### ISSUE TITLE
A11y_ADCS_Properties Of New Template_Screen Reader: NVDA is reading the label "Group or User name" when the focus is on the users list but not reading the label "Permissions for Authenticated Users" when the focus lands on the Allow/Deny Checkboxes

### ISSUE THREAD

**Issue by Shanmukha39** [nvaccess/nvda#10007]
Environment Details:
RDP: 10.91.4.95
User: atest\admin
Screen Reader: NVDA
​
Repro Steps:​
1)Open the app and login with appropriate credentials​
2)Tab till tools-->certification authority and press enter​
3)Activate Certificate Templates tab & Select Manage and press enter
4)Activate any one the item in the grid & select "Duplicate Template" and press enter
5)Tab till "Security" tab item
6)Start Screen Reader
7)Verify if Screen Reader is reading  the labels properly when the focus lands on the controls of the particular label

​Actual Result:​
NVDA is reading the label "Group or User name" when the focus is on the users list but not reading the label "Permissions for Authenticated Users" when the focus lands on the Allow/Deny Checkboxes

Expected Result:​
Screen Reader should read all the contents and controls properly.
NVDA should read the label "Permissions for Authenticated Users" when the focus lands on the Allow/Deny Checkboxes
![Bug_20578274_NVDA is not announcing label Permission for Enterprise Admins](https://user-images.githubusercontent.com/51434975/62213898-9a484b80-b3c1-11e9-9e39-42beea3dd22c.jpg)

​
User Impact:​
Visually Impaired Users or screen reader users will not be able to know what is the purpose or what the context is about if screen reader does not read the label properly
​
MAS Reference:​
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7B54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4%7D

**Comment by michaelDCurran** [comment]
Closing on request from reporter privately by email.
