### ISSUE TITLE
NVDA doesnt read images if they take too long to load, Ignoring alt tags in Firefox.

### ISSUE THREAD

**Issue by luisluix** [nvaccess/nvda#10009]
## Steps to reproduce: 
Get images in a website, something simple like:
```
<html>
<body>
    <img alt="image 1" src="1.png" />
    <img alt="image 2" src="2.png" />
    <img alt="image 3" src="3.jpg" />
    <img alt="image 4" src="4.png" />
    <img alt="image 5" src="5.png" />
</body>
</html>
```

throttle the internet connection to be slow and load the page.

### Actual behavior:
nothing is read, clicking control+home insert+down wont read anything, clicking G wont show any image at all. Even after the images have fully loaded nothing is detected by nvda, not even the alt tags. 
In full websites if the images take long to load they will be skipped entirely.
### Expected behavior:
image 1, image 2, image 3, image 4, image 5 read correctly even if the images havent loaded yet.
This is read correctly in chrome and IE.
#### NVDA version:
installed 2019.1.1
#### Windows version:
windows 10 pro 1809

I am using Firefox 68.0.1

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Tried the nightly and beta versions, issue still happens in both.

**Comment by Brian1Gaff** [comment]
I think you will find this has been around for a long time. it is not just 
graphics, you can find on even slightly slow loads, you have to bring up a 
menu and close it again for things to go back as they should be.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by luisluix** [comment]
> I think you will find this has been around for a long time. it is not just
graphics, you can find on even slightly slow loads, you have to bring up a
menu and close it again for things to go back as they should be.

what kind of menu? menus from my site and right clicking dont seem to fix the issue.

**Comment by DrSooom** [comment]
@luisluix: Press NVDA+F5 to update the (virtual) document.

**Comment by luisluix** [comment]
> @luisluix: Press NVDA+F5 to update the (virtual) document.

On the example that I provided nvda+f5 doesnt do anything.

**Comment by Adriani90** [comment]
@luisluix are you still seeing this issue in NVDA 2020.1 with Firefox 76?

**Comment by DrSooom** [comment]
See also: issue #11219
CC: @jcsteh

**Comment by jcsteh** [comment]
This was fixed in Firefox 75.
