### ISSUE TITLE
A11y_ADCS_Properties Of New Template_Screen Reader: NVDA is reading the text "Require the following for Enrollment" two times

### ISSUE THREAD

**Issue by Shanmukha39** [nvaccess/nvda#10006]
**Environment Details:**
RDP: 10.91.4.95
User: atest\admin
Screen Reader: NVDA
​
**Repro Steps:​**
1)Open the app and login with appropriate credentials​
2)Tab till tools-->certification authority and press enter​
3)Activate Certificate Templates tab & Select Manage and press enter
4)Activate any one the item in the grid & select "Duplicate Template" and press enter
5)Start Screen Reader
6)Verify if Screen Reader is reading all the contents, controls, links, images properly.

​**Actual Result:​**
NVDA is reading the text "Require the following for Enrollment" two times. 
Once its reading "Require the following for Enrollment" and again its announcing
"Require the following for Re enrollment" which is not present in the page

**Expected Result:​**
Screen Reader should read all the contents and controls properly. It should read the contents and control once.
​
**User Impact:​**
Visually Impaired Users or screen reader users will get confuse hearing the content two times
​
MAS Reference:​
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7B54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4%7D
![Bug_20580686_NVDA is reading the text require the following for enrollment two times](https://user-images.githubusercontent.com/51434975/62213579-ddee8580-b3c0-11e9-9243-f05f381b40ec.jpg)























**Comment by michaelDCurran** [comment]
Closing on request from reporter privately by email.
