### ISSUE TITLE
A11y_Dynamics 365 Relationship Insights (Relationship Assistant) + NA + TP_Talking Points_Screen Reader: NVDA is reading list with 2 items but it is not mentioning the position f list item when it is focused

### ISSUE THREAD

**Issue by SaisreeDandamudi** [nvaccess/nvda#10005]
**Environment Details:**
URL: https://kamsing901mar18org6.crm10.dynamics.com/ 
User Name: Tiptesttenant@tipregion.onmicrosoft.com
Server version: 9.1.0000.5616
Client version: 1.3.1865-190522-212622

**Repro Steps:**
1. Login to the application using URL: https://kamsing901mar18org6.crm10.dynamics.com/ with appropriate credentials
2. Tab to Dynamics 365 and press enter
3. Select Test app and press enter
4. Tab to contacts in sitemap and press enter
5. Tab to existing contact (Nancy Malhotra) and press enter
6. Tab to Talking points section
7. Change view to list view
8. Start NVDA
9. Tab list items 
10. Verify whether NVDA is reading position of list items like 1of 2, 2 of 2

**Actual Result:**
NVDA is reading list with 2 items but it is not mentioning the position f list item when it is focused

**Expected result:**
When NVDA is reading list with 2 items it should also read the position of list item when it is focused

**User Impact:**
Screen reader users face difficulty in using application if NVDA do not read list items with proper description

**MAS Reference:** 
https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

![Bug_1488485_NVDA issue](https://user-images.githubusercontent.com/51435580/62210532-00c96b80-b3ba-11e9-8fd4-2eb282b2be13.png)

**Comment by SaisreeDandamudi** [comment]
**Product Owner Comment On the Bug :** 
The problem is not related to code it is related external to NVDA .As edge with narrator is verifying list element and announcing them .Though we have implied role to list item but that is not enough for NVDA to recognize it . ARIA semantics for each HTML element [Informative only], whether a feature has implicit ARIA semantics [or something else] is defined in HTML  Accessibility API Mappings 1.0 <https://w3c.github.io/html-aam/>), it's up to the screen reader whether they announce the aria-label for any given element

**Comment by michaelDCurran** [comment]
Closing on request from reporter privately by email.
