### ISSUE TITLE
User Configuration: Delete Surplus Directories

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10014]
Since we're now using the Scratchpad directory to load app modules and other related data that used to be run directly from NVDA's user configuration directory, there's no longer a need to keep these hanging around. When a user updates their copy of NVDA, could we possibly check these directories, and if completely empty delete the following:

appModules

brailleDisplayDrivers

globalPlugins

synthDrivers

Other folders/files here immediately get created if they don't exist upon launching NVDA, so there's no point in removing anything else other than the above. This suggestion is mainly just to ensure that the configuration directory remains as tidy as possible!

**Comment by Adriani90** [comment]
Cc: @feerrenrut

**Comment by feerrenrut** [comment]
Happy for someone to look into this, it will require thorough testing and good explanation of the testing approach and results to prove the approach is robust.
