### ISSUE TITLE
Add-Ons Manager: Change default Button to "No" for Delete Add-On Confirmation Dialog

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10015]
When choosing to remove an add-on via the Add-Ons Manager, a warning is displayed; however, the "Yes" button is set as the default. To prevent accidental deletion of add-ons, would it be possible to change the default button that receives focus to "No"? This way, users will need to explicitly move focus to the "Yes" button; implementing this will decrease the likelyhood that add-ons are accidentally deleted.

**Comment by DrSooom** [comment]
This is the case with NVDA 2018.1. (NVDA 2019.2 RC1 wasn't tested by me.)

Furthermore I suggest to allocate the ESC key to the button "No". So pressing ESC will activate the button "No" as well.
