### ISSUE TITLE
Add-Ons Manager: Add button to Undo an Add-On Deletion

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10016]
If a user accidentally removes an add-on from within the Add-Ons Manager, NVDA doesn't currently delete the add-on until it's restarted. If an add-on is accidentally remove by a user, would it be possible to add an "Undo" button to the Manager to tell NVDA that the package shouldn't be removed? From memory, Firefox offers something similar; if the "Undo" button is clicked before the browser restarts, extension data is retained and the extension remains.

**Comment by DrSooom** [comment]
@elliott94: Please add the NVDA version to the issue description. Thanks.

Furthermore the devs must keep an eye regarding enabling/disabling add-ons as well when implementing such an undo feature.

**Comment by elliott94** [comment]
Is the version still required - even for future enhancement requests? I assumed that the lack of build number would suggest that this wasn't implemented yet; apologies if this is considered useful info.

**Comment by DrSooom** [comment]
Adding the NVDA version is always recommended due to historical reasons. In a few years you won't know which NVDA version was currently (in August 2019) the latest one.

**Comment by Adriani90** [comment]
cc: @hwf1324 maybe you could investigate this?

**Comment by hwf1324** [comment]
> cc: @hwf1324 maybe you could investigate this?

This Issue needs triage.

**Comment by Adriani90** [comment]
cc: @seanbudd, @SaschaCowley for triaging.
