### ISSUE TITLE
NVDA crashes on windows 10 1903  network adapter configuration dialogue

### ISSUE THREAD

**Issue by enessaribas** [nvaccess/nvda#10029]
### Steps to reproduce:
1. go to network and sharing center/change adapter settings.
2. press applications on a network adapter and chose properties. NVDA generates an error at this point
3. chose internet protocol version 4 IP4, and press the properties button. 
4. Try changing the automatically obtain an IP or DNS options to manual entry.
### Actual behavior:
 As stated previously, NVDA generates an error tone when opening the properties dialogue of a network adapter. Also, NVDA will not read the option chosen, and will generate an error. Moreover, the edit fields to enter information  are not read,  and error tones are generated.
### Expected behavior:
Errors are not generated, selection of the manual options in dialogues is read, and edit fields to input IP and DNS information are read as expected.
Error tone
yes
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
alpha-17808,4a780850
#### Windows version:
windows 10 1903, with all cumulative updates
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
[nvda.log](https://github.com/nvaccess/nvda/files/3463136/nvda.log)

**Comment by lukaszgo1** [comment]
I've fixed it in #9791. @enessaribas Please upgrade to the most recent Alpha. It is generally a good idea to update to the latest alpha before reporting an issue.

**Comment by enessaribas** [comment]
Hi,
I haven't upgraded to the latest alpha due to having an incompatible synthesizer. Thanks for the information.

**Comment by enessaribas** [comment]
hH
