### ISSUE TITLE
Website: Add Link to Download/Stream Podcast Episodes from the Podcast Page

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10022]
Currently, there's a link to the somewhat outdated but really informative NV Access Podcast on the main website (https://www.nvaccess.org/category/podcast/). Whilst you can browse to each individual podcast episode from this page, the actual links to download/stream the episodes appear to be missing; the only way to find them is to browse to the RSS feed for the podcast (https://www.nvaccess.org/category/podcast/feed/). Would it be possible to add these links to the main podcast category page?

**Comment by Qchristensen** [comment]
Can I ask what the interest in the podcasts is, given how out of date they are?  EG Is there any information in the podcasts which we haven't published a more up-to-date version of in another format?  Or information you can't find elsewhere?

**Comment by elliott94** [comment]
> 
> 
> Can I ask what the interest in the podcasts is, given how out of date they are? EG Is there any information in the podcasts which we haven't published a more up-to-date version of in another format? Or information you can't find elsewhere?

There's nothing of use concerning the use of NVDA; I just really enjoy the informal attitude of how these are produced. It'd be good to get more in this style!

**Comment by zahra21** [comment]
hi.
i vote for this great positive addition in nvda website too.

**Comment by Adriani90** [comment]
Given the discontinued podcast series, I am closing this issue. @Qchristensen I guess if the podcasts will continue, then the web page for that will be redesigned anyway. Then we would need an updated issue description anyway.
