### ISSUE TITLE
Config Clean-up: Only Generate Files/Folders when Needed by NVDA

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10027]
When NVDA generates a fresh set of config data, the following files/folders are included by default:

addons

profiles

speechDicts

updates

addonsState.pickle

nvda.ini

Besides the main config file (nvda.ini), purely to clean up the default set of data that is generated, could we:

1. Only generate the "addons" directory the first time an add-on is actually installed

2. Only generate the "profiles" directory the first time that a new profile is created

3. Only generate the "speechDicts" directory if a user chooses to create a custom dictionary

4. Only generate the "updates" directory if a user has a pending update ready to install, or actually has automatic update checks enabled (this directory is still generated even if the latter isn't enabled)

5. Only generate the "addonsState.pickle" file if any add-ons are present, or NVDA detects the presence of the "addons" directory

**Comment by Adriani90** [comment]
cc: @seanbudd what is the position at NV Access on this request?

**Comment by seanbudd** [comment]
Closing as won't fix. I don't see a clear reason to do this. Empty directories don't exactly take up much space.
