### ISSUE TITLE
Lost speech in MS Excel: the treeInterceptor is killed when deleting a row

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#10028]
### Steps to reproduce:

* Open a spreadsheet in Excel.
* Delete a row by pressing control+-.

Edit: I earlier stated that you didn't have to go through with the deletion, and the error was still prompted. That is incorrect--you must actually do the deletion.

### Actual behavior:

After dealing with the deletion dialog, the browse mode normally in use with Excel is exited, and thus no part of the sheet will read until something is done to re-focus the application.
(Alt+tab, or just alt then escape to temporarily invoke the ribbon, or F5 then escape to bring up the Go-to dialog then close it, etc.)

### Expected behavior:

After deleting a row, cell, or whatever, sheet navigation continues as usual.

#### NVDA installed/portable/running from source:

Installed or run from installer.

#### NVDA version:

beta-18270,90516aec

#### Windows version:

1903 (OS Build 18362.239)

#### Name and version of other software in use when reproducing the issue:

Microsoft Office 2019

#### Other information about your system:

Log attached. "Mark 2" shows where I started trying to navigate the sheet after the error. "Mark 3" shows object information in case that is useful.
[lost focus in excel 1.txt](https://github.com/nvaccess/nvda/files/3463008/lost.focus.in.excel.1.txt)

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

2019.1.1: same
2018.4rc2: same.

**Comment by lukaszgo1** [comment]
@XLTechie Could you check with 2018.4.1? There were some changes to Excel support in 2019.1 which might be causing this.

**Comment by XLTechie** [comment]
> @XLTechie Could you check with 2018.4.1? There were some changes to Excel support in 2019.1 which might be causing this.

Unless I'm being particularly thick, they don't make it easy to find those old versions, do they? Anyway, I was able to get a copy of 2018.4RC2, which should be sufficient for this purpose I think. Its performance is ridiculously bad, both before and after the error, but bottom line is that the result is the same as modern versions, it just doesn't recover nearly so well. Identical comError though.

**Comment by lukaszgo1** [comment]
Just for reference it isn't reproducible on Excel 2010 32-bit

**Comment by XLTechie** [comment]
I should have specified that I'm using 64bit.

**Comment by DrSooom** [comment]
[Here](https://github.com/nvaccess/nvda/files/3464382/10028_NVDA.2019.2.RC1_Excel.2010.32-Bit.txt) is the logfile for Microsoft Excel 2010 (32-Bit) on Win7x64 with NVDA 2019.2 RC1 (Portable). The above mentioned issue isn't reproducible, but two others. Search for "//" in the logfile.

**Comment by Adriani90** [comment]
@XLTechie I wonder if this is still reproducible after maximizing the window and after running the COM registration fixing tool. Did you try this already?

**Comment by Adriani90** [comment]
Still reproducible with NVDA alpha-20220,1c4519a6 and Excel 365, I am on 32bit version. Following is in the log:

```
IO - inputCore.InputManager.executeGesture (13:27:37.991) - winInputHook (15048):
Input: kb(laptop):downArrow
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (13:27:38.033) - MainThread (7156):
oleacc.AccessibleObjectFromEvent with window 199124, objectID 120 and childID 0: [WinError -2147467259] Unbekannter Fehler
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (13:27:38.033) - MainThread (7156):
oleacc.AccessibleObjectFromEvent with window 199124, objectID 122 and childID 0: [WinError -2147467259] Unbekannter Fehler
IO - inputCore.InputManager.executeGesture (13:27:38.281) - winInputHook (15048):
Input: kb(laptop):leftArrow
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (13:27:38.331) - MainThread (7156):
oleacc.AccessibleObjectFromEvent with window 199124, objectID 127 and childID 0: [WinError -2147467259] Unbekannter Fehler
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (13:27:38.331) - MainThread (7156):
oleacc.AccessibleObjectFromEvent with window 199124, objectID 129 and childID 0: [WinError -2147467259] Unbekannter Fehler
IO - inputCore.InputManager.executeGesture (13:27:38.511) - winInputHook (15048):
Input: kb(laptop):downArrow
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (13:27:38.551) - MainThread (7156):
oleacc.AccessibleObjectFromEvent with window 199124, objectID 134 and childID 0: [WinError -2147467259] Unbekannter Fehler
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (13:27:38.571) - MainThread (7156):
oleacc.AccessibleObjectFromEvent with window 199124, objectID 136 and childID 0: [WinError -2147467259] Unbekannter Fehler
IO - inputCore.InputManager.executeGesture (13:27:38.766) - winInputHook (15048):
Input: kb(laptop):upArrow
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (13:27:38.791) - MainThread (7156):
oleacc.AccessibleObjectFromEvent with window 199124, objectID 142 and childID 0: [WinError -2147467259] Unbekannter Fehler
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (13:27:38.791) - MainThread (7156):
oleacc.AccessibleObjectFromEvent with window 199124, objectID 143 and childID 0: [WinError -2147467259] Unbekannter Fehler
```


This is not reproducible in Excel 2010.

Moreover, this issue occurs only when deleting rows, not when deleting columns or moving cells up or down, left or right.

**Comment by Adriani90** [comment]
Can Anyone still on office 365 32bit reproduce this issue?

@XLTechie on 64bit I cannot reproduce.

**Comment by Adriani90** [comment]
No updates for this issue upon request since many years, I am closing as abandoned. If you are still having this issue, please comment and we can reopen.

**Comment by CyrilleB79** [comment]
Cannot reproduce on Microsoft® Excel® 2016 MSO (Version 2405 Build 16.0.17628.20006) 32 bits.
