### ISSUE TITLE
Core: Directly Integrate message.html into NVDA

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10026]
In #6804, I asked a question as to why there was a random file named "message.html" that gets included in the main NVDA distribution; an explanation was provided, and the issue closed.

Is there any way that we can implement the functionality of this particular file directly into NVDA's core? I realise that this may not in reality bring any advantages to users, but it would clean up one file from the distribution.

**Comment by feerrenrut** [comment]
While we could embed it as a string in a python file, I don't think this makes sense. The content of this file is html and javascript, it is much more sensible it lives in a html file.

I'm going to close this issue.
