### ISSUE TITLE
latest master branch builds an unrunnable launcher.

### ISSUE THREAD

**Issue by stickbear2015** [nvaccess/nvda#10039]
### Steps to reproduce:
pull latest master branch, run scons launcher to build the launcher.
### Actual behavior:
here's the output from scons first.
PS D:\dropbox\src\nvda\screen-reader> .\scons launcher
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
miscDeps\tools\NSIS\makensis /V2 /DVERSION=source-master-be63d19 /DPUBLISHER="unknown" /DCOPYRIGHT="Copyright (C) 2006-2
019 NVDA Contributors" /DVERSION_YEAR="2019" /DVERSION_MAJOR="3" /DVERSION_MINOR="0" /DVERSION_BUILD="0" /DNVDADistDir=D
:\dropbox\src\nvda\screen-reader\dist /DLAUNCHEREXE=D:\dropbox\src\nvda\screen-reader\output\nvda_snapshot_source-master
-be63d19.exe launcher\nvdaLauncher.nsi
scons: done building targets
I then run 

PS D:\dropbox\src\nvda\screen-reader\output> .\nvda_snapshot_source-master-be63d19.exe
and receive
The specified resource type cannot be found in the image file.
Could not locate script resource:
### Expected behavior:
launcher should run without problems.
#### NVDA installed/portable/running from source:
running from source
#### NVDA version:
master-be63d19
#### Windows version:
Microsoft Windows
Version 1903 (OS Build 18362.175)
#### Name and version of other software in use when reproducing the issue:
git latest release, all deps met for NVDA to run. windows power shell for scons to run
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

**Comment by lukaszgo1** [comment]
Have you tried doing the same from cmd? For me it works.

**Comment by stickbear2015** [comment]
doing scons from an admin level cmd prompt seems to have fixed it.
I'm so used to powershell....

**Comment by stickbear2015** [comment]
issue closed as the user sucks, lol.

**Comment by lukaszgo1** [comment]
It's strange, because I am able to build launcher using Powershell just fine. I am however still on Windows 7 so it might make a difference. BTW there is no need to building from admin cmd running as a standard user works just fine.

**Comment by stickbear2015** [comment]
I'm running windows 10. this entire installation is becoming a jerk and might require a reinstall, but anyhow...
