### ISSUE TITLE
A11y_AzDev Test Runner (Azure Test Plans)_Create a bug_Screen Reader: When we try to add tags using keyboard, after we press enter key, a new field is getting opened to add the tag but NVDA is reading as "no search results found" immediately

### ISSUE THREAD

**Issue by InduPriya1805** [nvaccess/nvda#10042]
**Environment Details:**
Install app from https://acctesting.visualstudio.com/​
OS Name: Microsoft Windows 10 Enterprise​
Version: 1903, 10.0.18362 Build 18362​
Google Chrome Version 75.0.3770.142
​
**Repro Steps:​**
1. Hit the URL: https://acctesting.visualstudio.com/ and log in with appropriate credentials.​
2.  Navigate to Test Plans-->Open any test plan​
3. Select any test case-->Select Run for desktop Application from the "Run" drop down and download the test runner for the desktop.​
4. Tab till create new bug and press enter​
5. Tab till "add tag" button and press enter. Verify NVDA "no search results found" immediately after user presses enter key or not​
​
**Actual result:** ​
When we try to add tags using keyboard, after we press enter key, a new field is getting opened to add the tag but NVDA is reading as "no search results found" immediately​
​
**Expected Result:​**
NVDA should not read as "no search results found" immediately after user presses enter key. It should read the message after user types something in the edit field​
​
**User Impact:​**
Disabled users may get confused if screen reader reads immediately as "no search results found" without typing anything​
​
**MAS Reference:​**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4} 

**Attachments:**
[Bug_10042_reading as no search results.pptx](https://github.com/nvaccess/nvda/files/3472058/Bug_10042_reading.as.no.search.results.pptx)

**Comment by michaelDCurran** [comment]
Closing on request from reporter privately by email.
