### ISSUE TITLE
Command line switch to specify language on startup

### ISSUE THREAD

**Issue by ScottChesworth** [nvaccess/nvda#10044]
#9648 # Is your feature request related to a problem? Please describe.
I was flying blind (with no speech) in the preferences dialog, attempting to direct speech output to an audio device that'd just been plugged in when I accidentally set my language to Hebrew. Admittedly this was user error, but once set, getting the language switched back to my usual choice of "User default" was a task and a half.

### Describe the solution you'd like
Could a command line switch to force language on startup be implemented? Section 15.1 of the user guide has all sorts of useful switches, but I didn't see language mentioned there.

### Describe alternatives you've considered
Well, I guess I could be more careful... :)

**Comment by DrSooom** [comment]
Pressing NVDA+CTRL+R would help here, as long as the current configuration wasn't saved on exiting NVDA. Maybe a command line flag to force eSpeak NG with default settings as TTS would be a possible solution here.

And as a second step, a command line flag for the GUI language wouldn't bad too.
