### ISSUE TITLE
NVDA remote

### ISSUE THREAD

**Issue by bedenhofer** [nvaccess/nvda#10067]
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

### Expected behavior:

I'm running the beta version of NVDA, whitch is up to python version 3 and NVDA remote no longer works, whatsoever, I'm using a laptop, with windows10 home adition, that's the machine I run it on.### System configuration

**Comment by XLTechie** [comment]
NVDA Beta is not using Python 3. Beta uses Python 2. Alpha uses Python 3.

Regardless, please contact the developers of the NVDA Remote add-on. It is a 
complex piece of software, and they are in the best position to help you. 
Barring that, try the nvda@groups.io mailing list, which is the user support 
mailing list, and has many NVDA remote users.

Lastly, for your next issue, please fill in the full bug report template. You have given very little of the information anyone would 
need to help you. Filling in the bug report template completely would provide 
that information.
That said, the mailing list or NVDA remote authors can best help you here. This 
is not an NVDA bug, it is an NVDA Remote problem.

**Comment by XLTechie** [comment]
To subscribe to the users list, send an email to: nvda+subscribe@groups.io

NVDA Remote has its own issue tracker at: https://github.com/NVDARemote/NVDARemote/issues
And its own website at: http://nvdaremote.com

**Comment by Adriani90** [comment]
Closing as per information above. @XLTechie thanks for your helping input.
