### ISSUE TITLE
russian Vocalizer does not read well when another vocalizer is installed

### ISSUE THREAD

**Issue by sigala2z** [nvaccess/nvda#10075]
Steps to reproduce:
1. go to this site: https://vocalizer-nvda.com/downloads
2. download russian vocalizer: Yuri ru_RU - Russian (Russia) 	Premium High
 download a second language vocalizer(any language)
4. install.
5. check reading form lables with NVDA in this form for example :https://www.aeroflot.ru/ru-ru

Actual behavior:
reads russian well in the whole website but does not read the labels  in the form.

Expected behavior:
reads the form labels in russian as well

System configuration:
 NVDA installed
2 different languages vocalizers are installed 
NVDA version:19.1.1
 Windows version:10

 Does the issue still occur after restarting your PC?
yes
log:
[log.txt](https://github.com/nvaccess/nvda/files/3491430/log.txt)

**Comment by ruifontes** [comment]
Hello!
That is an error of Aeroflot...
If you see the HTML code, you'll find the following first line:
<!doctype html><html lang="en"><head><meta 
charset="UTF-8"><title>Aeroflot</title><meta name="

And you'll see the page is codified in english... So, Vocalizer will use 
an english voice...
Rui Fontes

Às 09:02 de 12/08/2019, sigala2z escreveu:

**Comment by sigala2z** [comment]
Hi thank you but I see that the lang is correct 
https://www.aeroflot.ru/ru-ru
please see the screenshot: 
![image](https://user-images.githubusercontent.com/54019506/62859121-eb7f0600-bd04-11e9-99b5-63d60a3a5a8f.png)

**Comment by ruifontes** [comment]
1 - I can't see screenshots since I am blind.

2 - The HTML code of that page still have lang attribute set to EN, 
english...

Rui Fontes


Às 11:27 de 12/08/2019, sigala2z escreveu:

**Comment by sigala2z** [comment]
thank you I have changed a few details in my original question. the problem apparently was caused because I have installed two different vocalizers, one in russian and one in hebrew , and that what caused a conflict and bugs when NVDA tried to read the page.
