### ISSUE TITLE
Vocalizer does not read well when another vocalizer is installed 

### ISSUE THREAD

**Issue by sigala2z** [nvaccess/nvda#10079]
Steps to reproduce:

   1. go to this site: https://vocalizer-nvda.com/downloads
  2.  download russian vocalizer: Yuri ru_RU - Russian (Russia) Premium High
   3.  download any second language vocalizer(any language)
  4.  install.
 5.  check reading form lables with NVDA in this form for example :https://www.aeroflot.ru/ru-ru

Actual behavior:
reads russian well in the whole website but does not read the labels in the form.

Expected behavior:
reads the form labels in Russian as well, even though another/different language vocalizer is also installed.

System configuration:
NVDA installed
2 different languages vocalizers are installed
NVDA version:19.1.1
Windows version:10

Does the issue still occur after restarting your PC?
yes

**Comment by ruifontes** [comment]
As I said, the page have the lang attribute set to EN, english...
NVDA will honor the attribute and will not change to russian.

**Comment by sigala2z** [comment]
not the issue here (let it go:-) but thank you .

**Comment by DrSooom** [comment]
@sigala2z: Please disable "Automatic Language switching" and "Automatic Dialect switching" in the Speech NVDA Settings for each TTS separately and try again. Thanks.

**Comment by sigala2z** [comment]
thank you DrSooom :))
