### ISSUE TITLE
In the GitHub code editor, the gesture to move the braille display to the previous line does not work reliably

### ISSUE THREAD

**Issue by charadani** [nvaccess/nvda#10072]
### Steps to reproduce:

1. Get to www.github.com, and select one of your repositories.
2. Select the Find File tab, and open a file, for instance, the readme.md 
3. Tab until you get to the edit box, which NVDA will name as "section editable". This is where the file contents are (the issue does not occur in the file name edit box).
4. Use your up and down arrow keys and your braille specific gestures to move braille one line up and down.

### Actual behavior:

When you use your up and down arrow keys, NVDA will move through the lines of the file. However, when you use your braille gestures, NVDA will not move upwards through the file. the only specific braille gesture working is the one which moves the braille display to the next line.

### Expected behavior:

In the default NVDA configuration, the gesture "Moves the braille display to the previous line" should move the braille display to the previous line of text, same as the up arrow key does.

#### NVDA installed/portable/running from source:

Installed and portable.

#### NVDA version:

2019.2 RC2.

#### Windows version:

Version 1903 (OS Build 18362.239)

#### Name and version of other software in use when reproducing the issue:

Google Chrome and Mozilla Firefox, last versions available as of the date of the report.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Similar behavior in Alpha versions of NVDA. Last one tested is Version: alpha-18330,b4db7dca

**Comment by DrSooom** [comment]
Google Chrome 76.x and Mozilla Firefox 68.x.

**Comment by Adriani90** [comment]
@charadani are you still having this issue with NVDA 2023.1 or NVDA last alpha?

**Comment by charadani** [comment]
Thanks for folowing up.  It still happens in V 2023.1. Not sure about
Alpha, will update when tested.
Daniel Montalvo Charameli

**Comment by Adriani90** [comment]
@charadani is this also reproducible in NVDA 2024.2?
cc: @LeonarddeR

**Comment by Adriani90** [comment]
cc: @burmancomp, @Emil-18 could you please test whether this issue still occurs? This would be very helpful.

**Comment by charadani** [comment]
Thanks @Adriani90 

This now works as expected.
