### ISSUE TITLE
Braille doesn't follow when braille display is tethered to review

### ISSUE THREAD

**Issue by Andre9642** [nvaccess/nvda#10081]
### Steps to reproduce:
1. Pick a virtual buffer, terminal or multi-line field.
2. Enable — braille display follows the review cursor — option (NVDA+control+t).
3. Use arrow keys or write some text.

### Actual behavior:
Braille is not refreshed.

### Expected behavior:
Braille should be refreshed

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-18371,ac5ab409

#### Windows version:
Windows 10Ver1903

#### Name and version of other software in use when reproducing the issue:
notepad, Firefox, cmd, etc..

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The bug is recent with alpha versions (at least the previous alpha is concerned).

**Comment by leonardder** [comment]
Can you reproduce this in NVDA 2019.2RC2?

If not, it would be nice if you could check the threshold branch as 
well. That hasn't had updates since it was merged to master, so it might 
give us information on when the bug was introduced.

**Comment by Andre9642** [comment]
@leonardder No problem with NVDA 2019.2RC2.

**Comment by Andre9642** [comment]
Problem solved. I accidentally enabled – Follow System Caret — option (with NVDA+6).
So it's not an issue. My apologies.
