### ISSUE TITLE
Update UI changing state all the time causing repeated message

### ISSUE THREAD

**Issue by larry801** [nvaccess/nvda#10086]
### Steps to reproduce:
1.Check for update
2.Start to download
3. Press tab to switch to "Show details"
### Actual behavior:
NVDA keeps reading the following content.
Show details  button  collapsed
expanded
collapsed
Hide details
expanded
Show details
collapsed
Hide details
Show details
Hide details
Show details
expanded
collapsed
Hide details
Show details

### Expected behavior:
NVDA only read the button once
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-18368
#### Windows version:
Windows 8.1 
#### Other information about your system:
IO - speech.speak (21:21:24.911):
Speaking [LangChangeCommand ('cmn'), 'Show details']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:24.914):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 55 and childID 0: [WinError -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:24.914):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 56 and childID 0: [WinError -2147467259] Unspecified error
IO - inputCore.logTimeSinceInput (21:21:25.700):
10.875 sec since input
IO - speech.speak (21:21:25.701):
Speaking [LangChangeCommand ('cmn'), 'Hide details']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:25.715):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 57 and childID 0: [WinError -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:25.715):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 58 and childID 0: [WinError -2147467259] Unspecified error
IO - inputCore.logTimeSinceInput (21:21:25.721):
10.896 sec since input
IO - speech.speak (21:21:25.721):
Speaking [LangChangeCommand ('cmn'), 'Show details']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:25.725):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 59 and childID 0: [WinError -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:25.725):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 60 and childID 0: [WinError -2147467259] Unspecified error
IO - inputCore.logTimeSinceInput (21:21:32.811):
17.987 sec since input
IO - speech.speak (21:21:32.811):
Speaking [LangChangeCommand ('cmn'), 'Hide details']
IO - inputCore.logTimeSinceInput (21:21:32.815):
17.991 sec since input
IO - speech.speak (21:21:32.815):
Speaking [LangChangeCommand ('cmn'), 'expanded']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:32.821):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 61 and childID 0: [WinError -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:32.821):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 62 and childID 0: [WinError -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:32.824):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 63 and childID 0: [WinError -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:32.824):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 64 and childID 0: [WinError -2147467259] Unspecified error
IO - inputCore.logTimeSinceInput (21:21:32.831):
18.007 sec since input
IO - speech.speak (21:21:32.832):
Speaking [LangChangeCommand ('cmn'), 'Show details']
IO - inputCore.logTimeSinceInput (21:21:32.836):
18.012 sec since input
IO - speech.speak (21:21:32.837):
Speaking [LangChangeCommand ('cmn'), 'collapsed']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:32.838):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 65 and childID 0: [WinError -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:32.838):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 66 and childID 0: [WinError -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:32.841):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 67 and childID 0: [WinError -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:32.841):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 68 and childID 0: [WinError -2147467259] Unspecified error
IO - inputCore.logTimeSinceInput (21:21:33.220):
18.395 sec since input
IO - speech.speak (21:21:33.220):
Speaking [LangChangeCommand ('cmn'), 'expanded']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:33.228):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 69 and childID 0: [WinError -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:33.228):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 70 and childID 0: [WinError -2147467259] Unspecified error
IO - inputCore.logTimeSinceInput (21:21:33.234):
18.409 sec since input
IO - speech.speak (21:21:33.234):
Speaking [LangChangeCommand ('cmn'), 'collapsed']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:33.243):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 71 and childID 0: [WinError -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:21:33.243):
oleacc.AccessibleObjectFromEvent with window 2361016, objectID 72 and childID 0: [WinError -2147467259] Unspecified error
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by Adriani90** [comment]
This is actually a duplicate of #9624. However, I will close that one in favor of this one because this one contains also fragment of the log file.

**Comment by Adriani90** [comment]
@larry801 this seems fixed now. Could you please test with last NVDA alpha?

**Comment by larry801** [comment]
There is no update available, may be wait for next developer build?

**Comment by larry801** [comment]
When updating to alpha-20974 this issue no longer occur.
