### ISSUE TITLE
Old library files for libArm64 not cleaned like lib and lib64

### ISSUE THREAD

**Issue by larry801** [nvaccess/nvda#10084]
### Steps to reproduce:
Update nvda multiple times (3 or more)
### Actual behavior:
Many old library files under libArm64 folder is kept, which take up a lot of disk space.
### Expected behavior:
Only two copies are kept at most , just like lib and lib64 folder
### System configuration
Any version after libArm64 is introduced
#### NVDA installed/portable/running from source:
Installed

**Comment by lukaszgo1** [comment]
This one is fixed in #10085 and should be closed.

**Comment by Adriani90** [comment]
Closing as works for me
