### ISSUE TITLE
GitHub - Templates: Modify Question about Restarting PC

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10107]
I realise that this is purely cosmetic, but when reporting a bug and using the provided GitHub template, a question is asked as to whether a user has restarted their PC. Could we possibly consider changing the word "PC" to "device"? I've always considered PCs to mean desktops - device would include desktops, laptops, and Windows-based tablets as well as any other devices that Windows can run on.

**Comment by lukaszgo1** [comment]
I believe term PC is used here in accordance with this Wikipedia definition:
>  A personal computer (PC) is a multi-purpose computer whose size, capabilities, and price make it feasible for individual use. Personal computers are intended to be operated directly by an end user, rather than by a computer expert or technician. Unlike large costly minicomputer and mainframes, time-sharing by many people at the same time is not used with personal computers.

**Comment by Brian1Gaff** [comment]
If you say machine than that would work, then should somebody design a pc 
into a milk bottle you are covered grin....
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by DrSooom** [comment]
Suggestion: "Does the issue still occur after restarting Windows?"

Please note that the shutdown/reboot procedure has been changed in Windows 10 in compare to older Windows versions. If you shut down Windows, it will just log you off and then switch into the hibernate mode (ACPI-S4). Therefore we maybe have to explain in the wiki article how to correctly reboot Win10 machines.

**Comment by Adriani90** [comment]
addressed by PR #10720.. Thanks for reporting. I am closing this issue since it is a very small change which could also be discussed on the NVDA users mailing list.
