### ISSUE TITLE
UIA console: when typing in the console, characters are wrongly pronounced regardless of the keyboard layout

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#10113]
### Steps to reproduce:
1. open a console window with the uia console option turned on, for example a wsl console
. switch to croatian or to the US keyboard language. I am not aware of other layouts having the problem which i will describe here thoroughly
russian keyboard is also included there
2. try to type  or ], ; or ', \ or /
### Actual behavior:
note: here are given the corresponding keys on the us keyboard. these keys are wrongly interpreted by NVDA also on oother non-us keyboard layout
for example / slash on US keyboard is interpreted as apostrophe,
; as č, the croatian diacritic mark, and so on.
### Expected behavior:
the signs should be interpreded bz NVDA as these are written on the kezboard respectivelz
#### NVDA installed/portable/running from source:
NVDA installed
#### NVDA version:
Latest alpha
#### Windows version:
18362 latest indows 10 1903
#### Name and version of other software in use when reproducing the issue:
n-a
#### Other information about your system:
to reproduce this bug, you should have turned on have character echo turned on
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
n/a

**Comment by lukaszgo1** [comment]
cc @codeofdusk

**Comment by codeofdusk** [comment]
> cc @codeofdusk

This is probably a bug with Windows keyboard hooks. Look at the block starting at around line 196 of the `keyboardhandler` module and the [Win32 ToUnicodeEx function](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-tounicodeex).
