### ISSUE TITLE
Incorrect behavior of "review bottom line" in Windows Console

### ISSUE THREAD

**Issue by codeofdusk** [nvaccess/nvda#10119]
### Steps to reproduce:
1. Open Command Prompt.
2. Invoke "review bottom line" (desktop layout: shift+numpad 9).

### Actual behavior:
On Windows 10 1803, the last line of output is read as expected, but the review cursor is placed out of bounds: after invoking "review bottom line", blank lines at the end of the output become accessible that previously weren't.

On Windows 10 1903, NVDA says blank. "read current line" also reports blank, but attempting to review the next line says "bottom" followed by the last line of output.

### Expected behavior:
The last line of output is reported and the review cursor is placed there. The review cursor stays within the console bounds (i.e. no blank lines are exposed when the script is invoked).

#### NVDA installed/portable/running from source:
Installed and source.

#### NVDA version:
Latest `master` branch.

#### Windows version:
Windows 10 version 1803 and 1903.

#### Name and version of other software in use when reproducing the issue:
Windows Console (Command Prompt)

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

**Comment by codeofdusk** [comment]
This issue is likely caused by an unreliable `lastVisiRange`. See the initialization for a `ConsoleUIATextInfo` at `POSITION_LAST` (around line 35 of `NVDAObjects/UIA/winConsoleUIA.py`).

Cc @feerrenrut @leonardder @michaelDCurran

**Comment by michaelDCurran** [comment]
@leonardder  I have improved comments as requested. However, I did not take your suggestion of changing the makeTextInfo call into a direct WinConsoleUIATextInfo construction as this is not needed in the move method -- it can stay high-level. The only reason I did it in WinConsoleUIATextInfo's ```__init__``` method was because I was passing in _rangeObj which makeTextInfo does not allow.
