### ISSUE TITLE
A combobox in the settings to change the volume from 5 percent to 10.

### ISSUE THREAD

**Issue by audiogamer22** [nvaccess/nvda#10117]
I'd like to change the volume back to how it used to be, but for those who like this new volume, have a combobox so we can choose what we like.
### Is your feature request related to a problem? Please describe.
I don't like the new volume control in the NVDA settings ring, I prefered the older 10 percent instead of 5.
### Describe the solution you'd like
A combobox where you can choose either 5 or 10 percent.
### Describe alternatives you've considered
None.
### Additional context
I know this feature was added for those that use headphones but I still think being able to have the choice is much better than being stuck using something you don't like.

**Comment by DataTriny** [comment]
Hello @audiogamer22,
I am the developer who implemented this change. I understand your point, and I know adding such a feature is not a big deal. However, do you really think this is necessary? I doubt @feerrenrut would agree on letting the user configure such a small setting.
Furthermore, what makes you dislike this change? Can you elaborate on it?
Thanks!

**Comment by XLTechie** [comment]
Maybe the author of the Synth Ring Settings Selector add-on could be persuaded 
to add a flag that reverts this behavior if selected?

I can't imagine such a feature ever being approved for core.

**Comment by leonardder** [comment]
Personally, I think I would approve a hidden setting in the config spec that allows controlling this step size.

**Comment by DrSooom** [comment]
@leonardder: And one more hidden setting. Argh. See issue #9206. But I like this idea. 😉

**Comment by feerrenrut** [comment]
I think it would be better to implement this with an addon rather than in NVDA.
