### ISSUE TITLE
In Rich text area NVDA stops talking

### ISSUE THREAD

**Issue by rakesh-a11y** [nvaccess/nvda#10121]
When navigating the visual editor in the rich text editor of Wordpress and NVDA encounters a link the NVDA voice is stopped. NVDA is running but the content is not read aloud.
### Steps to reproduce:
1. Open Firefox browser.
2. Navigate to a new post in Wordpress admin.
3. Activate Visual button if the edit area is currently set to text. (this is in the old classic editor of WP)
3. Create a link eg: type Facebook, select and hit Control + K to fill in the URL and tab to apply.
4. Press apply to insert the link in the editor.
5. Now with arrow keys move to the newly created link to check it is inserted.
6. NVDA stops talking.
### Actual behavior:
NVDA stops reading. Manually one have to restart NVDA to continue reading.
### Expected behavior:
NVDA should read the content in the rich editor including the link as if it is in a browse mode.

#### NVDA installed/portable/running from source:
NVDA installed.
#### NVDA version:
NVDA 2019.2
#### Windows version:

OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17134 Build 17134

#### Name and version of other software in use when reproducing the issue:
Mozilla Firefox 68.0.2 (64-bit)
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
[nvda.log](https://github.com/nvaccess/nvda/files/3519805/nvda.log)

**Comment by Adriani90** [comment]
cc: @jcsteh

**Comment by jcsteh** [comment]
I see you're using OneCore speech. Are you able to temporarily test this with a different speech synthesiser?

Unfortunately, this log file doesn't contain sufficient information. Please set your log level to debug in NVDA's General Settings and provide another log. Note that this includes information about what is spoken and typed, so be sure you don't enter or encounter any sensitive information while the log level is set this way.

**Comment by leonardder** [comment]
@rakesh-a11y: Could you please provide an anser to @jcesth's questions in https://github.com/nvaccess/nvda/issues/10121#issuecomment-523241702?

**Comment by rakesh-a11y** [comment]
In the recent past I am not facing this issue. Perhaps this issue got resolved.

**Comment by leonardder** [comment]
In that case, closing this as works for me. We can always reopen if the problem returns.
