### ISSUE TITLE
New synthesizer in Portuguese Brazil Leticia cutting phrases

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#10126]
### Steps to reproduce:
download synthesizer in portuguese Brazil called Leticia:
It can be found at the link:

https://public.f123.org/download/Leticia-F123/19.08.03/Letícia F123-19.08.03-NVDA.zip

The voice is free.
It is necessary to install the 3 addons.
Choose from the nvda synthesizer the rh voice synthesizer.
Now note that using the nvda synthesizer nvda cuts several sentences as an example:
enter the notebook.
expected that nvda announces:
Untitled notepad, multi line editing.
What happens is that nvda announces:
untitled notepad
nvda does not advertise:
Multi line editing.
By selecting a check box nvda does not advertise checked or unchecked.
This is a problem with the synthesizer, if using another synthesizer as windows one core voices the errors do not occur.
In the attached log note that there are several errors.
But in the log it is as if the phrase multi-line editing had been pronounced but actually wasn't.
I have also reported this to the f123 organization, I open this to nvda in the hope that also nv access can help in some way.
### Actual behavior:
Nvda cuts several phrases during use.
### Expected behavior:
nvda should read your entire speech as when using other synthesizers.
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
alfa 18420
#### Windows version:
17763.615

#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
[leticia.txt](https://github.com/nvaccess/nvda/files/3520631/leticia.txt)

**Comment by zstanecic** [comment]
1.	It’s python3 and speech refactor,
2.	The link is not working

**Comment by Mary5958** [comment]
The correct link is:
https://public.f123.org/download/Leticia-F123/19.08.03/Let%C3%ADcia%20F123-19.08.03-NVDA.zip
In sayAll the reading stops after a few lines or sometimes even after a sentence when there is still more after that on the same line.

**Comment by Adriani90** [comment]
cc: @leonardder

**Comment by zstanecic** [comment]
Hi Adriani,

This synth needs to be ported for the speech refactor. It is compatible with NVDA 2019.3 alpha, but it has problems with indexes and say all.

Pitch command is broken also with the capital letters.

Cc 

@beqabeqa473

You can confirm this, as it is the case with version 0.7.2, for russian and other langs.

**Comment by zstanecic** [comment]
update:
the error with the brazilian portuguese RHVoice is fixed,
please see the repo of the synthesizer.
The synthesizer is compatible with new alpha snapshots based on PY3 and no cutting is heard. i can send the build here , so that you can verify this.

**Comment by Adriani90** [comment]
@zstanecic thank you very much for the update. Please feel free to post the link here so followers of this issue can find it easily. I am closing this for now as works for me.

**Comment by zstanecic** [comment]
Here are all languages including brasilian portuguese

Please feel free to test this, even on NVDA 2019.3.

https://yadi.sk/d/DlKMwTS_bF0aMg
