### ISSUE TITLE
Meta issue: NVDA often reads web element status, atributes or descriptions twice in all browsers

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#10140]
### Steps to reproduce:
This is a meta issue for several issue with the same effect on user experience, namely that information is spoken twice in browsers. For repro, please see each issue referenced here.

### Actual behavior:
NVDA repeats information twice.

### Expected behavior:
NVDA should report information once when focusing the coresponding element.

#### NVDA installed/portable/running from source:
both installed and portable

#### NVDA version:
2019.2

#### Windows version:
valid for all Windows versions

#### Name and version of other software in use when reproducing the issue:
Firefox 67, Chrome 76 and IE11

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, different versions until NVDA 2016.1.

**Comment by Adriani90** [comment]
following issues are dealing with this problem:

#10139, #10066, #9914, #9723, #9653, #9645, #9555, #8960, #8707, #7841, #7823, #7358, #6680, #6659, #4782, #4079

**Comment by Adriani90** [comment]
@feerrenrut, I understand that looking at those issues separately, in some cases the problem seems not to be very critical. However, when looking at all issues together, the double informatoin spoken while navigating through the internet can be painful and can cause inefficiencies for users.
cc: @jcsteh, @MarcoZehe, @leonardder, @derekriemer.

**Comment by kdunagan-od** [comment]
Hi! I'm just a random software developer working on a site. QA was testing NVDA on chrome and found the problem of repeating elements whenever we focused a container div that contained many elements. We are currently finding that adding the role of group (role = "group") to the outer container is making it so NVDA is not reading out elements twice. I don't know if that helps.

**Comment by Adriani90** [comment]
Yet another example of double information: #10512. It seems in Google Chrome this behavior appears more often.

**Comment by Adriani90** [comment]
I found another one:
#7996

**Comment by Adriani90** [comment]
Some other issues are:
#10840, #10548, #10096, #8971, #8735.

**Comment by feerrenrut** [comment]
@Adriani90 please note the `bug/double-speaking` label.

**Comment by Adriani90** [comment]
Thanks Reef for pointing this. I want to bulk all issues here first and then add the label to them and then close this Meta issue afterwards. I agree with the label it will be easy to find them one by one.

**Comment by Adriani90** [comment]
There are 17 issues open now with the label bug/double-speaking. They can be easily filtered by label now, so I will close this issue. If someone could check if there are any duplicates there, that would be greatly appreciated. Thanks.
