### ISSUE TITLE
NVDA does not correctly respect line breaks in spans in Firefox

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#10143]
This bug makes it virtually impossible to properly read CI build logs on Gitlab, since many lines of output are squashed onto one line.

### Steps to reproduce:

1. Go to the following URL in firefox: `data:text/html,<span class="term-fg-l-green term-bold section js-section-header section-header js-s-get-sources">$ ls -lah ${CI_PROJECT_DIR} || true; rm -rf ${CI_PROJECT_DIR} || git config http.postBuffer 524288000 || true</span><span class="section js-section-header section-header js-s-get-sources"><br></span><span class="section line s_get-sources"></span><span class="section js-s-get-sources">ls: /builds/wsg/test-project: No such file or directory<br></span>`
2. Inspect the accessibility properties of the text, and notice that Firefox is correctly exposing them as 2 text nodes.

### Actual behavior:

Everything is presented on one line:

```
$ ls -lah ${CI_PROJECT_DIR} || true; rm -rf ${CI_PROJECT_DIR} || git config http.postBuffer 524288000 || truels: /builds/wsg/test-project: No such file or directory
```

### Expected behavior:

There should be 2 lines of text in the virtual buffer:

```
$ ls -lah ${CI_PROJECT_DIR} || true; rm -rf ${CI_PROJECT_DIR} || git config http.postBuffer 524288000 || true
ls: /builds/wsg/test-project: No such file or directory
```

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

alpha-18064,e579eb02

#### Windows version:

Windows 10 1903

#### Name and version of other software in use when reproducing the issue:

Firefox 68.0.2 and 69.0 beta 16. Does not repro in chrome

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

**Comment by lukaszgo1** [comment]
cc @jcsteh

**Comment by jcsteh** [comment]
There are indeed two text nodes, but there is no line break (which one would expect due to the `<br>`). Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1578311.

This works as expected in Chrome.

**Comment by jcsteh** [comment]
This was fixed in Firefox 71.
