### ISSUE TITLE
NVDA very slow to start at logon on windows 7

### ISSUE THREAD

**Issue by RichCaloggero** [nvaccess/nvda#10142]
#9787 # Actual behavior:

When logging on to windows 7, the logon screen appears, but NVDA does not speak nor play startup sound for aprox. 60 seconds or more.

### Expected behavior:

NVDA plays startup sound and begins speaking almost immediately after windows startup sound is heard.

### System configuration
Windows 7 (just after reinstallation of windows).

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

2019.2

#### Windows version:

Windows 7 sp1.

#### Name and version of other software in use when reproducing the issue:

n/a

#### Other information about your system:

This issue begun after complete reinstallation of windows. It may have to do with other services starting before NVDA runs.

I can press windowsKey+u to open easyOfAccess and narrator begins speaking, however when I actually enable narrator by pressing spacebar on it's name and then press Enter to OK the easeOfAccess dialog, narrator too does not speak. When I do this, both narrator and NVDA begin speaking simultaneously after a long delay (a minute or more).

AUdio is running because I can actually log in and the post logon sound is played. I can even start NVDA at this point, and the startup sound is heard, but again, there is no speech.  I'm using NVDA's default synthesizer, not SAPI, so this seems odd to me!

#### Does the issue still occur after restarting your PC?

yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

no.

**Comment by Brian1Gaff** [comment]
OK what anti virus is being used on the machine. Please tell me its not 
avast!

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by Brian1Gaff** [comment]
Also thinking about the nvda start up settings. you imply that windows is set to need a password, or at least display a  user list before it starts, and of course for this to speak one has to set nvda to start at  log in and then save the settings and then restart the system.
 Normally nvda's start up tones only occur after the early start speech to allow you to read the screen.
I think it might be also an idea to set up nvda to write a debug log and  see if it says something like a warning that nvda took a long time to start near the beginning. However I would say this is  more than likely a windows issue considering your comments on Narrator, which of course you can also set to start at start up and as it seems not to be very good either that adds fuel to hte Windows  issue.
You do not tell us much about the hardware, if its a standard hard drive, how much memory or disk space it has or whether the disc or image used to reinstall is a bespoke one from the  machines vendor. Lots of things can try to load at start up which are pretty slow, so more investigation would be a good thing.
Brian

**Comment by DrSooom** [comment]
@RichCaloggero: I suggest to install/update the audio driver. Perhaps a Realtek on-board sound card is used. And please list all installed Anti-Virus/Backup solutions incl. version (e.g. Windows Defender, Acronis True Image 2020). Thanks.

btw: Disconnecting external HDDs reduces the boot time, but I guess it doesn't help here with that specific issue.

**Comment by lukaszgo1** [comment]
I am experiencing something very similar though the wait time isn't as long, but I have SSD drive here. @RichCaloggero In my case disabling UAC improved the situation. Could you try that ad least temporarily?

**Comment by RichCaloggero** [comment]
I seemed to have fixed things to some extent. I disabled a bunch of intel services:

- intel DSA (driver and support assistant)
- dell digital delivery
- dell command power manager
- dell hardware support
- probably others I'm not finding now...

Ugh!
