### ISSUE TITLE
Installed copy of NVDA: NVDA restarts when leaving secure screens

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#10179]
Hi,

Regression introduced in #9827: in installed copy of NVDA, whenever one exits secure screens, NVDA restarts.

### Steps to reproduce:
1. Install alpha.18571 or later, and for sake of completeness, have a portable copy of that snapshot handy.
2. After installing the snapshot in question, press Control+Alt+Delete.
3. Press Escape to exit.

### Actual behavior:
NVDA restarts.

### Expected behavior:
NVDA keeps using the copy that was running before secure screen shows up.

#### NVDA installed/portable/running from source:
Installed and portable

#### NVDA version:
Alpha.18574

#### Windows version:
Windows 10 Version 1903

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
None

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No problem in alpha.18569 and earlier.

Thanks.

**Comment by josephsl** [comment]
Hi,

Surprisingly, this issue does not occur if one is using portable copy.

Thanks.

**Comment by josephsl** [comment]
Hi,

Possible cause found: in NVDA launcher, NVDA will forcefully exit no matter what happens when desktop switches occur. Previously it won't do anything unless it is told to quit or restart, but with #9827, it'll restart without checking for flags.

I see two paths:

1. Revert #9827 until a more stable solution is found that will not cause NVDA to restart when all it did was exit out of secure screens.
2. Let NVDA remember desktop switches and tell it not to restart when it comes out of secure screens.

In the old days (before the current testing policy with alpha builds were adopted), I would have voted for the first option, but I'm sure there is a more stable solution in the works.

Thanks.

**Comment by XLTechie** [comment]
Joseph Lee wrote:

> Possible cause found: in NVDA launcher, NVDA will forcefully exit no matter what happens when desktop switches occur. Previously it won't do anything unless
> it is told to quit or restart, but with #9827, it'll restart without checking for flags.

I have not looked at this code, but would it be possible to invert the situation 
from what it was before? Have it called with a --keep-running flag, opposite of 
the old -r flag, when coming out of secure screens?

It would require adding that flag, of course, but it might be worth doing 
anyway for other use cases where you don't want a restart if it's already 
running.

**Comment by josephsl** [comment]
Hi, I think we need to do more than that: we need to remind NVDA that desktop switches are not a good time to restart unless this happens when a user logs on or off. The specific change will require adjusting IAccessible handler, specifically desktop switch code. Another possibility might be Ease of Access, but we need to figure out what’s up first before deciding what to do next. Thanks.

**Comment by josephsl** [comment]
CC @JulienCochuyt, and please address this before it goes to beta.

Thanks.

**Comment by leonardder** [comment]
>     1. Revert #9827 until a more stable solution is found that will not cause NVDA to restart when all it did was exit out of secure screens.

I would prefer this for the time being, until there is a suitable solution for this issue.

>     2. Let NVDA remember desktop switches and tell it not to restart when it comes out of secure screens.

I think this might be error-prone. Note that a destkop switch always triggers execution of nvda.exe, so the new copy of NVDA should not kill the old one if there is a destkop switch. The only way to communicate this, might be an extra command line argument. 

> ... would it be possible to invert the situation from what it was before? Have it called with a --keep-running flag, opposite of the old -r flag, when coming out of secure screens? It would require adding that flag, of course, but it might be worth doing anyway for other use cases where you don't want a restart if it's already running.

I think this makes sense. In fact, the --ease-of-access flag is still passed to NVDA when it is executed from ease of access for backwards compatibility, so it should be as simple as telling NVDA not to exit the new copy when --ease-of-access is provided.

> ... I think we need to do more than that: we need to remind NVDA that desktop switches are not a good time to restart unless this happens when a user logs on or off.

Honestly, when there is a command line argument, I don't see why?

**Comment by josephsl** [comment]
Julian, any thoughts? If it is okay with you, we’re willing to revert this one. Thanks.

**Comment by leonardder** [comment]
Actually, I don't think reverting is necessary if we choose the 
--ease-of-access flag way. That should be a few lines of code to fix. 
Note that the help description should be repeated.

**Comment by JulienCochuyt** [comment]
> Actually, I don't think reverting is necessary if we choose the --ease-of-access flag way. That should be a few lines of code to fix.

Fix up PR is on its way.

> Note that the help description should be repeated.

I'm not getting your point here. Could you please elaborate?

**Comment by leonardder** [comment]
> > Note that the help description should be repeated.
> 
> I'm not getting your point here. Could you please elaborate?

Ugh, probably was somewhere else with my head when I wrote this.

What I mean, is that the --ease-of-access flag has a help description in the arg parser in nvda.pyw. That probably requires updating to mention the new behavior, i.e. that is just in order not to restart NVDA.

**Comment by JulienCochuyt** [comment]
> What I mean, is that the --ease-of-access flag has a help description in the arg parser in nvda.pyw. That probably requires updating to mention the new behavior, i.e. that is just in order not to restart NVDA.

I'll have a look, but as this parameter is not meant to be passed by end user, I'm not so sure it bothers.

The try build of the fix up PR is building.
I'll check with this in the first place.
I missed to mark that fix up PR as a draft one, though.

**Comment by JulienCochuyt** [comment]
> I'll have a look, but as this parameter is not meant to be passed by end user, I'm not so sure it bothers.

I have amended the comment in `nvda.pyw` explaining the use of `--ease-of-access`:
Removed:
`# This option currently doesn't actually do anything.`
Added:
`# If this option is provided, NVDA will not replace an already running instance (#10179)`

The help screen shows:
> --ease-of-access      Started by Windows Ease of Access

That is, it historically did not mention the fact that the parameter had no effect.

My opinion is to leave it as is. What do you think?

**Comment by leonardder** [comment]
I think it is now good as is. I actually thought that there was 
something about the deprecated state of the parameter in the help text, 
but there isn't.
