### ISSUE TITLE
Python 3 versions of NVDA produce a scratch in the speech when finishing the end of a line

### ISSUE THREAD

**Issue by hozosch** [nvaccess/nvda#10185]
### Steps to reproduce:
Open a dokument
Press NVDA+A for "say all"
### Actual behavior:
You will find that NVDA scratches sometimes. Mostly at the end of a line, either a line you did with enter, or the automatic line change if one long line is too big for the screen.
### Expected behavior:
NVDA shouldn't scratch a single time
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
alpha-18574,56f5fcd2
#### Windows version:
7 professional sp1 64 bit
#### Name and version of other software in use when reproducing the issue:
doesn't matter here
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No. The latest stable obviously doesn't do that, since it's still running on python 2. However, I didn't try it with the threshold or any other version there may be on a different branch running python 3.

**Comment by zstanecic** [comment]
1.	Can you provide which synth you used to reproduce this?

This only happens with espeak and no other voice does that.

Even the beta version of RHVoice cannot do that.

**Comment by hozosch** [comment]
O yes, so it seems, as I'm indeed using espeak, that it's an issue in the portation of espeak to python 3. Maybe we should open an issue on espeak NG?

**Comment by Brian1Gaff** [comment]
But I'm using that on English on the Alpha branch and have had no such 
issues, so maybe its only when in another language?


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by hozosch** [comment]
For me, it also happesn in English, for instance  if you read one line
and it finished reading it.

Am 10.09.2019 um 17:58 schrieb Brian Gaff:

**Comment by Brian1Gaff** [comment]
Hmm, very strange. maybe its hardware related or something to do with the 
speech refactoring rather than Python 3. I'm using a Behringer USB sound 
device here.
One would have thought that it would be an odd fault to only occur in some 
circumstances. It makes me wonder if it occurs with no speech or another 
synth, say Sappi 5?

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by zstanecic** [comment]
It doesn’t have to do anything with speech refactor

**Comment by Brian1Gaff** [comment]
Well, I have been using it all morning with docs in word and other 
applications and apart from the occasional click one gets when a sound is 
interrupted by the user, ie the sudden fall of a DC level so to speak, 
normal reading with the Quincy voice works as it should do at least on my 
window 7 64 machine.
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by Adriani90** [comment]
Cc: @feerrenrut

**Comment by hozosch** [comment]
I should point out that it only happens with the compiled snapshots. I tested the prototype from source as well, and there, it didn't scratch, at least from what I can remember.

**Comment by leonardder** [comment]
The thought that this may be caused by speech refactor isn't strange at all, there have been major changes on how speech synthesizers process speech as well as how say all works.
I've been able to reproduce this in applications where movement through text is laggy, such as in word documents with lots of data in it.

Cc @michaelDCurran

**Comment by hozosch** [comment]
I'm now running 2019.3 beta 1 installed on windows 10 18363, and I still have that problem. It's whenever NVDA scrolls, and sometimes when it finishes a sentence. I think it's a speech refactor problem, because I was using an inofficial eloquence driver portet to python3, which also did it.

**Comment by zstanecic** [comment]
Hi!

Please try it with some official synth, especially sapi 4 or 5, and RH Voice or vocalizer

**Comment by hozosch** [comment]
I primarily use Espeak, and it still happens with this synth. In sapi4 and 5 it doesn't happen, I don't have the money to buy vocalizer.

**Comment by Adriani90** [comment]
Can you try on a different Laptop or PC? Can you reproduce it? Do you use multiple Sound Cards?
I am using NVDA 2019.3 Beta 1 on different PCs both with eSPeak and Eloquence as Wella s one core voices, both on Windows 10 and Windows 8.1. I cannot reproduce this Problem.

It might be a Sound issue from your Sound Card. Try also with different Headsets or Speakers.

**Comment by hozosch** [comment]
I don't have any other OS or PC to test with. When I opened the issue, I had windows 7 on this machine I'm using now, and there it was also reproduceable. I also don't have any other sound card except the internal one with the realtec driver installed. Espeak is the only synth with which this happens, if we exclude that inofficial synth.

**Comment by zstanecic** [comment]
So… it is a problem of espeak

**Comment by feerrenrut** [comment]
I notice this issue on my machine also (with espeak). I'm suspicious of the way that we send audio to the sound device, there are much newer API's for this. It will require some investigation.

**Comment by feerrenrut** [comment]
I'm labeling this as `goodForNewDev`, since very little NVDA specific knowledge is required to investigate. I expect the problem is limited to how we send audio data.

**Comment by Adriani90** [comment]
@hozosch could you please test with last alpha? Is this still reproducible?

**Comment by jcsteh** [comment]
This has the same cause (and thus the same investigation is required) as I describe in https://github.com/nvaccess/nvda/issues/11061#issuecomment-671638918.

**Comment by hozosch** [comment]
So it has! Well, as I expected, I can still reproduce it with the latest alpha version.

**Comment by CyrilleB79** [comment]
Reopening since WASAPI is not enabled by default anymore (#15172).

**Comment by hozosch** [comment]
I also noticed that this happens only at speeds faster than the default 30. I will need to make a more extensive test with vasapi enabled.
