### ISSUE TITLE
Screen curtain reveals mouse position

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#10181]
Note, this was reported to me by my wife, so it would help to have at least one sighted person who can verify this.

### Steps to reproduce:
1. Enable the screen curtain by assigning a custom gesture to the global command in the vision category
2. Look at the screen

### Actual behavior:
The screen is black, but the mouse is still shown.

### Expected behavior:
Screen is entirely black

### Proposed fix
There is a function in the magnification API that hides the system cursor, so that can be implemented for this. Having said that, I don't consider this very important.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-18574

#### Windows version:
Windows 10 1903

**Comment by k-kolev1985** [comment]
Yes, I can confirm this. I've tested it a few days ago and I observed the same behavior. The screen is black, but the mouse cursor/pointer is definitely visible on the screen.

I might be wrong, but I think this is a limitation of the used API. JAWS has the same feature and it behaves the same - the screen is black, but the mouse pointer is visible.

**Comment by leonardder** [comment]
Interesting to see that JAWS seems to use the same API. However, I'm 
pretty sure I can fix this.

**Comment by JulienCochuyt** [comment]
Shouldn't this issue be closed as of PR #10182 being merged?
