### ISSUE TITLE
How make better integration with NVDA?

### ISSUE THREAD

**Issue by RafaelGSS** [nvaccess/nvda#10197]
Hello everyone!

I'm creating a project that makes run from terminal (CLI).
_Is a project to help read text and publish text inside facebook_

I can make integration with NVDA to read the display from the terminal? Or can I support NVDA inside my application CLI?

Thanks so much for the reply.

**Comment by leonardder** [comment]
Thanks for your message. This issue tracker is intended to report issues or request features related to NVDA. For questions on how to use NVDA with your application, I'd like to advise to send a message to the [NVDA users mailing list](https://nvda.groups.io/g/nvda)
