### ISSUE TITLE
Using NVDA version alpha-18594, the following error occurred during the test of putty

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#10195]
hi
Using NVDA version alpha-18594, the following error occurred during the test of putty:

### Steps to reproduce:
First use putty to log in to the server and then enter the Linux command, for example:
cd and cd home
### Actual behavior:
At this time, NVDA will play an error tone when you enter the command.
### Expected behavior:
An error occurred
#### NVDA installed/portable/running from source:
install
#### NVDA version:
NVDA version alpha-18594,b5e4f738
#### Windows version:
windows 10 -1903
#### Name and version of other software in use when reproducing the issue:
putty 0.72.0
#### Other information about your system:
no
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
Attach NVDA.log:

Speaking [LangChangeCommand ('zh_CN'), ' root@ecs-B59:~#                                                                 \n']
ERROR - NVDAObjects.behaviors.LiveText._monitor (20:52:31.531):
Error getting initial lines
Traceback (most recent call last):
  File "NVDAObjects\behaviors.pyc", line 271, in _monitor
  File "NVDAObjects\behaviors.pyc", line 262, in _getTextLines
  File "displayModel.pyc", line 509, in getTextInChunks
AttributeError: module 'textInfos' has no attribute 'UNIT_DISPLAYCHUNK'
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (20:52:33.352):
Unsupported speech command: LangChangeCommand ('zh_CN')
IO - inputCore.InputManager.executeGesture (20:52:38.759):
Input: kb(desktop):windows+m
IO - inputCore.logTimeSinceInput (20:52:38.774):
0.015 sec since input
IO - speech.speak (20:52:38.775):
Speaking [CharacterModeCommand(True), LangChangeCommand ('zh_CN'), 'm', EndUtteranceCommand()]
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (20:52:38.776):
Unsupported speech command: LangChangeCommand ('zh_CN')
ERROR - NVDAObjects.behaviors.LiveText._monitor (20:52:38.788):
Error getting lines or calculating new text
Traceback (most recent call last):
  File "NVDAObjects\behaviors.pyc", line 289, in _monitor
  File "NVDAObjects\behaviors.pyc", line 262, in _getTextLines
  File "displayModel.pyc", line 509, in getTextInChunks
AttributeError: module 'textInfos' has no attribute 'UNIT_DISPLAYCHUNK'
IO - inputCore.logTimeSinceInput (20:52:38.903):
0.145 sec since input
IO - speech.speak (20:52:38.903):
thank

**Comment by leonardder** [comment]
Will be fixed by #10187

**Comment by dingpengyu** [comment]
> Will be fixed by #10187
I wait for the merge and I continue to test
thank

**Comment by dingpengyu** [comment]
hi leonardder
NVDA version alpha-18604, has solved the putty error problem, thank you for your work. I will close this question.
thank
