### ISSUE TITLE
Set up monitor Cells in Excel

### ISSUE THREAD

**Issue by kara-louise** [nvaccess/nvda#10201]
### Is your feature request related to a problem? Please describe.
JAWS has a feature called Monitor Cells, which allows you to mark up to 10 important cells you need to glance at quickly. You can then have JAWS speak the contents of these cells by pressing a hotkey from anywhere within the same worksheet or workbook. The cells do not have to be near each other. You could be in A5 and need to check f200, for example.
It would be beneficial if NVDA had a similar feature as it would save time in that you wouldn't have to locate the cells manually in order to refer back to them.
### Describe the solution you'd like
2 sets of commands would have to be provided. One to set the cells to be monitored and the other to read them. To set the cells, you could use NVDA+shift+1to0, and alt+shift+1to0 to read them.
A method to clear cells should also be provided.
I don't know the technical details of how to implement this feature.
### Describe alternatives you've considered
An alternative could be to have a cell marked to be read automatically as you move round a worksheet, such as a total cell.
### Additional context
I have attached a basic excel 365 spreadsheet as an example. I have put the numbers 1 to 5 in cells a1 to a5, and 6 is in q19.
As I said previously, you could read the contents of these sells from anywhere using this feature.
[monitor cells test.xlsx](https://github.com/nvaccess/nvda/files/3602296/monitor.cells.test.xlsx)

**Comment by Brian1Gaff** [comment]
On a similar theme. I do not myself use spreadsheets enough, but somebody 
asked if attributes such as text colour or style could be used to jump to 
cells or whole rows, ie red for  values that need to be actioned urgently 
etc.
 Does this make sense
Apparent the Jaws screenreader has something like this.?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by kara-louise** [comment]
Bumping this issue because there hasn't been any comments since 2019, and I just realised that I misspelt Excel in the title. This might explain the lack of comments.

**Comment by Adriani90** [comment]
This is actually possible in Excel natively.

1. Select the cells that you want to watch. e.g. to select all cells on a worksheet with formulas, press ctrl+g, go to "content" or "special" and press enter, and then choose "formula radio button".
2. Or select watch cells with shift+arrow keys or any other selecting method
3. On the Formulas tab, in the Formula Auditing group, navigate to Watch Window and select Watch Window.
4. Press the Add Watch Button.
5. Press the "Add" button.

Now the selected cells were added to the watch window, and you can navigate and explore the watch window by pressing f6.

When the watch window is enabled, you can add or remove cells from it in the window itself, press f6 to navigate to the window and you can interact with it.

I agree that it would be really nice to have a way to add and report monitored cells via hotkeys, but at least there is an acceptable workaround so far.

**Comment by Adriani90** [comment]
This works fine in Microsoft 365 MSO (Version 2408 Build 16.0.17928.20114) 64 Bit but also in earlier versions.

**Comment by SaschaCowley** [comment]
@kara-louise can you try [@Adriani90's native solution](https://github.com/nvaccess/nvda/issues/10201#issuecomment-2342293546) and see how you get on? If there is a way to do this natively in excel I doubt it will be added to NVDA core.

**Comment by kara-louise** [comment]
@SaschaCowley I have just tried this and it does work. It's quite clunky but it's doable.
As someone who rarely uses excel I had no idea this feature existed.

**Comment by Adriani90** [comment]
Since this is a native Excel feature and people using Excel should know it, I am closing as invalid. NVDA can certainly develop its own way of monitoring cells, but I don't think it is needed in this case.
If NV Access plans to triage this anyway, please feel free to reopen.
