### ISSUE TITLE
A11y_Visual Studio Tools for Xamarin_Android SDK Configuration_Screen Reader: NVDA is not reading the state of checked/not checked for the radio buttons

### ISSUE THREAD

**Issue by Shanmukha39** [nvaccess/nvda#10215]
### Steps to reproduce:

2.Navigate to "Create a new Project" control and press enter
3.Select platform as "Android" and project type as "Mobile" and select "Android app (Xamarin)"  template ​
4.Navigate till "Tools" and select "Android" option and then select "Android SDK manager" from the expanded list
5.Start NVDA
6.Tab till radio buttons and select the radio buttons using space bar and verify whether nvda is reading the state checked/not checked 

### Actual behavior:
NVDA is not reading the state of checked/not checked for the radio buttons

### Expected behavior:
NVDA should read the state of checked/not checked for the radio buttons

#### Name and version of other software in use when reproducing the issue:
Version 16.1.0 Preview 1.0 [28730.22.d16.1]

**Comment by Shanmukha39** [comment]
![NVDA issue_Select status](https://user-images.githubusercontent.com/51434975/64903633-475cf600-d6da-11e9-9baf-361b72b0ed22.png)

**Comment by leonardder** [comment]
Thanks for your report. How is this with Narrator?

**Comment by Adriani90** [comment]
@Shanmukha39 how is this now with NVDA 2020.1?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years, I am closing as abandoned.
