### ISSUE TITLE
A11y_SCOM - U&R View_Updates & Recommendations Page_Screen Reader: NVDA only reading only Actions tab selected not reading “Actions tab selected 1 of 2".

### ISSUE THREAD

**Issue by SaisreeDandamudi** [nvaccess/nvda#10213]
### Steps to reproduce:
1.Open  Windows Server 2016 "NEB-OM-1560240 "VM with above Details.
2.Launch "SCOM - U&R View" Desktop Application.
3.Tab till "Administration link "and press Enter.
4.Tab till  "Updates & Recommendations" link and press Enter.
5.Tab till "Actions Tab item".
6.Turn on Screen Reader and check whether they are reading label name, role and status  buttons with descriptively or not.

### Actual behavior:
NVDA not reading instructions when focus on "Actions and Resources tab items"
NVDA only reading only Actions tab selected not reading “Actions tab selected 1 of 2".

### Expected behavior:
NVDA should read “Actions tab selected 1 of 2" when focus on "Actions tab item" same for "Resources Tab item" also.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
![1_SCOM Tool_Updates   Recommendations_ Nvda not reading correct instructions at list items](https://user-images.githubusercontent.com/51435580/64861341-53e73d00-d64d-11e9-8ef0-6ade46d28210.png)

**Comment by Adriani90** [comment]
@SaisreeDandamudi is this working now with NVDA 2020.1?
Are you reproducing this in focus mode? Or in browse mode?

**Comment by Adriani90** [comment]
No updates from the initial author since years, I am closing as abandoned.
