### ISSUE TITLE
MS Edge: dynamically updated 'alt' attribute is not read

### ISSUE THREAD

**Issue by aloeugene** [nvaccess/nvda#10225]
Dynamically updated 'alt' attribute is not announced correctly when it's changed and navigated to with 'arrow down'.

**Note: this is currently only reproducing in MS Edge.**

### Steps to reproduce:
1. Open tireamerica.com/login and go to registration page.
2. Focus on "Password" field and type any character (e.g. 'q').
3. Observe the "Password requirements" section appearance.
4. Navigate to "Show" button inside "Password" field.
5. Start pressing 'arrow down' to enter the list of "Password requirements".
6. Listen to announcement of images on the left side of the list.
7. Go to one of the fields and meet one more requirement.

_If you open page inspector, you can see that 'alt' attribute is dynamically updated for the image when some of requirements changes **met** or **not met** status.
"Requirement met" or "Requirement not met" is displayed in 'alt' attribute._

### Actual behavior:
When previously **not met** requirement becomes **met**, NVDA announces "Requirement not met".

### Expected behavior:
When previously **not met** requirement becomes **met**, NVDA should announce "Requirement met".

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.2

#### Windows version:
Windows 10 Enterprise (Version 10.0.17763 Build 17763)

#### Name and version of other software in use when reproducing the issue:
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Nope.

**Comment by leonardder** [comment]
Can you reproduce this with the Chrome based version of Edge?

**Comment by Adriani90** [comment]
In Edge Cromium 81 this works as expected. All requirements are reported when typing the password, if a requirement is met, NVDA says the requirement followed by "success". If it is not met, NVDA reports the requirmeent followed by "not success".
I am closing this issue in favor of Edge Cromium which will be distributed with Windows 10 20 H1 update to most users.
