### ISSUE TITLE
Feature request: Improve NVDA's automatic reporting of cmd and putty

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#10220]
hi
When using cmd and putty in NVDA, NVDA will report the determined changes each time the enter command is pressed.

### Is your feature request related to a problem? Please describe.
When using cmd and putty in NVDA, NVDA will report the changes after the input each time the enter command is pressed.
In my opinion, this operation cmd and putty are very class.
### Describe the solution you'd like
I recommend integrating the NVDA cmd and putty auto-reporting capabilities into NVDA+u so that NVDA's built-in progress hints can be used to report changes in cmd and putty.
### Describe alternatives you've considered
no
### Additional context
no
test method:
First connect to a host of a Linux system using putty or windows10 cmd, then enter the following command:
apt install screen
At this time, regardless of whether you use putty or windows10 cmdNVDA, the report will be downloaded to the progress of the installation.
The only way to stop him is the case ctrl
thanks

**Comment by leonardder** [comment]
If I understand you correctly, you're suggesting that progess bars shown on a terminal will be spoken using NVDA's progress bar output. I'm afraid this can't be fixed, as the only thing we get when a progress indicator like this is shown in a terminal, is a textual representation of the progress.

Note that you can always disable NNVDA's output by using NVDA+5, reporting of dynamic content changes.

I'm tempted to close this as can't fix.

**Comment by dingpengyu** [comment]
> If I understand you correctly, you're suggesting that progess bars shown on a terminal will be spoken using NVDA's progress bar output. I'm afraid this can't be fixed, as the only thing we get when a progress indicator like this is shown in a terminal, is a textual representation of the progress.
> 
> Note that you can always disable NNVDA's output by using NVDA+5, reporting of dynamic content changes.
> 
> I'm tempted to close this as can't fix.

hi leonardder
thank you for your reply
Maybe this problem will be very troublesome to solve.
sorry
