### ISSUE TITLE
NVDA Alpha: modal dialogs sometimes don't get focus when they are expected to

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#10221]
### Steps to reproduce:
1. OPen notepad
2. In the NVDA menu, choose help > check for updates

### Actual behavior:
NVDA shows the checking for update indeterminate progress dialog. WHen the update check is finished, notepad gets focus again. You have to alt+tab back into the NVDA Update dialog.

### Expected behavior:
NVDA shows the checking for update indeterminate progress dialog, followed by the no update available dialog.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Alpha alpha-18646

#### Windows version:
Windows 10 1903

#### Name and version of other software in use when reproducing the issue:
N/A

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, I have the felling that this started to happen much more frequently after the Python 3 update.

**Comment by Brian1Gaff** [comment]
Yes I seem to recall mentioning this some time back now but at the time it 
was not very predictable. A similar issue happens after the download has 
happened sometimes where its still prompting to update even though its just 
done it and you have to fiddle about to find the prompt that should have 
been displayed.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by Adriani90** [comment]
@leonardder do you see this issue also in NVDA 2019.3 Beta 4?

**Comment by Adriani90** [comment]
I tested with alpha-20220,1c4519a6 and I cannot reproduce this issue. Out of 20 times the update dialog and the promt "no update available" always got focus properly.
@leonardder if you confirm this, then I vote for closing.

**Comment by XLTechie** [comment]
@leonardder I can not replicate this in NVDA alpha 2023.2.0.27996, Windows 10 22H2. Is there an updated STR?

**Comment by leonardder** [comment]
It looks like I can no longer produce it either. Lets close this!
