### ISSUE TITLE
When BRLTTY for Windows is installed scons fails to bundle BrlAPI

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#10238]
Discovered while debugging #10228
### Steps to reproduce:
1. Install BRLTTY for Windows you do not need to have any actual braille display connected.
2. Execute scons launcher from the root of the NVDA repo.
3. Start newly created launcher.
### Actual behavior:
BrlAPI dll is missing. It is therefore not possible to switch to BRLTTY.
### Expected behavior:
BrlAPI should be working regardless of what is installed on the system.
#### NVDA installed/portable/running from source:
Source
#### NVDA version:
Any after migration to BrlAPI 07 and Python 3.
#### Windows version:
Windows 7 x64
#### Name and version of other software in use when reproducing the issue:
Python, BRLTTY for Windows
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This is new after Python 3 migration.
#### Additional info:
WHen BRLTTY is installed it places brlapi-0.7.dll in the syswow64 directory. When this dll is removed either manually or by uninstall of BRLTTY BrlAPI is bundled correctly.

**Comment by Adriani90** [comment]
cc: @bramd, @leonardder
