### ISSUE TITLE
Revising of the text in Microsoft Word not localized

### ISSUE THREAD

**Issue by kvark128** [nvaccess/nvda#10261]
Translatable string "revised %s" incorrectly used in speech module on line 1500:
text=(_("revised %s"%revision) if revision
Please fix it.

**Comment by DrSooom** [comment]
@kvark128: Please completely fill out the bug report draft. Thanks.

**Comment by Adriani90** [comment]
@kvark128 I don't really understand what you expect the behavior to be here. Please edit the issue and include all information required in the issue template. Thanks.

**Comment by kvark128** [comment]
I don't know how to reproduce the problem in Word and can't describe it.
Here in the gettext function passed already partly translated string:
_("revised %s"%revision)
it should be:
_("revised %s")%revision
The closing bracket in the wrong place. This is a very common mistake.

**Comment by JulienCochuyt** [comment]
@Adriani90, @DrSooom, the `% revision` should be out of the the gettext call.
PR on its way.
