### ISSUE TITLE
Delete threshold labels for milestones

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#10277]
The first python3 version of NVDA will be released in 2019.3. Based on the above reasons Milestones's threshold tag has completed his mission.

### Steps to reproduce:
[open Milestones page](https://github.com/nvaccess/nvda/milestones)
You can see
threshold tag
### Actual behavior:
remove threshold tag
### Expected behavior:
remove
#### NVDA installed/portable/running from source:
no
#### NVDA version:
no
#### Windows version:
windows10-1903
#### Name and version of other software in use when reproducing the issue:
no
#### Other information about your system:
no
#### Does the issue still occur after restarting your PC?
no
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
thank

**Comment by leonardder** [comment]
Closed the milestone. Note that the python 3 project is still open, I think that's ok.
