### ISSUE TITLE
A11y_HPC Pack_Configure the naming of new nodes_Screen Reader : When user opens "Specify Node Naming Series" dialogue NVDA is not reading title. (NVDA is not reading about the title for all the dialogues)

### ISSUE THREAD

**Issue by SaisreeDandamudi** [nvaccess/nvda#10272]
### Steps to reproduce:
1)Open "HPC Pack Cluster Manager" application in your desktop
2)Tab till Configuration and navigate to Deployment To do list tab and press enter
3)Tab till import a certificate for deployment and press enter
4)Start Screen Reader
5)Verify screen reader is reading the title of the window properly

### Actual behavior:
NVDA is not reading the Title "Specify Node Naming Series" of the dialogue. After the dialogue opens NVDA start reading from the naming series

### Expected behavior:
NVDA should read the Title of the dialogue properly 

#### Name and version of other software in use when reproducing the issue:
HPC Pack 2016 Cluster Manager
Server Version : 5.3.6435.0
Client Version : 5.3.6435.0

#### Does the issue still occur after restarting your PC? Yes
[NVDA issue.pptx](https://github.com/nvaccess/nvda/files/3645473/NVDA.issue.pptx)

**Comment by michaelDCurran** [comment]
Closing on request from reporter privately by email.
