### ISSUE TITLE
[Preview-MAS Violation]: During scan mode focus is moving to hidden element before price value.

### ISSUE THREAD

**Issue by navyaGoberu423** [nvaccess/nvda#10287]
User Experience:
User who rely on screen reader if focus is moving to any hidden element user will confuse.

Test Environment:
OS: Windows 10
Browser: IE
URL: https://microsoftignite-staging-beta.azurewebsites.net/en-us/ignite/pricing

Repro Steps:
Step 1: Open the above URL using any browser.
Step 2: Navigate to section “Pricing_Blade_1” and press down key to select price information on this section.
Step 3: Verify screen reader focus is moving to hidden element or not?

Actual:
During scan mode focus is moving to hidden element after the paragraph and before price.
Expected:
Screen reader focus should not go any hidden element while pressing down key.

MAS Reference:
MAS 4.2.10
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={b24201d1-2276-4471-8183-e1e5353031ad}

**Comment by Adriani90** [comment]
@navyaGoberu423 this is not reproducible for everyone because the account needs a tenant in the azure environment. Could you please provide a minimal test case or a code snippet to reproduce? How is the element exactly hidden? With display:none? Or visibility:hidden? Or aria-hidden=true?

**Comment by seanbudd** [comment]
Welcome @navyaGoberu423 ,

We are unable to process this issue as it stands.
As this is an old issue, can you please confirm that this is still a problem with NVDA 2021.3.5 / NVDA 2022.1beta4. 

I've also added our issue template to your issue. Please fill out the template fully.

To be able to reproduce this issue, we need a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).

Kind Regards,
NV Access Software Developers

**Comment by seanbudd** [comment]
Closing as stale
