### ISSUE TITLE
Incorrect restart of NVDA after installing the addons

### ISSUE THREAD

**Issue by kvark128** [nvaccess/nvda#10299]
### Steps to reproduce:
1. Choose the nvda-addon file in your file Manager and press Enter.
2. In the dialog that appears, agree to install the addon, then agree to restart NVDA.

### Actual behavior:
Approximately with a probability of 10%, unloading NVDA will be incorrect. No exiting sound and relevant entries in NVDA log.
After loading NVDA received the following nvda-old.log:
INFO - __main__ (03:19:24.957):
Starting NVDA
INFO - core.main (03:19:25.112):
Config dir: c:\Users\kvark\nvda\userConfig
INFO - config.ConfigManager._loadConfig (03:19:25.112):
Loading config: c:\Users\kvark\nvda\userConfig\nvda.ini
INFO - core.main (03:19:25.221):
Developer Scratchpad mode enabled
INFO - core.main (03:19:25.309):
NVDA version 2019.2.1beta1
INFO - core.main (03:19:25.319):
Using Windows version 6.1.7601 service pack 1 workstation
INFO - core.main (03:19:25.319):
Using Python version 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)]
INFO - core.main (03:19:25.319):
Using comtypes version 1.1.7
INFO - core.main (03:19:25.319):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - external:synthDrivers.RHVoice.SynthDriver.__init__ (03:19:25.680):
Using RHVoice version 0.2.161
INFO - synthDriverHandler.setSynth (03:19:25.690):
Loaded synthDriver RHVoice
INFO - core.main (03:19:25.690):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5
INFO - brailleInput.initialize (03:19:25.690):
Braille input initialized
INFO - braille.initialize (03:19:25.690):
Using liblouis version 3.10.0
INFO - braille.BrailleHandler.setDisplayByName (03:19:25.700):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (03:19:25.839):
UIAutomation: IUIAutomation
INFO - core.main (03:19:26.220):
NVDA initialized

The addon is installed and working properly.

### Expected behavior:
After installation of the Addons, NVDA should restart always correctly.

#### NVDA installed/portable/running from source:
installed (using -c argument to override the directory user configuration)
#### NVDA version:
NVDA 2019.2.1beta1
#### Windows version:
Windows 7 32-bit

### Additionally
After reviewing gui.addonGui.handleRemoteAddonInstall function, i wrote a global plugin with the following code, which causes incorrect restart is a 75% chance:
```
addonPath = r"z:\nvda\test.nvda-addon" # any addon for testing
gui.mainFrame.prePopup()
if gui.addonGui.installAddon(gui.mainFrame, addonPath):
	core.restart() # restart NVDA immediately, without prompting the user
gui.mainFrame.postPopup()
```
Maybe it will help to understand the problem.

**Comment by kvark128** [comment]
Additional experiments showed that the problem only occurs on installation of a previously installed addon. For example, when installing a newer version. If the addon was previously not installed, then restart NVDA is always correct.

**Comment by JulienCochuyt** [comment]
@kvark128
> unloading NVDA will be incorrect

Could you please elaborate? Is it frozen? Does it shutdown but does not restart? Doesn't it restart at all? Does it restart but without sound notice?

Also, could you please try to reproduce with log level set to "debug" and add-ons disabled?

For others attempting to reproduce: Windows 7 32 bits might be of importance here.

**Comment by kvark128** [comment]
After consent to restart and pressing Yes button, NVDA returns to window with the addon file and even have time to read his name.
Then plays start sound of NVDA and starts a new copy of the program. Process of the previous copy disappears from the process list.
No exiting sound and the log file ends unexpectedly. It seems that NVDA for some reason not quits out of main loop.
[nvda-old.log](https://github.com/nvaccess/nvda/files/3668994/nvda-old.log)

**Comment by kvark128** [comment]
In the latest alpha builds with Python 3 the exact same problem.

**Comment by JulienCochuyt** [comment]
Did you experience the same issue with earlier versions of NVDA?

It seems indeed the log did not flush to disk, we really might need some external log connector one day…

Just to be sure, could you please reproduce with add-ons disabled?

By the way, I see in the log that the sole "Mozilla" add-on you are using states "last tested NVDA version: 2019.3"
If this is an add-on in development stage, flagged that way for testing purpose, fine.
If it has been publicly released and presented as "stable", note it misbehaves in pretending to be tested against a version of NVDA whose API is not yet frozen.

**Comment by kvark128** [comment]
The problem is reproducible only when the installation of an already installed addon. So i left only one addon, all rest was removed. In NVDA 2019.1 the problem is also reproduced.

**Comment by JulienCochuyt** [comment]
> The problem is reproducible only when the installation of an already installed addon. So i left only one addon, all rest was removed. In NVDA 2019.1 the problem is also reproduced.

Do you mean you do not reproduce when this add-on is already installed but disabled?
This would lead to questioning whether this very add-on crashes NVDA when it gets overridden while running…

**Comment by kvark128** [comment]
no, the problem is reproduced even if the addon is disabled. Main thing that it was installed. If the addon is first installed, reboot always occurs correctly.

**Comment by JulienCochuyt** [comment]
> no, the problem is reproduced even if the addon is disabled. Main thing that it was installed. If the addon is first installed, reboot always occurs correctly.

Is this statement also verified for any other add-on than this "Mozilla" one?

**Comment by kvark128** [comment]
Yes, this happens with any addon. Mozilla in the log it's just as example.

**Comment by Brian1Gaff** [comment]
Except of course the times when nvda will not start at all due to it not 
being able to open the log file for writing due to something slow in windows 
which locks the log file even when the old log is named.
 This seems to be far less likely in python 3 alphas however.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by Brian1Gaff** [comment]
Does nvda assume a 64 bit system when it handles add ons. I've certainly not 
seen this very specific problem here on windows 7 which is 64 bit.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by JulienCochuyt** [comment]
> Does nvda assume a 64 bit system when it handles add ons. I've certainly not seen this very specific problem here on windows 7 which is 64 bit.

No, there is not such consideration in my understanding, but I've been reported quite a few instabilities and oddities specific to Windows 7 32 bits since 2018.3 (migration to wxPython 4).
It appears wxPython 4 32 and 64 bits react differently in some faulty situations.
Eg. add-ons failing to properly destroy their GUI elements did cause an error in the log on 64 bits systems but block NVDA from quitting on 32 bits ones due to the watchdog restarting the core during shutdown.

**Comment by Adriani90** [comment]
@kvark128 are you still having this issue with NVDA 2024.1 Beta 10?

**Comment by Adriani90** [comment]
We didn't get any update upon request from the initial author since many years, I am closing as abandoned. If you are still having this issue, please comment and we can reopen.
