### ISSUE TITLE
NVDA/Firefox: Impossible to read certain Text Fields by either reviewing Current Line or via Object Navigation

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10291]
### Steps to reproduce:

Tested with NVDA 2019.2 and Firefox 69.0.1 - observed on both Windows 7 and 10 X64.

1. Navigate to the Google homepage

2. Navigate to the first form field on the page - this should be the "Search" box

3. Attempt to spell the name of this form field - both by using the "Spell Current Line" gesture and with Object Navigation

### Actual behavior:

You'll notice that whilst the title of this field is output as "Search" by NVDA, using either of the above methods to attempt to spell the name of the form field results in NVDA acting as if no object has focus.

### Expected behavior:

It would be useful with these kinds of text fields to be able to spell the name - as an example, to confirm the spelling of a form field. I have seen other cases of this across the web on various different websites; Google was the easiest site from memory where this could be observed.

**Comment by JulienCochuyt** [comment]
I cannot reproduce the described failure of "spell current navigator object" with Firefox 69.0.1 on Windows 10 (1903).
What language is your google homepage appearing in?
Mine is in French.

**Comment by Adriani90** [comment]
I think I understand this issue differently. @elliott94 could you please update the str accordingly? As I understand, you want to spell out the label of the search field on google letter by letter.
1. Go to google
2. Press e to land on search field
3. When you hear the label, press left or right arrow to spell it letter by letter
4. Press nvda+l to spell the label letter by letter
5. Change the review mode to "screen review" or to "object review" and try to navigate the object of the search field letter by letter

Actual: none of the above steps allow you to read the label letter by letter
expected: at least with nvda+l or with obect review / screen review NVDA should recognize the label accordingly and should allow navigation letter by letter.

Note: this behavior is also seen very often in Edge.

**Comment by elliott94** [comment]
> 
> 
> I think I understand this issue differently. @elliott94 could you please update the str accordingly? As I understand, you want to spell out the label of the search field on google letter by letter.
> 
>     1. Go to google
> 
>     2. Press e to land on search field
> 
>     3. When you hear the label, press left or right arrow to spell it letter by letter
> 
>     4. Press nvda+l twice to spell the label letter by letter
> 
>     5. Change the review mode to "screen review" or to "object review" and try to navigate the object of the search field letter by letter
> 
> 
> Actual: none of the above steps allow you to read the label letter by letter
> expected: at least with nvda+l or with obect review / screen review NVDA should recognize the label accordingly and should allow navigation letter by letter.
> 
> Note: this behavior is also seen very often in Edge.

This is exactly what I'm trying to do. I can't figure out if this is deliberate - is there any way to change how these fields are managed by NVDA?

**Comment by zahra21** [comment]
hi.
when i tested this with firefox 52 and nvda 2017.2,
1. i went to google.
2. i pressed control home.
3. pressed e to go to the edit fild.
4. i pressed nvda up arrow twice to spell.
nvda said space.
5. i pressed nvda space to go to the focus and typed something.
6. i repeated the first of my fourth steps and nvda could spelled the written words which i searched.
i tried in brows mode when i pressed e for the second time,
and used nvda up arrow twice and it spelled for me the content which i wrote for searching.

**Comment by Adriani90** [comment]
@zahra21 we are not talking about the content of the edit field, but about the label of the element. Thanks though for your testing.

**Comment by Adriani90** [comment]
cc: @MarcoZehe, @jcsteh

**Comment by jcsteh** [comment]
The label of this field is for accessibility only; it isn't visible (visually). Thus, NVDA doesn't render it as navigable text for browse mode. If you really did want to spell it, you could focus the field and press NVDA+tab (report focus) twice.

**Comment by jcsteh** [comment]
Or you could press Report current review object (desktop: NVDA+numpad5, laptop: NVDA+shift+o) twice.
