### ISSUE TITLE
NVDA+ ChromeA11y_ConnectedFieldService-IoTAlerts_IoTAlertsGrid _Screenreader:Narrator is announcing incorrect order list for the Radio button “and, or” in description filter tab.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [nvaccess/nvda#10309]
"Check out Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier." 

Environment Details:​
Application Name: Connected Field Service- Solution Deployment App
User Name – OCETestTenant@OCERegion.onmicrosoft.com
Operating System: Win10
Edge: 44.17763.1.10

Repro Steps:​
1. Launch the URL https://monti1tiecrmlivesg619org0.crm2.crmlivetie.com 
2. Select Connected field service app and navigate to the site map icon.
3.Navigate to site map and Select IoT Alerts.
4. Navigate to  " IoTAlertsGrid ".
5.Navigate to description filter tab by hitting tab and hit enter to open it.
6.Start Narrator to observe the announcement of order list for radio button.

Actual:​
Narrator is announcing wrong order lost for radio button "or ,and" .It is announcing one of one for both the radio button.
Similar issue has been observe with NVDA
NVDA version - 2019.2 
Similar issue is also observed with following screens:
1)IoTDevicesCommandsTab:
1. Launch the application Url and select Connected field service from the Published App list
2.Navigate to site map and Select IoT Alerts.​
3.Navigate to any record on the grid and click enter.​
4.Navigate to "Commands " Tab and hit enter.​
5.Navigate to more commands(...) and click on it.​
6.Navigate to "Seeassociatedrecord" and click on it.​
7. Verify that all the elements of " IoTDevicesCommandsTab" screen are accessible and MAS Compliant.

Expected:​
Narrator should announce correct order list for the radio buttons it should announce one of two and two of two. 

User Impact:​
Screen reader user will get misunderstood by the wrong announcement of screen reader.

**Comment by michaelDCurran** [comment]
Closing on request from reporter privately by email.
