### ISSUE TITLE
Add support for Windows Terminal

### ISSUE THREAD

**Issue by codeofdusk** [nvaccess/nvda#10305]
### Is your feature request related to a problem? Please describe.
The new Windows Terminal is inaccessible.

### Describe the solution you'd like
Once UIA is fully implemented upstream, the `NVDAObjects.UIA.WinConsoleUIA` class should provide support.

### Describe alternatives you've considered
None.

### Additional context

Blocked by microsoft/terminal#2447

**Comment by leonardder** [comment]
> Once UIA is fully implemented upstream, the `NVDAObjects.UIA.WinConsoleUIA` class should provide support.

Mm, note that `NVDAObjects.UIA.WinConsoleUIA` has some Windows Console specific workarounds in it. The Microsoft Console will most likely have a different UIA implementation that is hopefully more close to the default implementation in our UIATextInfo.
