### ISSUE TITLE
NVDA is not working when UIA disabled in the configuration

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#10300]
### Steps to reproduce:
1. Start NVDA.
2. Open Python console then type:
~~~ import config
 config.conf['UIA']['enabled'] = False
~~~

3. Restart NVDA.
### Actual behavior:
NVDA can no longer be used. Error sound is played almost constantly.
Each error entry in the log ends in the following:
  File "NVDAObjects\UIA\__init__.py", line 739, in <module>
    class UIA(Window):
  File "NVDAObjects\UIA\__init__.py", line 1492, in UIA
    def event_UIA_notification(self, notificationKind=None, notificationProcessing=UIAHandler.NotificationProcessing_CurrentThenMostRecent, displayString=None, activityId=None):
AttributeError: module 'UIAHandler' has no attribute 'NotificationProcessing_CurrentThenMostRecent'

### Expected behavior:
As long as this config option exists it should work.
#### NVDA installed/portable/running from source:
Running from source.
#### NVDA version:
Current master
#### Windows version:
Windows 7 x64
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The same behavior exists on installed 2019.2.1 beta 1

**Comment by josephsl** [comment]
Hi, that’s because the rest of UIA handler code (stored in a private module) isn’t loaded. CC @LeonardDer, as we have worked on this particular one a few months back.

**Comment by leonardder** [comment]
@lukaszgo1 Did you have a particular reason to disable UIA?

Instead of trying to make this option work again, I wonder whether we should eliminate this config parameter altogether.

**Comment by lukaszgo1** [comment]
In this particular instance it was just for testing. There are situations however when it is useful. One example of such was in #5337 when @michaelDCurran suggested that the crash is UIA related, so after disabling it I was able to tell that this assumption was incorrect.

**Comment by zahra21** [comment]
i use windows xp and since windows xp does not support UIA, i dont have slowness using nvda.
i had windows seven for some months for testing.
nvda responded slow even using my computer and file explorer!
i wish that i could find a solution that i disable UIA in windows seven and just use msaa and iaccessible 2 in windows seven as i do use in windows xp.
