### ISSUE TITLE
NVDA+ ChromeA11y_ConnectedFieldService-IoTAlerts_IoTAlertsGeneralTab_AI4D:Name property does not exist for the multilne edit box under alert data.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [nvaccess/nvda#10310]
Environment Details:​
Application Name: Connected Field Service- Solution Deployment App
User Name – OCETestTenant@OCERegion.onmicrosoft.com
Operating System: Win10​
Edge:44.17763.1.0

Repro Steps:​
1. Launch the URL https://monti1tiecrmlivesg619org0.crm2.crmlivetie.com 
2.Navigate to site map and Select IoT Alerts.
3.Navigate to site map and Select IoT Alerts.
4.Navigate to any record from the grid and click on it.
5.Navigate to "IoTAlertsGeneralTab" screen and navigate till multiline edit box under Alert data by pressing tab.

5.Open AI4D 
6.Observe that name property does not exist for multiline edit box.

Actual:​
Name property does not exist for multiline edit box.
Similar issue is also observed with following screens:
1)AddNewIoTDeviceCommand:

1. Launch the URL https://monti1tiecrmlivesg619org0.crm2.crmlivetie.com 
2.Navigate to site map and Select IoT Alerts.
3.Navigate to any record on the grid and click enter.​
4.Navigate to "Commands " Tab and hit enter.​
5.Navigate to "AddNewIoTDeviceCommand" and click on it.​

Expected:​
Name property should be provided for the multiline edit box.

​User Impact:​
Screen reader users won't get information regarding the multiline edit box .

**Comment by Adriani90** [comment]
@AccessibilityTestingTeam-TCS How is this behavior in Edge Cromium 81 or higher? I think since Edge Cromium will be distributed to most users soon, it makes sense to concentrate on that browser regarding NVDA issues rather than EdgeHTML Edge 44.

**Comment by feerrenrut** [comment]
I'm going to close this issue, the site is not available and was not a minimal test case. This issue is not likely to lead to an improvement in the NVDA project.
