### ISSUE TITLE
For List Item element NVDA is not reading aria-label and aria-expanded property

### ISSUE THREAD

**Issue by pidixit** [nvaccess/nvda#10324]
### Steps to reproduce:
Use following List structure:
```
<ul>
  <li id="item1" aria-label="This is aria label 1" aria-expanded="true" tabindex="0">
    <span>(Item1) This is display text 1</span>
    <button id="one" tabidex="0">(Item1) Button 1</button>
  </li>

  <li id="item2" aria-label="This is aria label 2" aria-expanded="false" tabindex="0">
    <span>(Item2) This is display text 2</span>
    <button id="two" tabidex="0">(Item2) Button 2</button>
  </li>
</ul>
```

Use NVDA to navigate the list items.

### Actual behavior:

- NVDA is not reading aria-label. It is reading internal element text.
- NVDA is not reading aria-expanded property

**Note:** This scenario works properly with Narrator + Edge. Narrator reads specified aria-label and aria-expanded property.

### Expected behavior:

- NVDA should read specified aria-label for list item element
- NVDA should read aria-expanded property

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.2.1

#### Windows version:
1903

#### Name and version of other software in use when reproducing the issue:
Added sample repro code above. JSFiddle for the same: https://jsfiddle.net/9qeLakt2/1/

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by Adriani90** [comment]
So you see this issue only in Edge?

**Comment by pidixit** [comment]
Here are the details on combinations.

NVDA screen reader:
1. With Chrome: Not reading aria-label and aria-expanded.
2. With Firefox:   Not reading aria-label and aria-expanded.
3. With Edge:      Reading aria-label and aria-expanded properties properly.

Narrator screen reader:
1. With Chrome:  Reading aria-label but not reading aria-expanded.
2. With Firefox:    Reading aria-label and aria-expanded properties properly.
3. With Edge:       Reading aria-label and aria-expanded properties properly.

Version info:
NVDA: 2019.2.1
Chrome: 77.0.3865.90 (Official Build) (64-bit)
Firefox: 69.0.1 (64-bit)
Windows version: 1903

**Comment by Adriani90** [comment]
cc: @jcsteh for Firefox at least.

**Comment by jcsteh** [comment]
IMO, overriding the content with the label here would be inappropriate. A list item is a container, just like a paragraph or a div. When you override with the label, you lose all of the semantics and formatting information inside. There have been use cases in the wild which would have been severely broken by this change. I wrote a [blog post with an in-depth discussion of these issues](http://blog.jantrid.net/2015/12/woe-aria-surprisingly-but-ridiculously.html).

nevertheless, Firefox already exposes all of the information needed to allow for this. If the NVDA developers decide to make this change, it's already possible.

**Comment by Adriani90** [comment]
@pidixit an update here, it seems in Firefox Aria-expanded is announced correctly in Firefox 75 with NVDA Version: alpha-20015,56a62097.
In Google Crome and Edge Cromium AriaAria-expanded is not announced in this example.
Does Cromium expose this?
cc: @aleventhal

**Comment by ObjectInSpace** [comment]
Filed https://crbug.com/1088085 for this issue. Thank you!

**Comment by jcsteh** [comment]
According to the [ARIA spec](https://w3c.github.io/aria/#aria-expanded), aria-expanded is not valid on listitem. Firefox allows it, but it's technically authoring error.

I'd question what the use case for this is. If you have a valid use case, you may wish to file an issue against the ARIA spec.

**Comment by feerrenrut** [comment]
Given the comment by @jcsteh I think this issue should be closed as invalid. Please comment if you believe further clarification is required.

**Comment by Anubarak** [comment]
@feerrenrut but at least `aria-label` should be read shouldn't it?
I have the same issue my `<li aria-label="test">` is ignored.

**Comment by feerrenrut** [comment]
@Anubarak The reasoning for this is given in this comment: https://github.com/nvaccess/nvda/issues/10324#issuecomment-541256470, please read the the attached blog post, it gives lots of background on this decision. If you are not satisfied, please open a new issue with a full example.

**Comment by keerthi567** [comment]
Still nvda is not reading aria-label for li element.Is this issue fixed if fixed in what version of nvda?

**Comment by seanbudd** [comment]
@keerthi567 - this issue was closed as invalid 4 years ago. Please read the reasoning referenced in the previous comment before opening another issue for this 

https://github.com/nvaccess/nvda/issues/10324#issuecomment-854475041
