### ISSUE TITLE
Capital Letters not Indicated in Google Docs

### ISSUE THREAD

**Issue by rdlynch** [nvaccess/nvda#10337]
### Steps to reproduce:

1. Open Firefox.
2. Browse to docs.google.com.
3. Open a blank Google Doc or one with text already entered (it doesn't matter).
4. enter a mixture of letters in upper and lower case.
5. Read the characters back one letter at a time.

### Actual behavior:

NVDA does not report the capitalization state using either pitch change, sound, or announcing cap.

[nvda.log](https://github.com/nvaccess/nvda/files/3693954/nvda.log)

### Expected behavior:

NVDA should report the capitalization state using the chosen method in Preferences > Settings > Speech.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.2.1
#### Windows version:
Windows 10 Version	10.0.18362 Build 18362
#### Name and version of other software in use when reproducing the issue:
Firefox 69.0.2 64 Bit
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by leonardder** [comment]
For this to work, you are required to enable braille support. In this case, capital letters are announced as expected.

Closing as works for me.
