### ISSUE TITLE
Current 2019.2.1 Milestones not closed properly

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#10330]
hi 
The stable version of NVDA 2019.2.1 has been released, but the current 2019.2.1 Milestones are not closed properly.

### Steps to reproduce:
[open Milestones page](https://github.com/nvaccess/nvda/milestones)
You can see 2019.2.1 Milestones
### Actual behavior:
remove 2019.2.1 Milestones
### Expected behavior:
2019.2.1 Milestones is no longer necessary
#### NVDA installed/portable/running from source:
install version
#### NVDA version:
alpha-18874
#### Windows version:
windows10-1903
#### Name and version of other software in use when reproducing the issue:
no
#### Other information about your system:
no
#### Does the issue still occur after restarting your PC?
no
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
thanks

**Comment by Adriani90** [comment]
cc: @michaelDCurran

**Comment by michaelDCurran** [comment]
The milestone has now been closed. Thanks for reporting.
