### ISSUE TITLE
Help with punctuation rules

### ISSUE THREAD

**Issue by TechHorseG** [nvaccess/nvda#10345]
Hello. I am trying to achieve the following.

On the "some" level of punctuation, I want the symbol "-" to be read when it occurs on its own, or at the beginning of a word, but NOT when it occurs within a word. For example:

with "-00:42:12:" I would hear that -
with "word1 - word2" I would hear that -
but with "word1-word2" I would just hear "word1 word2"

I would only wanrt to hear the "-"  in the last example if I move to the "most" punctuation level.

Is this possible? (apols for not filling out template but feel this query is completely universal and generic)

**Comment by Adriani90** [comment]
You could probably achieve that with cusomized entries in speech dictionary but I am not sure if this would work with every synthesizer.
However, please raise such questions on the users mail list at
https://nvda.groups.io/g/nvda
or on gitter at
https://gitter.im/nvaccess/NVDA
I am closing this issue for now. Thanks for your understanding.
