### ISSUE TITLE
Error in console when running NVDA from source

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#10352]
### Steps to reproduce:

With NVDA source:

* Open a windows console in the NVDA directory
* Launch `py -3-32 source\nvda.pyw` (or equivalent) to start NVDA from source

### Actual behavior:

I can hear error sound at startup (since the console is focused) and each time I alt+tab back to the console Window.

The following error appears in the log:

> ```
> Traceback (most recent call last):
>   File "NVDAObjects\behaviors.py", line 283, in _monitor
>     oldLines = self._getTextLines()
>   File "NVDAObjects\window\winConsole.py", line 62, in _getTextLines
>     return winConsoleHandler.getConsoleVisibleLines()
>   File "winConsoleHandler.py", line 127, in getConsoleVisibleLines
>     consoleScreenBufferInfo=wincon.GetConsoleScreenBufferInfo(consoleOutputHandle)
>   File "wincon.py", line 77, in GetConsoleScreenBufferInfo
>     raise WinError()
> OSError: [WinError 6] Descripteur non valide
> ```

### Expected behavior:

No error

#### NVDA installed/portable/running from source:

NVDA running from source

#### NVDA version:

Last alpha (today)

#### Windows version:

Windows 10 1709 only. The issue does not occur on Windows 10 1903.

#### Name and version of other software in use when reproducing the issue:

N/A

#### Other information about your system:

N/A

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes. NVDA alpha portable (today's release) : the issue does not occur.

### Other

Cc @codeofdusk since you worked on console.

**Comment by lukaszgo1** [comment]
Duplicate of #8653

**Comment by codeofdusk** [comment]
On 1709, you can get some limited console support when running from source by changing "Windows Console support" to "prefer UIA" in advanced preferences. Caret movement and review by granularity other than line has limited to no support.

**Comment by CyrilleB79** [comment]
Closing as duplicate of #8653 and commenting there.
