### ISSUE TITLE
NVDA saying "Non-next" button rather than "no next button" on NVDA Add-Ons Page

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#10372]
## Steps to reproduce:
          Navigate to https://addons.nvda-project.org/index.en.html, then use the B quick navigation command to try to locate buttons, of which there is only one, the OK button.

### Actual behavior:
           Once focus is on the OK button, and there is no next button, when you hit the B command to find the next button the words "no" and "next" are announced as "nonext."

### Expected behavior:
            One would expect announcement as "no next."   Given where this is happening, and how, I suspect that rather than "no next button" being handed to the synth that "nonext button" is being given to it to speak.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.2.1
#### Windows version:
Windows 10 Version 1903, Version 18362.418  64-bit
#### Name and version of other software in use when reproducing the issue:
Using chromium-based Brave browser, Version 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)

I am using Windows OneCore David as the synth.   And when I submitted this issue he's still staying "nonext" rather than the two words separately.  It could be that an issue has crept in to the synth, as I am virtually certain I would have noticed this in the past.

**Comment by JulienCochuyt** [comment]
The expected text "no next button" is indeed sent to the speech synthesizer
Checked source on master in `browseMode.py` line 682.
Checked live on 2019.2.1 using the Speech Viewer.

**Comment by britechguy** [comment]
Thanks for the update.  I gather Microsoft's cage is going to have to be rattled on this one.  There is no sane reason that the two words "no" and "next" should ever be combined into one by the synth when not sent as such in the first place.

**Comment by Adriani90** [comment]
Closing, since this seems to be handled correctly in nvda

**Comment by Brian1Gaff** [comment]
Not here they are not in Espeak in windows 7 in waterfox or latest Firefox. 
It is clearly saying no next.


Sounds like a synth issue.
 Brian



bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----
