### ISSUE TITLE
NVDA doesnt read all paragraphs in word 2010 if notebook distribution is set

### ISSUE THREAD

**Issue by federicogodan** [nvaccess/nvda#10374]
### Steps to reproduce:
Install nvda (spanish), configure notebook distribution and set block mayus as action key (instead of insert)
### Actual behavior:
When pressed block mayus + down arrow nvda only read one paragrpah and stop. If pressed again it reads another paragraph and stop (the expected beahavior for contrl + down arrow).
### Expected behavior:
NVDA must read one paragraph and continue to the next paragraph automatically until the end of the document is reached.
If the keyboard distribution is changed to desktop the behavior works as expected (only with notebook distribution it fails). So it works as a hotfix in my case.
### System configuration
Notebook Acer A325-51
Windows 10
Microsoft Word 2010
NVDA with action key as described
NVDA using windows narrator voices
#### NVDA installed/portable/running from source:
NVDA installed
#### NVDA version:
NVDA v 2019.2.1
#### Windows version:
Windows 10 version 10.0.18362
#### Name and version of other software in use when reproducing the issue:
Microsoft Word 2010 v 14.0.4770.1000 64bits
#### Other information about your system:
I test it on Windows 7 ant the error is not present.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by Adriani90** [comment]
In notebook distribution the command is insert+a or nvda+a. Closing as invalid.
