### ISSUE TITLE
Python 3.8: use native Python for altered search path workaround in NVDAHelper module

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/nvda#10385]
### Is your feature request related to a problem? Please describe.
de NVDAHelper module loads the NVDAHelper library with an altered search path.

### Describe the solution you'd like
 Python 3.8 has [add_dll_directory](https://docs.python.org/3/library/os.html#os.add_dll_directory) and exposes the `winmode` parameter, so we should be able to do this natively now.

### Describe alternatives you've considered
Leave as is

**Comment by josephsl** [comment]
Hi,

A variant of this (a new issue) is seen with libluis.dll.

Thanks.

**Comment by Adriani90** [comment]
@LeonarddeR is this still relevant?

**Comment by Adriani90** [comment]
@josephsl, @seanbudd is this issue still relevant? Or can it be closed?

**Comment by josephsl** [comment]
Hi,

This is superseded by Python 3.11 upgrade work.
