### ISSUE TITLE
outlook should have a real html parser like thunderbird

### ISSUE THREAD

**Issue by dreinn** [nvaccess/nvda#10392]
Now NVDA in Outlook use the Microsoft Word api for present messages and recognize html elements; this is good for very simple messages, but if you receive a newsletter or email with various elements, reading of messages is a pain.
You will find many many lines of blank, not labeled links, several tables that are only decoratives, graphics, etc.
If I forward the same message to thunderbird, all is absolutely ok.
So I think NVDA should use some other supports, Edge for example or similar, to improve the readibility and usability of email.

**Comment by leonardder** [comment]
I'm afraid this is simply impossible. Outlook uses the Microsoft Word control to expose HTML e-mail, there is no alternative other than UIA, which also exposes tables like this.

Closing as can't fix.
