### ISSUE TITLE
Edge Chromium: Add support for native UIA implementation

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#10402]
Note, it is probably early enough to start with this as soon as this hits the beta channel of Edge

# Is your feature request related to a problem? Please describe.
Canary builds of Edge on Chromium have an experimental native UIA implementation which can be enabled with `about:flags`. Currently, NVDA is able to see the several UIA Elements, but browse mode does not yet work.

### Describe the solution you'd like
Add support for the UIA implementation, at least in such a way that browse mode works.

**Comment by gdata1** [comment]
Hello. When is it planned to do this?

**Comment by leonardder** [comment]
I don't think it has to be considered before it reaches edge chromium beta.

**Comment by leonardder** [comment]
Actually, it can already be enabled in beta using about:flags, but it is still pretty unstable.

**Comment by gdata1** [comment]
Yes. I know. That's why I asked.

**Comment by leonardder** [comment]
Closing as duplicate of newer issue #10555, which has a broader scope.
