### ISSUE TITLE
Python 3.8: add NVDA source directory when attempting to import liblouis DLL

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#10416]
Hi,

A variation for #10385 

### Is your feature request related to a problem? Please describe.
Python 3.8 adds os.add_dll_directory function that takes path string. This is done for security reasons, as Python's DLL path lookup routine has changed. This affects all sorts of DLL's, including NVDA Helper (see #10385) and for this one, liblouis.dll.

### Describe the solution you'd like
Use os.add_dll_directory function right before importing liblouis.dll in lous helper module.

### Describe alternatives you've considered
Leave it as is, although it breaks Python 3.8 compatibility.

### Additional context
See #10384 for details.

**Comment by Brian1Gaff** [comment]
I thought it was unlikely that an update to this version was actually 
planned. Certainly some add ons show a flagged error if that runtime is 
going to be used now, even python 3 ready ones.
 Brian


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by josephsl** [comment]
Hi,

Eventually we will move onto a future Python release which will include this function, so we might as well start noting some things here and there.

Thanks.

**Comment by Adriani90** [comment]
Closing as fixed in #12020.
