### ISSUE TITLE
Background/toolbox mode of NVDA

### ISSUE THREAD

**Issue by TomVal** [nvaccess/nvda#10417]
### Is your feature request related to a problem? Please describe.

I'm a person with low vision, who still operates computer visually, using Windows 10 screen magnifier. NVDA has many useful features I'd like to use, so I'd like to leave NVDA running in background for all the time. This is currently hardly possible since when system's sound output is muted, I have no way to know which document view mode is engaged when switching to web browser, meaning system behaves strangely because of altered behavior of some keys/key combinations in browse mode. I also don't need constant chatter of speech output when focus changes.

### Describe the solution you'd like

I propose to introduce a special NVDA mode, which might be called either *background mode* or *toolbox mode.* This mode would mean NVDA would do following:

- Turn off reporting of focused object when focus changes using standard windows keys (TAB, arrow keys, etc.)
- Set default document view to *focus mode.*
- Don't respond to keys/key combinations which don't involve the NVDA key (in NumLock Off mode, numeric keys act as navigation keys instead of part of NVDA object navigation)
- All the commands involving NVDA key work normally according to NVDA setting. I can thus engage browse mode if I want it, I can have current focused object reported, read the text using NVDA+DownArrow, etc.

### Describe alternatives you've considered

Currently, I'm starting and stopping NVDA when I need it, which introduces some idle time during NVDA startup. So I use it much less than I could.

### Additional context

None.

**Comment by leonardder** [comment]
I think you should be able to do what you want pretty easily.

* Select the "no speech" synthesizer, which will make speech silent. If you want speech, you can enable the synthesizer again. Note that with NVDA+ctrl+s, there's a shortcut to get into that dialog. You can also start NVDA, then turn of speech quickly with NVDA+s
* In NVDA's browse mode settings, disable the check box that says: `Enable browse mode on page load`. This option has been introduced to solve the exact concern you're bringing up about browse mode.

**Comment by Adriani90** [comment]
We didn't get any further arguments from the initial author and I agree with the suggestions from @leonardder. I wouldn't introduce a separate mode for this.
If you want NVDA to be silent while you move the mouse, you can also just hold down the nvda key or the ctrl key while moving the mouse.
Due to several work arounds, I will close this issue for now. if you have other arguments please comment on it and we can reopen it.
