### ISSUE TITLE
NVDA generates error tones when opening categories and subcategories in Windows Settings

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#10422]
### Steps to reproduce:
1. Update NVDA to the latest alpha snapshot build.
2. Open Windows Settings (press Windows+I).
3. Navigate to the list of categories and open a few of them and a few subcategories within them with ENTER. The "System" one is a good example for reproducing the issue.

### Actual behavior:
When opening some of the categories and subcategories, NVDA plays its error sound at least once, which probably indicates some sort of error occurring.

### Expected behavior:
No error should occur when opening categories and subcategories within Windows Settings.

### System configuration
- Operating system: Windows 10 Pro version 1903 (build 18362.449), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-19012,5a0b42ea, in bulgarian.
- Processor: Intel Core i5-4670 at 3.40GHz.
- RAM Memory: 8.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC887 at Intel Lynx Point PCH - High Definition Audio Controller.

#### Does the issue still occur after restarting your PC?
Yes, it does.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I've tried with NVDA 2019.2.1 and the problem seams not to occur. More importantly, this was not occurring with alpha snapshots also until recently, so the fault must be in some recent changes. Maybe related to the changes made for suppressing the NVDA progress bar indications for Windows 10 volume level indicators in the Windows Settings panel (?).

[nvda-old.log](https://github.com/nvaccess/nvda/files/3771014/nvda-old.log)
I'm attaching a log created while reproducing the issue, done with add-ons disabled.

**Comment by zstanecic** [comment]
Hi Kostadin,

This started before the progress bar modifications.

i.e when we have enabled the debugging for comtypes.

It catches some strange comtypes errors.

**Comment by leonardder** [comment]
These errors are caused by increased error logging by comtypes, fortunately it is nothing to worry about. However, the errors indicate an error in our code that needs to be fixed, and that's covered in #10397

**Comment by josephsl** [comment]
Hi,

Update: this is also logged if one opens emoji panel and other modern keyboard features, so this is specific to search field detection. I've just published a pull request to correct this issue for now.

Thanks.
