### ISSUE TITLE
Appveyor improvements: Add a .pot translation template to NVDA CI

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#10433]
Currently when appveyor builds NVDA, the default is to delete the .pot translation template.
### Is your feature request related to a problem? Please describe.
It is recommended that nvaccess can maintain the .pot translation template in appveyor, which can bring convenience to NVDA localization maintainers. If there is a new interface change, the translation maintainer can get the translation template in the first time and then perform the rehearsal test in the local community.
### Describe the solution you'd like
```
Delete - del output\*.pot code segment del
 - py scons.py source %sconsArgs%
 # We don't need launcher to run checkPot, so run the checkPot before launcher.
 - py scons.py checkPot %sconsArgs%
 # The pot gets built by tests, but we don't actually need it as a build artifact.
 -  output\*.pot
 - 'echo scons output targets: %sconsOutTargets%'
 - py scons.py %sconsOutTargets% %sconsArgs%
```

### Describe alternatives you've considered
none
### Additional context
none
thanks

**Comment by Adriani90** [comment]
Fixed in #10465.
