### ISSUE TITLE
Move originating thread info to changes for developers

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#10443]
### Steps to reproduce:

1. open what's new.

### Actual behavior:

• For every entry in the NVDA log, information about the originating thread is now included. (#10259)  is not under changes for developers.

### Expected behavior:
• For every entry in the NVDA log, information about the originating thread is now included. (#10259)  is under changes for devlopers.

### System configuration

**Comment by JulienCochuyt** [comment]
I guess it makes sens. Pushed the change as PR #10445

**Comment by leonardder** [comment]
Honestly, I suggested to put this under 'changes' on purpose, as reading the log is not strictly something that developers do, it could also be relevant for support engineers. Having said that, I think the thread that logged something is something only devs care about.
