### ISSUE TITLE
Error when identifying on a protected web directory

### ISSUE THREAD

**Issue by Oreonan** [nvaccess/nvda#10440]
### Steps to reproduce:
-Try to connect in a website with a protected web directory
### Actual behavior:
-NVDA log many errors in log file
### Expected behavior:
-No error
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-19040,f9388eb5
#### Windows version:
10.0.18363.449
#### Name and version of other software in use when reproducing the issue:
Edge Chromium 79.0.309.5
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
[nvda.log](https://github.com/nvaccess/nvda/files/3785442/nvda.log)

**Comment by JulienCochuyt** [comment]
@Oreonan2, I'm glad I've finally found another user of the windows+number keyboard shortcuts!

This is a huge log file with 25000+ lines for a session lasting more than an hour.
We of course can dig up in it to find ou what's going on, but it really takes an unreasonable amount of time and potentially exposes your personal informations.

Could you please provide a shorter log, restarting NVDA just prior to reproducing the error and shutting down just after?
Please also mind disabling all add-ons to ensure taking them out of the equation.

Finally, what do you mean by "protected web directory" ? Is it a WebDAV of some kind or just basic directory listings - which are indeed nothing more than regular HTML? Is the protection form-based or browser-based?

**Comment by Oreonan2** [comment]
Soory for the big log file, I attach a short log in this comment.
The protection is based on http method, with .htaccess and .htpasswd files, a dialog box of navigator appear to authentified.
[nvda.log](https://github.com/nvaccess/nvda/files/3787152/nvda.log)

**Comment by Adriani90** [comment]
@Oreonan could you please test with NVDA last Alpha version and Edge Cromium 81? Is this still reproducible?

**Comment by Oreonan** [comment]
@Adriani90 Ah no, I just tested and I confirm that I do not reproduce the bug today
