### ISSUE TITLE
Reconsider making UIA default for terminals on Windows 10

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#10477]
Edited to reflect current state.
### Is your feature request related to a problem? Please describe.
In #9771 we decided to enable UIA in consoles by default for two most recent releases of Windows 10 and all future ones. While it improves performance in consoles it also introduces some issues. I'll try to list them by the order of importance.
- #10191
- #10036
- #10119
- #10113

The order is of course a little subjective.
The problem is that some of these are not easy to fix, others are not always reproducible, and in general most of them are not being worked on at the moment.
### Describe the solution you'd like
As the support for consoles introduces regressions for users either do not enable it until it is mature enough, or fix most (preferably al) of them before 2019.3

### Describe alternatives you've considered
Leave it as is and hope that users would live with these problems.
### Additional context
We had similar situation with making UIA default for MS Word. After doing it for a short time in Alpha versions it has been decided not to do this due to amount of problems it introduces.

**Comment by lukaszgo1** [comment]
cc @leonardder @feerrenrut @michaelDCurran

**Comment by leonardder** [comment]
Also cc @codeofdusk

**Comment by codeofdusk** [comment]
I’d really hate to see #9771 reverted, as UIA console does provide serious improvement in many (even most) cases.

Re #10406 could a test case be provided that reliably reproduces this?

Re #10191 did #10057 and #10091 not fix this? Could a heavy Braille user please re-test? Cc @leonardder

Re #9689 I’m sure this was fixed in #9802. @leonardder could you please re-test?

**Comment by michaelDCurran** [comment]
#10406 was closed with the merging of pr #10513 .
I have closed #9689 as it is no longer reproduceable. 
I feel that  #10191 and #10113 are the most serious. The others can probably fixed with out too much issue.

**Comment by codeofdusk** [comment]
Fixed in #10559.

**Comment by codeofdusk** [comment]
All of the linked issues (above) have been closed as of #10559.

**Comment by lukaszgo1** [comment]
Closing as per commend above.
