### ISSUE TITLE
aomei partition standard unable to access any menues

### ISSUE THREAD

**Issue by mhussaincov** [nvaccess/nvda#10485]
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

### Steps to reproduce:
have nvda running,
launch AOMEI Partition Assistant Standard Edition 8.5
try to navigate the menus

### Actual behavior:
i'm unable to access the menus or the disk utilities

### Expected behavior:
I should be able to access the menus, such as the wizards menu.

#### NVDA installed/portable/running from source:

installed
#### NVDA version:
NVDA 2019.2.1 

#### Windows version:
windows 10 v1909
#### Name and version of other software in use when reproducing the issue:
AOMEI Partition Assistant Standard Edition 8.5
#### Does the issue still occur after restarting your PC?
YES
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NO

**Comment by Brian1Gaff** [comment]
Is this app even accessible with Jaws? I'm sure I've seen criticism of it 
somewhere else, but cannot recall where.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by mhussaincov** [comment]
hi there,
I know that v7.5.1 was but this,


On 12/11/2019, Brian Gaff <notifications@github.com> wrote:
> Is this app even accessible with Jaws? I'm sure I've seen criticism of it
> somewhere else, but cannot recall where.
>  Brian
>
> bglists@blueyonder.co.uk
> Sent via blueyonder.
> Please address personal E-mail to:-
> briang1@blueyonder.co.uk, putting 'Brian Gaff'
> in the display name field.
> Newsgroup monitored: alt.comp.blind-users
> -----
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/10485#issuecomment-553049070


-- 
kind regards,
Majid Hussain

**Comment by Adriani90** [comment]
@mhussaincov are you still having this issue with NVDA 2023.2 and Aomei 10.2?

**Comment by Adriani90** [comment]
We didn't get any update upon request from the initial author since many years, I am closing as abandoned. If you are still having this issue, please comment and we can reopen.
