### ISSUE TITLE
Update Section 13.1 and 13.5 of the User Guide to reflect Windows OneCore as default synthesizer in Windows 10

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#10495]
### Steps to reproduce:
Open User Guide section 13.1: https://www.nvaccess.org/files/nvda/documentation/userGuide.html#eSpeakNG

### Actual behavior:

Section 13.1 reads: "13.1. eSpeak NG
The eSpeak NG synthesizer is built directly into NVDA and does not require any other special drivers or components to be installed. NVDA starts using eSpeak NG by default. As this synthesizer is built into NVDA, this is a great choice for when running NVDA off a USB thumb drive on other systems.

Each voice that comes with eSpeak NG speaks a different language. There are over 43 different languages supported by eSpeak NG.

There are also many variants which can be chosen to alter the sound of the voice."

Section 13.5 reads:
"13.5. Windows OneCore Voices
Windows 10 includes new voices known as "OneCore" or "mobile" voices. Voices are provided for many languages, and they are more responsive than the Microsoft voices available using Microsoft Speech API version 5.

Please see this Microsoft article for a list of available voices and instructions to install them: https://support.microsoft.com/en-us/help/22797/windows-10-narrator-tts-voices

Please note that the faster rates available with Narrator are not currently available with NVDA. Also, the speed you select in the Windows Settings affects the rate set in NVDA. These are issues we cannot resolve without changes to Windows. We are hopeful that these will be addressed in a future Windows update."

### Expected behavior:

Change sentence two of 13.1 to:

"NVDA starts using eSpeak NG by default in Windows 7 or 8 (Windows OneCore is used by default in Windows 10)."

In Section 13.5, add a new sentence at the end of the first paragraph which reads:
"NVDA starts using Windows OneCore Voices by default in Windows 10 (eSpeak NG is used by default in earlier versions of Windows)."

Also, as I believe all the issues mentioned in the final paragraph of 13.5 have been resolved, remove this paragraph entirely: "Please note that the faster rates available with Narrator are not currently available with NVDA. Also, the speed you select in the Windows Settings affects the rate set in NVDA. These are issues we cannot resolve without changes to Windows. We are hopeful that these will be addressed in a future Windows update. "

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.2.1
also alpha-19159,cde557d5

#### Windows version:
Windows 10 Version: 
18362

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
As noted, the latest alpha and 2019.2.1

**Comment by josephsl** [comment]
Hi, been meaning to look for a motivation to work on docs19.3 pass 2 to address this and what’s new changes. I’ll get on it in a few minutes. Thanks.
