### ISSUE TITLE
NVDA sometimes loses speech when toggling highlight

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#10509]
### Steps to reproduce:

* Start the computer. Note: I do not start Zoomtext nor Windows Magnifier.
* Start NVDA (from source)
* Open Vision settings panel
* Tab to the first item 'Enable Highlight'
* Press 'E' key during about 5 seconds; should activate and unactivate 'Enable Highlight' item at very high frequency.
* Press Tab many times to go to next items.

### Actual behavior:

Nothing is heard.
However, pressing windows key a few times let me know visually that the system is responsive since I can see the start menu open and close without delay.

Log attached: 
[nvda.log](https://github.com/nvaccess/nvda/files/3863918/nvda.log)

### Expected behavior:

The focus should move to the next item and thus, these items should be announced.

### Context

The steps to reproduce is not a real use case, but it is the best stress test I found to be able to reproduce the issue.
The original real use case is just playing with various options in the Vision panel, as an exploration, i.e. tabbing around and toggling the various focus highlight options. I got however the bug only randomly and very few times (about 1/30); that why I have tried to find a use case easier to reproduce.

#### NVDA installed/portable/running from source:

From source

#### NVDA version:

Version : source-master-e7b61dc
(last master version)

#### Windows version:

Windows 10 1709

#### Name and version of other software in use when reproducing the issue:

N/A

#### Other information about your system:

Zoomtext installed but not active since the time I have started my PC. I did not start Zoomtext nor Windows Magnifier, in order not to interfer with the Highlight feature.

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No, not applicable for older versions since this feature is new.
I did not try with last snapshot.

**Comment by CyrilleB79** [comment]
Cc @leonardder , @feerrenrut

**Comment by leonardder** [comment]
Ugh, this probably has to do with the highlighter thread not being 
killed correctly. I will try to come up with a fix tomorrow.
