### ISSUE TITLE
MS Teams: [Shifts app]: From second time onwards, NVDA is not reading the displayed tooltip information when "Shift Activities info (i)" button was activated

### ISSUE THREAD

**Issue by HarishTerala** [nvaccess/nvda#10517]
### Steps to reproduce:
1. Open MS Teams app.
2. Open "Shift" app from "More added apps". (Install "Shifts" app if not installed)
3. Navigate to any shifts grid and activate "+ Add shift" from "More options".
4. Turn off browse mode if enabled, press Tab/Shift+Tab key to navigate to "Shift Activities info (i)" button and activate it. Verify the speech of NVDA.
5. Again navigate back and activate "Shift Activities info (i)". Verify the speech of NVDA.

### Actual behavior:
From second time onwards, NVDA is not reading the displayed tooltip information when "Shift Activities info (i)" button was activated. NVDA reads as "blank" in both focus and browse modes.

### Expected behavior:
NVDA should read the displayed tooltip information everytime when "Shift Activities info (i)" button was activated in both focus and browse modes.
Eg: Schedule daily activities here and see them in the day view. Activities can be used for anything you need to schedule during the shift.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.2.1

#### Windows version:
Win10 1903

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by Adriani90** [comment]
@HarishTerala the shifts app is available only for enterprise customers, we are not able to test and reproduce this issue. Please provide a minimal html test case from the app, please include in the test case only the code for the button and for the display tooltip, and remove noisy code which is not relevant for this issue.

**Comment by seanbudd** [comment]
Closing this until information is provided to reproduce it.
