### ISSUE TITLE
MS Teams: [Meetings - Screen share]: In browse mode, when desktop screen was shared, NVDA reads about the external call monitor, instead reading about the shared window

### ISSUE THREAD

**Issue by HarishTerala** [nvaccess/nvda#10528]
### Steps to reproduce:
1. Open MS Teams app.
2. Join any scheduled screen and open share panel. (Make sure browse mode is enabled)
3. Navigate to "Desktop" preview screen and press Enter key.
4. Verify the focus sync issue and speech of NVDA.

### Actual behavior:
In browse mode, when desktop screen was shared NVDA reads as "Call is in progress. Click here to go back to the call screen.", pressing Enter key will ends the call.

### Expected behavior:
In browse mode, when desktop screen was shared NVDA focus should sync with the keyboard focus and NVDA should read about the shared screen information.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.2.1

#### Windows version:
Win10 1903

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by leonardder** [comment]
Could you reproduce this in MS Teams on the web? Also, that makes you think that this is an issue in NVDA?

**Comment by HarishTerala** [comment]
Same is reproducible on Chrome. 

This issue does not reproduce on Win32+JAWS, Chrome+JAWS, Mac+VoiceOver.

**Comment by Adriani90** [comment]
@HarishTerala are you still having this issue with NVDA 2024.4 and the new MS Teams, or while using the browsers last version?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author upon request since many years. Closing as abandoned.
If you are still having this issue with Teams Mini Version 24335.208.3315.1951 / Clientversion 49/24120100212 or newer, please comment and we can reopen.
