### ISSUE TITLE
Regression: Adobe Flash support in version 2018.4 and later

### ISSUE THREAD

**Issue by tmthywynn8** [nvaccess/nvda#10565]
As of NVDA 2018.4, support for Adobe Flash in NVDA ceased working. I know that Flash support is ending for other browser vendors at the end of 2020, i.e., [Microsoft](https://blogs.windows.com/msedgedev/2017/07/25/flash-on-windows-timeline/), [Mozilla](https://blog.mozilla.org/futurereleases/2017/07/25/firefox-roadmap-flash-end-life/), [Google](https://www.blog.google/products/chrome/saying-goodbye-flash-chrome/), and [Apple](https://webkit.org/blog/7839/adobe-announces-flash-distribution-and-updates-to-end/), but until then, NVDA should still support it for some of the fringe sites where Flash is still being used.

### Steps to reproduce:

1. Using Internet Explorer, open the [Flash Examples](https://condor.depaul.edu/sjost/hci430/flash-examples.htm) page.
2. Once the page loads, activate the [number-pad](https://condor.depaul.edu/sjost/hci430/flash-examples/swf/number-pad.swf) link.
    - Note: number-pad.swf has been linked for convenience.
3. Press *Enter* on the embedded object to start interaction.

### Actual behavior:

NVDA says ""embedded object" followed by "pane". One can tab among the elements in the SWF object, and use object navigation to interact with other elements, but interaction in browse mode simply says "blank".

### Expected behavior:

In NVDA 2018.3 and earlier, after the ""embedded object" and "pane" utterances, NVDA then says "edit". One can then use *Down-arrow* among digits 1-0 and the clear button (labeled "C"). One can even press *NVDA+Control+Space* to move the focus out of the embedded object.

### System configuration

- NVDA installed/portable/running from source: Installed
- NVDA version: 2019.2.1
- Windows version: Windows 10 Version 1809 (OS Build 17763.864)
- Name and version of other software in use when reproducing the issue:
    - Internet Explorer Version 11.864.17763.0
    - Flash Version 32.0.0.255

### Other questions

- Does the issue still occur after restarting your PC?
    - Yes
- Have you tried any other versions of NVDA? If so, please report their behaviors.
    - See above. Note that 2018.4 is the first version that breaks Flash support.

**Comment by Brian1Gaff** [comment]
Does this also fail in other browsers besides IE?
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by leonardder** [comment]
Closing in favour of newer duplicate #11131.
