### ISSUE TITLE
Automatic reading of incoming console text with UIA is severely broken

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#10566]
CC: @codeofdusk

### Steps to reproduce:

Use the terminal with the experimental UIA support enabled.

### Actual behavior:

Either incoming text is not read, or old text is read instead of the updated region of the screen. Using the review cursor also doesn't seem to work properly, if I can reproduce this more reliably I'll open another issue.

### Expected behavior:

Incoming text is read accurately.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

Latest alpha as of time of writing, alpha-19356,6fc6637d

#### Windows version:

Windows 10 1903

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

**Comment by codeofdusk** [comment]
To be fixed by #10559 (WIP).

**Comment by lukaszgo1** [comment]
@Neurrone According to @codeofdusk this should be fixed in the latest Alpha. Can you confirm?

**Comment by Neurrone** [comment]
This appears to be fixed, thanks.
