### ISSUE TITLE
Error when testing Braille viewer with NVDA version alpha-19410

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#10578]
In Error when testing Braille viewer with NVDA version alpha-19410

### Steps to reproduce:
First open the NVDA menu
Then enable Braille viewer from the tools submenu
At this time an error tone will be issued
### Actual behavior:
error
### Expected behavior:
normal work
#### NVDA installed/portable/running from source:
install version
#### NVDA version:
NVDA version alpha-19410
#### Windows version:
windows10-1909
#### Name and version of other software in use when reproducing the issue:
none
#### Other information about your system:
none
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
none
NVDA log:

ERROR - unhandled exception (19:02:07.796) - MainThread (8108):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 326, in onToggleBrailleViewerCommand
  File "brailleViewer\__init__.pyc", line 119, in createBrailleViewerTool
  File "brailleViewer\brailleViewerGui.pyc", line 65, in __init__
  File "brailleViewer\brailleViewerGui.pyc", line 145, in _setBrailleFont
  File "fonts\__init__.pyc", line 33, in importFonts
FileNotFoundError: [WinError 3] The system cannot find the path specified. : 'fonts'
thanks

**Comment by dingpengyu** [comment]
cc @feerrenrut

**Comment by leonardder** [comment]
It looks like the fonts have to be added to the data files in setup.py.

**Comment by feerrenrut** [comment]
Thanks @dingpengyu and @leonardder I'm looking at this now.

**Comment by lukaszgo1** [comment]
@feerrenrut While not directly related the following is witten in the log after unchecking Braille Viewer from the tools menu:
ERROR - unhandled exception (13:03:17.072) - MainThread (3560):
Traceback (most recent call last):
  File "brailleViewer\brailleViewerGui.py", line 198, in _onDestroy
    self._savePositionInformation()
  File "brailleViewer\brailleViewerGui.py", line 180, in _savePositionInformation
    position = self.GetPosition()
RuntimeError: wrapped C/C++ object of type BrailleViewerFrame has been deleted

 Could you also take a look while you are at it?
