### ISSUE TITLE
Tab traversal broken in Speech Viewer

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#10582]
### Steps to reproduce:
1. Open Speech Viewer
2. Use tab to navigate through the speech viewer.

### Actual behavior:
Tab doesn't jump from control to control

### Expected behavior:
Tab jumps from control to control.

## Additional context
It looks like wx.Frame doesn't implement tab traversal like wx.Dialog. May be this can be fixed by putting all controls on a wx.Panel inside the frame.

**Comment by feerrenrut** [comment]
Fixed by #10585 with commit 4cc025b5208d2106601847bcf6a38484836033fc
