### ISSUE TITLE
Windows 7 - X64: Extraneous Text announced by NVDA within Windows Explorer when Reading Tooltips of Directories that have an & Character

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10594]
### Steps to reproduce:

This is similar to #5210, with a slightly different set of steps performed to reproduce - this assumes that the reading of tooltips is enabled from within NVDA's preferences:

1. From within Windows Explorer, create a new folder with a name of "Explorer Test Folder to test & NVDA"

2. Enter the directory, and place several random files within; these can be of any filetype and of any size. Once done, use the Backspace key to navigate back out of the directory

3. Move focus up one item, and then down so that focus is returned to the just-created folder

### Actual behavior:

NVDA reads the tooltip for the just-created folder, along with all required info; however, after the last piece of information is output (the words "tool tip"), NVDA then announces the shortcut key of "alt+"

### Expected behavior:

This only appears to happen due to the "&" character placed in the folder name. If one of these is encountered, NVDA should simply read the tooltip as it would for any other

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.2.1

#### Windows version:

Windows 7 X64

**Comment by Adriani90** [comment]
cc: @lukaszgo1

**Comment by lukaszgo1** [comment]
I cannot reproduce this with latest Alpha nor with 2019.2.1. I can however reproduce #5210

**Comment by Adriani90** [comment]
Support for Windows 7 has completely ended in 2020. I am closing this as abandoned since I don't expect further accessibility updates to Windows 7. If you are still having this issue on Windows 10 or newer, then please comment on this issue and we can reopen. Or open a new issue with updated steps to reproduce.
