### ISSUE TITLE
when switching from another synth to espeak, the exception is generated and the synth has switched successfully

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#10592]
### Steps to reproduce:
1. switch from espeak to any synthesizer
2. switch from this synthesizer to espeak back again
### Actual behavior:
we have the following exception in the log
INFO - synthDrivers.espeak.SynthDriver.__init__ (14:40:32.566) - MainThread (2988):
Using eSpeak NG version b'1.49.3 dev'
INFO - synthDriverHandler.setSynth (14:40:39.122) - MainThread (2988):
Loaded synthDriver espeak
ERROR - unhandled exception (14:40:39.214) - MainThread (2988):
Traceback (most recent call last):
  File "wx\core.pyc", line 3240, in <lambda>
  File "gui\settingsDialogs.pyc", line 1313, in refreshGui
RuntimeError: wrapped C/C++ object of type BoxSizer has been deleted
Note that it switches normally and plays an error sound
### Expected behavior:
we shouldn't have this exception
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
alpha-19432,4cc025b5

#### Windows version:
windows 10, 1909, 18363
#### Name and version of other software in use when reproducing the issue:
n/a
#### Other information about your system:
Lenovo ideapad 320 isk 15, intel i3 6006U,
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
not applicable

**Comment by Adriani90** [comment]
@zstanecic I cannot reproduce this issue in NVDA alpha-20220,1c4519a6. Are you still having this issue?
Which synthesizers did you test with? Itried IBM TTS, Onecore and eSpeak and switching back and forth. I don't get any exception in the log. Do you by chance habe any NVDA dialogs open while switching the synthesizers?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years and I cannot reproduce this . Additionally, it might also be related or even duplicate of #13042.

I am closing this issue as abandoned.
