### ISSUE TITLE
Re-add Screen Curtain Enabled Beep at NVDA StartUp

### ISSUE THREAD

**Issue by ntcarver0** [nvaccess/nvda#10602]
### Is your feature request related to a problem? Please describe.
If a user is is expecting the enabled beep that was available in the Screen Curtain add-on when NVDA was started and Screen Curtain was enabled by default, they may incorrectly assume that Screen Curtain is not enabled in NVDA 2019.3beta1 after a restart.

### Describe the solution you'd like
If it is possible, it would be great to have the beep that played when NVDA started and Screen Curtain was enabled by default implemented in NVDA 2019.3. This beep provides piece of mind that Screen Curtain is in deed enabled and saves the user from having to check, especially  if they frequently have to toggle Screen Curtain on or off.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by davidacm** [comment]
I agree with this. In fact, a command to ask the status of this feature should be provided.
Even with the add-on, I usually have to change the screen curtain status to check if the feature is enabled or disabled.
Also a tone can be played when the screen curtain is enabled, even if the feature was enabled with a gesture.

**Comment by leonardder** [comment]
Interesting suggestion. This might also cover the case mentioned in #10476 where someone misses the switch of the curtain.

**Comment by feerrenrut** [comment]
Fixed with commit f194afaec02a3465ceb769ee88543ea337c6eb9e via #10611
