### ISSUE TITLE
In Electron apps, disable browse mode by default

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#10601]
### Is your feature request related to a problem? Please describe.
The number of Electron apps as well as applications where browse mode is triggered erroneously is increasing.

### Describe the solution you'd like
 I'd like to suggest to disable browse mode by default for at least the following apps and cases, in addition to Visual Studio Code and Skype:

* Spotify
* Microsoft Teams
* Windows Explorer (triggered when pressing applications key on a start menu item)
* Slack

### Describe alternatives you've considered
We can do this on a per appModule level, but may be there is some logic we can apply to do this for Electron apps by default. However, WhatsApp Desktop is an example of an Electron apps where browse mode is required to move through the app or read text in it.

I wonder what @jcsteh has to say here, especially regarding Spotify.

**Comment by jcsteh** [comment]
This really concerns me. Certainly, having used it extensively, I don't
think Spotify is particularly usable without browse mode. Same for many
parts of Slack, although they at least have tried to implement keyboard
navigation (albeit quirkily/buggily).

**Comment by leonardder** [comment]
Interesting findings. May be we should advertise the using browse mode on page load options in configuration profiles instead.
As for MS Teams, using browse mode really slows down its use, so I will start with a pull request for it, whereas leaving Spotify and SLack as they are.

**Comment by lukaszgo1** [comment]
The problem with overwriting it per appModule is that users cannot disable it with a configuration profile. When browse mode got disabled by default for Skype there were some users on NVDA list for whom this broke their workflow - their were apparently used to navigating through Skype by searching particular strings with CTRL+NVDA+F.

**Comment by leonardder** [comment]
I'm closing this as there are many disadvantages to the proposal I hadn't yet carefully considered.

**Comment by DrSooom** [comment]
Isn't it possible to add a list of checkboxes, which contains a few Electron apps? So the end user can enable and disable default focus mode for them via the Browse Mode NVDA Settings. See also the behavior of the checkbox "Enable browse mode on page load".

Please note that Electron apps are updated very often a year due to security reasons. So it should be made configurable for the end user in a very easy way – and not only via configuration profiles.
