### ISSUE TITLE
IE11: toggleVirtualBuffer, no audio indication of Focus and Browse modes

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#10613]
This case occurs in edit field only. When user moves to edit field, and manually force focus mode.

### Steps to reproduce:
1. Open an internal page.
2. Press e to move to edit field.
3. Press NVDA+space to switch to focus mode.
(No audio indication. NVDA played audio error.wav.)
4. Press NVDA+space to switch to browse mode.
#### Actual behavior:
(No audio indication.)
By using single letter nav, user knows that it is in browse mode now.
#### Expected behavior:
NVDA played audio indication. 

#### NVDA Installed/portable/running from source:
portable.

#### NVDA version:
2019.3Beta1

#### Windows version:
6.1.7601 service pack 1

#### Name and version of other software in use when reproducing the issue:
browser: Internet Explorer 11

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA?
Yes, this case does not occur in NVDA_2019.2.1 and NVDA alpha-18874.

### Developer info:
Log file starts from line 486.
[nvda toggle Virtual buffer.log](https://github.com/nvaccess/nvda/files/3958431/nvda.toggle.Virtual.buffer.line.486.log)

**Comment by Adriani90** [comment]
cc: @feerrenrut

**Comment by surfer0627** [comment]
[nvda toggle Virtual buffer line 486.log](https://github.com/nvaccess/nvda/files/3958401/nvda.toggle.Virtual.buffer.line.486.log)

**Comment by surfer0627** [comment]
Hi,
* This case occurs only when braille display is connected. In speech only, NVDA (audio indication) works as expected.
* This case occurs in [alpha-19012](https://ci.appveyor.com/api/buildjobs/v6ohkbyiexgp1edj/artifacts/output/nvda_snapshot_alpha-19012,5a0b42ea.exe) and later.
* braille display: Freedom Scientific PAC Mate

**Comment by lukaszgo1** [comment]
Why we are using EdgeNode from UIA for edit fields in Internet Explorer at all? cc @leonardder

**Comment by lukaszgo1** [comment]
@surfer0627 Could you please test your webpage with [This try build](https://ci.appveyor.com/api/buildjobs/kfewk95k37y2ekl0/artifacts/output%2Fnvda_snapshot_pr10652-19478%2C34d05d9a.exe)?

**Comment by surfer0627** [comment]
@lukaszgo1
This try build fixes audio indication issue in IE!
Thank you for help.
