### ISSUE TITLE
FAQs reading is wrong

### ISSUE THREAD

**Issue by MariiaRi** [nvaccess/nvda#10614]

**Comment by XLTechie** [comment]
What synth are you using?

**Comment by MariiaRi** [comment]
I have Windows OneCore voices, but checked the others as well and I can reproduce.

**Comment by Adriani90** [comment]
This is specific to Synthesizers and can only be solved by adding an Expression to the dictionary or by changing the phonemes in the Synthesizer itself. Please contact the synth Provider for a solution.
Closing as invalid.
