### ISSUE TITLE
Allow the Focus Mode cursor and Brows Mode Cursor to sync in HTML editable applications

### ISSUE THREAD

**Issue by frastlin** [nvaccess/nvda#10610]
### Is your feature request related to a problem? Please describe.

The problem is that I am unable to treat rich text editing applications, like [Google Docs](https://github.com/nvaccess/nvda/issues/9041) like Word, which makes Word my defacto text editor, just because of how quick I can move between elements when in brows mode.

### Describe the solution you'd like

I would like when I am editing, and press NVDA+space to exit the edit mode, that my brows mode cursor is at the same location as my edit mode cursor was.
Conversely, when I hit enter on an element in brows mode, I would like my cursor in edit mode to be where I hit enter.

### Describe alternatives you've considered

There are no alternatives if one wishes to edit using an application on the web.
There may be some way to do this in your HTML app itself by making every element clickable and when you hit enter on an editable element, it focuses on that line, but it's not the same.
I would also love if spelling errors and other information were reported in the brows mode, similar to what Word does.

### Additional context

There are more rich text editors on the web than there are on the desktop by a significant margin, Google Docs, Office 365, and Tiny MCE being the most prevalent, but despite this, it is still more user-friendly to write in Word, which is a paid application.

### Steps to reproduce the disconnect

1.       Open:
https://www.tiny.cloud/docs/demo/basic-example/
2.       Press o to get to the "Application" and hit enter.
3.       Press escape until you are placed in the editing area.
4.       Arrow down several lines
5.       Press NVDA+space to go into brows mode.
6.       Arrow up and down to find out your cursor when editing is different than your cursor when in brows mode.
7.       In brows mode, hit h to go to "A simple table to play with" and hit enter.
8.       Press read current line and it will be on the last line you were on in focus mode.

**Comment by brunoprietog** [comment]
Hello,
In Microsoft Word, using UI Automation (you can activate this in advanced options) the same thing happens, there is no way to synchronize both modes as you can do with this option deactivated.

I'd love to see that issue solved.

Greetings

**Comment by frastlin** [comment]
If UIA automation is planned to become standard, this feature needs to be fixed. This feature is the only reason why I still use word for word processing.

**Comment by Adriani90** [comment]
cc: @michaelDCurran maybe worthy to have a look to when considering further future work on UIA support.

**Comment by michaelDCurran** [comment]
In regards to syncing browse and focus mode cursors in Microsoft Word with UIA enabled, this has been specifically tracked in #9611 
And fixed in pr #12803.

**Comment by Adriani90** [comment]
MCE and Google Docs use the same technology as far as I understand, and that is the only point to be fixed still. Regarding spelling errors, this needs to be specified in the HTmL code of the website, and then NVDA can recognize it. So for that part an external fix is needed and you should report that to Google or the MCE developers.

Regarding browse mode and focus mode sync in ritch edit, I am closing this issue in favor of #9041.
If you are having other issues, please open new separate requests with clear steps to reproduce.
