### ISSUE TITLE
2019.3 beta 1 logs this error semi-frequently

### ISSUE THREAD

**Issue by mehgcap** [nvaccess/nvda#10619]
### Steps to reproduce:
not known

### Actual behavior:
Nothing odd happens, except the two-note sound indicating an error. Each time I check the log, I find the same traceback. Here it is:

```
ERROR - core.CorePump.run (08:48:53.754) - MainThread (9024):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 517, in run
  File "braille.pyc", line 2216, in pumpAll
  File "braille.pyc", line 1952, in handlePendingCaretUpdate
  File "braille.pyc", line 1958, in _doCursorMove
  File "braille.pyc", line 1011, in update
  File "braille.pyc", line 849, in _addTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 342, in getTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 305, in _getText
IndexError: pop from empty list
```
### Expected behavior:
n/a
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
2019.3 beta 1
#### Windows version:
10, 1903
#### Name and version of other software in use when reproducing the issue:
no specific software seems to trigger the problem
#### Other information about your system:
n/a
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
new in this beta as far as I can tell, though I don't often read the log on non-beta versions

**Comment by Brian1Gaff** [comment]
Reminds me of the way the suggest number of items in a list often gets it 
wrong.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by leonardder** [comment]
> Reminds me of the way the suggest number of items in a list often gets it wrong.

That's entirely unrelated.

According to the log, it looks like you were using Firefox or Thunderbird when triggering this problem. Do you use one or both of those?

**Comment by DrSooom** [comment]
Maybe related: #8967

@mehgcap: I guess if you have disabled the braille output (= no braille display), then this error doesn't occur, right?

**Comment by mehgcap** [comment]
Yes, I was using Firefox. I thought I noticed it happening in other apps as well, though I could be wrong.

Yes, if no braille display is in use, the error goes away.

**Comment by Adriani90** [comment]
cc: @MarcoZehe

**Comment by feerrenrut** [comment]
I expect this is a quick fix, though I haven't investigated. Since it is not causing any noticeable bad behavior, it won't get fixed for 2019.3

**Comment by lukaszgo1** [comment]
@feerrenrut May I ask why this one has been assigned a P1? It seems it only causes error sound to be played and there is no noticeable bad behavior for the user.
I've thought that P1 is reserved for severe crashes of either NVDA or other programs when accessed with it.

**Comment by feerrenrut** [comment]
Because I suspect its a quick fix, and until investigated it's hard to be sure that it isn't causing hard to detect problems.

**Comment by Adriani90** [comment]
@mehgcap are you still seeing this error in NVDA 2020.1 with Firefox 76? Please also try to run the COM resgistration fixing tool in NVDA menu / tools and see if the error occurs after that. Please report your results here. Thanks.
