### ISSUE TITLE
Python3. Eliminate the long silence in the one core voices

### ISSUE THREAD

**Issue by comunicationVoices** [nvaccess/nvda#10621]
Hello, in the version of NVDA 2019.3beta1, the long silences in windows one core remain as the versions below 2019.1. Silences happen when the text has a period, or two points, etc. I would like you to solve this error. Thank you for reading!

**Comment by josephsl** [comment]
Hi, just to clarify: you are saying that this is not happening with 2019.2.1, correct? If so, it is a definite regression. Thanks.

**Comment by Adriani90** [comment]
@comunicationVoices could you please answer to the question above? Is this not reproducible with NVDA 2019.2.1?

**Comment by comunicationVoices** [comment]
Hi. This error only occurs with 2019.3, in the beta version for python 3. I
just clarify this, regards.

**Comment by feerrenrut** [comment]
Closing as a duplicate of #10721 which has the template filled out.
