### ISSUE TITLE
No Addons will Install in Beta 3.

### ISSUE THREAD

**Issue by mikebayus** [nvaccess/nvda#10639]
Hi Guys, I have tried installing addons, the ones that the NVDA community announcement page on the Addons web site says work, but they won't install.

You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

### Steps to reproduce:

Actual behavior:
Addonws won't install.### 
### Expected behavior:
Install addons in Beta 3.
### System configuration

NVDA installed on hard-drive.

#### NVDA version:
2019.3 beta1
#### Windows version:
10 latest build
#### Name and version of other software in use when reproducing the issue:
NA.
#### Other information about your system:
HP Laptop.
#### Does the issue still occur after restarting your PC?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
All of my Addons worked in NVDA 2019.2

**Comment by josephsl** [comment]
Hi, I see, but we are missing a crucial puzzle piece: which add-ons were you trying to install? Thanks.

**Comment by mikebayus** [comment]
Well, the first one I tried was the addon for Bluetooth Audio, and when
that one didn't install, and I got the Addon requirews update message, I
tried all of the other ones on the Addon NVDA community announcement page
on the community addons Web Site.

Well... all of the ones that are supposed to work with Python 3.7 and later
anyway.

None of them install.

So I suppose it would be easier to tell you which ones I didn't try to
install, and those were the ones that said "Work in progress".

O.K?

The Addon that I am most concerned about is the one from acapela, and I
know that one won't work.

Bye Bye Ella!

Many thanks.

**Comment by josephsl** [comment]
Hi, ah… Bluetooth Audio add-on doesn’t even have manifest information. I’ll do something about this. Thanks.

**Comment by mikebayus** [comment]
Hello Joseph,

The other Addon I really got a lot of use out of was the VLC Media Player one.

That one won't install either.

Do you think that that is the problem with many of the other Addons on
the Web Site?

Because the addons that I tried wouldn't install, I couldn't get to
any of the manifests.

And, just so you know, I, because I dreaded the idea of having to face
Ella withdrawal, I looked for a SAPI5 voice that I could make sound as
much like Ella as was possible.

I found Zoe, a Nuance Vocalizer voice, but SAPI5, and then, I got
Mairi, from CereProc.

Things that make you go:  "hmmm!"

**Comment by josephsl** [comment]
Hi, manifest issue is one of the biggest issues regarding add-on compatibility – the others have to do with changes in terms of Python 2 to 3 and others introduced in NVDA 2019.3. I have advised the add-ons community to resolve manifest problem as soon as possible, and have marked affected add-ons (including Bluetooth Audio) as incompatible. Thanks for bringing this up.

**Comment by mikebayus** [comment]
You are most welcome.

**Comment by Adriani90** [comment]
Thanks for reporting. However, since this issue is related to the addons themselves, please report it to the authors of the addon or on the users mailing list at
https://nvda.groups.io/g/nvda
Closing this for now.
