### ISSUE TITLE
Installer: Delete temporary files in libs

### ISSUE THREAD

**Issue by OzancanKaratas** [nvaccess/nvda#10630]
### Steps to reproduce:
The installer should be prompted to stop or restart programs that use lib DLLs.
### Actual behavior:
NVDA installer does not delete the DLLs in libs.
### Expected behavior:
Installer should remove the old version DLLs instead of creating temporary files.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2019.3beta1
#### Windows version:
Windows 10 version 1909
#### Name and version of other software in use when reproducing the issue:
The issue related with NVDA installer.
#### Other information about your system:
No needed.
#### Does the issue still occur after restarting your PC?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
All versions in 2019 and 2018.

**Comment by SeanTolstoyevski** [comment]
Hi @OzancanKaratas ,
Which DLL files are you talking about deleting?

It makes no sense that NVDA deletes the DLL file of another program.
If these files are NVDA's, we can delete the old DLLs that remain in the temp file.

**Comment by OzancanKaratas** [comment]
I mentioned NVDA's old DLLs. So the temporary files.

**Comment by OzancanKaratas** [comment]
I'll close this issue, because it requires extra work and it's not worth doing.
