### ISSUE TITLE
Progress Bar Label not being read with Firefox

### ISSUE THREAD

**Issue by jnurthen** [nvaccess/nvda#10646]
### Steps to reproduce:
Open https://codepen.io/jnurthen/full/abzJWQd
The page has a link followed by 2 progress bars.
The first is Labelled Loading.... and the Valuetext is set to 50%
The second is also Labelled Loading but has no valuetext (or valuenow)

*Note: ProgressBar has accessible Name required in ARIA so all progress bars should have a label

### Actual behavior:
The first progressbar is read as "Progress bar 50%"

### Expected behavior:
It should be read as "Loading.... Progress bar 50%"

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.2.1

#### Windows version:
Windows 10 19013.1122

#### Name and version of other software in use when reproducing the issue:
Firefox 71.0

**Comment by Adriani90** [comment]
In Chrome the effect is either way. The label is read but not the value.
This seems inconsistent in browsers. I am not sure if NVDA can do something about this.

cc: @jcsteh, @aleventhal.

**Comment by jcsteh** [comment]
NVDA's rules about visible labels apply here. If the label is visible (which it is), the label is rendered where it is found and it is not reported again when you move to the control, since otherwise, you would get duplicate information as you move through the document.

**Comment by Adriani90** [comment]
Given the comment above, I am closing this issue as works for me.
