### ISSUE TITLE
Progress Bar Value not being read with Chrome

### ISSUE THREAD

**Issue by jnurthen** [nvaccess/nvda#10645]
### Steps to reproduce:
Open https://codepen.io/jnurthen/full/qBErmdB
The page has a link followed by 2 progress bars.
The first is Labelled Loading.... and the Valuetext is set to 50%
The second is also Labelled Loading but has no valuetext (or valuenow)

### Actual behavior:
The first progressbar is read as "Loading... Progress bar"

### Expected behavior:
It should be read as "Loading.... Progress bar 50%"

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.2.1

#### Windows version:
Windows 10 19013.1122

#### Name and version of other software in use when reproducing the issue:
Chrome 79.0.3945.88

**Comment by Brian1Gaff** [comment]
Has anyone noticed that some versions of the new edge beta have lost a lot 
of accessibility, but the later ones in the 80s seem to have it fixed? Don't 
know how much of that is Chrome related and how much is Microsoft related.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Adriani90** [comment]
This works correctly in Firefox 75.
@aleventhal do you have any idea why the value is not exposed in Crome or chromium based browsers here?

**Comment by ObjectInSpace** [comment]
This works for me. NVDA reads "progress bar Loading…50%" in Chrome 83.0.4103.61

**Comment by Adriani90** [comment]
Confirming this works also for me. Thanks for reporting. I am closing.
