### ISSUE TITLE
Switching to vocalizer from codefactory gives an error Unable to load vocalizer.

### ISSUE THREAD

**Issue by mdyer1** [nvaccess/nvda#10640]
### Steps to reproduce:

1.  Install codefactory synth addon.
2.  Bring up the synth selection Dialog with NVDA+CTRL+S.
3. Select vocalizer from the list and press enter.
### Actual behavior:
Dialog appears with the message could not load synth driver Vocalizer.
### Expected behavior:

NVDA should now be speaking with vocalizer rather than the lst synth used.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2019.2.1
#### Windows version:
windows 10 version 1909 with december c.u
#### Name and version of other software in use when reproducing the issue:
Codefactory 1.7 (Last stable version.)
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, but the elequence works fine.
Was unsure if I should file here or contact codefactory.
See attached log.
[output log.txt](https://github.com/nvaccess/nvda/files/3980647/output.log.txt)

**Comment by Adriani90** [comment]
This is definitely a code factory issue. Please try to contact them.

**Comment by Adriani90** [comment]
Try also to raise your question on the NVDA users mailing list at
https://nvda.groups.io/g/nvda

**Comment by Adriani90** [comment]
Thanks for reporting.

**Comment by mdyer1** [comment]
Hi,

 

I’ll have to bring it back up again as I hot no response there.  I was not sure if this was something to do with nvda directrely or not so thanks.

 

Matthew
