### ISSUE TITLE
Indeterminate Progress bars reported as "half-checked"

### ISSUE THREAD

**Issue by jnurthen** [nvaccess/nvda#10644]
### Steps to reproduce:
Open https://codepen.io/jnurthen/full/qBErmdB
The page has a link followed by 2 progress bars.
The first is Labelled Loading.... and the Valuetext is set to 50%
The second is also Labelled Loading but has no valuetext (or valuenow)

### Actual behavior:
NVDA reads the indeterminate progressbar as "half-checked":
Speech: `progress bar  half checked    0`
Braille: `⣏⣸⣹ prgbar 0 frame end`

### Expected behavior:
A better term than half-checked should be used for an indeterminate progress bar

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.2.1

#### Windows version:
Windows 10 19013.1122

#### Name and version of other software in use when reproducing the issue:
FF 71.0
Chrome 79.0.3945.88

**Comment by Adriani90** [comment]
@jnurthen do you mean by indeterminated that an user could only choose a value up to 50 for example although there are theoretically 100 values in the progress bar? Or what exactly should indeterminate mean for an user?

**Comment by brennanyoung** [comment]
half-checked sounds like the string that might be used to announce a "mixed state" checkbox.
Not ruling out an NVDA bug in how the valuetext attribute is interpreted, but this odd announcement might be speech synth related.

**Comment by jnurthen** [comment]
@Adriani90 sorry missed your question. The 2nd one is an indeterminate progress bar. What is meant is that the user (and the application) have no idea how long the task is going to take. They are often used when making a call to another system with a success or failure result. For example when submitting payment to a remote payment system.

**Comment by marie450** [comment]
Hi have experiment the same problem but only in Chrome 91. NVDA in both Firefox and Chrome read the progress bar just fine until I start putting some CSS on it. progress{background:green;} will cause "half-checked" to be annouce in Chrome, still work fine in Firefox.

**Comment by marie450** [comment]
The problem seem to not be in NVDA but with Chromium. JAWS give me the same result.

**Comment by feerrenrut** [comment]
One question that still needs to be answered here, how should an indeterminate progress bar be referred to?
I have updated the description with the current behavior:
- Speech: "progress bar  half checked    0"
- Braille: `⣏⣸⣹ prgbar 0 frame end`

**Comment by feerrenrut** [comment]
Suggested expected reporting
- Speech: `cycling progress bar` (explicitly changing the role label, dropping state and value)
- Braille: `cycprgbar frame end`

I'm unsure about cycling, it might be too cryptic. But it is much shorter than "indeterminate".

The exact word used can be altered later. Primarily I want to get agreement about overriding the role label in this case, and dropping state and value.

**Comment by XLTechie** [comment]
>  *  Speech: cycling progress bar (explicitly changing the role label, dropping state and value)

What about "repeating progress bar?"

There are very few English synonyms for "cycling" that are shorter than nine 
characters, and none of them as clear.
The only other one I can think of that makes more sense might be "Indefinite 
progress bar", which is my preference.

> I'm unsure about cycling, it might be too cryptic. But it is much shorter than "indeterminate".

Personally I agree that it would not be clear.

**Comment by feerrenrut** [comment]
Can you (or anyone) comment on this:
>Primarily I want to get agreement about overriding the role label in this case, and dropping state and value.

**Comment by feerrenrut** [comment]
NV Access is considering "busy indicator" dropping the value and the "half checked" state.
An indeterminate progress bar with a label of "loading" will be announced as: "Loading busy indicator"
