### ISSUE TITLE
NVDA stops reading during say all if blank lines are present in browse mode.

### ISSUE THREAD

**Issue by davidacm** [nvaccess/nvda#10657]
### Steps to reproduce:

1. Download [this html document](https://github.com/nvaccess/nvda/files/4014522/readingTest.zip) or any document containing blank lines.
2. Uncompress it.
3. Open the html document with Firefox, Chrome or IE.
4. Go to the beginning of the document.
5. Call the say all command.

Note: This issue doesn't happen on edge.
Tried with espeak synthesizer.

### Actual behavior:
NVDA will stop reading after some blank lines. In the [attached file](https://github.com/nvaccess/nvda/files/4014522/readingTest.zip), two lines after the first blank line.

### Expected behavior:
NVDA reads the entire document.
#### NVDA installed/portable/running from source:
NVDA installed.
#### NVDA version:
NVDA 2019.3 beta1.

#### Windows version:
windows 10 1903 64 bits.
#### Name and version of other software in use when reproducing the issue:
Chrome, firefox,internet explorer.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Works properly on NVDA 2019.2.1.

**Comment by Brian1Gaff** [comment]
Hi on trying this here with your file on an English windows 7 machine with 
espeak, I had no issues with say all stopping on the latest beta  in firefox 
or waterfox.

The plot thickens.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by davidacm** [comment]
Sorry. I tried it on a clean installation using a VM, but I forgot that an add-on was installed before. The issue is related with that add-on (speechHistory) so I will report it in the correct place.
I started NVDA without add-ons and not issues at all.
