### ISSUE TITLE
NVDA reads less information with the mouse in the Chromium Edge than it does in the EdgeHTML-based one

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#10650]
### Description:
In the new (Chromium-based) Microsoft Edge browser, NVDA reads less information with the mouse cursor than it does in the old/EdgeHTML-based one.

For example, when you point at a link for a video on the YouTube main page, in the old Edge NVDA reads something like this: "Ninja Gaiden (NES) James and Mike Mondays from „Cinemassacre“ 12 hours ago 37 minutes 80 657 views", which is very helpful - I can just point at the link for the video and read at once all the information that I need to know about the video and which is displayed for it below its thumbnail. The same information is read when I navigate to the link for the video via H (the link is also a heading). But if I point the same link in the new/Chromium-based Edge, I only get: "Ninja Gaiden (NES) James and Mike Mondays", which is only the text for the link/heading.

Another issue. NVDA does not "see" the "Actions menu" button located on the right of the link/title for each video on YouTube (e.g. for the suggested videos on its main page), if the Chromium-based Edge is used. But if the EdgeHTML-based Edge is used, NVDA sees those buttons. Another good example for a similar issue are the frequently visited sites located below the search field on the page for a new tab in the Chromium-based Edge. NVDA does read with arrow keys the image link, the text link and the button for each of them, but it does not read the button and the text link with the mouse - then for those elements it reports only their role (e.g. link, button).

In other cases, NVDA fails to read the text for a link, even though that text is clearly visible on the screen. A good example are the frequently visited sites located below the search field on the page for a new tab in the Chromium-based Edge. When traversed with arrow keys, NVDA reads the links text just fine, but not with the mouse - then it says only "link".

Another issue. NVDA fails to see the text in some web controls in the Chromium-based Edge. Examples are the entered text in the edit field on the Google Translate website, the buttons for language selection on the same site (the visible buttons for suggested languages above the fields), text in combo/list boxes, etc.

Those are only examples, but that is what I've discovered so far.

Can those issues be fixed? After all, they are not present in the EdgeHTML-based Microsoft Edge.

### Steps to reproduce:
1. Enable mouse tracking in NVDA.
2. Launch the EdgeHTML-based Microsoft Edge browser.
3. Go to the websites mentioned in the description above and point the mouse cursor over the problematic areas mentioned for those websites there.
4. Observe what NVDA reads.
5. Launch the Cromium-based Microsoft Edge browser.
6. Go to the websites mentioned in the description above and point the mouse cursor over the problematic areas mentioned for those websites there.
7. Observe what NVDA reads.
8. Compare your observations about what NVDA reads in the two browsers.

### Actual behavior:
NVDA provides less/inferior quantity and quality of information in the Chromium-based Microsoft Edge browser, than it does in the EdgeHTML-based one, when reading with the mouse.

### Expected behavior:
NVDA should provide the same quantity and quality of information in the Chromium-based Microsoft Edge browser, as it does in the EdgeHTML-based one, when reading with the mouse.

### System configuration
- Operating system: Windows 10 Pro version 1909 (build 18363.535), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-19460,d7229eff.
- EdgeHTML-based Microsoft Edge version: Microsoft Edge 44.18362.449.0, Microsoft EdgeHTML 18.18363, in bulgarian.
- Chromium-based Microsoft Edge version: 81.0.370.0 Canary, 64-bit, in bulgarian, UIA is enabled (default setting).
- Processor: Intel Core i5-9400F at 2.90GHz.
- RAM Memory: 16.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC892 at Intel Cannon Point PCH.

#### Does the issue still occur after restarting your PC?
Yes, it does.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, NVDA 2019.2.1. The behavior is the same.

**Comment by Brian1Gaff** [comment]
Which version of Edge Chrome though. I mentioned elsewhere that Microsoft 
had broken its accessibility in version 79.
 Lets hope they do not base the release version on that piece of rubbish.
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by k-kolev1985** [comment]
@Brian1Gaff As it was written in my report: Chromium-based Microsoft Edge version: 81.0.370.0 Canary, 64-bit, in bulgarian, UIA is enabled (default setting).

Furthermore, I've done testing of the same things in the same browser, but with Narrator and JAWS 2020. They behave more or less as it expected. So, it is possible, but NVDA is not doing it for some reason.

**Comment by gdata1** [comment]
I have this problem, too. even worse availability of microsoft edge extension store. Overall edge on chromiuam 81 is worse available with nvda than earlier versions.

**Comment by Adriani90** [comment]
@k-kolev1985 the behavior should be quite similar to Google Crome. Right?

**Comment by Adriani90** [comment]
@k-kolev1985 following questions to investigate further:
* Which unit is your mouse tracking set to? Character, word, paragraph?
* Could you please try to test this also with screen layout enabled in NVDA browse mode settings?
* Please enable UIA in Edge Chromium
1. Enter edge://flags in your address bar
2. Searh for UIA or Automation and activate that.
Is the issue still present after that?

**Comment by gdata1** [comment]
@Adriani90 I also have a problem with edge chromium. poor reading with your mouse. I tried to do what you said, but it didn't help. nvda poorly reads the contents of web pages. links, buttons, text. when my friend whose good eyesight injected the mouse cursor nvda often kept quiet and read with great delay. I tested on edge stable version 81 and edge Canary. nvda version alpha-20045,a335297e

**Comment by k-kolev1985** [comment]
@Adriani90 Here is my report:
1. Mouse echo resolution: Paragraph.
2. Doesn't matter if "Screen layout" in NVDA is enabled or not.
3. The option "Native UI Automation" seams no longer to be available in edge://flags in version 84.0.494.0 of Chromium Microsoft Edge.

**Comment by Adriani90** [comment]
Since the HTML based Edge has been discontinued for a while, we don't have any possibility to create a reliable test environment because this would be based on very old versions of Edge. I will close this issue as abandoned. Please feel free to open new issues specifically for single use cases in Chromium based Edge. Note that Edge has improved alot since this issue was submited.
