### ISSUE TITLE
NVDA

### ISSUE THREAD

**Issue by Poco1997** [nvaccess/nvda#10654]

**Comment by josephsl** [comment]
Huh?

**Comment by DrSooom** [comment]
@Poco1997: @josephsl is asking you to completely fill out the bug report draft and also to change the issue title. Thanks.

**Comment by Brian1Gaff** [comment]
I assumed it had been raised spuriously.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Adriani90** [comment]
Closing due to missing description.
