### ISSUE TITLE
IE11: braille abbreviations "⣏⣀⣹ rbtn" not begin on a new line, when screen layout is disabled

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#10664]
### Steps to reproduce:
1. Press NVDA+v to toggle Use screen layout off.
2. Open [testing page](https://www.nvaccess.org/download/).
3. Press r to move to next radio button.
#### Actual behavior:
braille:
$30 ⣏⣀⣹ rbtn
$30

#### Expected behavior:
⣏⣀⣹ rbtn
$30

#### NVDA Installed/portable/running from source:
portable.

#### NVDA version:
* [alpha-19184,d13635dc](https://ci.appveyor.com/api/buildjobs/ojh0s0xt4tguot41/artifacts/output/nvda_snapshot_alpha-19184,d13635dc.exe)

#### Windows version:
6.1.7601 service pack 1

#### Name and version of other software in use when reproducing the issue:
browser: Internet Explorer 11

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA?
2019.3Beta1

**Comment by lukaszgo1** [comment]
@surfer0627 What about with 2019.2.1? It would be good to establish if it is a regression or not.

**Comment by surfer0627** [comment]
@lukaszgo1
Thank you for the reply.

In 2019.2.1, NVDA works fine.
This case occurs in alpha-19184 and later.
Thanks.

**Comment by tapper82** [comment]
Use Firefox.

**Comment by Adriani90** [comment]
@tapper82 please stop using such comments. People are posting the issues for a reason and they might be aware of the alternatives.
Thanks.

**Comment by michaelDCurran** [comment]
@surfer0627  any chance you could provide the commit hash for the build you think it broke in? I.e. the letters and numbers after the sequencial build number in the snapshot filename.

**Comment by michaelDCurran** [comment]
Regression most probably caused by #10462
@leonardder  I think that adding alwaysReportName in the MSHTML vbufBackend may have caused this as in this scenario, the radio button is labeled with an HTML label association (I.e. label tag with a 'for' attribute pointing to the ID of the radio button). There is no real way you could have detected this case I know, but it would however cause the regression. 
I'm assuming you saw that this change fixed other more high-impact scenarios in IE 11?
Either way, I don't believe that this particular issue is high enough priority to worry about for 2020.1.

**Comment by surfer0627** [comment]
@michaelDCurran

Sorry, I'm not sure that I understand your message correctly.

After testing, this case occurs since alpha-19184,d13635dc.



@surfer0627 any chance you could provide the commit hash for the build you think it broke in? I.e. the letters and numbers after the sequencial build number in the snapshot filename.

**Comment by michaelDCurran** [comment]
Thanks. That is exactly what I needed.

**Comment by Adriani90** [comment]
This seems to affect only Internet Explorer. Support for IE ended completely in 2022 and the browser is automatically removed from machines that still have it after an Edge update in February 2023. I don't expect any further accessibility updates to IE or to IE mode in Edge. Closing as abandoned.
