### ISSUE TITLE
In Chromium-based browsers, NVDA exits focus mode when switching from and to full screen mode in video players

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#10671]
### Steps to reproduce:
1. Launch a Chromium-based browser (e.g. the new Microsoft Edge, Google Chrome, etc.).
2. Load a web page that contains a video to play via a web-based player (e.g. YouTube).
3. Force NVDA to go into focus mode (e.g. via NVDA+Space).
4. Use the web player's means to make the player to go into full screen mode.
5. NVDA will disable its focus mode and return to browse mode. Repeat step 3.
6. Use the web player's means to make the player to go out of full screen mode.
7. NVDA will disable its focus mode and return to browse mode.

### Actual behavior:
NVDA exits out of focus mode every time the web player is switched from or into full screen mode.

### Expected behavior:
NVDA should keep the focus mode enabled in such situations, considering that it was enabled manually by the user and it does so for browsers like Firefox and the old/EdgeHTML-based Microsoft Edge.

### System configuration
- Operating system: Windows 10 Pro version 1909 (build 18363.535), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-19460,d7229eff, in bulgarian.
- Processor: Intel Core i5-9400F at 2.90GHz.
- RAM Memory: 16.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC892 at Intel Cannon Point PCH.

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes - 2019.2.1 and the behavior is the same.

**Comment by Adriani90** [comment]
Closing in favor of #12983 which contains a bit more discussion, it seems I've missed this one and commented on the newer one.
