### ISSUE TITLE
NVDA 2019.3beta1  crashes in Thunderbird 

### ISSUE THREAD

**Issue by tapper82** [nvaccess/nvda#10676]
NVDA 2019.3beta1  crashes in Thunderbird 
### Steps to reproduce:
Open Thunderbird when in the tree view arrow up and down and it will crash.
### Expected behavior:
Should read out the name of the account you want to go to or the folder you want to read like inbox or outbox.
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
NVDA 2019.3beta1  
#### Windows version:
Windows 10 64
#### Name and version of other software in use when reproducing the issue:
Name
Thunderbird
Version
74.0a1
#### Have you tried any other versions of NVDA? If so, please report their behaviors.

NVDA 2019.2 installed to my harddrive works as it should.

**Comment by leonardder** [comment]
Do you also experience this with stable version of Thunderbird?

**Comment by Brian1Gaff** [comment]
Have you tried it with no add ons loaded in?
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by tapper82** [comment]
Hi I still get the crashes in tb 72 and 73 and with no addins loaded.

**Comment by Adriani90** [comment]
@tapper82 what kind of version are these? Thunderbirt last stable version is 68.4 to my knowledge. In this version I cannot reproduce this crash.

**Comment by tapper82** [comment]
They are betas I downloaded them from the FTP server. I will have a go with 68.4

**Comment by Adriani90** [comment]
@tapper82 could you try please with NVDA 2019.3 Beta 2 and Thunderbird 68? Thanks.

**Comment by Adriani90** [comment]
I suggest to wait until at least Thunderbird 72 is released since this was the first beta version where this issue seems to be reproducible. On the current final release the issue is not reproducible according to my tests.

**Comment by tapper82** [comment]
Hi this is fixt with NVDA b3 and TB74 Thanks for looking at this for me. BTW NVDA B3 is running full time on my system now and going grate.
