### ISSUE TITLE
B and F keys are working as Enter Key for keyboard navigation when i install NVDA

### ISSUE THREAD

**Issue by Shruthicsjava** [nvaccess/nvda#10673]

**Comment by DrSooom** [comment]
@Shruthicsjava: Please completely fill out the bug report draft. Thanks.

**Comment by Brian1Gaff** [comment]
Occasionally this  weird blank creation does seem to happen. Not sure why, 
but I've had it happen to me. What I now tend to do is  not create it 
straight away, but grab the wanted template and paste it into notepad, 
exit the creation without saving and then fill it out off line removing #s 
etc and then go back in and  remove the template and then paste in my pre 
prepared one. This seems to stop the issue where the navigation goes wild 
while  trying to figure out where to type in. Just saying.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by DrSooom** [comment]
@Brian1Gaff: I guess it's time to add your suggestion, which is the best way to handle this, to all issue templates directly as a hint at line 2 (= after the html comment area starts). @feerrenrut: Any thoughts?

**Comment by Adriani90** [comment]
Maybe it depends on which browser you are. With firefox, Chrome, Edge and Internet explorer the template works just great and there are no weired navigation issues. Anyway, this is not the issue here. Please fill another one if you have specific problems with the template.

**Comment by DrSooom** [comment]
@Adriani90: The GitHub features "Directly mention a user or team" and "Reference an issue or pull request" are interactive on the multiline textfield – after entering `@` or `#`. This behavior could irritate some users.

**Comment by Adriani90** [comment]
You can skip that by pressing escape.

**Comment by Adriani90** [comment]
We do not have any details on this issue and it is not possible to reproduce. Please reopen a new one and fill the issue template correctly. I am closing this for now. Thanks.
