### ISSUE TITLE
No speech after opening Device Manager

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#10700]
With NVDA 2019.3 beta 2 and alpha versions speech stops when opening Device Manager.
### Steps to reproduce:
1. Press Windows key to open Search.
2. Write "device manager" and press Enter
### Actual behavior:
NVDA loses speech.  Speech returns when alt-tabbing out of Device Manager and stops again when re-entering Device Manager.
### Expected behavior:
NVDA should continue to provide speech output.
#### NVDA installed/portable/running from source:
NVDA running by selecting Continue from Installation program
#### NVDA version:
2019.3 beta 2 (also occurs with a portable alpha build of 2019.3).
#### Windows version:
Version 10 Home 64 bit, 1903
#### Name and version of other software in use when reproducing the issue:
Nil
#### Other information about your system:
Microsoft Office 365 and various audio software installed but results do not vary when running or not.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes.  NVDA 2019.2.1 works fine.
Log file attached, but seems not to shed any light according to my limited expertise.
[NVDA-LOG-DEVICE-MANAGER.LOG](https://github.com/nvaccess/nvda/files/4084371/NVDA-LOG-DEVICE-MANAGER.LOG)

**Comment by andrew-l-d** [comment]
I have since created a portable version of NVDA 2019.3 beta 2.  Behaviour is the same - no speech in Device Manager.

**Comment by Brian1Gaff** [comment]
Just for the record, there are no issues in Windows 7.
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by andrew-l-d** [comment]
I inadvertently closed this issue four days ago, but did not intend to do so.

Andrew

**Comment by lukaszgo1** [comment]
@andrew-l-d  Have you tested this with portable 2019.2.1, or only with a installed version? I believe portable/temporary versions of NVDA were never able to access device manager unfortunately.

**Comment by Adriani90** [comment]
This works just fine if you start your portable version as administrator. Is the same like for protected screens. However, solving this issue depends on external changes from Microsoft. There is nothing we can do about that due to system priviledges. Thus, if you need taht, start your portable copy or the NVDA installation as an administrator. Aftar that it works according to my tests. Closing as works for me.
If it's still not working, please comment on it and we can reopen it. Thanks.

**Comment by andrew-l-d** [comment]
No, I did not test with NVDA 2019.2.1 as a portable.  Apologies for the inconvenience.

Andrew
