### ISSUE TITLE
feature_request: When opening or closing the NVDA settings interface, remember to browse where the cursor is

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#10701]
hello
Currently, when using NVDA settings, after opening or closing the NVDA settings interface, the cursor position will not be remembered.
### Is your feature request related to a problem? Please describe.
You can track the cursor when the user browses the NVDA settings interface, so that the user can continue to browse the list of NVDA settings from the place they are browsing the next time they open the NVDA settings.
### Describe the solution you'd like
none
### Describe alternatives you've considered
none
### Additional context
test1:
NVDA Settings: General (normal configuration
General', '1 of 14']
Speech', '2 of 14']
Braille', '3 of 14']
test2:
NVDA Settings: General (normal configuration
Speech', '2 of 14']
Braille', '3 of 14']
thanks

**Comment by Adriani90** [comment]
I don't know any software which has this feature. Actually the list of categories is quite short. Why do you need this feature? It is actually not very trivial to implement due to wx python restrictions.
cc: @josephsl what do you think?

**Comment by Adriani90** [comment]
Closing due to the restrictions mentioned and due to the fact that there are many possibilities in NVDA to access settings very fast (i.e. ctrl+nvda+...; or single key strokes for most settings).
