### ISSUE TITLE
Access to edit area of Biblos word processor broken with latest alpha versionse 

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#10704]
### Steps to reproduce:
Open a file using Biblos (epub for example) and try to review it using the arrows.
### Actual behavior:
Thoug the area is announced as an edit field, nothing is spoken and nothing displayed on the braille terminal.
### Expected behavior:
We should be able to review the text like in any text editor.
#### NVDA installed/portable/running from source:
NVDA installed
#### NVDA version:
alpha-19532,e1e4a551
#### Windows version:
Windows 10Ver1909 (64-bit) build 18363.592
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Works fine with 2019.3 beta 2

**Comment by lukaszgo1** [comment]
I can reproduce this on Windows 7 with latest Alpha. cc @leonardder  as most of the commits which are on master but not on beta are yours. This should be marked as a regression in any case.

**Comment by lukaszgo1** [comment]
I can not reproduce this with latest Alpha running as a portable. @MichelSuch Can you still reproduce this?

**Comment by MichelSuch** [comment]
Some more info on this problem:
When opening Biblos (here Biblos 5.30) the log contains following errors (see attached file):
[NVDA.log](https://github.com/nvaccess/nvda/files/4146779/NVDA.log)

**Comment by lukaszgo1** [comment]
cc @leonardder Most of the latest displaymodel changes are yours.

**Comment by leonardder** [comment]
@MichelSuch what happens if you maximize the window?
