### ISSUE TITLE
NVDA2019.3beta2 - Cannot close settings window on Vision panel

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#10705]
### Steps to reproduce:

* Open the Vision panel in the settings window
* Check the "Enable Highlighting" checkbox
* Click "Apply" button (without closing the window)
* Uncheck the "Enable Highlighting" checkbox
* Press "Escape" to cancel last action (i.e. unchecking the checkbox)

### Actual behavior:

NVDA error sound is heard and the settings Window does not close. There is then no way to close it unless restarting NVDA.

Moreover, we are then in an unexpected state where you can open many instances of the setting windows, what is usually forbidden.

The error is the following:

> IO - inputCore.InputManager.executeGesture (15:25:06.255) - winInputHook (2852):
> Input: kb(desktop):escape
> DEBUG - gui.settingsDialogs.SettingsDialog._setInstanceDestroyedState (15:25:06.255) - MainThread (11732):
> Setting state to destroyed for instance: <gui.settingsDialogs.NVDASettingsDialog object at 0x036B88A0>
> Current _instances {<gui.settingsDialogs.NVDASettingsDialog object at 0x036B88A0>: 0}
> DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (15:25:06.271) - MainThread (11732):
> loading vision screenCurtain
> DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (15:25:06.271) - MainThread (11732):
> Loaded settings for ScreenCurtainSettings
> DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (15:25:06.271) - MainThread (11732):
> loading vision NVDAHighlighter
> DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (15:25:06.271) - MainThread (11732):
> Loaded settings for NVDAHighlighterSettings
> ERROR - unhandled exception (15:25:06.271) - MainThread (11732):
> Traceback (most recent call last):
>   File "gui\settingsDialogs.pyc", line 633, in onCancel
>   File "gui\settingsDialogs.pyc", line 3344, in onDiscard
>   File "gui\settingsDialogs.pyc", line 3298, in safeInitProviders
> AttributeError: __enter__

### Expected behavior:

Settings window should be closed correctly

### Additional information

There are other ways to reproduce the issue, e.g.:

* Clicking on "Cancel" instead of pressing "Escape"
* Closing the settings window with "OK" after checking the checkbox and re-open it to make the cancelled uncheck.
* Use the Screen curtain checkbox instead of the Highlighter one.

### Analysis

The error occurs in settingsDialogs.py file on the following line:

`with VisionProviderStateControl(self, provider) as control:`

Indeed the class VisionProviderStateControl does not implement a context manager (__enter__ and __exit__ methods), and thus, cannot be used with the "with" keyword. The goal seemed to avoid any possible exception. If this is the case, a try/except would be more suitable. Moreover, we should guarantee that the "success" variable is assigned even if an exception occurs.

I am not totally sure how to fix the issue so I did not provide a PR to fix it.

#### NVDA installed/portable/running from source:

Installed and portable

#### NVDA version:

NVDA 2019.3beta2

#### Windows version:

Win 10 1809

#### Name and version of other software in use when reproducing the issue:

N/A

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

**Comment by CyrilleB79** [comment]
Cc @feerrenrut

**Comment by Adriani90** [comment]
Closing as fixed in #10722.
