### ISSUE TITLE
Screen curtain cannot be enabled permanently when the warning dialog is disabled

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#10717]
### Steps to reproduce:
1. Choose not show a warning dialog when enabling screen curtain.
2. Press twice a keystroke to toggle screen curtain.
3. See the NVDA message announcing that screen curtain has being enabled.
4. Restart NVDA.

### Actual behavior:
Screen curtain is not enabled.

### Expected behavior:
Screen curtain should be enabled (if configuration is set to be saved on exit).

#### NVDA installed/portable/running from source:

Installed, portable or running from source.

#### NVDA version:
2019.3beta2.

#### Windows version:
Windows 10 (tested in several versions).

#### Name and version of other software in use when reproducing the issue:
N/A

#### Other information about your system:
N/A.

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2019.3beta1: screen curtain is properly enabled.

**Comment by CyrilleB79** [comment]
Thanks to have opened this issue following the discussion on nvda-devel mailing list.

As a reminder, the regression was introduced in f194afaec02a3465ceb769ee88543ea337c6eb9e.

And the nvda-devel thread is [here](https://groups.io/g/nvda-devel/topic/70052725#44796).

**Comment by nvdaes** [comment]
Thanks Cyrille. There is also a [thread in an NVDA's spanish mailing list about screen curtain in NVDA 2019.3beta2](https://nvdaes.groups.io/g/lista/topic/69987451).

**Comment by feerrenrut** [comment]
Fixed in commit 767640b via PR #10718
