### ISSUE TITLE
One link in user guide is http only but changed to https in a previous pull request

### ISSUE THREAD

**Issue by larry801** [nvaccess/nvda#10725]
### Steps to reproduce:
Go to this link https://cldr.unicode.org/ in user guide
### Actual behavior:
Cannot go to CLDR database
### Expected behavior:
On CLDR - Unicode Common Locale Data Repository page

**Comment by dingpengyu** [comment]
cc @feerrenrut

**Comment by feerrenrut** [comment]
Fixed with commit  cd9c532 via #10726
