### ISSUE TITLE
Convert control types constants into enums

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#10732]
This issue stemmed from a comment in #10703

As a follow up, do the same for the rest of the constants in control types, and ensure that all of NVDA uses the enum versions and officially deprecate (and give a date of removal for) the module level constants.

While doing this, add a deprecation comment to SpeechReason constants also.

_Originally posted by @feerrenrut in https://github.com/nvaccess/nvda/pull/10703/review_comment/create_

**Comment by feerrenrut** [comment]
Closed with PR #10703 via commit f674567

**Comment by feerrenrut** [comment]
Oops, reading the description of this issue, this should remain open. This is work in extension of #10703 and should be delivered to 2020.1

**Comment by leonardder** [comment]
I think there are two implementation strategies:

1. Define the enums and after that, do a setattr on the module to add the old constants
2. Define a __getattr__ at the module level that looks up the constants from the enums.

Performance wise, I'd do the former, but if you want to raise deprecation warnings, the latter is probably more effective.

Have you also considered constants in oleacc.py? I'd leave them as is.

**Comment by leonardder** [comment]
An additional thought... May be we should advertise de labels using the enum itself?

```
class Role(enum.IntEnum):
	UNKNOWN = 0
	@property
	def label(self):
		return controlTypes.roleLabels[self]
```

**Comment by feerrenrut** [comment]
Given the possibility for breaking compatibility, I'm pushing this back to 2021.1

**Comment by feerrenrut** [comment]
Rather than do this all in one go, instead, similar to "Use enum for speech reason #10703" first we'll do this in a backwards compatible way so that add-on authors have a transitionary period. Later, probably 2022.1 we'll remove the deprecated aspects.

**Comment by seanbudd** [comment]
@feerrenrut - would the backwards compatible work be part of deprecations/2021.1 or should I start on this separately?

**Comment by feerrenrut** [comment]
@seanbudd the deprecation warnings don't necessarily need to be in this release. I think we should label this for 2022.1. The initial work to deprecate and provide a new alternative can be done after we get to beta for 2021.1.
