### ISSUE TITLE
"&"symbols in list boxes are misidentified

### ISSUE THREAD

**Issue by gyouzazuoyg** [nvaccess/nvda#10747]
### Steps to reproduce:
Find a list box control with "&" symbol.
For example: right-click a file in Windows --> click "Properties" --> "Security" tab --> in "Permissions for SYSTEM" list box

### Actual behavior:
"Read & execute" is misidentified as “Read  execute”.
I guess it's because "& " is identified as a shortcut key.

### Expected behavior:
& symbol should be read out as "and" just like in a .txt file.

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2019.2.1
Downloaded from the official website.

#### Windows version:
Win10
Version	10.0.18362 Build 18362

#### Name and version of other software in use when reproducing the issue:
Windows file properties.

#### Other information about your system:
x64

#### Does the issue still occur after restarting your PC?
Yes

**Comment by Adriani90** [comment]
This depends on which punctuation level you set NVDA to speak punctuation signs. If you set the punctuation level to all or most, sign will be read. This can also depend on the speech synthesizer you are using. eSpeak works for example as expected. If it is still not working, you can add the "&" sign to another symbol level manually, so NVDA speaks it in the symbol level you havwe set NVDA to.

Closing as works for me.
