### ISSUE TITLE
Feature request: Unicode normalisation

### ISSUE THREAD

**Issue by ghost** [nvaccess/nvda#10745]
### Is your feature request related to a problem? Please describe.
Some aspects of Twitter are not read correctly when users are using Unicode characters to simulate fonts. e.g. https://twitter.com/FakeUnicode/status/1223029914611240961

### Describe the solution you'd like
Unicode normalisation / decomposition may help make these tweets more readable

### Describe alternatives you've considered
It would be better for Twitter to support alt text on all tweets.

### Additional context
I am not a day to day NVDA user, I just see lots of replies to these kinds of tweets saying 'these Tweets aren't accessible to screenreader users'

**Comment by DrSooom** [comment]
@voltagex: You are primary talking about Text-to-Speech and not about braille output, correct?

**Comment by voltagex** [comment]
To be honest, I had not even considered Braille output.

**Comment by mayson199514** [comment]
Hello, I have actually seen this issue pop up on discords end as well! ware it happens most is when adding a user or if someone adds you from a discord server. I hope this issue can be solved soon. I actually have to quit nvda and switch to jaws temporarily just so I can see who I'm actually adding or chatting. with. witch is very inconvenient.

**Comment by Adriani90** [comment]
cc: @jcsteh, @derekriemer

**Comment by thetechguy-cpu** [comment]
Experiencing the same as @mayson199514

**Comment by lukaszgo1** [comment]
How exactly is it resolved in  JAWS?

**Comment by Qchristensen** [comment]
A user pointed me to https://yaytext.com/ which is a site specially made to abuse unicode in this way.

**Comment by Adriani90** [comment]
This is fied now in NVDA 2024.3 Beta, you have to enable normalization bmanually though.

Closing as works for me.
