### ISSUE TITLE
NVDA and Microsoft Chinese Input 倉頡

### ISSUE THREAD

**Issue by sine-w** [nvaccess/nvda#10742]
### Steps to reproduce:
1. activate the  Microsoft Chinese Input 微軟倉頡 under Windows 10
2. type any Chinese that will offer more than one options, e.g. type大月 will offer 1有 and 2冇
3. if chose 2.冇, NVDA did not read this selected text, but read 有
 
### Actual behavior:
NVDA did not correctly speak the chosen text option

### Expected behavior:
if based on the above example, I chose 2 nvda should speak 冇 

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2019.2.1
#### Windows version:
10 1909
#### Name and version of other software in use when reproducing the issue:
微軟倉頡 that is come with the Windows 10
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

**Comment by Adriani90** [comment]
Could you please test this with NVDA 2019.3 Beta 4?
You can find and download the beta and Alpha versions here:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by lstar4ever** [comment]
Hi,
I tested the 2019.3beta 4.
What I found is the problem remain the same.

Test situation
Notepad++
on both 2019.2.1 and 19.3 beta4
there seemed to be have no problem.

Firefox address bar
When typing in the address bar, both version of nvda do come across the problem.

Forms in online forum loaded in Firefox
When typing text into the text field displayed in one of the online forum, on both version of nvda, the problem do exist.

**Comment by Adriani90** [comment]
@sine-w can you please test with the last NVDA alpha version? Is this issue still occuring?

cc: @cary-rowen 

You can download the last NVDA alpha for testing purposes at this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by cary-rowen** [comment]
I don't use a Traditional Chinese OS, nor do I use the input methods mentioned, and may not be able to provide more helpful information.

**Comment by sine-w** [comment]
Hello,
Woo this is a very old post which I have created long long time ago which I had already forgotten this.

I have just tested alpha-28111,36a5eae2
And is no longer witnessing this problem.
Thank you.
