### ISSUE TITLE
Libre Office Calc 6.4: NVDA reports "has formula" on each cell regardless if there is a formula

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#10759]
### Steps to reproduce:
1. Open NVDA
2. Open an empty table in Libre Office Calc 6.4
3. navigate with arrow keys

### Actual behavior:
NVDA reports "has formula" on every cell.

### Expected behavior:
NVDA should report "has formula" only when there is one formula in the cell.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.3 RC2

#### Windows version:
Windows 10 1909 update

#### Name and version of other software in use when reproducing the issue:
Libre Office Calc 6.4.

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
In 2019.1.1 I didn't see this issue.

**Comment by Adriani90** [comment]
I tested with addons disabled and I also ran the COM registration fixing tool. No differences.

**Comment by lukaszgo1** [comment]
@Adriani90 Just to make sure, could you please test with [this try build](https://ci.appveyor.com/api/buildjobs/c44tnosg104d373r/artifacts/output%2Fnvda_snapshot_pr10962-19929%2C0dfb2680.exe) and confirm that this is fixed for you?

**Comment by Adriani90** [comment]
I have not access on the machine with LO, I will test as soon as I am back home. Sorry for this...

**Comment by Adriani90** [comment]
@lukaszgo1 this try build works as expected. The issue is fixed. Thanks.

**Comment by Adriani90** [comment]
Fixed in Libre Office 6.4.4.2. Closing as works for me.
