### ISSUE TITLE
Outlook 2010: Suppress Duplicate Searching Announcements

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10753]
### Steps to reproduce:

1. Open Outlook 2010, and navigate to the "Search" box displayed within the main window

2. Type a search term into the edit field, and hit enter

3. Perform a tab and shift + tab to navigate back to the Search field

### Actual behavior:

When focus is placed back within the edit field, NVDA announces "searching... searching... searching..."

### Expected behavior:

NVDA should only announce "searching" once when focus is placed on this field

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.2.1

#### Windows version:

Windows 7 X64

**Comment by DrSooom** [comment]
I can't reproduce it with Microsoft® Outlook® 2010 (14.0.7236.5000) SP2 MSO (14.0.7237.5000) and NVDA 2019.2.1 on Win7x64.

Two points: You can access the search field with CTRL+E or F6/Shift+F6 and you don't have to press Enter after you've typed the text into the search field, just press Shift+F6 once or Shift+Tab twice (if e-mail preview isn't enabled).

**Comment by Adriani90** [comment]
This is not reproducible with NVDA 2023.1 and Office 2016 or Office 365. Given the missing updates from the initial author and the MS Office support for Office 2010 ended completely in 2020, I am closing this as abandoned. I don't expect any further updates regarding to accessibility for that version.
Note: Office 2013 reaches end of live in April 2023, so please open a new issue in case you still have it, but for Office versions newer than 2013.
