### ISSUE TITLE
Visual Studio Memory Analyzer table is not read properly

### ISSUE THREAD

**Issue by mpeyrotc** [nvaccess/nvda#10761]
### Steps to reproduce:

1. Launch Visual Studio application with ".NET Desktop Development" and "Desktop Development with C++" workloads installed.
2. Clone this repository: "https://github.com/ericmitt/ScenarioDay" 
3. Build and run (Press F5) "PlayMP3" solution.
4. Move to "Diagnostic Tools" window present at the right side of the screen.
5. Move to "Memory Usage" tab item and enable "Enable Snapshots to begin Heap Profiling" link.
6. Hit "Take a snapshot" button and select any of the link under "Allocations" column. Heap View details should appear on the left.
5. Start NVDA.

Note: this can be accomplished with any native (C++) or managed (C#) application you debug as long as there are object being allocated in the heap.

### Actual behavior:

NVDA does not read column information about table when it gets focused for the first time. It does not read 'column header' keyword along with it's column number as column 1 of 4 like that or the total number of columns and rows. While reading the table rows, nothing is said by the tool.

### Expected behavior:

When the table gets focused for the first time NVDA should tell the user the number of columns present in the table. When moving along the rows, it should also say the information located in the row and while going through each column also say the column name before the column value. Similar to what Windows Narrator does.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

Version 2019.2.1

#### Windows version:

Windows 10 Enterprise (Internal build for testing)

#### Name and version of other software in use when reproducing the issue:

Visual Studio 2019 version 16.5 (all skews and released previews)

#### Other information about your system:

None.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No. Just the latest.

**Comment by DrSooom** [comment]
@mpeyrotc: Please start NVDA before doing all the other stuff and report its result. Thanks.

**Comment by Adriani90** [comment]
@mpeyrotc how is this now with NVDA 2020.1 and VS 2019 16.5?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years. I am closing this issue as abandoned. If you still have this issue with NvDA 2023.1, please comment and we can reopen.
