### ISSUE TITLE
Navigating by spelling error not working in multiline HTML text fields

### ISSUE THREAD

**Issue by Luke-Robinett** [nvaccess/nvda#10763]
using the W key in browse mode in a multiline HTML text field, NVDA reports "Not supported in this document" even when the text field contains misspelled words.
I didn't see this reported elsewhere but feel free to direct me to the open issue and close this one if it has already been reported. Thanks.

**Comment by Adriani90** [comment]
This is a duplicate of #7320. Closing as duplicate. Thanks for reporting.
