### ISSUE TITLE
translations not included in nvda 2019.3

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#10773]
### Steps to reproduce:
use version 2019.3 in Brazilian Portuguese.
Open the view tab.
walk with a tab and note that:
### Actual behavior:
the options below are not translated:
Always show a warning when loading Screen Curtain  Alt+s
Play sound when toggling Screen Curtain  Alt+p

### Expected behavior:
these options in nvda alfa 19633 are translated, i hope that in the stable version these options were translated as well.
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
2019.3
#### Windows version:
10 1909 18363.
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

**Comment by feerrenrut** [comment]
Apologies for this mistake. NVDA 2019.3.1 has now been released (and the post updated). This new release should fix the issues with the translations. 

https://www.nvaccess.org/post/nvda-2019-3-released/

Thank you for letting us know.
