### ISSUE TITLE
Anchor link jump menu not working in Chrome

### ISSUE THREAD

**Issue by kbeck303** [nvaccess/nvda#10794]
### Steps to reproduce:
1. Turn NVDA on
2. Open Chrome
3. Go to https://codepen.io/kbeck303/full/WNvwWQb
4. Tab to the "Skip to main content" link
5. Press ENTER, Focus does NOT move to the anchor destination.
6. Press TAB, it brings you to "Link One"

7. Turn NVDA Off
8. Open Chrome
9. Go to https://codepen.io/kbeck303/full/WNvwWQb
10. Tab to the "Skip to main content" link
11. Press ENTER, Focus moves to the anchor destination
12. Press TAB, it brings you to "Body Link One"

### Actual behavior:
1. Turn NVDA on
2. Open Chrome
3. Go to https://codepen.io/kbeck303/full/WNvwWQb
4. Tab to the "Skip to main content" link
5. Press ENTER, Focus does NOT move to the anchor destination.
6. Press TAB, it brings you to "Link One"

### Expected behavior:
1. Tab to the "Skip to main content" link
2. Press ENTER, Focus moves to the anchor destination
3. Press TAB, it brings you to "Body Link One"

#### NVDA installed/portable/running from source:
Downloaded nvda_2019.3.1.exe and installed it

#### NVDA version:
nvda_2019.3.1

#### Windows version:
Windows 8.1, Version 6.3

#### Name and version of other software in use when reproducing the issue:
Does work with Firefox 68.5 

Does *NOT* work with Chrome 79.0.89

#### Does the issue still occur after restarting your PC?
Yes, this issue still occurs after restart

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, this was not tested in older versions

**Comment by Brian1Gaff** [comment]
I've seen this for  a long time in nvda. I thought it was differences in 
coding of the site.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by Adriani90** [comment]
This works as expected now in NVDA Version: alpha-20548,e1f3ba99 and Chrome 84. Closing as works for me. Please comment on this if you are still having this issue and we can reopen.
