### ISSUE TITLE
Run COM Registration fixing tool Dialog can't be closed by ALT+F4 or ESC

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#10799]
### Path:
NVDA menu » Tools » Run COM Registration fixing tool
### Actual behavior:
Quotes from @Qchristensen [here in issue #10791](https://github.com/nvaccess/nvda/issues/10791#issuecomment-588047238):
> The only other dialog I couldn't close with alt+f4 was the "Run COM Registration fixing tool", which can't be closed with alt+f4, or escape, you need to activate either the Yes or No button […]

The question the dialog proposes is:
>You are about to run the COM Registration Fixing tool. This tool will try to fix common system problems that stop NVDA from being able to access content in many programs including Firefox and Internet Explorer. This tool must make changes to the System registry and therefore requires administrative access. Are you sure you wish to proceed?"

It requires an explicit yes / no answer.

### Expected behavior:
> […] (ideally, ALT+F4, and escape, should both activate the no button on that dialog).

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA 2019.3.1
#### Windows version:
I guess Win7 to Win10-2004
#### Does the issue still occur after restarting your PC?
Not tested.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by CyrilleB79** [comment]
Note that it is not a dialog but just a warning message box with 'Yes' and 'No' buttons.
If something is done on such message, it should also apply to the message appearing when pressing the button "Use currently saved settings on the logon and other secure screens (requires administrator privileges)" in general settings if you have add-ons in your configuration.
Also "Reset to factory defaults" button pressing in input gesture dialog opens such a warning message box.
Maybe some other message box are in the same situation.

**Comment by DrSooom** [comment]
@CyrilleB79: You're right. Sadly I haven't the time to check all that out at the moment.

@Qchristensen: It would be nice if you can take a look on this too. Feel free to edit the issue title.

**Comment by OzancanKaratas** [comment]
Is it necessary? “No” button already closes the dialog.

**Comment by feerrenrut** [comment]
There are certainly tweaks that COULD be made to that dialog. Though I don't think this should happen unless it is part of an overall move to improve the consistency and UI language of all of NVDA. Currently the dialog wants an explicit answer, alt+F4 or escape could be considered ambiguous. I'll mark this as low priority, perhaps it could be included in a future project looking at NVDA's GUI.
