### ISSUE TITLE
scons build error

### ISSUE THREAD

**Issue by SeanTolstoyevski** [nvaccess/nvda#10809]
Hi, I'm trying to build NVDA with Visual Studio 2019.

### Steps to reproduce:
1. `git clone --depth 1 --branch master --recurse https://github.com/nvaccess/nvda`
2. `cd nvda`
3. `scons source`

Output of the error:
```
C: \ projects \ nvda> scons source
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
interfaceAction (["source \ comInterfaces \ SpeechLib.py", "source \ comInterfaces \ __ pycache __ \ SpeechLib.cpython-37.pyc"], ["source \ comInterfaces \ __ init__.py"])
scons: *** [source \ comInterfaces \ SpeechLib.py] Library not registered
scons: building terminated because of errors.
```

### Actual behavior:
Scons returns an error.
### Expected behavior:
NVDA must be compiled successfully
#### NVDA installed/portable/running from source:
source
#### NVDA version:
https://github.com/nvaccess/nvda/commit/2c4caa62068feb03624670e35abd482ce91c48be
21.2.2020

#### Windows version:
Using Windows version 10.0.18358 workstation

#### Name and version of other software in use when reproducing the issue:
VS2019

#### Does the issue still occur after restarting your PC?
yes

**Comment by lukaszgo1** [comment]
What version of Python you have installed? Currently building with 3.7.6 is broken.

**Comment by SeanTolstoyevski** [comment]
3.7.5 32 bit

iPhone’umdan gönderildi

Łukasz Golonka <notifications@github.com> şunları yazdı (21 Şub 2020 16:27):

﻿

What version of Python you have installed? Currently building with 3.7.6 is broken.

**Comment by lukaszgo1** [comment]
Could you please clone  the repo with the command given in the readme and try again ?

**Comment by SeanTolstoyevski** [comment]
Hello, this is my fault.
I thought I would check one of the components. I had to check them all.

Excuse me for the inconvenience.
