### ISSUE TITLE
Speak typed word not correctly reading edited word in 2019.3.1

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#10808]
### Steps to reproduce:

In an edit field or document (eg a blank word document), type most of a word, backspace some letters, type the rest of a different word and press space, with speak typed words on, NVDA only reads the letters typed after backspace was pressed.  EG:
1. Open a blank document in Word (or notepad)
2. Without pressing space at the end, type the word step
3. Press backspace twice to remove the p and the e
4. Type ride then space.

### Actual behavior:

NVDA reads "ride".

### Expected behavior:

NVDA should read the word, "stride".

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.3.1
#### Windows version:
Windows 10 v1903 build 18362.388
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2019.2.1 - NVDA reads "stride" correctly

Note, as a work around, having just typed a word, and pressed space, the quickest way to re-read the word is by pressing numpad 4 (Laptop: NVDA+control+leftArrow) to have NVDA read the previous word with the review cursor.  This doesn't move the focus so assuming the word is correct, you can simply keep typing.  Otherwise, control+left arrow moves the caret to the previous word and reads it (but in that case you'll need to press control+right arrow to move back again).

**Comment by surfer0627** [comment]
Is this a related issue for pr [#8110](https://github.com/nvaccess/nvda/pull/8110)?

**Comment by Qchristensen** [comment]
Yes, therefore this is a duplicate of https://github.com/nvaccess/nvda/issues/8065  I'll close it as such, thanks!
