### ISSUE TITLE
Add a visual studio installer configuration export to the NVDA repository

### ISSUE THREAD

**Issue by SeanTolstoyevski** [nvaccess/nvda#10811]
Hello,

I recommend adding the config file exported from Visual Studio Installer to NVDA's main repo.

Using VS Installer is relatively difficult. There are many options.

It is possible to install components with the option to import in VS Installer.
This will save us a lot of trouble.

I have been dealing with the components in the installation for 2 days. I just solved the problem.

I hope you agree

config file content link: https://paste.ubuntu.com/p/zR5VS9QnQw/

**Comment by leonardder** [comment]
Could you elaborate on what made it so dificult for you to install Visual Studio as noted in the readme? May be we need to update the docs?

**Comment by SeanTolstoyevski** [comment]
It takes a lot of time.
The labels of the components are very long, which is tiring. It takes 4-5 seconds to find out if the components are checked or uncheck . Sometimes I get confused as I navigate through the components. Because their labels are very similar.

Electron applications are slower in my opinion.

I thought one of the MSVC components would be installed. I constantly looked for problems on my computer.
I didn't know we had to check them all.

I think the import option will be very efficient for those who find VS Installer complicated.
In this way, we do not need to look for components. They come checked and all we have to do is complete the setup.

Another issue is that you can add to README that all MSVC components should be checked.
But this should also be left to the user as an option.

**Comment by CyrilleB79** [comment]
👍 

Agree with @SeanTolstoyevski 

In the readme there are some one-line item that match many items in the installer with various version number. It is not clear that we need to check them all.

Moreover, in the VS installer the items are translated in the Windows UI language, what makes more difficult to check the name of the items.

**Comment by leonardder** [comment]
SeanTolstoyevski: Would you be able to open a pr with this file? I think it would be suitable to go in the extras folder. It makes it easier to comment on it.

**Comment by leonardder** [comment]
I actually think this should be sufficient. Note that some components are mandatory and will be added nevertheless.

```
{
  "version": "1.0",
  "components": [
    "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
    "Microsoft.VisualStudio.Component.Windows10SDK.18362",
    "Microsoft.VisualStudio.Component.VC.Redist.14.Latest",
    "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core",
    "Microsoft.VisualStudio.Component.VC.ATL",
    "Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset",
    "Microsoft.VisualStudio.Component.VC.Llvm.Clang",
    "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Llvm.Clang",
    "Microsoft.VisualStudio.Workload.NativeDesktop",
    "Microsoft.VisualStudio.Component.VC.Tools.ARM64"
  ]
}
```

**Comment by SeanTolstoyevski** [comment]
I create a PR on this Issue?
By adding a separate note to README, I can upload the ".vsconfig" file to the repo.

**Comment by leonardder** [comment]
It looks to me this was closed unintentionally.

CC @bramd

**Comment by SeanTolstoyevski** [comment]
I Forked NVDA.

I will send the PR.

I forgot.

Thanks for remind me @leonardder

**Comment by SeanTolstoyevski** [comment]
Hi,

I sent my first PR to NVDA.
I think it was not accepted.
But the comment was not written either.

Can you please summarize the situation with me?

I would like to fix it if it is wrong.

**Comment by josephsl** [comment]
Hi, I think the PR is okay (unless someone says otherwise); at the moment we are trying to focus on making sure pull requests that haven’t been touched in months and years get updates (think of it as PR maintenance). Thanks.

**Comment by CyrilleB79** [comment]
@SeanTolstoyevski could you comment on why you closed this issue, as well as the corresponding PR #11035? Thanks.

**Comment by SeanTolstoyevski** [comment]
hi @CyrilleB79 ,

I could not do what @leonardder said. It may also be because my English is nevbie :) .

Because the install component list in readme was very complex.
Everything is so confused and I turned it off.
