### ISSUE TITLE
NVDA not announcing legend hint with aria-describedby if first input has hint

### ISSUE THREAD

**Issue by NickColley** [nvaccess/nvda#10810]
### Steps to reproduce:

> The hint text for the aria-describedby on the input type="checkbox" supersedes the hint text for the aria-describedby on the fieldset. So the user only gets one hint read to them when they jump to the input through the tab index – the one on the input, rather than the legend.

1. Navigate to https://output.jsbin.com/juyaquq
2. Tab to first input

#### Minimal test case

```html
<fieldset aria-describedby="confirm-nationality-hint">
    <legend>
        What is your nationality?
    </legend>
    <span id="confirm-nationality-hint">
      Select all options that are relevant to you.
    </span>
    <br>
    <input id="confirm-nationality" name="confirm-nationality" type="checkbox" value="british-nationality" aria-describedby="confirm-nationality-item-hint">
    <label for="confirm-nationality">British</label>
    <span id="confirm-nationality-item-hint" class="govuk-hint govuk-checkboxes__hint">
      including English, Scottish, Welsh and Northern Irish
    </span>
    <br>
    <input name="confirm-nationality" type="checkbox" value="irish-nationality" aria-describedby="confirm-nationality-2-item-hint">
    <label class="govuk-label govuk-checkboxes__label" for="confirm-nationality-2">Irish</label>
    <span id="confirm-nationality-2-item-hint" class="govuk-hint govuk-checkboxes__hint">
      including from Northern Ireland
    </span>
    <br>
    <input id="confirm-nationality-3" name="confirm-nationality" type="checkbox" value="other-country-nationality" data-aria-controls="conditional-confirm-nationality-3">
    <label for="confirm-nationality-3">Citizen of a different country</label>
</fieldset>
```

JSBIN: https://output.jsbin.com/juyaquq

### Actual behavior:
The legend is announced, then the input and finally the input hint.

### Expected behavior:

The legend is announced, followed by the legend hint, then the input and finally the input hint.

#### Name and version of other software in use when reproducing the issue:
Chrome version: 79.0.3945.130
Firefox version: 72.0.2

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by Adriani90** [comment]
Did you test this in browse mode or in focus mode?

**Comment by nickcolley** [comment]
I'm not sure sorry, I would have to check. I used the default settings if that helps. Will get back to you.

**Comment by nickcolley** [comment]
I believe browse mode based on the description here: https://tink.uk/understanding-screen-reader-interaction-modes/

**Comment by Adriani90** [comment]
cc: @jcsteh

**Comment by jcsteh** [comment]
Firefox is exposing this correctly, so I guess NVDA is choosing not to read the description for groupings in browse mode when tabbing.

**Comment by Adriani90** [comment]
cc: @leonardder maybe you can help here since you implemented the grouping reporting feature earlier.

**Comment by BrianLovely** [comment]
I have a similar issue, but the hint isn't reading at all when in forms mode:

`<label for="iid">Trigger for Application Mode</label>
<input type="text" id="iid"/>
<fieldset aria-describedby="eid" aria-invalid="true">
<legend>Choose your favorite pizza topping</legend>

<label for="r1">Pineapple</label>
<input type="radio" id="r1" name="top"/>

<label for="r2">Pepperoni</label>
<input type="radio" id="r2" name="top"/>

</fieldset>
<span id="eid">You must hate pizza</span>`

NVDA v 2021.2
Windows 10 Enterprise
Chrome Version 96.0.4664.93 (Official Build) (64-bit)

The Accessibility tab in the dev tools shows the perceivable description of the fieldset to be set as expected, but NVDA does not read it out. I purposefully triggered forms mode by putting the group in a form element and preceding the group with a text input. The text input audibly switches NVDA to forms mode

**Comment by BrianLovely** [comment]
I have a similar issue, but the hint isn't reading at all when in forms mode:

```
<fieldset aria-describedby="eid" aria-invalid="true">
<legend>Choose your favorite pizza topping</legend>

<label for="r1">Pineapple</label>
<input type="radio" id="r1" name="top"/>

<label for="r2">Pepperoni</label>
<input type="radio" id="r2" name="top"/>

</fieldset>
<span id="eid">You must hate pizza</span>
```

NVDA v 2021.2
Windows 10 Enterprise
Chrome Version 96.0.4664.93 (Official Build) (64-bit)

The Accessibility tab in the dev tools shows the perceivable description of the fieldset to be set as expected, but NVDA does not read it out. I purposefully triggered forms mode by putting the group in a form element and preceding the group with a text input. The text input audibly switches NVDA to forms mode

**Comment by Adriani90** [comment]
@BrianLovely you set the description ID "eid" on a span which is not included in the fieldset, so NVDA cannot access the text when entering the fieldset because it is outside. You have to include the span into the fieldset and then it should work.

I am closing this issue as duplicate and in favor of #12718. The discussion contains more details there.
