### ISSUE TITLE
Suggestion about words with all caps

### ISSUE THREAD

**Issue by burakyuksek** [nvaccess/nvda#10822]
### Is your feature request related to a problem? Please describe.
I sometimes encounter words with all caps. As a student of translation studies, I want to capitalize my work too so I can fit it to the source. I don't know where I encounter them.
### Describe the solution you'd like
Addition of an option which causes the synthesizer to raise pitch while reading the word whenever it encounters a written word, just like it does when we navigate over capital letters. The options of beeping and say cap should also be implemented.

**Comment by Qchristensen** [comment]
Closing this as a duplicate of #3286.  The issue itself is still valid, but please continue conversation of it in issue #3286.
