### ISSUE TITLE
Add script for aria figure to input gestures and give the user the possibility to turn off reporing of this role in document formating settings

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#10826]
### Is your feature request related to a problem? Please describe.
See examples for Aria figure here
https://www.w3.org/WAI/tutorials/images/groups/#multiple-images-conveying-a-single-piece-of-information

I see more and more websites using this aria role to group information. The problem is that NVDA alway announce when entering and leaving this container. While this might be useful in some circumstances, users will most probably prefer to decide themselves if this should be reported or not while navigating in browse mode.

### Describe the solution you'd like
The best solution is to maintain consistency here. I.e. as it is in case of groupings, there should be a script for figures in input gestures. And the users should be able to turn off reporting in document formating settings.

### Describe alternatives you've considered
None

### Additional context
None

**Comment by Adriani90** [comment]
this should also be possible for captions, not only figures.

**Comment by fisher729** [comment]
Hi.

We're going to have the option to turn off graphics in NVDA 2020.3, why not just add an option to toggle the reporting of figures and captions?

**Comment by josephsl** [comment]
Hi, to add context to this: there was a discussion on NVDA users list about excessive verbiage of “figure/out of figure”. Thanks.

**Comment by leonardder** [comment]
I think it makes sense to let graphics reporting control figures as well. As for captions, I'd add a new entry to the document information section in document formatting settings.

I'll mark this good for new dev, as it is pretty easy to implement this.

**Comment by fisher729** [comment]
Hi.

Any update on this? I do acknowledge that figure reporting might be useful, but for most users, it's pretty irrelevant. I'd say it requires a separate checkbox in document formatting settings, possibly joined with captions.

**Comment by burakyuksek** [comment]
I agree on this being added. It's prittey unnecessary for me in most cases.

**Comment by rkingett** [comment]
If/when this gets added, I'd like the ability to include the, caption, announcement and this should be in the document formatting setting, not the browse mode setting.

**Comment by Adriani90** [comment]
@SaschaCowley thanks for contributing to solve this issue. Does your solution contain both figures and captions? Or only figures? I would say it is ok to merge both figures and captions in the same script in input gestures / checkbox in document formating settings. These atributes are being often used in similar scenarios.
See this source:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/figure_role

Mostly the caption is set on an image and is used instead of aria label or labeledby, and for many users it is enough to hear that it is a grafic along with the labels / caption text without the atribute "caption" or "figure".
So if caption has not been considered yet, I vote for reopening this issue, see also https://github.com/nvaccess/nvda/issues/10826#issuecomment-595172022.

**Comment by SaschaCowley** [comment]
@Adriani90, the linked PR does include captions. The user can disable reporting of both figures and captions at once, but not separately. The quick nav script allows navigation by figure, but not captions (I don't see how navigation by caption would be helpful?).

**Comment by Adriani90** [comment]
Hey Sascha thanks for the details, in this case I will close this issue. Yeah navigation by caption does not really make sense indeed.
