### ISSUE TITLE
NVDA plays progress bar notification sounds when scrolling through this page in Firefox

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#10828]
### Steps to reproduce:

1. Have progress bar announcements enabled (either with speech, beeps or both) under object presentation.
2. In Firefox, visit [this page](https://codeofmatt.com/list-of-2020-leap-day-bugs/) and press h to rapidly scroll through the page.

### Actual behavior:

Progress bar announcements are heard when scrolling through the page.

### Expected behavior:

No progress bar announcements are heard.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-19724,2c4caa62

#### Windows version:
Windows 10 1909

#### Name and version of other software in use when reproducing the issue:
Firefox 74.0B9

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

This does not happen in other browsers, and this is also not the first site where I've noticed this behaviour.

**Comment by DrSooom** [comment]
Because there is a progress bar implemented in this page – directly above the line "Code of Matt © 2020"". Therefore: Won't fix.

**Comment by Neurrone** [comment]
Thanks @DrSooom, I guess this is somehow a common enough pattern that I didn't think it would have been caused by websites themselves. Closing since this is a web authoring issue, and nothing to do with NVDA.
