### ISSUE TITLE
Read "Underline" & "Strike-through" words like "begin underline" & "end underline"

### ISSUE THREAD

**Issue by anudeeptummala** [nvaccess/nvda#10820]

**Comment by anudeeptummala** [comment]
Adding a option to read "Underline" & "Strike-through" words in detail would be helpful.

**Comment by Adriani90** [comment]
Please provide a clear description with an example document to be able to analyse nvda‘s behavior and please fill the template accordingly. Thanks.

**Comment by anudeeptummala** [comment]
![image](https://user-images.githubusercontent.com/58862583/75388033-24de2400-5899-11ea-9812-14aad131043a.png)
When I use NVDA Reader to read the underlined words or Strike-through words. NVDA is not reading underlined words as "begin underline" before reading the word & "end underline" after  last underlined word is read.Instead it just reads as a plain word.Same way with "Strike-through"  word.

**Comment by fnavaei** [comment]
I was wondering if the Document Formatting is the option you are looking for. 
I don't know how it works, but as NVDA User Guide suggests, it should report the type of formatting as you move the cursor around documents.
 
![image](https://user-images.githubusercontent.com/10091932/75389248-1133bd00-589b-11ea-844d-fa08c42b1b8b.png)

**Comment by Adriani90** [comment]
@anudeeptummala it works if you try with following settings in NVDA / document formating settings:
* Font atributes
* Emphasis
* Style
