### ISSUE TITLE
rate boost of Windowsonecore are not maintained after switching profile

### ISSUE THREAD

**Issue by lstar4ever** [nvaccess/nvda#10837]
### Steps to reproduce:
1. I switch to Fastreading profile from default profile
2. I enter into speech setting and enable the rate boost option for Windows one core.
3. save and exit the setting window
4. use hotkey to switch off fast reading profile and return to default window
5. after some time, I use the hotkey to enable fastreading profile
6. the rate boost effect does not appear. the reading speed is as if the rate boost option is not enabled.
7. I go into the speech setting and found that the check box for rate boost is checked.

### Actual behavior:
The rate boost option is not kept after switching back to the same profile

### Expected behavior:
after switching back to the same profile, rate should be boosted

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
19.3.1
#### Windows version:
10 1903

#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

**Comment by lstar4ever** [comment]
I feel sorry, after disabling addons, I found that this issue do not exist. It probably related to one of the installed addons. Thanks and sorry.

**Comment by Brian1Gaff** [comment]
If you can isolate the add on it might be nice to record this in the ticket 
for future use.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
