### ISSUE TITLE
Using CAPTCHA brings focus to hidden element

### ISSUE THREAD

**Issue by annameyerepic** [nvaccess/nvda#10835]
### Steps to reproduce: 
Multiple <div> elements, some of which are hidden via CSS (display: none). 

### Actual behavior:
Without a CAPTCHA on the page, everything works fine. Once we add the CAPTCHA, NVDA reads out the first display: none element but ignores all the other elements.

### Expected behavior:
NVDA should ignore the display: none elements

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.3.1

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
Chrome, version 80.0.3987.122 (we are not seeing this issue on versions of Chrome pre-80)

#### Does the issue still occur after restarting your PC?
Yes

**Comment by Adriani90** [comment]
Cc: @Qchristensen

**Comment by DrSooom** [comment]
@annameyerepic: Which CAPTCHA solution (name and version) was implemented?

**Comment by Brian1Gaff** [comment]
...and send 20000 volts up the  arm of the site admins using such a rubbish 
way to detect a human.. grin.
 Sorry....
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by annameyerepic** [comment]
We're using Google reCaptcha V2

**Comment by Adriani90** [comment]
@annameyerepic please provide a test example so that we can reproduce this issue. Otherwise it will be too difficult to investigate further. Thanks.

**Comment by Adriani90** [comment]
We didn't get the info requested and no updates from the initial author since many years, I am closing as abandoned. If you are still having this issue, please comment with info requested and we can reopen.
