### ISSUE TITLE
Audio Screen not working on one machine

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#10844]
Apologies if this is the wrong place to report this issue.  The problem occurs on my notebook computer with a touch screen, but not on the desktop.
### Steps to reproduce:
Download Audio Screen 2020.1
Install to NVDA 2019.3.1
Restart NVDA
### Actual behavior:
Audio Screen does not respond to relevant keystrokes.
When checking its status under NVDA Tools it is reported as "Audio Screen; Status: Installed, enabled after restart; Version: 2020.1;"
Multiple restarts of NVDA and rebooting do not help.
### Expected behavior:
Audio Screen produces sound when screen is touched.
#### NVDA installed/portable/running from source:
NVDA installed version
#### NVDA version:
2019.3.1
#### Windows version:
Windows Home 2019.3
#### Name and version of other software in use when reproducing the issue:
Firefox
#### Other information about your system:
Has touch screen.
Visual feedback on touch in Settings is unchecked.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
[nvda-ad.log](https://github.com/nvaccess/nvda/files/4290644/nvda-ad.log)

**Comment by andrew-l-d** [comment]
It just occurred to me that I have a portable copy of NVDA 2019.2.1 on the relevant machine and Audio Screen 1.4 has been added to that copy.  Could that upset things?

**Comment by andrew-l-d** [comment]
It has just occurred to me that there is a portable copy of NVDA 2019.2.1 on the machine and it includes Audio Screen 1.4.  Could that upset things?

**Comment by Adriani90** [comment]
cc: @michaelDCurran

**Comment by Adriani90** [comment]
@andrew-l-d I would suggest you to open a issue with audio screen directly at
https://github.com/nvaccess/audioScreen
or report this directly to NV Access per email at
info@nvdaccess.org

I am closing this issue here.
