### ISSUE TITLE
Problem with web browsing

### ISSUE THREAD

**Issue by DalisonCPU** [nvaccess/nvda#10843]
### Actual behavior:
when updating the site the content of the page does not change to NVDA
### Expected behavior:
when clicking on a link or button on the page, the content of the page should change normally.
#### NVDA installed/portable/running from source:
Instaled
#### NVDA version:
2019.3.1
#### Windows version:
10.0.18362 Compilation 18362
#### Name and version of other software in use when reproducing the issue:
Google Chrome
#### Other information about your system:
It hadn't happened before, and it suddenly started happening.
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no.
But I think this error only happens in NVDA 2019.3.1. The problem doesn't just happen to me, just to all my friends.
[nvda.log](https://github.com/nvaccess/nvda/files/4289652/nvda.log)

**Comment by Adriani90** [comment]
Fixed in chrome 81 scheduled for march 17th
