### ISSUE TITLE
NVDA says "caption, out of caption, figure, out of figure" even if all elements are disabled in document formatting category in settings dialog on some web pages

### ISSUE THREAD

**Issue by Surveyor123** [nvaccess/nvda#10845]
### Steps to reproduce:
Disable all elements in document formating.
go for example to this site: https://www.yenisafak.com/
Navigate through pressing h for instance or press say all command.
### Actual behavior:
It is impossible to follow page content because NVDA adds unneeded infos such as "caption, out of caption, figure, out of figure etc"
#### NVDA installed/portable/running from source:
for bouth installed and portable coppies
#### NVDA version:
2019.3.1 and valid for latest alpha
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Google Chrome
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, no problem with NVDA 2019.2

**Comment by Adriani90** [comment]
This is not possible yet to turn off. And is already covered in #10826. Closing as duplicate.
