### ISSUE TITLE
Screen reader announces table header twice for Angular 

### ISSUE THREAD

**Issue by staffordp** [nvaccess/nvda#10840]
### Steps to reproduce:

Using the table with sorting as documented here: https://material.angular.io/components/sort/overview

- Visit https://stackblitz.com/angular/xekbmvlqeqj?file=src%2Fapp%2Ftable-sorting-example.html
- Click open in new window to make navigation easier
- Navigate to the table header and activate it, (or click on it)

### Actual behavior:
NVDA reader announces the element twice as "Change sorting for name column 2 clickable Change sorting for name button"

### Expected behavior:
It announce the column once like "Change sorting for name column 2 clickable"

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2019.3.1

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
Chrome Version 80.0.3987.122 (Official Build) (64-bit)

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

**Comment by feerrenrut** [comment]
I don't seem to be able to reproduce this issue in firefox or chrome. Does this occur for you when you use keyboard only input? Have you tested firefox?

**Comment by staffordp** [comment]
Yes Chrome and Firefox. Use the stackblitz link I posted:[ Stackblitz](https://stackblitz.com/angular/xekbmvlqeqj?file=src%2Fapp%2Ftable-sorting-example.html)

**Comment by feerrenrut** [comment]
Still unable to reproduce the issue with Firefox 74.0
I can now reproduce the issue with Google Chrome 80.0.3987.132. I think chrome updated since my testing yesterday.

The issue is also reproducible with keyboard input.

**Comment by Adriani90** [comment]
This is only reproducible in focus mode when navigating with tab or shift+tab.

**Comment by feerrenrut** [comment]
Quite possibly related, a much simpler test case: [code pen](https://codepen.io/reefturner/pen/oNzNNmv), and the [code pen full view](https://codepen.io/reefturner/full/oNzNNmv)

**Comment by mfairchild365** [comment]
@feerrenrut I agree that this issue is not specific to Angular and can be reproduced in browse mode while running NVDA with a Chromium based browser. I tracked down the issue and put in a PR with system tests. https://github.com/nvaccess/nvda/pull/12763
