### ISSUE TITLE
Say all stops while reading documents in WordPad and Firefox 73.0.1

### ISSUE THREAD

**Issue by bingen13** [nvaccess/nvda#10852]
### Steps to reproduce:

Open a reasonably long document on Firefox 73.0.1 or WordPad on Windows 8.1, and press the Say All combination (NVDA-downarrow). Wait for a while.

### Actual behavior:

NVDA will read text for some time, but eventually stop without apparent cause.

### Expected behavior:

NVDA continues reading text until the end of the document is reached.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

2019.3.1

#### Windows version:

Windows 8.1 64 bit

#### Name and version of other software in use when reproducing the issue:

Firefox 73.0.1 or WordPad. Haven't tried on other programs but if it happens in those two it may happen in other Say All situations.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

2019.2 didn't do this.

#### If addons are disabled, is your problem still occuring?

I think so, but the non-deterministic response makes it hard to test.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

No, will do so now.

Additionally, there is this error in the log. I'm not sure if it is related, but since it may be, I am pasting it:

ERROR - speech.manager.SpeechManager._handleIndex (10:14:26.677) - MainThread (1784):
Error running speech callback

````
Traceback (most recent call last):
  File "speech\manager.pyc", line 404, in _handleIndex
  File "speech\commands.pyc", line 260, in run
  File "sayAllHandler.pyc", line 145, in <lambda>
  File "sayAllHandler.pyc", line 174, in lineReached
  File "documentBase.pyc", line 24, in makeTextInfo
  File "virtualBuffers\__init__.pyc", line 207, in __init__
  File "textInfos\offsets.pyc", line 460, in __init__
  File "virtualBuffers\__init__.pyc", line 225, in _getStoryLength
OSError: [WinError 1775] Un identificador nulo de contexto se pasó del cliente al host durante una llamada a procedimiento remoto
++++

**Comment by zstanecic** [comment]
Which speech synthesizer do you use?

**Comment by bingen13** [comment]
IBMTTS.

I would like to be able to reproduce this with ESpeak or another synth, but it's really difficult because it doesn't happen in any predictable schedule.

**Comment by zstanecic** [comment]
The problem is that I cannot reproduce this  with espeak, the legal codefactory eloquence and rh voice.

**Comment by bingen13** [comment]
Alright, I'll set logging to debug and wait for it to happen again--hopefully I can catch better information.

**Comment by Mohamed00** [comment]
Do you by any chance have the Speech History addon installed?

**Comment by bingen13** [comment]
No, I don't.

**Comment by bingen13** [comment]
Well, I run the COM registration fixing tool, and since then it hasn't seemed to happen again. I doubt this is what fixed it--probably it is just a matter of the bug coming up rather seldom--but I may as well close it until I get another reproduction and hopefully better logs to go with it. Thanks everyone.
