### ISSUE TITLE
Regression: NVDA exits focus mode when arrowing through list boxes in Vs Code

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#10853]
### Steps to reproduce:

1. In Vs Code insiders (this will probably work in stable as well), do something which causes you to navigate within a list box. I typed ctrl+shift+x to open the extensions view
2. Type any search term and press enter, e.g "vs notes"
3. Press tab to move focus to the list of results, and down arrow to review the result list.

### Actual behavior:

NVDA does not exit focus mode so that the arrow keys work as intended

### Expected behavior:

NVDA exits focus mode and enters browse mode so that the widget can't be used properly.

#### NVDA installed/portable/running from source:
Installed, running from snapshots while I binary searched the version that introduced the regression

#### NVDA version:
Versions since [alpha-19579,47367fb3](https://ci.appveyor.com/project/nvaccess/nvda/build/alpha-19579,47367fb3/artifacts), it looks like this was caused by #10713 

#### Windows version:
Windows 10 1909

#### Name and version of other software in use when reproducing the issue:
Vs code insiders

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, see above

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by leonardder** [comment]
Note that in Code Insiders, there's no appModule that disables browse mode by default. Therefore, I"m pretty sure that this works differently in Code Stable.

**Comment by Neurrone** [comment]
@leonardder hm, I'm wondering how this explains the issue not existing in NVDA 2019.3.1 (which presumably includes the app module for the stable version of Vs Code) vs recent snapshots? Or is it an interaction between browse mode not being disabled and #10713?

**Comment by leonardder** [comment]
I don't think these are related.

Could you please test the build for #10858 when it's ready?

**Comment by Neurrone** [comment]
I've tested this and it is still behaving unexpectedly. For example when an autocomplete suggestion comes out, you're thrown out of focus mode into browse mode, which is annoying when it appears as you're rapidly typing, causing a few characters not to be entered to the file.

**Comment by leonardder** [comment]
Could you ensure that the right appModule is loaded by doing 
nav.appModule from a python console?

**Comment by Neurrone** [comment]
@leonardder yeah, it says vs code

**Comment by Neurrone** [comment]
@leonardder curious if you use Vs Code yourself with snapshot NVDA builds?
