### ISSUE TITLE
Error with direction arrows in alpha versions

### ISSUE THREAD

**Issue by comunicationVoices** [nvaccess/nvda#10865]
Hello, I report an error that is happening to me when I have installed the alpha version, the arrow keys (Right and left respectively) Do not work. I mean, that it does not make the letters beautiful in either a text box or a document and this is something useful for me, I have restarted many times but the problem continues. I have Windows 10 version 1909. Thanks for reading.

**Comment by Adriani90** [comment]
Is the speech viewer enabled?

**Comment by Adriani90** [comment]
Please fill the template accordingly.

**Comment by Brian1Gaff** [comment]
I think the reporter may be having English issues filling in the template.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by comunicationVoices** [comment]
The same happens to me if Speech Viewer is activated or not. But, cave clarify that the stable 2019.3.1 does not bring this problem, only in the alpha and it is necessary to correct it. And as for the template, I'm just learning to use Gitub but I would be changing the subject ... A greeting and thanks

**Comment by Adriani90** [comment]
Have you tried with all addons disabled?
Try also to run the com registration fixing tool in nvda menu / tools.
Does this help?
If not, please attach here a log file. Press nvda+f1 when you hear the error sound. Save that file and upload it to this issue. Thanks.

**Comment by comunicationVoices** [comment]
Hi. I have already discovered this problem, it was indeed a problem of the speech history add-on to copy the last element verbalized by NVDA and navigate through the last 100 messages, I disabled it although I use it a lot. Thanks again!

**Comment by Adriani90** [comment]
In this case please get in touch with author of the addon. Thanks.
