### ISSUE TITLE
Allow developers to use different version of SCons than the one bundled in the repository

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#10876]
### Is your feature request related to a problem? Please describe.
On some hosts current version of SCons is not working which prevents building. For real examples see:
- #9990
- https://github.com/SCons/scons/issues/3572

The latter report is especially problematic for me, because it makes it impossible for me to build on my main machines.
In both these cases it is possible to build with more recent / self-modified version of SCons.

It is understandable that SCons in the repository is updated only when there are beneficial changes for NVDA, but often the gaps between updates are quite long (for example if someone suffered from #9990 he had to wait more than half a year to be able to build again).
### Describe the solution you'd like
It should be possible for a developer to specify different folder containing SCons, perhaps via command line. @feerrenrut Would you be able to give your opinion here?
 ### Describe alternatives you've considered
Stop including SCons as a submodule and require developers to install it via pip.
### Additional context
While such errors affects only minority of users they make it impossible to contribute, for them so I would appreciate commends.

**Comment by feerrenrut** [comment]
I think the simplest way for someone to modify their version of SCons is to update the submodule locally. But this doesn't necessarily mean it is compatible with our sconscripts, there isn't much we can do about that. In the future I would like the NVDA repo to configure and enable a python virtual environment as a first step in the build / run from source. It could then install python dependencies via pip. This would make it easier to test new dependency versions / upgrade python, and reduce the chance of interference from different dev setups. For this particular issue I don't think it would make much difference.

**Comment by leonardder** [comment]
Couldn't you just run scons by executing `"C:\Python37\Scripts\scons.bat"`?

**Comment by lukaszgo1** [comment]
Not in the current state. Our SConscript requires sourceEnv which is being added to PYTHONPATH by scons.py from the main dir of the repo.
It seems to be possible to reorganize this in a way which would allow to use installed version of SCons if invoked explicitly falling back to the bundled one in all other cases.
@feerrenrut Would you accept such enhancement to the build system?

**Comment by dingpengyu** [comment]
hello 
I think we can use GitHub Actions to solve this problem, we can write an NVDA actions build script, if developers who need to build and test NVDA can directly use this script to build.
thanks

**Comment by feerrenrut** [comment]
@lukaszgo1 Yes, as long as we can be confident it doesn't affect the main use case (building from bundled scons). 
@dingpengyu There would be quite some work to convert from Appveyor builds. It's not just a conversion, but generalizing the build process to separate the NV Access specific steps from the steps required for everyone. That said, if you wish to do this in your own fork of NVDA it would be possible.

**Comment by dingpengyu** [comment]
> @lukaszgo1 Yes, as long as we can be confident it doesn't affect the main use case (building from bundled scons).
> @dingpengyu There would be quite some work to convert from Appveyor builds. It's not just a conversion, but generalizing the build process to separate the NV Access specific steps from the steps required for everyone. That said, if you wish to do this in your own fork of NVDA it would be possible.
thank you for your reply
In fact, it can be used in conjunction with appveyor. My idea is based on the following items.
[Action-OpenWrt](https://github.com/P3TERX/Actions-OpenWrt)
thanks

**Comment by dingpengyu** [comment]
This is the component of my current environment for compiling NVDA. I hope it can help everyone:
visual studio: 2019-16.4x
python: 3.7.7
scons: latest
virtualenv: latest
thanks

**Comment by JulienCochuyt** [comment]
Hi @lukaszgo1,
What does prevent you from building NVDA from within a Python virtual environment?
Doing so would isolate your installed SCons from the one bundled with NVDA.
(I actually use only virtual environments, and thus never install anything in my bare Python installations.)

**Comment by lukaszgo1** [comment]
@JulienCochuyt wrote: 
> What does prevent you from building NVDA from within a Python virtual environment?
> Doing so would isolate your installed SCons from the one bundled with NVDA.

When running scons.py from the main directory of the repo the bundled SCons has precedence over the one installed in Python regardless if its installed in a virtualenv or not. When not using scons.py but invoking scons directly it fails. because SConscript cannot find sourceEnv as explained above. Pull request making it possible to build with a different SCons version will follow shortly.

**Comment by JulienCochuyt** [comment]
@lukaszgo1, Sorry I took this issue the other way around. Your proposal makes sense when facing issues with the bundled version.
