### ISSUE TITLE
Field values within html table are read as "selected" by NVDA

### ISSUE THREAD

**Issue by parora2020** [nvaccess/nvda#10880]
Using Windows 7, Chrome, NVDA version 2019.1.1. 
Reading table in HTML. All the fields are read as "selected" 
Tried with NVDA version 2019.3.1 and get same results.
It was bbeing read properly about 4 weeks back. We could have had a Windows patch in between. Now all table fields are read as "Selected"

**Comment by Adriani90** [comment]
Please fill the template including a test case and the browser version you are using. Include also testing with all addons disabled.

**Comment by parora2020** [comment]
Tested after disabling all addons in Chrome Version 80.0.3987.87 (official Build)(32 bit).All the fields within table are read as "selected"
Steps:
Turn "ON" NVDA screen reader
Generate report using IBM Cognos.
Navigate to the report using keyboard.
All the fields within the report are read as "selected"

**Comment by parora2020** [comment]
Please note I am application with IBM Cognos for generating reports.

**Comment by parora2020** [comment]
Please note the reports are generated using IBM Cognos

**Comment by feerrenrut** [comment]
@parora2020 Could you test with Firefox and report if the behavior is different?

I'm going to guess that there aren't any NVDA developers with access to reports generated using IBM Cognos. Could you inspect the HTML and create a minimal sample that reproduces the issue? If not, can you attach a sample report to this issue so that someone can do this on your behalf. 

A minimal sample is much more likely to result in this issue being resolved, without more information this issue will be closed.

**Comment by parora2020** [comment]
Hi!
Here is a small sample report that was being read in Chrome and reading every field as "selected" . I have attached screenshot for your reference.
The saved html is read differently than when this report is actually read when generated within Cognos.  I am attaching the saved sample report for reference as well.

![NVDA issue](https://user-images.githubusercontent.com/62262677/77934096-997ff600-727d-11ea-9f79-eee4633adb48.jpg)
[Sample for NVDA.zip](https://github.com/nvaccess/nvda/files/4403929/Sample.for.NVDA.zip)

The above results were obtained with following settings:
Windows 10 Professional X64
Intel i5-835ou CPU
Google Chrome : Version 80.0.3987.149(official Build)(64 bit)
NVDA : Version 2019.3.1 (Have tried with older versions as well)

**Comment by parora2020** [comment]
Hi ,
Here is a small sample report that was being read in Chrome and reading every field as "selected" . I have attached screenshot for your reference.
The saved html is read differently than when this report is actually read when generated within Cognos. I am attaching the saved sample report for reference as well.
[NVDA issue]<https://user-images.githubusercontent.com/62262677/77934096-997ff600-727d-11ea-9f79-eee4633adb48.jpg>
Sample for NVDA.zip<https://github.com/nvaccess/nvda/files/4403929/Sample.for.NVDA.zip>
The above results were obtained with following settings:
[cid:image002.png@01D6068B.74AEC580]

[cid:image003.png@01D6068B.74AEC580]            [cid:image004.png@01D6068B.74AEC580]



Regards,

Parminder

**Comment by feerrenrut** [comment]
I'm not able to reproduce the issue you are describing. How are you interacting with the report? Which keys are you pressing? are you using the mouse? Could you upload the NVDA log after testing with chrome please?

Also please try with Firefox.

**Comment by feerrenrut** [comment]
This looks like it is a duplicate of #10447. This issue is active, it would be good to get more information. 

@parora2020 Are you using a portable version of NVDA?

**Comment by parora2020** [comment]
Using installed version of NVDA (not portable)
I will not be able to test with firefox due to restrictions to download at workplace.

**Comment by parora2020** [comment]
Here is log file from today. The laptop was restarted today morning and cannot find previous log file. 
[nvda.log](https://github.com/nvaccess/nvda/files/4410263/nvda.log)

**Comment by parora2020** [comment]
Arrow keys are being used to navigate the table. No, mouse is not used.

**Comment by feerrenrut** [comment]
The log file is only at level INFO, if possible please upload a Debug level log (can be changed on the general settings panel). However the log uploaded contains the following error which is a good starting point. It is the same as the error in #10925
```
ERROR - eventHandler.executeEvent (08:49:49.666) - MainThread (25796):
error executing event: gainFocus on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x01179770> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1534, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 1102, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 988, in reportFocus
  File "speech\__init__.pyc", line 485, in speakObject
  File "speech\__init__.pyc", line 318, in speakObjectProperties
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1147, in _get_columnNumber
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
```

**Comment by parora2020** [comment]
Debug level log uploaded
[nvda.log](https://github.com/nvaccess/nvda/files/4444311/nvda.log)

**Comment by Adriani90** [comment]
@parora2020 I cannot find any table when i open the html sample file that you shared here. Can you please provide an updated minimal test case? Do you still hahve this issue in NVDA 2023.2?

**Comment by Adriani90** [comment]
No updates from the initial author since many years, I am closing as abandoned. If you are still having this issue, please comment and we can reopen.
