### ISSUE TITLE
VS Code: Reduce the number of times one has to use NVDA+Space to switch modes.

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#10888]
I just filed [this issue](https://github.com/microsoft/vscode/issues/93087) against VS Code where I suggest to use targeted role="document" in those places that produce HTML output for consumption, to make NVDA switch in and out of browse mode in a smart, automated, manner, reducing the number of times one has to use NVDA+Space to toggle modes. Examples I found while using the 1.44 VS Code Insider builds were:

* The Welcome page
* The details page for an extension
* The ReadMe file that may be displayed after an extension has been installed.

@leonardder suggested that, once this lands in stable, a modification might be needed for the VS Code app module. So filing this issue here.

**Comment by leonardder** [comment]
Added the needs external fix label. As soon as https://github.com/microsoft/vscode/issues/93087 is addressed, we can reconsider the behavior of our appModules.

**Comment by MarcoZehe** [comment]
VS Code insider builds now have the fix for role="document" in some places where they make sense, and more are being added as they're discovered. I think we can reevaluate now whether the VS app module still makes sense. The Insider one can certainly be removed, the other one once VS Code 1.44 gets released.

**Comment by leonardder** [comment]
This should be fixed for Code Insiders now. As soon as the april update of Code is there, we can revert
