### ISSUE TITLE
link activation problem in Firefox

### ISSUE THREAD

**Issue by oaron** [nvaccess/nvda#10884]
### Steps to reproduce:

1. Open a webpage in Firefox (E.G. https://m.facebook.com)
2. Select a link with a tab key (e.g. messages).
3. Press enter on it.
### Actual behavior:
After pressing enter, The new page does not load. It works only if I press a right arrow before enter or space pressing.
### Expected behavior:
After tabbing a  link, and if I press the enter, its page loads.
#### NVDA installed/portable/running from source:
Installed NVDA
#### NVDA version:
alpha-19801,a32d7e2e
#### Windows version:
Windows 10 pro	10.0.18362 build 18362

#### Name and version of other software in use when reproducing the issue:
Mozilla Firefox 74.0
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, I tried it with NVDA 2019.3.1, the problem is occuring.
#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes.

**Comment by Brian1Gaff** [comment]
If you do a page refresh, does that work?
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by feerrenrut** [comment]
Could you tab to the link, press NVDA+F1 and copy all lines after `Developer info for navigator object` and attach them to this issue?

**Comment by oaron** [comment]
[nvda-debug.txt](https://github.com/nvaccess/nvda/files/4359863/nvda-debug.txt)

**Comment by DrSooom** [comment]
Tip: Always maximize the Firefox/Chrome/Edge/etc window by pressing Win+ArrowUp. This could help if a link can't be activated.

**Comment by oaron** [comment]
I maximized the window, but it did not solve this issue.

**Comment by feerrenrut** [comment]
I can't reproduce this.
I have had a look at the log, indeed NVDA announces "News link", enter is pressed and nothing happens for 3 seconds. The dev info confirms this is a the news link on the NV Access website.

One thing I notice in the log is that there are several add-ons running, the issue description says you have tried with addons disabled, can you confirm this does not fix the issue on the NV Access site?

Does this problem always occur or only sometimes?

**Comment by oaron** [comment]
I've disabled NVDA add-ons, but the problem always occurs. I attached a new log file.
[nvda-debug.txt](https://github.com/nvaccess/nvda/files/4389838/nvda-debug.txt)

**Comment by Adriani90** [comment]
I can also reproduce this on websites from time to time since Firefox 74.

cc: @jcsteh

**Comment by jcsteh** [comment]
Do you have "Automatically set system focus to focusable elements" disabled in NVDA Settings -> Advanced? This is a known bug when that is disabled. Note that this is enabled by default.

**Comment by oaron** [comment]
Yes, that was disabled. I enabled it, and problem solved!
Thanks for your help!

**Comment by feerrenrut** [comment]
@jcsteh Do you have an issue number for that bug?

**Comment by jcsteh** [comment]
I don't believe a separate issue was filed, but it's described here: https://github.com/nvaccess/nvda/pull/9511#issuecomment-495099828
See also #9886.
