### ISSUE TITLE
SAPI-4 synthesizers/voices pitch no longer increase during letter navigation

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#10896]
### Steps to reproduce:
1. Select a SAPI-4 synthesizer like IBM ViaVoice TTS in the Speech NVDA Settings.
2. Set "Capital pitch change percentage" to "25".
3. If you want, disable the checkbox "Say "cap" before capitals". If this option is enabled, the word "cap" (in German "Groß") is spoken with the higher pitch level too.
4. Read "TESTtest" letter by letter.
### Actual behavior:
The voice pitch does no longer increase during letter navigation.
### Expected behavior:
The voice pitch should increase during letter navigation.
#### Notes:
- All three SAPI-4 voices work as expected in NVDA 2019.2.1.
- All three SAPI-4 voices don't work as expected in NVDA 2019.3.1.
- eSpeak NG still works as expected in NVDA 2020.1 Beta 1; but this isn't a SAPI-4 synthesizer.
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
2020.1 Beta 1
#### Windows version:
Win7x64
#### Name and version of other software in use when reproducing the issue:
- SAPI-4, IBM ViaVoice TTS Runtime v6.610 - Deutsch
- SAPI-4, IBM ViaVoice TTS Runtime v6.610 - Français
- SAPI-4, IBM ViaVoice TTS Runtime v6.610 - UK English
#### Does the issue still occur after restarting your computer?
Not tested.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2019.2.1 (installed) and 2019.3.1 (portable); See notes above.
#### If addons are disabled, is your problem still occuring?
No add-ons are installed/used in NVDA 2019.3.1 and 2020.1 Beta 1 and I don't think that the installed/used add-ons in NVDA 2019.2.1 have any affects here.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No.

**Comment by zstanecic** [comment]
Hi daniel,

For now, a workaround is to turn of the option 

# use spelling functionaliti when supported checkbox #

**Comment by DrSooom** [comment]
There are no differences if "Trust voice's language when processing characters and symbols" and "Use spelling functionality if supported" are disabled or enabled in NVDA 2019.3.1 and 2020.1 Beta 1. I've tested all four possible variants right now. Just let me know, if you need a debug logfile.

**Comment by Brian1Gaff** [comment]
Yes this affects that LH sappi 4 as well. I don't think  any of the sappi 4 
systems is as stable now. Its is an old system, i'm surprised Microsoft 
still support it.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by cary-rowen** [comment]
#12354  It seems to solve this issue. Can you test it with the latest alpha version?

**Comment by seanbudd** [comment]
Closing as fixed by #12354
