### ISSUE TITLE
NVDA not reading content after keypressed event on edge browser

### ISSUE THREAD

**Issue by NishantVerma12** [nvaccess/nvda#10905]
I am trying to read the content using **aria-label on edge** at keypressed event but NVDA is not reading the **aria-label** message.

` <a class="plag--icon-box plag--report-icon-box  plag-menu-tray" ng-if="student"
                            ng-click="vm.toggleMenuTray()" tabindex="1.6" aria-label="menu options {{vm.menuOption}}"
                            ng-keyup="($event.keyCode === 13 && vm.toggleMenuTray())" role="button">
                            <i class="fa fa-cog plag--settings">
                            </i>
                        </a>`

This is my html any help would be appreciated.

**Comment by DrSooom** [comment]
@NishantVerma12: Please completely fill out the bug report draft. Thanks.

**Comment by feerrenrut** [comment]
Closing this issue since not enough information was provided.
