### ISSUE TITLE
Add support for Dell Mobile Connect

### ISSUE THREAD

**Issue by codeofdusk** [nvaccess/nvda#10900]
### Is your feature request related to a problem? Please describe.
Dell [released](https://www.theverge.com/2020/3/25/21193655/dell-mobile-connect-ios-pc-screen-mirroring-drag-and-drop-transfer-files) a Windows 10 app that allows iPhone users to send messages, make calls, etc from Windows. The app is usable with NVDA, but this could be made more efficient.

### Describe the solution you'd like
Add an app module to NVDA that:

* Reports the custom (non Windows toast) notifications.
* (possibly) removes the extraneous empty elements from the tab order.
* (possibly) enables autoread and message review functionality, similar to Miranda and Skype 7.

### Describe alternatives you've considered
None.

### Additional context
This is a UWP app, so NVDA accesses it via UIA. There don't seem to be many special class names/automation IDs we can use to identify particular controls.

**Comment by feerrenrut** [comment]
As mentioned on the PR https://github.com/nvaccess/nvda/pull/10910#issuecomment-605936786 this application does not have wide support, and should be developed as an Addon first.
