### ISSUE TITLE
Eclipse Tree Control no longer accessible

### ISSUE THREAD

**Issue by VantageKR** [nvaccess/nvda#10937]
### Steps to reproduce:

1. Run NVDA 2019.3.
1. Open up any community version of DBeaver (https://dbeaver.io) - the most recent is version 7.1.
1. Connect to a database.
1. Issue a query that would fail - something like "SSELECT 1;" - any query really that would not succeed for any reason.
1. Open up the Error Log: Alt + Shift + Q, l.
1. Tab to the tree view that usually holds the errors, and is expandable.
1. Notice how nothing is being read - this is not how it use to be on NVDA versions prior to 2019.3.

### Actual behavior:

The tree view is completely silent - nothing is being read anymore.

### Expected behavior:

The tree view is read, can be xpanded / collapsed - works quite well.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes.

## Log output: NVDA-key + F1

```
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (13:41:35.831) - MainThread (27724):
Developer info for navigator object:
name: None
role: ROLE_TREEVIEW
roleText: None
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.IAccessible.sysTreeView32.TreeView object at 0x08985BB0>
Python class mro: (<class 'NVDAObjects.IAccessible.sysTreeView32.TreeView'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'object'>)
description: None
location: RectLTWH(left=582, top=830, width=1351, height=181)
value: None
appModule: <'eclipse' (appName 'dbeaver', process ID 23484) at address 7730370>
appModule.productName: exception: No version information
appModule.productVersion: exception: No version information
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 1380992
windowClassName: 'SysTreeView32'
windowControlID: 1380992
windowStyle: 1442960037
extendedWindowStyle: 1048576
windowThreadID: 8416
windowText: ''
displayText: ''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x87ea20c at 2dd7e90>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=1380992, objectID=-4, childID=0
IAccessible accName: None
IAccessible accRole: ROLE_SYSTEM_OUTLINE
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: None
IAccessible accValue: exception: (-2147352573, 'Member not found.', (None, None, None, 0, None))
IAccessible2 windowHandle: 1380992
IAccessible2 uniqueID: -32
IAccessible2 role: ROLE_SYSTEM_OUTLINE
IAccessible2 states:  (0)
IAccessible2 attributes: 'margin-left:0;margin-top:0;margin-right:0;margin-bottom:0;text-align:center;text-indent:0;'

```

**Comment by lukaszgo1** [comment]
@VantageKR Could you please test this with NVDA 2019.2.1 to establish if it is regression in NVDA or in Eclipse?

**Comment by Adriani90** [comment]
No updates upon request from the initial author since many years, I am closing as abandoned. if you are still having this issue, please comment and we can reopen.
