### ISSUE TITLE
IE8N: Unified NVDA.po generation method and character processing

### ISSUE THREAD

**Issue by xingkong0113** [nvaccess/nvda#10930]
Currently, the NVDA.po generated by svn translation and the NVDA.po generated by visual studio are found to have differences in characters during the test.
With my testing in Simplified Chinese, I found that some translation entries will report errors in NVDA.po in svn, such as the following string:
{symbol} as in {description} ID: 1366
and
{number} {candidate} ID: 1367
And using the locally generated NVDA.po translation does not report an error.
### Steps to reproduce:
First generate the .pot translation template locally, then use the .pot translation template to generate the zh_CN.po language file, and finally use the generated .po file and the original svn .po file to translate the following strings at the same time:
{symbol} as in {description} ID: 1366
and
{number} {candidate} ID: 1367
The following prompt appears when using the NVDA.po translation in svn to count the strings:
1 problem found in translation. Entries with errors are marked red in the list. Error details are displayed when you select such an entry. The file has been saved securely.
### Actual behavior:
There is a difference in character between NVDA.po generated locally and NVDA.po generated by svn.
### Expected behavior:
Unifying the character generation methods of the two can solve the counting problem.
#### NVDA installed/portable/running from source:
install version
#### NVDA version:
nvda_snapshot_alpha-19867
#### Windows version:
windows10-1909-18363.720
#### Name and version of other software in use when reproducing the issue:
none
#### Other information about your system:
none
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
none
#### If addons are disabled, is your problem still occuring?
none
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
none
 This issue is outside the scope of this tool
thanks

**Comment by dingpengyu** [comment]
hi @feerrenrut 
Could this problem be resolved this year?
thanks.
