### ISSUE TITLE
Winamp support: NVDA doesn't detect the status of shuffle and repeat modes

### ISSUE THREAD

**Issue by burakyuksek** [nvaccess/nvda#10945]
### Steps to reproduce:
1. Start winamp
2. Press r or s toggle shuffle or repeat
3. NVDA will say "off" every time you toggle those modes
### Actual behavior:
NVDA will say "off" every time you toggle those modes
##
### Expected behavior:
NVDA needs to state if setting is on or off.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.3.1
#### Windows version:
Windows10 latest

#### Name and version of other software in use when reproducing the issue:
Winamp 5.666 Build 3516
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by josephsl** [comment]
Hi, caused by calling ANSI version of GetWindow function – needed to use W (Unicode version). PR on its way – thanks for catching this.
