### ISSUE TITLE
Word 2019 last version duplicates NVDA attribute change notification when formatting text through keystrokes

### ISSUE THREAD

**Issue by ivnc** [nvaccess/nvda#10950]
Reproduced by many Spanish-speaking users, including me.

### Steps to reproduce:

1. Open a Microsoft Office Word document.
2. (Optional)Type any text.
3. Execute font attributes keystrokes (in Spanish, Control+N/S/K/etc.).

### Actual behavior:

NVDA starts announcing the change in the configured language but Word sends a notification with the attribute name in English and localized status interrupting NVDA, the same as happened with "delete back word" text.
IO - inputCore.InputManager.executeGesture (10:52:07.776):
Input: kb(laptop):control+n
IO - speech.speak (10:52:07.838):
Speaking [u'Negri\xf1a desactivada']
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.uiaDebugLogging (10:52:07.871):
W10: UIA object: <NVDAObjects.Dynamic_WordDocumentEditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject object at 0x054A0DD0>, name: , event: notification, app module: <'appModuleHandler' (appName u'winword', process ID 7392) at address 4d713b0>, automation Id: , class name: _WwG
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.event_UIA_notification (10:52:07.871):
W10: UIA notification: sender: <POINTER(IUIAutomationElement) ptr=0x9f132d8 at 5486760>, notification kind: 2, notification processing: 3, display string: Bold Desactivado, activity ID: AccSN1
IO - speech.speak (10:52:07.878):
Speaking [u'Bold Desactivado']
Note: This happens with winTenApps disabled as well.

### Expected behavior:

NVDA ignores notification and announces changes by itself, or disables these announcements for the most recent Word 2019/365 releases and, despite it is not under our control, Word sends them in the configured language.

#### NVDA installed/portable/running from source:

Portable and installed

#### NVDA version:

2019.3.1

#### Windows version:

Windows 10 Version 1903 (build 18362.720).

#### Name and version of other software in use when reproducing the issue:

Microsoft Office Word 2019 Version 2003 (build 12624.20382), Office 365 License.

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

2019.2.1 - Reproducible

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

N/A

**Comment by josephsl** [comment]
Hi, if the notification text is grammatically incorrect, chances are that Microsoft Office team is using AI-based translation services (I know that Windows Insiders can report translation issues to Microsoft). I’ll generate an add-on snapshot to resolve this (technical: AccSN1 is activity ID to be aware of). Thanks.

**Comment by josephsl** [comment]
Hi,

Windows 10 App Essentials April 7th development snapshot (to be released as version 20.04.1 to stable channel subscribers this week) resolves this. I'll do something about doing it from NVDA side of things also.

Technical: yes, another activity ID to be aware of. In the short term, adding activity ID's would be enough. In the long term, it might be time to revisit announcements of editing functions (implemented a few years ago, perhaps in 2021).

Thanks.

**Comment by Adriani90** [comment]
@ivnc are you still having this issue with NVDA 2024.2 Beta?
Could you please also test with the last alpha of NVDA? This would be very useful.

**Comment by ivnc** [comment]
Yes, it appears to be still reproducible with alpha-32319,dff28c76.
