### ISSUE TITLE
The "Number" symbol is not corectly read when NVDA's display language is set to Romanian

### ISSUE THREAD

**Issue by florianionascu7** [nvaccess/nvda#10951]
When pressing Shift+3, NVDA will say "number" instead of "diez", as the symbol name is translated into Romanian. This issue wasn't in NVDA 2019.2.1 and older, it's present in NVDA 2019.3, 2019.3.1 and 2020.1 beta 1.
Note: The keystroke I mentioned earlier applies to keyboard layouts such as Romanian (Standard), English (United States) and Spanish (Mexico).
### Steps to reproduce:
1. Set NVDA's display language to Romanian.
2. After NVDA says in Romanian "Loading NVDA. Please Wait", press Shift+3 and you'll see that the symbol is read as it is translated into English, though the "Trust Voice's language when processing characters and symbols" checkbox is checked.
### Expected behavior:
NVDA should read this symbol as it is translated into Romanian.
### Actual behavior:
NVDA doesn't do it.
#### NVDA installed:
Yes.
#### NVDA version:
2019.3.1
#### Windows version:
Windows 10 x64, version 1909.
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
As I said above, I also tried NVDA 2019.3 and 2020.1 beta 1.
#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes, but no result.

**Comment by lukaszgo1** [comment]
It is a mistake in Romanian symbols.dic. As hash is used to indicate commends it has to be escaped with `\` not to be threated as such.

**Comment by florianionascu7** [comment]
Hello! Thanks a lot, I didn't knew that. I'll perform a commit containing the fix for this issue.
