### ISSUE TITLE
User Guide: Provide link to Python Regular Expression HowTo in section 12.2.1. Speech dictionaries

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#10958]
### Is your feature request related to a problem? Please describe.

Section 12.2.1. Speech dictionaries of the User Guide notes the ability to use regular expressions in dictionary rules.  It states: 
>Regular expressions are not covered in this user guide, but there are many tutorials on the web which can provide you with more information.

This is true, however different Regex engines work slightly differently from each other.

### Describe the solution you'd like

The user guide should link to the Regular Expression howto document for Python 3.7, which NVDA uses:

https://docs.python.org/3.7/howto/regex.html

### Additional context
(Prompted by email conversation with Damien Garwood)

**Comment by Adriani90** [comment]
Would this not be more suitable for the developer guide? Then we could link to the developer guide in this chapter.

**Comment by JulienCochuyt** [comment]
@Adriani90 wrote:
> Would this not be more suitable for the developer guide? Then we could link to the developer guide in this chapter.

IMHO, it wouldn't. Users willing to configure their speech dictionary might not be interested at all in development.
