### ISSUE TITLE
Support for gender sensitive language in German

### ISSUE THREAD

**Issue by paulkitt** [nvaccess/nvda#10969]
### Is your feature request related to a problem? Please describe.
For now the * or _ is read as 'Leser star innen' or 'Leser underscore innen'

### Describe the solution you'd like
The * or _ should be read as 'Leser Innen'. So instead of reading star or underscore a  glottal stop would be the correct way of speaking the word gender sensitive.

### Additional context
In the German language the most commonly used ways of writing gender sensitive are adding * or _ as in e.g. 'Leser*innen' to words which have a gender form.

**Comment by Adriani90** [comment]
This is already possible:
1. Go to the NVDA menu
2. Open interpunction and symbols
3. in the filter edit field, type the star sign
4. In the list with symbols, choose the star symbol
5. press tab and change the interpunction level in which this sign should be spoken

I recommend to set NVDA to interpunction level "some" and then to switch symbols - which you don't need that often - to another interpunction level via the interpunction and symbols dialog.

Unfortunately there is not possible to create profiles for different interpunctions settings per symbol. But this is another issue.

I will close this one and will create another one targeting the profiles issue.

**Comment by paulkitt** [comment]
Thanks for the fast reply. It would be great if nvda could support gender sensitive by default or have a simple check box enabling gender sensetive language preset configuration. For most people setting up the correct configuration is not easy.

**Comment by Adriani90** [comment]
this is not possible for all languages. this needs a solution individually for every language and the most feasible way is to make a user defined interpunctuation cathegory. 

Von meinem iPhone gesendet
