### ISSUE TITLE
Python 3.8 (porting): "variable is value" aka identity comparison with a literal raises syntax error if warn on error option is specified

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#10966]
Although syntax warning is given, if Python is run with -Werror (convert warnings to errors) switch, the following raises syntax error exception:

### Steps to reproduce:
1. Prepare NVDA from source with `Python 3.7`.
2. If `Python 3.8 32-bit` is installed, install `Python 3.8` versions of `wxPython` (latest `4.1.0 snapshot` is required).
3. Run NVDA from source with errors turned on (`py -3.8 -Werror path/to/nvda/source/nvda.pyw`).

### Actual behavior:
If statement of the form:
`variable is var:`
is encountered, Python 3.8 raises syntax error.

### Expected behavior:
NO errors.

#### NVDA installed/portable/running from source:
Source

#### NVDA version:
master.2d73010

#### Windows version:
Windows 10 Version 2004 (build 19041.172)

#### Name and version of other software in use when reproducing the issue:
Python 3.7.7, 3.8.2 (both 32-bit)

#### Other information about your system:
Being used to test Python 3.8 compatibility

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NO errors in Python 3.7 version of NVDA (including latest alpha snapshot)

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Does not apply

### Motivation for running with errors turned on:
Although syntax warning would suffice in that errors will not be logged, running with errors turned on ensures testing for Python syntax errors that are easily ignored.

### Solution:

Convert instances of "variable is value" statement to "variable {condition} value" statement such as:

* `someStr is value` -> `someStr == value`
* `someNum is not something` -> `someNum != something`

This issue was observed with:

* `buildVersion`: constructing NVDA version string
* `Browse mode`: checking for headers

**Comment by feerrenrut** [comment]
One approach to doing this is to use a custom handler for 2to3. This makes these kinds of conversions much more thorough than a regex based approach because it understands python grammar.

You could check out a fixer I wrote to help [investigate string literals in NVDA](https://github.com/nvaccess/2to3/commit/8c49d86525b63b202cfeb2e6fce8ec2a809d3c39)

In particular the following article was helpful: 
http://python3porting.com/fixers.html#find-pattern

I'd strongly recommend writing a couple of unit tests for your fixer to start with. It is then much easier to work on it iteratively.

**Comment by josephsl** [comment]
Hi,

Investigating both a fixer and regexp route.

For others: context surrounding this issue is explained more thoroughly here:

https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/

Thanks.

**Comment by josephsl** [comment]
Hi,

Actually, there is an easier route: checking for Flake8 error F632. But since this check will take minutes (checking parts of source code), I'll take this route if necessary.

Thanks.
