### ISSUE TITLE
Tables with multi-level headers are not read properly by NVDA

### ISSUE THREAD

**Issue by HerinHentry** [nvaccess/nvda#10963]
Link tested: 
https://www.w3.org/WAI/tutorials/tables/multi-level/#table-with-three-headers-related-to-each-data-cell

Steps:
Using NVDA browse mode (Up and down arrow keys, Ctrl+Alt+Arrow keys) read information on this table.

### Actual behavior:
Row headers are not read properly. All the row headers that are spanned across 5 columns are read repeatedly.
For example:
Availability of holiday accommodation table  with 9 rows and 5 columns 
row 1  Paris Rome  column 1
Studio Paris Rome  column 2
Apt Paris Rome  column 3
Chalet Paris Rome  column 4
Villa Paris Rome  column 5
row 2  Paris Rome  column 1  through 5
Paris 1 bedroom  row 3  Paris Rome  column 1

### Expected behavior:
Only associated headers to be read.

#### NVDA version: 2019.1.1 on Windows 10, Chrome browser

Alternative testing: Tested the same table with JAWS to confirm the code behaviour. It works fine with JAWS.

**Comment by DrSooom** [comment]
@HerinHentry: Which Google Chrome version? And did you test this with Firefox, Edge or other web browsers as well?

**Comment by Adriani90** [comment]
This is reproducible in Crome and edge cromium 81, headers are reported even if you are in the first row. Also all the divisions (Paris, Rome) are reported together, no matter in which divisiona you are navigating.
cc: @aleventhal is there a bug filled with Cromium on this?

Let's continue discussions in #3245.

In Firefox this works as expected.
