### ISSUE TITLE
Advanced system settings: NVDA does not interrupt speech, while tabbing through controls

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#10986]
### Steps to reproduce:
1. In Windows Control Panel, choose System.
2. Choose Advanced system settings.
3. Tab through controls.
#### Actual behavior:
NVDA does not interrupt speech, while tabbing through controls

#### Expected behavior:
NVDA should interrupt speech, while tabbing through controls

Also, NVDA reports "unknown" for tab names in Advanced system settings. It includes:

* Computer name
* Advanced tab
* Hardware tab
* Performance tab:
* remote tab 

#### NVDA installed/portable/running from source:
portable

#### NVDA version:
2020.1beta1

#### Windows version:
Windows 10.0.18362 workstation

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
In NVDA_2019.2.1, NVDA works as expected.

#### If addons are disabled, is your problem still occuring?
Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes.

**Comment by bdorer** [comment]
If you'll read the userguide you'll see that's a limitation of windows with portable versions of NVDA. Please install NVDA and report back.

**Comment by surfer0627** [comment]
@bdorer You're correct. This does not occur in NVDA installed.
