### ISSUE TITLE
Adding new letters in dictionary

### ISSUE THREAD

**Issue by Futyn-Maker** [nvaccess/nvda#10984]
Hello!

I use Russian language in NVDA, and I see that not all synthisizers can read all Unicode symbols. For example, lots of Russian synthesizers default not read Greek alphabet, extended Cyrillic and more.
So, what is the best way to add necessary symbols? I can add them in "symbols.dic", but I'm not sure that it is the best way for letters (not punctuation).

I'd like to add lots of symbols and then share the dictionary to make available speaking this symbols for all Russian synthisizers default in NVDA.

Andrey

**Comment by CyrilleB79** [comment]
I add Cyrillic or Greek letters that are ommitted by the synthesizer in the symbol files. Of course this does not replace a Greek or Russian synthesizer because each Greek or Russian word is then spelt.

**Comment by Futyn-Maker** [comment]
Yes, of course, I understant about synthesizer. I've opened this issue only because at this moment a lot of characters are note spoken by more of Russian synthesizers default, with exception Espeak.
It not only letters, but math characters, Braille unicode and more.
I'm going to add all that symbols in "symols.dic". Could I share it then?

**Comment by zstanecic** [comment]
Hi,

Contact me privately with the suggested change, as I can do the necessary change.

I am currently translating untranslated user guide parts to Russian

My email is

Zvonimirek222@ya.ru <mailto:Zvonimirek222@ya.ru>

**Comment by Futyn-Maker** [comment]
Thanks! I got the answers to my questions, and I can close that issue.
Wait news :)

Andrey
