### ISSUE TITLE
NVDA Community Add-ons website bug: The simplified Chinese name of the Change language combo box is wrong

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#10987]
hello @michaelDCurran 
When using the Change language combo box to switch languages, the simplified Chinese name is wrong.
The correct name should be: Simplified Chinese China (zh_CN
### Steps to reproduce:
Open first
[Welcome to the NVDA Community Add-ons website](https://addons.nvda-project.org/index.en.html)
Then select Chinese / Chinese from the Change language combo box (83%)
### Actual behavior:
The Chinese / Chinese name of Change language combo box (83%) is wrong.
### Expected behavior:
Change the name of the Change language combo box to Simplified Chinese / Chinese (83%).
#### NVDA installed/portable/running from source:
install version
#### NVDA version:
nvda_snapshot_alpha-19938
#### Windows version:
windows10-1909-10.0.18363.720]
#### Name and version of other software in use when reproducing the issue:
chrome: 81
#### Other information about your system:
none
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
none
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Not within the scope of this tool
thanks

**Comment by Adriani90** [comment]
cc: @josephsl, @nvdaes

**Comment by josephsl** [comment]
Hi, It might be due to Ikiwiki unless there is a file in translations workflow that is responsible for this. Thanks.

**Comment by nvdaes** [comment]
Hi, this is something that should be fixed by @michaelDCurran, who requested to be notified about major breaks in the translations system:
https://nvda-addons.groups.io/g/nvda-addons/message/12046
BTW, @jcsteh  documented how to [add a new language for ikiwiki](https://github.com/nvaccess/l10n-code/wiki/Adding-a-New-Language-to-Ikiwiki)

**Comment by feerrenrut** [comment]
@nvdaes Isn't this just a translation error?

**Comment by nvdaes** [comment]
I think thisis a translation error. I mentioned Jamie"s article about adding new languages for reference. Anyway, I am not sure about the location of ikiwiki after the migration of add-ons to GitHub.

**Comment by dingpengyu** [comment]
> Hi, this is something that should be fixed by @michaelDCurran, who requested to be notified about major breaks in the translations system:
> https://nvda-addons.groups.io/g/nvda-addons/message/12046
> BTW, @jcsteh documented how to [add a new language for ikiwiki](https://github.com/nvaccess/l10n-code/wiki/Adding-a-New-Language-to-Ikiwiki)
hi
Currently I cannot get the relevant error log.
thanks

**Comment by nvdaes** [comment]
Don't worry, this must be an error in the website itself, not related to NVDA. Hope this can be fixed soon.
