### ISSUE TITLE
Keyboard shortcut is sometimes not properly read for Java applications

### ISSUE THREAD

**Issue by raducoravu** [nvaccess/nvda#10994]
In a Java application I have a menu item with Ctrl-F6 set as accelerator.
NVDA reads the shortcut as "control plus" without reading the F6 key at all. JAWS properly reads the entire shortcut.

      public static void main(String[] args) {
        JFrame fr = new JFrame();
        JMenuBar mb = new JMenuBar();
        JMenu menu = new JMenu("windows");
        JMenuItem mi = new JMenuItem("abc");
        mi.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F6, KeyEvent.CTRL_DOWN_MASK));
        menu.add(mi);
        mb.add(menu);
        fr.setJMenuBar(mb);
        fr.setSize(500, 500);
        fr.setVisible(true);
      }

**Comment by mwhapples** [comment]
This should be fixed by pull request #13676 and duplicates issue #13643

**Comment by mwhapples** [comment]
Duplicate of #13643

**Comment by mwhapples** [comment]
We should close this now that the duplicate issue is resolved.

**Comment by mwhapples** [comment]
@seanbudd could you close this issue?

**Comment by seanbudd** [comment]
Closed by #13676
