### ISSUE TITLE
NVDA reads 'table' while moving to sign in edit field.

### ISSUE THREAD

**Issue by eDADMSFTChristopher** [nvaccess/nvda#10996]
User Experience:
Screen reader user would face difficulty to understand the structure of the sign in page if screen reader reads table while navigating to sign in screen. NVDA reads 'table' while moving to sign in edit field.

Pre-requisite:
Launch the NVDA

Repro-Steps:
1. Open URL: https://www.office.com/
2. Navigate to 'Sign In' control and select it lying on Welcome to Office window.​
3. Navigate to 'Use another account' and select it.​
4. Navigate to Sign in edit field.
5. Verify the issue.

Actual Result:
NVDA reads 'table' while moving to sign in edit field but there is no table.

Expected Result:
NVDA should not read the 'table' while moving to sign in edit field as there is no table.

Repro-Steps:
1. Open URL: https://www.office.com/
2. Navigate to 'Sign In' control and select it lying on Welcome to Office window.​
3. Navigate to 'Use another account' and select it.​
4. Navigate to Sign in edit field.
5. Verify the issue.

Actual Result:
NVDA reads 'table' while moving to sign in edit field but there is no table.

Expected Result:
NVDA should not read the 'table' while moving to sign in edit field as there is no table.

Test Environment:
OS: Version 1809(OS build 18209.1000)
Browser: Chrome (Version 72.0.3626.119)
Screen reader: NVDA(2018.3.2)

Screen reader: NVDA(2018.3.2)

OS: Version 1809(OS build 18209.1000)

**Comment by josephsl** [comment]
Hi, hmmm, can you try with the following: Version 1909 (OS build 18363), NVDA 2019.3.1, and absolute latest Chrome stable? If any of these fixes it, chances are that it might be Chrome, otherwise it could be a combination of NVDA settings and/or how that page was programmed. Thanks.

**Comment by josephsl** [comment]
Hi,

Confirmed (see #10997). This is the case with Chrome family of browsers (including Microsoft Edge 80) as this issue does not occur in IE and Firefox 75.

Thanks.

**Comment by Adriani90** [comment]
Closing in favor of #10997.
