### ISSUE TITLE
Can we get a rap to top toggle

### ISSUE THREAD

**Issue by brogar2000** [nvaccess/nvda#11008]
### Is your feature request related to a problem? Please describe.
My friend has found himself to be very frustrated while navigating web pages do to the lack of a rap to top feature.
### Describe the solution you'd like
I'd love to see a checkbox in the browse mode settings to toggle weather or not NVDA will jump to the top/bottom when a navigation keystroke is pressed.

**Comment by ruifontes** [comment]
screenRapping  and NVDAExtensionGlobalPlugin


Rui Fontes

We already have, at least, two add-ons with that feature:


Às 23:51 de 14/04/2020, brogar2000 escreveu:

**Comment by feerrenrut** [comment]
Since this functionality is covered by add-ons, I'm going to close this issue.
