### ISSUE TITLE
User Guide line 1459: Typing software is called UniKey (Capital U & K) not unikey / Unikey

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11000]
### Steps to reproduce:

Read line 1459 of the User Guide (Under the Handle Keys from Other Applications heading of the keyboard settings: https://www.nvaccess.org/files/nvda/documentation/userGuide.html#KeyboardSettings )

### Actual behavior:

Text reads: "This option allows the user to control if key presses generated by applications such as on-screen keyboards and speech recognition software should be processed by NVDA. This option is on by default, though certain users may wish to turn this off, such as those typing Vietnamese with the Unikey typing software as it will cause incorrect character input."

### Expected behavior:

The software is called UniKey (capital U and capital K).

#### NVDA installed/portable/running from source:
Either
#### NVDA version:
2020.1 beta 1
#### Windows version:
NA
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

As reported by Vietnamese translator Cuong Dang Manh to translation mailing list.

**Comment by Adriani90** [comment]
Fixed in #11001
