### ISSUE TITLE
Accepting bug-fix / maintenance PR's only while addressing backlog

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#11006]
NV Access would like to kindly ask contributors to temporarily hold off on creating new Pull Requests (PR's) specifically for features or enhancements to NVDA. This will be a temporary arrangement to free us up while we go through the process of addressing the existing backlog of Pull Requests. Many of the outstanding PR's will require significant time to understand, update, test and review for merging. Given that many PR's were initially created long ago, it is easily understandable why many of these are out of date or the author no longer has time to work on them.
 
Why we think a large backlog of PR's is undesirable:
- Increased risk of missing important bug fixes.
- Harder to manage incoming PR's, they easily get out of date.
- Wastes time for contributors, keeping the PR up to date until we have a chance to consider it.
- It's a bad look for the project, it may give the impression the project is no longer active.
- Finally, it wastes time for NV Access, preventing us from getting to other important projects.
 
What the community can do:
- Contributors to please put your efforts towards existing PR's. Many need updating and testing. Effort to make these PR's as easy to understand as possible will significantly help to speed up this process.
- Look at issues linked to the existing PR's, see if the problems they describe are still reproducible.
- Continue to contribute (high priority) bug fixes or maintenance pull requests, we will continue to accept these. To avoid having your Pull Request closed, please contact us before starting work if you are uncertain how we will categorize it. To help understand our categorization, all existing PR's have been labelled as either bug, maintenance, enhancement, or feature.
 
Our goal is to get our [list of non-draft unblocked PR's](https://github.com/nvaccess/nvda/pulls?q=is%3Apr+is%3Aopen+-is%3Adraft+-label%3Ablocked) down to just a handful of the newest issues

Thanks for your patience.

**Comment by dingpengyu** [comment]
[Accepting bug-fix / maintenance PR's only while addressing backlog](https://github.com/nvaccess/nvda/issues/11006)

**Comment by leonardder** [comment]
Is this issue still relevant as of today?

**Comment by cary-rowen** [comment]
I hope to see further development of NVDA, and the GSOC19 list hopes to be realized soon

**Comment by seanbudd** [comment]
> Is this issue still relevant as of today?

NV Access feels like it is appropriate to lift this freeze now as the backlog has been somewhat reduced, and is unlikely to shrink much further in the near future.

**Comment by seanbudd** [comment]
Thanks @ExpandingS - I've updated that page
