### ISSUE TITLE
NVDA crashes when reading e-mail addresses

### ISSUE THREAD

**Issue by alexbernier** [nvaccess/nvda#11012]
Hi,
NVDA often crashes when accessing text containing e-mail addresses. It occurs when using a Braille display with the "français unifié abrégé" (french contracted) table. I suspect the problem could be related with LibLouis but do not investigate more for the moment. 
Attached is the relevant part of the log file.
Best,
Alex
[nvda-old.log](https://github.com/nvaccess/nvda/files/4481325/nvda-old.log)

**Comment by Adriani90** [comment]
please fill the template completely. Thanks.

**Comment by Brian1Gaff** [comment]
Also for others as well you will often find that if you grab the template 
its actually easier to fill out externally then uploaded to the blank field 
after deleting the template  in the edit field. Depends on the latency , but 
works for me.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----
