### ISSUE TITLE
NVDA running from source not possible strange behavior

### ISSUE THREAD

**Issue by christopherpross** [nvaccess/nvda#11016]
NVDA run from source here is not possible, it exit after start and produces no errors. I don't know whats going wrong here on my system, but I want to report this, maybe I do somethink wrong or it is a edge case.

### Steps to reproduce:
- Install Python 3.7.7 (32 bit)
- fork the current nvda-repo and clone it
- then follow the instructions in the readme.md to prepare the sourcetree and make sure the depentencys are currect.
- pass the scons source command succesful
- enter ```pythonw.exe nvda.pyw --debug-logging --disable-addons```

### Actual behavior:
for me, I hear the start up sound, serial short beeps, last two high quck ones. then nothing. In the taskmgr, mvda or pythonw, is not present anymore. In the cmd is no output. The nvda.log is in the file appended to this issue here.

### Expected behavior:
Well, running from source... NVDA should run...
#### NVDA installed/portable/running from source:
running from source (master)
#### NVDA version:
source-master-72ee0b9
#### Windows version:
10.0.18363
#### Name and version of other software in use when reproducing the issue:
-------
#### Other information about your system:
Visual studio and all the stuff is installed. 
#### Does the issue still occur after restarting your computer?
yes, serial restarts tried 
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
not yet 
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
not possible, but in the main nvda, yes
#### Did you tried to execute NVDA with python.exe and not with pythonw.exe?
yes, same bevavior.
[nvda.log](https://github.com/nvaccess/nvda/files/4483406/nvda.log)

**Comment by feerrenrut** [comment]
Could you test the latest alpha snapshot:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by christopherpross** [comment]
Yeah, it is now working. Thx. And sorry for this.
