### ISSUE TITLE
NVDA often crashes when reading e-mail addresses

### ISSUE THREAD

**Issue by alexbernier** [nvaccess/nvda#11013]
### Steps to reproduce:

Move the Braille display on a text containing an e-mail address

### Actual behavior:

NVDA crashes.
 It occurs when using a Braille display with the "français unifié abrégé" (french contracted) table. I suspect the problem could be related with LibLouis but do not investigate more for the moment. Attached is the relevant part of the log file.

### Expected behavior:

Correctly displays the text and continue to run.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.3

#### Windows version:

Windows 10

#### Name and version of other software in use when reproducing the issue:

N/A

#### Other information about your system:

N/A

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes
[nvda-old.log](https://github.com/nvaccess/nvda/files/4481855/nvda-old.log)

**Comment by alexbernier** [comment]
NVDA version: 2019.3.1

**Comment by Andre9642** [comment]
Probably related to https://github.com/liblouis/liblouis/issues/881

**Comment by alexbernier** [comment]
Thanks @Andre9642 - I confirm it seems to be related to the issue you pointed.
To reproduce:
- Enable the french contracted table
- On a line of text, write "a: b.c"
- Move the cursor at the beginning of the line and next move it on the right several times
- NVDA (actually LibLouis) crashes

**Comment by Andre9642** [comment]
Temporary quick fix (breaks some rules): edit 'fr-bfu-g2.ctb' file and comment the line "noback compbrl \xfff9" by adding a '#' at the beginning of the line.

**Comment by Adriani90** [comment]
Closing as fixed by the referenced PR above
