### ISSUE TITLE
Control+Delete doesn't report the word being deleted

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#11029]
### Steps to reproduce:
Simply open a Word document, a file in Wordpad, a new message in Thunderbird, etc. and start typing some words. Move a few words backwards via Control+Left. Now try deleting words to the right of the cursor with Control+Delete.
### Actual behavior:
NVDA remains silent as each word gets deleted via Control+Delete.
### Expected behavior:
NVDA should echo the deleted word, or the portion of it which is being deleted.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-20005,14c2e2ec, but also reproducable with 2019.3.1.
#### Windows version:
Win 10 Pro 64-Bit Version 2004 (OS Build 19041.207)
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Up to 2019.3 and 2019.3.1.
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No, as it doesn't presumably affect this issue.

**Comment by jacobchawala** [comment]
sure. It happens the same even in my Microsoft-Wore. for me, not only CTRL+Delete but also CTRL+backspace. no deleted word is spoken whether by pressing CTRL+Delete or CTRL+backspace. when pressing these hot keys, they should echo the deleted word. for instance, if you delete the word this by pressing CTRL+backspace, NVDA should say "delete back word this; when pressing CTRL+Delete, NVDA should say, Delete forward word this.

**Comment by feerrenrut** [comment]
I have a feeling this is because the caret does not move when using ctrl + delete, however it does when pressing ctrl+backspace.

**Comment by amirsol81** [comment]
Quite interestingly, the NVDA Global Plug-in, an NVDA Add-on, has an option for fixing this which works very well.

**Comment by Adriani90** [comment]
I just want to mention that addon has some fixes but it is not an official addon and has not passed the review. That addon is very comprehensive and has other conflicts with different NVDA features, key strokes etc. This addon is used only by a limited number of users worldwide.

**Comment by amirsol81** [comment]
So I hope the issue is fixed via NVDA itself in the near future.

**Comment by feerrenrut** [comment]
Perhaps someone can look at how that add-on fixes the problem and submit a PR.

**Comment by paulber19** [comment]
Hi,
I am the author of this add-on and I am very attentive to any report of 
problems encountered by it use.
However, I have not so far reported to you those you mentioned.
Those reported during the review for acceptance by the community were 
resolved long ago.
If there are any left, I will be happy to correct them.
You said:
 >This addon is used only by a limited number of users worldwide.
I would like to know how you measure it and is this statement really 
valid to judge the value or usefulness of an add-on?
Best regards.
Sorry for my bad english (Principal problem for review aggrement)
Paul.

**Comment by feerrenrut** [comment]
@paulber19 please don't start add-on review discussions here. The NVDA add-on mailing list is a better place to have this conversation and ask these questions. Of course you can link to this issue to give people context. I'm going to hide these comments to keep discussion on track.

**Comment by paulber19** [comment]
OK. I understand.
I'm very sorry.
Please also hide the email to which I replied.
Best regards.
Paul.

**Comment by JulienCochuyt** [comment]
@jacobchawala wrote:
> sure. It happens the same even in my Microsoft-Wore. for me, not only CTRL+Delete but also CTRL+backspace. no deleted word is spoken whether by pressing CTRL+Delete or CTRL+backspace. when pressing these hot keys, they should echo the deleted word. for instance, if you delete the word this by pressing CTRL+backspace, NVDA should say "delete back word this; when pressing CTRL+Delete, NVDA should say, Delete forward word this.

When attempting to solve this by PR #11315, I've concentrated on handling `control+delete` where `control+backspace` was already properly handled - which includes eg. Microsoft Word.
If you indeed identified a case where `control+backspace` is not handled, or neither are, please file a dedicated issue so we can look into it.
