### ISSUE TITLE
Installer not starting up

### ISSUE THREAD

**Issue by cablegunmaster** [nvaccess/nvda#11021]
### Steps to reproduce:
1. Download a NVDA version from the website
2. Start the setup.
### Actual behavior:
Please wait while loading setup shows.
After this nothing is happening, and the setup does not continue.
this happens on all versions of the installer. (whether the setup has elevated rights or not).

After several attempts I get this message when windows 10 does a troubleshooter:
An unexpected error has occured. The troubleshooting wizard cant continue. (anywhere I can find the logs?)

Error code: 0x80070057
Source: Command line
Context: Elevated (with administrator rights).

Most probable issue:
- Something goes wrong with extracting the setup file?

### Expected behavior:
Actually install the software, popup a license agreement, installation options?

Workaround 1 : 
1. Extract the setup file using 7zip, and look for the nvda_uiAccess.exe to start the program.  
2. Look for the icon in the right below next to the taskbar and click on tools-> install NVDA
3. restart the computer.
4. start up nvda.exe found in C:\Program Files (x86)\NVDA\nvda.exe

Workaround 2 :
1. look for a older version? Where?
https://www.filehorse.com/download-nvda/old-versions/
I found some link containing older versions , but not sure if this is from the official website.

#### NVDA installed/portable/running from source:
official website -> press download button.

#### NVDA version:
Not relevant, installer issue.
#### Windows version:
Windows 10 pro
Version 10.0.18363 Build 18363
#### Other information about your system:
Running Windows 10 pro on a Laptop.

#### Does the issue still occur after restarting your computer?
Yes still occuring.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes its happening on all versions.
#### If addons are disabled, is your problem still occuring?
Fresh installation.

**Comment by Adriani90** [comment]
This error occurs mostly when a partition has damage or when an windows update has not been installed completely. I guess NVDA cannot really detect your Windows version when you start the setup.
Try to update your Windows first and try to install NVDA again after that.
I think this issue is not really an NVDA issue.

**Comment by Adriani90** [comment]
Also try to run the setup as administrator.

**Comment by cablegunmaster** [comment]
- Try to update your Windows first 
The windows version is said to be the latest version.
 - Try to run the setup as administrator.
Same issue.

**Comment by DrSooom** [comment]
Install or update the sound card driver. … Maybe irrelevant if NVDA Portable already starts correctly.

**Comment by DrSooom** [comment]
Additional question: Which security software is installed? Temporary disable it while you're installing NVDA.

**Comment by cablegunmaster** [comment]
> Install or update the sound card driver. … Maybe irrelevant if NVDA Portable already starts correctly.
The sound card driver is working perfectly, Is there a log file I could look into when the installer is not booting up?  I am helping/debugging this in the hope its either a installer issue or a windows 10 issue.

The software itself is working with the work around as normally intended, but still in the future when new releases come out, I dont want to have this same issue:  installer shows and dissapears and thats it.

![image](https://user-images.githubusercontent.com/8159246/79963614-e96f6880-8489-11ea-9bcd-f84ccda4d0e4.png)

> Additional question: Which security software is installed? Temporary disable it while you're installing NVDA.

I deinstalled malwareBytes and only have windows defender and got the same issue.

**Comment by leonardder** [comment]
I've seen this in some circumstances:

* A system with a very low amount of available RAM
* A system with insufficient free system drive space
* A system with insufficient rights to write to the temporary folder. i think the latter isn't the case on your system.

Have you been able to reproduce this on other systems as well? Note that you can always start an installer from a portable copy by choosing the install option from the tools menu. The failing part on your end is the NVDA launcher.

**Comment by cablegunmaster** [comment]
> I've seen this in some circumstances:
> * A system with a very low amount of available RAM
This is not the case, 12 GB seems sufficient.
> * A system with insufficient free system drive space
276 GB free on my C:\ disk.
> * A system with insufficient rights to write to the temporary folder. i think the latter isn't the case on your system.
How can I check if this is the case? 
And why is this also happening when I give the program permissions as an administrator?

> Have you been able to reproduce this on other systems as well? 
Its only failing on the laptop.

>Note that you can always start an installer from a portable copy by choosing the install option from the tools menu. The failing part on your end is the NVDA launcher.
- Yeah, that was basically my workaround option :)  in my OP.
I am still debugging this because I want to know how to change my PC to make the installer also work.
Is there a Log file I can look into?

**Comment by Adriani90** [comment]
Could you please set the UAC level to 0 and try again?

Von meinem iPhone gesendet

**Comment by cablegunmaster** [comment]
![useraccountcontrolsettings](https://user-images.githubusercontent.com/8159246/79969019-360a7200-8491-11ea-828b-687dd7cdba54.jpg)
This was what I had it on the normal default setting on windows 10.
Changing it to the lowest (not recommended) setting does not make the installer appear.
I am going to reboot to be sure. and make a new windows profile (maybe this windows profile is bugged?)

**Comment by cablegunmaster** [comment]
Issue came down to: Windows profile is bugged. 
Solution create new windows user profile.

**Comment by leonardder** [comment]
While the issue is solved for you, I think something has to be done about this. If NSis generates an error of some sort, we somehow need to be able to access that.

**Comment by cablegunmaster** [comment]
So this leaves me to how to access the NSIS logs does it generate any?

**Comment by DrSooom** [comment]
@cablegunmaster: Sorry, I forgot to mention: https://www.nvaccess.org/category/news/releases/

**Comment by cablegunmaster** [comment]
> @cablegunmaster: Sorry, I forgot to mention: https://www.nvaccess.org/category/news/releases/
I am sorry ? I am trying to understand this one line. 
What does this have to do with the installer not being shown?

For this pc and user account; It is happening on all versions (tested from 3.1 backwards).
I am switching over my windows profile to another one and keep this one for you guys, just for debug purposes. If you got any debug solutions / please comment.

**Comment by Adriani90** [comment]
maybe this is related to #9178.

**Comment by DrSooom** [comment]
@cablegunmaster: It belongs to:
> Workaround 2 :
> 1. look for a older version? Where?
> https://www.filehorse.com/download-nvda/old-versions/

**Comment by cablegunmaster** [comment]
Since no one other as me had this issue and or not required to fix ill close this issue until needing otherwise.

**Comment by feerrenrut** [comment]
>While the issue is solved for you, I think something has to be done about this. If NSis generates an error of some sort, we somehow need to be able to access that.

I think there are a couple of things we could do to improve the installer logging:
- Write the launcher log to a different file name (eg nvda-launcher.log) to make it easier to identify and recover.
- Ensure that logging level can be given to the launcher as a command argument (or use NVDA config value)
- Investigate logging and getting error codes from NSIS installer.
