### ISSUE TITLE
NVDA controller client: allow choosing speech prioiryty when speaking

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#11028]
### Is your feature request related to a problem? Please describe.
External software can use the NVDA controller client library to make NVDA announce text. This is used by twitter clients like TWBlue and Chicken Nugget, for example. This functionality is also used internally, for example by the live region handler.

However, the new speech priority support is not added to the NVDA controller client. It would be helpful if it were,  See #10622 for a use case.

### Describe the solution you'd like
I propose adding a nvdaController_speakTextEx function that adds:

* An enum parameter for the speech priority
* A boolean value that allows one to cancel speech before speaking. I think it should only cancel speech within the speech queue of the given priority. If someone wants to cancel all the speech, they can use nvdaController_cancelSpeech instead.

### Describe alternatives you've considered
Add these new parameters to nvdaController_speakText. I'm afraid this can't be done without breaking backwards compatibility though. Could you confirm this @michaelDCurran?

**Comment by feerrenrut** [comment]
Related: #9079
