### ISSUE TITLE
CELA P1_A11y_code.visualstudio.com_VisualStudioCode_CodeEditingRedefined_Keyboard: Tooltip is missing for non text content other platform and insiders edition button.

### ISSUE THREAD

**Issue by mspatil110** [nvaccess/nvda#11042]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:**#CELAP1_A11y_code.visualstudio.com;#A11ySev2;#A11yTCS;#A11yMAS;#Benchmark;#ChromiumEdge;#DesktopWeb;#MAS1.1.1;#Win10;#Visual Studio Code;#CELAP1_code;#ColorContrast;

**Environment Details:**
Application Name: code.visualstudio.com
#URL:https://code.visualstudio.com/docs/python/python-tutorial
Windows Version: Windows10
Browser version: Microsoft Edge Version 81.0.416.60 (Official build) beta (64-bit)

**Repro Steps:**
1)Launch the application url :https://code.visualstudio.com/
2)Visual Studio Code will get open.
3)Go through "Code editing Redefined".
4)Navigate up to other platform and insiders edition button and observed that tool tip is present for this non text content or not.

**Actual:**
Tooltip is missing for non text content other platform and insiders edition button.

**Expected:**
Tooltip "other platform and insiders edition" should be present for non text content other platform and insiders edition button.

**User Impact:**
Keyboard only user will face difficulty to understand the button without tooltip.

**Attachment link for Reference:**

[11042_CELA P1_A11y_code.visualstudio.com_VisualStudioCode_CodeEditingRedefined_Keyboard.pptx](https://github.com/nvaccess/nvda/files/4510352/11042_CELA.P1_A11y_code.visualstudio.com_VisualStudioCode_CodeEditingRedefined_Keyboard.pptx)

**Comment by khansahab15** [comment]
GitHubTags:#P1_A11y_April2020

**Comment by akash07k** [comment]
So, how is it related to NVDA?

**Comment by fsteffi** [comment]
GithubTags:#P1_A11y_April2020;
