### ISSUE TITLE
Chromium browsers: report typed words does not work correctly when adding a line break

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#11059]
### Steps to reproduce:
1. Open a web page with a multi line edit field in Google Chrome or Edge Chromium, i.e. this issue with its comment area
2. In NVDA's keyboard settings, enable "report typed words"
3. In the multiline edit field, type:
>>>
This is line one
this is line two
>>>

### Actual behavior:
NVDA reports the previous lines whenever you add a line break with enter.

### Expected behavior:
NVDA should report only the last word of the previous line when adding a line break with enter.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-20045,a335297e

#### Windows version:
Windows 10 1909 Update

#### Name and version of other software in use when reproducing the issue:
Google Chrome 81, Edge Chromium 81

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If addons are disabled, is your problem still occuring?
yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes, no effect for this issue.

#### other information
This issue occurs only in Chromium browsers.
cc: @leonardder

**Comment by feerrenrut** [comment]
Can you test the previous release and report if this is a regression please?

**Comment by mohammad-suliman** [comment]
This is a Chromium issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=1044410

It will be fixed in Chrome 83 witch is supposed to be released in mid may I
think.

**Comment by ObjectInSpace** [comment]
Can confirm this does not reproduce as of Chrome 83.

**Comment by Adriani90** [comment]
Thank you guys for the good work on this. It works in Chromium browsers now, tested with NVDA alpha-20220,1c4519a6, Chrome 83 and Edge Chromium 83.
