### ISSUE TITLE
Upgrade wxPython to 4.1.1

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#11056]
Hi,

Update: originally 4.1.0, but wxPython 4.1.1 was released on November 25, 2020, hence the change of title and content. Unless requested, subsequent comments below refer to 4.1.0.

This issue serves as both a meta issue and a concrete one.

### Is your feature request related to a problem? Please describe.
wxPython 4.1.0 was released on April 24, 2020, with 4.1.1 released about seven months later (November 2020). Besides internal changes to use wxWidgets 3.1.x (master branch), wxPython 4.1.1 includes the following:

* More useful notification message handling.
* Deprecated code paths.
* Python 3.8 compatibility.
* Others to be discovered.

As updating to Python 3.8 and future 3.x releases require dependency checks, wxPython 4.1.1 fulfills the first dependency check (the other major ones include SCons and Py2exe unless a much better packaging tool is found; update: Py2exe supports Python 3.8 and 3.9 as of November 2020).

### Describe the solution you'd like
Upgrade to wxPython 4.1.1.

### Describe alternatives you've considered
None.

#### Blockers:
NVDA's own commands cannot be performed if NVDA menu is open. Also. NVDA may not appear to respond when a message dialog opens.

#### Past or mitigation possible:
There exists an issue in wxPython 4.1.0 where if one calls wx.Locale().Init, it changes locale and encoder seen by Python, which causes text processing to fail. The issue was traced to two areas: wxPython calling wx.App.InitLocale when an app is instantiated (can be mitigated by defining wx.App.OnPreInit), and InitLocale itself which tells wxWidgets to set the CPython locale to be in sync with wxWidgets locale.

Thanks.

**Comment by dingpengyu** [comment]
hello josephsl
Is it possible to use inno setup to package NVDA?
thanks

**Comment by ultrasound1372** [comment]
Did WXPython 4.1.0 fix the strange naming bugs that we started encountering in 4.0.4 and up to 4.0.7? People I know that develop apps are still using 4.0.3 because of this change, I think it's in WXWidgets and involves what accessible names controls get. Some change made it so you have to specify those specifically with accessible naming instead of just defaulting to the standard name, least that's what I think happened, and usually crops up on list controls and the like, simple things like buttons are not affected.

**Comment by josephsl** [comment]
Hi, yes resolved. There are more important things to look at though: I spent at least two days trying to work out more important issues with wxPython 4.1.0, namely NVDA freezing in message boxes, localization support and so on. Thanks.

**Comment by leonardder** [comment]
I'm strongly opinionated towards blocking this by #8679.

**Comment by feerrenrut** [comment]
Yep, agreed. Also added #8679 to the Python 3.8 project.

**Comment by josephsl** [comment]
Hi,

Update after six months: as wx.Yield is no longer considered deprecated (although we would like to find a workaround), I think it would be best to move forward with this dependency. If not done, a separate comment will be added regarding wxPython 4.1.x issues.

As for wx.InitLocale, resolved somewhat in 4.1.1-dev.

Thanks.

**Comment by feerrenrut** [comment]
>as wx.Yield is no longer considered deprecated

@josephsl please clarify, is it removed, or reinstated?

**Comment by josephsl** [comment]
Hi, nope, it’s still there in wxWidgets/wxPython (no deprecation message, so we can say that it is reinstated). Thanks.

**Comment by leonardder** [comment]
> Hi, nope, it’s still there in wxWidgets/wxPython (no deprecation message, so we can say that it is reinstated). Thanks.

Deprecating something and then undoing the deprecation is a bit weird. It would help to have a bit of documentation/rationale about reversing this.

**Comment by josephsl** [comment]
Hi,

Based on the following:
https://docs.wxwidgets.org/trunk/group__group__funcmacro__appinitterm.html#gac386c89a04e364afc07edce6d848c27a

This is because wxPython 4.1.x is based on wxWidgets master branch, which had a commit that notes that wxYield is not deprecated.

Thanks.
