### ISSUE TITLE
Texts with multiple line spacings are voiced with NVDA + down arrow and voices crack

### ISSUE THREAD

**Issue by SeanTolstoyevski** [nvaccess/nvda#11061]
### Steps to reproduce:
1. Create text as follows in the notepad.
```
test




test 123 123


test 111




test   ooooooo




test one



test two





teeest


wauw







test




test 123 123


test 111




test   ooooooo




test one



test two





teeest


wauw






test




test 123 123


test 111




test   ooooooo




test one



test two





teeest


wauw

```
2. Go to the beginning of the text.
3. Press the NVDA + down arrow.

### Actual behavior:

Voices crack in some places.

#### NVDA installed/portable/running from source:
installed
#### NVDA version:

2019.3.1

#### Windows version:

windows 10 pro, 64 bit, 18363.778

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Tested with versions after 2019.3.1.
Sounds are cracking.
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by fisher729** [comment]
Hi.

Which synthesizer is in use here? I can confirm a small crackle when using eSpeak, but I'm not sure if continuous reading of long text can cause this in eSpeak under normal circumstances, as I don't use it on the regular.

**Comment by SeanTolstoyevski** [comment]
Synthesizer is Espeak.

**Comment by Adriani90** [comment]
I can reproduce this only with eSpeak, and there also depending on which variant you are using. for example using Variant Quincy there is much less crackling than using for example variant "Robert".
I am not sure if NVDA can do something about this. The sound of the voices are comming actually from the eSpeak project. I suggest you to open also an issue on github to their repository at
https://github.com/espeak-ng/espeak-ng

This issue might also be due to the sonic library used by eSpeak as the underlying driver. Maybe reporting this to the developer of Sonic driver would help as well.

**Comment by amirsol81** [comment]
As much as I tried, I had no luck breaking Eloquence, Windows OneCore, and eSpeak set to Persian which is based on British English, which, IMO, means good luck this time around.

**Comment by feerrenrut** [comment]
This may be improved by: #11024 which has a [build you can test with](https://ci.appveyor.com/api/buildjobs/scexo5rpqllcsx7w/artifacts/output%2Fnvda_snapshot_pr11024-20018%2Caa38fb32.exe). Note that this build still has some issues, this PR is still only a draft.

**Comment by SeanTolstoyevski** [comment]
OK,

I will share this issue on Espeak.
Maybe it's Espeak's problem.

I will write the result here.

**Comment by SeanTolstoyevski** [comment]
Hi NVDA Team, I hope you are fine.

I shared Issue on Espeak.
There is no problem in Espeak.
But I can't be sure about this because Espeak pauses between the lines.
NVDA skips between the lines and voices like a straight line.
Additionally, the problem is felt more when Boost on is active. So sounds are cracking more.
I know almost nothing about Espeak and synthesizer. My knowledge is very little.
So I don't think I can say anything exactly.

Issue is here.
Maybe you can write to Espeak for a better test.:
https://github.com/espeak-ng/espeak-ng/issues/742

**Comment by Adriani90** [comment]
This might also be related to #7769.

**Comment by tspivey** [comment]
Simpler STR:
1. Set eSpeak to voice English (Great Britain), variant none, rate 20, rate boost on.
2. Read this with notepad and say all:
```
equals

The room
```

Note that this doesn't happen with 2019.2.1.

**Comment by SeanTolstoyevski** [comment]
hi @tspivey ,

I finished the last test.

Sound cracks in 2020.2.

Unfortunately, I often have to run 2019.3 as portable.
I cannot read a book. Cracking sounds disturbing.

And english :) . **Sound, audio, voice**...
It's a complex subject for someone whose native language is not English.
I hope you can understand me.

**Comment by Adriani90** [comment]
Could you please test with the last alpha version which has been issued today?

 

 

Von: SeanTolstoyevski <notifications@github.com> 
Gesendet: Sonntag, 9. August 2020 22:33
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Texts with multiple line spacings are voiced with NVDA + down arrow and voices crack (#11061)

 

hi @tspivey <https://github.com/tspivey>  ,

I finished the last test.

Sound cracks in 2020.2.

Unfortunately, I often have to run 2019.3 as portable.
I cannot read a book. Cracking sounds disturbing.

And english :) . Sound, audio, voice...
It's a complex subject for someone whose native language is not English.
I hope you can understand me.

**Comment by tspivey** [comment]
Test results: My example still breaks.

**Comment by Adriani90** [comment]
cc: @jcsteh maybe you have some thoughts on this?

**Comment by jcsteh** [comment]
This is related to the indexes (or marks) sent to the synthesiser for cursor tracking, accurate synchronisation of sounds and synth changes, etc. Say all uses these to mark each line for cursor tracking. However, it did this in 2019.2 as well.

There are a couple of possibilities:

1. We're now sending more indexes than we used to and eSpeak chokes on that for some reason. To determine that, we'd need to look at the markup sent to eSpeak between 2019.2 and a current release. We're probably sending at least one more index than we used to.

2. In 2019.2, we sent indexes and then polled periodically to see whether an index had been reached. The problem with that is inaccuracy; it's (mostly) acceptable for say all, but totally unacceptable for synchronisation of sounds, etc. Now, we send the audio in such a way that we get accurate callbacks when an index has been reached. However, it's possible this might lead to a situation where a chunk of audio is too small, so the next chunk isn't ready yet by the time the previous chunk is finished (buffer underrun). That will cause audio glitches.
    The question is why that's occurring here. Some of these chunks are probably pretty short, but they shouldn't be short enough to reliably cause buffer underrun.
    To figure out whether this has something to do with our audio code and not eSpeak, we could try preventing _feedUnbuffered from being called when onDone is provided, though this would completely break indexing and I'm not sure how well SpeechManager would cope with that.
    If it is our audio code, I'd start by looking at the sizes of buffers being pushed into `nvwave.WavePlayer._feedUnbuffered`. If we're getting some really small chunks there, we want to know why, perhaps starting at `nvwave.WavePlayer.feed` and working backwards from there.

**Comment by jcsteh** [comment]
It's also possible it's a combination of 1 and 2; i.e. this isn't an eSpeak bug, but we are sending two indexes very close together for some reason and that causes a buffer underrun. That raises the question of why we're sending indexes so close together. Either way, I think it's worth looking at the markup being sent to eSpeak.

**Comment by SeanTolstoyevski** [comment]
Well I have a question:
We need a lot of threads for these operations / topics  and Python is not powerful enough in this regard.

I want to change things and get a performance boost using **"nogil" with Cython**.
However, when I compile any module, I get an error stating that the module could not be found. (ie .pyd file).

Are c extensions acceptable for NVDA's source?
So if I do something that can solve many problems like this, will NVDA accept the Cython contribution?

**Comment by josephsl** [comment]
Hi, not that I’m opposed to this (we had a long discussion about Cython a while back), but I think it would be better to focus on one thing at a time (mental health takes priority). Thanks.

**Comment by jcsteh** [comment]
Actually, NVDA uses only a single background thread for synths and audio. I very much doubt the GIL is the bottleneck here. Of course, if you can prove otherwise, that's good info to have and solutions can then be considered... but let's work out the root cause before diving into solutions that may well not fix the problem.

**Comment by SeanTolstoyevski** [comment]
I'm not sure about that.

When I test with Python's performance profiler, I can see 30-40 ms delay for some functions.

I will do something. I will inform you about this when I move to the city.
