### ISSUE TITLE
Allow splitting of translatable strings

### ISSUE THREAD

**Issue by codeofdusk** [nvaccess/nvda#11071]
The translation system should allow strings to be split across lines. See https://github.com/nvaccess/nvda/pull/10941#issuecomment-620622703

### Summary of the problem

When a translation string is too long (generating a flake8 error) there is no way to reformat it to avoid the flake8 warning and such that the translation system picks up the string and translation comment correctly.

The following gives an error `ET113 (flake8-tabs) option continuation-style=hanging does not allow use of alignment as indentation`

```python
label=(
	# Translators: blah
	_("Use currently saved settings on the logon and other secure screens"
	" (requires administrator privileges)")
)
```

Really the translation system should handle one of the following:
```python
# Translators: blah
label=_(
		"Use currently saved settings on the logon and other secure screens"
		" (requires administrator privileges)"
	)
```
```python
label=_( # Translators: blah
		"Use currently saved settings on the logon and other secure screens"
		" (requires administrator privileges)"
	)
```

### Work around for now
For now just disable the "line too long" error. EG:
```python
label=(
	# Translators: blah
	_("Use currently saved settings on the logon and other secure screens (requires administrator privileges)")  # noqa: E501 line too long
```

### Other notes
Check the pot file in `output` directory. Ensure that translator comment and string are available. 

### Questions
Are split strings the pot file handled correctly? EG the following pot file entry:
Note that `msgid` starts with empty string, then two more strings on new lines:
```
#. Translators: The label for a button in general settings to copy current user settings to system
#. settings (to allow current settings to be used in secure screens such as
#. User Account Control (UAC) dialog).
#: gui\settingsDialogs.py:735
msgid ""
"Use currently saved settings on the logon and other secure screens (requires "
"administrator privileges)"
msgstr ""
```

**Comment by JulienCochuyt** [comment]
@codeofdusk, you were almost there with your second example. Try this:
```
label=_(
	# Translators: blah
	"Use currently saved settings on the logon and other secure screens"
	" (requires administrator privileges)"
)
```

Note the translator comment itself can also fit on multiple lines and still get extracted correctly.
Reference: (https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/xgettext-Invocation.html#Operation-mode)
In this manual, the sentence
> The second comment line will not be extracted, because there is one blank line between the comment line and the keyword.

should probably read **literal** instead of **keyword** (Any volunteer to raise this upstream?)

**Comment by feerrenrut** [comment]
Looks like the fix for this issue is to update the NVDA developer documentation. Thanks for the extra info @JulienCochuyt

**Comment by feerrenrut** [comment]
Though there was one case (see the PR where this showed up) where checkPot did not catch a missing translation string. That could also be looked at.

**Comment by JulienCochuyt** [comment]
@feerrenrut,
I couldn't find any mention of translators comments in the Developer Guide.
I updated the [Contributing wiki page](https://github.com/nvaccess/nvda/wiki/Contributing) with the example of PR #10941 (maybe not the most straight-forward example, though...)

`tests/lint/readme.md` would probably also benefit from an update on that matter.
