### ISSUE TITLE
NVDA crashes / becomes totally unresponsive when replying to a message in Outlook 365

### ISSUE THREAD

**Issue by behofer** [nvaccess/nvda#11070]
### Steps to reproduce:
1. Open Outlook for Office 365.
2. Compose a message or replying to one.
3. When writing text / navigating through entered text sometimes NVDA gets stuck and totally unresponsive so that no speech output is generated anymore and braille display isn't refreshed anymore.
4. NVDA must be re-launched.

### Actual behavior:
When composing a message or replying to one in Outlook 2016, NVDA sometimes becomes totally unresponsive.
From a user's point of view, it's like NVDA would crash as no output (speech, braille, tones) is generated anymore.
The issue doesn't occur regularly (every time a message is composed, every day, especially in case of large messages etc.). I didn't find a way of reproducing itt reliably.
But in my environment, it occurs on a weekly or sometimes daily basis.
Please see 2 attached log files for more information and insight:
[nvda-old-20200429_1.log](https://github.com/nvaccess/nvda/files/4552754/nvda-old-20200429_1.log)
[nvda-old-20200429_2.log](https://github.com/nvaccess/nvda/files/4552756/nvda-old-20200429_2.log)

As no dump file is generated in %temp% folder, I assume that NVDA doesn't really crash but becomes unresponsive which is from a user's point of view hardly different.

### Expected behavior:
NVDA should "work as usual" when the issue doesn't occur. So it should response to text input and follow the cursor in the input field.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.1.beta1
2019.3.1

#### Windows version:
Microsoft Windows 10 Enterprise Version	10.0.17763 Build 17763

#### Name and version of other software in use when reproducing the issue:
Microsoft Outlook for Office 365 MSO (16.0.11929.20436)

#### Other information about your system:
No other relevant information.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Same behaviour for: NVDA 2019.3.1 / NVDA 2019.2

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Running the COM registry fixing after the issue occurs isn't possible as NVDA is unresponsive and must be re-launched.

**Comment by DrSooom** [comment]
Duplicate of issue #10247.

**Comment by Adriani90** [comment]
Closing as duplicate.

**Comment by feerrenrut** [comment]
@behofer Can you tell us the language you have configured for the following:
- For Windows (settings -> language)
  - Windows display language
  - Windows preferred language
- For Office (via File -> Options -> Language)
  - Office Display language 
  - Office Authoring language


@Adriani90 @DrSooom We have not been able to reproduce many of these serious issues with Office. One theory we have is based on it appearing to occur more often (or only?) on systems in another language. Could you keep in mind to ask the above questions on these kinds of issues?

**Comment by behofer** [comment]
@feerrenrut:
* Windows display language: German (Germany)
* Windows preferred language: German (Germany)
* Office Authoring language: German (Germany)
* Office display language: 1. Bound to default Windows language; 2. German; 3. English
Generally, second language is always set to English.
If I can collect anythiing else, let me know.
Reproducing it is really hard! I was hoping the error at the end of the logs would help you to get an idea of what's going on. I never worked with other language settings by default, so I can't tell either if

**Comment by behofer** [comment]
[nvda-old_20200430.log](https://github.com/nvaccess/nvda/files/4558871/nvda-old_20200430.log)
@feerrenrut: Another log, error messages at the end are different, maybe it helps.

**Comment by feerrenrut** [comment]
Thanks for providing more information.
I notice several errors in braille, and at least one in the brailleExtender addon. Could you try disabling this addon to ensure it's not causing the problem? We have had some suspicion that using braille devices with office is triggering a problem. I understand working without braille devices temporarily might not be an option, but if it is for you, it could help to narrow down the cause.

**Comment by behofer** [comment]
@feerrenrut Sure. I disabled brailleExtender addon. But, unfortunately, it still occurs.
Here's the log from today: 
[nvda-old-20200504.log](https://github.com/nvaccess/nvda/files/4573029/nvda-old-20200504.log)

**Comment by behofer** [comment]
@feerrenrut What just came to my mind: If it's dependent on language settings, could it be related to charset/encoding? In German, we have some special characters (ü, ä, ...) like many other languages. Just an idea, you may have checked this anyway.

**Comment by Adriani90** [comment]
I am on german as well, but not able to reproduce. I don't think this is language specific, I am using Outlook also in romanian and we have also some crazy charsets. Which version of Outlook do you have exactly? Could you please try to update the Outlook 365 in the files ribbon > office account > update options > search for updates?

**Comment by Adriani90** [comment]
Another idea, could you please test this without braille display? It seems you are using a Friedom Scientific Focus braille display and this might contribute to this issue.
cc: @bramd, @leonardder maybe you have some thoughts for this as well?

**Comment by Adriani90** [comment]
@behofer did you try my suggestions above? Are you still having this issue in NVDA 2020.1?

**Comment by Adriani90** [comment]
@behofer did you try to re-create your Outlook profile? Such issues could be caused by a damaged Outlook profile as well. Here is a tutorial how to re-create your profile without loosing current Outlook settings etc.
https://www.howto-outlook.com/faq/newprofile.htm#create

**Comment by Alexparallel** [comment]
Hello,
 I have exactly de same problem. When reading o replying large mesages in outloock 365.
I'm runing windows 10 and the last stable version of Nvda. MI language is Spanish and I don't use braille display.
If I can help to test someting just tell me.

**Comment by leonardder** [comment]
I can also reproduce this sometimes. Also, both with object model and UIA, so this is not a duplicate. I only have freezes, not crashes, though I heard about crashes from others.

**Comment by Alexparallel** [comment]
If you find large conversations (more tan 5 mesages) with signatures it’s easy to reproduce in my experience.

De: Leonard de Ruijter <notifications@github.com>
Enviado el: 01 December 2020 16:12
Para: nvaccess/nvda <nvda@noreply.github.com>
CC: Alex Romera <alex@parallel.so>; Comment <comment@noreply.github.com>
Asunto: Re: [nvaccess/nvda] NVDA crashes / becomes totally unresponsive when replying to a message in Outlook 365 (#11070)


I can also reproduce this sometimes. Also, both with object model and UIA, so this is not a duplicate. I only have freezes, not crashes, though I heard about crashes from others.

**Comment by behofer** [comment]
For me, that doesn't happen anymore with current Outlook and NVDA versions.
