### ISSUE TITLE
Alpha-20080 has broken NVDA's time-oriented functions in Foobar2000

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#11082]
### Steps to reproduce:
1. First and foremost, make sure you are running NVDA Alpha 20080,83e32ba6 or newer.
2. Play an MP3 file via Foobar2000.
3. Press Control+Shift+E, Control+Shift+R and Control+Shift+T to check the elapsed, remaining and total times.
### Actual behavior:
NVDA erroneously says: "No track playing".
### Expected behavior:
NVDA should report the elapsed, remaining and total times, respectively.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
Alpha-20080 and newer. Alpha-20074 is the last alpha release which works properly.
#### Windows version:
Windows 10 Pro 64-Bit, version 2004.
#### Name and version of other software in use when reproducing the issue:
Foobar2000 only.
#### Other information about your system:
As mentioned, Alpha-20074 is the last functioning release. Even the alphas which were released On Friday May 1 exhibit this issue.
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes -- Alpha-20074 works, and newer alphas don't. NVDA 2019.3.1 also works as expected.
#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes -- though apparently irrelevant.

**Comment by josephsl** [comment]
Hi,

Follow-up from #9792, so this app module must provide a way to retrieve status information correctly.

Thanks.

**Comment by amirsol81** [comment]
Hi. Any idea as to when this issue will be fixed? It's effectively preventing me from installing and testing new alphas as I depend on the broken Foobar2000 time-oriented features.

**Comment by amirsol81** [comment]
One of the alphas released today fixed this issue, so I'm closing it. Thanks.
