### ISSUE TITLE
Current xgettext integration does not allow to follow copyright headers guidelines

### ISSUE THREAD

**Issue by JulienCochuyt** [nvaccess/nvda#11080]
### Steps to reproduce:

When adding a new source file, or updating an existing one, follow copyright headers guidelines at (https://github.com/nvaccess/nvda/wiki/Copyright-headers)
In the process, add a contributor name containing a non-ASCII character.
Build POT using `scons pot`

### Actual behavior:

Build fails as `xgettext` complains about the non-ASCII character.

### Expected behavior:

Build succeeds.

#### NVDA installed/portable/running from source:

N/A

#### NVDA version:

Any since POT generation automation, long ago.

#### Windows version:

N/A

#### Name and version of other software in use when reproducing the issue:

N/A

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No.

#### If addons are disabled, is your problem still occuring?

Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

No.

Upcoming PR...

**Comment by feerrenrut** [comment]
I think this will be fixed with:

``` python
# -*- coding: UTF-8 -*-
```

See https://github.com/nvaccess/nvda/wiki/Contributing#encoding

**Comment by feerrenrut** [comment]
Perhaps the copy-right headers page should mention that. Probably wouldn't hurt if all files had that. Or maybe you have a fix in mind that will remove the need for this?

**Comment by JulienCochuyt** [comment]
@feerrenrut wrote:
> I think this will be fixed with:
> 
> ```python
> # -*- coding: UTF-8 -*-
> ```
> 
> See https://github.com/nvaccess/nvda/wiki/Contributing#encoding

Sorry, I missed this one.




> Perhaps the copy-right headers page should mention that.

Indeed.

> Probably wouldn't hurt if all files had that.

I agree, it wouldn't.

> Or maybe you have a fix in mind that will remove the need for this?

See PR #11081.
Both approaches are fine to me.
