### ISSUE TITLE
Crashes with Microsoft Word 2019

### ISSUE THREAD

**Issue by alexbernier** [nvaccess/nvda#11089]
### Steps to reproduce:

I am experiencing very frequent crashes with Microsoft Word 2019, when editing document. I can not find an exact sequence of operations to rproduce those crashes. Attached are two NVDA log files to show what is happening.

### Actual behavior:

Crash when editing text.

### Expected behavior:

No crash

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.3.1

#### Windows version:

Windows 10

#### Name and version of other software in use when reproducing the issue:

Microsoft Word 2019

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes

[word1.log](https://github.com/nvaccess/nvda/files/4567475/word1.log)
[word2.log](https://github.com/nvaccess/nvda/files/4567476/word2.log)

**Comment by DrSooom** [comment]
@alexbernier: Please tell us the used Windows, Microsoft Office and NVDA languages as well as the used braille display. Thanks.

**Comment by alexbernier** [comment]
Windows, Word and NVDA are in French.

The braille display is an HandyTech EasyBraille 40 connected via USB.

**Comment by MarioBatusic** [comment]
### Same Problem by me
I have also contstant crashes of NVDA during editing Word files. Here my data:
#### NVDA Version
2020.1
#### Windows Version
10.0.18363 Build 18363
#### MS Word Version
Office 2016
#### Languages
System and NVDA: German - Deutsch
#### Braille Display
Freedom Scientific Focus 40 and Focus 14

**Comment by Adriani90** [comment]
I've heared also from other users with this braille display reporting crashes or lperformance lag in Word.

@alexbernier, @MarioBatusic are you also reproducing this issue without braille display connected? Or is it occuring only when you have the braille display connected?

**Comment by MarioBatusic** [comment]
I work always with Braille display connected. So I haven’t tested it without Braille display.

Von: Adriani90 <notifications@github.com>
Gesendet: Mittwoch, 3. Juni 2020 18:02
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Batusic, Mario <mario.batusic@fabasoft.com>; Mention <mention@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Crashes with Microsoft Word 2019 (#11089)


I've heared also from other users with this braille display reporting crashes or lperformance lag in Word.

@alexbernier<https://github.com/alexbernier>, @MarioBatusic<https://github.com/MarioBatusic> are you also reproducing this issue without braille display connected? Or is it occuring only when you have the braille display connected?

**Comment by Adriani90** [comment]
Could you please take the time and do this for us though? It would help in investigating furtherr here. Thanks.

Von meinem iPhone gesendet

**Comment by leonardder** [comment]
@alexbernier Could you answer the following additional questions?

1. What do you mean with crashes? Does NVDA crash, or does Word crash, or even both?
2. Do you have the `Use UI Automation to access Microsoft Word document controls when available` setting enabled in NVDA's advanced settings? Do things improve if you do so?

@Adriani90 I think that using a braille display certainly makes a difference, but I don't think there's any reason to believe that the brand or type makes a difference.

**Comment by leonardder** [comment]
cc @engineermario

**Comment by MarioBatusic** [comment]
Hi Alex,

@alexbernier<https://github.com/alexbernier> Could you answer the following additional questions?

  1.  What do you mean with crashes? Does NVDA crash, or does Word crash, or even both?
NVDA crashes.
  2.  Do you have the Use UI Automation to access Microsoft Word document controls when available setting enabled in NVDA's advanced settings? Do things improve if you do so?
No, not till now. But I will swith this option on and test with it. I post then the possible change.

@Adriani90<https://github.com/Adriani90> I think that using a braille display certainly makes a difference, but I don't think there's any reason to believe that the brand or type makes a difference.

**Comment by MarioBatusic** [comment]
I was now long time trying to use NVDA in Word with the 'Use UI Automation' option enabled. And yes, NVDA does not crash with it. but there are a plenty of issues working in MS Word with this option set. Especially for Braille Display presentation. Should I post these Issues? Is this option still experimental and is not implemented completely?

**Comment by leonardder** [comment]
It would be helpful if you can at least list your issues here. Some might have already been reported, others not

**Comment by MarioBatusic** [comment]
### Some Issues in Word, when UIA Mode on
Issue Info | Speech output | Braille output
----------------------------------- | --------------- | ---------------
Print Page View: False semantic announced in every line of text | Edit Read Only | ro edt
All views: NVDA does not announce alt text of a graphic, only | document graphic | gra
All views: Clicking a routing key on the braille display in a heading, puts the coursor key 3 Braille cells to the right of the clicked cell

**Comment by Adriani90** [comment]
cc: @michaelDCurran

**Comment by bhavyashah** [comment]
It is worth noting that #11247  also deals with NVDA freezing when a Braille display is connected. While the title may suggest specificity to Chrome, that may not necessarily be the case and one of the comments on it indicates NVDA freezing in Outlook when a Braille display is connected.
Also, do you think it would be better for the Word UIA issues listed in https://github.com/nvaccess/nvda/issues/11089#issuecomment-645893961 be documented and subsequently discussed in new, separate tickets? They seem functionality-related concerns whereas this ticket was originally about NVDA crashing. @Adriani90 @leonardder  @MarioBatusic

**Comment by michaelDCurran** [comment]
@MarioBatusic  Could you please state your exact Office version? You can find this in Microsoft Word under File -> Account -> About Microsoft Word. 
Something like 16.0.12827.2003.

I think all the issues you have listed related to UI Automation are simply bugs in Microsoft Word that were addressed in later versions. Thus even if we do turn this on by default, it wouldn't be for a version this old... though I can't be sure with out knowing your exact Office version.

**Comment by a11y-spl** [comment]
I am having issues with all MS Office products, Excel, Outlook, Power Point.....the applications freeze up, have to restart the machine

It is happening for V2019 & V 2020.2

**Comment by Adriani90** [comment]
@a11y-spl are you still have the freezing issue with NVDA 2023.1 RC1 and last version of Microsoft office?

**Comment by Adriani90** [comment]
We didn't get any further updates from the people who had this isue since many years. Given the current significant performance improvements in MS Office with NVDA 2023.2, I am closing this issue as abandoned until someone else encounter this issue again. Then we can reopen.
