### ISSUE TITLE
Selection by paragraph in Firefox with ctrl+shift+arrow keys is broken

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#11083]
### Steps to reproduce:
1. Open Firefox with NVDA
2. In an edit field with text, i.e. comment area or issue description, select the text with ctrl+shift+arrow keys.

### Actual behavior:
NVDA selects only the current line and does not move further up or down.

### Expected behavior:
NVDA should select the paragraphs as it worked recently.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-20097,6a573cd9

#### Windows version:
Windows 10 1909 Update

#### Name and version of other software in use when reproducing the issue:
Firefox 75

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
not yet

#### If addons are disabled, is your problem still occuring?
yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes, no effect

**Comment by Adriani90** [comment]
@jcsteh I recall this worked properly recently, I think this is a regression from one of the last PRs. It occurs only in Firefox.

**Comment by Adriani90** [comment]
This occurs only in focus mode

**Comment by JulienCochuyt** [comment]
I could reproduce this behavior with no screen reader running.
Selection by paragraph in multi-line text fields seems broken in recent Firefox.
I guess we can close this ticket.
Can someone please check that the Firefox team has been informed of the situation?

**Comment by jcsteh** [comment]
I can reproduce this, but as far as I know, this isn't a regression. I can reproduce it as far as back as Firefox 60. My guess is that Firefox just doesn't support the idea of paragraphs at all.

**Comment by JulienCochuyt** [comment]
@Adriani90 can we close this ticket in the light of https://github.com/nvaccess/nvda/issues/11083#issuecomment-623757443?

**Comment by Adriani90** [comment]
I guess yes. Thanks for the reminder. :-) Closing as can't fix.
