### ISSUE TITLE
Document NVDA build process based on Visual Studio Build Tools

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#11088]
### Is your feature request related to a problem? Please describe.
Currently, the readme advises people to build NVDA with Visual Studio community. For people who never use the IDE, this is overkill.

### Describe the solution you'd like
Describe the process based on Visual Studio 2019 build tools. Add a note that Build tools can be swapped for whatever version of Visual Studio they prefer.

**Comment by Adriani90** [comment]
cc: @seanbudd

**Comment by leonardder** [comment]
I'm pretty sure I added this and indeed, there's a reference to this in the build documentation:

> When you do not use the Visual Studio IDE itself, you can download the [build tools](https://aka.ms/vs/16/release/vs_BuildTools.exe)

I consider this fixed.
