### ISSUE TITLE
NVDA displays headings and the text after them on one line when Screen Layout is turned off

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#11096]
### Steps to reproduce:
1. First, make sure Screen Layout is turned off or unchecked. It can be done via Insert+V quickly.
2. Go to https://www.merriam-webster.com/dictionary/procrustean
3. Find the level-2 heading on the page which says: "Examples of procrustean in a Sentence". It is the 4th heading from the top.
4. If you use H and Shift+H to reach the heading, it is properly read as "Examples of procrustean in a Sentence". However, if you reach it via Up/Down, NVDA says: "Examples of procrustean in a SentenceRecent Examples on the Web//What was really at issue were".
### Actual behavior:
NVDA displays both the heading, Examples of procrustean in a Sentence", and the text immediately after it, "Recent Examples on the Web - What was really at issue were", on one single line, forcing navigation with both H and SHIFT+H ignore the reading of the non-heading stuff and confusing users who expect to see headings and the text below them properly separated when the Screen Layout mode is turned off.
### Expected behavior:
NVDA should properly separate the heading from the text which comes below it, and pressing the Down arrow from the heading should place the focus on the line which isn't part of the heading.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Alpha 20,097, but also duplicable with previous alphas, NVDA 2019.3.1, and all 2019/2018 releases.
#### Windows version:
Windows 10 Pro 64-Bit, version 2004
#### Name and version of other software in use when reproducing the issue:
Google Chrome 81 stable, but also duplicable with many older releases of Chrome. Internet Explorer 11.00.19041.1 works fine, though. Don't have access to Firefox for testing.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes -- as mentioned above up to all 2018 releases
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes -- though apparently irrelevant

**Comment by amirsol81** [comment]
I forgot to mention that JAWS works properly here -- if it makes any difference.

**Comment by Adriani90** [comment]
Related issue is #11073.

**Comment by amirsol81** [comment]
Issue #11073 which I reported a couple of days ago affects links and can be duplicated universally, everywhere, and is browser-independent. This one affects headings, pops up here and there rather infrequently, and apparently doesn't affect Internet Explorer.

**Comment by amirsol81** [comment]
Another example -- please check the 4th heading which says "Examples of draconian in a Sentence": https://www.merriam-webster.com/dictionary/draconian

**Comment by leonardder** [comment]
It would help to have details about how this looks for a sighted person.

**Comment by amirsol81** [comment]
Good point. As a visually impaired person, all I know is that JAWS works properly in this context on all browsers, and NVDA does it right in Internet Explorer not Chrome -- don't know about Firefox.

**Comment by amirsol81** [comment]
Also duplicable with the latest release of Firefox.

**Comment by zahra21** [comment]
hi.
i tested with nvda 2017.2 using firefox 52.9 esr, and did not reproduce the issue in both link for webster dictionary.
maybe a new bug in recent versions of browsers or screen reader!

**Comment by amirsol81** [comment]
IMHO NVDA 2017.2 and Firefox 52 are too old to be considered pro-valid testing points.

**Comment by zahra21** [comment]
as i said:
i cant reproduce in nvda 2017.2 with firefox 52.
and i mentioned that its maybe a new issue in recent versions of
browsers or even nvda screen readers!
i only use windows xp and cant test with newer versions of firefox!

On 5/6/20, amirsol81 <notifications@github.com> wrote:
> IMHO NVDA 2017.2 and Firefox 52 are too old to be considered pro-valid
> testing points.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/11096#issuecomment-624585806


-- 
By God,
were I given all the seven heavens
with all they contain
in order that
I may disobey God
by depriving an ant
from the husk of a grain of barley,
I would not do it.
imam ali

**Comment by leonardder** [comment]
@zahra21, while I really appreciate your intention to help, @amirsol81 has a valid point. We can't consider testing data regarding NVDA 2017.2 and Firefox 52 as relevant for any issue unless explicitly asked for. Therefore, I'm afraid sharing this information isn't of any help. Could you please refrain from this?

**Comment by zahra21** [comment]
how about
if i can reproduce reported issue in my version of nvda or other programs?
i really wish to help, how can i help?
may i have your email address?
can you please send me email and i can be in contact with you via email?

On 5/6/20, Leonard de Ruijter <notifications@github.com> wrote:
> @zahra21, while I really appreciate your intention to help, @amirsol81 has a
> valid point. We can't consider testing data regarding NVDA 2017.2 and
> Firefox 52 as relevant for any issue unless explicitly asked for. Therefore,
> I'm afraid sharing this information isn't of any help. Could you please
> refrain from this?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/11096#issuecomment-624597781


-- 
By God,
were I given all the seven heavens
with all they contain
in order that
I may disobey God
by depriving an ant
from the husk of a grain of barley,
I would not do it.
imam ali

**Comment by Adriani90** [comment]
I can reproduce this in Firefox only when pressing ctrl+down arrow on the heading. Not when pressing down arrow or up arrow alone.

**Comment by amirsol81** [comment]
> I can reproduce this in Firefox only when pressing ctrl+down arrow on the heading. Not when pressing down arrow or up arrow alone.


With Chrome 83 and 84 it's duplicable with Up and down, too. It also happens regardless of the status of the Screen Layout check box under NVDA's Browse Mode settings.

**Comment by amirsol81** [comment]
This has been resolved, so I'm closing the issue.
