### ISSUE TITLE
Incorrect count of HTML Description lists 

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11101]
### Steps to reproduce:

Create a HTML description list:

<dl>
	<dt>Test term 1</dt>
		<dd>Test definition</dd>
	<dt>test term 2</dt>
		<dd>test definition 2.1</dd>
		<dd>test definition 2.2</dd>
</dl>

Display in browser and navigate.

### Actual behavior:

In both Firefox 75 and Chrome 81.0.4044.129, NVDA reads the main list as "List with five items"

### Expected behavior:

Likely related to #11100 (counting nested lists) but this example should either be "a list with two items and two nested lists" (or even better, "a list with two items and two definitions", given it is a description list), or simply a list with two items.

#### NVDA version:

NVDA 2020.1 rc1

#### Windows version:

Windows 10 version 1903, build 18362

#### Name and version of other software in use when reproducing the issue:

Firefox 75 and Chrome 81.0.4044.129

#### Does the issue still occur after restarting your computer?

Yes

#### If addons are disabled, is your problem still occuring?

Yes

**Comment by leonardder** [comment]
I believe this is a duplicate of #3858, which is broader in scope.

**Comment by Qchristensen** [comment]
You are correct Leonard, sorry I searched for Description list, which is the term W3 uses on the page I was reading.  Description list and Definition list seem to be interchangeable in many places and I should have looked for Definition list as well (FWIW, Definition list seems to lend itself better to the standard use case given for these tags).  I'll close this issue.
