### ISSUE TITLE
NVDA is reading the whole content of the modal-dialog along with Title of the dialog

### ISSUE THREAD

**Issue by harishreddykanakanaka** [nvaccess/nvda#11106]
### Steps to reproduce:
Open the link: "https://ireade.github.io/accessible-modal-dialog/"
Open NVDA and navigate to the hamburger icon then press/click the button.

### Actual behavior:
NVDA is reading the whole content of the modal-dialog along with Title of the dialog
### Expected behavior:
NVDA should read only the title of the dialog.

### System configuration
RAM: 16GB
Storage: 1TB Hard disk
System Type: 64bit
#### NVDA installed/portable/running from source:
Tried with both
#### NVDA version:
NVDA version 2019.3.1

#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Google Chrome: Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by leonardder** [comment]
Your assumption is incorrect. NVDA reads: 
```
Site Navigation
Description goes here
```

As the `description goes here` is attached to the dialog using aria-describedby, the description is read automatically. NVDA can be configured not to do so by disabling object description reporting in NVDA's object presentation settings.

Also note that hamburger menu's really should be implemented with modal dialogs like this.
