### ISSUE TITLE
Incorrect count of item in HTML UL list containing a nested list

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11100]
### Steps to reproduce:

Create a HTML nested list, eg:

<UL>
	<LI>List item 1</LI>
	<LI>List item 2</LI>
	<UL>
		<LI>Sub-list item 1</LI>
		<LI>Sub-list item 2</LI>
	</UL>
	<LI>List item 3</LI>
</UL>

Display in browser and navigate

### Actual behavior:

In both Firefox 75 and Chrome 81.0.4044.129, NVDA reads the main list as "List with four items".  The nested sub-list is correctly identified as having two items.

### Expected behavior:

There are several ways it could be reported, but either way it's not a list with four items :)

The most informative is likely: "List with three items and one nested list".
Simply reporting "List with three items" is shorter, and leaves the user to discover that some items in this list contain their own nested lists.

#### NVDA version:

NVDA 2020.1 rc1

#### Windows version:
Windows 10 version 1903, build 18362

#### Name and version of other software in use when reproducing the issue:

Firefox 75 and Chrome 81.0.4044.129

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

NVDA 2019.2.1 behaves the same.

#### If addons are disabled, is your problem still occuring?
Yes (no add-ons installed to begin with)

**Comment by Qchristensen** [comment]
Note that issue #8103 is still present but separate to this issue.

**Comment by amirsol81** [comment]
It's duplicable here with Internet Explorer version 11.00.19041.1. Quite interestingly, IE 11 also says "List unavailable with 4 items". The word "unavailable" is also announced for the sublist.
"List with three items and one nested list" sounds reasonable.

**Comment by Adriani90** [comment]
@feerrenrut maybe this is one issue for the project board regarding lists?

**Comment by ice-blaze** [comment]
Any update on this one? I see it's not active that much but the issue still exists. (VoiceOver gives level and correct number of list item in the current list)

**Comment by ice-blaze** [comment]
I could find a solution. According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul the `ul` tag should be inside the `li` tag.

Good code:
```html
<ul>
  <li>Milk</li>
  <li>
    Cheese
    <ul>
      <li>Blue cheese</li>
      <li>Feta</li>
    </ul>
  </li>
</ul>
```

Bad code:
```html
<ul>
  <li>Milk</li>
  <li>Cheese</li>
  <ul>
      <li>Blue cheese</li>
      <li>Feta</li>
  </ul>
</ul>
```
