### ISSUE TITLE
the dll-s and the .h files are missing from the /extras/controller client

### ISSUE THREAD

**Issue by vlad-a-c** [nvaccess/nvda#11126]
###step to reproduce: i click on the /extras/controller client and i don't see anything besides the X86 directory which has only the examples.

**Comment by Andre9642** [comment]
Please read the instructions in [/extras/controller/readme.html](https://raw.githubusercontent.com/nvaccess/nvda/master/extras/controllerClient/readme.html).

> Note: The header and library files are built along with nvdaHelper. If you want to build them yourself, please see readme.txt in the NVDA source distribution for instructions. Alternatively, you can find a pre-built package at <http://www.nvda-project.org/nvdaControllerClient/>.

**Comment by leonardder** [comment]
It looks like this url no longer works. Leaving this open until we have a proper url pointing at the controller client.

Cc @feerrenrut

**Comment by feerrenrut** [comment]
A zip of the latest builds of controller client are available from [appveyor](https://ci.appveyor.com/project/NVAccess/nvda/history):  Go to the build, then to artifacts then find `output\nvda_2020.1_controllerClient.zip`.

Here is a direct link to the build for [2020.1 controllerClient](https://ci.appveyor.com/api/buildjobs/fjrffle3i3g5ww4e/artifacts/output%2Fnvda_2020.1_controllerClient.zip)

**Comment by bhavyashah** [comment]
@leonardder  https://github.com/nvaccess/nvda/issues/11126#issuecomment-625824063 does seem to contain the "proper url pointing at the controller client" you indicated that we should wait for. Given that this has been shared, should this ticket be closed now? Not sure myself.

**Comment by Adriani90** [comment]
Closing given the comments above.
