### ISSUE TITLE
Make possible during  uninstal delete also user data (files and folders of NVDA in %appdata%\roming)

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#11128]
### Is your feature request related to a problem? Please describe.

When NVDA is being uninstalled, it removes files and folders in c:\program files (x86) but leaves user data untouched. but sometimes user wants to remove NVDA completely from a system due to problems with current copy or other reasons.

### Describe the solution you'd like

during uninstal add a check box where user can choose whether also uninstall user data.

### Describe alternatives you've considered

Leave as it is or update userguide with instructions, how to manually remove user data.

thanks.

**Comment by Adriani90** [comment]
Closing as duplicate of #6869
