### ISSUE TITLE
The buttons "ask a question", "Report a question", "reply" are announced with additional text "Q&A property page".

### ISSUE THREAD

**Issue by eDADMSFTChristopher** [nvaccess/nvda#11121]
Bug Issue

The buttons "ask a question", "Report a question",   "reply" are announced with additional text "Q&A property   page".

Description | The buttons "ask a question"   ,"Report a question”, “reply Are not announced solely but the name and   control assigned to it , but with extra information as well.

Environment: https://testbashgallery.marketplace.vsts.io/testbash

Tools used
AzDev-Marketplace
Windows 10 Version 1909 
Chrome version 81.0.4044.129 (Official Build) (64-bit)
NVDA 2019.3.1

### Steps to reproduce:

Repro Steps 	
1. Launch screen reader as NVDA.
2. Launch the application Url : https://testbashgallery.marketplace.vsts.io/testbash
3. Navigate to "Visual studioTab" and select it.
4. Under most popular heading select extension “Redgate SQL Change Automation Core”
5. Navigate using tab to "Q&A tab" and select it.
6. Use tab key and navigate to the button “Ask a question”

### Actual behavior:
Actual Results 	
On navigating using tab to the buttons  "ask a question", "Report a question", "reply" they are announced with additional text "Q&A property page" preceding the button name.

### Expected behavior:

Expected Results 	
The words" Q&A property page" should not be announced with the controls. The control should be announced by the name and control type.
eg: "ask a question button"

### System configuration
Tools used
AzDev-Marketplace
Windows 10 Version 1909 
Chrome version 81.0.4044.129 (Official Build) (64-bit)
NVDA 2019.3.1

#### NVDA version:
NVDA 2019.3.1

#### Windows version:
Windows 10 Version 1909

**Comment by Adriani90** [comment]
This is also reproducible in Firefox. I cannot find something wrong here, it might be that in the java script code this is defined as a section and this is reported by NVDA as property page. at least this reporting sounds familiar to me from other Java web applications as well.
cc: @jcsteh maybe you have other findings here?

**Comment by Adriani90** [comment]
@eDADMSFTChristopher the test page is not available anymore. Can you please provide a minimal test case with Codepen?
Are you still having this issue with NVDA 2024.2 stable or 2024.3 Beta?

**Comment by Adriani90** [comment]
We didn't get any updates upon request from the initial author since many years, I am closing as abandoned. If you are still having this issue, please comment and we can reopen.
