### ISSUE TITLE
NVDA announces periods despite current punctuation level

### ISSUE THREAD

**Issue by bkoray** [nvaccess/nvda#11137]
### Steps to reproduce:
Read a text which has a period followed by a symbol like following:
[read.]
read./
### Actual behavior:
NVDA pronounces "dot" with punctuation levels "some" and "most" like:
left bracket read dot right bracket
read dot slash
### Expected behavior:
With punctuation level some and most, NVDA should pronounce:
left bracket read right bracket
read slash
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.1
#### Windows version:
10.0.18362.657
#### Name and version of other software in use when reproducing the issue:
n/a
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by DrSooom** [comment]
@bkoray: Which synthesizer is used? And did you mean `[Read.]` and `Read./` instead of `[Read]` and `Read/` in the StR section?

**Comment by bkoray** [comment]
Hey @DrSooom, I have tested it with
Microsoft Speech API version 5 and
Windows OneCore voices

Oh, thanks for mentioning that, I've edited the comment. I was testing a few more things before sending and apparently forgot to fix them. :)

**Comment by DrSooom** [comment]
@bkoray: I guess you already know that you can change the symbol level for this Unicode character (I mean the dot) in the punctuation/symbol pronunciation dialog. Just search for "." and change the level to "All". Please don't change the entry ". sentence ending".

**Comment by Brian1Gaff** [comment]
I thought it worked as it does so internet and email addresses sound 
correct.
 Or am I missing the point... pun intended..
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by OzancanKaratas** [comment]
The dot mark is not spoken unless you set the punctuation level to “All” so that you can feel the real life reading experience.

**Comment by fisher729** [comment]
Hi.

I'm thinking that this issue should be closed, as the dot (.) is also listed in the Symbol Pronunciation dialog being announced by default in the Some category. So, the above is the expected behaviour. There is no true cut and dry way of knowing if these full stops are sentence enders, and in these cases, they are not treated as such.

**Comment by bkoray** [comment]
Thanks everyone for your comments! Originally period marks were being used for slight pauses in the application, but we can't expect every user to adjust their settings accordingly. So we'll find another way.
