### ISSUE TITLE
Empty Name field in new configuration profile

### ISSUE THREAD

**Issue by karkenau** [nvaccess/nvda#11146]
if I create a new configuration profiles and leave 
the nave file empty, choose "menuel" and thand try to save this by hitting the "Ok" button...just nothing happens.
I am running NVDA 2020.1 on a Windows 10 system. Disaabeeling the addons and running the repair tool for the com registration didnÄt do any good.

**Comment by CyrilleB79** [comment]
Could you please use the template to submit issues? There are important information from the template that people addressing the issue need to know and that youdid not provide. Here, the "Actual result" and "Expected result" section would be specifically needed.

**Comment by JulienCochuyt** [comment]
@karkenau,
I just pushed a fix proposal for your issue.
Nevertheless, @CyrilleB79 remark still stands: Please fill the whole issue template every time you file an issue against NVDA. Even if it sometimes looks like too much for simple issues, it really helps contributors to spend less time in understanding your problems and thus spend more time in attempting to solve them.

**Comment by karkenau** [comment]
Good morning,
I am sorry for the inconvienience. I promise to do better in my next issue. 
Sorrt once mor.
