### ISSUE TITLE
NVDA is reading all the controls at once when set role="dialog" on button clicked.

### ISSUE THREAD

**Issue by v-sagsah** [nvaccess/nvda#11152]
**Browser Details: ​**
OS: Windows 10 (Version 1903, Build: 18362.175)
Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Issue:**
[Accessibility] : NVDA is reading all the controls at once when set role="dialog" on button clicked.

Please repro the same in the below code pen link
https://codepen.io/sagsah/pen/abvKvor?editors=0010

**Note :** 
1. In code pen code, the CallOut contains 2 button controls and one link. Upon clicking on the **_"Show Callout"_**, NVDA is reading all the controls label at once, even though the focus is not been set.
2. I had ran the Accessibility Insights tool on my code-pen components and there were no errors so it looks like the spec is being followed.
![image](https://user-images.githubusercontent.com/64409491/81643499-551e7300-9443-11ea-896f-5d33df0d111d.png)

**_Issue not found with Narrator +Chromium Edge._**

**Expected Result: ​**
NVDA should not read all the controls information at once when CallOut field button is opened. It should read only the information of the controls on which the focus is present.

**User Impact: ​**
Screen reader users will get confused if narrator reading all the information at once.

**Comment by Adriani90** [comment]
This can be solved if you disable "automatically read whole page after load" in NVDA's browse mode settings. This is expected behavior now in NVDA, see also issues #9135 and #4493 for more background on this. I am closing this issue as invalid.
