### ISSUE TITLE
Proposal: Change how "point" releases are numbered so they don't read as dates

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11162]
### Is your feature request related to a problem? Please describe.

When we go to a "point" release, a lot of synthesizers read the version number as a date.  For instance:

NVDA 2019.3.1 reads to many users as "NVDA March First, Two thousand and nineteen".  In fact what that version number represents is a "minor" release (to fix a critical bug) based on the third release of 2019.

### Describe the solution you'd like

Testing a couple ideas, the best one I've found, for readability, I think, is:

2019.3-1 (replace the second dot with a hyphen).  Most synthesizers read this as "Two-thousand and nineteen point three one".  At symbol level "Most" or "All" it gets read as "Two-thousand and nineteen point three dash one".

There is potential for someone to misinterpret this as the 31st release of 2019, but less confusing that reading it as a date.

### Describe alternatives you've considered

As long as the dividers aren't both the same it seems ok
2019.3,1 (Twenty-nineteen point three comma one)
2019.3a (Twenty-nineteen point three a)
2019.3.a (Two thousand and nineteen point three dot a)
2019.3/1 (Two thousand and nineteen point three slash one)
2019.3_1 (Two thousand and nineteen point three one) or at symbol level most or all: Two thousand and nineteen point three line one.

### Additional context

I'm not sure what else this change might break - eg version number code, website release system, etc.

**Comment by dingpengyu** [comment]
> ### Is your feature request related to a problem? Please describe.
> When we go to a "point" release, a lot of synthesizers read the version number as a date. For instance:
> 
> NVDA 2019.3.1 reads to many users as "NVDA March First, Two thousand and nineteen". In fact what that version number represents is a "minor" release (to fix a critical bug) based on the third release of 2019.
> 
> ### Describe the solution you'd like
> Testing a couple ideas, the best one I've found, for readability, I think, is:
> 
> 2019.3-1 (replace the second dot with a hyphen). Most synthesizers read this as "Two-thousand and nineteen point three one". At symbol level "Most" or "All" it gets read as "Two-thousand and nineteen point three dash one".
> 
> There is potential for someone to misinterpret this as the 31st release of 2019, but less confusing that reading it as a date.
> 
> ### Describe alternatives you've considered
> As long as the dividers aren't both the same it seems ok
> 2019.3,1 (Twenty-nineteen point three comma one)
> 2019.3a (Twenty-nineteen point three a)
> 2019.3.a (Two thousand and nineteen point three dot a)
> 2019.3/1 (Two thousand and nineteen point three slash one)
> 2019.3_1 (Two thousand and nineteen point three one) or at symbol level most or all: Two thousand and nineteen point three line one.
> 
> ### Additional context
> I'm not sure what else this change might break - eg version number code, website release system, etc.
hi
You can also refer to nvdajp's version naming format:
[nvdajp](
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp)

**Comment by XLTechie** [comment]
Of the presented options, I like the year, dot, major number, minor alpha. Drop 
the second punctuation all together, and use a letter. But if we have to have a 
second punctuation, I prefer sticking to the same one (period).

That way you keep using only one delimiter, so people don't accidentally start 
inverting which punctuation goes where, etc.

As a final thought, I like swapping the major and minor indicator types, and 
ditching the punctuation all together. 2020A1, 2020B1, 2020B2. Year, major 
alpha, minor number.

**Comment by JulienCochuyt** [comment]
The current version numbering is consistent with [Python's PEP 440 -- Version Identification and Dependency Specification ](https://www.python.org/dev/peps/pep-0440/#final-releases).

While sticking to it is not mandatory as we do not publish anything to PyPi, I would still advise to avoid adopting a new version numbering scheme that might lead to misinterpretation in regard to this standard.

Notably, following PEP 440:
 - 2019C1 means first release candidate of future release 2019
 - 2019.3-1 means first post-release of version 2019.3, that
> address minor errors in a final release that do not affect the distributed software (for example, correcting an error in the release notes),
> [...]
> The use of post-releases to publish maintenance releases containing actual bug fixes is strongly discouraged.

Also, the forward-slash ("`/`") is not permitted in filenames under Windows.

Thus, I guess the only remaining proposals that do not lead to misinterpretation are 2019.3,1 and 2019.3_1 but these feel IMHO quite unusual and cannot be automatically interpreted/sorted by Python's `packaging` parser.

If ever a consensus arises on the need for a change, my personal preference would be for 2019.3-1 despite PEP 440's recommandations.

Still, I'd prefer not to change at all, but I'm probably biased by not being hit by the confusion with a date.

**Comment by leonardder** [comment]
I'd rather not change the versioning scheme at all. How about considering other alternatives, like treating date formats more strictly? For example, is 2020.1.1 considered to be a valid date format? shouldn't it be 2020.01.01?

**Comment by Brian1Gaff** [comment]
I guess this must be synth related then, as using Espeak I don't hear the 
problem.


Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by Brian1Gaff** [comment]
Yes and at least in synths I've tried, making the second dot into 2 dots 
also works.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by CyrilleB79** [comment]
@Qchristensen and/or other, could you please give examples or even a full listing of the synth where the issue occur? And also tell us in which language/culture such a date format is valid and usual. This would allow to understand better this issue before thinking to a possible solution.

**Comment by XLTechie** [comment]
@JulienCochuyt wrote:

> The current version numbering is consistent with [Python's PEP 440 -- Version Identification and Dependency Specification ](https://www.python.org/dev/peps/pep-0440/#final-releases).

I was unaware of that one, thank you.

> Thus, I guess the only remaining proposals that do not lead to misinterpretation are 2019.3,1 and 2019.3_1 but these feel IMHO quite unusual and cannot be automatically interpreted/sorted by Python's `packaging` parser.

Agreed, I dislike both of those strongly.

> If ever a consensus arises on the need for a change, my personal preference would be for 2019.3-1 despite PEP 440's recommandations.

What about something like this, renumbering last year's versions:

* 2019.100
* 2019.101
* 2019.200
* 2019.201
* 2019.300
* 2019.301

It meets all the perceived requirements:
* Not excessive or strange punctuation.
* Doesn't violate any of the guidelines you listed.
* Doesn't sound strange when voiced by various synths (does it?).
* Sorts well in file lists.
* Is unambiguously clear about which version is more recent.

I'm sure it has its downsides, such as not looking like other common version numbers. But then, I'm a proponent of [Semantic Versioning](https://semver.org/), so this whole year first thing is not my preference anyway.


> Still, I'd prefer not to change at all, but I'm probably biased by not being hit by the confusion with a date.

I use eSpeak most of the time, so don't usually experience it, but I see it all the time in user support circumstances, especially on mailing lists.

### Replication

To replicate, I just typed "NVDA 2019.3.1" into notepad.

* `Espeak: NVDA 2019 point 3 point 1.`
* `One Core David: NVDA March first, 2019.`

**Comment by XLTechie** [comment]
I will add that my example above, tested in Narrator, has the same incorrect results.
English language.
I don't know where year.month.day is a valid date, especially as written with single digits and periods, but apparently Microsoft deems it so. Maybe @josephsl has some idea.

**Comment by josephsl** [comment]
Hi, ISO 8859 might be a handy reference, as it specifies date format for ease of sorting. As this issue is synthesizer specific, the ideal solution is letting screen readers pass raw strings and pronunciation commands to synthesizers unless it is resolved from the vendor’s end. Note that this may mean looking into version parsing code used for testing add-on compatibility. Thanks.

**Comment by Adriani90** [comment]
In my view this should be solved by synthesizer vendors, not by screen readers. To solve this globally would require a huge work and will possibly not succeed for every synthesizer anyway.

**Comment by Adriani90** [comment]
how about using something like NVDA 20.1, 20.2, 20.2.1 etc?So just the two last digits of the current year at the beginning? This would work correctly until we reach the year 2100 :)

**Comment by CyrilleB79** [comment]
If we choose not to modify version number, would it be acceptable to fix the pronunciation for NVDA only, i.e. pronunciation may fail on other screenreaders such as Narrator or Jaws.
If yes, such a dictionary entry seems to fix the issue by forcing a "dot" to be pronounced:
Pattern: (?<=\d{4}.\d).(?=\d)
Replacement: dot
Probably, a complex symbol would be more adapted to this issue, but I did not bother to edit my symbol file to test it.
This is just a proposal and the regexp may be refined.

**Comment by XLTechie** [comment]
Tested with Microsoft David, and it reads correctly.
Actually, 20.1 reads as twenty point one. While 20.1.1 reads as two zero point 
one point one.

Not sure why it does it like that, but either way solves the problem this issue targets.

**Comment by DrSooom** [comment]
I prefer the dictionary entry solution and strongly recommend not to change the version scheme. And to avoid side effects, I would limit the dictionary entry to "20(1-3)(0-9).(1-4).(1-3)".

PS: In German the thousand separator is a dot and not a comma like in English. So "2019.201" is spoken as "Two million nineteen thousand two hundred and one" – even if the syntax is wrong (correct syntax: 2.019.201).

**Comment by CyrilleB79** [comment]
@DrSooom wrote:
> I prefer the dictionary entry solution and strongly recommend not to change the version scheme. And to avoid side effects, I would limit the dictionary entry to "20(1-3)(0-9).(1-4).(1-3)".

I would not add such strong limitation since:
* NVAccess stated that they want to increase the annual number of release so do not limit them to four a year
* I do not hope so but we should not exclude an NVDA 2020.2.4.

@DrSooom wrote:
> 
> PS: In German the thousand separator is a dot and not a comma like in English. So "2019.201" is spoken as "Two million nineteen thousand two hundred and one" – even if the syntax is wrong (correct syntax: 2.019.201).

The same in French with Eloquence.

@Adriani90 wrote:
> how about using something like NVDA 20.1, 20.2, 20.2.1 etc?So just the two last digits of the current year at the beginning? This would work correctly until we reach the year 2100 :)

With SAPI5 Microsoft Anna - English (United States), "NVDA 20.2.1" is read "NVDA February 1st, 20".

**Comment by Adriani90** [comment]
To be honnest, I don't know if the community is the best place to solve this issue. It is very synth specific and probably there is no really consistent solution for all synthesizers out there. Regarding the versioning number, this is rather a strategical topic which should be discussed further internally at NV Access if needed. I mean we can give here our cents on it but we cannot influence the whole versioning process. This is done by NV Access as it has also been done with the introduction of Alpha and Beta versions.

If no further valuable input is expected here, then I suggest to close this issue and continue this discussion on the dev mailing list or in the NVDA council, if a diferent versioning should be trageted.

@Qchristensen what do you think?

**Comment by Adriani90** [comment]
I am closing this request for now, but please comment on it if you have further thoughts and we can reopen if needed.
