### ISSUE TITLE
UIA cannot get parent object in some circumstances

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#11164]
hello all.

i am writing an appmodule for unigram (telegram client), and i faced with a problem, where i cannot get a correct parent object.

in unigram, we have a main chats listview, in which, we have button, which is automatically focused when navigating with arrow keys, but because of focusing button in listview item and not listview item instead, we cannot get object position.
this listview item is a parent object of toggle button, but if i do nav.parent, i am jumping to window root object. instead of correct parent object.

**Comment by Adriani90** [comment]
@beqabeqa473 are you still having this problem? did you already ask on add-ons or core developers mailing list for advice?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author upon request since many years. I am closing as abandoned. if you are still having this issue, please comment and we can reopen.
