### ISSUE TITLE
NVDA is skipping error messages while reading multiple errors on the screen with role="alert"

### ISSUE THREAD

**Issue by SarveshNamjoshi** [nvaccess/nvda#11182]
Hi team,
I am having a form with multiple text boxes implemented in **React** using **Office UI Fabric** components.

There is a required field validation on each of the text box and if there is no value entered in the text box and if user tries to submit the form, error messages are displayed below each text boxes saying that the field is required.

I have verified in the **Google Chrome Dev Tools** that the div element for  error message is having **role="alert"** attribute. But still, while narrating, **NVDA** narrates some of the error messages and always skips some of the error messages. (I have verified on **Internet Explorer 11** with **Windows Narrator**, it reads all the error messages. So potentially there should not be anything with the code.). Therefore I suspect some problem with NVDA.

![image](https://user-images.githubusercontent.com/62882875/82531027-2e0b2400-9b5c-11ea-98e3-256e9f61edf4.png)

Google Chrome: **Version 81.0.4044.138 (Official Build) (64-bit)**
NVDA: **Version 2019.3.1**

Need help to understand the cause of this issue and possible solution.

**Comment by Brian1Gaff** [comment]
I've had this problem with almost every browser from time to time. Forms can 
be very unreliable. Though it pains me to say it, Jaws normally manages 
better.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by DrSooom** [comment]
@SarveshNamjoshi: Which TTS synthesizer are you using? Please try to reproduce this with [NVDA 2020.1](https://www.nvaccess.org/files/nvda/releases/2020.1/nvda_2020.1.exe) (running it from the Installer should be enough) and report the results. Thanks.

**Comment by SarveshNamjoshi** [comment]
@DrSooom 
We are using the inbuilt TTS Synthesizer (from tools -> Speech viewer). We tried with NVDA 2020.1 but still the issue is reproducible. It is skipping the error messages while narrating. Could you please let us know the cause and possible solution.

**Comment by DrSooom** [comment]
1. Does this issue only occur while the Speech Viewer window is opened?
2. Go to "Preferences » Settings... » Speech". There you see the TTS synthesizer.

**Comment by SarveshNamjoshi** [comment]
1. The issue is occurring irrespective of Speech Viewer window is opened / not opened.
2. Generally we are using "Windows OneCore Voices" TTS Synthesizer. We tried to change the TTS Synthesizer as you guided but still the issue persists.

**Comment by Adriani90** [comment]
@SarveshNamjoshi in order to investigate this as efficient as possible, we test also in other browsers (i.e. Firefox) to see if it is NVDA or the browser the underlying problem. Could you please create a minimal test case from that form containing the allert messages and upload it here as html or zip file? That would help alot. Thanks.

**Comment by Adriani90** [comment]
@SarveshNamjoshi do you have a test case for us to investigate further? You could also just give a link to a website where this issue can be reproduced. Thanks.

**Comment by Adriani90** [comment]
I am closing this as abandoned since we didn't get a test case from the initial author.. We are not able to reproduce this issue without a test case.
