### ISSUE TITLE
Global command script_navigatorObject_doDefaultAction not found

### ISSUE THREAD

**Issue by bilrousseau** [nvaccess/nvda#11194]
I'm trying to trigger default action in my module when Space or Enter is pressed.
I'd like the default action to be triggered when Space or Enter is pressed, but not using directly NVDA+numpadEnter gesture.

I tried to look into globalCommands using dir(globalCommand) and I didn't find the script_navigatorObject_doDefaultAction from GlobalCommands whereas it exists in the API Documentation : https://www.webbie.org.uk/nvda/api/frames.html

Were it moved in another module or renamed ?

### Steps to reproduce:

Write a class which inherits from appModule
class AppModule(appModuleHandler.AppModule)
Write decorator on gestures space and enter

```
@script(gestures=["kb:space", "kb:enter"])
    def script_clickOnObject(self, gesture):
        ui.message("Default action")
        GlobalCommands.script_navigatorObject_doDefaultAction(self, gesture)
```

### Actual behavior:
Nothing happens.

### Expected behavior:
Default action is triggered.

#### NVDA installed/portable/running from source
NVDA installed

#### NVDA version:
2020.1
#### Windows version:
Windows 10 Family 18362.836

#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not yet
#### If addons are disabled, is your problem still occuring?
Not tried yet

**Comment by lukaszgo1** [comment]
The documentation on webbie web page is horribly outdated. The script is now called script_review_activate. I don't think using it in an appmodule like that is a very good idea though. Could you explain what exactly are you trying to achieve?

**Comment by bilrousseau** [comment]
We're still beginners and for now we're figuring out how to call those methods. We're not sure if we're gonna use it in a module yet.

What would you recommend as a "not horribly outdated" documentation ? (I mean, besides the Github repo markdown and source code)

Thanks for your answer anyway. We'll check that out.

**Comment by lukaszgo1** [comment]
You can generate the uptodate developer documentation by executing scons devdocs from the root of the NVDA repo

**Comment by Adriani90** [comment]
You can also use following sources:
NVDA Developer guide:
https://www.nvaccess.org/files/nvda/documentation/developerGuide.html

Addons development guide:
https://github.com/nvdaaddons/DevGuide/wiki/NVDA-Add-on-Development-Guide

Or you can ask your question directly in the development mailing list at:
https://groups.io/g/nvda-devel

Or in the addons mailing list at:
https://nvda-addons.groups.io/g/nvda-addons

Or even in the Gitter instant messaging at:
https://gitter.im/nvaccess/NVDA

I am closing this issue for now given the new ressources.
