### ISSUE TITLE
NVDA should provide instructions for use for beginners

### ISSUE THREAD

**Issue by ollcayy** [nvaccess/nvda#11201]
NVDA should provide instructions for use for beginners. This is a feature especially desired by computer teachers. NVDA should include automatic user messages, such as how to enable it when a focus is on a check box, a button, link, or something else, how to select an item.
As of now, NVDA comes with a basic shortcoming for students who are starting to learn new computers.

**Comment by Adriani90** [comment]
I agree this could be useful for beginners, it could be sort of NVDA running in a beginners mode, where information for every element is spoken after the label is reported (i.e. link Github, press enter to open in the current tab).
The problem I see here is that elements might have more than one action possible and this would be quite long reporting. I.e. for a link: enter to open the page in the current tab, ctrl+enter to open in a new tab etc. Or for a combo box, enter to activate, alt+down arrow to expand, alt+up arrow to colaps. But this should not be an impediment here.

**Comment by ollcayy** [comment]
In my opinion, the length of the message doesn't matter for NVDA or someone new to the computer screen. Just take the hint to do the right action.
Maybe in education, the beginning can be divided into middle and closed levels. This talking can be grouped in education.

**Comment by josephsl** [comment]
Another variant of #2699. Thanks.

**Comment by bhavyashah** [comment]
@josephsl  @Adriani90 Do you think this ticket is sufficiently similar to #2699 for this to be closed as a duplicate? Tutor messages/context-sensitive help have definitely been requested in the past.

**Comment by josephsl** [comment]
Hi, yes, I think this is a duplicate. Thanks.

**Comment by Adriani90** [comment]
Closing as duplicate as per comment above.
