### ISSUE TITLE
automatic responses in the chat interface of cortana

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#11216]
### Describe the solution you'd like
was experimenting with the new chat-based interface of the cortana.
Press start menu + c on windows 10 may 2020 update.
When typing a message to the cortana, the cortana displays a response.
To read the answer as well as the whole conversation you can walk with tab or shift + tabe to the list and read the chat with the assistant with the arrows above and below.
My suggestion is when the user types a question and presses enter, and there is an answer from the assistant that nvda reads the answer automatically.
Just like nvda already does on other chat interfaces, on skype, skype for companies, etc.

**Comment by josephsl** [comment]
Hi, already possible via Windows 10 App Essentials add-on. Thanks.

**Comment by fernando-jose-silva** [comment]
Thank you very much for returning.
I have this add-on installed, however with me it does not work, nvda does not automatically read responses.
Anyway, I be
[cortana.txt](https://github.com/nvaccess/nvda/files/4692203/cortana.txt)
lieve that it is very good to have this feature directly on nvda.
Here is a log:

**Comment by josephsl** [comment]
Hi, which version of the add-on do you have? You need 20.06.1 or later in order to let NVDA read Cortana responses properly. Thanks.

**Comment by fernando-jose-silva** [comment]
I have this version and it doesn't work wintenApps-20200526-dev.nvda-addon - 244 KB

Enviado do meu iPhone

**Comment by josephsl** [comment]
Hi,

Okay, can you try the following for me:

1. With Windows 10 App Essentials installed, restart with debug logging.
2. Use Cortana.
3. After using Cortana for a while, press NVDA+F1 to open the log viewer.
4. Copy and paste the log and attach it to this issue.

I need a debug log because it'll then tell me what I'm missing about Cortana support in international markets. Thanks.

**Comment by fernando-jose-silva** [comment]
Follow the complete log as requested
[cortanafull.txt](https://github.com/nvaccess/nvda/files/4698370/cortanafull.txt)

**Comment by josephsl** [comment]
Hi, I see. Looks like UIA notification event isn’t fired when Cortana gives you results, and the add-on code only knows English. Can you try again with all add-ons except Windows 10 App Essentials disabled so I can read a cleaner log output? Thanks.

**Comment by josephsl** [comment]
Hi, also I just pushed WinTenApps May 28th snapshot – see if it improves things a bit. Thanks.

**Comment by fernando-jose-silva** [comment]
Thank you very much, great job, I believe you will not need the log, I downloaded your latest update to the addon windows app and everything worked perfectly.
Now is my request to implement this in nvda natively.
thank you

**Comment by josephsl** [comment]
Hi, I’ll look into this after the summer vacation (after July at the earliest). Thanks.

**Comment by Adriani90** [comment]
@josephsl is this now working in the NVDA core as well? Or is this still restricted for Win10 Apps Addon users?

**Comment by josephsl** [comment]
Hi, still included in Windows App Essentials, and I’m about to decide if I should remove it completely from that add-on with the rise of ChatGPT and similar conversational agents and chat bots. Thanks.

**Comment by Adriani90** [comment]
Ok Cortana will be discontinued for Windows and Teams, see this article. Thus, I don't expect any further updates regarding accessibility to this feature. Closing as abandoned.
https://support.microsoft.com/en-us/topic/end-of-support-for-cortana-in-windows-and-teams-d025b39f-ee5b-4836-a954-0ab646ee1efa
