### ISSUE TITLE
NVDA - Focus gets trapped when navigating within drop down menu (NVDA goes into scan mode)

### ISSUE THREAD

**Issue by khushveer** [nvaccess/nvda#11229]
### Steps to reproduce:
Open drop down Menu
Perform some action within the dropdown (expanded the list of items in the menu)
Navigate from to another item
NVDA goes into scan mode and focus gets trapped.
it starts working again after switching out of scan mode 

### Actual behavior:
Focus gets trapped

### Expected behavior:
Focus should go to the expected element

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2020.1

#### Windows version:
10.0.18363 Build 18363

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by DrSooom** [comment]
@khushveer: Where? Please list all web browsers incl. their versions and/or the applications incl. their versions where this issue occurs. And if it occurs on a website, please link to it or give us a sample html code for reproducing and testing. Thanks.

**Comment by Adriani90** [comment]
Same issue as #11228. Closing as duplicate.

**Comment by DrSooom** [comment]
@Adriani90: Hard to say until we get more information by @khushveer. I would keep it open as long as @khushveer confirms the duplicate.

**Comment by khushveer** [comment]
@DrSooom @Adriani90 I don't think this is the duplicate of the issue mentioned. 
I am attaching a video describing the issue.


**Browser Versions:**
Microsoft Edge version 81.0.416.53 (Official build) (64-bit)
Windows Version: windows 10
Google Chrome version 81.0.4044.113 (Official build) (64-bit)

Code Snippet:
`<div>`
`<div>`
`<span class="caption">Filters</span>`
`<span class="example">(e.g., Activity ext:cs)</span>`
`</div>`
`<ul role="listbox" class="list detailed" aria-label="filters list">`
`<li role="option" class="item" tabindex="-1">`
`<div class="text">ext:`
`</div>`
`<div class="hint">With file extension`
`</div>`
`</li>`
`<li role="option" class="item" tabindex="-1">`
`<div class="text">file:`
`</div>`
`<div class="hint">Filename`
`</div>`
`</li>`
...
`<li class="item expander" aria-expanded="true" role="button" tabindex="-1">`
`<span aria-hidden="true" class="expander-icon"></span>`
`<span>Show less</span>`
`</li>`
`</ul>`
`</div>`

`<div>`
`<div>`
`<span class="caption">Operators</span>`
`<span class="example">(e.g., ToDo OR revisit)</span>`
`</div>`
`<ul role="listbox" class="list compact" aria-label="filters list">`
`<li role="option" class="item" tabindex="-1">`
`<div class="text">AND</div>`
`</li>`
`</ul>`
`</div>`

[BugVideo_2.zip](https://github.com/nvaccess/nvda/files/4809482/BugVideo_2.zip)

**Comment by khushveer** [comment]
@DrSooom @Adriani90 as mentioned previously, can we please re-open the bug?
