### ISSUE TITLE
Combobox not working

### ISSUE THREAD

**Issue by lallerke1** [nvaccess/nvda#11228]
### Steps to reproduce:
Go to this website:
https://www.microsoft.com/en-us/wdsi/definitions/antimalware-definition-release-notes
Try to access the combobox, and select another antivirus definition.
You cannot do it, only with help wirth the mouse, arrows do not navigate.
### Actual behavior:
The combobox is not working for arrow keys.
### Expected behavior:
The listbox shall work as expected, with arrow keys.
#### NVDA version:
alpha-20256,f2cbfec8
#### Windows version:
Version: 2004 (OS Buildnummer: 19640.1)
#### Name and version of other software in use when reproducing the issue:
Microsoft edge, all versions
Mozilla Firefox all versions
Google chrome all versions
Opera all versions
Internet explorer all versions.

#### Other information about your system:
First language is hungarian, and using windows insider, but is not working in normal cirtumstances as well.
#### Does the issue still occur after restarting your computer?
Yes, it does.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, 2020.1, the same.
#### If addons are disabled, is your problem still occuring?
Yes, it does.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes, I did.
[nvda.log](https://github.com/nvaccess/nvda/files/4728293/nvda.log)

**Comment by DrSooom** [comment]
1. Move to "Select definition version" in Browse Mode:
2. Press ArrowDown. It switches to Focus Mode.
3. Press ArrowDown again until you reach "Released on". Note take NVDA switched back to Browse Mode.
4. Press ArrowUp in Browse Mode to reach the still expanded list.
5. Now switch to Focus Mode and you can change the value here with ArrowUp and ArrowDown.
6. Press then Enter and switch again back to Browse Mode.

Okay, not really handy (in Firefox 77.0.1). Contacting the [Microsoft Disability Answer Desk](https://www.microsoft.com/en-us/accessibility/disability-answer-desk) couldn't be bad here.

**Comment by Adriani90** [comment]
This combo box does not work as expected when automatically switch to focus mode is enabled in NVDA's browse mode settings. After the list is expanded, every press of down arrow key or up arrow key on the combo box traverses the combo box and switches NVDA to browse mode without sellecting a value. Only if you switch to focus mode manually with nvda+space bar, the combo box is working.
cc: @michaelDCurran

**Comment by bhavyashah** [comment]
Disclaimer: This is an unhelpful and unrelated comment.
Working with combo boxes, list boxes, menus and controls of the sort on the web have never been a particularly smooth experience with NVDA. The issue could be lagginess, shifts between browse and focus mode, inability to use commands like read current line to review options, thinking you selected one option but when you come out of the box you realize some other adjacent option got selected, and the list goes on. I think there is much scope for polishing this aspect of the NVDA experience.

**Comment by Adriani90** [comment]
This works as expected now with NVDA 2022.4, Firefox 109, Chrome and Edge 110. I am closing as works for me.
