### ISSUE TITLE
Realtek HD Audio Manager

### ISSUE THREAD

**Issue by Dino804** [nvaccess/nvda#11227]
### Steps to reproduce:
Open the Realtek HD Audio manager, no any of that window is accessible to read, no controls, no text output.
### Actual behavior:
See above.
### Expected behavior:
I wish this Manager would be fully accessible with NVDA because if you switch an audio device sometimes it happens that it appears and ask for some configurations you have to make but that is not possible yet.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Version: alpha-20256,f2cbfec8
#### Windows version:
Windows 10 Version 1909 (Build 18363.836)
#### Name and version of other software in use when reproducing the issue:
Realtek HD Audio Manager (no version information because that window isn't accessible, neither of the menu of that program).
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by DrSooom** [comment]
@Dino804: The Version of the installed Realtek High Definition Audio Driver should be visible in the list of installed programs in the Control Panel – or maybe in the Windows Update history.

**Comment by leonardder** [comment]
@Dino804 Could you provide information about brand and type of your system? It seems that some manufacturers provide their own implementation of the Realtek driver. For example, my Dell laptop provides an Asio driver, whereas other brands don't.

**Comment by OzancanKaratas** [comment]
We need more information. What is your control panel version? Universal Microsoft Store application or standard desktop application?

**Comment by Futyn-Maker** [comment]
Hi!

I have ASUS Zenbook 13UX333FN, and this problem is actual for me, too. Windows 10. It doesn't depend in version of NVDA.

**Comment by Adriani90** [comment]
The realtec HD audio manager is not installed on every laptop by Default. It depends on which motherboard you have and which driver version of the soundcard is designed for your Laptop.
I recall that the audio manager can only be accessed with NVDA by using object navigation, but not using tab or shift+tab.
I think it will be hard to investigate if developers do not have acess to the HD audio manager. Did you already contacted the sound card developers from Realtec for this issue at pctech@realtek.com
as stated here?
https://www.realtek.com/en/cu-1-en/cu-1-usa-en

I don't expect them to answer shortly or to start working on this, but you never know.

**Comment by Adriani90** [comment]
I think Acer laptops and Lenovo laptops have the HD audio manager installed by default as well.
I am using a Dell Laptop, there is no audio HD manager for my Laptop available.

**Comment by Adriani90** [comment]
Any updates on this? Is there a ticket opened with Realtec? How is this working now with NVDA 2023.1?

**Comment by epman100** [comment]
> Any updates on this? Is there a ticket opened with Realtec? How is this working now with NVDA 2023.1?

I highly doubt you & others will get any where with Realte**k** (not Realtec) as they usually listen more to pc manufacturers than with ordinary pc users like you & me.  I tried emailing Realtek several times from different addresses and have not gotten any response at all from them.  they used to have an unlisted non-public  but password protected ftp site to download drivers not released on their main web site but have shut that down a few years ago, making it near impossible to get new versions nowadays.  so contacting & emailing Realtek is like playing a game of [roulette](https://en.wikipedia.org/wiki/Roulette).

and so far, none of the people here have not even mentioned what **version** of the Realtek HD Audio drivers they have installed when using them with NVDA

**Comment by Adriani90** [comment]
The realtec HD audio manager is actually the same like Realtec audio console. Given the audio console is the follow up version of the HD audio manager, this is already accessible and can be used instead of the audio manager. I am closing this as abandoned since we still missing information about the version of the app and considering the alternative which works properly with NVDA.
