### ISSUE TITLE
Keyboard focus is lost after performing action on button when NVDA is on.

### ISSUE THREAD

**Issue by khushveer** [nvaccess/nvda#11230]
### Steps to reproduce:
Open drop down Menu
Navigate to button that expands the list in the drop down and click on it
On pressing "enter" NVDA is calling mouseDown which clears the focus because it looks like a mouse event. 

### Actual behavior:
Focus is lost.

### Expected behavior:
Focus should remain on the active element

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.1

#### Windows version:
10.0.18363 Build 18363

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by DrSooom** [comment]
@khushveer: Same missing information here such as in issue #11229. Therefore I quote myself:
> Where? Please list all web browsers incl. their versions and/or the applications incl. their versions where this issue occurs. And if it occurs on a website, please link to it or give us a sample html code for reproducing and testing. Thanks.

**Comment by khushveer** [comment]
@DrSooom I have attached a video for the issue.
The issue does not occur with Edge+Narrator, but only NVDA.


**Browser Versions:**
Microsoft Edge version 81.0.416.53 (Official build) (64-bit)
Windows Version: windows 10
Google Chrome version 81.0.4044.113 (Official build) (64-bit)

Sample code  - 
`<div class="vss-FilterBar--page-button-container">`
`<button aria-disabled="true" aria-label="See previous group of filters" class="page-button disabled icon-only" data-is-focusable="true" role="button" tabindex="-1" type="button">
<span aria-hidden="true" class="left-icon flex-noshrink">`
`</span>`
`</button>`
 `<button aria-disabled="false" aria-label="See next group of filters" class="page-button enabled icon-only" data-focuszone="" data-is-focusable="true" role="button" tabindex="0" type="button">`
`<span aria-hidden="true" class="left-icon flex-noshrink">`
`</span>`
`</button>`
`</div>`

[BugVideo_1.zip](https://github.com/nvaccess/nvda/files/4809428/BugVideo_1.zip)

**Comment by Adriani90** [comment]
@khushveer, @shrenik007 I cannot reproduce this issue with NVDA 2024.1 Beta and Chrome or Edge 121. Are you still having this issue?
@khushveer Please provide a clear test case (i.e. a codepen). The test code doesn't work because it doesn't allow for any action on the button to be performed.

**Comment by Adriani90** [comment]
We didn't get updates form the initial author upon request since more than one year, the abandoned rule is applying here. I am closing as abandoned. if you are still having this issue, plesae comment with the information requested and we can reopen.
