### ISSUE TITLE
Line numbers are not reported when UIA support in MS Word is enabled

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#11248]
### Steps to reproduce:
1. Open MS Word 2016 or 365
2. Open NVDA and enable UIA support for MS Word in advanced settings
3. IN document formatting settings, enable reporting of line numbers
4. In MS Word, press enter multiple times and navigate with arrow keys

### Actual behavior:
Line numbers are not reported.

### Expected behavior:
Line numbers should be reported both with UIA support disabled or enabled.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.1

#### Windows version:
Windows 10 1909 Update

#### Name and version of other software in use when reproducing the issue:
MS Office 2016 and newer.

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, all since UIA support for MS Word has been introduced. Same behavior on all of them.

#### If addons are disabled, is your problem still occuring?
yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
n/a

**Comment by leonardder** [comment]
I think this can be generalized to line number reporting in UIA in general. It seems it's simply neither implemented nor supported.

**Comment by leonardder** [comment]
This was fixed by #13387. Note that it looks like the fix might be incomplete/not working for every version of Word for which we advertice it should work, but that's a different story discussed in #13537

**Comment by cary-rowen** [comment]
Sorry, I was wondering if the issue has indeed been fixed?
NVDA2022.2Alpha still fails to report line numbers for me.

MSO (Version 2205 Build 16.0.15225.20172) 64 bit (Already the latest version).
@michaelDCurran 
@Adriani90 
@leonardder
