### ISSUE TITLE
the nvda speech viewer does not allow some text selections

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#11269]
### Is your feature request related to a problem? Please describe.
open the nvda speech viewer
Read any text as an article.
Now alternet to the nvda speech viewer, put the focus at the beginning of the text you want to copy, like the beginning of the article.
Now press home
the focus goes out of the selected line, and goes to the letter t at the end of the text in the speech viewer.
Now return to the beginning of the article in the viewer to select the text with shift + down arrow.
This is also not possible the focus is thrown to the end of the text in the nvda's speech viewer, with the text being spoken again.
### Describe the solution you'd like
the focus should not be shifted to the end of the text in the speech viewer, allowing me to make any type of text selection in the speech viewer
### Describe alternatives you've considered
everything that is spoken when the focus is on the nvda speech viewer window is not inserted in the...
### Additional context
this occurred during a class where I would like to show students that they could use the speech viewer to select a piece of text read on the internet.

**Comment by Neurrone** [comment]
The speech viewer in general is pretty inaccessible ironically to a sighted person. E.g, you can't increase the size of the window so that more text can be shown at once.

**Comment by bhavyashah** [comment]
@fernando-jose-silva I am unable to replicate this issue with NVDA version 2020.2 Beta 1. Pressing Home and Shift+down arrow works as expected in the Speech Viewer and I do not experience any jumpiness with my focus or selection.
@Neurrone I think it would be better to point out this limitation in a separate ticket. The issue you note, while related to the Speech Viewer like this ticket, is sufficiently different from the problem identified here.

**Comment by bhavyashah** [comment]
@Neurrone  I am not entirely sure, but #8991 might be of interest to you.

**Comment by bhavyashah** [comment]
@Neurrone Since you are thinking about the Speech Viewer from a sighted angle, I think #8388 may also be of interest to you. Sorry for spamming this ticket with references to other tickets! :)

**Comment by Neurrone** [comment]
Thanks @bhavyashah.

**Comment by fernando-jose-silva** [comment]
After further testing I discovered an add-on that is causing this add-on
Enhanced Phonetic Reading;
If anyone can report on the list of add-ons.
I'm not an English speaker, this is google translation.
I don't feel comfortable talking on a discussion list without speaking English.
I already thank you for taking care of this channel, which I know my speeches must be difficult to understand.

**Comment by TechHorseG** [comment]
I have the same or a similar problem. With Enhanced Phonetic Reading addon enabled., I can still arrow up and down the paused text in the Speech Viewer and the SV remains paused with no problem. But if I arrow left or right, causing EPR to state a word corresponding to the current letter, this causes the SV to unpause. The stated word, "foxtrot", "Sierra", "Alpha" etc now appears in the SV at the bottom, the cursor also moves down there, and the SV is now unpaused. This can make getting to, and selecting text within the SV tricky.

**Comment by lukaszgo1** [comment]
CC @davidacm

**Comment by Adriani90** [comment]
This seems an issue related to a specific add-on, please contact the add-on author to fix this issue. Closing.
