### ISSUE TITLE
Release Task: Review change log for 2020.2

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#11260]
For the upcoming 2020.2 release the change log needs to be reviewed and updated.

This meta issue can be used to keep track of those who have reviewed its current state.
You can inspect the file here: https://github.com/nvaccess/nvda/blob/beta/user_docs/en/changes.t2t

**Comment by feerrenrut** [comment]
@Qchristensen Would you mind taking a look?

**Comment by zstanecic** [comment]
Spelling fix:

Refiev = review

**Comment by josephsl** [comment]
Hi, eg should be e.g. in one of the entries. Also, the entry on new symbols is very vague, making users wonder exactly which symbols were added (perhaps examples would be useful). Thanks.

**Comment by DrSooom** [comment]
`- Updated liblouis braille translator to [3.14.0 https://github.com/liblouis/liblouis/releases/tag/v3.14.0] (from 3.12.0). (#10832, #11221)`

Please interchange the versions – "from 3.12 to 3.14". Then it sounds better and is more understandable. Thanks.

**Comment by josephsl** [comment]
Hi, I think it would be better to just say “updated to 3.14” for consistency with other releases. Thanks.

**Comment by Qchristensen** [comment]
As well as the comments above:

Under Highlights:
Change:
"...performance improvements 1Password,..."
To:
"...performance improvements in 1Password,..."


Under New Features:

Add: "(no default gesture)" to these two items (for consistency with the earlier item #2214):
- Added a command to report the active configuration profile. (#9325)
- Added a command to toggle reporting of subscripts and superscripts. (#10985)

Under bug fixes:
Change:
- NVDA starts correctly when log file cannot be created. (#6330)
to:
- NVDA now starts correctly when the log file cannot be created. (#6330)

Remove "a" from:
- The tool-tips of the icons in the system tray are no longer reported upon keyboard navigation if their text is equal to the name of the icons, to avoid a double announcing. (#6656)
to:
- The tool-tips of the icons in the system tray are no longer reported upon keyboard navigation if their text is equal to the name of the icons, to avoid double announcing. (#6656)

Change:
- Do not change focus in Java application when selection is change in not focused tree, table or list. (#5989)
to:
- Focus is not moved in Java applications when the selection is changed in an unfocused tree, table, or list. (#5989

**Comment by feerrenrut** [comment]
> Hi, I think it would be better to just say “updated to 3.14” for consistency with other releases. Thanks.

I don't think it is harmful to break this consistency, and it's helpful to know what the last version was.

**Comment by feerrenrut** [comment]
Thanks @Qchristensen, these changes have been addressed in #11264
