### ISSUE TITLE
This is because the button has an aria has popup on it. This is a duplicate of #9096 and might be solved either in NVDA or in Chrome itself. I am closing as duplicate.

### ISSUE THREAD

**Issue by nousrnm** [nvaccess/nvda#11276]
This is because the button has an aria has popup on it. This is a duplicate of #9096 and might be solved either in NVDA or in Chrome itself. I am closing as duplicate.

_Originally posted by @Adriani90 in https://github.com/nvaccess/nvda/issues/11274#issuecomment-646317682_

**Comment by nousrnm** [comment]
Sorry, i'm new on github. You can delete this topic.

**Comment by Adriani90** [comment]
Closing.
