### ISSUE TITLE
Braille: Often used undefined Unicode Symbols in the German comp8 table

### ISSUE THREAD

**Issue by MarioBatusic** [nvaccess/nvda#11275]
### Steps to reproduce:
Use Editors such as MS Word with unordered lists or HTML editors such as [XEditor](https://www.xeditor.com/)
### Actual behavior:
Some Unicode symbols are undefined using the German comp8 table. That means, the symbols appear on the Braille display as '\xhhhh' hexadecimal number.
### Expected behavior:
Some non-alphanumeric Braille signs witch are all different from each other. A system would be possible that uses 2 Braille cells.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.1
### Some important symbols to be defined in Braille
Symbol name | Unicode Hex
------------------ | -----------------
Checkmark | \x2714
hollow arrow | \x2b9a
solid square | \x25aa
four small diamonds | \x2756
invisible auxiliary symbol | \x200b

**Comment by leonardder** [comment]
I'm afraid this is not the right place to report this issue. Please refer to [Liblouis](https://github.com/liblouis/liblouis/issues).

**Comment by DrSooom** [comment]
@MarioBatusic: In the meantime install [BrailleExtender](https://andreabc.net/projects/NVDA_addons/BrailleExtender/) (20.05.28 or higher) and select [HUC8](https://danielmayr.at/huc/de.html#d8) for the representation of undefined Unicode characters.
