### ISSUE TITLE
Reading stop with microsoft word for microsoft 365

### ISSUE THREAD

**Issue by math65** [nvaccess/nvda#11282]
### Steps to reproduce:

* Create / open a long document in Microsoft Word
* Activate document reading with NVDA + Down arrow / NVDA + A

### Actual behavior:

In a moment, the reading of the Word document stops and we have to restart it

### Expected behavior:

Reading should continue, because sometimes NVDA stops in the middle of a line

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2020.1

#### Windows version:

Windows 10 (Version 2004)

#### Name and version of other software in use when reproducing the issue:

Microsoft Word for office 365

#### Does the issue still occur after restarting your computer?

Yes, in 2 computers

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes

**Comment by XLTechie** [comment]
Please specify what synth you are using.

**Comment by math65** [comment]
I use Manon (French voice acapela for NVDA)

**Comment by math65** [comment]
Oups! I don't want close, i'm sory

**Comment by XLTechie** [comment]
Does this only happen in Word, or does it also happen in a web browser or 
Notepad?

**Comment by math65** [comment]
The bug is random. Now it happened in notepad but not in word ...

**Comment by Adriani90** [comment]
Could you please try with another synthesizer? Does it occur for example with eSpeak or with Onecore voices?

**Comment by math65** [comment]
I tried with espeak, the problem only occurs with the voice acapela.

**Comment by Adriani90** [comment]
@math65 could you test with NVDA 2023.1 or with NVDA last alpha version? Is this still occuring in Microsoft Office last update?

You can download the last NVDA alpha for testing at this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by CyrilleB79** [comment]
Also, have you reported the issue to Acapela?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author upon request since many years, I am closing as abandoned. if you are still having this issue, please comment and we can reopen.
