### ISSUE TITLE
revue cursor: strange behavior in windows-terminal with braille

### ISSUE THREAD

**Issue by alex19EP** [nvaccess/nvda#11288]
### Steps to reproduce:

0. use a braille desplay
1. open new windows-terminal 
2. in power-shell execute "ls"
3. move revue cursor up with num7

### Actual behavior:

whole line underlined by dots 7, 8 

### Expected behavior:

only the first cell is underlined by dots 7, 8 

#### NVDA installed/portable/running from source:

installed

#### NVDA version:

2020.2beta1

#### Windows version:

Windows 10Ver2004 (64-бит) build 19041.330

#### Name and version of other software in use when reproducing the issue:

Windows Terminal Preview 1.1.1671.0

#### Does the issue still occur after restarting your computer?

yep

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

not applicable because 2020.2 is first version wich properly supports windows terminal

#### If addons are disabled, is your problem still occuring?

yep

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

yep. but i think this is not applicable  too.

FYI: @codeofdusk

**Comment by codeofdusk** [comment]
Cc @michaelDCurran  @carlos-zamora.

**Comment by codeofdusk** [comment]
This could very possibly be caused by microsoft/terminal#7342 as I think Braille relies on `setEndPoint`. Cc @carlos-zamora.

**Comment by codeofdusk** [comment]
After further investigation, this is almost definitely due to microsoft/terminal#7342.

**Comment by codeofdusk** [comment]
Could this issue please be closed?

**Comment by Adriani90** [comment]
Thanks Bill for the contribution. I am closing this issue as fixed.
