### ISSUE TITLE
Alert not read at all when setting focus on input

### ISSUE THREAD

**Issue by arnauddem** [nvaccess/nvda#11290]
### Steps to reproduce:
  1. start NVDA
  2. browse this url: https://codepen.io/arnauddem/pen/ExPWMjZ
  3. set focus on 'username' input

### Actual behavior:
 NVDA announce page title, input label and input value, but alert role is not read at all:
![nvda-silent-alert](https://user-images.githubusercontent.com/52075241/85298203-12b96e80-b4a4-11ea-8d94-7e586dab1fbd.png)
 Checked on Chrome 83.0.4103.106, FireFox 77.0.1, Opera 68.0.3618.165
 Also checked with  NVDA Alpha-20317 (https://ci.appveyor.com/api/buildjobs/rbo0m2q24s33nd6x/artifacts/output/nvda_snapshot_alpha-20317,6bf3ae5f.exe, from issue #11250), alert is not read at all.
 

### Expected behavior:
  NVDA should read alert from login page.
  role="alert" seems to be used for dynamic html page, is there any other role or ARIA technique to enable NVDA to read alert contained in html page ?

#### NVDA version:
NVDA 2020.1 installed, then install this one from issue #11250 
 NVDA Alpha-20317 https://ci.appveyor.com/api/buildjobs/rbo0m2q24s33nd6x/artifacts/output/nvda_snapshot_alpha-20317,6bf3ae5f.exe

#### Windows version:
Windows 10 Entreprise [1909] 64bits 

#### Does the issue still occur after restarting your computer?
not tried.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
see above

#### If addons are disabled, is your problem still occuring?
not tried.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes, Alert still not read at all.

**Comment by Adriani90** [comment]
cc: @jcsteh for Firefox
cc: @ObjectInSpace maybe you can consider looking into this for Chrome?

I assume both browsers expose this information properly, if this example is fully compliant with Aria spec. Right?

**Comment by jcsteh** [comment]
From what I can see, the alert is always displayed. It would only be read when focusing the input if the act of focusing the input caused the alert to be shown.
