### ISSUE TITLE
NVDA causes Office 365 to crash when typing

### ISSUE THREAD

**Issue by Asher3195** [nvaccess/nvda#11308]
#### NVDA installed/portable/running from source: Running from SSD on Laptop
Core i5 5200u
8GB of RAM
256GB SSD with 49GB free

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes, made the issue worse as now Outlook now gives constant ``Not the default application``, will not stop popping up

**Comment by Asher3195** [comment]
INFO - __main__ (14:45:47.368) - MainThread (10472):
Starting NVDA version 2020.1
INFO - core.main (14:45:47.503) - MainThread (10472):
Config dir: C:\Users\Danyela\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (14:45:47.503) - MainThread (10472):
Loading config: C:\Users\Danyela\AppData\Roaming\nvda\nvda.ini
INFO - core.main (14:45:47.689) - MainThread (10472):
Using Windows version 10.0.18363 workstation
INFO - core.main (14:45:47.689) - MainThread (10472):
Using Python version 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)]
INFO - core.main (14:45:47.690) - MainThread (10472):
Using comtypes version 1.1.7
INFO - core.main (14:45:47.690) - MainThread (10472):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDriverHandler.setSynth (14:45:48.249) - MainThread (10472):
Loaded synthDriver sapi5
INFO - core.main (14:45:48.250) - MainThread (10472):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5 with six version 1.12.0
INFO - brailleInput.initialize (14:45:48.252) - MainThread (10472):
Braille input initialized
INFO - braille.initialize (14:45:48.252) - MainThread (10472):
Using liblouis version 3.12.0
INFO - braille.initialize (14:45:48.255) - MainThread (10472):
Using pySerial version 3.4
ERROR - braille.BrailleHandler.setDisplayByName (14:45:53.450) - MainThread (10472):
Error initializing display driver baum for kwargs {'port': 'auto'}
Traceback (most recent call last):
  File "braille.pyc", line 1725, in setDisplayByName
  File "brailleDisplayDrivers\baum.pyc", line 118, in __init__
RuntimeError: No Baum display found
INFO - braille.BrailleHandler.setDisplayByName (14:45:53.467) - MainThread (10472):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - core.main (14:45:53.711) - MainThread (10472):
Java Access Bridge support initialized
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (14:45:53.726) - _UIAHandler.UIAHandler.MTAThread (7764):
UIAutomation: IUIAutomation6
INFO - core.main (14:45:53.895) - MainThread (10472):
NVDA initialized
INFO - config.ConfigManager._loadConfig (15:04:33.770) - MainThread (10472):
Loading config: None
WARNING - config.profileUpgrader.upgrade (15:04:33.774) - MainThread (10472):
Error saving configuration; probably read only file system
INFO - synthDriverHandler.setSynth (15:04:34.064) - MainThread (10472):
Loaded synthDriver oneCore
INFO - brailleInput.initialize (15:04:34.064) - MainThread (10472):
Braille input initialized
INFO - braille.initialize (15:04:34.064) - MainThread (10472):
Using liblouis version 3.12.0
INFO - braille.initialize (15:04:34.065) - MainThread (10472):
Using pySerial version 3.4
INFO - braille.BrailleHandler.setDisplayByName (15:04:34.070) - MainThread (10472):
Loaded braille display driver noBraille, current display has 40 cells.
INFO - core.resetConfiguration (15:04:34.071) - MainThread (10472):
Reverted to saved configuration
INFO - braille.BrailleHandler.setDisplayByName (15:04:39.277) - braille._BgThread (2732):
Loaded braille display driver noBraille, current display has 40 cells.
INFO - braille.BrailleHandler.setDisplayByName (15:05:19.478) - braille._BgThread (2732):
Loaded braille display driver noBraille, current display has 40 cells.
INFO - braille.BrailleHandler.setDisplayByName (15:05:48.171) - braille._BgThread (2732):
Loaded braille display driver noBraille, current display has 40 cells.
INFO - braille.BrailleHandler.setDisplayByName (15:06:21.363) - braille._BgThread (2732):
Loaded braille display driver noBraille, current display has 40 cells.
INFO - braille.BrailleHandler.setDisplayByName (15:06:26.503) - braille._BgThread (2732):
Loaded braille display driver noBraille, current display has 40 cells.
INFO - braille.BrailleHandler.setDisplayByName (15:06:31.647) - braille._BgThread (2732):
Loaded braille display driver noBraille, current display has 40 cells.
INFO - braille.BrailleHandler.setDisplayByName (15:06:36.795) - braille._BgThread (2732):
Loaded braille display driver noBraille, current display has 40 cells.
INFO - braille.BrailleHandler.setDisplayByName (15:06:42.958) - braille._BgThread (2732):
Loaded braille display driver noBraille, current display has 40 cells.
INFO - braille.BrailleHandler.setDisplayByName (15:06:48.087) - braille._BgThread (2732):
Loaded braille display driver noBraille, current display has 40 cells.
INFO - braille.BrailleHandler.setDisplayByName (15:07:52.461) - braille._BgThread (2732):
Loaded braille display driver noBraille, current display has 40 cells.
ERROR - RPC process 4564 (nvda_slave.exe) (15:07:52.787) - Dummy-2 (10320):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 99, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1245, in GetActiveObject
  File "_ctypes/callproc.c", line 935, in GetResult
OSError: [WinError -2147221021] Operation unavailable
ERROR - RPC process 11040 (OUTLOOK.EXE) (15:07:55.384) - Dummy-2 (10320):
Thread 6296, build\x86_64\remote\outlook.cpp, nvdaInProcUtils_outlook_getMAPIProp::<lambda_bf1b1bfd9b252bba03325198d027afc0>::operator (), 101:
Could not fetch MAPI property, code -2147467259

INFO - braille.BrailleHandler.setDisplayByName (15:07:57.591) - braille._BgThread (2732):
Loaded braille display driver noBraille, current display has 40 cells.
ERROR - RPC process 11040 (OUTLOOK.EXE) (15:07:57.816) - Dummy-3 (3900):
Thread 6296, build\x86_64\remote\outlook.cpp, nvdaInProcUtils_outlook_getMAPIProp::<lambda_bf1b1bfd9b252bba03325198d027afc0>::operator (), 101:
Could not fetch MAPI property, code -2147467259

ERROR - RPC process 11040 (OUTLOOK.EXE) (15:07:58.711) - Dummy-3 (3900):
Thread 6296, build\x86_64\remote\outlook.cpp, nvdaInProcUtils_outlook_getMAPIProp::<lambda_bf1b1bfd9b252bba03325198d027afc0>::operator (), 101:
Could not fetch MAPI property, code -2147467259

ERROR - RPC process 11040 (OUTLOOK.EXE) (15:08:01.570) - Dummy-3 (3900):
Thread 6296, build\x86_64\remote\outlook.cpp, nvdaInProcUtils_outlook_getMAPIProp::<lambda_bf1b1bfd9b252bba03325198d027afc0>::operator (), 101:
Could not fetch MAPI property, code -2147467259

INFO - braille.BrailleHandler.setDisplayByName (15:08:02.732) - braille._BgThread (2732):
Loaded braille display driver noBraille, current display has 40 cells.
ERROR - RPC process 11040 (OUTLOOK.EXE) (15:08:03.704) - Dummy-4 (4972):
Thread 6296, build\x86_64\remote\outlook.cpp, nvdaInProcUtils_outlook_getMAPIProp::<lambda_bf1b1bfd9b252bba03325198d027afc0>::operator (), 101:
Could not fetch MAPI property, code -2147467259

ERROR - RPC process 11040 (OUTLOOK.EXE) (15:08:04.624) - Dummy-4 (4972):
Thread 6296, build\x86_64\remote\outlook.cpp, nvdaInProcUtils_outlook_getMAPIProp::<lambda_bf1b1bfd9b252bba03325198d027afc0>::operator (), 101:
Could not fetch MAPI property, code -2147467259

ERROR - RPC process 11040 (OUTLOOK.EXE) (15:08:05.493) - Dummy-4 (4972):
Thread 6296, build\x86_64\remote\outlook.cpp, nvdaInProcUtils_outlook_getMAPIProp::<lambda_bf1b1bfd9b252bba03325198d027afc0>::operator (), 101:
Could not fetch MAPI property, code -2147467259

ERROR - RPC process 11040 (OUTLOOK.EXE) (15:08:10.104) - Dummy-5 (8684):
Thread 6296, build\x86_64\remote\outlook.cpp, nvdaInProcUtils_outlook_getMAPIProp::<lambda_bf1b1bfd9b252bba03325198d027afc0>::operator (), 101:
Could not fetch MAPI property, code -2147467259

ERROR - RPC process 11040 (OUTLOOK.EXE) (15:08:11.161) - Dummy-6 (10796):
Thread 6296, build\x86_64\remote\outlook.cpp, nvdaInProcUtils_outlook_getMAPIProp::<lambda_bf1b1bfd9b252bba03325198d027afc0>::operator (), 101:
Could not fetch MAPI property, code -2147467259

INFO - braille.BrailleHandler.setDisplayByName (15:08:18.278) - braille._BgThread (2732):
Loaded braille display driver noBraille, current display has 40 cells.
INFO - braille.BrailleHandler.setDisplayByName (15:08:23.417) - braille._BgThread (2732):
Loaded braille display driver noBraille, current display has 40 cells.

**Comment by Adriani90** [comment]
@Asher3195 please try following:
* Disable all addons and try to reproduce the issue
* Try to reproduce the issue with no braille display connected. Is it still occuring?
* Update your office version in outlook > file ribbon > office account > update options > update now.

I am also on KB german on Outlook 365, I cannot rpeproduce this issue with NVDA 2020.2 Beta 2. But I don't have a braille display connected, so it might be important to know if you can reproduce without braille display as well.

**Comment by Brian1Gaff** [comment]
As a matter of interest what other email clients are installed?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Brian1Gaff** [comment]
You have not been playing about with Braille support in narrator have you? 
Also there does seem to be problems writing to your disc in places. I'm 
thinking that the problem is not nvda but either a screwed up install, or 
something which has been corrupted.
 I'll leave it to people more experienced than I, but do you have a Braille 
display or not how you can have  one but have  40 cells is somewhat bizarre. 
The driver is apparently missing. Also problems retrieving the  saved 
settings when you change them, ie they are not written, and the apparent 
issue  on retrieving the data Outlook needs would I'd imagine tell you why 
the thing thinks its not the default and falls over a lot in office.

I hate to suggest this, and hope I'm wrong, but about a month before my 
Samsung ssd trashed itself these were the sort of things hat started to 
randomly occur, impossible to verify writes or read back data.
 So back everything up!

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since more than 2.5 years. I am closing as abandoned. if you are still having this issue, please comment on it and we can reopen.
