### ISSUE TITLE
Update CLDR to version 37

### ISSUE THREAD

**Issue by OzancanKaratas** [nvaccess/nvda#11303]
CLDR 37 has been released in [fujiwarat/cldr-emoji-annotation](https://github.com/fujiwarat/cldr-emoji-annotation) repository.

@leonardder, can you update it?

**Comment by dingpengyu** [comment]
[test build](https://ci.appveyor.com/api/buildjobs/4bhiwuid4hkal6ea/artifacts/output%2Fnvda_snapshot_pr11306-20408%2C202de760.exe)
