### ISSUE TITLE
Gmail and Firefox: NVDA keeps jumping in and out of focus mode

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#11301]
## Steps to reproduce:

1. Open Firefox
2. Go to gmail.com, ensuring that you have a gmail account.
3. If you do not have the Standard View enabled, enable it.
4. Wait for a few seconds.

### Actual behavior:

NVDA jumps in and out of focus mode within one second. Note that this only happens in Firefox, and not in Edge Chromium, which are the two browsers on my system.

### Expected behavior:

NVDA should stay in focus mode. Note that this is what happens when using Microsoft Edge Chromium.

### System configuration

Firefox 77,0.1 

#### NVDA installed/portable/running from source:

Both 

#### NVDA version:

2020.2beta2

#### Windows version:

Windows 10, 1909, 64-bit) build 18363.900

#### Name and version of other software in use when reproducing the issue:

None

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes, NVDA 2020.1

#### If addons are disabled, is your problem still occuring?

Yes, or I wouldn't report it...

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes

**Comment by Adriani90** [comment]
Do you have disable browse mode on page load by default enabled in nvda‘s browse mode settings?

**Comment by fisher729** [comment]
Hi.

No. I don't. While this does seem to fix the issue, I do not wish to have
this setting enabled, as it might cause problems when accessing other
sites. Also, as I said, this does not happen in Edge.

**Comment by Adriani90** [comment]
cc: @jcsteh, @MarcoZehe

**Comment by jcsteh** [comment]
@fisher729, can you still reproduce this? I can't reproduce it here.

**Comment by fisher729** [comment]
No. I can no longer reproduce this issue either.
