### ISSUE TITLE
iCloud website broken in Firefox, works in Chromium browsers

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#11307]
### Steps to reproduce:

1.  Open Firefox.
2.  Visit https://www.icloud.com
3.  Log in and perform other authentication steps.
4.  Attempt to click some buttons, such as "Account info", "Find iPhone", or any of the others.
5.  Repeat steps 2 through 4, but this time use a Chromium based browser.

### Actual behavior:

In steps 1 through 4, no button can be selected, or at least if it is, nothing apparently happens as far as NVDA is concerned. I have tried with all of NVDA's methods of pushing a button (space, enter, ctrl+enter, shift+enter, mouce cursor routing and left clicking with numpad divide, object nav. Not all attempts are reflected in the log).

This is all the same as described in #3259, which was closed by @derekriemer but never actually resolved.

Even the pre-login button for downloading iCloud for Windows fails to work in Firefox with NVDA.

However, when attempting in step 5--I tested Brave (then Edge and Chrome, at the request of @josephsl )--the iCloud site and all of its buttons work fine, with simple enter or space based button pushing.

### Expected behavior:

Steps 1-4 should work as step 5 does--that is: the buttons should be able to be pressed.

### System configuration

NVDA installed, 2020.2beta2.
Windows 10 Version 1909 (OS Build 18363.900)
Firefox 77.0.1 (64-bit)
Firefox 68.9.0esr (64-bit)
Brave 1.10.97
Edge 83.0.478.56 (Official build) (64-bit)
Chrome 83.0.4103.97 (Official Build) (64-bit)
Chrome 83.0.4103.116 (Official Build) (64-bit)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, 2019.3.1 (only tested with Firefox ESR - same outcome as current FF).

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

### Other information
Log attached. Marked up with notes of the form `--- comment ---`.
[NVDA icloud.com problems in firefox.log](https://github.com/nvaccess/nvda/files/4839772/NVDA.icloud.com.problems.in.firefox.log)
[iCloud problems with FF ESR under NVDA 2019.3.1.log](https://github.com/nvaccess/nvda/files/4839929/iCloud.problems.with.FF.ESR.under.NVDA.2019.3.1.log)

**Comment by josephsl** [comment]
Hi, just to make sure, does this happen with Chrome or Edge? CC @JCSTeh

**Comment by XLTechie** [comment]
@josephsl  It works with Edge. Added to issue. I will test Chrome, and when that likely works, I will add it as well, although I don't have it on my nearest system.

**Comment by josephsl** [comment]
Hi, one more thing we can try: how about Firefox ESR? Thanks.

**Comment by XLTechie** [comment]
@josephsl 
> 
> Hi, one more thing we can try: how about Firefox ESR?

Okay, I downgraded my more recent Firefox, to the several versions older ESR, and got the identical results (issue annotated).
I'm not really clear on why I just did that though; it seems like if a newer version doesn't work, and the very old version in #3259 didn't work, the ESR failing is entirely to be expected.

I did try the ESR with Firefox add-ons disabled, which I hadn't tried in the newer version. Also, NVDA on that system is 2019.3.1, although neither made any difference to the outcome.

**Comment by josephsl** [comment]
Hi, so it appears this is something that should be brought up to Mozilla and Apple then. Thanks for all the test data – helps us narrow down the problem a lot.

**Comment by Adriani90** [comment]
Just a big tumb up for this description! This makes investigation much easier.

One question, has this problem appeared shortly? I mean were there any significant design updates to the iCloud website in the last time?

**Comment by Adriani90** [comment]
The only thing that might be relevant from this log is following:

```
DEBUGWARNING - Python warning (23:36:43.691) - MainThread (1148):
C:\Program Files (x86)\NVDA\library.zip\keyboardHandler.py:538: DeprecationWarning: Yield() is deprecated
```

However, this is not an error but it seems to occur right after you tried to activate the button.

It seems you have "use screen layout" enabled in browse mode settings for the firefox profile. Could you try to reproduce this with this setting disabled?

**Comment by XLTechie** [comment]
Thank you @Adriani90. Unfortunately, I can't answer your question. It is a site 
I rarely visit. It does seem more accessible now than I remember it being in the 
past, but the past in this context is probably two-three years ago. So NVDA 
itself was a bit different back then.

But Apple is a rather big deal, so it would be preferable if their flagship user 
portal did work in Firefox for NVDA.

**Comment by jcsteh** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1649239

**Comment by jcsteh** [comment]
The iCloud website has now been updated and these controls now work as expected with Firefox and NVDA.
