### ISSUE TITLE
Braille isn't refreshed when opening books in Thorium

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#11302]
[nvda.log](https://github.com/nvaccess/nvda/files/4835072/nvda.log)

### Steps to reproduce:

1. Open Thorium.
2. If no publication is imported yet, press the "Import publication" button and import an epub file, for example, the "Outlook with NVDA" training module.
3. Press Enter on the link corresponding to the ebook to read it.

### Actual behavior:

NVDA reads the content with speech, but braille is not refreshed. Focus has to be moved, for example pressing àlt+tab`, so that the word "panel" disappears and the appropiate content can be presented in braille.

### Expected behavior:

Braille should be refreshed appropiately when a book is opened.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2020.2beta2

#### Windows version:

10.0.18363 workstation

#### Name and version of other software in use when reproducing the issue:

[Thorium v1.3.1-alpha.1.117](https://github.com/edrlab/thorium-reader/releases), by @edrlab 

#### Other information about your system:

Braille display: Focus 40 Blue 5th Generation

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes, with same behavior

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes

**Comment by nvdaes** [comment]
Braille can also be refreshed by moving the review cursor when the book has been opened.
This behavior is not happening running NVDA from portable and source.
It can be fixed using this code in an app module placed in the scratchpad folder, but when the app module is included in appModules folder of NVDA's core, this doesn't work.

```
class AppModule(appModuleHandler.AppModule):

	def event_NVDAObject_init(self, obj):
		if obj.role == controlTypes.ROLE_DOCUMENT:
			eventHandler.queueEvent("gainFocus", obj)
```
🤔

**Comment by JulienCochuyt** [comment]
@nvdaes, just to be sure, you did import `appModuleHandler`, `controlTypes` and `eventHandler` at the top of your module and simply didn't paste it here to be concise, right?

**Comment by nvdaes** [comment]
Thanks Julien for your interest. Yes, I imported appmoduleHandler, controlTypes and eventHandler at the top of the Python file.

**Comment by JulienCochuyt** [comment]
To check that the `AppModule` is active, you can press `nvda+f1` to read the Developer Info or issue `focus.appModule` in the Python Console.
If it reads indeed "thorium" and not "appModuleHandler", you can further check that it is indeed loaded from the source you intend by issuing in the Python Console:
```
import appModules.thorium
appModules.thorium.__file__
```
That way, you'll see if an add-on took priority over your change.

If all of this is fine, you may want to emit a log message from within your custom `event_NVDAObject_init` method, to ensure it is executed.
If it is, then I shall admit I have no clue how this might work from your scratchpad folder and not from the NVDA folder.

**Comment by nvdaes** [comment]
Thanks, I will test your suggestions and provide feedbackhere again.

2020-07-04 13:58 GMT+02:00, Julien Cochuyt <notifications@github.com>:

**Comment by nvdaes** [comment]
@JulienCochuyt , after testing your suggestions in the Python console and using `NVDA+f1`, I confirm that the created app module for Thorium is present in NVDA when I run it from source (`pythonw.exe nvda.pyw`), but it's not copied when I install NVDA from the created launcher (`scons launcher`). I don't know if this is an error at installation or produced because the app module is not copied to NVDA when Icreate  the launcher.

**Comment by nvdaes** [comment]
Seems that the app module is not copied in the launcher, since I
created a portable copy and it's not there. I will try to perform
scons clean in case it works.

2020-07-04 18:03 GMT+02:00, nvdaes <notifications@github.com>:

**Comment by nvdaes** [comment]
I have problems with my local computer, and finally I have built the
NVDA launcher with GitHub Actions uploading the artifact, after
running sconst tests. After that I have installed the built snapshot
of NVDA and now the app module works as expected.
I will test it and I may create a pull request when Thorium 1.4.0
stable is released, unless it is not published soon, but I think it
will be released in a few days seeing the progress of Thorium project.
The built launcher and GitHub Action output can be found at
https://github.com/nvdaes/nvda/runs/837443544?check_suite_focus=true
Thanks for all your help, Julien.

2020-07-04 18:19 GMT+02:00, nvdaes <notifications@github.com>:

**Comment by nvdaes** [comment]
Unfortunately, though I addressed this locally with an app module, this causes that the state of buttons (pressed or not pressed) is not announced, which is more important than this.
There is another issue with thorium panels with NVDA: when reading a book and pressing 'windows+m', then alt tab, a panel is shown, not the document.
All this can be fixed maximizing the window. Also, the issue described initially doesn't happen if braille follows to review cursor and disappears performing the command to "read all"
/cc: danielweck

**Comment by nvdaes** [comment]
Fixing myself:
/cc: @danielweck

2020-07-12 13:24 GMT+02:00, nvdaes <notifications@github.com>:

**Comment by Adriani90** [comment]
@nvdaes what part of the issue remains to be solved in NVDA? Please give an update so that we can continue discussion on this further. Are you planning to raise a PR with NVDA? Or are you contributing to Thorium directly to solve this?

**Comment by nvdaes** [comment]
Ideally, the isues described here should be fixed if possible.
Otherwise, we could document in the community wiki how users can
workaround to solve this manually, that is, maximizing the window.
I have cloned both NVDA and Thorium source code trying to find a
solution modifying both projects, and if I find a way to fix this, I
would raise a PR in any of them.
Anyway, maybe better to fix it via an NVDA app module, since Thorium
is accessible to other screen readers and works with other operating
systems, so when something is modified in Thorium, we need to ensure
it doesn't affect the compatibility with other screen readers or
systems.
I mentioned @edrlab and @danielweck, the company and one of the
developers of Thorium, respectively, so they can be informed.

2020-07-13 23:16 GMT+02:00, Adriani90 <notifications@github.com>:

**Comment by Adriani90** [comment]
@nvdaes how is it now with NVDA 2023.2 and the last version of Thorium?

**Comment by Adriani90** [comment]
No updates from @nvdaes upon request since many years, I am closing as abandoned. if you are still having this issue, please comment and we can reopen.
