### ISSUE TITLE
In the add-on manager, allow to enable or disable multiple add-ons in one time

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#11317]
### Is your feature request related to a problem? Please describe.

When I encounter an issue in NVDA, I test with add-ons disabled if the issue still persists. If it does not, I have to find the add-on responsible for this issue by disabling some add-ons by dichotomy. Selecting or unselecting half of the add-ons one by one is tedious in a list of 15 add-ons or so.
Also being able to easily disable all add-ons but one would be very useful to test a specific add-on without any side effect of other add-ons.

### Describe the solution you'd like

* Be able to select multiple add-ons in the add-on list
* For any multiple selection, be able to enable all of them or disable all of them; the "Enable add-on" and "Disable add-on" buttons should then be two separate buttons in order to address the case where some add-ons in the multiple selection are enabled and some other disabled.
* Also the "Remove add-on" button could be active for multiple selection to allow deleting many add-ons in one time.
* The "About" and "Help" buttons should be greyed out (disabled) in case the selection contains 2 or more add-ons.
* The "About", "Help", "Enable", "Disable" and "Remove" buttons should be greyed out in case the selection contains zero item. It is not useful to allow a 0-item selection; however, I think that in lists allowing multiple selection, it is not usual and maybe not easy to forbid an empty selection.

### Describe alternatives you've considered

None

### Additional context

N/A

**Comment by josephsl** [comment]
Hi, a possible yet technical alternative might be to let users specify add-ons to be disabled via command line switches (see #3090 for a brief discussion). Thanks.

**Comment by JulienCochuyt** [comment]
@CyrilleB79,
Multiple selection lists can be a bit tedious at first for beginners.

For quickly disabling/enabling add-ons, one can already proceed by using the accelerators without leaving the list.
That is, when a given add-on is selected in the list, press `alt+d` to disable it, or `alt+e` to enable it (`alt+a` with the French locale). Note that the focus does not land on the button, but rather stays on the list at the same position.
Then, `down arrow` to select the next add-on and repeat if you wish to disable the next one.
This surely uses more keystrokes than a multiple selection list would require, but also allows for a simpler UI.

To quickly delete a selection of add-ons, one can also open the `addons` folder in their user profile and simply delete the corresponding folders (given one knows the technical names of the add-ons to delete).

**Comment by lukaszgo1** [comment]
Maybe conversion of the add-ons list to a checkable list would solve the problem here? For beginners the behavior would stay the same and the use case described here could be accomplished.

**Comment by CyrilleB79** [comment]
Thanks to all for your comments. Replying globally:

@josephsl you wrote:
> Hi, a possible yet technical alternative might be to let users specify add-ons to be disabled via command line switches (see #3090 for a brief discussion). Thanks.

IMO, this does not address the need to enable or disable add-ons quickly as described in initial comment of this issue.

@JulienCochuyt you wrote:

> Multiple selection lists can be a bit tedious at first for beginners.

Multi selection lists are present everywhere, e.g. in Windows Explorer and e-mail clients. And I haven't heard that it was a difficulty for beginners. IMO the main point is that a beginner should be able to perform the most standard actions without being able to perform a multiple selection. This is the case in the solution I am suggesting since the user should still be able to select only one add-on by using up/down arrow and then press "Enable", "Disable" or "Remove" button.
Let me know however if I have missed something regarding beginner UX since you have clearly more feedback from them than I.

> For quickly disabling/enabling add-ons, one can already proceed by using the accelerators without leaving the list.
> That is, when a given add-on is selected in the list, press `alt+d` to disable it, or `alt+e` to enable it (`alt+a` with the French locale). Note that the focus does not land on the button, but rather stays on the list at the same position.
> Then, `down arrow` to select the next add-on and repeat if you wish to disable the next one.

Yes, I already proceed this way. The goal of this issue was to have a still quicker way to perform these actions.

> To quickly delete a selection of add-ons, one can also open the `addons` folder in their user profile and simply delete the corresponding folders (given one knows the technical names of the add-ons to delete).

This should work in most cases; this is however not recommanded, e.g. in case the add-on contains uninstall tasks.

@lukaszgo1 you wrote:

> Maybe conversion of the add-ons list to a checkable list would solve the problem here? For beginners the behavior would stay the same and the use case described here could be accomplished.

I have also thought to this solution. I did not mentioned this as it has some drawbacks:
* The UX seems less clear to me. We would have a checkable list here. But checking or unchecking items would enable/disable add-ons whereas the main goal of add-on manager is not to enable/disable the add-ons but to install and remove them.
* This does not handle the use case of multiple add-on removal.

**Comment by Brian1Gaff** [comment]
I think that would be more laborious than disabling them one at a time from 
the interface, personally!
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by lukaszgo1** [comment]
Sorry for not being clear enough. I haven't thought about checking and unchecking add-ons as a way of enabling/disabling them but as a way to create multiple selection i.e. when nothing is checked disable, enable and uninstall operates on the add-on with focus and when there is a selection on an entire selected range of add-ons.

**Comment by CyrilleB79** [comment]
> 
> Sorry for not being clear enough. I haven't thought about checking and unchecking add-ons as a way of enabling/disabling them but as a way to create multiple selection i.e. when nothing is checked disable, enable and uninstall operates on the add-on with focus and when there is a selection on an entire selected range of add-ons.

I disagree with you on this proposal. Indeed, you get a situation where pressing "Disable" button (for example) can perform 2 different actions:
* It disable the focused item
OR
* it disable the selected items
The user has to know how many items are checked to know to what the "Disable" action apply. This is not good at all for UX.

**Comment by amirmahdifard** [comment]
also, please add a toggel option to disable or enable all addons.
