### ISSUE TITLE
NVDA stopped responding after initial installation and system reboot

### ISSUE THREAD

**Issue by subbuatos** [nvaccess/nvda#11314]
NVDA is working only when initial version 2020.1 installed. After system restart, NVDA stopped responding. I see NVDA ICON in system tray and not responding for any click to view menu.

### Steps to reproduce:
Install NVDA and do system reboot for non responsive. However this is happening on random systems.

### Actual behavior:
After system restart, NVDA stopped responding. I see NVDA ICON in system tray and not responding for any click to view menu.

### Expected behavior:
NVDA should respond for right click to vew menus. Should do audio navigation.

### System configuration
LENOVO Thinkpad T480, 8GB RAM, 500GB HDD

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.1

#### Windows version:
Windows 10 1809

#### Name and version of other software in use when reproducing the issue:
All

#### Other information about your system:
NA

### Other questions
NA

#### Does the issue still occur after restarting your computer?
YES

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes and same behavior. 

#### If addons are disabled, is your problem still occuring?
I am not sure which addons and where to disable

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Not yet tried

**Comment by Adriani90** [comment]
Can you open the nvda menu with nvda+n, insert+n or with right click on system tray icon?
I assume the sound card is not on mute after system reboot and the volume is high enough. Is this correct?
Which synthesizer is selected in the synthesizer dialog when nvda does not respond? Is it eSpeak?

**Comment by subbuatos** [comment]
Right click on system tray icon is not working. Also sound card is not on mute and volume is set to high.

**Comment by subbuatos** [comment]
Also how can I run COM registry tool ? will this be available under NVDA menu in system tray when I right click ?

**Comment by subbuatos** [comment]
Update :
NVDA is working properly with elevated access (Admin). However when I try to open with normal user credentials, it is not working. I ran COM Register tool with elevated (Admin) access and completed successfully. However NVDA is still not responding with normal user credentials after system reboot. This issue is happening for multiple users.

**Comment by Brian1Gaff** [comment]
As a matter of interest, if you had kept it running after installation, did 
it continue to work? Also, if you run it from the archive without installing 
it what happens then?

I think you can run the  repair tool from any running copy via tools, so try 
that first on a running copy, then try a fresh install.
 What synth does it come up using by default on your machine?
  Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by subbuatos** [comment]
To Brian1Gaff
After first installation of NVDA, its working with normal user credentials. After system restart, it is stopped responding. All I see is NVDA ICON in system tray and not responding when I right click NVDA from system tray.

**Comment by josephsl** [comment]
Hi, what happens if you press Insert and letter N? Does NVDA menu appear at the center of the screen? If not, chances are that NVDA might not be running at all. Thanks.

**Comment by subbuatos** [comment]
Not responding when I press N. But I see NVDA icon in system tray and task manager.

**Comment by josephsl** [comment]
Hi, that’s strange. If nvda.exe is showing up in Tasks Manager’s details view, chances are that it could be running in a different user session (unlikely) or something odd is happening on this system. Thanks.

**Comment by XLTechie** [comment]
Is it possible that there is a second sound device, and NVDA is using that?

**Comment by subbuatos** [comment]
No, there is no dual sound device.

**Comment by Adriani90** [comment]
cc: @michaelDCurran

**Comment by Adriani90** [comment]
@subbuatos did you see this issue also in NVDA 2023.1?

**Comment by Adriani90** [comment]
I wonder if this could some how be related to #11553?

**Comment by Adriani90** [comment]
We didn't get any updates form the initial author upon request since many years. I am closing as abandoned. If you are still having this issue, please comment and we can reopen.
