### ISSUE TITLE
two incorrect links i found in nvda 2019.3 whats new!

### ISSUE THREAD

**Issue by zahra21** [nvaccess/nvda#11324]
hello every one.
while i use windows xp, and nvda 2017.2 and 2017.3 are the best versions for me, but i always follow github, nvda new features, changes and bug fixes.
i should i read hundreds of reports in github about nvda!
and for this reason, i am familiar with various versions of nvda and their changes.
however, two links in nvda 2017.3 whats new, i believe that they are not related to their discriptions and i believe that the link numbers are incorrect.

• In Start menu for Windows 10 Anniversary Update and later, NVDA will announce details of search results. (#10232)
• In the Settings app in Windows 10 April 2018 Update and later, NVDA will no longer announce progress bar information for volume meters found in the System/Sound page. (#10284)

**Comment by josephsl** [comment]
Hi,

You're right. Quentin, any thoughts?

Thanks.

**Comment by zahra21** [comment]
hi joseph.
thanks so much for your quick response and attention.
i always sincerely pray for all of you nvda developers and request divine infinite and especial mercy and blessings for you!
i believe that i found the correct link for the second one.
i just copy peist the entire sentence in the google search box!
i peisted:
In the Settings app in Windows 10 April 2018 Update and later, NVDA will no longer announce progress bar information for volume meters found in the System/Sound page. 
github.com/nvaccess/nvda/issues
the first result was:
https://github.com/nvaccess/nvda/pull/10412

**Comment by zahra21** [comment]
i also found correct link for the first item.
https://github.com/nvaccess/nvda/pull/10340
