### ISSUE TITLE
Partial sleep mode (only report messages generated from a plugin)

### ISSUE THREAD

**Issue by codeofdusk** [nvaccess/nvda#11333]
### Is your feature request related to a problem? Please describe.
Some applications provide no useful information via NVDA's usual channels – in these cases, app modules can be developed to produce messages making the app accessible using custom behaviour. ([Example](https://github.com/codeofdusk/emacspeak-nvda))

### Describe the solution you'd like
A "partial sleep mode" should be developed, which behaves like normal sleep mode except special messages from a plugin should be reported. Possibly a flag could be added to `speech.speak` and `braille.message`, `bypassSleepMode`, which always reports regardless of the sleep mode setting?

### Describe alternatives you've considered
None, but open to ideas.

### Additional context
Admittedly this is a fairly rare use case, but I think core changes are necessary to enable it.

**Comment by codeofdusk** [comment]
Cc @leonardder @michaelDCurran @jcsteh @derekriemer.

**Comment by josephsl** [comment]
Hi, I think this might be generalizable to “speech on demand” feature later (beyond the scope of this issue). Thanks.

**Comment by codeofdusk** [comment]
Actually, I don't think we need to do this (it seems that `speech.speak` actually disregards sleep mode already!) Closing the issue.

> “speech on demand” feature

What do you mean by this?
