### ISSUE TITLE
nvwave/output devices enumeration: first output device is an empty string in Windows 10 Version 2004 and later

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#11349]
Hi,

Reported on Twitter and subsequently confirmed:

### Steps to reproduce:
With Windows 10 Version 2004 (May 2020 Update) installed, open NVDA's synthesizer dialog (Control+NVDA+S). Then see which devices are listed under output device combo box.

### Actual behavior:
An empty string is displayed at the top.

### Expected behavior:
A default output device name (such as Microsoft Sound Mapper) is shown.

#### NVDA installed/portable/running from source:
Installed and portable

#### NVDA version:
2020.1, 2020.2 beta 2, alpha-20514

#### Windows version:
Windows 10 Version 20H2 beta (build 19042.330)

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
Multiple sound devices present (internal sound card, wireless headset)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Versions listed above exhibit the same problem

#### If addons are disabled, is your problem still occurring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Not applicable

### Additional context:
This issue occurs in Version 2004 and later (Version 1909 did return the correct name for the first selected output device). This suggests something going on with device capabilities functions found in winmm.dll which are used to build output device names.

Thanks.

**Comment by stickbear2015** [comment]
I was able to reproduce this with 2019.3.X as well.

**Comment by jage9** [comment]
Confirmed with latest snapshot. TO clarify, there is no Windows Sound Mapper option, so if Windows was providing that placeholder name in the past, it is not now. Looked in latest TeamTalk, and it is exhibiting similar behavior, with placeholder text of input and output for the default.
So if Windows is providing a blank, NVDA may need to supply its own text of default, which can probably be assumed if the device name is blank and also first in the list.

**Comment by josephsl** [comment]
Hi,

Note: this issue only affects 2004 and 20H2 - Microsoft Sound Mapper is listed in build 20161 (dev).

Thanks.Hi,

Note that this issue is for 2004 and 20H2 - Microsoft Sound Mapper is present in build 20161 (dev). I'm looking at placeholder text that Windows already provides to avoid adding yet another translatable string that could be discarded later.

Thanks.

**Comment by agtheblade** [comment]
Hello everyone. I was the one who originally reported the bug. Just as an experiment, I turned on Narrator while in the NVDA synthesizer dialog and even Narrator was not able to read the Microsoft sound mapper item. Not sure if that means anything but figured I'd put that out there.

**Comment by josephsl** [comment]
Hi, upon further investigation, it was determined that this is Windows release specific and affects all programs wishing to enumerate wave output devices. The good news is that it will be fixed in a future Windows 10 update. Once I finish looking at language issues (that is, making sure the setting in question is language independent), I’ll submit a pull request targeting alpha snapshots. Thanks.

**Comment by josephsl** [comment]
Hi,

It appears the term "Microsoft Sound Mapper" has been localized in other languages. Therefore this must be an alpha-level change.

Thanks.

**Comment by XLTechie** [comment]
On Tue, 7 Jul 2020, Leonard de Ruijter wrote:

> I don't think this is necessary. If even Windows Narrator suffers from this issue, it is definitely an issue in Windows and a work around for this doesn't
> sound very important to me.

You might want to think of PR. "Well, NVDA doesn't have that problem, why 
does your screen reader?" :)

**Comment by josephsl** [comment]
Indeed, fixed in a summer cumulative update, therefore this will be reverted. Thanks.
