### ISSUE TITLE
Advanced settings: the value does not restore to default for certain settings when activating the restore default settings button

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#11342]
### Steps to reproduce:
1. Open NVDA's advanced settings
2. Change the value for all the settings in this category to a value which is not the default

### Actual behavior:
Following settings do not restore to default when activating the restore to default button:
* Use the new typed character support in Windows Console when available
* Attempt to cancel speech for expired focus events
* carret movement timeout
* debug logging items in the list

### Expected behavior:
All the settings should restore to their default value when activating the coresponding button. This is very important in my view, if for example new users activate something accidentally and forgot about it.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Version: alpha-20514,e87d8ab1

#### Windows version:
Windows 10 2004 update

#### Name and version of other software in use when reproducing the issue:
n/a

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If addons are disabled, is your problem still occuring?
yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
n/a

**Comment by Adriani90** [comment]
cc: @codeofdusk, @feerrenrut

**Comment by codeofdusk** [comment]
I think this issue is a good candidate for a good for new dev label. For those working on it: search for `restoreToDefaults` in `source/gui/settingsDialogs.py`.

It might also be worth considering resetting these to the default on version bump, especially as feature flag defaults might change (mitigated for UIA conhost by the ternary setting in config but binary in GUI until default approach).

**Comment by lukaszgo1** [comment]
@Adriani90 It looks like #11344 also addresses this one. Could you please confirm with the build from this pr?

**Comment by XLTechie** [comment]
On Mon, 6 Jul 2020, Bill Dengler wrote:

> It might also be worth considering resetting these to the default on version bump, especially as feature flag defaults might change (mitigated for UIA
> conhost by the ternary setting in config but binary in GUI until default approach).

It has not been the habit of NVDA to unilaterally update settings on upgrades to 
fit the new normal, if the existing config has something else. Or has it and 
I've missed that?

These settings are called "advanced", not "experimental", even though that is 
often their use. If they were experimental, I could more easily expect the 
unexpected--I.E. their change without notice--but advanced implies that they are 
merely settings that normal users won't need.

If the user's preferences aren't going to be honored, I would rather see a 
"testing" panel or something, where settings under consideration or revision are 
worked out. Then when those settings get a default in a stable release, they get 
moved to "Advanced", or another preferred panel, with the preferred default, and 
don't get messed with again except by the user.

If testing was activated, then I could well see those settings changing to 
preferred testing defaults in every new alpha install even. That wouldn't bother 
me. Changing them in advanced though, seems a little user-unexpected.

**Comment by Adriani90** [comment]
@lukaszgo1 thanks for the quick work on this. yess your PR solves this issue as well.

**Comment by Adriani90** [comment]
Close as fixed by #11344

**Comment by feerrenrut** [comment]
@XLTechie generally I agree, however, there is a pretty specific warning on the advanced panel. 

Attempting to expose feature flags to users is only a fairly recent thing, the process and UX will improve with time. I agree a dedicated "experimental features" or "feature preview" section would make sense. 

There shouldn't be a need to change user selected values for feature flags. Only if the feature is reverted, or the old implementation is dropped.
