### ISSUE TITLE
Zoom: More Options for {Screen Name} button cannot be reliably activated

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#11343]
### Steps to reproduce:
1 Join a Zoom meeting.
2 Open the Participants panel.
3 Press Tab a couple of times until you reach the Participants list wherein you can arrow up or down to focus on any of the current meeting attendees (including yourself).
4 Tab twice again until you reach the More options for {screen name of participant under focus} button.
5 Try to activate it: Spacebar, Enter, move mouse pointer to current navigator object command and emulate left mouse click command, etc.

### Actual behavior:
The button does not get activated.

### Expected behavior:
The button should get activated and a couple options are revealed.

### Notes
* This issue does not occur consistently. However, I would put its frequency as well above 50% based on the 15-20 times I tried to access it in the past two days. When the button is activable, then Spacebar does the job, but if Spacebar fails, that means no other intuitive alternative succeeds either. If there is a work-around that has worked for you that I am missing, please let me know.
* I have not experienced this issue with other buttons in Zoom. Some such buttons are Mute, Open/Close Participants Panel, and Leave Room/Meeting. That is not to claim that no other button in Zoom exhibits this issue; I am just saying that I am aware of none.

### Impact
* In general, Zoom is being heavily used right now and is likely to remain so in the foreseeable future. Education; work; competitive, informative, and social events, are all being conducted over Zoom. Hence, I would argue that *any* accessibility issue with Zoom should be taken seriously and be resolved on priority.
* Still, let me share my use case for regularly needing to access the More Options for {screen name} button. In a tournament wherein everyone was sorted into rooms, everyone had to edit their screen name according to the room they were assigned in each round based on allocations, so that the hosts could then easily put people into respective breakout rooms. Hence, the moment the draw was released, I needed to instantly change my screen name to reflect my assignment. My failure to do so caused avoidable confusion and embarrassment. The reason for this is that the Edit Name option can be accessed through More Options for {screen name} itself. Also, I would think that people would need to access the More Options for {screen name} button to perform other actions and in other scenarios too.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.2 Beta 1

#### Windows version:
8.1

#### Name and version of other software in use when reproducing the issue:
Version: 5.0.2 (24046.0510)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by Adriani90** [comment]
Did you try to switch to focus mode and then activate the button with enter or space bar?

**Comment by lukaszgo1** [comment]
@Adriani90 Zoom is a classic win32 app so no browse mode is involved. @bhavyashah May I ask why you're believing this to be an NVDA issue rather than a Zoom one? Have you for example been able to activate this button consistently with another screen reader?

**Comment by Adriani90** [comment]
@bhavyashah are you still having this problem with NVDA 2022.4`? I cannot reproduce it in the last version of Zoom with NVDA 2022.4.

**Comment by bhavyashah** [comment]
@lukaszgo1 You are right. I should have tested with another screen reader before reporting this app-specific issue. My bad.
@Adriani90 Me neither using Zoom version 5,15,7,20303 and nVDA 2023.2! Closing this ticket.
