### ISSUE TITLE
Attempt to cancel speech for expired focus events: Title of NVDA Settings dialog omited

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#11361]
### Steps to reproduce:
1. Enable `Attempt to cancel speech for expired focus events`
2. Open the NVDA Settings dialog:

### Actual behavior:
NVDA announces: Categories:  list General  1 of 16

### Expected behavior:
NVDA announces: NVDA Settings: General (normal configuration)  dialog Categories:  list General  1 of 16

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-20514

#### Windows version:
Windows 10 2004

**Comment by leonardder** [comment]
cc @feerrenrut

**Comment by feerrenrut** [comment]
I think this is a duplicate of #11144 (Attempt to cancel speech for expired focus events: dialog title discarded when finding text in browse mode). This issue causes system tests to fail an is currently blocking PR #11266 (Enable cancellable speech by default).

**Comment by leonardder** [comment]
Ah, I'm sorry. I thought #11144 was supposed to be fixed, that's why I opened a new issue.

**Comment by feerrenrut** [comment]
I have cleared the milestone on #11144 to help clarify.
