### ISSUE TITLE
Enabling Focus Highlighting causes sluggishness when using NVDA with USB-attached monitor

### ISSUE THREAD

**Issue by kensgists** [nvaccess/nvda#11362]
When turning on focus highlighting with an external monitor attached, all mouse cursor movement and interaction is sluggish. Problem does not occur when monitor is not attached. Monitor is attached in configuration in which my desktop is extended from the laptop onto the external monitor.

### Steps to reproduce:
* Attach laptop via USB-C to external display monitor
* Set secondary display so that desktop is "extended" across the two displays (laptop and monitor)
* Enable any/all option(s) in NVDA's Focus Highlight group (Preferences > Vision: Focus Highlighting)

### Actual behavior:
* Mouse interactivity becomes sluggish, with mouse moving staccato and having a lot of latency between input and mouse cursor movement.

### Expected behavior:
* Focus highlighting should not negatively impact mouse cursor input

#### NVDA installed/portable/running from source:
* Installed

#### NVDA version:
* 2020.1

#### Windows version:
* 10.0.19041
#### Name and version of other software in use when reproducing the issue:
* NA. No other apps running

#### Other information about your system:
* Lenovo 4th gen X1 yoga with 16GB RAM and Core i7 

#### Does the issue still occur after restarting your computer?
* Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
* Had used community contributed focus highlighter for many years with no issues

#### If addons are disabled, is your problem still occuring?
* NA

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
* No

**Comment by leonardder** [comment]
The highlighter is a window that continuously refreshes itself and forces itself on top of all other windows. If there is a bit of latency involved with drawing the screen, I think this is expected behavior.
Would you by any chance be able to test this with NVDA 2019.2 and the Focus Highlight add-on?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years. i am closing this as abandoned. feel free to comment on it in case you still have this issue and we can reopen.
