### ISSUE TITLE
Expand the functionality of configuration profiles

### ISSUE THREAD

**Issue by slannon97** [nvaccess/nvda#11360]
### Is your feature request related to a problem? Please describe.
yes NVDA configuration profiles do not currently allow the customization of speech dictionaries, input gestures, or symbol pronunciations. All of these settings apply globally. It would also be nice if sleep mode could be automatically switched on when activating a profile.
### Describe the solution you'd like
I would like speech pronunciation dictionaries, symbol pronunciations, and input gestures to be customizable for each configuration profile. This would allow for an extremely large amount of customization on a per application basis.
### Describe alternatives you've considered
The only alternative that is currently somewhat feasible is using voice specific pronunciation dictionaries. However, this is not at all ideal and does not solve the main issue.

**Comment by Adriani90** [comment]
These issues are already covered in #3656 (speech dictionaries), #8123 (input gestures), #3721 (sleep mode) and discussions for symbol pronounciation in #10972.
This being said, I am closing this issue as duplicate.
