### ISSUE TITLE
Office UI Fabric - Callout - FocusTrapZone - NVDA - Read content only 1 st time of focus

### ISSUE THREAD

**Issue by MdAmeerMind** [nvaccess/nvda#11378]
### Environment Information

- **Browser and OS versions**: Chrome + NVDA

### Describe the issue:
In callout we have use FocusTrapZone to trap focus, So content inside call out are read out by NVDA only when focus inner part first time. If we focus on link using tab it read aria label provided to link first time, again press tab focus goes to outer part again but narrator not read anything.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/mdameer/pen/NWxLWrL?editors=0010

#### Actual behavior:

Narrator not reading content when focus is moving inside again and again

#### Expected behavior:

Content inside the callout should read all team if focus in moving inside again, not only first time

same issue already raise on Office UI fabric and team mark as external
https://github.com/microsoft/fluentui/issues/14021

**Comment by Adriani90** [comment]
I think this is a duplicate of #6627. @JulienCochuyt what do you think?

**Comment by JulienCochuyt** [comment]
@Adriani90: Unlike #6627, adding content to change offsets does not solve the issue.

By the way @MdAmeerMind, what is the intent in assigning the presentation role to a focusable div? AT should ignore presentation but report controls... hence this looks conflicting IMHO. It does not affect the issue you are reporting here, though.

**Comment by MdAmeerMind** [comment]
Hi @JulienCochuyt , Thank you for your response. I have removed role as presentation from focusable div and tried, still the same issue. Yes it does not affect issue I am reporting

**Comment by Adriani90** [comment]
@MdAmeerMind could you please test with NVDA last alpha if this issue is still occuring in Chrome or Edge 112?

The last NVDA alpha version can be downloaded here:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Adriani90** [comment]
We didn't get an update from the initial author since more than 3 years, I am closing as abandoned. If you are still having this issue, please comment and we can reopen.
