### ISSUE TITLE
Context menu items are not marked as selected by keys

### ISSUE THREAD

**Issue by PavelKushnirchuk** [nvaccess/nvda#11387]
### Steps to reproduce:
1. Open Google Chrome
2. Go to https://stackblitz.com/edit/angular-ivy-brnrvq
3. Click right mouse button on any cell of the grid to show context menu 
4. Press "Down" key to navigate to context menu item.
### Actual behavior:
Menu item is not marked as selected with blue background
### Expected behavior:
Menu item is marked as selected  with blue background
#### NVDA installed/portable/running from source:
NVDA was installed

#### NVDA version:
2020.1
#### Windows version:
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.18363 Build 18363
#### Name and version of other software in use when reproducing the issue:
Google Chrome Version 83.0.4103.116 
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. I've tried version 2019.3
#### If addons are disabled, is your problem still occuring?
There is no addon in the system
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes.

**Comment by Adriani90** [comment]
Is this in browse mode? Or focus mode?

**Comment by PavelKushnirchuk** [comment]
Sorry for late aswer. It seems to me it was focus mode. So the issue is not relevant anymore

**Comment by Adriani90** [comment]
Could you check in NVDA's browse mode settings if the setting "automatically set system focus to focusable elements" is enabled?

If you are in browse mode when pressing right mouse click, then press nvda key + spacebar and the up and down arrow key to navigate the menu item. I think then the selection is triggered. At lease for me I can activate the menu item with enter from both browse mode and focus mode.

@Qchristensen could you please test this from a sighted person perspective? For me it seems the menu items are selected properly and I don't see any issue here.

**Comment by Qchristensen** [comment]
Can you please clarify exactly where to right click?  As far as I can tell it seems to be working everywhere I could think to right click.

Also just to clarify Adriani's comment, "automatically set system focus to focusable elements" is in NVDA's "Advanced" settings, not the Browse mode settings page.

(It is under a heading called "Browse mode", but I don't want to add to the confusion!)

**Comment by Adriani90** [comment]
yeah this works as expected in focus mode, you can enable focus mode by pressing nvda+space bar. Closing as works for me. In browse mode, NVDA can navigate the menu without moving the system focus, so that'ts why they are not visually selected. As soon as you press enter on a menu item in browse mode, the system focus is moved to the object, the object is selected and the action is triggered.
