### ISSUE TITLE
problems with braille on NVDA 2020.2 rc 1 

### ISSUE THREAD

**Issue by Afik-souffir998** [nvaccess/nvda#11386]
### Steps to reproduce: upgrade to 2020.2 rc1 with braille display connected.
explore with the program for example in an email. you'll see at some points, thats the braille is gone, espcially with links. 

### Actual behavior: braille is gone in email messages, word documents  and more. 
i just see a cursor.

**Comment by zstanecic** [comment]
Shalom,

You haven’t answered to all questions in the template.

Can you provid logs and clarify more?

Are you using some addons?

**Comment by Afik-souffir998** [comment]
How do I provide logs?

And yes, I'm using braille extender.

Afik.




Cordialement,

Afik Souffir

Portable: 0505782208
Addresse email
Afik.souffir@outlook.com<mailto:Afik.souffir@outlook.com>

**Comment by Adriani90** [comment]
Can you reproduce with all addons disabled?
Please try to reproduce this issue in NVDA 2020.1. Is this still reproducible there?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since years, I am closing this issue as abandoned. Please comment on this issue in case you are still having it and we can reopen.
