### ISSUE TITLE
Cancelable speech: NVDA does not report tab titles when switching with ctrl+tab or ctrl+shift+tab

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#11397]
### Steps to reproduce:
1. Open Firefox
2. Open two tabs on amazon.com for example
3. Open NVDA, and make sure that you have enabled "attempt to cancel speech" in advanced settings
4. Switch between tabs with ctrl+tab and ctrl+shift+tab

### Actual behavior:
NVDA just reports the focused link, but does not report the tab title

### Expected behavior:
NVDA should report the tab title first.
Note: this issue might also occur when you switch between desktops in Windows 10.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Version: alpha-20548,e1f3ba99

#### Windows version:
Windows 10 2004

#### Name and version of other software in use when reproducing the issue:
Tested only in Firefox 78 so far, but it might occur on other browsers as well.

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no issue with "attempt to cancel speech" turned off.

#### If addons are disabled, is your problem still occuring?
yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
n/a

**Comment by amirsol81** [comment]
@feerrenrut #11492 is related to the issue -- not Chrome but the experimental Speech setting. Also with this setting turned on, NVDA doesn't report the title of its own dialogs when hot keys such as Control+NVDA+S and Control+NVDA+F are pressed.

**Comment by feerrenrut** [comment]
Hi @amirsol81 please see PR #11632 where a fix is being investigated. There will be updates on that PR in today or tomorrow.

**Comment by amirsol81** [comment]
Thanks.
