### ISSUE TITLE
NVDA read mutilple times when focus to marker Google Map

### ISSUE THREAD

**Issue by SonSiHo** [nvaccess/nvda#11394]
AR : When focus to marker in Google Map, sometimes NVDA read more time Title of marker.
ER : When focus to marker in Google Map, NVDA should read only one time Title of marker

**Comment by Adriani90** [comment]
Please open a new issue with exact steps to reproduce and fill in the requested details (i.e. NVDA version, windows version, browsers you tested in, or the app version which you tested with).
I am closing this issue for now due to missing details.
