### ISSUE TITLE
NVDA shouldn't warn about incompatible add-ons that were disabled by the user.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#11399]
### Steps to reproduce:
1. Using NVDA 2019.2.1 install an add-on which is incompatible with Python 3 versions.
2. Disable this add-on using add-ons manager.
3. Attempt an update to NVDA 2020.1 or whatever is the latest version at the time.

### Actual behavior:
The following warning is shown after update is downloaded:
> However, your NVDA configuration contains add-ons that are incompatible with this version
of NVDA. These add-ons will be disabled after installation. If you rely on these add-ons, please
review the list to decide whether to continue with the installation
I understand that these incompatible add-ons will be disabled

Assuming that the only incompatible add-on is the one disabled in step 2 of STR this message is not true in the following points:

> These add-ons will be disabled after installation.

It is already disabled so nothing  will change after update.

> If you rely on these add-ons, please
review the list to decide whether to continue with the installation

Given the fact that the add-on has been explicitly disabled I obviously don't rely on it.

### Expected behavior:
Only enabled add-ons should be taken into account when checking if the user configuration contains incompatible add-ons.
It can be argued that if the add-on is not needed user should simply uninstall it, but in my view there are some cases in which keeping an incompatible one installed but disabled just to stop annoying warnings during every update (often daily for Alpha users) may be beneficial i.e.:
- Uninstallation of add-onn may remove its configuration and while functionality that it offers is not critical enough to signify staying with Python 2 based version of NVDA it would be nice to use it again if it become compatible in the future.
- When using add-on updater it also monitors for updates to disabled add-ons so keeping it installed is a good way of being notified of new versions.

#### NVDA installed/portable/running from source:
Any
#### NVDA version:
2019.2 for initial steps - any Python 3 based for the actual upgrade.
#### Windows version:
N/A
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
None important
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not relevant
#### If addons are disabled, is your problem still occuring?
No - but the issue is about NVDA interaction with add-ons
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Not relevant

**Comment by feerrenrut** [comment]
> It is already disabled so nothing will change after update.

This warning is still valid for disabled add-ons, if they are incompatible, they can not be re-enabled. We don't uninstall them because of the potential to lose config.

>Given the fact that the add-on has been explicitly disabled I obviously don't rely on it.

We can't assume that users do not depend on currently disabled add-ons, they may only enable the add-on for certain use-cases. The intention of this dialog is to give users a chance to reconsider whether they would like to proceed with an update given this information about their installed add-ons. 

Perhaps the following line could be updated:
> I understand that these incompatible add-ons will be disabled
to something like:
> I understand that these incompatible add-ons will be disabled until they are updated to a version compatible with this version of NVDA.

I'm going to close this as won't fix for now.

I have a feeling the real core of this issue is.
> keeping an incompatible one installed but disabled just to stop annoying warnings during every update (often daily for Alpha users)

We do wish to minimize friction for those testing alpha, though if this is the case, please create a new issue.

**Comment by lukaszgo1** [comment]
@feerrenrut wrote:
> I have a feeling the real core of this issue is.
> 
> > keeping an incompatible one installed but disabled just to stop annoying warnings during every update (often daily for Alpha users)
> 
> We do wish to minimize friction for those testing alpha, though if this is the case, please create a new issue.



You're right, I believe that if not for the fact that I'm on Alpha and therefore have to acknowledge this message with every update I wouldn't find this so problematic. I can create a new issue of course but frankly have no idea what more can I say there which has not been said in this ticket. In other words I can't see a better solution for the problem and the solution which I've proposed is not going to be implemented. If you have a better idea of solving this for Alpha users I'd love to hear about it!

**Comment by feerrenrut** [comment]
Creating a new issue to discuss this problem leaving the solution open will allow us to focus on the core of the problem without distraction of unrelated aspects. If you focus on explaining your use case, there are likely further questions we can ask that may lead to a satisfactory solution.

For instance, I want to understand, given the last add-on API version update was for 2019.3, why do you still get incompatible add-on warnings? Why keep these add-ons installed? 

We could potentially "remember" which add-on's you have already been warned about and not warn you during pre-release updates. I think it is important to remind people at least for releases that they have add-ons that are incompatible.
