### ISSUE TITLE
EnhancedTermTypedCharSupport: store queued chars in a deque

### ISSUE THREAD

**Issue by codeofdusk** [nvaccess/nvda#11418]
### Is your feature request related to a problem? Please describe.
Currently, the `EnhancedTermTypedCharSupport` class stores its queue of typed characters in a list. Per [the Python docs](https://docs.python.org/3/library/collections.html#collections.deque):

> Though list objects support similar operations, they are optimized for fast fixed-length operations and incur $\mathcal{O}(n)$ memory movement costs for `pop(0)` and `insert(0, v)` operations which change both the size and position of the underlying data representation.

### Describe the solution you'd like
Use a `deque` instead. `pop` characters to be dispatched instead of iterating over the entire list and rebuilding it.

### Describe alternatives you've considered
Keep the current implementation: the number of queued characters is small and time/space savings are theoretical.

**Comment by feerrenrut** [comment]
Before accepting a change like this I'd like to see it actually measured under standard and extreme conditions. IE prove that it doesn't make things worse. I agree, this should perform better, but good to know for sure it does in the cases that this code encounters.

**Comment by Adriani90** [comment]
@codeofdusk are you still thinking implementing this makes sense? Or is the poerformance much better now?
If you think it makes sense, could you provide test results in extreme situations?

**Comment by codeofdusk** [comment]
I have little confidence that a PR like this without obvious user benefit will be accepted, see #11484. It just doesn't meet the #11006 bar (which I now understand to mean "accepting PRs with only obvious user impact"). If you'd like to provide benchmarks I'm happy to take this on.

**Comment by seanbudd** [comment]
@codeofdusk that issue is closed, we welcome positive code refactors that increase maintainability
