### ISSUE TITLE
bug: Copying object name can add a space

### ISSUE THREAD

**Issue by TechHorseG** [nvaccess/nvda#11438]
Hello. I recently updated my portable copy of NVDA from 2019.2.1 to 2020.2 on my Windows10 1909 PC. I have noticed improvements and thanks for those, but also a small few bugs / niggles that I would like to ask about. This is one.

With my key binds I can press NVDA+O three times to copy an object's name and value to the clipboard, and with the older version this worked flawlessly.

However now there is at least one place where it doesn't anymore. In FileExplorer if I select a file or folder then invoke this function, it adds an erroneous trailing space to the name. Although values from the other columns such as date and size copy fine.

I use this feature extensively and so obviously would prefer to not worry about erroneous characters being added to the copied text. Hope this is a simple one to fix! Thanks.

**Comment by Adriani90** [comment]
cc: @JulienCochuyt
