### ISSUE TITLE
Errors from time to time when navigating tables in MS word

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#11446]
### Steps to reproduce:
1. Open MS Word 365 and NVDA
2. In a table, navigate with ctrl+alt+arrow keys

### Actual behavior:
Sometimes this error is occuring:
```
IO - inputCore.InputManager.executeGesture (16:07:50.253) - winInputHook (6772):
Input: kb(laptop):alt+control+downArrow
ERROR - unhandled exception (16:07:50.277) - winInputHook (6772):
Traceback (most recent call last):
  File "wx\core.pyc", line 3240, in <lambda>
wx._core.wxAssertionError: C++ assertion "wxThread::IsMain()" failed at ..\..\src\common\timerimpl.cpp(60) in wxTimerImpl::Start(): timer can only be started from the main thread
```

### Expected behavior:
No error

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Version: alpha-20656,87eee7f4

#### Windows version:
Windows 10 2004

#### Name and version of other software in use when reproducing the issue:
MS Office 365

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, in previous Alpha I could not reproduce this error.

#### If addons are disabled, is your problem still occuring?
not sure, this occurs from time to time

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes, no effect

**Comment by CyrilleB79** [comment]
Do you use Windows Magnifier addon?
* If yes, try to disable it to see if the error disappears. I have had quite similar errors with this add-on, even if the stack trace is not exactly the same. And that is the reason why I did not asked to pass this add-on in stable version. I have not yet found the cause of this bug.
* If no, I hope solving this issue may also solve mine with Windows Magnifier add-on.

**Comment by MarcoZehe** [comment]
Also, do you have the option to use UIA for Word controls checked in Advanced Settings, or not?

**Comment by Adriani90** [comment]
@CyrilleB79 and @MarcoZehe, I am not using the magnifier addon. UIA support for Microsoft word is disabled in the advanced settings.

**Comment by Adriani90** [comment]
However, this seems very unreliable to reproduce. I will reopen the issue as soon as I found a reliable way to reproduce it.
