### ISSUE TITLE
Deprecation and removal (2021.1 milestone): remove app modules for old (universal) apps no longer in circulation due to renamed executables

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#11440]
Hi,

For one such justification behind this issue, see #11439.

### Is your feature request related to a problem? Please describe.
As apps from Microsoft and third parties are updated, it becomes important for screen reader vendors and users to keep track of changes so the screen reader can continue to support users. one of these changes is renamed executable where an app update changes the executable image name for the app in question. This happens either because apps are split, combined, or succeeded by another app.

NVDA comes with several apps that were recently renamed. One outstanding example is Windows 10's Mail and Calendar, specifically the Mail portion. Originally, this app was named hxmail.exe. In 2017, it was renamed to hxoutlook.exe, then renamed again to commsapes.exe in 2020 when it was combined with Calendar. I'm sure there are other apps that come with NVDA that are no longer in circulation due to the executable being renamed.

### Describe the solution you'd like
As part of 2021.1 milestone, consider deprecating or removing app modules for apps with old executable names provided that old executables are no longer in circulation.

### Describe alternatives you've considered
Leave app modules as is.

### Additional context
The above issue is pronounced in Windows 10 - as feature updates progress through development-testing-release-support-retirement cycle, apps will also check if users are running supported Windows 10 releases. As of time of this writing, Windows 10 versions older than 1709 are no longer supported (exceptions are 1507 and 1607 which are long-term support releases; even then, apps such as Mail and Calendar are not bundled with LTSC (long-term servicing channel) releases).

Thanks.

**Comment by feerrenrut** [comment]
I think this needs further discussion. Can the old applications still be in use by people with older versions of Windows?

**Comment by josephsl** [comment]
Hi, that’s precisely the reason why I’m a bit hesitant to proceed with it. To help us with answering this, can we get stats on how many folks are using unsupported Windows 10 feature updates (semi-annual channel or ones no longer supported for consumers), namely 10.0.10240, 10.0.10586, 10.0.14393, 10.0.15063, 10.0.16299, 10.0.17134, 10.0.17763, and 10.0.18362? Ideally folks should be using supported releases, but reality says otherwise. Thanks.

**Comment by CyrilleB79** [comment]
Hi
In my company, we are using: Windows 10 1809 (64-bit) build 17763.1757.
I do not know if an update is planned soon. Anyway they usually use supported version and migrate when they reach end-of-support date.
Are you sure all these versions are not supported anymore, even with LT?
Thanks.

**Comment by josephsl** [comment]
HI, the versions I wrote are no longer supported for consumers. LTSC versions are not affected as they do not come with universal apps such as modern Calculator and Mail and Calendar. Thanks.

**Comment by lukaszgo1** [comment]
Unless we can demonstrate that removing these appModules brings any real advantage I vote to close this. It is really hard to predict what our users may rely on.

**Comment by josephsl** [comment]
Hi,

The biggest advantage is maintenance burden - we can move contents of "old" app modules to the aliased modules. Besides, Microsoft encourages everyone to use supported feature updates.

Thanks.

**Comment by XLTechie** [comment]
As you certainly know, there are all kinds of reasons why people might not 
update, or not be able to, or not be allowed to.
If these modules aren't hurting anything to remain in their current state, I at 
least would request they stay.

If the maintenance burden becomes extended, that would be a good reason to axe 
them, I agree, but has that actually happened?

If not, I would suggest inserting a comment for each that it is for an app that 
stopped being distributed as of Windows version X, and that the modules may be 
removed without warning in a future version of NVDA.

**Comment by josephsl** [comment]
Hi, I see. I think we might as well revisit this in December when folks start talking about Python 3.10 and Windows 8 support. Thanks.
