### ISSUE TITLE
Many problems when creating tables in word with uia enabled

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#11457]
### Steps to reproduce:
Enable in the advanced word settings the option to use uia automation word controls when available.
Open a document in word, and create a table with for example 2 columns and 3 rows
Place the cells on row 1 column 1
Type test1
Press ctrl + alt + right arrow
Expected
Listen to column 2
What happens
The speech nvda is not in a table
Press tab
Expected to hear
Column 2
Nvda speaks
In blank
Type ctrl + alt + down arrow
Expected to hear
Line 2
Nvda speaks outside the table
As with several other problems, it became almost impossible to use nvda to read tables in word with uia on.
All of these commands work if the option to use uia automation in word controls when available is cleared.
Read information for column and cell headings as well as read cells is enabled in the nvda formatting guide.
I know of the possibility of using tabe and shift + tabe but I find the use of nvda commands more intuitive, and they work by disabling uia.
Besides that with the use of tabe and shift + tabe the numbers of rows and columns were not informed, which is informed when uia is deactivated.
### Actual behavior:
Does not work using uia in word
### Expected behavior:
Works correctly using uia
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-20643,f308a0d6

#### Windows version:
10 19041.388
#### Name and version of other software in use when reproducing the issue:
WINWORD.EXE, Microsoft Office 16.0.13001.20384

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by brunoprietog** [comment]
This is related to #11043
