### ISSUE TITLE
HTML listbox in browse mode always selects first option on <enter>

### ISSUE THREAD

**Issue by progman32** [nvaccess/nvda#11464]
I'm a newb to screenreaders; just a dev trying to improve accessibility on our site. Ran into some surprising behavior.

### Steps to reproduce:
Load the following HTML into Firefox or Chrome:
```html
<!doctype html>
<html>
<body>
        <ul role="listbox">
                <li role="option"><a href="https://google.com">Google</a></li>
                <li role="option"><a href="https://microsoft.com">Microsoft</a></li>
        </ul>
</body>
</html>
```
In Browse mode, tab to Microsoft. Hit Enter.
### Actual behavior:
Navigates to Google.
### Expected behavior:
Navigates to focused item (Microsoft).
If I remove `role="listbox"` from the `<ul>`, it works.
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
2020.2
#### Windows version:
10 version 1903
#### Name and version of other software in use when reproducing the issue:
Firefox 79.0 or Chrome 84.0.4147.105. IE and Edge do not repro the issue.
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If addons are disabled, is your problem still occuring?
clean install
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by Brian1Gaff** [comment]
I guess you might want to try other browsers as well, to narrow it down a 
bit.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by progman32** [comment]
Sure. Chrome 84 has the same behavior. Both Edge and Internet Explorer work correctly.

All 4 browsers work fine in Narrator.

**Comment by Adriani90** [comment]
cc: @jcsteh for Firefox.

**Comment by jcsteh** [comment]
Thanks for reporting.

This is due to an authoring error. A listbox should only occupy a single tab stop, so NVDA expects it to behave as such. It gets rendered as a single point in NVDA browse mode. In contrast, this listbox's items are all separately tabbable. Instead, the items should be reachable with the up and down arrow keys.

If you want the links to be tabbable, the listbox role is not appropriate.
