### ISSUE TITLE
Problems working with images in word using ui automation

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#11466]
### Steps to reproduce:
Open a new document in word and insert an image.
Place an alt text description for the image.
In the advanced settings of nvda make sure that using automation for controls in word is enabled.
Read the document with the arrows above and below and see that the alt text description will not be read.
switch to the navigation mode and read the document with the arrows and see that the alt text description is not read again.
To read the description you have to select the image and nvda will read the description.
In the advanced settings of nvda disable the setting to use uia automation for controls in word.
And see that it has now gotten worse, the image description is not read while reading with the arrows, it is not read when selecting the images and it is also not read in the navigation mode.
This is a regret, but I do not know when, I used this feature if I remember correctly in nvda 2019.1 and it worked
### Actual behavior:
the alt text description is not read while reading with the arrows
### Expected behavior:
the alt text description is read while reading with the arrows
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-20643,f308a0d6

#### Windows version:
10 19041.388
#### Name and version of other software in use when reproducing the issue:
WINWORD.EXE, Microsoft Office 16.0.13001.20384

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by michaelDCurran** [comment]
This was a bug in MS Word, fixed sometime before MS Word version 16.0.14405.20002.
With this version, alt text reads for images when navigating a document with the arrow keys.
