### ISSUE TITLE
Traceback occurs when switching synths in latest alpha

### ISSUE THREAD

**Issue by Mohamed00** [nvaccess/nvda#11482]
### Steps to reproduce:
1. Switch between two synthesizers several times and wait a bit. I was able to reproduce this reliably using ESpeak and Vocalizer, but it may happen for other synths as well.
### Actual behavior:
A traceback is displayed. The following log fragment demonstrates me switching from ESpeak to Vocalizer and then getting the traceback.
INFO - synthDriverHandler.setSynth (09:26:49.664) - MainThread (2068):
Loaded synthDriver espeak
DEBUGWARNING - synthDriverHandler.getSynthList (09:26:52.441) - MainThread (2068):
Synthesizer 'mssp' doesn't pass the check, excluding from list
DEBUGWARNING - external:synthDrivers.vocalizer_expressive._voiceManager.VoiceManager.setDefaultVoice (09:26:54.850) - MainThread (2068):
Voice not available, using default voice.
DEBUGWARNING - external:synthDrivers.vocalizer_expressive.SynthDriver._set_variant (09:26:54.855) - MainThread (2068):
Model not available: full_155mrf22
INFO - synthDriverHandler.setSynth (09:26:54.856) - MainThread (2068):
Loaded synthDriver vocalizer_expressive
ERROR - unhandled exception (09:26:59.835) - MainThread (2068):
Traceback (most recent call last):
  File "wx\core.pyc", line 2196, in Notify
  File "nvwave.pyc", line 349, in _close
  File "nvwave.pyc", line 90, in _winmm_errcheck
OSError: [Errno 5] The specified device handle is invalid.
### Expected behavior:
No error.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
alpha-20718,633435db.
#### Windows version:
Windows 10, version	10.0.20185 Build 20185.

#### Name and version of other software in use when reproducing the issue:
N/a
#### Other information about your system:
N/a
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, this seems to have started when #11024 was merged.
#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
N/a.

**Comment by Mohamed00** [comment]
CC @jcsteh

**Comment by jcsteh** [comment]
Curious. I [included explicit code which should deal with this case](https://github.com/nvaccess/nvda/blob/633435d/source/nvwave.py#L342), so I'm not sure why that isn't working here. I can't reproduce it with eSpeak and OneCore and I don't have Vocalizer.

**Comment by Mohamed00** [comment]
You may be able to reproduce it by switching between ESpeak and RHVoice. The common thread here seems to be pressing control quickly after the synth first loads, example, switch to ESpeak, press control quickly after it first starts speaking, then switch to RHVoice and press control quickly again.

**Comment by tspivey** [comment]
If I'm understanding the nvwave code right, there's at least one way it can fail.

1. If a player method is called in a thread, e.g. player.stop or player.idle, the timer will be started on the main thread with wx.CallAfter.
2. If you then call player.close from the main thread, then the timer will be stopped from the main thread (without CallAfter). However, the CallAfter to start the timer might not have ran yet.
3. The CallAfter runs to start the timer, the timer eventually fires and calls self._close, but the handle is invalid by then.

**Comment by amirsol81** [comment]
I can also duplicate this by, say, switching from eSpeak to MS Sapi 5 (Eva), or vice versa.
My log shows the following:
INFO - synthDriverHandler.setSynth (18:02:29.581) - MainThread (7288):
Loaded synthDriver sapi5
ERROR - unhandled exception (18:02:34.389) - MainThread (7288):
Traceback (most recent call last):
  File "wx\core.pyc", line 2196, in Notify
  File "nvwave.pyc", line 349, in _close
  File "nvwave.pyc", line 90, in _winmm_errcheck
OSError: [Errno 5] The specified device handle is invalid.
ERROR - unhandled exception (18:02:39.627) - MainThread (7288):
Traceback (most recent call last):
  File "wx\core.pyc", line 2196, in Notify
  File "nvwave.pyc", line 349, in _close
  File "nvwave.pyc", line 90, in _winmm_errcheck
OSError: [Errno 5] The specified device handle is invalid.

**Comment by jcsteh** [comment]
Thanks @tspivey; I somehow missed that. I'll look into a fix.
