### ISSUE TITLE
Edit signature field does not read in Windows 10 Mail

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11506]
### Steps to reproduce:

1. Open Windows Mail.
2. Press TAB to move to the "Settings" button and press ENTER.
3. Press TAB to move to "Signatures" and press ENTER.
4. TAB through the text formatting options, past the "Formatting button" to the next option, the signature edit.
5. Use the arrow keys to move through the signature (the field has "Sent from Mail for Windows 10" by default, but type something first if needed if this has previously been deleted).
6. Press ESCAPE to close.

### Actual behavior:

When the focus gets to the edit field, nothing is reported.  When moving through existing text in the signature field, again, nothing is reported.  No errors are recorded in the log:

```
IO - inputCore.InputManager.executeGesture (08:22:25.305) - winInputHook (16248):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (08:22:26.258) - winInputHook (16248):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (08:22:26.858) - winInputHook (16248):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (08:23:15.966) - winInputHook (16248):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (08:23:16.087) - MainThread (17528):
Developer info for navigator object:
name: 'Mail'
role: ROLE_WINDOW
roleText: None
states: STATE_FOCUSED
isFocusable: False
hasFocus: True
Python object: <NVDAObjects.UIA.UIA object at 0x0342AD90>
Python class mro: (<class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'object'>)
description: ''
location: RectLTWH(left=0, top=-1, width=2560, height=1259)
value: None
appModule: <'appModuleHandler' (appName 'commsapps', process ID 13836) at address 396cb10>
appModule.productName: 'microsoft.windowscommunicationsapps'
appModule.productVersion: '16005.13110.41006.0'
TextInfo: <class 'displayModel.DisplayModelTextInfo'>
windowHandle: 133424
windowClassName: 'Windows.UI.Core.CoreWindow'
windowControlID: 0
windowStyle: 1409286144
extendedWindowStyle: 2621440
windowThreadID: 15768
windowText: 'Mail'
displayText: ''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x61ad220 at 4641cb0>
UIA automationID: 
UIA frameworkID: XAML
UIA runtimeID: (42, 133424)
UIA providerDescription: [pid:20404,providerId:0x20930 Main:Nested [pid:13836,providerId:0x20930 Main(parent link):Unidentified Provider (unmanaged:Windows.UI.Xaml.dll)]; Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:UIAutomationCore.dll); View:Microsoft: ViewID Proxy (unmanaged:UIAutomationCore.dll)]
UIA className: Windows.UI.Core.CoreWindow
UIA patterns available: LegacyIAccessiblePattern

```

### Expected behavior:

NVDA should report the field when the focus moves to it and the contents when navigating.
#### NVDA version:
NVDA alpha-20739,89c84b84 (Installed) and 2019.2.1 and 2020.2 portable.

#### Windows version:
Windows 10 (64-bit) Version: 1903 Build 18362 

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
As above
#### If addons are disabled, is your problem still occuring?
No add-ons

**Comment by Carlos-EstebanM** [comment]
Hi all.
I have this problem in Windows 10 Version 2004 (build SO 19041.450), NVDA 2020.2 installed, the last version of the application Mail updated by Microsoft Store.

**Comment by josephsl** [comment]
Hi, did this work before? If yes, this will boost priority of #11439 if it turns out this is indeed due to the executable being renamed for the second time (to verify, try reproducing it after installing Windows 10 App Essentials add-on). Thanks.

**Comment by josephsl** [comment]
Hi, forget about what I wrote earlier – it can also be reproduced via Narrator, so looks like a call to Microsoft is in order. Thanks.

**Comment by Qchristensen** [comment]
Good point Joseph, I have passed this on to Microsoft.  So it might well be a NeedsExternalFix one, but I'll leave it open until I hear back from them (likely tomorrow), just in case.

**Comment by Adriani90** [comment]
@Carlos-EstebanM, @Qchristensen, @Aleskis, @gauravahir28, @alexandretoco Windows mail should work again in NVDA last alpha. Can you also test if this issue is still occuring with NVDA last alpha version? The alpha versions can be downloaded from following link, for those who did not test with them yet:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Qchristensen** [comment]
With the demise of Windows mail in favour of Outlook, is this issue still relevant?

**Comment by Adriani90** [comment]
Windows native mail app is discontinued and people will not be able to send or receive messages in it from 2025 onwards. I am closing as abandoned.
