### ISSUE TITLE
hclick bar cann't be triggered

### ISSUE THREAD

**Issue by DavidBitSource** [nvaccess/nvda#11516]
### Steps to reproduce:
* Open https://www.truenas.com/truenas-mini/ with Firefox
* go to configure
* try to select a platform: you'll only see +$799.00  +$1069.00  +$1299.00. Neither hitting enter nor the NVDA click work.

### Actual behavior:
Nothing happens, it is possible to trigger the site's functionality with a mouse.
### Expected behavior:
Select another option.
#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.2
#### Windows version:
Windows 7 64 bit
#### Name and version of other software in use when reproducing the issue:
Firefox 79.0 (64-Bit)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by Adriani90** [comment]
I can reproduce this, however I think here is an web authoring issue. The click bar does not have any role other than text, many buttons are not labelled, in short, this website is not really accessible.
I can reproduce this also in Chrome 84.

cc: @JulienCochuyt maybe you have other thoughts on this?

**Comment by leonardder** [comment]
Closing as per @Adriani90's comment, as this doesn't look like an NVDA issue. I know Acronis from creating great software, but not very accessible unfortunately.
