### ISSUE TITLE
Tether Braille: "Automatically" does not follow mouse when (Review cursor) "Follow mouse cursor is checked.

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11519]
### Steps to reproduce:
1) In NVDA's Braille settings, set "Tether Braille" to "Automatically" (this is set by default).
2) In NVDA's Mouse settings, check "Enable mouse tracking" (This is set by default).
3) In NVDA's Review cursor settings, check "Follow mouse cursor".
3) Apply the changes
4) Move the mouse over something (say the heading of this issue).  NVDA reads the line under the mouse.
5) Press numpad8 / NVDA+shift+. to read the current line in review.  NVDA reads the line under the mouse.
6) Read the line on the Braille display.

### Actual behavior:

At step 6, as reported by a Spanish speaking user, Sergio via email, the text is not updated on the Braille display as it should be.  I don't currently have a Braille display to test with but the Braille viewer does not update with that text.

### Expected behavior:

The Braille display should update with the text under the mouse as it is now the location of the review cursor.

#### NVDA version:

NVDA 2020.2 (Sergio) and NVDA alpha-20763,1ef4dfb0 (me), both installed.

#### Windows version:

Windows 10.  I have Windows 10 (64-bit) Version: 1903 Build 18362 - I don't have Sergio's exact build.

#### Does the issue still occur after restarting your computer?

Yes

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by leonardder** [comment]
I think that the read current line under review cursor command doesn't toggle tethering. There is also much to say that when review cursor follows mouse is on, everything that's reported by moving the mouse trigger auto tethering.
