### ISSUE TITLE
Outlook password entry field error sounds and unexpected speech silence

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#11512]
This is a small UX issue. Worth fixing I imagine, but at a rather low priority.

### Steps to reproduce:

In Outlook (I used 2019):

1.  Press alt+f, i, d, to add a new account.
2.  Enter an email address. I used `fake@fake.com`.
3.  Tab to then select each of the following chain of options:
    * `advanced options`.
    * `Let me setup my account manually`.
    * `Connect`.
    * `IMAP`
4.  Enter "`localhost`" for both servers, and leave everything else at default.
5.  Select `next`.
6.  Enter "`abc`" in the password field. Stars are spoken as might be expected.
7.  Press tab, going to but not pressing the `show or hide password` option.
8.  Press shift+tab to return to the password field.

### Actual behavior:

At step 8, there is an error sound, and nothing is spoken.
Pressing home or left arrow, results in error sounds and no speech.
Pressing end or right arrow, results in the word "blank" being spoken.
Using object nav will get "Password edit access denied protected".

### Expected behavior:

I'm not absolutely sure, but not this.
It may be that the error sound only happens because I'm running an alpha.
Still, the result in the case of a stable version of NVDA, would be that the password field would be totally silent unless a right arrow or end is pressed, and that doesn't seem right.

### System configuration

NVDA installed, alpha-20758,0098a31a
Windows 10 Version 2004 (OS Build 19041.450)
Microsoft Office Outlook 2019.

#### Does the issue still occur after restarting your computer?

yes

#### If addons are disabled, is your problem still occuring?

yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

yes

### Log

Can search for "start here" for the good stuff.
[nvda outlook 2019 password field.txt](https://github.com/nvaccess/nvda/files/5101470/nvda.outlook.2019.password.field.txt)

**Comment by leonardder** [comment]
This also looks like an issue in Outlook itself indeed, given the COM errors raised there's something broken in the UIA implementation.

**Comment by Adriani90** [comment]
cc: @Qchristensen
