### ISSUE TITLE
cancel  shortcut keyboard from NVDA

### ISSUE THREAD

**Issue by salmabadawy74** [nvaccess/nvda#11523]
### Is your feature request related to a problem? Please describe.
Hello Everyone 
why NVDA doesn't recognize keycode for the letter 
example when i press H i want to open popup but it say no text heading 
i want to cancel shortcut keyboard for nvda and allow only my shortcut

**Comment by lukaszgo1** [comment]
This is expected behaviour - in browse mode 'h' key moves to the next heading. To pass it to your website you need to either press NVDA+space to switch to focus mode, or, alternatively, press NVDA+Shift+Space to turn off quick letter navigation.

**Comment by leonardder** [comment]
Closing as invalid.

@salmabadawy74 If you have any remaining questions about this behavior, please consult the browse mode section in the user guide, found under NVDAs help menu. You can also direct your questions to the [users mailing list](nvda.groups.io/g/nvda)
