### ISSUE TITLE
Canot access some lists in android studio

### ISSUE THREAD

**Issue by PeterLecky** [nvaccess/nvda#11528]
The problem appeared in version 2020.2, it works properly in 2020.1

### Steps to reproduce:
1. Run android studio with some project
2. press e.g. ctrl+n to open find class dialog. Focus is now in edit where you can type part of class name
3. type some letters.

### Actual behavior:
The focus is in edit where you can modify typed text but list of recommended classes is not accessible. It is possible to access list of propositions by object navigation, and emulate left click on particular item to activate it.

### Expected behavior:
The focus is in list of recommended classes and you can choose one.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.2.0
#### Windows version:
7 pro
#### Name and version of other software in use when reproducing the issue:
Android studio 4.0.1
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, see expected behavior, which still works in 2020.1.0
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

I believe that the problem is caused by this change from changelog:
• Focus is not moved in Java application when the selection is changed in an unfocused tree, table or list. (#5989)

**Comment by feerrenrut** [comment]
@kaleev Would you be able to take a look at this issue? It seems possible this issue was introduced with PR #11048 "JAB: do not treat ActiveDescendentChange event from not focused component as focus gained event"

**Comment by Adriani90** [comment]
cc: @jcsteh

**Comment by PeterLecky** [comment]
Seems to be fixed in latest version of Android studio. It works now and this can be closed.
Thank You.
