### ISSUE TITLE
UI Automation: Implement a proxy DLL to use 64-bit UIA

### ISSUE THREAD

**Issue by OzancanKaratas** [nvaccess/nvda#11522]
### Is your feature request related to a problem? Please describe.
See #7041.
### Describe the solution you'd like
We can provide a 64-bit DLL proxy for UIA, NVDA should use it to reach original 64-bit UIA DLL.
### Describe alternatives you've considered
Compile NVDA for 64-bit, but it is too costly.
### Additional context
None

**Comment by OzancanKaratas** [comment]
CC @feerrenrut
CC @michaelDCurran

**Comment by OzancanKaratas** [comment]
@Oreonan, may you help us?

**Comment by leonardder** [comment]
I don't see how this could improve #7041, as that deals with MSAA and not with UIA. I'm pretty sure that using the X64 UIA dll for whatever reason won't improve anything. Note that we're using the COM interface for most UIA related tasks, and the COM system deals with X86/X64 interop itself.

**Comment by josephsl** [comment]
Hi, someone would argue that there should be a proxy DLL for ARM64, but as Leonard pointed out, COM is supposed to be language and machine architecture agnostic. Thanks.

**Comment by Oreonan** [comment]
@OzancanKaratas I'm not really sure to can help unfortunately, but your idea is the good.
Another example found to describe #7041 is the tree view of TeamTalk software, with 32bits dll NVDA announces correct informations, but not with 64 bits dll...

**Comment by OzancanKaratas** [comment]
So how can we fix the treeview?

**Comment by leonardder** [comment]
The treeview issue is unrelated to a 64-bit DLL of UIA. I'd suggest continuing the discussion in the already existing issue.
