### ISSUE TITLE
When using NVDA to browse the forms section of the pve - Proxmox Virtual Environment page, NVDA will keep playing an error tone!

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#11530]
Proxmox Virtual Environment
is an open source server virtualization management solution based on QEMU/KVM and LXC. You can manage virtual machines, containers, highly available clusters, storage and networks with an integrated, easy-to-use web interface or via CLI. 
NVDA keeps playing an error sound when browsing the forms section of the pve - Proxmox Virtual Environment page when currently using NVDA!

### Steps to reproduce:
First open the Proxmox VE administration page https://192.168.2.233:8006
and then log in with the account you set up.
Finally focus on the node cell and the Datacenter cell to reproduce the error.

### Actual behavior:
NVDA keeps playing error tones during use of pve - Proxmox Virtual Environment
### Expected behavior:
Browsing the pve - Proxmox Virtual Environment table with NVDA does not play an error tone.
#### NVDA installed/portable/running from source:
install version
#### NVDA version:
alpha-20763
#### Windows version:
Microsoft Windows [version 10.0.19041.450]
#### Name and version of other software in use when reproducing the issue:
none
#### Other information about your system:
none
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The same error occurs in NVDA 2020.2 Stable Edition.
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Not covered.
log:
```
ERROR - eventHandler.executeEvent (17:51:25.999) - MainThread (18612):
error executing event: gainFocus on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x032943B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 217, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1105, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 991, in reportFocus
  File "speech\__init__.pyc", line 478, in speakObject
  File "speech\__init__.pyc", line 517, in getObjectSpeech
  File "speech\__init__.pyc", line 381, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1103, in _get_rowNumber
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147467259, '未指定的错误', (None, None, None, 0, None))
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (17:51:26.241) - MainThread (18612):
Unsupported speech command: LangChangeCommand ('zh_CN')
ERROR - eventHandler.executeEvent (17:51:29.313) - MainThread (18612):
error executing event: gainFocus on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x06F19BD0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 217, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1105, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 991, in reportFocus
  File "speech\__init__.pyc", line 478, in speakObject
  File "speech\__init__.pyc", line 517, in getObjectSpeech
  File "speech\__init__.pyc", line 381, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1103, in _get_rowNumber
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147467259, '未指定的错误', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (17:51:32.546) - MainThread (18612):
error executing event: gainFocus on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x037B01D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 217, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1105, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 991, in reportFocus
  File "speech\__init__.pyc", line 478, in speakObject
  File "speech\__init__.pyc", line 517, in getObjectSpeech
  File "speech\__init__.pyc", line 381, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1103, in _get_rowNumber
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147467259, '未指定的错误', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (17:51:35.620) - MainThread (18612):
error executing event: gainFocus on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x037B09F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 217, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1105, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 991, in reportFocus
  File "speech\__init__.pyc", line 478, in speakObject
  File "speech\__init__.pyc", line 517, in getObjectSpeech
  File "speech\__init__.pyc", line 381, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1103, in _get_rowNumber
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147467259, '未指定的错误', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (17:51:38.711) - MainThread (18612):
error executing event: gainFocus on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x037B01D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 217, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1105, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 991, in reportFocus
  File "speech\__init__.pyc", line 478, in speakObject
  File "speech\__init__.pyc", line 517, in getObjectSpeech
  File "speech\__init__.pyc", line 381, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1103, in _get_rowNumber
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147467259, '未指定的错误', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (17:51:39.757) - winInputHook (13592):
```

**Comment by feerrenrut** [comment]
In case the error sound it self is making it hard for you to do your work, note that in release builds the error tone is not played.

It's unlikely that NVDA developers to setup a system to test this. Could you provide more information about the problematic page.

Would it be possible for you to do the following:
- Tell us what web browser you are using.
- Copy the HTML of the element that causes this problem
- Copy the devInfo for the element (NVDA+F1)

**Comment by dingpengyu** [comment]
hi @feerrenrut 
The following browsers were currently used for testing pve Proxmox Virtual Environment:
Google Chrome 
Version 86.0.4240.9 (official version) dev (64-bit)
test result
an error has occurred
Microsoft Edge.
Version 86.0.615.3 (official internal version) dev (64-bit)
test result
an error has occurred
Microsoft Edge
Version 85.0.564.41 (official internal version) (64-bit)
test result
an error has occurred

**Comment by dingpengyu** [comment]
hi
This is the html package from my server's pve - Proxmox Virtual Environment page.
[pve - Proxmox Virtual Environment web all.zip](https://github.com/nvaccess/nvda/files/5142341/pve.-.Proxmox.Virtual.Environment.web.all.zip)

**Comment by feerrenrut** [comment]
Sorry @dingpengyu that too much to go through. It's quite likely that this is caused by an error in the site. It might be a good idea to raise an issue with "Proxmox Virtual Environment". We are happy to work with them to help resolve the issue, but they will need to provide a minimal test sample that we can look at.

**Comment by dingpengyu** [comment]
I will forward this question to the pve Proxmox Virtual Environment mailing list
Thank you for your response!

**Comment by ThomasLamprecht** [comment]
> Sorry @dingpengyu that too much to go through. It's quite likely that this is caused by an error in the site. It might be a good idea to raise an issue with "Proxmox Virtual Environment". We are happy to work with them to help resolve the issue, but they will need to provide a minimal test sample that we can look at.

Hi, Proxmox VE dev here.
Which error types would cause such a behavior?

We could provide a small test system, I mean it's really easy to setup oneself in a VM if one wants just to checkout the interface.
ISO would be here: http://download.proxmox.com/iso/proxmox-ve_6.2-1.iso
https://pve.proxmox.com/wiki/Installation

I'll see if I get time to setup a windows VM to test NVDA out next week.

**Comment by dingpengyu** [comment]
> > Sorry @dingpengyu that too much to go through. It's quite likely that this is caused by an error in the site. It might be a good idea to raise an issue with "Proxmox Virtual Environment". We are happy to work with them to help resolve the issue, but they will need to provide a minimal test sample that we can look at.
> 
> Hi, Proxmox VE dev here.
> Which error types would cause such a behavior?
> 
> We could provide a small test system, I mean it's really easy to setup oneself in a VM if one wants just to checkout the interface.
> ISO would be here: http://download.proxmox.com/iso/proxmox-ve_6.2-1.iso
> https://pve.proxmox.com/wiki/Installation
> 
> I'll see if I get time to setup a windows VM to test NVDA out next week.
hello ThomasLamprecht
Thank you for using NVDA to investigate this issue.
proxmox-ve This is an excellent product.
thanks

**Comment by Adriani90** [comment]
It seems the error comes from the Sapi4 synthesizer, did you test with other synthesizers? Does the error still occur? I.e. with eSpeak or One Core Voices?
cc: @jcsteh

**Comment by dingpengyu** [comment]
> It seems the error comes from the Sapi4 synthesizer, did you test with other synthesizers? Does the error still occur? I.e. with eSpeak or One Core Voices?
> cc: @jcsteh

Yes, I tested it with other voice synthesizers and it still gives me errors.

**Comment by puffi** [comment]
Hi,
After some tests it looks like this is only an issue with Chrome (and derivatives like the new Edge). Firefox doesn't exhibit the beeps. Could you test the newest Firefox release as well?

PVE uses Ext JS 6.0.1 and the docs say the following:
`Note: Based on the advise of accessibility experts, Ext JS's ARIA support is optimized for the Firefox browser. This recommendation was based on the adoption of Firefox by users of assistive technologies ("AT") as well as Firefox's market-leading support for accessibility features. Other browsers (and AT solutions not available on Firefox), while supported, will lag to some degree based on their level of standards compliance.`
https://docs.sencha.com/extjs/6.0.1/guides/core_concepts/accessibility.html

In addition, I ran the [axe extension](https://addons.mozilla.org/en-US/firefox/addon/axe-devtools/) in both Firefox and Chrome and it mentioned the following errors which relate to the tree view the beeps happen on:
`Required ARIA child role not present: treeitem`
`Required ARIA parent role not present: row`

**Comment by dingpengyu** [comment]
> Hi,
> After some tests it looks like this is only an issue with Chrome (and derivatives like the new Edge). Firefox doesn't exhibit the beeps. Could you test the newest Firefox release as well?
> 
> PVE uses Ext JS 6.0.1 and the docs say the following:
> `Note: Based on the advise of accessibility experts, Ext JS's ARIA support is optimized for the Firefox browser. This recommendation was based on the adoption of Firefox by users of assistive technologies ("AT") as well as Firefox's market-leading support for accessibility features. Other browsers (and AT solutions not available on Firefox), while supported, will lag to some degree based on their level of standards compliance.`
> https://docs.sencha.com/extjs/6.0.1/guides/core_concepts/accessibility.html
> 
> In addition, I ran the [axe extension](https://addons.mozilla.org/en-US/firefox/addon/axe-devtools/) in both Firefox and Chrome and it mentioned the following errors which relate to the tree view the beeps happen on:
> `Required ARIA child role not present: treeitem`
> `Required ARIA parent role not present: row`

hello puffi
Thanks for the note, I used Firefox 80 to do the test on PVE, Firefox using NVDA to browse the PVE interface did not give me an error sound.

**Comment by feerrenrut** [comment]
Thanks for getting involved @ThomasLamprecht 

It would be helpful if you could copy a snippet of the HTML causing a problem. If we can get a minimal test case, and confirm an error in Chrome, we will be able to work with Google to fix the issue.

**Comment by puffi** [comment]
Looks like the official examples also have this issue: https://examples.sencha.com/extjs/6.0.1/examples/kitchensink/?classic#tree-reorder as well as https://examples.sencha.com/extjs/7.2.0/examples/kitchensink/?classic#tree-reorder

**Comment by dingpengyu** [comment]
hello @ThomasLamprecht 
Is there an official PVE plan to optimize accessible these days?
thanks

**Comment by dingpengyu** [comment]
[Proxmox VE 6.3 has been released](https://proxmox.com/en/news/press-releases/proxmox-ve-6-3).
Ask @ThomasLamprecht 
Will current issues with issues be fixed?
thanks

**Comment by dingpengyu** [comment]
https://bugzilla.proxmox.com/show_bug.cgi?id=3175

**Comment by Adriani90** [comment]
Since this affects cromium based browsers, at least from a Crome perspective maybe @aleventhal or @ObjectInSpace can also help here.
@dingpengyu did you test also to set different languages in NVDA? Just to be sure that this is not a language specific issue.

**Comment by dingpengyu** [comment]
> Since this affects cromium based browsers, at least from a Crome perspective maybe @aleventhal or @ObjectInSpace can also help here.
> @dingpengyu did you test also to set different languages in NVDA? Just to be sure that this is not a language specific issue.

Yes, I tested the English language in PVE using NVDA and the same error occurs.

**Comment by ObjectInSpace** [comment]
If Sencha intends Ext JS to be used in all browsers, optimizing their a11y for only one does not make sense to me.

Regardless, the tree nodes have role=presentation in their div elements, with text inside spans that are related child elements. According to Mozilla's web docs (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_presentation_role) "The presentation role is used to remove semantic meaning from an element and any of its related child elements." Chrome is correctly not reading the child element's text, while firefox is incorrectly reading it. 

I didn't look extensively, but a number of their examples, particularly the modern ones, also had ARIA implementations that appeared incorrect. 

A working implementation of a tree using ARIA roles and keyboard navigation can be found at https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-2/treeview-2a.html

**Comment by dingpengyu** [comment]
cc @seanbudd 
Can you please solve this problem?

**Comment by feerrenrut** [comment]
@dingpengyu this issue appears to be caused by the library being used in Proxmox. Until this is fixed, it seems you can either use Firefox, or you can use a release version of NVDA and you will not hear the error tone.

**Comment by dingpengyu** [comment]
> @dingpengyu this issue appears to be caused by the library being used in Proxmox. Until this is fixed, it seems you can either use Firefox, or you can use a release version of NVDA and you will not hear the error tone.
Thank you for your note
I will close this issues
