### ISSUE TITLE
Support new Microsoft voices

### ISSUE THREAD

**Issue by Cleversn** [nvaccess/nvda#11535]
### Is your feature request related to a problem? Please describe.

NVDA doesn't support the voices used to read text out loud in the new Microsoft Edge web browser, such as Microsoft Natasha for Australian English, Microsoft Clara for Canadian English, and Microsoft Francisca for Brazilian Portuguese.

### Describe the solution you'd like

If possible, please add support for these voices for use with NVDA as with any regular synthesiser.

### Describe alternatives you've considered

None.

### Additional context

You can ear those voices by pressing ctrl+shift+u at any web page in Microsoft Edge.

**Comment by leonardder** [comment]
The output for these voices is generated online, they aren't part of Windows and thus can't be accessed in real time by NVDA.
