### ISSUE TITLE
NVDA voice activation will not read text of textbox on startup (even after re-installation)

### ISSUE THREAD

**Issue by luke-creed** [nvaccess/nvda#11543]
I've reinstalled NVDA a couple of times, and on installation, everything seems fine. Please see below for steps to recreate my issue. The beeps are still present when i click and minimize, etc.

### Steps to reproduce:

- Normal installation
- On Windows search, search "NVDA"
- Right click, open file location
- Uninstall NVDA
- Follow steps to uninstall
- reboot computer
- go to browser "https://www.nvaccess.org/", click on purple box to download
- scroll down to download
- Download and install -> install
- Startup 
- textbox but no voice reading the text

![image](https://user-images.githubusercontent.com/70653456/92007457-fba0c380-ed13-11ea-9b34-02eef160f711.png)

### Expected behavior:
Expected it to read the text in the box on startup

#### Does the issue still occur after restarting your computer? Yes

**Comment by lukaszgo1** [comment]
Could you please post the NVDA log after starting it. Open NVDA menu, tools, log viewer select all and paste here. Also does NVDA speaks during installation?

**Comment by luke-creed** [comment]
INFO - __main__ (13:14:44.538) - MainThread (14780):
Starting NVDA version 2020.2
INFO - core.main (13:14:44.827) - MainThread (14780):
Config dir: C:\Users\Luke\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (13:14:44.827) - MainThread (14780):
Loading config: C:\Users\Luke\AppData\Roaming\nvda\nvda.ini
INFO - core.main (13:14:44.946) - MainThread (14780):
Using Windows version 10.0.18362 workstation
INFO - core.main (13:14:44.946) - MainThread (14780):
Using Python version 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 07:55:33) [MSC v.1916 32 bit (Intel)]
INFO - core.main (13:14:44.946) - MainThread (14780):
Using comtypes version 1.1.7
INFO - core.main (13:14:44.946) - MainThread (14780):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDriverHandler.setSynth (13:14:45.296) - MainThread (14780):
Loaded synthDriver oneCore
INFO - core.main (13:14:45.296) - MainThread (14780):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5 with six version 1.12.0
INFO - brailleInput.initialize (13:14:45.297) - MainThread (14780):
Braille input initialized
INFO - braille.initialize (13:14:45.297) - MainThread (14780):
Using liblouis version 3.14.0
INFO - braille.initialize (13:14:45.300) - MainThread (14780):
Using pySerial version 3.4
INFO - braille.BrailleHandler.setDisplayByName (13:14:45.304) - MainThread (14780):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - core.main (13:14:45.475) - MainThread (14780):
Java Access Bridge support initialized
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (13:14:45.485) - _UIAHandler.UIAHandler.MTAThread (1440):
UIAutomation: IUIAutomation6
INFO - core.main (13:14:45.783) - MainThread (14780):
NVDA initialized
ERROR - NVDAHelperLocal (13:14:46.008) - Dummy-1 (15948):
Thread 15948, build\x86\localWin10\oneCoreSpeech.cpp, ocSpeech_speak::<lambda_588a06e8c661fd02fa72cad965a4a6be>::operator (), 98:
Error -2147221164: Class not registered



Class not registered



ERROR - unhandled exception (13:14:46.008) - Dummy-1 (15948):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "synthDrivers\oneCore.pyc", line 331, in _callback
  File "synthDrivers\oneCore.pyc", line 301, in _processQueue
AttributeError: 'NoneType' object has no attribute 'sync'
INFO - config.ConfigManager.save (13:14:53.164) - MainThread (14780):
Base configuration saved
WARNING - watchdog._watcher (13:15:10.023) - watchdog (5428):
Core frozen in stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1052, in Notify
  File "core.pyc", line 516, in run
  File "mouseHandler.pyc", line 257, in pumpAll
  File "mouseHandler.pyc", line 213, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyc", line 286, in objectFromPoint
  File "NVDAObjects\__init__.pyc", line 95, in __call__
  File "appModules\explorer.pyc", line 266, in chooseNVDAObjectOverlayClasses
  File "baseObject.pyc", line 41, in __get__
  File "baseObject.pyc", line 144, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 976, in _get_parent
  File "NVDAObjects\__init__.pyc", line 95, in __call__
  File "appModules\explorer.pyc", line 266, in chooseNVDAObjectOverlayClasses
  File "baseObject.pyc", line 41, in __get__
  File "baseObject.pyc", line 144, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 979, in _get_parent
  File "NVDAObjects\__init__.pyc", line 95, in __call__
  File "appModules\explorer.pyc", line 266, in chooseNVDAObjectOverlayClasses
  File "baseObject.pyc", line 41, in __get__
  File "baseObject.pyc", line 144, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 977, in _get_parent
  File "IAccessibleHandler\__init__.pyc", line 461, in accParent
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
  File "gui\__init__.pyc", line 581, in onActivate

**Comment by lukaszgo1** [comment]
The relevant part of the log is:


ERROR - NVDAHelperLocal (13:14:46.008) - Dummy-1 (15948):
Thread 15948, build\x86\localWin10\oneCoreSpeech.cpp, ocSpeech_speak::<lambda_588a06e8c661fd02fa72cad965a4a6be>::operator (), 98:
Error -2147221164: Class not registered
Class not registered
ERROR - unhandled exception (13:14:46.008) - Dummy-1 (15948):
Traceback (most recent call last):
File "ctypes/callbacks.c", line 232, in 'calling callback function'
File "synthDrivers\oneCore.pyc", line 331, in callback
File "synthDrivers\oneCore.pyc", line 301, in processQueue
AttributeError: 'NoneType' object has no attribute 'sync'



cc @michaelDCurran It seems OneCore on this system is broken but in that case why NVDA is able to speak during install.

**Comment by luke-creed** [comment]
NVDA does not speak during installation

**Comment by lukaszgo1** [comment]
Can Narrator speak on this machine?

**Comment by luke-creed** [comment]
What is narrator?

**Comment by lukaszgo1** [comment]
A screen reader built-in to Windows. To launch it press Windows+r and type narrator.

**Comment by luke-creed** [comment]
Sorry for the late reply. Narrator does not seem to speak on my machine.

**Comment by lukaszgo1** [comment]
It seems OneCore, that is the default NVDA's speech synthesizer is broken on your machine for whatever reason. You should be able to switch to eSpeak by opening NVDA menu, preferences, settings choose speech, then click change in the synthesizer group and choose eSpeak. I'm not sure there is anything to be done in NVDA though possibly we should detect that OneCore is broken in this situation and switch to eSpeak by default.

**Comment by luke-creed** [comment]
it works now. Thank you lukaszgo1

**Comment by XLTechie** [comment]
On Wed, 2 Sep 2020, Łukasz Golonka wrote:

> A screen reader built-in to Windows. To launch it press Windows+r and type narrator.

Or just press control+windows+enter.
Same to stop it.

**Comment by XLTechie** [comment]
To try to fix OneCore, do the following:

press your windows key and type "speech".

Move down to "speech settings", and press enter.

Then tab over to the "Manage voices" group, and you should be on the "add 
voices" button.

Press enter on that, and you will be able to enter and choose your language, and 
then install the appropriate voice pack(s). For example, you can install the 
English (US) voice pack.

Once you select and install the voice, close everything and restart NVDA.

At this point, you can try to switch back to OneCore, by pressing 
Insert+Control+S, and choosing Windows OneCore from the dropdown, then pressing 
OK.

If you try it, please let us know if that fixes the problem.

**Comment by Brian1Gaff** [comment]
Well it obviously knows that synth does not apply to windows 7, so I'd have 
thought if a synth failed to initialise it should always go to Espeak. 
However, I think the original problem needs to get fixed in his 
installation, who knows what else might be broken?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----
