### ISSUE TITLE
Error sounds when speaking after NVDA has stayed silence for a few seconds

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#11542]
### Steps to reproduce:

1. Use any synthesizer. Have NVDA speak, don't do anything and then do something to cause NVDA to speak again.

### Actual behavior:

The following entry is logged:

```
ERROR - unhandled exception (21:41:48.696) - MainThread (30336):
Traceback (most recent call last):
  File "wx\core.pyc", line 2196, in Notify
  File "nvwave.pyc", line 351, in _close
  File "nvwave.pyc", line 91, in _winmm_errcheck
OSError: [Errno 5] The specified device handle is invalid.
```

### Expected behavior:

No errors or error sounds

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-20793,9a4074bc

#### Windows version:
Windows 10 2004

#### Name and version of other software in use when reproducing the issue:
Reproduceable with ESpeak NG

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by Neurrone** [comment]
Actually, I just saw this happening even while I was continually typing, so am not sure what's going on.

**Comment by Neurrone** [comment]
Potential duplicate of #11482, will wait till that makes it into the next snapshot build and willl test.

This only started happening when I switched synthesizers to test something else.

**Comment by Adriani90** [comment]
@Neurrone are you still having this issue in NVDA 2023.2? Please test with wASAPI enabled in advanced settings if possible.

**Comment by Neurrone** [comment]
Haven't seen this happening for a long time, closing.
