### ISSUE TITLE
upstart.com rate check form partially inaccessible with NVDA

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#11566]
I'm sure this is bad/inaccessible site design on Upstart's part, but there may be web elements with which NVDA could do better. My HTML/CSS skills are very rusty, and I haven't tried any other screen readers so far.

### Steps to reproduce:

1.  Visit: https://www.upstart.com/funding_form
2.  Begin filling out the form.

### Actual behavior:

The following fields and form areas have strange behavior:
* Month of birth, and also probably name suffix. This is a select list with auto completion. However it doesn't always seem to close, and NVDA doesn't always seem aware that it hasn't.
* Highest level of education. This does not even appear to NVDA to be clickable in any way in browse mode. However with object nav, there is a readonly edit field. Clicking that with object nav will (sometimes) get the options, but even after apparently choosing one, there may be suboptions, and other form fields appear. Again, sometimes the one chosen is not the one selected at the end. Bypass may be necessary to use parts of that interface, using the arrow and enter keys as coded by the site.
* Highest level of education. See above; same kind of thing.

### Expected behavior:

Fields reasonably accessible with NVDA and other screen readers.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

alpha-20840,c8d6ab95

#### Windows version:

10 version 2004

#### Name and version of other software in use when reproducing the issue:

Firefox 80.0 64 bit.

#### Does the issue still occur after restarting your computer?

N/A

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

alpha-20809,f4cb0847, same.

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes

**Comment by Adriani90** [comment]
cc: @MarcoZehe, @jcsteh

**Comment by Adriani90** [comment]
@XLTechie is this issue still occuring in the last version of NVDA and the newest browser updates?

**Comment by seanbudd** [comment]
I'm going to assume this is an issue with the website. If there are still accessibility issue with that website, please report it to the web authors.
If this is not an issue with that website, we need a minimal HTML sample to investigate this further.
