### ISSUE TITLE
Log too verbose with last alpha

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#11574]
### Steps to reproduce:

* Set log level to DEBUG
* Perform some actions
* Press NVDA+F1 to open the log
* Press many times upArrow to review the log.

### Actual behavior:

The following lines can be found regularly and often in the log:

> ```DEBUG - synthDrivers.oneCore.SynthDriver.cancel (10:53:42.998) - MainThread (7200):
> Cancelling
> DEBUG - synthDrivers.oneCore.SynthDriver._callback (10:53:43.008) - Dummy-22 (18476):
> Done pushing audio
> DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (10:53:43.008) - Dummy-22 (18476):
> Calling sync on audio player
> DEBUG - nvwave.WavePlayer._isPreferredDeviceOpen (10:53:43.008) - MainThread (7200):
> preferred device: WAVE_MAPPER current device name: WAVE_MAPPER (id: -1)
> DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (10:53:43.008) - Dummy-22 (18476):
> Calling idle on audio player
> DEBUG - nvwave.WavePlayer._isPreferredDeviceOpen (10:53:43.008) - Dummy-22 (18476):
> preferred device: WAVE_MAPPER current device name: WAVE_MAPPER (id: -1)
> DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (10:53:43.008) - Dummy-22 (18476):
> Queue empty, done processing```

### Expected behavior:

The log does not contain so much information regarding audio player so that the log can be read more easily when debugging. Maybe a solution would be to have a specific log option in advanced panel for this type of debug messages.

#### NVDA installed/portable/running from source:
From source

#### NVDA version:

Last alpha (commit f33664ec4935872e95f3add083a1e0ee96499832)

#### Windows version:

Windows 10

#### Name and version of other software in use when reproducing the issue:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2020.2 is OK. These appeared in last alpha only.

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by CyrilleB79** [comment]
@feerrenrut: I think that you have introduced these debug messages.
Is it expected to have so much such messages? Thanks.

**Comment by feerrenrut** [comment]
These log messages were left in since this change was made quite close to when we plan to release. If there were any problems with the nvWave changes, this would help us to rectify quickly. I certainly agree that longer term these messages are not very useful and quite noisy. I'd accept a change to put these messages behind an nvWave logging flag (in advanced settings panel). This change will likely have to target beta.

**Comment by michaelDCurran** [comment]
Agreed that we should  move debug logging for our in-built synthesizers under their own debug logging category. However, we will look into this after 2020.3 is released I think. Note that there is one nvWave message there which has already been moved to the nvWave debug logging category in the beta branch and will soon be in alpha.

**Comment by CyrilleB79** [comment]
Hi Mick

Yes, I am aware of #11582, I am the author. It was meant to address the present issue, but strangely githiub does not closes the present issue automatically even if I hav mentionned this issue in the PR. Should I close it manually?

**Comment by michaelDCurran** [comment]
Yep. You can close it manually with a comment mentioning that it was 
fixed in pr #11582  if you like. Though another option is to keep it 
left open for later fixing of all the synthDriver messages.

**Comment by leonardder** [comment]
I'd say, let's do the latter.
