### ISSUE TITLE
New ability to abandon the teams docx document viewer screen

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#11584]
### Steps to reproduce:
Open microsoft teams
Open the file viewing tab, or enter a channel, choose the files tab.
In the file selection window find a .docx file
Press enter to open the file.
The teams docx document viewer will open, which is inaccessible.
### Actual behavior:
there is no way to leave this screen, even closing teams and reopening the docx document viewer will open again.
### Expected behavior:
There must be a shortcut key to leave this window and return to the file list.

I believe that teams themselves do not provide a shortcut key for this purpose.
Another screen reader provided a shortcut key to leave this screen and return to the teams file list.
As I suffer from this problem when I mistakenly press enter on a docx file and get stuck on this screen, I suggest giving nvda the same ability, to abandon this screen and return to the teams file list
For a blind user pressing enter in a docx file in teams is an error, we must press the aplications key and use the open option in the application, however we sometimes make mistakes and press enter, and using nvda currently we are in an uncomfortable situation that we cannot manage get away with quickies.
The only way I know how to get out of this screen is to move the mouse across the screen, hope that the mouse falls over another area of the teams and click with the left mouse button.
#### NVDA installed/portable/running from source:
all
#### NVDA version:
all
#### Windows version:
all
#### Name and version of other software in use when reproducing the issue:
teams
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by leonardder** [comment]
This issue should be reported to Microsoft, rather than be solved by NVDA. I understand that another screen reader has a workaround, but that screen reader is known to create workarounds like plasters, making it even less urgent for the actual problem to be solved by the software author.

Having said that, I agree that it is difficult to escape from this, it requires you to use object navigation, route focus to the back button and then move back out of the viewer.

I'll see whether I can contact the Microsoft Enterprise Accessibility Desk about this.

**Comment by zstanecic** [comment]
what's that for a screenreader which likes to do that?

**Comment by leonardder** [comment]
This is being investigated by Microsoft: https://twitter.com/MSFTEnable/status/1304278664004145152

**Comment by Adriani90** [comment]
@fernando-jose-silva do you still have this issue with NVDA 2022.4 and Microsoft Teams 1.6.0?

**Comment by fernando-jose-silva** [comment]
we can consider that the problem has been solved, it is possible to exit the document currently by pressing ctrl + f6.
Maybe another command works better, but don't read teams help

**Comment by Adriani90** [comment]
Closing as works for me. Thank you for the update @fernando-jose-silva
