### ISSUE TITLE
Crash with Microsoft Word 365

### ISSUE THREAD

**Issue by math65** [nvaccess/nvda#11600]
### Steps to reproduce:

Open a document, and write in Microsoft Word

### Actual behavior:

When writing fast, NVDA crashes, and you have to restart it

### Expected behavior:

NVDA should not crash

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

NVDA 2020.2

#### Windows version:

Windows 10 (Version 2004)

#### Name and version of other software in use when reproducing the issue:

Microsoft Word 365

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes

**Comment by Andre9642** [comment]
Hi @math65 :)
This issue should be fixed in 2020.3. See #11431, #11425 and #11414.
Could you test with an alpha build and report the behavior?

**Comment by Adriani90** [comment]
Yes, this is fixed in NVDA alpha versions. You can downlaod and test the last alpha here:
https://www.nvaccess.org/files/nvda/snapshots/
I am closing this issue, but please feel free to comment if you can still reproduce this in the last alpha version and we can reopen it. Thanks.
