### ISSUE TITLE
Visual Studio: IntelliSense tooltips reported twice

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#11611]
### Steps to reproduce:
1. Open Visual Studio 2019
2. Open a C# project
3. Enable reporting of Tooltips
4. Trigger an IntelliSense autocomplete suggestion by typing something.
5. Arrow through the suggestions

### Actual behavior:
The selected item is announced, followed by twice the tooltip.

### Expected behavior:
The selected item is announced, followed by once the tooltip.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-20957

#### Windows version:
Windows 10 2004

#### Name and version of other software in use when reproducing the issue:
Visual Studio 2019 16.7.3 Enterprise

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by leonardder** [comment]
@josephsl Have you seen this behavior in more applications? What do you think would be the bst way to work around this? I'd like to avoid a check like _shouldAllowUIALiveRegionEvent if possible

**Comment by josephsl** [comment]
Hi, when I played with VS 2019 (IDE window), these tooltips were empty strings, so perhaps suppressing UIA tooltip open event for a tooltip with no label might work for this situation. As for live region and tooltips, haven’t come across that in a while (it was prevalent in Settings app in ancient Windows 10 feature updates (say, 1511)). Thanks.
