### ISSUE TITLE
the Page Break announce setting in the punctuation/symbols dialog should be set to most or all by default

### ISSUE THREAD

**Issue by Gene703122** [nvaccess/nvda#11625]
### Is your feature request related to a problem? Please describe.
Some programs like Openbook, Kurzweil, and others place hard page breaks in exported files.  NVDA announces these no matter what punctuation level is set in the punctuation level setting for the voice being used.
### Describe the solution you'd like
The default setting in the punctuation and symbols dialog should be set to most or all.  It is currently set to none.
### Additional context
This is likely to be a serious annoyance for a lot of users.  Bookshare requires files in RTF  and if readers get such bbooks, my guess is that they are sent with hard page breaks to the downloader.  Also, blind ;people share files they export from OCR programs and they probably generally place hard page breaks in exported files.

**Comment by XLTechie** [comment]
Gene703122 wrote:

> This is likely to be a serious annoyance for a lot of users. Bookshare requires files in RTF and if readers get such bbooks, my guess is that they are sent
> with hard page breaks to the downloader.
> Also, blind ;people share files they export from OCR programs and they 
> probably generally place hard page breaks in
> exported files.

Given that you say "this is likely to be", and "probably generally", and "my 
guess is".

Are you actually blind and using NVDA for every day accessibility, or are you 
just reporting something that you think might be a problem for blind users?

Your uncertain statements above seem to suggest that you have not personally 
experienced these problems, but are assuming that they will be problems for 
users.  If that is the case: can you point to forum posts, mailing list threads, 
or other actual user experiences of the difficulty here?

Can you provide a description of what NVDA actually speaks that you find 
objectionable?
I do not use Bookshare, and do not use RTF, but in dealing with OCRed documents, 
I have not observed this being a problem--though I do not use K1000 nor 
Openbook.

**Comment by Gene703122** [comment]
I am blind and use NVDA and have seen this behavior.  I used uncertain words because I have seen almost no complaints about this so I have no evidence of it causing problems for a lot of people.  But logically, it should.  

The behavior is that every time a page break is come to and crossed, NVDA announces the phrase page break.  This is really annoying when reading text and you hear page break spoken every time it occurs in the document.  

I wrote about the problem here because someone asked how to stop this behavior on a list I'm on.  I have been annoyed by this behavior when reading documents I exported from Openbook. 
 The solution found is to raise the setting from none to a higher level.  But I see no reason for page breaks to be announced unless using a high setting.  I suspect that a lot of people don't complain because they don't participate in the community, they may not even know what resources are available and I think many people are intimidated by technology and just accept things as they are some of the time.

**Comment by Gene703122** [comment]
I'm new to Github and I may not have replied properly online.  I see no 
reply e-mail.  So I'm replying again.  I'm sorry if those who look at the 
page see repetition.

I haven't seen much in the way of complaints about this problem.  I saw a 
very recent complaint and maybe in the past one or two over a long time. 
But this logically should be an annoyance for a lot of people if I am right 
that Book share books have hard returns in them.  and, as I said, one would 
think that blind people at times share books or other material exported from 
Kurzweil and Openbook with other blind people, and other OCR programs may 
have hard returns in files.

I am a blind user of NVDA.  The behavior is that every time a hard return is 
crossed while reading a document, using read to end, read by line or any 
other kind of movement commands, the phrase page break is spoken.  I find 
this very annoying and its completely unnecessary if the default setting at 
which this is spoken is raised to most or all.

As to why we haven't seen any complaints that amount to something about 
this, my speculation is that its because so many NVDA users are not active 
and probably don't even know about the NVDA community and because many 
people are, in my opinion, intimidated by technology and often accept things 
unless they are really serious problems as they are.

Gene.
-----Original Message-----

**Comment by XLTechie** [comment]
Gene703122 wrote:

> But this logically should be an annoyance for a lot of people if I am right
> that Book share books have hard returns in them. and, as I said, one would
> think that blind people at times share books or other material exported from
> Kurzweil and Openbook with other blind people, and other OCR programs may
> have hard returns in files.

You have named two different things: hard returns, and page breaks.
Which are we actually talking about?  They are not the same thing.

What might be helpful to understand this issue, is if you could attach an 
offending RTF file with examples of this.  Or some other kind of file.  Or a few 
such files.

> As to why we haven't seen any complaints that amount to something about
> this, my speculation is that its because so many NVDA users are not active
> and probably don't even know about the NVDA community and because many

The https://groups.io/g/nvda mailing list has 1,380 members.  There are lists 
for many other languages, and even other English lists such as 
https://groups.io/g/nvdaHelp .
I have the impression this would have been heard of if it really was a problem.
But I could be wrong for the reasons you pointed out or others.

> people are, in my opinion, intimidated by technology and often accept things
> unless they are really serious problems as they are.

Okay now that, I will agree with.

I'm not really trying to give you the hard time it seems like.  This issue just 
struck me as unconvincing as originally presented.  I'm willing to have my mind 
changed or to help nail down some of its particulars.
It seems very straight forward, I've just never heard anyone complain of it, and 
I thought I should have.  That makes me think it's not as clear cut as your 
original description suggests.

**Comment by Gene703122** [comment]
I made a mistake.  I am talking about page breaks.

Gene
-----Original Message-----
