### ISSUE TITLE
NVDA - Browsw mode - Breadcrumb is not navigable

### ISSUE THREAD

**Issue by kolaps33** [nvaccess/nvda#11626]
### Steps to reproduce:
1. Open URL:  
https://www.w3.org/TR/wai-aria-practices-1.1/examples/breadcrumb/index.html
2. Navigate to the Breadcrumb example (located under the heading Example) in browse mode
3. press down arrow key once you are in breadcrumb

### Actual behavior:
NVDA narrates:
Breadcrumb  navigation landmark    list  with 4 items  visited  link    WAI-ARIA Authoring Practices 1.1  link    Design Patterns  link    Breadcrumb Pattern  visited  link    current page  Breadcrumb Example

When user want to continue to the next link, then it skips the navigation and navigation continue in after breadcrumb. 

### Expected behavior:
NVDA narrates only first link in the breadcrumb. 
Navigation continues into second link in the breadcrumb. 

#### NVDA version:
2020.2

#### Windows version:
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.19041 Build 19041

#### Name and version of other software in use when reproducing the issue:
Tested with Chrome Version 85.0.4183.102 (Official Build) (64-bit)

#### Does the issue still occur after restarting your computer?
YES 

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NO I haven't try other version of NVDA.

#### If addons are disabled, is your problem still occuring?
yes problem still occuring after diabled all addons... 

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no did run anything special

**Comment by lukaszgo1** [comment]
This is actually a correct behavior since these links are visually in one line. To navigate from link to link you can either use tab or quick navigation key "k".  Alternatively you can disable screen layout by pressing NVDA+v to have every link in a separate line.

**Comment by kolaps33** [comment]
@lukaszgo1 thank you very much for quick answer and explanation. 
Based on your comment I consider it working as expected and closing the issue.
