### ISSUE TITLE
Installer - Command Line Switches: Add the ability to copy configuration from a portable version of NVDA

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11635]
### Is your feature request related to a problem? Please describe.

When installing NVDA from a portable copy, users have the option of copying over the current configuration set that's part of the portable version - rather than having to perform this step manually. When deploying NVDA to multiple machines within a corporate environment, both administrators and users may find it useful if during automated installations using either the "--install" or "--install-silent" command line switches, an additional switch could be added to tell the installer to copy user configuration from a specified location as part of the process - for example, an admin may wish to automatically set logging to a higher level so that issues can be diagnosed - rather than having to ask users to perform this step manually. Alternatively, more advanced users may have multiple machines where they wish to share the same configuration - there's no quick way of copying this over unless the GUI is used to install NVDA, or the "nvda" directory is manually copied from %appdata% on the "master" machine.

**Comment by lukaszgo1** [comment]
Duplicate of #9676 and would be resolved when #9679 is merged.

**Comment by elliott94** [comment]
Thank you. :) Closing as a duplicate.
