### ISSUE TITLE
Logging: Add one-time dialog to warn users that input will be logged if setting Log Level to either Input/Output or Debug

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11636]
### Is your feature request related to a problem? Please describe.

If setting their Log Level to either "Input/Output" or "Debug", I feel that it's really important for users to be aware of the fact that any input from the point that NVDA is launched until it's exited will be stored as part of NVDA's log. Whilst we make this explicitly clear within NVDA's documentation, could we possibly consider adding a one-time dialog (with "Yes/No" buttons) that notifies the user of this fact when changing their log level to either of the above? More than happy to come up with the text that could be displayed depending on feedback. Several things to be mindful of:

1. If the user chooses "Yes" to signify that they're happy with this choice, we should store this within NVDA's configuration so that they're not prompted each time they change their log level to either "Input/Output" or "Debug"

2. If added, we should ensure that this alert is triggered both when changing log levels within NVDA's GUI, but also when launching with a log level defined as part of a command line switch. As an example - system admins may choose to log at this level to assist with diagnosing (although in theory I don't think that this would be a good idea due to privacy/disk usage) - but if this is done for whatever reason, users should be aware of the privacy implications of this

**Comment by DrSooom** [comment]
Duplicate of issue #8515.

**Comment by elliott94** [comment]
Thank you - closing as a duplicate.
