### ISSUE TITLE
Keydown event not triggered on button element when NVDA is open

### ISSUE THREAD

**Issue by clanceyp** [nvaccess/nvda#11630]
The javascript 'keydown' event not triggered on button element when NVDA is open

### Steps to reproduce:
* Enable NVDA
* Open https://jsfiddle.net/clanceyp/hop4zv7L/ 
* Tab to or click on the button to give it focus
* Press Enter key

### Actual behavior:
No keydown event is triggered

### Expected behavior:
The keydown event is triggered and key code is written to the HTML 

#### NVDA installed/portable/running from source:
NVDA installed

#### NVDA version:
2020.1

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
Firefox 80, Chrome 85, Edge 85

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by clanceyp** [comment]
(interesting, it was just pointed out to me, the keydown event works as expected if you hold down the shift key)

**Comment by feerrenrut** [comment]
You may be in [browse mode](https://www.nvaccess.org/files/nvda/documentation/userGuide.html#BrowseMode) (by default signified by a "boop" noise), in this case this behavior is expected. This mode provides shortcuts to navigate the page more efficiently. To switch to focus mode, press NVDA+space and hear a "click". These sounds can be replaced with speech if you prefer via the ["Audio indication of focus and browse modes" option.](https://www.nvaccess.org/files/nvda/documentation/userGuide.html#BrowseModeSettingsPassThroughAudioIndication)

**Comment by clanceyp** [comment]
Aha, many thanks!
