### ISSUE TITLE
Installer: Add command line switch to prevent COM Registration Fixes from being run after a successful installation

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11648]
### Is your feature request related to a problem? Please describe.

For developers, it may be useful in certain situations to understand which parts of their applications may break COM when the software is uninstalled. If using NVDA to perform this testing, however, the installer automatically runs the COM Registration Fixing Tool when the installation process completes.

To aid in testing, could we possibly add a new command line switch to ensure that when installed, this tool isn't run? Whilst in theory a developer could simply reinstall and then uninstall their application, having the option of not running this tool in the first place has the potential to speed up the debugging process.

**Comment by JulienCochuyt** [comment]
@elliott94,
The testing you describe could as easily be accomplished with a portable copy of NVDA - or yet easier for a new comer with NVDA just ran from its installer.
Installed NVDA only has the added ability to be used on secure screens.
Can you identify a case where broken COM registration specifically impacts secure screens?
In my experience, the first (and almost sole) thing to break is browse mode - which can easily be tested without installing.
Alternatively, can you identify a case where COM registration could be of any arm for a regular installation?

I'm closing for now. Please feel free to re-open with added information if you think I missed the point.
