### ISSUE TITLE
Configuration: Additional considerations for clean-up

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11669]
### Is your feature request related to a problem? Please describe.

In #10014, due to the introduction of the Scratchpad directory we performed some clean-up to ensure that any empty directories that are now part of the Scratchpad folder were automatically removed. There are several further directories that I've noticed which automatically get created when launching NVDA - these may not always be relevant, so to assist in making sure that NVDA's configuration folder is as tidy as possible it may be worth only creating these when needed. I'm aware that the work required to change NVDA's code to only create these when required may not be worth the effort - I've listed the directories below:

Addons - Only needs to be created upon the first add-on installation

Profiles - This only needs to be created at the time a user creates their first profile

Speech Dicts - Only needs to be created the first time that a speech dictionary is created

Updates - Only needs to be created at the point of downloading an automatic update - may never apply if a user has this feature disabled

### Describe the solution you'd like

Consider only creating each directory when its feature is used for the first time - and remove existing directories if they are empty.

**Comment by lukaszgo1** [comment]
I do agree with this proposal and may look into it at some point. Having said  that this is a duplicate of #10027 which you've created yourself a while ago :-)

**Comment by elliott94** [comment]
Ah, I'd forgotten that I'd already raised this! :) Thank you, will close this one.
