### ISSUE TITLE
NVDA+Alt+C not reading cell comment in Excel

### ISSUE THREAD

**Issue by Luke-Robinett** [nvaccess/nvda#11664]
### Steps to reproduce:
1. Open Excel and create a new worksheet
2. Type something in cell A1 just so there's some content
3. Right click on cell A1 and choose new comment
4. Type something in the comment box and click Post
5. With the cursor over A1, press NVDA + Alt + C on the keyboard

### Actual behavior:
NVDA reports that there is no comment. I've attached an example Excel 365 worksheet where cell A1 has a comment that NVDA won't read aloud.

### Expected behavior:
NVDA should read aloud the comment.

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
2019.3.1

#### Windows version:
Windows 10 Pro

#### Name and version of other software in use when reproducing the issue:
Microsoft Office 365 - Excel

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If addons are disabled, is your problem still occuring?
N/A

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes.
[nvda-comment-issue.xlsx](https://github.com/nvaccess/nvda/files/5283963/nvda-comment-issue.xlsx)

**Comment by Adriani90** [comment]
The comments in Excel 365 are not supported yet by NVDA. The comments you usually know from older Office versions are now called notes. See #9195 for more details. You can read also chapter 11.2.3 in the user guide for more information.
I am closing this issue as it is blocked by #9195 anyway.
