### ISSUE TITLE
waterfox 2020.9 flakey and unstable on many sites after lenghthy period

### ISSUE THREAD

**Issue by smeveriss** [nvaccess/nvda#11667]
Hi.
please see here for the waterfox issue posted.
https://github.com/MrAlex94/Waterfox/issues/1765
This has gotten a lot more than just a few sites, simply put after moving through a few sites waterfox becomes unresponsive.
Everything from blogspot, github and the like will cause all sorts of issues.
In the issue alex mentions that these issues I am having are in firefox latest and reccons they are javascript ones.
However its happening a lot more than I'd like.
I was able to make things less flakey by resetting my firmware and flushing my memmory in the laptop with a hard reset but its still flaking out more than I'd like, and never used to on the previous version 2020.8.1
I am seriously tempted to just revert now as there was no issue in that version.
The debug log is below
[nvda waterfoxcrash.log](https://github.com/nvaccess/nvda/files/5285961/nvda.waterfoxcrash.log)

**Comment by Brian1Gaff** [comment]
Is this the classic or the one based on the newer Firefox?

I have to say that although Waterfox can be a little slower,and we are 
talking classic here, it seems quite good. I have not checked for updates of 
late though. Apologies for this bit, but I'm sure somebody else will ask you 
to fill out the template... grin.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by smeveriss** [comment]
its classic, and its version 2020.09.
I am back on 08 which has no issues.
So far I have tried turning off addons, uninstalling and reinstalling, etc.
I have even tried on another system.
It may simply be my amd cpu but I have no way to prove or disprove that of course.
I have doodled with cache settings and things did get worse when I fiddled with numbers but to be honest, I have spent at least 4 days off and on.
Its not that easy to nail down to anything.
All I know is that 08 works fine, 081 had some cpu spikes but no crashing but 09 did crash a lot.
If you want to fiddle with it to see why and where it goes nuts go nuts.
If you have or know someone that is on the yourdolphin testing forum, that site has a slow responce time, try that site login and muck about.
Now the sites do execute but who knows.
I have tried this with sites I use aryion, blogspot, wordpress, for some sites like github or a dolphin forum, I have to just access the site and it will crash.
With others say nvaccess going to a bandcamp site I have to go through 2 links.
It never does it if you open sites from a google search or something in different tabs or windows only on the same window.
I thought earlier this week that I had fixed since after I did a firmware update I had to reset the memmory because windows was not starting right and the fan was going really high but that doesn't happen anymore and in fact the system is running better than it has been in ages.
However, this version who knows.
According to the waterfox devs if they are to be believed, all they put are security updates.
Its happening in firefox to.
Their responce is that it has nothing to do with them and its some stack bomb or javascript error.
I have tried several times to get the conversation going but no responce though 3 of them are listening to the issue.
If this is how things are, I may just stay with waterfox 20.08, and if I need to be extra secure use chromium edge or chrome.
I like the classic interface but if this thing will become unstable or fiddly to handle, then I will just have to make sure I keep my protections updated and have a brouser for secure work and one for non secure work.

**Comment by smeveriss** [comment]
Just updated the waterfox issue.
g3 fixes most things though dropbox and google will intermittantly crash.
Biggest issues are all the extra content in the interface with search bars, extentions and a bunch of other extras down the side I can't hide as well as the fact resilio sync window not displaying properly.
That is its displaying but I can't read the main content.
I have tried with no extentions and addons and its still like that.
So I am back on 08.
There is almost nothing holding me on 08 bar those issues.
Could be interaction, but who knows.
I have latest updates and the system is stable.
I do still run noscript classic but thats about the only thing I do run.
G3 has potential and if they can sort these last 3 issues I will be using it.
Its more stable and its faster.
I also know when scripts interact
or when they complete loading pages.
I suspect with extra sounds enable that this is probably an interaction with nvda as waterfox does in fact complete loading the page.
So its probably not exclusively waterfox itself.

Anyway I have included the last 2 nvda logs, an older one and the current one.

**Comment by Adriani90** [comment]
@smeveriss can you still reproduce your issues in Waterfox Latest Version · G5.1.5
Release Date · 2023-04-13?

Please test with NVDA last lpha version. you can download the last alpha at this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Adriani90** [comment]
The upstream issue on waterfox repo is closed and we didn't get updates upon request from the initial author since more than 3 years. I am closing as abandoned. The waterfox issue indicates that most problems were solved for the user anyway. If you are still having issues with Waterfox while using NVDA 2024.2 or newer, please comment and we can reopen.
