### ISSUE TITLE
Audio: Consider extending the time that NVDA keeps an audio device open when not receiving any output from 10 to 30 seconds

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11670]
### Is your feature request related to a problem? Please describe.

In #11024, changes were made so that NVDA only closes the audio device if not receiving any output for 10 seconds - rather than immediately. Many of the machines that I use make use of drivers that take several seconds to re-open the audio device when closed - and whilst this pull has made things much quicker than they used to be, could we possibly consider extending this period from 10 to 30 seconds? Whilst I realise that with this kind of feature it may not be ideal to keep the audio device open indefinitely (battery impact is just one example that I can think of), I think that extending this by 20 more seconds gives some further headroom. As an example, I often find during my work that I need to speak to colleagues for several seconds at a time, and by the time I've come back to my machine I then have to wait for several more seconds before I receive any speech output - extending this value would be a huge help, and is hopefully considered as a good balance.

**Comment by lukaszgo1** [comment]
As of #11531 we do not close Audio device at all, so if  you're still experiencing delays after some time of audio inactivity the cause is different.

**Comment by elliott94** [comment]
Ah - I wasn't aware of this, thank you. :) Will close.
