### ISSUE TITLE
System-wide Registry Parameters: Add combo boxes for each setting to the Advanced panel of the Settings GUI

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11675]
### Is your feature request related to a problem? Please describe.

Section 16.2 of the User Guide outlines several system-wide parameters that can be set from within the registry. Could we possibly consider adding combo boxes for these entries (currently "configInLocalAppData" and "serviceDebug") to the "Advanced" panel of the Settings GUI? This would make these settings easier to quickly change for testing purposes, whilst ensuring that they're not easily available for users who may not ever need to change these options.

**Comment by leonardder** [comment]
Changing these settings requires administrative privileges. Furterhmore, there are several reasons why I think having these even in the advanced panel isn't a very good idea:

1. Service debug can cause an enormous security risk if used incorrectly. Therefore, hiding it behind a registry parameter ensures that only people with decent system admin skills can set it. It is even not present by default, so you really have to dig it up from the user guide, and that is exactly the intention behind this option IMO.
2. While config in local app data is certainly less risky, it causes the current configuration to be abandoned. It can therefore cause unexpected side effects for people and is also really meant to be a sysadmin thing.

I'm tempted towards closing this as won't fix.

**Comment by Adriani90** [comment]
Closing as won't fix as per the comment above.
