### ISSUE TITLE
User Guide - Command-line Options: Specify that quotation marks must be used if loading NVDA's configuration from a location that contains spaces

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11671]
### Is your feature request related to a problem? Please describe.

NVDA offers two command-line switches ("-c" and "--config-path") that can be used to manually specify the folder from where NVDA should load its configuration. What may not be immediately clear, however, is that if specifying a path that contains spaces, quotation marks (") need to be used. Could we update the User Guide to reflect this?

**Comment by feerrenrut** [comment]
Really this is shell specific behavior. Though I don't think there is any harm adding a note / example.

**Comment by XLTechie** [comment]
> Really this is shell specific behavior. Though I don't think there is any harm adding a note / example.

It is, but is there any shell that does not have this behavior?

**Comment by CyrilleB79** [comment]
Given this option is described in an "advanced" paragraph of the User Guide, I imagine that almost any advanced user using them would know how the cmd shell (or other) works.

If we provide examples with the double quotation marks, we should provide them for the three options that may use a path as parameter. Also, providing example with the quotation marks may let think that they are mandatory, which is not true for path containing no spaces.

Thus I would be inclined to close this ticket as "won't fix".

@elliott94 did you open this issue for yourself or for someone else? If for you, after 3 years, are you more accustomed to handling paths containing spaces in the shell?

**Comment by seanbudd** [comment]
Closing as won't fix
