### ISSUE TITLE
LibreOffice Writer: Quotes are not announced

### ISSUE THREAD

**Issue by peterpacult** [nvaccess/nvda#11686]
### Steps to reproduce:
1.Open Writer
2. Create a quote, no matter character or paraph formated.
3. Read the text with, for example, with Screenreader NVDA.

### Actual behavior:
When reading to text which contains a quote, no quote is announced.

### Expected behavior:
Announcment of the quote.

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.2

#### Windows version:
Edition	Windows 	10 Home
Version				1909
Operating system build	18363.1016

#### Name and version of other software in use when reproducing the issue:
LibreOffice
Version:	7.0.0.3 (x64)
Build ID:	8061b3e9204bef6b321a21033174034a5e2ea88e
CPU-Threads: 	4; BS: Windows 10.0 Build 18363; UI-Render: Skia/Vulkan; VCL: win
Locale: 	de-DE (de_DE); UI: de-DE
Calc: 	threaded

#### Other information about your system:
---
#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If addons are disabled, is your problem still occuring?
Not tested.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Not tested.

**Comment by leonardder** [comment]
This depends on the symbol level set in NVDA. Its default is set to some. When changing the punctuation/symbol level to most or higher, quotes are read correctly.

**Comment by peterpacult** [comment]
My symbol level is already set to "all". This will read out any formatting
hierarchies in LibreOffice, but it does not say that the text is marked as
a citation.

Am Mo., 28. Sept. 2020 um 14:25 Uhr schrieb Leonard de Ruijter <
notifications@github.com>:

**Comment by feerrenrut** [comment]
I think this issue is about text formatted as a quote, rather than the quote characters themselves?

**Comment by leonardder** [comment]
That makes sense indeed, I'm sorry.

@peterpacult I assume reproting blockquotes is on in the NVDA Formatting settings? IN that case, it's probably another  case of LibreOffice not following the IAccessible2 spec or not implementing this at all, which still required an external fix.

**Comment by peterpacult** [comment]
This issue has also been reported to the Document Foundation; see https://bugs.documentfoundation.org/show_bug.cgi?id=135586

**Comment by peterpacult** [comment]
Hello Leonard,

yes, the blockquotes are enabled in NVDA under "Options" -> "Settings" ->
"Document formatting"; so it seems that - as Reef correctly pointed out -
the blockquotes are not recognized as such by NVDA.

Am Di., 6. Okt. 2020 um 15:26 Uhr schrieb Leonard de Ruijter <
notifications@github.com>:

**Comment by michaelweghorn** [comment]
With the current LibreOffice development version (to become LibreOffice 24.2 next year), LibreOffice now reports the IA2_ROLE_BLOCK_QUOTE role for paragraphs using the "Block Quotation" paragraph style and NVDA announces the block quote as expected.
See https://bugs.documentfoundation.org/show_bug.cgi?id=135586 and the commits mentioned in there for more details.

I think this issue can therefore be closed.

**Comment by Adriani90** [comment]
Thanks for the update, closing as fixed.
