### ISSUE TITLE
Emoji panel can't be closed if NVDA automatically enters focus mode

### ISSUE THREAD

**Issue by nidza07** [nvaccess/nvda#11708]
### Steps to reproduce:
1. Open a website with some edit boxes, for example Gmail's message composition screen.
2. Press enter on the message body, which will cause NVDA to enter focus mode.
3. Write some text, and open the emoji panel with Windows plus period to insert an Emoji.
4. Press escape to close the panel
### Actual behavior:
NVDA doesn't let the key through and instead using escape, switches back to the browse mode
### Expected behavior:
If the emoji panel is open, the first press of escape should close it. If escape is pressed again, NVDA should switch to browse mode.

### Possible workaround
Two workarounds are to first focus the edit field and press NVDA plus space manually to enable the focus mode instead of enter, which will make it so that escape doesn't go to browse mode. Another is to press NVDA  plus F2 to pass the key through and then escape to close the panel. Still, I don't think these are very obvious to new users at first.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Should not matter much, but I can reproduce it on alpha-21082,dc0582eb
#### Windows version:
Windows 10 2004
#### Name and version of other software in use when reproducing the issue:
Google chrome version 85.0
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by XLTechie** [comment]
For what it's worth, I can not replicate this in latest Firefox and Brave using the following code in the addressbar:

```
data:text/html,<p><a href="test link">test link</a><br><form><input type='text' name='test'></form></p>
```

Tabbing to the text field so that focus mode activates when I get there, and entering a couple emoji: when I press escape, I am still in focus mode.
Tested with 2019.3, and recent alphas including today's.

What happens if you test using the above code?

**Comment by nidza07** [comment]
@XLTechie I see. I performed some more tests and it turns out that indeed, if you use the US keyboard layout, everything works as expected. The issue occurs when you switch your keyboard layout, in my case Serbian  latin. However, since the emoji panel isn't officially available on non US layouts and is enabled through a registry tweak, that probably explains why it doesn't work as intended.
