### ISSUE TITLE
Microsoft Teams crashes when moving through channels in a team

### ISSUE THREAD

**Issue by pleveris** [nvaccess/nvda#11712]
### Steps to reproduce:

1. Open Microsoft Teams desktop app.
2. Open an existing team.
3. Press tab (or take any other navigation actions such as arrow keys if in Browse mode) to find a llist of available channels in the selected team, like "General Channel". NVDA should switch to Focus mode where you could change channels using arrow keys.
4. Suppose you want to change the channel from the currently selected, so you are pressing up or down arrow keys (it's no matter).

### Actual behavior:
After pressing arrow keys two times (sometimes it happends when even nothing is pressed), MS Teams completely crashes, NVDA lags for a certain moment, and when Teams app is closed, NVDA usually goes to Desktop. Sometimes Teams application reopens itself (and sometimes not), and a Windows notification pops up with a message from Teams saying: "There was a glitch, and we had to restart the app. It's good to go now."  When Teams is newly launched, it staies in the same channel it was at previous time (which means, no change was successful from the user side). Trying to change the channel again, the same situation happends. (More info may be available in the error log.) Notes: 1) cannot reproduce this issue when running Teams in Chrome browser (without using Desktop app); 2) it's not possible to reproduce this issue when running latest version of JAWS or Narrator, so I assume it's an NVDA problem.

### Expected behavior:
User should be able to change team channels successfully, without any restrictions.

**Comment by feerrenrut** [comment]
If you can, it would be worth testing this with the recent beta of NVDA: https://www.nvaccess.org/post/nvda-2020-3beta4/ 

Several similar issues to this have been fixed, and debug logging has been added to help identify the cause of issues like this.

**Comment by pleveris** [comment]
Hello,
Just tried with the latest beta of NVDA; however, no changes - the
same situation happends. The updated log is here:
https://www.paulev.eu/files/nvda_log-updated.txt
Thanks.

**Comment by feerrenrut** [comment]
hmm, unfortunately this log doesn't tell us much. It seems NVDA didn't even freeze while teams crashes/exits. This indicates to me that it is a problem internal to teams. Have you contacted teams support/raised an issue with them?

**Comment by pleveris** [comment]
Hello,
I have contacted Microsoft Tech Support about this issue; However,
they have pointed out that if it doesn't happen using Narrrator, it is
likely not an issue with the Teams application itself. To add, JAWS
also does not have this problem.

Best regards,
Paulius

**Comment by michaelDCurran** [comment]
If you have not tried this already:
* With NVDA running, in Teams go to the treeview where you can move up down the channels.
* Open the NVDA Python console with NVDA+control+z.
* Type into the NVDA Python console the following line and press enter:
 ```
 nav.appModule.dumpOnCrash()
 ```
 Note the path to the dmp file that is output to the Python console.
* Back in Teams, move up and down the channels until Teams crashes.
* If the dmp file now exists at the path printed in the console, please attach it to this issue.

Thanks.

**Comment by pleveris** [comment]
Hello,
The thing is, as I understand, the NVDA crash dumps are only generated
if NVDA application crashes itself (or according to the other app).
However in this situation only Teams app crashes, this doesn't affect
NVDA at all. I mean, when Teams crashes, it certainly closes and opens
up again, with the notification saying about Teams Glitch... NVDA
remanes at its own state (actually, there is no need to restart it);
so I think NVDA itself does not experience crashing. If I understand
correctly, that's the reason why NVDA crash dump file is not generated
after the Teams crash. (By the way, here I could be wrong though).
Thanks.

**Comment by michaelDCurran** [comment]
The instructions I provided cause NVDA to instruct Teams to create a 
dump file on crashing where possible. NVDA does this by inserting a 
crash handler in Teams itself.


However, at the end of the day, if it is Teams crashing and not NVDA, it 
is more than likely a Teams issue rather than an NVDA issue, even if 
Teams does not crash with narrator or Jaws, this just means that those 
ATs are not hitting the thing that happens to make Teams crash. But with 
out being able to get a crash dump from teams, or debug teams itself, 
there is not really any more we can do here.

**Comment by seanbudd** [comment]
Hi @pleveris,

Have you been able to collect a crash dump of MS Teams? You can find steps to do this [here](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps#minidumps-for-other-applications).

Can you still reproduce this with the latest teams and NVDA?

**Comment by seanbudd** [comment]
Closing as stale and possibly fixed by teams
