### ISSUE TITLE
Navigating by word in Chrome results in word getting read twice when followed by punctuation

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11727]
### Steps to reproduce:

1. Move to an edit field in Chrome (Google search for instance).
2. Press NVDA+P to ensure Symbol level is set to all (just to ensure all punctuation is read)
3. Type text with punctuation:
The cat, dog, and bird are hungry.
4. Press HOME to move to the start of the text.
5. Press CONTROL+RIGHT ARROW to move by word.

### Actual behavior:

NVDA reads "The cat comma cat comma dog comma dog comma and bird are hungry dot hungry dot"

### Expected behavior:

NVDA should only read each word and punctuation symbol once while navigating by word.

#### NVDA version:

NVDA 2020.3 beta 4 installed
NVDA 2020.2 portable

#### Windows version:

Windows 10 (64-bit) Version: 1903 Build 18362

#### Name and version of other software in use when reproducing the issue:
 
Firefox Version: 
81.0 
 
Chrome Version: 
85.0.4183.121 

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes, as noted.

#### If addons are disabled, is your problem still occuring?

No add-ons installed

**Comment by Adriani90** [comment]
cc: @JulienCochuyt, @ObjectInSpace

**Comment by Qchristensen** [comment]
Follow up from user noting this also affects current Edge as well.

**Comment by ObjectInSpace** [comment]
I'm not able to reproduce this currently. Tried several fields and NVDA said "the cat comma dog" etc. Nothing repeated. Is this still occurring for others?

**Comment by Qchristensen** [comment]
Confirming I can no longer reproduce this in Windows 10 (64-bit) Version: 2004, Build: 19041 with Edge or with Chrome Version: 87.0.4280.88  and NVDA 2020.3.

Closing as WorksForMe.
