### ISSUE TITLE
Emulated system keyboard keys: unable to remove emulations without expanding entry

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#11731]
STR:
1. Open input gestures to emulated system keyboard keys category.
2. Add a gesture to emulate. In my case, I tried the Mute key.
3. Add a gesture to the emulation.
Desired behaviour: When going back to the emulation item (e.g. Emulate key press: NVDA+J) the user should be able to remove the emulated keyboard entry without deleting the gestures assigned to it. Removing multiple entries is time-consuming.

NVDA version: NVDA 2020.3beta4.

**Comment by CyrilleB79** [comment]
For reference, this was discussed in https://github.com/nvaccess/nvda/pull/11402#issuecomment-664448667.

@feerenrut clearly wanted to first merge #11402 that contains a big amount of work.
> > 3. Enable remove button even when the emulated key has associated gestures:
> I wont do this now. I don't think it would be common to have many gestures mapped to a single emulated gesture, and I don't want to go down the rabbit hole on the UX for removing these items. I think what we have now is acceptable.

**Comment by fisher729** [comment]
Hi. This issue has been resolved. Therefore, I'm closing the ticket.
