### ISSUE TITLE
Modifiers get stuck while using KeePass

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#11744]
### Steps to reproduce:
1. Put KeePass on desktop 2, and focus the list.
2. From desktop 1, press ctrl+win+right.
3. Press ctrl+c.
4. Switch back to desktop 1.
5. Press NVDA+1 to turn on keyboard help.
### Actual behavior:
I get a 1 put into my document.
To recover, I have to press ctrl, alt, win and shift until things work again.
### Expected behavior:
Keyboard help turns on.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Version: 2020.3beta4
#### Windows version:
Version 1909 (OS Build 18363.1082)
#### Name and version of other software in use when reproducing the issue:
KeePass 2.46
#### Does the issue still occur after restarting your computer?
Yes
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

[log.txt](https://github.com/nvaccess/nvda/files/5358292/log.txt)

**Comment by DrSooom** [comment]
CC: @michaelDCurran

**Comment by Adriani90** [comment]
@tspivey are you still having this issue with NVDA 2024.2?

**Comment by tspivey** [comment]
I haven't seen this issue in a while, and I can't reproduce it with 2024.2.
