### ISSUE TITLE
Using English US computer Braille crashes NVDA when reading URLs

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11754]
### Steps to reproduce:

1) Set NVDA's output Braille table to use English (US) grade 2.
2) Ensure "Expand to computer Braille for the word at the cursor" is enabled.
3) Use a connected Braille display OR the Braille viewer from NVDA's tools menu.
4) Open Notepad.
5) Type text including a URL, eg:
NV Access https://www.nvaccess.org/
6) Press control+right arrow twice to the URL.
7) Press LEFT ARROW to the end of the word then right arrow to the URL.

### Actual behavior:
NVDA stops responding at step 7.

### Expected behavior:

NVDA should read the URL and keep working normally.

#### NVDA version:

NVDA 2019.3.1
NVDA 2020.1 portable
NVDA 2020.2 portable
NVDA 2020.3rc1 installed
(I couldn't test any earlier as I don't have a Braille display handy and the Braille viewer was introduced in 2019.3).

Note that:
NVDA 2019.3 used LibLouis commit 58d67e63
NVDA 2020.1 used LibLouis 3.1.2
NVDA 2020.2 and newer use LibLouis 3.1.4
#### Windows version:

Windows 10 (64-bit) Version: 1903 Build 18362

#### Name and version of other software in use when reproducing the issue:

Notepad, but reporting user advised it happens in other programs as well.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
As above

#### If addons are disabled, is your problem still occuring?
Yes

**Comment by Adriani90** [comment]
Closing as fixed in #11888
