### ISSUE TITLE
Allow linting without Visual studio installed

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#11774]
### Steps to reproduce:

On a machine with no installation of Visual Studio, run:
`scons lint base=origin/master`

### Actual behavior:
Linting report generation fail due to Visual Studio missing.

### Expected behavior:
Linting report is generated.
If I am not mistaken, VS should not be required for this task 

### Context

I am often working on a machine where VS is not installed. If I want to suggest a PR with minimal changes, I do not need to re-compile source and can work locally with a copy of NVDA source compiled on another computer. However, for now, I cannot check linting before suggesting the PR.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.3

#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
N/A

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. Same issue with other version (e.g. 2020.2)
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by leonardder** [comment]
Interesting idea. I'd suggest taking this issue a bit broader. Currently, our SCons environment is getting pretty big and complex, and lots of loading and checks take place (such as Visual Studio version checking) without actually needing them at that particular moment.

**Comment by feerrenrut** [comment]
Yes, I think some time could be put into optimizing the build dependencies and ordering. It may also be worth reconsidering the build system choice, something like cmake would be faster and [integrates better with visual studio](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019).

**Comment by leonardder** [comment]
I've also seen CMake doing a pretty good job with VS Code, indeed.

**Comment by lukaszgo1** [comment]
I've briefly discussed something similar with @feerrenrut in #11108. I still believe that using SCons for lint, system and unit testing is overkill. We should be able to rewrite these in pure Python and run them passing appropriate parameters to scons.py. It would not only allow us to launnch these tests on AppVeyor in the same way in which developers are running them on their machines but would also provide significant speed improvements as SCons is pretty slow to initialize.

**Comment by lukaszgo1** [comment]
@CyrilleB79 If I'm not mistaken after #12075 Visual Studio is not necessary any longer for linting. Would you be able to confirm and assuming that this issue is fixed for you close it?

**Comment by CyrilleB79** [comment]
Correct: #12075 is fixing this issue and I am already running the `runlint.bat` script on a computer without Visual Studio.
Thanks @lukaszgo1 for pointing this; I had forgotten that I had opened this issue.

One additional question:
Since you also mention unit and system tests in https://github.com/nvaccess/nvda/issues/11774#issuecomment-727650474. What is the status now? Is Visual Studio still mandatory or not to execute them?

**Comment by lukaszgo1** [comment]
No, both unit and system tests can be executed without VS installed assuming that the virtual env has been created on a machine with Visual Studio.
