### ISSUE TITLE
OCR image-based pdfs directly like Jaws does

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#11785]
Add the ability for NVDA to OCR inaccessible pdf files and other images directly like Jaws does, and show the results in a browse-mode buffer like Jaws. Also add the ability for NVDA to recognize that the pdf that was loaded is an inaccessible image-based pdf and bring up a dialog box asking if you want to recognize it with OCR and maybe even with NVDA's AI neural engine for both OCR, image descriptions and screen recognition and show the results in an easy to read browse mode buffer.

**Comment by Brian1Gaff** [comment]
Would this all not need a third party sysystem, or need to be based on 
sending stuff back and forth to a cloud based system so  the gradually built 
up learning would be  added to by every user. At this point is where I think 
the industry needs to work out a standard api for such third party things 
and allow the various screenreaders to tap into them. It would probably 
eventually become a premium product though to be paid for and at that stage 
the problems of open source and free being used to access chargable services 
needs to be looked at as well.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by joshknnd1982** [comment]
The training may have to be done using a cloud-based system, or maybe somebody with a powerful computer. Or perhaps people could access a server running in the cloud. But the actual process, could probably be done on a computer. Perhaps NVDA could make add-ons or something to experiment with it, and NVDA could use The free and open source python-based tensor flow lite.

**Comment by akash07k** [comment]
Many APIs exist for this purpose like Microsoft's computer vision, 
Google's cloud vision etc.

**Comment by joshknnd1982** [comment]
with voiceover on the iPhone, you just download a training model for image recognition which is about 200 and 200 MB, you download another training model for screen recognition and OCR of controls and such, that's another 50 or so megabytes, then you turn everything on, it works on an app by app basis, so then it will describe images in a human like way, and give you access to many more controls especially in applications where the developer has not provided any accessible information whatsoever. it is so good, that it can recognize and read subtitles and text in videos, it even attempts to describe the video but it only feeds it so far as a series of still images. But at least it gives me an idea of what the video is and the text in the video as it appears on the screen when it appears it is read instantly by the voice over intelligent recognition feature. The recognition feature uses artificial intelligence and the onboard neural engine built-in to the iPhone or iPad. I hope someday that NVDA will also use artificial intelligence and perhaps the power of the GPU in order to more intelligently read the screen

**Comment by feerrenrut** [comment]
Please use the issue template in future. NVDA currently has an OCR feature via Windows in built support. If there are problems with this please describe them in detail in a new issue.

Due to the size of the models, this will likely always need to be implemented as an add-on for NVDA or via web API. Providing access to (paid) 3rd party API's will require an account / login / payment mechanism. It would be a large decision to take NVDA in this direction, and not one we would take lightly.
