### ISSUE TITLE
RealTime Live OCR, control, screen and image recognition using neural engine AI, with special recognition cursor

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#11784]
Could you please add realTime Live OCR, text recognition, image descriptions, and screen recognition which uses an AI neural engine, and a special recognition cursor to NVDA? This would do the same thing as voiceover recognition in IOS14.1. In windows10 apps and legacy windows7/xp apps that are not accessible, NVDA could go directly to the CPU or GPU, and by using neural engine AI technology and matrices, identify text, describe inaccessible images, read text and possible text in images, identify buttons and other inaccessible controls and present them as accessible controls to NVDA when the NVDA recognition cursor is active... Let you act on, activate, and interact with such controls, and by using its intelligent AI neural engine features, give meaningful labels with humanlike descriptions, to inaccessible controls. Ability to turn image descriptions, screen recognition, and text recognition on and off individually. Focus an object such as a video area with the NVDA recognition cursor and NVDA's neural engine AI technology would read any text or subtitles in the video, in any web browser or media player application. The NVDA recognition cursor would temporarily turn off the traditional NVDA access methods or maybe combine them with its neural engine like voiceover in IOS14.1 and later in order to intelligently recognize and bring to the surface all kinds of inaccessible text, descriptions of graphics, images, pictures, icons and controls and any possible text in such images, graphics, icons and controls. I strongly encourage NVDA developers to move NVDA in the direction of neural engine AI either processed with the CPU or maybe send neural AI screen reader processing to the GPU instead. thanks.

**Comment by feerrenrut** [comment]
Hi @joshknnd1982 thanks for opening an issue. Currently this issue is far too general and broad to be actionable, and misses the fact that there have been several attempts to provide OCR and image descriptions based on ML. These are certainly ideas we are aware of.

In the future please fill out the issue template correctly. I'm going to close this issue, since it is too general.
