### ISSUE TITLE
Update to Py2exe 0.10.0.2 

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#11794]
### Is your feature request related to a problem? Please describe.
We are currently using a development build of py2exe. Py2exe is now at version 0.10.0.2. @albertosottile improved the product since the build we're using, and it's now on PyPI as well.

### Describe the solution you'd like
I think we should switch to the most recent version, if it were only not to stay behind, making it harder to switch later on.
I'd like to propose changing the approach, namely not to longer use a binary repository but install from pip instead. We do this with Flake8 as well and, unlike dependencies like scons and wx, py2exe isn't a runtime dependency. It will probably require a change of the scons files, though.

### Describe alternatives you've considered
Update the binary repo. Py2exe added a dependency to pefile, which depends on other stuff that even depends on future, pulling in several other dependencies that will bloat the binary repo. I'm not sure whether we're on the right track with binary repos this way, as we'll also have to consider licenses here.

**Comment by josephsl** [comment]
Hi, resolution required to move to Python 3.8/3.9. Thanks.

**Comment by feerrenrut** [comment]
@josephsl I have added the Python 3.8 label. For future issues like this could you do the same?

**Comment by josephsl** [comment]
Hi, will do – or better yet, it would be better to put this inside a Python 3.8 or 3.9 project like we did in 2019. Thanks for the reminder for everyone.
