### ISSUE TITLE
NVDA says "unknown" for tree view items in some CHM files

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#11797]
### Steps to reproduce:
1. Install the latest alpha version of NVDA.
2. Open a CHM file from programs like JAWS or TortoiseSVN.
3. If the focus is not in the "Table of contents" tree view when you open the CHM file, move it there (e.g. with F6).
4. Use the arrow keys to navigate between the tree view items of the table of contents.
5. Observe how NVDA says "unknown" for each tree view item, instead of reading its name.

### Actual behavior:
NVDA says "unknown" for each tree view item, instead of reading its name.

### Expected behavior:
NVDA should read the item's name, as it does in v2020.3 and earlier versions.

### System configuration
- Operating system: Windows 10 Pro version 20H2 (build 19042.572), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-21274,71c2c419, installed, in bulgarian.
- HTML Help: version 10.0.19041.561.
- Processor: Intel Core i5-9400F at 2.90GHz.
- RAM Memory: 16.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC892 at Intel Cannon Point PCH.

#### Does the issue still occur after restarting your computer?
Yes, it does.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
With NVDA 2020.3 the issue does not occur.

#### If addons are disabled, is your problem still occurring?
Yes, it does

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No, I haven't. But based on the fact that the issue does not occur with other/older versions of NVDA, the cause should not be in unregistered libraries.

### Notes:
"HTML Help" (hh.exe) is the application which apparently is the viewer for CHM files (or at least for some of them).

**Comment by Adriani90** [comment]
Just to exclude that the COM registration fixing tool improves this, could you still try to run it and see if it changes anything?

cc:@michaelDCurran

**Comment by k-kolev1985** [comment]
@Adriani90 I just run the COM registration fixing tool and restarted the computer after that just in case. But it did not help. I think the fix for SysListView64 is causing this, but I might be wrong.
