### ISSUE TITLE
Conflicts with emulated keys and entering braille on HIMS devices

### ISSUE THREAD

**Issue by chojiro** [nvaccess/nvda#11806]
When you connect in my case BrailleSense U2, U2 Mini, Polaris and Polaris Mini, certain combinations on the display will emulate system keys. When you specifically turn off the emulation of F3 in NVDA-menu>Settings>Input gestures by removing it, you also have to assign it to the Braille category under "Inputs braille dots via the braille keyboard", since it doesn't automatically use dot 1248 for input via the braille keyboard after it has been removed. Seems to happen regardless of input table so far as I can determine.

### Steps to reproduce:
1. When plugging in either of the displays mentioned above, pressing dots 1248 will emulate system keys F3.
2. Going to NVDA-menu>Settings>Input gestures under "Emulated system keyboard keys", move down to F3 and remove it by expanding it with the right arrow, going down to dot+1+2+4+8 and pressing Alt+R.
3. In the treeview, move up to the "Braille" category.
4. Expand it, then go down to "Input braille dots via the braille keyboard" and press Alt+A.
5. Press Dots 1+2+4+8, then when the context menu appears, down arrow to "HIMS Braille Sense/Braille EDGE/Smart Beetle/Sync Braille series" and press enter.

### Actual behavior:
NVDA uses dots 1+2+4+8 as an emulated system key, even though in some tables, that actually enters braille like a number, making it unusable until it is removed.
### Expected behavior:
I'd honestly expect this to be a lot more intuitive. Instead of having to manually go and change input gestures, I'd prefer a nice checkbox in the Braille settings that either turns it on or off. Once it's off, it should be smart enough to figure out I probably want to use it for braille input instead of just assigning it to nothing. This way, you can either disable it completely or just for specific keys using Input Gestures as normal. There shouldn't be this much work just to fix this. Most people having this problem aren't going to do that, certainly not anyone I know. It feels very counterintuitive.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.3
#### Windows version:
Windows 10 2004 (64-bit) build 19041.572
#### Does the issue still occur after restarting your computer?
Yes

**Comment by lukaszgo1** [comment]
Hi @chojiro. I agree that this behaviour is quite confusing but that is  just because this assignment for HIMS displays was a mistake in the first place. I've reassigned F3 key for these displays to Space+dots 148.  in NVDA 2020.4. Would that change address your concerns?

**Comment by chojiro** [comment]
Hello,

 

Yes. Thank you. That should do the trick.

 

Fra: Łukasz Golonka <notifications@github.com> 
Sendt: 15. november 2020 23:13
Til: nvaccess/nvda <nvda@noreply.github.com>
Cc: chojiro <chojiro1990@gmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [nvaccess/nvda] Conflicts with emulated keys and entering braille on HIMS devices (#11806)

 

Hi @chojiro <https://github.com/chojiro> . I agree that this behaviour is quite confusing but that is just because this assignment for HIMS displays was a mistake in the first place. I've reassigned F3 key for these displays to Space+dots 148. in NVDA 2020.4. Would that change address your concerns?

**Comment by lukaszgo1** [comment]
@chojiro If you consider this issue fixed please close it.
