### ISSUE TITLE
Add ability to reset speech dictionaries to factory default

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11802]
### Is your feature request related to a problem? Please describe.

If entries are made in the default or voice speech dictionaries, the only way to reset these is to go back in and delete them manually (or editing the file in NVDA's appdata).

To reset these to "factory defaults", you need to go in and remove all entries.

### Describe the solution you'd like

Although removing all dictionary entries is easier than reverting all changes to the symbol pronunciation dialog manually, it would still be useful to have a button to either "Reset to factory defaults" or "Remove all" (which are basically the same thing).

The input gestures dialog has a "Reset to factory defaults" button, and issue #3762 proposes the ability to reset symbol pronunciation to defaults, so I have written this issue up to propose consistency across the three features.

Additionally I would propose that when implementing #6648, the dialog (confirming resetting NVDA to factory defaults) could offer the ability to also reset speech dictionaries (and punctuation / symbol pronunciation and gestures).

### Describe alternatives you've considered

Currently it is psosible to delete all entries manually, however this could need to be done for each voice and the default dictionary.  This issue also proposes a consistent approach to resetting speech dictionaries, punctuation / symbol pronunciation and gestures.

**Comment by Adriani90** [comment]
cc: @JulienCochuyt

**Comment by JulienCochuyt** [comment]
Interestingly, the "Remove" button (removing a single entry) was historically designed to handle the removal of all the selected entries in a multi-selection list control. This idea seems to have been abandoned as the list control is explicitly set to support only a single selection - presumably for easier user interaction.
