### ISSUE TITLE
When requesting formatting info, "baseline" should not be reported

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#11815]
### Steps to reproduce:

On a webpage (e.g. this GitHub page), press NVDA+F one ore two times.

### Actual behavior:
"Baseline" is reported in the formatting information.

### Expected behavior:
"Baseline" should not be reported when fetching formatting info with NVDA+F, since this is the default formatting regarding text position (superscript, subscript, baseline).
Indeed, in this case, we already do not report "Not bold" or "Not underlined" since this is considered the default formatting.
"Baseline" formatting should just be reported when "Superscript and subscript" formatting option is enabled and when you arrow from a superscript or subscript to a baseline text.

### Note
This issue occurs on Firefox, but also in IE (also in Edge if I remember well).
But not in MS Word (legacy), nor in Wordpad (and neither in Chrome if I remember well)

### !technical

According to the application / control type, the "text-info" attribute that is provided to speech.getFormatFieldSpeech may be "auto", "baselin", "middle"; in this case, "Baseline" is reported. Or no "text-position" attribute is provided at all; in this case, "Baseline" is not reported when pressing NVDA+F.

#### NVDA installed/portable/running from source:
all
#### NVDA version:
2020.3
#### Windows version:
10

#### Name and version of other software in use when reproducing the issue:
Mozilla Firefox 82.0.2 (64 bits)
But the issue also in other apps.

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2019.3.1 and 2019.1.1 show the same issue.
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by Adriani90** [comment]
Cc: @feerrenrut

**Comment by feerrenrut** [comment]
This looks fine, I'm happy for someone to work on this.

**Comment by CyrilleB79** [comment]
Yes, I have already a try branch.
I still have to perform checks / cleanup. I will come with a PR for this issue this week.
