### ISSUE TITLE
NVDA does not recognise a div whose role is "checkbox" if that div has no content

### ISSUE THREAD

**Issue by brhallin** [nvaccess/nvda#11810]
### Steps to reproduce:
* Create a `<div>` on an HTML document and assign it `role="checkbox"` and `aria-checked="true"`;
* Make sure it is empty, e.g. `<div role="checkbox" aria-checked="true"></div>`;
* Attempt to navigate to that element using the X shortcut key.

**Note:** providing a label, e.g. `aria-label="Apples"`, makes no difference.

Here is a link to a JSFiddle where this issue reproduces: [https://jsfiddle.net/q7rejkfp/2/show](https://jsfiddle.net/q7rejkfp/2/show).

### Actual behavior:
* NVDA announces "no next checkbox";

### Expected behavior:
* NVDA announces "checkbox checked".

#### NVDA installed/portable/running from source:
Portable.

#### NVDA version:
NVDA 2020.3.

#### Windows version:
Windows 10 (build 19042.572).

#### Name and version of other software in use when reproducing the issue:
Edge Chromium 86.0.622.63 (the current version as of this submission).

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If addons are disabled, is your problem still occuring?
Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No.

**Comment by feerrenrut** [comment]
Hi @brhallin thanks for raising an issue, and welcome to the NVDA project.

I think this is an authoring error. The check boxes are not visible, typically invisible elements don't provide semantic information (EG hidden form fields used to include certain extra information on submit) 

Guessing a little about the intent here, a common use case is making the content an image / icon and making it hidden, which reads as you expect:
``` html
        <div role="checkbox" aria-checked="true" aria-label="Oranges">
          <span aria-hidden="true"><img src="https://picsum.photos/20"></span>
        </div>
```

I'm going to close this issue, happy to review if there is further information added.

**Comment by brhallin** [comment]
I can easily make the element "visible" by adding CSS `width`, `height`, and a background image, or `:before` or `:after` psuedoclasses. I'd argue that unless I've deliberately hidden them via CSS (e.g. `display: none`), the screen reader should consider them as valid elements.
