### ISSUE TITLE
NVDA and Chrome seem not to support aria-owns and grids when grid rows are not nested within grid

### ISSUE THREAD

**Issue by ewolfman** [nvaccess/nvda#11811]
Hi,

Long ago in our aging app I was using aria-owns, NVDA and Chrome to read several DIVs as a grid.
(The reason for using aria-owns is that our website has a DOM structure were the grid header is separated from the grid rows.)

This solution was working quite well on Chrome and to some extent in Firefox. It was even reading out nested grids in Chrome.
Coming back to this today, unforunately it seems that via Chrome it no longer works.

### Steps to reproduce:
Here is a short demo to reproduce. A DIV-based grid with aria-owns, where the grid rows are **not** inside the grid:
```
<div role="grid" aria-owns="row1 row2">
</div>

<div id="row1" role="row"><div role="gridcell">apple</div><div role="gridcell">banana</div></div>                
<div id="row2" role="row"><div role="gridcell">dog</div><div role="gridcell">cat</div></div>  
```     

See here on [codepen](https://codepen.io/wolfmanjack/pen/YzWjdNY).

### Actual behavior:
In **Firefox** (82.0.2 64bit): NVDA reads this as table and allows table navigation.
Speech viewer shows: "_frame    table  with 2 rows and 2 columns  row 1  column 1  apple_" and NVDA allows navigation.

In **Chrome** (86.0.4240.183 Official Build 64-bit): NVDA reads this as table and allows table navigation.
Speech viewer shows: "_frame    table  with 0 rows and 0 columns  apple_"

### Expected behavior:
NDA when using Chrome should support aria-owns and grids, when grid rows are external to the grid DOM. Just like Firefox does if not better.

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2020.3

#### Windows version:
Windows 10 ver 1909 

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2019.1.1 - same behavior

#### If addons are disabled, is your problem still occuring?
Fresh install. AFAIK I did not install add-ons.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No, I don't think this is related

**Comment by ewolfman** [comment]
This is just to update that on Chrome 70 this works

**Comment by Adriani90** [comment]
cc: @aleventhal, @ObjectInSpace

**Comment by ewolfman** [comment]
reported here: https://bugs.chromium.org/p/chromium/issues/detail?id=1150481

**Comment by Adriani90** [comment]
@ewolfman the chromium bug has been fixed on their side. Do you still encounter this issue with NVDA?

**Comment by ewolfman** [comment]
I tested the codepen I wrote above and it looks working. Thanks for the followup.
