### ISSUE TITLE
Microsoft Teams: Menu focused when trying to read a message

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#11821]
### Steps to reproduce:
1. Install most recent Teams
2. Focus an incoming message in a chat or team channel.

### Actual behavior:
NVDA reads the incoming message.

### Expected behavior:
NVDA starts reading the incoming message, but this is suppressed by a menu getting focus. This is the menu that allows you to pick a reaction for a message (e.g. like). A focus triggers this menu. It doesn't strictly gain focus, however NVDA"s handling of the menuStart event redirects focus to it.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-21324

#### Windows version:
Windows 10 20H2

#### Name and version of other software in use when reproducing the issue:
Microsoft Teams 1.3.00.28779
Builds like 1.3.00.26xxx don't suffer from this.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
N/a

**Comment by leonardder** [comment]
Relevant logging:

```
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (09:52:40.166) - MainThread (15784):
Hook received winEvent: EVENT_OBJECT_SHOW, window 1967980 (Chrome_RenderWidgetHostHWND), objectID OBJID_CLIENT, childID -59951, process 2296 (teams), thread 19832
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (09:52:40.166) - MainThread (15784):
Adding winEvent to limiter: EVENT_OBJECT_SHOW, window 1967980 (Chrome_RenderWidgetHostHWND), objectID OBJID_CLIENT, childID -59951, process 2296 (teams), thread 19832
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (09:52:40.166) - MainThread (15784):
Hook received winEvent: EVENT_SYSTEM_MENUPOPUPSTART, window 1967980 (Chrome_RenderWidgetHostHWND), objectID OBJID_CLIENT, childID -59951, process 2296 (teams), thread 19832
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (09:52:40.166) - MainThread (15784):
Adding winEvent to limiter: EVENT_SYSTEM_MENUPOPUPSTART, window 1967980 (Chrome_RenderWidgetHostHWND), objectID OBJID_CLIENT, childID -59951, process 2296 (teams), thread 19832
...
DEBUG - IAccessibleHandler.orderedWinEventLimiter.OrderedWinEventLimiter.flushEvents (09:52:40.191) - MainThread (15784):
Emitting winEvent EVENT_OBJECT_SHOW, window 1967980 (Chrome_RenderWidgetHostHWND), objectID OBJID_CLIENT, childID -59951, process 2296 (teams), thread 19832
DEBUG - IAccessibleHandler.orderedWinEventLimiter.OrderedWinEventLimiter.flushEvents (09:52:40.191) - MainThread (15784):
Emitting winEvent EVENT_SYSTEM_MENUPOPUPSTART, window 1967980 (Chrome_RenderWidgetHostHWND), objectID OBJID_CLIENT, childID -59951, process 2296 (teams), thread 19832
...
DEBUG - IAccessibleHandler.processMenuStartWinEvent (09:52:40.192) - MainThread (15784):
Processing menuStart winEvent: window 1967980 (Chrome_RenderWidgetHostHWND), objectID OBJID_CLIENT, childID -59951, process 2296 (teams), validFocus False
DEBUG - IAccessibleHandler.winEventToNVDAEvent (09:52:40.192) - MainThread (15784):
Creating NVDA event from winEvent: EVENT_SYSTEM_MENUPOPUPSTART, window 1967980 (Chrome_RenderWidgetHostHWND), objectID OBJID_CLIENT, childID -59951, process 2296 (teams), use cache True
DEBUG - IAccessibleHandler.winEventToNVDAEvent (09:52:40.192) - MainThread (15784):
winEvent mapped to NVDA event: menuStart
DEBUG - IAccessibleHandler.winEventToNVDAEvent (09:52:40.197) - MainThread (15784):
Successfully created NVDA event menuStart for <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x06458E30> from winEvent EVENT_SYSTEM_MENUPOPUPSTART, window 1967980 (Chrome_RenderWidgetHostHWND), objectID OBJID_CLIENT, childID -59951, process 2296 (teams)
IO - speech.speak (09:52:40.237) - MainThread (15784):
Speaking ['menu', CancellableSpeech (still valid)]
```

**Comment by leonardder** [comment]
Just tested with JAWS, also no issues there. Marking this P2.

**Comment by munawarb** [comment]
@leonardder I just downloaded the latest NVDA (2020.4) and this problem is still there.

It's fixed for the message list, but if you @mention someone and then perform a "say line," NVDA reports "blank." It also continues to remain silent when you press Backspace. The only way to fix it is as before: press Tab to get to the "Send" button, then Shift+Tab to get back to the edit field to continue typing your message.

I've also noticed the ghost menu popping back up when in a call and someone does a screen share. NVDA will announce "menu" and you have to press Tab to get it to focus again on whatever control you were on (like the unmute button.)

So, this issue is not resolved.

**Comment by leonardder** [comment]
I'm afraid for this, either Teams has to fix this properly or we'll have to dive into the core of NVDA with regard to menu popup start events, see https://github.com/nvaccess/nvda/pull/11822#issuecomment-727654478
It's undoable to fix this on a case by case basis as no doubt there'll be a new version of Teams just after a release of NVDA that introduces another incarnation of this issue.

**Comment by gauravahir28** [comment]
Facing this issue again!

**Comment by Yeldece** [comment]
This is still exist.
