### ISSUE TITLE
Alpha 21356 breaks RSS feed reading and history access in Internet Explorer 11

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#11836]
In Internet Explorer 11, one can press Control+ G and Control+H to access RSS feeds and the History tree, respectively. However, NVDA Alpha 21356 generates a semi-crash in Internet Explorer 11 when a feed item or a history item is opened, and IE 11 keeps recovering the tab without ever displaying the HTML content.
### Steps to reproduce:
Having made sure NVDA Alpha 21356 or newer is running, select one of your feed or history items in Internet Explorer 11. That is, after pressing Control+G or Control+H, expand the tree view with the Right arrow and try opening an item from the history or an RSS feed.
### Actual behavior:
NVDA doesn't allow IE 11 to open the item, and the HTML content never gets displayed. IE 11 keeps retrying to access/open the tab as we press Tab or SHIFT+Tab, but the tab stays in a semi-crashed state.
### Expected behavior:
Upon pressing Enter, the HTML content should be display immediately. The last functioning alpha is 21351.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-21356
#### Windows version:
Win 10 Pro 64-Bit, V2009
#### Name and version of other software in use when reproducing the issue:
Internet Explorer V11.00.19041.1
#### Other information about your system:
For the record, the last NVDA Alpha which functions as expected is 21351. The issue starts with 21356, and all alphas after that exhibit the problem
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes -- the last functioning alpha is 21351.
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by Andre9642** [comment]
Related to #11834

**Comment by lukaszgo1** [comment]
@amirsol81 How is this with  latest Alpha?

**Comment by amirsol81** [comment]
@lukaszgo1 I just installed the latest alpha, and it exhibits no issues affecting those problematic areas.
