### ISSUE TITLE
errors occuring when trying to navigate with the review cursor in the uwp apps

### ISSUE THREAD

**Issue by fatihyuksek1** [nvaccess/nvda#11830]
### Steps to reproduce:
1. Wait for several hours. NVDA should stay open for a long amount of time
2. Enter into an uwp app, for example microsoft news
3. Try to navigate inside of the app with the virtual cursor
4. You will notice that NVDA will say nothing while navigating to the previous or next objects in the screen
### Actual behavior:
NVDA doesn't say anything when trying to move to the next or the previous objects with the review cursor
### Expected behavior:
NVDA should report the objects in the app
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.3
#### Windows version:
windows 10 build 1909
#### Name and version of other software in use when reproducing the issue:
Microsoft news
#### Does the issue still occur after restarting your computer?
no
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no
[nvda.log](https://github.com/nvaccess/nvda/files/5523606/nvda.log)

**Comment by josephsl** [comment]
Hi, the fact that Application Frame Host is shown indicates that the app was suspended, and if so, this explains why navigator object commands were not working. Thanks.

**Comment by fatihyuksek1** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 70.85pt 70.85pt 70.85pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by josephsl** [comment]
Hi,

Have you tried interacting the News app after pressing Tab to wake the app?

Thanks.

**Comment by fatihyuksek1** [comment]
I tried and it was working normally.Ps: This can occasionally happen with any uwp app, not just the news app. I came across this in the settings app or other uwp apps as well Windows 10 için Posta ile gönderildi Kimden: Joseph LeeGönderilme: 11 Kasım 2020 Çarşamba 20:40Kime: nvaccess/nvdaBilgi: fatihyuksek1; AuthorKonu: Re: [nvaccess/nvda] errors occuring when trying to navigate with the review cursor in the uwp apps (#11830) Hi,Have you tried interacting the News app after pressing Tab to wake the app?Thanks.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by josephsl** [comment]
I see. @MichaelDCurran, I strongly suspect that this might be a COM timeout issue due to app execution events (apps being suspended and such). Thanks.

**Comment by fatihyuksek1** [comment]
I also noticed that while this bug happens, NVDA also does not announce the toast notifications from the system automatically and it does not announce the messages in Microsoft edge like loading page, load complete and incoming notifications from the notifications bar are not announced automatically, for example when a download starts or is completed

**Comment by Adriani90** [comment]
@fatihyuksek1 can you please test with the last alpha version of NVDA? is this issue still occuring?

You can download the last alpha t this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by fatihyuksek1** [comment]
I guess this issue must have been fixed with the latest version, because I didn't notice it for a long long time.
