### ISSUE TITLE
Unable to copy text from MS Word virtual buffer

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#11839]
### Steps to reproduce:
* Open MS word
* write some text
* Press ctrl+space to review the text or to use quick nav keys
* select some text
* press ctrl+c to copy the selected text

### Actual behavior:

The selected text is not copied to clipboard and the following error is logged:
```
ERROR - scriptHandler.executeScript (12:13:52.772) - MainThread (308):
error executing script: <bound method CursorManager.script_copyToClipboard of <NVDAObjects.window.winword.WordDocumentTreeInterceptor object at 0x06ABA230>> with gesture 'contrôle+c'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "cursorManager.pyc", line 409, in script_copyToClipboard
  File "treeInterceptorHandler.pyc", line 193, in copyToClipboard
TypeError: copyToClipboard() takes 1 positional argument but 2 were given
```

### Expected behavior:

The text is copied without error.

#### NVDA installed/portable/running from source:
Temporary copy.
#### NVDA version:
Last alpha snapshot.
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
N/A
#### Does the issue still occur after restarting your computer?
Not tested.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. 2020.3 is OK.
#### If addons are disabled, is your problem still occuring?
Not tested
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

### Note

Issue very propably introduced by PR #9843.
cc @JulienCochuyt

**Comment by Adriani90** [comment]
Oops I have reported this just now also on #9843, I saw this one too lage...
