### ISSUE TITLE
NVDA speech is not cancelling on dynamic focus change

### ISSUE THREAD

**Issue by ramchaitanyap** [nvaccess/nvda#11840]
### Steps to reproduce: 
 Open [link](https://codepen.io/reefturner/pen/oNLVQpo?editors=1010) and press 'do focus changes button'

### Actual behavior:
Speech should be cancelled/interrupted on focus change.

### Expected behavior:
Speech is not cancelled/interrupted on focus change.

**Comment by Adriani90** [comment]
I agree this should be investigated, actually in this case, when pressing the do focus change button, it kind of simulates a press and hold down of a shift+tab key. in this case, the focus changes very fast from one element to the other, but NVDA still pronounces the whole focused element without considering the speed of focus movement which contradicts the actual press and hold behavior.

**Comment by Adriani90** [comment]
Thanks Jamie for the info, in this case I think it is reason enough to close this issue as won't fix.
