### ISSUE TITLE
Difficulties mooving between historic field and typing field in Windows Live Messenger 2011

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1185]
**Reported by ManuelRamos on 2010-11-06 16:15**
Normally to moove between typing and historic field we can press f6 key.

However, using latest snapshot with WLM 2011, it is happening that when in a conversation, often we cannnot moove with f6 key that is not performing correctly. Explaining, after I'm sending a message, I can not use f6 key, it seems that key is blocked. Moovement is only possible if interlocutor answers and after receiving answer.

ositive aspect is that automtically reading message is functioning properly, unless there are many users online, situation described in previous ticket.

**Comment by dkager** [comment]
Windows Live Messenger has been discontinued. Also, it's not really an NVDA issue. Closing.
