### ISSUE TITLE
Support for FL-Studio

### ISSUE THREAD

**Issue by FDX-VQ** [nvaccess/nvda#11859]
### Additional context
NVDA should fully support the app FL-Studio. There should also be shortcuts to ease the usability.

**Comment by leonardder** [comment]
It would help to know what's currently going wrong in this application.

**Comment by OzancanKaratas** [comment]
FL Studio does not use any accessibility APIs. NVDA cannot support applications that do not use an accessibility API. Please consult Image Line Software. If FL Studio is now more accessible, please let us know more.

**Comment by OzancanKaratas** [comment]
This issue should be closed, because the mentioned program runs as I said in my previous comment.

**Comment by leonardder** [comment]
I'd first like to have some more information about the program. What is it supposed to do? How do you know that it doesn't implement any accessibility support?

**Comment by OzancanKaratas** [comment]
First of all, many texts is usually in the graphics. It not uses UIA or IAccessible2. User cannot navigate with the Tab key, because “Unknown” is heard on every Tab hit.

**Comment by leonardder** [comment]
What happens if you use screen review in the application? Also, could 
you provide developer info about these objects?

**Comment by OzancanKaratas** [comment]
Screen review acts as if the screen is blank. Like in the Windows 10 Settings app. FL Studio is written in Delphi. What do you want to know?

**Comment by leonardder** [comment]
Interesting, as Delphi apps tend to be inaccessible but expose stuff with screen review.
Anyway, we'll close this for now.
