### ISSUE TITLE
PowerPoint emprovements

### ISSUE THREAD

**Issue by FDX-VQ** [nvaccess/nvda#11850]
### Describe alternatiPleas disable the aotomatic scrolling of NVDA within the presentation mode in Powerpoint.**

**Comment by FDX-VQ** [comment]
One should move with the errow up and errow down between the text blocks on the slide.

**Comment by leonardder** [comment]
@FDX-VQ: Please read the information [here](https://github.com/nvaccess/nvda/wiki/Github-issue-template-explanation-and-examples) before filing any additional issues. Closing as invalid.
