### ISSUE TITLE
nvda is not reading the result of the accounts in the windows calculator history

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#11858]
### Steps to reproduce:
open windows calculator
do at least two operations
walk with tabe until nvda advertise
list, list item
walk with the arrows below and sign up and see that nvda advertises only list item.
### Actual behavior:
nvda announces only list item
### Expected behavior:

the nvda must announce the realized accounts as well as the result of the account.
this is a regression, I remember using this feature a long time ago and everything worked fine.
the regression can be from nvda or windows
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-21386,53cecfd7

#### Windows version:
windows 10 19042.630
#### Name and version of other software in use when reproducing the issue:
Calculator.exe, Microsoft.WindowsCalculator 10.2009.4.0

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by Adriani90** [comment]
cc: @josephsl

**Comment by josephsl** [comment]
Hi,

Confirmed - I'll do something about it from Windows 10 App Essentials this weekend.

Thanks.

**Comment by JulienCochuyt** [comment]
@josephsl: Could you determine whether this is a regression in NVDA or a change in recent Windows 10?

**Comment by josephsl** [comment]
Hi, this is specific to Calculator and I deployed a fix as part of Windows 10 App Essentials 20.12. ultimately I hope Microsoft Calculator team would take these bugs into account. Thanks.
