### ISSUE TITLE
Can you change the table navigation keys?

### ISSUE THREAD

**Issue by TechHorseG** [nvaccess/nvda#11866]
Is there any way to rebind the table navigation keys? The current ctrl+alt+arrows clash with Magnifiers use of these keys to move its focus around.

Sorry if this is the wrong forum. If so is there an alternative forum for asking "how do I do X in NVDA" questions? Thanks.

**Comment by Mohamed00** [comment]
Yes, you can do this by going into the input gestures dialog while in 
browse mode. The gestures to change are located in the miscellaneous 
category.

**Comment by feerrenrut** [comment]
Closing this issue. A more appropriate location for these kind of questions is the users group: https://nvda.groups.io/g/nvda
