### ISSUE TITLE
NVDA should support Windows Frotz

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1186]
**Reported by KevanGC on 2010-11-07 05:53**
Windows Frotz is a program that plays Text-Adventure games, which are games that you can control by typing in text to move around characters, and the games are displayed in text. NVDA doesn't currently support Windows Frotz. Can you guys fix this?

**Comment by leonardder** [comment]
Closing, as there is an add-on for this (although not publicly listed).

**Comment by KevanGP** [comment]
In case you find this page and want to get the latest version of the addon, it isn't on the NVDA Addons website, but it can apparently be found in this repository.
https://github.com/nstockton/nvda-add-ons/
The one on the addons website is from before 2019.3, not compatible with latest NVDA.
