### ISSUE TITLE
Tables with colspan breaking column recognition in table reads

### ISSUE THREAD

**Issue by ThomasParker94** [nvaccess/nvda#11863]
A table displayed in Firefox 82 and read using NVDA 2020.2 is causing reading breaks when the table makes use a colspan attribute leading to every subseqent column association to be set to the first column in the table regardless of which column is actually being read.

![image](https://user-images.githubusercontent.com/74993331/100159883-4ccae880-2efa-11eb-9d0b-e43b378ca685.png)

### Steps to reproduce:
please make use of this example table for replication
```
<table>
    <thead>
        <tr>
            <th>Description</th>
            <th>Dividends</th>
            <th>Tax withheld</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>Norwood</th>
            <th>$854.79</th>
            <th>$132.45</th>
            <th>aa</th>
        </tr>
        <tr>
            <th>Norwood</th>
            <th>$854.79</th>
            <th>$132.45</th>
            <th>aa</th>
        </tr>
        <tr>
            <td colspan="4"></td>
        </tr>
        <tr>
            <th>Norwood</th>
            <th>$854.79</th>
            <th>$132.45</th>
            <th>aa</th>
        </tr>
        <tr>
            <td colspan="4"></td>
        </tr>
    </tbody>
</table>
```

<table>
    <thead>
        <tr>
            <th>Description</th>
            <th>Dividends</th>
            <th>Tax withheld</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>Norwood</th>
            <th>$854.79</th>
            <th>$132.45</th>
            <th>aa</th>
        </tr>
        <tr>
            <th>Norwood</th>
            <th>$854.79</th>
            <th>$132.45</th>
            <th>aa</th>
        </tr>
        <tr>
            <td colspan="4"></td>
        </tr>
        <tr>
            <th>Norwood</th>
            <th>$854.79</th>
            <th>$132.45</th>
            <th>aa</th>
        </tr>
        <tr>
            <td colspan="4"></td>
        </tr>
    </tbody>
</table>

### Actual behavior:
so as mentioned above the colspan will break column recognition.
### Expected behavior:
each column's data should correctly associate to the intended column heading
#### NVDA installed/portable/running from source:
full installation
#### NVDA version:
2020.2
#### Windows version:
Windows Server 2012
#### Name and version of other software in use when reproducing the issue:
Firefox 82.0
#### Other information about your system:
This is occurring on multiple systems within our test infrastructure I have only provided my own as I am raising this issue.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Older versions of Firefox and/or older versions of NVDA paired together do not experience this issue, I have also tested IE and Chrome which are also unimpacted. Running the same scenario across JAWS in each of the browsers mentioned also does not replicate the same result.
#### If addons are disabled, is your problem still occuring?
no addons in use
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes, to no avail

**Comment by feerrenrut** [comment]
@jcsteh You may want to be aware of this one. Looks like colspans are broken in recent versions of Firefox with NVDA. I haven't investigated yet based on it still working in Chrome. Let me know if it needs a deeper look.

**Comment by jcsteh** [comment]
Thanks. This is definitely a Firefox bug. I've filed this as https://bugzilla.mozilla.org/show_bug.cgi?id=1688532.

**Comment by ThomasParker94** [comment]
Thanks so much @jcsteh for forwarding the issue onto Mozilla. :)

**Comment by jcsteh** [comment]
I fixed this in Firefox 87 (currently Nightly).

**Comment by ThomasParker94** [comment]
Thanks for resolving this issue :)

Our organisation won't allow us to use nightly builds of Firefox but once 87 hits mainstream we will test on our end, I will make sure it works with the simplified code snippet before trying our more complex implementations. If all good I won't need to come back :)

**Comment by jcsteh** [comment]
I'm working on getting this into Firefox 86 as well so users get the fix
sooner, but I don't know whether that will be approved yet. I'll update
this issue once I know more.
