### ISSUE TITLE
Chrome PDF viewer's buttons are not read by tab key

### ISSUE THREAD

**Issue by minakononogaki** [nvaccess/nvda#11864]
### Steps to reproduce:

1. Open pdf file with Google Chrome.
2. Change to Browse mode (if not, press NVDA+space).
3. Press down-arrow key repeatedly to confirm there are rotate clockwise, download, print, fit to page(fit to width), zoom in, zoom out buttons.
4. Press ctrl+home.
5. Press NVDA+space to change to focus mode.
6. Press tab key repeatedly.

### Actual behavior:
No sound.

### Expected behavior:
There are rotate clockwise, download, print, fit to page(fit to width), zoom in, zoom out buttons.

#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2020.3
#### Windows version:
Windows 10 Version 2004
#### Name and version of other software in use when reproducing the issue:
Google Chrome Version: 87.0.4280.66 (Official build) (64 bit)
#### Other information about your system:
HP Elite book G3
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.
#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No.

In Windows 10 Narrator, rotate clockwise, download, print, fit to page(fit to width), zoom in, zoom out buttons are read by pressing tab key repeatedly in both, scan mode and scan mode off (changed by Narrator key + space).

[PDF_test_file.pdf](https://github.com/nvaccess/nvda/files/5594809/PDF_test_file.pdf)

**Comment by Adriani90** [comment]
Is the option "automatically move system focus to focusable objects" enabled or disabled? NVDA+8 is the command for that setting.

**Comment by michaelDCurran** [comment]
I am unable to reproduce this myself with this Chrome / Windows version. When tabbing to these buttons in focus mode NVDA announces them all correctly. If you can still reproduce this, please reopen the issue and attach an NVDA log set to debug that was captured over the time you opened the pdf file in Chrome, pressed control+home, switched to focus mode, and tabbed through the buttons.
