### ISSUE TITLE
Web dialogs are not handled with jira and firefox

### ISSUE THREAD

**Issue by daniel-1964** [nvaccess/nvda#11862]
[nvda.log](https://github.com/nvaccess/nvda/files/5591371/nvda.log)

### Steps to reproduce:
Using a version of firefox including the latest (83.0), go to https://xxx.atlassian.net (if you have an jira account) or create a free one on jira cloud (www.atlassian.com).
Try to create a board by clicking boards and then bellow board and select create.
The dialog can not be handled by NVDA but work successfully with chromium.

### Expected behavior:
I want to use the dialog 
### System configuration
windows 10 or windows 7

#### NVDA installed/portable/running from source:
installed version 2020.3 but don't work with earlier version.

**Comment by feerrenrut** [comment]
Have you raised this issue with Atlassian?

**Comment by daniel-1964** [comment]
Not yet. 
But it seem to me that this issue has sommething to do with the handling of the alert dialog box. If I navigate de page with object navigation (nvda+left/nvda+right) a get an allert objet with no decsendants. It's likely the alert subelement are ignored by NVDA in firefox.

**Comment by sagarjs** [comment]
+1

**Comment by daniel-1964** [comment]
I'am just testing with the latest NVDA 2020.4, and it seems that things go wrong. Now I am not able to interract with certain dialog using Ms Edge Chromium. Now things are the same under firefox and Chromium, but does not work for certains dialog on the jira web page. (E.G. unable to create a dashboard).

**Comment by Adriani90** [comment]
@daniel-1964 how is the behavior now with NVDA 2023.1? Are you still having this issue?

**Comment by Adriani90** [comment]
We don't have any updates from the initial author since more than two years, I am closing as abandoned. If you are still having this issue, please comment and we can reopen.
