### ISSUE TITLE
Unable to install add-ons on last alpha

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#11867]
### Steps to reproduce:

* Go to Windows Explorer
* select an add-on file (with .nvda-addon extension)
* Press enter

### Actual behavior:

Nothing happens. No vocal feedback. The selected file in Windows explorer keeps the focus.
No information in the log other than the 'Enter' key press.

### Expected behavior:

The add-on installation window opens.

### Note

I have tested the various commits (running NVDA from source) and have found that the commit responsible for this regression is ae4ea8f90420d1c00afa251f90abc2b59f35f826. It was introduced by PR #9079.
Cc @leonardder 

#### NVDA installed/portable/running from source:
From source or portable or temporary copy (run from installer).
Did not try to install this version.

#### NVDA version:
Version : source-master-001c99b

#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by CyrilleB79** [comment]
Additional comment:
Installing an add-on via the add-on manager works correctly.

**Comment by CyrilleB79** [comment]
For reference, this issue was originally discussed here:
https://nvda-addons.groups.io/g/nvda-addons/topic/78495637#14063

Cc @paulber19 who has initially found this issue and opened this discussion on the nvda-devel mailing list.

Strangely, Paul and I have a French system, but other people seem not to confirm the issue.
Could someone else confirm this issue with a system and/or NVDA in another language? Thanks.

**Comment by Christianlm** [comment]
I confirm the problem, using italian system language. Same behavior described above, both with nvda source and alpha portable version.

**Comment by leonardder** [comment]
I can not reproduce this using an English build of Windows 10 version 20h2.

> I have tested the various commits (running NVDA from source) and have found that the commit responsible for this regression is [ae4ea8f](https://github.com/nvaccess/nvda/commit/ae4ea8f90420d1c00afa251f90abc2b59f35f826). It was introduced by PR #9079.
> Cc @leonardder

That is tricky, as that commit contains much C++ code that requires a rebuild of NVDAHelper. Also, the file association relies on the installed version of NVDA. That makes it pretty hard to debug this, especially now I can't reproduce this myself.

**Comment by CyrilleB79** [comment]
> That is tricky, as that commit contains much C++ code that requires a rebuild of NVDAHelper.

I just want to confirm that I have successfully rebuilt the C++ code before running from source on each commit when bissecting.

> Also, the file association relies on the installed version of NVDA. That makes it pretty hard to debug this, especially now I can't reproduce this myself.

So let's clarify the two environments where it was reproduced:
* Environment 1:
  * Running version of NVDA: Temporary copy of nvda_snapshot_alpha-21391,15ab401a[2020-11-22].exe or portable Version : alpha-21391,15ab401a, both set to French
  * Window 10 1809 French
  * Version of NVDA installed on the system (but not running): NVDA 2020.3
* Environment 2:
  * Running version of NVDA: from source, commit ae4ea8f, set to French
  * Window 10 2004 French
  * Version of NVDA installed on the system (but not running): NVDA 2020.3
  
May it just be that installed version 2020.3 is trying to open the file in Windows Explorer and then fails to communicate with the currently running version of NVDA (last alpha)?

@leonardder and other, could you detail your environment when trying to reproduce this issue: which version of NVDA is running and which version is installed on the system if different from the running one?

**Comment by leonardder** [comment]
> May it just be that installed version 2020.3 is trying to open the file in Windows Explorer and then fails to communicate with the currently running version of NVDA (last alpha)?

That is very much possible, since the RPC definitions have changed since 2020.3. It is at least a scenario that we shouldn't support. I'd only consider this a bug when this happens on an installed copy when that particular copy is running. In that situation, I can't reproduce.

**Comment by feerrenrut** [comment]
We could probably improve the stability of this going forward, be separating out those aspects of the RPC so they aren't affected by changes such as this. I think that is low priority for us.

I'm going to remove the regression label and the 2020.4 milestone. I think this will be a rare situation for people to hit.

**Comment by OzancanKaratas** [comment]
There are no problem in Turkish Windows 10 system. It works as it should.

**Comment by lukaszgo1** [comment]
Confirmed on Polish Windows 7 with NVDA 2019.2.1 installed and last Alpha running as an portable. I can also confirm that on my Windows 10 1803 VM this cannot be reproduced with last Alpha installed. Fortunately this turns out to be pretty easy to fix - upcoming PR.
