### ISSUE TITLE
NVDA narrates all actionable elements in dialog 

### ISSUE THREAD

**Issue by kolaps33** [nvaccess/nvda#11874]
### Steps to reproduce:
1.Navigate to the example:
https://tl8xk.csb.app/
2. Navigate to the "Dialog test" button and press "Enter" key
3. observe NVDA narration

### Actual behavior:
NVDA narrates focused element +  dialog name(set via aria-label) + all actionable elements inside the dialog
![image](https://user-images.githubusercontent.com/22620150/100457997-52275f00-30c3-11eb-9843-fbb0fc3d2649.png)

### Expected behavior:
NVDA narrates focused element + dialog name
It doesn't narrate rest of the elements in the dialog. 
What is behind the expected behavior:
- tested with JAWS and VoiceOver and both readers don't narrate every actionable element in the dialog
- with narration of every actionable element it sounds verbose

#### Windows version: 
Windows 10 Enterpirse 
10.0.19042

#### Does the issue still occur after restarting your computer?
yes 

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no, I didn't try

#### If addons are disabled, is your problem still occuring?
yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by Adriani90** [comment]
In nvda settings under browse mode settings, is automatically read page after load enabled?

**Comment by kolaps33** [comment]
Hi @Adriani90 
thanks. Yes when I disabled the option "Automatic Say all on page load", then it was not narrated each actionable element on the page. 

Then it looks like it is not NVDA bug, just setting which can users switch off.
