### ISSUE TITLE
Report line numbers in controls using MozillaCompoundTextInfo

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#11882]
### Is your feature request related to a problem? Please describe.
Recently I've started to use Etherpad which is a collaborative online board for making notes when working in my university classes. One very useful feature when collaborating with others is ability to tell in which line you're in - it is shown visually but there is no accessible indication and I don't think ARIA allows for implementing this quite easily even if Etherpad developers would want to.

### Describe the solution you'd like
NVDA should be able to report line numbers in MozillaCompoundTextInfo when the corresponding option is enabled in document formatting settings.
### Describe alternatives you've considered
My current workaround is a simple globalPlugin which creates a textInfo from the start of the text field to the position of the caret, retrieves lines using `getTextInChunks` and reports  length of the resulting list. This is unfortunately quite slow.
### Additional context
None

**Comment by lukaszgo1** [comment]
cc  @jcsteh Can this be implemented at present or would it require some changes in Firefox?

**Comment by jcsteh** [comment]
I don't think it's possible in either NVDA or Firefox. As far as I know, browsers don't have any concept of line numbers. Calculating them would be pretty nasty, since the text stuff is implemented on almost all objects and a client might query line numbers in a massive document, which would cause major performance problems.

**Comment by michaelDCurran** [comment]
Based on  @jcsteh  's feedback which I agree with, closing as can't fix. If ARIA is one day extended to allow authors to specify line numbers, then NVDA / Firefox / Etherpad could make use of that.
