### ISSUE TITLE
NVDA very sluggish in a long list items

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1191]
**Reported by allan on 2010-11-09 09:37**
system:
windows 7 ultimate 32-bit
NVDA 2010.2 portable
intel core 2 quad machine
4GB DDR2-800 RAM

STR:
1. open windows update.
1. go to update history and there's a long list of updates, NVDA take about 4 to 5 seconds to read the item while arrowing up/down.

**Comment by dkager** [comment]
My attempts on Windows 10 are much more responsive than the 4-5 seconds mentioned. Closing because the reporter never came back to it.
CC @josephsl
