### ISSUE TITLE
Table navigation commands do not always navigate in the same column or row

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#11919]
### Steps to reproduce:

* Download [this example page](https://github.com/nvaccess/nvda/files/5665384/TableNavigation.html.txt). 
* Remove txt extension and open it in your browser
* Navigate to the unique table
* Go in the "Bob" column (last one)
* Press control+shift+downArrow to read the figures in each cell of this column until the end

### Actual behavior:

* The figures corresponding to a month are read correctly
* When arriving in the last row, the virtual cursor is in the first cell of the last row

### Expected behavior:

* The figures corresponding to a month are read correctly
* When arriving in the last row, the virtual cursor should remain in the 4th column ("Bob")

### Notes and context

* I have created the example page from scratch to give a simple example that can be published. The real-life example that caused me to open this PR is in a company application. The table in this application has more than 30 columns and it is very frustrating when navigating in the last columns (or in central columns) to have the cursor moved in the first column at a moment.
* Sorry if my HTML is not so standard, but it should be enough to illustrate the issue.
* I have checked the behaviour with Jaws. Jaws doe not exhibit this issue.

### Technical

* The issue is that when entering a merged cell (spanning over multiple rows or columns), the cursor is automatically set to the coordinates of the first cell that compose this merged cell.
* The issue has been explained for columns, but it is the same for rows. It can be tested in the same example table where the years span over 2 cells.
* When using a table navigation command, would it be possible to memorize the current row/column, the movement direction and the table ID which it is associated with? This information should be forgotten if another table navigation command is issued in a different table or direction.

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.3
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
Chrome, Firefox, but any browser should do

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes. Same behaviour in older versions.

#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

Cc @mltony if you are interested to work on this, hopefully in NVDA core, or in Tony's enhancement add-on.

**Comment by DrSooom** [comment]
Duplicate of issue #7278.

**Comment by CyrilleB79** [comment]
Thanks @DrSooom. So I am closing this issue in favor of the previous one and will comment there.
