### ISSUE TITLE
Last character is stripped when using object navigation to read messages and other texts in Unigram

### ISSUE THREAD

**Issue by sukiletxe** [nvaccess/nvda#11930]
### Steps to reproduce:
(This is a partial description which reproduces the problem. This also happens when trying to navigate the Unigram version, located in settings and only accessible with object navigation, in case that's easier to reproduce)
1. Open a chat in Unigram.
2. Navigate to the list of messages, and focus a text message.

3. Focus the message's content with object navigation.
4. Read the message using object navigation

### Actual behavior:

When reading by line and by word, the entire message is readable. But when reading by character, the last character is stripped from the message's content.

### Expected behavior:

All navigation modes should report the same result. If the message ends by a question mark, the question mark should be navigable when reading character by character (this is just an example symbol, it happens with every character as far as I am aware).

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2020.3

#### Windows version:

Windows 10 20H2

#### Name and version of other software in use when reproducing the issue:

Unigram 7.3 (5922) X64. Happens also with version from Microsoft store, though currently I am using a Beta version.

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No.

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

No.

**Comment by Adriani90** [comment]
Same underlying cause like #13302. Closing in favor of #13302.
