### ISSUE TITLE
nvda double speaks option names in preferences dialog of lotus symphony

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1193]
**Reported by mike.reiser on 2010-11-10 05:53**
In symphony, nvda double speaks option names causeing a bit of a delay when arrowing through the dialog.  STR:
1.  Create a new document in symphony and bring up preferences.  
2.  Start arrowing around in preferences in the tree view.  

Actual results: nvda will double speak items and this will cause a delay of about a second when moving through the dialog.  

Expected results: The usual, nvda should speak items once and not cause a delay.

**Comment by ehollig** [comment]
Closing:

1. This ticket is almost 7 years old.
2. IBM discontinued development of lotus symphony in January 2012.
