### ISSUE TITLE
NVDA's mouse tracking does no longer work in Skype

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#11957]
### Steps to reproduce:
1. Install the latest version of Skype.
2. Install and launch the latest version of NVDA.
3. From NVDA's settings, go to "Mouse" and enable "Mouse tracking" and "Report object type".
4. Launch Skype and sign into your account.
5. Move the mouse cursor in Skype's windows and dialogs.
6. Observe what NVDA reads under the mouse cursor.

### Actual behavior:
NVDA says only "pane" when the mouse cursor is over the Skype's windows and dialogs.

### Expected behavior:
NVDA should read the types of the objects and the containing text pointed with the mouse cursor, as it did before.

### System configuration
- Operating system: Windows 10 Pro version 20H2 (build 19042.685), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-21524,7b92e442, installed, in bulgarian.
- Skype version: 8.68.76.35 (insider build), in bulgarian.
- Processor: Intel Core i5-9400F at 2.90GHz.
- RAM Memory: 16.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC892 at Intel Cannon Point PCH.

#### Does the issue still occur after restarting your computer?
Yes, it does

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes - NVDA 2020.3 and the behavior is the same.

#### If addons are disabled, is your problem still occurring?
Yes, it is.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No, but since it happens only in Skype, I doubt it that the issue described here has something to do with it.

### Additional information:
I'm using the test (insider preview) version of Skype, but since I've noticed this occurring with Skype 8.67, which is now a public release, I don't think the issue affects only the test builds of Skype.

Also, this seams to be affecting JAWS (v2021) as well, but only partially affects Narrator. Either so however, I think the main culprit here is Skype, but I wanted to report this here, so I can at least gather some technical information with which I can report the problem to the Skype developers. Or maybe, if they can, even NV Access can directly report this to the Microsoft/Skype teams responsible for Skype's development.

**Comment by Neurrone** [comment]
Potentially related to #11954

**Comment by seanbudd** [comment]
Is this still an issue with the latest stable version of Skype and NVDA 2022.1rc2?

**Comment by k-kolev1985** [comment]
No, this seams not to be an issue with the latest versions of NVDA and Skype.

**Comment by seanbudd** [comment]
Thanks @k-kolev1985
