### ISSUE TITLE
outlook.com: reading email subject, annoyed message "Message list No items selected  list"

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#11952]
### Steps to reproduce:
1. Open [outlook.com](https://outlook.live.com/mail/0/inbox)
2. Press i to move to next list item.
#### Actual behavior:
speech: "Message list No items selected  list": (email subject)

#### Expected behavior:
email subject only

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
2020.3, 2020.4 beta1

#### Windows version:
10.0.18363 workstation

#### NVDA settings:
document formatting: lists (not check)

#### Name and version of other software in use when reproducing the issue:
Firefox: 84.0

Microsoft Edge

#### Does the issue still occur after restarting your computer?
Yes.

#### If addons are disabled, is your problem still occuring?
Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No.

**Comment by bhavyashah** [comment]
@surfer0627  Taking nothing away from the validity of this issue, I wanted to share a work-around that might help you while this issue persists. When you are somewhere in the message list, press NVDA+Space and then use the arrow keys to move through your emails. This approach avoids the verbosity you reported.

**Comment by surfer0627** [comment]
@bhavyashah Thank you for the tips.

**Comment by Adriani90** [comment]
Closing as per the above comments.
