### ISSUE TITLE
NVDA stops playing audio when audio output device is changed using latest betas

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#11968]
Hi.

I use a USB sound device with my computer. While using the beta, the following has been consistently reproduceable:
1. Use NVDA when the sound card is plugged in.
2. Unplug the USB sound device.
3. Try to invoke progress bar sounds, browse/focus mode sounds etc.
4. Plug back in the USB sound device.5.

Expected behaviour: NVDA should play the sounds using the device that is in use. Both synthesizer and voice should come through the same audio output device.
Actual behaviour: NVDA's synthesizer output comes through the right device in steps 3 and 4, but the minute the audio device changes, NVDA stops playing its sounds until it is restarted.

NVDA versions where this happens: NVDA 2020.4beta1, NVDA 2020.4beta2, but not NVDA 2019.3 or older
Default audio output device: Microsoft Sound Mapper
Installed or portable: Installed
Windows version: Windows 10 20H2 (64-bit) build 19042.685

**Comment by Brian1Gaff** [comment]
For the record, the exact opposite happens here in windows 7. Ie the windows 
sounds still work but nvda won't until its rebooted.

 This sort of thing has always been a little flaky in Windows to be honest.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by kvark128** [comment]
I confirm the problem on Windows 10 1809 with NVDA 2020.4beta2. When disconnecting the USB headphones, any speech output causes the following exception:
ERROR - queueHandler.flushQueue (10:22:41.502) - MainThread (9388):
Error in func cancelSpeech
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "speech\__init__.pyc", line 146, in cancelSpeech
  File "speech\manager.pyc", line 767, in cancel
  File "synthDrivers\espeak.pyc", line 146, in cancel
  File "synthDrivers\_espeak.pyc", line 245, in stop
  File "nvwave.pyc", line 501, in stop
  File "nvwave.pyc", line 112, in _winmm_errcheck
OSError: [Errno 6] There is no driver installed on your system.

**Comment by fisher729** [comment]
Hi.

I get the same errors, but I use a different synth. In fact, the
synthesizer plays no role in whether this occurs or not.

**Comment by leonardder** [comment]
I've also seen very strange issues with audio device switching lately, notably with a bluetooth headset connecting and disconnecting without speech and beeps going to the correct output.
@feerrenrut I'm afraid this is something that should be investigated before the 2020.4 release and is a potential show stopper.

**Comment by fisher729** [comment]
Hi.

It's so bad I had to uninstall the beta. Haven't tried it with a bluetooth speaker as yet, though.

**Comment by ivnc** [comment]
Same issue here. It is specially noticeable in computers that consider speakers and earphones as different soundcards, since plugging or unplugging earphones makes sounds as browse/focus mode indication to stop working until a NVDA restart.

Regards.

**Comment by feerrenrut** [comment]
I don't have a USB audio device to test, and don't seem to be able to reproduce this with a bluetooth headset. I believe I understand the issue (based on the stack trace), and have attempted to provide a fix in #11978 and a [try build is available](https://ci.appveyor.com/api/buildjobs/1ys6w1fa2l6ss1y3/artifacts/output%2Fnvda_snapshot_try-fixUsbSoundDevError-21576%2C21ad97b4.exe), please could you test this out and let me know if it resolves the issue?

**Comment by ivnc** [comment]
I've briefly tested it with temporary execution and seems to be working with this try build.

Regards.

**Comment by fisher729** [comment]
Hi.

The posted try build works perfectly. I no longer have the issue I reported.

**Comment by kvark128** [comment]
Yes, this build also works perfectly for me. When disconnecting the USB headphones, NVDA speech now correctly switches to the laptop speakers.

**Comment by Neurrone** [comment]
I'm seeing this issue except that its for a non-USB audio device (i.e, using the regular 3.5mm jack) on a new computer.

Will this fix only apply to USB devices?

**Comment by fisher729** [comment]
Try it and report back.

**Comment by Neurrone** [comment]
@feerrenrut this also fixes it for me as well
