### ISSUE TITLE
appModule for Jaba MUD Client

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1196]
**Reported by aleksey_s on 2010-11-11 09:58**
This is an inclusion request.
Some notes about the module:
- It uses new !DisplayModelLiveText API to automatically read incoming text from the MUD
- It automatically sets navigator to the output window whenever input field gets focused, because it is very inconvenient for user to activate flat review each time he/she wants to review text from server
- It automatically manages !ReviewCursorFollowsCaret option that it becomes disabled when user activates program window, so review always is on the output control even if user types something in the input field.
  I find current implementation of last two options neither elegant, but since NVDA doesn't have some concept like favorite objects I do need to emulate it for user convenience.

References:
There are a few forks of this client, One of those you can download here: http://jmc.alfuken.net/en/

**Comment by leonardder** [comment]
This ticket looks quite abandoned. Is there still desire to include this appModule into core?

**Comment by Adriani90** [comment]
@alexey_s

**Comment by Adriani90** [comment]
We cannot find the author of this issue and we do not have an update on this since many years. Meawhile, the most current version of Jaba mud client is 3.5.
We also don't have any further requests related to this mud client at all from other users. I am closing this as abandoned.
