### ISSUE TITLE
role=alert with input .focus(). Not announced.

### ISSUE THREAD

**Issue by 3dots** [nvaccess/nvda#11990]
### Steps to reproduce:

1. Use Chrome.
2. Go to this [codepen](https://codepen.io/3dot/pen/qBaKGBE)
3. start NVDA
4. press enter when focused on the validate button

### Actual behavior:
Alert message ends up in the speech viewer log, but it is not actually announced.

![image](https://user-images.githubusercontent.com/6589306/104018449-ca377900-5187-11eb-94ad-afbd6cbffabc.png)

Changing order of focus and alert creation doesn't help. Adding a half sec setTimeout around the focus ends up with NVDA starting to announce the alert, but then cuts off prematurely at the focus.

### Expected behavior:

Alert message should be announced. It works in Firefox 78.6.1esr (64-bit).

#### NVDA installed/portable/running from source:
portable
#### NVDA version:
 2020.3
#### Windows version:
OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134

#### Name and version of other software in use when reproducing the issue:
Chrome Version 87.0.4280.141 (Official Build) (64-bit)

#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.
#### If addons are disabled, is your problem still occuring?
Can't try. Only have Symantec Extension in Chrome, but can't disable it at work.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No.

**Comment by Adriani90** [comment]
This seems fixed in Chrome Canary 128 with NVDA 2024.3 Beta. Closing as works for me. If you are still having this issue, please comment and we can reopen.
