### ISSUE TITLE
Errors in new diffing algorithm breaks automatic reading of consoles till NVDA restarts

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#11992]
### Steps to reproduce:

Unsure exactly what caused this, I think it happened right as I switched from another application into the windows 10 console (conhost, am not using windows terminal).

### Actual behavior:

The following error is logged. Subsequent text written to the console is no longer read until NVDA restarts.

```
ERROR - diffHandler.DiffMatchPatch.diff (13:48:59.482) - Dynamic_WinConsoleUIAEditableTextWithAutoSelectDetectionUIA._monitorThread (1516):
Exception in DMP, falling back to difflib
Traceback (most recent call last):
  File "diffHandler.pyc", line 94, in diff
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 322: unexpected end of data
ERROR - diffHandler.DiffMatchPatch.diff (13:48:59.545) - Dynamic_WinConsoleUIAEditableTextWithAutoSelectDetectionUIA._monitorThread (1516):
Exception in DMP, falling back to difflib
Traceback (most recent call last):
  File "diffHandler.pyc", line 91, in diff
OverflowError: cannot fit 'int' into an index-sized integer
```

### Expected behavior:

Reading of new text does not break

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-21599,d3aaca53

#### Windows version:
Windows 10 2004

#### Name and version of other software in use when reproducing the issue:
Conhost

**Comment by Neurrone** [comment]
cc @codeofdusk

**Comment by codeofdusk** [comment]
Yes, this is a known issue.

**Comment by feerrenrut** [comment]
It seems this could fail in a more graceful way. @codeofdusk are you investigating this?

**Comment by codeofdusk** [comment]
I'm not really sure how to fix this, although I can reliably repro on my system. As I said over in the PR, flushing stdin/stdout doesn't fix it. I've added logging to nvda_dmp which appears to be receiving everything correctly. I've also contacted the author of the original DMP library to see about obtaining a dual-licensed version for NVDA (obviating the need for nvda_dmp) but haven't received a response.

**Comment by codeofdusk** [comment]
@Neurrone Can you still repro this on latest master?

**Comment by Neurrone** [comment]
I'll need a few days to test it with this setting enabled. Will report back soon.

Thanks @codeofdusk for investigating this 🙏

**Comment by codeofdusk** [comment]
@Neurrone Do you have any further updates?

**Comment by Neurrone** [comment]
Apologies, forgot to enable this setting. I'll do so and will get back by next Wed, as that should be enough time in the console for me to figure out if I still encounter this.

**Comment by codeofdusk** [comment]
@Neurrone Any updates on this?

**Comment by Neurrone** [comment]
I'm no longer seeing this, closing.
