### ISSUE TITLE
Unexpected empty lines in browseable messages (e.g. formatting information)

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#12004]
### Steps to reproduce:

* set the cursor or virtual cursor on a text having formatting information such as text in a web page
* Press two times quickly NVDA+F to get formatting info in a browseable window
* Examine the formatting information line by line by pressing down arrow many times

Extra:
* Open the Python console and type:
  `import ui;ui.browseableMessage("Hello\nworld")
`

### Actual behavior:

NVDA reads "blank" one line in two in formatting info as well as in "Hello world" message.

### Expected behavior:

NVDA should not read "blank" between formatting information line nor in "Hello world" message since:
* As a user, we do not need blank lines to examine a text such as formatting information
* Visually, there is no blank line
* The source string of the "Hello world" message does not contain any blank line.

#### NVDA installed/portable/running from source:
all
#### NVDA version:
2020.4beta4
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, 2020.3: same issue.
It seems to me that this issue has always been there.
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by michaelDCurran** [comment]
I cannot reproduce this issue. Has this always been the case for you, or have you only seen it happening quite recently?

**Comment by Christianlm** [comment]
I noticed this behavior only with the screen layout turned on...

**Comment by michaelDCurran** [comment]
Ah thanks @Christianlm  yes, turning screen layout off reproduces the issue for me.
