### ISSUE TITLE
Update BRLTTY for Python 3.8

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#12018]
### Is your feature request related to a problem? Please describe.
Python 3.7 is reaching the end of life, new releases are now source only. In order to upgrade to later versions of Python a new version of the BRLTTY Python C extension must be built.

### Describe the solution you'd like
Python extension built and upgraded.

### Describe alternatives you've considered
Not upgrade version of Python used by NVDA

**Comment by leonardder** [comment]
See https://github.com/nvaccess/nvda-misc-deps/pull/20

**Comment by dingpengyu** [comment]
The current issues have been resolved, should they be closed?

**Comment by feerrenrut** [comment]
Fixed with https://github.com/nvaccess/nvda/pull/12075
