### ISSUE TITLE
When page in google chrome is opened, the errors start to appear

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#12014]
### Steps to reproduce:
1. open any webpage you want in google chrome. For example www.github.com/nvaccess/nvda or www.dnevno.hr
### Actual behavior:
The page title is not read, braille display is not refreshed, and the page content is not read too. 
the log states the following 
ERROR - queueHandler.flushQueue (12:51:45.406) - MainThread (12248):
Error in func VirtualBuffer._loadBufferDone
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "virtualBuffers\__init__.pyc", line 470, in _loadBufferDone
  File "browseMode.pyc", line 1280, in event_treeInterceptor_gainFocus
  File "enum.pyc", line 354, in __getattr__
AttributeError: Focus
INFO - braille.BrailleHandler.setDisplayByName (12:51:57.198) - braille._BgThread (9988):
Loaded braille display driver noBraille, current display has 0 cells.
ERROR - queueHandler.flushQueue (12:52:39.840) - MainThread (12248):
Error in func VirtualBuffer._loadBufferDone
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "virtualBuffers\__init__.pyc", line 470, in _loadBufferDone
  File "browseMode.pyc", line 1280, in event_treeInterceptor_gainFocus
  File "enum.pyc", line 354, in __getattr__
AttributeError: Focus

### Expected behavior:
above should work
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
alpha-21672,856adec6

#### Windows version:
version 10.0.19042 workstation

#### Name and version of other software in use when reproducing the issue:
Google chrome version 88.0
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
not applicable. This error was introduced after the merge of enum constants to reasons.
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
not applicable and not related

**Comment by lukaszgo1** [comment]
﻿I'll fix this later today.

**Comment by CyrilleB79** [comment]
@lukaszgo1 wrote:
> ﻿I'll fix this later today.

Oh sorry, I missed this comment. I have already opened #12015 to fix it.

**Comment by dingpengyu** [comment]
hello @lukaszgo1 and @zstanecic 
Using NVDA version alpha-21672+ google chrome 89.0.4389.23dev 64 has the same problem.
log file:

[nvda.log](https://github.com/nvaccess/nvda/files/5886360/nvda.log)
thanks
