### ISSUE TITLE
bug: nvda incorrectly steals focus when using aria-labelledby and role

### ISSUE THREAD

**Issue by liamdebeasi** [nvaccess/nvda#12028]
When using `aria-labelledby` and `role`, NVDA incorrectly shifts focus to the next focusable element when pressing Space bar.

### Steps to reproduce:

1. Start NVDA.
2. Open https://codepen.io/liamdebeasi/pen/mdOewMy.
3. Press "Tab" to focus the button. (You may need to click inside of the rendered preview first)
4. Press "Tab" to focus the checkbox.
5. Press "Spacebar" to toggle the checkbox. The focus should move from the checkbox to the button.

Repeat steps 2-5 with NVDA not running. You should notice that the focus does not move from the checkbox to the button in step 5.

Additionally, using `for` instead of `aria-labelledby` works as expected. You can test this by following the steps above on this other codepen: https://codepen.io/liamdebeasi/pen/bGBVRjW

### Actual behavior:

The focus incorrectly moves from the checkbox to the button when pressing spacebar.

### Expected behavior:

I would expect that the checkbox retains focus and is toggled.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No other versions of NVDA tried.

#### If addons are disabled, is your problem still occuring?
No addons installed.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes, but there was no change to the reported behavior.

**Comment by Adriani90** [comment]
I can reproduce this also in Firefox with NVDA 2023.2. I tried to set tabindex in the div, still it doesn't help. cc: @jcsteh

**Comment by jcsteh** [comment]
This is due to authoring error. The checkbox is inside a labelled role="switch". The label overrides the content (in this case the check box) of the switch. Furthermore, the [ARIA spec](https://w3c.github.io/aria/#switch) specifies that children of a switch are presentational.
