### ISSUE TITLE
Sluggish browsing - UIA with Edge

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#12031]
### Steps to reproduce:
1. Launch NVDA.
2. From NVDA's advanced settings, enable the option "Use UIA with Microsoft Edge and other Chromium based browsers when available" (set it to "Yes").
3. Open Microsoft Edge and load Facebook's desktop site and log in into your Facebook account.
4. Press NVDA+Space to enable NVDA's "focus mode".
5. Press J to go to the next and K to go to the previous item in your news fedd.
6. Observe NVDA's time for reacting to the focus change.

### Actual behavior:
NVDA is sluggish to react when the focus changes between the news feed items.

### Expected behavior:
NVDA should react fast when navigating the news feed with J and K, as it does when its "Use UIA with Microsoft Edge and other Chromium based browsers when available" option is disabled "Set to "No" or "Only when necessary").

### System configuration
- Operating system: Windows 10 Pro version 20H2 (build 19042.746), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-21710,11ba984f, installed, in bulgarian.
- Microsoft Edge version: 88.0.705.56, 64-bit, in bulgarian.
- Processor: Intel Core i5-9400F at 2.90GHz.
- RAM Memory: 16.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC892 at Intel Cannon Point PCH.

#### Does the issue still occur after restarting your computer?
Yes, it does.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, because the feature that causes this issue is available only in alpha versions.

#### If addons are disabled, is your problem still occuring?
Yes, it is.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No, because in this case it is probably not related to this issue.

**Comment by Nikita34196** [comment]
Hello. I also experience it on many sites. for example, vk.com

**Comment by Adriani90** [comment]
@k-kolev1985, @Nikita34196 can you please test with last NVDA alpha on Edge 111? Are you still having this issue?

The last alpha verson of NVDA can be downloaded at this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by k-kolev1985** [comment]
@Adriani90 I cannot reproduce this anymore. It was probably fixed in the Chromium project, on which browsers like Edge are based.

**Comment by seanbudd** [comment]
Closing as fixed
