### ISSUE TITLE
nvda randomly looses focus in virtual buffers in latest firefox 4 nighly

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1203]
**Reported by mike.reiser on 2010-11-17 06:25**
As of nvdar3938 and the latest nightly build of firefox 4, nvda will randomly act like the virtual buffer is loading and say "Unknown" placeing the user in a totally blank buffer where the page can't be read.  The only way to solve this is to tab around in it.  STR:
1.  Go to https://bugzilla.mozilla.org/buglist.cgi?quicksearch=nvda
2.  Start arrowing around in the results.  Notice that while arrowing, nvda will randomly announce the title of the page and the application and will say "Unknown."  After that nothing happens when arrows are pressed.  Pressing tab will work but sometimes it just keeps saying unknown.  

Actual results: nvda will act like the virtual buffer is loaded or is loading, but no content will appear after a minute.  Tabbing takes one back to the position they were at when this event occurs.  

Expected results: nvda should maintain position.  This behavior also happens on the nvda trac page.  
**Blocking #3960**

**Comment by dkager** [comment]
> It's fixed for Firefox 32.

That's not bleeding edge code anymore. :)
