### ISSUE TITLE
OWASP ZAP, and other high-output Java applications, freeze NVDA

### ISSUE THREAD

**Issue by zersiax** [nvaccess/nvda#12040]
### General Description

NVDA seems to handle getting a large amount of info through the Java Accessibility Bridge somewhat poorly. Two examples come to mind:

- In the Java-based game Slay the Spire, given enough so-called Steam Modules are present, at some point NVDA will freeze for several seconds then throw a large amount of errors indicating that, from memory, the buffer for the access bridge is full/overextended or similar. I don't have logs at hand to give the exact message. What is worrying about this is that this will happen regardless of the focus being in the actual window or not.
- A second example is in the above mentioned penetration testing application OWASP ZAP or Zed Attack Proxy, which on pressing a button that would generate a lot of application-wide changes, instantly freezes NVDA, generates watchdog "Core frozen in stack"errors in the logs and makes the screenreader entirely unusable until the application is closed.
- 
### Steps to reproduce:
1. Run OWASP ZAP v2.10.0. This is a free download that requires a version of the JRE to be installed.
2. Make your way , through review cursor / mouseClick, to the quickstart tab.
3. Once you land on the explanatory edit field ctrl+tab  (just tabbing won't work) out of it and hit enter on the automated scan button.
4. Find the edit field for the URL and enter some address you have jurisdiction over, I used my VPS. DO NOT ENTER SOME PUBLIC RANDOM URL HERE!
5. Hit enter on the "Attack" button.
### Actual behavior:
NVDA will freeze and become unusable, and that freeze persists across NVDA restarts. The only way to seem to fix it is to kill the application in question.

### Expected behavior:
NVDA should be able to handle this, or at least mitigate the damage to the active window only.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-21668,e8f14f9a

#### Windows version:
2004
#### Name and version of other software in use when reproducing the issue:
OWASP ZAP v2.10.0, JAVA 15 through x64 JDK
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes
[zap_log.log](https://github.com/nvaccess/nvda/files/5932823/zap_log.log)

**Comment by Adriani90** [comment]
@zersiax are you still seeing this issue in NVDA 2023.2?

**Comment by Adriani90** [comment]
We didn't get any further updates from the initial author since more than 1 year, and during last months NVDA's performance improved significantly. also many issues related to freeze have been solved meanwhile. i am closing this as abandoned, please feel free to comment if you are still having this issue and we can reopen.
