### ISSUE TITLE
Incorrect Announcements for Caret Movement Inside Editable Links

### ISSUE THREAD

**Issue by jscholes** [nvaccess/nvda#12041]
Note: this issue only relates to Google Chrome; the expected behaviour is present in Mozilla Firefox.

#### Steps to reproduce:

1. Open the test page at https://jscholes.github.io/contenteditable/link-behaviour-demo.html.
2. Move your cursor into the editable region, which starts with a level 2 "Broken Cases" heading, and ensure focus mode is active.
3. Within the "Broken Cases" section, navigate to the start of each line starting with a link, and read them with the Right Arrow key to move by character.  Specifically, you can stop caret movement after encountering the space before the word "hello".
4. Within the "Working Cases" section, navigate to and readh each line containing a link in the same way described in `#3`.

#### Expected behavior:

When the caret moves onto the comma after the S in the linked word "Scholes", NVDA will announce, "out of link", and the presence of the comma character.  This should happen for all lines in the document which start with the `@James Scholes` link.

#### Actual behavior:

For all links in the "Broken Cases" section, moving the caret onto the comma after "Scholes" causes NVDA to reannounce the link text in full.  The expected behaviour is only present for the lines in the "Working Cases" section.

##### NVDA installed/portable/running from source:

Installed

##### NVDA version:

2020.3

##### Windows version:

Windows 10 Pro, version 10.0.18363 build 18363, x64

##### Name and version of other software in use when reproducing the issue:

Google Chrome, version 88.0.4324.146 (Official Build, 64-bit)

##### Does the issue still occur after restarting your computer?

Yes

##### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

##### If addons are disabled, is your problem still occuring?

Yes

##### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes

**Comment by jscholes** [comment]
CC @sinabahram

**Comment by Adriani90** [comment]
cc: @aleventhal, @ObjectInSpace

**Comment by jscholes** [comment]
This seems fixed in Chrome Canary (and the latest stable Chrome release too).
