### ISSUE TITLE
Task:  Add docs for manual virtual env process

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#12059]
To ensure we understand the process, and to provide information in case any aspect fails for some developer provide docs explaining the process.
Docs should include:
- Creating virtual env.
- How to populate with dependencies.
- What to do when deps change.
- Where packages for deps are cached.

In order to write these docs, the approach will need to be proved and tested locally.

**Comment by michaelDCurran** [comment]
This is no longer needed as the virtual environment process is now transparent in pr #12075

**Comment by feerrenrut** [comment]
I'd still like this to be documented in the code base. Hunting down the right PR for the overall design which contains the "what does it do", "how does it work", and "why is it done this way" is not always easy. I'd recommend copying the PR description into a markdown file in devDocs and then making sure it answers those three questions (what, how, why).

Can we please reopen this issue and address it in PR "Py3.8: Transparently use a Python virtual environment under the hood #12075"
