### ISSUE TITLE
[Accessibility][Screen reader- Manage Metadata Services - View dashboard]: In browse mode, nvda focus moves twice on filter dropdown.

### ISSUE THREAD

**Issue by ashish315** [nvaccess/nvda#12057]
**User Experience:**
Screen reader users will face difficulty while navigating to the control as NVDA reads half the information at 1st navigation and 2nd half on 2nd navigation. This makes confusion the user in understanding about the control and misguide them.

**Repro Steps:**
1. Open [URL](https://a830edad9050849829e20072008-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/home).
2. Select 'Content Services' under 'Reports' from the left navigation bar.
3. Navigate to "All" dropdown in browse mode.
4. Observe the issue.

**Actual Result:**
The screen reader focus land on "All" twice, 1st time it announces all the half content and 2nd time also focus remains on the same and announces the other half of the relevant information.

**Expected Result:**
The consolidated focus should land only once on the 'All' menu item and announces all the relevant info at that time.

**MAS Reference:** 
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/Doc.aspx?sourcedoc=%7BF98F4235-B6BD-47D3-8DA4-F28B9B6FBFA8%7D&file=Guideline%20101%20%E2%80%93%20Recommended%20Assistive%20Technology%20Tools%20for%20MAS%20Testing%20of%20Microsoft%20Digital%20Properties.docx&action=default&mobileredirect=true&cid=cfd410f9-ab7d-45d6-b822-faae4139f746
### Expected behavior:

**Test Environment:**
OS: Windows 10
Version: 2004 (OS Build 20180.1000)
Version 86.0.594.1 (Official build) dev (64-bit)
Screen reader : NVDA
NVDA Version: 2020.3

**Attachment:**
[NVDA behaviour on Menu item.zip](https://github.com/nvaccess/nvda/files/5956525/NVDA.behaviour.on.Menu.item.zip)

Does the issue still occur after restarting your computer?  YES
Have you tried any other versions of NVDA? If so, please report their behaviors. YES at 2020.2
If addons are disabled, is your problem still occuring? YES
Did you try to run the COM registry fixing tool in NVDA menu / tools? No

**Comment by akash07k** [comment]
Your test URL is not in public domain. it is not being resolved.
Secondly, will be better if you describe your bug properly than
describing it like bug writing bots.
Even I'm unable to understand anything from the provided video.

**Comment by akash07k** [comment]
Also,
your MAS reference URL is also not in public domain.
I think this bug should be closed right away.
Invalid bug

**Comment by ashish315** [comment]
Closing as per discuss with @akash07k
