### ISSUE TITLE
NVDA With Microsoft office Outlook 2007

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1207]
**Reported by vkulkarni on 2010-11-18 12:10**
When reading message(s) in Microsoft outlook 2007, both NVDA and Outlook will Stop working.

**Comment by leonardder** [comment]
This looks quite abandoned. Closing this, not yet sure about the label though.

**Comment by jcsteh** [comment]
I tend to label issues without sufficient issue as invalid (and have now done that here).
