### ISSUE TITLE
windows server inside vm ware player

### ISSUE THREAD

**Issue by StarTrekCafe** [nvaccess/nvda#12085]
hi. when using nvda, inside v mware player for my networking course last year and using windows server 2012 r2 and 2019 essentials. the audio service would not enable using the keyboard and had to either get sighted help from my trainer or disability answer desk. so is there going to be a feature for nvda, to then if i use it and then install say windows server 2022 stable release when it comes out or 2019 which is current version, wish nvda would then enable the audio and turn on audio and then give me speech when i click on the setup for windows server. thanks.

**Comment by josephsl** [comment]
Highly unlikely for servers, as the trend is remote management, not a local console login.

**Comment by lukaszgo1** [comment]
This issue is not specific enough to be actionable and also it is not an NVDA problem. You need to install either with Narrator for Server 2019 or using TWPE / unattended install for earlier versions and then enable audio service after installation.

**Comment by StarTrekCafe** [comment]
Hi well will be using windows server under vm ware player.

So not sure if can do remote management there. When I tried a dp. Would not connect, and had the correct credentials.

Thanks.

**Comment by Adriani90** [comment]
@StarTrekCafe do you still have this issue in NVDA 2024.3 Beta?

**Comment by Adriani90** [comment]
We didn get updates from the initial author upon request since more than 3.5 years, closing as abandoned. If you are still having this issue, please comment and we can reopen.
