### ISSUE TITLE
Read out is odd in bulleted list of multiple lines in Google document with braille support on

### ISSUE THREAD

**Issue by minakononogaki** [nvaccess/nvda#12081]
### Steps to reproduce:
1. Open Google Chrome(beta, canary). Open Google Document.
2. In the application, Tool (Alt+T), Accessibility settings. Check "Turn on screen reader support" and "Turn on braille support".
3. Format (Press Alt+F2 then right arrow key 4 times), Bullets & numbering, Bulleted list, then select one. Write long phrase so that the phrase in the first bullet goes over 2 lines.
4. Move the cursor by up or down key to go to the top of the second line of the first bullet. 

### Actual behavior:
The phrase of the first bullet is read out from the top of the first line to the end of the bullet phrase.

### Expected behavior:
The phrase of the first bullet is read out from the top of the second line, on which the cursor is located.

The sample file URL (editable: please take care not to change the content)
https://docs.google.com/document/d/1ZpP_zpviR59QPeKG9YPuopP6YffoWugnaBIXgOd1fp8/edit?usp=sharing

#### Name and version of other software in use when reproducing the issue:
Google Chrome
Beta 89.0.4389.47
Canary 90.0.4420.0
(it does not occur in Chrome Official 88.0.4324.182)

Braille display: Orbit Reader 20

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes. 2017.3jp and 2019.2.1jp. The behaviors are the same.
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes

**Comment by Adriani90** [comment]
@minakononogaki is this issue still occuring with NVDA 2023.2?

**Comment by Adriani90** [comment]
We don't have any updates from the initial author since more than 2.5 years, I am closing as abandoned. Please comment if you are still having this issue and we can reopen.
