### ISSUE TITLE
ICloudServices causing NDVA to report "UIThread" when using NVDA search in browsers (Chrome / Firefox)

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#12093]
### Steps to reproduce:

1. Use NVDA Alpha snapshot
2. In Chrome or Firefox, us NVDA+control+f to find text.
3. Press NVDA+F3 until the end of the document is reached.
4. Press ENTER on the "OK" button to acknowledge no further occurences.

### Actual behavior:

The search behaves as expected, but after acknowledging the end of the search at step 4, NVDA reports "UI Thread".  In some cases this does not happen the first time, but the second or third time a search is conducted.

In testing with "MSAA" checked in the Debug section of NVDA's advanced settings, @michaelDCurran determined this seemed to be caused by Apple's ICloudServices.

### Expected behavior:

UIThread should not be reported.

#### NVDA version:

 NVDA version alpha-21781,71c385ea
(Advised has been happening for the last few versions)

#### Windows version:

Windows version 10.0.18363

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes reported that this occurs in recent alpha snapshots.

#### If addons are disabled, is your problem still occuring?

yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Developer Info:

IO - inputCore.InputManager.executeGesture (11:23:23.056) - winInputHook
(14764):
Input: kb(laptop):NVDA+f1
DEBUG - gui.contextHelp.bindHelpEvent (11:23:23.099) - MainThread (19620):
Did context help binding for LogViewer
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo
(11:23:23.434) - MainThread (19620):
Developer info for navigator object:
name: 'UIThread'
role: ROLE_UNKNOWN
roleText: None
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.IAccessible.ContentGenericClient object at
0x072816F0>
Python class mro: (<class
'NVDAObjects.IAccessible.ContentGenericClient'>, <class
'NVDAObjects.IAccessible.IAccessible'>, <class
'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class
'documentBase.TextContainerObject'>, <class
'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>,
<class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: None
location: RectLTWH(left=0, top=0, width=0, height=0)
value: ''
appModule: <'appModuleHandler' (appName 'icloudservices', process ID
17336) at address 65cf790>
appModule.productName: 'AppleInc.iCloud'
appModule.productVersion: '12.0.188.0'
TextInfo: <class 'displayModel.DisplayModelTextInfo'>
windowHandle: 66620
windowClassName: 'ATL:001383C8'
windowControlID: 10836696
windowStyle: 1442840576
extendedWindowStyle: 0
windowThreadID: 17332
windowText: 'UIThread'
displayText: ''
IAccessibleObject: <POINTER(IAccessible) ptr=0x504f568 at 39a5f80>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=66620, objectID=-4, childID=0
IAccessible accName: 'UIThread'
IAccessible accRole: ROLE_SYSTEM_CLIENT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE,
STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: None
IAccessible accValue: None

**Comment by josephsl** [comment]
Hi, can we confirm that this invisible window is gone when iCloud Services executable is terminated?

**Comment by seanbudd** [comment]
Hi,

I'm having trouble reproducing this issue. 

I noticed that the iCloud version is used to test (12.2.10.0) is newer than the one which is logged (12.0.188.0). Is it possible to update iCloud and see if this problem is fixed?
Additionally, I'm using the latest NVDA alpha build: `alpha-21805,8e3657db`

If this problem still persists on the newer iCloud version and NVDA build, do you mind sharing

* iCloud configuration - do you use the Bookmarks and Password synchronization?
* does the webpage have any form data that would have been saved with iCloud Passwords?
* was iCloud installed through the Windows store?

Regards,
Sean

**Comment by Adriani90** [comment]
There are no updates and additional info provided upon request since more than 3 years from the initial author. Closing as abandoned. If this is still an issue, please provide the information and we can reopen.
