### ISSUE TITLE
Outlook 2019 crashes if you try to open an invitation to accept in Inbox when NVDA is Running

### ISSUE THREAD

**Issue by blinddark** [nvaccess/nvda#12098]
First of all: If NVDA isn't running, all works fine with the incoming invitation. If I use Microsoft speech or JAWS for Windows this issue doesn't come.
### Steps to reproduce:
NVDA is Running and Office 2019 STD installed. Office 2019 Has all updates that was released out due to 17.02.2021. Start Outlook and Click at the incomming Mail with a new invitation to read the Text and accept or decline it
### Actual behavior:
Outlook crashes and you have to reopen it.
### Expected behavior:
The invitation should be opened and i should read the Text.
#### NVDA installed/portable/running from source:
NVDA installed from https://www.nvaccess.org
#### NVDA version:
2020.4
#### Windows version:
Windows 10 2020 H2 professional with all Updates released until February 2021
#### Name and version of other software in use when reproducing the issue:
Outlook 2019 installed with Office 2019 Standard Updates released until February 17 2021
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes installed NVDA 2020.2 NVDA 2020.3 and try with NVDA Portable Always the same issue
#### If addons are disabled, is your problem still occuring?
Yes i disabled all addons and the Problem still occurs
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes that didn't fix the issue. I Also complete reinstalled NVDA 
[nvdadebug_outlook.txt](https://github.com/nvaccess/nvda/files/6042648/nvdadebug_outlook.txt)

**Comment by Adriani90** [comment]
@blinddark do you still have this issue in NVDA 2023.2?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author upon request since more than 3 years, I am closing as abandoned. If you are still having this issue, please comment and we can reopen.
