### ISSUE TITLE
NVDA reads out "blank" for table cells after reading the cell's data

### ISSUE THREAD

**Issue by deepakavvari** [nvaccess/nvda#12095]
NVDA is reading out "blank" when hit down arrow after reading the contents of the cells in tables in red mode. This is highly inconsistent. It is not happening for every cell of every table in the application and it is not happening every time we use NVDA.
I tested it with Windows+Chrome and Windows+Firefox.
I tried disabling CSS for the entire application to rule out the possibility of CSS being the culprit. The issue persists even with the CSS disabled.
I changed the markup to match the standard two headers table markup provided here- https://www.w3.org/WAI/tutorials/tables/two-headers/ . The issue still exists.

### Steps to reproduce:
JsBin: https://jsbin.com/wedaronebi/edit?html,output
Go to the sample code I provided and start NVDA. Navigate through the table in red mode.

### Actual behavior: 
NVDA sometimes reads "blank" when pressed down arrow after reading out the contents of the cell in a table when navigating through the table.

### Expected behavior: 
NVDA should just read the contents of the current cell and move on to read the contents of the next cell when hit down arrow.

#### NVDA version: 
2020.4

#### Windows version: 
Windows 10.0.18363

#### Other information about your system:
@angular/cli: @10.2.0
@angular-devkit/core: @10.2.0
typescript: @3.9.7
Chrome: @88.0.4324.182
Firefox: @85.0.2

#### Does the issue still occur after restarting your computer?
Yes

**Note**: This is an angular project. In the sample code I provided, I had to remove the custom component tags and classes because they won't make any difference here. But I did leave the structure intact. That is why the code has many divs inside table elements (they used to be components). I still faced the issue with this sample code. So that might conclude angular had no play in this.

**Comment by ZakBrownNutmeg** [comment]
Thanks for raising this, @deepakavvari. I too am having the same issue navigating a table with NVDA.

### Steps to reproduce:

1. Go to the table on [this page](https://www.nutmeg.com/lifetime-isa/help-to-buy-isas-and-the-lifetime-isa)
2. With NVDA in _Browse mode_ navigate through the table

When navigating through the cells, NVDA will _sometimes_ focus the cell twice:

* The first time it reads out the contents of the cell
* The second time it focuses the entire cell and reads out the word "Blank"

I haven't worked why it only does this sometimes. I can't see a pattern.

### HTML structure
In my case we have `td` elements with the following simplified structure:

```html
<td>
  <p>
    some text
  </p>
</td>
```

After having a dig I reckon removing the `p` tag, and just using a text element, would solve the issue, but this isn't optimal. Nested elements inside a `td` element is permitted.

I'm on version 2022.3.2 of NVDA.

@deepakavvari , did you discover any other work around for this?

**Comment by Adriani90** [comment]
I can reproduce this when navigating with arrow keys cell by cell through the table, but not when navigatinv with ctrl+alt+arrow keys column by column or row by row.

I think the browser might render and expose the distance between the <p></p> tags as blank lines when pressing arrow up and down or as space characters when pressing right and left. 
In Firefox 111 this is not reproducible.
Could you  please also fill a bug in Chromium for this and reference there this issue?

**Comment by Adriani90** [comment]
This seems fixed in Chromium canary 133 with NVDA 2024.4.1. Closing as works for me. if you are still having this issue, please comment and we can reopen.

**Comment by sxurik** [comment]
I can still reproduce the issue using the latest versions of Chrome and NVDA.
That's what I see when I follow steps to reproduce from the initial comment:

<img width="719" height="762" alt="Image" src="https://github.com/user-attachments/assets/ca368d0a-8ab3-4be5-bf98-915f5f9f7e39" />

сс @Adriani90
