### ISSUE TITLE
nvda hides the last character in object navigation in some parts of the windows settings screen 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12099]
### Steps to reproduce:
I'm using the notebook layout on nvda
open windows settings
open system
and now open about
sorry i haven't figured out yet how to properly explain the palaces below:
use object navigation on this screen commands
nvda + shift + left and right arrows until you hear processor
now read the word processor using
nvda + right arrow
the last character r is not read by nvda, I dare:
the penultimate character o and then the right word.

now press nvda + shift + right arrow to hear your processor name
now i will describe what happens on my computer:
daring
Intel (R) Core (TM) i3-1005G1 CPU @ 1.20GHz 1.19 GHz
now I used the commands to read word by word what I just heard:
nvda + ctrl + right arrow
I can even read the word
cpu
what is written after cpu I can't read with ctrl + nvda + right arrow nvda keeps talking cpu
I used nvda + right arrow and managed to read the rest of what is written:
@ 1.20GHz 1.19
### Actual behavior:
como tentei esplicar a ssima há dois problemas:
ao usar nvda + seta a direita o último caractere de uma palavra não é lido como no caso que consigo ler até a letra o da palavra processador.
e onde não consigo ler todas as palavras usando nvda + ctrl + seta a direita, como no exemplo ousso até a palavra cpu. 
### Expected behavior:
esperaria ler o último caractere de uma palavra e esperaria ler todas as palavras.
isto acontesseu em algumas outras partes desta janela, mais do mesmo modo não pude replicar em outras partes desta janela 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-21790,b4087a2c

#### Windows version:
10.0 21h1 19043.844
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by Adriani90** [comment]
Closing in favor of #13302 which contains some more discussion.
