### ISSUE TITLE
NVDA 20.4 and google sheets in Microsoft Edge

### ISSUE THREAD

**Issue by dTolmachev1** [nvaccess/nvda#12102]
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

**Comment by Adriani90** [comment]
The issue template is not filled, I am closing this one
