### ISSUE TITLE
NVDA say heading level 1 twice on long <h1> content

### ISSUE THREAD

**Issue by rpcorr** [nvaccess/nvda#12104]
### Steps to reproduce:

Let NVDA read the page

### Actual behavior:

NVDA say heading level 1 twice before finishing the <h1> content when heading has more than 17 words

### Expected behavior:

NVDA should only say level 1 once

#### NVDA version:
2020.4

#### Windows version:

Windows 10

#### Name and version of other software in use when reproducing the issue:

Happens in:

 Chrome Version 88.0.4324.150
 Firefox 84.0.2 (64-bit)
 Microsoft Edge Version 88.0.705.74
 IE Version 1909 (OS Build 18363.1377)

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes

**Comment by XLTechie** [comment]
If you read line by line with the arrow keys, does the heading appear across 
multiple lines?

Will you please provide an example website, and the text of the heading that 
does this?

Although I think you may be hearing a heading which spans multiple lines.

**Comment by rpcorr** [comment]
XLTechie,

Thanks for reaching out to assist.  Yes, the heading spans multiple lines as it is the title of a news story.

The page I am working on is in development and is not visible to the public at this moment.  I created an [example using Lorem ipsum](http://ronancorr.com/heading-levels-repeats/), and NVDA treats it the same way.   

If you let NVDA read the page when you load it, you'll hear "heading level 1" twice.   It appears to happen when one uses the arrow keys to continue reading (hearing).  I also have a level 2 heading, and the same thing occurs.

In the third example, I am using a level 3 heading and have placed a <br aria-hidden=true> attribute, but that doesn't help.

The only logical explanation I can think of is the headings are too long.  When searching the web, it is recommended that the H1 tag should be between 20-70 characters and that it should only take up one line.

**Comment by bramd** [comment]
I think this is expected behavior when the heading spans multiple "virtual" lines in NVDA's presentation of the website. You could change the line length in browse mode settings to se this effect. However, I notice NVDA also does this during say all as you describe (automatically on page load or triggered by nvda+downArrow). Since in say all it's not really clear when a line begins/ends, it might be better to say heading level x end "end heading" for long headings. This might be a feature request.
