### ISSUE TITLE
Windows language change selections (WINDOWS+SPACEBAR) not correctly read.

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#12100]
### Steps to reproduce:

1) Have at least two languages installed in Windows.
2) Ensure "Speech interrupt for typed characters" is enabled in NVDA's keyboard settings (NVDA+control+k, alt+i to toggle, enter).
2) Press and hold the WINDOWS KEY down.
3) Tap the SPACEBAR to change languages and release only the spacebar.
4) Before NVDA has finished reading the full details of this language, press SPACEBAR again.
5) Keep tapping SPACEBAR until back on the original language.

### Actual behavior:

a) At step 4 (pressing spacebar to move to the next language), NVDA keeps reading until it is finished reading the current language and then reads any subsequent languages mvoed to or past.  The keyboard action is processed by Windows - the highlight moves to the next language immediately, however it is also not recorded in NVDA's log (when the log level is set high enough to record keystrokes):

IO - inputCore.InputManager.executeGesture (10:07:37.867) - winInputHook (11984):
Input: kb(desktop):windows+space
IO - speech.speak (10:07:37.893) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'space', EndUtteranceCommand()]
DEBUGWARNING - IAccessibleHandler.internalWinEventHandler._shouldGetEvents (10:07:38.017) - MainThread (8052):
Foreground took too long to change. Foreground still 262168 (Shell_TrayWnd). Should be 4458766 (Shell_InputSwitchTopLevelWindow)
IO - speech.speak (10:07:38.201) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'English (United States) - US keyboard', 'US keyboard']
IO - speech.speak (10:07:48.679) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'Japanese - Microsoft IME', 'Microsoft IME']
IO - speech.speak (10:07:49.540) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'French (France) - French keyboard', 'French keyboard']
IO - speech.speak (10:07:50.231) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'German (Germany) - German keyboard', 'German keyboard']
IO - speech.speak (10:07:50.730) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'Bengali (India) - Bangla – INSCRIPT keyboard', 'Bangla – INSCRIPT keyboard']
IO - speech.speak (10:07:51.306) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'Spanish (Mexico) - Latin American keyboard', 'Latin American keyboard']
IO - speech.speak (10:07:51.921) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'English (Australia) - US keyboard', 'US keyboard']
IO - speech.speak (10:07:53.154) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'Taskbar']
IO - inputCore.InputManager.executeGesture (10:07:56.906) - winInputHook (11984):
Input: kb(desktop):NVDA+f1

Also note, with "Report object descriptions" enabled in NVDA's object presentation settings, when reading any language, NVDA reads the keyboard information twice.

### Expected behavior:

With speech interrupt for typed characters enabled, NVDA should immediately stop reading the old language and start reading the newly selected language when NVDA+spacebar is pressed a second or subsequent time.

#### NVDA version:

NVDA 2020.4 installed.

#### Windows version:

Windows 10 (64-bit) Version: 2009, Build: 19042 

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Also tested with temporary copy of NVDA alpha-21790,b4087a2c (latest alpha as at 26/2/2021)

#### If addons are disabled, is your problem still occuring?

Yes - no add-ons.

**Comment by nidza07** [comment]
I can reproduce this, and have also reported it as #11058
It's quite  annoying, and hopefully it can be addressed.

**Comment by Qchristensen** [comment]
Sorry @nidza07, I didn't notice your issue when I created this.  I've copied some additional information from this issue (the log) over to #11058 and I'll close this issue now as a duplicate
