### ISSUE TITLE
Bug when deleting line break character in IBM Lotus Symphony Documents

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1210]
**Reported by m11chen on 2010-11-20 09:36**
Steps to reproduce:
Open a new IBM Lotus Symphony document.
Type a single line of text.
Press return to start a new line.
Type some text into the second line.
Press Ctrl+Home and then End to go to the end of the first line.
Press delete to remove the line break between the first and second line.

Expected result:
NVDA should now be able to read the content of the two lines by character using left and right arrow keys.

Actual result:
NVDA speaks "Root pane", and then nothing when pressing left or right arrow.  You could regain focus of the editable text field by pressing up or down arrow, but it seems that some errors are generated along the way even though no error sound is played

**Comment by leonardder** [comment]
Although this ticket is quite abandoned and I was about to close it, I was able to reproduce strange behaviour in LibreOffice given the steps above. It seems the focus moves to an unknown object for a short amount of time and than the document gets the focus back.

**Comment by Adriani90** [comment]
I suggest to open a new issue specifically for Libre office if needed. Lotus Symphony has been discontinuedin 2012 accorting to this article:
https://en.wikipedia.org/wiki/IBM_Lotus_Symphony

I am quite sure that there are hardly any companies using Lotus symphony. Most of them changed their suites to more stable software with further support.
I am closing this as abandoned.
