### ISSUE TITLE
nvda is not reading line by line emails when using the native windows 10 email application 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12117]
### Steps to reproduce:
open an email in the native email app on windows 10 to view emails
walk with the arrow below to read the email line by line. 
### Actual behavior:
nvda keeps repeating the current line with the focus. 
### Expected behavior:
nvda should read the email line by line 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-21810,db664bef

#### Windows version:
10.0.19043.844
#### Name and version of other software in use when reproducing the issue:
HxOutlook.exe, microsoft.windowscommunicationsapps 16005.13426.20688.0

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If add-ons are disabled, is your problem still occurring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no
log:
[email.txt](https://github.com/nvaccess/nvda/files/6085236/email.txt)

**Comment by josephsl** [comment]
Hi,

Confirmed - traced to tree interceptor changes introduced in #12051. CC @MichaelDCurran

**Comment by lukaszgo1** [comment]
@fernando-jose-silva Is this still reproducible for you?

**Comment by fernando-jose-silva** [comment]
yes the problem is still reproducible.
I found out that the problem is due when opening an email the nvda is not automatically going into browsing mode.
If I open an e-mail to force the navigation mode with nvda + space everything works fine.
It is an annoying problem, since every open email you need to go to browsing mode.
This is a regression of the alpha versions.
Checking the option in the autofocus mode when the focus changes has no effect on this problem.
Thanks.

**Comment by lukaszgo1** [comment]
@michaelDCurran  Ping. Would it be possible to look into this before 2021.1 as it is clearly a regression.

**Comment by michaelDCurran** [comment]
Yes, this will get done before 2021.1.
