### ISSUE TITLE
Bug when correcting spelling error in IBM Lotus Symphony Documents

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1211]
**Reported by m11chen on 2010-11-20 10:03**
Steps to reproduce:
Open a new IBM Lotus Symphony document.
Type a first line of text with something misspelled.
Press Return and type a second line of text.
Move the caret back to the first line of text to the spelling error.
Press ExtendedApp to open the context menu and correct the spelling with the list of suggestions.

Expected result:
The spelling should be corrected and pressing left or right arrow would allow NVDA to speak the line by character.

Actual result:
NVDA does not speak when pressing left or right arrow.  However pressing down arrow would allow NVDA to regain focus to the editable text.

**Comment by leonardder** [comment]
Can't reproduce with the newest libre office, which IA2 code is based on Symphony. Closing, but please provide additional details if you have them available.
