### ISSUE TITLE
wxPython 4.1.1: Binary versions of NVDA crashes on Windows 8.1 and earlier.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#12116]
### Steps to reproduce:
1. Download a try build from PR #12075 
2. Try to execute downloaded launcher on Windows 8.1, Windows Server 2012 or Windows 7 SP1.

### Actual behavior:
NVDA startup sound plays and the Windows display a dialog informing that NVDA Aplication has stopped working.
[Dump file from NVDA](https://drive.google.com/file/d/1crN7drWPOojmZPrN_nFnSY0dluFygPhc/view?usp=sharing)
[nvda-old.log](https://github.com/nvaccess/nvda/files/6083188/nvda-old.log)

### Expected behavior:
NVDA should work normally.

#### NVDA installed/portable/running from source:
Running from launcher and portable - no problems when running from source on the same machines.

#### NVDA version:
nvda_snapshot_try-py3.8_venv-21812,b834a4e6

#### Windows version:
Windows 7 SP1, Windows Server 2012, Windows 8.1
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Versions using WxPython 4.0.3 works okay.

#### If add-ons are disabled, is your problem still occurring?
Yes -- tested with a clean config

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
N/A

# #Additional info:
I've finally tracked it down to two things:
1. WXPython 4.1.1 - if I build the launcher with wxPython 4.1.0 there is no crash.
2. Version of Universal CRT bundled in the launcher - if I don't bundle these libraries or bundle different versions of them (see below) NVDA starts properly. Note that it does not matter if the machine in question has Universal CRT installed or not since according to the [Microsoft help page about dll search order](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications) directory of the current application always has precedence over dll's bundled with Windows.

## Possible solutions:
Ideally we should get to the bottom of this problem and understand why wxPython 4.1.1 causes a crash with the version of the Universal CRT that we bundle. I don't know if the dump above is sufficient to debug further - my  experience with using a debugger is almost non existent it'd be great if someone more experienced could take a look at it. If this proves not to be easily fixable I see a few possible solutions:
### Use different version of the Universal CRT
I've discovered that using Universal CRt libraries from Windows 10 SDK 18362 or later works around this issue. This is in contrast which what Microsoft recommends for applications which need to bundle these libraries but it seems to work. Since I do not really understand why it works it is hard to recommend it as a solution.
### Don't bundle Universal CRt with NVDA.
This also solves the problem but causes NVDA not to work on machines without Universal CRt i.e. clean installs of Windows so it also isn't very appealing.
### Use wxPython  4.1.0
As described above this crash does not occur with 4.1.0 which is compatible with Python 3.8.

**Comment by lukaszgo1** [comment]
cc @michaelDCurran @feerrenrut

**Comment by josephsl** [comment]
Hi, we may need 4.1.1 due to localization initialization changes that affects NVDA. Thanks.

**Comment by seanbudd** [comment]
wxPython 4.1.1 pulled in an unreleased master branch of wxWidgets, so I think it's likely the bug lies within wxWidgets

**Comment by michaelDCurran** [comment]
@lukaszgo1  can you explain exactly what files / how you tested with the universal SRT from a Windows 10 sdk later than 18362? If I understand correctly, we currently copy them from Visual Studio, and not the Windows 10 SDK.

**Comment by lukaszgo1** [comment]
To be honest I've no idea from where exactly were copying them now. [Microsogt web page on the subject](https://devblogs.microsoft.com/cppblog/introducing-the-universal-crt/) gives the path that I've used when writing #10347 and it points to a Windows SDK directory even though it seems to be installed as part of Visual Studio. To make matters more complicated on my other system where I have only VS 2019 installed this path is not present at all.
As to how I've tested with later versions of the Universal CRT:
1. Removed all api*.dll and ucrtbase.dll from the NVDA folder.
2. Installed Windows 10 SDK version 18362 using Visual Studio installer.
3. Copied files from C:\Program Files (x86)\Windows Kits\10\Redist\10.0.18362.0\ucrt\DLLs\x86 to the NVDA folder.

**Comment by josephsl** [comment]
Hi, is this also the case with SDK 10.0.19041? I bet Visual Studio 2019 (the version we use to build NVDA on AppVeyor) uses 10.0.17134, whereas on my system, the Universal C Runtime version is 10.0.17713 (ideally it should have been 17763, but well). Thanks.

**Comment by leonardder** [comment]
I wonder whether we could rely on py2exe to provide us the Universal CRt automatically, though I recall that caused some issues in the past. It will probably use a random crt anyway
Using the sdk version instead of the one bundled with VS might be a better approach.

**Comment by michaelDCurran** [comment]
Adding a bit of debugging to look at the include directories during a 
build on appveyor, it looks like sdk 10.0.19041 is in use.


According to source/setup.py: It looks like we try to actually exclude 
all the api-ms-win-*.dll files, as including them can cause problems on 
some Operating System versions. Though clearly we are still including 
them, so I guess that monkeypatch is not currently working in Py2exe. 
Though it looks like recent stable builds of NVDA have also included 
these, so I'm not sure exactly when that broke?

Yet, even though it did break, it obviously wasn't causing too much of a 
problem until now...

So first, we could try getting that code to work correctly again.

And then if needed, we can copy them from the sdk.

**Comment by josephsl** [comment]
Hi, I’m in favor of Leonard’s suggestion – besides, it aligns with project readme in that we ask folks to use latest public SDK (10.0.19041 as of March 2021). Thanks.

**Comment by lukaszgo1** [comment]
> According to source/setup.py: It looks like we try to actually exclude
all the api-ms-win-*.dll files, as including them can cause problems on
some Operating System versions. Though clearly we are still including
them, so I guess that monkeypatch is not currently working in Py2exe.
Though it looks like recent stable builds of NVDA have also included
these, so I'm not sure exactly when that broke?

It isn't broken - the code that copies these to the NVDA distribution has been introduced by  me in #10347 to fix #10031

**Comment by lukaszgo1** [comment]
> 
> 
> I wonder whether we could rely on py2exe to provide us the Universal CRt automatically, though I recall that caused some issues in the past. It will probably use a random crt anyway

It'll copy whatever version of the CRT is installed in the system, so to me it looks like an accident waiting to happen.

> Using the sdk version instead of the one bundled with VS might be a better approach.


This is contrary to what Microsoft recommends (see the blog post to which I've linked above). Also since we don't know which version of Universal CRT works and which doesn't (for instance copying these libraries from SDK 17763 also causes a crash) I'd be cautious to copy latest versions of them without understanding the real cause of the problem. At a minimum it would be good to have a system test which verifies that NVDA can successfully start on Windows version older than Win 10.

**Comment by michaelDCurran** [comment]
On appveyor: these files are being copied from: C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x86\
On my system this path does not exist. 
We should probably add the ProductVersion key into this path like so:
C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x86\

**Comment by michaelDCurran** [comment]
Can somebody  please test the following try build on Windows 7 and or Windows 8 and let me know if it runs okay?
https://ci.appveyor.com/api/buildjobs/g6altrqhcrr5ci2s/artifacts/output%2Fnvda_snapshot_try-py3.8_venv-21858%2C9ab0f6df.exe
This is pr #12075 now copying the CRT dlls from the most recently installed version of the sdk. On Appveyor this is 10.0.19041. 
We are certainly considering how we can test on Windows 7 or Windows 8 in the future. We may be able to run the tests on Appveyor's Windows server 2012 image, though coming up with the right yaml configuration to build on Windows server 2019 and then somehow get the build over to a windows server 2012 job for testing is something we'll need to think about.

**Comment by josephsl** [comment]
Hi, it runs on Windows 8.1. Thanks.

**Comment by lukaszgo1** [comment]
> 
> 
> Can somebody please test the following try build on Windows 7 and or Windows 8 and let me know if it runs okay?
> https://ci.appveyor.com/api/buildjobs/g6altrqhcrr5ci2s/artifacts/output%2Fnvda_snapshot_try-py3.8_venv-21858%2C9ab0f6df.exe

I can confirm this build works correctly on a Windows 7 - both my main machine and a clean install, and on Windows  Server 2012.

> We are certainly considering how we can test on Windows 7 or Windows 8 in the future. We may be able to run the tests on Appveyor's Windows server 2012 image, though coming up with the right yaml configuration to build on Windows server 2019 and then somehow get the build over to a windows server 2012 job for testing is something we'll need to think about.



An alternative idea would be to use Server 2012 R2 image and install VS 2019 community on it our selves.

**Comment by zahra21** [comment]
hi.
i downloaded the snapshot version from:
https://ci.appveyor.com/api/buildjobs/g6altrqhcrr5ci2s/artifacts/output%2Fnvda_snapshot_try-py3.8_venv-21858%2C9ab0f6df.exe
installed it on windows seven and i confirm that it worked for me without any error when installing!
