### ISSUE TITLE
Audio player controls in webpages not focused correctly

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#12132]
### Steps to reproduce:

1. Go i.e. [here](https://www.ilpost.it/2021/03/07/suoni-origine-sconosciuta/) (sorry, it's in Italian);
2. Search audio player element (or 2nd result for "upsweep" and see upward);
3. Try to interact with player.

### Actual behavior:

You are able to enter in the player (pressing return where NVDA says "Audio Player application") and focus controls (Play button, slider...), but not to exit with esc (you have to use tab or shift+tab, landing on a link or other page element out of player).

### Expected behavior:

In my opinion, controls should be in the page as usual, like buttons, sliders etc.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

NVDA version alpha-21810,db664bef

#### Windows version:

Windows 10 20H2, build 19042.804.

#### Name and version of other software in use when reproducing the issue:

Firefox 86.0, Chrome 89.0.

**Comment by jcsteh** [comment]
The page is using ARIA role="application" on the audio player controls. Both NVDA and the browser are behaving as expected here. This is not really an appropriate use of role="application".

That said, you can escape it with NVDA+control+space.
