### ISSUE TITLE
Python 3.8:  Impossible to navigate in Windows Explorer under Windows Server 2012.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#12154]
### Steps to reproduce:
1. Launch recent Alpha based on Python 3.8
2. Open run dialog with Windows + R, type `%temp%` press enter and attempt to navigate in the newly opened folder.

### Actual behavior:
Windows error sound plays and NVDA crashes and restarts. If the folder view is still focused after restart NVDA crashes again.

### Expected behavior:
Windows Explorer should be navigable with NVDA
#### NVDA installed/portable/running from source:
Tested with both portable and installed
#### NVDA version:
alpha-21882,528d5708
#### Windows version:
Windows Server 2012.
#### Name and version of other software in use when reproducing the issue:
Windows Explorer
#### Other information about your system:
None relevant.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2020.4 works okay, latest Python 3.7 based Alpha works okay.

#### If add-ons are disabled, is your problem still occurring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes with no effect.

The attached zip file contains log at debug level and NVDA crash dump file.
[crash.zip](https://github.com/nvaccess/nvda/files/6123381/crash.zip)

**Comment by leonardder** [comment]
Do you have Enable selective registration for UI Automation events and property changes enabled? If so, how does this behave when that's off?

**Comment by lukaszgo1** [comment]
> 
> 
> Do you have Enable selective registration for UI Automation events and property changes enabled? If so, how does this behave when that's off?


No, I don't. Enabling selective event registration made the crash way less frequent but it still occurs from time to time.

**Comment by leonardder** [comment]
Can this be reproduced with the build from https://github.com/nvaccess/nvda/pull/12155 ?

**Comment by lukaszgo1** [comment]
> 
> 
> Can this be reproduced with the build from #12155 ?

Yes, it still happens with this build.

**Comment by michaelDCurran** [comment]
Stack trace from crash dump:
```
 # ChildEBP RetAddr      
00 0623fcf0 723f3e68     UIAutomationCore!AutoRelease<IAccIdentity *>::~AutoRelease<IAccIdentity *>+0x11
01 0623fd24 724111de     UIAutomationCore!ClientIEventHandler<IUIAutomationPropertyChangedEventHandler>::OnEvent+0x135
02 0623fd40 7241125a     UIAutomationCore!EventRecord::CrossProcess_OnEvent+0x59
03 0623fd54 72410297     UIAutomationCore!EventRecord::CallbackAdapter::CrossProcess_OnEvent+0x13
04 0623fdb4 724103cd     UIAutomationCore!SavedEvent::OnMessage+0xd6
05 0623fddc 72411bba     UIAutomationCore!SavedEvent::DoWork+0x31
06 0623fdf0 72411b41     UIAutomationCore!WorkItemQueue::ThreadProc+0x6e
07 0623fdfc 771386e3     UIAutomationCore!WorkItemQueue::StaticThreadProc+0xd
08 0623fe08 77349e89     kernel32!BaseThreadInitThunk+0xe
09 0623fe4c 77349e5c     ntdll!__RtlUserThreadStart+0x72
0a 0623fe64 00000000     ntdll!_RtlUserThreadStart+0x1b
```

In short it looks like a UI Automation propertyChange event handler is freeing an IAccIdentity COM interface after it has already been freed.

IAccIdentity suggests this is MSAA being proxied by UI Automation. However, we have tried rather hard to stop UIA core from proxying MSAA, especially the mapping of winEvents to UIA propertyChange events, as NVDA already gets them from MSAA itself.

**Comment by michaelDCurran** [comment]
I have made a try build of NVDA downgraded to Python 3.7, but otherwise identicfal to NVDA master at time of this comment:
https://ci.appveyor.com/api/buildjobs/9j0yrsjmphluhd9n/artifacts/output%2Fnvda_snapshot_try-py37-22369%2C439dc27a.exe
Please give this try build a test and let me know if the issue no longer occurs.

**Comment by lukaszgo1** [comment]
@michaelDCurran  I can confirm that UIA controls are once again usable under Windows Server 2012 with the try build that you've posted above.
