### ISSUE TITLE
When testing with NVDA version alpha-21882, the input gesture interface could not be opened

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#12151]
### Steps to reproduce:
First open the NVDA Menu/Preferences submenu, then find the input gesture, and then enter to open the menu.
### Actual behavior:
This is when the NVDA error tone appears
### Expected behavior:
Can open the input gesture interface normally
#### NVDA installed/portable/running from source:
install version and Portable
#### NVDA version:
NVDA version alpha-21882,528d5708
#### Windows version:
Microsoft Windows [version 10.0.19042.867]
#### Name and version of other software in use when reproducing the issue:
none
#### Other information about your system:
none
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
none
#### If add-ons are disabled, is your problem still occurring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Not in the scope of this tool
log:
[nvda.log](https://github.com/nvaccess/nvda/files/6122148/nvda.log)

**Comment by josephsl** [comment]
Hi, caused by wxPython 4.1.1 changes to sizer calls (if I’m reading the log correctly). CC @feerrenrut

**Comment by feerrenrut** [comment]
Thanks for reporting. I believe we have a fix on the works for this. @seanbudd  could you please confirm?

**Comment by dingpengyu** [comment]
cc @michaelDCurran

**Comment by seanbudd** [comment]
This could be fixed the same way as the wxStaticBoxSizer issue, but I'd need to investigate further to confirm as the error is being thrown in the parent class wxBoxSizer. I'll test if the suggested usage in #12115 / https://trac.wxwidgets.org/ticket/19086 fixes this error.

**Comment by dingpengyu** [comment]
> This could be fixed the same way as the wxStaticBoxSizer issue, but I'd need to investigate further to confirm as the error is being thrown in the parent class wxBoxSizer. I'll test if the suggested usage in #12115 / https://trac.wxwidgets.org/ticket/19086 fixes this error.
Thank you for your note

**Comment by zstanecic** [comment]
I confirm this
the log states
ERROR - unhandled exception (22:33:34.752) - MainThread (8792):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 301, in onInputGesturesCommand
  File "gui\__init__.pyc", line 193, in _popupSettingsDialog
  File "gui\inputGestures.pyc", line 575, in __init__
  File "gui\settingsDialogs.pyc", line 158, in __init__
  File "gui\inputGestures.pyc", line 611, in makeSettings
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at ..\..\src\common\sizer.cpp(2168) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
NVDA version alpha-21895,52bf1ed6
