### ISSUE TITLE
User Guide: Remove references to Adobe Flash

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#12162]
### Is your feature request related to a problem? Please describe.

Throughout the User Guide, several mentions are given to Adobe Flash. Flash is now depricated, so it may be worth removing all mentions of this. References can currently be found towards the top of sections 6 and 6.4

**Comment by DrSooom** [comment]
See also: Issue https://github.com/nvaccess/nvda/issues/11131#issuecomment-753320290

**Comment by seanbudd** [comment]
Closed by #12207
