### ISSUE TITLE
Browse Mode - Find dialog: Add option to only search within the currently-focused element

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#12163]
### Is your feature request related to a problem? Please describe.

When reading through large documents/web pages in Browse Mode, it's sometimes necessary to find a string within the current element - as an example, a user may be trying to find a word, but only within the heading that they're currently reading. At present, when using the "Find Next/Find Previous" NVDA commands, there's no easy way of determining whether focus has jumped out of the element that the Find command was triggered from.

To combat this, my idea was to add a checkbox to the Find dialog entitled "Search within current element" (or similar); if checked, when performing an initial find or when using the Next/Previous commands, NVDA would only search within the current element. In terms of element types, I was initially thinking of including the current heading, list, frame, table and block quote. Would appreciate thoughts as to whether this would be a useful addition.

**Comment by Adriani90** [comment]
I think such a feature would be an overkill, the efficiency gains if this was possible are minimal, if at all. I don't see a real use case for this feature. NVDA already reports the role of the element in which the word is located, e.g. the heading. If you search for the next word occurance and you leave the heading role, NVDA will indicate the new role.

I am closing as not planned. If there is any storng use case for this, please comment and we can reopen.

**Comment by XLTechie** [comment]
I can imagine this being useful in specific circumstances like searching only in a table, on a page that contains multiple tables. I deal with many such software management interfaces myself.

Searching for a word in a heading is a bad example--headings are usually small.
The block level elements are a different story though: tables, lists, even divs, can be large enough to warrant such a feature.

But would most users even understand where or when to use it?

It is probably better done in an add-on for now, as I don't see a lot of people wanting this.
