### ISSUE TITLE
Braille: Inserting a newline doesn't make the cursor show a blank line in VS Code or Textareas in Chromium-based browsers

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#12179]
### Steps to reproduce:
1. In a Chromium-based browser, or in Visual Studio Code or any other Electron app, open a blank document or focus a textarea, and type some text.
2. Press Enter.

### Actual behavior:

The cursor continues to blink after the last typed character. Only if I start typing another character, the display goes blank and shows the new line with the newly typed character and the cursor blinking after it.

### Expected behavior:

The Braille display should show a blank line with the cursor blinking at the beginning.

**Comment by Adriani90** [comment]
Is this issue still reproducible in NVDA 2024.4 Beta and Chromium 130 or canary?

cc: @burmancomp, @Emil-18 can you please test?

**Comment by Adriani90** [comment]
We didn't hear any updates from initial author upon request since many years, I am closing as abandoned. if you are still having this issue, please comment and we can reopen.

**Comment by CyrilleB79** [comment]
It should be quite easy to check if this issue is still reproducible or not. @adriani90 have you done so?
