### ISSUE TITLE
Reading Epub files with Adobe Digital Editions

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#12173]
### Steps to reproduce:

(Note: Reported by a user - I can't reproduce on my system running Windows 10 (64-bit) Version: 2009, Build: 19042 and Adobe Digital Editions version 4.5.8.183423 or version 4.5.11.187303)

1. I set up NVDA so that all add-ons are disabled;
2. I then opened the download folder and selected the “Country Strong …..epub” file;
3. I pressed enter on the file and it opened cleanly in Adobe Digital Editions, which is the default;
4. I then deliberately pressed any other key rather than the left alt key, this may have been an arrow key and then the page down key but there was no response from Adobe. In fact, the program had become frozen and NVDA was silent.
5. I then pressed alt-tab to move away from Adobe, encase NVDA was still active and this proved to be the case;
6. I went back into the frozen Adobe and pressed alt-F4, which offered me the option of waiting or closing the program. I pressed “Close”;
7. I then went back to the download folder where the epub file was still in focus and pressed enter to open it;
8. This time, I went to Adobe and touched nothing else before pressing the left alt key;
9. This gave me the menu bar an, when I arrowed down the file list, everything was greyed out but the arrow key was able to move between the menus;
10. I forget now if I pressed any key to escape from the menu bar but you can see what I did in the log;
11. I now pressed the page down key and heard “Blank”. This was important because that meant that NVDA was interacting with the Adobe interface and another page down brought the text of the book into focus and now the whole book is available;

### Actual behavior:

As noted above, Adobe Digital Editions freezes on opening at step 4.
[NVDA.LOG](https://github.com/nvaccess/nvda/files/6138746/NVDA.LOG)

#### NVDA version:
NVDA 2020.4
#### Windows version:
Windows version 10.0.19041 
#### Name and version of other software in use when reproducing the issue:

Adobe Digital Editions 4.5.11

#### Does the issue still occur after restarting your computer?
Yes
#### If add-ons are disabled, is your problem still occurring?
Yes

**Comment by nvdaes** [comment]
Hello, though this should be fixed, you may want to recommend the user and even promote [Thorium Reader](https://github.com/edrlab/thorium-reader) by @edrlab, which currently supports EPUB, PDF, DAISY3 and other formats, searching text in the epub, table of contents and browse mode in NVDA.
Adobe Digital Edition is not recommended widely due to lack of fundamental accessibility features:

https://inclusivepublishing.org/rs-accessibility/

cc: @ways2read

**Comment by Brian1Gaff** [comment]
Yes digital editions was dumped over a year back for being so messy and 
prone to lock ups on other screenreders, ie the shark.  Its a shame we are 
still fighting this battle.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Adriani90** [comment]
Adobe actually discontinued further development of ADE years ago, and there were only two minor security updates during last 5 years. Adobe does not offer any assistance on ADE anymore. The only support is through online forums and the online help articles.
See these links for more information:
https://help.overdrive.com/en-us/0118.html
https://helpx.adobe.com/support/programs/adobe-support-policies-supported-product-versions.html
https://community.adobe.com/t5/digital-editions-discussions/is-digital-editions-discontinued/td-p/14494485

That being said, I am closing this issue as abandoned. I don't expect any further updates to the adobe digital editions regarding accessibility.
