### ISSUE TITLE
NVDA symbol reporting at review position: cut off on last character of emojis

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#12186]
Hi.

Steps to Reproduce:
1. Assign a gesture to the following command, as it is written in the input gestures dialog: Reports the symbol where the review cursor is positioned. Pressed twice, shows the symbol and the text used to speak it in browse mode collapsed. It has no default gesture.
2. Move to an emoji, or select an emoji using the emoji picker.
3. Press this command twice to show the emojis replacement in browse mode.

Expected: All characters of the emoji are shown.
Actual: The last letter of the emoji name is cut off.

NVDA version: 2020.4
Add-ons installed: Happens without them
Windows: 10 20H2
Other versions: None to test

**Comment by CyrilleB79** [comment]
First investigations:
It seems that `ui.browseableMessage` does not supports correctly wide characters.
Type the following in the console:
```
import ui
ui.browseableMessage('Hello\n🐎🐎🐎🐎\nGoodbye')
```
Result: the "Goodbye" word has been truncated.
This is reproducible with NVDA 2019.3 onward. The issue does not occur with NVDA 2019.2.1 (Python 2), provided that you encode the test string in UTF8 before passing it to `ui.browseableMessage`.

Probably something to dig in when passing the parameters from python to HTML/javascript. I am not an expert here so if someone wants to search further, go ahead!

PS: check your input when typing emojis in the console input; I have seen an annoying bug when copy/pasting an emoji at the end of the line and when writing further.

**Comment by CyrilleB79** [comment]
After having looked a bit more carefully to it, this issue seems to have be fixed by chance thanks to the rework made in my own PR #12005 that is already integrated in NVDA alpha.
I did not find however why this made it work now.

Could you please test [last NVDA alpha](https://ci.appveyor.com/api/buildjobs/2mkhu6c160dm5jqg/artifacts/output/nvda_snapshot_alpha-22012,3c1693dd.exe)?

If you confirm that it is solved, please close this ticket.

**Comment by fisher729** [comment]
I'm closing this ticket, as the issue has indeed been solved.

**Comment by fisher729** [comment]
I'm closing this ticket, as the issue has indeed been solved.
