### ISSUE TITLE
Several errors while opening Android Studio

### ISSUE THREAD

**Issue by akash07k** [nvaccess/nvda#12188]
### Steps to reproduce:
1. install latest Android Studio,
2. Install latest NVDA Alpha snapshot.
3. Open Android Studio now and notice.
### Actual behavior:
NVDA throws a tons of errors and hence makes a lot of error sounds
### Expected behavior:
Errors shouldn't be thrown
### System configuration
Windows 10 Build 21332, I7 16 GB ram
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Latest alpha
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Android studio latest
#### Other information about your system:
Please see the attached log
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes
[jab.txt](https://github.com/nvaccess/nvda/files/6158319/jab.txt)

**Comment by cary-rowen** [comment]
I'm using the latest Android Studio and the problem doesn't seem to occur anymore.
@akash07k can you reconfirm this?

The version information is as follows:
Android Studio Hedgehog | 2023.1.1 Patch 1
Build #AI-231.9392.1.2311.11255304, built on December 27, 2023
Runtime version: 17.0.7+0-b2043.56-10550314 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    com.intellij.zh (232.172)
    com.intellij.plugins.vscodekeymap (231.8109.91)

**Comment by akash07k** [comment]
Hi @cary-rowen  yes, I checked just now, it no longer happens. closing the issue
> I'm using the latest Android Studio and the problem doesn't seem to occur anymore. @akash07k can you reconfirm this?
> 
> The version information is as follows: Android Studio Hedgehog | 2023.1.1 Patch 1 Build #AI-231.9392.1.2311.11255304, built on December 27, 2023 Runtime version: 17.0.7+0-b2043.56-10550314 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Windows 10.0 GC: G1 Young Generation, G1 Old Generation Memory: 2048M Cores: 8 Registry: external.system.auto.import.disabled=true ide.text.editor.with.preview.show.floating.toolbar=false
> 
> Non-Bundled Plugins: com.intellij.zh (232.172) com.intellij.plugins.vscodekeymap (231.8109.91)
