### ISSUE TITLE
bug? NVDA no longer states "carriage return" in Notepad on line creation

### ISSUE THREAD

**Issue by TechHorseG** [nvaccess/nvda#12194]
NVDA portable 2020.4 / Win10 20H2

I have noticed that if the caret is on a blank line in Notepad and I press enter to create a new line, NVDA remains silent. Whereas in previous versions it would state something like "carriage return". I hope I am remembering the term correctly.

Is there any way to restore this verbal feedback? If I wanted to create 1 or more blank lines in a text file I would use this announcement to  easily ensure that the lines had been created. My enter key can sometimes stick.

Thanks.

**Comment by CyrilleB79** [comment]
Hello
I have tested with NVDA 2020.2 and NVDA 2020.4. Carriage return is not reported when inserted in notepad in neither of these versions.
Maybe you were used to report control keys and you disabled it by mistake?
To toggle reporting of control keys, press NVDA+4. The key to use is the 4 above the letters, i.e. above the 'E' key, not the 4 of the numpad.

**Comment by TechHorseG** [comment]
Thanks for response, but tried control keys and that is definately not it. I have never had NVDA tell me whenever I've press the enter key.

I used 2019.2.1 portable for several months, so maybe it was that version?

**Comment by XLTechie** [comment]
> I have noticed that if the caret is on a blank line in Notepad and I press enter to create a new line, NVDA remains silent. Whereas in previous versions it
> would state something like "carriage return". I hope I am remembering the term correctly.

Interesting. I have tried:
Recent alphas.
An early 2020 alpha.
2019.3.1
A beta of 2019.2
2017.3

Which are all the versions I had laying around.
And none of them exhibit the behavior you describe.

I would wonder if perhaps you are mis-remembering; an add-on was involved; or 
this was a very specific behavior in 2019.2.1 which did not exist before or 
since.

**Comment by TechHorseG** [comment]
I definately used to hear it, and as said would use it to count how many new blank lines I was creating.

Perhaps it was due to an old build of Win10. I have noticed some changes in what NVDA reads out after feature updates. For example, in Notepad NVDA would not read out  the word I had typed if I pressed enter immediately after it to move to a new line. Then after a feature update it began reading out the final word I typed on a line after pressing enter, which was much welcomed!

So perhaps the old behaviour I am remembering is more down to the version of Win10 I was using at the time, rather than NVDA itself?

Well, not the biggest loss in the world! Just found it useful. Maybe when feature requests are allowed again I'll request it. Thanks.

**Comment by XLTechie** [comment]
@josephsl do you have any memory about whether notepad might have changed in 
this regard?

I believe feature requests can be made, they just won't be acted upon for now. 
If you close this and open a feature request, I would suggest linking to this 
issue for context.

You might also email the add-ons list (https://groups.io/g/nvda-addons), and ask 
someone to write you an add-on for the purpose in the meantime.

**Comment by josephsl** [comment]
Hi, the biggest change to Notepad took place in 2018 when it added all sorts of enhancements. Thanks.

**Comment by TechHorseG** [comment]
Thanks for the addons link, I will check it out. Thanks for all responses.
