### ISSUE TITLE
NVDA reads blank After pressing left arrow in windows default mail app.

### ISSUE THREAD

**Issue by gauravahir28** [nvaccess/nvda#12203]
### Steps to reproduce:
- Open windows default mail app.
- open an any email of which the first line is not empty.
- Move your focus to the first  letter of the first word.
- Keep pressing left arrow.
### Actual behavior:
NVDA reads blank.
### Expected behavior:
NVDA should read First letter of that first word.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
NVDA 2020.4
#### Windows version:
Windows 10 (20H2)
#### Name and version of other software in use when reproducing the issue:
Windows default mail client (Version 16005.13426.20688.0)
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No - not tried.
#### If add-ons are disabled, is your problem still occurring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No.

**Comment by Adriani90** [comment]
@gauravahir28 can you still reproduce this issue with the last version of the windows default mail app and NVDA 2023.1 or NVDA last alpha version?

**Comment by gauravahir28** [comment]
Yes @Adriani90 - I am still able to reproduce this in last version of windows mail and NVDA 2023.1

**Comment by Adriani90** [comment]
@gauravahir28, @Aleskis, @mjonsson1986, @chojiro, @ctoth, @Nikita34196, @Carlos-EstebanM, @alexandretoco can anyone of you still reproduce this issue with NVDA last alpha version?

**Comment by gauravahir28** [comment]
I can still reproduce this with NVDA 2024.4 Beta 5.

**Comment by Adriani90** [comment]
Windows native mail app will be discontinued by the end of December, and users won't be able anymore to send or receive messages in that app. Closing as abandoned. For more info see this link:
https://support.microsoft.com/en-us/office/outlook-for-windows-the-future-of-mail-calendar-and-people-on-windows-11-715fc27c-e0f4-4652-9174-47faa751b199
