### ISSUE TITLE
Windows Terminal with Braille: UIA and runtime errors when closing it

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#12206]
### Steps to reproduce:

1. Open Windows Terminal.
2. Do some things, it is not really important. I looked at the Preview version and checked out the new Settings UI, then closed it and returned to PowerShell.
3. Type `exit` and hit Enter to close.

### Actual behavior:

Often when I close Terminal, errors like this are logged:

```
ERROR - core.CorePump.run (10:57:55.344) - MainThread (10464):
errors in this core pump cycle
Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 297, in __init__
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.pyc", line 549, in run
  File "braille.pyc", line 2229, in pumpAll
  File "braille.pyc", line 1965, in handlePendingCaretUpdate
  File "braille.pyc", line 1971, in _doCursorMove
  File "braille.pyc", line 1002, in update
  File "NVDAObjects\UIA\__init__.pyc", line 780, in copy
  File "NVDAObjects\UIA\winConsoleUIA.pyc", line 36, in __init__
  File "NVDAObjects\UIA\__init__.pyc", line 301, in __init__
RuntimeError: Could not clone range

```

### Expected behavior:

No such errors.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

version alpha-22012,3c1693dd

#### Windows version:

19042, 20H2.

#### Name and version of other software in use when reproducing the issue:

Windows Terminal Preview
Version: 1.7.572.0, installed from the Microsoft Store.

#### Other information about your system:

Handy Tech Active Star in use.

#### Does the issue still occur after restarting your computer?

Yes, but it is intermittent anyway, so you may have to try it multiple times.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No.

#### If add-ons are disabled, is your problem still occurring?

Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

No. Not applicable.

**Comment by codeofdusk** [comment]
* What version of Windows Terminal are you running? (check the `productVersion` with NVDA+f1).
* Can you still reproduce this with the latest NVDA snapshot?

**Comment by Adriani90** [comment]
We didn't get an update from the initial author upon request since many years, I am closing as abandoned. If you are still having this issue, please comment and we can reopen.
