### ISSUE TITLE
Wrong cell read in Excel

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#12200]
### Steps to reproduce:
1. In an empty workbook, move to B1.
2. Press a letter.
3. Press down and left.

### Actual behavior:
If I press down and left too fast, I hear either B2 or nothing.
### Expected behavior:
I should hear A2.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.4
#### Windows version:
Version 2004 (OS Build 19041.867)
#### Name and version of other software in use when reproducing the issue:
Microsoft® Excel® 2019 MSO (16.0.13801.20240) 32-bit 
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2020.3, same result
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by XLTechie** [comment]
I can not replicate this in latest alpha for Excel 2019.

**Comment by cary-rowen** [comment]
This may be exactly the same or partly the same as #12108, and we very much hope that NVAccess will investigate this.
@seanbudd

**Comment by feerrenrut** [comment]
I can reproduce this with NVDA 2021.3.4, it is very finicky and seems to be related to the timing of the arrow key presses. It seems like occasionally the second navigation isn't observed by NVDA, resulting in no speech. The first speech would be cancelled by the second key press. It only seems to happen if I am first editing a cell (as per the steps to reproduce).

A log snippet, note that speech for the cell coords `G2` is logged, but were not heard, the final destination was `F2` (after starting on `G1`.
```
Input: kb(desktop):downArrow
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:20:49.531) - MainThread (10944):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 723610 (EXCEL7), objectID 9780, childID 0, process 20808 (excel), thread 7212
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:20:49.532) - MainThread (10944):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 723610 (EXCEL7), objectID 9781, childID 0, process 20808 (excel), thread 7212
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:20:49.574) - MainThread (10944):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 723610 (EXCEL7), objectID 9782, childID 0, process 20808 (excel), thread 7212
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:20:49.574) - MainThread (10944):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_VALUECHANGE, window 723610 (EXCEL7), objectID 9783, childID 0, process 20808 (excel), thread 7212
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:20:49.575) - MainThread (10944):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_VALUECHANGE, window 723610 (EXCEL7), objectID 9784, childID 0, process 20808 (excel), thread 7212
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:20:49.575) - MainThread (10944):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_VALUECHANGE, window 723610 (EXCEL7), objectID 9785, childID 0, process 20808 (excel), thread 7212
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:20:49.575) - MainThread (10944):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_VALUECHANGE, window 723610 (EXCEL7), objectID 9786, childID 0, process 20808 (excel), thread 7212
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:20:49.575) - MainThread (10944):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_SELECTIONREMOVE, window 723610 (EXCEL7), objectID 9787, childID 0, process 20808 (excel), thread 7212
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:20:49.575) - MainThread (10944):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 723610 (EXCEL7), objectID 9788, childID 0, process 20808 (excel), thread 7212
DEBUG - editableText.EditableText._hasCaretMoved (14:20:49.655) - MainThread (10944):
Focus event. Elapsed: 10 ms
IO - inputCore.InputManager.executeGesture (14:20:49.681) - winInputHook (14472):
Input: kb(desktop):leftArrow
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (14:20:49.695) - MainThread (10944):
Could not locate dropdown list in previous objects
IO - speech.speech.speak (14:20:49.734) - MainThread (10944):
Speaking [LangChangeCommand ('en_US'), 'G2', CancellableSpeech (still valid)]
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:20:49.758) - MainThread (10944):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_SELECTIONREMOVE, window 723610 (EXCEL7), objectID 9897, childID 0, process 20808 (excel), thread 7212
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:20:49.759) - MainThread (10944):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 723610 (EXCEL7), objectID 9898, childID 0, process 20808 (excel), thread 7212
IO - inputCore.InputManager.executeGesture (14:20:54.561) - winInputHook (14472):
Input: kb(desktop):NVDA+q
```

**Comment by cary-rowen** [comment]
I'm using NVDA2022.1beta4 and disabled the UIA for Excel option in the NVDA advanced settings panel and I have the following findings:
## steps
1. Open Excel;
2. Stop to cell A1;
3. Keep pressing the down arrow for about 3 seconds and then release it;
4. You will hear A81 or other cell coordinate(May depend on your hardware performance);
5. Then press the up arrow once and you will hear the same cell coordinate as in step (4).

**Comment by XLTechie** [comment]
I can replicate @cary-rowen's STR in the above comment.
Also, if pressing down arrow once after having held it down a few seconds, the next cell announced will have skipped one from the last one announced after holding down the arrow key.
Office 2019, NVDA alpha (an alpha of 2022.2)

**Comment by Adriani90** [comment]
Could you please test with last alpha of NVDA? This might have improved after #14701. At least I can notice a significant improvement in performance whle navigating in Excel tables with the last alpha version.

**Comment by cary-rowen** [comment]
@Adriani90 
Can you test it with the str from my comment before posting it, it's still reproducible for me.

Thanks
