### ISSUE TITLE
Consider dropping gui.accPropServer based GUI annotations in favour of wx.Accessible

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#12209]
### Is your feature request related to a problem? Please describe.
To annotate dialogs (e.g. adding accessible descriptions, changing roles, checked/unchecked state of checkable list items), we use the gui.accPropServer module for a custom COM server implementation using comtypes. It took us several iterations to get this right and honestly, it feels slightly hacky to me.

### Describe the solution you'd like
WX is now able to do this for us. The process is pretty straight forward:

1. Subclass wx.Accessible
2. Override the methods you need, e.g. GetDescription, GetRole
3. Instanciate the accessible
4. Set the accessible on the control using SetAccessible

### Describe alternatives you've considered
Leave as is.

**Comment by leonardder** [comment]
CC @feerrenrut you also devoted some time to the gui.accPropServer module. I really feel like we need to consider the wx way since it results in less and cleaner code and means a switch to a process that is much better documented and elegant

**Comment by feerrenrut** [comment]
It would be worth trying it out. Removing code is certainly nice to do.
