### ISSUE TITLE
NVDA freezes when trying to update itself to build 22123 alpha

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#12221]
### Steps to reproduce:

1. From an older snapshot, in my case NVDA version alpha-22114,ed5fca6b, try an auto-update to alpha snapshot version alpha-22123,8665526b.
2. The download runs, I hit Install, the sound plays and NVDA is shut down.
3. The new instance loads, starts speaking, then immediately goes into an infinite WatchDog freeze loop. the UAC dialog to ask me whether I want to install never comes up.

### Actual behavior:

Freezes, and I have to shut down the instance with the older, still installed version.

### Expected behavior:

Install runs through as normal.

#### NVDA installed/portable/running from source:

Installed, trying to update itself.

#### NVDA version:

See above.

#### Windows version:

20H2.

#### Name and version of other software in use when reproducing the issue:

N/A.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No, previous installs all went fine.

#### If add-ons are disabled, is your problem still occurring?

Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

N/'A.

[nvda freezes when trying to update.zip](https://github.com/nvaccess/nvda/files/6203495/nvda.freezes.when.trying.to.update.zip)

**Comment by MarcoZehe** [comment]
Above comment updated with a log file.

**Comment by seanbudd** [comment]
Possibly related to #12219

**Comment by MarcoZehe** [comment]
Still a problem when trying to update to version alpha-22148,9a1cca54. Downloading the full installer and running it manually, with a regular install dialog sequence, does update the build successfully, and the new build then runs fine.

**Comment by zstanecic** [comment]
Hi Marco,

I cannot reproduce the freeze,

Windows 10 20h2, lates cu's installed and so on

**Comment by MarcoZehe** [comment]
Some further investigation shows that this freeze only seems to happen if the previously focused window is a Chromium-based one, either a browser or Electron app like Discord. If I make sure the window is something else, like a command prompt, the freeze does not happen. This is in the moment between the old NVDA shutting down and the new one having just started, and the UAC dialog coming up for the automatic update installation. HTH.

**Comment by michaelDCurran** [comment]
@MarcoZehe  I am having trouble reproducing this. Do you have Use UIA in Edge and other Chromium browsers enabled in NVDA's advanced settings?
when previously focused on a Chromium Window, are you actually in a document? on a particular form control, or just in the outer Chrome?
Can you give me a specific scenario you know does this all the time and I can try?

Could you please also reproduce the issue with your NVDA log level set to input/output and provide the log here or send privately to me?

**Comment by michaelDCurran** [comment]
@MarcoZehe   It would be also very useful if you could test a couple of alpha snapshots before 22123 and see if you can reproduce the problem with those as well.

**Comment by MarcoZehe** [comment]
This is no longer reproducible. Fixed by one of the recent alphas. Closing.
