### ISSUE TITLE
Difficulty in reaching lower rule conditions to edit them in Outlook Express/Live mail message rules

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1222]
**Reported by briang1 on 2010-11-26 14:19**
When creating or editing a message rule, the third option is to click on the underlined word corresponding to the input required by that preselected condition. If there are only two here, its OK, but three or more and it becomes hard to get to the line or word without it jumping back to  another one in nvda. I've tried the various modes of navigation but it seems these underlined areas have no default action according to nvda.
I suspect it is something to do with the earea itself.For the record I  can copy it to the clipboard as..
Apply this rule after the message arrives
Where the To line contains 'briang1@blueyonder.co.uk' 
    and Where the CC line contains 'blueyonder' 
    and Where the To or CC line does not contain 'sun' 
Delete it from server 

The nvda/f1  says..
Input: kb(desktop):nvda+f1
DEBUGWARNING - watchdog._watcher (14:15:19):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 139, in <module>
  File "core.pyc", line 260, in main
  File "wx_core.pyc", line 8007, in MainLoop
  File "wx_core.pyc", line 7303, in MainLoop
  File "core.pyc", line 246, in Notify
  File "queueHandler.pyc", line 77, in pumpAll
  File "queueHandler.pyc", line 47, in flushQueue
  File "scriptHandler.pyc", line 62, in _queueScriptCallback
  File "scriptHandler.pyc", line 93, in executeScript
  File "appModules_default.pyc", line 717, in script_navigatorObject_devInfo
  File "logging__init__.pyc", line 1128, in info
  File "logHandler.pyc", line 109, in _log
  File "wx_controls.pyc", line 1950, in SetInsertionPointEnd

INFO - appModules._default.AppModule.script_navigatorObject_devInfo (14:15:19):
Developer info for navigator object:
name: u'3. Rule Description (click on an underlined value to edit it):'
role: ROLE_EDITABLETEXT
states: STATE_MULTILINE, STATE_READONLY, STATE_FOCUSED, STATE_FOCUSABLE
Python object: <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x03E54130>
Python class mro: (<class 'NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.edit.RichEdit20'>, <class 'NVDAObjects.window.edit.RichEdit'>, <class 'NVDAObjects.window.edit.Edit'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (293, 461, 410, 75)
value: u"Apply this rule after the message arrives\rWhere the To line contains 'briang1@blueyonder.co.uk' \r   " (truncated)
appModule: <msimn (appName msimn, process ID 764) at address 3d6c890>
TextInfo: <class 'NVDAObjects.window.edit.EditTextInfo'>
windowHandle: 394532
windowClassName: u'RichEdit20A'
windowControlID: 131
windowStyle: 1419872324
windowThreadID: 652
windowText: u"Apply this rule after the message arrives\r\nWhere the To line contains 'briang1@blueyonder.co.uk' \r\n " (truncated)
IAccessibleObject: <POINTER(IAccessible) ptr=0x4e706e8 at 2312350>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=394532, objectID=-4, childID=0
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_READONLY, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048644)

I can eventually get to the third option but only by repeatedly pressing down cursor more than one would assume  and sometimes it just goes back, which is irritating!

**Comment by leonardder** [comment]
Closing, OE abandoned.
