### ISSUE TITLE
Wrong text chunks during say all in browsers

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#12225]
### Steps to reproduce:

1. open a web page with Firefox or Chrome (browsers I tested);
2. start sayAll;
3. after some words or lines, stop it with control or shift;
4. change line with arrows or open a new page,;
5. relaunch sayAll.

### Actual behavior:

SayAll reads a text chunk of previous reading before the new text.

### Expected behavior:

SayAll forgot the old text and starts from new one.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

NVDA version alpha-22126,ff79f518
(but it happens in last two-three alphas)

#### Windows version:

Windows 10 20H2 build 19042.870.

#### Name and version of other software in use when reproducing the issue:

Firefox 86.0.1, various voices/synthesizers (including OneCore).

**Comment by lukaszgo1** [comment]
I've introduced this regression in #12195 I'll submit a fix later today.

**Comment by ABuffEr** [comment]
Thanks, I wait pr merging to close this issue.
