### ISSUE TITLE
Setting panels do not scroll automatically [Alpha regression]

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#12224]
### Steps to reproduce:

1. Open a setting panel with many items, e.g. Document settings (ctrl+NVDA+D); do not maximize the window.
2. Tab many times until you reach the "Spelling errors" option
3. Tab once again to "Page" option
4.  Continue tabbing

### Actual behavior:

At step 3. we can hear that the option "Page" is focused. But visually, the setting panel did not scroll automatically. Thus, the option is not visible.
At step 4, same for the following options.
Moreover, with Windows Magnifier active, the magnified view continues to follow the invisible focus at the bottom of the setting window and even below. In addition if you activate focus highlight, you will be able to see the position of this invisible focus.

### Expected behavior:
The panel should scroll automatically so that the focus is always visible.

#### NVDA installed/portable/running from source:
From source
#### NVDA version:
Version: source-master-ff79f51
#### Windows version:
Windows 10 1809 (64-bit) build 17763.1817
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Not tested
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2020.4 does not show this issue, i.e. panel scroll automatically with focus move.
#### If add-ons are disabled, is your problem still occurring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by CyrilleB79** [comment]
Probably due to recent modifications to GUI (new version of wxPython and follow-up)
Cc @seanbudd

**Comment by seanbudd** [comment]
Found this similar issue with a solution posted: https://discuss.wxpython.org/t/tabbing-in-a-scrollpanel/35009, going to investigate

**Comment by CyrilleB79** [comment]
@seanbudd, would you add 2021.1 label for this one since it is a regression in 2021.1 dev cycle.
This issue only impacts sighted and visually impaired people, but since many visually impaired already complain of various NVDA bugs specific to them, it would be wise not to introduce new ones.
Thanks.

**Comment by seanbudd** [comment]
Hi @CyrilleB79, it is already added to the milestone - we will fix it in beta if it doesn't make it before then.

**Comment by CyrilleB79** [comment]
Oh sorry. I had missed it.
