### ISSUE TITLE
GUI：UI issues introduced by Python 3.8 

### ISSUE THREAD

**Issue by lijianwei2019** [nvaccess/nvda#12247]
UI issues introduced by Python 3.8 

### Python 3.7 behavior:

1.Center the screen of the update window 
2.The update time prompt is located above the progress bar
3.Set the panel cursor to be uniformly dark blue

![3](https://user-images.githubusercontent.com/59390108/112843116-d53ddd80-90d4-11eb-9be5-4d8fbdae77cb.PNG)

![1](https://user-images.githubusercontent.com/59390108/112843163-e0910900-90d4-11eb-8e18-9bcba76e5b31.PNG)

### Python 3.8   behavior:

1.The update window is located in the upper left corner of the screen
2.The update time prompt is located below the progress bar 
3.The cursor color of the setting control panel is inconsistent. They are dark blue and light blue.

![4](https://user-images.githubusercontent.com/59390108/112843251-f7cff680-90d4-11eb-8e74-d4e6cf8b2faf.PNG)

![2](https://user-images.githubusercontent.com/59390108/112843427-2352e100-90d5-11eb-88c4-b7e036435674.PNG)

#### NVDA installed/portable/running from source:

 installed/portable

#### NVDA version:

alpha-22160 and nvda2020.3

#### Windows version:

Windows10 pro 20H2 x64

#### Name and version of other software in use when reproducing the issue:

no 

#### Other information about your system:

no

#### Does the issue still occur after restarting your computer?

Yes

#### If add-ons are disabled, is your problem still occurring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes

**Comment by Nikita34196** [comment]
Hello. in the latest alpha versions I've discovered a great retres availability. basically it's squinting at system interfaces. For example. nvda does not now announce an update when downloading and installing. There's been no problem with that before.

**Comment by feerrenrut** [comment]
@lijianwei2019  Can you expand on how these changes impact you or others? 

The location of the update dialog is clearly a regression.

**Comment by lijianwei2019** [comment]
Break the original UI style@feerrenrut

**Comment by feerrenrut** [comment]
Ok. As part of the recent updates, wxPython was updated. I suspect that some more modern controls are used which will explain some changes. Unless the changes cause a specific problem, I don't think they need attention.

**Comment by lijianwei2019** [comment]
@CyrilleB79 @JulienCochuyt
