### ISSUE TITLE
Bug: closing the currently focused window via a script command crashes NVDA

### ISSUE THREAD

**Issue by TechHorseG** [nvaccess/nvda#12240]
NVDA portable 2020.4 / Win10 20H2
(although this bug happened in earlier versions of both)

Hello. If a window is currently active and is closed via script commands, then NVDA can crash and stop talking. Probably the easiest example to illustrate this is as follows.

1. Open a Command Prompt (there is a shortcut in the Win+X menu).

2. Paste the following line into it, and press enter:

`title Unique Title For NVDA Test & timeout /nobreak 10 & taskkill /fi "Windowtitle eq Unique Title For NVDA Test*"`

What this command does is change the title of the Command Prompt to "Unique Title For NVDA Test", waits 10 seconds, then closes it.

Here's the problem. If you leave the Command Prompt as the active window then when it closes NVDA crashes. However if during those 10 seconds you minimise it or alt+tab to a different window, then no problem. The Command Prompt will quietly close in the background without affecting NVDA.

The same results occur if I use a NirCMD "win close" command instead of a .taskkill command. If the closed window is the currently active window then NVDA crashes.

This is a bit of a headache for me, as I want to create scripts to auto-close windows under certain circumstances, and can't easily guarantee that they won't be in focus at the time of their closure. Thanks.

**Comment by lukaszgo1** [comment]
Firstly this does not affect every window - just console windows. Secondly this is a duplicate of #1682

**Comment by TechHorseG** [comment]
Oh sorry. Pity it seems to have been unfixable for so long! Guess it's a tricky one.

**Comment by XLTechie** [comment]
Perhaps consider closing this, and posting your interest in a solution on #1682.

That issue has several (closed) duplicates, but it still has the most important 
discussion of why this happens, and whether it should be fixed.
