### ISSUE TITLE
Add Image description functionality

### ISSUE THREAD

**Issue by svilla03** [nvaccess/nvda#12269]
### Is your feature request related to a problem? Please describe.
No
### Additional context
Image description can very helpful in many situations. For example, you will want to pick out some details, such as automibles or a group of people. Another scenario is if you are working on a project and need to make sure you have the right photo. But if you do not know what those photos are, you might be out of luck when it comes to productivity. I am writing this because I run in to many situations where images need to be described, and NVDA would be a good screenreader for the job.

**Comment by XLTechie** [comment]
You might want to ask on the add-on list. There was a Google Summer of Code 
operative working on an add-on for this.

https://groups.io/g/nvda-addons

**Comment by seanbudd** [comment]
Hi @svilla03 - this would be a great addition to NVDA (and something I'm personally interested in doing). We have another issue to discuss this on #7671.
