### ISSUE TITLE
A lot of NVDA's classes still have the base class of object.

### ISSUE THREAD

**Issue by trypolis464** [nvaccess/nvda#12267]
### Is your feature request related to a problem? Please describe.
I wouldn't necessarily call it a problem in the sense that something's broken, but it's certainly something that would be nice to fix.
### Describe the solution you'd like
In Python 3, classes have a base class of object by default, making class Thing: the same as class Thing(object):
### Describe alternatives you've considered
N/A
### Additional context
This would clean up the codebase, as well as removing old Python 2-like code. Doing it might be a bit of a process though (maybe I could run find/replace for "(object):" to be replaced with ":"). But I would have to do that on every file... Thoughts?

**Comment by leonardder** [comment]
I don't think there's anything wrong with classes inheriting from object explicitly, even in Python 3.8. I think this is neither a bug nor it will add anything valuable to the product when this is changed. Therefore I"m closing this.
