### ISSUE TITLE
Svox Pico synthesiser doesn't load (Affects some other third party synth drivers also)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1227]
**Reported by hurrikenny on 2010-12-02 05:24**
In the latest snapshot (3962), when I go into preferences...synthesiser... and attempt to change it from e-speak to svox pico, and then tab to ok, it gives me the following error message "could not load the pico synthesiser". It also gives me the "crash" sound.

**Comment by dkager** [comment]
> Technically, this isn't an NVDA issue, since this isn't an officially supported driver, but I'll leave it open as there are probably quite a few users using this.

Those external updates to the drivers should have happened by now. :)

**Comment by jcsteh** [comment]
They did.
