### ISSUE TITLE
Command line switch --minimal isn't silent

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#12289]
### Steps to reproduce:

Run NVDA with the --minimal command line switch.

### Actual behavior:

NVDA's launcher startup sound plays,
NVDA starts a temporary copy
No launcher interface appears

### Expected behavior:

The description of the switch is: "No sounds, no interface, no start message, etc."

While there doesn't seem much point in running:

nvda.exe --minimal

with no other switches and NOT having NVDA run, we've had several users trying to use this with --install-silent in order to silently install NVDA and confused as to why it is still playing the startup sound.

Issue #6289 was a similar issue, but ended up resolving a fix for the installer crashing when no soundcard was present (eg some situations when installing via SCCM in a virtual machine).

While the argument was put forward in that issue that this is a screenreader, if we're going to have a switch which proclaims "No sounds" then it should deliver on that promise.

The simple fix of course would be to reword the description, but we do get asked regularly and I think it is worthwhile having a way of installing NVDA without it making any sound.

#### NVDA version:

NVDA 2020.4 installer

#### Windows version:

Windows 10 (64-bit) Version: 2009, Build: 19042 

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I didn't when writing this up, but the behaviour isn't new

**Comment by feerrenrut** [comment]
Question is, should the docs be changed to say that this does play the startup sound, or should the startup sound be removed when this is present. 

Typically for an installer the argument `--silent` only prevents user prompts. EG all required information must be provided on the command line for the install to complete, otherwise the command fails.

The first step here I think should be surveying the current command line options to look for coverages of these use cases. It would probably be fine if this command argument could be combined with something else for instance.

**Comment by Qchristensen** [comment]
We don't have a --silent argument, but --install and --install-silent both install NVDA without prompting (aside from the UAC prompt).  The only difference between the two switches is that --install then starts the installed copy whereas --install-silent does not.  Perhaps --install-exit would have been more indicative of what happens?

In either case, adding --minimal does not do anything different.  The only time --minimal  makes a difference is if you start the downloaded launcher with it (eg nvda_2020.4.exe --minimal), it doesn't show the license agreement screen (with the install / continue options) it simply starts a temporary copy of NVDA, however it still plays the music at the start.

When starting an installed or portable copy of NVDA, the --minimal switch stops the four notes playing on startup.

IF --minimal did supress the music played when starting the downloaded launcher, it would make it consistent with its use on an installed / portable copy, and also fulfil the use case of those wanting to automate NVDA installation without any audio feedback using --install-silent --minimal.
