### ISSUE TITLE
aria-describedby and single line input fields

### ISSUE THREAD

**Issue by RichCaloggero** [nvaccess/nvda#12288]
### Is your feature request related to a problem? Please describe.

Assume we have a label such as "name" on our input field.

Suppose further that our `aria-describedby` on that field points to a long bit of text such as "(Enter as: Last/Surname, First/Given Middle)".

CUrrently, both label and contents of element referenced by `aria-describedby` are read *before* the current value of the input field.

### Describe the solution you'd like

I'd like:
- label read first;
- current value of field read next;
- contents of element pointed to by `aria-describedby` read last;

### Describe alternatives you've considered

- Make this a selectable / configurable option (although would prefer default to be as I suggested above);
- multiline fields should continue to read both label and aria-describedby *before* current field contents.

**Comment by MarcoZehe** [comment]
I believe this is already being dealt with in #12149.

**Comment by RichCaloggero** [comment]
Closed: duplicate of #12149.

**Comment by Brian1Gaff** [comment]
I've often wondered  if a little peep could be read in spoken output when 
the type of item being read changes in the middle as in the example.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Rich Caloggero" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Monday, April 12, 2021 3:17 PM
Subject: [nvaccess/nvda] aria-describedby and single line input fields 
(#12288)
