### ISSUE TITLE
ModuleNotFoundError: No module named 'comtypes.gen.MathPlayer' when import MathPlayer module

### ISSUE THREAD

**Issue by tsengwoody** [nvaccess/nvda#12281]
### Steps to reproduce:

1. Activates the NVDA Python Console
2. input "from mathPres.mathPlayer import MathPlayer"

NVDA Python Console show "ModuleNotFoundError: No module named 'comtypes.gen.MathPlayer'module"

### Actual behavior:

NVDA Python Console show "ModuleNotFoundError: No module named 'comtypes.gen.MathPlayer' when import MathPlayer module"

### Expected behavior:

NVDA Python Console should import and no error

#### NVDA installed/portable/running from source:

NVDA portable/NVDA running from source

#### NVDA version:

NVDA portable(nvda_snapshot_alpha-22260,62eaba52)
NVDA running from source(commit 62eaba5)

#### Windows version:

Windows 7 SP1/Windows 10 pro 20H2 (19042.867)

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes, it worked in NVDA 2020.4.

#### If add-ons are disabled, is your problem still occurring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes

**Comment by feerrenrut** [comment]
I can reproduce this, as well as the change in behavior between 2020.4 and alpha.

This might be related to "Make com interfaces ide friendly" #12201, but I don't immediately see how it could cause this issue.

**Comment by michaelDCurran** [comment]
This is a regression introduced by pr #12201 

comInterfaces_sconscript instructs comtypes to generate Python files from typelibs/mathPlayer.tlb. Comtypes produces MathPlayer.py (note the uppercase M). However, the sconscript target was hardcoded as "mathPlayer.py" (note the lowercase m). This has always been the case, and has not been a problem as scons and Windows is case insensitive and so Scons thought the target had been correctly created. However, pr #12201  makes use of the target's abspath property to rewrite the file with some extra imports. However, the path is made from the hardcoded target, so it has the lowercase m and therefore when the file is written out again, it has a lowercase m, and mathPres cannot then import MathPlayer with an uppercase M.
We just need to change the hardcoded "mathPlayer.py" string to "MathPlayer.py".

**Comment by feerrenrut** [comment]
Thanks for the investigation @michaelDCurran!
