### ISSUE TITLE
NVDA causing CPU usage spikes when some particular applications are running

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1228]
**Reported by parham on 2010-12-02 08:32**
NVDA causes CPU usage spikes (going as far as 35 per cent of CPU usage on a dual core CPU) when some particular applications are running. I have observed this behaviour on the following applications:
- Visual Web Developer Express 2010
- Total Commander (while syncronizing, downloading or uploading)
- Firefox
- "Down them all!": a Firefox ad-on for downloading files
- Microsoft office Word (seemingly with no apparent pattern)
- Jarte (again with no apparent pattern)
- ZQuake: a terminal/command line interface for running the Quake game

Previously, it has been observed that because of some of these applications (such as Total Commander) sending a lot of events to NVDA, NVDA would be sluggish. However, apart from the sluggishness, the CPU usage increases dramatically, making the user have to either close NVDA or the application that is causing it, since using the computer becomes impossible.

**Comment by leonardder** [comment]
Closing as invalid as things have changed in a major way during the last seven years, and the author didn't respond to @MichaelDCurran's last message in this issue.
