### ISSUE TITLE
Problem spelling things when speaking of tooltips is turn on.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1229]
**Reported by RamboUdin on 2010-12-02 11:17**
-. Latest snap of NVDA
-. Windows XP sp2

STR
1. Make sure that report tooltips is check, in the object presentation dialog box.
2. Go to my computer, and choose one of the hartDrive.
3. Press insert+up arrow twice quickly, to spell the current thing.
4. NVDA will spell the thing, and at some point, when the spelling still in progress, it will be interupted by the tooltips.

eg:
"L, o, c, eigh, l, d, i, s, free space: 100GB total size: 400GB. k, left parren, c, right parren bla bla bla."

Could you fix this?

THANKS!

**Comment by jcsteh** [comment]
Requires speech refactor (#4877).

**Comment by dkager** [comment]
Does this depend on/benefit from speech refactor?

**Comment by jcsteh** [comment]
Yes, as per [my comment above](https://github.com/nvaccess/nvda/issues/1229#issuecomment-228227784). :)

**Comment by dkager** [comment]
Not sure how I missed that comment...

Side note for when this gets fixed: as the comment in ToolTip.event_show says, an implementation with ui.message would be cleaner than directly calling braille helper functions. You could generalize and add a `queue` parameter to ui.message.

**Comment by lukaszgo1** [comment]
This one should be closed, as it was fixed by speech refactor.

**Comment by Adriani90** [comment]
Closing as works for me.

**Comment by zahra21** [comment]
Hi.
today, i found this bug and since someone reproduced it on windows xp which i use, i tried the mentioned steps to reproduction in the description.
but, i really could not reproduce it on windows xp service pack 3, with nvda 2017.3 and espeak 1.49.1
i tested three times,
and i am really glad that this issue does not occur for me!
