### ISSUE TITLE
Starting with version 2019.3, the "Capital pitch change" when using the SAPI4 synthesizer was invalid

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#12311]
Below is the debug log I added, You may find helpful information from line 630.
[nvda_log.txt](https://github.com/nvaccess/nvda/files/6350567/nvda_log.txt)

### Steps to reproduce:

1. Download and install the speech synthesizer provided in the following link, or use the SAPI4 speech synthesizer already on your computer.
link: [https://www.dropbox.com/s/3njaa8jrplutk24/IBM_ViaVoice_TTS_Runtime-V6.405.exe?dl=0](https://www.dropbox.com/s/3njaa8jrplutk24/IBM_ViaVoice_TTS_Runtime-V6.405.exe?dl=0)
2. Start NVDA and press NVDA + CTRL + S to select "Microsoft Speech API version 4" and confirm.
3. At this point the NVDA should have switched to the SAPI4 synthesizer and you will need to press NVDA + CTRL + V to open the Voice Setup dialog.
4. Use the Tab key to navigate until you hear "Capital pitch change percentageeditselected 30" You can change this value to 40 (or higher, or leave it unchanged).
5. Then use Windows + R to open the Run dialog and type notepad and confirm, this will open notepad allowing you to type some text.
6. Press the Caps lock key (it may be located to the left of the letter A) You may need to press it twice in a row until you hear "Caps lock on".
7. Try to enter some letters, such as the letter "C" (or "D" or something else)
8. Use Left Arrow or Right Arrow to move between these letters.

### Actual behavior:
NVDA reports these capital letters with no change in pitch.

### Expected behavior:
You will hear NVDA report these capital letters in a higher pitch

#### NVDA installed/portable/running from source:
installed and portable.

#### NVDA version:
NVDA 2020.4

#### Windows version:
Windows 10 20H2 (64Bit) build 19042.928

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
None

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I tested NVDA2020.4, NVDA2020.3, NVDA2019.3 And NVDA2019.2.1 in turn and found that this is a regression introduced by NVDA 2019.3(Of course including 2019.3.1).

#### If add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by vgjh2005** [comment]
Hi:
I agree with you. It is a Critical issue! SAPI version 4 is still the most important synthesizer today. Though there are more and more modern complex synthesizer switching system plugins,  but using different sounds to announce different languages do to text reading is not enough of satisfied. Fortunately, IBM viavoice text to speech engine has been able to run to announce multi language at the same time by one voice. It is still my only synthesizer. So please fix it. Thanks!

**Comment by zstanecic** [comment]
Hi,

The workaround for this is to turn off use spelling functionality checkbox in the NVDA voice settings. 

When this setting is turned off, the speech returns to normal, i.e capital pitch change is normal.

**Comment by cary-rowen** [comment]
Thanks, I have tried this method and it does not work as expected, so it is invalid.
@zstanecic

**Comment by cary-rowen** [comment]
Can you investigate this? Thank you.
@CyrilleB79

**Comment by zstanecic** [comment]
Ach, this works for one type of sapi4 synths, but not for others.

**Comment by cary-rowen** [comment]
Yes, so I believe this is a bug of NVDA. In the synthesizer download link I provided, this method is invalid.

**Comment by zstanecic** [comment]
Aare there any debug logs?

**Comment by cary-rowen** [comment]
@zstanecic I have added the debug log at the very beginning of the first comment.
Thank you for your reminder and hope you can assist in the investigation.

**Comment by zstanecic** [comment]
The thing is very simple, but it should be rewritten with people who knows sapi4. 

Pitch command is not supported at all, but it should be.

**Comment by dingpengyu** [comment]
cc @seanbudd
