### ISSUE TITLE
nvda windows store

### ISSUE THREAD

**Issue by Nikita34196** [nvaccess/nvda#12313]
hi. are there any improvements in the nvda functionality for the windows store. how much I know in nvda from the store can not install additions. I read an article about changes in store policy. here. https://www.windowscentral.com/windows-10-big-changes-coming-app-store

**Comment by josephsl** [comment]
Hi,

Update: the nee Store will be backported from Windows 11 to 10 except for Android app install functionality. Looks like a new issue might be better for this one (closing in favor of a new issue).

Thanks.
