### ISSUE TITLE
Alt+F4 closes Braille Viewer, but not Speech Viewer.

### ISSUE THREAD

**Issue by trypolis464** [nvaccess/nvda#12327]
### Steps to reproduce:
Go to NVDA Menu -> Tools -> Speech viewer. Alt+Tab to it, and try to press Alt + F4. Nothing happens. I'm not sure if this is on purpose or not. Then, open Braille Viewer (NVDA Menu -> Tools -> Braille Viewer), tab over to it, and press Alt+F4. It closes.
### Actual behavior:
Only one of the two viewers responds to the close command.
### Expected behavior:
For both to have the same behavior. I'm not sure if they were ever meant to be closeable with Alt+F4, but either way, it should be the same across both of them.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.4
#### Windows version:
Windows 10 2004 (64-bit) build 19041.928
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by JulienCochuyt** [comment]
Closing in favor of #10791 (see https://github.com/nvaccess/nvda/issues/10791#issuecomment-588047238)
