### ISSUE TITLE
the nvda settings window is not closed 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12336]
### Steps to reproduce:
I will inform all the palaces I made, as I have not tested other scenarios where this problem can occur.
I opened the nvda settings window
I selected the advanced tab
unchecked the checkbox
Enable selective logging of UI automation events and property changes
I walked with shift + tabe until I applied and pressed space
I walked with shift + tabe until ok and I pressed space. 
### Actual behavior:
the settings window is not closed 
### Expected behavior:
the settings window is closed 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-22498,d9afe35d

#### Windows version:
10 19043.962
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes
although the settings window does not close as expected the settings appear to be saved

**Comment by seanbudd** [comment]
I haven't been able to reproduce this. You mentioned that the issue no longer occurs after running the COM registration fixing tool, does that mean it is no longer present at all now?

**Comment by fernando-jose-silva** [comment]
sorry, edit the comment above, wrong answer due to lack of correct understanding of the English language The problem still occurs even after running the registry correction tool with

**Comment by CyrilleB79** [comment]
@fernando-jose-silva could you provide a log in debug mode when you reproduce this issue?
Also can you hear an error sound when pressing "OK"?

At least are you able to reproduce this issue with NVDA 2020.4 (e.g. portable or from the launcher)?

**Comment by fernando-jose-silva** [comment]
log:
[exit.txt](https://github.com/nvaccess/nvda/files/6399110/exit.txt)

**Comment by fernando-jose-silva** [comment]
The problem did not happen when using nvda 2020.4
I just got a call from a friend running the alpha nvda last version also asking me why the settings are not closing.
Yes, an error sound is played.
Thank you very much for your attention.

**Comment by CyrilleB79** [comment]
Thanks for the log! It should help NVAccess people.

Linked to issue #12220 and to workaround PR #12292.
Cc @feerrenrut 

For information, I have tried to reproduce the issue. Without success with the same steps.
But I could reproduce it as follows:
* Open settings
* Go to Speech settings and change the synth
* Go to advanced settings
* Enable "selective logging of UI automation events and property changes" option
* Shift-tab back to "Apply" button and press it
* Shift-tab back to "OK" button and press it

Note: I do not know if it matters but in @fernando-jose-silva's log, the config is pointing at a synth in an add-on (IBMTTS), but OneCore is used since NVDA is running with add-ons disabled. Could it be the reason why the synth setting is saved whereas no synth switch has occurred?

**Comment by XLTechie** [comment]
I was able to repro this using @CyrilleB79's STR.

@seanbudd this looks similar to something you just recently fixed, maybe back again?

When hitting apply in advanced settings after @CyrilleB79's STR:
```
ERROR - unhandled exception (14:50:13.707) - MainThread (12952):
Traceback (most recent call last):
  File "gui\settingsDialogs.pyc", line 665, in onApply
  File "gui\settingsDialogs.pyc", line 643, in _doSave
  File "gui\settingsDialogs.pyc", line 1013, in onSave
RuntimeError: wrapped C/C++ object of type ExpandoTextCtrl has been deleted
```

Here's another STR:

1. NVDA+n, p, s, s, alt+h.
2. Up/down arrow to change synths, then press enter.
3. Alt+h to change synth again.
4. Arrow to a different synth and press enter.
5. Shift+tab to Apply, and press.

Apply seems to work, but the settings dialog becomes unclosable, with the same error logged as above.

**Comment by feerrenrut** [comment]
This looks like it was caused by: PR "Work around wxWidgets assertion #12292"

I'll update this with an alternative approach.
