### ISSUE TITLE
COM Registration Fixing Tool shouldn't start with a warning dialog and off-putting language

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#12351]
### Is your feature request related to a problem? Please describe.

The COM Registration Fixing Tool is a critical utility for maintaining the accessibility of Windows software.
It seems that more and more actions in Windows have the potential to cause COM deregistration, and the tool must be used more than in past years.

In supporting users across a few mailing lists, and in direct phone calls and email support sessions, I have repeatedly experienced the circumstance where a user needs to run the tool, either diagnostically or to fix a problem.
However, the responses I often hear/see are: "I looked at that, but I was afraid to run it", "I didn't understand it and it seemed dangerous to use without knowing more", "I thought we weren't really supposed to use that", and similar.
In many of those cases, running the tool actually did solve the problem.

I have become convinced that the reason for this hesitation, is fear generated by the heavy warning dialog and message that is shown when one starts to run the tool.

### Describe the solution you'd like

Because I believe this utility is more important than it ever was, I would like to see:
* The dialog switched from having a warning icon, to an info icon or no icon;
* The text in the dialog made less off-putting, and more encouraging of using the tool to try to solve problems; and
* The text in the user manual made more friendly.

### Describe alternatives you've considered

The only alternative I know of is leaving it as is, but I believe the existing warning is overkill.

### Additional context

The prime concern here seems to be that the tool modifies the registry.
However there are many programs and situations that modify the registry, which do not hit the user in the face with such a warning window. Many (all?) software installations, for example.

Even Regedit, arguably the most risky piece of software shipped with any Windows installation, doesn't provide an overt warning such as the CRFT warning.

We specifically ask users to run this tool before submitting **any** apparent bug issue on Github--so I can't believe it's as dangerous as all that.

If I am not mistaken, even NVDA itself, installs certain registry keys without warning the user, upon its installation.

And lastly, I find it telling that in #2807, which appears to be the issue which spawned the CRFT, @jcsteh, @michaelDCurran, and others never gave any big warning about running the raw commands which later became the basis for the tool.
It seemed well enough understood that, if you had this problem, getting it fixed was the most important thing; and you needed to use administrative (I.E. abnormal) commands to do it.
Discouraging users from even trying it to fix their problems, did not seem like the intention.

### Follow-up

I have already written code that can implement a better dialog. I can easily include it in #12349 if NV Access agrees to this proposal, or can do it separately if this seems too controversial.

**Comment by jcsteh** [comment]
Ultimately, this isn't my decision, but just a bit of commentary:

> However there are many programs and situations that modify the registry, which do not hit the user in the face with such a warning window. Many (all?) software installations, for example.

That's true, but software installations explicitly and obviously require administrator privileges. When you install software, you expect that it may modify your system in some way or another and that it may thus require admin privs.

> Even Regedit, arguably the most risky piece of software shipped with any Windows installation, doesn't provide an overt warning such as the CRFT warning.

True, but it's also effectively an advanced/developer tool; most users don't come across it.

> If I am not mistaken, even NVDA itself, installs certain registry keys without warning the user, upon its installation.

Actually, NVDA runs the COM registration fixes tool during installation. But again, see above re installers and the expectation of system changes therein.

> And lastly, I find it telling that in #2807, which appears to be the issue which spawned the CRFT, @jcsteh, @michaelDCurran, and others never gave any big warning about running the raw commands which later became the basis for the tool.

True, but keep in mind that we knew for a fact users already had a big problem, so the assumption was that they probably wouldn't make things any worse by trying the fixes we suggested. It's not like we went out to a mailing list and said "hey, everyone, you should run this"; users only learned about the fixes if they found the thread because they had a problem. In contrast, this is something that's available in the Tools menu. There are some users that may try it "just because" and be scared (and potentially distrust NVDA) when it requests admin privs. They do need to be aware that it will change system settings, since that's not explicit or obvious like it is when you choose to install a piece of software.

**Comment by seanbudd** [comment]
I'm not sure if this behaviour is already included in the tool, but it might be worth adding an option to backup the registry before running the tool or giving instructions on how to do so.

**Comment by XLTechie** [comment]
First, thanks @jcsteh for providing your commentary.

> That's true, but software installations explicitly and obviously require administrator privileges. When you install software, you expect that it may modify your system in some way or another and that it may thus require admin privs.

And running the tool requires them as well.
Perhaps I am unusual, but I always assume that anything which requests elevation, is doing something that could change system files. I had thought that was a general understanding.

> Actually, NVDA runs the COM registration fixes tool during installation.

I thought it surely must, but hadn't actually dug through the installer to look so I didn't want to claim it.

> True, but keep in mind that we knew for a fact users already had a big problem, so the assumption was that they probably wouldn't make things any worse by trying the fixes we suggested. It's not like we went out to a mailing list and said "hey, everyone, you should run this"; users only learned about the fixes if they found the thread because they had a problem.

Fair enough. Although i believe I did suggest that the problem under discussion is now (significantly) more common than it was in 2017. Though I only have anecdotal evidence for that, based on my experience personally and in support contexts.

> In contrast, this is something that's available in the Tools menu. There are some users that may try it "just because" and be scared (and potentially distrust NVDA) when it requests admin privs. They do need to be aware that it will change system settings, since that's not explicit or obvious like it is when you choose to install a piece of software.

I want to be clear that I'm not suggesting having **no** dialog. I still think we need to explain the tool, possibly to the extent of saying "only run this if you are having these problems".
I just think that having it as a warning (which is usually for something very serious indeed) is damaging, and the current language if made not a warning, should be revised and softened. Maybe also expanded to be more descriptive of use cases.

**Comment by jcsteh** [comment]
Oh sure, it's reasonable to say that requesting elevation means system
stuff is going to be changed. However, the user needs to have some idea of
*why* something is going ot request elevation. With an installer, that
understanding is implicit. With something like this, it has to be explicit.

**Comment by britechguy** [comment]
I have, for a very long time, thought that the warning message, as presented by the COM Registration Fixing Tool, is a huge blunder as far as how end users are going to react to it.

Warnings, identified as warnings, are generally only issued in one of two situations:  when there is significant risk of an unintended result or where the intended result is not something that the user would "naturally expect."   Neither of those conditions is true of the COM Registration Fixing Tool, which is likely to either have the utterly benign and expected result of fixing what it's supposed to fix, or "doing nothing" from the perspective of the end user.

The dialog presented by this tool needs to be toned down significantly.  It produces unnecessary worry and hesitancy to use it, and that has been expressed on the NVDA Group on Groups.io multiple times over the years by multiple first-time users of the tool.

The expected result of the COM Registration Fixing Tool has always, in my experience and observation, been utterly been utterly benign.  I have never even once heard of a situation where using it has caused "an immense conflagration."  The warning, as issued, should be removed and an informational dialog of a much less worrying nature presented when the tool is run.

**Comment by britechguy** [comment]
> I'm not sure if this behaviour is already included in the tool, but it might be worth adding an option to backup the registry before running the tool or giving instructions on how to do so.

Unless there is very good reason to believe this is necessary, or it could be done "silently," this is another thing that if emphasized will be very off-putting to the uninitiated.

If, up until this point, and for as long as the tool has existed, there has not been a perceived need to do this I can really see no reason to do it now.  There's been years of use of the tool without issue in the field.

**Comment by britechguy** [comment]
Here's my own proposal for an appropriately thorough, but "soothing," COM Registration Fixing Tool dialog box, sans any mention of the word warning:

Welcome to the COM Registration Fixing tool.
This tool is used by NVDA to fix interaction issues between NVDA and Windows and/or application programs.
It examines the system registry for corrupted or missing entries and will correct either.
You have most likely been asked to run this tool by NVDA support or a power user trying to assist you.
If no one has asked you to run this tool and all is well, it should not be run.
Because it may need to modify the Windows registry, if you have User Account Control (UAC) active, you will be prompted by UAC before it can do its job.  This is normal and you should answer using the Yes button.
Do you wish to try to repair the registry at this time?

**Comment by josephsl** [comment]
Hi, translators, any thoughts?
