### ISSUE TITLE
Adding Liblouis hyphenation support for braille

### ISSUE THREAD

**Issue by Futyn-Maker** [nvaccess/nvda#12381]
### Is your feature request related to a problem? Please describe.

Now NVDA, at least for Russian language, make hyphenations incorrectly (with unchecked "avoid words splitting when possible"). I don't know if the problem is for other languages, but if there's the same algorythm, I guess, yess.

### Describe the solution you'd like

Liblouis has hyphenation tables for some languages. Firstly, they use in LiblouisUtdml and in the `nocross`-opcode. But there's a possibility to organize hyphenation in any program that uses Liblouis, see http://liblouis.org/documentation/liblouis.html
It would be really nice to have right hyphenations when reading texts with braille display.
For example, these tables can be added manually for supported languages.

### Describe alternatives you've considered
Maybe some alternative hyphenation-algorhythms can do it better, but I think it's the most simple way.

### Additional context

I think that correct hyphenations are great balance between avoiding word splitting at all and do it anywhere.

**Comment by josephsl** [comment]
Hi, an important question: is this unique to NvDA, or does it affect others using Liblouis such as JAWS and Narrator? If it is unique to NVDA, then we might as well investigate this; if not, it might be something to do with braille tables from Liblouis. Thanks.

**Comment by josephsl** [comment]
Hi, in this case, it might be best to contact whoever wrote Russian braille table for Liblouis, as hyphenation is defined at the table level, not at the Liblouis library levee. Thanks.

**Comment by josephsl** [comment]
Hi, @LeonardDeR may know more about communication between NVDA and Liblouis (or perhaps @JCSTeh might). I assume it was tables based on initial comment, but based on what you said above, it might be something to look into. Thanks.

**Comment by LeonarddeR** [comment]
Since this issue is stale and talks about liblouis hyphenation support specifically while discouraged by @bertfrees, I'm going to close this issue. @Futyn-Maker, if this is still an issue for you, please open a new issue along with steps to reproduce.
