### ISSUE TITLE
Line ending normalization

### ISSUE THREAD

**Issue by seanbudd** [nvaccess/nvda#12387]
The NVDA code base uses a mix of CRLF and LF style line endings, with the preference being CRLF. LF style endings have been introduced prior to lint checking, and can causes issues when moving code or making changes. Many IDEs will normalize the line endings when editing files, causing larger than intended diffs in PRs.

In order to tackle part of many linting issues noted in #12261, we can normalize all files to use LF in the NVDA code base. This commit can be ignored with git blame by introducing a [git ignore revs file](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt). 

The concerns around reviewing mass linting here can be ignored as we can review an empty diff quickly with `git diff --ignore-cr-at-eol`.

- [x] .gitattributes PR #12816:
    - confirm translators aren't effected (eg python translation comments, multiline strings)
    - update .gitattributes to use LF
        - get a list of file extensions in the NVDA repo, confirm we want these to change
        - exclude `*.t2t` files so translators aren't affected
    - add a git ignore revs file
    - update dev and internal documentation
- [ ] Normalization PR:
    - Re-check in files with LF `git add --renormalize .`
    - Use `git diff --ignore-cr-at-eol` and ensure there is an empty diff.
    - Notify developers of the change, how to update PRs.
          - https://github.com/nvaccess/nvda/pull/16754
- [ ] Update git ignore revs file PR:
    - Update git ignore revs file with commit from normalization
    - https://github.com/nvaccess/nvda/pull/16754
- To consider:
    - [ ] Consider further documentation.
    - [ ] update changes for developers / notify developers

**Comment by seanbudd** [comment]
Script for renormalizing PRs with merge conflicts.

```sh
git checkout PRBranchWithConflicts
git branch newBase `git merge-base master HEAD`
git checkout newBase 
git checkout master -- `.gitattributes`
git commit -m "add .gitattributes"
git add --renormalize .
git checkout PRWithConflicts
git rebase newBase --exec "git add --renormalize . && git commit --allow-empty --amend --no-edit"
```

**Comment by feerrenrut** [comment]
Github now also has [support for the ignore-revs file](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view)

**Comment by seanbudd** [comment]
For fixing merge conflicts with normalization, this works if no other merge conflicts for the PR existed before the normalization

```
git merge 8fb8ffcaba3950b1e4ca7b58e165267fc5369eb9 -x ours
git add --renormalize .
git commit -m "renormalize changed files"
```

**Comment by seanbudd** [comment]
Please see steps in https://github.com/nvaccess/nvda/discussions/16761 to resolve this
