### ISSUE TITLE
00:00 and 0:00 are intrepreted as "Midnight" or "24:00" 

### ISSUE THREAD

**Issue by SuzanneTaylor** [nvaccess/nvda#12394]
### Steps to reproduce:

1. Go to http://manateeroad.com/BugReports/duration.html
2. Read the different instances of number number colon number number with NVDA
3. Some speech synthesizers read these as just numbers, others as minutes and seconds, some translate the first 00 to 24, some translate 0:00 and 00:00 to midnight.
4. In no cases does &lt;time&gt; or datetime make any difference

### Actual behavior:
When punctuation is set to the default of "Some":
- On my Windows Surface Pro 0:00 and 00:00 are read as "midnight"
- On a colleague's system 00:27 is read as "twenty-four twenty-seven" 

When punctuation is set to "Most" these are read as numbers.

### Expected behavior:
I would expect this to be read as numbers, or at least for Web developers to have a way to clarify the intended meaning of these numbers. HTML does offer a &lt;time&gt; element and a datetime attribute, which should be able to provide the clarification, but this does not seem to work, as you can see at the test page.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.4 using Windows One Core voices > Microsoft David

#### Windows version:
Windows 10 Home OS build 19041.928

#### Name and version of other software in use when reproducing the issue:
Firefox 88.0.1

#### Other information about your system:
Surface in laptop mode.

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I tried this on an old Windows 7 computer with NVDA 2020.4 and punctuation set to "Some" with the following results:
- with Microsoft Speech API Version 5, these are read as minutes and seconds
- with eSpeak NG, these are read as numbers

**Comment by XLTechie** [comment]
This is a case of the speech synth trying to be too intelligent for its 
own good, and showing just how unintelligent it actually is.

Submit some Microsoft feedback about this, or complain to their 
accessibility department, if you can replicate this behavior with 
Narrator.

You can fix it in your voice speech dictionary while you wait for 
Microsoft to act on your feedback.

A regular expression entry of:

\b00:(\d{2})\b

With a replacement of:

00 colon \1

would work, as would the more generic:

\b(\d{2}):(\d{2})\b

With replacement of:

\1 colon \2

Note, the word colon is spelled in these replacements, while it's the 
symbol in the expressions.

**Comment by feerrenrut** [comment]
Thanks for the explanation @XLTechie. Since this is not an issue in NVDA I'm going to close this issue.

**Comment by SuzanneTaylor** [comment]
> 
> 
> Thanks for the explanation @XLTechie. Since this is not an issue in NVDA I'm going to close this issue.

Thanks for all of this input, but I would suggest still at least looking at this as a feature request to allow Web developers to prevent their users from encountering this, by using the **&lt;time&gt;** element with the **datetime** attribute to clarify the meaning. As noted, the synthesizers are all over the place. This leaves all of the responsibility on the user, and the primary concern is that the users may be distracted by the incorrect info and not know what the Web developer intended.
