### ISSUE TITLE
NVDA announces tables with role="presentation" in Outlook app

### ISSUE THREAD

**Issue by quidkid** [nvaccess/nvda#12419]
### Steps to reproduce:

1. Open Outlook desktop app on Windows
2. With NVDA on, navigate an email with all the tables having an attribute of role="presentation".
3. Notice that columns and rows are still being announced.

### Actual behavior:
Table semantics are announced by NVDA when role="presentation" is used
### Expected behavior:
Table semantics should not be announced by NVDA when role="presentation" is used.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.1
#### Windows version:
Windows 10 Enterprise 10.0.18363
#### Name and version of other software in use when reproducing the issue:
Microsoft 365 Apps for Enterprise Outlook Version 2008 Build 13127.21506
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment]
Would you be able to test with [last alpha build](https://ci.appveyor.com/api/buildjobs/uowxqjrmtatr8w8y/artifacts/output/nvda_snapshot_alpha-22774,44fabd74.exe)?
 
A recently merged PR (#11899) may have impact on this issue.

**Comment by quidkid** [comment]
@CyrilleB79 Just tested and it is still reading out tables that have role="presentation".

**Comment by CyrilleB79** [comment]
OK, too bad.

How do you create an e-mail with table role=presentation in Outlook?

**Comment by quidkid** [comment]
I just tried it again and it no longer reads the tables! I’m so confused! When I first installed it and I hit launch after making the portable copy, it was reading the tables. When I go back and click on the .exe after initially closing it, it doesn’t read the tables.

As for how to test, you can use Litmus Putsmail to send a copy of an email to yourself with html code. The easiest way was to get the Salted email template, find and replace all  <table with <table role=“presentation” and copy that into the Litmus Putsmail. Alternatively, if you give me an email address, I can send you a test email to work with to see if you have the same issue.

As of now, the old NVDA 2020 reads out tables but the alpha version does not. Going to restart the computer and test again.

**Comment by quidkid** [comment]
@CyrilleB79 It's not reading the tables after restarting today when I directly click on the .exe which is awesome! But when install a fresh copy and hit launch after portable copy, it reads the tables. So not sure what is that all about but hopefully it is resolved.

**Comment by CyrilleB79** [comment]
Things are not so clear to me. Do you still face the problem?
If yes, could you test with latest alpha (there are modifications integrated regarding NVDA restart after installation).

If the issue is still present in some case but not in other case. Could you write for both cases more detailed steps (e.g. bullet step list) describing which version of NVDA you launch and what you do?

Thanks.

**Comment by quidkid** [comment]
@CyrilleB79 so sorry for not getting back to you, but yes it is fixed with the latest alpha!
