### ISSUE TITLE
Exiting NVDA not possible if Elements List window is open

### ISSUE THREAD

**Issue by patrickhlauke** [nvaccess/nvda#12437]
If an Elements List window is open, attempting to exit NVDA will bring up the usual "Exit NVDA dialog - what would you like to do". Proceeding as normal and choosing to exit ... nothing happens. The exit dialog is closed, but NVDA is still running. This can be particularly confusing if you have lots of windows open and don't even realise that the Elements List window is still open somewhere.

### Steps to reproduce:

- in NVDA, fire up the Elements List (e.g. while browsing through a web page) (NVDA+f7)
- attempt to exit NVDA (e.g. using NVDA+q)
- "Exit NVDA dialog" appears
- Choose "Exit", OK

### Actual behavior:

- the "Exit NVDA dialog" closes, but NVDA keeps happily running. No indication is given why it's not exiting (only once the Elements List window is closed does the exit process work correctly)

### Expected behavior:

- NVDA should close the still open "Elements List" window (the same way it closes other windows, like the NVDA Speech Viewer, if open) automatically
- NVDA should then exit

#### NVDA installed/portable/running from source:

NVDA installed

#### NVDA version:
2020.4

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
Chrome, Firefox

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This has been an issue with at least the past few releases of NVDA.

#### If add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by josephsl** [comment]
Hi, can you test this with latest alpha snapshot and report what happens? Thanks.

**Comment by patrickhlauke** [comment]
Aha, tried latest snapshot, and this behaves as expected now. Good to see this already addressed in the next release.
