### ISSUE TITLE
Make command line switches not case sensitive

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#12434]
### Is your feature request related to a problem? Please describe.

NVDA has a number of command line options, as detailed in the User Guide: https://www.nvaccess.org/files/nvda/documentation/userGuide.html#CommandLineOptions

Currently these are case sensitive.  For instance:

nvda.exe --help

in all lowercase brings up the help screen and exits, whereas:

nvda.exe --Help
(with the H in help capitalised) or
nvda.exe --HELP
(all capitalised), both start NVDA and ignore the command line parameter.

### Describe the solution you'd like

Command line options should not be case sensitive.  There is no current use case in which this is required, and no foreseen requirement for this going forward.

### Describe alternatives you've considered

The main alternative is training to ensure users are aware.  We did have an issue recently where a corporate user was trying to roll out installing NVDA and had capitalized the first letter of a command line switch and it took a little while to uncover exactly why it was not working.

**Comment by pauliyobo** [comment]
Would it be ok for me to tackle this one?

**Comment by TheQuinbox** [comment]
Can you simply .lower() them? Like,
```
(globalVars.appArgs,globalVars.appArgsExtra)=parser.parse_known_args()
globalVars.appArgs, globalVars.appArgsExtra = globalVars.appArgs.lower(), globalVars.appArgsExtra.lower()
```
?
Not sure of the types of these, if I'll have to "".join() or something, or if it's a different var, but if it's that easy I could probably do it in a matter of 5 minutes.

**Comment by lukaszgo1** [comment]
> 
> 
> Can you simply .lower() them? Like,
> 
> ```
> (globalVars.appArgs,globalVars.appArgsExtra)=parser.parse_known_args()
> globalVars.appArgs, globalVars.appArgsExtra = globalVars.appArgs.lower(), globalVars.appArgsExtra.lower()
> ```
> 
> ?
> Not sure of the types of these, if I'll have to "".join() or something, or if it's a different var, but if it's that easy I could probably do it in a matter of 5 minutes.



No its not that simple. Besides when command line arguments are parsed into `globalVars.appArgs` it is too late top do any normalization.

**Comment by dorenel** [comment]
Can we pre-process and lower() the options before passing them to parse_known_args()? For example:

    args = sys.argv[1:]
    lowerArgs = [arg.lower() if arg.startswith('-') else arg for arg in args]
    (globalVars.appArgs, globalVars.appArgsExtra) = parser.parse_known_args(args=lowerArgs)

It seems like the first thing parse_known_args() does is to set `args` to `sys.argv[1:]` when no argument is provided, as in the existing code. So maybe we can pre-process the options first and pass the lowercased options as the argument to parse_known_args()?

Here is the diff of the code changes: https://github.com/dorenel/nvda/commit/8a0b9993b36b82747e8724d8cb997bc8855bbfa4

**Comment by ahmad-alajaj** [comment]
Hello, I worked on this issue, I located the entry point of nvda software which is nvda.pyw in the source folder.

For the solution I used 'sys' library, I edit all the arguments and lower them using 'lower()' function before any process from the parser. As this parser uses also 'sys.argv', I put the changes in the begining of the file.

here is the code:

for i in range(len(sys.argv)):
	sys.argv[i]=sys.argv[i].lower()

Later I wrote a small program to test this changes using sys and parser and it worked pretty fine, which made me test it on nvda and it ignores the case sensitivity of the commands while using CMD.

**Comment by seanbudd** [comment]
Case sensitivity of CLI arguments is preferred and a common pattern. Closing this as won't fix.

**Comment by seanbudd** [comment]
Apologies for this miscommunication, it would have been ideal to make this decision earlier.

**Comment by XLTechie** [comment]
@seanbudd wrote:
> Case sensitivity of CLI arguments is preferred and a common pattern. Closing this as won't fix.

For single letter arguments, yes. For whole word (gnu long style), not so much.

And in Windows, Microsoft has made the tendency to be that long options are 
case insensitive. E.g. /restorehealth works as well as /RestoreHealth to dism. 
That said, we use gnu style options (- instead of /, -- instead of /), so maybe 
that effects the direction.

I'm not sure which situation this PR was trying to fix (long or short options), 
but if long options, it seems worth consideration.
