### ISSUE TITLE
Play audio file when reading text

### ISSUE THREAD

**Issue by MesterPerfect** [nvaccess/nvda#12446]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
Is there a possibility that when NVDA speaks text, it plays an audio file?
i thinking of creating an nvda add-on and the function includes the idea of playing an audio file from within the add-on when nvda reads certain text
Example
I want nvda when it reads word [AHMED] in square brackets It plays the ahmed.mp3 file 

### Describe alternatives you've considered

I don't know anything alternative that helps me do what I want 

### Additional context

**Comment by feerrenrut** [comment]
Yes, this is possible. You look at `WaveFileCommand`, these should get inserted into a speech sequence before the text you want it to play over. 

Since this issue is not to do with NVDA I'll close it. Please consider joining the addon developers mailing list and the NVDA developers mailing list.
