### ISSUE TITLE
Unsigned builds (such as PRs) fail to start on touchscreen devices

### ISSUE THREAD

**Issue by seanbudd** [nvaccess/nvda#12440]
### Steps to reproduce:

Create a PR build and install it, and run it

### Actual behavior:

Touch handler fails to initialise with the following log.

```python
DEBUG - core.main (10:19:34.062) - MainThread (10856):
Initializing touchHandler
DEBUG - touchHandler.initialize (10:19:34.063) - MainThread (10856):
Touchscreen detected, maximum touch inputs: 10
CRITICAL - __main__ (10:19:34.066) - MainThread (10856):
core failure
Traceback (most recent call last):
  File "nvda.pyw", line 266, in <module>
  File "core.pyc", line 555, in main
  File "touchHandler.pyc", line 342, in initialize
  File "touchHandler.pyc", line 322, in setTouchSupport
  File "touchHandler.pyc", line 217, in __init__
  File "touchHandler.pyc", line 232, in run
  File "_ctypes/callproc.c", line 935, in GetResult
PermissionError: [WinError -2147024891] Access is denied
IO - inputCore.InputManager.executeGesture (10:19:36.378) - winInputHook (30428):
Input: kb(laptop):windows+u
IO - inputCore.InputManager.executeGesture (10:19:46.708) - winInputHook (30428):
Input: kb(laptop):shift+5
```

### Expected behavior:

NVDA starts properly

#### NVDA installed/portable/running from source:

PR builds

#### NVDA version:

alpha and 2021.1 beta

#### Windows version:

10

#### Name and version of other software in use when reproducing the issue:

N/a

#### Other information about your system:

n/a

#### Does the issue still occur after restarting your computer?

yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

n/a

#### If add-ons are disabled, is your problem still occurring?

yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

n/a

**Comment by seanbudd** [comment]
this is due to NVDA not having the UIAccess permission without being a signed copy. touchHandler.touchSupported should return false at the bottom if systemUtils.hasUIAccess returns false

**Comment by josephsl** [comment]
Hi, this is the first time I’m seeing this traceback (note that touch support requires UI access privilege). Besides that, whenever I test touch support, I experiment with Enhanced Touch Gestures add-on first before submitting PR’s dealing with touch handler. CC @MichaelDCurrand others using touchscreens.

**Comment by XLTechie** [comment]
On non-touch enabled systems, I've been getting the same permission denied 
error, but for audio ducking initialization, for such builds. I assumed it 
had something to due with signing.

**Comment by josephsl** [comment]
Hi, yes, UI access privilege is also required to use audio ducking functionality (this is why the user guide states that you must be running an installed copy of NVDA in order to use audio ducking feature). As far as internals are concerned, PR builds are seen as portable NVDA because it lacks privileges (no signing as folks pointed out).
