### ISSUE TITLE
Using google tts in NVDA

### ISSUE THREAD

**Issue by NVCDevelopmentTeam** [nvaccess/nvda#12457]
Have you ever thought about integrating google tts into NVDA? I think it's a great text to speech tool. This problem has been mentioned by many people but there is really no way to solve it specifically. I have contacted google so they can work with NVAccess to resolve this issue. However, things have not come to an end. I find it very good to replace espeak which is no longer relevant at the present time. What do you think because what I share here and is it really relevant?

**Comment by XLTechie** [comment]
I have no comment on Google TTS, though more speech options are always 
desired. But for you to say definitively that eSpeak is no longer 
relevant, is ill informed and absurd. Quite a large number of users find 
eSpeak to both be very "relevant" and preferable in many situations.

As someone who can't stand the false humanity of the Microsoft voices, and 
their robotic nature at high speeds, eSpeak Great Britain Max continues 
to be my synth of choice.

Which is to explain to you, that one person can not judge what another 
person finds "relevant" in speech synths. We all have different histories 
with speech, and different preferences; and place different weight on 
various qualities of speech synthesis.

**Comment by cary-rowen** [comment]
ESpeak's Chinese voice is very unbearable. I don't like it!

**Comment by Brian1Gaff** [comment]
Yes indeed, I use my voice that i donated to the project Espeak Quincy as it 
is to my ears fast and understandable even on tiny speakers. Obviously we 
would all like the human voices if we were going to enjoy a real leisure 
read, but so many voices are over sincere and that can be really tiresome. 
What a pity the voice in Edge read aloud is not portable and usable from 
outside the system. Some friends of mine still use Eloquence sound alikes or 
the voice itself, but to me it has a lisp which makes it hard to understand, 
so you see we are all different, and Espeak may have poor us accents, but 
most of the others are fine in UK English.
 For the record I also designed Auntie as a bit of a laugh. Who says you 
cannot have a bit of fun?

Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by NVCDevelopmentTeam** [comment]
Perhaps I say a bit negatively, although espeak supports Vietnamese language, it actually reads with no quality at all and is not clear at all. Although it has three voices from all three regions, it is very livid. I need a more precise voice. Vocalizer has Vietnamese language but it is very uncomfortable to read and not suitable for me. In short, google tts will be what I want at this time. Foreigners themselves don't know Vietnamese and they don't care about voice quality but I do. IT needs to be replaced at this point. Eloquence is very good but does not support Vietnamese so I cannot use it for the purpose of reading Vietnamese text content and English does not need to be discussed anymore because it is very good.

**Comment by seanbudd** [comment]
From what I can tell, using Google TTS requires an API key ([4 million characters/month free](https://cloud.google.com/text-to-speech/pricing)) and internet access. I think this could be done as an addon at the very least, but it would require some technical knowledge (and a credit card) for an NVDA user to make their own API key to use with the addon.

**Comment by josephsl** [comment]
Hi, if so, I think it would be better to ask the add-ons community to look into this, although I think folks might be a bit hesitant given a really mixed experience with add-ons that relied on API keys and API themselves. Thanks.

**Comment by NVCDevelopmentTeam** [comment]
I find google tts to read Vietnamese very well, myself a foreigner who has worked in Vietnam for many years and I need those. I see, google tts can recognize language automatically by domain. I like it can run through NVDA. I have worked with google and NVAccess to swap it out with NVDA but it has limited integration because it's an online API. I believe there is a solution anyway. I need something that can bring in google tts to complement the new tts stuff.

**Comment by zstanecic** [comment]
Hi,

What about the Vocalizer voice Linh?

It can be bought from codefactory.

**Comment by NVCDevelopmentTeam** [comment]
I know, the vocalizer has Vietnamese but it doesn't read well and the pronunciation is not standard, incorrect spelling, not right for native speakers. I need an accuracy. I see, google tts will be some new voice reading. I know, google has a powerful tts toolkit and I want it in NVDA because it is very familiar to the blind in Vietnam. I hope you understand that.

**Comment by alexarnaud** [comment]
To complete what @seanbudd said, Google TTS seems to not have Windows version so you need to call a server each time NVDA needs to speak something which could slow down the speech process, and after a lot of a speech, it is paid.

For the Espeak issues you've, I suggest you to report bug on the Espeak NG bug tracker to make them able to figure out the bugs you've. I tell you that because one of the problem I assume the Espeak NG has is they probably don't speak the language. It is the same problem on French language, there were many bugs and I needed to report them to make them figured out.

At the end, I think it wouldn't be really efficient to have Google TTS while Google doesn't provide a Windows version.

**Comment by NVCDevelopmentTeam** [comment]
I completely agree with your opinion. However, with google probably coming up with an offline API for google tts then integrating it into NVDA is very possible. So in the near future maybe everything will be resolved. As long as the developers work well together, all problems will be solved. I'm used to using google tts in android and i hope everything is fully integrated. There will be a big change if espeak has a clear voice. English may be good but it sucks in other languages. This hinders my learning Vietnamese. I need something that can read this content. Like I said, google tts is a powerful tool. I will contact espeak as soon as I get a reasonable reply.

**Comment by alexarnaud** [comment]
@NVCDevelopmentTeam Why do you think Google TTS will be released on Windows? Do you have any information about it?

If you have no information, I'd propose to close this issue while Google TTS is not available on Windows. I personally don't think Google TTS will be released on Windows but indeed it's just my own assumption.

**Comment by NVCDevelopmentTeam** [comment]
Of course I don't believe there is google tts on windows and i don't expect much of it either but what i am saying here is google will provide users with voice data and offline API so developers can integrate it into their products including NVDA. At the same time, it will be more doable. Because of this, I can't say 100% but I have worked with google disability support team and they have agreed with my opinion, they will forward my issue to google tts development team and they will come up with an offline API in the future but I'm not sure right now but it will happen. I've worked with google's disability support team so, I believe it's going to happen; Before talking with google, I consulted with NVAccess and they will agree if google will provide them with API and offline voice data. I believe any problem will take effect when google have offline API.

**Comment by NVCDevelopmentTeam** [comment]
Previously, I used to use a tts tool called VNSpeak integrated on NVDA developed by engineer Le Anh Tuan for the blind in Vietnam. However, it encountered a condition that it is not compatible with NVDA versions from 2019.3 and above and it is no longer being developed so, I want to find an alternative tts tool for VNspeak. They don't update it anymore and its downside is that the English pronunciation is very bad. I believe google tts do better than them in this regard. I hope, what I say will work.

**Comment by xingkong0113** [comment]
> ESpeak's Chinese voice is very unbearable. I don't like it!
Using google voice synthesizer to replace espeak is a good idea, I don't like the Chinese voice of espeak either.

**Comment by NVCDevelopmentTeam** [comment]
When I was about to post this topic, I really thought that so many people would be interested. I look forward to a progress on integrating google tts into NVDA, I'm glad you support this project. I see there will be a solution to integrate it provided that there is an offline API from google provided otherwise everything is useless.
