### ISSUE TITLE
when creating a portable copy of nvda the installed copy is turned off 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12452]
### Steps to reproduce:
start an installed copy of nvda.
now using the create portable copy item in the nvda tools menu
create a portable copy, make sure the checkboxes:
copy current user settings is checked
start port copy after creation is cleared 
### Actual behavior:
when the portable copy is created the installed nvda is closed 
### Expected behavior:
when the portable copy is created the installed nvda continues to run 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-22877,9a285153

#### Windows version:
19043.1021
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by CyrilleB79** [comment]
I did not test on last alpha.
But testing on 2020.4, I can say that this issue is not present in 2020.4.

@fernando-jose-silva do you have the opportunity to test on 2020.4 to confirm what I am writing?

@seanbudd, @feerrenrut:
It seems this one should be integrated in 2021.1.

**Comment by fernando-jose-silva** [comment]
thanks in 2020.4 the problem does not occur

**Comment by cary-rowen** [comment]
I tested it with Alpha-22877 and it can be reproduced. I think this should be fixed in 2020.1.
Thanks.

**Comment by seanbudd** [comment]
Closed via #12455
