### ISSUE TITLE
Consider <article> as a landmark

### ISSUE THREAD

**Issue by ndarilek** [nvaccess/nvda#12462]
### Is your feature request related to a problem? Please describe.
NVDA does not seem to consider HTML `<article>` tags as landmarks. Forums like Discourse seem to be adding more semantic HTML tags, and being able to jump by article is a quick way to move between posts.
### Describe the solution you'd like
Not sure if there is some semantic reason that the HTML `<article>` tag isn't considered a landmark for the case of jumping to next/previous, but it'd be nice if it could be.
### Describe alternatives you've considered
Articles/posts could certainly be marked up with headings at the relevant/appropriate level, but this doesn't always work, particularly in the case where an article may contain subheadings. Also, it is apparently possible to support article navigation by creating a custom region--the Discourse folks are apparently considering doing this to work around the lack of support--but it seems to me like the article already defines a region and should be considered a landmark.
### Additional context
Here is some HTML that demonstrates the use case. Imagine these articles are larger blocks of unstructured text which may or may not include heading tags. It'd be nice to jump quickly between these with d/D:

```html
<!DOCTYPE html>
<html>

<body>
    <p>This is some text.</p>
    <article>
        <p>First article.</p>
    </article>
    <article>
        <p>Second article.</p>
    </article>
</body>

</html>
```

Thanks.

**Comment by CyrilleB79** [comment]
Hello

Are you aware that NVDA already provides scripts to jump to previous or next article? These scripts do not have any associated gesture by default. But you can assign one to each of them in the Input gesture dialog.
That may be a solution to the issue you are facing.

**Comment by ndarilek** [comment]
Thanks, someone actually pointed me to those this morning, so I'll 
probably assign them. Appreciate the heads-up.


Is there some reason that articles aren't considered landmarks, though? 
It was a bit of a surprise coming from Orca which I believe does 
consider them landmarks, and since there's a separate script, I'm 
probably missing some reason for it.

**Comment by CyrilleB79** [comment]
@leonardder some thoughts?

**Comment by leonardder** [comment]
Well, I think my answer can be quite simple, an article is not a landmark according to the ARIA spec.

MDN states it [as follows](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Article_Role):

> Articles are not considered a navigational landmark, but many assistive technologies that support landmarks also support a means to navigate among articles.

**Comment by ndarilek** [comment]
Got it. Sorry, for some reason I thought it was a landmark and wasn't being considered one by NVDA.

**Comment by leonardder** [comment]
No problem.
