### ISSUE TITLE
speak whats happening with clipboard and select all action

### ISSUE THREAD

**Issue by Holzinger736** [nvaccess/nvda#12461]
I teach working  blind people on computers, Especially beginners want to know if they pressed proper key combinationn. It would be gread to have an option to speak what happens with clipboard (coppied, moved, pasted and selected all notifications announced.

**Comment by ehollig** [comment]
Hello @Holzinger736, you can enable speak command keys under the setting for keyboard to have NVDA announce when keys like shift, ctrl, alt are pressed. Alternatively, there is an NVDA addon called [Clipspeak](https://addons.nvda-project.org/addons/clipspeak.en.html), that provides the functionality you are requesting and announces copy/paste actions.
