### ISSUE TITLE
use multiple braille displays when connected

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#12466]
If possible, when two or more braille displays are connected such as two orbit readers, add the ability for NVDA to use them both together so you could have 40 cells of braille or so multiple students can view the same thing like in a classroom setting.

**Comment by CyrilleB79** [comment]
Hello
There is already an issue open regarding this topic.
If you feel it appropriated, please close this issue and add your comments there to avoid duplicates.
Thanks.

**Comment by surfer0627** [comment]
Perhaps, duplicated of #6614.

**Comment by feerrenrut** [comment]
Closing this in favor of #6614.
