### ISSUE TITLE
Linting issues in config/configSpec.py

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#12470]
Hi,

it's not a bug, so I don't filled the relative template.

Looking at configSpec.py some time ago (it's an excellent reference to write add-on config), I noticed some discrepancies; I'm quite sure these not affect the result, but seeing a lot of work on refactoring sources, well... here you are:

* in boolean(default=value), value is sometimes capitalized, sometimes not;
* in string(default=value), value is sometimes quoted, sometimes not (strings in option seem always quoted);
* log levels might be converted into option.

I can provide a PR, if someone tells me what's the better option for each point.

**Comment by feerrenrut** [comment]
@ABuffEr I guess this has just gradually become inconsistent. I don't think it is worth fixing if it isn't causing a problem. I'd suggest checking the docs for configObj to see if there is a consistent recommendation for these.

Here is the section on config spec: https://configobj.readthedocs.io/en/latest/configobj.html#configspec

**Comment by seanbudd** [comment]
Closing as not required. We fix linting issues gradually and the configSpec string is not part of our linted codespace.
It might be worth implementing linting rules for the string, in a separate issue/PR.
