### ISSUE TITLE
How can fl studio work well with NVDA?

### ISSUE THREAD

**Issue by NVCDevelopmentTeam** [nvaccess/nvda#12473]
I have known fl studio as a very reputable electronic music production tool. However, the downside here is that it can't work with NVDA. In your opinion, is there anything that can replace or make it work? I hope this discussion will be of interest to many people.

**Comment by feerrenrut** [comment]
Hi @NVCDevelopmentTeam, since this is more of a question/discussion. Please start a discussion here: https://github.com/nvaccess/nvda/discussions/new

I'm going to close this issue.
