### ISSUE TITLE
NO code, low code future of programming and new technology trends.  

### ISSUE THREAD

**Issue by NVCDevelopmentTeam** [nvaccess/nvda#12477]
### Additional context
You know, in recent years no-code, low-code development platforms have become more powerful and useful. However, there are still difficulties that blind people are facing when accessing no code, low code. The question is, is it suitable for future programmers? How can visually impaired people catch up to this trend? I think it is necessary to build a no-code, low-code development platform specifically for the visually impaired so that they can master everything. From there, it helps to improve work efficiency and remove barriers between professional programmers and non-professionals. I open this problem, hope you can come here to discuss so that we can find the best solution together. As I see it, this trend will prevail within the next few years and we are all waiting for something to happen. I believe, no code, low code will be an effective tool for everyone regardless of who you are, whatever industry you are in, you can also join the no code, low code development model. I'm happy to receive everyone's input and I hope my sharing will help you know more about it.

**Comment by cary-rowen** [comment]
I think you should open a discussion instead of a feature request.
Even if it is a feature request, you should fill in the template according to the template, thank you.
On this topic, it might be more appropriate to start a discussion:
https://github.com/nvaccess/nvda/discussions

**Comment by NVCDevelopmentTeam** [comment]
Ok, I'll look into it. However, I don't understand how to use github very well because I'm using them for the first time. sympathy.
