### ISSUE TITLE
Add Feature Close Screen Reader

### ISSUE THREAD

**Issue by Pantyhose-X** [nvaccess/nvda#12472]
Applied to language learner. Language worker's
Applied to language learning. Pronunciation correction
The mother tongue is not English. Need to learn English, the market is very large

### Is your feature request related to a problem? Please describe.
* Close Screen Reader
* Use alone keyboard Reader https://www.youtube.com/watch?v=YPBn6D6pf78&feature=youtu.be&t=213

**Comment by cary-rowen** [comment]
Difficult to understand, please fill in the requirements according to the template.
In addition, please understand the sleep mode of NVDA+Shift+S

**Comment by feerrenrut** [comment]
I'm going to close this, as it stands it is not descriptive enough. There is a discussion available for those who maybe can help with this request: See https://github.com/nvaccess/nvda/discussions/12335

**Comment by Pantyhose-X** [comment]
> I'm going to close this, as it stands it is not descriptive enough. There is a discussion available for those who maybe can help with this request: See #12335

Turn off the mouse to speak.

**Comment by feerrenrut** [comment]
@Pantyhose-X What is your native language? There may be people who can help you with translation.
