### ISSUE TITLE
When reloading plugins, settings dialogs are created twice.

### ISSUE THREAD

**Issue by TheQuinbox** [nvaccess/nvda#12480]
### Steps to reproduce:
1. Grab the latest code of my Cliptools addon from https://github.com/thequinbox/cliptools
2. Load it into NVDA, and restart.
3. Visit the NVDA menu -> Preferences -> settings. You'll notice CLiptools at the bottom, only once.
4. Reload plugins.
5. Open the settings dialog again
6. You'll notice cliptools pops up twice.
### Actual behavior:
The settings dialog is re-created, or rather, the old instance isn't destroied.
### Expected behavior:
The old instance of the settings dialog to be destroied before creating the new one.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
Latest Alpha
#### Windows version:
Windows 10 2004, 64-bit
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2020.4 does not do this from my testing.
#### If add-ons are disabled, is your problem still occurring?
No, but that's because it's an addon-related bug.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by josephsl** [comment]
Hi, you must define a terminate method inside the global plugin, as reload plugins command will call this method while reloading global plugins (note: I have reviewed this add-on a few minutes ago). Thanks.

**Comment by TheQuinbox** [comment]
Oh, I didn't know about that. Thank you!

For anyone starting off, and not sure how to do this, this was how I did it. Thanks to other addons.
```python
	def terminate(self):
		super(GlobalPlugin, self).terminate()
		settingsDialogs.NVDASettingsDialog.categoryClasses.remove(CliptoolsPanel)
```
