### ISSUE TITLE
Add Report Comments to Input Gestures dialog

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#12483]
### Is your feature request related to a problem? Please describe.

Request from a user to be able to change the Report Comments keystroke from NVDA+alt+c when using Word, so they could do it with one hand (presumably in desktop keyboard layout).

The feature is covered in the User Guide here: https://www.nvaccess.org/files/nvda/documentation/userGuide.html#WordReportingComments

### Describe the solution you'd like

Add an entry to the Input Gestures dialog for this keystroke.

**Comment by CyrilleB79** [comment]
Hi,
On my side (NVDA 2020.4), the entry is already in the input gesture dialog, in the Miscellaneous section.
You need to open the gesture dialog when you are already in the Word document to have it available in this dialog.

**Comment by Qchristensen** [comment]
Oops, I was sure I'd tested this, and from within Word....
