### ISSUE TITLE
Wrong behaviour in word with UIA when navigating tables

### ISSUE THREAD

**Issue by grishakonzalaev** [nvaccess/nvda#12490]
### Steps to reproduce:
1. Turn on UIA in word documents in advanced setting of NVDA.
2. Open document with tables in word 2019.
### Actual behavior:
Bad navigation by pressing CTRL+alt+arrows inside the table.
Synth speeks not in table cell after that I press left or right and next alt+CTR+arrows can move me by not empty cells.
If I move to empty cell, it speeks me not in table. Usual arrows move me normally.
### Expected behavior:
CTRL+alt+arrows should move me by cells.
#### NVDA installed/portable/running from source:
Installable NVDA
#### NVDA version:
2021.1 beta
#### Windows version:
windows 10 version 20H2 (build ОС 19042.985)
#### Name and version of other software in use when reproducing the issue:
Word 2019
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA older versions work normally.
2019.3, 20.1,2,3 work normally.
#### If add-ons are disabled, is your problem still occurring?
no
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
no

**Comment by michaelDCurran** [comment]
After testing, I found that NVDA 2020.4 also contains this bug. This last worked in 2020.3.
I'm investigating why this broke and if it is a quick fix. But most likely we won't address this in 2021.1 as we are too close to the release.

**Comment by michaelDCurran** [comment]
This is not trivial and further investigation is needed. Pushing to at least 2021.2.

**Comment by brunoprietog** [comment]
Hi, this is the same as #11043, it is a well old bug that happens with any version of NVDA from 2019.1 onwards, and only happens with the latest versions of Office that came out around March last year. With previous versions it still works fine, they probably made some change that affected that in Office.
