### ISSUE TITLE
NVDA 2021.1 crashes when attempting to exit from the menu with exit dialog disabled.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#12498]
### Steps to reproduce:
1. Ensure that you have "Show exit options when exiting NVDA" unchecked in the general settings.
2. Activate Exit in the NVDA menu.
### Actual behavior:
NVDA plays an error sound, and standard Windows dialog for application has  stopped working appears.
The following is in the log:
```
Input: kb(desktop):enter
DEBUG - core._terminate (21:07:28.924) - MainThread (8492):
Terminating updateCheck
DEBUG - core._terminate (21:07:28.924) - MainThread (8492):
Terminating watchdog
DEBUG - core._terminate (21:07:28.924) - MainThread (8492):
Terminating globalPluginHandler
DEBUG - core._closeAllWindows (21:07:28.924) - MainThread (8492):
destroying system tray icon and menu
ERROR - unhandled exception (21:07:28.954) - MainThread (8492):
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(470) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "watchdog.pyc", line 184, in _crashHandler
SystemError: <_FuncPtr object at 0x02A16AF8> returned a result with an error set
IO - inputCore.InputManager.executeGesture (21:07:30.184) - winInputHook (1072):
Input: kb(desktop):alt+tab

```

### Expected behavior:
NVDA exits normally.

#### NVDA installed/portable/running from source:
From the launcher

#### NVDA version:
NVDA 2021.1 Beta 1

#### Windows version:
Windows 7 X64

#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None relevant
#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This is new in 2021.1

#### If add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tried

cc @seanbudd

**Comment by seanbudd** [comment]
Closed by #12499
