### ISSUE TITLE
Navigating to static text in browse mode instead of "text after a block of links"?

### ISSUE THREAD

**Issue by Luke-Robinett** [nvaccess/nvda#12506]
Currently, the N key moves to the next text following a block of links when on a web page and in browse mode. This seems like a strange target and often results in skipping over sections of static text that doesn't happen to follow a block of links. Why not just implement this feature as navigating to the next static text in the document? That way, whether the text followed a link, a form control, an image or other non-plain text element, the user could still easily find static text without missing chunks of the content. Indeed VoiceOver on iOS (and I presume Mac OS) has a roter setting for "static text" and it works exactly as I'm proposing here for NVDA. Often times poorly written sites and pages will use plain text where they should be using a header or some other more distinctive symantic tag and it can be hard to navigate these sites without a reliable way to move between blocks of static text.

**Comment by XLTechie** [comment]
+1

**Comment by TechHorseG** [comment]
Oh yes please introduce this essential means of navigation. It would make reading a site flow so much easier, without having to do trial-and-error button presses to get to the next readable bit of text.

**Comment by ctoth** [comment]
I am a big fan of this feature suggestion.
A couple questions:
- If you are in a static text element, say a DIV, and you press n, and there are children elements which are also static text, such as SPAN or P, would you expect to go to the next child, or to the next sibling static text?
- Should comma be extended to jump to the bottom of the current static text?

I'd be happy to pick this up if we can figure out exactly how it should work and if core devs would find this a useful change.

**Comment by Adriani90** [comment]
This is now possilbe via p and shift+p in NVDA 2024.2 Beta, navigating to next or previous text paragraph. Closing as works for me.
