### ISSUE TITLE
Allow escape to close SpeechViewer and BrailleViewer as well

### ISSUE THREAD

**Issue by TheQuinbox** [nvaccess/nvda#12519]
### Is your feature request related to a problem? Please describe.
It's not necessarily a problem, just an inconsistancy. Escape closes the log viewer, and it's also closable with alt+f4 and the system menu. SpeechViewer and BrailleViewer are only closable with the latter 2. It might be good to add this for consistancy.
### Describe the solution you'd like
Escape to also close SpeechViewer and BrailleViewer. The code already exists in logViewer, I just need to port it. Pretty easy, but the guide says to open issue before most PRs.
### Describe alternatives you've considered
None, really, just keep it how it is.
### Additional context
None.

**Comment by feerrenrut** [comment]
I don't think escape should close the Speech viewer or braille viewer. A major use case for these is to leave them open in the background (for sighted developers).

**Comment by TheQuinbox** [comment]
OK. That's why I opened an issue first, wasn't sure. I use it for reviewing large Telegram conversations personally, so wasn't sure for sighted developers.
