### ISSUE TITLE
when I close outlook and then open the nvda start menu it hangs for a few seconds 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12537]
### Steps to reproduce:
open outlook
wait about 10 seconds
close outlook
then press start menu 
### Actual behavior:
nvda is speechless for about 20 seconds, then it works normally again 
### Expected behavior:
nvda should then work normally.
I saw this a few days ago in another office excel program.
On this date I disabled the add-ons and I couldn't reproduce the problem, I disabled several add-ons until I thought that the cause would be the windows 10 app essentials add-on.
However later I saw the same problem in outllok, and I managed to play with the add-ons disabled, as follows log attached, so another issue occurs on my machine.
it's as if nvda was waiting for some process to get back up and running. 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-23069,94b8fa28

#### Windows version:
10 19043.1052
#### Name and version of other software in use when reproducing the issue:
OUTLOOK.EXE, Microsoft Outlook 16.0.14026.20246

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
[outlook.txt](https://github.com/nvaccess/nvda/files/6633823/outlook.txt)

**Comment by Adriani90** [comment]
@fernando-jose-silva could you test with NVDA 2021.2? Is it still occuring?

**Comment by fernando-jose-silva** [comment]
a lot has changed since this call, I am now using the latest nvda alpha, windows 11 22000, and I believe that at this time the office has also updated.
Now I haven't noticed the problem anymore, I'm closing at the moment, if I notice it again, I'll reopen it.
