### ISSUE TITLE
MS Excel via UI Automation: no support for insert comment (shift + f2)

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#12546]
### Steps to reproduce:
1. Open excel.
1. press shift + f2 to insert comment.
1. Type string.
1. Press left / right arrow to move caret.
1. Press say all command nvda + a (laptop)
#### Actual behavior:
speech: No response.
#### Expected behavior:
speech: report current character / execute say all command
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2021.1 beta2
#### Windows version:
Windows 10 20H2 (10.0.19042)
#### Name and version of other software in use when reproducing the issue:
Microsoft 365: 16.0.14026.20270
#### NVDA settings
advanced → checked (Use UI Automation to access Microsoft Excel spreadsheet controls when available
#### log message:
```
Input: kb(laptop):shift+f2
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (11:49:50.593) - winInputHook (13820):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (11:49:50.787) - winInputHook (13820):
Input: kb(laptop):NVDA+a
DEBUGWARNING - speech.sayAll._SayAllHandler.readText (11:49:52.163) - MainThread (348):
Unable to make reader
Traceback (most recent call last):
  File "speech\sayAll.pyc", line 178, in __init__
  File "documentBase.pyc", line 22, in makeTextInfo
  File "textInfos\offsets.pyc", line 470, in __init__
  File "textInfos\offsets.pyc", line 249, in _getCaretOffset
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "speech\sayAll.pyc", line 101, in readText
  File "speech\sayAll.pyc", line 180, in __init__
NotImplementedError: Unable to make TextInfo: 
IO - inputCore.InputManager.executeGesture (11:49:55.388) - winInputHook (13820):

Input: kb(laptop):tab
IO - speech.speech.speakTypedCharacters (11:49:55.488) - MainThread (348):
typed word: change
IO - inputCore.InputManager.executeGesture (11:49:55.589) - winInputHook (13820):
Input: kb(laptop):enter
IO - inputCore.InputManager.executeGesture (11:49:56.347) - winInputHook (13820):
Input: kb(laptop):escape
IO - speech.speech.speak (11:49:56.660) - MainThread (348):
Speaking ['cell', 'has comment', CancellableSpeech (still valid)]
```

#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.
#### If add-ons are disabled, is your problem still occurring?
Yes.

**Comment by feerrenrut** [comment]
This does look like an issue, however we'll look at this in 2021.2 because it is in an early access feature that is not enabled by default. Thanks for reporting it @surfer0627.

**Comment by michaelDCurran** [comment]
What is the exact version of Excel you are using?
For me, with UIA for Excel advanced setting in NVDA enabled, and in Excel pressing shift+f2 on a cell, NVDA announces edit, and then I can type / read the note.
My Excel version is:  
```
Microsoft® Excel® for Microsoft 365 MSO (16.0.14329.20000) 64-bit 
```

**Comment by seanbudd** [comment]
This has been fixed in the latest stable Excel version. Considering this is an experimental feature, I am closing this issue.
