### ISSUE TITLE
Announce all second values on the slider when cropping videos in the photos app 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12555]
### Steps to reproduce:
open a video in the app photos native application windows 10.
Walk with tab to edit, and in the menu choose press enter then the first option:
Cut your video, focus on the best moments
walk with tabe until nvda informs
Start of sliding section 0
now walk with the right arrow keys to advance the seconds 
### Actual behavior:
nvda is muted and doesn't announce anything, when we get to whole seconds like 1, 2, so on, nvda announces the integer second 
### Expected behavior:
nvda should announce all values in this slider, including intermediate seconds 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-23112,0d98162d

#### Windows version:
10.0.19043.1055
#### Name and version of other software in use when reproducing the issue:
Microsoft.Photos.exe, Microsoft.Windows.Photos 2020.20120.4004.0

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
[video.txt](https://github.com/nvaccess/nvda/files/6665863/video.txt)

**Comment by Adriani90** [comment]
@fernando-jose-silva are you still having this issue in the newest Microsoft Photos app update?

**Comment by fernando-jose-silva** [comment]
If I understood correctly, video editing in the Photos app no ​​longer exists, now it is in the Clipchamp app.

**Comment by Adriani90** [comment]
Yeah you are right, and in clipchamp this issue is not occuring according to my tests with NvDA 2024.4.1. Closing as invalid since this functionality is not part of the foto app anymore.
