### ISSUE TITLE
Internet Explorer and Firefox cannot agree if some links exist or not, but they do..

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1257]
**Reported by briang1 on 2010-12-05 17:34**
http://www.nvda-project.org/log/main?verbose=on&rev=main,395
6
This page will show it. I'm using IE7, but as one cursors through the  details of the changes, there are spurious links spoken. I know they are not real as you can't tab to them and Firefox does not see them.

**Comment by ehollig** [comment]
@Brian1Gaff, is this still an issue?

**Comment by ehollig** [comment]
I am closing this as invalid, as the original author has not replied in over a year and we still require additional information to reproduce this issue.
