### ISSUE TITLE
German: Wrong translations in symbols.dic

### ISSUE THREAD

**Issue by adkurz** [nvaccess/nvda#12578]
In the latest master commit, in the file locale\de\symbols.dic, there are some wrong translations. All phrase endings are in English, not in german,. Please add the right translations again.

**Comment by CyrilleB79** [comment]
Hi
Please give an example of an erroneous line and what you are expecting for this line.
For next time, please use the template. Indeed, these questions were in the template and thus they would be already answered.

**Comment by adkurz** [comment]
Sorry, I was to fast. The problem is fixed now with a commit from 2021-06-25.
