### ISSUE TITLE
NVDA crashes when reading unsupported fonts or emojis.

### ISSUE THREAD

**Issue by VBMaster311** [nvaccess/nvda#12587]
NVDA crashes when reading unsupported fonts or emojis without any warning or something. I don't know is this NVDA or windows bug, but please try to fix it.

**Comment by josephsl** [comment]
Hi, can you tell us how we can reproduce the issue you are experiencing? That way folks on different configurations can try reproducing this. Thanks.

**Comment by feerrenrut** [comment]
Hi @VBMaster311 in future please fill out the issue template. The information requested in the template is vital to us being able to fix the issue. If NVDA is crashing [please attach an NVDA log (and also the crash dump file if it exists)](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps)

**Comment by VBMaster311** [comment]
I fix it. I switch to Microsoft OneCore Voices and that was fix bug. That was another error with Vocalizer Lana.

**Comment by XLTechie** [comment]
Please report to the developer of the voice (Code Factory, I believe).
