### ISSUE TITLE
Add support for Windows 11

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#12585]
Hi,

This issue serves as a meta issue for Windows 11 related discussions:

### Background:
On June 24, 2021, Microsoft introduced Windows 11. This is an enhanced version of Windows 10 with UI tweaks and internal changes.

### Is your feature request related to a problem? Please describe.
To be confirmed (and updated accordingly): Windows 11 is Windows 10 with tweaks, therefore Windows NT kernel (system) version is 10.0. This means NvDA will recognize Windows 11 as Windows 10.

### Describe the solution you'd like
Extend winVersion module and friends to recognize Windows 11, preferably as part of or as a follow-up to #12544. 

### Describe alternatives you've considered
None

### Additional context
Windows 10 will be supported for a while, and the overall implementation can change based on system internals.

Thanks.

**Comment by Nikita34196** [comment]
hi. Are you planning to add nvda to the new microsoft store? as I understood there now you can publish win32 programs without changes. and it will be possible to add a full version of nvda

**Comment by josephsl** [comment]
Hi,

NVDA and Microsoft Store: @MichaelDCurran, any comments?

Thanks.

**Comment by seanbudd** [comment]
>hi. Are you planning to add nvda to the new microsoft store? as I understood there now you can publish win32 programs without changes. and it will be possible to add a full version of nvda

It would be good to create a new issue regarding this, with more information on what has changed, such as links to announcements.

**Comment by leonardder** [comment]
Windows 11 has been there for a year now and this issue is getting stale. I'm closing it as completed. If there's anything specific to Windows 11 we can easily create a new issue. There is no need for a meta issue.
