### ISSUE TITLE
Tabbing between focusable elements in the Windows Mail HTML viewer breaks browse mode

### ISSUE THREAD

**Issue by ctoth** [nvaccess/nvda#12589]
### Steps to reproduce:

- Press enter on a message with multiple links in it to open it in the message viewer.
- Press tab and shift+tab several times to navigate between links
- Attempt to use arrow keys to navigate regularly

### Actual behavior:

NVDA gets ... stuck? only allowing you to read the line surrounding the link until you alt tab out and back into the message.

### Expected behavior:

NVDA should act as it does in other webviews

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.4

#### Windows version:
Version Dev (OS Build 21390.2025)
#### Name and version of other software in use when reproducing the issue:
Windows Mail

#### Other information about your system:

Device name	Empiricist
Processor	AMD Ryzen 9 5950X 16-Core Processor               3.70 GHz
Installed RAM	128 GB
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

#### Does the issue still occur after restarting your computer?
Yup

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This has been a persistent issue for several versions
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment]
@ctoth can you reproduce this issue with NVDA 2023.1 or last alpha in Windows Mail? You can download the last alpha for testing purposes at this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Adriani90** [comment]
I could not reproduce this issue and we didn't get any updates from the initial author since more than 2 years. Closing as abandoned. if you are still having this issue, please comment and we can reopen.
