### ISSUE TITLE
Chrome: form select element, first option is skipped if there is a option with hidden set.

### ISSUE THREAD

**Issue by hessj1** [nvaccess/nvda#12593]
### Steps to reproduce:
open chrome Version 91.0.4472.114 (Official Build) (64-bit) (works in firefox)
In the following exampled highlight the select and press space to expand.
press arrow down and note that Symptoms is highlighted visually but "Medication concerns" is read

```html
 <select class="select" id="location">
      <option hidden>Choose an option</option>
      <option value="Symptoms">Symptoms</option>
      <option value="Medication_Concerns">Medication concerns</option>
      <option value="General_Health_Questions">General health questions</option>
      <option value="Test_Results">Test results</option>
      <option value="Diet">Diet</option>
      <option value="Appointment_Schedule">Appointment schedule</option>
      <option value="Resources">Resources</option>
    </select>
```

[Code sandbox example](https://4qywr.csb.app/)

### Actual behavior:
Item is highlighted but reader announces item below it.

### Expected behavior:
item highlighted is read.

#### NVDA installed/portable/running from source:
NVACCESS - installed

#### NVDA version:
v2020.04

#### Windows version:
windows 10 v21H1
![image](https://user-images.githubusercontent.com/51164301/123838368-ed8ee580-d8d9-11eb-8570-08248f1b4617.png)

#### Name and version of other software in use when reproducing the issue:
chrome Version 91.0.4472.114 (Official Build) (64-bit)
edge Version 91.0.864.59 (Official build) (64-bit)

_works in firefox v89.0.2 (64-bit)_
#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No worked in the past though not sure if a change in chrome or NVDA 
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment]
This works as expected now in Chrome 127 and NVDA 2024.2. Closing as works for me. if you are still having this issue, please comment and we can reopen.
