### ISSUE TITLE
testdisk-app accessibility 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12596]
### Steps to reproduce:
I was looking for a file recovery tool, and the testdisk software was indicated.
download the software from the link:
https://www.cgsecurity.org/testdisk-7.1.win.zip
Unzip the file, and run the program in the executable:
testdisk_win.exe
a prompt window will be displayed where you are guided to walk with the arrows and press enter on the desired function. 
### Actual behavior:
when walking with the arrows only heard in white, sometimes nvda announces some option but it is rare. 
### Expected behavior:
nvda could read the options when walking with the arrows
If nvda could extend access to this tool, and also to other tools that use this form of interaction, arrow navigation through a prompt.
Sorry if I'm being too shallow, I have no programming skills, I'm just a curious user, and willing to help nvda. 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-23227,dbd6c119

#### Windows version:
10.0.19043.1081
#### Name and version of other software in use when reproducing the issue:
testdisk_win.exe, TestDisk 7.2

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
log:
[nvda.log](https://github.com/nvaccess/nvda/files/6736668/nvda.log)

**Comment by fernando-jose-silva** [comment]
yes, so far no response, I find it difficult for an ordinary person to respond, this response usually comes from a company-to-company communication.
If you believe that nv access cannot act, feel free to close the call.

**Comment by seanbudd** [comment]
Closing as needs external fix from the authors of the software
