### ISSUE TITLE
Selection + Speak Typed Words issue

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1259]
**Reported by txt on 2010-12-06 05:06**
When Speak typed words under Keyboard Settings is enabled, and you have some amount of text selected, and you type some text, the first character you type is cut off.

One such test case I did involved the following key presses on windows XP:
Ok[speech output is something like:
Ok
selecting Ok 
selection removed
k

It seems to happen the same way no matter what word you replace "Ok" with.

It also seems to sometimes happen even if you press delete or backspace before typing the new word, eg:
Ok[space](space][shift+ctrl+left]Ok[space]

The)[through debugging logs and the source code, I think the reason this happens is that the program seems to register the first character of the new word typed (eg the 'O' in the second "Ok" in the above examples) before it says "selection removed," and apparently the function speakText() (which is used by speakMessage() which is in turn given the message "selection removed") clears out the current word (using curWordChars=[](shift+ctrl+left][Backspace]Ok[space]

Looking)).

I'm not sure why it still does this even when you press backspace (or delete) before typing the second word, though. I can only guess that that's a separate error with updating selections.

**Comment by dkager** [comment]
Can still reproduce. Short and clear STR:

1. Open Notepad
2. Type `ok`
3. Press ctrl+shift+leftArrow
4. Type `ok` again
5. Press space

Expected: you hear "ok".
Actual: you hear "k".

**Comment by fisher729** [comment]
@Adriani90  no, not related to #8559 at all. I can still reproduce this issue, by the way, even as I type this.

**Comment by Adriani90** [comment]
I cannot reproduce this in NVDA Version: alpha-20045,a335297e with Notepad or in any browser. In MS Word it does work correctly as well, although there NVDA does not report when the selected becomes unselected. But this is another issue.
@fisher729 can you still reproduce this with last NVDA alpha?

**Comment by fisher729** [comment]
Hi.

This issue seems to have been resolved in the latest stable and alpha releases. As a side note, I should hunt down and comment on an issue where NVDA is announcing previously typed text when speaking typed words.

**Comment by Adriani90** [comment]
Thanks for reporting. Closing as works for me.
