### ISSUE TITLE
Present sheet names in a list to allow for faster workbook browsing

### ISSUE THREAD

**Issue by pranavlal** [nvaccess/nvda#12612]
### Is your feature request related to a problem? Please describe.
Yes. I get workbooks from various  colleagues and from other projects. I need to quickly see what sheets are present and to navigate to them. I also need to put sheet names into documents so need to spell them.
### Describe the solution you'd like
Present sheet names in a list so that I can scroll through them and copy individual names to the clipboard.
### Describe alternatives you've considered
I navigate sheets with ctrl + page down and ctrl + page up. No way to  see the spelling of sheet names.

**Comment by lukaszgo1** [comment]
This is possible already. You can list sheets from the elements list (NVDA+F7) and press F2 on a given sheet to select and copy its name.

**Comment by pranavlal** [comment]
Oh, I did not know about the f2 functionality. Thanks.

**Comment by lukaszgo1** [comment]
@pranavlal If the list displayed with NVDA+F7 fulfills your needs please close this issue.

**Comment by Adriani90** [comment]
This works just fine with the elements list. Note that if oyu enable the UIA support for MS Excel in advanced settings, you can view and edit the list of sheets by pressing f6 in MS Excel 365. I am closing this issue as works for me.
