### ISSUE TITLE
AOL 9.6 With NVDA Main 2011.1

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1261]
**Reported by tmatthews on 2010-12-06 16:07**
NVDA currently does not expose virtual buffer controls with AOL dialogs, such as the Startup Settings Dialog, or the Sign On Welcome Screen.
Also, if signed out of AOL, the menubar works as expected when pressing the alt key, focusing you to the first item, being File menu. However while inside AOL if logged in, pressing the alt key will take quite a bit of time speaking the first item, if at all. 
Sometimes, it won't even do that!
Finally, pressing alt-f4 doesn't close the program. It instead takes you to the "services" menu, however you don't know that, until you press the escape key, where then the menu bar is readable. 
A log will be attached to this ticket, demonstrationing these problems.

**Comment by dkager** [comment]
Any Online Americans have experience with [the latest version](https://discover.aol.com/products-and-services/aol-desktop-for-windows)? If not we can probably close this as outdated.

**Comment by leonardder** [comment]
Closing for now. Please start a new issue for the most recent version of this software if results are still unsatisfactory.
