### ISSUE TITLE
in whatsapp desktop application when in focus mode when walking with tabe is not focused all available controls 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12634]
### Steps to reproduce:
install whatsapp from whatsapp website, 64bit
Connect your phone, make sure that nvda is in focus mode and walk with tabe through the whatsapp interface
note:
that you will go through:
Open emoji panel button
tab
blank editable multiline section
now return with shift + tabe to the button
Open emoji panel button
put nvda in browse mode and this with the arrows and note that you will go through several options not found when browsing with only tabe in focus mode:
Open emoji panel button
navigation mode
button Open GIF Panel
button Open the sticker panel
attach button
enter a message
editable multiline section 
### Actual behavior:
if you are in focus mode and walk with tabe you will find the options:
Open emoji panel button
tab
blank editable multiline section
### Expected behavior:
if you are in focus mode and walk with tabe you will find the options:
Open emoji panel button
button Open GIF Panel
button Open the sticker panel
attach button
enter a message
editable multiline section

#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-8,b8b88b0d

#### Windows version:
10.0.19043.1083
#### Name and version of other software in use when reproducing the issue:
WhatsApp.exe, WhatsApp 2.2123.8

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by feerrenrut** [comment]
What makes you think this is an NVDA bug, and not a WhatsApp bug?

**Comment by fernando-jose-silva** [comment]
I believe that nvda should provide the user with the same amount of controls regardless of nvda's focus or navigation mode.  I propose to analyze this issue with the eyes of a novice user, the user enters the application, nvda is in focus mode, he navigates with tabe, and see some controls, now he tries to use the arrow keys on the buttons but he can't find one anymore control, so for him the application is over.  however this is not true, there are many more options to achieve in browse mode, novice user should not be required to test focus mode and browse in all applications, to be honest when you explain focus mode and application and what you have that testing both modes in this case of whatsapp the user's face of confusion is almost visible.  Regardless of whether the problem is with nvda or whatsapp I believe that nvda should support more the novice user.  Firstly investigating whether this issue really shouldn't be fixed by nvda, coming to the conclusion that it's a whatsapp problem, nvda should think about how to improve the application's use always thinking with the head of a novice user.  nvda could: switch to browse mode when focus is on buttons.  Advise the user that there is more to know in navigation mode or with the arrows logically by making the arrows focus on the buttons currently reachable only in navigation mode.  I didn't just get it out of my head, when I noticed this problem I was teaching a novice user.  later I will try to request support from whatsapp.  I'm not a programmer.

**Comment by fernando-jose-silva** [comment]
##- WhatsApp Support -##
Hi,
Thanks for your message.
Your experience is important to us. We're constantly working on improving our products. To stay updated with current and upcoming features, please visit our blog and Help Center frequently.
If you have any other questions or concerns, please feel free to contact us. We'll be happy to help!
 
good afternoon dears
I was using whatsapp desktop along with the nvda screen reader, and I noticed two problems:

When putting the nvda screen reader into focus mode and navigating with the tabe key it is not possible to put focus on various controls in the whatsapp interface.

Steps to reproduce:
install whatsapp from whatsapp website, 64bit
Connect your phone, make sure that nvda is in focus mode and walk with tabe through the whatsapp interface
note:
that you will go through:
Open emoji panel button
tab
blank editable multiline section
now return with shift + tabe to the button
Open emoji panel button
put nvda in browse mode and this with the arrows and note that you will go through several options not found when browsing with only tabe in focus mode:
Open emoji panel button
navigation mode
button Open GIF Panel
button Open the sticker panel
attach button
enter a message
editable multiline section
Actual behavior:
if you are in focus mode and walk with tabe you will find the options:
Open emoji panel button
tab
blank editable multiline section
Expected behavior:
if you are in focus mode and walk with tabe you will find the options:
Open emoji panel button
button Open GIF Panel
button Open the sticker panel
attach button
enter a message
editable multiline section
System configuration
NVDA installed/portable/running from source:
instaled
NVDA version:
nvda.exe, NVDA alpha-8,b8b88b0d
Windows version:
10.0.19043.1083
Name and version of other software in use when reproducing the issue:
WhatsApp.exe, WhatsApp 2.2123.8

I contacted the nvacces team that develops the nvda screen reader, and was asked to see with the whatsapp support team if the issues are caused by the whatsapp app.
follows the github ticket access link created for the nvda team.

https://github.com/nvaccess/nvda/issues/12634

again when using whatsapp together with the nvda screen reader i noticed another problem, when the screen reader is in hover mode it cannot read the label of some controls.
Again, when contacting the nvaccess team through github, it was suggested to check with the whatsapp team the possibility of the problem being with the whatsapp app.

Steps to reproduce:
install whatsapp on your computer, 64bit version obtained from whatsapp website.
nvda is configured not to enter focus mode automatically.
the configuration
Automatically position the system focus on focusable elements
is disabled
open whatsapp, connect your phone.
choose a conversation and:
walk with tabe to the button
Open emoji panel button
change nvda to browse mode.
walk with the arrows below to:
attach button
press enter.
now walk with the arrows to up and notice some buttons being read only as button, the button labels are not read.
now put nvda in focus mode and continue to navigate the buttons with the arrows, see now that the labels are read.
Actual behavior:
when nvda is in browse mode the button labels are not read
Expected behavior:
button labels must be read in browse mode and focus mode
System configuration
NVDA installed/portable/running from source:
instaled
NVDA version:
nvda.exe, NVDA alpha-8,b8b88b0d
Windows version:
10.0.19043.1083
Name and version of other software in use when reproducing the issue:
WhatsApp.exe, WhatsApp 2.2123.8

follow the github link for this second issue open to the nvaccess team

https://github.com/nvaccess/nvda/issues/12633

I would like to ask the whatsapp accessibility team to investigate these two issues and fix them if possible.
If the problem requires changes by nvaccess with the nvda screen reader, I would like to ask you to contact nvaccess in order to suggest the necessary fixes, I believe that whatsapp accessibility team has much more credibility to suggest changes .
I'm not a programmer.
The use of whatsapp in Brazil is very large.
Sorry for the flawed English, this is not my native language, these writings support the use of google translator.

--
Atenciosamente Fernando Silva.
request #61300297858570

**Comment by fernando-jose-silva** [comment]
##- WhatsApp Support -##

Hi,

Sorry for the delay! We've received many emails recently. We do our best to answer them all. Thanks for your patience.

Thank you for reaching us and letting us know the different problems you are experiencing. I have escalated your feedback to our team to investigate the problems.

If you have any other questions or concerns, please feel free to contact us. We'll be happy to help!

Valentina 
WhatsApp Support Team

Take a look at our Help Center!

**Comment by Adriani90** [comment]
@fernando-jose-silva Do you still have this issue in Whatsapp  desktop version? I guess the developers of Whatsapp need to put tabindex attribute on all interactive elements such as buttons. Did you write this to them?
Here is more about tabindex:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

**Comment by fernando-jose-silva** [comment]
This problem has been solved, WhatsApp has significantly changed its interface, and now it is impossible to use the navigation mode in the app, and navigating with tabs and comparing it to object navigation it seems that it is possible to reach the entire interface if you move tabs and arrows.
Thank you very much.
