### ISSUE TITLE
Screen wrap when in web browsers

### ISSUE THREAD

**Issue by KevGP** [nvaccess/nvda#12650]
### Is your feature request related to a problem? Please describe.
No
### Describe the solution you'd like
NVDA should bounce back up to the first item in a webpage, when I press a command for the item after the last one. For example, H for heading currently says no next heading, but I'd like it to bounce me back to the 1st one.
### Describe alternatives you've considered
Current behavior, where NVDA remains stuck at the last item.

**Comment by Brian1Gaff** [comment]
This has been asked for many times or at least a toggle to change behaviour 
to  and from this. Jaws and other screenreaders  wrap back but can also make 
a sound to indicate its  going to do that.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "KevGP" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Thursday, July 15, 2021 6:08 AM
Subject: [nvaccess/nvda] Screen wrap when in web browsers (#12650)

**Comment by ehollig** [comment]
This has been recommended previously, #846. There may be an NVDA addon out there that provides this functionality.
