### ISSUE TITLE
Feature request: Generate NVDA development environment using docker

### ISSUE THREAD

**Issue by xingkong0113** [nvaccess/nvda#12659]
### Is your feature request related to a problem? Please describe.
The current NVDA development needs to install a very complicated development environment, first is to install visual studio, then python, and finally a whole bunch of system support libraries.
### Describe the solution you'd like
It is recommended to use [docker](https://www.docker.com) to unify NVDA's development environment into a docker container.
This allows both developers and translation maintainers to use this image to generate, and test NVDA code and translations.
### Describe alternatives you've considered
none
### Additional context
none

**Comment by lukaszgo1** [comment]
As far as I understand NVDA would require Windows containers to be used and therefore would require Docker Desktop. This is rather problematic as Docker desktop has pretty strict system requirements i.e. Pro version of Windows 10 and CPU with support for SLAT. Requiring all contributors to have these as a minimum seems pretty unreasonable to me.
