### ISSUE TITLE
Braille input with NVDA isn't always correct

### ISSUE THREAD

**Issue by Futyn-Maker** [nvaccess/nvda#12667]
### Steps to reproduce:

1. Open NVDA braille settings and choose, for example, "unified English braille grade 1" as an input braille table (generally relevant for all braille tables).
2. (for UEB) input with a braille display keyboard: ⠐⠣⠠⠉⠐⠜ (5-126-6-14-5-345). Another example: ⠐⠣⠼⠁⠐⠜ (5-126-3456-1-5-345). And many other examples.

### Actual behavior:

For the first example: NVDA says: "Input isn't supported" when I try to input the caps indicator (dot 6) after '(' (dots 5-126) and ignores my input.
For the second example: NVDA says "Input isn't supported" when I try to input the number sign (3456) after '(' (5-126) and ignores my input.
Generally: something goes wrong with input multicellular signs after parentheses, quotes, brackets, dashes and other symbols. 

### Expected behavior:

Input should be processed correctly, number signs, caps indicators and other parts of multicellular symbols shouldn't be ignored.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.1
#### Windows version:
10
#### Other information about your system:
I use the Focus 40 (4th generation) braille display.
#### Does the issue still occur after restarting your computer?
Yes
#### If add-ons are disabled, is your problem still occurring?
Yes (including BrailleExtender)
### Other comments

I've found this problem when working on Russian Liblouis tables, but it's actual for all input tables.
It doesn't seem to be a problem of Liblouis because back translation in other programs used Liblouis (including lou_translate.exe) works correctly. I think that the problem is in how NVDA processes Liblouis tables.

**Comment by feerrenrut** [comment]
@leonardder Do you have any insight into this issue? I'd love to know if someone with a different braille display can reproduce the issue.

**Comment by seanbudd** [comment]
Reopened due to #12742 being reverted by #12789

**Comment by lukaszgo1** [comment]
@Futyn-Maker  Would you be able to test [with this try build](https://ci.appveyor.com/api/buildjobs/3i42a0c1o3iscgv0/artifacts/output%2Fnvda_snapshot_pr12850-23759%2C1b1d34ea.exe)?

**Comment by Futyn-Maker** [comment]
@lukaszgo1 Seems to work as expected, without problems.        Thanks!
