### ISSUE TITLE
Aria atomic ignored in Chrome on sibling node change

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [nvaccess/nvda#12704]
### Steps to reproduce:
This fiddle updates node HTML on button click:

https://jsfiddle.net/wzm5y46x/

This fiddle sets an update timer every 2 seconds to trigger narration, beware:

https://jsfiddle.net/kznhq4v6/

### Actual behavior:

NVDA narrates `Before After` on HTML node updates (every two seconds) even though the `Before` and `After` text nodes have not changed.

### Expected behavior:

Nothing should be narrated on these HTML node updates.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

Thanks to @Xayan-alAmin for originally spotting this issue! The original context was Codecademy's learning environment output terminals constantly narrating `Output:`.

**Comment by feerrenrut** [comment]
Thanks for raising an issue @JoshuaKGoldberg, though I'm a little bit confused. I think this is the expected behavior. 

Both samples have `aria-atomic="true" `
> NVDA narrates Before After on HTML node updates (every two seconds) even though the Before and After text nodes have not changed.

"Before" and "after" are both inside the `aria-live` container.

From https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions#basic-examples-aria-atomic
>aria-atomic="true" ensures that each time the live region is updated, the entirety of the content is announced in full (e.g. "17:34").

From https://w3c.github.io/aria/#aria-atomic
> - false (default): Assistive technologies will present only the changed node or nodes.
> - true: Assistive technologies will present the entire changed region as a whole, including the author-defined label if one exists.

**Comment by JoshuaKGoldberg** [comment]
Oh dear, how embarrassing - I mixed up the true and false values for `aria-atomic`! Confirmed, the examples behave as expected when `aria-atomic="true"` is removed or changed to `false`. 🤦

Thanks for the very informative answer @feerrenrut and sorry to take up your time!

FYI @Xayan-alAmin @katiezutter
