### ISSUE TITLE
NVDA only reads the edited character of the word in Microsoft teams.

### ISSUE THREAD

**Issue by gauravahir28** [nvaccess/nvda#12714]
### Steps to reproduce:
Perform following steps to reproduce this issue in Microsoft teams:
- Open any chat edit field in MS teams.
- type at least 2 words in the edit field for example, I typed (Narrator NVDA).
- Now, as the NVDA cursor at the end, move  cursor anywhere between the "NVDA" word by left arrow key(Make sure you are not at the last character).
- Now, replace  any character from the word "NVDA". for example, I replaced  "N" with "J".
- when the above step is completed, try to read the same word again with ctrl + right/left arrow key.
### Actual behavior:
NVDA only reads the replaced character, not the entire word.
for example, as per the example given in the above steps, NVDA will read only "J" 
### Expected behavior:
NVDA should read the entire word.
for example, as per the example given in the above steps, NVDA should  read  "JVDA".
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA 2021.1
#### Windows version:
Windows 10(21H1)
#### Name and version of other software in use when reproducing the issue:
Microsoft Teams Version 1.4.00.19572 (64-bit). 
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Did not try
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment]
Is this still an issue?

**Comment by gauravahir28** [comment]
Hi @seanbudd - i can still reproduce this issue.

**Comment by Adriani90** [comment]
I cannot reproduce this issue with NVDA 2022.4 and Microsoft Teams 1.6.0. Are you still having this issue with these NVDA and MS Teams versions? Make sure that the MS Teams Window is maximized when reproducing this issue.

**Comment by gauravahir28** [comment]
I cannot reproduce anymore since I am now using new MS teams!
since Microsoft almost have migrated its users to new ms teams, I'll close this issue!
