### ISSUE TITLE
Notification/search speech gets cut off

### ISSUE THREAD

**Issue by ndarilek** [nvaccess/nvda#12711]
### Steps to reproduce:
1. This is an odd one, but check out the Itch client app repository from https://github.com/itchio/itch, run through the setup, and finish by running "npm start".
2. Compiling the NPM package generates a notification in Action Center that the compilation is complete.
3. Attempt to access Action Center via Win+A, or the search/start screen via Win.

### Actual behavior:
Neither speaks anymore. Or rather, it seems to try, but is cut off before it can begin. Restarting NVDA doesn't solve it, and the problem doesn't appear with Narrator. The only fix is to restart my computer.

### Expected behavior:
Notifications should continue reading, and I should get speech feedback when arrowing through or searching.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2021.1

#### Windows version:
Version 21H1 (OS Build 19043.1110)

#### Does the issue still occur after restarting your computer?
No.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If add-ons are disabled, is your problem still occurring?
Yes, all addons are disabled. I did notice that attempting to access the search menu produced the Windows error sound with some addons enabled, but that is gone now. The behavior was otherwise identical.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

Note that this issue has happened in other circumstances as well, but I haven't nailed down a reliable reproduction until I tried to work on the Itch client, which generates a notification when builds finish and reliably seems to trigger this. So it isn't limited to this very specific path.

Here's what I see in the log viewer, with level set to debug, when pressing the Search key. I start from this browser window, from the issue search field. 'Search box', 'edit' logs as being spoken but I never hear it:

Speaking ['Search all issues', 'edit', CancellableSpeech (still valid), 'is:issue is:open ']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (12:25:25.673) - MainThread (3844):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (12:25:25.717) - winInputHook (9820):
Input: kb(desktop):
IO - speech.speech.speak (12:25:25.768) - MainThread (3844):
Speaking ['Start', 'window', CancellableSpeech (still valid)]
IO - speech.speech.speak (12:25:25.774) - MainThread (3844):
Speaking ['Search', 'window', CancellableSpeech (still valid)]
DEBUG - NVDAObjects.NVDAObject._get_placeholder (12:25:25.780) - MainThread (3844):
Potential unimplemented child class: <NVDAObjects.Dynamic_StartMenuSearchFieldSearchFieldEditableTextWithAutoSelectDetectionUIA object at 0x08EA5A10>
IO - speech.speech.speak (12:25:25.781) - MainThread (3844):
Speaking ['Search box', 'edit', CancellableSpeech (still valid), 'blank']
IO - inputCore.InputManager.executeGesture (12:25:25.793) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:25.871) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:25.964) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:26.042) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:26.119) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:26.212) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:26.289) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:26.367) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:26.460) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:26.538) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:26.615) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:26.708) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:26.785) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:26.878) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:26.956) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:27.034) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:27.126) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:27.204) - winInputHook (9820):
Input: kb(desktop):
IO - inputCore.InputManager.executeGesture (12:25:27.276) - winInputHook (9820):
Input: kb(desktop):escape
IO - inputCore.InputManager.executeGesture (12:25:27.282) - winInputHook (9820):
Input: kb(desktop):
IO - speech.speech.speak (12:25:27.369) - MainThread (3844):
Speaking ['Issues · nvaccess/nvda - Brave - Personal', CancellableSpeech (still valid)]
IO - speech.speech.speak (12:25:27.449) - MainThread (3844):
Speaking ['Issues · nvaccess/nvda', 'document', CancellableSpeech (still valid)]
IO - speech.speech.speak (12:25:27.451) - MainThread (3844):
Speaking ['main landmark', CancellableSpeech (still valid)]
IO - speech.speech.speak (12:25:27.452) - MainThread (3844):
Speaking ['search landmark', CancellableSpeech (still valid)]
IO - speech.speech.speak (12:25:27.454) - MainThread (3844):
Speaking ['Issues', 'search landmark', CancellableSpeech (still valid)]
IO - speech.speech.speak (12:25:27.460) - MainThread (3844):
Speaking ['Search all issues', 'edit', CancellableSpeech (still valid), 'is:issue is:open ']

**Comment by feerrenrut** [comment]
Very odd that there are many lines in the log with `Input: kb(desktop):` only. Note these are happening approximately every 100ms.
Keyboard input will cancel speech. It would be worth tracking the source of those keyboard events and understanding why there is no description of the key pressed.

**Comment by seanbudd** [comment]
I built this and couldn't reproduce the issue.

I was about to comment something like what @feerrenrut said above. I can't think of or find a way in code that this sort of thing would be logged in the first place.

**Comment by feerrenrut** [comment]
I suspect there is some application on @ndarilek's system that is sending phantom key press events.

**Comment by ndarilek** [comment]
I don't know enough to definitively dispute this, but again I'll note that it doesn't happen under Narrator. So if it *is* external to NVDA, Narrator seems to handle it better.

Tips on how to either track down such a program, or to rule it out? I don't immediately know of anything I'd be running that would inject keyboard events, and it's odd how this particular notification seems to reliably cause it, but not reproduceably for anyone else.

**Comment by feerrenrut** [comment]
>So if it is external to NVDA, Narrator seems to handle it better.

Yes, it is curios that this is the case. We'd need to know more about these keyboard events to be certain.

> Tips on how to either track down such a program, or to rule it out?

You could start by using spyxx.exe (part of visual studio community 2019) to confirm these keypresses are sent to NVDA.

**Comment by ndarilek** [comment]
Any general pointers on what I should be looking for?


I launched spyxx.exe. I'm guessing I want to go into the log messages 
configuration and ensure that the keyboard messages box is checked, 
which it appears to be. But how do I filter to the specific messages I'm 
looking for? There's a lot here.


Thanks.

**Comment by feerrenrut** [comment]
Ensure that ONLY keyboard messages are checked. Then, when you aren't pressing any keys, there should be no messages. When you do press keys, there should be messages that reflect the keys pressed.

**Comment by ndarilek** [comment]
1. Open up spyxx.exe as an administrator.

2. Arrow down to not select the top-most tree item, because subsequent 
steps don't work if I do.

3. Press Ctrl-m.

4. Check "All windows in system".

5. Navigate to the Messages tab.

6. Click Clear all.

7. Check Keyboard.

8. Click OK.

9. Press a key.


I can't figure out how to view the log. I'm in a window with an unknown 
widget, and the option to clear logs is disabled, suggesting none are 
being captured. What am I missing?


Thanks.

**Comment by ndarilek** [comment]
Aw, figured it out.

I'm storing my gamepad at a slight angle, and if it shifts just the right way, its buttons/d-pad are pressed. And of course, if I don't check it, I find various behaviors that seem to trigger the notification silence reliably. I've confirmed by holding down a button and trying to use NVDA. Interestingly, the behavior only seems to happen in certain places like the start menu, and in what I assume are UWP apps (I.e. the Windows 10 Weather app.)

I've also confirmed that Narrator doesn't exhibit this behavior. Holding down my d-pad buttons and opening the start menu speaks normally.

So maybe the interruption logic should either a) ignore gamepad events completely or b) act on them universally. My gut instinct is that they should be filtered out, since I myself use them in gaming contexts that sometimes leverage NVDA via Tolk, and I'd want the game to manage whether speech interrupts. But there are likely subtleties to that which I'm missing.

Thanks.

**Comment by ndarilek** [comment]
Minor addendum:

The, uh, trigger wasn't the d-pad button. It was the gamepad trigger which caused NVDA not to speak, though the d-padbuttons do as well.

I'd vaguely understand d-pad buttons cutting off speech, though I still don't think they should. I *definitely* don't think the triggers should, though.

**Comment by feerrenrut** [comment]
Glad you got to the bottom of it. I suspect NVDA treats gamepad input as generic input. Please can you give some examples of the values, perhaps it will help us to filter them out.

**Comment by Adriani90** [comment]
@ndarilek are you still having this issue in NVDA 2024.1 Beta with WASAPI enabled?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author upon request since 2.5 years, I am closing this as abandoned.
