### ISSUE TITLE
Problem with ESpeak on NVDA2021.1

### ISSUE THREAD

**Issue by bedenhofer** [nvaccess/nvda#12732]
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Benjamin is working with the alpha Snap shots when I test them, but when I updated to the latest release, Benjamin isn't included in NVDA version 2021.1.

**Comment by seanbudd** [comment]
This is intended behaviour, we have updated espeak since 2021.1. In future, please fill out the issue template properly.

[Check out 2021.2 beta](https://www.nvaccess.org/post/nvda-2021-2beta1/), which also includes Benjamin, and should be included when 2021.2 is released.

**Comment by Brian1Gaff** [comment]
Does this beta actually create a desk top icon, as when I installed it it 
did not do so.
 it also started in espeak.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by seanbudd** [comment]
> Does this beta actually create a desk top icon, as when I installed it it did not do so.

The behaviour should not have changed in this instance, can you create a new issue with confirmation steps and logs?

> it also started in espeak.

This is likely because of our fix for #10451, #12647. If the behaviour is troublesome (eg, NVDA is set to a language that should support oneCore), please fill out an issue template with expected behaviour, your NVDA language, your preferred system languages and installed system languages.

**Comment by lukaszgo1** [comment]
> This is likely because of our fix for #10451, #12647. If the behaviour is troublesome (eg, NVDA is set to a language that should support oneCore), please fill out an issue template with expected behaviour, your NVDA language, your preferred system languages and installed system languages.


I don't thing #12647 is in beta already.

**Comment by seanbudd** [comment]
> > This is likely because of our fix for #10451, #12647. If the behaviour is troublesome (eg, NVDA is set to a language that should support oneCore), please fill out an issue template with expected behaviour, your NVDA language, your preferred system languages and installed system languages.
> 
> I don't thing #12647 is in beta already.

You're right, my mistake. @Brian1Gaff - that espeak issue is quite strange, I assume it may be because oneCore is not installed on your system - I saw it mentioned elsewhere that it was a fresh install of Windows? It would still be helpful to fill out the issue template with the above information.
