### ISSUE TITLE
How to navigate tree view with keys since v2020.4

### ISSUE THREAD

**Issue by SimpelMe** [nvaccess/nvda#12733]
### Steps to reproduce:
- go to https://playground.xwiki.org/xwiki/bin/view/Main
- use key [ h ] til you are reaching h1 "Navigation"
- use key [ tab ] to jump to first tree item

### Actual behavior:
v2020.4/v2021.1: From this point on I can't find any keys to go through this tree, open and close

### Expected behavior:
v2019.1.1: From this point I can use arrow keys to open, close and walk through the tree

#### NVDA installed/portable/running from source:
2019.1.1 portable
2020.4 installed
2021.1 portable

#### NVDA version:
2019.1.1
2020.4
2021.1

#### Windows version:
OS: WIN_10/X64, Build: 19042 2009, OSLang: 0407

#### Name and version of other software in use when reproducing the issue:
Google Chrome Version 91.0.4472.124 (Offizieller Build) (32-Bit)
Microsoft Edge Version 92.0.902.67 (Offizielles Build) (64-Bit)

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes see above

#### If add-ons are disabled, is your problem still occurring?
can't test as the browsers are managed by company

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
I can't as written above computer is managed by company

**Comment by cary-rowen** [comment]
You can use NVDA + Space to enter the focus mode to perform expansion/collapse, but NVDA does not report the expansion/collapse status

**Comment by Adriani90** [comment]
cc: @feerrenrut

**Comment by feerrenrut** [comment]
This is an authoring error on the site:
- Visually there is a down arrow icon that must be clicked to expand the "Blog" item, however it is given role="presentation".
- When in focus mode, the keys are passed through to the underlying application. The item with focus (the anchor "blog") has no change, so nothing is reported. 

It seems like the javascript is used to expand/collapse levels of the tree, however `role=application` isn't used to signify that this is no longer a basic document. When building components with an "application" like UX, the web author has a much greater responsibility. 

There may be some improvement possible for NVDA, but we'll need a minimal sample to demonstrate the specific issue. 

> can't test as the browsers are managed by company

Note, this question refers to NVDA add-ons. I will assume you don't have any installed.

**Comment by Adriani90** [comment]
We didn't get further updates from the initial author, and it seems this issue is rather a web authoring issue and not an NVDA issue. Closing as such.
