### ISSUE TITLE
Problem with NVDA202.1 and microsoft edge chromium

### ISSUE THREAD

**Issue by bedenhofer** [nvaccess/nvda#12734]
### Steps to reproduce:
 press control J to go to the downloads

### Actual behavior: 
Nothing happen's, whatsoever

### Expected behavior: 
in previous versions of NVDA, which was 2002.0, I never had this problem, whatsoever

### System configuration 
desktop PC with an intel processor
#### NVDA installed/portable/running from source: 
the installed version I have is, NVDA 2002.1 and the portable copy I have is 2002.2 of our NVDA snapshots

#### NVDA version:
 202.1

#### Windows version: 
10 home adition 64bit

#### Name and version of other software in use when reproducing the issue: 
microsoft edge

#### Other information about your system: 
it's an HP desktop tower

#### Does the issue still occur after restarting your computer?
 Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors. 
NVDA2002.0 and when you press control J to go to the downloads, and ta one time, you'll see an option to open or save the executable.

#### If add-ons are disabled, is your problem still occurring? 
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu? 
I don't When running NVDA 2002.2 of our snapshots, and you press control J, to go to the downloads, it doesn't bring up the downloads, in microsoft edge, so I can tab to the button to save an executable, whatsoever.know, because I've never messed with it.

**Comment by seanbudd** [comment]
Hi @bedenhofer,

Do you mind going over and correcting all the version numbers listed? None of these are valid NVDA versions, which makes debugging this quite difficult.

**Comment by feerrenrut** [comment]
I can't reproduce the described issue with NVDA 2021.1 and Microsoft Edge Version 92.0.902.73

Pressing `control + j` opens the download dialog, nvda announces:
```
Recent downloads  list  clickable  with 2 items  nvda (8).log  Open file
```

@bedenhofer to ensure this isn't caused by some other change on your machine / edge / configuration. Please can you test the older (previously known to work) version of NVDA again now to confirm the behavior.

**Comment by ehollig** [comment]
Just a friendly reminder for @bedenhofer to provide the requested information in https://github.com/nvaccess/nvda/issues/12734#issuecomment-901508892 and to update us with the NVDA and Edge version being used.

**Comment by seanbudd** [comment]
Closing this as stale and cannot be reproduced
