### ISSUE TITLE
NVDA not focusing to all items in Scan Mode. 

### ISSUE THREAD

**Issue by scharde** [nvaccess/nvda#12739]
### Steps to reproduce:
I have provided codepen example, [link](https://codepen.io/scharde/full/RwVmPyw) 
1. Open NVDA in scan mode.
2. Navigate to legends list, here issue observed with role="listbox"
![image](https://user-images.githubusercontent.com/29042635/129586345-c30e5cfb-a809-4fb6-950d-aa79dd54c94d.png)
3. Press Up and Down arrow, to move backward and forward to legends list. 
  Here only first item is focusing other are not. 

The same issue is with SVG elements as well. 
![image](https://user-images.githubusercontent.com/29042635/129586585-eed17888-b53d-40e2-8cb8-6c932c5ed6ee.png)

### Actual behavior:
In scan mode, all the elements are not focusing. 

### Expected behavior:
It should focus to all the elements in Scan mode.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA 2021.1

#### Windows version:
Windows 10 20H2 (64 bits) build 19042.867

#### Name and version of other software in use when reproducing the issue:
Microsoft Edge Version 92.0.902.73 (Official build) (64-bit)
Google Chrome Version 92.0.4515.131 (Official Build) (64-bit)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes

#### If add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by feerrenrut** [comment]
Thanks for reporting @scharde, and welcome to the NVDA project.

I'm not 100% sure I understand the expectation. Without a screenreader, once the legend has focus (tab until it has a border), I must press right / left arrows to focus the items within the legend.

This matches the behavior in NVDA in focus / forms / applications mode, so far so good.
When in browse mode, the sample is close to unusable, I get the following speech (with reporting of command keys enabled):
```
Browse mode
up arrow
graphic    graphic  clickable    2020/04/30 40%
down arrow
Legends  list  clickable    Debit card numbers (EU and USA)
down arrow
out of frame  clickable
up arrow
main landmark    frame    clickable  Legends  list  clickable    Debit card numbers (EU and USA)
ctrl+right arrow
card 
ctrl+right arrow
numbers 
ctrl+right arrow
(EU 
ctrl+right arrow
and 
ctrl+right arrow
USA)
ctrl+right arrow
out of list  out of frame  out of main landmark  clickable
space
```

I don't see any immediate issues in the accessibility tab in Edge dev tools.

Thanks for including a sample, however it pulls in fabric and other JS that result in unnecessarily complex HTML. Could you please create a minimal test case in plain HTML, and only as much JS as necessary?

We'll need to inspect and understand the HTML, then consider how that is interpreted by the browser mapped to and exposed via OS level accessibility API's (UIA and IA2), then look at how we use this exposed information.

**Comment by Adriani90** [comment]
@scharde could you please respond on the comment above so we can investigate further? Do you still see this issue with NVDA?

**Comment by seanbudd** [comment]
Closing as abandoned. This will be reopened if the required information is provided.
