### ISSUE TITLE
Focus issues reading by paragrph in Google docs involving blank lines

### ISSUE THREAD

**Issue by ainekc** [nvaccess/nvda#12746]
### Steps to reproduce:
1. Make a google doc.
2. Write some words, press enter twice, write something else (and continue pattern as desired for testing).
3. Move around using the previous and next paragraph commands (control+up and control+down)
### Actual behavior:
NVDA announces "blank" not only on the blank lines but on the lines of text as well.
The issue has something to do with the blank lines because if there's two lines of text next to each other,, or a line of text at the bottom of the doc with no blank line underneath, it's announced.
### Expected behavior:
NVDA should focus correctly to read the text.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Version: alpha-23589,c9d6729b

#### Windows version:
Windows 10 Home
Version	21H1
OS build	19043.1165

#### Name and version of other software in use when reproducing the issue:
Chrome Version 92.0.4515.159 (Official Build) (64-bit)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This started recently. Whether as an NVDA update or Chrome update I'm not sure. the reverse used to happen, in fact - paragraphs would double-read on the blank lines.
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by feerrenrut** [comment]
I can reproduce this in the latest alpha `nvda_snapshot_alpha-23598,a4524704` but not in `2021.2 beta 1`. This indicates it is caused by a change in NVDA. @michaelDCurran do you have any suggestions here?

**Comment by michaelDCurran** [comment]
Running a bisect, it looks like it broke in fab35ec3c03038b22c9c288d78520aa03d4f2155.
Report aria-description always pr #12500

**Comment by feerrenrut** [comment]
This would block the release of 2021.3
