### ISSUE TITLE
[Win11] NVDA is not announcing the current day (Sunday, Monday, etc.) properly in the calendar view. 

### ISSUE THREAD

**Issue by SMTestGH** [nvaccess/nvda#12757]
### Steps to reproduce:
1. Press Win+B to navigate to system tray
2. Arrow to date/time control and open with Enter
3. Tab to calendar grid
4. Arrow left/right to a different day

### Actual behavior:
NVDA abbreviates day of week to 2 letters: 26  data item  ‎August‎ ‎2021  row 4  Th  column 5

### Expected behavior:
NVDA reads the date (i.e. 26 and the full day of the week (i.e. Monday, Tuesday)

#### NVDA installed/portable/running from source:
Occurs when installed or portable

#### NVDA version:
2021.1
#### Name and version of other software in use when reproducing the issue:
Windows 11 Insider preview

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, but Narrator screen reader does not exhibit the same issue.

#### If add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by josephsl** [comment]
Hi,

The accompanying pull request also resolves this in Windows 10 (I suspect Version 1909 or later), so looks like an edit to what's new would be great before 2021.3 enters string freeze.

Thanks.

**Comment by seanbudd** [comment]
Thanks @josephsl  - see #12863.
