### ISSUE TITLE
Telegram Is Not Accessible Accept Through Unigram Interface

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#12777]
### Steps to reproduce:
Browse to the web interface of telegram, or try to install it on your pc. Web.telegram.org and telegram app for Windows, though completely built using two different GUI interfaces, share one common problem. Web.telegram.org used to be 100% accessible, and now it is not. Millions of people around the world are switching to telegram after the disaster that has been Microsoft Skype. And quite frankly, we deserve to have windows accessibility be addressed for this app as every other operating system can successfully integrate with it, including Android, IOS, Mac Linux and others.
### Actual behavior:
You can't navigate to different areas where lists of users and groups and channels are.
### Expected behavior:
To interact with web.telegram.org and their desktop app either as a web page, or as a tabbed view list control page.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.1
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
Firefox, Chrome, Edge, Stable
#### Other information about your system:
High Spec Computer
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Snapshot, Beta, same issue
#### If add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by feerrenrut** [comment]
Please report this to the developers of those specific sites. These issues most likely need the website to be fixed, if not, we'll need a much more specific and isolated case to show a bug in NVDA. The case should show that despite the appropriate accessibility information being exposed by the browser, NVDA doesn't use it as expected.

I'm going to close this issue.
