### ISSUE TITLE
Dynamic Content Controls Are Missing Or Not Available

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#12776]
### Steps to reproduce:
Go to a site that has either auto refresh content or in page refresh reloaded content on it. Such as fast.com or speedtest.net.
### Actual behavior:
 In the first example, fast.com does not inform you that there's any refreshed content to view on the page. In the second example, there's no way to silence notifications from speedtest.net when testing the remaining part of your download and upload speed. Yet the first half is silent.
### Expected behavior:
Some way to control auto notifications reliably on web pages. Either ones sent via an alert, like in speedtest.net or ones sent in page, like on fast.com.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2021.1
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
Firefox, Chrome, Edge, Stable
#### Other information about your system:
High Spec Computer
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Snapshot, Beta, same issue across all browsers and versions
#### If add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by feerrenrut** [comment]
Please report this feedback to those sites specifically. NVDA can only use the information made available to it. This bug tracker is for issues that are specific to NVDA. I'm going to close this issue, since there is likely nothing that can be done on NVDA's side to improve this.
