### ISSUE TITLE
Github Is Inaccessible

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#12775]
### Steps to reproduce:
When signed in to your account, navigate to the button to star, watch or otherwise receive notifications about an issue.
### Actual behavior:
NVDA will tell me I've starred or watched an issue even if I haven't.
### Expected behavior:
To accurately tell me to perform an action if I haven't already.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.1
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
Firefox, Chrome, Stable
#### Other information about your system:
High Spec Computer
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Snapshot, Beta, still a problem
#### If add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by TheQuinbox** [comment]
I vote for closing this, it's not an NVDA problem. Both JAWS and narrator suffer from it too.

**Comment by feerrenrut** [comment]
Please report this feedback to GitHub.
