### ISSUE TITLE
Deezer Is Inaccessible

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#12774]
### Steps to reproduce:
Go to Deezer Account Settings. Navigate to Display settings. Try to update check boxes. Or, still while in account settings, try to upload a photo.
### Actual behavior:
Absolutely no state change occurs. It just says clickable.
### Expected behavior:
To be able to interact with the check boxes and photo upload dialog in account settings.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.1
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
Firefox, Chrome, Stable
#### Other information about your system:
High spec computer.
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Snapshot, Beta, same issue
#### If add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by feerrenrut** [comment]
Please report this to the developers of Deezer. If there is a specific issue that stops them from making Deezer accessible with NVDA they will need to raise an issue here.

I'm going to close this issue.
