### ISSUE TITLE
Wifi signal strenght reading

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1279]
**Reported by djblind on 2010-12-15 21:31**
Nvda should read strenght of wifi signal on demand, (like battery status). A new command can be added to perform this.

**Comment by dkager** [comment]
> Do sighted users have easy access to this without clicking something? If so, where?

Yes, in Windows 10 it is part of the visual appearance of the Wi-Fi icon in the taskbar.
So for Windows 10 there is some motivation to add a hotkey.

**Comment by jcsteh** [comment]
Fair enough. I think we'd take code for this, but it's not a priority for us.

**Comment by fisher729** [comment]
Any updates on this?

**Comment by ruifontes** [comment]
Add-on made.
Code: https://github.com/ruifontes/networkStrenght
Add-on: https://github.com/ruifontes/networkStrenght/releases/download/1.0/networkStrenght-1.0.nvda-addon

**Comment by kvark128** [comment]
Better use direct wlanapi calls instead of netsh, as implemented in this addon:
https://github.com/kvark128/WlanReporter/releases/download/2019.12.22/WlanReporter-2019.12.22.nvda-addon
The shortcut can be assigned in the category System status, in Input gestures dialog.

**Comment by feerrenrut** [comment]
Since there are add-ons addressing this issue I'm going to close it.
