### ISSUE TITLE
NVDA doesn't change language

### ISSUE THREAD

**Issue by MSurvonen** [nvaccess/nvda#12794]
### Steps to reproduce:
NVDA setting change language automatically is chosen.
Normal language is other than English: tested with Finnish and Swedish
In some HTML document: html lang="en-US" and NVDA doesn't change language
Compared to html lang="en-us" and language changes
### Actual behavior:
Language of NVDA is still Finnish or Swedish.
### Expected behavior:
NVDA should change language from Finnish to Englis when html lang="en-US"
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2021.1.
#### Windows version:
Win10
#### Name and version of other software in use when reproducing the issue:
HTML documents produced with Visual Studio code and some existing websites. Used with Google crome.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I haven't tried.
#### If add-ons are disabled, is your problem still occurring?
Yes it is.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by Adriani90** [comment]
which synthesizer are you using?

Some time ago @dineshkaushal worked on this, but I think there was a discussoin about system tests and there were no further updates on that. The approach was trying to set language change based on unicode characters if I am not wrong.

@feerrenrut maybe the old PR could be resumed and someone in the community could work on it. What do you think?

**Comment by seanbudd** [comment]
Is this still an issue with NVDA 2022.2.X? I this being fixed this in #13727.

Closing as stale unless it can be reproduced still
