### ISSUE TITLE
native windows email, when clicking the option move nvda announces unknown 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12834]
### Steps to reproduce:
open the windows native email app.
place the arrows focus on some message.
Press the application key to open the contest menu.
Use the arrow keys to move to the option.
press enter 
### Actual behavior:
nvda announces unknown.
It is worth noting that this problem does not occur every time, however it occurs very frequently.
the hover button seems to be the create new folder button, because if you press tabe and then shift + tabe this is the hover button.
It seems to be more of a problem, or the email app is slower than what nvda expects, and when nvda informs the name of the option in focus this button is not available yet, or some other problem, I'm not a programmer, just an enthusiastic user of new versions. 

### Expected behavior:
every time nvda must inform the name of the hover button, in which case it appears to be a new folder. 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-23729,f8f62b04

#### Windows version:
11 10.0.22000.184
#### Name and version of other software in use when reproducing the issue:
HxOutlook.exe, microsoft.windowscommunicationsapps 16005.14326.20206.0

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
log:
[emailmovy.txt](https://github.com/nvaccess/nvda/files/7148122/emailmovy.txt)

**Comment by seanbudd** [comment]
Do you know if this occurred on Windows 10?

**Comment by fernando-jose-silva** [comment]
yes this also occurs on Windows 10

**Comment by ahmad-alajaj** [comment]
Hi,
The problem you are talking about does not always happen
Although I don't use it, but I tried it, the problem actually happens sometimes 

Are you using Windows 10 App Essentials add-on?

**Comment by fernando-jose-silva** [comment]
even with the windows app Essentials add-on? disabled the problem occurs.

**Comment by Adriani90** [comment]
@fernando-jose-silva are you still having this problem with NVDA 2024.4.1.??

**Comment by fernando-jose-silva** [comment]
unfortunately I am no longer a user of this email client, thank you very much.Enviado do meu iPhoneEm 11 de nov. de 2024, à(s) 16:41, Adriani90 ***@***.***> escreveu:﻿
@fernando-jose-silva are you still having this problem with NVDA 2024.4.1.??

**Comment by Adriani90** [comment]
Ok, it seems native Windows mail app reaches end of life on December 31 2024 after which people will not be able anymore to send and receive messages in this app. You can install the new Outlook for Windows if you still want the native email experience. Closing as abandoned.
Fir more details, see
https://support.microsoft.com/en-us/office/outlook-for-windows-the-future-of-mail-calendar-and-people-on-windows-11-715fc27c-e0f4-4652-9174-47faa751b199
