### ISSUE TITLE
Adobe Reader/Acrobat crashes when a bullet is read in a PDF with NVDA.

### ISSUE THREAD

**Issue by bholeshwar** [nvaccess/nvda#12838]
### Steps to reproduce:
1. Open the attached PDF and tab through text fields to reach the radio field.
2. Acrobat silently quits as tab-key is moved from text field to radio button.

### Actual behavior:
Acrobat crashes

### Expected behavior:
Acrobat shouldn't crash

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2021.1

#### Windows version:
10 (Enterprise) Version 10.0.19042 Build 19042

#### Name and version of other software in use when reproducing the issue:
Adobe Acrobat Reader DC 2021.005.20060

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, I have only tried the latest version

#### If add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes
[Form with radio button.pdf](https://github.com/nvaccess/nvda/files/7153723/Form.with.radio.button.pdf)

**Comment by seanbudd** [comment]
Unfortunately the latest version seems to crash with NVDA so this may be hard to confirm. I'll confirm when #12920 is resolved.

**Comment by Adriani90** [comment]
@seanbudd is this fixed now?

**Comment by seanbudd** [comment]
Seems fixed to me
