### ISSUE TITLE
NVDA 2021.2 (Japanese) reading latin characters as words.

### ISSUE THREAD

**Issue by SpanishCrusader** [nvaccess/nvda#12847]
Hello everyone.
I sincerely apologize if this is not the correct place to post this question, but I couldn't figure out the right combination of words to find a solution on Google.

I just updated my NVDA JP portable installation from I think 2019.2 to 2021.2.
I've benn ignoring all the updates because I had a wird problem when typing in japanese.

I decided to give 2021.2 a chance, to see how it works, and it appeared that everything was working fine, but when I try to navigate through a sentence using the left and right key, instead of getting the proper audio feedback for the letter (a, e, r, z etc) I get words descriptions like "echo" for e, "papa" for p or lemon for l.

I don't know how to revert this new feature to the old behavior, I tried almost every settings combination I could imagine.

### Steps to reproduce:
1. Install lastest NVDA JP 2021.2 from https://www.nvda.jp/en/
2. Open any text editor like Notepad.
3. Type a letter like "o" or "l" and place the cursor before it by using the left or right key to get the audio feedback.

### Actual behavior:
Characters are interpreted as words instead of single characters.

### Expected behavior:
A single character should be interpreted as a single letter, like "a" = "a" or "l" = "l".

#### NVDA installed/portable/running from source:
NVDA JP 2021.2 portable.

#### NVDA version:
2021.2

#### Windows version:
Windows 10 21H1.

#### Name and version of other software in use when reproducing the issue:
Notepad for Windows.

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, previous 2019.2 doesn't seem to have this behavior.

#### If add-ons are disabled, is your problem still occurring?
No custom addons installed.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not sure how can I perform this task.

**Comment by SpanishCrusader** [comment]
> 
> 
> This looks very similar to the functionality of an add-on. Are you sure that no add-on is installed?

Indeed.
I tried a clean install of NVDA and the "restart with addons disabled" option from the exit menu (NVDA + Q).
And I'm still getting single characters as words like "alpha" for "a", "charly" for "c".

It really seems like a silly problem that probably it's just about turning off a switch in the settings menu, but I've look everywhere, and I couldn't find what I need to turn off.

**Comment by seanbudd** [comment]
This occurs only with the [Japanese forked version you have listed](https://www.nvda.jp/en/), not the NVDA developed here.
To use the nvaccess version of NVDA, install it from [here](https://www.nvaccess.org/post/nvda-2021-2/)

**Comment by seanbudd** [comment]
You can file an issue for that specific fork here: https://github.com/nvdajp/nvdajp
