### ISSUE TITLE
Trying to scroll braille display forward in Firefox's address bar when it is empty causes an error.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#12885]
### Steps to reproduce:
1. Start Firefox.
2. Move to the address bar ensure that it is empty
3. Try to scroll braille display forward.
### Actual behavior:
Error sound is played and the following is in the log:
```
ERROR - scriptHandler.executeScript (23:10:45.752) - MainThread (2532):
error executing script: <bound method GlobalCommands.script_braille_scrollForward of <globalCommands.GlobalCommands object at 0x06F75150>> with gesture 'rightAdvanceBar'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "globalCommands.pyc", line 2819, in script_braille_scrollForward
  File "braille.pyc", line 1879, in scrollForward
  File "braille.pyc", line 1396, in scrollForward
  File "braille.pyc", line 1157, in nextLine
  File "braille.pyc", line 852, in _setCursor
  File "compoundDocuments.pyc", line 110, in updateCaret
  File "textInfos\offsets.pyc", line 668, in updateCaret
  File "NVDAObjects\IAccessible\__init__.pyc", line 199, in _setCaretOffset
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 30, in __call__
_ctypes.COMError: (-2147024809, 'Parameter is incorrect.', (None, None, None, 0, None))

```

### Expected behavior:
No error sound
#### NVDA installed/portable/running from source:
Tried with portable.
#### NVDA version:
Latest Alpha
#### Windows version:
Windows 7 X64
#### Name and version of other software in use when reproducing the issue:
Nightly 94
#### Other information about your system:
None relevant
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, I haven't
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tried

cc @jcsteh  As this affects Firefox

**Comment by Adriani90** [comment]
@lukaszgo1 are you still seeing this issue with NVDA 2024.1 on Firefox 124 and Windows 8.1 or higher?
cc: @dkager, @burmancomp

**Comment by lukaszgo1** [comment]
This is still reproducible on Windows 10 22H2, Firefox Nightly 126 with NVDA alpha-31555,7bfe7137. It is probably a Firefox issue, rather than an NVDA one, though it would be nice to get confirmation from @jcsteh

**Comment by burmancomp** [comment]
@lukaszgo1 can you confirm this happens when braille is tethered to focus (or to focus when tethered to automatic) but it does not occur if braille is tethered to review?

**Comment by burmancomp** [comment]
May #16314 be somewhat relative with this issue?

**Comment by lukaszgo1** [comment]
> can you confirm this happens when braille is tethered to focus (or to focus when tethered to automatic) but it does not occur if braille is tethered to review?


I can confirm this is the case for me.
