### ISSUE TITLE
Include structured braille like in Jaws

### ISSUE THREAD

**Issue by jcoffin1** [nvaccess/nvda#12890]
### Is your feature request related to a problem? Please describe. 
No
### Describe the solution you'd like
Please add structured braille like in Jaws. 
### Additional context
Add a feature in braille that will allow the user to have a structured braille experience like in Jaws. this way it makes things easier to understand, and for new users of braille or NVDA the braille structure won't be overwelming for people.

**Comment by josephsl** [comment]
Hi, can you tell us more please, such as the rationale for this, examples, and other details? Thanks.

**Comment by msviolafangirl** [comment]
Just googled JAWS braille structured mode and found the following: https://doccenter.freedomscientific.com/doccenter/doccenter/rs25c51746a0cc/2015-03-11_jawsbraillein/02_JAWSBrailleIn.htm#:~:text=If%20Braille%20Follows%20Active%20is,JAWS%20switches%20to%20Structured%20Mode.

I have used JAWS in the past with a braille display but never paid attention to what structured mode or any of that stuff is. From what I can gather, it seems to allow the display of some extra information on the display and JAWS braille is in structured mode by default, but I don't know much about it. In the future I'll probably install a JAWS demo and can check using that, but for now, I don't know.

**Comment by josephsl** [comment]
Hi,

Structured braille mode in JAWS refers to providing additional information about controls to braille displays. In that respect, NVDA already does this - NVDA does include control information.

Is this what you are looking for?

Thanks.

**Comment by feerrenrut** [comment]
For us to consider a new feature it needs to be properly described. The question "Is your feature request related to a problem" allows us to consider how your described solution solves a real user problem. I'm going to close this issue, please open a new one if you wish to describe the user problem and feature in detail. To make this easier, I'd recommend starting with one small aspect of the feature.
