### ISSUE TITLE
NVDA does not report Ctrl + BackSpace deleted words in Visual Studio

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#12901]
### Steps to reproduce:

1. Open Visual Studio;
2. Ctrl+Shift+N to create a project (C# Console project as an example);
3. go to the code editing area and try to edit Program.cs;
4. Type Console.WriteLine();
5. use Ctrl+Left/Right to move the position of the input focus;
6. hear "Console", "dot";
7. When you hear "Dot" press Ctrl+BackSpace.

### Actual behavior:
  The word "Console" was deleted, but NVDA did not report anything.
### Expected behavior:
  The word "Console" was deleted, NVDA report "Console".
#### NVDA installed/portable/running from source:
- installed
- portable
#### NVDA version:
2021.2 and 2021.1 and Alpha
#### Windows version:
Windows 10 21H1 (x64) build 19043.1237

#### Name and version of other software in use when reproducing the issue:
Microsoft Visual Studio Community 2019
Version: 16.11.3
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA2021.1 and the latest Alpha can also reproduce this issue.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment]
@cary-rowen are you still having this issue with NVDA 2024.1 Beta 9?

**Comment by cary-rowen** [comment]
Yes, this issue is no longer reproducible in Visual Studio 17.8.5 and I will close it.
