### ISSUE TITLE
Problems identifying errors in Word with UI Automation selected

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#12915]
### Steps to reproduce:
1. Open a document in Word
2. Ensure that UI Automation in Word is checked in Advanced under NVDA settings if using NVDA 2021.2.
3. Write some text that includes spelling errors.
4. Review the text with either arrow keys or by using w in browse mode.

### Actual behavior:
No errors are reported
### Expected behavior:
NVDA should buzz when a spelling error is made.  It should also identify errors when reviewing text.
#### NVDA installed/portable/running from source:
Both installed and as portable.
#### NVDA version:
2021.2 installed and alpha-23892,93c1fbcf portable
#### Windows version:
Windows version 10.0.19042 Build 19042
#### Name and version of other software in use when reproducing the issue:
MS Outlook 365
#### Other information about your system:
Nothing I can think of
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2021.2 and alpha-23892,93c1fbcf
behave the same. No errors reported during writing or reviewing.  After running the Word spell checker errors can be found.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by andrew-l-d** [comment]
If Check Errors as you Write is checked under Proofing in Options, errors are identified both when arrowing to them or when searching with w in Browse mode.  However, there is no buzz as the error is made.

**Comment by lukaszgo1** [comment]
> 
> 
> If Check Errors as you Write is checked under Proofing in Options, errors are identified both when arrowing to them or when searching with w in Browse mode.

This is expected - the fact that disabling that option had no effect when using object model was a bug (see #7917)
>  there is no buzz as the error is made.


This is already covered by #12161

**Comment by andrew-l-d** [comment]
Apologies, I missed #12161 when searching for relevant open issues.  I will close this one.
Andrew
