### ISSUE TITLE
NVDA 2021.2. Problems when using continuers reading

### ISSUE THREAD

**Issue by dTolmachev1** [nvaccess/nvda#12923]
### Steps to reproduce:
Open any content (E.G. web-page), perform NVDA gesture for reading from system caret (NVDA+Down_Arrow on default desktop layout, or NVDA+A on default laptop layout), read a little bit, then go to some other content using usual navigation (it can be even different page), try to start reading from system caret performing the same gesture again.
### Actual behavior:
NVDA will read next unread sentence from previous page and then start reading new content (it seams like screenreader try to buffer some of the reading content and didn't clear this buffer if the reading was stopped).
### Expected behavior:
NVDA just reads new content.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2021.2.
#### Windows version:
Windows 10 1809 (build 17763.2183) (also tried on Windows 10 21H2 (build 19044.1263) and Windows 11 21H2 (build 22000.194)).
#### Name and version of other software in use when reproducing the issue:
Any software, which allows viewing the content, E.G. web-browser (like Google Chrome or Microsoft Edge) or text processor (like Microsoft Office Word or standard Wordpad or Notepad).
#### Other information about your system:
Issue occurs even on clean installed system, so it can't be problem with my apps or something similar.
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
All starting from 2019.3 -- the behavior was the same.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes, even on clean copy of NVDA.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by feerrenrut** [comment]
> All starting from 2019.3 -- the behavior was the same

@dTolmachev1 this sounds like all versions after and including 2019.3 have this issue, is that correct?

I haven't been able to reproduce this issue. If you can reproduce it easily, please attach a debug level log to this issue to help us understand the steps required. For instructions see the [Log Files And Crash Dumps wiki article](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps)

While this is annoying, and it would be great to get to the bottom of it, the impact is not severe enough to block the 2021.3 release.

**Comment by Adriani90** [comment]
@dTolmachev1 are you still having this issue in NVDA last alpha version or NVDA 2023.1?

You can download the last alpha version for testing at this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Adriani90** [comment]
We didn't get any update upon request from the initial author since many years. i am closing as abandoned. If you are still having this issue, please comment and we can reopen.
