### ISSUE TITLE
ESpeak NJ-1.51’s Mandarin pronunciation is corrupted

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#12952]
When reading a Chinese character aloud, in addition to reporting the Chinese character itself, the tones of the Chinese character will also be read out in English numbers. This is abnormal.
This looks similar to [this Issue](https://github.com/espeak-ng/espeak-ng/issues/499)

### Steps to reproduce:
1. Use NVDA 2021.2 or the latest Alpha version to read the following text, The Chinese meaning of 'this text is(Today's weather is good.':
  - 今天的天气很好
2. Use NVDA2021.1 to read the Same sample text:
  - "今天的天气很好".

### Actual behavior:
In step (1)
NVDA reports ("今One 天 One 的 Five 天 One 气 Four 很 Three 好 Three").
The following is the incorrect recording demonstration (from NVDA-2021.2):
https://drive.google.com/file/d/1wBNLbUzQpPMx-5zLfXYC-XbEg0d6_1fo/view?usp=sharing

### Expected behavior:
NVDA reports sample text ("  - 今天的天气很好") in Mandarin, just like NVDA-2021.1.
The following is the correct recording demonstration (from NVDA-2021.1):
https://drive.google.com/file/d/1EdaSVpDq8kLXCaAEqZmFcaHRpMwfiJOU/view?usp=sharing

#### NVDA installed/portable/running from source:
installed and portable

#### NVDA version:
NVDA-2021.2
#### Windows version:
Windows 10 21H1 (x64) build 19043.1288
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA2021.2 everything is normal
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment]
Hi @cary-rowen  - would you be able to test [this try build](https://ci.appveyor.com/api/buildjobs/cwydngyy0a9wxk7c/artifacts/output/nvda_snapshot_pr12950-23974,fd672982.exe), which is using the latest e-Speak

**Comment by seanbudd** [comment]
Thanks @cary-rowen - this will have to reported to the espeak repository https://github.com/espeak-ng/espeak-ng/issues

**Comment by cary-rowen** [comment]
Hi guys,

If [this commit][1] is merged, and espeak-ng/espeak-ng#1044 is closed, then this issue can also be closed after updating eSpeak.


[1]: https://github.com/espeak-ng/espeak-ng/issues/1044

**Comment by seanbudd** [comment]
@cary-rowen - can you let us know when we can update eSpeak to incorporate this fix?

**Comment by cary-rowen** [comment]
@seanbudd 
Sorry, the link I provided above was wrong, now that I've corrected it, we'll keep an eye on the status of [this commit][1].
[1]: https://github.com/espeak-ng/espeak-ng/commit/1443c970cdffe258276e1a6442316268c1d380be
