### ISSUE TITLE
braille in Word (after UIA is always on) is not refreshing cursor position

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#12970]
### Steps to reproduce:

- Open Word
- start typing
- after some typed words and lines check, what is on braille display

### Actual behavior:

braille is not refreshing and is stopped on random position.

### Expected behavior:

braille should be synchronised with speech and should show line, where is cursor

#### NVDA installed/portable/running from source:

installed

#### NVDA version:

alpha-23897,7bd9e8b1

#### Windows version:

10 21h1 with latest updates

#### Name and version of other software in use when reproducing the issue:

office 2019 (Microsoft Office version 16.0.14430.20306)

#### Does the issue still occur after restarting your computer?

yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

2021.1 and it is ok.

#### If NVDA add-ons are disabled, is your problem still occurring?

n-a

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

n-a (no difference)

**Comment by zstanecic** [comment]
[braille.txt](https://github.com/nvaccess/nvda/files/7388041/braille.txt)
Here the log it is.
I've turned on advanced categories: UIA, and hw IO
