### ISSUE TITLE
NVDA switches to browse mode while switching to full screen on Microsoft edge

### ISSUE THREAD

**Issue by fatihyuksek1** [nvaccess/nvda#12983]
### Steps to reproduce:
1. Open Microsoft edge
2. Open www.youtube.com
3. Click on any video
4. Switch to focus mode on the video player, for example while focus is on the pause button
5. Press f to switch to full screen
6. NVDA will announce "press esc to leave the full screen mode."
7. It will then switch to browse mode
8. Switch to focus mode again
9. Press esc to leave the full screen mode
10. NVDA will again switch to the browse mode.
### Actual behavior:
NVDA switches to browse mode while getting into or out of the full screen mode from the focus mode
### Expected behavior:
NVDA will stay in the focus mode while switching into or out of the full screen mode.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.2
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Microsoft Edge
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2021.1 behaved same as 2021.2
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
This occurs also in Google Chrome, it seems it affect Chromium browsers and in general every chromium embeded interface.

It seems when disabling the setting "use browse mode after page has loaded" in NVDA browse mode settings", this works as expected.

@leonardder if I remember correctly you introduced that setting some while ago. Should I fill a bug with Chromium? Or is something that can be fixed from NVDA side for Chromium?

**Comment by Adriani90** [comment]
Actually after some more testing this seems related to web authoring issues and need to be reported to Youtube.
Now with NVDA 2024.1., when enabling focus mode manually with nvda+space bar, NVDA stays in focus mode no matter whether full screen mode is toggled on or off.

However, when enabling automatic focus mode on focus change or on system carret movement in NVDA browse mode settings, NVDA switches to focus mode when it encounters an edit field or a slider.
Pressing f from that slider (e.g. the volume slider) will change to full screen mode and the focus is redirected to another region which is not editable. NVDA switches then to browse mode as expected.
For pressing escape to close the full screen, this part is not reproducible anymore. NVDA remains in focus mode as soon as you enabled it manually.

So if you want this to work properly, you should report to Google and Youtube developers that the focus should never be redirected when opening the full screen, but should stay on the same focused control as before opening the full screen.
I am closing this issue as invalid and needs external fix.
