### ISSUE TITLE
Some mouse over dropdown menus not updating the buffer in IE

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1298]
**Reported by abletec on 2011-01-04 17:35**
Ok, let's try this 1 more time.
Please go to:
http://brightervisioncontent.com/wordpress/
Type l & read the list of items. You'll likely see 3.

Unfortunately, there are 5, as follows:
home
blog
about
elise Lonsdale &
Jackie
the latter 2 of which don't read.

W/Jaws, u can actually route the Jaws cursor to the about link & make the 2 sublinks appear. That obviously isn't a very satisfactory solution. I haven't found a way to read them w/NVDA yet.

**Comment by ehollig** [comment]
As @michaelDCurran said, this web address no longer seems to work for me. Can another address to a page that shows the same issue be provided if there is one?

**Comment by derekriemer** [comment]
closing as this is something which a developer coded wrong.
