### ISSUE TITLE
Word UIA: Lag in Reading Status Bar

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#12991]
### Steps to reproduce:
1 Open an existing, somewhat large Word document. 
Note: The one I am using has 31 pages, numerous tables, and that is about it.
2 Press the read status bar command.
Note: I am using the laptop keyboard layout, so it is NVDA+Shift+End.

### Actual behavior:
NVDA reads it (sometimes incorrectly but that is a separate issue) but with a lag of almost 2 seconds. For comparison, NVDA responds to an upp arrow (to go to and read the previous line) in under 70 seconds, meaning a nearly 30X difference.

### Expected behavior:
NVDA should be relatively prompt in reading the status line on issuance of the command.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-24073,8b17f662
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
Word for Office 365
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by ehollig** [comment]
@bhavyashah has performance increased in newer versions of Office 365? Without a sample word document, it is difficult to reproduce this issue. If the document contains confidential information, you can also email it to NVAccess and mention this issue.

**Comment by seanbudd** [comment]
Closing as stale / can't reproduce.
If you can still reproduce it, please provide a sample document and the latest steps to reproduce

**Comment by bhavyashah** [comment]
NVDA reads the status bar in about 250 ms for me which is reasonable. In other words, I do not experience this issue now.
