### ISSUE TITLE
NVDA 2021.2 unpredictably crashing when using Chrome's Back command

### ISSUE THREAD

**Issue by chrisnorman7** [nvaccess/nvda#13001]
### Steps to reproduce:

Navigate to (presumably) any website. I most commonly see this behaviour on [https://forum.audiogames.net/].

Click a few links. The actual number doesn't seem to matter. I've had this happen after just one click, but when I tried just now to force it to happen, I got nothing after about 50.

Hit alt left arrow to go back a page.

### Actual behavior:

On my system, very occasionally NVDA crashes, the fan speed increases, and when I reload NVDA there are now multiple NVDA icons in the system tray, with only one icon actually doing anything.

This happens daily rather than weekly, but I can't find any pattern to it. It only seems to happen when going back a page, rather than when navigating with a link or whatever.

### Expected behavior:

For it not to crash. :)

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

NonVisual Desktop Access (NVDA)
Version: 2021.2

##### From winver:

Version 21H1 (OS Build 19043.1288)

##### Google Chrome

Chrome is up to date
Version 95.0.4638.54 (Official Build) (64-bit)

#### Other information about your system:

I am using an AMD processor, for whatever that's worth.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

I don't think this happened on older versions, but I never really paid much attention to when it changed.

#### If NVDA add-ons are disabled, is your problem still occurring?

Due to the random nature, I haven't tested this. Happy to though, if it would help.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

I've only just ran it, so I guess I'll find out.

**Comment by chrisnorman7** [comment]
Hi,
Predictably, when I want it to happen, it hasn't.

So I edited my log, since it was over 200 MB, and there was loads of stuff in there I didn't want laying around on the internet for obvious reasons, but I have retained the unabridged copy in case my truncated version doesn't provide all that is needed.

The problems start when I hit alt left arrow, which is there in the log. Hopefully this will help.

[nvda-log.edited.log](https://github.com/nvaccess/nvda/files/7448290/nvda-log.edited.log)

Thanks in advance.

**Comment by lukaszgo1** [comment]
Would it be possible for you to work for a few days with Braille Extender disabled? From your log it seems the freeze occurs inside Braille Extender's code rather than in NVDA itself.

**Comment by CyrilleB79** [comment]
Cc @aaclause for information, in case it is confirmed Braille Extender is in cause.

**Comment by aaclause** [comment]
Thanks @CyrilleB79 for letting me know.
Indeed, it is very likely that Braille Extender is the cause.
@chrisnorman7 I think the crash should go away by completely disabling the undefined characters feature.
For that, please go to: NVDA menu > "Braille Extender" submenu > Settings... > "Undefined character representation" category > "Representation method" listbox.
Then select the first option i.e. "Use braille table behavior (no description possible)".
Sorry for that. In the meantime, I'll disable this feature by default.

**Comment by chrisnorman7** [comment]
Hi,
Thank you so much for that, I've just enacted the change you suggest. I'll
close this in a few days if the problem hasn't come back.

Cheers,

Take care,

Chris Norman

**Comment by seanbudd** [comment]
Hi @chrisnorman7 - has the problem returned? I've closed the issue, feel free to reopen.

**Comment by chrisnorman7** [comment]
Sorry, it's been a busy week, and I admittedly forgot about this.

No, the problem hasn't returned since I affected the above configuration
changes, so it's fine closed.

Take care,

Chris Norman
