### ISSUE TITLE
nvda error sound is heard when walking with arrows through a combo box in a java application 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#13005]
### Steps to reproduce:
I haven't tested if the error occurs when using other combo boxes in java apps or apps outside of this platform
Open a java application that has a combo box
now walk the arrows through the options available in the combo box. 
### Actual behavior:
nvda error sound is heard
the options in focus are read normally 
### Expected behavior:
nvda error sound is not heard
options are read normally 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda alfa 24154
#### Windows version:
11 10.0.22000.282
#### Name and version of other software in use when reproducing the issue:
app java

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
log:
[java.txt](https://github.com/nvaccess/nvda/files/7436841/java.txt)

**Comment by mwhapples** [comment]
I am not sure what can be done here. Unless the issue can be demonstrated with a publically available application then it will be impossible to debug and determine what these unexpected values mean

**Comment by seanbudd** [comment]
Agreed, closing as can't fix without a sample
