### ISSUE TITLE
NVDA is not working with Chrome Updated version, only announcing every time 'Chrome legacy' window

### ISSUE THREAD

**Issue by NeerajChouksey** [nvaccess/nvda#13014]
![NVDA](https://user-images.githubusercontent.com/78546412/139805981-e7717061-d9b9-4931-97e0-a6232b3c99cf.png)
The NVDA(Version 2021.2) is not working with Chrome's latest version(Version 95.0.4638.69). NVDA is not reading anything in Chrome browser just announcing 'Chrome legacy window'

**Comment by feerrenrut** [comment]
When [creating a new issue, please fill in the full issue template](https://github.com/nvaccess/nvda/issues/new?assignees=&labels=&template=bug_report.md), and try the suggestions contained in the template.

There is also a detailed [explanation of the template to help](https://github.com/nvaccess/nvda/blob/master/devDocs/githubIssueTemplateExplanationAndExamples.md)

I'm going to close this issue, as it stands there is nothing we can do.
