### ISSUE TITLE
Task module content with hyperlink not read on focus

### ISSUE THREAD

**Issue by prajwalmanju** [nvaccess/nvda#13040]
### Steps to reproduce:
Enable screen reader and open teams task module consist of content with hyperlink tag click tab multiple time to start focusing on the card.

### Actual behavior: 
Screen reader start reading only hyperlink tags while focusing on the card.

### Expected behavior: 
screen reader should read all the content visible on the card.

#### NVDA installed/portable/running from source:
windows10

#### NVDA version:
2021.2

#### Windows version:
OS Build 19042.1288

#### Name and version of other software in use when reproducing the issue:
MS Teams 1.4.00.29469 (32-bit).

#### Does the issue still occur after restarting your computer?
 Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors. : 
(2021.1) while focusing on the card screen reader will read all the content if data doesn't consist of hyperlink tag but behavior is same if data having hyperlink tag

#### If NVDA add-ons are disabled, is your problem still occurring? 
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu? 
Yes

**Comment by feerrenrut** [comment]
Please ensure that you have given this feedback via the Teams application.

**Comment by prajwalmanju** [comment]
Yes, we are facing this issue while using NVDA screen reader in Teams task module.

**Comment by feerrenrut** [comment]
Please report the issue to the developers of Teams via "help", then "give feedback".

**Comment by prajwalmanju** [comment]
Basically the issue is that the NVDA solution doesn’t read the content as expected.
So do you consider that the rendering of the Teams dialog doesn’t meet the requirements for the NVDA content reader?

**Comment by zersiax** [comment]
@prajwalmanju  this is more than likely a problem with Teams, not so much NVDA. Leave feedback for them so they can fix it, not much NVDA can really do about this one I'm pretty sure.

**Comment by Adriani90** [comment]
For NVDA to access content with other tags than hyper link tags, it is required to include a tabindex property and value to the focusable elements. This needs to be done by the Teams developers. Also it is often possible to access the contents in Browse mode of NVDA without using the tab key, but the arrow keys instead.

I am closing this issue since it is not related to NVDA, but is rather an implementation and design issue related to Teams itself.
