### ISSUE TITLE
When focus switched to tooltip element, NVDA should switch to browse mode

### ISSUE THREAD

**Issue by isidorn** [nvaccess/nvda#13047]
Based on feedback from @jooyoungseo here https://github.com/microsoft/vscode/issues/133773

1. Turn on NVDA, start VS Code
2. Open some code file
3. Ctrl + k, Ctrl + i -> to trigger hover. Focus is moved to hover, but NVDA is not in browse mode

On the VS Code side we set the `tooltip` role on the hover which we think is fitting. But based on feedback it seems like if NVDA switched to browse mode this would help.
What do you think?
Thanks

**Comment by ehollig** [comment]
Closing as the tooltip aria spec doesn't require screen readers to switch to browse mode.
Suggestion is to use document role to trigger browse mode, from https://github.com/microsoft/vscode/issues/133773#issuecomment-928072607.
