### ISSUE TITLE
Warning appeared in NVDA 2021.3beta2

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#13051]
I report here a warning that has appeared at various places in 2021.3beta2 (not tested the beta1) but was not present in 2021.2.
Maybe introduced by #12925? (Cc @michaelDCurran )

Also Cc @feerrenrut to decide if this issue should be in the 2021.3 milestone or not.

### Steps to reproduce:

* Open a setting dialog, e.g. NVDA+control+D (formatting)
* Press space key to modify the state of the first checkbox.

### Actual behavior:

The following warning appears in the log
```
DEBUGWARNING - NVDAObjects.NVDAObject._reportErrorInPreviousWord (21:08:34.573) - MainThread (5336):
Error fetching last character of previous word
Traceback (most recent call last):
  File "NVDAObjects\__init__.pyc", line 1050, in _reportErrorInPreviousWord
  File "documentBase.pyc", line 22, in makeTextInfo
  File "textInfos\offsets.pyc", line 470, in __init__
  File "textInfos\offsets.pyc", line 249, in _getCaretOffset
NotImplementedError
```

I have not noted however any other negative side effect.

### Expected behavior:

No such warning that makes the log more difficult to read and that does not bring any useful information in this case. IMO, such a warning should not be present for objects that do not have text edition capability.
Why is the function `_reportErrorInPreviousWord` present and called for a such generic object?

If I have misunderstood the goal of this warning however, please explain and close this issue.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.3beta2

#### Windows version:
Windows 10 20H2 (64-bit) build 19042.1288

#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2021.2: no warning
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested but probably not related.

**Comment by feerrenrut** [comment]
We need to understand the severity of this before we can determine if it needs to be fixed for 2021.3, further investigation is required:
- Which PR was this introduced with?
- Why is this code being called in this situation?
- Does the exception prevent something useful from happening?

@CyrilleB79 these aren't necessarily questions for you, but you are welcome to investigate and try to answer them if you wish.

**Comment by michaelDCurran** [comment]
these warnings were introduced in pr #12925  / pr #12931 .
They are harmless and the exceptions they talk about are expected.
We could silence these particular warnings, I.e. for NotImplemented, but I certainly wouldn't bother for NVDA 2021.3.

**Comment by feerrenrut** [comment]
Thanks for looking @michaelDCurran. I'm going to bump this to fix in 2022.1

"Expect-tions" don't really do anyone any favors.

**Comment by CyrilleB79** [comment]
I just confirm that I have not seen any undesirable side effect.

**Comment by lukaszgo1** [comment]
What I do not fully  understand is why the code for spelling errors detection is in the base  NVDAObject as opposed to being in `editableText.EditableText`. Are there cases in which spelling error can be detected when typing outside of editable content?
