### ISSUE TITLE
NVDA should return to browse mode when down or up arrowing by default

### ISSUE THREAD

**Issue by Gene703122** [nvaccess/nvda#13067]
### Is your feature request related to a problem? Please describe.
By default, NVDA automatically goes into forms mode when down or up arrowing into an edit field.  It doesn't automatically return to browse mode when you up or down arrow out of the edit field.
### Describe the solution you'd like
By default, NVDA should automatically return to browse mode when you leave an edit field.
### Additional context
At present, behavior is inconsistent and encourages tabbing when it should not be encouraged.  You can tab out of an edit field to the next control or field but when working in an unfamiliar form, that is exactly what shouldn't be done.  Unfamiliar forms should be arrowed through to see if there is explanatory text that should be known when filling it out.  Thus, the environment is biased toward the user adopting a poor practice when it should be neutral.

Also, the current behavior is inconsistent.  If you use NVDA space to return to browse mode to arrow out of an edit field, you are no longer automatically placed in an edit field when arrowing through a form.  This inconsistent behavior wouldn't be a problem if the default were to automatically leave edit fields when arrowing out of them.  I would think this inconsistent behavior confuses many users and may be particularly confusing to those newly learning NVDA.

**Comment by CyrilleB79** [comment]
Hello

I think that it would be irrelevant and even counter-productive to switch to browse mode on up/down arrow press in multi-line edit fields.
That said, wouldn't the user be more confused if we implement such a different behaviour between single and multi-line edit fields? There are probably in the wild multi-line edit fields actually used for a single line input.

Personally, I think that today's behaviour remains the best compromise.
Glad to hear the opinions of other people however.

**Comment by nidza07** [comment]
I tend to agree with @CyrilleB79
If we are talking only about new users, I would assume many people expect to read what they just wrote in an edit field by pressing up / down arrow, and thus getting them completely out of focus mode would not be very intuitive and would create further confusion in regards to editing already existing text in an edit field.
In addition, this behaviour doesn't encourage pressing tab at all. Rather, you should simply press Escape to get out of the edit field and continue browsing the page as normal.

Finally, you can already get the behaviour you want as long as you enable "Automatic focus mode for caret movement" inside NVDA's browse mode settings, I just don't believe that needs to be the default.

Of course, this is all very subjective, and I would be curious if examples of users being confused by the current behaviour have already been observed. It's also worth noting that other screen readers behave in a similar way here.

**Comment by Gene703122** [comment]
I played with this behavior some more and its different than I thought.  The inconsistency is much worse than I realized, since I don’t use the default settings in my general browsing.  

When you arrow in a form, you will enter and get stuck in an edit field.  If you return to browse mode by pressing escape or with NVDA space bar and then arrow to edit fields in the form, you will not automatically enter forms mode.  This is completely inconsistent behavior.  

When tabbing, you automatically enter and leave forms mode when you tab to and tab out of an edit field.  The behavior is consistent no matter how often you do this on a page.  Since the behavior is consistent, it favors using tab.  

I don’t see a problem with confusion if you automatically move into and out of forms mode when arrowing through a page.  Forms mode doesn’t exist to eliminate such confusion.  System Access never had a forms mode and I never heard a complaint about users being confused.  Forms mode exists because when you are in forms mode, you are working directly with the page and can enter text and work with combo boxes.  It was not introduced because of worries over confusion when reading what you wrote in an edit field.  

A student I would expect, would immediately recognize what he/she wrote and will know that what is above and below it is preexisting material on the web page.  If there should be any cconfusion, the matter can easily be explained.

What is confusing is inconsistent behavior between tabbing and arrowing and inconsistent behavior regarding use of the arrows themselves.

Gene
-----Original Message-----

**Comment by nidza07** [comment]
To clarify a bit.
What you call inconsistency is a configuration choice. Press NVDA plus CTRL plus B to open the browse mode panel.
Here two options are mainly important:
1. Automatic focus mode for focus changes - if this option is checked, the behaviour you mentioned will apply. When  tabbing, NVDA will enter focus mode if encountering an edit field, and will leave focus mode once you tab past an edit field. If this option is disabled, the state never changes when tabbing. If you were in browse mode, tabbing to an edit field won't enter focus mode and vice versa.
2. Automatic focus mode for caret movement - this option concerns moving the cursor. If you check this checkbox, NVDA will do what you want, i.e enter focus mode when encountering an edit field, and when arrowing past go back to browse mode.

In the end it's up to you to configure NVDA the way you personally like. IN my opinion, the default behaviour is not confusing, but it can easily be changed to fit your need.

**Comment by Gene703122** [comment]
I’m not writing for me.  I have NVDA set so I manually change modes.  Of course, NVDA users may configure things as they wish, but default settings should be based on the best choice for the most users or on some other criterion such as for new users.  My contention is that the current default settings are more likely to confuse users and, since new users are being discussed, I’d love to hear from teachers about whether the default settings confuse new users and favors tabbing, which shouldn’t be encouraged in unfamiliar forms.

I don’t want to clutter the discussion so I will likely reply less since I’ve probably made the argument and continuing might well be repetitious.

Gene
-----Original Message-----

**Comment by cary-rowen** [comment]
> I tend to agree with @CyrilleB79 If we are talking only about new users, I would assume many people expect to read what they just wrote in an edit field by pressing up / down arrow, and thus getting them completely out of focus mode would not be very intuitive and would create further confusion in regards to editing already existing text in an edit field. In addition, this behaviour doesn't encourage pressing tab at all. Rather, you should simply press Escape to get out of the edit field and continue browsing the page as normal.
> 
> Finally, you can already get the behaviour you want as long as you enable "Automatic focus mode for caret movement" inside NVDA's browse mode settings, I just don't believe that needs to be the default.
> 
> Of course, this is all very subjective, and I would be curious if examples of users being confused by the current behaviour have already been observed. It's also worth noting that other screen readers behave in a similar way here.

I totally agree with you.

**Comment by cary-rowen** [comment]
In the current default mode, I have not heard any complaints from users. The new users I met are accustomed to using the up and down keys to check the input text after typing. If they jump out of the edit box, they will be confused.

**Comment by Brian1Gaff** [comment]
I can see both sides. Is there not a way a checkbox could be added or indeed 
maybe some combination of the existing ones might do this. I had not 
actually considered that  multi lines would not work. I'd assumed that if 
its still an edit area it would stay there, otherwise how could you go back 
and alter your messages and correct spellink errors?
 I do sometimes encounter pages where even tab won't get you out of focus 
mode as some other 'helpful' thing like landmarks etc, throw you completely 
out to who knows where.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Brian1Gaff** [comment]
One of the problem pages is tinyurl, as it has a custom alias area, but you 
can only really read the instructions by coming out of focus mode first.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----
