### ISSUE TITLE
NVDA no longer get MathML in Chromium Base browser recently

### ISSUE THREAD

**Issue by tsengwoody** [nvaccess/nvda#13076]
### Steps to reproduce:
1. open chrome and go to  wiki page which in clude math content(https://en.wikipedia.org/wiki/Quadratic_equation)
2. Move cursor to any mathematical content written by MathML
3. It just get pure text not MathML object
### Actual behavior:
NVDA get pure text instead of MathML object when the cursor is on the mathematical content written by MathML
### Expected behavior:
NVDA gets the MathML object when the cursor is on the mathematical content written by MathML
#### NVDA installed/portable/running from source:
installed/portable/running from source
#### NVDA version:
NVDA 2020.4, NVDA 2021.2, alpha
#### Windows version:
windows 10 21H2
#### Name and version of other software in use when reproducing the issue:
chrome 96.0.4664.45
#### Other information about your system:
chrome 95.0.4638.69 is work correctly.
chrome 96.0.4664.45 is not work correctly.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Presumably caused by chrome update not NVDA
chrome 95.0.4638.69 is work correctly.
chrome 96.0.4664.45 is not work correctly.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by fred-wang** [comment]
Hi, this is https://bugs.chromium.org/p/chromium/issues/detail?id=1272563
It should be fixed in the latest chrome canary. We are working on a fix for the next update of the chrome release.

**Comment by fred-wang** [comment]
@tsengwoody This should be fixed in the latest chromium release update from Tue, Dec 7, 2021

**Comment by tsengwoody** [comment]
Yes, I updated the latest version of the chrome and it is work correctly.
