### ISSUE TITLE
 Windows 11: On the taskbar, background progress bar get's announced even though report background progress bars is off.

### ISSUE THREAD

**Issue by mazen428** [nvaccess/nvda#13071]
### Steps to reproduce:
have a window that has a progress bar, such as a file download or such.
press windows + b. to be on the taskbar.
Progress bar will still be reported even though the window is not in focus.
If the tab key was pressed to go to the desktop, progress bar beeps would stop.
### Actual behavior:
background progress bars get reported
### Expected behavior:
NVDA should not report progress bars of a window if it's in background and "report background progress bars is off".
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2021.2
#### Windows version:
windows 11 21 h2, x64, build 22000.318
#### Name and version of other software in use when reproducing the issue:
Any.
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by josephsl** [comment]
Hi,

Do you have any updates six months later?

Thanks.

**Comment by seanbudd** [comment]
closing as fixed, feel free to reopen if this is still an issue

**Comment by mazen428** [comment]
It's still an issue.
It's seems to be caused by the updated taskbar icons on windows 11, they now report if a window requests attention (flashs on the taskbar), has a progress bar in it, or number of messages if it's a messaging app ETC.
But, it's still a background progress bar so it still shouldn't report it if focus on the taskbar and report background progress bars is off.
