### ISSUE TITLE
Word 365: Incorrect verbosity during initial navigation of a table

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#13074]
### Steps to reproduce:
1 Open a Word document with a table in it (preferably populated and of dimensions at least 2X2).
2 Switch to browse mode in Word, ensure table reporting is enabled from Document Formatting settings, and press the single letter navigation key “t”.
3 Press Ctrl+Alt+right/down arrow.

### Actual behavior:
NVDA announced the number of rows and columns in the table when you first navigated to it in Step 2. ON performing Step 3, NVDA will say that you went out of the table and came back in and repeats the number of rows and columns.

### Expected behavior:
NVDA should simply report the cell you have moved to.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA 2021.3 Beta 2
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Word for Microsoft 365
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by bhavyashah** [comment]
Clarification: I can replicate this bug independent of whether Word UIA is enabled or disabled.

**Comment by feerrenrut** [comment]
@bhavyashah Can you still reproduce this with the latest alpha?

**Comment by bhavyashah** [comment]
I cannot reproduce this issue with NVDA 2022.3.2.
