### ISSUE TITLE
Word: Incomplete or incorrect reporting during multi-cell selection in tables

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#13080]
### Steps to reproduce:
1 Open a Word document with a fully populated 4X4 table (not the lowest entropy test case).
2 Navigate to row 1 column 2, move to the left of the last character of the cell, and press Shift+right arrow to select the last character.
3 Press Shift+right arrow twice to expand selection to include R1C2 and R1C3, Shift+down arrow to cover R2C2 and R2C3, and press the read current selection command (NVDA+Shift+S by default on a laptop).

### Actual behavior:
The experience varies based on version of Word, browse mode VS focus mode, and whether Word UIA is enabled or disabled. The shared theme across all configurations though is that reporting is incomplete at best and incorrect at worst. (To be explicit, the read current selection command on one occasion reported the entirety of some rows as opposed to its selected subset.)

### Expected behavior:
NVDA should actively report the coordinates and contents of the cells which become part of the selection. The read current selection command should accurately report the selected cells.

### Additional Notes
Regarding the read current selection command, If identifying the selection is hard for NVDA, one non-ideal approach would be to simulate Ctrl+C followed by NVDA+C and then revert the clipboard's contents to its previous state.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA 2021.3 Beta 2
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Word for Microsoft 365
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment]
Closing as duplicate

**Comment by bhavyashah** [comment]
In reply to https://github.com/nvaccess/nvda/issues/13080#issuecomment-1191094844, I agree that this is a duplicate and with its closure.
