### ISSUE TITLE
NVDA will not read login form on robinhood.com

### ISSUE THREAD

**Issue by enessaribas** [nvaccess/nvda#13085]
### Steps to reproduce:
 go to  robinhood.com/login

### Actual behavior:
NVDA reads e-mail field on login form, however several seconds later announces document, and the  entire webpage appears as a blank page. Moreover, when trying to object navigate page, the NVDA error tone is played, and the following error appears.
ERROR - scriptHandler.executeScript (16:12:10.775) - MainThread (2072):
error executing script: <bound method GlobalCommands.script_reviewMode_previous of <globalCommands.GlobalCommands object at 0x071A2970>> with gesture 'NVDA+numpad 1'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "globalCommands.pyc", line 994, in script_reviewMode_previous
  File "review.pyc", line 143, in nextMode
  File "review.pyc", line 124, in setCurrentMode
  File "review.pyc", line 26, in getObjectPosition
AttributeError: 'NoneType' object has no attribute 'makeTextInfo'

### Expected behavior:
NVDA accesses login form, and enables filling out and navigating webpage with no error.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
 alpha-24237,a77aff3c
#### Windows version:
windows 11 21h2
#### Name and version of other software in use when reproducing the issue:
Firefox 94.0.2
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Brian1Gaff** [comment]
What does it do in Edge is that still working? I have to say that some pages 
do odd things in Firefox sometimes for me even on windows 7 so might be some 
odd authoring quirk that upsets Firefox?
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "enessaribas" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Monday, November 22, 2021 10:40 PM
Subject: [nvaccess/nvda] NVDA will not read login form on robinhood.com 
(Issue #13085)

**Comment by enessaribas** [comment]
Is there any particular reason Edge would have  different results to Chrome though? This issue is also present in Edge.

**Comment by lukaszgo1** [comment]
This is not reproducible for me in Firefox 101 nor in Edge.

**Comment by ehollig** [comment]
This is not reproducible for me using Firefox 104.0.2 and NVDA 2022.2.3.

If this is still an issue, please provide exact steps to reproduce and it can be reopened.
