### ISSUE TITLE
Google Docs: Initial focus should be inside the document in Edge

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#13090]
### Steps to reproduce:
1 Open a .gdoc file or paste the link to a Google Docs document in the address bar or otherwise open a GDocs in Microsoft Edge.
2 Wait a few seconds so as to let loading complete.
3 Arrow around.

### Actual behavior:
NVDA says "blank".

### Expected behavior:
NVDA should be reading the document's contents.

### Additional Notes
Preliminary testing shows that this issue occurs in Edge but not in Firefox. Also, pressing NVDA+Space or Space in Edge does get you inside the document. It is unclear to me what this state-of-limbo where I am neither in the document nor on the web interface exactly is: Tab just indents and unindents paragraphs, alphabets and punctuations are treated as single-letter navigation keys, and the arrows of course give me blanks.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.3 Beta 2
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Microsoft EdgeVersion 95.0.1020.53 (Official build) (64-bit)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment]
This works as expected with NVDA last alpha and Edge 113. Closing as works for me.
