### ISSUE TITLE
The shortcut to Explore User Config directory in the start menu cannot open the user config directory

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#13094]
Suspect that this is the regression introduced by #13082 But it needs further investigation.

### Steps to reproduce:
1. Install the latest nvda_snapshot_alpha-24264, 2a6ba8fd;
2. Click "Explore User Config directory" under the NVDA folder of the start menu;

### Actual behavior:
User documents directory is opened.
### Expected behavior:
NVDA user config directory should be opened
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
Latest Alpha version
#### Windows version:
Windows 10 21H2 (x64) build 19044.1348
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA2021.2 is normal
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by josephsl** [comment]
Hi,

Confirmed - broke with alpha.24247. @lukaszgo1, any thoughts?

Thanks.

**Comment by lukaszgo1** [comment]
I'vereproduced this and I'll prepare a PR later today or tomorrow.
