### ISSUE TITLE
Microsoft Speech API version 4 skips lines of text that are included in Speech Viewer

### ISSUE THREAD

**Issue by dwilliamepic** [nvaccess/nvda#13092]
### Steps to reproduce:
Change Synthesizer to be Microsoft Speech API version 4. Continue normally through workflows
### Actual behavior:
Entire lines of text that are included in the Speech Viewer are not read out by NVDA.
Screenshot attached below - in this screenshot I include the full speech history as well as one example of an affected workflow within our software. The workflow is - tab from labeled point 1 to labeled point 2. What is read is "Le-To change the selection, use the arrow keys." as noted in the speech history part of the screenshot. Everything in between the 2 highlighted portions of the Speech Viewer is skipped when using Microsoft Speech API version 4.
![NVDA Microsoft Version 4](https://user-images.githubusercontent.com/94990569/143293847-017a385d-17b4-4384-8ec9-16922ce6a7e5.png)
### Expected behavior:
all lines of text are read
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
NVDA 2020.4
#### Windows version:
Windows 10 Version 20H2 (OS Build 19042.1348)
#### Name and version of other software in use when reproducing the issue:
Epic Hyperdrive running on an unreleased (under development) version
#### Other information about your system:
Running on a VDI through VMWare Horizon

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
I'm not aware of any add-ons in use
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by lukaszgo1** [comment]
Would you be able to test this with NVDA 2021.2 or preferably the latest beta of 2021.3?

**Comment by dwilliamepic** [comment]
2021.2 experiences the same issue. Where can I access the beta of 2021.3?

**Comment by lukaszgo1** [comment]
The latest beta can be downloaded from [here](https://www.nvaccess.org/files/nvda/releases/2021.3beta2/nvda_2021.3beta2.exe)

**Comment by dwilliamepic** [comment]
The beta version does not offer the ability to select Microsoft Speech API version 4, so it is not affected.

**Comment by lukaszgo1** [comment]
@dwilliamepic  This is quite strange - on my machine SAPI 4 can still be selected. Could you please start the latest beta, switch the logging level to debug (NVDA menu, Preferences, General settings, and choose debug in the Logging level combobox) then open the synthesizer selection dialog, and if SAPI 4 still does not show up upload the log file from the Tools -> Log Viewer here?

**Comment by dwilliamepic** [comment]
I am still not seeing version 4 available. I've attached the debug log

**Comment by lukaszgo1** [comment]
You cannot upload files by sending them as an email attachments. Please open the issue page in the web browser and upload that way.

**Comment by dwilliamepic** [comment]
[nvda debug log.txt](https://github.com/nvaccess/nvda/files/7652389/nvda.debug.log.txt)

**Comment by lukaszgo1** [comment]
@dwilliamepic Please retry with [the latest RC version of NVDA 2021.3](https://www.nvaccess.org/files/nvda/releases/2021.3rc1/nvda_2021.3rc1.exe) and if SAPI 4 still cannot be selected  open Python Console from the tools menu and execute the following lines:
```
from comtypes import GUID
CLSID_TTSEnumerator = GUID("{D67C0280-C743-11cd-80E5-00AA003E4B50}")
import winreg
winreg.OpenKey(winreg.HKEY_CLASSES_ROOT, r"CLSID\%s" % CLSID_TTSEnumerator).Close()
```

**Comment by dwilliamepic** [comment]
Okay that version does let me select SAPI 4 but is still running into the same speech issue where it will cut out most of the line of text that is correctly listed in the Speech Viewer.

**Comment by Adriani90** [comment]
@dwilliamepic do you still see this issue in NVDA 2023.3 RC2?

Is this issue reproducible only with Sapi 4 synthesizers? Or can you see it with other synthesizers as well?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since more thhan 2 years, I am closing as abandoned. If you are still having this issue, please comment and we can reopen.
