### ISSUE TITLE
Screen Reader reading dynamic content twice in Mozilla

### ISSUE THREAD

**Issue by asahun** [nvaccess/nvda#13105]
### Steps to reproduce:
I have the following sample html where I change the value of header dynamically with a button click. it will repeat some of the texts. my use-case is a calendar header where the month/year changes based on navigation.
`<div aria-live="polite" aria-atomic="true"> {{header}}</div>`
Attached is a simple Angular App to reproduce the issue.
[TestNVDA.zip](https://github.com/nvaccess/nvda/files/7621193/TestNVDA.zip)
### Actual behavior:
 it repeats some of the month values and it has a pattern too. Meaning it repeats the same set of months on next click and same set on previous click.
### Expected behavior:
It should not repeat value
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.2
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Mozilla Firefox
#### Other information about your system:
it reproduces in Windows Server 2016 too.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, 2019.2 and the behavior is the same.

**Comment by seanbudd** [comment]
Could you create a minimal example using [codepen](https://codepen.io) instead? That way we can confirm the issue is not caused by Angular, and NVDA developers do not need to create an Angular developer environment to debug this.

**Comment by asahun** [comment]
Thank you for getting back. I hope my sample app on [stackblitz](https://stackblitz.com/edit/angular-ivy-q7g5sl?) will work too.

**Comment by asahun** [comment]
I couldn't be able to reproduce using [codepen ](https://codepen.io/asahun/pen/KKXKYMz?editors=1111) with plain js. But I could still see it on [stackblitz](https://stackblitz.com/edit/angular-ivy-q7g5sl?) with sample Angular. Clearly your suspicion is point on. But I still don't know what the issue is or how to address it.

**Comment by asahun** [comment]
I found a way around it. I replaced the angular interpolation with [innerHTML] and that seems to work now.
