### ISSUE TITLE
word 365: NVDA loses performance over time in a document with many spelling errors  in the editor

### ISSUE THREAD

**Issue by enessaribas** [nvaccess/nvda#13103]
### Steps to reproduce:
 1. obtain a document with many, hundreds or thousands of spelling errors flagged by word.
 2. press f7, and go through the errors, correcting or ignoring as needed.

### Actual behavior:
as time goes by, NVDA becomes slower and slower to respond in the spellcheck editor,  and there is a multisecond lag in between key presses, on an octo core processor.  This is with UIA enabled, but also happens without.
### Expected behavior:
NVDA is responsive in the word editor, and allows correction of errors with no performance penalty over time.
#### NVDA installed/portable/running from source:
installed

#### NVDA version:
alpha-24237,a77aff3c
#### Windows version:
windows 11 21h2
#### Name and version of other software in use when reproducing the issue:
microsoft word 365 version  16.0.14527.20276
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by josephsl** [comment]
Hi,

Any updates as of May 2022 with Microsoft 365 Version 2203?

Thanks.

**Comment by Adriani90** [comment]
@enessaribas are you still having thiw issue with NVDA 2023.2?

**Comment by enessaribas** [comment]
yes, in fact now the editor is almost entire unusable with many spelling errors in a document.

**Comment by Adriani90** [comment]
@enessaribas to make investigation more efficient, could you please upload a test document where people can reproduce this issue? Thanks.

**Comment by enessaribas** [comment]
I cannot share this document as it is private.  Any document with many misspelled words trigger the issue.

**Comment by hwf1324** [comment]
I generated a document of random text using `lorem10000` as an example, but it may be a bit too long

[lorem10000.docx](https://github.com/nvaccess/nvda/files/13400163/lorem10000.docx)

**Comment by enessaribas** [comment]
yes this issue is worse now.  NVDA freezes when you press f7 to view the editor and spelling errors with this document.  Thanks for the example also.
Word version is 16.0.16924.20124

**Comment by Adriani90** [comment]
I agree this document has the significant performance issue with the spelling errors, you can even check it by enabling browse mode and pressing w to navigate from spelling error to spelling error. NVDA will take many seconds until it reports the word.
However, it seems Jaws suffers from the same problem, at least Jaws 2023. So it seems it is a MS Word issue rather than a screen reader issue.
However, Maybe there are some mechanisms to make NVDA scroll faster to the spelling errors.
@Qchristensen, @seanbudd how is it without using a screen reader? Can you scroll without performance issues to the spelling errors?
How is it when you use the f7 spelling error dialog without a screen reader?

**Comment by seanbudd** [comment]
Yes, even without a screen reader, navigating that document is extremely sluggish once activating `F7` and buffering 5000+ spelling errors. Note that it takes a while and some navigation for word to buffer them all in batches. Word crashed for me after trying to navigate deeper into the document with f7 active.

Closing this as a bug with word, this needs to be reported to microsoft
