### ISSUE TITLE
support StartAllBack software search suggestions; 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#13115]
### Steps to reproduce:
install StartAllBack software
now press start menu
type a search 
### Actual behavior:
nvda is muted, the suggestions are read only when walking with the arrows like this and below. 
### Expected behavior:
allow nvda to read the results as they are displayed 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
NVDA version alpha-24295,83125f2e
#### Windows version:
11 22000.348
#### Name and version of other software in use when reproducing the issue:
StartAllBack  3.0
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
log
[startback.txt](https://github.com/nvaccess/nvda/files/7636116/startback.txt)

**Comment by josephsl** [comment]
Hi, I think the log doesn’t describe the issue – can you try again after performing the steps provided in the issue please? Also, have you contacted the app developer about this problem? I won’t talk about personal opinions about overlays in general unless requested. Thanks.

**Comment by fernando-jose-silva** [comment]
sorry, I didn't understand your request, the log And from the moment I typed in the start menu, when I pressed the down arrows, the options were shown, but when I typed, nvda didn't announce.  I will try to communicate with the developers, but I believe that having an answer will be difficult, Seal nvda couldn't do anything, I believe the problem will persist.

**Comment by josephsl** [comment]
Hi,

May 2022 update: I still think it would be best to contact developers and tell them to implement auto-suggest accessibility provided that we are dealing with UIA here. That's how NVDA can announce search suggestsion in "default" Windows 10/11 Start menu.

Thanks.

**Comment by fernando-jose-silva** [comment]
I didn't get feedback from the developers

**Comment by josephsl** [comment]
Hi, this complicates the picture a lot. Either we can keep this issue open, or if needed, close it and come back to it later. Thanks.

**Comment by fernando-jose-silva** [comment]
Thank you, feel free to close if you want.
