### ISSUE TITLE
Repetition in items list with java software

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1312]
**Reported by aleskis on 2011-01-09 18:19**
With RSSOwl (a desktop agregator) in a feeds or news items list, pressing arrowdown or arrowUp, the synthetizor of NVDA repeat precedent item before saying the current. However, braille follow correctly. Apparently, the bug is known for java applications and RSSOwl uses java.

**Comment by leonardder** [comment]
Closing as invalid, because it is not possible to track down the original author, many things have changed since 2011 and I've never seen this bug in a JAVA app.
