### ISSUE TITLE
allow the user to momentarily disable the use of an add-on 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#13129]
### Is your feature request related to a problem? Please describe.
when an add-on works regularly but is having an error specifically when doing an activity in nvda, the user may want to just disable this add-on quickly, do the problematic activity and then re-enable the add-on quickly.
Nvda already allows you to disable an add-on, but this process takes a lot of time from the user, as he needs to go to the add-on manager window, find the add-on he wants to disable, need to disable the add-on, close the window, nvda restarts, then the user does what he wants, and then repeats everything again to re-enable the add-on.
### Describe the solution you'd like
what I would like is to be able to have functionality to disable an add-on by pressing a command in nvda, do the desired activity and press the same command to turn the add-on back on again.

### Additional context
logically there should be a dialog window that allows me to select the add-on and link to it a command key to disable and re-enable this command whenever I want.
Can be integrated into current add-on manager window.

**Comment by CyrilleB79** [comment]
Do you have a real-life example with a specific add-on? Or better, several cases with several add-ons?
The best alternative would be to ask to the add-on author to fix the issue in the add-on.

IMO, the developers' time would be better employed to fix the issue in the add-on rather than developing such a work-around in NVDA. Note also that, except for some parts of the speech or braille drivers, the vast majority of the add-ons are open source. So even if the author does not want or cannot fix the issue, someone else can.
Just my personal opinion though.

**Comment by fernando-jose-silva** [comment]
I agree that add-on developers should be the one to solve the problem, however the reality is very different, some add-ons go for years, and years, without any updates.
 to observe this, just look at the nvda add-ons page, it looks like a graveyard of incompatible add-ons.
 Also, let's remember that once a year, almost all add-ons stop working due to major changes in the nvda code, and in this change, many are left behind.
 The fact that the add-ons are open source does not make the community mobilize and solve the problems found.
 Finally, we have to remember, that the use of add-ons in nvda is not unimportant, many users would give up using the screen reader, if some very necessary add-on stopped working, making it unfeasible if the use of nvda in all areas .
 Finally, it was just a suggested solution, you have the autonomy to accept it or not.  thanks.

**Comment by fernando-jose-silva** [comment]
Sorry, I remembered something else, it's also about leaving the control a little more in the users' hands, without having to wait for the community to mobilize so that their problem is fully resolved.
 again, respectfully, it was just a suggestion.

**Comment by CyrilleB79** [comment]
I have expressed my opinion but the ticket and the discussion is always open.
So please give real situations and add-ons examples to better illustrate the need, rather than only generalities.
Thanks.

**Comment by fernando-jose-silva** [comment]
what made me think about this solution was the add-on extension of nvda features and emoji Windows 11. I work with novice users, and sometimes with learning difficulties, who use this add-on to help in using nvda.  please don't take this one example as I believe it will be resolved, but there are, there will be other examples to come.
 please be careful in using the word generalities, as I use the screen reader in my day, including teaching the use of this screen reader to large groups of visually impaired users, again, these users use many add-ons to facilitate the use of the nvda, novice users, and with learning difficulties most of the time.
 And I believe I know what I'm talking about.

**Comment by lukaszgo1** [comment]
The discussion of fixing the issue of an add-on or implementing this work around aside it would be extremely hard or even impossible from a technical standpoint to disable add-on without forcing restart of NVDA.

**Comment by CyrilleB79** [comment]
> what made me think about this solution was the add-on extension of nvda features and emoji Windows 11. I work with novice users, and sometimes with learning difficulties, who use this add-on to help in using nvda. please don't take this one example as I believe it will be resolved, but there are, there will be other examples to come. please be careful in using the word generalities, as I use the screen reader in my day, including teaching the use of this screen reader to large groups of visually impaired users, again, these users use many add-ons to facilitate the use of the nvda, novice users, and with learning difficulties most of the time. And I believe I know what I'm talking about.

Hi Fernando

Sorry if my words have hurt you. I have used the word "generality" just to insist on the fact that one or many examples help much more to understand the problem encountered by the person who has opened the ticket.
You have proven by your activity on NVDA's GitHub and mailing-lists that you know very well the topic, and I am not questioning this point at all.
Just to clarify...

Note: I will hide this comment that is off-topic.

**Comment by fernando-jose-silva** [comment]
@CyrilleB79  fique tranquilo, estamos aqui todos em prol de uma causa só, de melhorar a vida das pessoas com deficiência visual.
Muito, mas muito obrigado mesmo pelo seu trabalho, tenho muita gratidão e muito respeito pelo trabalho que vocês fazem, mais uma vez muito, muito obrigado, parabéns.

**Comment by josephsl** [comment]
Hi,

May 2022 update: hypothetically, it might be possible, but technically, no. This is because of the fact that when Python imports modules such as parts of add-ons, they stay in memory until Python is reloaded. In other words, the best way to suspend add-ons momentarily (as this issue requests) is restarting NVDA with some or all add-ons disabled.

As for an example given (NVDA Extensions Global Plugin and Windows 11 emoji panel), I hope Paul has found a way to resolve the error you are experiencing. Besides, Windows 11 emoji panel support is now present without help from add-ons.

Thanks.

**Comment by fernando-jose-silva** [comment]
thank you, sorry, feel free to close the problem
