### ISSUE TITLE
enable speech announcement of the progress bar at shorter intervals 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#13124]
### Is your feature request related to a problem? Please describe.
no
### Describe the solution you'd like
when we enable the reading of progress bars by voice, nvda announces them more or less within a 10% range.
when we enable the beeps they are made every 1% or so.
I confess that I don't really like the sounds, including the beeps, and I'm disabling them when possible, I like to receive feedback with voice.
But when I disable the reporting of progress bars on beeps I miss the voice announcements at a shorter interval.
I would suggest enabling users to choose how many % each they would like to receive voice announcements from the progress bar.
if this option existed maybe I would put it at every 3%.
Again a user configurable option as this is very personal.

**Comment by Mohamed00** [comment]
There's a hidden setting that will do what you want. Open the Python 
console and paste in these two lines.

import config
config.conf['presentation']['progressBarUpdates']['speechPercentageInterval']=3

**Comment by OzancanKaratas** [comment]
Duplicate of #5031.

**Comment by fernando-jose-silva** [comment]
Thank you very much
@Mohamed00 
this is exactly what i would like
as a suggestion I would like this function to be available in the user interface.
Or that these console commands were documented in the user documentation.

**Comment by seanbudd** [comment]
Closing as duplicate of #5031
