### ISSUE TITLE
Outlook 2013 hangs when sending email with reminder window open

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/nvda#13128]
This issue was reported on the NVDA Dutch mailing list

### Steps to reproduce:
1. Write a mail in Outlook 2013
2. Ensure the reminder window is open
3. Send the e-mail

### Actual behavior:
NVDA and Outlook both hang. After NVDA  is manually restarted, outlook still hangs, though recovers automatically and yet sends the e-mail.

### Expected behavior:
NO freezes.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2021.3RC1

#### Windows version:
UInknown

#### Name and version of other software in use when reproducing the issue:
Unknown

#### Other information about your system:
Unknown

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This problem didn't occur with 2021.2

#### If NVDA add-ons are disabled, is your problem still occurring?
Hard to reproduce as as far as I know, the user relies on an add-on speech synth.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Tool has run during installation, so I guess so.

**Comment by Adriani90** [comment]
@leonardder do you know if this happened also on a newer version of Office?

**Comment by leonardder** [comment]
I've never seen this happening myself.

**Comment by Adriani90** [comment]
Given support for Outlook 2013 ended years ago, I don't expect any further updates related to this version. If someone can reproduce this issue with newer versions of Outlook, please comment and we can reopen. I am closing as abandoned.
