### ISSUE TITLE
Irreliable behavior in application switching (alt+tab) under windows 11

### ISSUE THREAD

**Issue by abdullah5490** [nvaccess/nvda#13134]
### Steps to reproduce:
1. Open multiple programs on your computers.
2. try to switch between opened windows by pressing alt+tab, you'll here unusual repetitive announcements of word "pain", and most of the time after leaving the alt key, it will not correctly focuss the forground windows and does not read anything. We have to repeat the switching process again to come back to this windows in order to NVDA work in it.

### Actual behavior:
By holding "alt" key and hitting "tab" for navigating the task switcher for opened windows, NVDA kept repeating "pain, Pain" along with windows title. It even sometime do not speak the title and just repeat "pain". Also, after leaving the alt key at any window to jump focus in it, NVDA doesn't focus it correctly and stop interacting with on-screen content untill I repeat task switching process to come back to this windows again. Sometime it works and sometime I need to repeat the process thrice.

### Expected behavior:
While holding "alt" and pressing "tab", NVDA should speak titles of opened programs (as It did in windows10 and earlier), and after leaving "alt" at any title, it should jump in to that program's window and start interacting with on-screen content normally (as it did in windows10 and earlier).

#### NVDA installed/portable/running from source:
NVDA installed locally, no portable, but same problem if I'm running the portable version under windows 11.
#### NVDA version:
2021.2.
#### Windows version:
windows11, build 22000.318.
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
My system is dell 7290, core i5 8th gen with 8GB-DDR4 RAM and 512GB M2-SSD drive. But this problem is only on windows11, not specific to any system/model.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by josephsl** [comment]
Hi, can you try with NVDA 2021.3 RC and see if that changes things for you? Thanks.

**Comment by abdullah5490** [comment]
@josephsl  Yes, after reading your comment, I tried RC version and feeling that issue is much more minimized and its working quite fine now. Please add this issue as marked as resolved in the latest change log of NVDA 2021.3 version. 
I'm thankful.

**Comment by josephsl** [comment]
Hi, actually, this is a duplicate of an earlier issue. Thanks.

**Comment by abdullah5490** [comment]
@josephsl  could you please mention that issue here so that I can read? because I did a search before creating new issue with input query "windows11" but only 1 issue popped up which was about something different. that's why I've created this one. I'm interested to know the duplication that i'm doing of.

**Comment by josephsl** [comment]
Hi, it is issue #12648. Thanks.

**Comment by Brian1Gaff** [comment]
I was thinking that some third party app or new windows message might have 
been interfering with the focussing of the next program window. I've had 
such things go on with some anti virus or other alerts even back to windows 
7, so I nearly always disable stuff that might cause it one at a time.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----
