### ISSUE TITLE
MathPlayer in Edge 96

### ISSUE THREAD

**Issue by dTolmachev1** [nvaccess/nvda#13132]
### Steps to reproduce:
With already preinstalled MathPlayer open latest version om Microsoft Edge and find some math content, E.G. math article on Wikipedia.
### Actual behavior:
NVDA reads any kind of equation as if MathPlayer is not installed.
### Expected behavior:
NVDA provides access to the interface for interacting with equations through the MathPlayer.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2021.2
#### Windows version:
Windows 10 21H2 (Build 19044.1348) (also tested on latest build of Windows 11).
#### Name and version of other software in use when reproducing the issue:
Microsoft Edge 96.0.1054.43 (Also tested with previous versions from 96.x branch).
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2021.1 -- the same.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.
### Additional details:
MathPlayer works correctly with all previous versions of Edge (95.X-), so maybe that's an Edge related issue, but I'm not sure.

**Comment by josephsl** [comment]
Hi,

Can you tell us what happens now with Edge 101?

Thanks.

**Comment by dTolmachev1** [comment]
Now (with Edge 101.1210.53) the issue is completely fixed.
