### ISSUE TITLE
The word landmark is no longer abbreviated in braille

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#13158]
### Steps to reproduce:
1. Connect a braille display.
2. Go to www.nvaccess.org.
3. Ensure that browse mode is turned on.
3. Press Ctrl+Home.

### Actual behavior:
The braille display shows:
"landmark navi h1 lnk gra NV Access"

### Expected behavior:
The display shows:
"lmk navi h1 lnk gra NV Access"
That is, "landmark" should be "lmk", just as "navigation" is shortened to "navi".

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:

2021.3

#### Windows version:
Windows 10 21H2 (10.0.19044) workstation

#### Name and version of other software in use when reproducing the issue:
Firefox 95.0

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, "lmk" is shown in 2021.2 and the release notes does not mention this change.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by dkager** [comment]
It looks like `getControlFieldBraille` retrieves `controlTypes.Role.LANDMARK.displayString`, but the value from `braille.roleLabels` should probably be used.

**Comment by feerrenrut** [comment]
Please test and confirm this is fixed in the RC for 2021.3.1: https://www.nvaccess.org/post/nvda-2021-3-1rc1/

**Comment by lukaszgo1** [comment]
Confirmed as fixed.

**Comment by dkager** [comment]
I can confirm that this issue is fixed.
