### ISSUE TITLE
garbageHandler related errors triggered during Google Chrome usage

### ISSUE THREAD

**Issue by DraganRatkovich** [nvaccess/nvda#13163]
Today, when I just opened the log viewer, I noticed a long line of errors, which in turn is very large, so I am attaching the log here for developers to view.
I am using an installed copy of NVDA 2021.3. The same bug existed in previous version of nvda 2021.2.
@lukaszgo1 @michaelDCurran @seanbudd @feerrenrut 
### Steps to reproduce:
Not sure since I don't know what is causing the problem, but just open the log viewer and you will notice the error, even if you do, I don't know.
### Actual behavior:
NVDA shows over a thousand error symbols
### Expected behavior:
NVDA should not show errors
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2021.3, also exists in 2021.2
#### Windows version:
Windows 8.1 pro X64, Windows 10 pro x64
#### Name and version of other software in use when reproducing the issue:
NA
#### Other information about your system:
NA
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2021.2, also existed same problem
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes
[nvda.log](https://github.com/nvaccess/nvda/files/7713458/nvda.log)

**Comment by seanbudd** [comment]
Hi @DraganRatkovich,
Thank you for reporting this issue, we are concerned that this could be a serious issue and could cause crashes or freezes. We haven't managed to be able to reproduce this ourselves. We have a few questions to help us investigate further:
- Would you be able to describe what applications you are using when this happens?
- Is there any noticeable change of behaviour?


Could you provide the full log file of this occurring? [This contains some instructions](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps#log-levels). If you have privacy concerns, this is understandable - you can email the log file to info@nvaccess.org. If there are still concerns, feel free to trim the log, but we need more context than what was provided. Specifically, we need information before the garbage handler warning starts i.e at least 5 minutes before the first warning timestamp. We are trying to work out the affected application and actions taken prior to this happening.

Regards,
Sean

**Comment by DraganRatkovich** [comment]
@seanbudd Hi,

I have set the log level for debugging, so I think there is a more verbose log. I use Google Chrome a lot and as I noticed in the log debug mode the error is caused by chrome, although I'm not sure as there are several lines of errors that I am not aware of. As for the behavior, when an error occurs, NVDA's behavior does not change, it continues to work as it was. Here is a new log.
[nvda.log](https://github.com/nvaccess/nvda/files/7717135/nvda.log)

**Comment by feerrenrut** [comment]
There are a lot of add-ons enabled in this log. Can you please test again (debug level logging) but with all add-ons disabled?

**Comment by DraganRatkovich** [comment]
@feerrenrut Sure. Here it is.
[nvda.log](https://github.com/nvaccess/nvda/files/7726909/nvda.log)

**Comment by seanbudd** [comment]
Hi @DraganRatkovich - neither of those newer logs contain the same set of `garbageHandler.notifyObjectDeletion` errors as the first log provided.

**Comment by DraganRatkovich** [comment]
@seanbudd Hello,
Very interesting. I don’t know why it doesn’t give errors in debug mode. What then are the errors recorded in the current attached logs? Are they fixable?

**Comment by seanbudd** [comment]
Hi @DraganRatkovich - the warnings that occurred in those logs are relatively minor to the initial log you provided.
Error level logs are still provided in debug mode, it's just that the errors you provided in the initial log did not occur.
If you happen to encounter those errors again, please upload the full log.

Thanks

**Comment by seanbudd** [comment]
With 2021.3, if you turn on the setting ["Play a sound for logged errors"](https://www.nvaccess.org/files/nvda/documentation/userGuide.html#AdvancedSettings) found in the advanced settings, you will get a beep when an error occurs.

That way, you can check the logs and see if the `garbageHandler.notifyObjectDeletion`/ `garbageHandler._collectionCallback` error, or another error, has occurred.

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since more than one year, and I cannot reproduce the issue. I assume it was due to a specific addon. Anyway, since updates are missing, I am closing this as abandoned.

**Comment by Adriani90** [comment]
I have to say, trying with NVDA 2022.4, 2022.3 and 2023.1 as well as with last alpha in Chrome 111, I cannot reproduce this issue.
