### ISSUE TITLE
LibreOffice: choose Printer, NVDA inappropriately reports all content in the container

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#13167]
### Issue Description:

The bug specifically occurs when users attempt to select a printer in the Print dialog of LibreOffice Calc. NVDA inappropriately reports all the content within the container, rather than only reporting the selected printer. This behavior can be confusing and overwhelming for users.

### Steps to reproduce:
1. Open LibreOfficeDev Calc.
2. Press Ctrl+P to open the Print dialog.
3. Press the Tab key to navigate to the Printer option.

NVDA reads out the content as follows: 

Printer combo box - Microsoft Print to PDF. The list box shows the installed printers. Click the printer to use for the current print job. Click the Properties button to change some of the printer properties. Alt+i, 12 of 14 level 1.

4. Press the Up Arrow key.
   

#### Actual behavior:

Upon pressing the Up Arrow key, NVDA reads out additional content related to the Page Layout option pane: 

speech: 

Page Layout  option pane

Paper size:  combo box  Set the paper size you would like to use. The preview will show how the document would look on a paper of the given size.  6 of 18

A4 210mm x 297mm  6 of 18  level 1

#### Expected behavior:

The expected behavior is for NVDA to only report the selected printer when the "Up Arrow" key is pressed, without providing any additional information related to the Page Layout option pane.

#### NVDA installed/portable/running from source:
Portable

#### NVDA version:
2023.2rc1

#### Windows version:
Windows version 10.0.19042

#### Name and version of other software in use when reproducing the issue:
LibreOffice version 7.6.0.3

#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2021.3
#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No.

**Comment by CyrilleB79** [comment]
Hi @surfer0627 

Please update to last  version of NVDA (2023.1, or better, 2023.2rc1), as well as last version of Libre Office. There have been accessibility fixes on both sides recently.

Cc @michaelweghorn

**Comment by surfer0627** [comment]
Hi @CyrilleB79 ,
Thank you for your comment. 
I have added your suggested changes into the description.

**Comment by michaelweghorn** [comment]
This is a LibreOffice bug, since it incorrectly sends an `ACTIVE_DESCENDANT_CHANGED` event for the paper size combobox/listbox whose value changes dependent on the selected printer.

I've created a corresponding LibreOffice report (just copied the text from here):
https://bugs.documentfoundation.org/show_bug.cgi?id=157137

Pending fix (to be included in the next LibreOffice version 24.2):
https://gerrit.libreoffice.org/c/core/+/156666

So I think this NVDA issue can be closed. (And maybe adding an `app/libreoffice ` label would make sense, too, so it shows up when filtering issues for LibreOffice-specific tickets.)

**Comment by CyrilleB79** [comment]
Thanks @michaelweghorn. Closing.
