### ISSUE TITLE
NVDA should not speak any punctuation at level "None"

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#13172]
### Is your feature request related to a problem? Please describe.
At present, in the "symbols.dic" file for NVDA, from about 300 symbols (or more - I don't know their exact number), over 100 of them are set to the "None" level and are read no matter the punctuation level set. For one, this does not make any sense, because "none" means "nothing", which should mean that no symbols are read at this level. For another, the "none" punctuation level is designed with the idea of smoother and more natural reading experience, which should mean - no punctuation spoken. But alas, with NVDA at present, this is not true - quite a lot of symbols are read even at level "None", which brakes the smoothness and naturalness of the reading experience.

### Describe the solution you'd like
The NV Access team should reconfigure those symbols by default to be read only at levels "Some" and higher, instead of them being read at level "None" as well. Furthermore, this mistake should not be repeated - in the future, no more symbols should be set to be spoken at level "None".

### Describe alternatives you've considered
Each user can manually reconfigure those symbols at level "None" to be read at levels "Sone" and higher, but that is not an ideal solution. For one, each user that wants it, has to do it on his own and probably not all users are comfortable or knowledgeable enough to do it. For another, there are quite a lot of such symbols and it would be quite a task for each wanting user to do it on his own. Furthermore, this has to be done for each new added symbol that is defined to be spoken at level "None".

### Additional context
And for people who for one reason or another want more punctuation spoken, they can set NVDA to a punctuation level different than "none".

**Comment by zahra21** [comment]
i completely agree.
i has this issue since nvda 2016.2 and change in nvda settings myself manually.

**Comment by feerrenrut** [comment]
It might be better to think of "none" as "minimal".
- Is there a use-case for having no symbols at all reported?
- Any specific symbols that cause a problem in this category need to be individually explained so we can reconsider them.

I'm going to close this issue, since I don't think we can progress it as it is.

**Comment by k-kolev1985** [comment]
I think there should be a level "None" as there is now, where no punctuation is spoken. Reason: more smoother and natural reading experience.

If NV Access and the users desire, another punctuation level called "Minimal" could be created and that will include for reading the symbols set now to be read at level "None".
