### ISSUE TITLE
NVDA says clipboard empty when a message opened in outlook 2007 or a document in word 2007

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1319]
**Reported by surveyor on 2011-01-12 09:38**
When a message opened to read in outlook or a document in word 2007, NVDA at first says "clipboard empty" when used arrow keys to read the document. It is required to change the focus and turn back the document window with alt+tab or close and reopen the document to read the document normally.

**Comment by leonardder** [comment]
Closing because the author didn't respond to @JosephSL's request for more information and abandoned this issue. Feel free to provide details if this still occurs, though.
