### ISSUE TITLE
[Screen reader-M365 Admin Portal-Your Tenants (tenant switcher)] : Screen reader doesn't notify whether the search box is cleared or not, while clicking on ‘clear’ button. 

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#13200]
### Steps to reproduce:
1.Open URL, login with your credentials and start screen reader.
2.Navigate to search edit field and enter data in that, clear button will be visible
3.Observe if screen reader notifies whether the search box is cleared or not, while clicking on ‘clear’ button.

### Actual behavior:
Screen reader doesn't notify whether the search box is cleared or not, while clicking on ‘clear’ button.

### Expected behavior:
Screen reader should notify that data is cleared.

### Additional Notes:
1.Similar issue has been observed for all search edit fields.
2.Similar issue has been observed for 'remove' button in add cards.

### System configuration
Application: M365 Admin Portal
URL: https://admin.microsoft.com/Adminportal/Home
Browser: Edge, Version 96.0.1054.62 (Official build) (64-bit)

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA Version 2021.1

#### Windows version:
Window 11, Version 21H2 (OS Build 22000.376)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, also reproducible through NVDA version 2020.4

**Comment by feerrenrut** [comment]
This needs further investigation by Microsoft developers. Please provide a minimal test case for us to investigate. I'm closing this issue for now.
