### ISSUE TITLE
[M365 Admin center-Setup Guidance-Training Resources] Screen reader is reading twice the button name.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#13207]
### Steps to reproduce:
Step 1: Open the URL in Edge Dev browser and Turn on NVDA.
Step 2: Select 'training resources' tab and activate 'email your organization' button.
Step 3: Navigate 'topic' dialog box and verify screen reader is announcing 'next' button name twice or not. 

### Actual behavior:
Screen reader is reading 'Next button next' while navigating the next button in topic dialog box.

### Expected behavior:
Screen reader should read 'Next button' while navigating the next button.

### Additional Note:
Same issue reproducible for 'Preview', 'Recipients', 'Review and finish' dialog box.

### System configuration
Application: M365 Admin Portal
URL: https://admin.microsoft.com/Adminportal/Home
Browser: Edge, Version 96.0.1054.62 (Official build) (64-bit)

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA Version 2021.1

#### Windows version:
Window 11, Version 21H2 (OS Build 22000.376)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, also reproducible through NVDA version 2020.4

**Comment by lukaszgo1** [comment]
Please retry this with NVDA 2021.3.1. In general reporting issues with outdated versions of NVDA is not a very good idea TBH.

**Comment by msftedad** [comment]
This can be closed. Issue is no longer reproducing.

**Comment by ehollig** [comment]
Closing as requested.
