### ISSUE TITLE
[M365Admin Portal - Volume Licensing] : In browse mode screen reader focus does not move to links under 'Downloads & Keys'.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#13206]
### Steps to reproduce:
Step 1: Open URL and login with valid credentials.
Step 2: Start NVDA and Activate 'Volume Licensing' tab.
Step 3: Navigate to link under 'Downloads & Keys' in browse mode. 
Step 4: Observe the issue.

### Actual behavior:
In browse mode screen reader focus does not move to links 'Downloading Software, Viewing Keys, Online service activation' under 'Downloads & Keys'. Focus lands on whole information and at a time it announcing three links.

### Expected behavior:
In browse mode screen reader focus should move individually to all the links under 'Downloads & Keys' separately.
Ex: Focus should navigate in below format in browse mode
Downloading Software - Viewing keys - Online Service Activation

### System configuration
Application: M365 Admin Portal
URL: https://admin.microsoft.com/Adminportal/Home
Browser: Edge, Version 96.0.1054.62 (Official build) (64-bit)

#### NVDA installed/portable/running from source:
Installed 

#### NVDA version:
NVDA Version 2021.1

#### Windows version:
Window 11, Version 21H2 (OS Build 22000.376)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, also reproducible through NVDA version 2020.4

**Comment by feerrenrut** [comment]
This needs further investigation by Microsoft developers. Please provide a minimal test case for us to investigate. I'm closing this issue for now.
