### ISSUE TITLE
Narrator doesn't announce the automation properties name of TextBox control

### ISSUE THREAD

**Issue by angel-kou** [nvaccess/nvda#13216]
### Steps to reproduce:
1. Create a WPF app in .NET 4.8 or .NET 5.0
2. Add a text box control and set the AutomationProperties.Name to "hello"
3. Turn on narrator and focus on the text box
4. Observe that narrator doesn't announce "hello" or the text of the text box. It says "No item in view"
### Actual behavior:
Narrator says "No item in view"
### Expected behavior:
Narrator should say "TextBox hello {text-in-textbox}"
#### Name and version of other software in use when reproducing the issue:
Visual Studio 2022

**Comment by feerrenrut** [comment]
This is the bug tracker for NVDA not for Narrator, if you are having trouble with Narrator please submit feedback with `Narrator key + alt + f`

If you did mean to refer to NVDA, please provide information on the version you are using and the source code for a minimal test case (attach as a zip file) for us to investigate further. I'm going to close this issue for now, please comment to re-open.
