### ISSUE TITLE
NVDA does not install on Windows 10 21H2

### ISSUE THREAD

**Issue by teo951** [nvaccess/nvda#13222]
### Steps to reproduce:
Open computer with Windows 10 21H2
### Actual behavior:
Installation starts and display window with information: Please wait while Setup is loading…, window close sand Setup does not display.
### Expected behavior:
Start Setup
### System configuration
Laptop HP Probook
#### NVDA installed/portable/running from source:
Runing  filenvda_2021.3.1.exe
#### NVDA version:
2021.3.1
#### Windows version:
Windows 10 21H2
#### Name and version of other software in use when reproducing the issue:
No
#### Other information about your system:
I tried install NVDA on 4 computers with Windows 10 21H2 and was the same behavior
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, Same like 2021.3.1
#### If NVDA add-ons are disabled, is your problem still occurring?
Blank installation of NVDA
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
No installed NVDA

**Comment by lukaszgo1** [comment]
After starting NVDA's launcher please go to %temp% and check if file nvda.log was created there. If it was please attach it to this issue.

**Comment by teo951** [comment]
I do not have any nvda'-.log file anywhere.

**Comment by lukaszgo1** [comment]
Would you be able to create a portable NVDA (NVDA menu -> Tools -> Create portable copy) on another computer and try starting from it by running nvda.exe from the created folder on the machine on which it does not work?

**Comment by teo951** [comment]
I do not have installed NVDA on any computer. I'm aPole, so maybe we will discuss in Polish? My e-mail: leszekz@gmail.pl

**Comment by teo951** [comment]
I managed to create NVDA for a pendrive and works on a computer where I can not install it.

**Comment by Brian1Gaff** [comment]
This is very peculiar, I'm hoping you do not have Avast or another anti 
virus installed on the machines, as they do seem to think they are centre of 
the universe. What about Narrator? Does that still work and does it shed any 
light on what happens as nvdas installer  runs, can you  install from the 
portable which is running?
I think the key is to find a log file. There usually is one, even if install 
is broken.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by teo951** [comment]
I have only Defender, but I tried to install NVDA with a Defender turned off. Unfortunately, without success. I managed to install NVDA from a portable disk. Thank you for your help.

**Comment by josephsl** [comment]
Hi,

Note that there are two Windows 10 21H2 releases: client (build 19044) and Server 2022 (build 20348); I assume the former (client); to reduce confusion, please provide the build number as well.

One important question that isn't addressed: are these computers part of a corporate network/domain? If yes, this may partly explain why - there are settings admins can set which can block software installation from untrusted sources. Also, are these computers up to date, as in running build 19044.1415 (with December 2021 cumulative update applied)?

Thanks.

**Comment by seanbudd** [comment]
Hi @teo951 - 

Could you try installing with [this installer](https://ci.appveyor.com/api/buildjobs/yfcbf3j6vrm2by5l/artifacts/output%2Fnvda_snapshot_try-NSISAsSubmodule-24877%2Cffd63ec6.exe)?  We are trying to test if #13398 solves your problem of the installer failing.

Regards,
Sean

**Comment by seanbudd** [comment]
Can you test the latest alpha build and confirm that this is still an issue: https://www.nvaccess.org/files/nvda/snapshots/ ?

**Comment by seanbudd** [comment]
Closing this issue as we have not heard back from the author in almost 2 years
