### ISSUE TITLE
NVDA Settings Search - Please add this feature

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#13225]
### Is your feature request related to a problem? Please describe.
There is no easy way to "drill down" into NVDA settings if you do not know precisely where a given setting is located.  Settings search features have now become almost ubiquitous.  NVDA really needs to add one.
### Describe the solution you'd like
The addition of a Settings Search feature when NVDA Settings are open.

**Comment by josephsl** [comment]
Duplicate of #872, closing as that issue includes additional details.
