### ISSUE TITLE
A command to silence ARIA speech

### ISSUE THREAD

**Issue by Gene703122** [nvaccess/nvda#13220]
It is my understanding that aggressive ARIA speech can cause serious problems by interfering with other speech.  There should be a user definable command to stop ARIA speech.

**Comment by Brian1Gaff** [comment]
One issue I see, which may well be what you mean is when a home page has a 
slide show, and while you are trying to make sense of the way the page is 
laid out you keep hearing  now viewing slide x of xx every time it changes. 
I can get rid of that by turning of speak new content, but I fully realise 
this is poor page design, but is there a toggle for the speak new content? I 
had a poke about but could not find one.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Gene703122" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Friday, January 07, 2022 10:48 PM
Subject: [nvaccess/nvda] A command to silence ARIA speech (Issue #13220)

**Comment by lukaszgo1** [comment]
As it stands this issue is not actionable. 
- There is no such thing as an 'ARIA speech' - at a guess you probably mend `aria-live`
- If my guess is correct you can already turn off announcements of live regions with NVDA+5, but since you gave no example of the problematic web page it is impossible to say if this is sufficient for your use case.

Also please fill the issue template next time.

**Comment by Gene703122** [comment]
As far as the dynamic content command, NVDA 5, is concerned, that addresses what I wanted to solve.  I'd seen it stated on a large e-mail list that there is no way to stop this speech and there was no rebuttal to the statement.  Perhaps the purpose of the command isn't well known.  

I didn't include a web site because I don't have an example, though I know aggressive live Aria region speech can be very intrusive.  

Regarding the template, I tried to fill it out but my comments never were in the template.  I'll try a different browser and see if that solves the problem.  If not, I'll ask about how to resolve the problem.

Gene

**Comment by josephsl** [comment]
Hi, or I’d say not documented well in the user guide – if NVDA+number row 5 does resolve this issue, then I guess an update to the user guide might be a good suggestion. Quentin, any thoughts? Thanks.

**Comment by Gene703122** [comment]
I want to give some explanation and to thank those who have provided a solution.  

I submitted this issue because I was annoyed by some forced speech in Thunderbird. I had had the idea of submitting an issue on forced speech in ARIA regions vaguely in mind and that motivated me to do so.  I didn't mention Thunderbird because I didn't know if the speech was related.  However, the report dynamic content command appears to stop unwanted verbosity in Thunderbird.

 I'd never seen the report dynamic content changes command proposed as a solution, in such contexts, as I recall.

I think I know one perhaps important reason the command seems to be so little known for such uses.  Here is the manual entry about the command:
Key: NVDA+5 
Toggles the announcement of new content in particular objects such as terminals and the history control in chat programs.  

I suspect this language is from the early days of the manual and this sort of forced speech may not have been prevalent.  I hope the discussion is broadened to discuss these sorts of contexts.  If such discussion isn't in the training material, I hope it is added.

I appreciate finding the answer through those who commented.

**Comment by lukaszgo1** [comment]
> I submitted this issue because I was annoyed by some forced speech in Thunderbird. 


Have you reported this to Thunderbird developers?

> 
> I'd never seen the report dynamic content changes command proposed as a solution, in such contexts, as I recall.

That is probably because the fact that it disables announcements from live regions is pretty new - I believe it was introduced about a year ago.

> I suspect this language is from the early days of the manual and this sort of forced speech may not have been prevalent. I hope the discussion is broadened to discuss these sorts of contexts. If such discussion isn't in the training material, I hope it is added.

It is unreasonable to expect an end user to know that speech is coming from the live region so documenting this in a understandable way would be pretty tricky.

**Comment by Gene703122** [comment]
It wouldn't be hard to discuss.  You could discuss what might cause the problem such as an aggressive live region on a web page, but as a general statement, you could say that whenever you hear unwanted speech, try turning off report dynamic content to see if that solves the problem.  

That's how I stopped excessive forced speech in Thunderbird.  I don't know technically how the developers are inappropriately forcing excessive speech but I stopped it in that way.  

This is important for users to know.  I saw a long discussion about this problem in Thunderbird perhaps eight months ago and no one proposed turning off report dynamic content, which would have instantly solved the problem..

**Comment by mltony** [comment]
FWIW in BrowserNav  v2.2 I added an option to block aria live speech selectively for specific websites/pages. Just in case you don't want to block live speech everywhere.

**Comment by feerrenrut** [comment]
@Gene703122 If you have any suggestions on how to clarify the user guide in this case please add a comment with the suggestion, for now I'm going to close this issue.

**Comment by Gene703122** [comment]
Something like this might be included.  At times, a web site or program will force unwanted speech that is disruptive or clutter.  In such cases, turning report dynamic content changes off may silence such speech.  
I would think this should be above what is already there because it is probably of interest or use to the most users and states a general and wider application.

I'm not sure if this is the right place to discuss manual changes and changes to the training material but if this isn't discussed in the training material, it should be.  The command appears to be very little known for the purpose I'm discussing.

**Comment by feerrenrut** [comment]
I think this is a fine place to discuss this. I think what you suggest is an improvement, however it would be good to explain the dynamic aspect. Eg content being reported that is not a direct response to a users input.

**Comment by Gene703122** [comment]
I don't object to a definition being given, but as you will see later, it needs to be done carefully and I don't think it is necessary.  

Here is something like what might be said:
At times, a web site or program will force unwanted speech that is disruptive or clutter. In such cases, turning report dynamic content changes off may silence such speech.

An example is a web page with a stock ticker, constantly updating information.  If you don't want to hear this constant speech, turn off report dynamic content changes.

Another example is a program that announces unwanted status updates, such as downloading message 3 of 8, in the case of an e-mail program.

Your definition, even if technically correct, would confuse the issue.  There are many times when dynamic content is announced in response to a user command.  In the command prompt, turning off report dynamic content changes silences all output in response to commands.  I think giving examples is better than a definition in this case unless a different one is provided.  I don't think it is necessary but I have no objection if it doesn't limit or confuse matters.
