### ISSUE TITLE
Behaviour of Home and End keys in NVDA UI sliders

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#13230]
### Steps to reproduce:

1. Open NVDA's speech settings (NVDA+control+v)
2. Tab to one of the sliders (perhaps pitch or inflection, which are less likely to make it unintelligible)
3. Press HOME
4. Press END
5. Press PAGE UP several times
6. Press PAGE DOWN
7. Press ESCAPE to close the dialog without making any changes (the value should return to what you were using.  If you get stuck, press NVDA+control+r to restore the previously saved configuration).

### Actual behavior:

At step 3, (Home), the slider goes to "100%", the highest value.
At step 4, (End), the slider goes to "0%", the lowest value.
At step 5, (page up), the value increases.
At step 6, (page down), the value decreases.

### Expected behavior:

In most situations, the Home key generally moves to the start of something (Home takes you to the start or leftmost point of the line, control+home takes you to the top of a document, etc).

Similarly, the End key generally moves to the end of something, the rightmost point of a line or control+end to the bottom of a document.

Page up moves towards the top or start - towards where home (or control+home at least) would take you.
Page down moves towards the end or bottom - towards where end (or control+end) would take you.

So, in this case, I would expect Home to move to the leftmost, lowest value of the slider, and end to move towards the rightmost, highest value.

#### NVDA version:

NVDA 2021.3.1 installed

#### Windows version:
Windows 10 (64-bit) Version: 21H2 (2009), Build: 19044.1415 

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, tried portable copies of various versions back to 2015.3.  The bahaviour was the same.  I'm surprised if it really has been like that for years, although pressing home and end on things like the speech rate aren't the most common behaviours.  (I wrote the "expected" behaviour in the Basic Training material back in 2016.  I can't recall specifically now, but I'm sure I would have tested the keystroke before writing it).

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by feerrenrut** [comment]
This also happens without NVDA, in several standard Windows OS controls. However, within Windows there is a mix of behavior. 
- The volume slider shown when let clicking the audio device in the system tray is also backwards.
- The opposite behavior is shown with the volume slider on the levels tab, of an audio devices properties, accessed via the sound control panel, via sound settings.

At this point, I think we'll have to assume it is a bug / quirk in Windows given even those controls aren't consistent.

An image to show the audio device properties dialog:
![image](https://user-images.githubusercontent.com/3491346/149045668-8f825604-2beb-45b7-84b6-55ab27f3aa09.png)

**Comment by CyrilleB79** [comment]
Since #13752 has been closed would it be worth closing this issue too, just assuming it is the way some sliders are implemented in Windows?

Note: I can think of an explanation why they have coded the home/end behaviour this way; I do not know if it is the real reason of this implementation however.
On a desktop keyboard, logically, pgUp increases the value and pgDown decreases it. Since the home and end key are next to these key, maybe the idea was to take advantage of the position of these keys, i.e. to use the upper key (the home) to go to the highest value similarly and and to use the lower key (the end key) to go to the lowest value.
Of course on a laptop keyboard where these keys often migrate at any position, this does not make sense anymore.

**Comment by feerrenrut** [comment]
Yes, I think perhaps we should close this. Given that it affects the Windows controls when NVDA is not running, it doesn't seem like something this project has any control over. Interfering with it would cause a change in behavior only when NVDA is running, which would also be confusing.
