### ISSUE TITLE
hearthstone stop reading speech when using nvda in microsoft speech api5

### ISSUE THREAD

**Issue by wightfall** [nvaccess/nvda#13259]
### Steps to reproduce:
launching hearthstone access mod then run hearthstone.
### Actual behavior:
in my thai language when remove period from the mod file nvda stop reading message after first sentence.
here is the log file:
I 17:30:27.5985781 Pressed key: C
I 17:30:30.1050786 Output to screen reader (success=True): คอลเลกชันของฉัน
I 17:30:30.1323328 Output to screen reader (success=True): เรียกดูคอลเลกชั่น 1 จาก 4
I 17:30:34.0150778 Pressed key: DownArrow
I 17:30:34.0150778 Output to screen reader (success=True): เด็คของฉัน 2 จาก 4
I 17:30:35.2868807 Pressed key: UpArrow
I 17:30:35.2868807 Output to screen reader (success=True): เรียกดูคอลเลกชั่น 1 จาก 4
### Expected behavior:
it shouldn't be stop reading even no period include or if replace with other symbol like space,  ?. if no any symbol or punctuatlion end of file nvda must read next sentence.
#### NVDA installed/portable/running from source:
install
#### NVDA version:
Version: 2021.3.1
#### Windows version:
window 10 Version 21H2 (OS Build 19044.1469)
#### Name and version of other software in use when reproducing the issue:
hearthstone version 22.0.2.128654 and hearthstone access version 20.
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
this application doesn't need extra add on, still golden cursor may help in gameplay but not related to this period problem.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes this issue still occur.

**Comment by Adriani90** [comment]
@mohamedSulaimanAlmarzooqi, @wightfall are you still having this issue in NVDA 2023.1 or NVDA last alpha version?

You can download and test with last alpha version at this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by mohamedSulaimanAlmarzooqi** [comment]
I actually did a thumbsdown because I don't think this is an NVDA related issue, Could be anything from the game's accessibility mod, But I could be wrong.

**Comment by seanbudd** [comment]
If this is still an issue - please let us know.

We are unable to process this issue as it stands.

Please reproduce this issue and provide a full [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.
This is very likely a problem with the implementation of the application/website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers
