### ISSUE TITLE
Math is read with unnaturally long pauses

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#13289]
### Steps to reproduce:

1. Go to [this page](https://rafalab.github.io/dsbook/probability.html#conditional-probabilities)
2. Read the first equation in section 14.4 Conditional probabilities

### Actual behavior:

The terms of the equation are read with unnaturally long pauses, which makes reading longer expressions incredibly slow.

```
clickable    Pr 
<pause>
times  
<pause>
open paren   
<pause>
Card 2 is a king  
<pause>
divides 
<pause>
Card 1 is a king 
<pause>
close paren   
<pause>
equals 3 
<shorter pause>
divided by   51 
```

### Expected behavior:

In the past, these pauses were not present while reading math. I would like that behaviour to be restored, or at least for these incredibly long pauses to be shortened.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-24450,49168d54

#### Windows version:
Windows 10.0.19044 x64

#### Name and version of other software in use when reproducing the issue:
Firefox 97.0b9 x64

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by antonshusharin** [comment]
Any updates? This is a serious regression for MathML users.

**Comment by Adriani90** [comment]
cc: @NSoiffer
is this now better with NVDA 2024.4.1? @Neurrone which add-pon are you using to read math with?
