### ISSUE TITLE
input type="file", not reading chosen file, after file change

### ISSUE THREAD

**Issue by praveeno** [nvaccess/nvda#13303]
### Steps to reproduce:
https://thepaciellogroup.github.io/AT-browser-tests/test-files/input-file-upload.html
when change input select file, not reading changed file name

### Actual behavior:
when change input select file, not reading changed file name

### Expected behavior:
new filename is chosen should be read
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2021.3.1
#### Windows version:
windows 10
#### Name and version of other software in use when reproducing the issue:
WIndows Chrome Version 97.0.4692.99 (Official Build) (64-bit)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
No addons, today latest installation
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not sure on this

**Comment by Adriani90** [comment]
This is fixed in Chromium canary 133 with NVDA 2024.4.1. Closing as works for me.
