### ISSUE TITLE
Problems with Elements List in Word 365 with UIA Enabled

### ISSUE THREAD

**Issue by msviolafangirl** [nvaccess/nvda#13368]
### Steps to reproduce:
1. Open a word file that contains comments.
2. Make sure UIA support for word is enabled in NVDA advanced settings.
3. While in browse mode, press NVDA+F7 to access elements list and then press Alt+A for annotations.
4. Check list of annotations. You won't find any.
5. Turn UIA off. Check list of annotations again. The comments will appear.

### Actual behavior:
When viewing a list of annotations in elements list, nothing shows up. Links list works but the other lists, like headings and annotations, I see nothing even if I can browse through headings and annotations using h and a respectively in browse mode.

### Expected behavior:
I should be able to use the elements list to view a list of headings and comments in word.

#### NVDA version:
2021.3.1

#### Windows version:
Windows 10 21H2

#### Name and version of other software in use when reproducing the issue:
Word 365

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by seanbudd** [comment]
This will be fixed in 2022.1, and is currently fixed on alpha.
