### ISSUE TITLE
Strange behavior when switching GitHub comment editor from write to view in Chromium browsers

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#13360]
This appears to be an unknown COM error.

### Steps to reproduce:

In a Chromium based browser (I used Brave), go to anywhere on GitHub where you might enter a comment. Ex: a new issue.
In browse mode, and move up to the two tabs called "write" and "preview".
Select "preview".

### Actual behavior:

NVDA will stop speaking while using the up/down arrow keys, to try to review the comment.
Using left/right arrows will resume speech, but sometimes:
* You will still be in the write tab, as if "preview" hadn't been selected; or
* Instead of pressing left/right, you can use alt then escape, or alt+tab twice, after which you will be in the browser, and *might* be viewing the preview.

### Expected behavior:

NVDA reads normally and immediately once you have switched to preview. This is what happens in Firefox.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

A couple of recent alphas, including
alpha-24718,ba11e8a6

#### Windows version:

21H1 (OS Build 19043.1526)

#### Name and version of other software in use when reproducing the issue:

Brave Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit)

#### Does the issue still occur after restarting your computer?

Yes

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

### Log

I have included comments in brackets, indented by one tab. Search for "First indication of problem" for the actual error.
[COMError when switching GitHub comment tabs.txt](https://github.com/nvaccess/nvda/files/8093459/COMError.when.switching.GitHub.comment.tabs.txt)

Com error:
``` 
IO - speech.speech.speak (19:33:49.805) - MainThread (17456):
Speaking ['tab', 'Write', 'tab', 'selected', 'Preview']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2States (19:33:49.809) - MainThread (17456):
could not get IAccessible2 states
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1760, in _get_IA2States
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (19:33:49.810) - MainThread (17456):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
```

**Comment by Adriani90** [comment]
@XLTechie can you still reproduce this issue in last NVDA alpha?

**Comment by Adriani90** [comment]
We didn't get any updates from @XLTechie upon request since more than 2 years, I am closing as abandoned. If you are still having this issue, please comment and we can reopen.

**Comment by XLTechie** [comment]
@CyrilleB79, @Adriani90.   My apologies, I missed the requests for update on this one. This can no longer be reproduced as of July, 2024.
