### ISSUE TITLE
When clicking no on the restart dialog, focus is stolen from the foreground window

### ISSUE THREAD

**Issue by TheQuinbox** [nvaccess/nvda#13385]
### Steps to reproduce:
1. Install an NVDA addon.
2. Click no on the restart dialog.
### Actual behavior:
A window called NVDA is focused, taking focus away from whatever the user was focused on previously. Pressing Alt f4 on this window will attempt to exit NVDA, and alt+tabbing away makes it die.
### Expected behavior:
If I click no, the dialog should close like any other dialog.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.3.3
#### Windows version:
Windows 10 (64-bit).
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2021.3.1 also has this behavior
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by josephsl** [comment]
Hi, if you don’t mind, can you try testing with latest alpha build (24771) and see if that makes any difference? You may use any of my add-ons such as Resource Monitor to test the issue described as it should pose no problems in alpha builds. Thanks.

**Comment by TheQuinbox** [comment]
@josephsl, that fixed it, thanks!
