### ISSUE TITLE
nvda can't find all titles on a webpage 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#13389]
### Steps to reproduce:
open the page
https://blogs.windows.com/windows-insider/
press ctrl + home.
now navigate by pressing the letter h through the headers.
See that nvda announces only 2 headers.
Now press ctrl + end
Navigate through the headers returning with shift + h, see that now nvda finds several other headers that were not reported. 
### Actual behavior:
if you are at the top of the page and browse headers nvda does not inform you that there are multiple headers. 
### Expected behavior:
navigating from top of page
by the headers nvda should find all the headers. 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-24809,2583f8fe

#### Windows version:
11 22000.527
#### Name and version of other software in use when reproducing the issue:
chrome.exe, Google Chrome 100.0.4892.0

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
log:
[loop.txt](https://github.com/nvaccess/nvda/files/8133485/loop.txt)

**Comment by Qchristensen** [comment]
I just tried with NVDA 2021.3.3 installed, and then a temporary copy of NVDA alpha-24809,2583f8fe and it seems to be reading fine here in both
Firefox version: 97.0.1 
and 
Chrome Version: 98.0.4758.102 
on Windows 10 (64-bit) Version: 21H2 (2009), Build: 19044.1526 

The first three links are:
- the Introducing Android Apps on Windows 11 Heading level 2
- Latest News heading level 1
- Announcing Windows 11 Insider preview build ... heading level 3

**Comment by zahra21** [comment]
hi. did you test with nvda and firefox?
i tested with firefox 102 and nvda 2022.1 and did not reproduce it.

**Comment by fernando-jose-silva** [comment]
thank you very much, we can close this call, I no longer have this problem.
