### ISSUE TITLE
Recent alpha versions crash Notepad++ versions 8.2.x and below

### ISSUE THREAD

**Issue by mltony** [nvaccess/nvda#13397]
### Steps to reproduce:
1. Use NVDA alpha version nvda_snapshot_alpha-24771,a1a6598b.exe or above.
2. Open Notepad++ v8.1.x or v8.2.x 64-bit.
3.Press up/down a few times.

### Actual behavior:
Notepad++ crashes. No error message is printed in NVDA log.
### Expected behavior:
Notepad++ should not crash.
#### NVDA installed/portable/running from source:
Portable alpha nvda_snapshot_alpha-24771,a1a6598b.exe
#### NVDA version:
nvda_snapshot_alpha-24771,a1a6598b.exe

#### Windows version:
Reproduced on both Windows 10 and 11 64-bit.
#### Name and version of other software in use when reproducing the issue:
Reproduced using either of these two versions (64-bit in both cases):
- Notepad++ v8.1.9.3: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.1.9.3/npp.8.1.9.3.portable.x64.zip
- Notepad++ v8.2.1: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.2.1/npp.8.2.1.portable.x64.zip
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Identified that commit a1a6598b19f71bd108bef64373dd35c89c14cd4a is causing this, therefore cc: @lukaszgo1.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by josephsl** [comment]
Hi, confirmed, and a potential solution is in the works (#13382). Thanks.
