### ISSUE TITLE
On the fly speech adjustments should allow the command plus home/end to immediately set the adjustment to the first or last value in the list 

### ISSUE THREAD

**Issue by tangela19** [nvaccess/nvda#13395]
### Is your feature request related to a problem? Please describe.
Adjusting speech on the fly could be faster. 

### Describe the solution you'd like.
The nvda command plus home and end should jump to the first or last value in a list. Example. When setting the speech rate in laptop keyboard layout, `nvda+shift+control+home` should set the value to 100%, while `ctrl+shift+nvda+end` would set it to 0%. 

### Describe alternatives you've considered.
Add this to a user-mappable keystroke

**Comment by Qchristensen** [comment]
What is your use case for this?  While using the current keystroke to move 5% at a time could mean pressing it up to 20 times to get from 0% to 100% - how often do you actually need to do that?

While your proposed keystrokes are logical and not currently used elsewhere, my concern is that a single inadvertent keystroke could suddenly render NVDA unintelligible for a user who didn't realise what they had pressed.

**Comment by tangela19** [comment]
I use the acapela voices often with nvda. Every time you switch to that
synth from another, or switch voices within that synth, they start at their
default (very slow) speech rate and you have to manually adjust them. While
it is true that an inadvertent keystroke might set nvda's speech rate to be
unintelligible, the fact that it requires four keys pressed simultaneously
should hopefully cut down on the instances of doing so accidentally.

You could also set the ability to do this user side, but leave the
keystroke unassigned so that only those users who wanted to could bind it
to a keystroke.

Tangela

**Comment by seanbudd** [comment]
Would it be preferred that voices remember their speech rate?

**Comment by zahra21** [comment]
hi. today, i tested this with nvda 2018.1 and it worked for me with espeak. i dont know about other synthesizers.

**Comment by seanbudd** [comment]
We think that there is no current need to jump from start to end, and that the maximum of 20 presses to jump from end-to-end is reasonable.
We agree that it is frustrating that changing the voice changes the speech rate.

Closing this issue, instead a new issue should be opened so that voices can remember their speech rate.
