### ISSUE TITLE
Unlock the mouse button when exiting NVDA

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#13410]
This feature request comes from a [discussion](https://groups.io/g/nvda-fr/topic/deverouillage_du_clique/89379366?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,89379366,previd=1646158884655339753,nextid=1641406144833584516&previd=1646158884655339753&nextid=1641406144833584516) on a French mailing list.

### Is your feature request related to a problem? Please describe.

The user has accidentally locked one of the mouse button with shift+PavNum*without realizing it while working in Windows Explorer. Then he noticed unexpected behaviors such as arrow keys not working or not reporting anything when trying to navigate in Windows Explorer.

He has tried to restart NVDA but this did not solve the issue. Thus he was thinking to a Windows issue.

### Describe the solution you'd like

The user suggests the following solution:
When exiting NVDA with insert +q, NVDA should unlock the mouse buttons if the button was originally locked by an NVDA command.

### Describe alternatives you've considered

The real issue is that a screenreader user may forget that he has locked a mouse button with a screenreader command. On the contrary, a mouse user does not forget to release the pressure on the mouse button when needed.

Other solutions to this issue can be thought. For example a sound notification each 10 seconds to record the user that a button should be unlocked.

### Additional context
None

**Comment by XLTechie** [comment]
Another option would be a periodic announcement or beep indicating mouse button 
lock. Optional, of course.

**Comment by seanbudd** [comment]
@XLTechie - this would make a good feature request in a separate issue

**Comment by mwhapples** [comment]
I have made a pull request which fixes this. The only thing I was unsure about is whether the unlocking should be announced or should happen silently.

**Comment by XLTechie** [comment]
> I have made a pull request which fixes this. The only thing I was unsure about is whether the unlocking should be announced or should happen silently.

Announced, if possible. "Unlocking left mouse button.", "Unlocking right mouse 
button".

**Comment by mwhapples** [comment]
I have updated the pull request so that unlocking is announced.

**Comment by CyrilleB79** [comment]
@seanbudd this issue has been fixed by the merge of #13529.
Thus it should be closed and added to milestone 2022.2.

I could close this issue but not add the milestone 2022.2.

**Comment by CyrilleB79** [comment]
If you read the initial description and the following discussion, you can see that this issue focused on releasing mouse buttons when NVDA exits. I can change the title for clarity if you want, e.g.: A way to avoid forgetting a locked mouse button when exiting NVDA.

On the contrary, #13446 focuses on a feature reminding regularly that a mouse button is down.

If you consider that something in this issue is not fixed by #13529, nor covered by #13446, please be more specific. Thanks.

**Comment by seanbudd** [comment]
@CyrilleB79 - I agree, but I think this issue title is misleading. I'm going to change it, add the milestone, and close.
Feel free to re-edit the title further.

**Comment by seanbudd** [comment]
Closed by https://github.com/nvaccess/nvda/pull/13529
