### ISSUE TITLE
NVDA says "Task switching" when switching between applications in Windows 11

### ISSUE THREAD

**Issue by ivnc** [nvaccess/nvda#13425]
Reported by a Spanish-speaking user. Reproduction not attempted here.

### Steps to reproduce:

Press alt+tab, and hold alt, to switch between windows/applications.

### Actual behavior:

Before each window title, NVDA starts saying or says "Task switching" ("Conmutación de tareas").
IO - inputCore.InputManager.executeGesture (15:05:29.118) - winInputHook (10668):
Input: kb(laptop):alt+tab
IO - speech.speech.speak (15:05:29.181) - MainThread (5260):
Speaking ['Conmutación de tareas', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:05:29.221) - MainThread (5260):
Speaking ['La Sala de Juegos [(xxx)]', 'fila 1', 'columna 1', '1 de 2', CancellableSpeech (still valid)]
DEBUGWARNING - IAccessibleHandler.internalWinEventHandler._shouldGetEvents (15:05:29.734) - MainThread (5260):
Foreground took too long to change. Foreground still 131982 (wxWindowNR). Should be 393430 (WorkerW)
IO - speech.speech.speak (15:05:29.781) - MainThread (5260):
Speaking ['La Sala de Juegos [(xxx)]', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:05:29.813) - MainThread (5260):
Speaking ['Menú', 'lista', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:05:29.817) - MainThread (5260):
Speaking ['Tirar 6 dados', CancellableSpeech (still valid)]

### Expected behavior:

NVDA should only say window title.

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
2021.3.3.

#### Windows version:
Windows 11 21H2 (x64) build 22000.527.
Not reproducible in Windows 10.

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, same behavior.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested.

**Comment by mwhapples** [comment]
I have observed similar to this, but have not determined a way to tell when it will occur.

**Comment by josephsl** [comment]
Hi,

I wonder if fixing #13506 would resolve this as a side effect?

Thanks.

**Comment by josephsl** [comment]
Hi,

Is this still the case in February 2023 with NVDA 2022.4/2023.1 beta 1?

Thanks.

**Comment by ivnc** [comment]
No, the user says this is no longer happening. Thanks.
