### ISSUE TITLE
Braille in Vs Code is erratic and difficult to rely on

### ISSUE THREAD

**Issue by zersiax** [nvaccess/nvda#13423]
### Context & Explanation
I am going to step away from the traditional template here for just a bit, as the reproduction of some or all of these glitches is hard to specifically quantify. They are things you notice, particularly when working with somewhat longer lines of code, and make braille a third-class citizzen at best in the VS Code editor and, I assume, other Electron-based applications:

- Moving character by character across a line will at times make braille jump, only show indentation , only show part of the indentation or not show any of the indentation at all.
- Moving up and down between lines in VS Code tries to preserve the column you are at, even if there's a blank line in between. This does mean that if you land in the middle of the line, it can be difficult to figure out the line's indentation in braille due to the issue outlined above.
- Cursor routing can at times freeze NVDA for several seconds; I have the feeling this happens if one clicks a character that is past a certain line length but have not been able to precisely pin this down.
- A lot of messages VS Code emits are not brailled but only spoken due to the way ARIA alerts are handled in NVDA. This has been reported as #9352 and #7756 as early as 2017 but is still a problem today.

All this together makes braille within VS Code far less useful than it could be, and I honestly wouldn't want to be a user who relies on braille as their primary modality when using the program with NVDA, as I feel this would be a severe productivity killer.
- ### System configuration
#### Other information about your system:
These tests were performed using a Mantis q40 40-cell braille display.

#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by zersiax** [comment]
I will add that disabling "Avoid splitting words when possible" mittigates the first issue somewhat.

**Comment by seanbudd** [comment]
To also consider in this meta-issue #12179

**Comment by seanbudd** [comment]
Would you be able to create new issues to capture each of these bugs you have mentioned?

**Comment by bramd** [comment]
@zersiax I also recognize the routing performance issues. I don't think it is just line length. I almost never have it while editing "normal" code files, which I admittedly don't do as often as I used to, but I recently had it very dramatically while editing a large (as in multiple pages) Markdown document. So, it seems number of lines in the document matter as well. This Markdown file was hard wrapped at 80 columns, so didn't contain very long lines. Please mention me if you open new, separate issues for the problems in this issue.

**Comment by Adriani90** [comment]
Live regions and allerts are now shown in Braille as well, you have to enable the braille live region reporting in NVDA advanced settings in case it is disabled on your end.

@zersiax how is the current status now with NvDA 2024.4 Beta? Do you still see some of your issues? I think freezing should not happen now, or at least it should be much better than before since there were many improvements in NVDA and system caret movements.

The indentation issue might still occur though.

**Comment by Adriani90** [comment]
Maybe @burmancomp or @Emil-18 you can report as well your results on this issue? That would be helpful.
