### ISSUE TITLE
NVDA don't read content of dialog box in Qt based applications if object description is disabled

### ISSUE THREAD

**Issue by CoBC** [nvaccess/nvda#13442]
### Steps to reproduce:
- Disable object description in object presentation settings
- Open a Qt based application (tried with TeamTalk)

### Actual behavior:
- When a dialog box is open (for example in TeamTalk you are kicked from channel), NVDA only read the dialog title and the button which get focus

### Expected behavior:
- NVDA should read content of dialog

#### NVDA installed/portable/running from source:
- Installed

#### NVDA version:
- alpha-24876,2325be89

#### Windows version:
- Windows 11 10.0.22000.527

#### Name and version of other software in use when reproducing the issue:
- Any Qt application (for example TeamTalk (Qt version) V5.9.0.5076 (latest beta))

#### Does the issue still occur after restarting your computer?
- Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
- Same with 2021.3.3

#### If NVDA add-ons are disabled, is your problem still occurring?
- Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
- Yes

**Comment by leonardder** [comment]
I don't think this is actually a bug. It also works like this within NVDA itself, e.g. when selecting the advanced settings category in NVDA"s settings. It also works this way in generic Windows popups, e.g. the one shown when executing `winver` from a run prompt.

The user guide reads:

> Uncheck this checkbox if you don't wish to have the description reported along with objects (i.e. search suggestions, reporting of whole dialog window right after the dialog opens, etc.).

Closing this issue.
