### ISSUE TITLE
Strange behavior regarding reporting of font related attributes in MS Word

### ISSUE THREAD

**Issue by LittleStar-VIP** [nvaccess/nvda#13459]
Note:
I just discovered that this is not a specific problem related to reporting of font color as what I have first reported in #13458 

### Steps to reproduce:
1. open document setting of nvda
2. check some of the items that are related to the styles and attributes of fonts, e.g. color, text-alignment, etc.
3. open a word file, probably with a table 
4. in some of the places, edit cursor moving from one place to another, nvda will still report the font style or attribute, as if there is a change in the style or attribute

For example:
1. press ctrl and end jump to end of document,
2. press nvda and f, nvda report that there is no format information
3. press up arrow 
4. nvda will report font style and attributes based on what I have selected in the document setting, e.g. in my situation, it report "black, background color is white, left aligned"

The above problem can also be found when inside a table cell and press end, which move the cursor to the end of that cell,
or when moving from one table cell to another table cell

### Expected behavior:
As what I have checked , end of the document, end of the table cell, nvda will report that the cursor position has no styling information, so nvda should ignore this when checking for style or attribute changes

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
nvda2021.3.3
#### Windows version:
Windows 10 Home 21H1
#### Name and version of other software in use when reproducing the issue:
MS Word 365 installed version
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not tried.
#### If NVDA add-ons are disabled, is your problem still occurring?
Not tried.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tried.

**Comment by CyrilleB79** [comment]
I have done some tests arrowing from a cell containing normal text to an empty cell. It results that the following formatting information is unduly reported:
* Font name
* Font size
* Font attribute
* Font superscript/subscript
* Font style
* Font color
* Paragraph alignment

**Comment by CyrilleB79** [comment]
Please change milestone to 2022.1 instead of 2022.2.

PS: Just let me know if such comments are useless. E.g. if your process already takes care to modify the milestone later when closing issues fixed by a merge in beta branch.
