### ISSUE TITLE
Under document setting, allow table column and row header to be set individually 

### ISSUE THREAD

**Issue by LittleStar-VIP** [nvaccess/nvda#13455]
### Is your feature request related to a problem? Please describe.
When reading some tables in word or web page that is not properly designed, or some tables are intended not to have column or row header, some irrelevant information may be treated as header.
However, currently, if I do not want specific header to be spoken by nvda, I can only choose to turn off the reporting of column and row header totally.

### Describe the solution you'd like
break down the current setting and allow two separate options,
1. check if report column header
2. chegck if report row header

**Comment by michaelDCurran** [comment]
Superseded by issue #14075  
and fixed in pr #14132
