### ISSUE TITLE
Nvda is very lag when several options in the document setting page is enabled when editing a word with lots of pages

### ISSUE THREAD

**Issue by LittleStar-VIP** [nvaccess/nvda#13464]
### Steps to reproduce:
1. open nvda document setting, enable some of the options, e.g. enable the reporting of text alignment, font color etc
2. open a word file that contain lots of text andpages, the one that I am experiencing the problem is a word file that contain 4xx pages and 1151325 words 
3. use control and up or down arrow to read paragraph by paragraph
4. nvda will lag or even freeze for several minutes if the focus is jump to a relatively long paragraph

I have tried unchecking everything that I have enabled at the very begining in the document setting, and the lag or freeze problem is not observed

### Expected behavior:
nvda will not lag or freeze
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
nvda 2021.3.3
#### Windows version:
Windows 10 home 21h1
#### Name and version of other software in use when reproducing the issue:
Microsoft Word 365 installed version
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not tried.
#### If NVDA add-ons are disabled, is your problem still occurring?
Not tried.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tried

**Comment by XLTechie** [comment]
Is this maybe a duplicate or co-issue to #13461?

**Comment by LittleStar-VIP** [comment]
> Is this maybe a duplicate or co-issue to #13461?
> 
Hi Luke
This issue here do exist regardless of whether or not UIA support is enabled

**Comment by LittleStar-VIP** [comment]
Hello,
That file I was editing, is a text-only file, without any images.

**Comment by Adriani90** [comment]
the biggest impact on performance in this  case is the setting "reporting of pages" in NVDA settings, as we found out in #2296. I am closing this issue in favor of that one. Apart from that the performance has got far better meanwhile, but it still needs to be improved.
