### ISSUE TITLE
Clean build is broken in recent master

### ISSUE THREAD

**Issue by mltony** [nvaccess/nvda#13468]
### Description
I followed all the steps on building NVDA, but I am running into an error.
I tracked it down to commit 2583f8fee71b9083f79346e1dfd73a016deb2f28 - that is before this commit build seems to work fine.
### Steps to reproduce:
I have Visual Studio Community edition 2019 installed. Then I run:
```
> git clone --recursive https://github.com/nvaccess/nvda.git
> cd nvda
> scons source
```

### Actual behavior:
Here are lines from the output that appear to be relevant:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(131,5): warning : Unable to find version '1.0.191107.2' of package 'Microsoft.Windows.ImplementationLibrary'. [H:\nvaccess\nvda2\include\microsoft-ui-uiautomation\src\uiAutomation\UIAutomation.sln]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(131,5): warning :  [H:\nvaccess\nvda2\include\microsoft-ui-uiautomation\src\uiAutomation\UIAutomation.sln]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(131,5): warning : Unable to find version '2.0.200703.9' of package 'Microsoft.Windows.CppWinRT'. [H:\nvaccess\nvda2\include\microsoft-ui-uiautomation\src\uiAutomation\UIAutomation.sln]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(131,5): warning :  [H:\nvaccess\nvda2\include\microsoft-ui-uiautomation\src\uiAutomation\UIAutomation.sln]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(131,5): warning : Unable to find version '2.0.200703.9' of package 'Microsoft.Windows.CppWinRT'. [H:\nvaccess\nvda2\include\microsoft-ui-uiautomation\src\uiAutomation\UIAutomation.sln]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(131,5): warning :  [H:\nvaccess\nvda2\include\microsoft-ui-uiautomation\src\uiAutomation\UIAutomation.sln]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(131,5): warning : Unable to find version '1.0.191107.2' of package 'Microsoft.Windows.ImplementationLibrary'. [H:\nvaccess\nvda2\include\microsoft-ui-uiautomation\src\uiAutomation\UIAutomation.sln]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(131,5): warning :  [H:\nvaccess\nvda2\include\microsoft-ui-uiautomation\src\uiAutomation\UIAutomation.sln]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(131,5): error MSB4181: The "RestoreTask" task returned false but did not log an error. [H:\nvaccess\nvda2\include\microsoft-ui-uiautomation\src\uiAutomation\UIAutomation.sln]
4 Warning(s)
1 Error(s)
scons: *** [build\x86\microsoft-ui-uiautomation\lib\Microsoft.UI.UIAutomation.dll] Error 1
scons: building terminated because of errors.
```
I attach full build log:
[output.txt](https://github.com/nvaccess/nvda/files/8238602/output.txt)
### Expected behavior:
Build should work.
#### NVDA installed/portable/running from source:
Source
#### NVDA version:
master
#### Windows version:
Windows 11
#### Name and version of other software in use when reproducing the issue:
Visual Studio Community Edition 2019.
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Build works on commit 3b088196a841b7c76fc47bfbc47b55fa9ea5ec21 and before. Commit 2583f8fee71b9083f79346e1dfd73a016deb2f28 seems to break build for me.
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
n/a

**Comment by mltony** [comment]
cc:  @michaelDCurran, @lukaszgo1

**Comment by lukaszgo1** [comment]
Can't reproduce here. Just to rule out the obvious stuff:
- Are you connected to the internet?
- Is the machine behind some kind of proxy which may block download of packages from the NuGet repositories?
- - Perhaps you have some custom config for NuGet which specifies different url for packages?

**Comment by mltony** [comment]
Good Internet connection, no proxy of any kind. 
How can I check NuGet configuration? I didn't change it manually, but my suspicion is that I previously had VS 2022 installed (NVDA readme was saying at the time that build works fine with 2022), but I uninstalled 2022 since then and installed 2019, so maybe this somehow screwed up my nuget configuration...

**Comment by lukaszgo1** [comment]
From your log it seems the config is at `      C:\Users\tony\AppData\Roaming\NuGet\NuGet.Config`. 
I'm not familiar enough with NuGet to say if it would be recreated automatically if missing, but creating a backup, deleting it and attempting to build NVDA probably wouldn't hurt.

**Comment by mltony** [comment]
You're right,  it was indeed configuration  problem as my nuget sources list was empty. Just in case anyone else is running into this here is what I've done to fix this:
1. In Visual Studio 2019 Go to Tools > Nuget > Package Manager Settings
2. In the tree view navigate to Package sources.
3. If the list is empty add default Nuget package source: https://api.nuget.org/v3/index.json
