### ISSUE TITLE
development guide: adding descriptions for Problem with generating pot file for the add-on

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#13467]
### Is your feature request related to a problem? Please describe.

1. type **scons pot** (To generate a gettext translation template (for translators)

error message: 

Generating pot file nvda-markdownForever.pot                                                                                 

scons: *** [nvda-markdownForever.pot] Error 1                                                                                

scons: building terminated because of errors.                                                                           

### Describe the solution you'd like

> Fawaz Abdul rahman
2021年8月16日 凌晨2:31 
What you have to do is:
1. download Gettext like v0.21, from the following github: 
vslavik/gettext-tools-windows at v0.21-1 
2. extract it somewhere, then set the path before running scons pot. 
set path=partition:\gettext-tools-windows-0.21-1\bin;%path% 
of course change it depending on the path you are going to extract in. 
After that, scons pot should work as expected. 

reference:

https://nvda-addons.groups.io/g/nvda-addons/message/16695

**Comment by lukaszgo1** [comment]
`scons pot` is an add-on template command not NVDA's. @surfer0627 Please report this against add-on template. IMO this should be closed as won't fix for NVDA.

**Comment by josephsl** [comment]
Hi, I think this is more towards an add-on dev guide issue. You can “get around this” by using Windows Subsystem for Linux (WSL) and install Gettext via whatever package manager the distribution comes with. I expect this will impact anyone who uses Windows (Command Prompt, PowerShell, Terminal, etc.) to build add-on pot files. Thanks.

**Comment by lukaszgo1** [comment]
Looking at the add-on development guide the fact that you need to have gettext either in your path or in the add-on folder is mentioned so I'm not sure if this can be clarified any further.
