### ISSUE TITLE
HID Braille: When waking the PC from sleep, Braille display sometimes doesn't reconnect

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#13485]
When using a Mantis Q40 and enabling the HID Braille setting, sometimes after waking the computer from sleep, the keyboard reconnects, but Braille remains dormant until re-choosing the Automatic setting from NVDA's Braille Settings dialog. This is similar to #9830 where something similar could be observed with Focus Blue displays.

### Steps to reproduce:

1. Connect a Mantis Q40 by:
   * Going into NVDA's Advanced Settings, and setting the "Use HID Braille" option to "Yes".
   * Connecting a Mantis.
2. Let the computer go to sleep, and try to wake it later.

### Actual behavior:

Sometimes, not always, the Mantis keyboard wakes up the machine, but the Braille display doesn't resume working. Just reconnecting to the USB connection from the Mantis doesn't work, I have to go into NVDA's Braille Setting, hit Enter on the Current Display and choose the currently selected item again. After a short moment, Braille then resumes.

### Expected behavior:

Braille always resumes when waking up the computer.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

NVDA version alpha-24951,e86e37f6

#### Windows version:

11.0

#### Name and version of other software in use when reproducing the issue:

N/A.

#### Other information about your system:

Braille display connected via USB.

#### Does the issue still occur after restarting your computer?

No, after restarting the computer, the display is always detected. it is only a problem after sleep/hibernation/power saving mode.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

N/A.

**Comment by Adriani90** [comment]
#7736 might also be related to this.

**Comment by Adriani90** [comment]
@MarcoZehe can you still reproduce this issue with NVDA 2024.1?

**Comment by MarcoZehe** [comment]
I am afraid I currently no longer use Windows, so am not setup to try.

**Comment by seanbudd** [comment]
To be able to process this issue we need a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences and hwIO logging enabled in advanced preferences.

**Comment by Adriani90** [comment]
cc: @Emil-18, @burmancomp, @FelixGruetzmacher, @LeonarddeR could anyone test if this is still an issue with NVDA 2024.1?

**Comment by seanbudd** [comment]
Closing this unless it can be reproduced with a log file
