### ISSUE TITLE
TPlusMemo class and issues with text reading

### ISSUE THREAD

**Issue by JanuszChmiel** [nvaccess/nvda#13484]
### Steps to reproduce:
1. download and install Balabolka application from
http://www.cross-plus-a.com/balabolka.zip
2. 
### Actual behavior:
When editable field contain more than one line of text, NVDA pronounces empty line if user press arrow keys with less than 1 or 2 Seconds delay. 
### Expected behavior:
NVDA should read content of Balabolka editable field with The textual content with text immediately. No matter on time delay between arrow keys presses. .

#### NVDA installed/portable/running from source:
NVDA is installed
#### NVDA version:
2021.3.3

#### Windows version:
Windows 11 Home
Version	21H2
Operating system build	22000.556

#### Name and version of other software in use when reproducing the issue:
Balabolka version 2.15.0.812
Skype version 8.80.0.194

#### Other information about your system:
Lenovo IdeaPad S540-14IML
SSD disk connected to mother board by using Intel rapid storage technology, 128 GB
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I did not test
#### If NVDA add-ons are disabled, is your problem still occurring?
I have no NVDA addons installed. And my problem is still occurring.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by Adriani90** [comment]
@JanuszChmiel are you still having this issue? If yes, this might probably get fixed by #14708.

**Comment by Adriani90** [comment]
Note this is not reproducible in Skype 94. So it might be specific to balabolka software.

**Comment by Adriani90** [comment]
We didn't hear any update from the initial author since more than 2 years upon request, I am closing as abandoned. if you are still having this issue, please comment and we can reopen.
