### ISSUE TITLE
NVDA should announce the number of visible columns and rows in a data grid when the value of aria-rowcount or aria-colcount is different from the number of rows and columns available in the accessibility tree

### ISSUE THREAD

**Issue by rperez030** [nvaccess/nvda#13504]
I consider this an issue because NVDA fails to inform users about dynamic changes in the number of rows and columns available in a grid which may lead to confusion, but it can also be seen as an enhancement.
## Steps to reproduce:

1. Navigate to the [data grid examples in the ARIA authoring practices page](https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/dataGrids.html) and locate the heading level 3 for third example (Example 3: Scrollable Data Grid With Column Hiding).
2. Make sure that browse mode is on, and press T to navigate to the grid containing transactions. Take note of the number of columns and rows announced by NVDA (16 rows and 6 columns).
3. Press Up arrow to focus the button with the label "Hide Type and Category", and press Enter or the space bar to activate this button. The label will change to "Show Type and Category".
4. Press T again to set NVDA focus to the data grid and take note of the number of rows and columns announced (16 rows and 6 columns).

### Actual behavior:
NVDA announces the total number of rows and columns indicated by aria-rowcount and aria-colcount independently of the columns and rows currently available to the user.
### Expected behavior:
When the type and category columns are hidden, this should be reflected by NVDA in the announcement of rows and columns. This announcement should also reflect the fact that just 6 out of the 15 rows are available. For example, when the type and category columns are hidden, the announcement could be something like: "Table  with 6 out of 16 rows and 4 out of 6 columns". 
#### NVDA installed/portable/running from source:
not applicable.
#### NVDA version:
2021.3.3
#### Windows version:
Windows 11 build 22000.556
#### Name and version of other software in use when reproducing the issue:
Microsoft edge version 99.0.1150.39
#### Other information about your system:
Not applicable
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not applicable.
#### If NVDA add-ons are disabled, is your problem still occurring?
Not applicable
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not applicable

**Comment by XLTechie** [comment]
> something like: "Table with 6 out of 16 rows and 4 out of 6 columns".

May I suggest:
"Table showing 6 out of 16 rows and 4 out of 6 columns"

Or, slightly more succinct:
"Table showing 6 of 16 rows and 4 of 6 columns"

**Comment by rperez030** [comment]
In the future, we may also want to consider exploring ways to notify the user about the visible range based on aria-colindex and aria-rowindex. It may be beneficial in more complex applications.

**Comment by michaelDCurran** [comment]
To be clear, this is a feature request, not a bug.
I also totally disagree with that example. If those columns have been hidden, then the table should report as if those columns were not there. I.e. column count should be like those columns never existed, similarly the column number of subsequent columns should also be such that the hidden columns never existed. 
In Other words, probably no actual reason for the ARIA table attributes in this example at all, as the physical table coordinates are what the user should have reported to them.
In regards to actually reporting x of y columns etc, either new ARIA attributes would be required to provide  both the visible and total number to the AT, or the AT would have to calculate this themselves which for large tables would be extremely costly.
If you disagree with this opinion, please point me to very clear documentation from the ARIA spec that outlines the expectations for ATs for this example.
