### ISSUE TITLE
Calling UIA custom pattern in some malformed Outlook messages causes the app to crash

### ISSUE THREAD

**Issue by codeofdusk** [nvaccess/nvda#13503]
### Steps to reproduce:
1. Open [this message](https://github.com/nvaccess/nvda/files/8288480/bad.zip) in Outlook 16.0.15028.20050.
2. Press down arrow in the message body.

### Actual behavior:
Outlook crashes and the following is written to the log:

```
ERROR - NVDAHelperLocal (13:28:04.198) - MainThread (16740):
Thread 16740, build\x86\UIARemote\UIARemote.cpp, msWord_getCustomAttributeValue, 95:
Error in scope.Resolve: code -2147418113
DEBUGWARNING - scriptHandler.executeScript (13:28:04.218) - MainThread (16740):
error executing script: <bound method CursorManager.script_moveByLine_forward of <NVDAObjects.UIA.wordDocument.WordBrowseModeDocument object at 0x06EFECB0>> with gesture 'down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 212, in executeScript
  File "cursorManager.pyc", line 256, in script_moveByLine_forward
  File "cursorManager.pyc", line 163, in _caretMovementScriptHelper
  File "baseObject.pyc", line 26, in __get__
  File "treeInterceptorHandler.pyc", line 212, in _get_isCollapsed
  File "baseObject.pyc", line 26, in __get__
  File "textInfos\__init__.pyc", line 449, in _get_isCollapsed
  File "NVDAObjects\UIA\__init__.pyc", line 909, in compareEndPoints
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
DEBUG - speech.sayAll._TextReader.nextLine (13:28:04.220) - MainThread (16740):
no self.reader
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (13:28:04.298) - MainThread (16740):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUG - appModuleHandler.cleanup (13:28:04.303) - MainThread (16740):
application outlook closed
DEBUG - treeInterceptorHandler.killTreeInterceptor (13:28:04.314) - MainThread (16740):
Killed treeInterceptor: <NVDAObjects.UIA.wordDocument.WordBrowseModeDocument object at 0x06EFECB0>
```

### Expected behavior:
No app crash.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Commit c8d96591.

#### Windows version:
Windows 11 (22000.556).

#### Name and version of other software in use when reproducing the issue:
Outlook.

#### Does the issue still occur after restarting your computer?
N/A
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A (custom patterns new to 2022.1).
#### If NVDA add-ons are disabled, is your problem still occurring?
N/A
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A (UIA issue)

**Comment by codeofdusk** [comment]
It appears that commit c8d96591 does not exhibit this crash.

**Comment by michaelDCurran** [comment]
@codeofdusk  It would be great if you could track down the exact call from NvDA (Python code) that did this. My hunch is that it is when fetching section number. If so, we could easily refuse to fetch this for Outlook messages which I don't think would hurt users too much. However, this may also be true for fetching line numbers as well... in that case, we should not try fetching custom attributes in Outlook messages at all...

**Comment by codeofdusk** [comment]
Duplicate of #13511.
