### ISSUE TITLE
NVDA sometimes does  not read selected words in Eclipse editor

### ISSUE THREAD

**Issue by shadyar** [nvaccess/nvda#13513]
### Steps to reproduce:
Just open Eclipse STS (Spring Suite Tool) 

### Actual behavior:
After a while typing in an eclipse editor suddenly NVDA no longer reads selected words. it just says "selected"

### Expected behavior:
NVDA must read selected words. It must say "lab lab selected"

#### NVDA installed/portable/running from source:
NVDA installed

#### NVDA version:
(NVDA) Version: alpha-25008,c8d96591

#### Windows version:
Windows 11 enterprise 64-bit latest version
I tested in Windows 10 last version but The problem occurred.

#### Name and version of other software in use when reproducing the issue:
Eclipse or STS 2021

#### Other information about your system:
Laptop Asus UM325UA
I tested it by another laptop and a PC. The problem occurred.

#### Does the issue still occur after restarting your computer?
Yes, it does.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, I tried several older version of NVDA, the problem occurred while using all of them.

#### If NVDA add-ons are disabled, is your problem still occurring?
I uninstalled and installed again only NVDA. but problem still occurred 

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes, it does.

**Comment by seanbudd** [comment]
More technical information or investigation will help move this issue along, consider providing a debug log.

**Comment by shadyar** [comment]
> More technical information or investigation will help move this issue along, consider providing a debug log.
Okay, I post a log when ever I'll encounter this problem.

**Comment by shadyar** [comment]
This is a NVDA log related to this issue, I attached.
[nvda.log](https://github.com/nvaccess/nvda/files/8331712/nvda.log)

**Comment by Adriani90** [comment]
@shadyar, @mwhapples can you reproduce this issue with NVDA 2024.3 beta or 2024.2 Stable?

**Comment by shadyar** [comment]
It seems that the problem has been solved, thank you.
