### ISSUE TITLE
Word crashes on start if NVDA is in UIA-Mode for word document controls

### ISSUE THREAD

**Issue by adkurz** [nvaccess/nvda#13511]
### Steps to reproduce:

1. Go to settings, advanced and set "Use UI Automation to access Microsoft Word document controls" to "Always"
2. Open Microsoft Word and wait some seconds after the empty document control is shown (new document).

### Actual behavior:

After opening Word, the program closes and the NVDA Log, shows following error:

ERROR - NVDAHelperLocal (13:03:42.273) - MainThread (12844):
Thread 12844, build\x86\UIARemote\UIARemote.cpp, msWord_getCustomAttributeValue, 95:
Error in scope.Resolve: code -2147418113

### Expected behavior:

Word and NVDA should work together without the issue mentioned.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

alpha-25008,c8d96591

#### Windows version:

Windows 11 Pro X64: 21H2 (Build 22000.556)

#### Name and version of other software in use when reproducing the issue:

Microsoft Office 365 Version 2202 Build 16.0.14931.20128) 64 Bit

#### Other information about your system:

German language, new computer installed a week ago

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by lukaszgo1** [comment]
cc @michaelDCurran  While i understand custom annotations are not supported for this build of MS Word attempting to query for them should certainly not cause a crash.

**Comment by michaelDCurran** [comment]
I agree. I have also heard of crashes in Outlook, and I've experienced crashes in some MS Word tables. All to do with fetching a custom attribute value. This is absolteuly a bug in MS Word which I shell report straight away. 
We should firstly stop fetching these in Outlook, and in MS Word versions below 15000, whether or not UIA is forced. 
I shall investigate this further and decide specifically what to do.
