### ISSUE TITLE
Feature request ： add format change navigation to NVDA

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#13527]
## Is your feature request related to a problem? Please describe.
There is a lot of rich formatting in the documentation for emphasizing certain definitions or terms, such as bold or italic. Unfortunately, screen readers have no way to navigate them, which may degrade the reading experience if you enable report "Font attributes" in NVDA's document formatting dialog.
For this sentence: "No water, no life."
I made the words "water" and "life" bold and italicized respectively.
You might hear the following:
"No bold water no bold, no italic life no italic."

## Describe the solution you'd like
Please add a letter or key for navigating through formatting changes,
Also consider changing "Font attributes" to a dropdown combo box, like "Line indentation reporting", offering options like "off", "speech", "tones", "speech with tones".

## Describe alternatives you've considered
None
## Additional context
Actually part of this feature request is already implemented in tony's NVDA add-on.
see [here][1]

[1]: https://github.com/mltony/nvda-browser-nav

**Comment by leonardder** [comment]
I think this can be considered a duplicate of #9527.

**Comment by cary-rowen** [comment]
Hi @leonardder 

Yes, please close it as a duplicate of #9527.
One difference, I propose to use a tones to indicate format changes during reading,

Do you have any plans to continue working on it for #9527? I think this is really important and meaningful.

What does NV Access think about this?

Best

Cary
