### ISSUE TITLE
Text is announced twice in the latest version of Windows Terminal (1.12.10732.0)

### ISSUE THREAD

**Issue by jpospical** [nvaccess/nvda#13541]
### Steps to reproduce:
1. Open Windows Terminal
2. Do anything that generates output, including simply pressing enter to get a new line with the shell prompt.
### Actual behavior:
The text is announced twice, even though it hasn't changed.
### Expected behavior:
The output should only be read once. I believe this is related to [this fix](https://github.com/microsoft/terminal/pull/12358) in Windows Terminal; if I'm understanding correctly, it seems like NVDA may now be doing some unnecessary work.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.3.5
#### Windows version:
Windows 10 21H2, build 10.0.19044.1586
#### Name and version of other software in use when reproducing the issue:
Windows Terminal 1.12.10732.0
#### Does the issue still occur after restarting your computer?
Yes
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by josephsl** [comment]
Hi, looks like this is due to terminal output and UIA notification event. CC @CodeOfDusk

**Comment by codeofdusk** [comment]
Oh dear, sorry about this! Fixed in 2022.1, so get one of the latest betas. Didn't know this would be released so quickly!

CC @carlos-zamora.

**Comment by jpospical** [comment]
Ah, I didn't think to try a beta/snapshot. Sorry for the noise.

**Comment by josephsl** [comment]
Hi, don’t worry – I resolved it in Windows App Essentials add-on which is going through testing at the moment. Thanks.
