### ISSUE TITLE
Intermittent Crash with Firefox

### ISSUE THREAD

**Issue by hafta** [nvaccess/nvda#13540]
### Steps to reproduce:
Intermittent crash in Firefox believed to be caused by NVDA double free.

### Actual behavior:
Firefox crash.
Firefox bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1737688
Crash signature: https://crash-stats.mozilla.org/signature/?signature=RtlFreeHeap%20%7C%20free_base%20%7C%20std%3A%3A_Tree_val%3CT%3E%3A%3A_Erase_tree%3CT%3E&date=%3E%3D2022-02-24T05%3A55%3A00.000Z&date=%3C2022-08-24T05%3A55%3A00.000Z#summary

#### NVDA installed/portable/running from source:
Unknown.

#### NVDA version:
From the Firefox crash report, nvdaHelperRemote.dll version 2021.2.0.23747 was loaded.

#### Windows version:
Windows 8.1 6.3.9600.

#### Name and version of other software in use when reproducing the issue:
Firefox 93.0.

**Comment by seanbudd** [comment]
Welcome @hafta ,

We are unable to process this issue as it stands.

- To be able to reproduce this issue, we need steps to reproduce
- Please reproduce this issue and provide a [log file and Firefox crash dump](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Kind Regards,
NV Access Software Developers

**Comment by Adriani90** [comment]
We didn't get any update from the initial author since more than one year, closing as abandoned or even fixed most probably.
