### ISSUE TITLE
In notepad, pressing RETURN doesn't refresh the Braille display anymore

### ISSUE THREAD

**Issue by vincent-lg** [nvaccess/nvda#13551]
### Steps to reproduce:

1. Open Notepad (it might be a Windows 11 issue).
2. Type a line of text. Anything will do, as long as there is more than one character.
3. Press RETURN.

### Actual behavior:

The Braille display doesn't display the new (and empty) line after pressing RETURN.  Instead, the former line is still displayed with the blinking cursor as though one had not pressed RETURN.  One need to type in order to see the changes.

### Expected behavior:

A new, blank line of text (with a blinking cursor at the beginning) should appear.

**Comment by mwhapples** [comment]
I see this with my Braille display  and so I will take a look at this issue.

**Comment by mwhapples** [comment]
I think it may be an issue with UIA itself. There are also issues for speech. It seems like IUIAutomationTextRange.ExpandToEnclosingUnit gets the line before in the case of a trailing blank line. If the document ends with two trailing blank lines this is not an issue as the previous line also is blank, but it is when there is only one trailing blank line.

**Comment by mwhapples** [comment]
Further to the above, I have noticed that narrator also has some issues with this case as well, which implies it could be in UIA itself.

**Comment by mwhapples** [comment]
I have created a feedback request with Microsoft for this issue as I think it is an issue in UIA, see https://aka.ms/AAgkp9i

**Comment by josephsl** [comment]
Hi,

Resolved in Notepad 11.2203.10 (tested by dev channel Insiders at the moment, confirmed with braille viewer turned on).

Thanks.

**Comment by feerrenrut** [comment]
Closing as needs external fix, as mentioned by @josephsl, the fix appears to be in the pipeline.
