### ISSUE TITLE
NVDA no longer reading whole web page

### ISSUE THREAD

**Issue by amandamillar** [nvaccess/nvda#13552]
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

**Comment by josephsl** [comment]
Hi, we’re missing a very important puzzle piece here: what is the web browser and version you are using? Also, does it get resolved when you log out of the user account and log back in? Thanks.

**Comment by josephsl** [comment]
Hi, that’s okay – I figured this might be the first time you’re posting something like this. Glad the problem is resolved (what I meant by logging out of the user account is the account that you are signed into Windows). Do let us know if the problem comes back. Thanks.
