### ISSUE TITLE
crashing windows live 2011

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1356]
**Reported by loveme on 2011-02-06 13:05**
Is there anyway that you guys have nvda not crash windows live messenger 2011? It will work fine, but if you alt tab, or press the down Erro  it will crash the program.  That's the only problem I see right now.

**Comment by dkager** [comment]
In https://github.com/nvaccess/nvda/issues/1356#issuecomment-155287334 it is suggested that this is specific to WLM's text controls, not text controls in general.

Windows Live Messenger has been discontinued. Closing.
