### ISSUE TITLE
When downloading Windows updates, NVDA reads old update percentage

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#13567]
### Steps to reproduce:

1) Open the Windows update screen (Press windows, type "update", launch "Check for updates" system setting).
2) Check for and download an update.
3) Focus the name of the update to read the percentage while downling.

### Actual behavior:

NVDA reads the name of the update and the percentage downloaded / installed, however reads each percentage update in order (eg "name" downloading 1%, then "name" 2%, then "name" 3% etc, where "name" is the full name and KB number of the update) even though by the time it is reading information, it may be well beyond that point.

### Expected behavior:

As soon as NVDA detects a change in the percentage, it should drop any old changes and only read the latest change.

#### NVDA version:

NVDA 2022.1 Beta 3 Installed
#### Windows version:

Windows 10 (64-bit) Version: 21H2 (2009), Build: 19044.1586 

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
No
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by enessaribas** [comment]
Hi,
In Windows 11, now none of that information is announced. Only downloading update and installing update.  If you attempt to focus the percentage bar with object navigation, periodically whenever it updates focus is thrown  out of that area.

**Comment by josephsl** [comment]
Hi, cause: live region change event. By default NVDA is told to announce all live region changes even if the screen text gets out of sync. It is highly unlikely that Microsoft will change the update UI for Windows 10, so looks like something may need to be done from NVDA side , balancing between announcing all live region changes versus cutting off things. A live region monitor might be of use, but until we figure things out, the next best thing is me offering yet another intervention in the form of Windows App Essentials add-on update. What I wrote above does not apply to Windows 11 at all. Thanks.

**Comment by josephsl** [comment]
Hi, focus movement problem is resolved in Version 22H2 (dev and beta). Thanks.

**Comment by Brian1Gaff** [comment]
Just to say, this is not a new thing, as other software suffers from time to 
time, and I always put it down to how the message is updated to the screen.
Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by josephsl** [comment]
Hi, I think it would be best to deal with individual cases as there are live regions where we may wish to let NVDA report the whole thing without interruption (for example, update status region in Windows Update when Windows says you are up to date). In the meantime, I’ll do something about Windows Update status live region issue via my add-on. Thanks.

**Comment by Qchristensen** [comment]
Thanks Joseph, that sounds like a good approach.  In that case, I will close this issue.

**Comment by josephsl** [comment]
Hi, I once read a discussion on Twitter that talks about this issue. If yes, I’ll mention both Microsoft and NV Access when I do release a dev build of my add-on with this specific issue resolved (the earliest time I can release a stable version with the fix applied is May). Thanks.

**Comment by josephsl** [comment]
Hi,

2025 update: resolved from Microsoft - live region change event is no longer raised in Windows 10 Settings/Update and Security/Windows Update screen when downloading updates.

Thanks.
