### ISSUE TITLE
The name of the unit for the font size in the formatting information provided by NVDA is not localized

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#13573]
### Steps to reproduce:
1. Start NVDA.
2. Switch NVDA's interface language from english to another one (preferably one that you are familiar with) and restart NVDA when prompted.
3. Open a text editor like Notepad or a similar one, from which text formatting information can be retrieved by NVDA.
4. Type some text in it.
5. Move the system caret on one of the typed characters.
6. Invoke the NVDA script for reporting formatting information (e.g. NVDA+F for the desktop keyboard layout).
7. Press the same command twice, to display the information in a browse mode window.
8. Observe how NVDA reports the information, specially the name of the font size unit.

### Actual behavior:
NVDA reports the font size unit in english as "pt" (which means "points"), instead of in the language in which NVDA is set to.

### Expected behavior:
NVDA should report the font size unit in the language in NVDA's interface language is set to.

### System configuration
- Operating system: Windows 11 Pro version 21H2 (build 22000.556), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-25159,c4466885, 2021.3.5 (both set to "Bulgarian").
- Processor: Intel Core i5-9400F at 2.90GHz.
- RAM Memory: 16.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC892 at Intel Cannon Point PCH.

#### Does the issue still occur after restarting your computer?
Yes, it does.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Both the latest alpha build and 2021.3.5 behave the same.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes, it is.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
I haven't tried it, because the issues that the COM Registration Fixing Tool aims to fix are not related to the issue I'm describing here.

**Comment by CyrilleB79** [comment]
In notepad (at least on Windows 10), there is no such formatting information.
However in WordPad or MS Word, there is this information.

On my system, I have no translation issue since I am using NVDA in French; in this language, the unit is also called "point' and the abbreviation "pt" is used for it. It can be seen in Word when you get information for a style from the style management window.

As an example, could you please indicate what would be the translated abbreviation in Bulgarian? I imagine it is written in Cyrillic? Are you able to see this abbreviation written somewhere, e.g. in Word's style definition?

**Comment by k-kolev1985** [comment]
In bulgarian, the abbreviated variant of the font size unit is "пкт". The whole word is "пункта", which means "points".

I thought that the information might be extracted directly (including locale names) from the program in which the command for formatting information is requested and therefore the issue might be caused by broken bulgarian localization in the specific program, but this occurs in every program that I've tested (both built-in and external ones) and this makes this theory highly unlikely. Unless, the information, although taken from the specific program, is provided by the system on a system level and the bulgarian localization for this is broken on a system level. But to be honest, I doubt it - I think this is just hard-coded in NVDA and it is not localizable at the moment.

**Comment by CyrilleB79** [comment]
Yes, I have seen that it is hard-coded and not localizable in NVDA, at least for some applications or interface. I think that it could be localized quite easily.

This issue may be a good canditate for labels such as "good for new dev" or "good first issue".
Cc @seanbudd, @feerrenrut.

If no one volunteers to fix this issue, I may have a look at it when I have more time. Feel free to ping me again.

**Comment by gregjozk** [comment]
in slovenian there is simular problem.
tested in web browsers, word etc.
this bug exist a longtime, but users easily dismiss it during hard work.
simular bug is in word on "page break". this string is translatable and in slovenian translated, but when UIA is disabled for word, NVDA still speaks page break...

**Comment by CyrilleB79** [comment]
@gregjozk you write:
> simular bug is in word on "page break". this string is translatable and in slovenian translated, but when UIA is disabled for word, NVDA still speaks page break...

A similar bug, yes, but maybe not with the same type of cause.
In French, "page break" is localized; tested in Word.
Thus if you want to have the "page break" untranslated issue looked at, you should open a separate issue for it.
