### ISSUE TITLE
treeInterceptor.documentConstantIdentifier doesn't work in Chrome v100

### ISSUE THREAD

**Issue by mltony** [nvaccess/nvda#13570]
### Description
This is mltony, author of BrowserNav add-on. Certain functions stopped working in Chrom v100. In particular, I was using treeInterceptor.documentConstantIdentifier property to retrieve URL of current page and it no longer seems to work on some websites in Chrome v100.
I can't figure out what's the pattern, e.g. amazon.com fails, while google .com seems to work fine.
### Steps to reproduce:
1. Open Google Chrome v100.
2. Navigate to Amazon.com
3. Open NVDA Python console by pressing NVDA+Control+Z
4. Type: `focus.treeInterceptor.documentConstantIdentifier`
### Actual behavior:
Returns empty string.
### Expected behavior:
Should return URL, something like `https://www.amazon.com/`.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.3
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Google Chrome Version 100.0.4896.60 (Official Build) (64-bit)
Used to work fine in Chrome before v100. Also works fine in Firefox and Edge.
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, reproduces in 2022.1beta3
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by amirsol81** [comment]
@mltony Guess this is similar to #13571 which I created after your report.

**Comment by amirsol81** [comment]
@mltony The same or similar issues apparently affect NVDA's ability to not report the page title upon load and break the auto-SayAll function on most, if not all, pages.

**Comment by Adriani90** [comment]
cc: @feerrenrut, @ObjectInSpace, @aleventhal

**Comment by aleventhal** [comment]
I don't see anything actionable on the Chrome side yet. LMK if there is a bug in one of our APIs.
