### ISSUE TITLE
Please default ESpeak NG's voice role to "Chinese (Mandarin, latin as Pinyin)" for Chinese to fix #12952

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#13572]
### Is your feature request related to a problem? Please describe.
#12952 makes ESpeak completely unusable for Chinese users. This is a disaster for beginners who cannot use Windows OneCore.
### Describe the solution you'd like
After testing, setting the voice role of ESpeak NG to "Chinese (Mandarin, latin as Pinyin)" can temporarily solve #12952 .
The word "temporarily" is used because the English pronunciation of "Chinese (Mandarin, latin as Pinyin" is less vivid than the current default "Chinese (Mandarin, latin as English)".
But this solution can get rid of the dilemma of not being able to use ESpeak NG at all.

### Describe alternatives you've considered
The best solution is to solve [#1028](https://github.com/espeak-ng/espeak-ng/issues/1028) by ESpeak.
Make "Chinese (Mandarin, latin as English)" can speak Chinese correctly.
### Additional context.
I think this question is urgent enough, especially for beginners of nvda.

**Comment by Brian1Gaff** [comment]
Is this then, not also an issue you need to report to the Espeak list as 
well?
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Rowen" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Saturday, April 02, 2022 3:43 AM
Subject: [nvaccess/nvda] Please default ESpeak NG's voice role to "Chinese 
(Mandarin, latin as Pinyin)" for Chinese to fix #12952 (Issue #13572)

**Comment by cary-rowen** [comment]
@Brian1Gaff 
Sorry, I'm just a regular user, please give some explanation as useful as possible why I can't ask this request in the NVDA Repo.
I obviously see other screen reader that use the same version of ESpeak as nvda but default to the correct Chinese Mandarin voice.

**Comment by cary-rowen** [comment]
Still thanks for your suggestion, I'll make the same request in the ESpeak repo if possible.

**Comment by feerrenrut** [comment]
- #12950
May impact this.

**Comment by feerrenrut** [comment]
Note, the default / preference for the voice for a certain language code is controlled by espeak-ng.
This will also need to be reported to espeak as per https://github.com/espeak-ng/espeak-ng/issues/1028

**Comment by cary-rowen** [comment]
hi @feerrenrut 

Unfortunately #12950 doesn't change anything for that.
I have made the request in ESpeak NJ repo,
please see [here](https://github.com/espeak-ng/espeak-ng/issues/1028#issuecomment-1094884941)

Thanks

**Comment by cary-rowen** [comment]
Hi,
@feerrenrut 
This issue doesn't seem to get enough attention in ESpeak, and I'm wondering how this can be advanced.
Thanks

**Comment by cary-rowen** [comment]
Hi guys,

If [this commit][1] is merged, and espeak-ng/espeak-ng#1044 is closed, then this issue can also be closed after updating eSpeak.


[1]: https://github.com/espeak-ng/espeak-ng/issues/1044

**Comment by seanbudd** [comment]
Can you let us know when we can update eSpeak to close this issue

**Comment by cary-rowen** [comment]
@seanbudd 
Sorry, the link I provided above was wrong, now that I've corrected it, we'll keep an eye on the status of [this commit][1].
[1]: https://github.com/espeak-ng/espeak-ng/commit/1443c970cdffe258276e1a6442316268c1d380be

**Comment by cary-rowen** [comment]
@seanbudd 
The commit I mentioned in the above comment has been merged, can we now update eSpeak NG in NVDA to solve the problem for Chinese users?
This problem directly prevents Chinese users using Windows7 from using eSpeak to complete the installation of NVDA, and it should even be fixed in 2022.3Beta.

**Comment by seanbudd** [comment]
@cary-rowen - 2022.3beta is well and truly closed to new features. We will try to update eSpeak again for 2022.4
