### ISSUE TITLE
NVDA double reads characters in VS Code quick pick

### ISSUE THREAD

**Issue by isidorn** [nvaccess/nvda#13577]
1. Latest NVDA, latest [VS Code insiders](https://code.visualstudio.com/insiders/)
2. Turn on NVDA, Open VS Code Insiders, 
3. Ctrl + P -> start typing
4. Notice that NVDA double reads every typed character 🐛 

No other screen reader behaves like this.
Can you please investigate on the NVDA side and let me know how we can solve this problem together.

Thank you
fyi @leonardder @ahicks92

**Comment by isidorn** [comment]
@josephsl correct, I am using NVDA `2021.3.5`

**Comment by leonardder** [comment]
This isn't a bug on NVDA"s side. I'll update the original VS code issue accordingly.
