### ISSUE TITLE
gecko_ia2 virtual buffer produces some errors while loading a page

### ISSUE THREAD

**Issue by OzancanKaratas** [nvaccess/nvda#13600]
### Steps to reproduce:
1. Open Firefox or a Chromium based web browser.
2. Load a page.
3. Wait for error sound.
### Actual behavior:
NVDA logs the following error:
```
ERROR - queueHandler.flushQueue (19:43:42.878) - MainThread (8840):
Error in func VirtualBuffer._loadBufferDone
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "virtualBuffers\__init__.pyc", line 492, in _loadBufferDone
  File "browseMode.pyc", line 1306, in event_treeInterceptor_gainFocus
  File "virtualBuffers\gecko_ia2.pyc", line 532, in _getInitialCaretPos
  File "browseMode.pyc", line 1850, in _getInitialCaretPos
UnboundLocalError: local variable 'caretPos' referenced before assignment`
```
### Expected behavior:
NVDA should run without errors.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-25209,21367c8e
#### Windows version:
Windows 11
#### Name and version of other software in use when reproducing the issue:
Google Chrome 100.0.4896.75
#### Other information about your system:
Not required
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The issue was produced after merging #13589.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment]
Cc @michaelDCurran, @feerrenrut
