### ISSUE TITLE
wechat

### ISSUE THREAD

**Issue by chinput** [nvaccess/nvda#13619]
### Steps to reproduce:
Here is sogou input method.

We implement the MSA interface in software.
EVENT_OBJECT_FOCUS is sent when the focus object changes.

### Actual behavior:
But NVDA doesn't sense it.

### Expected behavior:
NVDA can read focus object

#### NVDA installed/portable/running from source:
https://www.nvdacn.com/index.php/nvda.html

#### Name and version of other software in use when reproducing the issue:
none

#### Other information about your system:
The software in China can  sense it~
For example：争度读屏, 阳光读屏

#### Does the issue still occur after restarting your computer?
no

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes

#### If NVDA add-ons are disabled, is your problem still occurring?
no

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
no

**Comment by lukaszgo1** [comment]
@chinput Please fill the issue template. Otherwise this issue would be closed.

**Comment by chinput** [comment]
I think I know why.

Note the following:

1
NotifyWinEvent(DWORD Event, HWND HWND, LONG idObject, LONG idChild) 
The third parameter, idObject, needs to distinguish between different objects

2
IAccessible: : get_accState return to a state of must contain STATE_SYSTEM_FOCUSED | STATE_SYSTEM_FOCUSABLE
