### ISSUE TITLE
while using sapi5, when I change the voice, the volume and rate parameters are reset

### ISSUE THREAD

**Issue by alexandretoco** [nvaccess/nvda#13631]
### Steps to reproduce:
I am using eloquence through sapi5.
1. use ctrl + shift + right arrow to adjust volume and rate
2. use the same commands and change the voice
### Actual behavior:
when I change voice, the volume goes to 100% and the rate also changes to a value slower then I set before
### Expected behavior:
nvda should keep the volume and rate as same as in the previous voice
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2022.1 beta 3
#### Windows version:
windows 10
#### Name and version of other software in use when reproducing the issue:
eloquence sapi5 version
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
not related

**Comment by seanbudd** [comment]
This is deliberate, as SAPI5 voices have non-standardized rates and volumes, so it safer to defer to default.
