### ISSUE TITLE
No new Alpha builds of NVDA since April 20th

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#13638]
### Steps to reproduce:
Check when the latest Alpha version of NVDA was released, then compare the date with the last commit to master.
### Actual behavior:
The latest Alpha was released on April 20 TH, whereas the last commit to master was today. In other words no build of Master succeeded since April 20.
### Expected behavior:
Since the failure when building Alpha is caused by the failing system tests (for example see [this build log](https://ci.appveyor.com/project/NVAccess/nvda/builds/43343901) ), I would expect that results of system tests should not affect Alpha builds.

#### NVDA installed/portable/running from source:
N/A
#### NVDA version:
Latest master
#### Windows version:
N/A
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
N/A
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A
#### If NVDA add-ons are disabled, is your problem still occurring?
N/A
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by lukaszgo1** [comment]
cc @feerrenrut  Assuming that we cannot make our system tests not failing intermittently skipping them for Master builds seems a reasonable work around - that of course assumes that only code for which system tests passed is ever merged to the master branch.

**Comment by seanbudd** [comment]
This is no longer true
