### ISSUE TITLE
Include python3.dll so add-ons can use the stable Python C ABI

### ISSUE THREAD

**Issue by mwcampbell** [nvaccess/nvda#13645]
### Is your feature request related to a problem? Please describe.

Add-on developers that want to include a Python C extension module in their add-on currently have to compile that module for the specific version of Python that NVDA is using, leading to another type of add-on breakage when NVDA updates Python.

### Describe the solution you'd like

Python 3 provides a limited C API with a stable ABI. To use this feature on Windows, the python3.dll file included with Python needs to be part of the distribution.

### Describe alternatives you've considered

I know it's typical for Python code in NVDA to interface with native code through ctypes. This is adequate, of course, but for an add-on I'm working on, I'll be using Rust for the native code, and I'd like to avoid the extra overhead of a C FFI, especially since there are good Rust packages for safely working with the Python C API.

**Comment by seanbudd** [comment]
Would you be able to provide a hypothetical example of what needs to use this?

**Comment by seanbudd** [comment]
Closing as stale as no information / use case has been provided

**Comment by josephsl** [comment]
Hi, two things: I bet this is a 32-bit DLL, so we might as well think about 64-bit ABI too when NV Access says we will be moving to 64-bit. Second, would it be possible to document that this works with Python 3.7 and later as wel? Thanks.
