### ISSUE TITLE
In Firefox, pressing enter on an editable list item does not switch to focus mode

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#13642]
### Steps to reproduce:
1. In Firefox, open this test case:
    `data:text/html,<div contenteditable><ul><li>test`
2. Press control+home to move to ensure the cursor is within the list item.
3. Press enter.

### Actual behavior:
NVDA should switch to focus mode.

### Expected behavior:
It doesn't.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-25262,a55f9a62

#### Windows version:
Windows 11 Version 21H2 (OS Build 22000.613)

#### Name and version of other software in use when reproducing the issue:
Firefox Nightly 101 (but this is not specific to Nightly)

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2021.3.5, same problem

### Other info
I believe I've tracked this down to [this line of code](https://github.com/nvaccess/nvda/blob/9b5fa21/source/NVDAObjects/IAccessible/__init__.py#L932) which removes the editable state if the readonly state is present. This was introduced in 0569e731, PR #7935. The problem is that for lists and list items, the readonly state is used to differentiate between an interactive list box and a non-interactive list. It's possible to have an editable list, in which case Firefox exposes both the readonly and editable states.

This doesn't happen in Chrome because Chrome doesn't expose the readonly state on editable lists. Interestingly, NVDA [has to work around this lack of the readonly state for editable lists in Chrome](https://github.com/nvaccess/nvda/blob/9b5fa21/source/NVDAObjects/IAccessible/chromium.py#L106).

I think NVDA should not remove the readonly state for lists and list items which have the editable state.

CC @MichaelDCurran, who authored the regressing pull request.

**Comment by michaelDCurran** [comment]
As removing that change to editable/readonly will cause a regression in Google Sheets, I think at a minimum we can tighten up that logic to only remove the editable state when readonly exists on tables/rows/cells, as they were originally the problematic roles anyway. This would leave lists unaffected. Perhaps we could come up with something better in the long-term, but I feel this would be a suitable compromise at the moment.

**Comment by Adriani90** [comment]
cc: @SaschaCowley

**Comment by Adriani90** [comment]
just for completeness, it seems a work around is to add some blank lines to the list. Pressing enter on the blank lines switches to focus mode, but indeed it doesn't work if there is a bullet or something that triggers a new list item.
