### ISSUE TITLE
Use consistent terminology for insert key between User Guide and Welcome Screen

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#13648]
### Is your feature request related to a problem? Please describe.

On the "Welcome Screen", there is a line which reads:
"By default, the numpad Insert and main Insert keys may both be used as the NVDA key."

In the User Guide, in section 4.2.1, the second paragraph reads:
"NVDA can be configured so that the numpad Insert, Extended Insert and/or Caps Lock key can be used as the NVDA modifier key. By default, both the numpad Insert and Extended Insert keys are set as NVDA modifier keys."

### Describe the solution you'd like

We should be consistent and use either "Main Insert" or "Extended Insert".

The Microsoft Style Guide simply notes the "Insert key" without distinguishing between them: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/keys-keyboard-shortcuts

Wikipedia gives screen readers a mention but also doesn't offer a disctinction beween the different insert keys: https://en.wikipedia.org/wiki/Insert_key (in fact the text doesn't mention the number pad insert at all, although it is highlighted on the image of a keyboard).

I can't find any reference specifying what to call that insert key near delete, home, end etc.  I've heard it called "extended insert" before although I am not sure how many people are familiar enough with either term?

So, I don't mind either way, but we should endeavour to be consistent, whatever we call it.

### Describe alternatives you've considered

Doing nothing.  That has mostly worked well until now, but it is probably worth neatening it up.

**Comment by XLTechie** [comment]
I had never heard the term "extended insert" until reading that in the user 
guide years ago.
In fact i remember wondering how it was different than the normal insert key in 
the six-pack, and where it was.

Because we are talking about two (or three if you count capslock) different 
inserts, "main" or "regular" insert seems reasonable to me.

Although I could be fine with just calling it "insert" vs. "numpad insert".

I don't like "extended insert" though.

**Comment by feerrenrut** [comment]
I think we should go with `insert` and `numpad insert`, it differentiates them without introducing some new and 'specific to NVDA terminology'.
