### ISSUE TITLE
In Chrome or Chromium-based Browsers NVDA does not Initiate the Say All Command When Opening a Page in a New Browser Window

### ISSUE THREAD

**Issue by dgoldfield** [nvaccess/nvda#13650]
# Steps to reproduce:
1. Open Chrome. (The newly loaded page that first opens might also not initiate the say all function.
2. Move to a link on the page.
3. Press shift+enter to open the page in a new window.

### Actual behavior:
NVDA does not automatically read the contents of the newly opened page when it is opened in a new browser window.

### Expected behavior:
When opening a page in a new browser window NVDA initiates a say all command.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.3.5
#### Windows version:
Windows 11 21 H2
#### Name and version of other software in use when reproducing the issue:
Google Chrome/Brave Version 100
#### Other information about your system:
Dell Vostro 5510
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2022.1 beta 3. Produces identical results.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by dgoldfield** [comment]
I initially closed this as I had difficulty submitting the report properly but this is now resolved.

**Comment by lukaszgo1** [comment]
cc @michaelDCurran  It seems fixes for say all when loading new pages in Chromium included in 2022.1 are not always effective.

**Comment by seanbudd** [comment]
Is this fixed by #13652, [alpha-25324,0f08ccb7](https://ci.appveyor.com/project/nvaccess/nvda/build/alpha-25324,0f08ccb7)?

**Comment by seanbudd** [comment]
This should be fixed by #13589 and fixed in 2022.1beta4

**Comment by dgoldfield** [comment]
It is indeed fixed in beta 4. Many, many thanks for such a quick response.


David Goldfield,
Blindness Assistive Technology Specialist
[JAWS Certified, 2022]<https://www.freedomscientific.com/Training/Certification>
NVDA Certified Expert<https://certification.nvaccess.org/>

Subscribe to the Tech-VI announcement list to receive emails regarding news and events in the blindness assistive technology field.
Email: ***@***.******@***.***>
www.DavidGoldfield.org<http://www.DavidGoldfield.org>
