### ISSUE TITLE
StartisBack application fails to speak menu items

### ISSUE THREAD

**Issue by hxebolax** [nvaccess/nvda#13659]
### Steps to reproduce:

* Install StartisBack for Windows 11:

https://www.startallback.com/

* Press WIN key

Navigate up or down if we have quick access items or right arrow to go to the different items such as Control Panel, Run, Settings, Favorites, Documents, Downloads, etc....

### Actual behavior:

When scrolling through the menu it only speaks the word [selected].

### Expected behavior:

You are expected to verbalize the name of the item that has the focus.

#### NVDA installed/portable/running from source:

For the tests I used both installed and portable versions.

#### NVDA version:

NVDA 2022.1beta4

#### Windows version:

Name SO	Microsoft Windows 11 Pro
Version	10.0.22000 Build 22000

#### Name and version of other software in use when reproducing the issue:

StartisBack version 3.3.5

#### Other information about your system:

N/A

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

* NVDA 2021.3.5

Behavior is as expected, correctly verbalizes menu items.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

[logs.zip](https://github.com/nvaccess/nvda/files/8609725/logs.zip)

**Comment by seanbudd** [comment]
Hi @hxebolax - thanks for your testing. I've updated the title to be more accurate. 

Just to confirm - does any application actually crash? From my understanding, menu items are just failed to be read correctly.
The rest of the issue description seems to suggest this, and has no mention of crashes occurring.

**Comment by jmdaweb** [comment]
There are no crashes, the translator chose the wrong word when translating the message from spanish to english.

**Comment by seanbudd** [comment]
Unfortunately we are unable to safely fix this issue. The StartIsBack and StartAllBack developers need to be contacted.
This information might be helpful for future developers investigating the issue.

When navigating through the start menu with the application StartAllBack/StartIsBack installed, a layer is created over file explorer. NVDA uses the file explorer app module, but fetching the column order array with SendMessage fails.
We fetch the column order array ([LVM_GETCOLUMNORDERARRAY](https://docs.microsoft.com/en-us/windows/win32/controls/lvm-getcolumnorderarray)) with [SendMessage](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendmessage). While other related ListView messages are successful, we cannot be determine the correct data without a known column order array.

When this fails, 3 different errors are reported:
- 1400: [ERROR_INVALID_WINDOW_HANDLE](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1300-1699-)
- 0: [ERROR_SUCCESS?](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-)
- 5: [ERROR_ACCESS_DENIED](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-)

We are uncertain why these errors are reported, or why the error codes are inconsistent. I expect it is to do with the StartIsBack/StartAllBack dll that is injected into file explorer.
