### ISSUE TITLE
Trust voice's language when processing characters and symbols  does not work

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#13678]
### Steps to reproduce:
1 Ensure that the Trust voice's language when processing characters and symbols  check box  is not checked (Voice Settings).
2 Enable automatic language switching and select an English voice or the English language in your speech synthesizer.
3 Visit es.wikipedia.org and navigate to, for instance, the line: "¿Cómo colaborar?."
4 Separately, open the Punctuation/Symbol Pronunciation dialog.

### Actual behavior:
The question marks are reported in Spanish (as are other symbols) and the Punctuation/Symbol Pronunciation dialog loads with English as opposed to NVDA's global language (as documented in the User Guide). This is true both with ESpeak-NG and Windows OneCore.

### Expected behavior:
The questions marks being symbols should be read in NVDA's language (English in my case as set in General Settings) or the speech synthesizer's original language, as opposed to that in which the text may have been marked up even though automatic language switching is enabled. Also, Punctuation/Symbol Pronunciation should load globally as opposed to for a particular language like English.

### Notes ###
I report this apparent bug with considerable uncertainty about my understanding of these functionalities. My use case is that I am learning Spanish and would like the symbols to be read as they are in English so that I can focus solely on the substantive Spanish text. I am not sure if I correctly understand the term "global language" used in the User Guide, nor have meaningfully used the Trust voice's language when processing characters and symbols option in the past.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.3.5
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Firefox version 100.0
Microsoft Edge version 101.0.1210.39
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by feerrenrut** [comment]
Does turning off automatic language switching fix the problem for you?

**Comment by bhavyashah** [comment]
@feerrenrut Turning off automatic language switching does cause the symbols to be reported in English but the Punctuation/Symbol Pronunciation dialog shows up in English still. Checking "Trust voice's language when processing characters and symbols" fixes the latter issue though.

**Comment by Adriani90** [comment]
cc: @CyrilleB79

**Comment by CyrilleB79** [comment]
@bhavyashah I am trying to clearly understand this issue. Could you clarify the points I raise below? Thanks.

> ### Actual behavior:
> 
> The question marks are reported in Spanish (as are other symbols)

Confirmed on my side.

> and the Punctuation/Symbol Pronunciation dialog loads with English as opposed to NVDA's global language (as documented in the User Guide).

I do not understand. Your NVDA is in English and the dialog opens with English symbols. This seems OK to me.

> (...)

> ### Expected behavior:
> 
> The questions marks being symbols should be read in NVDA's language (English in my case as set in General Settings)

I agree with that.

> or the speech synthesizer's original language, as opposed to that in which the text may have been marked up even though automatic language switching is enabled.

No, if you uncheck trust voice language, you should not use the synth's language to read symbols. At least, that's what I understand from the User Guide and from the option's name.

> Also, Punctuation/Symbol Pronunciation should load globally as opposed to for a particular language like English.

What do you mean?

> ### Notes
> 
> I report this apparent bug with considerable uncertainty about my understanding of these functionalities. My use case is that I am learning Spanish and would like the symbols to be read as they are in English so that I can focus solely on the substantive Spanish text. I am not sure if I correctly understand the term "global language" used in the User Guide, nor have meaningfully used the Trust voice's language when processing characters and symbols option in the past.

**Comment by CyrilleB79** [comment]
@bhavyashah, could you please answer to the questions in my previous comment (https://github.com/nvaccess/nvda/issues/13678#issuecomment-1516960417)?

Without feedback from your side, we will have to close this issue.

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author upon request since more than 2 years, closing as abandoned. Please comment and provide the requested info if you still have this issue and we can reopen.
