### ISSUE TITLE
Wrong display name for Chinese Braille output and input tables

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#13674]
### Steps to reproduce:
1. Switch the display language of NVDA to English;
2. Go to the Braille settings panel;
3. Navigate the output table and input table combo box.
### Actual behavior:
You will see the following items:
- Chinese (China, Mandarin) grade 1
- Chinese (China, Mandarin) grade 2

### Expected behavior:
The display name here is incorrect, according to the definition in the Chinese National Standard [GB/T 15720-2008][1], sections 2.13 and 2.14:
- "Chinese (China, Mandarin) grade 1" should be changed to "Chinese (China, Mandarin) Current Braille System"
- "Chinese (China, Mandarin) grade 2" should be changed to "Chinese (China, Mandarin) Double-phonic Braille System"

I will open a PR to correct this.

Due to copyright reasons, the text in the above "GB/T 15720-2008" link cannot be read by visually impaired users, but it can be previewed in image form.
#### NVDA installed/portable/running from source:
installed, portable, running from source:
#### NVDA version:
All
#### Windows version:
n/a
#### Name and version of other software in use when reproducing the issue:
n/a
#### Other information about your system:
n/a
#### Does the issue still occur after restarting your computer?
n/a
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
n/a
#### If NVDA add-ons are disabled, is your problem still occurring?
n/a
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
n/a

[1]: http://www.gb688.cn/bzgk/gb/newGbInfo?hcno=484E4150A1F62E81B0553422E6A8A292

**Comment by seanbudd** [comment]
Hi @cary-rowen, I assume Chinese users would be more familiar with the names you have suggested.
Just to confirm, I have two related concerns:

The phrase "Current Braille system" could appear misleading when selecting a braille table.
Is it necessary to remove "Mandarin" from the name? I am concerned that removing it will make it difficult to differentiate with other Chinese braille tables.

You may also want to consider a liblouis issue / PR.
https://github.com/liblouis/liblouis/blob/master/tables/zhcn-g1.ctb
https://github.com/liblouis/liblouis/blob/master/tables/zhcn-g2.ctb

**Comment by cary-rowen** [comment]
Hi, @seanbudd 

You're right, I'll add the word 'mandarin' for the sake of distinction.

I'm not very familiar with the Liblouis repo, do I just need to change the two files you mentioned for this change?

To be on the safe side, I may need to open an issue in Liblouis first.

Thanks

**Comment by seanbudd** [comment]
> Hi, @seanbudd 
> 
> You're right, I'll add the word 'mandarin' for the sake of distinction.
> 
> I'm not very familiar with the Liblouis repo, do I just need to change the two files you mentioned for this change?
> 
> To be on the safe side, I may need to open an issue in Liblouis first.
> 
> Thanks

I believe editing these is all that is needed, but I would open an issue and confirm.

Do you have any ideas on something other than "Current Braille System"? Is "Modern Braille" an appropriate alternative translation)?

**Comment by cary-rowen** [comment]
To be honest, "Current Braille System" I don't think is a better name, but as I mentioned, it is the translation given in China's national standard document[(GB/T 15720-2008)](http://www.gb688.cn/bzgk/gb/newGbInfo?hcno=484E4150A1F62E81B0553422E6A8A292).
I also consulted with professionals in the field of Braille in China, and they also suggested using the names in the national standard documents.

**Comment by cary-rowen** [comment]
@seanbudd 
I modified the original description and the corresponding PR.
