### ISSUE TITLE
Minimally document context sensative help

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#13695]
### Is your feature request related to a problem? Please describe.

There is no documentation in the user guide or commands quick reference, for the context sensitive help feature, available on F1.

As a result, most users do not likely know about it.

### Describe the solution you'd like

While I know it is not yet available in every dialog, or for every control; and it does have some browser-related technical issues that make it a bit unreliable: I suggest providing at least some mention of it in the User Guide, and also in the Command Quick Reference.

### Describe alternatives you've considered

Well, it could be kept as a hidden/undocumented feature, until everything that can have it, does have it. But it is somewhat useful as it sits, so IMHO it should be publicized.

**Comment by XLTechie** [comment]
CC @Qchristensen

**Comment by CyrilleB79** [comment]
Yes I support this.

IMO it is not undocumented on purpose. Indeed, I was documented in the change log for NVDA 2020.4, not only in the list of changes, but also in the introduction text describing the main features of the release.

**Comment by XLTechie** [comment]
> IMO it is not undocumented on purpose. Indeed, I was documented in the change log for NVDA 2020.4, not only in the list of changes, but also in the
> introduction text describing the main features of the release.

I very much suspect that most users have never read the changelog.
