### ISSUE TITLE
NVDA tends to sometimes land on the wrong place whem moving around within rappidly updating webpages

### ISSUE THREAD

**Issue by Keithcat1** [nvaccess/nvda#13697]
### Steps to reproduce:
Go play an incremental game such as Antimatte rDimensions or Trimps, set the update rate as fast as possible under options.
### Actual behavior:
Occationally, you will try pressing B to select the next button, only to find that you haven't moved or have moved a button or three too far.
### Expected behavior:
It doesn't jump around and selects the button / checkbox / heading / whatever in the order they're presented.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.3.4
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
Google Chrome Version 101.0.4951.54 (Official Build) (64-bit)
#### Other information about your system:
64-bit
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
I spent five minutes trying with addons disabled but wasn't able to reproduce it. That was a freshly started instance of AD though. It's possible that this only happens after the webpage has been open for a while.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Brian1Gaff** [comment]
Have you tried this with  a different browser. I never got along with 
Chrome, it used to lag or do funny things for me.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Keithcat1" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Saturday, May 14, 2022 8:50 PM
Subject: [nvaccess/nvda] NVDA tends to sometimes land on the wrong place 
whem moving around within rappidly updating webpages (Issue #13697)

**Comment by seanbudd** [comment]
Welcome @Keithcat1 ,

We are unable to process this issue as it stands.

- To be able to reproduce this issue, we need a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).
- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.
- This is very likely a problem with the implementation of the application/website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers
