### ISSUE TITLE
problem with numbers in windows live messenger

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1371]
**Reported by fatma.mehanna on 2011-02-13 23:39**
when i type numbers in windows live messenger's edit fields such as the email address edit field or the input message edit and use the left and right arrow to move , silence occurs.  the same thing happens when i press back space to delete a number
for example, if the email address contains numbers like fatma24 and you typed a wrong number, when you press back space to delete it, nvda says nothing. nvda also doesn't read the numbers when you move by arrow keys
this happens in vda version 2010.1, 2010.2, and 2011.1 beta2

**Comment by dkager** [comment]
Assuming this issue is about Messenger, not Mail: Windows Live Messenger has been [discontinued](https://en.wikipedia.org/wiki/Windows_Live_Messenger#Discontinuation).
