### ISSUE TITLE
NVDA Hotkey Read current text selection not working with left shift 

### ISSUE THREAD

**Issue by LittleStar-VIP** [nvaccess/nvda#13720]
### Steps to reproduce:
According to the NVDA help file, the hotkey for Read current text selection is NVDA+Shift+upArrow
1. Open word or notepad and type some words.
2. use ctrl+shift+arrow keys to select some of the words
3. press NVDA+LeftShift+upArrow NVDA does not report what is selected
4. press NVDA+RightShift+upArrow NVDA does report what is selected

### Expected behavior:
Pressing either left or right shift should trigger the same function.

#### NVDA installed/portable/running from source:
portable
#### NVDA version:
nvda 2022.1 rc2

#### Windows version:
win 10 home ed 21h2
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
also existed in nvda 2021.3.5
#### If NVDA add-ons are disabled, is your problem still occurring?
this is a clean version without addon
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
not tried

**Comment by CyrilleB79** [comment]
Hello

Very strange.
1. If you use an external keyboard (for laptop) or if you change your keyboard (for desktop PC), do you encounter the same issue?
2. Are there other NVDA gestures contaiing shift that are impacted? E.g. NVDA+shift+D for audio ducking mode.
3. Which nVDA key are you using?

**Comment by LittleStar-VIP** [comment]
> 1. If you use an external keyboard (for laptop) or if you change your keyboard (for desktop PC), do you encounter the same issue?
I am using nvda on my desktop and my keyboard is connected to my pc with usb

> 2. Are there other NVDA gestures contaiing shift that are impacted? E.g. NVDA+shift+D for audio ducking mode.
So far I have not observed any other example.
Say for NVDA+Shift+D, it works on both left and right shift

> 3. Which nVDA key are you using?
I have not set Capslock as NVDA key, and I am using Insert as the NVDA key.

By the way, I try activating input help mode by nvda+1
If I press NVDA+LeftShift+Up arrow, NVDA only say NVDA+LeftShift

**Comment by XLTechie** [comment]
Short of an add-on getting in the way, I have most often observed this when some 
keyboards don't allow certain combinations. It is one reason why it is good to 
always have more than one NVDA key set.

You can try a different keyboard if you have one and see if that solves the 
problem.

**Comment by LittleStar-VIP** [comment]
> some keyboards don't allow certain combinations. 

So @XLTechie you are suggesting that this is a keyboard issue, not a NVDA issue?

I do not have an alternative keyboard to compare, but one of my friend who is using a different brand of keyboard also has the same problem as listed in this issue.

**Comment by XLTechie** [comment]
> So @XLTechie you are suggesting that this is a keyboard issue, not a NVDA issue?

I am suggesting that keyboards are usually the cause of this. Not always, but 
very often.

Have you tried pressing these keys in a different order? Like the shift key 
before the NVDA key, or the other way around?
That can also sometimes make a difference.

You may also check what Narrator input help says for this key 
combination--whether it picks up all of the keys or not.

**Comment by LittleStar-VIP** [comment]
@XLTechie 

> Have you tried pressing these keys in a different order? Like the shift key
before the NVDA key, or the other way around?

I have tried that, but pressing the key combination in different order does not make any difference.

> You may also check what Narrator input help says for this key

I have just tried issuing the same key combination using Narrator, and Narrator was also unable to detect Insert+LeftShift+UpArrow

So do you think I should close this issue?
Thanks.

**Comment by seanbudd** [comment]
This can't be fixed

**Comment by XLTechie** [comment]
> So do you think I should close this issue?

Until you can test with some other keyboard, there's nothing anyone can do, so 
yes you should probably close it.

Though since Narrator doesn't recognize it either, it seems very much that it is 
that your particular keyboard can't generate a code for this combination, but 
another keyboard will probably work.

You can of course remap the gesture for that command to something that does 
work.
