### ISSUE TITLE
Few Heading is read as clickable

### ISSUE THREAD

**Issue by niroshamn** [nvaccess/nvda#13728]
### Steps to reproduce: 
Web application is built using Oracle VBCS. 
<h1 class="hero-header">
              <oj-bind-text value="What would you like to report?"></oj-bind-text>
            </h1>
Section and div are parent of the heading tag. Even with no tabindex, or role="presentation" NVDA reads as clickable.

**Comment by seanbudd** [comment]
Welcome @,

We are unable to process this issue as it stands.

To be able to reproduce this issue, we need a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).
Could you confirm if this is an issue with 2021.3.5?

Kind Regards,
NV Access Software Developers

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since more than one year. i am closing this as abandoned. If you are still having this issue, please provide the requested info and we can reopen.
