### ISSUE TITLE
When UI automation is on, NVDA does not recognize tables in Microsoft Word, especially in browse mode

### ISSUE THREAD

**Issue by Sanjog1605** [nvaccess/nvda#13746]
## Steps to Reproduce
1. Open Microsoft Word document which has tables.
2. Turn on NVDA with UI automation for Microsoft Word documents.
- In NVDA 2022.1 or later, UI automation is turned on by default.
- In earlier versions of NVDA, one needs to turn on UI automation manually by going to NVDA menu > Preferences > Settings > Advance and by checking the check box which says "Use UI automation for Microsoft Word documents".
3. Try reading and navigating the table in Word in browse mode of NVDA.

## Actual Behavior
NVDA does not recognize tables in word documents when UI automation is turned on, especially in browse mode.

## Expected Behavior
NVDA should recognize tables in both focus as well as browse modes.

## System Configuration
- NVDA: Installed
- NVDA Version:  2022.1 (and also 2021.5with UIA enabled)
- Windows Version: Windows 11 Home Version 10.0.22000 Build 22000
- Microsoft Office Version: Microsoft 365 Apps for Enterprise Version  2205 Build 16.0.15225.20172) 64-bit

## Other Details
- The above mentioned issue occurs in earlier versions of NVDA as well but only if UI automation is enabled. I have tested in versions as early as 2021.1.
- The issue remains even after restarting the computer as well as after disabling all the add-ons.
- The issue resolves once UI automation is turn off. This was possible  in NVDA 2021.5 or earlier. In 2022.1, there is no way in which one can disable UI automation.

## Remarks
I use UI automation as I need to read and write STEM content. NVDA recognizes tables in the focus mode even when UI automation is turned on and set as ‘Always’ in case of 2022.1. But in that case, I am unable to use Easy Table Navigator addon to navigate the table, and it is very hard to use Ctrl + Alt + arrow keys for a long time.

**Comment by CyrilleB79** [comment]
Hi @Sanjog1605 

You write:
> 3. Try reading and navigating the table in Word in browse mode of NVDA.

Do you mean that you are using control+alt+arrow gesture to navigate in tables in browse mode and that it does not work for you?

Also, could you please share here a document where the issue occurs so that we can test on the same document as you?

At least, regarding Easy Table Navigator, there is an [issue with UIA table detection](https://github.com/CoBC/easyTableNavigator-1/issues/6). Please, only comment NVDA's issue here and comment the Easy Table Navigator in the dedicated repository. Thanks.

**Comment by Sanjog1605** [comment]
Thank you for your prompt reply and inputs on the behalf of which , I would like to revise my STR. The revised STR are as follows:

## Steps to Reproduce
1. Open a new word document
2. Turn on NVDA with UI automation for Microsoft Word documents.
3. Create a new table  in Microsoft Word.
4. Try reading and navigating the table in Word in browse mode of NVDA.

## Remarks
When we create new table in word document and try to navigate the same table with NVDA in browse mode, it does not recognize the table. On the other hand, if we navigate an already existing table in word, everything works fine. I have not attached any document as one requires to open a fresh word document.

**Comment by seanbudd** [comment]
Potentially related #13078

**Comment by Adriani90** [comment]
This is not the case in NVDA 2023.2 with Office 365 (Version 2308 Build 16.0.16731.20182) 64 Bit.
However, when UIA is set to "always" or "standard", the virtual cursor in browse mode skips empty cells in tables when navigating with arrow keys. I will fill a new ticket for this and close this one.

**Comment by brunoprietog** [comment]
This happened to me many times when working on Word documents at the same time with other people. When I was working on the document without other collaborators it did not happen. It was also frequent when copying tables from Excel to Word. I have not been doing these activities for a long time to check it first hand
