### ISSUE TITLE
NVDA 2022.1 not reporting inputed numbers in Microsoft Word

### ISSUE THREAD

**Issue by LittleStar-VIP** [nvaccess/nvda#13743]
### Steps to reproduce:
1. Open any word file
2. type any number using NumPad and type any number using the number row above QWERT
3. NVDA do not report the numbers that I have entered

I have try doing the same thing using a clean version of nvda (without any addon and with default configuration) and it still produces the same result.

 
#### NVDA installed/portable/running from source:
installed and portable

#### NVDA version:
2022.1
#### Windows version:
windows 10 home ed 21h1

#### Name and version of other software in use when reproducing the issue:
Microsoft 365 Apps for enterprise
16.0.15128.20248
 
#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
this problem doesn't exist when I was using NVDA2021.3.5 yesterday, when I was using the same version of word

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

**Comment by Qchristensen** [comment]
Have you definitely restarted the computer after updating NVDA?  I can't reproduce this on:

Windows 10 (64-bit) Version: 21H2 (2009), Build: 19044.1706 
Office 365 (64-bit) Version: 16.0.15128.20244 
NVDA 2022.1

(Note that in order to type numbers on the number pad, you need to have numlock on)

**Comment by LittleStar-VIP** [comment]
Hello,
Yes.
I just confirmed that if I disabled UIA support for word, the problem disappeared.
