### ISSUE TITLE
[Word->Canvas->Braille->]: Braille is not determining the misspelled/grammatical/advanced proofing errors word.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#13758]
https://user-images.githubusercontent.com/93735775/171300955-51aa6f7c-4937-468e-a10c-778271edf2b5.mp4

### Steps to reproduce:
1. Connect Braille device to the system.
2. Open Word document in the Edge Dev browser.
3. Navigate to the canvas area and navigate to misspelled/grammatical/advanced proofing errors.
4. Braille is not determining the misspelled/grammatical/advanced proofing errors word.

### Actual behavior:
Braille is not determining the misspelled/grammatical/advanced proofing errors word.
NVDA is announcing about the proofing errors but it is not displayed on the Braille viewer.

### Note:
Issue is reproducible for Outlook and PowerPoint as well.

### Expected behavior:
Braille should determine the misspelled/grammatical/advanced proofing errors word with NVDA.

### System configuration:
Windows 11

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA Version 2022.1

#### Windows version:
OS build: 21H2 (OS Build 22000.675)

#### Name and version of other software in use when reproducing the issue:
Edge Version 101.0.1210.53
Word Build: 16.0.15327.41000
Braille Details: Braille Details: Focus 40 Blue/ Model: F40B5 

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by Adriani90** [comment]
@msftedad is this issue still reproducible with NvDA 2024.4 Beta and last version of MS Edge?
Please also make sure that report live regions is enabled in braille grouping of NVDA advanced settings.

**Comment by msftedad** [comment]
Hi @Adriani90, I have checked NVDA 2024.4 beta5 version, Braille display recognizes spelling error information as a flash message.

**Comment by Adriani90** [comment]
Thanks for the update, so I am closing this one as fixed. If there is still an issue, please comment and we can reopen.
