### ISSUE TITLE
Screen reader is not announcing the number of selected links appearing.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#13753]
[NVDA Specific Issues.docx](https://github.com/nvaccess/nvda/files/8803383/NVDA.Specific.Issues.docx)

### Steps to reproduce:
**Pre-requisite:**
1.	Open URL: https://www.bing.com/webmasters on New Edge Browser.
2.	Login using valid credentials. Navigate to Add site manually section.
3.	Add any site manually. Home page appears.

**Repro Steps:**
1. Open URL https://www.bing.com/webmasters on New Edge Browser.
2. Login using valid credentials.
3. Navigate to side navigation bar.
6. Navigate to SEO and Expand it.
7. Navigate to Backlinks and select it.
8. Navigate to Domains under List by section.
9. Turn on NVDA and reach at the table header and click on select all check box.
10. Observe that screen reader is not announcing the number of selected links appearing.

### Actual behavior:
Screen reader is not announcing the number of selected links appearing.

### Expected behavior:
Important messages that indicate some dynamic status can be announced to assistive technology without needing to change focus to that item. This is typically done using aria-live regions.

**[SME Recommendation](url)**
The screen reader must announce the status message when it appears. This can be achieved with the aria-live attribute. 
Additionally, the controls inside the blue status banner should be able to receive focus. 

#### NVDA installed/portable/running from source:
OS: Windows_11
Version: 21H2
OS Build: 22000.194
Browser: New edge (96.0.1054.29)
URL:  https://www.bing.com/webmasters
Screen reader: NVDA 2020.4

#### NVDA version:
NVDA 2020.4

#### Windows version:
OS: Windows_11
Version: 21H2
OS Build: 22000.194

**Comment by seanbudd** [comment]
We are unable to process this issue as it stands.

- To be able to reproduce this issue, we need a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).
- This is very likely a problem with the implementation of the application/website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers
