### ISSUE TITLE
change something and make it bettar in NVDA (speak typed words) ability.

### ISSUE THREAD

**Issue by amirmahdifard** [nvaccess/nvda#13751]
i wanted to give a suggestion, i hope you do that, because it make this ability much bettar: when speak typed words is on, and when we are typing something and pressing a simble, or pressing space, it will read the word that you typed: but, for example, if you want to lissen to that word again, you should bee able to press backspace to remove the simble or the space from after that word, and press space to read the word again: but right now, it is only working in first time, and not more: for example, right now, if you type a word and press space, it will read the word for you, but if you remove the space and press space again, it is not reading for you anymore: please aply this little change to speak typed words ability in NVDA, and thank you. version: 2022.1

**Comment by seanbudd** [comment]
Welcome @amirmahdifard ,

We are unable to process this issue as it stands. Please fill out the [issue template](https://github.com/nvaccess/nvda/issues/new?assignees=&labels=&template=feature_request.md) fully.

Kind Regards,
NV Access Software Developers
