### ISSUE TITLE
 In Browse mode navigation, NVDA focus is going on some blank element before “heading level 1 Help” i

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#13762]
**Help Body:** 
![image](https://user-images.githubusercontent.com/93735775/171584323-1d0b8857-e34b-4c5b-9498-0d440e586795.png)

**Help Settings in the Coherence Header component:**
![image](https://user-images.githubusercontent.com/93735775/171584427-f1956bdb-bad0-4c40-9888-8bde57c021ec.png)

### Steps to reproduce:
 Step 1: Enable NVDA & open the above URL in Edge Chromium browser and login with valid credentials.
Step 2: "Get Connect Device register" Home page will open and by default 'Register Device' will be selected.
Step 3: Navigate to "? icon" (help icon) present in header section & activate it.
Step 4: "Help" dialog will appear.
Step 5: Enable NVDA browser mode with (Insert + Space Key).
Step 6: Navigate inside the dialog with Up/Down arrow key.
Step 7: Verify that NVDA focus is going on some blank element before “heading level 1 Help” or not.
Note: Similarly for "Profile" dialog which appear after activating User profile icon (header section).

### Actual behavior:
(I) In Browse mode navigation, NVDA focus is going on some blank element before “heading level 1 Help”.And also if user further presses Enter Key then the "Help" dialog gets closed.Note: Similar behavior exists in 'Profile' dialog

### Expected behavior:
In Browse mode navigation, NVDA focus should not go on blank element before “heading level 1 Help” after user presses Up arrow key and the NVDA focus should stay on same “heading level 1 Help” and it should announce “heading level 1 Help”.

#### NVDA installed/portable/running from source:
OS: WIN 11 21H2 (OS Build 22000.434)
Browsers: Edge 97.0.1072.62 (Official build) (64-bit)
[https://getconnected.microsoft.com/deviceRegister](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fgetconnected.microsoft.com%2fdeviceRegister&data=04%7c01%7cv-kachau%40microsoft.com%7c2b0e068735a54df51f1908da0aec9835%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637834308745378506%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000&sdata=eMQYRDmKrcFAaSx1dwOuQnK8DA16ULtm39%2BAUU6So6U%3D&reserved=0)

#### NVDA version:
NVDA 2021.3

**Comment by seanbudd** [comment]
We are unable to process this issue as it stands.


- Many developers, contributors and community members here are vision impaired. Screenshots are not accessible. Provide an alternative description, and capture any relevant information from images.
- To be able to reproduce this issue, we need a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).

Kind Regards,
NV Access Software Developers
