### ISSUE TITLE
Improved Paragraph Navigation

### ISSUE THREAD

**Issue by rob-aph** [nvaccess/nvda#13797]
### Is your feature request related to a problem? Please describe.
NVDA needs a more flexible way to deal with navigating between paragraphs, especially block paragraphs, in text editors. Such navigation makes skimming through material in search of the desired content much more efficient than navigation options currently available.
### Describe the solution you'd like
I have begun development of a patch to allow three different styles of paragraph navigation:
1. Handled by application. (This is the paragraph style currently supported by NVDA, and is the default setting in my proposal. It requires that the application in use do something reasonable when pressing Control+UpArrow, and Control+DownArrow.)
2. Normal style. (This setting allows NVDA to navigate between paragraphs marked by a single press of Enter. NVDA does the work of determining the next and previous paragraph, so cooperation from the running application is unnecessary. This setting gives basic paragraph navigation to editors which do not support this feature.)
3. Block style. (This setting allows navigation between paragraphs which are delimited by one or more blank lines. NVDA determines the previous and next paragraph as in the Normal style setting, so cooperation from the application is unnecessary.)

My solution adds a settings panel called Paragraph Navigation. The panel contains a single combo box allowing selection of the desired paragraph style. (I tried to find a place in the existing panels for this setting, but nothing seemed right to me.)

Draft pull request to follow shortly, let's discuss!

**Comment by cary-rowen** [comment]
This is a good feature, but I wonder if it can be related to #8518, assuming we add a "reading" category to the NVDA settings panel
