### ISSUE TITLE
NVDA crashes in Visual Studio 2010 Professional

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1380]
**Reported by ianr on 2011-02-19 18:13**
Sometimes NVDA will crash while in VS 2010.  I notice this when trying to move the cursor with the arrow keys and NVDA is no longer reading.

Generally Visual Studio will become unresponsive for about 30 seconds during which time I go to task manager and see that nvda is still running for the next 30 seconds or so, then it crashes and Visual Studio becomes responsive again.

This crashing generally happens between 5 and 10 times in an 8 hour period of using Visual Studio.

It also used to happen in older versions of nvda such as 2010.2 and 2010.1.

I have attached the log file taken from my %temp% folder.
Unfortunately log level was set to info at the time.
I will set my log level to debug and see if I can get a better log to attach.

**Comment by bhavyashah** [comment]
Could users of more recent versions of Visual Studio test and let us know if these frequent crashes with NVDA still take place? If not, I suggest closing this ticket as worksforme or invalid.

**Comment by Adriani90** [comment]
@ianr is this issue still reproducible?

**Comment by Adriani90** [comment]
@francipvb, @JulienCochuyt do you know by chance if this is still occuring in VS Studio 2010 or newer versions? This is a prety old issue and we lost contact to the initial author.

**Comment by JulienCochuyt** [comment]
> @francipvb, @JulienCochuyt do you know by chance if this is still occuring in VS Studio 2010 or newer versions? This is a prety old issue and we lost contact to the initial author.

I don't know.
I was not yet a full-time NVDA user when I intensively worked with VS 2010.
I fully switched only around 2015.3 and was back to Eclipse at the time.
My recent uses of VS 2012 & 2015 with newer NVDA were not problematic, but nothing heavy on resource consumption, so I can't tell.

**Comment by leonardder** [comment]
I haven't seen this issue in recent versions of Visual Studio. Given we seem to be unable to contact the original author, I'm closing this.
