### ISSUE TITLE
Continuous reading suspends pc on windows 11 using kindle

### ISSUE THREAD

**Issue by ericdq** [nvaccess/nvda#13809]
When I am reading in Windows 11 with continuous reading on Kindle desktop, when the time configured in the system is reached, the pc is suspended.
I don't know if the same thing happens in other applications.

**Comment by seanbudd** [comment]
Welcome @ericdq ,

We are unable to process this issue as it stands.
Please fill out the issue template fully.

Kind Regards,
NV Access Software Developers

**Comment by Adriani90** [comment]
Closing since the template is not filled. Please fill the template with all details of this issue, reproduce it with NVDA 2024.1 and Kindle 2.3.5.
