### ISSUE TITLE
Outlook 365: Text on Braille display not being updated while typing on computer keyboard

### ISSUE THREAD

**Issue by DGartmann** [nvaccess/nvda#13808]
### Steps to reproduce:
- Go to Outlook.
- Create a new e-mail message.
- Go to the body of the message
- Type some text on the keyboard on the computer.
- Take your hands to the Braille display and try to read the text that has just been entered from the keyboard without using the pannning keys on the Braille display.

### Actual behavior:
When writing text in the message body of a new message, text is being spoken but no change happens on the Braille display i.e. no new text is being shown. The contents on the Braille display is only updated when I press either the Left or the Right arrow key on the computer keyboard or one of the panning keys on the Braille display. This makes reading text on the display cumbersome because it requires more key presses than should be necessary. 

### Expected behavior:
The text on the Braille display should be updated as text is being entered.

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
Both tested with 2022.1 and 2022.2 beta 1 
Connected Braille display either via USB or Bluetooth: HumanWare BI x 40 runnning latest firmware version 2.

#### Windows version:
Windows 10 21H2 (10.0.19044) workstation

#### Name and version of other software in use when reproducing the issue:
Microsoft Outlook 365 as follows:
appModule.productName: 'Microsoft Outlook'
appModule.productVersion: '16.0.15225.20204'

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by DGartmann** [comment]
With NVDA 2022.3 beta 5, possibly earlier versions as well, this problem has disappeared. Not sure why but I wanted to report it here.

**Comment by seanbudd** [comment]
Can you confirm this is also fixed on alpha?
If this is fixed in 2022.3 and alpha you or I should close this as fixed

**Comment by DGartmann** [comment]
Fixed in alpha. Just tested it with NVDA version alpha-26682,79480085

**Comment by DGartmann** [comment]
Therefore closing this issue.
