### ISSUE TITLE
Emojis show as garbage characters in Braille

### ISSUE THREAD

**Issue by TheQuinbox** [nvaccess/nvda#13802]
### Steps to reproduce:
Read the following text with a Braille Display:
This👏is👏a👏test
### Actual behavior:
Random characters are shown on the braille display where ever the emojis show.
### Expected behavior:
Replacements should be shown on the braille display for emojis, and/or they should be filtered out. The current system is extremely disruptive to braille reading.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2022.1
#### Windows version:
Windows 10 21H2 (x64) build 19044.1706
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
Processor: AMD Ryzen 9 5950X 16-Core Processor, 3401 Mhz, 16 Core(s), 32 Logical Processor(s)
RAM: 128 GB
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/a

**Comment by seanbudd** [comment]
Perhaps these should be replaced by "emoji" or "emj", so that they can be read in further details by executing a script

**Comment by TheQuinbox** [comment]
I actually really like how Braille Extender handles this.

**Comment by seanbudd** [comment]
@TheQuinbox - how does braille extender handle this?

**Comment by ABuffEr** [comment]
Hi,
I agree with @TheQuinbox , BrailleExtender is a must for me, thanks to its option that expands hex coding to [emoji description], got from NVDA symbol description (even if customized). But it may be too long for many users.
