### ISSUE TITLE
Regression: Attempt to import wrong appModule

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#13813]
### Steps to reproduce:
1. Enable loading custom code from Developer Scratchpad directory;
2.Try to create a new empty file qq.py in scratchpad/appModules;
3. Now feel free to start an application named '6.5.qq.exe' with a GUI;

### Actual behavior:
You get a bunch of errors and NVDA can't report anything in the application;
Error log attached: [NVDA.log](https://github.com/nvaccess/nvda/files/8933578/NVDA.log)

### Expected behavior:
NVDA can read the application normally, consistent with the 2022.1 behavior.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2022.2Beta1
#### Windows version:
Windows 10 21H2 (x64) build 19044.1766
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2022.1 can work well
#### If NVDA add-ons are disabled, is your problem still occurring?
No(but this has nothing to do with any of the add-ons)
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by cary-rowen** [comment]
Note that this may be related to #13366

**Comment by lukaszgo1** [comment]
@cary-rowen Would you mint uploading the 6.5.qq.exe application, so I can try to reproduce on my machine?

**Comment by cary-rowen** [comment]
Hi, @lukaszgo1 
The following is a sample application, it is safe, please feel free to test this.
[6.5.qq.exe.zip](https://github.com/nvaccess/nvda/files/8934527/6.5.qq.exe.zip)

**Comment by lukaszgo1** [comment]
@cary-rowen Please try with [this build](https://ci.appveyor.com/api/buildjobs/6q8yjlgvh8i8c91v/artifacts/output%2Fnvda_snapshot_pr13814-25626%2Cddc56c85.exe).

**Comment by cary-rowen** [comment]
Hi, @lukaszgo1 
I can confirm that #13814 fixes this issue.
Thanks

**Comment by cary-rowen** [comment]
Fixed by #13814
