### ISSUE TITLE
when navigating on result table in Oracle Developer Tools for VS Code, Nvda repeats every column 3 times.

### ISSUE THREAD

**Issue by hamidrezaabroshan** [nvaccess/nvda#13825]
### Steps to reproduce:
on VS CODE, install Oracle Developer Tools for VS Code  extension.
press F6 key til go to active view switcher.
select Oracle Developer Tools for VS Code  and press enter and create a new connection.
then connect to the db and import some data and execute some query on it.
Tip: sid and serviceName does not different in this context for creating connection and it will work with both.
for performing query, you should press enter on Oracle Developer Tools for VS Code  in active view switcher toolbar and press tab until hear connections. press application key on connections and select new sql file.
after writing sql, press ctrl+r to execute the query and press alt+k followed by alt+left or write to jump to the results.
in results page, by tabbing, you will find result table.
### Actual behavior:
when navigating through table, it will repeat every column or row for 3 times.

### Expected behavior:
reading every column in a row for 1 time is enough.

### System configuration
Nvda 2022.1 installed.

#### Windows version:
Microsoft Windows
Version 21H2 (OS Build 19044.1766)
#### Name and version of other software in use when reproducing the issue:
Oracle Developer Tools for VS Code  
Version 21.4.0
Visual Studio Code

Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z (1 wk ago)
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0

**Comment by shadyar** [comment]
I experienced exactly the same behavior by NVDA the latest stable version.

**Comment by seanbudd** [comment]
Welcome @hamidrezaabroshan ,

We are unable to process this issue as it stands.

- This is very likely a problem with the implementation of the application/website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers

**Comment by Adriani90** [comment]
@hamidrezaabroshan, @shadyar are you still having this issue with NVDA 2023.1 and last Chromium version?

**Comment by Adriani90** [comment]
cc: @isidorn

**Comment by shadyar** [comment]
Unfortunately there is The problem still in Oracle Developer Tools for VS Code, even while navigating by new version of NVDA.

**Comment by shadyar** [comment]
Thanks for your attention.
@Adriani90

**Comment by Adriani90** [comment]
@shadyar could you please answer my question above? Are you still having this issue with NVDA 2024.4.1?

**Comment by Adriani90** [comment]
We didn't get an update since more than 1 year from the initial author on whether this issue still exists or not, although we repeatedly requested an update. Closing as abandoned. If you are still having this issue, please comment with updated test results and we can reopen.
