### ISSUE TITLE
latency in navigation with the AutoIt GUI controls

### ISSUE THREAD

**Issue by rmcpantoja** [nvaccess/nvda#13833]
### Steps to reproduce:
1. Make sure you have NVDA running.
2. Run some Script, example or something that is where a GUI has to be shown, we have many examples from the AUtoIt help file.
3. Start navigating with the controls in that window. 
### Actual behavior:
[AutoIt](https://autoitscript.com) is a language for both scripting and programming, which in addition to a series of automation functions allows the creation of graphical interfaces (GUIS) the behavior in these GUIS, such as the In the case of NVDA, it has latency when navigating the controls when pressing the keys while we are navigating, and even more latency so if the GUI has several controls.
### Expected behavior:
Latency in navigation in GUI controls was expected to be real-time as it is in navigation in Windows Explorer, for example.
#### NVDA installed/portable/running from source:
in all three distributions. Portable, installed, source.
#### NVDA version:
This happened forever, even until 2022.2beta2 or the alpha
#### Windows version:
Windows 11 21H2 (x64) build 22000.739
#### Name and version of other software in use when reproducing the issue:
AutoIt v3, currently version 3.3.16.1
#### Other information about your system:
12 gigabits of RAM, 8-core CPU, 2.2 gigahertz.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
During these two years that I have been programming with AutoIt, from 2022 to today, the same thing continues to happen. I have even tested with 2017.3 and the behaviors are the same, even in old versions.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes
### More information about this issue. Source: autoit forums, where several blind users over time have been commenting on this.

[GUI is very sluggish with keyboard navigation and screen reader](https://www.autoitscript.com/trac/autoit/ticket/1199)
[Responsiveness Of AutoIt GUI's With Screen Readers](https://www.autoitscript.com/forum/topic/157089-responsiveness-of-autoit-guis-with-screen-readers/)
[Accessibility issue with the large sleep in AutoIt GUI message loop](https://www.autoitscript.com/forum/topic/193009-accessibility-issue-with-the-large-sleep-in-autoit-gui-message-loop/)
[Slow performance of autoit GUI](https://www.autoitscript.com/forum/topic/188261-slow-performance-of-autoit-gui/)

**Comment by seanbudd** [comment]
As described in these forum posts, and notably the fact this has been reported for multiple screen readers, this is a problem with AutoIT GUI. 
Please direct feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers
