### ISSUE TITLE
All buttons are reading as "Text Button Text" intead of "Text Button" (e.g. "Main Menu" button "Main menu").

### ISSUE THREAD

**Issue by prajwalmanju** [nvaccess/nvda#13831]
### Steps to reproduce:
1) Enable NVDA Screen Reader
2) Focus on the any adaptive card button.
3) observe the screen reader input.
 
### Actual behavior:
While focusing on the adaptive card NVDA screen reader reading button text as "Text Button Text" (e.g. Share Una Feedback Button Share Una feedback) 

### Expected behavior:
While focusing on any adaptive card button it should read it as "Text Button" (e.g. Share Una feedback Button)

#### NVDA installed/portable/running from source:
Windows 10

#### NVDA version:
2022.1

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes I tried with NVDA 2021.1 version as well same issue in both the versions.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by lukaszgo1** [comment]
Please provide a minimal reproducible HTML example using CodePen or similar tool. Without a MWE this issue cannot be progressed.

**Comment by prajwalmanju** [comment]
we are using JSON to create cards, is it fine if we share JSON example along with screen recording of the repro ?

**Comment by lukaszgo1** [comment]
It is pretty likely the issue is with the Adaptive Cards rather than with NVDA. Would you be able to right click the created button, choose inspect and copy the HTML markup for the button here?

**Comment by prajwalmanju** [comment]
Hello Team,

In Narrator screen reader button text is reading as expected, we are facing the issue while using NVDA screen reader.

Please find the HTML sample below.

<div data-is-focusable="true" tabindex="0" role="group" aria-labelledby="important-1655885629996 badge-1655885629996 read-status-icon-1655885629996 content-1655885629996 author-1655885629996 attachments-1655885629996 timestamp-1655885629996 edited-1655885629996" data-last-visible="false" data-mid="1655885629996" data-tid="chat-pane-message" data-tabster="{&quot;uncontrolled&quot;: {}}" class="ms-FocusZone ui-chat__message gz ha hb ce hc hd he hf hg hh hi hj hk hl hm hn ho hp hq hr hs ht hu hv hw hx hy hz ia ib ic id ie if ig ih ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc gw jd je jf jg jh ji jj jk ey ez fb fd jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp ui-animation gx gy cc focused" data-focuszone-id="FocusZone47"><div class="ui-box dc dd de df dg dh bu di dj dk dl dm dn" style="position: absolute;"><button tabindex="-1" class="ui-button afb aeb afc kq jk gz zk bp bq ce ve fi fj vf vs zl zm xb afd hb wh wi wj wk wd we wf wg xs xt xu xv zq zr afe aff afg afh afi afj afk afl afm afn he hj hk hl hm hn ho hp aca hr hs ht hu hv hw hx hy hz acb acc acd ace ie if ig ih ii ij ik acf im in io ip iq ir is it iu acg ach aci acj abw abx aby abz acm acn aco acp ww afo" data-is-focusable="false" aria-expanded="false" data-tid="message-actions-menu-hidden-button" aria-label="Toolbar with two buttons, press enter to enter toolbar"></button></div><div class="ui-chat__message__bar"></div><div class="ui-chat__messageheader"><span class="ui-text gd ge kq kr ks kt ui-chat__message__author"><span class="ui-text" dir="auto" data-tid="message-author-name" id="author-1655885629996">UnaBot QA</span></span><time class="ui-text gd ge gb ha kt ui-chat__message__timestamp" dir="auto" aria-label="Today at 1:43 PM." datetime="2022-06-22T08:13:49.996Z" id="timestamp-1655885629996" title="Today at 1:43 PM">1:43 PM</time><div class="ui-chat__messagedetails gb ha gd vn"><div class="ui-flex bo vo"><span class="ui-text gd ge gb" dir="auto" id="edited-1655885629996" aria-label="Edited Today at 1:44 PM" title="Edited Today at 1:44 PM">Edited</span></div></div></div><div class="ui-flex bo"></div><div class="ui-box ku cz kq cd kv kw kx ky kz kx la lb lc ld le lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz ma mb mc md me mf mg mh mi mj mk ml mm mn mo mp mq mr ms mt mu mv mw mx my mz na nb nc nd ne nf ng nh ni nj nk nl nm nn no np nq nr ns nt nu nv nw nx ny nz oa ob oc od oe of og oh oi oj ok ol om on oo op oq or os ot ou ov ow ox oy oz pa pb pc pd pe pf pg ph pi pj pk pl pm pn po pp pq pr ps pt pu pv pw px py pz qa qb qc qd qe qf qg qh qi qj qk ql qm qn qo qp qq qr qs qt qu qv qw qx qy qz ra rb rc rd re rf rg rh ri rj rk rl rm rn ro rp rq rr rs rt ru rv rw rx ry rz sa sb sc sd se sf sg sh si sj sk sl cu sm sn so sp sq sr ss st su sv sw sx sy sz ta tb tc td te tf tg th ti tj tk tl tm tn to tp tq tr ts tt ui-chat__message__content" id="content-1655885629996" aria-label="" dir="auto"><div class="ui-flex bo br bdd bde"><ul role="list" class="ui-list cd fe ve fi fj vf eo vh eq gw"><li role="listitem" class="ui-list__item bo bq bdf ve fi fj vf bdg bdh bdi gp bdj bdk bdl"><div class="ui-list__item__main bo br db jf"><div class="ui-list__item__contentWrapper bo"><div class="ui-list__itemcontent db gd ge bdm"><div class="ui-flex bo bde ce ao"><div class="ui-box he bde bdn cd ce ao bdo bdp bdq bdr bds bdt bdu bdv bdw bdx bdy bdz bea beb bec bed bho bhp beg beh bei" aria-label=" This is a card message. Your language is changed to English. To explore all features, click go to main menu." data-is-focusable="true" title="" tabindex="-1"><div class="ui-flex bo br bej cu wb yu bek bel baw wg bem bau we ben bav wf beo eo vh eq gw fm jh bep jg ao beq"><div class="ui-box bfc bfd bfe bff bfg bfh bfi bfj bfk bfl bfm bfn bfo bfp bfq" data-tid="adaptive-card"><div class="ac-container ac-adaptiveCard" tabindex="-1" aria-label="Your language is changed to English. To explore all features, click go to main menu." style="display: flex; flex-direction: column; justify-content: flex-start; box-sizing: border-box; flex: 0 0 auto; padding: 1.6rem; margin: 0px; background-color: rgb(255, 255, 255);"><div class="ac-textBlock" style="overflow: hidden; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; font-size: 14px; color: rgb(31, 31, 31); font-weight: 400; text-align: start; line-height: 18.62px; overflow-wrap: break-word; box-sizing: border-box; flex: 0 0 auto;"><p style="margin-top: 0px; width: 100%; margin-bottom: 0px;">Your language is changed to English. How may I help you?</p>
</div><div class="ac-horizontal-separator" aria-hidden="true" style="height: 12px; overflow: hidden; flex: 0 0 auto;"></div><div><div style="overflow: hidden;"><div class="ac-actionSet" role="menubar" style="display: flex; flex-flow: row wrap; justify-content: flex-start; margin: -2px;"><button class="ui-button acs jf ao vl jk gz zk bp bq ce ve bfr fj bfs vs zl zm xb bao hb wh wi wj wk wd we wf wg bft bfu bfv bfw bfx bfy bfz bga bgb bgc afg afh afi afj afk afl afm afn he hj hk hl hm hn ho hp aca hr hs ht hu hv hw hx hy hz acb acc acd ace ie if ig ih ii ij ik acf im in io ip iq ir is it iu acg ach aci acj bgd bge abw abx aby abz acm acn aco acp bgf bgg bgh bgi kr aet bgj bgk afr bgl bgm bgn bgo bgp bgq bgr bgs bgt bgu" title="Go to main menu" tabindex="-1"><span class="ui-text bu bgv bar" dir="auto">Go to main menu</span></button><div></div><button class="ui-button acs jf ao vl jk gz zk bp bq ce ve bfr fj bfs vs zl zm xb bao hb wh wi wj wk wd we wf wg bft bfu bfv bfw bfx bfy bfz bga bgb bgc afg afh afi afj afk afl afm afn he hj hk hl hm hn ho hp aca hr hs ht hu hv hw hx hy hz acb acc acd ace ie if ig ih ii ij ik acf im in io ip iq ir is it iu acg ach aci acj bgd bge abw abx aby abz acm acn aco acp bgf bgg bgh bgi kr aet bgj bgk afr bgl bgm bgn bgo bgp bgq bgr bgs bgt bgu" title="Share Una feedback" tabindex="-1"><span class="ui-text bu bgv bar" dir="auto">Share Una feedback</span></button></div></div><div></div></div></div></div></div></div></div></div></div></div></li></ul></div></div><div class="ui-chat__messagereadstatus tw dn tx ty tz ua ub uc ud ue uf ug uh ui uj uk ul um un uo up bo"></div></div>


Thanks!

**Comment by prajwalmanju** [comment]
Hello Team,

Please find the attachment for HTML sample
[HTML sample.txt](https://github.com/nvaccess/nvda/files/8957128/HTML.sample.txt)
.

**Comment by prajwalmanju** [comment]
Hello Team,

Greetings of the day!

A gentle follow up to check if there is any update on this issue ?

I have attached the requested HTML sample via previous chat, please let me know if you need any additional details.

Thanks!

**Comment by prajwalmanju** [comment]
Hello Team,

Greetings of the day!

A gentle follow up to check if there is any update on this issue ?

Thanks!

**Comment by prajwalmanju** [comment]
Hello Team,

Greetings of the day!

A gentle follow up to check if there is any update on this issue ?

Thanks!

**Comment by seanbudd** [comment]
@prajwalmanju - thank you for providing the required information to investigate. There are over 2000 open issues. When we get a chance to investigate further, we will let you know on this issue.

**Comment by michaelDCurran** [comment]
I cannot reproduce this.
I have tried the html sample with Firefox, Chrome and Edge.
I do not get double speaking of the button label when:
* Arrowing to it in browse mode
* Jumping to it with single letter quick navigation (E.g. b for button)
* Reporting current navigator object.

If this issue is still present in the current stable version of NVDA, and you can provide clearer steps to reproduce, please reopen the issue.
