### ISSUE TITLE
Send dashes to the synthesizer by default

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#13830]
### Steps to reproduce:
1. Set NVDA to use OneCore and one of the English voices. Mark will work.
2. You'll need to reset your punctuation/symbols to defaults, unless you know you haven't modified the -. There's no way to do this from the GUI, so back up or delete symbols_en.dic manually.
3. Set symbol level to some.
4. Read the following: Jean-Luc Picard, 1950-1960
5. Change Preserve of - to always and read them again.

### Actual behavior:
I hear Jean Luc Picard, and 1950 1960
### Expected behavior:
The synthesizer knows what it's doing here, so I want to hear these pronounced correctly.
This should also apply to —. – is set to always by default, so should be fine.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2022.1
#### Windows version:
Windows 10 X64 Version 21H1 (OS Build 19043.1766)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment]
Hi @tspivey 

The example "Jean-Luc Picard" seems to be pronounced correctly to me.
You have taken the "New feature" template, but you are actually describing an incorrect behaviour of the existing symbol reporting feature. Would you mind use the bug report template instead and fill it adequately?

And describe:
* The symbol level used
* What you actually hear
* What you want to hear

Thanks.

**Comment by tspivey** [comment]
Description updated. Personally I use only below symbol's level, but I used always for consistency with the rest of the punctuation (parentheses, …, etc).

**Comment by TheQuinbox** [comment]
Only issue with this is that it breaks when reading certain code blocks. For example:
```go
x := 5
x -= 2
```
When having dashes passed to the synthesizer, these two lines sound almost the exact same, in terms of the pauses.

**Comment by tspivey** [comment]
Programmers have enough knowledge to adjust their punctuation exactly the way they want, and NVDA gives them the tools to do so. I just want better defaults.
