### ISSUE TITLE
It is sometimes not possible to complete certain HTML forms, such as activating a button to complete a search when using NVDA and Seamonkey.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1384]
**Reported by dgoldfield on 2011-02-21 19:59**
On certain Web pages where I am filling out information in a form it is sometimes not possible to activate the link or button which completes or submits the information in the form.  This is not consistent; with Google everything works fine.  I noticed this with AFB's message boards at www.afb.org. After typing the text of the message there is an "add" button and pressing enter or spacebar on this button did not seem to allow me to complete the form and the page did not change.  With IE 8.0 this did not happen and all worked well.  h

**Comment by bhavyashah** [comment]
@dgoldfield  Could you please respond to https://github.com/nvaccess/nvda/issues/1384#issuecomment-155287903 and let us know if you are still experiencing this problem? If David responds in the negative or we do not hear from him within a week or two, I would suggest closing as worksforme. @ehollig

**Comment by ehollig** [comment]
If this problem still exists, we can reopen this issue. Closing as worksforme
