### ISSUE TITLE
NVDA skip on empty TH cells in PDF files

### ISSUE THREAD

**Issue by toovyaShenfled** [nvaccess/nvda#13866]
when I have pdf table that the first cell of the table is empty, NVDA not read it and read the secound cell as the first one.
everything in the PDF tag as it should be.

Is anyone ancounter this?
anyone know a solution for this?

Thanks.

**Comment by seanbudd** [comment]
Welcome @toovyaShenfled ,

We are unable to process this issue as it stands. Please either update your issue or open a new issue.

- Please fill out the issue template fully.
- To be able to reproduce this issue, we need a sample. Provide an example PDF file
- It is unclear what software you are using. What are you using to read the PDF? What version of the software?

Kind Regards,
NV Access Software Developers
