### ISSUE TITLE
VSCode 1.69.0 becomes totally inaccessible when Alt Tabbing to another browser

### ISSUE THREAD

**Issue by mmfarahmand** [nvaccess/nvda#13884]
With the release of VSCode 1.69.0, Whenever I Alt Tab to another browser such as Edge or Firefox and come back to VSCODE again, It's totally inaccessible.
I should add that this issue doesn't exist in VSCode 1.68.1 (The previous version).

### Steps to reproduce:
1. Grab VSCode 1.69.0 and open it.
2. Now open up Firefox or any chromium based browsers (I tested with Edge and Brave).
3. Now come back to VSCode with Alt+Tab keys or your prefered method.

### Actual behavior:
* NVDA does not read anything in VSCode. Even the menus!

### Expected behavior:
* NVDA should be able to read VSCode user interface.

#### NVDA installed/portable/running from source:
* installed

#### NVDA version:
* 2022.1

#### Windows version:
* Windows 10 21H2 (x64) build 19044.1766

#### Name and version of other software in use when reproducing the issue:
* VSCode 1.69.0

#### Does the issue still occur after restarting your computer?
* Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
* No

#### If NVDA add-ons are disabled, is your problem still occurring?
* Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
* Yes

**Comment by cary-rowen** [comment]
Yes, I reproduced this. This is really urgent.

**Comment by cary-rowen** [comment]
I reproduced this using VS Code 1.69.0 with NVDA alpha-25756 and the logs are attached.
[log.txt](https://github.com/nvaccess/nvda/files/9077567/log.txt)

**Comment by steverep** [comment]
I have the same issue.  Note that it is not specific to VS Code 1.69.0 and also occurs with the insiders edition currently at 1.70.0.

**Comment by steverep** [comment]
This appears to be a known bug in VS Code related to Electron that was caught in the insiders edition but still made it to stable.  There is a workaround to add a flag when starting code.  See microsoft/vscode#152291.

**Comment by bramd** [comment]
Based on the VS Code bug, I would say this bug is not in NVDA and needs an external fix?

**Comment by seanbudd** [comment]
Closing as this is an issue with VS Code
