### ISSUE TITLE
NVDA - v-select reads blank on focus

### ISSUE THREAD

**Issue by Ben-SMS** [nvaccess/nvda#13887]
### Steps to reproduce:

Using NVDA 2021.3.5
Given v-select as Country list with selected item "Texas"
Tab to a v-select 

### Actual behavior:

NVDA reads Blank at the end: "Texas Menu button collapsed, sub-menu, Country, Required, **Blank**"

### Expected behavior:

NVDA shouldn't read Blank at the end

#### NVDA version:
2021.3.5
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Vuetify 2.2.11
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, the same issue

**Comment by seanbudd** [comment]
Welcome @Ben-SMS ,

We are unable to process this issue as it stands.

What is a v-select? This appears related to an npm package, Vue / Vue-Select, as a starting point please submit feedback to the authors to let them know about the problem.

To be able to reproduce this issue, we need a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).

Kind Regards,
NV Access Software Developers

**Comment by seanbudd** [comment]
You can report the issue on the Vuetify GitHub project: https://github.com/vuetifyjs/vuetify/issues

**Comment by Ben-SMS** [comment]
The issue has been reported on the Vuetify GitHub. Thanks Sean!
