### ISSUE TITLE
System tests fail with fresh OS install

### ISSUE THREAD

**Issue by peluse** [nvaccess/nvda#13894]
Using Master and a fresh install of latest Win 11, VS2022, following the directions on github to the letter I can build and pass UT but systems tests fail as follows: (no other apps/windows open, no user interaction during tests):

<details>
  <summary>system tests output</summary>

    C:\Users\Paul\nvda>runsystemtests.bat
    Ensuring NVDA Python virtual environment
    call py -m robot --argumentfile "C:\Users\Paul\nvda\tests\system\robotArgs.robot"  "C:\Users\Paul\nvda\tests\system\robot"
    ==============================================================================
    Robot
    ==============================================================================
    Robot.chromeTests :: HTML test cases in Chrome
    ==============================================================================
    checkbox labelled by inner element :: A checkbox labelled by an in... | PASS |
    ------------------------------------------------------------------------------
    Announce list item when moving by word or character :: Entering a ... | PASS |
    ------------------------------------------------------------------------------
    i7562 :: List should not be announced on every line of a ul in a c... | PASS |
    ------------------------------------------------------------------------------
    pr11606 :: Announce the correct line when placed at the end of a l... | PASS |
    ------------------------------------------------------------------------------
    ARIA treegrid :: Ensure that ARIA treegrids are accessible as a st... | PASS |
    ------------------------------------------------------------------------------
    ARIA checkbox :: Navigate to an unchecked checkbox in reading mode.   | PASS |
    ------------------------------------------------------------------------------
    Marked Browse mode :: Ensure that Marked content is read in browse... | PASS |
    ------------------------------------------------------------------------------
    Marked Focus mode :: Ensure that Marked content is read in Focus mode | PASS |
    ------------------------------------------------------------------------------
    ARIA details :: Ensure a summary of aria-details is read on comman... | PASS |
    ------------------------------------------------------------------------------
    ARIA details with free review and nav :: Variation on the ARIA det... | PASS |
    ------------------------------------------------------------------------------
    ARIA details noVbuf :: Test for retrieving ARIA details from a but... | PASS |
    ------------------------------------------------------------------------------
    ARIA details noVbuf with free review and nav :: Test for retrievin... | PASS |
    ------------------------------------------------------------------------------
    i12147 :: New focus target should be announced if the triggering e... | PASS |
    ------------------------------------------------------------------------------
    Table in style display: table :: Properly announce table row/colum... | PASS |
    ------------------------------------------------------------------------------
    ARIA roleDescription focus :: report focusing an element with a cu... | PASS |
    ------------------------------------------------------------------------------
    ARIA roleDescription inline browse mode :: Read an inline element ... | PASS |
    ------------------------------------------------------------------------------
    ARIA roleDescription block browse mode :: Read a block element wit... | PASS |
    ------------------------------------------------------------------------------
    ARIA roleDescription inline content editable :: Read an inline ele... | PASS |
    ------------------------------------------------------------------------------
    ARIA roleDescription block content editable :: Read an block eleme... | PASS |
    ------------------------------------------------------------------------------
    ARIA description Focus Mode :: Navigate to a span with aria-descri... | PASS |
    ------------------------------------------------------------------------------
    ARIA description Browse Mode :: Navigate (down arrow, in browse mo... | PASS |
    ------------------------------------------------------------------------------
    ARIA description Say All :: Say all, contents includes aria-descri... | PASS |
    ------------------------------------------------------------------------------
    i10840 :: The name of table header cells should only be conveyed o... | PASS |
    ------------------------------------------------------------------------------
    Prevent Duplicate Speech From Description while in Focus mode         | PASS |
    ------------------------------------------------------------------------------
    Prevent Duplicate Speech From Description while in Browse mode wit... | PASS |
    ------------------------------------------------------------------------------
    Only report description in focus mode due to reportObjectDescripti... | PASS |
    ------------------------------------------------------------------------------
    Quick Nav reports target first :: Quick Nav target should always b... | PASS |
    ------------------------------------------------------------------------------
    Focus reports target first :: Focus target should always be report... | PASS |
    ------------------------------------------------------------------------------
    Table navigation with merged columns :: When navigating through a ... | PASS |
    ------------------------------------------------------------------------------
    focus mode is turned on on focused read-only list item :: Focused ... | PASS |
    ------------------------------------------------------------------------------
    ARIA details role :: Test aria details roles being announced on di... | PASS |
    ------------------------------------------------------------------------------
    Robot.chromeTests :: HTML test cases in Chrome                        | PASS |
    31 critical tests, 31 passed, 0 failed
    31 tests total, 31 passed, 0 failed
    ==============================================================================
    Robot.startupShutdownNVDA :: Basic start and exit tests
    ==============================================================================
    Starts :: Ensure that NVDA can start                                  | PASS |
    ------------------------------------------------------------------------------
    Starts from desktop shortcut :: Ensure that NVDA can start from de... | PASS |
    Desktop shortcut only exists on installed copies
    ------------------------------------------------------------------------------
    Quits from keyboard :: Starts NVDA and ensures that it can be quit... | PASS |
    ------------------------------------------------------------------------------
    Quits from keyboard with welcome dialog open :: Starts NVDA and en... | PASS |
    ------------------------------------------------------------------------------
    Quits from menu :: Starts NVDA and ensures that it can be quit usi... | PASS |
    ------------------------------------------------------------------------------
    Read welcome dialog :: Ensure that the welcome dialog can be read ... | PASS |
    ------------------------------------------------------------------------------
    Restarts :: Ensure that NVDA can restart from keyboard                | PASS |
    ------------------------------------------------------------------------------
    Restarts on crash :: Ensure NVDA restarts on crash.                   | FAIL |
    A crash.dmp file has not been generated after a crash
    ------------------------------------------------------------------------------
    Restarts on braille crash :: Ensure NVDA restarts on a crash on th... | FAIL |
    A crash.dmp file has not been generated after a crash
    ------------------------------------------------------------------------------
    Restarts on UIAHandler crash :: Ensure NVDA restarts on crash on t... | FAIL |
    A crash.dmp file has not been generated after a crash
    ------------------------------------------------------------------------------
    Robot.startupShutdownNVDA :: Basic start and exit tests               | FAIL |
    10 critical tests, 7 passed, 3 failed
    10 tests total, 7 passed, 3 failed
    ==============================================================================
    Robot.symbolPronunciationTests :: Symbol pronunciation tests
    ==============================================================================
    symbolInSpeechUI :: Ensure symbols aren't substituted within NVDA ... | FAIL |
    actual vs expected. Unexpected speech when moving to final character.: ['shouldn tick t sub tick symbol\nt'] != ['blank']
    ------------------------------------------------------------------------------
    moveByWord :: Ensure symbols announced as expected when navigating... | FAIL |
    actual vs expected. With symbolLevel SymLevel.NONE: ['colon', 'Say', 'left paren', 'quietly', 'right paren', 'quote', 'Hello', 'comma', 'Jim', '.', "don't", 'right pointing arrow', 't shirt', 'carriage return', '1', 'bar', '2', '', '3', '', '4', 'carriage return'] != ['Say', '(quietly)', 'Hello,', 'Jim', '.', "don't", 'right pointing arrow', 't shirt', '1', 'bar', '2', '', '3', '', '4', 'blank', '', 'blank', 'right pointing arrow', 't shirt', 't shirt', 'blank']
    ------------------------------------------------------------------------------
    moveByLine :: Ensure symbols announced as expected when navigating... | PASS |
    ------------------------------------------------------------------------------
    moveByCharacter :: Ensure symbols announced as expected when navig... | FAIL |
    actual vs expected. With symbolLevel SymLevel.NONE: ['S', 'space', 'left paren', 'right paren', 'quote', 'tick', 'e', 'comma', 'right pointing arrow', 't shirt', 'tab', 'carriage return', 'Right\ncarriage return'] != ['S', 'space', 'left paren', 'right paren', 'quote', 'tick', 'e', 'comma', 'right pointing arrow', 't shirt', 'tab', 'carriage return', 'line feed']
    ------------------------------------------------------------------------------
    selectionByWord :: Ensure symbols announced as expected when selec... | FAIL |
    actual vs expected. With symbolLevel SymLevel.NONE: ['Test selected', ':  selected', 'Say  selected', 'left paren selected', 'quietly selected', ')  selected', 'quote selected', 'Hello selected', ',  selected', 'Jim  selected', '.  selected', "don't  selected", 'selected', 't-shirt   selected', 'carriage return selected', '1  selected', 'selected', '2  selected', 'selected', '3  selected', 'selected', '4 selected', 'carriage return selected', 'space selected', 'carriage return selected', 'tab selected'] != ['Test:  selected', 'Say  selected', '(quietly)  selected', 'Hello,  selected', 'Jim  selected', '.  selected', "don't  selected", 'selected', 't-shirt   selected', 'selected', '1  selected', 'selected', '2  selected', 'selected', '3  selected', 'selected', '4 selected', 'selected', 'selected', 'selected', 'selected', 'right pointing arrow selected', 'selected', 't shirt selected', 'selected', 't shirt selected']
    ------------------------------------------------------------------------------
    selectionByLine :: Ensure symbols announced as expected when selec... | FAIL |
    actual vs expected. With symbolLevel SymLevel.NONE: ['Test:  selected', 'Say  selected', '(quietly)  selected', 'Hello,  selected', 'Jim .  selected', "don't   selected", 'selected', 't-shirt   selected', 'selected', 't-shirt    selected', 't-shirt   selected', '1   2    3      4  selected', 'selected', 'selected', 'selected'] != ['Test:   selected', 'Say   selected', '(quietly)   selected', 'Hello,   selected', 'Jim .   selected', "don't    selected", 'selected', 't-shirt    selected', 'selected', 't-shirt     selected', 't-shirt    selected', '1   2    3      4   selected', 'selected', 'selected', 'selected']
    ------------------------------------------------------------------------------
    selectionByCharacter :: Ensure symbols announced as expected when ... | FAIL |
    actual vs expected. With symbolLevel SymLevel.NONE: ['T selected', 'S selected', 'space selected', 'left paren selected', 'right paren selected', 'quote selected', 'tick selected', 'e selected', 'comma selected', 'right pointing arrow selected', 't shirt selected', 'tab selected', 'carriage return selected'] != ['T selected', 'S selected', 'space selected', 'left paren selected', 'right paren selected', 'quote selected', 'tick selected', 'e selected', 'comma selected', 'right pointing arrow selected', 't shirt selected', 'tab selected', 'selected']
    ------------------------------------------------------------------------------
    tableHeaderSymbols :: Ensure symbols announced as expected in tabl... | PASS |
    ------------------------------------------------------------------------------
    Robot.symbolPronunciationTests :: Symbol pronunciation tests          | FAIL |
    8 critical tests, 2 passed, 6 failed
    8 tests total, 2 passed, 6 failed
    ==============================================================================
    Robot                                                                 | FAIL |
    49 critical tests, 40 passed, 9 failed
    49 tests total, 40 passed, 9 failed
    ==============================================================================
    Output:  C:\Users\Paul\nvda\testOutput\system\output.xml
    XUnit:   C:\Users\Paul\nvda\testOutput\system\systemTests.xml
    Log:     C:\Users\Paul\nvda\testOutput\system\log.html
    Report:  C:\Users\Paul\nvda\testOutput\system\report.html
    Deactivating NVDA Python virtual environment
</details>

**Comment by seanbudd** [comment]
What happens when you run the failing tests individually?

For example: `runsystemtests.bat -t "Restarts on braille crash"`

If the tests fail when running individually, can you please upload the relevant logs found in `testOutput\system\nvdaTestRunLogs`.

**Comment by peluse** [comment]
[](url
[system.zip](https://github.com/nvaccess/nvda/files/9102808/system.zip)
)

**Comment by seanbudd** [comment]
Can you please give us the results of running `systeminfo` in command prompt?

**Comment by peluse** [comment]
You bet....C:\Users\Paul\nvda\testOutput\system>cd ..

C:\Users\Paul\nvda\testOutput>cd ..

C:\Users\Paul\nvda>systeminfo

Host Name:                 PEL-PC
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Paul
Registered Organization:
Product ID:                00330-81611-09401-AA800
Original Install Date:     7/4/2022, 12:23:17 PM
System Boot Time:          7/13/2022, 6:47:30 AM
System Manufacturer:       Gigabyte Technology Co., Ltd.
System Model:              Z170X-UD5
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~4001 Mhz
BIOS Version:              American Megatrends Inc. F5, 3/7/2016
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     63,579 MB
Available Physical Memory: 59,556 MB
Virtual Memory: Max Size:  72,795 MB
Virtual Memory: Available: 67,058 MB
Virtual Memory: In Use:    5,737 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\PEL-PC
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5013889
                           [02]: KB5015814
                           [03]: KB5014034
                           [04]: KB5016353
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (2) I219-V
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Intel(R) I211 Gigabit Network Connection
                                 Connection Name: Ethernet 2
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.188
                                 [02]: fe80::a11c:e760:d17c:88e9
                                 [03]: 2600:8800:1600:140::4f
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by josephsl** [comment]
Hi, I know this may not be relevant, but did you realize that private IP addresses are now visible around the world? Thanks.

**Comment by peluse** [comment]
> Hi, I know this may not be relevant, but did you realize that private IP addresses are now visible around the world? Thanks.

Thanks, maybe someone will hack in and fix it LOL :)

**Comment by peluse** [comment]
@seanbudd any thoughts? Would love to jump in and start fixing bugs but, of course, need a stable setup before doing anything and/or trying to understand the code base.

**Comment by seanbudd** [comment]
@peluse It's not immediately clear what the problem is. Considering this problem is only affecting you, it's unlikely to get any further attention soon.

Unless the system tests are relevant to the bugs you plan to address I would not worry. When you open a pull request the AppVeyor build system will run the system tests for you.

**Comment by seanbudd** [comment]
To rule out that something is broken with your build system, you could try running the system tests against an installed copy of NVDA.

Install NVDA 2022.2rc1, then run from source: `runsystemtests.bat --variable whichNVDA:installed`

**Comment by peluse** [comment]
Will do, thanks!  @seanbudd do you think it's worth using a fresh Win10 install or are plenty of folks using Win11 w/o issue?

**Comment by seanbudd** [comment]
I use Win 11, it's more likely the problem is with using VS22 instead of VS19, hence checking an installed copy vs your build from source.

**Comment by josephsl** [comment]
Hi, I am one of the contributors using Windows 11 (without issues) for code contributions (switched from a Windows 10 system a few months ago as that computer had a file system corruption on a hard disk with NVDA code on it). Note that I do build and test NVDA code from my local computer and do not usually perform system tests unless I need to deal with them directly (usually not the case for me as I mostly perform unit and lint tests only). Thanks.

**Comment by peluse** [comment]
Well, I guess there's something about my system that some of the system tests just wont pass on.  I tried another fresh Win11 with VS2019 and same thing.  I tried installing the latest and running against it as suggested by @seanbudd and same thing.  I'm OK to close this now and I might fire it up on another PC just for fun.  So Im looking to pick up a simple bug to get my feet wet, any suggestions?

**Comment by seanbudd** [comment]
@peluse - a list of good first issues can be found here:
https://github.com/nvaccess/nvda/contribute
