### ISSUE TITLE
Unable to read by character in some terminals

### ISSUE THREAD

**Issue by TheQuinbox** [nvaccess/nvda#13937]
### Steps to reproduce:
1. Run either Cygwin or Git Bash. Either one works, which is why I'm assuming its an NVDA issue.
2. Type "echo test." without the quotes and press enter.
3. Press up arrow, and attempt to navigate first by word, then by character.
### Actual behavior:
Every word of the command is read as you navigate over it. If reading by character, though, all you hear is "space".
### Expected behavior:
I should be able to left and right arrow over specific characters, same as in cmd or powershell.
### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2022.1
#### Windows version:
Windows 10 21H2 (x64) build 19044.1766
#### Name and version of other software in use when reproducing the issue:
Cygwin or Git Bash. Might also effect other terminals, but these are two tools I use daily that are effected.
#### Other information about your system:
Processor	AMD Ryzen 9 5950X 16-Core Processor, 3401 Mhz, 16 Core(s), 32 Logical Processor(s)
Installed Physical Memory (RAM)	128 GB
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by CyrilleB79** [comment]
With NVDA 2022.2 on exactly the same version of Windows, in Git bash:
* I can read the line character by character using left and right arrows without problem
* Regarding word navigatio:
  * Without UIA enabled: 2 words instead of one are reported each time I press control+left/rightArrow.
  * With UIA enabled (do not know if it is supported for this version of Windows): control+left/rightArrow does not produce any 
    * word movement at all.

Cc @codeofdusk

**Comment by codeofdusk** [comment]
If Git Bash is set up to use Mintty (default I think), tracking is less reliable since NVDA uses the display model. In the installer there's an option to use conhost which should work better especially with UIA on the latest build (`FORMATTED`/SV2 inbox).

**Comment by CyrilleB79** [comment]
> @CyrilleB79 When UIA is on, what is the "API level" reported by the console (NVDA+F1)?

API level: 0 (END_INCLUSIVE)

**Comment by codeofdusk** [comment]
Ah, no wonder word navigation is acting strangely. `END_INCLUSIVE` consoles don't have real UIA word navigation (it wasn't implemented for philosophical reasons), so I [had to fake it](https://github.com/nvaccess/nvda/blob/master/source/NVDAObjects/UIA/winConsoleUIA.py#L181).

**Comment by TheQuinbox** [comment]
Switching Git Bash to use Wincon did indeed fix it there, including word nav. That said, Cygwin is still broken, even with UIA enabled.

**Comment by codeofdusk** [comment]
@TheQuinbox You should be able to run Cygwin shells/programs from conhost or wt.

**Comment by seanbudd** [comment]
If this is an underlying problem with MinTTY, has this been reported to them?

**Comment by seanbudd** [comment]
This needs further investigation to see if it can be fixed on the NVDA side.

**Comment by feerrenrut** [comment]
We suspect that it needs an external fix, but further investigation is required to confirm.

**Comment by Adriani90** [comment]
@TheQuinbox are you still having this issue with NvDA 2024.1 Beta 9 or last alpha?

**Comment by Adriani90** [comment]
We didn't get an update from the initial author since more than two years upon request, closing as abandoned. If you are still having this issue, pleaes comment and we can reopen.
