### ISSUE TITLE
announce item count within combo box and groups

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#13938]
### Typical interaction:
Use `alt + down arrow` to expand and interact with combo boxes.
However, on this issue, the interaction is purely using down arrow (not expanding the combo box)

### Steps to reproduce:

1. On nvda enable the option to "guess object position information when unavailable".
1. Now find some combo box in windows or even nvda itself.
1. On nvda I went to the NVDA "Language combo box (requires restart):" Just as an example in several other combo boxes on nvda or windows system the problem is the same.
1. Press `down arrow` to expand the combo box and to position yourself on any item in the combo box.

Before proceeding with the description, I would like to mention that I noticed this problem in a windows control that nvda announced as a grouping.
To find this grouping please follow the path:
1. Open settings.
1. now open customization.
1. Now open themes
1. walk with tab to option
1. Desktop icon settings
1. open button.
1. now press enter
1. nvda will announce: "Group Desktop Icons"
1. now walk with arrows.

Please let me know if it is necessary to open a problem for each type of combo box and grouping control, or if it is possible to handle everything within the same call.

### Actual behavior:
In both types of combo box and groups controls, when walking with the arrows, nvda announces the item with focus but does not inform the general count of items within the control and also does not announce the position in which the user is within these items.

### Expected behavior:
nvda should announce the item in focus, the user's position within the items, and the overall amount of items, similar to what nvda reports in lists.
This for the two types of control, combo box and groups.

#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-25937,0f9c0daf

#### Windows version:
11 22622.290
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by girishbalanagu** [comment]
I do face the same issue. I basically use search and the data in the list box is dynamic and that dynamic list `count` needs to readout when the list changes.

**Comment by mazen428** [comment]
Try expanding the combobox first with alt + down arrow.

**Comment by fernando-jose-silva** [comment]
Perfect, opening the combobox solves the problem for the comboboxes, although I believe nvda should count even if the box is closed as we are browsing through it.
But I pay attention to the other grouping element.
Thanks.

**Comment by michaelDCurran** [comment]
When a combo box is closed, it is just a control with a value. Pressing the arrow keys changes the value. Windows does not expose any count information for closed combo boxes. So this cannot be fixed. I would always recommend expanding a combobox with alt+downArrow before changing the value with the arrows as otherwise unexpected actions may occur as you are moving through the values.

The grouping scenario is much different. But again, Windows in this particular case does not expose any kind of count informaiton. If this is necessary, it should be instead reported to Microsoft and they can implement positionInSet and sizeOfSet UI automation properties on each item and then NVDA will appropriately report them.
