### ISSUE TITLE
thunderbird doesn't read messages with incoming progress bar

### ISSUE THREAD

**Issue by smeveriss** [nvaccess/nvda#13941]
This has been discussed on the list for ages now but I only just got round to splitting this off from the main statusbar bug in thunderbird which seems to have been handled at least from the reports.
The new bug for that is
https://bugzilla.mozilla.org/show_bug.cgi?id=1780944
if anyone is interested.

**Comment by amirmahdifard** [comment]
hi.
please open the ishoos properly

**Comment by seanbudd** [comment]
Welcome @smeveriss ,

We are unable to process this issue as it stands.

- Please fill out the issue template fully.
- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Please re-open this issue with the above information if the investigation by [Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1780944) reveals this to be a bug in NVDA.

Kind Regards,
NV Access Software Developers
