### ISSUE TITLE
NVDA announces Blank

### ISSUE THREAD

**Issue by rpilman** [nvaccess/nvda#13948]
NVDA Ver. 2022.2

### Steps to reproduce:
1. Download our sample web output [Blank Phrase.zip](https://github.com/nvaccess/nvda/files/9183837/Blank.Phrase.zip)
2. View our story.html 
3. Launch NVDA
4. Navigate to the Next Button and hit the spacebar to go to Test Slide 1.2

As you get to Test Slide 1.2, NVDA announces "Test Slide 1.2 Blank"

### Actual behavior:
Blank Phrase  document
slide: Test slide 1.1
main landmark    clickable  This is only a test text. 
blank
button    Back to top
toggle button  not pressed    volume
volume  slider    8
slide navigation  navigation landmark    button  unavailable    previous
button    next
slide: Test slide 1.2 
blank

Copied to clipboard: slide: Test slide 1.2
 

### Expected behavior:
To hear NVDA read "Test Slide 1.2" without blank. 
This doesn't happen with JAWS 

#### NVDA installed/portable/running from source:
Windows 11 Home
Surface Pro 7
Browser: Chrome

#### NVDA version:
2022.2

#### Windows version:
Version	10.0.22000 Build 22000

#### Name and version of other software in use when reproducing the issue:
Articulate Global - Storyline 360 (Ver. 3.66.28270)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A 

#### If NVDA add-ons are disabled, is your problem still occurring?
N/A

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

Attempts by our dev team results in worse behavior

- Setting focus to the label causes the slide title to be read twice

- Setting focus to slideEl causes the entire contents of the slide to be read

- Setting aria-live to off on the slide-label causes the slide title not to be read when clicking on the next button or menu items. I believe this is at least partially caused by focus being give to the innards of interactive elements instead of to the interactive element itself. For instance, setting the focus to the button element and not the inner view-content partially fixes this issue

- Not setting the focus to anything leaves focus on the clickable element that caused the slide change

- Not changing the tab index doesn't actually set focus to the element, focus() is a noop (this is the current state)

- Setting focus to the focus sink causes nvda to read blank (this is the current state)

**Comment by feerrenrut** [comment]
This is intentional, it lets the user know that their interaction was successful, even if there is no content to report. We'd be willing to hear arguments about why this is not beneficial for users (from the perspective of screen reader users), however with the absence of this, I'm going to close the issue. Please feel free to comment / re-open if you'd like to discuss this further.

**Comment by ahesham900** [comment]
I have a logout page and it says blank after screen title and then listing all page elements including back to login button, if this is intentional why it does not happen in 3 other similar pages with the exact structure. Please help. I use aria live to make all elements said
