### ISSUE TITLE
Combobox element text content not being announced in Firefox.

### ISSUE THREAD

**Issue by AlmeroSteyn** [nvaccess/nvda#13947]
### Steps to reproduce:
- Go to https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-select-only.html
- Use Firefox and NVDA and set focus on the combobox element

### Actual behavior:
- Control is read out as: Favorite fruit combo box collapsed

Seems related to: https://github.com/nvaccess/nvda/issues/12329

### Expected behavior:
- Control should be read out as: Favorite fruit combo box Choose a Fruit collapsed
- This is current the behaviour of using NVDA on this page in Chrome and Edge

#### NVDA installed/portable/running from source:
Installed

#### NVDA version: 
2022.2

#### Windows version: 
10

#### Name and version of other software in use when reproducing the issue:
- Firefox 102.0.1 (64-bit)
- Also occurs in Firefox Nightly

#### Other information about your system: 
None relevant to this issue

#### Does the issue still occur after restarting your computer? 
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This issue has only become apparent on the latest version. Have not been able to downgrade to test

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Running this on a development computer. As the system registry fixes that will be made is not clearly outlined I will have to skip this step. However, as it works in Chromium browser I suspect it to be a Firefox / NVDA integration issue and not registry related.

**Comment by lukaszgo1** [comment]
cc @jcsteh

**Comment by jcsteh** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1631693

**Comment by AlmeroSteyn** [comment]
@jcsteh Thank you for the fast response. Appreciated. 

I did do a search of open issues but somehow missed the related issue. Sorry.

**Comment by Adriani90** [comment]
Fixed since Firefox 109, closing as works for me.
