### ISSUE TITLE
Starting from alpha-25864,c9d9ec30, eSpeak sound changed when rate is set to 100 percent

### ISSUE THREAD

**Issue by DraganRatkovich** [nvaccess/nvda#13952]
It's the most descriptive title I can find for this issue, but if you think it's worth renaming it, then go for it.

Since NVDA alpha-25864,c9d9ec30, eSpeak's sound has changed a lot. More precisely, when the rate percentage is set to 100, eSpeak no longer produces clear, fast speech, as it did before the said alpha release.

I have tried several alpha releases before alpha-25864,c9d9ec30, the sound is clear like in NVDA 2022.2, but since the mentioned alpha release newer alpha releases are also affected by this issue.

I will attach a .zip archive, please download it, extract it and find the two audio recordings. One for NVDA version 2022.2, one for alpha-25864,c9d9ec30. File names are enough to distinguish the audio recordings. Please listen to them patiently and let me know what the problem is. I don't have any more opportunity to describe this problem because I don't know anything about the eSpeak sound engine and other things behind it, so the audio recording is more than enough I think to see how different the two versions are.

### Steps to reproduce:

1. [Download alpha-25864,c9d9ec30](https://www.nvaccess.org/files/nvda/snapshots/alpha/nvda_snapshot_alpha-25864,c9d9ec30.exe)
2. Try to reproduce the issue for your NVDA build by listening to the exact parameters in the audio file below.

### Actual behavior:
eSpeak does not provide clear sound when rate is set to 100

### Expected behavior:
eSpeak should produce clear sound, as it was before the mentioned alpha, as well as in the current stable version of NVDA

### NVDA logs, crash dumps and other attachments:
[TestRecordings.zip](https://github.com/nvaccess/nvda/files/9188411/TestRecordings.zip)

#### NVDA installed/portable/running from source:
Installed, as well as portable
#### NVDA version:
Tested alpha-25864,c9d9ec30, alpha-25865,1d43ec8d,alpha-25875,d6a193ae, alpha-25881,7c08cf52 and all alpha before alpha-25977,af0014e1, which is latest.

#### Windows version:
Windows 10 Pro x64-bit, also can be reproduced in Windows 8.1 x64-bit
#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Tried alpha-25844,44086021 which was released before alpha-25864,c9d9ec30, in alpha-25844,44086021 the eSpeak sound is clear

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
I haven't tried it, but I think it doesn't matter, there is something related to eSpeak.

@seanbudd @leonardder @Qchristensen Hope you can find the reason for this.

**Comment by CyrilleB79** [comment]
Hi @DraganRatkovich

Very probably due to #13893.
The way eSpeak speaks at rate 100% rate boost (RB) off in last alpha builds is the same as eSpeake at 99% RB off in 2022.2.
If you want the same experience of rate 100% RB off in 2022.2, you need to set rate to 19% RB on in last alpha builds.
Also in last alpha, a rate between 90% and 95% RB off should be approximately the same speed as the 2022.2 rate 100% RB off, even if the prononciation is not the same.

Please read well #13893, to understand why it does not totally fixesthe issue which is basically an eSpeak issue.

If you find that #13893 was not the correct way to fix the issue, please elaborate.

**Comment by DraganRatkovich** [comment]
Hello @CyrilleB79

Yes, I read the information on the mentioned link and everything became clear.

**Comment by CyrilleB79** [comment]
Since #13876 has remained opened, I think you can close the current issue as a duplicate of #13876.

Or maybe you would suggest to give more explicit indications in the change log for #13893. Today, the change log says:
> When rate boost is off, eSpeak's rate does not drop anymore between rates 99% and 100%. (#13876)

**Comment by DraganRatkovich** [comment]
Duplicate of #13876

**Comment by CyrilleB79** [comment]
In https://github.com/nvaccess/nvda/issues/13876#issuecomment-1206159599 @DraganRatkovich, you wrote:
> Hello,
> @CyrilleB79 In the most recent alpha version of NVDA, I can still reproduce this issue. Are you sure this commit fixed the issue? eSpeak still makes unclear sound when speed is set to 100 and rate boost is disabled. The clearest explanation is in my opened issue #13952, in which I have attached audio files to it. I'm not sure what was done in the alpha that this issue originated from, but I think it has nothing to do with eSpeak because the issue you mentioned in the eSpeaks repo is from 2016, which is not applicable in this situation.

eSpeak 100% is now faster (and this was expected), thus maybe you need to change your rate to get something acceptable for you?

In https://github.com/nvaccess/nvda/issues/13952#issuecomment-1195263796, I wrote:
> If you want the same experience of rate 100% RB off in 2022.2, you need to set rate to 19% RB on in last alpha builds.
> Also in last alpha, a rate between 90% and 95% RB off should be approximately the same speed as the 2022.2 rate 100% RB off, even if the prononciation is not the same.

Have you tested it? And can you get the same experience?

If this does not satisfy your needs, please explain.
