### ISSUE TITLE
Add a way to get to and from pop-ups on web pages

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#13957]
### Is your feature request related to a problem? Please describe.

Many websites use a type of pop-up to get your cookie preferences, ask you to subscribe to their newsletter or request a donation.  These appear visually on screen, however are not noticeable to screen reader users (some might say this is generally a good thing).

The contents of these types of pop ups seems to be at the very bottom of the page:

1) Open most pages on Wikipedia, eg: https://en.wikipedia.org/wiki/Andromeda_Galaxy
2) Press TAB to navigate to any link in the main body of the article (after the H1 heading - tab seems to trigger this where K does not).

A pop-up appears showing a preview of the page the link goes to.  NVDA does not report anything.

Alternatively:

1) Open The Guardian newspaper: https://www.theguardian.com/au
2) Wait for the page to load

A pop-up appears asking you to donate

In both cases, NVDA does not report anything, however, in both cases:

3) Press CONTROL+END to move to the bottom of the page.
4) Press up arrow.

The focus moves backwards through the pop-up text.

### Describe the solution you'd like

Ideally, it would be good if users:

a) were alerted to the existence of these pop-ups
b) Had a way to jump to them,  and especially in the case of pop-ups used in the way they are on Wikipedia , a way to jump back from the pop-up text to the earlier location on the page.

### Describe alternatives you've considered

In the case of pop ups which appear immediately, and which the user expects, jumping to the bottom may not be too much of a burden, however that requires the user to a) expect the pop up to be there, and b) know to go to the bottom of the page without any prompting.

In some cases pop-ups like this can be ignored with no ill effects, however on some sites, a user needs to acknowledge something or do something before the site works as expected.

### Additional context

I don't know if the Guardian and Wikipedia pop-ups use the same technology and require the same fix, but from an end-user perspective, the method of accessing them appears the same.

**Comment by seanbudd** [comment]
Hi @Qchristensen,

It appears that for the wikipedia example: "aria-hidden" is on the popover element. It appears that the developers are intentionally hiding these from screen reader users.

The initial reporter should report these issues to the relevant web pages.

**Comment by Qchristensen** [comment]
Ok, is that the same for the Guardian example?  (There are lots of aria-hidden's on that page so I wasn't sure)

**Comment by seanbudd** [comment]
I'm not sure - generally these issues need a minimal sample to reproduce them as a bug with NVDA. If web content is inaccessible it needs to be reported to the authors primarily.

**Comment by Qchristensen** [comment]
That's ok, like I said originally, I wasn't sure if they were caused by the same code, just that they behaved the same.  I've encountered a few pages like that, and it may be that they are all aria-hidden.  As you say, that is poor design of the page and up to the web developers to fix - I just wanted to check that it wasn't a new type of pop-up control we needed to be aware of.
