### ISSUE TITLE
Impossible to set caret to the position of the review cursor in rich edit controls when handle keys from other applications is enabled.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#13968]
Initially described in  issue #13420 

### Steps to reproduce:
1. Open NVDA's log viewer or  Wordpad,
2. Set your caret somewhere and move review cursor to the top of the edit field.
3. Try to move caret to the position of the review cursor by pressing NVDA+Shift+numpad minus twice.
4. In keyboard settings disable "Handle keys from other applications" and repeat steps 2 to 3.

### Actual behavior:
When Handle keys from other applications is enabled caret fails to move.

### Expected behavior:
Caret should be moved to the review position regardless of the "Handle keys from other applications" being enabled or disabled.

### NVDA logs, crash dumps and other attachments:
Log snipped with "Handle keys from other applications" enabled:
```
IO - inputCore.InputManager.executeGesture (15:02:16.639) - winInputHook (3116):
Input: kb(desktop):shift+NVDA+numpadMinus
IO - speech.speech.speak (15:02:16.649) - MainThread (7152):
Speaking ['Move focus']
IO - inputCore.InputManager.executeGesture (15:02:16.649) - winInputHook (3116):
Input: kb(desktop):NVDA+
IO - inputCore.InputManager.executeGesture (15:02:16.759) - winInputHook (3116):
Input: kb(desktop):shift+NVDA+numpadMinus
IO - speech.speech.speak (15:02:16.769) - MainThread (7152):
Speaking ['Move focus']
IO - inputCore.InputManager.executeGesture (15:02:16.769) - winInputHook (3116):
Input: kb(desktop):NVDA+

```

Notice the additional lines `Input: kb(desktop):NVDA+` which should not be there.

Log snipped with "Handle keys from other applications" disabled:
```
IO - inputCore.InputManager.executeGesture (15:03:29.438) - winInputHook (3116):
Input: kb(desktop):shift+NVDA+numpadMinus
IO - speech.speech.speak (15:03:29.448) - MainThread (7152):
Speaking ['Move focus']
IO - inputCore.InputManager.executeGesture (15:03:29.588) - winInputHook (3116):
Input: kb(desktop):shift+NVDA+numpadMinus
IO - speech.speech.speak (15:03:29.648) - MainThread (7152):
Speaking ['Developer Scratchpad mode enabled\r']

```

#### NVDA installed/portable/running from source:
Both installed and portable.

#### NVDA version:
Latest Alpha, 2022.2

#### Windows version:
Tested on Windows 7 but should not matter.

#### Name and version of other software in use when reproducing the issue:
Wordpad, NVDA's log viewer, QRead
#### Other information about your system:
None relevant
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The same issue occurs with 2019.2
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Haven't tried.

**Comment by lukaszgo1** [comment]
@cary-rowen  Would you be able to confirm that disabling "Handle keys from other applications" makes it possible to move caret to the position of the review cursor in bookworm?

**Comment by cary-rowen** [comment]
yes i can confirm this.

**Comment by cary-rowen** [comment]
Also, as you said in #13420, Say all needs to be improved.

**Comment by leonardder** [comment]
@lukaszgo1 Can you still reproduce this with Wordpad in current alpha versions? Note that in NVDA itself, we forcefully disable UIA.

**Comment by cary-rowen** [comment]
Hi @leonardder 

"Handle keys from other applications" is checked.

Excitingly, I can no longer reproduce this in WordPad and Bookworm using NVDA-alpha-28931,186a8d70. But still reproducible in NVDA's log viewer.

Thanks

**Comment by leonardder** [comment]
I'm afraid we can not use UIA in NVDA's log viewer. That said, we could more safely consider disabling ITextDocument2 by default for the log viewer.

**Comment by cary-rowen** [comment]
Can we assume that #15314 has fixed (or partially fixed) this issue?

**Comment by Adriani90** [comment]
We didn't hear an update from the initial user since more than 2 years upon request, and I cannot reproduce it either. Maybe it was fixed as referencced above. Closing as abandoned. if anyone can still reproduce this, please comment and we can reopen.
