### ISSUE TITLE
Links not visible when using arrow keys on https://www.homes.vic.gov.au/

### ISSUE THREAD

**Issue by sjtaylor82** [nvaccess/nvda#13964]
### Steps to reproduce:
1. Visit https://www.homes.vic.gov.au/
2. Tab and shift-tab. Note that links such as Home, About, Projects, Engage, Housing, Contact, Search... are spoken. These links cannot be explored with arrow keys and are completely skipped over. They are however visible when using JAWS. This behaviour is observed with both Edge and Chrome. NVDA is installed.

**Comment by seanbudd** [comment]
Welcome @sjtaylor82 ,

We are unable to process this issue as it stands.

- Please fill out the issue template fully.
- To be able to reproduce this issue, we need a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).
- This is very likely a problem with the implementation of the website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers

**Comment by Brian1Gaff** [comment]
In fact the same effect occurs in Mozilla as well, so all you really need to 
do is go to the page he suggests. I don't think the user should need to be 
able to extract code from a web site in order to report this.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "sjtaylor82" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Friday, July 29, 2022 1:35 AM
Subject: [nvaccess/nvda] Links not visible when using arrow keys on 
https://www.homes.vic.gov.au/ (Issue #13964)

**Comment by Brian1Gaff** [comment]
I just had a very quick look at the page source in Firefox, and there are so 
called hidden menu items with the names you mention. This appears to be 
something to do with mobile display optimisation, so it could be that you 
are not actually supposed to see these unless you use a mobile to access the 
site. They could be intermediate menus to split up the content to make each 
page easer to navigate on a mobile or vice versa.

Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "sjtaylor82" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Friday, July 29, 2022 1:35 AM
Subject: [nvaccess/nvda] Links not visible when using arrow keys on 
https://www.homes.vic.gov.au/ (Issue #13964)

**Comment by alexarnaud** [comment]
Hello @sjtaylor82,

There is a big issue on the website itself, the part of the site not shown by NVDA is a big heading. You should report the problem to the website owner, this is not allowed to use a big heading labelled to handle the header. The culprit code on the website:
`<div id="page-highlighted" role="heading" aria-label="Page highlighted">`

Best regards.

**Comment by sjtaylor82** [comment]
Thanks for the explanation, I will contact the web developers. Sam Sent from my iPhoneOn 30 Jul 2022, at 12:53 am, Alex ARNAUD ***@***.***> wrote:﻿
Hello @sjtaylor82,
There is a big issue on the website itself, the part of the site not shown by NVDA is a big heading. You should report the problem to the website owner, this is not allowed to use a big heading labelled to handle the header. The culprit code on the website:
<div id="page-highlighted" role="heading" aria-label="Page highlighted">
Best regards.

**Comment by Brian1Gaff** [comment]
Yes you can hear the words page highlighted, but there is not real 
indication of what it means, As I said there are a lot of invisible or 
supposed to be invisible items depending on if its on a mobile platform or 
not. Probably one of those pages that has been extensively modified to do 
what they want, but not tested in all situations.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "Alex ARNAUD" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Brian Gaff" ***@***.***>; "Comment" 
***@***.***>
Sent: Friday, July 29, 2022 3:53 PM
Subject: Re: [nvaccess/nvda] Links not visible when using arrow keys on 
https://www.homes.vic.gov.au/ (Issue #13964)

**Comment by seanbudd** [comment]
Closing this as needing an external fix from the website authors
