### ISSUE TITLE
NVDA reading incorrect information when navigating

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#13979]
### Steps to reproduce:

Navigating quickly seems to triger this.  I found I could reproduce it reliably by:
1) Take a large (thousands of rows) spreadsheet.  I copied the entire WWI Wikipedia article and just dumped it in a blank Excel spreadsheet.
2) From the bottom, hold down the up arrow key for a couple of seconds.
3) Note the row and data NVDA reports, say, Row 400.  You can verify this with numpad 8, NVDA+delete or NVDA+tab.
4) Press the up arrow.

### Actual behavior:

Note that the row reported at step 4 is different (by more than one) to the row reported at step 3.  EG, at step 3, NVDA reported I was on row 401.  However, visually, the focus was actually on row 355, which was confirmed when I pressed up arrow once and moved to row 354.

When NVDA thought it was on cell A355, it did read the text from cell A355.

### Expected behavior:

NVDA should report the correct row and text from where the focus actually is.

#### NVDA version:

NVDA 2022.3 beta 1

#### Windows version:
Windows 11 (64-bit) Version: 21H2 (2009), Build: 22000.795 
#### Name and version of other software in use when reproducing the issue:
Office 365 (64-bit) Version: 16.0.15330.20260 
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
A user reported this using NVDA 2022.2.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

**Comment by seanbudd** [comment]
Is this a duplicate of #12200?

**Comment by Qchristensen** [comment]
I'm happy to call it a duplicate.  I'll call it a duplicate of 12108 given I replicated with a large worksheet.

Further to that, I can also replicate this issue with UIA disabled but NOT with UIA enabled for Excel.
