### ISSUE TITLE
Contents item on hyperlink not read (latest version)

### ISSUE THREAD

**Issue by FvdGDTP** [nvaccess/nvda#13981]
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

**Comment by seanbudd** [comment]
Welcome @FvdGDTP ,

We are unable to process this issue as it stands.

- Please fill out the issue template fully.
- Many developers, contributors and community members here are vision impaired. Screenshots are not accessible. Provide an alternative description, and capture any relevant information from images.
- To be able to reproduce this issue, we need a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).
- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Once the template has been filled out feel free to re-open the issue.

Kind Regards,
NV Access Software Developers

**Comment by seanbudd** [comment]
Nevermind, I see that #13982 has been opened
