### ISSUE TITLE
NVDA is not narrating Location, Details, contact and Review tab information, while navigating using down arrow key.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#13993]
### Description: ###
NVDA narrating as Facility Request grouping Clickable Graphic Current location tab 1 of 4.
NVDA should not narrate clickable information using NVDA browse mode because Location/Details/Contact/Review tabs are not clickable controls.

### Test Environment: ###
OS: Windows 11 version 21H2(OS build 22000.318)  

Browser: New Edge Version (101.0.1210.53), Chrome (102.0.5005.63)

URL:  https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fmicrosoft.sharepoint-df.com%2fteams%2fdev_myhubring0%2fSitePages%2fDashboard.aspx&data=05%7c01%7cv-bcherian%40microsoft.com%7c0300b82b02464ea4f20b08da43af1447%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637896716799001193%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=74zE3KFSkdAJtdmmN30Z2Z0I76%2Bq3Jz63G9t5d5e7FU%3D&reserved=0

Screen readers: NVDA 2021.3.3

### Repro steps: ###
Step 1: Open the above Url in New Edge brower/Chrome

Step 2: Home page will display and turn on the screen reader NVDA

Step 3: Navigate to “Facility Request” and activate it.

Step 4: Facility Request dialog box is appearing.

Step 5: Click on 'Make a request' button.

Step 6: Verify NVDA browse mode it’s announcing Location, Details, contact, and Review tab is announcing as Clickable.

### Actual Results: ###
NVDA/JAWS is narrating these Location, Details, contact and Review tab information as clickable

### Expected results: ###
1.Location tab ->NVDA should announce “Current Location tab 1 of 4 

2.Details tab -> NVDA should announce Current Details tab 2 of 4 

3.Contact tab -> NVDA should announce Current Contact tab 3 of 4 

4.Review tab -> NVDA should announce Current Review tab 4 of 4 

### Attachments: ###
<img width="922" alt="Screenshot 2022-08-08 021512" src="https://user-images.githubusercontent.com/93735775/183310425-63cc15d2-9942-459c-b12b-bf7d7aabb85a.png">

https://user-images.githubusercontent.com/93735775/183310437-6cd120de-6279-4d83-ac84-de2b3e624025.mp4

### Additional information: ###
The same issue repro with the Details 2 of 4 Tab, Contact 3 of 4 Tab, Review 4 of 4 Tab.

**Comment by seanbudd** [comment]
We are unable to process this issue as it stands.

- Please fill out the issue template fully.
- To be able to reproduce this issue, we need a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).
- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.
- This is very likely a problem with the implementation of the website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers
