### ISSUE TITLE
Windows hanging for a while on computers with amd gpu's with nvda during shutdown

### ISSUE THREAD

**Issue by BlindWarriorSven** [nvaccess/nvda#13992]
### Steps to reproduce:
1. Run NVDA on a pc or laptop with amd ryzen with radeon graphics such as the amd ryzen 7 5700u or amd ryzen 7 5800u.
2. Make sure your drivers for the radeon graphics have been installed.
3. Work with the computer for a while and then shutdown or reboot.
4. It will take a few seconds before nvda is closing and the pc shuts down or reboots also, a message appears that windows needs to end a running task first (shutdown is blocked by a process). This doesn't happen on pcs with intel or nvidia graphics.

### Actual behavior:

See point 4 above.

### Expected behavior:

NVDA should close normally and the pc should reboot/shutdown faster.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2022.2

#### Windows version:
Windows 10 Pro X64 Dutch V21H2 and Windows 11 Home X64 Dutch V21H2

#### Name and version of other software in use when reproducing the issue:
AMD Software: Adrenalin Edition 21.5.1 is installed as the driver for the graphics cards. It's a clean system with all windows updates and related drivers installed.

#### Other information about your system:
This "bug" occures on every amd powered system I tested it on. The following processors with radeon graphics were installed in the systems:
AMD Ryzen 3 4300u
AMD Ryzen 7 4800U
AMD Ryzen 7 5700U
AMd Ryzen 7 5800u

*** On my 2 laptops with AMD Ryzen 7 4800H the problem doesn't occure but the amd radeon graphics have been disabled on those systems due to an nvidia GTX 1660 TI graphics card. ***

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, NVDA versions 2022.x and NVDA 2021.X. Problem existed too.

#### If NVDA add-ons are disabled, is your problem still occurring?
No addons running.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by josephsl** [comment]
Hi, what if NVDA is turned off before shutting down or restarting a system? I doubt that it can fix the problem but something to try, and if it is what I think it is, then I guess Radeon software got stuck while trying to exit threads as that’s the cause of “hung program” window (source: Windows Internals, Seventh Edition part 2). Thanks.

**Comment by BlindWarriorSven** [comment]
Hello Joseph,

When I restart/shutdown those systems without nvda launched there is no problem. I also discovered that closing nvda manually before shutting down/reboot the problem appears. See the scenario's below:

1. System shutdown/reboot without nvda have been started = Fine.
2. System shutdownreboot with nvda running = Hang.
3. System shutdown/reboot with nvda manually closed = hang.

I hope this helps.

Best regards,

Sven

**Comment by josephsl** [comment]
Hi, I see. This might not be relevant, but have you tried reproducing this with Narrator instead of NVDA running? That way we can try pinpointing to a specific module inside NVDA that might be causing threads to get stuck somehow. Thanks.

**Comment by BlindWarriorSven** [comment]
Hello Joseph,

I will try that and report back here.

Best regards,

Sven

**Comment by amirmahdifard** [comment]
hello: i'm also using the same moddle as this, and this problem is happening to me too, i've red the comments, and i also want to help you for fixing this: so due to your last question, i tryed this with narator and i tested with jaws too, and the problem happens with NVDA, and there is no problem with other screen readers.

**Comment by seanbudd** [comment]
Welcome @BlindWarriorSven ,

Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Kind Regards,
NV Access Software Developers

**Comment by feerrenrut** [comment]
I'm using an `AMD Ryzen 7 PRO 4750U with Radeon Graphics` and don't run into this issue.

**Comment by Adriani90** [comment]
@BlindWarriorSven, @amirmahdifard are you still having this issue with NVDA last alpha version?
Please turn off the visual highlighters in NVDA's visual presentation settings and turn off also screen curtain in case you have them enabled. Is then the isue still occuring?

The last alpha version of NVDA can be found here:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Adriani90** [comment]
We didn't get an update from the people having this issue since more than one year. I am closing this as abandoned. if you are still having this issue, Please provide the requested info and we can reopen.
