### ISSUE TITLE
 NVDA is not narrating '(Bindings in the MSI file always overwrite those in the application)' when focus moved to the checkbox of 'Overwrite resources'.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#13991]
**Test Environment:**
OS: Windows_11
Version: 21H2
OS Build: 22000.795
Browser: Version 103.0.1264.71 (Official Build) (64-bit)
Screen Reader: NVDA (2021.3)

**Pre-Requisites (if any) :**
Turn on NVDA (Ctrl + Alt+ N)
Download TestLabels_21804423 application and unzip it.
[TestLabel_21804423 (1) (1).zip](https://github.com/nvaccess/nvda/files/9268242/TestLabel_21804423.1.1.zip)
[MAS1.3.1-NVDA-Checkbox.webm](https://user-images.githubusercontent.com/93735775/183071106-f7d704e0-82df-425a-994c-cffab53c9359.webm)

**Repro Steps:**
1. Open 'TestLabel_21804423' file folder by using the enter key.
2. The screen will open with " 'TestLabel_21804423' file folder and " 'TestLabel_21804423' SLN file.
3. Select 'TestLabel_21804423' file folder by using the enter key.
4. The screen will open with bin, obj and properties file folder.
5. Select bin file folder using enter key.
6. The screen will open with debug file folder and select it using enter key.
7. TestLabel_21804423 application will appear and select it using enter key.
8. Windows protected your pc dialog will appear.
9. Press 1 tab key to reach more info and select using enter key.
10.  Press one more tab key to reach ran anyway and select it.

**Actual Behavior:**
Navigate to 'MSI File to Import' field on 'Welcome to the Wizard page' page and select MSI file, click on next button.
 NVDA does not narrate '(Bindings in the MSI file always overwrite those in the application)' when focus moved to the checkbox of 'Overwrite resources'.

**Expected Behavior:**
NVDA should narrate '(Bindings in the MSI file always overwrite those in the application)' along with 'Overwrite resources' when focus moved to checkbox of 'Overwrite resources.

**Comment by josephsl** [comment]
Hi, is this also the case with Edge 104/105 and NVDA 2022.2/2022.3 beta? Note that filling out the template is advised. Thanks.

**Comment by feerrenrut** [comment]
Note that this a limitation with Windows.
Using an accessibility info viewer tool shows the extra text is not associated with that control. I.E. `(Bindings in the MSI file always overwrite those in the application)`.

The text needs to be included in the label for the control in order for it to be reported for that control.

The code from the provided sample that is causing this issue. Note that there is a check box (which has the label via the Text property "OverWrite Resources") and an independent static text.
```C#
            // 
            // overwriteChkBox
            // 
            this.overwriteChkBox.AutoSize = true;
            this.overwriteChkBox.Location = new System.Drawing.Point(95, 102);
            this.overwriteChkBox.Name = "overwriteChkBox";
            this.overwriteChkBox.Size = new System.Drawing.Size(186, 24);
            this.overwriteChkBox.TabIndex = 0;
            this.overwriteChkBox.Text = "OverWrite Resources";
            this.overwriteChkBox.UseVisualStyleBackColor = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(140, 129);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(467, 20);
            this.label1.TabIndex = 1;
            this.label1.Text = "(Bindings in the MSI file always overwrites those in the resources)";
```

Additionally, this text can be reported with Object navigation in NVDA.

I'm closing this issue, since this appears to work as expected. I will note that these use-cases may be improved with future features, such as something like scan-mode.
