### ISSUE TITLE
Excel: NVDA speaks nothing when user navigate to the slicer and focus also stuck on the first slicer.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#14006]
### Steps to reproduce:
1) Launch NVDA
2) Load the attached test Excel document (there are 3 slicers in the worksheet)
3) Press alt+h, f, d, o (Select Objects)
4) Press tab to select first slicer
5) Press tab again to go through the focusable items in the first slicer and ultimately the next slicer

### Actual behavior:
Step 4: NVDA speaks nothing but the slicer gets focused
Step 5: Tab does not advance. Focus is stuck on the first slicer

### Expected behavior:
Step 4: NVDA should speak that you focused the "Jan slicer"
Step 5: Tab takes you through the focusable element and ultimately the next slicer speaking the expected information as you go

### NVDA logs, crash dumps and other attachments:
[test.xlsx](https://github.com/nvaccess/nvda/files/9303972/test.xlsx)

https://user-images.githubusercontent.com/93735775/184018525-3c84ef1a-6c95-429a-8c19-4f16629ef252.mp4

### System configuration
Windows 11 Enterprise

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA: Version 2022.2

#### Windows version:
OS build: Version 21H2 Build 22000.856

#### Name and version of other software in use when reproducing the issue:
Excel: Version 2207 Build 15427.20178

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by seanbudd** [comment]
I could not reproduce this using NVDA 2022.2 and `Microsoft® Excel® for Microsoft 365 MSO (Version 2207 Build 16.0.15427.20182) 64-bit` with UIA enabled via advanced preferences.

I could successfully tab the graphics and the contents were reported.

**Comment by seanbudd** [comment]
When UIA becomes default for using Excel, this issue can be closed.

**Comment by msviolafangirl** [comment]
I can confirm this issue is resolved. It should be closed.
