### ISSUE TITLE
The indeterminate state checkbox on the web is not reflected in braille

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#14012]
### Steps to reproduce:
1. Open the following page: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes
2. Navigate to "Indeterminate state checkboxes" with level 3 heading;
3. Check the 'book' checkbox and observe the status of the 'Enchantment table' on the braille display;

### Actual behavior:
Go to step 3, the abbreviations on the braille display are shown as unchecked.

### Expected behavior:
A half-checked checkbox should be displayed on braille display.

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2022.3Beta2
#### Windows version:
Windows 10 21H2 (x64) build 19044.1889
#### Name and version of other software in use when reproducing the issue:
chrome: 104.0.5112.81
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
None
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by rperez030** [comment]
Interesting. This one doesn't reproduce for me. I have the halfchecked symbol in Braille (1 2 3 4 6 followed by 3 4 5 6 followed by 1 3 4 5 6).

**Comment by seanbudd** [comment]
@rperez030 - what browser are you using, and what version is your browser?

**Comment by rperez030** [comment]
Hi @seanbudd . I'm using Edge version 104.0.1293.54 and NVDA 2022.3beta2 with UIA support for Microsoft edge and chromium browsers in its default state in the advance setting section. the checkbox appears as half checked in braille and it announces as "Enchantment table  check box  half checked". If I set UIA support to yes, I can then reproduce the issue as @cary-rowen described.

**Comment by SaschaCowley** [comment]
I am unable to reproduce this. @cary-rowen, @rperez030, are you still having this issue?

**Comment by cary-rowen** [comment]
Seems like good news, I can't reproduce this either. So let me close it.
Thanks @SaschaCowley
