### ISSUE TITLE
Live regions that are outside of the viewport are not read in Firefox

### ISSUE THREAD

**Issue by dhenneke** [nvaccess/nvda#14017]
### Steps to reproduce:

1. Have a live region (`<div role="status" aria-atomic="false"></div>`) that is outside of the viewport. 
   A live region with a "visibility hidden" css class also leads to the same error.
3. Add a message to the live region.

Example: https://codesandbox.io/s/infallible-ully-intcpe
> The example has two regions: the first one is visible and fills the whole screen; the second one is below the first one outside of the viewport.

### Actual behavior:

**Firefox**: The message _**is not**_ read to the user.

https://user-images.githubusercontent.com/720821/184684215-fa62ec51-9fd1-43dc-ab35-41a64836c9ca.mp4

**Chrome**: The message _**is**_ read to the user.

https://user-images.githubusercontent.com/720821/184684231-1fbe0da5-be1a-4d49-88d4-dad4c2d6552a.mp4

### Expected behavior:

The message should be read to the user in all browsers.

#### Name and version of other software in use when reproducing the issue:

* Firefox 103.0.2 (64-Bit)
* Chrome 103.0.5060.134 (64-Bit)

**Comment by lukaszgo1** [comment]
cc @jcsteh

**Comment by jcsteh** [comment]
This is a Firefox bug and will be fixed as part of our in-progress re-architecture of the accessibility engine. Specifically for this issue, see https://bugzilla.mozilla.org/show_bug.cgi?id=1782172.

**Comment by jcsteh** [comment]
Btw, this bug only occurs in iframes. It should not occur in a top level document.

**Comment by dhenneke** [comment]
> This is a Firefox bug and will be fixed as part of our in-progress re-architecture of the accessibility engine. Specifically for this issue, see https://bugzilla.mozilla.org/show_bug.cgi?id=1782172.

That's awesome, thanks for linking and fixing it. I'm not familiar with the dev processes at Firefox, but it looks like it was merged just now(?). Do you know whether this will be part of the next (or current) nightly build so we could verify if it would be fixed? We are in the process of improving the accessibility of our applications and that might be helpful for our testers.

> Btw, this bug only occurs in iframes. It should not occur in a top level document.

Good to know. Our application runs in an iframe as part of a larger application which I guess is quite unusual.

**Comment by jcsteh** [comment]
It has been merged, but unfortunately, because of the huge scope of this re-architecture (which this fix is part of), it is currently disabled by default. It will be a few months before we are ready to ship it. You could test it yourself in Nightly by flipping a pref, but it will be a few months at least before most users see it.

If this is really a critical blocker for you, there is probably a way I can fix this with the old architecture, but I'm reluctant to invest time in that given where we're at with the new architecture, so I'd only consider this if it was a critical issue for you.

Btw, I see you also mention visiblity: hidden. Anything with visibility: hidden is not exposed to accessibility (as per spec), including live regions. This is also the case in Chrome.

**Comment by dhenneke** [comment]
I don't think it is that critical so we should be able to wait until the remaining parts are ready. It should be fine when we report that it works everywhere except in Firefox for now and that it will be fixed in a newer browser release.

> by flipping a pref

Could you maybe detail what that means 😅.

> Btw, I see you also mention visiblity: hidden. Anything with visibility: hidden is not exposed to accessibility (as per spec), including live regions. This is also the case in Chrome.

Correct, I guess I phrased it wrong: I mean an element that is "visually hidden", e.g. by adding the following CSS:

```
position: absolute;
margin: -1px;
border: 0px;
padding: 0px;
overflow: hidden;
clip: rect(0px, 0px, 0px, 0px);
```

Texts, labels, `aria-describedby`s, etc. that are hidden in this way are read by NVDA when browsing the page, but live regions become silent similar to when they are out of the viewport.

**Comment by jcsteh** [comment]
Once this change lands in Nightly (I'd wait 24 hours at least to be certain), you can go to about:config in your address bar, search for accessibility.cache.enabled and set that to true, then restart Firefox. That will allow you to test this fix. Setting it to false again (and restarting Firefox) will revert to the old architecture.

Regarding visually hidden content, I understand now. This will be covered by the same fix.

**Comment by dhenneke** [comment]
I tested it with the latest Firefox Nightly build (2022-08-16-19-03-18) and it works properly 👍. Thanks again for the quick solution and your ongoing effort. I'm looking forward to the release once everything is done at your side.

**Comment by Adriani90** [comment]
Cache has been enabled by default in Firefox 113, closing as works for me.
