### ISSUE TITLE
Factor programming language terminal is not accessible

### ISSUE THREAD

**Issue by Cleversn** [nvaccess/nvda#14027]
### Steps to reproduce:
1. Download the factor distribution from https://downloads.factorcode.org/windows-x86-64/factor-windows-x86-64-2022-08-17-02-38.zip
2. Unzip the file;
3. Using either the file explorer or a command prompt, enter into the created folder called factor, then run the file factor.com
### Actual behavior:

NVDA doesn't read any output text automatically, nor you can manually read any output using the review cursor.
### Expected behavior:

NVDA should automatically read output texts, and review cursor should detect output texts, as in other command line apps like cmd and PowerShell.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2022.2
#### Windows version:
Windows 11 Pro 21H2
#### Name and version of other software in use when reproducing the issue:
Factor latest development version.
#### Does the issue still occur after restarting your computer?
Yes.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

**Comment by seanbudd** [comment]
Has this been reported to the factor developers?

**Comment by seanbudd** [comment]
It's really up to developers to know how to make their software accessible.
Providing programming support/consulting is out of scope of NVDA.

**Comment by seanbudd** [comment]
If it is the case of NVDA is not handling accessibility information / events properly, we can fix it given a technical description of the problem.

**Comment by Cleversn** [comment]
OK, I'll talk to them.
