### ISSUE TITLE
When modifying accesskey attribute, change not reflected in NVDA's virtual buffer

### ISSUE THREAD

**Issue by RichCaloggero** [nvaccess/nvda#14030]
If modifying the accesskey attribute on an element via javascript, then examining the page, the old accesskey is still announced by NVDA.

Pressing NVDAKey+f5 to refresh NVDA's virtual buffer shows the updated value.

See the following test page:

- http://richcaloggero.github.io/test/browser-hotkeys.html

**Comment by seanbudd** [comment]
Welcome @RichCaloggero,

We are unable to process this issue as it stands.
Please fill out the issue template fully.

Kind Regards,
NV Access Software Developers
