### ISSUE TITLE
Braille doesn't auto update when typing in MS Word

### ISSUE THREAD

**Issue by ainekc** [nvaccess/nvda#14069]
### Steps to reproduce:
1. Connect a Braille display.
2. Open file in MS Word.
3. Start typing.
4. Braille does not update till you for instance use the arrows to move the cursor. 
### Actual behavior:

Braille display does not update while typing. 
### Expected behavior:

The Braille shoudl update as text is typed.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-26283,9173f868 (2022.4.0.26283)

#### Windows version:
Windows 11 Version	10.0.22000 Build 22000

#### Name and version of other software in use when reproducing the issue:
Microsoft® Word for Microsoft 365 MSO (Version 2207 Build 16.0.15427.20182) 64-bit 

Mantis Braille display

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I noticed this about two weeks ago but have been on the alpha channel the whole time
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment]
Is this an issue with NVDA 2022.2?

**Comment by ainekc** [comment]
Just tried 2022.2.2 and no - all working correctly there

**Comment by lukaszgo1** [comment]
Would you be able to check with the latest beta of 2022.3? That way we would be able to establish if this regressed only in Alpha or if this is something to fix for 2022.3.

**Comment by ainekc** [comment]
Still working correctly with 2022.3 beta 4

**Comment by lukaszgo1** [comment]
Please open NVDA settings, go to the advanced panel, check the checkbox stating that you understand the risk, move the to "Registration for UI Automation events and property changes:" drop down list, choose "Globally", apply the changes, restart NVDA and check if braille updates when typing.

**Comment by ainekc** [comment]
Oh found it!


The global registration vs automatic registration doesn't make a 
difference but the UIA enabled setting for Word documents had to be 
changed from "always" to the default "where suitable". (The last time I 
remember looking at the UIA setting for word there wasn't a "where 
suitable" option, and I don't remember if there was a using default 
option, so other people who had UIA always enabled in Word before might 
also unsuspectingly encounter this issue).

**Comment by lukaszgo1** [comment]
Are you saying that When Use UI Automation to access Microsoft Word document controls" is set to "Always" braille fails to update, whereas when it is set to Default (Where suitable)" changes are shown on the braille display. This is pretty concerning, since you're on Windows 11, and with the version of MS Word you're running these two options should behave exactly identical. Could you set the control to "Default (Where suitable)", press NVDA+F1, and post the developer info for the MS Word editor here?

**Comment by ainekc** [comment]
Yeah though only as of some version of NVDA alpha which is later than 
2022.3 beta 4 seemingly


What should the logging level be set to when I do that?

**Comment by lukaszgo1** [comment]
> Yeah though only as of some version of NVDA alpha which is later than 2022.3 beta 4 seemingly

That is even stranger - there was no change which can explain it logically.

>  What should the logging level be set to when I do that?

Does not matter - the developer info is always the same regardless of the log level.

**Comment by ainekc** [comment]
OK here's with the default Word UIA setting

INFO - __main__ (16:44:41.899) - MainThread (860):
Starting NVDA version alpha-26283,9173f868
INFO - core.main (16:44:41.939) - MainThread (860):
Config dir: C:\Users\ainek\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (16:44:41.939) - MainThread (860):
Loading config: C:\Users\ainek\AppData\Roaming\nvda\nvda.ini
INFO - core.main (16:44:42.098) - MainThread (860):
Windows version: Windows 10 21H2 (6.2.9200) workstation
INFO - core.main (16:44:42.098) - MainThread (860):
Using Python version 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 
18:01:55) [MSC v.1900 32 bit (Intel)]
INFO - core.main (16:44:42.098) - MainThread (860):
Using comtypes version 1.1.11
INFO - core.main (16:44:42.098) - MainThread (860):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDrivers.espeak.SynthDriver.__init__ (16:44:42.365) - 
MainThread (860):
Using eSpeak NG version 1.52-dev
INFO - synthDriverHandler.setSynth (16:44:42.445) - MainThread (860):
Loaded synthDriver espeak
WARNING - mathPres.initialize (16:44:42.460) - MainThread (860):
MathPlayer 4 not available
INFO - core.main (16:44:42.460) - MainThread (860):
Using wx version 4.1.1 msw (phoenix) wxWidgets 3.1.5 with six version 1.16.0
INFO - brailleInput.initialize (16:44:42.465) - MainThread (860):
Braille input initialized
INFO - braille.initialize (16:44:42.465) - MainThread (860):
Using liblouis version 3.22.0
INFO - braille.initialize (16:44:42.465) - MainThread (860):
Using pySerial version 3.5
INFO - brailleDisplayDrivers.brailliantB.BrailleDisplayDriver.__init__ 
(16:44:43.485) - MainThread (860):
Found display with 40 cells connected via hid 
(\\?\hid#vid_1c71&pid_c111&mi_00#7&2332323a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})
INFO - braille.BrailleHandler.setDisplayByName (16:44:43.490) - 
MainThread (860):
Loaded braille display driver brailliantB, current display has 40 cells.
INFO - core.main (16:44:43.611) - MainThread (860):
Java Access Bridge support initialized
INFO - UIAHandler.UIAHandler.MTAThreadFunc (16:44:43.670) - 
UIAHandler.UIAHandler.MTAThread (28748):
UIAutomation: IUIAutomation6
INFO - external:globalPlugins.brailleExtender.GlobalPlugin.__init__ 
(16:44:43.890) - MainThread (860):
BrailleExtender 22.08.06:b688253 loaded (0.02s)
INFO - core.main (16:44:44.016) - MainThread (860):
NVDA initialized
INFO - globalCommands.script_navigatorObject_devInfo (16:44:47.942) - 
MainThread (860):
Developer info for navigator object:
name: 'Microsoft Word Document'
role: Role.EDITABLETEXT
processID: 18176
roleText: None
states: State.FOCUSABLE, State.MULTILINE, State.FOCUSED
isFocusable: True
hasFocus: True
Python object: 
<NVDAObjects.Dynamic_WinwordWordDocumentWordDocumentIAccessibleWindowNVDAObject 
object at 0x0A0C2B70>
Python class mro: (<class 
'NVDAObjects.Dynamic_WinwordWordDocumentWordDocumentIAccessibleWindowNVDAObject'>, 
<class 'appModules.winword.WinwordWordDocument'>, <class 
'NVDAObjects.IAccessible.winword.WordDocument'>, <class 
'NVDAObjects.IAccessible.IAccessible'>, <class 
'NVDAObjects.behaviors.EditableTextWithoutAutoSelectDetection'>, <class 
'editableText.EditableTextWithoutAutoSelectDetection'>, <class 
'NVDAObjects.behaviors.EditableText'>, <class 
'editableText.EditableText'>, <class 
'NVDAObjects.window.winword.WordDocument'>, <class 
'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 
'documentBase.TextContainerObject'>, <class 
'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, 
<class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: None
location: RectLTWH(left=570, top=153, width=867, height=547)
value: None
TextInfo: <class 'NVDAObjects.window.winword.WordDocumentTextInfo'>
appModule: <'winword' (appName 'winword', process ID 18176) at address 
74ef790>
appModule.productName: 'Microsoft Office'
appModule.productVersion: '16.0.15427.20210'
appModule.helperLocalBindingHandle: c_long(61782624)
windowHandle: 1966930
windowClassName: '_WwG'
windowControlID: 0
windowStyle: 1442840576
extendedWindowStyle: 16
windowThreadID: 27504
windowText: 'Microsoft Word Document'
displayText: ''
IAccessibleObject: <POINTER(IAccessible) ptr=0x48efb50 at a021a80>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=1966930, objectID=-4, childID=0
IAccessible accName: 'Microsoft Word Document'
IAccessible accRole: ROLE_SYSTEM_CLIENT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, 
STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: None
IAccessible accValue: None

**Comment by ainekc** [comment]
And here's the log when set to always

INFO - __main__ (16:46:03.193) - MainThread (29440):
Starting NVDA version alpha-26283,9173f868
INFO - core.main (16:46:03.453) - MainThread (29440):
Config dir: C:\Users\ainek\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (16:46:03.457) - MainThread (29440):
Loading config: C:\Users\ainek\AppData\Roaming\nvda\nvda.ini
INFO - core.main (16:46:03.601) - MainThread (29440):
Windows version: Windows 10 21H2 (6.2.9200) workstation
INFO - core.main (16:46:03.601) - MainThread (29440):
Using Python version 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 
18:01:55) [MSC v.1900 32 bit (Intel)]
INFO - core.main (16:46:03.601) - MainThread (29440):
Using comtypes version 1.1.11
INFO - core.main (16:46:03.601) - MainThread (29440):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDrivers.espeak.SynthDriver.__init__ (16:46:03.853) - 
MainThread (29440):
Using eSpeak NG version 1.52-dev
INFO - synthDriverHandler.setSynth (16:46:03.937) - MainThread (29440):
Loaded synthDriver espeak
WARNING - mathPres.initialize (16:46:03.945) - MainThread (29440):
MathPlayer 4 not available
INFO - core.main (16:46:03.945) - MainThread (29440):
Using wx version 4.1.1 msw (phoenix) wxWidgets 3.1.5 with six version 1.16.0
INFO - brailleInput.initialize (16:46:03.949) - MainThread (29440):
Braille input initialized
INFO - braille.initialize (16:46:03.949) - MainThread (29440):
Using liblouis version 3.22.0
INFO - braille.initialize (16:46:03.953) - MainThread (29440):
Using pySerial version 3.5
INFO - brailleDisplayDrivers.brailliantB.BrailleDisplayDriver.__init__ 
(16:46:04.973) - MainThread (29440):
Found display with 40 cells connected via hid 
(\\?\hid#vid_1c71&pid_c111&mi_00#7&2332323a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})
INFO - braille.BrailleHandler.setDisplayByName (16:46:04.980) - 
MainThread (29440):
Loaded braille display driver brailliantB, current display has 40 cells.
INFO - core.main (16:46:05.094) - MainThread (29440):
Java Access Bridge support initialized
INFO - UIAHandler.UIAHandler.MTAThreadFunc (16:46:05.158) - 
UIAHandler.UIAHandler.MTAThread (26016):
UIAutomation: IUIAutomation6
INFO - external:globalPlugins.brailleExtender.GlobalPlugin.__init__ 
(16:46:05.369) - MainThread (29440):
BrailleExtender 22.08.06:b688253 loaded (0.02s)
INFO - core.main (16:46:05.497) - MainThread (29440):
NVDA initialized
INFO - globalCommands.script_navigatorObject_devInfo (16:46:10.842) - 
MainThread (29440):
Developer info for navigator object:
name: ''
role: Role.DOCUMENT
processID: 18176
roleText: None
states: State.FOCUSABLE, State.FOCUSED
isFocusable: True
hasFocus: True
Python object: 
<NVDAObjects.Dynamic_WinwordWordDocumentWordDocumentEditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject 
object at 0x064D3350>
Python class mro: (<class 
'NVDAObjects.Dynamic_WinwordWordDocumentWordDocumentEditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject'>, 
<class 'appModules.winword.WinwordWordDocument'>, <class 
'NVDAObjects.UIA.wordDocument.WordDocument'>, <class 
'UIAHandler.browseMode.UIADocumentWithTableNavigation'>, <class 
'documentBase.DocumentWithTableNavigation'>, <class 
'NVDAObjects.UIA.wordDocument.WordDocumentNode'>, <class 
'NVDAObjects.behaviors.EditableTextWithoutAutoSelectDetection'>, <class 
'NVDAObjects.UIA.UIA'>, <class 
'NVDAObjects.window.winword.WordDocument'>, <class 
'NVDAObjects.window.Window'>, <class 
'editableText.EditableTextWithoutAutoSelectDetection'>, <class 
'NVDAObjects.behaviors.EditableText'>, <class 
'editableText.EditableText'>, <class 'NVDAObjects.NVDAObject'>, <class 
'documentBase.TextContainerObject'>, <class 
'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, 
<class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: ''
location: RectLTWH(left=570, top=153, width=867, height=547)
value: None
TextInfo: <class 'NVDAObjects.UIA.wordDocument.WordDocumentTextInfo'>
appModule: <'winword' (appName 'winword', process ID 18176) at address 
6a7f790>
appModule.productName: 'Microsoft Office'
appModule.productVersion: '16.0.15427.20210'
appModule.helperLocalBindingHandle: c_long(55112544)
windowHandle: 1966930
windowClassName: '_WwG'
windowControlID: 0
windowStyle: 1442840576
extendedWindowStyle: 16
windowThreadID: 27504
windowText: 'Microsoft Word Document'
displayText: ''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x3413fe0 at 964cdf0>
UIA automationID:
UIA frameworkID: Win32
UIA runtimeID: (42, 1966930)
UIA providerDescription: [pid:24304,providerId:0x1E0352 Main:Nested 
[pid:18176,providerId:0x1E0352 Main(parent link):Unidentified Provider 
(unmanaged:mso.dll)]; Hwnd(parent link):Microsoft: HWND Proxy 
(unmanaged:UIAutomationCore.dll)]
UIA className: _WwG
UIA patterns available: LegacyIAccessiblePattern, ScrollPattern, TextPattern

**Comment by lukaszgo1** [comment]
It looks like you've accidentally set NVDA to start in compatibility mode. To check if my hypothesis is correct move to the NVDA shortcut, open properties, go to the compatibility tab, and check if "Start this program in compatibility mode with:" is checked or not.

**Comment by ainekc** [comment]
Oh yeah you're right thank you!! I've absolutely no idea how I achieved 
that as I have no memory of even knowing the compatibility tab existed?? 
but there we go. I wonder if possibly it activitated itself somehow 
during the install process, as sometimes I get file in use error the 
first time I try. Anyway, will check for that in future if any similarly 
mysterious issues come up...

**Comment by ainekc** [comment]
And which of the logging categories in the advanced settings should be 
enabled? Just UIA?
