### ISSUE TITLE
please add an advanced speech settings dialog

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#14074]
In the old NV-speech-player NvDA addon, you could adjust many many different speech parameters. Therefore so the user can further tweak ESpeak, especially its Klatt voices, could you please create an advanced speech dialog with a warning checkbox similar to the warning checkbox in the normal advanced settings dialog box? The advanced speech settings dialog would let the advanced user change by using ssliders or edit boxes, many many more parameters, virtually every single parameter of ESpeak's normal formants and especially its Klatt formants. radio buttons would let you choose between changing Klatt parameters or normal parameters and then appropriate parameter settings would appear when you tab to the main settings area. In this advanced dialog, all possible ESpeak parameters could be changed and modified--including all of its tunes or intonation statements. You would hear the changes as you make them. When done, you could give your custom changes a name, save them in either the older ESpeak sapi5 format or the new ESpeak-ng format and then share them with other NVDA users. A restore button would reset all settings back to normal in case you really mess up. Want to adjust ESpeak to inflect like Keynote gold? eloquence? or something of your own creation? no problem. Save a copy of your changes in both the older ESpeak format and another copy in the newer ESpeak-ng format then share with other users. I am tired of people complaining about ESpeak... ok so give us an advanced speech dialog where we can tweak and change to our heart's content and share our changes with older sapi5 ESpeak users and the newer ESpeak-ng users. And since ESpeak runs on android such variants could be imported to the ESpeak of other platforms maybe. not sure about that one though. Please let us tweak and change very advanced ESpeak parameters and save changes with an advanced speech dialog box everything including intonation tunes statements.

**Comment by joshknnd1982** [comment]
I forgot to mention, if you won't add this directly into NVDA at first, implementing it into the core of the project, could someone out there please make an addon with the functionality I request? thanks.

**Comment by joshknnd1982** [comment]
one last thing, changing phonemes and their sounds would be beyond what the advanced speech settings dialog would allow us to do. Or maybe someone could make a separate NVDA addon that lets us much more easily modify phonemes for all languages for both old sapi5 espeak and new espeak-ng...

**Comment by josephsl** [comment]
Hi, as this deals specificlaly with eSpeak NG, I advise asking for an add-on for this one. Thanks.

**Comment by joshknnd1982** [comment]
Refresh my memory… I have to join the addons list to ask for such an addon? Am I correct?

**Comment by joshknnd1982** [comment]
If you read the comments I left on the issue page, I did ask for an addon in a later comment.

But I could also post my request on the addons list itself to ensure it is seen.

**Comment by josephsl** [comment]
Hi,

By the way, before going any further: let us not forget that screen readers are not the same thing as speech synthesizers. These advanced speech settings, if specific to a text-to-speech engine, are exposed by synthesizers themselves, not by screen readers. Nor you can make one synthesizer sound more like another one as this may (and will) involve editing synthesizer source code, not screen reader source code.

Thanks.

**Comment by joshknnd1982** [comment]
Yes. The dialog would expose all possible espeak parameter settings. Currently we can just change speed, pitch, volume and inflection. I would like to change many more though then save these in my own custom variant file.

**Comment by Brian1Gaff** [comment]
I seem to recall that the Espeak project had a lot of that and more in stand 
alone form, whether they were accessible is a whole other issue. Certainly 
ordinary parameters are easy to tweak as its basically a text file. That was 
how I made Quincy.
 My feeling is that a stand alone system is much more useful as it would 
make the ability to change voices  universally, not just for Nvda.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by joshknnd1982** [comment]
Can you put tunes statements into voice variant files? This would be useful because then each variant could have its own unique inflection or speaking style if you wish.

**Comment by joshknnd1982** [comment]
You don’t need skills. You just have to be willing to experiment and play with the numbers. You can teach yourself the skills by playing with the espeak and espeakedit system at sourceforge and seeing what you get… A willingness to experiment is all you need.

**Comment by josephsl** [comment]
Hi,

Note: some of what I'm about to say can sound really harsh to issue readers (apologies in advance):

I'm doing everything I can to not explode in public, and have been trying my best to come up with ways to convey what I'm about to say in a gentle way while taking multiple angles at this issue. But it looks like my patience has finally run out:

I strongly disagree and advise you (Josh) to seriously reconsider what you are saying:

1. You don't need skills, you can play with numbers: I don't know about others reading this issue, but that's an offensive comment for software engineers and anybody who have studied computer science, software engineering, and related disciplines while sitting on top of thousands of dollars in student debt. Sure, we can argue about skill sets and folks can play with numbers (frequency, tone, pitch, rate, and others) if folks are showing willingness to learn additional things along the way. But you call this "experimenting with numbers" and telling folks that you don't need skills. I personally take that as an insult - speech synthesis algorithms require understanding phonetic rules for many languages, dialects and accent variations, knowledge on voice frequencies (hertz), vocal stress, memory usage for text processing, among others. Even if we advertise speech synthesis algorithms as objective, the end product, or for that matter, the perception of speech synthesis results, is highly subjective from person to person.
2. eSpeak, eSpeakedit, and Source Forge: I seriously advise you to dig into eSpeak NG mailing list archives and think about why NV Access sometimes asks people to submit eSpeak NG issues on GitHub- not directly here, not on most add-on repositories, but on eSpeak NG GitHub repo directly. Having played with eSpeakedit, I know what it can do. In your comment, you are effectively trivializing eSpeakedit and its purpose, something that's unacceptable on an issue tracker devoted to screen reader technologies.

I won't comment on what I can tell as the "actual" reason behind this issue as it is way beyond the realm of screen reading and my interpretation may not be the same as others. If it is what I think it is and that's the majority interpretation, then I think it would be best to close this issue as "won't fix".

Thanks.

**Comment by britechguy** [comment]
And I will sign off with this.

Josh, you seem to have no idea, none, of how esoteric a request like this is and how few users would ever, ever use it.  That matters.

NVDA (or any screen reader) has a purpose, and editing speech parameters for speech synthesizers is not among them as a native function.  Nor should it be.

"Language design and refinement" is outside the realm of screen readers.  It's the province of synthesizer developers.

I can't think of another single person who would be really interested in "under the hood" editing of eSpeak voices and/or making the synth sing (literally) than you.  It wouldn't likely even be something that ever crossed their minds.

There are far, far, far more important features and refinements that should be hundreds of items above this one on the development priorities list.  I can think of few of the issues that currently exist in GitHub for NVDA that would not rank far above this one.

This is your pet thing and you need to realize that.

**Comment by joshknnd1982** [comment]
And I will sign off with this also. I can play with the older stuff on sourceforge, accessibly, no addon required.

**Comment by josephsl** [comment]
Hi,

As a final remark, I hope this was a teaching moment for GitHub readers.

**Comment by mazen428** [comment]
How is it a duplicate though

**Comment by Brian1Gaff** [comment]
I'm not sure either, but then github does definitely need a rewrite to make 
a lot of things plainer to newbies. Thanks folks for giving me a headache!
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "Mazen" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Brian Gaff" ***@***.***>; "Comment" 
***@***.***>
Sent: Saturday, August 27, 2022 12:29 AM
Subject: Re: [nvaccess/nvda] please add an advanced speech settings dialog 
(Issue #14074)

**Comment by britechguy** [comment]
> Edit: Never mind what I said.

As an aside, remember that there is a Delete option in the triple dot menu associated with each comment posted to GitHub.  It can come in handy.

**Comment by joshknnd1982** [comment]
Its not necessary because nv-speech-player has been integrated into espeak-ng.
