### ISSUE TITLE
Strange freeze in nVDA when I start it and alt tab to Chrome

### ISSUE THREAD

**Issue by burakyuksek** [nvaccess/nvda#14077]
### Steps to reproduce:
1. Start NVDA and make sure there is another browser and 2-3 other windows running the background
2. Alt tab to focus on chrome.
### Actual behavior:

NVDA freezes for a few seconds and then responds.
### Expected behavior:

NVDA does not freeze
### NVDA logs, crash dumps and other attachments:
[nvda.log](https://github.com/nvaccess/nvda/files/9437704/nvda.log)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2022.2
#### Windows version:
Windows10 latest
#### Name and version of other software in use when reproducing the issue:
Chrome 104 I beleive
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Did not try
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Did not try

**Comment by burakyuksek** [comment]
Hello,
I dont think It is very hard to reproduce, I also forgot to add that I have jaws 2022 installed on that computer. Could that be interfeering somehow?
I could not understand the second item of the list very well. Can you please explain it ina simpler way? I may be able to collect more logs with that information.
Thank you.

**Comment by abdulari** [comment]
Issue reproducible using [NVDA2022.2](https://www.nvaccess.org/download/?nvdaVersion=2022.2) with espeak-turkish.
tested on Windows 10.
