### ISSUE TITLE
Independent setting for report Row/column headers (Document Formatting panel)

### ISSUE THREAD

**Issue by davidacm** [nvaccess/nvda#14075]
### Is your feature request related to a problem? Please describe.
Just a small inconvenience. Sometimes users want to read just row, or colum header, but not both at the same time.

### Describe the solution you'd like
NVDA should allow the user to configure if the user wants to read the header of colums, rows, both, or disabled.

### Describe alternatives you've considered
I checked the documentation to know if this can be done with some option.

### Additional context
In my opinion, the posibility to choose between read just colum or row headers, but not both aht the same time, can be useful when the user is reading a big table, for example in excel.

**Comment by feerrenrut** [comment]
Happy for someone to work on this.
Add a combo box with values for "both", "row header", "column header", "none" and ensure config is upgraded so that "checked" becomes "both" and "unchecked" becomes "none".

**Comment by XLTechie** [comment]
I have had cases where a circular toggle for this would have been very useful, 
especially when the undesired header is overly verbose.

**Comment by CyrilleB79** [comment]
> I have had cases where a circular toggle for this would have been very useful, especially when the undesired header is overly verbose.

@XLTechie, you are commenting in a closed issue.
If your comment is here to ask for a new feature, you'd better open a new issue (feature request template) to get this request considered.

Fortunately, in the specific case, your request is already addressed in NVDA 2022.4 (beta just released today). Look at the unassigned script "Cycle through the possible modes to report table row and column headers" in "Document formatting" category of input gesture dialog.
