### ISSUE TITLE
in Firefox on gmail.com button to switch to basic html mode is not showing in browse mode

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#14076]
### Steps to reproduce:
1. oepn gmail.com in Firefox;
2. try to locate basic html mode button to switch to it.
### Actual behavior:

Button is not visible in browse mode, however it can be located but can't be clicked with object navigation
### Expected behavior:

Button should be visible in browse mode on top of page.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-23944,a2b2e3d6
#### Windows version:
Windows 10Ver2009 (64-bit) build 19044.1766
#### Name and version of other software in use when reproducing the issue:
Firefox 103 release and 106 nightly
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by lukaszgo1** [comment]
cc @jcsteh

**Comment by jcsteh** [comment]
The button has a width and height of 0, so it is considered invisible by NVDA browse mode. This can be seen in Javascript as well using the clientWidth and clientHeight properties, so this isn't just a Firefox accessibility engine issue. I'd say this is a Gmail bug.

**Comment by seanbudd** [comment]
This is very likely a problem with the implementation of the application/website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers
