### ISSUE TITLE
Prevent NVDA to announce "Down" on Qt comboboxes

### ISSUE THREAD

**Issue by CoBC** [nvaccess/nvda#14093]
### Steps to reproduce:
- Go to a Qt application and find a combobox (example in TeamTalk preferences)
- When focus is on combobox, NVDA announce label of combobox and item selected, and add "Down".
I think there was introduced on the NVDA side as a workaround because Qt doesn't integrate expanded or collapsed state, but this has been fixed in Qt6.

### Actual behavior:

- NVDA announce "Down" which cause a double announce of combobox state.

### Expected behavior:

- NVDA should let Qt send state and just announce this

#### NVDA installed/portable/running from source:
- Installed

#### NVDA version:
- alpha-26424,2392d13c (2022.4.0.26424)

#### Windows version:
- Windows 11 build 22621.382

#### Name and version of other software in use when reproducing the issue:
- Tested with TeamTalk Qt 5.11.0.5093 but reproduceable with all Qt apps

#### Does the issue still occur after restarting your computer?
- Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
- Applicable with all NVDA versions

#### If NVDA add-ons are disabled, is your problem still occurring?
- Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
- Yes

**Comment by mazen428** [comment]
It's not a workaround. QT sends the down key as a shortcut key, you can disable this from NVDA object presentation and then uncheck Report object shortcut keys.

**Comment by CoBC** [comment]
Oh OK, not what I thought. Closing.
