### ISSUE TITLE
Provide comments for translators alongside messages to be localized.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1410]
**Reported by orcauser on 2011-03-10 00:17**
To improve the quality of localizations, each message marked for translation should have a translators comment, informing the user where and when the message will be presented. These comments are automatically pulled out along with the messages by the po tools, and presented as part of the comments in the po file. This way the translator can easely reproduce the situation, or find the location where the message is being presented, so that they can check if the correct information is being conveyed. 
 
An example of this is:

# Translators, this is what is spoken when the user moves onto a line that has no contents
#
return _("blank")

I realize that there are many such messages that have no comments at the moment, but if new commits follow this convension, then the old messages that do not have comments can be done at a later date.

Thank you.

**Comment by jcsteh** [comment]
Almost all strings have translator comments now, so closing this. We can just address any that don't as we discover them.
