### ISSUE TITLE
Foobar2000: Reporting the remaining time (Control Shift R) on a file that is over 1 day long produces an error.

### ISSUE THREAD

**Issue by Brynify** [nvaccess/nvda#14127]
### Steps to reproduce:
1: Find an audio file that is over a day long.
2. Open it in foobar2000.
3. In the foobar2000 window, press control shift R.

### Actual behavior:
Nothing is spoken, and an error is appended to the log as follows.

ERROR - scriptHandler.executeScript (21:52:20.186) - MainThread (7396):
error executing script: <bound method AppModule.script_reportRemainingTime of <'foobar2000' (appName 'foobar2000', process ID 11520) at address 85c92b0>> with gesture 'ctrl+shift+r'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 216, in executeScript
  File "appModules\foobar2000.pyc", line 81, in script_reportRemainingTime
  File "appModules\foobar2000.pyc", line 41, in parseIntervalToTimestamp
  File "_strptime.pyc", line 571, in _strptime_time
  File "_strptime.pyc", line 359, in _strptime
ValueError: time data '2d 8:56:36' does not match format '%H:%M:%S'

### Expected behavior:
NVDA should speak the remaining time as days:hours:minutes:seconds if applicable, else hours:minutes:seconds

#### NVDA installed/portable/running from source:
NVDA Installed
#### NVDA version:
2022.2

#### Windows version:
Windows 10 21H2 (64-bit) build 19044.1889

#### Name and version of other software in use when reproducing the issue:
Foobar2000 Version 1.6.11
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, this has been happening ever since the keyboard shortcuts for foobar2000 were added.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by saurabhanand03** [comment]
Hi, can I work on this issue?

**Comment by seanbudd** [comment]
@saurabhanand03 please do

**Comment by saurabhanand03** [comment]
@seanbudd Hi, sorry for the delay in getting back to you, which file has the code to edit? Also, where is the "log" mentioned in the issue?

**Comment by TheQuinbox** [comment]
@saurabhanand03, its under the actual behavior heading. The error is:
ERROR - scriptHandler.executeScript (21:52:20.186) - MainThread (7396):
error executing script: <bound method AppModule.script_reportRemainingTime of <'foobar2000' (appName 'foobar2000', process ID 11520) at address 85c92b0>> with gesture 'ctrl+shift+r'
Traceback (most recent call last):
File "scriptHandler.pyc", line 216, in executeScript
File "appModules\foobar2000.pyc", line 81, in script_reportRemainingTime
File "appModules\foobar2000.pyc", line 41, in parseIntervalToTimestamp
File "_strptime.pyc", line 571, in _strptime_time
File "_strptime.pyc", line 359, in _strptime
ValueError: time data '2d 8:56:36' does not match format '%H:%M:%S'
That should tell you what file to edit :)
