### ISSUE TITLE
NVDA takes an incredibly long time to gain focus on Firefox when the system is under high load

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#14123]
CC @jcsteh 

### Steps to reproduce:

1. Perform a CPU intensive operation, in my case I was compiling a rust application
2. Switch to Firefox while the background operation is in progress, I was reading some docs while waiting for the compile to complete.

### Actual behavior:

NVDA takes up to 10 seconds to gain focus, and a few instances of the following error is logged:

```sh
ERROR - api.setFocusObject (19:16:17.722) - MainThread (15268):
Error updating tree interceptor
Traceback (most recent call last):
  File "api.pyc", line 158, in setFocusObject
  File "treeInterceptorHandler.pyc", line 33, in update
  File "NVDAObjects\__init__.pyc", line 422, in _get_treeInterceptor
  File "treeInterceptorHandler.pyc", line 25, in getTreeInterceptor
  File "virtualBuffers\gecko_ia2.pyc", line 302, in __contains__
  File "comtypes\__init__.pyc", line 856, in __call__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 39, in __call__
exceptions.CallCancelled: COM call cancelled
```

### Expected behavior:

NVDA should not take up to 10 seconds to gain focus on Firefox. I don't see this extreme lag happening when switching focus to other applications like the desktop.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-26524,bc1f92f9 (2022.4.0.26524)

#### Windows version:
10.0.19044.1889

#### Name and version of other software in use when reproducing the issue:
Firefox 105.0b9

#### Does the issue still occur after restarting your computer?
Yes

**Comment by jcsteh** [comment]
We're tracking this in https://bugzilla.mozilla.org/show_bug.cgi?id=1626789. It should be fixed by our current major re-architecture of the Firefox accessibility engine. If you are willing to run Nightly builds, you could give this a try to see if it fixes the problem for you. Note that it is not enabled by default yet even in Nightly. See [this blog post](https://blog.mozilla.org/accessibility/cache-the-world-opt-in-preview/) for instructions.

**Comment by jcsteh** [comment]
Our major re-architecture of the Firefox accessibility engine fixes this. This is now enabled by default in Firefox 113 release.
