### ISSUE TITLE
Applying highlight to a table cell will incorrectly applied the color to the other cell in MS Word

### ISSUE THREAD

**Issue by LittleStar-VIP** [nvaccess/nvda#14143]
### Steps to reproduce:
1. make sure color reporting is enable in nvda document setting page and uia for word is enabled
2. create a empty table with 2x2 rows and columns in a MS word file
3. on row 1 column 2, type the word hello
4. press shift tab and tab again to select the whole cell, i.e. the cell which i have entered 'hello'
5. on the menu selecte the button to hightlight the word with yello
6. tap twice to move to row 2 column 2, this time nvda is reporting that the background color is yellow
7. i have also check by pressing nvda + f, and nvda is also reporting that thebackground  color is yellow
### Expected behavior:
the row 2 column 2 should not be in yellow background as I have only selected the row 1 column 2 cell to highlight

#### NVDA installed/portable/running from source:
portable
#### NVDA version:
nvda 2022.3 beta4
#### Windows version:
Windows home ed 21h2
#### Name and version of other software in use when reproducing the issue:
MS office 365 for enterprise 
16.0.15601.20088
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, this problem also existed in nvda 2022
#### If NVDA add-ons are disabled, is your problem still occurring?
I tested it in a newly created nvda portable copy
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
not tried

**Comment by michaelDCurran** [comment]
I am unable to reproduce this.
Feel free to reopen the issue and provide a NVDA log with log level set to input/output, showing the issue being produced.

**Comment by LittleStar-VIP** [comment]
Hello,
Here is the error lo
[NVDA WORD HIGHLIGHT ERROR.log](https://github.com/nvaccess/nvda/files/9573296/NVDA.WORD.HIGHLIGHT.ERROR.log)
g

**Comment by LittleStar-VIP** [comment]
Sorry I do not know how to reopen this issue,
and also, it is like the error is not always being reproduced.

**Comment by Adriani90** [comment]
@LittleStar-VIP are you still having this issue with NVDA 2024.4.1 in MS Word 365? Please make sure the MS Office 365 is updated to the last build when testing.

I am not sure I can reproduce this issue.
Is UIA for MS Word in NVDA advanced settings set to when suitable? or to "only when necessary"?
Please try with both settings and report whether the behavior is the same or not.

**Comment by LittleStar-VIP** [comment]
Hmm I also cannot reproduce this issue now.
