### ISSUE TITLE
Braille viewer doesn't report formatting for the current word

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#14151]
### Steps to reproduce:

I've separated this out from #14146.  That issue is around the Braille viewer not reporting (in English) all the formatting it is displaying in Braille.

1. Turn on the Braille viewer
2. Go into Word
3. Ensure NVDA's document formatting is set to report "Font attributes".
4. Type some text, say "The quick brown fox".
5. Set some of it bold, say the word "brown".
6. Move to the middle of the word "quick"
7. Move to the middle of the word "brown"

### Actual behavior:

At step 6, with the caret in the middle of the word "quick", the braille viewer displays the symbol (Dots 4,5 and then dot 2) to indicate that the word "brown" is bold.

At step 7, with the caret in the middle of the (bold) word "brown", the "bold" symbol has disappeared and there is no indication that this word is bold.

### Expected behavior:

The Braille display should correctly report the formatting of the current word.

#### NVDA version:

NVDA 2022.3beta4 installed

#### Windows version:

Windows 11 (64-bit) Version: 21H2 (2009), Build: 22000.978 

#### Name and version of other software in use when reproducing the issue:

Office 365 (64-bit) Version: 16.0.15601.20072 

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

NVDA 2021.3.5 (portable)
NVDA 2020.2 (portable)

#### If NVDA add-ons are disabled, is your problem still occurring?

yes

**Comment by michaelDCurran** [comment]
Most likely due to Expand to computer braille at the cursor option being enabled?
Computer braille has no concept of formatting.
I think we need to consider from a product/UX point of view whether we do wish to change this behaviour.

**Comment by Qchristensen** [comment]
Thanks Mick,

Confirming that with "expand to computer braille at the cursor " disabled, the Braille viewer does now show any formatting symbols for the current word as expected.  (Issue #14146 is still present, but that can be dealt with in that issue).

In that case, I'm happy for this issue to be a discussion of whether the behaviour should be kept as is, or changed.  I will bow to others' expertise on that subject.

**Comment by michaelDCurran** [comment]
pr #16864  now provides an option to explicitly show formatting attributes in braille, which is not affected by expand to computer braille. Thus I am going to close this issue as completed.
