### ISSUE TITLE
an issue regarding showing Numbers in Arabic changes and user guide files

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#14169]
Issue raised in [this thread](https://groups.io/g/nvda-translations/topic/an_issue_regarding_showing/93628584?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,93628584,previd%3D1663575543949429190,nextid%3D1632325348684306781&previd=1663575543949429190&nextid=1632325348684306781) of the translators mailing list.

In this thread, هتون فلمبان (Hatoon Felemban) writes:
> Hello all!
> we have a problem with numbers in Arabic changes and User Guide files, Which causes wrong pronunciation and displaying in Braille for versions Numbers in changes file, and Sections numbers in user guide. e.g, The version 2022.2.2 appears in NVDA as 2.20222. so, I made some changes in Localet2t.conf file, seems better when tested Html files which existing in assembla's folder, But after releasing NVDA nothing changed.
> What should i do?
> Thank you for any help.

Firstly, I have offered to make a PR on his behalf with his modification of the `locale.t2tconf` file. But looking deeper in it, things do not seem so clear.

1. According to https://github.com/nvaccess/nvda/pull/13133#issuecomment-989647287 from @feerrenrut:
> > Is updating the translated *.t2t files in this manner safe?
> Not really, this COULD cause merge conflicts. Really only the en should be updated here, and the rest of the files via the screenReaderTranslations Subversion repository.

2. But looking at https://github.com/nvaccess/mrconfig/blob/master/.sh.d/01_svn2nvda.sh from [mrconfig](https://github.com/nvaccess/mrconfig), the only files that are copied from SVN screenreadertranslations repo to GIT are:
  * `nvda.po` (line 76)
  * symbols.dic (line 78)
  * characterDescriptions.dic (line 79)
  * gestures.ini (line 80)
  * changes.t2t  (line 81)
  * userGuide.t2t (line 82)

So what should be done? There are two possible paths:
1. Modify https://github.com/nvaccess/mrconfig/blob/master/.sh.d/01_svn2nvda.sh in [mrconfig](https://github.com/nvaccess/mrconfig) repo to allow translators to push modifications in `locale.t2tconf` from SVN screenReaderTranslations repo.
2. Allow PRs in [NVDA](https://github.com/nvaccess/nvda) repo on non-English `locale.t2tconf` files and check that these modifications are reported in SVN  screenReaderTranslations repo when beta branch is merged to it.

@feerrenrut, @seanbudd could you please clarify this point? Many thanks.

### See also
#13133, #8856

**Comment by seanbudd** [comment]
We aim to confirm an approach soon.

**Comment by feerrenrut** [comment]
Just to clarify, this quote:

>>Is updating the translated *.t2t files in this manner safe?

>Not really, this COULD cause merge conflicts. Really only the en should be updated here, and the rest of the files via the screenReaderTranslations Subversion repository.

The statement was intended to apply to `*.t2t` files rather than `*.t2tconf`. I.E. 
- `user_docs/**/changes.t2t`
- `user_docs/**/userGuide.t2t`

**Comment by seanbudd** [comment]
We intend to go with path (1):

>Modify https://github.com/nvaccess/mrconfig/blob/master/.sh.d/01_svn2nvda.sh in [mrconfig](https://github.com/nvaccess/mrconfig) repo to allow translators to push modifications in locale.t2tconf from SVN screenReaderTranslations repo.
