### ISSUE TITLE
Line indent - Wrong option selected when switching profile

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#14170]
### Steps to reproduce:

1. Create a profile for Notepad
2. While in Notepad, open document settings and set ""Line indentation reporting" on "Tones", then validate.
4. Alt+Tab to Firefox
5. Open document settings and set "Line indentation reporting" on "Speech", then validate.
6. Alt+tab to Notepad.
7. Open document settings window and look at "Line indentation reporting" value.

### Actual behavior:
"Line indentation reporting" is set on "Both Speech and Tones"

### Expected behavior:
"Line indentation reporting" is set on "Tones" as it has been set at step 2 and not modified afterwards.

### NVDA logs, crash dumps and other attachments:
[nvda_combinedOptions.log](https://github.com/nvaccess/nvda/files/9611341/nvda_combinedOptions.log)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2022.3beta5
#### Windows version:
Windows 10 2004 (x64) build 19041.388
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Already present in 2022.2.
And probably much earlier versions also.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes, tested with no add-on.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested but unrelated.

### Cause of the issue
In the GUI, the "Line indentation reporting" is one combobox, but its value is stored thanks to two separate values in the config (one for speech and the other for tones).
### Solutions
To solve this issue, the easiest way is to have GUI controls match the config, i.e. one control matches one and only one config item. Thus there are two options:
1. Upgrade the config to store the required in a single item of type `int` or `string`, not `boolean`.
2. Or modify the GUI to replace the combobox with two checkboxes, one for speech and one for tones; the script controlling this option should then also be split into two separate scripts.

I prefer solution 1., which allow to keep less items in the GUI, especially in the doc formatting settings panel; this also prevent from increasing the number of tabs when navigating in this panel.

NVAccess,
could you please indicate if you agree with solution 1?
Thanks.

**Comment by seanbudd** [comment]
Option 1 seems appropriate.

**Comment by CyrilleB79** [comment]
A similar issue due to mismatch between config and GUI is described below:
### Config options
`config.conf['braille']['messageTimeout']`
and 
`config.conf['braille']['noMessageTimeout']`

### GUI options
In braille settings: "Show messages" and "Message timeout".

### Steps to reproduce
* While in default profile open braille settings
* Set "Show messages" on "Disabled" and validate.
* Create and activate manually a new Test profile.
* Open braille settings
* In test profile set "Show messages" on "Show indefinitely" and validate.
* Open braille settings again

### Actual resimt
"Show messages" option is set to "Disabled".
### Expected result
"Show messages" option is set to "Show indefinitely".

### Note
This issue may probably be fixed without changing the config with a good logic in functions. However, making the config match is clearer.

**Comment by CyrilleB79** [comment]
## Issue 4
Similar issue due to mismatch between config and GUI with cell border options.

### Config options
`config.conf["documentFormatting"]["reportBorderStyle"]`
and 
`config.conf["documentFormatting"]["reportBorderColor"]`

### GUI options
In document formatting settings: "Cell borders"

### Steps to reproduce
* While in default profile open doc formatting settings
* Set "Cell borders" on "Styles" and validate.
* Create and activate manually a new Test profile.
* Open doc formatting settings
* Set "Cell borders" on "Both Colors and Styles" (for Test profile) and validate.
* Deactivate Test profile (turn back to default profile)
* Set "Cell borders" on "Off" (for default profile) and validate.
* Open braille settings again.

### Actual result
"Cell borders" is set on "Off".
### Expected result
"Cell borders" is set on "Both Colors and Styles".
