### ISSUE TITLE
Microsoft: eDAD 3P Bug-NVDA: Users is not able to access/select the list items of 'Switch view options' menu item in browse mode of NVDA.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#14199]
### Steps to reproduce:
 1.Open https://codepen.io/testaccount01/pen/QWrmKay
2. Enable NVDA in browse mode using 'Insert +Spacebar'.
3. Navigate to 'All Documents menu item' and activate it.
4. Observe the issue.
### Actual behavior:
Users is not able to access/select the list items of 'Switch view options' menu item in browse mode of NVDA.
### Expected behavior:

Users should be able to access/select the list items of 'Switch view options' menu item using down arrow key and when user presses Enter , then the list item should get selected in browse mode of NVDA.
#### NVDA version:
2022.2.3
#### Windows version:
21H2(OS Build 22000.978)

**Comment by seanbudd** [comment]
Clicking the button in this code pen does not open a menu, regardless if NVDA is running. Additionally it appears that the code sample is far from a minimal sample.

Please test the steps to reproduce with sample and let us know when a working minimal sample is provided.
