### ISSUE TITLE
Unable to read webpages in microsoft edge, or chrome

### ISSUE THREAD

**Issue by Glenn1212** [nvaccess/nvda#14191]
When I open up microsoft edge and try to go to a website or type in a google search, a window pops up that identifies as a chrome legacy window. 
NVDA states unknown unknown when trying to navigate.
Running the latest version of NVDA and latest version of edge

**Comment by seanbudd** [comment]
Welcome @Glenn1212 ,

We are unable to process this issue as it stands.

- Please fill out the issue template fully.
- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Kind Regards,
NV Access Software Developers
