### ISSUE TITLE
UEB Grade 2 table doesn't seem to be updated in 2022.3

### ISSUE THREAD

**Issue by krzysz00** [nvaccess/nvda#14220]
### Steps to reproduce:
Get the string ` ; ` (with the surrounding spaces) into the Braille rendering (ex. via notepad) with the output table set to "Unified English Braille grade 2"

### Actual behavior:

The Braille rendering is `  ⠆ ` ( 23 )

### Expected behavior:

The Braille rendering of ` ; ` should be `  ⠰⠆ ` ( 56-23 ) per http://liblouis.org/translate/ as a result of https://github.com/liblouis/liblouis/pull/1240, a PR of mine that landed in the version of liblouis shipped with NVDA 2022.3

### NVDA logs, crash dumps and other attachments:

N/A

#### NVDA installed/portable/running from source:

NVDA installed

#### NVDA version:

2022.3

#### Windows version:

Windows 11 Pro 21H2

#### Name and version of other software in use when reproducing the issue:

N/A

#### Other information about your system:

(The hardware I'm using is a Freedom Scientific Braille display, but I'd be surprised if the Braille tables depend on the display in use)

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Earlier versions having this behavior was why I filed a PR against liblouis to fix it

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

N/A

**Comment by seanbudd** [comment]
LibLouis was not updated in NVDA 2022.3.
LibLouis is staged to be updated to 3.23 in 2022.4 via #14112.
Please test the latest NVDA alpha build to confirm your issue has been fixed in 2022.4
