### ISSUE TITLE
NVDA: Screen Reader is not reading listview item 1 of 5 

### ISSUE THREAD

**Issue by cppqtdev** [nvaccess/nvda#14236]
Hi Team
I am facing one issue with NVDA Screen Reader when the focus goes to the Listview in Qt /QML Application
it is not reading 1 of 5 ,Let's total 5 item in the list and current item is 1 . then it should read name of the item and then read selected and then 1 of 5 or 1 of 5 item selected .

it read only the Accessibility name . 

Expected Behavior : Accessibility name and if description available then description and then 1 of 5 item selected if current item is active focus . 

Currently Running Windows 11 and NVDA version Current beta Release .
1.nvda_2020.3.exe
2.nvda_2021.3.1.exe
3.nvda_2022.4beta1.exe -->current release .

Note : When I tested this on Window Inbuilt Screen reader like narrator it read properly and also JAWS also read same behavior as windows narrator screen reader .

Please support if possible .What we need to do ?

**Comment by seanbudd** [comment]
Welcome @cppqtdev,

In future, please do not spam the comments on closed and unrelated issues as you have done today.

We are unable to process this issue as it stands.

- Please fill out the issue template fully.
- To be able to reproduce this issue, we need an example application. Provide a minimal application to reproduce this.
- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Kind Regards,
NV Access Software Developers

**Comment by cppqtdev** [comment]
Hi @seanbudd ,
I am sorry for posting the issue and I am not spamming .But I am facing this issue that why I posted 
Please follow this example code  and you can test with this qt qml application :
if this issue is irrelevant then definitely you can mask as close .
Note : you can also check [Slider](https://doc.qt.io/qt-6/qml-qtquick-controls2-slider.html) using NVDA ( using left and right arrow key) 

https://drive.google.com/file/d/1FQFkaLHinkJ0KIOo_RrTk7fm6GRywUQs/view?usp=sharing

**Comment by seanbudd** [comment]
Identical comments elsewhere:
* https://github.com/nvaccess/nvda/issues/8604#issuecomment-1274628357
* https://github.com/nvaccess/nvda/issues/10285#issuecomment-1274630977
* https://github.com/nvaccess/nvda/issues/9069#issuecomment-1274629098

**Comment by seanbudd** [comment]
@cppqtdev 

Please re-open a new issue using the issue template.
We need a compiled application, we do not know how to compile your code.
We also need the log file, as requested.
