### ISSUE TITLE
Using delayed character descriptions, on each uppercase letter, a double beep is heard.

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#14239]
### Steps to reproduce:
- in NVDA settings and  "speech" category check: Delayed descriptions for characters on cursor movement check box and  Beep for capitals check box.
- now review word with capital letters.
### Actual behavior:

On each uppercase letter, a double beep is heard.
### Expected behavior:

only a single beep should be heard
#### NVDA installed/portable/running from source:
nvda portable
#### NVDA version:
NVDA 2022.3  and alpha
#### Windows version:
Windows 10 21H1 (10.0.19043) workstation

#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Same behavior
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment]
The beep is issued once when the character is read and a second time one second later when its description is read. I agree that the first beep is enough.

Note that there are two other options related to cap reporting: "Capital pitch change percentage" and "Say cap before capitals". The same way, these two options operate twice: once when the character is reported and once one second later when the character description is reported. Do we expect that they operate for character description?

I would say that pitch change should operate as today, that is both when the character is reported and when its description is reported.
For the option "Say cap before", I have no opinion.

It would be good to have the feedback of people with hearing difficulties.

**Comment by paulber19** [comment]
Exact.
But there is no beep for a lowercase letter although the description 
starts with an uppercase letter.
To solve the problem, I think that the description would have to be 
completely lowercase.

**Comment by CyrilleB79** [comment]
> Exact. But there is no beep for a lowercase letter although the description starts with an uppercase letter. To solve the problem, I think that the description would have to be completely lowercase.

No, the case of the description does not matter. E.g. in French, you have "éco" and "youniform" with lower case and the other ones with upper case but the result is always the same. What matters is only the case of the character being described.

**Comment by paulber19** [comment]
Yes, but that's even more disturbing.
Why and what does this second beep signal?

**Comment by CyrilleB79** [comment]
> Yes, but that's even more disturbing. Why and what does this second beep signal? 

The second beep just repeats the same information that was already provided by the first beep. Again, I agree with you. This second beep is useless and disturbing. It should be removed.

**Comment by Brian1Gaff** [comment]
It would probably depend on the synth in use. I sometimes feel that the 
pitch is raised more obviously in Espeak than in most of the natural 
sounding voices. I am not hearing impaired, but one point has been made by 
some who are is that some beeps in nvda seem too high a pitch, but that is 
another issue.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
