### ISSUE TITLE
Espeak reads numbers more than 34 digits as 3647

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#14241]
### Steps to reproduce:
Try to read number 2748573849604723649583647594365737548 With espeak
### Actual behavior:
Espeak read this number as 3647
### Expected behavior:
Espeak should read large number correctly
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-26783,f749e49f
#### Windows version:
Build 19044.2006
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2022.3 behave normally
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment]
This is an issue on eSpeak's side. Here is the ref that was not present in initial description: https://github.com/espeak-ng/espeak-ng/issues/1385.

**Comment by beqabeqa473** [comment]
Please update espeak to the commit which fixes this issue.
Pr espeak-ng/espeak-ng#1458
