### ISSUE TITLE
Build with many CPUs on appVeyor

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#14299]
### Is your feature request related to a problem? Please describe.
Problem: long builds of appVeyor.
### Describe the solution you'd like
Recently, I saw the following message in appVeyor console:

> Warning: Building with 1 concurrent job while 2 CPU threads are available. Running SCONS with the parameter '-j2' may lead to a faster build.

Is there a way to detect the number of CPUs on appVeyor and pass it as parameter?

### Describe alternatives you've considered
Keep builds as they are today.
### Additional context
N/A

**Comment by josephsl** [comment]
Hi, I think we tried this before, but the downside is that we lose track of build progress, specifically reporting test results. Thanks.

**Comment by seanbudd** [comment]
According to this discussion https://github.com/nvaccess/nvda/pull/13226#issuecomment-1009646496, it doesn't improve performance and also makes logging non-linear and harder to follow.

Closing this as won't implement.
