### ISSUE TITLE
Line number reading problem in windows notepad

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#14318]
### Steps to reproduce:
1. turn on the reporting of line numbers in document formatting settings,
2. type some text in the notepad application, the test should be placed in multiple lines
3. navigate through lines using arrow keys.
### Actual behavior:

NVDA doesn't report line numbers in the windows notepad application
### Expected behavior:

NVDA should speak line numbers
### NVDA logs, crash dumps and other attachments:
not applicable
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA version alpha-27037,e4305a44

#### Windows version:
Windows version: Windows 11 22H2 (10.0.22621) workstation

#### Name and version of other software in use when reproducing the issue:
11.2209.6.0
#### Other information about your system:
none needed
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, latest stable
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by feerrenrut** [comment]
NVDA used to report line numbers.
When using notepad now, UIA is being used.
When using UIA to interact with notepad, we can't report line numbers.
The richEdit API has support for fetching line numbers.
It looks like Notepad has changed the window class used for the edit control, so now we no longer refuse to use UIA for that control. See `badUIAWindowClass`.

Fixing this may be as simple as adding the new Window class to the `badUIAWindowClass` list.

**Comment by feerrenrut** [comment]
The window class now being used on Windows 11 is `RichEditD2DPT`

**Comment by josephsl** [comment]
Hi,

I actually advise against labeling Notepad edit field as bad UIA window since:

1. It causes NVDA to repeat the line you've entered when Enter key is pressed.
2. If there is text followed by a blank line at the end of a file, the content of the previous line is repeated instead of NVDA saying "blank".

I think a much better strategy would be creating an overlay class for the document edit field and do something about announcing line numbers.

Thanks.

**Comment by Aarushb** [comment]
Hi,
This seems to be fixed in the latest NVDA version (2023.1 stable).
I am running an installed copy, Windows 11 22H2 (AMD64) build 22621.1413
@feerrenrut

**Comment by Adriani90** [comment]
Thanks for the update. Closing as works for me.
