### ISSUE TITLE
Windows OneCore seslerinde düzeltme

### ISSUE THREAD

**Issue by haruncetinkaya306** [nvaccess/nvda#14310]
Türkçe dilinde, Windows OneCore sesleri sentezleyicisinde, Microsoft Tolga, aşağıdaki karakterleri seslendirmiyor:
â
ê
î
û
x
Bu karakterleri, yazarken de, okuturken de seslendirmiyor. Sadece, x karakterini yazarken seslendiriyor ama onu da okuturken seslendirmiyor.

**Comment by OzancanKaratas** [comment]
Please close this issue. The user has reported an issue that needs to be addressed by Microsoft.
