### ISSUE TITLE
I don't know if it matters, but after cloning the NVDA repository,  there is a file detected and quarantined by Windows Defender.  It is: Backdoor:PHP/Dirtelti.HAGrave       file:F:\nvdaproject\nvda\nvda\include\espeak\chromium_extension\index.php   It is detected: - either when trying to copy the nvda folder, - or when you try to open it with notepad++.

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#14328]
I don't know if it matters, but after cloning the NVDA repository,
 there is a file detected and quarantined by Windows Defender.

It is:
Backdoor:PHP/Dirtelti.HAGrave
      file:F:\nvdaproject\nvda\nvda\include\espeak\chromium_extension\index.php

It is detected:
- either when trying to copy the nvda folder,
- or when you try to open it with notepad++.
### Actual behavior:

file quarantine
### Expected behavior:

No quarantaine

**Comment by seanbudd** [comment]
This is a file from the eSpeak-ng repository: https://github.com/espeak-ng/espeak-ng/blob/master/chromium_extension/index.php

I suggest opening an issue with eSpeak: https://github.com/espeak-ng/espeak-ng/issues

**Comment by michaelDCurran** [comment]
this is in espeak. Please report this to the espeak-ng project:
https://github.com/espeak-ng/espeak-ng/
