### ISSUE TITLE
SConstruct and readme: try usin Windows 11 SDK 10.0.22621 when compiling NVDA

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#14337]
Hi,

A small follow-up to #13867 

### Background
Whenever new Windows SDK's are published, NVDA project has shown interest in using latest released SDK. This means Apveyor must be checked to make sure:

* There is a Visual Studio image identical to the one used for local compilation.
* The VS image on Appveyor includes the target Windows SDK release.

While looking into #13867, it was observed that Windows 11 SDK 10.0.22621 was released for use by developers (comment posted in August 2022). Since then, Windows 11 Version 22H2 (2022 Update) did come out in September with the build number of 10.0.22621. Due to use of Visual Studio 2019 tools to build Microsoft UIA library, NVDA project could not upgrade to pure VS 2022 environment for compiling NVDA locally, and Windows 11 SDK 10.0.22621 was included in VS 2022 image but not 2019 environment on Appveyor.

### Is your feature request related to a problem? Please describe.
Now that NVDA can be built locally via Visual Studio 2022, ask developers to use Windows 11 SDK 10.0.22621 when building NVDA locally, starting with 2023.1.

### Describe the solution you'd like
Edit readme to favor Windows 11 SDK 10.0.22621. This will require looking into using VS 2022 image on Appveyor to make sure things are working correctly (separate issue).

### Describe alternatives you've considered
Leave things as is, although eventually Appveyor YAML file will need to be edited to favor VS 2022 image if planning to use the newer Windows SDK.

### Additional context:
See Visual Studio 2022 pull requests.

**Comment by feerrenrut** [comment]
Appveyor is still using Visual Studio 2019, the most recent SDK available on this image is `Windows 11 SDK/WDK (build 10.0.22000.1)` . Our recommended / official build process should match, the appveyor build is the standard.
Until the appveyor image is updated, the SDK specified must stay the same.

**Comment by seanbudd** [comment]
Closed via #14313
