### ISSUE TITLE
NVDA browse mode does not recognize aria-hidden false attribute with input checkbox

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#14339]
### Steps to reproduce:
For example, there is a agreement section.
There is a checkbox that agree all detailed agreements.
And there is a button that expand or close detailed agreement checkboxes.
If I expand or close this area, the checkboxes will be shown or hidden with aria-hidden false and true, tabindex -1 and 0.
Because this area is hidden or shown with css animations not display:none and block attribute.

### Actual behavior:
If checkbox is hidden with aria-hidden true and tabindex -1, NVDA browse mode also hide the checkbox.
But even if aria-hidden false with tabindex 0, NVDA browse mode does not recognize checkbox.
So if I pres stab, NVDA speak nothing, because focus stay checkbox, but NVDA does not reconize it.
You can watch [demo video](https://nv-a11y.synology.me/wp-content/uploads/kboard_attached/5/202211/6366119aec90d8967069.mp4).

### Expected behavior:
NVDA should recognize checkbox with aria-hidden false attribute.
### NVDA logs, crash dumps and other attachments:
Not applicable
#### NVDA version:
alpha latest
#### Windows version:
Windows 11
#### Name and version of other software in use when reproducing the issue:
Chrome latest

**Comment by feerrenrut** [comment]
Welcome @khsbory,
We are unable to process this issue as it stands.
- To be able to reproduce this issue, we need a code sample. Please provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/) or including a html code snippet in this issue.
- Please also be explicit about the precise speech or braille you expect vs what you actually get.

This stops us from having to make many assumptions about the issue you are reporting, saves us time, and makes a successful resolution much more likely.

I'm going to close this issue for now, we can re-open it if a sample is presented.
