### ISSUE TITLE
Infinite loop in Handy Tech braille display driver

### ISSUE THREAD

**Issue by burmancomp** [nvaccess/nvda#14346]
When using automatic detection and Caiku Albatross braille display is plugged in and powered on, Handy Tech driver may get to infinite loop.

Opposite to many displays Albatross does not wait that driver asks if it is present but it sends continuously its initial packet until driver sends to it quit packet. Init packet consists of two bytes: \xff (init byte which tells that the packet is init packet) and settings byte which includes display settings like number of cells and status cells. Settings byte value can be anything between \x00 and \xff.

Albatross has same FTDI chip with VID 0403 and PID 6001 as some Handy Tech models have. Part of Albatross settings byte values cause infinite loop in Handy Tech driver detection process.

Maybe @FelixGruetzmacher or @leonardder could look at this.
### Steps to reproduce:
- select Automatic from NVDA's braille display list and save NVDA settings
- shutdown NVDA
- change Albatross settings from its internal menu so that its settings byte value is \xe5 or \xfe (quite likely there are also other values raising the issue)
- switch Albatross off and then on
- connect Albatross with USB cable if not already connected
- run NVDA

### Actual behavior:
Continuous beep sounds, speech seems to work as expected.
### Expected behavior:
No continuous beep sounds.
### NVDA logs, crash dumps and other attachments:
[nvda.log](https://github.com/nvaccess/nvda/files/9960027/nvda.log)
#### NVDA installed/portable/running from source:
source
#### NVDA version:
source-master-f674505 (2023.1.0.0)
#### Windows version:
Versio 10.0.19045 Koontikäännös 19045
#### Does the issue still occur after restarting your computer?
Yes

**Comment by leonardder** [comment]
What driver is supposed to be used for these displays?

**Comment by burmancomp** [comment]
The problem seems to be in `_handleInputStream` function. When unknown `modelId` is detected, `RuntimeError` is raised. Because Albatross sends new bytes continuously, hwIO `notifyReceive` function calls handyTech `_serialOnReceive` which in turn calls `_handleInputStream`. Raising `RuntimeError` does not unfortunately stop this.

Ugly solution could be to add following line before raising `RunTimeError` on line 862:

`					self._dev._onReceive = None`

No doubt, there are better solutions, and I do not have Handy Tech display to test if there are some side effects. However, from Albatross perspective this is one way to solve the problem: with this added line automatic detection seems to progress and reach Albatross.

**Comment by leonardder** [comment]
Could you please try the following?

1. Set your NVDA to no braille
2. Restart NVDA
3. From the braille display selection dialog, select the handy tech driver (no longer automatic)

Could you tell whether you're getting an error message or does this result in an endless loop again?

**Comment by burmancomp** [comment]
Error only.

**Comment by leonardder** [comment]
Could you please try latest alpha build. I have the feeling that a fix for this is an unexpected but yet pretty nice side effect of #14147.

**Comment by burmancomp** [comment]
Yes, it seems to resolve this problem.

I got once (I think at very first run) when testing with code containing also Albatross Driver one `AttributeError` and `TypeError` in handyTech.py but I cannot reproduce them with official source code or code including Albatross driver.

I think I can close this issue.
