### ISSUE TITLE
Streamline importing of addon directories for python packages

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#14340]
### Is your feature request related to a problem? Please describe.
For addons, the several directories are added to the python package path using a function in the config module. This needs refactoring:
https://github.com/nvaccess/nvda/blob/f674505671e6f170bd33b2902ad7a7eb423df097/source/config/__init__.py#L487

### Describe the solution you'd like
1. Move the function to addonHandler instead.
2. Instead of calling `addConfigDirsToPythonPackagePath` in the initialize function of the several modules like braille, globalPluginhandler and vision, let addonHandler do this.

### Describe alternatives you've considered
Leave as is

**Comment by feerrenrut** [comment]
Happy to see a prototype for this.
It'll need to be clear whether it affects backwards compatibility, I suspect it can be done without any impact, but it will need to be considered carefully.
