### ISSUE TITLE
NVDA sometimes ignores Chrome, works fine with other browsers and other apps

### ISSUE THREAD

**Issue by brennanyoung** [nvaccess/nvda#14354]
Not the first time I've experienced this, but NVDA is completely ignoring Chrome for me today. I've tried restarting NVDA, and made sure I have the latest version, but when I click on a chrome window, or alt-tab to Chrome, NVDA still thinks it's focused on the app that was previously frontmost. It's as if Chrome does not exist.

### Steps to reproduce:
I wish! This happens quite rarely with no other obvious clues. The only thing I can mention is that chrome had been running for a couple of days before I started NVDA. Chrome and NVDA are up-to-date. No bleeding edge nightly builds.

### Actual behavior:
NVDA acts as if I am still in the previously frontmost Windows application, whichever that may be. "Next" shortcuts allow me to navigate the content/UI in that app. 

Pressing TAB focuses things correctly in the browser, but NVDA says nothing at all. Keypresses are announced (for example NVDA is announcing these keystrokes and I am typing in Chrome).

### Expected behavior:
Expected behavior is the normal behavior.

#### NVDA installed/portable/running from source:
Installed 

#### Windows version:
10

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Updated from next-last to latest and no improvement.

**Comment by michaelDCurran** [comment]
I have never seen this before, thus we'll need to collect some info from your system.
When this starts happening again, Can you please:
1. In NvDA's General settings, set log level to debug
2. In NvDA's Advanced settings, in the Debug logging list, enable the MSAA option
3. Try to interact with Chrome for a while, ensuring you are reproducing the issue you describe
4. Open the NVDA log viewer with NVDA+f1, Save the log file and email it to `info@nvaccess.org` noting this issue #14354

Your log file will hopefully give us detailed info as to what is going on.

**Comment by seanbudd** [comment]
We're closing this issue until further information can be provided

**Comment by brennanyoung** [comment]
I sent you my log file, did you not receive it?

**Comment by seanbudd** [comment]
Sorry @brennanyoung, we didn't receive this, can you send it to again to info@nvaccess.org?

**Comment by seanbudd** [comment]
Closing as abandoned
