### ISSUE TITLE
NVDA will not read the browser window shown in Windows sign-in/forgot my pin screen

### ISSUE THREAD

**Issue by enessaribas** [nvaccess/nvda#14368]
### Steps to reproduce:
1. Using 2022.3
2. With a pin for sign-in as an authentication method
3. Click on the forgot my pin link at sign-in.

### Actual behavior:
The NVDA startup sound plays, and there is no speech. 
Speech does not return until this browser dialogue is closed with the system menu at alt space.

### Expected behavior:
NVDA reads the contents of the browser window that appears upon clicking this link. 
Narrator is currently necessary to navigate this dialogue.

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
alpha-27145,0a97d209 

#### Windows version:
windows 11 22h2 (OS Build 22621.819)

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by josephsl** [comment]
Hi,

Likely cause: cannot obtain necessary information to render browse mode for this screen as it is entered from a secure screen.

Thanks.

**Comment by enessaribas** [comment]
is there a possible solution to this problem?

**Comment by josephsl** [comment]
Hi, this may require reworking the secure/lock screen code so browse mode can work under special circumstances, as the browser window is invoked from the secure screen. CC @buddsean

**Comment by TheQuinbox** [comment]
CC @seanbudd

**Comment by seanbudd** [comment]
The PIN reset workflow happens on a temporary user profile, and uses an MS edge spartan window.
It is currently unclear how NVDA can differentiate between this temporary profile and an ordinary profile while Windows is locked.
Further technical investigation is required.

**Comment by Brian1Gaff** [comment]
Sounds to me like Microsoft need to change this, so it can be uniquely 
identified by a screenreader.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by seanbudd** [comment]
@enessaribas  this should now be fixed on alpha as of [alpha-27325,304ea7a3](https://www.nvaccess.org/files/nvda/snapshots/alpha/nvda_snapshot_alpha-27325,304ea7a3.exe).

We will release this into 2022.3.3 and 2022.4beta4
