### ISSUE TITLE
Unable to view command line output using the review cursor, the navigator is locked in a list item with class name 'MultiaskingViewFrame'.

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#14377]
### Steps to reproduce:
[testconsole.py.txt](https://github.com/nvaccess/nvda/files/12715627/testconsole.py.txt)

1. Use python to execute the above script in cmd
2. Alt+Tab to switch to other windows, and then back to the cmd window
3. Try to review the output in CMD
4. Press alt+Space, X to maximize the CMD window.
5. Alt+Tab to switch to other windows, and then back to the cmd window
### Actual behavior:
Perform step 3: You cannot use the review command to review the cmd window. At this time, the navigator’s window class name is 'MultiaskingViewFrame'.
Perform step 4: You will be able to review the CMD window again
Perform step 5: You cannot use the review command to review the cmd window. At this time, the navigator’s window class name is 'MultiaskingViewFrame'.
### Expected behavior:
The cmd output can be reviewed as expected.
### NVDA logs, crash dumps and other attachments:
[log.txt](https://github.com/nvaccess/nvda/files/12717419/log.txt)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA2023.3Beta2

#### Windows version:
Windows 10 22H2 (x64) build 19045.2251
#### Name and version of other software in use when reproducing the issue:
Windows CMD
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I can reproduce this using NVDA-2022.4
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by cary-rowen** [comment]
Found no further information, I'll close this for now, and reopen when definitive information becomes available.

**Comment by cary-rowen** [comment]
I found steps to reproduce the problem.
Execute a script with a lot of output, and you'll notice that NVDA behaves strangely, as described in the description.
[testconsole.py.txt](https://github.com/nvaccess/nvda/files/10986545/testconsole.py.txt)
Please execute the above script in cmd:
```python testconsole.py.txt```

**Comment by cary-rowen** [comment]
## Steps
1. Execute the above script
2. Alt+Tab to switch to other windows, and then back to the cmd window
3. Try to review the output in CMD
## actual performance
* NVDA cannot navigate the CMD window, or even focus it.
* You can no longer switch review modes and use object navigation in the CMD window.

**Comment by CyrilleB79** [comment]
With the script testconsole.py.txt running, NVDA is completely busy in cmd window or even in other windows and does not speak anymore. Visually, I can see that the cmd window's content is updating during many minutes.
I have had to kill NVDA (with Kill NVDA add-on) and then to kill python (`taskkill /f /im python.exe`)

**Comment by Adriani90** [comment]
cc: @michaelDCurran, @seanbudd

**Comment by Adriani90** [comment]
cc: @codeofdusk

**Comment by cary-rowen** [comment]
Hi @CyrilleB79 

I'm still plagued by this bug.
cc @codeofdusk Do you think this might be console related?
For example, when executing `scons source` to generate an NVDA source code tree, and in scenarios with a large amount of text output.
Could you suggest a more accurate title for this Issue?

Thanks

**Comment by cary-rowen** [comment]
I edited it too many times and it may have caused confusion, so I will reopen an issue.
