### ISSUE TITLE
Tab names not reported when switching in file explorer on Win11

### ISSUE THREAD

**Issue by diegomatos16** [nvaccess/nvda#14388]
When creating multiple tabs in file explorer, when pressing ctrl+tab to alternate tabs, NVDA announce only the folder name focused.
Teste using NVDA 2022.3 and higher, windows 11.

**Comment by josephsl** [comment]
Hi,

Note: this is part of tabbed File Explorer introduced in Windows 11 22H2 Moment 1 (October 2022).

Technical: UIA element selected event is fired when switching between tabs, sometimes multiple times for the same tab. We can try detecting this and let NVDA announce the name of the tab being switched to, but then on braille display, this will be quickly replaced by the focused control information.

Thanks.

**Comment by feerrenrut** [comment]
This is a new feature in Windows 11, is not supported by NVDA yet. I'd be happy to see a contribution for this.

@diegomatos16 in future please fill in the issue (new feature, bug) template, it helps to ensure that the information we need is captured.

**Comment by josephsl** [comment]
Hi,

2023 update: see #14588 for an example of how to resolve this - the mechanics between tabbed Notepad and File Explorer tab switching are the same. In fact, Windows App Essentials add-on 23.02 will resolve this issue, with a potential pull request for NVDA Core to be done later.

Thanks.

**Comment by josephsl** [comment]
Hi,

#14588 is now a thing, so let's resolve this issue - pull request coming very soon. The biggest difference will be that speech cannot be canceled as it will cut off items view/selected item announcement.

Thanks.
