### ISSUE TITLE
Windows 11 on ARM: "ARM64" is returned for app architecture for AMD64 applications

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#14403]
Hi,

Stemming from a discussion in #14397:

### Background:
#7894 introduced a collection of properties for app modules, one of them being app architecture. The purpose of "app architecture" property is to inform humans and code about which machine architecture the app is designed for. This property internally asks IsWow64Process2 function to return the machine type the process is running under, which is used to figure out if a process is a WoW64 process (x86 on x64, for example). There is a design flaw: in Windows 11 on ARM, it is possible to run x64 apps, causing NVDA to think that this is an ARM64 process when it is not.

### Steps to reproduce:
See #14397 for an example, but to recap: run AMD64 app on a Windows 11 on ARM machine and observe that, in NVDA Python Console, typing "focus.apModule.appArchitecture" returns "ARM64" when it should say "AMD64".

### Actual behavior:

"ARM64" is returned as ap architecture property.

### Expected behavior:

"AMD64" is returned.

#### NVDA installed/portable/running from source:
Installed/portable

#### NVDA version:
2022.3.2

#### Windows version:
Windows 11 22H2 (build 22623 beta)

#### Name and version of other software in use when reproducing the issue:
None

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
None

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### Solution:
In Windows 11 and later, ask kernel32.dll::GetProcessInformation to obtain actual process machine information (although GetProcessInformation is available in Windows 8 and later, Windows 11 is required since one of the parameters was made available with build 22000).

Thanks.

**Comment by josephsl** [comment]
Hi,

Note that the solution provided will also work on Windows 11 for x64. Thanks.

**Comment by seanbudd** [comment]
Hi @josephsl ,

There was a typo in your description of the issue, which makes it hard to understand. Can you fix it up?

>There is a design flaw: in Windsible to run x64 apps, causing NVDA to think that this is an ARM64 process when it is not.

**Comment by josephsl** [comment]
Hi, thanks for catching this. I’ve been meaning to do a follow-up commit about an error raised by someone, so I’ll take care of PR description while at it (should be done by tonight at the latest, but I would like to request a delayed review/merge after NV Access folks had a chance to test this PR on the ARM64 dev kit). Thanks.

**Comment by seanbudd** [comment]
To clarify, I was referring to the issue. The last sentence in the background section is unclear.

**Comment by josephsl** [comment]
Hi,

Updated - thanks for catching this earlier.
