### ISSUE TITLE
NVDA repeats heading level number in middle of long headings... bug or feature

### ISSUE THREAD

**Issue by fallenturtle** [nvaccess/nvda#14415]
My client has some pretty long headings and while I am working with them to make them shorter, I'm wondering if the way NVDA handles these is correct or a bug. What from I can tell, around character 90 or 95 NVDA will pause at the nearest word and re-annouce the heading level, for example:
"heading    level 2  Two roads diverged in a yellow wood, And sorry I could not travel both And be one traveler, long I   heading    level 2  stood And looked down one as far as I could To where it bent in the undergrowth"

**Comment by seanbudd** [comment]
This issue sounds related to #14394 and #14335.

I am closing this as a duplicate.
