### ISSUE TITLE
Quick nav to content editable elements in an iframe

### ISSUE THREAD

**Issue by ZaphodAndo** [nvaccess/nvda#14414]
### Overview:
Currently when navigating around a page that contains rich text editors such as TinyMCE and CKEditor and pressing `e` to jump to the next text edit field, NVDA complains that `no next edit field` can be found despite there being rich text editors on the page.
This has been brought up before in #5534 and was supposedly fixed in #7461 however this does not seem to have resolved the issue.

### Steps to reproduce:
1. Navigate to a page containing a rich text editor e.g. https://www.tiny.cloud/docs/tinymce/6/full-featured-premium-demo/
2. Press `e` to navigate to the next edit field.

### Actual behaviour:
NVDA Speech: "no next edit field"

### Expected behaviour:
NVDA should navigate to the rich text editor.
NVDA Speech: "Rich Text Area  document  editable  selected"

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Release 2022.3.2

#### Windows version:
Windows 10 Business Version 10.0.19044 Build 19044

#### Name and version of other software in use when reproducing the issue:
Firefox version: 107.0

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviours.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by amirsol81** [comment]
I can duplicate this with NVDA Alpha 27213, Windows 11 22H2 (OS Build 22623.819), Google Chrome V108, and MS Edge V107.

**Comment by Adriani90** [comment]
We don't have any minimal test case e.g. in codepen in order to use it for further investigation, and we didn't get any updates from the initial author since almost 2 years. Closing as abandoned. If you are still having this issue, please comment and we can reopen.
