### ISSUE TITLE
HTML Table elements not being declared when containing less than 6 table rows

### ISSUE THREAD

**Issue by dunnieallstar** [nvaccess/nvda#14418]
### Steps to reproduce:

1. Open Firefox
2. Navigate to https://www.teacherspensions.co.uk/public/privacy.aspx
3. Page contains two HTML Tables (one used incorrectly for styling)
4. Use T key (and SHIFT + T) to navigate between available tables
5. Check NVDA output for Table declaration
6. Only one table is declared when two are available

### Actual behavior:

- Only HTML Tables with 6 or more table rows are declared to the user including number of rows and columns
- HTML Tables with 5 or less Table Rows are not declared to the user, number of rows and columns are also not declared

### Expected behavior:

- All HTML Tables, including number of rows and columns are declared to the user.

**Explanation:** I found a page with 2 HTML tables, one Table being used was being used to style content rather than being used semantically. When testing the NVDA output the table used for styling was being ignored but contained no additional attributes that would hide it from screen readers - no Aria Roles changes are applied, content is not hidden etc. 
I might be incorrect but I was expecting both Tables should be declared.
I edited the HTML to include different HTML Markup and it seems to be that when there are 6 or more <tr> elements, NVDA will declare the table, but not if less <tr> elements are available.
I also tested this on a blank HTML document with no CSS or additional properties to double check and had the same outcome.

### NVDA logs, crash dumps and other attachments:
Issue with screenshots of HTML and NVDA output.
Includes some basic HTML testing documents.
[HTML-Table-Issue.zip](https://github.com/nvaccess/nvda/files/10141543/HTML-Table-Issue.zip)

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Release 2022.3.2

#### Windows version:
Version	10.0.19044 Build 19044

#### Name and version of other software in use when reproducing the issue:
Mozilla Firefox Version 105.0 (64-bit)

**Comment by seanbudd** [comment]
For the sample in the website, NVDA is correctly ignoring a layout table.

Going by the samples in the zip, this seems to be an HTML problem/intended behaviour from web browsers. If you check the accessibility tree in Chrome and Firefox, the browser determines that these are layout tables. In Chrome, all 3 tables in the sample are exposed as layout tables. 
In Firefox, at 6 rows, the accessibility tree guesses the table is a data table.

Adding `role="table"` to data tables should fix this problem for web developers.

**Comment by dunnieallstar** [comment]
Thanks for the help and feedback @seanbudd - I thought using <table> would apply the implicit ARIA Role for all instances, I had no idea browsers were marking these differently as Layout tables. I'll have to dig more into this.

Adding the role="table" and role="presentation" works exactly as intended so we'll make sure to use going forward.

Thanks again!
