### ISSUE TITLE
Some progressbars in thunder bird are not automaticalli reported

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1442]
**Reported by radek.zalud on 2011-04-06 04:36**
When i am sending some message in thunderbird, NVDA does not automaticalli report progressbar. I can find out it only for example pressing NVDA+B,. Also when thunderbird is automaticalli receiving email messages, progressbar is not automaticalli reported. But if i press Ctrl+Shift+T for receiving emails, or if i press send later and then i press send messages, suddenly the progressbar is reported. I have the newest version of thunder bird, but older versions have same problem.

**Comment by leonardder** [comment]
At least for progress bars when sending mail, I can't reproduce this, they are reporting just fine. Same for the receiving progess bar I belief, although I don't see it very often.

Closing as works for me, but please give a shout if you belief this still occurs.
