### ISSUE TITLE
numbers spoken incorrectly

### ISSUE THREAD

**Issue by Nappler** [nvaccess/nvda#14428]
Numbers are spoken incorrectly.

Nuance Vocalizer 5.5 V2.1.3

Worked until NVDA 2021.3.5.

Espeak works correctly.

1.009 €

spken as 1 9 € and not as 1009 €.

**Comment by ruifontes** [comment]
What voice are you using?

**Comment by Nappler** [comment]
I´m using the german voice Steffi. Also tried Anna. Same result

**Comment by ruifontes** [comment]
Sorry, but check if you do not have any dictionary entry...
I have tested Steffi voice and she read correctly...

**Comment by CyrilleB79** [comment]
@Nappler, have you redefined some symbols? I.e. have you a `symbols-de.dic` in the folder `%appdata%\nvda`?

**Comment by seanbudd** [comment]
Closing this as stale. Please resubmit the issue with the proper issue form, and answers for the outstanding questions if you are still experiencing this.
