### ISSUE TITLE
NVDA TAKILIYOR

### ISSUE THREAD

**Issue by haruncetinkaya306** [nvaccess/nvda#14435]
NVDA, windows 11'de, varsayılan uygulamalar kısmındaki dosya türü veya bağlantı türü giriniz bölümünde arama yapıldığında takılıyor.

**Comment by Adriani90** [comment]
Please submit issues only in english, because most developers understand better what you exactly mean. Please also follow the content structure as it is displayed when you open a new issue.

I will close this one since it is not clear what exactly the problem is and what is expected.
