### ISSUE TITLE
Narrator announces the name and expanded/Collapsed state twice for the expandable item under 'Frequently asked questions'.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#14441]
### Steps to reproduce:
1. Launch One Drive application.
2. Turn on Nvda using 'Win + Ctrl + Enter' key.
3. Navigate to the 'Help & Setting' menu button and activate it.
4. Navigate to 'Get help' menu item in 'Help & Setting' flyout and activate it.
5. Navigate to 'Learn How to protect your files]' link present in 'Get help' dialog using tab key and activate it.
6. Navigate to expendable item under 'Frequently Asked questions' using Tab key.
7. Observe the issue that Narrator announces the expanded/Collapsed state for the expandable item twice.

### Actual behavior:
When user activates the the name and Expandable items under Frequently Asked Questions then Narrator announces the state expanded or collapsed twice. The narrator's announcement is 'I can't find the personal vault button expanded I can't find the personal vault button expanded'
Use odc account to repro the issue ODC: odidctest2@outlook.com](mailto:odidctest2@outlook.com

### Expected behavior:
The narrator should announce the name and expanded/collapsed state after the user activates the expandable item only once.
The narrator's announcement is 'I can't find the personal vault button expanded'.

### NVDA logs, crash dumps and other attachments:
[nvda logs.zip](https://github.com/nvaccess/nvda/files/10209198/nvda.logs.zip)

#### Other information about your system:
Version: 22H2
OS Build: 22621.819

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment]
@msftedad, you are writing about "Narrator" and its start-up shortcut key (windows+control+Enter). But here it's NVDA's bug tracker.

Could you update the initial description to clarify or close this issue in case you have posted in the wrong bug tracker?

Thanks

**Comment by seanbudd** [comment]
This issue is invalid
