### ISSUE TITLE
Braille Viewer is not displaying expanded state for treeitem

### ISSUE THREAD

**Issue by kolaps33** [nvaccess/nvda#14443]
### Steps to reproduce:
1. Enable "Braille Viewer" in NVDA Tools menu. 
2.  Navigate into ARIA pattern: 
[https://www.w3.org/WAI/ARIA/apg/example-index/treeview/treeview-1/treeview-1b.html](https://www.w3.org/WAI/ARIA/apg/example-index/treeview/treeview-1/treeview-1b.html)
3. Navigate into "My Documents" tree
4. Expand tree on "Projects" item 
5. Navigate away from "Projects" item 
6. Navigate back to "Projects" item 

### Actual behavior:
Braille viewer is not showing information about expanded state. 
On the other side NVDA narrate "expanded" state. 
![image](https://user-images.githubusercontent.com/22620150/207354076-3b54a221-8aa5-4799-8b40-48d05e22160d.png)

### Expected behavior:
"expanded" state should be displayed as well by braille viewer...

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2022.3.1

#### Windows version:
10.0.22621 Build 22621

#### Name and version of other software in use when reproducing the issue:
Chrome Version 108.0.5359.99 (Official Build) (64-bit)

#### Does the issue still occur after restarting your computer?
yes 

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no, I haven't tried

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
didn't try

**Comment by seanbudd** [comment]
The "-" is the braille shorthand symbol for expanded. This is working as expected.
