### ISSUE TITLE
Card details are read two times by NVDA screen reader-Bot accessibility Issue

### ISSUE THREAD

**Issue by PuspanjaliMuduli** [nvaccess/nvda#14447]
**Steps to reproduce:** 
Enable NVDA Screen Reader
Focus on the any adaptive card button.
observe the screen reader input.

**Actual behavior:** 
While focusing on the adaptive card NVDA screen reader reading the card text as 2 times.

**Expected behavior:** 
While focusing on any adaptive card it should read card text only once.

**System configuration**
NVDA installed/portable/running from source:
Windows 10

**NVDA version:** 
2022.3.1 

Windows version: 10
Name and version of other software in use when reproducing the issue: 2022.3.1 
Other questions
Does the issue still occur after restarting your computer?
Yes

**Comment by seanbudd** [comment]
Welcome @PuspanjaliMuduli ,

We are unable to process this issue as it stands.

- Please fill out the issue template fully. It is unclear what software you are using or what an "adaptive card" is.
- To be able to reproduce this issue, we need a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).
- This is very likely a problem with the implementation of the application/website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers

**Comment by PuspanjaliMuduli** [comment]
Hi @seanbudd,

Could you please help me to share what all details you need to check on this issue.

Regards.
Puspanjali
