### ISSUE TITLE
Log viewer sometimes does not properly regain focus

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1445]
**Reported by geoff on 2011-04-07 21:19**
Sometimes when looking at developer info in the log viewer, I've 
alt-tabbed away from the viewer to look at something else and returned 
to find myself back in the window but not in the edit field containing 
the log.

The only thing I've been able to do is move the navigator to the edit 
field, route the mouse to it and left-click, which returns focus to the 
edit field.

Is this something we can do anything about?

**Comment by feerrenrut** [comment]
Looks related to #4918, perhaps a duplicate.

**Comment by jcsteh** [comment]
Maybe, but if so, it manifests differently. In this case, focus lands in limbo and it doesn't usually occur. In the case of #4918, focus always lands on the first control in the dialog and you can reproduce it by simply switching to another window and back again; e.g. with alt+tab.

**Comment by bhavyashah** [comment]
I doubt #4918 and this ticket are related in any way. The reported issue seems something far more general. Sometimes, when a large number of windows are open or there seems to be a significant processor overload, Alt+Tabbing around doesn't land inside the window and focus properly, just like the Log Viewer example cited here. I do not have any reliable STR or log to offer at the moment, but I shall try to provide the latter whenever next I experience this problem. CC @brian1gaff

**Comment by leonardder** [comment]
I also experienced this problem. It seems to be accompanied by a Windows ding sound.

**Comment by Adriani90** [comment]
I cannot reproduce this issue in NVDA 2019.1.1 and have not seen this problem even in earlier versions. @geoff are you still having this issue?

**Comment by Adriani90** [comment]
@leonardder are you still seeing this issue?

**Comment by Adriani90** [comment]
I am trying to reproduce this one with NVDA 2019.2 RC2 but without success. It works properly for me. @leonardder are you still seeing this issue by chance?

**Comment by Adriani90** [comment]
We do not have any updates from the initial author since years. And I cannot reproduce this issue with NVDA 2019.3 Beta 2. Clsoing as abandoned and works for me. Please comment on it if you are still having this issue and we can reopen it. Thanks.
