### ISSUE TITLE
New nvda gesture to report whole column may have unexpected behavior, probably related to blank cells

### ISSUE THREAD

**Issue by LittleStar-VIP** [nvaccess/nvda#14469]
### Steps to reproduce:
1. open the html file that I have uploaded here.
2. move to the second column, i.e. Close
3. press nvda+ctrl+alt+up or down
4. starting from the third row, nvda is reporting the content of first column, instead of the second column

### Expected behavior:
nvda should consistently report content on the same column

#### NVDA installed/portable/running from source:
portable
#### NVDA version:
nvda 2022.4 beta4

#### Windows version:
Windows 10 home ed 21h2

#### Name and version of other software in use when reproducing the issue:
brave browser

#### Does the issue still occur after restarting your computer?
not tried
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
not tried
#### If add-ons are disabled, is your problem still occurring?
this version of nvda doesn't has any addon installed
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
not tried
[SPY_DividendsAnalysis.zip](https://github.com/nvaccess/nvda/files/10285808/SPY_DividendsAnalysis.zip)

**Comment by seanbudd** [comment]
In my experience both the first and the second column are being read. This is because the first column uses `th` instead of `td`. From what I can tell, this is intended behaviour. Note when you read a row, the headers for each cell are read before the contents of the cell.

Can you confirm this is the behaviour? Maybe Brave is acting different to Chromium. Can you provide a debug log of this bug?

**Comment by LittleStar-VIP** [comment]
@seanbudd 
Two points to add.

1. Sorry I have made a mistake here.
because the column headers i.e. content of the first column and the content of the second column are all numbers, it seems to me that it was reporteing only a set of numbers yesterday. But I carefully listen to it again, in between the header and the content, nvda will say something like row 1, row2, row3 etc, to differentiate the two.

2. Because I literally read from the what's new and also the updated user guide that
the guesture's function is:
'''Reads the column vertically from the current cell downwards to the last cell in the column.'''
And so I am just expecting that the gesture will only report the content of the current column, excluding the column headers.
