### ISSUE TITLE
NVDA2022.3.3 throws error for a split second when computer goes to sleep

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#14475]
### Steps to reproduce:
alt+f4 Click on the sleep option in the dialog.
### Actual behavior:
At this point you will hear NVDA beeping as the error is logged.
### Expected behavior:
There are no errors.
### NVDA logs, crash dumps and other attachments:
[log.txt](https://github.com/nvaccess/nvda/files/10300046/log.txt)

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2022.3.3, 2022.4Beta4 and Alpha-27364,
#### Windows version:
Windows 10 22H2 (x64) build 19045.2364
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Brian1Gaff** [comment]
This also can happen with certain add ons, even when turning off the 
machine. The OCR one for instance. Its does show an error normally as a bit 
of a mixture of errors. My guess is that something is active in nvda that 
gets nonsensical input to it during the sleep or shutting down process. Of 
course you would not hear it on a release version and normally no problems 
occur. However I do tend not to use any of the sleep quick start hibernate 
or whatever Microsoft are calling it this week as sometimes it can return 
with nvda in a strange state.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "Rowen" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Sunday, December 25, 2022 1:51 PM
Subject: [nvaccess/nvda] NVDA throws error for a split second when computer 
goes to sleep (Issue #14475)

**Comment by seanbudd** [comment]
Thanks for reporting @cary-rowen, this is a known case. The error level log will be suppressed in #14457.

**Comment by cary-rowen** [comment]
@seanbudd 
OK, feel free to close this issue.

**Comment by seanbudd** [comment]
We will keep it open to track the problem. Thank you for documenting this issue clearly, it will help reduce duplicates and improves the documentation of the PR to fix it.
