### ISSUE TITLE
input of secure text like a masked social security number is read out loud

### ISSUE THREAD

**Issue by ncsugrad94** [nvaccess/nvda#14476]
### Describe the solution you'd like

User is inputing ssn into a web page. We changed the font to security-disc but do not want to change the input type to password because password managers try to remember and autofill passwords. So we have tried aria-hidden=true and role=presentation to try and prevent nvda from reading the chars typed in the SSN field.  We would like a method to tell nvda not to read out loud the typed chars when the input font is security-disc. 

### Describe alternatives you've considered

Changing to role=presentation seems to work on chrome screen reader.

**Comment by seanbudd** [comment]
I suggest disabling auto-completion rather than changing the aria role

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
