### ISSUE TITLE
NVDA RAM useage keeps steadily climbing in Windows 7

### ISSUE THREAD

**Issue by KevanGP** [nvaccess/nvda#14499]
### Steps to reproduce:
Make sure NVDA is running. Keep checking it's useage of RAM under the processes tab in task manager in Windows 7.

### Actual behavior:
The useage of RAM for NVDA keeps going up from the time NVDA starts, and never stops. Every 10 seconds it goes up a couple hundred k sometimes. In 24 hours I was using over a GB of ram for NVDA. eSpeak is the synth in use and restarting NVDA resets the RAM to normal levels. Before NVDA 2022.3.3, I didn't notice this behavior, but I didn't really look like I do now.

### Expected behavior:
The RAM count should stay relatively the same without a steady climb. I understand needing to go up sometimes, but not constantly.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2022.4
#### Windows version:
Windows 7 Home Premium X64 6.1.7601 Service Pack 1 Build 7601
#### Other information about your system:
Lenovo ThinkPad X230 laptop, about 9.5 years old.

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2022.3.3, same behavior
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment]
@KevanGP does NVDA RAM usage continue to grow and use up all the RAM? i.e. does it surpass 2 GB after 48hrs?

**Comment by KevanGP** [comment]
It becomes unresponsive if not restarted within a day and a half or so.
It works fine on Windows 10, however. My older laptop is just almost 10 years old and don't wanna upgrade it to Windows 10.

**Comment by Adriani90** [comment]
Support for Windows 7 has officially ended in 2020 completely. Since this is probably a fix needed from NVDA's side, I think NV Access can better decide if this should be further investigated or not.

**Comment by seanbudd** [comment]
Closing, we are no longer performing windows 7 bug fixes
