### ISSUE TITLE
NVDA does not toggle focus mode on when focus moves from within an ARIA document back to its parent interactive ARIA listitem

### ISSUE THREAD

**Issue by kloots** [nvaccess/nvda#14495]
### Steps to reproduce:

This bug is a followup to [issue 13357](https://github.com/nvaccess/nvda/pull/13357). The issue is NVDA does not toggle focus mode on when focus is moved from within an ARIA document back to an ARIA interactive list.

1. Open the [CodePen example](https://codepen.io/toddlr/pen/vYaGVzg) 
2. Use tab-key navigation to move focus to the first ARIA listitem of the ARIA list representing the list of messages
3. Observe NVDA automatically toggles focus mode on when the ARIA listitem is focused (this is thanks to the fix for [issue 13357](https://github.com/nvaccess/nvda/pull/13357))
4. Press tab to move focus to the button representing the message sender
5. Observe NVDA **does not** toggle browse mode on despite the button being contained within an element with `role="document"`. (This is due to [issue 12896](https://github.com/nvaccess/nvda/issues/12896).)
6. Press tab once more to move focus to the anchor element representing the time
7. Observe NVDA toggles browse mode on when the anchor is focused
8. Press shift + tab twice to move focus back to the ARIA listitem
9. Observe NVDA **does not** toggle focus mode on when the ARIA listitem is focused

### Actual behavior:
NVDA does not toggle focus mode on when focus moves from within an ARIA document to an interactive ARIA listitem.

### Expected behavior:
NVDA should toggle focus mode on when focus moves from within an ARIA document to an interactive ARIA listitem.

#### Windows version: 10

**Comment by kloots** [comment]
If it helps, I made [a screen recording](https://user-images.githubusercontent.com/40818/210108153-ef7de8a3-8924-4f73-8136-ada36ba3b72a.mp4) to demo this issue.

**Comment by michaelDCurran** [comment]
Just to clarify for anyone reading this: the bug is specific to when the listitem is a parent of the ARIA document. If tabbing from content inside the ARIA document to an adjacent ARIA list item that is not an ancestor, focus mode is correctly switched to automatically.
