### ISSUE TITLE
:before html tag causing screen reader to repeat itself

### ISSUE THREAD

**Issue by mgrayH** [nvaccess/nvda#14505]
### Steps to reproduce:
Go to timesunion.com
Click on Sign In in the top right.
Click the show/hide password eyeball
_The aria-label is repeated 3 times_ ("Showing Password Showing Password Showing Password" or "Hiding Password Hiding Password Hiding Password")
### Actual behavior:
The Speech Viewer output looks like the following:
(a stylized x) 
hiding password
hiding password
hiding password

or 

(a little save icon)  
showing password
showing password
showing  password

It seems that an html :before tag is causing the screen reader to repeat aria-labels multiple times. I found this on stackoverflow:
https://stackoverflow.com/questions/55475027/screen-reader-reads-list-items-multiple-times which is what is leading me to believe it the the :before tag, but to reproduce, you can look at timesunion.com

### Expected behavior:
I would expect it to only say the label once. 

### NVDA logs, crash dumps and other attachments:
It's not crashing and the log only has startup information.

#### NVDA installed/portable/running from source:
installed and portable

#### NVDA version:
2022.4

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
google chrome for the web browser

**Comment by mgrayH** [comment]
is this in progress at all?

**Comment by Adriani90** [comment]
In Firefox it seems NVDA reports this only twice while in Chrome and Edge this is reported three times.

However, I am not sure if NVDA can ignore the before tag HTML. cc: @jcsteh 

it seems the authors of this website wanted to make it the most accessible and might overreached the target. :-)

**Comment by jcsteh** [comment]
The button has aria-live="assertive". This is redundant because the button is focused when it is pressed and label changes are always read on focused elements. The aria-live should be removed by the author.
