### ISSUE TITLE
Landmarks read even if disabled from formatting preferences

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#14519]
### Steps to reproduce:

1. Ensure to use a NVDA alpha (last, previous... I estimate from November at least);
2. open preferences, Document formatting, and disable landmarks reporting;
3. go i.e. to [issues page](https://github.com/nvaccess/nvda/issues);
4. press 3 to find h3 Footer navigation.

### Actual behavior:

NVDA says (voice only, partially translated)
"Footer navigation landmark Footer navigation level 3".

### Expected behavior:

The usual, less verbose
"Footer navigation level 3".

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

NVDA alpha-27446,6dd90020.

#### Windows version:

Windows 10 64-bit 22H2.

#### Name and version of other software in use when reproducing the issue:

Firefox 108.0.2, Google Chrome 108.0.5359.125.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Tested with NVDA 2022.4 portable, no issue.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Not tested.

**Comment by seanbudd** [comment]
I can confirm that this is broken in alpha but not 2022.4. 

I'll perform a bisect to try and track the problem down.

**Comment by seanbudd** [comment]
Bisect determined that #14303 broke this
