### ISSUE TITLE
When the "Paragraph style" is set to "Multi line break" and "Single line break", review the output in the terminal of VS Code has unexpected behavior

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#14522]
### Steps to reproduce:
```c
	for (int i = 1; i <= 10; i++)
{
    printf("%d\n", i);
}
```
1. Use the above code to output an integer from 1 to 10 in the VS Code terminal
2. Set "Paragraph style" to "Single line break" or "Multi line break" in NVDA settings Panel; 
3. Press Ctrl+` to switch to the VS Code terminal;
4. Press Ctrl+UpArrow/DownArrow;

### Actual behavior:
 After a few seconds of silence NVDA reports "No previous paragraph","No next paragraph".
### Expected behavior:
NVDA should be able to navigate the output within the terminal. Like setting the "Paragraph style" to "Handled by application".
#### NVDA installed/portable/running from source:
Installed 
#### NVDA version:
alpha-27446
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.2364
#### Name and version of other software in use when reproducing the issue:
Vs Code 1.74.2
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
None
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by rob-aph** [comment]
@cary-rowen Do you have any idea how to know if the terminal window in VS Code is focused? If we could solve this, I could pass the paragraph navigation keys to the application without attempting paragraph navigation. The TextInfos and window titles through VS Code all look the same, or similar to me, so specific identification of the terminal window may be a challenge.

**Comment by seanbudd** [comment]
@rob-aph you can log NVDA object information on the terminal window by pressing `NVDA+f1` when it is focused

**Comment by rob-aph** [comment]
@seanbudd Yes, thanks. I did that, and the Console terminal window doesn’t look much unlike other windows. One of the text items starts with “Terminal”, and I guess we could key off of that, but it seems a little cheesy to me. (I’m assuming things like window handles, etc., change all of the time, and can’t be used.)

**Comment by josephsl** [comment]
Hi, can we somehow bring in VS Code developers from Microsoft to see if folks can collaborate on solutions? Thanks.

**Comment by rob-aph** [comment]
@josephsl Seems a bit extreme to bring in MS devs at this stage. Are you willing to take a quick look and advise? Or, perhaps I could post the developer info here?

**Comment by josephsl** [comment]
Hi, let’s start with dev info as it can give us a clue as to what kind of object we’re dealing with.

**Comment by josephsl** [comment]
Hi,
Dev info for the terminal window from VS Code:

name: 'Terminal 2, cl.exe build active file Use Ctrl+UpArrow and Ctrl+DownArrow to navigate the terminal buffer'
role: Role.EDITABLETEXT
processID: 24256
roleText: None
states: State.FOCUSABLE, State.EDITABLE, State.FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x0418AA10>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'NVDAObjects.behaviors.EditableTextWithSuggestions'>, <class 'NVDAObjects.behaviors.InputFieldWithSuggestions'>, <class 'NVDAObjects.behaviors.EditableTextBase'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.ia2Web.Editor'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.DocumentWithTableNavigation'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: None
location: RectLTWH(left=678, top=1092, width=12, height=24)
value: ''
TextInfo: <class 'NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo'>
appModule: AppModule(code, appName='code', processID=24256)
appModule.productName: 'Visual Studio Code'
appModule.productVersion: '1.74.2'
appModule.helperLocalBindingHandle: c_long(88794392)
windowHandle: 17307556
windowClassName: 'Chrome_RenderWidgetHostHWND'
windowControlID: 14104256
windowStyle: 1445986304
extendedWindowStyle: 32
windowThreadID: 23688
windowText: 'Chrome Legacy Window'
displayText: ''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x791dc0c at adc120>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=17307556, objectID=-4, childID=-26769
IAccessible accName: 'Terminal 2, cl.exe build active file Use Ctrl+UpArrow and Ctrl+DownArrow to navigate the terminal buffer'
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: None
IAccessible accValue: ''
IAccessible2 windowHandle: 17307556
IAccessible2 uniqueID: -26769
IAccessible2 role: ROLE_SYSTEM_TEXT
IAccessible2 states: IA2_STATE_EDITABLE, IA2_STATE_OPAQUE, IA2_STATE_SELECTABLE_TEXT, IA2_STATE_SINGLE_LINE (13320)
IAccessible2 attributes: 'display:block;tag:textarea;explicit-name:true;class:xterm-helper-textarea;text-align:left;text-model:a1;'
IAccessible2 relations: 

Compare this to the dev info for the editor window:

name: 'Untitled-1.cpp'
role: Role.EDITABLETEXT
processID: 24256
roleText: 'editor'
states: State.FOCUSABLE, State.AUTOCOMPLETE, State.FOCUSED, State.MULTILINE, State.EDITABLE
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x0419FB10>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'NVDAObjects.behaviors.EditableTextWithSuggestions'>, <class 'NVDAObjects.behaviors.InputFieldWithSuggestions'>, <class 'NVDAObjects.behaviors.EditableTextBase'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.ia2Web.Editor'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.DocumentWithTableNavigation'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: None
location: RectLTWH(left=751, top=240, width=2, height=2)
value: '#include <cstdio>\n\nint main()\n[{\n\tfor (int i = 1; i <= 10; i++)\n{\n    cout << i << end;\n}\nreturn 0;\n}'
TextInfo: <class 'NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo'>
appModule: AppModule(code, appName='code', processID=24256)
appModule.productName: 'Visual Studio Code'
appModule.productVersion: '1.74.2'
appModule.helperLocalBindingHandle: c_long(88794392)
windowHandle: 17307556
windowClassName: 'Chrome_RenderWidgetHostHWND'
windowControlID: 14104256
windowStyle: 1445986304
extendedWindowStyle: 32
windowThreadID: 23688
windowText: 'Chrome Legacy Window'
displayText: ''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x2abe844 at 444c300>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=17307556, objectID=-4, childID=-19298
IAccessible accName: 'Untitled-1.cpp'
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: None
IAccessible accValue: '#include <cstdio>\n\nint main()\n[{\n\tfor (int i = 1; i <= 10; i++)\n{\n    cout << i << end;\n}\nreturn 0;\n}'
IAccessible2 windowHandle: 17307556
IAccessible2 uniqueID: -19298
IAccessible2 role: ROLE_SYSTEM_TEXT
IAccessible2 states: IA2_STATE_EDITABLE, IA2_STATE_MULTI_LINE, IA2_STATE_OPAQUE, IA2_STATE_SELECTABLE_TEXT, IA2_STATE_SUPPORTS_AUTOCOMPLETION (38408)
IAccessible2 attributes: 'display:block;tag:textarea;xml-roles:textbox;autocomplete:both;roledescription:editor;explicit-name:true;class:inputarea monaco-mouse-cursor-text;text-align:left;text-model:a1;'
IAccessible2 relations: 

Note: VS Code 1.74.2, a sample C++ file, paragraph navigation set to single line break.

I think a safe solution for now is using an overlay class inside VS Code app module and overriding paragraph navigation commands to force the default value. I'd pay particular attention to IAccesisble2 properties as window class name and handle checks won't be enough. I bet there are other focusable unforcuable containers throughout VS Code, so doing an instance check may not be reliable unless furhter testing indicates it is safe to use it.

Thanks.

**Comment by rob-aph** [comment]
@josephsl Thanks for your input. I think I'm going to try to handle it in the paragraph navigation code, unless this is a bad idea. I am already making exceptions in that code for situations which don't work properly with paragraph navigation.

**Comment by cary-rowen** [comment]
According to my observation, at least since VS Code1.76.1, the terminal output is changed.
The previous Ctrl+Up/DownArrow reading output is no longer applicable, replaced by an editable control, and navigating the output has become easier.
The special case mentioned in this Issue no longer exists.
However, Paragraph navigation should be more precise.
