### ISSUE TITLE
When using UIA to access Word documents, replace the XX centimeters of the indent value with xx characters to ensure the consistency of user experience

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#14542]
### Is your feature request related to a problem? Please describe.
In the paragraph formatting dialog in MS Word, we set the first line indent to be XX characters, but NVDA reports XX centimeters, which confuses users.

Use the object model to access Word documents, press NVDA + F to get formatting information:
> style 正文 楷体 16 pt default color align default first line indent 2 characters line spacing 1.5 lines
Use the UIA to access Word documents, press NVDA + F to get formatting information:
> style 正文 楷体 16.0 pt black on white align justify first line indent 1.13 cm line spacing 1/.5 倍行距
### Describe the solution you'd like

When using UIA to access Word documents, replace the XX centimeters of the indent value with xx characters to ensure the consistency of user experience.

### Additional context
None

**Comment by seanbudd** [comment]
As discussed on #14533, this should only happen for a known set of locales. What languages do you think this is appropriate for @cary-rowen ?

**Comment by cary-rowen** [comment]
Hi @seanbudd 
According to my test, this happens at least in the zh-CN and zh-TW locales. For Chinese users, it is a strange behavior to express the indentation size in inches and centimeters, We are more used to following the options in the MS Word Paragraph Settings dialog.

**Comment by cary-rowen** [comment]
Btw, if this is a bug, do I need to turn this into a bug report, not a feature request?

**Comment by seanbudd** [comment]
I think there is enough information now to work on this problem. Thanks.

**Comment by CyrilleB79** [comment]
@cary-rowen could you check your Word options:
* Open Word options (alt, F, V on my system)
* Select "Advanced options" category
* Tab to the checkbox "Show measurements in character width"
Is this checkbox checked. On French MS Word, it is not by default. I guess it is checked by default on East-Asian versions of Word; could you confirm this?

More generally, I am a bit reluctant to make such specific processing according to locale. If possible, I will try to base how things are reported upon Word option if and when it is available via object model.

**Comment by cary-rowen** [comment]
@CyrilleB79 
I checked the option you mentioned, it is checked by default, when I uncheck it, NVDA behaves the same as MSWord option,
It would probably be nice if NVDA depended on this option.

**Comment by CyrilleB79** [comment]
> @CyrilleB79 I checked the option you mentioned, it is checked by default, when I uncheck it, NVDA behaves the same as MSWord option, It would probably be nice if NVDA depended on this option.

Could you confirm this test is done with UIA? With object model, the options is honored on my side.

**Comment by cary-rowen** [comment]
Hi @CyrilleB79 
More detailed test results are as follows:
## In the UIA enabled state, not checked "Show measurements in character width":
style 正文 等线 10.0 pt black on white align justify first line indent 0.90 cm line spacing 单倍行距

## In the UIA disabled state, not checked "Show measurements in character width":
style 正文 等线 10.5 pt default color align default first line indent 0.899 centimeters line spacing single

## In the UIA enabled state, checked "Show measurements in character width":
style 正文 等线 10.0 pt black on white align justify first line indent 0.90 cm line spacing 单倍行距

## In the UIA disabled state, checked "Show measurements in character width":
style 正文 等线 10.5 pt default color align default first line indent 2.43 characters line spacing single
