### ISSUE TITLE
Add Dictionary Entry dialog should make Case sensitive checkbox ON if a user selects Regular Expression match type

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#14541]
### Is your feature request related to a problem? Please describe.
When using regular expressions in virtually any context, case sensitivity is assumed.  I have never used a regular expression processor where case sensitivity is OFF by default.  You can force it to be off, but that is very seldom done in practice.  A regular expression such as ([A-Z]) is presumed to capture nothing but capital letters.  As the NVDA dictionaries are currently configured, regular expressions are being treated as case INSENSITIVE by default because the checkbox for Case sensitive is unchecked by default.  It never entered my mind that this was being used with regular expressions.  I initially believed that this would only be applied if "anywhere" or "whole word"  matching types were used.

### Describe the solution you'd like
The Add Dictionary Entry dialog needs two changes.  First, the Matching Type should be placed before the checkbox for Case sensitive.  This forces the "review sequence" for the person doing the entry to look at case sensitivity last.  Second, the value for that checkbox should be set based upon what is most logical/common based upon the radio button selected for the Match type.  It should be checked by default if Regular Expression matching is chosen, and unchecked by default if Anywhere or Whole Word is selected.  This makes the actual behavior of the match behave in the way that would be expected by those who use regular expressions as well as anywhere or whole word matching.

### Describe alternatives you've considered
Another alternative would be to present a warning message to the user if Regular Expression matching is selected and the Case Sensitive checkbox is unchecked.  This would not be my preference because it is, essentially, backward from the usual expectation of regular expression writers.  It's also more intrusive as a very great many people using regular expressions would do as I did, ignoring the Case sensitive checkbox because in virtually all regular expression matching contexts case sensitivity is ON by default.

### Additional context
In any case, I believe moving the Case sensitive checkbox to the end position in the Add Dictionary Entry dialog would be better because it makes the end user pay more attention to it, and at the time they're more likely to pay attention to it.

**Comment by josephsl** [comment]
Hi,

For whoever wishing to implement this, you must edit:

* source/gui/speechDict.py
* user_docs/en/userGuide.t2t (documentation)

Both MUST be edited but should be committed separately (I advise doing GUI first, test it, then commit user guide changes). As a bonus, speech dictionary unit tests would be ideal (perhaps in a separate PR). Lastly, please edit the copyright header for the GUI file (mostly update the copyright year). Good luck.

Thanks.

**Comment by XLTechie** [comment]
I would personally support either primary suggested solution, and also the idea of moving the checkbox.

The current mechanism is not ideal.

**Comment by seanbudd** [comment]
The UX proposed would be quite misleading, it would be misleading to change the state of the checkbox based on the radio button for RegEx.

The warning message proposal also seems overly complicated.

Moving the case sensitivity option to after the radio buttons would be a simpler and more intuitive change.

**Comment by britechguy** [comment]
> The UX proposed would be quite misleading, it would be misleading to change the state of the checkbox based on the radio button for RegEx.

I'm sorry, but that is absolutely untrue.  What is grossly misleading is allowing anyone who is accustomed to using regular expressions, where case sensitivity is the DEFAULT in every other context, to have it turned off for NVDA dictionary processing leading to matches where they would not be expected to occur.

I honestly cannot believe that this is not obvious to anyone who uses regular expressions, which I'd hope would be most, if not all, NVDA developers.

Is ANY change planned?

**Comment by seanbudd** [comment]
Without tabbing to the control, it is unclear that the state for "case sensitivity" would have changed when changing the matching type. Users should not expect that another control would change based on changing the match type.
I don't understand how it is misleading, when the explicit value of case sensitivity is set by the dialog.

Your assertion about typical behaviour is not true. For example, the VS Code UX has case sensitivity as a separate control, and off by default even when doing regex searches.

**Comment by britechguy** [comment]
I am going to bump this issue because I still believe it to be critically important.

As a former coder under Unix and having used Linux and other Regex mechanisms, I still assert that the vast majority of them are case sensitive, that is, the regexes Se* and se* would not match the string "See."  Only the first would.  If case insensitivity were wanted for a single character, that would use a character class, [Ss]e*

I seriously doubt that I am the only long-term user of regular expressions who has been caught out by case-insesitivity being the NVDA default without any obvious warning that this is the case.  And over time, I forget this, and the same issues with things being matched that I don't expect to be bites me.

**Comment by CyrilleB79** [comment]
@britechguy, commenting in a closed issue is unlikely to make things move, especially when the issue has been closed for a long time.

If you really think that this issue has been closed erronously or that things have changed since then, please open a new issue. In this new issue, make a reference to the current issue, summarize why it has been closed, and explain why it is not relevant (or not anymore). Thanks.

**Comment by lukaszgo1** [comment]
While indeed for most Unix based tools case sensitivity is assumed for regular expressions, from my experience this is not the case in Windows graphical tools. Both VS Code (as mentioned in the above comment) and Notepad++ are case insensitive when searching using reg ex-es. If your assertion that this is surprising for most NVDA users would be true, we would have a ton of issues about the problem. Yet I didn't see anyone except you complain. While this does not make problem invalid in any way, the fact that the default seems to be good enough for most users, suggests that this is just a typical case in which the default settings, whatever the context, does not suit particular individual.

**Comment by britechguy** [comment]
> While indeed for most Unix based tools case sensitivity is assumed for regular expressions

Key words.

You haven't seen many people complain because the vast majority of NVDA users have no idea of how to use regexes at all.

For those of us that do, and have years of experience with them, having the behaviro match "most Unix environments" makes the most sense, as that's their origin and, as such, that's the reasonable expectation.

Just because "we've always done it backwards" is not a good idea for keeping it that way.  And if the desire is to keep it that way then it should be made very obvious to those setting up regexes that this is being done, and it's not right now.  That's where the biggest problem lies.

**Comment by lukaszgo1** [comment]
>  And if the desire is to keep it that way then it should be made very obvious to those setting up regexes that this is being done, and it's not right now. That's where the biggest problem lies.


It is likely a difference between users who rely exclusively on a screen reader, versus these who do not, but I'm not sure if the original suggestion of moving the case sensitivity check box to the end would improve the situation at all. When scanning the dialog visually I assume the checkbox would stand out more when added at the bottom. But for a screen reader user who navigates with TAB it is pretty common to just set whatever they need to, and activate the default control with enter. In the current arrangement the case sensitivity checkbox is before match type, so is unlikely to be missed. For the same reason changing its state depending on the match type won't work very well, as something like this can be only noticed visually without tabbing again throughout the entire dialog.

**Comment by britechguy** [comment]
@lukaszgo1 

In the end, I've pretty much come to the conclusion that this request is never going to be taken seriously nor addressed, and have made my peace with that to a large extent.

If the "Case Sensitive" state were checked by default, this would have been a non-issue for me from the outset, as I expect case sensitivity in virtually any context in whch I've ever used regular expressions, and there have been plenty.

It will never make sense to me that a tool where, in the vast majority of situations where it's used, case sensitivity is presumed for the opposite to be presumed in NVDA.  It just makes it harder for many of us who've been using regular expressions for decades (literally) and who somehow happen to ignore that checkbox at the end of the dialog.

I routinely use regex testing sites whenever I'm crafting anything but the simplest of regexes, and to a one, they presume case sensitivity unless explicitly specified otherwise.  There's got to be an exception, surely, but not for the ones I've used.
