### ISSUE TITLE
Report status in Braille when downloading files in Chrome 

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#14562]
### Is your feature request related to a problem? Please describe.

As reported by Sergio via email, the status of files is reported in speech, but not in Braille when download files in Chrome.  Having the ability to have this information reported in Braille would be useful for those who rely on Braille either exclusively, or more than speech.

### Describe the solution you'd like

Report that the download is starting and when it is complete, and possibly status in between as needed, as is done in speech.

### Describe alternatives you've considered

I'm not sure if this was deliberately omitted to keep the Braille display uncluttered with constant messages, but if that is the case, perhaps some way of choosing which messages are reported?

### Additional context
I tested using:
NVDA 2022.4.0.27401 
Windows 11 (64-bit) Version: 22H2, Build: 22621.1105 
Chrome Version: 108.0.5359.126 

I noted that Microsoft Edge, Version: 109.0.1518.55 approaches it slightly differently, displaying a message when a file is downloaded and this is reported.

**Comment by josephsl** [comment]
Hi, Edge: uses UIA notification event, resulting in speech and braille announcing file download progress. I bet Chrome does not implement the same event here – perhaps it might be using an alert event. Thanks.

**Comment by Qchristensen** [comment]
It does look like Edge have implemented a different notification than Chrome - although to be clear, NVDA does at least report "Download complete" in speech, it just isn't presented in Braille.

**Comment by josephsl** [comment]
Hi,

Technical: turns out braille output isn't even considered in alert event for IAccessible objects (grrr)!

I'm testing to see if it affects just Chrome or Firefox as well.

Thanks.
