### ISSUE TITLE
Use "tel" prefix to pronounce phone numbers correctly

### ISSUE THREAD

**Issue by xtstoll** [nvaccess/nvda#14563]
### Is your feature request related to a problem? Please describe.
NVDA 2022.4 (using eSpeak) pronounces phone numbers in a long string instead of how pronouncing the numbers one by one. For example, one of one like this "6 3 1 4 4 6 7 1 2 3" rather than in a string like this "6314467123"

### Describe the solution you'd like
When the "tel" prefix (ex: href="tel:+16314467123") has been used, NVDA should understand this is a phone number and process the numbers individually.

**Comment by seanbudd** [comment]
The href is not passed on to the screen reader in a structured way, so this is not feasible. Phone number pronunciation is handled by the synthesizer.
