### ISSUE TITLE
move (Configuration profiles) option from NVDA's main menu to the tools sub menu

### ISSUE THREAD

**Issue by amirmahdifard** [nvaccess/nvda#14571]
### Is your feature request related to a problem? Please describe.
it is not a problem, just the configuration profiles option is a tool if you think about it it should be moved to the tools sub menu
### Describe the solution you'd like
the solution is that to move the configuration profiles to the tools sub menu, and change it's shortcut from c to f or something else, because, the c shortcut in tools sub menu is already exists with the create portable coppy option, so please also change the shortcut
### Describe alternatives you've considered
alternatively we can access the configuration profiles sub menu from the main menu, but i suggest moving it to the tools sub menu and change its shortcut because the c shortcut is already exists in the tools sub menu
### Additional context
i suggest the folowing shortcuts for this option because these shortcuts are empty and not being used in the tools sub menu: f is empty, i is empty, o is empty, u is empty, g is empty, and l is empty: i suggest these shortcuts because these shortcuts are empty, and the leters are also contanes in the configuration profiles word: note: i suggested these shortcuts with out so meny addons, i only have speech history, nvda remote, and addon updater: so some of these shortcuts are may be not empty if you are using other addons too possibly: but actually, i see that some options in the tools menu have one shortcut at the same time, as an example, reload plugins and run COM registration fixing tool, they both have the r shortcut as their shortcut, so may be you can just add it with its own c shortcut, because currently, the c shortcut only has one option in it, so you can add one more option with the c shortcut

**Comment by amirmahdifard** [comment]
@josephsl hello bro, this thing that i'm requesting, i think that it is not an advance and complicated thing, so it's not gonna possibly create other bugs if you change this: if possible for you, please open a pull request for this and move this option, then, this will be the first request that i reported to NVDA and accepted: thank you so much in advance!

**Comment by josephsl** [comment]
Hi,

Configuration profiles is really a settings management feature - it is designed to package a group of settings as though it is a single unit for use in various situations.

Also, I think this is a duplicate of an issue raised a few years ago.

Thanks.

**Comment by amirmahdifard** [comment]
ok
