### ISSUE TITLE
Windows 11 Notepad: status bar retrieval fails if Notepad UI is redesigned, specifically with tabbed Notepad

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#14573]
HI,

Covers current and upcoming Windows 11 Notepad changes:

### Overview
In ealry 2022, Microsoft released Notepad version 11 specifically designed for Windows 11, bringing with it modern Notepad interface and UIA-based text editor control. Almost a year later, on January 19, 2023, Microsoft released Notepad 11.2212 for Widnows Insiders subscribed to dev channel. The most notable change with 11.2212 is tabbed Notepad - that is, multiple files can be opened under one window. This also brings revised UIA tree for Notepad window, specifically the position of the status bar in the UIA tree changes as tabs are opened and closed, causing current status bar retrieval to fail.

### Steps to reproduce:
Prerequisite: Windows 11 Insider Preview build 25281 or later with Notepad 11.2212 and later. For comparison, use current Notepad (11.2210) running on latest stable Windows 11 build (22621 will do):

1. Open Notepad.
2. Type something.
3. Obtain status bar text (NVDA+End in desktop layout, NVDA+Shift+End in laptop layout).
4. In Notepad 11.2212 and later, open a new Notepad tab (for now you must click new tab button).
5. Retrieve status bar text.

### Actual behavior:
In Notepad 11.2212, NVDA does not announce status bar text.

### Expected behavior:
NVDA announces status bar text.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-27590,180c9f2b

#### Windows version:
Windows 11 22H2 beta (build 22623)/dev (25281)

#### Name and version of other software in use when reproducing the issue:
Notepad 11.2210 (stable)/11.2212 (dev)

#### Other information about your system:
Build 25281 is a virtual machine

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Reproducible in NVDA 2022.4

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### Solution
Thankfully status bar is the second to last item in Notepad UIA tree, and this formula also holds true in 11.2212. This can change depending on the progress of tabbed Notepad in coming weeks, but for compatibility, the new position should be used.

Thanks.

**Comment by CyrilleB79** [comment]
@michaelDCurran, @josephsl: I think that this issue should be reopened due to #14574 being reverted in #14620. Could you do it please?

This issue may be closed again when #14622 is merged.
