### ISSUE TITLE
Braille issues with libreoffice writer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1457]
**Reported by AlexTrial91 on 2011-04-12 20:16**
With the last version of libreoffice and I think it’s the same with OOo, I have some issues in braille.
On the one hand when I write I have no feedback on my braille display.
On the other hand when I wish read I have to use the review cursor because when I use the focus cursor I have no feedback.
It’s a critical bug for a braille-user person who would like to switch for an open source solution on a windows environment.

**Comment by leonardder** [comment]
Closing this because this ticket is very old, many things have changed (i.e. IAccessible2 support in LibreOffice). Please request a reopen if you still experience this.
