### ISSUE TITLE
Minimal Win32 checkbox fragment not reading as a checkbox

### ISSUE THREAD

**Issue by yaakovschectman** [nvaccess/nvda#14584]
I am working on a team effort to implement UIA support for an application framework, and our checkboxes are not recognized as checkboxes when using UIA. In order to seek support, I have created a minimal similar win32 application that produces the same behavior. The entire window is treated as one fragment with the checkbox role, indeterminate toggle state, and name "Fragment root", and it provides the Toggle Pattern. NVDA does not speak any indication that this should be a checkbox, so I must investigate what conditions are not met.

### Steps to reproduce:
Build and run the Windows application https://github.com/yaakovschectman/UIA-Repro
Hover the cursor anywhere in the window

### Actual behavior:
"Fragment Root" is read aloud

### Expected behavior:
"Fragment Root - Checkbox indeterminate" is read aloud

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2022.4

#### Windows version:
Version	10.0.19044 Build 19044

#### Name and version of other software in use when reproducing the issue:
Minimal Win32 application

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
None

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by josephsl** [comment]
Hi, can you try with NVDA 2022.4 to see if that makes a difference? Thanks.

**Comment by yaakovschectman** [comment]
I updated to 2022.4. The same behavior is occurring.

**Comment by jcsteh** [comment]
Currently, NVDA mouse tracking is geared towards reading text under the mouse. It doesn't generally read roles (check box) and states (checked). You can configure it to read roles: NVDA menu -> Preferences -> Settings -> Mouse -> Report role when mouse enters object. It won't read states, however. It's not unreasonable to question that behaviour, but that would be a separate feature request.

A better way to test this (which is more consistent with the way most NVDA users would interact with your app) is to make the check box focusable with the keyboard and then focus it.

**Comment by yaakovschectman** [comment]
My team and I seem to have misunderstood some of the keyboard commands and expected functionality, so I will close this as a non-issue.
