### ISSUE TITLE
While using nvidia geforce experience to update nvidia drivers and software, nvda says (and displays) "common-crimsion-window" instead of the actual content while tabbing through the app

### ISSUE THREAD

**Issue by dave090679** [nvaccess/nvda#14586]
### Steps to reproduce:
* start nvidia geforce experience
* tab through the app
### Actual behavior:

nvda displays and speaks common-crimsion-window in very most cases. in very rare cases, nvda displays the actual app controls

### Expected behavior:

nvda should display the actual components while tabbing through nvidia geforce experience
#### NVDA installed/portable/running from source:
tested (and occured) with installed versions of nvda
#### NVDA version:
2022.4
#### Windows version:
Windows 11 Version 22H2 (Build 22621.1105)
#### Name and version of other software in use when reproducing the issue:
NVIDIA GeForce Experience 3.26.0.160
#### Does the issue still occur after restarting your computer?
yes
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Brian1Gaff** [comment]
Having occasionally had the misfortune to try to use Nvidias control panels, 
I'd suggest that if it works correctly then I'd be very surprised.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "dave090679" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Wednesday, January 25, 2023 3:56 PM
Subject: [nvaccess/nvda] While using nvidia geforce experience to update 
nvidia drivers and software, nvda says (and displays) 
"common-crimsion-window" instead of the actual content while tabbing through 
the app (Issue #14586)

**Comment by ABuffEr** [comment]
> Having occasionally had the misfortune to try to use Nvidias control panels, I'd suggest that if it works correctly then I'd be very surprised.

Indeed, NVIDIA Control Panel is quite accessible, but requires object navigation to initially move focus in the correct place.

About Gaming Experience, I doubt that NVDA can take care of it (perhaps with an appModule, maybe), so I limit to report [the latest release](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/releases/tag/v1.16.2) of [this useful tool](https://github.com/ElPumpo/TinyNvidiaUpdateChecker).

Hth.

**Comment by dave090679** [comment]
If I disable browse mode while tabbing through nvidia geforce experience, I can see some more controls. For example, I can see the "Scan for updates" button after activating the second "main-tab-label", which is the "drivers" Tab. 

Displaying the update status is more complicated:
1. select the "drivers tab" on nvidia geforce experience.
2. shift+tab through the geforce experience until you see something like '\xfffc' or you hear "nvidia geforce experience document"
3. use the nvda ocr (nvda+r). 

Sometimes, the gaming overlay gets activated after updating the nvidia driver. The gaming overlay blocks some keyboard shortcuts and I have to disable it for this reason. For me, the following procedure works for disabling the gaming overlay:
1. I open geforce experience
2. I select the second "mainTab" which is the settings tab.
3. I tabbed until I see the list of settings categories. The list items are displayed as "preferences-list-item", I select the first one.
4. In this settings category, there is a checkbox called "generalEnableShareSwitch". After disabling this, the gaming overlay is also disabled.
