### ISSUE TITLE
advanced speech dialog

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#14596]
Could you please create an advanced speech dialog box that would let us create and save our own custom espeak ng voices? This dialog box would give advanced users access to many more advanced espeak features like how with the nv-speech-player addon you could change all kind of formant settings. The advanced dialog would let you adjust espeak's pitch by a much much wider range, adjust headsize, breathiness, and adjust each individual formant. It would also let you base your new voice on pre-existing voices. You could choose klatt6 as your base voice, or the none variant as your base voice and work from there for example. Then it would save your changes in a standard espeak variant file that you could share with others. When you would close and save your changes, NVDA would need restarted for your new voice variant to show up. To delete the new voice variant, you could find a list box with checkboxes check and uncheck the espeak variants you want, hit delete, restart NVDA and they are gone. the old hal for windows95 had a similar advanced voices dialog box years ago.

**Comment by amirmahdifard** [comment]
hi
first, please folow the templates when you are opening an issue, considering others to understand actually what you are requesting on your issue.
2nd, i think that before you opened a such issue with a same request as now too, and people answered you, such as @josephsl 
i mite be incorrect, others can confurm me if i'm rong
thanks.

**Comment by joshknnd1982** [comment]
Should have posted it to the espeak ng github sorry about that feel free to close it if you wish.
