### ISSUE TITLE
NVDA keeps announcing search suggestions in the search field on bing.com

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#14616]
### Steps to reproduce:
Open bing.com and try typing 'python' in the search field NVDA keeps announcing search suggestions.
### Actual behavior:
p
搜索网页 p  清除  1/1000 
p 
y
清除  2/1000 上一条建议 上一条建议我需要举办6人晚宴。你能帮我推荐三道不包括坚果或海鲜的菜吗？ 下一条建议 下一条建议 试试吧 了解详细信息   pixivイラストを中心としたソーシャル・ネットワーキング・サービス popタイピング pdf pdf 結合 PubMed学術文献の検索サイト pc パナソニック poki プロ野球速報 Python汎用の高レベルプログラミング言語     
y 
pixivイラストを中心としたソーシャル・ネットワーキング・サービス popタイピング pdf pdf 結合 PubMed学術文献の検索サイト pc パナソニック poki プロ野球速報 Python汎用の高レベルプログラミング言語    
Python 汎用の高レベルプログラミング言語 python インストール python 入門 python for文 PyTorch 機械学習ライブラリ python if文 PyCharm Pythonの統合開発環境 python 配列 pythonとは python csv 読み込み   
t
清除  3/1000 上一条建议 上一条建议我需要举办6人晚宴。你能帮我推荐三道不包括坚果或海鲜的菜吗？ 下一条建议 下一条建议 试试吧 了解详细信息    
t 
Python 汎用の高レベルプログラミング言語 python インストール python 入門 python for文 PyTorch 機械学習ライブラリ python if文 python 配列 pythonとは python csv 読み込み python range   
h
清除  4/1000 上一条建议 上一条建议我需要举办6人晚宴。你能帮我推荐三道不包括坚果或海鲜的菜吗？ 下一条建议 下一条建议 试试吧 了解详细信息    
h 
Python 汎用の高レベルプログラミング言語 python インストール python 入門 python for文 python if文 python 配列 pythonとは python csv 読み込み python range python list   
o
清除  5/1000 上一条建议 上一条建议我需要举办6人晚宴。你能帮我推荐三道不包括坚果或海鲜的菜吗？ 下一条建议 下一条建议 试试吧 了解详细信息    
o 
Python 汎用の高レベルプログラミング言語 python インストール python 入門 python for文 python if文 python 配列 pythonとは python csv 読み込み python range python list   
n
清除  6/1000 上一条建议 上一条建议我需要举办6人晚宴。你能帮我推荐三道不包括坚果或海鲜的菜吗？ 下一条建议 下一条建议 试试吧 了解详细信息    
n 
Python 汎用の高レベルプログラミング言語 python インストール python 入門 python for文 python if文 python 配列 pythonとは python csv 読み込み python range python list   

### Expected behavior:
I think such a prompt is seriously interfering with my typing and it should be shorter.
### NVDA logs, crash dumps and other attachments:
[log.txt](https://github.com/nvaccess/nvda/files/10693371/log.txt)

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2022.4
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.2486
#### Name and version of other software in use when reproducing the issue:
Chrome: 版本 109.0.5414.120
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by rperez030** [comment]
The entire form is an aria live region. You can get around it by turning dynamic updates off (NVDA +5).

` <form data-h="ID=HpApp,21474.1" class="sb_form hassbi c_show_form c_show_form_expanded c_show_c" id="sb_form" action="/search" aria-live="polite" aria-expanded="false"> `

**Comment by michaelDCurran** [comment]
This  is deliberately caused by the web author and therefore not an NVDA issue.
this is not to say that the behaviour is perfect, but the issue should be reported to / debated with Bing instead.
