### ISSUE TITLE
include many new espeak variants in attachment

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#14619]
Please include all the new espeak ng klatt6 speech player variants included in the attached zip file in the new NVDA. There are new baby variants, child, male, female, alien and bug and robot variants, many based on klatt6 nv speech player. With all these new speech player based klatt6 variants, and the improvements in espeak ng the need for eloquence is going away.
[exclamation-v.zip](https://github.com/nvaccess/nvda/files/10700466/exclamation-v.zip)

**Comment by CyrilleB79** [comment]
@josephsl, I am not against closing. But for future trackability, could you provide a reason why you have closed this issu?
