### ISSUE TITLE
The word "as" is sometimes read as "American Samoa"

### ISSUE THREAD

**Issue by RD-Brown** [nvaccess/nvda#14625]
Pearson's accessibility team has identified an issue when using the Windows OneCore Voices synthesizer where the word "as" is sometimes read as "American Samoa." Because this issue is not present when using the eSpeak synthesizer, we believe this issue to be specific to Windows OneCore Voices.

This issue was also discussed on NVDA's discussion group:
[https://nvda.groups.io/g/nvda/topic/default_speech_dictionary_as/82655319?p=](url)

We have attached a file that demonstrates this issue. Note that if the Space after the span tag in the XML is deleted, the problem goes away, although this means that the paragraph number is then not separated from the paragraph text. (Less than ideal.)

### Steps to reproduce:
1. Start NVDA and ensure that you are using one of the Windows OneCore voices.
2. Open the attached file in a browser.
3. Note that when the page content is auto-read, "as" is read as "American Samoa."
4. When navigating by lines, the issue remains, but is no longer present when word navigation is used.

### Actual behavior:
"As" is read as "American Samoa."

### Expected behavior:
"as" should be read normally.

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
2022.4 (2022.4.0.27401)

#### Windows version:
Windows 10 Pro

#### Name and version of other software in use when reproducing the issue:
Google Chrome, Version 109.0.5414.120

#### Other information about your system:
64-bit, Intel i7-8665U CPU @ 1.90GHz, 32.00 GB RAM

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.
[American Samoa.zip](https://github.com/nvaccess/nvda/files/10708141/American.Samoa.zip)

**Comment by josephsl** [comment]
Hi, this is more towards a speech synthesizer issue, so I advise contacting Microsoft about this one. Thanks.

**Comment by RD-Brown** [comment]
Thank you. Can you suggest a site where synthesizer feedback can be posted to Microsoft?

**Comment by josephsl** [comment]
Hi, not that I know of – the closest is Feedback Hub. Thanks.

**Comment by Adriani90** [comment]
You can find the accessibility chat on this website, as well as a phone number. There is also a twitter account for microsoft accessibility.
https://www.microsoft.com/en-us/accessibility/disability-answer-desk?rtc=1&activetab=contact-pivot%3aprimaryr8

**Comment by Adriani90** [comment]
I will close this issue here since this is related to one core synthesizer dictionary and not to NVDA.

**Comment by XLTechie** [comment]
Have you tested with Narrator, and if so what is the outcome?

**Comment by RD-Brown** [comment]
Hello Luke. Testing with Narrator produces the same results.

**Comment by XLTechie** [comment]
> Testing with Narrator produces the same results.

Which confirms, if there was any doubt, that this is a Microsoft problem, not an 
NVDA one.

NVDA could probably solve it with speech dictionaries, but correcting all of the 
problems that "helpful" speech synths create, is a slippery slope. OneCore, in 
particular, has a plethora of these. ("cups" as "Cuban pesos", being a common 
example).

**Comment by RD-Brown** [comment]
Correct. We actually didn’t have any doubt that this was a Windows OneCore issue. Our goals were to inform NVDA of its existence, and hopefully open a dialogue regarding next steps. The issue has now been reported through Windows Feedback Hub, as well as to Microsoft’s Disability Support Helpdesk.

Thank you.
