### ISSUE TITLE
Link to nvdaHelper readme in developer guide 404s

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#14632]
### Steps to reproduce:

1. Open section 1.3 of the Developer Guide: https://www.nvaccess.org/files/nvda/documentation/developerGuide.html#toc5
2. The link in this section "NVDAHelp Readme" points to: https://www.nvaccess.org/files/nvda/documentation/nvdaHelper_readme.md

### Actual behavior:

This link 404's.

### Expected behavior:

Correct link or reword text.

#### NVDA version:

NVDA 2022.4

(Other system questions irrelevant)

**Comment by michaelDCurran** [comment]
@Qchristensen  How did you get to the developer guide in the first place? I.e. where is https://www.nvaccess.org/files/nvda/documentation/developerGuide.html  listed or linked from? The developer guide was originally written to be just accessed from the NVDA repository itself. In fact the nvdaHelper readme is never published anywhere a part from being included in the repository. I'd be tempted to convert the developerGuide.t2t to markdown (.md) and redirect that nvaccess.org url to the developerGuide in the github repository, and let Github render the html on demand. then the link to the NVDAHelper readme can stay relative to the repository. 
However, even if that was all done, the nvdaHelperReadme relative URL in the link is still wrong. It should be `../nvdaHelper/readme.md`

**Comment by michaelDCurran** [comment]
But would love to get opinion of people like @josephsl  and others before converting the developerGuide.
For now we could change the link in the developerGuide to point to:
`https://github.com/nvaccess/nvda/blob/master/nvdaHelper/readme.md`

**Comment by Qchristensen** [comment]
I was looking for something unrelated to this which I thought was in the developer guide - and to be honest, I couldn't remember where the guide was myself - so I did a google search.  "nvda developer guide" brings up https://www.nvaccess.org/files/nvda/documentation/developerGuide.html as the first result.

**Comment by seanbudd** [comment]
Note that the developer guide (hosted online) is linked from the changes document to the [API section](https://www.nvaccess.org/files/nvda/documentation/developerGuide.html#API)
