### ISSUE TITLE
NVDA accessibility tool- speech viewer does not capture any event of user actions when screen is locked

### ISSUE THREAD

**Issue by sain5557** [nvaccess/nvda#14636]
### Is your feature request related to a problem? Please describe.
I have observed that when my windows m/c screen gets lock the NVDA speech viewer stops capturing the events of the user actions. Hence in order to capture the events by NVDA the user has to login to the system and watch the UI Actions.

### Describe the solution you'd like
NVDA should capture the events of user actions when screen is locked.

**Comment by seanbudd** [comment]
What do you mean by "capture the events of the user"?

Speech viewer is a tool which captures the speech sent to the synthesizer.

It is expected to not capture this speech when windows is locked, as this may cause secure information to be leaked.
