### ISSUE TITLE
Mouse selection is not read in Internet Browsers

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1464]
**Reported by ragb on 2011-04-18 19:18**
Hi,

This was reported on the NVDA portuguese list.

It would be great that, browsing in both internet explorer and firefox, the text that is selected with the mouse could be read like it was before with the nvda+shift+up key command. Users report that this command worked in NVDA 2010.2 for mouse selections. Alternatively, the selected text could be read when passing the mouse pointer over the selection or, when releasing the mouse button while finishing the selection. This is very important for low vision users that can still use the mouse for some tasks like selecting text, but need spoken feedback of what they are doing.

Regards,

Rui Batista

**Comment by Qchristensen** [comment]
Just a quick follow up to this one to confirm that this behaviour is still the case in Windows 10 and in Firefox 53, Chrome 58, Internet Explorer 11 and Microsoft Edge.

**Comment by feerrenrut** [comment]
Since this is a regression (perhaps an old one, but still) setting priority 2.

**Comment by Qchristensen** [comment]
A little bit more info:
- Using NVDA 2017.1 or 2017.2rc1

- If NVDA is in Browse mode, selecting text with the mouse, then trying to read selection results in NVDA reporting "No selection".  In this mode, pressing control+c does not copy the text to the clipboard, but pressing the applications key or the right mouse button and choosing "copy" does copy the text.
- If NVDA is in Focus mode, selecting text with the mouse, then trying to read selection results in NVDA reporting "Selected: " but not reporting what is selected.  Pressing control+c at this point DOES copy the text to the clipboard and NVDA+c correctly reads the clipboard contents. (Internet explorer still announces "no selection" but text can be copied and read).
- In Microsoft Edge, selecting text with the mouse and then trying to read the selection does work IF NVDA is in focus mode.  In Browse mode, the selection cannot be read or copied, as with the other browsers.

**Comment by jcsteh** [comment]
I don't see how this could have worked in NVDA 2010.2. In browse mode, NVDA uses its own cursor/selection and can't retrieve nor manipulate the actual browser selection. It should work for an editable text field in focus mode, however, which might explain the confusion. It's not going to be possible to work with the browser selection without major changes to the way browse mode works (probably getting rid of virtual buffers).

**Comment by KrolPolski** [comment]
This is an issue for me. I am a low vision user of NVDA and use the mouse for a lot of tasks but struggle to read long sections of text; being able to copy text that was selected from the clipboard is core windows functionality that should still work with NVDA running. I am sure this issue impacts many low vision users.

**Comment by jcsteh** [comment]
> being able to copy text that was selected from the clipboard is core windows functionality that should still work with NVDA running.

As noted above, you can still select text with the mouse and copy it, though control+c won't work with browse mode enabled; you'll either have to right click and then click Copy, or switch to focus mode with NVDA+space and then press control+c.

**Comment by Adriani90** [comment]
This will be more intuitive when #8846 will be implemented.

**Comment by Adriani90** [comment]
Closing in favor of #3773 since the comments in that issue explain in more detail where the problems are.
