### ISSUE TITLE
Strange behavior in dictionaries if replacement contains space

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#14663]
### Steps to reproduce:

1. First, set symbol level of "\\" to have it reported (i.e., None);
2. open a dictionary and create something like "foo" replaced by "foo bar" (note the space in replacement);
3. read text: "test of foo".

### Actual behavior:

Voice says:
"test of foo\\bar"

### Expected behavior:

Voice should say:
"test of foo bar"
without any "\\".

#### NVDA installed/portable/running from source:

Installed and running from source.

#### NVDA version:

NVDA alpha-27727,86e93666 (installed).

#### Windows version:

Windows 10 22H2 Build 19045.2604 64-bit.

#### Other information about your system:

Tested with Eloquence and Microsoft OneCore (Elsa) synthesizers.

#### Does the issue still occur after restarting your computer?

Not tested.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

2023.1beta1 seems to not have this issue.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Not tested.

**Comment by CyrilleB79** [comment]
Thanks for reporting Alberto.

This bug has been introduced by my own PR (#14557). I will provide a fix soon.
