### ISSUE TITLE
Symbol speaking verbosity while cursoring  and say all

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1466]
**Reported by briang1 on 2011-04-20 09:32**
Having read all the tickets regarding the new symbol processing, some parts are not clear to me. Namely, exacty when and where punctuation and other symbols are to be spoken. I can understand the levels relating to say all, and this seems to work quite well, but I'd question the choices in the current  set up for.
 Sayall of web and email addresses
Cursoring up and down in documents
In email addresses and web sites, the full punctuation shoul, in my view, always be spoken thus  making it less likely you will need to stop and cursor along a line to hear all the  items.
 In the old set up, dots between  elements were spoken in cursor up and down, but now only increasing the verbosity of the punctuation to most lets this occur but with even more spoken than before. Try these.
Channel 4+1 (13)
Rubbish@noisp.co.uk
www.not_a_real_address.org
My-name@semi-bored.co.uk
http://silly-address.org.uk

The first one above is a channel from a tv listing page, where the channel is called plus 1 as its a time shifted channel, and the number in the  brackets is the channel number. The rest are obvious. 

Is there anything that could be done to achieve  the correct  spoken results here?
I'd have thought that  cursor up and down and left and right might also need the same level of punctuation.

**Comment by ehollig** [comment]
@Brian1Gaff, are you looking for something like #1708?

**Comment by bdorer** [comment]
As of its complexity I wote for closing as cantfix.

**Comment by Adriani90** [comment]
closing as requested.
