### ISSUE TITLE
NVDA plays error sound when switching windows in alpha when braille is set to automatic

### ISSUE THREAD

**Issue by enessaribas** [nvaccess/nvda#14673]
### Steps to reproduce:
insure NVDA settings/braille is automatic, the default.
In current alpha, move through windows, by going to desktop, launching browser or alt tabbing
### Actual behavior:
NVDA error sound is played multiple times and following is in log many times
ERROR - extensionPoints.Chain.iter (03:08:27.785) - ThreadPoolExecutor-0_0 (3872):
Error yielding value from handler <function _Detector._bgScanBluetooth at 0x0412C4B0> for <extensionPoints.Chain object at 0x041265B0>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 274, in iter
  File "bdDetect.pyc", line 369, in _bgScanBluetooth
TypeError: 'property' object is not iterable

### Expected behavior:
 no error tones or errors in log

#### NVDA installed/portable/running from source:
 installed
#### NVDA version:
alpha-27727,86e93666
#### Windows version:
Version 22H2 (OS Build 22621.1265)
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by lukaszgo1** [comment]
This is almost certainly fixed already by #14531, unfortunately no Alpha build after this PR got merged was build successfully since system tests are so fragile.

**Comment by XLTechie** [comment]
It was definitely fixed.

If you download the build from that PR, you will find that this error no longer 
occurrs.

**Comment by Brian1Gaff** [comment]
I hear two error sounds when I start alpha, even though I let it disable the 
add ons it wanted to, so who knows. This is, after all, alpha software.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment]
Is it not on the alphas in the  snapshots download page though? I seem to 
recall somebody said the  page was not updating, and wondered why exactly. A 
bit misleading if the update checker for that branch no longer works, don't 
you think?
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by seanbudd** [comment]
Closing as fixed by #14531
