### ISSUE TITLE
Installer doesn't preserve configuration when upgrading a portable copy, inconsistent with updating an installed copy

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#14678]
### Steps to reproduce:

* Create a portable version of an NVDA beta/alpha.
* Download an updated beta/alpha, without using the "check for updates" option. Example: update your local collections of alphas and betas by downloading their files while running your installed copy of NVDA, and running their installers.
* Run the installer for the updated version. It may or not matter, but for purposes of reproduction, note that I did this from an installed copy of NVDA, not from the copy being updated.
* Select to create a portable copy.
* Enter the directory of an existing portable copy which already has a customized configuration.

### Actual behavior:

The installer ignores that the portable copy has a configuration, and gives it a clean configuration.

### Expected behavior:

When performing these steps for an installed copy, the installer preserves the existing configuration and "updates" NVDA.
I would expect the installer to also preserve the configuration of portable copies, and "update" those.

I am [not alone](https://github.com/nvaccess/nvda/issues/9596#issuecomment-594459701) in this expectation.

#### NVDA installed/portable/running from source:

While installing.

#### NVDA version:

All versions. Most recently: 2023.1Beta2

#### Windows version:

All versions.

#### Name and version of other software in use when reproducing the issue:

N/A

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Lots. Same.

#### If NVDA add-ons are disabled, is your problem still occurring?

N/A

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

N/A

**Comment by Brian1Gaff** [comment]
That sounds like it is not polling the existence of an installation in the 
folder of choice, after you select it. In the auto update of course, you are 
not going back to scratch, so to speak, as it knows the relative  addresses 
of its folders. If you run a different copy,  and then download and create 
the temp over the top of the old one, does this also do it, or is it only if 
you are running originally from the copy its going to overwrite?
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "Luke Davis" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Monday, February 27, 2023 5:21 AM
Subject: [nvaccess/nvda] Installer doesn't preserve configuration when 
upgrading a portable copy, inconsistent with updating an installed copy 
(Issue #14678)

**Comment by XLTechie** [comment]
@Brian1Gaff I have edited the original to make clear(er) that I was running the installer from an installed copy, not the copy being updated.
However, it shouldn't matter AFAIK, because the installer starts its own copy which should be independent from anything on the local machine, except that the temporary copy in the installer picks up the configuration of the installed copy, though it isn't preserved in any portables created.

**Comment by XLTechie** [comment]
Until a choice is given for the same things regarding installed copies, I think 
the installer should do the same for portables as it does for installed copies. 
That is: it should update them in-place, retaining any configuration.

**Comment by jcsteh** [comment]
It's worth noting that the installer doesn't do anything at all regarding configuration for installed copies. The configuration is separate from the application, so it isn't touched.

Are you saying that the userConfig folder in the portable copy gets completely obliterated? I'm looking at the code and I really can't fathom how that is possible. It explicitly excludes the userConfig path when creating a portable copy precisely so that it doesn't touch the config (unless the user checks the "Copy current user configuration" check box).

**Comment by XLTechie** [comment]
What occurred, is that I set the synth, and a bunch of reading and formatting 
settings in a portable copy I was trying to keep current with beta. Might have 
even installed a few add-ons.

Then, a few days later, a new beta was released. I updated that portable beta, 
"from outside", by downloading the new beta installer and pointing it to the 
same directory.

The next time I started the beta, the synth and other settings had reverted to 
factory defaults.

I did not actually analyze exactly what was happening, only that it did happen.
I will do some further studies and try to pin down the "how" of it.

**Comment by jcsteh** [comment]
FWIW, [here's the code that is supposed to prevent userConfig from being overwritten in a portable copy](https://github.com/nvaccess/nvda/blob/d30349c3afdfb4988124d4a8a628e2ddd9b0e63b/source/installer.py#L218). I guess it isn't working for some reason. I haven't dug into why at this stage.

**Comment by XLTechie** [comment]
Either I screwed up somewhere, or something on my system went wonky. Either way, using fresh copies of everything, I can no longer replicate this. Closing for now.
