### ISSUE TITLE
Occasional Outlook crashes with NVDA

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#14692]
### Steps to reproduce:
1. Launch NVDA
2. Open Outlook 365
3. Open an unread message
### Actual behavior:

When opening a minority of emails, Outlook closes and reopens and the email is shown as unread.  Emails deleted immediately beforehand reappear.
### Expected behavior:

The email is presented reliably.
### NVDA logs, crash dumps and other attachments:
NVDA log file retrieved immediately following the problem attached.
#### NVDA installed/portable/running from source:
NVDA installed
#### NVDA version:
Version 2022.4 and at least four previous versions
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Outlook in Office 365, 32 bit
#### Other information about your system:
Computer is about eight years old.  No antivirus software apart from Windows Defender.  The problem does not occur on several other computers and I wonder if the issue is peculiar to the 32 bit version of Outlook.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Problem has been present for at least a year.  Also occurred with beta 2 of 2023.1 portable.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes
[nvda-outlook.log](https://github.com/nvaccess/nvda/files/10877345/nvda-outlook.log)

**Comment by Adriani90** [comment]
Did you update Outlook to the last build and last version?

**Comment by andrew-l-d** [comment]
Yes, Outlook is current.  I also had Microsoft check it and repair some apparently corrupted files.  The other thing I forgot to mention is that I cannot replicate the issue with Narrator.  But, as mentioned, it only happens on this machine.

 

 

Andrew

**Comment by seanbudd** [comment]
Closing as duplicate #13621

**Comment by andrew-l-d** [comment]
Apologies.  I did a quite extensive search before posting and missed #13621 <https://github.com/nvaccess/nvda/issues/13621> .  Just adding that Office on this machine is 32 bit whereas it is 64 bit on my other machine where I cannot recall the problem occurring.

 

 

Andrew
