### ISSUE TITLE
strange behavior of nvda in the latest stable version of microsoft edge

### ISSUE THREAD

**Issue by Nikita34196** [nvaccess/nvda#14728]
hi. recently I noticed strange nvda behavior on many sites in microsoft edge including google.comthe pages open by themselves as if I press enter, but I don't do it for example. there is a search for something in google and nvda pronounces the name of the link. then it is opened, although there is no pressing of any kind. this problem is found on many other sites for example vk.com yandex.ru and others. I have not noticed this problem in other browsers. NVDA version alpha-27830,d2d4bfce also tested on nvda 2023.1 microsoft edge 111.0.1661.41

**Comment by Adriani90** [comment]
Did you enable automatically set system  focus on focusable elements in browse mode settings or with NVDA+8? If yes, this issue might be solved when you disable this.

**Comment by Nikita34196** [comment]
Hello. Yes. I have it enabled. If the problem is solved, I will close the issue.

**Comment by Adriani90** [comment]
@Nikita34196 the solution is to disable it. I am closing this one since it is the same issue as described in #14729.

**Comment by brunoprietog** [comment]
It also happens to me a few weeks ago. Disabling that option with NVDA+8 does not help me at all, as for me it is very useful that feature when using Object Location Tones. Also, even if you turn it off, in Google Calendar, navigating to events opens the create button without me pressing it. This also happens in Google search, in Gmail swiping to Gmail emails opens automatically, in Google oauth 2 screen links are pressed automatically, in Google Meet swiping to upcoming meetings buttons also presses automatically, in Jira dialogs also open without pressing the buttons, in many places. In my opinion this should not be closed, it is being too obnoxious and every time I enter these sites I have to disable the option, and when I leave there re-enable it. Sometimes I have discovered sites where it happens and they are pressed without my consent.

Translated with www.DeepL.com/Translator (free version)

**Comment by brunoprietog** [comment]
It also happens to me a few weeks ago. Disabling that option with NVDA+8 does not help me at all, as for me it is very useful that feature when using Object Location Tones. Also, even if you turn it off, in Google Calendar, navigating to events opens the create button without pressing it. This also happens in Google search, in Gmail browsing emails opens automatically, in Google oauth 2 screen links are pressed automatically, in Google Meet browsing to upcoming meetings buttons also presses automatically, in Jira dialogs also open without pressing the buttons, in many sites. In my opinion this should not be closed, it is being too obnoxious and every time I enter these sites I have to disable the option, and when I leave there re-enable it. Sometimes I have discovered sites where it happens and they are pressed without my consent.
