### ISSUE TITLE
NVDA does not report process manager list item names in Visual Studio Code

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#14721]
### Steps to reproduce:
1. Open Visual Studio Code
2. Press Alt + H, P
3. Navigate to the list and press the up or down arrow

### Actual behavior:
NVDA only reports "list item"
### Expected behavior:
NVDA should report the names of list items as Narrator does.
### NVDA logs, crash dumps and other attachments:
[log.txt](https://github.com/nvaccess/nvda/files/10985888/log.txt)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-27830
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.2604
#### Name and version of other software in use when reproducing the issue:
Visual Studio Code 1.76.2 
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment]
We could also reproduce this issue with Narrator.
This issue needs to be reported to Microsoft.

**Comment by cary-rowen** [comment]
Sorry, I confirm that the issue can be reproduced with Narrator.
I will report the issue to Vs Code
