### ISSUE TITLE
compatibility with tunderbird 112

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#14738]
### Steps to reproduce:
upgrade to thunderbird 112
now open thunderbird and walk to message list.
navigate with the arrows:

### Actual behavior:
when navigating between messages nvda announces only the subject of the messages.
### Expected behavior:
nvda should advertise all headers that are configured to show in tunderbird.
Especially would like to hear:
sender's name.
message subject.
receipt date
whether the message has attachments.
previously nvda read even a piece of the message, if this behavior would be interesting.
This is what I noticed, but I think a good review on nvda's performance in tunderbird would be interesting.
There is an add-on for tunderbird that does not yet support this version.
Anyway I hope that nvda supports at least the minimum accessibility in the application.

#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-27830,d2d4bfce

#### Windows version:
windows 11 22621.1483
#### Name and version of other software in use when reproducing the issue:
thunderbird.exe, Thunderbird 112.0

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by XLTechie** [comment]
This is beta software. You should be complaining to Thunderbird about 
accessibility of their betas.

They should be reaching out here or to NV Access, if they want their next 
release to be accessible and are making some large scale change as you describe, 
but you should definitely report this change to them.

**Comment by XLTechie** [comment]
And also possibly talk about it on the thunderbird mailing list for blind users:

https://groups.io/g/thunderbird

**Comment by mdyer1** [comment]
I believe there is a bug report in the thunderbird Bugzilla  bug tracker, but not sure not sure of the link off the top of my head.

Matthew

**Comment by leonardder** [comment]
As this is beta software, closing this as needs external fix.
