### ISSUE TITLE
installer should check state of Windows Audio service.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1474]
**Reported by challsworth2 on 2011-04-27 12:04**
The NVDA installer should check the state of the Windows Audio service. If disabled, start it and set the startup type to automatic if set to manual. This is particularly important for users of server operating systems, like 2008 R2, and they wish to use NVDA. If a commercial screen reader does this, why not NVDA.

**Comment by leonardder** [comment]
Closing as won't fix as per https://github.com/nvaccess/nvda/issues/1474#issuecomment-155289654. Server admins should be aware of this fact.
