### ISSUE TITLE
Error sounds heard when navigating up in the synth settings ring

### ISSUE THREAD

**Issue by Mohamed00** [nvaccess/nvda#14741]
### Steps to reproduce:
1. Switch to OneCore.
2. Navigate to the voice option with the synth settings ring, then move upwards until you reach the last voice.
### Actual behavior:

An error sound is heard when navigating up past the last voice. This doesn't seem to happen when navigating down.
### Expected behavior:

No error, last voice should be repeated like it was previously.
### NVDA logs, crash dumps and other attachments:
Log fragment: error executing script: <bound method GlobalCommands.script_increaseSynthSetting of <globalCommands.GlobalCommands object at 0x0813C710>> with gesture 'ctrl+shift+NVDA+up arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "globalCommands.pyc", line 292, in script_increaseSynthSetting
  File "synthSettingsRing.pyc", line 122, in increase
  File "synthSettingsRing.pyc", line 19, in increase
  File "synthSettingsRing.pyc", line 55, in _set_value
IndexError: list index out of range
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-27892,42dbabcc
#### Windows version:
Windows 11, build 25324.1000.
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. This seems to have started occurring when #14704 was merged.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by CyrilleB79** [comment]
Cc @leonardder

**Comment by Brian1Gaff** [comment]
I think this  is tolerated and like many others, seems to be ignored.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "Mohamed Al-Hajamy" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Friday, March 24, 2023 1:15 PM
Subject: [nvaccess/nvda] Error sounds heard when navigating up in the synth 
settings ring. (Issue #14741)

**Comment by leonardder** [comment]
Ugh, I've been thinking about a workaround for some hours, so @Brian1Gaff's suggestion is definitely incorrect.
