### ISSUE TITLE
error when switching to another synthesizer when the change was previously made in a profile

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#14760]
### Steps to reproduce:
First of all, apologies if I'm too imprecise, as I don't know what causes the problem, I'll try to show my whole scenario.
First create a profile for word.
In this profile I have configured nvda to read column and cell information in tables.
Now in the normal settings profile besides several settings I have configured nvda to use the rh voice synthesizer.
It is worth saying that I think that to reproduce this problem it is possible to use a profile of settings for any program, the most important thing is that in the normal profile the voice is defined for the rhvoice synthesizer and in the profile for word there is not even a defined voice, so he is using the rh voice too, derived from the normal profile.
Perhaps this is reproduced with another synthesizer besides the rh voice.
in summary:
normal perfio using rhvoice voice and not reading table info.
perfio word using rh voice inherited from normal perfio and reading table positioning information.
Now open word
press nvda + ctrl + s choose with the arrow keys the one core synthesizer and press enter.
so far everything ok.
I don't know if it matters how these screens are opened, so I'm describing how I opened and used them.
now press windows+d to go to desktop.
Now nvda should be using the rh voice synthesizer defined in the normal profile again.
reopen the synthesizer screen with nvda + ctrl + s.
from there with the arrow keys to the one core synthesizer and press enter.
  
### Actual behavior:
nvda reports that there is an error in the one core synthesizer and does not change the normal profile synthesizer.

### Expected behavior:
nvda should switch to the one core synthesizer for the normal profile as it is already in use in the word profile.

I remembered, the profile for word is configured to be activated automatically when entering word.

#### NVDA installed/portable/running from source:
instaled e portable
#### NVDA version:
nvda.exe, NVDA alpha-27948,bc3e97dd

#### Windows version:
10 19045.2728
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
log:
[voz.txt](https://github.com/nvaccess/nvda/files/11105344/voz.txt)

**Comment by CyrilleB79** [comment]
@fernando-jose-silva could you reproduce the issue with add-ons disabled and provide a log? Thanks.

**Comment by fernando-jose-silva** [comment]
follows log with disabled addons.
it is possible to reproduce the error by switching between speak and one core voices.
normal configuration using speak.
word configuration using one core.
When going to the desktop, nvda switches to the normal profile using the speak voice, so far so good.
When trying to change the voice from the normal profile to the one core voices the error is displayed, it is not possible to switch to the synthesizer.
expecte
[voz1.txt](https://github.com/nvaccess/nvda/files/11112692/voz1.txt)
d, able to switch to the one core synthesizer.
log hoe

**Comment by CyrilleB79** [comment]
Thanks @ruifontes.
In the meantime, I have just faced the same issue. Very strange since I have run 2023rc1/2 for some weeks and have just got this issue now.

**Comment by fernando-jose-silva** [comment]
thank you very much for your attention.

**Comment by leonardder** [comment]
The relevant error:

```  File "synthDrivers\oneCore.pyc", line 351, in _set_volume
TypeError: unsupported operand type(s) for /: 'str' and 'float'
```

It looks like the profile is corrupt, i.e. the volume is parsed as string, not as float. Is this an entirely new profile?

**Comment by fernando-jose-silva** [comment]
I deleted the nvda.ini files, and reconfigured nvda.
I deleted the word profile and created a new one.
after all this the error can be reproduced.
Attached is a new log with these changes, add-ons enabled since disabling them did not change according to messages like this.
[voz3.txt](https://github.com/nvaccess/nvda/files/11116561/voz3.txt)

**Comment by leonardder** [comment]
In that case @fernando-jose-silva, it would really help to know when this issue started occurring. Does it occur in 2023.1 and 2022.4?

**Comment by CyrilleB79** [comment]
> In that case @fernando-jose-silva, it would really help to know when this issue started occurring. Does it occur in 2023.1 and 2022.4?

I have performed tests. The issue does not occur on 2022.4. It occurs on 2023.1beta1.

**Comment by CyrilleB79** [comment]
I have tracked the regression to be introduced in commit 816496f178e3964323d0a8f8f19825274554e096 (PR #14133). Previous commit 084db952c03fdcc5c098c8ba034f59712cb78586 is running well.

@seanbudd could you have a look to this regression since you are the author of #14133? Thanks.

Note that I have used a slightly different way to reproduce the issue but it seems to me that it is the same root issue.

STR:
* Default profile with synth IBMTTS
* Notepad profile with one change, e.g. indent reporting and no other TTS change, thus inheriting IBMTTS
* Go to Notepad
* Restart with add-ons disabled

Result:
OneCore is sometimes heard when NVDA is loading (since IBMTTS cannot be loaded due to restart without add-ons). Then as soon as NVDA reports Notepad window, eSpeak is speaking, due to the same error with OneCore. Note also that if I alt+tab to another application where default profile applies, the TTS remains set to eSpeak.

**Comment by CyrilleB79** [comment]
Also got just now another error related to value coming from the config 

```
ERROR - unhandled exception (21:58:23.911) - MainThread (9448):
Traceback (most recent call last):
  File "gui\settingsDialogs.pyc", line 4149, in onCategoryChange
  File "gui\settingsDialogs.pyc", line 667, in onCategoryChange
  File "gui\settingsDialogs.pyc", line 649, in _doCategoryChange
  File "gui\settingsDialogs.pyc", line 577, in _getCategoryPanel
  File "gui\settingsDialogs.pyc", line 335, in __init__
  File "gui\settingsDialogs.pyc", line 345, in _buildGui
  File "gui\settingsDialogs.pyc", line 3221, in makeSettings
  File "gui\settingsDialogs.pyc", line 2726, in __init__
TypeError: Choice.SetSelection(): argument 1 has unexpected type 'str'
```

The code line is the following:
`self.UIAInMSWordCombo.SetSelection(config.conf["UIA"]["allowInMSWord"])`

NVDA 2023.1; Windows 10 2004 (x64) build 19041.388.
