### ISSUE TITLE
Copy link to clipboard when NVDA+K is pressed 3 times quickly

### ISSUE THREAD

**Issue by marcel-88** [nvaccess/nvda#14804]
Hi, it would be helpful if the functionality to copy the link when NVDA+K is pressed 3 times quickly was added, as it helps better productivity.
Now to copy a link I would have to press NVDA+K and then copy what the voice said with the speech history addon or press NVDA+K twice and then use CTRL+A and CTRL+C.
But wouldn't it be faster to be able to copy the link in basically one click (ie 3, but you get the idea).
Thank you❤

**Comment by XLTechie** [comment]
Already intending to do that one.

Note that most of the time, the context menu copy link command, should work for 
this.

**Comment by Adriani90** [comment]
Given the context menu item works usually, and now you can copy the link also from the NVDA's browseable window as introduced in #17018,  I think this is comfortable enough to get the link quite fast.
I am closing as won't fix.
