### ISSUE TITLE
Browse cursor cannot maintain its position while reading feed content

### ISSUE THREAD

**Issue by ObjectInSpace** [nvaccess/nvda#14808]
### Steps to reproduce:
Use arrow keys to browse content in browse mode on a site with a scrollable list view that contains refreshable content. Example sites: browsing an email thread in gmail/proton, or reading a Mastodon timeline in Pinafore.social or semaphor.social. (the native mastodon interface works as expected, as does twitter.)
### Expected behavior:
The cursor's position within the page should remain predictable.

### Actual behavior:a
The cursor position refreshes to the top of the view as soon as it is entered, making it impossible to read most of the content. For example:
-in a gmail thread, arrow down in browse mode from an email header until NVDA says "show details." Immediately after this the cursor moves back to the start of the header and NVDA will start reading it. (E.G. "show details clickable from: xxx@y.z" and so on.
-in Semaphore the focus gets lost in a similar way, however it will do something weirder and cause the currently focused post to be opened! This obviously makes it very hard to track your place or do much of anything.

### NVDA logs, crash dumps and other attachments:

The NVDA log viewer threw an error when I triggered the behavior in gmail, which I have pasted below:

ERROR - eventHandler.executeEvent (11:15:11.478) - MainThread (19492):
error executing event: gainFocus on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x00D89FD0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 110, in next
  File "browseMode.pyc", line 1662, in event_gainFocus
  File "speech\speech.pyc", line 628, in speakObject
  File "speech\speech.pyc", line 668, in getObjectSpeech
  File "speech\speech.pyc", line 520, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1174, in _get_rowNumber
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))

#### NVDA installed/portable/running from source:
installed from website
#### NVDA version:
2023.1
#### Windows version:
windows 11 home 22H2
#### Name and version of other software in use when reproducing the issue:
Chrome: 112 (first noticed in Chrome 111)
#### Other information about your system:
system is new, and this copy of NVDA has no addons.
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by ObjectInSpace** [comment]
this occurs if "automatically set system focus to focusable elements" is on.

**Comment by amirsol81** [comment]
@ObjectInSpace The "Automatically set system focus to focusable elements" feature, when set to On which is the default, has other strange issues, too. For instance, using Chrome/Edge and with Google search results, it automatically activates the "About this result" button for each result as we press the Down arrow to reach it. The moment the Down arrow reaches the "About this result" button, it's activated automatically, and this makes turning on the "Automatically set system focus to focusable elements" a headache. It also activates the Listen button automatically as we use the search operator "define:xxx" on Google.com to look up words. As the Listen button gains focus with the Down arrow, the audio pronunciation gets played. In short - and as things stand right now, the "Automatically set system focus to focusable elements" feature is so problematic that I've disabled it altogether.

**Comment by seanbudd** [comment]
We are planning on deprecating this option.
This is the option working as intended.
I would discourage using it to avoid this behaviour.

**Comment by ObjectInSpace** [comment]
https://www.youtube.com/watch?v=Q_8v2V2XojA

If the plan is to deprecate the option, it should not be the default. It's a pretty bad user experience to have an unknown number of your websites break with no obvious explanation.

**Comment by seanbudd** [comment]
@michaelDCurran  - can we default the option to off in the meantime?

**Comment by michaelDCurran** [comment]
It has been defaulted to off since 2020.3.
