### ISSUE TITLE
Consider ruff for linting and replace Flake8 with it

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#14817]
### Is your feature request related to a problem? Please describe.
Flake8 is a very popular linter, but it is extrelmely slow and it checks every time all files, even if they have not been changed.
It also lacks of relevant rules and the development activity is slowing down.

### Describe the solution you'd like
Ruff is a very promising alternative, combining Pylint, Flake8 and other linters in one very fast environment. It can be configured so it checks only files that have been changed when sending a pull request.
https://github.com/charliermarsh/ruff
Its development team is very active and already many projects are using it especially because it provides a good mix of many linters out there and still it is very fast.
It has also a flake8 Gettext plugin included, so translatable strings could also be linted.

### Describe alternatives you've considered
Leave as it is.

### Additional context
n/a

**Comment by seanbudd** [comment]
Does this support tabs? We need to use `flake8-tabs`

**Comment by seanbudd** [comment]
see also discussion in #12261

**Comment by seanbudd** [comment]
It seems the authors of ruff are aware of flake-8tabs: https://github.com/charliermarsh/ruff/issues/2319#issuecomment-1407548839

It might be worth asking them to prioritise it

**Comment by leonardder** [comment]
I think this subject might be better suited for a discussion first, see https://github.com/nvaccess/nvda/discussions/15299, where I basically dropped my opinion on how to go forward with the NVDA code base. It's not just linting, we really need auto formatting. And we need to reconsider using tabs for indentation in a modern era.

**Comment by leonardder** [comment]
As an update that is probably pretty relevant to us, the experimental formatter in Ruff now supports tab indentation. That might mean we can start considering auto formatting for NVDA. The formatter in Ruff is mostly based on Black. Black usually follows the code style NVDA uses, except for the extra level of indentation PEP8 and NVDA use for function parameters.

**Comment by CyrilleB79** [comment]
Although a replacement or upgrade discussion still needs to progress, I would like to note that this ticket is not a full feature request.

There is also currently an issue with code complexity checking:
Indeed, since Python 3.11 and #15636, as written by @lukaszgo1 in #15636:
> While this version of Flake8 is way more recent than what we we're using up to now, it predates Python 3.11. It means that some constructs (case statements) would not be recognized. Possible 

The consequence is that code complexity computation is not reliable anymore when using match / case statements.

**Comment by Adriani90** [comment]
Ruff now supports tab conversion properly, so the concern stated in https://github.com/nvaccess/nvda/issues/14817#issuecomment-1502566648 is resolved.

cc: @gerald-hartig, @michaelDCurran fyi

**Comment by LeonarddeR** [comment]
Have I missed something? While Ruff supports tab indentation for the formatter, it formats function and method parameters with one level indentation (the black way) instead of two (the Pep8 way). We are currently using the Pep8 approach for our codebase.

**Comment by Adriani90** [comment]
Ah thanks @LeonarddeR for this, yeah that issue seems still open.
Discussion can be followed at
https://github.com/astral-sh/ruff/issues/8360
