### ISSUE TITLE
Lint Gettext wrapper functions for translatable strings

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#14818]
### Is your feature request related to a problem? Please describe.
When changing or adding large amount of code there is always the risk to forget adding wraper functions to the messages that should be translatable. This results in adhoc adjustments to make strings translatable often after a release of NVDA, which in turn triggers an additional release.
Users complain about strings not being translatable, and at the same time the number of releases can be overwelming.

### Describe the solution you'd like
To make this process as secure as possible, add a linter that checks for messages that should have a _("") wraper function and warn about them before checks for a pull request pass.
As an example, here is a good Gettext linter for Pylint. 
https://www.technomancy.org/python/pylint-i18n-lint-checker/
Pylint runs with Flake8 and with ruff as well, so it should be spossible to integrate it either in the current development or in ruff linting, in case NV Access decides to change the linting to Ruff.

### Describe alternatives you've considered
Use Flake8 Gettext linter, but this is not configurable so it would be hard to customize it. The code for the plugin above is publicly available, so it could be taylored to the needs of this project.

### Additional context
n/a

**Comment by seanbudd** [comment]
@Adriani90 - how is this possible?
There are strings in NVDA which should not be translatable and there is no programmatic way to know this.
The example you provided requires a manual whitelist of non-translatable strings.
This seems not worthwhile for NVDA.

**Comment by Adriani90** [comment]
@seanbudd three conditions I can imagine are:
1. Search for # translators:
 * after or before the translators comments, the next or the previous line should contain either a string with a _ wrapper function, or a string with a pgettext wrapper function like in braille.py. If not, raise a warning
2. Search for speech.speakMessage and ui.message
 * These should always contain a string with an _ wrapper function, if not, raise a warning.
3. Ignore wx.ok, wx.cancel and wx.apply

At least it would make sense to rund a flake 8 or a Pylint gettext linter to see how feasible it would be to implement.

Would you mind reopening this to maybe gather more arguments?

Even with a white list, if at all needed, the implementation of such a linter would make sense and it might be possible that some one in the community feels motivated to provide such a list. However, I am not totally convinced that a white list is needed.

cc: @nvdaes

**Comment by seanbudd** [comment]
I believe it would be difficult to implement a linter that you have described here and outside of the scope of the project.
There's also very little gain for doing this.

**Comment by Adriani90** [comment]
However, NVDA promotes externally as beeing a software which brings accessibility to people without costs, on an international scale. This is what you at NV Access state on your website and also in podcasts. 
https://www.nvaccess.org/about-nvda/

I mean if guaranteeing translatable strings is not in scope of this project, then you should comunicate the expectations also in the community.

In that case we should not make translatable strings a standard at all. or am I missing a point here?

There is a linter already out there, even in flake8. It just needs to be taylored, if at all.

**Comment by seanbudd** [comment]
>I mean if guaranteeing translatable strings is not in scope of this project, then you should comunicate the expectations also in the community.

@Adriani90 - We manually check for translatable strings. It is very rare strings slip through, and when they do they are picked up and fixed. We have a beta testing cycle for this purpose. Forking and maintaining a custom linter is not in the scope of this project.

**Comment by Adriani90** [comment]
That sounds reasonable.

**Comment by lukaszgo1** [comment]
> I think a more pythonic approach would be to perform type checking on our code, and make translatable strings a specific type. That way if a function receives a non translatable string when it expects one, a type error would be thrown when performing the type check.

Unless I'm missing something this has the same downsides as the solution proposed in the initial comment, i.e. some spoken strings should not be translatable. To  use a naive example someone may assume that the message provided to to `ui.message` should be always translated and add type annotations to that effect. This however is not always the case (for a real example see `script_reportCurrentComment`, where the content of the comment is spoken as retrieved from the application).

**Comment by seanbudd** [comment]
Still speaking hypothetical here, but it would be reasonable to cast externally fetch strings (e.g. content on a website) to a separate data type e.g. `ExternalString` . That way `ui.message` could accept `Union[ExternalString, TranslatableString]` but not `str`.
