### ISSUE TITLE
Follow up 14836:When using windows 11 with NVDA28111 to enter text in Notepad, the title will be reported once after the space on the screen

### ISSUE THREAD

**Issue by dpy013** [nvaccess/nvda#14838]
### Steps to reproduce:
First press windows+R to open the run and type notepad
Next, use NVDA-alpha-28111 to enter the text in Notepad
At this point NVDA-alpha-28111 will report the window title of Notepad
### Actual behavior:
无标题 - 记事本
文本编辑器  编辑框  多行  空白
空白
空白
w
x
Windows 输入体验  窗口
候选  列表
微小的微, 信息的信 1
我现在
z
我现在
空格
*无标题 - 记事本
文本编辑器  编辑框  多行  我现在
z
Windows 输入体验  窗口
候选  列表
存在的在 1, 1. 存，居：存在。健在。青春长在。 2. 存留于某地点：在家。在职。在位。 3. 关于某方面，指出着重点：在于。在乎。事在人为。 4. 表示动作的进行：他在种地。 5. 介词，表示事情的时间、地点、情形、范围等：在逃。在望。在握。在理。在朝。在野。在世。 6. 和“所”连用，表示强调：在所不辞。无所不在。
在
z
正在
空格
*无标题 - 记事本
文本编辑器  编辑框  多行  我现在正在
c
Windows 输入体验  窗口
候选  列表
从此的从 1, 多音字【cóng】1. 依顺：顺从、盲从、从善如流。 2. 采取，按照：从优。 3. 跟随：愿从其后。 4. 跟随的人：侍从、仆从。 5. 参与：从业、从政、投笔从戎。 6. 由，自：从古至今。从我做起。 7. 次要的：主从、从犯。 8. 宗族中次于至亲的亲属：从父（伯父和叔父的统称）。 9. 中国魏以后，古代官品（有“正品”和“从品”之分，宋代龙图阁大学士为从二品）。 10. 姓氏从。 其他字意【zòng】1. 古同“纵”，竖，直。 2. 古同“纵”，放任。
从
s
测试
空格
*无标题 - 记事本
文本编辑器  编辑框  多行  我现在正在测试
s
Windows 输入体验  窗口
候选  列表
是否的是 1, 1. 表示解释或分类：他是工人。《阿Ｑ正传》的作者是鲁迅。 2. 表示存在：满身是汗。 3. 表示承认所说的，再转入正意，含有“虽然”的意思：诗是好诗，就是太长了。 4. 表示适合：来的是时候。 5. 表示任何：凡是。是活儿他都肯干。 6. 用于问句：他是走了吗？ 7. 加重语气，有“的确”、“实在”的意思：天气是冷。 8. 对，合理，与“非”相对：是非。他说的是。实事求是。 9. 认为对：是古非今。各行其是。深是其言。 10. 表示应承或同意（单说一个“是”字）：是，我就去。 11. 这，此：是日。是可忍，孰不可忍。比比皆是。 12. 助词，把行为对象提前表示只这样做：惟你是问。惟利是图。 13. 姓。
是
r
输入
f
输入法
空格
*无标题 - 记事本
文本编辑器  编辑框  多行  我现在正在测试输入法
d
Windows 输入体验  窗口
候选  列表
的确的的 1, 多音字【dí】真实，实在：的确。的当。的情。的真。的证。 其他字意【dì】箭靶的中心：中的。有的放矢。众矢之的。目的。 其他字意【de】1. 用在词或词组后表明形容词性：美丽的。 2. 代替所指的人或物：唱歌的。 3. 表示所属的关系的词：他的衣服。 4. 助词，用在句末，表示肯定的语气，常与“是”相应：这句话是很对的。 5. 副词尾，同“地”。
的
空格
*无标题 - 记事本
文本编辑器  编辑框  多行  我现在正在测试输入法的
s
Windows 输入体验  窗口
候选  列表
是否的是 1, 1. 表示解释或分类：他是工人。《阿Ｑ正传》的作者是鲁迅。 2. 表示存在：满身是汗。 3. 表示承认所说的，再转入正意，含有“虽然”的意思：诗是好诗，就是太长了。 4. 表示适合：来的是时候。 5. 表示任何：凡是。是活儿他都肯干。 6. 用于问句：他是走了吗？ 7. 加重语气，有“的确”、“实在”的意思：天气是冷。 8. 对，合理，与“非”相对：是非。他说的是。实事求是。 9. 认为对：是古非今。各行其是。深是其言。 10. 表示应承或同意（单说一个“是”字）：是，我就去。 11. 这，此：是日。是可忍，孰不可忍。比比皆是。 12. 助词，把行为对象提前表示只这样做：惟你是问。惟利是图。 13. 姓。
是
r
输入
空格
*无标题 - 记事本
文本编辑器  编辑框  多行  我现在正在测试输入法的输入
q
Windows 输入体验  窗口
候选  列表
过去的去 1, 1. 离开所在的地方到别处；由自己一方到另一方，与“来”相对：去处。去路。去国。 2. 距离，差别：相去不远。 3. 已过的，特指刚过去的一年：去年。去冬今春。 4. 除掉，减掉：去掉。去皮。去势。 5. 扮演戏曲中的角色：他去男主角。 6. 用在动词后，表示趋向：上去。进去。 7. 用在动词后，表示持续：信步走去。 8. 汉语四声之一：去声（ａ．古汉语四声的第三声；ｂ．普通话字调中的第四声）。
去
k
情况
### Expected behavior:
Normal report space after the input method on the screen
Here are the log files
[nvda.log](https://github.com/nvaccess/nvda/files/11259312/nvda.log)

#### NVDA installed/portable/running from source:
install version
#### NVDA version:
NVDA version alpha-28111,36a5eae2
#### Windows version:
Version 22H2 (OS internal version 22621.1555)
#### Name and version of other software in use when reproducing the issue:
none
#### Other information about your system:
none
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
none
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by josephsl** [comment]
Hi, does this happen also with Narrator? This happens because candidates window takes system focus away from Notepad when entering Chinese, and once the input composition window closes, focus returns to Notepad. If this also happens with Narrator, then we might as well work with Microsoft on improving this experience (my test setup: NVDA alpha 28089 with Windows App Essentials add-on disabled, Windows 11 22H2 build 22621.1555 with Korean IME installed). Thanks.

**Comment by dpy013** [comment]
> Hi, does this happen also with Narrator? This happens because candidates window takes system focus away from Notepad when entering Chinese, and once the input composition window closes, focus returns to Notepad. If this also happens with Narrator, then we might as well work with Microsoft on improving this experience (my test setup: NVDA alpha 28089 with Windows App Essentials add-on disabled, Windows 11 22H2 build 22621.1555 with Korean IME installed). Thanks.

Sorry, that was an oversight on my part.
The narrator has not been tested

**Comment by dpy013** [comment]
I just used the narrator to do a test in Notepad
The title of the notepad will be reported after the empty frame is on the screen.

**Comment by josephsl** [comment]
Hi, after entering Chinese and input composition window closes, yes? If so, this is something we can’t really fix from NVDA as this has to do with the redesigned IME interface in Windows 11, the very reason for creating #14836. Thanks.

**Comment by dpy013** [comment]
> Hi, after entering Chinese and input composition window closes, yes? If so, this is something we can’t really fix from NVDA as this has to do with the redesigned IME interface in Windows 11, the very reason for creating #14836. Thanks.
Got it, thanks
for the clarification, do I need to close this issue?

**Comment by josephsl** [comment]
Hi, for now I suggest closing this one unless other people would like to comment on it. Thanks.
