### ISSUE TITLE
In Microsoft Edge, some types of buttons or links are unintentionally pressed when focused with NVDA

### ISSUE THREAD

**Issue by brunoprietog** [nvaccess/nvda#14841]
### Steps to reproduce:

1. Press NVDA + 8 until NVDA says Automatically set system focus to focusable elements on. This is very important
2. Go to Google.com in Microsoft Edge and search for anything, such as "NVDA Screen Reader"
3. Press the number 3 to go to the first search result and scroll down with the arrows to the About this result button

### Actual behavior:

The button is pressed without pressing any key such as enter or space.

This happens with many buttons and links, but this is the easiest one I could find to replicate the error.

Disabling the option with NVDA + 8 is not a solution, as has been proposed in other issues that have been quickly closed. set system focus automatically to focusable elements in browse mode is a very important feature at least for me, especially if used with the Object Location Tones add-on.

Speech viewer:

NVDA+8
Automatically set system focus to focusable elements on
ithub.com selected
GitHubgithub.com location from history, presiona TAB y después Entrar para buscar  1 of 9
o unselected
o unselected
left arrow
g
gle.com unselected
enter
Cargando página
Google  document
search landmark
Carga completada
Google  document
search landmark
Search  combo box  collapsed  has auto complete  multi line  editable  blank
list
nvda screen reader  1 of 10
Search  combo box  expanded  has auto complete  multi line  editable  NV
enter
Cargando página
NVDA screen reader - Google Search
heading    level 1  Accessibility links
link    Skip to main content
link    Accessibility help
link    Accessibility feedback
search landmark    link    graphic    Google
Search  combo box  collapsed  has auto complete  multi line  editable  opens list    NVDA screen reader
button    Clear
button    Search by voice
button    Search by image
button    Search
main landmark    Download NVDA  heading    level 3  link  
Carga completada
down arrow
link    NV Access
down arrow
link    https://www.nvaccess.org › download
down arrow
button    About this result
About this result  dialog
Close About this result  button  
About this result
button    Close About this result
heading    level 3  Source
NonVisual Desktop Access is a free and open-source, portable screen reader for Microsoft Windows. 
The project was started by Michael Curran in 2006. NVDA is programmed in Python.

### Expected behavior:

Nothing should happen. Buttons or links should be pressed when you press enter or space only.

This is serious. I have submitted forms without my consent due to this error. In Firefox it doesn't happen, but many applications use Chromium in Electron as well and there is no way around it.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

NVDA alpha-28111,36a5eae2 (2023.2.0.28111)

#### Windows version:

Windows 11 22H2 (AMD64) build 22621.1555

#### Name and version of other software in use when reproducing the issue:

Microsoft Edge 112.0.1722.48

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Same behavior with 2023.1 and 2022.4

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by seanbudd** [comment]
We are planning on deprecating this option.
I would discourage using it to avoid this behaviour.

**Comment by brunoprietog** [comment]
@seanbudd Why do you plan to deprecate this option? It is too useful for me, it allows me to have a better understanding of the screen and the location of the elements in conjunction with the Object Location Tones add-on. When I disable it, I am infinitely less productive.

I don't understand why you close this bug so quickly. Still, probably many people have this option enabled and are going through the same thing.
