### ISSUE TITLE
Selected list item in Excel read twice

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#14856]
### Steps to reproduce:

Press ALT+A for the Data ribbon
Press V for the Data Validation menu
Press V again to open the Data Validation dialog
TAB to "Allow" and choose "List".
TAB to Source, and type:
1,2,3
Press ENTER

From that cell, press ALT+DOWN ARROW to open the list, and down arrow through the list. NVDA does not read out the items.

### Actual behavior:

This issue follows on from https://github.com/nvaccess/nvda/issues/6459  While that issue appears to be fixed now, in testing it, I found that the currently selected list item is read twice when you press alt+down arrow to open the list.  At that point, NVDA reads:

combo box expanded Has a data validation drop-down menu.
2
2

Reading the selected item twice (in this case 2 was selected). If you up and down arrow through the list at this point, NVDA reads each option once.

### Expected behavior:

The current item should only be read once.

#### NVDA version:

NVDA 2023.1 installed

#### Windows version:

Windows 11 (64-bit) Version: 22H2, Build: 22621.1555

#### Name and version of other software in use when reproducing the issue:

Office 365 (64-bit) Version: 16.0.16227.20244

**Comment by Adriani90** [comment]
@Qchristensen if you type 1;2;3 is there any difference on how NVDA reports the list options? I mean using semicolon instead of Comma?

**Comment by Adriani90** [comment]
Closing as non issue, data validation dropdowns in Excel cannot be navigated anymore for a longer time which is  severe in my view. See #15138 for more details.
