### ISSUE TITLE
focus is always redirected to Malwarebytes tray application when closing the last window or when closing certain menus or dialogs

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#14858]
### Steps to reproduce:
1. Install Malwarebytes
2. Open NVDA
3. Make sure you have only one window open
4. Press alt+f4 or use any other way to close that Window
5. Open more Windows
6. Navigate to the desktop
7. Open NVDA menu with NVDA+m or any dialog of NVDA settings
8. Press either escape, or activate ok or cancel button

### Actual behavior:
In step 4 and 8, NVDA is always redirected to a tray window application "Malwarebytes tray application". From here NVDA is silent when pressing arrow keys or tab key.

### Expected behavior:
NVDA should always be redirected to the desktop folder view list when closing last window, no matter which application is installed on your computer. The same should apply for menus or dialogs that are directly opened from the desktop folder view list, since the desktop was the focus area before opening the menu.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Version: alpha-28126,03c31e5b (2023.2.0.28126)

#### Windows version:
Windows 11 or Windows 10 22 H2

#### Name and version of other software in use when reproducing the issue:
Different ones, but Malwarebytes shows the behavior most obvious.

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, all previous versions that I tested had this, even 2019.1.

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Brian1Gaff** [comment]
I think this is a software issue. I used to see it with intel security 
elements until they fixed the problem.

Obviously somebody else will ask you for more details as in the template, 
though I suspect in this case, it is what it is. Can you hide the item so 
you  do not see it on the display unless you want to? Malwarebytes has lots 
of other flaws, like some of its text is unreadable or not recognised and 
some of its buttons seem to activate just by going to them.
 Brian
Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "Adriani90" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Friday, April 21, 2023 10:32 AM
Subject: [nvaccess/nvda] focus is always redirected to Malwarebytes tray 
application when closing the last window or when closing certain menus or 
dialogs (Issue #14858)

**Comment by Adriani90** [comment]
@Brian1Gaff I cannot reproduce your issue with buttons or checkboxes activated without my keayboard action. Maybe you accidentally move the the mouse cursors on the touchpad of your laptop when navigating, this can happen sometimes.
Otherwise I find their interface is quite accessible, also especially when using object navigation but also when using tab navigation.

Anyway, I have reported this focus redirecting issue to Malwarebytes as well.

**Comment by Adriani90** [comment]
Ok this is fixed in Malwarebytes 5 beta, Closing as works for me.
