### ISSUE TITLE
Combo box items not reported in Chrome or Edge in focus mode

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#14862]
### Steps to reproduce:
1. Open NVDA
2. Open this code in a browser
```
<body>
  <select role="combobox">
      <option value="Option 1">Option 1</option>
      <option value="Option 2">Option 2</option>
      <option value="Option 3">Option 3</option>
    </select>
</body>
```
3. Enter focus mode on the combo box
4. Press up and down arrow keys to select an eitem

### Actual behavior:
No matter if you expand the list or not, NVDA does not report the combobox items in focus mode.

### Expected behavior:
NVDA should report the combobox items in focus mode. It works as expected in Firefox.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Version: alpha-28126,03c31e5b (2023.2.0.28126)

#### Windows version:
Windows 11 22 H2

#### Name and version of other software in use when reproducing the issue:
Chrome and Edge 112

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2023.1 has the same issue.

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by burmancomp** [comment]
Same with Chrome 113.0.5672.53 beta 64-bit in Windows 10; NVDA current source.

**Comment by Adriani90** [comment]
cc: @michaelDCurran any idea why this happens only in Chromium browsers? Is a change needed in NVDA? Or should we report this to Chromium?

**Comment by Adriani90** [comment]
This is fixed in Chromium canary 129 by Chrome developers. Works with  NVDA 2024.3 RC1. Closing as works for me.
