### ISSUE TITLE
Hot Key to get line and percent statistics in virtual buffers

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1487]
**Reported by ianr on 2011-05-03 16:44**
Sometimes when I am reading a very large article or tutorial in a web browser I wish I could get some indicator of how far I am in the document.  I'd like to be able to press a hot key that tells me what line I am on and how many lines there are in the document and / or what percent complete I am with the document.

Editors usually provide this information via the status bar.

This could be helpful when coming back to a document later and trying to return to where you left off by pressing page down repeatedly.
Or perhaps later a go to line feature could be added.

I could just copy the whole page and paste it into an editor, but this results in me losing the quick navigation keys to jump between headers and the ability to follow links.

**Blocked by #4219**

**Comment by bhavyashah** [comment]
Out of interest, could someone please share the download link of the Percentage Checker add-on being discussed as well as its source code for the benefit of NVDA developers?

**Comment by ehollig** [comment]
When I did a search for the percentage checker addon, I found this. http://oriolgomez.com/files/percentageChecker.nvda-addon
It is not on the official list of addons but I can confirm that it indeed works. There are some other pretty useful addons on this site as well.

**Comment by leonardder** [comment]
I"m tempted to close this as per https://github.com/nvaccess/nvda/issues/1487#issuecomment-155289875 . I agree that in browse mode, line numbers are probably not very useful

**Comment by leonardder** [comment]
Closing now. If this is still an issue, please provide info on what you expect and what's happening instead.
