### ISSUE TITLE
NVDA announces 'caption' before every element within figcaption element

### ISSUE THREAD

**Issue by clanceyp** [nvaccess/nvda#14874]
### Steps to reproduce:
Author a webpage containing a figure and figcaption element. Add links to the figcaption element (as allowed in the HTML spec)
e.g. https://codepen.io/clanceyp/full/RweVbBj

### Actual behavior:
NVDA announces "caption" multiple times through out the figcaption content
e.g. NVDA speaks "caption link [link label]" for each link element within a figcaption

<img width="946" alt="Screenshot 2023-04-25 at 19 02 02" src="https://user-images.githubusercontent.com/889590/234372106-149ec794-23b9-48f7-917e-1d87687bd56f.png">

### Expected behavior:
NVDA announces "caption" a single time at the beginning of the figcaption content
e.g. NVDA speaks "link [link label]" for each link element within a figcaption

### NVDA logs, crash dumps and other attachments:
NA
### System configuration
NA
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2023.1
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
MS Edge 112.0.1722.58
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No have not tried.
#### If NVDA add-ons are disabled, is your problem still occurring?
no add-ons installed
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Brian1Gaff** [comment]
Yes I think this has always been the case on large graphics with nvda, and I 
just tested it on windows 7  and its the same. I actually thought this was 
how it was supposed to be.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "Patrick" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Tuesday, April 25, 2023 7:49 PM
Subject: [nvaccess/nvda] NVDA announces 'caption' before every element 
within figcaption element (Issue #14874)

**Comment by clanceyp** [comment]
Our accessibility team want us to remove all figcaption elements from our system entirely as they don't like this unnecessary repetition.

**Comment by Adriani90** [comment]
Maybe I am wrong, but is it at all necessary to report the word "caption"? Actually if the text with the caption role itself is reported, I don't really get why the user should hear "caption" at all. Caption is not an element that I can interact with like a link or a button. It is also not a table, The word "caption" or "figure " does not imply a certain interaction method. So it should actually suffice to hear the elements with the role figure or caption like the Text itself, element type (i.e. grafic, link, button, heading etc.)

cc: @michaelDCurran, @seanbudd, @jcsteh what do you think?

**Comment by clanceyp** [comment]
@Adriani90 I agree. My example with the book cover isn't a very good one, if the image is quite complex (e.g. it's a chart) and the information associated with it is the contents of figcaption (the association between the image and the figcaption is working a bit like aria-describedby). When the img tag is being read you would want to hear that it "Has caption" (or something similar), you don't really need the figcaption element itself to be announced as such, and definitely not all its children.
