### ISSUE TITLE
foobar2000 x64 accessibility problem

### ISSUE THREAD

**Issue by djgraco** [nvaccess/nvda#14871]
### Steps to reproduce:
1. Install a foobar2000 x64
https://www.foobar2000.org/download

2. Go to preferences/display/context menu.
3. In the list of context menu icons, NVDA does not tell us whether a given control is checked or unchecked, it omits the checkbox at all. The same happens in the advanced preferences in the tree, where there are also checkboxes.

#### NVDA installed/portable/running from source:
NVDA Installation version

#### NVDA version:
2023.1

#### Windows version:
Windows 10 pro x64 22h2

#### Name and version of other software in use when reproducing the issue:
foobar2000 portable x64 v2.0 beta 34

### Other questions
I created a thread on the official foobar forum, where the author even referred to it. At the moment, I can't pinpoint exactly what's causing the problem. Can anyone confirm what I wrote above?
https://hydrogenaud.io/index.php/topic,122858.0.html
I don't even know on which side the problem lies, foobar side or nvda side?

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I haven't tried other versions of nvda. I've been seeing this issue since version 2022

#### If NVDA add-ons are disabled, is your problem still occurring?
With disabled addons problem is occurring.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by djgraco** [comment]
Okay, sorry for my indecision. Finally, I leave the thread open. For now, the case is pending and we will wait for Peter's actions.

**Comment by seanbudd** [comment]
Closing as an authoring issue
