### ISSUE TITLE
USB x NVDA could not load Braille Display. BT works properly

### ISSUE THREAD

**Issue by Thalitaw** [nvaccess/nvda#14870]
Hello!
 
I need some help on a probably driver issue.
*To clarify*:
 
- Bluetooth connection and NVDA works properly. 
- USB connection and NVDA = Error: “NVDA could not load Hims Display”.  
 
Ps:
-Hims USB driver installed,
- USB + Windows Narrator works properly (due it has a independent driver),
-I’ve already tried te remove and Install again NVDA, Hims Driver, Bluetooth and Usb controller drivers but the error remains. 
 
 
I am posting the*NVDA log error* just because it is very brief snippet and focuses directly on the issue reported. 
 
ERROR - braille.BrailleHandler.setDisplayByName (10:46:41.565) - MainThread (8288):
Error initializing display driver hims for kwargs {'port': 'auto'}
Traceback (most recent call last):
  File "braille.pyc", line 2131, in setDisplayByName
  File "brailleDisplayDrivers\hims.pyc", line 235, in __init__
RuntimeError: No Hims display found
 
*Device Manager* - Hims driver (libusb):
 
USB (usb/vid_045e&pid_930b/)  needs an additional installation.
 
Could u pls help me?
Thalita Uttembergue.

**Comment by XLTechie** [comment]
You did not fill out the issue template. What is your version of NVDA? What is 
your version of Windows? What is your version of the braille display driver?

Have you tried contacting Hims?

Next time, please fill out the template--it's there to collect the information 
that is needed to properly start providing assistance.

**Comment by seanbudd** [comment]
Welcome @Thalitaw ,

We are unable to process this issue as it stands.

Please fill out the issue template fully.

Kind Regards,
NV Access Software Developers

**Comment by Thalitaw** [comment]
Hey Sean!
Tks for the answer. I did it! I enter in Narrator on Windows and I modified the driver in use for it. I don”t know what happened, if this forced to update something or even it was because the Narrator and Nada could not use the same driver, I don’t know, but it solved.
Thanks anyway ;)

**Comment by Adriani90** [comment]
@Thalitaw I had a similar problem with some users here in Germany, it seems Nrator overtakes the braille display as soon as you install a Braille driver or BRLTTY in Narator, so afterwards NVDA cannot see it anymore. This is definitely something which needs to be reported to Microsoft.

Is for Hims a Braille driver needed at all in NVDA? I thought NVDA would recognize it without the Hims extra driver as well.

Anyway, thanks for the update, closing as works for me.

**Comment by josephsl** [comment]
Hi, if you haven’t, try after upgrading to Windows 11 22H2, more specifically build 22621.1344 or later as changes were made to help Narrator cope better with third-party screen readers as far as braille display drivers are concerned. Thanks.
