### ISSUE TITLE
Support for Microsoft Silverlight

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1488]
**Reported by cardsfan22 on 2011-05-04 20:49**
I would like to see NVDA work with Microsoft Silverlight.  I know Silverlight is used with Netflix when one wants to watch a movie or TV show instantly on his/her computer.  I'm sure it is used in other instances.  It doesn't read the controls (play, forward, rewind, pause, etc.) and it doesn't read the episode names if one wants to jump around when watching a season of a TV series.

**Comment by leonardder** [comment]
Silverlight has been discontinued and this ticket looks abandoned anyway. Closing as invalid, since @JCSTeh pointed out that silverlight apps should be accessible if app authors took that in mind.
