### ISSUE TITLE
Braille: when routing review cursor, route also system caret if desired

### ISSUE THREAD

**Issue by burmancomp** [nvaccess/nvda#14885]
### Is your feature request related to a problem? Please describe.
If braille is tethered to review cursor, system caret is not moved in text areas when navigated with braille display buttons (scroll forward/back, next/previous line). This is fine because then system caret keeps it position when checking something for example from previous line.

But if you navigate with display buttons for example to the previous line and there is typo you would like to correct, it is quite complex. You can press routing button to get review cursor to the desired position, but then you have to move system caret with separate command.
### Describe the solution you'd like
There should be setting in the braille settings dialog. Setting could be something like "Routing review cursor routes system caret". This setting would have effect only if braille would be tethered to review cursor. Current behavior should be default.
### Describe alternatives you've considered
In addition to the setting described above some modification of script_braille_routeTo in globalCommands.py.
### Additional context
If accepted, I could try to implement this.

**Comment by burmancomp** [comment]
This alternative where reviewing content without affecting caret and routing caret to reviewing position when needed has been supported for decades by several software.

NVDA supports it also but it requires more steps: pressing routing button and then moving focus/caret. I think this could be combined and performed with one routing button press.

Setting in braille settings dialog which could be for example "Routing review cursor routes system caret" could be a feature flag which default would be disabled. Because setting would only have effect if also braille would be tethered to review cursor, setting could be hidden when braille is tethered to automatic/focus.

There should not be difference in reliability because adequate implementation could only combine pressing routing button with moving focus/caret (mainly without spoken messages).

This would have no effect on many braille users but some would get additional alternative to use NVDA with their braille displays.

**Comment by irrah68** [comment]
I think this would be a very useful feature. This is something I have always been waiting to happen in NVDA. Burmancomp has compiled a test version of NVDA and I have tried it with my Braille display. It seems to work as expected.

**Comment by burmancomp** [comment]
I noticed there is issue #3166. Could these both be solved at same time, and could same solution be acceptable for both issues?

**Comment by Jykke67** [comment]
I really do hope, and I’ve said this earlier, that this feature, like the other one discussed, would be implemented to NVDA as soon as possible, or even earlier without an endless discussion about the issue.

The same goes for the verbosity issue that has been discussed concerning different verbosity levels in order to customize announcements of heading levels etc. on webpages.

**Comment by burmancomp** [comment]
@seanbudd

Why product decision is needed in this case (I'm not familiar with product decision process or practice)? Do you think there are some disadvantages if this is implemented with feature flag setting or do you think other implementation would be better or should there be more people who would like this to be implemented? I suppose many screenreaders have supported this.

Many questions but I would only like to know if this could be implemented to NVDA some day, and what it would require.

**Comment by michaelDCurran** [comment]
I support implementing a solution for this.
I see 3 options:
1. Provide an extra config option when tethered to review, where if a routing button is pressed, both the review cursor and system caret are moved. 
2. When tether is automatic, and review cursor is temporarily shown in braille, pressing a routing button will move both review cursor and system caret.
3.  If tether is set to review, or tether is automatic and braille is temporarily showing review cursor, double pressing a routing button moves both review cursor and system caret.

My preference would be option 2.
If this is implemented issue #3166 can be closed.

**Comment by leonardder** [comment]
As pointed out in #15044, I really want to take this back to the drawing board. It looks like @michaelDCurran expressed his preference for a solution in https://github.com/nvaccess/nvda/issues/14885#issuecomment-1598166983 but #15044 chose another implementation. Furthermore #15044 also seems to fiddle with focus. I'm not sure whether that's desirable.

First of all, I think we need to understand the use case of this feature better. Here are three findings that make me question the necessity of changes in this area. Even worse, I'm afraid it will cause unintended side effects.

### Finding 1
1. Focus the desktop
2. Set braille tethered to review and review cursor to object
3. Observe that a routing key press on a desktop icon will perform the action on the object, just as what would happen if tethering was set to focus.

Technical explanation: NVDAObjectRegion.routeTo calls doAction on the object.

### Finding 2
1. Focus the desktop
2. Set braille tethered to review and review cursor to screen
3. Observe that one routing press on an icon will set the review cursor and a second press will try to perform a single mouse click on that text, which in this case means that you';re about to rename the icon.

Technical explanation: TextInfo.RegionrouteTo sets review cursor on first press and performs textInfo.activate on second press, which performs the mouse click.

### Finding 3
1. Open Notepad in Windows 11
2. Set braille tethered to review and review cursor to object
3. Observe that one routing press on a character will set the review cursor and a second press will try to perform a single mouse click on that character, which implicitly moves the system caret.

Technical explanation: TextInfo.RegionrouteTo sets review cursor on first press and performs textInfo.activate on second press, which performs the mouse click on the character.

**Comment by burmancomp** [comment]
@leonardder I tried what you described in findings. System is Windows 10. I think behavior is very similar but I had "Route review cursor and system caret" disabled. Finding 2 required 3 presses but nothing was selected before first press.

Enabling "Route review cursor and system caret" gives same result with finding 1 and finding 2.

Could you please clarify this?

**Comment by leonardder** [comment]
What do you mean with "I had "Route review cursor and system caret" disabled"? Do you mean the new function you added in #15044 or the follow review cursor/system caret options?
If the former, mmy findings were with the current version of Alpha, without your pr in place.

**Comment by burmancomp** [comment]
Yes I had that functionality included and I tried your findings when that was disabled and enabled.

I think findings 1 and 2 were same so I suppose that new functionality has no effect on those. Finding 3 was different when new functionality was enabled but this is just for what that functionality should be there.

I'm unsure the relationship of these findings with pr #15044.

**Comment by leonardder** [comment]
> I'm unsure the relationship of these findings with pr #15044.

The findings show that #15044 might not be necessary since it is already possible to move the system caret when braille is tethered to review.

**Comment by burmancomp** [comment]
> The findings show that #15044 might not be necessary since it is already possible to move the system caret when braille is tethered to review.

But why user should press routing button twice if it is possible to perform task with one press? This is important question. I suppose that those who have used their display to review text without moving caret and to move caret when needed, have used one routing button press to do this. Those who have used NVDA have also used one routing button press to move caret. All users should start to work differently.

Although it should not happen, I think that it is not so rare: you pressed a button but for some reason your press was not recognized. This would be very harmful with second press because caret was not moved yet, and you would not notice that second press was failed.

I think two (or more) presses would not be right direction.

There is same question if this would only implemented for automatic tether: why user should perform "object command" before he/she could review and use routing buttons to route caret.

User can select tether to focus, or tether to automatic and not use temporary review tether, but in both cases when he/she reviews text, caret position is changed although user would not have any reason to move it (for example there were no typos to correct). Result is that user has to move cursor again - it may require many key strokes. But if there is functionality what for example #15044 tries to implement, only one button press from braille display is needed, and user is back there where he/she started review (I suppose most displays has defined gesture to go back where cursor is).

In #15044 implementation user can select:

- keep the previous behavior (feature flag is disabled by default)
- use when tethered to automatic; enable setting (feature flag) and use as suggested in option 2
- use when tethered to review; enable setting and use as suggested in option 1

It is possible to define gesture for both tether and "Route review cursor and system caret" (#15044) so user can quickly change behavior, and I suppose that configuration profiles can also be used.

I think this would improve user experience of braille giving users more possibilities to select from how they like use their braille displays.

**Comment by leonardder** [comment]
> But why user should press routing button twice if it is possible to perform task with one press? This is important question. 

I guess this question can be asked for multiple scripts that require several key presses. In this case I'd say, the behavior is consistent. Introducing the feature as in #15044 introduces inconsistency. When braille is tethered to focus, the behavior is clear for objects with caret, first press moves cursor, second press activates the position. The review cursor is just a virtual caret, and therefore the current behavior for Braille makes perfect sense.

As for how to progress this, I think we must return to the proposed solutions by @michaelDCurran 

>     1. Provide an extra config option when tethered to review, where if a routing button is pressed, both the review cursor and system caret are moved.
> 
>     2. When tether is automatic, and review cursor is temporarily shown in braille, pressing a routing button will move both review cursor and system caret.
> 
>     3. If tether is set to review, or tether is automatic and braille is temporarily showing review cursor, double pressing a routing button moves both review cursor and system caret.
> 
> 
> My preference would be option 2.

I second @michaelDCurran's preference here. The current pr introduces unrelated behavior, such as focusing objects. This has never been the explicit behavior of routing keys and is therefore out of scope of the current request. Furthermore, I think the changes should be in braille.py (i.e. the routing behavior in there), not in the routing script.

I'm happy to provide a quick prototype as an alternative for #15044. Then, it might be easier to compare things.

**Comment by XLTechie** [comment]
I haven't used refreshable braille under Windows, ever, so have hardly any 
opinion or prospective on this.

That said, the discussion has made me curious. If all of the other screen 
readers can do this already, as has been said, in what way do they implement it, 
from a user point of view?

Would it make sense to try to approximate, as much as possible, the behavior and 
UI that has gone before, and with which users are likely already familiar?

This might not be a one to one mapping, of course, but I haven't read, unless I 
missed it which is possible, a description of how the other SRs do this. I have 
only heard a few times that all/most of them do provide it.

**Comment by burmancomp** [comment]
> I guess this question can be asked for multiple scripts that require several key presses. In this case I'd say, the behavior is consistent. Introducing the feature as in #15044 introduces inconsistency. When braille is tethered to focus, the behavior is clear for objects with caret, first press moves cursor, second press activates the position. The review cursor is just a virtual caret, and therefore the current behavior for Braille makes perfect sense.

Unfortunately this is not what my purpose is with this issue. The reason to use multiple key presses should not be that there are several scripts using that. My approach is to minimize number of steps to perform task. I like to route cursor with one button press. If braille is following focus, then it is focus but if braille follows review, then it is review cursor or focus defined with setting. I cannot think that this is problematic logic. It is different.

> As for how to progress this, I think we must return to the proposed solutions by @michaelDCurran
> 
> > ```
> > 1. Provide an extra config option when tethered to review, where if a routing button is pressed, both the review cursor and system caret are moved.
> > 
> > 2. When tether is automatic, and review cursor is temporarily shown in braille, pressing a routing button will move both review cursor and system caret.
> > 
> > 3. If tether is set to review, or tether is automatic and braille is temporarily showing review cursor, double pressing a routing button moves both review cursor and system caret.
> > ```
> > My preference would be option 2.
> 
> I second @michaelDCurran's preference here. The current pr introduces unrelated behavior, such as focusing objects. This has never been the explicit behavior of routing keys and is therefore out of scope of the current request. Furthermore, I think the changes should be in braille.py (i.e. the routing behavior in there), not in the routing script.
> 

My interpretation is that @michaelDCurran suggestion is that both review cursor and system caret are moved with one routing button press - no two presses needed. #15044 requires only one routing button press and works in "tethered to automatically" mode. My arguments that option 2 is not adequate are:

- routing buttons work differently when braille follows review continuously or temporarily
- extra step is needed to use this functionality because temporarily tether to review must be activated (harmful if one thinks he/she uses this often)
- to get previous routing button behavior user should change tether to review because they route also system caret in "automatically" mode when following review.

I prefer that there is setting which enables/disables this. Behavior of routing buttons is not affected whether review cursor is followed temporarily or continuously but value of setting (disabled or enabled).

#15044 focuses objects but objects may be focused currently with routing buttons when followin review. With #15044 this should be perhaps told better. I do not think focusing objects is problem - what would disadvantages be?

Jaws users might like behavior of #15044. Jaws has somewhat similar (I do not say similar) alternative as in #15044. I have understood that people may have thought that NVDA's braille functionality is more limited when comparing to Jaws. Maybe this is one reason.

Implementation of #15044 may require fixing. However it works and its functionality is what I think solution of this issue should contain.

This is not objective but in my opinion user experience of braille is better with than without #15044.

**Comment by irrah68** [comment]
I'm now using a test version of NVDA compiled by @burmancomp. Braille is tethered to review and Route review cursor and system caret is enabled. I think that this kind of new feature will make NVDA's Braille support better and it gives more flexibility from an user's point of view.

Even writing this comment is easier than before.

I have also tested some object navigation, and it feels very easy and practical when I can press a routing button to do something, for example if I want to start a program, maximize a window etc.

These kinds of features have been in use in other screenreaders for many years. Ofcourse screenreaders are all different in many ways but they are ment to be used for the same purposes. It is good to see that NVDA is getting better Braille support.

**Comment by leonardder** [comment]
@burmancomp Thanks for clarifying. My impression is that we're both intending to achieve the same, I'm just a bit worried about how #15044 with all the logic that's added to the routing script.
I'd still like to know @michaelDCurran's thoughts about how to bring this to a good end.

**Comment by burmancomp** [comment]
@leonardder and @michaelDCurran my interest is that when braille is tethered to review (continuously or temporarily), user can decide if he/she wants that single routing button press routes both review cursor and focus/caret, or just review cursor. This requires setting in braille dialog, and input gesture for quick change.

Using #15044 is not important. However, it should show what kind of user experience there should be.

**Comment by leonardder** [comment]
I just created https://github.com/nvaccess/nvda/pull/15064 as an alternative implementation to #15044. @burmancomp again, not trying to criticize your implementation in any way, just trying to do what seems to be most appropriate to do, based on some experience with the braille module I gained in the last years.
