### ISSUE TITLE
notepad++ anomaly NVDA stops reading editor content

### ISSUE THREAD

**Issue by FrancoisLB** [nvaccess/nvda#14903]
### Actual behavior:

once notepad++ is openned, i open a python file.
i can move the text cursor in the text of the file.
NVDA starts to annonce the text.
after a time variable time period NVDA stops to speak.
i have to restart nvda to solve this anomaly.

this observed under windows 10.
 NVDA is suppose to speak all along the content of the code shown in the notepad+++ edition window.

NVDA seams to be unstable with notepad ++

### NVDA logs, crash dumps and other attachments:
no dumps avalable

#### NVDA installed/portable/running from source:
installed version 

#### NVDA version:
2023.1

#### Windows version:
windows 10

#### Name and version of other software in use when reproducing the issue:
notepad++ version 8.4.8
 
#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

**Comment by seanbudd** [comment]
Welcome @FrancoisLB ,

We are unable to process this issue as it stands.

- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.
- Can you please test with the latest Notepad++ version 8.5.2
- This is very likely a problem with the implementation of the application/website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers

**Comment by FrancoisLB** [comment]
Hello,

 

I have updated notepad++ software. You’re righet, now, NVDA works properly.

 

So this ticket could be closed.

 

Many thanks for your help

 

Best regards

 

François

 

 

De : Sean Budd ***@***.***> 
Envoyé : mardi 9 mai 2023 10:51
À : nvaccess/nvda ***@***.***>
Cc : FrancoisLB ***@***.***>; Mention ***@***.***>
Objet : Re: [nvaccess/nvda] notepad++ anomaly NVDA stops reading editor content (Issue #14903)

 

Welcome @FrancoisLB <https://github.com/FrancoisLB>  ,

We are unable to process this issue as it stands.

*	Please reproduce this issue and provide a log file <https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps>  of the behaviour. Ensure your log level is set to debug in general preferences.
*	Can you please test with the latest Notepad++ version 8.5.2
*	This is very likely a problem with the implementation of the application/website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers
