### ISSUE TITLE
nvda crashes while using grade 1 or grade 2 braille tables with capital letter marks

### ISSUE THREAD

**Issue by dave090679** [nvaccess/nvda#14901]
### Steps to reproduce:
1. open an empty notepad.
2. in nvda braille settings, set any braille table with capital letter marking (either german basic braille [detailed] or german grade 1 [detailed] or german grade 2 [detailed]).
3. in the notepad window, type a string according the following pattern: one uppercase letters, followed by a dot, followed by two lowercase letters. examples of such "killer strings" are "Q and A.html", "j f K.mp4". Just when you type the second lowercase letter, nvda crashes. it fortunattelly doesn't save its settings, so you can just start nvda again to have your old braille table active. 

### Actual behavior:

NVDA crashes when a string with the format X.xx has to be displayed in braille
### Expected behavior:

nvda should display the strings properly without crashing
### NVDA logs, crash dumps and other attachments:
log file: [nvda-14901.txt](https://github.com/nvaccess/nvda/files/11392478/nvda-14901.txt)

#### NVDA installed/portable/running from source:
nvda is installed
#### NVDA version:
nvda 2023.1
#### Windows version:
Microsoft Windows 11 Version 22H2 (Build 22621.1555)

#### Does the issue still occur after restarting your computer?
yes.
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
Is this occuring in other applications as well? Or only in Notepad?
Can you also check if NVDA generated any crashdump as follows?
1. Open run by pressing Windows+r
2. Type "%localappdata%\crashdumps" and press enter
3. Is there a crashdump generated for NVDA in that folder?
4. If not, have a look in "%temp%", is there a crashdump for NVDA generated?

**Comment by seanbudd** [comment]
in future please upload a log file rather than copy and pasting the log into the issue. it makes it very difficult to read.

**Comment by seanbudd** [comment]
Can you also test with NVDA alpha and with add-ons disabled and confirm this is still an issue?
If this is still an issue please provide a log with the add-ons disabled using alpha

You can download NVDA alpha from www.nvaccess.org/files/nvda/snapshots/

**Comment by michaelDCurran** [comment]
I was able to reproduce this in NVDA 2023.1. But not in current alphas.
Most likely fixed by upgrade to liblouis 3.25.0.
