### ISSUE TITLE
facing a strange problem on google related sites in google chrome

### ISSUE THREAD

**Issue by narayan-b-raikar** [nvaccess/nvda#14915]
#### NVDA version: (NVDA)
Version: 2023.1 (2023.1.0.27913)

#### Other information about your system: Dell inspiron 15 3542, Processor: Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz   1.70 GHz
Installed memory (RAM): 4.00 GB
System type: 64-bit Operating System, x64-based processor

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu? Yes.

As mentioned above, I have been experiencing a strange problem with NVDA Screen-reader for a long time. This problem was also occurred in its earlier beta version i.e., NVDA 2023.1 beta 1, beta 2 etc. The problem is that when we open the Gmail site in google chrome and try to focus on any link or button, that link or button is automatically executed without our knowledge. This problem is not only in Gmail site, but in some other sites egg - web google play store, google search, Gmail account site etc. As far as I know mostly this problem seems to happen only on google related sites in google chrome. This makes it exceedingly difficult for us to browse these sites. We request you to resolve this issue as soon as possible. thank you.

**Comment by XLTechie** [comment]
Turn off "Automatically set system focus to focusable elements" in NVDA's browse 
options, or on a US keyboard, press NVDA+8.

**Comment by narayan-b-raikar** [comment]
OK, Now this problem is solved. But, I only checked on google search result page. Not checked in other google related site.But, Why this is happening? This problem was not  appearing before.
thanks anyway.

**Comment by seanbudd** [comment]
We are planning on deprecating this option.
I would discourage using it to avoid this behaviour.

**Comment by narayan-b-raikar** [comment]
OK Thank you for your reply. regards. @

> We are planning on deprecating this option. I would discourage using it to avoid this behaviour.

**Comment by XLTechie** [comment]
Changes in Chrome/Chromium have brought this to prominence recently. It was 
always possible that this option could cause strange effects, but now it is 
worse. Using it is discouraged.
