### ISSUE TITLE
Microsoft edge: unable to redirect focus to context menu in downloads window

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#14916]
### Steps to reproduce:
1. open Microsoft Edge;
2.Try to download something;
3.press control+j to open downloas window;
4.press Applications key or shift+f10 to invoke context menu.
### Actual behavior:
Context menu opens, but NVDA focus is not redirected there and arrow keys does not do anything.
### Expected behavior:
Context menues should be read as in previous msedge versions.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-28193,d1ce3bc9 (2023.2.0.28193)
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.2728
#### Name and version of other software in use when reproducing the issue:
Microsoft Edge Version 113.0.1774.35 (Official build) (64-bit) Version 113.0.1774.35 (Official build) (64-bit)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by beqabeqa473** [comment]
Yes, it is not reproucable with narrator

On 5/10/23, Cyrille Bougot ***@***.***> wrote:
> Is it OK with Narrator instead?
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/14916#issuecomment-1541577956
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Adriani90** [comment]
Quote from @Qchristensen in #14922:

> I did find a workaround for anyone hitting this, is to open the downloads page rather than the "menu":
> 1. Press alt+d to open the address bar.
> 2. Type the following
> edge://downloads
> 3. Press enter
> The user who reported this also noted that the context meu (after pressing control+j ) reads fine with both Narrator and Jaws.

> Update from Microsoft: "Everything seems normal to me. There is a focus being fired to each new menu item. I see that NVDA isn’t speaking but not sure why."

**Comment by Gene703122** [comment]
This issue isn't limited to the download window.  Try to open the context menu on any link appearing on any opened Web page.  NVDA doesn't speak when you open the context menu and move in it.  That makes the issue more important because functions such as save link as and copy link are found in the context menu.

**Comment by enessaribas** [comment]
This is an issue specific to NVDA. Jaws works fine with Edge.

**Comment by wmhn1872265132** [comment]
Press Ctrl+D to add favorites, then press Tab, space, the pop-up menu NVDA also cannot read aloud.

**Comment by Carlos-EstebanM** [comment]
Hi all.
In my computer, if I tray to open the context menu on a link, for example for copy the URL, the first time NVDA cannot read the options. I need to press escape, tray again and the second time I can use the menu. Also, I have this problem in the pop-up for change the folder of a favorite, and in the downloads page (if I open this page with Control + j).
Regards.

**Comment by zersiax** [comment]
I think there's two different issues here.

The context menu on links on a page I have  seen for a long time, and the way to fix that one is to just go into focus mode after which it works fine. That does not appear to work for the downloads window though

**Comment by Carlos-EstebanM** [comment]
Hi all.
Recently, I discovered that this problem also is  present in another menu. Press CTRL+h to open the history. Press tab to navigate and press a button called more options. NVDA cannot read the context menu.
NVDA 2023.1, Microsoft Edge version 114.0.1823.43.
Regards.

**Comment by beqabeqa473** [comment]
i can confirm this

On 6/12/23, Carlos-EstebanM ***@***.***> wrote:
> Hi all.
> Recently, I discovered that this problem also is  present in another menu.
> Press CTRL+h to open the history. Press tab to navigate and press a button
> called more options. NVDA cannot read the context menu.
> NVDA 2023.1, Microsoft Edge version 114.0.1823.43.
> Regards.
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/14916#issuecomment-1587590233
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by enessaribas** [comment]
hi again,
This is not solved in Edge 114. Possibly update ticket name to indicate this?

**Comment by Qchristensen** [comment]
> hi again, This is not solved in Edge 114. Possibly update ticket name to indicate this?

I've updated the title to remove the version number.

**Comment by cary-rowen** [comment]
Hi @seanbudd 

It's hard to say this isn't a Microsoft issue, but since the issue only occurs with NVDA, I wonder if NV Access could investigate this.
There have been [discussions](https://nvda.groups.io/g/nvda/topic/microsoft_edge_114_issues/100073783) around this issue on Groups.io, and it's important to note that Ms Edge is the default browser that comes pre-installed on Windows, and the issue is serious enough to warrant attention.

Thanks

**Comment by mzanm** [comment]
It seems shouldAcceptEvent is returning false, not sure why as I don't know about how eventHandler works.

**Comment by seanbudd** [comment]
Note a useful log was posted in https://github.com/nvaccess/nvda/issues/15293

**Comment by rperez030** [comment]
I don't think this problem is being caused by edge along. It can be a showstopper in some situations, for example, if someone tries to download a file which is legit but flagged by Windows defender for not having a signature, and the user needs to open the context menu to allow the download. I'm aware there have been efforts on the Microsoft side to identify the cause of this without success. The fact that it only reproduces with NVDA doesn't make it easier. cc @benbeaudry

**Comment by beqabeqa473** [comment]
Hi.

For now you can try to use addon from this link.
https://github.com/beqabeqa473/MSEdgeDiscardAnnouncements/releases/download/v0.9/MSEdgeDiscardAnnouncements-0.9.nvda-addon

On 8/15/23, Roberto Perez ***@***.***> wrote:
> I don't think this problem is being caused by edge along. It can be a
> showstopper in some situations, for example, if someone tries to download a
> file which is legit but flagged by Windows defender for not having a
> signature, and the user needs to open the context menu to allow the
> download. I'm aware there have been efforts on the Microsoft side to
> identify the cause of this without success. The fact that it only reproduces
> with NVDA doesn't make it easier. cc @benbeaudry
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/14916#issuecomment-1678936257
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by rperez030** [comment]
> Hi. For now you can try to use addon from this link. https://github.com/beqabeqa473/MSEdgeDiscardAnnouncements/releases/download/v0.9/MSEdgeDiscardAnnouncements-0.9.nvda-addon

Thanks @beqabeqa473 for doing that.

**Comment by cary-rowen** [comment]
Hi @seanbudd 

This is a serious issue for NVDA users, would you consider fixing it in an upcoming release?
Or @beqabeqa473 could you consider opening a PR to NVDA to fix this?
Thanks

**Comment by leonardder** [comment]
I just created pr #15300. @seanbudd given the questions/concerns above, please consider taking this for 2023.2.
