### ISSUE TITLE
Give information on changing settings categories in NVDA's settings dialog

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#14927]
### Is your feature request related to a problem? Please describe.

NVDA's settings dialog is divided into categories.  The user guide covers these in section 12: https://www.nvaccess.org/files/nvda/documentation/userGuide.html#NVDASettings

In 12.1, the guide mentions there are shortcut keys to jump to specific categories and also talks about changing categories.  It would be worth including a sentence clarifying that you can change categories with control+tab / control+shift+tab.

### Describe the solution you'd like

The last line before of 12.1 reads:
The settings categories found in the NVDA Settings dialog will be outlined below.

A sentence could be added after this reading:

To change between categories, press control+tab to move forward, or control+shift+tab to move backwards, or use tab or shift+tab to move to "Categories" list and use the arrow keys.

### Describe alternatives you've considered

Although these are standard Windows controls, and thus not otherwise covered in the user guide, as it covers navigating a specific dialog within NVDA, it doesn't hurt to confirm this is how the dialog works as there can be alternate implementations of similar controls.  We have recieved a query from a user on this.

(These keys are currently covered in the Basic Training for NVDA module as well, though not in the context of the NVDA settings dialog).

**Comment by XLTechie** [comment]
@Qchristensen wrote:
> NVDA's settings dialog is divided into categories. The user guide covers these in section 12:
> https://www.nvaccess.org/files/nvda/documentation/userGuide.html#NVDASettings

Which starts with:

"
The NVDA Settings dialog contains many configuration parameters that can be 
changed.
This dialog contains a list with several categories of settings to choose from.
When you select a category, several settings related to this category will be 
shown in this dialog.
"

There is a lot of word re-use in those sentences, that makes it difficult to 
read IMO. The first two sentences also appear redundant.

Suggesting:

"
NVDA provides many configuration parameters that can be changed.
The settings dialog presents a list with several configuration categories to 
choose from.
When you select a category, all of the settings related to it will be shown in 
the dialog.
"

I will include that proposed text in the PR.
