### ISSUE TITLE
Support the Narrator Excel extension (NarratorExtension – Excel) for customizable announcements of content

### ISSUE THREAD

**Issue by tmthywynn8** [nvaccess/nvda#14921]
### Is your feature request related to a problem? Please describe.

Apart from cell coordinates and headers, the customizability of Excel's reading order cannot be changed. If users can further customize the amount of output they wish, such as swapping name and value announcements.

### Describe the solution you'd like

According to [this Microsoft support article][1], new insider builds of Windows 11 and Office 365 will have these announcements in Narrator. I have no idea how this works, but presumably the announcements and/or enhanced attribute information will be sent via UIA. If attributes are sent via the extension, then NVDA can allow for more customizability (maybe in a settings category. If announcements are hard-coded with UIA, then maybe NVDA can manage its customizability just as Narrator has commands to do the same.

### Describe alternatives you've considered

See above.

### Additional context

Having customizable speech/braille output for the dense information given in Excel can be useful, though there maybe a cost in the amount of options users can customize, hence the reason for a feature request. It is up to developers and users to determine the viability/usefulness of such customizations.

[1]: https://sway.office.com/A24LjOo2uV8kUo3a

**Comment by seanbudd** [comment]
This is an extension for Narrator and Excel. This seems unrelated to NVDA. If there are specific features for Excel interaction you would like, please open an new issue detailing the features you want.
