### ISSUE TITLE
Clarify "applications key" and how to access the context menu in the user guide

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#14929]
### Is your feature request related to a problem? Please describe.

Following a query from a user about accessing the context menu on a keyboard without an applications key, it occured to me we should perhaps clarify it in the user guide.

### Describe the solution you'd like

In section 4.5: The NVDA menu, the applications key gets mentioned for the first time (in the context of explaining how to open the NVDA menu via the notification area shortcut as an alternate to using NVDA+n).  In that instruction, we note: "press the applications key located next to the right control key on most keyboards. "  It would be worth following this with a short sentence to say "On a keyboard without an applications key, press shift+f10".

### Describe alternatives you've considered

Although a purely Windows key (anyone without a screen reader running can use the aplications key or shift+f10 to open the context menu), it is worth noting both the key (as it currently is) and the alternative shift+f10 in the user guide because:
a) It is used in accessing the NVDA menu in that way, and
b) those on alternate keyboards (Apple users, or those with new compact keyboards) may not be familiar with the shift+f10 alternative when you don't have an applications key.
c) new users may not be familiar with the term "applications key".  I have also heard it called the "menu key" or the "context menu key".

**Comment by Brian1Gaff** [comment]
Maybe I am getting the wrong end of the stick here, but the applications 
key, or its emulation of shift/f10 is one of the most used keys to get at 
information and contextual option menues in most versions of Windows.
 Obviously, though, there are users who just never have used it, I suppose.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "Quentin Christensen" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Tuesday, May 16, 2023 1:46 AM
Subject: [nvaccess/nvda] Clarify "applications key" and how to access the 
context menu in the user guide (Issue #14929)

**Comment by XLTechie** [comment]
> Maybe I am getting the wrong end of the stick here, but the applications
> key, or its emulation of shift/f10 is one of the most used keys to get at
> information and contextual option menus in most versions of Windows.
> Obviously, though, there are users who just never have used it, I suppose.

I agree. And yet, just today, I had to tell someone who has been using Windows 
for ten years or more, what and where it was. And I know for a fact that he has 
used context menus many times.
I don't know what he was trained to call it, but it evidently wasn't that.

**Comment by mwhapples** [comment]
I agree with the proposed request. Some keyboards simply do not have the applications key so the shift+f10 could be useful for those users, even if they know the name of the applications key. I have always known it as the applications key, but I can imagine many not knowing the name for it or having another name for it.

**Comment by XLTechie** [comment]
@Qchristensen While the section of the manual does say that, it only says so 
because that is the keyboard equivalent of right-clicking.

However, wouldn't it be easier, practically, to just tell the user to press 
enter on "NVDA" in this situation?

**Comment by cary-rowen** [comment]
cc @Qchristensen @XLTechie 
I don't think Shift+F10 has the same effect as the Application key at all, Although most of the time their functions are the same.
We have defined the following keymaps in the Simplified Chinese localized gestures.ini.
`kb:applications = kb:'+nvda` 
This mapping allows the user to get the real Application key.
Since many laptops don't have this key, I think the above keymap should be generalized to NVDA core.

**Comment by XLTechie** [comment]
@cary-rowen I'm not sure that Microsoft would agree with you.
https://learn.microsoft.com/en-us/windows/win32/menurc/wm-contextmenu

"""
Notifies a window that the user desires a context menu to appear. The user may 
have clicked the right mouse button (right-clicked) in the window, pressed 
Shift+F10 or pressed the applications key (context menu key) available on some 
keyboards.
"""

**Comment by XLTechie** [comment]
> I don't think Shift+F10 has the same effect as the Application key at all, Although most of the time their functions are the same.

In the past, I think it may have been possible that Shift+F10 was the same as 
Shift+Applications (that is: extended options, such as "Copy as path"), but that 
was never different in every circumstance.

In latest Windows 10 (22H2), I've been unable to find a difference, although I 
can't say I have made an in-depth study.

> We have defined the following keymaps in the Simplified Chinese localized gestures.ini.
> kb:applications = kb:'+nvda
> This mapping allows the user to get the real Application key.

What do you find different between this gesture, and Shift+F10? And in what 
circumstances?

**Comment by cary-rowen** [comment]
Although Microsoft's documentation recommends using Shift+f10 many times, I can easily find a counter-example that shows that Shift+f10 does not replace the Application key.
## step:
1. Open Chrome
2. Press Alt+F,B to go to bookmark menu.
3. Find a bookmark at random, try to press Shift+F10
4. Repeat steps 1 and 2, find a bookmark at random, and press the Application key

## Actual performance
Execute step 3 and the menu is not opened.
However performing step 4 the menu can be opened.

**Comment by cary-rowen** [comment]
The simplest, in Windows Explorer, the effects of Shift+F10 and the Application key are also different.
Shift+Application is the same as Shift+F10.

You can try the following keys on the icons on the desktop, and observe the pop-up menu:
* Application
* Shift+F10
* Shift+Application

**Comment by cary-rowen** [comment]
@XLTechie 
Did you notice my comment above?
Does the wording here affect #14936?

**Comment by XLTechie** [comment]
@cary-rowen yes, but this is by request of NV Access. I was expecting 
@michaelDCurran, or especially @Qchristensen to respond.

That said, as an alternative for reaching the system tray icon of NVDA (that is: 
the specific use case that is being used to imply the general use case), 
Shift+F10 and Applications (and Right-click) are identical in effect.

**Comment by cary-rowen** [comment]
> That said, as an alternative for reaching the system tray icon of NVDA (that is: the specific use case that is being used to imply the general use case), Shift+F10 and Applications (and Right-click) are identical in effect.

Yes, I think it's ok for this specific use case.

Thanks for your work.
