### ISSUE TITLE
After Windows Update KB5025221, Web content is no longer accessible to NVDA in Tor Browser or Firefox ESR built with mingw

### ISSUE THREAD

**Issue by malthej** [nvaccess/nvda#14935]
After applying the KB5025221 update, web content in the Tor Browser and Firefox ESR built with mingw is no longer read properly by NVDA.
I also filed an issue on TorBrowser's bug tracker [here](https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41729) but was advised to file an issue with NVDA as well on the users list.
### Steps to reproduce:
1. Open Tor Browser and make sure an external web page, not an internal firefox-related tab, such as about:config is loaded.
2. Try to read the web content in browse mode with NVDA
3. NVDA will not react, but will allow you to tab between element like using normal keyboard navigation. It will also, in some cases, allow you to toggle between focus and browse mode, but this will not make a difference.
### Actual behavior:

NVDA does not interact properly with web content, but only lets you tab between elements.
### Expected behavior:

NVDA should read web content as normal.
### NVDA logs, crash dumps and other attachments:
[nvda.log](https://github.com/nvaccess/nvda/files/11512152/nvda.log)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.1 (2023.1.0.27913)
#### Windows version:
Version	10.0.19045 Build 19045
#### Name and version of other software in use when reproducing the issue:
Tor Browser 12.0.6 (based on Mozilla Firefox 102.11.0esr) (64-bit)
#### Other information about your system:
Windows is in a virtual machine. However other people seem to have this issue as well.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by jmdaweb** [comment]
Hi,
Same problem using NVDA 2022.4 and/or Windows 11 22H2 build 22621.
Regards.

**Comment by AKJ** [comment]
Per the Tor Project issue, this bug was introduced because [Cache The World](https://wiki.mozilla.org/Accessibility/CacheTheWorld) is disabled in current Tor Browser builds.

Mine and other people's testing confirms that toggling accessibility.cache.enabled to true in about:config fixes the browser navigation issues, and Tor developers say it will be enabled in future Tor releases.

**Comment by Adriani90** [comment]
I close this issue as works for me since cache the world can be enabled and has been designed to solve such issues. Please push the Tor project to enable cache the world by default to solve this issue.
