### ISSUE TITLE
Using NVDA+spacebar to toggle browse mode with a YouTube video open pauses/plays the video

### ISSUE THREAD

**Issue by Luke-Robinett** [nvaccess/nvda#14947]
### Steps to reproduce:
1. Visit YouTube using Chrome and open a video.
2. Press NVDA+spacebar to toggle browse mode.

### Actual behavior:
The video plays or pauses.

### Expected behavior:
Browse mode should be toggled without the spacebar keystroke being passed to Chrome and the YouTube player.

### NVDA logs, crash dumps and other attachments:
n/a

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2022.4

#### Windows version:
10 Home

#### Name and version of other software in use when reproducing the issue:
Google Chrome v113

#### Other information about your system:
Intel i7 processor with 16gb of ram.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment]
Welcome,

We are unable to process this issue as it stands. We are unable to reproduce the issue

- Could you please confirm this is still an issue with 2023.1?
- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Kind Regards,
NV Access Software Developers

**Comment by Adriani90** [comment]
This issue is not reproducible in Chrome canary 125 with NVDA 2024.1 RC1. Closinga s works for me. If you are still reproducing this issue, please comment and provide the info requested and we can reopen.
