### ISSUE TITLE
from version 2023.1, i see some stranges about reporting rows and columns

### ISSUE THREAD

**Issue by amirmahdifard** [nvaccess/nvda#14945]
in 2022.4, i was getting the rows and columns announced difrently, and i felt that was bettar: for example, when i switch between windows with alt + tab, in 2022.4 it wasn't like this, but in 2023.1, it says the window name and then number of columns: like, teamtalk column 2: also, with 2022.4, in teamtalk qt client, in channels list, i was getting both rows and columns, but now in 2023.1, i'm only getting the rows: please tell me if this is really a problem that needs fixing, or a new setting has been added and i will need to modify that? thanks.
### Steps to reproduce:
compare the announcement of rows and columns with 2022.4 and 2023.1
### Actual behavior:
some rows and columns are not reported when they should and they are being announced strangely at other places
### Expected behavior:
like 2022.4, please fix the rows and columns announcements, or if i'm rong, please help me fix my  problem
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2023.1
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.2846
#### Name and version of other software in use when reproducing the issue:
i'm not sure really of other apps, but teamtalk qt client for now can show you the difrence
#### Other information about your system:
not sure
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2022.4 works fine
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by XLTechie** [comment]
Since not all of us use teamtalk (maybe none of us do), can you test with 
websites with tables, and MS Word with tables, and let us know if the same 
strange things happen there?

Or is it only with QT applications?

**Comment by CyrilleB79** [comment]
Hi @amirmahdifard 

In document formatting setting (NVDA+control+D), what is the value of the option "Headers"? It should be put on "Rows and columns".

**Comment by seanbudd** [comment]
Have you tested with 2022.4 and your current version of TeamTalk? are you sure TeamTalk hasn't changed?

Can you confirm if this is an issue with any other website or application?

**Comment by seanbudd** [comment]
Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

**Comment by amirmahdifard** [comment]
@seanbudd i'm sorry, but how can i show you this bug with log? it isbnot a crash or anything, and i don't beleave the log could do any help  on this

**Comment by seanbudd** [comment]
You follow the steps to reproduce, then send us the NVDA log. If you are concerned about privacy, you can send the log to info@nvaccess.org

The log file helps us with debugging, whether or not NVDA crashed is not relevant.

**Comment by CyrilleB79** [comment]
Hello

I can reproduce what is described here with Alt+Tab (in the task switcher), or better with Windows+Tab.

What happens in 2023.1 is that, in the task switcher, the icons are positioned in a grid (or table). If enabled cell coordinates are reported when the cursor (or selected icon) is moved. The reporting is as follows:
- When the first move occurs, row and column are reported since they have not been reported before.
- then, for the next move, only what changes is reported, that is:
  - if the move occurs in the same row, only the column changes and is reported
  - if the move is in a different row (and column), both rows and columns are reported
This is coherent with general table navigation in NVDA. On the contrary, in 2022.4, row and column were always reported, no matter if they change or not.

However, I do not know how and why this has changed between 2022.4 and 2023.1.

A more obvious way to see what happens is to use Windows+Tab and play with Tab, Shift+Tab but overall also arrows. If you still want to test with Alt+Tab, you can also use arrows as follow:
- Press Alt+Tab
- Maintain Alt pressed
- Use arrows
- Release Alt when you're done.

@amirmahdifard now that you have an explanation on why rows or columns are sometimes reported and sometimes not, is the new behaviour still a problem for you? If yes, can you explain why? This would help to decide if the old behaviour need to be restored (if possible) or not.

**Comment by amirmahdifard** [comment]
@CyrilleB79 yes! finally someone understood what i mean to say! and yes, please restore like 2024 so allways both of them has been reported because that is more ok

**Comment by CyrilleB79** [comment]
I wrote:
> is the new behaviour still a problem for you? If yes, can you explain why? This would help to decide if the old behaviour need to be restored (if possible) or not.

And you answer:
> and yes, please restore like 2024 so allways both of them has been reported because that is more ok

Sorry @amirmahdifard , but "because that is more ok" does not seem an explanation likely to convince someone to look at this issue further, to understand why it is an issue and maybe fix it (if possible and desirable).

Please describe why this new behaviour is a problem for you, illustrating with an example situation. Personally, I feel that repeating the row information when it does not change increase the verbosity without giving new unknown information, which is not desirable.

Note that if you only use Alt+Tab or Alt+Shift+Tab in the task switcher, you may not be interested by the row/column information at all. In this case, you may also be interested in creating a profile for explorer.exe in which you disable table heading reporting.

Let us know with more details why you disagree with me so that we can understand better your situation.

**Comment by cary-rowen** [comment]
The behavior of NVDA-2022.4 is redundant and inefficient to me:
in 2022.4, row and column were always reported, no matter if they change or not. 
I think the current behavior - only reporting changed information is fine, We only care about those important information in every step of operation, don't we?

**Comment by amirmahdifard** [comment]
@CyrilleB79 but it seems this one is a bug, because rows only reported when they gets changed, but colloms reported everytime i think, but i'm not sure: also, i like them like 2024 because i could always here wich rows and colloms i'm in, but now i only hear them when they gets changed, wich is not a good thing for me to work with, that's what i can think right now.

**Comment by amirmahdifard** [comment]
@seanbudd please remove the blocked and needs info lable from this issue now, i beleave now there is enough  information here for a one who is willing to fix this.

**Comment by CyrilleB79** [comment]
> @CyrilleB79 but it seems this one is a bug, because rows only reported when they gets changed, but colloms reported everytime i think, but i'm not sure:

No, that not the case: on my side, rows are reported when they get changed and columns are reported when they get changed. The thing is that when you press Alt+Tab many times, the selected item moves on the first row and when it reach the end, goes to the beginning of the second row, then move further on the second row, etc. The consequence is that the column change each time you press Alt+Tab, whereas the row change only when moving from the end of a row to the beginning of the next one, i.e. once in four or five presses.
So on my side, it is not a bug.

Also, have you tried to use Alt+Arrows after the first press of Alt+Tab? Is it less confusing for you?

If you do not experience what I describe, please provide a log.

> also, i like them like 2024 because i could always here wich rows and colloms i'm in, but now i only hear them when they gets changed, wich is not a good thing for me to work with, that's what i can think right now.

OK, I understand that you would like to have row and column reported for each move, no mater if they change or not. Then, the question still open is: have you the same issue when navigating in table on the web with alt+control+arrows? On my side, rows/columns are reported only if they change, i.e. rows are reported when moving in column and vice versa. Is it a problem for you on the web?

**Comment by amirmahdifard** [comment]
@CyrilleB79 yes it is a problem for me in the web, because i don't have them announced anymore: and yes: i can confurm what you say, and both of them are only reported when they got changed. so it is not a bug

**Comment by amirmahdifard** [comment]
hello everyone, i'm now closing this because after i gave information that i kknow about this, still my issue has the blocked needs info label and i don't know what to do next, i'm just getting so much confuse , i gues opening an issue for nvda to fix is too hard for people like me because enough informations are not given to me by anyone thanks

**Comment by seanbudd** [comment]
Hi @amirmahdifard you were asked several times for a log file. There may also still be open questions from Cyrille, but the label is because at a minimum we need a log file.

**Comment by seanbudd** [comment]
On further reading, it seems that the log is unnecessary if this is not a bug. It seems like this is an intended change of behaviour and the change is popular. I'd encourage a GitHub discussion or leaving the issue open to see if anyone else prefers the old behaviour.

**Comment by seanbudd** [comment]
On further reading, it seems that the log is unnecessary if this is not a bug. It seems like this is an intended change of behaviour and the change is popular. I'd encourage a GitHub discussion or leaving the issue open to see if anyone else prefers the old behaviour.

**Comment by amirmahdifard** [comment]
i don't know if the log file is still needed because now we completely know what has been gon with this issue, and i said i like 2024 is bettar

**Comment by XLTechie** [comment]
The reason to leave the issue open, is that if enough other people like the way 
things were before, maybe they will comment here and a change will eventually be 
considered.

Have you considered asking someone to write an add-on to restore the old 
behavior for you?

**Comment by amirmahdifard** [comment]
@seanbudd @CyrilleB79 @XLTechie to be clear, i'm now stressed and scared to talk to nvda developers because once i was excited about a suggestion i gave for nvda and i wanted that to happen and i didn't ment anything bad, but i got banned for 30 days, so after that i'm scared and i don't know how to show my excitement and my interest and i don't know how can i ask a developer to open a pull request  and adress my issue with out getting banned from the project:  i guess this project would be only good for me if i was a developer my self so i could implement my own suggestions as i think 2 of my suggestions in here are easy to implement

**Comment by cary-rowen** [comment]
@amirmahdifard wrote:
> i didn't ment anything bad, but i got banned for 30 days


This confuses me, NV Access didn't ban you, you can comment anytime.

BTW, I don't think an open source project will break most people's preferences in order to satisfy one person's preferences.

**Comment by XLTechie** [comment]
@cary-rowen wrote:
> This confuses me, NV Access didn't ban you, you can comment anytime.

But he was banned for 30 days either earlier this year or late last year, for 
repeatedly spamming developers with requests to immediately implement one of his 
ideas.

I would call it an over-abundance of enthusiasm, combined with frustration at 
the development speed of NVDA, not that anything was wrong with the idea itself, 
which was a good one IMO.

Sadly, having to hear about it so frequently, made those of us who might have 
done it, lose interest in pursuing it at the time.
