### ISSUE TITLE
Unicode characters not interpreted

### ISSUE THREAD

**Issue by WBerndorfer** [nvaccess/nvda#14951]
Version NVDA 2022-3
There is a range of Unicode characters around the contained name “document” that is not interpreted by NVDA:

&amp;#128462; / &amp;#x1F5CE; (Document), 
&amp;#128459; (empty document),
&amp;#128441; (document with text)
&amp;#128442; (document with text and image),
&amp;#128443; (document with image) 
...
Please add the name in the relevant library and forward this issue respectively to translators.

**Comment by seanbudd** [comment]
Welcome @WBerndorfer ,

We are unable to process this issue as it stands.
Please fill out the issue template fully.

Kind Regards,
NV Access Software Developers

**Comment by WBerndorfer** [comment]
[nvda_unicode.txt](https://github.com/nvaccess/nvda/files/11642172/nvda_unicode.txt)

This is my testfile. Just change .txt to .html

**Comment by seanbudd** [comment]
@WBerndorfer please fill out the issue template.
