### ISSUE TITLE
NVDA freezes in Excel when pressing tab after editing cell contents

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#14964]
### Steps to reproduce:

In advanced options, using UIA in Excel is not enabled.

1. Open an excel sheet
2. Edit some cells. Type text into the cell, remove some text, etc
3. Move to the next cell either by pressing right arrow or tab
4. Do this for a few cells in the worksheet, as this freeze doesn't happen immediately (after a few mins)

### Actual behavior:

NVDA freezes after a couple of minutes to the point that no speech happens when in Excel, and speech only comes back when minizing to the Desktop. Alt tabbing into Excel freezes NVDA again, making it impossible to continue working on the sheet. 

Restarting NVDA does not fix this as the freeze happens again when tabbing to Excel. The only way to fix this is to close and restart Excel, which is problematic if you can't interact with it to save your work.

### Expected behavior:

This should not be happening, as using Excel is practically unuseable with this issue.

### NVDA logs, crash dumps and other attachments:

```
INFO - watchdog.waitForFreezeRecovery (21:20:30.669) - watchdog (20068):
Starting freeze recovery after 1.515153599990299 seconds.
INFO - watchdog.waitForFreezeRecovery (21:20:31.354) - watchdog (20068):
Recovered from freeze after 2.200841899990337 seconds.
ERROR - eventHandler.executeEvent (21:20:31.319) - MainThread (8624):
error executing event: typedCharacter on <NVDAObjects.Dynamic_CellEditEditableTextWithAutoSelectDetectionUIA object at 0x011CB290> with extra args of {'ch': '\t'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 110, in next
  File "NVDAObjects\behaviors.pyc", line 271, in event_typedCharacter
  File "NVDAObjects\__init__.pyc", line 1181, in event_typedCharacter
  File "speech\speech.pyc", line 1131, in speakTypedCharacters
  File "api.pyc", line 337, in isTypingProtected
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 1059, in _get_isProtected
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1639, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 987, in _getUIACacheablePropertyValue
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2146233083, None, (None, None, None, 0, None))
INFO - watchdog.waitForFreezeRecovery (21:20:33.056) - watchdog (20068):
Starting freeze recovery after 1.5299417999922298 seconds.
INFO - watchdog.waitForFreezeRecovery (21:20:33.554) - watchdog (20068):
Recovered from freeze after 2.0274443999805953 seconds.
INFO - watchdog.waitForFreezeRecovery (21:20:42.217) - watchdog (20068):
Starting freeze recovery after 6.614179199998034 seconds.
INFO - watchdog.waitForFreezeRecovery (21:20:45.845) - watchdog (20068):
Recovered from freeze after 10.242056400020374 seconds.
INFO - watchdog.waitForFreezeRecovery (21:20:47.332) - watchdog (20068):
Starting freeze recovery after 1.5200874999864027 seconds.
INFO - watchdog.waitForFreezeRecovery (21:20:47.896) - watchdog (20068):
Recovered from freeze after 2.0837520999775734 seconds.
INFO - watchdog.waitForFreezeRecovery (21:20:48.354) - watchdog (20068):
Starting freeze recovery after 0.5004182999837212 seconds.
INFO - watchdog.waitForFreezeRecovery (21:20:48.415) - watchdog (20068):
Recovered from freeze after 0.5617695999972057 seconds.
INFO - watchdog.waitForFreezeRecovery (21:20:48.916) - watchdog (20068):
Starting freeze recovery after 0.50050199998077 seconds.
INFO - watchdog.waitForFreezeRecovery (21:20:54.796) - watchdog (20068):
Recovered from freeze after 6.3801678000018 seconds.
INFO - watchdog.waitForFreezeRecovery (21:21:05.319) - watchdog (20068):
Starting freeze recovery after 10.183007399988128 seconds.
INFO - watchdog.waitForFreezeRecovery (21:21:07.813) - watchdog (20068):
Recovered from freeze after 12.677102699992247 seconds.
```

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-28231,648a5d34 (2023.2.0.28231)

#### Windows version:
Windows 10 22H2

#### Name and version of other software in use when reproducing the issue:
Microsoft® Excel® for Microsoft 365 MSO (Version 2304 Build 16.0.16327.20200) 64-bit

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

**Comment by seanbudd** [comment]
We are unable to process this issue as it stands.
We need a full log file.
Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.
You can upload the log as an attachment rather than copy pasting a snippet.
Alternatively, email it to info@nvaccess.org

**Comment by leonardder** [comment]
@Neurrone Could you please provide a status update for this issue with a current Alpha build of NVDA?

**Comment by Neurrone** [comment]
I haven't seen this happening recently, so will close this.
