### ISSUE TITLE
piper tts pauses after each line

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#14963]
I noticed the latest piper tts addon pauses at the end of each line. It does not read complete sentences or paragraphs with a nice flow to its reading, can this be fixed? thanks.

**Comment by seanbudd** [comment]
We do not maintain NVDA add-ons. Please provide feedback to the authors of the add-on.

**Comment by seanbudd** [comment]
https://github.com/rhasspy/piper

**Comment by vallabhsumanth1** [comment]
Why piper TTS model usually reduces the bytes in the end?
