### ISSUE TITLE
Implement tab bar to settings dialog

### ISSUE THREAD

**Issue by CoBC** [nvaccess/nvda#14972]
### Is your feature request related to a problem? Please describe.
In the new addon store, the dialog use a tab bar. In the settings dialog, it's still a list box which is use for category selection.

### Describe the solution you'd like
TO uniformize interface, and also because tab bar is more standard on all apps, I suggest to replace categories listbox by a tab bar in the settings dialog.

**Comment by CoBC** [comment]
For example in the Discord app you have 28 tabs. It's a web app but 
however it use a tab bar as well.

**Comment by CyrilleB79** [comment]
In add-on store, the tab list is horizontal. Visually more than 6 or 7 tebs would not fit anymore in the window. So IMO using an horizontal tab list is not suitable.

If the tab list is vertical with items still written horizontally), the layout would be quite similar to the list. IMO this new design does not bring anything interesting.

Also, the settings dialog with a category list and a panel are common in windows settings as well as in other application such as Office settings

**Comment by CoBC** [comment]
For me, a big benefit could be the ability to use CTRL-Tab to switch tab 
instead, currently if we just want to change an option and than go to 
another category we have to press tab a lot of time to go to categories 
list.

**Comment by CyrilleB79** [comment]
> For me, a big benefit could be the ability to use CTRL-Tab to switch tab instead, currently if we just want to change an option and than go to another category we have to press tab a lot of time to go to categories list.

Ctrl+Tab is actually already supported to change category in the settings dialog.

Not sure that it is documented in 2023.1's User Guide. But in recent alpha, it has been documented as follows:
> From anywhere in the dialog, you may also move forward one category by pressing ``ctrl+tab``, or back one category by pressing ``shift+ctrl+tab``.

Any other reason why you would prefer tabs?

**Comment by seanbudd** [comment]
Closing this as won't fix
