### ISSUE TITLE
Add-on Store: Open add-on help in ui.browseableMessage

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#14989]
### Is your feature request related to a problem? Please describe.

When a user requests help for an installed add-on, it isn't obvious that he will be taken to a web page.
When help is finished, it isn't obvious how to get back to the store, or that the store is even still open.

### Describe the solution you'd like

If help was to be opened in a `ui.browseableMessage`, it would not interact with any currently open browser that the user may have running. Therefore when closed, it should return the user to the store interface.

Further, the escape key will work as a reasonable go-back mechanism.

### Additional context

I don't propose this for the Homepage option, because in that case it is apparent that a website will be opened based on the name.

**Comment by cary-rowen** [comment]
it's a good idea,
Sometimes opening an html file asks which browser to use, making the steps more cumbersome and unnecessary.

**Comment by nvdaes** [comment]
This would make necessary to verify that links included in help can be opened properly through the ui.browseableMessage, since HTML documentation may contain links to other websites, for example if the add-on is created for an app module.

**Comment by seanbudd** [comment]
Closing this as unplanned

**Comment by CyrilleB79** [comment]
@seanbudd, any explanation why NVAccess has not accepted this request? Just for completeness and curiosity actually... Thanks.

**Comment by seanbudd** [comment]
We feel it's an inappropriate usage of the dialog, and the current UX is more typical
