### ISSUE TITLE
Add-on Store: Make talking about add-on submission easier, by providing a shortlink to the submission form

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#14993]
### Is your feature request related to a problem? Please describe.

Any time one wishes to submit an add-on to the store, one must go to:

```
https://github.com/nvaccess/addon-datastore/issues/new?assignees=nvaccess&labels=autoSubmissionFromIssue&template=registerAddon.yml&title=%5BSubmit+add-on%5D%3A+
```

While all that get info may not be necessary, enough of it is to make manually typing this undesirable.

Since various people often need to post that URL on mailing lists and the like, publish it in documents, etc:

### Describe the solution you'd like

I'd like NV Access to provide a shortlink directly to that long URL. Something along the lines of:

```
https://nvaccess.org/submitaddon
```

that is easily memorable, brief, not error-prone, and convenient to type manually rather than having to look it up in a notes file and copy/paste.

### Additional context

I just had to open a notes file, search for "addon-data", copy the line, and paste it into an email for someone on a mailing list a few minutes ago.

I have a URL-shortened version for my own use, but don't think it's right to publish that publicly since it's not controlled by NV Access.

**Comment by nvdaes** [comment]
I"m not against this, but I think that it"s better to provide a link to the submission guide, where the provided url doesn"t containt title parameter, instead of informing people, directly, about the issue form.

**Comment by seanbudd** [comment]
Agreed, the submission guide should be linked, not the issue form.

I think the either of the following links are more appropriate than directly linking to the issue form:
- https://github.com/nvaccess/addon-datastore/
- https://github.com/nvaccess/addon-datastore/blob/master/docs/submitters/submissionGuide.md

Does this still warrant a short url?
Can users who need this just use a url shortening service or similar?

**Comment by XLTechie** [comment]
@seanbudd wrote:

>  *  https://github.com/nvaccess/addon-datastore/blob/master/docs/submitters/submissionGuide.md

I'm not likely to type that out by hand in response to a question.

> Can users who need this just use a url shortening service?

Of course. But I'm surprised NV Access would prefer that, as stated at the end 
of my initial comment.
