### ISSUE TITLE
Can't install add-ons from Windows Explorer

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#14994]
CC @seanbudd 

### Steps to reproduce:
1. Download an add-on from an external source
2. Open the add-on from explorer

### Actual behavior:
```
ERROR - unhandled exception (08:45:34.803) - MainThread (12336):
Traceback (most recent call last):
  File "wx\core.pyc", line 3407, in <lambda>
  File "gui\addonGui.pyc", line 578, in handleRemoteAddonInstall
  File "gui\addonGui.pyc", line 482, in installAddon
ModuleNotFoundError: No module named '_addonStoreGui'
```

### Expected behavior:
Add-on is offered to install.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-28398,7d716373

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Did work before the add-on store was merged.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

**Comment by leonardder** [comment]
This also happens when trying to install from the 'Install from external source' button.

**Comment by nvdaes** [comment]
in case this helps, Í can reproduce this with most add-ons, but not withPiper Neural. I don"t know if the available version shared in Inprocess blog is the same available in the repo, but I downloaded taking that reference, and the add-on is installed pressing the Install from external source. I don"t know if the folder structure of add-ons is affecting this.

**Comment by Brian1Gaff** [comment]
I usually do not have the nvda as the default action for the add ons. So I 
can go too open with, and look at the zip contents or say then open with 
nvda, and do that. I'm assuming your comments are for the alpha builds, 
which I don't have right now though. Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by mzanm** [comment]
I'm encountering this issue with incompatible add-ons only; other add-ons install with no issues for me.

**Comment by cary-rowen** [comment]
From the logs, it seems that it is not the same problem as #14991.

**Comment by leonardder** [comment]
Good catch, the add-on I opened indeed turned out to be incompatible.
