### ISSUE TITLE
New Teams Is inaccessible

### ISSUE THREAD

**Issue by munawarb** [nvaccess/nvda#15001]
### Steps to reproduce:
1. Check the box that enables the new Teams preview.
2. Observe that the new Teams is inaccessible.
### Actual behavior:

NVDA announces "Teams Pane" in the new Teams. Additionally, no keys such as CTRL+1 or CTRL+2 report any feedback. Further, NVDA says nothing when pressing TAB.

### Expected behavior:

New Teams should be accessible. I suspect this versionw ill be the default once it's ready, at which point there will be no "revert" option.

#### Windows version:
Windows 11

**Comment by seanbudd** [comment]
This is very likely a problem with the implementation of the application/website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers
