### ISSUE TITLE
NVDA add-ons store: UI: Partial incompatibility with Windows High Contrast mode

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#15007]
### Steps to reproduce:
1. Enable high-contrast mode in Windows 11, by doing the following:
1.1. Open Windows Settings (Windows+I).
1.2. Go to Accessibility ➡ Contrast themes.
1.3. From the "Contrast themes" combo-box, select any dark theme.
1.4. Activate the "Apply" button.
2. Update to the latest alpha version of NVDA, that contains the add-ons store.
3. Launch NVDA.
4. Open the NVDA menu and go to Tools -> Add-on store and activate it.
5. Select an add-on from the list (doesn't matter from which tab).
6. Observe the background color of the panel on the right side of the "Add-on Store" window.
7. Observe the color of the text in the field "Other details".

### Actual behavior:
- The background color of the panel on the right side of the "Add-on Store" window is white.
- The text color in the "Other details" field is black.

### Expected behavior:
- The background color of the panel on the right side of the "Add-on Store" window obeys the Windows color settings.
- The text color in the "Other details" field obeys the Windows color settings.

### NVDA logs, crash dumps and other attachments:
I can provide screenshots, if necessary.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA alpha-28430,3920fa58

#### Windows version:
Windows 11 Pro version 22H2 (build 22621.1848), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".

#### Other information about your system:
Wimdows High Contrast mode active, as explained in the "steps to reproduce" section above.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This is an issue in the addons store since it appeared in the alpha versions of NVDA.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
This is a GUI issue and it is not related to unregistered libraries.

**Comment by seanbudd** [comment]
Yes - screenshots would be helpful to have on the issue thanks

**Comment by k-kolev1985** [comment]
OK, here is a screenshot of the add-ons store window with the Windows High Contrast black theme active and the color issues with the right side of the window are plainly visible.
![2023-06-16_08-55-14](https://github.com/nvaccess/nvda/assets/4395934/c2883b27-1740-4d04-9f1b-9baffb8c5349)
