### ISSUE TITLE
NVDA add-ons store: UI: "Description" and "other details" fields do not have visual labels

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#15011]
### Steps to reproduce:
1. Update to the latest alpha version of NVDA, that contains the add-ons store.
2. Launch NVDA.
3. Open the NVDA menu and go to Tools -> Add-on store and activate it.
4. Select an add-on from the list (doesn't matter from which tab).
5. Observe the area above the "Description" field on the right side of the "Add-on Store" window.
7. Observe the area above the "Other details" field on the right side of the "Add-on Store" window..

### Actual behavior:
- There is no visual label for the "Description" field.
- There is no visual label for the "Other details" field.

### Expected behavior:
- There is a visual label for the "Description" field.
- There is a visual label for the "Other details" field.

### NVDA logs, crash dumps and other attachments:
I can provide screenshots, if necessary.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA alpha-28430,3920fa58

#### Windows version:
Windows 11 Pro version 22H2 (build 22621.1848), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This is an issue in the addons store since it appeared in the alpha versions of NVDA.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
This is a GUI issue and it is not related to unregistered libraries.

**Comment by CyrilleB79** [comment]
+1

Visual labels may help low vision user and sighted users to communicate with blind people. If I say to a sighted person "Tab to the Other details fields", this person may not clearly identify the field.

Also, if we use a visual label (e.g. `wx.StaticText`), #15010 may be easily solved. IMO, at least the controls which have an accelerator key should have a visual label to present it.

**Comment by CyrilleB79** [comment]
@k-kolev1985, PR #15103 creates a visible label for controls having a shortcut key, i.e. the add-on list and the "Other details" field, but not for the description field.As discussed in https://github.com/nvaccess/nvda/pull/15103#pullrequestreview-1515716175, there is no need to have "Description" field visible.

Thus, do you agree that merging it would close the current issue? If not, please explain why in details; thanks.

**Comment by k-kolev1985** [comment]
@CyrilleB79 
Well, I think that all controls (incl. text fields) should have visual labels - for consistency, if nothing else. 
Not only that, but in my observations, visual labels for controls are a standard for GUI. 
Also, visual labels help sighted and partially sighted (like me) to better distinguish the controls. Remember, not only fully blind people use NVDA, after all.

**Comment by seanbudd** [comment]
I don't think this is typical - there are many instances where screen readers provide information to replace something inherently obvious to sighted folks.
I believe the long description of the add-on is one of these cases.
