### ISSUE TITLE
add-on store GUI: The "Include incompatible add-ons" checkbox is not aligned with the component to its left, but rather it is affixed to the top.

### ISSUE THREAD

**Issue by hwf1324** [nvaccess/nvda#15018]
### Describe the solution you'd like

The "Include incompatible add-ons" checkbox is not aligned with the component to its left, but rather it is affixed to the top.

**Comment by seanbudd** [comment]
You can always minimize the add-on store after opening it. Due to the amount of content in the add-on store dialog, I strongly believe it should be maximised by default.

**Comment by seanbudd** [comment]
>The height of the detail information panel on the right-hand side should match that of the add-on list on the left-hand side, which may potentially address issue #15011 simultaneously.

Could you explain this a bit more? The left and right panel height currently matches. It is intentional that the tabbing interface is part of the left panel, and not across both panel.

**Comment by hwf1324** [comment]
> Could you explain this a bit more? The left and right panel height currently matches. It is intentional that the tabbing interface is part of the left panel, and not across both panel.

Sorry, I misunderstood. These two tags should be added inside the right HTML panel.

**Comment by seanbudd** [comment]
>Sorry, I misunderstood. These two tags should be added inside the right HTML panel.

I still don't understand - I assume by tags you mean those referenced in https://github.com/nvaccess/nvda/issues/15011. I still don't understand what this has to do with height of the panels.

**Comment by hwf1324** [comment]
Sorry, I was the one who didn't give an affirmative answer. You are right, I started to think that the "description:" label is outside the HTML panel, but now I don't think so anymore.

I will modify Issue's description so that it focuses only on checkbox issues.

**Comment by hwf1324** [comment]
The problem seems to be caused by a difference between `addLabeledControl` and `addItem`.
Because `addLabeledControl` is based on `associateElements`, `associateElements` creates a `BoxSizer` that wraps both controls, while `addItem` does not.

And there is a lot more `Spacer` here because it only hides the `CheckBox` when switching tabs.

@CyrilleB79 , do you have any ideas?
