### ISSUE TITLE
Add-on Store: disabled add-ons should be checked for updates

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#15029]
### Steps to reproduce:

1. Disable an add-on which has an update available.
2. Restart NVDA.
3. Check for available updates.

### Actual behavior:

The add-on isn't listed as having any updates.

### Expected behavior:

Even though the add-on is disabled, if it has an update in the store, that update should be available to install.

### Reasoning:

If a version of an add-on is broken with respect to current NVDA, and it must be disabled in order to access the store, there is no way to acquire an updated version even if the store has one, short of removing the add-on, or going external.

Alternate: a version of an add-on currently does something I don't like. The newly released version fixes the issue. I don't want to enable it until I upgrade. I can't currently upgrade without enabling.

Example:
I currently have an external version (dev, though that doesn't matter) of an add-on installed.

Something about the latest alpha of NVDA doesn't cooperate with that version, and it breaks the speech.speech.speak method.
There is a stable version with a higher version number available in the store.

Because the add-on is preventing the store (and many other things) in NVDA from working, I can't leave it enabled when checking for updates. However if I disable it, NVDA doesn't show any updates available. Nor does it show in the store's list of available add-ons, so obviously NVDA recognizes that these are the same add-on.

Installed, it is 23.1.0-dev6 (external).
The store currently includes 23.1.1 (stable) of this add-on.
No update is offered while the add-on is disabled.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

alpha-28447,cc222a06

#### Windows version:

10 Home 22H2

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by CyrilleB79** [comment]
Note that @joseph's Add-on Updater checks for disabled add-ons and reenables them if updated. A message first asks for confirmation.

@josephsl if you have time, maybe you can comment on this use case. Why add-ons are reenabled when updated? (technical limitation or UX optimization?) Any user complaining of the current behaviour?

Add-on Updater has proven to be satisfying over the years, so we should think twice before handling things differently.

**Comment by josephsl** [comment]
Hi,

When updating diabled add-ons, NVDA is responsible for removing the add-on from disabled add-ons list, causing the updated version to be enabled.

There is a separate issue that has popped up in recent weeks: in add-on store, cannot check for updates for add-ons forcefully enabled despite marked as incompatible. I'll raise a separate issue and will mention this one as the new issue will involve alpha snapshots.

Thanks.
