### ISSUE TITLE
Add-on store: add ability to manually refresh store data cache

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#15034]
Hi,

I propose 2023.3 milestone for this and the next feature request unless people feel this should be part of 2023.2:

### Introduction
NVDA 2023.2 includes a client to access add-on store hosted by NV Access. As part of this change, a caching mechanism is introduced to present avaialble add-ons and their updates, updated every few hours.

### Is your feature request related to a problem? Please describe.
Due to the caching mechanism, add-on updates may not be shown right after an add-on author publishes updates.

### Describe the solution you'd like
Add a control to add-on store client that will refresh the add-on store cache, thereby letting users see latest updates. The most likely method is a button added to updatable add-ons tab or additional tabs named "check for add-on updates" or similar wording that will refresh i.e. build an updated cache based on store data at that moment, updating the cache timestamp in the process (subsequet cache updates will happen a few hours later).

### Describe alternatives you've considered
Let users configure cache refresh interval (say, between one hour and six hours).

### Additional context
Add-ons such as Add-on Updater can offer latest updates on the fly as they do not use a cache.

Thanks.

**Comment by seanbudd** [comment]
I think a "refresh" button, next to the store install from external button, would be ideal. I think it's fine if it's available when any tab is selected.

**Comment by nvdaes** [comment]
Hi, I had though about this too, but i didn"t request it thinking that the cache may be created to preserve server sustainability, and NVDA itself offers updates each 24 hours and this is not configurable. but this issue is interesting since we may wonder if addonUpdater and add-ons which want to follow practices reccomended by NV Access should update without a predefined interval like 6 hours. Cheers.

**Comment by josephsl** [comment]
Hi,

As I'm going through some life changes, I might not be able to implement this, but am happy to mentor someone or help test the eventual implementation. Thanks.

**Comment by nvdaes** [comment]
If it"s needed, i.e., if nobody works on this after some weeks, I may try to do it requesting a pr review from @josephsl too.

**Comment by XLTechie** [comment]
Definitely support some implementation of this. Preferably in 2023.2 if it can 
be gotten there in time.

This one was just bothering me this morning with a bug fixing update to an 
add-on

I advocate for 2023.2 for the simple reason that we want as few pain points for 
users as possible out of the gate--head off those complaints before they even 
exist.
Much better to explain how to do a thing, than to say "it can't be done yet, but 
be patient".

**Comment by CyrilleB79** [comment]
I fully support a way to refresh this cache, i.e. from a user point of view, refresh the updatable add-on list. Adding a keyboard shortcut with F5 (as on webpages) would also be nice; or maybe alt+letter forbetter  discoverability on the "Refresh" button.

Sean writes:
> I think a "refresh" button, next to the store install from external button, would be ideal. I think it's fine if it's available when any tab is selected.

IMO, the refresh button on the available add-on list is confusing from a UX point of view: what does it refresh in this list? Is there an information stored in the cache displayed in this list? Or does it refresh the information in this list (e.g. add-on version if I have manually changed the manifest).
It would be better to have this button available only when the Updatable add-ons tab is selected. Or label the button with a text such as "Refresh add-on information from the server"... but it's quite ugly.

Actually, the user does not know of the cache so what is refreshed in the user experience?

**Comment by nvdaes** [comment]
Cyrille wrote: 

> Adding a keyboard shortcut with F5 (as on webpages) would also be nice; or maybe alt+letter forbetter discoverability on the "Refresh" button.

I'd prefer alt+letters since it's the mechanism used in other controls. For example, we can rename profiles but we don't use f2.

Cyrille wrote:

> IMO, the refresh button on the available add-on list is confusing from a UX point of view: what does it refresh in this list? Is there an information stored in the cache displayed in this list? 

I've released a dev version of emoticons and this doesn't appear in the available add-ons for now. Imo, refreshing the cache in the available tab should allow to discover the recently released version of this add-on. Fixme if I'm wrong.

**Comment by CyrilleB79** [comment]
I wrote:
> Sean writes:
> 
> > I think a "refresh" button, next to the store install from external button, would be ideal. I think it's fine if it's available when any tab is selected.
> 
> IMO, the refresh button on the available add-on list is confusing from a UX point of view: what does it refresh in this list? Is there an information stored in the cache displayed in this list? Or does it refresh the information in this list (e.g. add-on version if I have manually changed the manifest). It would be better to have this button available only when the Updatable add-ons tab is selected. Or label the button with a text such as "Refresh add-on information from the server"... but it's quite ugly.
> 
> Actually, the user does not know of the cache so what is refreshed in the user experience?

Sorry, my bad. I should have written:
IMO, the refresh button on the installed add-on list is confusing from a UX point of view
and
It would be better to have this button available only when the available or Updatable add-ons tab are selected.

**Comment by nvdaes** [comment]
Luke wrote:

> Definitely support some implementation of this. Preferably in 2023.2...

I stated that I'd wait for some weeks: this is triaged as p4. Anyway, I may start working on this in the next days, since it would be good to have this feature for NVDA 2023.2 and the PR needs to be reviewed/tested.

**Comment by XLTechie** [comment]
Thanks @nvdaes!

@seanbudd, I was wondering if it would be better to locally record the last store cache update 
time from the server.
Then, a low-impact http request could check the server and compare, to learn if 
there have been any updates.

There are also other ways of doing the same thing using metadata.

Then, whenever the store is opened, it could do that low-impact http request, 
and if the cache has been updated, it could automatically refresh it.

That avoids troubling the user with a refresh button, and avoids a user sitting 
there and hitting it a bunch of times "just in case".

It is a standard way of cache management in many client-server applications.

**Comment by nvdaes** [comment]
If the cache can be updated automatically, the button to do it woldn¡t be needed, as mentioned by Luke.
Otherwise, I can send a PR. For now I've just wrote 16 lines of code or so, and I'm testing locally.

**Comment by seanbudd** [comment]
>[@seanbudd](https://github.com/seanbudd), I was wondering if it would be better to locally record the last store cache update
time from the server.
Then, a low-impact http request could check the server and compare, to learn if
there have been any updates.

@XLTechie - I think we'd rather return the hash of the current commit.
We can create an endpoint to return the SHA of the transformed add-on views repo.

**Comment by XLTechie** [comment]
@seanbudd wrote:

> @XLTechie - I think we'd rather return the hash of the current commit.
> We can create an endpoint to return the SHA of the transformed add-on views repo.

Even better!

**Comment by seanbudd** [comment]
https://www.nvaccess.org/addonStore/cacheHash.json is live on production now: [documentation](https://github.com/nvaccess/addon-datastore/blob/master/docs/design/designOverview.md#get-cachehash)

**Comment by nvdaes** [comment]
Should I create a PR for this? In that case, I suppose that NVDA should fetch the hash whenever the store is opened, and, if differences are found, then the most recent value should be cached and all data cache should be refreshed; then the cache shouldn"t be restored each 6 hours anymore.

**Comment by seanbudd** [comment]
@nvdaes - yes that sounds ideal. Means we have no use for a refresh button, re-opening the browser will cover that.

**Comment by nvdaes** [comment]
gvreat, i will start working on this today.Enviado desde mi iPhoneEl 28 jun 2023, a las 2:39, Sean Budd ***@***.***> escribió:﻿
@nvdaes - yes that sounds ideal. Means we have no use for a refresh button, re-opening the browser will cover that.

**Comment by josephsl** [comment]
Hi all,

For reference, the "cache hash" method is now part of Add-on Updater 23.07, improving update check performance in the add-on.

Thanks.
