### ISSUE TITLE
Modify the add-on store title bar text

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#15042]
### Steps to reproduce:
* Open the add-on store
* Press NVDA+T
### Actual behavior:
NVDA reports:
"Add-on Store - All Installed add-ons"

### Expected behavior:
NVDA should report:
"Add-on Store - Installed add-ons (All)"

Indeed, the "Installed add-ons" information is more important than the "All" filter value.

Also, in English, by chance, "All Installed add-ons" sounds like "All installed add-ons" (note the difference in case). That means that concatenating a filter value and a tab name, by chance, allows to create a grammatically correct single expression (if you ignore the case). But in translations it does not sound so good as discussed in [this thread](https://groups.io/g/nvda-translations/topic/new_strings_for_store_addon/99566662?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,99566662,previd%3D1687330883456295628,nextid%3D1651299684347517459&previd=1687330883456295628&nextid=1651299684347517459) on the translators mailing list.

IMO it's safer (regarding potential translation issues) to concatenate unrelated values explicitly, i.e. adding parenthesis or dash in between, rather than trying to solve this problem with a translatable compound string such as `"{channel} {tabName}"`.

### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
Version: alpha-28477,50ef7d38 (2023.2.0.28477)
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A
#### If NVDA add-ons are disabled, is your problem still occurring?
N/A
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by gnailnix** [comment]
"Hi, @CyrilleB79 @seanbudd 

I very much agree with what Cyrille said, i.e.: the "Installed add-ons" information is more important than the "All" filter value.
For the name of the list in the add-on store: "{channel} {tabName} add-ons", I think it is too verbose. As noted in [this thread][link], the current list names cause confusion for localized translators of some languages.
I recommend removing {channel} from the list name of the add-on store, i.e.: The final effect should be "Installed add-ons", "Available add-ons", etc.
In fact, a similar approach is used in the NVDA settings panel. More detailed information, such as "NVDA Settings: General (normal configuration)", is displayed on the title bar, while the list name is simplified to "Categories", which works well.

Thanks"

[link]: https://groups.io/g/nvda-translations/topic/new_strings_for_store_addon/99566662?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,99566662,previd%3D1687330883456295628,nextid%3D1651299684347517459&previd=1687330883456295628&nextid=1651299684347517459
