### ISSUE TITLE
When role="math" is present, MathCAT isn't called

### ISSUE THREAD

**Issue by NSoiffer** [nvaccess/nvda#15058]
### Steps to reproduce:
Open a file that has `role="math"` specified around some MathML. Navigate to the math. Nothing is spoken for the math when MathCAT is used to read the math.  I'm pretty sure the same is true when MathPlayer or Access8Math is used to read the math.

[This example file](https://github.com/nvaccess/nvda/files/11875221/role-math-example.zip) has two instances of math. They are identical except that the first one has `role="math"` given on the span around the `math` element (both have a `span` element). Note: file is zipped html because I can't attach HTML in github.
### Actual behavior:
Nothing is spoken for the math with `role="math"` specified, but the math is read for the second instance without `role` given.

### Expected behavior:
AFAIK, `role="math"` should not affect the behavior of NVDA for enclosed math.

I discovered this bug based on a real-life file not speaking math in NVDA.

### NVDA logs, crash dumps and other attachments:
Nothing in the log file.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2023.1

#### Windows version:
Windows 10

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Haven't tried other versions

#### If NVDA add-ons are disabled, is your problem still occurring?
You need at least one math add-on to try this out.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
MathCAT doesn't use a COM interface.

**Comment by ways2read** [comment]
This issue occurs when reading math generated by Atypon's journal platform (allegedly used by 60% of English language academic journals). It affects math displayed on web pages and in generated EPUBs.

**Comment by ways2read** [comment]
It seems related to #4422

**Comment by jmegginson** [comment]
Vote for this. An update would be appreciated.  This is also true when role="math" is applied around a MathJax object. 

Is this a limitation of NVDA, Access8Math plugin or both? 

In comparison, JAWS continues to allow the math viewer to operate when role="math" is applied around a MathJax (MathML) object.

**Comment by NSoiffer** [comment]
I just tried 2024.4 rc1 and the problem is still there. It is happening at a level above MathCAT. I will try to debug the NVDA code and see if I can trace down where the problem lies.
