### ISSUE TITLE
Map flattened object nav gestures by default

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#15053]
### Is your feature request related to a problem? Please describe.
Object navigation can be difficult to grasp for some people. It might be helpful to assign the flattened object nav gestures (that are now only available on touch screen)by default.

### Describe the solution you'd like
Add the following additional gesture mappings:

- navigatorObject_nextInFlow: ("kb(desktop):NVDA+numpad9", "kb(laptop):shift+NVDA+=")
- - navigatorObject_previousInFlow: ("kb(desktop):NVDA+numpad3", "kb(laptop):shift+NVDA+-")

### Describe alternatives you've considered
Leave as is

**Comment by bramd** [comment]
I like the power of a nested object nav if the structure of an app is correct, but I tried explaining how to navigate with NVDA's review cursor to multiple users and most of them have difficulty understanding why and when they need to use up/down/left/right. Same users have no issue understanding swipe gestues in mobile VoiceOver or using Narrator with capslock+arrows. So yes, I think mapping this by default is a great idea.

**Comment by leonardder** [comment]
What do you think about the proposed gestures?

**Comment by burmancomp** [comment]
I suppose laptop layout gestures like "kb(laptop):NVDA+;", "kb(laptop):NVDA+'", "kb(laptop):NVDA+\" are not available?

**Comment by seanbudd** [comment]
I think the suggested gestures for desktop make more sense swapped

**Comment by leonardder** [comment]
> I suppose laptop layout gestures like "kb(laptop):NVDA+;", "kb(laptop):NVDA+'", "kb(laptop):NVDA+" are not available?

Actually, they are. However for laptop, I prefer at least the shift+NVDA combination to stay consistent with the other keys.

> I think the suggested gestures for desktop make more sense swapped

You are right. I based them on the next/previous review mode gestures, but I think those are actually a bit weird.

**Comment by burmancomp** [comment]
> > I suppose laptop layout gestures like "kb(laptop):NVDA+;", "kb(laptop):NVDA+'", "kb(laptop):NVDA+" are not available?
> 
> Actually, they are. However for laptop, I prefer at least the shift+NVDA combination to stay consistent with the other keys.

I have not strong opinion about gestures. You surely consider to keep gestures consistent, as well as to keep them as easy to use as possible.
