### ISSUE TITLE
No braille with Esys80 on last alpha

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#15079]
### Steps to reproduce:
* Start NVDA
* Try to unplug/re-plug the braille display
* Try to set braille display to "No braille" and then again to "Automatic"

### Actual behavior:
No braille on the display.
### Expected behavior:
Braille should be refreshed on the display.
### NVDA logs, crash dumps and other attachments:
[nvda.log](https://github.com/nvaccess/nvda/files/11916307/nvda.log)

#### NVDA installed/portable/running from source:
Temporary version from launcher.
#### NVDA version:
nvda_snapshot_alpha-28542,8accbfa7.exe
#### Windows version:
Windows 10 21H2 (AMD64) build 19044.3086
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
* NVDA 2023.1 installed: braille OK
* nvda_snapshot_alpha-28351,ffa9d798.exe (temp version): braille OK
* nvda_snapshot_alpha-28355,02199b76.exe (temp version): braille NOK
* Another recent alpha portable: braille NOK
* nvda_snapshot_try-fix-14872-28527,83b07642.exe (coming from https://github.com/nvaccess/nvda/issues/14872#issuecomment-1613921839): braille NOK
* Last alpha from source (commit 3f89b600aec1497ecbc106b588acc5d0db9ec387): braille OK!
* Alpha from source (commit a0a146d0fd9df6879d81780e56b347cd46b85f93): braille OK
* Alpha from source, some other commits around between April 3rd and today (June 30th): braille OK

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested, probably unrelated.

### Investigation
To summarize various version tests:
* all tested versions running from source are running well
* on compiled versions (at least temporary and portable versions), the issue has been introduced between nvda_snapshot_alpha-28351,ffa9d798.exe and nvda_snapshot_alpha-28355,02199b76.exe.

Looking at the possible range of commits between these two alpha versions, we have the following three commits which may have introduced the issue:
* Commit 02199b76e54dd4730f990466f25193f29c9106dc: Add-on store: add missing changelog entries
* Commit a0a146d0fd9df6879d81780e56b347cd46b85f93: Eurobraille bnote and bbook automatic detection (#14690)
* Commit 671c8babc495c5e7a049de75924214c16d45e28a: Bump requests from 2.28.2 to 2.31.0 (#14965)

Given the subject, #14690 is very likely.

Cc @FalkoBabbage:
When testing #14690, have you or Eurobraille guys also tested the older displays?

**Comment by leonardder** [comment]
It is probably a0a146d indeed, but it is almost impossible to read that diff due to the refactoring of the driver.

**Comment by FalkoBabbage** [comment]
Hi,
currently eurobraille does not show up at all in de brailleDisplayDrivers:

`import brailleDisplayDrivers, pkgutl
for loader, name, isPkg in pkgutil.iter_modules(brailleDisplayDrivers.__path__): print(name)`
This does not give eurobraille as an option.

Also, if I check the library zip file the eurobraille folder also does not occur. 
Is this something in SCons that I missed? I only tested it directly with the code, not with a distribution.

**Comment by leonardder** [comment]
Ugh, looks like you need to add the module to setup.py, similar to the albatros driver.

**Comment by seanbudd** [comment]
Can you test the fix in #15090? Thanks

https://ci.appveyor.com/api/buildjobs/ud1qxho0prvlkcxa/artifacts/output%2Fnvda_snapshot_pr15090-28566%2C9ce05249.exe

**Comment by FalkoBabbage** [comment]
> Can you test the fix in #15090? Thanks
> 
> https://ci.appveyor.com/api/buildjobs/ud1qxho0prvlkcxa/artifacts/output%2Fnvda_snapshot_pr15090-28566%2C9ce05249.exe

Thanks! I tested it with my B.Note and it works properly now
