### ISSUE TITLE
Gestures behavior should not depend from current review mode

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#15084]
### Steps to reproduce:

1. move to the system tray with win+b;
2. find, for example, the volume icon;
3. change review mode to screen;
4. press NVDA+enter (laptop) or NVDA+numpadEnter (desktop);
5. change review mode to object;
6. repeat step 4.

### Actual behavior:

Gesture works as expected only in object review mode.

I noticed also gestures not available (from an add-on) and completely different NVDA OCR results, always according to review mode.

### Expected behavior:

Gestures should work in both situations, as it was until recently.

### NVDA logs, crash dumps and other attachments:

During attempt with screen review mode, log says:

```
ERROR - scriptHandler.executeScript (20:47:05.066) - MainThread (1940):
error executing script: <bound method GlobalCommands.script_review_activate of <globalCommands.GlobalCommands object at 0x07C62FD0>> with gesture 'NVDA+Invio'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "globalCommands.pyc", line 1438, in script_review_activate
  File "textInfos\__init__.pyc", line 643, in activate
  File "baseObject.pyc", line 41, in __get__
  File "textInfos\offsets.pyc", line 513, in _get_pointAtStart
  File "displayModel.pyc", line 482, in _getBoundingRectFromOffset
LookupError
```

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

NVDA alpha-28542,8accbfa7

#### Windows version:

Windows 10 22H2.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

I'm quite sure the issue was born in last two alphas.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes.

**Comment by burmancomp** [comment]
After step 3 when review mode was screen NVDA told me with NVDA+numpad8 or NVDA+shift+. "blank". After NVDA+numpadMinus or NVDA+backspace same commands announced system tray item, and NVDA+numpadEnter and NVDA+enter also worked after that.

In review cursor category follow focus and caret are selected. For some reason that I do not know review cursor do not follow system focus/caret when object review is set to screen.

**Comment by ABuffEr** [comment]
Ok, I tried with 2023.1 with same results, so I noticed an issue that seems to not exist indeed. Closing issue.

**Comment by XLTechie** [comment]
@ABuffEr wrote:

> so I noticed an issue that seems to not exist indeed.

It doesn't exist in the way that you thought, but I think many users can be 
confused by this. Can the documentation be improved in this area, in some way 
that doesn't confuse things more?
