### ISSUE TITLE
Add ability to determine current document view in Microsoft Word

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#15088]
### Is your feature request related to a problem? Please describe.

Word behaves slightly differently depending on the current "View" in use.  Views include read mode, print layout, web layout, outline, draft, focus and immersive reader.

The layout can determine how things such as page numbers, columns and footnotes are presented, so it is useful for the NVDA user to be aware of the current view.

It is not currently possible to quickly find this out, short of pressing alt+w to open the view ribbon, then tab to move through until finding the "Pressed" toggle button.

While the view name isn't necessarily written on screen (unless the View ribbon is open, then it is), the presentation is different between layouts so a user familiar with the layouts will be able to glance at the screen to see cues about which layout they are in (whether there is whitespace around the page, whether page numbers are listed in the status bar, etc).

### Describe the solution you'd like

A user noted that with Jaws, insert+t reports the view with the Window title.  I would probably have chosen NVDA+tab for report focus myself, but in any case, either would be one keystroke which advises the current view.

### Describe alternatives you've considered

NVDA+tab or NVDA+t are probably the two most obvious candidates to add the information to.

### Additional context

Tested using NVDA 2023.1 on Windows 11 (64-bit) Version: 22H2, Build: 22621.1848  with Office 365 (64-bit) Version: 16.0.16529.20118 but this would affect any version of Office / Windows / NVDA.

**Comment by XLTechie** [comment]
I would inspect this in NVDA+t, as it describes the whole document, not just the 
current control which could conceivably be something else.

**Comment by amirsol81** [comment]
Yes - NVDA+T would be a great candidate for that. JAWS uses the same.

**Comment by nvdaes** [comment]
Seems that this doesn't have a PR. I'll create one at the appModule level.
It will consist in determining if the status bar is present. If so, if a children has the pressed state, it will be added to the name of the foreground object.

**Comment by CyrilleB79** [comment]
Is the status bar always present?

If no, an alternative design may be to use Word object model, if such information is available in the object model. Though, The Word object model too may not be available in some cases.

**Comment by nvdaes** [comment]
@CyrilleB79 , the status bar is not always present, for example when dialogs are open. Also, if someone doesn't want to have certain controls of the status bar, they can be disabled. I have tried to handle these cases.
About the DOM, I tried to investigate if this is available from Microsoft Word API, but I haven't found this, so I'm using the status bar, unless someone brings up better suggestions.
