### ISSUE TITLE
NVDA does not consistantly announce reading untagged document dialogue in Adobe reader

### ISSUE THREAD

**Issue by enessaribas** [nvaccess/nvda#15087]
### Steps to reproduce:
1. in Adobe Acrobat launch an untagged document 
### Actual behavior:
  NVDA is unresponsive.  To review the reading untagged document dialogue, moving away and back to the window with alt tab, or pressing f6 several times in the window is required.  However even in this case sometimes the dialogue will disappear and NVDA will announce unknown. 

### Expected behavior:
  NVDA reads this dialogue automatically  when launching an untagged document

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
NVDA alpha-28542,8accbfa7; 
#### Windows version:
windows 11 22h2  (OS Build 22621.1928)
#### Name and version of other software in use when reproducing the issue:
Adobe Acrobat  23.003.20215
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by michaelDCurran** [comment]
Please report this to Adobe.  The dialog either does not physically get focus, or focus events are not being fired by the application. There is nothing that NVDA can do here.
