### ISSUE TITLE
In Excel, cell format is reported on each move

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#15091]
### Steps to reproduce:
* Launch Excel (new blank sheet)
* In document formatting settings, enable reporting of paragraph alignment
* With arrows, move the focused cell in the sheet
### Actual behavior:
On each move, NVDA reports: '"align default  vertical align default  cell".
### Expected behavior:
The alignment should be reported only if it changes with respect to the previously selected cell.
### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
From source
#### NVDA version:
Alpha, commit 8accbfa7ee68c651fce3958b08b921d1041e8c7a
#### Windows version:
Windows 10 21H2 (AMD64) build 19044.3086
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2023.1 installed is OK
#### If NVDA add-ons are disabled, is your problem still occurring?
Not tested
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested

### Investigation
I have tested various versions (commits) of NVDA and found that the regression has been introduced in a5931ddca5bd87285dfc5778751349eac0a72d7a by PR #14984.

In `NVDAObjects/window/excel.py`,, in function `script_changeSelection`, changing back:
`oldSelection = self._getSelection()`
to:
`oldSelection = api.getFocusObject()`
allows to fix the issue.

However, this probably defeats the purpose of #14984.

@leonardder any idea?

**Comment by leonardder** [comment]
Thanks for reporting, I'll have a look later today.
I assume this is ok with UIA enabled?
