### ISSUE TITLE
NVDA crashes when IBM ViaVoice crashes

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1510]
**Reported by winman3000 on 2011-05-18 07:46**
If you type the word dage-gen or dane-ben, IBM ViaVoice crashes and NVDA too. I know it is a bug of IBM ViaVoice and Eloquence, but I think that NVDA should ignore this word or reload the synthesizer if the sythesizer is chrashed.

**Comment by bhavyashah** [comment]
Do we have any active users of NVDA+German IBM ViaVoice who can help us in determining whether this issue still stands?

**Comment by ehollig** [comment]
If this is a bug of IBM ViaVoice and Eloquence, it probably needsExternalFix. Looking at IBM ViaVoice on [Wikipedia](https://en.wikipedia.org/wiki/IBM_ViaVoice), it appears the latest stable release was 12 years ago. Closing because of these reasons.
