### ISSUE TITLE
[Taskbar]: Focus moves to an unknown element before moving to taskbar and NVDA announces it as "Pane Dragging"

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#15114]
### Steps to reproduce:
Turn on NVDA
Press Win+D to move the focus to desktop.
Press tab key and observe.
### Actual behavior:
On pressing tab key, from desktop, NVDA focus moves to an invisible element and it announces as "Pane Dragging"

### Expected behavior:
Focus should not move to invisible elements.

#### NVDA version:
2023.1

#### Windows version:
25376.1

**Comment by seanbudd** [comment]
This is a bug with Windows

**Comment by msftedad** [comment]
agree, we are closing the issue.
