### ISSUE TITLE
NVDA focus is not moving to left side controls in browse mode

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#15112]
[210059_nvda attachement.webm](https://github.com/nvaccess/nvda/assets/93735775/5905fc96-7a45-4019-a633-6dd363a0c0f4)
![210059_code snippet image](https://github.com/nvaccess/nvda/assets/93735775/54653825-9ce8-4d02-99ff-3223f6c7d1b2)

### Steps to reproduce:
1. Hit enter on this link (https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-navigation/) 
2. Tab till "Home" treeitem.
3. Turn on NVDA in browse mode.
4. Check whether NVDA focus is moving to left side controls in browse mode or not.

### Actual behavior:
NVDA focus is not moving to left side controls in browse mode

### Expected behavior:
NVDA focus should move to the left side controls in browse mode.

#### NVDA version:
2023.1

#### Windows version:
window: 11, Version: 21H2 (OS build 22000.2057)

**Comment by seanbudd** [comment]
This is intended behaviour
