### ISSUE TITLE
NVDA announces nested role="button" elements incorrectly

### ISSUE THREAD

**Issue by phillipervin** [nvaccess/nvda#15116]
### Steps to reproduce:
1. Navigate to https://jsfiddle.net/phillip_ervin/76wotsgz/
2. Tab to 'Start Here' element.
3. Tab once, next element focused will be the 'Calendar Cell'. NVDA announces content as:
>Calendar Cell Day: 10 Monday Appointment  button Additional Detail  button 
4. Tab again, focus will be on the element for Monday Appointment. NVDA announces content as:
>Monday Appointment  button    button
5. Tab again, focus will be on the element for Additional Detail.  NVDA announces content as:
>Additional Detail button    button

### Actual behavior:
When the outer element with button role is focused, it is not announced as button, however inner elements with button roles are announced as buttons.

When the inner elements with button role are focused, they are announced as buttons twice.

### Expected behavior:
For the outer element we would expect something like:
>Calendar Cell Day: 10 Monday Appointment  Additional Detail   button 

For the inner elements we would expect:
>Monday Appointment button
>Additional Detail button 

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
2023.1 (2023.1.0.27913)

#### Windows version:
Windows 11 Version 22H2 (Build 22621.1848)

#### Name and version of other software in use when reproducing the issue:
Chrome 115.0.5790.75 (Official Build) beta (64-bit) (cohort: Beta) 
Firefox 115.0.1 (64-bit)

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If NVDA add-ons are disabled, is your problem still occurring?
No add-ons installed.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by seanbudd** [comment]
This is a W3C violation. You should not have interactive content as a child to a button.

https://stackoverflow.com/a/39386695/8030743

**Comment by seanbudd** [comment]
Perhaps `role=group` is more appropriate for the parent

**Comment by phillipervin** [comment]
Thanks for your explanation, @seanbudd. That makes sense. I've also found this resource helpful for others who may encounter this issue: https://github.com/dequelabs/axe-core/issues/601.
