### ISSUE TITLE
Website behaviour differs when navigating with the keyboard

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1512]
**Reported by AEGIS on 2011-05-20 12:21**
To reproduce the bug do the following:

1) Open http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/
2) Select a tab e.g. Slider
3) Press the tab key - focus should be around the content area of the selected tab
4) Press CTRL + Arrow up

If NVDA is not running the previously selected tab is focused again. If NVDA is running the last tab in the list is focused (it is always the Tree tab no matter what tab was previously selected). It seems not to be a programming issue with the website

**Comment by ehollig** [comment]
I could be wrong, but this sounds like it has been resolved.

**Comment by derekriemer** [comment]
not a bug, invalid. Closing as invalid.
