### ISSUE TITLE
 Screen reader announcing unnecessary information as 'share' when focus move to info control.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#15123]
**Steps to reproduce:**
1. Open URL: https://aka.ms/codexbingv2 in New Edge browser.
2. Bing Chat GPT page will appear.
3. Enter input 'How to Swim video' edit field.
4. After result get displayed, navigate to 'How to Swim' video control and activate it.
5. In this video popup get appeared.
6. Turn on NVDA and Now try to navigate to info control.
7. Observed that Screen reader announcing unnecessary information as 'share' when focus move to info control.

**Actual behavior:**
Screen reader announcing unnecessary information as 'share' when focus move to info control..

**Expected behavior:**
Content which is visually displayed must also be available to assistive technology users. If the content is dynamic (such as an error message), focus management and/or aria-live can expose it to a screen reader. If the content is static, be sure it is not hidden with CSS or using aria-hidden.

 **NVDA logs, crash dumps and other attachments:**

 **System configuration**
 NVDA installed/portable/running from source:

 **NVDA version:**  NVDA 2023.1

**Windows version: Edition**: Windows 11 Enterprise
Version 22H2
OS build 22621.1848
Experience: Windows Feature Experience Pack 1000.22642.1000.0

 **Name and version of other software in use when reproducing the issue:**

 **Other information about your system:**

 **Other questions
 Does the issue still occur after restarting your computer?

 Have you tried any other versions of NVDA? If so, please report their behaviors.

 If NVDA add-ons are disabled, is your problem still occurring?

 Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?**

**Comment by josephsl** [comment]
Hi,

Please tell us:

* Web browser version in use (I assume Microsoft Edge).
* In steps to reproduce, let us know which keyboard commands, mouse movements, touch gestures and what not were used to reproduce the issue.
* Does this happen with other screen readers and/or additional web browsers? Note that I tested this with Edge 114 and Firefox 115 on Windows 11 22H2 build 22621.1928.

As for screen readers announcing screen content: yes, but remember that screen readers such as NVDA rely on content deemed important (at that moment) by the web author as communicated via focus and other events, ARIA specs, or other factors. Along with this, NVDA and other screen readers may announce dynamic content if told to do so by users and websites, and unless the web author tells screen readers to announce most recent information right away, screen readers will process and report everything from beginning to end (a good example is UIA notification event where some messages are announced one after the other).

Thanks.

**Comment by seanbudd** [comment]
We are unable to process this issue as it stands.

To be able to reproduce this issue, we need minimal a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).
This is very likely a problem with the implementation of the application/website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers
