### ISSUE TITLE
Intermitent crashing on latest alphas

### ISSUE THREAD

**Issue by blindpk** [nvaccess/nvda#15150]
### Steps to reproduce:
NVDA crashes intermitently while reading. Hard to reproduce because I've not managed to pinpoint what causes it. Issue appeared a few days ago. The error in the log file indicates that it has to do with the OneCore voice.

### Actual behavior:

While reading, NVDA crashes. No exit sound and it does not restart.

### Expected behavior:

No crashing.
### NVDA logs, crash dumps and other attachments:
Log file and crash dump attached.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-28685
#### Windows version:
Windows 11, 22H2, latest updates installed, Swedish language
#### Name and version of other software in use when reproducing the issue:
Has appeared when using Notepad, Firefox and on its own
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, but issue first appeared a few days ago
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
[NVDALog.zip](https://github.com/nvaccess/nvda/files/12064224/NVDALog.zip)

**Comment by seanbudd** [comment]
@jcsteh - this is an error coming from nvwave

**Comment by Brian1Gaff** [comment]
I'd be interested in what it does with add ons disabled.
 Does the effect occur with Espeak or other synths?

Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "blindpk" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Sunday, July 16, 2023 3:06 PM
Subject: [nvaccess/nvda] Intermitent crashing on latest alphas (Issue 
#15150)

**Comment by Brian1Gaff** [comment]
Hi, if you look back on one of the general lists, I asked about this some 
time ago. It looked then like two things were attempting to use that wav 
player at the same time. Its sound schemes in this case, and seems to be 
made worse by other add ons like  browser nav for some odd reason.. 
Disabling that seemed to stop it happening. Timing issues?
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by blindpk** [comment]
Have possibly found a way to reproduce, however, this does not show exactly the same behavior but similar.
I did the following:
* Opened foobar2000.
* Turned off sound.
* Started playing songs in WASAPI Exclusive mode.
* Jumped around in a large playlist for a bit, then NVDA froze and produced the attached log.

As it was only frozen, no crash dump was created, and, as I said, I'm not 100% sure if this is the same bug, but I post it here anyway. All add-ons were turned off and ESpeak was used as the synth.
[nvda-old.log](https://github.com/nvaccess/nvda/files/12071234/nvda-old.log)

**Comment by amirsol81** [comment]
@Brian1Gaff Not with the most recent Alpha in particular, but I've seen this with new Alphas made available over the past month or so. And it happens with eSpeakNG/Eloquence as well, with or without add-ons. When it happens, it seems that NVDA is still running but in "no speech" mode. I just restart NVDA to resolve it.

**Comment by seanbudd** [comment]
Can you confirm that this issue is fixed when WASAPI is disabled? You can disable WASAPI in advanced settings.

**Comment by jcsteh** [comment]
The log does indeed seem to indicate a bug in the WASAPI code, but I haven't seen it myself despite using this continually and I have no idea what would cause it at this point. I'll think on it further.

**Comment by OzancanKaratas** [comment]
Additional information: The IBM TTS add-on is not fully compatible with WASAPI. The code for @davidacm's IBM TTS add-on should be reviewed for WASAPİ. However, @pumper42nickel's Eloquence Synthesizer add-on does not seems to crash in long time of usage.

**Comment by brunoprietog** [comment]
It happens to me very frequently when removing the headphones from my laptop, using WASAPI here as well. NVDA crashes completely and I don't know how to attach logs

**Comment by brunoprietog** [comment]
Also, it does not seem to be a problem with the synthesizer. With OneCore Voices it also happens

**Comment by OzancanKaratas** [comment]
@brunoprietog, please give me some info:

- Your computer brand and model (get it from msinfo32)
- Audio driver version (get it from Programs and Features or Device Manager)

The problem may be that you are not using a proper sound card driver.

**Comment by brunoprietog** [comment]
I have a Microsoft Surface Laptop 5. I'm using Microsoft High Definition Audio Device 10.0.22621.608. The reason I use it is because its latency is much lower than the Realtec drivers and it is from Microsoft itself.

I've found that the problem happens when I'm on a Discord call. If I disconnect the headphones while on a Discord call, NVDA starts producing an error sound every few seconds but is totally unusable until I restart it. If I'm not on the call everything works fine. All this with WASAPI enabled. With WASAPI disabled it works fine.

As NVDA stops responding, I don't know how to attach logs. If someone helps me with that I could post them here. Thanks.

**Comment by XLTechie** [comment]
The log of the previous NVDA run is in %temp%\nvda-old.log.

That means, after you restart NVDA, you can go into %temp% (for example through 
the run dialog Windows+r), then locate the nvda-old.log file. Press space to 
select it, and press shift+applications or shift+f10, and choose "copy as path" 
from the menu.

Then go to a comment here, press the browse button, and press ctrl+v to paste in 
the path you copied earlier.
Press enter, and the log should be attached.

Then submit the comment.

**Comment by XLTechie** [comment]
The log of the previous NVDA run is in `%temp%\nvda-old.log`.

That means, after you restart NVDA, you can go into `%temp%` (for example through 
the run dialog `Windows+r`), then locate the `nvda-old.log` file. Press space to 
select it, and press `F2` or use the context menu to rename it to `nvda-old.txt`, because you can't attach a `.log` file here.

Then, press `shift+applications` or `shift+f10`, and choose "copy as path" 
from the menu.

Then go to a comment here, press the browse button, and press `ctrl+v` to paste in 
the path you copied earlier.
Press enter, and the log should be attached.

Then submit the comment.

**Comment by brunoprietog** [comment]
Thanks! Here is the log with the add-ons disabled. I can reproduce it with any synthesizer.

[nvda-old.txt](https://github.com/nvaccess/nvda/files/12309416/nvda-old.txt)

**Comment by jcsteh** [comment]
Ah. That log is super helpful. Thanks. I think it's a different issue from the one for which this was originally filed, but it's a problem nevertheless. Now I just have to figure out how to fix it without being able to reproduce it myself. :)

**Comment by jcsteh** [comment]
Investigation note: WASAPI idle() is called on the main thread and it calls sync(). If the device is disconnected during a call to sync(), it looks like sync() doesn't return sometimes. Could this be because IAudioClock::GetPosition() returns an error, in which case we return 0 from getPlayPos? In that case, 0 would remain < sentMs forever if sentMs is > 0.

**Comment by amirsol81** [comment]
> Also, it does not seem to be a problem with the synthesizer. With OneCore Voices it also happens

I can confirm this. I've seen it with virtually all TTS engines. Oftentimes when it happens, NVDA becomes silent but keeps playing the error chime every few seconds - maybe 5 to 10 seconds. I'll also be proving my log as soon as it happens.

**Comment by amirsol81** [comment]
OK - it happened to me with eSpeak-NG. I was reading a page with Chrome so, this time around at least, I'm not sure if it's, say, the BrowserNav add-on or WASAPI - I guess the latter. My old NVDA log is also attached.
[nvda-old.txt](https://github.com/nvaccess/nvda/files/12330248/nvda-old.txt)

**Comment by amirsol81** [comment]
Yet another log file of mine which displays info about my latest WASAPI-related crash.
[Uploading nvda-old.txt…]()

**Comment by amirsol81** [comment]
Yet another NVDA old log of my machine related to the 
[nvda-old.txt](https://github.com/nvaccess/nvda/files/12336453/nvda-old.txt)
sudden WASAPI-related crash.

**Comment by amirsol81** [comment]
@jcsteh @seanbudd @XLTechie Any update or progress on this? I've provided 2 logs so far and they apparently display the issue.

**Comment by jcsteh** [comment]
I don't have time to give this the in-depth testing it needs right now, which is why I haven't submitted a fix. However, if you're willing to take a build for a decent spin, that's probably enough, perhaps better since you can reproduce it and I can't. I've just pushed a try build, so I'll post here when it's done.

**Comment by jcsteh** [comment]
It's worth noting that my fix is speculative; I honestly don't know for certain that the issue I've identified is actually the problem you're seeing and I have no real way of verifying that. If worse comes to the worst, I guess we can disable WASAPI by default again until we can sort this out.

**Comment by amirsol81** [comment]
Thanks @jcsteh for your efforts. So I'll test your build to see what it does. The point is that even here my crashes are quite rare.

**Comment by OzancanKaratas** [comment]
@jcsteh, please create a pull request to beta branch for this try build. Even if this build doesn't make any significant changes, we should have the change tested by a larger group of users.

**Comment by brunoprietog** [comment]
I think it solves the problem for me. I've had no errors

**Comment by jcsteh** [comment]
Whether or not this goes into beta isn't my call. Also, WASAPI has been disabled by default in beta, so I'm not sure accelerating this into beta is necessary. Nevertheless, I'll submit a pull request when I get a chance.

**Comment by amirsol81** [comment]
So any progress on this? Any alphas or pre-alpha builds to try? I've seen lots of crashes over the past few days which are TTS-independent. Interestingly, some of them occur after disconnecting my Bluetooth headphone and returning to the built-in laptop speakers.

**Comment by brunoprietog** [comment]
Did you try the test build?

**Comment by amirsol81** [comment]
@brunoprietog No, as I haven't seen the test build. 😕
Where can I grab it? Of course, I'd rather see it as part of an alpha release so that I can test with my add-ons.

**Comment by brunoprietog** [comment]
It's in an above comment, in a link that says "Try build". With that one you can try it with your add-ons installed as well

**Comment by amirsol81** [comment]
@brunoprietog thanks! I'll try it.

**Comment by amirsol81** [comment]
@jcsteh @brunoprietog Well, low and behold, this try build has fixed my crashes! I've had no crashes after installing this build with various TTS engines and multiple potentially crash-producing scenarios tested. So it would be a good idea to release it as part of an upcoming alpha for more comprehensive testing.

**Comment by amirsol81** [comment]
@jcsteh @brunoprietog Update: unfortunately I still get crashes with the try build. Two of them just happened here.

**Comment by jcsteh** [comment]
Do you have a log for the issues with this try build? It is likely to have a slightly different stack, so I'll need a new log to diagnose that.

**Comment by amirsol81** [comment]
@jcsteh Think I lost that one as I restarted Windows and a newer log file was generated. However, I'll make sure to locate and send the next log file as soon as the crash occurs.

**Comment by XLTechie** [comment]
@amirsol81 You might want to install the NVDA Dev And TestToolbox add-on, which 
lets you keep more than just the two logs. 
https://www.nvaccess.org/addonStore/legacy?file=nvdaDevTestToolbox

**Comment by amirsol81** [comment]
@jcsteh Here's my log after a fresh crash. This time it happened as I switched to my Bluetooth headphones - after a couple 
[nvda-old.log.txt](https://github.com/nvaccess/nvda/files/12446127/nvda-old.log.txt)
minutes of using them.

**Comment by amirsol81** [comment]
And yet another fresh crash accompanied by an NVDA log which is attached. Interestingly, with this crash I had to kill NVDA and its processes from the Task Manager in order to be able to run it again. Attempting a single restart couldn't help.
[nvda-old.log.txt](https://github.com/nvaccess/nvda/files/12448136/nvda-old.log.txt)

**Comment by jcsteh** [comment]
Curious. That's locking up in exactly the same spot I supposedly fixed. So now I have no clue.

**Comment by jcsteh** [comment]
How did you switch exactly? What did you switch from? Did you just turn them on or did you disconnect some other device such that it switched?

**Comment by amirsol81** [comment]
@jcsteh The last log is for a crash without a switch: I just turned on the computer, selected eSpeakNG, opened Chrome, read for a minute or 2, and NVDA crashed. However, the log posted before that one, I mean the bigger log, is for a crash which happened after my audio was automatically altered from Bluetooth headphones to Realtek audio upon turning off the Bose headphones.

**Comment by jcsteh** [comment]
The last crash actually might not be caused by nvwave at all. There's nothing in the log to indicate that it was. The previous crash definitely was though, so that's the one I'm more interested in right now.

**Comment by jcsteh** [comment]
I'm starting to think this is an edge case interaction with the Bluetooth audio add-on. I'll push another try build which might fix this.

**Comment by brunoprietog** [comment]
Anyway, I hope you can keep the changes from the first test build, that fixed the errors for me, apparently, after a long period of usage

**Comment by jcsteh** [comment]
@amirsol81 Please give [this try build](https://ci.appveyor.com/api/buildjobs/jiv1w48t4ea77oys/artifacts/output%2Fnvda_snapshot_try-playPosErr-28993%2C812bb16f.exe) a shot and let me know if that helps.

**Comment by XLTechie** [comment]
One means of testing with the former try build, might be to switch from 
Bluetooth Audio, to Wake Speaker. It does the same thing (very probably more 
effectively), but might be different enough not to provoke this. Then again, it 
might be just another variable that's not worth introducing.

https://github.com/davidacm/WakeSpeaker

**Comment by jcsteh** [comment]
Either way, this bug needs to be fixed, so let's see if the new try build fixes it and we can figure out next steps from there.

**Comment by amirsol81** [comment]
@jcsteh Thanks for your efforts. I'll take a stab at the new build later today as I get home as it's my Windows 11 machine which is generating these crashes. I'll post the update here.

**Comment by amirsol81** [comment]
@jcsteh Thanks again for your efforts. Well, hope I'm not proven wrong this time around, but the latest try build seems to be crash-free! So far I've seen no crashes whatsoever. I'll keep monitoring the situation and will post updates here in case something goes awry.

**Comment by jcsteh** [comment]
Okay. I'm going to give this a few days, but if we're still good after that, I'll submit a pull request.

**Comment by ruifontes** [comment]
I have also tested with WASAPI activated and deactivated, with whiteNoise add-on activated and deactivated, and no crash!

**Comment by amirsol81** [comment]
@jcsteh Something strange is happening here.
While I've had no audio-related crashes so far, with the new try build NVDA beeps every 20 or 30 seconds or so. And it always beeps almost 12 seconds after the last speech output, when no keyboard command is executed. Sometimes it beeps while something is being spoken, say in continuous reading. I tried disabling all add-ons, but the beeps continue, and nothing gets written to my log file to determine the potential source of that. It happens in almost all NVDA sessions even after I restart Windows. I'm baffled, so thought you might shed light on the glitch.

**Comment by jcsteh** [comment]
My bad. Forgot to remove a debug beep from the code. I'll remove it before I submit a pull request.

For your interest, that beep indicates when an audio stream has been treated as idle. I put it there to help me ensure that my code hadn't broken the idle checks, but forgot to remove it before pushing a try build.

**Comment by amirsol81** [comment]
@jcsteh Thanks for the explanation - it was quite enlightening!
So looking forward to the PR.
