### ISSUE TITLE
`aria-haspopup="dialog"` announced as "submenu"

### ISSUE THREAD

**Issue by dgibson666** [nvaccess/nvda#15155]
When I use `aria-haspopup="dialog"` on a button control that opens a full-screen overlay (modal) dialog, NVDA is announcing this as "submenu" instead of dialog. Since there is a separate "menu" value for this attribute, it seems like a bug.

### Steps to reproduce:
Tab to a button with  `aria-haspopup="dialog"`.

### Actual behavior:
Announces "submenu"

### Expected behavior:
Announce "dialog"

### NVDA logs, crash dumps and other attachments:
n/a

#### NVDA version:
NVDA v2023.1

#### Windows version:
Windows 11

#### Name and version of other software in use when reproducing the issue:
Chrome Version 114.0.5735.199 (Official Build) (64-bit)

**Comment by seanbudd** [comment]
Welcome @dgibson666 ,

We are unable to process this issue as it stands.
To be able to reproduce this issue, we need a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).

Kind Regards,
NV Access Software Developers

**Comment by alexarnaud** [comment]
Hello,

Here the sample:
`data:text/html,<button aria-haspopup="dialog">Open</button>`

You just need to tab on the button and NVDA latest stable release will say "button submenu Open"

**Comment by mzanm** [comment]
This was fixed in #14709

**Comment by dgibson666** [comment]
I'll upgrade and close the issue once confirmed, unless a project owner closes it first.
