### ISSUE TITLE
DOM with role="application" is hidden from headings navigation or browse mode navigation

### ISSUE THREAD

**Issue by kolaps33** [nvaccess/nvda#15166]
Please find below two types of repro steps. One is about heading navigation, second is about browse navigation.

### Steps to reproduce:
1. Open enclosed example from page: "application-role-on-some-page-area.html"
Enclosing html file compressed to zip as I could not add html file directly:
 [application-role-on-some-page-area.zip](https://github.com/nvaccess/nvda/files/12099639/application-role-on-some-page-area.zip)
3. Navigate to the "Before test" button.
4.1 Press Insert+F7 and navigate to "headings" radio button. Verify listed headings. Then close this dialog. 
3.2 Focus is still on "Before test" button. Press key 2 and key 3 to navigate through the headings. 

### Actual behavior:
NVDA navigates only to headings which are outside the area which has role="application".
NVDA doesn't list headings inside the area with role="application" in the "List all heading" dialog. 

### Expected behavior:
NVDA could navigate to headings inside are with role="application" and could list all headings in the dialog

### Comment
NVDA behaves like role="application" should hide the part of the UI from accessibility tree. The similarly like aria-hidden="true" does. Please, is this expected behavior? The JAWS and Narrator still navigate to these headings.  

### Steps to reproduce:
1. Open enclosed example from page: "application-role-on-some-page-area.html"
3. Navigate to the "Before test" button.
4.  Navigate in browse mode with keep pressing "down arrow" key

### Actual behavior:
Once user navigates to the area with role="navigation", then NVDA just announce "application" and skip the whole content. When this role="application" is on the top of DOM, then user just hear "application" and "blank"...

### Expected behavior:
NVDA could navigate inside the area with role="navigation". The JAWS and Narrator still navigates inside this area. 

### NVDA logs, crash dumps and other attachments:
no available

### System configuration
NVDA installed

#### NVDA version:
2023.1

#### Windows version:
OS Name	Microsoft Windows 11 Enterprise
Version	10.0.22621 Build 22621

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
didn't run this tool

**Comment by Adriani90** [comment]
my understanding is that role="application" explicitely tells NVDA not to build its own virtual document, but to respect the application navigation layout and the rutines defined by the app developers. So browse mode will not work in this case.

Quote:
"The application document structure role, indicates to assistive technologies that this part of the web content contains elements that do not conform to any other known HTML element or WAI-ARIA widget. Any sort of special interpretation of HTML structures and widgets should be suspended, and control should be completely handed over to the browser and web application to handle mouse, keyboard, or touch interaction.
In this mode, the web author is completely responsible for handling any and all keyboard input, focus management, and other interactions and cannot assume assistive technologies would do any processing on their end."

Source:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/application_role

@jcsteh any idea how Jaws or narator build their virtual document even in role="application"? I guess in that case the aria specs are not respected entirely.

**Comment by jcsteh** [comment]
That's correct. To prevent any interference with application content, NVDA doesn't render it into browse mode at all. I guess JAWS and Narrator still render this into the virtual cursor/scan mode.

Note that NVDA is not treating this like aria-hidden. The application does have a placeholder in browse mode so that you can press enter to interact with it.

If you really want this content to be navigable in browse mode, it should not be marked with role="application".
