### ISSUE TITLE
read email message in thunderbird from message list.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#15176]
### Describe the solution you'd like
in versions prior to tunderbird 115 when walking with the arrows in a folder, when a message receives focus, nvda read in addition to all the email information such as sender and subject, it read the email message.
Just like nvda does in other email managers like windows email.
Therefore, it was possible to read the email without opening the message, a similar experience for people who see and read the message displayed on the side panel without opening the message.
In newer versions of tunderbird from 115 onwards, nvda no longer reads the message when the focus is on the mailing list in the folder.
I would like this feature to be implemented again.

**Comment by Brian1Gaff** [comment]
I think a lot of people are avoiding the new code base version of Tbird, due 
to quite a few oddities still present, so any modification of the app module 
or an add on would need to be code base agnostic and not cause issues of 
regression if used with the older version.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "fernando-jose-silva" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Saturday, July 22, 2023 12:35 AM
Subject: [nvaccess/nvda] read email message in thunderbird from message 
list. (Issue #15176)

**Comment by Brian1Gaff** [comment]
Personally, I prefer to hit enter to read an email as it slows it down if it 
opens in a preview panel, much like it used to in Outlook Express, but you 
could turn this off or on in the client. Are you saying that nvda does not 
respect this switch if it exists in Tbird?
Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "fernando-jose-silva" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Saturday, July 22, 2023 12:35 AM
Subject: [nvaccess/nvda] read email message in thunderbird from message 
list. (Issue #15176)

**Comment by seanbudd** [comment]
This is something that needs to be reported and requested from thunderbird
