### ISSUE TITLE
Add-on store: Not all Portuguese translations are displayed in available add-ons

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#15173]
### Steps to reproduce:
* Run NVDA in Portuguese with `--lang=pt_PT` flag
* Go to add-on store, available add-ons tab
* select at Agenda add-on(Accessible agenda)
* Look at description

### Actual behavior:
* The add-on's name is in English
* The description is in English
### Expected behavior:
Since a Portuguese translation exists (pt):
* The add-on's name should be in Portuguese ("Agenda acessível")
* The description should also be in Portuguese

### Additional notes
Probably rather an issue on server side, but I have opened the issue here since it's where the visible part of the issue occurs.

If I understand correctly, NVDA's add-on store sends a request to the server for a list of add-ons in "pt_PT" language. The server replies with the add-ons in "pt_PT" if existing, else in English. It should instead list the add-ons in "pt_PT", else in "pt", else in English.

### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
Source
#### NVDA version:
Commit c4ca763b60e6e4d400a454c8295b3dafa9e9771b
#### Windows version:
Windows 10 21H2 (AMD64) build 19044.3086
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
N/A
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A
#### If NVDA add-ons are disabled, is your problem still occurring?
Not tested
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

Cc @ruifontes

**Comment by seanbudd** [comment]
Hi @CyrilleB79, this is intended behaviour. `pt` without a language code should not fallback to `pt_PT` or `pt_BR`. 
Some add-ons have chosen to create translations for `pt`, so using that language code allows some add-ons to be translated.
In absence of `pt` translations, i.e. if add-ons chose not to create translations for `pt` we would still fall back to english rather than `pt_PT` or `pt_BR`.

**Comment by CyrilleB79** [comment]
> Hi @CyrilleB79, this is intended behaviour. `pt` without a language code should not fallback to `pt_PT` or `pt_BR`. Some add-ons have chosen to create translations for `pt`, so using that language code allows some add-ons to be translated. In absence of `pt` translations, i.e. if add-ons chose not to create translations for `pt` we would still fall back to english rather than `pt_PT` or `pt_BR`.


@seanbudd:
But it's the other way around: NVDA is in "pt_PT". So it requests 'pt_PT' to the add-on store. For each add-on the add-on store should provide pt_PT if available, else pt if available, else en. For "Accessible agenda", there is no pt_PT translation, so the pt description is expected; the English description is actually provided instead.

**Comment by seanbudd** [comment]
ah I see - we could probably fallback to languages without locale when generating the views in addon-datastore-transform

**Comment by seanbudd** [comment]
This should be solved now

**Comment by CyrilleB79** [comment]
Thanks! I confirm that the issue is solved on my side.
