### ISSUE TITLE
Allow add-on braille display drivers to opt in for auto detection

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#15196]
### Is your feature request related to a problem? Please describe.
There is currently no documented way for braille display drivers to register themselves for auto detection. You can register a display in a global plugin, but as the global plugin loads after the braille subsystem, the display won't be detected in the first round of detection.

### Describe the solution you'd like
1. Add a `registerAutomaticDetection` method on `BrailleDisplayDriver`. This method must be implemented for drivers to register themselves in bdDetect. The method receives a new bdDetect.DriverRegistrar object that has addUsbDevices, addBluetoothDevices and addDeviceScanner methods that are bound to the driver.
2. Add a new checklistbox to the braille display selection dialog. When selection is set to automatic, this list box will be visible and allows you to opt out for auto detection of drivers you aren't interested in. For example, I only own HandyTech and Humanware devices, so the rest can be stolen from me.😉 Note that this list box will be a opt out list, so drivers will be enabled by default. This ensures that new drivers will always be enabled unless explicitly disabled.
3.  bdDetect.addUsbDevices and bdDetect.addBluetoothDevices will be deprecated. The advanced option to disable HID braille will also be removed in favor of this new ability to opt out for detection. As HID braille opt out is an advanced setting, I don't think profile upgrades are required.

**Comment by bramd** [comment]
From a user's perspective, the opt-out of certain drivers is the big feature here worth implementing in it's own right. Easier driver registration for add-on developers is also a nice bonus that I would love to see implemented.

The HID braille driver sometimes activates when a HID-compatible display such as the Brailliant BI 40x is being detected during a scan cycle where the native Brailliant driver missed it. This causes confusion such as other key bindings and is a good argument to get disabling this driver outside of the advanced options.
