### ISSUE TITLE
2023.2 beta 1 and eloquence - words that start with uppercase are being spelled

### ISSUE THREAD

**Issue by alexandretoco** [nvaccess/nvda#15212]
### Steps to reproduce:
Just use eloquence with beta. 
press nvdaKey + n and arrow in this menu and tab to navigate in any configuration dialog
For me, it happens with codefactory eloquence and codefactory vocalizer
### Actual behavior:
words that starts with uppercase are being spelled

### Expected behavior:
<!--
words should be read normally 

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2023.2 beta 1
#### Windows version:
windows 10
#### Name and version of other software in use when reproducing the issue:
codefactory eloquence and codefactory vocalizer
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
in 2023.1, the problem didn't occur

**Comment by CyrilleB79** [comment]
Hi @alexandretoco 

Thanks for reporting.
Unfortunately you have not filled the whole template; thus some important information is missing.
Could you edit your first comment (click the "Show options" button) and add the missing sections of the [template](https://github.com/nvaccess/nvda/issues/new?assignees=&labels=&projects=&template=bug_report.md)?

I think that the log (in at debug level) would especially be useful. And if possible for comparison, a log with the same steps with NVDA 2023.1 if you confirm that 2023.1 is OK.
If you have no privacy concern, you can attach tem to this issue. Else, you can send it to me (cyrille dot bougot at laposte dot net), or better directly to NVAccess people (info at nvaccess dot org).

Thanks.

**Comment by seanbudd** [comment]
Please open a new issue with the bug template correctly filled: https://github.com/nvaccess/nvda/issues/new?assignees=&labels=&projects=&template=bug_report.md
