### ISSUE TITLE
NVDA 2023.2 Beta 1: Can not tab past the first link in a message in Windows mail.

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#15211]
### Steps to reproduce:

1) Open an email with more than one link in it.  A simple text message with just two lines might be:

Test link www.google.com
NV Access www.nvaccess.org

(If composing a new message, send it to yourself, and then check for new mail to download it).

2) Press TAB to move to the first link.
3) Press TAB to move to the second link.

### Actual behavior:

At the first tab press, focus moves to the first link (www.google.com in my example).  The link is highlighted then immediately un-highlighted.

At the second tab press, exactly the same thing happens: Focus moves to the first link, which gets highlighted, then immediately un-highlighted.

### Expected behavior:

Focus should move to the next link each time TAB is pressed.

### NVDA logs, crash dumps and other attachments:

Here is a log fragment from pressing tab twice in an email:

IO - inputCore.InputManager.executeGesture (16:34:05.581) - winInputHook (21576):
Input: kb(desktop):tab
DEBUG - editableText.EditableText._hasCaretMoved (16:34:05.607) - MainThread (3696):
Focus event. Elapsed 0.0202839 sec
IO - speech.speech.speak (16:34:05.661) - MainThread (3696):
Speaking [LangChangeCommand ('en_GB'), 'www.google.com', 'link']
IO - inputCore.InputManager.executeGesture (16:34:07.036) - winInputHook (21576):
Input: kb(desktop):tab
DEBUG - editableText.EditableText._hasCaretMoved (16:34:07.066) - MainThread (3696):
Focus event. Elapsed 0.0197625 sec
IO - speech.speech.speak (16:34:07.116) - MainThread (3696):
Speaking [LangChangeCommand ('en_GB'), 'www.google.com', 'link']

#### NVDA version:

2023.2 Beta 1 Installed

#### Windows version:

Windows 11 (64-bit) Version: 22H2, Build: 22621.1992 

#### Name and version of other software in use when reproducing the issue:

Windows Mail Version 16005.14326.21514.0

#### Does the issue still occur after restarting your computer?

Yes, and also reported by a user (but no system information provided)

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

NVDA 2023.1 correctly moves through links in messages.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

**Comment by michaelDCurran** [comment]
Bisecting shows that it is caused by my pr #14611
I shall investigate further.
