### ISSUE TITLE
Thunderbird occasionally crashes with beta of nvda

### ISSUE THREAD

**Issue by PeterLecky** [nvaccess/nvda#15210]
### Steps to reproduce:
Happens sometimes, canot tsimulate it. I saw it more times when i used ctrl+w to close particular window with message. Thunderbird crashed immediately after shortcut.

### Actual behavior:

Thunderbird sometimes unexpectedly crashes when using it with beta1 of nvda 2023.2. 

### NVDA logs, crash dumps and other attachments:
There is nothing special in nvda log, Thunderbird produces crashdump, i can post it personally to some mail address.
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
2023.2beta1 (2023.2.0.28773)
#### Windows version:
Windows 10 latest version
#### Name and version of other software in use when reproducing the issue:
Older version of thunderbird 60.0
#### Does the issue still occur after restarting your computer?
Yes, few times per day
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
It is stable (there are no crashes) with latest stable NVDA.

**Comment by seanbudd** [comment]
Please update to the latest version of thunderbird and confirm this is still an issue

**Comment by XLTechie** [comment]
@seanbudd Do you mean for the user to upgrade to version 102, or 115 of TB?

There were significant changes between TB 102 and 115+. It is likely that a 
large number of users will be staying with 102 for quite a while. Version 
freezing is common in the Thunderbird community anyway, as various accessibility 
breaks are introduced, and people choose to remain with working versions.
However 102 was accessible and worked fine for all of the usual reasons people 
remained with earlier versions, so I would think this user could safely upgrade 
to 102 without effecting his familiarity with the software.

I would suggest that NVDA should try to continue to work with 102 for a while. 
Though not 60, of course, that is absurdly out of date.

But the "latest", 115, has not been sent through the automatic release channel 
for all users, and it is a significant "relearning" for most if they do go to 
it.

**Comment by Brian1Gaff** [comment]
Most are avoiding versions after 114, due to the new code base causing issues. I have not tried this myself. I prefer older ones on the win 10 machines.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by PeterLecky** [comment]
I upgraded Thunderbird to 102.14  which is last stable version distributed via update channel and i am last 24 hours without crash, so it seems that problem was fixed in Thunderbird.
