### ISSUE TITLE
2023.2 beta 1 - uppercase words being spelled when using codefactory eloquence or vocalizer

### ISSUE THREAD

**Issue by alexandretoco** [nvaccess/nvda#15233]
### Steps to reproduce:
1. choose to use codefactory eloquence or vocalizer as the synthecizer 
2. 2. for an example, press insert + n to open nvda's configuration menu. 
3. 3. navigate the menu using the arrow keys
4. the menu itens will be spelled 
### NVDA logs, crash dumps and other attachments:
I attached it in the end 
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2023.2 beta 1
#### Windows version:
windows 10
#### Name and version of other software in use when reproducing the issue:
codefactory drivers
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2023.1 the menus were read normally
#### If NVDA add-ons are disabled, is your problem still occurring?
I can't do this test because eloquence is an addon
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
not related
[nvda.log](https://github.com/nvaccess/nvda/files/12222245/nvda.log)

**Comment by CyrilleB79** [comment]
> @michaelDCurran this is fixed now. right?

@Adriani90, the PRs merge to beta do not trigger automatically the closing of the corresponding issues. These issues are closed automatically once the commit lands in master. Thus the current issue has only been closed when beta has been [merged to master](https://github.com/nvaccess/nvda/pull/15240).
