### ISSUE TITLE
NVDA 2023.2 beta 1 is not correctly reading the display on the win32 calculator

### ISSUE THREAD

**Issue by btman16** [nvaccess/nvda#15230]
### Steps to reproduce:
1. On a version of Windows that contains the win32 calculator such as Windows 7 or Windows 8.1 or Windows 10 LTSC, open calculator (calc.exe).
2. Type a calculation and press enter.
### Actual behavior:

NVDA is one result behind, so if I type 5+4, NVDA will speak 4 when I press enter, and I have to press the read current line command to hear the correct result, 9.
### Expected behavior:

NVDA should speak the displayed result without having to read the current line.
### NVDA logs, crash dumps and other attachments:
Here is the portion of the log after NVDA was initialized:
Speaking ['Command Prompt', 'terminal', CancellableSpeech (still valid), 'C:\\Users\\B>                                                                     ']
DEBUGWARNING - characterProcessing._getSpeechSymbolsForLocale (11:41:07.759) - MainThread (2404):
No symbol data for locale en_GB
IO - inputCore.InputManager.executeGesture (11:41:08.088) - winInputHook (2112):
Input: kb(laptop):c
IO - inputCore.InputManager.executeGesture (11:41:08.260) - winInputHook (2112):
Input: kb(laptop):a
IO - inputCore.InputManager.executeGesture (11:41:08.338) - winInputHook (2112):
Input: kb(laptop):l
IO - inputCore.InputManager.executeGesture (11:41:08.447) - winInputHook (2112):
Input: kb(laptop):c
IO - inputCore.InputManager.executeGesture (11:41:08.604) - winInputHook (2112):
Input: kb(laptop):enter
IO - speech.speech.speak (11:41:08.654) - MainThread (2404):
Speaking ['C:\\Users\\B>                                                                     ']
IO - speech.speech.speak (11:41:08.879) - MainThread (2404):
Speaking ['Calculator', CancellableSpeech (still valid)]
IO - speech.speech.speak (11:41:08.910) - MainThread (2404):
Speaking ['dialog', 'Running History\nMemory\nResult 0 \n0', CancellableSpeech (still valid)]
IO - speech.speech.speak (11:41:08.910) - MainThread (2404):
Speaking ['Result', '0 ', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (11:41:11.645) - winInputHook (2112):
Input: kb(laptop):3
IO - inputCore.InputManager.executeGesture (11:41:11.879) - winInputHook (2112):
Input: kb(laptop):.
IO - speech.speech.speakTypedCharacters (11:41:11.910) - MainThread (2404):
typed word: 3
IO - inputCore.InputManager.executeGesture (11:41:12.473) - winInputHook (2112):
Input: kb(laptop):8
IO - inputCore.InputManager.executeGesture (11:41:12.613) - winInputHook (2112):
Input: kb(laptop):8
IO - inputCore.InputManager.executeGesture (11:41:13.254) - winInputHook (2112):
Input: kb(laptop):-
IO - speech.speech.speakTypedCharacters (11:41:13.285) - MainThread (2404):
typed word: 88
IO - inputCore.InputManager.executeGesture (11:41:13.707) - winInputHook (2112):
Input: kb(laptop):3
IO - inputCore.InputManager.executeGesture (11:41:13.863) - winInputHook (2112):
Input: kb(laptop):.
IO - speech.speech.speakTypedCharacters (11:41:13.879) - MainThread (2404):
typed word: 3
IO - inputCore.InputManager.executeGesture (11:41:14.160) - winInputHook (2112):
Input: kb(laptop):1
IO - inputCore.InputManager.executeGesture (11:41:14.317) - winInputHook (2112):
Input: kb(laptop):1
IO - inputCore.InputManager.executeGesture (11:41:14.520) - winInputHook (2112):
Input: kb(laptop):enter
IO - speech.speech.speak (11:41:14.520) - MainThread (2404):
Speaking ['3.11 ']
IO - inputCore.InputManager.executeGesture (11:41:15.145) - winInputHook (2112):
Input: kb(laptop):escape
IO - speech.speech.speak (11:41:15.145) - MainThread (2404):
Speaking ['0.77 ']
IO - inputCore.InputManager.executeGesture (11:41:15.817) - winInputHook (2112):
Input: kb(laptop):escape
IO - speech.speech.speak (11:41:15.817) - MainThread (2404):
Speaking ['0 ']
IO - inputCore.InputManager.executeGesture (11:41:16.895) - winInputHook (2112):
Input: kb(laptop):alt+f4
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (11:41:16.910) - MainThread (2404):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUG - appModuleHandler.cleanup (11:41:16.910) - MainThread (2404):
application calc closed
IO - speech.speech.speak (11:41:16.926) - MainThread (2404):
Speaking ['Command Prompt', 'terminal', CancellableSpeech (still valid), 'C:\\Users\\B>                                                                     ']
IO - inputCore.InputManager.executeGesture (11:41:17.801) - winInputHook (2112):
Input: kb(laptop):NVDA+q
IO - speech.speech.speak (11:41:17.895) - MainThread (2404):
Speaking ['Exit NVDA', 'dialog', CancellableSpeech (still valid)]
IO - speech.speech.speak (11:41:17.895) - MainThread (2404):
Speaking ['What would you like to do?', 'combo box', 'Exit', 'collapsed', 'Alt+', CharacterModeCommand(True), 'd', CharacterModeCommand(False), CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (11:41:19.176) - winInputHook (2112):
Input: kb(laptop):downArrow
IO - speech.speech.speak (11:41:19.207) - MainThread (2404):
Speaking ['Restart']
IO - inputCore.InputManager.executeGesture (11:41:19.801) - winInputHook (2112):
Input: kb(laptop):enter
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (11:41:19.801) - MainThread (2404):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUG - core.triggerNVDAExit (11:41:19.817) - MainThread (2404):
_doShutdown has been queued
IO - speech.speech.speak (11:41:19.817) - MainThread (2404):
Speaking ['Command Prompt', 'terminal', CancellableSpeech (still valid), 'C:\\Users\\B>                                                                     ']
DEBUG - core._terminate (11:41:19.817) - MainThread (2404):
Terminating updateCheck
DEBUG - core._terminate (11:41:19.817) - MainThread (2404):
Terminating watchdog
DEBUG - core._terminate (11:41:19.817) - MainThread (2404):
Terminating globalPluginHandler
DEBUG - core._closeAllWindows (11:41:19.832) - MainThread (2404):
destroying system tray icon and menu
DEBUG - core._closeAllWindows (11:41:19.832) - MainThread (2404):
destroying main frame during exit process
DEBUG - core._startNewInstance (11:41:19.832) - MainThread (2404):
Starting new NVDA instance: NewNVDAInstance(filePath='C:\\Program Files (x86)\\NVDA\\nvda.exe', parameters='', directory='C:\\Program Files (x86)\\NVDA')
INFO - core.main (11:41:19.911) - MainThread (2404):
Exiting
DEBUG - core.triggerNVDAExit (11:41:19.911) - MainThread (2404):
NVDA has already been triggered to exit safely.
DEBUG - core._terminate (11:41:19.911) - MainThread (2404):
Terminating gui
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._saveSpecificSettings (11:41:19.911) - MainThread (2404):
Saved settings for NVDAHighlighterSettings
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._saveSpecificSettings (11:41:19.911) - MainThread (2404):
Saved settings for ScreenCurtainSettings
DEBUG - fileUtils.FaultTolerantFile (11:41:19.911) - MainThread (2404):
C:\Users\B\AppData\Roaming\nvda\nvda.ini22foh52f.tmp
INFO - config.ConfigManager.save (11:41:19.942) - MainThread (2404):
Base configuration saved
DEBUG - core._doLoseFocus (11:41:19.942) - MainThread (2404):
calling lose focus on object with focus
DEBUG - core._terminate (11:41:19.942) - MainThread (2404):
Terminating treeInterceptorHandler
DEBUG - core._terminate (11:41:19.942) - MainThread (2404):
Terminating IAccessible support
DEBUG - core._terminate (11:41:19.942) - MainThread (2404):
Terminating UIA support
DEBUGWARNING - UIAHandler.UIAHandler.terminate (11:41:20.145) - MainThread (2404):
Timeout or error while waiting for UIAHandler MTA thread
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating Legacy winConsole support
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating Java Access Bridge support
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating app module handler
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating tones
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating touchHandler
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating keyboard handler
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating mouseHandler
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating inputCore
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating vision
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating brailleInput
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating braille
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating speech
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating bdDetect
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating hwIo
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating addonHandler
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating garbageHandler
DEBUG - core._terminate (11:41:20.145) - MainThread (2404):
Terminating NVDAHelper
DEBUG - core.main (11:41:20.161) - MainThread (2404):
core done
INFO - __main__ (11:41:20.176) - MainThread (2404):
NVDA exit

#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2023.2 beta 1
#### Windows version:
Windows 8.1 64-bit
#### Name and version of other software in use when reproducing the issue:
No other software is being used, other than Windows Calculator.
#### Does the issue still occur after restarting your computer?
I have not tried rebooting yet, but I recently rebooted this machine before reproducing this issue.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2023.1 works correctly.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by Adriani90** [comment]
cc: @josephsl

**Comment by josephsl** [comment]
Hi, I don’t think it has to do with Calculator ap module changes is (applicable to modern Calculator) in 2023.2 beta. Thanks.

**Comment by seanbudd** [comment]
Can you confirm which version of Windows 10 you can reproduce this with?
Note that we are no longer actively supporting Windows 7 / 8 issues.

**Comment by josephsl** [comment]
Hi, Win32 Calculator is available in Windows 10 Enterprise LTSB/LTSC (1507, 1607, 1809, 21H2) and Server 2016/2019/2022 (will test if this is reproducible in Server Insider Preview). Thanks.

**Comment by wmhn1872265132** [comment]
This problem also exists on Windows 10 LTSC 2021 system, Windows 10 21H2 (x86) build 19044.3324

**Comment by lukaszgo1** [comment]
I can confirm this issue still occurs in the old Win32 calculator. Bisect shows that it has been introduced by #14708.
I'll have to verify ,but my hypothesis after reading the code is that this worked before only by chance as follows:
1. User pressed a key which should cause NVDA to announce updated display
2. The gesture was sent to the application
3. NVDA went to sleep
4. At the time it wake up the new value was written to the control, and therefore it could be announced to the user

After #14708 point 3 no longer occurs, therefore at the time when the object is spoken NVDA has not yet processed the change to the control.
It would be good not to rely on a fragile mechanism for detecting changes if at all possible.
cc @jcsteh

**Comment by lukaszgo1** [comment]
@btman16  @wmhn1872265132  Could you please download [this try buld](https://ci.appveyor.com/api/buildjobs/g07tm2h2agdlnvly/artifacts/output%2Fnvda_snapshot_pr15377-29075%2C6328ae16.exe), test calculator under the version of Windows you have and share the results? This is from PR #15377 .

**Comment by btman16** [comment]
Hello,

This seems to have fixed it for me.

Thanks,

Brandon

On 9/5/23, Łukasz Golonka ***@***.***> wrote:
> @btman16  @wmhn1872265132  Could you please download [this try
> buld](https://ci.appveyor.com/api/buildjobs/g07tm2h2agdlnvly/artifacts/output%2Fnvda_snapshot_pr15377-29075%2C6328ae16.exe),
> test calculator under the version of Windows you have and share the results?
> This is from PR #15377 .
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/15230#issuecomment-1707299136
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
“Be what you are. This is the first step towards becoming better than you are.”
– J. C. Hare & A. W. Hare

**Comment by lukaszgo1** [comment]
Thanks for you testing. This fix should be included in 2023.3.

**Comment by btman16** [comment]
Hi,

No worries, and thanks for your assistance in getting the issue fixed.

Brandon

On 9/6/23, Łukasz Golonka ***@***.***> wrote:
> Thanks for you testing. This fix should be included in 2023.3.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/15230#issuecomment-1708009667
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
“Be what you are. This is the first step towards becoming better than you are.”
– J. C. Hare & A. W. Hare
