### ISSUE TITLE
NVDA should not read submenu for certain aria-haspopup values

### ISSUE THREAD

**Issue by alexstine** [nvaccess/nvda#15244]
### Steps to reproduce:

1. Start NVDA.
2. Build an HTML document with the `aria-haspopup="dialog"` attribute.
3. Open the document in Firefox or Chrome.
4. Notice how NVDA announces submenu instead of dialog.

> button  subMenu    Button Text

### Actual behavior:

Posted above.

### Expected behavior:

I would expect to hear a phrase more closely related to dialogs, not a submenu. MDN docs covers how the `aria-haspopup` attribute can take a value of dialog and a few others. Sample of what I expect to hear.

> button  dialogTrigger    Button Text

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-haspopup

#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2023.1.0.27913.
#### Windows version:
Windows 10 Professional.
#### Name and version of other software in use when reproducing the issue:
Google Chrome, Firefox.
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by Adriani90** [comment]
This is fixed in alpha and beta versions of NVDA and will reach NVDA 2023.2. Closing.
