### ISSUE TITLE
Error when help unavailable

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#15257]
### Steps to reproduce:
* In Add-on Store, install "10dita" (2023.1) and "Audiocinemateca para NVDA" (1.1)
* Restart NVDA and reopen the Addon-Store
* In installed add-ons list, select 10dita and open Help menu item
* In installed add-ons list, select audiocinemateca and open Help menu item

### Actual behavior:
For 10dita, nothing happens and the following error is logged:
```
ERROR - unhandled exception (21:53:49.722) - MainThread (23976):
Traceback (most recent call last):
  File "gui\_addonStoreGui\controls\actions.pyc", line 37, in _menuItemClicked
  File "gui\_addonStoreGui\viewModels\store.pyc", line 240, in helpAddon
TypeError: startfile: filepath should be string, bytes or os.PathLike, not NoneType
```

It's because there is no help at all in this add-on.

For audiocinemateca, the same type of error message is logged and nothing happens either. It's because there is only a help (readme) file in the "es" folder and I am using NVDA in French (actually "fr_FR" coming from Windows)

### Expected behavior:
* Help menu item should not be present in the menu if the add-on has no help (10dita)
* For audiocinemateca, help menu item should not be present in the menu if the add-on has no help in NVDA's language (fr_FR), or countryless eqivalent language ("fr") or English

For audiocinemateca, it would be still better to open the only available help file, i.e. the Spanish one. However what should we do if my NVDA is in French and if the add-on has help in Italian and in Spanish, but nor in French or in English? Should we choose a language randomly?

### NVDA logs, crash dumps and other attachments:

```
ERROR - unhandled exception (21:53:49.722) - MainThread (23976):
Traceback (most recent call last):
  File "gui\_addonStoreGui\controls\actions.pyc", line 37, in _menuItemClicked
  File "gui\_addonStoreGui\viewModels\store.pyc", line 240, in helpAddon
TypeError: startfile: filepath should be string, bytes or os.PathLike, not NoneType
```

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
NVDA 2023.2beta1
#### Windows version:
Windows 10 2004 (AMD64) build 19041.388

#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Not tested, probably yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A
#### If NVDA add-ons are disabled, is your problem still occurring?
N/A
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested, unrelated.

**Comment by seanbudd** [comment]
>For audiocinemateca, it would be still better to open the only available help file, i.e. the Spanish one. However what should we do if my NVDA is in French and if the add-on has help in Italian and in Spanish, but nor in French or in English? Should we choose a language randomly?

I think this would be atypical of NVDA. We generally don't fall back to languages other than English. An english basefile is expected if add-on authors want fallback translatable strings or documentation.
