### ISSUE TITLE
Add-on store list shares translatable strings with tabs causing accelerator keys to appear on tab names

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#15258]
@CyrilleB79 what could you say about this?
### Steps to reproduce:
* Updatable &add-ons
* Installed &add-ons
* Available &add-ons
* Installed incompatible &add-ons
### Actual behavior:
For example, translating "Updatable &add-ons" into Simplified Chinese is "可更新的插件(&A)".
The accelerator key (A) also appears on each tab name.
### Expected behavior:
Accelerators on the list of add-ons are important, but including accelerators on each tab name is clearly wrong.
I had to remove the accelerator key from the Simplified Chinese translation.
### NVDA logs, crash dumps and other attachments:
None
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-28841,a85afcef （2023.3.0.28841）
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3208
#### Name and version of other software in use when reproducing the issue:
NVDA
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment]
Good point @cary-rowen ! I had not in mind the Chinese way to define shortcuts anymore when writing #15103, sorry.

I can see many options:
1. Duplicate the 4 strings: one for the tab (without the accelerator) and one for the list with the accelerator.
   Drawback: Translators will have to pay attention to use the same translation if possible for a string without accelerator and its matching string with accelerator.
2. Use a single string ("&Add-ons") for the list.
   Drawback: The content of the list is less clear for users.
3. Improve the algorithme to transform the string with accelerator in string without accelerator: If the string ends with " (&x)" (where x is any letter) remove this part, else remove only the "&".
   Drawback: Robustness: Are there only English and Chinese way to define accelerator? Or are there other unexpected ways?

@seanbudd, what is your opinion on this?

**Comment by seanbudd** [comment]
I think option 1 is probably the most robust. We can add a note for translators that these should match.
