### ISSUE TITLE
Capital pitch change depends on pitch setting, should check for PitchCommand in supportedCommands instead

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#15262]
Note: as the issue below is only visible in source, I decided not to fill in the issue template here. I'm pretty sure it is a small oversight from speech refactor. Therefore it might be helpful to have @jcsteh's opionion about this.

When implementing a synthesizer driver, there are two ways to change pitch:

1. Change the pitch setting
2. Send a pitch command that changes the pitch for the duration of the sequence or until there is a new pitch command.

Capital pitch change uses pitch commands to change pitch for capital letters. When doing this, it calls isSupported("pitch") on the driver, which returns True when the pitch setting is supported. However in order to support capital pitch changes, the driver should implement support for the PitchCommand instead.

Therefore, we should change all situations where isSupported("pitch") is called to generate a pitch command to check whether the PitchCommand is in supportedCommands.

**Comment by jcsteh** [comment]
Yeah, that's reasonable. I guess I figured a driver which supports the pitch setting is likely to also support the pitch command, but I guess those two things aren't necessarily correlated.
