### ISSUE TITLE
User request: Ability to sort add-on store by columns (name, publisher, status, etc)

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#15277]
### Is your feature request related to a problem? Please describe.

The add-on store (as in NVDA 2023.2 Beta 2) displays add-ons in a table with headings such as "name", "publisher" and "status", among others.

These are sorted by add-on name by default.  This is useful in many situations, butit would also be useful if you could sort by the other column headings as well.  That way you could see all add-ons by a particular publisher.

### Describe the solution you'd like

A way to navigate to, and sort by, column headings.

### Describe alternatives you've considered

This is currently available to mouse users by clicking on the column headings.

### Additional context

Initially requested by a user via Twitter - https://twitter.com/kool_turk/status/1688782747203227648 - that request included being able to sort by date.  I created an issue for a date column as #15278.

**Comment by CyrilleB79** [comment]
Note that it is already possible, even if not very smooth. Here are the steps, assuming that your review cursor follows the focus (which is the default):
* Focus the add-on list
* Press Home key to select the first add-on
* Change review mode to screen review (NVDA+PavNum7)
* Move review cursor to previous line (PavNum7). This way, the review cursor is on the headers line
* Change review mode to object review (NVDA+PavNum3). This way, the header of the first column (name) is selected as navigator object.
* Use object navigation to move to other headers with NVDA+PavNum4/6. E.g. three times NVDA+PavNum6 to move nav obj to author
* Execute default action on navigator object with NVDA+PavNumEnter

Anyway, this request does not seem specific to the add-on store. It would be beneficial for any list view which have no tab stop on the columns headers. I have not checked if there is already an issue open for this.

**Comment by Adriani90** [comment]
> Anyway, this request does not seem specific to the add-on store. It would be beneficial for any list view which have no tab stop on the columns headers. I have not checked if there is already an issue open for this.

There is no open request on that as far as I know.

**Comment by Adriani90** [comment]
I propose to consider the difference between sorting and filtering. I think sorting a list by name, publisher, and maybe last updated date if implemented, make most sense. Enabled or disabled as well for convenience, although I think filtering by status instead of sorting makes more sense otherwise we have to introduce a lot of columns due to the high number of different statuses.

**Comment by Adriani90** [comment]
See also discussion in #15860.

**Comment by nvdaes** [comment]
@CyrilleB79 , I can use the procedure mentioned by you on Windows 10, but this doesn't work on my computer using Windows 11 with NVDA 2024.4beta2.
Seems that the col click event is not triggered.

**Comment by CyrilleB79** [comment]
> @CyrilleB79 , I can use the procedure mentioned by you on Windows 10, but this doesn't work on my computer using Windows 11 with NVDA 2024.4beta2. Seems that the col click event is not triggered.

Oh, too bad...
Alternatively, you may move the mouse to nav object (NVDA+numpad/) and click the mouse (pavnum/); but this becomes still less smooth.

**Comment by nvdaes** [comment]
Thanks Cyrille, though the mouse approach seems not to work. I'm working in a pr to sort add-ons by new, and I think that it should work well, but testing is difficult from the gui, and I don't know if we should create a combo box or what.

**Comment by nvdaes** [comment]
FinallyI have been able to sort columns from the gui. The trick is to move the mouse to the object, and then press NVDA+enter.

**Comment by nvdaes** [comment]
I'll try to create a PR for this. I'm working to sort add-ons by new, but doing it with object navigation is difficult and may not be consistent between different computers, may be due to settings or whatever.
I would like to set the date column as the default for sorting, but since for now add-ons don't have a date, and sorting them by display name and then by date has problems when preforming the remove action, I think it's better to haye an easy way to sort columns too. I'm thinking on adding a combo box to the filtered controls.

**Comment by nvdaes** [comment]
The pull request is linked to this issue.
A combo box is placed after the store tabs, before the channel combo box. The shortcut key is alt+m.
Please, feel free to test and provide feedback or code reviews.
