### ISSUE TITLE
Error on initialization when NVDA is not able to find Braille display

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#15287]
### Steps to reproduce:
Restart NVDA.

### Actual behavior:

Clean, error-free initialization.

### Expected behavior:

Error each time.

### NVDA logs, crash dumps and other attachments:
INFO - brailleInput.initialize (21:35:15.938) - MainThread (4228):
Braille input initialized
INFO - braille.initialize (21:35:15.938) - MainThread (4228):
Using liblouis version 3.25.0
INFO - braille.initialize (21:35:15.938) - MainThread (4228):
Using pySerial version 3.5
ERROR - braille.BrailleHandler.setDisplayByName (21:35:15.964) - MainThread (4228):
Error initializing display driver 'brailliantB'
Traceback (most recent call last):
  File "braille.pyc", line 2179, in setDisplayByName
  File "braille.pyc", line 2246, in _setDisplay
  File "braille.pyc", line 2216, in _switchDisplay
  File "extensionPoints\util.pyc", line 216, in callWithSupportedKwargs
  File "brailleDisplayDrivers\brailliantB.pyc", line 125, in __init__
RuntimeError: No display found
INFO - braille.BrailleHandler._setDisplay (21:35:16.005) - MainThread (4228):
Loaded braille display driver 'noBraille', current display has 0 cells.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.2 Beta 2
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
I had once connected a Brailliant with NVDA on this computer but that was a couple weeks ago. The first field in NVDA's Braille Settings reads "No braille" as expected. Finally, I should note that I don't know if this error has any user-facing implications.

#### Does the issue still occur after restarting your computer?
Not tested
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not tested
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested

**Comment by Brian1Gaff** [comment]
Does this in fact matter? In other parts of nvda if something cannot be done, it silently just resets to what might be considered a sensible  default, which is what seems to occur here.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by seanbudd** [comment]
This is not an issue which affects the user, closing as invalid
