### ISSUE TITLE
Enhances for the Add-On Store

### ISSUE THREAD

**Issue by AppleUser03** [nvaccess/nvda#15292]
### Is your feature request related to a problem? Please describe.
When I browse the Add-On Store there are very few add-ons available. I know that is possible to install add-ons from an external source such as a website that talks about NVDA add-ons, but in this way I have to control periodically if a new version of the addon has been released. Also, when I find an add-on that interests me, I would like to know if it works well or not, for example by reading other user's experience.
### Describe the solution you'd like
To resolve the first problem, I would like to have the possibility to add external repositories directly into the Add-On Store, so I can install add-ons that are not distributed in the official repository and update then automatically when a new version is available. For the second problem, I'd like to have the possibility to read other user's reviews about the add-ons and also write my own reviews so others can read them.

**Comment by seanbudd** [comment]
These are out of scope for the add-on store and will not be included in NVDA
