### ISSUE TITLE
Unable to write some characters with Braille Sense in french

### ISSUE THREAD

**Issue by jf-fr-git** [nvaccess/nvda#15306]
### Is your feature request related to a problem? Please describe.
With a Hims BrailleSense 6, in terminal mode, four braille combinations cannot be performed on the braille keyboard. 
The corresponding combinations are occupied by the following NVDA commands: 
- dots 2-7: alt left arrow 
- dots 5-7: alt right arrow 
- dots 2-3-7: alt up arrow 
- dots 5-6-7: alt down arrow 

### Describe the solution you'd like
I would like to be able to type these four braille combinations with the braille keyboard, because they correspond to the following characters in the French (unified) computer braille table 8 dots: 
- dots 2-7: Å (LATIN CAPITAL LETTER A WITH RING ABOVE, decimal 197)
- dots 5-7: ‹ (SINGLE LEFT-POINTING ANGLE QUOTATION MARK, decimal 8249)
- dots 2-3-7: £ (POUND SIGN, decimal 163)
- dots 5-6-7: > (GREATER-THAN SIGN : decimal 62)

**Comment by CyrilleB79** [comment]
@leonardder any idea why these braille chords are taken by NVDA shortcuts?

PS: @jf-fr-git congratulation for opening your first ticket!

**Comment by leonardder** [comment]
I don't know why these are bound, but I agree they should be removed.

**Comment by CyrilleB79** [comment]
@leonardder you seem to be the author of the commit which introduced the hims driver, probably on behalf of @BabbageCom.

Who were your contact? Or may someone else at @BabbageCom answer? Maybe @FalkoBabbage?

It's surely a good idea to remove such gestures. But the manufacturer would probably prefer to bind these shortcuts to another chord gesture. This would not make sense to have no predefined gesture for alt+arrows but predefined gestures for alt+shift+arrows.

@jf-fr-git or any user of Braille Sense, you may also suggest logical 4 alternative gestures for alt+arrws if you have an idea.

**Comment by KihunJang1981** [comment]
BrailleSense 6 has alt and control key on both sides of space.
I think that develop assigne alt-dot-5 key. And this key send the dots-5-7 key.
I will change alt-dot-5 key in the BrailleSense 6. 
And EdKweon will change NVDA map for math alt-left arrow key.
Thank you.
