### ISSUE TITLE
Bug in MSDE (Code Editor) pressing a Cursor Routing Key

### ISSUE THREAD

**Issue by Friedhard-Michael** [nvaccess/nvda#15302]
### Steps to reproduce:
1. Start NVDA with Braille and Speech.
2. Open Excel or Word with or without a document open.
3. Hit Alt+F11 and open/create a Code Module.
4. Review your Code and press a Routing Key on your Braille Display at a specific Braille cell.
### Actual behavior:

1. the Cursor isn't routed.
2. The application would terminate without warning.
3. NVDA will not freeze or terminate.
### Expected behavior:

Pressing a Routing key on a specific Braille cell would move the Cursor to that very cell.
### NVDA logs, crash dumps and other attachments:
[nvda-Bug_inMicrosoft_Vb.txt](https://github.com/nvaccess/nvda/files/12359937/nvda-Bug_inMicrosoft_Vb.txt)

#### NVDA installed/portable/running from source:
NVDA installed
#### NVDA version:
NVDA version 2023.2beta3

#### Windows version:
Microsoft Windows Version 22H2 (Build 19045.3324)

#### Name and version of other software in use when reproducing the issue:
Microsoft® Word LTSC MSO (16.0.14332.20546) 64-Bit
#### Other information about your system:
CPU-Typ: AMD Ryzen 5 3600 6-Core 
Processor , Rev. 28928
BIOS-Version: ALASKA - 1072009 F50 Ameri
Grafics (Mode): NVIDIA GeForce GT 610
Screen Resolution: 1440x900x16m (32 bit) 
COM-Ports: 1 LPT-Ports: 0
#### Does the issue still occur after restarting your computer?
Yes, it does.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The error occurs starting with NVDA version 2021.1 to version 2023.2 Beta 3,
with same behaviour.
#### If NVDA add-ons are disabled, is your problem still occurring?
I've just tested it recently with Start Option "--disable-addons" (wothout quotes).
Same behaviour!

**Comment by CyrilleB79** [comment]
Also, please complete all the fields of the template.

More specifically, the following:
"Have you tried any other versions of NVDA? If so, please report their behaviors."

Knowing explicitly if the issue is present in 2023.1 would be very useful.

**Comment by Adriani90** [comment]
@Friedhard-Michael I guess you are still having this issue with NVDA 2024.3 Beta4. Is this sorrect?

**Comment by Adriani90** [comment]
No updates from the initial author since more than 1 year upon request. Closing as abandoned. If you are still having this issue, please comment and we can reopen.
