### ISSUE TITLE
Fourth column of symbols.dic cannot be edited in new Symbol Pronunciation GUI.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1530]
**Reported by elliott94 on 2011-05-27 20:36**
The pauses that should be honoured when symbols such as parentheses and em-dashes are encountered only occur when a fourth column is (manually) added to symbols.dic and set to the value of "Always."  This cannot be achieved at this time while using the new "Punctuation/Symbol Pronunciation" dialog.

**Comment by jcsteh** [comment]
This was done in #5234.
