### ISSUE TITLE
Make the NVDA Add-Ons Manager Dialog window wider by default so that the first three columns can show in their entirety, or close to it.

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#15317]
### Is your feature request related to a problem? Please describe.
Yes, but only for a sighted assistant.  If you open Manage Add-Ons from the NVDA main menu, the dialog that opens is too narrow to allow the columns presented to be seen in their entirety.  This is not a huge problem, as the window can be widened, but it is so small to begin with that if its default dimensions horizontally were increased, that would not be necessary.  The most critical column is the version number, and that's consistently only partially visible.  It should be possible to show the add-on name, status, and version numbers fully for almost all add-ons.  Developers will likely remain cut off at the right.

### Describe the solution you'd like
To have that dialog open with a wider horizontal dimension and where the column widths for the first three columns in particular are increased such that the data is fully visible.

### Describe alternatives you've considered
None

### Additional context
None

**Comment by Qchristensen** [comment]
Hi Brian, as the Add-ons manager is being replaced with the add-on store in 2023.2, could you please check the latest NVDA 2023.2 Beta and confirm that the widths are correct in this? https://www.nvaccess.org/post/nvda-2023-2beta3/

![image](https://github.com/nvaccess/nvda/assets/15902216/1c4a48e7-d1e5-431d-a93a-0e4f331a08e5)
(I don't think I've ever tried putting an image in a comment, but if it works, that should be a screenshot of the add-on store on my computer.

**Comment by britechguy** [comment]
Quentin,

Your screenshot was successful, and that looks much better than what we
have now!

The addition of the detailed information box, on the right, is a huge plus,
too.

Thanks much for sending this along.

Brian

**Comment by seanbudd** [comment]
This is fixed by the add-on store
