### ISSUE TITLE
addonHandler.initTranslation() should be callable from scratchpad

### ISSUE THREAD

**Issue by mo29cg** [nvaccess/nvda#15318]
### Is your feature request related to a problem? Please describe.
Right now, if you call `addonHandler.initTranslation()` from the add on scratchpad, you get this error below.
```
addonHandler.AddonError: Code does not belong to an add-on package.
```

This is annoying. 
I frequently clone someone's addon repository and copy it to scratchpad directory and tweak it.   
But because of this error, I always need to comment out "addonHandler.initTranslation()" before start tweaking.
I think this is a waste of time for me and other add-on developers. 
It can just let it go without throwing an error and stop everything.

### Describe the solution you'd like
Do not throw an error, if `addonHandler.initTranslation()` is called within  scratchpad.

### Describe alternatives you've considered
Nothing

**Comment by beqabeqa473** [comment]
I think it is responsibility of addon developer to handle this exception.
This exception is logical and no one should make it to behave
otherwise, just because you don't want to correctly handle an
exception.

On 8/21/23, suzukix ***@***.***> wrote:
> ### Is your feature request related to a problem? Please describe.
> Right now, if you call `addonHandler.initTranslation()` from the add on
> scratchpad, you get this error below.
> ```
> addonHandler.AddonError: Code does not belong to an add-on package.
> ```
>
> This is annoying.
> I frequently clone someone's addon repository and copy it to scratchpad
> directory and tweak it.
> But because of this error, I always need to comment out
> "addonHandler.initTranslation()" before start tweaking.
> I think this is a waste of time for me and other add-on developers.
> It can just let it go without throwing an error and stop everything.
>
>
> ### Describe the solution you'd like
> Do not throw an error, if `addonHandler.initTranslation()` is called within
> scratchpad.
>
> ### Describe alternatives you've considered
> Nothing
>
> ### Additional context
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/15318
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by seanbudd** [comment]
This is intentional behaviour. We should add documentation to the developerGuide and the function itself to warn developers on how it should be used.

For example, this is how NVDA remote uses the function

```py
try:
	addonHandler.initTranslation()
except addonHandler.AddonError:
	log.warning(
		"Unable to initialise translations. This may be because the addon is running from NVDA scratchpad."
	)
```

**Comment by CyrilleB79** [comment]
@seanbudd, if all add-ons replace
`addonHandler.initTranslation()`
by:
```
try:
	addonHandler.initTranslation()
except addonHandler.AddonError:
	log.warning(
		"Unable to initialise translations. This may be because the addon is running from NVDA scratchpad."
	)
```
I don't understand the point of leaving the responsibility to the author of the add-on to filter this exception.

Also, NVDA could also check if the scratchpad is in the file path.

Maybe I have missed something. Could you explain when an add-on should just use `addonHandler.initTranslation()` statement and when an add-on should instead use the pattern of NVDA remote? This would help me differentiate the two use cases. Thanks.

**Comment by beqabeqa473** [comment]
hi @CyrilleB79.

scratchpad is ment to be a testing pollygon while developing something and if someone for some reason wishes to use my addon in scratchpad, it is their problem from beginning to the end.
But if for some reason they need it, they have a way to comment out this particular line or catch the exception.
I fon'y understand why nvaccess should make assumbtions where code is running. It is logical that addonHandler.initTranslations method is ment to be used in addons, but code running in scratchpad is not an addon and here logical exception occures.
I cannot get a point of that.

**Comment by mo29cg** [comment]
I think the nvda remote pattern with an addition of path checking should be natively implemented in `initTranslation()`.

It's what every add-ons should do in them, so why not natively?

I don't see downside of doing that way, it'll save every future add-on developer's time.

**Comment by seanbudd** [comment]
We don't want to have that function called from NVDA core. We also don't want it called from the scratchpad.
The best way to prevent that from happening is to raise an error when it happens.

I don't really think every add-on necessarily needs to do this, it's on whoever is adding the code  to the scratchpad to not call the function.
Handling the exception e.g. how remote does this is just a preference, and to make devs timem easier.
A better way of handling it is to never catch the exception in production code, only in development.

```
try:
	addonHandler.initTranslation()
except addonHandler.AddonError:
	if debugMode:
		log.warning(
			"Unable to initialise translations. This may be because the addon is running from NVDA scratchpad."
		)
	else: raise
```

**Comment by CyrilleB79** [comment]
@seanbudd your explanation is clear.

In this case, should this issue just be closed as WONTFIX given your last comment?

**Comment by seanbudd** [comment]
As mentioned in my first comment, we think the documentation should be improved to make the usage clear

**Comment by CyrilleB79** [comment]
Oh yes, sorry for closing.
