### ISSUE TITLE
error when opening outlood office 365 installed version

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#15322]
I am getting the following error when NVDA is waiting for outlook to open: OSError: [WinError -2147221021] Operation unavailable

**Comment by seanbudd** [comment]
Welcome @joshknnd1982 ,

We are unable to process this issue as it stands.

Please fill out the issue template fully.

Kind Regards,
NV Access Software Developers

**Comment by Adriani90** [comment]
this is certainly a duplicate of #8961, there are a lot of logs but my last comment there and the last comment from Quentin contain the most important information. This error does not really have a significant user impact, it might cause very old Office versions to freeze but not in Office 2016 or newer.
