### ISSUE TITLE
Add a new setting to object presentation category to exclude reporting of groupings when focussing elements

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#15324]
### Is your feature request related to a problem? Please describe.
NVDA reports groupings when entering them with the system focus (i.e. in settings dialogs like in Microsoft Office) and since #14878, NVDA reports groupings even when they don't have a name or a description. This leads to very inefficient navigation through menus and settings dialogs with nested groupings.

### Describe the solution you'd like
Allow the user to turn off reporting of groupings all together in the object presentation category. At least for me as an advanced user, I am not really interested in hearing those groupings every time I navigate around.

### Describe alternatives you've considered
Leave as is, but this might impact negatively user experience for advanced users.

### Additional context
n/a

**Comment by michaelDCurran** [comment]
@Adriani90  How about a tri-state option, which allows  speaking all groupings, only labeled groupings, or no groupings? The reason for allowing only labeled groupings would allow for the original behaviour before 23.2. 
The alternative of course, if speaking of unlabeled groupings is really unpopular, then perhaps we should just revert that.

**Comment by Adriani90** [comment]
I agree with the tri-state option approach, although I try to find an use case where unlabeled groupings play a role for the user. In my experience at least it makes sense to have all labeled groupings reported, only when I am able to jump between groupings (i.e. like in ribbon menus with ctrl+left and right arrow keys). But I guess this is not possible to implement for every kind of menu or dialog style.

**Comment by XLTechie** [comment]
I would favor the approach suggested by @michaelDCurran. It seems the most 
flexible, without adding a large amount of additional explanation to users who 
may be fuzzy on the subject.

**Comment by Adriani90** [comment]
Ok I found some use cases in some MS Office dialogs, where the element label is only given through the group label, so turning off completely reporting of grouping is not gonna work since this will introduce accessibility issues on such elements.
How about only a check box that allow turning off only the reporting of unlabeled groupings? This will at least suppress some of the groupings being reported in menus etc.

I wonder if there is a way to identify elements with no label other than the group label, and introduce a state in NVDA that reports group labels only in that case?

**Comment by jcsteh** [comment]
Out of curiosity, when is reporting of unlabelled groupings useful? Are there practical examples? #14878 notes that this was requested, but it's unclear where this has a practical benefit to the user.

For what it's worth, I was just talking to a user (not on GitHub) using Outlook at work where there is a context menu with more than 10 unlabelled groupings, each containing only 1 item. It's making things very inefficient for him to do his job. I'm obviously aware that there are likely multiple angles to be considered here, but I figured this additional data point might be useful in making that decision.

**Comment by jcsteh** [comment]
If anyone is really annoyed by this, you can work around it temporarily by pasting the following snippet into the Python console whenever you restart NVDA. Disclaimer: if it breaks, you get to keep both pieces.

```
import baseObject; import controlTypes; import NVDAObjects; NVDAObjects.NVDAObject.presentationType = baseObject.CachingGetter(lambda self: self.presType_layout if self.role == controlTypes.role.Role.GROUPING and not self.name and self.positionInfo else NVDAObjects.NVDAObject._get_presentationType(self))
```

**Comment by Adriani90** [comment]
Yeah it makes work quite inefficient in all Microsoft office applications basically when using the context menu. I face this also every day at work. Maybe there is a corner use case I don't know of, maybe when designing accessible concept boards like in Miro or something like that, but at least we should be able to turn off reporting of unlabelled groupings in the object presentation settings.

**Comment by CyrilleB79** [comment]
Knowing the grouping in a context menu may be useful to use tab to jump from one group to another, i.e. in a context menu, press 3 times tab instead of 10 times downArrow.

Unfortunately, the groupings in Office menus contain very few items each one, which makes this approach almost useless.

What may be useful and much more invasive is to report unlabeled grouping after the menu item is reported. Unfortunately, this would create an inconsistent UX between labeled grouping and unlabeled ones, which is probably undesirable.
