### ISSUE TITLE
Adobe Acrobat crashes and NVDA freezes completely when opening a file

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#15321]
Note this might impact all 64 bit versions of Adobe Acrobat, I couldn't reproduce in 32 bit versions. With Jaws this issue does not occur.

### Steps to reproduce:
1. Open NVDA
2. , On a pdf file, press context menu and choose "open with Acrobat"
3. press arrow keys to navigate through the document, on my side Adobe is set to display the current page only.

### Actual behavior:
NVDA freezes and at least Adobe Acrobat crashes completely and exits. See attached NVDA log and Adobe crashdump. For the crashdump you have to remove the .txt ending in order to open the file.
[Acrobat.exe.16148.dmp.txt](https://github.com/nvaccess/nvda/files/12409094/Acrobat.exe.16148.dmp.txt)

Note this is not reproducible every time, but I could reproduce it reliably every 3 or 4 times I opened the file.

### Expected behavior:
No crash or freeze of NVDA or Adobe Acrobat.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-28861,705687b3 (2023.3.0.28861)

#### Windows version:
Windows 11 22 H2

#### Name and version of other software in use when reproducing the issue:
Adobe Acrobat DC 2023.003.20269 64bit

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
in earlier versions of NVDA I could reproduce it as well.

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
[log_nvda+adobe.txt](https://github.com/nvaccess/nvda/files/12409069/log_nvda%2Badobe.txt)

**Comment by seanbudd** [comment]
Is it a particular file causing this problem? We are unable to reproduce this.

Have you reported this to Adobe yet?

**Comment by Adriani90** [comment]
No, I was able to reproduce it on any file from time to time.
What does the crashdump say? I currently don't have the environment to check this myself and I think also lack of experience on checking the source of the crash.
But actually the NVDA log and the crashdump should give some indications  whether the crash is caused by NVDA or not.

**Comment by seanbudd** [comment]
I've attempted to analyse the crash dump but it doesn't yield any useful information as Adobe doesn't publish their debug symbols. You'll have to send the crash dump to them to investigate.

**Comment by Adriani90** [comment]
I reported the crash, how ever after down grading from adobe DC pro to the free Adobe Acrobat reader, the crash is not occuring anymore. I suspect there was something wrong with my license or something.
Closing as works for me.
