### ISSUE TITLE
Read only my highlighted texts outloud.

### ISSUE THREAD

**Issue by antdude** [nvaccess/nvda#15336]
### Is your feature request related to a problem? Please describe.
Yes. I only wanted NVDA to read my highlighted texts and not everything. For an example in Windows' Notepad with texts. I highlight some texts, with my mouse, and want NVDA to read those highlighted texts only. Nothing else.

### Describe the solution you'd like
Yes. I only wanted NVDA to read my highlighted texts and not everything. For an example in Windows' Notepad with texts. I highlight some texts, with my mouse, and want NVDA to read those highlighted texts only. Nothing else.

### Describe alternatives you've considered
Using 64-bit W10's Narrator, but it had the same problem.

### Additional context
None.

**Comment by seanbudd** [comment]
This is out of scope - this may be better implemented as an add-on or using alternative

**Comment by Adriani90** [comment]
Actually this is already possible even though the user experience is ok but not ideal.
Note, my solution works only in editing areas where selected text can be reported.

1. Make sure you have created a profile for the coresponding application (i.e. Notepad)
2. While you are focusing the application, press NVDA+s until you hear "speech mode off"
3. Select your text with the mouse or what ever
4. Press nvda+s twice until you hear "speech mode: talk"
5. Press nvda+shift+s to make NVDA report only the selected text
6. Press NVDA+s again to mute the speech and continue working without NVDA speaking.

Then repeat steps 4 to 6 every time you select a text.

@Qchristensen maybe this is something you could cover in an in process article or so?

**Comment by Qchristensen** [comment]
@Adriani90 your solution would probably be annoying to do regularly as a user, BUT would possibly be able to be turned into an add-on without too much difficulty.

In fact, the one scenario I get asked for more, is to have speech off generally, but hover the mouse over some text, press a keystroke and have that read.  For that too, I came up with a workaround - but like yours for this it was less than ideal - basically have the review cursor follow the mouse, then press numpad plus to read the object at the review cursor - which works, but on the web particularly it will ONLY read the current element, you can't trigger a "say all from this point".

Getting off track, but we could move this to a discussion if anyone is interested?
