### ISSUE TITLE
Caret navigation does not work fully in ThinBasic's ThinAir editor

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1533]
**Reported by oaron on 2011-05-30 21:20**
NVDA is not able to successfully track the cursor when navigating character by character in ThinBasics code editor, ThinAir.
Reading line by line seems to work, however using any other key to navigate, e.g. left and right arrow, home, end, page up or down, NVDA does not seem to follow the cursor.
ThinBasic's latest beta can be downloaded from here:
http://www.thinbasic.biz/projects/thinbasic/thinBasic_1.8.7.0.zip

Some info about the edit control:
Developer info for navigator object:
name: u"' Empty GUI script created on 05-30-2011 23:17:26 by  (ThinAIR)\r\n"
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_FOCUSED
Python object: <NVDAObjects.Dynamic_IAccessibleDisplayModelEditableTextWindowNVDAObject object at 0x05C3A8B0>
Python class mro: (<class 'NVDAObjects.Dynamic_IAccessibleDisplayModelEditableTextWindowNVDAObject'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.DisplayModelEditableText'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (201, 87, 1398, 748)
value: None
appModule: <'appModuleHandler' (appName u'thinair', process ID 10256) at address 5c3ae70>
TextInfo: <class 'displayModel.EditableTextDisplayModelTextInfo'>
windowHandle: 3738048
windowClassName: u'CodeSense'
windowControlID: 2150
windowStyle: 1375731712
windowThreadID: 11368
windowText: u"' Empty GUI script created on 05-30-2011 23:17:26 by  (ThinAIR)\r\n"
IAccessibleObject: <POINTER(IAccessible) ptr=0x8143ea8 at 5c47f80>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=3738048, objectID=-4, childID=0
IAccessible accRole: ROLE_SYSTEM_CLIENT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)

**Comment by ehollig** [comment]
I am not having issues navigating using caret navigation in this editor. It is possible that updates to the program resolved some of the problems. Closing. Please open another ticket with specific information on what is not working with this program if other problems persist.
Testing on Windows 10,1703.
The latest version of the program can be downloaded from http://www.thinbasic.com/index.php/download/thinbasic-1-9-16-17/
