### ISSUE TITLE
nvda 2023.2RC1: ERROR - _addonStore.dataManager._DataManager._getCachedInstalledAddonData

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#15345]
### Steps to reproduce:
NVDA+n, tools sub-menu, add-on store sub-menu.
- "add-on warning" dialog appears and an error is logged.
- accept by "OK"
- then at each "control+tab", the same error ocurs
this is the error:

ERROR - _addonStore.dataManager._DataManager._getCachedInstalledAddonData (15:40:20.086) - MainThread (5216):
Invalid cached installed add-on data
Traceback (most recent call last):
  File "_addonStore\dataManager.pyc", line 282, in _getCachedInstalledAddonData
  File "json\__init__.pyc", line 293, in load
  File "codecs.pyc", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 49: invalid continuation byte

### Expected behavior:

No error
#### NVDA installed/portable/running from source:
Nvda portable
#### NVDA version:
NVDA 2023.2RC1
#### Windows version:
W10 22h2
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No problem with 2023.2 beta
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
No tested

**Comment by CyrilleB79** [comment]
Thanks Paul for having opened this issue. I had seen it a few days ago, probably with NVDA 2023.2beta3, but had forgotten to write a report.
It is actually 100% reproducible.

I have not noticed any impact on UX; I have not investigated if there is one. I have been using all the beta versions (and even alpha before); I do not know if it may be due to older file format modified during the dev cycle.

In any case, @seanbudd I had thought that cached files were removed in case of error when loading the json. Isn't it the case?

**Comment by seanbudd** [comment]
This is likely caused to an add-on that was installed before beta2 was released.
Unfortunately the logging here needs to be improved slightly to include the filename causing the error.
Note that this error shouldn't effect you much, it just means that one of your installed add-ons will act as if it is been externally installed, as the add-on store information is corrupted.

Do you have git bash installed?
If so, can you confirm the results of the following?
```sh
# Change to NVDA add-on app data
cd ~/AppData/Roaming/nvda/addons
# list encoding of JSON files
file  --mime-encoding *.json
```

Alternatively, if you don't have git bash installed, please list the add-ons you have installed with the channel filtered to "EXTERNAL".
If you can find a file in `%APPDATA%/nvda/addons` that matches an add-on listed as external, you have found the culprit for the issue.
Can you confirm this add-on was installed before you installed beta2?
Feel free to delete this file to get rid of the error sound.

>In any case, @seanbudd I had thought that cached files were removed in case of error when loading the json. Isn't it the case?

We keep these files as it helps with debugging. If the add-on store cache of all add-ons is corrupt, we through it out as its easy to fetch a new cache. However specific add-ons we keep the file for debugging.
More info in: https://github.com/nvaccess/nvda/pull/15241#issuecomment-1661504854

**Comment by paulber19** [comment]
Hi.
 >Do you have git bash installed?
No.
 ># Change to NVDA add-on app data
I's no an installed NVDA, but aportable.
So I suppose that I must use "userConfig\addons".
 ># list encoding of JSON files
In "userConfig\addons", I found two json files:
addonUpdater.json
pcKbBrl.json
 >If you can find a file in %APPDATA%/nvda/addons that matches an add-on 
listed as external, you have found the culprit for the issue.
All add-ons are external.
 >Can you confirm this add-on was installed before you installed beta2?
I haven't installed an add-on since beta 2
 >Feel free to delete this file to get rid of the error sound.
By deleting both files, the error disappeared.
Deleting either file did not clear the error.

Best regards.
Paul.

**Comment by seanbudd** [comment]
Ah I guess both files were the culprit. Apologies for the inconvenience, the issue with locale and encoding wasn't picked up until the first beta, as translations weren't fully supported until then.

**Comment by CyrilleB79** [comment]
> This is likely caused by an add-on that was installed before beta2 was released. Unfortunately the logging here needs to be improved slightly to include the filename causing the error. Note that this error shouldn't effect you much, it just means that one of your installed add-ons will act as if it is been externally installed, as the add-on store information is corrupted.

I do not know if its intended. But these add-ons being listed as external cannot be migrated to add-on store, maybe because the version number is the same?
 
> Do you have git bash installed? If so, can you confirm the results of the following?
> 
> ```shell
> # Change to NVDA add-on app data
> cd ~/AppData/Roaming/nvda/addons
> # list encoding of JSON files
> file  --mime-encoding *.json

Listing the files like this, I can see that json files are encoded in us-ascii, utf-8 or iso-8859-1. The add-ons corresponding to files encoded in iso-8859-1 are actually listed as external in the add-on store. And removing the json encoded in iso-8859-1 fixes the errors in the log

> > In any case, @seanbudd I had thought that cached files were removed in case of error when loading the json. Isn't it the case?
> 
> We keep these files as it helps with debugging. If the add-on store cache of all add-ons is corrupt, we throw it out as its easy to fetch a new cache. However specific add-ons we keep the file for debugging. More info in: [#15241 (comment)](https://github.com/nvaccess/nvda/pull/15241#issuecomment-1661504854)

But will updates be proposed for such add-ons? If not, we should ask beta testers to remove all the json files from their config on all the lists where beta was advertised (and maybe also in NV Access news?).

**Comment by seanbudd** [comment]
>I do not know if its intended. But these add-ons being listed as external cannot be migrated to add-on store, maybe because the version number is the same?

Yeah - we only encouraging migrating if we don't know if it's an upgrade or downgrade due to the externally installed add-on not having a parseable version

>But will updates be proposed for such add-ons?
If an add-on is updated or re-installed, a new add-on store version file will be created. Is that what you meant here?

>If not, we should ask beta testers to remove all the json files from their config on all the lists where beta was advertised (and maybe also in NV Access news?).

I think this is overzealous, there's little user impact other than error dings in beta and slightly less add-on information.

**Comment by CyrilleB79** [comment]
> > But will updates be proposed for such add-ons?
> If an add-on is updated or re-installed, a new add-on store version file will be created. Is that what you meant here?

I was jujst wondering if a version with higher version number would appear in updatable add-on tab even if the json file of the current version is corrupted.

**Comment by seanbudd** [comment]
Yep it should - it will only not appear if we know for sure it's a downgrade, or the same version.
We could consider listing migrating as an option for the same version as well.
