### ISSUE TITLE
Find dialog and battery status changes not documented

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#15340]
Hi.

When performing a find with NVDA 2023.2rc1, I realise that the find dialog has changed. So, if I do a find on a page with no matches, the title of the dialog displays '0 matches', and it is a warning dialog. Previously, the title would be 'Find', with the dialog being an error dialog.

Also, when charging a system battery, when pressing NVDA_Shift+B, NVDA 2023.2rc1 states the percentage, followed by 'plugged in'. In older versions, NVDA would report 'charging'.

Were these changes added by mistake, on a whim or intentionally? If the latter two, why haven't they been documented?

**Comment by seanbudd** [comment]
These are PRs https://github.com/nvaccess/nvda/pull/14807 and https://github.com/nvaccess/nvda/pull/14765, they were considered small enough changes to not warrant a changelog entry.
