### ISSUE TITLE
Numbers displayed on separate lines in Chinese articles while reading PDF files in Firefox using NVDA.

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#15343]
When using NVDA to read PDF files in Firefox, there is an unexpected behavior where sentences, including both text and numbers, are split onto separate lines. 

### Steps to reproduce:
1. Launch Firefox.
2. Paste the following link into the address bar: https://www.twse.com.tw/staticFiles/news/news/tsecnews/ff8080818a025c1e018a2c039e6d0058.pdf
3. Open the PDF file by pressing Enter.
4. Begin reading the PDF file using NVDA.

### Actual behavior:

As you read through each line, you will notice that NVDA automatically splits sentences into separate lines.

中華民國
11
2
年
8
月
25
日
 
 
企劃研究部
 
 
本週發行量加權股價指數漲幅約為
0.61%
，上市股票總市值達
51.81
兆元。
 

根據臺灣證券交易所統計，
112
年
8
月
25
日發行量加權股價指數收盤為
16,481.58
點，較上週
(112
年
8
月
18
日
)
的
16,381.31
點上漲
100.27
點，漲幅約為
0.61%

### Expected behavior:

while reading pdf files, NVDA does not Split sentences (text and numbers) on to separate lines.

中華民國112年8月25日
企劃研究部
本週發行量加權股價指數漲幅約為0.61%，上市股票總市值達51.81兆元。
根據臺灣證券交易所統計，112年8月25日發行量加權股價指數收盤為16,481.58
點，較上週(112年8月18日)的16,381.31點上漲100.27點，漲幅約為0.61%，

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2023.2

#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3086
#### Name and version of other software in use when reproducing the issue:
Firefox version 117.0

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

**Comment by seanbudd** [comment]
This seems to be an issue with how the PDF was written. Line breaks are being rendered in the browser, not by NVDA

**Comment by seanbudd** [comment]
This may actually be a problem with Firefox

**Comment by surfer0627** [comment]
The relevant Firefox issue: [1850860](https://bugzilla.mozilla.org/show_bug.cgi?id=1850860#c0)

**Comment by Adriani90** [comment]
cc: @jcsteh

**Comment by jcsteh** [comment]
I've commented on the Firefox bug. There's nothing NVDA can do here and this would affect other screen readers equally, so I'm closing this. Anyone interested in following the progress of this should follow the Mozilla bug. Thanks.
