### ISSUE TITLE
Can't review message body when composing a message in Thunderbird

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1534]
**Reported by hurrikenny on 2011-05-31 03:27**
In mozilla thunderbird 3.1.1 when you go to send a new email after putting in youremail address and subject which you can review, once you tabl down to where you type your meial and typed it out, when you go to review it it just says blank like there is nothing there, how ever if you move the mouse across it it will say what it is you have typed.  Now and again it may let you review it in this section, mostly not.I am useing windows 7 64 bit and the latest snapshot 4362, I think it is.  You will see what I mean in this area.

**Comment by ehollig** [comment]
Anyone who is using thunderbird? CC @leonardder

**Comment by jcsteh** [comment]
NVDA's handling of Mozilla rich text editing (as used by the HTML composer) was completely refactored in #1668. Issues like this should be fixed as a result. Closing, but please comment if the problem persists.
