### ISSUE TITLE
NVDA 2023.2rc1 - CRITICAL error logged when ctrl+tabbing while an add-on is downloading

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#15347]
This is sort of a stress test of the Add-on Store trying to download a lot of add-ons.

### Steps to reproduce:
* Start a brand new NVDA (no personal config)
* Open Add-on Store
* Install all the add-ons starting with letters "T" and "U"
* Control+tab forth and back to leave the "available add-ons" tab and turn to it
* In the "T" or "U" add-ons, there are add-ons reported as "Available" (strangely); install them again

### Actual behavior:
First, it is strange that add-ons that have been installed are available again when turning in the "available add-ons" tab

Second, I get a CRITICAL error in the log. NVDA does not freeze nor crash, but I guess a CRITICAL is quite worrying in any case.

### Expected behavior:

First the add-ons that have been installed should all appear as Downloading or pending install.

Second, no CRITICAL error should occur.

### NVDA logs, crash dumps and other attachments:
[nvda.log](https://github.com/nvaccess/nvda/files/12478202/nvda.log)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.2rc1
#### Windows version:
Windows 10 21H2 (AMD64) build 19044.3324

#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Not tested
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A
#### If NVDA add-ons are disabled, is your problem still occurring?
N/A, but no add-on initially installed since the STR uses a brand new config.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested, unrelated.

**Comment by CyrilleB79** [comment]
And here is a simpler STR:
* Open add-on store
* Click Install in the context menu of Character information to install it
* Control+tab immediately (and as soon as possible) after this click
CRITICAL error occurs.

Here is the log: 
[nvda.log](https://github.com/nvaccess/nvda/files/12478340/nvda.log)

**Comment by seanbudd** [comment]
These logs are actually two separate issues
The log in the comment has: `File "gui\_addonStoreGui\viewModels\store.pyc", line 318, in _downloadComplete`

The log in the issue has: `File "_addonStore\network.pyc", line 126, in _done`
