### ISSUE TITLE
NVDA narrates graphic for button accessibility name

### ISSUE THREAD

**Issue by kolaps33** [nvaccess/nvda#15384]
### Steps to reproduce:
1. Run NVDA
2. Open the example 
 https://gf57rj.csb.app/
3. Navigate on "before test" button
4. Press TAB key and observe next button narration
5. Press TAB key and observe next button narration

### Actual behavior:
NVDA narration:
For 1st button: "call  graphic    Katri Athokas busy  button"
For 2nd button: "Katri Athokas busy  graphic    button"

### Expected behavior:
I would expect narration of "graphic" in the accessibility name

### Comment
When I toggle the mode with  NVDA key+Space into forms mode, then NVDA doesn't narrate graphic. 
I would expect the "graphic" narration when I browse the page(up/down arrow key), but when I use TAB key I wouldn't expect it... 
JAWS, Narrator doesn't narrate "graphic" in the button name.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2023.2rc1

#### Windows version:
OS Name	Microsoft Windows 11 Enterprise
Version	10.0.22621 Build 22621

#### Name and version of other software in use when reproducing the issue:
Chrome Version 116.0.5845.141 (Official Build) (64-bit)
Firefox 117.0 (64-bit)

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
yes 

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by seanbudd** [comment]
This is intended behaviour. Can you please explain the issue with reporting graphic in these situations? What negative user impact is there?
