### ISSUE TITLE
Add a button to copy NVDA version

### ISSUE THREAD

**Issue by alexstine** [nvaccess/nvda#15407]
### Is your feature request related to a problem? Please describe.

Currently, there is no easy way to copy the exact version number of NVDA without using alternate navigation techniques. This is a problem because submitting bug reports requires you to list specifics about your environment. The NVDA version is not easily accessible.

### Describe the solution you'd like

1. NVDA menu.
2. Help.
3. About.
4. Add a Copy Current Version button.

### Describe alternatives you've considered

N/A.

### Additional context

N/A.

**Comment by XLTechie** [comment]
While this is not a bad idea, I will just point out the Say Product Name and 
Version add-on, which has a copy function.
Open the NVDA menu, press NVDA+Shift+v twice fast, and it will copy NVDA's 
version.

https://is.gd/sayProdNAV

**Comment by alexstine** [comment]
It would be cool if this add-on was folded into the main release. Very useful feature. Thanks for sharing.

**Comment by alexstine** [comment]
Actually, it seems like the add-on only allows me to get my OS version. I really need a solution to return my current NVDA version. That exact build is hard to copy at this point.

**Comment by tspivey** [comment]
Press Ctrl-c in that dialog, then paste it somewhere.

**Comment by alexstine** [comment]
That is super embarrassing. Had no idea that would work in a dialog. Thanks.

**Comment by XLTechie** [comment]
I reiterate. Open the NVDA menu. While it's open, press NVDA+Shift+v twice.
That will get your NVDA version with the add-on.

I tested it again, to make sure I didn't break something in the last release. It 
still works.

That ctrl+c command to copy the whole text of the dialog, is a Windows thing. 
But it only works for certain kinds of dialogs. I had no idea it would work in 
that one--I don't know of any other NVDA dialog where it does.

**Comment by Brian1Gaff** [comment]
It would also be good to know what add ons are in fact enabled and their versions if this is a debug item that is useful.
Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by Brian1Gaff** [comment]
NonVisual Desktop Access (NVDA)
Version: 2023.2 (2023.2.0.29051)
URL: https://www.nvaccess.org/
Copyright (C) 2006-2023 NVDA Contributors


However,  navigating away from OK then doing the copy gives you all below as well.
 I agree, it needs a clean way to do this without either doing this or viewing the log and cutting and pasting it from there.

Brian
NVDA is covered by the GNU General Public License (Version 2). You are free to share or change this software in any way you like as long as it is accompanied by the license and you make all source code available to anyone who wants it. This applies to both original and modified copies of this software, plus any derivative works.
For further details, you can view the license from the Help menu.
It can also be viewed online at: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

NVDA is developed by NV Access, a non-profit organisation committed to helping and promoting free and open source solutions for blind and vision impaired people.
If you find NVDA useful and want it to continue to improve, please consider donating to NV Access. You can do this by selecting Donate from the NVDA menu.

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by XLTechie** [comment]
@Brian1Gaff That information is not relevant to a feature request. Nor is it 
requested in the template. [Your request for the list of add-ons.]
