### ISSUE TITLE
In Firefox, NVDA treats title as the label of links when the immediate child of the link is a code tag

### ISSUE THREAD

**Issue by ahicks92** [nvaccess/nvda#15408]
### Steps to reproduce:

I discuss the impact below (this is actually breaking a lot of coding-related sites in Firefox).

Open this HTML in Firefox.  I'm on NVDA 2023.2 and Firefox 117.0 (64-bit):

```
<!doctype html>
<html lang=en>
  <head>
    <meta charset=utf-8>
    <title>blah</title>
  </head>
<body>
  <a href="https://google.com" title="Broken title">This linke is fine</a>
  <a href="https://google.com" title="Broken title!"><code>hi</code></a>
</body>
</html>
```

### Actual behavior:

In Chrome and in previous versions of (I think) Firefox the second link reads "hi", not "Broken title!".  I don't really ahve the time to try to bisect Firefox and NVDA versions unless that's necessary; I'm hoping someone can quickly spot the bug without that step.

Weirdly, switching the code tag to a span works fine.  I imagine maybe using code tags here isn't spec, but as discussed below this is common enough to force Chrome on me in the wild.

The problem is that Python documentation, Rust documentation, and probably others uses this pattern frequently where title is something long.  For example, in Rust, you will get things like "struct very::long::absolute::path::MyType" instead of just "MyType" when people link out (and, in some cases, this even replaces informative text, because the title is hiding the link's content).  Some example pages in the wild:

From [Egui's docs](https://docs.rs/egui/latest/egui/struct.Context.html):

In Firefox: "This is the first thing you need when working with egui. Contains the struct egui::InputState, struct egui::Memory, struct egui::output::PlatformOutput, and more.
struct egui::Context is cheap to clone, and any clones refers to the same mutable data (struct egui::Context uses refcounting internally)."

In Chrome, we get the much cleaner: "This is the first thing you need when working with egui. Contains the InputState, Memory, PlatformOutput, and more.
Context is cheap to clone, and any clones refers to the same mutable data (Context uses refcounting internally)."

In Python, titles can be the entire name and first-line description of a module. From [here](https://docs.python.org/3/library/gc.html):

"The gc: Interface to the cycle-detecting garbage collector. module provides the following functions:"

Which should just be gc (indeed, it's a link to the same page).

And so on.  Unfortunately I don't have an example of the really problematic Rust one I found in front of me because I was doing other things--but imagine the Egui one if the paths were a few modules deep, which is easier than you'd think if crates start re-exporting each other and such.

In many cases these are generated sites (e.g. rustdoc) and we can't expect people to fix them because it would require e.g. releasing a new version just to retrigger the builds (or to convince Rustdoc to make a change, then rebuild all of docs.rs, for example); I considered taking this to rustdoc first but then I found the Python examples too, and the internet has implied (correctly or not) that title shouldn't be considered here in any case.

### Expected behavior:

Hard to cover this separately and I explained above, but for completeness the expected behavior is title attribute gets ignored.

#### NVDA installed/portable/running from source:

Tried with portable with default settings ("copy current user configuration" was unchecked).

#### NVDA version:

2023.2

#### Windows version:

Windows 10.

#### Name and version of other software in use when reproducing the issue:
Firefox 117.0 64-bit.

#### Does the issue still occur after restarting your computer?

yes. Also on multiple machines and I've had a friend repro.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?

No.  Did portable without user configuration.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

yes it does.

**Comment by CyrilleB79** [comment]
@ahicks92, please correct NVDA version; NVDA 2023.3 (stable) has not yet been released.

Cc @jcsteh

**Comment by lukaszgo1** [comment]
This is a Firefox issue, rather than NVDA one. The bug report on Bugzilla is [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1851865). I suggest affected people to subscribe to that report for updates. Since this has been given high severity ,and @jcsteh  has already assigned this to themselves, I expect the problem to be fixed sooner than later.

**Comment by ahicks92** [comment]
Ugh, sorry about the NVDA version.  I'll edit it.

**Comment by jcsteh** [comment]
Looks like we broke this in Firefox 116. :( This is definitely a Firefox bug, but given the severity of this, I'll leave this open for tracking until it's fixed.

**Comment by ahicks92** [comment]
This seems to have been fixed in Firefox 118.  Should we close, @jcsteh?

**Comment by seanbudd** [comment]
If it appears fixed, lets close it
