### ISSUE TITLE
miscdeps update error

### ISSUE THREAD

**Issue by Kc9jjj** [nvaccess/nvda#15410]
### Steps to reproduce:
git submodle update --init
### Actual behavior:

fatal: transport 'file' not allowed                                                                                                                                                
fatal: Fetched in submodule path 'include/nvda-cldr', but it did not contain e3af0878691391cc019d2e1e7965aa5756ac653a. Direct fetching of that commit failed.                      
 
### Expected behavior:

update without error
### NVDA logs, crash dumps and other attachments:
none
#### NVDA installed/portable/running from source:
2023.2 frome source
#### Windows version:
windows 11 22h2
#### Name and version of other software in use when reproducing the issue:
none
#### Does the issue still occur after restarting your computer?
y
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
n
#### If NVDA add-ons are disabled, is your problem still occurring?
y
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
na

**Comment by lukaszgo1** [comment]
I am also experiencing this each time nvda-cldr is updated. From a research I've done this appears to be a Git bug (see discussion [in this mail list thread](https://www.spinics.net/lists/git/msg462309.html)). I haven't had time to create a minimal reproducer to be able to report this to Git properly. My current work around is to just use older version of Git for fetching new revisions of nvda-cldr (version 2.32 works on my side).

**Comment by XLTechie** [comment]
I'm not having this issue on Ubuntu git 2.34.1, for what it's worth.

**Comment by seanbudd** [comment]
Note you should probably be using `git submodule update --init --recursive` instead. did you perform `git submodule sync --recursive` as well? Closing this as an issue with git, not NVDA

**Comment by Kc9jjj** [comment]
tried both of those and still received the same error message
