### ISSUE TITLE
Add-on Store GUI: The "Don't show this message again" checkbox of the "Add-on Store Warning" dialogue box should be on the left side of its label.

### ISSUE THREAD

**Issue by hwf1324** [nvaccess/nvda#15426]
The "Don't show this message again" checkbox in the "Add-on Store Warning" dialogue box should be on the left side of its label, but is currently on the right side of its label.
This should be consistent with the rest of the NVDA GUI, but I'm not sure if this point in #15246 commit serves any other purpose?

> Add support for creating labelled checkboxes using the `BoxSizerHelper`, `LabelledControlHelper` and `associateElements`

### Steps to reproduce:

In nvda.ini:

```
[addonStore]
	showWarning = False
```

open Add-on Store

### Actual behavior:

Visually the "Don't show this message again" checkbox is located to the right of its label.

### Expected behavior:

Visually the "Don't show this message again" checkbox is located to the left of its label.

#### NVDA installed/portable/running from source:

installed

#### NVDA version:

2023.2

**Comment by CyrilleB79** [comment]
I too was surprised by this, but did not bother reporting this.

If there is no other explanation, I think that it's better to have something coherent with the rest of the GUI; see the screen curtain warning dialog for another example of such dialog.

**Comment by CyrilleB79** [comment]
The issue has gotten the label "Triaged", what means that NV Access accepts someone working on this.

@hwf1324, do you plant to fix this issue yourself?

**Comment by hwf1324** [comment]
> do you plant to fix this issue yourself?

Okay, this should be a very simple modification.
