### ISSUE TITLE
Report cell coordinates when navigating with mouse in Excel

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#15420]
### Is your feature request related to a problem? Please describe.

(Requested by a user via email)

When hovering the mouse over cells in Excel, NVDA reports the contents of a given cell, but not the coordinates.

### Describe the solution you'd like

An option to report cell coordinates when hovering with the mouse.

### Additional context

Magnification users particularly may not have the top or left edge of the spreadsheet (where the visual cell rows and columns) visible when navigating.  And if they do, reading them requires scanning across and up from the current location and back which can be difficult for low vision users.

**Comment by leonardder** [comment]
Does NVDA report the table cell roles when you enable the mouse option `Report role when mouse enters object`?

**Comment by hwf1324** [comment]
> Does NVDA report the table cell roles when you enable the mouse option `Report role when mouse enters object`?

Yes, the cell role is reported once for each cell moved to.
But it only says "cell", not coordinates.

**Comment by leonardder** [comment]
In that case, I think we should consider changing the `Report role when mouse enters object` option to something like `Report object when mouse enters it`, and let this option report the object as it was gaining focus.

**Comment by hwf1324** [comment]
> In that case, I think we should consider changing the `Report role when mouse enters object` option to something like `Report object when mouse enters it`, and let this option report the object as it was gaining focus.

That's a nice idea, maybe it can also solve #15397 at the same time.

**Comment by leonardder** [comment]
I marked this as "needs product decision". In short, I propose:

1. Rename `Report role when mouse enters object` to `Report object when mouse enters it`
2. Report similar properties as for OutputReason.FOCUSENTERED, except for description.

**Comment by seanbudd** [comment]
Given there's been no negative feedback I think your proposal is sufficient @leonardder
