### ISSUE TITLE
NVDA 2023.3beta1 - Add§on Store version scheme should not be made mandatory

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#15440]
### Steps to reproduce:
* Use NVDA 2023.2
* Install (externally) an add-on whose version number does not conform add-on store scheme, e.g. [Command Helper](https://github.com/javidominguez/commandHelper), version [dev20230730](https://github.com/javidominguez/commandHelper/releases/download/dev20230730/commandHelper-dev20230730.nvda-addon))
* Upgrade to NVDA 2023.3beta1 and restart

### Actual behavior:
The add-on cannot be loaded.

### Expected behavior:
The add-on should be loaded.
Add-on Store version scheme should be a recommendation, but not mandatory.
If it becomes mandatory in the future, it should only happen with an API breaking version (e.g. 2024.1)

Note: many add-ons based on the add-on template of NVDA add-on community are able to generate dev versions with a version number 

### Additional note
* Other version numbers create different errors, e.g. "1.0dev".
* With Instant Translate add-on, I had a manually compiled version with version number "20230901-dev" and have faced the same issue. I have tried to reinstall from the store to fix it but the installation cannot complete. It's a use case to test.
* At last with Instant translate, I have tried to remove "instantTranslate.pendingInstall" folder manually; it is a recommendation that was given from time to time on the mailing list, so people may be used to it. I realize now that the status is also in Add-ons state files. Thus I get the following error in log:
```
ERROR - addonHandler.Addon.completeInstall (09:18:07.541) - MainThread (6156):
Failed to complete addon installation for instantTranslate
Traceback (most recent call last):
  File "addonHandler\__init__.pyc", line 429, in completeInstall
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'C:\\Users\\Cyrille\\AppData\\Roaming\\nvda\\addons\\instantTranslate.pendingInstall' -> 'C:\\Users\\Cyrille\\AppData\\Roaming\\nvda\\addons\\instantTranslate'

```

### NVDA logs, crash dumps and other attachments:
```
DEBUG - addonHandler._getAvailableAddonsFromPath (08:44:52.932) - MainThread (14348):
Found add-on commandHelper - dev20230730. Requires API: (2019, 3, 0). Last-tested API: (2023, 1, 0)
ERROR - addonHandler._getAvailableAddonsFromPath (08:44:52.932) - MainThread (14348):
Error loading Addon from path: C:\Users\Cyrille\AppData\Roaming\nvda\addons\commandHelper
Traceback (most recent call last):
  File "addonHandler\__init__.pyc", line 299, in _getAvailableAddonsFromPath
  File "addonHandler\addonVersionCheck.pyc", line 70, in isAddonCompatible
  File "addonHandler\addonVersionCheck.pyc", line 56, in isAddonTested
  File "addonHandler\addonVersionCheck.pyc", line 27, in _isAddonForceDisabled
  File "_addonStore\models\version.pyc", line 28, in _parseVersionFromVersionStr
ValueError: Version string not valid: dev20230730
```

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.3beta1
#### Windows version:
Windows 10 21H2
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Not tested
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A
#### If NVDA add-ons are disabled, is your problem still occurring?
N/A
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested, unrelated

**Comment by pvagner** [comment]
All the RHVoice voice addons are suffering from this too. In other words they are not loaded with NVDA 2023.3 Beta 1 because in their manifest the version key has 4 parts not three or two.
Is this documented somewhere and what's the best we can suggest to RHVoice maintainers?
I've created a [RHVoice issue too](https://github.com/RHVoice/RHVoice/issues/789).

**Comment by pvagner** [comment]
[NVDA issue](https://github.com/nvaccess/nvda/issues/15440) does also exist. Most likelly for the 2023.3 version this is not going to be enforced after all.
