### ISSUE TITLE
Spell selection when NVDA+shift+upArrow is pressed a second time

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#15449]
### Is your feature request related to a problem? Please describe.
When pressing NVDA+shift+upArrow to have the selection reported, it may be hard to understand its content.

### Describe the solution you'd like
Double pressing NVDA+shift+upArrow spells the selection. No need to append "selected" at the end IMO.

Since NVDA command often offer a triple press feature, one can ask if one is needed or useful for NVDA+shift+upArrow:
* Copy to clipboard is clearly not useful since control+C can be used easily instead
* Spelling with character description (alpha, bravo, Charlie) seems more suitable

One question remains: what if the selection is longer than 512 characters? Since there is a limitation to read a too big content In one time, I guess that the same limitation occurs for spelling. Thus I can see two options:
* report again "513 characters selected"
* report nothing at all
### Describe alternatives you've considered
None
### Additional context
Today, I have automatically double pressed NVDA+shift+upArrow hoping to have the selection spelt as it is the case for other NVDA reading command (read line, report title, etc.) I was surprised that this command does not behave as other commands regarding this point.

**Comment by ruifontes** [comment]
For me, when more then 512 characters are selected, the second press should say "Can not spell. Too many characters..."
Regarding third press, I agree with "Spelling with character description (alpha, bravo, Charlie)"

**Comment by Adriani90** [comment]
This applies also to the reporting of clipboard content (nvda+c in laptop keyboard or the equivalent for desktop keyboard layout).
