### ISSUE TITLE
USE PEP 440 or modification for add-on versioning in the store

### ISSUE THREAD

**Issue by ultrasound1372** [nvaccess/nvda#15445]
### Is your feature request related to a problem? Please describe.
In an attempt to canonically order add-on versions for the datastore, a rather restrictive versioning scheme was enforced on add-ons which is especially inconvenient to certain release cadences or local builds. I understand the ultimate purpose of this was to make it so checking for updates could be resistant to such local builds and other issues, and I suppose the concept of channels can be used for part of this, but difficulty is still presented for many existing add-ons and certain workflows. Issues like #15440 are a symptom of this, and while that is technically due to a bug on the purely local side I expect it won't be long before this version scheme is actually made mandatory. I therefore propose expansion of the store versioning scheme to something a bit more robust, which preserves the same canonical ordering concerns.
### Describe the solution you'd like
Ideally before the release of 2024.1, extend the add-on datastore versioning scheme to be based on [PEP 440](https://peps.python.org/pep-0440/), to allow for such things as dev and beta versions to be used without consuming an extra digit in your currently digit limited scheme.
### Describe alternatives you've considered
A modified form lacking the epoch, local specifiers, and arbitrary numbers of digit groups would probably be ideal, epoch specifiers are not likely to be needed, and local versions wouldn't actually make sense given the way the add-on store works. The behavior of normalizing all numbers to lack any leading 0s is up to you, probably best based on your current scheme, but such normalization would be done silently when comparing and not affect display, to help avoid confusion with existing year.month.n formats.  
Channels and behavior of certain cross-channel updates may be derived from this scheme, using dev, b, and rc indicators as a means of pointing at channels, and perhaps dev would update to beta of the same version as is dictated by the PEP. These would be future extensions though.

### Additional context
Add-ons would, in some cases, still have to change their version numbering to comply with this, but I think the introduction of this scheme based on the way pip itself does things would ease the transition to benefit from the add-on store. I do believe that the post release should be included in the scheme just in case of the equivalent of emergency patches for specific versions that weren't thoroughly tested, but its exclusion could still work if one merely increases the last digit as we've been doing.

**Comment by seanbudd** [comment]
PEP 440 is too complicated to be able to parse correctly and provide ordered versions.

Instead we can allow any string to be used as a display version, and keep the schema of x.x.x or x.x.x.x for ordered version numbers.

See also: https://github.com/nvaccess/addon-datastore/issues/407
