### ISSUE TITLE
add option in document formatting to toggle the announcement of blank lines

### ISSUE THREAD

**Issue by hozosch** [nvaccess/nvda#15462]
### Is your feature request related to a problem? Please describe.
There is a German mailing list for NVDA and I've seen the need for NVDA to simply do nothing on blank lines come up quite a few times now. Since many of the subscribers are unfamiliar with GitHub, I would like to open this issue on their behalf.
### Describe the solution you'd like
I personally have no problem with the announcement of blank lines, especially as the user can be sure that NVDA is still online this way. However, adding this as an option you can toggle in the document formatting category would be a good idea, since anyone can have their own way then. This also should include any edit field, not just word documents or web pages.
### Describe alternatives you've considered
Well, no idea. Maybe the current state stays, and users can add the word to the dictionary and replace it with nothing. The problem is, even if it is set as the whole word only, it would be skipped in a sentence containing the standalone word.
### Additional context
Nothing more to add.

**Comment by Adriani90** [comment]
At least for browse mode, this is already covered in #4904 referencing also an attempt to introduce this.

**Comment by hozosch** [comment]
#4904 is about skipping blank lines, but this is not what I meant. #2522 covers that as well though, I've seen. Moreover, NOw that I have just seen René in the List pointing out that braille extender has this feature implemented already, I will close this issue.

**Comment by hozosch** [comment]
Oh, I'm sorry, this option in Braille extender doesn't do what I'M after. Still, leaving this closed because of #2522
