### ISSUE TITLE
If the download is terminated during the download of an add-on, the user will not be able to download the add-on again

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#15469]
### Steps to reproduce:
1. Open the add-on store
2. Switch to the "Available add-ons" tab.
3. Feel free to install an add-on such as access8Math
4. After clicking "Install" in the action menu, quickly press Esc and then press Y, This ensures that the add-on has not been downloaded and has been terminated by the user.
### Actual behavior:
The add-on's status is "Downloaded, pending install".
There are only the following options in the action menu:
* Homepage
* License
* Source

Users cannot re-download the add-on, even after restarting NVDA.

A temporary file is stored in the `%appdata%\nvda\addonStore\ dl` directory: Access8Math.download.

### Expected behavior:

1. Allow users to resume downloading and installation from breakpoints.
2. Allow users to download and install the add-on from scratch as if they were installing it for the first time.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.3Beta2
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3448
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Alpha version can also reproduce this
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by cary-rowen** [comment]
I think this also applies to situations where downloads are forced to be interrupted due to network failures.

**Comment by akash07k** [comment]
Hmm, I second this issue. It's surely problematic if a user is not into much technical expertese
