### ISSUE TITLE
NVDA in browse mode navigates twice in to button with graphic  

### ISSUE THREAD

**Issue by kolaps33** [nvaccess/nvda#15467]
### Steps to reproduce:
1. Run NVDA
2. Open the example 
https://z7k8xn.csb.app/
3. Navigate on "before test" button
4. Press "down arrow key" to navigate in browse mode
5. Press "down arrow key" to navigate in browse mode

### Actual behavior:
NVDA navigates to one button like there would be 2 buttons. 
NVDA narrate following:
button    Tag 1
button    graphic    remove

### Expected behavior:
I would expect NVDA navigates only to one button element. 
It doesn't sounds to me efficient if user need to navigate to such button twice. Even it can give the impression there are two buttons, but in the fact there is only 1 button. 
JAWS navigates only to single button, like it is single button. 

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2023.3beta2 (2023.3.029218)

#### Windows version:
OS Name	Microsoft Windows 11 Enterprise
Version	10.0.22621 Build 22621

#### Name and version of other software in use when reproducing the issue:
Chrome Version 116.0.5845.141 (Official Build) (64-bit)
Firefox 117.0.1 (64-bit)

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
yes 

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by seanbudd** [comment]
This is intended behaviour.
The div containing the graphic displays as a block.
If you believe this is a spec violation please elaborate.
