### ISSUE TITLE
NVDA 2023.3beta2 - Error at NVDA startup

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#15479]
### Steps to reproduce:
Start NVDA
### Actual behavior:
Error ding at startup

I have not seen any consequence of this error, but I have not opened the add-on store.

This issue does not occur each time. I have seen it only twice in 10 or 20 restarts.

I am reporting it in case it is a consequence of code merged recently (cc @seanbudd)

### Expected behavior:
No error

### NVDA logs, crash dumps and other attachments:

```
ERROR - addonHandler.AddonsState.load (11:18:14.234) - MainThread (22404):
Traceback (most recent call last):
  File "addonHandler\__init__.pyc", line 115, in load
  File "utils\caseInsensitiveCollections.pyc", line 20, in __init__
  File "utils\caseInsensitiveCollections.pyc", line 23, in add
AttributeError: 'int' object has no attribute 'casefold'
```

#### NVDA installed/portable/running from source:
Source
#### NVDA version:
Running uncommitted modifications for #15478 on top of beta branch (262b27cb80ecc501d06ae6a8a8e6eca45866f151).

#### Windows version:
Windows 10 21H2 (AMD64) build 19044.3324

#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Not tested
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I have not seen this error on NVDA 2023.beta2 (during one day), nor with NVDA 2023.2 or with NVDA 2023.3beta1. But since the error only occurs rarely, we cannot conclude anything with absolute certainty.

#### If NVDA add-ons are disabled, is your problem still occurring?
Not tested
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested

**Comment by Adriani90** [comment]
Maybe related to #15455?

**Comment by CyrilleB79** [comment]
> Maybe related to #15455?

@Adriani90 are you sure you have linked the correct PR?

The error is seen during add-on handler initialization, but #15455 has nothing to do with it...

**Comment by seanbudd** [comment]
This is due to #15439

If you downgrade NVDA from that version you will get this error in the log.
It's harmless, and there's no clear way to avoid it.
