### ISSUE TITLE
notepad not reading

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1547]
**Reported by dwillemv on 2011-06-03 05:33**
When using notepad, the following error occurs frequently:

DEBUGWARNING - RPC process 6048 (notepad.exe) (07:24:56):
Thread 6000, nvdaHelper\build\x86\remote\ia2Support.cpp, installIA2Support, 81:
Error registering class object, code -2147221008

Sometimes the notepad window doesn't read, but alt+tabbing out and back in again restors focus.
This is on XP, but might be on windows 7 too. The focus problem certainly is.

**Comment by dkager** [comment]
Looks like this issue was abandoned.
