### ISSUE TITLE
Bug in LibreOffice Calc: NVDA does not update cell content after modifying it

### ISSUE THREAD

**Issue by javidominguez** [nvaccess/nvda#15485]
### Steps to reproduce:

1. run libreoffice calc  
2. Write something in a cell  
3. Move to another cell with tab or enter key  
4. Go back to the cell where you typed the content  
5. Write different content in this cell
6. Repeat steps 3 and 4

### Actual behavior:

* After step 4 NVDA will show an empty cell but actually the cell has content.  
* After step 6 NVDA will show the cell with the content written the first time (step 2) when actually the cell has the content written the second time (step 5).  

If the table loses focus and then regains it, for example by doing this:  
* Opening and closing the application menu  
* Pressing F2 to edit the cell and then tab or enter  
* Minimizing the LibreOffice Calc window and restoring it again  
The cell is updated correctly. This perhaps indicates that the problem is with an event that is not propagated properly. When a cell loses focus, the table object could be refreshed so that the content is updated.

### Expected behavior:

NVDA should read the actual contents of the cell.  

### NVDA logs, crash dumps and other attachments:

There are none.  

#### NVDA installed/portable/running from source:

Installed and portable NVDA.  

#### NVDA version:

NVDA 2023.2 and alpha-29251,2fe9cb23 (2024.1.0.29251)  

#### Windows version:

Windows 11 22H2 (AMD64) build 22621.2283  

#### Name and version of other software in use when reproducing the issue:

LibreOffice 7.6.0.3 (X86_64)  

#### Does the issue still occur after restarting your computer?
Yes  

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes  

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by michaelweghorn** [comment]
This is a LibreOffice bug:
https://bugs.documentfoundation.org/show_bug.cgi?id=157616

It's a regression in LibreOffice 7.6, so using LibreOffice 7.5.7 ("LibreOffice still") for now could be a workaround until it gets fixed.

**Comment by mwhapples** [comment]
It is definitely an issue on the LibreOffice end rather than NVDA. I have reproduced the issue using Narrator and I see a similar bug report for Orca and LibreOffice.
Using LibreOffice 7.5.7 is acceptable for me, I just hope it can be fixed before LibreOffice 7.5.x releases are no longer supported.

**Comment by michaelweghorn** [comment]
This is fixed in the current development version of LibreOffice now:
https://git.libreoffice.org/core/commit/8e886993f32b7db11a99bdecf06451e6de6c3842

Pending backport for 7.6 (to be included in LibreOffice 7.6.3 once it has been reviewed and merged):
https://gerrit.libreoffice.org/c/core/+/157627

**Comment by michaelweghorn** [comment]
> Pending backport for 7.6 (to be included in LibreOffice 7.6.3 once it has been reviewed and merged): https://gerrit.libreoffice.org/c/core/+/157627

Merged now, i.e. it's fixed in 7.6.3.

**Comment by CyrilleB79** [comment]
OK. Closing as completed (externally).
