### ISSUE TITLE
Feature request: Allow simulated mouse wheel scrolling

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#15484]
### Is your feature request related to a problem? Please describe.
Some dynamically loaded web pages only allow scrolling with the hardware wheel on the mouse to display more content. A similar situation exists with some desktop applications, such as [dism++](https://github.com/Chuyu-Team/Dism-Multi-language/). NVDA can only interact with it through the screen review mode. However, if you want to load more items, you must use the mouse wheel.

I created a simple html demo to further clarify this situation, but this demo does not only allow mouse wheel scrolling.

[Scroll-loading List_Demo.html.txt](https://github.com/nvaccess/nvda/files/12675903/Scroll-loading.List_Demo.html.txt)

Even more coincidentally, I also saw people asking for the same feature on Groups.io.
[Sending scroll event to focused window](https://nvda-addons.groups.io/g/nvda-addons/topic/101114690)

### Describe the solution you'd like
Add a set of gestures to simulate the behavior of the mouse wheel being rolled.
### Describe alternatives you've considered
I considered Windows Mouse Keys, but Mouse Keys only seem to move the mouse pointer, not the wheel, and Windows Mouse Keys require a numpad.

Here is Microsoft's documentation on mouse keys:

[Microsoft's documentation on mouse keys](https://support.microsoft.com/en-us/windows/use-mouse-keys-to-move-the-mouse-pointer-9e0c72c8-b882-7918-8e7b-391fd62adf33)

### Additional context
I also searched NVDA Issues and found #4019; the wording of that feature request may have caused some misunderstanding. So I created this Issue hoping to re-clarify the feature request and give a Minimal Reproducible Example that is easier to test.

This feature is already implemented in the tonys-enhancements add-on, and given the above, I think it needs to be in NVDA core.

Finally, if possible, I'd like to contribute a PR to bring this feature to NVDA.

**Comment by XLTechie** [comment]
Can you point to a website which only allows this type of scrolling? (Not a 
constructed example)

**Comment by cary-rowen** [comment]
@XLTechie 
I can give an example of a desktop application:
https://github.com/Chuyu-Team/Dism-Multi-language/


## Possible test steps
1. Download "Dism++10.1.1002.1B.zip" from the Release page of the Repo given above.
2. Unzip the file and run "Dism++x64.exe".
3. You must use screen review mode to access the content on the screen.
4. e.g. "Optional Features".

There are many optional items in Optional Features, However, it cannot be fully displayed on the screen.
As far as I know, you can only make more items appear on the screen via the mouse wheel or touchpad.


Thanks

**Comment by ultrasound1372** [comment]
With some apps, such as Spitfire Audio, Korg Software Pass, and other music software management applications that expose only a single window object that you must use OCR to navigate, I imagine generating a mouse wheel scroll event is the only way to get their lists of things to show more items, as their windows refuse to get any bigger. So this would be useful in that case as well if you can't find an actual scrollbar.

**Comment by mltony** [comment]
FWIW, Tony's enhancement already has this implemented. Keystrokes: Alt+NumpadPlus/NumPadMinus.
