### ISSUE TITLE
Request for NVDA to track the translated line in Duxbury Braille Translation Software when in the Braille document view

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1549]
**Reported by Marcia.Yale on 2011-06-06 05:05**
In Duxbury Version DBT10.6, Windows XP, it is not possible to navigate the Braille view of a document in order to verify the translation and/or lay-out which Duxbury has prepared for embossing. NVDA does not recognize any of the characters shown. I am not aware of any fixes in later versions of either the Duxbury program or Windows and I apologize if this is out of scope or out of line, but I have not received any responses when I've sent this query to the support list.

**Comment by bhavyashah** [comment]
Could our resident Braille experts please test if the reported issue still stands with the latest versions of both NVDA and Duxbury?

**Comment by Adriani90** [comment]
@Marcia.Yale can you still reproduce this in NVDA 2018.2.1? i guess with automatic braille tetering it should work.

**Comment by leonardder** [comment]
This is an old issue and we haven't had relevant comments in a while. If the issue still applies, please create a new issue, making use of the issue template.
