### ISSUE TITLE
NVDA Not reading symbols in WSL Terminal

### ISSUE THREAD

**Issue by EneyeAttah** [nvaccess/nvda#15496]
NVDA Not reading symbols in WSL Terminal ;
blah -----   ###   %%%  blah ----  $$$ -----   -----  blah

**Comment by seanbudd** [comment]
Welcome @EneyeAttah ,

We are unable to process this issue as it stands.

Please fill out the issue template fully and reopen a new issue.

Kind Regards,
NV Access Software Developers
