### ISSUE TITLE
Click handler called repeatedly when holding space or enter key on an expand/collapse button

### ISSUE THREAD

**Issue by Epic-Third-Party-Bug-Reporting** [nvaccess/nvda#15499]
### Steps to reproduce:
Navigate to a button that controls the expanded/collapsed state of a section, and hold space or enter key.

### Actual behavior:
When NVDA is running, holding Enter or Space bar will repeatedly call the click handler on an expand/collapse button, switching the expanded state back and forth while the key is held.

### Expected behavior:
Button state should change on keyup, and not repeatedly while key is held

### NVDA logs, crash dumps and other attachments:
Example of raw HTML where issue can be reproduced

"<!DOCTYPE html>
<html>
    <style>
        .nodisp {
            display: none;
        }
    </style>
    <body>
        <button 
            type="button" 
            tabindex="0" 
            id="btn" 
            role="button"
        >
            Collapse All
        </button>
        <div id="content">
            <p>According to all known laws of aviation, there is no way a bee should be able to fly. It's wings are too small to get its fat little body off the ground. The bee, of course, flies anyway, because bees don't care what humans think is impossible.</p>
        </div>
 
        <script>
            var el = document.getElementById("btn");
            el.onclick = collapseExpand;
            el.onkeydown = onKey;
            el.onkeyup = onKey;
            el.focus();
 
            function onKey(e) {
                if ((e.type == "keydown" && e.key == "Enter" && !e.repeat)|| (e.type == "keyup" && e.key == " "))
                {
                    collapseExpand();
                }
            }
 
            function collapseExpand(e) {
                var content = document.getElementById("content");
                if (!e || e.pointerType == "mouse") {
                    content.classList.toggle("nodisp");
                    if (content.classList.contains("nodisp"))
                    {
                        el.ariaExpanded = "false";
                        el.innerText = "Show text";
                    }
                    else
                    {
                        el.ariaExpanded = "true";
                        el.innerText = "Hide text";
                    }
                }
            } ;
        </script>
    </body>
</html>"

#### NVDA version:
2022.4.0.27401
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
Chrome and Edge browser
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

**Comment by seanbudd** [comment]
Welcome @Epic-Third-Party-Bug-Reporting 

We are unable to process this issue as it stands.

- I noticed you also reported this to JAWS. Are you sure this isn't just keyboard behaviour irrelevant to screen readers? Is the behaviour still the same without a screen reader running?
- please use [CodePen](https://codepen.io/) or similar for your sample so the issue can easily be reproduced
- Please provide the versions of the browser you can reproduce this with
- please test with the latest version of NVDA, 2023.2


Kind Regards,
NV Access Software Developers
