### ISSUE TITLE
regression: Sapi4 speech rate is changed after triggering PitchCommand.

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#15500]
cc @leonardder 
I will privately email you a copy of the speech synthesizer application that reproduces the issue.
### Steps to reproduce:
1. Run nvda-Alpha-29323.
2. Switch to the Sapi4 synthesizer.
3. Try adjusting the sapi4 synthesizer's speech rate to be faster.
4. Make NVDA pronounce a capital letter.

### Actual behavior:
Synthesizer speech rate reduced.
Two options are available to restore the original rate:
1. Use gestures to adjust the speech rate of the synthesizer settings ring.
2. Press Ctrl+NVDA +V to open the voice settings panel, then press ESC to close.
### Expected behavior:
Speech pitch changes should not affect speech rate.
### NVDA logs, crash dumps and other attachments:
[log.txt](https://github.com/nvaccess/nvda/files/12705437/log.txt)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Alpha-29323
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3448
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA2023.3Beta2 works as expected
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by leonardder** [comment]
I'm pretty sure that, when this synthesizer gets prosody in a sequence, it resets all other prosody variables to their defaults. In a worse scenario, it supports only one command at a time.
That said, I found [this add-on](https://github.com/TETYYS/SAPI4) which seems to be maintained by @CyrilleB79. Is there any reason to stick with the old SAPI4 version?

**Comment by cary-rowen** [comment]
Hi,

Oh, there seems to be a misunderstanding here. What I sent you privately is an executable program that you need to install on your computer and then select "Microsoft Speech API version 4" in the speech synthesizer dialog box in NVDA.

As for the add-on you mentioned, it is maintained by @davidacm.

Thanks
