### ISSUE TITLE
Formatting reporting status shortcut keys for Excel cells should follow the key mapping for English.

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#15506]
cc @CyrilleB79 

### Steps to reproduce:
According to Microsoft's support documentation available in both [French][fr-fr] and [English][en-us], it is clarified that the keyboard shortcuts introduced in #14923 are designed specifically for the French localization and are not applicable to the English version.

* bold: control+shift+2
* italic: control+shift+3
* underline: control+shift+4
* strikethrough: control+shift+5

As a standard practice, NV Access adheres to the English keyboard layout. In cases where special key combinations are needed, especially those inconsistent with the English layout, the localization team in each region is responsible for mapping separate gestures accordingly.

### Actual behavior:
According to Microsoft support documentation. When the language in Excel is set to English, pressing the following shortcut keys may not yield the same action as reported by NVDA.

* bold: control+shift+2
* italic: control+shift+3
* underline: control+shift+4
* strikethrough: control+shift+5

### Expected behavior:

* bold: control+2
* italic: control+3
* underline: control+4
* strikethrough: control+5

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.3beta2
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3448
#### Name and version of other software in use when reproducing the issue:
Microsoft 365MSO (Version 2308 Build 16.0.16731.20182) 64 Bit
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This was introduced in 2023.2
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

[fr-fr]: https://support.microsoft.com/fr-fr/office/raccourcis-clavier-dans-excel-1798d9d5-842a-42b8-9c99-9b7213f0040f#PickTab=Windows

[en-us]: https://support.microsoft.com/en-us/office/keyboard-shortcuts-in-excel-1798d9d5-842a-42b8-9c99-9b7213f0040f#PickTab=Windows

**Comment by CyrilleB79** [comment]
Thanks for reporting this.

Something quite strange is that when I have implemented #14923, I have tested both with Excel in French and in English. I have tested it again and the actual shortcuts with Excel in English are the same as when Excel is in French for control+shift+2/3/4/5.
I am using Microsoft® Excel® 2016 MSO (Version 2308 Build 16.0.16731.20182) 32 bits

Would there be a change between Excel 2016 and 365 regarding the shortcut keys? Or is my test protocol to test on English Excel not correct? To test in English, I go to Excel's language options, I just change the interface language to English (putting it first in the list) and then I restart Excel.

Also, @cary-rowen, you speak specifically about documentation in the initial description of this PR. Could you confirm me that you have performed the tests on Excel in English on your side? That is:
* What happen when you press control+shift+2/3/4/5 on a cell in your Excel?
* If instead a cell is selected and you press control+2/3/4/5, are you able to check that the formatting of the cell is toggled (either visually or with NVDA+F)?

Sorry to ask all this but it's necessary to understand the full problem.
Many thanks.

**Comment by cary-rowen** [comment]
Hi @CyrilleB79 
I apologize for not providing this information in the original description.

> Would there be a change between Excel 2016 and 365 regarding the shortcut keys? Or is my test protocol to test on English Excel not correct? To test in English, I go to Excel's language options, I just change the interface language to English (putting it first in the list) and then I restart Excel.

Sorry I didn't use Office2016 for testing. So I don’t know if there are shortcut key differences between different versions. However, I followed the same testing steps as you with MSO365, which is: changing English to the preferred language.

---

> Could you confirm me that you have performed the tests on Excel in English on your side? That is: • What happen when you press control+shift+2/3/4/5 on a cell in your Excel?

Yes, I can confirm this, when I press control+shift+2/3/4/5 I find that Office365 performs the same actions as documented in the English documentation.

| To do this | Press |
| --- | --- |
| Apply the Time format with the hour and minute, and AM or PM. | Ctrl+Shift+At sign (@) |
| Apply the Date format with the day, month, and year. | Ctrl+Shift+Number sign (#) |
| Apply the Currency format with two decimal places (negative numbers in parentheses). | Ctrl+Shift+Dollar sign ($) |
| Apply the Percentage format with no decimal places. | Ctrl+Shift+Percent sign (%) |

Note that Microsoft’s wording here is: At sign, Number sign, Dollar sign and Percent sign

---

> If instead a cell is selected and you press control+2/3/4/5, are you able to check that the formatting of the cell is toggled (either visually or with NVDA+F)?

Yes, I can use both ways to confirm that the cell's format has been toggled.


Thanks

**Comment by CyrilleB79** [comment]
I would be interested to have other people perform this test on various versions and languages of Office; I will try to ask on my side.

However, if it is confirmed that Office 2016 and 365 do not share the same shortcuts, I fear we need to unmap these shortcuts.

**Comment by cary-rowen** [comment]
Thank you @CyrilleB79 for your efforts.

For the Chinese version of Microsoft 365, the above shortcut keys are consistent with English.

Thanks

**Comment by wmhn1872265132** [comment]
By reading the Excel help documents released by Microsoft in other languages, I found that the default Excel shortcut keys in the following regions involving the numbers on the main keyboard are also the same as those in the English version:
de_CH (German), es_CO (Spanish), nb_NO (Norwegian), pt_BR (Portuguese), zh_CN (Simplified Chinese), zh_HK (Traditional Chinese).

**Comment by CyrilleB79** [comment]
> By reading the Excel help documents released by Microsoft in other languages, I found that the default Excel shortcut keys in the following regions involving the numbers on the main keyboard are also the same as those in the English version: de_CH (German), es_CO (Spanish), nb_NO (Norwegian), pt_BR (Portuguese), zh_CN (Simplified Chinese), zh_HK (Traditional Chinese).

@wmhn1872265132 and all:
To be extra clear, I fully agree that only English versions of Excel should be considered when defining the gestures in NVDA's codebase. If there are other differences, they have to be implemented in the locale `gesture.ini` files maintained by translators.

What is sure is that ctrl+shift+2/3/4/5 are not the shortcuts defined in English Office 365. Thus they have to be unbound.

The only concern that I have is that I have still to figure if I should bind ctrl+2/3/4/5 instead or if I should bind nothing as a replacement.

If we find that control+2/3/4/5 is implemented in all recent versions of English Office, we should bind these shortcuts. If instead the shortcuts may differ according to the versions, it's better to keep the shortcuts unbound.
ctrl+B, ctrl+u and ctrl+I will still remain as an alternative (actually the most common one); unfortunately, there is no equivalent of ctrl+5 with a letter.

At last, I insist on the fact that I prefer that the shortcuts be tested rather than looking at the documentation. I have already seen errors in the documentation, at least the French one.

**Comment by CyrilleB79** [comment]
After more investigation I have found the cause of shortcuts differing between my tests on English versions of Excel and yours.

It seems that some Excel shortcuts are impacted not only by the language of Excel's GUI, but also the layout of the keyboard when Excel is started (and not after !). If I have the English keyboard when Excel is started, I can confirm that control+2/3/4/5 are the cell formatting shortcuts.

Note that this issue with keyboard layout when starting Excel only seems to affect gestures containing a number keys of the alphanumeric keyboard, i.e. number keys above the letters. This seems an Excel bug, probably related to the fact that on French keyboards, the number keys of alphanumeric keyboard require to be combined with shift to write digits.

**Comment by cary-rowen** [comment]
Thank you for your rigorous and careful investigation of this.

Now that it's clear, it didn't occur to me that the shortcut keys might be affected by the keyboard layout before Excel started.

thank you for your efforts
