### ISSUE TITLE
synthesizer selection in the latest alpha fails

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#15516]
### Steps to reproduce:
1. open the synthesizer dialog with insert+control+s,
2. try to choose any speech synthesizer available from the list.
### Actual behavior:

Speech synthesizer doesn't change at all, error sound is present, and the following exception is in the log.
### Expected behavior:

speech synthesizer should change to the requested one properly without errors and logged exceptions.
### NVDA logs, crash dumps and other attachments:
ERROR - unhandled exception (13:16:15.925) - MainThread (10860):
Traceback (most recent call last):
  File "gui\settingsDialogs.pyc", line 1136, in onOk
AttributeError: 'SynthesizerSelectionDialog' object has no attribute 'deviceList'

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
NVDA version alpha-29361,87d5b5a5

#### Windows version:
Windows version: Windows 11 23H2 (10.0.22631) workstation AMD64

#### Name and version of other software in use when reproducing the issue:
not applicable
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not applicable
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by ruifontes** [comment]
Confirmed with Windows version 22H2 22621 and same version of NVDA

**Comment by CyrilleB79** [comment]
Probably a bug in #15486.

Cc @codeofdusk

**Comment by cyrmax** [comment]
Confirmed with the same version of NVDA and with Windows 10 22H2 (AMD64) build 19045.3448.
