### ISSUE TITLE
Windows 11: recognize build 22631 (23H2/2023 Update)

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#15530]
Hi,

Hoping the follow-up pull request can be part of 2023.3:

### Is your feature request related to a problem? Please describe.
As of September 26, 2023, Windows 11 2023 Update (Version 23H2) is available to Windows Insiders subscribed to release preview channel. This means stable channel users will get build 22631 as early as October 2023.

### Describe the solution you'd like
Recognize build 22631 as Windows 11 23H2 and update last tested build in app store XML file.

### Describe alternatives you've considered
Push 23H2 recognition to 2024.1 (alpha).

### Additional context
See #15312 for rationale on 23H2 features support.

**Comment by seanbudd** [comment]
If this gets merged before Monday AEST next week it should be able to make the cut off for (the hopefully final beta) 2023.3beta4
