### ISSUE TITLE
All multiline text controls should have no automatic soft line feeds.

### ISSUE THREAD

**Issue by hwf1324** [nvaccess/nvda#15549]
All multi-line `wx.TextCtrl` controls in the NVDA GUI now use automatic soft line feeds by default for text that extends beyond the width of the control.

### Is your feature request related to a problem? Please describe.

Reading text can be interrupted by soft line breaks, which can be a bit of a pain to translate or copy what you've just heard.

### Describe the solution you'd like

Pass the `wx.HSCROLL` flag for the `style` parameter when creating the `wx.TextCtrl` control.

### Describe alternatives you've considered

preserve the status quo

### Additional context

Maybe people also want to report less text at a time, I'm not sure. And for those who can see it, it might be more aesthetically pleasing to maintain the status quo.

**Comment by seanbudd** [comment]
This is intended behaviour
