### ISSUE TITLE
Message : AV Page View or AV Page Text frame

### ISSUE THREAD

**Issue by marialuzhansky** [nvaccess/nvda#15553]

**Comment by hwf1324** [comment]
Please re-edit the issue description, you seem to have accidentally commented out what you wrote with `<! ---->` commented out.

**Comment by seanbudd** [comment]
Welcome @marialuzhansky ,

We are unable to process this issue as it stands.

Please open a new issue fill out the issue template fully. What version of the software are you using? What version of NVDA? Can you provide a sample document?

Kind Regards,
NV Access Software Developers

**Comment by hwf1324** [comment]
> @marialuzhansky 
> 
> Please re-edit the issue description, you seem to have accidentally commented out what you wrote with `<!---->` commented out.

@marialuzhansky

**Comment by seanbudd** [comment]
Please open a new issue by filling out the bug report template
