### ISSUE TITLE
When attempting to start the NVDA 2023.1 installer to run locally, it starts, exits, and NVDA 2023.3beta3 

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#15554]
### Steps to reproduce:
I have two separate situations, based on what @lukaszgo1 advised me to do.  When I attempt a clean start of NVDA using the following command line:
```batchfile
nvda_2023.1.exe -c "C:\Users\brite\OneDrive\Desktop\TEMP NVDA\nowhere" --debug-logging --log-file="C:\Users\brite\OneDrive\Desktop\TEMP NVDA\nvda2023.1_debug.log"
``` 
everything behaves as expected.  The installer starts and allows me to go through the usual choices when not actually installing, including running as portable from the installer.

However, whether I invoke nvda_2023.1.exe by activating that file in File Explorer or via the following command line:
```batchfile
nvda_2023.1.exe  --debug-logging --log-file="C:\Users\brite\OneDrive\Desktop\TEMP NVDA\nvda2023.1_debug_normal-start.log"
``` 
what happens, in order, is this:
The usual setup starting tune and dialog box.
Then I get the rising xylophone tones indicating NVDA is starting, a very brief pause, and then a second set of xylophone tones indicating NVDA is starting. From all appearances, the installer starts, exits, and somehow tells 2023.3beta3 to start.
Using the NVDA + N, H, A command to get the NVDA version information, I am shown I am running NVDA 2023.3beta3

Note: the above does not occur, at all, if I am actually kicking off NVDA 2023.1 from a true portable copy by activating nvda.exe

### Actual behavior:
Documented in Steps to Reproduce

### Expected behavior:
NVDA 2023.1 firing up as it normally should from an installer, rather than triggering NVDA 2023.3.beta3

### NVDA logs, crash dumps and other attachments:
[nvda2023.1_debug_cleanstart.log](https://github.com/nvaccess/nvda/files/12775605/nvda2023.1_debug_cleanstart.log)
[nvda2023.1_debug_normal-start.log](https://github.com/nvaccess/nvda/files/12775606/nvda2023.1_debug_normal-start.log)

#### NVDA installed/portable/running from source:
Running nvda_2023.1.exe, whether directly by activating that file in file explorer, double clicking, or triggering via the command line as noted in Steps to Reproduce.

#### NVDA version:
NVDA 2023.1

#### Windows version:
Windows 11, Version 22H2, Build 22621.2283

#### Name and version of other software in use when reproducing the issue:
N/A

#### Other information about your system:
LG Gram 16, 16GB RAM, i5 12th gen CPU, 1TB NVMe SSD

### Other questions
Not applicable in this instance.

**Comment by CyrilleB79** [comment]
Yes, I am facing the same issue.

It's probably an issue either in my config or in my add-ons. I need to take time to investigate this.

**Comment by lukaszgo1** [comment]
I'm in the process of writing a fix for this, I'll hopefully submit it later today.

**Comment by lukaszgo1** [comment]
See #15556

**Comment by seanbudd** [comment]
Please note that NVDA does not support downgrading

**Comment by britechguy** [comment]
> Please note that NVDA does not support downgrading

True.  But this was not an attempt to downgrade, but was an attempt to run an earlier version from its installer (essentially as a portable) as part of determining if a regression had occurred in later NVDA 2023.X versions.

It is my understanding that one should be able to run any version of NVDA as a portable by kicking off its installer, but answering the "keep running" prompt, regardless of what one's installed version happens to be.  That was my only reason for filing this issue.

**Comment by XLTechie** [comment]
@seanbudd, this is not an issue of downgrading.

When starting an installer, whether you are planning to create a portable copy 
or just need to run a temporary copy for debugging, the installer reads the 
currently installed copy's configuration.

Therefore it doesn't matter whether you are planning to downgrade, or do some 
other, more legitimate action. You won't be able to.

**Comment by britechguy** [comment]
I know this was just closed, but I do have a question, will the fix noted only apply to "to be released" versions of NVDA going forward, or would it work at present if an earlier installer were being used with NVDA 2023.3beta4 (which I know does not yet exist).

**Comment by seanbudd** [comment]
Could you please explain your question a bit more? Perhaps some steps to reproduce

**Comment by britechguy** [comment]
> Could you please explain your question a bit more? Perhaps some steps to reproduce

Actually, the initial problem statement is precisely the steps to reproduce (or not reproduce, we hope).

However, I missed the line in [de187e7](https://github.com/nvaccess/nvda/commit/de187e790ca2541fb10adc822c21be123f0b873c) that reads:  "It should be once again possible to start older versions of NVDA with the config used with the latest beta."  That answers the query I was trying to make.
