### ISSUE TITLE
Focus order not resetting when opening a new page/link.

### ISSUE THREAD

**Issue by joshuaboele** [nvaccess/nvda#15567]
### Steps to reproduce:

* Open Chrome or FireFox
* Visit https://www.den.nl/ with NVDA enabled,
* Navigate to the footer
* Click/activate any link in the footer, i.e 'Over ons'.

### Actual behavior:

Focus order not moving to top (resetting) after page load.

### Expected behavior:

Focus order resetting on page load.

### NVDA logs, crash dumps and other attachments:

x

### System configuration

NVDA installed 

#### NVDA version:

2023.1 (2023.1.0.27913)

#### Windows version:

Version	10.0.19045 Build 19045

#### Name and version of other software in use when reproducing the issue:

Chrome 117.0.5938.132 
FireFox 118.0.1

#### Other information about your system:

Windows 10 running natively

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If NVDA add-ons are disabled, is your problem still occurring?

No add-ons are enabled.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

#### Misc.

This might not be a bug, but I'm very curious if it's not a bug why this happens and why this would be the intended behavior.

Kind regards,

Joshua

**Comment by seanbudd** [comment]
Are you the author of `den.nl`? If so, could you please create a minimal HTML sample for us to reproduce the issue?
Would you also be able to test with 2023.3beta4? There has been some recent fixes with focus changes.

**Comment by joshuaboele** [comment]
Hi Sean,

Thanks for the answer. Unfortunately I'm not the author of the website. Just the accessibility auditor. It's going to be hard/impossible for me to create a minimal HTML sample.

I'll give it a shot with the 2023.3beta4 version.

**Comment by seanbudd** [comment]
I can't reproduce this with 2023.3beta4, can you confirm?
