### ISSUE TITLE
Add-on store: no updates present for add-ons forcefully enabled despite marked incompatible

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#15568]
Hi,

A variation of #15029 but applies mostly to NVDA alpha snapshots (for now):

### Prerequisites:
NVDA 2024.1 alpha, one or more add-ons marked incompatible with 2024.1 API, one or more of these add-ons enabled (overriding compatibility). updates released for at least one of these add-ons.

### Steps to reproduce:
1. From add-on store, make sure incompatible add-ons are enabled (forcefully a.k.a. overriding compatibility).
2. Restart NVDA when prompted.
3. Open add-on store, then go to available add-ons tab.
4. Make sure "include incompatible add-ons" is checked and channel is set to "all".
5. If updates are available, the new versions will be shown from available add-ons tab, hopefully these updates should be compatible with 2024.1 API (preferably dev builds).
6. Try installing add-on updates via context menu for "incompatible" add-ons.

### Actual behavior:
There is no "install/update" option in add-on context menu despite the updated add-on (or a dev build) declaring compatibility (and actually tested) with 2024.1 API (alpha).
 
### Expected behavior:
Updates can be installed (either from available or updatable add-ons tab).

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-29490,2adb77cb

#### Windows version:
Windows 11 23H2 beta (build 22631.2338)

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
Add-on development workstation

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2023.2/2023.3 exhibits similar issues, although the main issue being discussed occurs with alpha builds

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not applicable

### Additional context:
Some add-on authors would like to test their add-on(s) with alpha level code (with dev builds) and would like to also test add-on updating functionality provided by the add-on store.

Thanks.

**Comment by seanbudd** [comment]
I think we will need to make the status of an add-on contextual to the tab of the add-on store its on.
