### ISSUE TITLE
Updated shortcut key reporting doesn't respect use spelling functionality option

### ISSUE THREAD

**Issue by Mohamed00** [nvaccess/nvda#15566]
### Steps to reproduce:
1. Disable the use spelling functionality option.
2. Navigate to a control with a shortcut key, for example by pressing alt+f in Notepad.
### Actual behavior:

Character mode commands are still sent to the synthesizer. This can cause issues with some older SAPI synthesizers that don't properly implement character mode support.
### Expected behavior:

No character mode commands should be sent to the synthesizer.
### NVDA logs, crash dumps and other attachments:
Log fragment with use spelling functionality off.
IO - speech.speech.speak (08:29:13.122) - MainThread (20000):
Speaking [LangChangeCommand ('en_US'), 'Installed apps', 'Alt, ', CharacterModeCommand(True), 'p', CharacterModeCommand(False), '1 of 18', CancellableSpeech (still valid)]
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
alpha-29490,2adb77cb.
#### Windows version:
Windows 11, Version 23H2 (OS Build 25951.1010).
#### Name and version of other software in use when reproducing the issue:
N/A.
#### Other information about your system:
N/A.
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, versions prior to #14900 being merged don't have this problem.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by CyrilleB79** [comment]
Thanks for reporting @Mohamed00!
I will have a look.

If I understand correctly, with these old synthesizers, you need to uncheck "Use spelling functionality" option so that they work correctly. Is it correct?

**Comment by Mohamed00** [comment]
Yes. Some old synthesizers may not implement character mode properly, and in these cases, it may result in pauses that may not be wanted, or, in others, may result in the character mode command being spelled out literally.

**Comment by CyrilleB79** [comment]
@Mohamed00, will you be able to test the build generated in #15572 when it is ready?

**Comment by Mohamed00** [comment]
Can confirm that this fixes the character mode issues I was having.
