### ISSUE TITLE
Specify the style of docstrings in the code style

### ISSUE THREAD

**Issue by hwf1324** [nvaccess/nvda#15575]
### Describe the solution you'd like

Add a description of the style for the documentation strings used by NVDA in the code style file

**Comment by seanbudd** [comment]
Can you please give an example of what you propose to add to [codingStandards.md](https://github.com/nvaccess/nvda/blob/master/projectDocs/dev/codingStandards.md)?

**Comment by hwf1324** [comment]
Describe the details of the style of docstrings used in the source code of NVDA, and provide at least a reference link

When I look at the docstring, its style is similar to Sphinx, but there are some differences that are confusing
So I hope to clarify the style details of the document string

**Comment by seanbudd** [comment]
Do you have a proposed standard to be implemented? Sphinx is probably most appropriate

**Comment by seanbudd** [comment]
I think currently we use epytext

**Comment by hwf1324** [comment]
No, but if it is necessary to specify that it is Sphinx, it is necessary to explain those different parts
Those differences could be the evolution of Sphinx or something, I don't know

Should consult the person who has written a large number of docstrings in this project

**Comment by hwf1324** [comment]
Okay, I didn't have much knowledge about it before

**Comment by leonardder** [comment]
> I think currently we use epytext

This is correct. I once tried to come up with a conversion script that converted Epytext style to sphinx, but that's a real challenge.

**Comment by seanbudd** [comment]
Considering #12972 exists, I'm going to consider this issue as mentioning epytext in codingStandards.md
