### ISSUE TITLE
Add-on store: Users can uninstall downloaded/in-progress add-ons

### ISSUE THREAD

**Issue by hwf1324** [nvaccess/nvda#15578]
Users cannot refuse to install when they accidentally download the wrong add-on or do not want to download the updates
One crude method is to delete the files in the download directory, but this will disrupt the installation of other add-ons

### Describe the solution you'd like

Add a cancel/abandon operation when the add-on is in the state of downloaded, waiting to be installed/downloading

**Comment by XLTechie** [comment]
I support this feature request. I had the same thought, that pending operations 
should be atomic, and should therefore be cancellable.
