### ISSUE TITLE
After a second installation of an incompatible add-on, this one is disabled after restarting NVDA.

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#15584]
### Steps to reproduce:
install an incompatible add-on for the first time from its installation file.
- restart NVDA.
- check that the add-on is activated.
- install this add-on again without uninstalling it.
- restart NVDA.

The add-on is then deactivated.

### Expected behavior:

The add-on should be activated as when it was first installed.
#### NVDA installed/portable/running from source:
NVDA portable
#### NVDA version:
2023.3Beta4 and alpha
#### Windows version:
Windows 10 22H2 (10.0.19045) workstation x86

#### Does the issue still occur after restarting your computer?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by lukaszgo1** [comment]
Could you please fully fill the issue template?

**Comment by paulber19** [comment]
That's what I think I did, but the copy and paste didn't turn out well.
here is the complement:
- install an add-on for the first time from its installation file.
- restart NVDA.
- check that the add-on is activated.
- re-install this add-on again without uninstalling it.
- restart NVDA.

The add-on is not activated after restarting NVDA.

**Comment by lukaszgo1** [comment]
There is still a lot of important info (which was asked in the template) missing:
- With what add-on you have tested exactly
- Has this worked in NVDA 2023.2

**Comment by paulber19** [comment]
Sorry, I didn't see this request in the template.
It doesn't depend on the add-on.
It just needs to be incompatible.
I haven't tested with 2023.2, but I think the problem is occurring.

**Comment by paulber19** [comment]
In response to the second question:
The problem also occurs with NVDA 2023.2.
