### ISSUE TITLE
Feature request: Natural voices support for windows 11

### ISSUE THREAD

**Issue by dpy013** [nvaccess/nvda#15587]
### Is your feature request related to a problem? Please describe.
Starting with Win11 Build 22631.1835 Narrator officially supports Natural voices
### Describe the solution you'd like
I hope to be able to support natural speech if NVDA support is not too difficult.
### Describe alternatives you've considered
none
### Additional context
[Microsoft documentation](https://support.microsoft.com/en-us/windows/appendix-a-supported-languages-and-voices-4486e345-7730-53da-fcfe-55cc64300f01#WindowsVersion=Windows_11)

**Comment by GeorgeWu3** [comment]
I agree it will be nice.

**Comment by dpy013** [comment]
The main reason is that Natural voices has great voice quality.

**Comment by seanbudd** [comment]
Closing as duplicate of #13288
