### ISSUE TITLE
Python 3.11: include python3.dll as part of binary distribution

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#15594]
Hi,

Part of #12064 work and subsequent pull requests:

### Background:
Recent Python releases defined limited C API for use by extensions. This allows C extensions to create a .pyd file that will work across Python 3.x releases, including 3.6 and later.

### Is your feature request related to a problem? Please describe.
Suppose an add-on uses external libraries interfacing with CPython runtime (usually .pyd files). If these C extensions are written using limited API, it will allow add-ons to work across Python 3.x releases. At the moment these modules must be accompanied by python3.dll from Python 3.7 installation folder because NVDA itself does not include python3.dll as part of binary distribution.

### Describe the solution you'd like
As part of Python 3.11 upgrade, include python3.dll as part of NVDA binary distribution.

### Describe alternatives you've considered
Let add-ons ship with multiple versions of third-party dependencies, one for each Python version NVDA supports.

### Additional context
Add-ons affected include Resource monitor, Sound Splitter, and others using psutil module.

A bigger problem may arise once 64-bit CPython runtime is used as add-ons must include dependencies supporting both 32-bit and 64-bit Python runtime.

Thanks.

**Comment by seanbudd** [comment]
Could you please give a specific use case? This issue was previously rejected as #13645

**Comment by seanbudd** [comment]
i.e. would these add-ons you mention explicitly rely on this if introduced?

**Comment by josephsl** [comment]
Hi,

The mentioned issue was closed as stale i.e. no word from the original poster for some time.

Including python3.dll will allow add-ons relying on packages such as psutil to not duplicate packages to support various NVDA/Python releases. We had to duplicate packages when add-ons transitioned from Python 2 to 3, more so when packages included pyd files, and psutil is one such package used in add-ons. Also, it might be possible that add-ons may need to include newer python3.dll if AppVeyor updates to Python 3.11.6 and later, and if that becomes a case, add-ons must duplicate packages again for the sole reason of including newer python3.dll file and load the correct package based on Python 3.11.x/NVDA release. However, if it turns out python3.dll from 3.11.5 (included in add-ons) will run code from 3.11.6 (newer NVDA releases) happily, then we don't have to duplicate packages for minor 3.11.x releases, but again duplication remains to support NVDA 2019.3 to 2023.3.

Thanks.

**Comment by seanbudd** [comment]
It looks like next BRLTTY release is going to rely on the stable ABI https://github.com/brltty/brltty/commit/12a6d1ca278a07920f0510efb099a0541a4d0239, which makes updating BRLTTY much more straightforward.

**Comment by seanbudd** [comment]
I think this feature is still requested - regardless of BRLTTY (see also #13645)
