### ISSUE TITLE
Ability to have NVDA Present Clipboard Contents in a Browsable Message using Browse Mode

### ISSUE THREAD

**Issue by btman16** [nvaccess/nvda#15593]
### Is your feature request related to a problem? Please describe.
My feature request is not related to a problem. Instead, this would be an enhancement to an existing feature.
### Describe the solution you'd like
NVDA currently has a key to read the text on the Windows clipboard, NVDA+C. While this is very useful, sometimes I would like to be able to examine the clipboard text in further detail.

Another key could be bound, such as NVDA+shift+C, that would present the clipboard content in browse mode using something like ui.BrowsableMessage, similar to what happens when a user presses NVDA+F twice quickly.

The reason I am proposing a new keyboard shortcut instead of NVDA+C pressed multiple times is that in snapshots, NVDA+C pressed multiple times spells the text on the clipboard.
### Describe alternatives you've considered
I am not sure of any alternatives, hence the reason for this feature request, as I am not sure of anything else that could accomplish this. I was told that Clip Contents Designer can do what I'm wanting to accomplish, however I feel that this is something that many users would benefit from, so having it in NVDA Core itself would be beneficial.

**Comment by CyrilleB79** [comment]
I have introduced spelling upon double or triple press of NVDA+C in PR #15504 that originally aimed to solve #15449 (NVDA+shift+upArrow multi-pressed).
While at it, I have also handled NVDA+C to make something consistent.

But if we find that opening a browseable message would be better, we can map it to double press or triple press of NVDA+C. The spell functions on NVDA+C have not yet been released.

However, I think that there is a limitation for the length of the text in browseable messages to render quite quickly. @nvdaes any comment on this?

**Comment by nvdaes** [comment]
I think that there"s a limit in the number of characters of browseable messages, so I set a limit on clipContentsDesigner. I think that default is set to 100000 and max limit to one million. I made tests years ago about this. >hope this helps.Enviado desde mi iPhoneEl 7 oct 2023, a las 23:59, Cyrille Bougot ***@***.***> escribió:﻿
I have introduced spelling upon double or triple press of NVDA+C in PR #15504 that originally aimed to solve #15449 (NVDA+shift+upArrow multi-pressed).
While at it, I have also handled NVDA+C to make something consistent.
But if we find that opening a browseable message would be better, we can map it to double press or triple press of NVDA+C. The spell functions on NVDA+C have not yet been released.
However, I think that there is a limitation for the length of the text in browseable messages to render quite quickly. @nvdaes any comment on this?

**Comment by seanbudd** [comment]
`NVDA+shift+C` is already used for setting column headers.
The spell features introduced in #15504 are more inline with NVDAs UX.
You can always paste into notepad or similar.

This should be introduced as an unbound command or kept as an add-on.

**Comment by XLTechie** [comment]
Doesn't Windows Clipboard History (Win+v) effectively provide what is requested 
here?

It's a pretty limited and crappy interface, but perhaps work could be done to 
improve it.

**Comment by btman16** [comment]
Hi,

Win+V does not provide this functionality for me, as it isn't
convenient to be able to arrow through it in detail with standard
navigation keys.

Thanks,

Brandon

On 10/9/23, Luke Davis ***@***.***> wrote:
> Doesn't Windows Clipboard History (Win+v) effectively provide what is
> requested
> here?
>
> It's a pretty limited and crappy interface, but perhaps work could be done
> to
> improve it.
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/15593#issuecomment-1754073243
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
“Be what you are. This is the first step towards becoming better than you are.”
– J. C. Hare & A. W. Hare

**Comment by Adriani90** [comment]
reporting of clipboard content right away is actually a feature that sighted people do not have, unless you enable clipboard history. so strictly speaking this feature does not belong into NVDA core at all. Reporting the selected text / items with nvda+shift+s or NVDA+shift+up arrow is the feature we should focus on and which should be extended acconrdingly i.e. like proposed in https://github.com/nvaccess/nvda/issues/7414#issuecomment-1854679059.

Additionally improve the support for clipboard content history like proposed in #10597.

I am closing this issue in favor of the other two referenced issues where discussion is broader and can be continued there.
