### ISSUE TITLE
New Setting for Pauses in Line breaks in Edit Fields

### ISSUE THREAD

**Issue by Jykke67** [nvaccess/nvda#15599]

**Comment by Brian1Gaff** [comment]
Which reminds me, there is something weird for Espeak in 20234.1 in that it seems to me that sometimes it tends to leave little gaps in between the first letter in a word and the rest of the word. Its hard to explain though.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by seanbudd** [comment]
Welcome @Jykke67 ,

Please fill out the feature template properly.

Kind Regards,
NV Access Software Developers

**Comment by Jykke67** [comment]
#

**Comment by Jykke67** [comment]
#

**Comment by seanbudd** [comment]
Why did you close this?

**Comment by seanbudd** [comment]
Closed in favour of #15645

**Comment by Jykke67** [comment]
Sean Budd kirjoitti 18.10.2023 klo 0:53:00:

> Why did you close this?

It was closed because of the missing template that should have been filled out. Therefore I opened a new issue with the same subject, and now the template was filled out correctly. Did you notice that?

-- 
Jyrki Voutilainen
***@***.***

**Comment by Jykke67** [comment]
Thanks. It seems that you have mentioned my new issue by the same subject.

Apologies for reacting on my own issue, but just wanted to see how it works. Will not happen in the future. :)

-- 
Jyrki Voutilainen
***@***.***

**Comment by seanbudd** [comment]
It's fine - it's just helpful to add a comment when closing with the reason.

Cheers

**Comment by Jykke67** [comment]
OK. Would have been hard to edit the incorrectly opened issue, but the new one seems fine. Apologies for that mess, will not happen in the future!
