### ISSUE TITLE
Document how translation / localization issues should be reported

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#15627]
### Is your feature request related to a problem? Please describe.
Sometimes, people want to report or even fix translation or localization issues in NVDA's GitHub. For example see:
* Recently PR #15622
* PR #10162, my first PR trial

However, translation is not performed through NVDA GitHub's repo but through SVN repo.

Translation issues are usually reported through various local communities (e.g. user mailing lists) or on the translator's mailing list. This seems to work quite well, at least in the French community.

### Describe the solution you'd like

NV Access (@seanbudd, @Qchristensen?) should indicate the preferred way to report translation issues.

For example:
When people try to report a translation issue through GitHub, indicate that translation issues should preferably be reported through the community.

Somewhere in dev docs or in the PR template (or both), indicate that the modification of NVDA's interface or user documentation should not be done through a PR but through SVN / translators.

### Describe alternatives you've considered
None.

### Additional context

Issue opened following #15622.

**Comment by zstanecic** [comment]
I want to add something here:

I don’t want someone to go to svn and do the mess in my work.

This should be done in a coordinated way.

 

From: Cyrille Bougot ***@***.***> 
Sent: Friday, October 13, 2023 7:50 PM
To: nvaccess/nvda ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nvaccess/nvda] Document how translation / localization issues should be reported (Issue #15627)

 


Is your feature request related to a problem? Please describe.


Sometimes, people want to report or even fix translation or localization issues in NVDA's GitHub. For example see:

*	Recently PR #15622 <https://github.com/nvaccess/nvda/pull/15622> 
*	PR #10162 <https://github.com/nvaccess/nvda/pull/10162> , my first PR trial

However, translation is not performed through NVDA GitHub's repo but through SVN repo.

Translation issues are usually reported through various local communities (e.g. user mailing lists) or on the translator's mailing list. This seems to work quite well, at least in the French community.


Describe the solution you'd like


NV Access ***@***.*** <https://github.com/seanbudd> , @Qchristensen <https://github.com/Qchristensen> ?) should indicate the preferred way to report translation issues.

For example:
When people try to report a translation issue through GitHub, indicate that translation issues should preferably be reported through the community.

Somewhere in dev docs or in the PR template (or both), indicate that the modification of NVDA's interface or user documentation should not be done through a PR but through SVN / translators.


Describe alternatives you've considered


None.


Additional context


Issue opened following #15622 <https://github.com/nvaccess/nvda/pull/15622> .

**Comment by CyrilleB79** [comment]
> I want to add something here: I don’t want someone to go to svn and do the mess in my work. This should be done in a coordinated way.

Of course. This issue is not about granting access to anybody to SVN.

For example, if I remember well, you translate Polish (among other things). This issue is to have a solution so that, say a new Polish user, know how to contact you if they see an issue in the Polish translation so that you can fix it.

**Comment by dpy013** [comment]
Personally, I don't see the point in discussing this.
NVDA is slowly switching to crowdin. 
For more information, please refer to
[Planned Translation System Changes](https://github.com/nvaccess/nvda/discussions/15014)
After the switch is complete
Translation-related issues can be managed using crowdin's
[Discussions](https://crowdin.com/project/nvda/discussions) function.

**Comment by seanbudd** [comment]
@dpy013 - until changes occur its best to keep documentation up to date and accurate.
With the change to crowdin, I don't expect this workflow to change for the average user. 
While we can encourage people to report issues on crowdin, folks may still prefer to raise issues on the translation mailing list.
Unless there are plans for translators to stop using the translations mailing list in favour of just using crowdin.

**Comment by Chealer** [comment]
Greetings,

Thank you for bringing this up, but what you report is not the issue which caused #15622. In fact, this does not report an issue at all.

I do agree that #15622 highlights a meta-issue which should be addressed, but it was not characterized properly. What @mtelgkamp reported is that the instructions at the time for tracking locale issues were poor for his situation, and that the bug reporting template(s) were inappropriate. The latter is now tracked in #19947.

But even fixing those will not provide strong “protection“ against cases like these. Not offering “Fork this repository and edit the file” and “More edit options” on .po files (at least not without a warning) would probably have avoided this, but would still only cover those accessing GitHub from a browser.

To directly and more reliably prevent this, several mitigations/solutions are possible:
1. Add a README to source/locale/.
2. Add a warning header to .po files ([example](https://www.state-machine.com/qm/ce_comment.html#ce_comment_gpl)).
3. Cleanup the path:
   1. Avoid misleading elements like `source/`
   2. Add an element indicating that the directory is secondary.

   For example, change `source/locale/` to `generated/locale/`
4. The definitive solution: remove the copy (unless versioning the strings is better than having them in Crowdin).

[🅭🄍](https://www.philippecloutier.com/Common+infrastructure+licensing#its)

**Comment by CyrilleB79** [comment]
@Chealer, this issue has been validated by NV Access, fixed in #15631 and closed more than 2 years ago.

I am not sure to understand your last comment, but in any case, parts of it are outdated. The subversion (SVN) repo is not used for a long time now for NVDA translation.

Moreover, comments in closed issues are usually not well tracked by NV Access, especially when they are closed for a long time. If you are requesting more changes than the one described in #19947, I'd recommend to open another issue for them.

**Comment by Chealer** [comment]
> [@Chealer](https://github.com/Chealer), this issue has been validated by NV Access, fixed in [#15631](https://github.com/nvaccess/nvda/pull/15631) and closed more than 2 years ago.

This is not an issue. It's a _request_ (which was already fulfilled when it was formulated).

> I am not sure to understand your last comment, but in any case, parts of it are outdated. The subversion (SVN) repo is not used for a long time now for NVDA translation.

Ah, sorry and thank you Cyrille, I updated that part. Let me know in case anything else would need revision.
