### ISSUE TITLE
TTS only for selected text

### ISSUE THREAD

**Issue by henriqueArrazao** [nvaccess/nvda#15626]
### Is your feature request related to a problem? Please describe.
Yes, I don't want to hear every single word my mouse is on, only the select the text.

### Describe the solution you'd like
When I select/highlight a text in any application and press a shortcut in my keyboard, the selected text should be spoken.

### Describe alternatives you've considered
None.

### Additional context
None.

**Comment by hwf1324** [comment]
Related to #15336

**Comment by henriqueArrazao** [comment]
> Related to #15336

Horrible work around to be honest

**Comment by henriqueArrazao** [comment]
Is there any alternative software for windows 11 perhaps?

**Comment by hwf1324** [comment]
> Is there any alternative software for windows 11 perhaps?

Perhaps you can try using "Windows Magnifier"

**Comment by henriqueArrazao** [comment]
> > Is there any alternative software for windows 11 perhaps?
> 
> Perhaps you can try using "Windows Magnifier"

Most of the times it selects the whole paragraph or line, etc 🫤 Instead of the selected text only

**Comment by hwf1324** [comment]
> Most of the times it selects the whole paragraph or line, etc 🫤 Instead of the selected text only

In my case, select a piece of text and then press `Ctrl+Alt+Enter`, it will be read out loud in the narrator's voice. At the same time, it will be highlighted

**Comment by henriqueArrazao** [comment]
> > Most of the times it selects the whole paragraph or line, etc 🫤 Instead of the selected text only
> 
> In my case, select a piece of text and then press `Ctrl+Alt+Enter`, it will be read out loud in the narrator's voice. At the same time, it will be highlighted

Love you bro, thankss
