### ISSUE TITLE
more configuration profile triggers

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#15659]
I would like more triggers for configuration profiles. example: I would like triggers on either a global, or app by app basis, for when a certain screen appears, disappears, if a certain object, text in a certain object, the colors of a certain on-screen object or the fonts or styles of a certain object should change which could trigger a configuration profile to activate. I would also like to be able to have configuration profiles activate, or switch profiles, if certain keyboard keys or combinations of keys are pressed. This would let me silence speech in outlook messages, and then switch to a different one once a say-all command or arrows are pressed, or if i escape out of the message and back to the listbox of messages, then a new configuration profile would be triggered to activate. Another example: I bring up a web video, on a certain website, a configuration profile would load which would set my NvDA to speech mode beeps.

**Comment by lukaszgo1** [comment]
@joshknnd1982  This is not actionable. Please edit the initial comment following the feature request template. Unless this is done I propose to close this issue as invalid.

**Comment by seanbudd** [comment]
Welcome @joshknnd1982,

We are unable to process this issue as it stands.

Please open a [new issue](https://github.com/nvaccess/nvda/issues/new?assignees=&labels=&projects=&template=feature_request.md) and fill out the feature request template fully.

Kind Regards,
NV Access Software Developers
