### ISSUE TITLE
Braille Viewer in NVDA is not displaying the label of a multiline input element.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#15678]
### Steps to reproduce:

1. Turn on NVDA screen reader and open Braille viewer.
2. Open the url [Fluent UI - Controls - React - TextField (microsoft.com)](https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield).
3. Navigate to Multiline TextField.
4. Observe the issue in Braille viewer.

### Actual behavior:
Braille Viewer in NVDA don't display the label of a multiline input element and displaying as blank.

### Expected behavior:
Braille viewer in NVDA should provide the details of label for the multiline input field, along with value of the input field.

### NVDA logs, crash dumps and other attachments:
[NVDA - Multiline input behaviour in Braille dispaly.webm](https://github.com/nvaccess/nvda/assets/93735775/78256b42-4783-41a8-9050-275240ca9946)

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors. 
No

**Comment by seanbudd** [comment]
This is intended behaviour. To read the label, scroll backwards on the multiline edit control.
