### ISSUE TITLE
a button which toggles the visibility of elements in a list skips the first "visible" element after the toggle

### ISSUE THREAD

**Issue by bbudd** [nvaccess/nvda#15672]
Hi there! I have a list of 5 items, the 3rd, 4th, and 5th items using `visibility: hidden`. The second item in the list is a button which sets the visibility of #1 and 2 to `hidden` and sets the visibility of 3, 4, and 5 to `visible`. Once I toggle the visibility, the third item (the "next" item in the list) gets skipped using the down buttons to navigate through the list.

To clarify something here, I'm not using "list" to mean the HTML definition of `ol` or `ul`, just "list" as shorthand for 5 successive elements.

### Steps to reproduce:
1. Navigate to https://codepen.io/bbudd/pen/JjxobdR
2. Put  focus into the preview frame
3. Navigate down to the "button show others"
4. Hit enter to click the button 
5. Use the down arrow to read the next item

### Actual behavior:

CodePen Preview  frame    one  show others
button    show others
button
four
five

### Expected behavior:

CodePen Preview  frame    one  show others
button    show others
button
three
four
five

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2023.2.0.29051
(same behavior in earlier versions of NVDA)

#### Windows version:
10.0.23545 Build 23545
(same behavior in other versions of windows)

#### Name and version of other software in use when reproducing the issue:
Edge browser

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, same behavior

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by michaelDCurran** [comment]
This is expected behaviour as when the button disappears, the content after moves up to where the button was. When pressing the button, verify that you are now on item 3 by speaking the current line. 
I cannot imagine an alternative here as the caret must go somewhere after the button disappears.
