### ISSUE TITLE
esp32 microController is identified as Caiku Albatross 46/80 braille display

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#15671]
### Steps to reproduce:
Plug esp32 pico board like m5stack device into usb port
### Actual behavior:
After starting NVDA, if autodetect braille display is selected, it identifies this esp32 board as braille display and is sending commands of pressing routing, wheel or other buttons
### Expected behavior:
NVDA should not identify esp32 boards as braille displays
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Version: alpha-29610,03c8abe6 (2024.1.0.29610)
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3448
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, latest master code
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment]
@beqabeqa473, have you tested NVDA 2023.3rc1?
If the issue is also there, it would be worth mentioning it.
And if you have not tested, it would be worth testing it.

**Comment by CyrilleB79** [comment]
Cc @burmancomp

**Comment by beqabeqa473** [comment]
Issue is occuring also in nvda-2023.3 RC1

On 10/23/23, Cyrille Bougot ***@***.***> wrote:
> Cc @burmancomp
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/15671#issuecomment-1775231592
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by burmancomp** [comment]
If it has same pid&vid and if it sends packet starting with \xff and after it any other byte albatross driver has detected albatross braille display. I suppose controller has serial port shown in windows? Other displays (at least many of them) wait that they are queried but albatross sends initialization packet continuously so driver detects it reading bytes. Suggestion is that albatross is excluded from auto detect list.

**Comment by seanbudd** [comment]
Yes, you'll have to exclude the albatross display in settings.
It seems that the albatross hardware uses this device, and is likely indistinguishable.

**Comment by beqabeqa473** [comment]
It is not a case.

In this situation might be not only me, and i advice to disable it by default from autodetection, as this might cause some serious issues. @seanbudd

**Comment by burmancomp** [comment]
besides me there are no others using albatross actively, and there are very few devices (my estimation is about 5), and at least one is not working properly.

Excluding albatross by default from auto detection is not problem.

**Comment by lukaszgo1** [comment]
Looking at the [BRLTTY driver for Albatross](https://github.com/brltty/brltty/blob/master/Drivers/Braille/Albatross/braille.c) it turns out that  in addition to matching on PID&VID they also match on a manufacturer name `"Tivomatic Oy"`. This suggests that the problem is, at least in theory, fixable, though if it is worth the effort for a very few users is an open question.

**Comment by beqabeqa473** [comment]
Blind developer can develop for firmware for esp32 micro-controller.
This particular dev cannot be known to know about this particular issue.
If they plug this board into computer and nvda will make some actions,
like activating some controlls which might make bad actions, this
responsibility would be on shoulders of that people who thought about
efforts for not taking actions just for few users.
It is very serious issue, which should be fixed as soon as possible to
eliminate false-positive reactions from screenreader.
For me for example, it clicked on close button of a cmd window. It is
good that this cmd window was not so useful, but what if nvda could
activate a wrong button and thing on what i was working just would
threw as a trash?
It is not serious at least.
Albatros displays should be excluded by default from autodetection
list if that couldn't be fixed in other way and be noted in user guide
for users who have such displays to enable it manually.

On 10/24/23, Łukasz Golonka ***@***.***> wrote:
> Looking at the [BRLTTY driver for
> Albatross](https://github.com/brltty/brltty/blob/master/Drivers/Braille/Albatross/braille.c)
> it turns out that  in addition to matching on PID&VID they also match on a
> manufacturer name `"Tivomatic Oy"`. This suggests that the problem is, at
> least in theory, fixable, though if it is worth the effort for a very few
> users is an open question.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/15671#issuecomment-1777936110
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by seanbudd** [comment]
@burmancomp 

>Looking at the [BRLTTY driver for Albatross](https://github.com/brltty/brltty/blob/master/Drivers/Braille/Albatross/braille.c) it turns out that in addition to matching on PID&VID they also match on a manufacturer name "Tivomatic Oy". This suggests that the problem is, at least in theory, fixable, though if it is worth the effort for a very few users is an open question.

Can you confirm this is a reliable way to detect albatross drivers?

**Comment by burmancomp** [comment]
As to brltty source code there are handytech and hims displays with same vid and bit as albatross. In those drivers manufacturer is ftdi. In windows usb serial port of albatross is as ftdi usb port.

There is no other driver albatross uses in windows so very likely there are no references to tivomatic.

I can investigate it little however.

**Comment by burmancomp** [comment]
But there is also ftdi driver in usb drivers category: usb serial converter. In properties, details tab, there is bus reported device description which value is albatross braille display. This value should not be same with esp32.

How to check this in albatross driver?

**Comment by beqabeqa473** [comment]
i don't know, but simple plug in of esp32 starts the show.

On 10/26/23, burmancomp ***@***.***> wrote:
> But there is also ftdi driver in usb drivers category: usb serial converter.
> In properties, details tab, there is bus reported device description which
> value is albatross braille display. This value should not be same with
> esp32.
>
> How to check this in albatross driver?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/15671#issuecomment-1780007345
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by lukaszgo1** [comment]
I haven't worked at that  low level, and not having a device to test does not help,  but I'd probably start investigating as follows:
- in `hwPortUtils.listComPorts` try logging the entire `hwID`, to make sure there is no manufacturer mentioned there
- In the same function verify what is `friendlyName` set to for these ports, though that may not yield anything useful
- For more inspiration you may also take a look at `_getHidInfo` in the same module, as that function retrieves additional info from the device

**Comment by LeonarddeR** [comment]
@beqabeqa473 wrote:
 
> It is very serious issue, which should be fixed as soon as possible to eliminate false-positive reactions from screenreader.

If this issue is that serious to you, could you please address repeated request for feedback in https://github.com/nvaccess/nvda/pull/15693 ? Otherwise it cannot be guaranteed that the problem will be solved in 2024.1.

**Comment by beqabeqa473** [comment]
I am sorry for delays. Was busy with work due to some health
conditions i was away from development for a while.
I will be back with results in a few minutes.

On 12/12/23, Leonard de Ruijter ***@***.***> wrote:
> @beqabeqa473 wrote:
>
>> It is very serious issue, which should be fixed as soon as possible to
>> eliminate false-positive reactions from screenreader.
>
> If this issue is that serious to you, could you please address repeated
> request for feedback in https://github.com/nvaccess/nvda/pull/15693 ?
> Otherwise it cannot be guaranteed that the problem will be solved in
> 2024.1.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/15671#issuecomment-1851385286
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili
