### ISSUE TITLE
whenever i enable unsupported add-ons, then the speech stops.

### ISSUE THREAD

**Issue by bobbysingh2005** [nvaccess/nvda#15694]
### Steps to reproduce:

[nvda.log](https://github.com/nvaccess/nvda/files/13184885/nvda.log)

**Comment by seanbudd** [comment]
Please fill out the issue template

**Comment by seanbudd** [comment]
This looks like an issue with Tony's enhancement add-on relying on private API functionality. Please report it to Tony [here](https://github.com/mltony/nvda-tonys-enhancements)
Thanks

**Comment by CyrilleB79** [comment]
Use Tony's Enhancements 1.16 instead.
