### ISSUE TITLE
 Pressing space only works sometimes when in focus mode when on youtube.

### ISSUE THREAD

**Issue by audiogamer22** [nvaccess/nvda#15707]
### Steps to reproduce:
Make sure you have the latest version of NVDA and go to youtube.com and load a video, then press NVDA space, now press space to try and play/pause the video.
### Actual behavior:

Nothing happens when you press space when you're meant to be able to play/pause the video.
### Expected behavior:

The video should play/pause.
### NVDA logs, crash dumps and other attachments:
https://ln5.sync.com/dl/0dd57e740/mhs9dv4s-93d59pwz-azcpkmf2-8phnk37c
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
NVDA version 2023.2
#### Windows version:
Version 22H2 (OS Build 22621.2506)
#### Name and version of other software in use when reproducing the issue:
The latest version of Firefox.
#### Other information about your system:
Device name	Brad
Processor	11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz   2.69 GHz
Installed RAM	8.00 GB (7.73 GB usable)
Device ID	CF0B6F41-1851-4911-AB5B-1652D2500E9F
Product ID	00342-20989-33205-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

#### Does the issue still occur after restarting your computer?
Yes.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by Adriani90** [comment]
I can reproduce this issue ion all browsers actually.

Str:
1. Make sure NVDA loads browse mode on page load in browse mode settings is enabled
2. Make sure automatically move system focus to focusable elements is disabled
3. Open a browser and open a video on Youtube
4. While in Browse mode, navigate with arrow keys or with the "b" key to the video controls
5. When you land on the button "pause", press nvda+space bar to enable focus mode
6. Press space bar to pause or play the video
7. Press enter to pause and play the video

Actual:
When switching to focus mode, via nvda+space for the first time, space bar does not work. If you press tab and shift+tab, the system focus is synchronized properly and pausing the viode via space bar works as usual.

Expected:
Space bar for pausing and playing videos should work also when enabling focus mode for the first time with nvda+space bar.

It seems NVDA cannot synchronize the system focus properly on these video controls when switching to focus mode. cc: @jcsteh any idea on this?

**Comment by jcsteh** [comment]
The focus does get synchronised correctly. If I press NVDA+tab after switching to focus mode, NVDA reports that the play button has focus. It just ignores the space and enter keys.

I think this needs to be reported to YouTube.

**Comment by seanbudd** [comment]
This is an authoring issue and need to be reported to YouTube
