### ISSUE TITLE
NVDA is not reading a complete word

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1570]
**Reported by shobana on 2011-06-16 06:21**
I am using open office 2.0 writer localized  for Malayalam language (India) .when I type a words and press ctrl+right or left keys to read word by word ,it is reading only sub words ( words are split with vowel signs)not the complete word but when I press ctrl+down key to read a line ,it is reading perfectly..

Note : accessbridge2_0_2 is used.

**Comment by ehollig** [comment]
Open Office is discontinued acording to [Wikipedia](https://en.wikipedia.org/wiki/OpenOffice.org). Unless there are other things addressed in this issue that I am missing, I think it can be closed.

**Comment by derekriemer** [comment]
closing, as per this now being IAccessible2, it probably works (We don't need jab anymore).
