### ISSUE TITLE
Pressing space only works sometimes when in focus mode when on youtube.

### ISSUE THREAD

**Issue by audiogamer22** [nvaccess/nvda#15704]
<!-- Please read the text in this edit field before filling it in.
Please thoroughly read NVDA's wiki article on how to fill in this template, including how to provide the required files.
Issues may be closed if the required information is not present.
https://github.com/nvaccess/nvda/blob/master/projectDocs/issues/githubIssueTemplateExplanationAndExamples.md
Please also note that the NVDA project has a Citizen and Contributor Code of Conduct which can be found at https://github.com/nvaccess/nvda/blob/master/CODE_OF_CONDUCT.md. NV Access expects that all contributors and other community members read and abide by the rules set out in this document while participating or contributing to this project. This includes creating or commenting on issues and pull requests. 

Steps to reproduce:
Open youtube.com and load a video, go into focus mode and press space.
Actual behavior:
Pressing space doesn't play/pause the video, apart from when it does... Pressing enter or k works fine though.
Expected behavior:
NVDA should play/pause the video.
NVDA logs, crash dumps and other attachments:
https://ln5.sync.com/dl/0dd57e740/mhs9dv4s-93d59pwz-azcpkmf2-8phnk37c
System configuration
NVDA installed/portable/running from source:
Installed.
NVDA version:
2023.2
Windows version:
Version 22H2 (OS Build 22621.2428)
Name and version of other software in use when reproducing the issue:
The latest version of Firefox.
Other information about your system:
Other questions
Does the issue still occur after restarting your computer?
Yes
Have you tried any other versions of NVDA? If so, please report their behaviors.
If NVDA add-ons are disabled, is your problem still occurring?
Yes.
Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Brian1Gaff** [comment]
You really do need to fill out the template, or nobody will do anything. All the details of versions and browsers and what other add ons are in use is the only way to see if the problem is seen by just you, or others. If the devs cannot see the problem they cannot fix it. Their crystal ball is not working just now :-)

Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by CyrilleB79** [comment]
Hi @audiogamer22 

We are unable to process this issue as it stands.
Please open another issue filling all the fields of the template.
Thanks.
