### ISSUE TITLE
Silent Install

### ISSUE THREAD

**Issue by joachimlindenberg** [nvaccess/nvda#15713]
### Is your feature request related to a problem? Please describe.

I need to maintain multiple install and prefer automation of updates

### Describe the solution you'd like

Most installers have a feature silent installation or silent upgrades. Can you please consider adding an installer option or if already existant, document this (I tried nvda_2023.3.exe /Silent, nvda_2023.3.exe /?). For updates there is imho also no need to accept anything.

**Comment by joachimlindenberg** [comment]
@Qchristensen thanks a lot! May I then suggest to add /? with some help and the link to documentation? Windows users more often try /? than -h...

**Comment by Brian1Gaff** [comment]
Not sure that is true.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by Qchristensen** [comment]
Just responding to @joachimlindenberg's request for a help command:

Either:
-h  or --help
will show command line help and exit.
