### ISSUE TITLE
Emoji/symbols partially broken

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#15714]
Hi,
I'm quite sure it's a decoding issue appeared with Python 3.11 switch.
In any case...

### Steps to reproduce:

1. Open Symbol pronunciation dialog;
2. write "face" in filter box;
3. scroll results at least until "smiling face".

### Actual behavior:

NVDA reads nothing for first column, in the majority of cases.

### Expected behavior:

NVDA should say the symbol in the first column, like still do for "smiling face":
☺; Replacement: smiling face; Level: none; Preserve: never  18 of 138

### NVDA logs, crash dumps and other attachments:

None.

#### NVDA installed/portable/running from source:

Running from source (but I tried also some snapshots of last days).

#### NVDA version:

NVDA version source-master-3ac42fe.

#### Windows version:

Windows 10 22H2 (10.0.19045) workstation AMD64.

#### Name and version of other software in use when reproducing the issue:

None.

#### Other information about your system:

None.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

2023.3rc2 works ok.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Not tried in this specific case, but I ran it recently.

**Comment by ABuffEr** [comment]
CC: @OzancanKaratas

**Comment by OzancanKaratas** [comment]
Since you're more familiar with Python than I am, would you like to help me out @CyrilleB79?

**Comment by CyrilleB79** [comment]
For characters 😃 (CLDR = grinning face with big eyes, char number = 0x1f603), in last alpha we have instead:
character 0xd83d which maps to a character from Surrogate category, bloc High Surrogates, which has no sense in Python 3 strings. Visually, the character looks like a square, which is what is displayed for non displayable characters.

I do not know if this bug is coming from Python 3.11 or new wxPython release.

**Comment by seanbudd** [comment]
I think this is this wxWidgets bug https://github.com/wxWidgets/wxWidgets/issues/23750 with workarounds noted in the issue discussion

**Comment by ABuffEr** [comment]
Hi @seanbudd,
I looked at linked discussion, but it seems that the simplest fix, using SetTechnology(wxSTC_TECHNOLOGY_DIRECTWRITE), is related to wx.stc, that apparently lacks from wx modules included into NVDA. So, I'm not sure it's a solution, good for a PR. I don't know wx so well to understand the other suggestions to workaround the issue.

**Comment by seanbudd** [comment]
I have no problem importing `wx.stc.STC_TECHNOLOGY_DIRECTWRITE` and `wx.stc.StyledTextCtrl` on the master branch in NVDA source code

**Comment by ABuffEr** [comment]
Hi,
I found the exact bug, in [that old issue](https://github.com/wxWidgets/Phoenix/issues/2446). Looking for a workaround.

**Comment by ABuffEr** [comment]
Hi @seanbudd,
I cannot find a solution, like wxMonkeyPatches. Any possibility to fix the issue into 2024.1? Maybe compiling wx without [29520a1 commit](https://github.com/wxWidgets/Phoenix/commit/29520a122a5a7c34cbd9951102562297a6b5afb5)?

**Comment by seanbudd** [comment]
I've asked wxWidgets to fix Windows snapshot builds, so we could use the fix for https://github.com/wxWidgets/Phoenix/issues/2446 which landed in master

https://github.com/wxWidgets/Phoenix/issues/2489

**Comment by lukaszgo1** [comment]
Has it been considered to simply create the wheel of wx Python ourselves based on the release 4.2.1, with addition of `0dcd064`?  Using some wheel build from master means we are on much less tested code, and if any other fix is identified, we would have to report it, and hope it is addressed in time for NVDA 2024.1. Essentially this means we may be using an ever moving target. Compiling ourselves with a specific fix included is more work in the short term, but seems much safer.

**Comment by seanbudd** [comment]
I think we have some time to wait to see if a 4.2.2 is released, it looks like there's been activity lately including updating their version of wxWidgets. Even if instead alpha builds are fixed instead of 4.2.2, wxPython isn't not super active, using an alpha build will be relatively low risk compared to 4.2.2. My perception of their release cycle is: some work gets merged in a batch, and then a release is tagged. We can always create a patched fork as a back up if there is no 4.2.2/alpha build, or if we find issues with newer official builds.

**Comment by ABuffEr** [comment]
Hi,
apparently, the fix has been included in alpha builds, but no updated snapshot for Windows at the moment.

**Comment by ABuffEr** [comment]
Hi @seanbudd,
any news on this? I see someone suggested wheel from Azure, but is it a doable solution?

**Comment by seanbudd** [comment]
@ABuffEr - I think we could test using the Azure build but I wouldn't package it with the release as downloads are often ratelimited from these services - i.e. the release process or NVDA devs might get blocked from building if the wheel download fails

**Comment by seanbudd** [comment]
2024.1 is going to have a long beta period - if we approach the RC without a new stable wxPython release we will consider building from scratch with the patch, or incorporating the azure build into the release temporarily

**Comment by britechguy** [comment]
Have these emoji characters been removed from the Punctuation/Symbol list?   I just tried the steps outlined in the original issue report and entering "face" (no quotes) in the filter box returns one, and only one, symbol - Surface integral.

**Comment by hwf1324** [comment]
> Have these emoji characters been removed from the Punctuation/Symbol list? I just tried the steps outlined in the original issue report and entering "face" (no quotes) in the filter box returns one, and only one, symbol - Surface integral.

No, this Issue still exists.

Emoji data is generally inherited from CLDR, so if you are using a language other than English, you may need to search for it by typing in the pronunciation that corresponds to your language.

**Comment by britechguy** [comment]
But the only language I use is English.  And, as I said, if I enter "face" in the Symbol/Punctuation filter only a single item shows, and it's a mathematical symbol.

If there's something else I need to check and turn on/off or otherwise tweak, I'm happy to do it.  I'm simply reporting what's happening here on my machine when I follow the original issue recreation steps.

**Comment by CyrilleB79** [comment]
> Have these emoji characters been removed from the Punctuation/Symbol list?

No.

> I just tried the steps outlined in the original issue report and entering "face" (no quotes) in the filter box returns one, and only one, symbol - Surface integral.

I have 138 items containing "face" instead.
You have probably unchecked "Include Unicode Consortium data (including emoji) when processing characters and symbols" in Speech settings. Check it again and you'll get back the symbols.

**Comment by hwf1324** [comment]
> You have probably unchecked "Include Unicode Consortium data (including emoji) when processing characters and symbols" in Speech settings. Check it again and you'll get back the symbols.

Yes, I forgot to add that.

**Comment by britechguy** [comment]
Cyrille,

You are correct about that setting, but I have no recollection whatsoever of ever having touched it.  Is it typically checked by default?

**Comment by britechguy** [comment]
As an aside, but a potentially very useful one, if that setting is unchecked, does that mean that emoji characters as a class are effectively "silenced?"  - that NVDA would never announce them?   If so, that could be a very handy thing for those who don't want emojis read to uncheck.

**Comment by hwf1324** [comment]
> As an aside, but a potentially very useful one, if that setting is unchecked, does that mean that emoji characters as a class are effectively "silenced?" - that NVDA would never announce them? If so, that could be a very handy thing for those who don't want emojis read to uncheck.

Yes, if the synthesizer doesn't handle them by default.

But CLDR may have more than just emoticons, or the translator may override them in symbols*.dic

**Comment by britechguy** [comment]
> Yes, if the synthesizer doesn't handle them by default.

Thanks, but that probably means the problem will still exist with many synths.  These things have become so ubiquitous that the processing of them has become almost equally so.

It would be so nice to have a "silence emoji" capability.
