### ISSUE TITLE
Controller client library for ARM64 is called nvdaControllerClient32.dll

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#15717]
### Steps to reproduce:
1. run `scons client`
2. Go to `extras\controllerClient\arm64`

### Actual behavior:
Resulting ddl is called `nvdaControllerClient32.dll`

### Expected behavior:
Something diffferent

### Additional context
The library is called `nvdaControllerClient64.dll` for x86_64, otherwise it is called `nvdaControllerClient32.dll`.

### Proposed fix
I propose removing the architecture suffix from the dll name. The architecture is clear from the folder the dll is bundled in. Furthermore, X64 examples like the C# and Python ones don't run on X64 without changes.

**Comment by OzancanKaratas** [comment]
I think the suggestion in issue 13526 is pragmatic. In my opinion, implementing the controller client as a COM object and registering it system-wide would be a solution that is architecture-independent and suitable for use by proprietary software.

**Comment by leonardder** [comment]
Thanks for the reminder, but that's at least out of scope for this issue.
