### ISSUE TITLE
Introduce Click-to-Interact Functionality for Recognized OCR Text

### ISSUE THREAD

**Issue by vadimkholodilo** [nvaccess/nvda#15724]
### Is your feature request related to a problem? Please describe.
No
### Describe the solution you'd like
Whenever text of a window is recognized by OCR, it would be awesome to be able to click on any text, and if the text is represents a button or a checkbox, it would be activated. It might help in situations when an application is not keyboard-accessible
### Describe alternatives you've considered
I don't know, if there are solutions on Windows, but there is one on Linux which does exactly what I mean. Here is a link to the software: https://github.com/chrys87/ocrdesktop

**Comment by mzanm** [comment]
You can already do this, on laptop layout you press nvda shift m to move the mouse to the location of the character under the cursor, then you press nvda [ to left click or ] to right click.

**Comment by seanbudd** [comment]
Closing as fixed
