### ISSUE TITLE
More clarity on update policy

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#15726]
You have arrived at the blank issue template from submitting issues.
It is preferable to [choose a type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Your issue may be closed if you do not follow one of the following issue templates.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

**Comment by Adriani90** [comment]
Template is not filled.

**Comment by XLTechie** [comment]
Brian, there is quite literally no content in your initial comment that opened 
this thread, as you can see if you look at this issue on the web.
All there is, is the header of the default issue template, which nobody should 
be using even if it was filled in.

I don't know how you got to that, but in the future, please go to 
https://github.com/nvaccess/nvda/issues/new/choose
and use one of the templates there for filing your issues.

Also, don't delete anything in the comment field. Just move to the lines 
starting with multiple number signs, and enter your answers below them.
