### ISSUE TITLE
likely bug in oneCore.py

### ISSUE THREAD

**Issue by NSoiffer** [nvaccess/nvda#15723]
While trying to track down a problem with an espeak voice, I noticed this likely bug in synthDrivers/oneCore.py:
```
	def _set_rateBoost(self, enable):
		if enable == self._rateBoost:
			return
		# Use the cached rate to calculate the new rate with rate boost enabled.
		# If we don't, getting the rate property will return the default rate when initializing the driver and applying settings.
		rate = self._rate
		self._rateBoost = enable
		self.rate = rate
```
I believe the last line should be 
```
self._rate = rate
```
There is no other occurrence of `self.rate`.

FYI: the similar function in espeak.py doesn't use `_rate`, so maybe it is a copy paste error? Note that it uses the local var `rate` as a temp just as the above code does, but the above code fails to restore the original value unlike the code below.
```
	def _set_rateBoost(self, enable):
		if enable == self._rateBoost:
			return
		rate = self.rate
		self._rateBoost = enable
		self.rate = rate
```

**Comment by seanbudd** [comment]
Hi @NSoiffer,

We are unable to process this issue as it stands.
Please fill out the bug template fully. What is the change of behavior? What issue occurs for the user? What behavior should happen instead?


Kind Regards,
NV Access Software Developers

**Comment by CyrilleB79** [comment]
@NSoiffer wrote:
> There is no other occurrence of self.rate.

No, but executing:
`self.rate = rate`
actually executes:
`self._set_rate(rate)`

`self._set_rate` not only executes:
`self._rate = rate`
but also performs additional processing.

I'll close this issue as invalid.

@NSoiffer, if you still think there is a bug, please describe it more specifically and we can reopoen.
