### ISSUE TITLE
check for updates from rc copies

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#15727]
### Is your feature request related to a problem? Please describe.
Update check in RC of a new version asks the questions, and then exits with no message
### Describe the solution you'd like
If it is indeed the case that you do not want RC users to do the final update, either a message to that effect should replace the new update is available message, or you should be given the opportunity to choose to stay on the update channel you are on.
### Describe alternatives you've considered
Not allowing check for updates in RC, which then precludes you doing an update except via the web links or leaving as it is, which may confuse those trying the RC, when it suddenly goes away. My previous comment has another suggestion. After all, in the Add on store you can change updat channels so allowing that here would seem to be consistant.
### Additional context
I think I said it all.

**Comment by seanbudd** [comment]
Hi Brian,

Without more information in your issue, my understanding is you are describing the following situation.

- You are on Windows 7 (which OS are you on?)
- You are using NVDA 2023.3rc1/2023.3rc2 (which RC are you on?)
- You perform a manual check for update (is this a manual or automatic check ?)
- You are notified about the 2023.3 update
- The update to 2023.3 fails

If an expected task fails, this is a bug.
Please reopen using a bug template, as you are missing a lot of useful information.
We need a log of this behaviour and clearer steps to reproduce.

Thanks,
Sean
