### ISSUE TITLE
The NV Access Get Help page regarding the steps for accessing the user guide needs to be updated.

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#15737]
Since #15688 was merged, the wording of many external tutorials is now misleading. This also includes individual pages of NV Access.

The wording below is currently no longer in use.

> You can access the User Guide at any time under “Help” in the NVDA menu. Press either INSERT and the “N” key, or CAPS LOCK and the “N” key to open the NVDA menu. Alternatively, click on the NVDA icon in the task bar.

The text above comes from [here](https://www.nvaccess.org/get-help/)

**Comment by seanbudd** [comment]
@Qchristensen - can you investigate updating the website when 2024.1 is released?
I will add this to the milestone so we remember to do this closer to the release date.

@cary-rowen - are you aware of any other NV Access documentation that has this issue?

**Comment by cary-rowen** [comment]
Hi @seanbudd 

> Are you aware of any other NV Access documentation that has this issue?

If I find anything else related to this I will update here.

Thanks

**Comment by seanbudd** [comment]
Closing in favour of #15749
