### ISSUE TITLE
"Configuration profiles" and "Check for updates" share their accelerator key

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#15740]
### Steps to reproduce:
1. Open NVDA Menu
2. Press c

### Actual behavior:
Configuration profiles gets focus but isn't activated.

### Expected behavior:
Configuration profiles is activated instantly.

### Additional context
This was introduced in #15688

### Proposed fix
Use `u` as the accelerator for `Check for updates`

**Comment by lukaszgo1** [comment]
Given that, according to @seanbudd 's comments in #15688, 'check for updates' was supposed to remain in the help menu, I suggest to move it back there to fix this issue.
