### ISSUE TITLE
wxPython 4.2.1/touch handler: argument 1 has unexpected type "float"

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#15742]
Hi,

Possibly a regression introduced with wxPython 4.2.1 upgrade:

### Steps to reproduce:
Prerequisites: a touchscreen computer with NVDA installed.

Run NVDA with a touchscreen computer and try tapping on the screen in rapid succession (for example, when invoking an object).

### Actual behavior:
ERROR - core.CorePump.Notify (06:43:35.155) - MainThread (16124):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 759, in Notify
  File "touchHandler.pyc", line 285, in pump
TypeError: Timer.Start(): argument 1 has unexpected type 'float'

### Expected behavior:
No errors.

### NVDA logs, crash dumps and other attachments:
See above for the traceback.

#### NVDA installed/portable/running from source:
Instaled

#### NVDA version:
Alpha 29844

#### Windows version:
Windows 11 23H2 beta (build 22635)

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
Development workstation

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No issues with 2023.3 and earlier

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not applicable

### Additional contxt:
Looks like wx.Timer wants integer as first parameter (timer interval). I'm sure this is just one instance where a float is passed in. One solution is converting the interval (and its multiple) into an integer.

Thanks.

**Comment by seanbudd** [comment]
I'll look into fixing this and other instances of `.Start`.

**Comment by seanbudd** [comment]
it appears this is the only instance with `.Start` using a float as an argument
