### ISSUE TITLE
Braille doesn't update when navigating between two FakeTableCell objects

### ISSUE THREAD

**Issue by Emil-18** [nvaccess/nvda#15755]
### Steps to reproduce:
* Open, for example, the add-on store and use object navigation to go between the column information, such as name, version, etc
### Actual behavior:

Braille gets stuck on the first column. This is because NVDA thinks all FakeTableCell objects is equal, obj1 == obj2 always returns True
### Expected behavior:

Braille should be updated as normal
### NVDA logs, crash dumps and other attachments:
n/a
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2023.3
#### Windows version:
n/a
#### Name and version of other software in use when reproducing the issue:
n/a
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
every version I have tried has this issue
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
cc: @burmancomp

**Comment by burmancomp** [comment]
@Emil-18 did you get vs 2022 problem solved?

**Comment by Emil-18** [comment]
@burmancomp Nope. I tried to install the spector mitigation tools, but I still got the same error. I have made a fix for #15755, but I am unable to test it, and therefor I am hesitent to make a pull request for it, even tho I am 99% sure that it works

**Comment by burmancomp** [comment]
I am not sure what solved vs 2022 problem. Which vs 2022 did you install? I installed community version. There was update (shown in installer) and after that I did not get error. Did you try to import NVDA's .vsconfig?

I encourage you to open pull request. I think I tested your solution (or practically similar) locally a couple of weeks ago when you told how it should be solved.

**Comment by CyrilleB79** [comment]
> @burmancomp Nope. I tried to install the spector mitigation tools, but I still got the same error. I have made a fix for #15755, but I am unable to test it, and therefor I am hesitent to make a pull request for it, even tho I am 99% sure that it works

@Emil-18, if you have a fix, it would be worth opening the PR. In the PR, indicate clearly that you have not been able to test and why.

You can also add a test plan such as: "Ask someone else to test". Someone else can test for you if needed, either using the build generated by your PR as a portable temporary NVDA or testing from source.

**Comment by Emil-18** [comment]
@burmancomp It worked after I updated visual studio. Thanks for the help!
