### ISSUE TITLE
Papenmeier Braillex newer models doesn't start

### ISSUE THREAD

**Issue by towebo** [nvaccess/nvda#15761]
### Steps to reproduce:
1. Unplug the Braillex USB device from the computer.
2. Plug it in and restart NVDA.
### Actual behavior:

The device just shows it's name and revision on the cells regardless what you try to shake life in it.
### Expected behavior:

The device should start showing text on its cells.
### NVDA logs, crash dumps and other attachments:
Log from newly plugged in Braillex display and start of NVDA:
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (23:13:40.649) - MainThread (4472):
registering pre_configSave action: <class 'brailleDisplayDrivers.papenmeier.BrailleDisplayDriver'>
INFO - brailleDisplayDrivers.papenmeier.BrailleDisplayDriver.connectUSB (23:13:40.699) - MainThread (4472):
connectUSB success
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (23:13:40.821) - MainThread (4472):
loading braille papenmeier
INFO - braille.BrailleHandler._setDisplay (23:13:40.821) - MainThread (4472):
Loaded braille display driver 'papenmeier', current display has 0 cells.

Log after starting and shutting down JAWS 2024 that brings life into the Braillex display. NVDA was shut down while JAWS was running:

DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (23:21:04.511) - MainThread (12180):
registering pre_configSave action: <class 'brailleDisplayDrivers.papenmeier.BrailleDisplayDriver'>
INFO - brailleDisplayDrivers.papenmeier.BrailleDisplayDriver.connectUSB (23:21:04.592) - MainThread (12180):
connectUSB success
INFO - brailleDisplayDrivers.papenmeier.BrailleDisplayDriver.__init__ (23:21:04.655) - MainThread (12180):
Found EL40s
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (23:21:04.659) - MainThread (12180):
loading braille papenmeier
INFO - braille.BrailleHandler._setDisplay (23:21:04.659) - MainThread (12180):
Loaded braille display driver 'papenmeier', current display has 40 cells.

#### NVDA installed/portable/running from source:
NVDA  installed
#### NVDA version:
2023.3 RC 2
#### Windows version:
Version 22H2 (OS-version 19045.3570)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, exactly the same.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by towebo** [comment]
Having a look in the papenmeier.py it does seem as the __init__ does get called but _dev is None.

Excerpt from __init__:

		#try to connect to usb device,
		#if no usb device is found there may be a bluetooth device
		if ftdi2:
			devlist = ftdi2.list_devices()
		if(len(devlist)==0):
			self.connectBluetooth()
		elif ftdi2:
			self._baud = 57600
			self.connectUSB(devlist)
		if(self._dev is not None):

The log clearly states that the following line is called:

self.connectUSB(devlist)

	def connectUSB(self, devlist: List[bytes]):
		"""Try to connect to usb device, this is triggered when bluetooth
connection could not be established"""
		try:
			self._dev = ftdi2.open_ex(devlist[0])
			self._dev.set_baud_rate(self._baud)
			self._dev.inWaiting = self._dev.get_queue_status
			log.info("connectUSB success")
		except:
			log.debugWarning("connectUSB failed")

As you can see the info about success is written last in the method and no exception is caught so the self._dev should not be None but that must be the only reason why the display isn't initialized correctly.

**Comment by seanbudd** [comment]
>Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, exactly the same.

Could you mention which other versions of NVDA you tested?

**Comment by towebo** [comment]
2022.3.2

**Comment by lukaszgo1** [comment]
@towebo  Would you be willing to try with [NVDA 2019.2.1](www.nvaccess.org/download/nvda/releases/2019.2.1/nvda_2019.2.1.exe)? In the next version when migrating to Python 3 there were a lot of changes to Braille display drivers, however most of them were done without access to actual devices, so some issues might have slipped through.

**Comment by towebo** [comment]
1. Unplugged, plugged in, started NVDA 2019.2

DEBUG - core.main (16:23:23.257):
Initializing braille input
INFO - brailleInput.initialize (16:23:23.259):
Braille input initialized
DEBUG - core.main (16:23:23.259):
Initializing braille
INFO - braille.initialize (16:23:23.259):
Using liblouis version 3.10.0
DEBUGWARNING - brailleDisplayDrivers.papenmeier.BrailleDisplayDriver.connectBrxCom (16:23:23.266):
BRXCom is not installed
INFO - brailleDisplayDrivers.papenmeier.BrailleDisplayDriver.connectUSB (16:23:23.331):
connectUSB success
INFO - braille.BrailleHandler.setDisplayByName (16:23:23.453):
Loaded braille display driver papenmeier, current display has 0 cells.
DEBUG - core.main (16:23:23.453):
Initializing displayModel


Stone dead.


2. Started JAWS 2024, stopped JAWS 2024, started NVDA 2019.2

DEBUG - core.main (17:12:58.526):
Initializing braille input
INFO - brailleInput.initialize (17:12:58.526):
Braille input initialized
DEBUG - core.main (17:12:58.526):
Initializing braille
INFO - braille.initialize (17:12:58.535):
Using liblouis version 3.10.0
DEBUGWARNING - brailleDisplayDrivers.papenmeier.BrailleDisplayDriver.connectBrxCom (17:12:58.540):
BRXCom is not installed
INFO - brailleDisplayDrivers.papenmeier.BrailleDisplayDriver.connectUSB (17:12:58.605):
connectUSB success
INFO - brailleDisplayDrivers.papenmeier.BrailleDisplayDriver.__init__ (17:12:58.655):
Found EL40s
INFO - braille.BrailleHandler.setDisplayByName (17:12:58.660):
Loaded braille display driver papenmeier, current display has 40 cells.
DEBUG - core.main (17:12:58.660):
Initializing displayModel
DEBUG - core.main (17:12:58.661):

Works fine.

After installing NVDA 2019.2 I renamed the folder %appdata%\NVDA so all settings were initialized from zero.

**Comment by burmancomp** [comment]
Does it use ftdi usb serial converter?

**Comment by Adriani90** [comment]
Did you test with a clean installatiom of nvda 2023.3 after you renamed the folder in %appdata%?

**Comment by Adriani90** [comment]
Also could you disable the braille connection in Windows Narator? Until Windows 11 23 H2 Narator caused some braille displays to fail starting in NVDA even when Narator was turned off. This seems to be fixed in Windows 11 23 H2

**Comment by towebo** [comment]
Tested with NVDA 2018.1 and 2019.2 with the same result as for 2023.3.
Deleted the %appdata%\NVDA folder each time to ensure clean start.

Got a tip that one could first select Papenmeier older, dismiss the error message and then select Papenmeier newer to get it running. For me I have to try Papenmeier older twice and the second time the display starts moving. Selecting Papenmeier newer after that will make it work as expected and it's 100% reproducable on my machine so if something needs to be tested I can do that.
Below is the excerpt from the log where I open the dialog to select display, selects Papenmeier older twice and then Papenmeier newer and closes the dialog.


Speaking [LangChangeCommand ('sv_SE'), 'Punktskrift', 'egenskapssida', CancellableSpeech (still valid)]
IO - speech.speech.speak (19:41:30.681) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'Punktskriftsdisplay', 'gruppering', CancellableSpeech (still valid)]
IO - speech.speech.speak (19:41:30.684) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'Ändra...', 'knapp', 'Alt+ä', CancellableSpeech (still valid)]
DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (19:41:30.775) - Dummy-1 (1472):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1233, in getNearestWindowHandle
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467259, 'Odefinierat fel', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (19:41:30.967) - winInputHook (14780):
Input: kb(desktop):space
IO - speech.speech.speak (19:41:30.979) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'mellanslag', EndUtteranceCommand()]
IO - speech.speech.speak (19:41:30.980) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'tryckt']
DEBUG - gui.settingsDialogs.__new__ (19:41:31.087) - MainThread (15352):
Creating new settings dialog (multiInstanceAllowed:True). State of _instances {<gui.settingsDialogs.NVDASettingsDialog object at 0x08FA82B0>: <DialogState.CREATED: 0>}
DEBUG - gui.contextHelp.bindHelpEvent (19:41:31.090) - MainThread (15352):
Did context help binding for BrailleDisplaySelectionDialog
DEBUG - gui.contextHelp.bindHelpEvent (19:41:31.103) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:31.109) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:31.124) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUGWARNING - braille.getDisplayList (19:41:31.142) - MainThread (15352):
Braille display driver alva reports as unavailable, excluding
DEBUGWARNING - braille.getDisplayList (19:41:31.144) - MainThread (15352):
Braille display driver brltty reports as unavailable, excluding
DEBUGWARNING - braille.getDisplayList (19:41:31.145) - MainThread (15352):
Braille display driver freedomScientific reports as unavailable, excluding
DEBUGWARNING - braille.getDisplayList (19:41:31.146) - MainThread (15352):
Braille display driver hidBrailleStandard reports as unavailable, excluding
DEBUGWARNING - braille.getDisplayList (19:41:31.147) - MainThread (15352):
Braille display driver hims reports as unavailable, excluding
DEBUGWARNING - braille.getDisplayList (19:41:31.149) - MainThread (15352):
Braille display driver seikantk reports as unavailable, excluding
IO - speech.speech.speak (19:41:31.352) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'Välj punktdisplay', 'dialog', CancellableSpeech (still valid)]
IO - speech.speech.speak (19:41:31.361) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'Punktskriftsdisplay:', 'kombinationsruta', 'Papenmeier BRAILLEX nyare modeller', 'stängd', 'Alt+d', CancellableSpeech (still valid)]
DEBUGWARNING - IAccessibleHandler.internalWinEventHandler._shouldGetEvents (19:41:32.320) - MainThread (15352):
Foreground took too long to change. Foreground still 67026 (#32770). Should be 67050 (WindowsForms10.Window.8.app.0.282af8c_r8_ad1)
IO - inputCore.InputManager.executeGesture (19:41:33.119) - winInputHook (14780):
Input: kb(desktop):downArrow
IO - speech.speech.speak (19:41:33.229) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'Papenmeier BRAILLEX äldre modeller']
IO - inputCore.InputManager.executeGesture (19:41:34.727) - winInputHook (14780):
Input: kb(desktop):tab
IO - speech.speech.speak (19:41:34.741) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'Port:', 'kombinationsruta', 'Seriellport: Braillex Serial Port (COM3)', 'stängd', 'Alt+p', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (19:41:37.087) - winInputHook (14780):
Input: kb(desktop):downArrow
IO - inputCore.InputManager.executeGesture (19:41:37.615) - winInputHook (14780):
Input: kb(desktop):upArrow
IO - inputCore.InputManager.executeGesture (19:41:38.359) - winInputHook (14780):
Input: kb(desktop):tab
IO - speech.speech.speak (19:41:38.368) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'OK', 'knapp', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (19:41:39.287) - winInputHook (14780):
Input: kb(desktop):enter
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (19:41:39.289) - MainThread (15352):
registering pre_configSave action: <class 'brailleDisplayDrivers.papenmeier_serial.BrailleDisplayDriver'>
INFO - brailleDisplayDrivers.papenmeier_serial.BrailleDisplayDriver.__init__ (19:41:39.290) - MainThread (15352):
papenmeier_serial using port COM3
ERROR - braille.BrailleHandler.setDisplayByName (19:41:39.290) - MainThread (15352):
Error initializing display driver 'papenmeier_serial'
Traceback (most recent call last):
  File "braille.pyc", line 2187, in setDisplayByName
  File "braille.pyc", line 2254, in _setDisplay
  File "braille.pyc", line 2224, in _switchDisplay
  File "extensionPoints\util.pyc", line 216, in callWithSupportedKwargs
  File "brailleDisplayDrivers\papenmeier_serial.pyc", line 94, in __init__
  File "serial\serialwin32.pyc", line 33, in __init__
  File "serial\serialutil.pyc", line 244, in __init__
  File "serial\serialwin32.pyc", line 64, in open
serial.serialutil.SerialException: could not open port 'COM3': PermissionError(13, 'Åtkomst nekad.', None, 5)
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (19:41:39.290) - MainThread (15352):
registering pre_configSave action: <class 'brailleDisplayDrivers.noBraille.BrailleDisplayDriver'>
DEBUG - braille.BrailleHandler._switchDisplay (19:41:39.291) - MainThread (15352):
Switching braille display from 'papenmeier' to 'noBraille'
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (19:41:39.294) - MainThread (15352):
loading braille noBraille
INFO - braille.BrailleHandler._setDisplay (19:41:39.295) - MainThread (15352):
Loaded braille display driver 'noBraille', current display has 0 cells.
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.485) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.606) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.610) - MainThread (15352):
Did context help binding for CheckBox
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.612) - MainThread (15352):
Did context help binding for CheckBox
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.614) - MainThread (15352):
Did context help binding for CheckBox
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.625) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.642) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.659) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.677) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.689) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.706) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - config.featureFlag._validateConfig_featureFlag (19:41:39.728) - MainThread (15352):
Validating feature flag: DEFAULT, optionsEnum: ReviewRoutingMovesSystemCaretFlag, behaviorOfDefault: NEVER
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.728) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.730) - MainThread (15352):
Did context help binding for CheckBox
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.733) - MainThread (15352):
Did context help binding for CheckBox
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.750) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - config.featureFlag._validateConfig_featureFlag (19:41:39.768) - MainThread (15352):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.768) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - config.featureFlag._validateConfig_featureFlag (19:41:39.784) - MainThread (15352):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - gui.contextHelp.bindHelpEvent (19:41:39.785) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
IO - speech.speech.speak (19:41:39.810) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'Punktskriftsdisplayfel', 'dialog', 'Kunde inte ladda displayen papenmeier_serial.', CancellableSpeech (still valid)]
IO - speech.speech.speak (19:41:39.821) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'OK', 'knapp', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (19:41:40.935) - winInputHook (14780):
Input: kb(desktop):enter
IO - speech.speech.speak (19:41:40.988) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'Välj punktdisplay', 'dialog', CancellableSpeech (still valid)]
IO - speech.speech.speak (19:41:40.990) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'OK', 'knapp', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (19:41:42.407) - winInputHook (14780):
Input: kb(desktop):enter
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (19:41:42.410) - MainThread (15352):
registering pre_configSave action: <class 'brailleDisplayDrivers.papenmeier_serial.BrailleDisplayDriver'>
INFO - brailleDisplayDrivers.papenmeier_serial.BrailleDisplayDriver.__init__ (19:41:42.410) - MainThread (15352):
papenmeier_serial using port COM3
ERROR - braille.BrailleHandler.setDisplayByName (19:41:42.898) - MainThread (15352):
Error initializing display driver 'papenmeier_serial'
Traceback (most recent call last):
  File "braille.pyc", line 2187, in setDisplayByName
  File "braille.pyc", line 2254, in _setDisplay
  File "braille.pyc", line 2224, in _switchDisplay
  File "extensionPoints\util.pyc", line 216, in callWithSupportedKwargs
  File "brailleDisplayDrivers\papenmeier_serial.pyc", line 144, in __init__
Exception: No or unknown braille display found
IO - speech.speech.speak (19:41:42.973) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'Punktskriftsdisplayfel', 'dialog', 'Kunde inte ladda displayen papenmeier_serial.', CancellableSpeech (still valid)]
IO - speech.speech.speak (19:41:42.977) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'OK', 'knapp', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (19:41:43.998) - winInputHook (14780):
Input: kb(desktop):enter
IO - speech.speech.speak (19:41:44.050) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'Välj punktdisplay', 'dialog', CancellableSpeech (still valid)]
IO - speech.speech.speak (19:41:44.053) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'OK', 'knapp', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (19:41:45.839) - winInputHook (14780):
Input: kb(desktop):tab
IO - speech.speech.speak (19:41:45.855) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'Avbryt', 'knapp', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (19:41:46.015) - winInputHook (14780):
Input: kb(desktop):tab
IO - speech.speech.speak (19:41:46.030) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'Punktskriftsdisplay:', 'kombinationsruta', 'Papenmeier BRAILLEX äldre modeller', 'stängd', 'Alt+d', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (19:41:46.911) - winInputHook (14780):
Input: kb(desktop):upArrow
IO - speech.speech.speak (19:41:46.938) - MainThread (15352):
Speaking [LangChangeCommand ('sv_SE'), 'Papenmeier BRAILLEX nyare modeller']
IO - inputCore.InputManager.executeGesture (19:41:49.063) - winInputHook (14780):
Input: kb(desktop):enter
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (19:41:49.066) - MainThread (15352):
registering pre_configSave action: <class 'brailleDisplayDrivers.papenmeier.BrailleDisplayDriver'>
INFO - brailleDisplayDrivers.papenmeier.BrailleDisplayDriver.connectUSB (19:41:49.098) - MainThread (15352):
connectUSB success
INFO - brailleDisplayDrivers.papenmeier.BrailleDisplayDriver.__init__ (19:41:49.162) - MainThread (15352):
Found EL40s
DEBUG - braille.BrailleHandler._switchDisplay (19:41:49.162) - MainThread (15352):
Switching braille display from 'noBraille' to 'papenmeier'
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (19:41:49.170) - MainThread (15352):
loading braille papenmeier
INFO - braille.BrailleHandler._setDisplay (19:41:49.170) - MainThread (15352):
Loaded braille display driver 'papenmeier', current display has 40 cells.
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.453) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.651) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.656) - MainThread (15352):
Did context help binding for CheckBox
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.660) - MainThread (15352):
Did context help binding for CheckBox
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.663) - MainThread (15352):
Did context help binding for CheckBox
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.680) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.709) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.738) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.766) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.785) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.812) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - config.featureFlag._validateConfig_featureFlag (19:41:49.844) - MainThread (15352):
Validating feature flag: DEFAULT, optionsEnum: ReviewRoutingMovesSystemCaretFlag, behaviorOfDefault: NEVER
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.844) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.848) - MainThread (15352):
Did context help binding for CheckBox
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.852) - MainThread (15352):
Did context help binding for CheckBox
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.879) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - config.featureFlag._validateConfig_featureFlag (19:41:49.908) - MainThread (15352):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.908) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - config.featureFlag._validateConfig_featureFlag (19:41:49.936) - MainThread (15352):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - gui.contextHelp.bindHelpEvent (19:41:49.936) - MainThread (15352):
Did context help binding for LabeledControlHelper.__init__.<locals>.WxCtrlWithEnableEvnt
DEBUG - NVDAObjects.NVDAObject._get_placeholder (19:41:49.941) - MainThread (15352):
Potential unimplemented child class: <NVDAObjects.Dynamic_NvdaDialogDialogIAccessibleWindowNVDAObject object at 0x08EA6470>
DEBUG - NVDAObjects.NVDAObject._get_placeholder (19:41:50.022) - MainThread (15352):
Potential unimplemented child class: <NVDAObjects.IAccessible.IAccessible object at 0x08ECDF70>
IO - braille.BrailleBuffer.update (19:41:50.024) - MainThread (15352):
Braille regions text: ['Välj punktdisplay dlg ', 'Punktskriftsdisplay: Papenmeier BRAILLEX nyare modeller + cbo Alt+d']
IO - braille.BrailleHandler.update (19:41:50.024) - MainThread (15352):

**Comment by towebo** [comment]
Braille is off in Narrator. I added the Papenmeier display  to see if Narrator could bring it to life but it couldn't so I removed it from the list.

**Comment by towebo** [comment]
I got this from the Papenmeier support and it works. I've replied and asked if there's a sequence of commands one can send that does the same as the below and perhaps that's what JAWS does?
Would it be possible to display a message to the user when the Papenmeier newer models is selected to inform how to get around this problem?

There is an option in our USB driver which can cause an issue to use our braille devices with screenreaders especially NVDA.
Please try the following:
•             Please make sure that you have installed the latest driver 2.12.36.4.
•             Open the „device manager“.
•             Scroll down the list to "USB Controllers" or "USB Devices".
•             Select „Papenmeier Braillex USB Device“.
•             Open the properties and switch to the "Advanced" tab.
•             Disable the "Load VCP" option.
NOTE:
Sometimes the “Advanced” tab doesn't appear. If this is the case, disconnect the braille display from the computer, close the running screen reader, if possible, wait a moment and reconnect the braille display. Repeat this 4 to 5 times if necessary. If the "Advanced" tab is still not displayed, please restart the computer.

**Comment by seanbudd** [comment]
@towebo - can you confirm that this fixes the issue?

I think this would be best placed in the user guide, to be less obtrusive to users. Users can then get this information easily when they begin to investigate the problem.
