### ISSUE TITLE
Regression detected in readFeeds add-on for API version 2024.1

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#15770]
### Steps to reproduce:
1. Open the add-on store in NVDAalpha-29936,a5d9e5b5 (2024.1.0.29936)
2. Select the dev channel and install readFeeds 26.0.2 add-on.
3. Go to NVDA's menu, Tools submenu, Feeds..., and activate the List of articles button.
### Actual behavior:
An error is produced and the list of articles is not shown.

> NVDA+n
NVDA  menu
t
View log  l
f
Feeds: normal configuration  dialog
list
Project Gutenberg
tab
List of articles...  button  Alt+  a
enter

### Expected behavior:
The list of articles of the selected feed should be presented.

#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
alpha-29936,a5d9e5b5 (2024.1.0.29936)
#### Windows version:
Windows 11 22H2 (10.0.22621) workstation AMD64

#### Name and version of other software in use when reproducing the issue:
n/a
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I tried other alphas with API version 2024.1 with the same behavior.
The add-on works as expected in NVDA2023.3, using readFeeds 26.0.0.
#### If NVDA add-ons are disabled, is your problem still occurring?
No since this is related to an add-on.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.
[nvda.log](https://github.com/nvaccess/nvda/files/13322702/nvda.log)

**Comment by CyrilleB79** [comment]
In this issue you describe an issue with ReadFeeds add-on.
Have you investigated which part of NVDA makes it break?
May it be linked to a change / new requirement in the updated wxPython version ?

**Comment by nvdaes** [comment]
@CyrilleB79 , I tried to investigate before opening this issue, but my investigation was not successful.
The issue seems to be related to wx.Dialog and sizers. Previously, I borrowed code from the NVDA ConfigProfilesDialog to build the FeedsDialog, trying that visual appearance is good. I use guiHelper controls. 26.0.0 stable version of readFeeds works well.
T26.0.2 dev version doesn't work well in NVDA 2023.3 due to xml updated to Python3.11, so this version cannot be used to compare if the ArticlesDialog works for NVDA 2023.3 and 2024.1.
But 26.0.0works as expected.
I think that changes maybe needed in gui.guiHelper, or at least, changes in documentation maybe useful to explain how to fix regressions like this one.

**Comment by beqabeqa473** [comment]
Hello @nvdaes.

It is due to an upgrade to WXVidgets 3.2.2.1.

Log says about itself.

I think i would be able to make a pr to this addon during the day.

**Comment by beqabeqa473** [comment]
just remove self.Sizer = sizer

**Comment by nvdaes** [comment]
beqabeqa473 commented 

> just remove self.Sizer = sizer

Thanks Beqa! This works perfectly. I'll release a new dev version now. Let'sleft this issue opened, in case this needs to be documented.

**Comment by beqabeqa473** [comment]
@nvdaes  The correct solution would be to pass not self as parent but frame. Then It should work as expected

**Comment by nvdaes** [comment]
Now I'm having issues builting the binary. I'll try this too.

**Comment by beqabeqa473** [comment]
Oops, that is not working as expected. I will try to take a look further.

**Comment by nvdaes** [comment]
Tanks Beqa, though removing self.sizer works well. I'll wait until tommorrow and then I'll publish a new dev release on the store with your future suggestion, or just removing self.sizer. In case you want to create a PR in the add-on repo to appear as a contributor for this, feel free to do it.

**Comment by nvdaes** [comment]
I'll wait to publish a new release, in case NVAccess dev look at this, so steps to reproduce don't need to be changed and the add-on can be installed from the store.

**Comment by seanbudd** [comment]
Closing as this appears to be an issue with an add-on, not NVDA

**Comment by nvdaes** [comment]
OK, I'm submitting a fixed version of the add-on to the store with the solution provided by @beqabeqa473
