### ISSUE TITLE
When nvda screen reader is on the onclick on parent component is not working

### ISSUE THREAD

**Issue by repl-shenoy-sukumaran** [nvaccess/nvda#15789]
### Steps to reproduce:
-  Open NVDA screen reader (2023.3)
- Navigate to code sandbox link https://codesandbox.io/s/admiring-phoebe-f4w8fy?file=/src/Demo.tsx
- Using the tab navigate to the ListItemButton click enter to open the dialog
- Enter the key open the dialog (Instead of opening the dialog its checking the checkbox)
- This works correctly when nvda screen reader is OFF.

### Actual behavior:
- Its checking the checkbox instead of opening the dialog on enter

### Expected behavior:

- Its should open the dialog on enter same behavior when nvda is off.
![Working](https://github.com/nvaccess/nvda/assets/13564819/6f931ccf-e002-4105-8f3f-0b0544a1f257)

### NVDA logs, crash dumps and other attachments:
Not required easily reproducible 

#### NVDA installed/portable/running from source:
NVDA installed 2023.3 

#### NVDA version:
2023.3 

#### Windows version:
Windows 11 Pro (22631.2715)

#### Name and version of other software in use when reproducing the issue:
Chrome Version 119.0.6045.160 (Official Build) (64-bit)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes 2023.2 its same

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by hwf1324** [comment]
Maybe this is related to the behavior of the browsing mode?

Although I cannot explain the reasons for this, there are several methods that can achieve the goal of the problem.

The simplest way is to press `NVDA+Space` to enter focus mode.

Or use the mouse to move to the object currently being viewed

**Comment by Adriani90** [comment]
This is also reproducible in Firefox, and it is only reproducible when using tab while NVDA is in browse mode.

Using arrow keys in browse mode followed by enter key opens the dialog as expected.

Maybe @jcsteh can explain in more detail why using tab in browse mode does not bring the focus properly on the button to open the dialog?

**Comment by jcsteh** [comment]
Pressing enter in browse mode always activates the element under the cursor. Since the checkbox is the first thing inside the button, when you tab to the button, the cursor lands on the checkbox. Thus, enter activates the checkbox.

Note that putting a checkbox inside a button is a violation of the ARIA spec, which states that children of buttons are presentational.

**Comment by repl-shenoy-sukumaran** [comment]
Thanks everyone for the replay.
Thanks @Adriani90 we can give it as work around.
