### ISSUE TITLE
Do not allow to rewrite Python console history

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#15792]
### Steps to reproduce:
* Open Python console
* Execute "regexp = r"a(very)?complex[R]+egexp"
* Execute "foo=4"
* Press upArrow twice
* Edit the line to "bar=3" but do not press enter
* Press down arrow
* Press Enter to execute the current line ("foo=4")
* Press upArrow many times
### Actual behavior:
The regexp cannot be found anymore in the history
### Expected behavior:
No item should be deleted or modified. They may only be deleted/moved in case an item is entered two times to keep only the most recent occurence.
### NVDA logs, crash dumps and other attachments:
None
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.3
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3570

#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, older version have the same problem
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by XLTechie** [comment]
Interestingly, this is exactly the same way that bash works.

Perhaps more relevantly, it is also the way that the standard Python 3 console 
works.

One might say: if it's good enough for the most respected shell, and the 
official Py3 console, why isn't it good enough for us?

It is true that CMD and PowerShell don't work this way, so maybe Windows users 
don't expect this kind of history malleability.

I guess you would prefer it be more like cmd's history, which is purely 
additive?

**Comment by CyrilleB79** [comment]
> Interestingly, this is exactly the same way that bash works. Perhaps more relevantly, it is also the way that the standard Python 3 console works. One might say: if it's good enough for the most respected shell, and the official Py3 console, why isn't it good enough for us? It is true that CMD and PowerShell don't work this way, so maybe Windows users don't expect this kind of history malleability. I guess you would prefer it be more like cmd's history, which is purely additive?

On contrary of you, I cannot see this issue of item disappearing in Python console or in bash.
For bash, I have tested with "Git bash", what may be discutable.
But for Python console, I have just typed "python" in a cmd window. I guess it is what you call official Python console?
May it depend on other environment configuration? Or may it depend on from where the Python console was launched (cmd in ?my case)

**Comment by lukaszgo1** [comment]
> But for Python console, I have just typed "python" in a cmd window. I guess it is what you call official Python console? May it depend on other environment configuration? Or may it depend on from where the Python console was launched (cmd in ?my case)



There is no such thing as a 'official' handling of the history in Python's REPL. On Windows the command history works merely by chance, i.e. cmd provides command history, and stuff entered into Python interpreter ends up in it (there were various better solutions in Python 2, but I don't think any of it survived migration to Python 3 sadly). On all other platforms it just relies on readline which is included on most, if not all, *nix based systems. That is also why the behavior is the same in it as in Bash, at least when running on Linux.
