### ISSUE TITLE
MS Word - Commands to navigate to start or end of row or column do not report the correct cell anymore

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#15805]
### Steps to reproduce:
* Open a Word document and create a table (e.g. 4x4) with some content in each cell
* Use the native Word commands to jump to the start or the end of row or column, i.e. Alt+Home, Alt+End, Alt+PgUp and Alt+PgDown

### Actual behavior:
The content of the cell before the move is reported instead of the content of the landing cell.

### Expected behavior:
The content of the landing cell should be reported instead.

### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.3
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3570
#### Name and version of other software in use when reproducing the issue:
Microsoft® Word 2016 (16.0.5413.1000) MSO (16.0.5413.1000) 32 bits
and
Microsoft® Word 2016 MSO (Version 2310 Build 16.0.16924.20054) 32 bits
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Not tested
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2023.2 NOK.
NVDA 2023.1 OK.

Thus it may be a regression of 2023.2 dev cycle.
From the change log, I imagine that #14708 or #14928 may have caused this regression, or just modified the timings so that a hidden bug has been uncovered. I have not bissected all the commits between 2023.1 and 2023.2 however.
Cc @jcsteh, any idea?

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested

**Comment by jcsteh** [comment]
This seems a lot like #14984. This was probably "regressed" by #14708, though the bug was likely always present, just not exposed. Before #14708, gesture.send() did a sleep after sending the gesture, which caused performance problems. Now, it doesn't. That means that the code needs to wait for the application to update, rather than assuming it is up to date as soon as the gesture is sent. I haven't looked at the MS Word code in question, but that's my guess.

If I'm correct, note that this was always possible if the application took longer than 20-30 ms to update; e.g. if the system was under load. It's just more likely now.

**Comment by CyrilleB79** [comment]
> This seems a lot like #14984. This was probably "regressed" by #14708, though the bug was likely always present, just not exposed. Before #14708, gesture.send() did a sleep after sending the gesture, which caused performance problems. Now, it doesn't. That means that the code needs to wait for the application to update, rather than assuming it is up to date as soon as the gesture is sent. I haven't looked at the MS Word code in question, but that's my guess.
> 
> If I'm correct, note that this was always possible if the application took longer than 20-30 ms to update; e.g. if the system was under load. It's just more likely now.

Yes, the code uses `gesture.send()` and immediately after, it retrieves text info at the caret's position to speak the new cell's content. There is no delay nor check to let the application enough time to update, what was not a visible problem in NVDA 2023.1 due to NVDA's intrinsic delays.

**Comment by jcsteh** [comment]
An interim fix would be to just add a time.sleep after the gesture.send, restoring the previous behaviour. The more correct fix is to actually make sure the cursor moved.

**Comment by CyrilleB79** [comment]
I am currently coding a fix inspired from what was done in Excel, i.e. wait until the cursor has moved to report the move.
