### ISSUE TITLE
Beep for capital is not working if typed characters and words are set off

### ISSUE THREAD

**Issue by abhijitkasbe** [nvaccess/nvda#15811]
in the speach setting of NVDA there is an option "beep for capital" if you enable it then as you type capital letter NVDA will play beep however if you set typed characters and words off NVDA key  followed by 2 and 3 on number rowthen NVDA will not play beep

**Comment by seanbudd** [comment]
Welcome @abhijitkasbe ,

We are unable to process this issue as it stands.

- Please fill out the issue template fully.

Kind Regards,
NV Access Software Developers
