### ISSUE TITLE
Store the poEdit appModule scripts in a dedicated category

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#15815]
### Is your feature request related to a problem? Please describe.
NVDA includes an appModule for the PoEdit software which provides scripts to improve its accessibility.
As these scripts are defined without a category, they are found in the "Others" category.
### Describe the solution you'd like
In order to find them easily, it would be much preferable if they were placed in a category specific to PoEdit.

**Comment by CyrilleB79** [comment]
Yes, it makes sense.

There are also uncategorized scripts in the following appModules:
* eclipse.py
* foobar.py
* miranda32.py
* powerpnt.py
* vipmud.py

**Comment by Nael-Sayegh** [comment]
Hello Paul,
Do you plan on making the Pull request to fix this issue or can I do it?
Thank you

**Comment by Nael-Sayegh** [comment]
Thank you very much, I'll try to do it.
