### ISSUE TITLE
No feedback when using Backspace while typing in Kannada language using Nudi 6.1 software

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#15822]
### Steps to reproduce:
Received via email

Using Nudi6.1 software. (you can download from below link.)
https://kagapa.in/kannada/sites/default/files/downloads/Nudi-6.1/Nudi_6.1_setup.exe

Type any text and then use backspace to remove any characters.

### Actual behavior:

With NVDA's Keyboard setting "Handle keys from other applications" checked, user receives the following error:
"71 hotkeys have been received in the last 1812ms.
Do you want to continue?
yes  no
(see #MaxHotkeysPerInterval in the help file)"

With this option disabled, the action works, however with no feedback from NVDA.

(Regarding this setting, the user guide does note that "Certain users may wish to turn this off, such as those typing Vietnamese with the UniKey typing software as it will cause incorrect character input")

The user advised that when trying the same thing with NVDA 2022.4, they do not receive the error.  But when using NVDA 2023.1 or later, they do.

### Expected behavior:

Ideally the user should get feedback about deleted characters, and no error.

#### NVDA version:

NVDA 2023.3 installed

#### Windows version:

Windows 10.0.19045 Build 19045

#### Name and version of other software in use when reproducing the issue:

for typing Kannada, we use Nudi6.1 software. (you can download from below link.)
https://kagapa.in/kannada/sites/default/files/downloads/Nudi-6.1/Nudi_6.1_setup.exe

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Also tested with NVDA 2022.4 and NVDA 2023.1

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

**Comment by Qchristensen** [comment]
Note from the user: A workaround for this is to use shift+backspace.

**Comment by lukaszgo1** [comment]
My testing does not confirm the range of versions mentioned in the initial comment i.e. this does not work for me with NVDA 2023.2, and does work as expected in 2023.1. Bisect shows that this has been introduced in PR #14708

**Comment by CyrilleB79** [comment]
cc @jcsteh (author of #14708)

**Comment by jcsteh** [comment]
My guess is that Nudi6.1 captures the backspace key and then re-sends it for some reason. Previously, we delayed slightly when sending keys, which would mean that any keys sent by an app which captured a key sent by NVDA would be ignored during that period. Now that we don't delay, we only ignore the key sent by NVDA itself, but that doesn't include any keys captured and sent by, for example, Nudi6.1.

I'm not really sure what to do about this except put the delay back, but that would reintroduce a significant performance loss (15-40ms) for all users for cursor keys, backspace, etc.

**Comment by jcsteh** [comment]
Actually, one thing we could try is this, as I discussed in https://github.com/nvaccess/nvda/pull/14708#issue-1615290627:

> This sleep was apparently added to ensure NVDA's keyboard hook ignored the injected keys. In my testing, removing this didn't seem to have any negative impact. If this does turn out to be a problem, we could watch for the last injected key in the keyboard event hook and fire a Windows event when it arrives. This will be faster to wake than a 10-16 ms sleep.

I'm not convinced it'll work, but it's worth a shot. I've pushed a try build with this approach. It will arrive [here](https://ci.appveyor.com/project/NVAccess/nvda/builds/48615216/artifacts) soon.

**Comment by lukaszgo1** [comment]
I was unable to test with a binary try  build (as it failed to finish for some reason), but testing with the branch `try-injectEvt` I can confirm that the issue appears to be fixed. It would be good to get confirmation from the user who reported this initially to @Qchristensen  though, just to make sure.

**Comment by Qchristensen** [comment]
Thanks everyone!  That try build doesn't seem to have build.  Have you got a link to the one you got to work please?

**Comment by lukaszgo1** [comment]
I have tested running from sources. Perhaps you can just ask Michael or Sean to re-trigger the build.

**Comment by Qchristensen** [comment]
Ping @jcsteh - there appears to be an issue with the new code which is preventing the build - are you able to have a look when you get a chance please?

**Comment by jcsteh** [comment]
Is this even after a re-trigger? In the first build I pushed, it seems to get stuck in a Chrome system test, but I don't know what because the console log is not particularly useful.

**Comment by jcsteh** [comment]
If I had to guess, I'd say we're injecting a key, but that key never gets received by NVDA's keyboard hook for some reason. That would suggest it gets swallowed by something else or that our keyboard hook couldn't catch it for some reason. That's definitely one danger of this approach.

I guess I could add a small timeout when waiting for the injected key, but that feels pretty hacky.

**Comment by jcsteh** [comment]
To make matters more fun, I think we might be hitting the AppVeyor job time limit here, so even if we uploaded an NVDA log from the test run, it wouldn't actually get uploaded because the job gets killed.

**Comment by jcsteh** [comment]
[Trying again](https://ci.appveyor.com/project/NVAccess/nvda/builds/48633665/artifacts).

**Comment by smbgsrini** [comment]
Indeed I am very grateful to you all.
as you given link I have installd nvda_snapshot_try-injectEvt-30139,19bd9384.exe and checked it. NVDA announcing deleted character's by using backspace. 
but, in kannada language there is character ೠ by pressing cap R and X characters ೠ appears. In keyboard setting of nvda, Handle keys from other applications is checked, by pressing caps R and X Kannada character ೠ unable to output. 
if I un-checked, pressing caps R and X Kannada character ೠ appears. 
this is also with NVDA functions. Because without using  NVDA, pressing caps R and X Kannada character ೠ able to output. NVDA 2022.4 was much compatible with these issues.  
kindly please add this compatibility feature in upcoming version.
With thanks,
Srinivasamurthy

**Comment by smbgsrini** [comment]
after installing nvda_snapshot_try-injectEvt-30139,19bd9384.exe and 
With NVDA's Keyboard setting "Handle keys from other applications" checked, Currently not recieving the following error:
"71 hotkeys have been received in the last 1812ms.
Do you want to continue?
yes no
(see #MaxHotkeysPerInterval in the help file)"
thanks for the effort.

**Comment by lukaszgo1** [comment]
@smbgsrini Just to clarify: are there any differences in behavior with the `nvda_snapshot_try-injectEvt-30139,19bd9384.exe` as compared to NVDA 2022.4?

**Comment by smbgsrini** [comment]
Sir,
nvda_snapshot_try-injectEvt-30139,19bd9384.exe as compared to NVDA
2022.4 these both behaving same while typing Kannada text. nvda2023.3
is not announcing deleted character by pressing backspace key.


On 07/12/2023, Łukasz Golonka ***@***.***> wrote:
> @smbgsrini Just to clarify: are there any differences in behavior with the
> `nvda_snapshot_try-injectEvt-30139,19bd9384.exe` as compared to NVDA
> 2022.4?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/15822#issuecomment-1845142727
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
Srinivasamurthy B G,
mo: 9035911023
blog: www.samaajakkaagi.blogspot.com

**Comment by lukaszgo1** [comment]
Hi @jcsteh Given your fix seems to solve this problem, are you planning to submit it as a PR?

**Comment by smbgsrini** [comment]
In nvda_2024.1beta1 has same problems which I mentioned through  #Qchristensen

**Comment by smbgsrini** [comment]
Yet to be find solution
