### ISSUE TITLE
Intall NVDA in mode sillent via MS Intune

### ISSUE THREAD

**Issue by Aldi1990** [nvaccess/nvda#15824]
I have installed NVDA in 2023.4 --minimal --install-silent via Microsoft Intune but after installed NVDA is working on logon Screen. I have checked setting and I found below option.

How can I disable this option before install via MS Intune or any script?

<img width="414" alt="MicrosoftTeams-image" src="https://github.com/nvaccess/nvda/assets/117146995/b6ba04e6-1d8f-452f-855e-4747866a8f64">

**Comment by hwf1324** [comment]
First of all, welcome to NVDA.

Secondly, it is recommended to fill out the problem template for easier problem resolution.
Please describe the image (such as the text, controls, etc.) as most people here are visually impaired.

Finally, there is relevant information in section 17.3 of the user guide. Perhaps you just need to scroll down a bit.

> `--enable-start-on-logon=True|False`

**Comment by Aldi1990** [comment]
Thanks for very quickly answer. Parameter which you pass me Can I add to command to install in mode silent ?

**Comment by hwf1324** [comment]
I have not tried it, but I think it is possible. Still recommend checking the user guide.

**Comment by Aldi1990** [comment]
I checked your solution and it works. Thanks for all.

**Comment by outforever** [comment]
FYi I couldnt find a this theoretical users guide (nothing about switches on the wiki), but you can get the strings by just passing --help to the installer exe file.
