### ISSUE TITLE
NVDA freezes after closing one of multiple Windows Terminal instances

### ISSUE THREAD

**Issue by igor-gorlov** [nvaccess/nvda#15841]
### Steps to reproduce:

1. Open Windows Terminal.
2. Ensure that `Settings` -> `Startup` -> `New instance behavior` is set to `Create a new window`.
3. Launch another instance of Windows Terminal.
4. Close one of these two instances with any method you prefer (either with `CTRL + Shift + W`, or with `Alt + F4`, or by typing `exit`, or by activating the standard button with object navigation).

### Actual behavior:

NVDA freezes for a random time (from 2 seconds to 1 minute). Moreover, after unfreeze, it hangs again when you try to activate the remaining Terminal window.

### Expected behavior:

No freezes.

### NVDA logs, crash dumps and other attachments:

A [debug log](https://github.com/nvaccess/nvda/files/13478093/nvda.log) demonstrating the issue is attached. First, I reproduce the problem using `CTRL + Shift + W` keystroke for window closing; next, `Alt + F4` is tested.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

2023.3.0.29780

#### Windows version:

10.0.19045.3693

#### Name and version of other software in use when reproducing the issue:

Windows Terminal Preview 1.19.3172.0

#### Other information about your system:

(Nothing to say)

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by josephsl** [comment]
Hi, can you try with NVDA alpha build 30080 (UIA event limiting) and see if that makes a difference? Thanks.

**Comment by igor-gorlov** [comment]
@josephsl, I tried both 30080 and 30101 (published several hours ago): the problem persists.

**Comment by seanbudd** [comment]
Is this a new problem? Did it exist in NVDA 2023.1 or 2023.2?

**Comment by igor-gorlov** [comment]
@seanbudd, the problem DID exist both in 2023.1 and 2023.2.

**Comment by igor-gorlov** [comment]
A new aspect I've discovered today: when there is two Terminal windows, and one of them had been launched as admin, I can close both these windows in any order without the issue.

**Comment by seanbudd** [comment]
This needs to be reported to Microsoft. It appears that Terminal doesn't correctly handle NVDA releasing the COM objects.

**Comment by Adriani90** [comment]
@igor-gorlov do you still have this issue with NVDA last alpha version? You can download the last alpha version here:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by igor-gorlov** [comment]
@Adriani90, I do not observe this issue on stable 2024.1. Cannot tell exactly when and why the problem had gone. Maybe Microsoft provided a fix (@seanbudd stated that this bug is caused by them). Anyway, I think the issue should be closed now.
