### ISSUE TITLE
suggestion notify the user of new add-ons available in the store

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#15842]
### Is your feature request related to a problem? Please describe.
no
### Describe the solution you'd like
I would like to suggest a new feature for the nvda add-on store.
Currently the only way to discover new add-ons in the store is to look at all available add-ons.
I would like to make this task easier.
The form of this is not yet clear to me, as there are countless ideas.
I will suggest the way that, in my limited knowledge, would perhaps be the easiest.
In the channel combo box there may be a new option such as new add-ons added to the store in the last 7 days.
So in the list, nvda would show the latest new add-ons added to the store.
Other ideas:
Every time a new add-on is posted to the store, a notification will be sent via Windows.
Whenever a new add-on is made available in the store, a window will open informing you of the new feature, which is configurable.
Complementing the first idea with a new channel showing the latest add-ons added to the store since the last time the user opened the store.
It could also be a new tab in the store.
Options can be configurable.
I still like the first suggestion more, but I'm happy that there is an easy way to discover new add-ons faster than today.
Thanks for your attention, and sorry for the confusion.

**Comment by Emil-18** [comment]
In my oppinion, the user should be able to sort add-ons from newest added

**Comment by seanbudd** [comment]
Closing in favour of https://github.com/nvaccess/nvda/issues/15278, we'd much prefer that a user can check this rather than have push notifications
