### ISSUE TITLE
show result of report focus, report navigator object, and report selection in braille

### ISSUE THREAD

**Issue by Emil-18** [nvaccess/nvda#15844]
### Is your feature request related to a problem? Please describe.
The report focus and report navigator object commands reports more information then NVDA normaly does when navigating to a control. Because this information isn't reported in braille, someone that only uses braille has no way of knowing if an object is for example invisible or not. When selecting more then one line, someone that only uses braille can't check to see what exactly is selected because when tethered to review, the selection information is not visible and when tethered to focus, the selection is unselected when moving up a line, do to movement of the caret
### Describe the solution you'd like
show in braille the information exactly as spoken

**Comment by burmancomp** [comment]
@Emil-18 I somewhat think that your next pull request is behind a corner.
