### ISSUE TITLE
Sometimes D3 on the brailliant 80 will not navigate down

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1585]
**Reported by ianr on 2011-06-17 20:39**
Sometimes when I hit D3 which is the bottom left key on the Brailliant 80 braille display it will not navigate to the next line down even though there are more lines.

Usually this happens after I have been moving around in EdSharp with the arrow keys, then I hit D3 and it moves to the next line, then I hit it again and again and it will no longer move down to the next line.
Usually when this happens I can hit D1 to go up a line and then hit D3 multiple times and it will work again.  I think I can also use the arrow keys to navigate around and then go back to the D3 button and it will work at least once again.
Other times it works every time, it is a bit intermittent, but happens fairly often.

**Comment by dkager** [comment]
I can think of a few causes:
- Unlikely, but maybe faulty hardware.
- A problem with the B80 firmware. This seems very plausible. :)
- A problem in the driver. I don't have the B80, but with the BI 40 I don't have this issue. It also seems strange that only D3 is affected.
- The problem where panning past the visible text on the screen doesnt work. This was fixed for Scintilla, see #5678. However, I'm not sure if pressing D1 once would make D3 work again, unless that visually scrolls multiple lines. If this was the issue then assigning D3 to emulate the down arrow would fix it.

I don't know if there is anything we can do without more information.

**Comment by jcsteh** [comment]
I think we have to use screen scraping (display model) to access EdSharp. We don't support scrolling past what's visible on the screen there. Closing as duplicate of #659.
