### ISSUE TITLE
possibility of executing scripts in the input gesture dialog

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#15869]
There are more and more scripts without input gesture.
The only way to make them execute is to assign a input gesture to them and use it.
For scripts that are used occasionally, this is not very practical.
The request is:
- Open the "input gestures" dialog,
- search and find the desired script,
- then by any means (key or button), request the execution of this script,
- then the dialog closes and the script is executed.

### Is your feature request related to a problem? Please describe.
No.

**Comment by Nael-Sayegh** [comment]
Hello,

If you go into the input gesture, position yourself on the command you want to execute, and press tab, you'll find a "Run script" button.

Doesn't that solve your problem?

**Comment by CyrilleB79** [comment]
> If you go into the input gesture, position yourself on the command you want to execute, and press tab, you'll find a "Run script" button.

No, this Run button does not exist in NVDA. Maybe it's coming from an add-on. By the way, I wonder if it's coming from @paulber19's Global commands add-on.

@paulber19 or @Nael-Sayegh, if you know of such a feature in an existing add-on, it would be interesting to mention it here. First, it give some background, indicating that this feature already exists, works well and is useful for some people. Second, it may be the opportunity to ask the add-on author if they want to submit a PR to integrate it in core. Third, if the add-on author does not want to submit a PR themself, the add-on's code may be a basis for someone else wanting to submit a PR for this.

Regarding the feature request:
* Will the scripts take into account the situation before the input gesture dialog is open? E.g. if I execute "read selection" or "read focus", will the selection or the focus before the input gesture dialog is open be read? Or will the information be relative to the "Run" button in the input gesture dialog?
* An alternative solution which does not use a GUI is the [Command helper](https://github.com/javidominguez/commandHelper) add-on by @javidominguez.

**Comment by Nael-Sayegh** [comment]
@CyrilleB79 Indeed, it's @paulber19 's extension that adds this button; I wasn't aware of that.
If this feature could be added to NVDA, that would indeed be much better.

**Comment by javidominguez** [comment]
Hello.

The reason Command Helper doesn't use GUI is to prevent an NVDA-displayed dialog from interfering with focus. When a window is displayed, it captures the focus of the system. Even if you hide the window before executing the NVDA command, it is possible in some circumstances that the focus may not return to exactly the same place it was before. This could alter the output of some commands. For example a command that needs to check the events that are fired when a certain object receives focus (I was thinking of script displayEventsList on Event Tracker addon).

**Comment by Emil-18** [comment]
I think its best to use a virtual menu, but it should be searchable as well, unlike in the command helper add-on

**Comment by javidominguez** [comment]
I agree but to do a search you have to type what you want to search for and I don't know how to do it without showing a window with an editing box. If you show a dialog to search, you lose the advantage of the virtual menu, of not altering the content of the screen or the focus. That's why I implemented voice search.

**Comment by Emil-18** [comment]
@javidominguez 
[code.zip](https://github.com/nvaccess/nvda/files/13540259/code.zip)
This is an add-on I am working on. See newKeyDownCallback in extraFunctions and event_typedCharacter in enhancedObjectNavigation for an example of how it can be done

**Comment by seanbudd** [comment]
This cannot be done reliably as it requires moving focus, which would affect what the gesture does.
This is best suited to an add-on.
To be able to reliably test a gesture you must execute it with a key command.
