### ISSUE TITLE
NVDA crashes with no log output when alt+tabbing across specific windows

### ISSUE THREAD

**Issue by cyrmax** [nvaccess/nvda#15866]
### Steps to reproduce:
* Reboot NVDA to be sure for a fresh start;
* Open VSCode;
* Set up a dedicated configuration profile for VSCode;
* In this profile set another synthesizer, punctuation level, synthesizer speed and volume;
* Open Unigram, Powershell and Teamtalk5;
* Build your alt+tab list so you can repeat the following order;
* Alt+tab into VSCode and do something, read, edit, etc;
* Start alt+tabbing without releasing alt key;
* You should alt+tab in the following order: start in VSCode, then Powershell, then Unigram, then Teamtalk5;
* While listening to the Teamtalk5 window title you see the issue.

### Actual behavior:
NVDA completely crashes on reading mentioned window title without even freezing or writing any logs. Just process disappears from the system.
I have recorded two logs but they do not contain any information.

### Expected behavior:
NVDA should not do this and should continue working properly or at least write some logs.

### NVDA logs, crash dumps and other attachments:
[nvda-crashes-when-alttab2.log](https://github.com/nvaccess/nvda/files/13514286/nvda-crashes-when-alttab2.log)
[nvda-crashes-when-alttab.log](https://github.com/nvaccess/nvda/files/13514287/nvda-crashes-when-alttab.log)

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
Version: alpha-30154,021c13da (2024.1.0.30154)

#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3693

#### Name and version of other software in use when reproducing the issue:
* Latest VSCode (version 1.84.2);
* TeamTalk v5.14 QT;
* Powershell;
* Unigram 10 (with Unigram plus addon).

#### Other information about your system:
Windows terminal is not used. Console support legacy, no UIA.

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, but before I didn't see such bugs.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by cyrmax** [comment]
Important update!
This bug exists with the following conditions:
* Start in the app with custom configuration profile;
* Meet Powershell window on your path (alone or along with other windows);
* End in TeamTalk5 window.

Important, that a configuration profile change should happen when you start alt+tabbing.

My idea was that not only TeamTalk5 but any QT application can trigger this bug.
But no, currently I can reproduce only with TT5.
Maybe the problem is related to QT6 only.
Or maybe there are some conditions regarding the window title string. Maybe it should contain some symbols or match some pattern.

**Comment by Brian1Gaff** [comment]
I know some older windows processes when terminated by mouse with the x remove nvda completely. Obviously, I am not using your software, but it was just a thought. Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
  ----- Original Message -----

**Comment by cyrmax** [comment]
I do not know the reason, but I see no crash dump for NVDA when this issue happens.
Also, still nothing interesting in logs. The last line is about speaking the Teamtalk window title.
@lukaszgo1 in the next comment I write that Unigram with Unigram plus is not needed. And for Teamtalk, powershell and VSCode or Total Commander I have no addons.

**Comment by lukaszgo1** [comment]
Still this may be caused by one of your global plugins, or the fact that Newfon is used, so testing without any add-ons is beneficial.

**Comment by Adriani90** [comment]
@cyrmax are you still having this issue with NvDA 2024.1 RC1?

**Comment by seanbudd** [comment]
Closing as we haven't heard from the original author

**Comment by cyrmax** [comment]
Excuse me guys, had some problems and had no time to test. But during last months on latest betas the problem doesn't occur. So yes, probably autofixed :D
