### ISSUE TITLE
NVDA does not report selected values when selecting them in a multi selection list

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#15925]
### Steps to reproduce:
1. Open NVDA and the test case at
https://stackblitz.com/edit/2tmhcn-suquy2?file=index.js
2. Use tab or in browse mode the arrow keys or the letter c to navigate to the combo box "choose a country"
3. make sure you are in focus mode, press alt+down arrow to open the list of countries
4. The focus will be placed in the search field. Press down arrow to navigate the list of available countries
5. Press space bar on a country you want to choose
6. The list closes and the focus will move outside of the combo box. Press tab to land on the combo box again and hear the selected values.
7. Press down arrow key to navigate both selected values and available values. Note that selected values are moved to the top of the list, not sure if it is a separate list or the same one.

### Actual behavior:
in step 5 the list closes and the focus is moved outside of the combo box, and you don't hear that the value has been selected.

### Expected behavior:
1. The focus should not move at all after pressing space bar on a country. 
2. NVDA should report "<country> selected" when pressing space bar
3. The list should remain open until you are finished with the selections. The user should be able to close the list by pressing escape.
4. After that the focus should land on the combo box which opens a list and not outside of it.

### NVDA logs, crash dumps and other attachments:
n/a

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-30299,4519b893 (2024.1.0.30299)

#### Windows version:
Windows 11 23 H2

#### Name and version of other software in use when reproducing the issue:
Firefox 120, Chrome and Edge 119

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
I am not sure but I suspect here is a web authoring error meaning the web author could actually make the focus land on the combo box after closing the list, and could also specify that selecting a country with space bar should not close the list.

I am not sure about the reporting of the country selected when pressing space bar (i.e. "France selected"). Is this something which can be done with an aria alert when pressing space bar?

If yes, then I think the whole description of this issue is related to web authoring and not NVDA.

@jcsteh can you confirm this? Or did I misunderstood something here?

**Comment by seanbudd** [comment]
>The focus should not move at all after pressing space bar on a country.

>in step 5 the list closes and the focus is moved outside of the combo box, and you don't hear that the value has been selected.

>The list should remain open until you are finished with the selections. The user should be able to close the list by pressing escape.

This is the behaviour when not using a screen reader as well. This is how the control was implemented.

>NVDA should report " selected" when pressing space bar

This is an authoring issue, the controls are not correctly being labelled as selected once they are selected.

Closing this as invalid
