### ISSUE TITLE
Character navigation behaves inaccurately in Tera Term 5.0 but works in 4.x

### ISSUE THREAD

**Issue by yncat** [nvaccess/nvda#15929]
### Steps to reproduce:
1. Install Tera Term 5.0 from https://github.com/TeraTermProject/osdn-download/releases/download/teraterm-5.0/teraterm-5.0.exe
2. Connect to an ssh host
3. Input some commands
4. Move the terminal cursor to left / right or try to erase characters using backspace

#### Console

```
Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 5.15.133.1-microsoft-standard-WSL2 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Strictly confined Kubernetes makes edge and IoT secure. Learn how MicroK8s
   just raised the bar for easy, resilient and secure K8s cluster deployment.

   https://ubuntu.com/engage/secure-kubernetes-at-the-edge
Last login: Sun Dec 17 15:29:04 2023 from 127.0.0.1
yncat@DESKTOP-QVRKB05:~$
```

#### input 8 a's
a
a
a
a
a
a
a
a

#### backspace each
c
e
s
/
e
g
a
g

#### observation
While using Tera Term 4.x makes the review cursor stick to the bottom, using 5.0 places it at the middle of the terminal buffer.
NVDA is misunderstanding the line where I'm currently inputting?
Don't really know which is the cause (NVDA or Tera Term)
Apparently Tera Term 5.0 changed the internal charset to UTF-8. I'm pretty sure that's related, but not sure which side should fix.

#### backspace each
a
a
a
a
a
a
a
a

### NVDA logs, crash dumps and other attachments:
no errors

#### NVDA installed/portable/running from source:
Installed and portable

#### NVDA version:
2023.3

#### Windows version:
Windows 10 and 11

#### Name and version of other software in use when reproducing the issue:
Reproducable only with NVDA and Tera Term 5.0

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by burmancomp** [comment]
Changing DPIAware=off to Tera Term section in TERATERM.INI may help.

**Comment by seanbudd** [comment]
Hi @yncat ,

Considering this broke across Tera Term releases, not NVDA releases, I expect this to be an accessibility issue with Tera Term.
Have you reported this to the developers of Tera Term?

**Comment by yncat** [comment]
@burmancomp
Thanks for the information. Unfortunately it did not change anything, at least here. I found other options like fallbackToCP932(in the ini file), and a switch between ANSI API and Unicode API (In the settings dialog). Both did not work however.

@seanbudd
Not yet. Assuming the latest change in Tera Term has broken the accessibility, I'm not pretty sure how to explain it with only currently known facts. If I were the devs, it'd be still very hard to track down the direct cause.
I wanted to track down a bit more, but looks like very little is known about why this happens.
Please feel free to keep or close this in accordance with the issue management policy. I'd appreciate for any additional findings, if someone has any.

**Comment by burmancomp** [comment]
If cursor shape is not horizontal line, set it to horizontal line in setup -> window...

**Comment by burmancomp** [comment]
It seems that cursor shape does not matter when DPIAware=off. I do not remember but it may have effect if dpiaware is on. Did you edit teraterm.ini in %appdata%\teraterm5? If/when there is teraterm.ini, it uses it. If there is not it seems to copy ini from installation directory. Default ini in installation directory has dpiaware=on so editing of default ini does not effect because copy in %appdata%\teraterm5 still contains dpiaware=on.

I use teraterm 5 both in debian 12 and ubuntu 22.04.

@seanbudd what do you think why enabling high dpi support causes problem where nvda does not detect caret correctly?

**Comment by seanbudd** [comment]
@yncat 
>Not yet. Assuming the latest change in Tera Term has broken the accessibility, I'm not really sure how to explain it with only currently known facts

You don't need technical information to report a bug to them. Reporting a bug to other developers is a complex as reporting bugs to NVDA. Please report this issue to the developers of the software. It is likely we are unable to do anything about it in NVDA.


@burmancomp 
>@seanbudd what do you think why enabling high dpi support causes problem where nvda does not detect caret correctly?

I don't quite understand this question, it seems you are saying this doesn't affect the issue. I don't recall asserting anything to do with DPI support and this issue. I strongly believe it is an issue with Tera Term.

**Comment by burmancomp** [comment]
@seanbudd sorry my unclear comment. I try to say: changing cursor shape (alternatives are block, horizontal line or vertical line) from teraterm settings does not solve this problem although setting cursor shape to horizontal line may help to some extend. But setting dpiaware=off in %appdata%\teraterm5\teraterm.ini solved problem at least in my case.

So what do you think why high dpi support seems to cause problems to nvda to detect caret correctly?

**Comment by seanbudd** [comment]
@burmancomp - I think you'd have to ask their developers that. NVDA has DPI awareness. We only have known problems in chromium due to bugs in chromium

**Comment by burmancomp** [comment]
@seanbudd tera term uses the Per-monitor DPI awareness V2(see [https://teratermproject.github.io/manual/5/en/setup/teraterm-misc.html#HighDPI](https://teratermproject.github.io/manual/5/en/setup/teraterm-misc.html#HighDPI)). I do not know anything about this so I want to ensure that nvda should work without problems with this mode.

**Comment by seanbudd** [comment]
Yes this was fixed via #13254

**Comment by burmancomp** [comment]
Thank you @seanbudd.

@yncat do you still have same problem after changing dpiaware to off in %appdata%\teraterm5\teraterm.ini?

**Comment by yncat** [comment]
@burmancomp
I was able to confirm that editing the setting file in %appdata% resolved the issue. I forgot teraterm's setting file precedence when I first tested.
I think I can now make a decent report to the teraterm devs, clarifying the specific condition that the issue happens. Thanks @seanbudd and @burmancomp for your information and discussion, this is exactly what I wanted to accomplish in this issue thread.

**Comment by burmancomp** [comment]
I read yesterday that dpiaware has been in version 4 but then it has been off by default ([https://teratermproject.github.io/manual/5/en/usage/migrate_to_5.html](https://teratermproject.github.io/manual/5/en/usage/migrate_to_5.html).

**Comment by Adriani90** [comment]
@yncat does Teraterm have a public issue tracker where we can follow proggress on this? You could post a link to the issue you reported to them. Otherwise we will have to ask you for an update at a later stage before closing this issue.

**Comment by Adriani90** [comment]
@yncat could you please test with NVDA last alpha version and the last update of Tera term? Is this issue still occuring?
You can download NVDA last alpha from here:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by yncat** [comment]
Thanks, and sorry for not being able to respond to last few messages.
I'm afraid I still wasn't able to post an issue to the teraterm devs. I was not sure about where to post the issue, and I was distracted by work and etc. 
I have just downloaded alpha-32932,b94415e8. Will definitely test it within a few days.

**Comment by Adriani90** [comment]
@yncat you can report issues for Tera term direct to their community and their developers here:
https://github.com/TeraTermProject/teraterm/issues

**Comment by yncat** [comment]
@Adriani90 Update: I will be able to test the NVDA latest alpha + teraterm latest version tomorrow!

**Comment by yncat** [comment]
Update: It no longer occurs with TeraTerm 5.2. It just got fixed with 2024.2 (jp though), without installing the beta. I guess TeraTerm itself had an issue and they fixed it. Closing this one anyway since it doesn't exist anymore.

**Comment by yncat** [comment]
Memo: It started to happen on TeraTerm 5.6.0 again. Still not sure which version introduced the bug.

**Comment by seanbudd** [comment]
Hi - this issue has been closed. Can you open a new issue with the current accurate information?

**Comment by yncat** [comment]
I will do so after confirming some more info on this and only if I still need to post an issue to NVDA side. I was just in a hurry yesterday and posted here so that I could recall. Sorry for the confusion I caused.
