### ISSUE TITLE
Translation via Crowdin - Many unmodified strings need to be re-translated

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#15934]
Testing Crowdin translation (French) via poedit.

### Steps to reproduce:
Compare translation via Crowdin and translation via manual merge of the .pot file of NVDA 2024.1. See #15933 for more details.

### Actual behavior:
Read the status bar in poedit and compare:
* Crowdin translation:
  Translated: 2669 of 2900 (92 %)  •  remaining: 231
* Translation file created by merging .pot file of 2024.1 into nvda.po of 2023.3 in poedit:
  Translated: 2798 of 2900 (96 %)  •  Remaining: 102

### Expected behavior:
Same number of strings to translate.

More specifically, the following strings should not have changed:
* "hiragana"
* Many braille abbreviations ("dlg", "btn", "mnu", etc.)
* "orange" (ctx="color hue")
* etc.

### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2024.1
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3693
#### Name and version of other software in use when reproducing the issue:
Poedit, Version 3.4.1 (6867)
#### Other information about your system:
N/A

**Comment by CyrilleB79** [comment]
Here is an example with two similar strings, the second has been dropped, the first not.

###Original file from NVDA 2023.3
Actually last file taken from SVN.

```
#. Translators: The color between  red and orange (HSV hue 15 degrees)
msgctxt "color hue"
msgid "red-orange"
msgstr "rouge-orange"

#. Translators: The color orange (HSV hue 30 degrees)
msgctxt "color hue"
msgid "orange"
msgstr "orange"
```

### Crowdin file for NVDA 2024.1
```
#. Translators: The color between  red and orange (HSV hue 15 degrees)
#: colors.py:190
msgctxt "color hue"
msgid "red-orange"
msgstr "rouge-orange"

#. Translators: The color orange (HSV hue 30 degrees)
#: colors.py:192
msgctxt "color hue"
msgid "orange"
msgstr ""
```

### NVDA 2023.3 .po file + NVDA 2024.1 .pot merge
Actually I have taken:
* last .po file in SVN
* .pot of last alpha in appVeyor since the one for NVDA 2024.1 was not available

```
#. Translators: The color between  red and orange (HSV hue 15 degrees)
#: colors.py:190
msgctxt "color hue"
msgid "red-orange"
msgstr "rouge-orange"

#. Translators: The color orange (HSV hue 30 degrees)
#: colors.py:192
msgctxt "color hue"
msgid "orange"
msgstr "orange"
```

**Comment by CyrilleB79** [comment]
I did not check all the strings but maybe it's because the source and the translation are the same.

That would explain why only "orange" is missing in the colors: it's the only color that has the same name in French as in English.

**Comment by michaelDCurran** [comment]
If it did loose many strings I think I can undo the import if necessary.

**Comment by zstanecic** [comment]
Hi,

Undo the import then also for polish and Croatian. 

I need to do some corrections.

**Comment by CyrilleB79** [comment]
> If it did loose many strings I think I can undo the import if necessary. Message ID: ***@***.***>

What do you mean?

For now there is no translation work in French translation, so you can undo what you want.
Cc @MichelSuch, @CoBC.

**Comment by CyrilleB79** [comment]
Additional note: The issue is probably general; does not impact only French.

**Comment by zstanecic** [comment]
Yes, issue impacts croatian and polish, too.

**Comment by michaelDCurran** [comment]
But can you confirm that the translated strings like "orange" are now there?

**Comment by ruifontes** [comment]
Michael, in portuguese "orange" was not affected since the translation is not equal.
If you need to undo all languages that is not a problem to me, since I translated downloading the .PO file, translating it and uploaded to the system.
The advantages are a better use of our translation database and possibility of approval of the translations in the upload process.

**Comment by Adriani90** [comment]
This could happen probably also when two people translate at the same time in the same language, maybe the approval process has not been completely done in Crowdin editor due to synchronizing problems. We need to check that before importing translations into NVDA from Crowding I guess. But I might be totally wrong and the cause comes from something different.

**Comment by michaelDCurran** [comment]
I think trying to fix this generally for all languages now may cause some translators to loose work, so I think it is better just to let translators handle this as they best see fit. In many cases they can just upload a PO file with these translations in place, remembering to turn on the allow translation same as source option. 
I have manually fixed this for French however, which was the original reason for this issue I believe.
I / the community can work with any other individual translators with this issue in future.

**Comment by CyrilleB79** [comment]
Just confirming here that for French, the new import contains the identical translations such as "orange". Thanks.
