### ISSUE TITLE
Inconsistent state reporting when overriding add-on incompatibility

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/nvda#15941]
### Steps to reproduce:
1. Open add-on store
2. Select an add-on that is disabled and incompatible
3. Enable the add-on, override the incompatibility.
4. Note the contents of the `status` column
5. Restart add-on store
6. Note the contents of the `status` column for the add-on that was previously enabled.

### Actual behavior:
Step 4: Status `enabled`
Step 6: Status `Enabled (incompatible)`

### Expected behavior:
Step 4: Status `enabled (Incompatible)`
Step 6: Status `Enabled (incompatible)`

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-30343

#### Windows version:
Windows 11 23H2

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not yet, but given the current status of Alpha, it is very likely that this also occurs in 2023.1 beta.

#### If NVDA add-ons are disabled, is your problem still occurring?
n/a

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by lukaszgo1** [comment]
@LeonarddeR  I cannot reproduce this with latest master, nor with the latest beta. My steps were as follows:
- Opened Add-ons Store
- From the Installed add-ons tab selected an incompatible disabled add-on (Mozilla Apps enhancements)
- From the context menu selected 'enable - override incompatibility'
- Answered the prompt
- The status of the add-on has changed to 'Enabled (incompatible), pending restart', and stayed like this no matter how many time I have reopened the store

**Comment by LeonarddeR** [comment]
I can no longer reproduce this either. It might have been fixed automagically.
