### ISSUE TITLE
compatibility issue with a text expander software named Breevy

### ISSUE THREAD

**Issue by jprykiel** [nvaccess/nvda#15959]
Hello.
Github is not the easiest thing in the world, and if I'm posting this to the wrong place, thanks for telling me where to post it before closing this issue.

I use a text expander software called Breevy. 
https://www.16software.com/breevy/
It allows you to type words or even whole phrases just by typing a few signs.
I never had any issue using it with Jaws, but with NVDA, it behaves strangely. I have the latest available stable version of both under Windows 10.
When an abbreviation's result contains unconventional characters, such as ê é ç and so on, these correctors are not written. Even when the abbreviation does not contain any of these, I noticed that the result is spelt out by NVDA which is not normal.
I would like to know if NVDA intercepts what is output by Breevy in any way before it's actually written, and if there is a way to avoid this.
I know that compatibility between 2 applications  is  a delicate question, especially if both developers do not know each other, what usually happens is that one will blame the other one and vice versa.
I still count on you helping me to solve this problem.
Best regards and Merry Christmas to you all,
Jean-Philippe Rykiel

**Comment by Emil-18** [comment]
Just downloaded and tested Breevy, and it didn't work with both NVDA and JAWS. The application window was completely inaccessible with both screen readers.

**Comment by jprykiel** [comment]
Thanks for your reply @Emil-18. My apologies, you're absolutely correct, I needed sided assistance to enter my licence key and add my own abbreviations. But since it was done, I was able to use the program and I'm still using it for so long that I actually forgot I had to do all this before…
Can you still help anyway? A more general question may be, do you know if, in some cases,  NVDA can interfere with what you are writing? That would help me understand.
Thanks and Merry Christmas.
JPR

**Comment by Emil-18** [comment]
@jprykiel Have you tried turning off "Handle keys from other applications" in keyboard settings? I think that may solv the problem with characters don't being written.

**Comment by jprykiel** [comment]
@Emil-18, you made my day! This worked. I wonder if it could have any disadvantage, but none that I saw for the moment.
Thanks a lot,
JPR

**Comment by CyrilleB79** [comment]
Closing this issue as resolved.
@jprykiel, if this setting change causes any unexpected side effect, please comment here and we can reopen.
