### ISSUE TITLE
Problem sharing screen in MS Teams

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#15955]
### Steps to reproduce:
Join or create a MS Teams meeting
Share screen by pressing ctrl+shift+e
Tab three times to reach the button to share the entire screen or tab a fourth time to reach the button to share a window

### Actual behavior:

shift+ctrl+e
Hide share options (Ctrl+Shift+E)
Share content  dialog
Include computer sound  switch  off  
Share content
switch  off    Include computer sound
heading    level 3  Presenter mode
Presenter mode  tool bar    radio button  checked    Content only  radio button  not checked    Standout  radio button  not checked    Side-by-side  radio button  not checked    Reporter  out of tool bar
button    Add background
heading    level 4  Screen
heading    level 4  Window (6)
button    Share Microsoft Whiteboard Collaborate on a whiteboard
heading    level 3  PowerPoint Live
See your notes, slides, and audience while you present.
tab
Presenter mode  tool bar
grouping
Content only  radio button  checked  1 of 4
tab
Add background  button  
tab
blank
tab
blank
I have tried NVDA+Enter to activate, with no success.  Also tried routing the mouse, again without success.
Narrator reports "generic PNT(?) monitorFOR the screen and "List of five windows" for windows and buttons can be activated.
With no screen reader running, tabbing to the Screen button and pressing Enter works (checked by a sighted observer).
### Expected behavior:

Sorry, cannot demonstrate expected behaviour.  Both buttons should be located and it should be possible to activate them.
#### NVDA installed/portable/running from source:
NVDA installed
#### NVDA version:
2023.3
#### Windows version:
Windows 10 Home
#### Name and version of other software in use when reproducing the issue:
Microsoft Teams (tried on two computers)
#### Other information about your system:
Both Windows and Teams should be up to date
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I cannot remember last time it worked correctly.  I am sure though the issue is relatively recent, which suggests that something has changed in Teams rather than NVDA.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by sevapopov2** [comment]
Hello,
To be able to access choosing the part of the screen you want to share with NVDA you should go to focus mode by pressing insert+space after openning share content window, then press tab. On elements where it told blank blank it will tell options to share.
I cannot tell about microsoft teams but usually if you press tab and hear blank it means that the element has an attribute aria-hidden set to true and you should use focus mode to be able to find and access it with NVDA.

**Comment by andrew-l-d** [comment]
You are spot on.  Given the fickle nature of Teams, I should have thought of that.  Closing the ticket.
