### ISSUE TITLE
Generating the list of all modules in library.zip and publishing that as an appveyor artifact

### ISSUE THREAD

**Issue by gerald-hartig** [nvaccess/nvda#15971]
### Is your feature request related to a problem? Please describe.

Issue https://github.com/nvaccess/nvda/issues/15886 raises the problem of python environment maintenance between nvda core & add-ons. How much responsibility does NV Access take to provide the environment that add-on developers need to build their code, and thus avoid the developer having to roll their own and coming up against version incompatibilities, dependency chain issues, architecture compatibility issues, etc.

In order for NV Access to manage this issue more effectively, a first step is to clearly list the Python standard library modules included in nvda's binary builds.

### Describe the solution you'd like

- In the build system, after building NVDA with scons, recursively find all *.pyc files in the generated library.zip
- Write them all to a file, converting their paths to Python module syntax, I.e. from x\y\z.pyc to x.y.z.
- Make sure that file is exported as an artifact. 

Then at a later stage, we can look at producing diffs of this file between releases.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by Brian1Gaff** [comment]
If people update existing copies of nvda though, many existing add ons will still work but have been written in previous versions of the code, surely?
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
  ----- Original Message ----- 
  From: gerald-hartig 
  To: nvaccess/nvda 
  Cc: Subscribed 
  Sent: Wednesday, December 27, 2023 1:32 AM
  Subject: [nvaccess/nvda] Generating the list of all modules in library.zip and publishing that as an appveyor artifact (Issue #15971)



  Is your feature request related to a problem? Please describe.
  Issue #15886 raises the problem of python environment maintenance between nvda core & add-ons. How much responsibility does NV Access take to provide the environment that add-on developers need to build their code, and thus avoid the developer having to roll their own and coming up against version incompatibilities, dependency chain issues, architecture compatibility issues, etc.

  In order for NV Access to manage this issue more effectively, a first step is to clearly list the Python standard library modules included in nvda's binary builds.

  Describe the solution you'd like
    a.. In the build system, after building NVDA with scons, recursively find all *.pyc files in the generated library.zip 
    b.. Write them all to a file, converting their paths to Python module syntax, I.e. from x\y\z.pyc to x.y.z. 
    c.. Make sure that file is exported as an artifact. 
  Then at a later stage, we can look at producing diffs of this file between releases.

  Describe alternatives you've considered
  N/A

  Additional context
  N/A
