### ISSUE TITLE
Automatic lowering of sounds from other applications/programs while using NVDA

### ISSUE THREAD

**Issue by kerp4l** [nvaccess/nvda#15985]
### Is your feature request related to a problem? Please describe.
I am always frustrated when I am trying to work using  NVDA and at the same time listen some music. it is very annoying because there is no setting to make all the other running applications/programs sounds slighty go down when using NVDA. For example when I am working with MS Word, it is very hard to hear properly what the NVDA is saying while I am writing something  and while listening some sweet Finnish heavy metal from Spotify, because the music and NVDa speech become just one big mass. And the maximum sound level available on NVDA could be more higher, for example for me it always has been at the 100% level and I wouldh wish it would go higher.
### Describe the solution you'd like
I would like there to be a setting that I can choose which would lower the volume of other applications/programs while I am using NVDA. For example the Windoes Narrator has this setting available. And also the maximum volume level of the NVDA could be raised.
### Describe alternatives you've considered
No alternative suggestions comes to my mind. The way that Windows Narrator does this has worked for me very well.
### Additional context
No additional context.

**Comment by josephsl** [comment]
Hi, try NVDA+Shift+D and see if that makes a difference between night and day. Thanks.

**Comment by Adriani90** [comment]
There is the audio ducking setting in the audio settings category, either nvda+shift+d as Joseph suggestend or open the dialog with ctrl+nvda+u.

Closing as invalid.

**Comment by Adriani90** [comment]
If audio ducking is still not working, see #15790. Make sure User Account Control is enabled in your Windows.
