### ISSUE TITLE
Mouse navigation in Firefox: Speech a portion of text aloud or do not speech text in certain paragraphs

### ISSUE THREAD

**Issue by hwf1324** [nvaccess/nvda#15990]
Note: This issue is different from other mouse tracking issues.
To fully reproduce the issue, please open the original webpage.
Will text unit resolution left at the default "paragraph".

### Steps to reproduce:

1. Open the link in Firefox:

https://github.com/nvaccess/nvda-misc-deps/pull/30#issue-2051587636

3. Move the cursor to the paragraph using the mouse

> As such text2tags doesn't have default rules for this. To retain our custom anchors, I added rules for a common markdown extended syntax. This is supported by the [python markdown legacy attributes extension](https://python-markdown.github.io/extensions/legacy_attrs).
> Similarly we use a custom syntax for autogenerating the [Table of contents](https://python-markdown.github.io/extensions/toc/).

4. Then move the mouse cursor to the paragraph

> Similarly we use a custom syntax for autogenerating the [Table of contents](https://python-markdown.github.io/extensions/toc/).

### Actual behavior:

In step 2, the speech output is:

> As such text2tags doesn't have default rules for this. To retain our custom anchors, I added rules f

Step 3, no speech output

Note that this problem does not only occur when there are links in a paragraph.

### Expected behavior:

Should be consistent with Chrome and Edge, speech the text under the mouse cursor

#### NVDA installed/portable/running from source:

All

#### NVDA version:

2023.3 to latest alpha

#### Windows version:

Windows 11
Version 22H2 (OS Build 22621.2861)

#### Name and version of other software in use when reproducing the issue:

Firefox
121.0 (64-bit)

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

same

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by hwf1324** [comment]
Open https://plantuml.com/en/class-diagram

After the second paragraph of the article, the "text" under the mouse is not read aloud, or is misplaced.

**Comment by hwf1324** [comment]
Cc: @jcsteh

I'm not sure if this is a Firefox issue, the Firefox accessibility tree looks correct.

The narrator doesn't have this issue either.

**Comment by jcsteh** [comment]
I have a patch locally which fixes this. I'll submit a PR when I get some time.

**Comment by hwf1324** [comment]
Thank you very much for your work.

**Comment by MoubinShiraz** [comment]
Hi @hwf1324 .
It seems that they have fixed the BUG. However, when I open this again https://codepen.io/Moubin-Shiraz/pen/LYKRpJB/ , the BUG still exists in my system "Windows 11". Can you please confirm that is it only on my side or you are also facing the same.
If you are not facing the same issue again. Please let me know how should I get those changes in NVDA desktop App in my system?

cc: @jcsteh

**Comment by seanbudd** [comment]
@MoubinShiraz - I'm not sure how you have tested this, are you testing with the latest alpha build? https://www.nvaccess.org/files/nvda/snapshots/

This code won't be released to NVDA stable until 2024.4 is released

**Comment by hwf1324** [comment]
@MoubinShiraz 
I confirm that this issue is fixed in NVDA version: alpha-33085,f05f1c8f (2024.4.0.33085).
