### ISSUE TITLE
Feature request: add more roles to jump to in browse mode QuickNav commands

### ISSUE THREAD

**Issue by mltony** [nvaccess/nvda#16001]
I propose to add more roles to jump to in QuickNav scripts in NVDA. I will implement this feature request myself if green light is given by NVDA team.
* Menu item
* next list item of the same level (useful for nested lists with items of multiple levels)
* Toggle Button
* Progress bar
* math
I propose to leave these gestures unassigned by default.
Navigating to next element by type (menu/progress bar/math) will be  only implemented for IA2, since all major browser these days work with IA2 and it's impossible to test MSHTML and UIA implementations. It will be implemented in a manner similar to other QuickNav commands.

**Comment by mltony** [comment]
Previous discussion in #15996.

**Comment by ABuffEr** [comment]
Hi @mltony,
very happy to see your contributions.
About this issue, in last months I'm thinking about the interaction needed by some roles. Menu/menu item like list/list item was already highlighted somewhere, but I also noticed toggle button and switch, that have the same conceptual interaction (on/off) of checkbox.
I struggle a lot to understand why these roles should be keep under different/unassigned quick nav gestures, making them probably much less "quick".
It's not a criticism to you, of course, just a thought to drive the current situation to a better and more flexible one, hopefully.

**Comment by cary-rowen** [comment]
If possible, I would like to have gestures assigned to these roles by default, just like the tab navigation, which user know is useful, but user have to manually assign gesture. This situation reduces the discoverability of useful features.
There is also the fact that we no longer have enough alphabetic keys.
