### ISSUE TITLE
Feature request: add QuickNav command for Same style navigation in browse mode

### ISSUE THREAD

**Issue by mltony** [nvaccess/nvda#16000]
I propose to add  Same style navigation in browse mode. I I will implement this feature request myself if green light is given by NVDA team.
*jump to next/previous text written in the same style as current text.
* Style is defined as font name and other attributes, such as font size, bold, italic, etc.
* Utility of this function can also be illustrated on [issues list on github](https://github.com/nvaccess/nvda/issues/) - as all the issue titles are written in the same style.
* I propose to assign by default  right bracket `]` and `Shift+]` gestures to this command.
* This feature has already been implemented in [BrowserNav add-on](https://addons.nvda-project.org/addons/browsernav.en.html) and can be triggered by first adjusting BrowserNav rotor by pressing `NVDA+O` to the value "BrowserNav navigates by  font size and same style"  and then pressing `NVDA+Control+Up/Down` keystrokes.
    * In BrowserNav however, same style navigation only finds other paragraphs written in the same style; therefore it would miss same style within the same paragraph. This feature request proposes to find any text within or without current paragraph.

**Comment by mltony** [comment]
Previous discussion in #15996.

**Comment by seanbudd** [comment]
Could you please explain more as to why it's by paragraph?
I can understand the utility of groups by style, but consider it could be misleading for skipping over style changes within paragraphs.

**Comment by mltony** [comment]
The reason why I was thinking about paragraphs is that in BrowserNav add-on that's the main theme - finding paragraphs with different criteria. But I see your point that it's going to be confusing if we miss same style within paragraph. Let me change description so that we find next/previous  character instead of paragraph with the same formatting.
