### ISSUE TITLE
NVDA 2024.1 beta 2 Portable not speaking capitals with eSpeak

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#16003]
### Steps to reproduce:
1.  Open a portable copy of NVDA 2024.1 beta 2.
2. Set eSpeak as the synthesizer.
3. In any document, webpage, email or Windows Explorer, navigate to an uppercase character with left or right arrow.
### Actual behavior:

New Issue · nvaccess/nvda — Mozilla Firefox
New Issue · nvaccess/nvda  document
main landmark
Write  property page
Comment  edit  multi line  blank
alt+tab
NVDA 2024.1beta2 User Guide - Google Chrome  row 1  column 2
NVDA 2024.1beta2 User Guide  document
heading    level 1  NVDA 2024.1beta2 User Guide
ctrl+right arrow
Guide
ctrl+right arrow
out of heading  heading    level 2  Table 
ctrl+right arrow
of 
ctrl+right arrow
Contents
right arrow
o
Oscar
left arrow
C
Charlie
left arrow
space

right arrow
C
Charlie
right arrow
o
Oscar
left arrow
C
Charlie
left arrow
space

ctrl+left arrow
Table 
right arrow
a
Alfa
left arrow
T
Tango
left arrow
out of he
The Speech Viewer does not accurately reflect the issue.  It is showing the letter when NVDA makes the error sound.  If navigating to a word with - say - ctrl+right arrow NVDA speaks the word correctly.  If using left arrow to go to the uppercase letter, the error sound occurs.Similarly, if navigating to a word with right arrow the error sound occurs.  Note that the issue only occurs with the eSpeak synthetizer.  The issue occurs regardless of which option for presenting uppercase characters is selected.
### Expected behavior:

When navigating to an uppercase character with right or left arrow keys, the character will be presented correctly.  
### NVDA logs, crash dumps and other attachments:
See espeak-no-speak-caps.txt
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
NVDA 2024.1 beta 2 
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
Outlook, Notepad++, Notetab Pro, Chrome, Firefox.
#### Other information about your system:
Should be up to date
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I am fairly certain the issue was present with 2024.1 beta 1, also running as portable.  I have not encountered the issue with any prior version.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes
[espeak-no-speak-caps.txt](https://github.com/nvaccess/nvda/files/13827288/espeak-no-speak-caps.txt)
[espeak-no-speak-caps.txt](https://github.com/nvaccess/nvda/files/13827293/espeak-no-speak-caps.txt)

**Comment by lukaszgo1** [comment]
@andrew-l-d  I cannot reproduce this. What is your eSpeak pitch set to? Also how you've set 'Capital pitch change percentage' in the settings panel?

**Comment by hwf1324** [comment]
I can't reproduce it in Windows 10/11 either, what language/voice variant are you using?

**Comment by andrew-l-d** [comment]
Thanks both for the feedback.  The one setting I did not check!  Pitch change for capitals is set at 30 and because eSpeak ignores it I left it there.  But I dropped the eSpeak pitch to 0 and that is what caused the problem.  I will therefore close the issue.

**Comment by XLTechie** [comment]
@andrew-l-d Why do you say that ESpeak ignores the caps pitch setting? Or have I 
misunderstood you?
It does not ignore it on my system.

**Comment by andrew-l-d** [comment]
Luke, you are correct.  With pitch change set to 50 it is obvious.  When set to 30 with the Male 7 variant set to pitch 20 and with my aging ears it is not obvious.


Andrew

**Comment by XLTechie** [comment]
Ah okay. :)
