### ISSUE TITLE
Speech modes status not announced when enabling/disabling from settings

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#16005]
### Steps to reproduce:

1. open voice settings;
2. scroll to the new list with speech modes;
3. try to enable or disable one.

### Actual behavior:

NVDA says nothing, and Braille is not refreshed.

### Expected behavior:

NVDA should say "enabled" or "disabled", and Braille update accordingly.

#### NVDA installed/portable/running from source:

Installed and ran from source.

#### NVDA version:

Alpha, but also last commit on beta branch (after release-2024.1beta2 tag).

#### Windows version:

Windows 10 22H2.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

I tried source at release-2024.1beta2 tag, that not include [this commit](https://github.com/nvaccess/nvda/commit/e4a2474e7155a8e61ae2d9df3ff9e60c1a3cb05b) from #15960, that introduced the issue.

I'll provide a fix in minutes; but considering the above commit, I'll try to make a PR on beta branch.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Not relevant.

**Comment by XLTechie** [comment]
I noticed this as well--"checked" or "unchecked" is not announced for those 
boxes. So confirmed.

CC @lukaszgo1

**Comment by hwf1324** [comment]
Sorry, I just noticed this problem.

The cause is caused by my event handler bound to `wx.EVT_CHECKLISTBOX` forgetting to pass the event message on.

Simply adding `evt.Skip()` to the end of the `_onSpeechModesListChange` method should fix this. 

> I'll provide a fix in minutes; but considering the above commit, I'll try to make a PR on beta branch.

@ABuffEr Are you going to fix it? I'm happy to see it.

**Comment by ABuffEr** [comment]
Hi @hwf1324,
yes exactly, I already discovered it before opening the issue. I added evt.Skip() as you say, but at the beginning of the method (as done in custom control handler). PR #16006 is up.

**Comment by hwf1324** [comment]
OK, there should be no difference for this issue.
