### ISSUE TITLE
severely limited functionality after windows 2024 update

### ISSUE THREAD

**Issue by insomnimus** [nvaccess/nvda#16029]

**Comment by insomnimus** [comment]
Amazing, it seems I can't even type here properly...
Here's what i had copied and pasted:

After the latest Windows update as of January 11 2024, NVDA does not report any context ("button", "radio button", "link", "heading leve ..." etc).
In fact it can't even report the NVDA menus brought by nvda+n.

I've tried reinstalling NVDA but that did nothing.
I've unrolled the Windows update, and shockingly that also didn't fix the problem.
I was going to go back to a recovery point only to find out i had no recovery points.

**Comment by insomnimus** [comment]
In my frustration I forgot to mention a few important details:

- I'm using Windows 10 22h2.
- I've tried disabling addons but as previously stated, I'm not able to interact with NVDA menus.
- Right before the Windows update, NVDA was functioning properly; this was last night before I went to sleep.

**Comment by insomnimus** [comment]
Interesting update: I can access the NVDA menus during the Windows login screen.
So the problem begins manifesting after sign in, somehow...

**Comment by insomnimus** [comment]
Update: Starting NVDA from the command line using `--disable-addons` does not address the issue.

**Comment by hwf1324** [comment]
Are you unable to change your initial description?

**Comment by lukaszgo1** [comment]
The issue template  asks:
< Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Are you able to do this and report what is the outcome? If NVDA menu fails to read I'll try to start NVDA and Narrator at the same time to execute the tool.

**Comment by insomnimus** [comment]
Actually I wasn't able to interact with any NVDA settings.
However after noticing that the sign-in profile was unaffected, I decided to clear my NVDA configuration directory at `$LOCALAPPDATA/nvda`.
This fixed the issue, which is odd as I haven't changed any NVDA configuration in the past week.

I'm sorry for the false positive, this was pretty hard to figure out.

**Comment by insomnimus** [comment]
Huh, now that I've fixed the problem, I'm restoring my old configuration one by one and I noticed that NVDA's language was changed to Persian, which would explain NVDA not speaking contextual information: It actually tries but my TTS engine is configured for English, which doesn't understand Persian letters, and ignores those words.

Anyway, sorry for the false alarm. It coinciding with the Widnows update is likely a red herring...
