### ISSUE TITLE
userguide multiple targets

### ISSUE THREAD

**Issue by Kc9jjj** [nvaccess/nvda#16030]
### Steps to reproduce:
run scons.bat
### Actual behavior:

                                                                                                                                                                                   
scons: *** Multiple ways to build the same target were specified for: user_docs\am\keyCommands.html  (from ['user_docs\\am\\keyCommands.md'] and from ['user_docs\\am\\userGuide.md'])                                                                                                                                                                                
File "C:\Users\Darren\nvda\SConstruct", line 271, in <module>                                                                                                                      
D
### Expected behavior:

build without errors
#### NVDA installed/portable/running from source:
source
#### NVDA version:
latest source
#### Windows version:
windows 11 pro 23h2
#### Name and version of other software in use when reproducing the issue:
windows terminal
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
n/a
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
n/a

**Comment by seanbudd** [comment]
Please clean dirty files before building - you have uncommitted files in your repository that need to be removed.

**Comment by seanbudd** [comment]
Particularly, run:

`git clean -xf user_docs/*/keyCommands.t2t`
`git clean -xi user_docs/*/*.md`
`git clean -xf user_docs/*/*.html`

**Comment by Kc9jjj** [comment]
thanks that worked
