### ISSUE TITLE
Documentation is inadequate for math support setup

### ISSUE THREAD

**Issue by mitchellevan** [nvaccess/nvda#16036]
### Steps to reproduce:

1. Read [NVDA documentation for adding math support](https://www.nvaccess.org/files/nvda/documentation/userGuide.html#ReadingMath).
2. Follow the link as instructed: https://www.dessci.com/en/products/mathplayer/
3. Observe that the browser redirects to: https://info.wiris.com/mathplayer-info
4. Read the documentation on the Wiris web page, which NVDA depends on by reference.
5. Determine whether it is necessary to install MathPlayer 4 based on the instructions.

### Actual behavior:

NVDA documentation says:

> Using MathPlayer 4 from Design Science, NVDA can read and interactively navigate supported mathematical content. This requires that MathPlayer 4 is installed on the computer. MathPlayer is available as a free download from: https://www.dessci.com/en/products/mathplayer/. After installing MathPlayer, restart NVDA. 

The Wiris documentation (which NVDA depends on) says:

> MathPlayer views and speaks web pages containing math. Accessibility for web environments using MathPlayer is limited to obsolete browsers such as Internet Explorer 8.

Taken together, the above NVDA and Wiris instructions currently inform users that MathPlayer is necessary, but only for Internet Explorer 8. However, this is incorrect. For example, if I perform the "Steps to reproduce" in #16035 using Firefox or Chrome, without first installing MathPlayer, then NVDA does not announce the structure of MathML content.

### Expected behavior:

If MathPlayer 4 is required for all browsers, instructions should clearly say that it is required.

### NVDA logs, crash dumps and other attachments:

not checked

#### NVDA installed/portable/running from source:

installed

#### NVDA version:

Version: 2023.2 (2023.2.0.29051)

#### Windows version:

Version 10.0.19045 Build 19045

#### Name and version of other software in use when reproducing the issue:

Chrome 120
Firefox 121.0.1

#### Other information about your system:

none

#### Does the issue still occur after restarting your computer?

yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

no

#### If NVDA add-ons are disabled, is your problem still occurring?

not attempted

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

not attempted

**Comment by josephsl** [comment]
Hi, isn’t MathPlayer 4 deprecated and no longer developed? If it is still being developed yet the documentation on its own website recommends IE8 or other older browsers, then I think it would be best to ask the webmaster of MathPlayer website to update their docs while updating NVDA user guide to point to the redirected website. As an alternative, try MathCAT add-on (with NVDA 2023.3) and see if that makes a difference (JAWS uses MathCAT). Thanks.

**Comment by seanbudd** [comment]
Related #15352
