### ISSUE TITLE
2023.3.1 regression: add-on store can't download 2023.3.1 API data

### ISSUE THREAD

**Issue by hwf1324** [nvaccess/nvda#16046]
### Steps to reproduce:

Open the add-on store

### Actual behavior:

Add-on data update failure
Unable to fetch latest add-on data for compatible add-ons.

### Expected behavior:

The installable add-ons should be displayed within the Installable tab

### NVDA logs, crash dumps and other attachments:

```log
IO - speech.speech.speak (17:21:22.419) - MainThread (22280):
Speaking [LangChangeCommand ('zh_CN'), 'Available add-ons:', 'list', 'Alt+a', CancellableSpeech (still valid)]
ERROR - _addonStore.dataManager._DataManager._getLatestAddonsDataForVersion (17:21:24.199) - getAddonData (22676):
Unable to get data from API (https://nvaccess.org/addonStore/en/all/2023.3.1.json), response (400): b'Addon API version not available'
DEBUG - gui._addonStoreGui.viewModels.store.AddonStoreVM._getAvailableAddonsInBG (17:21:24.211) - getAddonData (22676):
completed getting addons in the background
DEBUG - gui._addonStoreGui.viewModels.addonList.AddonListVM.resetListItems (17:21:24.211) - getAddonData (22676):
resetting list items
DEBUG - gui._addonStoreGui.viewModels.addonList.AddonListVM._tryPersistSelection (17:21:24.211) - getAddonData (22676):
No entries in new order
```

[nvda-old.log](https://github.com/nvaccess/nvda/files/13937188/nvda-old.log)

#### NVDA installed/portable/running from source:

portable

#### NVDA version:

2023.3.1

#### Windows version:

Windows 11

#### Name and version of other software in use when reproducing the issue:

None

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes, 2023.3 Normal

#### If NVDA add-ons are disabled, is your problem still occurring?

None

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by josephsl** [comment]
Hi,

Resolved - had to add Windows App Essentials dev build to trigger views branch to show 2023.3.1 view of the add-on store. In other words, as stated in the linked pull request (no longer necessary), views must be rerun whenever stable NVDA releases are released; in this case, when a patch release shows up.

Thanks.
