### ISSUE TITLE
The options table in the user guide is very difficult to read

### ISSUE THREAD

**Issue by wmhn1872265132** [nvaccess/nvda#16063]
### Steps to reproduce:
Open the user guide page below and read the table of options under "Delayed descriptions for characters on cursor movement".
https://www.nvaccess.org/files/nvda/releases/2024.1beta4/documentation/en/userGuide.html#delayedCharacterDescriptions

### Actual behavior:

> down arrow
heading    level 5  Delayed descriptions for characters on cursor movement
down arrow
table  with 3 rows and 2 columns  Default
down arrow
Disabled
down arrow
Default  Options
down arrow
Disabled  Enabled, Disabled
down arrow
Default  ---
down arrow
Disabled  ---

This table is difficult to understand because Default and Disabled are incorrectly used as headers.

### Expected behavior:

Default and Disabled should not be used as table headers

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2024.1beta4(2024.1.0.30651)

#### Windows version:
Windows 11

#### Name and version of other software in use when reproducing the issue:
Microsoft Edge Version 120.0.2210.133

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This is a change in the 2024.1 development cycle. In previous versions, this information was presented in a list.

#### If NVDA add-ons are disabled, is your problem still occurring?
irrelevant

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
irrelevant

**Comment by wmhn1872265132** [comment]
This is just one example, there are many more such tables

**Comment by CyrilleB79** [comment]
Confirmed. In addition, there is an unexpected extra row in last position with dashes in it.

**Comment by seanbudd** [comment]
I think an easy fix for this would be adding a generic header to the table i.e. "Attribute, details". Also the last row of these tables needs to be fixed up.

**Comment by seanbudd** [comment]
Makes sense @wmhn1872265132
