### ISSUE TITLE
Emoticons, Don't Speak, but instead punctuations/symbols

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1608]
**Reported by kevinchao89 on 2011-06-25 18:06**
Windows XP and 7
2011.2 beta and Snapshot 4503 

Before (2011.1.1 and earlier), it would say smilie for :) frown for :(
Now it just says the punctuation/symbol marks, 

Applies to all other emoticons, as well.

**Comment by ehollig** [comment]
This sounds like it can be resolved with the [Emoticons](http://addons.nvda-project.org/addons/emoticons.en.html) addon or with user dictionary rules. Also, some websites and programs have their own versions of the symbols that read correctly. (Skype and Facebook, for example)

**Comment by derekriemer** [comment]
@jcsteh or @feerrenrut any idea if this is a close because of the addon, or a p4/p3?

**Comment by jcsteh** [comment]
Speaking of Emoji is definitely in scope (covered by #6523). Emoticons are a bit more risky because they can match combinations of symbols which appear elsewhere. @MichaelDCurran, thoughts?

**Comment by ehollig** [comment]
Possibly related issues: #909, #3530

**Comment by bhavyashah** [comment]
As requested by @jcsteh in https://github.com/nvaccess/nvda/issues/1608#issuecomment-315643471, @michaelDCurran, thoughts? Just a gentle reminder in case that comment got inadvertently skipped earlier.

**Comment by michaelDCurran** [comment]
I don't think we need to support Emoticons as it is possible to understand them as punctuation symbols. Also, an add-on exists for this already. Emoji on the other hand needs to be supported directly.
