### ISSUE TITLE
Rename NVDA process helper name from "A free and open source screen reader for Microsoft Windows" to "NVDA process helper"

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#16094]
### Is your feature request related to a problem? Please describe.

When installing NVDA 2024.1 Beta 5 or running a COM Registration fixing tool, the UAC dialog gives the application name of NVDA as "A free and open source screen reader for Microsoft Windows".

### Describe the solution you'd like

It would be beneficial to at least include "NVDA" in there.  In discussion with Sean, his suggestion is:
"NVDA Process Helper"

### Describe alternatives you've considered

In previous versions of NVDA (2023.3) this name was simply given as "NVDA".

### Additional context

From Sean: "This is a change made during our upgrade of py2exe."

**Comment by XLTechie** [comment]
Personally, I would prefer something a little less technical, and more end-user 
friendly.

E.g. "NVDA screen reader".

E.g. "Non-Visual Desktop Access"

**Comment by lukaszgo1** [comment]
My suggestion will be to restore the 2023.3 name i.e. NVDA, since:
- Users do not really care that particular action is invoked by a helper process. More importantly
- The name we can provide for our executables, is not, and cannot be easily made to be, translatable, so adding any English there should be done only if absolutely necessary

**Comment by XLTechie** [comment]
> My suggestion will be to restore the 2023.3 name i.e. NVDA, since:

That seems agreeable. I did not know of the translation problem.

>  *  Users do not really care that particular action is invoked by a helper process.

Yes, quite. Most don't even know what one is. We do not need to be technically 
accurate on this, just informative at a level all will understand, which is what 
I was trying to say before.
