### ISSUE TITLE
Add the ability for NVDA to speak a certain number of previously spoken phrases

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1609]
**Reported by elliott94 on 2011-06-25 18:14**
This is an idea that I've had for a while now, and something that I don't think any other screen readers currently have the ability to do.

I think that it could be useful for NVDA to speak previously-spoken text. A good example of when this could be useful is when a user misses a Help Baloon, Tooltip, etc and that particular piece of text can not be reviewed.

If this were to be implimented, as a starting point, a combination of the NVDA, CTRL, and a number from 1-0 could be used - in theery, this could allow NVDA to speak the previous ten strings. I realise that in order for this to be achieved the last couple of spoken phrases would have to be stored on-the-fly and removed on exit, so not sure if this could potentially lead to any performence decredations.

Just an idea that I thought could be useful.
**Blocking #4323**

**Comment by ehollig** [comment]
@elliott94, this is now possible with the [Speech History](https://addons.nvda-project.org/addons/speech_history.en.html) addon. I do not know if this will become a core feature of NVDA though. Is this what you were looking for?

**Comment by elliott94** [comment]
This is exactly what I was looking for. :) Thank you, happy for this to be closed.

**Comment by ehollig** [comment]
Closing because of https://github.com/nvaccess/nvda/issues/1609#issuecomment-320516775.
