### ISSUE TITLE
Add table of contents to key commands and change log

### ISSUE THREAD

**Issue by seanbudd** [nvaccess/nvda#16106]
### Is your feature request related to a problem? Please describe.
As a user it can be challenging to navigate the key commands guide, there is no clear document outline.

The change log is a bit unique - unlike the user guide or the key commands, most people expect to read from top to bottom, usually just checking the latest entry.
However, it would be handy to easily jump to a given years API changes for example, or just check the new feature for recent releases.
The table of contents would still allow easy jumping to the first entry.

### Describe the solution you'd like
Add table of contents to key commands and change log

### Describe alternatives you've considered
Leave as-is, only have a table of contents for the user guide and developer guide

**Comment by seanbudd** [comment]
more feedback here from the community would be appreciate before proceeding

**Comment by CyrilleB79** [comment]
Regarding key commands, I have no strong opinion. But I agree that this document's organization may not be obvious and that the table of content may help here.

Regarding the Change log, I am rather opposed to add it a table of content. The vast majority want to see the changes of the last version. Today that's the first text they read when they open the document; with a table of content, they will have to find the interesting information further, either going down with downArrow, quick navigating with "H" or pressing the first or second link of the table of content.
I guess that the people wanting to look at information of previous releases are more experimented, so they will be able to find it more easily even without table of content. If they use a screen reader, quick navigating between level 2 heading with "2" key is quite efficent to find a specific release. If they are sighted, this may be a bit longer, but scrolling is also quite fast for sighted people.
At last, are there many examples of table of contents in change logs?

**Comment by cary-rowen** [comment]
I don't have any more feedback on this, and to some extent I think it's redundant.

**Comment by Nael-Sayegh** [comment]
I agree with @CyrilleB79, adding a table of contents may not be a good idea because it will get longer with each new version and people may be less interested in reading it if they are not comfortable with that kind of system. I think it's better to leave it as it is.
But I think it's a good idea to make one for the list of keyboard shortcuts.
