### ISSUE TITLE
NVDA doesn't consistently announce text that is shown in its speech viewer

### ISSUE THREAD

**Issue by jasmineylopez** [nvaccess/nvda#16116]
### Steps to reproduce:

1. Install Microsoft Edge Canary
2. Log in to an account 
3. There should be a button near the top left. If there is no button if you are logged in with a work account, the policy for the Workspaces feature may be disabled. Try logging in with a personal test account. 
4. <img width="191" alt="image" src="https://github.com/nvaccess/nvda/assets/158246464/ae03b667-0699-4acc-89c4-14aa7e5bddec">
6. Click the button, a dialog should open with an option to create a workspace. 
7. Click "Create new" and choose a name/color.
8. Now you should be in the Workspace, you can tell that by seeing the workspace button icon with the name of your workspace. 
9. <img width="251" alt="image" src="https://github.com/nvaccess/nvda/assets/158246464/c38c51a9-f4be-41c2-b0a2-ee79615bda78">
10. At this point NVDA can be running.
11. Now click the workspaces button again to open the menu and select the "..." button next to the "+" button. 
12. <img width="284" alt="image" src="https://github.com/nvaccess/nvda/assets/158246464/f66ae50a-d2ba-4d0e-9e87-ca0841431ef5">
13. Click Hide Workspaces button and observe that the speech viewer displays this text: **Closing all open workspace windows.
Workspaces button removed from toolbar** but does not announce. 

### Actual behavior:
The speech viewer displays the correct text bolded below, but NVDA either doesn't announce "Closing all open workspace windows" or it doesn't announce both that message and "Workspaces button removed from toolbar.

#### Speech Viewer:
Show Speech Viewer on Startup
NVDA Log Viewer
Application Contains commands to manipulate the current view or document
panel
Discover
 
FolderView
Add favorites to this workspace by placing them here on the favorites bar.
Test Fluid Workspace  window
Workspaces
 
Workspaces  tool bar
More options  button
Context
Learn more  1 of 3
Learn more
Send feedback
Send feedback  2 of 3
Hide Workspaces button
Hide Workspaces button  3 of 3
**Closing all open workspace windows.
Workspaces button removed from toolbar**
Workspaces button removed from toolbar
NVDA Log Viewer
edit  read only  multi line  INFO - __main__ (09:21:23.769) - MainThread (6816):
NVDA+f
 
NVDA+k
 
NVDA+k
Report link destination
edit  read only  multi line  INFO - __main__ (09:21:23.769) - MainThread (6816):
NVDA+f
 

### Expected behavior:
NVDA should announce this text: **Closing all open workspace windows.
Workspaces button removed from toolbar**

### NVDA logs, crash dumps and other attachments:
[9:23 AM] Jasmine Lopez (SHE/HER)
INFO - __main__ (09:21:23.769) - MainThread (6816):

Starting NVDA version 2023.3.3

INFO - core.main (09:21:24.121) - MainThread (6816):

Config dir: C:\Users\jasminelopez\AppData\Roaming\nvda

INFO - config.ConfigManager._loadConfig (09:21:24.121) - MainThread (6816):

Loading config: C:\Users\jasminelopez\AppData\Roaming\nvda\nvda.ini

INFO - core.main (09:21:25.103) - MainThread (6816):

Windows version: Windows 11 23H2 (10.0.22631) workstation AMD64

INFO - core.main (09:21:25.103) - MainThread (6816):

Using Python version 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]

INFO - core.main (09:21:25.103) - MainThread (6816):

Using comtypes version 1.1.11

INFO - core.main (09:21:25.103) - MainThread (6816):

Using configobj version 5.1.0 with validate version 1.0.1

INFO - NVDAHelperLocal (09:21:25.396) - MainThread (6816):

Thread 6816, build\x86\localWin10\oneCoreSpeech.cpp, ocSpeech_initialize, 215:

ocSpeech_initialize
 
INFO - NVDAHelperLocal (09:21:25.396) - MainThread (6816):

Thread 6816, build\x86\localWin10\oneCoreSpeech.cpp, OcSpeechState::activate, 89:

Activating
 
INFO - NVDAHelperLocal (09:21:25.509) - MainThread (6816):

Thread 6816, build\x86\localWin10\oneCoreSpeech.cpp, preventEndUtteranceSilence_, 443:

AppendedSilence supported
 
INFO - synthDriverHandler.setSynth (09:21:25.517) - MainThread (6816):

Loaded synthDriver oneCore

WARNING - mathPres.initialize (09:21:25.533) - MainThread (6816):

MathPlayer 4 not available

INFO - core.main (09:21:25.533) - MainThread (6816):

Using wx version 4.1.1 msw (phoenix) wxWidgets 3.1.5 with six version 1.16.0

INFO - brailleInput.initialize (09:21:25.535) - MainThread (6816):

Braille input initialized

INFO - braille.initialize (09:21:25.536) - MainThread (6816):

Using liblouis version 3.25.0

INFO - braille.initialize (09:21:25.536) - MainThread (6816):

Using pySerial version 3.5

INFO - braille.BrailleHandler._setDisplay (09:21:25.539) - MainThread (6816):

Loaded braille display driver 'noBraille', current display has 0 cells.

INFO - core.main (09:21:25.765) - MainThread (6816):

Java Access Bridge support initialized

INFO - UIAHandler.UIAHandler.MTAThreadFunc (09:21:25.856) - UIAHandler.UIAHandler.MTAThread (14724):

UIAutomation: IUIAutomation6

INFO - NVDAHelperLocal (09:21:26.156) - UIAHandler.UIAHandler.MTAThread (14724):

Thread 14724, build\x86\UIARemote\UIARemote.cpp, initialize, 145:

Registered C:\Program Files (x86)\NVDA\lib\2023.3.3\Microsoft.UI.UIAutomation.dll.manifest
 
INFO - NVDAHelperLocal (09:21:26.196) - UIAHandler.UIAHandler.MTAThread (14724):

Thread 14724, build\x86\UIARemote\UIARemote.cpp, initialize, 150:

Microsoft.UI.UIAutomation is available
 
INFO - core.main (09:21:26.263) - MainThread (6816):

NVDA initialized

ERROR - eventHandler.executeEvent (09:23:07.036) - MainThread (6816):

error executing event: caret on <NVDAObjects.Dynamic_ChromiumUIAEditableTextWithAutoSelectDetectionUIA object at 0x0E1C8310> with extra args of {}

Traceback (most recent call last):

  File "eventHandler.pyc", line 325, in executeEvent

  File "eventHandler.pyc", line 115, in __init__

  File "eventHandler.pyc", line 124, in next

  File "NVDAObjects\behaviors.pyc", line 306, in event_caret

  File "editableText.pyc", line 398, in detectPossibleSelectionChange

  File "editableText.pyc", line 407, in _updateSelectionAnchor

  File "NVDAObjects\UIA\__init__.pyc", line 942, in compareEndPoints

  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__

_ctypes.COMError: (-2146233079, None, (None, None, None, 0, None))

ERROR - stderr (09:23:07.297) - nvwave.playWaveFile(suggestionsClosed.wav) (51316):

Exception in thread nvwave.playWaveFile(suggestionsClosed.wav):

Traceback (most recent call last):

  File "threading.pyc", line 926, in _bootstrap_inner

  File "threading.pyc", line 870, in run

  File "nvwave.pyc", line 710, in play

AttributeError: 'NoneType' object has no attribute 'feed'

INFO - watchdog.waitForFreezeRecovery (09:23:11.788) - watchdog (29740):

Starting freeze recovery after 0.5011508000000049 seconds.

INFO - watchdog.waitForFreezeRecovery (09:23:11.912) - watchdog (29740):

Recovered from freeze after 0.6259324000000106 seconds.

ERROR - eventHandler.executeEvent (09:23:17.973) - MainThread (6816):

error executing event: mouseMove on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x010DBEB0> with extra args of {'x': 935, 'y': 536}

Traceback (most recent call last):

  File "eventHandler.pyc", line 325, in executeEvent

  File "eventHandler.pyc", line 115, in __init__

  File "eventHandler.pyc", line 124, in next

  File "NVDAObjects\__init__.pyc", line 1214, in event_mouseMove

  File "documentBase.pyc", line 74, in makeTextInfo

  File "textInfos\offsets.pyc", line 461, in __init__

  File "NVDAObjects\IAccessible\__init__.pyc", line 173, in _getOffsetFromPoint

  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__

_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))

ERROR - eventHandler.executeEvent (09:23:30.287) - MainThread (6816):

error executing event: mouseMove on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x055462F0> with extra args of {'x': 1094, 'y': 853}

Traceback (most recent call last):

  File "eventHandler.pyc", line 325, in executeEvent

  File "eventHandler.pyc", line 115, in __init__

  File "eventHandler.pyc", line 124, in next

  File "NVDAObjects\__init__.pyc", line 1214, in event_mouseMove

  File "documentBase.pyc", line 74, in makeTextInfo

  File "textInfos\offsets.pyc", line 461, in __init__

  File "NVDAObjects\IAccessible\__init__.pyc", line 173, in _getOffsetFromPoint

  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__

_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))

#### Name and version of other software in use when reproducing the issue: 
Microsoft Edge Canary
There was a related bug fix that went in recently, it's not in Canary at the time of filing this bug. 
Version: 123.0.2378.0 or greater.

**Comment by Adriani90** [comment]
Could you please try to reproduce the issue with eSpeak synthesizer? You can change it in the NVDA menu.

**Comment by seanbudd** [comment]
This is intended behaviour. Speech viewer captures all speech sent to the synthesizer, but cannot mirror exactly what NVDA outputs to audio. For example speech is cancelled in your case before it completes or starts.
