### ISSUE TITLE
Changing from Business to Home address in Outlook 2007 problem

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1611]
**Reported by dharvey on 2011-06-26 07:41**
Hi,

I'm wanting to add home address details to a contact in Outlook 2007, but only Business is shown and pressing the button to change it doesn't work.

Steps to reproduce:
1. Start Outlook then navigate to Contacts.
2. Backtab to the address area till you hear the word "Business".
3. Tab once to an unlabeled button. Under JAWS a menu comes up allowing you to change address IE Home, Business, etc.

Result: Does nothing when pressed.

Expected result: Should bring up a context menu presenting the options to change address to Home.

**Comment by ehollig** [comment]
Can anyone verify this in Outlook 2007? Otherwise, I would suggest worksforme as stated in https://github.com/nvaccess/nvda/issues/1611#issuecomment-155291170

**Comment by ehollig** [comment]
Closing as worksforme. If this is still an issue for someone, please create a new issue.
