### ISSUE TITLE
Rename option "Allow the NVDA Project to gather NVDA usage statistics" to "Allow NV Access to gather NVDA usage statistics"

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#16136]
### Is your feature request related to a problem? Please describe.

In the case of the General option: "Allow the NVDA Project to gather NVDA usage statistics" the usage statistics gather are sent directly (and only) to NV Access, and only NV Access has access to them directly from users.

With the option currently referencing "the NVDA Project", it may not be clear who these usage statistics get sent to.

### Describe the solution you'd like

Rename the option to "Allow NV Access to gather NVDA usage statistics".

### Additional context

**Comment by Nael-Sayegh** [comment]
Hello,
I will try to take care of it.
