### ISSUE TITLE
NVDA alpha: NVDA's volume increases as he speaks.

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#16149]
### Actual behavior:

- open the NVDA user manual,
- read the manual using "nvda + down arrow".
- the volume increases slowly.
- press shift twice, to pause and restart playback.
- the volume starts again normally and increases again.
- the same if reading is stopped by "control" then restart.

I use an E7 Stereo bluetooth headset.
This happens with NVDA version alpha-30989,39994073, regardless of the value of the "Duration in seconds of keeping audio device awake" option and Wasapi enabled or not.
This does not happen with nvda_snapshot_alpha-30972,9717b815.

### Expected behavior:

the volume should not change
#### NVDA installed/portable/running from source:
NVDA portable
#### NVDA version:
NVDA version alpha-30989,39994073, 
#### Windows version:
Windows 10 22H2 (10.0.19045) AMD64 workstation
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
E7 Stereo bluetooth headset.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, but no problem.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
No tested.

**Comment by CyrilleB79** [comment]
@paulber19, any explanation why you have closed this issue? Thanks.

**Comment by paulber19** [comment]
After deleting the nvda.ini and restarting NVDA, the problem disappeared.
I couldn't reproduce it again after that.

**Comment by CyrilleB79** [comment]
OK. Thanks for the explanation.
