### ISSUE TITLE
Currencies incorrectly read if a letter is positioned streight after

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1615]
**Reported by elliott94 on 2011-06-27 17:14**
Since the reading of currencies has recently been fixed, I thought it'd be useful to note another problem that can be experienced.

If a letter comes straight after a currency, it is incorrectly read. For example, £15.59 reads fine, but £15.21doesn't.

I'm unclear at this time if it can be fixed with a dictionary entry in combination with a regular expression, but if not I'm not really sure what can be done at the users end; I assume this will have to be changed code-side.

**Comment by ehollig** [comment]
I am experiencing the same results as @jcsteh in https://github.com/nvaccess/nvda/issues/1615#issuecomment-155291195 with no dictionary entries using the latest ESpeak NG. Closing
