### ISSUE TITLE
Play silence feature can be turned off

### ISSUE THREAD

**Issue by haruncetinkaya306** [nvaccess/nvda#16155]
### Is your feature request related to an issue? Please define.
The play silence feature that comes with the alpha-30989,39994073 build is useful, but not for users using wired devices.
### Describe your desired solution
A checkbox can be added to the sound panel to turn off this feature. Turning off this feature would be beneficial if it would also save battery.
### Describe the alternatives you considered
None.
### Additional context

**Comment by Adriani90** [comment]
As I explained in several issues already, this feature solves problems with audio output i.e. also in virtual environments or on systems with low performance. It doesn‘t affect only wireless stuff. You can turn this off in advanced settings.

**Comment by CyrilleB79** [comment]
As explained in the User Guide, setting the duration to 0 disables 
the feature.

There is a PR in progress to move the option to audio settings, what should allow people that are not interested in this feature to disable it.

Note however that the first benchmarks that have been made have not shown any significant impact on the laptop's battery duration.
