### ISSUE TITLE
Silent Uninstall

### ISSUE THREAD

**Issue by rrricky16** [nvaccess/nvda#16150]
### Is your feature request related to a problem? Please describe.
I'm trying to uninstall this program silently. I've tried using C:\Program Files (x86)\NVDA\uninstall.exe /S but that did not uninstall the program. 

### Describe the solution you'd like
Can you add an uninstall-silent command line option to NVDA? Similar to how you handle silent install: https://www.nvaccess.org/corporate-government/#deployment

### Describe alternatives you've considered
I've tried using USSF (https://www.capstanservices.com/tools-blog/2018/4/4/the-ultimate-silent-switch-finder-ussf) to find the uninstall switch but /S doesn't work.

### Additional context
I work in the IT department for a college. I've been asked to add NVDA to Microsoft Configuration Manager (formally known as SCCM) so we can deploy NVDA to a computer lab. I want to make sure we have a way of uninstalling NVDA from Configuration Manager if we need to.
![image](https://github.com/nvaccess/nvda/assets/34283700/56e48b2a-8601-4bb3-992d-b234c594a1b6)

**Comment by seanbudd** [comment]
My understanding is this process works, as per #14603

Can you confirm what happens when you run `C:\Program Files (x86)\NVDA\uninstall.exe /S` and provide any log file if possible

**Comment by seanbudd** [comment]
Running from an administrator command prompt `"C:\Program Files (x86)\NVDA\uninstall.exe" /S` works for me to silently uninstall
