### ISSUE TITLE
TextInfo in MSWord doesn't provide formatting information

### ISSUE THREAD

**Issue by mltony** [nvaccess/nvda#16171]
### Steps to reproduce:
1. Create a new MS Word document and type the following text:
```
This is a bold word.
```
2. Select the word "bold" and press `Control+B` to mark it bold. NVDA speaks "bold on".
3. Optionally verify by pressing `NVDA+F` that the word indeed turned bold.
4. Press `Home` to move the cursor to the very beginning of the document.
5. Press `NVDA+space` to enter browse mode.
6. Open NVDA Python Console by pressing `NVDA+control+z` and type:
```
>>> t = focus.treeInterceptor.makeTextInfo('caret')
>>> t.expand('paragraph')
>>> ff = t.getTextWithFields()
>>> ff[5]
'bold '
>>> ff[4]
FieldCommand formatChange with {'language': 'en_US', 'page-number': '1'}
```

### Actual behavior:

As can be seen in python output, `formatChange` command immediately preceding the word "bold" doesn't contain any information suggesting that the text is actually bold.
### Expected behavior:

`TextInfo.getTextWithFields()` should return correct formatting information. In particular, `ff[4]` should contain `dict` entry `'bold': True,` among others.
### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
Running from dist.
#### NVDA version:
master
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
MSWord 16.0.17029.20140
This issue reproduces with both UIA enabled and disabled. When UIA disabled indices in `ff` are going to be different, but the problem is the same: `formatChange` field immediately preceding the word "bold" doesn't contain `'bold': True` entry - as well as all other formatting information seems to be missing.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by CyrilleB79** [comment]
1. Is it with UIA, without it, or with both options?
2. Could you explicitly indicate in "Expected result" what you expect in the console when entering `ff[4]`?

**Comment by CyrilleB79** [comment]
You should probably call `getTextWithFields` with a specific `formatConfig` argument (not `None`) to get the appropriate formatting.

When enabling "Attributes" reporting in document formatting settings, "bold" is correctly reported. So `getTextWithFields` is probably able to report it in some way; try this piece of code with this use case to understand how.

**Comment by mltony** [comment]
You're right, my bad, didn't notice that argument. Closing as this is not a bug.
