### ISSUE TITLE
speach mode on-demand stops working when "NVDA + B" key is pressed.

### ISSUE THREAD

**Issue by gauravahir28** [nvaccess/nvda#16186]
### Steps to reproduce:
- set the speach mode to "on-demand" using "NVDA +S" key.
- observe that the speach on-demand mode is working correctly.
- Now, press "NVDA + B" key.
- NVDA starts reading all  controls of the active window.
- Now, press any key, NVDA works as the speach mode "Talk" is selected.
- this is even applicable if user again cycle through the speach modes and again select "on-demand" mode.
### Actual behavior:

the "speach on-demand" mode works similar to "talk" mode of speach.
### Expected behavior:

the Speach on-demand mode should work as described in the documentation.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
NVDA 2024.1 Beta 7
#### Windows version:
Windows 11 23H2
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not applicable as this is introduced in 2024.1
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment]
Would you be able to provide a debug log with add-on disabled reproducing this issue?

On my side, I have reproduced this issue, but only with add-ons enabled. More specifically, I had tracked down the issue to be caused by "Speech history Explorer" add-on.

**Comment by CyrilleB79** [comment]
Cc @davidacm and @jscholes for information.

Notes:
* I have only tested Speech History Explorer, not the original Speech History from @jscholes.
* I have not investigated the cause of this issue in the add-on
