### ISSUE TITLE
On outlook express. Strange window gets focus.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1618]
**Reported by briang1 on 2011-06-28 08:01**
This is very trivial, but thought I'd ticket it for ref. I remember mentioning it on list so I thought  this was appropriate. 
When sending an email where significant parts were pasted, say from Word, you often get the  character set conflict message when sending. It gives a choice of sending as unicode, which uses base64 coding to send the hi ascii etc, or as is which will probably break some of the content. No matter which you choose this window gets focus and either has no output or what sounds like gibberish. You need to use alt/tab to get back , but when you try to come back its gone. Was it really there?

Here is the tiny bit of log and the developer info for the window when it appears. 
IO - speech.speak (08:47:40):
Speaking [Character Set Conflict  dialog  This message contains some text having a character set other than the default character set. When sending this message you have the following options: The message will be sent as a Unicode message. All character set information will be retained. However, if the recipient's e-mail reader does not support Unicode, the message may not be display correctly. The message will be sent as a regular e-mail message using only the default character set. Any text not in the default character set may be unreadable by the recipient. Return to editing the message. "](u"Message)
IO - speech.speak (08:47:40):
Speaking [As Unicode  button  Alt+u'](u'Send)
IO - inputCore.InputManager.executeGesture (08:47:51):
Input: kb(desktop):rightArrow
IO - inputCore.InputManager.executeGesture (08:47:51):
Input: kb(desktop):leftArrow
IO - inputCore.InputManager.executeGesture (08:47:52):
Input: kb(desktop):tab
IO - speech.speak (08:47:52):
Speaking [As Is  button  Alt+s'](u'Send)
IO - inputCore.InputManager.executeGesture (08:47:54):
Input: kb(desktop):enter
IO - speech.speak (08:47:54):
Speaking [u'O\u016d0']
IO - inputCore.InputManager.executeGesture (08:48:13):
Input: kb(desktop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (08:48:13):
Developer info for navigator object:
name: u'O'
role: ROLE_UNKNOWN
states: STATE_INVISIBLE, STATE_FOCUSABLE, STATE_FOCUSED
Python object: <NVDAObjects.IAccessible.ContentGenericClient object at 0x01E11B30>
Python class mro: (<class 'NVDAObjects.IAccessible.ContentGenericClient'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (0, 0, 0, 0)
value: ''
appModule: <'msimn' (appName u'msimn', process ID 1492) at address 1c97750>
TextInfo: <class 'displayModel.DisplayModelTextInfo'>
windowHandle: 1048786
windowClassName: u'OutlookExpressHiddenWindow'
windowControlID: 0
windowStyle: -2080374784
windowThreadID: 3096
windowText: u'O'
IAccessibleObject: <POINTER(IAccessible) ptr=0x1e0910 at 3d19da0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=1048786, objectID=-4, childID=0
IAccessible accRole: ROLE_SYSTEM_CLIENT
IAccessible accState: STATE_SYSTEM_INVISIBLE, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1081348)

**Comment by ehollig** [comment]
I believe OE bugs are no longer being fixed. @jcsteh also says this may not be an NVDA issue
