### ISSUE TITLE
Firefox menus activate but are invisible in full screen mode

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1619]
**Reported by Palacee_hun on 2011-06-28 16:35**
To reproduce this:
1. In any FF 3.6 document window switch to fullscreen mode by hitting F11 or from View menu. This works immediately. If you have no sight, you can check whether fullscreen mode is on by querying the status bar (NVDA+End) or by trying to invoke menus by Alt+letter combinations (e.g. Alt+f goes to file menu). In fullscreen mode neither succeeds, while in normal mode both does obviously.
2. Try to go back to normal mode by pressing F11. Then perform the check described above. You will find that FF is still in fullscreen mode. It seems you can repeat pressing F11 as many times as you like, FF won't switch back to normal mode.
3. Unload NVDA while still in the FF document window. Now press F11. Relaunch NVDA, then check for fullscreen mode. Alas, you'll find that normal mode returned as it should! This step proves that this issue has got something to do with NVDA, not just with FF.

FF 4 and 5 and IE may exhibit the same behaviour with NVDA, I couldn't test them. This issue seems to be reproducible Both with NVDA 2011.1.1 and 2011.2 beta1. It doesn't seem to matter which version you use in the FF 3.6 series, all seem to work the same in this aspect. 

This issue has significance because some irregular or badly programmed web content can only be interacted with object navigation and/or mouse routing (NVDA+/) and they sometimes can only be clicked on when in fullscreen mode (otherwise mouse pointer wouldn't be routed to them correctly). However in fullscreen mode you can't use the menu shortcuts and other FF keyboard shortcuts and you can't query the status bar, so you'd want to switch back to normal mode as soon as fullscreen mode is not needed.

**Comment by bhavyashah** [comment]
@jcsteh Could you please mention the URL of MozillaBug:648504 that you had filed? Googling 'MozillaBug:648504' leads me only to this NVDA Github ticket thus preventing me and possibly others from tracking the progress of this issue on the Firefox tracker.

**Comment by ehollig** [comment]
The URL is [MozillaBug:648504](https://bugzilla.mozilla.org/show_bug.cgi?id=648504). The issue is still new and appears to not have any activity in the past year.

**Comment by jcsteh** [comment]
This was fixed in [Mozilla bug 1192655](https://bugzilla.mozilla.org/show_bug.cgi?id=1192655). Now, it's no longer possible to activate menus in full screen mode at all, which means that f11 will always work to switch off full screen. Bug 648504 is still open because some users want the menus to work even in full screen mode. However, the original concern discussed here (the confusion of f11 not working) is fixed, so I'm closing this.
