### ISSUE TITLE
Native selection in MS Word: NVDA reports "native copy"

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#16201]
### Steps to reproduce:
1. Open an empty MS Word document
2. With NVDA running, type "hello"
3. Switch to browse mode
4. Select one character (e.g. h) and press ctrl+c
5. Select more than one character (e.g. hello) and press ctrl+c

### Actual behavior:
IN step 4, NVDA reports the NVDA specific message "native copy".
In step 5, NVDA reports part of NVDA specific copy message and the full copy message retrieved by the MS Word app module "na... copy"
Users get confused because they might get the impression that the copied content in browse mode is different than the one in focus mode. So this is a regression.

### Expected behavior:
NVDA should report the copy message retrieved by the app module in browse mode, as it was before impelemnting native copy and same as it does in focus mode, because the same content is copied both in browse and focus mode.

### NVDA logs, crash dumps and other attachments:
n/a

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
alpha-31113,6a43521f (2024.2.0.31113)

#### Windows version:
Windows 11 23 H2

#### Name and version of other software in use when reproducing the issue:
Microsoft 365 MSO (Version 2401 Build 16.0.17231.20236) 64 Bit

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
, 2024.1 Beta has the same issue.

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
cc: @michaelDCurran

**Comment by Adriani90** [comment]
I vote for going the same way we do in MS Excel where in browse mode everything behaves as there was no native selection mode at all.

**Comment by michaelDCurran** [comment]
I don't understand your steps. I do not see any step where you press `control+c` to copy.
Also, what is the copy message you are talking about in focus mode? do you mean that UIA notification that MS Word sends where it says "copy" when you press control+c? If so, there is specific code to filter that out. Are you saying that this is not working?
Please attach a log set to input/output, showing the exact steps being performed and the speech output.

**Comment by Adriani90** [comment]
@michaelDCurran sorry forgot to include ctrl+c in step 4 and 5, _'ve edited_ accordingly.
> Also, what is the copy message you are talking about in focus mode? do you mean that UIA notification that MS Word sends where it says "copy" when you press control+c? If so, there is specific code to filter that out. Are you saying that this is not working?

yes that's what I mean, probably this is also sent via the object model. I have UIA set to "only when necessary". This is not working in browse mode, when only one character is selected.
When more than one character is selected, pressing ctrl+c reports the message sent by MS Word but you will notice NVDA starts to report "native copy" and is interupted by the "copy" message sent by MS word.
I attached the log as requested.

[nvda_native-copy-ms-word.txt](https://github.com/nvaccess/nvda/files/14350654/nvda_native-copy-ms-word.txt)

**Comment by CyrilleB79** [comment]
Note: I have commented on this issue in #16202 (see https://github.com/nvaccess/nvda/issues/16202#issuecomment-1955233554) since both issues are related.

**Comment by CyrilleB79** [comment]
Note: I have commented on this issue in #16202 (see https://github.com/nvaccess/nvda/issues/16202#issuecomment-1955233554) since both issues are related.

**Comment by michaelDCurran** [comment]
I agree that it is unclean to have the two copy messages interrupting each other.
I  will be opening a pr to remove the "native copy" message completely from native selection mode, and ensure that  the copy message in MS word with UIA is again no longer suppressed. 
 
> Users get confused because they might get the impression that the copied content in browse mode is different than the one in focus mode. So this is a regression.

this is not a regression, rather it is a change in behavior. If you feel there is a contradiction with the user guide, please suggest a change to the documentation to make it clearer.
 
> NVDA should report the "copy" message retrieved by the Outlook app module in browse mode, as it was before implementing native copy and same as it does in focus mode, because the same content is copied both in browse and focus mode.

I completely disagree. The change in behaviour is now that it copies like focus mode, thus it should not (nor can it) report the original message about copying in browse mode.

The behaviour will stay as is for 2024.1. But Feel free to suggest clarifications to documentation if necessary.
However, if there is in deed a regression or loss of behaviour (excluding a change in the message) then please state this more clearly.
