### ISSUE TITLE
Narrate row position in the grid, while user navigates "row by row"

### ISSUE THREAD

**Issue by kolaps33** [nvaccess/nvda#16211]
### Is your feature request related to a problem? Please describe.
Across the Microsoft products, like for example MS Onedrive, MS Teams is used grid where user can navigates row by row.
Please see simple codesandbox example:
https://4hdw6h.csb.app/ 

When user navigate in the grid by pressing up/down arrow key, then it navigates "row by row". 
It would be great and really useful if user know the position of the row in the table.  
Please see enclosed video what is meant by "row by row" navigation:
https://github.com/nvaccess/nvda/assets/22620150/65cb7612-2206-4434-9edb-fd15f1ab3bc1

### Describe the solution you'd like
Narrate the position of the row in the grid, similarly like when user navigates through the grid cell by cell.
Current narration is:
"accessible name" row

Proposing narration:
"accessible name" row 1
"accessible name" row 2
"accessible name" row 3

### Additional context
Currently the NVDA narrates the position for the row in the treegrid
https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/examples/treegrid-1/
so would be nice to have this narration as well for the grid.

**Comment by Adriani90** [comment]
In which browser do you see this issue? have you enabled reporting of "tables" in NVDA document formating settings?

**Comment by Adriani90** [comment]
I think this is web authoring error here. You seem to redirect the focus out of the grid when pressing up and down arrow, probably at a position right left of the checkbox to select the row. This triggers NVDA to read the whole row at once.
For this to work properly, you should maintain the vertical position of the focus in the same coluumn when pressing up and down arrow, and not redirect it to the checkbox to the left.
This works as expected in grid like here for example:
https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/data-grids/

**Comment by Adriani90** [comment]
Closing as invalid. Please comment here if I understood something wrong and we can reopen.

**Comment by kolaps33** [comment]
@Adriani90 

The focus the row in the grid is by purpose, this is not mistake. 

This is similar navigation pattern as is used in treegrid APG example:  https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/examples/treegrid-1/

But this case we use the "grid" role (not treegrid).

This navigation pattern when focus goes to the row is used as well
in the microsoft onedrive:
![image](https://github.com/nvaccess/nvda/assets/22620150/5a9156a2-7cd8-4337-bd26-2676c82a24ea)

or in the google drive:
![image](https://github.com/nvaccess/nvda/assets/22620150/0f81dda0-1795-4b6d-a2a1-3bdd59a2ba61)

**Comment by kolaps33** [comment]
as I am not able to reopen this ticket (I am missing such option), therefore created the new one:
https://github.com/nvaccess/nvda/issues/16227
