### ISSUE TITLE
Add .NET desktop build tools to Visual Studio dependencies

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#16217]
### Steps to reproduce:
1. Install either Visual Studio 2022 Community or the Visual Studio Build Tools. Select only the components listed in NVDA's [official guide](https://github.com/nvaccess/nvda/blob/master/projectDocs/dev/createDevEnvironment.md).
2. Get the NVDA sources and submodules.
3. Run `scons source`.

### Actual behavior:
MSBuild starts working on microsoft-ui-uiautomation and fails to restore its dependency packages. This is because it fails to fetch from NuGet, because it can't find Newtonsoft.Json.

### Expected behavior:
Required packages should be fetched from NuGet.

I found that this can be resolved by adding the workload '.NET desktop build tools' to the Visual Studio installation (ID: 'Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools'). I suggest that this is added to the developer guide and also to the .vsconfig file.

**Comment by lukaszgo1** [comment]
Note that the dependence on the UIA Remote library will be removed as part of #16214

**Comment by dkager** [comment]
Good point. When we know when that PR will land in a release we can decide if updating the developer guide is necessary. The requirement to add .NET tools to build NVDA seems counter-intuitive anyway.

**Comment by Adriani90** [comment]
@dkager does your last comment mean #16214 will close this issue?

**Comment by dkager** [comment]
> @dkager does your last comment mean #16214 will close this issue?

Yes, assuming that no other Visual Studio projects that rely on NuGet packages are included as submodules. I'm pretty sure the Microsoft UIA submodule is the only one.

**Comment by michaelDCurran** [comment]
As #16214 is now merged, I'm closing this as fixed.
