### ISSUE TITLE
Narrate row position in the grid, while user navigates "row by row" #16211

### ISSUE THREAD

**Issue by kolaps33** [nvaccess/nvda#16227]
Creating this issue as follow up of the:
https://github.com/nvaccess/nvda/issues/16211
Because 16211 I was not able to re-open. Unfortunately, I have no such option. 

### Is your feature request related to a problem? Please describe.
Across the Microsoft products, like for example MS Onedrive, MS Teams is used grid where user can navigates row by row.
Please see simple codesandbox example:
https://8p94v6.csb.app/

When user navigate in the grid by pressing up/down arrow key, then it navigates "row by row". 
It would be great and really useful if user know the position of the row in the table.  
Please see enclosed video what is meant by "row by row" navigation:
https://github.com/nvaccess/nvda/assets/22620150/65cb7612-2206-4434-9edb-fd15f1ab3bc1

### Describe the solution you'd like
Narrate the position of the row in the grid, similarly like when user navigates through the grid cell by cell.
Current narration is:
"accessible name" row

Proposing narration:
"accessible name" row 1
"accessible name" row 2
"accessible name" row 3

### Additional context
Currently the NVDA narrates the position for the row in the treegrid
https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/examples/treegrid-1/
so would be nice to have this narration as well for the grid. 

The focus the row in the grid is by purpose, this is not mistake. 

This is similar navigation pattern as is used in treegrid APG example:  https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/examples/treegrid-1/

But this case we use the "grid" role (not treegrid).

This navigation pattern when focus goes to the row is used as well
in the microsoft onedrive:
![image](https://github.com/nvaccess/nvda/assets/22620150/5a9156a2-7cd8-4337-bd26-2676c82a24ea)

or in the google drive:
![image](https://github.com/nvaccess/nvda/assets/22620150/0f81dda0-1795-4b6d-a2a1-3bdd59a2ba61)

**Comment by Adriani90** [comment]
Thanks for the detailed description, I am ccing also  @jcsteh for further investigation on this since it affects also Firefox.
For whatever reason NVDA reads the whole row when arrowing up and down, and not the current cell only. So I think NVDA does not get the exact cell coordinates.

**Comment by kolaps33** [comment]
@Adriani90 
the narration of the row by NVDA is correct and expected. 
Because in our custom keyboard navigation we implemented the focus goes on the "row" element. 

Only what I we would need to get from NVDA to narrate the position of the row. :)

**Comment by kolaps33** [comment]
Adding the screenshot which demonstrate that "document.activeElement" is the row of the table.

The focused element is the row and it is done by purpose, implemented by our custom keyboard navigation/handling.

![image](https://github.com/nvaccess/nvda/assets/22620150/93c41d6e-7d24-449a-bb5f-01686a20fc22)

**Comment by seanbudd** [comment]
Welcome @kolaps33 ,

We are unable to process this issue as it stands.

- This appears to be a bug report. Please fill out the BUG REPORT issue template fully. It is unclear what browsers, versions of NVDA, and system version you have. Log files are also missing.
- The example you provided appears to read the row position information correctly in Firefox but not Chrome. Can you please confirm.
- Many developers, contributors and community members here are vision impaired. Screenshots are not accessible. Provide an alternative description, and capture any relevant information from images. As requested in the bug template, please copy relevant actual and expected speech from speech viewer. 
- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Kind Regards,
NV Access Software Developers

**Comment by kolaps33** [comment]
@seanbudd, @Adriani90 , @jcsteh  

Hi Sean, 
thank you for the last comment, it was super useful. 

I created the bug for chromium:
[Not exposing information about row count for grid for screen reader
](https://issues.chromium.org/issues/328298017)
