### ISSUE TITLE
on microsoft edge, it is impossible to activate items on the history window while in focus mode

### ISSUE THREAD

**Issue by fatihyuksek1** [nvaccess/nvda#16228]
### Steps to reproduce:
1. Open Microsoft Edge
2. Press ctrl+h to open the history
3. Press NVDA+space to switch to focus mode
4. Press up and down arrows to see the history
5. Press enter on a site to try to access it
6. You will see that nothing happens
### Actual behavior:

Nothing happens when pressing enter on a history item while in focus mode
### Expected behavior:

The site that is on focus should be activated while on focus mode by pressing enter.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.3.3
#### Windows version:
Windows 11 latest build
#### Name and version of other software in use when reproducing the issue:
Microsoft Edge latest version
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, they behaved the same way
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
Is UIA for Edge / Chromium enabled or disabled in your NVDA advanced settings?

**Comment by fatihyuksek1** [comment]
It is set at "only when necessary", which is the default value.

**Comment by seanbudd** [comment]
>Microsoft Edge latest version

Please ALWAYS report the version of the browser you are reproducing this with.
I cannot reproduce this on 122.0.2365.52.

However, we can reproduce this on 123. 
This means Microsoft broke this, you will have to report it to Microsoft.

**Comment by fatihyuksek1** [comment]
FYI my edge version is 122.0.2365.52.
If you say I should report this to Microsoft because microsoft broke this, then according to this mentality, we shouldn't report bugs with apps because the developer broke them.
Why does this system exist if we aren't going to report anything by third prty developers anyway? What a rediculous attitude in my opinion. This bug hasn't started now anyway, it was there a very, very long time ago.
I'm an ordinary user, wanting to report what I go through. If I'm not supposed to report any bug that is from third party apps, then what's there to report, for god's sake?
And how can I report this bug to microsoft, will they even care if I report this from the feedback centre?
Thank you for answering or not answering, I don't care, you can even close this issue for whatever reason that you see fit, I don't care about htat either.
Good luck on development.

**Comment by seanbudd** [comment]
@fatihyuksek1 - please adhere to the NVDA code of conduct

https://github.com/nvaccess/nvda/blob/master/CODE_OF_CONDUCT.md

**Comment by Adriani90** [comment]
Indeed I tested now with NvDA 2024.1 Beta 10 under Edge 122 I cannot reproduce.
When you press enter, the website is opening and nVDA announces that the new page has been loaded. Though the page opens in a separate tab and the focus needs to be moved manually there with ctrl+tab.
This is expected because the history pannel is a tab itself and the website saved there is actually a tab.

**Comment by Adriani90** [comment]
In browse mode though, NVDA simulates a mouse click event and probably closes the history pannel which automatically brings the focus to the newly opened website.
