### ISSUE TITLE
2024.1. Audio ducking mode is missing from audio panle

### ISSUE THREAD

**Issue by amirmahdifard** [nvaccess/nvda#16231]
i have a problem. In the changelog you've mentioned, audio output device and audio ducking mode have been removed from the select sinthesizer dialog. They can be found in audio pannle. But, i can't find audio ducking mode in there. Why?

**Comment by OzancanKaratas** [comment]
This option appears only when NVDA is installed. Portable usage environments does not support audio ducking.

**Comment by amirmahdifard** [comment]
yeah, i was about to say that. Thanks
