### ISSUE TITLE
When using Thunderbird 5.0 it is difficult to hear information being read when sending an email message to more than one recipient

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1623]
**Reported by dgoldfield on 2011-06-29 15:30**
When using Thunderbird 5.0 to send an email message to more than one recipient it is necessary to use the alt-down arrow key to move to an edit field to type in the name/address of the additional contact.  In TB 3.1 NVDA read this field properly and you could review what you wrote with the arrow keys.  If the contact is in your address book NVDA read the autocomplete information as you typed the name.  With TB 5.0 pressing alt-down arrow gives the prompt "row 2 of 4."  Autocomplete information is not read if you type a contact who is in your address book, but if you move focus away from and then back to the window you can properly review the contact with arrow keys.

**Comment by ehollig** [comment]
Sounds like this has been fixed from [MozillaBug:673860](https://bugzilla.mozilla.org/show_bug.cgi?id=673860)
