### ISSUE TITLE
OBS not reading with 2024.1beta10

### ISSUE THREAD

**Issue by jessieppp** [nvaccess/nvda#16250]
### Steps to reproduce:
1. download open broadcaster software if not installed.
2. 2. when installed go in to the open broadcaster software and you will notice that nothing reads and also the control key doesn't work to stop screen reader from speaking.
### Actual behavior:

nothing happens can't even use software.
### Expected behavior:

was expecting to be able to use the open broadcaster software to use it.
#### NVDA version:
nvda 2024.1 beta 10
#### Windows version:
windows 23 h2
#### Name and version of other software in use when reproducing the issue:
o b s 30.0.2
#### Does the issue still occur after restarting your computer?
yes it does issue is still present.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
it works with stable version of nvda.
#### If NVDA add-ons are disabled, is your problem still occurring?
n/a
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes it does.

**Comment by lukaszgo1** [comment]
You haven't mentioned if you are using the beta version as installed or portable. The described behavior often occurs with portable versions with applications running as administrator.

**Comment by jessieppp** [comment]
Sorry about that, I am using the beta of NVDA, as a portable version. I don't think I have OBS running as administrator. But I will check.

**Comment by seanbudd** [comment]
Closing - after googling it seems likely that you have set OBS to run as administrator as this often recommended. I am happy to reopen if you can confirm that this is still an issue when not running as admin, or using an installed copy of 2024.1
