### ISSUE TITLE
IE8 and FF7: should recognize the datalist item as an edit combo because you can type text, or use UP or DOWN ARROW to move to the list box and change values.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1627]
**Reported by kevinchao89 on 2011-06-29 20:14**
Internet Explorer 8, Firefox 7.0a1 (2011-06-29), NVDA Snapshot 4511.
1. Open IE9 or Firefox and move to the following page:
   http://www.w3schools.com/html5/tryit.asp?filename=tryhtml5_datalist
2. Press the letter M until you find the view frame. This frame has a datalist with three values, BMW, Ford and Volvo. 
   Expected: NVDA to speak that it 's a view frame and summary of how many datalist are within frame. 
   Actual: NVDA speaks "Edit, has autocomplete" 
3. Find the edit box and press ENTER to activate focus mode.
   Expected: NVDA to speak that it's an edit combobox
   Actual: NVDA speaks box as if it were a standard edit box, but it's possible to UP/DOWN ARROW.

**Comment by bhavyashah** [comment]
@jcsteh As you expressed in https://github.com/nvaccess/nvda/issues/1627#issuecomment-155291302, you were going to test this issue in IE 9 and revert. This is a friendly reminder to do that, and accordingly triage this ticket. CC @ehollig for testing and triaging also

**Comment by ehollig** [comment]
The URL for this has changed. I believe it is now:
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_elem_datalist
Note: The datalist tag is not supported in Safari or IE9 (and earlier)

**Comment by jcsteh** [comment]
Confirmed that datalist isn't supported for IE 8 or IE 9. Since everything works as expected in Firefox and this isn't supported by IE 8 or IE 9 (so not handling it is expected), closing as works for me.
