### ISSUE TITLE
2024.1 beta12. Introduced a new bug regarding the gui change states

### ISSUE THREAD

**Issue by HanaDadfar** [nvaccess/nvda#16280]
today i've installed the beta 12, and noticed something, i'll just explane what i do and what happens, i don't have any idea why this happens.
### Steps to reproduce:
1: from the read only edit box or the change button, open the Select Synthesizer  dialog
2: change your synth from the combo box or just leave it as it is, just press ok button, not the cancel button.
### Actual behavior:
nvda speecks like this.
NVDA Settings: Speech (normal configuration)  dialog
Speech  property page
Synthesizer  grouping
Modes available in the Cycle speech mode command: list alt+m off check box checked.
But when I press tab or shift tab, it jumps back to the synth grouping again, and swiches between the box and the change button.
### Expected behavior:
nvda should speeck like this.
NVDA Settings: Speech (normal configuration)  dialog
Speech  property page
Synthesizer  grouping
edit  read only  multi line  eSpeak NG
or
Change... button alt+h
depending on your focuse.
and work as normal
#### NVDA installed/portable/running from source:
portable/installed
#### NVDA version:
2024.1 beta 12
#### Windows version:
Windows 10 enterprise 22H2 (AMD64) build 19045.4123
#### Name and version of other software in use when reproducing the issue:
non
#### Other information about your system:
non
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
older versions works fine, probably this issue has been introduced because of wx python update.
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by CyrilleB79** [comment]
Yes.
Reproduced on my side both on beta12 and beta4. Thus, the last WxPython upgrade is not the cause of this; I cannot tell for the first WxPython upgrade during 2024.1 dev cycle.

NVDA 2023.3.4 works fine. But it's worth nothing that the checkable list was not present in this dialog for this version of NVDA.

**Comment by CyrilleB79** [comment]
Cc @seanbudd

**Comment by lukaszgo1** [comment]
@HanaDadfar  Thanks for your report. I'm looking into this.

**Comment by HanaDadfar** [comment]
@lukaszgo1 thanks for your investigations. I tryed to take this my self to not bother other nvda developers/staff members as now i'm also a contributor of nvda too, but sadly i don't know what is the cause of this problem, I couldn't find any solootion to fix this in the code, So thanks for your investigations, And be sure that i see your benefits, and your trys.
