### ISSUE TITLE
Screen reader announcing text/date columns or cells as clickable in lightning datatable lwc salesforce

### ISSUE THREAD

**Issue by abhiabhinav98** [nvaccess/nvda#16294]
### Steps to reproduce:
1. Create a lightning-datatable inside lwc and load it with some data rendering from backend and formatted columns with url, text, and date types in them

### Actual behavior:
When the speech viewers enter into the datatable, while traversing the cells of the table with text or date values, it announces the column or cell as clickable. 
![image](https://github.com/nvaccess/nvda/assets/37726374/3b675f31-89a4-44d7-b275-70598a7ef99a)

### Expected behavior:
When the speech viewers enter into the datatable, while traversing the cells of the table with text or date values, it shouldn't announce the column or cell as clickable. 

#### NVDA version:
2023.3.3

#### Windows version:
Windows 22H2

#### Name and version of other software in use when reproducing the issue:
Google Chrome 122.0.6261.112
Webapp - Salesforce

#### Other information about your system:
Windows 10 22H2

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NA

#### If NVDA add-ons are disabled, is your problem still occurring?
NO Add-Ons

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
NA

**Comment by Adriani90** [comment]
Please don't copy screenshots into the issue descriptions, here are a lot of blind developers and screenshots are not accessible. Next time please copy the text output from the NVDA speech viewer and paste it here.

Do you have a minimal test case in a codepen or jsfiddle to investigate this issue further? Otherwise it is not really possible to give any advise.

**Comment by seanbudd** [comment]
Welcome @abhiabhinav98 ,

We are unable to process this issue as it stands.

- Many developers, contributors and community members here are vision impaired. Screenshots are not accessible. Provide an alternative description, and capture any relevant information from images.
- To be able to reproduce this issue, we need a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).
- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.
- This is very likely a problem with the implementation of the application/website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers
