### ISSUE TITLE
Use the new file installTasks.py when updating an add-on

### ISSUE THREAD

**Issue by Nael-Sayegh** [nvaccess/nvda#16309]
### Steps to reproduce:
* Install an add-on that contains an installTasks.py file
* Modify the installTasks.py file of your add-on and reinstall it without uninstalling the first one

### Actual behavior:

Currently, during the add-on update, the installTasks.py file executed is that of the already installed version and not that of the add-on being installed.

### Expected behavior:

The new installTasks.py file from the add-on being installed should be used instead of the old one already installed.

### NVDA logs, crash dumps and other attachments:
None

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
NVDA 2023.3.4

#### Windows version:
windows 11

#### Name and version of other software in use when reproducing the issue:
None

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I have tested with from NVDA 2022.4

**Comment by lukaszgo1** [comment]
This should be fixed by #15967 @Nael-Sayegh Would you be able to verify if this no longer occurs in Alpha for you?

**Comment by Nael-Sayegh** [comment]
Hello @lukaszgo1 ,
I am going to test this alpha and I will come back to you to keep you posted.

**Comment by Nael-Sayegh** [comment]
@lukaszgo1  I tested #15967 , and the problem is solved, I had not thought to test it before opening this issue.
Thank you and I am closing this issue.
