### ISSUE TITLE
NVDA-2024.1 enhancements to Poedit do not work

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#16318]
cc @LeonarddeR 
### Steps to reproduce:
1. Open a po file in Poedit3, such as NVDA’s latest interface translation.
2. Select an item in the list, for example: "Native input"
3. Try the following gestures:
  - Ctrl+Shift+C
  - Ctrl+Shift+O
  - Ctrl+Shift+W
  - Ctrl+Shift+A
### Actual behavior:
NVDA reports:
  - No comment
  - 翻译者注释
  - No translation warning
  - No notes for translators

### Expected behavior:
At least translator notes should be reported:
‪Translators: A mode  that allows typing in the 
‪actual 'native' characters for an east-Asian input 
‪method language currently selected, rather than 
‪alpha numeric (Roman/English) characters.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA2024.1, 2024.2 Alpha
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.4170
#### Name and version of other software in use when reproducing the issue:
Poedit Free 3.4.2 (6902)
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
n/a

**Comment by cary-rowen** [comment]
I haven't debugged the Poedit app module code yet.
However, Ctrl+Shift+O seems to located the wrong object.

**Comment by LeonarddeR** [comment]
Is this the paid or the free version of poedit?

**Comment by cary-rowen** [comment]
Hi @LeonarddeR 
Poedit Free 3.4.2 (6902)

**Comment by LeonarddeR** [comment]
I can not reproduce this with the Dutch translation of NVDA, at least the notes for translators are properly read.
However, note that you need to have the side bar enabled for notes for translators to get reported. Have you enabled that in the view menu?

**Comment by hwf1324** [comment]
> I can not reproduce this with the Dutch translation of NVDA, at least the notes for translators are properly read. However, note that you need to have the side bar enabled for notes for translators to get reported. Have you enabled that in the view menu?

Currently in my case `OLD_SOURCE_TEXT` should be `66` to report the contents of Notes for translators correctly, otherwise it just reports "Notes for translators".

Poedit
Free version (please upgrade!)
Version 3.4.2 (6902)

**Comment by LeonarddeR** [comment]
> Currently in my case `OLD_SOURCE_TEXT` should be `66` to report the contents of Notes for translators correctly.

Old source text should not report notes for translators at all.
It looks like Poedit just behaves differently on some systems.

**Comment by cary-rowen** [comment]
Does this mean it is a specific problem in the Chinese language?

**Comment by hwf1324** [comment]
> Does this mean it is a specific problem in the Chinese language?

Not sure, because I set Poedit's display language to English and still have this problem. But the system voice is Chinese.

**Comment by cary-rowen** [comment]
> Currently in my case  OLD_SOURCE_TEXT  should be  66  to report the contents of Notes for translators correctly, otherwise it just reports "Notes for translators".

Yes, for me only setting TRANSLATOR NOTES to 66 correctly reports translator notes when pressing Ctrl+Shift+A.

**Comment by LeonarddeR** [comment]
I can actually reproduce this now when opening the zh_CN translation. I'm not sure what causes this though, need to dive into that and I don't have much time currently.

**Comment by CyrilleB79** [comment]
@LeonarddeR, I suspect the number of plurals of the used language to cause unwanted offsets in the object id's.

I have done some tests. The shortcuts seem to work for languages es, fr, it, nl that are all languages with 2 plural forms. It does not work for zh_CN (which has only one plural form) and Slavic languages such as ru, sk, sl, sr which have more than 2 plural forms.

I am not sure to investigate further on this topic for now; just mentioning my ideas in case it can be useful.

**Comment by josephsl** [comment]
Hi, Korean (ko) also has one plural form, and when I press Control+Shift+A for translator comments in Poedit, NVDA reports no translator notes. Thanks.

**Comment by LeonarddeR** [comment]
@seanbudd I leave it up to you whether or not to revert https://github.com/nvaccess/nvda/pull/15313 before the release.

**Comment by cary-rowen** [comment]
Would rather see a patch for 2024.2.

**Comment by cary-rowen** [comment]
Is there any hope that this will be resolved in 2024.2? Is it necessary to move to other milestones?

**Comment by LeonarddeR** [comment]
I find it very complicated to do something with this, because I'm afraid that by fixing one problem I will cause another.

**Comment by LeonarddeR** [comment]
I created https://github.com/vslavik/poedit/issues/845
