### ISSUE TITLE
error executing script in thunderbird write message window when braille is tethered to focus

### ISSUE THREAD

**Issue by burmancomp** [nvaccess/nvda#16314]
### Steps to reproduce:
- ensure braille is tethered to focus
- ensure that settings => composition only plain text is in use
- ensure that in thunderbird account settings => composition & addressing compose messages in html format is not checked
- open thunderbird write message window
- write something and press enter so that you are on blank line
- press "next line" button on braille display
### Actual behavior:

error executing script.
### Expected behavior:

no error.
### NVDA logs, crash dumps and other attachments:
[loglines.txt](https://github.com/nvaccess/nvda/files/14623041/loglines.txt)

#### NVDA installed/portable/running from source:
running from source
#### Windows version:
windows 10 22h2
#### Name and version of other software in use when reproducing the issue:
thunderbird 115.11.0 64-bit
#### Does the issue still occur after restarting your computer?
yes
#### If NVDA add-ons are disabled, is your problem still occurring?
yes

**Comment by burmancomp** [comment]
@irrah68 you could not reproduce this in Windows 11 23h2.

**Comment by seanbudd** [comment]
which NVDA version is this occurring in? this was missed in the template. Do you know if this is a regression in 2024.1 or 2024.2?

**Comment by Jykke67** [comment]
I tested this in Thunderbird 115.7.0 (64-bit) and Windows 11 Version 23H2, and no error occured. The message was written in plain text.

**Comment by Adriani90** [comment]
@burmancomp could you test with Thunderbird last beta version?
https://www.thunderbird.net/en-US/thunderbird/124.0beta/releasenotes/
I thought it was solved in Beta 117 but not sure if all of those changes were merged into the 115 stable release.

**Comment by burmancomp** [comment]
> @burmancomp could you test with Thunderbird last beta version?

I read release notes from 116 to 124. On the basis of release notes I am unsure if this was fixed (I could not find any reference to this problem unless I have missed something). @Jykke67 and @irrah68 have w11, and they have not this problem with thunderbird 115. I have w10. It would be interesting if somebody using w10 would test this.

**Comment by seanbudd** [comment]
@burmancomp - can you investigate which config items that cause this? you can do this by comparing the profiles.

When uploading logs, please provide the full log file. When logging at debug level, it includes the config being loaded, which means we can debug what config is causing this.

**Comment by burmancomp** [comment]
> @burmancomp - can you investigate which config items that cause this? you can do this by comparing the profiles.

This should happen with Windows 10 and when using plain text when composing message (see [steps to reproduce](https://github.com/nvaccess/nvda/issues/16314#issue-2189878681) (comment).

I am unsure what I should do.

**Comment by seanbudd** [comment]
@burmancomp - please upload a full log file with debug logging enabled as requested earlier

**Comment by burmancomp** [comment]
Here is log file:

[nvda.log](https://github.com/nvaccess/nvda/files/15326117/nvda.log)

There is also (I guess separate) issue with speech - I copy some lines from attached file to point it out. But I feel that it is not of thunderbird write window merely (I am writing this comment with firefox 125.0.3 and I just noticed similar situation).

Input: kb(laptop):downArrow
DEBUG - editableText.EditableText._hasCaretMoved (22:21:46.440) - MainThread (10348):
Caret didn't move before timeout. Elapsed: 0.102995 sec
DEBUGWARNING - NVDAObjects.IAccessible.normalizeIA2TextFormatField (22:21:46.447) - MainThread (10348):
Unsupported value for text-align attribute: "start"
IO - speech.speech.speak (22:21:46.447) - MainThread (10348):
Speaking ['line 1\n']
DEBUGWARNING - NVDAObjects.IAccessible.normalizeIA2TextFormatField (22:21:46.468) - MainThread (10348):
Unsupported value for text-align attribute: "start"
IO - braille.BrailleBuffer.update (22:21:46.468) - MainThread (10348):
Braille regions text: ['line 2 ']

**Comment by burmancomp** [comment]
After writing previous comment I tried to increase caret movement timeout to solve "Caret didn't move before timeout." problem. With very quick testing increasing timeout to 300 ms did not solve issue completely.
