### ISSUE TITLE
Indentations Not Shown Correctly on Braille Display

### ISSUE THREAD

**Issue by Jykke67** [nvaccess/nvda#16326]
### Steps to reproduce:
1. Edit the default braille table by searching string "\t" and edit the line as follows:

space	\t	0-0-0-0-0-0-0-0-0	# control

2. Open e.g. a new Word document and add one or more hanging indents (Control+T).
3. Pres the Tab key once and type more than one line text (the text should now be shown as indented on the braille display).
4. Move the focus to the next line(s) of the typed text.
### Actual behavior:

Only the very first line of text is shown as indented on the braille display.
### Expected behavior:

All lines should be shown as indented on the braille display (like in JAWS).
### NVDA logs, crash dumps and other attachments:
No attachments available.
#### NVDA installed/portable/running from source:
NVDA installed
#### NVDA version:
2024.1rc1
#### Windows version:
Windows 11 Version 23H2
#### Name and version of other software in use when reproducing the issue:
Microsoft Word (Microsoft Office XP 10.0.2627)
#### Other information about your system:
Microsoft Windows 11 Pro 64-bit (updated from Windows 10 Pro 64-bit)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Have tried beta versions of NVDA. The behaviors have been the same.
#### If NVDA add-ons are disabled, is your problem still occurring?
Becayse This is not an add-on issue, disabling add-ons would not have any affect.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by lukaszgo1** [comment]
Are you able to test this with a more modern version of MS Word?

**Comment by Jykke67** [comment]
I have tested this with add-ons disabled, and no change.

I am unable to test this with a more modern version of Word, but I suppose that it is not a Word issue. Could someone else test?

**Comment by seanbudd** [comment]
Closing as won't fix. We cannot support such outdated versions of Word. If this can be reproduced with a modern copy let us know and we can reopen
