### ISSUE TITLE
When performing an update, NVDA should offer a "what's new" dialog as part of the update conversation

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#16338]
### Is your feature request related to a problem? Please describe.

Users often have no idea what was added between NVDA versions, and what bugs were fixed.
Many never look at the "What's new" option on the Help menu; many others don't even know it's there.

Even experienced users on mailing lists where In-Process is posted (which often highlights important new features) never get around to reading it, or just forget by the time they update NVDA, or for whatever other reason, often seem not to be aware of new features and fixes.

### Describe the solution you'd like

When an NVDA update is requested, before the "Update/postpone" question appears, show a "What's new in this version" dialog.

* The dialog could start with a note that the contents can be read later in the Help menu.
* It could take into account the current NVDA version and the target version, and show everything from the changes file that is between the two versions. It could show everything up or down or both, if one of the versions does not match a known version string, which would happen with alphas and PR/test builds on either side of the update.
* It could end with a "Continue" button, which would result in the current Postpone/Update dialog.

### Describe alternatives you've considered

Show a "Read about what's new" button, as the first control in the "Update/Postpone" dialog.

**Comment by hwf1324** [comment]
Related: #14274

**Comment by Adriani90** [comment]
alternative UX designs can be discussed in #14274. I think there is already a clear proposal out there, meybe comment on that why your alternative is better.
Closing this in favor of #14274.

**Comment by XLTechie** [comment]
@Adriani90
Did you see @feerrenrut's comment on that issue? He said:

> Let the user fetch and review what will change before upgrade. To allow the user to decide whether to upgrade.

That is exactly my proposal in this issue. Since the other has not yet been 
implemented, I propose doing it this way in preference, for exactly the reason 
@feerrenrut described.

I do not think mixing the proposal discussions is the best idea.
