### ISSUE TITLE
documentation\\__pycache__ folder in the launcher of NVDA 2024.1beta4 and above

### ISSUE THREAD

**Issue by tiago-casal** [nvaccess/nvda#16333]
### Steps to reproduce:
With file explorer, explore the NVDA's Documentation folder and you will find an extra subfolder called "\_\_pycache\_\_".
### Actual behavior:

There is an unnecessary subfolder in the installer, "Documentation\\\_\_pycache\_\_".
### Expected behavior:

The **Documentation\\\_\_pycache\_\_** subfolder no longer appears in the launcher, as in 2024.1beta3 and previous versions.
### NVDA logs, crash dumps and other attachments:
n/a
#### NVDA installed/portable/running from source:
Both installed and portable.
#### NVDA version:
2024.1rc1
#### Windows version:
11, 23H2.
#### Name and version of other software in use when reproducing the issue:
n/a
#### Other information about your system:
n/a
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Same behavior in version 2024.1beta4 and higher.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by wmhn1872265132** [comment]
This has been fixed in alpha version, see
https://github.com/nvaccess/nvda/pull/16100

**Comment by CyrilleB79** [comment]
Closing as fixed by #16100.
