### ISSUE TITLE
Automatic focus mode is not activated when focussing an interactive control in an ARIA grid

### ISSUE THREAD

**Issue by bramd** [nvaccess/nvda#16353]
### Steps to reproduce:
1. Open <https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/layout-grids/>
2. Ensure NVDA's "Automatic focus mode for focus changes" option is enabled in browse mode settings (this is the default)
3. Tab through the page until you land on the grid under "Example 1"

### Actual behavior:

NVDA does not enter focus mode.

### Expected behavior:

NVDA should enter focus mode, just like when focussing a gridcell.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.3.4 and alpha-31546,f67d3173
#### Windows version:
Windows 11 23H2
#### Name and version of other software in use when reproducing the issue:
Both in Firefox 124.0.1 and Edge 123.0.2420
#### Does the issue still occur after restarting your computer?
Yes

**Comment by Adriani90** [comment]
This is probably related to #11413. It seems this behavior impacts all interactive elements in grids.

**Comment by bramd** [comment]
@Adriani90 Yes, this seems to be a duplicate. I didn't find it while searching, but it matches this problem exactly.
