### ISSUE TITLE
Single Letter Navigation to MathML

### ISSUE THREAD

**Issue by GeorgeKerscher** [nvaccess/nvda#16350]
### Is your feature request related to a problem? Please describe.
My problem is that it is difficult  to find MathML on a page. Now that MathML is accessible with MathCAT and Access8Math, more people are using MathML for STEM materials. It is easy to move to the next image on a page, and many people want the same ease of navigation to the next MathML expression on the page.
### Describe the solution you'd like
In discussions with people, we thought the equal sign "=" would be a logical character for this functionality.

### Describe alternatives you've considered

We thought that it could be a feature in MathCAT, but other addons, such Access8Math would want to this same functionality. It seems that it is better in core. We do think that this should navigate directly to the HTML "math" element.

### Additional context

Now all the browsers support the display of MathML. In addition, the EPUB publishing standard supports MathML and the Reading Systems support the presentation of MathML. Publishers have now turned to the inclusion of MathML, which is now the best practice in publishing. Microsoft Word also has powerful math editing tools. It would be wonderful if when in browse mode in Word, a person could use single letter navigation with the "=" sign to move to the next math expression. Word has a math mode that is very accessible. The navigation in HTML and EPUB to MathML, coupled with the power of MathCAT allows the cutting of the MathML and then  the user can paste this into Microsoft Word. This workflow is outstanding for students in the STEM field.

We can provide any supporting files if needed.

**Comment by Adriani90** [comment]
This will be part of NVDA 2024.2 and is already part of alpha, has been introduced in #16247. Closing as works for me.
