### ISSUE TITLE
HP Secure Browser support

### ISSUE THREAD

**Issue by tomaszw** [nvaccess/nvda#16377]
### Is your feature request related to a problem? Please describe.
N/A

### Describe the solution you'd like
HP Secure Browser is part of HP Wolf Security package. It is a chromium-based web browser where individual websites are isolated in separate virtual machines. To support screen readers, windows UIA trees are remoted between the virtual machines and the host. IAccessible2 interface is not remoted, hence HP Secure Browser is a rare case of chromium-browser which supports UIA but not IAccessible2.

In theory assuming perfect UIA support in both NVDA and Secure Browser, NVDA should work out-of-the-box. In practice there are a number of tweaks and fixes required to improve UIA-on-chromium scenario on the NVDA side.

HP are planning to submit individual pull requests referencing this issue.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by seanbudd** [comment]
Would we also be able to get a PR adding an item under bug fixes in the change log noting that HP Secure Browser support has improved?

**Comment by Adriani90** [comment]
I think those PRs are also having a positive effect on all chromium browsers when using UIA, see the text under  ‚Describe the user facing changes“. Is it not an idea to include those texts in the changelog for each of the PRs?

**Comment by tomaszw** [comment]
Sure, I've tried to add changelog entries at https://github.com/nvaccess/nvda/pull/16410

Correct, these do also apply to other chromium browsers in UIA mode, so I've noted it as such.
