### ISSUE TITLE
accessibility vs code with Nvda.

### ISSUE THREAD

**Issue by amir7207** [nvaccess/nvda#16391]
Hello. I hope you are well . I am a programmer, and I use Ide visual studio code. In new versions of the program, when we save a file, Nvda says Unknown and we have to close the program and then open it. Please solve this problem in the next update, thank you.
This problem still exists in the latest version of the program that I tested.

**Comment by Adriani90** [comment]
Please run the com registratipn fixing tool in NVDA menu under tools. If the issue still occurs after that, please open a new issue and fill the.complete issue template.

**Comment by amir7207** [comment]
Hello. I hope you are well. I Run the registration fixing tool, but the problem is still there.

**Comment by CyrilleB79** [comment]
@Adriani90 wrote:
> Please run the com registratipn fixing tool in NVDA menu under tools. If the issue still occurs after that, please open a new issue and fill the.complete issue template.

@amir7207, @Adriani90 has explained what to do. Your issue will not be investigated anymore if you do not provide the information requested in the template.
