### ISSUE TITLE
NVDA does not remove "Expanded" state when there are no shortcuts available to an option in the Input gesture settings!

### ISSUE THREAD

**Issue by gauravahir28** [nvaccess/nvda#16401]
### Steps to reproduce:
- Open Input gesture
- open any category such as "Brows mode.
- expand any available subcategory such as "Activates the current object in the document"
- Delete all the assigned keyboard shortcuts  of  expanded subcategory.
- observe the announcement of subcategory
### Actual behavior:

NVDA says "Activates the current object in the document  expanded " even when there are no keyboard shortcuts  available!
### Expected behavior:

NVDA should not convey the expanded state since the keyboard shortcuts are not available anymore!
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA 2024.1
#### Windows version:
Windows 11 23H2
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not tried
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment]
This likely needs to be fixed in Windows
