### ISSUE TITLE
Retrieve color in Microsoft Word 2003

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1641]
**Reported by Shaimaa on 2011-07-02 16:05**
When I press NVDA+f to read the formatting information in Microsoft Word and Excel 2003, NVDA doesn't report the colors at all even if i changed it from the formatting options of the programs themselves. I'm attaching 2 log files for each. I found it good to report both in 1 ticket because I think they are related.

**Comment by leonardder** [comment]
Color reporting works for newer versions of Word, Word 2003 is quite outdated now. Closing, but it might help if someone could tell whether a works for me label could be added.
