### ISSUE TITLE
color from stylesheet where only the colour is changed for that item is not read out correctly

### ISSUE THREAD

**Issue by csworcs** [nvaccess/nvda#16429]
### Steps to reproduce:
Use this web page:
\<!DOCTYPE html>
\<html>
\<link rel="stylesheet" href="style.css">
\<body>
\<h1>To do\</h1>
\<p>Say hello\</p>
\</body>
\</html>

And this style sheet: "style.css"
h1 { color: green;}

Open that webpage in a browser and press 1 to focus on heading. 
Press NVDA+F to get font information.

### Actual behavior:
"Times New Roman 24 pt black on white bold align left"

Note 1: 
If an inline style is used (e.g. \< h1 style='color:green;'>) instead of a stylesheet it works as expected.

Note 2
If the stylesheet item contains two attributes(e.g. h1 { color: green; font-size:100px;}) then it also works as expected with the correct size and colour. 

### Expected behavior:
"Times New Roman 24 pt dark green on white bold align left"

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2022.3.1 works as expected.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment]
Welcome @csworcs ,

We are unable to process this issue as it stands.

To be able to reproduce this issue, we need an interactive code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).

Kind Regards,
NV Access Software Developers

**Comment by gerald-hartig** [comment]
@csworcs can you please use codepen as requested. This helps triage and debugging greatly.

**Comment by csworcs** [comment]
Hi,

I am no longer able to replicate this problem. I will close it and reopen it if I spot it again.

Thank you for your time.

Craig

**Comment by csworcs** [comment]
I am no longer able to replicate this problem. Thank you for your time. I will close the ticket.
