### ISSUE TITLE
NVDA version info: log Python/NVDA architecture as part of version information

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#16432]
Hi,

Coming from 32-vbit to 64-bit transition discussion (#16304):

### Is your feature request related to a problem? Please describe.
As of April 2024, NVDA runs on 32-bit (x86) Python runtime. With the transition to 64-bit runtime, it would be good to know which NVDA version/architecture is in use (useful for developers and testers to isolate architecture issues).

### Describe the solution you'd like
Include 32-bit/64-bit version information when reporting NVDA version (About dialog and log).

### Describe alternatives you've considered
Do not report architecture info in version information but offer a way to query this information.

### Additional context
See #16304 for rationale and overall process

**Comment by XLTechie** [comment]
@josephsl I definitely think this should be queryable and logged, but I'm less sure it should be shown in about until alphas become available in 64 bit.

Users are already sensitive to this topic, and I don't like the notion that they will start having expectations before core is ready to field 64 bit related questions.

Naturally, once it can be queried, adding it to About is trivial.
