### ISSUE TITLE
Sound split: add an ability to adjust applications volume separately from NVDA volume

### ISSUE THREAD

**Issue by mltony** [nvaccess/nvda#16444]
### Is your feature request related to a problem? Please describe.
With Sound split introduced in #16071, there appears to be no way to adjust volume of applications channel sepeartely from NVDA channel. 

### Describe the solution you'd like
Since #16273 is being reverted, I propose to reintroduce this in some form being exclusively marked as sound split feature to avoid any further confusion. We can rename it to something like: "Adjusting volume of applications channel in sound split mode". Thus it will be disabled when sound split is disabled. I also propose to get rid of applications mute feature as it seems to cause unnecessary confusion too.
### Describe alternatives you've considered
N/A
### Additional context
N/A

**Comment by cary-rowen** [comment]
If this feature is tied to sound split, I think it will limit its scope of use. Sound split is useful, but it does not mean that people use it all the time, and vice versa.

**Comment by Adriani90** [comment]
@cary-rowen I think still having it tied to sound split in the first step is good enough to have this in the core. When designing features it is always a trade-off. Either you insist on having the whole cake at once with the risk of not getting it at all, or people accept a piece of cake first and look where it goes afterwards.
Having it tied to sound split might be a good compromise for now.

**Comment by wmhn1872265132** [comment]
I think the operation for all applications should be part of Sound split. Why do you need to adjust the volume of all applications except NVDA without using this function?
The only scenario I can think of is that the TTS volume of NVDA is too low. Even if the voice volume is adjusted to 100, it cannot be heard clearly. By reducing the volume of all other applications, the TTS volume is made loud enough in disguise.
For other scenarios, individual adjustments for a certain application may be a more appropriate solution.
The only problem here is that sudden loud sounds cannot be localized, but enabling Sound split and then reducing the volume of other applications should also be an acceptable solution.

**Comment by seanbudd** [comment]
Is this not a duplicate of #16052? Generally we re-open the original issue after performing a revert

**Comment by mltony** [comment]
Ok, I'll close this. It would be good to have an agreement on a path forward - I listed 5 requirements in #16440 - could you check that they make sense to you and I didn't leave anything out?
