### ISSUE TITLE
NVDA not honoring aria-selected="true" in date picker calendar

### ISSUE THREAD

**Issue by grahamarmfield** [nvaccess/nvda#16454]
### Steps to reproduce:

1. Start NVDA
2. Open Firefox
3. Navigate to W3C WAI Date Picker Dialog page (https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/)
4. In the example, note that no date is currently in the text box. Open calendar by actioning 'Choose Date' button after text input field.
5. Use up, down, left and right arrow keys to move around the current month.
6. When on one date press Enter key to select that date. Date input field is populated with selected date.
7. Return to 'Choose Date' button after text input field and open calendar again.
8. Move around month using arrow keys - including moving to previously selected date.

### Actual behavior:

1. When calendar is first opened NVDA announces current month table and current day number and not selected. For example "April 2024 table, 26 not selected". This is as expected.
2. When I move around in month NVDA announces new day number and not selected. For example "25 not selected, 24 not selected".
3. When I press Enter to select a date, NVDA announces "button Change Date, Wednesday April 24, 2024"
4. When I then open the calendar again and move around month using arrow keys NVDA once again announces day number and not selected.
5. When I move to the date I previously selected NVDA announces the day number and not selected.

### Expected behavior:

If I have previously selected a date and I go back into the calendar, when I move onto the date I have previously selected I would expect NVDA to announce day number and 'selected' rather than 'not selected'.

Looking at the underlying code for the calendar the table cell containing the previously selected day number has aria-selected="true" present.

### NVDA logs, crash dumps and other attachments:
[nvda.log](https://github.com/nvaccess/nvda/files/15131722/nvda.log)

#### NVDA installed/portable/running from source:
NVDA is installed

#### NVDA version:
2024.1 (2024.1.0.31547)

#### Windows version:
Windows 10   Version 10.0.19045 Build 19045

#### Name and version of other software in use when reproducing the issue:
Firefox 125.0.2 (64-bit)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Don't think I have add-ons running

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment]
Cc: @jcsteh

**Comment by jcsteh** [comment]
Coincidentally, i just filed a Firefox bug about this a few days ago. https://bugzilla.mozilla.org/show_bug.cgi?id=1893096

**Comment by jcsteh** [comment]
This has been fixed in Firefox Nightly and will be included in the Firefox 127 release.

**Comment by grahamarmfield** [comment]
Excellent, thanks for letting me know.
