### ISSUE TITLE
sony Support for SoundForge (v. Pro 10)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1645]
**Reported by menschomat on 2011-07-04 10:43**
Sony's SoundForge Pro 10 is pretty accessible so far, and I use it for cutting sound files on a regular basis.
Unfortunately NVDA doesn't speak the status bar i. e. when loading or saving large files.
I suppose it isn't a difficult matter to add this feature so I stand informed while waiting.

Yours sincerely

Arno

**Comment by leonardder** [comment]
We are now at SoundForge 11, so it is very unlikely that this will be fixed specifically for 10. I suggest closing this, a new issue can be raised if this is still valid for SoundForge 11.
