### ISSUE TITLE
Firefox menu bar drop-down option list problem using mouse pointer with NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1647]
**Reported by dcmack on 2011-07-05 04:52**
I shall begin with a general description of the problem followed by a brief but somewhat detailed description of Firefox layout and mouse-pointer movements and resulting NVDA announcements as the pointer is moved or is stationary within a Firefox drop-down menu panel.

Part 1.  General description of problem.

NVDA's latest BETA 2 as well as earlier versions of NVDA have a problem reading the dropdown Firefox menus correctly when using a physical mouse pointer or other pointing method such as a touch pad on a laptop. Invariably, NVDA reports the underlying web address field or portions of text on other menu bars present on Firefox or the webpage text beneath the drop-down menu list panel instead of the individual menu items in the dropdown list.   The menu bar drop-down menu lists in Internet Explorer and other programs are quite responsive unlike Firefox when rolling the physical mouse pointer up and down  the dropdown lists.   When using a mouse pointer on Firefox one must roll the mouse pointer very slowly up and down the vertical list of drop-down options several times to have NVDA recognize a list item and even then NVDA  rarely reads correctly.  It is much less responsive and accurate than on menu bar lists in other programs.   When not otherwise misbehaving by reporting text beneath the drop-down menu panel, NVDA will often lag behind and report a prior menu item the pointer has passed over rather than the menu option the pointer is actually paused upon.  It is almost as if NVDA is treating the menu panels  as semi-transparent and is always trying to read text underneath instead of the drop-down menu item panel the pointer is situated upon.  The problem occurs with Firefox 3, 4 and 5 on my Win 7 machine and seems to be related to video-hooking or whatever in some manner unique to Firefox.

Part 2.  A detailed description in lieu of a debug log.  I will try as best I can to create a mental picture of the mouse pointer behavior and associated NVDA responses.

First, I will be using Firefox in maximized mode so the title bar is at the top of the screen and the menu bar is situated directly beneath the title bar - both, of course, running horizontally at top of screen.  I have disabled most other Firefox add-on option bars for simplicity but beneath the menu bar is the so-called Navigation Bar, containing the web page adress field and to the far right is also a search field in my version of Firefox. I will be describing the use of the Firefox drop-down menus while the browser is open on the NVDA homepage for this example.   I should also mention that I have my menu options set to a fairly large font size due to my low vision so my drop-down menus  extend a bit farther down the screen than normal but this is not a problem.  The same problem exists with smaller menu fonts, except NVDA may read a different portion of the background than I will be describing depending on the font size used and, hence, how far down a menu panel drops in the foreground over a webpage in the main viewing pane.

I shall begin by moving the mouse pointer horizontally over the menu bar titles beneath the program title bar.  As I do so, NVDA correctly reports the following drop-down menu titles in sequence running left to right as follows:  "File", "Edit", "View", "History", "Bookmarks", "Tools", and "Help".  This, of course, corresponds to what one hears when pressing ALT-F and then using the right arrow key to navigate menu bar titles horizontally in Firefox 5.0.

All is well to this point as NVDA will properly read the menu titles with pointing device until I stop on one and click it with my left mouse button and make the associated option panel drop down.

Let us say I pause my mouse pointer on "Bookmarks" and click the left mouse button. As the Bookmark menu panel opens and drops down its menu of options, NVDA immediately says "Bookmarks Menu" which is fine.  However, when I move the pointer down vertically to the first option which actually says "Bookmark this Page Control plus D" that is not what NVDA reports.  Instead of reading that menu item, it reads aloud the NVDA homepage web address which is in the Navigation address field underneath the Bookmark menu option which is on top of the adress field and covering most of it. Now when I move the mouse pointer down vertically to the next item in the Bookkmark menu list, NVDA says "NVDA Download" or sometimes may say  "NVDA logo" which is actually reading info from the web page I have previously loaded for this demo but NVDA should actually say "Subscribe to this page - Unavailable".  To get it to say the menu item properly, I must go to the third item down the list with the mouse pointer and then go back up to the second item again and NVDA may propperly speak the option text this time but that is not always the case.  Now when I run the mouse pointer further down the menu vertically, NVDA reads portions of text from NVDA;s homepage instead of the menu items.  I must go up and down, pausing occasionally and I may get a correct option reported but most often this does not happen and I must put down my coffee cup I was holding in my free hand and use the up and down arrow keys instead of the mouse pointer (Pardon my attempt at a little humor) .

I will give further examples using other menu categories such as File, Edit, Tools, et cetera if they ar needed but the example I have cited is what occurs in these other drop-down menus as well.

I hope this brief description is helpful and if I can be of further assistance in this please let me know as I truly appreciate the amazing work you are doing for so many of us. 

Dave Mack (aka Grandpa Dave in California)

**Comment by ehollig** [comment]
This was fixed in Firefox 25 acording to [MozillaBug:670087](https://bugzilla.mozilla.org/show_bug.cgi?id=670087)
