### ISSUE TITLE
Consider the addition of a NVDA shortcut key, to present further information.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1648]
**Reported by MHameed on 2011-07-05 11:10**
in several places a user may wish to get information that is not presented by the normal navigation mode, or reduce the information given and have it optional.

For example:
- in lists: "item 3 of 5" 
- in tables: "row 5 column 3" (briefly discussed in #719)
- context sensative additional info for controls: "multi line edit, line 500 of 1000" (#1480)
- for radio buttons, the radio button group label
- application specific additional info such as duration of track (#727)
- announcement of read only fields (#1436)

The above are just a few examples of additional information that the user may need.

NVDA already presents some of this information when the user navigates, but some people perceive that it can be "too chatty" at times and want this information upon request.

By reducing the standard information being presented, they will feel that nvda is quick and they can achieve their tasks quickly, while still having access to the additional information whenever they require it.

This also means that we dont have to introduce various shortcut keys for reading bits of information.

People using orca would recognize this as the 'where am I' key, I think the Mac screenreader also has a similar function but not sure.

Thanks for your consideration.

**Comment by bhavyashah** [comment]
@jcsteh In https://github.com/nvaccess/nvda/issues/1648#issuecomment-155291452, you had mentioned that something of the like was being considered back then. Could you please update us with your present thoughts on this ticket?

**Comment by jcsteh** [comment]
Since then, the report location command (NVDA+numpadDelete/NVDA+delete) has been extended to report some context specific info where appropriate. That will probably be extended further still for various situations. I tend to think the report current object commands (NVDA+tab and NVDA+numpad5) plus the report location command are enough to cover various scenarios, but those scenarios should be addressed as separate cases. Closing.
