### ISSUE TITLE
NVDA repeats input label text

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1650]
**Reported by stevefaulkner on 2011-07-05 15:14**
when an author codes a HTML label element in certain ways NVDA announces the label text twice when an input receives focus.

I have provided test cases and results here: 
http://www.html5accessibility.com/tests/form-labels.html

**Comment by ehollig** [comment]
It sounds as if [MozillaBug:682790](https://bug1234567.bugzilla.mozilla.org/show_bug.cgi?id=682790) has been resolved in Firefox 10. When opening the above link, http://www.html5accessibility.com/tests/form-labels.html, I believe everything works as expected, but am not exactly clear on what is the original issue is. No labels double speak when I navigate the example site.

**Comment by Brian1Gaff** [comment]
What about tests 5 and 6?
 You need to go back to header then cursor down, or it only says it once.

Firefox 55 32 bit windows 7 64 pro
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by ehollig** [comment]
@Brian1Gaff is this still an issue for you? When I use the arrow keys to the edit fields or use tab navigation to all of athe examples on this site, I am not getting double speaking. Using NVDA latest Alpha with Chrome and Firefox.

**Comment by Adriani90** [comment]
I am testing with NVDA 2019.1 on Firefox 66.0.2. and Chrome 73. Every example is pronounced only once as it should be.

Tested as follows:
1. In Browse mode, navigate the tests from top to bottom of the website and back fro bottom to the top with arrow keys: labels reported only once
2. In browse mode navigate the tests from top to bottom and back to top with tab and shift+tab: NVDA reports the labels only once.
3. In focus mode navigate the tests from top to bottom and then back from bottom to top with tab and shift+tab: NVDA reports labels only once.

Thus, closing as works for me.
