### ISSUE TITLE
NVDA not read the status change when focus on button

### ISSUE THREAD

**Issue by wuyanweu19950707** [nvaccess/nvda#16509]
### Steps to reproduce:
When focus on a button and then using keyboard to trigger the button action with an text chang, NVDA not read out the status change.
Steps：
 1. Open Chrome settings page.
 2. Go to Sync and Google services.
 3. Using the space key to trigger the toggle button in "Enhance spell check"
![Screenshot 2024-05-09 095620](https://github.com/nvaccess/nvda/assets/163518190/362cd0f2-bb12-45fb-950e-b790e27d4fc2)
 4. NVDA only read "press" or "not press", but the other screen reader software will also read the changed status like "toggle button checked" (eg. JAWS)

### Actual behavior:
The braille viewer output
![Screenshot 2024-05-09 095924](https://github.com/nvaccess/nvda/assets/163518190/bc8ea5ee-edfb-4a17-bf05-96511e489fbe)

### Expected behavior:
When using keyboard to trigger a button change, expect NVDA will read out the status change (check status, text change or other changed properties) when focus still on this button.

### NVDA logs, crash dumps and other attachments:
[nvda.log](https://github.com/nvaccess/nvda/files/15256697/nvda.log)

#### NVDA version:
2023.3.3

#### Windows version:
Window 11

#### Name and version of other software in use when reproducing the issue:
Google Chrome
Version 124.0.6367.119 (Official Build) (64-bit)

#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. Behave same.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by seanbudd** [comment]
This is expected behaviour. We use the terminology "pressed/not pressed" in this scenario for toggle buttons. It is the same concept as checked/not checked.
