### ISSUE TITLE
NVDA+arrowdown not working in WinUI apps

### ISSUE THREAD

**Issue by Youssef1313** [nvaccess/nvda#16524]
### Steps to reproduce:

1. Open NVDA (set CapsLock as NVDA modifier key)

    ![image](https://github.com/nvaccess/nvda/assets/31348972/17350f9d-423f-4c73-996e-e8b27ed12106)

2. Open WinUI 3 Gallery

3. Press multiple tabs, the elements are correctly read.

4. Press CapsLock+arrowdown, nothing is read

### Actual behavior:

CapsLock+arrowdown not working

### Expected behavior:

It's expected to work per https://www.nvaccess.org/files/nvda/documentation/userGuide.html

![image](https://github.com/nvaccess/nvda/assets/31348972/6866b5eb-4a66-4b1c-9ff4-babcd46639d9)

#### NVDA version:

2023.3.4.31265

#### Windows version:

22H2 (OS Build 19045.4291)

**Comment by Adriani90** [comment]
That is not a browse mode document, and it is also not an edit field. Say all works only in browse mode and in editable areas. If you want to read the whole window, you can press nvda+b. I am closing as invalid.

**Comment by Youssef1313** [comment]
Thanks for the clarification @Adriani90. This is exactly what I needed.
