### ISSUE TITLE
In NVDA's input gestures category, allow assigning gestures for touch screen input

### ISSUE THREAD

**Issue by kefaslungu** [nvaccess/nvda#16526]
### Is your feature request related to a problem? Please describe.
Currently, NVDA's input gestures let users personalize their experience by assigning keyboard shortcuts or using predefined layouts ("Laptop" and "All"). However, touchscreen users lack this flexibility.
### Describe the solution you'd like
when assigning gestures to nvda functions using the input gestures, we currently have the following options:
* Laptop layout.
* All layout.
But what if we could have a third option for those using a touch screen enabled computer? (touch screen)
#### For example:
If I'll like to assign a gesture for
> Reports the name of the current NVDA configuration profile.

currently, I can only choose between laptop and all, but I want a situation whereby I can assign it to a touch screen gesture if I'm using a touch screen enabled computer.
### Describe alternatives you've considered
Another alternative, is to implement something like that on enhanced touch gestures.
### Additional context
Assigning touch gestures allows users to choose intuitive and comfortable ways to interact with various NVDA commands, this feature request proposes allowing users to assign touch gestures for NVDA functionalities.

**Comment by CyrilleB79** [comment]
When you add a gesture in the dialog:
* if you type one ore more keys on the keyboard, you get the desktop/laptop/all layouts choice
* if you type on a braille keyboard, you have other choices such as: space with dot 1 (Eurobraille keyboard), space with dot 1 (braille keyboard), space with any dot, etc.

What happens if you press "Add" in the input gesture dialog and enter a touch gesture?

**Comment by kefaslungu** [comment]
> What happens if you press "Add" in the input gesture dialog and enter a touch gesture?

Thank you! I didn't thought of that, it brings up an option for the following:
* (Touch screen, object mode)
* (Touch screen
Thank you again.
