### ISSUE TITLE
NVDA has problem reading information with large dictionaries

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1652]
**Reported by drein on 2011-07-06 13:05**
With quite big dictionary, NVDA is not able to make spelling, read date/time or copy to clipboard the t itle of a window.
It should very useful if some commands like insert+f12, insert+t have priority over the dictionaries, otherwise it is quite difficult to use  the "double commands" insert+t of insert+f12.

**Comment by bhavyashah** [comment]
@jcsteh @feerrenrut @tspivey Could the file attached in https://github.com/nvaccess/nvda/issues/1652#issuecomment-155291472 please be restored as well as the NeedsCodeReview label be added to this ticket?

**Comment by feerrenrut** [comment]
Added the attachment to the comment, since quite some time has passed this will need to be re-tested, and a PR created.

**Comment by Adriani90** [comment]
@drein are you still seeing this issue in NVDA 2019.2 RC2? @tspivey your global plugin is certainly a promising feature for some users. And if you could implement it with an unassigned key stroke that would be great. Are you planning to raise a PR for this any time in the future?

**Comment by CyrilleB79** [comment]
> and we don't have any updates from the initial author on this issue after asking for it. 

Cc @dreinn (with two n's), which is most likely the real initial reporter of this issue.

@dreinn:
As written by @Adriani90, if you still have the problem, please provide an update and we can reopen.
