### ISSUE TITLE
Macintosh version, please!

### ISSUE THREAD

**Issue by unblocktheplanet** [nvaccess/nvda#16536]
### Is your feature request related to a problem? Please describe.
Need Macintosh version, please.
### Describe the solution you'd like
Macintosh version, please.
### Describe alternatives you've considered
Mac's VoiceOver
### Additional context
Mac now needs 64bit
Thank you.

**Comment by seanbudd** [comment]
Sorry - this is not within the scope of the NVDA project. Screen readers are completely OS specific.
I'm aware there are some projects attempting to write an open source screen reader for mac.
You may wish to follow these projects instead.
I found this with a web search: https://github.com/Choominator/Vosh
