### ISSUE TITLE
Optional rendering of unlabelled graphics which aren't interactive

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1654]
**Reported by drein on 2011-07-07 08:23**
I'm using NVDA 2011.1beta3 and Ie8.
in the following webpage,  you will find a table where there is a comparison between various features of a filehosting company, and there are some graphics where the feature is enabled.
For example ftp is not available for free, but only for premium users.
NVDA is not able to detect this graphics, and for reading it I must run jaws, enable all graphics and then I can understand where is the little image.
the web page is:
http://www.adrive.com/plans

**Comment by leonardder** [comment]
Closing n favour of newer duplicate #5874.

**Comment by leonardder** [comment]
Hmm, honestly, I decided to quick on this one. I'm getting overworked.

**Comment by leonardder** [comment]
Closing for real this time, duplicate of #7412, which contains some considerations by @JCSTeh and for which triage has already token place.
