### ISSUE TITLE
Text paragraph navigation: NVDA crashes in Kindle

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#16558]
### Steps to reproduce:
1. Open NVDA
2. Open a book in Kindle
3. Press p or shift+p to navigate to a text paragraph

### Actual behavior:
NVDA crashes imediately. No crashdump generated.
[nvda-old.txt](https://github.com/nvaccess/nvda/files/15339227/nvda-old.txt)

### Expected behavior:
NVDA should navigate to text paragraphs as it does in other browse mode documents.

### NVDA logs, crash dumps and other attachments:
Attached above

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-31948,fdc3e9e6 (2024.3.0.31948)

#### Windows version:
Windows 11 23 H2

#### Name and version of other software in use when reproducing the issue:
Kinde 2.3.5 for desktop

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
cc: @mltony, @seanbudd I don't know if the crash can be fixed, otherwise I would say disable text paragraph navigation for kindle completely because this command is set by default and users might deal with this crash accidentally when pressing p.

**Comment by mltony** [comment]
How do you setup kindle app? I bought a sample kindle book - but in order to read it it asks me to log in and presents me with a visual captcha - seemingly with no audio option.

**Comment by Adriani90** [comment]
I used the Be my AI app on my Phone and took a picture of the screen, the AI bot could give me the code from the captcha.Von meinem iPhone gesendetAm 16.05.2024 um 22:10 schrieb mltony ***@***.***>:﻿
How do you setup kindle app? I bought a sample kindle book - but in order to read it it asks me to log in and presents me with a visual captcha - seemingly with no audio option.

**Comment by Adriani90** [comment]
You must put the book in full screen in the view menu to repro the crash.

**Comment by XLTechie** [comment]
The usual solution is to call Amazon accessibility, who will generate a bypass key for you.

**Comment by Adriani90** [comment]
This happens automatically if you enter the wrong captcha code 3 times or so. Then you would get a code per SMS if you have given your phone number in your Amazon account before.Von meinem iPhone gesendetAm 17.05.2024 um 03:37 schrieb Luke Davis ***@***.***>:﻿
The usual solution is to call Amazon accessibility, who will generate a bypass key for you.
