### ISSUE TITLE
Many blank lines in browse mode after #16471 merge

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/nvda#16554]
### Steps to reproduce:
1. Open https://github.com/nvaccess/nvda/pull/16471
2. Go to the `Code Review Checklist:` heading
3. Press down arrow

### Actual behavior:
NVDA reports three empty lines below the heading before it reports the first list item

### Expected behavior:
NVDA directly moves to the first list item.

### Additional context
There are also empty lines added in the github pull request overview, for example.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-31919,383b2044

#### Windows version:
Windows 11 23H2

#### Name and version of other software in use when reproducing the issue:
Firefox 125.0.3

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, I reverted a1848dd when running from source and the issue disappeared.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by Adriani90** [comment]
cc: @SaschaCowley
