### ISSUE TITLE
Disable text style navigation in Kindle

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#16559]
### Detailed description of the issue
Text style navigation does not work in Kindle for Desktop because text formating is not available in Kindle. Instead, the text style navigation fails and produces errors and freezes of at least 1.5 seconds while trying to get text style formatting.

### Why are the other templates not appropriate in this case?
It is not a bug, it is a limitation given by Kindle, so we should not support text style navigation there.
This request is also the oposite of a feature.

### Have you asked for advice on how to report this issue via a community discussion? If so, please link to the discussion
n/a

### Steps to reproduce or illustrate the issue (if applicable)
1. Open NVDA
2. Assign [ and shift+[ for different style navigation
3. Assign ] and shift+] for same style navigation
4. Open a book in Kindle for desktop
5. Press the assigned commands for navigating to next and previous text styles

### Expected outcome or behaviour (if applicable)
NVDA should not support text style navigation because formatting information is not available.

### Screenshots, logs, and other attachments (if applicable)
n/a

### System configuration or software environment (if applicable)
n/a

### Additional information (if applicable)
Following is written to the log:
```
IO - inputCore.InputManager.executeGesture (20:17:50.672) - winInputHook (4440):
Input: kb(laptop):plus
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2States (20:17:50.672) - MainThread (8124):
could not get IAccessible2 states
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1922, in _get_IA2States
_ctypes.COMError: (-2147467263, 'Nicht implementiert', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getLineOffsets (20:17:50.952) - MainThread (8124):
IAccessibleText::textAtOffset failed
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 376, in _getParagraphOffsets
  File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 349, in _getLineOffsets
  File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (20:17:51.183) - watchdog (7464):
Potential freeze, waiting up to 10 seconds.
ERROR - scriptHandler.executeScript (20:17:52.102) - MainThread (8124):
error executing script: <bound method BrowseModeTreeInterceptor.addQuickNav.<locals>.<lambda> of <appModules.kindle.BookPageViewTreeInterceptor object at 0x09033DD0>> with gesture 'plus'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "browseMode.pyc", line 558, in <lambda>
  File "browseMode.pyc", line 516, in _quickNavScript
  File "browseMode.pyc", line 2447, in _iterTextStyle
IndexError: list index out of range
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (20:17:52.184) - watchdog (7464):
Recovered from potential freeze after 1.5018194999993284 seconds.
IO - inputCore.InputManager.executeGesture (20:17:52.659) - winInputHook (4440):
Input: kb(laptop):ü
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2States (20:17:52.664) - MainThread (8124):
could not get IAccessible2 states
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1922, in _get_IA2States
_ctypes.COMError: (-2147467263, 'Nicht implementiert', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getLineOffsets (20:17:52.942) - MainThread (8124):
IAccessibleText::textAtOffset failed
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 376, in _getParagraphOffsets
  File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 349, in _getLineOffsets
  File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (20:17:53.159) - watchdog (7464):
Potential freeze, waiting up to 10 seconds.
IO - speech.speech.speak (20:17:55.102) - MainThread (8124):
Speaking ['No next different style text']
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (20:17:55.161) - watchdog (7464):
Recovered from potential freeze after 2.501913500000228 seconds.
```

**Comment by CyrilleB79** [comment]
Style navigation, and maybe also other types of navigation implemented by @mltony, should be tested in all type of content where the shortcut can be executed, I.e. all content having a browse mode I guess.

PS: Not very important, but IMO, the bug template was suitable for this. It's a bug: text style navigation feature is expected to work in any text content but it does not actually work in Kindle. No worry though: with this template, the required information is available in any case.

**Comment by Adriani90** [comment]
Vertical navigation seems to be the most stable one for now.Text paragraph is also stable with the exception that makes NVDA crash in Kindle.Text style navigation works stable only in browsers sofar.Von meinem iPhone gesendetAm 16.05.2024 um 21:40 schrieb Cyrille Bougot ***@***.***>:﻿
Style navigation, and maybe also other types of navigation implemented by @mltony, should be tested in all type of content where the shortcut can be executed, I.e. all content having a browse mode I guess.
PS: Not very important, but IMO, the bug template was suitable for this. It's a bug: text style navigation feature is expected to work in any text content but it does not actually work in Kindle. No worry though: with this template, the required information is available in any case.
