### ISSUE TITLE
Hyphenated words reported incorrectly in standard Windows Edit controls on Win XP with East Asian langs installed

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1657]
**Reported by jteh on 2011-07-08 09:26**
Split off #1455:
 1f25164770f92a8d04a3b1143a7453ad384e69b1 breaks this again for XP with east asian languages installed. Need a way to detect this and fall back to uniscribe.
Works in 2011.1.1, but the old implementation was extremely problematic and cannot be reinstated.

**Comment by leonardder** [comment]
@JCSTeh: Is this still valid?

**Comment by jcsteh** [comment]
No, because it's XP specific and we're not fixing XP specific issues.
