### ISSUE TITLE
Developer Quick-Start Guide

### ISSUE THREAD

**Issue by simmocha** [nvaccess/nvda#16601]
### Is your feature request related to a problem? Please describe.
Although the existing documentation is good and I was able to set up a development environment by following it, I think that the project could benefit from a quick-start guide for developers.  It appears that the development documentation is separated into multiple files in the nvda/projectDocs/dev/ directory, and I'm afraid I was not able to find a direct link to here in many of the main documents that a new developer would see first (README.md and CONTRIBUTING.md, for example).
### Describe the solution you'd like
Please consider adding a quick-start guide file that summarizes the steps for setting up a development environment, and perhaps a link to the file in one of the upper-level documents, such as CONTRIBUTING.md.  It looks like the main steps are in https://github.com/nvaccess/nvda/blob/master/projectDocs/dev/buildingNVDA.md and https://github.com/nvaccess/nvda/blob/master/projectDocs/dev/createDevEnvironment.md, and I have included an example quick-start file based on them as an attachment.
### Describe alternatives you've considered
I do appreciate the documentation that you already have, and an alternative could also be to link directly to the nvda/projectDocs/dev/ directory in the documentation files.
### Additional context
I have created an example quickStartGuide.md (intended to be placed in the nvda/projectDocs/dev/ directory) and a small change to the CONTRIBUTING.md to link to it.
[CONTRIBUTING.md](https://github.com/nvaccess/nvda/files/15425515/CONTRIBUTING.md)
[quickStartGuide.md](https://github.com/nvaccess/nvda/files/15425524/quickStartGuide.md)
If interested, I am happy to edit/update/polish these files as needed.  Thank you for your time and consideration!

**Comment by seanbudd** [comment]
@simmocha - can you please explain what this is trying to achieve differently to https://github.com/nvaccess/nvda/blob/master/projectDocs/dev/contributing.md#overview-of-contribution-process, which is linked from the main contributing page?

All of the information in this page is important for getting started with contributing as a developer

**Comment by simmocha** [comment]
Thank you for your quick response, and I will admit that I have somehow managed to overlook the part of the guide that you've linked.  I suppose the main difference would be that we could consolidate the steps for setting up a development environment into one document for more junior developers.  I was intending to make a quick pathway to get the project's code set up on their computer so they could begin exploring it.

**Comment by seanbudd** [comment]
Would you consider making a PR to make any improvements to that document you see necessary?
Perhaps a high level summary at the top?

**Comment by simmocha** [comment]
Thank you, yes, I would be happy to take a look into that!  I'll try to be careful that any edits I request don't get in the way of or detract from the existing guides.

**Comment by seanbudd** [comment]
Closing as fixed. Feel free to open a new issue or PR as we descissued earlier
