### ISSUE TITLE
Add / update the documentation to translate NVDA's interface (nvda.po)

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#16656]
### Detailed description of the issue
New translators need guidance on how to translate the interface. Currently, there are many translators for new languages or abandoned ones, but they do not seem to go forward and some of them have explicitly asked for help on the translators mailing list.

For now, we have an outdated wiki as well as messages on the mailing list. For someone who has not followed the discussion during the transition, it is hard to know the current process to translate the interface as well as having tips on how to use Crodin.

I was about to write a wiki on how to translate the interface, when #16627 has been opened. Also I am not very comfortable with Crowdin.

### Why are the other templates not appropriate in this case?
It is documentation only.

### Have you asked for advice on how to report this issue via a community discussion? If so, please link to the discussion
No

### Steps to reproduce or illustrate the issue (if applicable)
N/A

### Expected outcome or behaviour (if applicable)
N/A

### Screenshots, logs, and other attachments (if applicable)
N/A

### System configuration or software environment (if applicable)
N/A

### Additional information (if applicable)
N/A

**Comment by Adriani90** [comment]
I don't know why people are so confused about translating the interface. Actually, there are tons of possibilities to translate strings in a po file, it doesn't have to be crowdin or poedit or what ever.
I am concerned that people expect the NVDA project to give a translating guide for Crowding or Poedit interface, but there are tons of other ways where people can upload the po file and translate it.
The process is as easy as this:
Either:
1. Log in to the Crowdin NVDA project
2. Translate the strings of your language in the crowdin interface
3. Let people with approval rights approve your translations
4. Done.

Or
1. Login to the Crowdin NVDA project
2. Download the .po file of your language from Crowdin NVDA project
3. Search for the po editor of your choice, or any other website which you are confortable with and make yourself familliar with its interface
4. Load the downloaded po file into that interface
5. Translate the strings
6. Save the file locally
7. If you don't have approval rights in the Crowdin project, send the translated file to a person from your language translation community who has approval rights
8. If you have approval rights, upload the translated .po file back to crowdin into your language and enable the checkbox to approve all changes
9. Done.

I think also Crowdin has a really comprehensive user guide and documentation. In my view the NVDA project should not be responsible for giving people a full user guide for an external interface.
We can give recommendations, and explain the NVDA translation process. But explaining the Crowdin or Poedit interface should not be in scope of the guide.

cc: @michaelDCurran
