### ISSUE TITLE
NVDA AND FACEBOOK COMPETITION PROBLEM

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1666]
**Reported by dharvey on 2011-07-11 10:15**
Hello,

A new technology provider in New Zealand launched today and are offering promo codes via their Facebook page.

Sighted users report no issue, but using NVDA after clicking on the Welcome Promo tab to get my discount code brings up a bunch of ads instead of the coupon.
STR:
1. Go to www.facebook.com/TechTigerNZ and like the page.
2. Go to the Welcome Promo link and press Enter to activate it.

Expected result: Should be able to get my discount code.

Current result: Gets a bunch of FB ads instead of promo code.

**Comment by ehollig** [comment]
I received a "Page not found error" for the URL provided in steps by original poster. Suggest a close.

**Comment by derekriemer** [comment]
closing as invalid because even so, it's not really likely an NVDA issue, and it's antique.
