### ISSUE TITLE
feature request: Editing semi-accessible edit boxes

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#16680]
### Is your feature request related to a problem? Please describe.

Here is a short quote from [mltony/nvda-browser-nav | Editing semi-accessible edit boxes](https://github.com/mltony/nvda-browser-nav#editing-semi-accessible-edit-boxes):

> Many modern web applications, notably Jupyter among others, use edit boxes, that are not that accessible, e.g. they appear blank, but you can copy text in and out of them using Control+A, Control+C and Control+V keystrokes.

### Describe the solution you'd like

We suggest that NVDA provides a method to better interact with and edit these semi-accessible edit boxes, improving the user experience.

**Comment by seanbudd** [comment]
If a certain control is an accessible this is a bug. 
Can you please reopen a new issue filling out the bug template?
We need a lot more information here that is requested in the template such as:
- example software and the software version involved
- steps to reproduce
- a log file
- the version of NVDA involved

**Comment by surfer0627** [comment]
> If a certain control is not accessible this is a bug. 
Can you please reopen a new issue filling out the bug template?

Yes.
The testing case occurs in an internal application. Once I find a good example for testing, I will reopen the issue.
