### ISSUE TITLE
[Bug] Task switcher (windows + number key) response is very slow

### ISSUE THREAD

**Issue by mo29cg** [nvaccess/nvda#16737]
### Steps to reproduce:
* pin any program to task bar, so you can access it by windows + number key.
* Open two window of the same program.
* Try switching the window by pressing windows + number key several times.

### Actual behavior:
Response of nvda is very slow and laggy.
It takes several seconds before it starts saying the selected  window name.

### Expected behavior:
It should respond more real time, like it does when only one window of the same program is open.

### NVDA logs, crash dumps and other attachments:
None.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2024.1
#### Windows version:
windows10
#### Name and version of other software in use when reproducing the issue:
This occurs  with any software pinned on task bar, but I tried with firefox, vscode, file explorer .
#### Other information about your system:
None

### Other questions
If there is a workaround of this, like setting of windows, I want to know.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Also occured with 2023.3
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by mo29cg** [comment]
@Adriani90 
Just checked, and yeah it does.
Might be a little bit more laggy with nvda, but it's occuring on a simillar level.

**Comment by Adriani90** [comment]
This seems to be also the case when no screenreader is running. You need to report this to Microsoft. Closing as invalid.
