### ISSUE TITLE
Request for Turkish Grade II table

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#16735]
### Is your feature request related to a problem? Please describe.

NVDA 2024.2 includes Liblouis 3.29.  This version of LibLouis includes a Turkish Grade II table, however this has not been enabled in NVDA.

### Describe the solution you'd like

Enable the Turkish Grade II table for Braille users of NVDA.

### Additional context
(Requested by email as "Suggestion request")

**Comment by oguzugur28** [comment]
Hi,
Via Email, I've shared this problem. Now, I want to explain the problem step by step:
1. Open the NVDA Settings screen.
2. Go to the Braille sub title and move to the Braille table selection box.
3. User can find Turkish Grade I table only.

However, NVDA's Liblouis folder which is named Louis, includes Turkish Grade II table but on the NVDA settings screen, only Turkish Grade I option is displayed to selectable.

I hope I can explain the bug clearly.

İf you have any question about this bug, don't hesitate to reach me.

Best,
