### ISSUE TITLE
Request for IPA Braille table

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#16773]
### Is your feature request related to a problem? Please describe.

LibLouis includes an IPA Braille Table, however NVDA does not make this available.

### Describe the solution you'd like

Enable the IPA Braille Table in NVDA.

### Additional context

Requested by Kara on Mastodon.

**Comment by SaschaCowley** [comment]
See also #2044

**Comment by josephsl** [comment]
Hi,

I think the table should be output only for now unless we get a justification or two on entering IPA via braille.

Thanks.

**Comment by zstanecic** [comment]
Hi Joseph and all, 
I can act appropriatelly and create a pull request to add this.
Which release is this going to target?

**Comment by josephsl** [comment]
Hi, try basing it on beta as the milestone is 2024.3 (according to GitHub). Be sure to work on both the braille tables list and changes.md (perhaps edit the new braille tables list in change.md file). Thanks.

**Comment by zstanecic** [comment]
Hi @josephsl 
Will do so in an hour from now on.
