### ISSUE TITLE
NVDA prevents mp3tag from exiting

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1677]
**Reported by tspivey on 2011-07-17 07:07**
STR:
Get mp3tag from http://www.mp3tag.de/en/index.html
Install and run it. Close it with alt+f4.
On my system, the process hangs around until I kill it in task manager. If I do it with NVDA unloaded, it completely dies like I expect.

**Comment by ehollig** [comment]
Can not replicate this. MP3Tag exits fine on my system.
Mp3tag v2.78, released Jun 25 2016 
Windows 10,1607

**Comment by jcsteh** [comment]
Closing as worksforme as per above comment. Please reopen if the problem persists.
