### ISSUE TITLE
Unicode normalisation: It is not possible to find out which character is normalised when "normalized" is pronounced on character by character navigation while using one core, or maybe also some other synthesizers

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#16772]
### Steps to reproduce:
1. Enable unicode normalization in NVDA voice settings
2. Enable the checkbox "report "normalized" when moving by character"
3. Read following character with both e.g. one Core synthesizer and eSpeak
𝐂

### Actual behavior:
When using OneCore, NVDA reports "knormalized, without any pause between c and "normalized" so users don't know it is a letter c. This occurs also for symbols like d, f, etc. They are sticked together with the word "normalized".
In contrast, eSpeak reports "C,normalized", it pronounces the c as single letter and then the word "normalized".

### Expected behavior:
Pronounce the normalized symbol as such, and then the word "normalized". Maybe adding a short pause between the symbol pronounciation and the word "normalized" can solve this issue.

### NVDA logs, crash dumps and other attachments:
N/A

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-32650,405f9bfa (2024.3.0.32650)

#### Windows version:
Windows 11 23H2

#### Name and version of other software in use when reproducing the issue:
n/a

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
n/a

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
cc: @LeonarddeR

**Comment by Adriani90** [comment]
I think as of now one core synthesizer seems most impacted by this behavior.

**Comment by LeonarddeR** [comment]
I'm tempted to think that this is more of an issue in OneCore than in the normalization code, as the speech sequence looks okay to me:
`Speaking [PitchCommand(offset=30), 'cap ', CharacterModeCommand(True), 'C', CharacterModeCommand(False), ' normalized', PitchCommand(), EndUtteranceCommand()]`

**Comment by LeonarddeR** [comment]
It is actually an issue caused by the character mode commands being added that seem to screw up spacing in the resulting speech sequence.
