### ISSUE TITLE
Add a getObjectFromPointRedirect method on the NVDAObject class

### ISSUE THREAD

**Issue by Emil-18** [nvaccess/nvda#16788]
### Describe the solution you'd like
Add a getObjectFromPointRedirect method on the NVDAObject class that takes x and y coordinates as parameters and returns None in the default implementation. Call this method inside the objectFromPoint method, and send the x and y coordinates as parameters. If it returns an object, treat that object as the new objectFromPoint. In this way, add-ons can implement proper mouse reading and touch support for objects that has a location that differs from the location provided by the API class. This is useful if you for example are implementing support for a custom list control that don't support any accessibillity apis, and have to rely on win32 messages. The objectFromPoint method will normaly just return the root object. You could then implement getObjectFromPointRedirect on it to instead return the list item in that exact location.
### Describe alternatives you've considered
None

**Comment by LeonarddeR** [comment]
Could you please provide a real world use case for this? What prevents you from creating an overlay class that implements the location property appropriately?
