### ISSUE TITLE
When jumping between headings with lists, nvda lags

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1678]
**Reported by mreiser on 2011-07-17 18:45**
If you are in a list within a heading and you press H to jump to another heading that contains a list, nvda takes a second or two to respond to the key press.  Steps to reproduce:
1.  Open www.facebook.com if you are on facebook, and start navigating through the news feed.  
2.  Just keep pressing H until you hear it say "List with X visable items" this will indicate that you are on the next section of feed items.  

Expected results: nvda should just respond like usual and speak the next news item in the next list.  

Actual results: Nvda freezes for a few seconds before speaking the next item and sometimes jumps back to the previous item.  I've tested this with ie 9 and the latest firefox 6 beta, and am using 2010.2 beta3.

**Comment by leonardder** [comment]
I'm afraid I can't reproduce this. Much has changed in the last six years regarding to NVDA, Firefox and Facebook. I will leave this open for the next week for someone to come up with another str, and will close this at the end of next week if we haven't gotten any replies. After that, it is of course still possible to request a reopen.
