### ISSUE TITLE
Support for Java web applets

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#168]
**Reported by tbd on 2008-09-09 14:05**
I'm having trouble with other screenreaders and Java aplets on the internet when using online bancking. NVDA needs Java support then I could use it for almost everything I need when browsing the web. Will this bee possible one day?

**Comment by leonardder** [comment]
NVDA has proper JAVA support, and Java applets on the web are very rare nowadays. What to do with this? Is a won't fix justifiable?

**Comment by jcsteh** [comment]
I'm pretty sure we've seen this working with at least one Java applet. However, of the very few Java applets still in use in the wild, I'll wager very few of them are actually accessible. Also, [Firefox 52 and later](https://support.mozilla.org/en-US/kb/npapi-plugins), [Chrome 45 and later](https://www.java.com/en/download/faq/chrome.xml) and [Microsoft Edge](https://www.java.com/en/download/faq/win10_faq.xml) no longer support Java. Closing.
