### ISSUE TITLE
Enhancement NVDA+F to detect more information in Microsoft Word and Excel

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1680]
**Reported by jfauchon on 2011-07-19 13:22**
I understand that it may take time to do this but as I use Microsoft Word regularly with NVDA, I wish I could have access to this information. 
Too bad I can not help you because I do not know Python or I'll get you help with great pleasure because I am to improve so he can compete NVDA JAWS! 

You are doing a great job! 

I suggest to improve the function NVDA + F so that it can detect in all Microsoft Word versions: 
- The color of the police; 
- The color of the highlight; 
- The different types of highlighting; 
- If the text is shaded if it has contours, if it is raised or if there are borrowed; 
- If the character is lowercase or uppercase; 
- If the text is hidden; 
- The shading and color it; 
- The border and the color of it; 
- Withdrawals; 
- The line spacing; 
- The general alignment and vertical alignment in Microsoft Excel; 
- The height and width of the cell in Word and Excel; 
- The format cells in Excel; 

I suggest if possible to add a command (eg F + NVDA times) that will read the endnotes page, endnotes document, comments, saying if the cell contains a formula .. .

**Comment by feerrenrut** [comment]
Since most of this seems to be implemented I'm going to close this issue. If there are some missing features that are required, please open a new issue (one per feature), and provide an example document and the expected output. Thanks!
