### ISSUE TITLE
Remove linking code between `config.conf['documentFormatting']['reportFontAttributes']` and `config.conf['documentFormatting']['fontAttributeReporting']`

### ISSUE THREAD

**Issue by SaschaCowley** [nvaccess/nvda#16802]
### Is your feature request related to a problem? Please describe.

#16748 introduced new behaviour whereby NVDA can be configured to report font attributes in speech, braille, both or not at all. This required the implementation of a new configuration key, `documentFormatting.fontAttributeReporting`. To avoid a breaking change to the API, aliasing code was introduced to ensure that these two configuration keys are kept in sync.

### Describe the solution you'd like

Remove this code in release 2025.1.

### Describe alternatives you've considered

Leave the code there. It already does version checking, so won't run if the version is not 2024.x.

### Additional context

The only places that should need changing are:
https://github.com/nvaccess/nvda/blob/649c9e68d61c0e7ed74695254f8a6a4fb03090ce/source/config/__init__.py#L1287-L1310
https://github.com/nvaccess/nvda/blob/649c9e68d61c0e7ed74695254f8a6a4fb03090ce/source/config/configSpec.py#L208-L209

**Comment by beanieyi** [comment]
May I potentially take a look at this issue?

**Comment by CyrilleB79** [comment]
This issue is targeting NVDA 2025.1 since it's an API breaking change.
But alpha releases are now targeting 2024.4.

So you cannot tackle this issue until 2025.1 dev cycle has begun.

**Comment by SaschaCowley** [comment]
@beanieyi I will try and remember to ping you when it comes time to look in to actioning this.
