### ISSUE TITLE
Test plan for add-on update notification, may not work for real pending updates

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#16917]
With real add-on updates pending in the updates tab of the store, running the test plan for add-on update notifications, results in no update notification.
Update notifications are set to `notify` in the `add-ons` panel.

### Steps to reproduce:

In python console:

```
>>> import schedule
>>> schedule.jobs
[Every 1 day at 01:02:00 do callJobOnThread() (last run: [never], next run: 2024-07-27 01:02:00)]
>>> schedule.jobs[0].run()
>>> schedule.jobs
[Every 1 day at 01:02:00 do callJobOnThread() (last run: 2024-07-27 01:02:00, next run: 2024-07-28 01:02:00)]
```

### Actual behavior:

Nothing happens.

### Expected behavior:

According to the test plan, a window should appear, offering buttons which should be tested.

### NVDA logs, crash dumps and other attachments:

A side note: it seems to me that more should be logged about what the update notification is doing.

Log started just before `run()` was called:

```
IO - inputCore.InputManager.executeGesture (01:01:56.199) - winInputHook (13776):
Input: kb(desktop):enter
DEBUG - utils.schedule.callJobOnThread (01:01:56.199) - MainThread (37172):
Starting thread for job: _checkForUpdatableAddons on GUI thread
DEBUG - gui.addonStoreGui.controls.messageDialogs.UpdatableAddonsDialog._checkForUpdatableAddons (01:01:56.199) - MainThread (37172):
checking for updatable add-ons
DEBUG - addonStore.dataManager._DataManager._getCacheHash (01:01:56.199) - MainThread (37172):
Fetching add-on data from https://nvaccess.org/addonStore/cacheHash.json
IO - speech.speech.speak (01:01:56.645) - MainThread (37172):
Speaking ['>>>']
DEBUG - utils.schedule.callJobOnThread (01:02:00.127) - ScheduleThread (14396):
Starting thread for job: _checkForUpdatableAddons on GUI thread
DEBUG - gui.addonStoreGui.controls.messageDialogs.UpdatableAddonsDialog._checkForUpdatableAddons (01:02:00.127) - MainThread (37172):
checking for updatable add-ons
DEBUG - addonStore.dataManager._DataManager._getCacheHash (01:02:00.127) - MainThread (37172):
Fetching add-on data from https://nvaccess.org/addonStore/cacheHash.json
```

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2024.3beta4

#### Windows version:

11, 23H2, 10.0.22621.3235

#### Does the issue still occur after restarting your computer?

Not yet tested.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

N/A

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by XLTechie** [comment]
I think this was a red-herring.
Because the store was showing certain add-ons as updatable, I assumed that the update notification should consider them updatable as well.
However, I am now thinking that these were exclusively external add-ons, that the store knows how to update to store versions, but which apparently the update notifier does not recognize as updatable.

So the actual error here, is that add-ons which the store can update from external to store supported, do not show up in the update notification. Since that may be intended behavior for reasons I do not yet know, not having been able to follow the development of that feature very closely, I won't open such a report until I can investigate further.

**Comment by seanbudd** [comment]
@XLTechie - the current update notification just does same channel updates - e.g. stable to stable, beta to beta.
We intend to create a more comprehensive and flexible system for picking channels in 2024.4, but we figured this base case covered most peoples needs to start with.

**Comment by XLTechie** [comment]
@seanbudd what it misses, are people transitioning from Add-on Updater. Since Updater's installations are done as external add-ons, most add-ons on anyone's system who was using Updater, will be external, and thus not picked up by the core updater.

I was hoping for a more straight forward handover.

The only solution I know of currently, is to manually perform one update via the store interface, for each effected add-on.

**Comment by XLTechie** [comment]
cc @josephsl, for awareness.
