### ISSUE TITLE
Feature request: It is recommended to add the clean parameter to scons to clean up the residual files and directories of a local build.

### ISSUE THREAD

**Issue by dpy013** [nvaccess/nvda#16913]
### Is your feature request related to a problem? Please describe.
Currently, after building NVDA locally and testing it, some used directories are left behind, such as outputs, builds.
### Describe the solution you'd like
It is recommended to introduce a parameter to scons to clean up these used directories, and built files.
### Describe alternatives you've considered
Here, the cleanup can be temporarily parameterized as:
scons clean
### Additional context
none

**Comment by hwf1324** [comment]
Do you mean that `scons --clean` doesn't clean up enough and needs to clean up the environment more aggressively?

You can also use Git's `git clean -x` to clean the repository.

Or just want to clean the output directory?

**Comment by dpy013** [comment]
> Do you mean that `scons --clean` doesn't clean up enough and needs to clean up the environment more aggressively?
> 
> You can also use Git's `git clean -x` to clean the repository.
> 
> Or just want to clean the output directory?

Thank you for the information.
The problem was solved using git clean.
Also, I did not see any documentation on cleaning up the working directory in the project documentation directory.
