### ISSUE TITLE
Problems with The NVDA Snapshot which is alpha version 33085

### ISSUE THREAD

**Issue by BEdenhofer6** [nvaccess/nvda#16925]
When you unload jaws and go to launch NVDA, with alt control N? What happen's is, NVDA, and jaws, will launch at the same time. I can reproduce this problem, every time. I am not sure, if it's on freedom scientifics end, sense they are the ones, that make and develop jaws? Or, if this is an NVDA problem, itself.

Unload jaws, Press alt control N, to launch NVDA### Steps to reproduce:

jaws launches, each time, NVDA does### Actual behavior:

**Comment by BEdenhofer6** [comment]
This happen's, every time I restart my PC. I'm running windows11 and the latest version of NVDA, which is,NVDA version 2024.2

**Comment by seanbudd** [comment]
Welcome @BEdenhofer6 ,

We are unable to process this issue as it stands.

Please open a new issue and fill out the issue template fully.
Instructions for filling out the template are linked in the template and can also be found here: https://github.com/nvaccess/nvda/blob/master/projectDocs/issues/githubIssueTemplateExplanationAndExamples.md

Kind Regards,
NV Access Software Developers
