### ISSUE TITLE
nvda crashing on start

### ISSUE THREAD

**Issue by Kc9jjj** [nvaccess/nvda#16926]
start nvda

### Steps to reproduce:
start nvda
### Actual behavior:

dialog saying nvda crashed comes up
### Expected behavior:

start without crashing

### NVDA logs, crash dumps and other attachments:
[nvda log](https://github.com/user-attachments/files/16420890/nvda.log)

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2024.2
#### Windows version:
11 pro
#### Name and version of other software in use when reproducing the issue:
none
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
don't know

**Comment by Qchristensen** [comment]
There are quite a few add-on errors in that log.  Can you recreate the issue with add-ons disabled?

Press NVDA+r to open the Windows RUN dialog, type the following and press enter:
nvda --disable-addons

**Comment by Adriani90** [comment]
Did you run the COM registration fixing tool?

**Comment by Kc9jjj** [comment]
I did restart with no addons and still got the error. I didn't try running the com registration

**Comment by Kc9jjj** [comment]
I ran the com registration and still got the error

**Comment by CyrilleB79** [comment]
Could you provide a log without add-ons and still at debug level?

**Comment by seanbudd** [comment]
Welcome @Kc9jjj ,

We are unable to process this issue as it stands.
Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Please also provide a crash dump using the instructions from the link.

Kind Regards,
NV Access Software Developers

**Comment by Kc9jjj** [comment]
ok here they are
[nvda_crash.dmp](https://github.com/user-attachments/files/16451921/nvda_crash.dmp)

**Comment by Kc9jjj** [comment]
forgot this one

**Comment by Kc9jjj** [comment]
heres the other

**Comment by Kc9jjj** [comment]
heres the other
[nvda no addons.txt](https://github.com/user-attachments/files/16452034/nvda.no.addons.txt)

**Comment by seanbudd** [comment]
@Kc9jjj - that log has add-ons enabled. It also doesn't seem to include a crash. Are you sure that log is from a crash? You seem to be able to open and save a file after NVDA has started.

>dialog saying nvda crashed comes up

what dialog is coming up? can you copy the exact text?

**Comment by seanbudd** [comment]
In fact you've managed to run the com registration fixing tool. 
Is NVDA crashing every time on start up or only sometimes?
How have you managed to use log viewer or the com registration fixing tool?
Can you please define what a crash means to you and confirm the dialog message you are receiving.

**Comment by Kc9jjj** [comment]
The dialog says an error has occured press ok I press ok and it says a log has been created in a folder this was happening every time I started nvda but has seemed to have stopped after I ran a cleanup program. I am wondering about that one error that says something about usb how to fix it.

**Comment by SaschaCowley** [comment]
> The dialog says an error has occured press ok I press ok and it says a log has been created in a folder this was happening every time I started nvda but has seemed to have stopped after I ran a cleanup program. 

Without a log created when the crash occurs, we do not have enough information to further work out what is going on.

> I am wondering about that one error that says something about usb how to fix it.

A preliminary web search indicates that it is likely something to do with your Wifi/Bluetooth card. If everything is working as expected, I probably wouldn't worry about it.
