### ISSUE TITLE
Better reading of heading spanning multiple lines

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#16945]
### Is your feature request related to a problem? Please describe.

When in a webpage there is an heading N (N=level) with a long text spanning multiple lines, NVDA repeats "heading N" for each line, both reading with arrows and with say all.

Note that the spanning could happen simply due to text length, not to br tags.

Example:

### Describe the solution you'd like

I'd like a less intrusive messages, like "Start heading N" and "End heading N".

### Describe alternatives you've considered

None.

### Additional context

I'm using Firefox 128.0.3, don't remember what happens in Chrome.

In addition, I suspect this behavior relates to other HTML elements too.

**Comment by seanbudd** [comment]
Closing this in favour of #14335

We believe this is expeced behaviour when navigating via arrow keys, but should be fixed in Say all
