### ISSUE TITLE
Single anchor used two times in the user guide

### ISSUE THREAD

**Issue by pvagner** [nvaccess/nvda#16941]
### Steps to reproduce:

* Open this link: https://github.com/nvaccess/nvda/blob/47695acc3d71dfab3fc243714e5827de7472a5a1/user_docs/en/userGuide.md#L42-L48
* Look through line 42 and line 48

### Actual behavior:

Same anchor is defined twice. Thus it's not possible to link to individual headings Recommended system requirements or Minimum system requirements

### Expected behavior:

I have noticed this while translating user guide into slovak.
I think the anchor for Recommended system requirements should be changed into #RecommendedSystemRequirements`

#### NVDA installed/portable/running from source:

Not applicable. I am reading user guide in a web browser.

#### NVDA version:

Current development version

**Comment by josephsl** [comment]
CC @Qchristensen, while at it, I propose rewriting these sections to state the absolute minimum system requirements (for all users) before stating recommended system requirements. Another option is to present the system requirements as a table, with separate columns for minimum and recommended requirements. That way we can only deal with one anchor.

Thanks.

**Comment by Qchristensen** [comment]
Thanks @Pvagner for raising this - and you are right @josephsl - it makes sense to have the minimum requirements above the recommended requirements.  I've created PR #16959 to address both.
