### ISSUE TITLE
Document names not read when switching between open files in Visual studio 2022

### ISSUE THREAD

**Issue by LVamos** [nvaccess/nvda#16946]
### Steps to reproduce:

- Open a solution in Visual Studio 2022.
- Open some documents in the text editor
- Try to switch between the open files by holding the CTRL key and repeatedly pressing the Tab key.

### Actual behavior:

No speech or braille output from NVDA.

### Expected behavior:

NVDA should read names of the open documents.

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2024.3beta5   2024.3.0.33135

#### Windows version:
Windows 11 Pro 23H2        

#### Name and version of other software in use when reproducing the issue:
Microsoft Visual Studio Community 2022 64-bit v17.10.3

#### Does the issue still occur after restarting your computer?
yes

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by LVamos** [comment]
I found that NVDA only behaved like this in one particular solution. I tried other 3 solutions and the problem did not occur. After deleting the cache of the original solution, i.e. the .vs and obj folders, NVDA reads the document names properly. In my opinion, the problem occurs with some specific settings related to window layout.

**Comment by seanbudd** [comment]
Closing as this has been resolved.
It seems likely a bug with VS caching
