### ISSUE TITLE
Problem Navigating Bookmarks Folder Tree when Adding Bookmark in Firefox 3.6

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1695]
**Reported by m11chen on 2011-07-27 13:01**
Steps to reproduce:
1. Open any webpage with Firefox 3.6.
2. press Ctrl+D to open the Add to Bookmarks dialogue
3. Press tab to go to the bookmarks folder tree.
Expected result:
NVDA should be able to navigate the folder tree with arrow keys
Actual result:
NVDA can partially read the tree but the behavior is not very predictable, as it seem to skip some folders even though it exists in the tree.  Also pressing right arrow to expand a folder will sometimes cause focus to change to the next element in the dialogue instead of expanding the folder.

**Comment by ehollig** [comment]
I do not have this problem using Firefox 54.0.1. Lots of things have changed in Firefox since 3.6. Suggest closing unless someone can replicate this issue.
