### ISSUE TITLE
OCR

### ISSUE THREAD

**Issue by djblind** [nvaccess/nvda#16968]
It would be great, just like with JAWS, to choose whether the OCR will be performed on the entire screen, the window in focus, or even better, to be able to define a specific area of the screen. Thank you!

**Comment by seanbudd** [comment]
Welcome @djblind ,

We are unable to process this issue as it stands.

- Please fill out the issue template fully. Use the feature request template not the bug template.
- Many of those requests are already possible through [object navigation](https://www.nvaccess.org/files/nvda/releases/2024.2/documentation/userGuide.html#ObjectNavigation).

See also #12981 https://github.com/nvaccess/nvda/issues/11861

Kind Regards,
NV Access Software Developers
