### ISSUE TITLE
Notify when labels are changed in issues or pull requests

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#16979]
### Is your feature request related to a problem? Please describe.
When someone works on issues/pull requests, this developer needs to know when labels are added or removed, for example, if the issue has been triaged or the pull request is locked waiting for testing or product decision.
### Describe the solution you'd like
When labels are added or removed, a comment may be added so that followers of the issue can receive an email notification. For example: "Labels: triaged, p4, locked/needsTesting", etc.
### Describe alternatives you've considered
Developers can check this manually from time to time.
### Additional context

GitHub Actions may be used for this:

https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows

**Comment by nvdaes** [comment]
Hi @XLTechie . Can you provide links to documentation about filling issues with GitHub Accessibility? Your idea seems reasonable, if I have understood it well.

**Comment by XLTechie** [comment]
@nvdaes Perhaps start here: https://github.com/orgs/community/discussions/categories/accessibility
There is a pinned issue there for introduction, and you should be able to post something new.

**Comment by nvdaes** [comment]
Thanks @XLTechie . I've created this discussion:

https://github.com/orgs/community/discussions/135202

**Comment by CyrilleB79** [comment]
Apart of automatic notification, giving a reason is sometimes useful and not always done when needed. E.g. sometimes the blocked label is applied, but we do not always know why the issue / PR is being blocked.

**Comment by seanbudd** [comment]
Closing this as won't fix. Comments would be too noisy on this repository. Please provide feedback to GitHub for a proper solution
