### ISSUE TITLE
Support HID standard multi-line braille displays

### ISSUE THREAD

**Issue by alexmoon** [nvaccess/nvda#16993]
### Is your feature request related to a problem? Please describe.

The hidBrailleStandard driver currently does not support multi-line braille displays, such as Tactile Engineering's Cadence. It only finds the first braille row capability and ignores any subsequent rows. As a result, only the first line of braille cells is used on the display.

### Describe the solution you'd like

The hidBrailleStandard driver should detect all braille row capabilities and set numRows/numCols appropriately. This would allow NVDA to address all available braille cells and allow HID standard multi-line braille displays to support any future multi-line braille capabilities NVDA might add. I'm happy to create a PR to add this functionality.

### Describe alternatives you've considered

None.

### Additional context

USB standard [HID Usage Tables](https://usb.org/sites/default/files/hut1_5.pdf)

**Comment by michaelDCurran** [comment]
@alexmoon  If you have a physical display to test with, please open a pr by all means. I agree with your approach. I am currently in discussion with some other display manufacturers where I am proposing the same thing, so I am glad to see alignment.  Unfortunately so far I do not have a display that exposes this enhancement to test with.
