### ISSUE TITLE
In `ui.browseableMessage`, every other line is empty

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#16995]
### Steps to reproduce:
* Press NVDA+V to ensure screen layout is off.
* On a webpage, press 2 times NVDA+F
* Press many times down arrow
* Press NVDA+V to enable screen layout
* Press up/downArrows again to explore the lines

### Actual behavior:
Every other line is empty when screen layout is off.
### Expected behavior:
The content should not contain empty lines between useful lines; screen layout should not have any impact here.
### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Version : source-master-c8a847b (2024.4.0.0)
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Not tested, probably yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2024.3rc1 is OK, i.e. no such issue.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested, probably unrelated.

### Notes
This issue is very likely introduced by #16369. Cc @XLTechie.
Thus #12004 has been reintroduced unfortunately.

**Comment by XLTechie** [comment]
Unfortunately, there were security concerns about the solution used by #12005 (though I was unaware of #12004, so did not take its solution into account).

I will investigate a new solution.

**Comment by XLTechie** [comment]
I think part of the problem might be in the C code, specifically in `NVDAHelper.localLib.VBuf_getLineOffsets`.
I might be able to figure out what's going on there (my C is very rusty, but I may remember enough), but at the moment I can't find where the code for that function is. Can anyone with more recent C experience point me to this?
I see that it is exported in `nvdaHelper/local/nvdaHelperLocal.def`, but that's as much as I have learned.

Probably not an approved use, but maybe I can ask @coderabbitai where the source code for `NVDAHelper.localLib.VBuf_getLineOffsets` can be found?

**Comment by michaelDCurran** [comment]
It looks like MSHTML converts line feeds into `<br>` tags within a `<pre>` tag. I didn't think this is what a browser was supposed to do. pre tags should have plain text, and no other elements.
Assuming we're not doing anything wrong here in the way we are inserting the message, we might need to change mshtml VBufBackend's fillVBuf  to replace br tags with `\n` assuming we are not already doing that. Right now I'm guessing we are rendering a br tag as a block-level element with a `\n` inside.  
File: nvdaHelper/vbufBackends/mshtml/mshtml.cpp

**Comment by XLTechie** [comment]
@michaelDCurran regarding your comment above, this only happens to `<pre>` newlines, while in screen layout off mode. That suggests to me, that it's not the browser's fault.

I tried various changes in the MSHTML VBuf code per your suggestion, but could not figure out where this is handled differently for screen layout off, vs. screen layout on. Regardless, nothing I tried was successful.
