### ISSUE TITLE
NVDA+f browseable message - pressing alt+c makes a ding

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#16996]
Follow-up of #16369; cc @XLTechie.
### Steps to reproduce:
* Press NVDA+f twice on a formatted text, e.g. in a webpage
* Press alt+c
### Actual behavior:
NVDA says "Text copied", a "ding" sound is heard and the text is actually in the clipboard.
### Expected behavior:
NVDA says "Text copied" and the text is actually in the clipboard.
But no "ding" sound should be heard. This sound is quite unusual when pressing alt+letter to activate a button and this may let think that there has been an error.
### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
Source
#### NVDA version:
Version : source-master-c8a847b (2024.4.0.0)
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Not tested; probably yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested; probably unrelated.

**Comment by XLTechie** [comment]
@CyrilleB79 This is coming from MSHTML, because Alt+C is not a key sequence it knows, even if its contained javascript does. Nothing I know of can fix this, but if you know of something I'd be happy to implement it.

The alternative is to change the key to something that doesn't ding, which probably means a sequence without alt.

**Comment by seanbudd** [comment]
@XLTechie - can you open a PR to revert #16369 ? Please use the new revert template https://github.com/nvaccess/nvda/blob/master/.github/PULL_REQUEST_TEMPLATE/revert.md
