### ISSUE TITLE
Word 2003 status bar not vound

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1699]
**Reported by ghoath on 2011-08-01 04:50**
In Word 2003, the status bar is never found with NVDA key + End. This is with the Word window restored or maximised. 

It can't be found in the normal object navigation. Flat review has to be activated, and then NVDA key + numpad 6 until it is found.

**Comment by leonardder** [comment]
Word 2003 is very old. I'd close this as won't fix if it wasn't a duplicate of #649. So, closing anyway.
