### ISSUE TITLE
Lint/format C++ code

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/nvda#17009]
### Is your feature request related to a problem? Please describe.
Multiple code styles are mixed in NVDA's C++ code

### Describe the solution you'd like
Apply auto linting/formatting to the code base, similar to what we do with Ruff.

### Describe alternatives you've considered
Leave as is.

### Additional context
I have experimented with clangformat in https://github.com/jcsteh/osara/pull/940 . The idea there is to find a format that minimized changes to OSARA's code base. However, there were several side effects to clangformat that resulted in pretty ugly results with spacing. I'm therefore not sure clangformat is the way to go.

CC @seanbudd

**Comment by seanbudd** [comment]
Closing in favour of https://github.com/nvaccess/nvda/issues/12407
