### ISSUE TITLE
Include NVDA-VSCode as a Submodule

### ISSUE THREAD

**Issue by SaschaCowley** [nvaccess/nvda#17003]
### Is your feature request related to a problem? Please describe.

Many developers, including vision impaired developers, use Visual Studio Code as their IDE of choice. As NVDA is a complex project, getting all aspects of the project working with VS Code can be tricky. The [vscode-nvda repository](https://github.com/nvaccess/vscode-nvda) exists to solve some of these difficulties, by recommending extensions and configurations that are helpful when working on NVDA in VS Code. However, many users may not know about this resource.

### Describe the solution you'd like

Include the vscode-nvda repo as a submodule of the NVDA repo.

### Describe alternatives you've considered

- Move the `.vscode` directory into NVDA. This is not ideal, as:
  - Users may want to customise their vscode config, and keeping a submodule dirty is easier than keeping part of the superproject dirty
  - The VS Code config isn't really part of NVDA, and including it in NVDA would confuse NVDA development with development of tooling configurations
- Keep the config where it is, but ensure it is mentioned more prominently in the developer documentation.
- No change.

### Additional context

The configuration repo was initially created in response to #9971, which was closed by #10064. Since then, VS Code has matured a lot, and NVDA's own developer docs have increasingly leant toward VS Code as the preferred IDE, as pointed out in https://github.com/nvaccess/nvda/pull/16971#issuecomment-2274164561.

**Comment by LeonarddeR** [comment]
I second this idea to make it a sub module!
