### ISSUE TITLE
Wide characters break caret position reporting in PowerPoint

### ISSUE THREAD

**Issue by SaschaCowley** [nvaccess/nvda#17006]
### Steps to reproduce:

1. Open a PowerPoint presentation.
2. In a text box, insert text which includes wide characters, such as "Hello💻world".
3. Use the arrow keys to navigate the text. Notice that "💻w" is reported as a single character.

### Actual behavior:

```
cap   H
right arrow
e
right arrow
l
right arrow
l
right arrow
o
right arrow
💻w
right arrow
o (caret is actually to the left of 'w')
right arrow
r (caret is actually to the left of 'o')
right arrow
l (caret is actually to the left of 'r')
right arrow
d (caret is actually to the left of 'l')
right arrow
blank (caret is actually to the left of 'd')
right arrow
blank (caret is actually to the right of 'd')
```

### Expected behavior:

NVDA should report '💻' and 'w' separately, and should accurately report the position of the caret, even after wide characters.

### NVDA logs, crash dumps and other attachments:

N/A

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

alpha-33355,52559a9c (2024.4.0.33355)

#### Windows version:

Windows 11 23H2 (OS Build 22635.4005)

#### Name and version of other software in use when reproducing the issue:

Microsoft® PowerPoint® for Microsoft 365 MSO (Version 2407 Build 16.0.17830.20056) 64-bit 

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by LeonarddeR** [comment]
This should be an easy fix. Encoding should be set to None on the TextInfo class.
