### ISSUE TITLE
NVDA and HTML tables

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1702]
**Reported by andre14 on 2011-08-01 11:22**
Some HTML tables are long enough to traverse column by column.
One option for reading the tables line by line would be a good alternative to this problem.
P.S: sorry I'm french.

**Comment by dkager** [comment]
You can read row-by-row with ctrl+alt+rightArrow. Then when you reach the last cell of the row, hit downArrow to jump to the first column of the next row and repeat.

**Comment by jcsteh** [comment]
#1911 discusses commands to read entire rows and columns.
