### ISSUE TITLE
Canvas with role img is read as "clickable"

### ISSUE THREAD

**Issue by teodorachiosa** [nvaccess/nvda#17031]
Context: Using canvas to display charts.

### Steps to reproduce:
1. Go to this CodePen link: https://codepen.io/teodorachiosa/pen/dyBdVPP
2. Navigate with arrows to the 2 canvas elements in the page to hear how they are read. The second canvas is read as "graphic clickable".

### Actual behavior:
When the canvas contains click interaction, "clickable" is mentioned. I understand this is default behavior and it's automatically detected.

But this is flagged as an accessibility issue by Firefox for example, in the accessibility tree.

Below is an image of the Firefox Accessibility tab, which shows a "keyboard" tag for my canvas, with an error message saying "Clickable elements must be focusable and should have interactive semantics". But I don't want this to be focusable, I want to present it as an image.
![image](https://github.com/user-attachments/assets/d64d5d7b-8d1a-4f75-809d-ee53d16113fd)

```
frame    Focus starter  button  
down arrow
heading    level 2  Example 1:
down arrow
Doesn't announce "clickable" - good ✔
down arrow
graphic    My description  Pie chart showing the most popular Primary Desktop/Laptop Screen Reader: JAWS with 619 answers, 
down arrow
graphic    My description  NVDA with 577 answers, VoiceOver with 148 answers, Dolphin SuperNova with 57 answers, 
down arrow
graphic    My description  ZoomText/Fusion with 41 answers, Orca with 36 answers, Narrator with 10 answers, Other with 41 
down arrow
graphic    My description  answers  

down arrow
heading    level 2  Example 2:
down arrow
Announces "graphic clickable" - confusing. ❌ Detects click interaction in canvas, but canvas isn't 
down arrow
accessible. I expect adding role img and alternative text to my chart in the form of aria-label or 
down arrow
an adjacent table to be a good alternative to using inaccessible canvas.
down arrow
Click the canvas below:
down arrow
graphic  clickable    My description  Pie chart showing the most popular Primary Desktop/Laptop Screen Reader: JAWS with 619 answers, 
down arrow
graphic  clickable    My description  NVDA with 577 answers, VoiceOver with 148 answers, Dolphin SuperNova with 57 answers, 
down arrow
graphic  clickable    My description  ZoomText/Fusion with 41 answers, Orca with 36 answers, Narrator with 10 answers, Other with 41 
down arrow
graphic  clickable    My description  answers  

```

### Expected behavior:
I expect that, since canvas isn't accessible, I can add role="img" to the canvas, add a label for the canvas and, for canvases with interaction, I plan to use an adjacent table that contains canvas data and buttons to functionalities (so that mouse users and keyboard users have access to the same features).

The fact that this canvas is read as "clickable" is confusing to users, especially since my canvas is also intentionally not focusable.

I expect to be able to tell screen readers that my canvas is simply an image (non clickable, non interactive) and provide my own interaction alternative (as said before, in a table for example).

#### NVDA installed/portable/running from source:
https://www.nvaccess.org/download/

#### NVDA version:
2024.3 (2024.3.0.33433)

#### Windows version:
Windows 10

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment]
cc: @jcsteh since it is flagged in Firefox accessibility tree.

**Comment by jcsteh** [comment]
> When the canvas contains click interaction,
> ...
> "Clickable elements must be focusable and should have interactive semantics". But I don't want this to be focusable, I want to present it as an image.

These two things are fundamentally contradictory. If the canvas contains click interaction, it is therefore interactive. That also means it isn't just an image and needs to be focusable in some way in order to be operable for keyboard users.

You can violate this rule of course, but then you need to choose to deliberately ignore the Firefox error, which is trying to prevent you from making a control with inaccessible behaviour.

**Comment by Adriani90** [comment]
In case the canvas is indeed interactive even if it is an image, this should be focusable, I agree with Jamie.
Closing as invalid:
