### ISSUE TITLE
Stop interrupting users' work with suddenly appearing windows

### ISSUE THREAD

**Issue by cyrmax** [nvaccess/nvda#17037]
### Is your feature request related to a problem? Please describe.
Recently added feature to check for add-on updates on every startup of NVDA bothers users with suddenly opening window. It doesn't mater if you are in a hurry typing some report or very quickly answering to something important. It doesn't mater if you are in an online shooter and you are killed while trying to close this window. It appears and annoys users, interrupting any action you were doing before.

### Describe the solution you'd like
My idea is to switch from this big window to a Windows notification which will just play its sound, will be announced by NVDA, and then user decides to open it or update their add-ons via add-on store tool.

### Describe alternatives you've considered
As an alternative solution there could be a checkbox to disable this add-ons update check on start up. And this checkbox should be disabled by default because this behavior can surprise and confuse users.

### Additional context
N/a

**Comment by XLTechie** [comment]
@cyrmax wrote
> As an alternative solution there could be a checkbox to disable this add-ons update check on start up.

Change the combobox under NVDA Preferences, Settings, Add-on Store, from "notify" to "disabled".
Problem solved.

> And this checkbox should be disabled by default because this behavior can surprise and confuse users.

If they are surprised or confused, they can turn it off, as described above, and in the user guide.

This feature was prominently mentioned in the changes/what's new for NVDA, as well. Most users shouldn't be surprised by it.

If users don't like it, they should read about it in the user guide, and learn how to turn it off, as with any NVDA feature.
Although, given how popular the Add-on Updater has been for years, I doubt that many will turn it off.

If it was turned off by default, they wouldn't know to read about it. It is hard to notice an absence.

The option for toast notifications is planned for the future.

**Comment by CyrilleB79** [comment]
@XLTechie wrote:
> The option for toast notifications is planned for the future.

Is it described in another issue? If yes, we can close this issue as duplicate, can't we?

**Comment by XLTechie** [comment]
> Is it described in another issue? If yes, we can close this issue as duplicate, can't we?

If memory serves, Sean mentioned it when explaining why it was a combobox instead of a checkbox, so probably in the comments of the Update Notifications PR.
