### ISSUE TITLE
Allow disabling updates via registry key

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#17046]
### Is your feature request related to a problem? Please describe.

My company has an internal toolchain for managing installs of software on corporate systems. Recently, we added NVDA to this toolchain. The toolchain allows us to push updates to the fleet after validating new updates, as well as ensuring that our security software plays nice with NVDA. However, at the current moment, NVDA only allows disabling the update checker from a config setting, and not via corporate managed toolchains. I.E. the update checker disables updates as a per-user setting. This requires every user to disable automatic updates, or requires our install script to modify the user's config, which is risky.

### Describe the solution you'd like

We propose adding a registry key that would disable the update check functionality, so that our toolchain can manage automatic updates. There's nothing wrong with the built-in updator for the vast majority of users, we just do the updates internally, and thus the updator popping up for users is a bit annoying.

### Describe alternatives you've considered

We've thought about modifying the users ini files locally with our script.
However, other companies that manage updates may well wish to update NVDA in this way as well, and will need to disable the update checker. Also, as a matter of policy, changing users local configs without their express consent is less than ideal, and if corrupted, could be a problem. 

## additional

I am happy to contribute a pull request for this change, once the implementation details are considered reasonable by NV Access.

**Comment by seanbudd** [comment]
Closing in favour of #16599 
A registry key here would not actually prevent updates, it would just work similarly to a config item, as add-ons or other custom code would enable getting around it.
As you say, if this is for "annoyance" reasons, not security reasons, I would encourage setting the config item directly. An add-on or similar which sets the config value as desired is probably the safest solution.

**Comment by alexhass** [comment]
Ähhh what? I need a registry key to disable updates. I‘m installing the update, the users do not have permissions to do so and should not get annoyed by the popups I see now for 2025.1.1
