### ISSUE TITLE
The ability to enable or disable Wasapi should not appear in a configuration profile

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#17041]
### Actual behavior:

- launch NVDA and in the "advanced" category of NVDA settings, check that Wasapi is activated for the "normal configuration " profile.
- launch notepad and create a profile for notepad.
- disable Wasapi for this profile and save the configuration.
- as requested, restart NVDA

We then see that Wasapi is activated using the "Audio" category.
By putting focus on Notepad if it is not, in principle Wasapi should be disabled. 
This is not the case. 

### Expected behavior:

The Use WASAPI for audio output option should not appear in a profile configuration.
#### NVDA installed/portable/running from source:
nvda portable
#### NVDA version:
nvda 2024.3
#### Windows version:
W10
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, but I guess it's been around since Wasapi was introduced in NVDA.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment]
There is no reason why WASAPI should be disabled, actually the request is to remove this setting from the advanced pannel all together. This is triaged in #16080. cc: @SaschaCowley, @seanbudd, @jcsteh.

**Comment by CyrilleB79** [comment]
Even if WASAPI removal is merged, there is probably the same issue with "Use enhanced event processing (requires restart)".

And it would probably make sense to make also global the option "Enable loading custom code from Developer Scratchpad directory". Technically, you can change this setting in a profile and have it honoured when reloading plugins (NVDA+control+F3). However, this corner case does not correspond to any normal use case and should be removed IMO.

**Comment by paulber19** [comment]
How do I know that there is no point in disabling Wasapi if NVDA allows 
you to do so?
As a reminder, since Wasapi is enabled by default, there seem to be 
auto-sleep issues.
So it is normal to have the possibility of being able to deactivate 
Wasapi to carry out tests.
The fact that it's a configuration profile option confuses things.

**Comment by jcsteh** [comment]
This is probably a valid bug, albeit a low priority one. When you use the advanced settings panel, you accept some risks, are expected to know what you're doing (or be asked by a developer to do something specific) and should expect that certain things won't behave as you think they will. That said, if WASAPI is removed, this particular instance of this bug will obviously be moot.

**Comment by SaschaCowley** [comment]
Note: Removed extraneous issue body from the issue title

**Comment by CyrilleB79** [comment]
We probably have the same issue for "Use enhanced event processing (requires restart)" option.

And I'd also say that we should also include "Enable loading custom code from Developer Scratchpad directory" when solving this issue. Even if technically we are able to honour this setting when a profile is active when reloading plugins (`NVDA+control+f3`), I do not consider this corner case a valide use case, i.e. there is no valide use case to use this setting in a profile IMO.

**Comment by paulber19** [comment]
How do I know that there is no point in disabling Wasapi if NVDA allows 
you to do so?
As a reminder, when Wasapi is deactivated, automatic standby occurs 
without problem.
Best regards.

**Comment by seanbudd** [comment]
Closing in favour of #16080

**Comment by CyrilleB79** [comment]
@paulber19 wrote (in a comment hidden as "duplicate"; by the way, this comment is not duplicate, but rather off-topic IMO):
> How do I know that there is no point in disabling Wasapi if NVDA allows you to do so? As a reminder, when Wasapi is deactivated, automatic standby occurs without problem. Best regards.
If there are remaining issues blocking the use of WASAPI, they should be reported (if not already), and mentioned in #16080.
From what I read in #16080, there is no more blocking issue to remove the choice between WASAPI and winmm for now. Please comment there if needed.
