### ISSUE TITLE
Speech Stops when I Open a Folder located on a Thumb Drive

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1705]
**Reported by dgoldfield on 2011-08-04 14:46**
The following happens consistently on my XP Pro machine.
1.  With a thumb drive inserted I go to the run dialog with Windows key and the letter r.
2.  I type f: and press enter to bring up the folder list on that drive.
3. At this point NVDA seems to freeze and I get no speech.
At that point I attempt to terminate and restart NVDA with the ctrl-alt-N hotkey.
I press the hotkey once and I do not usually hear the descending tones indicating that NVDA has stopped.
I then press it again and hear the ascending tones indicating that NVDA has started again.  Everything is fine now and I can then alt-tab to the thumb drive's directory with normal reading.

I am using a very slow computer with Microsoft security Essentials running; not sure if that's helpful.

**Comment by ehollig** [comment]
I am not sure if there is enough information provided here to replicate. I do not have issues bringing up flash drives from the run dialog. Maybe I am missing something? I am using Windows 10, although the original poster is using XP.

**Comment by Brian1Gaff** [comment]
I have never been able to duplicate this here, so if the original person 
cannot add more detail, we are a bit stuck.
 I do know that there can be times where the focus gets to the wrong part of 
an explorer window in any flavour of Windows, but XP is pretty benign on 
this. On other systems sometimes if  you cannot get permission to view a 
particular drive then often the folder is blank even though there are files 
there, its just not allowed and usually a message tells you so.
 Brian

**Comment by jcsteh** [comment]
No feedback from original reporter. Closing as worksforme as per above comments.
