### ISSUE TITLE
Problem with the HIMS display line Braille Sense 6 Mini 

### ISSUE THREAD

**Issue by josevan** [nvaccess/nvda#17066]
[nvda josevanf.log](https://github.com/user-attachments/files/16769421/nvda.josevanf.log)

**Comment by Adriani90** [comment]
Please fill the template properly. This cannot be investigated further.

**Comment by CyrilleB79** [comment]
@josevan in addition to @Adriani90's remark which still stands, beware that Braille Sense 6 Mini works with NVDA 2024.1 but not with NVDA 2024.2 and above.

See #16641 and more specifically https://github.com/nvaccess/nvda/issues/16641#issuecomment-2301269246 for more details.

Cc @EdKweon FYI.
