### ISSUE TITLE
custom symbol groupings

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1708]
**Reported by mehgcap on 2011-08-05 19:13**
The new symbol settings are great. I would like to see it taken one step further, by allowing users to define different punctuation schemes. For instance, I might want parentheses, braces, and the like spoken when writing programming code, but not when reading a webpage, while editing a wordprocessor document could require a different set of symbols. My suggestion, therefore, is to allow the user to create a new punctuation group in addition to the four standard ones, then add symbols. A keystroke to quickly cycle through the available groups, or to bring up the punctuation settings dialog, would be very helpful if this were implemented. Even if it were not, though, such a keystroke would be great to have. Currently, I treat the "most" setting as my programming setting and "some" as my reading setting. The ability to quickly, and globally, toggle between the two would be wonderful.

**Comment by bhavyashah** [comment]
If I understand mehgcap  correctly, shouldn't this be possible via customized symbol pronunciations for an app-specific profile? CC @brian1gaff and @jcsteh to elucidate

**Comment by jcsteh** [comment]
I think profiles are the correct way to deal with this. You could trigger profiles for specific apps or manually switch profiles. There are open requests for faster manual switching of profiles (though I don't have issue numbers offhand). Closing as won't fix.

**Comment by ehollig** [comment]
One of the issues you are looking for is #4209
