### ISSUE TITLE
Windows 24H2 update KB5041865 breaks support for 1Password

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/nvda#17086]
### Steps to reproduce:
1. Install Windows 24H2 2024-8 preview update KB5041865
2. Start 1Password

### Actual behavior:
NVDA reports `Chrome legacy Window` all over the place

### Expected behavior:
NVDA reads 1Passwords interface normally.

### NVDA logs, crash dumps and other attachments:
No relevant information in there. `NVDAObjects.IAccessible.getNVDAObjectFromEvent` just returns an IAccessible object rather than an IAccessible2 one. Querying IAccessible2 on this object is not supported.
Also note that when NVDA is running as administrator, it is able to read 1Password's interface just fine.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-33623

#### Windows version:
Version 24H2 (OS Build 26100.1591

#### Name and version of other software in use when reproducing the issue:
1Password 8.10.40, both machine level and user level versions.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, NVDA 2024.3

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by LeonarddeR** [comment]
On another system, I have this update installed and there, the issue does not occur. It must be something else, though it is still worrying.
Closing until I have more relevant details, in which case I will open a new issue.

**Comment by CyrilleB79** [comment]
@LeonarddeR FYI, you probably ment to close this issue but it is still open.

**Comment by LeonarddeR** [comment]
thanks @CyrilleB79
