### ISSUE TITLE
Treegrid - row description narrated for each gridcell while navigating in the column  

### ISSUE THREAD

**Issue by kolaps33** [nvaccess/nvda#17081]
### Steps to reproduce:
1. Run NVDA
2. Navigate into example: https://codepen.io/kolaps33/pen/poXZYea
This example is the same as the one from ARIA:
https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/examples/treegrid-1/ 
Only description was added for each row.
4. Navigate in the first row into email column: "CTRL+ALT+Arrow " using NVDA in browse mode
5. Navigate down in the column with using CTRL+Alt+Down arrow key

### Actual behavior:
NVDA narrates:
more description available  level 2  row 3  link    joe@blahblahblah.blahblah
Comment: NVDA narrate row description when user navigates through the column up and down.

### Expected behavior:
NVDA should narrates:
level 2  row 3  link    joe@blahblahblah.blahblah
Comment: NVDA shouldn't narrates row description.  

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2024.3

#### Windows version:
OS Name	Microsoft Windows 11 Enterprise
Version	10.0.22631 Build 22631

#### Name and version of other software in use when reproducing the issue:
Chrome Version 128.0.6613.86 (Official Build) (64-bit)

#### Does the issue still occur after restarting your computer?
YES 

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No 

#### If NVDA add-ons are disabled, is your problem still occurring?
YES

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Didn't try.

**Comment by seanbudd** [comment]
This is intended behaviour. Can you please explain in detail why the behaviour you're expecting is desired.
