### ISSUE TITLE
[BUG] NVDA become extremely laggy and freeze when reading page.

### ISSUE THREAD

**Issue by mo29cg** [nvaccess/nvda#17088]
### Steps to reproduce:
https://docs.stripe.com/js
This is the official documentation of stripe.
Using chrome or firefox, go to the link above, and navigate on the page by pressing "H" or/and arrow keys.

### Actual behavior:
NVDA become extremely laggy and inresponsive.

### Expected behavior:
NVDA keep responding with normal speed.

### NVDA logs, crash dumps and other attachments:
None

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2024.1

#### Windows version:
windows 11

#### Name and version of other software in use when reproducing the issue:
Google chrome Version 128.0.6613.86 (Official Build) (64-bit)
Firefox
#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
How is it with NVDA 2024.3 beta?

**Comment by SaschaCowley** [comment]
@Adriani90 NVDA 2024.3 is out. We are now in the beta phase of 2024.4.

**Comment by SaschaCowley** [comment]
@mo29cg Can you please try to reproduce this in NVDA 2024.3? I experienced no lag when exploring the linked page in Firefox.

**Comment by seanbudd** [comment]
This is a problem without a screen reader in use. The page is extremely large and slow to load.
