### ISSUE TITLE
Braille: zero division error while using "speech output" mode

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#17092]
### Steps to reproduce:
After installing recent alpha build (33644 and later), press Alt+NVDA+T to toggle braile mode between "follow cursors" and "speech output".

### Actual behavior:
A zero division error is logged when braille mode is switched to "speech output".

### Expected behavior:
No errors

### NVDA logs, crash dumps and other attachments:
Log fragment (on alpha-33656,35e31582):
ERROR - extensionPoints.Action.notify (18:48:53.927) - MainThread (18176):
Error running handler <bound method BrailleHandler._showSpeechInBraille of <braille.BrailleHandler object at 0x06258ED0>> for <extensionPoints.Action object at 0x042FC250>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 56, in notify
  File "extensionPoints\util.pyc", line 216, in callWithSupportedKwargs
  File "braille.pyc", line 2471, in _showSpeechInBraille
  File "braille.pyc", line 2057, in update
  File "braille.pyc", line 1884, in _get_windowStartPos
  File "braille.pyc", line 1874, in windowPosToBufferPos
ZeroDivisionError: integer division or modulo by zero

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-33656,35e31582

#### Windows version:
Windows 11 24H2 Insider dev (build 26120.1542)

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
Used as a development workstation

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Started with alpha-33644,cee553df - no issues with 2024.3 and 2024.4 beta

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not applicable

CC @MichaelDCurran, likely something coming from word wrap handling for multi-line displays.

**Comment by ruifontes** [comment]
Can't reproduce.
Same NVDA version, but Windows is 23H2 (22631.4112)
With or without add-ons activated.

**Comment by Emil-18** [comment]
@josephsl I could reproduce it when I didn't have the braille viewer open and didn't have a braille display connected. When I had the braille viewer open, it worked fine. I suspect it also would have worked if I had a braille display connected. I think a way to fix this is to check if braille.handler is enabled from within the extention point that displays the speech output, and if it isn't, return without doing anything, like all other functions in NVDA that displays braille does.
