### ISSUE TITLE
Add-on store: if the add-on download fails, you should be able to re-download the add-on

### ISSUE THREAD

**Issue by hwf1324** [nvaccess/nvda#17090]
### Is your feature request related to a problem? Please describe.

When the add-on fails to download, it could simply be the network, and when I configure the network and want to retry the download, the fastest way to do it would be to switch to the other tab on the way back, which is cumbersome and not intuitive.

### Describe the solution you'd like

Add “Retry”/“Redownload” Action when the add-on fails to download.

**Comment by seanbudd** [comment]
I think the install action should just be allowed in this case, rather than making a new action

**Comment by hwf1324** [comment]
> I think the install action should just be allowed in this case, rather than making a new action

That's great, but it seems a bit difficult to realise.

My general idea is to re-determine the available Actions via `getStatus` when fetching the available Actions when the status of the add-on is Download Failed.

But it seems that I have to add some tedious code if I want to get the external context in the abstract model.

**Comment by seanbudd** [comment]
@hwf1324 -  I think this patch should cover the issue

```py
AddonActionVM(
  # Translators: Label for an action that retries the selected addon
  displayName=pgettext("addonStore", "&Retry"),
  actionHandler=self.getAddon,
  validCheck=lambda aVM: aVM.status in {AvailableAddonStatus.DOWNLOAD_FAILED, AvailableAddonStatus.INSTALL_FAILED},
  actionTarget=selectedListItem,
),
```
