### ISSUE TITLE
Opt new PRs out of Code Rabbit by default

### ISSUE THREAD

**Issue by codeofdusk** [nvaccess/nvda#17112]
### Steps to reproduce:
1. Observe Code Rabbit summaries of several recent PRs. Examples are far too numerous to list here, but some selections:
* #17104: Mentions changes to the exit dialogue that aren't included in this PR.
* #17080: mentions command line and eSpeak updates that aren't included in this PR.
* #17048: mentions update to the Seika Notetaker driver that aren't included in this PR.

### Actual behavior:
PR summaries are being generated without user prompting. These summaries suggest that unrelated (but plausible) changes are being included in PRs, which could be extremely misleading.

### Expected behavior:
* No AI summaries are generated without explicit user request.
* When AI summaries are generated, only relevant changes are included. This may be very difficult given the nature of large language models.

**Comment by seanbudd** [comment]
@codeofdusk - we coincidently had a similar conversation this morning
