### ISSUE TITLE
in the gpt chat application when accessing the menu bar nvda takes a long time to respond

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#17111]
### Steps to reproduce:
install application to access gpt chat for free at the link:

https://sourceforge.net/projects/chatgpt-desktop.mirror/

After installing the application, open it and press the alt key to access the application's menu bar.
### Actual behavior:
nvda takes approximately 15 seconds to speak some information.

### Expected behavior:
nvda should respond quickly as it does in all other areas.
I tested and did not encounter this issue in narrator.

#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-33778,b6d08a0d

#### Windows version:
10.0.19045.4780
and
windows 11 24600.
#### Name and version of other software in use when reproducing the issue:
chat gpt 1.1.0
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
[gpt.txt](https://github.com/user-attachments/files/16852387/gpt.txt)

**Comment by seanbudd** [comment]
Closing as won't fix. This is very likely a problem with the implementation of the application/website, as a starting point please submit feedback to the authors to let them know about the problem.
