### ISSUE TITLE
Improve the report link feature

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#17127]
### Is your feature request related to a problem? Please describe.
Links to the same page are reported for `http` and `https` schemes, and this doesn't include local files like the NVDA's user guide.
### Describe the solution you'd like
Same page links should be reported also for local files.
### Describe alternatives you've considered
Report link types just for non local webpages.
### Additional context
This feature has been included in pr #16994, to fix issue #141.

Other refinements may be suggested in the future. For example, when we see if this works consistently in webpages with query parameters and if this should be improved for such wwebpages..

**Comment by amirsol81** [comment]
If implemented for local files and CHM help systems, this would make such announcements more consistent. JAWS also covers these instances.

**Comment by nvdaes** [comment]
I'll create a PR  when this is triaged.
For me it has been a good idea to merge this early, so that it can be tested by more users.
I'm testing locally with the proposed changes enabling the reporting of same page links in the user guide.
I've also tested removing query parameters for comparison between root and target URL, but I think it's better not to remove them, even when some same pages in certain cases aren't identified as such if query parameters are found.

**Comment by XLTechie** [comment]
To a user, a web page is a web page, whether it is local or remote. So I support this issue.

On the other topic: There is too much potential for query strings to change what the page displays. Better not to risk it.

**Comment by nvdaes** [comment]
Luke wrote:

> To a user, a web page is a web page, whether it is local or remote.

This reasoning is almost undebatable for me.
Let's wait for this to be triaged.
