### ISSUE TITLE
Voice breaking in particular circumstances

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#17131]
From time to time, I ran into this issue, but only today occurred a situation that could provide a explanation.

I was reading something (a mail, a web page, I don't remember), and maybe I stopped the voice and then received one or more notify by WhatsApp app, or first I received a first notify and then stopped voice, I don't remember exactly. From that moment, voice completely disappeared (log provided below).

I don't know whether it's important, but I use WASAPI in NVDA, even if I disabled exclusive mode checkboxes in current audio device properties.

### Steps to reproduce:

Unable to provide.

### Actual behavior:

Voice disappeared, until I restarted NVDA.

### Expected behavior:

Voice should recover itself without restarting NVDA.

### NVDA logs, crash dumps and other attachments:

```
ERROR - logHandler._threadExceptHook (13:48:18.521) - Thread-2 (14032):
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "C:\Users\Admin\AppData\Roaming\nvda\addons\Eloquence\synthDrivers\_eloquence.py", line 109, in run
    player.stop()
  File "nvwave.pyc", line 978, in stop
  File "_ctypes/callproc.c", line 1000, in GetResult
OSError: [WinError -2004287477] Windows Error 0x8889000b
ERROR - comtypes._comobject.call_without_this (13:48:39.865) - Dummy-4 (6804):
Exception in IUIAutomationEventHandler.HandleAutomationEvent implementation:
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 176, in call_without_this
  File "UIAHandler\__init__.pyc", line 747, in IUIAutomationEventHandler_HandleAutomationEvent
  File "comtypes\_post_coinit\unknwn.pyc", line 115, in __getattr__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
```

Last block is repeated for many times.

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
NVDA alpha-33864,7e526e81

#### Windows version:
Windows 10 Version 22H2 (build SO 19045.4842)

#### Name and version of other software in use when reproducing the issue:
WhatsApp app from Microsoft Store.

#### Other information about your system:
None.

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I'm sure it's happened something similar in previous alphas.

#### If NVDA add-ons are disabled, is your problem still occurring?
Not tested.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested (but I ran the tool recently).

**Comment by ABuffEr** [comment]
CC: @jcsteh

**Comment by zstanecic** [comment]
Hi,

Have you tried to reproduce this with a different tts?

 From the log, i see also some error going from eloquence itself.

**Comment by ABuffEr** [comment]
> Hi, Have you tried to reproduce this with a different tts? From the log, i see also some error going from eloquence itself.
It happens too rarely to use another TTS. And, in any case, the audio error targets also nvwave and _ctypes, and my suspect is that appears if there is another application that operates in the meantime (see [here](https://www.avsim.com/forums/topic/617202-voice-control-will-not-work-at-all/)).

**Comment by jcsteh** [comment]
For reference, the error code is AUDCLNT_E_BUFFER_OPERATION_PENDING.

I don't know the Eloquence code, nor am I willing to look into it, but it looks like it's calling WavePlayer.stop from a background thread. It probably shouldn't do that. It also looks like it might be calling WavePlayer.stop from two different threads simultaneously, which is even worse, but I can't be certain of that. That is most likely the cause of this error.

**Comment by jcsteh** [comment]
I'm reasonably certain this is a bug in the synth driver, and given that we can't realistically look at the code for this, there's nothing we can do here. If this happens with another synth and we have access to its driver's code, please reopen with details. Thanks.
