### ISSUE TITLE
NVDA stops reading the level at which headings appear

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1714]
**Reported by elliott94 on 2011-08-09 21:08**
I unfortunately can't seem to find the event that causes this, but recently I've noticed that NVDA will stop reading the level of headings, I.E. "heading level 1, 2, 3, etc".
This appears to be independent of the website that is currently being read. I've seen this several times before, but unfortunately didn't document it sooner - sorry that I'm unable to come up with exactly how to reproduce this.

Using Firefox 5, and snapshot 4580.

**Comment by ehollig** [comment]
This was fixed in Firefox 18 acording to [MozillaBug:686821](https://bugzilla.mozilla.org/show_bug.cgi?id=686821)

**Comment by derekriemer** [comment]
confirmed.
