### ISSUE TITLE
The Commands Quick Reference contains text from the User Guide that should not belong to it

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#17159]
### Steps to reproduce:

1. Open Commands Quick Reference
2. Go to"MiniSeika (16, 24 cells), V6, and V6Pro (40 cells)" paragraph
3. Look at the content of this paragraph after the first table

### Actual behavior:
You have some extra text and table that actually belong to "Papenmeier BRAILLEX Newer Models" in the User Guide, from "The following Braille displays are supported:"
to "Following are the Papenmeier command assignments for NVDA:"

### Expected behavior:

In any case, this extra text does not need to be in the Commands quick reference, neither in "MiniSeika (16, 24 cells), V6, and V6Pro (40 cells)", paragraph nor in "Papenmeier BRAILLEX Newer Models" paragraph.

### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
N/A
#### NVDA version:
2024.4beta3
#### Windows version:
N/A
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
N/A
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not checked again but I think that this issue was already present in 2024.3
#### If NVDA add-ons are disabled, is your problem still occurring?
N/A
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by seanbudd** [comment]
Closing as fixed by #17121
