### ISSUE TITLE
Feature request: Keep audio device awake indefinitely

### ISSUE THREAD

**Issue by haruncetinkaya306** [nvaccess/nvda#17168]
### Is your feature request related to a problem? Please explain.
NVDA can keep the audio devices awake for up to 3600 seconds. This is sufficient for everyday usage scenarios, but it doesn't solve some problems. For example, I may be away from the computer for more than an hour and encounter the action of waking up the audio devices. When I put the computer to the lock screen, I think it's because Windows has gone silent after 1 hour of silence, when I start using the computer it doesn't recognize any of my audio devices. This problem doesn't go away unless I find someone to see it, or somehow turn the computer off and on, restart it, or connect an external sound card. This last problem only occurs in Windows 11.
### Explain your desired solution
Instead of setting the wake time for the audio devices to 3600 seconds, have them stay awake indefinitely with a checkbox.
### Explain any alternatives you've considered
Or maybe an option like keeping them on all the time could be added as an extra option, since some people might want to use it that way.
### Additional context
None

**Comment by seanbudd** [comment]
It sounds like there is a problem with your audio card. Closing as out of scope of a screen reader.
