### ISSUE TITLE
Title: Focus Shift Issue in Nested Iframes with NVDA Active

### ISSUE THREAD

**Issue by Anjali935453** [nvaccess/nvda#17165]
### Detailed description of the issue

When using NVDA with nested iframes, if a user tries to interact with an element within a deeply nested iframe, the focus unexpectedly shifts to the parent iframe instead of remaining on the clickable element in the nested iframe. This issue does not occur when NVDA is not active; the focus behaves correctly and remains on the target element.

### Why are the other templates not appropriate in this case?

The bug report template does not fully capture the complexity of this issue, which involves nested iframes and specific behavior with NVDA. This issue may require detailed examination of focus handling within nested iframes, which is why this detailed issue report is more suitable.

### Have you asked for advice on how to report this issue via a community discussion? If so, please link to the discussion

No, I have not yet sought advice through community discussion forums.

### Steps to reproduce or illustrate the issue (if applicable)

1. Open a web page with multiple nested iframes.
2. Navigate to a deeply nested iframe that contains clickable elements.
3. With NVDA active, try to focus on and activate a clickable element within the deeply nested iframe.
4. Observe that the focus moves to the parent iframe instead of remaining within the nested iframe.

### Expected outcome or behaviour (if applicable)

The focus should remain on the clickable element within the deeply nested iframe when it is activated with NVDA enabled. 

### Screenshots, logs, and other attachments (if applicable)

Currently, there are no screenshots or logs available. However, I can provide them if necessary.

### System configuration or software environment (if applicable)

- NVDA version: 2024.3.1.33894
- Browser: Chrome
- Operating System: Windows 11

### Additional information (if applicable)

This issue significantly impacts users who rely on NVDA for web navigation, particularly in complex web applications involving multiple nested iframes. Further investigation and resolution would improve usability and accessibility.

**Comment by XLTechie** [comment]
Please provide a sample.Either an HTML file attached to the issue (you may need to zip it first for GitHub to accept it), or a jsfiddle, codePen, or similar demo site version.

**Comment by Adriani90** [comment]
We don't have any minimal test case to see what's hapening here exactly, so we cannot further 9investigate. If you provide a minimal test case e.g. in codepen, wen can reopen.
