### ISSUE TITLE
white space before a link at the start of a line requires you to tab to the link  when navigating around with arrow keys.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1716]
**Reported by dwillemv on 2011-08-10 18:58**
Normally when I navigate around with my arrow keys on a page and there is a link at the start of a line, I can just press enter if the link is on its own line or at the start of the line.

In firefox on the gmail website, the "show search options" has a single space before the link starts and when I press enter it does not activate. If there is other text, I understand why the link is not activated, but I think this should ignore white space.

Note that when I tested this in internet explorer, this was not a problem as it seemed to strip the space before the link and it activated.

**Comment by ehollig** [comment]
I think I agree with @jcsteh in https://github.com/nvaccess/nvda/issues/1716#issuecomment-155292014. Disabling screen layout will allow for all links to appear at the start of the line. I think when screen layout is enabled, it should show text as it is visually displayed on screen, including spaces. I do not believe anything else should be done on this ticket and should be safely closed.

**Comment by Brian1Gaff** [comment]
The issue I think is how to communicate that the link is not currently under 
the focus when you might otherwise assume that it is.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment]
I think this issue can be clolsed because it works when screen layout is disabled. Moreover, the gemail website has been redesigned.

The initial author is welcome to reopen a new issue with a current website if this issue is still reproducible.

**Comment by ehollig** [comment]
Closing because of the solution provided in https://github.com/nvaccess/nvda/issues/1716#issuecomment-155292014
