### ISSUE TITLE
Replace Feature Flags in the UI, with a prompt for default changes

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#17171]
### Is your feature request related to a problem? Please describe.

Some users find the feature flags interface, to be much less preferable than simple checkboxes.

Checkboxes, other than just being the usual binary on/off control type, and thus being very familiar to users, also have the advantage that accelerator keys can be assigned to them.

I also get the impression that a nice group of checkboxes, suddenly broken up by a combo box that is only there because it needs to provide a default option, is visually unappealing.

However, NVDA does need a way for NV Access to change an expected default preference, to a different default, if NV Access believes it to be in the best interest of the users. Balanced against this, is the consideration that users may know very well that NV Access could prefer something different in the future, but for reasons of user's own, want to maintain a certain selection despite it.

### Describe the solution you'd like

Given how rarely NV Access development leads to a change in any of these defaults, I would much rather these be changed back to checkboxes in the case of binary options.

Then, if in the future it is noticed that a default option should have a better value, NVDA could raise a dialog on update saying something like:

>We noticed that you are using the X option set to never.
>While that was the default preference before, NV Access now believes that the "Always" choice is safe, and is best for most users going forward.
>(You can read more about it Link here.)
>Would you like to update this preference, or keep your current selection?
>Remind me later button. Update my choice now button. Keep current setting button.

This alternative would require NVDA to carry an internal list of versions after which any flag changed, in order to handle the case of a user skipping a version upgrade and jumping to the one after. But that shouldn't be unwieldy.

One concern I haven't thought of a way to address, is the idea that years down the road, the number of changed defaults could accumulate to the point that the number of these prompts could be annoying.

There are probably other aspects I haven't thought of as well, but I thought this might be a good time to get some feedback on the concept.

### Describe alternatives you've considered

This is a follow-up proposal to #17170.
I suggested that as a short-term solution, and to cover cases where the choice is not binary even without the default, with this as a longer term solution.
This one likely needs more discussion, and perhaps has significant pitfalls I haven't considered.

### Additional context

While the "feature flag creep" has been low level bothersome for a while, @Adriani90's recent comments (such as #17122), have drawn my attention to it again.

Whether my suggestions or some other, it really seems as if there should be a better way to address this.

**Comment by seanbudd** [comment]
Closing as won't fix. We don't understand the issue raised here. Combo-boxes are not particularly confusing to use, and the premise of a try-state control is something we want to retain for the uses of it.
