### ISSUE TITLE
Update wxPython to 4.2.2, using 32-bit wheel hosted on PyPI

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#17175]
Part of component updates for NVDA 2025.1 development milestone:

### Is your feature request related to a problem? Please describe.
NVDA 2024.x uses an alpha version of wxPython 4.2.x hosted on NV Access dependencies repository. While this did provide a ready to use 32-bit wheel, using a development snapshot of wxPython was risky and the project could not take advantage of changes intorduced in later builds.

### Describe the solution you'd like
wxPython 4.2.2 was released on September 11, 2024. The biggest change is restoration of 32-bit wheel so NV Access no longer needs to host its own 32-bit wheel for this dependency. This also allows the project to use newer changes from wxPython (wxWidgets 3.2.6).

### Describe alternatives you've considered
Keep using current wxPython 4.2.x alpha build.

### Additional context
Part of major component updates in line with year.1 release - wxPython is the GUI toolkit used in NVDA, so this dependency is a critical component for the screen reader. Besides, wxPython 4.2.2 introduces support for Python 3.13 (a 32-bit wheel was also built for 3.13).

Thanks.

**Comment by dpy013** [comment]
Modifying the requirements file compiles fine, and it looks like he has correctly recognized 32bit during the pip install of wx python.
          Here are the logs and modifications:
           requirements.txt | 2 +-
          -wxPython @ https://github.com/nvaccess/nvda-misc-deps/raw/51ae7db821d1d5166ab0c030fe20ec72dd7a2ad9/python/wxPython-4.2.2a1-cp311-cp311-win32.whl
          +wxPython==4.2.2
          logs:
          [nvda.log](https://github.com/user-attachments/files/17008023/nvda.log)
