### ISSUE TITLE
Visual Highlight color is incorrect upon NVDA startup in browse mode

### ISSUE THREAD

**Issue by nishimotz** [nvaccess/nvda#17183]
### Steps to reproduce:

1. **Enable Visual Highlight in NVDA**:
   - Go to NVDA settings and enable the "Visual Highlight" feature.
2. **Configure Browse Mode Settings**:
   - Ensure the following settings are configured in NVDA:
     - "Enable browse mode on page load" is checked.
     - "Audio indication of focus and browse modes" is unchecked.
3. **Use the Speech Viewer**:
   - Open the Speech Viewer in NVDA (`NVDA` > `Tools` > `Speech Viewer`) to monitor and log NVDA's spoken feedback.
4. **Open a webpage in Google Chrome**:
   - Open Google Chrome and navigate to [www.nvaccess.org](http://www.nvaccess.org).
   - The web content is surrounded by a red frame, indicating browse mode.
5. **Navigate with the Tab key**:
   - While NVDA is reading the content, press the `Tab` key.
   - Focus moves to the "About" link, and the frame color changes to blue.
6. **Switch to Focus Mode**:
   - Press `NVDA+Space` to switch to focus mode.
   - NVDA announces "focus mode," and the frame remains blue.

### Actual behavior:

Upon starting NVDA and navigating to a webpage in browse mode, the Visual Highlight frame correctly appears in red. However, after moving focus with the `Tab` key and **not** switching to focus mode, the frame changes to blue, which is not expected.

Speech Viewer Log:
```
https://www.nvaccess.org selected
NV Access
navigation landmark    heading    level 1  visited  same page  link    graphic    NV Access Empowering lives through non-visual access to technology
link    Donate
list  with 9 items  visited  same page  link    current page  Home  link    About  link    Download  link    Get Help  link    Corporate / Government  link    Blog  link    Support Us  link    Shop  link    Create Account / Log In  out of list
main landmark    heading    level 2  We believe that every Blind + Vision Impaired personDeserves the right to freely & easily access a   heading    level 2  computer!
About  collapsed  subMenu  link  
Focus mode
```

### Expected behavior:

The Visual Highlight frame should remain red in browse mode when navigating with the `Tab` key unless explicitly switched to focus mode.

#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
alpha-34002, 29b6a9b3 x86
#### Windows version:
Windows 11 23H2 (10.0.22631) workstation AMD64 (Japanese environment)
#### Name and version of other software in use when reproducing the issue:
Chrome 128.0.6613.138（Official Build) 64bit
#### Other information about your system:
NVDA UI language is set to English.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This behavior has been the same since the feature was implemented.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes, the problem occurs with all add-ons disabled.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes, running the COM Registration Fixing Tool does not resolve the issue.

**Comment by hwf1324** [comment]
This is expected behavior.

Note that the red rectangle indicates a navigation object and does not indicate a browsing mode.

It is the small yellow rectangle that indicates the navigation cursor in browsing mode.

And the system focus is on the link at the same time the navigation object is on the link, so there is a solid blue rectangle indicating the current focus.

See: https://www.nvaccess.org/files/nvda/documentation/userGuide.html?#VisionFocusHighlight

**Comment by Adriani90** [comment]
Closing as invalid, as per comment above.

**Comment by nishimotz** [comment]
Thank you for clarifying the expected behavior specifications. I appreciate the detailed explanation.

I will consider the next steps, such as providing alternative steps to reproduce the issue or suggesting this as a feature enhancement. Specifically, I believe there is room for improvement for sighted users conducting accessibility testing, as the current behavior can be confusing.

Additionally, I want to mention that for the Focus Highlight, there was an option to "Make focus mode the default," which addressed the confusion around the initial color state.

**Comment by hwf1324** [comment]
Hi,

Is your idea that highlighter can indicate that it is currently in browse mode or focus mode?

A more reliable way for now is still to confirm the presence of the yellow rectangle of the browse cursor.

Surely having a way to visually indicate browsing mode or focus mode certainly makes sense.

That could be a new way.
Or a new highlighter color.

Thanks.
