### ISSUE TITLE
nvda doesn't display check box status in braille in libreoffice dialogs

### ISSUE THREAD

**Issue by dave090679** [nvaccess/nvda#17218]
### Steps to reproduce:
- open libreoffice calc
- open the options dialog
- select the accessibility category
- set the focus to the "enable accessibility features" check box
### Actual behavior:
the status of the checkbox isn't displayed in braille, it is only spoken.
### Expected behavior:
the status of the checkboxes should be displayed in braille.

#### NVDA installed/portable/running from source:
nvda is installed.

#### NVDA version:
nvda 2024.3.1
#### Windows version:
Windows 11 23h2 (Build 22631.4169)
#### Name and version of other software in use when reproducing the issue:
Libreoffice 24.8.1.2
#### Does the issue still occur after restarting your computer?
yes.
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by michaelweghorn** [comment]
I don't have an actual braille device, but from what I can see at least NVDA's braille viewer shows the text of the checkboxes (tested with LibreOffice 24.8.1 and NVDA 2024.3 and current development versions of both).

@dave090679 You wrote:
> set the focus to the "enable accessibility features" check box

I don't see any checkbox with that particular text in the dialog. Do you mean the one labeled "Support assistive technology tools (program restart required)"?

For that one, NVDA's braille viewer also displays this for me: "a Support assitive technology tools (", which seems OK to me, but I don't have any deeper knowledge of braille devices, so might be missing something.

I'm attaching a screenshot for reference:
![Screenshot of LibreOffice options and NVDA's braille viewer displaying the text of the checkbox](https://github.com/user-attachments/assets/ce5b1bb8-9ec9-45b2-bed4-bf0fa7919ad7)

**Comment by michaelweghorn** [comment]
> For that one, NVDA's braille viewer also displays this for me: "a Support assitive technology tools (", which seems OK to me, but I don't have any deeper knowledge of braille devices, so might be missing something.

But now I see that e.g. the checkboxes in NVDA's Braille Viewer are displayed as e.g. "Show Braille Viewer on Startup ⣏⣀⣹ c", with "⣏⣀⣹" indicating that the checkbox is not checked, while "⣏⣿⣹" would indicate that the checkbox is checked. And that is not displayed in Braille Viewer for checkboxes in LibreOffice's options dialog.

@dave090679 Do I understand correctly now that this is what you're referring to by "the status of the checkbox isn't displayed in braille"?

The fact that the status is spoken just fine seems to suggest to me that it's probably properly reported via the IAccessible2 API by LibreOffice and therefore it's likely something in NVDA causing this.

**Comment by michaelweghorn** [comment]
> The fact that the status is spoken just fine seems to suggest to me that it's probably properly reported via the IAccessible2 API by LibreOffice and therefore it's likely something in NVDA causing this.

I think I understand now *why* it behaves  the way it does: NVDA seems to be using a list of potential texts to display for braille, and only the last one actually gets used. The second last candidate includes the checkbox state (and the a11y description, too), while the last one (which is the one that gets displayed) doesn't.

In the `getFocusRegions` method, an additional "focus region" is taken into account when the object is considered to have "useful text": `https://github.com/nvaccess/nvda/blob/1573904b17722303f66434804cd515fc012b78af/source/braille.py#L2237-L2240

One criterion for "useful text" is if the object's class is a subclass of the `EditableText` class. That is the case for checkboxes in Libreoffice, as the `SymphonyText` class currently gets used for them, which is a subclass of `EditableText`. Not using that class for checkboxes causes the previously second-last text to get displayed in braille viewer instead, which includes the state. I'll think a bit more about it and will then probably submit a PR.

**Comment by Emil-18** [comment]
You can read the checked/unchecked state by scrolling the braille display back
