### ISSUE TITLE
Tesseract OCR Does Not Scan the Entire Document

### ISSUE THREAD

**Issue by Jykke67** [nvaccess/nvda#17224]
### Steps to reproduce:
1. Put an A4 text document on the scanning glass and close the cover.
2. Press Windows+Control+w in order to start the scanning and OCR procedure.
3. Press ”No” when prompting to scan one more page.
4. See the OCR result in ocr.txt.
### Actual behavior:

The OCR result shows that the document has not been completely scanned.
### Expected behavior:

An option for skanning the entire page should also be prompted, not just the page adding option, or the document should be entirely scanned by default.
### NVDA logs, crash dumps and other attachments:
Not available (WIA Canon MF4600 Series recognized by Tesseract)
#### NVDA installed/portable/running from source:
NVDA installed
#### NVDA version:
NVDA 2024.4beta4
#### Windows version:
Windows 11 Pro, 64-bit (updated from Windows 10 Pro, 64-bit)
#### Name and version of other software in use when reproducing the issue:
No other software (scanning works correctly with OmniPage 18)
#### Other information about your system:
Scanner: Canon I-Sensys MF4660PL Multi Printer
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.
#### If NVDA add-ons are disabled, is your problem still occurring?
Inpossible to test, because Tesseract OCR add-on is required.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by Adriani90** [comment]
This is an issue with the addon, please write the addon author directly, or create an issue on the github repository of the addon, or use the nvda addons mailing list.

**Comment by ruifontes** [comment]
@Jykke67, can you sent a mail to rui.fontes@tiflotecnia.com?
Thanks!

**Comment by Jykke67** [comment]
Hello, @ruifontes ,

Have sent you e-mail as you requested.

I’m afraid that I can’t be of very much assistance, because my scanning issue is against all logics. A friend of mine has got an option for scanning the entire page.
