### ISSUE TITLE
Change of the window title announcement in the file explorer

### ISSUE THREAD

**Issue by Nael-Sayegh** [nvaccess/nvda#17241]
### Steps to reproduce:
Open any folder in the explorer.
Listen to the window name or press NVDA+T.

### Actual behavior:

Normally, with NVDA, the folder name is reported alone in the explorer. But recently, NVDA announces "FolderName - File Explorer".
This is disturbing because we are used to hearing a name after the name of the window only in applications and not in folders.

### Expected behavior:

We should not hear any change; when we hear the name of the folder, it should not have the name of the explorer.

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2024.3.1
#### Windows version:
windows 11 pro Version 23H2 (build 22631.4169)
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CoBC** [comment]
IMO, this is due to a change in Windows, not in NVDA

**Comment by josephsl** [comment]
Hi,

Yes - this is a change introduced with File Explorer in recent Windows 11 releases. This is also seen with Narrator as well. A counterargument could be made that adding "- File Explorer" to the title bar makes the window title consistent with other apps that display file names and app name on the title bar (such as Edge, Firefox, Notepad, among others), and I believe that's the intention for changing the way File Explorer window title is displayed. To reverse this, you must justify really strongly when talking to Microsoft folks.

Thanks.

**Comment by Adriani90** [comment]
This is given by Windows via UIA in the recent Windows 11 updates, and strictly speaking the file explorer is an application, so it is ok to hear that in my opinion.
cc: @josephsl should we close this issue?

**Comment by Adriani90** [comment]
Let's close this issue for now as invalid, since Windows Explorer does not what other applications do as well.

**Comment by SaschaCowley** [comment]
@Nael-Sayegh if you find this particularly annoying, you could set up a speech dictionary entry that replaces " - File Explorer" with an empty string, with likely very little impact elsewhere.
