### ISSUE TITLE
braille: cannot move to last empty line with braille scrolling keys in notepad

### ISSUE THREAD

**Issue by burmancomp** [nvaccess/nvda#17251]
### Steps to reproduce:
- open notepad and write something and press enter
- move back to previous non-empty line
- try to move back to empty line with braille down/scroll forward keys

Note that if there are two empty lines you can move to the first but not to the second.
### Actual behavior:

Cannot move back to empty line
### Expected behavior:

Should move back to empty line.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
alpha-34198,67f6cb99 (2025.1.0.34198)
#### Windows version:
windows 11 23h2
#### If NVDA add-ons are disabled, is your problem still occurring?
yes

**Comment by irrah68** [comment]
I can reproduce this in Notepad and Notepad++.

**Comment by nvdaes** [comment]
I can reproduce this also in documments of Perky Duck. I think that this may be related to textInfo in UIA objects.

**Comment by nvdaes** [comment]
@burmancomp , I've created a PR. I'll add the changelog later. Feel free to test it if you want.
