### ISSUE TITLE
We can't navigate list with checkbox using arrow keys when NVDA screen reader is on. Take https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/examples/checkbox-mixed/ for example

### ISSUE THREAD

**Issue by thambu77** [nvaccess/nvda#17267]

**Comment by seanbudd** [comment]
Welcome @thambu77 

We are unable to process this issue as it stands. Please fill out the issue template fully.

Kind Regards,
NV Access Software Developers

**Comment by thambu77** [comment]
Actual behavior: Using Arrow Keys, user is able to Navigate through the list but the record focussed is not highlighted
Expected behavior:  Using Arrow Keys, When we navigate, the record focussed should be highlighted
System configuration:-
NVDA installed/portable/running from source: BrowserStack. (Same working fine on Mac VoiceOver)
NVDA version: 
Windows version: 10, Chrome 128
