### ISSUE TITLE
Unicode normalization while spelling not working correctly

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#17286]
### Steps to reproduce:
* Enable Unicode normalization in Speech settings
* Open the add-on store
* Select the first add-on
* Press `alt+o` to go to "Other details" field
* Press `NVDA+upArrow` to spell the first line; in my case, the text on the first line is: "Publisher: Tseng Woody"

### Actual behavior:
All the characters after the colon (:)  are reported as "normalized".

### Expected behavior:
Only the em-dash character should be reported as normalized: it is actually normalized to space.

### Notes
There are various other normalization reporting issues. I may document them later in the comments of this issue.

### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2024.4rc1
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.4894
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Last alpha also produces this issue.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested, unrelated

**Comment by CyrilleB79** [comment]
@seanbudd, I wonder if we should revert the default enabled of this feature in 2025.1...

Also cc @LeonarddeR in case you still follow this.

**Comment by LeonarddeR** [comment]
I guess this is something that can be fixed before 2025.1. I will have some more spare time around mid november, so I should be able to dive in for an hour or two.

**Comment by SaschaCowley** [comment]
FYI the character being normalised here is an em-space, not an em-dash.

**Comment by seanbudd** [comment]
@CyrilleB79 I agree that this should block the feature staying on as default
