### ISSUE TITLE
Getting to the previous page does not jump to the same position in orkut.com

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1729]
**Reported by clev on 2011-08-22 13:43**
To reproduce this, go to any comunity in the Orkut.com social network, then to the comunity forum, where you will get a table containing the forum topics. Enter a topic, then jump a bit around using for example the h key for jumping between the topic messages, then press alt-left arrow for getting back to the forum main page. Instead of being placed at the topic link you just entered, the browse mode remains in the same position you were in the topic you have just left, as if you haven't even changed the page.

It's worth noting that orkut.com maintains two layouts, one classing/older and another newer. I like using the older one, which offers more heading navigation, however I'm almost sure the problem occurs in both the layouts.

I cannot precise now what NVDA version it started happening from, but it certainly didn't happen in 2011.1 and happens in 2011.2.

I'm using Internet Explorer 8, don't know how other browsers behave.

**Comment by ehollig** [comment]
The link that the author of this ticket provided is no longer available. I have experienced NVDA not remembering the exact location of where you were on the page with browse mode after hitting the back button, but do not have a good STR right now.

**Comment by derekriemer** [comment]
Sounds like a bug in javascript coding. If the site is gone, closing as invalid.
