### ISSUE TITLE
gesture to move to start/end of selection in documents and edit controls

### ISSUE THREAD

**Issue by burmancomp** [nvaccess/nvda#17299]
### Is your feature request related to a problem? Please describe.
Hopefully just to improve ux. When selecting several lines of text you might want to quickly check where your selection starts. This is now possible with "announce current selection" but may require several key presses.
### Describe the solution you'd like
This should be easy by setting review position to start/end of selection. I think it would be consistent to have both selection start/end gestures.

**Comment by nvdaes** [comment]
I think that NVDA+shift+home may move the review cursor to the start and end of selection, alternatively.
I may try to create a PR for this.

**Comment by nvdaes** [comment]
@burmancomp , I think that we shouldn't use NVDA+shift+f9 since this is related to text marked to be copied. Then I'll try to use NVDA+alt+home and NVDA+alt+end.

**Comment by nvdaes** [comment]
@burmancomp , feel free to test the linked pull request if you want.
Feedback is appreciated.
