### ISSUE TITLE
Apllying audio settings resets volume level for apps

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#17300]
### Steps to reproduce:

1. open Windows volume mixer;
2. customize volume of any app, e.g. system sounds;
3. close volume mixer;
4. open NVDA preferences, then audio section;
5. without changing anything (even if default), choose apply, then ok.

### Actual behavior:

Customized volume is reset, returning to current general volume.

### Expected behavior:

Customized volume is left untouched.

### NVDA logs, crash dumps and other attachments:

None.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

NVDA alpha-34301,695456a5

#### Windows version:

Windows 10 22H2 (build SO 19045.5011)

#### Name and version of other software in use when reproducing the issue:

I tried with no opened windows except desktop, so I presume no other application/profile is related.

EDIT: cleaned profiles from [audio] section, and issue persist.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Not tested.

**Comment by Adriani90** [comment]
Is the apps volume adjuster enabled or disabled in NVDA?

**Comment by ABuffEr** [comment]
> Is the apps volume adjuster enabled or disabled in NVDA?

Default (disabled).
As I said, this happens even with default configuration, without changing anything.

**Comment by seanbudd** [comment]
cc @mltony

**Comment by mltony** [comment]
I will investigate it this weekend.
