### ISSUE TITLE
Some issues after #17271

### ISSUE THREAD

**Issue by wmhn1872265132** [nvaccess/nvda#17303]
### Steps to reproduce:

1. Open the Input Gestures dialog
2. Browse to the audio category

### Actual behavior:

1. The writing style of some entries has not been updated.
   > Toggles other applications volume adjuster status
2. After assigning a gesture to the above item, the prompt for pressing the gesture has no function description and only prompts Yes/No.

### Expected behavior:

The writing style has been updated, and there is a functional description when switching.

#### NVDA installed/portable/running from source:
portable

#### NVDA version:
All versions after #17271

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
irrelevant

#### Other information about your system:
irrelevant

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
irrelevant

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
irrelevant

**Comment by seanbudd** [comment]
closing this issue.
It is unclear what this issue means or is in reference to.
In future:
- Please use a more descriptive title
- Please create more thorough steps to reproduce
- Please clarify what you mean by writing style
