### ISSUE TITLE
NVDA+F Text Format Info should report alignment info (left, centered, right-justified)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1732]
**Reported by kevinchao89 on 2011-08-25 00:23**
Windows 7 x64, Firefox Nightly 9.0a1 (2011-08-21), NVDA snapshot 4586.

NVDA+F very nicely reports text formatting information. I see in release notes that
strikethroughs and underlines can be reported, but I did not see any
mention of alignment (center, left, right) and it does not seem that this is currently supported, but it would be very much appreciated if it if were provided at some point.

**Comment by dkager** [comment]
It's now included. On this GitHub page with Firefox 54:

```
IO - inputCore.InputManager.executeGesture (16:18:04.713):
Input: kb(laptop):NVDA+f
IO - speech.speak (16:18:04.726):
Speaking [LangChangeCommand ('en_GB'), u'Segoe UI  11pt  very dark aqua-blue grey on white  baseline  align center']
IO - braille.BrailleBuffer.update (16:18:04.726):
Braille regions text: [u'Segoe UI  11pt  very dark aqua-blue grey on white  baseline  align center']
```
