### ISSUE TITLE
None is announced after document layout in MS Word

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#17338]
### Steps to reproduce:
- Run nvda_snapshot_alpha-34447,a69efb36.exe
- - Open Microsoft Word 16.0.17328.20612 on Windows 10 22H2 (19045.5011)
### Actual behavior:

None is reported after document layout. This is speech output in Spanish:

> Documento de Microsoft Word  edición  multilínea  Print layout None  página 1  
### Expected behavior:

None shouldn't be reported.
#### NVDA installed/portable/running from source:
Temporary copy
#### NVDA version:
Alpha 34447,a69efb36
#### Windows version:
Windows 10 22H2 (19045.5011)
#### Name and version of other software in use when reproducing the issue:
Microsoft Word 16.0.17328.20612 on Windows 10 22H2 (19045.5011)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
n/a
#### If NVDA add-ons are disabled, is your problem still occurring?
n/a
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
n/a

**Comment by nvdaes** [comment]
I think we should check if document description is None, and in this case the document layout shouldn't be prepended to the description. Instead, in this case the document layout should be the description itself.
Also, we can check if description is "" (empty string), to avoid the extra final space when the document layout is prepended.
cc: @SaschaCowley

**Comment by SaschaCowley** [comment]
> I think we should check if document description is None, and in this case the document layout shouldn't be prepended to the description. Instead, in this case the document layout should be the description itself.
> Also, we can check if description is "" (empty string), to avoid the extra final space when the document layout is prepended.

That sounds like a good plan to me. You should be able to do this with a simple `if` statement, as `None` and `''` both evaluate to `False`.

**Comment by nvdaes** [comment]
Thanks @SaschaCowley . I think we can close this issue since you said that this fix doesn¡t need to be triaged by NV Access. I'll close it and the next time I will fix directly things like this is a PR needs to be fixed for alphas.
I'll do it now in another PR.
