### ISSUE TITLE
Issue with Add-Ons

### ISSUE THREAD

**Issue by Sbilek44** [nvaccess/nvda#17342]
### Steps to reproduce:
With NVDA running, I went to Tools, then Add-On Store.
### Actual behavior:

When I click on the Add-On Store, I receive a warning message that says, "Unable to fetch latest add-ons for compatible add-ons."  When I click OK, the Add-Ons window open but there are no add-ons available.  The window is blank.  The Add-On that I'm trying add is Focus Highlights.
### Expected behavior:

I'm assuming that when I click Add-On Store, I should not be receiving the warning message and there should be numerous add-ons available.
#### NVDA installed/portable/running from source:
NVDA installed from NVDA official website.
#### NVDA version:
2024
#### Windows version:
Windows 11 Enterprise
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Add-Ons are the problem.  I don't want to disable them.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
I haven't run this because I need my IT administrator to do this task.

**Comment by hwf1324** [comment]
Hi,

This may be a problem with your network.The NVDA Add-on Store needs to get the Add-on's metadata from NV Access's servers.

Your computer seems to be under the management of the company, please check if you can access the servers of NV Access from your network.

Of course, if you can provide debug logs, it will allow us to make a more accurate judgement.

Thanks!

**Comment by seanbudd** [comment]
Closing as can't fix, this is a problem with your system network
