### ISSUE TITLE
Feature request: Add sentence navigation functionality for txt text editors

### ISSUE THREAD

**Issue by haruncetinkaya306** [nvaccess/nvda#17347]
### Is your feature request related to a problem? Please explain.
In txt text editors, sometimes several words fit on a line and require constantly pressing the down arrow.
### Explain your desired solution
Add the alt+downArrow and alt+upArrow functions that are in MS Word and Outlook to txt text editors.
### Explain alternatives you have considered
Or add other functions that may be possible.
### Additional context
None.

**Comment by Adriani90** [comment]
Closing as duplicate of #8518
