### ISSUE TITLE
Using eSpeak sapi5, when spelling a capital letter, it doesn't back to normal pitch.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1736]
**Reported by ateu on 2011-08-28 13:53**
I use eSpeak sapi 5.
When I spell a chapital leter, it increments  the pitch, but It does not back the previous pitch.

**Comment by bhavyashah** [comment]
Does this issue still stand with ESpeak-NG, the successor of ESpeak? I believe the SAPI 5 version of ESpeak-NG is under development at the moment, and thus would request @rhdunn to take this ticket into account for the same.

**Comment by seanbudd** [comment]
Closing as abandoned/stale.
