### ISSUE TITLE
Toggling radio button triggers "checked" feedback twice

### ISSUE THREAD

**Issue by ssande-fwd** [nvaccess/nvda#17369]
When using radio buttons with click listeners the screen reader might repeat "checked" twice after a click event. I was able to resolve the issue by putting the callback function on the click event in a timeout. The timeout can even be 0 ms. 
### Steps to reproduce:
Set up a click listener on your radio button that performs something reasonably intensive like changing display on a block of text from none to block. Toggle the radio button.
### Actual behavior:

The screen reader says "checked checked"
### Expected behavior:

The screen reader says "checked"
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
2024.4 (2024.4.0.34423)
#### Windows version:
Windows 11 Pro 23H2
#### Name and version of other software in use when reproducing the issue:
Firefox
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
No add-ons.

**Comment by Adriani90** [comment]
cc: @jcsteh since it affects Firefox.

@ssande-fwd can you please provide a minimal test case in Codepen for example? This would help alot in investigating this further.

**Comment by ssande-fwd** [comment]
Hi Adriani90. This has been a really tough bug because it's so inconsistent. Several times I have been able to repeatably prove a solution and then later that solution no longer works. In that same pattern, the timeout is no longer reliably preventing it.

The good news is I have not been able to repeat the bug in codepen, so it's likely some abstract interaction with the other code on our site. You can mark this as resolved

**Comment by ssande-fwd** [comment]
This has been a really tough bug because it's so inconsistent. Several times I have been able to repeatably prove a solution and then later that solution no longer works. In that same pattern, the timeout is no longer reliably preventing it. The good news for nvda is I have not been able to repeat the bug in codepen, so it's likely some abstract interaction with the other code on our site.
