### ISSUE TITLE
Update missing for beta/rc channel

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#17387]
### Steps to reproduce:
* Use a beta/rc channel installation, e.g. NVDA 2024.4rc1
* Check for update
* Use a stable channel installation, e.g. NVDA 2024.4
* Check for update
### Actual behavior:
* On the beta/rc channel, no update is offered
* On the stable channel, NVDA 2024.4.1 update is offered
### Expected behavior:
A 2024.4.1 update should be available for all channels. I.e. a 2024.4.1rc1 should be released.

### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
installed or portable
#### NVDA version:
2024.4.1
#### Windows version:
N/A
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
N/A
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A
#### If NVDA add-ons are disabled, is your problem still occurring?
N/A
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by seanbudd** [comment]
Closing, @SaschaCowley has release 2024.4.1 https://www.nvaccess.org/post/nvda-2024-4-1rc1/
