### ISSUE TITLE
Warn if option Registration for UI Automation events and property changes isn't set to Selective when running Visual Studio

### ISSUE THREAD

**Issue by towebo** [nvaccess/nvda#17394]
### Is your feature request related to a problem? Please describe.
Yes, poor performance with intellisense in Visual Studio 2022.

### Describe the solution you'd like
When NVDA detects that Visual Studio becomes the foreground application (devenv.exe) it should check that the option "Registration for UI Automation events and property changes" is set to Selective and if not a message will be displayed with info about the performance gains you get by changing this option. There can be a checkbox to disable the message from appearing again if it isn't applicable for your situation.

### Describe alternatives you've considered
Adding an entry in a FAQ somewhere, perhaps hosted on NV Access website, with tips on how to tweak NVDA for certain tasks with certain applications.

**Comment by CyrilleB79** [comment]
I cannot see a reason why such a warning should be added.

There is already a warning/disclaimer checkbox in Advanced settings. In the past, you have checked it to change "Registration for UI Automation events and property changes" to a value other than the default one. There is no reason to put a second warning for any advanced setting change that would cause any undesirable effect.

If you think to a good reason why it should be added in this specific case, please be more specific.

Just my opinion though.

**Comment by towebo** [comment]
I think you missunderstand the suggestion.The warning should appear when you start or switch toVisual Studio, not in the Settings dialog in NVDA.The purpose of the message is to inform the user that the experience will be greatly improved by changing the option in the Advance category.Karl-Otto0701-75 98 56Även om det är ett äpple på baksidan så får du inte tugga på min mobil!12 nov. 2024 kl. 21:31 skrev Cyrille Bougot ***@***.***>:﻿
I cannot see a reason why such a warning should be added.
There is already a warning/disclaimer checkbox in Advanced settings. In the past, you have checked it to change "Registration for UI Automation events and property changes" to a value other than the default one. There is no reason to put a second warning for any advanced setting change that would cause any undesirable effect.
If you think to a good reason why it should be added in this specific case, please be more specific.
Just my opinion though.

**Comment by Adriani90** [comment]
I think this could be argued for alot of apps, and this is not the responsibility of NVDA. For example with reporting of pages enabled in document formating settings, MS Word might be significantly lagier compared to when it is off. But there is no reason why we should show such specific warning. The setting about UIA registering events is clearly explained in the user guide as well.
What was the purpose for you to changecthat setting to a value other than the default one?

**Comment by seanbudd** [comment]
Closing for reasons outlined by @CyrilleB79 and @Adriani90
