### ISSUE TITLE
When I use the k key to scroll through links, other elements, such as titles or footers within the link, are described to me, which should not be default behavior, but rather optional.

### ISSUE THREAD

**Issue by titet11** [nvaccess/nvda#17397]
When I scroll through links using a keyboard shortcut, NVDA often announces descriptions that are not part of the links. 

For example: 

When I browse the "gmail.com" page, always in the first email, the tab title is described, which can be confusing: 

This behavior occurs on several websites, which contain footers as a tab title, or when they contain a title for each section before a link: 

proposal: 

My proposal is that these types of descriptions are optional, and that when using the k key only the title of the link is read, and not focus on describing other types of page elements in the link, such as footers or page elements. 

NVDA Version: 2024.4.1

system operation: windows 10 22 h2:

**Comment by titet11** [comment]
@Adriani90  I disabled everything in the document formatting section, and this doesn't work.

**Comment by tittet99** [comment]
I confirm the same as titet11, although this behavior is not only manifested when browsing links but also when browsing buttons using the f key: 
I am going to give an example similar to that of titet11, but I will do it in more detail so that it can be analyzed: 

1: When you try to navigate to the next link that contains a tab title or footer, that is when NVDA describes the element that should not be associated with the link or button:; However, when you return to the link or button where NVDA describes elements that do not correspond to the link or button, they are no longer described: that is, this behavior occurs when you advance to the next link or button, but not when you try to return to the previous link or button where NVDA describes elements that should not be associated: 

I hope it is understandable: 

Likewise, I disabled all NVDA features and this behavior still occurs:

**Comment by SaschaCowley** [comment]
Welcome @titet11 ,

We are unable to process this issue as it stands.

- Please fill out the issue template fully.
- To be able to reproduce this issue, we need a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).


Kind Regards,
NV Access Software Developers

**Comment by titet11** [comment]
@SaschaCowley I'm not sure how to replicate an html code as I'm pointing out, since I'm not sure how to do this. I tried it without results.

**Comment by titet11** [comment]
@SaschaCowley 
Here I will provide an example that does manage to replicate what I am explaining. please take it into account.


                    <a href="https://moodleprogramas.udgvirtual.udg.mx/curso_seleccion/course/view.php?id=109&amp;section=1" aria-current="page" >Cronograma</a>

</ul><ul class="topics"><li id="section-1" class="section main clearfix" role="region" aria-label="Cronograma"><div class="left side"></div><div class="right side"><img class="icon spacer" width="1" height="1" alt="" aria-hidden="true" src="https://moodleprogramas.udgvirtual.udg.mx/curso_seleccion/theme/image.php/maker/core/1727291248/spacer" /></div><div class="content"><h3 class="sectionname accesshide"><span><a href="https://moodleprogramas.udgvirtual.udg.mx/curso_seleccion/course/view.php?id=109&amp;section=1">Cronograma</a></span></h3><div class="summary"><div class="no-overflow"><p style="text-align: left;"><iframe width="700" height="700" frameborder="0" scrolling="no" src="https://1drv.ms/x/c/969aa97fc5f05a00/IQQ1ZeoKOxNcRJmhii0_sm7NAXJuljsFfNxti1TvnjpZf6o?em=2&amp;wdAllowInteractivity=False&amp;wdHideGridlines=True&amp;wdHideHeaders=True&amp;wdDownloadButton=True&amp;wdInConfigurator=True&amp;wdInConfigurator=True"></iframe></p></div></div><div id="completionprogressid" class="completionprogress">Su progreso<a class="btn btn-link p-a-0" role="button"

**Comment by titet11** [comment]
[intento-de-prueba.txt](https://github.com/user-attachments/files/17769581/intento-de-prueba.txt)

Here I will attach a file containing the replicated example.

**Comment by carlosperez99** [comment]
@SaschaCowley 
[result-button-chat.txt](https://github.com/user-attachments/files/17772446/result-button-chat.txt)
Like titet11, I attach an example, with the difference that my example is based on an html button with a header.

**Comment by titet11** [comment]
@SaschaCowley Hello: I hope you can respond to me as soon as possible. I believe that what I am contributing is necessary for investigation and correction.

**Comment by seanbudd** [comment]
@carlosperez99 @titet11 - please provide a minimal HTML sample. These examples are quite complex and unclear. Please provide a link to codepen, with a clear and simple case of the issue occurring. Alongside the code pen, we need a clear set of instructions to follow, that explain what to do, what you are expecting to hear, and what actually occurs.
Please [follow our guide to making a bug report](https://github.com/nvaccess/nvda/blob/master/projectDocs/issues/githubIssueTemplateExplanationAndExamples.md) for more information.
Closing this issue as invalid. Feel free to open a new one following the template
