### ISSUE TITLE
Key navigation of scrollbar is getting modified by the screen reader 

### ISSUE THREAD

**Issue by thirubme** [nvaccess/nvda#17410]
### Actual behavior:

I have a tab panel component. there is a text area & a large paragraph present within that along with a scrollbar. when tried to access those content using down arrow keys, the scrollbar is not moving. But when screen reader is off, the scrollbar is moving properly.
### NVDA logs, crash dumps and other attachments:
[![nvda_scrollbar issue_tabpanel](https://github.com/user-attachments/assets/65c97dec-1769-419d-b87d-4a60a6e23fe2)]

#### NVDA installed/portable/running from source:
(https://www.nvaccess.org/download/)
#### NVDA version:
2024.4.0.34423
#### Windows version:
Windows 11 pro 64bit
#### Name and version of other software in use when reproducing the issue:
Issue occured in our own software named, "Zoho Components"
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, facing same issue in all versions
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

**Comment by Adriani90** [comment]
You have to enable xocus mode with nvda+space bar in order to use your native keystrokes. Closing as works for me.
