### ISSUE TITLE
Say All doesn't work in libreoffice writer latest version

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#17417]
When I try to read a document in libreoffice writer using Say-all, capslock+a, NVDA reads a line or two and then stops, and puts me several lines down the page.

**Comment by joshknnd1982** [comment]
I am using NVDA 2024.4.1 and libreoffice version 24.8

**Comment by Adriani90** [comment]
In 25.2 it is fixed. Daily alpha builds already incorporate this. Closing as works for me.

**Comment by michaelweghorn** [comment]
> In 25.2 it is fixed. Daily alpha builds already incorporate this. Closing as works for me.

Indeed. See https://wiki.documentfoundation.org/QA/Testing_Daily_Builds for testing daily builds.
