### ISSUE TITLE
When using the arrow keys to move between Material checkboxes, selection status is not announced

### ISSUE THREAD

**Issue by Kosta-github-singular** [nvaccess/nvda#17420]
### Steps to reproduce:
1. Start NVDA.
2. Start Chrome browser
3. Go to URL https://material.angular.io/components/list/overview
4. On the page go to "Selection lists"
5. Select checkboxes for "Boots" and "Clogs"
6. Using keyboard, move between selected ("Boots" and "Clogs") and not selected ("Loafers", "Moccasins", "Sneakers")
### Actual behavior:
From speech viewer :
Boots  1 of 5
Clogs  2 of 5
Loafers  not selected  3 of 5
Moccasins  not selected  4 of 5
Sneakers  not selected  5 of 5
Moccasins  not selected  4 of 5
Loafers  not selected  3 of 5
Clogs  2 of 5
Boots  1 of 5

### Expected behavior:
Boots  **selected**  1 of 5
Clogs  **selected**  2 of 5
Loafers  not selected  3 of 5
Moccasins  not selected  4 of 5
Sneakers  not selected  5 of 5
Moccasins  not selected  4 of 5
Loafers  not selected  3 of 5
Clogs  **selected**  2 of 5
Boots  **selected**  1 of 5

Note: word "selected" is expected as for example in JAWS

### NVDA logs, crash dumps and other attachments:
![NVDA-Selection](https://github.com/user-attachments/assets/6c48ff0e-0b45-41f8-8ac0-6861d06f14bd)

#### NVDA installed/portable/running from source:
portable
#### NVDA version:
2024.4.1
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Chrome Version 111.0.5563.148 (Official Build) (64-bit)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
N/A
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by Adriani90** [comment]
This is expected behavior and is consistent with what we have in other windows apps such as Windows explorer. NVDA does not announce the selected attribute on selected items, but the not selected state on not selected items. So the user can easily find selected and not selected elements without having too much verbosity. Closing as won't fix.
