### ISSUE TITLE
Notepad++: braille doesn't move to the next line if last line is empty

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#17430]
### Steps to reproduce:
1. Open Notepad++.
2. In the opened document, type several lines.
3. Type `enter` to add an empty line.
4. Press `control+end` to move the system cursor to the end of the document.
5. Press `up arrow` to move the cursor to the previous line.
6. Try to run the `next line` command in a braille display.
### Actual behavior:
The cursor is not moved to the last line of the document
### Expected behavior:
The cursor should be moved to the last line of the document.

#### NVDA installed/portable/running from source:
Running from source
#### NVDA version:
source-master-c32e0e7 x86
#### Windows version:
Windows 11 23H2 (10.0.22631) workstation AMD64

#### Name and version of other software in use when reproducing the issue:
Notepad++ 7.81
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2024.4.1, with same behavior.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

[nvda.log](https://github.com/user-attachments/files/17882085/nvda.log)

**Comment by nvdaes** [comment]
@burmancomp , you may be interested in this issue.
I think that we may fix this if ww expand the textInfo to the line before collapsing to end.
I've tested it locally and seems to work.,

**Comment by irrah68** [comment]
I can reproduce this with the latest Alpha version of NVDA and Notepad++ Version 8.6.9.

**Comment by nvdaes** [comment]
@irrah68 , if you want, please test pr #17431

**Comment by irrah68** [comment]
I tested this pr, and it seems to work correctly. I can navigate to hte empty line by using braille display's navigation keys.

But I found another problem in this pr version. I tested with the latest Alpha and 2024.4.rc1 and they don't have this problem at all.

1. Type a line containing some text and press enter.
2. Add only one character.
3. Press the up arrow key and home so that you are on the first character of the first line.
4. Press Shift+End to select the content of the line.
5. Start pressing Nvda+Alt+Home and Nvda+Alt+End. You'll hear the first character of the selected line and after pressing Nvda+Alt+End the only character of the next line, though it is not selected.

**Comment by nvdaes** [comment]
Thanks @irrah68 . Now we don't expand to line before collapsing to end if selection is not collapsed.
Feel free to test this PR again.

**Comment by irrah68** [comment]
Thanks. Now it works OK.

But there is a difference when selecting a line in Notepad++ and othe editors like Windows Notepad or word.

1. Type some text and press enter.
2. Press the up arrow key and put cursor on the first character of the first line.
3. Press Shift+End and start testing with Nvda+Alt+Home and Nvda+Alt+End.

In Notepad++ the last selected character is period and in othe editors it is line break (CR-LF).

**Comment by irrah68** [comment]
OK. If you can reproduce the problem I described, perhaps it is worth new issue. This pr seems to work. No problems with a blan line and braille display's navigation keys.

**Comment by nvdaes** [comment]
@irrah68 , many thanks for testing the PR.
About selection in Notepad++, perhaps this is related to Notepad++ itself, not NVDA. I am not sure.
