### ISSUE TITLE
allow the user to specify a sequence of objects to be pronounced at once when an object is focused.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#17445]
### Is your feature request related to a problem? Please describe.
Some programs display next to the name of an object on the screen an explanatory text of what that function does. Sometimes NVDA does not announce this text, certainly due to some improper programming that occurs on a daily basis.
### Describe the solution you'd like
nvda could allow selecting a portion of the screen using object browsing with the existing commands nvda + f9 and nvda + f10, and associate this selection with the current navigation object. When the object is focused, nvda will read the selection previously made by the user.

Example steps:

Imagine a diary, where I can access a text field called name with tab.

If the user accesses this object using object browsing, notebook commands nvda + shift + right arrow and then nvda + shift + down arrow, a help text would be read, for example (type the person's name, you can also type a nickname to identify this name more easily later).

Well, the user wants the name of the name field, and the help text to be announced when accessing it with tab, and not only if exploring the screen with object browsing.

The request would be:

arrive at the object with tab.

Press an nvda command so that nvda associates the selection with this field.

Now the user will select the help text present on the screen using object navigation.
Done, now nvda will announce the field name and the selected text on the screen.
### Describe alternatives you've considered
specifying how far nvda should seek text when reading an item on the screen is subject to inaccuracies.
### Additional context
Where would I use this:
In the Windows 10 and 11 settings window, (system, about)
In a very old calendar program that I have, where the screen reader only announces editing, but if I use object exploration I can find the names of the fields.
in the control panel, where sometimes NVDA only announces the name of the link, but does not read the help text about what the item does.
and in other poorly written programs out there, where I have already spoken to the programmer and was not listened to, lol.....

**Comment by Adriani90** [comment]
To be honnest, I would never want to spend so much time to customize an application with NVDA like this. In fact, NVDA can only select what is in the currect object with NVDA+f9, and NVDA+f10. The review cursor selection does not work  outside of the current object, because you cannot select two different objects with the review cursor at the same time.
This proposal might work only in browse mode documents with the document review mode though.
I think it is preferable that the app developers associate the controls with their description properly, and then NVDA announces it as expected.

cc: @CyrilleB79

**Comment by fernando-jose-silva** [comment]
I confess that I would still do this great work to adapt some applications.
Especially when we are preparing in nvda for beginner students.

**Comment by seanbudd** [comment]
Closing as won't fix, if there's this level of technical knowledge an add-on is more appropriate
