### ISSUE TITLE
Support for Gedite text editor

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1745]
**Reported by ateu on 2011-09-02 21:46**
Thise are editors developed by Gnome Project, therefore, they are free.
Especialy Abiword, because It has advanced features.
In the first, is not possible reading content using arrow keys, but is possible to access menus.
Conversely, the secont do not allows navigate through the menus, but we can navigate for the text using arrow keys.

Thanks

**Comment by ehollig** [comment]
Closing because we do not have contact with the original author, and it is really recommended to contact the application developers to report accessibility issues first when requesting support for new programs.
