### ISSUE TITLE
Support for a free and advanced Text Editor caled Abiword

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1746]
**Reported by ateu on 2011-09-03 14:07**
Abiword is a free and open source Text Editor developed by Gnome Project, but also can be installed in Windows.
It has several useful functionalities.
It can be considered a great editor.
For now, it is possible view all the menu itens, and using flat review or object navigation, it is possible reading texts.
However, it's not possible reading using caret, so that we cannot edit using Abiword.

**Comment by Adriani90** [comment]
@ateu is this still reproducible?

**Comment by leonardder** [comment]
Since this issue hasn't received any comments in a while though @Adriani90 did a poke, I"m closing this. If this is still reproducible, please open a new issue along with steps to reproduce.
