### ISSUE TITLE
Screen reader (NVDA) focus is not moving to 'Info' icon control present beside select button, while navigating with up/down arrow keys in Windows.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#17492]
### Steps to reproduce:

1. Open the URL: https://codepen.io/Pagidimarry-Alekhya/pen/MWNVdNK in latest Edge browser 
2. Info icon page will get displayed.
3. Press up/down arrow keys to reach the 'Info' icon control present beside select button.
4. Verify whether Screen reader (NVDA) focus is moving to 'Info' icon control present beside select button, while navigating with up/down arrow keys or not.

### Actual behavior:
Screen reader (NVDA) focus is not moving to 'Info' icon control present beside select button, while navigating with up/down arrow keys in Windows.
Current Order: After select button, screen reader focus is skipping the info icon button and moving to 'Fork' button in footer section.

### Expected behavior:
Screen reader (NVDA) focus should move to 'Info' icon control present beside select button, while navigating with up/down arrow keys in Windows.
Expected Order: After select button, screen reader focus should move 'Info' Icon button, while navigating with up/down arrow keys in Windows.

### NVDA logs, crash dumps and other attachments:

https://github.com/user-attachments/assets/79eaf4f2-2c16-424f-b2a6-7e54033e14f5

<img width="960" alt="In NVDA browser mode, NVDA focus is not moving to 'Info' icon control present beside select button, while navigating with up or down arrow keys in Windows" src="https://github.com/user-attachments/assets/7314fe62-129e-4a70-9d14-311fa60ea75c">

**Comment by seanbudd** [comment]
Closing as invalid. The HTML markup is incorrect. The code has no text content, we ignore elements with no content.
In future please provide a **_MINIMAL_** HTML sample
