### ISSUE TITLE
sapi5 voices don't read with NVDA say all

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#17504]
There is a big bug in NVDA where certain sapi5 engines such as l&h sapi5 Michael and Michelle, logox-tts, and certain other NVDA addons such as older Eloquence 4.7. When you use L&H Michelle or Michael, it only speaks one word, or the first utterence when doing a say all, and then say all stops reading and refuses to continue. Sapi4 does not seem to have this issue. This is an issue with some older sapi5 tts engines and a few older synthesizers but this has to be fixed, thanks.

**Comment by Adriani90** [comment]
This is anyway a duplicate of #16691.
