### ISSUE TITLE
Cannot load sapi 5 synthesizer

### ISSUE THREAD

**Issue by burmancomp** [nvaccess/nvda#17512]
### Steps to reproduce:
Update to current alpha.
### Actual behavior:

sapi5 synthesizer cannot be loaded anymore.
### NVDA logs, crash dumps and other attachments:
ERROR - synthDriverHandler.setSynth (09:38:56.999) - MainThread (4020):
setSynth failed for sapi5
Traceback (most recent call last):
  File "synthDriverHandler.pyc", line 483, in setSynth
  File "synthDriverHandler.pyc", line 446, in getSynthInstance
  File "synthDrivers\sapi5.pyc", line 140, in __init__
  File "synthDrivers\sapi5.pyc", line 209, in _initTts
TypeError: '>=' not supported between instances of 'str' and 'int'
INFO - synthDriverHandler.setSynth (09:38:57.030) - MainThread (4020):
Falling back to previous synthDriver espeak

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
alpha-34782,82fefa5a (2025.1.0.34782)
#### Windows version:
w11 23h2
#### Does the issue still occur after restarting your computer?
yes

**Comment by irrah68** [comment]
Same happens here. Windows 11 Pro 2024H2, NVDA's latest Alpha version, Mikropuhe 5.4 Sapi 5 Speech synthesizer.

**Comment by zstanecic** [comment]
I can reproduce this bug, too with the same log lines.

**Comment by SaschaCowley** [comment]
@burmancomp , @irrah68, @zstanecic, I believe I have resolved this in #17513. If you're comfortable doing so, would you mind testing either from source or with the launcher once the AppVeyor build completes?

**Comment by zstanecic** [comment]
@SaschaCowley The I confirm that the sapi5 now loads properly.

**Comment by zstanecic** [comment]
Tested on version source-fixSapi5-d76177c x86

**Comment by irrah68** [comment]
I downloaded the pr version and it worked ok. I started and finished nvda without problems, and Sapi 5 speech synthesizer was always loaded correctly.
