### ISSUE TITLE
automatically run ocr in window after a while

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#17557]
### Is your feature request related to a problem? Please describe.
In some inaccessible programs where we use OCR to access the displayed content may be updated, which requires the user to recognize the screen several times to obtain updated recognition.

### Describe the solution you'd like
provide a box where the user can specify how often they want the OCR to stop for new recognition.
I think that in addition to this, another suggestion would be for nvda to announce if the new recognition detected any changes since the last OCR pass, this could be done by comparing the previous recognition with the current one.
Another suggestion would be if the user clicks or presses keys like enter, new text will most likely appear in the window, due to user interaction, and the OCR would then be automatically run again.
Warnings could be shown that when the OCR is run it does not always detect changes relevant to the user.

**Comment by SaschaCowley** [comment]
@fernando-jose-silva does the setting [Periodically refresh recognized content](https://www.nvaccess.org/files/nvda/documentation/userGuide.html#Win10OcrSettingsAutoRefresh) do what you want?

**Comment by fernando-jose-silva** [comment]
yes, thanks, I didn't know that.

**Comment by Adriani90** [comment]
Closing as already works with refreshable OCR.
