### ISSUE TITLE
add option to speak link before or after text

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1772]
**Reported by challsworth2 on 2011-09-11 11:00**
Add an option to the document formatting preferences dialogue box to choose whether the word "link" should be spoken before or after the associated text.

**Comment by bhavyashah** [comment]
@jcsteh In https://github.com/nvaccess/nvda/issues/1772#issuecomment-155292697, you have provided several justifications for the current order of speaking of control types. Do you maintain this stand or are you open to at least accepting a PR providing customization for the same? This probably has a non-trivial implementation cost, but I do feel that options in this case would be beneficial for many and we should leave this open as a P4 in case any developer wants to give it a shot.

**Comment by jcsteh** [comment]
We've discussed making it possible  to customise this. Use cases where this might make sense include when screen layout is disabled or if there were a future option to have pauses between control information and content. In these cases, my arguments aren't as relevant. Implementation cost is still very high, though. So, p4 for now.

**Comment by Adriani90** [comment]
Actually I think it is ok to close this in favour of #7232. The discussion is much more detailed there and covers this aspect globally.
