### ISSUE TITLE
Firefox 9 Nightly: Upon moving to book text heading, DOWN ARROW - NVDA freezes  Read All, and many other attempts in arrowing around all do not work

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1784]
**Reported by kevinchao89 on 2011-09-13 12:12**
NVDA Snapshot Main-4675

Occasionally, when logged into CourseSmart.com, reading a textbook, NVDA will freeze:
go to page, select section, and or next page;
1 for book text heading, down arrow for next line, NVDA+DOWN

Expected: NVDA to read next line and do a read all
Actual: NVDA freezes

Notes: Please see attached NVDA log with level=in/output.

**Comment by bhavyashah** [comment]
@jcsteh The original author of this ticket seems to have responded to you with the requested information in https://github.com/nvaccess/nvda/issues/1784#issuecomment-155292880. Could the same attachment please be restored as well as a quick investigation be made? Regardless, it may be very likely that this almost 6-year-old issue is no lonhrt existent.

**Comment by jcsteh** [comment]
[Read All Freeze.txt](https://github.com/nvaccess/nvda/files/1203878/Read.All.Freeze.txt)

The attached log does not show the steps I requested; i.e. pressing NVDA+f12 or NVDA+tab. Given the age of this issue, I'm going to close this as invalid, since we don't have sufficient information.
