### ISSUE TITLE
Make the Read status bar command copy its contents on third press like Report window title

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1785]
**Reported by Ahiiron on 2011-09-13 18:50**
Something I think would be nice is the ability to have the status line copied to the clipboard when pressed thrice, similar to say window title.

**Comment by leonardder** [comment]
Seems to be a useful feature and quite easy to implement, but low on priority.

**Comment by leonardder** [comment]
Added goodForNewDev label, since this might be good for a new dev :)

**Comment by derekriemer** [comment]
congrats @ehollig for your first graduated PR!

**Comment by fisher729** [comment]
Hi.

On testing this, I realise that if the status line says 'blank', NVDA on the third key press says nothing. It would be good if NVDA said 'nothing copied' or something similar, or no status line found.

**Comment by feerrenrut** [comment]
@fisher729 thanks for commenting about this, I have raised an issue for it, please see: #7789
