### ISSUE TITLE
unable to activate flat review in some rare cases in firefox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1792]
**Reported by dwillemv on 2011-09-15 05:32**
Using firefox 7, with the latest snapshot there was a stage where NVDA could not enter flat review. I could however not accurately reproduce the problem and I don't know if it is a bug in firefox.
IO - speech.speak (07:20:27):
Speaking [('en'), u'pane'](LangChangeCommand)
DEBUGWARNING - RPC process 4412 (plugin-container.exe) (07:20:27):
Thread 2152, nvdaHelper\build\x86\vbufBase\storage.cpp, VBufStorage_buffer_t::getLineOffsets, 991:
Offset of 0 too big for buffer, returning false

IO - speech.speak (07:20:27):
Speaking [('en'), u'blank'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (07:20:31):
Input: kb(desktop):NVDA+numpad7
DEBUGWARNING - RPC process 4412 (plugin-container.exe) (07:20:31):
Thread 2152, nvdaHelper\build\x86\vbufBase\storage.cpp, VBufStorage_buffer_t::locateTextFieldNodeAtOffset, 806:
Offset 0 out of range. Returnning NULL

DEBUGWARNING - RPC process 4412 (plugin-container.exe) (07:20:31):
Thread 2152, nvdaHelper\build\x86\vbufBase\storage.cpp, VBufStorage_buffer_t::locateControlFieldNodeAtOffset, 826:
Could not locate node at offset, returning NULL

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (07:20:31):
oleacc.AccessibleObjectFromEvent with window 0, objectID -4 and childID 0: [-2147467259](Error) Unspecified error
ERROR - scriptHandler.executeScript (07:20:31):
error executing script: <bound method GlobalCommands.script_navigatorObject_moveToFlatReviewAtObjectPosition of <globalCommands.GlobalCommands object at 0x062DBB50>> with gesture u'NVDA+numpad 7'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 165, in executeScript
  File "globalCommands.pyc", line 238, in script_navigatorObject_moveToFlatReviewAtObjectPosition
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects__init__.pyc", line 821, in _get_flatReviewPosition
  File "baseObject.pyc", line 21, in __get__
  File "textInfos\offsets.pyc", line 305, in _get_pointAtStart
  File "virtualBuffers__init__.pyc", line 75, in _getPointFromOffset
AttributeError: 'NoneType' object has no attribute 'location'

**Comment by dkager** [comment]
Hasn't had any discussion since 2011 and doesn't have consistent STR (as the original poster pointed out).
