### ISSUE TITLE
NVDA stops speking after pressing find now button in message find dialog box of Windows live mail

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1797]
**Reported by surveyor on 2011-09-16 12:49**
Mail Client: Windows Live Mail 2011.
Current NVDA version: Main 4691.
Press F4 to open "find message" dialog in windows live mail. 
Fill in and set requiered fields.
Press "find message" button.
Expected: You should be able to navigate around the list of found messages with arrow keys.
Current: NVDA stops speaking and does not speak until you change focus. Further more, It stops again if you refocus find message dialog with alt+tab.

**Comment by leonardder** [comment]
Closing as won't fix due to the discontinued state of Windows Live Mail.
