### ISSUE TITLE
More issues relating to currencies

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1803]
**Reported by elliott94 on 2011-09-17 10:58**
There are several issues that I've seen relating to the reading of currencies. I unfortunately have know idea why some of these are occuring, but I've tried to explain them as best as possible.

The first issue that a friend has reported seeing is that if currencies contain a comma, they are read incorrectly. For example, £1579.99 reads fine, but £1,575.99 doesn't. He's tried the following regexp to fix the problem, however it has no effect.

Regexp: ([£|$|€])([0-9]_),([0-9]_)
Replacement: \1\2\3

I've been unable to replicate this; both currencies read fine for me.

The other issue that I've been experiencing since upgrading to Snap 4634 is that, for no apparent reason, currencies on web pages are read incorrectly. I've provided a recorded example; I can't think of a good way of describing it. What's strange, however, is that some read fine, while others don't. In the example that I've given, £68.61 reads fine, but £39.99 reads as thirty nine Pounds dot 99. The even stranger aspect is that as I'm typing this, doing a Read Current Line reads the currency as it should be read.

Here's the file:
http://dl.dropbox.com/u/6662110/Currency_Test.ogg

Sorry for the trouble; I wish I could figure out what the problem is.

**Comment by leonardder** [comment]
@elliott94: It seems your file is gone.

Is this issue still present?

**Comment by elliott94** [comment]
I haven't seen this for several years now - shall we close?

**Comment by derekriemer** [comment]
The original reporter says close.
