### ISSUE TITLE
there should be an option for disabling reading of messege headers in Windows Live Mail

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1804]
**Reported by surveyor on 2011-09-17 14:14**
It's really so borring to hear message headers like from, subject, date etc each time while navigating around in a message list view. I don't know how, but it would be nice if we can disable reading of message headers while navigating.

**Comment by ehollig** [comment]
Should this be closed as WLM is discontinued? It looks like the Outlook problem has been addressed separately.

**Comment by leonardder** [comment]
I belief so yes.
