### ISSUE TITLE
User interface/experience to work with Windows 8 touch redirect

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1813]
**Reported by kevinchao89 on 2011-09-19 08:11**
Windows 8 has touch redirect, which allows for assistive technologies, such as NVDA, and is what Narrator uses to provide touch screen access, where it's possible to have this entire user interface/experience provide an interaction module, where touch will only work with the top-layer, ignore transparent background apps, and provide touch screen in/output and help. 
It would be great if NVDA could take advantage of all of this provided within Windows 8, especially the touch redirect and work within top-layer focus/apps and provide full, immersive, and natrual touch screen support, which leverages and goes beyond existing modules, such as Narrator and iOS VoiceOver.

**Comment by leonardder** [comment]
Touch support has been implemented in 2012, but does this also mean that this issue can be closed?

**Comment by josephsl** [comment]
Hi,
@MichaelDCurran, any thoughts?

**Comment by jcsteh** [comment]
Yes, this is covered by our implementation of touch support. Specific enhancements should be filed as separate issues.
