### ISSUE TITLE
Occasional loss of functions if booted up at start of windows session

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1814]
**Reported by briang1 on 2011-09-20 07:49**
This is probably going to be vague, but thought I'd ticket it as it seems to happen on more than one machine.
Basically the symptoms are these.
 If nvda is set to boot in at start up on  my xp machines, it initially appears to have been successful, but some things do not always work correctly. these include.
 Lotus Symphony main edit area no cursor or delete feedback.
Rename a folder or file in Explorer no cursor or delete feedback
Same on some save and load dialogues as well.
 The fix is always simple. just restart nvda.
 My feeling is that either something in my and certain others start up sequence is  not letting part of nvda initialise correctly, or its some timing issue.
 Its been around for a long time, but seems to be more likely since 2011.1.
 As I say, there appears no easy way to find out what is going on, as no errors are generated. You just get silence. Most other parts of nvda still operate.

**Comment by dkager** [comment]
@Brian1Gaff Is this still happening?

Sounds a bit like a missing/broken COM interface, e.g. if NVDA would start before something else that properly registers that interface.

**Comment by ehollig** [comment]
@Brian1Gaff just a friendly reminder to reply to https://github.com/nvaccess/nvda/issues/1814#issuecomment-313093015

**Comment by Adriani90** [comment]
I suggest closing this since Windows XP is not supported anymore.

Someone can reopen a new issue if it can be reproduced on Windows 7 or higher.

**Comment by josephsl** [comment]
Hi,

Closing due to NVDA system requiremenets. Please reopen if this happens on Windows 7 SP1 and higher. Thanks.
