### ISSUE TITLE
Say all for table columns

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1820]
**Reported by nik62591 on 2011-09-28 02:33**
==Say all for tables==

===Purpose===

The purpose of implementing a say all feature for tables is to allow the reading for text formatted in to rows and columns. For example, a periodical might have some text split up into multiple columns, laid out in a table. A say all feature for tables would allow the reader to read down a single column of text, rather than reading the entire first row, then the entire second row...and finally, the entire last row.

===How it should work===

If the user wishes to read a column of text, he or she should find the cell in a table that he or she wishes to start at. Then the say all for tables hot key will be pressed, reading from the current cell to the end of the current column.

**Comment by ehollig** [comment]
I believe discussion for this will take place in #1911. Closing
