### ISSUE TITLE
The last line of multi-line edit fields in IE8 is skipped or is read as the content of the entire edit field.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1829]
**Reported by mehgcap on 2011-10-10 01:52**
When in a multi-line edit field with IE8, enter some text. Press enter to make a new line, and enter more text. Now try to arrow through the field. When you land on the last line of text, it will either be read as "blank" or the entire text of the field will be read instead of just the last line.

**Comment by dkager** [comment]
I imagine this would have had more attention if it was still a consistent issue.

**Comment by jcsteh** [comment]
Also, IE 8 is very old now. Even on XP, users have the option of upgrading to a more modern alternative browser. Closing.
