### ISSUE TITLE
Support STEM accessibility

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1832]
**Reported by kevinchao89 on 2011-10-14 10:18**
Unfortunately, accessibility of science, technology, engineering, and math content (textbooks, assignments, exams, etc.) for students, professors, researchers, etc. are all very difficult. This is because of a variety of things that are lacking.

All of the following _MUST_ be met in order for STEM accessibility:

*proper speech output: NVDA to work with MathML, LaTex, an Accessible SVG. Must be fully understood, ingested, and output via speech in a effective and efficient manner. MathML and LaTex will open the doors to formulaas, equations, etc. for math, science, and engineering to be rendered in a very accessible and usable format for speech output. Accessible SVG is an area that is lacking across the board, but has great benefits for STEM graphs, charts, figures, models, etc. to be conveyed in a very powerful and functional speech output format, but it must be implimented properly.
- Braille output: full Nemeth Math Braille code support, understanding, processing, and outputting all the formulas, equations, and all STEM content in tactile braille output.
- Braille input: Ability to use braille keys to input Nemeth, for it to be understood, and back-translated into the print-equivalent.

**Comment by dkager** [comment]
I think this can be closed:

1. The scope is too broad, spanning the entire STEM field and many different technologies.
2. There is no mention of solutions to the stated problems.

For reference, MathML is now supported. See #4673.
