### ISSUE TITLE
Some Thunderbird issues

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1833]
**Reported by challsworth2 on 2011-10-14 11:49**
Please try to duplicate the following.
1. Select a message and press enter to open it.
2. The expected result is to read the subject and the message body. The actual result is NVDA is also reading the title, such as "message - mozilla thunderbird", then the subject and the body. This can be quite verbose.
3. Next, reply to a message. Now and again either NVDA or Thunderbird does not focus to the write window. Or it appears to not gain focus. However, if you alt-tab until you hear write, then all is well. The expected result is to not only focus to the write window but allow NVDA to see the focus change.
If you can duplicate any or all of the above, this will be greatly appreciated. Thanks!

**Comment by leonardder** [comment]
1. is normal behaviour if you have Thunderbird set to open the message in a new window, whereas I can't reproduce this with setting the open message behaviour to open in a new tab, which I belief is the default. Can't reproduce 3 either. Given the age of this, closing as works for me, please comment if you think I am in error.
