### ISSUE TITLE
Configurable rate for speech in non-default language

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1840]
**Reported by oaron on 2011-10-15 18:32**
I installed the latest test version of NVDA. I use the Hungarian Espeak (rate 90%), and when NVDA switches to Englis, it speaks too fast. Is it possible to create an option, wich allows to  configure a second voice (e.g. English) rate? It would be usefull 
those users, whos native language are not the English.

**Comment by bhavyashah** [comment]
@jcsteh Could you please respond to https://github.com/nvaccess/nvda/issues/1840#issuecomment-155293381? Furthermore, I believe the feature proposed in this ticket depends on the implementation of the speech refactor covered by another ticket (not sure which though). I suppose this ticket should therefore be blocked and the speech refactor ticket should be referenced, leaving this ticket open. @ehollig

**Comment by jcsteh** [comment]
Closing as a duplicate of #4738, since there's more technical discussion there and we're tracking this already. To cut a long story short, the aim is to handle this with profile triggers for languages.
