### ISSUE TITLE
Issue with braille when reading Outlook 2010 message

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1847]
**Reported by jupiterfr on 2011-10-17 08:18**
When I read a message from message list by pressing enter, speech work fine.
But my braille device through brltty doesn't show the message.
If I press twice nvda-ctrl-t the braille regain access to the message content.
This is true either if braille is attached to the focus or to the review cursor.
Another mean to regain braille access to the message is to presse nvda-ctlr-r (reload config).
This deffect has been constated with 2011-3beta1 or 2011-2.

**Comment by dkager** [comment]
Anyone with Outlook 2010 who can confirm? Can't reproduce in Outlook 2013 or 2016 with NVDA 2015.1 or later.

**Comment by Adriani90** [comment]
We do not have any feedback from Office 2010 users since two years or so. I am closing this one for now. If someone using Office 2010 and a braille display can reproduce this issue, please comment on it. We can reopen the discussion.
cc: @novalis7747, @ruifontes, @bdorer.
