### ISSUE TITLE
Bad cursor position in the cygwin's mintty terminal

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1848]
**Reported by jupiterfr on 2011-10-17 08:58**
When I use the cyngwin's mintty utility my braille refresh fine, i.e. when I modify the line, all characters appear synchronously. 
The only big problem is that the cursor position is one character after the correct position.
I would like to use this utility because all other ssh terminal such as teraterm has problem refreshing my braille display sometimes, and braille loose focus.
this problem has been constated in nvda ver 2011.2 and nvda 2011.3beta1.

**Comment by bhavyashah** [comment]
@jcsteh @leonardder Could you please assign this ticket a priority? The ticket summary seems to suggest that this is a regression as opposed to being a pre-existing bug, which may increase the value of this issue.

**Comment by jcsteh** [comment]
I don't think this is a regression. I think it just wasn't tested in earlier versions.

**Comment by Adriani90** [comment]
@jupiterfr how is this now in NVDA 2019.3.1?

**Comment by Adriani90** [comment]
It seems we've lost contact to the initial author and I didn'T hear other users having this issue. If I am wrong, then please comment and we can reopen this or create a new issue to gain more attention.
Closing as abandoned.
