### ISSUE TITLE
An appModule for Delphi 6

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1849]
**Reported by lpintes on 2011-10-17 17:50**
## What works
- Code editor
- Object inspector (properties/events list)
- Added support for speaking typed characters -- doesn't work natively
  ## What doesn't work yet
- Things dependent on highlighted text like error messages list (I am currently working on it)
- Error messages must be read with flat review
- it is probably impossible to close the error messages list -- Nvda is unable to locate the "close symbol". Jaws can see it, so it is probably not the regular close button.

**Comment by leonardder** [comment]
Is it true that the attachments to this tickets are lost in the migration to github?

**Comment by ehollig** [comment]
@leonardder, I have restored the attachments in https://github.com/nvaccess/nvda/issues/1849#issuecomment-155293448 and https://github.com/nvaccess/nvda/issues/1849#issuecomment-155293449

**Comment by Adriani90** [comment]
@lpintes this app module seems to be lost in the bunch on issues here on github. Are still on github and able to raise a pull request for it to be included in NVDA?
