### ISSUE TITLE
NVDA misses focus When opening a new browser window from an existing one

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1851]
**Reported by dgoldfield on 2011-10-17 20:59**
In 2011.3 beta 1 NVDA does not refresh its buffer when loading a page on top of an existing window.  Going from page to page normally works fine; when a new browser window opens NVDA does not always show the buffer.  I can usually get it to display the newly loaded page if I press alt to move focus to the menu bar and alt again to bring focus back to the Web page.  This is very consistent with Seamonkey and somewhat intermittent with Firefox 7.0.1.

**Comment by leonardder** [comment]
CC dgoldfield

This issue is rather old, and I can't remember experiencing this. Closing around this time next week if no other info is provided.
