### ISSUE TITLE
NVDA should give feedback with FREE Hi-Q Recorder

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1862]
**Reported by ManuelRamos on 2011-10-23 23:09**
I'm looking for a good software that works with NVDA to record sounds like play lists, radio broadcasting transmitions, etc. For example, I created a play list that is sounding, but now I am wanting to record it to a mp3 file to carry out a cd. Helpfull also when broadcasting.

So, when googling for it, I found that software, refered in summary, that it is not yet compatible with NVDA. It would be grate if it can work it our screen reader because, not onlin NVDA, but also FREE Hi-Q Recorder are free software.

**Comment by ehollig** [comment]
Closing, because the original author did not specify what problems they were having with the application. Also, it is recommended to contact the application author and request that their application be made more accessible.
