### ISSUE TITLE
Interact with help balloons

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1864]
**Reported by challsworth2 on 2011-10-26 10:56**
When a help balloon is displayed, allow the user to interact with it by simulating a left mouse click.
**Blocking #3235, #5101**

**Comment by bhavyashah** [comment]
IMHO, proper access to help balloons should have been looked into years ago given the clear demand for the same. Regardless, given that Windows 10 uses toast notifications which I believe are accessible, and clearly, Windows 10 is the future and not Windows 7/8.1, I suppose the priority of this feature is no longer high. Thoughts?

**Comment by Adriani90** [comment]
Support for Windows 8.1 ended in January 2023 so I don't expect any further accessibility updates to that Windows version.
Dropbox notifications are displayed in the notification center in Windows 10 and 11 which can be accessed by pressing windows+a or windows+n shortcut.
I am closing this issue as works for me. If you are still having it, please comment and we can reopen.
