### ISSUE TITLE
When viewing search results for the catalog of my local public library NVDA appears to freeze, not allowing navigation and saying "desktop window" when I exit and re-enter the window.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1876]
**Reported by dgoldfield on 2011-10-31 18:30**
I regularly use the Web site of my local public library to search for items in their online catalog.  Search results used to read properly, with each item in its own heading, allowing me to press H to move from one item to another.  While I am able to access the initial page I am no longer able to access the results page with either Seamonkey 2.4.1 or with Firefox 7.0.1.  Here are the steps if the problem can be duplicated.
1. Go to http://ilsapp.lib.de.us/uhtbin/cgisirsi/x/x/0/49/
2.  You should be in a search edit box for the local catalog; if not move to the edit box and type in a book title and press enter to begin the search.
3.  NVDA appears to freeze, not allowing any navigation to take place with arrow keys.  
4.  Now temporarily leave the window by pressing the Windows key to open the start menu.
5.  Press the Windows key again to close the start menu and to return to the catalog search results page.  NVDA may say "desktop window" though it does not always say this.  It is still unresponsive until I close the page.  
I have tried reverting to 2011.2 but the problem persists.  I am wondering if it's something new introduced in FF/Seamonkey in a recent version?
To make matters more confusing this problem does not occur at all using FF 7.0.1 on my faster Windows7 machine at work.  I will admit that my XP machine at home has specs which are lower than what NVaccess recommends for use with NVDA but the site used to work reliably all of the time and the library claims that they've changed nothing in the page as far as they know.

**Comment by bhavyashah** [comment]
The original author of this ticket seems to suggest in https://github.com/nvaccess/nvda/issues/1876#issuecomment-155293977 that the reported issue is unrelated to NVDA. Time to close? @ehollig
