### ISSUE TITLE
Flash player based chat is not working correctly while using one system to realize WEBINARS. When first chat message have been sended, user can not jump to The editbox for writing chat message again. Even while triing to jump to The editbox for writing chat messages by disabling virtual browsing temporalily, NVDA is not able to monitor The written text when user is pressing arrow keys. NVDA can work ammazingly, when writting first chat message. But when user press ENter, or when user activate send button even without virtual browser active,

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1878]
**Reported by janusz on 2011-11-01 12:26**
Dear core developers of NVDA,
NVDA is according to my opinion The worlds most advanced screen reader. And why I AM thinking so? Because NVDA is now support Three various web browsing engines. Chromium based, Gecko based, and Microsoft rendering engine based. And, what is very important for many visually impaired users through out  The world, NVDA is supporting WEB pages, which are using Adobe flash player objects not only for streaming and playing various multimedia content.
NVDA is amazing assistive technology for visually impaired individuals, who would like to fully valuably participate on various WEBINARS.
I Am testing one WEBINAR service available in our country.
This system is Omnif.
Now, I AM learning, how to allow some user to visit my chat room in trial test mode.
For now, I Am having issues with NVDA while sending A chat messages. While typing first chat message, all characters can be comfortably reviewed by using standard Windows shortcuts for moving inside editable fields. But this amazing NVDA behavior stop at The moment, when I AM pressed The enter key while typing chat message inside The editable field. NVDA is having following issues.
NVDA virtual buffer quick navigation keys are not able to find editable field.
When using INSERT+SPACE keyboard shortcut, to disable virtual browsing mode, when using TAB to get to The editable field for writing new chat message, NVDA can not cooperate with keyboard shortcuts for moving inside The editable fields. Such as left or right arrow key. This behavior is happening only, when first chat message have been send. It is impossible to fix this issue even after closing and restarting NVDA, INSERT+F5 shortcut for restoring virtual buffer not help.
My conclusion is, that user interface of WEBINAR service is making something with focus, because there are several TABS for controlling various aspects of this webinar service.
But even though I have tried to press right or left arrow key when NVDA announced ME The TAB, editable field with text for writing chat messages have not been reachable when  pressing e letter for finding editable text. 
Thank You very much for Yours programmers help.
The question is, if this issue can be solved by modifying NVDA source code, or Adobe corp would had to make new accessibility enhancement. Or, if The developers of Flash player code incorporated in to The Omnif WEBINAR system would had to make some modification to The user interface.
I AM not getting exception from NVDA, so this error is not syntax error, it is problem for debugging.

**Comment by dkager** [comment]
As a minimum the issue title should be chopped down a bit. :)

**Comment by jcsteh** [comment]
Requested info not provided by reporter, plus Flash is more or less abandoned these days, both by Adobe and most implementers. Closing.
