### ISSUE TITLE
Create an option to reduce braille output while tethered to focus

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1884]
**Reported by ianr on 2011-11-04 16:17**
In certain applications I would like to have braille tethered to focus all the time so that I can easily use routing keys in edit boxes.  I find that tethering to focus works well for most editing areas of text editors, but when you switch to menus or treeviews in the same application focus mode becomes too verbose in comparison to review mode.

One example is the address bar of mozilla firefox.

Here is the text in focus mode:
Google - Mozilla Firefox property page   Navigation Toolbar tool bar Go to a Web Site Go to a Web Site + cbo ... edt www.google.com

Here is the text in review mode:
... edt www.google.com

Another example is when you are in the treeview of visual studio.
Here is the additional text that is placed in front of any treeview item:
MyProject - Microsoft Visual Studio (Administrator) window tv 

My suggestion is to add an option in the braille config section that allows you to turn off the output of parent control text and type names when tethered to focus.

**Comment by dkager** [comment]
We are doing this in #7236 as a fix for #217. Instead of completely hiding the ancestry there will be an option to scroll it out of the way by default.

**Comment by jcsteh** [comment]
Closing as duplicate.
