### ISSUE TITLE
NVDA should know how to handle soft carriage return (\0xb) in Microsoft Word

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1899]
**Reported by Bernd on 2011-11-10 21:26**
At the moment if you route the system cursor to this symbol NVDA reads all lines splitted by it. The braille display shows points 1378 for it. I think nvda should split the line on this sign and work with it as a carriage return.
**Blocking #4587**

**Comment by bhavyashah** [comment]
@jcsteh What priority would you deem appropriate for this ticket? From the sound of it, this seems to be a quick fix, in which case a higher priority would be justified. CC @leonardder @dkager @derekriemer and others

**Comment by Adriani90** [comment]
@leonardder is this issue still occuring? Unfortunately I currently don't have any braille display to test it.

**Comment by Adriani90** [comment]
@Bernd

**Comment by bdorer** [comment]
I'm not able to reproduce this Bug with Word 2013 and NVDA 2018.3Beta2.

Am 27.07.2018 um 16:48 schrieb Adriani90:

**Comment by leonardder** [comment]
In that case, closing as works for me.
