### ISSUE TITLE
Jango.com: Use Screen Layout Off Has No Effect

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1904]
**Reported by jhomme on 2011-11-13 12:37**
Hi,
Using Firefox, Go to http://www.jango.com.

If you do not have an account, you may need to crate one.

Try to use screen layout off and you will see that hyperlinks are inline with the rest of the text on screen. This is with the snapshot version from 12 November. The number is 4792.

**Comment by leonardder** [comment]
Due to the age of this ticket, it is very likely that this has been fixed now.
