### ISSUE TITLE
Support for code editor in Visual C++ express 2008 and Visual C# express 2008

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1906]
**Reported by lpintes on 2011-11-14 10:05**
Implementation of TextInfo based on the accessibility information provided by VsTextEditPane.
I also attached two app modules, one for VC++ and one for VC#.
I suspect that VB could also work, not tested.

**Comment by bhavyashah** [comment]
Is it a patch that has been attached in https://github.com/nvaccess/nvda/issues/1906#issuecomment-155294151 or is it diagnostic information?

**Comment by ehollig** [comment]
The attachment is a patch. @feerrenrut should this code be looked into, because it sounds like it is only for VS 2008?

**Comment by feerrenrut** [comment]
If including this patch allows us to provide better support to users who have to work with Visual studio 2008 then we should. However we should see if there is anyone who will volunteer to test this patch (or a try build of NVDA with this patch included). If there is any significant cost associated with this including this patch (EG developer time to integrate the patch, maintenance difficulty, or testing) then we will need to more carefully weigh that cost against the benefit it will bring users. Which would require us to get some kind of idea of how many users it would help.

**Comment by Adriani90** [comment]
@lpintes I guess you tested this. Right? ARe you still enhancing it? Or is it only for VS 2008?
@feerrenrut this patch could be implemented in a beta version and users will automatically give feedback on it. If it causes problems it can easily be taken out of the development snapshots. What do you think? At least we can be sure that there will be valuable feedback in a short time range.

**Comment by leonardder** [comment]
Given Visual Studio Express 2008 is really, really old and it is really hard to maintain support for all these old versions, I"m closing this. If it is really important for someone to have this support, it is probably best to include it in an add-on.
