### ISSUE TITLE
NVDA is stuttering on parts of the m.facebook.com website

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1910]
**Reported by challsworth2 on 2011-11-15 20:33**
Please try to duplicate the following.
1. Go to http://m.facebook.com.
2. If you are not signed in already, do so now.
3. Press enter on the messages link.
4. Press enter on the link to one of your friends who have posted.
Expected result: same as actual result (see below), except NVDA shouldn't stutter at all.
Actual result: On this page, NVDA stutters before speaking the actual text. For example, if you down arrow or press b until you hear apply button, you will hear what sounds like a apply button.
This seems to be hard to reproduce as it does not happen all the time, but if you can do so this would be great! Thanks!

**Comment by dkager** [comment]
Reasons to close:

- Doesn't always happen (as noted by the poster).
- This website definitely has changed since 2011.

**Comment by leonardder** [comment]
Also note that the layout of this web app differs between browsers

**Comment by jcsteh** [comment]
Closing. Please reopen if you can still reproduce this and provide details.
