### ISSUE TITLE
Within Open with dialog, select browse, TAB to search, and NVDA errors

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1922]
**Reported by kevinchao89 on 2011-11-19 06:09**
winwordTextInproc-4800

Navigate to any file;
Application/context key/menu;
Open with>choose default app>browse;
TAB a few times to search

Expected: Search box, label and contents to be spoken
Actual: NVDA errors

Regression: No, I've seen this for a while now, even with 2011.3 RC, current, and previous snapshots

Notes: Please see attached log

**Comment by bhavyashah** [comment]
@jcsteh As indicated in https://github.com/nvaccess/nvda/issues/1922#issuecomment-155294289, has this issue been reported to Microsoft? Please let us know in case there has been any work from Microsoft in this regard.

**Comment by jcsteh** [comment]
It hasn't. However, this doesn't occur in Windows 10. Since Microsoft are really focused on Windows 10 now, it's extremely unlikely this would get fixed in earlier versions. Also, while annoying, it's not a total show stopper: you can still locate a file in these apps. Closing as can't fix.
