### ISSUE TITLE
PSPad mode problem

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1924]
**Reported by oogi on 2011-11-19 15:54**
I am using PSPad editor (text editor with special functions for programming etc.) and it is not for me possible to use it in editor mode, I can use it only in reading mode, so the reading cursor stays on the first line of document and does not follow text cursor. Shortcut NVDA + space bar does not do anything with the mode and I have not found another solution.
Standard Windows Notepad works in editor mode without problems.

**Comment by bhavyashah** [comment]
From @jcsteh's https://github.com/nvaccess/nvda/issues/1924#issuecomment-155294296, it seems that this ticket requires the NeedsExternalFix label at the very least. Also, the age of this issue and seeming lack of information makes me lean towards closing. @ehollig

**Comment by ehollig** [comment]
As @jcsteh said in https://github.com/nvaccess/nvda/issues/1924#issuecomment-155294296, it would be better if the application developer can implement accessibility in a more reliable way. Closing as wontfix
