### ISSUE TITLE
Latest Two Female ESpeak Voices Are Missing From Within Varients List.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1927]
**Reported by trenton on 2011-11-19 16:46**
The two newest ESpeak voices, F5, (Female 2 with a whisper,) and WhisperF, (Simply The ESpeak variant  "Whisper" as a female,) are both missing within the variant list of voices, whether using the Synth's ring, or the ctrl-NVDA-V dialog.
You can find both thse both in the NVDA Espeak Data Voices V! folder, however they're not usable.

Any newer voices that people create Using the ESpeak edit program, or by modifying an existing voice and changing its name, show up without a problem. Its just these two.

**Comment by ehollig** [comment]
Female 5 and Female_Whisper are available in the variant combo box. If this was a problem, it is not anymore.

**Comment by derekriemer** [comment]
closing, worksforme
