### ISSUE TITLE
Apple.com, navigate to iTuens link, and cannot ENTER to activate

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1930]
**Reported by kevinchao89 on 2011-11-19 23:05**
Firefox 11.0a1 (2011-11-19)
NVDA_snapshot_webKit-4739

Throughout the Apple.com website, e.g. iTunes link, each step along the way to view details and to the point of downloading iTunes, it's not possible to press ENTER to activate the element.

Apple.com;
NVDA+F7 for elements list;
type "iTunes";
ENTER

Expected: iTunes link to be activated and to be brought to iTunes page
Actual: Nothing

Regression: yes, not sure if something changed at Apple's, Mozilla's, or NVAccess's end.

Notes: 
When focused on element, it's possible to use NVDA+SHIFT+F9 to RouteMouseTONavigatorObject and NVDA+LEFT to perform a LEFTClick, which will activate the element.

Following was tried, but does not work:
NVDA+PAGE DOWN to move to object within flat review will report paragraph;
NVDA+SHIFT+F9 will report desktop;
NVDA+LEFT will click desktop.
Note: Resetting zoom with CTRL+0 and repeating above steps yield same results.

**Comment by dkager** [comment]
Can open this link without problems on the current version of apple.com with Firefox 54.0.1.
