### ISSUE TITLE
Firefox: Opening link in new tab and switching among tabs sometimes will report incorrect content

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1931]
**Reported by kevinchao89 on 2011-11-19 23:12**
Firefox 11.0a1 (2011-11-19)
NVDA winwordTextInproc-4800, 2011.3 RC, and previous snapshots

At times, but not always, when opening a link in a new tab, switching focus to that tab, and reviewing contents. the tab title is reported correctly when switching to it and checking tab title, but content that is reported with report current line shows info from tab I was just in. Other times, when cycling among tabs that are currently open, which doesn't involved opening links in a new tab, NVDA will have this same issue, where when cycling among tabs, it will report tab title correctly, but the content will be from the tab I initially was on or the one before the tab that I stopped on.

I think that this may be due to a Firefox Nightly issue, but not exactly sure.

**Comment by bhavyashah** [comment]
The STR is not too clear, but I don't believe I have experienced such issues in recent stable Firefox builds. In case no one else has encountered the described behaviour in the recent past either, I suggest closing. @ehollig

**Comment by Adriani90** [comment]
I cann not really reproduce this. Is anyone able to reproduce it?

cc: @jcsteh

**Comment by jcsteh** [comment]
Haven't seen this myself, nor have I seen reports of it occurring. Closing.
