### ISSUE TITLE
Optionally Quieting Graphics Within Browse Mode

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1932]
**Reported by trenton on 2011-11-20 00:57**
At this moment in time, NVDA has no way of silencing Graphics while in browse mode, frames within browse mode, and Access keys next to links within browse mode. 
Can there be options in the CTRL-NVDA-D dialog, for those to be toggled individually? 
Note, you can toggle speaking of Access keys off from within the CTRL-NVDA-O dialog, however it does it for both Access keys on web pages, and for menus in general.

I set the type setting as, enhancement, Within browse mode.

**Comment by ehollig** [comment]
Closing because this is being covered by #4837 which already has a priority.
