### ISSUE TITLE
Word 2010: need a way to query cursor position, i.e. how many inches from margin - very useful for formatting

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1939]
**Reported by kevinchao89 on 2011-11-20 07:19**
Word 2010
winwordTextInproc-4800  

There’s no way to query for cursor location, which is useful when formatting document’s, especially when one is instructed or needs to
have certain bits of text  so many inches from margins (left, top,
etc.), e.g. text needs to be centered and 4 inches from bottom of
page.
**Blocking #5127**

**Comment by ehollig** [comment]
Is this something that can be retrieved from the NVDA+Del command? CC @michaelDCurran @bhavyashah

**Comment by bhavyashah** [comment]
@ehollig I have never practically used the NVDA+Delete key command. However, pressing it reveals how much percentage above, below, left or right of an edge of a screen the current text or navigator object is. This is helpful but I don't think it adequately addresses the original feature request of actually reporting how many inches from a particular margin something is. @Qchristensen Do you have any views on the amount of solvency of the existing NVDA+Del command with regards to this ticket?

**Comment by Qchristensen** [comment]
The NVDA+Delete command does work as Bhavya describes in many cases, however, there are situations where it has been overwritten in order to provide more useful information, for instance, to give the sheet and cell location in Excel.  I think having it provide the location of the cursor is a useful use-case.

**Comment by ThomasStivers** [comment]
As a work-around I have the below macro in my normal document template for word. When I press Alt+Delete I get a message box with the information. Adding the relevant call(s) to the Word appModule should be easy.

```
Sub HorizontalPosition()
'
' HorizontalPosition Macro
'
    hLocation = Selection.Information( _
      wdHorizontalPositionRelativeToPage)
      vLocation = Selection.Information( _
      wdVerticalPositionRelativeToPage)
      hInches = Round(PointsToInches(hLocation), 2)
      vInches = Round(PointsToInches(vLocation), 2)
      Page = Selection.Information(wdActiveEndPageNumber)
    MsgBox hInches & " inches from left, " & vInches & " inches from top, page " & Page & ".", vbOKOnly, "Cursor Location"

End Sub
```

**Comment by nvdaes** [comment]
Hello: A kind call to @michaelDCurran and others: Is there any progress on this?
A user of a NVDA spanish mailing list is requesting this feature and provides these use cases:
* If the subject of certain documents is distributed into several lines, the margins need to be the same for each of these lines.
* It's also useful to check if a line signature is properly positioned respect the name.
* To insert a picture at the bottom of a page containing text, knowing its size, a procedure to check the current position it's needed too.
Thanks for addressing this.
The request on the spanish list can be found at
https://nvdaes.groups.io/g/lista/message/314
Cheers
