### ISSUE TITLE
Firefox: Gmail.com, within list of messages, navigate to next column, and NVDA errors

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1941]
**Reported by kevinchao89 on 2011-11-20 08:45**
Firefox 11.0a1 (2011-11-19)
NVDA winwordTextInproc-4800

GMail.com Basic HTML;
x to checkbox, which drops you into table, containing list of messages;
CTRL+ALT+RIGHT to next column

Expected:  NVDA to read people involved in conversation
Actual: NVDA errors

Notes: Please see attached log

**Comment by ehollig** [comment]
I can not replicate this using latest NVDA and Firefox 54.0.1

**Comment by derekriemer** [comment]
closing, worksforme
