### ISSUE TITLE
Firefox/IE: move to next/previous paragraph should ignore blank lines and go to text/HTML elements

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1952]
**Reported by kevinchao89 on 2011-11-23 00:52**
OK I'm using both IE 9, and Firefox 8. I've tried this on both browsers with NVDA snapshot 4800. If I go to a page like:
http://www.sryth.com/
When I hit control+down I will through the page have to hit this several times to get to actual text. I'll just hear blank, blank, blank. One instance of this is just above the date at the top of the page. Another is right above the play/sign up area. I find that this happens quite a bit, so was wondering if there could be a way to ignore extra blank lines, or white space. At least in browse modes...

**Comment by ehollig** [comment]
Sounds related to #4904. CC @derekriemer

**Comment by ehollig** [comment]
Closing in favor of #4904, as it has a priority and an associated PR.
