### ISSUE TITLE
Randomly switching from focus to browse mode in multi line edit boxes.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1958]
**Reported by kara_louise on 2011-11-24 21:36**
When  reading by character in a multi line edit field such as this one, NVDA will randomly switch from focus mode to browse mode, causing you to move to whichever element is in the direction you were going.  Hitting the opposite arrow  immediately after will put you back in the edit field with focus mode enabled, and  the cursor will be in the same place before this occurred.

I have only seen this happen in firefox.
I originally thought it may happen when the cursor raps down a line, but it appears not to be the case.

**Comment by bhavyashah** [comment]
@jcsteh As noted in https://github.com/nvaccess/nvda/issues/1958#issuecomment-155294544, has the raising of timeout been reconsidered ever since?

**Comment by jcsteh** [comment]
The timeout was raised in #7201, so this should effectively be fixed.
