### ISSUE TITLE
Separate the reading of structural elements from the text inside them.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1965]
**Reported by ashleycox on 2011-11-26 16:39**
Currently, when reading a webpage or document with NVDA that contains structural elements (lists, landmarks, tables, etc), nvda will announce the element exists (if you have it set to do so) and then will proceed to read the text or content that is contained within. However, this is inefficient in some instances; for example, if tabbing through a page that contains a number of lists to hear each link, you have to listen to NVDA read "list with x items" "out of list" at any point where a link comes first in a list. The same is true if arrowing down a page, for example at the top of this creat new ticket table; you have to hear the existance of the table, before the word "summary". I feel that an option should be provided to change this behaviour, so that the structural item information is before the first item within, and ends after the last item within; for example, arrowing down a page with a list, you would hear "list with x items" and then, a second arrow down would be the first item. Similarly, when you reach the last item, another down arrow would be necessary to hear "out of list". I feel that even if this weren't the default behaviour (which in my opinion it should be), having this option would make navigation for users who like to quickly read pages, or like reading links with the tab key much easier and more efficient.

**Comment by leonardder** [comment]
This is also how JAWS does this. Honestly, I have list reporting disabled in browsers as I find it too verbose.

**Comment by jcsteh** [comment]
The problem with this is that there is no actual position for the start of a list or table; it's just meta information. In the world of virtual buffers (where you can generate arbitrary text as you wish), this might be possible, but we're slowly moving away from this. There are also questions about how to handle this when you start bringing editable text into the mix. Certainly, I don't think this makes sense in something like Microsoft Word. You can argue that Word is different to the web, but actually, we're starting to see some pretty big rich text editing implementations on the web (Google Docs, etc.) and it'd be useful to support browse mode there too and have it synchronise with the editing cursor.

**Comment by Adriani90** [comment]
Related to #7860

**Comment by Adriani90** [comment]
Closing as duplicate of #3997 which contains more discussion.
