### ISSUE TITLE
sentences are joined together when last word in the first is a link.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1972]
**Reported by kara_louise on 2011-11-29 02:56**
This is most noticeable on Wikipedia.
If a sentence has a link at the end, NVDA will say "dot" before reading the next sentence without pausing between them.
So for example: you're reading an article about Oasis, and it says "Oasis were formed in Manchester. Their first album was Definitely Maybe." The word Manchester would be a link to an article about the city. It'd then say dot, then without a pause continue reading the next sentence.

This occurs in both firefox and IE. I'm running the latest nightly build of Firefox and the latest stable release of IE, with NVDA 2011.3.
I've tried various tts engines with the same result.

I hope I've made myself clear enough.  :)

**Comment by jcsteh** [comment]
This is a duplicate of #1475.
