### ISSUE TITLE
different handling of usemaps with different browsers

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1985]
**Reported by dave090679 on 2011-12-05 16:08**
when I'm loading a web page which is using usemap imagemap links (e.g. www.netbank.de), Internet Explorer, Firefox and google Chrome behave slightly different (tested in Windows xp with nvda r4823). When using Firefox 8.0, the imagemap links are displayed correctly. When using Inter explorer 8.0.6001.18702, the imagemap links are only displayed as unlabeled links (only "lnk" is displayed). in Google Chrome 15.0.874.121 m, the imagemap links are not displayed at all.

to reconstruct what I mean, you can try to find the online banking login links at http://www.netbank.de/nb/onlinebanking.jsp.

**Comment by ehollig** [comment]
Unless I am missing something entirely, I am not able to locate the imagemap on the URL provided. If this is still the case, please create a new issue with updated information including:

- Latest NVDA
- Versions of Chrome, Firefox, and IE used
- An example where this issue can be located

Closing. CC @jcsteh
