### ISSUE TITLE
NVDA's  Table Reading Commands with LibreOffice Writer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1994]
**Reported by Shah on 2011-12-11 08:54**
NVDA's table reading commands--Control+Alt+Arrow keys--do not work in LibreOffice Writer. I am using LibreOffice Portable 3.4.4.

**Comment by leonardder** [comment]
Confirmed for the IA2 based version of LibreOffice.

**Comment by bdorer** [comment]
This issue exists with current version of libreOffice.

**Comment by Adriani90** [comment]
Closing in favor of #4133
