### ISSUE TITLE
Disabling of speaking of "space" while typing

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1997]
**Reported by td.dinakar on 2011-12-13 10:58**
Speaking of spacebar while typing seems to be an irritant and it also reduces the speed of typing. Therefore, speaking of "space" while typing should be disabled when the "Speak command keys" is disabled.  If this is not possible, an alternative should be worked out.

Thanks,

**Comment by bhavyashah** [comment]
@jcsteh Am I correct in understanding that an option specifically to toggle the reporting of space is being requested and agreed to here? If so, I consider such an option to be quite unnecessary and a redundant overkill. I am not convinced we should accept this feature request in the first place. Thoughts?

**Comment by Adriani90** [comment]
In my opinion, space is also a character. So if you disable character reporting and enable word reporting instead, space will not be spoken anymore. So I vote closing this issue as worksforme.

**Comment by josephsl** [comment]
Hi,

Please reopen once folks come up with really good justifications as to why this option should be added. Thanks.
