### ISSUE TITLE
Focus 40 USB braille display : "Unable to load freedomScientific teminal"

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2004]
**Reported by del65 on 2011-12-17 23:31**
I followed the instructions to install the "focus blue" driver from the Freedom Scientific website with the link provided in the NVDA User Manual.

Even when installing this driver or running NVDA with administrator rights I obtain the same error message when switching from the default "brltty" braille display driver to the "Freedom Scientific series Focus/Pac Mate" braille display driver.

The log event viewer (journal) show the following trace :

ERROR - braille.BrailleHandler.setDisplayByName (00:12:07):
Error initializing display driver
Traceback (most recent call last):
  File "braille.pyc", line 1024, in setDisplayByName
  File "brailleDisplayDrivers\freedomScientific.pyc", line 124, in **init**
RuntimeError: No display found
INFO - braille.BrailleHandler.setDisplayByName (00:12:07):
Loaded braille display driver noBraille

Operating system : Windows 7 (32 bits)

**Comment by dkager** [comment]
Looks abandoned.
