### ISSUE TITLE
Missing python library modules on binary distribution to be used within plugin

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2008]
**Reported by ragb on 2011-12-20 17:14**
I came around this issue when writting aplugin that imported the urllib2 module. Running from source everything went fine but within a binary distribution (installer or portable) I found that py2exe did not distribute that module. That happens because NVDA itself does not need that code, I supose. This might happen with many other python standard library modules and packages.

So we have one of two problems to solve in NVDA: we document what modules are provided within the binary distribution and plugin writers must stick to those modules (or find alternatives to package the code they need);
or bundle many more modules within the binary dist. The problem with this approach is that the distribution size might increase too much and one does not really know what modules a plugin would need to make fundamented choices...

Regards,

Rui Batista

**Comment by ehollig** [comment]
Any thoughts on this issue? CC @jcsteh @josephsl and others

**Comment by leonardder** [comment]
@ragb: Could you provide a rationale on why you think urllib2 should be preferred over urllib?

@josephSL: Do you use urllib2 in the add-on update mechanism?

**Comment by josephsl** [comment]
Hi, not just yet, as I want to make sure the basic implementation is ready (making sure I and NV Access work on a server implementation and the database). See #3208 for details. Thanks.

**Comment by jcsteh** [comment]
I vaguely recall that urllib2 has better support for system configured
proxies, but I looked into this a long time ago, so I'm not sure.

**Comment by leonardder** [comment]
If urllib2 is backwards compatible, it is as easy as changing the import and the function calls in updateCheck, however, that might break compatibility with add-ons depending on urllib.

**Comment by josephsl** [comment]
Hi, I’ll do some initial investigations as part of #7105. Thanks.

**Comment by jcsteh** [comment]
It's not backwards compatible. Also, we access the socket to change the
timeout, which is private and in a different place with urllib2.

**Comment by Adriani90** [comment]
@josephsl any new thoughts on this issue?

**Comment by josephsl** [comment]
Hi,

As of now, more modules became part of NVDA's binary distribution, including six, json, and possibly others. Urllib2 is a separate issue.

Overall, I tend to favor add-on authors bundling needed modules by hand.

I'll close this for now unless someone comes up with a really good justifications for including modules other than urllib2 via py2exe.

Thanks.
