### ISSUE TITLE
added support for the list items when typing NVDA+F7 (Elements list)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2009]
**Reported by jfauchon on 2011-12-21 11:06**
added detect edit list, checkbox lis, table list, zonelist,button lis, object lis, radiobutton list, graphic list, forms list to the list items when typing NVDA+F7

**Comment by PigeardSylvain** [comment]
At least the form fields list must be available. This list is available using Jaws and lot of users can't do without.

**Comment by josephsl** [comment]
Hi, If you don’t mind, you might want to create a new issue regarding this (commenting on an old issue just to provide suggestions isn’t an ideal thing). Thanks.

**Comment by bhavyashah** [comment]
@leonardder has been working on adding various elements to the Elements List recently. Leonard, could you please elaborate on the new elements supported by the Elements List dialog once you work is incorporated and accordingly triage this (probably as a duplicate)?

**Comment by Adriani90** [comment]
@paulber007 I think you have created a Microsoft word add-on which enhances  the element list. Are you planing to continue that work, maybe raising any pull requests?

In my view, form fields is necessary in word and MS Excel, but not in browsers. Also, we have to split element list in browsers from the one in MS Word and MS Excel.

**Comment by Adriani90** [comment]
No meaningful contributions to this sofar, I am closing as abandoned. Please create new issue regarding form fields and separate issues for other elements that you thing might be important.
