### ISSUE TITLE
decrease nvda verbosity in the windows 7 start search area

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2020]
**Reported by jmwalton on 2012-01-02 07:21**
when you search in the windows 7 start menu search box, nvda speaks "items view list, programs, program" as an example. i feel that it would be better if it were to just say the search results as they come up. an example there would be you search for "update" and nvda would speak "windows update" not "items view list, programs, windows update."

**Comment by ehollig** [comment]
While I see that this can be annoying at times, it is not life threatening. The information that is provided lets the user know where they are in the search. What do others think?
