### ISSUE TITLE
NVDA begins to slow down and/or unload from memory after several hours of use

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2022]
**Reported by louie12000 on 2012-01-03 03:55**
After several hours of use, NVDA will begin to slow down and/or unload from memory. This issue mainly occurs in Internet Explorer.

**Comment by dkager** [comment]
Having used IE in Windows 7 and 10 for a few months last year I can't say I recognize the symptoms.

**Comment by jcsteh** [comment]
Closing. Please reopen if you can reproduce this and provide thorough details.
