### ISSUE TITLE
Braille with BrlTTY freezes

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2033]
**Reported by mwhapples on 2012-01-07 22:21**
There are occasions when Braille output using BrlTTY will freeze and from that point on NVDA does not update rthe Braille display. Even when I exit NVDA after this issue occurs the Braille display maintains the Braille which was displayed when Braille output froze. One work around I have found to enable Braille again is to quit NVDA, then unplug my Braille display (its an ALVA 544 being used through USB) and then plug the display back in (I plug it back in to the same USB port) and then restart NVDA. While I can use this work around, as the issue can show itself fairly quickly (sometimes within a minute of starting use) it is quite annoying and makes Braille inpractical for use. While I hve no specific cause, it seems to generally occur when there are quick and frequent updates to the Braille, for example it quite often occurs when I am typing in the run dialog of windows. Typing seems to be the most common cause, I guess because it is an activity where Braille is frequently being updated quickly, but I have encountered it at other times, for example whn moving through the list of messages in Windows Live Mail. I am uncertain awhethe the issue is in NVDA or BrlTTY. I can try and get a debug file of the problem occurring and will attach one to this ticket when I have one. Is thre any other information or activities I can perform to help in finding th source of this issue?

**Comment by bhavyashah** [comment]
Various comments on this ticket by the original author indicate that this issue lies with the Braille display and not NVDA itself. Given that this issue is more than five years old, unless our resident Braille experts recommend otherwise, I suggest closing. @ehollig

**Comment by Adriani90** [comment]
@ehollig what do you suggest?

**Comment by ehollig** [comment]
Thank you for finding this issue @Adriani90. I should have closed this issue months ago. Closing as invalid
