### ISSUE TITLE
Support relations providing live updates

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2036]
**Reported by mwhapples on 2012-01-09 14:19**
In eclipse's SWT there is a snippet showing how one can use a relation to provide live updates to access technologies, a description of this can be found at http://www-03.ibm.com/able/news/eclipse_introduces_iaccessible2.html#using_relations

According to the page linked to here this facility is provided by IA2 on windws. However when I tried snippet 340 which is an example the above page refers to showing this function in action, NVDA does not read th updates being made.

This ticket is a request that NVDA should support such live updates as described in the page linked to above.

**Comment by ehollig** [comment]
The URL provided in the original post no longer exists. Also, it sounds like from @jcsteh's comment in https://github.com/nvaccess/nvda/issues/2036#issuecomment-155295199 that NVDA already supports descriptionChange events. If this issue still exists, and someone can provide another working example, the issue can be reopened. Closing
