### ISSUE TITLE
nvda doesn't move on bullets and numbers

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2037]
**Reported by fatma.mehanna on 2012-01-09 20:26**
nvda doesn't pronounce bullets and numbers when using the left and the right arrows.
steps to reproduce:
1 open a word document.
2 type some lines and bullet them.
3 press home to go to the top of the line.
results: nvda pronounces the first letter of the line and ignore the bullets.
expected: nvda should pronounce the bullet.
the same issue happens when i press back space to delete the bullet. nvda deleted it without pronouncing it.
the same also happens when i use the left and the right arrows to move between characters.

**Comment by bhavyashah** [comment]
I am positive that I had filed a very similar ticket (probably on Trac) which duplicates this. Could someone please relocate that and close either this or the other one (I am bad when it comes to locating particular tickets)? @ehollig

**Comment by Adriani90** [comment]
closing in favor of #2649.
