### ISSUE TITLE
Libre office series 4 is broking by reading, and by braille.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2049]
**Reported by lallermacher on 2012-01-17 17:28**
When I want to read something in libre office, it stops, by reading 3 lines. It is the same by navigating with a braille display. By the stopping, you hear an error sound from nvda. If I do not navigate to the another type of cursor, the navigator cursor, it does not read in braille, but when I set it to the navigator cursor, it reads only 3 lines, or even 4, and stops. It is very annoiing.

**Comment by ehollig** [comment]
Closing for the following reasons:

1. This ticket is over 5 years old.
2. We do not have a way to contact the original author as far as I am aware.
3. We have insufficient information to troubleshoot the issue further.
4. Others are using Libre Office with speech and Braille without a problem.
