### ISSUE TITLE
When entering in mozilla firefox 9 to a webpage, some links directs to the dsktop.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2050]
**Reported by lallermacher on 2012-01-17 17:34**
When I open mozilla firefox, and navigate with the browse mode between links, and want to activate a link, then I press enter, sometimes it directs to my desktop. It is sometimes by the elements list also, and then I shall open internet explorer for opening and navigating good on a webpage. It is only in mozilla firefox series 9, but abowe no such navigation detected.

**Comment by ehollig** [comment]
Sounds like there is not enough information provided to replicate.
