### ISSUE TITLE
If I wanted to install windows live essentials on my new windows 7 desktop, nvda was crashed, and it will say a part of the things, I navigate on it.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2051]
**Reported by lallermacher on 2012-01-19 07:50**
When I enter in an application, in skype, or even a mail program, such as mozilla thunderbird, or firefox, or even in skype, my nvda announces me every time ismeretlen, it means unknown. It is after I wanted to install the new windows live essentials, before was it not. I made a system restore, an nvda uninstall, everything, I could do. By skype I can make it with skypetalking, but in my mails can I make with thunderbird, but I shall enter on a word, when it sais ismeretlen, unknown, and it will announce, what is in the mail. Please help, to reproduce my nvda! On my pc is no virus, it was caused by the installer of the windows live essentials 2011, and it was downloaded from the official website. I am using browsing with a blind majde programm, webbie, and it is good, and I am enabled to write you this ticket.

**Comment by leonardder** [comment]
This issue looks abandoned. Closing, as it seems to be related to a specific user system. Furthermore, Windows Live is deprecated.
