### ISSUE TITLE
Treat KurzWeil 1000  as a self-voicing application

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2054]
**Reported by drein on 2012-01-20 09:57**
Hello,
Kurzweill1000 is a software that is self-voicing.
It is really powerful and is used in Italy by many users.
I have modified the openbook module in order to put NVDA in sleep mode, also if I have a problem: I'd like to disable the voice, but keep the braille alive...
Is it possible?
For now, when running KurzWeil 1000, NVDA go to sleep mode, but if you know a manner to allow user to use the braille, please modify the attached file.
the executable name is:
"Kurzweil 1000.exe"

**Blocking #4713**

**Comment by bhavyashah** [comment]
Since the original author of this ticket cannot be contacted and he unfortunately did not respond to @jcsteh's https://github.com/nvaccess/nvda/issues/2054#issuecomment-155295344, the scope of this ticket remains unclear. Time to close? @ehollig

**Comment by jcsteh** [comment]
Closing due to lack of feedback/interest. If there is active interest or someone willing to pursue this, please provide feedback on the outstanding questions here and we can reconsider.
