### ISSUE TITLE
Audio output device names truncated to 32 characters

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2067]
**Reported by HKatic on 2012-01-29 13:10**
In NVDA's synthesizer preferences dialog, the Output Device Combo Box displays incomplete device names. For example, I have 2 sound cards, the one which is Realteck High Definition Audio, and another which is SoundBlaster X-Fi Surround 5.1 Pro. However, they are displayed as follows:
Output device: Speakers (Realtek High Definiti
Output device: Speaker (Sound Blaster X-Fi Sur
This simply means that the entire device name doesn't fit into the Combo Box control, and that the control or dialog itself needs to be resized.

**Comment by bhavyashah** [comment]
@jcsteh As you indicated in https://github.com/nvaccess/nvda/issues/2067#issuecomment-155295439, the reported issue is a limitation of the Windows API function we use. Do we have alternatives to use with a more relaxed character limit? CC @feerrenrut for GUI expertise

**Comment by jcsteh** [comment]
I don't know. There are newer APIs, but the question is whether we can map these back to WinMM device identifiers. Further research is required.

**Comment by Adriani90** [comment]
I can reproduce this in NVDA alpha-20097,6a573cd9.
cc: @JulienCochuyt

**Comment by JulienCochuyt** [comment]
Found a few hints here: https://stackoverflow.com/questions/1449162/get-the-full-name-of-a-wavein-device/43396412

Long story short:
 - First pass a WAVEOUTCAPS2 structure to gain the device GUID then lookup in registry
 - If this fails (no info in registry), use DirectSound to fetch device info

It's doable, but a bit complicated for what it attempts to solve...
