### ISSUE TITLE
MS Outlook 2007: unable to use spell checker

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2070]
**Reported by CBartlett on 2012-01-30 18:40**
When editing an email in Outlook 2007 and attempting to spell-check, the spell check dialogue comes up if there are errors, but I have no access to the word flagged.  I hear grammatical error for every misspelled word.  I can tab to the suggestions box and down-arrow through the list normally, but in no case can I see the original word, or the sentence/line the word is found in.  Other controls work, but I am left having to guess what word is being flagged based on the suggestions list.

**Comment by leonardder** [comment]
This ticket looks abandoned. Outlook 2007 is also very old anyway. We can discuss reopening if this is still reproducible.

This is also related to #3410, although that's for a newer office version, and Word specific.
