### ISSUE TITLE
Error in IBM Lotus Symphony

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2081]
**Reported by drein on 2012-02-03 08:40**
I have two problem with IBM Lotus Symphony. 
The first, I can't read anything in the display braille of my document I'm writing.
The second, i have a sound error when I arrow down.
I attach the log, perhaps this is the same problems?

**Comment by ehollig** [comment]
The original author did not report back with trying with the latest version of NVDA (at the time) or answer any of @jcsteh's questions in https://github.com/nvaccess/nvda/issues/2081#issuecomment-155295530. Also, @jcsteh was not able to reproduce the issue. As there is not a way to contact the original author, and Lotus Symphony development has been discontinued, closing.
