### ISSUE TITLE
NVDA with IE8, browser hang on Blastbay.com and audiogames.net forums

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2085]
**Reported by CBartlett on 2012-02-04 19:19**
It seems that about one time in two, when I enter the edit box to respond to a topic on http://forum.audiogames.net or the blastbay games forum, I get in a situation where I lose speech, but only in that application.  I am able to alt-tab away from IE and speech returns correctly.

I'd attribute this to an IE problem, except that when I explore using object navigation, i hear "invisible object" and the object has no parent, children or siblings.

Procedure: log onto either one of these forums.  (The blastbay forum kills me more frequently.)  Read a topic and hit e to move to the quick reply edit box.  Begin typing.  For me, things go silent within a few keypresses of doing this.  Now check things out using object navigation.

**Comment by leonardder** [comment]
Everyone using IE8 should update to something newer if possible. For XP users there's no alternative to staying on IE8, but given the age of this ticket and the specific cases with an acceptable workaround, I suggest a close.
