### ISSUE TITLE
problem with NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2092]
**Reported by jfauchon on 2012-02-08 16:06**
Hello to allthe development team,

I would like toreport a buginNVDA,whenofalist boxina folder inExplorer7 orWindowsXPorin a tree,NVDAdoes not announcethat there isno evidencein thesecontrols.

Pouveayou correctthis problem.

I have onesuggestion to makeis thatNVDAwill announce the numberofradio buttonsthatarein theradio groupandexplorethe Internet,NVDAcan announcethe labeledit boxwhenpreceded by severalspaces beforethe editing area.

Thank you toall the team forthework you do.

**Comment by dkager** [comment]
This looks quite vague...
