### ISSUE TITLE
Winamp Playlist editor title bar does not read correctly, i.e., Winamp Playlist editor. Instead it reads a series of random numbers.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2093]
**Reported by shazza59 on 2012-02-08 22:21**
I am using Windows7 64 byt with NVDA 2012.1 Beta1. The version of Winamp I am usign is 5.581.

All Winamp's Child windows title bars read correctly except the Playlist editor, which, upon opening it or control tabbing to it reads thusly: 4924967296 . It should say Playlist Editor. 
Winamp Playlist editor window can be gotten to via the file menu, (alt f), arrowing down to winamp playlist editor, pressing enter, then control tabbing to it from the main winamp screen.

**Comment by ehollig** [comment]
CC @josephsl, just wondering what the status on your commit #655b457 was and if it could help with #2094

**Comment by bdorer** [comment]
Winamp is at Version 5.80 or s.th. like that.Could someone test and report?

**Comment by Adriani90** [comment]
yes this occurs also in Winamp 5.8 but only in very rare cases. I am closing this issue since the ol Winamp interface is discontinued, they are working on a new Winamp 6.0 which will be redesigned.
