### ISSUE TITLE
an app module for instant bird

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2105]
**Reported by fatma.mehanna on 2012-02-14 11:53**
hi,
it will be gratefull if an app module has been written to help nvda users to deal with instant bird.
we need shortcuts to read the current message and the previous messages like miranda. i think it is more accessible than miranda. it will be also nicer if you enable the announcement of the incoming message. we can't read it till we arrow to it.

**Comment by Adriani90** [comment]
@fatma.mehanna, @pvagner is this still an issue in last version of instantbird?

**Comment by ABuffEr** [comment]
Hi,
I remember that @nvdaes has developed an add-on [here](https://bitbucket.org/nvdaaddonteam/instantbird), that reads 1-10 messages...
However, Instantbird 1.5 was released in 2013, and now project seems abandoned...

**Comment by Brian1Gaff** [comment]
I don't think they are developing it. Especially now Twitter has removed the 
protocols apps used to figure out what to do, anyway.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by leonardder** [comment]
Last news article dates from almost 3 years ago and indeed, the last version dates from much longer ago. I'm closing this for now, as I don't see any reason to add an app module for abandoned software. Having said that, if someone ever wants to extend the current appModule, feel free to file a pull request.
