### ISSUE TITLE
MetecBD 40 braille display driver.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2106]
**Reported by MHameed on 2012-02-14 12:44**
Attached is a braille display driver for the Metec bd40 as privately emailed to me by:

Mr Shankar 
braille section team.
Anna Centenary Library
Chennai

I understand that this driver was developed by the producers of MeTec and provided to the governmental library, but they are currently not intrested in maintaining it.

It is working fine with nvda 2011.1, and 2011.3, (english)
but they are currently having problems with the tamil braille table, which I am hoping to help them resolve.

I also know that the MeTec displays are being used in Egypt, and those users would be very intrested in this.

Thanks.

**Comment by bhavyashah** [comment]
@jcsteh Did any of the suggestions you provided in https://github.com/nvaccess/nvda/issues/2106#issuecomment-155295707 ever materialize? I believe not, and I thus suggest closing. @ehollig

**Comment by jcsteh** [comment]
No progress was made. We'd of course be happy to support this display, but we'd need someone to at least initially work with us to address code issues or a loan of a display and documentation as outlined earlier. Closing.
