### ISSUE TITLE
a way to read current page's url when inside virtual buffer without going into location bar

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#211]
**Reported by aleksey_s on 2008-10-27 13:53**
subj. for example, in jaws it is attached on ctrl+a. i believe we can generalize this to read location bar in current application. just implement different methods in explorer and firefox to receive this info.

**Comment by leonardder** [comment]
I'm leaning towards a close, since this ticket is abandoned for a long time. Furthermore, after you've read the web address in the address bar by pressing alt+d or control+l, you can usually switch back to where you were using shift+f6.
