### ISSUE TITLE
Object Labeler Functionality

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2111]
**Reported by ateu on 2012-02-17 00:37**
Hello

Sometimes, when using object navigation, we navigate controls which NVDA only anounces the control's name (in my job, for example, i use an application which has many inaccessible buttons, and when I use object navigation, I heard just "button" or simply unknown.)
Also, when it ocurrs, the flat review does not detect them.
For this reazon, it would be so good nNVDA provides a graphic labeler.
It would be associated with the object navigation, as it provides the control tipe.
As well as the symbols, the graphic info would be saved in the user config, in a file specially made for it.
The command key used to activate the graphic labeler would be NVDA+g.

Thanks
**Blocking #4391**

**Comment by hatserdevlats** [comment]
I read that Jaws does have this capability. How does this works in Jaws and why it can not in NVDA?

**Comment by feerrenrut** [comment]
See also an issue for specifically labeling objects in web pages: #5874

**Comment by Qchristensen** [comment]
Is there any progress on this issue?  People still request it.

**Comment by ruifontes** [comment]
Yes, this feature is still required by members of portuguese language 
comunity...

Best regards,

Rui Fontes
NVDA portuguese team


Às 00:31 de 26/09/2018, Quentin Christensen escreveu:

**Comment by rkingett** [comment]
I hope this is still being thought of, because this would be great for accessibility issues! Is there a way to have an open source database of these labels?

**Comment by ruifontes** [comment]
So do I!
It is very important...
Altough I agree with Joseph Lee, we should ask devellopers to label all 
controls, we need some tool to bypass that problem untill all 
devellopers start doing things the right way...

Rui Fontes


Às 13:52 de 15/02/2019, Robert Kingett escreveu:

**Comment by Adriani90** [comment]
somehow addressed in #7194. This feature is also requested from many people in the romanian community.

**Comment by joshknnd1982** [comment]
What is the progress on the NVDA object labeler? Will it be in NVDA 2019.3? or 2019.4?

**Comment by h-rezaei** [comment]
Please consider adding this.
JAWS has had this for years and users are forced to work with JAWS for their jobs just because of  this.

**Comment by rkingett** [comment]
Talkback is a good example of easy labeling. JAWS too. This wouldn't discourage accessibility advocacy, it may push it forward, but I know many JAWS users that use JAWS because this feature exists. If this can also have an open source database of labels, it would make it easier to try NVDA with indie programs.

**Comment by amirsol81** [comment]
Hi. Even some printers and scanners have apps which require image/button-labeling in order to become more accessible. So please kindly consider implementing this functionality.

**Comment by cary-rowen** [comment]
I am really surprised that this feature has not appeared on NVDA so far, and now NVDA users have to force the implementation of this feature on add-ons. Is it possible for NVAccess to reconsider?

**Comment by rkingett** [comment]
I still maintain this would be a boom to NVDA adoption, combined with an open source repository of labels would be the best. Just out of curiosity, which add ons allow this?

**Comment by cary-rowen** [comment]
> I still maintain this would be a boom to NVDA adoption, combined with an open source repository of labels would be the best. Just out of curiosity, which add ons allow this?

Hello
NVDA users in Taiwan have created this add-on, but there is no github repository for the time being.
Is there an open source tag repository available?
Thanks.

**Comment by leonardder** [comment]
I once created an add-on on behalf of @BabbageCom, not sure about the current state though:
https://github.com/BabbageCom/objEnhancer

**Comment by cary-rowen** [comment]
@leonardder I tested him roughly, it's good, can you continue this PR?

**Comment by leonardder** [comment]
I'm not really interested in taking this further, honestly.

**Comment by Qchristensen** [comment]
Did anyone ever update this add-on for current versions of NVDA?  It is something we still get asked about.

**Comment by haruncetinkaya306** [comment]
@gerald-hartig
NVDA users need such a feature. Can't such a feature be implemented for NVDA? Isn't this possible with today's technology?

**Comment by gerald-hartig** [comment]
Closing. Issue and discussion updated in linked issue.
