### ISSUE TITLE
NVDA causes some applications to not close (exit) correctly

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2113]
**Reported by k_kolev1985 on 2012-02-18 20:01**
I've noticed that NVDA causes some applications not to close (exit) correctly and stay resident in the memory. Such applications are "SpeedCommander" (file manager) and "Total Recorder".

Steps to reproduce:
1. Run NVDA (I'm using main snapshot 5012, but this was noticed a long time ago, so I guess it applies to older versions of NVDA as well).
2. Install and run one of the applications mentioned above ("SpeedCommander" and/or "Total Recorder"), while NVDA is running. Both applications have a trial version witch can be downloaded from their websites for test purposes.
3. While the application in question is running, try to close it (exit) via Alt+F4, "Close" from the system menu, or via its "Exit" command in its "File" menu.
4. Normally, the application should close itself completely, leaving no trace of itself in the memory. Actually though, the application's main process stays resident in the memory, and in the case of "Total Recorder" - there is a taskbar button of the application, witch has no visible window attached to it. In both cases, you'll have to kill the application's process to close it completely.
5. Now, after killing the application's main process, exit NVDA, and run the application in question.
6. After that you may run NVDA as normal.
7. Try to exit the problematic application via one of the methods from step #3. Now it closes correctly and does not hang in the memory. At least I can confirm it for "Total Commander" - I removed "SpeedCommander" some time ago and can't test if it will apply to it as well.
I recall that there was something similar happening between NVDA and "MP3Tag", but now it seams not to happen anymore - I guess it's been fixed (though I don't know from witch side - NVDA or MP3Tag).
This has been tested with NVDA main snapshot 5012 and Total Recorder 8.3.4600 VideoPro Edition on a Windows 7 Ultimate 32-bit system localized in vulgarian and all regional and language settings set to bulgarian. But I can recall it happening with older versions of both NVDA and Total Recorder and even on Windows Vista Home Premium witch I was running previously.

**Comment by bhavyashah** [comment]
@k_kolev1985 Could you please test and report whether or not the reported issue still persists with the latest versions of NVDA and problematic software?

**Comment by k-kolev1985** [comment]
I no longer use Total Recorder and Format Factory, but the issue does no longer occur with Speed Commander.

**Comment by ehollig** [comment]
Closing as the problem no longer exists in https://github.com/nvaccess/nvda/issues/2113#issuecomment-320892591.
If the problem still exists with Total Recorder or Format Factory, please create a new issue.
