### ISSUE TITLE
In virtual box when a vm is created it is not reported in the list of vms

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2116]
**Reported by mhussain on 2012-02-20 21:48**
In virtual box when a vm is created it is not reported in the list of vms
after a vm is created, it does not show up in virtual box yet it is there in the list

**Comment by Adriani90** [comment]
@mhussain is this still reproducible?

**Comment by Adriani90** [comment]
@mhussaincov I think you are also the initial author of this issue. Is this problem still occuring for you with NVDA 2019.1.1?

**Comment by Adriani90** [comment]
@lukaszgo1, @k-kolev1985, @novalis7747 do you by chance use Virtual box? Could you please test if this is still an issue in NVDA 2019.2 RC2? If not, I am tempted to close this issue as abandoned because we lost contact to the initial author.

**Comment by lukaszgo1** [comment]
I suspect it still is, however I am using quite old version of VB on my main machine. Will test and report back

**Comment by Adriani90** [comment]
@steverep80, @mhussaincov are you still using Virtual Box with NVDA? Could you test if this issue still occurs with NVDA 2024.2 Stable or 2024.3 Beta?

**Comment by Adriani90** [comment]
We don't have an update form the initial author since many years upon request, I am closing as abandoned. if you are still having this issue, please comment and we can reopen.
