### ISSUE TITLE
NVDA should offer to transfer just settings to logon and other secure screens

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2119]
**Reported by mwhapples on 2012-02-21 12:24**
If I have global plugins in my user settings directory when I activate the "Use currently saved settings on the logon and other secure screens" option NVDA currently warns me about having global plugins in the user settings directory and asks whether I still wish to proceed. The only options for answering this warning is yes or no, a third option such as "Copy settings but not plugins" would be useful so that the settings could still be transferred to secure screens without having to copy the plugins.

**Comment by bhavyashah** [comment]
@jcsteh @feerrenrut Could you please talk about the feasibility or possibility of this proposal? If it can be implemented taking security concerns and implementation considerations into account, please add the feature label.

**Comment by jcsteh** [comment]
I think #6305 is a better solution to this problem. Closing as a duplicate.
