### ISSUE TITLE
Add an option to select wether to interrupt speech while scrolling the braille display

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2124]
**Reported by bramd on 2012-02-23 14:08**
The current behavior is to interrupt speech for every key press. Most screenreaders have an option to don't interrupt speech when one of the braille scrolling commands is used. If this option is enabled, the user can explore information on the braille display while listening to the info provided by the speech synthesizer.

**Comment by dkager** [comment]
I think this is a legitimate feature.

CC @leonardder

**Comment by leonardder** [comment]
I'd like to implement this, but I'd also like to add a feature that allows the speech to read the display contents, i.e. when you are reading text, speech should read the chunk of text that's on the display, *not* the real text that's on the display. This is not going to work for NVDAObjects though, only textInfos.

**Comment by seanbudd** [comment]
Is an option necessary here?
I think perhaps we should just switch to this behaviour.
Is there a reason a user would want scrolling forwards and back to interrupt speech?

**Comment by jcsteh** [comment]
While I do use speech and braille together, I don't really use them simultaneously. I tend to switch between them, though I might switch multiple times within a minute. The impact of this is that when i scroll braille, I am not interested in speech and I want it to be silenced to reduce the distraction. So, if this were an option, I'd personally choose to have scrolling interrupt speech. That said, I could probably learn to live with it if this were changed with no option.

**Comment by leonardder** [comment]
I agree with @jcsteh here. Interrupt on scrolling should really stay the default in my opinion.

**Comment by seanbudd** [comment]
@jcsteh @leonardder 

From this my understanding is:

If you find speech when using braille distracting, an intuitive UX is to cancel speech when you begin scrolling.

Am I correct in thinking that cancelling speech via scrolling the braille display, requires you to either:
* read the first character/word with braille or speech, then scroll forward
* before speech starts, scroll back and forth to get back to the start of the braille

Rather than the above UX, would it be a better to have a specific braille device gesture(s) to:
* toggle speech on/off: prevent distracting speech from starting
* cancel speech: as a no-op for the braille display, instead of scrolling back and forth

**Comment by jcsteh** [comment]
Personally, I'd find either of these less ideal than just cancelling speech
when scrolling. I'm sorta okay with speech reading a little bit while I
read the first chunk of braille; I just don't want it to keep muttering if
it's going to read a lot of text. Scrolling is an intuitive way of
indicating "okay, now I'm interested in braille, whatever you're saying
isn't relevant to me any more".

If it were possible to silence speech when your fingers touch the display,
that might be nice, but most displays (other than maybe Handy Tech?) can't
do that. Needing some additional gesture to silence speech feels clunky and
incurs additional cognitive load.

**Comment by leonardder** [comment]
Also agree with Jamie with this regard.

**Comment by seanbudd** [comment]
Thank you for your answers, it made understanding the UX for this really clear. This will help inform how integrate the option (i.e. not by default, but still as a feature flag so the default can change in future).

>If it were possible to silence speech when your fingers touch the display, that might be nice, but most displays (other than maybe Handy Tech?) can't do that

Also something to keep in mind is to add this as an additional feature for the devices that support it.
The DotPad is meant to support this, and it might become more common in the future.
