### ISSUE TITLE
appModules should have a way to override the logic to retrieve status bar text in api.getStatusBar

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2125]
**Reported by ragb on 2012-02-23 14:26**
Currently api.getStatusbar() tries to retrieve the statusbar object from the botom left corner of the foreground window. In some windows such as WiNdows Live messenger the statusbar is not dectected. In the case of windows messenger the statusbar has no statusbar role either but can be customized in the appModule as it is the history Window. 

The idea is to provide some method on the appModule class to get the statusbar object. If the module does not implement that method, or returns, None (or some other way to report that it can't find the status bar) the current logic is used.

Is this suitable for inclusion? If yes, shall I write a patch?

**Comment by leonardder** [comment]
On #6769, @FeerRenrut posted some relevant tickets for this:

> *   Unable to find status bar in Visual Studio Ref bug [#5618](https://github.com/nvaccess/nvda/issues/5618)
> *   Unable to find status bar in Office aplications [#649](https://github.com/nvaccess/nvda/issues/649)
> *   Status bar handling does not work with Java Access Bridge applications [#5674](https://github.com/nvaccess/nvda/issues/5674)

**Comment by leonardder** [comment]
Closing as duplicate of #4640. Even though this issue is older, #4640 contains more discussion.
