### ISSUE TITLE
sometimes wrong numbering for footnotes

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2127]
**Reported by fatma.mehanna on 2012-02-24 18:55**
hi devs,
thanks for all the improvements you made with msWord.
i'd like to refer to something about reading the footnotes numbers.
in microsoft word, there are 3 patterns of numbering the footnotes
one of them is a continious numbering
 where all the footnotes being numbered in a continious way from the start of the text to its end

i.e, if the last footnote in page 1 has number 5 then the first foot note in page 2 is number 6
and so on till the end of the file

 the second pattern is starting a new numbering for each page

this makes the first footnote in page 6 for example gets number 1

and nvda at the moment always reads the foot notes numbers according to the continious numbering

this means when i choose to number the footnotes as for each page separately, nvda reads the footnotes numbers according to their existance in the file
not according to its number in the page
this is our arabic mailing list members feedback.

**Comment by fatmamehanna** [comment]
Hi ,
still no way to solve this problem?
this ticket is opened for 4 years and there is no responce to it.
thanks.

**Comment by jcsteh** [comment]
There's nothing new because we never discovered anything new. It was investigated and we unfortunately weren't able to find a way to solve it.

CC @michaelDCurran

**Comment by ehollig** [comment]
Closing because the issue was investigated and unfortunately, there was no way to solve it as stated in https://github.com/nvaccess/nvda/issues/2127#issuecomment-186691438
Unless @michaelDCurran has additional information to provide, closing as cantfix
