### ISSUE TITLE
Improviments for formatting information in applications using java access bridge

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2129]
**Reported by ateu on 2012-02-25 19:36**
This allows obtain more formatting information in openoffice/libreoffice.

When nvda f is pressed, we hear simply "proportional" instead of the font name, the cize and the style.
It would be nice NVDA announces color, alignment and spelling errors.

Thanks

**Comment by bhavyashah** [comment]
@jcsteh From your comments, it seems that only font colour, and possibly alignment as well, can be supported by NVDA in JAB. However, I believe Java Access Bridge has been superceded or something of the sort. Could someone please shed light on this so that JAB tickets can be accordingly triaged?

**Comment by jcsteh** [comment]
Closing, as JAB in Libre/OpenOffice has been replaced by IA2, which provides much more info.

Just as a general triage note, JAB has been replaced by IA2 in Libre/OpenOffice, but it has not been replaced for Java Swing applications.
