### ISSUE TITLE
processFocusWinEvent: force focus-event after a reorder-event was made

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2132]
**Reported by adrianw on 2012-02-27 13:24**
Hello.

There is a problem with "processFocusWinEvent()" in IAccessibleHandler.py.

The signature looks like this:
"def processFocusWinEvent(window,objectID,childID,force=False)"

With "force=False" processFocusWinEvent() ignores a second EVENT_OBJECT_FOCUS if the current focused
element has the same childID as the new element even when a EVENT_OBJECT_REORDER was triggered before. So the new focused element never gets read-out by nvda.

In my application, after some user-input, my object-model changes significantly and all the visible elements getting reordered and another element gets the focus. Sometimes different elements got the same childID and a EVENT_OBJECT_FOCUS gets ignored by NVDA (NVDA thinks it's the same element, but that's not the case).

When i edit the nvda-source-code and set "force=True" in processFocusWinEvent everything works fine. The new focused element gets read-out by nvda.

Is it possible to queue the second focus-event when a previous EVENT_OBJECT_REORDER has been made?
IMHO, after a REORDER the first focused element isn't valid any more and nvda should 
accept a second EVENT_OBJECT_FOCUS.

To solve this i'd like to suggest:
- set force=True in processFocusWinEvent() (yes, i know it's not very clever) OR
- invalidate lastQueuedFocusObject after an EVENT_OBJECT_REORDER was made

Thanks for a great tool!!

Adrian

**Comment by bhavyashah** [comment]
@jcsteh Since the original author of this ticket, although now out-of-reach, did respond to your questions in https://github.com/nvaccess/nvda/issues/2132#issuecomment-155295901, could you please provide a follow-up comment?

**Comment by jcsteh** [comment]
I haven't dug into this too deeply, but it looks like the no duplicate rule for child id > 0 is specific to simple children; i.e. IAccessibleChildID > 0, not event_childID > 0. In this case, these are full IAccessibles, but with a positive child id. We might be able to test event_childID > 0 instead... or perhaps we could somehow use the reorder event as was originally suggested.

Regardless, we don't have any way to contact the reporter and thus nothing to work with. Closing, but we can reopen if this becomes relevant again.
