### ISSUE TITLE
Lag/crash when trying read large pages containing changesets

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2133]
**Reported by ateu on 2012-02-27 15:09**
Hello,

Buth using chrome and firefox, when I try read the changesets in timeline, causes a lag or simply nvda crashes.
To reproduce:
1. Open a browser, Firefox and Chrome. (I haven't tested with internet explorer, but I do not think the problem is with the browser);
2. Go to timeline and open the link changeset main 5040;
Expected result:  the page is opened and nvda automaticaly start say all.
Actual result: nvda stop responding.

**Comment by leonardder** [comment]
We aren't using Trac any more, so this can be closed.
