### ISSUE TITLE
Unable to read books in Blio with braille

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2139]
**Reported by jteh on 2012-03-02 07:47**
Blio is an ebook reader written in .net. There are two issues which mean braille can't be used to read books:
1. It uses a role of document for its book content area. However, braille doesn't treat this as a text object. We should add document to the list of roles accepted by braille.NVDAObjectHasUsefulText.
2. Once the first issue is fixed, braille does not track the cursor. In turn, this means you can't move to the next line with braille. This happens because we disabled the UIA !TextSelectionChanged event (#1205, 9025c04dc0aaef7fc5ae4575844260503b5acdc5). Unfortunately, #1205 apparently occurred in Windows 7 as well, so re-enabling the event would re-introduce this.

Mick, any thoughts on (2)? The best I could come up with is to selectively listen for these events only for certain objects, but we've run into problems with object event registration in the past.

As a sidenote, (1) is also valid for Digital Editions, but unfortunately, it doesn't fire !TextSelectionChange events even when we listen for them.

**Comment by leonardder** [comment]
@JCSTeh: Should we close this as won't fix in favour of kindle/QRead, which are both accessible solutions now?

**Comment by Adriani90** [comment]
@jcsteh, @leonardder, any further thoughts on this? Is the support for braille in this application still an option? or should we close it?

**Comment by Adriani90** [comment]
It seems the software is either discontinued or it changed its name. I cannot find anything about it in the web. Iam going to close this as abandoned due to missing updates for a very long time and given also the questions raised above.
If you still have a link to a website where we can download the software and test it, please comment and we can reopen.

**Comment by Adriani90** [comment]
Oh sorry it seems I was wrong, reopening :)).

**Comment by SaschaCowley** [comment]
@jcsteh is this still an issue that we should look in to? Otherwise it should probably be closed as abandoned.

**Comment by jcsteh** [comment]
I have no idea. I'm not sure whether this software still exists or whether it is still used. No one has asked for it, so I guess we'll close it as abandoned and see what happens.
