### ISSUE TITLE
Sound error and log error when deleting an iten on windows explorer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2144]
**Reported by ateu on 2012-03-04 00:09**
When deleting an iten when shift+del, the iten, is deleted, but nvda plays its sound error and the error is logged.

Follows attached the log

**Comment by dkager** [comment]
Duplicate of #1793, but with log info this time.

**Comment by jcsteh** [comment]
I closed #1793 as a duplicate of this one, as this one has more info.

P4 because this doesn't negatively impact functionality and is only intermittently reproduceable.

**Comment by Adriani90** [comment]
Can someone reproduce this? I didn't see this issue on Windows 7 or higher.

**Comment by Adriani90** [comment]
@ateu any progress on this? registering dlls might work in solving it.

**Comment by Adriani90** [comment]
@jcsteh is this still reproducible with NVDA 2018.4 Beta 1? The initial author did not respond. I didn't find anyone who was able to reproduce it.

**Comment by jcsteh** [comment]
I don't recall whether I was able to reproduce this or whether I just deduced what was going on from the log. I suspect the latter. In any case, I can't reproduce it now.

**Comment by ehollig** [comment]
As we are unable to reproduce this, I am going to close it. Closing
