### ISSUE TITLE
Silent context menus under Windows 7 x64 (Explorer)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2149]
**Reported by rriem on 2012-03-06 10:51**
This bug reports to explorer unter Win 7 x64 only. The right button menus on desktop and in explorer apper, but doesnt speak. The main menues in explorer (File... options) doesnt also speak with nvda. The left hand part of explorer window (tree) doesnot speak. nvda says instead: strucured objects.
Zoomtext 9.1 works in exporer context menu an main menu bar properly. I think, the problem results of x64 Version.
I started protocol in dubug mode. File added to this report.
After crossing the icon "Wiso Sparbuch" on desktop, I right click on desktop and passed through the context menu. nvda keeps silent.

rriem

**Comment by dkager** [comment]
Hard to say what's going on, but could be another case of the problem described in #6177.

**Comment by leonardder** [comment]
@rriem: Are you the rriem who opened this issue? If so, could you provide additional details about whether this issue still occurs for you?

**Comment by leonardder** [comment]
Closing due to lack of recent information.
