### ISSUE TITLE
Spoken text when activating elements with NVDA+Enter is always in English

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2155]
**Reported by zahari_bgr on 2012-03-08 00:21**
The text that is spoken when activating an element with NVDA+Enter is always in English.
For example, when activating a checkbox or radio button, NVDA says "Check"; "Press" - for buttons etc.

**Comment by bhavyashah** [comment]
@jcsteh Based on 'the best we can do is support it where it's possible if we aren't already and fall back to English where it's not possible' from your https://github.com/nvaccess/nvda/issues/2155#issuecomment-155296091, I take it that this is a valid issue which NVDA can resolve to a certain extent. If so, what priority would you recommend be assigned to this ticket?

**Comment by Adriani90** [comment]
@zahari_bgr, @ateu, is this issue still reproducible for you? In german I cannot reproduce this. It might be a translation issue in your language.

**Comment by Adriani90** [comment]
I am closing this as works for me. I cannot reproduce with romanian language either. I assume it is a translation issue. If you still have this problem, please comment on it and we can reopen the discussion. You might also try to contact the translator for your particular language and report this to him or her as well.
