### ISSUE TITLE
nvda with the new VBT scripts

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2159]
**Reported by fatma.mehanna on 2012-03-12 13:23**
hi all,
i want to refer to something that should be taken into consideration in the incoming versions.

many editing scripts for web sites have been developed and many companies
started to rely on them. VBuliton company for example, updated its
editing scripts to change its appearence totally and to become
unsupported by screenreaders
the problem summes up in most of the forums update their script VB to
the latest version to avoid the security issues and to enjoy the new
features. this will effict the way inwhich the blind browse the forum
with, so this issue should be looked at.
 among these problems i faced with these new scripts, the multi line edit fields. try to create a poast for instance. you won't be able to use the editing format features.
here is an example of one of the forums.
http://vbt.alshmasi.net/
log in details:
user name admin
password: ADMIN1234567890
note, passwords are case sensitive.
thanks.

**Comment by ehollig** [comment]
Closing do to the website mentioned in https://github.com/nvaccess/nvda/issues/2159#issue-116029835 seems to not exist, and from the information provided, it seems to be specific to this one application/website.
