### ISSUE TITLE
Braille scroll right sometimes stops working at end of line

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2164]
**Reported by ianr on 2012-03-14 03:27**
I have noticed that using the scroll right key on my braille display sometimes stops working when scrolling right would move me to the next line of text.
I am experiencing this in notepad++ but have experienced similar issues in other editors in the past.
I am using a Brailliant 80 with the BAUM protocol.
This only seems to happen when the braille currently being displayed is at the end of the line of text.
It does not consistently happen, it will happen to me and I can use the keyboard to move up a line then use scroll right again and it may work for a few lines then get caught up on a line that is different than the one it was stuck on before.
I am attaching a log file with log level set to input/output.
I have added a //look here comment that shows an example of where the scroll right key suddenly stops working.
Above it you can see the braille display updating.  Below it you can see repeated scroll right presses that don't change the braille display.

Fixing this would make my reading in braille much smoother as I wouldn't need to revert to using the keyboard to get it unstuck.

Thanks for all your hard work on this great screen reader.

**Comment by dkager** [comment]
This can probably be closed. It looks like the same issue as #5678, which was recently integrated into master.

**Comment by jcsteh** [comment]
Closing as a duplicate of #5678.
