### ISSUE TITLE
When audio output device is changed beeps are still beeing played in the previous device

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2167]
**Reported by ragb on 2012-03-15 00:48**
This was reported on the portuguese list. According to an user when the audio output device is changed on the synthercizer settings dialog, beeps and other sounds play on the default sound card. Is that the expected behaviour? At least beeps for progress bars and mouse tracking make sence to playalong with the synth's audio.

I can't reproduce it now because I don't have access to an external soundcard at the moment, but I recall seeing this behaviour at some point...

**Comment by Adriani90** [comment]
This is still an issue in NVDA 2019.2 RC2 and I experience this quite often. Actually very annoying when you are doing some DJ stuff or recording.
cc: @jcsteh, @leonardder

**Comment by XLTechie** [comment]
Very much agreed! I do a lot of audio work, and this is a pain to deal with.
