### ISSUE TITLE
links in interactive elements

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2169]
**Reported by jkiss on 2012-03-15 09:48**
If focus is set to an element made interactive with some key-based event handler, and that element has a nested link as its first item, activating that interactive element will fire the nested link, even with focus set to the link's parent. This does not happen if the nested link is preceded by any other content, including simple inline text.

For example, see http://www.accessibleculture.org/misc-tests/link-inside-onclick.html

James, you've previously mentioned that this happens because when the interactive element gains focus, NVDA moves the browse mode cursor to the start of the interactive element. Since the start of the element is the link, the browse mode cursor moves to the link. In browse mode, the space and enter keys always operate on the object under the browse mode cursor, not the focused object. You noted that this needs to be done because it's sometimes necessary to activate elements which aren't focusable. As such, pressing enter on the interactive parent activates the link.

This has problematic ramifications, particularly for the HTML5 details/summary elements, where the content model for the summary element is, for better or worse, phrasing content, which includes links. Whether or not details/summary is used, it is not unreasonable to expect links to be included in the content of a disclosure type element or other elements that might have nested links as their first bits of content, but where following the nested link upon pressing the space or enter keys on the focussed parent is not expected.

**Comment by bhavyashah** [comment]
@feerrenrut @jcsteh Assuming that the reported issue still stands, please assign this a priority deemed appropriate by you.

**Comment by Adriani90** [comment]
@jkiss are you still seeing this issue? The link in the issue description is not valid anymore.

**Comment by Adriani90** [comment]
We do not have an answer from the initial author since more than 5 years. I am closing this for now. But feel free to comment on it and we can reopen the discussion. Thanks!
