### ISSUE TITLE
accessibility with teamspeak client

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2171]
**Reported by hadi_gsf on 2012-03-17 00:04**
from what i know teamspeak has one part of toolbar which has the main menus like connect/bookmarks/self/tools and such, a box for sending chat, a list which shows the channels and the users in them, which are all accessible with NVDA.

the current thing which is not accessible is the output window of teamspeak which is the chat window, and the window which gives out the notifications and such.
this is a feature request for NVDA that if we can have the support to be able to read the output window of teamspeak client.

there are some problems with other windows of teamspeak like (connect to server, permissions) and such, but those require more research.
thanks

**Comment by Adriani90** [comment]
@hadi_gsf are you still using Teamspeak with NVDA? How is it working now in NVDA 2020.1 RC1?

**Comment by Adriani90** [comment]
It seems we lost contact to the initial author and there are no updates on this since many years. Closing as abandoned.
