### ISSUE TITLE
Adobe Reader X: when text is highlighted, it should be possible for info to be reported or queried

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2176]
**Reported by kevinchao89 on 2012-03-18 19:23**
If a phrase, sentence, word, and/or character is highlighted, NVDA
should be able to:
1) setting, which will automatically announce via TTS or different
sounds the presence or change in highlight and no-highlight
2) when cursor is positioned on highlighted text, NVDA+F should report
that text is highlighted.

**Comment by bhavyashah** [comment]
The original author of this ticket did not respond to @jcsteh's https://github.com/nvaccess/nvda/issues/2176#issuecomment-155296240 and we have no available means of contacting him. Time to close? @ehollig

**Comment by ehollig** [comment]
If this is still the case with the latest version of Adobe Reader, please create a new ticket or provide an example document demonstrating the issue. Closing
