### ISSUE TITLE
internet explorer9 progress bars

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2178]
**Reported by crashmaster on 2012-03-18 22:22**
While loading pages in ie9 nvda does not detect or speak progress bars

**Comment by bhavyashah** [comment]
Since IE 9 is fading into obscurity, the original author of this ticket did not respond to https://github.com/nvaccess/nvda/issues/2178#issuecomment-155296250, and we have no means of contacting him/her, I suggest closing. @ehollig

**Comment by ehollig** [comment]
Actually, Microsoft removed the progress bar when they rebuild IE9. If this is referring to IE 8 and XP, it is very unlikely that this issue will be fixed. Closing as wontfix
