### ISSUE TITLE
Better support for Adobe Flash installers

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2179]
**Reported by briang1 on 2012-03-19 09:52**
Tis one keeps popping up on other lists, so thoughtI'd raise this ticket but suspect it needs an external change to the installer.

At present, when prompted to install the new versions of flash, one gets an interface which says. Button (tab) I button (tab) Qbutton etc
I have found by trial and error that the sequence should be Button hit space, I button hit space I button again hit space, but it would be nice if the legends were read properly. 
If it does need an external fix maybe someone could have a word in adobes ear?

**Comment by bhavyashah** [comment]
https://github.com/nvaccess/nvda/issues/2179#issuecomment-155296261 seems to indicate that this issue was fixed byAdobe. Regardless, with the demise of Flash, it is highly unlikely that this ticket will receive any attention due to its minimal value.

**Comment by ehollig** [comment]
This probably requires fixes from Adobe. Adobe has announced that Flash is deprecated, thus will no longer be developed actively. Closing
