### ISSUE TITLE
Improve Support For ooVoo

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2187]
**Reported by parham on 2012-03-20 11:34**
The list of contacts in ooVoo can not be read with NVDA. Navigating the treeview containing contacts with the navigator is possible, but the contact names are not read out.

**Comment by ehollig** [comment]
Closing because of reasons in https://github.com/nvaccess/nvda/issues/2187#issuecomment-155296311. If there are specific things that are not working correctly after contacting the developers, please create a new issue with exact steps to reproduce the issue.
