### ISSUE TITLE
nvda some times crashes when looking at yahoo groups messages on cites

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2188]
**Reported by jaime on 2012-03-20 14:00**
when you use nvda to look at yahoogroups web pages nvda crashes out when you look at group messages when you use arrow keys

**Comment by ehollig** [comment]
Yahoo Groups has changed a lot since this was created. I am not able to replicate this using IE 11 on Windows 10. The original poster states using IE 8 on Windows 7. Can anyone on Windows 7 confirm if this is a problem?

**Comment by jcsteh** [comment]
Several years old, insufficient info and no additional reports of this. Closing. Please provide thorough details if the problem persists.
