### ISSUE TITLE
A new, extensible  speech dictionary type for nvda

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#219]
**Reported by aleksey_s on 2008-11-02 14:00**
sometimes one dictionary must be applied to more than one voices or even synthesizers. it is possible when user wants to handle voices of one manufacturer or one language.
So nvda must have functionality to make such dictionaries.
i offer to implement a new type of speech dicts: smart dictionary. this one besides list of entries will have regular expression pattern, which must match with current voice and synthesizer for this dictionary to be active. for users, who are unfamiiliar with regular expressions, nvda will offer dialog with all voices of all available synthesizers, where user can check items and regular expression will be constructed.
i have allready implemented smart dictionaries, for now i am working on gui for manipulate its. 

here is a log of my local bzr branch:
 2263 Алексей Садовой    2008-10-31
      *core.py: fixed some inconsistend logging.

 2264 Алексей Садовой    2008-11-01
       \* speech dicts: implemented a new type of dictionary, smart dictionary. this one can be applied to all synthesizers and voices, if some regexpr matches synthesizer-voice string. we can have many such dictionaries at a time loaded and processed.
       \* some fixes to existing speech dictionaries implementation

 2265 Алексей Садовой    2008-11-02
      speechDictHandler.py: 
       \* now dictionary files can have native characters in names. 
       \* Smart dictionaries now have name. file name will be constructed on this name.

```
  keyboardHandler.py:
   * fixed one typo
```

**Blocking #212**

**Comment by leonardder** [comment]
CC @BDorer

Anyone knows whether aleksey is available on github? I'd be happy to mention him if I know his github ident.

@JCSTeh: May be you could reprovide the attachments?

**Comment by jcsteh** [comment]
No need; the code is available in the `smartDictionaries` branch in the official repo.

1. I've always been very dubious about this. It seems overly complex to me and I'm not clear on real world use cases.
2. We don't "support" manual editing of files these days, so a regular expression isn't a good fit.
3. Even if users used multiple synthesisers for a single language, would they go through the effort of configuring something like this?
4. I think profile specific dictionaries are probably more versatile.

**Comment by Adriani90** [comment]
I agree, we should continue with profile based dictionaries. Synth based dictionaries are hard to handle because it often depends on the voice you are using. This is fair too much work to maintain such things, especially for synths which are updated on a regular basis like Cereprog or eSpeak.

**Comment by jcsteh** [comment]
Closing as per https://github.com/nvaccess/nvda/issues/219#issuecomment-316264614, and also because no one is interested in actively working on this now.
