### ISSUE TITLE
The CapPitchChange setting on the Voice Settings Dialog should only be presented if the synth supports the pitch setting

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2195]
**Reported by ragb on 2012-03-23 17:54**
The summary says it all... In my opinion there is no need to present capPitchChange on the voice settings Dialog when the sytnh does not supports pitch changing. This setting makes no sence in this situation and may confuse the users.

I found this when developing a new synth driver that does not support pitch.

**Comment by bhavyashah** [comment]
@jcsteh Although the original author of this ticket cannot be contacted anymore, since you were interacting earlier, could you still please respond to https://github.com/nvaccess/nvda/issues/2195#issuecomment-155296487?

**Comment by jcsteh** [comment]
There's not really anything to respond to. Some potential problems were noted, which I agree are certainly valid, but it's just a matter of refactoring things to get around that.

**Comment by josephsl** [comment]
Hi,

Seven years later...

CC @ragb, any thoughts?

Thanks.

**Comment by ragb** [comment]
> Hi,
> 
> Seven years later...
> 
> CC @ragb, any thoughts?
> 
> Thanks.


Twelve years after I investigated this.. No, no thoughts :). I didn’t even recall what was the synth with no pitch control.

**Comment by josephsl** [comment]
Hi Rui,

Thanks for the update (nice to hear from you after all these years) - closing the issue (for now) then.
