### ISSUE TITLE
user configuration directory accessible from NVDA's menu

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2214]
**Reported by dallasobrien on 2012-04-04 21:45**
it would be handy to have the user configuration directory accessible from the nvda menu, as this would solve several problems. one is that sometimes, finding the icon in  the start group can be a little hard, especially in windows 8.
how ever, a more important option this would give users, is the ability to open up the user configuration directory while using a temp version of nvda with the new repackaged nvda, so as they may apply app modules and global pluggons. this would then let them create a portable version, and copy the hole set of modifications over to the portable install. i would asume this would work for the installing of nvda as well.
it would perhaps be an option under the tools submenu.

**Comment by ehollig** [comment]
What do you think of this idea? It would be nice to have an option to access the user config directory in the Tools menu for reasons stated above. CC  @jcsteh

**Comment by JulienCochuyt** [comment]
This feature is partially covered by the  "Open developer scratchpad directory" button in the Advanced Settings as of #9238.
