### ISSUE TITLE
user not being notified of installed/completed update

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2222]
**Reported by bmisch1000 on 2012-04-05 17:24**
when i updated nvda it completed but i wasn't notified of this so had to check the about dialog box. Would be nice if a dialog came up letting the user know that the update was complete instead of just reloading the updated copy with no dialog. The installer already does this but the update system doesn't do this yet.

**Comment by ehollig** [comment]
I do not believe this is an issue anymore. I personally think the dialog saying "Updating NVDA" is enough to know what is going on. When the update completes, the start/exit tones are heard indicating a restart.
