### ISSUE TITLE
NVDA speaks 2 colons instead of only one in Foobar2000's baloon tooltips

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2229]
**Reported by k_kolev1985 on 2012-04-07 09:34**
When I'm listening audio files in Foobar2000 (latest stable version), there are help balloons popping up from the notification area of Windows. Those balloons contain information about what's currently playing. They start with a string such as "Now Playing:", "Paused:", "Unpaused:", etc (containing 1 colon at the end of them and then a specified text string (by default - song Artist and Title information)). When such help balloons appear, and NVDA's punctuation is on "Most" or "All", NVDA reads 2 colons at the end of the example strings, instead of only 1. For example: "Now Playing::", instead of "Now Playing:". I've managed to look at those balloons and saw that they visually contain only 1 colon and not 2, as NVDA reports. Why is this happening? Note, that this does not happen with help balloons from other applications, even when Foobar2000 is on focus. Is this a bug in Foobar2000 itself?

Steps to reproduce it:
1. Set NVDA's punctuation level to "Most" or "All".
2. Open Foobar2000.
3. Go to menu File -> Preferences and press Enter to open it.
4. Go to Display -> Default User Interface and check the following 2 items: "Always show notification area icon" and "Show balloon tooltip on song change" (they are not checked by default).
5. Press OK button to close the dialog and save the changes.
6. Start playing an audio file in Foobar2000 (playback controls are found in the "Playback" menu). On file start, pause, resume and on file change, a help balloon will appear. Then NVDA will read something like "Now Playing::", instead of "Now Playing:".

NOTE: I think the NVDA version and the synthesizer used don't matter in this case.

**Comment by Adriani90** [comment]
@k_kolev1985 is this still reproducible?

**Comment by k-kolev1985** [comment]
No, it seams not to occur anymore.

Note however, that a lot of things have changed since then. For one, I no longer use this feature of Foobar2000 and have turned it on only now to test it. The versions of both Foobar2000 and NVDA are also newer. Let's not mention the fact that now I'm using Windows 10 and the balloons there are replaced with toast notifications.

In conclusion, I don't know what caused the problem not to occur anymore, but it is gone now. So, the bug report can be closed.

**Comment by ehollig** [comment]
Thank you @k-kolev1985 for reporting back about this issue. Closing
