### ISSUE TITLE
Add ability for users to vote on tickets.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2232]
**Reported by MHameed on 2012-04-08 11:14**

To increase user participation and ownership, we should consider adding a voting system.
Once we have voting, it is easier to place bounties because people can see the level of interest.

Not sure if this is compatible with the version of trac that is currently being used:
http://trac-hacks.org/wiki/VotePlugin

Thanks.

**Comment by derekriemer** [comment]
Hi:
We now use github, so should this be closed?

**Comment by jcsteh** [comment]
Irrelevant now that we're on GitHub.
