### ISSUE TITLE
Support for visual studio breakpoints, etc.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2233]
**Reported by camlorn on 2012-04-08 19:51**
In jaws, at least, visual studio breakpoints, errors, current line of code in the debugger, and many other things are indicated by the screen reader.  Visual studio stores these, apparently, as an icon in the left margin, next to the line in question.  I can not be more specific than that, as I am blind myself and am going off the visual studio documentation.  Unfortunately, jaws hides how it does this, i.e. the source for that particular script seems to not be included if it is even coded as a script.

Support for these would be nice, as the accessibility interfaces and apis supported by nvda is more complete than those supported by jaws; in addition, nvda is great for testing as well.

```
More generically, some way to know that a graphic is in the margin when viewing text in a text editor of any sort would be useful, especially if custom labels could be assigned.
```

**Comment by dineshkaushal** [comment]
Find a sample vs2015 project with 
[WindowsFormsApplication1.zip](https://github.com/nvaccess/nvda/files/121631/WindowsFormsApplication1.zip)
breakpoints

**Comment by dineshkaushal** [comment]
as camlorn suggested, in update 2 for vs2015 line numbers are no longer being read all the time. if users turns off the line numbers, breakpoint reading stopps working. Breakpoint reading is also no longer working with jaws as well. But in case of jaws, breakpoint does not work whether the line number is on or off. I tried with NVDA branch in_t2233_new and jaws 17 trial.

**Comment by leonardder** [comment]
In visual studio 2019, break points are still not read by default. I recall @mohammad-suliman's add-on implements this, though.

**Comment by christopherpross** [comment]
Hey,
i had looked into the VS IDE and I thing the implementation of announce of breakpoints and lightboulds would be easiely to implement.
The question is, would it better to put that in a add-on or directly in nvda. the serial forges of the VisualStudio add-ons are not under active development i think.
What is your opinion?
How you do you prefer to announce the extra informations?

**Comment by cary-rowen** [comment]
I very much hope that this information can be reported without relying on additional components.

**Comment by Adriani90** [comment]
How is this now with NVDA 2024.3 in Visual Studio 2022? Does anyone have a current status update?

**Comment by cary-rowen** [comment]
The situation in Visual Studio 2022 has changed a lot. Audio Cues can prompt breakpoints in the editor, and NVDA will also report the currently executed code when running step by step.
Therefore, I think this can be closed. If there are other issues, I recommend reopening an Issue and submitting it using the latest template.

**Comment by Adriani90** [comment]
Thanks for the update, closing as works for me.
