### ISSUE TITLE
in microsoft access2007 the selected fields are not appointed

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2244]
**Reported by paul otter on 2012-04-15 14:30**
hello, when i open microsoft acces2007, the fields are good accessible, but the only problem is you can not hear wich field it is for example, address, phone number, etc. when i want to hear wich field it is i've selected, i have to press nummpad 7, then i hear the name of the field and then i know what kind of information i have to type there.
is it possible to do this automaticaly so when i tab to a field nvda tells me what the name is of that field?
i hope it is very simple to solve this problem.
thanks for your help!!

**Comment by ehollig** [comment]
Consolidating discussion to #2281
