### ISSUE TITLE
Vertical/horizontal hold for mouse pointer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2246]
**Reported by CFlat on 2012-04-15 20:35**
It would be useful if when moving the mouse pointer, one could hold down the shift key to lock the mouse pointer on a horizontal or vertical line. For example while moving left/right, up/down a row/column of buttons/icons that can only be accessed via mouse tooltip announcements.
I sometimes have ZoomText running in the background just for this purpose as it has that capability. ZT isn't much use to me these days, and it is CPU intensive, so it would be nice if the command were part of NVDA.
I believe that being able to manipulate the mouse with sounds and tooltip announcements has great potential, but not as long as it wanders diagonally all over the place.

**Comment by leonardder** [comment]
This functionality sounds like it should be a magnifier function. I don't belief NVDA should have such functionality in core. There's no problem putting this in an add-on, though.

Closing as won't fix, but if you have comments or solid use cases for this feature, feel free to comment.

**Comment by derekriemer** [comment]
Actually, I feel this could be useful when trying to for example, read a row of inaccessible buttons, but the use case is small. A partially sighted person could read each word on the line as it goes by, but I don't think that's screen reader functionality.
