### ISSUE TITLE
Add an option to keep the update in installation version of updater

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2255]
**Reported by briang1 on 2012-04-20 13:53**
It would be useful if one could elect to keep a downloaded  update so that any reinstalls does not involve downloading the latest version again.
 I used to do this with snapshots via the nvda downloader before, but the only way to achieve this without going to the download pages is to update using a portable version  as far as I can see.

**Comment by bhavyashah** [comment]
@jcsteh in https://github.com/nvaccess/nvda/issues/2255#issuecomment-155297174, you expressed your temptation to close this ticket as a wontfix. What is your opinion on this matter at present? As done by Jamie in the same comment, thoughts, @michaelDCurran?

**Comment by jcsteh** [comment]
I'm making an executive decision. Won't fix. :)
