### ISSUE TITLE
I have to restart NVDA to make him working as usual

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2261]
**Reported by PZajda on 2012-04-23 18:01**
I have set  NVDA to run automaticaly before and after I open a session.
When everything is started, I have to restart NVDA because I have so much freezes.
Attached there are two logs, one when NVDA runs afted I was logged in, and the second is after I restarted NVDA.
The first one have a lots of errors, so I didn't know how to cut it. Sorry.

**Comment by ehollig** [comment]
@pzajda are these issues still occurring for you? Also, @michaelDCurran do the logs provided offer anything useful, or do you believe this is of fault of some Bluetooth software as indicated in https://github.com/nvaccess/nvda/issues/2261#issuecomment-155297215

**Comment by Adriani90** [comment]
Are there any further discussions regarding to this issue? Is it still occuring?

**Comment by Adriani90** [comment]
I cannot see the log files, but it might be related to #7982 and referenced issues.
Please note the comments provided by @dineshkaushal.

**Comment by ehollig** [comment]
@Adriani90, I have attached the files it the comments above.
Also, it would be good to know if these issues are still occurring for @pzajda. Otherwise, I am leaning toward an invalid.

**Comment by Adriani90** [comment]
@ehollig, after looking at the log files, this could be solved by registering the com dlls which can be done by using the tool provided in NVDA 2018.2. Who is the author of this issue? Is it still reproducible?

**Comment by ehollig** [comment]
Hello @Adriani90. Thank you for looking at the log files. I believe the original author is @pzajda based on the Trac username. However, based on the age of this issue and a possible solution is available, I will close this issue.
