### ISSUE TITLE
inconsistancy when reading excel spreadsheets

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2279]
**Reported by ashleycox on 2012-04-27 10:10**
When reading excel spreadsheets with NVDA, I have noticed some inconsistancy when NVDA announces the coordinates. For example, if the user is located at b2, and tries to use the right arrow key to move to b3, sometimes NVDA will repeat "b2", and sometimes will announce the column that is actually selected, b3. Using excel 2007

**Comment by ehollig** [comment]
As stated in https://github.com/nvaccess/nvda/issues/2279#issuecomment-155297348, the issue could not be reproduced. If someone using Excel 2007 can still produce this issue, it can be reopened.
