### ISSUE TITLE
Word: NVDA+END does not report info in status bar, e.g. page x of y, total word count, etc.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2283]
**Reported by kevinchao89 on 2012-04-29 15:23**
Within a Word docx, using NVDA report status bar info, NVDA should read page x of y, total word count, zoom level, etc.; however, it reads "blank"

Open Word 2010;
Ensure Word is maxamized with ALT+SPACE followed by X;
NVDA+END to report status bar info;
eExpected: page x of y, total word count, zoom level, and any other info that WOrd is set to report in status bar
Actual: NVDA reports "blank"

**Comment by leonardder** [comment]
Superseeded by #649. Closing as duplicate.
