### ISSUE TITLE
Report when a text is copyed in other documents

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2285]
**Reported by ateu on 2012-04-30 11:03**
At the moment, NVDA only report when a text is copyed in browse mode documents.
I agree that is not logical announces when a file is copyed, because the screen reader can't know this information.
But I'd like to know whether it's possible obbtain the information when a text is copyed in text editors.
If so, it would be really useful.

**Comment by dkager** [comment]
So do sighted people see an indication of a successful copy (not a paste)?
CC @leonardder

**Comment by leonardder** [comment]
I think they do not. Furthermore, this really looks like a duplicate.

**Comment by ehollig** [comment]
Duplicate of #553
