### ISSUE TITLE
Problems with object navigation

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2292]
**Reported by jfauchon on 2012-05-03 13:41**
Hello,

I have detected a problem with object navigation.

Step to reproduce:
1. Open Microsoft Word.
2. Press CTRL + O to go in Open Dialog.
3. When you want to go on OK button, object navigation don't go after Name edit or after a combo box or after a tab.

Those problems appear on others applications and in windows.

Thank you for your work.

**Comment by dkager** [comment]
Closing because this issue looks vague. Also, can't reproduce in Word 2016, though it looks quite different from e.g. Word 2003.
If there is a problem in older versions of Word it should probably go into a new issue with more details.
