### ISSUE TITLE
add option to skip layout/formatting information when tabbing through content.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2308]
**Reported by ashleycox on 2012-05-08 20:58**
It would be nice to have an option to disable the reading of layout/formatting information, such as the start and end of lists, tables, frames, landmarks, etc when tabbing through content, such as a webpage. This would enable the user to still have this information read when navigating through a document, but would mean they could tab through documents quickly.

**Comment by bhavyashah** [comment]
I am not too convinced by this feature request. The absence of any concrete usage case or justification for this feature and lack of justification for differentiation between arrowing and Tabbing makes this ticket somewhat incomplete.Thoughts/inputs from others would be appreciated.

**Comment by ehollig** [comment]
This should be fixed by #7434

**Comment by ashleycox** [comment]
Yes, I believe this is now resolved.

**Comment by ehollig** [comment]
Thank you @ashleycox. Closing
