### ISSUE TITLE
Braille: Outlook 2010 Message Cannot be read

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2317]
**Reported by kevinchao89 on 2012-05-10 13:48**
When using APH RefreshaBraille, there is no Braille support in Outlook 2010 messages.

Steps to Reproduce:
1. Ensure NVDA is configured with APH RefreshaBraille 18;
2. Open a message in Outlook 2010
3. Read content using Braille display
Expected: read using APH RefreshaBraille 18
Actual: Speech-only support/access

**Comment by dkager** [comment]
Hard to track down the problem, but I doubt if the braille display being used is the cause.

**Comment by jcsteh** [comment]
Can anyone still reproduce this?

**Comment by Adriani90** [comment]
I do not have any confirmations from other users regarding this issue. I guess it is related to the braille display and not generally to NVDA. I suggest to close it and reopen it as soon as more users report this issue.

**Comment by Adriani90** [comment]
cc: @jcsteh

**Comment by ehollig** [comment]
As this issue is pretty vague and we have not had users report something like this using a APH RefreshaBraille since this issue was created, I am going to close this.
