### ISSUE TITLE
STRANGE SYMBOK problem with systray nvda icon when activated by  simulated or real mouse clickS

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2334]
**Reported by SALJARY on 2012-05-14 04:47**
RIGHT CLICKING ON THE NVDA SYMBOL ON THE TASKBAR BRINGS UP A WINDOW FILLED WITH SQUARES INSTEAD OF TEXT.

**Comment by feerrenrut** [comment]
I cant reproduce this in Windows 10. What version of windows was being used at the time, does anyone remember?

**Comment by jcsteh** [comment]
@Brian1Gaff, can you still reproduce this problem? If so, what version of Windows? Can you provide steps that reproduce this for you? Thanks!

**Comment by bhavyashah** [comment]
This is a friendly reminder for @brian1gaff to kindly respond to @jcsteh's https://github.com/nvaccess/nvda/issues/2334#issuecomment-245240905.

**Comment by Adriani90** [comment]
We didn't get any answer from the initial author for more than 5 years and I guess this is not an issue in NVDA 2019.1.1. But if the problem still occurs though, please comment on it and we can reopen the discussion.
cc: @Qchristensen, @feerrenrut.
