### ISSUE TITLE
Feature request: The ability to jump to table boundaries

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2336]
**Reported by geoff on 2012-05-14 15:30**
I feel it would be very useful to be able to jump to the first or last 
row or column of a table.  Other screen readers have this functionality 
and it can make navigating tables much faster, particularly if you're 
very familiar with their contents.

**Comment by dkager** [comment]
We picked this up in #957, so let's discuss there.

**Comment by jcsteh** [comment]
Closing as duplicate of #957.
