### ISSUE TITLE
properties for human-readable or custom roles on NVDAObjects

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#235]
**Reported by mdcurran on 2008-11-24 11:31**
## Problem
- NVDAObjects can not by themselves provide a human readable role. This this makes debugging complex, in that the role's label must be manually looked up.
- Some APIs can provide custom roles, or type names for their objects. NVDA currently has no way of conveying this to the user.
  ## suggestion

NVDAObjects should contain a roleText property. By default, NVDAObject's should just look up the role's label and use that as the value. But for APIs that may have custom role strings, then it should provide that as the value instead. 
However, care must be taken to make sure that the role string is localized.
- If IAccessible2 objects have a localizedExtendedRole then use that, else use extendedRole, else let NVDA look up the label.
- For IAccessible (MSAA) NVDA should just look up the name, unless the role is a string and its not known by NVDA.
- For UI Automation, if it has a localizedControlType then use that, else let NVDA look up the label.
- Java Access bridge: if the role_us role is not known by NVDA, perhaps the localized role should be used.
  ## Questions
- How should braille use roleText? it may want to use shorter role labels, but NVDAObjects arn't to know if braille is asking or not. Unless of course _get_roleText took an optional argument to indicate that a shorter role is preferable.

**Comment by leonardder** [comment]
Is there still demand for this?

**Comment by bhavyashah** [comment]
@leonardder Given that the last comment didn't receive any response, it doesn't seem like there is much demand for this, I guess.

**Comment by leonardder** [comment]
This issue has two parts:

1. The ability to provide custom role text. This was done in #8448
2. Being able to find out what role an object has for debugging purposes. This can be done by getting the developer info, but #10732 will provide a much more elegant fix for that.

Closing this one.
