### ISSUE TITLE
nvda having issues when updating because of viper antivirus 2012

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2355]
**Reported by bmisch1000 on 2012-05-17 16:57**
when i tried updating nvda or downloading the latest snapshot and running it the nvda music goes on but then nothing else no errors or anything. not even a false positive from viper.

**Comment by bhavyashah** [comment]
Since there is little to nothing that NVDA can modify itself, the original author of this ticket is now out-of-reach and unfortunately he/she didn't respond to https://github.com/nvaccess/nvda/issues/2355#issuecomment-155297998 either, I suggest closing. @ehollig
