### ISSUE TITLE
NVDAObjects should have a way to convey extended/custom states to the user.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#236]
**Reported by mdcurran on 2008-11-24 11:56**
APIs such as IAccessible2 and UI Automation may have custom states on their objects. Examples of this  could be a contact in an instant messaging program, with a custom state of ''away' or 'online' etc.
NVDAObjects should contain a customStates property which is a list of strings which are the current custom states.
- IAccessible2: use localizedExtendedStates, or extendedStates.
- UIAutomation: use itemState

**Comment by leonardder** [comment]
This is similar to #235 and might be useful at some point

**Comment by Adriani90** [comment]
I am closing this in favor of #235 since the discussion goes further there and touches this aspect as well.
