### ISSUE TITLE
Unexpected table boundary condition on news.ycombinator while using Firefox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2362]
**Reported by Q on 2012-05-20 06:19**
While navigating the table on http://news.ycombinator.com with table navigation commands, I am only able to traverse two rows at a time before NVDA announces "edge of table."
This is using Snapshot Main 5193.

I appreciate your time.

**Comment by bhavyashah** [comment]
@jcsteh notes in https://github.com/nvaccess/nvda/issues/2362#issuecomment-155298038 - "I'll see what I can come up with when I get some time. If you/someone else wants to poke at this, I can provide a quick brain dump on where to start." Could you please do one of the above and share your thoughts?

**Comment by jcsteh** [comment]
Fixed by #7410. CC @CToth.
