### ISSUE TITLE
issue with the everything search program

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2371]
**Reported by troopanum on 2012-05-22 19:29**
For a substitute to the windows search box, I use a search program called everything.
For example, if I wanted to find a sertain setup file or search for a song on my computer I would type all or part of the name of the file into the edit box then I would press tab.
then I would press the down arrow to find the file I want.
However the edit box works fine with NVDA but when you pres tab and go to the list of files, it just says pane and when you press the down and up arrows it doesn't say anything at all.

**Comment by ehollig** [comment]
Closing as we do not have a way to contact the original author of this ticket, and the developer should really fix the accessibility of the application in the first instance.

**Comment by derekriemer** [comment]
This is now fixed anyhow (I use this puppy every day).
