### ISSUE TITLE
Cells, in calc, and excell spreadshees

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2381]
**Reported by lallermacher on 2012-05-25 08:30**
In microsoft office, and in libre office, the cells in excell or in calc are not good present. If I want to write a cell, in libre ofice, the name is spoken, but the written text not, and I can not write anyway in the cell. In office 2010, so in excel, the cell names are not present. It is, from an update to the cell names, for one month, or so.

**Comment by ehollig** [comment]
Closing for 2 reasons:

1. The original author did not reply to @jcsteh's comment in https://github.com/nvaccess/nvda/issues/2381#issuecomment-155298154
2. This ticket is over 5 years old, with no additional information provided from the author to replicate the issue.
