### ISSUE TITLE
NVDA doesn't allow braille scrolling in Eclipse

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2383]
**Reported by drein on 2012-05-25 09:23**
When using Eclipse, it is possible to scroll forward with braille, but pressing a button to go backword it gives an error.
Here is the log in attachment.

**Comment by Adriani90** [comment]
@drein is this still an issue for you?

**Comment by Adriani90** [comment]
We do not have an update from the initial author since years. I am closing this issue as abandoned.
