### ISSUE TITLE
Non working  nvda menu when nvda starts

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2384]
**Reported by briang1 on 2012-05-25 12:17**
Although this problem has existed intermmitently for a long time, I cannot see a ticket for it so I'm creating this one.
 It seems that for some reason when nvda starts, all appears well, but some things just do not work correctly. The usual  one is that nvda/n does not bring up the gui menu, but it can also affect other hot keys apparently randomly as well, and when one attempts to exit nvda, it usually crashes out but with no error messages.
 a small log fragment of a recent snapshot is below.

NVDA version main-5194

IO - speech.speak (12:09:44):
Speaking [Documents  1 of 77'](u'My)
IO - inputCore.InputManager.executeGesture (12:09:51):
Input: kb(desktop):NVDA+n
IO - speech.speak (12:09:51):
Speaking [ menu'](u'NVDA)
DEBUGWARNING - watchdog._watcher (12:09:53):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 155, in <module>
  File "core.pyc", line 339, in main
  File "wx_core.pyc", line 8010, in MainLoop
  File "wx_core.pyc", line 7306, in MainLoop
  File "wx_core.pyc", line 14669, in <lambda>
  File "gui__init__.pyc", line 130, in showGui
  File "gui__init__.pyc", line 378, in onActivate
  File "wx_windows.pyc", line 2190, in PopupMenu

IO - speech.speak (12:09:53):
Speaking [ list'](u'Desktop)
IO - speech.speak (12:09:53):
Speaking [Computer  2 of 77'](u'My)
IO - speech.speak (12:09:54):
Speaking [the disk drives and hardware connected to this computer.  tool tip'](u'Shows)
IO - inputCore.InputManager.executeGesture (12:10:00):
Input: kb(desktop):control+alt+i

The log ends there. that key combination is a batch file that reboots nvda after capturing the log, so it would usually contain the nvda shutting down log, but not when this issue is present.

I have set the error to core as I feel that the non appearence of the gui is just one symptom of the underlying problem. I've ncountered non working edit areas and menus as well if nvda is not restarted. Its as if its in an unstable state. I've  said xp, but this is just because I've not seen it myself on other os's.

**Comment by bhavyashah** [comment]
From @jcsteh's https://github.com/nvaccess/nvda/issues/2384#issuecomment-155298165, part of this bug affects Windows XP, specific to which issues are no longer addressed by NVDA. However, this does affect all portable/source/non-uiAccess copies too. I doubt that I have ever experienced the reported issue personally with portable copies, but since Jamie seems to be acknowledgeing it, that should be validation enough. Could fixes/solutions to this problem please be discussed and implementation related thoughts/inputs be shared?

**Comment by Adriani90** [comment]
This is Windows XP related and I didn' reproduce this on any other OS. However, also on Windows XP it seems to be related to some registry problems rather than NVDA itself. I suggest closing this. @briang1 you are welcome to open a new issue on Windows 7 or higher.

**Comment by Adriani90** [comment]
I didn'T hear any further reports from users on this and I don't know exactly where to start investigating. @Qchristensen do you have any users reporting this issue? If not, let's close it and reopen the discussion if the issue appears again. Personally I think this might occur when a dirty installation is on the system, maybe after down grading to older versions without uninstalling the current version etc. This could have really comprehensive reasons if it occurs and is quite hard to investigate. But anyway, we need more user reports on this containing more details.

**Comment by Qchristensen** [comment]
I actually did have a user report the NVDA menu not opening recently (first report I've seen in a long time).  Impossible to know whether it is related.  For my user, the log has:
“DEBUGWARNING - core.main (11:26:20.720):
Slow starting core (5.40 sec) “

and they were running addons as well, so it could have been a combination of a slow computer and misbehaving add-ons or anything.  I asked them to try with add-ons disabled and they haven't got back to me - maybe it was an add-on playing up, they fixed it and are happy and haven't let me know.  Either way, I'm still inclined to close this, and open a new issue with more information if we get a comprehensive, replicatable issue from someone on it.

**Comment by XLTechie** [comment]
I had it happen to me the other day while I was in a blazing hurry for 
something, so I was unable to grab a log. I later tried very hard to replicate 
it, and could not.
