### ISSUE TITLE
Windows Update control panel list items not reported until focus moved away from list once

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2387]
**Reported by mstopka on 2012-05-25 13:23**
Hi,

In windows update in windows 8 I have to tab away from the updates that are avabile before nvda will read them

**Comment by bhavyashah** [comment]
With reference to the Windows Updates Windows8.1's Start Menu offered me on a search, I had no major updates available. However, there were 11 optional updates available, which link I pressed and received this in the NVDA log:
DEBUGWARNING - RPC process 3372 (explorer.exe) (20:38:17):
Thread 5620, build\x86_64\remote\sysListView32.cpp, nvdaInProcUtils_sysListView32_getGroupInfo, 28:
LVM_GETGROUPINFOBYINDEX failed
However, if this affects Narrator as well and appears to be a Windows bug as believed by @jcsteh, reporting it to Microsoft is perhaps all that can be done.

**Comment by Adriani90** [comment]
@mstopka, @josephsl I guess you are not using Windows 8 anymore, but if yes, could you see if this is still occuring in control pannel with NVDA 2019.1.1?

**Comment by lukaszgo1** [comment]
I can still partially reproduce it on Windows 8.1 that is when the list of updates gains focus the first update isn't reported. When arrow is pressed the next one is announced and after that it works normally.

**Comment by Adriani90** [comment]
Support for Windows 8.1 has completely ended in January 2023, I don't expect further accessibility updates in this regard. I am closing as abandoned.
