### ISSUE TITLE
First available SAPI5 voice is used on secure screens

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2392]
**Reported by challsworth2 on 2012-05-28 15:36**
When using NVDA with the Microsoft Speech API version 5 synthesizer, if you run it as a standard user the voice chosen is used as normal. If you then decide to use the above synthesizer also on secure screens, the first voice available will be used, which is Microsoft Anna in this case. I looked in Speech Recognition, Text to Speech, and the voice I prefer, Ivona 2 Amy, is set as the default. This is on 64 bit.

**Comment by ehollig** [comment]
I can not replicate this using the latest NVDA on Windows 10. I tested this by setting my default voice to Microsoft Zira Desktop - English (United States) (the second one in the list) and saved the settings. Then I went to the setting for "Use currently saved settings on the logon and other secure screens" and activated it. When I press CTRL+Alt+Delete, Zira was the voice used, as expected. If anyone can replicate this issue on XP or Windows 7 I would be happy to reopen. Closing
