### ISSUE TITLE
Dubbal Speaking in the New Add-On manager

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2395]
**Reported by Brendon22 on 2012-05-29 03:09**
Hi when browsing to the Folder that you have your Add-on's in for NVDA. All of your folder names are being spoken twice? So if you had a folder called NVDA Add-on's. NVDA would say NVDA Add-on's NVDA Add-on's not just NVDA Add-on's . This is true for every folder that you pass? Using NVDA RC1

**Comment by Adriani90** [comment]
@Brendon22 is this still an issue?

**Comment by Adriani90** [comment]
Just to inform, this is still reproducible in NVDA 2019.1.1 on Windows 10 1809 Update.
