### ISSUE TITLE
anouncing of tab in ms word

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2396]
**Reported by aravind on 2012-05-29 14:32**
measurement of distance of tab is being anounced in jaws while typing in ms word. the same is not happening in nvda

**Comment by ehollig** [comment]
I believe NVDA announces the measurement of distance of tab now in Microsoft Word. Just tested in Microsoft Word 2016. Still, it would be interesting to know if these attachments are still needed. CC @feerrenrut

**Comment by feerrenrut** [comment]
I have added the attachments to this ticket.

**Comment by bdorer** [comment]
I wote for closing as worksforme. You get the needed information by pressing NVDA+delete or by inserting tabs. Tested with Word 2013.

**Comment by Adriani90** [comment]
Apart from pressing nvda+del, you can also enable "line indentation" in nvda settings and you will get coresponding information when navigating through the text. Closing as works for me because there are several ways to get tab distances in NVDA.
@bdorer thanks very much for picking this one!
