### ISSUE TITLE
In mozilla headingsd of tables that repete through the page repete.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2404]
**Reported by driemer.riemer@... on 2012-06-02 02:28**
The lov file has the info because this page is in a password protected area I have only given you the info I want you to see and have erased the typing of the username and password and have gotten rid of the url. The problem is that nvda speaks the headings in this gradebook multiple times. For example: name hotdog:  and the next section could be name: hamburger when nvda reads name name hamburger. This gets annoying when listening to it read this info repetitively.

**Comment by derekriemer** [comment]
Um, wow, I don't know what I was meaning to say with this ticket, closing as I'm stupid.

**Comment by derekriemer** [comment]
I think this is an issue with scope"col" and not setting the rowspan.
