### ISSUE TITLE
NVDA 2012.2 RC2 installer did not update the autostart path in the registry after having moved the existing installed copy (at a non-standard location) to the standard path

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2408]
**Reported by Palacee_hun on 2012-06-03 17:44**
The ticket summary pretty much says it all. My installed NVDA used to be at C:\NVDA. I wanted to install RC2. I checked both checkboxes in the install dialog. The install was without errors, but when rebooting NVDA didn't autostart at boot-up as it used to. It could be launched manually with its hotkey of course. The cause was that the path of NVDA executable hadn't got updated in the appropriate registry key during installation. I had to fix this manually with Regedit tool.
[[BR]]
one further remark: after RC2 installation, some files and folders were left in the old C:\NVDA folder, among them a temp folder. Its name is TMP plus 6 random letters. There is one file in it bearing the name TMP+ 6 random letters (different from those in the folder name). The file is an executable (albeit without .EXE extension). Its size is 54784 bytes. The leftover files haven't been removed by Windows at rebooting.

**Comment by bhavyashah** [comment]
According to @jcsteh's https://github.com/nvaccess/nvda/issues/2408#issuecomment-155298381, there seems to be nothing that can be done to solve this issue, and according to his https://github.com/nvaccess/nvda/issues/2408#issuecomment-155298384, the relevant change in standardizing the installation path is very much justified. Thus, I suggest closing. @ehollig

**Comment by josephsl** [comment]
Please reopen with further justifications as to why this problem must be fixed. Thanks.
