### ISSUE TITLE
NVDA crash when playing sounds in GoldWave

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2416]
**Reported by mrdin8877 on 2012-06-08 06:42**
STR:
1. Open goldwave.
2. open a file to edit.
3. press space bar to play the track/music/sound. now, press insert+f12 or something. NVDA will hang! it takes sometimes to speak. 
4. If you stop the sound with space bar again, NVDA will then becomes normal.

thanks!

**Comment by dkager** [comment]
Can't reproduce with GoldWave v6.28 and NVDA 2017.2.
