### ISSUE TITLE
Updating NVDA 2012.2 RC2 to NVDA 2012.2 takes a significant amount of time then displays a message

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2420]
**Reported by challsworth2 on 2012-06-08 15:56**
When attempting to update NVDA 2012.2 RC2 to NVDA 2012.2 using the check for updates feature, everything is fine until it begins to update. It then takes a significant amount of time, then displays something about do you want to try the update again or something like that. This is on an Acer Aspire 5733 running Windows 7 Home Premium 64 bit. The antivirus used is Microsoft Security Essentials and the antimalware used is the paid version of Malwarebytes. Reporting this on behalf of a friend Ms Day.

**Comment by dkager** [comment]
The two things I can think of:
1. Network issues at the time of the report.
2. The antivirus software taking extra long to scan the executable.

Closing this one because 2012.2 is well behind us.
