### ISSUE TITLE
reporting combo boxes/radio buttons position

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2429]
**Reported by fatma.mehanna on 2012-06-10 22:30**
when we open a dialogue, we want nvda to tell us the combo boxes/radio buttons positions. i.e, to inform us this is radio button one of 4 for example.
in browse mode, nvda reports radio buttons position in fire fox, but not in internet explorer.

**Comment by leonardder** [comment]
Hmm, this is an interesting point, but probably quite difficult if not impossible to do for MSAA. As for Firefox/IAccessible2, this seems already been implemented as the reporter points out. How about UIA?

cc @JCSTeh @MichaelDCurran

**Comment by Adriani90** [comment]
Closing as duplicate of #8187. Even if the title seems to restrict that issue to wpf combo boxes, the issue is more general and the discussion will continue on that issue.
