### ISSUE TITLE
nvda reporting repeated links in firefox.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2431]
**Reported by ashleycox on 2012-06-11 11:53**
When reading certain pages in firefox (google is a great example), nvda announces links that aren't present on the page. To reproduce, go to google, navigate to the top of the page, and read down the navigation bar - you will hear the navigation link, and then on each line underneath a navigation item, the word "link" will be spoken when there is actually no link present.

**Comment by leonardder** [comment]
I can't reproduce this on Google, closing as works for me. It is very unlikely that NVDA reports a link when there isn't a link. If it does, it is probably due to bad web page programming or a bug in the browser. Of course, we can reopen if you still consider this issue to be valid.
