### ISSUE TITLE
Cannot activate links in a given web page by any ways

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2436]
**Reported by clev on 2012-06-12 01:01**
I'm unable to activate any link at the top of the following page, such as home, about us, courses, etc. Enter does not work, nor does numpad insert+Enter, nor mouse single and double clicks...
www.mnblind.org

**Comment by leonardder** [comment]
Can't reproduce with Firefox, closing as works for me. Also, some essential information is missing, e.g. what browser is used?
