### ISSUE TITLE
Support role=alert in MSHTML

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2442]
**Reported by mike_Eck@... on 2012-06-12 15:28**
I'm working on making a dynamic web application accessible to the visually impaired via screen readers, and I'm running into a problem I hoping someone can help me with. 

When I test my code (see below) with JAWS, it was works just fine, reading me the alert as I expect. But when I use NVDA, I'm getting the dynamically-added content is being read -twice- by the reader in Firefox, and not being read at all in IE9.

Has anyone ever seen this kind of behavior before? I'm using Firefox 13.0, NVDA 2012.1, and Windows 7 64-bit. I'm new at NVDA and coding markup for accessibility, so it is entirely possible that there's something goofy in my code as well.

Thanks, anyone, for any ideas you may have!
-Mike

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<HTML xmlns="http://www.w3.org/1999/xhtml">
    <HEAD>
        <TITLE>Mike's Alert Test Page</TITLE>  
    </HEAD>
    <BODY>  
            <script type="text/javascript">
                function simulateErrors()
                {
                    var elem = document.getElementById("inlineErrors");  

```
                if (elem != null && elem != undefined) {
                    elem.innerHTML = '<DIV role="alert">I am some alert text.</DIV>';
                }
            }
    </script>       
    <H1>Test Page</H1>
    <DIV ID="inlineErrors"></DIV>
    <DIV ID="buttons">
        <input type="submit" value="Simulate Errors" onClick="simulateErrors()"/>
    </DIV>
</BODY>
```

</HTML>

**Comment by bhavyashah** [comment]
@jcsteh @michaelDCurran Just to clarify, is support for role=alert insufficient only in case of Internet Explorer, or does this affect other modern web browsers as well? If recent versions of Firefox and Chrome also demonstrate the problem(s) reported, then this ticket can be triaged, but addressing IE specific deficiencies are no longer worthwhile.

**Comment by michaelDCurran** [comment]
This only affects IE. NV Access is not going to actively pursue a fix, but will accept a PR.

**Comment by oleh-momot** [comment]
You can fix it if you will add `display=none` before to add your alert node to DOM
Then when you added the alert node you need to add content to this node and set `display=block`
It works on IE and other browsers too

**Comment by XLTechie** [comment]
@Adriani90 wrote:

> Support for Internet explorer ended completely in 2022, and the browser is being removed automatically from machines that still have it after an Edge update

But mshtml, which the title of this issue says it's about, will apparently be 
around until 2029.

https://techcommunity.microsoft.com/t5/access-blog/ie-11-retirement-what-does-this-mean-for-microsoft-access-apps/ba-p/3261899

**Comment by XLTechie** [comment]
> But mshtml, which the title of this issue says it's about, will apparently be
> around until 2029.

And to be more clear: it is the basis of NVDA's ui.browseableMessage function, 
which is used heavily by add-ons and core.

This should be re-opened until it is determined whether the actual issue has 
been solved.
