### ISSUE TITLE
List items in firefox have no space between item type and item

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2443]
**Reported by tspivey on 2012-06-12 19:53**
Browse the attached html file in Firefox, and in IE.
For both lists, in firefox the type (either number or bullet) has no space between it and the item text, while in IE they do.

**Comment by dkager** [comment]
This doesn't sound familiar to me (in browse mode with braille). A bit of clarification would be nice.

**Comment by leonardder** [comment]
@Tspify: Do you still consider this a bug and if so, could you provide the attachment again?

**Comment by jcsteh** [comment]
Appears to be fixed:

`data:text/html,<ul><li>item</li></ul><ol><li>item</li></ol>`

There is a space between the bullet or number and the text for each list item.
