### ISSUE TITLE
Alert of a change in system tray content.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2445]
**Reported by briang1 on 2012-06-13 08:38**
It seems that  as sighted folk will see, for example that a new user has logged in to  aMiranda session  and anti virus programs often alter their tray icons if they have changed state, that some form of alert to these changes would be very handy for us, rather than just having to go there periodically to see if there are any things we need to know.

Apologies if this has already been suggested, but could not find any enhancement exactly like this on the system. I don't know if this is even possible, but a little interesting blip noise  might be very handy.

**Comment by bhavyashah** [comment]
Going case-by-case seems to be the only way of implementing this, and doing that sounds somewhat impractical, IMHO. @brian1gaff Do you agree to close this ticket as a wontfix? From a technical standpoint, I am not exactly sure how feasible it would be to dynamically report updates to System Tray icons of a specific set of programs.

**Comment by Adriani90** [comment]
@Brian1Gaff is this still an issue? As far as I know most applications report their system tray icon status trhough Windows notifications or through own notifications like Dropbox for example.

**Comment by Adriani90** [comment]
@brian1gaff this is just a reminder before closing this issue. Do you still see this problem? The newest versions of many applicatoins send their change status through windows notifications which is being reported by NVDA. Can you confirm?

**Comment by Adriani90** [comment]
No updates since years, closing as abandoned.
