### ISSUE TITLE
All NVDA 2012 releases disables Dragon 11.5 Custom Voice Commands

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2456]
**Reported by fjwilke@... on 2012-06-16 21:04**
Hardware: Acer 8951G, Pentium I7 64-bit, 8 MB RAM
operating system: Windows 7 64-bit
in VDA 2012.1, 2012.2, 2000 12.2.1 clash with voice recognition software by Nuance called Dragon NaturallySpeaking 11.5

Nature of Problem: Dragon NaturallySpeaking 11.5 allows users to create custom-made voice commands.  Voice commands enter predefined text strings on command. NVDA 2012 releases disable these commands.
 I have returned to NVDA 2011.3 that does not cause this problem.

**Comment by dkager** [comment]
Any relation to the "Handle keys from other applications" setting?

**Comment by leonardder** [comment]
cc @DerekRiemer

**Comment by Adriani90** [comment]
@fjwilke@... can you still see this issue?
@dkager, @derekriemer any further comments on this?

**Comment by dkager** [comment]
Since this issue has long been abandoned and we can't easily trace the original poster on GitHub I am going to close this. Please reopen if you have more info.
