### ISSUE TITLE
Windows 8 start screen search doesn't read the first selected item

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2457]
**Reported by tspivey on 2012-06-17 08:14**
The start screen doesn't read the first item found for a search. For example, if I open it and start typing team,
I should land on TeamTalk 4 Classic. If I press enter at this point, that's the one that gets activated, but I don't hear the result.
Moving up and down the list works, although IMO the not selected spoken after everything is a bit misleading because pressing enter on the focused item opens it, regardless if I select it with space or not.

**Comment by ehollig** [comment]
As Windows 8.1 has superseded Windows 8, I am going to close this from @josephsl's comment in https://github.com/nvaccess/nvda/issues/2457#issuecomment-155298892 as worksforme
