### ISSUE TITLE
NVDA announces 'not selected' for items on the Windows 8 start screen

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2459]
**Reported by erion on 2012-06-17 11:24**
When moving through items on the Windows 8 start screen, NVDA announces not selected for each tile.
Since the tiles are not selected by default, I believe this is superfluous information.
NVDA should only announce the selected state when a tile is actually selected.

**Comment by leonardder** [comment]
I wonder whether this is still reproducible. I'll keep this open for the next week for people to bring in their findings. If we haven't got any reply by then, I'll consider this ticket abandoned and will close.

**Comment by leonardder** [comment]
@JosephSL: Do you have anything to add here?
