### ISSUE TITLE
blue screen of death when using nvda 2012.2.1

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2461]
**Reported by pf112781 on 2012-06-18 03:20**
i was reading a web page when nvda crashed. it crashed at 9:06 pm on saturday june 16.  i then investigated on my own and found that nvda slave.exe is not compatible with win 8 release preview. also when investigating i found that my windows event viewer recorded an event id of 439 i then rebooted and it occured again i am using windows 8 release preview on a hp pavillion p6774y pc i did virus scans and checked for disk errors and all came back fine.

**Comment by dkager** [comment]
Closing as @josephsl suggested.
