### ISSUE TITLE
NVDA's Sapi driver reacts a lot slower in windows 8

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2464]
**Reported by erion on 2012-06-18 16:15**
On a 64 bit Windows 8, NVDA's Sapi driver reacts a lot slower than in previous versions of the operating system.
Other applications using Sapi work fine.
This was only tested under 64 bit, but it might be present under x86 as well.

**Comment by bhavyashah** [comment]
CC @jcsteh

**Comment by Adriani90** [comment]
@erion can you still reproduce this?
@jcsteh, @michaelDCurran I guess there is low priority for this issue at NV Access. Right? Actually there was also some problems regarding this issue which have been reported in the german community as well. Especially with 24 khz voices. But I think those voices can be replaced by better and more responsive ones. Your thoughts are very appreciated.

**Comment by Adriani90** [comment]
We do not have any user reports on this one for a very long while. I am closing this. if you still have this problem, please comment on it and we can reopen the discussion. For me it works just fine with NVDA 2019.1.1 on Windows 8.1 and Sapi5 voices.
