### ISSUE TITLE
Name not rendered in virtual buffer for some ARIA roles

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#247]
**Reported by jteh on 2008-12-04 06:26**
The name of some ARIA widgets is not rendered into the virtual buffer. This includes ARIA radio buttons and list boxes.

**Comment by leonardder** [comment]
@jcsteh: Is this still a valid issue? You might be able to provide more details about what goes wrong in what browser?

**Comment by jcsteh** [comment]
- ARIA radio buttons were fixed as part of #1562.
- The label of list boxes is now reported when tabbing/using quick nav.
- List box labels are not reported when moving the caret in browse mode. This will be fixed by #4773.

Closing as duplicate given this is all covered by other issues.
