### ISSUE TITLE
Visual Studio 2010 Open Code Editor File Name Not Reported

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2471]
**Reported by Kerneels on 2012-06-19 20:55**
Changing between open code editor files with Ctrl + F6 (for example), NVDA doesn't speak the currently active file's name or title of the editor window. NVDA does speak the line the cursor is on.

**Comment by leonardder** [comment]
CC @mohammad-suliman, who seems to have provided a pr that might fix this.

**Comment by leonardder** [comment]
Visual studio 2010 is 9 years old. I've also received reports that this works properly in 2019. I'm closing this.
