### ISSUE TITLE
Cancelling download of update intermittently fails

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2476]
**Reported by elliott94 on 2012-06-20 09:58**
I was downloading a new update using the auto updater yesterday, and accidentally pressed the Cancel button during the process. Instead of stopping the download and closing the dialog, I had to wait about 10 seconds before I was told that the download had failed, at which point I could close the dialog. However, the downloaded launcher wasn't removed from the temp directory (see #2476 for more info).

However, what's interesting is that I tried downloading the update again, and the Cancel button closed the dialog without a delay.

I'm guessing this isn't how the button is supposed to behave, and that it should simply cancel the download and remove the launcher.

**Comment by bhavyashah** [comment]
@elliott94 Does this still occur for you?

**Comment by elliott94** [comment]
Happy for this to be closed - I haven't seen this since initially reporting.

**Comment by Brian1Gaff** [comment]
No me neither, though I notice when updating portable copies from the web, 
Firefox keeps on saying this file is not usually downloaded and you have to 
bring up the context menu in the downloads list and select the option to 
allow it to finish downloading.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by ehollig** [comment]
Closing from https://github.com/nvaccess/nvda/issues/2476#issuecomment-321464236
