### ISSUE TITLE
NVDA is slow reading the focussed item in the tree view of catigories in Utorrent.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2484]
**Reported by fatma.mehanna on 2012-06-23 21:35**
hi,
nvda in its latest version 2012.2.1 doesn't report the files that are being downloaded in µTorrent .
as the arabic users reported, this wasn't happened in the previous versions.
i don't use µTorrent  myself, so this is a feedback from our arabic comunity.
thanks.

**Comment by bhavyashah** [comment]
Various versions of NVDA as well as UTorrent released over the years may have well fixed the reported issue. Since we probably no longer have contact with the original author of this ticket, unless we receive feedback in a week's time confirming this issue at present with a more recent software setup, I suggest closing. @ehollig

**Comment by k-kolev1985** [comment]
No, the bugs described here are still present. In the list of torrents, NVDA does not report the name of the torrent currently selected. In the categories tree view, when moving up and down in the tree view, NVDA firstly reports the item from which we've moved and then the item to which we've moved the focus. As far as I know, the bugs are not language-Dependant and can be reproduced no matter the language in which uTorrent is set.

Test environment:
- Operating system: Windows 10 Pro version 1703 (build 15063.540), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: next-14373,6bbe5915, in bulgarian.
- uTorrent version: 3.5  build 43916 32-bit, in bulgarian.

**Comment by Adriani90** [comment]
@k-kolev1985, could you please test if this is still reproducible in uTorrent 3.5.5 with NVDA 2019.3.1 or newer? Thanks.

**Comment by k-kolev1985** [comment]
@Adriani90 Unfortunately, I cannot. I stopped using and uninstalled from my machine uTorrent at least a few months ago.

**Comment by Adriani90** [comment]
I tested in uTorrent 3.5.5 and this is not reproducible. Closing as works for me.
