### ISSUE TITLE
Add speech mode beep pitch to Voice Settings Dialog

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2487]
**Reported by Ahiiron on 2012-06-24 02:29**
It would be nice to have a quick edit field to quickly change beep pitch in the voice settings dialog, rather than edit the .ini directly.

**Comment by bhavyashah** [comment]
@michaelDCurran Based on https://github.com/nvaccess/nvda/issues/2487#issuecomment-155299122, you seem to be somewhat unconvinced about this feature request. the two comments after yours affect your take on this matter?

**Comment by fernando-jose-silva** [comment]
If I can raise a voice to the called, surely would vote for a setting to control the volume of the beeps, because in the current situation depending on the audio equipment used is very important to hear the beeps in a high volume.
The onecore voices, for example, are lower, forcing the volume to be high , making the beeps very comfortable.
If it is possible to control the volume of the other audios of the nvda would also be very good, but if there are great arguments for this only to control the volume of the beeps would be wonderful.

**Comment by bhavyashah** [comment]
@fernando-jose-silva  There is another ticket which deals entirely with the feature request of adding an Audio Manager to control the volume of all NVDA tones/beeps and sounds. Therefore, your suggestions in https://github.com/nvaccess/nvda/issues/2487#issuecomment-321381006 are already covered elsewhere.

**Comment by fernando-jose-silva** [comment]
Thank you very much.

 

De: bhavyashah [mailto:notifications@github.com] 
Enviada em: quarta-feira, 9 de agosto de 2017 23:55
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [nvaccess/nvda] Add speech mode beep pitch to Voice Settings Dialog (#2487)

 

@fernando-jose-silva <https://github.com/fernando-jose-silva>  There is another ticket which deals entirely with the feature request of adding an Audio Manager to control the volume of all NVDA tones/beeps and sounds. Therefore, your suggestions in #2487 (comment) <https://github.com/nvaccess/nvda/issues/2487#issuecomment-321381006>  are already covered elsewhere.

**Comment by ehollig** [comment]
The issue dealing with volume of NVDA sounds is #1409. This ticket is different, however, as it deals with the frequency of the beeps.

**Comment by Adriani90** [comment]
@michaelDCurran is it probable that NV Access implement a function like this? Or are there any plans to change the beeps to a more lovely sound?

**Comment by Adriani90** [comment]
cc: @feerrenrut

**Comment by Adriani90** [comment]
Actually, I will close this as duplicate of #9308. The discussion in that issue is more detailed and the justifications for such a feature are more comprehensive.
