### ISSUE TITLE
I wish to support tencent qq.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2489]
**Reported by vgjh2005 on 2012-06-24 07:03**
  qq is a famous software in China.thousand of people is using it.But It's gui is very special.NVDA can not get any information about the application.If NVDA can support it,and I think NVDA will become more successful in China.Thanks.You can download it here:http://dl_dir.qq.com/qqfile/qq/QQ2012/QQ2012Beta2.exe

**Comment by Adriani90** [comment]
@vgjh2005, @qingtian, @Palacee_hun, is this issue still reproducible in the last qq version? Could someone please post a link to the last version?

**Comment by Adriani90** [comment]
@larry801 do you have any information about the application for which @vgjh2005 requests support with NVDA? I don't really know this application actually.

**Comment by cary-rowen** [comment]
Tencent QQ can now be used with NVDA, but the performance of NVDA will be reduced on some list or menu objects in Tencent QQ, but I think this is another issue, so NVAccess can already close this issue.
