### ISSUE TITLE
speech recognition software to operate NVDA-key?

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2494]
**Reported by cwadsworth on 2012-06-25 21:07**
How may speech recognition software be used to emulate keyboard control for the NVDA-key?  Dragon NaturallySpeaking, as far as I can see, does not allow voice control to use Insert or CapsLock in combination with other keys.  Could the NVDA key be re-assigned to something else?  Sorry, I'm not a Python programmer.
**Blocking #3429**

**Comment by derekriemer** [comment]
hey, how could dictationbridge interface with this?

**Comment by dkager** [comment]
See also #2976, which is broader in scope.

**Comment by leonardder** [comment]
[**@derekriemer**](https://github.com/derekriemer) commented on [12 apr. 2017 10:57 CEST](https://github.com/nvaccess/nvda/issues/2494#issuecomment-293516105 "2017-04-12T08:57:31Z - Replied by Github Reply Comments"):
> hey, how could dictationbridge interface with this?

How do you mean your question? I guess dictation bridge would be able to execute the NVDA key and its input will be handled by NVDA as long as Handle keys from other applications is on. Tempting to close this like #2976.

**Comment by jcsteh** [comment]
Closing because DictationBridge allows for execution of NVDA commands. See #2976.
