### ISSUE TITLE
review position isn't updated when moving through edit field with shift key pressed

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#250]
**Reported by aleksey_s on 2008-12-04 21:45**

when you select text in edit field and press insert+uparrow or numpad8, nvda reports current line as it is first before selection.

### steps to reproduce
- start notepad
- enter two lines of text: "Hello" and "World"
- go to start of document
- press shift+down arrow
- press numpad8
 
### Actual result
nvda announces the first line of text: "Hello"

### expected results
nvda must announce second line of text, which is really current line: "World"

**Comment by leonardder** [comment]
@dkager, Is this somehow covered in #6775? Probably not

**Comment by dkager** [comment]
No, but that could could be a good starting point. It would add an attribute indicating at which end the selection is anchored.

**Comment by feerrenrut** [comment]
I have updated the description to make this a little easier to talk about.
I can reproduce this in NVDA `next-14098,66f26bb2`.
Visually I can confirm that when positioning the caret before the 'H' pressing shift down results in the caret moving to the second line, before the 'W' character.
After removing the selection and positioning the caret before the 'W' pressing shift up results in the caret moving to the first line, before the 'H'.

**Comment by feerrenrut** [comment]
Setting this as priority 2 since it seems related to some recent work in #7131 (Though I'm not suggesting this is a regression caused by it)

**Comment by Adriani90** [comment]
cc: @JulienCochuyt

**Comment by Adriani90** [comment]
Closing in favor of #16549 which contains more discussion and different use cases.
