### ISSUE TITLE
Proxy support for the update feature

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2504]
**Reported by menschomat on 2012-07-02 08:30**
That's not an important problem, but when I try to update NVDA at work, it didn't run. I suppose the reason for the problem is the proxy.
I read the manual but didn't find something where I could add the proxy data. So if NVDA didn't have this feature, yet, I suggest to add it in one of the next versions. Thank you.

**Comment by bhavyashah** [comment]
@jcsteh The original author of this ticket, although now out-of-reach, did follow-up in https://github.com/nvaccess/nvda/issues/2504#issuecomment-155299220 to your initial questions. Could you please triage this ticket depending on whether or not we have sufficient information to diagnose the reported issue?

**Comment by jcsteh** [comment]
There isn't sufficient info here. While we do know that the proxy requires a username and password, we don't know how it is configured on the system; i.e. whether it is auto configuration, manually entered data in the system settings, configured separately in each application, etc. Closing.
