### ISSUE TITLE
NVDA and www.oasis.com

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2506]
**Reported by challsworth2 on 2012-07-03 16:16**
NVDA sometimes crashes when updating one's profile on the free dating site www.oasis.com. Attached is the log.
Hope this can be reproduced.

**Comment by leonardder** [comment]
@elliott94: As you were able to provide a log regarding this website, do you think this issue is still present?

**Comment by elliott94** [comment]
I haven't seen this since the initial time that it was reported - happy for this to be closed.
