### ISSUE TITLE
Yahoo Messenger support

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#251]
**Reported by Vortex on 2008-12-05 14:22**
I'm not sure, but it may be possible to add support for Yahoo messenger in NVDA. It works to a degree already, when one reaches a conversation window all messages are read.
The object wich contains the conversation text could be found by using object navigation.
NVDA says "property page" when reaching the object wich contains the text, but when trying to read the text by line or by word nvda reads the entire object every time.
Steps to reproduce:
- download Yahoo messenger 8 from http://us.dl1.yimg.com/download.yahoo.com/dl/msgr8/us/ymsgr8us.exe;
- create an account at"http://mail.yahoo.com if applicable;
- install the application;
- open the application, login, and add yourself as a contact;
- open a conversation.

The info I retrieved with ins+f1 about the object containing the conversation text is:
Control ID: 2819229
Class: IMClass
internal text:  .
I know that the internal text field is empty, but the text is actually here, at least NVDA reads it.
I know there is Yahoo messenger 9, but I haven't used it, and I don't know if there are any differences.
I know about Miranda, but based on what I've written above I think that there is a chance to implement yahoo messenger support for NVDA, as I see it we have to find out how to get the coordinates of the cursor while reading the text conversation. After that maybe some keyboard shortcuts for reading messages would be an interesting addition, but we'll see then.

**Comment by leonardder** [comment]
cc @josephsl.

As you wrote the last comment in this, you might have an idea whether this issue is solved in Yahoo Messenger?

**Comment by ehollig** [comment]
Acording to [Wikipedia](https://en.wikipedia.org/wiki/Yahoo!_Messenger), the Yahoo Messenger desktop client is no longer being developed and the clients no longer working by August 31, 2016.
CC @josephsl @leonardder

**Comment by jcsteh** [comment]
It looks like there is some new Yahoo Messenger app now which is still supported. However, we don't have any details at all concerning the accessibility of this new client, so I think that should be addressed separately. Closing.
