### ISSUE TITLE
change the voice of language Sinhalese(ISO 639-2 code sin)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2514]
**Reported by thimal on 2012-07-08 08:11**
Translate in voice in to shinalese and switch to sinhalese in autolanguage switch

**Comment by bhavyashah** [comment]
As Mesar noted in https://github.com/nvaccess/nvda/issues/2514#issuecomment-155299315, this ticket is too vague and unclear, we have no means of contacting the original reporter, and unfortunately he/she did not follow-up either on Mesar's prompt. Time to close? @ehollig

**Comment by ehollig** [comment]
Unfortunately, there is not enough information provided in this issue.
If you would like to help translate NVDA into a language that is currently not supported, take a look at the page for [Translating NVDA](https://github.com/nvaccess/nvda/wiki/Translating) and subscribe to the [NVDA Translations email list](https://www.freelists.org/list/nvda-translations).
If you would like a language that is currently not supported in ESpeak NG, please create a new issue on the [ESpeak NG Github Issue Tracker](https://github.com/espeak-ng/espeak-ng/issues/new).
