### ISSUE TITLE
Some of the error messages in Windows Live Mail 2009 are not spoken by default

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2515]
**Reported by briang1 on 2012-07-08 09:12**
Recentlyy I have been using windows Live Mail 2009 on Windows XP and noticed that when error messages occur, they seem to only read the  choice buttons, such as OK. The text in the  aleert or error box can be read with nvda/B or using object navigation but  the window seems to be being identified as Dialogue. Here is a sample log fragment from a recent snap of nvda and the  nvda/F1 output after navigating to the message.

IO - speech.speak (12:08:56):
Speaking [\- SoC  Subject: Re: Tech for social change - event #9 this 
Monday, Date: 07/07/2012 09:33  1565 of 1566'](u'Marc)
IO - inputCore.InputManager.executeGesture (12:08:57):
Input: kb(desktop):enter
IO - speech.speak (12:08:57):
Speaking [Live Mail  dialog'](u'Windows)
IO - speech.speak (12:08:57):
Speaking [ button'](u'OK)
IO - inputCore.InputManager.executeGesture (12:09:23):
Input: kb(desktop):NVDA+b
DEBUG - queueHandler.registerGeneratorObject (12:09:23):
Adding generator 1085
IO - speech.speak (12:09:24):
Speaking [u'Windows Live Mail  dialog'](IndexCommand%280%29,)
IO - speech.speak (12:09:24):
Speaking [u'graphic'](IndexCommand%281%29,)
IO - speech.speak (12:09:24):
Speaking [u'There was an error opening this message.\n\nAn 
error has occurred.  text'](IndexCommand%282%29,)
IO - speech.speak (12:09:26):
Speaking [u'link'](IndexCommand%283%29,)
IO - speech.speak (12:09:26):
Speaking [u'OK  button'](IndexCommand%284%29,)
IO - inputCore.InputManager.executeGesture (12:09:44):
Input: kb(desktop):numpad4
IO - speech.speak (12:09:44):
Speaking [- speech.speak (12:09:44):
Speaking [u'OK'](u'top']
IO)
IO - inputCore.InputManager.executeGesture (12:09:45):
Input: kb(desktop):numpad6
IO - speech.speak (12:09:45):
Speaking [- speech.speak (12:09:45):
Speaking [u'OK'](u'bottom']
IO)
IO - inputCore.InputManager.executeGesture (12:09:49):
Input: kb(desktop):NVDA+numpad7
IO - speech.speak (12:09:51):
Speaking [flat review for this object'](u'No)
IO - inputCore.InputManager.executeGesture (12:09:56):
Input: kb(desktop):NVDA+numpad4
IO - speech.speak (12:09:56):
Speaking [- inputCore.InputManager.executeGesture (12:10:00):
Input: kb(desktop):numpad4
IO - speech.speak (12:10:00):
Speaking [u'top'](u'link']
IO)
IO - speech.speak (12:10:00):
Speaking [- inputCore.InputManager.executeGesture (12:10:01):
Input: kb(desktop):numpad6
IO - speech.speak (12:10:01):
Speaking [u'bottom'](u'blank']
IO)
IO - speech.speak (12:10:01):
Speaking [- inputCore.InputManager.executeGesture (12:10:03):
Input: kb(desktop):numpad4
IO - speech.speak (12:10:03):
Speaking [u'top'](u'blank']
IO)
IO - speech.speak (12:10:03):
Speaking [- inputCore.InputManager.executeGesture (12:10:08):
Input: kb(desktop):NVDA+numpad4
IO - speech.speak (12:10:09):
Speaking [u'There was an error opening this message.\n\nAn error has 
occurred.  text  read only'](u'blank']
IO)
IO - inputCore.InputManager.executeGesture (12:10:21):
Input: kb(desktop):NVDA+numpad4
IO - speech.speak (12:10:21):
Speaking [ read only'](u'graphic)
IO - inputCore.InputManager.executeGesture (12:10:40):
Input: kb(desktop):control+alt+i
INFO - core.main (12:10:49):
Exiting

INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo 
(12:20:07):
Developer info for navigator object:
name: u'There was an error opening this message.\n\nAn error has occurred.'
role: ROLE_STATICTEXT
states: STATE_READONLY
Python object: <NVDAObjects.IAccessible.StaticText object at 0x03D01B90>
Python class mro: (<class 'NVDAObjects.IAccessible.StaticText'>, <class 
'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, 
<class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, 
<class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (212, 173, 197, 39)
value: None
appModule: <'wlmail' (appName u'wlmail', process ID 1060) at address 
3cf5eb0>
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 2294646L
windowClassName: u'Static'
windowControlID: 1002
windowStyle: 1342308352
windowThreadID: 3372
windowText: u'There was an error opening this message.\n\nAn error has 
occurred.'
IAccessibleObject: <POINTER(IAccessible) ptr=0x1aa008 at 3cf2e40>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=2294646L, objectID=-4, childID=0L
IAccessible accRole: ROLE_SYSTEM_STATICTEXT
IAccessible accState: STATE_SYSTEM_READONLY, STATE_SYSTEM_VALID (64)

I have not at this time tested this with older versions of nvda.
The same seems to be true of other errors, such as when the connection is dropped while downloading from Imap servers.

**Comment by dkager** [comment]
@leonardder You are WLM wizard. Is there still a working version of this software?
CC @brian1gaff

**Comment by leonardder** [comment]
WLM is discontinuued and the last version was 2012, not 2009 as @Brian1gaff pointed out. Closing as won't fix.
