### ISSUE TITLE
NVDA crashed

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2517]
**Reported by Twinsen on 2012-07-09 15:05**
NVDA work 2 days and self stoped.

**Comment by ehollig** [comment]
Unfortunately, I am not able to replicate this. If there is information presented in the log provided that I am missing, please let me know.

**Comment by jcsteh** [comment]
here are the attachments from Trac:

[nvda.log.txt](https://github.com/nvaccess/nvda/files/1151544/nvda.log.txt)
[nvda.2.log.txt](https://github.com/nvaccess/nvda/files/1151546/nvda.2.log.txt)

Unfortunately, on a quick glance, there's nothing useful we can glean from them. There are no suspicious errors, etc.

Closing as invalid, as we don't have sufficient info, this is quite old now and we have no way of contacting the reporter.
