### ISSUE TITLE
Miranda IM message feedback only given after enitial interaction after NVDA restart

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2519]
**Reported by elliott94 on 2012-07-09 22:43**
This is most likely a limitation to the way that NVDA retrieves information from Miranda, but feedback is only given about activity in the focused message window after an enitial event. For example, if I send a message to a contact, I won't hear the first message, but if they reply or a second mesage is sent this information is announced.

This can only be seen for windows that already have focus when NVDA is restarted.

**Comment by leonardder** [comment]
This is annoying, but certainly not high priority. Giving this p4.

**Comment by elliott94** [comment]
Unfortunately I haven't used the Miranda client for several years now - is anybody able to confirm?

**Comment by Adriani90** [comment]
@sukiletxe can you maybe try to reproduce this?

**Comment by Adriani90** [comment]
@codeofdusk can you test if you can reproduce this? I guess this issue was not part of your draft PR targeting Miranda. Right?

**Comment by Adriani90** [comment]
Actually Miranda IM is discontinued since 2018 and is replaced by Minranda NG. Thus, closing this issue as wont fix.
