### ISSUE TITLE
NVDA Custom Label Feature for Web Pages, Word and PDF Documents

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2531]
**Reported by louie12000 on 2012-07-16 02:30**
NVDA really needs a custom label feature useful for web pages, Microsoft Word and Adobe PDF documents.

**Comment by leonardder** [comment]
Closing as duplicate of #5874. While this issue is broader in scope, #5874 has pull requests associated. Furthermore, the need for custom labels in Word en PDF documents isn't clear to me.
