### ISSUE TITLE
Unable to use The New Braille Sense U2 32-Cell in Excel 2010 Pro

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2536]
**Reported by Brendon22 on 2012-07-17 11:01**
Hi,
I'm unable to scrol up or down in Excel 2010 Pro and See A1 A2..... In Excel 2010 All I get is excel -- Book1 Sheet1 tb cell.

Scroling up or down will show the same information?
Hmmm

**Comment by dkager** [comment]
It seems unlikely that the particular type of braille display is the issue. Closing because clear STR are missing.
