### ISSUE TITLE
Lost feedback when the context menu is opened

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2542]
**Reported by Twinsen on 2012-07-18 18:22**
Good day! My computer work without reboot about 3 days.When I end my work I press power button and he stay some think like sleep mode.For start working I press any button on my keyboard.When I work some times I open pop-up context menu, in this moment I lost feedback with NVDA, I can't navigate between  items of this menu using (UP) and (DOWN) arrows on my keyboard.Please see my log file in end  of this file I press  (APPLICATIONS)buttonof my keyboard to open context pop-up menu.After this I try using (UP) ,(DOWN)arrows to navigate on this menu but nothing to bee happened.You may see also moment when I press (CAPS LOCK) + (N)to open NVDA pop-up menu.When this issuesis appear I can,t switch between opened windows using (ALT) + (TAB)the NVDA talk about switching between windows but nothing to be happened.Also I can't switch between windows using (CTRL) + (ALT) + (TAB)in this dialog I can navigateon items using (LEFT) and (RIGHT) arrows but can't switch using (ENTER) button of my keyboard.To exit from this situation need used flat rebiew (NVDA) + (NUMPAD) to actibate any menu item from this pop-up menu.After this the NVDA work correct. 
I habe some qwestions not related with this issues:
1)I create some tickets.How I can understand so my ticket is started or planed to resolve? Do I need change ticket status to starting resolve this issues?
2)How I can use controls placed on web page into the franes?

**Comment by bhavyashah** [comment]
@brian1gaff According to your https://github.com/nvaccess/nvda/issues/2542#issuecomment-155299538, you did experience this or related issues at the time. Is this still the case? If not, I suggest closing this ticket due to the lack of detailed diagnostic information provided and the lack of any means to get in touch with the original reporter of this issue. @ehollig

**Comment by Adriani90** [comment]
@Twinsen are you still having this pbroblem in NVDA 2019.1.1? Could you please run the com registration fixing tool in nvda menu / tools? Does this solve your issue?

**Comment by ehollig** [comment]
We have not heard from the author of this issue since the creation of the ticket. Due to the insufficient information provided as well as the inability to get in touch with the original reporter of this issue, I am going to close this issue. Closing
