### ISSUE TITLE
Remote NVDA like Remote assistance on Windows

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2557]
**Reported by nvdakor on 2012-07-25 03:13**
Hi,
A suggestion brought on one of the language forums: would it be possible to create a remote NVDA feature where one user of NVDA on one computer can control NVDA installation on another computer, similar to functions on other screen readers and Windows Remote Assistance?

**Comment by bhavyashah** [comment]
As of 2017, we have the NVDA Remote add-on (CC @tspivey) and there exists another ticket requesting for the incorporation of this add-on's functionality into core. Time to close? @ehollig

**Comment by ehollig** [comment]
I am not sure if this should be closed quite yet, as @jcsteh thoughts in https://github.com/nvaccess/nvda/issues/2557#issuecomment-155299647, while there are common concepts, #3564 is related, but probably not dependent.

**Comment by jcsteh** [comment]
Closing as a duplicate of #4390, since it is more recent and talks about integration fo NVDA Remote, rather than rolling something completely new.
