### ISSUE TITLE
Auto Language Switching in Microsoft Speech Platform

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2561]
**Reported by ateu on 2012-07-25 12:55**
Corrently, this voices has a good quality, so that they are been used for several users, as this is a good free solution with respect to natural voices.
As they has voices in several languages, I think it's a important request.

**Comment by bhavyashah** [comment]
Since a more universal auto language switching functionality is in the works elsewhere (by Dinesh Kaushal and others), could we close this ticket as a duplicate of that other? @ehollig

**Comment by josephsl** [comment]
Hi,

Seven years later...

Considering that we have Windows OneCore and other naturally sounding voices with (hopefully improved) language switching performance, I think it would be best to close this one (for now).

Thanks.
