### ISSUE TITLE
Allow the creation of portable copies to be canceled

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2565]
**Reported by elliott94 on 2012-07-26 13:54**
Currently, it isn't possible to cancel the creation of a portable copy once the process has started.

A Cancel button could be added to the creation window which when clicked, would abort the process and remove any created directories from the selected destination.

**Comment by ehollig** [comment]
From the comment in https://github.com/nvaccess/nvda/issues/2565#issuecomment-155299712, this sounds sort of related to #3113

**Comment by josephsl** [comment]
Hi,

Seven years later...

This issue is about canceling portable copy creation process. I believe newer issues have more detailed justifications and discussion points, and if yes, let's close this one.

Thanks.

**Comment by seanbudd** [comment]
Closing as won't fix. Unless your machine is incredibly slow, I don't think it's really possible or worthwhile to cancel the action. The creation of the portable copy takes me about 2-3 seconds. You can always delete the folder later, so cancelling would really only save 2-3 seconds of time.
