### ISSUE TITLE
Bug with NVDA reading website: coursera

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2566]
**Reported by miahtech on 2012-07-29 03:04**
This could be a website that isn't coded as it should be, but even so, it'd be nice if something were put in to prevent this behavior.
When you go to the web page https://www.coursera.org/course/qcomp
NVDA starts reading "blank blank blank" while on that page, and will not stop until you navigate away from the page. 
I am using Firefox nightly.

**Comment by ehollig** [comment]
Looks like the original link does not exist anymore. Sounds to be invalid, unless there is another site that experiences the same behavior.
