### ISSUE TITLE
Excel: Report The Presence Of Drop Down Lists When Focus Lands On Cells That Contain Them

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2575]
**Reported by jhomme on 2012-07-31 12:41**
This may also involve the speaking of list boxes that result when someone uses Alt + Down Arrow to open a drop down list in a cell, but I don't have NVDA on this computer to verify that. 

Open the attached spreadsheet, which was created with Excel 2010.

Move to the top left corner.

At this point, the enhancement would be that NVDA would report that there is a filter on for this column, and that the current cell contains a drop down list.

The user would then use Alt + Down Arrow to open the list and choose how they want Excel to filter the rows of the spreadsheet.

**Comment by bhavyashah** [comment]
@Qchristensen For some odd reason, I am under the impression that you had filed a more recent ticket which duplicates this one. Thoughts?

**Comment by Qchristensen** [comment]
I filed #6452 about data validation list items being read twice (in Excel 2016).  In that case, the list itself is being identified though (NVDA reports, "Sub-menu B3" for instance).

Issue #5012 looks like it is about navigating within drop down lists, but doesn't indicate how they are identified.  It also references a number of other open and closed issues.

There are a couple of issues about filters not being identified.  Using filters in Excel 2016, I found that Excel simply reads the cell contents when you navigate to a header cell which has a filter applied, but doesn't identify that there is a sub-menu as it does for data validation sub-menus.  When you open the sub-menu with the applications key or alt+down arrow, the contents are read correctly.

Back to this issue, if someone could double check whether this behaviour is the same in Excel 2010 we could perhaps close this as fixed, or as a duplicate of one of the other issues.

**Comment by fernando-jose-silva** [comment]
Using excel 2013 when I press alt + down arrow in a cell the nvda utters list only, when walking with the arrows above or below the list nvda does not read anything.
Nvda masterpiece 14294

**Comment by Adriani90** [comment]
@michaelDCurran is there any chance for NV Access to look into this? Reporting columns with filters and dropdowns is very important, especially for people working in complex excel sheets.

**Comment by Adriani90** [comment]
It is even worse in Excel 2016 / 365, the dropdown / filter cannot be recognized at all. NVDA reports "undknown" and I get following errors:

```
IO - inputCore.InputManager.executeGesture (12:05:52.207):
Input: kb(laptop):alt+downArrow
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (12:05:52.242):
Could not locate dropdown list in previous objects
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (12:05:52.417):
Could not locate dropdown list in previous objects
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (12:05:52.460):
Could not locate dropdown list in previous objects
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (12:05:52.493):
Could not locate dropdown list in previous objects
DEBUGWARNING - NVDAObjects.window.excel.ExcelCell.script_openDropdown (12:05:52.519):
Failed to get dropDown, giving up
IO - inputCore.logTimeSinceInput (12:05:52.684):
0.478 sec since input
IO - speech.speak (12:05:52.684):
Speaking [u'Unbekannt']
IO - inputCore.InputManager.executeGesture (12:05:53.664):
Input: kb(laptop):escape
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (12:05:53.780):
oleacc.AccessibleObjectFromEvent with window 198876, objectID -4 and childID 0: [Error -2147024809] Falscher Parameter
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (12:05:53.789):
IUIAutomationElement.buildUpdatedCache failed given IDs of set([30019, 30022, 30086, 30025, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079])
DEBUGWARNING - eventHandler.executeEvent (12:05:53.805):
error executing event: typedCharacter on <NVDAObjects.UIA.UIA object at 0x058215F0> with extra args of {'ch': u'\x1b'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 913, in event_typedCharacter
  File "speech.pyc", line 683, in speakTypedCharacters
  File "api.pyc", line 248, in isTypingProtected
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 787, in _get_isProtected
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1116, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 741, in _getUIACacheablePropertyValue
COMError: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten aufrufen.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (12:05:53.885):
Could not locate dropdown list in previous objects
```
cc: @lukaszgo1

**Comment by leonardder** [comment]
@Qchristensen how is this issue related to #6065?

**Comment by Qchristensen** [comment]
@leonardder it appears to be the same issue - identifying cells which have a filter and that you can press alt+down arrow to open.

The title of this issue simply refers to "drop-down lists" (which could also include data validation lists), however, the provided example includes autofilters.  Data validation lists are slightly different although those cells are also not identified.  It is possible that fixing identifying one also fixes identifying the other,

**Comment by Adriani90** [comment]
Closing in favor of #5012 and #6065.
