### ISSUE TITLE
How to possibly implement a "simple" diagram reader

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2585]
**Reported by Agran on 2012-08-06 11:30**
1. Identify picture as diagramm, plot. (no clue, trial and error?, tagged?)
2. Extract scaling values (OCR)
3. (Dis)play plot, diagramm as time dependent audio.
4. Read out scaling with reference audio, repeat diagram
5. Repeat on demand

After recognizing the type of diagram, you should handle diagrams either as continuous diagrams like stock exchange curves or singular point or bar diagrams.

Continuous diagrams should have a short forte when crossing a y-scaling value and a metronome could give x scaling.

Bar diagrams are a bit easier to understand. After reading category you make the audio elevate from 0 to max y (including a forte on the scaling, which should make it more a bit easier), than next category.
You could probably set single points in categories instead of a bar-like elevation of the audio, but this seems more comprehensible.

You can even have parallel categories/curves "displayed" with different instruments/sound characters

I hope someone finds this useful, I hopefully won't need it. If I'd knew how to program it, I'd done it myself. But alas, I hope this helps and of course all the best luck for the recognition part which is quite complicated. I only realized this when I wrote down the step by step approach. I won't be here often, but feel free to contact me on the subject chrush at web dot de

**Comment by leonardder** [comment]
I think that this is way beyond the scope of what a screen reader should do by default. Leaning towards a won't fix, but I'd like to have other's opinions first.

**Comment by derekriemer** [comment]
well, we could theoretically do some of this with cloud sourced image descriptions, and we do this in excel, but not OCR.

**Comment by dkager** [comment]
I agree with @leonardder that at least part of this feature request lies with content providers and/or user agents.

Besides that the ticket is too broad:
- What kind of diagrams? Only line and bar diagrams and pie charts? What about diagrams from specific fields of science: Venn diagrams, Gantt charts, automata, UML class dagrams, histograms, etc.
- What is the source of the diagram? Standard images, vector images, Excel, modeling tools, R, etc.
- Do we really want audio only? Could it not be useful to interact with the diagram like you can with math?

Also leaning toward wontfix, but I would be happy to brainstorm about such a feature for specific visual diagrams/schematics in a specific program, e.g. Excel charts.

**Comment by jcsteh** [comment]
Closing as won't fix. If there are solid ideas on specific proposals with clearly defined goals, user experience and feasibility, we can consider these in separate issues.
