### ISSUE TITLE
NVDA Not Working with the GMAIL Account Creation Page

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2587]
**Reported by waldorfpc on 2012-08-07 12:44**
Hello:

I am writing to report to you that the current version of NVDA is not working compatibly with the new layout of the page that facilitates creating a new GMail account. I know that it is an NVDA problem because I tested it with JAWS, and it worked fine.

The problem I see is that Google has chosen to use some type of list box or menu if you will. One list box is used wen choosing a month for filling out the birthday portion, and another list box is used when choosing the gender.

If you want to see what I mean, feel free to go to gmail.com and choose the link that allows a new account to be created.

Thanks so much for all of your hard work maintaining this wonderful screen reader.

Warm regards,
Reina Grosvalet

**Comment by derekriemer** [comment]
added blocked.

**Comment by derekriemer** [comment]
oops, removing blocked and closing as fixed.
