### ISSUE TITLE
Don't announce end-of-container when quick navigation keys are used in browse mode

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2591]
**Reported by aliminator on 2012-08-10 07:33**
NVDA announces end-of-container when jumping somewhere else using the navigation quick navigation keys.
Visiting for example 
[http://en.wikipedia.org/wiki/Football_at_the_2012_Summer_Olympics]
and navigating to the table of contents.
In the list, when pressing the h key to get to tthe next heading, NVDA announces end-of-list (maybe multiple times, depending on the nesting).
This behaviour should be turned off in this case because users can act quicker and don't need to wait till end-of-container is announced.

**Comment by derekriemer** [comment]
2017 web fix?

**Comment by jcsteh** [comment]
It's a common request, so I'll include it in webfix for now, but I think it's lower priority than other webfix issues, not least because there is some controversy surrounding it.
