### ISSUE TITLE
Add mnemonic for OCR settings in Preferences menu

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2599]
**Reported by Brendon22 on 2012-08-17 02:36**
In The NVDA Preferences Dialog, after every option there is a letter to jump to each itom. Like D M K.
But the Ocr Settings doesn't have any letter after it to jump to it quickly?
This sounds a little strange when every other itom has a letter and this itom doesn't?

**Comment by bhavyashah** [comment]
I am pretty sure I had reported this same thing at one point in time, and @jcsteh had told me that this was known, but a new OCR add-on release simply for this minor improvement would be meaningless. I might havve reported this on the NVDA-Devel list, but in case this was on the Trac issue tracker, please close either as a duplicate.

**Comment by Adriani90** [comment]
I think this is obsolete with the new settings dialog. @jcsteh should this issue be closed?

**Comment by jcsteh** [comment]
Note that this is about the old (Tesseract based) OCR add-on, not the builtin Windows 10 OCR functionality. However, if we did release a new version of the add-on, we'd probably want to integrate it into the new Settings dialog too. So yes, I think this is now irrelevant.
