### ISSUE TITLE
Firefox and NVDA only: Image buttons read incorrectly

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2601]
**Reported by HFP on 2012-08-17 15:55**
It seems that NVDA favors the value of the image button over the alt text in Firefox 14 only.  This is different from JAWS since it always favors the alt attribute.  NVDA reads the alt attribute when using IE 8.

Below is a snippet of code showing the value and alt text of the image button:

<input name="EDIT" src="images/Edit.gif" value="0" tabindex="22" onclick="this.form.selectedContactIndex.value=this.value" class="edit-page" alt="Edit Contact Person Information" type="image"> 

For example, NVDA reads "0" for this button instead of the alt text of "Edit Contact Person Information"

**Comment by dkager** [comment]
Closing as fixed based on the status of [the Mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=786163). Please reopen if I'm too hasty (and resurrect the code sample mentioned).
