### ISSUE TITLE
using braille routing keys to move sliders

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2609]
**Reported by dave090679 on 2012-08-20 16:41**
this global plugin re-assigns the routing keys of a braille display to make it possible to quickly move a slider.
usage:
1. place the system focus on a slider e.g. a volume control in sndvol32
2. press any routing key to move the slider to the corresponding position e.g. when you press the first routing key, the slider will move to 0%, when you press the last routing key the slider will move to 100% etc.

todo:
I Send the tbm_setpos and tbm_setposnotify messages to the trackbar objects to move the sliders. unfortunatelly, the tbm_setposnotify message is not supported in xp so you have to use any arrow keys of page up/down to apply the new slider position correctly. I didn't find any workarround for this yet. the tbm_setposnotify message is only supported in windows 7 and above:-(.

**Comment by leonardder** [comment]
@dave090679: assuming you are the initial author of this ticket, it might be best to publish your plugin as an add-on, in case we will close this. I think it is nice functionality, but not a fit to NVDA core. Routing is meant for routing in the first place.

**Comment by jcsteh** [comment]
It's probably a valid feature request; routing keys don't serve any other useful function in sliders, so they may as well do something. However, it won't work on quite a lot of sliders, including any sliders on the web, since there's no way to programmatically set those from NVDA. Marking as feature.

**Comment by dkager** [comment]
The granularity is another consideration. Most braille display sizes don't map well to a 100% scale, e.g. with 40 cells you get 2.5% steps so rounding will occur. With 14, 32 or 88 it's also quite interesting. Plus, the usefulness of this feature depends on your braille display size. All of that muddles the UX a bit I think.

**Comment by jcsteh** [comment]
In light of @dkager's comment concerning questionable UX, closing as wo't fix. Of course, this doesn't prevent this from being published as an add-on. :)
