### ISSUE TITLE
Unable to tick answers to questions in a Word document given to me by an agency

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2614]
**Reported by Brendon22 on 2012-08-21 23:43**
Hello,
I was given a word document with some tables in it by an agency. But NVDA will just say blank. I have confirmed with a sited person that there are tables in this document. I atach this document for you to look at please.

**Comment by bhavyashah** [comment]
@michaelDCurran According to https://github.com/nvaccess/nvda/issues/2614#issuecomment-155300088, should this ticket be closed as a cantfix? @ehollig

**Comment by ehollig** [comment]
Closing as cantfix as stated above by @michaelDCurran
