### ISSUE TITLE
Problem with the new google groups layoud and firefox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2615]
**Reported by nikosdemetriou on 2012-08-22 08:22**
Hello.
When browsing google groups with firefox nvda repports a lot clear cash buttons and edit areas and the experience is not very pleasant. 
With internet explorer this problem doesn't exist but it has got other problems like not being able to activate buttons, replying etc.
You can have a look at http://groups.google.com/group/eyes-free/topics
I am using firefox 14 and internet explorer 8 under windows xp.

**Comment by bhavyashah** [comment]
@jcsteh This issue has more to do with certain Mozilla Firefox bugs as opposed to general NVDA deficiencies with the web or Google Groups. If my understanding is correct, could you please update us about the present status or progress made on relevant Mozilla bugs?

**Comment by jcsteh** [comment]
#1354 causes the content of these buttons (including the hidden input field) to be overridden by the label/title. In practical terms, this means this issue is fixed.
