### ISSUE TITLE
NVDA makes always a beep in Poedit

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2619]
**Reported by drein on 2012-08-24 08:30**
On my system, Windows7 64 bit, with the snapshot 4572, any times I use arrow keys to move up and down between the lines in Poedit, NVDa makes a beep as if the line contains a string to be translated, but instead it is ok. All lines makes a beep.
I tried to uninstall NVDA, remove the folder that contains user configuration, reinstall  NVDA, change the poedit version, now is the 1.5.2, but nothgin is changed.
Here is the information from the viewLog:

Developer info for navigator object:
name: u'\*  and currently loaded module is %s'
role: ROLE_LISTITEM
states: STATE_FOCUSABLE, STATE_SELECTABLE, STATE_FOCUSED, STATE_SELECTED
Python object: <appModules.poedit.PoeditListItem object at 0x05AED3D0>
Python class mro: (<class 'appModules.poedit.PoeditListItem'>, <class 'NVDAObjects.IAccessible.sysListView32.ListItem'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (222, 318, 753, 17)
value: u"Traduzione: e il modulo caricato e' %s"
appModule: <'poedit' (appName u'poedit', process ID 1864) at address 5bba5d0>
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 3213124
windowClassName: u'SysListView32'
windowControlID: 100
windowStyle: 1377898573
windowThreadID: 11292
windowText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0xa6d7eb8 at 5ba4300>
IAccessibleChildID: 1
IAccessible event parameters: windowHandle=3213124, objectID=-4, childID=1
IAccessible accRole: ROLE_SYSTEM_LISTITEM
IAccessible accState: STATE_SYSTEM_SELECTABLE, STATE_SYSTEM_SELECTED, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (3145734)

**Comment by bhavyashah** [comment]
Can Poedit users please test and update us about the current standing of this issue with the latest stable version of both Poedit and NVDA? CC @k_kolev1985

**Comment by bdorer** [comment]
NVDA isn't able to detect untranslated or fuzzy strings any more. 
Further the comments window isn't there, so the shortcuts mentioned in 
the userguide aren't working any more. This is the case since Poedit 
1.8.5 or so.

Am 09.08.2017 um 19:07 schrieb bhavyashah:

**Comment by zstanecic** [comment]
Hi bernd,

i can even give the report about that.

All shortcuts are not working, so the support in the NVDA itself is broken.

Comment edit box is not accessible anymore to us,

beeps wich indicated the fuzzy or untranslated strings are gone 
somewhere, and the * (star sign) wich indicated the untranslated or 
fuzzy string is gone somewhere.

i.e it’s no longer available.

We need to collaborate with Václav slavík, to fiks this problem.

He is following the github account.

He can give us the recommendation about what should be done on the NVDA 
side.


W dniu 03.09.2017 o 17:31, Bernd Dorer pisze:

**Comment by Adriani90** [comment]
@ehollig what are your thoughts? In my view we can close this issue because it is not reproducible anymore in the last poedit version. Tested with poedit 1.9.

**Comment by Adriani90** [comment]
@zstanecic, the comment boy is accessible with object navigation. at least for me it works on Windows 10 with NVDA 2018.3.2.

**Comment by ehollig** [comment]
I will close this for now, as it sounds as if it is now working in 1.9. If this is still an issue, we can reopen.
