### ISSUE TITLE
when typing in an address in firefox, the phrase selection removed gets spoken again and again

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2623]
**Reported by hyperactive on 2012-08-28 05:07**
Hi.
When you start typing into the location bar on firefox 14.0.1, I keep hearing the phrase "selection removed".  I guess this is the autocomplete function kicking in and messing things up.
Can this be fixed?
Cheers.

**Comment by bhavyashah** [comment]
It may be worth noting that NVDA now says 'selected instead' instead. Also, @jcsteh stated quite clearly that there is little to nothing that we can change to improve this situation without losing functionality. Time to close? @ehollig

**Comment by ehollig** [comment]
Unfortunately, as stated in https://github.com/nvaccess/nvda/issues/2623#issuecomment-155300155, there is little to nothing that we can change to improve this situation without losing functionality. There is a workaround, however, stated in https://github.com/nvaccess/nvda/issues/2623#issuecomment-155300156. Closing, but would be happy to reopen if someone would want to address this specific case.
