### ISSUE TITLE
IE8 speaking language and input details every time its run

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2627]
**Reported by briang1 on 2012-08-30 06:08**
Since the merge of input methods, IE8 when running in XP seems to be  speaking information other than what is required. However it does not always manage to speak it all, even though it appears in the log, as it gets truncated by other strings from the browser. Thus to see what is actually going on I've put a small section of the log in this text as below.

IO - inputCore.InputManager.executeGesture (06:59:03):
Input: kb(desktop):enter
WARNING - stdout (06:59:05):
stringCode 00000000, input method name None
WARNING - stdout (06:59:05):
stringCode 00000809, input method name United Kingdom
IO - speech.speak (06:59:05):
Speaking [('en_UK'), u'English (United Kingdom) - United Kingdom'](LangChangeCommand)
IO - speech.speak (06:59:05):
Speaking [('en_UK'), u'Native input'](LangChangeCommand)
DEBUGWARNING - watchdog._watcher (06:59:06):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 155, in <module>
  File "core.pyc", line 339, in main
  File "wx_core.pyc", line 8010, in MainLoop
  File "wx_core.pyc", line 7306, in MainLoop
  File "core.pyc", line 316, in Notify
  File "IAccessibleHandler.pyc", line 837, in pumpAll
  File "IAccessibleHandler.pyc", line 585, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 504, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 38, in getNVDAObjectFromEvent
  File "IAccessibleHandler.pyc", line 333, in accessibleObjectFromEvent
  File "oleacc.pyc", line 240, in AccessibleObjectFromEvent

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (06:59:06):
oleacc.AccessibleObjectFromEvent with window 394362, objectID -4 and childID 0: 
IO - speech.speak (06:59:06):
Speaking [('en_UK'), u'Windows Internet Explorer'](LangChangeCommand)

This does not occur on links, only if the link is a fresh launch of IE. as no swithing of input methods is going on here, the strings being spoken seem pointless.

**Comment by dkager** [comment]
This sounds like a specific case of #7383. Also, it mentions IE8, which is obsolete.
@leonardder @jcsteh Would you agree with closing?

**Comment by Brian1Gaff** [comment]
Remember that if running XP you only have that version of IE to use, most of us would suggest using something else than IE 8 as so many web sites now actually actively won't let you on the site with it.
 
Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
This message sent from a Windows XP machine!
  ----- Original Message -----

**Comment by Brian1Gaff** [comment]
PS the next snaps seem not to do this in IE8 for me here.
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
This message sent from a Windows XP machine!
  ----- Original Message -----

**Comment by leonardder** [comment]
When this is indeed XP specific, I'd say let's close. This is not live threatening at all, even though annoying.

**Comment by dkager** [comment]
This is not specific to XP. However, it is also not specific to one program, e.g. I usually get this when starting Skype 7. That's why I was thinking about closing and further discussing in #7383.

**Comment by bhavyashah** [comment]
In conclusion, do we all agree to close this in order to consolidate discussion in #7383?

**Comment by dkager** [comment]
> In conclusion, do we all agree to close this in order to consolidate discussion in #7383?

I don't know if we all agree, but sounds good to me.
