### ISSUE TITLE
Dynamic file version for launcher

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2632]
**Reported by elliott94 on 2012-08-31 15:31**
This isn't a big issue; it's just something that I was considering when looking at a downloaded launcher earlier.

Would it be possible to automatically change the file version of the launcher based on either the stable version, or the unstable snapshot revision? I just feel this is more descriptive than 0.0.0.0 - although, I doubt many users see this information.

**Comment by jcsteh** [comment]
Superseded by #6204.
