### ISSUE TITLE
No cursor speech feadback in some text fields in Internet Explorer 9

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2659]
**Reported by k_kolev1985 on 2012-09-09 11:01**
I've noticed that in some text fields on web pages, while using Internet Explorer 9.0, NVDA doesn't report the character on witch the text cursor is located, neither it reports the deleted character when pressing "backspace". 

But this doesn't happen in all text fields on web pages in Internet Explorer. So far I've noticed it happening on the NVDA website, in section "Development -> Create a new ticket". The 2 problematic fields are "Summary" and "Description", as far as I noticed.

Steps to reproduce:
1. Go to the NVDA website -> Development -> Issue Tracker -> create a new ticket.
2. Type some text in the "Summary" or in the "Description" fields, by switching to "focus mode".
3. Press "backspace" to delete a character or press left/right arrow keys to move character by character in the text field.
Expected result: NVDA should speak the deleted or focused characters.
Actual result: NVDA doesn't speak anything.

I can provide you with the log file of NVDA, if necessary.

P.S.: The issue occurs with both NVDA 2012.2.1 and the latest snapshot (r5429).

**Comment by ehollig** [comment]
Duplicate of #1909
