### ISSUE TITLE
Mouse tracking broken for Internet Explorer 9

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2660]
**Reported by k_kolev1985 on 2012-09-09 11:51**
It seams that the mouse tracking in Internet Explorer 9.0 is broken. It doesn't obey the "tracking resolution" setting. Also, it may skip reading some of the elements on the screen.

Steps to reproduce:
1. Go to the NVDA website, using Internet Explorer 9.0.
2. Enable "mouse tracking" and set a preferred text resolution (e.g. "word").
3. Start moving the mouse over the objects on the page (paragraphs, links, headings).
Expected result: NVDA should read all elements and obey the "text resolution" setting and therefore - read the text word by word (if you've set the option to "word").
Actual result: NVDA doesn't obey the "text resolution" settings and reads by paragraphs; It also skip the reading of some elements (e.g. for me, it skips reading the headings on the page).

Actually, there's more to it: it seams that the mouse tracking is inaccurate: I point the mouse cursor over the heading "Video: NVDA on ABC TV's New Inventors" on the main page, but NVDA reports the embedded object below it. I've noticed similar behavior from NVDA in Google Chrome some time ago (when I was using that browser), but I seam to recall that it was working in Internet Explorer, as it works in Firefox. But I don't use Internet Explorer as my default browser and can't tell when this got broken (if it was working at all that is).

The test is mainly done with latest NVDA snapshot (main r5429). I've tested it with v2012.2.1 as well and there the situation seams to be a little better - accuracy is better. But there it reports all elements (links, headings, paragraphs, etc.) as "edit" controls. But the "text resolution" setting is again ignored. When navigating with the keyboard, NVDA behaves as it should.

**Comment by bhavyashah** [comment]
#3494 seems to have been fixed in NVDA version 2014.4. If this is indeed the case, I suggest closing this ticket as fixed.
