### ISSUE TITLE
Sapi 4 Error Loading Voice

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2663]
**Reported by levilibegas on 2012-09-11 11:01**
Good morning.
When I try to load certain Scansoft Sapi 4 voices there sounds a beep and does not load the apropiate voice. I am Using the very last development Snapshots 5447 I guess. I have Windows XP SP3.
Thanks a lot in advance.

**Comment by bhavyashah** [comment]
Since we have no means of contacting the original author, @brian1gaff and others were unable to reproduce the reported issue with a few SAPI 4  synthesizers, and SAPI 4 is fading into obscurity, I suggest closing this ticket. @ehollig

**Comment by ehollig** [comment]
Closing, as @Brian1Gaff was not able to replicate the issue in https://github.com/nvaccess/nvda/issues/2663#issuecomment-155300574, and we do not have a way in contacting the original author for further clarification.
