### ISSUE TITLE
Braille it not refresh in windows explorer when you add characters  after the last character.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2666]
**Reported by aleskis on 2012-09-11 15:32**
To reproduce:
1. Go on a file and press F2 to rename it.
2. Place the cursor after the last character of file extension.
3. Enter a new character. It doesn't appear in braille, before you move arrow key or click on a routin cursor.

**Comment by dkager** [comment]
Works for me on Windows 10. There are cases where braille doesn't always pan correctly, but this doesn't seem to be one of them anymore.
