### ISSUE TITLE
Copying an HTML table

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2671]
**Reported by DavePower on 2012-09-13 22:23**
When in the browser mode, it would be highly desirable to be able to copy the current object [list, heading level](table,) to the standard windows paste buffer.  This buffer could then be copied into word for subsequent editing.

This is particularly a problem as windows Internet Explorer does not provide any keyboard shortcuts to copy part of a web page.  Eg a table on a web page without copying the entire web page contents.

This option would provide equivalent features to what a sighted person can do using a mouse.

**Comment by bhavyashah** [comment]
I fully concur with this feature request, because retaining formatting such as well as hyperlinking, table layouts and other aesthetics seems to be all the more important in a professional setting. Anyways, please change the label of this ticket from enhancement to feature. @feerrenrut @ehollig

**Comment by leonardder** [comment]
I think we should treat this as a duplicate of #5354, which is broader in scope. Thoughts?

**Comment by ehollig** [comment]
I agree with @leonardder. Do I close this as duplicate, put block label on this or that one, or what exactly?

**Comment by leonardder** [comment]
There is some github magic that automatically marks this as a duplicate of a ticket if you say something like: "closing as duplicate of #5354." It does not add the duplicate label though, and I'm afraid that it doesn't work if the ticket is already closed.
