### ISSUE TITLE
Symbols change their dots when the cursor is over them

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2674]
**Reported by drein on 2012-09-17 07:32**
I have this problem with the italian 8 dots table, but I changed the table to English and the problem is the same, but with different dots, so I explain with italian 8 dots for now.
I open an editor, notepad++, and start writing.
If a press the "#" symbol, I read it correctly if the cursor isn't over the character. If the cursor is over it, instead of reading the dots 3456, I can touch the dots 467. If I press right arrow, the # returns ok.
But the best is with the numbers!
Suppose you write, 123456.
If the cursor is not over one of the 6 digits, I read ok.
If the cursor is over one of the 6 digits, instead of reading:
dots 16, 126, 146, 1456, 156 and 1246, I read dots  16, 128, 138, 1456, 156, 1246.
Could you please confirm this strange issue?
Thank you.

**Comment by ehollig** [comment]
Sounds like from https://github.com/nvaccess/nvda/issues/2674#issuecomment-155300650 that @jcsteh's suggestion in https://github.com/nvaccess/nvda/issues/2674#issuecomment-155300647 fixed the issue.
Closing as worksforme, but please let me know if I have misunderstood the issue.
