### ISSUE TITLE
NVDA on IE: upload file (editable button ...)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2677]
**Reported by surfer0627 on 2012-09-19 07:17**
Hello NVDA developers,
  I selected the option "Automatic focus mode for caret movement" before uploading files.

While moving caret to the upload file button, NVDA changed from brose mode to focus mode.

But if I pressed "b" to move to the button, it would be ok (on brose mode).

P.S.: In the brose mode, users could press "space" to open the upload dialog.

Please help to solve the case.
Thank you so much.

**Comment by ehollig** [comment]
This still occurs using IE 11.
Relevant code:
``<input type=file accept=binary>
Ensure Automatic focus mode for caret movement check box is checked. CC @jcsteh @feerrenrut

**Comment by feerrenrut** [comment]
I think I can reproduce this with IE Version: `11.540.15063.0` and NVDA version `master-14289,6c85ce59` but I'm not 100% sure.
@ehollig could you please elaborate on the steps to reproduce and clarified what the actual vs expected behaviour was for this?

**Comment by ehollig** [comment]
## StR
1. Ensure Automatic focus mode for caret movement is checked in Browse mode settings
2. Open the attachment in IE 11
3. Press down arrow
### Expected Result
NVDA says "buttonBrowse…" in browse mode and the button is clickable
### Actual Result
NVDA says "buttonBrowse…" in focus mode. Item is not clickable.
[test.html.txt](https://github.com/nvaccess/nvda/files/1222549/test.html.txt)

**Comment by feerrenrut** [comment]
When you say that the item is not clickable, do you mean its not reported as clickable, but you can press enter to press the button? If so, how did you try to "click" the button.

**Comment by ehollig** [comment]
I should have specified. When I meant clickable, I meant the ability to press enter and for the browse dialog to pop up.

**Comment by Adriani90** [comment]
@feerrenrut, any updates on this issue?

**Comment by Adriani90** [comment]
IE support has ended completely in 2022 and the browser is being removed automatically from machines that still have it after an Edge update in February 2023. I am closing this issue as abandoned, since I don't expect any further accessibility updates to IE or to IE mode in Edge. If you are having this issue in other browsers, please open a new issue with updated steps to reproduce and a minimal test case.
