### ISSUE TITLE
Support to reloadplugin and check sleep mode for an application using controller client

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2690]
**Reported by ovjforu on 2012-09-28 16:09**
Hi,

I am submitting changes to add support for below two functionality in controller client.
1) To reload plugins when requested.
2) To check sleep mode status for a given application.

I have attached a zip file containing original files and one diff file. 
Modified Files
1) nvdaController.c
2) nvdaController.idl
3) nvdaControllerClient.def
4) NVDAHelper.py
5) nvdaHelperLocal.def
6) speech.py

I have also attached the test code to test the functionality ( testRoutineForControllerClient.py)

Please let me know if you need more information. My contact details (ovjforu@gmail.com)

Thank you and have a great day.

**Comment by bhavyashah** [comment]
@jcsteh @michaelDCurran Do the usage cases provided in https://github.com/nvaccess/nvda/issues/2690#issuecomment-155300813 suffice?

**Comment by jcsteh** [comment]
We really need practical use cases here, not theoretical ones. For example, why does your external application need to do these things? What is it actually trying to achieve from a user perspective?

Closing given the age of the issue and the fact that we can't contact the reporter any more.
