### ISSUE TITLE
Create snapshot branch built with svn espeak/liblouis

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2696]
**Reported by jteh on 2012-10-01 03:54**
NVDA generally is (and should) be built with stable espeak and liblouis. However, it's useful for non-devs to be able to test upstream espeak/liblouis changes and should hopefully help to catch regressions sooner.

To do:
1. Create mainUnstableDeps branch.
2. Update nvda_autobuild to handle per-branch deps directories and add mainUnstableDeps with its own deps dir.
3. Create script to update espeak and liblouis from svn for mainUnstableDeps.
4. Continuously merge espeakNext (and eventually liblouisNext) into mainUnstableDeps. Periodically merge main into mainUnstableDeps.

**Comment by leonardder** [comment]
CC @FeerRenrut:

It seems that it is the plan to move next to Espeak-NG master on a regular basis. Should we still consider this additional snapshots? Would people ever need them?

**Comment by dkager** [comment]
In light of #6733 I would say that yes, people would use this. However, table changes in liblouis require some manual work. So I'm not sure about the maintenance burden.

**Comment by jcsteh** [comment]
I forgot about this issue. :) We decided to have NVDA next update to eSpeak master on a semi-regular (but not automated) basis. We could probably do the same for liblouis. People who wanted to test specific tables in liblouis master would need to file an issue to do this, but we'd only consider this if there were a commitment to test the table and fix any problems.

**Comment by dkager** [comment]
Is this issue then resolved and ready to close, or do you first want to document the procedure to request a snapshot (AKA next)?

**Comment by ehollig** [comment]
@leonardder @jcsteh @dkager I do not believe a resolution was made for this issue from https://github.com/nvaccess/nvda/issues/2696#issuecomment-315699534

**Comment by dkager** [comment]
With liblouis we have to watch out for API changes that happen on master. While it is usually just opcode changes, e.g. when the big UEB update was going on, it could also be that the Python wrapper changes and breaks the snapshot builds.

So if the process remains manual then who does it and when?

**Comment by Adriani90** [comment]
Is this actually not working when pushing try builds? Actually the try builds could fetch unstable branches of eSpeak and Liblouis. Or am I wrong?

**Comment by feerrenrut** [comment]
I think we can close this issue. There aren't any current plans to create automatic builds with the HEAD of espeak or liblouis repositories.

**Comment by josephsl** [comment]
Hi, for Espeak and liblouis, one must update dependencies before generating try builds or pull request builds. Thanks.
