### ISSUE TITLE
Routing navigator object to mouse pointer misbehaves when mouse tracking is disabled

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2702]
**Reported by Ahiiron on 2012-10-07 22:46**
(Reported on behalf of another user.)

Win7 x64

Steps to reproduce:
1. Launch Firefox. 
2. Make sure Firefox window is maximized.
3. Move the mouse pointer over any item in Firefox window.
4. Press "NVDA + Numpad *" to route navigator object to mouse pointer.

Desired result:
NVDA focus should move to where the mouse pointer is. You should be able to navigate the area using review cursor. 

Actual result:

Instead, the navigator object is routed to the item behind Firefox window. If its a desktop it would start announcing desktop items, for example. 

Notes: Doesn't occur all the time, but enough to be annoying/worth filing.

**Comment by Adriani90** [comment]
@Jarekczek do you have an update on this? Have you tried to fix this meanwhile?

**Comment by Adriani90** [comment]
This seems fixed in Firefox 128 with NVDA 2024.2. I am closing as works for me. if you are still having this issue, please comment and we can reopen.
