### ISSUE TITLE
Row and Column Headers in IBM Lotus Symphony

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2708]
**Reported by ateu on 2012-10-12 15:27**
As well as it's now possible to configure it in Microsoft Excel, i'd like to see this feature implemented in IBM Lothus Symphony.
Most likely in 2013, Openoffice will migrate its APIs to IAccessible, by mergging code from IBM. This will give us an oportunity to have an accessible and powerful office suite.
So I'd really like to see the accessibility level found in this suite be compared to Microsoft Office.

Thank you for your great work.

**Comment by Adriani90** [comment]
Lotus symphony has been discontinued since years now. I am closing this as abandoned. Please open a new issue for open office and alike with exact steps to reproduce and the results you get and expect. Thanks.
