### ISSUE TITLE
Sysinternals DBGView is slow to respond when NVDA is running under xp

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2713]
**Reported by tspivey on 2012-10-13 04:09**
STR:
1. Launch DebugView (dbgview.exe).
If the window appears at all, navigating around is really slow (sometimes can take a minute or so to get any results).

Deleting this line out of nvdaHelper/remote/IA2Support.cpp seems to fix it, though there's probably a better fix:

```
LOG_DEBUGWARNING(L"Error registering class object, code "<<res);
```

Which was the one error I saw quite a bit.

I'm assuming that the remote part of nvdaHelper gets injected into all processes, and dbgview isn't expecting itself to call OutputDebugString. I haven't seen this break on win8, though.

**Comment by ehollig** [comment]
@tspivey is this still an issue?

**Comment by tspivey** [comment]
This seems to work on Windows 10.

However, NVDA still outputs here, but so do a lot of other things now.

**Comment by ehollig** [comment]
XP issues are not being addressed anymore. Closing
