### ISSUE TITLE
NVDA doesn't want to be updated... but sometimes agrees

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2723]
**Reported by PZajda on 2012-10-15 09:25**
Hello,

When I check for update for NVDA and click the button to download and install it, sometimes it works, but last days I have an error on 4 out of 5 attempts to update.

This is the error I have:
DEBUGWARNING - updateCheck.UpdateDownloader._bg (11:16:38):
Error downloading http://nvda.sourceforge.net/snapshots/main/nvda_snapshot_main-5547.exe
Traceback (most recent call last):
  File "updateCheck.pyc", line 277, in _bg
  File "updateCheck.pyc", line 314, in _download
  File "socket.pyc", line 380, in read
error: [10035](Errno) Une opération non bloquante sur un socket n'a pas pu être achevée immédiatement

What could be the cause?
Everything else which is connected work well, I have only error when trying to download updates for NVDA.

**Comment by dkager** [comment]
The mentioned [Python issue](https://bugs.python.org/issue9090) is fixed in Python 2.7.
