### ISSUE TITLE
NVDA will not read the Windows XP Security screen

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2728]
**Reported by krussell on 2012-10-18 10:17**
I've just installed NVDA on my Windows XP machine with JAWS as the default screen reader.

After installing NVDA, I went into the General option of Preferences and unchecked the Automatically start NVDA after I log on option.

However, when I shut down NVDA and go back to JAWS, I discovered that when I went into the Windows security screen, NVDA would speak as well.

I then went back into the General option of Preferences in NVDA and 
unchecked the Use NVDA on the log on screen option.

However, when I go back to JAWS and try and use the Windows security 
screen, it won't speak.  In fact, everything stops talking until I hit the Escape key to come out of the Security screen.

The only way to fix this is to recheck the Use NVDA on the log on screen option and reboot the machine.

I wonder if NVDA is intercepting the video driver in some way.  I do have adnin rights on the PC.

I uninstalled NVDA, rebooted the PC but accessing the security screen was still broken.

I ran the JAWS repair option from the JAWS installer and that fixed it.

I also use Window-Eyes and had to reinstall it as accessing the security screen was broken as well.

Is this a known issue.

**Comment by bhavyashah** [comment]
CC @jcsteh @brian1gaff

**Comment by ehollig** [comment]
This is an interesting issue. However, we are unable to contact the original poster for more information. Closing, as XP specific issues are not being addressed anymore.
