### ISSUE TITLE
Japanese input method is not reported correctly

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2730]
**Reported by nishimotz on 2012-10-19 07:24**
Japanese input method is reported as follows:

Example:
Three syllabic (kana) characters (transliterated from Latin 'k a w a n o') 

```
'ka' (0x304B)
'wa' (0x308F)
'no' (0x306E)
```

are translated into three (ideographic and syllabic) characters:

```
'kawa (river)' (0x5DDD)
'no' (0x306E)
```

```
typed character: reported message

k: k
a: ka
w: w
a: wa
n: n
o: no
space: ka wa
```

When the space is pressed, first candidate 'kawa no' is shown (without opening candidate window), so it should be reported using character descriptions.

It also should include the last (syllabic) character 'no'.
- operating system: Windows 7 SP1 Japanese
- input method: Microsoft IME (Roman input mode)
- application: Notepad

**Comment by bhavyashah** [comment]
@michaelDCurran Since you were assessing the reported issue earlier, could you please share any thoughts/inputs you may have in response to @nishimotz's https://github.com/nvaccess/nvda/issues/2730#issuecomment-155301139?

**Comment by nishimotz** [comment]
Let me continue the discussion of #8621 regarding Japanese IME here.

The first candidate issue is still open for Japanese as well, however, it is different from Chinese.
Candidates window of Japanese IME is not shown during the type of Latin characters.
Windows 10 can show the prediction window during the type, but usually it is not expected to be announced.

When the space key is pressed, first candidate is shown, without candidate window.
At the second press of space key, candidate window pops up and the second candidate is focused.
As the result, first candidate is not announced as character description.

**Comment by larry801** [comment]
Auto focus means announce the prediction window under Windows 10. Am I right?
@nishimotz

**Comment by larry801** [comment]
As far as I have seen, the first candidate in Japanese IME after pressing space is treated as a reading string. That is why the first candidate is not announced as character description.

**Comment by josephsl** [comment]
Hi,
Six years later...

Updates please, especially with Windows 11 modern IME support.

Thanks.

**Comment by Adriani90** [comment]
No updates from the initial author since many years upon request, I am closing as abandoned. If you are still having this issue, please comment and we can reopen.
