### ISSUE TITLE
windows mobile device center is unaccessible with Nvda

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2735]
**Reported by mayson on 2012-10-21 05:05**
Hello, my name is Mayson. I have an ishue to report with nvda with wmdc. when starting wmdc, nvda will not read the buttons that are used with the program. when I try to connect my Braillenote apex, I nvda will not read the buttons. thus, I can not get to the set up a partnership button or, connect with out setting up your device button. can you please address this ishue?

**Comment by dkager** [comment]
@jcsteh Wontfix? The software is old and was meant for Windows Vista only - [source](https://support.microsoft.com/en-us/help/931937/description-of-windows-mobile-device-center). Notetaker users may depend on WMDC, but then we are quite late with adding support. :)

**Comment by josephsl** [comment]
Hi, I have received reports that this doesn’t even work on latest Windows 10 builds, so I’d say let’s close this.
