### ISSUE TITLE
Start menu doesn't read at all

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2739]
**Reported by driemer.riemer@... on 2012-10-21 22:41**

**Comment by dkager** [comment]
No further information from reporter.
CC @derekriemer

**Comment by derekriemer** [comment]
That was me. I was young and ignorant and saw the explorer appModule in core, and thought wth, why are these here but not used, so I threw it in my appModules folder not realizing it was actually built in at the time.
