### ISSUE TITLE
Possibility of translating OcR addon

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2744]
**Reported by nvdakor on 2012-10-25 01:31**
Would it be possible to translate NvDA OcR addon for languages other than English? Thanks.

**Comment by bhavyashah** [comment]
CC @josephsl and @jcsteh to kindly request further discussion on getting the OCR add-on part of NVDA's automated translation system, assuming that it isn't already.

**Comment by josephsl** [comment]
Hi, now that Windows 10 OCR is here, discussion should focus on allowing those not using Windows 10 to reap the benefits of translating this add-on at a later time. I suggest delaying this until the old OCR add-on is updated to support the new content recognition framework, which should also give us an opportunity to improve the add-on in many ways. Thanks.

**Comment by leonardder** [comment]
Honestly, I belief it would be best to move issues regarding de OCR add-on to [its repository](https://github.com/nvaccess/nvda-ocr) on Github.

**Comment by ehollig** [comment]
Closing. See [NVAccess/NVDA-OCR/#4](https://github.com/nvaccess/nvda-ocr/issues/4)
