### ISSUE TITLE
In Windows 8, some programs such as Outlook, Skype and others crash while using NVDA for a while

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2746]
**Reported by nvdakor on 2012-10-25 22:59**
When using Microsoft Outlook 2007 on either Windows 7 or Windows 8, after using it for a while, Outlook stops responding and the following is recorded in NvDA log:

DEBUGWARNING - NVDAObjects.window.ContentGenericClient._get_displayText (15:53:31):
appModule has no binding handle
IO - speech.speak (15:53:31):
Speaking [- Microsoft Outlook (Not Responding)'](u'Inbox)

This occurs whenever Outlook is run and has been used for at least five minutes. Usually solved by restarting Outlook. Thanks.

**Comment by jcsteh** [comment]
The Skype issue is #2712 and was fixed in Skype. I'm not aware of any outstanding Windows 8 specific freezes in third party apps. Outlook 2007 crashes are covered in other issues. Closing.
