### ISSUE TITLE
Activating buttons that do not have one default action

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#275]
**Reported by vtsaran on 2009-02-16 21:39**
In its current implementation NVDA always executes a single left-click on an focusable element when a SPACE or an ENTER key is pressed.
This is not always desirable as there may be some elements on the page, e.g. split buttons, that are capable of performing more than one action. With such buttons, ENTER key may drop down a menu while SPACE bar may execute a default click. A good example of such buttons can be found inside Yahoo! Mail Classic.

Repro steps:
1. Log into Yahoo! Mail and make sure that you are viewing the "classic version".
2. Pick one of the messages in your INBOX folder (or any other folder, for that matter) and open it.
3. Scroll down to the "Reply" button and press ENTER.
This button is designed to drop down a submenu with options such as "Reply to sender" and "Reply to all". NVDA, however, will execute default action, which is "Reply to sender" and take you to the message composition screen.
You can test to see that ENTER key does in fact drop down the submenu, described above, by bypassing ENTER key on a "Reply" button with INSERT+F2./

**Comment by leonardder** [comment]
@JCSTeh: Is this part of webfix?

**Comment by jcsteh** [comment]
I don't think so, since it doesn't appear to be affecting users in the wild. Moreover, I don't see a way to fix this which won't break cases where a button doesn't implement key handling as the user expects. Closing as won't fix, but if there are solid use cases for this in the wild, happy to discuss.
