### ISSUE TITLE
in a Windows 8 Data grid, only the first column is announced.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2752]
**Reported by pitermach on 2012-10-26 21:37**
In the task manager, when you access the more details view, most of the tabs, except details, use a data grid to display information which seems to have multiple columns EG memory and CPU usage, username, etc. NVDA does see them (you can enter the items to look at them), but when navigating with arrow keys doesn't announce them.

**Comment by bhavyashah** [comment]
If I am following this ticket correctly, object navigation is the work-around I employ to access the otherwise inaccessible portions of the Task Manager. Any thoughts/inputs on priorities and implementation anyone?

**Comment by Adriani90** [comment]
this is also reproducible in the task manager in Windows 10. The columns can only be accessed via object navigation, but not with arrow keys.
Testing with NVDA alpha-20097,6a573cd9
cc: @josephsl

**Comment by Adriani90** [comment]
Closing in favor of new issues like #13147 and #14001 which contain more details.
