### ISSUE TITLE
NVDA 2012.2.1 seems to lock-up for Java Access Bridge v2.0.3 on paging

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2753]
**Reported by vsfoote on 2012-10-27 05:31**
Environment:

Windows 7, 64-bit
NVDA 2012.2.1
JRE 1.7u9 (32-bit, with jabswitch /enabled and a JAVA_HOME var set to install directory, and an entry to JAVA_HOME\bin in PATH)
LOdev 3.6 (2012-10-25_19.15.46 build)
LibO 3.5.7
Apache OpenOffice 3.4.1
IBM Symphony 3.0.1

Test document:
NVDA 2012.2.1 User Guide ( C:\Program Files (x86)\NVDA\documentation\en\userGuide.html saved as .ODT text)

This may already be a know NVDA issue as I am a casual user. I did a quick searh of NVDA tickets and found nothing recent. 

I've noticed that with JAB v.2.0.3 of JRE 1.7u9 NVDA would freeze (stop speaking) when paging to next screen of document. For the test document above, it happens with both LibreOffice 3.5.7, LOdev 3.6 and Apache OpenOffice 3.4.1--all dependent on Java Accessibility -- Java Access Bridge mappings of UNO Accessibility roles.

However, it does not happen when viewing the same test document with IBM Symphony 3.0.1.

Strongly suggests that with JAB v2.0.3 there is an issue with Java Accessibility API role mappings being limited to current screen only.  And on move to next page, there is either no precessing of page structure or there is excessive delay/time out of Java Access Bridge rendering of UNO Accessibility.  Either way it seems like NVDA 2012.2.1 is unusable with multi-page documents that in Java Accessibility API based applications. I receive a Windows "NVDA has stopped responding" notice.  Closing the document and the office product releases the hang and NVDA resumes functioning for other apps in the Windows shell. 

Conversely, the IAccessible2 API of the Symphony 3.0.1 writer exhibits no delay, or lockup of NVDA when paging within a document. Not sure if that is simply more responsive that Java JRE, or if the entire document is parsed for exposed accessibility roles and cached for NVDA use.

Don't know if this is a NVDA regression caused by the JAB v.2.0.3 now bundled with JRE > 1.7u6 and NVDA 2012.2.1, or if it has is a known issue also manifested in JAB v2.0.2 and has affected multiple builds of NVDA but not been reported.

Happy to fill requests for any additional debug steps required.

V Stuart Foote
University of Texas at San Antonio
LibreOffice Project QA Volunteer

**Comment by bhavyashah** [comment]
@jcsteh Does this still occur with NVDA 2017.2 and the latest version of Java Access Bridge? Also, in case this proves to be a JAB bug, feel free to add the NeedsExternalFix label.

**Comment by jcsteh** [comment]
No longer relevant because this refers to OpenOffice/LibreOffice with Java Access Bridge and that implementation has since been replaced by IAccessible2. Closing.
