### ISSUE TITLE
In notepad, only first character is announced when moving by word with multi-byte chars such as Asian words (specifically, Korean words)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2754]
**Reported by nvdakor on 2012-10-29 06:52**
In Notepad, when using navigate by word command (either via focus via CTRL+left/right arrow or via review cursor using numpad 4/6), when Asian words (specifically, Korean words) are encountered, NVDA only reads the first character. To demonstrate this behavior, I'm attaching What's New in NvDA file written in Korean. This happens only in Notepad (as far as I'm concerned).

**Comment by Adriani90** [comment]
@josephsl please try to test this also if possible, or maybe ask someone in the translations list to test if this has improved in last NVDA alpha. Thanks.

**Comment by dnz3d4c** [comment]
Hi.
I am part of the Korean translation team.
This issue is still reproducible in the alpha and stable version.
Thank you.

**Comment by Adriani90** [comment]
cc: @khsbory, @ungjinPark, @dnz3d4c how is this now in NVDA 2023.1 Beta or NVDA 2022.4? also cc: @larry801 it might also be relevant for chinese word navigation.
