### ISSUE TITLE
nvda does not report the justification in Jarte

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2755]
**Reported by jmwalton on 2012-10-29 06:58**
in Jarte, when editing text, nvda does not report the justification of the text that is selected.
Step to reproduce.
1. open jarte.
2. type something, and select it all with control a.
3. go to format menu, paragraph menu and set  the text to center.
4. put the cursor on the word you typed and press insert f. NVDA reports the font, size, color but not the justification.

**Comment by leonardder** [comment]
This works for me in version 6.1
