### ISSUE TITLE
Ffirefox won't stay focused.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2764]
**Reported by driemer.riemer@... on 2012-10-31 03:42**
The mozilla firefox application has been recently reporting the title and the virtual buffer is not reading consistantly. The page will read normal for a while and occationally it will say a message like "mozilla firefox " and website title. The browser is still usable but hard to use.F

**Comment by ehollig** [comment]
@derekriemer any updates?

**Comment by derekriemer** [comment]
It was a weird ff issue which has disappeared over the last few years.
