### ISSUE TITLE
Half shape symbols may not be announced within candidate words

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2776]
**Reported by nishimotz on 2012-11-03 06:19**
Japanese language users sometimes type half shape symbols (left paren, right paren, etc.) within input method editor. 
It gives the candidates including full-shape symbols and half-shape symbols, which are corresponding to the typed characters.

When symbol announce level is not 'all', such symbols may not be announced within candidate words.

Setup: Windows 7 sp1 x64 Japanese, NVDA_snapshot_2012.3-5637, Microsoft Speech Platform (Japanese)

Procedure:
- run NVDA as default language (Japanese)
- disable 'Automatically report all available candidates' of Input Composition settings
- set 'Punctuation/symbol level' to 'none'
- open Notepad
- select Microsoft Japanese IME
- enable Japanese conversion
- type left paren, right paren
- press space twice to open the composition window.
- the candidates consist of two items: (1) 'half-shape left paren, half-shape right paren', (2) 'full-shape left paren, full-shape right paren'. If half-shape parens are selected, it is not announced.
- if 'Punctuation/symbol level' is set to 'all', both candidates are announced, but it also contains 'comma' between two symbols.

**Comment by bhavyashah** [comment]
Assuming that this still occurs (@nishimotz?), @michaelDCurran, any thoughts regarding this ticket?

**Comment by Adriani90** [comment]
@nishimotz is this issue still reproducible in NVDA 2020.1 RC1?

**Comment by nishimotz** [comment]
Setup:
* Windows 10 (1909) x64 Japanese
* NVDA 2020.1rc1
* Microsoft OneCore voice (Japanese)
* Microsoft Japanese IME

What happens in this case is the same as what I reported in the beginning.

I will see what happens with the Windows 10 version 2004 modern input method.
If it's a small issue I'll write about it here, but I'll probably write about a more serious situation in issue #10093.

**Comment by josephsl** [comment]
Hi all,

Any updates in 2024? If not (at least in Windows 11), I vote to close this issue (for now).

Thanks.

**Comment by Adriani90** [comment]
No updates since years form the initial author upon request, closing as abandoned. If you are still having this issue, please comment and we can reopen.
