### ISSUE TITLE
Can not control alt down arrow in Thunderbird To field

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2783]
**Reported by ianr on 2012-11-05 17:08**
When writing a new email I used to be able to be in the To field and press control + alt + down arrow to move to the next To field.

This not only moved to the next to field but would create a new one if it did not exist.

Using snapshot 5638 This no longer does anything.

I reverted to NVDA 2012.2.1 and it works as it used to.

Upon further testing I found that alt + down arrow works in snapshot 5638.

So it seems the behavior is not lost but responds to a slightly different keyboard gesture.

I checked NVDA 2012.2.1 and it also responds to alt + down arrow.

Knowing this I can just use alt + down arrow but I thought I'd report it so you are aware of the change anyway.

**Comment by jcsteh** [comment]
It looks like Thunderbird itself no longer supports these commands, so we're not overriding anything here.
