### ISSUE TITLE
Better support for handling compound characters in languages such as Korean and Tamil

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2791]
**Reported by nvdakor on 2012-11-09 09:28**
Hi,
Normally, Unicode assigns one code per character. This works well for Latin-based scripts and similar ones such as English. However, there are languages such as Korean and Tamil that uses characters coposed of compound characters - that is, character components are used to make up a single character. A good example is Korean, where a character is composed of an initial conscenant, vowel and zero, one or two final conscenants.
The support for handling such compound characters would be useful for proofreading scenarios (such as pressing Numpad5 three times to spell the word with character descriptions). As of 2012.3, one of two things occur:
- In languages such as Korean, the character itself is announced again instead of individual char components.
- In languages such as Tamil, only the first part of the char is announced.
  There are scripts out there which allows calculation of Unicode values for chars that make up the components of a single compound character. However, a concern would be whether such cases would apply to just one or more languages, with a potential issue being catching possible test cases when dealing with compound characters due to script differences between various languages (which also involves looking up the base Unicode value for chars in a particular language).
  In the end, the ideal result would be: when a user presses review current character/word command twice or three times to obtain character descriptions, NvDA would announce individual components of a compound character, instead of translators writing tens of thousands of possible compound char combinations in characterDescriptions.dic, which helps with performance as well.
  Thanks.

**Comment by bhavyashah** [comment]
@josephsl As the original author of this ticket, could you please respond to the questions asked in @jcsteh's https://github.com/nvaccess/nvda/issues/2791#issuecomment-155301630?

**Comment by josephsl** [comment]
Hi,
Almost five years later:

* Korean: fixed by adding character components in symbols and char descriptions dictionaries thanks to work from prominent leaders of the Korean NVDA community.
* Tamil: will need to ask on the translations mailing list.

Thanks.

**Comment by Adriani90** [comment]
@josephsl could you please ask in the translation lists about the current behavior in NVDA 2020 Betaß There was PR #10550 which might have improved this.

**Comment by josephsl** [comment]
Hi, probably not at this point unless I’m wrong 9I have moved on from Korean translation at this point, but we can ask translators once 2020.1 is released). Thanks.

**Comment by bhavyashah** [comment]
@josephsl Since NVDA version 2020.1 has been released, this is a is a friendly reminder to reconsider https://github.com/nvaccess/nvda/issues/2791#issuecomment-619384810.

**Comment by josephsl** [comment]
Hi,

In this case, it would be better to let Korean users comment on this, as they can tell us if things have improved.

Thanks.

**Comment by Adriani90** [comment]
@khsbory, @ungjinPark, @dnz3d4c could you please give an update on thi issue as well? how is it working in NVDA 2023.1 Beta?

**Comment by Adriani90** [comment]
Closing this issue as abandoned, no updates from Korean users. For Tamil language, this is already covered in #1428 I think.
