### ISSUE TITLE
Support for Presentation, specifically Writing and Editing Slides in IBM Lotus Symphony

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2794]
**Reported by ateu on 2012-11-12 16:46**
I've tested and I think this task doesn't requires a lot of work.
Currently, it's already possible to perform some tasks:
Some buttons are already accessible using the focus;
It's possible to edit title and subtitle;
Using object navigation, it's possible to access the slide selector, and once done, you can select the slide with arrow keys and also jumping to the selected slide with control+tab. From there, it's possible to edite the slide if accessible.
unfortunately, I can't understand the reazon, several slides are not accessible, and I can't read them, even when I am incide them.
But the slides created and edited by myself, I can switch the slide and read which I selected.
**Blocking #3130**

**Comment by ehollig** [comment]
This sounds specific to IBM Lotus Symphony which development has been discontinued. Closing
