### ISSUE TITLE
suppressing of blank lines when reading online

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2795]
**Reported by kingshand on 2012-11-14 10:44**
Add an option to suppress the saying of blank lines and removing the extra lines when reading a website online. This would make it much faster to navigate a website line by line and would make it smoother to read.

**Comment by ehollig** [comment]
Related issue: #4904

**Comment by bhavyashah** [comment]
There are two features being requested here:
* skipping over a large chunk of blank lines
* suppressing NVDA from saying 'blank' when blank lines are encountered and staying silent instead
The former has already been covered by #4904 and the latter can be taken care of by #2522. Thus, I suggest closing this as a duplicate. @ehollig

**Comment by ehollig** [comment]
Duplicate of #4904
