### ISSUE TITLE
Progressive MS Excel Enhancements

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2801]
**Reported by jhomme on 2012-11-16 17:22**
Hi,
I'd like to see if we can make some progressive enhancements to the column and row reading feature in Excel. 

Store the settings for row and columns on disk in some sort of file. I invision a group of ini files that could be stored in the folder where the Excel module resides. Here's what I see for the format of the file. This would also need to have some reading logic added.
- The name of the ini file reflects the excel file.
- Each section of the ini file represents a sheet within the work book. It would get its name from the sheet name. Note that sheets can be named something other than sheet1, sheet2, and sheet3, and it's possible to have more than three sheatts in an excel file.
- Each key/value pair in a section would reflect the following qualities.
- Whether the value represents a column or a row.
- The address of the cell.

Note, in an excel work sheet, it is possible to have multiple regions. A region is a block with empty cells around it, so NVDA would need to make sure that if someone defines multiple row and column cells for a sheet, that the location of the headers it reads would be above or to the left of the current cell, and that there is a blank row of cells above the column and row locations, if the user wants to hear column and row headers in a second region.

There would also need to be a facility for speaking more than one cell for a row or column. This is because some spreadsheets break row and column information into multiple cells for visual reasons. So, for example, you may want to hear two narrow cells as you move across from left to right. Or you may have an outline that sometimes has two cells of row information on the left, and sometimes one. I invision this reflected in the ini file as an excel range, something like $a1:$a2. This way, it can be directly used by the code, or at least what I understand of how it works.

I will start to work on getting excel files as attachments to suplement this ticket. If you need me to break these out into separate tickets, please tell me. 

I put this under the category of compound documents, because I believe that further enhancements such as indicating whether or not the cell is a formula, or the result of a formula is part of the Excel document object model.

I'de be happy to stand corrected on any of this.

Thanks.

Jim

**Comment by leonardder** [comment]
Most of this seems already been covered. Having settings for work sheets stored on disk is not an appealing idea to me.

**Comment by jcsteh** [comment]
Yes, row/column header reading has been implemented for some time. Closing.
