### ISSUE TITLE
NVDA not read out the options in Kaspersky antivirus

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2803]
**Reported by agateinfotek on 2012-11-17 06:49**
NVDA 2012.1. was working in my Laptop all the time. Suddenly, it stopped working. I tried to install NVDA. The NVDA icon becomes active and the voice comes during start up. I have installed Kasperskey Internet Security 2012 version for virus protection. NVD not read out the options in the Kaspersky Antivirus. I disabled it and checked the NVDA. The same condition prevails. Whereas, NVDA Portable created on USB works fine on this same environment. What could be the solution for this?

**Comment by dkager** [comment]
Looks abandoned and a bit vague (or am I being harsh?).
