### ISSUE TITLE
reader stops at end of sentence

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2811]
**Reported by swondrasch on 2012-11-19 23:58**
The NVDA reader stops at the end of sentence, and will not continue on to next sentence in paragraph despite hovering over it!

**Comment by leonardder** [comment]
This is abandoned and I'm afraid the report is incomplete. E.g. what version of NVDA, how to reproduce? For example, I'd say this is about say all, but I'm just not sure.

Closing as invalid.
