### ISSUE TITLE
Media Player Classic Home Cinema can't be closed correctly if NVDA is running

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2818]
**Reported by k_kolev1985 on 2012-11-21 18:57**
I've recently downloaded a portable copy of a nightly build of "Media Player Classic Home Cinema" from the following link:
http://xhmikosr.1f0.de/mpc-hc/MPC-HC.1.6.5.6238.x86.7z
And I've noticed that if NVDA is running, this application can't be closed correctly - even after executing the "Exit" command from its menu, the "mpc-hc.exe" process stays resident in the memory and I have to terminate it via the "Task Manager".

Steps to reproduce:
1. Launch NVDA.
2. Unpack the downloaded archive and from the unpacked folder, launch the "Media Player Classic Home Cinema" by executing the "mpc-hc.exe" file.
3. From the "File" menu, execute the "Exit" command.
Expected result: "MPC-HC" should close correctly.
Actual result: The "mpc-hc.exe" process remains resident in the RAM memory of the system.
Try doing the steps above without NVDA running (e.g. with "Narrator") - the issue doesn't occur - "MPC-HC" terminates correctly. I think the same happens - no issue - when "MPC-HC" is launched before NVDA is launched, but the "Exit" command is executed with NVDA running.

**Comment by leonardder** [comment]
@k-kolev1985, I can't reproduce this myself. Could you please report whether this is still the case for you?

**Comment by k-kolev1985** [comment]
@leonardder No, I also can no longer reproduce this issue. You may close the ticket.

**Comment by leonardder** [comment]
Thanks a lot! Closing as works for me.
