### ISSUE TITLE
Use gettext natively for add-on manifest localisation

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2819]
**Reported by jteh on 2012-11-22 20:24**
(Spun off #2744#comment:4.)

It seems that add-on manifests are being translated using gettext. Currently, this is implemented in Rui's [add-on template](https://bitbucket.org/nvdaaddonteam/addon-template). Quoting Rui:

> I implemented a way to generate translated manifest files from gettext mo files, so we can avoid most of the encoding problems translators caused (by accident). ...
> 
> manifests have been causing some more trouble to translators, further than encoding (i.g. quotes not close, extra fields added - which cause no harm but they tend to put there), etc). My point (and Mesar's at least) was more of users just using one format so they won't get more confused.

If everyone is going to do this, we should seriously consider replacing the current way we localise manifests with gettext. I realise this will break backwards compatibility and maybe we need to deprecate the old method in one release before we remove it in the next, but there's little point in the current system if no one uses it directly. It's just another layer of indirection.

Thoughts?

**Comment by leonardder** [comment]
@JCSTeh: So, if I understand you correctly, you'd like to get rid of the whole localized manifest system somehow?

**Comment by jcsteh** [comment]
That was the intent, yes. However, add-ons have been using localised manifests for years now, popular add-ons are using the add-on template, the add-on template is required for far more than just this, we don't have any idea how to implement this, and we have far bigger problems to solve. So, closing, at least for the foreseeable future. :)
