### ISSUE TITLE
Nvda completely stops working on some websites.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2821]
**Reported by meerkat on 2012-11-22 23:12**
Nvda stops working completely when I go to certain websites. It freezes causing me to have to restart the application. One example is this link to an article on a website. 

 http://tinybuddha.com/blog/20-things-to-do-when-youre-feeling-angry-with-someone/

**Comment by dkager** [comment]
Amazingly, this webpage still exists. However, it does not lock up for me with NVDA 2017.2 and IE11 or Firefox 54.0.1.

**Comment by Brian1Gaff** [comment]
No still does not cause a problem here. It was either a fault in the page 
when the user looked or something resolved either in Firefox or nvda, but as 
I said before, it worked for me before as well.
 Brian
