### ISSUE TITLE
Table Navigation Broken on iTunes pages in web browsers

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2823]
**Reported by parham on 2012-11-25 09:42**
Table navigation has been broken for a few changesets. It has partly been fixed in changeset:main-5614, but it still persists in some form, unfortunately.

To see an example, go to the following iTunes page: https://itunes.apple.com/ca/album/lead-with-your-heart/id568249701

Focus on the first table and try to read the headers using alt+ctrl+left/right. Instead of hearing "name", "artist", "time", and "price", you will hear the values in the row beneath the headers.
**Blocking #3665**

**Comment by ehollig** [comment]
Is this still an issue? I am not having problems with table navigation using the website provided in https://github.com/nvaccess/nvda/issues/2823#issue-116032750. Maybe there was some change in the website? CC @jcsteh

**Comment by jcsteh** [comment]
Works for me now too.
