### ISSUE TITLE
Heading reading in IE not working properly, ie as it does in firefox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2824]
**Reported by briang1 on 2012-11-25 10:07**
Unless there is something strange about my system, I'm getting the following problem in adding to a ticket.

The first two column headers seem to be being repeated for other entries when  tabbing or arrowing through the ticket, rather than the correct  identifiers.
So for example owned by gets repeated all the way down etc.
 This is IE 8 in XP

**Comment by leonardder** [comment]
Closing this one as a duplicate of #3677, as it is specifically related to a table in the old Trac system, which is no longer in use.
