### ISSUE TITLE
While typing in Turbo C editor NVDA not read out the # as hash symbol as it is. It read out as 2

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2828]
**Reported by agateinfotek on 2012-11-27 10:42**
While typing in Turbo C editor NVDA not read out the # as hash symbol as it is. It read out as 2.What is the solution for this

**Comment by leonardder** [comment]
This issue looks abandoned and very specific. Closing, but if this still occurs, please give a shout and we can reopen.
