### ISSUE TITLE
Some web pages create strange effects and error sound

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2829]
**Reported by briang1 on 2012-11-27 15:52**

The effect can be seen if you go to 
http://www.ipservice.jp/en/bitcash.html
and let it read the page. 
Error in IE8.

IO - speech.speak (15:32:55):
Speaking [u'Consumers can buy Bit Cash in convenience stores or via internet.'](IndexCommand%2848%29,)
IO - speech.speak (15:32:56):
Speaking [u'All information of Bit Cash is integrated to 16 digit Japanese cursive syllabary, it makes Bit Cash ', IndexCommand(50), u'security thorough.'](IndexCommand%2849%29,)
IO - speech.speak (15:33:02):
Speaking [u'Bit Cash issues campaign card and original card.'](IndexCommand%2851%29,)
ERROR - synthDrivers._espeak.callback (15:33:03):
callback
Traceback (most recent call last):
  File "synthDrivers_espeak.pyc", line 127, in callback
ValueError: invalid literal for int() with base 10: ''
ERROR - unhandled exception (15:33:03):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 339, in 'converting callback result'
TypeError: an integer is required
ERROR - stderr (15:33:03):
Exception
ERROR - stderr (15:33:03):
 in
ERROR - stderr (15:33:03):
<function callback at 0x01C30DF0>
ERROR - stderr (15:33:03):
 ignored
ERROR - synthDrivers._espeak.callback (15:33:03):
callback
Traceback (most recent call last):
  File "synthDrivers_espeak.pyc", line 127, in callback
ValueError: invalid literal for int() with base 10: ''
ERROR - unhandled exception (15:33:03):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 339, in 'converting callback result'
TypeError: an integer is required
ERROR - stderr (15:33:03):
Exception
ERROR - stderr (15:33:03):
 in
ERROR - stderr (15:33:03):
<function callback at 0x01C30DF0>
ERROR - stderr (15:33:03):
 ignored
IO - speech.speak (15:33:06):
Speaking [u'Bit Cash is very well known as one of the most famous digital Cash brand.'](IndexCommand%2852%29,)
ERROR - synthDrivers._espeak.callback (15:33:07):
callback
Traceback (most recent call last):
  File "synthDrivers_espeak.pyc", line 127, in callback
ValueError: invalid literal for int() with base 10: ''
ERROR - unhandled exception (15:33:07):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 339, in 'converting callback result'
TypeError: an integer is required
ERROR - stderr (15:33:07):
Exception
ERROR - stderr (15:33:07):
 in
ERROR - stderr (15:33:07):
<function callback at 0x01C30DF0>
ERROR - stderr (15:33:07):
 ignored
ERROR - synthDrivers._espeak.callback (15:33:07):
callback
Traceback (most recent call last):
  File "synthDrivers_espeak.pyc", line 127, in callback
ValueError: invalid literal for int() with base 10: ''
ERROR - unhandled exception (15:33:07):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 339, in 'converting callback result'
TypeError: an integer is required
ERROR - stderr (15:33:07):
Exception
ERROR - stderr (15:33:07):
 in
ERROR - stderr (15:33:07):
<function callback at 0x01C30DF0>
ERROR - stderr (15:33:07):
 ignored
IO - speech.speak (15:33:11):
Speaking [of list'](u'out)
ERROR - synthDrivers._espeak.callback (15:33:12):
callback
Traceback (most recent call last):
  File "synthDrivers_espeak.pyc", line 127, in callback
ValueError: invalid literal for int() with base 10: ''
ERROR - unhandled exception (15:33:12):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 339, in 'converting callback result'
TypeError: an integer is required
ERROR - stderr (15:33:12):
Exception
ERROR - stderr (15:33:12):
 in
ERROR - stderr (15:33:12):
<function callback at 0x01C30DF0>
ERROR - stderr (15:33:12):
 ignored
IO - speech.speak (15:33:17):
Speaking [u'\u25a0', IndexCommand(54), u'Sales Channels of Bit Cash'](IndexCommand%2853%29,)
IO - speech.speak (15:33:17):
Speaking [u'Consumers can buy Bit Cash in following convenience stores. '](IndexCommand%2855%29,)
IO - speech.speak (15:33:18):
Speaking [Cash will contribute to expansion ', IndexCommand(56), u'of payment ways on your web sites.'](u'Bit)

In firefox as well as errors the voice speed is slowed by the first error it encounters it seems.

snap 5617.

**Comment by dkager** [comment]
@brian1gaff Is this still valid with espeak-ng?

**Comment by Brian1Gaff** [comment]
I think this must have not been closed but it was fixed a long time ago by a 
bug fix for something else as I recall.
It was a long time ago now and if it had reappeared somebody would have 
noticed I think!
 Brian

**Comment by dkager** [comment]
Closing as per the comment above.
