### ISSUE TITLE
Unread message counts in Outlook 2010 not spoken

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2846]
**Reported by Marcia.Yale on 2012-12-04 05:23**
There does not seem to be a way to determine the number of unread messages in any folder in Outlook 2010. NVDA-End does not report this information, nor does moving down the folder tree, nor does using the "move-to" dialog. This information would be very helpful as it ensures no newly-received email is missed.

**Comment by Qchristensen** [comment]
This issue is the same as #5068 - I'll close this one just because there is more discussion on the other issue.
