### ISSUE TITLE
Search in windows 8, number of results for apps, setting and files not read

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2849]
**Reported by david on 2012-12-05 16:56**
In windows 8, using the search pane for searching apps, settings or files, then in the Search Apps list (list of possible scopes for the search), after each of apps, settings, and files, the number of results in that scope is displayed. When the focus moves to one of these list items, Jaws and narrator read the name of the item and the number of results, but NVDA doesn't. This information is available in the ItemStatus of the object in UIA api.

**Comment by jsschultz** [comment]
Hello,

I would like to contribute to fix this issue. The UIA_ItemStatusPropertyId is being used to communicate item status information, but NVDA is not reading it. 

My approach is to mimic the HelpText property handling for UIA objects. I would just queue the property changed event for this property as a descriptionChange event and do the same things that are already done for that event. 

I could expose another event altogether called statusChange, but that might be too close to the existing stateChange event. 

What do you guys think?

**Comment by ehollig** [comment]
CC @michaelDCurran @feerrenrut @leonardder on your opinions on suggested fix in https://github.com/nvaccess/nvda/issues/2849#issuecomment-290626484 from @jsschultz

**Comment by feerrenrut** [comment]
@jsschultz Do you have a prototype you could point us to? It would make it easier to be sure we understand what you are proposing.

**Comment by Adriani90** [comment]
@josephsl since you were involved in improving this on Windows 10, is there maybe a fix for Windows 8 not far away. Your thoughts are very welcome here.

**Comment by jsschultz** [comment]
Sorry for my lack of responsiveness … I've been extraordinarily busy lately. I will provide a prototype when I get some time. Hopefully in the next several weeks.

**Comment by Adriani90** [comment]
@josephsl, @jsschultz is there a plan to extend the fix introduced in #12791 for windows 8 as well?

**Comment by josephsl** [comment]
Hi, personally, I think it doesn’t really make sense to extend the fix to an operating system that’s long out of support, especially Windows 8.0 which is end of life since January 2016. Thanks.

**Comment by jsschultz** [comment]
I do not think I will ever get to this. If no one else is complaining, then no sense in moving forward.

John


Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Brian1Gaff** [comment]
I'd guess there are more windows 7 users than 8, though I do know a few 8.1 
users. The one time I tried that OS it slowed the machine down to a crawl.

Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment]
It seems the resonance for windows 8 support is very limited and I also think not many users are on Windows 8 anymore. I am Closing this issue for now, but feel free to comment if you think that it is very crucial to implement a solutoin for windows 8.
