### ISSUE TITLE
some iTunes 11 checkboxes always reporting not checked

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2862]
**Reported by pitermach on 2012-12-11 17:15**
This is effecting the checkboxes on the device info screen if an iOS device is connected, EG the convert songs option, encript local backup, etc. The settings in preferences seem to be working fine. No matter if the box is checked or not, NVDA always says that they aren't.
On looking at the object info, it seems that the checked/not checked state is not obtained...
name: u'Convert higher bit rate songs to '
role: ROLE_CHECKBOX
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.IAccessible.IAccessible object at 0x05377D30>
Python class mro: (<class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (425, 685, 222, 18)
value: None
appModule: <'itunes' (appName u'itunes', process ID 4268) at address 54e6d10>
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 459560
windowClassName: u'Button'
windowControlID: 162085472
windowStyle: 1375797250
windowThreadID: 2504
windowText: u'Convert higher bit rate songs to '
displayText: ''
IAccessibleObject: <POINTER(IAccessible) ptr=0x6533d8 at 525c350>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=459560, objectID=-4, childID=0
IAccessible accName: u'Convert higher bit rate songs to '
IAccessible accRole: ROLE_SYSTEM_CHECKBUTTON
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: None
IAccessible accValue: exception: (-2147352573, 'Member not found.', (None, None, None, 0, None))

**Comment by ehollig** [comment]
This has been tested and is now working on the latest iTunes.
