### ISSUE TITLE
When braille display is tethered to focus  current position is not refreshed properly

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2874]
**Reported by aliminator on 2012-12-18 14:04**
Consider following text in Wordpad:
hello
world

Navigate to "worl" (braile should be tethered to focus). Cursor is blinking at "w". Press enter. Press up arrow.
 A blank line should be displayed; but the word "world" is still visible on the display.

 I tried this in a multi-line textfield in IE and it worked as expected.

**Comment by Adriani90** [comment]
@aliminator is this still reproducible?
@michaelDCurran is there a PR related to this? I see this was marked as milesotne at a certain point in the past.

**Comment by Adriani90** [comment]
cc: @ruifontes, @dkager could you please test if this is still reproducible? I tend to think that it is but I don't have a braille display at hand to test.

**Comment by dkager** [comment]
I can't reproduce this using NVDA 2019.1.1 and WordPad in Windows 10. That is only one scenario, though, maybe it still does not work in Windows 7 or in other editors.

**Comment by Adriani90** [comment]
Can we get further results from @k-kolev1985, @lukaszgo1, @hozosch, @david-acm, @buevest, @gregjozk, @Sylvie42, @Zstanecic, @jmdaweb, @ivnc, and possibly others?
Specisifically, we needs tests under Windows 8.1, Windows 7 and several editors like notepad, MS Word, wordpad etc.

**Comment by hozosch** [comment]
I can't reproduce this with windows 7 professional 64 bit and NVDA 2019.1.1.

**Comment by Adriani90** [comment]
@hozosch in which Editors did you test?

**Comment by hozosch** [comment]
So far only wordpad. After all, that's in which the issue occurred. I didn't test snapshot versions though.

**Comment by Adriani90** [comment]
I wonder if this issue could be specific to a certain Braille Display? Unfortunately the initial author did not tell us which Braille Display has been used. So if we do not get answers from referenced People above, I tend to Close this one as works for me.

**Comment by Adriani90** [comment]
cc: @FelixGruetzmacher, @MarcoZehe maybe you have further results for us with different Braille Displays?

**Comment by hozosch** [comment]
@Adriani90 I agree to your first comment. With my Handy Tech active star 16016, it works anyway.

**Comment by Sylvie42** [comment]
I tested only with windows 10, NOtepad++ and wordpad with NVDA 2019.1.1 and a varioULtra display and I could not reproduce the issue.

**Comment by MarcoZehe** [comment]
No problem here with a Handy Tech Actilini and a Focus 40 Blue 5th Generation on two machines in NotePad++, Word, WordPad, NotePad, Firefox in a multiline edit field etc.

**Comment by Adriani90** [comment]
Closing as works for me.
