### ISSUE TITLE
The NVDA cursor moves top of the page when clicking on "continue" button in a news articles of BBC.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2875]
**Reported by Harich on 2012-12-18 15:33**
If you visit news.bbc.co.uk and pick any given news heading to read the full article, you'll find there's a "continue" button a few lines below the article headline. If you click on it, the NVDA cursor moves top of the page instead scrolling down to the location where it supposedly pointing. This behavior is noticed in many other web sites as well.

**Comment by ehollig** [comment]
@jcsteh was not able to reproduce this in https://github.com/nvaccess/nvda/issues/2875#issuecomment-155303252, so closing.
I was not able to reproduce the described behavior. This could also be a special case of #2039.
