### ISSUE TITLE
Sluggish response with audio indication of focus and browse mode on/off.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2882]
**Reported by Harich on 2012-12-21 16:02**
The audio indication of focus and browse mode seems to be a bit lagging in my experience. There's a slight delay, it seems, before the beep for focus and browse mode play. It just seems a bit sluggish. Maybe we should have a shorter beep for both?

**Comment by ehollig** [comment]
This looks abandoned. I do not experience any sluggish response with focus and browse mode. This may possibly happen on some older systems though.

**Comment by jcsteh** [comment]
Closing as worksforme, since others can't reproduce and there have been no additional reports.
