### ISSUE TITLE
NVDA not indicating unread/unseen e-mails in Windows 8 mail app.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2883]
**Reported by Harich on 2012-12-21 16:16**
I'm using mail client app in Windows Eight. When you first open your mailbox to check the messages, the mail app will indicate like: "ten unseen messages" -- something to that effect. This is when you have the focus of account name. Then you tab to the inbox, it indicates something like "ten unread messages". And, of course, you tab again to sort through your mails. It's the "unseen" and "unread" indication that's not being informed by NVDA.

**Comment by Adriani90** [comment]
@Harich is this still an issue for you?

**Comment by Adriani90** [comment]
We don't have an update from the initial author since many years. In Windows mail on  Windows 10 this works correctly with NVDA 2019.1.1. If you are still having this issue, please comment on it and we can reopen the discussion if needed.
