### ISSUE TITLE
Appmodule for teamtalk4classic allowing to obtain some controls's label

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2884]
**Reported by ateu on 2012-12-21 18:44**
This appmodule provides information such as input volume, output volume and microphone activation level.
**Blocking #4076**

**Comment by ehollig** [comment]
I believe this ticket an be closed, as TeamTalk 5 has superseded TeamTalk 4. Feel free to reopen if I am in error.
