### ISSUE TITLE
NVDA navigational key behaving strangely.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2886]
**Reported by Harich on 2012-12-22 00:58**
The NVDA single navigational key is behaving strangely. Pressing letter "F" functioning like the letter "K" and the "D". For instance, pressing letter "F" on nvda-project.org, I could jump to every mark where it says "posted" (the date for NVDA's posting) and every other section noted links. The same is true for other web sites. It's happening in both IE ten and Firefox seventeen.

**Comment by ehollig** [comment]
Not able to replicate the issue described here, and it sounds like input help is providing the expected behavior.

**Comment by jcsteh** [comment]
Closing as worksforme because no one can reproduce, no further reports and this is an old issue.
