### ISSUE TITLE
"Report text formatting" could not work on merge cell

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2887]
**Reported by surfer0627 on 2012-12-22 01:39**
The function "Report text formatting" (NVDA+f) could not work on merge cell.
I got the same result from Office2003, Office2010 Excel.
I tested the function on NVDA main-5723.

**Comment by ehollig** [comment]
From https://github.com/nvaccess/nvda/issues/2887#issuecomment-155303421 it sounds like the issue reported is fixed. Closing as worksforme.
## Testing performed:
1. Open MS Excel (I have 2016)
2. Write "Hello" in cell A1.
3. Select A1 and B1 using shift+right arrow.
4. Press applications or shift+F10 and arrow down to format cells and press enter.
5. Press the right arrow key to the alignment tab and tab to merge cells.
6. Check the box and press enter to save.
7. Press NVDA+F
### Actual and Expected result
NVDA announces formatting information.

**Comment by bhavyashah** [comment]
Using NVDA 2017.2 and Excel 2010 on a Windows 8.1 system, when a1 and b1 are merged and centred, there are two results:
* When navigation around the spreadsheet and landing on the merged 'a1 through b1' cell, pressing NVDA+F reports the following:
style Normal
no border lines
Calibri
11.0
black on white
background pattern none
align center
vertical align default
* However, when I press F2 to edit the field and then issue NVDA+F, NVDA speaks the following:
space
Calibri
11pt
black on white

At the very least, there is a discrepency between what NVDA reports (when sort of like in browse mode and navigating cells in Excel and what NVDA reports when in a focus mode equivalent and editing the cell) in these two cases. This probably needs to be reopened and investigated further. Apologies for not having tested this earlier itself, @ehollig.

**Comment by ehollig** [comment]
Interestingly, in Excel 2016, when I issue the F2 command to edit the contents of the cell and perform the NVDA+F, NVDA reports, "No formatting information". Maybe @michaelDCurran or @jcsteh could shed some light on this issue and the reasoning for the differences?

**Comment by michaelDCurran** [comment]
Excel 2016 implements UIAutomation for the formular bar. Thus we don't 
use display model. However, the UIA implementation does not provide 
useful formatting information yet.

**Comment by Adriani90** [comment]
@ehollig I think your described behavior is covered in issue #6479. Do you see this particluar issue as solved?

**Comment by ehollig** [comment]
Yes, sounds to be solved. Closing
