### ISSUE TITLE
Announcing spelling Errors In IE 10 Preview And Later

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2889]
**Reported by trenton on 2012-12-22 09:25**
Not sure if this has to be implemented or not, as it technically just works with Mozilla, so I suppose if this idea were to  be added, it'd just work. NVDA has no problems with this new spell checking feature.

**Comment by jcsteh** [comment]
Duplicate of #4174 (fixed some time ago).
