### ISSUE TITLE
Improvements on editing Messages in Windows Live Mail

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2894]
**Reported by ateu on 2012-12-23 18:50**
It would be so useful if NVDA provides support for formatting information and spelling errors when editing messages in Windows Live Mail, like occurs in Mozilla Thunderbird and SeaMonkey.
Currently, it'spossible to obtain this information when reading  messages, but not editing.

Forgive me if it's not possible to do this.

**Comment by ehollig** [comment]
I believe WLM has been discontinued. Suggest closing?
