### ISSUE TITLE
Automatic braille table suggestion based on the user's language

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#290]
**Reported by aleksey_s on 2009-03-17 21:12**
NVDA must automatically suggest appropriate braille translation table, to help beginners. We need to decide what tables take as default, and add the language code as a field into table-list binding.

**Comment by leonardder** [comment]
CC @Dkager @JCSTeh @BDorer @JosephSL

**Comment by leonardder** [comment]
Labeled as feature. Some thoughts.

It seems that @JCSTeh doesn't want to rely on liblouis metadata alone, which I understand and agree with. @DKager, you might have a better overview on how the metadata thing is going?

Personally, I think we should allow language maintainers to set their prefered defaults with some restrictions (e.g. no grade 2). Such an automated selection system could be broader in scope. For speech, I belief selection of the desired language is done in the espeak driver, which is a bit ugly imo.

**Comment by dkager** [comment]
Related: https://github.com/nvaccess/nvda/issues/6952#issuecomment-285997765

**Comment by dkager** [comment]
> @dkager, you might have a better overview on how the metadata thing is going?

Slowly. :)
It's hard to standardize. One country's grade 1 is uncontracted, another country calls that grade 0. Yet others say grade 0 is computer braille.

**Comment by jcsteh** [comment]
The new brailleTables module introduced in #6449 makes our own table metadata a lot more extensible. I think we could add a `defaultForLanguages` argument to the `addTable` function which specifies a list of languages for which this is the default. To be future proof, I think we should allow language defaults to be specified for both contracted and uncontracted. For now, we can just choose uncontracted. In future, though, we may want to make them separately configurable to allow fast switching, uncontracted input outside of editable content, etc.

**Comment by leonardder** [comment]
One concern I have is how we should deal with dialects. For example, there is a Dutch (Netherlands) and Dutch (Belgium) table, however there is only one single NVDA language for both dialects. Using the windows language for this could be sufficient, of course.

**Comment by dkager** [comment]
One result that should come out of the Braille Authority is that these two tables get merged. But I imagine some Asian countries have the dialect problem too. English countries had it, but UEB covers most or all of that.

**Comment by bdorer** [comment]
one easy way would be the following:
Ask the user in the welcome dialog wheather he wants to use braille and provide him one of the table wich fits to his language.

**Comment by Qchristensen** [comment]
Since this was asked on Twitter, would setting the Braille table for the current language be done just when installing, or when detecting changes of language in text (like the synthesizer changing language on the fly)?

**Comment by dkager** [comment]
Changing the braille table dynamically based on content language should probably not be the default behavior. You don't necessarily have knowledge of all the braille tables for the languages that you understand.

If there will be an option to dynamically switch braille tables it will be helpful if the user can also specify if she wants 6-dot/literary braille or 8-dot/computer braille.
