### ISSUE TITLE
live region not read in firefox when tabbing - reads when arrowing

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2908]
**Reported by RichCaloggero on 2013-01-03 04:45**
http://www.mit.edu/~rjc/aria/popupExtraInfo.html

The popup is triggered when one of the links gains focus, either via tab or arrows,  However, it is not announced when tabbing.

You can sort of hear nvda begin to voice it, but then it is cut off by nvda voicing the text inside the "a" element.  When you arrow, the text content of the anchor is read first, then nvda voices the popup.

Seems like a bug to me.

Got to say - I love that nvda will read title tags on links - certainly the easiest way of adding small bits of extra info; wish all screen readers did this!
-- Rich

**Comment by ehollig** [comment]
It appears that the URL provided as an example no longer exists. @jcsteh, in https://github.com/nvaccess/nvda/issues/2908#issuecomment-155303715 it sounds like you had an opinion about this. Has this changed since the creation of the comment?

**Comment by jcsteh** [comment]
I think things have changed in this code since this issue was filed. Nevertheless, now that the test case has gone, this is no longer valid. Closing. If this behaviour is seen elsewhere, this can be reopened.
