### ISSUE TITLE
An easy way for users to select the additional braille translation tables

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#291]
**Reported by aleksey_s on 2009-03-17 21:17**
Add the "other..." button near the table selection combo box, which will bring up the default windows open file dialog, pointed in louis\tables directory to allow user select an additional table, which is not presented in nvda's tables list.

**Comment by dkager** [comment]
I would say this is a won't fix. While it should be made easier for add-ons to supply braille tables (#3304), a user should probably not be able to select any liblouis table. For example, some tables are meant to be included by other tables and don't work well stand-alone. Furthermore, this enhancement makes it quite easy to select a table that was deliberately kept out of NVDA for whatever reason.

CC @leonardder

**Comment by jcsteh** [comment]
Agreed. Note that #3304 would also make it possible for someone to create an add-on to add arbitrary tables if they really wanted to.
