### ISSUE TITLE
The notification of browse mode updates should be anounced by sound signal while working with Gecko based WEB browsers

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2935]
**Reported by janusz on 2013-01-17 15:02**
Dear MR Tech, Dear Mr Michael Damien Curan,
Dear others,
What about implementing  The notification of browse mode updates by using some NVDA sound alert?
I know, that it is not possible to use speech, but what about sound signal? This setting could be enabled or disabled by users by using some NVDA settings menu.
Or for beginning, by manually edit nvda.ini, because i know, that You do not like to modifi NVDA GUI too oftento prevent frequent translations of NVDA strings.
Please do not change my suggestion  with The NVDA message busy, which is being pronounced by NVDA when ever new page refresh have been made by gecko based browsers.
Thank You for Yours answer on this ticked.
It is really somethink else, than in my previously reported ticked.
Only some sound would be played by NVDA.
Thank You very much for yours answer.
With kindness regards.
Janusz Chmiel

**Comment by derekriemer** [comment]
closing because this clearly is fixed.
