### ISSUE TITLE
- unhandled exception in Winamp when  looking up cddb

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2936]
**Reported by briang1 on 2013-01-17 20:18**
This error is generated whenever winamp is used to play a new cd it does not know about via the winamp menu. Once the cd is known, the error is not heard.
I think some information appears on screen which is not read which shows the player looking for the details over the internet the first time, but not subsequently, and it is this information which triggers the error.

Here is a standard log with the error on a first run of the cd.

IO - speech.speak (18:27:31):
Speaking [('en_UK'), u'Winamp 5.63'](LangChangeCommand)
IO - speech.speak (18:27:37):
Speaking [('en_UK'), u'System  subMenu  Space'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:27:37):
Input: kb(desktop):downArrow
IO - speech.speak (18:27:37):
Speaking [('en_UK'), u'Winamp  subMenu  w'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:27:39):
Input: kb(desktop):rightArrow
IO - speech.speak (18:27:39):
Speaking [('en_UK'), u'Nullsoft Winamp...  w  1 of 23'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:27:41):
Input: kb(desktop):downArrow
IO - speech.speak (18:27:41):
Speaking [('en_UK'), u'Play  subMenu  p'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:27:41):
Input: kb(desktop):rightArrow
IO - speech.speak (18:27:41):
Speaking [('en_UK'), u'File...   \tL  f  1 of 11'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:27:43):
Input: kb(desktop):downArrow
IO - speech.speak (18:27:43):
Speaking [('en_UK'), u'URL...\tCtrl+L  u  2 of 11'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:27:44):
Input: kb(desktop):downArrow
IO - speech.speak (18:27:44):
Speaking [('en_UK'), u'Folder...\tShift+L  f  3 of 11'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:27:45):
Input: kb(desktop):downArrow
IO - speech.speak (18:27:45):
Speaking [('en_UK'), u'Audio CD D:  a  5 of 11'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:27:46):
Input: kb(desktop):downArrow
IO - speech.speak (18:27:46):
Speaking [('en_UK'), u'Audio CD E:  a  6 of 11'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:27:48):
Input: kb(desktop):enter
DEBUGWARNING - watchdog._watcher (18:27:49):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 164, in <module>
  File "core.pyc", line 298, in main
  File "wx_core.pyc", line 8010, in MainLoop
  File "wx_core.pyc", line 7306, in MainLoop
  File "wx_misc.pyc", line 1358, in Notify
  File "wx_core.pyc", line 14771, in Notify
  File "IAccessibleHandler.pyc", line 793, in _fakeFocus
  File "NVDAObjects__init__.pyc", line 253, in objectWithFocus
  File "NVDAObjects__init__.pyc", line 183, in findBestAPIClass
  File "NVDAObjects__init__.pyc", line 182, in findBestAPIClass
  File "NVDAObjects\IAccessible__init__.pyc", line 325, in kwargsFromSuper
  File "IAccessibleHandler.pyc", line 333, in accessibleObjectFromEvent
  File "oleacc.pyc", line 240, in AccessibleObjectFromEvent

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (18:27:49):
oleacc.AccessibleObjectFromEvent with window 1179880, objectID -4 and childID 0: 
ERROR - unhandled exception (18:27:49):
Traceback (most recent call last):
  File "wx_misc.pyc", line 1358, in Notify
  File "wx_core.pyc", line 14771, in Notify
  File "IAccessibleHandler.pyc", line 796, in _fakeFocus
  File "IAccessibleHandler.pyc", line 660, in processFocusNVDAEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 597, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 780, in _get_states
AttributeError: 'winampMainWindow' object has no attribute 'event_objectID'
IO - speech.speak (18:27:49):
Speaking [('en_UK'), u'1. The Noisettes - Transmission Will Start - Winamp'](LangChangeCommand)

This is the same cd next time.

IO - inputCore.InputManager.executeGesture (18:28:08):
Input: kb(desktop):alt+f4
IO - speech.speak (18:28:08):
Speaking [('en_UK'), u'Taskbar'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:28:11):
Input: kb(desktop):windows+m
DEBUG - appModuleHandler.update (18:28:11):
application winamp closed
IO - speech.speak (18:28:11):
Speaking [('en_UK'), u'Desktop  list'](LangChangeCommand)
IO - speech.speak (18:28:11):
Speaking [('en_UK'), u'Winamp  19 of 65'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:28:13):
Input: kb(desktop):enter
IO - speech.speak (18:28:15):
Speaking [('en_UK'), u'Winamp 5.63'](LangChangeCommand)
IO - speech.speak (18:28:19):
Speaking [('en_UK'), u'System  subMenu  Space'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:28:20):
Input: kb(desktop):downArrow
IO - speech.speak (18:28:20):
Speaking [('en_UK'), u'Winamp  subMenu  w'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:28:21):
Input: kb(desktop):rightArrow
IO - speech.speak (18:28:21):
Speaking [('en_UK'), u'Nullsoft Winamp...  w  1 of 23'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:28:22):
Input: kb(desktop):downArrow
IO - speech.speak (18:28:22):
Speaking [('en_UK'), u'Play  subMenu  p'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:28:22):
Input: kb(desktop):rightArrow
IO - speech.speak (18:28:23):
Speaking [('en_UK'), u'File...   \tL  f  1 of 11'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:28:24):
Input: kb(desktop):downArrow
IO - speech.speak (18:28:24):
Speaking [('en_UK'), u'URL...\tCtrl+L  u  2 of 11'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:28:24):
Input: kb(desktop):downArrow
IO - speech.speak (18:28:24):
Speaking [('en_UK'), u'Folder...\tShift+L  f  3 of 11'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:28:25):
Input: kb(desktop):downArrow
IO - speech.speak (18:28:25):
Speaking [('en_UK'), u'Audio CD D:  a  5 of 11'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:28:26):
Input: kb(desktop):downArrow
IO - speech.speak (18:28:26):
Speaking [('en_UK'), u'Audio CD E:  a  6 of 11'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:28:28):
Input: kb(desktop):enter
IO - speech.speak (18:28:28):
Speaking [('en_UK'), u'1. The Noisettes - Transmission Will Start - Winamp'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:28:40):
Input: kb(desktop):alt+f4
IO - speech.speak (18:28:41):
Speaking [('en_UK'), u'Taskbar'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (18:28:43):
Input: kb(desktop):control+alt+r
INFO - core.main (18:28:43):
Exiting

Now that first log showed little of what actually was going on on the winamp screen at the time of the error, so here is what I got when I gave it a non existent CD to look up. IE the text causing the error was displayed long enough to be seen.

ERROR - unhandled exception (19:22:14):
Traceback (most recent call last):
  File "wx_misc.pyc", line 1358, in Notify
  File "wx_core.pyc", line 14771, in Notify
  File "IAccessibleHandler.pyc", line 796, in _fakeFocus
  File "IAccessibleHandler.pyc", line 660, in processFocusNVDAEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 597, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 780, in _get_states
AttributeError: 'winampMainWindow' object has no attribute 'event_objectID'
IO - speech.speak (19:22:14):
Speaking [('en_UK'), u'Retrieving CD information...  dialog  Accessing Gracenote CDDB\xae...'](LangChangeCommand)
IO - speech.speak (19:22:14):
Speaking [('en_UK'), u'Abort  button  Alt+a'](LangChangeCommand)
IO - tones.beep (19:22:14):
Beep at pitch 1760.0, for 40 ms, left volume 50, right volume 50
IO - speech.speak (19:22:14):
Speaking [('en_UK'), u'100 percent'](LangChangeCommand)
IO - speech.speak (19:22:16):
Speaking [('en_UK'), u'1. cda://E,1 - Winamp'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (19:22:38):
Input: kb(desktop):control+alt+r
INFO - core.main (19:22:39):
Exiting

If you need any more info let me know. 
It does this  without the new  winamp extended module or with it.

**Comment by leonardder** [comment]
CC @Brian1Gaff, can you still reproduce this?

**Comment by bhavyashah** [comment]
This is just a friendly reminder for @brian1gaff to kindly respond to @leonardder's https://github.com/nvaccess/nvda/issues/2936#issuecomment-314222956.

**Comment by Brian1Gaff** [comment]
I was not sent an email about this new /old comment. May have been one of 
the emails Virgin dumped.
 Using winamp now, with the latest add on as well, the only weirdness is if 
you answer no to is this a new portable device you want to use.
 I'm thinking that the actuall issue is probably in winamp and unlikely to 
ever get fixed now.
 I'll go and rre read the thread to see if I can remember exactly what else 
was going on. Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Brian1Gaff** [comment]
Personally, I seldom use winamp to look up cddb these days, but I think it 
prompts you when there is an issue when you inseert some discs. .
 My feeling is that once again its Winamp as its suspiciously like the error 
on portable  media.
 Probably worth closing and as it is, I think now abandoned software then so 
be it. It can be annoying but worked around.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by ehollig** [comment]
Closing, as it sounds as if this is an issue with Winamp, which is now abandoned software. It is still usable, but development is abandoned.
