### ISSUE TITLE
NVDA skipps parts of the text

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2937]
**Reported by ruifontes on 2013-01-19 23:59**
Hello,

In a webpage, http://www1.folha.uol.com.br/esporte/1217462-valdivia-desfalca-palmeiras-em-estreia-no-paulista.shtml, NVDA is skipping parts of the text.

In the log viewer the text is:

Speaking [u'Desde seu retorno ao clube, em agosto de 2010, o meia ja sofreu ', u'link', u'dez lesoes mais serias, que o ', IndexCommand(22), u'cou apenas nove gols. '](IndexCommand%2821%29,)

In the webpage the text is:
Desde seu retorno ao clube, em agosto de 2010, o meia ja sofreu (link) dez lesoes mais serias, que o tiraram de 68 partidas.(end link) No mesmo periodo, marcou apenas nove gols. 

As you can see, the text:
tiraram de 68 partidas.(end link) No mesmo periodo, mar
was not read.

I have replaced the accentued characters by the characters without accentuation.

Rui

**Comment by ehollig** [comment]
I am not able to replicate this using IE 11. Log file displays all of the text when set to debug as well. Unless this is a particular issue with IE 9, I suggest a close.

**Comment by leonardder** [comment]
CC @RuiFontes, do you have anything to add here?

**Comment by ruifontes** [comment]
Hi Leonard!

The problem is solved.
Can close it.

Rui


-----Mensagem Original----- 
De: Leonard de Ruijter
Data: 26 de julho de 2017 17:52
Para: nvaccess/nvda
Cc: ruifontes ; Mention
Assunto: Re: [nvaccess/nvda] NVDA skipps parts of the text (#2937)



CC @ruifontes, do you have anything to add here?
