### ISSUE TITLE
Issue with Outlook profile change while using NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2941]
**Reported by sajeesh on 2013-01-23 14:52**
Hi Team,

I am facing an issue with my Microsoft outlook client while using along with NVDA. While starting the outlook client it never popup a profile selection window if the NVDA service is running. The outllok work fine without the NVDA running.

**Comment by ehollig** [comment]
Closing, as the original poster did not mention which version of Outlook was being used, which version of NVDA, and the original poster is no longer easily reachable.
