### ISSUE TITLE
baum dm80plus in NVDA latest snapshot is not running

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2948]
**Reported by ruslan on 2013-01-26 14:29**
I would like my braile display baum dm80plus to be running directly in NVDA.
it is running but through BRLTTY.

**Comment by bhavyashah** [comment]
The original author of this ticket is now out-of-reach and unfortunately did not respond to @jcsteh's https://github.com/nvaccess/nvda/issues/2948#issuecomment-155304189 either. @jcsteh Do we have resources, contacts or technical information sufficient to work on this issue further?

**Comment by jcsteh** [comment]
We do have contacts at Baum, but without current interest from users, I don't think pursuing this has any practical benefit. I'm closing this for now, but we can reconsider opening discussions with Baum should user interest arise.

**Comment by leonardder** [comment]
As far as I know, this display is no longer shipped.
