### ISSUE TITLE
NVDA updater and password protected proxies

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2950]
**Reported by quetzatl on 2013-01-26 17:32**
NVDA should use the proxy settings configured in the OS to download updates from networks that use these proxies

**Comment by jcsteh** [comment]
No response to last question and can't contact reporter. Closing.

**Comment by ivnc** [comment]
Hello.

It seems that, in ONCE's case, username and password are stored in Credentials Manager (Windows's Control Panel). I don't have access to this proxy, but contact with the original reporter.
I propose to reopen this issue, as it could be preventing users in corporative environments from using NVDA.

Regards.

**Comment by ivnc** [comment]
With the introduction of NVDA 2019.3, it is possible to connect to this kind of proxies by adding the "HTTP_PROXY" and "HTTPS_PROXY" environment variables to the windows user profile, containing the full Proxy address (e.g. http://me:mypassword@miproxy.micompany.com:3128). this has been tested with ciberpxy.once.org with good results.

Regards.
