### ISSUE TITLE
MS Excel (braille cursor position incorrect on merged-cell)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2954]
**Reported by surfer0627 on 2013-02-01 06:33**
Please test the case on the attachment.

There are five merged cells.
A1 through C1
A2 through C2
A3 through C3
A4 through C4
A5 through C5

While moving from A1 to A2:
Synthesizer reports
"A2 Tuesday through C2 selected"

Braille cursor stuck in A1.

The same situation happened again, while moving from A2 to A3.

**Comment by ehollig** [comment]
I am not able to replicate using Excel 2016 and Braille Viewer. If someone is using a Braille display and can replicate this, we can reopen this issue. Closing
