### ISSUE TITLE
report line spacing in valid locations

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2961]
**Reported by driemer.riemer@... on 2013-02-04 03:43**
Report formatting such as double spaced or single spaced where applies. This could be a feature reported when NVDA+f is pressed and could also be in document formatting.

**Comment by derekriemer** [comment]
@MichaelDCurran would this be something to look into with the further word enhancements that are happening lately? It's something that students often need to look at when editing papers.

**Comment by nvaccessAuto** [comment]
Incubated in 15cc374df61392770330202f17a687b672aef2b1.

**Comment by derekriemer** [comment]
@MichaelDCurran do you want me to write scripts for reporting the control+1 and control+2 keystrokes?

**Comment by michaelDCurran** [comment]
If you like. Thanks :)

**Comment by derekriemer** [comment]
Should I still merge it into master? I could create the pr against t2961


On 5/25/2016 1:47 AM, Michael Curran wrote:
> If you like. Thanks :)
>
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/2961#issuecomment-221498285>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by michaelDCurran** [comment]
Do it against t2961 as it depends on  it.


Mick



On 25/05/2016 7:14 PM, derekriemer wrote:
> Should I still merge it into master? I could create the pr against t2961
>
>
> On 5/25/2016 1:47 AM, Michael Curran wrote:
> > If you like. Thanks :)
> >
> >
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nvaccess/nvda/issues/2961#issuecomment-221498285>
> >
>
> -- 
> ------------------------------------------------------------------------
>
>
> Derek Riemer
>
> * Department of computer science, third year undergraduate student.
> * Proud user of the NVDA screen reader.
> * Open source enthusiast.
> * Member of Bridge Cu
> * Avid skiier.
>
> Websites:
> Honors portfolio <http://derekriemer.com>
> Awesome little hand built weather app!
> <http://django.derekriemer.com/weather/>
>
> email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
> Phone: (303) 906-2194
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/2961#issuecomment-221517624>
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by derekriemer** [comment]
Note I removed two tabs from the end of a line that were randomly there.


On 5/25/2016 3:25 AM, Michael Curran wrote:
> Do it against t2961 as it depends on it.
>
>
> Mick
>
>
>
> On 25/05/2016 7:14 PM, derekriemer wrote:
> > Should I still merge it into master? I could create the pr against t2961
> >
> >
> > On 5/25/2016 1:47 AM, Michael Curran wrote:
> > > If you like. Thanks :)
> > >
> > >
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/nvaccess/nvda/issues/2961#issuecomment-221498285>
> > >
> >
> > --
> > ------------------------------------------------------------------------
> >
> >
> > Derek Riemer
> >
> > * Department of computer science, third year undergraduate student.
> > * Proud user of the NVDA screen reader.
> > * Open source enthusiast.
> > * Member of Bridge Cu
> > * Avid skiier.
> >
> > Websites:
> > Honors portfolio <http://derekriemer.com>
> > Awesome little hand built weather app!
> > <http://django.derekriemer.com/weather/>
> >
> > email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
> > Phone: (303) 906-2194
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nvaccess/nvda/issues/2961#issuecomment-221517624>
> >
>
> -- 
> Michael Curran
> Executive Director, NV Access Limited
> Phone: +61 7 3149 3306
> Website: http://www.nvaccess.org/
> Twitter: @NVAccess
> Facebook: http://www.facebook.com/NVAccess
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/2961#issuecomment-221520236>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by nvaccessAuto** [comment]
Incubated in b9559f8c19fab80c651eb73ab61980c9c081275d.

**Comment by jcsteh** [comment]
Master merge note: add Derek to contributors.

**Comment by derekriemer** [comment]
NO. I'm there.


On 5/25/2016 5:54 PM, James Teh wrote:
>
> Master merge note: add Derek to contributors.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/2961#issuecomment-221741543>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment]
Oh. So you are. Your name is in lower case and I did a case sensitive 
search. That should be fixed at least.

**Comment by nvaccessAuto** [comment]
Incubated in c12fe1dc65b2386550dd1b0652f5980221d6eeeb.
