### ISSUE TITLE
Problems When Using Down or Up Arrow Keys when Crossing Page Boundaries in Microsoft word 2003

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2972]
**Reported by dgoldfield on 2013-02-07 16:40**
When trying to read through a multi-page document in Word 2003 NVDA appears to skip a page when using the down arrow when moving from one page to another.  In a document containing only two pages pressing the down arrow key does not appear to speak the first line of the next page but just reads the bottom line of page 1.  This does not occur when performing a "say all" nor does it occur when navigating word by word with ctrl and arrow keys.  .

**Comment by ehollig** [comment]
It appears that this issue does not contain an example of the problem and there is no way to contact the original author. Unless someone can replicate this or provide an example using Word 2003, I suggest a close.

**Comment by leonardder** [comment]
Agreed here. Word 2003 issues usually end up in a won't fix anyway :)
