### ISSUE TITLE
make conexant  smart audio control panel accessible

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2973]
**Reported by enes on 2013-02-07 21:01**
hi,
my computer's audio driver conexant has many important settings that can only can be configured through it's control panel applet
currently the control panel app for conexant is almost totally inaccessible

**Comment by leonardder** [comment]
This ticket looks abandoned. Furthermore, it is very likely that conexant updated their applet since the initial report.

So, this is a call for other conexant users. If we haven't gotten new information about this ticket at the end of next week, I will close this.
