### ISSUE TITLE
NVDA does not report misspelled words in AkelPad

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2991]
**Reported by k_kolev1985 on 2013-02-13 12:48**
AkelPad has a spell checker, witch relies on the Aspell core. I've read the documentation for the spell check plugin for AkelPad, and by following its instructions, I've managed to install Aspell and a bulgarian dictionary (not official - made by a friend of mine). But I've noticed, that even though after executing the command for background spell check ("spell check as you type") and the misspelled words are underlined, NVDA does not report those words as misspelled. Can something be done (either on NVDA or on AkelPad's side, so NVDA can report the misspelled words in AkelPad?

**Comment by ehollig** [comment]
@k_kolev1985 do you know if this is still the case with this plugin? As stated in https://github.com/nvaccess/nvda/issues/2991#issuecomment-155304813, it is possible that this is not possible to do.

**Comment by k-kolev1985** [comment]
I doubt that the situation has changed, but I can't confirm it, since I've stopped using AkelPad and I'm using Notepad++ at the moment with its DSpellCheck plugin. But even there the situation is the same, unfortunately. But never mind Notepad++ and its spellchecking - it is a topic for another discussion.

**Comment by Adriani90** [comment]
I suggest closing this issue and reopen it when someone need a solution. @k-kolev1985 as I understand you don't use AkelPad anymore. Right?

**Comment by k-kolev1985** [comment]
@Adriani90 Yes, I no longer use AkelPad.

**Comment by leonardder** [comment]
@Adriani90: Sounds like a great suggestion.
