### ISSUE TITLE
The KMPlayer :a VideoPlayer maybe can help Nvda to read the Subtitles

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3002]
**Reported by alyabani94 on 2013-02-18 12:36**
Hello
i requested for a weak ago about supporting reading the subtitles on videoes with Nvda
i looked for a way that i can help you somehow to do it
i found a VideoPlayer called KMPlayer 
http://www.kmpmedia.net/
maybe it will help Nvda to read the subtitles if you create an compatible or add an add-ons for it
because there are some options  are interesting
on the Options menu
the options are
TTS: Read Subtitle but this option doesn't work when i activate it
TTS: Read Message when i activate this option the  default   speech of the Windows is speak it's the Sapi 5's speech  
TTS: Read Title on Play Start it's the same thing with the TTS: Read Message 
I hope this can help somehow to read the Subtitles with Nvda
and thanks

**Comment by ehollig** [comment]
This sounds similar to the request in #2797

**Comment by josephsl** [comment]
Hi,

Two things: are there any updates to this, and can we contact the original poster?

CC @k-kolev1985

**Comment by Adriani90** [comment]
cc: @nvdaes, @javidominguez

**Comment by smythp** [comment]
Does anyone have any insights into the kmplayer bug introduced after version 3.7 that makes the TTS repeat? I can roll back to an earlier version but then some newer videos won't play.

**Comment by Adriani90** [comment]
I cannot download the KM Player for Windows from the website.
However, automatic OCR recognition has been introduced to NVDA 2023.3 so the subtitles can be read via the automatic OCR recognition. Closing as works for me.
