### ISSUE TITLE
Move virtual buffer position to mouse position in browse mode feature

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3004]
**Reported by falinn.onda on 2013-02-18 21:14**
I think it will be very useful to enable users to move virtual buffer position to mouse position in browse mode.
For example, if one uses firefox to read a webpage, letting the user put the mouse on a certain element on the page and press a keyboard shortcut, so that the current position in the virtual buffer is set to this element. The keyboard navigation can be used from that point on.

In many web pages it is difficult to locate desired element only by keyboard and for those of us who can use mouse to locate the item, such feature will be very helpful.

If it is technically problematic, please consider adding this feature in the following way: adding a keyboard shortcut that when pressed copies the text under the mouse into the NVDA search dialog and search for the first occurrence of this text. In this way you can achieve a similar capability in most cases where the text is unique.

BTW. i tried using NVDA+numpadmultiply for this but it did not work for me on firefox.

Thanks

**Comment by ehollig** [comment]
Closing in favor of #4896. Discussion can continue there.
