### ISSUE TITLE
NVDA doesn't switch between different keyboard layouts in windows 7 ultimate

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3008]
**Reported by fatma.mehanna on 2013-02-19 13:24**
hi,
This problem happens since 2012.3, but because it doesn't happen from the first time, the users didn't notice it.
the problem is when we move between deskTop and windows explorer twice or thrice, NVDA stopped switching between different keyboard layouts inside windows explorer.
it converts the language layout when we are on desktop, but when we move from desktop to any partition/folder thrice or 4 times, Nvda stopped converting.
sorry for reporting it lately, but it started to occure clearly in main 5896.
it doesn't happen in windows xp.
it just happens in windows 7.
here is a log file to show you the problem.
thanks.

**Comment by ehollig** [comment]
This sounds like it has been resolved from https://github.com/nvaccess/nvda/issues/3008#issuecomment-155304986. Possibly related #7383
