### ISSUE TITLE
Excel 2010-some extraneous text is announced on moving to the first control in fill tab page of format cells dialog.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3021]
**Reported by sumandogra on 2013-02-22 15:01**
Excel 2010
Extraneous text is announced on tabbing to the first control in the fill tab page of the format dialog.

Steps to reproduce:
1.  Press CTRL+1 to open format cells dialog.
2.  CTRL+TAB to fill tab page.
3.  TAB to move to the first control
4.  NVDA announces some extraneous text-MSO control generic….

**Comment by leonardder** [comment]
@sumandogra: Can you still reproduce this?

**Comment by ehollig** [comment]
This sounds related to #3041 and #1836

**Comment by Adriani90** [comment]
This is not reproducible in NVDA 2019.1.1 and Excel 2010. I am closing this as works for me.
