### ISSUE TITLE
Indicate spelling errors in braille

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3022]
**Reported by albzan on 2013-02-22 15:55**
- Braille attributes now are displayed using Emphasis Opcodes defined on liblouis tables. By this way you get extra symbols in 8-dots braille representation. Using 7 and 8 dots instead of opcodes also for Bold, Italic, underline, misspelling attributes, the number of chars is the same of what you have on the screen.
- Now braille attributes are displayed only if the speech read them. Is it possible to show braille attributes independently?
- Now misspellings are not displayed using attributes.
  **Blocking #3469**

**Comment by dkager** [comment]
See also #6785 which is more generic (also covers comments and revisions).

**Comment by Adriani90** [comment]
Actually I would close this in favor of #6785 and #7608. There are good suggestions there to cover this.
Regarding display of atributes separately in speech and braille, there is already issue #1885.
Please continue discussions on the coresponding issues. Thanks.
