### ISSUE TITLE
NVDA makes Windows Explorer crash in the Windows Action Center

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3024]
**Reported by k_kolev1985 on 2013-02-23 08:38**
If I'm reading an error report in Windows Action Center, using the mouse tracking function of NVDA (reading with the mouse), Windows Explorer will most probably crash.

Steps to reproduce:
1. Open "Action Center" in the Control Panel.
2. If you don't have any current error reports (messages from the "Action Center"), go to the link "Show archived messages" (if you have any there).
3. Open a message, and with NVDA's mouse tracking turned on, start exploring the window with the messages.
Expected result: NVDA should read the things under the mouse cursor without problems.
Actual result: A "Windows Explorer has stopped working" error message appears and the "Action Center" closes.

NVDA version: snapshot main r5900.
OS: Windows 7 Ultimate SP1 32-bit in bulgarian with locale settings set to "bulgarian".
IE version: 8.0.7601.17514.

**Comment by bhavyashah** [comment]
According to https://github.com/nvaccess/nvda/issues/3024#issuecomment-155305158, the reported issue no longer persists with Internet Explorer 11. Since this therefore seems to be specific to older versions of IE, which we no longer can provide fixes for, I suggest closing. @ehollig

**Comment by leonardder** [comment]
Agreed.
