### ISSUE TITLE
Visual studio 2012 quick info

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3025]
**Reported by falinn.onda on 2013-02-23 11:03**
Hi,
I'm trying to work with Visual studio 2012 and NVDA 2012.3.1.
One of the nice features is visual studio is that you can put the cursor on an element and press CTRL+k,i to show quick info tooltip.

I have enabled "report tooltips" but NVDA doesn't seem to notice this tooltip. If i point the mouse at the tooltip it does read correctly. I've also tried using object navigation to get to this tooltip with no success.

For example, in a c# windoes form project, writing MessageBox and placing the edit cursor on this code and pressing CTRL+k,i (might be configured to a different shortcut, but also available at Edit->Intellisense->quick info).

Another example for such a tooltip is in intellisense auto completion. For example write the beginning "Mes" and that press CTRL+SPACEBAR to show auto completion. NVDA reads the selected line correctly (which is really great), but i did not find a way to read the tooltip describing the selected element.

Those tooltips can really improve productivity during coding and it would be really nice someone would help me find a way to read them.

If a more detailed reproduction steps are needed, pleas let me know.

Thanks in advance

**Comment by leonardder** [comment]
This might be related to #6743 and #3020 

CC @mohammad-suliman

**Comment by leonardder** [comment]
Given the age of this issue and we don't seem to be able to track down the original author, I'm closing this one. Note that Visual 2019 has many accessibility fixes.
