### ISSUE TITLE
loss of speech and sluggish in win7

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3029]
**Reported by davycuppens on 2013-02-28 20:37**
These are the properties on my system where nvda is crashing all the time:
Windows 7 home sp1.
gwrd-mir-driver, Intel(R)G33/G31 express chipset family
Windoweyes display driver: Wineyes is my first used screenreader at the
moment.
Realtek HD Audio Processor
Intel(R) core (TM2) duo cpu 8400 3.0GHZ ram processor user pc.
My screen is set up at resolution 32 bit 1280/1024 60 herz.
Virus scanner is Avast internet security
I hope that with this information maybe deverlopers or other advanced users
can reproduce the problem that remains occuring on some win7 systems.

**Comment by leonardder** [comment]
Closing as duplicate of #1710. Also #686 seems related.
