### ISSUE TITLE
nvda reads entire text when moving the  mouse to an empty  spot on a web page in internet explorer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3034]
**Reported by enes on 2013-03-02 09:41**
str 
1. open any web site example
www.donanimhaber.com
and stop  the mouse  at an  empty place  on the page with no text 
nvda will read out aprox 25 pages of php code
this only happens with internet explorer all versions

**Comment by Adriani90** [comment]
I can still reproduce this with NVDA 2018.4 Beta 2 and IE11 on Windows 10 1809 Update.

**Comment by Adriani90** [comment]
cc: @leonardder

**Comment by Adriani90** [comment]
IE support has ended in 2022 and the borwser is automatically removed from PCs that still have it after an Edge update in February 2023. I don't expect any accessibility updates to the IE mode in Edge, so I am closing this as abandoned.
