### ISSUE TITLE
add support for maxthon browser

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3039]
**Reported by beqa on 2013-03-03 09:02**
hi.

please add support for maxthon browser if it is possible.

**Comment by bhavyashah** [comment]
@feerrenrut From https://github.com/nvaccess/nvda/issues/3039#issuecomment-155305347, do we have sufficient technical information about the Maxthon browser in order for us to be able to be certain whether or not NVDA can improve support for this browser?

**Comment by leonardder** [comment]
Even though NVDA supports webkit to some extend, Safari for Windows has always been quite inaccessible from what I recall. Having said that, I think NVDA is doing a good job in supporting the four major browsers on the market. In my opinion, at least from NV Access we can't expect that they invest time in supporting a browser that is only used by a small group of people. So, even this could be fixed from a developers perspective, I'm yet leaning towards a won't fix.

**Comment by feerrenrut** [comment]
There isn't really sufficient technical information present, this would require some investigation. I agree with @leonardder that implementing this would not have sufficient impact to our user base to warrant the time spent by NV Access. There is also the potential for significant maintenance cost. Closing as won't fix.
