### ISSUE TITLE
NVDA announces "not selected" after each list item in any combo box in MS Word such as in customize dialog.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3046]
**Reported by sumandogra on 2013-03-04 12:00**
MS Word 2010
NVDA announces “not selected” after announcing the list item name on navigating the items of combo boxes in the customize dialog.  This behaviour can be observed in many places.  One can observe the same behaviour in the table of contents dialog or insert charts dialog as well.  For example, the choose commands from combo box in the customize page of the options dialog.  Its an important page that can help users    to select the commands they want to work with in MS Word/MS Office   apps.
This piece of speech "not selected" is confusing and user may waste is time findidng out how to select the list item.
Steps to reproduce:
In MS Word, press ALT+F followed by T.
select  customize in categories.
TAB to choose commands from combo box. 
Use UP/DOWN ARROW to move in the list items.
NVDA announces the list item followed by “not selected”.
It is confusing.
This can be observed in other combos in the same dialog.  This can be observed in may other places in MS Word 2010, such as insert chart dialog.

**Comment by ehollig** [comment]
I am not able to replicate this using Word 2016. I am not sure if there would be a different experience using Word 2010. NVDA is able to read all list items in the "Customize Ribbon" option without saying "Not selected".

**Comment by Adriani90** [comment]
I cannot reproduce it in MS Word 2010 on Windows 8.1 with NVDA 2017.3.

**Comment by Adriani90** [comment]
@ehollig I think we can close this issue, since NVDA seems to work properly in this regard.

**Comment by ehollig** [comment]
Thank you @Adriani90 for your testing. Closing as worksforme
