### ISSUE TITLE
In Outlook, context menu items that have the submenus are not read with NVDA KEY+UP ARROW, instead NVDA announces "blank"

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3052]
**Reported by sumandogra on 2013-03-06 12:02**
Outlook 2010
The menu items of the context menu that have the submenus are not read with NVDA KEY+UP ARROW.  Instead NVDA announces “blank”.  One has to navigate away and come back to the menu item in order to know the menu item again.  This can be observed with follow up, quick steps etc.
Steps to reproduce:
1.  In a message folder, press Applications KEY.
2.  Move with UP/DOWN ARROW in the context menu.
3.  On the menu items that have the submenu items press NVDA KEY+UP ARROW.
4.  NVDA announces “blank”.  This is not observed with the menu items that do not have the submenus.

**Comment by ehollig** [comment]
Performing the steps described in https://github.com/nvaccess/nvda/issues/3052#issue-116034150, pressing NVDA+Up arrow or NVDA+Tab reads the menu item as expected in Outlook 2016.

**Comment by ehollig** [comment]
For me, using Outlook 2016, the menu items, "follow up" and "quick steps" both report that they have a submenu. Closing this as worksforme, but if someone can reproduce this issue on Outlook 2010, we can reopen this issue.
