### ISSUE TITLE
Error when trying to run IVONA Voices through NVDA. Also IVONA Voices are very sluggish.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3055]
**Reported by Brendon22 on 2013-03-07 07:32**
Hello,
When trying to run some of the IVONA  Voices  I will here the NVDA error sound, and all speech will cut out. Also the voices are really sluggish?

**Comment by ehollig** [comment]
As stated by @jcsteh in https://github.com/nvaccess/nvda/issues/3055#issuecomment-155305564 the sluggish of the voices are not of fault of NVDA. Also, without more information from the original author, we can not troubleshoot what are causing the errors. Closing
