### ISSUE TITLE
Firefox: Keyboard shortcuts in View -> Sidebar menu reported twice

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3057]
**Reported by sumandogra on 2013-03-07 11:44**
Firefox 19.0

The keyboard shortcuts of the submenu commands are announced twice in the menus of the Firefox.
Steps to reproduce:
1.  Press ALT to go to the menu bar in Firefox.
2.  Go to the view menu>sidebar menu>bookmarks.
3.  The keyboard shortcut is announced twice.

**Comment by Adriani90** [comment]
Testing with NVDA 2018.4 Beta 2 on Fiferfox 63.0.3 on Windows 10 last Update, I cannot reproduce this issue.

**Comment by lukaszgo1** [comment]
@Adriani90 I am still able to reproduce it with Nightly 65 on Windows 7 by following the STR given above.  cc @jcsteh

**Comment by lukaszgo1** [comment]
@Adriani90 wrote:
> 
> 
> @lukaszgo1 I found out how to reproduce and also how to solve it:
> To solve it, go to NVDA menu / preferences / settings / object presentation and disable "report object shortcuts".
> Be sure that you create a profile for Firefox first and that you are in the Firefox window when changing this setting.
> Obviously Firefox already provides this reporting feature natively and you don't need to enable it extra in NVDA.

It is not a fix, but rather work around of bug in Firefox.

**Comment by Adriani90** [comment]
Maybe someone can report this bug to firefox. If I find some time I can do it tomorrow or so.

 

 

Von: Łukasz Golonka <notifications@github.com> 
Gesendet: Mittwoch, 28. November 2018 00:33
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Firefox: Keyboard shortcuts in View -> Sidebar menu reported twice (#3057)

 

@Adriani90 <https://github.com/Adriani90>  wrote:

@lukaszgo1 <https://github.com/lukaszgo1>  I found out how to reproduce and also how to solve it:
To solve it, go to NVDA menu / preferences / settings / object presentation and disable "report object shortcuts".
Be sure that you create a profile for Firefox first and that you are in the Firefox window when changing this setting.
Obviously Firefox already provides this reporting feature natively and you don't need to enable it extra in NVDA.

It is not a fix, but rather work around of bug in Firefox.

**Comment by jcsteh** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1510476

**Comment by jcsteh** [comment]
Now that a Mozilla bug has been filed, I don't think this is worth tracking for NVDA, as it's a fairly trivial issue. Closing.
