### ISSUE TITLE
on opening bookmarks dialog in MS Word, NVDA gives  irrelevant message about the errors in word file in the bookmark name edit field.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3058]
**Reported by sumandogra on 2013-03-07 11:47**
Word 2010

On opening the bookmarks dialog a message is read by NVDA which seems irrelevant while in the bookmark name edit field.  This irrelevant message speaks about the errors in the word file.  This message should not be given by NVDA in this dialog in this edit field.
Steps to reproduce:
Open a work file.
Press ALT, N, K to open bookmarks dialog.
The focus is in the bookmarks name edit field.
NVDA reads out a message that talks about the errors in the word file.  There are no errors in the word file.  This message is irrelevant in this place.

**Comment by bhavyashah** [comment]
@feerrenrut @Qchristensen Could you please be our sighted assistants for the diagnosis of this ticket as requested by @josephsl in https://github.com/nvaccess/nvda/issues/3058#issuecomment-155305585?

**Comment by feerrenrut** [comment]
I cant seem to reproduce the error text. Using Microsoft Word 2013 and NVDA `master-14289,6c85ce59`

### Steps I took:
1. Create a blank word document
2. Press `alt+n, k` causing the bookmarks window to open (from the insert panel)
3. Create several paragraphs
4. Open bookmarks window again.
5. Added a bookmark (by typing in the edit field, then pressing `alt+a`)
6. Open bookmarks window again.

NVDA did not report any errors with the word document.

**Comment by ehollig** [comment]
I performed the steps provided by @feerrenrut in https://github.com/nvaccess/nvda/issues/3058#issuecomment-322418555 in Word 2016 with no error text reported.
When taking a look at the patch provided, it appears the error is:
"Errors were detected in this file, but Word was able to open the file by making the repairs listed below.  Save the file to make the repairs permanent."
Doing a quick Google search, it appears that this error appears in heavily formatted files that have overlapping images in a Word document. I am closing as worksforme, but if someone else is able to reproduce in Word 2010 or can provide a working example, we can reopen this.
