### ISSUE TITLE
Suggestion for Minor Change to New Laptop Keyboard

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3059]
**Reported by miahtech on 2013-03-07 12:51**
While I was initially not happy with the new laptop scheme I've come to see the good points in it. One thing though I think should be looked at, changing the read current line command. Having to go back to l from the arrows every time is very annoying. Why not instead, use alt+NVDA+up arrow. It is open, not being used by anything else, and would be easy to do on a laptop. I think this would make more sense, and I suspect other users would agree. Something to at least consider.

**Comment by ehollig** [comment]
Intriguing, but I do not believe it is possible. As stated in https://github.com/nvaccess/nvda/issues/3059#issuecomment-155305593, the alt key would activate the menu bar, as the alt key itself is not intercepted by NVDA. CC @jcsteh

**Comment by jcsteh** [comment]
Actually, the alt and Windows keys can now be used as modifiers for NVDA commands thanks to #3472. That said, I'm reluctant to make this change at this stage, as the layout has been like this for years. Users can always bind the command themselves, though. Closing as won't fix.
