### ISSUE TITLE
Echoing by words does not work in akelpad

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#307]
**Reported by aleksey_s on 2009-04-23 14:57**
## steps to reproduce
- start akelpad
- type some word, "nvda" for example
- press spacebar
## actual results

NVDA speaks nothing
## expected results

NVDA must echo typed word "nvda"

==additional info ==
Akelpad version in question is 4.1.2

**Comment by leonardder** [comment]
Tempted towards closing this, as this ticket looks quite abandoned and this is most likely an issue in akelpad (see https://github.com/nvaccess/nvda/issues/307#issuecomment-155279868)

@pvagner, do you have anything to add here?

**Comment by leonardder** [comment]
Closing as needs external fix as proposed in https://github.com/nvaccess/nvda/issues/307#issuecomment-316015739. Feel free to request a reopen if desired.
