### ISSUE TITLE
Prevent reading of background live regions

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3070]
**Reported by jteh on 2013-03-09 22:06**
Currently, NVDA reports off-screen live regions. This is because we want to report regions which have been placed off-screen so they are only read by screen readers. Unfortunately, content in background tabs is also marked off-screen. We can't tell the difference in an efficient, standard way. However, we definitely shouldn't be reading live regions in the background.

**Comment by Adriani90** [comment]
@jcsteh, @michaelDCurran this is a very annoying issue I have since my company implemented a share point solution. Lots of websites have such live regions which are bein reported even when i switch to another window. A solution for this issue would be indeed very welcome. Thank you.

**Comment by jcsteh** [comment]
> Lots of websites have such live regions which are bein reported even when i switch to another window.

Just to clarify, do you mean switch to another window or another tab? If you switch to another window, live regions in other windows shouldn't be reported even now. Live regions in background tabs in the same window will get reported, however. I confirmed this with the following test case:

`data:text/html,<div id="live" aria-live="polite"></div><script>let count = 0; function update() { live.textContent = count++; setTimeout(update, 1000); } update();</script>`

This updates a live region with a counter every second. If I switch tabs, I still hear it. If i switch windows, however, I do not.

**Comment by Adriani90** [comment]
Hi Jamie,

 

so in my case with share point it is also reported when I change the window. I have also created an issue which might be a duplicate but I am not sure. This is #7743.

 

 

Von: James Teh <notifications@github.com> 
Gesendet: Dienstag, 27. November 2018 23:08
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Prevent reading of background live regions (#3070)

 

Lots of websites have such live regions which are bein reported even when i switch to another window.

Just to clarify, do you mean switch to another window or another tab? If you switch to another window, live regions in other windows shouldn't be reported even now. Live regions in background tabs in the same window will get reported, however. I confirmed this with the following test case:

data:text/html,<div id="live" aria-live="polite"></div><script>let count = 0; function update() { live.textContent = count++; setTimeout(update, 1000); } update();</script>

This updates a live region with a counter every second. If I switch tabs, I still hear it. If i switch windows, however, I do not.

**Comment by jcsteh** [comment]
With SharePoint, do you see this issue in Firefox when switching windows? I
should have clarified that I was referring to Firefox (and Chrome uses the
same code so it should be the same). I'm not sure about IE.

**Comment by Adriani90** [comment]
@jcsteh, in Firefox I have this issue only for Background Tabs. In IE it occurs also when switching to other Windows.

**Comment by Adriani90** [comment]
@jcsteh, in issue #7743 I have found out that this issue might be related to the Java plugin. But this might be clear anyway because mostly dynamic Content on Websites is based on Java, at least this is my understanding.

**Comment by jcsteh** [comment]
I think you might be confusing Java with Javascript. Java on the web is quite rare now, to the point where I haven't encountered something that needed the Java plugin on the web in literally years. Javascript, on the other hand, is the scripting language of the web and is used everywhere. I'd say that particular issue might be related to Java, but the more general one (and certainly SharePoint) isn't.

**Comment by Adriani90** [comment]
Yes, Java and Java script are two things I often cannot really distinguish, I have to digg into this deeper to understand how it really works. Do you think there is something which can be solved from NVDA's side? Or is this an issue which has to be solved on browser side first? Because the strange Thing is that NVDA reports that Content iven if Report dynamic Content is disabled in NVDA's Settings. So I guess this could be caused by some native behaviors in the browser itself.

**Comment by Adriani90** [comment]
@jcste should we close this in favor of #1318 and #7743? Those issues contain many examples and the discussion goes a bit further. #1318 covers firefox and #7743 is about different browsers but especially IE.

**Comment by jcsteh** [comment]
Closing in favour of #1318, yes. However, I'll adjust the title of #1318, since it's fairly confusing right now.
