### ISSUE TITLE
Copy To Clipboard Failing In Firefox E-mail, HTML View

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3072]
**Reported by jhomme on 2013-03-10 16:28**
In my GMail in Firefox, very often, I find some text, press NVDA + F9, go to the last character of a piece of text, press NVDA + F10, and when I read the clipboard with NVDA + C, there is only one character on the clipboard.

**Comment by jcsteh** [comment]
I can't reproduce this either; it works as expected. This possibly got fixed as part of #6070.
