### ISSUE TITLE
XFA PDF Listbox reading Id of item not the display text

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3078]
**Reported by BR001 on 2013-03-12 06:52**
In an Adobe PDF XFA document containing a ListBox control with a selected value NVDA reads the Id of the item in the ListBox not the Display Text of the item.

If there is no value selected when entering the field then NVDA works as expected.

**Comment by leonardder** [comment]
It would help if we had an example of such a document to investigate.

@BR001: If you are the BR001 who opened this issue, would you be able to provide details on the current status of this issue?

**Comment by leonardder** [comment]
@JCSTeh: I remember you tackled another XFA pdf issue in the recent past. Do you have the chance to check this one?

**Comment by jcsteh** [comment]
I just tested an XFA PDF with both a combo box and a list box (though I don't know how these are mapped internally). While the selected item wasn't rendered in browse mode, I wasn't seeing any id either, and I was seeing the display text in focus mode. It's difficult to know exactly what I'm looking for without a test case and exact steps and we can't contact the reporter, so closing.
