### ISSUE TITLE
In Internet Explorer the graphical links are repeated twice and are listed with twice in the elements list.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3080]
**Reported by sumandogra on 2013-03-12 07:20**
In internet explorer The graphical links are announced twice and are listed twice in the elements list.     This takes some more time of a user who is trying to navigate through a web page quickly.
Steps to reproduce:
1.  Open a web page that has graphical links.  For example, open www.yahoo.com
2.  Navigate around the page.  There are certain links that will be repeated twice.
3.  Press G to quickly move to a graphical link.
4.  Press NVDA KEY+F7.  Here again such links are listed with words repeated twice.

**Comment by ehollig** [comment]
I do not find any repetition using the above steps with Internet Explorer 11 and Windows 10

**Comment by leonardder** [comment]
I'm closing this as invalid. This is or was probably related to bad web programming. If there are duplicates in the source of the website, there's nothing we could or should do about it.

**Comment by leonardder** [comment]
Additional note, I recall JAWS has a feature to explicitly filter duplicated links, but I think this is not something that should go in NVDA core. Duplicate links are there for a reason, and if they are there for no valid reason, that's not something a screen reader should bother with.
