### ISSUE TITLE
Repeating the previous List item before announcing the current item in some programs

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3081]
**Reported by NVDA-Fanatic on 2013-03-12 15:54**
While NVDA reports well some highlighted list items in Windows Explorer and some file managers, I find that in some programs like RSSOwl, for example, it announces the previous item before announcing the currently highlighted list item. Programs where this was experienced is RSSOwl, a JAVA-based application for subscribing and reading RSS feeds and UTorrent, a torrent client.

**Comment by bhavyashah** [comment]
@jcsteh Could you please take a look at the information provided in https://github.com/nvaccess/nvda/issues/3081#issuecomment-155305755 and clarify whether this seems to be an issue that needs case-by-case fixes or if a more universal solution is available.

**Comment by Adriani90** [comment]
@NVDA-Fanatic is this still reproducible? I guess it could also be related to the java access bridge and its way to deliver information to screen readers.
@jcsteh, @derekriemer your ghoughts are very apprecaited. Maybe this has improved after implementation of checable list PR.

**Comment by Adriani90** [comment]
We do not have any updates on this since years and I didn't hear further reports on this problem from other users. If you have a certain case which can be reproduced, please comment on this issue and we can reopen it. I am closing this as abandoned since we lost contact to the initial author.

**Comment by leonardder** [comment]
I've seen this recently in the sessions list of FileZilla.

**Comment by Brian1Gaff** [comment]
Hmm, I still see that explorer in windows 7 can be very laggy, ie move down 
a list of audio files in explorer, hear one you want and hit enter and the 
media player will probably play a different file altogether.
 Similar things occur if, say you open a dropbox folder from the desktop and 
nothing appears to happen, indeed when cursoring it seems you are on the 
destop, but an alt tab shows that the folder did in fact open, but nvda 
missed it.

Web browser, one can normally get it to read  automatically but sometimes 
you need to refresh the page or alt tab away and back.
 Tis machine is not to slouch, being a four cor i5 at 3.2mhz with the speed 
made faster  during idle to stop lag.

I'm thinking the underlying  story here is retention of old data while not 
always getting the new data fast enough.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Adriani90** [comment]
I tested in uTorrent 3.5.5 with NVDA and the issue is reproducible. I think this might be java specific.

**Comment by Adriani90** [comment]
@feerrenrut maybe also something to fix via cancelable speech?

**Comment by Adriani90** [comment]
I cannot reproduce this anymore in utorrent 3.6.0 with NvDA 2022.4. Note that I have installed the java access bridge for 32 and 64 bit, and both are enabled via jabswitch -enable command.

I am closing this for now, please comment again if you see any cases which we can test this issue on.
