### ISSUE TITLE
XFA PDF CheckBox checked state not reported

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3083]
**Reported by BR001 on 2013-03-13 04:22**
In an Adobe PDF XFA document containing a CheckBox control which has been selected NVDA announces the state as unchecked.

**Comment by leonardder** [comment]
It would help if there was an example document we could try to reproduce this.

**Comment by jcsteh** [comment]
Can't reproduce with an XFA document I have here (can't share the test case unfortunately). No way to contact original reporter, so closing.
