### ISSUE TITLE
Routing off with Pacmate Display and Routing Keys

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3087]
**Reported by miahtech on 2013-03-15 12:45**
With certain words, the routing key behavior is acting very odd with certain words. I'm using the pacmate 40 display, with the Unified English Braille Grade 2 table, expand word turned off, curser blink set to 0, tethered to focus, read by paragraph  off, and avoid splitting words on.
Here are 2 examples I've come across so far:
pree: if you route to the p or the R, it drops you on the first e. 

lefthand: If you try to route to the h or the and sign, it puts the cursor on the t.

Not sure what's causing this, but it's a tad annoying for my editing work here. :)

**Comment by leonardder** [comment]
This sounds similar to #3230, the author of that issue also used UEB grade 2.

Honestly, I'm tempted to close this, as the Pacmate is getting quite old and it is mainly used as a stand alone note taker. 

Any UEB Grade2 user who can reproduce this with another display? I will close this at the end of next week if we haven't received additional comments.

**Comment by jcsteh** [comment]
This is the same reporter as #3230.

**Comment by dkager** [comment]
Note that this is likely not an issue with the PACmate or its driver, but with liblouis.

**Comment by leonardder** [comment]
I think @Dkager is correct. It is probably related to #7301. Closing.
