### ISSUE TITLE
Support PCMan X, (a free cross-platform BBS client)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3089]
**Reported by surfer0627 on 2013-03-17 11:53**
Could NVDA support PCMan X, (a free cross-platform BBS client)?
Or NVDA developers could recommend other BBS client software for users.

I hope to use this software to login bbs platform, read articles.

Thank you.

Information 
Download software PCMan X 0.1.7.6 
(I could not find the English Version. This is traditional Chinese version.)
https://dl.dropbox.com/u/90288447/PCManX.rar

Source Code:
PCManX-src-0.1.7.6.tar.gz
http://ignum.dl.sourceforge.net/project/pcmanx/PCMan%20X%20Source%20Code/PCMan%20X%200.1.7.6%20Source%20Code/PCManX-src-0.1.7.6.tar.gz

PCManX-src-0.1.7.6.zip
http://ignum.dl.sourceforge.net/project/pcmanx/PCMan%20X%20Source%20Code/PCMan%20X%200.1.7.6%20Source%20Code/PCManX-src-0.1.7.6.zip

I'm not sure the difference between file one and two.

**Comment by ehollig** [comment]
Closing because of https://github.com/nvaccess/nvda/issues/3089#issuecomment-155305803. If more information can be provided, this can be reopened.
