### ISSUE TITLE
NVDA not rendering some contents in browse mode with firefox.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3111]
**Reported by ateu on 2013-03-26 14:12**
I've tested with chrome and Iexplorer, and the problem does not appears.

Access this link:

http://wol.jw.org/pt/wol/lv/r5/lp-t/0/19378

The content is in Portuguese, so ignore it.

Which matter is that there is a menu, and after it, a list of 139 items, and this list is not showed with firefox.

**Comment by derekriemer** [comment]
Hi,
Another case of this is the table of contents on the [html5.1 specification](https://www.w3.org/TR/2016/CR-html51-20160621/).
I believe this is a bug. I'm not sure how NVDA should reference this, maybe a table of contents region, or treat it as an embedded section I.E. you press enter from browse mode to enter it.
https://www.w3.org/TR/wai-aria/roles#directory

**Comment by derekriemer** [comment]
I can't reproduce this anymore. I think it got fixed.
