### ISSUE TITLE
new ESpeak voice Variant

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3112]
**Reported by brandon15 on 2013-03-26 23:20**
adds a new variant to NVDA's ESpeak voice synthesizer, a deep male voice.

**Comment by ehollig** [comment]
Any new variants or voices for ESpeak should be submitted on the [ESpeak Issue Github page](https://github.com/espeak-ng/espeak-ng/issues/new).
@jcsteh it may be helpful to attach the file to this ticket so that it may be sent to the ESpeak tracker.
