### ISSUE TITLE
Better search of text in MS Office

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3120]
**Reported by bvivi on 2013-04-01 07:31**
In MS Office when searching for text (Ctrl + Shit + T) NVDA when it finds a word tells me only the button "Find Next", but it would be nice if they read the line found if you tulizza word or the contents of the cell in the case it is in Excel.
This would allow for the search to get an idea of the found text without entering and leaving the search box.

Tested with MS Office 2003

**Comment by bhavyashah** [comment]
Duplicate of #4446

**Comment by ehollig** [comment]
Closing in favor of #4446
