### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3123]
**Reported by joshknnd1982 on 2013-04-02 01:35**
I would like to see someday ESpeak support the hebrew, and Arabic and Japanese languages either by itself or through use of an mbrola voice so hebrew arabic and japanese speakers will have a tts language option.

**Comment by ehollig** [comment]
ESpeak does support the Arabic and Japanese languages as an option in the voice settings dialog.
For suggestions on new voices or languages, including Hebrew, please create a new issue on the [ESpeak NG Github page](https://github.com/rhdunn/espeak/issues/new).
