### ISSUE TITLE
eOn opening untitled new dialogs in Outlook 2010 such as new contact/appointment dialogs, some irrelevant speech is given by NVDA.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3133]
**Reported by sumandogra on 2013-04-06 04:24**
Outlook 2010

On opening untitled new dialogs such as new contact window with CTRL+SHIFT+C, or, new appointment dialog with CTRL+SHIFT+A, NVDA gives some extraneous speech starting from “MS Work Pane…” afterwards it starts reading the dialog from some field randomly,  for example, new contact dialog it starts the dialog reading from “file as” field.  It’s confusing.
Steps to reproduce:
1.  Press CTRL+SHIFT+C to open untitled contact dialog.
2.  NVDA starts with its speech.
3.  It first announces the title of the dialog and then gives some irrelevant speech starting from “mso work pane….”, and then it reads the complete dialog and then announces the field in focus.
4.  This can be observed with other untitled new dialogs such as new appointment dialog (CTRL+SHIFT+A).

**Comment by bhavyashah** [comment]
@josephsl's https://github.com/nvaccess/nvda/issues/3133#issuecomment-155306078 seems to invalidate this ticket. Time to close? @ehollig

**Comment by ehollig** [comment]
Closing because of https://github.com/nvaccess/nvda/issues/3133#issuecomment-155306078
