### ISSUE TITLE
Braillesense u2: a lot of shortcuts don't work

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3157]
**Reported by PZajda on 2013-04-16 10:05**
Braille input work, but I have all these shortcut keys, and none of them work for me.

Example, F2, F3 et F4 (those around the space bar called Advance 2, Advance 3 and Advance 4). 
Advance 2 should emulate Alt, Advance  3 Tab and Advance  4 Escape.

Combinated shortcuts don't work too:
- Space + Advance 3
- Space+dot1+dot8
- Space+Dot1+Dot4+Dot8
- Space+Dot1+Dot2+Dot3+Dot6+Dot8
- Space+Dot1+Dot3+Dot4+Dot6+Dot8

I cannot test anymore by myself, but a French vendor reported me these problem.

**Comment by cskchao** [comment]
It appears that much (if not all ) commands work when NVDA starts. However, functionality becomes lost along the way when using the device normally. One trigger I've been able to duplicate several times is with chorded commands. If one presses space + l and later space + dots 456, or the other way around, some commands involving dot 4 no longer work. Interestingly, this also seems to present itself in input help mode. Pressing space with dot 4 causes NVDA to announce the keys being pressed, but will no longer announce the description of what the command actually does.

**Comment by leonardder** [comment]
Interesting issue. I might be able to test this with a perkins in a short while.

@@cskchao: would you be able to test [this](https://github.com/nvaccess/nvda/files/329992/HanSoneConnect-NVDA.zip) new driver file? I'd be great if you could replace the dll in C:\Program Files (x86)\NVDA\brailleDisplayDrivers\hims with the dll in this zip file. Please let me know whether this fixes your issues or improves anything.

**Comment by leonardder** [comment]
I've tried these issues and was unable to reproduce any of them. Would anyone owning a Braille Sense mind to post a str? Furthermore, I'd appreciate it if you guys could try key combinations in keyboard help and see whether all the keys are detected properly.

**Comment by cskchao** [comment]
I replaced the dll in my portable copy and have been using the Braille Sense connected via USB. I'm still experiencing the issues previously mentioned here. For example, entering input help and pressing space with dot 4, the key combination is spoken, followed by "Emulates pressing downArrow on the system keyboard." After pressing space with dots 4-5-6, followed by space with dots 1-2-3, the descriptions for many commands containing space with dot 4 are no longer spoken. The one exception I can find is space with dots 4-5-6 which appears to behave normally. Even in this multi line edit field, space with dot 1 works as expected, but space with dot 4 simply interrupts speech and normal behavior is  not restored until NVDA is restarted.
Log:
INFO - __main__ (12:29:32):
Starting NVDA
INFO - core.main (12:29:32):
Config dir: E:\nvda\userConfig
INFO - core.main (12:29:32):
NVDA version 2016.2.1
INFO - core.main (12:29:32):
Using Windows version 6.1.7601 service pack 1 workstation
INFO - core.main (12:29:32):
Using Python version 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
INFO - core.main (12:29:32):
Using comtypes version 0.6.2
INFO - synthDrivers.espeak.SynthDriver.__init__ (12:29:33):
Using eSpeak version 1.48.15  16.Apr.15
INFO - synthDriverHandler.setSynth (12:29:33):
Loaded synthDriver espeak
INFO - core.main (12:29:33):
Using wx version 3.0.2.0 msw (classic)
INFO - braille.initialize (12:29:33):
Using liblouis version 2.6.5
INFO - brailleDisplayDrivers.hims.BrailleDisplayDriver.__init__ (12:29:35):
Braille Sense (4 scrolls mode) device found
INFO - braille.BrailleHandler.setDisplayByName (12:29:35):
Loaded braille display driver hims, current display has 32 cells.
INFO - brailleInput.initialize (12:29:35):
Braille input initialized
INFO - core.main (12:29:36):
NVDA initialized
INFO - inputCore.InputManager._handleInputHelp (12:30:29):
Input help: gesture br(hims):space+dot4, bound to script kb:downArrow
INFO - inputCore.InputManager._handleInputHelp (12:30:31):
Input help: gesture kb(desktop):NVDA
INFO - inputCore.InputManager._handleInputHelp (12:30:31):
Input help: gesture kb(desktop):NVDA+1, bound to script toggleInputHelp on globalCommands.GlobalCommands
INFO - inputCore.InputManager._handleInputHelp (12:31:10):
Input help: gesture br(hims):dot1+space, bound to script kb:upArrow
INFO - inputCore.InputManager._handleInputHelp (12:31:12):
Input help: gesture br(hims):space+dot4, bound to script kb:downArrow
INFO - inputCore.InputManager._handleInputHelp (12:31:16):
Input help: gesture br(hims):space+dot6+dot5+dot4, bound to script kb:control+end
INFO - inputCore.InputManager._handleInputHelp (12:31:18):
Input help: gesture br(hims):dot3+dot2+dot1+space, bound to script kb:control+home
INFO - inputCore.InputManager._handleInputHelp (12:31:21):
Input help: gesture br(hims):dot4+space
INFO - inputCore.InputManager._handleInputHelp (12:31:23):
Input help: gesture br(hims):dot1+space, bound to script kb:upArrow
INFO - inputCore.InputManager._handleInputHelp (12:31:26):
Input help: gesture kb(desktop):NVDA
INFO - inputCore.InputManager._handleInputHelp (12:31:26):
Input help: gesture kb(desktop):NVDA+1, bound to script toggleInputHelp on globalCommands.GlobalCommands

**Comment by leonardder** [comment]
It seems to have to do with the order in which the keys are detected. 
Since only NVDA seems to fail, it either is a problem in the dll or in 
NVDA itself.
     Input help: gesture br(hims):space+dot4, bound to script kb:downArrow
     Input help: gesture br(hims):dot4+space

**Comment by cskchao** [comment]
Indeed - this was the assumption under which I was also operating. To that end, is it worthwhile to test for this issue on other devices? I can perhaps see about borrowing a Braille Edge for a short time.

**Comment by leonardder** [comment]
I have a Braille Edge at the @BabbageCom office, so I might be able to test this very soon. I will also see whether I can poke Hims about this.

**Comment by leonardder** [comment]
I have a Braille Edge at the @BabbageCom office, so I might be able to test this in a while. I will also see whether I can poke Hims about this issue.

**Comment by leonardder** [comment]
Comfirmed for the Braille Edge as well.

**Comment by jcsteh** [comment]
After some investigation, I determined that the issue with keys behaving differently depending on the order in which they are detected is caused by a new core issue I just filed: #6945.

**Comment by jcsteh** [comment]
P2 because this causes intermittent failure of braille commands for users of HIMS displays.

**Comment by jcsteh** [comment]
I've hopefully fixed the space+dot4 issue. The fix is currently available in NVDA "next" snapshots. It'd be great if someone experiencing this could confirm whether the fix works. Thanks.

**Comment by leonardder** [comment]
@cskchao: Could you confirm whether this works now, so we can close this issue?
