### ISSUE TITLE
MSHTML: Title attribute not reported when using quick navigation or tabbing in browse mode

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3158]
**Reported by nmatthews on 2013-04-16 20:37**
This is likely related to #1354. 

When both the aria-label and title attributes are provided on buttons, NVDA reads the aria-label attribute, the identifier button, followed by the title attribute.

For buttons with an image content, the title attribute is used as a tooltip for the button for sighted users.  

A similar example would be the following:
http://pauljadam.com/demos/title-aria-label.html

If both of these attributes are included, it seems that they often contain similar or identical text. When looking at a button role, without the aria-label attribute, voiceover on the Mac only reports a "button", due to the different handling of the title attribute. Providing both attributes however, leaves NVDA and Firefox reading both attributes. 

When using an element with inner text, 

```
<button title="foo title" aria-label="foo label">foo content</button>
```

In firefox, this element reads "foo content button foo title", and the aria-label attribute is ignored entirely.
In IE, this element reads "foo label button". 

Why the different behaviour? I really expected aria-label to be picked up in Firefox, and I would have preferred that it ignore the title attribute, similar to IE. 

**Blocking #3711**

**Comment by bhavyashah** [comment]
@jcsteh While this issue now only covers the title attribute in IE, does it affect later versions such as IE 11 too? If so, feel free to assign this a priority as deemed appropriate.

**Comment by jcsteh** [comment]
It looks like IE 11 does support aria-label, so title gets correctly mapped to accDescription and this therefore gets reported properly in focus mode or when pressing NVDA+tab. However, we don't map accDescription to the description attribute in the vbuf backend, so this doesn't get reported when using quick navigation, etc.

Low priority because it's IE, but this shouldn't be too hard to fix.

**Comment by Adriani90** [comment]
@nmatthews is this issue still reproducible?

**Comment by Adriani90** [comment]
Testing with NVDA 2019.1.1, Chrome 74, Firefox 66.0.3 and IE11, the behavior is exactly the same in all three browsers. When navigating in browse mode or focus mode, NVDA reports "button foo label". When pressing nvda+tab, NVDA reports "foo label button focused foo title".
I guess Jamie already answered the question raised in the issue description. As of now I think it is safe to close this as works for me. Please comment on it if you are still having questions.
