### ISSUE TITLE
Swahili language addition

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3160]
**Reported by jacobchawala on 2013-04-17 05:40**
Windows has recognized Swahili language in its programs in such a way that it has Swahili lip setups for windows XP, Vista, 7, 8, and Swahili Microsoft office. Swahili language is spoken by more than 100 million people in the world. Because of its importance, I think we should add the Swahili language among other languages in NVDA. most of Swahili speakers with visual impairment who are computer literate, NVDA is their primary screen reader. There is a Swahili voice in the voice settings but there is no Swahili language in the general settings.

**Comment by ehollig** [comment]
While having Swahili as a supported language of NVDA would be nice, we need a volunteer that can do the Swahili localization. Closing as we are unable to contact the original poster for additional information. CC @josephsl to forward to the translations list to see if there are any Swahili speakers that may be able to help.

**Comment by josephsl** [comment]
Hi, shall be done today.
