### ISSUE TITLE
nvda settings randomly resetting

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3165]
**Reported by camlorn on 2013-04-17 13:24**
This has happened twice in 3 days.  Nvda will randomly forget _all_ of my settings, including that nvda has been run on my computer before, re displaying the start up dialogs and resetting everything.  Obviously, this is...problematic.
What do I need to do, besides (if I can) comment with how to reliably reproduce it?
The only changes in my setup since this has started happening are the enabling of the us-dvorak keyboard layout.
I'm on Version: master-9098,fb41602, and continually update as soon as new development snapshots come out.  I first saw this on Monday the 15th.
The easiest fix would probably be making a backup of all settings at startup, of some sort.  I'm not really sure why this is happening, but both times were while the system was being very sluggish--maybe some sort of interrupted file writing?
**Blocked by #667**

**Comment by bramd** [comment]
I've seen this issue happen a few times recently on a fairly new laptop of a friend running Windows 10. It seems quite easy to implement this and I would be glad to do so.

**Comment by derekriemer** [comment]
Please produce steps to reproduce the

Sent from my heavily encrypted iPhone.
Please disregard errors as this is a smaller device.

**Comment by bramd** [comment]
@derekriemer So far, I was unable to reproduce this reliably. It just sometimes happened after a shutdown/reboot of the computer.

**Comment by Brian1Gaff** [comment]
Are you sure that the computer is not trying to recover from an error, it 
has at least once happened to meas it has restored to what it thought was a 
last known good start up.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by jcsteh** [comment]
Making this a p1. While it doesn't cause a crash, the configuration getting corrupted and reset is very bad for the user when it happens and we've had quite a few reports of it now.

@feerrenrut, would you mind taking care of this? @bramd kindly provided a PR (#5916) to fix this, but unfortunately, I didn't notice he had addressed my review comments and now we've broken it with recent config system changes. I think much of the PR is still usable though. See also https://github.com/nvaccess/nvda/issues/3165#issuecomment-155306321 for background.

**Comment by PratikP1** [comment]
Thank you. This would be a greatly welcomed fix. See my request in #6969 as well.
