### ISSUE TITLE
Implement an option on braille preferences to not interrupt speech when pressing braille keys

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3167]
**Reported by sergioneves on 2013-04-17 16:33**
I'm using NVDA (last development version) and Focus 40 braille display.
Imagine the following situation:
An user is reading some kind of document. When he presses some key on braille display, such as a panning button or a routing button, he would like that the remaining portion of the line is announced by the synthesizer, that is, pressing a braille display key doesn't interrupt the synthesizer.
Why? Because I think reading in braille and hearing the same thing can be considered two independent tasks and one of them may not interfer on each other.
Imagine, for example, a line of text with its length larger than the length of braille display.
This line has an word the user doesn't know, and the only thing he wants to do at this line is to hear all the line and to inspect how the word is written. The word ends at a position beyond the length of the braille display.
Thus, to catch all the word, the user has to press a panning button at least once. If the synthesizer stops speaking, the user loses the context of what he is reading and, either he continues to read in braille what the synthesizer hasn't spoken, or he has to touch the keyboard to ask that the synthesizer reads the line to him.
In sort, he loses some time performing this.
My suggestion is to implement a braille setting (checkbox) named "don't interrupt speech when pressing braille display keys".

**Comment by surfer0627** [comment]
Related issue #2124.

**Comment by dkager** [comment]
Yes, duplicate of #2124.
