### ISSUE TITLE
MS Word: press home, braille cursor could not move to the first cell

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3168]
**Reported by surfer0627 on 2013-04-18 01:59**
Braille Settings
Braille Tethered to review.

Please use the attached file to test the case.

In some cases, when user press home to move the cursor to the first cell, and the braille cursor stay at the different cell.

line no.        cell no.
third           7
fourth          5
eighth          2
eleventh        20
twelveth        9
fourteenth      16
fifteenth       19
eighteenth      6

If Braille Tethered to focus, braille cursor will correctly move to the first cell.
But it will have one-second delay, after press arrow down or up.

**Comment by Adriani90** [comment]
@surfer0627 is this still an issue for you? Does this occur also when tetering the braille display to automatic?

**Comment by Adriani90** [comment]
@bdorer can you reproduce this maybe?

**Comment by bdorer** [comment]
hmm, I don't understand the issue. The user tethers braille to review but mooves system cursor. If review follows system cursor is on, review should follow system cursor and that's the case for me. If review follows system cursor is off review cursor doesn't follow system cursor and that's expected. @surfer0627 should provide exact steps to reproduce and what hapens and what is expected.

**Comment by bdorer** [comment]
Furthermore I arrowed to all noted possitions and the first coursor 
routing key worked as expectted. Used Word 2013. Voting as closing as 
worksforme.

Am 06.12.2018 um 00:07 schrieb Adriani90:

**Comment by Adriani90** [comment]
As we didn't hear from the author since 5 years and @bdorer confirmed that it works as expected, I'll close this as works for me. We can reopen it if the issue comes up again.
