### ISSUE TITLE
Translating the word heredity

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3169]
**Reported by jacobchawala on 2013-04-18 05:57**
The word heredity is not pronounced well in this NVDA version. Can we kindly make it pronounce well?

**Comment by ehollig** [comment]
No follow up from the original author to the question in https://github.com/nvaccess/nvda/issues/3169#issuecomment-155306345. If the synthesizer that was used was ESpeak, you may want to create an issue on the [ESpeak Issue Github Tracker](https://github.com/espeak-ng/espeak-ng/issues/new). Closing, as we are unable to contact the original author.
