### ISSUE TITLE
NVDA with Espeak Switches To Another Language or dialect with the string "30th" (without the quotes)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3173]
**Reported by dgoldfield on 2013-04-19 17:25**
I am using Espeak with the US English variant with the Male3 voice.  Language and dialect switching is disabled in my preferences.  NVDA seems to read the string "30th" in some other dialect, as in April 30th.  This occurs with other voices as well using the US English variant.

**Comment by jcsteh** [comment]
@dgoldfield, I'm assuming this has been fixed for some time now. Can you please confirm?

**Comment by jcsteh** [comment]
According to the above comment, this has been fixed for some time. @dgoldfield, please comment if this is not the case.

**Comment by dgoldfield** [comment]
Yes, this is fixed.
