### ISSUE TITLE
Alert notification are not spoken in IE10.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3176]
**Reported by Harich on 2013-04-20 17:28**
Notification alerts are not being spoken in IE10 after a file download is complete. That is, the NVDA reads the notification as you try to download a file, however, it does not so when the download is completed. I'm running Win-8 64 bit OS.

**Comment by leonardder** [comment]
Is someone able to reproduce this with IE11? Honestly, I didn't even know that there was such a notification. Are we really sure there is a notification expected?

**Comment by Adriani90** [comment]
I am not able to reproduce it in Windows 8 64bit with IE11 and NVDA 2017.3.

**Comment by ehollig** [comment]
I am not able to reproduce this in IE 11 using NVDA Alpha and downloading a file. I am also unsure if there is even a notification presented in IE once a file is complete. I believe the notification disappears. Closing
