### ISSUE TITLE
NVDA not indicating selection in TED Notepad

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3178]
**Reported by camlorn on 2013-04-20 23:57**
I've been looking for a Programmers' editor for a bit now, and got a recommendation from another NVDA user for an editor called TED Notepad.  All appeared to be fine.  Then I selected some text.  Nothing from NVDA.  I asked NVDA for selection and it reported none.  Using my remaining vision, i was able to verify that the text is in fact selected, and NVDA is picking up the color change for selected text.  It's just not picking up the selection.
The interesting thing is that me and the person who recommended this to me are both on the latest developer snapshot as of this writing and the same OS--windows 7 64-bit--and selecting is working fine for him in the same editor.  NVDA picks it up as normal.
I've seen similar behavior in other editors: everything works fine except for selection, which NVDA refuses to indicate.  I assumed that this was the editor not exposing the information.  now, I'm not so sure and am leaning towards a possible bug in NVDA or oddity of my configuration.  Obviously this is problematic, as it's limiting my choice of available editors.  Between this and #885, I am quickly running out of options for good text editors that work fully with NVDA.
version: master-9133,0557983 as of this writing.

**Comment by bhavyashah** [comment]
@jcsteh Could you please clarify if your https://github.com/nvaccess/nvda/issues/3178#issuecomment-155306421 implies that this ticket should be closed as a cantfix and partial duplicate?

**Comment by jcsteh** [comment]
#770 is now fixed and should have in turn fixed this. However, given the inherent inconsistency/unreliability of display hooking, we can't be certain as to whether it actually fixes the problem for this particular editor without specific testing.

@Camlorn, is TED Notepad something you still care about or should we close this?

**Comment by bhavyashah** [comment]
This is a friendly reminder for @camlorn to please respond to @jcsteh's https://github.com/nvaccess/nvda/issues/3178#issuecomment-322602056.

**Comment by Adriani90** [comment]
@briang1, @brian1gaf, @camlorn is this issue still reproducible with last version of NVDA and last editor version?

**Comment by ehollig** [comment]
Closing, as we seem to have  lost contact with the original author of this issue.
