### ISSUE TITLE
Portable NVDA not working in several apps

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3180]
**Reported by andrewd on 2013-04-22 02:30**
As well as the Audacity issue I noted earlier today, portable NVDA is not working at all in NoteTab or Firefox.  I have tested on two machines, but I do have an installed version on each machine which may be upsetting things.  The issue goes back to 2012.3 - makes me wonder why I hadn't noticed earlier.

**Comment by ehollig** [comment]
this sounds to be an isolated issue to the users machine indicated in https://github.com/nvaccess/nvda/issues/3180#issuecomment-155306433
