### ISSUE TITLE
Modifying text in wordpad crashes NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3182]
**Reported by tspivey on 2013-04-22 10:00**
1. Open a large (500k or so) text file in wordpad.
2. Delete a character or type something.

NVDA will crash.

**Comment by bhavyashah** [comment]
@tspivy @josephsl and others: Is this crash still reproducible? Since Tyler notes in https://github.com/nvaccess/nvda/issues/3182#issuecomment-155306455 that disabling UIA eliminates the crash, UIA may be a causative factor of the crash. Thoughts? @jcsteh

**Comment by Brian1Gaff** [comment]
I do still find that Wordpad can sometimes just give up in windows 7, the 
usual  thing of its stopped working let be  go and find etc. My solution to 
this has been to import the XP version of Wordpad, I'm afraid. The only 
other strange thing is some cut and pasted stuff from wordpad seems to end 
up pasted in Word as an object not text. Still trying to figure that one 
out. If you paste it to notpad then to word its fine, so has to be something 
in the formatting.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment]
I have opened a .docs file in Wordpad (2.4 MB) with 900 pages. It took about half a minute to open but I can edit anything into it without NVDA chrashing.
Tested with NVDA 2018.2.1 on Windows 10.

It can ofcourse depend on how powerful your PC is. But I don't see any NVDA bug here.

**Comment by ehollig** [comment]
Closing, as we have not had a report of this in several years. @tspivey,, if this is still reproducible, please open a new issue.
