### ISSUE TITLE
NVDA freezes while arrowing down on certain pages in Firefox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3185]
**Reported by ppatel on 2013-04-24 10:38**
On certain pages with what I suspect are Iframes, NVDA freezes when arrowing down the page. Switching to another window and returning to the window allows the user to move down the page once again. This appears to happen with iFrames. 

See the following example page to see this in action. http://allthingsd.com/20130423/galaxy-s-4-is-a-good-but-not-a-great-step-up/

I can provide additional examples if needed. The behavior in IE 9 and 10 is slightly different. When encountering these problematic areas, NVDA outputs the error double beep as if it has encountered an unrecognizable object. But the user is allowed to go past it if arrowing down unlike with Firefox.

**Comment by ehollig** [comment]
The URL provided appears not to load for me. If someone is able to provide another example where this issue exists, we can reopen this. Seeing we are unable to contact the original author of the issue, closing.
