### ISSUE TITLE
better support for editing characters in the middle of lines in command prompt/terminal

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3200]
**Reported by camlorn on 2013-05-04 20:49**
Currently, when editing any text in the middle of the line, both in terms of deleting with backspace and typing new characters, NVDA will read everything to the right of the cursor position.  It would be helpful if it didn't, as I wish to use VI and am frequently using ssh for website administration.

**Comment by leonardder** [comment]
cc @jcsteh @camlorn @josephsl 

I'm giving this a priority of 3, feel free to suggest otherwise.

**Comment by Adriani90** [comment]
@derekriemer are you thinking to extend your console timer add-on? Or is the add-on not further developed? Maybe a function for solving this issue could be added.
