### ISSUE TITLE
new variant for espeak

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3204]
**Reported by Animesh.mr on 2013-05-07 13:46**
hello all this is a new voice for espeak zac2 hope u all will like this

**Comment by ehollig** [comment]
For suggestions on new voices please create a new issue on the [ESpeak NG Github page](https://github.com/rhdunn/espeak/issues/new).
@jcsteh, it may be useful to attach the original file so that it can be forwarded on to the ESpeak tracker.
