### ISSUE TITLE
NVDA navigation in Internet Explorer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3207]
**Reported by svenvandewege on 2013-05-07 21:38**
Hello,

It would be nice if NVDA (both braille and speech) are announcing the name of an object on webpages after the name itself.

Now nvda is doing like this:

lnk  home
lnk  downloads
lnk  payment

it would be easier to read pages eespecially by speech when nvda is doing it like this:

home  lnk
downloads  lnk
payment  lnk

etc

Can this option be enabled in a later version of nvda???

**Comment by leonardder** [comment]
I think we can safely treat this as a duplicate of #1956, with the note that for #1956, we should take speech into account. See also #7232

**Comment by jcsteh** [comment]
This is a duplicate of #1772. Arguably, #1956 is a duplicate of #1772 as well (except #1772 only specifically mentions speech).
