### ISSUE TITLE
In Wordpad, ctrl+arrow down doesn't read paragraphs.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3220]
**Reported by aleskis on 2013-05-11 13:28**
To read text paragraph by paragraph, NVDA+arrow down is a useful command. However, on Wordpad, this command only read the first line of the paragraph, then NVDA stop.

**Comment by ehollig** [comment]
CC @michaelDCurran

**Comment by bhavyashah** [comment]
This is a friendly reminder for @michaelDCurran to consider commenting on this ticket by providing "further clarifications" as requested in @jcsteh's https://github.com/nvaccess/nvda/issues/3220#issuecomment-155307127.

**Comment by ehollig** [comment]
I am going to close this issue as worksforme. I performed the following steps:
1. Open wordpad
2. Write, or paste, two paragraphs or more of text.
3. Navigate the paragraphs using CTRL+up or CTRL+down.
4. Notice that NVDA properly moves focus to the beginning of the paragraph and reads the entire paragraph even if it spans multiple lines.
Using Windows 10,1803
