### ISSUE TITLE
NVDA lags  with complex formatting in microsoft word

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3227]
**Reported by Shaimaa on 2013-05-12 17:41**
Hi,
whenever I have a word file with a complex format, NVDA doesn't speak the text as fast as it does with the other simple format. It lags, and it takes seconds to speak the items. 
by complex format, I mean things like tables, or tables of content.
steps to reproduce:
1. open a 50-page document or more if available. 
2. create a big table like 6 columns, 10 rows. 
3. make sure that the cells have enough content not only 1 / 2 words. 
4. try to navigate the table content. 
results:
It takes longer to read the content of the table than it does for the normal text. 
again, steps to reproduce:
1. find a document with heading formats. 
2. go to references.
3. choose table of contentt.
4. choose the automatic one which uses the heading format and apply it. 
5. depending on the length of the file, you should wait a bit for the program to create the table of content. 
6. go to the table of content itself and try to navigate it.
results:
NVDA lags and it doesn't speak the items quickly as it should compared to the other normal text specially at the first item. 
notes:
1. I use microsoft office 2007, and windows 7 64 bit. 
2. I made sure that announcing the format after changing cursor is disabled / unchecked. 
3. I have a laptop with high specifications. 
4. NVDA has this problem for a very long time not only with development snapshots. 
Thank you

**Comment by Adriani90** [comment]
@Shaimaa how is the performance in NVDA 2019.1 in such documents?

**Comment by Adriani90** [comment]
We do not have an answer from the initial author since more than 5 years. As performance in MS Word is already covered in several issues, I am closing this one.
