### ISSUE TITLE
Nvda crashes Kindle for PC with Accessibility Plugin

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3229]
**Reported by hand2mouth on 2013-05-12 23:32**
When I try to open Kindle for PC with Accessibility Plugin while running Nvda, Nvda crashes the program immediately. The error details are as follows: 

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: Kindle.exe
  Application Version:  1.10.2.40279
  Application Timestamp:    500ff29b
  Fault Module Name:    nvdaHelperRemote.dll
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   517f6d5d
  Exception Code:   c0000005
  Exception Offset: 000183f7
  OS Version:   6.1.7601.2.1.0.256.48
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

**Comment by ehollig** [comment]
I know there have been improvements with Kindle for PC in 2017.1. Would this still be considered an issue?

**Comment by jcsteh** [comment]
This accessibility specific version of Kindle has been superseded for some time now by the far superior screen reader support included in the mainstream Kindle app. Closing.
