### ISSUE TITLE
If Try to Use  Routing Keys in Thunderbird Subject Field of Message, kicks you all the way to from

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3230]
**Reported by miahtech on 2013-05-13 08:25**
Summary pretty much covers it. Using a FS pac mate 40 display at the moment. 
UEB Grade 2, expand to word off, cursor blink 0, Tether to focus.

**Comment by leonardder** [comment]
Can't reproduce this with recent thunderbird and NVDA next. Closing as works for me.
