### ISSUE TITLE
Support for mumble

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3250]
**Reported by joshknnd1982 on 2013-05-23 12:52**
Please make an addon which provides better access to mumble chat client. NVDA seems to slow down and keypresses do not interrupt speech when using mumble which makes its use with NVDA difficult. Also due to this issue access to any toolbars buttons or menu bars is not possible.

**Comment by bhavyashah** [comment]
The scope of this ticket, especially the original ticket body, is quite unclear, in my humble opinion. Does this ticket deal with an all-round improvement in accessibility of Mumble (in which case specific areas of improvement will need to be outlined), or may we morph this ticket so as to only cover the bug reported by the original author of this ticket (Josh) and confirmed by webczat  wherein key presses fail to interrupt speech?

**Comment by Adriani90** [comment]
@joshknnd1982 could you please give us an update on this issue? Is your problem still reproducible with NVDA 2018.3.2 or 2018.4 Beta 4 and last version of the chat client?

**Comment by joshknnd1982** [comment]
Seems to work fine now

**Comment by ehollig** [comment]
Thank you @joshknnd1982 for the comment. Closing
