### ISSUE TITLE
new speech addon google tts

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3251]
**Reported by joshknnd1982 on 2013-05-23 12:55**
Please reach an agreement with google to put the android jellybean google tts all voices and all languages in an NVDA speech synthesizer addon. This would give people access to high quality natural speech if they could not afford nuance vocalizer expressive voices. thanks.

**Comment by bhavyashah** [comment]
Downloading speech synthesis data from Google Translate simply for the sake of using Google text to speech is definitely not something meant for NVDA core. Regardless, this may also not be legal. @jcsteh Could NV Access's contacts at Google be notified about the interest of NVDA users in porting Google TTS to Windows?

**Comment by jcsteh** [comment]
We actually had some discussions with Google about this a few years ago, but despite initial hopes, this turned out to be infeasible for technical reasons. The technology they use to compile the TTS engine for Chrome for Windows is Chrome specific. Closing as can't fix.
