### ISSUE TITLE
NVDA2013.1 could not detect some click graphic

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3252]
**Reported by surfer0627 on 2013-05-24 01:55**
I found this problem in an intranet web page.
So, it cann't be reproduced.
I'll attach the debug.log file.

The click graphic is a calender option.
After clicking it, it will open a calender for user to choose month and date.

But if I use NVDA 2012.2.1.
It will detect the click graphic.

**Comment by ehollig** [comment]
@jcsteh is this still the case? Does the attached file provide information to replicate the issue? Currently, it is unavailable.

**Comment by ehollig** [comment]
@surfer0627, is this still an issue with the latest version of NVDA? Is there an example test site where this behavior occurs?

**Comment by leonardder** [comment]
@surfer0627: Would you be able to reply to @ehollig's message?

Closing this as invalid around this time next wweek if no additional information has been provided.

**Comment by surfer0627** [comment]
to @ehollig, and @leonardder:
Please close this as invalid.
Due to some changes in the internal web, I does not able to reproduce this.

**Comment by ehollig** [comment]
Closing as invalid, as requested in https://github.com/nvaccess/nvda/issues/3252#issuecomment-334331788
