### ISSUE TITLE
Combine Design Overview With Developer Guide And Other Info From User Guide

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3255]
**Reported by jhomme on 2013-05-30 12:02**
There's a lot of great information in the design overview article on the community site. And some of the information in the Developer Guide refers to some stuff in the normal User Guide. It would be extremely convenient to either have this in a single document or to have it linked to. Maybe it would also be great to link to the Accessing the source code document. I'd be glad to take a crack at making those edits. I'm having trouble getting mail from the lists at work, so if you want to reply to me, do so at my home address.

**Comment by bhavyashah** [comment]
CC @josephsl (current maintainer of NVDA's Developer Guide) for his thoughts/inputs on this documentation related proposal.

**Comment by josephsl** [comment]
Hi, in the end, @JCSTeh, @MichaelDCurran, I and some in the add-ons community agreed that at least good parts of add-on dev guide should be merged into an improved development guide, something I would like to target for 2018.1. Thanks.

**Comment by jcsteh** [comment]
Long-term, I've been thinking we should consider combining all of our development documentation (including code documentation) into one single resource using Sphinx. While this does mean there is more work in documenting the code and we can't simply auto-generate all of the code documentation as Epydoc does, it has the added advantage that we can intersperse the code reference with explanatory text. We can also better order and structure the code reference. For example, for some classes (e.g. TextInfo), we have documentation for people calling the class, but we also have documentation for people subclassing it to provide their own implementations that others would use. In a purely auto-generated reference (such as with Epydoc), these two types of information get mixed together, whereas clear separation would be a huge help for intelligibility.

All that said, what I'm proposing here is an absolutely massive undertaking and would involve completely rethinking the way we write docstrings, etc.

**Comment by leonardder** [comment]
As part of #9840, I started looking into Sphinx, which has also been mentioned here.

> In [my sphinx branch](https://github.com/leonardder/nvda/tree/sphinx) I created a prototype:
>
> 1. Install sphinx using pip: `pip3 install sphinx`
> 2. In the mentioned branch, navigate to the devDocs directory
> 3. Execute `make html`
> 4. Consult the _build folder for the output.
>
> Note that the doc string annotations are still epydoc style. This is also a reason for many warnings. However, I've been able to get rid of all tracebacks at source code parsing time.

**Comment by Adriani90** [comment]
The dev docs is now created using sphinx. Specifically for this issue, in the readme of the NVDA repository, there is now a chapter called "get support" which brings the most important documentation sources into one place, from which you can easily access almost everything about NVDA's development environment.

I am closing this issue for now.
