### ISSUE TITLE
Strange error in LibreOffice in XP

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3257]
**Reported by briang1 on 2013-06-01 07:59**

The version I installed is LibreOffice_4.0.3_Win_x86.msi
And the help package that went with it...
Basically when you install Libra Office the first thing to check up on is 
that you ticked the accessability  checkbox just before you commit to the 
install. You have to tab for this so  watch you do not miss it

If like me you are using XP with the old Java Access bridge installed, when 
Libra Office is installed it will probably not actually work. Here is what 
to do.
 Using explorer go into the program files folder, and into the java access 
bridge folder.
Run the file installer.exe, and wait till its finished checking the disc.
 Now restart the computer and try Libra Office again.

This time it should present you with buttons for the various bits of the 
software.

I have thus far tried writer, ie text document, and bar some menu options 
which trigger not implimented errors in nvda  ( see below), it seems to 
work.

Note that the say all does not work correctly. In this case it does not move 
the cursor when reading the file and only reads around a page at a time. 
This is irritating, but seems to be a problem in all these Open Office 
derived  programs.

Occasionally, errors occur when in the text editor or when returning to it 
from a command. My feeling is that this may well be a timing issue on slow 
machines though, as it does eventually seem to sort itself out or will if 
you switch away and back again.

I'll leave it there as I'm sure there are plenty of folk who love trying 
stuff.

This was the  auto correct options, for which i could only find one option 
and it was checked, but unchecking it then makes the following error when 
you attempt to tab to the apply button.
At least that is what was there before!

IO - inputCore.InputManager.executeGesture (12:04:27):
Input: kb(desktop):downArrow
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:27):
states: enabled,focusable,opaque,sensitive,showing,visible
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:27):
states: 
enabled,focusable,focused,opaque,selectable,selected,sensitive,showing,visible
IO - speech.speak (12:04:27):
Speaking [('en_GB'), u'AutoCorrect  menu  selected'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:04:29):
Input: kb(desktop):enter
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:29):
states: 
enabled,focusable,focused,opaque,selectable,selected,sensitive,showing,visible
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:29):
states: 
enabled,focusable,opaque,selectable,selected,sensitive,showing,visible
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:29):
states: 
checked,enabled,focusable,focused,opaque,sensitive,showing,visible,armed
IO - speech.speak (12:04:29):
Speaking [('en_GB'), u'While Typing  checked'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:04:33):
Input: kb(desktop):enter
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:33):
states: 
checked,enabled,focusable,focused,opaque,sensitive,showing,visible,armed
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:34):
states: checked,enabled,focusable,opaque,sensitive
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:35):
states: enabled,sensitive,showing,visible
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:35):
states: enabled,sensitive,showing,visible
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:35):
states: editable,enabled,multiselectable,opaque,showing,visible
IO - speech.speak (12:04:35):
Speaking [('en_GB'), u'Document view  document  editable'](LangChangeCommand)
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:35):
states: enabled,focusable,opaque,selectable,sensitive,showing,visible
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:35):
states: enabled,focusable,opaque,selectable,sensitive,showing,visible
IO - speech.speak (12:04:35):
Speaking [('en_GB'), u'Format  menu'](LangChangeCommand)
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:35):
states: enabled,focusable,opaque,selectable,sensitive
IO - speech.speak (12:04:35):
Speaking [('en_GB'), u'AutoCorrect  menu'](LangChangeCommand)
IO - speech.speak (12:04:35):
Speaking [('en_GB'), u'Format  menu'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:04:38):
Input: kb(desktop):tab
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:38):
states: enabled,focusable,opaque,selectable,sensitive,showing,visible
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:38):
states: enabled,focusable,opaque,selectable,sensitive,showing,visible
ERROR - eventHandler.executeEvent (12:04:38):
error executing event: caret on 
<NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionJAB object at 
0x03F90CF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 136, in executeEvent
  File "eventHandler.pyc", line 84, in __init__
  File "eventHandler.pyc", line 91, in next
  File "compoundDocuments.pyc", line 410, in event_caret
  File "compoundDocuments.pyc", line 387, in makeTextInfo
  File "compoundDocuments.pyc", line 216, in **init**
  File "NVDAObjects__init__.pyc", line 903, in makeTextInfo
  File "textInfos\offsets.pyc", line 280, in **init**
  File "textInfos\offsets.pyc", line 159, in _getCaretOffset
NotImplementedError
ERROR - eventHandler.executeEvent (12:04:38):
error executing event: caret on 
<NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionJAB object at 
0x03F90F90> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 136, in executeEvent
  File "eventHandler.pyc", line 84, in __init__
  File "eventHandler.pyc", line 91, in next
  File "compoundDocuments.pyc", line 410, in event_caret
  File "compoundDocuments.pyc", line 387, in makeTextInfo
  File "compoundDocuments.pyc", line 216, in **init**
  File "NVDAObjects__init__.pyc", line 903, in makeTextInfo
  File "textInfos\offsets.pyc", line 280, in **init**
  File "textInfos\offsets.pyc", line 159, in _getCaretOffset
NotImplementedError
DEBUG - NVDAObjects.JAB.JAB._get_states (12:04:39):
states: enabled,focusable,opaque,selectable,sensitive,showing,visible
ERROR - eventHandler.executeEvent (12:04:39):
error executing event: caret on 
<NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionJAB object at 
0x03F90CD0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 136, in executeEvent
  File "eventHandler.pyc", line 84, in __init__
  File "eventHandler.pyc", line 91, in next
  File "compoundDocuments.pyc", line 410, in event_caret
  File "compoundDocuments.pyc", line 387, in makeTextInfo
  File "compoundDocuments.pyc", line 216, in **init**
  File "NVDAObjects__init__.pyc", line 903, in makeTextInfo
  File "textInfos\offsets.pyc", line 280, in **init**
  File "textInfos\offsets.pyc", line 159, in _getCaretOffset
NotImplementedError
ERROR - eventHandler.executeEvent (12:04:39):
error executing event: caret on 
<NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionJAB object at 
0x03F90450> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 136, in executeEvent
  File "eventHandler.pyc", line 84, in __init__
  File "eventHandler.pyc", line 91, in next
  File "compoundDocuments.pyc", line 410, in event_caret
  File "compoundDocuments.pyc", line 387, in makeTextInfo
  File "compoundDocuments.pyc", line 216, in **init**
  File "NVDAObjects__init__.pyc", line 903, in makeTextInfo
  File "textInfos\offsets.pyc", line 280, in **init**
  File "textInfos\offsets.pyc", line 159, in _getCaretOffset
NotImplementedError
IO - inputCore.InputManager.executeGesture (12:04:46):
Input: kb(desktop):control+alt+r
IO - speech.speak (12:04:46):
Speaking [('en_GB'), u'reboot nvda with log  terminal'](LangChangeCommand)
IO - speech.speak (12:04:46):
Speaking [('en_GB'), u'blank'](LangChangeCommand)
INFO - core.main (12:04:47):
Exiting

This was with the latest version of the master branch.

**Comment by ehollig** [comment]
@Brian1Gaff, is this still happening for you? It appears that there has been several releases of LibreOffice since you have reported this.

**Comment by ehollig** [comment]
Is this still an issue @Brian1Gaff?

**Comment by Brian1Gaff** [comment]
I am no longer using Libra Office so I cannot say myself now. Its been a 
while since I've tested it in any version of Windows. I'd close it and see 
what others say if they use it.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by leonardder** [comment]
As XP specific issues won't be addressed anymore, closing this anyway.

**Comment by zahra21** [comment]
hi.
since, libreoffice since in its version since 4.3.0, no longer does not java access briedge, and its accessible by default when installing, i did not have such issues using it.
i could not learn and did not want the version wich such difficulties!
i should say:
at least in 4.3.0 and later, i did not have such issues using libreoffice.
menus, options and buttons are accessible and i did not have issue with unchecking autoCorrect.
