### ISSUE TITLE
nvda doesn't refresh progressbars in braille

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3258]
**Reported by halim on 2013-06-01 17:48**
Maybe I am doing something wrong but it seems that nvda displays progressbars but doesn't update these on the brailledisplay.
firefox downloadmanager or progressbar when copieing files are useful examples.
I tested it with nvda 2013.1 in windows xp pro.

**Comment by jcsteh** [comment]
The update dialog issue is covered by #6862. Closing this in favour of that, since this issue is suffering from scope confusion. :)
