### ISSUE TITLE
MS Word 2007 & 2010, NVDA No Longer Reads All Info On Word Status Line

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3263]
**Reported by jhomme on 2013-06-03 16:27**
Hi,
I don't know when this started. I have NVDA 2013, Release 1 at work and a newer revision at home, but not the latest one. This morning from home and later from work, I tried to read the status line in MS word. Both times NVDA did not say the page number nor word count, which is set up on both computers. At home, I have Word 2007. At work, I have Word 2010. At home I have Vista. At work, I have Windows 7.

**Comment by leonardder** [comment]
Closing this as invalid, as this seems abandoned and we don't have enough information. For example, how is the status bar information retrieved, using NVDA's status bar command or by moving the focus to it using F6? Also note that, at least for Word 2016, it is possible to toggle what is shown in the status bar and what not.

If it is the status bar that can't be found, this is also a duplicate of #649.
