### ISSUE TITLE
Sometimes when arrowing down in a website the virtual buffer jumps back at the beginning.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3265]
**Reported by nikosdemetriou on 2013-06-06 08:58**
Sometimes when exploring a website with the arrow keys nvda jumps at the beginning of the virtual buffer at a spessifick point and it makes reading the website difficult. However if we use one of the quick navigation keys such as N or H to pass the part where is the problem we can read fine. I suspect that some types of frames are causing this problem. 
Usually i find this problem in news websites where they have facebook and twitter sharing etc. I don't have an example at the moment but as soon as i find one i will give the address here. Using the latest firefox.

**Comment by ehollig** [comment]
Duplicate of #3266
