### ISSUE TITLE
Firefox: some pages cause NVDA to jump to the top

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3266]
**Reported by camlorn on 2013-06-06 21:32**
I am not 100% sure that this is an NVDA issue, but am lately seeing a lot of web pages that cause this.  When moving down the page, something causes the focus to jump back to the top.  I've managed to find an example page:
http://forecast.weather.gov/MapClick.php?lat=26.6374761&lon=-80.2432839&site=all&smap=1&searchresult=Wellington%2C%20FL%2033414%2C%20USA#.UbD9SJxRK-U
Move to heading Current conditions, and arrow down past En Español.  the next line causes this for me.  Using NVDA's object navigation and text review functions, it appears to be something to do with sharing on facebook, stumble upon, and the like. I'm not sure who's at fault: Firefox, NVDA, or the web site author, but am seeing this a lot.  It always seems to occur around places with Facebook and similar integration. I can't always be sure what it is for obvious reasons.  Moving past it, using any method similar to moving by heading, allows one to read the rest of the web page.  It happens reasonably frequently, and obviously it isn't always possible to guess what to move to to get past it.

**Comment by ehollig** [comment]
It appears that this example no longer works for me. Does anyone have an updated example to provide?

**Comment by Adriani90** [comment]
I had something similar on google groups but thats another issue whic is not reproducible anymore.
I cannot reproduce this issue either. I suggest closing it unless someone reports it again. Then we can reopen it.

**Comment by ehollig** [comment]
Closing as worksforme
