### ISSUE TITLE
new variant for espeak

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3268]
**Reported by Animesh.mr on 2013-06-07 12:07**
hi there it is a new variant for espeak try to use it and let me know if wee can ad it to nvda screenreader thanks in advance 
name email 6

**Comment by ehollig** [comment]
For suggestions on new voices please create a new issue on the [ESpeak NG Github page](https://github.com/espeak-ng/espeak-ng/issues/new).
@jcsteh , it may be useful to attach the original file so that it can be forwarded on to the ESpeak tracker.
