### ISSUE TITLE
Word 2010: Allow NVDA to read the Text Statistics dialog.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3270]
**Reported by jhomme on 2013-06-07 19:43**
Currently, when you finish a spelling and grammar check, NVDA only reds and sees the OK button in the text statistics dialog. It would be good to be able to read this dialog to get an idea of how many words and other things like paragraph count, sentences per paragraph, and grade level.

**Comment by leonardder** [comment]
For Word 2017, NVDA only says that the spelling and grammar check is complete, no information about statistics whatsoever. However, it at least reads the dialog contents.

Anyone who can reproduce this in Word 2010?

**Comment by ruifontes** [comment]
Leonard, I think they ment the Word Count dialog...

Rui


-----Mensagem Original----- 
De: Leonard de Ruijter
Data: 13 de julho de 2017 18:39
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Word 2010: Allow NVDA to read the Text 
Statistics dialog. (#3270)



For Word 2017, NVDA only says that the spelling and grammar check is 
complete, no information about statistics whatsoever. However, it at least 
reads the dialog contents.

Anyone who can reproduce this in Word 2010?

**Comment by leonardder** [comment]
Ah, that's helps a lot Rui, thanks!

@Elliott94, turns out that you are using Office 2010. Would you be able to do a word count in a document and could you please report whether you are able to read the statistics dialog?

**Comment by elliott94** [comment]
After testing this, it appears that this particular dialog is presented as a graphic; this can be found when using Object Navigation, and I am able to successfully read the content if I OCR the object. Hope that helps!

**Comment by ruifontes** [comment]
Sorry, but you are wrong...
The dialog is not graphical. You can read it using the object navegation.

In 2010 the dialog is not read automatically, but in 2013 is automatically.

Rui


-----Mensagem Original----- 
De: elliott94
Data: 18 de julho de 2017 19:02
Para: nvaccess/nvda
Cc: ruifontes ; Comment
Assunto: Re: [nvaccess/nvda] Word 2010: Allow NVDA to read the Text 
Statistics dialog. (#3270)



After testing this, it appears that this particular dialog is presented as a 
graphic; this can be found when using Object Navigation, and I am able to 
successfully read the content if I OCR the object. Hope that helps!

**Comment by Adriani90** [comment]
Moreover, testing in Word 2010, you can also read the Dialog with NVDA+b.

**Comment by ehollig** [comment]
I am going to close this issue, as this sounds to be specific to Office 2010 and there is also a workaround
