### ISSUE TITLE
Focus 40 blue braille keyboard single letter navigation in browse mode

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3273]
**Reported by falinn.onda on 2013-06-09 06:57**
Hi,
I got a new focus braille display and i managed to connect it to NVDA really easily (great work guys...).

When i open a window like explorer and i type a letter with the braille keyboard, it navigates to an item starting with this letter as expected. Same for menus with single letter shortcuts.

However, if i try to use single letter navigation in firefox in browse mode with the braille keyboard, it reacts strangely.
If i write h it doesn't move to next headline. Same for numbers for heading levels or n for next text.
However if i type dot2 it says "no more text after block of links" as if i pressed n (or moves if any).
Pressing dot3 opens quick find (firefox, not nvda find)
Pressing dot5 seems to go to next visited link and says "no next visited link" if at the end, as if i pressed v.
Pressing dot3+dot6 seems to trigger next checkbox navigation.
1. I think single letter navigation should work in browse mode. Keys such as h , k v and n are really helpful for reading a site.
   I'm not familiar with NVDA implementation of this, but Isn't it supposed to simulate a key stroke by calling NVDA keystroke handler which can pass it to the application if it is not handled by NVDA?
2. If this is the intended behavior and there is an organized list of such key combination please let me know where i can find it.

Run on win 7 64 bit and NVDA 2013.1.

Help will be greatly appreciated...
Falinn
**Blocking #4287**

**Comment by derekriemer** [comment]
Does this have to simply do with the fact that the braille keys aren't being bound as gestures?

**Comment by jcsteh** [comment]
I'm closing this in favour of duplicate #7306, as it's a bit more generic and contains some technical discussion.
