### ISSUE TITLE
When using Windows 7 with Office 2007 installed, NVDA responds slower in dialogs such as file copy while Office supplied IME is in use

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3274]
**Reported by nvdakor on 2013-06-10 08:16**
Hi,
Some Korean users reported an issue where NVDA responds slower when using Win7 and Office 2007 and while one is in a dialog such as file copy.

STR (as reported by users):
1. Switch to IME supplied by Office 2007 (you need to install them; the ones used are Korean ones).
2. Try some tasks such as copying files.
3. Switch back to default IME which shipts with Windows.
4. Do step 2. You should notice noticeable performance differences.

Notes from users:
- This occurs if Windows 7 and Office 2007 is installed.
- Other Office versions such as 2010 does not cause this issue when installed under Win7.
- This affects both 32-bit and 64-bit versions of Windows 7.
- This happens when Office supplised IME is in use, not the default one used under Windows.
- Tested with Korean IME.

I asked users for a log to attach to this ticket.
Thanks.

**Comment by bhavyashah** [comment]
@josephsl Could you please request the Korean user who reported these slowdowns to test with the latest version of NVDA (now NVDA version 2017.3) as requested in @jcsteh's https://github.com/nvaccess/nvda/issues/3274#issuecomment-155307562? CC @brian1gaff (user of Windows 7)

**Comment by leonardder** [comment]
I'm closing this because the issue is getting very old and hasn't got relevant comments in a while. Furthermore, Office 2007 is getting quite old as well.
