### ISSUE TITLE
Text on the braille display doesn't update after using Undo in Word

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3276]
**Reported by falinn.onda on 2013-06-10 17:16**
Hi,

Assuming you do the following:
1. open new word 2010 document.
2. Type a text. for example "1234"
3. press undo CTRL+Z once.

 Expected behavior: braille displays "123" as the current document content after undo.
Actual behavior: Braille displays "1234"

I am using Focus 40 blue via Bluetooth.

**Comment by bhavyashah** [comment]
Could Braille experts please test and report whether these Braille synchronization issues (particularly with MS Word's Undo and Redo, Ctrl+Backspace and Ctrl+Delete) still occur?

**Comment by Adriani90** [comment]
@falinn.onda is this issue still reproducible?
cc: @bramd

**Comment by dkager** [comment]
I can still reproduce this with Word 2016, non-UIA. It isn't specific to a particular braille display.

**Comment by Adriani90** [comment]
@dkager how is this now with NVDA 2023.1 RC1 or NVDA 2022.4?

**Comment by burmancomp** [comment]
I tried locally to add `braille.handler.handleUpdate` to source\NVDAObjects\iaccessible\winword.py and there to `event_caret` function.

It worked almost. If there is for example: "12345", and then ctrl-z is pressed 5 times, there is not necessarily blank display. If pressing and holding ctrl-z it seems to work or if pressing ctrl-z with long delay between presses, it seems to work also. But if something between these, it may not work.

@leonardder what do you think about this? Is my approach wrong?

**Comment by leonardder** [comment]
@burmancomp is this with or without UIA enabled in Word?

**Comment by burmancomp** [comment]
Do you mean this setting: "Use UI Automation to access Microsoft Word document controls"? It is currently " Default (Where suitable)".

**Comment by burmancomp** [comment]
In blank document typing q then ctrl-z. Quite often q remains in braille line. If there are more characters like qwerty, others y, t ... seems to be removed correctly. It seems that `event_caret` would not be always executed.

**Comment by burmancomp** [comment]
It may work better with UIA set to always, and when NVDAObjects\UIA\wordDocument.py also includes event_caret.

I have understood that UIA does not work properly in ms word before Windows 11. I have not Windows 11 installed.

I'm considering if it would be worth of opening draft pull request. I suppose that braille.handler.handleUpdate should be enough in most cases but when document contains only 1 character and then ctrl-z is pressed to undo this does not work always. As if caret event would not be fired every time, but why it is happening (if this is the case), I do not know.

**Comment by leonardder** [comment]
Well if a pr doesn't fix 100% of the instances of the issue, it might be 
better to get more to the bottom of it.

I might be able to do some tests later this week. I think we need to 
search more in the lines of event_textChange

**Comment by burmancomp** [comment]
I added event_textChange, event_textInsert and event_textRemove functions to WordDocument class which just write a log line. It seems that any of these events were never fired because there was no log line they should have written.

I should have time to test so let me know what you think I could try.

**Comment by burmancomp** [comment]
It seems that his is larger issue because display is not necessarily updated when using ctrl+x.

**Comment by burmancomp** [comment]
I have also noticed that when in blank document repeating following may cause situation where entered character is not updated to braille display:

- type character
- press control+z

Log lines are attached. Version is current main branch source.
[no_updates.txt](https://github.com/nvaccess/nvda/files/12559698/no_updates.txt)
