### ISSUE TITLE
NVDA crashes in MS Word 2013.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3277]
**Reported by Harich on 2013-06-12 13:03**
Two problems occurred when opening MS Word 2013. 
1. The NVDA stopped speaking and then shut down by itself -- and then restarted automatically. 
2. In other instances, it did not restart once it stopped speaking and shut down.

**Comment by ehollig** [comment]
Unfortunately, we are unable to contact the original author and there appears to be not enough information to troubleshoot this issue. I know others are using MS Word 2013 without a problem. Closing
