### ISSUE TITLE
Hidden elements read out in IE8

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3281]
**Reported by hh10k on 2013-06-14 03:32**
Hi, I found that my hidden <div>s in IE8 (8.0.7601.17514) are read out by NVDA.  Applying style="display:none; visibility:hidden" and aria-hidden="true" has no effect.

These elements are not read out in Firefox, Chrome and Opera.

**Comment by hkdennis2k** [comment]
I did a quick search and found few issue might be related.
#5233
#5320
#6097

---------------
I did some test on IE11 (Win10) and found that nvda will read out "Not read" by tab and focus. but skip them if browsing (up/down key)


```
<ol>
<li tabIndex=0 aria-describedby="id"><span class="text">Span1 Only</span></li>
<li tabIndex=0 ><span aria-describedby="id" class="text">Span2 Only</span></li>
<li tabIndex=0 ><span aria-label="x" class="text">Span3 Only</span></li>
<li tabIndex=0 aria-describedby="id"><span class="text">Span4 Only</span>3</li>
<li tabIndex=0 ><span aria-describedby="id" class="text">Span5 Only</span>2</li>
<li tabIndex=0 ><span aria-label="x" class="text">Span6 Only</span>1</li>
<li tabIndex=0 ><span aria-label="x" class="text">Span</span> and Another</li>
<li tabIndex=0 ><span aria-hidden="true" class="text">Not Read</span></li>
<li tabIndex=0 ><span aria-hidden="true" class="text">Not Read</span> Another Only</li>
<li tabIndex=0 >Before <span aria-hidden="true" class="text">Not Read</span></li>
<li tabIndex=0 ><span aria-hidden="true" class="text">Not Read</span>Middle1<span aria-hidden="true" class="text">Not Read</span></li>
<li tabIndex=0><span aria-hidden="true" class="text">Not Read</span>Middle2<span aria-hidden="true" class="text">Not Read</span></li>
</ol>
<span id="id">Labled by</span>
```

**Comment by Adriani90** [comment]
@feerrenrut is this issue a priority for NV Access to solve?

**Comment by Adriani90** [comment]
@hh10k, @Yossarian I guess this is still reproducible in IE. Right?

**Comment by Adriani90** [comment]
Aria hidden=true is covered in #5833

**Comment by leonardder** [comment]
Given we haven't received any reply from the initial author on @Adriani90's request and Internet Explorer specific bugs have quite low priority, I"m going to close this for now. We can always reopen if needed.
