### ISSUE TITLE
Hebrew braille display

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3284]
**Reported by falinn.onda on 2013-06-14 14:14**
Hi, 
I am using Focus 40 blue.
I set the braille output table to Hebrew with 8 dots.
The thing is that in Hebrew, few letters have a final/non final version. A bit like the capital letters in English only for few letters when at the end of the word.
Currently i get the same braille dots for both final/non final versions of the letter.

This miens that if i write a word incorrectly i cannot see the difference in braille, while sighted people will comment me about writing incorrectly.

Maybe there is already a standard solution which i am not aware of, but i know two things certainly:
1. my braille display shows the same dots for final/non final.
2. In 6 dots braille standard both final/non final letters are represented by the same dots.

I think that the solution should be like in capital English letters, i.e. adding dot 7 to the final letters.

I made a list of those letters according
http://en.wikipedia.org/wiki/List_of_Unicode_characters#Hebrew

Note that i do not change the letter dots, only add dot 7 for final versions. If someone will explain me how to change the NVDA output table for Hebrew I'll try doing it myself.

Here is the list:
letter, code, suggested dots
kaf final, U+05DA, 157
kaf, U+05DB, 15
Mem final, U+05DD, 1347
Mem, U+05DE, 134
Final Nun, U+05DF, 13457
Nun, U+05E0, 1345
final pe, U+05E3, 1247
Pe, U+05E4, 124
final tsadik, U+05E5, 23467
tsadik, U+05E6, 2346

**Comment by bhavyashah** [comment]
@josephsl's https://github.com/nvaccess/nvda/issues/3284#issuecomment-155307634 suggests that recent LibLouis developments may have solved this ticket. Could someone please test and triage this ticket accordingly?

**Comment by ehollig** [comment]
@josephsl, do you know if this issue has been resolved? Your https://github.com/nvaccess/nvda/issues/3284#issuecomment-155307634 suggests that it may be

**Comment by ehollig** [comment]
As NVDA is now using LibLouis 3.6, and https://github.com/nvaccess/nvda/issues/3284#issuecomment-155307634 suggests this may have been resolved in version 2.6, I am going to close this issue. If this issue comes up again in the future, we can revisit this issue.
