### ISSUE TITLE
NVDA Incompatible with Nuance Dragon NaturallySpeaking

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3291]
**Reported by fjwilke@... on 2013-06-19 17:04**
All NVDA editions published after NVDA 11.3 disables user created voice commands in Nuance Dragon NaturallySpeaking 11, 11.5, 12 and 12.5. 

Users of Nuance Dragon NaturallySpeaking may create their own voice commands by going to Nuance Dragon NaturallySpeaking > Tools >Add New Command.  Voice commands thus created make text entities and can also apply font attributes to those entries.

I make extensive use of Nuance Dragon NaturallySpeaking voice commands and for that reason I am stuck with NVDA 11.3.

Would it be possible to resolve this issue?

**Comment by ehollig** [comment]
I thought NVDA works well with Dragon through DictationBridge as well as using it alone. CC @derekriemer

**Comment by jcsteh** [comment]
Closing because there's insufficient information and no answers from reporter. Also, DictationBridge now provides improved access to Dragon.
