### ISSUE TITLE
Microsoft Word: Synchronize Style Name Speaking When Certain Keys Are Pressed

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3294]
**Reported by jhomme on 2013-06-20 13:53**
In Microsoft Word 2010, the following happens.
1. Create a document with a line of text and make sure the speaking of style names is turned on.
2. Press any of these keys: Alt + Control + 1, Alt + Control + 2, Alt + Control + 3, Alt + Shift + Left Arrow, Alt + Shift + Right Arrow, Control + Shift + N, Control + Shift + L, etc.
3. Immediately press NVDA + F.
4. Expected: NVDA should say the new style name, because it has changed. What actually happens is that NVDA speaks the style name the text was formerly associated with.
5. Use any method you wish to move off of the line and back on, and press NVDA + F. NVDA now speaks the new style name.
6. It would even be better if NVDA would speak the new style name after the keys are pressed, but maybe that would be done only if style names are on. This would save the time of checking with NVDA + F, becausethe other information would have to be heard or interrupted.

**Comment by ehollig** [comment]
I just performed these steps in Microsoft Word 2016 with styles was selected in document formatting and was not able to replicate this issue. I think @jcsteh is right in https://github.com/nvaccess/nvda/issues/3294#issuecomment-155307747, that the performing those commands does not change the style of the text unless text is selected. Closing as worksforme
