### ISSUE TITLE
Navigating word with braille display (focus 40 blue)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3297]
**Reported by falinn.onda on 2013-06-21 05:48**
Hi,
I am trying to use my focus 40 blue to read word documents and outlook emails.
In both programs i noticed that NVDA skips certain lines for some reason.
'Ill try explaining it with the attached example file:
1. open the attached word file while braille is thathered to focus.
2. start reading the file using braille display, starting at the beginning. Use the panning buttons to advance the display.

The behavior i see is that the first four parts are displayed correctly.
The fifth part shows line and"".
At this point if i press panning to go to next part, the end of the line is skipped. The next thing i get is "This is..."
instead of "another paragraph".
Strangely, if while showing "This is..." and panning up, i do get to see the "another paragraph".

The same thing happens when reading emails. It took me a while to understand that i am missing some parts of sentences but i noticed the same behavior where panning down skips something but panning up doesn't.

I am using Office 2010.

**Comment by bhavyashah** [comment]
According to these two reports, these Braille issues are happening on more than one Braille display as well as more than one version of Microsoft Office, implying that this could potentially be an NVDA defect which needs to be addressed. I would like to kindly request Braille experts to take a look at this ticket and share their thoughts/inputs.

**Comment by Adriani90** [comment]
@amenaide can you still reproduce this?
@bramd are you maybe available to test this on a focus blue and see if it still occurs?

**Comment by Adriani90** [comment]
@ivnc could you please also test if this is still an issue in NVDA 2019.2 last Beta? Thank you very much for your availability. This is very apreciated.

**Comment by ivnc** [comment]
Do you have a copy of the word file attached to the report? I can't see a link to it. With my own content (two paragraphs without spacing, two paragraphs separated by a blank line and one multi-line paragraph) I am unable to reproduce.
I'll try to find someone who uses Outlook as well to ask them if they can reproduce this.
Testing environment: NVDA 2019.2Beta-17861 with Focus 40 Blue 5th Generation (firmware 5.81-50) and Office 2019 (16.0.11629.20238) 64 bits on Windows 10 1803 (build 17134.765).

Regards.

**Comment by Adriani90** [comment]
@ivnc here is the document which I have gathered from the old issue tracker.
[Uploading In order to test the panning buttons when used with NVDA I wrote this short document.docx…]()

**Comment by ivnc** [comment]
It seems the file wasn't uploaded correctly, but anyway I saw the URL to the old tracking system's attachments and could access [the file](https://www.nvaccess.org/files/nvdaTracAttachments/3297/In%20order%20to%20test%20the%20panning%20buttons%20when%20used%20with%20NVDA%20I%20wrote%20this%20short%20document.docx). I still can't reproduce this, both with UIA for Office enabled and disabled. I've also tried to test with add-ons disabled, with no results.

Regards.

**Comment by Adriani90** [comment]
Thanks very much Ivano. I am closing this as works for me.
