### ISSUE TITLE
T chord (alt-tab command) doesn't work properly

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3302]
**Reported by Ahiiron on 2013-06-24 04:13**
NVDA: master-9280,3350d74;
Windows 8 X64;
Brailliant BI 40 (firmware: 2.0.1)

STR:
1. Load the display with NVDA, make sure it's working etc.
2. Open two or more apps. Notepad and winword, for instance.
3. Press space with Dots 2-3-4-5 (t chord) for emulated alt-tab keypress.

Expected: for focus to switch to the other application like if you really pressed alt-tab on a real keyboard.

Actual: Just says "pane" or "taskbar" but then switches back to prior app.

**Comment by bhavyashah** [comment]
@jcsteh Since you were able to reproduce this as mentioned in https://github.com/nvaccess/nvda/issues/3302#issuecomment-155307788, can you please retest this and update us about the current standing of the reported issue?

**Comment by jcsteh** [comment]
Don't have one of these displays, but tested with the following entry in `%appdata%\nvda\gestures.ini`:

> ```
> [globalCommands.GlobalCommands]
> kb:alt+tab = kb:f11
> ```

This binds f11 to emulate alt+tab.

For me, this now works as expected. However, I'm using Windows 10 64 bit. Closing as works for me, but if someone experiences this on Windows 8, we should reopen.
