### ISSUE TITLE
Custom braille tables

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3304]
**Reported by falinn.onda on 2013-06-25 11:49**
Following the discussion in
http://community.nvda-project.org/ticket/3284#comment:5

 I think it is a good idea that NVDA will enable users to customize tables,
 if they know the table format (by referring to louise docs).

In response to jteh
" \* Coming up with an elegant user interface for this is tricky.
- We then have to document and explain how it works.
- It encourages users to copy files into the NVDA program directory. In
  general, users should never touch the NVDA program directory, only their
  config directory."

jteh, i agree with both comments.
I did not mean that NVDA will add a graphical user interface or that NVDA will have full documentation about customizing tables.
I do not think that is necessary since there is already a very good table definition format defined and explained in detail by louise documentation.
I think other users can tweak tables to their needs like i was able to after reading louise documentation.

the only thing i am suggesting is to have several table files which the user will be able to edit. I agree that it is bad practice to edit the default standard tables in louise/tables and that is exactly why i think it is a good idea to have few table files in userConfig\brailletables (or similar). 
The only thing i need from NVDA is to have an option in the braille setting input/output tables combo boxes which lets me choose to use those custom files i wrote.
It is the user responsibility to edit the file outside NVDA in a text editor of his choice  (or get a file someone else wrote).).

For example if we can put other1_custom_user_table.ctb other2_custom_user_table.ctb and other3_custom_user_table.ctb
in userConfig\brailleTables. (i'm suggesting file names starting with o because there is no such tables that start with o right now which will make it easy to switch to those combo )entries by pressing o ).

I am aware that not everyone will understand how to edit tables but most advanced users will benefit from this option and maybe give the tables to other users in their community or publish online like addons. 

In NVDA documentation we can only add a chapter titled "Customizing braille tables":
Advanced users who wish to use custom braille tables can edit the tables files x, y, z in the folder w. For a definition of the file format see luise documentation link.
Note that users who only wish to add symbols to ecisting tables can use the include command.

Here we can have a small example file that includes english braille table and adds additional letter and punctuation as example. 

What do you think?
**Blocking #4996**

**Comment by josephsl** [comment]
@dkager: found the actual ticket, will close 6113. Could you provide the updated link to your branch?
Also, @jcsteh says all our braille settings issues depends on #2439, so will hold off on this for a while. Thanks.

**Comment by dkager** [comment]
https://github.com/dkager/nvda/tree/t3304

**Comment by dkager** [comment]
Also #5489.

**Comment by bhavyashah** [comment]
@dkager  Since your submission seems to be ready for code review, I would like to kindly request @josephsl, @jcsteh and others to take a look. If it isn't ready, please update us about the implementation status, Davey.

**Comment by dkager** [comment]
See the associated PR (#5489), which definitely isn't ready anymore.

**Comment by Adriani90** [comment]
@josephsl #2439 is closed in #6449. Are there any further updates on this issue?

**Comment by JulienCochuyt** [comment]
> Are there any further updates on this issue?

@Adriani90, yes indeed.
I am currently testing an implementation of this feature based upon a custom liblouis table resolver, as using the sole environment variable LOUIS_TABLEPATH would mean either:
 - to rely on a strict import order, especially faulty if an addon happen to (in)directly import louis
 - or to reload the DLL if it has been loaded before we could alter the environment

So far, this new approach seems quite promising.
Currently, it can look for tables files in "brailleTables" sub-directories of:
 - the scratchpad directory, if enabled
 - the user configuration directory
 - running addons

Existing tables (same file name) are overridden, even when indirectly included.
New tables metadata are expressed in JSON files (localized display name, contracted, input, output).

**Comment by dkager** [comment]
The original plan was to allow absolute paths as table filenames, thereby allowing addons to specify their own table location. But I think that got lost a long time ago.

**Comment by JulienCochuyt** [comment]
> The original plan was to allow absolute paths as table filenames, thereby allowing addons to specify their own table location. But I think that got lost a long time ago.

This implementation allows for this, too.
"brailleTables" directories scrutation and support for JSON configuration files were merely added to allow for insertion of new tables with no code.
Addons can call `brailleTables.addTable` with any absolute path, or add any absolute directory to the resolver search path.

**Comment by leonardder** [comment]
@JulienCochuyt: Is your work somehow based on the work by @dkager which he did earlier?

**Comment by JulienCochuyt** [comment]
> @JulienCochuyt: Is your work somehow based on the work by @dkager which he did earlier?

Nope. The comments in PR #5489 helped me find my way to understand liblouis process, but this is original work based on a custom table resolver.

**Comment by leonardder** [comment]
@JulienCochuyt: When is this expected to arrive in a pr? We are working on a new Dutch braille standard with the Dutch Braille Authority and we'd be pretty interested in having an ability for users to test braille tables the easy way.

**Comment by zstanecic** [comment]
@leonardder

@andre9642 is working on something like that in Braille extender.

Why to duplicate pr’s?

**Comment by JulienCochuyt** [comment]
> When is this expected to arrive in a pr?
Whenever you like, thanks for your interest.
I was holding on this one waiting for threshold to stabilize and for anybody to disagree on the feature scope.
I am currently on a business trip, but I guess I could find time to rebase this branch onto the latest master before the end of next week.

> Why to duplicate pr’s?
Because:
 1- My first personal motivation for this dev was not to allow add-ons to supply braille tables (which I already could do easily), but instead to have the custom braille table working fine even when disabling add-ons (which I frequently do when developing/testing)
 2- There is currently no notion of inter-add-on dependencies in NVDA. This means an add-on cannot be expected to be installed and provide features for other add-ons to use. Allowing add-ons to supply new braille tables is the main motivation for a few people historically supporting this ticket. Hence, there need cannot be satisfied with an add-on, be it as widespread as BrailleExtender.
 3- I am of those who, while professionally developing add-ons, almost always prefer targeting NVDA core whenever a consensus can be reached. IMHO, if too many people need a feature, or if enough people need it very bad, it preferably should not be an add-on.

**Comment by Andre9642** [comment]
@zstanecic it's not a problem, I don’t have exclusivity on this feature. ☺ As @JulienCochuyt said, there is more advantages if this feature is directly into NVDA Core. Also it's much easier to integrate it like this.

In any case, I look forward to testing that!

**Comment by zstanecic** [comment]
<mailto:noreply@github.com> @Andre9642/BrailleExtender

I haven’t said that it is an exclusivity.

I’ve said, that something can be improved from your code and used for the PR.

**Comment by Andre9642** [comment]
@zstanecic I see, thanks. But the implementation by @JulienCochuyt is completely different and better. And mine is currently not finished / is still under consideration.

**Comment by leonardder** [comment]
This code is awesome, especially the liblouis resolver part. I made some pre pr comments in https://github.com/accessolutions/nvda/commit/820ff898fce9a93e4940cff3916f1970567f2aa8

**Comment by JulienCochuyt** [comment]
> This code is awesome, especially the liblouis resolver part. I made some pre pr comments in [accessolutions@820ff89](https://github.com/accessolutions/nvda/commit/820ff898fce9a93e4940cff3916f1970567f2aa8)

Thanks a lot for all these useful comments. Much appreciated.

**Comment by JulienCochuyt** [comment]
@leonardder,
The Python 3 version is (at last) ready with all your suggested changes.
It off course does not accept non-ASCII table files names due to liblouis/liblouis#698, but it now supports non-ASCII characters in the names of the directories in which they are located.
I probably won't have time to file a properly described PR before this weekend, but if this subject is still urgent for you, you can have a look at branch i3304-customBrailleTables in the accessolutions/nvda repo.

**Comment by leonardder** [comment]
Feel free to take your time. I won't be able to look into this before next week.
