### ISSUE TITLE
Nvda browse mode question in internet explorer 10.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3309]
**Reported by hyongsop.kim on 2013-06-29 07:10**
Hello, I discovered some strange things from Nvda’s browse mode.
With Internet Explorer version 10, I went to gmail with Nvda and tried to go to compose email button.
But even if I press enter key so many times, no work.
And I went to google drive and tried to go to some buttons, Nvda says these has submenu, also no work.
Could you help me how to solve this problem?
Why enter key doesn’t work?
Thank you.

**Comment by ehollig** [comment]
Closing, as this sounds like a general question that has been resolved. You can use the [NVDA nvda@nvda.groups.io](https://nvda.groups.io/g/nvda) mailing list for general questions regarding NVDA.
