### ISSUE TITLE
NVDA crashes on MozillaFirefox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3311]
**Reported by bluetek on 2013-06-29 15:25**
When starting Firefox for the ferst time or closing and reopening it. NVDA gives noe feadback when moving backwards thrue text in Google and Google based surch boxes sutch as Youtube, until focous is moved and returned. Sumtimes in these situations NVDA completely crashes.

**Comment by ehollig** [comment]
I do not get these warnings when performing a search in Google, but maybe I am missing something that has been provided in the attachment? Otherwise, I am leaning toward a close. CC @feerrenrut

**Comment by feerrenrut** [comment]
Added attachment to https://github.com/nvaccess/nvda/issues/3311#issuecomment-155307874.

@ehollig what version of NVDA are you using to test this? Be aware that release versions have warnings silenced.

**Comment by Adriani90** [comment]
@bluetek are you still having this issue?

**Comment by netblue44** [comment]
No not for a long time can close now thanks.

**Comment by leonardder** [comment]
Closing as requested. Please open a new issue along with steps to reproduce if the issue reoccurs.
