### ISSUE TITLE
Firefox: moving by word does not say punctuation immediately proceeding words

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3337]
**Reported by camlorn on 2013-07-06 13:40**
When moving by word in edit controls in firefox, i.e. the one for this ticket, NVDA is ignoring punctuation that appears to the left of words, most notably opening parentheses and quotes.  The cursor is properly placed before it as it used to be, but the symbol itself is not read as part of the word.  Examples include parentheses, quotes, and the like.  It does not seem to matter which punctuation is used.  I can't find one that works: even ` and | exhibit this behavior.
I am in symbol level most and these are properly read when moving by larger units.  In addition, moving by word across the edit control while not in focus mode works properly.
I am on Firefox 22, and NVDA next-9345,72dae8f.

**Comment by Adriani90** [comment]
@jcsteh, are there any updates on this? I think the Mozilla bug is still open. Right?

**Comment by jcsteh** [comment]
No updates yet. Yes, it's still open.

**Comment by leonardder** [comment]
Note that there are several bugs in this area, i.e. when moving by character, 32 bit unicode characters are considered one character by Firefox, whereas its IA2 implementation makes us believe that they consist of two characters. See also #9034 and https://github.com/nvaccess/nvda/pull/8953

**Comment by jcsteh** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=872397 is now fixed in Firefox 83 (currently Firefox Nightly). Thus, this issue is fixed.

**Comment by jcsteh** [comment]
> Note that there are several bugs in this area, i.e. when moving by character, 32 bit unicode characters are considered one character by Firefox, whereas its IA2 implementation makes us believe that they consist of two characters. See also #9034 and #8953

I think this should be treated as a separate issue. This is much better anyway now that #8953 is fixed. However, more complicated emoji such as 🤦‍♂️ consisting of multiple Unicode code points are treated as one character when cursoring in Firefox, but NVDA only reports the first Unicode codepoint.
