### ISSUE TITLE
n v d a is slow with Microsoft Speech Platform

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3342]
**Reported by Animesh.mr on 2013-07-07 15:33**
hi there wile i was using n v d a so i come to know that n v d   a is slow when using with
Microsoft Speech Platform 
i don't know y it is but i think that this is a bug and need to solve

**Comment by bhavyashah** [comment]
CC @jcsteh

**Comment by ehollig** [comment]
@jcsteh do you believe this is still something that NVDA can not fix? Or has a fix for sapi voices already been added?

**Comment by jcsteh** [comment]
The specific nature of the performance problem here (as compared to other software using the same synthesiser) was never clarified. #8174 does implement a fix which allows certain Microsoft voices to be interrupted faster. That may or may not be relevant here; I'm not sure. Either way, in order for this to be actionable, this needs to be re-tested and the exact nature of the issues clarified.

**Comment by Adriani90** [comment]
@Animesh.mr could you please describe a bit more what exactly the issue is? Is the speech reacting slow when you navigate with arrow keys? Or is the interuption between sentences and words too Long compared with other Synthesizers?
According to my last tests on Windows 10 with NVDA 2019.1 Beta 1, Microsoft speech platform works quite good in Terms of Performance.

**Comment by fernando-jose-silva** [comment]
I did a simple test:
In nvda I am using the voice of the one core synthesizer, I set the voice speed to 100%.
Now I logged into the narrator, went through speech settings and changed the voice speed to 100%.
The speed reached by the narrator is enormous, much greater than the speed achieved by the nvda, ambush the readers at 100%.
I expect nvda when set to 100% using the one core synthesizer will achieve much higher speeds, similar to that of the narrator at 100%.
It is a question of speed of the voice, the problem of pauses when finishing sentences is much better after the corrections implemented in the nvda.

**Comment by Brian1Gaff** [comment]
But the original item was in the speech platform ie the old ones, I imagine. 
That always was slow as its meant for telephone answering systems  I think.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment]
I tested with the old speech engine on Windows 10 and the performance is quite good. @fernando-jose-silva the speed of the voice is covered in a different issue.

I am afraid the initial author is not available anymore and we are not exactly sure what the issue actually is. So if someone can reproduce an issue similar to this, please open a new issue. I close this one for now.
