### ISSUE TITLE
NVDA indicates a landmark where there might not be one.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3344]
**Reported by HariC on 2013-07-08 10:12**
On some web sites, NVDA indicates a landmark even though such might not be the case. This happens only in Internet Explorer ten. If you visit www.PCWorld.com and go to the heading named "Don't-Miss Stories", the NVDA will identify it as "Main Landmark" -- and that is correct. However, NVDA indicates "Main Landmarks" for the subsequent links to this heading, or the links that this heading relates to, which is incorrect identification. This I assume based on how the same content is displayed in Firefox.

**Comment by leonardder** [comment]
I only see three landmarks on this page and no heading called "Don't-Miss Stories". Closing as invalid, but please provide additional details (preferable another website to test this on) if you think I'm to harsh.
