### ISSUE TITLE
Prevent Double Speaking of Menu Items in Office 2003

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3349]
**Reported by m11chen on 2013-07-09 09:58**
Currently in Office 2003 applications, the menu item labels are spoken twice: once when the focus changes to the menu bar and another time when "Report object descriptions" is enabled in the "Object presentation" Dialogue Box.  I think this might be a regression issue; since the introduction of Office 2007+ suites, the traditional pull down menus were replaced by the "Ribbon" for enhanced visual effects.

I tried to write a simple one line appModule as follows:

import appModuleHandler
from config import conf 

class AppModule(appModuleHandler.AppModule):

```
conf[= False
```

but this is not working as I expected...

Steps to reproduce:
1. Open Office Word/Excel/PowerPoint 2003.
2. press the Alt key.

Current result:
NVDA returns:
Speaking [LangChangeCommand ('en'), u'File  File Menu'](presentation][reportObjectDescriptions])

Ideal result:
NVDA should return:
Speaking [('en'), u'File  subMenu'](LangChangeCommand)
to be consistent with other Windows menu bars.

Note that the appModule that I tried to write would silence all descriptions in dialogue boxes, which is not necessarily desirable.  Can anyone help me write/modify the current appModule for the Office Suites to detect the presence of "Ribbons," and revert to just speaking the menu labels when focus changes?

Thanks in advance!

**Comment by leonardder** [comment]
Closing as won't fix, given the obsolete state of Office 2003.
