### ISSUE TITLE
Adobe Reader: Support protected PDF documents

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3350]
**Reported by ondrosik on 2013-07-09 14:28**
It seems, that some screen readers are somehow overriding the "Content Accessibility Enabled" attribute of pdf documents so the document is displayed as normal PDF document. Currently I have one document which I can not read with NVDA but I can open and read it with JAWS. After analysis of my friend it seems, that JAWS just override or ignore the mentioned attribute. As I am not owner of the document, I don't attach it here, but I can send it privately.
I am not sure about legal or technical aspects of this issue, but from the user's perspective this should be a partially good solution for protected pdf documents.

**Comment by bhavyashah** [comment]
@jcsteh You expressed a few thoughts and concerns about this ticket in https://github.com/nvaccess/nvda/issues/3350#issuecomment-155308167 almost four years ago. Might you have any updates with regards to the request given that Adobe Reader has changed significantly and is now Adobe DC/Acrobat Reader?

**Comment by jcsteh** [comment]
There have been no changes in Reader related to this.

**Comment by Adriani90** [comment]
It is still an issue, but it depends how strong the protection is. You can protect your pdf document in several ways. If the protection is not sstrong, then NVDA recognizies the text. I think @derekriemer wanted to start some research on this.

**Comment by Adriani90** [comment]
I think without a sample document we will not be able to investigate further. I am adding the blocked needs info label. If anyone has a protected pdf where this issue occurs, please attach it here.

cc: @XLTechie, @CyrilleB79

**Comment by Adriani90** [comment]
I am closing this issue as abandoned due to missing updates from users. Actually I didn't encounter any pdf document during last 5 years which was protected in such a way that is not accessible to screen readers at all. Moreover, the push towards accessible pdf is quite high so I don't think there is any case out there where the protection is that high.
However, if anyone has an example document we can test with, please comment and we can reopen.
