### ISSUE TITLE
Python should be upgraded to 3.3.2

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3355]
**Reported by Animesh.mr on 2013-07-11 10:59**
hi all i am sure that by upgrading  Python we would be able to make n v   dd  a much more stable
go hear to see what is new in Python 3.3.2
http://docs.python.org/3/whatsnew/3.0.html

**Comment by bhavyashah** [comment]
@josephsl May we close this ticket as a duplicate of the ones you recently filed to better structure this Python 3 upgrade?

**Comment by leonardder** [comment]
3.3.2 is heavily outdated anyway. Closing.

**Comment by josephsl** [comment]
See #7105 for overall design, transition plan, and progress so far.
