### ISSUE TITLE
Edsharp and braille display problems with fast typing

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3363]
**Reported by falinn.onda on 2013-07-13 13:25**
Hi,
I'm having a really weird problem when using edsharp to edit text while NVDA is connected to focus 40 braille display.

I noticed that sometimes when i type, the cursor moved to weird places. For example if i type 123123123123123 than you can expect that the text will be written as above and then the cursor will be in the end of typed text.
I noticed that many times i get an unexpected result. The text is not what i typed, same letters but in different order.
Even more strangely the cursor is not at the end of the typed text. It is few characters before the end...

It took me a while to understand that at certain point while i type, the cursor moves few characters back from where you expect it to be with no apparent reason. Then, when i type more letters they are put after the cursor so in the end i get all the letters i typed but not in the correct order.
For example 123456789 may turn as 124678953.

It is more common if i type fast and the CPU is in use. When i type really slow it doesn't happen.

If i set braille display to "no braille" i do not get this behavior at all. On notepad i did not see this happening. Just edsharp.

Someone on NVDA community told me that edsharp is a good text editor which works well with NVDA .
If there is other good text editor which is more compatible i will appreciate it if you write the name.

The display is connected via USB.
It happens both when braille is tathered to review and focus.
I am using edsharp 3.3.

**Comment by ehollig** [comment]
Closing, as this issue is over 5 years old and we are unable to contact the original author. If this is still an problem, please reopen a new issue.
