### ISSUE TITLE
Outlook 2010 Calendar: Tab Only Reads First Appointment Automatically In Month View

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3366]
**Reported by jhomme on 2013-07-16 12:36**
To reproduce, do the following.

Open Outlook 2010.

Press Control + 2 to go to the calendar.

Make sure that you have more than one appointment for the current day.

Press Alt + Control + 4 to go to Month view.

Note, you may need to go out of and back into the calendar, or out of and back into Outlook, just as long as you shift focus away from and then back to the calendar.

Press Tab. NVDA reads the first appointment for the day.

Press Tab again. NVDA doesn't read the next one.

From here on in, whether you press Tab or Shift + Tab, NVDA does not read appointments. You have to use NVDA + Tab to read the appointment you are on.

Expected behavior: NVDA would read each appointment.

**Comment by leonardder** [comment]
cc @jhomme: Can you still reproduce this?

**Comment by Adriani90** [comment]
@jhomme could you please thest if you can reproduce it?
I will try to test this tomorrow.

**Comment by ehollig** [comment]
Thank you @Adriani90 for testing. Closing
