### ISSUE TITLE
NVDA not showing buttons with Sam Broadcaster

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3378]
**Reported by ManuelRamos on 2013-07-21 22:34**
I am a SAm Broadcaster testing user. So, before, purchasing, I try this soft.

But, it occours that, from time to time, music is being interrupted for this message:
Start your online radio today
 This trial version is for a limited time 
 only. Experience the full version by 
 purchasing SAM Broadcaster PRO at 
 spacial.com or just click on the button 
 below.

 (c) 1999 - 2011 Spacial Audio Solutions, LLC., and its licensors. All rights reserved.
 See the other legal notices in this software license.

The question is that NVDA is not reporting yet those buttons.

If possible I would NVDA to show buttons, for example which one that, makes desappear that tedious message.

Thanks.

**Comment by ehollig** [comment]
Closing because of https://github.com/nvaccess/nvda/issues/3378#issuecomment-155308397
