### ISSUE TITLE
Microsoft Word 2010, NVDA Doesn't Say All Selected Text In Table Cell When Tabbing To It.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3383]
**Reported by jhomme on 2013-07-25 16:29**
To reproduce:
1. Open Word 2010.
2. Go to the Insert tab and create a table with one row and two columns.
3. Put text in both cells of the table that you know is going to be more than two lines long.
4. Use Tab and Shift Tab to go back and forth between the cells.
5. Expected behavior: NVDA should read all of the text, because it is selected. It only reads the first line of the cell.

**Blocked by #2295**

**Comment by bhavyashah** [comment]
Based on @michaelDCurran's https://github.com/nvaccess/nvda/issues/3383#issuecomment-155308443 as well as my testing with Word 2010, this issue has clearly been fixed. Thus, I suggest closing as worksforme. @ehollig

**Comment by ehollig** [comment]
From testing performed in https://github.com/nvaccess/nvda/issues/3383#issuecomment-322670645, closing
