### ISSUE TITLE
Possible interaction of NVDA with IE8 and Outlook Express in XP

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3395]
**Reported by briang1 on 2013-08-02 08:14**
Now this is a strange an long running problem which has been around for some years now. I have mentioned it before on the dev list, but recengtly decided to attempt to prove it had something to do with nvda. What I did is rigged up a machine that I know has the issue. Thiswas not hard as all XP machines do!

 I then made it work with an old copy of Hal by default and ran it for a few days to see if the issue came up. It did not, but it did if i closed Hal and used nvda again after just half an hour, so its very  peculiar. Now nobody else seems to have  mentioned it, so it could still be something else on my machines that interacts with nvda causing the strange symptoms. anyway, I present what I know here and you can decide what to do.

How to make  things go wrong.
 Machine running XP pro with all updates.
Outlook Express as default email and news reader reading in  plain text mode
IE8 as default browser
Only add on which is possibly not usual is Simple Ad Block, the early free version. All other add ons are normal like flash etc
Javascript enabled

How to get problems.
There are two main issues, on affecting Outlook Express, and one  IE.

 read email and newsgroups for a while and  when you see a link to a web site,  make display go to html, I did it via the view menu and click the link. View the pag or pages and  then close IE
After some time of reading and replying to emails and news messages one of the following effects happens
You cannot open an email or news posting, Outlook Express complains of not enough memory
or
it will tell you you cannot view the rest of a message as it has not yet been downloaded.
or
when you try to reply or start a new message, it will allow you to enter email addresses and sub lines, but when you tab to the main edit area, nvda just sayd pane, and nothing you type will go into the message. When you attempt to sent the blank page it complains of issues with spelling or character set mismatches and goes around in circles, obviously completely confused what is going on.

The only way out of this is to shut Outlook express, and restart it, and all returns to normal. Closing  nvda will make no difference.
 The IE issue is more simple, and I'm grouping these as it may well be  the same issue.
If you restart nvda or boot in a different version while IE8 is running about 1 time in 3, IE will not be there after the reboot. it just disappears, and is not visible in the task manager.

In the Outlook  Express issue, the effects seem to be lack of memory, but the memory usage does not go out of what is normal for the software from what I can see in Task manager, so it is a bogus report.
 This has as I say been the case for a long time for me, and yet as nobody else has reported it and we do have a lot of xp users, I am at a loss to know what the issue really is here.
Nothing untoward is ever visible in nvda or its log.

**Comment by leonardder** [comment]
XP specific issues won't be fixed any more, unless really critical. Closing as wontfix.
