### ISSUE TITLE
In outlook 2013, misleading msg as not checked is announced in thenavigationmenu when navigating with the ARROWS.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3405]
**Reported by sumandogra on 2013-08-05 09:34**
Outlook 2013
On navigating in the navigation menu each item is announced as not checked.  Could not understand why it is announced as such on pressing enter or spacebar the item does not get checked.
Steps to reproduce:
Press F6 to go to the navigation bar grouping navigation menu.
Use ARROWS to navigate in the menu.
After each item, not checked is announced.

**Comment by leonardder** [comment]
@sumandogra: Can you still reproduce this?

**Comment by ehollig** [comment]
Closing as invalid, as we have not heard from the original poster. If this is still an issue for @sumandogra: or others who may use Outlook 2013, we can reopen this issue.
Note: in Outlook 2016 in the navigation bar, NVDA reports these buttons as pressed or not pressed.
