### ISSUE TITLE
on navigatingwith ARROWS each itemis announced as not selected in the folders tree view in Outlook.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3406]
**Reported by sumandogra on 2013-08-05 09:37**
Outlook 2010 and Outlook 2013
On navigating in the folders tree view, not selected is announced on reaching a folder.  For example on reaching inbox NVDA announces “not selected” before announcing inbox.
Steps to reproduce:
PressF6 to go to the folders tree view in Outlook.
Now, use UP/DOWN ARROW to navigate in the folders tree view.
NVDA announces “not selected” before announcing the folders name.

**Comment by leonardder** [comment]
Closing as invalid, since this is expected behaviour, as moving to the folders list doesn't select the folder. You have to do that explicitly using enter. At least, that is what I recall from my past experiences with Outlook 2013.

Please request a reopen if you belief I'm in error.
