### ISSUE TITLE
On using NVDA+F7 IE window looses the focus and one has to ALT+TAB to go back to IE window.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3408]
**Reported by sumandogra on 2013-08-06 08:33**
Using NVDA+F7 to get the elements list, focus is lost from the Internet Explorer window.  If one selects a link from the elements list, the focus is not on IE instead on the desktop or some other window opened other than IE. One has to use ALT+TAB to go to the IE and read the page.
Steps to reproduce:
1.  Open any web page that has elements on it for example, www. Nvda-project.org
2.  Press NVDA+F7
3.  Select community from the elements list.
4.  Focus is on the desktop as only IE is open. In other words IE looses the focus and one lands on either desktop or some other window opened other than IE.
One has to use ALT+TAB to go to the IE.

Note:  this is not observed in Windows 7.

**Comment by ehollig** [comment]
I am not able to replicate this issue on Windows 10 using IE 11. Could someone using Windows 8 and IE 10 please test this?

**Comment by bhavyashah** [comment]
I cannot reproduce this issue with Windows 8.1 and internet Explorer 11 either. Unless @sumandogra can still replicate the reported issue, I suggest closing. @ehollig 
P.S. Are we taking IE 10 specific issues into consideration anymore? IE 11 is within radar and IE 8 and 9 are not, but I am unsure of IE 10.

**Comment by ehollig** [comment]
As far as I am aware, if the issue can be replicated in IE11, then we will take it. Users of Windows 7 do have the option to upgrade to the latest version of IE, which is IE11.
Closing this as worksforme, but if the problem still exists, please create a new issue with exact detailed steps to reproduce, including what you did, what you expected to happen and what happened instead.
