### ISSUE TITLE
Password for Lync 2013 is read out

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3411]
**Reported by nickbi on 2013-08-06 16:17**
NVDA is able to read out characters and the whole string in the password field in Lync 2013. 

When logging in, user can type in the password and have the masked characters read out by either backspacing or using the left/right arrow keys. User can also have the whole password read out back selecting all the text in the field.

**Comment by leonardder** [comment]
This is most likely a bug in Lync, as NVDA just reads what is exposed to it using accessibility APIs. Given the abandoned state of this ticket, closing with needs external fix. Please provide additional details if you really think that NVDA is doing something wrong here.
