### ISSUE TITLE
NVDA not allowing full text expansion

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3412]
**Reported by jusmail on 2013-08-06 16:52**
Often, I use typepilot, a text expander program. To type the word yesterday, I might use yd which automatically expands to yesterday. When I use NVDA, when I type yd, what I get is "ydyesterd", and as you can notice, the first two letters are added in the start, while 2 letters are omitted from the phrase itself. I also use Window Eyes in which I do not face the problem. Hope there is a fix for this. Thanks

**Comment by leonardder** [comment]
Closing as invalid, since the author seems to have abandoned this and it is not possible to track down the author. Also, it seems that typepilot operates within a text editor like notepad or word, and we really need information on what editor it is used with.
