### ISSUE TITLE
With keyboard echo enabled, pressing the Plus key on the numeric keypad within Calculator does not speak

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3430]
**Reported by dgoldfield on 2013-08-09 19:27**
While working in the Windows 7 calculator program, the Plus key on the numeric keypad will not speak, even if keyboard echo is enabled.

Steps to Reproduce:
1. Open the Calculator program.
2. Ensure that the speaking of typed characters is enabled via the insert-2 hotkey.
3.  Ensure that numlock is turned on.
4. Press the plus key on the number pad.  The key is silent.

**Comment by ehollig** [comment]
This works correctly in Windows 10,1703. Which version of Windows is this referring to? CC @Brian1Gaff, if you are able to test this on Windows 7

**Comment by ehollig** [comment]
This is just a friendly reminder for @Brian1Gaff to test and see if this is still the case in the calculator on Windows 7.

**Comment by Adriani90** [comment]
@dgoldfield, @Brian1Gaff is this issue still reproducible on Windows 7?

**Comment by lukaszgo1** [comment]
Still reproducible on Windows 7 and 8.1

**Comment by Adriani90** [comment]
I don't have a keyboard with numpad at hand, can any one test if this is also occuring on Windows 10 or 11? cc: @lukaszgo1

**Comment by Adriani90** [comment]
This is probably due to NVDA catching the whole UIA event showing what you typed from the beginning. But maybe I am wrong. @josephsl is it possible to tell NVDA to catch only a part of the UIA Event, say only the last typed character?

**Comment by josephsl** [comment]
Hi,

By default UIA notification event handler will announce the text sent by the app in its entirety. It might be a bit risky to announce only the last part of this text - it could be an operator like plus, a number, parts of the number being entered, and so on. What Cyrille reported is what gets announced with speak typed characters on and with UIA notification event right after. Thankfully, NVDA will not announce numbers twice.

Right now the Calculator being discussed is a different app than the Calculator referred to in the original posting (203 versus 2023), so speaking of one is speaking of a different issue.

Tanks.

**Comment by lukaszgo1** [comment]
According to https://github.com/nvaccess/nvda/pull/15377#issuecomment-1707518418 this is still reproducible in the Win32 based calculator on LTSC versions of Windows 10. I suggest labeling as P5. Also what @CyrilleB79  described above affects the modern UWP calculator, so that probably should be reported as a separate issue.

**Comment by Adriani90** [comment]
@dgoldfield Is this also reproducible in Windows 11?
@CyrilleB79 is the interuption of the typed + character still hapenning in Windows 11 24 H2?

**Comment by CyrilleB79** [comment]
@Adriani90 I am not able to test on Windows 11, I am still with Windows 10.
