### ISSUE TITLE
Header landmark announcing problem

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3433]
**Reported by oaron on 2013-08-11 19:59**
In html5, when website contains header html tag, NVDA announces "banner landmark", but this landmark is connecting with head of the page.
Here is an example: http://www.nvda.hu/html5test.html

**Comment by ehollig** [comment]
Closing for reasons in https://github.com/nvaccess/nvda/issues/3433#issuecomment-155308828 posted by @jcsteh
