### ISSUE TITLE
The name of the sheet in Excel is not announcedwith CTRL+PG UP/PG DOWN.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3435]
**Reported by sumandogra on 2013-08-13 12:15**
The sheet names are not announced in Excel on using the CTRL+PAGE UP/PAGE DOWN commands.

Steps to reproduce:
1.  Open MS Excel workbook that has multiple sheets with different names.
2.  Now press CTRL+PG UP/DOWN to move the between sheet.
3.  NVDA does not announce the name of the sheet names.  Even if there are no names assigned NVDA does not announce sheet 1 or sheet 2 etc.
4.  One can open an empty workbook and move with the CTRL+PG UP/DOWN to verify.
5.  This is observed in Excel 2010 and Excel 2013.
6.  s

**Comment by ehollig** [comment]
Closing. This works correctly for me in Excel 2016 and others have also reported that it works for them in other versions. As we are unable to contact the original poster, closing
