### ISSUE TITLE
Can't access the new Outlook website with NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3440]
**Reported by Brendon22 on 2013-08-14 07:05**
Hello,

When logging into your  Outlook email account on the website https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=11&ct=1332305003&rver=6.1.6206.0&wp=MBI_SSL_SHARED&wreply=https:%2F%2Fhome.live.com%2F&lc=3081&id=251248&cbcxt=hom&mkt=en-AU, and you try and access your list of emails, you are unable to access them. The checkboxes don't work on this page, and the links for opening a message don't work when pressing enter on them know matter what web layout you have turned on in NVDA. This broke when the website changed from Hotmail to Outlook. Using the latest version of master.

Thank you.

**Comment by bhavyashah** [comment]
@brian1gaff @michaelDCurran Is this still the case with the current form of Outlook on the web? Regardless, it doesn't seem to me that NVDA has scope for a fix, rather Outlook authoring needs to be corrected.

**Comment by ehollig** [comment]
This indeed does sound to be a website authoring issue. As stated by @michaelDCurran in https://github.com/nvaccess/nvda/issues/3440#issuecomment-155308873
> The checkboxes and the email subject links only seem to listen manually for key or mouse events.
This would indicate that NVDA would not be able to fix this issue. Closing as cantfix

**Comment by Brian1Gaff** [comment]
This has been mentioned on RBNIB Connect radio in Techtalk apparently and 
seems to be a web issue in a recent update to the system.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- O
