### ISSUE TITLE
RGB values of colors are announced in the automatic color of font dialog in MSWord 2013.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3443]
**Reported by sumandogra on 2013-08-15 08:41**
RGB values are announced along with the color names in the font dialog in MS Word2013.
Steps to reproduce:
1.  Open MSWord.
2.  PressCTRL+D.
3.  TAB to Automatic color and Press DOWN ARROW to get the colors.
4.  Avigate in the colors with ARROWS.
5.  theRGBvalues are announced.

**Comment by leonardder** [comment]
RGB values are provided by Word as the description of the IAccessible object. This is not a bug, and you can disable this for Word by disabling reporting of object descriptions. Closing as invalid.
