### ISSUE TITLE
new options should be added to the installer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3445]
**Reported by Animesh.mr on 2013-08-16 05:55**
hi all advance options to installer should be added it will make us possible to make n v d a the way wee want to  such wee would be able to remove features that wee don't want to use see the installer of win amp for explanation of this idea thanks

**Comment by bhavyashah** [comment]
There are hardly any benefits to this proposal, IMHO. Plus, the potential confusion this may cause to newbie users, keeping in mind the fact that NVDA is the most fundamental and vital companion for any blind computer user, also needs to be taken into account. As noted by @brian1gaff earlier, saving a few bytes, or at most, a few megabytes, is pretty pointless at the risk of causing extraneous convolution to the process of installing NVDA in a world with massive HDDs and SSDs where NVDA is a relatively lightweight software in its present state itself. With all due respect, I would like to kindly suggest turning down this request and closing this ticket. @leonardder

**Comment by ehollig** [comment]
I think @bhavyashah summarized it pretty well in https://github.com/nvaccess/nvda/issues/3445#issuecomment-319979892. Closing, unless someone may disagree.
