### ISSUE TITLE
Chrome treeInterceptor isn't initialized on simple web pages

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3451]
**Reported by mherrmann.at on 2013-08-19 07:55**
''NVDA version: 2013.1.1
OS: Windows 7, 64 bit
Chrome version: 28.0.1500.95 m''

When starting Chrome with a simple (non-JS) web page, Chrome's treeInterceptor is not initialized until one switches away from, and then back to the Chrome window.

'''How to reproduce:'''
- Close all open Chrome windows.
- Start NVDA 2013.1.1.
- Open the file "HelloWorld.html" attached to this ticket. This is a simple HTML page with title "Hello World" and body contents "Hello World in body". NVDA correctly reads the two texts.
- Open the NVDA Python console.
- Enter "from api import getMouseObject" into the Python console.
- Hover (but do not click!) the mouse cursor over the HTML page, so NVDA reads "Hello World in body"
- With the keyboard focus still in the Python console, type "getMouseObject().treeInterceptor".

'''What is the expected behaviour?'''
After the last step, NVDA's Python console should contain a text similar to "<appModules.chrome.ChromeVBuf object at 0x066360B0>".

'''What do you see instead?'''
The Python console does not print the above line, meaning that the treeInterceptor is None. 

When you switch to the Chrome window, back to NVDA's Python console and perform the last steps from above again, treeInterceptor is no longer None. It appears as if the treeInterceptor was not correctly initialized upon startup, but once the Chrome window has actively been switched to at least once, the treeInterceptor is defined. 

The problem with the above is that it makes it impossible to use treeInterceptor functionality in newly started Chrome windows. Interestingly, the problem does not seem to occur for more complex (JavaScript-heavy) applications. Maybe this problem is related to ticket #2700?

**Comment by ehollig** [comment]
Acording to Google Issue [Chromium:347448](https://bugs.chromium.org/p/chromium/issues/detail?id=347448) it appears this was fixed in May 2014. Can this issue be closed? I am not able to test this with the attachment, as it is unavailable.
