### ISSUE TITLE
Suppress API calls (during say all)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3453]
**Reported by leonarddr on 2013-08-20 11:19**
Sometimes when reading a piece of text, the reading is interrupted by API speak messages, for example when my twitter client gets new incoming messages. It would be handy wen incoming API messages could be muted/ignored, at least during say all. This could be accomplished in two ways:
- A new option, "suppress incoming API messages during say all".
- A general "Suppress incoming API messages" option, which can be specified in say all only cases using the new configuration profiles.

**Comment by leonardder** [comment]
I'm not sure whether I still consider this request to be valid. Actually, there's a reason why you want a message to be spoken by NVDA when using the API, so interrupting say all makes sense.

**Comment by bhavyashah** [comment]
@leonardder Given the fact that you are the original author of this ticket coupled with your now contrarian stand about this feature request in https://github.com/nvaccess/nvda/issues/3453#issuecomment-317187804, may we safely close this ticket as a wontfix (or invalid)?

**Comment by leonardder** [comment]
Yes, I'll close this for now and will file a new ticket as soon as #7599 is merged. This will open up new possibilities, including optionally providing the priority of a speech message to the API.
