### ISSUE TITLE
Oddity in outlook Express  message rules - select an action for your rule

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3459]
**Reported by briang1 on 2013-08-21 16:12**
When operating the checkboxes with space, no condition is read. However  the condition does in fact change when you press space. In the  first list where  you select the basis for the rule this same action works perfectly.
 I did not notice when this stopped working but the last realease still has the  quirk. Its not mega serious, but thought it worth mentioning in any case.

**Comment by ehollig** [comment]
Outlook Express has been replaced by Windows Mail in later versions of Windows according to [Wikipedia](https://en.wikipedia.org/wiki/Outlook_Express). This sounds like an XP specific bug, which only critical bugs are being addressed. Closing as wontfix

**Comment by Brian1Gaff** [comment]
bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Brian1Gaff** [comment]
Actually this problem no longer seems to have occurred recently even on the 
modified version of Outlook express I use in windows 7 and 10, so I'm 
wondering if its accidentally been sorted out by another update.
 Tested on both master and Next branches. I use message rules a lot to sort 
emails, and have had no problems
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
