### ISSUE TITLE
braille user

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3479]
**Reported by kroksland on 2013-08-29 17:00**
Hey
I just updated nvda today and I'm not pleased at all. I'm using nvda at work with a braille display and it has always been perfect. I'm not using speach at all. But now, when for example when I've done a google search and use H to navigate between headings fast, the title/link-text simply disapears. If I want to read what I'm actually looking at I have to arrow up and down and hope the title appears as soon as possible. The same with facebook, when I get a notification and I hit enter on it to check it out and arrow down to read it, the link disapears but the text beneath explaining how long ago it happened still remain. To see what the notification is I have to arrow up and down a few times and then it might appear on my alva bc640. Perhaps this sounds a little confusing, but english isn't my native language. I'm currently using firefox, but I have tried chrome and IE and the problem remains. This is a serious problem for me.

**Comment by ehollig** [comment]
Closing, since the original poster did not comment or answer any of the questions above and we are not able to contact the original poster.
