### ISSUE TITLE
word spell checker enhancements

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3482]
**Reported by manish on 2013-08-30 11:02**
In the spell checker in word, speak and spell the currently selected suggestion along with the error text when error text is spoken automatically.
In addition, when moving among the suggestions list using the up and down arrows, after speaking the current selection, also spell it out. This makes differentiating between similar sounding suggestions easier without having to use the review cursor on every suggestion.

**Comment by leonardder** [comment]
This sounds like changing the behaviour of the spell checker in a more general way, not only related to Word 2017. I agree that stuff could be improved a bit to make things work somewhat more intuitive, for example, you need object navigation in Word 2016 to find the actual misspelled word.

**Comment by leonardder** [comment]
This is related to #3410, but this is from an enhancement perspective. #3410 has a priority of P3. @JCSTeh, Should we treat these as one and close this one in favour of #3410?

**Comment by feerrenrut** [comment]
Duplicate of #3410.
