### ISSUE TITLE
A new setting to configure the used review mode

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3486]
**Reported by kredh on 2013-09-02 13:01**
It could be useful to have a setting to use a specific review mode. This would be particularly useful when a specific profile is being used: we could configure a specific application to be read with text review or object review (and will have the possibility to switch back, if needed).

**Comment by bhavyashah** [comment]
At least on the surface, this feature request makes sense to me. Simply put, review modes should be attachable to configuration profiles. Please change labels from enhancement to feature. @ehollig

**Comment by Adriani90** [comment]
@leonardder actually now the braille tether is profile specific, so users could specify the tether to review for some applications at least for braille.
For speech, I would rather discuss further on #7749. I would vote for closing this one in favor of #7749.

**Comment by Adriani90** [comment]
More discussion is in #7749. Closing this in favor of the referenced request.
