### ISSUE TITLE
Ref bug#3418-inExcel2013 an item, an edit control is announced when one starts typing in a cell.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3487]
**Reported by sumandogra on 2013-09-02 13:41**
Excel 2013
edit an item an edit control
 is announced when one starts typing in Excel 2013 or whenoneshiftsto the edit mode with F2.
Steps to reproduce:
1.  Start typing in a cell in Excel 2013.
2.  as soon as the first value is typed,NVDA announces edit an item an edit control.  
3.  Press F2.
4.  Again an item an edit control is announced.

**Comment by leonardder** [comment]
I can't reproduce this for Excel 2016. However, if you are already editing a cell, pressing f2 again isn't something someone would normally do anyway. Closing as invalid, but please provide additional details (e.g. a use case why you think this should really be fixed)

**Comment by ruifontes** [comment]
Hello!

1 - Open an Excel file;
2 - In any cell start typing;
3 - Expected feedback:
Edit. character typed.
4 - Real feedback:
Edit. One edition box. Character typed.

Regards,

Rui

-----Mensagem Original----- 
De: Leonard de Ruijter
Data: 10 de julho de 2017 20:42
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Ref bug#3418-inExcel2013 an item, an edit 
control is announced when one starts typing in a cell. (#3487)



I can't reproduce this for Excel 2016. However, if you are already editing a 
cell, pressing f2 again isn't something someone would normally do anyway. 
Closing as invalid, but please provide additional details (e.g. a use case 
why you think this should really be fixed)

**Comment by jcsteh** [comment]
I can't reproduce the original reporter's behaviour regarding pressing f2 while already editing. However, I think this issue might be referring to the pointless "an edit control" description that Excel exposes when editing. It also exposes a label of "Edit item", but this arguably isn't extraneous; it differentaites it from "Comment" or similar.

**Comment by leonardder** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [11 jul. 2017 00:51 CEST](https://github.com/nvaccess/nvda/issues/3487#issuecomment-314272283 "2017-07-10T22:51:20Z - Replied by Github Reply Comments"):
> I think this issue might be referring to the pointless "an edit control" description that Excel exposes when editing. It also exposes a label of "Edit item", but this arguably isn't extraneous; it differentaites it from "Comment" or similar.

This is indeed where @ruifontes refers to. Personally, I don't think we should do anything about this, since its exposed by Excel and can be easily silenced when you start typing. I agree the description is obnoxious.

**Comment by jcsteh** [comment]
@MichaelDCurran, might be worth filing a bug with Microsoft about this.
