### ISSUE TITLE
Mixx DJ application crashes when NVDA is running

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3490]
**Reported by ondrosik on 2013-09-02 16:45**
Mixxx is an open-source QT based DJ software. I am doing a private radio show with it in Irregular time. When recent stable, Master or Next branch version of NVDA is loaded, Mixxx crash in various situations, mostly when I try to load file to deck 1 or 2.
When I run Portable nvda 2011.1, everithing works e. g. I did a two hour show yesterday without any issues. When I switch back to current stable version, I can freeze it during few seconds, in better times during 10 minutes.
I took all stable versions and I noticed that the freeze starts in 2013.1.1. E. g. I can use 2012.3.1 without any issue but when Switching to 2013.1.1, Mixxx will soon or later crash. On my system the crash mostly freezes nvda so I have to restart NVDA as well, but in rare cases NVDA woke up after a while.
I can not see nothing related in the mixxx log, but bunch of debug information in the NVDA log (see attached file).
My configuration is Win 7 64-bit, Mixxx 64 or 32 bit (I tryed both with same results). I use QT accessibility lybrary for better mixxx accessibility howewer, when I delete the accessibility lybrary it freezes too (I can do things by memory so when tested I tryed to open two files and play them. This can be done with keyboard without additional assistance).
I can reproduce this also on my old XP machine but recently the mixxx behaves strangely here due to fact that the computer doesn't work good at all so I didn't use the xp old computer for recent testing, but I can if this will be important.

What I need to improve this ticket:
Try old version or current beta version of mixxx, I am currently using version 1.11.1-pre-bzr3881. I remember that I used mixxx 1.9.something earlyer so I can try, what happens when I move to this version
Get experience from other users, I know two people, who can test this. They reported that mixxx crashes sometimes but they didn't tested if old version of NVDA works better.

**Comment by jcsteh** [comment]
Unfortunately, QT 4 seems to have some serious accessibility bugs that have never been fixed. While earlier versions of NVDA may not have triggered these problems, QT 4's accessibility support just isn't solid enough to justify trying to work around this. Closing.
