### ISSUE TITLE
Trac doesn't allow me to change e-mail

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3496]
**Reported by leonarddr on 2013-09-04 10:43**
When trying to change my e-mail address, i get:
> Warning: Incorrect response to spam prevention question. 

There however is no way to answer or find this spam prevention question.

**Comment by derekriemer** [comment]
This should be closed as it has to do with track which we don't use any longer.

**Comment by jcsteh** [comment]
No longer relevant now that we're on GitHub.
