### ISSUE TITLE
NVDA does not write correctly in some cases in word, and IE

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3510]
**Reported by lallerkee1 on 2013-09-10 07:53**
When writing in a multi line edit box, such as this box, when creating this ticket, nvda's reaction is too long, and it writes the characters not the requested way.
For example I write this line slowly, and it is good:
I am at home, and making a bath.
I am writing it quickly, and it is the written text:
  I mathome a making a bth.
This appeares in the microsoft word programm, but only in version 2010, and 2013.

**Comment by Adriani90** [comment]
@lallerke1 are you still having this issue? It seems very specific. Did you try to run the com fixing registration tool in NVDA menu / tool and see if it is still occuring?

**Comment by Adriani90** [comment]
@lallerkee1 can you still reproduce this issue in NVDA 2019.1.1?

**Comment by Adriani90** [comment]
I am closing this issue as we do not have any updates from the author since years. This issue seems very specific and cannot be reproduced by everyone. If you are still having this issue, please comment on it and we can reopen the discussion. Thanks.
