### ISSUE TITLE
When navigating in windows 7 start menu, and windows 8 start screen, or in control panel, speech is not always there.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3511]
**Reported by lallerkee1 on 2013-09-10 08:02**
When I would like to search something in windows 7 start menu, or in windows 8 start screen, speach is not alwais done. I tried it with uac, and without uac. Both did not resolve the problem. It has resolved for 2 minutes, when I changed the category view in control panel, or I put it in the full screen.

This problem exists long ago, but in windows 7 has not so big effect, than in windows 8, because windows 7 start menu is not alwais needed, then start screen.

**Comment by Adriani90** [comment]
I cannot reproduce it in Windows 8.1 with NVDA 2017.3. @lallerkee1 can you still reproduce it?

**Comment by Adriani90** [comment]
@jcsteh the user Name of the author of this issue is not valid anymore. I suggest closing this issue and reopen it if someone reports it again.

**Comment by ehollig** [comment]
Thank you @Adriani90 for your testing. Closing
