### ISSUE TITLE
In Firefox,text written in multiline edit fields is not read with ARROWS in Gmail.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3520]
**Reported by sumandogra on 2013-09-12 08:06**
In Firefox, the text written in multiline edit fields in Gmail standard view is not read with ARROWS. 
Steps to reproduce:
1.   In Firefox, logon to a Gmail account.
2.  Select a received email.
3.  Select the reply button.
4.  Write in the multiline edit field.
5.  Use ARROWS to read the text.
6.  The text is not read.

**Comment by Adriani90** [comment]
This is not reproducible with NVDA 2018.4 RC1 and Firefox 63.0.3.

**Comment by Adriani90** [comment]
Closing as works for me.
