### ISSUE TITLE
Suggestion-NVDA automatically brings the audio levels to the one predefined by the user

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3521]
**Reported by sumandogra on 2013-09-12 09:21**
Quite often when a system is shared by able bodied members of a family or at workplace, the sighted person mutes the volume or reduces it to an unusable level.
Suggestion is whenever NVDA starts, it should unmute the audio and sets the level predefined by the user.
It can take care of such situations.

**Blocking #4602**

**Comment by bhavyashah** [comment]
Similar (enough to be a duplicate?) to #3049

**Comment by leonardder** [comment]
Agreed, although slightly different in approach. Closing as duplicate of #3049.
