### ISSUE TITLE
Miranda NG, first message after NVDA load isn't being read.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3523]
**Reported by leonarddr on 2013-09-12 10:59**
Quite a small and insignificant bug. When NVDA is restarted or first loaded and you receive or send a message in Miranda NG when the message window is focused, it isn't being read by NVDA. Also, you can't read the message back using ctrl+nvda+1. This occurs only for the first message received or sent after NVDA load, the second message and all the future messages are being read as expected.

**Comment by leonardder** [comment]
Since Miranda IM and Miranda NG are basically the same, closing this as a duplicate of #2519
