### ISSUE TITLE
Switching synthesizer using synth settings ring

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3529]
**Reported by leonarddr on 2013-09-16 09:22**
We could change voice, rate and volume as well as other settings of a synthesizer on the fly using the synth settings ring. It would make changing synths on the fly easier if synthesizer selection itself could be added to the ring. This wil raise the issue that when selected the no speech synthesizer, NVDA won't announce the selection of "no speech", which can be fixed by announcing "No speech" with the previously selected synthesizer. For hardware synthesizers, availability of such synthesizers could be checked on selection, and when not detected, "synth name (not detected)" could be spoken using the previously selected synthesizer.

**Comment by leonardder** [comment]
Duplicate of #2590
