### ISSUE TITLE
The list items in folder view of choose add on package in the add on manager are announced  twice.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3531]
**Reported by sumandogra on 2013-09-16 23:53**
The list items in the folder view tree view of choose add on package dialog of add on manager  are repeated twice.
Steps to reproduce:
1.  Go to NVDA menu with NVDA+N.
2.  Go to Tools and then to Manage Add on
3.  Select the Install button.
4.  SHIFT+TAB to the folder view tree view.
5.  Use first letter navigation or UP ARROW/DOWN ARROW.
6.  Each item is announced twice.

**Comment by ehollig** [comment]
this is still the case with the latest NVDA. CC @jcsteh

**Comment by Brian1Gaff** [comment]
As a matter of interest, this can sometimes be three times if you have speak 
tooltips on, but not always. Could it be being refreshed using that mega 
slow UIA routine that often causes issues in explorer, as this looks and 
feels like an explorer window with some extras bolted on.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- O

**Comment by jcsteh** [comment]
This occurs because we explicitly disable UIA for NVDA's own process, since that previously caused freezes and other weirdness due to the UI Automation Client in Windows. I'm not sure if this is still the case in Windows 10.

**Comment by josephsl** [comment]
Hi, still causes a freeze when running from source in Windows 10.

**Comment by josephsl** [comment]
Hi, at least it doesn’t freeze in Version 1809 from what I can tell. Thanks.

**Comment by Adriani90** [comment]
Is this then possible to enable UIA on NVDA's own process only on Windows 10? If this does not freeze on 2809 Update it is actually a green light for doing this.
cc: @michaelDCurran

**Comment by Adriani90** [comment]
This is fixed in NVDA alpha-20097,6a573cd9. Closing as works for me.
