### ISSUE TITLE
No announcements in speech settings ring in GW Connect

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3537]
**Reported by noshark on 2013-09-20 15:18**
Although the values of settings can be changed using the ring, there are no announcements of parameter type or values when using the ring when GW Connect has focus.

This happens with latest Master and Next but not with 2013.2.

**Comment by jcsteh** [comment]
GWConnect [no longer exists](https://www.gwmicro.com/News_&_Events/Latest_News/?newsNo=317). Closing.
