### ISSUE TITLE
hover a image link with a mouse. NVDA reads the content of src of image

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3552]
**Reported by xoxa2004 on 2013-09-26 15:01**
In chrome, hover a image link with a mouse. NVDA reads the content of src of image.
​https://mondossiercitoyen.gouv.qc.ca/General/index.aspx - an example.

**Comment by Adriani90** [comment]
@xoxa2004 I am not able to reproduce this issue in NVDA 2019.1.1 and Chrome 74. Are you still having this problem?
cc: @Qchristensen

**Comment by Qchristensen** [comment]
I can't reproduce this just now either, although there are other issues with mouse tracking on the web.

**Comment by Adriani90** [comment]
Closing as works for me.
