### ISSUE TITLE
Button with aria-disabled="false" still announced as "unavailable"

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3565]
**Reported by hhillen on 2013-10-08 17:04**
When a button both has disabled="disabled" AND aria-disabled="true", and both those attributes are turned off at the same time (i.e. disabled="disabled" is removed, and aria-disabled is set to "false") then NVDA still announces the button as "unavailable". 

It seems NVDA does not update the virtual buffer properly: Refreshing the buffer with INS+F5 makes NVDA announce the button correctly again. The issue is avoided when only one of "disabled" or "aria-disabled" are used, but it would still be useful if this can be fixed on the NVDA side.

Test case has been provided on https://dl.dropboxusercontent.com/u/573324/testcases/bugreports/NVDA/test_case_aria_disabled_virtual_buffer.html (also attached).

To use this test case:
1. Tab to the third button, labelled "Toggle both aria-disabled AND disabled", and activate it. This will apply both attributes on the fourth button, which is labelled "save".
1. Activate the third button a second time. This will remove the disabled attribute and set aria-disabled="false"
1. Press tab to move focus to the next button, labeled "Save". NVDA will now incorrectly announce it as "unavailable".
1. Use the NVDA + F5 shortcut to refresh the virtual buffer. Now the button will be announced correctly again.

Note that the page in the test case also has controls that toggle only the disabled attribute or the aria-disabled attribute. The issue only occurs when both attributes are turned off at the same time.

**Comment by ZeikJT** [comment]
The mozilla bug was fixed.

**Comment by santospro** [comment]
Hi all, is there a way to don't read 'unavailable' in a self-disable button?
[example](http://codepen.io/anon/pen/BLBBKO)

**Comment by jomoji** [comment]
Hi @csantos1113, in your [example](http://codepen.io/anon/pen/BLBBKO) tested on NVDA 2019.2.1 if you mantain aria-disabled="false" instead on change it to "true" it seems that the reader prioritizes the aria-diabled attribute rather than disabled attribute. And my NVDA dont tell me unavailable once it changes after click
