### ISSUE TITLE
Support for Citrix environments

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3572]
**Reported by mustafa on 2013-10-10 22:30**
NVDA does not support Citrix environments currently, but it would be very important to implement this because this would be useful in professional environments. I mean by this implementing network installations and support for virtual synthesizers and virtual braille.

**Comment by leonardder** [comment]
Closing as duplicate of #3564. @camlorn is right in https://github.com/nvaccess/nvda/issues/3572#issuecomment-155310194
