### ISSUE TITLE
NVDA not reading "All Programs" supbmenu on Windows XP SP 3.  Just started happening the other day and I can't fix it.  Tried reinstall.  Also not reading Internett Explorer 8.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3580]
**Reported by controlmasterp on 2013-10-15 12:55**
None

**Comment by ehollig** [comment]
This is an XP issue and has not been touched in 5 years, so I assume that the problem is fixed or can be closed.
