### ISSUE TITLE
Excel: detect more formatting information in Excel

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3583]
**Reported by vrdhn on 2013-10-16 17:17**
Filing this as excel part of the ticket #1680

This is the excellent list prepared by Suman:

Formatting in Excel

written by: Suman Dogra
Date: August 29, 2013

number category:
typeof data:
genral
number
currency
date
time
percentage
fraction
scientific
text
special
custom

decimal
the number ofdecimalplaces to be notified

the type of currency  to benotified
if fraction
towhat digit should benotified

if special the type ofcode to be notified

horizontal alignment-
genral
left affect
centre
right affect
fill
justified
centre across selection
distributing affect

effect number
vertical-
bottom
justified
distributed

wrappedtext
merged cell
degrees
text controlfromrightleft
text ornot
textdirection-
context
left to right
right to left

font name

font style-
regular
italics
bold
bold italic

font size

strike through
superscript
subscript

underline-
single
double
single accounting
double accounting

font color

cell border-
thin
double
medium
slanteddash dot
mediumdash dot
hair
dotted
dash dot dot
dash dot
dash

cell border color

celloutline
top
left
right
bottom
diagnol down

diagnol up

fill/cell shade
color
fill effects

pattern grouping
solid
horizontal stripe
thin horizontal stripe
75% grey
vertical stripe
thin vertical stripe
50% gray
reverse diagnol stripe
thin reverse diagnol stripe
25% gray
diagnol stripe
thin diagnol stripe
12.5% gray
diagonal cross patch
thin horizontal cross patch
6.25% gray
thinkdiagonalcross patch
6.25%gray

The work for this is being done on NVDA-India repo.

**Comment by jcsteh** [comment]
It's now possible for a user to browse font information by pressing NVDA+f twice. See #4908.

Most of these formatting items are now reported.

@ManshulBelani, I'm going to close this. If there are still formatting items you want to implement here, please file separate issues with full details, use cases, test cases, etc. Thanks!
