### ISSUE TITLE
Mouse Tracking Glitches

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3589]
**Reported by kumajuannazhi on 2013-10-20 19:15**
When you are using the mouse in any web browser with Mouse Tracking enabled, there are times when, visually, a hyperlink is placed within a line, and then there is text after it on the same line.  When using the mouse, NVDA will read the text before the link, but then it'll stop.  It won't read the link itself either.  Also, if a link is at the very start of a line, NVDA will read that link, but it won't read the text that follows.  Plus, things get really glitchy when there are multiple links and occurrences of static text within the same line.

**Comment by leonardder** [comment]
@QChristensen, here is another mouse tracking bug. May be we should close some of these and use one issue for all these mouse tracking issues.

**Comment by Qchristensen** [comment]
This is similar to #3590 and others, and likely they are related.  There is a good chance that fixing one issue in this area will fix others.

**Comment by bhavyashah** [comment]
In case @Qchristensen's hunch is correct and fixing one of these mouse tracking issues will effectively resolve others, one of these tickets should probably be assigned a high priority. Thoughts? @feerrenrut

**Comment by Qchristensen** [comment]
Thanks Bhavya, definitely do take my comments with the knowledge that I haven't looked at the code and was just going on the basis that there are several issues which all basically fit under the broad problem of  "where reading starts and stops when moving the mouse over text".

**Comment by Brian1Gaff** [comment]
I'm assuming this has come up again since there is a message about problems 
with mouse reading in todays message on the user list. I'll not bring it 
over but noticed it.
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by feerrenrut** [comment]
Without more specifics about the problem its hard to tell how this is different from #3590 where @Qchristensen has done a fantastic job of outlining the behaviour in a bunch of different cases. I will close this issue as a duplicate of #3590
