### ISSUE TITLE
Mouse Tracking: Textual Layer Bug

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3592]
**Reported by kumajuannazhi on 2013-10-20 20:07**
When using Mouse Tracking on webpages with NVDA, if you click on a dropdown menu or a list box, moving the cursor over the different menu items does not report the menu items themselves, but instead, it reports the text that would visually be seen directly behind each option, that is, if menus could be translucent.

**Comment by ehollig** [comment]
Unfortunately, there does not appear to be an example provided from the original poster and we are unable to contact for additional information. Furthermore, the did not answer @jcsteh's question in https://github.com/nvaccess/nvda/issues/3592#issuecomment-155310791 on the browser used. Closing
