### ISSUE TITLE
New Vietnamese Voice Pitch Crash

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3593]
**Reported by kumajuannazhi on 2013-10-20 20:19**
When using the "Vietnam_Hue" voice, NVDA crashes if the pitch is lowered beyond 34%.

**Comment by ehollig** [comment]
I can not reproduce this either. I performed the same steps as in https://github.com/nvaccess/nvda/issues/3593#issuecomment-155310814 by using both the Voice Settings Dialog, as well as the Synth settings ring. CC @jcsteh

**Comment by leonardder** [comment]
We can't contact the original author any more. Closing as work's for me.
