### ISSUE TITLE
Allow NVDA to continue speaking when multimedia keys are pressed

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3595]
**Reported by garrettk18 on 2013-10-22 01:04**
I have a keyboard with media keys, and I often find I want to change tracks or adjust the volume of my music while reading a document. Right now, NVDA doesn't treat these keys specially, and stops reading whenever one of these keys is pressed.

I'd be interested to hear other peoples' opinions on this, both from a development and user perspective. I can see some cases where this behavior would be undesirable (i.e. user exploring a new system and not knowing the functionality of various controls). Personally, at work I find it useful, especially when I'm programming and just need to click over to a new track ETC.

**Comment by bhavyashah** [comment]
@jcsteh Could you please clarify exactly which keys are being referred to as multimedia keys in the context of this ticket? Play/Pause is one that comes to mind, but it would be beneficial if you could specify all multimedia keys that this ticket encompasses, since we have no means of contacting the original author of this ticket.

**Comment by jcsteh** [comment]
The reporter wasn't specific, but I assumed play/pause, next track, previous track, etc. Volume up/down was also covered, but we don't interrupt speech for those already.

I don't think it's unreasonable for play/pause, next, previous, etc. to interrupt speech, just as pressing a function key interrupts speech. In particular, the use case given above seems strange to me (skipping tracks while programming). Everyone is different, but from what I've seen, programming doesn't usually involve reading large amounts of text without any input from the user, so interrupting reading of a line (for example) to change tracks doesn't seem unreasonable.

Closing as won't fix. If a compelling use case can be given (and an argument for why these shouldn't be treated like function keys, etc.), we can reconsider.
