### ISSUE TITLE
the new sayall doesn't pause when up arrow is pressed.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3599]
**Reported by driemer.riemer@... on 2013-10-22 20:01**
When nvda is in say all mode with the new say all skim reading and the up arrow is pressed nvda reads the current line again. when it is pressed repeatedly nvda tries to keep reading the current line.
I prepose that if the up arrow key is pressed multiple times say all should be deactivated. either this or say all should jump up line by line.

**Comment by leonardder** [comment]
cc @derekriemer

**Comment by derekriemer** [comment]
closing as wontfix because I opened it, and it seems to be fixed in most situations.
