### ISSUE TITLE
When loading a URL with a target anchor, NVDA should jump to that anchor

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#360]
**Reported by mohammed on 2009-07-04 19:23**
Currently, when NVDA encounters html anchors, (typically links that jump to parts of the same loaded page), it reports them as links. Nvda should distinguish between links and anchor links. it should report them more discriptively like "same page link".

Also, NVDA doesn't seem to jump to the relevant part of the page that those anchor links refer to. take for an example any wikipedia page, which are full of such anchors: http://en.wikipedia.org/wiki/Comparison_of_screen_readers#References

tested with nvda r3040 and both IE8 and firefox 3.5.

**Comment by leonardder** [comment]
I think this is fixed everywhere it should have been, right?

**Comment by jcsteh** [comment]
Almost. As noted in https://github.com/nvaccess/nvda/issues/360#issuecomment-155280281:

> We still need MozillaBug:617544 to get this right for documents loaded before NVDA is started.

I think that's a pretty low priority use case, though. Also, the Mozilla bug was closed due to inactivity.

I'm going to close this, since this works in the majority of real world cases.

**Comment by thiago-1000** [comment]
In Google Chrome it is still jumping the external link anchor, do you have any adjustment forecast?
