### ISSUE TITLE
win 32 exception error when using outlook 2007

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3601]
**Reported by asteer on 2013-10-22 22:34**
I am helping my dad - PC  - Vista professional [know but he is used to it](I) he consistently gets a win32 exception error and Outlook [2007] crashes. I've discovered that  this  doesn't happen when I  exit NVDA. I've downloaded and installed the latest  version but still have same problem.
However, when I start outlook first and then NVDA -  it seems to be ok. Trouble is he uses NVDA to read his email and I had it set up to start at boot.

**Comment by ehollig** [comment]
Closing, as we are unable to contact the original poster and do not have enough information to debug the issue.
