### ISSUE TITLE
NVDA is too slow in Windows 8.1

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3606]
**Reported by shadyar on 2013-10-26 16:34**
Hello
I have downloaded and installed Windows 8.1 64-bit enterprise and installed NVDA last snapshot MASTER 9667,AAD88A0on it, but when I navigate between the icons of a window, NVDA is too slow, NVDA has a PERSECUTOR delay before the reflex  to the keyboard commands and reading the name of the next icon.
this problem there is not in to applications eg. notpad or word.

**Comment by dkager** [comment]
Do we still have the log files referenced in https://github.com/nvaccess/nvda/issues/3606#issuecomment-155311330 and do they offer any additional info?
Tempted to close this because of scope creep.

**Comment by feerrenrut** [comment]
Both attachments added to https://github.com/nvaccess/nvda/issues/3606#issuecomment-155311319

**Comment by ehollig** [comment]
After briefly looking at the attachments, I am leaning toward invalid as @dkager suggested in https://github.com/nvaccess/nvda/issues/3606#issuecomment-320724193 as we do not have a reliable way to replicate the issue. Feel free to reopen if you do not agree.
