### ISSUE TITLE
Problem with custom (js-based) autocomplete text-fields

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3615]
**Reported by kent78 on 2013-10-31 10:02**
We have identified a problem with NVDA and google.com style autocomplete "input fields". To reproduce use NVDA version 2013.2 and Firefox (latest, I´m using version 24) and go to "www.google.com". Write for example "car" in the search field. Then there are som suggested words visible below the input field and you can arrow down to choose one and it will replace what you have written and NVDA should report the new text. But sometimes (seamingly random) it reports the text-field beeing "blank". These types of "drop-downs" works fine i for example JAWS.

**Comment by leonardder** [comment]
This is likely to have changed, and for me it is perfectly accessible. Closing as works for me.
