### ISSUE TITLE
unable to subscribe to newsgroups using Thunderbird

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3619]
**Reported by laughingthunder on 2013-11-03 03:14**
I just attempted to subscribe to newsgroups on the news.grc.com server using Thunderbird.  However the groups appear in an inaccessible tree view in Thunderbird's subscribe dialog.

Steps to reproduce:
1. Install Thunderbird and launch it as a standard user.
2. Add a new newsgroups account.  On the first screen, enter the required information and select the next button.
3. In the newsgroup server field, enter "news.grc.com" without the quotes, and select the next button.
4. Enter an account name of your choosing and select next.
5. Verify the information and select the finish button.
6. At this point, you should be returned to the Thunderbird main page.  Select the link labeled "Manage newsgroup subscriptions."
7. In the resulting dialog, select the refresh button.
8. At this point, it should be easy enough to tab around the dialog, find the list of possible newsgroups, and select which ones to subscribe to.  However this is not the case, as Mozilla has chosen to use a nonstandard tree view like control to represent the group list, and NVDA does not recognize it at all.

I have attached a log showing the developer info for the control in question.  Any information on this would be greatly appreciated, as I can't seem to find any good accessible newsgroup readers other than Thunderbird.

**Comment by leonardder** [comment]
Seems that [the Mozilla Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=934872) is still open.

**Comment by Adriani90** [comment]
I think this should be fixed in Thunderbird 62.0. @laughingthunder is this still an issue?

**Comment by Adriani90** [comment]
The Mozilla bug is solved and the tree view works as expected in Thunderbird 60.6.1 with NVDA 2019.1.1. I am closint this as works for me.
cc: @bdorer, @novalis7747 if you find some time to test and if you still see this issue, please comment on it and we can reopen the discussion.
