### ISSUE TITLE
In mozilla thunderbird, pressing control plus backspace triggers an error rather than reading the correct word

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3621]
**Reported by driemer.riemer@... on 2013-11-04 03:07**
When  ctrl+backspace is pressed in mozilla thunderbird an error is triggered sometimes randomly. It appears to be trying to calculate the length of an object of type None.

Input: kb(laptop):control+backspace
ERROR - scriptHandler.executeScript (19:51:05):
error executing script: <bound method Dynamic_EditableTextWithAutoSelectDetectionDocumentBrokenFocusedStateMozillaIAccessible.script_caret_backspaceWord of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionDocumentBrokenFocusedStateMozillaIAccessible object at 0x05B44B30>> with gesture u'ctrl+backspace'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 174, in executeScript
  File "editableText.pyc", line 144, in script_caret_backspaceWord
  File "editableText.pyc", line 134, in _backspaceScriptHelper
TypeError: object of type 'NoneType' has no len()
IO - inputCore.InputManager.executeGesture (19:51:06):
Input: kb(laptop):p

**Comment by ehollig** [comment]
@derekriemer are you still experiencing this issue? According to [MozillaBug:935375](https://bugzilla.mozilla.org/show_bug.cgi?id=935375) this problem has been resolved.

**Comment by derekriemer** [comment]
nope
