### ISSUE TITLE
OpenOffice IA2: Double reporting of dialog captions

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3631]
**Reported by jteh on 2013-11-08 01:53**
This occurs because getDialogText includes the name of the caption even though it's already included the IA2 text. This can be fixed easily by setting isNameIncluded to True for ROLE_STATICTEXT.

**Comment by leonardder** [comment]
@JCSTeh: is this still an issue? I can't reproduce this in the find and replace dialog of Libre Office, for example.

**Comment by jcsteh** [comment]
It seems this issue is fixed, but now we don't report dialog captions at all; e.g. the "Save Document?" dialog. That should probably be addressed in a separate issue to avoid confusion.

Quick note: getDialogText probably doesn't descend into option panes. It needs to for LibreOffice.
