### ISSUE TITLE
When Using NVDA with Internet explorer 11 on www.bookshare.org, a specific section of the page is identified as an edit box when it is really a heading with an access key

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3633]
**Reported by dgoldfield on 2013-11-08 20:01**
there is a heading which NVDA can access by pressing the letter E, even though this is not an edit field.  Here is how to duplicate this bug.
1.  Open Internet explorer 11.
2.  Go to www.bookshare.org.  You do not need to be a member to duplicate this issue.
3.  From the bottom of the page, press shift-E.  
4.  You will be taken to a level 1 heading with an access key identified as alt-1, but this is not an edit box.  If you press the enter key at this point, NVDA will take you out of browse mode.
   If you go to the top of the page and press the letter E repeatedly, you will also be taken to this level 1 heading, although NVDA will find the real edit boxes on this page as well.

**Comment by ehollig** [comment]
The provided example does not work anymore in IE 11. @michaelDCurran, in https://github.com/nvaccess/nvda/issues/3633#issuecomment-155312175 it sounded as if you knew what the problem was and was going to address it. Is this still the case or something that still needs to be fixed?

**Comment by michaelDCurran** [comment]
Closing as worksforme as bookshare.org no longer has the strange heading and this was the only case reported.

**Comment by Brian1Gaff** [comment]
Actually a page on the infosound web site also did something very much the 
same, but I persuaded the author to take the offending bits off, and replace 
them with normal text, which cured the issue of it going into focus mode for 
no apparent reason.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
