### ISSUE TITLE
NVDA throws exception; windows Explorer focus is thrown off when loading a Word document

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3634]
**Reported by RobertSpangler on 2013-11-09 17:28**
This issue is not 100% reproduceable but it does occur often.  When either pressing enter on a Word document or opening it through Open With in Windows Explorer, NVDA's focus in the Explorer window is thrown to the preview payne and it seems to be impossible to tab around the window.  The document is loaded in Word but does not gain foreground focus.  This is with Office 2010 and latest snap of NVDA Next.  It has been occurring for a while now.  Here is the debug log:
Input: kb(desktop):enter
IO - speech.speak (14:34:35):
Speaking [('en_US'), u'CSU'](LangChangeCommand)
IO - speech.speak (14:34:35):
Speaking [('en_US'), u'Items View  list'](LangChangeCommand)
IO - speech.speak (14:34:35):
Speaking [('en_US'), u'Daily Routine (CORRECTED).doc  3 of 3'](LangChangeCommand)
IO - braille.BrailleBuffer.update (14:34:35):
Braille regions text: [', u'Items View lst ', u'Daily Routine (CORRECTED).doc 3 of 3'](u'CSU)
IO - braille.BrailleHandler.update (14:34:35):
Braille window dots: 123 234 2345 - 1457 1 24 123 13456 - 12357 135 136 2345 24 1345 15 - 1268 147 1357 12357 12357 157 147 23457 157 1457 3457 3 145 135 14 - 146 - 135 124 - 146
IO - speech.speak (14:34:35):
Speaking [('en_US'), u'Preview Pane  tree view'](LangChangeCommand)
IO - speech.speak (14:34:35):
Speaking [('en_US'), u'pane'](LangChangeCommand)
IO - speech.speak (14:34:35):
Speaking [('en_US'), u'Message  edit  multi line'](LangChangeCommand)
DEBUGWARNING - NVDAObjects.window.winword.Dynamic_IAccessibleWordDocumentWindowNVDAObject._get_WinwordWindowObject (14:34:35):
Could not get MS Word object model
Traceback (most recent call last):
  File "NVDAObjects\window\winword.pyc", line 517, in _get_WinwordWindowObject
  File "oleacc.pyc", line 212, in AccessibleObjectFromWindow
  File "_ctypes/callproc.c", line 941, in GetResult
WindowsError: [-2147467259](Error) Unspecified error
ERROR - eventHandler.executeEvent (14:34:35):
error executing event: gainFocus on <NVDAObjects.Dynamic_IAccessibleWordDocumentWindowNVDAObject object at 0x04EE0C30> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 136, in executeEvent
  File "eventHandler.pyc", line 84, in __init__
  File "eventHandler.pyc", line 91, in next
  File "NVDAObjects__init__.pyc", line 843, in event_gainFocus
  File "NVDAObjects__init__.pyc", line 787, in reportFocus
  File "speech.pyc", line 328, in speakObject
  File "NVDAObjects__init__.pyc", line 909, in makeTextInfo
  File "NVDAObjects\window\winword.pyc", line 251, in **init**
AttributeError: 'NoneType' object has no attribute 'range'
IO - inputCore.InputManager.executeGesture (14:34:36):

**Comment by ehollig** [comment]
@RobertSpangler, are you still experiencing this issue, or can it be safely closed?

**Comment by robertspangler** [comment]
It can be closed.

**Comment by derekriemer** [comment]
Cool, thanks for letting us know.
