### ISSUE TITLE
request for add-ons and web folder to be included into 'fa' folder

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3639]
**Reported by aslani.ali on 2013-11-11 18:41**
1- the folder 'web' and some add-ons have not been included in the folder which i synched by SVN server for translation into farsi. please add it into /fa/ folder as well as other languages.
2- i recieve all notification of mailinglist but maybe my country is blocked by that mailinglist because i cannot send any e-mails into the list to request it.
my e-mail address which is registered: aslani.ali@gmail.com
the username on assembla: aliaslani

**Comment by ehollig** [comment]
@josephsl, do you know the status on this issue and whether it still applies?

**Comment by ehollig** [comment]
Just a friendly ping to @josephsl to answer the question in https://github.com/nvaccess/nvda/issues/3639#issuecomment-323904588

**Comment by josephsl** [comment]
Hi,

Ah yes, closing, as Farsi has been added as a wiki language and add-ons are being translated. Thanks.
