### ISSUE TITLE
Support for Microsoft Access

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3643]
**Reported by nvdakor on 2013-11-12 18:08**
Hi,
A number of NVDA users have requested support for Microsoft Access, the database management tool in Microsoft Office. For now, I and others are developing support for Access as an add-on app module, but I highly anticipate that this app module would be merged into NvDA core at some point.
Specifically, the feature sets that were requested are:
- In data tables, ability for NvDA to announce column headers automatically as one moves around the table grid whether or not the user is editing the cell.
- Fix for a long standing bug where one cannot hear the contents of a data cell when editing (after pressing F2) such as deletion or navigation using arrow keys.
  And other features from community input. Thanks.

**Comment by ehollig** [comment]
Closing this to consolidate discussion to #2281. CC @josephsl

**Comment by oissac** [comment]
Hi, I'm working on an Access App that is going to be used by blind users together with NVDA. I've encountered this exact problem, but I don't know how/where to install this add on you developped. What are the steps on implementing this?

Thanks a lot in advance, I've been looking like crazy for a solution and this is the closest I've found
