### ISSUE TITLE
Add the Edited profile in preferences dialogs title bar

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3644]
**Reported by PZajda on 2013-11-12 18:49**
Hi,

To be absolutely certain that no confusion can occur when modifying NVDA settings, it might be good to have the name of the profile being edited in the title bar of dialogs preferences, if the default profile is not currently used.

**Comment by leonardder** [comment]
I think the dialog is clear as it is. As soon as you focus the dialog, the currently active profile is shown. Showing the profile in the title bar sounds a bit too far-fetched to me, but this might be only my opinion.

**Comment by jcsteh** [comment]
I believe the reporter meant showing the name of the active profile in the title of settings dialogs; e.g. General Settings (my profile).

**Comment by pzajda** [comment]
Exactly @jcsteh
In my opinion, it could help to avoid some confusion on what profile is being modified when changing NVDA settings.

**Comment by leonardder** [comment]
I'm sorry for the misunderstanding.

There is one thing we should consider here, since #577 might come along in the near term. This would make the title quite long, e.g. NVDA Settings: Speech [my profile].

If this isn't a problem, it might be a good idea to add this to the implementation of #577.

**Comment by jcsteh** [comment]
I think this makes sense as part of #577. As you say, it does make the
title long, but it's probably not significantly longer than, say, a web
browser with Gmail open. We could possibly consider dropping the "Settings"
or "NVDA" if we feel the context is clear enough without it; e.g. "NVDA:
Voice [my profile]" or "Settings: Voice [my profile]". I think I prefer the
former.
