### ISSUE TITLE
merge configuration related menu items under configuration submenu

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3647]
**Reported by surveyor on 2013-11-14 14:44**
There are currently 4 configuration related menu items under NVDA menu, Configuration Profiles,
Revert to saved configuration,
Reset configuration to factory defaults,
Save configuration.
It maybe more convenient to move these items under  Configuration submenu.

**Comment by ehollig** [comment]
@jcsteh, do you still think something like this is counter-productive as stated in https://github.com/nvaccess/nvda/issues/5976#issuecomment-220572872? Other comments in #5976 think this may be a useful feature.

**Comment by jcsteh** [comment]
1. Change for change's sake is rarely a good idea.
2. I don't think 11 items in the main menu is unreasonable, especially as these are pretty basic functions.
3. IMO, adding an extra menu for these just makes them harder to find/get to.
4. "Configuration" might get confused with "Preferences". If we were going to do this, I'd suggest "Configuration management".
5. I'll defer to @QChristensen, @MichaelDCurran and @feerrenrut on this one; I'm not going to fight it if the consensus is to change it.

**Comment by michaelDCurran** [comment]
I agree with Jamie's points. Closing as wontfix
