### ISSUE TITLE
NVDA commands stop working after a screen saver

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3651]
**Reported by Agent Golder on 2013-11-18 18:03**
If for example we have set the screen to be tirned off after 1 minute and we don't do anything for more than a minute or so, when we press any key that changes the focus like tab is read but all the NVDA shortcuts like control, NVDA key+t etc are passed directly to the currently running application like it would happen if NVDA was not running. Also, the events are read the one after the other! For example if we are on the desktop and press down arrow twice, it would say "my documents" and then after it finishes the first the next one "My computer". When this happens currently we need to press `control+alt+N or one of the shortcuts for NVDA to be restarted to behave again as it should.
Can this please be fixed?
Thank you.

**Comment by bhavyashah** [comment]
@jcsteh Could you please explain how an average user can ascertain whether or not a running application has a keyboard hook in response to https://github.com/nvaccess/nvda/issues/3651#issuecomment-155312751? I don't understand keyboard hooks properly myself, but it does sound like Winap with global hot keys enabled implies the presence of a keyboard hook. Anyways, the reported issue certainly sounds like a specific case of #2003. Therefore, we might want to close this ticket in as a duplicate so as to consolidate discussion there. @ehollig

**Comment by jcsteh** [comment]
Unfortunately, I don't think there's any reliable, clear-cut way to ascertain this, even for a developer. Apps that support global shortcut keys possibly use a keyboard hook, but not always; there are other ways to register global shortcuts, though usually, you can't override Windows commands with those.

**Comment by Adriani90** [comment]
@jcsteh Since this issue does not fully depend on NVDA I think it is quite hard to solve. If changes in NVDA are not going to solve it then i think we should close it. @Agent Golder is this still a big issue for you? To be honnest I didn't hear from anyone else having this issue.

**Comment by jcsteh** [comment]
I can't reproduce this myself and I haven't seen any other reports of it for a long time. Closing.
