### ISSUE TITLE
"Power saving and privacy"

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3658]
**Reported by Agent Golder on 2013-11-21 19:38**
Can you please make an option like the Mobile speak for Symbian screen reader has for turning off the backlight when running so a sited person can't see what is on the screen?
Would be usefull in many situations, one of these are laptops and netbooks, especially when used with batary.

**Comment by ehollig** [comment]
As stated by @jcsteh in https://github.com/nvaccess/nvda/issues/3658#issuecomment-155312907, you can do this in Windows 7 by pressing Windows key+p and selecting "Projector only". For newer versions of Windows, I do not believe this is possible without using some 3rd party software. This would have to be changed by Microsoft. Closing as NeedsExternalFix and cantfix

**Comment by ehollig** [comment]
Duplicate of #5856
