### ISSUE TITLE
NVDA gets stuck on application-triggered profile when moving away from said application

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3673]
**Reported by twynn92 on 2013-11-29 08:05**
I don't know how to reliably reproduce this, but there are rare cases when you switch to a triggered application profile , switching away from the application doesn't cause NVDA to switch back to the normal configuration. Instead, NVDA lists the triggered profile as "editing", but does not say that it is "triggered". There seems to be no way, apart from restarting, to switch back to the normal configuration.

A log with this bug is attached. The bug appears towards the end of the log. NVDA is in debug warning as its logging level.

**Comment by ehollig** [comment]
@jcsteh, should this be closed as you were unable to see anything obvious in the log? You also mentioned in https://github.com/nvaccess/nvda/issues/3673#issuecomment-155313166 that you would think on it.

**Comment by jcsteh** [comment]
I don't have any further thoughts on this, the log isn't any help and I haven't seen any other reports fo this. Closing as works for me. Note that #6787 provided some fixes related to profile switching, so this may have been fixed by that.
