### ISSUE TITLE
read all - chceckbox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3674]
**Reported by tutej on 2013-11-29 10:51**
Hello once again,
my configuration is:
Windows 7 64bit, IE9, NVDA 2013.2

the Code:

<table style="width: 100%;" role="presentation">
    <tbody>
    <tr>
        <td>
            <div class="gwt-CheckBox gwt-CheckBox-disabled">
                <table role="presentation">
                    <tbody>
                    <tr>
                        <td>
                            <div>
                                <input id="gwt-uid-116" disabled="" tabIndex="1002" value="on" type="checkbox">
                            </div>
                        </td>
                        <td>
                            <div>
                                <label for="gwt-uid-116">Zgłoszeniowy</label>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </td>
        <td>
            <div><span class="gwt-RadioButton gwt-RadioButton-disabled">
                <input
                        id="gwt-uid-117" disabled=""
                        tabIndex="1003" name="rodzajInformacji"
                        value="Z" CHECKED="" type="radio">
                <label
                        for="gwt-uid-117">Dotyczący miesięcznego
                    dofinansowania</label></span><span class="gwt-RadioButton gwt-RadioButton-disabled">
                <input
                        id="gwt-uid-118" disabled=""
                        tabIndex="1004" name="rodzajInformacji"
                        value="K" type="radio">
                <label
                        for="gwt-uid-118">Korygujący</label></span>
            </div>
        </td>
    </tr>
    </tbody>
</table> 

and the issue:

for given code, when i'm using the read-all command (NVDA-down-arrow)
NVDA doesn't read the information for input: id="gwt-uid-117" properly. chcekbox is marked but NVDA read it as unmarked.

Thanks for help.

**Comment by Adriani90** [comment]
@tutej is this still an issue?

**Comment by Adriani90** [comment]
Ok I have tested with NVDA 2018.4.1 and IE11. The issue is still reproducible.
@leonardder this issue in IE is also very present in SAP web apps which are working only in IE.

**Comment by Adriani90** [comment]
This was only reproducible in IE and IE is discontinued since 2023 when it was automatically removed from Windows PCs after a Windows update. Closing as abandoned.
