### ISSUE TITLE
IE8: "Report table row/column headers" could not match with the content

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3677]
**Reported by surfer0627 on 2013-12-02 04:00**
Hello developers,
Here are steps to reproduce the case:

1) Open one ticket in the NVDA website.

2) Press t navigate to table

3) Move to (r2, c2)

4) Press Up Arrow to (r2, c1)
NVDA report: Reported by: c1 Priority: 

5) Press Down Arrow two times to (r2, c3)
NVDA report: Owned by: c3 Milestone: 

6) Press Down Arrow two times to (r3, c1)
NVDA report: Reported by: c1 Component: 

Thank you.

**Comment by ehollig** [comment]
Can this, as well as #2824 be marked as a duplicate as it sounds like there are other tickets that are covering this topic. Also, NVDA does not use track anymore, which is used to reproduce the issues.

**Comment by Brian1Gaff** [comment]
Also, does anyone still use IE8, even on XP?
 Its actually now being chucked off many web sites if you try.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by leonardder** [comment]
Closing this:

1. The NVDA project no longer uses Trac
2. IE8 is obsolete, XP users should at least consider to use something more up to date.

if this issue can be reproduced for another website and a newer version of IE (preferably IE11), please raise a new issue.
