### ISSUE TITLE
Normalisation of input gesture identifiers doesn't handle upper case correctly

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3678]
**Reported by jteh on 2013-12-02 04:26**
When normalising gesture identifiers, we order any items separated by + into Python set order and convert to lower case. Currently, we convert to lower case _after_ the order in several places. This can break if two equivalent identifiers have different capitalisation before normalisation.

This needs to be fixed in inputCore.normalizeGestureIdentifier, as well as all sources that output identifiers, including keyboard, braille display drivers and braille input.

**Comment by jcsteh** [comment]
I'm addressing this in #6945.
