### ISSUE TITLE
Excel suggestion:  there should be a quick way to read all the formulas present in a large sheet.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3680]
**Reported by sumandogra on 2013-12-02 13:00**
Excel 
When an large and extensive Excel sheet is read with NVDA, there is no method to find out about the presence of   formulas quicklysuggestion to make available a keystroke that can help list all the cells with formulas, so that one can have a quick glance at final values present on a sheet.

note:  this is at first basically for tracking a experimental feature.

**Comment by ehollig** [comment]
[**@nvaccessAuto**](https://github.com/nvaccessAuto) commented on [Jun 4, 2014, 10:11 PM MDT](https://github.com/nvaccess/nvda/issues/3680#issuecomment-155313290 "2014-06-05T04:11:07Z - Replied by Github Reply Comments"):
> Comment 13 by @michaelDCurran on 2014-06-05 04:11
> Official branch t3680 provides a Cell list dialog, basedon code from the patch on this ticket. It can show cells with formulas or comments, and can show them grouped by region, or just flat.
> Are there any other specific features needed?

As we are now able to access formulas using NVDA+F7, is there anything else that needs to be done with this issue?

**Comment by bhavyashah** [comment]
This is a gentle request for @michaelDCurran to kindly consider responding to @ehollig's https://github.com/nvaccess/nvda/issues/3680#issuecomment-325143170.

**Comment by Adriani90** [comment]
Comments and formulas can easily be displayed in a tree view when pressing nvda+f7. I vote for closing.

**Comment by ehollig** [comment]
Closing because of reasons pointed out above.
