### ISSUE TITLE
Excel Suggestion:  there should be a quick way to find out about the comments on a sheet

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3681]
**Reported by sumandogra on 2013-12-02 13:02**
Excel
If one is reading an Excel sheet, there is no way one can find out about the cells that have comments on sheet.  One has to read each cell to find out about the presence of comments for reader of the Excel sheet.  Suggestion is to add a keystroke to list all the cells with comments in so that NVDA user can select  the desired cell.

Note:  this is at first basically for tracking a experimentalfeature.

**Comment by ehollig** [comment]
Duplicate of #3680
