### ISSUE TITLE
Excel suggestion:  there should be a quick way of navigating all the contents on a sheet that are visible on the screen.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3682]
**Reported by sumandogra on 2013-12-02 13:24**
Suggestion:  For quick navigation it will be useful to have a way to read all the contents visible on screen on a sheet at a time.
A user should be able    to select a desired value on a sheet and go directly on it through this quick navigation mode.

Note:  this is basically for tracking an experimental feature.

**Comment by ehollig** [comment]
Duplicate of #3680
