### ISSUE TITLE
Incorrect table reading in Microsoft Word 2007

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3685]
**Reported by Sukil on 2013-12-02 20:24**
In Word 2007, when reaching the last line of a multiline row table with the arrow keys, NVDA reads the entire row. See attachment for an example.

**Comment by ehollig** [comment]
Should this be closed as #3421 was resolved in 2014.3?

**Comment by ehollig** [comment]
Closing as duplicate of #3421. Please reopen if I am of error.
