### ISSUE TITLE
NVDA doesn't seem to provide a way to correct spelling errors in Mozilla Firefox using the keyboard.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3686]
**Reported by laughingthunder on 2013-12-03 02:30**
When I fill a form in Firefox, NVDA reports spelling errors when they occur.  However, when I attempt to correct them, I can't seem to find a way to get to the corrections list.  I start by navigating to the misspelled word.  I then select it and press the applications key on the keyboard to bring up the context menu, which contains no suggestions.  However, when I use my remaining vision to move the mouse over the word, the suggestions actually do appear in the context menu when the right mouse button is pressed.  I use the applications key to correct spelling errors in Microsoft Word, and I feel it should work this way in Firefox as well.  I apologize in advance if this is not the right place to mention this issue, since it certainly seems to be a bug.  The only problem is that I'm not sure if it's an NVDA bug or a Mozilla bug, and I don't know how to file bugs with Mozilla.

**Comment by jcsteh** [comment]
This seems to work as expected now; i.e. the suggestions appear in the context menu when you use the arrow keys to move to a misspelled word.
