### ISSUE TITLE
Showing the progress bar on the Braille Display

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3692]
**Reported by winman3000 on 2013-12-05 12:54**
Many people in europe using only braille. If you turn off speech, you are not able to hear the progress bars, except you have enable the beep tones. It would be nice to see the progress bar on the Braille Display too. You can also add a function to turn on or off the show progress Bar on the Braille Display.

**Comment by ehollig** [comment]
Duplicate of #3258 and fixed in 2017.3 from #6862
