### ISSUE TITLE
NVDA randomly speaks spaces instead of chars while arrowing through MS Excel 2003 cells

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3697]
**Reported by bdorer on 2013-12-08 12:56**
Example: I have the form:
=MONTH(TODAY())

While Arrowing NVDA randomly says space instead of a char.

**Comment by leonardder** [comment]
CC @BDorer

Excel 2003 is getting very old and obsolete. Since this issue is not disruptive in a major way, closing as won't fix.
