### ISSUE TITLE
Some BUGs and advises of document reading.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3704]
**Reported by vgjh2005 on 2013-12-09 12:19**
Hello developers:
There some BUGs of NVDA.
If I move the left or arror key to navagation the document of simplified Chinese, the character cannot be read correctly.
If I make a input, the source character will be read before the short description even I unselect the Checkbox Report changes to the reading string.
There is a space between the description and source character,however, could remove it.
I can define which object will be read in document formatting dialog. I think the content is always useful for us than the control type. I hope NVDA can offer some variables to let the translator to define how to read.
If the symbol is ignored, add some comma for it.
Thanks at last and say sorry for my bad English.

**Comment by leonardder** [comment]
@vgjh2005: Can you still reproduce this?

**Comment by vgjh2005** [comment]
Hi:
This issue is for more than one topic. So I think it is not useful.
Sorry!

**Comment by derekriemer** [comment]
original user says invalid basically.
