### ISSUE TITLE
request for fiture or addon which will allow easy switching bitween 2 or more braille input tables

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3718]
**Reported by pavel.kaplan on 2013-12-13 22:22**
i'm using the braille keyboard of my vario connect 40 to perform braille input.
 i use braille input to type in english, hebrew and russian languages.
 as a result i have to go very often to braille settings and switch bitween at list 3 diffferent braille input tables.
 this is very uncomfotable. so i would like to have a fiture or an addon which will allow to select up to 3 or 4 different input tables and switch bitween them by pressing a hot key that i would be able to assigne to the combination of the D keys of my braille display.

**Comment by peyyman** [comment]
I don't know why this feature is not available by default. Switching between languages (between input tables if you are using braille keyboard) is a repetitious task, so having a shortcut for this task is really needed.

**Comment by leonardder** [comment]
Closing this one in favour of newer duplicate #7515, which is broader in scope (it also covers output tables).
