### ISSUE TITLE
logviewer not working properly

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3722]
**Reported by halim on 2013-12-16 09:05**
In some cases the logviewer can't be read with cursor keys.
I can reprroduce that problem when trying to rename  a desktop shortcut.
- select a shortcut from desktop and press f2 and then nvda+f1
- result logviewer pops up but can't read. Moving the mouse in logviewer seems working correctly.

**Comment by leonardder** [comment]
I can't reproduce this with the provided str, but I recall cases where I alt+tab back into the log viewer and a ding sound is played.

**Comment by jcsteh** [comment]
Closing as worksforme for now, since I can't reproeduce either. If someone can reproduce, please provide details.
