### ISSUE TITLE
Using the Focus 40 Blue Braille display in the portable version of NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3723]
**Reported by andersbp on 2013-12-16 12:16**
1. It is possible to using the Focus 40 Blue Braille display in the portable version of NVDA?
1. Can I select to install the driver only on the USB-drive, so I can use an portable version of NVDA there support my Focus 40 Blue?
2. If the answer to the questions above is "no", it is so possible for you to add the drivers in the upcoming release of NVDA?

Very thanks.

Regards,
Anders

**Comment by bhavyashah** [comment]
@jcsteh's https://github.com/nvaccess/nvda/issues/3723#issuecomment-155314300 sounds justification enough. Since we are willing to accept a patch (which seems to me unlikely to come), we probably should mark this as a P4 and label it as a feature. @ehollig

**Comment by Adriani90** [comment]
cc: @leonardder, @dkager, @bramd

**Comment by Adriani90** [comment]
I guess this is now fixed since the native driver for friedom scientific braille displays has been added to NVDA's core. Can this be closed?
cc: @leonardder, @feerrenrut, @bramd

**Comment by bramd** [comment]
Yes, it can be used with Bluetooth. Since USB is not going to happen as long as a driver is not provided in Windows or through Windows update by default, which is out of our control, I would like to close this.
