### ISSUE TITLE
Request: Automatic synthesizer switching base on unicode charachters

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3729]
**Reported by taghavi on 2013-12-20 20:29**
Dear,
I'm an Persian user and my language alphabets are Arabic, So it can be identified very simple from English alphabets. 
This routine implemented in Vocalizer driver for many languages base on: 
https://bitbucket.org/spirit/guess_language/ 
Because Vocalizer is commercial and also it don't involve some languages such as Persian, I need implement of this routine in NVDA!
I hope also implement of synthesizer switching in NVDA!
So I will be able to set a second synthesizer such as internal eSpeak of NVDA or a SAPI 5 voice for Persian if NVDA detect Persian language or Arabic Unicode alphabets.

Thanks in advance

Best Regards
Mahmood Taghavi

**Comment by mohdshara** [comment]
I think this should be closed as a duplicate of #2990?
