### ISSUE TITLE
NVDA does not seem to handle the "Send iTunes Gifts" form correctly.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3733]
**Reported by laughingthunder on 2013-12-25 16:48**
In iTunes, there is a form that can be filled out to send gifts via e-mail.  However, NVDA does not correctly announce the labels for the text fields.  Also, there is a multi-line text field to enter a message for the recipient, but NVDA incorrectly identifies it as a single-line one.  It is also not possible to review entered text using the arrow keys on the keyboard in any text field on this form.  Is this an issue with iTunes?

**Comment by bhavyashah** [comment]
@laughingthunder With the latest versions of both NVDA and iTunes, could you please perform the tests requested by @jcsteh in https://github.com/nvaccess/nvda/issues/3733#issuecomment-155314574 and revert with their results?

**Comment by Adriani90** [comment]
@laughingthunder can you still reproduce this issue?

**Comment by Adriani90** [comment]
I will close this issue because we do not have an answer from the author since many years. iTunes has been updated and redesigned several times. If anyone still has problem in iTunes, please open new issues for individual problems. Thanks!
