### ISSUE TITLE
Excel: if a web address is present within a sentence, it is not identified as a link by NVDA.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3737]
**Reported by sumandogra on 2013-12-27 10:17**
Excel 2010
If a web page address is written in a sentence then NVDA does not identify it as a link.
Steps to reproduce:
1.   Write a sentence with a web address in the middle of the sentence in an excel cell.  For example, connect to www.google.com for reference.
2.  Press ENTER to go to the next cell.
3.  Again go back to the cell with the web  address. Note that web address is not identified as a link.  Instead if one just has a web address with no text before and after it, it is identified as a link.

**Comment by leonardder** [comment]
CC @sumandogra

I belief this is not a bug in NVDA

When I open excel 2016 en enter a string containing a link, Excel simply doesn't treat it as a link. Instead, you can press application key and insert a link on a cell. A cell can only contain one link.

Closing as invalid. If you belief I am in error, please give a shout.
