### ISSUE TITLE
Excel: if an email address present in a sentence in an excel cell, NvDA announces link at the end of the sentence.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3738]
**Reported by sumandogra on 2013-12-27 10:40**
If an email id is written in a sentence, NVDA identifies the link at the end of the sentence and not on the email address.

Steps to reproduce:
1.  In an Excel cell, write a sentence with an email id in it, for example, write: sent by Jackson@hotmail.com on Monday.
2.  Press ENTER and go to the next cell.
3.  Again go back to the cell with the email id.  Note:  NVDA reads the complete cell content and then announces “link” at the end of the sentence.  This is not correct behavior.
4.

**Comment by leonardder** [comment]
Cells can only contain one link and the whole cell is treated as link, so this is normal behavior. Closing as invalid.

See also #3737, which is related and also has @sumandogra as author.
