### ISSUE TITLE
Dash symbols should be passed through to the synthesizer if not spoken as words

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3740]
**Reported by k_kolev1985 on 2013-12-29 11:01**
At least some (if not most) speech synthesizers are designed to make pauses when they detect dash symbols (as symbols, and not as text). Because in the natural speech, one of the reasons to insert a dash symbol is exactly for that - to make a pause in the reader's speech. At present however, NVDA is set to replace the non-spoken at the current punctuation level symbols with a space. And in most cases, this is OK. In most, but not in all. And the dash symbol is one such case. I think that NVDA should be set (through the default english symbols dictionary) to not replace the dashes (all kinds of them) with a space, but to pass them through directly as they are to the synthesizer. I think it can relatively easy be done (I think it is done for the colon symbol and some others), but I don't know how to do it for our bulgarian symbols dictionary for NVDA and I think that it should be done globally for all dictionaries, via the default english symbols dictionary. And as I wrote above, it should be for all types of dashes available in the symbols dictionary, and not only for the normal one (-).

**Comment by zahyur** [comment]
Hi,
Is this fixed? I think it is. Or it isn't? CC @k-kolev1985

**Comment by k-kolev1985** [comment]
Yes, it is fixed.

**Comment by jcsteh** [comment]
The "–" (n-dash) is passed through, but other dashes aren't at this stage due to my concern above.

**Comment by k-kolev1985** [comment]
Yes, but now the user can specify this on his own if he wants to. And that is what I've done for myself.

**Comment by jcsteh** [comment]
Okay. Closing, since reporter is satisfied. :)
