### ISSUE TITLE
ARIA Grid: aria-selected to convey selectable rows and cells conflicts with 'selected' feedback in Applications Mode

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3744]
**Reported by bgaraventa on 2014-01-03 00:31**
When an ARIA Grid is constructed, the use of aria-selected on the elements with role=row or role=gridcell should convey that the row or cell is selected.
Reference: http://www.w3.org/TR/wai-aria/states_and_properties#aria-selected

This does work correctly in Browse Mode using the Virtual Buffer, but not when using Applications Mode.

When Applications Mode is activated, NVDA announces 'selected' for every cell that receives focus, regardless which cell or row includes aria-selected="true", making it very difficult for an NVDA user to tell the difference when the feedback is the same for both.

Live demo:
http://whatsock.com/test/demo/Coding%20Arena/ARIA%20Data%20Grids/ARIA%20Data%20Grid%20(Dynamic)/demo.htm

Steps to reproduce:
1. Navigate to the test URL.
2. Activate the Selectable radio button.
3. Check the 'Allow multiSelect' checkbox.
4. Check the ' Preserve row selection across pages' checkbox.
5. Check the ' Use aria-selected instead of offscreen text' checkbox.
6. Check the 'Use double click' checkbox.
7. Navigate into the Grid by pressing Tab, and press Insert+Space to force NVDA into Applications Mode.
8. Use the Up/Down arrow keys to navigate between rows, and press the Spacebar to toggle selection for the desired row.
9. Confirm that 'selected' is announced for every cell that receives focus regardless of selection via aria-selected="true".

**Comment by leonardder** [comment]
I'm able to reproduce this.

**Comment by Adriani90** [comment]
@bgaraventa the link seems not to be uptodate anymore. It says "404 document could not be found". Is this still reproducible?

**Comment by Adriani90** [comment]
cc: @leonardder the initial author is not available anymore. Can you still reproduce it?

**Comment by carmacleod** [comment]
@Adriani90 The [example grid link](http://whatsock.com/test/demo/Coding%20Arena/ARIA%20Data%20Grids/ARIA%20Data%20Grid%20(Dynamic)/demo.htm) that @accdc (bgaraventa) gave is working now, so the 404 must have been transient. I followed the steps quickly on Chrome (checked "selectable" and it's checkboxes), and I couldn't reproduce the problem. Perhaps it has been fixed, or perhaps it was a problem in some other browser. Just saying that you can try it now.  :)

**Comment by Adriani90** [comment]
With NVDA 2019.1.1 in Firefox 66.0.3 and Chrome 74 I am not able to reproduce this issue. When selecting a row with space bar, NVDA reports the cell content and after that "selected" for that specific row. Other rows above or below the selected row are reported as unselected.

In IE11 NVDA even reports "selected" twice. One time before cell content and then after cell content.

I am closing this issue as works for me.
Thank you very much for reporting back and reposting the link.
