### ISSUE TITLE
Button: Title attribute is not properly conveyed as an explicit label when no innerText is present

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3745]
**Reported by bgaraventa on 2014-01-03 00:43**
When a Button element has no inner text within the opening and closing boundaries, it should be possible to set the Title attribute on the Button to set an explicit label in the same manner as a standard form field.

E.G

`<button class="paginate" title="First Page">`
`<span aria-hidden="true">&#8656;</span>`
`</button>`

When viewed in Firefox, the Button is simply announced as "button" when arrowing down the page in the Virtual Buffer, which is non-intuitive.

Steps to reproduce:
1. Run the above code in an HTML file.
2. Open the page and press Down to arrow down the page using Browse Mode.

**Comment by ehollig** [comment]
This is still the case with Firefox 54. CC @jcsteh

**Comment by jcsteh** [comment]
This should be covered by [Mozilla bug 1123248](https://bugzilla.mozilla.org/show_bug.cgi?id=1123248).

**Comment by Adriani90** [comment]
@jcsteh testing on Firefox 64.0, this issue is fixed. Also Mozilla bug 1123248 seems to be solved.

**Comment by jcsteh** [comment]
Correct; this is fixed.
