### ISSUE TITLE
Superscripts are not read when the higher powers are inserted using the keystroke CTRL+SHIFT+EQUALS.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3749]
**Reported by sumandogra on 2014-01-07 11:59**
MSWord 2010
Superscripts are not read when the higher powers are inserted using the keystroke CTRL+SHIFT+EQUALS.
When superscripts are inserted using the symbols dialog in a word document, NVDA reads the superscripts but when the keystroke is used no indication about the superscripts is given.
Please see the attachment for clear understanding.

Steps to reproduce:
1.   Open a word document.
2.  Write a variable say x.
3.  Write a higher level of power, such as 4, 5 etc with CTRL+SHIFT+EQUALS.
4.  Now read the text with usual reading commands, such as line reading command, UP/DOWN ARROW.
5.  The superscripted text is read as x 4 and no indication of superscripted text is given.

**Comment by bhavyashah** [comment]
The reporting of font attributes must be enabled for NVDA to announce presence of subscripted and superscripted text in Word. Unless @sumandogra has something to add, I suggest closing. @ehollig

**Comment by ehollig** [comment]
Closing because the reporting of font attributes must be checked in the document formatting dialog for NVDA to announce presence of subscripted and superscripted text in Word.
