### ISSUE TITLE
Subscripts are not read when inserted with CTRL+EQUALS. The subscrited text is read as if the subscript is the text following the previous one.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3750]
**Reported by sumandogra on 2014-01-07 12:06**
MSWord 2010Subscripts are not read when inserted with CTRL+EQUALS. The subscrited text is read as if the subscript is the text following the previous one.
Please see the attachment.

Steps to reproduce:
1.  Open a blank MSWord  document.
2.  Write a character such as O.
3.  Press CTRL+EQUALS and then write some number such as 2.
4.  Now read the text with usual reading commands such as line reading commands, UP/DOWN ARROW.
5.  No subscript text is read.

**Comment by bhavyashah** [comment]
The reporting of font attributes must be enabled for NVDA to announce presence of subscripted and superscripted text in Word. Unless @sumandogra has something to add, I suggest closing. @ehollig

**Comment by ehollig** [comment]
Closing because the reporting of font attributes must be checked in the document formatting dialog for NVDA to announce presence of subscripted and superscripted text in Word.
