### ISSUE TITLE
Announcing whether an item is a container and the number of contained elements

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3764]
**Reported by zahari_bgr on 2014-01-09 16:18**
When the user focuses on a container element, or he uses the object navigation, and lands on a container element, at the end of the message with information for that element there should be an announcement, indicating that this is a container element and with how many items.
Currently, this is done for some elements (like lists), but I think it should cover all types of container elements. There could be default message, different messages for some elements and different message when the number of items is unknown.
The reason behind that is, that somethimes it is not clear that the element contains other elements, a specialy for beginners, but also with some programs, a specialy with custom elements.
However, reporting of this information should be configurable.

**Comment by bhavyashah** [comment]
We will probably need extensive discussion before we can finalize on the UX of this feature request, but this does sound worthwhile, at least to me. Also, I am probably also unfamiliar with the more technical implications of this added verbosity, but on the surface for now, this sounds fascinating and potentially useful. I would like to kindly request thoughts and inputs from others.

**Comment by Adriani90** [comment]
@zahari_bgr I do not exactly understand which use case you want to achieve. Reporting this on every container would produce a lot of verbosity which is not necessary everytime. Are there any other examples which clarify the use case of this feature?

**Comment by Adriani90** [comment]
The author is not available anymore and we do not have updates on this discussion since many years. Please comment on it if you have a use case in mind where this could be helpful. I am closing thi one as abandoned but we can reopen it if the discussion on this starts again.
cc: @lukaszgo1, @leonardder, @k-kolev1985, @Robert-J-H

**Comment by Robert-J-H** [comment]
Closing is fine by me. Skype is a special case and should be treated
as such (if the problem still exists).
We should first tackle the general position info problems I've
mentioned elsewhere (menus, tabs, checklists and running programs).
