### ISSUE TITLE
The foundation of the link that still doesnt work with NVDA.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3765]
**Reported by Slava on 2014-01-10 12:36**
Hello there!

I came into troubless during the process of my post-gradual studies and I was recomended to report it here. I am pleased with the way NVDA improves almost day by day, especially when it comes to object navigation and accesibility of web browsing. However, as part of the lingvistic section of our studies, we were asked to sumarize something from this website:
    http://www.rastko.rs/filologija/stil/index.html 

In this point I found out the website is almost inaccesible with NVDA (home ppage in particular, after getting further it probably works properly) while with Jaws accesibility is much better, but even here I find it quite confusing what it actually depends on, as the website is not always viewed properly. However, my technical skills are pretty poor, so I dont feel capable for more detail analysis, just I came in touch with this and I find it kind of crucial for certain group of users. 

So thanks for reading and also for the job you have been doing for us for so many years.
Slavomira Matlova
P.s. I am still using windows xp, but I tried the same thing with windows7, seemed to be the same.

**Comment by bhavyashah** [comment]
Since the original author of this ticket is now out-of-reach, unfortunately did not respond to @jcsteh's https://github.com/nvaccess/nvda/issues/3765#issuecomment-155315412, and with the demise of Flash (which @brian1gaff and @derekriemer believe the provided test case uses), I suggest closing. @ehollig

**Comment by Brian1Gaff** [comment]
If this was indeed inaccessible flash, then those people with such sites 
will probably have to redesign them in any case as I notice that Firefox now 
tends to ward advising any flash add on is not used I notice.
 This is going to make such sites very hard to use!
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
