### ISSUE TITLE
Flash and other embedded objects contents can't be read on win xp service pack 3.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3766]
**Reported by domasofan on 2014-01-10 16:51**
Hi all,

I found a interesting issue though i thought i got it working a long
while ago.

I have 2 computers. One runs Windows XP Pro with Service Pack 3 and the other runs Windows 7
Pro.

Both run NVDA Next 10161, Firefox 26.0 and Flash 11.9.900.170.

The interesting thing is now that on Win 7 i get a buffer when i hit
enter on the flash object for example the youtube player.

On win xp i get no buffer. What i get there is t he mode when you are in
a buffer and you hit nvda+space. so you actually get out of browse mode.

Is this because UI Automation is missing on win xp?

Though i thought i saw it working a longer time ago.

It should be reproduceable pretty easily.
1. open up for example youtube and look for a video
2. play the video and go to the flash object with the o key.
3. hit enter
4. on win 7 you get to read also the objects content to get for example the time how long its running and how long it has to go.
   On Win XP you don't get anything of those. though you can jump to the buttons and activate them, modify the slider and use the up/down keys to modify the volume.

would be very nice if someone could look into that and also fix it.

Greetings,
simon

**Comment by ehollig** [comment]
XP issues are no longer being addressed. Also, keep in mind that flash will be discontinued in 2020. Closing

**Comment by Brian1Gaff** [comment]
At present most of the issues concerning flash seem to be bad implimentation 
in the first place.

However I understood that only really serious crashing bugs would be fixed 
in xp, not that no issues are being  addressed at all.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
