### ISSUE TITLE
LibreOffice/Openoffice Calc does not read the presence of formula in cell

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3768]
**Reported by bvivi on 2014-01-10 22:10**
Openoffice Calc, the development version, not the read, with support IA2, not law if there is a formula in the cell or less

Sorry for my poor english
**Blocking #2083**

**Comment by Adriani90** [comment]
@bvivi can you still reproduce it with NVDA 2018.4 RC2 and las version of open office?
cc: @Qchristensen, @michaelDCurran

**Comment by Adriani90** [comment]
hm it seems the initial author is not on Github anymore.

**Comment by Qchristensen** [comment]
This is working for me with the current NVDA snapshot (alpha-16583,a33f71cb) in both Open Office 4.1.6 and LibreOffice 6.1.3.2.

Closing.  Good work :)
