### ISSUE TITLE
nvda won't read back to me text I type in word or outlook email

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3778]
**Reported by iriti on 2014-01-14 20:50**
A problem has been occuring recently only. I can read existing word files or emails in outlook using NVDA with no problem at all.

If I type new text in a new email or a new word file and ask NVDA to read it back to me, it says 'blank'.

**Comment by ehollig** [comment]
Closing as we are not able to contact the original poster, and they did not answer @Brian1Gaff's questions in https://github.com/nvaccess/nvda/issues/3778#issuecomment-155315775
I do not believe the log provides anything useful, but the log does appear to have a lot of errors. CC @jcsteh
