### ISSUE TITLE
Inconsistencies between "mouse tracking" and object navigation on a touch screen

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3780]
**Reported by k_kolev1985 on 2014-01-15 11:26**
Since I've started using NVDA on a portable computer with a touch screen running windows 8.1, I've noticed that there are some Inconsistencies between "mouse tracking" and the object navigation on a touch screen, related to the correct detection and recognition of objects on the screen. In some cases, the "mouse tracking" fails to detect and report an object on the screen, while the object navigation ("touch exploration") reports it correctly. In some other cases however, the "mouse tracking" correctly reports an object, while the "touch exploration" fails to do so. Shouldn't the 2 functionalities work the same?

There are a lot of examples for such inconsistencies. Some of them are in the modern Windows 8.1 interface and apps, and some others - in the standard Windows interface. Most of those are related to static text objects. If you need concrete examples, I can give you some.

**Comment by bhavyashah** [comment]
@k_kolev1985 Could you please clarify if you believe these inconsistencies to be a result of problems in mouse tracking or caused by issues in NVDA's touch screen support?

**Comment by k-kolev1985** [comment]
To be honest, I haven't compared mouse tracking and touch support recently on my portable computer which has a touch screen. The main reason for that is that I don't have the necessary free time to do it. Now it is running Windows 10 anyway and the examples above are for Windows 8.1, which makes this ticket somewhat out of date, I think. Maybe we should close it if nobody else can provide current feedback while testing under Windows 8.1 and if needs be, open new tickets with touch support issues related to Windows 10. What do you think?

**Comment by Adriani90** [comment]
If this issue does not occur on Windows 10, I think we can close it because most touch screen devices will run on Windows 10 or are already running on it.
cc: @josephsl, @leonardder

**Comment by josephsl** [comment]
Hi,

2024 update: while touch tracking has improved, there are places in Windows 11 now where both touch and mouse tracking fails (especially for aps defining XAML Islands). But for all intents and purposes, I think it would be safe to close this issue, with new issues created to deal with specific situations in the future.

Thanks.
