### ISSUE TITLE
Make Total Commander 64 announce the left and right panes

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3791]
**Reported by MarcoZehe on 2014-01-19 08:40**
The 64-bit version of Total Commander has a changed window structure, so simply applying the AppModule for the 32 bit version is not sufficient. For one, the window class to check for to load the custom class has changed, and second the logic to determine the left and right panes needed to be swapped. I decided to create a full separate app module, based on the 32 bit version's, and keep the logic separated for these two versions so other inconsistencies can be dealt with without ugly 32/64 bit version check hacks in that one script file. Pull request to follow.
**Blocking #3950**

**Comment by bhavyashah** [comment]
@MarcoZehe  Do you think this is something you might be able to look at and subsequently work on in the future, or is Total Commander no longer significantly relevant to you? It may be worth noting that the latest stable release of Total Commander for 32+64 bit Windows took place about nine months ago.

**Comment by MarcoZehe** [comment]
Afraid not. If someone wants to pick this up, feel free.

**Comment by bhavyashah** [comment]
Alright. Since I suspect that NV Access would probably be unwilling to
invest time in this too, I suggest marking this as a P4.

On 9/16/17, Marco Zehe <notifications@github.com> wrote:
> Afraid not. If someone wants to pick this up, feel free.
>
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/3791#issuecomment-329968915


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by Adriani90** [comment]
@Novalis7747 Do you still have in mind to raise the Pull Request for Total Commander? I don't recall if you did it already.

**Comment by Novalis7747** [comment]
No, I gave it up, I released a TC addon for those who are interested.

**Comment by tspivey** [comment]
Someone who uses this could just ask the author of Total Commander to use [Dynamic Annotation](https://msdn.microsoft.com/en-us/windows/desktop/cc307286.aspx) to name the lists.

**Comment by Novalis7747** [comment]
https://github.com/Novalis7747/totalcmd-enhanced/blob/master/totalcmd-0.6.1.nvda-addon
my addon, if something is not working as expected, just give me a ping…

**Comment by Adriani90** [comment]
@tspivey, @Novalis7747, @k-kolev1985 are you still having this issue with add-ons disabled in NVDA 2023.3 and Total commander 64 version 11.02 which has recently been released?

**Comment by Adriani90** [comment]
We didn't get any updates from users upon request since more than 5 years, closing as abandoned. If you are still having this issue, please comment and we can reopen.
