### ISSUE TITLE
Retry code signing

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3795]
**Reported by jteh on 2014-01-20 10:03**
The timestamp server we have to use for code signing appears to be a bit temperamental and intermittently fails. If it fails, it'd be good if we can retry signing a few times, probably with a short delay after each attempt, as otherwise, it kills the entire build. This is particularly annoying for daily snapshot builds.

**Comment by ehollig** [comment]
This appears to have been implemented in 2014.4. Closing. Please reopen if I have misunderstood.
