### ISSUE TITLE
in mozilla thunderbird, emails with long descriptions trigger an error.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3797]
**Reported by driemer.riemer@... on 2014-01-21 23:03**
I am attaching an email about this. 
Move threw it by graphic. The error triggers in next when nvda+d is pressed. I sent trace text to the email at one point. This originally was discovered with a different email which I lost. I found another email that triggers the same error though.

**Comment by michaelDCurran** [comment]
[attachments-ticket-3797.zip](https://github.com/nvaccess/nvda/files/292648/attachments-ticket-3797.zip)

**Comment by ehollig** [comment]
@derekriemer is this still the case? When I open the attachment with Outlook 2016 and navigate by graphics, and then perform NVDA+D, I get "No long description" and no error tones.

**Comment by derekriemer** [comment]
I don't know. I don't use thunderbird now.

**Comment by Adriani90** [comment]
@Novalis7747 could you please test if this is still an issue in last thunderbird?

**Comment by Adriani90** [comment]
@bdorer could you also test if this is still reproducible in las version of Thunderbird? Thank you!

**Comment by bdorer** [comment]
I don't see any graphic in this mail so I'm unable to test.

**Comment by Adriani90** [comment]
The first example has only one grafic with a long description. the second one shows more grafics but there is no grafic with long description. I am testing with NVDA 2019.1.1 in Thunderbird 60.6.1. I cannot reproduce this issue in both examples. So I am closing this as works for me. There is no error triggered.
