### ISSUE TITLE
Don't assume that python is registered with .py files

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3798]
**Reported by camlorn on 2014-01-22 03:25**
Currently, the build system assumes that .py files are registered with python itself, rather than a text editor.  For many of us who program with python, however, this is not true.  A more valid assumption may potentially be that python can be found on the path; alternatively, python 2.7 registers itself in the registry.  The latter solution may require an executable, and may consequently be unworkable.
Obviously, this is low priority: python scons.py arguments works just as well.  I'd say that providing a note that python should be on the path would be sufficient-I'd think you'd have that anyway, if you're going to do any serious python development, and it may stop more wtf reactions when people can't figure out why their scons is suddenly not working.
If no one has any thoughts on this, I'll at least attach a one-line diff that changes the batch file; I assume this would, however, be superfluous

**Comment by bhavyashah** [comment]
Will the transition of NVDA from Python 2.x to 3.x affect this ticket in any way?

**Comment by Adriani90** [comment]
As far as I understand, the change would affect Windows XP only. Right?
@camlorn, @michaelDCurran, @josephsl.

**Comment by Adriani90** [comment]
cc: @derekriemer

**Comment by derekriemer** [comment]
No, this isn't xp specific.

**Comment by leonardder** [comment]
I"m temped to close this. As we are in the process of moving to Python 3, it is safe to assume that a developer has the python launcher installed, so this issue is much less prevalent.

**Comment by josephsl** [comment]
Hi, especially given we’re using 3.7 and later. Thanks.
