### ISSUE TITLE
IDLE (Python GUI)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3812]
**Reported by Twinsen on 2014-01-24 09:17**
hi guys!I'm blind and non vision programmer .I'm lost my eyes 4 years ago.Now I'm try  learn the Python  but i can not  do this . Because the NVDA don't speak the IDLE (Python GUI)For nice training I need  built in debugger  .In debugger   I can drop breakpoints and see him and his valua.It is very important for me,please help me!.

**Comment by ehollig** [comment]
[**@nvaccessAuto**](https://github.com/nvaccessAuto) commented on [Jan 24, 2014, 10:49 AM MST](https://github.com/nvaccess/nvda/issues/3812#issuecomment-155316473 "2014-01-24T17:49:25Z - Replied by Github Reply Comments"):
> Comment 1 by @jcsteh on 2014-01-24 17:49
> IDLE is built with a very inaccessible GUI toolkit, so it's very likely it can't be made accessible at all.

Closing as cantfix. Feel free to reopen if you disagree.
