### ISSUE TITLE
NVDA next 10237: reading version numbers in commas instead of dots

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3814]
**Reported by domasofan on 2014-01-24 14:39**
Hi all,

Just discovered this while i was updating from nvda next 10190 to 10237.
anyone noticed this with nvda that it says for example one comma two comma three when i write 1.2.3.
this seems to be in english and german at least.
in next 10190 it said as it should 1 point 2 point 3.
my local espeak install which i used from the command prompt seems not to say this at all.

would be nice if this could be fixed.

greetings,
simon
**Blocked by #3842**

**Comment by dkager** [comment]
From the comments I gather this can be closed?

**Comment by jcsteh** [comment]
Yup; fixed by #3842.
