### ISSUE TITLE
NVDA reacts very sluggish when navigating in a document in the Word web app in IE

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3817]
**Reported by MarcoZehe on 2014-01-27 05:13**
To reproduce:
1. Using IE, log onto [SkyDrive](https://skydrive.live.com), login with a Microsoft account (Live ID or MSN Messenger account), and create a new Word document.
2. Type something.
3. Navigate using the arrow keys.

Result: NVDA reacts very sluggish.
1. Press Control+Shift+F6 to go to the Ribbon bars.
2. Press Tab to navigate between items.

Result: Here, the reaction is snappy.
1. Repeat steps 1 through 3 in Firefox and notice that sluggishness does not occur.

**Comment by dkager** [comment]
Closing because the Office online apps have changed quite a bit over the years. Please open a new issue if this problem still occurs.
CC @MarcoZehe
