### ISSUE TITLE
Improve KeyboardInputGesture.send

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3829]
**Reported by jteh on 2014-01-31 01:48**
1. Use SendInput so the send operation is atomic.
2. If there are any unwanted modifiers being held by the user, release them before the desired keys and press them again afterwards.
3. Use GetAsyncKeyState instead of GetKeyState.
See easeOfAccess.notify for code that could be borrowed.

**Comment by leonardder** [comment]
CC @JCSTeh

**Comment by jcsteh** [comment]
Closing as a duplicate of #4294, since that issue had an implementation and a backout. :)
