### ISSUE TITLE
Optional ducking of other audio

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3830]
**Reported by jteh on 2014-01-31 01:54**
Windows 8 allows us to request that other audio be ducked. This means we can duck the volume of other audio while NVDA is speaking. This should be optional, as it isn't always desirable. Also, I wonder whether it might be useful to have a command to duck audio even if this option is disabled for times when unexpected loud audio clobbers speech.

See the audioDuckingPrototype branch.

**Comment by nvaccessAuto** [comment]
Incubated in ca7e036c4e66390977b257e2551914854f4e5076.

**Comment by leonardder** [comment]
It seems that ducking and configuration profiles don't like each other.

To reproduce, enable ducking in a configuration profile with a trigger and disable it in the default configuration. When switching to the application with the ducking enable profile, ducking isn't enabled as expected.

**Comment by jcsteh** [comment]
@michaelDCurran: You need to switch ducking modes when config profiles are switched. Introduce a handleConfigProfileSwitch function in nvwave and call it from config.ConfigManager._handleProfileSwitch (config/__init__.py around line 510).

**Comment by k-kolev1985** [comment]
I want to report a bug with the current (available in the "next" snapshots) implementation of the audio ducking feature. It seams not to work with SAPI5. I've tried with 2 bulgarian voices and with Microsoft Zira voice, but it did not work. The option is set to "Duck when outputting speech and sounds". If the option is set to "Always duck", the feature works as expected. Is this a limitation with SAPI5 or a bug in the current implementation of the audio ducking feature? It works with other TTS engines like "Speech Player" and "RHVoice" (the older one - I don't like the newer one very much) witch are as add-ons for NVDA.

Test environment:
- Operating system: Windows 10 Pro (build 10586.11), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: next-12831,b1f00f4.
- Processor: Intel Core i5-2320 at 3.00GHz.
- RAM Memory: 4.00 GB.
- Sound Card: Realtek ALC662 at Intel Cougar Point PCH - High Definition Audio Controller.

**Comment by jcsteh** [comment]
This isn't currently possible because SAPI 5 handles its own audio 
output; it doesn't use NVDA code to do this. It should be possible for 
us to fix this with some rewriting of the SAPI 5 driver, but we don't 
plan to do this for the initial implementation of ducking.

**Comment by nvaccessAuto** [comment]
Incubated in 071a65396b68bafade119e81e48b4d779d1a564a.

**Comment by nvaccessAuto** [comment]
Incubated in fe9c9397949da33b2f7665ac172d6ca4fe92fd3b.

**Comment by nvaccessAuto** [comment]
Incubated in 9fa91c2f07da195bc08992fd94d5b8bf6695be9a.

**Comment by jcsteh** [comment]
I think it'd be really good if we can not delay the audio if there isn't audio playing (or better still, if audio is quiet). So, I've been looking into this a bit.

It seems there are two APIs you can use to get the peak levels for an audio device:

1. The [Windows Core Audio APIs](https://msdn.microsoft.com/en-gb/library/windows/desktop/dd370784%28v=vs.85%29.aspx) in Vista and later. These are COM based. Basically, you start with [IMMDeviceEnumerator](https://msdn.microsoft.com/en-gb/library/windows/desktop/dd371399%28v=vs.85%29.aspx), get an [IMMDevice](https://msdn.microsoft.com/en-gb/library/windows/desktop/dd371395%28v=vs.85%29.aspx) and call [IMMDevice::Activate](https://msdn.microsoft.com/en-gb/library/windows/desktop/dd371405%28v=vs.85%29.aspx) and request [IAudioMeterInformation](https://msdn.microsoft.com/en-gb/library/windows/desktop/dd368227%28v=vs.85%29.aspx).
 - Unfortunately, as nice as being COM based sounds, calling CoCreateInstance for IMMDeviceEnumerator results in class not registered for some reason. mmdevapi.dll doesn't seem to have a typelib, so I tried generating one from mmdeviceapi.idl. When I tried to use that with comtypes, it threw a weird assertion error.
 - [This StackOverflow thread](http://stackoverflow.com/questions/32149809/read-and-or-change-windows-8-master-volume-in-python) shows it's possible to use this API with comtypes, but the interfaces would all have to be written out.
2. The old [Audio Mixer API](https://msdn.microsoft.com/en-us/library/dd756701%28v=vs.85%29.aspx) from winmm. [This article](https://support.microsoft.com/en-us/kb/181550) provides details about how this could be used to get peak levels.
 - Unfortunately, there would be a hell of a lot of structs to write out if we wanted to do this in Python.

Of course, I guess we could write the code in C++ and avoid the Python porting bit. After all, all we want is one damned value.

**Comment by jcsteh** [comment]
However, the above should perhaps be done separately, as it looks like it's pretty complicated to implement and it is nice-to-have rather than essential. Thoughts, @MichaelDCurran?

**Comment by michaelDCurran** [comment]
Certainly sounds cool, but:

Windows ducks audio of all sound cards, not just the default. I assume 
we'll want to check if there is audio playing on any available card? Or 
should we just use NVDA's currently configured output device?

Also, depending on the speed of the delay in the peak meters, it may 
inadvertently detect NVDA's own speech. Though if we do the check at the 
lowest level (i.e.) `audioDucking._setDuckingState`, this is guaranteed 
not to be called for at least a second after any speech finishes. 
`_setDuckingState` will also need to return True or false based on 
whether it actually did change state. If asking to duck and 
`_setDuckingState` returns false, `_requestDucking` should not do a 
`time.sleep`.

On 8/12/2015 9:53 PM, James Teh wrote:
>
> I think it'd be really good if we can not delay the audio if there 
> isn't audio playing (or better still, if audio is quiet). So, I've 
> been looking into this a bit.
>
> It seems there are two APIs you can use to get the peak levels for an 
> audio device:
>
>  1. The Windows Core Audio APIs
>     <https://msdn.microsoft.com/en-gb/library/windows/desktop/dd370784%28v=vs.85%29.aspx>
>     in Vista and later. These are COM based. Basically, you start with
>     IMMDeviceEnumerator
>     <https://msdn.microsoft.com/en-gb/library/windows/desktop/dd371399%28v=vs.85%29.aspx>,
>     get an IMMDevice
>     <https://msdn.microsoft.com/en-gb/library/windows/desktop/dd371395%28v=vs.85%29.aspx>
>     and call IMMDevice::Activate
>     <https://msdn.microsoft.com/en-gb/library/windows/desktop/dd371405%28v=vs.85%29.aspx>
>     and request IAudioMeterInformation
>     <https://msdn.microsoft.com/en-gb/library/windows/desktop/dd368227%28v=vs.85%29.aspx>.
>
>       * Unfortunately, as nice as being COM based sounds, calling
>         CoCreateInstance for IMMDeviceEnumerator results in class not
>         registered for some reason. mmdevapi.dll doesn't seem to have
>         a typelib, so I tried generating one from mmdeviceapi.idl.
>         When I tried to use that with comtypes, it threw a weird
>         assertion error.
>       * This StackOverflow thread
>         <http://stackoverflow.com/questions/32149809/read-and-or-change-windows-8-master-volume-in-python>
>         shows it's possible to use this API with comtypes, but the
>         interfaces would all have to be written out.
>  2. The old Audio Mixer API
>     <https://msdn.microsoft.com/en-us/library/dd756701%28v=vs.85%29.aspx>
>     from winmm. This article
>     <https://support.microsoft.com/en-us/kb/181550> provides details
>     about how this could be used to get peak levels.
>       * Unfortunately, there would be a hell of a lot of structs to
>         write out if we wanted to do this in Python.
>
> Of course, I guess we could write the code in C++ and avoid the Python 
> porting bit. After all, all we want is one damned value.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/3830#issuecomment-162860239>.
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by michaelDCurran** [comment]
Actually, my last idea was a little too over engineered, and incorrect.

Rather than changing `_setduckingState`, `_requestDucking` simply does 
not have to do the `time.sleep` if no other audio is playing. 
`_setDuckingState` will still technically duck, in case other audio does 
start playing while NVDA is speaking.

On 9/12/2015 1:28 AM, Michael Curran wrote:
> Certainly sounds cool, but:
>
> Windows ducks audio of all sound cards, not just the default. I assume 
> we'll want to check if there is audio playing on any available card? 
> Or should we just use NVDA's currently configured output device?
>
> Also, depending on the speed of the delay in the peak meters, it may 
> inadvertently detect NVDA's own speech. Though if we do the check at 
> the lowest level (i.e.) `audioDucking._setDuckingState`, this is 
> guaranteed not to be called for at least a second after any speech 
> finishes. `_setDuckingState` will also need to return True or false 
> based on whether it actually did change state. If asking to duck and 
> `_setDuckingState` returns false, `_requestDucking` should not do a 
> `time.sleep`.
>
> On 8/12/2015 9:53 PM, James Teh wrote:
>>
>> I think it'd be really good if we can not delay the audio if there 
>> isn't audio playing (or better still, if audio is quiet). So, I've 
>> been looking into this a bit.
>>
>> It seems there are two APIs you can use to get the peak levels for an 
>> audio device:
>>
>>  1. The Windows Core Audio APIs
>>     <https://msdn.microsoft.com/en-gb/library/windows/desktop/dd370784%28v=vs.85%29.aspx>
>>     in Vista and later. These are COM based. Basically, you start
>>     with IMMDeviceEnumerator
>>     <https://msdn.microsoft.com/en-gb/library/windows/desktop/dd371399%28v=vs.85%29.aspx>,
>>     get an IMMDevice
>>     <https://msdn.microsoft.com/en-gb/library/windows/desktop/dd371395%28v=vs.85%29.aspx>
>>     and call IMMDevice::Activate
>>     <https://msdn.microsoft.com/en-gb/library/windows/desktop/dd371405%28v=vs.85%29.aspx>
>>     and request IAudioMeterInformation
>>     <https://msdn.microsoft.com/en-gb/library/windows/desktop/dd368227%28v=vs.85%29.aspx>.
>>
>>       * Unfortunately, as nice as being COM based sounds, calling
>>         CoCreateInstance for IMMDeviceEnumerator results in class not
>>         registered for some reason. mmdevapi.dll doesn't seem to have
>>         a typelib, so I tried generating one from mmdeviceapi.idl.
>>         When I tried to use that with comtypes, it threw a weird
>>         assertion error.
>>       * This StackOverflow thread
>>         <http://stackoverflow.com/questions/32149809/read-and-or-change-windows-8-master-volume-in-python>
>>         shows it's possible to use this API with comtypes, but the
>>         interfaces would all have to be written out.
>>  2. The old Audio Mixer API
>>     <https://msdn.microsoft.com/en-us/library/dd756701%28v=vs.85%29.aspx>
>>     from winmm. This article
>>     <https://support.microsoft.com/en-us/kb/181550> provides details
>>     about how this could be used to get peak levels.
>>       * Unfortunately, there would be a hell of a lot of structs to
>>         write out if we wanted to do this in Python.
>>
>> Of course, I guess we could write the code in C++ and avoid the 
>> Python porting bit. After all, all we want is one damned value.
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/nvaccess/nvda/issues/3830#issuecomment-162860239>.
>>
>
> -- 
> Michael Curran
> Executive Director, NV Access Limited
> Phone: +61 7 3149 3306
> Website:http://www.nvaccess.org/
> Twitter: @NVAccess
> Facebook:http://www.facebook.com/NVAccess

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by jcsteh** [comment]
Ah, I was wondering what audio device(s) Windows ducked. I assumed it 
was just the default.

I guess then it'd make sense to check for audio on all devices.

**Comment by michaelDCurran** [comment]
Using the winmm technique, no waveOut devices of my two sound cards support the peak metre control.  Several posts on the web suggest that cards and/or Windows has not supported this for years.
The stack change article also mentions that winmm is now pretty much local to each application (i.e. the mixer API is specific for the process calling it).
And the stack exchange example itself, only dealt with setting/getting volume control levels, not peak levels as such.
I shall have a look at the COM interfaces in more details to see if any kind of peak metre functionality exists...

**Comment by jcsteh** [comment]
Damn.

> The stack Exchange article also mentions that winmm is now pretty much local to each application (i.e. the mixer API is specific for the process calling it).
> And the stack exchange example itself, only dealt with setting/getting volume control levels, not peak levels as such.

Not that this matters, but out of interest, I assume you're referring to some other article you found (and I probably saw as well)? The article I linked here was from support.microsoft.com and dealt with metering, not volume. The StackOverflow article i linked was for Core Audio. Still, the support article was quite old.

> I shall have a look at the COM interfaces in more detail to see if any kind of peak metre functionality exists...

IAudioMeterInformation has this to say:

> If the audio device lacks a hardware peak meter, the audio engine automatically implements the peak meter in software, transparently to the client.

So I presume that means we can get what we need.

**Comment by nvaccessAuto** [comment]
Incubated in 4b7eeb73f26e9723da02450633ef97774f38ab29.

**Comment by jcsteh** [comment]
Very nice!

Further info on the duck delay not happening sometimes as discussed yesterday. There are two issues.

STR for the first issue:

1. Play some audio in the background.
2. Switch to ducking for speech and sounds.
3. Wait until audio unducks.
4. Press NVDA+shift+d to switch to always duck.
 * Expected: Sleep before speech.
 * Actual: No sleep.

STR for the second issue:
1. Play some audio in the background.
2. Switch to no ducking.
3. After the audio unducks but before 1 second has elapsed, press NVDA+shift+d to switch to ducking for speech and sounds.
 * Expected: Sleep before speech.
 * Actual: No sleep.
 * Audio unducks immediately, which makes sense, but the callLater still seems to apply, so it doesn't think it has to sleep.

**Comment by nvaccessAuto** [comment]
Incubated in dfa326192beb408bda59732f5e08599a8b098a5d.

**Comment by leonardder** [comment]
I found a little issue with the current ducking implementation in next.

STR in Windows 10:

1. Set NVDA to no ducking
2. Start Narrator with ctrl+win+u. Narrator ducks all other audio, except for NVDA
3. Disable Narrator again with ctrl+win+U
    * Expected: Ducking is entirely disabled again
    * Actual: NVDA ducks all other audio until closed or ducking is disabled again with nvda+shift+d

**Comment by michaelDCurran** [comment]
Annoyingly this is not a bug we will be able to fix. The issue is how 
the AccSetRunningUtilityState function in Windows is implemented. Any 
two assistive technologies that try and control audio ducking at the 
same time will most likely cause this.

It should also be noted that we do not recommend running  another Screen 
Reader at the same time as NVDA (including narrator). Of course people 
do it (us certainly as developers do from time to time) however we 
cannot promise system stability if doing so.

On 15/12/2015 7:59 PM, Leonard de Ruijter wrote:
>
> I found a little issue with the current ducking implementation in next.
>
> STR in Windows 10:
>
>  1. Set NVDA to no ducking
>  2. Start Narrator with ctrl+win+u. Narrator ducks all other audio,
>     except for NVDA
>  3. Disable Narrator again with ctrl+win+U
>       * Expected: Ducking is entirely disabled again
>       * Actual: NVDA ducks all other audio until closed or ducking is
>         disabled again with nvda+shift+d
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/3830#issuecomment-164708112>.
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by JamaicanUser** [comment]
Settings for controlling this are not present in the General settings dialog.

**Comment by michaelDCurran** [comment]
They are in the Synthesizer dialog.

What lead you to believe they were in General Settings?
On 7/01/2016 10:35 PM, JamaicanUser wrote:
>
> Settings for controlling this are not present in the General settings 
> dialog.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/3830#issuecomment-169650796>.
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by derekriemer** [comment]
Oddly I thought this at first as well. Maybe we should put what dialog 
it is in the whats new?

On 1/7/2016 11:16 AM, Michael Curran wrote:
> They are in the Synthesizer dialog.
>
> What lead you to believe they were in General Settings?
> On 7/01/2016 10:35 PM, JamaicanUser wrote:
> >
> > Settings for controlling this are not present in the General settings
> > dialog.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nvaccess/nvda/issues/3830#issuecomment-169650796>.
> >
>
> -- 
> Michael Curran
> Executive Director, NV Access Limited
> Phone: +61 7 3149 3306
> Website: http://www.nvaccess.org/
> Twitter: @NVAccess
> Facebook: http://www.facebook.com/NVAccess
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/3830#issuecomment-169760994>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.drupalgardens.com>
Non-proffessional website. <http://derekriemer.pythonanywhere.com/personal>
Awesome little hand built weather app that rocks! 
<http://derekriemer.pythonanywhere.com/weather>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by JamaicanUser** [comment]
@michaelDCurran  in the What's New

**Comment by jcsteh** [comment]
Err, my bad. Brain detached from fingers. :) I'll fix this.
