### ISSUE TITLE
sysListView32.List.columnCount can send to a null HWND

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3843]
**Reported by jteh on 2014-02-03 10:48**
It fetches the header window, but doesn't check whether the result is null. This seems to happen when pressing backspace in Windows Explorer in Windows XP. We shouldn't send messages to a null HWND, though this is normally harmless.

**Comment by leonardder** [comment]
@JCSTeh: Is this XP only? If so, we can safely close as won't fix.

**Comment by jcsteh** [comment]
Windows XP was the only place i could reproduce this, but I guess it could happen if a SysListView32 disappeared while NVDA was querying it. Still, this is harmless and clearly no one has cared for years, so closing.
