### ISSUE TITLE
Support reporting of misspelled words in Windows 8.1 global spellchecker

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3853]
**Reported by k_kolev1985 on 2014-02-06 09:44**
In Windows 8.1, there's a global spellchecking functionality. It works in all "modern" (aka "metro") applications. It allows us to know if we've misspelled  a word and correct it if we want (like we can in applications like MS Word for example). Unfortunately however, NVDA seams not to be able to report if a written word is misspelled or not. The built-in screen reader - Narrator - reports if a word is misspelled as soon as we write the word and insert a space after it, though it does not report it as misspelled if we read line by line with it. NVDA can report misspelled words when we read text (incl line by line) in applications like MS Word and the Mozila products, but it does not do it in the "modern" Windows 8.1 applications. The option to report spelling errors in NVDA -> Settings -> Document Formatting is turned on, of course.

Steps to reproduce it:
1. Open a "modern" Windows 8.1 application (eg. the built-in Calendar).
2. Press the "Applications" key to bring up the context menu and from there choose "Create", to create a new event.
3. Either in the "Subject" or in the "Notes" field, write a misspelled word and insert a space.
4. Read the current line with the respective keystroke for NVDA (eg. NVDA+Up Arrow).
5. Move the text caret on the beginning of the misspelled word or somewhere in it. Then press the "Applications" key to bring up the context menu. If the spellchecker has a suggestion for the misspelled word, it will be in there. In short, you can work with this global spellchecker like you can with the one in the Mozilla products, for example.

Expected results: NVDA should report the written word as misspelled as soon as the space is inserted, or at least when reading the text line by line or word by word.
Actual results: NVDA does not report the written word as misspelled when the space is inserted, nor when reading the text line by line or word by word.

System specs:
- Operating system: Windows 8.1, 32-bit, with locale and regional settings set to "Bulgarian" (incl. a language pack for the interface and the spellchecking).
- NVDA version: next-10304,4e28381, also set to "Bulgarian".

**Comment by jcsteh** [comment]
Fixed as part of #4174 some time ago.
