### ISSUE TITLE
NVDA would not read suggestions or corrections for spell/grammar check in MS Word 2013.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3869]
**Reported by HCDhoundiyal on 2014-02-10 16:53**
When using spell/grammar check in MS Word 2013, NVDA would not read suggestions or corrections if offered.

**Comment by leonardder** [comment]
Since this ticket is Abandoned and we haven't seen similar reports about the suggestion list not being read, closing as duplicate of #3410
