### ISSUE TITLE
Some apps refuse to return physical coordinates for high DPI settings when NVDA is DPI aware

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3875]
**Reported by jteh on 2014-02-11 04:52**
(Spun off ticket:3758#comment:7.)
Some DPI unaware apps such as Steam and Demul give us logical coordinates when we call LogicalToPhysicalPointForPerMonitorDPI (and probably the reverse as well). MSDN says that these functions are supposed to give physical coordinates regardless of DPI awareness, so this seems like a Windows bug. Strangely, the function works as expected when we _aren't_ DPI aware, which is pretty silly.

**Comment by Adriani90** [comment]
@jcsteh any updates on this issue? Was there any further work on it so far?
cc: @michaelDCurran

**Comment by jcsteh** [comment]
No; I never did any work on it beyond my investigations above.

**Comment by seanbudd** [comment]
Is this still an issue? I'm struggling to determine the steps to reproduce this

**Comment by jcsteh** [comment]
I'm not sure. I'd say you could test it as follows:

1. Ensure you're on a high DPI system.
2. Get either Steam or Demul. NO idea where to get them from.
3. Use screen review and try to route the mouse to a particular piece of text on screen.

Assuming these apps are still DPI unaware (and honestly, there's no guarantee of that), if the bug exists, the mouse will get routed to the wrong place.

**Comment by seanbudd** [comment]
Thanks, not knowing step 3 is where I was stuck

**Comment by seanbudd** [comment]
Interesting, the mouse routing appears to work correctly, but with visual highlighting the frames are way off.

**Comment by seanbudd** [comment]
This will be fixed by #13254
