### ISSUE TITLE
When I go to Microsoft Outlook 2007 NVDA slows down, becomes unresponsive

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3876]
**Reported by Vilmantas on 2014-02-11 14:43**
When I go to Microsoft Outlook 2007 NVDA slows down, becomes unresponsive. I use NVDA 2013.3.

**Comment by ehollig** [comment]
There is a lot of watchdog activity in the log provided, however, I do not believe I see anything about Microsoft Word in the log provided. As we are unable to contact the original poster for more specific information, closing as invalid

**Comment by Brian1Gaff** [comment]
I thought this was about Outlook though?
 Incidentally any known reason why Outlook 2003 might be crashing in 
creators update with latest nvda? Not me but a friend and finding it hard to 
get the info I need to find out what is doing wht to which!
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by ehollig** [comment]
@Brian1Gaff, yes, I meant Outlook. Thank you for catching that
