### ISSUE TITLE
Gecko vbuf backend: Don't fetch stuff that isn't needed for a node

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3889]
**Reported by jteh on 2014-02-17 02:54**
We fetch text even when we aren't going to render children, keyboard shortcut and description even when invisible, etc. Where reasonable, this should be fixed, though there are certain cases where doing this would make the code very difficult to read, so don't bother with those.

This depends on #1354, as I started this as part of that work.
**Blocked by #1354**

**Comment by derekriemer** [comment]
@jcsteh Is this still an issue?

**Comment by jcsteh** [comment]
It's still valid, but I suspect the gains won't justify the effort and potential for regressions. There probably aren't that many nodes in the grand scheme of things where we don't render children or which are in the tree but considered invisible. I'm going to close this.
