### ISSUE TITLE
Please implement a workaround for poorly written HTML form controls which only contain their meaningful name in their name, id or even class attribute

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3893]
**Reported by Palacee_hun on 2014-02-17 17:57**
All the findings below apply to Firefox browser. I don't know how IE behaves, for I don't use that browser.
[I have been encountering a lot of such HTML form controls for which NVDA reads nothing more than their role (e.g. "button"). By examinig a lot of these I have found out that these do not follow accessible HTML guidelines at all, however they usually expose their meaningful name in their IAccessible2 attributes, namely in their id or even in their class attribute.[[BR]([BR]]
Recently)]
## Example 1: a "Print" button in an Internet banking interface

[source of the button is:

```
<input type="button" id="nyomtatas" value="" style="padding:0px;cursor:pointer;background-image: url(/style/def_styl/img/buttons/HUN/g_nyomtatas.gif); height:19px;width:108px; border:solid 1px #ffffff" onmouseover="this.style.border='solid 1px #cc0033'" onmouseout="this.style.border='solid 1px #ffffff';" onClick="javascript:print()"  />
```

[[BR]([BR]]
HTML)]
Development info for that control from NVDA log:
[info for navigator object:
name: u''
role: ROLE_BUTTON
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_ButtonMozillaIAccessible object at 0x03E44B70>
Python class mro: (<class 'NVDAObjects.Dynamic_ButtonMozillaIAccessible'>, <class 'NVDAObjects.IAccessible.Button'>, <class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (483, 648, 108, 19)
value: None
appModule: <'firefox' (appName u'firefox', process ID 448) at address 3c0b650>
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 131770L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 452
windowText: u'Budapest Internetbank - Mozilla Firefox'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x19f814 at 3cf0bc0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=131770, objectID=-4, childID=-195457088
IAccessible accName: None
IAccessible accRole: ROLE_SYSTEM_PUSHBUTTON
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: u''
IAccessible accValue: None
IAccessible2 windowHandle: 131770
IAccessible2 uniqueID: -195457088
IAccessible2 role: ROLE_SYSTEM_PUSHBUTTON
IAccessible2 states: IA2_STATE_OPAQUE, IA2_STATE_HORIZONTAL (1040)
IAccessible2 attributes: u'display:inline;id:nyomtatas;tag:INPUT;text-align:center;text-indent:0px;'

```
[[BR]([BR]]
```

Developer)]
The id attribute is the only place from which we can know what this button does: "nyomtatas" (printing in English).[Example 2: a "Place My Order" button in a webshop interface ==
[[BR]([BR]]
==)]
HTML source for the button:

```
                                <input  class='mehet' name='elkuld' type='submit' value='&nbsp;' /> 
```

[info for it from the log:

```
Developer info for navigator object:
name: u''
role: ROLE_BUTTON
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_ButtonMozillaIAccessible object at 0x03EA3050>
Python class mro: (<class 'NVDAObjects.Dynamic_ButtonMozillaIAccessible'>, <class 'NVDAObjects.IAccessible.Button'>, <class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (775, 671, 228, 67)
value: None
appModule: <'firefox' (appName u'firefox', process ID 448) at address 3c0b650>
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 131770L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 452
windowText: u'www.gastroyal.hu - Mozilla Firefox'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x1efba4 at 3cc3e40>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=131770, objectID=-4, childID=-265112080
IAccessible accName: u'\xa0'
IAccessible accRole: ROLE_SYSTEM_PUSHBUTTON
IAccessible accState: STATE_SYSTEM_FLOATING, STATE_SYSTEM_DEFAULT, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1052932)
IAccessible accDescription: u''
IAccessible accValue: None
IAccessible2 windowHandle: 131770
IAccessible2 uniqueID: -265112080
IAccessible2 role: ROLE_SYSTEM_PUSHBUTTON
IAccessible2 states: IA2_STATE_SELECTABLE_TEXT, IA2_STATE_OPAQUE, IA2_STATE_HORIZONTAL (5136)
IAccessible2 attributes: u'display:block;tag:INPUT;text-align:center;text-indent:0px;class:mehet;'
```

[[BR]([BR]]
Development)]
Here the meaningful class attribute 'mehet' ('go!' in English, i.e. place the order in basket) is exposed in the log in IAccessible2 attributes string. There is no id attribute here. It's funny that the HTML source shows a name attribute 'elkuld' (submit in English), which would be equally meaningful, but somehow NVDA does not catch it. It's not obvious to me why.
[[br]]
These obvious examples of bad web authoring regarding accessibility seem to be in the wild. The examples are from sites which I use almost daily. They cause inconvenience, because I either have to memorise what that particular button does, or consult the log for clues (fortunately IAccessible2 attributes are the last line of the entry). Consulting web authors seems a futile approach nowadays, when web authors often compete for the lowest authoring price for a given website, and do not have time, motivation and knowledge to deal with accessibility requests properly. Rendering the meaningful attributes in NVDA does not seem particularly hard in these cases, so it's a far simpler and more fruitful approach. After all it's a smaller issue if we render something that turns not to be too useful for a given control than rendering nothing except the role.

**Blocking #4742**

**Comment by bhavyashah** [comment]
@jcsteh stated in https://github.com/nvaccess/nvda/issues/3893#issuecomment-155317530 that he is leaning towards a wontfix. Unless @leonardder, @feerrenrut and others have thoughts or further discussion, I suggest closing. @ehollig

**Comment by feerrenrut** [comment]
Closing as `wontfix`. While its true that in (probably quite a few cases) exposing the class and id attributes may give an indication of the meaning of an element for technical users, it is also likely to be confusing to non-technical users.
