### ISSUE TITLE
Outlook 2010: When entering an email address in the new message dialog, NVDA does not always speak the address, although it eventually does after typing enough characters.  This seems to happen if there are multiple suggestions while typing an address.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3898]
**Reported by dgoldfield on 2014-02-18 21:10**
This is similar to bug 2816, which was closed as being fixed.  In Outlook 2010, the autocomplete feature while typing in an address does work, but not immediately.  I may have to type several letters before NVDA speaks the name of the contact.  I believe this is not the case in Outlook 2003.

**Comment by leonardder** [comment]
@dgoldfield: Could you still reproduce this?

**Comment by ehollig** [comment]
Closing as worksforme, as we have not heard from the original poster in awhile.
Also, when I type a name or an address in Outlook 2016, autocomplete results do not show visually, and are not read until after typing a few characters.
