### ISSUE TITLE
Crash without restart as Thunderbird receives mail

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3911]
**Reported by MarcoZehe on 2014-02-21 06:44**
This crash occurred while I was reading on FB in Firefox Nightly and Thunderbird received new mail in the background. NVDA fell silent the moment I heard the New Mail sound. Master-9919,f591be4.

**Comment by bhavyashah** [comment]
@jcsteh In https://github.com/nvaccess/nvda/issues/3911#issuecomment-155317667, you were hoping that this issue might already be fixed. Is it so?

**Comment by jcsteh** [comment]
No idea. However, we haven't had any further reports of this, so closing as works for me. Note that our crash dumps and logs are a lot more useful now, so we should have more luck in tracking this down if it happens again in future.
