### ISSUE TITLE
cannot read first search result on windows 8 start screen!

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3914]
**Reported by aslani.ali on 2014-02-22 09:01**
I have windows 8 installed with 3 imput languages installed. when start key on keyboard is pressed, I begin to type in, but no result is reported by NVDA.

**Comment by bhavyashah** [comment]
@jcsteh seems to state as a fact that this issue is specific to Windows 8 in https://github.com/nvaccess/nvda/issues/3914#issuecomment-155317679. If this is indeed the case, Windows 8 has been superceded by Windows 8.1, and thus, I suggest closing. @ehollig

**Comment by ehollig** [comment]
Closing, as this sounds to be Windows 8 specific, and @jcsteh says in https://github.com/nvaccess/nvda/issues/3914#issuecomment-155317679 that this works properly in Windows 8.1.
