### ISSUE TITLE
nvda complex symbols copying and pasting

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3919]
**Reported by JamaicanUser on 2014-02-24 15:01**
Out there, there is an add-on for the copying and pasting of complex symbols not found on the keyboard, such as the degrees sign, acute letters and math signs. This add-on is not properly translated, however. In JAWS, this function is integrated with a simple keystroke. I would like this feature to be integrated into NVDA.

**Comment by bhavyashah** [comment]
@jcsteh Based on https://github.com/nvaccess/nvda/issues/3919#issuecomment-155317711,, should this ticket be closed as a wontfix or left open as a P4?

**Comment by jcsteh** [comment]
Closing as won't fix.
