### ISSUE TITLE
Support descriptions of HTML/XML objects

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#392]
**Reported by benjaminhawkeslewis on 2009-08-18 06:41**
Support advisement of, presentation of, and interaction with long descriptions of HTML/XML elements on content focus, including:
1. Same-page descriptions referenced with "aria-describedby" on the "table" element. Treat similarly to "summary", perhaps.
2. Same-page descriptions referenced with "aria-describedby" (all other elements, but especially "img", controls, fields).
3. Same-page descriptions referenced with "longdesc" ("img", "frame", "iframe" elements).
4. Other-page descriptions referenced with "longdesc" ("img", "iframe", "iframe" elements).
5. Perhaps legacy "D" links ("img" elements)?
6. Perhaps SVG descriptions: http://www.w3.org/TR/SVG11/struct.html#DescriptionAndTitleElements ?

I've left out other-page descriptions referenced with "aria-describedby", since it's unclear whether those are going to be allowed or not. They'd work by treating:

<img src="sales.png" alt="Sales Chart" aria-describedyby="description">
<a id="description" href="sales-trend.html">Sales Trend</a>

as roughly equivalent to:

<img src="sales.png" alt="Sales Chart" longdesc="sales-trend.html">

I call out "interaction with" because descriptions can be more than text - they can contain links, controls, data tables, and so on.

It may be simple text descriptions would benefit from different behavior than complex descriptions.

**Comment by leonardder** [comment]
We do have the support to report long descriptions now.

@benjaminhawkeslewis: Assuming you opened this ticket years ago, could you elaborate on what you'd like to see in NVDA exactly?

**Comment by jcsteh** [comment]
As noted above, you can access long descriptions with NVDA+d. Also, you can access descriptions such as aria-describedby by using NVDA+tab (if the object in question has focus) or NVDA+numpad5 (laptop: NVDA+shift+o) if it isn't focusable but is beneath the browse mode cursor.
