### ISSUE TITLE
Mail client in Windows 8 no speech in  messagefield

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3920]
**Reported by Torben on 2014-02-24 18:46**
Hi.
To do a long story short, so is my problem that  NVDA stops the speech when i tabulate from subject field to  the text/messagefield in the mail  app (Metro app)
I can  not tabulate to the next field or buttons. to get speech back i only can tabulate backwards until  NVDA says  subject.  Typing in message is no problem but  there is  no way to verify  the text and so on using arrowkeys.
The problem  is both on my pc and on my labtop and  the problem  also was present before updating to windows 8.1 pro.

When  i starts up narrator  there is no problem in the text field.
I am using a danish sapi voice (CARSTEN) 
i have tried to use  the built in speches and  the microsoft sapi voices but it is the same...no speech after typing.i hav made a NVDA + F1 and pasted it below, maybe that can give you a hint to solve this.
INFO - **main** (14:16:53):
Starting NVDA
INFO - core.main (14:16:53):
Config dir: C:\Users\Torben\AppData\Roaming\nvda
INFO - core.main (14:16:53):
NVDA version 2013.3
INFO - core.main (14:16:53):
Using Windows version sys.getwindowsversion(major=6, minor=2, build=9200, platform=2, service_pack='')
INFO - core.main (14:16:53):
Using Python version 2.7.5 (default, May 15 2013, 22:43:36) [v.1500 32 bit (Intel)](MSC)
INFO - core.main (14:16:53):
Using comtypes version 0.6.2
INFO - synthDriverHandler.setSynth (14:16:54):
Loaded synthDriver sapi4
INFO - core.main (14:16:54):
Using wx version 2.8.12.1 (msw-unicode)
INFO - braille.initialize (14:16:54):
Using liblouis version 2.5.3
INFO - braille.BrailleHandler.setDisplayByName (14:16:54):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - brailleInput.initialize (14:16:54):
Braille input initialized
INFO - core.main (14:16:54):
NVDA initialized
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (14:31:30):
Developer info for navigator object:
name: u', Meddelelse i en samtale, Emne SV: sms p\xe5 computer, Modtaget \u200e20\u200e. \u200enov, Fra Jens Jensen, Ul\xe6st, , , , ,'
role: ROLE_LISTITEM
states: STATE_FOCUSABLE, STATE_SELECTABLE, STATE_FOCUSED, STATE_SELECTED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.IAccessible.MSHTML.MSHTML object at 0x05232950>
Python class mro: (<class 'NVDAObjects.IAccessible.MSHTML.MSHTML'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u'2 af 3'
location: (180, 360, 438, 56)
value: None
appModule: <'wwahost' (appName u'wwahost', process ID 3380) at address 25b3310>
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 131790
windowClassName: u'Internet Explorer_Server'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 4220
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x970d8b0 at 52b18a0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=131790, objectID=205, childID=0
IAccessible accName: u', Meddelelse i en samtale, Emne SV: sms p\xe5 computer, Modtaget \u200e20\u200e. \u200enov, Fra Jens Jensen, Ul\xe6st, , , , ,'
IAccessible accRole: ROLE_SYSTEM_LISTITEM
IAccessible accState: STATE_SYSTEM_SELECTABLE, STATE_SYSTEM_SELECTED, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (3145734)
IAccessible accDescription: u'2 af 3'
IAccessible accValue: None
MSHTML node has ancestor IAccessible: False
MSHTML nodeName: u'DIV'
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (14:34:51):
Developer info for navigator object:
name: u'Br\xf8dtekst'
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_EDITABLE, STATE_FOCUSED
isFocusable: False
hasFocus: True
Python object: <NVDAObjects.IAccessible.MSHTML.MSHTML object at 0x052AEF90>
Python class mro: (<class 'NVDAObjects.IAccessible.MSHTML.MSHTML'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (0, 0, 742, 522)
value: ''
appModule: <'wwahost' (appName u'wwahost', process ID 3380) at address 25b3310>
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 131790
windowClassName: u'Internet Explorer_Server'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 4220
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x9745238 at 51338f0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=131790, objectID=54, childID=0
IAccessible accName: u'Br\xf8dtekst'
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: None
IAccessible accValue: None
MSHTML node has ancestor IAccessible: False
MSHTML nodeName: u'DIV'
INFO - updateCheck.AutoUpdateChecker._started (19:28:01):
Performing automatic update check
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (19:39:22):
Developer info for navigator object:
name: u'Br\xf8dtekst'
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_EDITABLE, STATE_FOCUSED
isFocusable: False
hasFocus: True
Python object: <NVDAObjects.IAccessible.MSHTML.MSHTML object at 0x05523A70>
Python class mro: (<class 'NVDAObjects.IAccessible.MSHTML.MSHTML'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (0, 0, 742, 522)
value: ''
appModule: <'wwahost' (appName u'wwahost', process ID 3380) at address 25b3310>
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 131790
windowClassName: u'Internet Explorer_Server'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 4220
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0xa030de0 at 51a7670>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=131790, objectID=54, childID=0
IAccessible accName: u'Br\xf8dtekst'
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: None
IAccessible accValue: None
MSHTML node has ancestor IAccessible: False
MSHTML nodeName: u'DIV'

Best regards, and thanks for your GREAT efforts in helping and developing
Torben Frederiksen
Aalborg, denmark.

**Comment by ehollig** [comment]
Any updates on this one? CC @josephsl

**Comment by josephsl** [comment]
Hi, at this point, it would be preferable to move to Windows 10 version. Thanks.

**Comment by ehollig** [comment]
Closing as duplicate of #3226, as it contains a priority.
