### ISSUE TITLE
unnecessary braille refresh in firefox when line contains a hyperlink

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3924]
**Reported by halim on 2014-02-25 20:53**
Nvda uses dots 7 and 8 to highlight a hyperlink when brailledisplay is tethered to review.
This works as expected but:
The line gets writen twice on the braille display.
First write is without highlighted hyperlink. Second write uses dots 7 and 8 to underline the link.
The time between these writes is about 200 ms so the two writes are visible on braille display.

If you set debug to input / output you can see the two writes in the log.

**Comment by leonardder** [comment]
@DKager, have you seen this during your work for reporting links in braille?

**Comment by dkager** [comment]
> Nvda uses dots 7 and 8 to highlight a hyperlink when brailledisplay is tethered to review.

I can only reproduce this by:
- Tethering to review.
- Turning on the cursor.
- Going into focus mode, then back into browse mode.

But I don't see oduble writes. Of course that could be because the writes occur in a short time.

**Comment by Adriani90** [comment]
@halim is this a significant  issue for you? As @dkager points out in his comment above, the double line possibly appears in a very short time range and is probably not noticeable by users in most cases.

**Comment by Adriani90** [comment]
We do not have an update if this is a significant issue for the initial author. We also don't have other user reports which reveal any negative impact on user experience. I am closing this issue but feel free to comment on it if it is significant. We can reopen the discussion then.
