### ISSUE TITLE
Message window in thunderbird 27 beta: bottom line not being read

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3927]
**Reported by leonarddr on 2014-02-26 08:55**
When using Thunderbird 27.0 beta for creating an e-mail message, the bottom line of the message doesn't read properly when arrowing through the message. Letter by letter navigation works properly though. I wonder whether this is a Thunderbird problem or NVDA spesific

**Comment by leonardder** [comment]
Can't reproduce any more, closed.
