### ISSUE TITLE
Make Mouse tracking report the state of controls

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3930]
**Reported by k_kolev1985 on 2014-02-26 11:43**
Currently, NVDA's mouse tracking can detect what type of control is under the cursor, but it can't detect its state. For example - it tells us that the mouse is under a check-box or a radio-button, but it does not tell us if those controls are checked or not. Also, it does not tell us if a control is available for interaction or not (eg. if a menu item is unavailable). When a control is focused via the keyboard and it is unavailable (eg. a menu item), NVDA reports that it is unavailable. Can the mouse tracking be improved, so those things are reported from NVDA via its mouse tracking as well?

**Comment by leonardder** [comment]
CC @k-kolev1985 

@JCSTeh: Honestly I've never understood why "Report role when mouse enters object" isn't the default. May be we can extend this option to have the control under the mouse reported based on the output for REASON_FOCUS?

**Comment by jcsteh** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [16 Jul 2017, 01:26 GMT+12](https://github.com/nvaccess/nvda/issues/3930#issuecomment-315533900 "2017-07-15T13:26:17Z - Replied by Github Reply Comments"):
> Honestly I've never understood why "Report role when mouse enters object" isn't the default.

The use cases for NVDA mouse tracking are somewhat different (and more varied) than those for the keyboard. My understanding is that some partially sighted users have enough sight to see the controls on the screen, but not enough to read the text, so they use mouse tracking purely to help them access text. Of course, this doesn't apply to all users, though I believe our feeling was that more users would use it like this.

> May be we can extend this option to have the control under the mouse reported based on the output for REASON_FOCUS?

I agree it probably does make sense to report states, but reporting exactly the way we report focus isn't really possible if, for example, the user chooses to mouse track by word. That would result in duplicate information in editable text controls, for example.

CC @MichaelDCurran for his thoughts.

**Comment by jcsteh** [comment]
CC @QChristensen for his thoughts as well.

**Comment by Qchristensen** [comment]
Good point re when to read what.  Assume you had a checkbox with the label "some label" to the right.  If text unit resolution was set to word, would you read the checkbox with the word "some" or as its own word to the left of "some".

Mouse tracking also doesn't announce things like headings or font changes (from the last text read?).  The mouse settings dialog isn't too busy, so theoretically extra options could be added to control whether such information was read (without looking at what is involved in adding such features), the question then is whether enough users want it.

**Comment by Adriani90** [comment]
I don't know if this is really needed. Let's take the perspective of a blind person. This person would use focus mode or browse mode to navigate and would route the mouse to certain areas out of those modes. In some cases the mouse would be routed from object navigation mode. So, before routing the mouse, the blind person already gets this state information in braille or speech.
Now, for a visually impaired person who uses the physical mouse to navigate, there is other visual information which is used to gather this information. However, I think if magnification is implemented in NVDA, speech could be minimized to report only states and formating information because I think in some cases for a visual impaired person they are hard to recognize.

**Comment by Qchristensen** [comment]
I think having the ability to have information such as the state of checkboxes announced when moving the mouse over them is still important - perhaps even moreso now that not every two-state control has a box with a tick in it.  Whether a control is enabled or not in Word's ribbon (eg Bold or underline) is distinguished by a very subtle colour change in the background of the control itself.

**Comment by Adriani90** [comment]
This is working as expected in NVDA last alpha, introduced by #15518. Closing as fixed.
