### ISSUE TITLE
Incorrect reading of Unicode text in menu items of some applications

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3935]
**Reported by a11cf0.vk on 2014-02-28 09:36**
Hello.
This accurs in some applications like [PeaZip](http://peazip.org/).
Steps to reproduce:
1. Open PeaZip
2. Change application language to Russian, for example
3. Try to access the menu bar and navigate the menus.

Expacted result: all text should be read correctly.
Actual result: some menu items are read as if the text is in a wrong encoding, but when pressing NVDA+Ctrl+F2 everything is read correctly.
Testid on Windows 7 64-bit with a 64-bit version of PeaZip. The system language is Russian.
Thanks.

**Comment by leonardder** [comment]
This ticket looks abandoned, has anything like this been seen during the last three years? I will close this issue around this time next week if we don't get any response.
