### ISSUE TITLE
Screen review is not updated properly upon content change

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3943]
**Reported by erion on 2014-03-02 11:19**
When screen review is used and an application updates its window, previous chunks of its content are still readable if the new text is smaller in length.
See the attached application as an example. Its label should be read using screen review. After about ten seconds, the label's text changes.
This does not occur via object navigation.
Windows 8.1 x64 and NVDA next-10400,e57e598 were used.

**Comment by Adriani90** [comment]
We do not have any updates from the author since 5 years or so. I am closing this as works for me. Please comment on it if you are still having this problem and we can reopen the discussion.
