### ISSUE TITLE
Get rid of previous and next review mode commands and replace them with a more intuitive solution.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3958]
**Reported by driemer.riemer@... on 2014-03-08 09:47**
When navigating in screen or object review, I feel it would be a better option to make  the previous and next review modes into one command. This would cycle through the allowed options and thus eliminate the notion of having to go backwards through the options and then forward through them. I have seen confusion with some newbies to nvda when doing this, because other screen readers don't have the notion of cycling through the review modes. My proposed solution would be to rap backwards once the end is reached. So when in screen review, if the command was pressed to move forward, nvda would report "Object review." When repeating, nvda would hop back to screen review, rather than speaking "no next review option" and so forth. I feel this would simplify the use of nvda to navigate with review modes, first because it would decrease the number of keystrokes one must learn, secondly it would decrease the number of translatable strings needing to be maintained, and thirdly because it would free up a key for other nvda commands.

**Comment by surfer0627** [comment]
See also #3392.

**Comment by leonardder** [comment]
Closing as duplicate of #3392.
