### ISSUE TITLE
When I tab around in Outlook 2013 often times I hear, "DAL=on"

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3959]
**Reported by csm120 on 2014-03-08 17:37**
Mostly when I'm in text emails I'll hear, "DAL=on text" Most of the time this message is heard within text emails. I do sometimes hear it in html emails as well. It seems to be related to embedded objects within html emails. I also seem to hear this when tabbing through static text, or read only boxes. Below is what the log had right after I tabbed and got the dal message. I'm running NVDA 2014 RC4, but have seen it in many earlier NVDA versions prior. I'm also running Windows 8.1 X64.

name: u'DAL=on'
role: ROLE_STATICTEXT
states: STATE_READONLY
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.StaticText object at 0x04CE29D0>
Python class mro: (<class 'NVDAObjects.IAccessible.StaticText'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (3, 149, 0, 0)
value: None
appModule: <'outlook' (appName u'outlook', process ID 6252) at address 4adeb50>
appModule.productName: u'Microsoft Outlook'
appModule.productVersion: u'15.0.4569.1503'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 1509422
windowClassName: u'Static'
windowControlID: 4557
windowStyle: 1375797248
windowThreadID: 580
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x7ce9440 at 4e3ae40>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=1509422, objectID=-4, childID=0
IAccessible accName: u'DAL=on'
IAccessible accRole: ROLE_SYSTEM_STATICTEXT
IAccessible accState: STATE_SYSTEM_READONLY, STATE_SYSTEM_VALID (64)
IAccessible accDescription: None
IAccessible accValue: None

**Comment by leonardder** [comment]
@csm120: Can you still reproduce this?

**Comment by Adriani90** [comment]
I could reproduce this rarely. But this is not very reliably. At least it was so trivial that I couldn' find a way to reproduce it reliably. I didn't see any reports about this for any other users and I think this does not impact user experience at all.
@csm120 is this a significant issue for you?

**Comment by Adriani90** [comment]
DAL (data access layer) seems to be used for several dialogs in Office to group different data. But I have no idea why we get this information over the API.
Since this is not happening everytime when we press tab, it does not really impact user experience. Moreover, we do not have exact steps to reproduce so it will be quite hard to reproduce. Feel free to report this to Microsoft, they are at the best position to handle this. I am closing this for now.
