### ISSUE TITLE
It reads first line only

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3966]
**Reported by satguru59 on 2014-03-11 08:40**
When i moove the cursor it mooves the first line only and doesnt read the second line even if i moove cursor towards it on some pages not all.
http://www.shabdkosh.com/forums/viewthread/1071

Like on the above page it reads only first line not second line

**Comment by leonardder** [comment]
I haven't seen such behavior ever before, and we really need more information to track something like this down. Closing as invalid.
