### ISSUE TITLE
Powerpoint to announce the number of slides as you open the document.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3969]
**Reported by jacobchawala on 2014-03-11 21:35**
as you open the created powerpoint slides, it is helpful for NVDA to announce the number of slides present in the whole document. this helps the reader to know the length of the document even without navigating to slides. in slide view, NVDA should also mention the slide you are in number as it is in thumbnails for instance, 3 of 20.

**Comment by leonardder** [comment]
@qchristensen: is the number of slides instantly visible for sighted users when they open a presentation?

**Comment by Qchristensen** [comment]
When you open a presentation, visually you can see the first 4 or 5 slides down the left side in the slides list.  Just under that, the status bar has "Slide 1 of 100" (or however many slides there are).  You can press NVDA+end (laptop: NVDA+shift+end) to read that.  I can see the benefit in knowing the number of slides, although this isn't announced for other programs - eg number of pages in a Word document (that could be an argument either way).

Re announcing the slide number when changing slides.  If you press page down when you are on the slide itself, NVDA simply announces "Slide 3".  If you press down arrow in the slide list, NVDA does read "Slide 3 of 100", though interestingly if you press page down from the slide list, it reads "Slide 3".  I'd be happy for this to be consistently announced as "Slide X of Y".

**Comment by Adriani90** [comment]
This information can be retrieved via status bar as explained above by Quentin which is comfortable in my opinion and prevents NVDA from being overly verbose. Additional information such as automatic announcement of slides when opening the document etc. need to be implemented on Powerpoint side, there is nothing NVDA can do about this if Microsoft doesn't provide the information in the correct format.

I am closing as can't fix, but feel free to comment in case you have any further arguments, and we can reopen.
