### ISSUE TITLE
Inability to select line by line or by paragraph in a notepad

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3970]
**Reported by jacobchawala on 2014-03-11 21:53**
after writing some texts in several lines or paragraph in a notepad, you can select character by character by pressing shift+right or left arrow, word to word by pressing control+shift+right or left arrow, but you can not select line by line or paragraph by paragraph by pressing control+shift+down arrow. this command  control+shift+down arrow does well in word and word pad.

**Comment by bhavyashah** [comment]
I am pretty sure that Jacob and Brendon were reporting the inability to select paragraphs in Notepad, something beyond the scope of NVDA, and anyways, we cannot contact them anymore. Time to close? @ehollig

**Comment by Brian1Gaff** [comment]
Isn't this all tied in with the lack of windows commands that work in 
Notepad and other text editors?
 If you, of example try to delete words in notepad you merely insert control 
characters into the file, not delete anything.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by ehollig** [comment]
#7052 discusses moving by paragraph in notepad and possibly can include selecting text. As that issue has a priority, closing this in favor of #7052
