### ISSUE TITLE
Ref bug#1686-Word 2013 docs are not read with UP/DOWN ARROW in protected view.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3972]
**Reported by sumandogra on 2014-03-12 09:02**
In word 2013, one cannot read line by line with  UP/DOWN ARROW in protected view when MSWord docs are downloaded as attachments from emails(Reference bug#1686).
Steps:
1.  Download a MSWord document attachment from an email
2.  Open the document.
3.  The document will open in protected view.
4.  Read the document with UP/DOWN arrow.
5.  One will not be able to read the document. On using UP/DOWN ARROW, one moves between pages instead of going to next/previous line.
6.  Say All command is available in this protected view.

**Comment by Qchristensen** [comment]
There are I think two problems.  One I have documented separately in Issue #7540.

The other option is that Word, by default, opens protected documents (e-mail attachments and documents downloaded from the web) in "Reading View".  Say all works in this mode, but up and down arrows move the view by one page.  You can use control+down arrow and control+up arrow to move by line as a workaround, alternatively press control+alt+p to return to print layout - note that the document is still in protected mode.  There is an option in Word's general options page to open protected documents in reading view.  Uncheck this option to open these documents in print layout.

It's then a philosophical debate about whether we hijack navigation commands in reading mode to work how users expect them to from other view modes, or instruct users on how to read in that mode or change to another mode.

**Comment by Adriani90** [comment]
@sumandogra are you still reproducing this issue? In Office 2010 at least, NVDA can read out the text even if the document is protected.

**Comment by Adriani90** [comment]
@Qchristensen yan you also try to reproduce it?

**Comment by Qchristensen** [comment]
@Adriani90 as per my [previous comment](https://github.com/nvaccess/nvda/issues/3972#issuecomment-325854329) I can read documents in protected view, yes.  I recommend turning off the option to display protected view documents in reading view - they will then open in print layout but still protected.  I'm using Word 365, I haven't tried in Office 2013 or earlier.
