### ISSUE TITLE
Usability of Thunderbird message viewer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#398]
**Reported by aleksey_s on 2009-08-23 11:06**
Thunderbird's message viewer is pretty comfortable. You can navigate forward/backward through unread/all messages and threads by pressing quick navigation keys b,f,n,t and p. however, Its usability  conflicts with NVDA virtual buffer quick-nav keys. Pressing nvda+space each time you want skip the message can become quite nasty. 
I am thinking about some customized virtual buffer for thunderbird appModule, which will pass those keys to message viewer. Or we can go further and implement mode, in which nvda virtual buffer will act as regular text field without any quick-nav keys. Therefore this mode can be enabled by user when desired.

**Comment by leonardder** [comment]
Would it be easily possible to disable quick navigation by default for thunderbird message view now that 33203 is there?

**Comment by bdorer** [comment]
This would be great to have

**Comment by Adriani90** [comment]
@leonardder is this somehow addressed by the PR #8846 which has been recently merged allowing browse mode to be disabled by default? Or is that working only for browsers?

**Comment by leonardder** [comment]
@Adriani90: Disabling browse mode by default should work for thunderbird, yes. However, disabling browse mode also destroys the ability to navigate through the message content, so is definitely not what one would do when working nonvisually.

**Comment by Adriani90** [comment]
Ok, this works quite good when disabling quick navigation with nvda+shift+space bar. But quick navigation gets automatically enabled after a dialog is displayed or when the cursor jumps to another area on the thunderbird window.
Is it possible to turn off quick navigation for an application entirely until you press nvda+shift+space bar again?

**Comment by Adriani90** [comment]
I am onl keyboard layout Laptop.

**Comment by Adriani90** [comment]
Hmm this behavior seems to have changed in Thunderbird 68.3.0 and NVDA alpha 19420,a2c6f0f8.
I cannot really reproduce this anymore.
Is anyone able to reproduce this?

**Comment by Adriani90** [comment]
Ok, I am closing this issue since I cannot reproduce it and I didn't hear any further user reports on this.
Closing as owrks for me.
