### ISSUE TITLE
aria-relevant ignored

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3982]
**Reported by gwailoh on 2014-03-15 15:48**
With Firefox or Chrome, visit this page: [http://test.cita.illinois.edu/aria/live/live1.php].  Set the controls for the "Live Region 2: Text Log" test to: Live Property Value: polite; Atomic Property Value: false; Relevant Property Value: additions.  NVDA should read each line which is appended to the text box labeled "Log Text", and should read only that line.  Instead, each time a line is appended it re-reads the entire text box from beginning to end, as if the Relevant Property Value had been set to "all".

**Comment by ehollig** [comment]
@jcsteh, should this be closed as you said in https://github.com/nvaccess/nvda/issues/3982#issuecomment-155318439 that this particular test case is broken?
