### ISSUE TITLE
Can you offer some variables to set the reading order of the WEBSite controls?

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3984]
**Reported by vgjh2005 on 2014-03-16 01:11**
When we browse the website with arrow keys, NVDA can read lots of information about the kinds of control. For example, we can know where we are  on the table. Which control we are browsing etc.  The name of the control is different. Get the name of the controls is important than the control. So,I hope to change the order between content and control notifications. Let me make a test for this: I press the down arror key, Out of list Main landmark Heading level 1 Create a new ticket.  If we can change it to  Create a new ticket  Out of list Main landmark Heading level 1 , we can know what we are browsing and what it is. Because custom is always different in the world. I hope to set some variables to let translators set in themselves custom.
Thanks!

**Comment by leonardder** [comment]
Closing as duplicate of #1956 and #3207
