### ISSUE TITLE
Shorter names for commands in Input Gestures dialog

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3989]
**Reported by vgjh2005 on 2014-03-17 05:23**
I think add a EditBox to search by the hotkey name/Hotkey description or by the hotkey can find what key we need more quickly. The hotkey name is too long now, I think if NVDA collect the hotkey quick preference's name to do the hotkey name on it, it is better. Put the descriptions after the hotkey defined. Speaking of the cancel button, I modified a hotkey to the tab key, but I forget what key I change, so I press the cancel button  at last. unfortunately, the key didn't be reset. I cannot control my computer at all, I cannot  choose but to let NVDA into factory state.

**Comment by bhavyashah** [comment]
@jcsteh A search option for the Input Gestures dialog is now available. However, does this ticket concern manually shortening the command descriptions of various NVDA keyboard shortcuts for the Input Gestures dialog (which implies the Input Help mode also, I believe), or simply making the command descriptions found in the user Guide and the messages spoken during Input Help mode and present in the Input Gestures dialog consistent? If the latter interpretation is correct, I think the ticket title might need to be revised to increase clarity.

**Comment by jcsteh** [comment]
1. This issue covers shortening the names for the Input Gestures dialog.
2. We don't want to shorten them for input help. Thus, we would need to add a new name attribute to use in the Input Gestures dialog and use the existing message (the description) in input help.
3. The User Guide includes both a (shorter) name and a (longer) description. I don't think we need to be strict about the descriptions being consistent. The names might serve as a good starting point for the new names to be used in the Input Gestures dialog.
