### ISSUE TITLE
NVDA prevents automatic system standby

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#400]
**Reported by jteh on 2009-08-25 03:42**
While NVDA is running, the system will not go into standby mode automatically despite being configured to do so.

Str:
1. Ensure that no other background tasks which will prevent standby are running; e.g. audio players, etc.
2. Set the system standby time to 1 minute. (In Windows XP, Control Panel -> Power Options -> Power Schemes tab -> System standby...)
3. Press NVDA+f12 and let the speech reach completion. Do not hit control to interrupt it. Otherwise, the speech will pause instead of finishing.
4. Wait a little more than 1 minute.
   Actual: The system does not go into standby mode.
   Expected: The system should go into standby mode after 1 minute.

Additional info:
This occurs because tones keeps an instance of `nvwave.WavePlayer` which it does not close after each tone plays. We do this so that we don't have to (synchronously) wait for the tone to finish playing. Calling `tones.player.close()` from the Python Console fixes this problem. Fixing this will require refactoring the tones code so that it calls `player.idle()` after each tone, which will probably need to be done in a background thread.

**Comment by leonardder** [comment]
@JCSTeh: Is this still an issue?

**Comment by jcsteh** [comment]
I'm not certain, but I'm pretty sure I've seen automatic standby work in the past few years. My guess is that this is an XP specific issue. It'd be great if someone can confirm that automatic standby works after playing beeps; e.g. progress bar beeps or mouse tracking beeps.

**Comment by ehollig** [comment]
@Brian1Gaff, is this something you could test?

**Comment by ehollig** [comment]
CC @Brian1Gaff

**Comment by Brian1Gaff** [comment]
Unfortunately at this time my elderly laptop only runs xp, though I am going 
to get a more modern one.
 However one needs to be very careful about terminating sound systems. Even 
now on some machines I notice synths tend to click at the end of speech or 
beeps as if the zero crossing is not working, ie if you stop sound with the 
voltage not at zero you tend to get a loud click on some hardware or even 
lose the last part of a word. Drivers??

This has been seen on windows 7 and 10 desktops, and a friends Dell laptop 
running vista.

Sorry I can be of no further help right now.
Brian

**Comment by feerrenrut** [comment]
@Brian1Gaff I think there was some miscommunication here.

Would you mind testing this on your xp laptop:
1. Ensure that no other background tasks which will prevent standby are running; e.g. audio players, etc.
1. Set the system standby time to 1 minute. (In Windows XP, Control Panel -> Power Options -> Power Schemes tab -> System standby...)
1. Get NVDA to play some beeps; e.g. progress bar beeps or mouse tracking beeps.
1. Wait a little more than 1 minute and confirm that automatic standby works.

Thanks!

**Comment by jcsteh** [comment]
Is there any point in doing XP specific testing given that we no longer support XP? It might make more sense to test this on Windows 7 (the earliest OS we now support). If the problem doesn't exist there, we can happily close this.

**Comment by feerrenrut** [comment]
I was suggesting this based on a comment suggesting this was likely specific to XP. But if someone has encountered it on another machine, that would handy to know also. If we can reliably reproduce on XP, and using the same machine/steps not reproduce on later OS, then we can close the issue.

That said, reliable steps to reproduce (on any machine / OS) are required to progress the issue.

**Comment by Brian1Gaff** [comment]
OK I'll have some time to look into it at the weekend.
 I set standby auto to off at the moment as I got fed up with having to log 
myself back in after listening to a radio station for a bit, but that was 
with the lid open which takes longer.
 Brian

**Comment by Brian1Gaff** [comment]
That was what I thought, but what the hell, I'll try it at the weekend in 
any case.
 Brian

**Comment by Brian1Gaff** [comment]
Well I tried this on the last known good snap that ran on xp next branch, 
and it always worked fine. It went into standby. When it wooke up it seemed 
a little confused at first complaining a network cable was unplugged as it 
span up and  all that, but after around 30 seconds it was working fine.

That is the best i can do for the laptop tests, as I have not updated the OS 
though it says it will run 32 bit windows 7 as it stands.
 Its a dell Inspiron series  machine with a core duo thing in it and 2 gig 
of ram, and a full size keyboard.


Brian

**Comment by ehollig** [comment]
@Brian1Gaff, do you have a Windows 7 machine in which you could test this issue? If the problem doesn't exist there, we can close this issue.
On Windows 7, in the power settings, set the automatic system standby to occur when the computer has been inactive for a period of time.
Do something on the computer that would cause progress bar beeps (copying files, for example), and let the computer sit until it goes into standby.
If the computer is able to automatically go into standby on Windows 7, then I think we can safely close this issue.

**Comment by Brian1Gaff** [comment]
No that was my original point, I do not.
 Brian

**Comment by feerrenrut** [comment]
I have tested this on a Windows 7 VM, I wasn't able to reproduce it.
- I went to `Control Panel\Hardware and Sound\Power Options\Edit Plan Settings` and set "put the computer to sleep" to 1 min.
- I then copied a bunch of files, to hear the beeps.
- I waited 1 minute and the VM suspended. 

While this may be sound driver specific, I think we can close this issue.

If anyone can reproduce this, please comment / reopen.
