### ISSUE TITLE
MS Word: First character outside a table merged into it

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4010]
**Reported by Sukil on 2014-03-21 16:43**
In Word, when a table ends andthere is text right below it, the next navigation command after the last text chunk in teh table (next character, next word or next line) announces its output as if they were inside the table. I know this because when navigating line by line the line is announced inside the table, and when navigating character by character, only te first characters is announced this way.

**Comment by leonardder** [comment]
I can't reproduce this in [Table test.docx](https://github.com/nvaccess/nvda/files/1150148/Table.test.docx). However, when in the second row of the table, arrowing right announces a non-existent, second column.

**Comment by leonardder** [comment]
Closing as works for me. Regarding the issue I mentioned above, that one has a separate issue (#4876)
