### ISSUE TITLE
The US 6-dot computer Braille table renders capital letters in 8-dot Braille

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4014]
**Reported by mhorspool on 2014-03-23 02:40**
Capital letters are indicated by the presence of a dot 7 even though I have specifically selected the US 6-dot computer Braille table.  This is most irritating as I am using NVDA to proofread BRF files produced by Braille translation software and the added dots are getting in the way.

**Comment by bhavyashah** [comment]
@josephsl's https://github.com/nvaccess/nvda/issues/4014#issuecomment-155318747 seems to indicate that resolving this ticket may need an external fix, requiring the NeedsExternalFix to be added. Also, @dkager, since you expressed interest in the reported issue in https://github.com/nvaccess/nvda/issues/4014#issuecomment-155318749, feel free to provide a status update, in case there is any.

**Comment by dkager** [comment]
Label added.

**Comment by leonardder** [comment]
Does the inclusion into NVDA for this table even make sense, given that it's broken? Are there major differences between the 6-dot and 8-dot table?

**Comment by dkager** [comment]
It appears that the combination of NVDA with liblouis uses dots 456 (i.e. not dot 7) to indicate capitals only when "Expand to computer braille for the word at the cursor" is enabled and the cursor is at the particular word.

**Comment by Adriani90** [comment]
Is this an issue someone looks into? Is there a coresponding bug filled for Liblouis?

**Comment by dkager** [comment]
Seems like this issue covers it: https://github.com/liblouis/liblouis/issues/598

**Comment by Adriani90** [comment]
@dkager, @leonardder is this fixed now in NVDA 2020.1 RC1? I saw that the coresponding issue in Liblouis has been partly fixed but closed now. There might be still issues left.
Unfortunately I don't have a braille display at hand to test this.

**Comment by leonardder** [comment]
liblouis/liblouis#598 is fixed, so closing this one. If the problem persists, it needs a fix in liblouis anyway, so there's nothing we can do about it from the NVDA side.
