### ISSUE TITLE
The ability to create custom punctuation Definitions

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4016]
**Reported by mhorspool on 2014-03-23 13:37**
In the Punctuation/Symbol Pronunciation Dialog, I would like to be able to add custom punctuation definitions and modify the default ones.

This is mostly so that I can add rules for character codes that NVDA does not natively recognise.  However, the ability to customise existing definitions would be most useful.  For instance, I would like the colon to be announced when it is followed by a slash, because it is part of a URL.  However, I do not want it announced when reading times.

**Comment by leonardder** [comment]
It is already possible to add and change symbols. However, the specific behaviour to change the pronunciations based on situation as suggested above, is currently only people using regex in the symbols file itself. Personally, I belief we should keep it that way. @JCSTeh, thoughts?

**Comment by jcsteh** [comment]
You can already customise the pronunciation of existing complex symbols; e.g. ": phrase ending". Adding new ones is too risky, as they need to be regular expression fragments and they're all compiled into a single regular expression. Thus, there are any number of ways a user could break the entire symbol processor. Note that you can still add symbols with multiple characters; e.g. you could add ":/" and have it pronounced as "colon slash".
