### ISSUE TITLE
Note in the User Guide About the Update, Concerning Portable Copies

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4020]
**Reported by ateu on 2014-03-24 10:13**
Hi 

I've received some questions from the Portuguese List with respect the NVDA updates when using a portable copy.
For this reason, I suggest to be added a text about this in the User Guid.
Someting as:
Note that if you are using a portable copy, when you update, NVDA will not automatically update your copy, but just to save the updated launcher in your download folder, allowing you from there to update your portable copy or to install it.

This text is just a suggestion, but my English doesnt helps.

Thanks

**Comment by bhavyashah** [comment]
CC @jcsteh @josephsl @Qchristensen

**Comment by Qchristensen** [comment]
This could certainly be worth mentioning as a limitation of portable versions.  I'll have to think on the wording, I can't come up with anything I like tonight!
