### ISSUE TITLE
NVDA freezes when selecting text styles in microsoft word 2010

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4024]
**Reported by ashleycox on 2014-03-25 21:00**
WHen using MS Word 2010, NVDA freezes when selecting text styles using the right click context menu. TO reproduce:
Open a new document in word
Type some text
Highlight the text
Press the context menu key (or shift+f10)
Down arrow to 'styles', and right arrow to a style for example, 'heading 2'
Press return on the selected style. After "leaving menues" is spoken, try to navigate your document
You will find that navigating the document is impossible; to resume navigation, you must alt+tab away from, and then back into, the document.

**Comment by leonardder** [comment]
@ashleycox, are you the ashleycox that opened this issue? If so, could you provide a status update?

**Comment by Adriani90** [comment]
@ashleycox can you still reproduce it? Can you try to reproduce it after you disable "pages" in document formating settings of NVDA? Thanks.

**Comment by ashleycox** [comment]
@Adriani90 Afraid I no-longer have office nor a Windows installation with NVDA to test.

**Comment by ehollig** [comment]
Closing as worksforme. If someone else is experiencing this issue, please open a new issue with clear steps to reproduce
