### ISSUE TITLE
Issues navigating multi-page word documents

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4025]
**Reported by ashleycox on 2014-03-25 21:03**
When reading a multi-page word document using the down arrow key, NVDA will sometimes skip entire pages. In order to get NVDA to focus on teh desired page, you must arrow back up to the previous line of text, and use character or word reading commands to navigate to the end of the line, and then right arrow to the first character of the next page.
I've attached a word document in which this problem occurs

**Comment by bhavyashah** [comment]
I believe this issue has been reported in another ticket too, although I may be wrong. Regardless, I can confirm the reported bug in Microsoft Office Word 2010 where there aren't multiple text columns or any complications of the sort. At one point in time, this was extremely frustrating, but as Ashley stated, character navigation and word navigation does land on the next page itself, rather than skipping a page and jumping to the one after that.

**Comment by ThomasStivers** [comment]
This is not an NVDA specific issue, nor a Word 2010 specific issue. Word can display pages side by side. When Word is set to display multiple pages side by side it is logical that navigating down would move to pages on the left side. The solution is to set word to display only one page at a time. I was able to duplicate this issue in Word 2016, but I do not believe it is an NVDA issue.

**Comment by k-kolev1985** [comment]
Exactly. This can happen if the page is zoomed out enough that 2 pages can fit side by side on the screen, which is easier to occur on a wide-screen monitor and/or with higher screen resolution set. That is why I set the page zoom to "fit width". To do that while a document is opened, press F6 to go to the status bar; press TAB a few times to get to the Zoom button, which displays the zoom value as well and press ENTER on it. In the "Zoom" dialog, from the group of radio buttons, select "Page width" and press ENTER to close the dialog and apply the changes. And unless a document has a specific zoom level specified for it (I think it is possible), Word will apply the selected zoom level for all documents from now onward (in our case - "page width").

**Comment by Adriani90** [comment]
I suggest to close this issue since changing the view in the word document solves it actually. Thus, NVDA behaves correctly. This can also be seen in jaws.

**Comment by Adriani90** [comment]
cc: @ehollig

**Comment by ehollig** [comment]
Closing
