### ISSUE TITLE
Update OCR add-on

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4035]
**Reported by zahari_bgr on 2014-03-28 00:56**
The OCR addon has not been updated for a while, so there are some translations which are not added.
There could be other reasons for an update too - new version of the OCR engine, etc.

**Comment by bhavyashah** [comment]
To summarize:
* This ticket broadly concerns two issues - (1) integration of the OCR add-on into the automated translation system and (2) update to the latest version of the Tesseract OCR engine and consequently an updated OCR add-on release.
* (1) is already covered by #2744 separately.
* (2) has been addressed by @jcsteh in https://github.com/nvaccess/nvda/issues/4706#issuecomment-155330911. However, as seems to have been discussed back again in this ticket itself, the possibility of allowing users to independently select a set of languages whose recognition packages they would like to download and install very much stands.
* Therefore, if my understanding is correct and if we all agree, may we morph this issue to only suggest facilitating OCR add-on users to choose languages for which they desire up-to-date Tesseract recognition data themselves?
P.S. Would the discussed adoption of the ContentRecog framework by the OCR add-on affect this ticket in any way?
