### ISSUE TITLE
NVDA not reading offscreen text

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4037]
**Reported by ashutosh.blr on 2014-03-28 16:17**
Hi,

I am using version 2013.3 and its not reading any of the Offscreen text on a page.
Please help. Thanks.

**Comment by ehollig** [comment]
Closing, as we are unable to contact the original poster, that I am aware of, and they did not respond to @josephsl's questions in https://github.com/nvaccess/nvda/issues/4037#issuecomment-155319117
