### ISSUE TITLE
Developer Guide: Clarify how to leave scripts unbound in ScriptableObject.__gestures

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4039]
**Reported by nvdakor on 2014-03-29 02:37**
Hi,
With the addition of Input Gestures dialog in 2013.3, users can now assign, change and remove gestures (keyboard commands, braille display commands, etc.). This facility works as expected in most cases (and modules) except when a module has partial gesture assignments; that is, some scripts have gesture bindings, while others does not. This is mostly for some add-ons and future add-ons where an add-on writer may elect to leave some of the commands unassigned as they might conflict with core gestures.

Setup:
1. Create a module (a global plugin will work).
2. In the module, write a single script that does anything (I recommend writing a UI.message script), then write a **doc** method for it. Then:

A. Bind a command to this script. Restart NVDA and look at the Input Gestures dialog where you'll find the new script with your bindings.
B. Remove the script binding from the module code (to do this, use the key of None in the gestures dictionary instead of the gesture identifier). Restart NVDA, and go to Input Gestures dialog. You'll see your script with the gesture unassigned.
1. Back in the module, write a second and/or a third script that does something different, then write a **doc** method for each. Then:

A. Assign gestures for your scripts, save the module, restart NVDA and open Input Gestures dialog. Your new scripts and the commands for them are listed.
B. Remove a gesture from your script(s) with Input Gestures, then select OK. Next time you open Input Gestures, you'll see that the gestures for your other scripts are unaffected.
C. Back at Input Gestures dialog, reassign the previously removed gesture to your scripts, then select OK.
D. Now remove a gesture from your module by replacing the gesture identifier (the key to the __gestures dictionary) with None. Save the module, restart NVDA and open Input Gestures dialog.

Expected: the gestures you removed from the module code should be removed with other gestures unaffected.
Actual: the entire gesture set for your module is listed as unassigned.

To verify:
1. Open Python Console with the module with the removed gestures (from code) running.
2. Type the following:

```
import modType (either globalPlugins or appModules)
modType.modName.modType._modType__gestures
For example:
import globalPlugins
globalPlugins.testPlugin.GlobalPlugin._GlobalPlugin__gestures
```

The entry with key of None is displayed first, implying that we're dealing with an ordered dictionary. This happens no matter where the None key is found - in the beginning or in the middle.

This issue has vast consequences for current and new modules:
- Some add-ons use commands which conflicts with locale-specific gestures.ini, thus the add-on writer needs to assign unused gestures for his or her add-on (the gestures pool is decreasing).
- Some users might assume (or assume) that add-ons come with default gesture bindings; this cannot be the case for all add-ons - an add-on writer might expect users to assign custom gestures for some commands. As a result, some writers will try to leave some scripts unassigned in their add-ons.
- A possible solution to this issue will mean that current and new add-ons will require NVDA 2013.3 (or 2014.2/2014.3 or later) in order for gesture customization to be useful; also, if a solution to this problem is found and if an add-on writer wishes to produce an add-on with partial gesture set, then this will require future NVDA versions (add-on code compatibility issue is another story).
  Thanks.

**Comment by bhavyashah** [comment]
Any updates? @jcsteh @josephsl

**Comment by josephsl** [comment]
Hi, a much improved developer guide is in the works and more edits are being planned (may need to locate the one I raised a few weeks ago), and I’d like to focus my 2017.4 efforts on documentation improvements. Thanks.

**Comment by Adriani90** [comment]
@josephsl I think this is addressed in a newer developer guide version. Or not?

**Comment by josephsl** [comment]
Hi, yes, resolved in more recent dev guide. Thanks.

**Comment by Adriani90** [comment]
Ok, could you close it please? I cannot. Thanks.

 

 

Von: Joseph Lee <notifications@github.com> 
Gesendet: Sonntag, 23. Dezember 2018 23:49
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Developer Guide: Clarify how to leave scripts unbound in ScriptableObject.__gestures (#4039)

 

Hi, yes, resolved in more recent dev guide. Thanks.

**Comment by ehollig** [comment]
Closing
