### ISSUE TITLE
nvda behaves improperly in wordweb

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4048]
**Reported by JamaicanUser on 2014-04-03 18:21**
For the longest while now, while using wordweb dictionary/thesaurus, i notice that nvda keeps
1. reading text twice.
2. saying edit multi-line read-only.
3. avoiding reading the examples
4. ignoring the close and copy buttons
Support for this free application is needed.

**Comment by ehollig** [comment]
Closing because of reasoning in https://github.com/nvaccess/nvda/issues/4048#issuecomment-155319271
