### ISSUE TITLE
NVDA reads Windows 8.1 toast notifications twice when unnecessary animations disabled

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4052]
**Reported by k_kolev1985 on 2014-04-05 19:57**
I don't know why I haven't noticed this earlier, but today I've noticed it: NVDA reads toast notifications twice in Windows 8.1. I think It does not matter from witch app comes the notification: I was able to reproduce it with toast notifications from the modern Skype, the autoplay function of Windows and from the Windows Store (for a complete install of an app).

Steps to reproduce it:
1. Load NVDA.
2. Make a toast notification appear. The easiest way to do it is to insert a media witch will trigger an autoplay toast notification to appear (e.g. a CD/DVD or an USB flash drive).
3. Listen to NVDA's speech output, without interrupting it.

'''Actual results:''' NVDA reads the notification twice.

'''Expected results:''' NVDA should read the toast notification only once, since it appears only once and not twice on the screen.

'''System specifications:'''
- Windows version: Windows 8.1 Pro N, 64-bit, in bulgarian.
- NVDA version: next-10455,b3deb14, 2014.1.

**Comment by bhavyashah** [comment]
@k_kolev1985 Since this ticket is more than three years old and Windows 8.1 updates may have affected the reported issue too, could you please provide a status update by sharing whether or not this still occurs with Windows 8.1 with all recent updates installed and NVDA 2017.3? If the answer is yes, I would like to kindly request @jcsteh to share his thoughts on whether this can be fixed by NVDA itself, or feedback needs to be sent to Microsoft alerting them of this bug.

**Comment by k-kolev1985** [comment]
I only have a virtual machine with Windows 8.1 at the moment with a "next" snapshot of NVDA installed there. I can check to see if the bug is still reproducible, but it will have to wait for at least the next week, because I'll be away from my computer for the next few days.

**Comment by Adriani90** [comment]
@k-kolev1985 can you try to reproduce this issue again? Is this still an issue?

**Comment by k-kolev1985** [comment]
Oops, I forgot to do the testing last year after being away from my PC for a few days in September. My apologies. I've done the testing now and the bug is still reproducible.

**Comment by Adriani90** [comment]
@k-kolev1985 do you see this behavior also in Windows 10 or 11? I cannot reproduce this on my end in Windows 10 with NVDA 2022.4.

**Comment by k-kolev1985** [comment]
I cannot reproduce this under Windows 11 22H2 with the latest alpha snapshot of NVDA. So, I guess it affects only Windows 8.1. Since Windows 8.1 is no longer supported by Microsoft and the problem probably comes from Windows itself, we might as well close this issue/ticket.

**Comment by Adriani90** [comment]
Thanks @k-kolev1985 for the fast reply. Closing as not planed since it probably affects only Windows 8.1 which is out of support.
