### ISSUE TITLE
Useless information spoken by NVDA in some Windows 8.1 toast notifications

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4054]
**Reported by k_kolev1985 on 2014-04-06 11:24**
In Windows 8.1, in the toast notifications, NVDA sometimes reads some useless information. In some of the cases, that useless information is not even displayed on the screen.

For example, when a dialog for a device from the autoplay feature of Windows pops up, NVDA reads something like the following:

```
@AutoPlay SAMSUNG USB Flash Drive (512MB) (G:), Tap to choose what happens with removable drives.
```

The "@AutoPlay" string I think is somewhat useless and is not even displayed on the screen in the toast notification. Not only that, but if it comes from Windows itself, at least at present is not localized - even with a bulgarian language pack, it stays in english.

When we receive a chat message from someone in the modern Skype, NVDA reads something like the following from the corresponding toast notification:

```
Skype John Smith, This is a test message., 6b646b6d6173746572 Image
```

I think the "6b646b6d6173746572 Image" is related to the displayed image for the user's avatar in Skype, because the letters and digits in the string vary depending on the user from witch is the message - it is different for the different users. And since the strings tells us nothing meaningful, I suggest to suppress it in NVDA's output, if possible.

When we install an app from the Windows Store and the app's installation is completed, we get a toast notification for that. The text of the notification read by NVDA is something like this:

```
Store Speed Checker was installed.,   Image
```

Here there is an image, but it apparently does not have even a random string for its identification, so NVDA says only "image". Actually, I don't know if that "image" is from NVDA - I think that it is from Windows itself, part of the accessibility string for the toast notifications.

The "image" string at least is localized.

So, is it possible to suppress those useless strings in the toast notifications? They are in most cases a minor annoyance, but still - an annoyance (smile).

**Comment by bhavyashah** [comment]
@feerrenrut Based on @jcsteh's evaluation of the reported issue in https://github.com/nvaccess/nvda/issues/4054#issuecomment-155319314, I believe this ticket can be safely marked P4.

**Comment by feerrenrut** [comment]
The last report for the status of this issue was quite some time ago. @bhavyashah would you be able to test it again?

**Comment by Adriani90** [comment]
@k-kolev1985 could you please give us an update over this issue? Are you still experiencing this issue? For me I got used to often filter such information out of my head having the impression that I don't hear it at all. but I know what you mean. In the past there were very often such cases. Now it got much better during last years.

**Comment by k-kolev1985** [comment]
I can still reproduce this (at least with the "@autoplay" example), but it is only a minor annoyance and probably something not worth fixing from NV Access.

**Comment by Adriani90** [comment]
@k-kolev1985 I think it is hardly, if not possible at all for NVDA to customize the accessibility strings provided by the accessibility API. Fore example you find also stuff like "Dal-on" in Outlook which is used in the database for the window design in C#. I guess only Microsoft can really improve this consistently.
Could you please report this to them via Feedback hub or so?

**Comment by k-kolev1985** [comment]
@Adriani90 It is not worth it to report it to Microsoft either - they won't fix it, because they no longer develop Windows 8.1, as far as I know. We might as well just close the issue. If you can - close it - I can't.

**Comment by Adriani90** [comment]
I am closing this as won't fix. Please comment on it if you have other arguments / suggestions and we reopen the discussion. Thanks.
