### ISSUE TITLE
wrong work with calculator

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4062]
**Reported by Twinsen on 2014-04-08 02:08**
HI! im from Russia,when calculator result 1 000 000 the Nvda talk 1 000.

**Comment by ehollig** [comment]
I am experiencing the same results as @jcsteh in https://github.com/nvaccess/nvda/issues/4062#issuecomment-155319401 when ESpeak is set to Russian. Closing, but please let me know if I am wrong as I do not speak Russian.
