### ISSUE TITLE
Issues with NVDA on eBay

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4063]
**Reported by ashleycox on 2014-04-09 15:02**
Browsing eBay causes NVDA to become unresponsive. To reproduce, simply search for something on ebay.co.uk. This happens using firefox and IE (those are the 2 browsers I've tried). This is with add-ons disabled.
**Blocked by #1668**

**Comment by bhavyashah** [comment]
#1668 has already been implemented and the issues pertaining to unresponsiveness have been resolved as reported in https://github.com/nvaccess/nvda/issues/4063#issuecomment-155319407. Time to close? @ehollig

**Comment by ehollig** [comment]
Closing because of the implantation of #1668 and the issues pertaining to unresponsiveness have been resolved as reported in https://github.com/nvaccess/nvda/issues/4063#issuecomment-155319407. Closing
