### ISSUE TITLE
Blank announced in autocomplete

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4073]
**Reported by gezlemon on 2014-04-14 15:16**
When navigating through a list of items for autocomplete, NVDA occasionally announces "Blank". For example, navigating through the suggestion in the following example results in NVDA announcing blank: http://hanshillen.github.io/jqtest/#goto_autocomplete

**Comment by ehollig** [comment]
According to [MozillaBug:949518](https://bugzilla.mozilla.org/show_bug.cgi?id=949518) and https://github.com/nvaccess/nvda/issues/4149#issuecomment-155320658, this was fixed for Firefox 32.
