### ISSUE TITLE
Adobe flash W3C technique 'FLASH34: Turning off sounds that play automatically when an assistive technology is detected' not support in NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4074]
**Reported by advck1123 on 2014-04-15 07:27**
The W3C technique 'FLASH34: Turning off sounds that play automatically when an assistive technology is detected' http://www.w3.org/TR/WCAG20-TECHS/FLASH34.html

> To perform screen reader detection, Flash provides the flash.accessibility.Accessibility.active 

property. If this property is set to true, it means that the Flash player has detected running assistive technology. Based on this flag, the Flash developer can choose to run different functionality.
But NVDA is not support this technique.
Thanks.

**Comment by ehollig** [comment]
This is an interesting idea. Although, keeping in mind that flash will be discontinued in 2020, what are your thoughts @jcsteh? I am leaning toward a wontfix

**Comment by jcsteh** [comment]
Given the continuing demise of Flash, I don't think even investigating this is worthwhile. Closing.
