### ISSUE TITLE
Allowance for a character descriptions dictionary in the user config folder

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4083]
**Reported by mhorspool on 2014-04-21 01:23**
I am adding Braille Unicode to my symbols-en.dic file.  I am describing each dot patern by reading the dots which are present in the cell. I wish to press num2 twice quickly and hear the name of the braille letter/contraction etc etc.  I can do this but I must add the definitions at factory locale level.

I do not wish to do this as it is not good practice.  It also has the potential to disrupt things when upgrading.  I therefore wish to create a characterDescriptions-en.dic file in my user config directory.  I can do this, of course, but NVDA will currently not take advantage of it.

There are more generic use cases where one may wish to alter one's character descriptions.  Say, for instance, a user has learning difficulties and would prefer F to be defined as "Fred" instead of "Foxtrot".  This should absolutely be done at the user level, not the factory level - what if the user is working on a school network and his classmate has autism, and thus cannot accept the alternative phonetic representation?  This is not an exaggeration, despite how it may seem!

**Comment by bhavyashah** [comment]
It sounds like #6811 is a duplicate of this ticket. However, while this ticket was filed before #6811, there seems to be a lot of discussion there, so we may want to close this ticket to further consolidate discussion there rather than the other way round, as long as the two feature requests are the same and I am not misinterpreting, that is.

**Comment by ehollig** [comment]
Closing as duplicate of #6811. Further discussion can continue there as there has been more recent discussion.
