### ISSUE TITLE
Announce Table Cell Coordinates After the Cell's Data

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4088]
**Reported by mhorspool on 2014-04-21 01:53**
Assuming that I am using table navigation commands, and I am hearing table headers, you can assume that I already know where I am.  I just want the data, and I want it as quickly as possible.  Therefore please, please, please don't give me the cell coordinates first!  It slows me down!  You are welcome to give them to me afterwards because, if I am not interested, I will just override them with my next keystroke, no harm done there.

I am not interested in hearing them at all if I navigate with just the arrow keys because, as I said in #4087, if I am navigating with the arrows I want speed, not details.  Again, though, announcing the coordinates at the end would be less of a verbosity burden than announcing them at the start because, as I say, I can always interrupt them without sacrificing the data.

**Comment by bhavyashah** [comment]
Duplicate of #3462

**Comment by ehollig** [comment]
Duplicate of #3462
