### ISSUE TITLE
Allow appModules to force a window to use UI automation

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4102]
**Reported by mdcurran on 2014-04-29 03:07**
Currently it's possible for an appModule to force a control to not use UIA, via its isBadUIAWindow method. However, there is no way for the opposite situation. We should replace isBadUIAWindow with an isUIAWindow which can return True for yes, False for no, and None for not sure (ask the window). 
A practical usecase is the spell check field and signature field in Outlook 2013. These have suitable UIA implementations but unusable IAccessible ones.

**Comment by bhavyashah** [comment]
@feerrenrut Since labelling well-defined feature requests or proposals as feature would help in eliminating them from the triage process and allow developers to systematically access a list of them later, I think this particular ticket looks suitable to be labelled as a feature. Thoughts?

**Comment by feerrenrut** [comment]
@bhavyashah this issue does not contain a description of a user facing feature. It does however detail a "behind the scenes" change that could allow improvements in app modules.  As such, I think an enhancement label would be best for this. One thing we should try to get an understanding of, is what kind of demand there is for this change. This will help to influence when something like this will get worked on.

**Comment by bhavyashah** [comment]
@michaelDCurran In https://github.com/nvaccess/nvda/issues/4102#issuecomment-328726851, @feerrenrut states "One thing we should try to get an understanding of, is what kind of demand there is for this change. This will help to influence when something like this will get worked on." Do you have any inputs on or responses to this?

**Comment by josephsl** [comment]
Hi, I believe this is now a part of NVDA via good UIA window list. Thanks.

**Comment by Adriani90** [comment]
@michaelDCurran if you agree with @josephsl, I guess this issue can now be closed. Right?

**Comment by leonardder** [comment]
Fixed in #7961

**Comment by josephsl** [comment]
Hi,

Yes, this is an older issue that was the reason for defining appModule.isGoodUIAWindow and friends in recent releases. See #7961 for details on justifications and implementation discussion.

Thanks.
