### ISSUE TITLE
Updates attempt to run, even when not downloaded

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4116]
**Reported by briang1 on 2014-05-03 14:13**
Recently I noticed that when Sourceforge presented a bandwidth exceeded message when using the  automatic updater, nvda seemed to think it had actually download the file and tried to run it. This culminated in an error in the ms Dos 16bit subsystem, which luckily presented a graceful exit  as long as you did not hit the ignore button. Suggestion. Nvdas updater should actually check it has got the file before it is run!
Not going to break anything I don't think, but its a bug.
 I only know what the message was from sourceforge because I went to the site and looked.

**Comment by bhavyashah** [comment]
NVDA no longer uses SourceForge for hosting. Time to close? @ehollig
