### ISSUE TITLE
Bad reading some web pages

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4117]
**Reported by Twinsen on 2014-05-03 15:52**
HI!I`m from Russia. I have Windows 7 russian version ,Profession64 bit.I use standard synthesizer eSpeak,voice:Maks.  If from Mozilla go to web site: http://www.microsoft.com/ru-ru/security/default.aspx  the nvda start reading wrong. Betwin all characters I hear some sound like english character (A.)AAlso this error occurs if type in WINDOWS reference window (F1 when system focus in Desktop )"сканер отпечатков пальцев" and go to hyper link  " 
Идентификация по отпечаткам пальцев и модуль доверенной платформы"

**Comment by ehollig** [comment]
Unfortunately, this looks abandoned, and there is not enough information to reproduce.

**Comment by ProvodIII** [comment]
Hi! I`m Twinsen! I can`t login on this web site using my :Twinsen: login. I can not restore my forget password.  You web pagw don`t send me message on my email adress (Twinsen@live.ru). I don`t remember what  you web page tell me when I try restore my forget password.  We (I`m and My frend) add new user named :ProvodIII: with same (old) e-mail adress (Twinsen@live.ru). But it is not important. Please ask you system administrator: "Whats happend with My old account?" 

Now! About this issue.  You absolutly write! This  bug does not occurih if in NVDA settings  we remouve flag: "Automaticly switch languages if support" (in My NVDA settings it is write on Russian language, I translate this is). But You need know, so  this bug not happend when I press CTRL + A (select all text on web  page. And  press   SHIFT + CAPSLOOK + UP ARROW. (to read selected text). This error does not appear Now I work  using  Google Hrome browser and WINDOWS 10 Professional X64.) This issue appear on this web page. For example: first string "перейти к содержанию" , before each letter e-speak talk: "cyrylyc". (You see this string only if Google Hrome translate this page on Russian laanguage) On Englesh  lenguage this string: "Skip to content" If I use another sync (Im use full time built in Windows OneCore voices) voice:"Ирина" this error not appear)
