### ISSUE TITLE
Speech Viewer: NVDA does not provide speech feedback while focused in speech viewer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4121]
**Reported by nvdakor on 2014-05-05 23:59**
Hi,
A Korean user reports:
When I enable speech viewer and focus to it, NVDA does not provide speech feedback as to the content of the viewer. To see what NVDA speaks, I select all the viewer's content, then paste to an editor such as Notepad. Would it be possible to allow NVDA to provide speech feedback when focused in the speech viewer? Thanks.

**Comment by bhavyashah** [comment]
I believe this is no longer the case with the Speech Viewer window now made navigable/accessible. Time to close? @ehollig

**Comment by ehollig** [comment]
Closing. I am able to focus to the speech viewer using the keyboard and read the text results in the speech viewer. Is this the case you are experiencing as well @jcsteh @josephsl?
