### ISSUE TITLE
Open office for NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4141]
**Reported by Giovani on 2014-05-13 07:59**
Open office is not, I think to new version supported for NVDA. I think to part word processor of this software.
Please, could You fix It?
Thank You, Marco.

**Comment by bhavyashah** [comment]
Since we have little to no details about this ticket, and there is no way of getting back in touch with the original reporter, may we consider closing this ticket as 'Invalid' (not only because of the vagueness of this ticket but also because of Open Office's dying existence)?
