### ISSUE TITLE
Caret move not responding after input method candidate window closed

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4145]
**Reported by nishimotz on 2014-05-17 04:21**
setup:

  * Windows 8.1 Update (64bit, User Interface Language: English, enabled Japanese Microsoft IME and SAPI5 Japanese Haruka Desktop TTS)
  * NVDA 2014.2rc1 (speak typed characters: enabled, automatically report all available candidates: disabled)
  * notepad.exe

procedure:

  * start notepad application
  * type "abc" with English keyboard array. each characters are reported as typed.
  * windows+space: switch to Japanese IME
  * application key, then upper arrow key twice: if the item is "Close IME", press Escape to cancel. if it is "Open IME", press Enter.
  * type "kawa" (reported 'k', 'ka', 'w', 'wa')
  * space key (reported 'kawa')
  * space key (opened candidate window and reported second candidate)
  * enter key (second candidate is selected.): expected to announce the selected candidate 'kawa'. actually only 'candidate' is announced.
  * left arrow key or right arrow key: expected to report the character at the caret. actually nothing reported.
  * alt key twice: now left or right arrow keys work normally.

As far as we know, Braille display is also not properly updated after the open-close of candidate window (although Japanese Braille is only supported by Japanese forked version of NVDA).

Reverting api.py line 96 regarding #3873 (setFocusObject incorrectly caches container property as parent) seems to resolve the issues as far as we investigated.

**Comment by michaelDCurran** [comment]
Fix implemented as part of #4011
