### ISSUE TITLE
This ticket, is about the html views and deleting HTML items ripetition.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4154]
**Reported by lamacchia87 on 2014-05-23 10:09**
To encourage users to use the shortkut keys on the webpages, I ask if it's possible to add a tutorial mode to announcing, what item folow or preceed. For example, fif I'm to the last list item, if NVDA announce me what's next item name, I can use the related command. I ask this features because not always we can know the contents page. That can is an alternative to press the arrow keys.
Ask, inother, if it's possible, replace to the item name repetition ("out of list out of list out of list" or "out of table out of table out of table") with someting such as "Jumping (n list) or (n table)". This feature, can reduce the time to listen informations spoken.
Thanks,
Andrea

**Comment by leonardder** [comment]
Honestly, I find it a bit hard to understand what the initial reporter is trying to bring up here. Encouraging people to use quick navigation seems to be a bit out of scope from a development perspective. The out of table, out of list messages can be disabled using the document formatting dialog for elements you don't want this announcement for.

Closing as invalid, but feel free to provide additional details if you so desire.
