### ISSUE TITLE
Sometimes NVDA uses browse mode in Mozilla Thunderbird's write window

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4163]
**Reported by oaron on 2014-05-29 22:10**
Sometimes, when I press ctrl+r in mozilla Thunderbird, I can't write anything in the message box. If I press a webpage navigation key (d, f, e, etc), NVDA announces there are no ladmarks, links, etc.
Restart of NVDA solves this problem.

**Comment by ehollig** [comment]
@leonardder have you ever experienced this using Thunderbird?

**Comment by Adriani90** [comment]
@oaron can you still reproduce this issue? @novalis7747 could you try to reproduce it please? I tend to think that NVDA remembers if you activated browse mode in a message box before pressing ctrl+r.

**Comment by Adriani90** [comment]
We do not have an update from the initial author since years. I am not able to reproduce it with NVDA 2019.1.1 and Thunderbird 60. Closing as works for me. If you are still having the problem, please comment on it and we can reopen it. Thanks.
