### ISSUE TITLE
No shortcut for read-only fields in web pages

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4164]
**Reported by ABuffEr on 2014-05-30 15:23**
Hi,
as said, in NVDA there is no shortcut for read-only field/editbox in web pages, or, alternatively, shortcuts for editbox and forms doesn't intercept this controls if in read-only. Is it a precise choice, or a defect/bug?

**Comment by jcsteh** [comment]
We decided the e and f single letter navigation keys should include read-only editable text fields.

**Comment by leonardder** [comment]
> A read-only edit field has a role of ROLE_SYSTEM_TEXT, not ROLE_SYSTEM_DOCUMENT. It has STATE_SYSTEM_READONLY and IA2_STATE_EDITABLE.

It seems read only edit fields now have ROLE_EDITABLETEXT, according to my observations in Firefox.
Also note that in Chrome, a read only edit field like in [this attachment](https://github.com/nvaccess/nvda/files/350143/edit.html.txt) can be reached with e and is not identified as a read only field. However, it is not possible to input anything in the field of course.

**Comment by derekriemer** [comment]
This is probably a chromeium bug. should this be reported?


On 7/6/2016 8:58 AM, Leonard de Ruijter wrote:
>
>     A read-only edit field has a role of ROLE_SYSTEM_TEXT, not
>     ROLE_SYSTEM_DOCUMENT. It has STATE_SYSTEM_READONLY and
>     IA2_STATE_EDITABLE.
>
> It seems read only edit fields now have ROLE_EDITABLETEXT, according 
> to my observations in Firefox.
> Also note that in Chrome, a read only edit field like in this 
> attachment 
> <https://github.com/nvaccess/nvda/files/350143/edit.html.txt> can be 
> reached with e and is not identified as a read only field. However, it 
> is not possible to input anything in the field of course.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/4164#issuecomment-230799000>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AFGivT4HWu5cDC9YBP49OP3A94FU49ipks5qS8KfgaJpZM4JFrCm>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment]
You're confusing raw API roles (like ROLE_SYSTEM_TEXT) with NVDA roles (ROLE_EDITABLETEXT). You'll need to deal with the former to fix this issue because the quick nav code runs in-process.

**Comment by leonardder** [comment]
I realised Jamie, sorry for that.
In [this commit\(https://github.com/BabbageCom/nvda/commit/1b21f90c1da876aa8d1ecc08f8c12e91f9393799), we have a fix for Mozilla documents. Is this the right way to do this, or am I overlooking something? For example, does ignoring the read only state in form field navigation have any impact on elements other than edit boxes?

**Comment by jcsteh** [comment]
Haven't looked at this yet (and won't be able to until I return to work in August), but to answer your question, yes, ignoring the read only state for form fields will break things. As an example, the ul and ol tags (textual lists) are role list with read only state.

**Comment by leonardder** [comment]
Ouch, you're very true indeed. Fixed.

**Comment by leonardder** [comment]
> This is probably a chromeium bug. should this be reported?

I'm not sure:
 
* Read only field: IAccessible2 attributes: u'display:inline-block;tag:input;explicit-name:true;id:readonly;text-input-type:text;'
* Read/write field: IAccessible2 attributes: u'display:inline-block;tag:input;explicit-name:true;id:readwrite;text-input-type:text;'

In other words, it should be possible for NVDA to distinguish those, but that's something for another ticket.
