### ISSUE TITLE
Apply changes to every profile

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4167]
**Reported by kredh on 2014-06-01 09:20**
It would be great to apply a certain change of setting to every profile.  For instance, I have several profiles, but when I decide to change Braille display settings, I have to load every profile, apply it, then unload... then do it again and save NVDA settings at the end.  It would be great to just do this change once on a profile and ask NVDA to apply it to every profile.

The way to do it would be, I think, to add a new button to every setting dialog (apply to every profile).  When clicked, NVDA acts as if the "Ok" button was clicked and use the modified settings to change the settings of every profile.  Of course, it implies that if other settings in other profiles provided other information on this specific settings, these would be lost (and in this case, I don't think there's a choice, the current way is the best one).  Still, this button could be very useful in my opinion.

**Comment by Adriani90** [comment]
I agree with @bdorer and suggest closing it because changing Default configuration changes Settings for all profiles. @ehollig what do you think?

**Comment by josephsl** [comment]
Hi,

Closing as requested.
