### ISSUE TITLE
Screen review doesn't work in "modern" apps in Windows 8.1

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4171]
**Reported by k_kolev1985 on 2014-06-03 08:26**
I've noticed that screen review doesn't work correctly for reading text in "modern" apps in Windows 8.1. The commands for reviewing text instead reading the text in an object, report only "blank", as if there is no text for reviewing.

Steps to reproduce it:
1. Start NVDA.
2. Open a "modern" app in Windows 8.1 (e.g. the "Weather" one).
3. Switch NVDA to "screen review".
4. Try reviewing the text on the screen via the text review commands.

'''Actual results:''' NVDA reports only "blank".

'''Expected results:''' NVDA should be able to report the text on the screen for "modern apps in Windows 8.1.

Test environment:
- Operating system: Windows 8.1 Pro N, 64-bit.
- NVDA version: next-10666,9632e36; 2014.2.

**Comment by bhavyashah** [comment]
Modern apps in Windows 8.1 are hardly in use today in favour of UWD apps on Windows 10. Regardless, @jcsteh seems to suggest in https://github.com/nvaccess/nvda/issues/4171#issuecomment-155321016 that it may be difficult or impossible to support such screen scraping techniques consistently anyways. Thus, I suggest closing. @ehollig

**Comment by leonardder** [comment]
I agree.

**Comment by josephsl** [comment]
Hi, universal apps are, for all intents and purposes, modern apps. Because of this, the big picture applies: cannot use screen scraping reliably, although one workaround is object navigation emulation (see ObjPad add-on for details). Thanks.
