### ISSUE TITLE
NVDA send an error message if the default Braille display is not connected

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4175]
**Reported by oaron on 2014-06-05 00:02**
If I set a Braille display to default, plug out it from my computer and restart NVDA, I get this error message:
ERROR - braille.BrailleHandler.setDisplayByName (23:32:14): 
Error initializing display driver 
Traceback (most recent call last): 
  File "braille.pyc", line 1276, in setDisplayByName 
  File "brailleDisplayDrivers\freedomScientific.pyc", line 179, in **init** 
RuntimeError: No display found 
It would be better If NVDA throw an exception, or sow an alert window.

**Comment by ehollig** [comment]
Closing, as we are unable to contact the original poster, that I am aware of. Also, they did not respond to @jcsteh's request in https://github.com/nvaccess/nvda/issues/4175#issuecomment-155321058 to describe the issue in another way. I do agree that providing an alert dialog would just be annoying for users, as they are aware that their display is disconnected.
