### ISSUE TITLE
NVDA stops responding when a bluetooth audio device is connected to the computer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4178]
**Reported by k_kolev1985 on 2014-06-08 11:06**
'''Description:'''
Until recently, I was using the TOSHIBA Bluetooth Stack for my bluetooth needs (mainly for connecting my bluetooth headset and sending files to my tablet and my phone). When connecting my bluetooth headset to my computer, it was a little tricky, but not impossible, to make NVDA send its audio output to the bluetooth headset (no matter if via the A2DP or the HFP (hands-free) protocols). That - using the TOSHIBA Bluetooth Stack software.

Yesterday I've decided that the TOSHIBA Bluetooth Stack software was too heavy and too bloated for my needs and taste. So, I've uninstalled it and started using the built-in Bluetooth functionality of Windows itself. It's not bad, except for the too long automatically generated PIN codes for pairing, but I can live with that.

I've noticed however, that if the bluetooth headset is connected to the computer via both the A2DP and HFP protocols and the HFP protocol kicks in (it does specially when on a Skype call via the Skype app for Windows 8 and when in the "recording" tab of the "Sound" in the Control Panel), NVDA will stop responding: no sound comes from it and the NVDA commands stop working. As soon as the headset switches back to the A2DP protocol, NVDA starts working normally again.

I've set NVDA's logging level to "Input/Output", reproduced the issue and I'm attaching here the log file witch should hopefully contain some useful information about what's going on.

'''NOTES:'''
1. In order for the system to know when to switch to the HFP protocol, the HFP (headset) mode of the bluetooth headset is set as a default communication device in Control Panel -> Sound. The A2DP (headphones) mode is set as a default audio device in Control Panel -> Sound. Both modes appear as separate audio devices in Control Panel -> Sound.
2. Same happens with Narrator. Can't tell for other screen readers, because I don't have any of them installed.
3. The issue with NVDA occurs no matter if the output device set in the NVDA's "Synthesizer" dialog is set to the Microsoft Sound Mapper or my sound card.
4. The issue with NVDA occurs no matter if a SAPI5 synthesizer is used or the built-in eSpeak.

'''Steps to reproduce it:'''
1. Install a bluetooth headset with both A2DP and HFP protocols supported.
2. Connect it to the computer via both protocols (it's done via the "Connect" context menu command for each bluetooth playback audio device in Control Panel -> Sound). NVDA will start talking via the A2DP protocol.
3. While you're still in the "Sound" dialog, switch to the "Recording" tab. The HFP protocol will kick in. NVDA will stop talking and will not respond to commands.
4. Go to the "Playback" tab again. NVDA will resume speaking and will respond to commands again.

'''Actual results:''' When the HFP protocol is the active one, NVDA stops talking and will not respond to commands.

'''Expected results:''' NVDA should be able to work even if the HFP protocol is active and use that audio for speech output. I think NVDA would work normally if it "knows" to automatically switch its speech output to the "Headset" audio device, but it doesn't. And since it doesn't respond to commands, we can't switch the speech output device manually either. Actually, it seams that screen readers like NVDA and Narrator don't know how to output their speech to the default communication device and that is why they react like that in a situation like that. Though I might be wrong.

'''Test environment:'''
- Operating system: Windows 8.1 Pro N, 64-bit, with all updates installed.
- NVDA versions: next-10673,1813d27; 2014.2.
- Sound card: Realtek ALC888 with the latest drivers installed.

**Comment by bhavyashah** [comment]
@jcsteh's https://github.com/nvaccess/nvda/issues/4178#issuecomment-155321096 implies that someone with such a device would be in a position to investigate this bug further. Clearly, no one has stepped up with necessary prerequisites in the past three years. Additionally, Jamie very much doubts that a work-around for an issue of this kind even exists. If @k_kolev1985  does not disagree, I suggest closing as cantfix. @ehollig

**Comment by k-kolev1985** [comment]
Since this is not a bug in NVDA itself and a workaround from NVDA is probably not possible, I agree that the issue should be closed. I've sent a feedback to Microsoft about this via the Feedback Hub, which can be found here: [https://aka.ms/bknmwh](url). I don't know if that way the issue will get to the right people at Microsoft and if they will do something about the issue, but that is the only way that I know of to report bugs to Microsoft. Well, actually, there is another way via some sort of forums for reporting bugs and sending ideas and I might use that channel as well. 😀

**Comment by ehollig** [comment]
As this is not an issue with NVDA and an appropriate bug has been filed with Microsoft, closing as requested in https://github.com/nvaccess/nvda/issues/4178#issuecomment-325209817
