### ISSUE TITLE
nvda sometimes won't focus in firefox windows

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4180]
**Reported by mayson on 2014-06-08 19:42**
Nvda will sometimes say mozilla firefox start page edit has auto complete, or it will say nothing at all

**Comment by leonardder** [comment]
@mayson: If you are the mayson who opened this issue, could you tell whether this is still an issue for you? If so, it would help if you could provide more details (e.g. steps to reproduce, version of Firefox, version of NVDA, version of Windows)

**Comment by leonardder** [comment]
Closing as invalid due to lack of recent information and steps to reproduce,
