### ISSUE TITLE
NVDA Makes Firefox Crash

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4181]
**Reported by netblue on 2014-06-09 15:46**
When letting NVDA, sit idally on a web page for mor than five minits, or sumtimes just letting NVDA,  read with say all firefox completely freazes.
I have tried restarting NVDA, but to noe avail. The only solution is to restart firefox.
See atached file.

INFO - **main** (03:48:10):
Starting NVDA
INFO - core.main (03:48:10):
Config dir: C:\Users\ZelvinWilson\AppData\Roaming\nvda
INFO - core.main (03:48:10):
NVDA version 2014.2
INFO - core.main (03:48:10):
Using Windows version sys.getwindowsversion(major=6, minor=1, build=7601, platform=2, service_pack='Service Pack 1')
INFO - core.main (03:48:10):
Using Python version 2.7.6 (default, Nov 10 2013, 19:24:18) [v.1500 32 bit (Intel)](MSC)
INFO - core.main (03:48:10):
Using comtypes version 0.6.2
INFO - external:synthDrivers.eloquence.SynthDriver.**init** (03:48:10):
Using Eloquence version 6.1.0.0
INFO - synthDriverHandler.setSynth (03:48:10):
Loaded synthDriver eloquence
INFO - core.main (03:48:10):
Using wx version 2.8.12.1 (msw-unicode)
INFO - braille.initialize (03:48:10):
Using liblouis version 2.5.3
INFO - braille.BrailleHandler.setDisplayByName (03:48:10):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - brailleInput.initialize (03:48:10):
Braille input initialized
INFO - core.main (03:48:11):
NVDA initialized
ERROR - NVDAObjects.behaviors.Dynamic_IAccessibleWinConsoleWindowNVDAObject._monitor (07:41:01):
Error getting initial lines
Traceback (most recent call last):
  File "NVDAObjects\behaviors.pyo", line 247, in _monitor
  File "NVDAObjects\window\winConsole.pyo", line 48, in _getTextLines
  File "winConsoleHandler.pyo", line 121, in getConsoleVisibleLines
  File "wincon.pyo", line 70, in GetConsoleScreenBufferInfo
WindowsError: [6](Error) Controlador no válido.

**Comment by ehollig** [comment]
I do not experience the described problem using the latest NVDA Master. It does not appear the original author has answered @jcsteh's questions in https://github.com/nvaccess/nvda/issues/4181#issuecomment-155321108 which would make this harder to replicate. Any thoughts?

**Comment by leonardder** [comment]
It is probably quite hard to track down the initial author anyway. Closing as invalid, since @JCSTeh clearly asked for more information which hasn't been provided.
