### ISSUE TITLE
NVDA support for sheduling events in Zara Radio 1.6.2

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4183]
**Reported by dr-who-1 on 2014-06-09 18:41**
I am an internet broadcaster who uses nvda to access computers, I use Zara radio 1.6.2 as my radio automation program and I have not been able to schedule events in Zara radio. The program is mainly accessible and I would really appreciate if event scheduling could be made accessible with nvda.  There does not appear to be any way of accessing the events dialog box using nvda.  Also when attempting to create a jingle, nvda does not appear to read the buttons correctly. If it would not be possible then is there a better alternative that would work well with nvda and is preferably free?

**Comment by ehollig** [comment]
Closing because of https://github.com/nvaccess/nvda/issues/4183#issuecomment-155321115
