### ISSUE TITLE
support for fl studio

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4196]
**Reported by mayson on 2014-06-14 11:33**
I would like to see accessibility support in nvda for the fl studio music production software. I am currently going in to music production, And I gratly need to use this piece of software.

**Comment by Adriani90** [comment]
@mayson could you please give us an update regarding fl studio? Is it now somehow usable with NVDA? What exactly are the main issues with this application when using NVDA?

**Comment by Adriani90** [comment]
We do not have any updates from the initial author since more than 5 years. Please open new issues for specific problems in this music production software and we can continue discussions on those issues. Thanks. I am closing this for now.
