### ISSUE TITLE
Adding new features in poedit modules.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4205]
**Reported by dhankuta on 2014-06-18 08:04**
In poEdit module, To indicate the category of the messages, a beeping  feature is adopted. However, it does not indicate the exact state of the message. Whether it is untranslated, fuzzy or if translated but contains the same text as in original message (sometimes it happens by an accidental human slip!).
Let there be a different tone for:
1. unstranslated message.
2. Fuzzy message.
3. Translated as a simply copied  original message.
4. Properly translated (no beep for this)
I suggest the changes and the made patch is as follows:

```
def event_gainFocus(self):
    super(sysListView32.ListItem, self).event_gainFocus()
    name1 = super(PoeditListItem,self)._getColumnContent(1) #The original message
    name2 = super(PoeditListItem,self)._getColumnContent(2) # The translated message.
    if self.isBold:
        if name2 is None: # Untranslated.
            tones.beep(700, 50)
        else: # Fuzzy message.
            tones.beep(500, 50)
    elif name1 == name2 # Same text in both  panes.
        tones.beep(300, 50)
```

**Comment by bhavyashah** [comment]
Him Prasad Sir did work on the Poedit Made Easy NVDA add-on which may be worth considering for inclusion in the community add-ons portal or integration in core itself, if it still holds relevance for the latest version of Poedit. If it doesn't work, unfortunately, Him Prasad Gautam AKA dhankuta  is no more with us to continue work on the Poedit app module.

**Comment by josephsl** [comment]
Hi, no, I’d say we close this and reopen if a new maintainer is found. Thanks.

**Comment by ehollig** [comment]
Closing, as suggested by @josephsl in https://github.com/nvaccess/nvda/issues/4205#issuecomment-325149255. This can be reopened, or a new issue can be created, if a new maintainer is found.
