### ISSUE TITLE
Add a way to bind a keyboard shortcut with manual profile activation/deactivation

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4209]
**Reported by kredh on 2014-06-20 09:53**
It would be great to be able to manually activate/deactivate configuration profiles (those who are  configured for manual activation) with a keystroke that could be entered by the user.  This feature could be added to the configuration profile dialog box (perhaps a button only accessible for profiles configured for manual activation).

If the profile is not activate, the keystroke activate it.  Otherwise it deactivate it.  It remains pretty simple and would allow more speed while switching between manual profiles.

**Comment by jcsteh** [comment]
P3 because this would be a massive efficiency boost for some use cases; e.g. #6882.

**Comment by leonardder** [comment]
For reference, here is an alternative approach I came up with in #7058:

> Add an extra option to each profile which adds the profile to a list which can be cycled through using an input gesture (NVDA+shift+p) by default

Personally, I prefer the first approach though. @jcsteh: How would you like this to be implemented?

**Comment by devil418** [comment]
What's the current status of this issue? Is anyone working on it?

**Comment by Qchristensen** [comment]
Of those two options, I agree the first one is arguably more useful and easier to understand.  My question is where did NVDA+i come from? My immediate thought is that I can't relate why the letter "i" for profiles, except that it is one of not many NVDA+letter assignments that are free.

My other thought was that you could use something like NVDA+control+number, and that way you could assign shortcuts to ten profiles.  I'm sure as soon as I say "no-one will need more than that" someone will throw out a use case, but it does give a sequence of options which the user can set as they prefer.  I would suggest NVDA+control+1 activates the chosen profile then the same keystroke again to deactivate it, or if you press say NVDA+control+2 it would activate that profile.

I realised after I'd written this that NVDA+control+numbers are used by both Skype and Miranda, so maybe NVDA+shift+number?

Or as someone suggested earlier, NVDA+shift+p and either have it a toggle for one profile, or a cycle through any number as elected by the user?

**Comment by leonardder** [comment]
> My question is where did NVDA+i come from? 

Honestly, it is completely random.

> My other thought was that you could use something like NVDA+control+number, and that way you could assign shortcuts to ten profiles. I'm sure as soon as I say "no-one will need more than that" someone will throw out a use case, but it does give a sequence of options which the user can set as they prefer. I would suggest NVDA+control+1 activates the chosen profile then the same keystroke again to deactivate it, or if you press say NVDA+control+2 it would activate that profile.

Personally, I'd prefer having the author choose this. Like:

1. IN the input gestures dialog, have a separate category "configuration profile activation"
2. For every profile, dynamically add an entry to the list for the profile, leaving it unbound by default.
3. Optionally have people assign a gesture right from the configuration profiles dialog, without requiring them to open the input gestures dialog.

**Comment by kara-louise** [comment]
I love this feature, but, I think currently the switching message is a bit verbose. I suggest rather than saying "Configuration profile Web manually activated" for example, say "web manually activated". Or just "web activated".

**Comment by feerrenrut** [comment]
> the switching message is a bit verbose.

I think it could easily be confusing to someone who is not very familiar with what is going on. Though I agree that the name of the configuration profile should come first, an experienced user can then silence their synth. What about `{name} profile activated` and `{name} profile deactivated`

**Comment by kara-louise** [comment]
> What about `{name} profile activated` and `{name} profile deactivated`

Yes, That'd work.

Apologies if This appears twice as reply via e-mail doesn't seem to be working.
