### ISSUE TITLE
Nvda and reading text

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4220]
**Reported by khsruru on 2014-06-24 14:50**
Hello, I’m Hyongsop Kim in Korea.
I have a suggestion about Nvda’s reading and mouse pointer.
In case of low vision users, they use mouse very much as you know.
And when I watch them, they want screen reader reas the text from their mouse pointer.
For example in web page, there is a very long document.
They want to read with screen reader because the text is very long.
But they are mouse user, it is too bothersome or hard to focus from browse mode cursor to text that they want to read with keyboard.
So if Nvda supports read from mouse pointer, it will be very easy for them.
Please add this function.
Thank you.

**Comment by leonardder** [comment]
@khsbory: What you could do is the following:

1. Place the mouse where you want to start reading
2. Press nvda+shift+n (laptop lay-out) or NVDA+numpad multiply (desktop layout)
3. Press NVDA+shift+a (laptop layout) or numpad plus (desktop layout)

Would that be an option for you?

**Comment by khsbory** [comment]
Wow, thank you for your advice.
 
My colleague is low vision, he is really want to know the way how to read from the mouse pointer.
I let him know the way and he wants to appreciate to you.


Thank you.
 
김 형 섭	 / Hyongsop Kim
(주)엔비전스 / 웹접근성사업팀 팀장	

서울시 종로구 가회동 1-29 
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 70 4900 0895   F. +82 2 313 3645   M. +82 10 5359 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark

 
 
-----Original Message-----

**Comment by ehollig** [comment]
Sounds like from https://github.com/nvaccess/nvda/issues/4220#issuecomment-320627423 that this issue has been resolved. Closing
