### ISSUE TITLE
In MICROSOFT excel: executing event: typedCharacter on <NVDAObjects.window.excel.ExcelCell object at 0x0835D9F0> with extra args of {'ch': u'\x1a'}

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4224]
**Reported by advck1123 on 2014-06-26 06:49**
I'am using Excel 2007.
Str:
1. Open excel then open my attache file.
2. Open context menu: insert... dialog.
3. Press ok button.
4. Press Control+z.

My error log:
ERROR - eventHandler.executeEvent (15:35:50):
error executing event: typedCharacter on <NVDAObjects.window.excel.ExcelCell object at 0x0835D9F0> with extra args of {'ch': u'\x1a'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in **init**
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects__init__.pyc", line 809, in event_typedCharacter
  File "speech.pyc", line 538, in speakTypedCharacters
  File "api.pyc", line 242, in isTypingProtected
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\window\excel.pyc", line 533, in _get_states
  File "comtypesMonkeyPatches.pyc", line 32, in new__getattr__
  File "comtypes\client\lazybind.pyc", line 149, in **getattr**
  File "comtypes\automation.pyc", line 664, in _invoke
COMError: (-2146827864, None, (None, None, None, 0, None))

**Comment by bhavyashah** [comment]
The following is a sequential list of things that need to be done to make progress on this ticket:
1. Restore the attachment in https://github.com/nvaccess/nvda/issues/4224#issuecomment-155321476
2. Test for the reported error in various versions of Excel so as to ascertain its current standing the scope of its applicability
3. Check whether the reported error affects user expeerience directly in terms of feature deficiency or performance slowdown, so as to understand if this is a relatively unimportant internal error that NVDA generates or if it impacts the average user noticeably
CC @feerrenrut and @ehollig to help out with Step 1

**Comment by ehollig** [comment]
File added to https://github.com/nvaccess/nvda/issues/4224#issuecomment-155321476. Also, performing the above steps in Excel 2016 does give the error described in the original post.

**Comment by Adriani90** [comment]
I am testing in Word 2010 on Windows 8.1 with NVDA 2018.4. I cannot reproduce this issue. @advck1123 are you able to reproduce it with last Version of NVDA?

**Comment by dnz3d4c** [comment]
Adriani90 This is the user who previously used the advck1123 id.
I will take the time to test this issue.

**Comment by Adriani90** [comment]
@dnz3d4c did you find some time to test if the issue is still occuring? Thanks.

**Comment by Adriani90** [comment]
I cannot reproduce this issue with NVDA alpha-17134,363af94b and Excel 2010 or 2016 / 365. I am closing this as works for me. If you are still having this problem, please comment on it and we can reopen the discussion.
