### ISSUE TITLE
Nvda throwing errors in Outlook passwords fields, inable to read them

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4227]
**Reported by leonarddr on 2014-06-27 08:20**
Although this issue should have been fixed according to #4090 and #3832, i still get com errors in password fields.
Steps to reproduce: Open the accounts manager by pressing alt+f,i,s,a. Select an acount and choose Change. I attached a log file containing the error

**Comment by leonardder** [comment]
I can't reproduce this any more. Feel free to close this. I can't do it myself since this is a pre2015 issue
