### ISSUE TITLE
report line spacing in ms word

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4237]
**Reported by JamaicanUser on 2014-06-30 21:08**
When using Microsoft Word, NVDA should report whether the file is in single or double line spacing, 1.5 line spacing etc. This ay be a duplicate. Also, NVDA should anouncd speak font size changes with the keystroke, nvda+</>.

**Comment by leonardder** [comment]
This seems to be a duplicate of #2961 and has already been fixed
