### ISSUE TITLE
nvda repeating file names

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4243]
**Reported by JamaicanUser on 2014-07-02 19:06**
I don't normally use Windows 7, but in the latest snapshot, when I was about to download something from Firefox, Windows Explorer appeared, and file names were reported twice.

**Comment by JamaicanUser** [comment]
As the person that initially reported this, I can confirm that this issue has long been resolved.

**Comment by ehollig** [comment]
Thanks for the update. Closing
