### ISSUE TITLE
NVDA/Program: Not Responding When Attaching A File

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4245]
**Reported by iamjett27 on 2014-07-03 08:14**
I’m having this issue with my NVDA. When I want to attach a file in my outlook, web mail or any application, and when I’m already on the file that I want to attach, the application will not be responding or suddenly the browser will crash. And after a few minutes, it will return to normal.

**Comment by bhavyashah** [comment]
Not only is the reported issue quite vague but also the original author of this ticket is now out-of-reach and unfortunately did not respond to https://github.com/nvaccess/nvda/issues/4245#issuecomment-155321658 and https://github.com/nvaccess/nvda/issues/4245#issuecomment-155321659. Thus, I suggest closing. @ehollig

**Comment by ehollig** [comment]
Closing do to lack of information to replicate.
