### ISSUE TITLE
Nvda and mark tag in html5.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4247]
**Reported by khsruru on 2014-07-03 15:21**
Hi, I’m Hyongsop Kim in Korea.
I have a question about Nvda and html5 mark tag.
As you know, the mark tag is used to mark some text and sighted person sees as if the pen is marked.
But Nvda doesn’t support mark tag.
So I thought how to support it.
Verbal method is that inform too much information.
So how about using sound?
It is to inform that start and end of the mark with different sound as if browse mode and focus mode sound.
As a reference, I attached a short html file that used with two marks.

Thank you.

**Comment by jscharett** [comment]
Any updates?  Would love to see support for this if possible.

**Comment by jcsteh** [comment]
This would require changes in the various browsers. For Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=982125

**Comment by Adriani90** [comment]
The part with Sound could be achieved once speech refactoring has been implemented. So also might be blocked by #8877

**Comment by josephsl** [comment]
Hi,

Not that one - #4877 is the speech refactor issue. Thanks.

**Comment by ehollig** [comment]
Now that [Mozilla Bug 982125](https://bugzilla.mozilla.org/show_bug.cgi?id=982125) and #4877 is resolved, this may  be possible, in Firefox at least.

**Comment by Adriani90** [comment]
cc: @feerrenrut

**Comment by CyrilleB79** [comment]
Could anyone remove blocked and blocked:needexternalfix labels?

**Comment by Adriani90** [comment]
Closing as fixed by #12892 and #11436.
The part to have this indicated by a sound is a different feature request which should be filled separately with the new feature request template, explaining also why this should only be added to mark tags.
