### ISSUE TITLE
Windows Store apps: use app title as product name instead of wwahost

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4259]
**Reported by nvdakor on 2014-07-07 13:10**
Hi,
Currently, when invoking appModule.productName for a Windows Store app, NVDA says "Windows operating system". Although this is fine for built-in apps such as Bing Weather and Windows Store, this may confuse users and developers when they are testing accessibility of Store apps (both existing ones and apps to be created in the future). As a way of providing actual product name for debugging purposes and for people to tell us which app they are having issues with, I propose using app title for productName.
Before:
1. Go to Windows Store app such as Weather.
2. Once the app opens, press NVDA+F1 to show developer info. Look under appModule.productName.
After:
1. Open any Windows Store app.
2. Press NVDA+F1 to open developer info. appModule.productName tells you the title of the app.
Implementation:
1. In appModules.wwahost.py, override _get_productName to return the title (api.getForegroundObject().name).
2. wwahost.AppModule.productName will contain the actual title of the app.
Thanks.

**Blocked by #4569**

**Comment by leonardder** [comment]
cc @josephsl

**Comment by josephsl** [comment]
Hi, hopefully we should do something about it, as there are folks still using Windows 8.x and they might encounter hoste3d apps. Thanks.

**Comment by Adriani90** [comment]
@josephsl, @michaelDCurran, @jcsteh any update on this issue? I think the priority for Windows 8 store apps is quite low. in favour o0f Windows 10. Right?

**Comment by Adriani90** [comment]
Is this issue occuring also on Windows 10?

**Comment by josephsl** [comment]
Hi,

Not by much, as most apps do come with their own executables (including converted desktop apps). I'm leaving this open in case we can find a solution for wwahost issue. Thanks.

**Comment by josephsl** [comment]
Hi,

And I found one: kernel32::GetPackageFullName. This function returns a serialized representation of an app package info, including name, version, architecture, and family. Each part is separated by an underscore, which makes it easy to parse this (index 0 is publisher.name, index 1 is version).

I'll come up with a pull request in the next few hours.

Thanks.

**Comment by josephsl** [comment]
Hi,

Update: #10114 will resolve this through a more generic version as part of base app module, as this issue also extends to universal aps and converted desktop apps, too.

Thanks.
