### ISSUE TITLE
Occasional loss of focus (unknown) on web pages in Chrome/Chromium

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4260]
**Reported by domasofan on 2014-07-09 06:47**
Hi all,

Just noticed some issues with NVDA and Chrome/Chromium in both daily builds.
1. braille seems to hang when you are going through the page. in firefox it does that successfully and follows speech but in chrome/chromium it seems to do that for a while but decides to stop. I can reproduce it all the time but it is inconsistent but its pretty obvious. this also seems to happen in stable versions as well.
2. dialogs seem not to react in chrome. for example when you have a install dialog for a extension you can't give focus to it when hitting enter on it. this seems to be something i discovered a while now. both in stable chrome and nvda versions this can be found.
3. i don't know what this is but there seems to be also an issue when loading pages. for example the google search. when you are on google and you enter something and hit enter then it seems the search results don't show up. though you can tab to the links of the search results. so it seems that nvda doesn't get the data or something.

chrome/chromium: 38.0.2085.0 (daily build)
NVDA: Next-10818 (daily build)
OS: Win XP 32 bit, Win 7 64 bit

greetings,
simon

**Comment by leonardder** [comment]
@domasofan: Could you please provide a status update for this issue?

**Comment by Adriani90** [comment]
I think this is also related to #8389. I think there are some dlls which have to be registered but no idea which. Maybe we can get a list of accessibility API related dlls from Microsoft?

**Comment by Adriani90** [comment]
@domasofan are you still available for testing? Otherwise I suggest closing this issue because it covers multiple issues and for loosing Focus, freezing pages and so on are also other issues open. If @domasofan is not available anymore I think we should Close this and reopen it if he or someone else reports this issue again. Thanks.

**Comment by Adriani90** [comment]
I am closing this one for now. Please comment on it if you still have this problem and we can reopen the discussion. Thanks!
