### ISSUE TITLE
Speakers/HP Volume % is not announced when slider is edited

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4269]
**Reported by blindbhavya on 2014-07-12 08:49**
To reproduce this perform the following:
1 Press Windows + b to go to the System Tray.
2 Arrow to the Speakers/HP button and prepress Enter.
3 Press the up or down slider to adjust the system volume.
4 NVDA (using ESpeak's latest development version here) will not say anything, only the Windows sound will be heard. Only when the NVDA read current line command is given will the current volume be announced after editing.
I restarted NVDA and rechecked thissue and it persisted. After restarting NVDA and immediately changing the volume I checked the log viewer for some information of my doings that I could attach here but only information about NVDA initialization was present.
Please fix the above.

**Comment by ehollig** [comment]
@bhavyashah are you still able to replicate this? I am not able to using Windows 10. I wonder if this has to do with the manufacturers volume control versus Microsoft's Volume control.

**Comment by ehollig** [comment]
Thank you @bhavyashah. Closing as requested in https://github.com/nvaccess/nvda/issues/4269#issuecomment-413288706
