### ISSUE TITLE
Text is not always read in a text field for a Java application (depends on cursor placement).

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#427]
**Reported by nkovach on 2009-09-24 15:03**
In a Java Application using Java Access Bridge.

When there is text is a text field and the user tabs out of the field then back to the field, NVDA reports the text differently depending on where the cursor is located.  When the cursor is located at the end of the text the field is reported by NVDA as ‘blank’.  When the cursor is located at the beginning of the text the field is reported correctly by NVDA as having text and the correct text is read to the user.

It would be better if any text in the text field was reported when the text field receives focus.  This is especially true if the text field it not editable.

**Comment by leonardder** [comment]
Unfortunately, since the initial reporter didn't name the JAVA application he used when experiencing this, it is hard to say whether this has already been fixed. I don't recall such issues when using java apps.

**Comment by jcsteh** [comment]
I can't reproduce this in text fields in Java Control Panel. Closing as worksforme.
