### ISSUE TITLE
reporting of e-mail address of sender beside his or her name in GMail Basic HTML View

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4270]
**Reported by blindbhavya on 2014-07-12 08:53**
Do the following to reproduce this :
1 Register or log into GMail and change your view to Basic HTML.
2 Open any conversation and go to end of document (Ctrl + End) and then Shift + h (go to previous heading i.e. last message sender name).
Assuming that reporting of tables is disabled then NVDA will only say heading no. sender's name. You have to right arrow to read the e-mail address.
I propose that the e-mail address should be presented on the next line. JAWS presents it in that manner and I would like NVDA to do the same.
P.S. Sorry for the comparison but just want needed features to come into NVDA as well.

**Comment by bhavyashah** [comment]
I can confirm that this issue still persists.

**Comment by Adriani90** [comment]
Actually, this can be by partly solved by adjusting the characters per line (in this case 40 would split the name and the email address in two lines). But this is not a long term solution unless profiles in NVDA can be created for specific websites.

**Comment by Adriani90** [comment]
Given the low impact of this issue and the workaround described above, I am closing this issue.
