### ISSUE TITLE
inability to remember the e-mail last viewed when user presses Alt + left arrow to go back to the Inbox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4271]
**Reported by blindbhavya on 2014-07-12 11:38**
I am using Mozilla Firefox 30 and versions of other applications are given.
To reproduce perform the following:
Note : This issue occurs 90% of times but somehow 10% it works nicely. Also, this issue is not there with JAWS so shouldn't be with NVDA as well. Sorry again for comparison with JAWS but I really am liking NVDA and want all JAWS pros to come into NVDA.
1 Register or log into GMail and change your view into Basic HTML.
2 Navigate to and Open any conversation.
3 Press Alt + left arrow (back command) to go to your Inbox (or any other label/folder).
Result : You will most probably reach the start of the Inbox or maybe the edit field. I would like NVDA to remember the last e-mail viewed and directly jump to the cell of the e-mail (third column) so that the user can  easily view the subject and some parts of the next or previous e-mail.
Again I say that this problem is not consistent and sometimes somehow NVDA remembers the position.
Someone once said that GMail changed very frequently so it was impossible for NVDA to achieve this, but then I ask how does JAWS remember always?

**Comment by Adriani90** [comment]
@mltony Dows your last pull request solve this issue? If yes, maybe we should reference this issue in it as well. Thanks.

**Comment by Adriani90** [comment]
@bhavyashah I guess you can still reproduce this issue. Right?

**Comment by Adriani90** [comment]
I cannot reproduce this issue either with NVDA 2019.1.1. I am closing as works for me, given also that we didn't hear anything from Bhavya. I you are still having this problem, please comment on it and we can reopen the discussion. Thanks!
