### ISSUE TITLE
GMail cell containing subject and initial part of the message in the messages table.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4272]
**Reported by blindbhavya on 2014-07-12 11:43**
I am using Firefox 30.
Note : This happens always with NVDA and never with JAWS.
To reproduce this :
Register or log into GMail and change into Basic HTML view.
Press t on the Inbox page and you will land onto a the table which has all the messages.
On pressing Ctrl Alt right arrow once you reach the cell with the sender's name. Press down arrow and you will hear half of the cell I described. Press down arrow again and the second part of the cell will be read.
I propose that NVDNVDA should display that cell as one part only and not two.

**Comment by fisher729** [comment]
I have seen Narrator read the link as if it were one line using Microsoft Edge.

**Comment by jcsteh** [comment]
I'm not able to look into this at the moment. I don't have any prior knowledge here, so anyone should be able to test this. It might be easiest if someone with some sight could take a look, but it might also be possible to figure out from the HTML/DOM.

**Comment by ehollig** [comment]
I just had a look at this in basic HTML. I noticed, in the HTML and visually, (with what little vision I have) that the message in the table appears on one line. You can also tell by changing the Maximum characters on one line in the Browse mode settings to 200 or even 300. To test this for yourself:

1. Press NVDA+CTRL+B and change the maximum characters on one line to 200.
2. Login to Gmail Basic HTML
3. Press T to go to the first table on the page.
4. Press CTRL+Alt+Right arrow to go to column 3
5. Notice that the entire message preview is read on one line.
6. Change the maximum characters on one line to 100, or whatever you previously had it set to and perform the above steps again.

I am closing as worksforme, but please let me know if I am of error.

**Comment by bhavyashah** [comment]
@ehollig You are right. Thanks for doing the needful.
