### ISSUE TITLE
Firefox goes blank when an application is closed and focus goes onto it

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4276]
**Reported by blindbhavya on 2014-07-12 12:55**
Supposing I have opened an application and Firefox and I close that application and my focus goes onto Firefox it goes blank. I try press Tab but nothing happens.
 I have to press Windows M and then Alt Tab to get control over Firefox again.
Why does Firefox go blank? Why cant NVDA let me interact with it?
Is this an NVDA issue?
I hope the steps to reproduce this issue are comprehensible by the above info.

**Comment by ehollig** [comment]
Has anyone experienced this lately with Firefox? If not, I may suggest a close as worksforme

**Comment by feerrenrut** [comment]
This is an old issue, that describes an issue that does not seem to have been reproduced or properly understood. If someone can reproduce similar behaviour as described here, it would be clearer to open a new issue.
