### ISSUE TITLE
Elements list dialog box improvements

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4279]
**Reported by blindbhavya on 2014-07-12 14:00**
In this ticket I will mention all the improvements that can be made in the Elements list dialog box.
1. ability to filter other elements
Currently only three or four Internet elements can be shown in the Type option in the Elements list dialog box. All other common and uncommon elements should be available in that Type grouping option.
2 User should be able to use Ctrl Home & Ctrl End in the list of selected elements.
3 The Type grouping option should have the elements in form of check boxes, so that two or more elements can be included in one list.
Hope these features will be added.

**Comment by bhavyashah** [comment]
I have no justification to back my suggested improvements. Also, @leonardder is already working on adding some more elements to the Elements List dialog. The only concern I still have, which may be more of an enquiry that too, is why Level 0 is spoken for links in the Elements List dialog. As long as someone can clarify whether that is a valid bug or intended information, I am happy for this to be closed.
@jcsteh Never mind the brutally straightforward and somewhat non-cooperative 12-year-old me you met as blindbhavya. :)

**Comment by jcsteh** [comment]
The level 0 weirdness is covered by #7142. Additional elements list types are covered by #6131. Given that this addresses all outstanding issues here, closing as duplicate.
