### ISSUE TITLE
NVDA reports hierarchy of components in Java application

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#428]
**Reported by nkovach on 2009-09-24 15:06**
In a Java application using the Java Access Bridge: NVDA reports more information about the state of the object.  For example, when a JOptionPane is displayed, NVDA reports “RootPane, LayeredPane, OptionPane”.  It is not necessary to report the first two.  Only the last really matters.  This is just an example it also happens with other components.

**Comment by leonardder** [comment]
Looking at the NVDA code, I think this has already been fixed but this issue is still open. We recently fixed it for split panes as well (#7063)

**Comment by jcsteh** [comment]
Yes, this is fixed. Thanks.
