### ISSUE TITLE
need to include indic brailles by an update braille module.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4283]
**Reported by dhankuta on 2014-07-12 14:29**
Hi,
The list of language for braille enlisted in louis/tables and the list of the languages of available braille as shown in braille setting dialog do not match. The setting dialog laps to show about dozens of languages specially of indic origin. Please update it as the tables available in include/liblouis/table!

**Comment by Adriani90** [comment]
I do not see any Response from @dhankuta. @dhankuta if you have any tables which you want to be included and of which you certainly know that they are valid, please reply as @jcsteh proposed above. Otherwise I suggest to Close this issue.

**Comment by josephsl** [comment]
Hi,

That's because @dhankuta has gone on to the other world (deceased). I'm closing this because of this and also because his request was fulfilled not long after.

Thanks.
