### ISSUE TITLE
Eclipse bug in package explorer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4286]
**Reported by oaron on 2014-07-13 04:59**
In Eclipse, when I navigate in Package explorer, NVDA doesn't the selected item announce (Eclipse bug 315339). But on braille display and under the review cursor, the correct text appears. Is it possible to wrewrite the Eclipse script to announce text which is under the review cursor in package explorer?

**Comment by dkager** [comment]
Assuming the reported problem is that speech doesn't announce the selected package when arrowing up/down.
Can't reproduce with Eclipse Neon.
