### ISSUE TITLE
Facilitate control of the cursor position iwhen editing files

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4293]
**Reported by leidner on 2014-07-14 16:14**
To be able to control the layout of a text by the blind user it is very important to be able to control the cursor position (particularly the distance from the left edge) either in pixel or mm. A keyboard shortcut should be provided to ask NVDA for the cursor position easily.

**Comment by dkager** [comment]
What is being requested here? NVDA can already report the current character and show the cursor position in braille.

If the request is to report the physical position of the cursor, then I wonder about the use case.

**Comment by derekriemer** [comment]
Reporting the location in pixels from the left edge I think. IMHO this has limited use cases, because pixels are small, and people who haven't had vission won't easily know how far things should be placed in. Also, we report indent and formatting in word processing apps now.

**Comment by dkager** [comment]
Leaning toward wontfix.

**Comment by leonardder** [comment]
Agreed.

@leidner: Are you the leidner who opened this issue? If so, could you provide additional info about why you think this is necessary and current level of functionality in NVDA isn't enough for you?

**Comment by leonardder** [comment]
Closing for now, but still open to additional feedback if desired.
