### ISSUE TITLE
Tighten top level client check in NVDAObjects.IAccessible.isPresentableFocusAncestor

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4300]
**Reported by jteh on 2014-07-17 04:19**
Google Chrome exposes ROLE_SYSTEM_CLIENT for some of its accessibles which don't have their own HWND. This seems odd given the name CLIENT, but MSDN is much less specific:
 Microsoft Active Accessibility uses this role as a default if there is a question about the role of a UI element.

We can tighten this by using IAccessibleIdentity to check for OBJID_CLIENT, CHILDID_SELF.

This will prevent extraneous reporting of two panes when focusing Google Chrome.

**Comment by jcsteh** [comment]
We decided to use event_objectID/event_childID rather than IAccessibleIdentity, as root object doesn't theoretically require IAccIdentity.
