### ISSUE TITLE
when switching languages in Windows 8.x, NVDA moves focus away from the app and/or plays error tone with COM error recorded in the log

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4302]
**Reported by nvdakor on 2014-07-17 06:13**
Hi,
Another possible regression with recent next branch commits (haven't tested in master yet):
When switching languages in Windows 8.x (Windows+SPACE), NVDA does either one of the following:
- Moves focus away from the app.
- Plays error tone with COM error recorded in the log.

STR:
1. Install one or more keyboard layouts for different languages (say, English and Spanish; I use English and Korean).
2. Open any app and press Windows+SPACE to switch languages.
Expected: NVDA leaves focus alone and announces new active language.
Actual: NvDA moves focus away from the app and/or COM error is recorded in the log.

In case of the first problem, the relevant console session is as follows:

```
Before: User is focused on Outlook's Inbox window.
Enter Python Console.
Input: focus.appModule
Output: <'outlook' (appName u'outlook', process ID 5524) at address 45863d0>
Input: focus
Output: <appModules.outlook.SuperGridClient2010 object at 0x049E65D0>
User presses Windows+SPACE, then enters the console:
Input: focus.appModule
Output: <'explorer' (appName u'explorer', process ID 1780) at address 47d6190>
Input: focus
Output: <NVDAObjects.UIA.UIA object at 0x049E6930>
```

For the second problem, the traceback is as follows:

```
Input: kb(desktop):windows+space
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (23:10:19):
COM pointer <POINTER(IAccessible) ptr=0x735013c at 49c4800> already deleted
IO - speech.speak (23:10:19):
Speaking [u'pane']
ERROR - eventHandler.executeEvent (23:10:19):
error executing event: gainFocus on <NVDAObjects.UIA.UIA object at 0x049E7850> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\User\AppData\Roaming\nvda\globalPlugins\enhancedTouchGestures.py", line 38, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "appModules\explorer.pyc", line 218, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 862, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 806, in reportFocus
  File "speech.pyc", line 321, in speakObject
  File "speech.pyc", line 239, in speakObjectProperties
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 534, in _get_columnNumber
COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
```

My suspicion is that it might be something to do with IAccessible focus event problem that one or more ticket commit fixes. Thanks.

**Blocking #4347**

**Comment by ehollig** [comment]
This sounds similar to #2707 and are probably related.

**Comment by Adriani90** [comment]
@josephsl, @bhavyashah is this issue still reproducible?

**Comment by josephsl** [comment]
Hi,

It may have been resolved in a recent NVDA release, as focus is moved back to the app you were working on. For now, it shall be closed - please feel free to reopen and mention me if someone can reproduce this on 8, 8.1, and various iterations of 10.

Thanks,
