### ISSUE TITLE
Donation Page Should Be Translated

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4307]
**Reported by ateu on 2014-07-18 10:18**
Hi dear Developers,

In last days, I've received several requests from the Portuguese list about the donation page. Many people are interested in making a donation, but unfortunately, it's not possible to them to make this, as they don't speak English. I'm sure not only in Brazil, but in all the world, there are people that aren't able to make a donation due to the same reason, so I think this really should be a priority.

**Comment by ehollig** [comment]
Closing as Duplicate of #6392, as it has recent comments.
