### ISSUE TITLE
Wordweb : Incorrect control type being announced by NVDA in word definitions

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4314]
**Reported by blindbhavya on 2014-07-19 08:05**
To understand and reproduce this issue kindly download and install Wordweb, which is a freeware.
Type the word in the edit box and press Tab twice.
Pressing Tab twice gets you to the place where you can read the meanings of the word typed.
When you press the second Tab, NVDA should say 'Wordweb property page pause edit multiline read only'.
I don't think property page is required and what does property page signify anyway? Why is edit multiline said? This is by no mean a place to edit anything, just to read, nothing to edit.
Hope I was clear.

**Comment by ehollig** [comment]
Closing, as a request to improve the accessibility of this software has been sent to the developers.
