### ISSUE TITLE
in the Start Menu when focus is on the search box and user presses up arrow to go to All Programs, NVDA says blank All Programs (and all the information with it)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4317]
**Reported by blindbhavya on 2014-07-19 08:33**
Steps to reproduce
Press Ctrl + Esc to launch the Start Menu.
Your focus will be on the search box.
Press up arrow to go to All Programs.
NVDA will say blank all programs.
So, NVDA should not say blank.

**Comment by leonardder** [comment]
cc @bhavyashah

**Comment by leonardder** [comment]
Giving this p4, since although it is annoying, it is not at all live threatening and probably not very trivial to fix.

**Comment by Adriani90** [comment]
@bhavyashah can you still reproduce the issue?

**Comment by lukaszgo1** [comment]
Still reproducible on Windows 7.
