### ISSUE TITLE
Buffers not Being Completely Loaded in Some Pages When Using Recent Compilations of Chrome

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4318]
**Reported by ateu on 2014-07-19 12:59**
Steps to reproduce:
1. Using Chrome 38, ( dev or canary channel can be used) open facebook.com or the Google search page;
2. When NVDA announces the page title, try to navigate through the page with arrow keys or using the quick navigation keys;

Expected result: The page should be completely loaded.
Current result: In most cases, just a small part of the page is loaded, and is necessary to press NVDA+f5 to refresh the buffer. For example, in Facebook, the posts aren't showed, and in google.com, the search results aren't showed.
I think this is a problem in NVDA, as I have tested using other screen readers and this doesn't occurs.
**Blocking #4566, #4657, #4836**

**Comment by jcsteh** [comment]
Chromium issue 425861 was fixed some time ago. Issue 425885 is still open.

**Comment by ehollig** [comment]
[Chromium issue 425885](https://bugs.chromium.org/p/chromium/issues/detail?id=425885) has been archived. Is this still an issue for users? All other Chrome issues seem to be resolved.

**Comment by Adriani90** [comment]
@ateu is this still reproducible? I am using Chrome 71 and cannot reproduce this issue with NVDA 2018.4.

**Comment by Adriani90** [comment]
Closing as works for me. If it is still reproducible, please feel free to comment and we will reopen it. Thanks.
