### ISSUE TITLE
Indication of focusmode erratic when  new page loaded

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4328]
**Reported by briang1 on 2014-07-26 12:47**
It seems for some time now that the sound or focus mode  depending on the selected warning, does  not occur when the new page has it focus directly on the edit area. It is very hit and miss.
Also on this very page it happened, and so its not that unusual.
Mostly noticed on searche engines such as https://startpage.com

Its a minor irritation but sometimes you can be caught out when you type and the mode is not focus mode when you thought it should have been.

**Comment by Adriani90** [comment]
@Brian1Gaff are you still available?

**Comment by Adriani90** [comment]
This is not reproducible in NVDA 2019.1.1 and Firefox 66.0.3 or Chrome 74. In IE, focus mode is often not automatically enabled when system focus changes. But it is properly working if system cursor changes. So if you enable both checkboxes in NVDA menu / browse mode settings, everything works well also in IE. I am closing this as works for me. Please comment on it if it is still an issue for you and we can reopen the discussion. Thanks!
