### ISSUE TITLE
Java Access Bridge: Support function and additional keys in key bindings

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4345]
**Reported by jteh on 2014-07-31 06:45**
I was notified about this privately.

```
I wanted to let you know that we've added support for F keys and
controls keys to Java accelerators.

Bit 8 of the modifier indicates an F key and the F key number (1 - 24)
is in the character.

Bit 9 indicates a control key and the control key is in the character. 
Supported are the following:

            case KeyEvent.VK_BACK_SPACE:
            case KeyEvent.VK_DELETE:
            case KeyEvent.VK_DOWN:
            case KeyEvent.VK_END:
            case KeyEvent.VK_HOME:
            case KeyEvent.VK_INSERT:
            case KeyEvent.VK_KP_DOWN:
            case KeyEvent.VK_KP_LEFT:
            case KeyEvent.VK_KP_RIGHT:
            case KeyEvent.VK_KP_UP:
            case KeyEvent.VK_LEFT:
            case KeyEvent.VK_PAGE_DOWN:
            case KeyEvent.VK_PAGE_UP:
            case KeyEvent.VK_RIGHT:
            case KeyEvent.VK_UP:

This will be in 7ux, 8u40, and 9.
```
- Bit 8 is 1 << 8; i.e. counting bits from 0.
- There are no constants for these yet, but they'll probably be named ACCESSIBLE_FKEY_KEYSTROKE and ACCESSIBLE_CONTROLKEY_KEYSTROKE.
- There's a test case attached to [this bug](https://bugs.openjdk.java.net/browse/JDK-8028241).
- The VK_\* constants can be found [here](http://docs.oracle.com/javase/7/docs/api/constant-values.html#java.awt.event.KeyEvent.CHAR_UNDEFINED).

**Comment by leonardder** [comment]
CC @JCSTeh

**Comment by jcsteh** [comment]
P4 because we haven't had any requests for apps that actually depend on this. Happy to consider raising that priority if there are use cases, though.

**Comment by jcsteh** [comment]
Closing as duplicate of #6081, as that issue provides a use case and a PR.
