### ISSUE TITLE
combining three modifier key selection check boxes into one combo box

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4357]
**Reported by blindbhavya on 2014-08-02 17:13**
In the Keyboard Settings dialog box, there are three check boxes for the use of the Caps lock key, Num pad Insert and extended Insert key as the NVDA modifier key.
Is it possible that instead of those three check boxes there is one combo box with three options, Caps lock, Num Pad insert, extended insert?
Also somehow, it should be possible that within the combo box user can chosse more than one of the given keys as modifiers.

**Comment by bhavyashah** [comment]
@jcsteh (Mr. James Teh again, please comment. :D) Unless you, @leonardder, @feerrenrut and others believe that an accessible dropdown with checkable items can be implemented with WX Python, I am happy for this ticket to be closed.

**Comment by derekriemer** [comment]
Ping to https://github.com/nvaccess/nvda/pull/7491
