### ISSUE TITLE
conversion of all NVDA reference documents for e.g. License under Help submenu

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4359]
**Reported by blindbhavya on 2014-08-02 17:25**
Hi.
I feel that everything should be universalized.
So, the License found under the Help submenu and all other such files should be converted into HTML files such as the User Guide and all other documentation files.
Note : My previous ticket should not be closed because of this because it mentioned another request as well, while this ticket only deals with the request to convert all documents into HTML files.

**Comment by bhavyashah** [comment]
@jcsteh Please excuse https://github.com/nvaccess/nvda/issues/4359#issuecomment-155324454 and feel free to close this ticket. @ehollig

**Comment by ehollig** [comment]
As requested in https://github.com/nvaccess/nvda/issues/4359#issuecomment-319597008
