### ISSUE TITLE
avast antivirus tray icon is unresponsive

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4362]
**Reported by enes on 2014-08-03 08:32**
hi,
avast antivirus is fairly usable with self defense disabled
however a new issue has popped up with version 9
when moving to the tray icon of avast in the system tray the icon's right-click menu isn't accessible with the applications key and a second after moving to the icon nvda says unknown 
this is the case even with self defense enabled or disabled
and disabling the animate the icon when scanning setting in avast does not resolve the issue

**Comment by ehollig** [comment]
Closing because of https://github.com/nvaccess/nvda/issues/4362#issuecomment-155324594
