### ISSUE TITLE
double announcement of clock icon in the system tray

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4364]
**Reported by blindbhavya on 2014-08-03 11:24**
Steps to reproduce
Press Windows + B to go to the System Tray.
Press left arrow (on my machine a single left arrow is enough but maybe on other machines navigating to the cock icon may differ).
Actual Result = clock cock other information
Expected Result = clock other information
Why does NVDA read clock clock twice?

**Comment by bhavyashah** [comment]
@derekriemer NVDA is leaving support for Windows XP. Not version 2014.2 though, but 2017.4. :)
@dkager Would you like to be assigned this ticket?
If not, @feerrenrut, should we mark this as a P3/P4?

**Comment by dkager** [comment]
Which operating systems does this affect? Not Win10 and probably not Win8.1 either.

**Comment by bhavyashah** [comment]
Based on the ticket body and some of my own testing coupled with your assertion that this does not affect Windows 10, below is a compilation of how the Clock icon fairs on different Windows versions:
* Windows 7 - clock clock {time}
* Windows 8.1 - 22:30, ‎Tuesday, ‎05-‎09-‎2017  clock  22:30, ‎Tuesday, ‎05-‎0
* Windows 10 - All is well.

**Comment by dkager** [comment]
Someone can probably get the fix from my "RTL marks" PR. I removed it from there because it wasn't related to the issue at hand, but it's still in the commit history.

**Comment by feerrenrut** [comment]
I think @dkager is referring to this commit: 92931317ec6c7a1260fc6ca61b6060ad092707cb. Anyone who wishes to look into fixing this issue, should consider how they will have it tested across the various versions of windows, and report the results of this testing in the PR. Given the availability of a reference implementation, I will label this with `goodfornewdev`
