### ISSUE TITLE
WINDOWS 8.1

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4365]
**Reported by fionadt on 2014-08-03 13:17**
I  put nvda the latest version on my thinkpad 8 tablet yesterday which runs 8.1 and it froze the tablet. nIn the  end i had to uninstall it. I would greatly appreciate any advice you can give . I'm  sending this so hopefully  my experience  can be passed on to others and avoid what happened to me. I want to use nvda with adobe digital editions so it can read to me but i'm finding it very difficult.

Fiona

**Comment by ehollig** [comment]
Unfortunately, there is not enough information provided from the author of this ticket and we have no way in contacting the original author. Closing as invalid
