### ISSUE TITLE
When in M-S-word 2010 the alinement isnt isn't spoken when pressing insert-f to read the formatting

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4380]
**Reported by johnythehess on 2014-08-11 20:15**
After I center a page and press insert-f I hear the font but not weather the page is centered.

**Comment by bhavyashah** [comment]
I was certainly one of those who was flummoxed in my early days with NVDA when things like NVDA+. and NVDA+F (laptop keyboard layout) reported in the context of the character focused by screen review. However, I don't think I follow @jcsteh in terms of the proposed NVDA+F configurability. Could you please shed some more light on this and morph this ticket accordingly?

**Comment by jcsteh** [comment]
On further thought, I think making this configurable would just make things more confusing as you say. Closing as won't fix.
