### ISSUE TITLE
Some edit fields in firefox don't show their contents in a consistant manner.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4381]
**Reported by driemer.riemer@... on 2014-08-11 21:41**
A good website to test this with is [w3schools.com](www.w3schools.com). On this site, if you click any of the examples, and try moving around in the editor with your html code, you hear unexpected results. This also happens in the editor window for tickets, which makes me think this happens in any multiline edit field.
Take this line for an example.
<!DOCTYPE html>
Sounds random when moved through with the arrows.
It one time may sound like <DDDTPMLL 
And another time may sound like !OCTYYEhtml 

This happens when moving by words as well. 
This behavior is noticeable with regular English as well and is very prevalent on my machine on most websites. 

It also happens when moving by line, and makes using multiline edit fields with nvda very hard if not impossibl with firefoxe. 
**Blocking #4412**

**Comment by jcsteh** [comment]
There may still be some rare instances of this, but the regression that caused this to be filed has been fixed.
