### ISSUE TITLE
Mouse Tracking Not always speaking Accurately

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4385]
**Reported by jessean1 on 2014-08-12 16:54**
I am a low vision user, and like to use a screen reader like NVDA or System Access with windows magnifier.  I often like to view frequently visited web pages that don’t have a lot of Headings and other mark-up by using mouse navigation and the Mouse Tracking feature of NVDA.  
The problem I’m encountering is that NVDA seems to keep reading the whole body of the page, or text that isn’t actually under my mouse.  I have tried the mouse mode set to both line and paragraph.  

Here’s an example.  

Go to www.applevis.com .  

There are a couple of main sections in the body of the page.  Under the “Welcome to AppleVis” heading, there are 3 paragraphs.  Then there’s a “Getting Started…” heading with several paragraphs and bulleted lists underneath it.  

I believe NVDA used to read just the paragraph the mouse pointer was over.  So I could hover my mouse over each one of the 3 paragraphs under the Welcome section, and only have that paragraph read aloud, not the whole section starting from the top each time.  Each visual paragraph break would be its own paragraph or line, and NVDA would read just that area.  

Now NVDA seems to read much larger chunks of text, and not necessarily what’s under the mouse.  This is very confusing as a low vision user.  In fact, I can move my mouse over the column in yellow on the right, titled The Hot List, and it still reads the main left column of that page.  It seems very difficult, often impossible, to navigate some screens and web pages via the mouse hover feature.  

Is there a way to make NVDA’s mouse read feature read more of what’s actually under the mouse?  Maybe I need to be in a different review mode or something?  

For an example of how I thought this feature used to work, try the same above experiment using System Access To Go: www.satogo.com .  I can hover my mouse under each individual paragraph and only that paragraph, heading, or link will read aloud.

**Comment by leonardder** [comment]
Anyone with some sight who can reproduce? CC @QChristensen

**Comment by Qchristensen** [comment]
The original poster didn't mention which browser they were using, but trying with the latest versions of the four browsers on Windows 10:

- Internet Explorer and Edge both work as expected
- Chrome is still being flakey for me with mouse tracking so I couldn't get any reliable data.
- Firefox seems to be stuck reading by line rather than paragraph, even when definitely explicitly set to paragraph.

So definitely still mouse tracking issues, though slightly different to the original description.

**Comment by ehollig** [comment]
Sounds like another case of #5344 and other issues, if there are additional duplicates of this issue

**Comment by Adriani90** [comment]
@Qchristensen, @jessean1 could you please try to reproduce it with NVDA 2018.4? Is it still reproducible?

**Comment by josephsl** [comment]
Hi,

Or, for that matter, is this fixed for all in 2018.4/alpha? Thanks.

**Comment by Qchristensen** [comment]
Using 2018.4.1, I get the same results as [previously](https://github.com/nvaccess/nvda/issues/4385#issuecomment-316030861), that is, Chrome does not do mouse tracking at all reliably, and Firefox works fairly well set to character, word or line, but seems to treat paragraph the same as line.

There are still issues with links in the middle of paragraphs, as per https://github.com/nvaccess/nvda/issues/3590 but that aside, the main issue for me here was Firefox treating mouse tracking as being set to line when it is set to paragraph.

**Comment by Adriani90** [comment]
it Seems this describes similar behavior like #9442 and #10847. I think enabling cancellable speech on focus events after focus event xpired in NVDA advanced settings should solve this issue. @Qchristensen can you confirm?

**Comment by Qchristensen** [comment]
Just trying now, it doesn't seem to matter "Attempt to cancel speech for expired focus events" is enabled or not, NVDA will read the current paragraph for me as I hover over it with the mouse.  However, if the paragraph contains links, it will only read up to the link

**Comment by hwf1324** [comment]
@Qchristensen, are you describing the situation as described in this [comment](https://github.com/nvaccess/nvda/issues/15397#issuecomment-1718029623)?

**Comment by Qchristensen** [comment]
@hwf1324 Re stopping at links, yes like that comment (and pretty sure there are several issues for it) - what I more meant was that I'm not getting the original behaviour described in this issue - of reading the entire page rather than just the paragraph under the mouse.

**Comment by hwf1324** [comment]
@Qchristensen, it seems that we can now close this issue unless the original problem cannot be reproduced with an earlier version of NVDA

**Comment by seanbudd** [comment]
Closing as there are other issues surrounding mouse tracking which are more specific
