### ISSUE TITLE
Firefox and IE (but not Chrome) "remember" last tab order even after hard refresh, but only with NVDA running.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4386]
**Reported by digitaltoast on 2014-08-13 12:33**
I'm trying to test my page for accessibility and after a LONG night of extensive testing and head meeting desk, I can safely say the following is happening on a Win 8.1 machine in IE and Firefox:

Open a page, tab to a certain link, refresh the page, tab again and it seems that something about NVDA is interfering with the tab order. I THINK this guy is having the same issues: http://stackoverflow.com/questions/22517242/how-to-prevent-nvda-setting-focus-automatically-on-last-used-html-element but other users weren't "getting" it, so no answer came.

I've even found some workarounds involving re-focussing to the top of the page via javascript and document ready, and if I set up some CSS to highlight current elements, I can see my page top element being focussed on, and then after a split second, the damn focus is back on the same element before I refreshed the page.

If I turn NVDA off, this strange behaviour doesn't occur. 

There's always a possibility there's some bizarre NVDA setting I've accidentally switched on, but I can't find it to switch it off.

**Comment by ehollig** [comment]
Can someone clerify what exactly is the bug or issue discussed here? It sounds like, from https://github.com/nvaccess/nvda/issues/4386#issuecomment-155325616 that the original poster got his questions answered. CC @jcsteh

**Comment by derekriemer** [comment]
I'll work on the mozilla case if I get time.

**Comment by rileyL6122428** [comment]
I believe my team is facing the same issue. Turning off NVDA restores the correct behavior in Firefox. Is there a way to toggle off the feature causing this bug while NVDA is running in order to to confirm?

**Comment by Adriani90** [comment]
is this maybe because browse mode is enabled and Focus moves if automatic reading of Webpage is enabled? @rileyL6122428, @digitaltoast if you disable automatically read the web page after the page is loaded in NVDA Settings under browse mode, is then the issue still reproducible?

**Comment by Adriani90** [comment]
cc: @jcsteh, @MarcoZehe

**Comment by Adriani90** [comment]
cc: @leonardder

**Comment by Adriani90** [comment]
Closing this one as duplicate and in favor of #3575.
