### ISSUE TITLE
VLC Media Player 2.15 (latest stable version) issue: in Preferences dialog for the first two options NVDA says thrice and four times respectively the word 'pane'

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4397]
**Reported by blindbhavya on 2014-08-16 16:37**
Steps to reproduce
Download and install and launch VLC Media Player (2.15 latest stable version recommended).
Under Tools find and hit Enter on Preferences.
Press Tab.
Expected Result : NVDA should normally read out whatever options are there.
Actual Result : NVDA for the first option says pane pane pane (thrice) and then reads out some option.
The next Tab will make you land on something which NVDA calls pane pane pane pane (four times).
Please investigate into this matter and see if this can be resolved.

**Comment by bhavyashah** [comment]
The reported issue is not occurring with VLC Media Player version 2.2.3, though I don't feel too inclined to close this ticket and open a new one. The described behaviour has been resolved (probably by a VLC update and UI change), but here's an absurd issue that exists now.
STR
* Open VLC Media Player.
* Press Ctrl+P to open the Preferences dialog.
Expected Result: NVDA should report the dialog name and the new control (setting or option) under focus, and maybe something else related to the category or type of option at most.
Actual Result: NVDA utters a ton of gibberish which has been retrieved from the Speech Viewer and pasted below:
Simple Preferences  dialog  Interface Settings
Show media change popup: <html><head><meta name="qrichtext" content="1" /><style type="text/css"> p, li { white-space: pre-wrap; } </style></head><body style=" font-family:'Sans Serif'; font-style:normal; text-decoration:none;"><p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Show a notification popup with the artist and track name when the current playlist item changes, when VLC is minimized or hidden.</p></body></html>
File extensions association
Show settings  grouping  Show settings
Simple  radio button  checked  Switch to simple preferences view
@josephsl Could you please test this at your end?

**Comment by Adriani90** [comment]
@bhavyashah are you still able to reproduce it? @nvdaes, @josephsl are you maybe available for testing as well? Thanks.

**Comment by josephsl** [comment]
Hi,

Let's close this one, as we already have an add-on for VLC and changes were made to VLC in recent years.

Thanks.
