### ISSUE TITLE
New Espeak voices

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4400]
**Reported by briang1 on 2014-08-19 07:22**
It has been mentioned to me more than once that the Quincy voice is too quiet on some machines, and so I have done a new version which is considerably louder at normal volume settings.
 Care needs to be taken of course not to overload the audio systems in laptops or rattle the speakers. 
**Blocking #5061**

**Comment by fisher729** [comment]
@jcsteh, perhaps this issue should be closed, as some of these voices have been included in eSpeak NG, and, based on feedback I got for raising a similar issue, submitting this to the devs of eSpeak NG would be the better solution.

**Comment by jcsteh** [comment]
Closing as per previous comment.
