### ISSUE TITLE
This control will leave the edit mode in firefox.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4415]
**Reported by vgjh2005 on 2014-08-25 03:03**
There is a control that cannot enter edit mode automatically. If switch it manually, press arror key will announce useless info.
There are log:
Developer info for navigator object:
name: None
role: ROLE_SECTION
states: STATE_EDITABLE
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionMozillaIAccessible object at 0x05A9D770>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionMozillaIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (251, 401, 729, 21)
value: None
appModule: <'firefox' (appName u'firefox', process ID 2396) at address 5977630>
appModule.productName: u'Firefox'
appModule.productVersion: u'31.0'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 656710L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 4896
windowText: u'\u521b\u5efa\u7f3a\u9677-QQ2014-TAPD\u5e73\u53f0 - Mozilla Firefox'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x9db3844 at 5a9b580>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=656710, objectID=-4, childID=-485432784
IAccessible accName: None
IAccessible accRole: u'div'
IAccessible accState:  (0)
IAccessible accDescription: u''
IAccessible accValue: None
IAccessible2 windowHandle: 656710
IAccessible2 uniqueID: -485432784
IAccessible2 role: IA2_ROLE_SECTION
IAccessible2 states: IA2_STATE_SELECTABLE_TEXT, IA2_STATE_OPAQUE, IA2_STATE_EDITABLE (5128)
IAccessible2 attributes: u'margin-left:0px;text-align:start;text-indent:0px;formatting:block;margin-right:0px;tag:div;margin-top:0px;margin-bottom:0px;display:block;'

**Comment by Adriani90** [comment]
@vgjh2005 are you still able to reproduce it?

**Comment by josephsl** [comment]
Hi,

Preferably with Firefox 52 and higher? Thanks.

**Comment by Adriani90** [comment]
Closing as requested by the author.
