### ISSUE TITLE
Touch gestures: introduce arrows/navigation mode to simulate pressing arrow keys via flick gestures

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4443]
**Reported by nvdakor on 2014-09-06 01:52**
Hi,
There are certain situations where trying to accomplish something via object navigation may fail on touchscreens. For example, when trying to change languages in general settings dialog, one needs to use physical arrow keys or remember to click expand button. Thus I propose introduction of a mode to allow flicks to emulate pressing physical arrow keys.

Example situation: A user wishes to change keyboard layout.
Scenario 1: when using the keyboard, the user would open NVDA's keyboard settings dialog, then use physical arrow keys to change keyboard layout between desktop and laptop.
Scenario 2: in order to change keyboard layout using touchscreens, one needs to move inside the combo box control until one lands at expand button. Double-tap, move down the object hierarchy (one finger flick down in object mode) in order to land in a list of keyboard layouts. When one wishes to move onto other controls in keyboard settings dialog with touchscreens, one cannot simply move among objects and would resort to using TAB key to move to other settings, or locate the other controls by exploring the screen.
Scenario 3: with the arrows/navigation mode implemented, a touchscreen user would switch to arrows mode and use up and down finger flicks to select the desired keyboard layout.

Implementation strategies:
1. Introduce an arrows/navigation mode in touch handler module that'll allow touch gestures to emulate arrow keys. This is similar to how some braille displays emulate arrows using braille commands.
2. A user would switch to this mode using the existing mode switch command (three finger single tap). By default, NVDA should start in object mode like previous releases.
3. Either in touch handler or in global commands, add arrows/navigation layout flag for finger flick gestures.
The commands in arrows mode would be as follows:
- One finger flick left/right/up/down: left, right, up and down arrows.
- Two finger flick left/right/up/down: control+arrow keys.

Possible concerns:
- Some may ask, "doesn't NVDA support touch keyboard and can the touch arrow keys be used instead?" Yes, which requires the user remember how to activate touch keyboard (located on the bottom of the screen between taskbar and notification area) and the location of the touch arrow keys. The new arrows mode would simplify this approach, in that the commands can be executed from virtually anywhere.
- Doesn't some braille displays emulate arrow keys using their braille keyboards? Yes, and the new touch arrows mode would utilize this functionality but implemented in a different module.
- Some would also ask for functionality to let touch gestures emulate TAB key. This should be discussed on another ticket, as this ticket is meant to talk about emulating just the arrow keys.

Thanks.

**Comment by leonardder** [comment]
@josephsl: any recent thoughts about this issue?

**Comment by Adriani90** [comment]
how about integrating and improving the quicknav addon from Tuukka and assigning touch gestures to its functions?

[QuickNav](https://github.com/tuukkao/nvda-quicknav)

**Comment by josephsl** [comment]
Hi,

2024 update: while I still have touchscreen computers, I don't have any thoughts on emulated arrow keys mode (consider the idea abandoned at this stage). Closing as abandoned. Thanks.
