### ISSUE TITLE
Thunderbird: make expanded and collapsed on braille displays shorter

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4444]
**Reported by driemer.riemer@... on 2014-09-07 21:53**
When in a tree view, the word collapsed takes up a lot of space. 
I would suggest making an arrow on the display that points towards the left, or right to signify whether the tree view is expanded or collapsed.

so treeview that has a collapsed item might look like  this in dev info (this is an email in thunderbird.
name: u'Collapsed   Read: notes for systems.  (redacted name)  100 3:23 PM'
role: ROLE_TREEVIEWITEM
states: STATE_COLLAPSED, STATE_FOCUSABLE, STATE_FOCUSED, STATE_SELECTED, STATE_SELECTABLE

If the state says collapsed, show {3l on the braille display, which looks like a leftward arrow.
If the state is expanded, show _3o on the braille display, so it is a rightwards pointing arrow.

**Comment by ehollig** [comment]
Thanks to René in [this message](https://nvda.groups.io/g/nvda/message/49700), it sounds as if this has been changed in Thunderbird. Closing
