### ISSUE TITLE
Nvda crashed in cygwin.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4455]
**Reported by driemer.riemer@... on 2014-09-14 10:41**
I have verry little details besides the dump. I know that in the log, which unfortunately got erased by another nvda-old.log, there was the text 
"error accessing memory at address " blablalablabla "permition denied."

It had something to do with braille. 

I am not sure, but it could be related to this traceback I found a couple of days ago and need to report. 
That will be in the next ticket.

**Comment by ehollig** [comment]
@jcsteh, should this be closed as you said in https://github.com/nvaccess/nvda/issues/4455#issuecomment-155327398 that you ca not do anything with this dump?

**Comment by jcsteh** [comment]
This was possibly related to #4457, which has since been fixed. Regardless, we can't do anything with this dump. Closing as works for me, since it can't be reproduced now.
