### ISSUE TITLE
Driver installation error: Failed to extract the installer for FSBrlDriver64.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4464]
**Reported by surfer0627 on 2014-09-16 20:43**
In the operating system windows 7 (64bit), I installed FocusBlueDriver1.0.2030 for PAC Mate, and got error message:
Failed to extract the installer for FSBrlDriver64.

Then I try to install jaws (15.0.11024ENU-64bit.exe).

After that, braille display could show message:
pm display 20  3.70

If I open jaws, and the display could work on.

But I could not find and select freedomScientific in the braille settings.

I got message from NVDA log file:
Braille display driver freedomScientific reports as unavailable.

**Comment by leonardder** [comment]
Honestly, I think that documenting system requirements for a driver is the responsibility of the driver vendor, Freedom Scientific. Unless @jcsteh still feels we should document this, I lean towards closing this.

**Comment by jcsteh** [comment]
You're absolutely right that the responsibility of documenting this should rest with the vendor. However, as with many things, it doesn't matter whose responsibility it is if users keep coming to us with the problem. In the absence of the right people taking responsibility, we want to reduce the support load on NV Access and our community, and if including a sentence in our User Guide can do that, it's a small price to pay. :)

**Comment by leonardder** [comment]
note to @bramd: please let the github magic close this issue when you've been able to finish your fs native driver.
