### ISSUE TITLE
Trigger pull of addonFiles repo and sync of crontab via push web hook

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4466]
**Reported by jteh on 2014-09-18 04:56**
We're currently pulling the addonFiles repo and syncing the crontab from that repo in an hourly cron job. It'd be better if we could trigger it using the [Bitbucket POST hook](https://confluence.atlassian.com/display/BITBUCKET/POST+hook+management).
1. If get.php is updated, just pull the repo.
2. If automatic.crontab is updated, pull the repo and sync the crontab.
3. Otherwise, do nothing.

**Comment by leonardder** [comment]
@JCSTeh: This seems to be a bit outdated, correct?

**Comment by jcsteh** [comment]
Still valid. Probably should be moved into the nvaccess/l10n-code GitHub project at some point, though.

**Comment by Adriani90** [comment]
@michaelDCurran, @feerrenrut your thoughts are also very apreciated here. Thanks.

**Comment by feerrenrut** [comment]
Given that many of these processes are getting looked at, it's unlikely that the specifics of this issue are going to remain valid. I'm going to close this issue.
