### ISSUE TITLE
Upgrade to ConfigObj 5.x.y

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4470]
**Reported by nvdakor on 2014-09-19 20:51**
Hi,
As of NVDA 2014.3, ConfigObj 4.7.2 is used to retrieve, manage and store preferences. Now that a new version of ConfigObj has been released in 2014, I propose upgrading to ConfigObj 5.x.y (preferably 5.0.6, released in August 2014).
By upgrading to ConfigObj 5.x.y, NVDA users and developers will be able to:
- Save config files in folders with non-ASCII names.
- Provide easier way to upgrade NVDA's core code to Python 3.x, as ConfigObj 5.x.y supports Python 3.x. This means one less package to worry about when upgrading NVDA core to Python 3, if this ever happens.
- ConfigObj now uses Git for version control. This means we can try Git submodule from within misc deps submodule to retrieve latest ConfigObj releases. The Github page for ConfigObj is: https://github.com/DiffSK/configobj
  Thanks.

**Comment by josephsl** [comment]
Hi,

See #7105 and #7429 for updated justifications. Thanks.

**Comment by leonardder** [comment]
I've attempted an update to version 5.0.6, but it broke my config. Seems like there have been some changes that need to be addressed first.

**Comment by leonardder** [comment]
Yuck, I just discovered that #7945 adds configobj 5.1.0dev while still using the old configobj under the hood. I will fix this in a new pr. There's no need to revert the old pr, though, since it actually doesn't break anything.
