### ISSUE TITLE
Moving by word broken in Python Console output control when line starts with a space

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4473]
**Reported by vgjh2005 on 2014-09-21 01:51**
Hi:
type "help(file)"in python console, press nvda+4 to jump to the content EditBox. Press numpad9 to find " |  file(name[mode[, buffering](,)]) -> file object". Press numpad6 to read by word continually.
Thanks!

**Comment by bhavyashah** [comment]
@jcsteh wrote in https://github.com/nvaccess/nvda/issues/4473#issuecomment-155327795 "Oddly, this doesn't happen in Wordpad, which seems to use the same control." It might be worth investigating this discrepency so as to better track down the cause of the reported bug as a whole.

**Comment by Adriani90** [comment]
cc: @codeofdusk

**Comment by JulienCochuyt** [comment]
I do not reproduce in NVDA 2020.1 on Windows 10

**Comment by Adriani90** [comment]
I am closing as works for me, i cannot reproduce it either. Feel free to comment on this if you are still having this issue and we can reopen.
