### ISSUE TITLE
Defect in the select all command in Spanish versions of MS Office applications

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4478]
**Reported by netblue on 2014-09-22 16:18**
When using the select all text shortcut control+e for Spanish version of MS applications  NVDA just announces the current text alignment. And when using control+a NVDA says all selected, but nothing is selected and the open dialog of the application is activated.
Using Office 2013 PRO Spanish.

**Comment by ehollig** [comment]
Was this submitted to the translations repository and fixed? CC @josephsl

**Comment by jcsteh** [comment]
Yes. It landed in NVDA in 22326a16 (2014.4).
