### ISSUE TITLE
NVDA Unreliable in Applications via SSH

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4481]
**Reported by ironmangary on 2014-09-22 20:14**
When using SSH terminal clients, such as putty, Cygwin, etc., NVDA, up to the latest stable release 2014-03, is unreliable with responding with the correct line of data at the cursor position in applications on the console, such as pico and other text editors.  In addition, it will not follow highlighting unless a cursor is present, and even then, it won't always report the correct line being moved to.

Several people have confirmed what I have personally encountered in the following thread:

http://www.freelists.org/post/nvda/UNIX-Applications-Over-SSH

I am willing to provide you more specific examples and am available for testing.  I am switching from JAWS to NVDA and desperately need this to work for the ticketing system my work uses.  I would be happy to test any advances in this area.

Gary

**Comment by leonardder** [comment]
Although I do not experience this very often, I think adding the ability to change the cursor movement timeout would be helpful here. I'd say an option for this fits nicely into the object presentation options?

**Comment by leonardder** [comment]
For me, it already has noticeable positive impact if I change the 
timeout in editableText.EditableText._hasCaretMoved from 0.03 to 0.05.

@jcsteh, what do you think about just rising the timeout for 
NVDAObjects.behaviors.Terminal? This way, we can tackle this specific 
case while there will no difference for other EditableText cases you 
mentioned, such as the top of a document.

**Comment by jcsteh** [comment]
#7201 raises the default timeout to 100 ms, so cursor tracking should now work in terminals with up to 100 ms latency. Beyond this, #7201 also makes this configurable, but there's no UI for it. I don't think we'll ever add a proper GUI option for this, but an advanced config editing GUI is being discussed to at least avoid the need to fiddle in the Python console.

**Comment by Adriani90** [comment]
@ironmangary, @leonardder are you experiencing further this issue? Or can it be closed?

**Comment by sonor3000** [comment]
@ironmangary, @leonardder, @Adriani90, there are still problems with ssh and applications that are executed on the remote system.

I've tested some ssh clients during the last months and the best working client with nvda 2018.3 is the ssh client included in cygwin. However, this client has not that much possibilities and features that other clients, e.g. putty or secure cert, have.

Maybe all issues regarding ssh should be linked in a new issue that covers the actual situation with the different ssh clients and at least one ssh client with more features then the cygwin ssh client should be made working with a current NVDA release.

**Comment by leonardder** [comment]
As the caret move timeout can now be adjusted using NVDA's advanced settings category, I'm closing this as works for me. Since the default timeout has been increased, I've hardly experienced this issue anyway.
