### ISSUE TITLE
NVDA crashes randomly

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4482]
**Reported by norrumar on 2014-09-23 09:05**
I was copying a folder, pressing control+c, when NVDA crashed.

**Comment by bhavyashah** [comment]
@nvdaes At the time of reporting this issue, you stated that this crash occurs several times a week. Does Do you still experience such crashes? If so, how frequent are these presently?

**Comment by nvdaes** [comment]
Hi, I am on holliday. I will take care of issues when I go back and have a computer available. Thanks. 

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
@bhavyashah, I think that this issue can be closed for now. It's not happening now.
Cheers

**Comment by ehollig** [comment]
Closing, as requested in https://github.com/nvaccess/nvda/issues/4482#issuecomment-325314871. If this problem still persists, we can reopen this issue or a new issue can be created with exact steps to reproduce the issue.
