### ISSUE TITLE
text is entered in edit boxes despite being in browse mode

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4484]
**Reported by blindbhavya on 2014-09-23 15:09**
Steps to reproduce
Go to community.nvda-project.org
Press Ctrl Home to go the start of the page.
Press e to go to the edit box. Ensure that you do not hit spacebar or Enter  to switch to focus mode.
Press for e.g. an alphabet such as a (a because a is not a quick navigation key).
Now press b (b because b is a quick navigation key for buttons).
Actual Results: When you press a, which is not a quick navigation key, a gets entered in the edit box, despite being in browse mode. This applies for all other keys which are not quick navigation keys, for e.g. alphabets such as a, p, w, y, z, punctuation/symbols, special characters and simply everything else that is not a quick navigation key.
When you press b, NVDA promptly takes you to the next button.
Expected Result: NVDA shouldn't let a enter in the edit box because the user isn't in focus mode. NVDA shouldn't do anything at all since a is not a quick navigation key either.
NVDA correctly handles b.
Hope I was clear.

**Comment by ehollig** [comment]
I am not able to reproduce this using the comment box on this issue for an example. When in browse mode and I press, Z, Y, P, or any punctuation/symbols, Windows makes an error tone and the key is not passed to the application. Closing, but if someone can reproduce and provide an STR, this can be reopened. Closing
