### ISSUE TITLE
Plustek Book Pavilion is not accessibleis

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4486]
**Reported by bvivi on 2014-09-23 21:35**
Plustek Plustek Book Pavilion . Program to manage the scanner OpticBook is not accessible, a number of items you can not select .
Even with Jaws 13 has the same problem .
I have already reported the problem to the company also Plustek

**Comment by leonardder** [comment]
Closing this, as we can't contact the initial author of this issue any more. Furthermore, this is not NVDA specific.
