### ISSUE TITLE
Several Problems With the new klatt engine

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4497]
**Reported by ateu on 2014-09-28 13:24**
Hi,

I have tested the build with NVSpeechPlayer, and detected several important problems when using the Brazilian voice.
1. Some accented lettersare not spoken, such as á and ó. This occurs with any espeak variant.
2. Some letters are not correctly pronounced, such as:
   D, which is spoken like r when followed by a or o in word end, (e.g. espada or dado);
   Ã is not pronounced like it is when using other variants. It sounds strangely, but I can't describe this, and you should test to understand;
   This last problem also occurs in am and am, specially when they are the stressed syllable, such as cama, cana, etc.
   Õ is not correctly spoken, it sounds like u;
   Words where the stress is un, like mundo, are not spoken like when using other variants.
   I don't know what is causing this problem.

**Comment by bhavyashah** [comment]
CC @michaelDCurran

**Comment by Adriani90** [comment]
@ateu are you still having this issue?

**Comment by Adriani90** [comment]
I am closing this because we lost contact to the author and we do not have updates since a very long time. Please comment on it if you want to reopen the discussion. But feel also free to report these issues directly  to NV Access as it is the author of the NV speech player addon.
