### ISSUE TITLE
NVDA losing functionality

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4508]
**Reported by virking on 2014-09-30 01:35**
Hi,

I love NVDA and really don't want to use any other screen reader. Lately, though, I've had an increasing number of problems with it that have rendered it almost useless. 

Firstly, I started to have problems typing into text boxes like search engines. Instead of typing letters, it would often use the hotkeys instead. For example, if I tried to type H, it would try to find a heading instead. I had to turn NVDA off in order to type into text boxes. 

Then I had trouble scrolling down a page and having NVDA read it to me. Sometimes it would work, but other times it would not go down the page past a certain point, whether I tried to use tab to go down the page or use the down arrow.

Also, I like to mouse over text to have NVDA read it to me. This function broke down next. At first the mouse positioning was off and I would have to move the mouse well above the text in order to have it read. Now it no longer reads text at all, no matter where I move the mouse.

Please let me know if you can help me solve this problem.

**Comment by ehollig** [comment]
Sounds to me like all the issues have been resolved in https://github.com/nvaccess/nvda/issues/4508#issuecomment-155328344. For the second issue, we would require additional information from the author to reproduce the issue. Since we do not have a way in contacting the original author, closing.
