### ISSUE TITLE
NVDA does not function as expected in dialogs on Google sites (Play, Calendar etc)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4511]
**Reported by gregjozk_ on 2014-10-01 10:02**
When installing an app or using calendar may be also in groups and other services, NVDA does not function as expected. It means, that I could not read all content during app instalation (list of requested permitions). I tried to exit from dialog mode (object mode) and went to bottom of the page, but it was unsuccessful. Same issue is on calendar, groups and other services. I don't know why it heppens. It may heppens because Google did not implement html5 and aria as it should or NVDA can not read Googles dialogs.

p.s. Same problems exists on couple of other sites.

p.s.2. same test was made also in Firefox with same results.

**Comment by ehollig** [comment]
Sounds like from https://github.com/nvaccess/nvda/issues/4511#issuecomment-155328420, the problem has been fixed. Can this then be safely closed? CC @leonardder @jcsteh
