### ISSUE TITLE
Nvda and link role question.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4518]
**Reported by khsruru on 2014-10-02 01:47**
Hello, I’m Hyongsop Kim in Korea.
I’m always appreciate your replies about all of my tickets.
And I have a question about Nvda and treating link role.
For testing, I made two scenarios.
First, in div tag, I added link role with text and Nvda treated link role correctly.
But second, in a tag, I added link role without href attribute, Nvda doesn’t recognize link role.
I think that role attribute should be taken priority over their original control.
In this case, do you think that it is a bug of NVDA or not?

Thank you.

**Comment by Adriani90** [comment]
This is still reproducible in NVDA 2019.1.1 and IE11.

**Comment by Adriani90** [comment]
Support for IE has ended completely in 2022 and is being removed automatically from machines that still have it after an Edge update in February 2023. I don't expect further accessibility updates for IE or for IE mode in Edge, so I am closing this issue as abandoned.
