### ISSUE TITLE
Sometimes focus jumps back to a previous web element in Firefox when arrowing down a webpage

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4522]
**Reported by blindbhavya on 2014-10-03 15:10**
Hi.
I have left the summary line empty, since can't think of a concise summary of this issue.
STR
Go to http://www.ilovereading.in/
Press h and go to the heading labelled Search For Excellence.
Press down arrow once and listen to the line. After NVDA has finished speaking that line press down arrow once more. If it has completed reading this line as well press down arrow.
While down arrowing, on my system (Firefox 31 or 32), NVDA goes back to the heading Search For Excellence.
I haven't been able to figure out the exact and reliable way of reproducing this issue.
Hope someone may be able to reproduce it.
I will attach a log as well.

**Comment by ehollig** [comment]
Closing as it sounds like a duplicate of #3266
