### ISSUE TITLE
display an error message informing the user about the 250 characters' limit when user enters a value greater than 250 in 'Maximum characters on one line' option in Browse Mode dialog

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4529]
**Reported by blindbhavya on 2014-10-04 15:15**
The summary explains it all. Anyways, when the user enters a value greater than 250 in the Maximum characters on one line field in the Browse Mode Settings dialog, and attempts to save those changes by pressing the Ok button, NVDA should display an error message, informing the user of the 250 characters' limit and a request to modify the value so that it is equal to or lesser than 250.
I hope I was clear and detailed enough.
P.S. Please file another ticket, if there is a limit to maximum lines in a page and there is no error message there as well.

**Comment by leonardder** [comment]
Fixed in #6414. It is no longer possible to exceed the limit for this option.
