### ISSUE TITLE
assign Ctrl S keystroke to Save As command in NVDA Log Viewer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4532]
**Reported by blindbhavya on 2014-10-06 14:44**
The summary line explains it all.
So, could Ctrl + S be made to work as the access key for the Save As option in the Log menu in the Log Viewer found in Tools submenu under NVDA Menu?

**Comment by derekriemer** [comment]
Hi guys, Pretty sure &As will bind to a not s. Shouldn't that be "save A&s"? That's how I did it in wx last time I did this sort of work.

**Comment by dkager** [comment]
> Pretty sure &As will bind to a not s.
Yup.

> Shouldn't that be "save A&s"?
I would reserve the `S` for Save, which the log viewer doesn't have, and `A` for Save As. For that matter, Ctrl+S intuitively means to save without popping up a dialog to me. It's probably not a problem in this instance, but I wouldn't change the mnemonic.

**Comment by jcsteh** [comment]
1. The shortcut in the menu is currently "s", even without this change.
2. Even if we wanted to change it to "a", that doesn't affect the binding of the control keystroke.
3. Control+s often does Save as if no file name has been specified. Try opening Notepad and just pressing control+s. This is always the case in the log viewer, so I think this is acceptable.

**Comment by jcsteh** [comment]
Oh, and the reason I bound it to "s" instead of "a" in the first place is that there *is* no plain "save" for the log viewer.

**Comment by dkager** [comment]
Regarding (1), I wasn’t aware of that as I tend to open the log externally. That kinda voids my point. :)

**Comment by nvaccessAuto** [comment]
Incubated in 79a5a2d703e70801bfd2c8c4576bc691402e101c.
