### ISSUE TITLE
eclipse - make title reading more useful by reading title of currently focussed widget

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4536]
**Reported by manish on 2014-10-07 01:42**
In the spring tool suite version of eclipse - and the bare bone version of eclipse as well --, the title bar does not always have useful information. It only has the name of the currently loaded perspective.  Is it possible to append the title of the currently focused widget to the title bar information. This can be a code editor window, the console, the dashboard etc. 
It may alternatively be an option within the eclipse IDE to display this information in the title bar but I haven't found such an option so far.

**Comment by Adriani90** [comment]
@jcsteh have there been any further discussions regarding this issue?
@manish I guess you can still reproduce it. Right?
cc: @michaelDCurran, @feerrenrut

**Comment by Adriani90** [comment]
Given the workaround with the object navigation which is standard for reporting title of parent objects, I am closing as works for me. We cannot squeeze all type of titles into the nVDA+t command, otherwise it will become to verbose for one single command.
