### ISSUE TITLE
Pressing read current line command thrice should spell the current line with character descriptions

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4551]
**Reported by blindbhavya on 2014-10-14 14:39**
When NVDA + up arrow for Desktop kb layout and NVDA + l for laptop kb layout (say current line command) is pressed thrice, NVDA should do either of the following:
1 NVDA should read the current line phonetically
2 NVDA should copy the current line to the clipboard

**Comment by feerrenrut** [comment]
Fixed by: Fixes to reportCurrentLine's spelling functionality #6894

**Comment by derekriemer** [comment]
@tspivey, can you publish your nvda+v addon to the site, @bhavyashah might like it.
