### ISSUE TITLE
Send liblouis log output to the NVDA log

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4554]
**Reported by jteh on 2014-10-16 23:18**
liblouis logs information which could be useful in debugging problems. We should send liblouis log output to the NVDA log at level debugWarning (or perhaps debug if it's too much). This is now possible with the logging callback introduced in liblouis 2.6.0.

**Comment by leonardder** [comment]
cc @JCSTeh @DKager

**Comment by dkager** [comment]
I have been meaning to add the necessary functions to the Python wrapper, but haven't done so yet.
One potential problem is that liblouis has its own log levels, which don't map to NVDA log levels. For example, I think most of what liblouis logs shouldn't be included in NVDA's default (info) level.

**Comment by jcsteh** [comment]
I'd say just push all liblouis log output as debug in NVDA's log. Even if
it's reporting an error, that should cause an error higher in the code
(e.g. translate failing). The dev can then poke at the log to get more
details.

**Comment by leonardder** [comment]
May be even add a separate option to the configuration system similar to HwIo debugging?
