### ISSUE TITLE
NVDA generates huge amount of errors and becomes unresponsive in NetBeans 8.0.1 new project dialogue

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4557]
**Reported by zersiax on 2014-10-18 16:48**
When JDK version 8.x is being used in combination with the Java Access Bridge, Netbeans is supposedly accessible. However when encountering certain controls, like the category selection treeview in the New Project dialogue, NVDA crashes rather spectacularly. I had to go in with JAWS to grab the logs it was generating. The error sound is played often repeatedly and a number of JAB errors show up in the logs.

**Comment by tyrylu** [comment]
Hello,
Same with jdk 8.x, Netbeans 8.1/8.0, latest snapshot. The log is filled with tracebacks like those:
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "JABHandler.pyc", line 611, in internal_event_stateChange
  File "JABHandler.pyc", line 298, in internalQueueFunction
  File "Queue.pyc", line 148, in put_nowait
  File "Queue.pyc", line 123, in put
Full
and those:
ERROR - unhandled exception (20:04:45):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "JABHandler.pyc", line 604, in event_valueChange
  File "NVDAObjects\__init__.pyc", line 69, in __call__
  File "NVDAObjects\JAB\__init__.pyc", line 217, in __init__
  File "NVDAObjects\window\__init__.pyc", line 166, in __init__
ValueError: invalid or not specified window handle
The second kind is more frequent, it seems.

**Comment by bogdanus91** [comment]
Hello. I have the following error while try to write code in NetBeans IDE. It is happening after NVDA reads autocomplesion suggestion. After this nvda doesn't speak at all until you pres alt+tab and then return to NetBeans window. In log I see the following:

ile "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 614, in compareEndPoints
AttributeError: 'NVDAObjectTextInfo' object has no attribute '_start'

**Comment by Brian1Gaff** [comment]
Is this a system that depends on firefox then?
 Does it actually work with the new versions of ff or is it meant for 52 and 
before?
 Brian

**Comment by Adriani90** [comment]
@zersiax, @tyrylu, @bogdanus91 are you still able to reproduce the issues?

**Comment by tyrylu** [comment]
I was not able to reproduce it with Netbeans 10, however it has some strange focus stealing bug, so the usability is still lacking.

**Comment by Adriani90** [comment]
Thank you vor your fast reply! Could you please open a new issue and describe the current problems? Please include also a log file with debug enabled while you see the issues. Thank you.

I guess if this specific issue is not reproducible anymore, maybe we can close this one once you opened the new issue. cc: @josephsl

 

 

Von: Lukáš Tyrychtr <notifications@github.com> 
Gesendet: Samstag, 5. Januar 2019 15:15
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] NVDA generates huge amount of errors and becomes unresponsive in NetBeans 8.0.1 new project dialogue (#4557)

 

I was not able to reproduce it with Netbeans 10, however it has some strange focus stealing bug, so the usability is still lacking.

**Comment by Adriani90** [comment]
I am closing this one as works for me, given the response above which states that the crash is not reproducible in NetBeans 10. For individual problems or questions regarding NetBeans, please create new issues. Thanks.
