### ISSUE TITLE
NVDA ignores Headings that have an SVG inside inFirefox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4559]
**Reported by MarcoZehe on 2014-10-20 07:58**
If a heading element only contains an SVG tree, NVDA ignores it, including the heading, even though Firefox exposes them in the accessibility tree just fine. Even NVDA's object nav sees the elements. They just don't show up in the virtual buffer.

Steps to reproduce:
1. Go to [this example on Codepen](http://codepen.io/heydon/pen/lyAqm).
2. The top shows the code, the bottom iframe contains the actual result of the code.

Expected: The h1 plus the titled SVG should show up in the iframe.
Actual: The heading is completely ignored.
1. Now, explore the accessibility tree of the iframe with the object navigator.

Result: Heading level 1 is there, and its child is a diagram accessible with the title of the SVG.

**Comment by Adriani90** [comment]
@MarcoZehe can you still reproduce it? I tested in Firefox 64.0 and the h1 is recognized properly in the virtual buffer. I double checked with object navigation and the h1 is definitely the one with the diagram as child.

**Comment by MarcoZehe** [comment]
Nope, this is no longer reproducible and can be closed.
