### ISSUE TITLE
add less obtrusive way to subscribe to tickets

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4567]
**Reported by mohammed on 2014-10-22 07:50**
perhaps there's a Trac plugin for subscribing to tickets less obtrusively? or may be it can be done in another way? there are certain members who only update a ticket just to subscribe to them. when this is done 5 times a day, it starts to become annoying.

I acknowledge that this is a trivial request, but it'd be nice if it can be accommodated one day.

**Comment by derekriemer** [comment]
Should be closed.

**Comment by derekriemer** [comment]
Closed as the project doesn't use track anymore.
