### ISSUE TITLE
Google alert manage page: some text have no element information provided

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4573]
**Reported by surfer0627 on 2014-10-24 06:05**
browser: Internet Explorer 8

Steps to reproduce the case`:
1. Open google alert manage page:
https://www.google.com/alerts
2. Sign in account.
3. Press "e" to go to the field "create an alert about".
4. Press arrow down few times, heard information about my alert "alert name, edit, delete".
User could activate "edit" and "delete".
result: No element information provided.
expected: NVDA detects the element information 

P.S. 
Test the same case on firefox:
speech reports "alert name".
Text "Edit and delete" are just reported "clickable".

Thanks.

**Comment by ehollig** [comment]
I performed the steps outlined in https://github.com/nvaccess/nvda/issues/4573#issue-116045545 and was able to activate and navigate to the edit and delete". They both appear as buttons in IE 11 and Firefox 54. More and more sites now are warning you your browser is out of date and you should update if using IE 8, which may be part of the issue. Closing
