### ISSUE TITLE
Regression in NVDA Voice Dialog

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4577]
**Reported by netblue on 2014-10-27 14:10**
High, when opening the voice dialog with the short cot NVDA+control+v there is usually a two to three second lag. This does not happen with previous versions of NVDA. This is happening in latest snap.

**Comment by ehollig** [comment]
I do not experience a lag when opening the voice dialog with NVDA+CTRL+V. Can anyone confirm that this is still an issue on slower machines or if it is indeed a regression? CC @jcsteh

**Comment by ruifontes** [comment]
Hello!

In a slow machine with Windows 10:

IO - inputCore.InputManager.executeGesture (19:37:35.627):
Input: kb(desktop):control+NVDA+v
DEBUGWARNING - Python warning (19:37:35.744):
C:\Program Files\NVDA\library.zip\gui\settingsDialogs.py:69: 
DeprecationWarning: object() takes no parameters
IO - speech.speak (19:37:36.351):
Speaking [u'Defini\xe7\xf5es da Voz  Janela']

724 miliseconds to open the dialog.

To open Browse mode settings, NVDA+Ctrl+B it takes only 391 miliseconds...

So, it really exists some lag, but for me it is acceptable...

Rui




-----Mensagem Original----- 
De: Ethan Holliger
Data: 27 de julho de 2017 16:38
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Regression in NVDA Voice Dialog (#4577)



I do not experience a lag when opening the voice dialog with NVDA+CTRL+V. 
Can anyone confirm that this is still an issue on slower machines or if it 
is indeed a regression? CC @jcsteh

**Comment by Adriani90** [comment]
I guess this is due to different synth add-ons because the synth drivers are stored when pressing NVDA+ctrl+v NVDA looks if there are all synth srivers in place. But I might be wrong. I do not really notice a significant lag in the new settings dialog.
I suggest closing this.

**Comment by leonardder** [comment]
[**@Adriani90**](https://github.com/Adriani90) commented on [28 Jul 2018, 10:44 CEST](https://github.com/nvaccess/nvda/issues/4577#issuecomment-408592939 "2018-07-28T08:44:20Z - Replied by Github Reply Comments"):
> I guess this is due to different synth add-ons because the synth drivers are stored when pressing NVDA+ctrl+v NVDA looks if there are all synth srivers in place. But I might be wrong.

I'm afraid you are wrong indeed. The only situation where all synths are fetched is when opening the synthesizer selection dialog, either by pressing nvda+control+s or when pressing change from the speech settings category in the settings dialog.

**Comment by leonardder** [comment]
@netblue44: Is this still an issue for you?

**Comment by netblue44** [comment]
No you  can close now thanks.
