### ISSUE TITLE
FS Focus Braille display skips soft line breaks when read by paragraph is unchecked

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4581]
**Reported by Sukil on 2014-10-27 20:51**
I don't know if it's specific to this display, but I noticed this in MS word 2007.
STR:
- Example text:
  _Whereas recognition of the inherent dignity and of   the equal and inalienable rights of all members of the human family is the foundation of freedom, justice and peace in the world
  This is anotherline_
- Paste this in word. 
- Go to the top of the document and navigate right using the braille display.
  Result: The Braille display will skip the second line.

**Comment by Adriani90** [comment]
cc: @leonardder, @bramd

**Comment by Adriani90** [comment]
@david-acm coul you please test if this issue is still reproducible with focus braille display?

**Comment by Adriani90** [comment]
If possitlbe test with las NVDA Alpha.

**Comment by Adriani90** [comment]
@ivnc could you please try to test if this issue is still reproducible on focus blue? Thanks.

**Comment by Adriani90** [comment]
We do not have any reaction from initial author and other braille display users regarding this issue since years. I am closing this issue as abandoned. Please feel free to comment on it with test results if you think this issue still occurs. Thanks.

**Comment by ivnc** [comment]
I’ll be able to test this the next week. Feel free to remind me this if I forget. Regards

**Comment by ivnc** [comment]
Can't reproduce here, both with UIA for Word enabled and disabled. Could be @sukiletxe the original reporter? If so, please test again and update the issue with your results.
Testing environment: NVDA 2019.2Beta1 with Focus 40 Blue 5th Generation (firmware 5.81-40) and Office 2019 (16.0.11629.20238) 64 bits on Windows 10 1803 (build 17134.765).

Regards.

**Comment by bdorer** [comment]
@ivnc did you test this? If you are able to reproduce please ask to 
reopen this.

Am 11.06.2019 um 23:04 schrieb Iván Novegil:

**Comment by ivnc** [comment]
> 
> @ivnc did you test this? If you are able to reproduce please ask to reopen this.

Yes, with negative results. See my previous comment above.

Regards.
