### ISSUE TITLE
NVDA is not reading validation messages

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4583]
**Reported by Santosh on 2014-10-28 11:24**
Hi,

I am using Firefox and NVDA.
when  validation error messages(using errors on top technique) are displayed on the screen, Whole content that is available on the screen is read by NVDA rather than only the validation message.
This is happening only in Mozilla firefox, also NVDA reading Clickable clickable continuously.

I am using Firefox 33.0.1 version.

Could you please help me , what might be the issue here.

**Comment by ehollig** [comment]
I am unfortunately unsure what the original author is talking about, and am not able to reproduce without a test case and exact steps to reproduce as @jcsteh requested in https://github.com/nvaccess/nvda/issues/4583#issuecomment-155329792

**Comment by bhavyashah** [comment]
I concur with @ehollig. Since we have hardly any information with regards to what the author was originally reporting, no STR, no test case, and most importantly, no means to contact the original reporter of this ticket, could this ticket be safely closed? @jcsteh @feerrenrut @leonardder

**Comment by feerrenrut** [comment]
As discussed this issue seems to be at a dead end. If anyone is able to reproduce this issue or has more information, please comment and we would be happy to re-open this issue and work through the process required to gather the necessary information.
