### ISSUE TITLE
double announcement of hot key in Show All History option in History submenu of Firefox latest stable

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4591]
**Reported by blindbhavya on 2014-11-02 15:00**
This is a pretty trivial issue, but anyways...
Steps to reproduce
Go into Firefox > History.
Your focus will land on to the Show All History option.
Expected: NVDA should simply read the option name and its hot key once.
Actual: NVDA will read the option name, then say the hot key twice (hot key is Ctrl Shift H).

**Comment by ehollig** [comment]
This sounds like a duplicate of #3057
