### ISSUE TITLE
Brailand 40 touch cursor navigation keys do not work with NVDA at all

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4592]
**Reported by janusz on 2014-11-02 15:34**
Dear developers,
I would like to inform You, that Brailand 40
USB device is not fully compatible with NVDA screen reader for now.
User is not able to use cursor navigation touch keys to set The cursor at The corresponding cell at The Braille display. The touch navigation keys are The keys which are situated above every Braille cell. 
Touch cursor navigation keys do not work at all no matter, if user run Notepad or Word.
Is it possible to repair this issue please?

The serial number of The Braille device is

35003772

What can I do to help You debug and repair this issue please?

Thank You very much for Yours help.
With kindness regards.
Janusz Chmiel

**Comment by dkager** [comment]
Seems safe to close because we don't know which display is being referred to. On the Brailliant BI cursor routing definitely works. :)
