### ISSUE TITLE
Apostrophe incorrectly interpreted as a word separator

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4607]
**Reported by leonarddr on 2014-11-07 11:48**
The change in #1704 does not yet work for combinations containing apostrophes. I have "'t" which should be pronounced as het, In combination such as "don't", the dictionary item does apply although whole word is selected. IN other words, the apostrophe is detected as a word separator. This is also visible when speak typed words is on:
`
Input: kb(laptop):d
IO - inputCore.InputManager.executeGesture (12:45:50):
Input: kb(laptop):o
IO - inputCore.InputManager.executeGesture (12:45:50):
Input: kb(laptop):n
IO - inputCore.InputManager.executeGesture (12:45:50):
Input: kb(laptop):ACUTE/CEDILLA
IO - inputCore.InputManager.executeGesture (12:45:51):
Input: kb(laptop):t
IO - speech.speakTypedCharacters (12:45:51):
typed word: don
IO - speech.speak (12:45:51):
Speaking [u'don']
`

**Comment by leonardder** [comment]
Note that #4622 fixed my use case for using apostrophes in speech dictionaries.

**Comment by jcsteh** [comment]
Closing because the original use case was handled another way and fixing this would break matching with single quotes (as per https://github.com/nvaccess/nvda/issues/4607#issuecomment-155329991).
