### ISSUE TITLE
Repetitive unknown announcement in the list in the Applications page of Firefox Options

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4608]
**Reported by blindbhavya on 2014-11-07 14:23**
I am using Firefox latest stable.
Steps to reproduce
GO into Tools menu > Options
Press down arrow to select the Applications category.
Tab twice till you reach a combo box.
Now press down arrow.
Expected: NVDA should act normally, as it does with other combo boxes, or as it behaves generally.
Actual: NVDA will say options dialog unknown options dialog unknown and then read the item gaining focus.
Very weird.

**Comment by ehollig** [comment]
@bhavyashah, are you still able to reproduce this? When I go to options > applications > the list view, I do not get any indication of unknown using Firefox 55 and latest Master of NVDA. @jcsteh, do you still believe this depends on [MozillaBug:786508](https://bugzilla.mozilla.org/show_bug.cgi?id=786508)

**Comment by bhavyashah** [comment]
Using Firefox 55.0.3 with NVDA 2017.3, I can no longer reproduce this issue. Feel free to close. @ehollig

**Comment by ehollig** [comment]
Closing as requested in https://github.com/nvaccess/nvda/issues/4608#issuecomment-326745938. If this is still an issue, we can reopen it.
