### ISSUE TITLE
TencentQQ crash by using NVDA.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4615]
**Reported by vgjh2005 on 2014-11-10 10:32**
Hi Mic:
TencentQQ is the most social software in China. But the input method don't be read when inputting on it. I contract the Tencent company to solve this problem. When they try to add NVDAHelpRemote.dll to the safetyList, TencentQQ will be crashed. I've get the stack dump information here. Please fix this BUG as soon as possible. Thanks very much!!

**Comment by bhavyashah** [comment]
@vgjh2005  Does the reported crash still occur with TencentQQ  and NVDA's latest versions?

**Comment by vgjh2005** [comment]
Please close.

2017-09-15 19:29 GMT+08:00, bhavyashah <notifications@github.com>:

**Comment by ehollig** [comment]
Closing as requested in https://github.com/nvaccess/nvda/issues/4615#issuecomment-329833206
