### ISSUE TITLE
Thunderbird and Firefox cannot create virtual buffers when Avast anti virus used

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4623]
**Reported by briang1 on 2014-11-14 09:39**
There have been several reports of this problem on the freelists list. it only seems to affect Windows 7 and later.
 Myself I cannot  get Avast to install from the latest archive due to inaccessible installer, so cannot check, but thought it wise to at least raise this ticket in case it is an nvda bug.
 There is a lot file on the list and also a comment that taking the machine back to before the last Avast update makes it work and that it seems to be quarantining a file that might well be important.

 I know no more thant this myself, for as I say, i cannot test it.
 If I can still find the relevent messages I'll add them here.

**Comment by ehollig** [comment]
As far as I am aware, there is no way to fix false positives with antivirus's. Closing
The accessibility of the interface of Avast is covered in #3241. It would be recommended to contact the developers of Avast and ask them to improve accessibility into their app.

**Comment by derekriemer** [comment]
This was probably due to the av blocking in proc injection (If that's possible even).
