### ISSUE TITLE
Pressing enter doesn't trigger say word when language switching is enabled

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4626]
**Reported by leonarddr on 2014-11-14 15:36**
I tried this with several synths. When language switching is disabled, every word in below example is read when 'speak typed words' is on:
``
this is line one
this is line two

``
However, when automatic language switching is enabled, the last word of every line isn't spoken as a word. In other words, pressing enter doesn't trigger saying the word when automatic language swithcing is on.
**Blocking #4656**

**Comment by jcsteh** [comment]
This would probably be fixed by #1259.

**Comment by Adriani90** [comment]
This works as expected in NVDA Version: alpha-20045,a335297e and most edit fields in most programs. Closing as works for me.
