### ISSUE TITLE
Soport for Project Libre

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4627]
**Reported by netblue on 2014-11-14 15:57**
Hi all, Project Libre is and alturnative to MS Project. It is open source. However NVDA only reads some of the controls and some of the text. It would be great if soport could be developed for this softwear.

**Comment by ehollig** [comment]
Closing because of https://github.com/nvaccess/nvda/issues/4627#issuecomment-155330143. If this is referring to Libre Office, this is a very broad issue and would need additional information on specific cases.
