### ISSUE TITLE
nvda no longer able to install Avast on XP

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4628]
**Reported by briang1 on 2014-11-17 11:20**
It seems that the installer on recent versions of Avast anti virus do not work with nvda on XP any more.
  I'm creating this ticket just in case it can be fixed, though it might well be  the old  problem of it working on later versions of windows.
 The effect is that all the text on the  installer is read as one string and no apparent navigation is possible in any mode of the screenreader.

**Comment by bhavyashah** [comment]
@brian1gaff Could you please test and report whether or not the reported issue still persists?
 with the latest versions of NVDA and Avast? Regardless, since this seems to be a Windows XP specific bug, it may not be worthwhile to resolve this anymore.

**Comment by leonardder** [comment]
XP specific bugs aren't taken any more. Closing.
