### ISSUE TITLE
Quotes are not being read by NVDA.  the punctuation " is not read by NVDA even when the punctuation level is set to "ALL".

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4632]
**Reported by Stacy on 2014-11-18 14:34**
NVDA should read quotation punctuation, when punctuation setting for quotes is set to "Most" and "All".

**Comment by ehollig** [comment]
When I change the punctuation setting to "All" and read https://github.com/nvaccess/nvda/issues/4632#issue-116045889, the quotes around "most" and "all" are correctly read. It seems that we need more information from the author on this ticket.

**Comment by ehollig** [comment]
This worksforme and we can not contact the original author for more information. Closing.
