### ISSUE TITLE
a bug in  Sapi 4 Voices dialogue under windows 8.1

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4635]
**Reported by sirlaurence on 2014-11-20 17:20**
when using eti eloquence under the name true voice as a synthesizer, in preferences\voices, the o k button doesn't activate with enter or spacebar or mouse. therefore you cant change any settings.

**Comment by bhavyashah** [comment]
Given the age of this issue, our inability to contact the original author of this ticket for further information, the fact that SAPI 4 is fading into obscurity, and Eloquence, one of the two voices with which the reported issue was claimed to be applicable, is illegal and unsupported, I suggest closing. @ehollig

**Comment by ehollig** [comment]
Closing, as we are unable to contact the original poster for more information, and I am unable to find a link to download this True Voice synthesizer from Microsoft.
