### ISSUE TITLE
NVDA doesn't allow to type"ó" (lowercase o acute) in Braille

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4647]
**Reported by Sukil on 2014-11-27 20:02**
STR:
1. Switch both input and output table to Spanish computer braille.
2. Type or copy ó with the PC keyboard (the display shows dots 3-4-6)
3. Try to type the same symbol.
Result: a 0 is typed, and the display shows dots 3-4-6-7-8. The same thing is typed when pressing those dots.

**Comment by ehollig** [comment]
@jcsteh has this been fixed in Liblouis for Spanish computer braille?

**Comment by jcsteh** [comment]
Honestly, I have no idea. :(

**Comment by jcsteh** [comment]
If this issue still exists, it should be [filed as a liblouis issue](https://github.com/liblouis/liblouis/issues/new). Also, we can't contact the original reporter, so have no way of confirming. Closing.
