### ISSUE TITLE
Let add-ons get translated messages included in the core

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4652]
**Reported by norrumar on 2014-11-30 11:37**
When creating add-ons, sometimes developers can use messages included in NVDA's core.
Alberto Buffolino, a member of the add-on team, creates a plugin to get the translations of these messages, which can be useful for translators, since they could skip duplicate localizations.
I suggest to add a getTRanslatedMessage function in add-on handler to get translated messages.
Thanks.

**Comment by derekriemer** [comment]
Hi: I agree, and work done by Alberto et al has paved the way for this function.

**Comment by josephsl** [comment]
CC @NVDAES, @ABuffEr

**Comment by derekriemer** [comment]
Anyone who wants a PR under their belt, this would be pretty easy to add.

**Comment by nvdaes** [comment]
Hi, just to point out that perhaps it would be better to add something 
similar to the translate function that I use in add-ons, instead of the 
message function in which it's based, since message is for braille and 
speaking, not for gui, and translate seems more generic:

def translate(text):
	return _(text).

I think this function could be added in the addonHandler file.
Thanks.

**Comment by nvdaes** [comment]
Hi, I created an old branch on BitBuucket, so I can send a PR on GitHub now.

**Comment by nvdaes** [comment]
You can see #6747 PR

**Comment by jcsteh** [comment]
Closing as per https://github.com/nvaccess/nvda/pull/6747#issuecomment-273696649:

> One concern we have is that there's no guarantee that a message won't get removed from or changed in core. If that happens, the message in your add-on will be mysteriously untranslated in some versions of NVDA but not others, which could become difficult to manage.

See that PR for further discussion.

**Comment by nvdaes** [comment]
Thanks for your valuable comments.
I have created a public gist in case this is useful:
https://gist.github.com/nvdaes/00e6f53f36b2be7f794eb06629691531
