### ISSUE TITLE
NVDA does not seem to speak table info in Excel 2007

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4654]
**Reported by zersiax on 2014-12-02 11:43**
I opened an Excell sheet just now, but all NVDA seemed to say was 'table' without actually reporting the table's contents. This rather interesting log content was returned from nvda+f1:
Developer info for navigator object:
name: u''
role: ROLE_TABLECELL
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.window.excel.ExcelCell object at 0x04C92650>
Python class mro: (<class 'NVDAObjects.window.excel.ExcelCell'>, <class 'NVDAObjects.window.excel.ExcelBase'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: ''
location: (33, 174, 736, 487)
value: ''
appModule: <'appModuleHandler' (appName u'excel', process ID 28072) at address 4bbcf90>
appModule.productName: u'2007 Microsoft Office system'
appModule.productVersion: u'12.0.4518.1014'
TextInfo: <class 'NVDAObjects.window.excel.ExcelCellTextInfo'>
windowHandle: 9441750
windowClassName: u'EXCEL7'
windowControlID: 0
windowStyle: 1456406528
windowThreadID: 28460
windowText: u'Kernkwadranten.xlsx'
displayText: u'A B C D E F4 Mart5 KernkwaliteVertrouwen Aanwezigheid6 Valkuil GoedgelovighOpdringerigheid7 Allergie Achterdocht Onzichtbaarheid8 Uitdaging WaakzaamheiBescheidenheid9 Florian10 KernkwaliteNadenkendheiFlexibel11 Valkuil Passiviteit Veranderlijk12 Alle' (truncated)

I'm guessing that focusable = false attribute has something to do with this, but why is that even there?

**Comment by ehollig** [comment]
Closing, as @jcsteh provided the necessary information in https://github.com/nvaccess/nvda/issues/4654#issuecomment-155330346
