### ISSUE TITLE
Support for Firefox Hello

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4658]
**Reported by netblue on 2014-12-02 20:19**
Hi all, firefox 34 has a exciting new and very handy feature called Firefox Hello, which is a new real-time communication feature of Firefox using WebRTC. It enables you to communicate with friends, family and colleagues using the browser and nothing else.
What you may find interesting about it is that it does not require the creation of an account to communicate with other users. You have to exchange a link then. Users who don't mind the creation can creat a firefox acount.
It wood be great if nvda could make use of this feature.

**Comment by bhavyashah** [comment]
According to https://support.mozilla.org/en-US/kb/hello-status, Hello has been discontinued since Firefox 49. Time to close? @ehollig

**Comment by ehollig** [comment]
Closing because [Support for Hello was discontinued in Firefox 49](https://support.mozilla.org/en-US/kb/hello-status) and the latest version is Firefox 55.
