### ISSUE TITLE
NVDA screen reader reading Video tag Twice

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4662]
**Reported by vivek-panday on 2014-12-03 15:37**
Hi All,

I am using HTML 5 Video tag to play video ,while reading with NVDA screen reader it only saying "video video" in chrome and Opera browser .
After enable speech viewer I am only able to see "video video" coming.

Screen reader is not reader Title or aria-label values in chrome and Opera browser but working expected in FireFox .

Please suggest and update asap.  
**Blocking #4660**

**Comment by ehollig** [comment]
Closing this as wontfix, as @jcsteh pointed out:
> Moving the mouse isn't how most screen reader users will interact with the page.
Someone is still welcome to file a Chrome issue for this if they would like.
