### ISSUE TITLE
Virus of false positive ?

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4672]
**Reported by Albator on 2014-12-06 17:53**
VBA32 syas "suspected of Malware-Cryptor.Win32.General " in http://sourceforge.net/projects/nvda/files/releases/2014.4/nvda_2014.4.exe
https://www.virustotal.com/fr/file/430d0ec46e4e20f297100cf2354e31479051d1cb5e66bbbe3f6eb625e242e191/analysis/1417884250/

**Comment by ehollig** [comment]
@jcsteh, there is nothing that NVDA can do with false positives, right?

**Comment by jcsteh** [comment]
Not directly, no. We need to try to figure out how to report issues like these to the relevant antivirus vendors, but this info isn't easy to find, especially for all the different vendors. Regardless, closing because the situation has almost certainly changed in three years.
