### ISSUE TITLE
NVDA does not recognize the list view control in MP3Gain

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4675]
**Reported by jkinnunen on 2014-12-08 08:03**
NVDA doesn't recognize the list view control in the MP3Gain program. When the control becomes active, NVDA says "pane" but nothing else. Also, when trying to navigate through the file names in the list view with the arrow keys, nothing happens.

I'm using MP3Gain 1.3.4 beta. It can be downloaded [here.](http://mp3gain.sourceforge.net/download.php)

**Comment by leonardder** [comment]
@jkinnunen: Could you provide a status update for this issue? cc @josephsl

**Comment by Adriani90** [comment]
cc: @josephsl

**Comment by josephsl** [comment]
Hi,

I and others would like to hear from the original poster before proceeding with this.

Thanks.

**Comment by Qchristensen** [comment]
I have a user (from Twitter) advising that they are having the same problem, at least with the file list view, using NVDA 2019.1.  I'm trying to get more information from them.  Has anyone else tried out the program and replicated (or not replicated) the issue?

**Comment by Qchristensen** [comment]
I've got a log now:
[nvda (18).log](https://github.com/nvaccess/nvda/files/3062464/nvda.18.log)

**Comment by Adriani90** [comment]
This is fixed in the WXMP3gain, which is the follow-up project of MP3gain and can be downloaded here, last version is 4.2:
https://github.com/cfgnunes/wxmp3gain/releases/tag/4.2
Closing as works for me.
