### ISSUE TITLE
hpsf window is inaccessible

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4676]
**Reported by bhavyashah on 2014-12-08 16:47**
Hi,
There was some window with the title 'hpsf'
The parts that were inaccessible in it were:
1 When I Alt Tab on my computer, when I reach the hpsf window, NVDA simply said icon x of y.
2 When I Tab around the window, NVDA remains silent on some Tabs, and in some other places, says only 'button' for a control.
3 When I use object navigation, I can use the application better, but still there is a puzzling bit, when I tell NVDA to move to the next object, after all the controls in the window, it begins with the System Tray and other irrelevant things. When I press NVDA + B again NVDA starts reading the contents of the System Tray after reading the contents of this hpsf window.
More information about this hpsf window
THe window tells me 'A critical message about your computer is available. View now.'
There are controls like Remind Me Later, Remind Me later in x duration, View Now and Close.
Could NVDA be made to work with this window better?
If this is of any use, I am using an HP Elitebook.

**Comment by bhavyashah** [comment]
Since I no longer have access to any HP laptop nor are we in touch with Palacee_hun, as the original author of this ticket, I am happy for this to be closed. @ehollig

**Comment by ehollig** [comment]
As requested in https://github.com/nvaccess/nvda/issues/4676#issuecomment-323397109, closing
