### ISSUE TITLE
It's not Possible to Read Typed Content in Editable Combo Boxes When Using Google Chrome

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4678]
**Reported by ateu on 2014-12-09 17:36**
Hi

This editable combo boxes are present mainly in facebook. When entering a comment there via Google Chrome or its derivative browsers, It's not possible to read typed comment.
This doesn't occurs with Firefox or its derivatives.

**Comment by jcsteh** [comment]
Chromium issue 440653 is fixed, so this now works as expected.
