### ISSUE TITLE
Ability to warn the user about common errors in text that are difficult to detect for a screen reader user

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4684]
**Reported by Diego on 2014-12-11 15:54**
hello developers!
I would like to suggest a feature similar to JAWS text analiser.
is a feature that allows warn us that there are many spaces, inverted capital letters, lack of capital at the beginning of sentences, punctuation, parentheses
and inverted quotes, etc
**Blocking #4989**

**Comment by bhavyashah** [comment]
At least as it seems best to me, this feature should be demonstrated and tested for some time as an add-on package and later be incorporated into core. This is a gentle ping to add-on developers to consider taking up this challenge if and when time, priorities and circumstance permits...

**Comment by ruifontes** [comment]
In my opinion, that functionality should remain in the addons field...
It is not a screen reader feature, and visually there are no indication of 
those errors...

Rui


-----Mensagem Original----- 
De: bhavyashah
Data: 18 de agosto de 2017 17:20
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Ability to warn the user about common errors in 
text that are difficult to detect for a screen reader user (#4684)



At least as it seems best to me, this feature should be demonstrated and 
tested for some time as an add-on package and later be incorporated into 
core. This is a gentle ping to add-on developers to consider taking up this 
challenge if and when time, priorities and circumstance permits...

**Comment by zstanecic** [comment]
Well,
The NVDA cannot do that.
And if you thing about the NVDA text analyzer, 
That’s impossible for just one language


Od: ruifontes
Wysłano: piątek, 18 sierpnia 2017 19:25
Do: nvaccess/nvda
DW: Subscribed
Temat: Re: [nvaccess/nvda] Ability to warn the user about common errors intext that are difficult to detect for a screen reader user (#4684)

In my opinion, that functionality should remain in the addons field...
It is not a screen reader feature, and visually there are no indication of 
those errors...

Rui


-----Mensagem Original----- 
De: bhavyashah
Data: 18 de agosto de 2017 17:20
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Ability to warn the user about common errors in 
text that are difficult to detect for a screen reader user (#4684)



At least as it seems best to me, this feature should be demonstrated and 
tested for some time as an add-on package and later be incorporated into 
core. This is a gentle ping to add-on developers to consider taking up this 
challenge if and when time, priorities and circumstance permits...

**Comment by ruifontes** [comment]
What's NVDA Text Analiser and where to find it?

Rui


-----Mensagem Original----- 
De: zstanecic
Data: 18 de agosto de 2017 18:56
Para: nvaccess/nvda
Cc: ruifontes ; Comment
Assunto: Re: [nvaccess/nvda] Ability to warn the user about common errors in 
text that are difficult to detect for a screen reader user (#4684)

Well,
The NVDA cannot do that.
And if you thing about the NVDA text analyzer,
That’s impossible for just one language


Od: ruifontes
Wysłano: piątek, 18 sierpnia 2017 19:25
Do: nvaccess/nvda
DW: Subscribed
Temat: Re: [nvaccess/nvda] Ability to warn the user about common errors 
intext that are difficult to detect for a screen reader user (#4684)

In my opinion, that functionality should remain in the addons field...
It is not a screen reader feature, and visually there are no indication of
those errors...

Rui


-----Mensagem Original----- 
De: bhavyashah
Data: 18 de agosto de 2017 17:20
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Ability to warn the user about common errors in
text that are difficult to detect for a screen reader user (#4684)



At least as it seems best to me, this feature should be demonstrated and
tested for some time as an add-on package and later be incorporated into
core. This is a gentle ping to add-on developers to consider taking up this
challenge if and when time, priorities and circumstance permits...

**Comment by zstanecic** [comment]
Well, i willl name that feature in that way
It doesn’t exist

Od: ruifontes
Wysłano: sobota, 19 sierpnia 2017 00:59
Do: nvaccess/nvda
DW: zstanecic; Comment
Temat: Re: [nvaccess/nvda] Ability to warn the user about common errors intext that are difficult to detect for a screen reader user (#4684)

What's NVDA Text Analiser and where to find it?

Rui


-----Mensagem Original----- 
De: zstanecic
Data: 18 de agosto de 2017 18:56
Para: nvaccess/nvda
Cc: ruifontes ; Comment
Assunto: Re: [nvaccess/nvda] Ability to warn the user about common errors in 
text that are difficult to detect for a screen reader user (#4684)

Well,
The NVDA cannot do that.
And if you thing about the NVDA text analyzer,
That’s impossible for just one language


Od: ruifontes
Wysłano: piątek, 18 sierpnia 2017 19:25
Do: nvaccess/nvda
DW: Subscribed
Temat: Re: [nvaccess/nvda] Ability to warn the user about common errors 
intext that are difficult to detect for a screen reader user (#4684)

In my opinion, that functionality should remain in the addons field...
It is not a screen reader feature, and visually there are no indication of
those errors...

Rui


-----Mensagem Original----- 
De: bhavyashah
Data: 18 de agosto de 2017 17:20
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Ability to warn the user about common errors in
text that are difficult to detect for a screen reader user (#4684)



At least as it seems best to me, this feature should be demonstrated and
tested for some time as an add-on package and later be incorporated into
core. This is a gentle ping to add-on developers to consider taking up this
challenge if and when time, priorities and circumstance permits...

**Comment by Adriani90** [comment]
Even if it would exist, I doubt that it will work in every text editor. Maybe for MS Word it would be possible but actually MS Word has already functions to warn you in those cases.
Maybe @paulber007 has further suggestions.
cc: @michaelDCurran

**Comment by leonardder** [comment]
Honestly, I'd rather see functionality that allows you to jump two formatting differences with quick navigation keys. I.e.

* Bold text
* Italic text
* Font size
* An option to jump to the next difference in font attributes

**Comment by Adriani90** [comment]
@leonardder your suggestion is very interesting for me as well. I have discussed this in detail on the nvda community users list and also on the add-ons list. An example is in #7744 which however would depend on implementation of #7747.

**Comment by leonardder** [comment]
I agree that if a feature like this would be developed, it is best distributed as an add-on. Therefore, I'm closing this one as won't fix for now. We could always reopen if there are valid reasons to do so.
