### ISSUE TITLE
add an Addons submenu in the NVDA Menu, containing all add-on and add-on settings dialogs

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4689]
**Reported by bhavyashah on 2014-12-13 13:46**
Hi,
With increasing NVDA add-ons, there are increasing add-on dialogs as well, whichh are present in the Preferences dialog. The Preferences dialog is much populated anyway, and with add-on dialogs, becomes even more populated.
For convenience, a submenu could be created in the NVDA menu named Add-ons submenu, with all the NVDA add-on dialogs.

**Comment by bhavyashah** [comment]
I am not entirely convinced by @jcsteh's https://github.com/nvaccess/nvda/issues/4689#issuecomment-155330718. With the multiplicity of add-ons that we have today, many of which do have settings dialog, I can't imagine how cluttered the Preferences submenu would be with its inherent 14 items+add-on related items. With the emergence of a significant number of add-ons, this move would not separate add-ons or make their integration any less seemless, but rather, this would provide them distinction and the users a cleaner and more comprehensive UI. @leonardder Shall any of the above arguments be affected by the ongoing work on unification of NVDA settings dialogs?

**Comment by ruifontes** [comment]
I agree with the introduction of a new menu for Addons...
One question, in that new menu will go only the addons configuration entries 
or also the help entries?

And, by the way, why not join Profiles, Restore to saved configurations, 
restore to factory and Save configuration in one menu?


-----Mensagem Original----- 
De: bhavyashah
Data: 18 de agosto de 2017 17:25
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] add an Addons submenu in the NVDA Menu, 
containing all add-on and add-on settings dialogs (#4689)



I am not entirely convinced by @jcsteh's #4689 (comment). With the 
multiplicity of add-ons that we have today, many of which do have settings 
dialog, I can't imagine how cluttered the Preferences submenu would be with 
its inherent 14 items+add-on related items. With the emergence of a 
significant number of add-ons, this move would not separate add-ons or make 
their integration any less seemless, but rather, this would provide them 
distinction and the users a cleaner and more comprehensive UI. @leonardder 
Shall any of the above arguments be affected by the ongoing work on 
unification of NVDA settings dialogs?

**Comment by bhavyashah** [comment]
@ruifontes  Regarding the merger of mentioned configuration options under one dedicated submenu, I am certain that is covered elsewhere. I think I might search for that ticket later today and check about its current status...

**Comment by ruifontes** [comment]
Hi!

It is:
Reordering Main Menu Structure In NVDA #5976

it is closed, but I do not agree! Smile!

Rui


-----Mensagem Original----- 
De: bhavyashah
Data: 19 de agosto de 2017 05:18
Para: nvaccess/nvda
Cc: ruifontes ; Mention
Assunto: Re: [nvaccess/nvda] add an Addons submenu in the NVDA Menu, 
containing all add-on and add-on settings dialogs (#4689)



@ruifontes Regarding the merger of mentioned configuration options under one 
dedicated submenu, I am certain that is covered elsewhere. I think I might 
search for that ticket later today and check about its current status...

**Comment by Adriani90** [comment]
Actually I am ok with the current new cathegory structure. The addons are right after NVDA's settings cathegory which saves lot of time because you do not have to open a new dialog for each addon.
@ruifontes, @bhavyashah what are your opinions?

**Comment by ruifontes** [comment]
For me, you can close this issue...

Rui Fontes
NVDA portuguese team


Às 19:44 de 11/01/2019, Adriani90 escreveu:

**Comment by Adriani90** [comment]
closing
