### ISSUE TITLE
lag while arrowing in MS Word 2007 in NVDA as compared to JAWS

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4692]
**Reported by bhavyashah on 2014-12-14 08:51**
I think I started facing this issue only in version 2014.4
As compared to JAWS, NVDA is slower while arrowing in an MS Word document.
Restarting NVDA, even with add-ons disabled, doesn't make much of a difference.
I'm using Microsoft Office Word 2007.
Is anyone facing this?
I know I'm pretty vague, how can I be more detailed?

**Comment by bhavyashah** [comment]
There may still exist performance problems with Word, but this ticket is too vague and unclear, and as its original author, I am happy for this to be closed. @ehollig

**Comment by ehollig** [comment]
This is a very vague and unclear issue. However, as requested by the original poster in https://github.com/nvaccess/nvda/issues/4692#issuecomment-323399556, closing
