### ISSUE TITLE
find messages in thunderbird.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4708]
**Reported by siddharta33 on 2014-12-17 15:48**
Hello.
This message refers to last release of both NVDA and TB.
When you try to find a message using the edit field reachable by pressing ctrl+k, you'll find an HTML pages with all the occours of your research.
There are links with submenu that should provide list of messages divided for accounts or folders.
Pressing enter on them, by the way, causes NVDA saying "Section", "Sezione" in italian an no further actions are possible.
Gabriel.

**Comment by ehollig** [comment]
Any Thunderbird user can confirm this, or confirm whether it is fixed?

**Comment by ruifontes** [comment]
Still happens...
It seems that pressing spacebar does nothing...

**Comment by Adriani90** [comment]
@ruifontes could you please test once more with Thunderbird 68.3.0 and NVDA last alpha?
I think I cannot reproduce it.
cc: @ehollig

**Comment by Adriani90** [comment]
This is still reproducible in Thunderbird 115.1.0 with NVDA 2023.2 Beta 3.

cc: @emitche this needs an external fix, if possible. it seems when you press enter on a result after searching a message, two entries are added near to the filter area: "in inbox", "without inbox". These can only be accessed by NVDA via object navigation but not with arrow keys or tab keys. These need a tabindex or a role="application" or something like that.

**Comment by thgcode** [comment]
I created pull request #17130 to perform some tests, but I'm unsure, because the code I created is a big workaround to fix the bug, but it seems to work on Thunderbird 128.2.0. I will perform some tests on older versions to see if it works the same way.
