### ISSUE TITLE
NVDA announces the introductory message of the person wanting to add the user as a contact when the Accept button is pressed

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4720]
**Reported by bhavyashah on 2014-12-20 12:08**
Hi,
I'm using the latest stable version of Skype.
Steps to reproduce
Launch Skype (latest stable version).
Somehow, get a Skype invitation request, and go to that window.
After tabbing, you'll reach the Accept button where you hit Enter.
Expected Result: NVDA should say that {variable: your name} has shared contact details with {variable: person who sent contact request}.
Actual Result: NVDA announces the original introductory message which is something like 'I want to add you as a contact'
Although trivial, thought at least to bring it to your notice.

**Comment by leonardder** [comment]
@bhavyashah: Is this still the case? I belief way of acceptance of invitations is now changed, right?

**Comment by bhavyashah** [comment]
Not sure. I haven't received a contact request on Skype since quite some while, nor do I expect one anytime soon. Still, @ehollig  Mind experimenting this with me on Skype?

**Comment by ehollig** [comment]
@bhavyashah and I were unable to reproduce this issue and thus this ticket can be closed.
