### ISSUE TITLE
Ignore static text parent of add to favorites button and profile link

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4721]
**Reported by bhavyashah on 2014-12-20 13:29**
I am using the latest stable version of Skype.#
Steps to reproduce
Launch Skype (latest stable version).
Choose a contact and tab around.
On pressing Tab after the Avatar button:
Expected Result: NVDA should announce 'Add {variable: selected contact's name} to Favourites button'
Actual Result: NVDA announces '{variable: selected contact's name} text pause Add {variable: selected contact's name} to Favourites button'
Press Tab again and NVDA says '{variable: selected contact's name} link' as expected.
Press Shift tab and:
Expected Result: NVDA will act wrongly as before and say '{variable: selected contact's name} text pause {variable: selected contact's name} Add to Favourites button'
Actual Result: NVDA behaves as expected this time by saying 'Add {variable: selected contact's name} to Favourites button'
**Blocking #4722**

**Comment by Adriani90** [comment]
@bhavyashah can you still reproduce this issue?

**Comment by Adriani90** [comment]
The skype interface changed significantly since this issue has been reported. Please open a new issue with steps to reproduce according to the new interface. Thanks.
