### ISSUE TITLE
NVDA remains silent on the Tab after the two locations button in VLC Media Player's Open File... dialog

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4730]
**Reported by bhavyashah on 2014-12-21 04:46**
Steps to reproduce
Launch VLC Media Player (latest stable version).
Through the Media submenu, choose the Open File... dialog
When the dialog appears, tab until you reach the 'two locations button'.
On the next tab notice that NVDA remains silent.

**Comment by bhavyashah** [comment]
I re-tested this with VLC Media Player 2.2.3, and was unable to reproduce my earlier described behaviour. In fact, there is no more a 'two locations' button in VLC's Open File dialog. While the version I use is not the latest (which is 2.2.6), I suppose we can safely close this issue regardless.

**Comment by ehollig** [comment]
Thanks for the update. Closing as invalid
