### ISSUE TITLE
in Shareit (by Linnovo group), when user presses the Next Page or Previous Page button, NVDA simply announces 'Shareit window' instead of saying the newly appeared help tip

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4731]
**Reported by bhavyashah on 2014-12-21 04:53**
Steps to reproduce
Download, install and launch Shareit by Linnovo (free application).
You will be presented with 'Next Page button' and 'Do not show this dialog again check box'.
Hit Enter on Next Page button.
Expected Result: NVDA will read the help tip that Share it is providing on this screen.
Actual Result: NVDA says 'Shareit window'.
The same ocurrs on the new 'Next Page button', and also on 'Previous Page button's as well.
Ideally, NVDA should report the newly appeared help tip/information that Shareit is providing to the users.

**Comment by ehollig** [comment]
Closing, because of reasoning in https://github.com/nvaccess/nvda/issues/4731#issuecomment-155331452
