### ISSUE TITLE
issues in Windows 7 Disk Defragmenter utility

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4732]
**Reported by bhavyashah on 2014-12-21 08:16**
I may not be able to provide information about expected and actual results, but they will be pretty obvious when you encounter them.
Simply open the Disk Defragmenter utility in Windows 7 (thats the OS I'm using, this issue may occur with other versions of Windows as well).
Tab around and press up and down arrow, and you'll understand whats strange.

**Comment by ehollig** [comment]
@bhavyashah, do you still have a Windows 7 machine to test this on or could you clarify exactly what is the issue addressed in this ticket? If not, @Brian1Gaff, could you test this?

**Comment by Brian1Gaff** [comment]
Right, well. Often in Windows 7 when you do the test of the volume in the 
defrag, the actual descriptors of the fields are spoken as gibberish with a 
situation like if  foreign characters are present, but that language is not 
in Windows. IE letter this or that.
Strangely, the actual fields of the data are correct.
Later if you do a defrag you will find next time you look at the same part 
of the utility, that the correct characters are spoken.
 I think this used to also be the case in XP.
I would say this is annoying but once you figure out what is going on, its 
managable.
Are we saying no similar issues exist in 8 or 10?
 I'm rather busy to do a long log right now, but if it will be of help poke 
me again. Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by bhavyashah** [comment]
@ehollig Unfortunately, I do not have a Windows 7 machine to test this on myself. Thank you @Brian1Gaff for chiming in with your testing results. To clarify, no such issue seems to be present at least while analysing drives for fragmentation using the built in disk defragmentation utility on Windows 8.1. I cannot speak for Windows 10. @feerrenrut Do you think the information reported in https://github.com/nvaccess/nvda/issues/4732#issuecomment-323695118 is sufficient to understand and evaluate this ticket?

**Comment by ehollig** [comment]
No issue seems to be present using the built in disk defragmentation utility on Windows 10. As it sounds from https://github.com/nvaccess/nvda/issues/4732#issuecomment-323695118, there does not appear to be an issue with Windows 7 either. Please reopen if I misunderstood. Closing
