### ISSUE TITLE
assign keyboard shortcuts to common actions in Skype

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4736]
**Reported by bhavyashah on 2014-12-21 09:12**
In Skype, there are very few keyboard shortcuts to jump to different areas of the program.
I propose assigning keystrokes in NVDA itself to jump or to active those areas. Examples of such areas are:
Video Call button
Call button
Chat content list
Type message here edit field
and others

**Comment by Adriani90** [comment]
here are all shortcuts for skype, which are actually quite some.
https://support.skype.com/en/faq/FA12025/what-are-keyboard-shortcuts-and-how-do-i-use-them-in-skype

@bhavyashah, @Brendon22, @k_kolev1985 is this actually a good user experience to work efficiently in Skype? Or are you still missing anything?

**Comment by Adriani90** [comment]
In my opinion the user experience is much better than earlier. And since Microsoft is pushing strongly accessibility, I think it is better to talk to them about further key strokes. Because this would also be beneficial for people using other screen readers.

**Comment by Adriani90** [comment]
Should I close this as worksforme?

**Comment by k-kolev1985** [comment]
> 
> 
> In my opinion the user experience is much better than earlier. And since Microsoft is pushing strongly accessibility, I think it is better to talk to them about further key strokes. Because this would also be beneficial for people using other screen readers.

I completely agree with your statement. I think is best for Microsoft to add additional keystrokes to Skype if necessary.

**Comment by josephsl** [comment]
Hi, in this case, I advise closing it as “needs external fix”. Thanks for an update on Skype.

**Comment by Adriani90** [comment]
closing as requested. Please feel free to report to Microsoft if further key strokes improve your efficiency. I am sure they are happy to help further in this regard.
