### ISSUE TITLE
NVDA doesn't speak when erranging apps side by side

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4743]
**Reported by fatih on 2014-12-22 16:31**
Hi,
NVDA doesn't speak apps when you presss Windows+period and begin to erange them by holding down the Windows key and pressing left or right arrows but narator speaks that information. Please fix this.

**Comment by ehollig** [comment]
Windows+. does not do anything for me either. When pressing Windows+Arrow keys to arrange apps on the screen, nothing, aside from the command keys is announced. Using Narrator and performing the same steps, nothing, aside from the command keys are announced. This is on Windows 10,1703. It would be interesting if the same results can be found in Windows 7 or 8.1. Regardless, I am leaning toward a wontfix

**Comment by bhavyashah** [comment]
Pressing Windows+. causes NVDA to say 'Desktop window', implying that the keystroke does have some effect. CC @Qchristensen to help us understand the working of this side-by-side app placement Windows feature

**Comment by Qchristensen** [comment]
I've never heard of being able to rearrange desktop icons like this.  The initial issue was raised in 2014 so the original person was likely using either Windows 7 or Windows 8.  I have tried on both Windows 7 and Windows 10.   I tried with NVDA running, with Narrator running, and with no AT running, and in all cases, I couldn't get anything to happen when I pressed NVDA+., nor can I find any documentation on such a command.

With a window active, if you press WINDOWS+LEFT ARROW or WINDOWS+RIGHT ARROW, on Windows 7 and later, it makes that window take up exactly half of the screen - either left or right.  Additionally, on WIndows 10, with the window taking up half the screen, if you then press WINDOWS+UP or WINDOWS+DOWN arrows it resizes the window to take up the appropriate quarter of the screen.  Pressing WINDOWS+UP ARROW from a window that is windowed and taking up anything other than half the screen will make the window full screen.

NVDA doesn't announce any of these changes in Window size.  For reference, neither does Narrator.  While it's something that sighted users can perceive, aside from the information that the window has changed size, for the cost of implementation, is it something that is beneficial to users?  NVDA shouldn't behave differently regardless of window size.

**Comment by ehollig** [comment]
[**@Qchristensen**](https://github.com/Qchristensen) commented on [Sep 4, 2017, 5:43 PM MDT](https://github.com/nvaccess/nvda/issues/4743#issuecomment-327039767 "2017-09-04T23:43:44Z - Replied by Github Reply Comments"):
> NVDA doesn't announce any of these changes in Window size.  For reference, neither does Narrator.  While it's something that sighted users can perceive, aside from the information that the window has changed size, for the cost of implementation, is it something that is beneficial to users?  NVDA shouldn't behave differently regardless of window size.

For reasoning stated above, closing as wontfix.
