### ISSUE TITLE
hot key to move system focus to Skype's edit area

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4748]
**Reported by mohammed on 2014-12-24 15:05**
Hi.

after the recent improvements to Skype I would like to request an enhancement that I think is necessary: a hot key that moves the system focus to the edit area "type a message here" in Skype's chat. the reason is that many times you find yourself far from that place either because Skype jumps you to another place suddenly, (the ad area for example, or because you were doing something. in either case it will often take too many tabs to move there. #3210 already takes care of moving and reviewing chat history.

thanks.
**Blocking #5134**

**Comment by Adriani90** [comment]
@k-kolev1985 I guess Skype has changed significantly in the last years. I am not a regular skype user. But is the behavior related in this issue now acceptable?

**Comment by Brian1Gaff** [comment]
I thought they had effectively made Skype like a web page now. Still don't 
like it though.
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by k-kolev1985** [comment]
@Adriani90 Yes, Skype 8 is significantly different than Skype 7 and earlier. In Skype 8 and Skype for Windows 10 from the Microsoft Store, there is a built-in keyboard command to focus the chat entry edit field - it is Alt+Shift+E. So, I think we can close this as "works for me" (or something like that).

**Comment by Adriani90** [comment]
closing as works for me
