### ISSUE TITLE
Support for the Caiku Albatross braille displays from Tivomatic

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4750]
**Reported by jkinnunen on 2014-12-26 06:01**
Would it be possible to create a driver for the Caiku Albatross braille display? There are two models available, one with 46 cells and one with 80 cells. They can be connected via USB or serial port.

There is a [driver](https://github.com/brltty/brltty/tree/master/Drivers/Braille/Albatross) for the BRLTTY package that might help in the development process. You can get more help also by contacting Teijo Burman teijo@burmanintk.fi, who has been involved in the development of the JAWS driver for these displays.

I have the 46 cell model of this display myself, so I am ready for testing the driver.

**Comment by leonardder** [comment]
@jkinnunen: Am I correct that these displays are supported by brltty? If so, I'm tempted to close this issue, since the displays have since long been discontinued according to https://github.com/nvaccess/nvda/issues/4750#issuecomment-155331785

**Comment by jkinnunen** [comment]
In Windows, there are problems that prevent these displays from being 
used smoothly with BRLTTY. As I no longer have one of these devices 
myself, am not able to comment on the problems exactly.

**Comment by leonardder** [comment]
In that case, I'm closing this as I proposed.
