### ISSUE TITLE
Microsoft Lync 2010 causes NVDA speech to stop working on an intermitant basis

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4765]
**Reported by Xonic on 2015-01-02 11:32**
When using microsoft Lync,I have noticed that NVDA stops speaking after an indeterminate amount of time. Unfortunately, there is no action or set of repeated steps that I am performing to create this issue, so I will do my best to describe it.

I am using multiple machines, runing NVDA latest nightly build, windows 7 64, ms office 2010 including Lync 2010 with latest security patches on all.

When using MS lync, I am able to chat fine with NVDA, by using the tab and shift tab keys, plus arrow keys to navigate. 
At multiple points during the day, I have seen as few as 2, and a maximum of 10, NVDA simply stops speaking. I do not have to be in MS Lync for this  to happen, but Lync does have to be running. I believe that the more I chat through Lync, the more likely it is to occur but as I've said, I cannot force this issue to happen on its own.

The crash has the following simptoms.
NVDA stops speaking. I have tried this with the build in e-speak synth and an external synth dolphin  orpheus that I am using. I have also tried Lync with other screen readers such as JAWS and supernova and determiend that this behavior does not occur.

Once NVDA stops speaking, i have 2 choices. I can either leave it for about 10 minutes, in which case speech sometimes comes back up. Or, I can navigate to the windows task manager using memory, and kill the "communicator.exe" file which is MS Lyncs main executable file. As soon as I do this, speech comes back up on NVDA.

I am sorry I cannot provide more information about this bug, it is a very irritating one and I've not found a reliable method of replicating it, other than to say it definitely does happen on a daily basis. Is there some sort of system tracker I could install to pick it up and report back>

Many thanks.

Ed.

**Comment by ehollig** [comment]
Closing, as we are unable to contact the original poster, as far as I am aware, and they did not respond to @jcsteh's request for a crash dump in https://github.com/nvaccess/nvda/issues/4765#issuecomment-155332122. If this is still an issue, we can reopen this issue or please open a new ticket with clear steps to reproduce the issue.
