### ISSUE TITLE
Javaw: command line parser routine returns full path of a jar file

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4770]
**Reported by nvdakor on 2015-01-03 03:42**
Hi,
Spin off from #4360:
If you run a jar file (jara archive), Javaw app module's command line parsing routine records the full path fo the jar file, not the file name itself.
STR:
1. Install a program packaged in a jar file (a good example is Braille Blaster).
2. Once Braille Blaster starts, press NVDA+F1 to bring up dev info for the object. Look for app module property.
Expected: the actual jar file name should be recorded.
Actual: full path is recorded.
Example via Braille Blaster:

```
Expected: appModule: <brailleblaster(appName 'javaw_brailleblaster', process ID 6332) at address 4dcb670>
Actual: appModule: <'appModuleHandler' (appName 'javaw_C:\\Program Files (x86)\\brailleblaster\\brailleblaster', process ID 6332) at address 4dcb670>
```

Problem implications:
- Java apps can be run on both 32-bit and 64-bit systems, and environment variables specify different program paths for 32-bit versus 64-bit Windows.
- One should not rely on absolute paths - system drive letter can change, program might be installed into different folder(s), etc.
  One way to perhaps fix this is to:
- See if we're dealing with a jar file (current routine provides this capability).
- If command line has backslashes, split the command line and take the last part of the executable path (perhaps using split or via os.path).
  For reference, this does not affect wwahost work (#4569), as there is a way to query name of the loaded wwa file without resorting to command line parsing (there is a way to parse the actual wwa file name via command line).
  Thanks.

**Comment by leonardder** [comment]
@josephsl: Given https://github.com/nvaccess/nvda/issues/4770#issuecomment-155332255, could we safely assume that this has been fixed?

**Comment by josephsl** [comment]
Hi, I’d say yes. Thanks.

**Comment by ehollig** [comment]
Closing from https://github.com/nvaccess/nvda/issues/4770#issuecomment-155332255 and https://github.com/nvaccess/nvda/issues/4770#issuecomment-365777608
