### ISSUE TITLE
Some changes between current release and current master causing problems with an add on

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4771]
**Reported by briang1 on 2015-01-03 12:56**
This is a strange one, and thus far  nobody seems to be able to explain it.
 The current Goldwave add on seems to misbehave on some machines, but not on others, but the only obvious predictable factor is that the release version of 2014.4 and its release candidate work fine on all machines, but the current master and next snaps do not.
The effect seems to throw off the reading of text in certain areas used  when start and end markers are dropped during playback inGoldwave 5.70 , and once an error has happened the 1, 2, 3,  options can  lose their focus and give an error in the case of  the 3 option.

Has there been any changes to the nvda code since the last release which is also now in the mster branch that could affect this?
 I have looked at the changelog, but not knowing what I might be looking for means I might not see it if I found it.
 Windows itself seems not to matter, one of the machines with this issue is windows 7 64bit and the others xp.

Only a handful of people/machines seem to get this effect which is puzzling. Thus far I see that it cannot be goldwave settings as all machines work correctly on the last release candidate snap and release version.
These two log fragments show the effect.
 Non working version...
INFO - core.main (12:31:27):
NVDA version master-10641,d5b17df
INFO - core.main (12:31:27):
Using Windows version sys.getwindowsversion(major=5, minor=1, build=2600, platform=2, service_pack='Service Pack 3')
snip..
Gap in time while i load goldwave and a file etc.

IO - speech.speak (12:47:01):
Speaking [('en_GB'), u'GoldWave  icon  5 of 5'](LangChangeCommand)
IO - speech.speak (12:47:03):
Speaking [('en_GB'), u'GoldWave'](LangChangeCommand)
IO - speech.speak (12:47:03):
Speaking [('en_GB'), u'real love.wav'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:47:18):
Input: kb(desktop):control+NVDA+1
IO - speech.speak (12:47:18):
Speaking [('en_GB'), u'Selected channel: stereo'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:47:23):
Input: kb(desktop):control+NVDA+2
IO - speech.speak (12:47:23):
Speaking [('en_GB'), u'Track length: 4:10.677'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:47:27):
Input: kb(desktop):control+NVDA+3
IO - speech.speak (12:47:27):
Speaking [('en_GB'), u'1.683 to 4.246 (2.563)'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:47:34):
Input: kb(desktop):[- speech.speak (12:47:34):
Speaking [LangChangeCommand ('en_GB'), u'Start: 5.100'](IO)
IO - inputCore.InputManager.executeGesture (12:47:37):
Input: kb(desktop):]
IO - speech.speak (12:47:37):
Speaking [('en_GB'), u'Finish: 5.100'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:47:41):
Input: kb(desktop):control+a
IO - speech.speak (12:47:41):
Speaking [('en_GB'), u'Select all'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:47:43):
Input: kb(desktop):space
IO - inputCore.InputManager.executeGesture (12:47:46):
Input: kb(desktop):[- speech.speak (12:47:46):
Speaking [LangChangeCommand ('en_GB'), u'Start: '](IO)
IO - inputCore.InputManager.executeGesture (12:47:49):
Input: kb(desktop):]
ERROR - scriptHandler.executeScript (12:47:49):
error executing script: <bound method SoundWindow.script_dropFinishMarker of <appModules.goldwave.SoundWindow object at 0x03E430D0>> with gesture u']'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 176, in executeScript
  File "C:\nvda extra\userConfig\addons\goldwave\appModules\goldwave.py", line 123, in script_dropFinishMarker
IndexError: list index out of range
IO - inputCore.InputManager.executeGesture (12:47:55):
Input: kb(desktop):control+NVDA+1
IO - speech.speak (12:47:55):
Speaking [('en_GB'), u'Selected channel: Channel information unavailable'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:47:59):
Input: kb(desktop):control+NVDA+2
IO - speech.speak (12:47:59):
Speaking [('en_GB'), u'Track length is unavailable. Please close and reopen the audio track.'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:48:03):
Input: kb(desktop):control+NVDA+3
ERROR - scriptHandler.executeScript (12:48:03):
error executing script: <bound method SoundWindow.script_announceAudioSelection of <appModules.goldwave.SoundWindow object at 0x03E430D0>> with gesture u'ctrl+NVDA+3'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 176, in executeScript
  File "C:\nvda extra\userConfig\addons\goldwave\appModules\goldwave.py", line 229, in script_announceAudioSelection
IndexError: list index out of range
IO - inputCore.InputManager.executeGesture (12:48:08):
Input: kb(desktop):control+alt+r
INFO - core.main (12:48:08):
Exiting

working version..

Starting NVDA
INFO - core.main (12:32:48):
Config dir: C:\nvda release candidates\userConfig
DEBUG - core.main (12:32:48):
setting language to Windows
INFO - core.main (12:32:48):
NVDA version rc-10562,7e7bc6f
INFO - core.main (12:32:48):
Using Windows version sys.getwindowsversion(major=5, minor=1, build=2600, platform=2, service_pack='Service Pack 3')

snip
IO - speech.speak (12:33:14):
Speaking [('en_GB'), u'real love.wav'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:33:19):
Input: kb(desktop):control+NVDA+1
IO - speech.speak (12:33:19):
Speaking [('en_GB'), u'Selected channel: stereo'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:33:22):
Input: kb(desktop):control+NVDA+2
IO - speech.speak (12:33:22):
Speaking [('en_GB'), u'Track length: 4:10.677'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:33:25):
Input: kb(desktop):control+NVDA+3
IO - speech.speak (12:33:25):
Speaking [('en_GB'), u'2.396 to 4.336 (1.940)'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:33:30):
Input: kb(desktop):space
IO - inputCore.InputManager.executeGesture (12:33:32):
Input: kb(desktop):]
IO - speech.speak (12:33:32):
Speaking [('en_GB'), u'Finish: 4.336'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:33:37):
Input: kb(desktop):control+NVDA+1
IO - speech.speak (12:33:37):
Speaking [('en_GB'), u'Selected channel: stereo'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:33:41):
Input: kb(desktop):control+a
IO - speech.speak (12:33:41):
Speaking [('en_GB'), u'Select all'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:33:42):
Input: kb(desktop):space
IO - inputCore.InputManager.executeGesture (12:33:44):
Input: kb(desktop):[- speech.speak (12:33:44):
Speaking [LangChangeCommand ('en_GB'), u'Start: 1.683'](IO)
IO - inputCore.InputManager.executeGesture (12:33:46):
Input: kb(desktop):]
IO - speech.speak (12:33:47):
Speaking [('en_GB'), u'Finish: 4.246'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:33:51):
Input: kb(desktop):control+NVDA+1
IO - speech.speak (12:33:51):
Speaking [('en_GB'), u'Selected channel: stereo'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:33:54):
Input: kb(desktop):control+NVDA+2
IO - speech.speak (12:33:54):
Speaking [('en_GB'), u'Track length: 4:10.677'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:34:01):
Input: kb(desktop):control+NVDA+2
IO - speech.speak (12:34:01):
Speaking [('en_GB'), u'Track length: 4:10.677'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (12:34:07):
Input: kb(desktop):control+alt+r
INFO - core.main (12:34:07):
Exiting

It may well be a weird quirk, but its puzzling,any enlightenment welcome.
 Just recording it here for ref.

**Comment by ehollig** [comment]
Is this still the case with the Goldwave addon?

**Comment by ehollig** [comment]
@Brain1Gaff, any updates on this issue?

**Comment by Brian1Gaff** [comment]
Ahem, nearly missed this, as I'm brian1gaff, not brain!
 Old ticket, no longer of relevance.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by ehollig** [comment]
Sorry about that @Brian1Gaff, it was a spelling error. it has been fixed. Closing as requested.
