### ISSUE TITLE
Emulate Backspace key is not possible in the brailiant by

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4776]
**Reported by leonardo.gleison on 2015-01-05 16:39**
HumanWare Brailiant bi is not emulating Backspace key when pressing dot 7 or space key + 7 in the Braille keyboard.

**Comment by leonardder** [comment]
I assume this is fixed now? cc @dkager

**Comment by dkager** [comment]
Neither Enter nor Backspace is explicitly defined in the driver.

**Comment by leonardder** [comment]
Shouldn't they be assigned by default since #2439 is implemented?

**Comment by dkager** [comment]
I am blatantly ignorant about braille input, but can test on this particular series of displays on Monday.

**Comment by leonardder** [comment]
[**@dkager**](https://github.com/dkager) commented on [21 okt. 2017 18:53 CEST](https://github.com/nvaccess/nvda/issues/4776#issuecomment-338416394 "2017-10-21T16:53:56Z - Replied by Github Reply Comments"):
> I am blatantly ignorant about braille input, but can test on this particular series of displays on Monday.

I hope you had a great Monday while testing this ;)

**Comment by dkager** [comment]
I cheated and tested this on a foggy Tuesday morning, as the leaves turned yellow then orange then red and began to fall in great cascades mourning summer. I ate bacon from one hand and deftly played a beautiful lute with the other. And it works now with the new braille input code.
