### ISSUE TITLE
Support Glossomathia programming language editor

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#478]
**Reported by Agent Golder on 2009-11-23 18:57**
It is an exampl and it's used at schools here in Greece to learn the basics of programming.
As toled me, it looks like a word proscessor... I'M attaching it to you and it would be nice if you make something.
I haven't tested it with Jaws yet but I heard it works fine...

**Comment by leonardder** [comment]
This is very specific software. It seems that NVDA doesn't read the contents of the multi line edit field, but you can get to the contents using the review cursor. Since this will probably never be fixed, I'd like to suggest a won't fix for this.

**Comment by jcsteh** [comment]
This would probably require application specific code to fix. Closing as won't fix, but happy to reopen if someone wants to investigate and provide a PR.
