### ISSUE TITLE
automatically report updates to crash report sending in Adobe Flash Player Firefox plugin

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4788]
**Reported by bhavyashah on 2015-01-10 20:28**
While playing a YouTube video, Adobe Flash Player plugin crashed, and while up and down arrowing, I accidentally discovered that there was a button that could allow me to send the crash report.
When I hit Enter there, and upped and won arrowed, the status had changed to Sending Report, and then after manual arrowing, it changed to Report Sent.
NVDA should have automatically reported these changes.

**Comment by leonardder** [comment]
Closing as invalid, since Flash isn't used in Youtube anymore. @bhavyashah, have you experienced this in other web pages as well in the recent past?
