### ISSUE TITLE
Braille driver for BraillePen Slim

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4802]
**Reported by Karol on 2015-01-14 11:27**
Braille driver for BraillePen Slim keyboard.

**Comment by Adriani90** [comment]
@ehollig could you please upload the attachment to this issue? Thanks.

**Comment by ehollig** [comment]
@Adriani90 the file has been added to https://github.com/nvaccess/nvda/issues/4802#issuecomment-155333026 or [braillePen.py.txt](https://github.com/nvaccess/nvda/files/2753370/braillePen.py.txt)

**Comment by jcsteh** [comment]
PR #5539 was opened for this. However, the author never addressed the review comments, so it was closed (https://github.com/nvaccess/nvda/pull/5539#issuecomment-415353888). I'm likewise closing this issue.
