### ISSUE TITLE
Report functions of touch keys in Input Help

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4807]
**Reported by bhavyashah on 2015-01-14 13:21**
On my laptop, above the built in keyboard, is a series of touch keys, whih aren’t physically pushed down, just tapped on. They perform a specific function, for which Input Help messages should be provided.

**Comment by leonardder** [comment]
@bhavyashah: Could you provide brand and type of your laptop? It is very unlikely that this can be fixed, as these keys are probably handled by the laptop on bios level. For example, if I press fn+1 on my laptop, the fan starts spinning continuously. NVDA is unable to report this.

@JCSTeh: I'm tempted towards a won't fix here, but may be you can give a more proper explanation of why this is probably not going to work?

**Comment by jcsteh** [comment]
@leonardder is correct: in most cases, the system does not send key presses for such keys, but instead triggers behaviour in a non-standard way. Sometimes, that behaviour does affect Windows (e.g. turning off WiFi), but that is triggered either in the hardware or handled by some custom application which doesn't provide a way for us to intercept it. It's also handled differently by each manufacturer. So unfortunately, this is not something we can support.
