### ISSUE TITLE
List Navigation in MS Word

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4810]
**Reported by netblue on 2015-01-14 14:41**
Hi all, menny times I work with documents that have a lot oof lists. It wood be really great if nvda could navigate these lists quickly perhaps thru browse mode.

**Comment by leonardder** [comment]
it would be nice if this could be implemented as part of #7409 for Office 2016+

**Comment by bhavyashah** [comment]
Do we want to restrict the scope of this ticket to single letter navigation for lists in Microsoft Word only, or should we broaden it to cover Outlook and Excel too while we are at it? Two questions:
* Assuming lists are very much a thing in an e-mail client, are L and Shift+L currently supported in Outlook?
* Are lists even relevant in a spreadsheet program like Excel?

**Comment by Adriani90** [comment]
For excel lists are not relevant. At least I didn't ever see a use case where you must navigate several lists in excel.

**Comment by Adriani90** [comment]
Closing in favor of #16999 which is filled with new template.
