### ISSUE TITLE
Speak Typed Words: NVDA pronounces decimals as whole number during Speak Typed Words, but reviewing the text later pronounces it correctly

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4812]
**Reported by bhavyashah on 2015-01-14 17:54**
Steps to reproduce
1 Type  for example '1.234'
2 Now hit the Spacebar, or any key that marks the end of the word and causes NVDA to speak the typed word (ensure that Speak Typed Words is enable NVDA + 3)
Result : NVDA says two hundred and thirty four. Now re-read the same text, and observe that NVDA reads the decimal values correctly as individual digits 'two three four'.
I am using the built in ESpeak while reproducing this issue.

**Comment by bhavyashah** [comment]
As noted by @jcsteh in https://github.com/nvaccess/nvda/issues/4812#issuecomment-155333224, there is no solution for the issue reported. In case others cannot come up with ways of solving this issue either, we'll probably need to close as a cantfix. @ehollig

**Comment by jcsteh** [comment]
I haven't come up with any solution to this and it seems no one else has either. Closing.
