### ISSUE TITLE
Unable to access the Word office 2013 password message window.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4822]
**Reported by Brendon22 on 2015-01-18 02:43**
Hello.

When loading a word document with a password  and the window that comes up and states for you to type your password in will not read with NVDA Friday Snap. All NVDA will state is unknown? Also are not voiced with a star, they are spoken out. This works in Office 2010. I am running Win 8.1 64-Bit. I get the following from the NVDA log viewer:

ERROR - api.setFocusObject (12:37:00)
Never ending focus ancestry: last object: None, unknown, window class bosa_sdm_msword, application name winword
ERROR - queueHandler.flushQueue (12:38:16):
Error in func _loadBufferDone from eventQueue. Please look into this. Thanks.

**Comment by bhavyashah** [comment]
According to the original author's https://github.com/nvaccess/nvda/issues/4822#issuecomment-155333318, this ticket is possibly related to another one concerning the reading of RTF files. Does anyone have any idea about which specific ticket is being referred to? This information may be useful in establishing association between such related and possibly duplicate tickets which would further improve our understanding of the actual scope of and grassroot cause of such behaviour.

**Comment by bhavyashah** [comment]
Possibly related to or a duplicate of #6871 (where more discussion seems to have taken place)

**Comment by Adriani90** [comment]
@Brendon22 are you stil having this issue?

**Comment by Adriani90** [comment]
@feerrenrut could you please test if this is still reproducible in Word 2013? Thanks.

**Comment by feerrenrut** [comment]
Yes, I can still reproduce it.

If I create a document, and choose "Protect Document" then "Encrypt with password".

When trying to reopen this document I am presented with a dialog, NVDA only announces "pane unknown". 
After trying to use object navigation to get more information NVDA froze / crashed.

**Comment by Adriani90** [comment]
I cannot reproduce in Word 2016 or Word 365. Support for MS Office 2013 will completely end on April 11, 2023. By that date all Office products older than 2013 will have reached end of life. Thus I am closing this issue as abandoned, but if you still have it with Office versions starting with 2016 or newer, please feel free to comment and we can reopen.
