### ISSUE TITLE
Virtual ribbon functionality in NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4844]
**Reported by supanut2000 on 2015-01-24 03:51**
Hi, sorry if this has been created once already, but I can't find any tickets relating to this feature when searching for 'virtual ribbon'.
Is it possible that the virtual ribbon, similar to the one in Jaws, could be implemented in NVDA? With this feature, the ribbon controls would behave like it was a menubar control.

**Comment by jcsteh** [comment]
While the experience is different, it is quite possible to navigate ribbons using the keyboard. See https://github.com/nvaccess/nvda/issues/7061#issuecomment-293170836 for some tips. Also, doing this provides an entirely different user experience for screen reader users and such alternative interfaces are prone to break as changes are made in applications. As such, this is not something we are considering for implementation in NVDA. Closing.
