### ISSUE TITLE
Firefox - in some edit fields, braille routing does not work

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4855]
**Reported by msuch on 2015-01-27 17:51**
This can be reproduiced on http://ixquick.com which is a search engine.
In the edit field where you enter your search, you'll notice that you can't route cursor if you want to fix a spelling error.
It happens here with Ff 35, NVDA 2014.4, Master and Next

**Comment by ehollig** [comment]
Can I have the Braille experts take a look at this issue?

**Comment by Adriani90** [comment]
note that ixquick does not exist anymore. Could you please provide another test website?

**Comment by Adriani90** [comment]
We did not get any updates since more than 2 years on this issue. I am closing it as abandoned. Please comment on it if you can reproduce it and we can reopen. Thanks.
