### ISSUE TITLE
μTorrent 3.4.2  (build 35702) [32-bit]: in tree view of main µTorrent window, every alternate tree view item isn’t read and is skipped while down arrowing, and the last tree focused view item is repeated and the second next tree view item is focused and read

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4860]
**Reported by bhavyashah on 2015-01-30 13:17**

Steps to reproduce
Download, install and open μTorrent 3.4.2  (build 35702) [32-bit].
Focus the main window’s tree view.
Arrow up/down the tree view.
Expected Result : Arrowing up/down will be done correctly and NVD will announce correct information.
Actual Result : \* Arrowing up/down will skip one item and take you to the next/previous tree view item, for e.g. pressing down arrow from item 1 will take you to item 3 and likewise
• On arrowing up/down alon with skipping an item will also make NVDA read the last focused item once and then the newly focused item, for e.g. pressing down arrow from item 1 will make NVDA read item 1 and then item 3
• Object navigation works almost correctly, apart from the behaviour that NVDA reads he tree view items that were skipped while arrowing as ‘tree view item x of y’, that is it reads the skipped tree view items without any label/name, simply its control type (that is a tree view item) and its item number of total items.
• JAWS skips items like NVDA does as well, but does not repeat the previously focused tree view item, simply skips and reads the newly focused item.

**Comment by leonardder** [comment]
@bhavyashah: Could you provide a status update?

**Comment by bhavyashah** [comment]
@leonardder Unfortunately, I do not use µTorrent anymore. Hence, I will be unable to provide a status update on this issue. However, if there are a bunch of µTorrent specific issues on the tracker (most of which would probably have been filed by me), I could probably seek assistance from an existing µTorrent user in testing these by asking on the NVDA Users e-group.

**Comment by mohdshara** [comment]
out of interest, have you found a better alternative to this? 

I can confirm that this is still the case though. NVDA would still skip items as described. but I can live with it, because if you do NVDA plus tab NVDA would read the correct label.

**Comment by Adriani90** [comment]
@mohdshara maybe the software bitcomet

**Comment by bhavyashah** [comment]
Since I lo longer use μTorrent, this seems to be the only open issue about μTorrent, this is quite likely an app issue rather than an NVDA one, and app interfaces typically change a lot over 8 years, I am happy for this ticket to be closed.
