### ISSUE TITLE
enhance documentation for Message Timeout in user guide

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4864]
**Reported by bdorer on 2015-01-30 22:56**
If you press any routing key on a NVDA message it will be dismissed. If you press a navigation key on the display the timeout starts new.

I think this should be noted in the userguide.

**Comment by bhavyashah** [comment]
CC @jcsteh

**Comment by Adriani90** [comment]
@bdorer I am not sure if this should really be documented. Because it depends may which keys you have assigned and I guess it can also depend on which braille display you use. We would need much more testing with several braille displays to see if it occurs systematically.
