### ISSUE TITLE
Crash during loading a config profile.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4866]
**Reported by driemer.riemer@... on 2015-01-30 23:22**
I think this is the appropriate crash dump. I don't know how to view it.  I was loading a config profile when it happened. It updated the bluetooth status on the braille display that was connecting waited like 5 seconds and then made the windows error sound and was gone. It seems no nvda-old.log was ever created.

**Comment by Adriani90** [comment]
It seems there was no discussion at all here. @derekriemer have you seen this behavior regularly? Or was it just one time? If it is no issue anymore then we could close it I guess.

**Comment by Adriani90** [comment]
I am closing this issue since there was no discussion on this issue since more than three years. If the problem still occurs, please comment on it and we can reopen.
