### ISSUE TITLE
Problem in AVG's configuration dialog

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#487]
**Reported by Agent Golder on 2009-11-30 07:44**
In the settings treeview, it just says "Treeview item" when moving through the options with cursor keys without reading each one.
I'M using the latest version of both AVG security and NVDA...

**Comment by leonardder** [comment]
As this ticket is over 7 years old, I assume that many things have been changed in AVG in this period. May be there are AVG users who can elaborate on this? May be this should just be closed, we can always reopen if the problem is still there.

**Comment by jcsteh** [comment]
Closing as invalid, since we don't have sufficient information at this point and this is very old.
