### ISSUE TITLE
NVDA Sluggish when reading Browse Mode elements with sapi4 as speech synthesizer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4881]
**Reported by brandon15 on 2015-02-04 14:07**
Hello,

For awhile now, I use NVDA with sapi4 voices. When I am using a sapi4 voice (it doesn't matter which ones), it almost always seems like there is a lag when navigating browse mode documents elements in Internet Explorer or Firefox.

Steps to reproduce:
1. Install a Sapi4 voice and select it in NVDA's synthesizer menu.
2. Open either Internet Explorer or Firefox, and go to a web site with links, headings, edit boxes and buttons (almost any web site).

For this example we will use www.nvaccess.org.
As you read the text with the up/down arrows, NVDA reads and responds normally. But as soon as the user hits a link, button, check box, combo box, radio button, or almost any sort of non-text element with the exception of graphic, there is a huge delay before NVDA reads the element. This is most noticible on a computer with some 1 or 2 gb of Ram, but is also noticable on 64 bit computers with 4 to 8 gb of ram.
To compare this, then switch over to eSpeak and navigate the same page. You will now notice that there is no lag.

This is extremely annoying, especially when using Gmail's basic html view and you hit the button that says more reply options in the quick reply area.

Thank you very much for your time and I look forward to any assistance you are willing to provide.

Thanks,

Brandon

**Comment by bhavyashah** [comment]
CC @jcsteh

**Comment by Brian1Gaff** [comment]
This sort of issue seems totally dependent on the synth used under sappi 4, 
for example the old illegal Viavoice has no issues that I can see.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by jcsteh** [comment]
Given that this appears to be voice specific as per the above comment, the fact that SAPI 4 is fading into obscurity and the age of this issue, closing as works for me.

**Comment by Brian1Gaff** [comment]
Yes the slow ones are the old Microsoft ones like Mary etc, as far as I can 
tell.
 Not tremendously slow but definitely sluggish.

Mind you the speech platform voices in that interface can be laggy but that 
I assume is doe to other reasons.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
