### ISSUE TITLE
NVDA will be more slow when run this kind of installer.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4887]
**Reported by vgjh2005 on 2015-02-05 12:26**
Hi:
Please download it from http://www.danielzingaro.com/superdeekout_setup.exe 
Run this installer,then press yes, then next. Press tab key at this time, NVDA will not say anything unless I switch to another window. Thanks!

**Comment by leonardder** [comment]
@vgjh2005: Could you please provide a status update?

**Comment by Adriani90** [comment]
it seems this author is not available anymore.

**Comment by Adriani90** [comment]
Testing with NVDA 2018.4 on Windows 10 1809 Update. It works correctly and NVDA reports everything even after pressing yes, next and then tab. I went through the whole installation process and I didn't have to switch the window. So closing as works for me.
