### ISSUE TITLE
Deadlock in NVDA Process Injection

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4888]
**Reported by camlorn on 2015-02-06 04:08**
Hi, 
    So.  Let me emphasize that this is a maybe still.  A pretty sure maybe, but a maybe nonetheless.  Anyhow. 

    I'm working with Pyglet, a framework for game development in Python.  It's OpenGL-based and includes a lot of stuff.  Merely importing the modules pyglet and pyglet.app in a Python script causes a deadlock which appears to be in NVDA process injection code.  I've attached tracebacks, as the debug log is long. 

My question at the moment is this.  What events specifically trigger NVDA's injection routines?  As far as I can tell, the importing of these modules runs nothing save some dll loading, yet two threads end up going through NVDA.  The latter appears to be something to do with the graphics driver.  And the end result is a deadlock involving LdrpLoaderLock and inprocThreadsLock, the former of which Google reveals little about and the latter of which is in NVDA. 

Any suggestions?  I'd love to solve this, as otherwise it's back to maintaining my own package that does less than the one I want to use.

**Comment by Adriani90** [comment]
closing as worksforme because it depends on the grafic driver and it is apparently fixed for @camlorn. Feel free to comment if this is not the case and we can reopen it.
