### ISSUE TITLE
Default rules in builtin.dic interferes with Chinese

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4889]
**Reported by tspivey on 2015-02-06 05:13**
STR:
1. Switch to vocalizer Chinese simplified or espeak mandarin.
2. Read: ma1, ma4

Expected:
The synth reads these as it should (these two seem to support pinyin plus tone numbers).
Actual:
The synth reads the characters, followed by the number. Disable the builtin dictionary and this works fine.

**Comment by bhavyashah** [comment]
@tspivey Is this issue still existent?

**Comment by larry801** [comment]
Pinyin plus tone numbers is only used internally by synthesizers. 
espeak never supported such feature.
Pinyin is also rarely used in daily communication in Chinese .
This issue is invalid and should be closed.

**Comment by Adriani90** [comment]
@tspivey do you still have this issue? Otherwise I am leaning towards closing it as suggested by @larry801.

**Comment by Adriani90** [comment]
Closing as abandoned as per comments above.
