### ISSUE TITLE
html: NVDA does not recognize the <Q> tag as a quote delimiter

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4893]
**Reported by msuch on 2015-02-07 15:55**
Normally, text placed between ```<q>``` tag should be detected as quoted, but it does not.
To chek this, go to
https://www.mozilla.org/access/qa/win-webcontent-jaws.html
and search for
This sentence is surrounded by the <q> quote html tag.”
Note that other screen readers don't see it as well, so I wonder if the tag is not deprecated.

**Comment by leonardder** [comment]
This works for me in all browsers. Note that text surrounded with ```<q>``` is placed between quotation marks, <q>like this</q> You need speak symbols set to most or all.
