### ISSUE TITLE
Outlook 2013-One cannot reach to the list of the found msgs in outlook in the find dialog.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4913]
**Reported by sumandogra on 2015-02-12 09:13**
Outlook 2013
One cannot reach to the list of the found msgs in the advanced find dialog.  It is very important at times to search a message in outlook received message folders.
Steps to reproduce:
1.	In Outlook 2013, press CTRL+SHIFT+Fto open advanced find dialog.
2.	Input some values to find a email.
3.	TAB to find now button and press ENTER.
4.	A list of found msgs appear.
5.	TAB around to reach out to the found msg list.  There is no way one can reach to the list.
Please note, this is an important function which is not usable with NVDA at present in outlook 2013.

**Comment by siddhartha-iitd** [comment]
Focus can be brought upon Search results in the grid using F6 key. After that, listed messages are read by NVDA. Not a bug.
