### ISSUE TITLE
rowgroup and colgroup scope attributes not recognized

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4917]
**Reported by paulbohman on 2015-02-13 20:24**
NVDA doesn't seem to recognize scope="colgroup" or scope="rowgroup" in data tables. See:

https://dequeuniversity.com/testsuite/tables/colgroup-rowgroup

**Comment by ehollig** [comment]
This seems to read perfectly in Firefox 54. CC @jcsteh

**Comment by leonardder** [comment]
Comfirmed. Closing as works for me.
