### ISSUE TITLE
Gesture for temporary disable all configuration profile triggers

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4935]
**Reported by leonarddr on 2015-02-20 12:47**
(Spun off ticket:4898#comment:17.)
This ticket deals with creating an unbound gesture for temporary disabling all configuration profile triggers. I have a text editing profile which reports several pieces of text information, which i'd like to disable at some times.

**Comment by leonardder** [comment]
[Moved the topic branch for this issue to Github](https://github.com/leonardder/nvda/tree/t4935)
