### ISSUE TITLE
Pressing UP, DOWN, LEFT and RIGHT ARROW in an Inno Setup script file reads incorrect information.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4936]
**Reported by munawar on 2015-02-20 18:25**
Using Inno Setup version 5.5.5, when in the Inno IDE, pressing UP / DOWN ARROW does not read the whole line if it does not fit on the screen. Further, pressing LEFT / RIGHT arrow to move across a line reports "space" and does not announce characters like it should.

**Comment by leonardder** [comment]
@munawar: Are you the munawar who opened this? If so, could you provide a status update?

**Comment by leonardder** [comment]
Closing due to lack of recent information. Please request a reopen if the described issue is still valid.
