### ISSUE TITLE
Config.conf: If an invalid value string is found for a setting, NVDA throws errors and does not reset the setting to its default value

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4941]
**Reported by nvdakor on 2015-02-23 06:40**
Hi,
Consider the following scenario: A user or an add-on changes a setting via config.conf dictionary, and it happens that the value type for a particular key (setting) is a string (validate.check("string"). If the user or an add-on provides an unexpected string value for a particular setting, NVDA will say "stop iteration" next time one attempts to open the preferences dialog which contains the just modified setting.

STR:
1. Try the following from the Python Console:

```
import config
config.conf[= "focused"
```

The expected strings are "focus" and "review", with the focus set as the default value.
2. Try opening the braille settings dialog.
Expected/ideal: NVDA will detect that an unexpected string value was encountered in tether to list and will revert to the default setting.
Actual: NVDA throws stop iteration exception with that exception not being handled.

Short term solution: for affected settings (such as tether to setting in braille settings), provide a try block that catches and reverts the setting to factory defaults. This means one needs to consult the config module to locate the default string values and do:

```
try:
    # Iterate through values.
except StopIteration:
    config.conf[section]("braille"]["tetherTo"])[setting] = defaultValue
```

Long term solution: in ConfigObj, one can specify a list of options in conficspec. This will force people or code to be restricted as to which value strings are acceptable. In addition, a check should be made when presenting a setting which has strings for values to make sure unexpected values are caught and dealt with (preferably to restore default value for that setting).
Thanks.

**Comment by leonardder** [comment]
cc @josephsl

**Comment by Adriani90** [comment]
@josephsl, I guess this is still the case. Right? Maybe it should be considered further while moving to Python 3.

**Comment by josephsl** [comment]
Hi, or rather, when we use ConfigObj 5.1.0 features. CC @JCSTeh

**Comment by Adriani90** [comment]
Now that configobj 5.1.0 is integrated, maybe there are some features which would help to solve this.
cc: @feerrenrut

**Comment by josephsl** [comment]
Hi,

Try config.conf["keyboard"]["keyboardLayout"] = "classic". With this set, keyboard layout combo box value will not be selected from keyboard settings panel. This behavior, while not that great, is an improvement over iteration issue I reported almost nine years ago. Threfore, I think we can close this with a new issue to be created to deal with combo box value issue.

Thanks.
