### ISSUE TITLE
Adobe Flash Support not working in NVDA 2015.1

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4946]
**Reported by GatorCountry on 2015-02-24 10:57**
Adobe Flash support has been excellent up until the last 2014 version released. In Firefox or IE, when opening a standard website with a Flash object, pressing Space in the "Embedded Object" would launch a Flash window from which a user could press a Play button to start a video. In 2015.1, navigating with arrow keys inside the object only produces the word "Blank". This is occurring on multiple websites including SiriusXM's web player and a video streaming site with content from the Ooyala video player. Thank you for your prompt response to this issue.

**Comment by ehollig** [comment]
This probably requires fixes from Adobe. Adobe has announced that Flash is deprecated, thus will no longer be developed actively. Closing
