### ISSUE TITLE
E-mail Clients Should be Mentioned in Browse Mode Section.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4949]
**Reported by ateu on 2015-02-25 12:46**
As well as in web browsers, it's possible to use the browse mode features in e-mail clients, such as Thunderbird and Windows Live Mail/Windows Mail, including elements list, quick navigation keys, find, etc.
Therefore, I think such applications should be mentioned where are listed the applications which supports browse mode.
I think this is important, as many people don't know this, and they don't use this important and useful features in this applications.

**Comment by leonardder** [comment]
Thunderbird is already mentioned here, Windows (live) mail is discontinued software. Furthermore, there is a clear audio indication when browse mode is triggered, even in application which aren't listed in the user guide. Closing as won't fix.
