### ISSUE TITLE
NVDA reads 1,,2 as 1 for German

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4956]
**Reported by bdorer on 2015-03-01 16:13**
If someone types 1,,2 (one coma coma two) by accident using German NVDA reads only 1. We in Germany use coma as decimal point. If you try this with NVDA set to english and 1..2 this isn't reproducable.
Is their a typo in the German language file?

**Comment by ehollig** [comment]
Closing, as this appears to be resolved in ESpeak 1.49.1
