### ISSUE TITLE
NVDA isn't able to detect skype message window I think

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4964]
**Reported by bdorer on 2015-03-08 12:15**
A german user reports NVDA isn't able to announce the first, second message, etc. I'll attach his log.
**Blocked by #4972**

**Comment by Adriani90** [comment]
@bdorer, @k-kolev1985, @jcsteh can you reproduce this in last skype version?

**Comment by Adriani90** [comment]
@k-kolev1985 I am trying to reproduce this issue but cannot. If this is not an issue in Skype 8, I would suggest to close it because the interface changed significantly.

**Comment by leonardder** [comment]
Closing this, since Skype has been entirely rewritten.

**Comment by leonardder** [comment]
Closing this, since Skype has been entirely rewritten.
