### ISSUE TITLE
adding an option to report border color

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4965]
**Reported by Sukil on 2015-03-08 15:37**
Sometimes, web and document authors use borders to emphasizing purposes (for instance the selected option among several possibilities). This is often done by changing the color of the border, but NVDA currently doesn't report this information.

**Comment by leonardder** [comment]
Border colours can now be reported for excel cells. It would help if we had an example of something that has borders to see what NVDA reports in the current situation.

**Comment by Adriani90** [comment]
@Sukil could you please help us reproduce such an issue with an example document? Thanks.

**Comment by sukiletxe** [comment]
I've searched issues today and found this one. The issue in my specific case weren't borders, but rather the few colors NVDA recogniced. So in the end it worked for me.

**Comment by CyrilleB79** [comment]
The initial reporter of this issue (@sukiletxe) has indicated that their issue was solved; thus I'll close this issue.

If @sukiletxe or someone else has a similar unresolved issue, please open a new ticket. Thanks.
