### ISSUE TITLE
interpret #d0ffd0 color hex as green instead of white

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4970]
**Reported by Sukil on 2015-03-09 12:31**
Currently, the hex color d0ffd0 is interpreted as white instead of green, and this causes confusion (particularly when it is used for selection purposes and it's surrounded with white). This problem may happen too with other colours (in MS Word I get descriptions witch don't match when selecting a color and when reading the text. 
By the way, ticket #4965 which was posted yesterday was part of this problem but I found out that it won't make a difference.

**Comment by jcsteh** [comment]
Covered by #4984.
