### ISSUE TITLE
NVDA does not report status of messages in Outlook 2010

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4971]
**Reported by andrewd on 2015-03-10 21:52**
NVDA reports when a message is unread.  It does not report when a message has been read, replied to or forwarded.

**Comment by feerrenrut** [comment]
@michaelDCurran This was assigned to you a long time ago, was there some progress on this? Can I unassign it from you?

**Comment by michaelDCurran** [comment]
@feerrenrut: No progress was made. Originally all MS Office bugs were assigned to me. Feel free to take it.

**Comment by leonardder** [comment]
I'd really appreciate this to be fixed, so let me know whether I can be of any assistance.

**Comment by ivnc** [comment]
An Spanish user asked NVDA.es about this and says that, with the last NVDA version, I suppose, she can't know if a message is marked as replied or forwarded. In addition another related issue is open (#6911). Any progress on this? Can the issue be solved?

Thanks.

**Comment by leonardder** [comment]
I'm afraid this can't be fixed for Outlook 2010 and older. Where Outlook 2013 and above expose the replied to or forwarded status using the UIA value, Outlook 2010 does not. For Outlook 2010, name and value properties just seem to expose the same.

We can not retrieve replied to or forwarded information from the object model, as that triggers a security warning in Outlook 2010.

Closing this as can't fix.
