### ISSUE TITLE
NVDA Announcing Spelling ?Errors in Chrome

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4975]
**Reported by ateu on 2015-03-13 13:05**
Hi all

As well as it's possible in Mozilla Firefox and now in Internet Explorer, NVDA would be able to announce spelling errors in chrome.

Furgive me if this is not a problem in NVDA.

**Comment by jcsteh** [comment]
This has now been implemented in Chrome. Note that "Play sound for spelling errors while typing" doesn't currently work. That's due to a Chrome bug which I've just filed as [issue 640479](https://bugs.chromium.org/p/chromium/issues/detail?id=640479).
