### ISSUE TITLE
Sometimes when moving through emails in Windows Live Mail NVDA will crash.  It is still doing so in NVDA 2015.1.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4978]
**Reported by dbeaver888 on 2015-03-17 19:28**
NVDA crashes and creates a dump while moving through emails in Windows Live Mail.  It most often happens if I tab into a list such as Inbox and then press home to go to the top of the list.  Once at the top of the list if I press enter NVDA sometimes crashes and restarts.
This also occasionally happens just while cursoring through a list of emails.  When this happens it most often happens immediately after deleting an email via the delete key.
It does not always occur so it has been hard to capture the issue.

**Comment by leonardder** [comment]
Windows Live Mail is unfortunately discontinued. Note that for example, Mozilla Thunderbird is a well functioning alternative. Closing as won't fix.

**Comment by leonardder** [comment]
That is to say, A crash is somewhat more serious than some other issues gregarding WLM. @Brian1Gaff, do you recall this issue? I'm happy to reopen this if people have additional details, though it is not very likely that this can or will be fixed.

**Comment by ruifontes** [comment]
As far as I know, this problem does not exist anymore...

About WLM, my comment is, look how many tickets about problems and 
enhancements were not solved...

Rui Fontes, still using WLM!


-----Mensagem Original----- 
De: Leonard de Ruijter
Data: 17 de julho de 2017 19:26
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Sometimes when moving through emails in Windows 
Live Mail NVDA will crash. It is still doing so in NVDA 2015.1. (#4978)



That is to say, A crash is somewhat more serious than some other issues 
gregarding WLM. @Brian1Gaff, do you recall this issue? I'm happy to reopen 
this if people have additional details, though it is not very likely that 
this can or will be fixed.
