### ISSUE TITLE
no formatting info is available  with INSERT+F in notepad

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4983]
**Reported by sumandogra on 2015-03-18 10:44**
No formatting info is available with INSERT+F.  NVDA announces no formatting information.  This sometimes is useful for a user.

Steps to reproduce:
1.  Open notepad and write some text.
2.  Press INSERT+F to get the fond information.  NVDA announces no formatting information.

**Comment by leonardder** [comment]
Formatting information in notepad is useless, since it is a plain text editor. There is actually a font and a font size, but this is tied to notepad and not to the content. Closing as invalid.
