### ISSUE TITLE
Unable to play a media file in Microsoft PowerPoint 2013

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4988]
**Reported by pranavlal on 2015-03-21 02:33**
I am unable to activate media when I am in slide show mode.
1. On a slide of a presentation, add media. This can be a sound file from your computer or a video.
2. Activate slide show mode using shift+f5 so that you start at the current slide.
3. Navigate around the slide with the arrow keys.

Try keys such as alt+p to play the media. Nothing will happen.
Note:
After inserting the media, you can navihgate to the alt+ text option in the format picture task pane and add an alt tag to the image to make it easier to find the clip. NVDA will speak the alt text but if you hit the spacebar on it, the media clip will not play.

**Comment by bhavyashah** [comment]
Confirmed using PowerPoint 2010 and NVDA 2017.3 on a Windows 8.1 system. I added an audio file from my computer on the Title slide itself, successfully played it while editing by pressing Spacebar on the object NVDA reports as "audio", without adding any alternative text for the audio (if alt text can even be added for audios in the first place). As reported by the original author of this ticket, NVDA reports the slide as empty in Slideshow mode and I am unable to play the audio.
@Qchristensen Could you please test and report whether PowerPoint 2016 exhibit this behaviour also? Also, does any work-around come to mind to access media in PowerPoint's (at least 2010 and 2013) Slideshow mode?

**Comment by Qchristensen** [comment]
Reading the [Keystrokes for PowerPoint page](https://support.office.com/en-us/article/Use-keyboard-shortcuts-to-deliver-your-presentation-1524ffce-bd2a-45f4-9a7f-f18b992b93a0#bkmk_controlvideo) it seems to treat online media (eg youtube videos) differently to offline media.  The keystrokes offered in that article only work with offline video.

In fact, what I found for both online and offline video, was if you get to the slide with the video (or audio), press TAB to move to the media, and then press ENTER to play it and again to pause.  For online video it at least reports it as "Web video" (when I used a video from YouTube).  On online videos, you can also press spacebar to launch the video in your browser.  For offline video, as well as using ENTER, you can press alt+p to play / pause.  Note that for offline media, nothing is announced when the focus moves to it.  Visually it does display a play button and progress bar on the video / audio.

You can add alt text and description to audio / video by selecting it and from the context menu choosing "Format video" (or "Format picture" for an audio file, for reasons known only to Microsoft :)), however this is simply read out when the slide loads along with the rest of the text, and again, nothing is read when you move the focus to the media itself.

**Comment by feerrenrut** [comment]
@Qchristensen @bhavyashah if you are happy for me to do so, I will close this issue as "worksforme"
