### ISSUE TITLE
The standard colors category is not being spoken in the font colors dialog box in Microsoft Excel 2013..

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4990]
**Reported by pranavlal on 2015-03-21 03:51**
The standard colors category label in the font color dialog box is not being spoken when I move through the colors using the arrow keys. To duplicate this, do the following.
1. Navigate to the "font colors" split button and activate it.
2. You will be in a list of colors.
3. Arrow up and or down to reach the "more colors" item.
4. Hit the up arrow key once to get to the "standard colors" catgeory.

This category label is not being spoken with nvda. Jaws does speak it.

Note:
I use the term "category label" in a generic sense. I do not know technically what the "standard colors" text is in the dialog or if this is a jaws feature.

**Comment by leonardder** [comment]
@pranavlal: Is this still reproducible?

**Comment by ehollig** [comment]
Closing, as requested by the original author in https://github.com/nvaccess/nvda/issues/4990#issuecomment-377486698
