### ISSUE TITLE
Review modes: let review modes be changed automatically when switching between apps

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4994]
**Reported by nvdakor on 2015-03-23 21:04**
Hi,
Possible spin-off from a ticket on binding review modes to configuration profiles:
Some members of the NVDA users list report that the behavior of review cursor commands change when switching between review modes. For example, when one issues read current line via review cursor (Numpad 8 on desktop layout) while object and screen review modes are active, NVDA announces current line on the current element versus the current line on the display screen, respectively. Also, when switching between apps, current review mode will be active, thus one will need to switch to the desired review mode while using the newly focused program.
Thus users propose the following:
- When switching to different programs, if one was using screen review, switch to object review automatically.
- Clarify user guide section on review modes by adding a note that behavior of some review cursor commands change when one switches review modes.
  Thanks.

**Comment by leonardder** [comment]
cc @josephsl

**Comment by Adriani90** [comment]
I think this could be hard for beginners to get used to. I would still propose to improve object navigation and screen review. That is, to make theese review modes as similar as possible to browse mode. And we should give them more priority in tutorials and documentation. At a later stage an automatic switch between review modes could be implemented. But in my view they are too different and would strongly confuse new users who are trying to learn every review mode step by step.

**Comment by Adriani90** [comment]
I am closing this one in favor of #7749 which proposes a less intrusive option for locking the review mode. Once that is implemented, people can still discuss if doing it automatically when switching to an app or not.
