### ISSUE TITLE
On the attachments page for attaching a file to a ticket, the brows... Button is labelled as Button?

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5002]
**Reported by Brendon22 on 2015-03-26 20:05**
On the attachments page for attaching a file to a ticket, the brows... Button is labelled as Button?

**Comment by bhavyashah** [comment]
The NVDA project has moved on to Github. Since this ticket concerns Internet Explorer (a relatively unimportant browser now that Edge is on the rise) and more specifically Trac (which we no longer use), please close this issue. @jcsteh @leonardder

**Comment by ehollig** [comment]
This issue concerns Trac, which NVDA no longer uses. Closing
