### ISSUE TITLE
NVDA does not report if there are speaker notes on a slide and does not give any way to read them

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5015]
**Reported by pranavlal on 2015-04-02 11:29**
When in slide show view or in the object presentation layer, NVDA does not report on the presence of speaker notes. 

In addition, it does not give any way to read these notes from within slide show view.

**Comment by ehollig** [comment]
Closing, as it sounds that this issue has been resolved from https://github.com/nvaccess/nvda/issues/5015#issuecomment-155336267
