### ISSUE TITLE
NVDA + MathPlayer 4 + Firefox reports SVG islands as "MathML error"

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5018]
**Reported by kennpetri on 2015-04-02 18:51**
This issue applies to the custom build housed at Design Science for support of MathPlayer 4 beta (version try-t4673-10720,5202e97).

SVG islands get reported as MathML (with "MathML error" being reported, repeatedly). 

In addition, neither the SVG title nor desc are read aloud (possibly because the SVG is interpreted as MathML?)

http://wac.osu.edu/mathtest.html

**Comment by Adriani90** [comment]
Ok the author seems not to be available anymore and the link provided does not lead to the svg which would let us reproduce this issue. I will close this one.
