### ISSUE TITLE
add a way to copy rendered web content

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5028]
**Reported by Sukil on 2015-04-09 20:14**
Currently, the selection and copying in webpages copies the text in the virtual buffer of NVDA. Maybe some other command or a toggle could be added to copy the actual rendered HTML, as if NVDA was not running.
Thanks.

**Comment by leonardder** [comment]
Closing as duplicate of #5354, which has already been triaged.
