### ISSUE TITLE
nv speech player; How phonemes defined in "data.py"?

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5030]
**Reported by taghavi on 2015-04-10 19:12**
I try use nv speech player for research about Persian TTS.
I need add a new phoneme to data file of nv speech player.
But there is no document about it! And it is different from eSpeakedit and Praat!
Please explain:
1. What program used to extract parameters of individual phonemes?
2. What is the full name of these parameters that stated as abbreviations?
Thanks in advance

**Comment by ehollig** [comment]
A gentle nudge to @michaelDCurran or @jcsteh on this question.

**Comment by jcsteh** [comment]
This isn't the right place for this question; nvda-devel is a better place.  That said, nvSpeechPlayer (as opposed to speechPlayerInEspeak) is not being actively maintained, so this isn't likely to get any attention. Closing.

**Comment by ehollig** [comment]
Ah, thank you for the clarification. I got the two mixed up. And for anyone who browses this in the future, here is link to the [NVDA-Devel email list](https://sourceforge.net/p/nvda/lists/nvda-devel/).
