### ISSUE TITLE
Starting with Firefox 37 there is more of a delay with speech when typing on the Web with typing echo enabled

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5033]
**Reported by dgoldfield on 2015-04-13 08:27**
When using previous versions of Firefox, typing text on the Web, such as using this particular form to file this ticket, produced instant feedback when typing mode was enabled. The response was nearly instantaneous, as it is with standard word processing software. Starting with Firefox 37.0.1 I am noticing more of a delay between a keypress and when speech reads the key which was typed.

**Comment by jcsteh** [comment]
Mozilla believes this to be fixed, so closing. Please comment if the problem persists.
