### ISSUE TITLE
sometimes NVDA does not report battery time remaining information

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5045]
**Reported by bhavyashah on 2015-04-21 17:09**
At certain times, when I press NVDA + Shift + B, NVDA simply reports the battery remaining information, i.e. 35%.
However, it doesn’t report the time remaining such as x hours and y minutes.
I am able to consistently reproduce this behaviour at present but at other times, this features works according to what it claims to do.
Note: The test environment (below) has never changed between the occurrence of two behaviours and I haven’t customized the System Tray in any form. The System Tray battery status icon displays the information (battery and time emaining) correctly, however, its NVDA’s battery reporting keystroke (NVDA + Shift + B) that announces incomplete information.
Test Environment
Windows 7 Ultimate 32 bit
NVDA 2015.1
Note: The log does not show anything suspicious such as an error, warning or traceback.

**Comment by ehollig** [comment]
@bhavyashah, is this still an issue? As @jcsteh suggested in https://github.com/nvaccess/nvda/issues/5045#issuecomment-155337853, it's possible your system sometimes provides this information and other times it does not.

**Comment by bhavyashah** [comment]
I think it is. Please give me a week or so to actively test this issue and share any updated findings I may have in this regard.

**Comment by leonardder** [comment]
I recall that I read somewhere that the information provided by NVDA sometimes differs from the info in the system tray icon, due to NVDA using an older, XP compatible method to retrieve battery information. Now that XP support has been dropped, a possible fix would be updating the battery script to the [newer WMI based API. There also seems to be an even newer UWP API that can be used.

**Comment by bhavyashah** [comment]
@Adriani90  Probably not. Since I cannot seem to have experienced thiss recently to the best of my memory, coupled with how minor this issue truly is, I would be happy for this ticket to be safely closed for now. We can always reopen and revisit this if this bug crops up again.
