### ISSUE TITLE
Start Menu: report status of Start Menu search automatically

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5046]
**Reported by bhavyashah on 2015-04-21 17:12**
Steps to reproduce
Press Ctrl + Esc or simply the Windows key to launch the Start Menu.
Your default focus lies on the search edit box.
Type a set of keywords.
Quickly enter screen review and at the top you will find the text ‘Searching...’ which indicates that the Start Menu search is in progress.
The Start Menu search either completes yielding results or at the same location displays ‘No items match your search.’.
Proposal - The status of the Start Menu search, i.e. Searching..., Search Complete and No items match your search should be reported automatically eliminating the requirement of manually checking the status through screen review.
Test Environment
NVDA 2015.1
Windows 7 Ultimate 32 bit
Note: I haven’t modified or customized the Start Menu in any form or by any means, therefore, this feature request should be reproducible and applicable to everyone.

**Comment by ehollig** [comment]
I tend to agree with @jcsteh. If NVDA announced "Searching..." and then announced, "Search complete", prior to announcing the focused item, this would get really verbose. Thoughts from others? CC @josephsl

**Comment by josephsl** [comment]
Hi,

Windows 10 specific changes were implemented as of NVDA 2017.3 (#6241), not in a position to investigate Windows Vista as support for it has ended as of this year. Live region change is a tempting solution (#7281 and friends), but only if the control supports it. As I outlined above (as nvdakor), it leads to event flooding, possibly leading to people not hearing results in time to react to it, or worst, select the wrong result.

I'll close this for now. Please reopen if and only if sufficient (and compelling) justification is there. Thanks.

**Comment by lukaszgo1** [comment]
For me announcing 'searching' and 'search complete' makes no sense, however 'no items match your search' is quite useful, and for sighted users the fact that nothing has been found is obvious visually, so adding this one might be nice.

**Comment by josephsl** [comment]
Hi,

This is possible in Windows 10 Settings app - will need to investigate this for Windows 7 and 8.x provided that it can be done and does not introduce negative user experience.

Thanks.

**Comment by josephsl** [comment]
Hi,

I'm a bit hesitant to implement this suggestion for older operating systems (Windows 7 and 8.1).

Thanks.

**Comment by josephsl** [comment]
Hi,

2022 update: the Windows 10 Settings app version is now available as of NVDA 2021.3.

Anyone would like to take care of this for older operating systems?

Thanks.

**Comment by lukaszgo1** [comment]
I **may** take a look at this at some point. In general this seems to be a good candidate for a P4 which should be closed **only** when NVDA drops support for anything older than Windows 10

**Comment by Adriani90** [comment]
This decision should be taken by NV Access officially since this issue requires a change on NVDA side. Microsoft ended support for Windows 8.1 completely in 2020, and other Windows versions older than that are also not supported anymore.

**Comment by seanbudd** [comment]
@Adriani90 - we will not be doing work on Windows 8.1 and Windows 7, as they are expected to be dropped in 2024.1, when updating Python.

**Comment by Adriani90** [comment]
@seanbudd thanks for the update, i am closing this one as abandoned in this case as I did with other issues that also affected Windows 8.1.
I guess an official statement from NV Access regarding the timeline for dropping the support would help also to raise awareness for this in the community.
