### ISSUE TITLE
NVDA reads the complete contents of the element with role=tabpanel on focusing an input field within despite the name given by author through aria-labelledby=ID.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5047]
**Reported by gandalf on 2015-04-22 06:38**
I tested it with Firefox and Chrome (Versions from April 2015).

The Form is contained in a role=dialog. The dialog has more tabs, so the currently visible contents is in role=tabpanel. There are several input fields there.
1. Focus goes to the first input field in the role=tabpanel.
2. After speaking the correct name of the "dialog" and of the current "tabpanel" NVDA continues to speak all the contents of the element with role=tabpanel before announcing the name and the value of the input field with focus.

Sample Code:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Sample Dialog</title>
</head>
<body role="application">
  <div class="FscOverlayApp FscHasTabs" id="A5" role="dialog"
    aria-labelledby="FscPageTitleA5" data-ctrl="A5">
    <span tabindex="0" class="FscAcc"
      onkeydown="return vappfocus.doCatch(event)"
      onkeyup="return vappfocus.doCatch(event)" data-iscatch="true"></span>
    <div class="FscOverlayBg FscScrollbarRight">
      <div class="FscOverlayHeader" id="FscOverlayHeaderA5">
        <h3 id="FscPageTitleA5">My Teamroom (Teamroom): Edit</h3>
        <div class="FscErrorContainer" id="FscErrorA5" aria-live="assertive"></div>
      </div>
      <div class="FscBranches" id="FscPageBrA5">
        <div tabindex="0" class="FscBt FscBackBtn FscBtNoImg" role="button"
          onclick="return vappoverlay.toggleSmall()">More</div>
        <div tabindex="0" title="Cancel Alt+A" class="FscBt FscBtNoImg"
          id="FscBr0A5" role="button" onclick="return vapp(0)">Cancel</div>
        <div tabindex="0" title="Apply Alt+P" class="FscBt FscBtNoImg"
          id="FscBr1A5" role="button" onclick="return vapp(1)">Apply</div>
        <div tabindex="0" title="Next Alt+W"
          class="FscBt FscBtNoImg FscDefBtn" id="FscBr2A5" role="button"
          onclick="return vapp(2)">Next</div>
      </div>
      <ul
        class="FscTabContainer FscFontLarge FscFontInvert FscDots FscDotsPNG"
        id="FscTabContainerA5" role="tablist" aria-labelledby="FscPageTitleA5"
        onclick="return vappctl.cbk(event, 'TAB')">
        <li id="FscTab0A5" role="tab" aria-selected="false"
          aria-describedby="FscAccEnter" data-i="0">Teamroom</li>
        <li id="FscTab1A5" role="tab" aria-selected="false"
          aria-describedby="FscAccEnter" data-i="1">Logos</li>
        <li id="FscTab2A5" role="tab" aria-selected="false"
          aria-describedby="FscAccEnter" data-i="2">Templates</li>
        <li id="FscTab3A5" role="tab" aria-selected="false"
          aria-describedby="FscAccEnter" data-i="3">Orphan Objects</li>
        <li tabindex="0" id="FscTab4A5" role="tab" aria-selected="true"
          aria-describedby="FscAccEnter" data-i="4">General</li>
        <li id="FscTab5A5" role="tab" aria-selected="false"
          aria-describedby="FscAccEnter" data-i="5">Remarks</li>
        <li id="FscTab6A5" role="tab" aria-selected="false"
          aria-describedby="FscAccEnter" data-i="6">Versions</li>
        <li id="FscTab7A5" role="tab" aria-selected="false"
          aria-describedby="FscAccEnter" data-i="7">Security</li>
      </ul>
    </div>
    <div tabindex="-1" class="FscOverlayScroll" id="FscOverlayScrollA5">
      <div class="FscOverlayContent FscOverlayPad" id="FscOverlayBodyA5">
        <div class="FscTabBody FscOverlayPad" id="FscTabBodyA5"
          role="tabpanel" aria-labelledby="FscTab4A5">
          <div class="FscPageTitle FscDotsBtm FscDotsPNG">
            <h2>General</h2>
          </div>
          <div class="FscGridBlock" data-ctrl="fl11_0">
            <div class="FscGridLabel FscLabelSel" id="grl_objname12_A5">Name</div>
            <div class="FscGridData FscDataSel" id="grd_objname12_A5"
              data-ctrl="11_0">
              <input name="f11_0" class="FscInput FscMax"
                aria-labelledby="grl_objname12_A5" type="text" size="70"
                maxlength="254" value="My Teamroom">
              <div title="Help Ctrl+F1" class="FscCtxInfo" role="button"
                aria-describedby="grl_objname12_A5" aria-label="Help"
                onclick="vappflatlist.help(this)">
                <img alt="" src="../tmp/a/i/COO.1.1.1.16703.svg">
              </div>
            </div>
            <div class="FscGridLabel" id="grl_objsubject1_A5">Subject</div>
            <div class="FscGridData" id="grd_objsubject1_A5" data-ctrl="11_1">
              <input name="f11_1" class="FscInput FscMax"
                aria-labelledby="grl_objsubject1_A5" type="text" size="70"
                maxlength="254" value="">
              <div title="Help Ctrl+F1" class="FscCtxInfo" role="button"
                aria-describedby="grl_objsubject1_A5" aria-label="Help"
                onclick="vappflatlist.help(this)">
                <img alt="" src="../tmp/a/i/COO.1.1.1.16703.svg">
              </div>
            </div>
            <div class="FscGridLabel" id="grl_objcreatedby_A5">Created
              by</div>
            <div class="FscGridData" id="grd_objcreatedby_A5">
              <div id="grs_objcreatedby_A5" role="listbox"
                aria-labelledby="grl_objcreatedby_A5">
                <span tabindex="0" class="FscOL" id="FscVO11_2A5"
                  role="option" aria-labelledby="FscVO11_2A5" draggable="true"
                  data-args="COO.1.506.1.5731;COO.1.506.2.1226;;COO.1.1.1.89;;;0;7;69">Baumann0015
                  Christina</span>
              </div>
              <div title="Help Ctrl+F1" class="FscCtxInfo" role="button"
                aria-describedby="grl_objcreatedby_A5" aria-label="Help"
                onclick="vappflatlist.help(this)">
                <img alt="" src="../tmp/a/i/COO.1.1.1.16703.svg">
              </div>
            </div>
            <div class="FscGridLabel" id="grl_objcreatedat_A5">Created
              on/at</div>
            <div class="FscGridData" id="grd_objcreatedat_A5">
              <div id="grs_objcreatedat_A5" role="textbox"
                aria-readonly="true" aria-labelledby="grl_objcreatedat_A5">22.04.2015
                08:30:50</div>
              <div title="Help Ctrl+F1" class="FscCtxInfo" role="button"
                aria-describedby="grl_objcreatedat_A5" aria-label="Help"
                onclick="vappflatlist.help(this)">
                <img alt="" src="../tmp/a/i/COO.1.1.1.16703.svg">
              </div>
            </div>
            <div class="FscGridLabel" id="grl_objchangedby_A5">Last
              Change by</div>
            <div class="FscGridData" id="grd_objchangedby_A5">
              <div id="grs_objchangedby_A5" role="listbox"
                aria-labelledby="grl_objchangedby_A5">
                <span tabindex="0" class="FscOL" id="FscVO11_4A5"
                  role="option" aria-labelledby="FscVO11_4A5" draggable="true"
                  data-args="COO.1.506.1.5731;COO.1.506.2.1226;;COO.1.1.1.91;;;0;7;69">Baumann0015
                  Christina</span>
              </div>
              <div title="Help Ctrl+F1" class="FscCtxInfo" role="button"
                aria-describedby="grl_objchangedby_A5" aria-label="Help"
                onclick="vappflatlist.help(this)">
                <img alt="" src="../tmp/a/i/COO.1.1.1.16703.svg">
              </div>
            </div>
            <div class="FscGridLabel" id="grl_objmodifiedat_A5">Last
              Change on/at</div>
            <div class="FscGridData" id="grd_objmodifiedat_A5">
              <div id="grs_objmodifiedat_A5" role="textbox"
                aria-readonly="true" aria-labelledby="grl_objmodifiedat_A5">22.04.2015
                08:31:40</div>
              <div title="Help Ctrl+F1" class="FscCtxInfo" role="button"
                aria-describedby="grl_objmodifiedat_A5" aria-label="Help"
                onclick="vappflatlist.help(this)">
                <img alt="" src="../tmp/a/i/COO.1.1.1.16703.svg">
              </div>
            </div>
            <div class="FscGridLabel" id="grl_objclass1_A5">Object Class</div>
            <div class="FscGridData" id="grd_objclass1_A5">
              <div id="grs_objclass1_A5" role="listbox"
                aria-labelledby="grl_objclass1_A5">
                <span tabindex="0" class="FscOL" id="FscVO11_6A5"
                  role="option" aria-labelledby="FscVO11_6A5" draggable="true"
                  data-args="COO.1.1001.1.324003;COO.1.506.2.1226;;COO.1.1.1.83;;;0;7;69"><img
                  title="Object Class" class="FscI" alt=""
                  src="../tmp/a/COO.1.1001.1.262505.svg">Teamroom</span>
              </div>
              <div title="Help Ctrl+F1" class="FscCtxInfo" role="button"
                aria-describedby="grl_objclass1_A5" aria-label="Help"
                onclick="vappflatlist.help(this)">
                <img alt="" src="../tmp/a/i/COO.1.1.1.16703.svg">
              </div>
            </div>
            <div class="FscGridLabel" id="grl_objcategory_A5">Category</div>
            <div class="FscGridData" id="grd_objcategory_A5" data-ctrl="11_7">
              <table class="FscFix" role="group"
                aria-labelledby="grl_objcategory_A5" cellspacing="0"
                cellpadding="0">
                <tbody>
                  <tr>
                    <td class="FscMax"><div class="FscSB" id="11_7A5"
                        role="combobox" aria-expanded="false"
                        aria-labelledby="grl_objcategory_A5"
                        onkeydown="return vappsb.keyDown(event, this)"
                        onclick="vappsb.open(event, this)" data-ctrl="11_7"
                        data-args=";COO.1.506.2.1226;;COO.1.1001.1.179540;;;;7;71">
                        <span tabindex="0" role="textbox"
                          aria-labelledby="grl_objcategory_A5"></span>
                        <div class="FscSBButton" role="button"
                          aria-label="Expand List">
                          <img class="FscLink" alt=""
                            src="../tmp/a/FSCVAPP_1_1001/combodown.gif">
                        </div>
                      </div></td>
                    <td><span class="FscBtBranch"><a title="Find"
                        role="button"
                        onclick="return vappbranch.ctrl(event,0)" href="#"><img
                          class="Fsc16" alt="Find"
                          src="../tmp/a/COO.1.1.1.8431.svg"></a></span></td>
                  </tr>
                  <tr>
                    <td colspan="2"></td>
                  </tr>
                </tbody>
              </table>
              <div title="Help Ctrl+F1" class="FscCtxInfo" role="button"
                aria-describedby="grl_objcategory_A5" aria-label="Help"
                onclick="vappflatlist.help(this)">
                <img alt="" src="../tmp/a/i/COO.1.1.1.16703.svg">
              </div>
            </div>
            <div class="FscGridLabel" id="grl_objaddress_A5">
              <span lang="de">Fabasoft</span> Cloud ID
            </div>
            <div class="FscGridData" id="grd_objaddress_A5">
              <div id="grs_objaddress_A5" role="textbox" aria-readonly="true"
                aria-labelledby="grl_objaddress_A5">COO.1.506.2.1226</div>
              <div title="Help Ctrl+F1" class="FscCtxInfo" role="button"
                aria-describedby="grl_objaddress_A5" aria-label="Help"
                onclick="vappflatlist.help(this)">
                <img alt="" src="../tmp/a/i/COO.1.1.1.16703.svg">
              </div>
            </div>
          </div>
        </div>
        <div tabindex="0"
          class="FscSupport FscScrollbarRightPos FscFontInvert"
          id="FscSupportA5" role="button"
          onmousedown="return vappevent.cancelBubble(event)"
          onclick="return vapptelemetry.feedbackDialog()">
          <h3>Support</h3>
        </div>
        <span tabindex="0" class="FscAcc"
          onkeydown="return vappfocus.doCatch(event, true)"
          onkeyup="return vappfocus.doCatch(event, true)" data-iscatch="true"></span>
      </div>
    </div>
  </div>
</body>
</html>

**Comment by Adriani90** [comment]
@gandalf is this issue still reproducible with NVDA 2018.4.1 and last browser versions?

**Comment by Adriani90** [comment]
We do not have an update from the author since more than 4 years. Closing as abandoned.
Please comment on this issue and we can reopen it if needed. Thanks.
