### ISSUE TITLE
NVDA (almost) hangs in Visual Studio Community Edition

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5052]
**Reported by parham on 2015-04-24 07:13**
I'm not completely sure about the term I should use to describe what happens to NVDA, but here goes.

After a while of using the Visual Studio Community Edition 2013, NVDA stops responding to keys such as control, caps lock, and so on. Also, pressing keys such as down/up arrow quickly doesn't interrupt speech like it should, and instead queues each string after what is already being spoken.

**Comment by leonardder** [comment]
Labeling this p4, as Community 2017 is now the most recent version. Having said that, if this issue also applies to community 2017, we can reconsider the priority.

**Comment by Adriani90** [comment]
@parham could you please give us an update regarding this issue? Are you still having it?

**Comment by leonardder** [comment]
Community 2013 has been superseded by 2015, 2017 and 2019. Given its age and the difficulty to maintain support for all these versions of Visual Studio, I'm closing this.
