### ISSUE TITLE
say all and graphics on more than one line

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5055]
**Reported by JamaicanUser on 2015-04-25 03:19**
When performing a say all in browse mode, when the cursor encounters a graphic with alt text that spans multiple lines, NVDA says graphic for each line. Example? The JAWS logo.

**Comment by Adriani90** [comment]
I think this also occurs if you press down arrow to read the grafic alt text line by line. This is also the case for links and other elements which are on multiple lines.

**Comment by Adriani90** [comment]
cc: @jcsteh

**Comment by Adriani90** [comment]
closing in favor of #14335 which contains more detail and the issue template is accordingly filled.
