### ISSUE TITLE
Keys on Braille Sense U2 disabled after using as display

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5063]
**Reported by cskchao on 2015-04-27 19:12**
When using the HIMS Braille Sense U2 as a display, the F2 and F3 keys become disabled for use on the device itself. This remains even after quitting both NVDA and terminal mode. For example, one is not able to get back into terminal mode using the F3+S command unless they reset the unit.

**Comment by leonardder** [comment]
This is an interesting issue. I assume you tested this with other screen readers?

**Comment by cskchao** [comment]
If memory serves, the issue only seems to present with NVDA, much to my
disappointment. Tested with JAWS/Window-Eyes/Mac and iOS VoiceOver

**Comment by cskchao** [comment]
just a quick note to say that this issue also presents itself when using BrailleBack with Android devices. Perhaps a BRLTTY/HIMS issue in that case.

**Comment by leonardder** [comment]
@cskchao: Is this still the case with the new Hims driver?

**Comment by cskchao** [comment]
@leonardder yes, I'm afraid so. At least over USB, this remains the case.

**Comment by leonardder** [comment]
I'm afraid there's nothing else we can do other than close this as a needs external fix. We usually keep issues open until an external fix has been provided, however in the case of these displays that are not actively maintained by Hims any more, it is very unlikely that there will be provided a fix for it.
