### ISSUE TITLE
NVDA turns on but will not talk

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5064]
**Reported by tkaupla on 2015-04-27 19:38**
I recently downloaded NVDA on this computer (the latest version) and it worked. But when I tried it a second time, it will only make the audible noise that it turns on, but then will not read anything to me.  I tried to redownload it and I'm having the same problem.

**Comment by ehollig** [comment]
There is not enough information in this ticket to replicate the issue. Unless we can contact the original author for further clarification and steps to reproduce, closing as worksforme
