### ISSUE TITLE
Track changes in Word 2013

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5066]
**Reported by amenaide on 2015-04-28 14:54**
When I delete text while track changes is enabled in Word 2013, the deleted text is not reported.

Steps:
1. Open new document.
2. Write the lines
"This is my boring example text.
I needed another line of text to make my point."
Turn on track changes pressing ctrl+shift+e.
Delete the Word "boring" by pressing ctrl+del and insert "random" instead.
3. Read the line using the arrow keys.
NVDA will say
"This is my [deleted](revised) random [reviesed view](not) example text.
Apologies if I got the English NVDA strings wrong, I am using a German copy. 
This makes it appear as if the word "random" has not been inserted but deleted.
4. Put the cursor in the space before the word "random". Press arrow right. NVDA will say "revised deleted time, author, r" making it appear as if the r has been deleted. 
5. Delete the "ed" in the second line of text so it says "I need another line of text to make my point."
6. Activate review mode pressing ins+space and go to beginning of text.
7. Press a. NVDA says "space" instead of announcing the deleted word "boring". 
8. Press a again. NVDA correctly reports that the word "random" has been inserted.
9. Press a once more to jump to the deleted "ed". NVDA will say "space".
I think reporting track changes doesn't work as it should with Word 2013.
If I press insert+f7, NVDA announces the information correctly, but this way it is not possible to see the changes in context, so I hope the other methods of reading chnges can be fixed for Word 2013, too.

**Comment by ehollig** [comment]
@michaelDCurran, can this type of information be retrieved from Word and reported as requested in https://github.com/nvaccess/nvda/issues/5066#issuecomment-155338582?

**Comment by michaelDCurran** [comment]
Extra information for property changes can be seen in the Elements list when selecting annotations.

**Comment by ehollig** [comment]
Thank you @michaelDCurran. Sounds like everything is settled here from the comment provided in https://github.com/nvaccess/nvda/issues/5066#issuecomment-323615836. Closing as worksforme
