### ISSUE TITLE
Document the ability to read charts in the application specific settings part of the users guide.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5071]
**Reported by driemer.riemer@... on 2015-05-01 13:27**
This is currently not documented, and an overview of how to read a chart with excel would probably be a useful thing to have in the users guide. Also, noting that cropped or overlapped data is spoken might be useful to document as well.

**Comment by bhavyashah** [comment]
@derekriemer Could you please respond to https://github.com/nvaccess/nvda/issues/5071#issuecomment-155338688? As the author of the Microsoft Excel training module from NV Access, @Qchristensen's inputs would also be valuable.

**Comment by Qchristensen** [comment]
The commands to move around charts are actually Excel keystrokes, not NVDA specific ones.  I have had many comments on the Word and Excel training material on how people never knew many of those features were accessible, but as Jamie said, if we start documenting one keystroke which isn't NVDA specific in the user guide, where do we stop?  Indeed, the Word and Excel training modules do cover a lot more Microsoft Office keystrokes rather than NVDA ones.

Certainly noting how NVDA reports cropped or overflowing data is potentially within the scope of the Use Guide.

**Comment by derekriemer** [comment]
I feel mentioning "you can arrow around charts" is not going to far, and to be fair, most users who aren't top notch computer users are going to get frustrated with not knowing its possible (or knowing the training material exists). You could put something in the guide like "many more keystrokes and features are available in exccel which help screen reader users, see our excel module for more info."

**Comment by bhavyashah** [comment]
I agree with @derekriemer's https://github.com/nvaccess/nvda/issues/5071#issuecomment-320151294 with reference to addinng information about the official Basic, Word and Excel training modules available in the NVDA User Guide itself. Many more users will be driven to check out the modules and potentially purchase them. And in any case, I do think it is important to have a more directly visible mention of all official training material from NV Access within either the User Guide document or as a dedicated item in the Help submenu, the former seeming more preferable to me.

**Comment by Adriani90** [comment]
@derekriemer is the bullet point in 10.2.2 actually enough for new users? It provides a quick method to rach the diagram via elements list and says that you can navigate it by pressing arrow keys.

**Comment by bhavyashah** [comment]
@derekriemer  This is a friendly reminder to consider responding to https://github.com/nvaccess/nvda/issues/5071#issuecomment-458338454.
@Qchristensen  Could you please share your thoughts on mentioning the existence of the Word and Excel training material under their respective User Guide sections?

**Comment by Qchristensen** [comment]
Thanks @bhavyashah, yes I definitely agree including a mention to the training modules is definitely worthwhile

My suggestions would be:

- Mention "Basic Training with NVDA" either in Section 1. Introduction, or Section 4, Getting Started with NVDA.
- Mention the Word / Excel / PowerPoint (shortly) in the relevant parts of section 11. Application Specific Features.

**Comment by Adriani90** [comment]
The links to the NV Access shop and coresponding training modules are now part of the user guide in section 2.6. Closing this as fixed.
