### ISSUE TITLE
make it easier for nvda users to find tutorials and the community

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5072]
**Reported by driemer.riemer@... on 2015-05-01 13:52**
Hi, I have a few suggestions for nvda as per what I have noticed from several people who I know talking to me. These aren't things that are necessarily high priority, but might help to make usage of nvda easier.
## Tips

Currently, a user would have to find out about the nvda community website by going to nvaccess.org and finding it. It would be useful to have a get support or nvda community or other type of link in the nvda help menu. This could be a submenu with the following options. 
1. Visit the nvda community webpage.
   this activates the link at  http://community.nvda-project.org/
2. Nvda tutorials and self-help.  
   This activates the link at http://community.nvda-project.org/wiki/Guides
3. Connect with nvda users around the world, and get technical support.  
   This activates the link for http://community.nvda-project.org/wiki/Connect

Also, when a download completes, maybe the user could be sent to a getting started using nvda webpage.

Put an learn how to use nvda link on nvaccess.org, which sends the user to the nvda guides page.

The links in the help menu could link to the specific nvda communities for their language group, (this may be unpheasable for translators to design).

**Comment by bhavyashah** [comment]
@derekriemer Could you please follow-up with @jcsteh with regards to https://github.com/nvaccess/nvda/issues/5072#issuecomment-155338711? If Derek agrees, we should be able to safely close this ticket. @ehollig

**Comment by derekriemer** [comment]
I think this can be closed, but I do want to state again that it is way to difficult to find things if you are a beginner. I'd prefer the link on nvaccess.org to somehow link to all the important project links, because many users will struggle to realize that they have to click through from github to the wiki (On a separate github repo). It's at least 2 clicks to get to the wiki, after clicking the community link. Maybe we point at the nvda community repo first, or at least put a notice on the readme that a wiki is available for users at this link.

**Comment by jcsteh** [comment]
It'd probably make sense to link to the Community Wiki somewhere on the NV
Access "Get Help" page.

**Comment by Adriani90** [comment]
After the redesign of the webpage, it seems that there is a link under "get help" which is called "find out more". This link leads already to the connect wiki on github, where users can find all information needed to subscribe to the users list etc.
Moreover, at the bottom of the nv access website there is a link to the main github page for NVDA.

I am closing this issue also in favour of #4033.
