### ISSUE TITLE
Microsoft Excel: NVDA does not handle font and font size comboboxes in Cell Format Multi-Tab Dialog

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5076]
**Reported by msuch on 2015-05-04 17:05**
Hi. In Excel, the combo box used to change the font in the "Cell Format" is not appropriately reported. 
Steps to reproduce: 
1. Open a new excel sheet and activate the context menu. 
2. Arrow to then press Enter on "Cell format". 
3. In the multi-tab dialog that displays choose the Fonts tab. 

Synptom: When arrowing the font list, they change but they're not spoken by NVDA, unless NVDA+arrow-up is pressed. Same goes for the font sizes on the next control that's reached through the tab key. 

The colors tab, within the aforeesaid dialog is reported but it is too verbose. 
Happens with: NVDA stable and Master 11017,7b4a196 Windows 7 32 bits SP1, Microsoft Office Excel 2003 and 2010. All up-to-date. 
Thanks!

**Comment by bhavyashah** [comment]
CC @Qchristensen

**Comment by Adriani90** [comment]
@msuch, @josephsl, @bdorer can you still reproduce this issue? I have tested in MS Excel 201 and 2016 and this seems solved now.

**Comment by Adriani90** [comment]
Closinga s works for me. Please comment on this if you still have the issue and we can reopen it. Thanks.
