### ISSUE TITLE
First character after the cursor is dropped for Unicode not in braille table

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5077]
**Reported by dkager on 2015-05-05 14:54**
This issue occurs when the cursor moves onto Unicode characters that aren't defined in a braille table (#499, #537). Probably a liblouis bug.

To reproduce, use NVDA with the default braille table (en-us-comp8.ctb) and default braille settings. Open Notepad and enter the following line:
French uses the letter é a lot.

In braille this is rendered as:
French uses the letter '\x00e9' a lot.

The problem:
- If the cursor is to the left of the charcode everything looks fine.
- If the cursor is on the charcode (i.e. on the first apostrophe) the character just after the charcode is removed.
- If the cursor is to the right of the charcode everything looks fine again.

For example, if the cursor is on the charcode, the following space is removed:
French uses the letter '\x00e9'a lot.

This becomes a bigger problem when the charcode appears in the middle of a word.

Finally, while on this subject, has there been a final decision on whether or not to print an arbitrary indicator instead of the hex code? I'd prefer that, especially if it was a user setting.

**Comment by Adriani90** [comment]
@dkager the Liblouis issue seems fixed. Is this issue still present?
cc: @Andre9642

**Comment by Adriani90** [comment]
I am closing this issue since we don't have any updates since years on this and the Liblouis issue seems solved. If you are having this issue still, please feel free to comment on this one and we can reopen. Thanks.
