### ISSUE TITLE
Unable to find status bar in Windows Live Mail

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#508]
**Reported by Agent Golder on 2009-12-15 11:41**
How do we learn when does it finish checking and how many new messages we have?
Is there any status line like in Outlook Express or something els?
It says "No status bar found" when pressing the related command!...

**Comment by leonardder** [comment]
Live mail seems to be deprecated now and Thunderbird is probably a better alternative, so how about closing this?

**Comment by ruifontes** [comment]
If we go that route, XP is also deprecated, and we don't want to kill 
support to it, don't we?

Still many people using Windows Live Mail...

I will agree with this when NVDA provide a very good support for Mail of 
Windows 10...

Rui

-----Mensagem Original----- 
De: Leonard de Ruijter
Data: 7 de junho de 2017 20:11
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Unable to find status bar in Windows Live Mail 
(#508)



Live mail seems to be deprecated now and Thunderbird is probably a better 
alternative, so how about closing this?

**Comment by jcsteh** [comment]
We don't want to "drop" support for anything unnecessarily, no, but there's also no point in us working on additional support for something which is now obsolete. Closing.
