### ISSUE TITLE
browse mode does not start when using chromeless firefox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5082]
**Reported by finn.turner on 2015-05-07 22:43**
when using Firefox like so: `Firefox -chrome protocol://domain.tld/path/to/file.extention`, Firefox starts in a chromeless mode in which only the webpage is shown. However, NVDA does not turn on browse mode for the Gecko document on Screen

**Comment by leonardder** [comment]
This works for me, but I'm not sure whether my Firefox is entirely chromeless. @DerekRiemer, would you like to give this a try as well?

**Comment by derekriemer** [comment]
wo, that's a thing, neat hang on

**Comment by derekriemer** [comment]
these directions do not bring up a chromeless ff for me

**Comment by MarcoZehe** [comment]
First I'm seeing of this bug, and never actually used this technique myself. If it brought up a chromeless window once, but does not now, I guess this bug is obsolete. Note that it's very likely that this was an experiment at some point which got stopped and the capability removed.

**Comment by derekriemer** [comment]
I'll close as invalid for now, if anyone rediscovers this, reopen please.
