### ISSUE TITLE
certain controls not gaining focus when firefox window is restored

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5098]
**Reported by chrisw on 2015-05-19 13:56**
With the firefox window restored and the browser not in full screen mode:
1.  Go to http://gmail.com nad log in.
2.  Click on hte compose button.  The new message dialog seems ot come up, but focus is not set to it and there seems to be no way to set focus to it.  With the winow maximized or in full screen mode (hit f11) with the window restored, things work as expected.
I have seen this on windows 7 and 8.1.

**Comment by ehollig** [comment]
this sounds similar to #2913. This could be an issue as described in https://github.com/nvaccess/nvda/issues/2913#issuecomment-155303761, however, when I click the compose button in standard or basic HTML view of Gmail, focus is properly placed in the To field. As we are unable to contact the original poster, as far as I am aware, closing as invalid
