### ISSUE TITLE
Major Issues Reading Pdfs

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5099]
**Reported by tweyen on 2015-05-19 18:41**
For a year and a half, we have been creating accessible pdfs for our client, who needs to control and lock the content of their pdfs when posted to the web. We experienced a some glitches prior to 2015.1, however, since the update to 2015.1, we have encountered some major new glitches:

1 reading "link" every couple of words when no links exist
2 reading "link" within alternate text for images
3 reading a header from another section before continuing on in the same area (occurs only in a complete read through)
4 link destination error
5 reading "header X" in the middle of a sentence (occurs only in a complete read through)

Attached are some screenshots numbered to correspond with the issues I listed above.

We are setting up our documents in Adobe InDesign and exporting to accessible pdfs. We have not changed how we are setting up documents  nor have we encountered any of these problems prior to 2015.1. It appears there is not much discussion about how NVDA reads pdfs but we'd like to get that going because there are significant related issues and we are not finding any support. 

Heather Skillicorn

**Comment by bhavyashah** [comment]
@jcsteh From https://github.com/nvaccess/nvda/issues/5099#issuecomment-155339203, I infer that the scope of this ticket is not specific and thus remains unclear. Could you and @josephsl please take another look at this ticket so as to ascertain what the reported issue or requested feature exactly is?

**Comment by Adriani90** [comment]
I am closing this as abandoned, we didn't get any updates from the initial author fro a very long time. Please comment if you are still facing this issues and we can reopen.
