### ISSUE TITLE
Wrong Greek letter translations in zh-tw.ctb

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5106]
**Reported by school510587 on 2015-05-24 19:51**
Hi, developers,

My language is zh_TW, and I use zh-tw.ctb for Braille display.
However, there are 3 problems in translation of Greek letters.
This problem is actually about liblouis, one of NVDA's dependency.
I've tried to report it on liblouis\* website, they suggested that I send my patch to liblouis-liblouisxml@freelists.org
But I didn't get any response... So I describe my problem and the solution (a patch) here.
Could you help me fix it (or communicate liblouis*)?
Thanks in advance.

I'm using NVDA 2015.1 on XP.
1. On Greek letter Φ (uppercase Phi, unicode 03A6), NVDA shows 46-1257 dots.
   However, according to Greek Braille translation (gr-gr-g1.utb), Phi is 124.
   So the correct translation is 46-124, where 46 is a prefix for us to distinguish Greek letters from English letters.
2. On Greek letter φ (lowercase phi, unicode 03C6), NVDA shows 46-125 dots.
   For the same reason that is stated in the previous problem, the correct translation is 46-124.
3. On Greek letter θ (lowercase theta, unicode 03B7), NVDA shows its internal code directly.
   its correct translation is 46-1456, but this entry is missing in zh-tw.ctb.

Sorry, I'm new to this website, and please forgive my unstructured report.

The following is the link of my original bug report on liblouis*
http://liblouis.org/bugs/Wrong_Greek_alphabets_translation_in_zh-tw.ctb/

I checked "I have files to attach to this ticket", but I couldn't find the "..." or "Browse" button to upload my patch.
So I put it in the following link:
http://mail3.batol.net/~school510587/0001-Fix-greek-character-translations-in-zh-tw.ctb.patch

**Comment by dkager** [comment]
liblouis has long since been upgraded, this can be closed.
