### ISSUE TITLE
report comments option in input gestures dialog

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5108]
**Reported by JamaicanUser on 2015-05-27 02:37**
In the Document formatting section of the Input gestures dialog, there is an option to toggle the reporting of comments. It is, however, not an option in the Document formatting dialog. Is it that the entry in the Input gestures dialog will be removed, or the option will be added to the dialog as a new option.

**Comment by leonardder** [comment]
Topic branch for this issue is now [here](https://github.com/leonardder/nvda/tray/t5108/) on github
