### ISSUE TITLE
braille in arabic does not display while writting

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#511]
**Reported by orcauser on 2009-12-16 23:12**
install arabic as a writing language, open word/wordpad, switch to arabic braille table and arabic writing and start typing, the braille does not display until we go down to the next line and then up again, cant be sure at the moment, but i think cursor movement is also wrong.

**Comment by leonardder** [comment]
I wonder whether there Arabic users who can confirm this. Since there haven't been comments on this issue for seven years, I think it's safe to close this. People who still experience this can request to reopen it, or open a new issue themselves.

**Comment by mohdshara** [comment]
I don't quite understand the problem here, but there's no computer Arabic braille table yet, so of course you can't input Arabic text using a braille display. Since the lack of such a table isn't NVDA scope I would vote to close as needs external fix.

**Comment by jcsteh** [comment]
If I understand correctly, I think the reporter meant switching to Arabic braille output and the Arabic PC keyboard layout. So, the question is: if you open Wordpad and start typing in Arabic, do you see braille output?

**Comment by mohdshara** [comment]
Confirmed.

this seems specific to notepad, wordpad, and windows explorer edit boxes. steps to repro:
1. open any of those apps and start typing a word in Arabic.
2. expected, you should see each character as you type it.
3. what happens is that you don't see any character on your display  until you type a space. and that's only for the first word that you type.
4. for any typed word after that, you might see a character or 2 of each word before the  space.

NVDA 2017.2, Windows creator's 10 update, and a bronto Braille display.

@hatoon-fel

**Comment by mohdshara** [comment]
forgot to mention that if you move your cursor with the arrow keys, before typing a space causes the characters that you had typed so far to show.

**Comment by feerrenrut** [comment]
@mohdshara Thanks for investigating, just to confirm its not a more general bug: if you follow the same steps with English input on your setup, then the braille is output character by character as you type?

This is the behaviour I get (for English keyboard input, and Arabic keyboard input) in next Version: `next-14098,66f26bb2` regardless of the state of the `Speak typed characters check box` in the `Keyboard Settings dialog`

**Comment by mohdshara** [comment]
Hi. yes, if you type English, characters will appear instantly as soon as you type them. This behavior only happens if you type Arabic text. I tried this with 2 Braille displays just to be sure it's not a hardware issue. Is there anything else you want me to do to help track down this bug?
