### ISSUE TITLE
extra quick nav keystrokes

### ISSUE THREAD

**Issue by nvdaTrac** [nvaccess/nvda#5112]
**Reported by JamaicanUser on 2015-05-28 14:14**
For some time, the quick navigation keystrokes in their current state have been unchanged, and new possibilities have not been explored. I propose the following:
1. A key to move to the next/previous clickable element, even if reporting clickable elements is turned off.
2. A key to move to the next paragraph or block of text. I have seen this implemented in an add-on on the French add-ons web site, (NVDA extension global plugin), but the add-on is somewhat unusable as the translation is poor. This would prove useful for persons who just want to read non-link plain text.
3. A keystroke to move to the next division/region. Again, the above mention add-on has a good implementation of this.
Maybe these commands can be unbound by default? Trust me, this is of good use to a power user like myself.

**Comment by jcsteh** [comment]
Clickable quick nav is covered by #124. The others are addressed or not feasible; see [above](#issuecomment-155339413).
