### ISSUE TITLE
Performance decrease after upgrading NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5114]
**Reported by elliott94 on 2015-05-28 18:41**
Since upgrading NVDA from an older snapshot and using the Next branch in production for several weeks, I've noticed a significant performance hit while browsing through lists of files/folders in Explorer. Whilst I would previously receive speech feedback upon moving the focus almost instantaneously, it now takes around half a second before the new content is announced. This observation was made with Next snapshot 12021,7c7aad1 in combination with eSpeak. I feel it relevant to point out that whilst I have noticed performance degradation in other applications also, Explorer lists are definitely an area where this can be experienced the most.

Has anyone else noticed anything similar? This is with a Windows 7 X64 setup.

**Comment by bhavyashah** [comment]
@eliot94 Are you still experiencing these performance deficiencies?

**Comment by elliott94** [comment]
No; happy for this to be closed unless anybody else thinks otherwise.

**Comment by ehollig** [comment]
Closing because of https://github.com/nvaccess/nvda/issues/5114#issuecomment-320516420. If a problem similar like this still persists, please open a new ticket.
