### ISSUE TITLE
Duplicate feedback whilst reading edit fields in Firefox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5115]
**Reported by elliott94 on 2015-05-28 18:55**
From memory I believe that this particular issue may have been reported several years ago, but I've been unable to find any relevant information.

Whilst using Firefox 38.0.1 in combination with the latest NVDA snapshot (Next 12021,7c7aad1), I've noticed that whilst editing form content in Focus Mode duplicate information is presented. There doesn't seem to be a set of conditions where this behaviour can be observed; whilst moving the focus to the next/previous line or character the previous information for the relevant line or character is given. I've noticed this on multiple machines running Windows 7 Home Premium X64.

**Comment by leonardder** [comment]
@elliott94: Could you provide a status update for this issue?

**Comment by elliott94** [comment]
I'm afraid so - behaviour is still as described. Am I correct in thinking that this is more of a Firefox bug, though?

**Comment by Adriani90** [comment]
@elliott94 I am testing several website in Firefox 66.0.2 where such issues occured before and now I cannot reproduce it anymore. I am testing with NVDA 2019.1. Are you still seeing this issue? Thanks!

**Comment by elliott94** [comment]
Happy to close for now; I haven't seen this for a while.

**Comment by Adriani90** [comment]
Thanks for confirming. Just comment on it if you have this issue again and we can reopen it.
