### ISSUE TITLE
AVG options are not accessible

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5120]
**Reported by HungarianLaller on 2015-05-29 11:34**
AVG user interface is accessible, if the self defence is disabled.
If not, the user interface is not accessible either.
Problem is with the options panel. The tree view is readable, but, unfortunatly, the statuses of the buttons are not reported in NVDA.
It is not reported, that is checked, unchecked, the radio buttons are not sayd properly, see attachment.

**Comment by Adriani90** [comment]
@HungarianLaller the interface has changed significantly in the last aVG version. Are you still having this issue?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years, closing as abandoned. If you still have this issue, please comment and we can reopen.
