### ISSUE TITLE
NVDA not reading the labels or text in boxes when arrowing through Charactor setup or alias boxes in VipMud

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5123]
**Reported by patjk on 2015-05-29 22:13**
Hi,
I'm testing VipMud version 2 where this issue still happens, but it carried over from version 1.1. I'm reporting on Davids behalf since he's not familiar with how NVDA grabs things from the screen.

In VipMud version one or 2, if you go and add a character from the character setup/connect menu, you'll notice that NVDA will detect the boxes and read any text if any is in the boxes already, but you can't arrow or review text, and the text label for the box is not spoken. This also occurs in the triggers and aliases functions from the edit menu.

I have mailed David about this, and he can't seem to figure out why this happens. Screen readers such as Jaws and Windo-eyes have no issue. Any ideas?

**Comment by Adriani90** [comment]
@patjk is this still an issue with last NVDA and last Vipmud version?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years. I am closing as abandoned. Please comment on this if you are still having this issue and we can reopen.
