### ISSUE TITLE
Single Character Navigation Keys

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5128]
**Reported by MoonShiner on 2015-06-01 19:26**
I am running Windows8.1, using NVDA 2015.2.

I have a USB connected keyboard.  None of the Single Character Navigation Keys seem to work, the only way to move through a Web page is with the tab key.

Using IE11 as the browser.

Any suggestions?

**Comment by ehollig** [comment]
Do we have any additional information from the person who created this issue? CC @jcsteh

**Comment by jcsteh** [comment]
Closing, as we don't have an easy way to find the reporter and this issue is now two years old without activity. We can reopen if the reporter provides the details requested.
