### ISSUE TITLE
Windows 10 and Cortana: Handle listening events e.g. silencing NVDA while dictation or interaction with Cortana is taking place

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5131]
**Reported by nvdakor on 2015-06-02 06:08**
Hi,
One of the most exciting features in Windows 10 is Cortana, a personal digital assistant making its debut on the PC platform in 2015. It operates similar to services such as Siri and Google Now, and mobile screen readers (especially VoiceOver) cooperates well with these services.
While Cortana is listening, it sends listening events (via UIA), which I believe NVDA does not handle now. Thus I propose that we provide a handler to handle listening event so that NVDA could be silenced while a user is talking to Cortana or doing dictation.

Design: The design for the listening event handler will be similar to other events such as gain focus, sleep mode and so on. Specifically:
- When services such as Cortana fires listening event, NVDA will enter a special mode that restricts its output activity (speech, braille, etc.).
- Once the listening event is done or when Cortana or other services fire an event notifying NVDA that it has finished listening, NVDA should resume normal activity. In case Cortana is speaking something, NVDA should not perform any speech output activity.

Benefits:
- This would mirror user experience when using iOS: when Siri is active, VoiceOver does not interrupt this activity.
- This allows Cortana and similar services to interact with users such as speaking, asking questions, more listening and so on.
- By letting NVDA cooperate with Cortana through listening event handling routines, users will be able to appreciate the fact that NVDA does a good job of working with other apps to bring best user experience when using dictation apps in Windows 10 and beyond.

Issues to be solved:
- Can we port this to earlier versions of Windows, say Windows 7 and 8.x? If these OS's raise listening events, then yes, otherwise this will be on Windows 10 and later.
- What if user is waiting for a speech act from NVDA, say instant chat messages, update notifications and so on that cannot wait until listening/interaction event is finished? A possible workaround would be to provide a setting to control listening event behavior.

Thanks.

**Comment by leonardder** [comment]
cc @josephsl

**Comment by josephsl** [comment]
Hi, not exactly, as the fix for this involves name change event, and only after Windows 10 App Essentials does SearchUI app module listen to name change events and react accordingly (note that Cortana’s UI has changed drastically in recent Windows 10 releases). Thanks.
