### ISSUE TITLE
toggle for reporting background progress bars.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5145]
**Reported by Mohamed on 2015-06-07 23:02**
So, I'd like to see in a future version the ability to have a shortcut key to toggle the reporting of background progress bars. Because I often find that I would like to listen to a progress bar in the background for a while e.g. when copying files, audio editing, etc; but I only want to hear the progress bar temperarily, but I would not like this to be my primary setting.

**Comment by ehollig** [comment]
The solution provided by @derekriemer in https://github.com/nvaccess/nvda/issues/5145#issuecomment-155339950 would work, also having the solution provided by #4209 would allow you to change this with a keystroke. Closing, as this will be resolved with either of the above solutions
