### ISSUE TITLE
Elements list: Copy to clipboard

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5155]
**Reported by leonarddr on 2015-06-15 09:45**
I'd like to suggest a 'copy to clipboard' button for elements in the elements list. This would especially be useful for:
- Comments in Word, particularly the lengthy ones which can't be fully showed
- Links, although it could also be considered to copy the destination URL instead.

**Comment by leonardder** [comment]
> - Comments in Word, particularly the lengthy ones which can't be fully showed

Actually, it would be better to have a double or triple press of nvda+alt+c to copy a comment to the clip board. I don't see other valid use cases for such a button that fit in NVDA core's scope, copying an URL is something a browser has facilities for

**Comment by ehollig** [comment]
@leonardder, do you agree that this feature request should be limited to copying a comment to the clipboard in Word? If so, should the keystroke be NVDA+Alt+C three times, to stay consistent with other features that do this, I.E. Press once to speak, twice to spell, three times to copy to clipboard? In that case, this sounds fairly easy to implament.

**Comment by Adriani90** [comment]
@ehollig yes I think this is indeed the case here. In my opinion this would be a good feature.

**Comment by Adriani90** [comment]
The link can already be copied by pressing nvda+k twice and copying it from the browseable window, at least in browsers. In MS Word you can do it via the context menu.

For the comment area, in Excel you can use shift++f2 to display the comment and copy it, in MS Word you can also use the comment editing area and copy the content. A browseable window for MS Word and Excel comments will be implemented in #15987 and #15986. 

So this request is invalid.

**Comment by Brian1Gaff** [comment]
Its a pity it could not be opened in notepad. Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
  ----- Original Message -----
