### ISSUE TITLE
Possible regression with WLM (ticket 4976): Email address is not spoken when pressing enter in WLM's email field

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5156]
**Reported by nvdakor on 2015-06-15 17:22**
Hi,
A user reports that, after upgrading to 2015.2, NVDA no longer announces email addresses typed into "to" field in Windows Live Mail when enter is pressed. Upon further investigation, it was determined that this is new to NVDA 2015.2, possibly caused by commits for #4976. Thankfully, NVDA comes with WLM app module, so will it be possible to override this behavior in the app module, or should this be done from MSHTML controls themselves?
Thanks.
**Blocked by #4976**

**Comment by leonardder** [comment]
I'm closing this as works for me, based on the last two comments by @JosephSL. WLM is discontinued anyway and there are well working alternatives.
