### ISSUE TITLE
Forms and tables mixed: when a th contains only a label, it's not announced when moving up/down in a table

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5157]
**Reported by jmuheim on 2015-06-16 09:39**
I experimented with forms mixed into tables (for complex forms).

I noticed that when I put only a label into a th, then the th is not announced when moving up/down in the table.

I also noticed that the same is true when shift-tabbing from the first focusable item in a row back into the last focusable element of the row above. The other way round, it works.

Here's a CodePen which illustrates the problem.

http://codepen.io/jmuheim/pen/aOyVEZ

JAWS doesn't seem to have this problem, so I think it's an NVDA bug.

**Comment by ehollig** [comment]
I am not sure this is an issue anymore. Can anyone else confirm?

**Comment by derekriemer** [comment]
yeah, this works now. Closing.
