### ISSUE TITLE
Book text in Adobe Digital Editions is always shown in Braille with a highlight

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5158]
**Reported by srandall on 2015-06-17 08:50**
When reading  book content in Adobe Digital Editions, dots 78 are always on with my display.  In JAWS I am able to turn off "show highlighting" and this fixes the issue, so I conclude ADE is exposing the text this way to whichever API (insert other technical term I don't understand) you are using to obtain the book text.
I don't know enough about louis to go poking around to make a custom braille table and apply it to a digital editions profile ; I found no NVDA setting to turn off highlighting or other attributes.

**Comment by dkager** [comment]
It would be good to know what version of ADE this is. With v4.5 I don't get book text in braille at all (#5634).

**Comment by bhavyashah** [comment]
@dkager By https://github.com/nvaccess/nvda/issues/5158#issuecomment-233739881, do you mean that the reported issue no longer exists at your end with recent versions of Adobe Digital Editions? If so, this issue can be safely closed. @ehollig

**Comment by dkager** [comment]
What I meant is that I don't see any of the book's text content on the braille display, so this problem doesn't occur for me. But that's not because it was fixed, but because my problem is even worse. :)

I should say that I haven't tested this since my comment from a year ago.

**Comment by Adriani90** [comment]
@srandall, @dkager are you still able to reproduce your issues?

**Comment by Igor3947** [comment]
I'm experiencing the same problem. It appears that text is selected whenever arrow keys are used; in addition, it is also not possible to move through text using the panning keys on the display.

**Comment by Adriani90** [comment]
Adobe actually discontinued further development of ADE years ago, and there were only two minor security updates during last 5 years. Adobe does not offer any assistance on ADE anymore. The only support is through online forums and the online help articles.
See these links for more information:
https://help.overdrive.com/en-us/0118.html
https://helpx.adobe.com/support/programs/adobe-support-policies-supported-product-versions.html
https://community.adobe.com/t5/digital-editions-discussions/is-digital-editions-discontinued/td-p/14494485

That being said, I am closing this issue as abandoned. I don't expect any further updates to the adobe digital editions regarding accessibility.
