### ISSUE TITLE
NVDA needs enhanced braille navigation so dialog boxes etc. can be read without using the keyboard on the computer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5164]
**Reported by tbdalgaard on 2015-06-18 21:34**
This has been tested with a HIMS Braille Sense U2, Focus 40 classic and a VarioConnect 40.
When reading on a braille display NVDA works very well when the system cursor can follow the braille like in ducuments, websites etc.
But when the user wants to read a dialoug box it becomes a little tricky. Object navigation, screenreading mode do not change the navigation. When braille follows the review cursor this doesn't change reading areas of the screen where the keyboard fucus can't follow it.
That's a realy needed feature in NVDA, hopefully this can be improoved.
I'll be happy to test it out.

Best regards Thomas

**Comment by leonardder** [comment]
@tbdalgaard: Assuming you are the original author of this issue, could you elaborate whether you still see this as a problem? Note that you can assign desired input gestures in the input gestures dialogb. Ideas about default assignments for displays are welcome of course.

**Comment by Adriani90** [comment]
@tbdalgaard you can also emulate modifier keys on many braille displays, there is more information on this in the user guide. So do you have any further suggestions? Or is this problem solved for you?

**Comment by Adriani90** [comment]
Since we did not hear from the initial author for a very long time, I am closing this one. Please open a new feature if you feel that something is missing. Thanks.
