### ISSUE TITLE
When you are trying to create a ticket, NVDA throws you out of the ticket creation page when you try and press backspace to remove a letter?

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5174]
**Reported by Brendon22 on 2015-06-20 22:26**
When you are trying to create a ticket, NVDA throws you out of the ticket creation page, when you try and press back space to remove a letter?

Also,, 's and .'s seem to  throw NVDA out, because NVDA Keeps on  repeating words with ,'s and .'s after them, or a word that has it in it, when you press ALT+Left and ALT+Right when in the ticket edit fields?
No error sound is given, using IE11, this is a very frustrating

 issue for people who are trying to create a ticket, I had this happen to me on a large number of times when creating tickets.

**Comment by ehollig** [comment]
This works as expected for me. Also, I believe this is referring to the old ticket software. Unless we can contact the original author for more information, I would say this can be closed.

**Comment by leonardder** [comment]
Closing as invalid, since Trac is no more for us.
