### ISSUE TITLE
Start button in Windows 8.1 and later is recognized as a list and reported as selected

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5178]
**Reported by nvdakor on 2015-06-22 20:56**
Hi,
When you navigate desktop via object navigation or tab through the shell window, NVDA announces Start button as a list.

STR:
1. Press Windows +M to minimize all windows.
2. Press TAB to go to Start button.
Expected: NVDA announces "Start button".
Actual: In Windows 8.1 and 10, NVDA says, "Start list selected".

Technical: Thankfully, window class name is "Start", which is unique among Windows Explorer objects. Somehow, IAccessible thinks it is a list when documentation clearly says it is a button. This is for Windows 8.1 and 10 (likely as a result of removal of Start button in Windows 8). Tweaking this with NVDAObject_init solves the problem.
Thanks.

**Comment by josephsl** [comment]
Hi,

Solution change: Since Windows 10 Version 1511 (build 10586), Start button is now labeled as a button. Thus, it might be possible to isolate Windows builds with this issue (9200 (Win8), 9600 (Win8.1), 10240 (Win10 RTM)). I'll formally request a pull request as a separate issue, linking the two tickets. Thanks.

**Comment by jcsteh** [comment]
No need t do build checks if that's what you mean; this code simply won't match on a system which has the fix because the role will be different. There are, however, some other issues with your fix. I'll comment on the commit.

**Comment by nvaccessAuto** [comment]
Incubated in b1f00f4f8c3d4a6cf036e1a9c6c7deefe664a0c8.

**Comment by josephsl** [comment]
The latest commit fixes a major bug where error tones were heard when using object nav to move between shell objects such as the Start button (important for touch users as well). Thanks.

**Comment by nvaccessAuto** [comment]
Incubated in 64df7584160dc762745c7b0e6a04b3d19abc222e.

**Comment by JamaicanUser** [comment]
This should be added to 2016.1 Milestone

**Comment by dkager** [comment]
This again is as trivial as they come, but in `appModules/explorer.py:chooseNVDAObjectOverlayClasses`, should there not be a return statement after inserting the appropriate class? E.g.:

```
		if windowClass == "Start" and role in (controlTypes.ROLE_LIST, controlTypes.ROLE_BUTTON):
			if role == controlTypes.ROLE_LIST:
				clsList.remove(List)
			clsList.insert(0, StartButton)
			return
```
