### ISSUE TITLE
Nvda speech does not start some times in windows 7 32 bit home premium

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5182]
**Reported by HungarianLaller on 2015-06-24 11:14**
If I start the pc, and when the windows login signal is heared, sometimes I hear only nvda signal, but no speech.
I tried the following:
1. I waited a half a hour, then logged off, than on, with the logon screen speech.
2. I started narrator, and restarted the pc.
3. I turned the power button, until the pc did not stopped.
If I logged off, an error message released:
Error in the following application: nvda.exe
Ok button.
And no details.

**Comment by jcsteh** [comment]
We believe this to be the same underlying cause as #4457. A fix is now available for testing in the latest "next" branch snapshots.
