### ISSUE TITLE
BSTR memory leaks

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5184]
**Reported by DelRed on 2015-06-26 09:10**
Hello, I use UI Automation with my controls, I have noticed that when I use NVDA and just tab all controls on my form - it cases memory leaks in my application. If I use JAWS - there is no such problem.
I think that the issue is that when I return VARIANT with BSTR (for example as answer to UIA_NamePropertyId), or just BSTR (IValueProvider::get_Value(BSTR *pRetVal)) I use SysAllocString, so after NVDA use this BSTR it should call SysFreeString.

**Comment by leonardder** [comment]
Although a very interesting ticket, I'm afraid we can't contact the original author any more, and as @MichaelDCurran stated in https://github.com/nvaccess/nvda/issues/5184#issuecomment-155340861, a test case is needed for this. I'm leaning towards a close.

**Comment by ehollig** [comment]
Closing, as suggested by @leonardder in https://github.com/nvaccess/nvda/issues/5184#issuecomment-323261338
