### ISSUE TITLE
Command Prompt: Extraneous Information Spoken when Typing

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5193]
**Reported by elliott94 on 2015-07-01 19:12**
I've noticed this particular issue since upgrading to the latest couple of snapshots several months ago, which makes me think that it has been introduced with NVDA rather than being a Windows-specific bug.

Steps to reproduce (observed on Windows 7, not sure about any other versions):
1. Open a new Command Prompt window.
2. Begin typing some text, either separating content with a space or the period character.

Expected: NVDA should only announce content when either a space/period character is used.

Actual: NVDA sometimes announces typed content in chunks rather than as entire words. This behaviour is more prevalent with only typed words enabled, but can also be observed with only character feedback chosen as an option.

**Comment by bhavyashah** [comment]
@elliott94 Does this still occur for you?

**Comment by elliott94** [comment]
I haven't seen this for a while now; happy for it to be closed.

**Comment by ehollig** [comment]
Closing as requested in https://github.com/nvaccess/nvda/issues/5193#issuecomment-323800647
