### ISSUE TITLE
Faster add-on development workflow

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5199]
**Reported by Q on 2015-07-06 20:11**
Currently, the options for developing an NVDA add-on consist of:

1: Create and work on the add-on in your standard code directory.
This is how I'd like to work, but it has some pretty major downsides.
When working on the code, test, debug lifecycle, the necessity of constantly having to run scons, then install the add-on and answer yes three times for every single change becomes incredibly wearing.
2: An ugly hack that several people have suggested is to place the actual add-on code into the add-ons directory and work on it there. This means not having access to the version control while working on the code, and manually having to copy code back and forth to the git repo. It's also just sort of downright ugly.

I suggest an improved version of 1:

If we can figure out where NVDA data should go, either by asking NVDA itself, asking the user, or even just guessing, we can automatically install the add-on without prompting the user. NVDA already has the ability to force restart. I propose a scons install command in the default add-on template, which may need to call infrastructure in the core to accomplish what it needs to to get the add-on installed and the current NVDA restarted.
I'm opening this here as my conversation with @joslee lead me to believe that this will need at least a bit of work in core.

**Comment by Adriani90** [comment]
cc: @feerrenrut

**Comment by Adriani90** [comment]
cc: @michaelDCurran

**Comment by feerrenrut** [comment]
II think I'll close this. At the moment you can use the scratchpad to avoid having to install the addon. You could link the directories as Jamie suggested, or you could use a directory synchronization tool to keep the scratch pad in sync with the addon repo. If you do this, then working on an addon from an IDE (opening the NVDA source code as a project, with the addon synchronized with the scratchpad directory) allows you to get hinting and instantly start and test the addon.

I think the first step should be for the addon community to get together docs on the suggested workflow for addon authors. From beginning to end. This will help to identify the friction points and we can work to do something about it.
