### ISSUE TITLE
Input Help: Sentence Reading Commands not announced in Microsoft Word

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5200]
**Reported by elliott94 on 2015-07-08 08:51**
In 2015.2, the functionality of being able to move by sentence in Word documents was added. While this is mentioned in both the User Guide and in the Commands Quick Reference, this is not announced if this particular combination is used whilst in Input Help when Word is active.

**Comment by leonardder** [comment]
CC @Elliott94

Closing as invalid, since even though the commands are mentioned in the user guide, they are in fact Word commands, so it is expected that they don't speak in input help.
