### ISSUE TITLE
I think NVDA's logic is wrong on password confirmation & strength

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5202]
**Reported by mgifford on 2015-07-08 14:09**
Coming from a Drupal 8 issue queue https://www.drupal.org/node/1811240

We're trying to dynamically pass along the password strength & password confirmation status to screen reader users.

In this instance we're largely looking to add aria-live="polite" aria-atomic="true" to the form.

NVDA seems to be reporting opposite to what I see on the screen when testing this out.  

It could be that we've just set this up wrong, but logically it doesn't make sense that it would be reporting the opposite on the screen as it is to the screen reader.

**Comment by leonardder** [comment]
Closing, since the mentioned drupal issue seems fixed.
