### ISSUE TITLE
NVDA has problems with Decimal marks in German

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5203]
**Reported by The_Dark_Man on 2015-07-09 05:38**
In German, NVDA tries to use decimal marks. When I write the number 7.000, it says "seven dot zero zero zero". When I write 17.000 it says seventeenthousand. When I write 7.000.000 it says "seven dot zero zero zero thousand." It would be nice to fix this bug.

Thank you.

**Comment by ehollig** [comment]
@bdorer is this still an issue? Do you think the dot in German should be set to most?

**Comment by bdorer** [comment]
Hi, I wote for closing.

**Comment by leonardder** [comment]
As we can't seem to contact the original author and he was the only one who could reproduce this, I'll close this indeed. Please open a new issue according to the template if the problem still occurs somehow.
