### ISSUE TITLE
Update support for the Alva BC6 braille displays

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5206]
**Reported by dkager on 2015-07-10 10:47**
This patch updates support for the Optelec Alva BC6 series braille displays. It currently does the following:
* Detect the secondary cursor routing buttons. They are not assigned to any NVDA actions at the moment.
* Add more key bindings, largely based on the bindings for other screen readers as described in [this document](https://in.optelec.com/binaries/content/documents/optelec-international-website/products/alva-bc680/alva-bc680/optelec%3Adownloads%5B10%5D/optelec%3Afile) from Optelec.
* Update the key commands documentation accordingly.

To do:
* Implement meaningful scripts to be triggered using the secondary cursor routing buttons. A good start would be the ```reportFormatting``` script. See the Papenmeier driver for a possible implementation. Ideally, it should be possible to call this script for an arbitrary position without first routing the (review) cursor there.
* Add bindings to change the cursor shape and toggle the cursor on/off. Depends on #5198.

Branch: [alvaBC6](https://bitbucket.org/dkager/nvda/branch/alvaBC6)
**Blocked by #5198, #5250**

**Comment by jcsteh** [comment]
Merged in fb766618.
