### ISSUE TITLE
Navigating an item list in 1Password 4 with the arrow keys causes the application to crash

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5208]
**Reported by AlexH on 2015-07-10 20:38**
When using 1Password 4 for Windows alongside NVDA, using the arrow keys to quickly navigate a list of items in the application will cause 1Password to crash. In addition to that 1Password's interface will become unresponsive, forcing the user to quit the application using the task manager.

---

'''Steps to reproduce:'''
1. Install [1Password 4 for Windows](https://cache.agilebits.com/dist/1P/win4/1Password-4.6.0.582.exe)
2. Create a demo vault:
   a) Select 'File > New 1Password Demo Vault'
   b) Follow the steps to create the demo vault.
3. With the demo vault in place, use the arrow keys to quickly go UP and DOWN the list of items in the vault.
4. If the error doesn't occur, duplicate a few items (select an item and press CTRL+D) until the count is above 50.
5. Go through the list again, using the UP and DOWN arrow keys until the app crashes.

---

'''Result:'''

1Password will crash, displaying an error message prompting the user to send in an error report.
However, the application's UI will be unresponsive to a degree that will prevent the user from sending in an error report (sometimes) and from being closed without the use of the task maanger (almost always).

The error message that appears usually reads:

`Access violation at address 75DE1CD1 in module 'combase.dll'. Read address 6F706D6D.`

---

Additional information:
- Windows 8.1, Windows 7
- NVDA 2015.2
- 1Password 4 for Windows, version 4.6.0.582
- 1Password is built in delphi, using the standard Windows UI components.

---

Notes:

We have received numerous complaints from visually impaired users relying on 1Password 4 for Windows for the password security and we would love nothing more than to increase the compatibility of 1Password with NVDA.

We feel that there is still a lot to do on our end to make 1Password play nice with NVDA and, if helpful, we will arrange contact with our developers.

Thanks!

Alex Hoffmann
(Bearded Vulcan Support Technician @ [AgileBits](https://agilebits.com))

**Comment by bhavyashah** [comment]
The freeze/crash seems to have already been resolved, and seeing that the original reporter did not respond to @jcsteh's https://github.com/nvaccess/nvda/issues/5208#issuecomment-155341142, please close this ticket.
