### ISSUE TITLE
Implement HTTPS for Trac Pages

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5214]
**Reported by elliott94 on 2015-07-13 07:28**
Lots of websites are now modifying their web server config to serve an encrypted version of a website by default. This has two major advantages; search engines including Google have previously explained that sites secured using HTTPS will be displayed before those that don't, which in theory could offer further exposure to the project as a whole. Furthermore, when a user enters their username/password to login to Trac this information is currently sent unencrypted, which presents the possibility of interception (on an unsecured 802.11 network, for example). Is this something that you would consider adding to the website?

**Comment by jcsteh** [comment]
We're on GitHub now (which uses https), so this is done.
