### ISSUE TITLE
Bad Voice Attribute:  messages on console in master branch

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5225]
**Reported by vrdhn on 2015-07-15 06:31**
This happens when I start nvda.pyw from python ( not the windows pythonw ).
Following messages are displayed in the cmd window:

Bad voice attribute: to
Bad voice attribute: 5
Bad voice attribute: ther

The string 'Bad Voice attribute' is present in espeak.dll.
I've verified these attributes are NOT passed to espeak from NVDA.

This can be an espeak data file issue. I was not able to locate the exact language / variant show this. 

These are the lines from nvda.ini which are showing this behaviour:
[= espeak
    [[espeak](speech]
    synth)]
        voice = default
        variant = Mr serious
        rate = 55
        pitch = 81
        inflection = 70
        volume = 80
My system regional languages is set to English India
Thanks

**Comment by rhdunn** [comment]
I fixed these bad voice attribute messages in my espeak GitHub fork on 2013-09-05 (rhdunn/espeak@f6db58e6b000a782ac278924f7c608e0b7448575) after importing the NVDA variants. This was long before I created the `espeak-ng` project which incorporates these fixes.

**Comment by jcsteh** [comment]
Thanks @rhdunn. In that case, this will be fixed as part of #5651.

**Comment by ehollig** [comment]
Since #5651 is closed, can this be closed as well?
