### ISSUE TITLE
assigning key-combination to invoke HOME and END function with autohotkey scripting language will not work while NVDA is running

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5226]
**Reported by rossdevent on 2015-07-15 10:32**
I am using autohotkey (http://www.autohotkey.com/) to assign a keystroke that will activate the HOME and END function of my keyboard.  The hotkey will work when NVDA is not running, but soon as I start NVDA, the key combination will not work.

I have used this scripting tool to map PageUp and PageDown to control-alt W and control-alt S respectively, and this works with NVDA, but no matter what key-combination I assign to HOME and END, it will not work.

The reason I am using this scripting tool is because I can't physically reach the Home and End key because my laptop requires me to hold down the fn key and press the arrow keys to activate this functionality.

**Comment by leonardder** [comment]
Closing this as invalid because we can't reach the initial author of this ticket any more. Furthermore, the author didn't answer the question in https://github.com/nvaccess/nvda/issues/5226#issue-116051314 . Feel free to give a shout if this should still be concidered a problem.
