### ISSUE TITLE
nvda lags while browsing folders in windows10

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5229]
**Reported by mohammadobid on 2015-07-16 11:08**
Hi,
nvda lags a bit when Browsing folders in windows10.
It takes from 1 second to 1.5 second for nvda to speak the selected item, also when pressing enter on an item.
I'm using windows10 build 10240 with a microsoft surface pro3 tablet.
I've noticed it since the build 10166.

**Comment by jcsteh** [comment]
As per previous comments, we believe this issue to be fixed now.
