### ISSUE TITLE
Windows 10: Time picker values are not announced

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5231]
**Reported by nvdakor on 2015-07-18 07:13**
Hi,
A number of apps uses so-called time picker to select hour, minute, period and so on. So far, this appears when creating new alarms in the Alarms and Clock app and when selecting the time to restart to finish installing updates. For these controls, NVDA does not announce values as the picker changes.
STR:
1. Open an app that uses time picker controls such as Alarms.
2. If Alarms app is opened, select New, then type the name for an alarm.
3. Press TAB to move to the time picker. Press ENTER to begin interacting with it, and use up and down arrows to change values. In case of Alarms, the first picker will be hour selector.
Expected: NVDA announces values when one presses up or down arrows to select an item from a time picker.
Actual: Value isn't announced.

Technical: Yet another UIA friend. Thankfully, developer info says it has class name of LoopingSelector (doesn't matter which selector we're dealing with, as it'll have different cached class name but they are really LoopingSelector controls). Also, NVDA says it is a list when it might be best to classify it as a slider (I think reclassifying it as a slider might be the easiest solution). I'll do some more investigation into this guy.
Thanks.

**Comment by josephsl** [comment]
Hi,

Coming back to this ticket...

During a conversation with @JCSTeh, possibility of integrating support for Alarms and Clock and other apps into NVDA core was brought up. Thankfully, Windows 10 App Essentials add-on has a pull request quality code for looping selector items.

Thanks.

**Comment by leonardder** [comment]
@josephsl: Is the needs code review label still valid for this issue?

**Comment by josephsl** [comment]
Hi, yes, until the PR appears and/or accepted. I’m being careful with looping selectors, as they can change between Windows 10 releases and across apps. Thanks.

**Comment by jcsteh** [comment]
Dropping needsCodeReview, as @josephsl will be able to submit a PR if/when he wishes. Thanks.

**Comment by jcsteh** [comment]
When creating an Alarm, the value does seem to get announced for me when I use the arrow keys in the lists. This is possibly the result of another recent fix. The current value isn't announced when focusing the list, though.

P3 because it's possible to work around this, but it's annoying/inefficient nevertheless.

**Comment by josephsl** [comment]
Hi,

Eighteen months later...

I'm putting the code through some more scenarios, and will provide a pull request once the code in my add-on says it is still working in Version 1809 (hopefully in the next few hours or so).

Thanks.

**Comment by josephsl** [comment]
Hi,

Technical: looping selectors do not expose value pattern (some might). For those that wouldn't, it would be best to coerce them into combo box without value pattern objects. not only this simplifies class checks, but it also removes code duplication.

Thanks.
