### ISSUE TITLE
Teceract update to version 3.0.2

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5236]
**Reported by Diego on 2015-07-20 21:04**
Hello developers!
I found that in teceract project page there is the version 3.0.2 and on the OCR addon folder in the file of release notes is version 3.0.1.
Updating the teceract it could be made in the addon to the latest version?

**Comment by leonardder** [comment]
Is the OCR add-on still maintained by NV Access now we have Windows 10 OCR built in? I think that we should no longer treat issues regarding this add-on within the nVDA issue tracker, but that's my personal opinion.

**Comment by Brian1Gaff** [comment]
How complicated is this? I seem to recall the latest version was not a 
simple update. If its good then it might help out windows 7 users etc.
 Maybe it would also be time to investigate making some way for it to call 
other third party ocrs like Abbey for example if that were possible as some 
may have better performance in some circumstances than even the Microsoft 
cloud one has.

 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by derekriemer** [comment]
If you want to raise issues against the deprecated OCR addon, raise them against https://github.com/nvaccess/nvda-ocr

**Comment by bhavyashah** [comment]
If that is indeed the mutually agreed action to be performed on all
OCR add-on pertinent tickets, please apply the same to all issues
listed on https://github.com/nvaccess/nvda/labels/OCR%20add-on.

On 12/17/17, Derek Riemer <notifications@github.com> wrote:
> If you want to raise issues against the deprecated OCR addon, raise them
> against https://github.com/nvaccess/nvda-ocr
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/5236#issuecomment-352242995


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750
