### ISSUE TITLE
Tethering braille to review and back to focus fails in browse mode

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5237]
**Reported by bramd on 2015-07-22 08:07**
### Procedure:
1. Start with braille tethered to focus mode
2. Open a document that uses browse mode (tested with a web page in Firefox)
3. Tether braille to review and back to focus

### Actual result:

The braille display is showing the information regarding the focussed document, but not the contents of the virtual document anymore.

### Expected result:

The braille display should behave as in sstep 2 of the procedure (e.g. show the current line of the virtual document).

**Comment by dkager** [comment]
Any chance this is an easy fix? :) I'm running into this from time to time coming out of a terminal window and forgetting to tether back to focus first.

**Comment by leonardder** [comment]
@Bramd: Is this still the case?

**Comment by bramd** [comment]
@leonardder Yes, just reproduced in Chrome using latest NVDA next.

**Comment by leonardder** [comment]
Confirmed this, and this gets a bit problematic for auto tethering #2385, #7489. Let's see whether we can fix this as part of that pr.
