### ISSUE TITLE
Browse mode: provide braille feedback while pressing NVDA+space

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5239]
**Reported by surfer0627 on 2015-07-23 02:51**
Expected: While pressing NVDA+space, NVDA provides braille feedback (focus mode / browse mode.

Now, in browse mode, while pressing NVDA+shift+space, NVDA provides speech and braille feedback (Single letter navigation on / off).

**Comment by dkager** [comment]
Very trivial fix by the looks of it.

**Comment by jcsteh** [comment]
Thanks!

Note to self: Good to merge.

**Comment by nvaccessAuto** [comment]
Incubated in 8ef4a4da6ea8949ac055ec105ee7d7131299c43a.
