### ISSUE TITLE
Script to move braille to the focus and cursor

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5250]
**Reported by dkager on 2015-07-28 15:27**
Add a script that routes braille to the focus or cursor position. If braille is tethered to review, call script_navigatorObject_toFocus. If braille is tethered to focus, scroll the braille display so the cursor/caret is shown. In dialog boxes, should probably also scroll the display to the initial position it's in when first encountering a control. That is, if a control plus meta information is too long to fit on the reading unit and the user has scrolled the display, put it back to the original position.

Used for the Alva BC6 bindings as per #5206. May also apply to #5243.
**Blocking #5206**

**Comment by jcsteh** [comment]
Merged in 4c671a6d.
