### ISSUE TITLE
NVDA Does Not Update Browse Mode When Choosing An Action While Logged In To  The "Fallen London" World

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5252]
**Reported by matthews on 2015-07-29 09:45**
Browser used:
"Firefox/Seamonkey/Ice Dragon."

Steps For Reproduction:
1. Go to:
   http://fallenlondon.com
   , and sign up/log in.
2. When you first enter, you will see a button either saying the word "Go" or "Onward," while you either arrow through the text.
3. after you press the button in question, the Fallen London screen will "instantly" update under the cursor, however NVDA itself does not notice this fact, thus moving the cursor around stays within the "previously" displayed text, and doesn't update the page with the newly fresh text/controls. Only way to see the freshly cooked text on the page, is to use the NVDA-F5 command.  

If tabbing/shift-tabbing around after hitting the "go" button, the text and controls update dynamic fashion like they should.

**Comment by ehollig** [comment]
I am not able to replicate this. If I press the next button, arrowing around reads the updated text under the cursor.

**Comment by jcsteh** [comment]
Closing as worksforme. If the problem persists, please provide details.
