### ISSUE TITLE
Windows 10: NVDA freezing on focus changes after a short while of use

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5255]
**Reported by mayson on 2015-07-31 21:38**
when using my del inspiron rn 14 4110 for five to 10 minutes preformance will start to drgrade with nvda. when first booting up. nvda is perfectly fine. no slugishness what so ever. ow ever after a lengthy period of itme. browsing the web, skyping, and using metro apps. nvda will start to get slugish when navagating the gui and file explorer. I have some light, so I can see when the window is focused. the screen moves to the window just fine, but for some reason nvda will have a big big delay 10 to 25 second befor it says the task name when alt tabbing or alt shift tabbing. also with file exploerer, the same thing happens. I open this pc, then move to the folder I want to open. same sanario hear. the focus on the screen will move to it quick, but yet again. nvda will have the 10 to 25 second d lag delay when navagating to the file or folder in question. I have tried everything. seeting the power saver mode to high preformance and also ajusting viusal affects. I have 8 gb of ram installed on this machine. and I do close all apps when I am done with them.
**Blocking #5244**

**Comment by jcsteh** [comment]
As per previous comments, we believe this issue to be fixed now.
