### ISSUE TITLE
Errors when browsing with Google Chrome with NVDA. This is the latest version of Google Chrome.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5256]
**Reported by Brendon22 on 2015-08-01 03:04**
Hello,
When browsing through a website with Google Chrome with NVDA, I get the following error:
Note: this is on most websites not all though.
ERROR - XMLFormatting.XMLTextParser.parse (12:29:12):
XML: <control controlIdentifier_docHandle="18350620" controlIdentifier_ID="-3516" _startOfNode="0" _endOfNode="0" isBlock="1" isHidden="0" _childcount="4" _childcontrolcount="3" _indexInParent="0" _parentChildCount="1" IAccessible2::attribute_tag="#document" IAccessible2::state_1024="1" IAccessible::role="15" IAccessible::state_1048576="1" IAccessible::state_4="1" IAccessible::state_64="1" keyboardShortcut="" name="NV Access | Download" ><control controlIdentifier_docHandle="18350620" controlIdentifier_ID="-3518" _startOfNode="0" _endOfNode="0" isBlock="1" isHidden="0" _childcount="1" _childcontrolcount="1" _indexInParent="1" _parentChildCount="4" IAccessible2::attribute_display="block" IAccessible2::attribute_tag="div" IAccessible2::attribute_xml-roles="main" IAccessible2::state_1024="1" IAccessible::role="1054" keyboardShortcut="" ><control controlIdentifier_docHandle="18350620" controlIdentifier_ID="-3582" _startOfNode="0" _endOfNode="0" isBlock="1" isHidden="0" _childcount="20" _childcontrolcount="18" _indexInParent="0" _parentChildCount="1" IAccessible2::attribute_display="block" IAccessible2::attribute_tag="article" IAccessible2::attribute_xml-roles="article" IAccessible2::state_1024="1" IAccessible::role="15" IAccessible::state_64="1" keyboardShortcut="" ><control controlIdentifier_docHandle="18350620" controlIdentifier_ID="-3602" _startOfNode="1" _endOfNode="0" isBlock="1" isHidden="0" _childcount="5" _childcontrolcount="4" _indexInParent="19" _parentChildCount="20" IAccessible2::attribute_display="block" IAccessible2::attribute_tag="ul" IAccessible2::state_1024="1" IAccessible::role="33" IAccessible::state_64="1" IAccessible::state_65536="1" keyboardShortcut="" ><control controlIdentifier_docHandle="18350620" controlIdentifier_ID="-3776" _startOfNode="1" _endOfNode="1" isBlock="0" isHidden="0" _childcount="1" _childcontrolcount="1" _indexInParent="0" _parentChildCount="5" IAccessible2::attribute_display="inline-block" IAccessible2::attribute_posinset="1" IAccessible2::attribute_setsize="5" IAccessible2::attribute_tag="li" IAccessible2::state_1024="1" IAccessible::role="34" IAccessible::state_64="1" IAccessible::state_65536="1" keyboardShortcut="" ><control controlIdentifier_docHandle="18350620" controlIdentifier_ID="-3781" _startOfNode="1" _endOfNode="1" isBlock="0" isHidden="0" _childcount="2" _childcontrolcount="1" _indexInParent="0" _parentChildCount="1" IAccessible2::attribute_display="inline-block" IAccessible2::attribute_tag="a" IAccessible2::state_1024="1" IAccessible::role="30" IAccessible::state_1048576="1" IAccessible::state_4194304="1" IAccessible::state_65536="1" description="Click to share on LinkedIn" keyboardShortcut="" ><control controlIdentifier_docHandle="18350620" controlIdentifier_ID="-3782" _startOfNode="1" _endOfNode="1" isBlock="0" isHidden="0" _childcount="2" _childcontrolcount="0" _indexInParent="0" _parentChildCount="2" IAccessible2::attribute_<pseudo="before&gt;" IAccessible2::attribute_display="inline-block" IAccessible2::state_1024="1" IAccessible::role="1060" IAccessible::state_65536="1" keyboardShortcut="" name="Click to share on LinkedIn" ><text _startOfNode="1" _endOfNode="1" isBlock="0" isHidden="0" _childcount="0" _childcontrolcount="0" _indexInParent="0" _parentChildCount="2" >Click to share on LinkedIn</text></control><text _startOfNode="1" _endOfNode="1" isBlock="0" isHidden="0" _childcount="0" _childcontrolcount="0" _indexInParent="1" _parentChildCount="2" >LinkedIn15</text></control></control></control></control></control></control>
Traceback (most recent call last):
  File "XMLFormatting.pyc", line 60, in parse
ExpatError: not well-formed (invalid token): line 1, column 2926
ERROR - XMLFormatting.XMLTextParser.parse (12:29:12):
XML: <control controlIdentifier_docHandle="18350620" controlIdentifier_ID="-3516" _startOfNode="0" _endOfNode="0" isBlock="1" isHidden="0" _childcount="4" _childcontrolcount="3" _indexInParent="0" _parentChildCount="1" IAccessible2::attribute_tag="#document" IAccessible2::state_1024="1" IAccessible::role="15" IAccessible::state_1048576="1" IAccessible::state_4="1" IAccessible::state_64="1" keyboardShortcut="" name="NV Access | Download" ><control controlIdentifier_docHandle="18350620" controlIdentifier_ID="-3518" _startOfNode="0" _endOfNode="0" isBlock="1" isHidden="0" _childcount="1" _childcontrolcount="1" _indexInParent="1" _parentChildCount="4" IAccessible2::attribute_display="block" IAccessible2::attribute_tag="div" IAccessible2::attribute_xml-roles="main" IAccessible2::state_1024="1" 

I am unable to hear the content on the website and I am unable to brows the website correctly:
Website where this happens is the following:
http://www.nvaccess.org/download/
Thank you.

**Blocking #5394**

**Comment by jcsteh** [comment]
Chromium issue 540974 is now fixed.
