### ISSUE TITLE
Windows 10: Battery status script change to make it report time till fully charged

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5259]
**Reported by leonarddr on 2015-08-01 19:26**
It seems that Windows 10 has the ability to indicate how long it will take until the battery of a laptop or tablet is charged. It might be interesting to change the battery script to also report this, for example whenever the hotkey is pressed twice.

**Comment by leonardder** [comment]
cc @JosephSL @derekriemer 

The time I tested this initially, it wasn't technically possible to retrieve this information. I wonder whether it is possible now. Also, I recall a ticket that is related to this and where I mentioned my tests earlier, or it must have been IRC.

**Comment by derekriemer** [comment]
It's not in the battery api. If there's another way,p lease let me know.

**Comment by PratikP1** [comment]
@derekriemer<https://github.com/derekriemer> Can you possibly use ChargeRateInMilliwatts in combination with FullChargeCapacityInMilliwattHours from the Battery​ReportClass to estimate the time to charge?

Reference: https://docs.microsoft.com/en-us/uwp/api/windows.devices.power.batteryreport

Feel free to tell me if I’m off.

**Comment by seanbudd** [comment]
@Adriani90 - no it is not. I agree that it is better suited to an add-on. Sighted folks are generally expected to go to "Power & Settings" to find this information, or use hardware monitoring software.

I am closing this as won't fix

**Comment by XLTechie** [comment]
@seanbudd according to this article, and to my experience with Win 10 laptops 
sometimes announcing this, the sighted can access it with a mouse hover over the 
power icon in the notification area.

https://www.cnet.com/tech/computing/find-out-how-much-time-remains-before-your-laptop-is-fully-charged/

**Comment by PratikP1** [comment]
@seanbudd I find this philosophy of, “if not available to sighted people, we’ll not implement it in core” to be short-sighted. There are many screen reading functions not readily available to sighted people. Not having resources to implement a feature and prioritizing one thing over another is a different matter. There is so much not part of the core functionality that should be like proper Excel support that prevents someone like me from completely abandoning JAWS. It’s a bit disheartening at times.

**Comment by PratikP1** [comment]
I can think of two examples without thinking hard: 1) Retrieving font and character information; and 2) Elements list in browsers. By its nature, a screen reader can only convey information in a single dimension with some exception. It means that what the screen reader is able to convey is never equal to what is available to sighted people. So the definition of a screen reader merely there to convey information solely available to sighted people is limited and is limiting. To me, it’s a failure of imagination. I’d say considering a name and coming up with a definition of that based only on the name limits how the piece of software serves the people whom it supports. Instead of considering this piece of software as a sole conveyance for what is on the screen, I’d argue that we need to expand the definition to say that it is an information conveying mechanism.

**Comment by Qchristensen** [comment]
Can I suggest this conversation is better had in either the user group or as a discussion?

FWIW, getting back to the original request - I would say:

1) Having the amount of battery life left (in minutes) IS arguably useful.

2) This information would be useful for everyone.  There is nothing screen reader specific to the usefulness of it.

3) That request should go to Microsoft - if they implement it as perhaps a mouseover or hint on the battery information, that would potentially benefit all Windows users.  It would then absolutely be valid to ensure that NVDA reported any information as contained in such a popup.

4) Something being "useful to users of Windows (or other software) in general" (like amount of battery life left) is not justification for including it in NVDA.  To take Pratik's two examples - font formatting information is readily available visually in programs such as Microsoft Word, hence the need to have NVDA+f report the same information to NVDA users.  The fact this also works on the web and other places that information is not visually printed is partly a convenience, but partly also, a sighted user CAN see that text is italic, or underlined, or in MS Comic Sans, so the information is "there" visually, even if it isn't explicitly written on screen.  And the elements list - I gave you on Mastodon this morning - is arguably useful for navigation.  Sure a sighted user might not immediately get a count of how many links there are on a page, but they can also flick the mouse wheel to quickly scroll down and stop when they see larger text for a heading they want.  The exact method might be different, but the end result in both cases is still to endeavour to get the user to the section of the page they want as quickly as possible.  If you do have anything else which you feel strongly about, please do create an issue or comment on the appropriate issue.
