### ISSUE TITLE
Documentation: Add Developer Info and Application Name commands to Commands Quick Reference

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5261]
**Reported by elliott94 on 2015-08-02 10:11**
Whilst reading through the Commands Quick Reference, I noticed that the above two commands are missing. Is this intentional? My first thought was that since they're both more developer-orientated than the majority of other commands the decision was made not to include them, but they don't appear in the Developer Guide either.

**Comment by ehollig** [comment]
CC @jcsteh @josephsl

**Comment by Adriani90** [comment]
cc: @josephsl

**Comment by Adriani90** [comment]
What is the command for the developer info?

**Comment by CyrilleB79** [comment]
The command for developer info is just NVDA+F1, which log a message with "Developer info for navigator object" and opens the log viewer on this last message.

**Comment by Adriani90** [comment]
This is now added to the user guide and command quick reference in last NVDA alpha. Closing as fixed.
