### ISSUE TITLE
VIPMud: Reading output does not work when not in foreground

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5262]
**Reported by KCunningham on 2015-08-02 14:05**
When I am not on a VIPMud window, using version 1.11 of the program, text will fail to read. this can mean that if I am in another window doing some coding or even on another VIPMud window, I miss a lot of text going on in one of my games. this is especially annoying if, for example, I want to listen to music and am moving through tracks on my media player window. I should also point out that this has only happened since upgrading to windows 10, and does not happen on any of the snapshot versions I use on my windows 7 and 8 machines.

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years, closing as abandoned. In case you still have this issue, please comment on it and we can reopen.
