### ISSUE TITLE
Certain bullets not reported in Microsoft Word

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5267]
**Reported by csm120 on 2015-08-05 09:05**
I have tried this in NVDA 2015.2 and in the latest snapshots.
Steps to reproduce:
1. In Microsoft Word 2010 through 2016 open a blank document
2. Press the star key (Shift 8 on numbers row) then type a line of text and press enter.
3. Type another line and press enter twice.
4. You should now have a bulleted list with 2 items.
5. Arrow through the list and on my end NVDA won't indicate that bullets are there.
6. Do the same steps above but instead of typing a star, type 1. As you type lines of text word automatically puts numbers pressing enter twice stops the auto-numbered list. Again NVDA doesn't indicate numbers here.

**Comment by jcsteh** [comment]
> NVDA does report numbers and bullets like "*", but as soon as i create a list with "-" (dash), it doesn't report the bullet properly.

@Leonardder, do you have your symbol level set to most or all? For me, dash bullets don't get reported at level none or some because dashes don't get reported at those levels. However, they do get reported at most or all. I don't think there's really much we can do about this unless there's some semantically better Unicode symbol for a dash bullet.

**Comment by jcsteh** [comment]
@dkager, @qchristensen, @MichaelDCurran, thoughts on how common this is? Just trying to work out what priority we should give this.

**Comment by Qchristensen** [comment]
list items denoted with a dash I would guess are not as common as asterisk / bullet list items, but I think they are still used quite regularly.  Particularly as it's an easy conversion from plain text.

Another way around it could potentially be to check the style of the text - any list will default to "List paragraph".  That way it wouldn't matter what symbol was used.  The issues with that would be that both bulleted and numbered lists are identified as "list paragraph", and also it's possible to create custom styles which work as a list.  Theoretically it's possible to set text in the middle of a paragraph to be "list paragraph" too but I wouldn't expect that to be very common.

As it is now, the list is automatically indented, and assuming NVDA is set to announce indentation, that is announced as you enter a list.

Back to the original point, I think the easiest to understand for the user would still be to find a way to announce that a dash list is still a list, even if the current symbol level wouldn't normally announce dashes.

**Comment by dkager** [comment]
Sorry, missed this one when searching for an existing issue. Lists with asterisks are quite common. The dashed lists I think already use a plain dash, but the asterisk is a Private Use codepoint that is brailled but not translated by liblouis, e.g. '\xf0b7'.
Just announcing if something is a list is not enough for nested lists (which can also use different bullets for the different levels). Here it would be useful if you knew an item was called `1`, `a`, or had a bullet.

**Comment by jcsteh** [comment]
I was confused because the asterisk bullet reads fine with speech. However,
it looks like we mapped U+F0B7 to bullet in symbols.dic. That's a total
hack and something we probably shouldn't have done.

**Comment by leonardder** [comment]
@jcsteh: Indeed, changing symbol level to most or all does report them, but I'd honestly prefer a fix to have them read for the some level as well.

**Comment by dkager** [comment]
At first glance the associated PR looks good, though I wonder if we shouldn't replace the PUA codes with ASCII. Even U+2022 (bullet) isn't in all braille tables. On the other hand it could be argued that those symbols are closer to what the PUA ones actually look like.

**Comment by jcsteh** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [11 Jan. 2017, 5:02 pm AEST](https://github.com/nvaccess/nvda/issues/5267#issuecomment-271794038 "2017-01-11T07:02:36Z - Replied by Github Reply Comments"):
> @jcsteh: Indeed, changing symbol level to most or all does report them, but I'd honestly prefer a fix to have them read for the some level as well.

I don't think that's possible beyond changing dash to level some (which we don't want to do). Even if we said that all punctuation should be read regardless of level for line prefixes (bullets, numbers, etc.), then you'd get the full stop being read for numbered list items, which would annoy users as well. The reality is that the dash is just used for way too many things.


[**@dkager**](https://github.com/dkager) commented on [11 Jan. 2017, 7:35 pm AEST](https://github.com/nvaccess/nvda/issues/5267#issuecomment-271821478 "2017-01-11T09:35:29Z - Replied by Github Reply Comments"):
> At first glance the associated PR looks good, though I wonder if we shouldn't replace the PUA codes with ASCII.

I totally accept that the Unicode characters aren't in a lot of tables, but using ASCII feels like a hack to me and is likely to cause us problems in the future. For speech, we'd then have to map those ASCII characters to some words and those words could be wrong or confusing depending on context.

**Comment by dkager** [comment]
One final concern: is the PR complete with regards to the possible bullets you can encouonter? And do the replacements visually match? I haven't been able to find a good reference for all standard bullet types.

**Comment by jcsteh** [comment]
The PR is very probably incomplete in terms of available symbols. You can
probably use just about any symbol in Word as a bullet and I imagine that
is a pretty big list. That said, I don't think we need to be "complete"
here; at the very least, we want an extensible framework with the most
common bullets.

**Comment by dkager** [comment]
We should probably try to include all bullets you can type on the keyboard, e.g. dash, asterisk, and the fancier bullets like => and <>.
I can't find a "to get this symbol, type this" reference. Maybe the list gallery can help. I think there are only a handful of default styles we need to deal with.

**Comment by bhavyashah** [comment]
Could someone please summarize the limitations of the current implementation and what work still remains for this issue to be fully addressed?

**Comment by dkager** [comment]
WRT the braille side of things, an update is in https://github.com/nvaccess/nvda/pull/6778#issuecomment-320503561.
