### ISSUE TITLE
Windows 10 - Start menu not always accessible

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5270]
**Reported by msuch on 2015-08-06 06:28**
Sometimes, when pressing Windows key to get to the start menu, the start menu gets inaccessible.
You are on the Cortana search area, but pressing up or down arrow simply announces "blank".
I can't say if this is a NVDA or a Windows problem, but restarting NVDA often makes it accessible again.

**Comment by ehollig** [comment]
Is there a way we could get a log demonstrating this issue? I do not believe I have experienced this on Windows 10.

**Comment by josephsl** [comment]
Hi,

This was build 10240 (Version 1507), which was retired on May 9, 2017 for most users (except on Enterprise LTSB). Because this doesn't happen on later builds, this issue will be closed.

Thanks.
