### ISSUE TITLE
strange nvda problem

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5273]
**Reported by nvdauser on 2015-08-07 10:33**
hello, I have a problem. when I am using nvda with e speak everything is well. I am using the newest version. when I  am using it with e speak everything is fine. but when I decide to switch to microsoftnt sapi5 speech, when I  switch to this, the computer becomes slow, and I have to turn off nvda. ususallly, I am using jaws, but I was using nvda in the past when I had a jaws problems, and I love it lol. I've unninstal and install nvda again, I've deleted all its folders  before installing again, but everything is the same. I am using windows764  bit. any suggestions on how to  fix it? thanks.

**Comment by ehollig** [comment]
This indeed could be because the voice is just slow/resource intensive and is slowing things down. Not much that we can do, unfortunately, unless there is additional information provided.

**Comment by jcsteh** [comment]
No additional info from reporter (and no way to contact). Closing.
