### ISSUE TITLE
Losing speech when selecting more then 5 files and pressing the Shift+F 10 Key?

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5278]
**Reported by Brendon22 on 2015-08-10 10:37**
Hello,
When I try and go into File explorer.
I Lose speech when selecting more then 5 files and pressing the Shift+F 10 Key?
This used to work up until a couple of weeks ago.

Please see log attached input/output.
Latest next snap.
Thank you.

**Comment by bhavyashah** [comment]
Given that this is a fairly old ticket, there is insufficient information and we cannot get in touch with the original reporter, please close this. @jcsteh @leonardder
