### ISSUE TITLE
Office 2013 is losing Focus when using Outlook and reading email? NVDA error is sometimes heard.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5279]
**Reported by Brendon22 on 2015-08-10 10:44**
Please look into the following issue.
Using Windows 8.1 and Office 2013: Latest NVDA Snap!
Office 2013 is losing Focus when using Outlook and reading email? NVDA error is sometimes heard and speech is lost.

**Comment by ehollig** [comment]
Closing, as we are unable to contact the original poster for this issue, and they did not respond to @michaelDCurran's questions and request for a log in https://github.com/nvaccess/nvda/issues/5279#issuecomment-155342351
