### ISSUE TITLE
User Guide (Section 9.1.1): Add Text for Consistency

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5280]
**Reported by elliott94 on 2015-08-10 21:44**
In section 9.1.1 of the User Guide, we have the following text and description: "Use currently saved settings on the logon and other secure screens".

For consistency with the option title for using NVDA on the logon screen, the text "(requires administrative privileges)" should be added to this description also.

**Comment by dkager** [comment]
In dkager/nvda@dc7ae49 along with some other minor tweaks.

**Comment by jcsteh** [comment]
Thanks!

Note to self: Happy for this to be merged.
