### ISSUE TITLE
Gibberish every time I try to install NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5281]
**Reported by iamjett27 on 2015-08-11 04:40**
I'm trying to install NVDA 15.2 but I only get gibberish on the screen and can't figure out what I should click to be able to install. Even in newly downloaded installer from the website. And when i did manage to install it its the gibberish part got worst.

**Comment by ehollig** [comment]
Unfortunately, I do not believe anything else can be done about this issue without the attachment.
@feerrenrut, is there an attachment I am missing?

**Comment by feerrenrut** [comment]
Indeed, in the attached image it looks like the UI for NVDA is in some other language. Is this issue still affecting anyone, I would be surprised if that were case. I'm going to close the issue. If I'm wrong, please comment on the issue and we can look into it further.
