### ISSUE TITLE
NVDA doesn't recognize submenus in Windows forms applications

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5284]
**Reported by adkurz on 2015-08-11 23:07**
In programs using Windows forms NVDA don't recognize Submenus.
For example the submenus in Keepass 2 (http://keepass.info) arn't recognize. NVDA speaks the submenu like an normal menu item.

**Comment by leonardder** [comment]
Comfirmed. Unfortunately, these submenu items don't expose oleacc.STATE_SYSTEM_HASPOPUP, so there's probably nothing we can do about it. It is very unlikely that Microsoft will fix this, as they are probably investing all their efforts in WPF. Closing as can't fix.
