### ISSUE TITLE
NVDA support braille and switching keyboard input language.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5285]
**Reported by khsruru on 2015-08-12 01:35**
Hello, I’m Hyongsop Kim in Korea.
I have a bug report about NVDA braille and Korean language.
In case of Korean language, most right alt key function is reversing between Korean and English.
In case of NVDA, if I press that key, it says keyboard status such as Korean or English very well with voice, however there is no such message in braille display.
Since some users use NVDA with braille display and turn off speech, to notify keyboard status in braille is very important.
Please check this issue.

Thank you.

**Comment by leonardder** [comment]
Hmm, from what I can see in the code (I haven't tested with a braille display yet), the code that announces input language switches uses ui.message, so this should be displayed in braille as well.

CC @DKager

**Comment by dkager** [comment]
Checked, and works for me.
