### ISSUE TITLE
NVDA is sluggish when navigating in a message list in outlook 2013 with Exchange

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5295]
**Reported by pranavlal on 2015-08-19 14:16**
NVDA is sluggish when I navigate in a message list in outlook 2013. By sluggish I mean that when I hit either the up or down arrow key to navigate to the next or previous message, NVDA takes over a second to respond. 

This does not happen uniformly. It is more frequent when I am on my work laptop which has outlook 2013 connected to Microsoft Exchange. This is happening with NVDA 2015.3 release canidate 1.
os=windows 7 32bit professional

**Comment by ehollig** [comment]
@pranavlal is this still happening for you? Considering that #5268 is closed, and @jcsteh said that this should improve the issue, I am going to close this issue.

**Comment by pranavlal** [comment]
This is still happening only on certain kinds of messages. These messages have large attachments. This is on an Exchange server.

**Comment by ehollig** [comment]
As @jcsteh said in https://github.com/nvaccess/nvda/issues/5295#issuecomment-155342597

> If you can get sighted assistance, it would be interesting to know whether the visual display also takes some time to update the current item when you press the arrow keys. It's possible that at least some of this lag occurs for everyone using the keyboard, not just NVDA users.
