### ISSUE TITLE
Making XBox app accessible

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5297]
**Reported by mohammadobid on 2015-08-19 15:02**
Hi,
Many blind people, me included, love to play games on XBox.
Now with the XBox app on windows10 and with the new features like streaming etc, it would be really awesome if you guys take a look at the app and make it more accessible with nvda.
I know the app is fine at the moment with nvda a bit, infact I can stream my games from my XBox just fine, but you just need to do some accessibilty tweeks here and there, like the settings screen for example.
And also the achievements screen needs some work as well, so for example:
if I wanted to view mortal Kombat ex Achievements, I can read all of the 60 just fine, but I don't know if I unlocked one of them or not, unless I press the enter button and if the share button is there, I know that I unlocked it.
Thanks a lot guys for your work.

**Comment by ehollig** [comment]
Closing because of https://github.com/nvaccess/nvda/issues/5297#issuecomment-155342610. Requests like this should really be made to Microsoft. In Windows 10, you can easily provide feedback in the Feedback Hub by pressing Windows+F.
