### ISSUE TITLE
Unable to click on the download button when registering for a fireEye webinar

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5298]
**Reported by pranavlal on 2015-08-19 15:11**
Hi, please navigate to the following link.
https://www2.fireeye.com/CMPG-StopTheNoise-Spoiler-Alerts.html

The above link is the registration form for a webinar. I am able to fill all the information but nothing happens when I click on the "download" button.
NVDA versoon: 20015.3 release candidate 1

**Comment by ehollig** [comment]
When I click the download button, everything works as expected. This sounds like it was an issue with the website.

**Comment by jcsteh** [comment]
Closing as worksforme. Please provide details if the specific problem persists.
