### ISSUE TITLE
See track change history in microsoft word

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5300]
**Reported by pranavlal on 2015-08-19 15:48**
I would like to be able to see the history of changes. By default, the last change should be spoken as requested in ticket 5066. 

However, there are situations when a history of changes may help. This could be presented in the virtual buffer.

**Comment by bhavyashah** [comment]
This is a friendly reminder for @pranavlal  to kindly respond to @jcsteh's https://github.com/nvaccess/nvda/issues/5300#issuecomment-155342626.

**Comment by Adriani90** [comment]
@pranavlal track changes are actually part of the elements list in MS Word. If you enable browse mode and then press nvda+f7 in MS word then you can choose "editor revisions" and in the list you can see all changes.

**Comment by pranavlal** [comment]
I see that, thanks.

-----Original Message-----

**Comment by Adriani90** [comment]
Closing as works for me.
