### ISSUE TITLE
Issues with the Camera app in Windows 10

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5310]
**Reported by k_kolev1985 on 2015-08-25 15:39**
The things that I'm about to report are probably at least partially the fault of Microsoft, but Narrator works better with the Camera app, so I guess that things can be improved from within NVDA. The problems are as follows:
- Additional useless information is reported as part of the labels for some controls (like "true" at the end of the labels for "Settings" and Camera Roll").
- Status changes (such as the change in the camera mode, capture mode, etc.) are not reported.
- etc. (see below).

Steps to reproduce it:
1. Launch NVDA.
2. Launch the Camera app.
3. Press TAB to "walk around" in the interface of the Camera app. You'll notice the following:
- The "Settings" button is reported by NVDA as "Settings true" button, while Narrator calls it only "Settings".
- The "Capture button is called by NVDA as "Capture 0" and "Capture 1" depending on the capture mode (0 is for photos and 1 is for video) and the 0 state is reported as checked and the 1 as not checked. Narrator calls it only "Capture" and I think it doesn't report check status.
- When you are on the "Capture" button and switch the modes via UP and DOWN arrow keys, Narrator reports the mode to witch has the camera switched. NVDA doesn't do that.
- The label for the "Camera Roll" button is reported by NVDA as "Camera roll true", while Narrator reports it only as "Camera roll". This button opens the Photos app in the folder (called "Camera roll") with the photos and video recordings from the Camera app.
- If you have 2 or more cameras connected, a "Switch camera" button will appear in the Camera window. If you press it, the app switches to the other camera. In this case NVDA doesn't say anything, but Narrator reports to witch camera has the app switched.
- On the right of the "Switch camera" button is the "Control mode" button. If you have the "Switch camera" button, you may need to press right arrow key to move  the focus to the "Camera mode" button - TAB doesn't do it in this case for this group of buttons. The issue here is that when you press the "Camera mode" button, Narrator reports the switching between "Professional" and "Automatic" camera modes, but NVDA does not.

Test environment:
- Operating system: Windows 10 Pro N, 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: next-12489,2c555c3.
- Windows Camera app version: 5.49.3004.0.
- Processor: Intel (R) Core (TM) 2 Duo CPU E7400 at 2.80GHz.
- RAM Memory: 4.00 GB.
- Graphics: Palit GeForce GT 630, 1024MB dedicated memory + 2047MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC888 at Intel 82801JB ICH10 - High Definition Audio Controller.

**Comment by ehollig** [comment]
I am not able to replicate this from the instructions provided in the previous comment. I am able to access all components of this app similar to Narrator. Has the camera app changed since this was reported?
CC @josephsl

**Comment by josephsl** [comment]
Hi,

Live region change event handling should fix some problems. The only annoying thing is that certain controls with no names raise live region change events, and I'll take care of that as part of next version of Windows 10 App Essentials add-on before asking @MichaelDCurran to take my PR.

Please reopen if folks run into other problems with this app.

Thanks.
