### ISSUE TITLE
how to get the voice of html table structure on mouse over

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5318]
**Reported by lokesh on 2015-08-28 12:54**
Hi Helpdesk,

Can you help us in letting know, how do the NVDA will read the row numbers and column numbers when we mouse over the content in the table.

for example:
Table:

Header1   Header2   Header3
Test1     Test2     Test3

When we mouse over on the above 2nd row-1st column:  "Test1" content.

Expected voice read out is: Row 2 “Header1” column 1 “Test1”

but It voices out only "Test1"

Please let us know how to address this scenario.

Thanks in Advance!
Lokesh

**Comment by leonardder** [comment]
Closing as invalid. This was posted in an issue tracker, which is not a help desk. :) The author asked how to accomplish table cell coordinates reading for mouse tracking, and this is currently not possible. The author didn't explicitly state the demand to implement this feature. Please file a new issue if you belief this should happen.
