### ISSUE TITLE
Carousel not reading for next or previous page contents on mouse hover in chrome

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5319]
**Reported by lokesh on 2015-08-28 13:12**
Hi Helpdesk,

The pages where we have used carousel, the voice reads out only for the first carousel content, but whereas when I click on next carousel the voice doesn't read out the new content, instead it reads out the previous carousel content only.

This is happening only in Chrome browser.

Please help us in solving this.

Thanks,
Lokesh

**Comment by ehollig** [comment]
Closing, as we do not have enough information to replicate the issue, the original poster did not reply to @josephsl's request in https://github.com/nvaccess/nvda/issues/5319#issuecomment-155342835, and we are unable to contact the original poster for more information, as far as I am aware.
