### ISSUE TITLE
Prevent reading the Hidden content in IE on Mouse hover

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5320]
**Reported by lokesh on 2015-08-28 13:27**
Internet Explorer all versions

NVDA Version 5.1

How to prevent the voice reading of hidden content. For hiding we are using display:none. When I tried using the html attribute area-hidden="true" but that also did not solve the problem.

In Firefox & Chrome it doesn't read the hidden content, only in IE this is happening.

Can you please help us in letting us know how to resolve this?

Thanks,
Lokesh

**Comment by AleksueiR** [comment]
Just checked again: elements hidden with `visibility: hidden` and `aria-hidde="true"` are read on mouse over by NVDA 2016.3.

**Comment by feerrenrut** [comment]
P3 since this is a low impact bug for most use cases.

**Comment by Adriani90** [comment]
Closing as duplicate of #3281. In that issue the discussion is more detailed. So please comment on that issue.
