### ISSUE TITLE
Firefox how to prevent voice read out of link url along with link text

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5321]
**Reported by lokesh on 2015-08-28 15:14**
Firefox:

NVDA Version 5.1

On link mouse hover, it reads the link text but along with the full url starting from https://url.

In Chrome & IE it read outs only the link text.

Please help me in getting this issue resolved.

Thanks,
Lokesh

**Comment by ehollig** [comment]
I do not believe this is the case anymore.

**Comment by derekriemer** [comment]
closing, as I don't know what NVDA 5.1 is
