### ISSUE TITLE
Report current version on addon updates

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5324]
**Reported by leonarddr on 2015-08-29 05:27**
When you install an addon that is already installed, NVDA asks you to update. I think it can be a handy addition whenever NVDA reports the current version of the addon as well as the version being updated to. Furthermore, a downgrade warning could be considered in line with NVDAs update meganism.

**Comment by leonardder** [comment]
I don't know whether the @BeQa is the same BeQa, but it would be great if you'd be able to create a pr for this.
