### ISSUE TITLE
NVDA is freezing while activating The dialog window which is awailable in The ffdshow audio decoder. This issue can cause that Nvda can not be used. Or NVDA can respond after 8 or more seconds. The algorithms, which are responsible for getting The text from The dialog Window are very complex and are allocating many system resources until The text from this dialog box is ready for speech synthesizer or Brltty.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#533]
**Reported by janusz on 2010-01-18 20:45**
The algorithms, which are responsible for getting text information from The dialog Window, which can be accessed by recalling ffdshow  audio decoder. When user is triing to activate this dialog window, NVDA can freeze or user must wait more than 7 seconds until NVDA is ready for interactioning with user. This issue is also presented, if user is triing to use INSERT and 4 or 6 key, which is awailable on The numeric key pad. The Klitecodecpack, where The ffdshow filter is awailable can be downloaded by using The following direct link. 

ftp.tw.xemacs.org/cpatch/media/k-lite/klcodec561f.exe

The package download syze is 14,7 MB. It is necessary to install this package, please let installer to chose The default settings. To spend Yours work and to free Your time from downloading and using compatible multimedia player, You can activate The dialog Window by exactly running The following command. I love procedures direct calls from dynamic linked libraries by using rundll32.exe command. It is a little pleasure for programmers.

C:\WINDOWS\system32\rundll32.exe ffdshow.ax,configureAudio

This command will not run if You will not execute it from The  

\Program Files\K-Lite Codec Pack\ffdshow

The installation program for Klite codecpack will create necessary links for activating some configuration options without need to run compatible multimedia player. Please explore The Programs folder detaily and You will find out, which special links have been created. Please, try to fix this issue. Many visually impaired users would be very deeply appreciating The programmer, who would create new application setting file specifically for all dialog windows, which are awailable for managing all codecs and filters. The purpose of this new application settings file is to force NVDA to get The labels of all editable fields and other important user interface controls. Because The source code of those dlls is frelly awailable, it is very nice C programming language complex source code, somebody would get those labels by analysing all source code or somebody would try to get in touch with The core developers of The Klitecodecpacks and all dlls. This codecs is ammazing, visually impaired user can modifi The sound while plaing multimedia content without need to load The multimedia file to The sound editor. The dolby filter and other modules are working reliably. Be very careful while exploring and experimenting with all numbers for modifiing The equalizer. IN some relationships between various settings, Your computer would freeze and You would have to be forced to turned it of force.

**Comment by leonardder** [comment]
I just tested this with a recent version of the K-Lite Codec Pack and it all seems to work like a charm. I'd suggest a close as works for me
