### ISSUE TITLE
Skype for Business (Lync) Does Not Read New IMs

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5333]
**Reported by adm_76 on 2015-09-09 13:55**
When using Skype for Business, a new IM in the window that has focus is not automatically read.  There is no indication that a new message has arrived, unless you set the software itself to give an alert.

I have no idea what relationship this product has, code-wise, with the consumer Skype application.

**Comment by ehollig** [comment]
CC @michaelDCurran, should this have been fixed in #7281? Although, this issue is dealing with a new message when the window has focus, and #7281 deals with when the focus is not on the window.

**Comment by michaelDCurran** [comment]
Fixed in PR #7287.
