### ISSUE TITLE
NVDA is sluggish and frequently says "unknown" in  internet explorer 11 on windows 7

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5334]
**Reported by pranavlal on 2015-09-09 14:01**
NVDA 2015.3 is sluggish and I frequently hear the word "unknown" when navigating to websites. In terms of sluggish, I was typing in an edit box in gmail which was set to the basic  html view. The echoback of typing was slow and I was unable to hear anything when I navigated character-by-character using the left and right arrow keys. Moreover, the speech feedback I got namely "blank" was delayed by over 2 seconds in coming. The same thing happens when typing in the search box on google.com and in other editboxes.

I frequently hear the word "unknown" when I navigate to a website or when a website is loading.
1. Launch internet explorer.
2. Hit ctrl+o to invoke the dialog box for entering a URL.
3. Visit a site that has a fair bit of javascript such as
http://www.emc.com/security/rsa-archer-governance-risk-compliance/index.htm .
4. I will hear "unknown" as the webpage loads.

I am attaching a large log file that contains debug output of a session where this happened. Search for the line
Trying to recover from freeze, core stack:
to get to the error quickly.
In terms of software setup, NVDA is running on a Linovo thinkpad T420 laptop with windows 7 professional. This is my work machine so is locked down.

**Comment by leonardder** [comment]
CC @DKager, this sounds similar to the issues you had when you once removed Supernova. Think I forget whether and where you reported this

**Comment by dkager** [comment]
This is not the same. I didn't experience sluggishness and didn't get "unknown". Instead I didn't get output at all for some cases.
The issue you were looking for is #6177.

**Comment by dkager** [comment]
PS: of course this also smells like worksforme.

**Comment by ehollig** [comment]
CC @pranavlal, is this still the case, or can it be closed.

**Comment by pranavlal** [comment]
This can be closed. This is no longer the case.
