### ISSUE TITLE
Powerpoint 2003 note wiev while browsing edit box  with notes issue

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5338]
**Reported by janusz on 2015-09-09 15:17**
Dear developers,
I Am using newest NVDA development snapshot, Windows 10 X64 bit edition. Microsoft Office 2003 standard for students and teachers. I AM running 32 bit release of Office 2003. I AM using all latest office 2003 updates but Windows update for Windows 10 did not allowed me to install last available office 2003 update from available office 2003 updates list. When I Am using notewiev wiev mode, when pressing Enter and when focus get inside note editbox, arrow keys are producing NVDA alarms and following bug attached inside attachment.

**Comment by leonardder** [comment]
Honestly, I don't know what notewiev wiev mode is supported to mean. Closing as won't fix due to the age of powerpoint 2003.
