### ISSUE TITLE
SayAll on long bits of text seems to fail randomly

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5339]
**Reported by RichCaloggero on 2015-09-09 15:19**
Mostly experienced in Firefox on long bits of text like a full-length article. SayAll seems to either quit completely after a while, or randomly skip to previously read text and re-read it.

**Comment by ehollig** [comment]
I am not able to replicate this.
Tested using SayAll using Firefox 54.0.1 (32-bit) on a Wikipedia article.
@jcsteh any ideas?

**Comment by ehollig** [comment]
Duplicate of #1726
