### ISSUE TITLE
NVDA 2015.3 makes Windows Luetus crash

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5342]
**Reported by jkinnunen on 2015-09-09 16:11**
Windows Luetus is a program made by the Finnish Federation of the Visually Impaired that is used to read electronic publications such as newspapers and magazines. NVDA 2015.3 makes this program to freeze and/or crash. The crashes do not occur with NVDA 2015.2.

**Comment by ehollig** [comment]
@jkinnunen, are you the original poster of this ticket? If so, can you provide any updates or steps to reproduce so that I may be able to reproduce the issue?

**Comment by ehollig** [comment]
As we are unable to contact the original author of this issue for more information and exact steps to reproduce, I am going to close this as invalid.
