### ISSUE TITLE
Inconsistent behaviour. Pressing [Enter] or [Space]  does not register as a 'click' on some modal windows

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5345]
**Reported by stephen.khuu on 2015-09-09 16:26**
On Chrome, using the NVDA reader to navigate to the 'close' button on a dialog and using [or [Space](Enter]) to click on the close button does not always work.

When it doesn't work, hitting [or [Space](Enter]) will just cause the 'close' button to go out of focus.

Happens on Chrome  v44.0.2403.157, Windows 10 Pro

Example of where it's not working:
 http://itstiredinhere.com/accessibility/ (look for the launch accessible modal)

 Examples of where it is working:
 http://accessibility.oit.ncsu.edu/training/aria/modal-window/version-2/
 http://www.visionaustralia.org/digital-access-dialog
 http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/ (dialog widget)

**Comment by smashuu** [comment]
It also happens with the [Twitter Bootstrap modal demos](http://getbootstrap.com/javascript/#modals). 

I encountered this issue using Chrome 49.0.2623.87 (Official Build) m (32-bit). I spent some time testing it, and it seems to come down to the **role="dialog"** ARIA attribute on the parent modal element. If present, enter/space won't trigger a click event on buttons or links, and moves focus back to the modal parent. But when the role attribute is removed, clickable items work as expected.

**Comment by smithwib** [comment]
+1

**Comment by bhavyashah** [comment]
The URL http://itstiredinhere.com/accessibility/ no longer seems to be active.
@smashuu  @smithwib  Could you please share a direct URL to a webpage with a modal dialog where you are able to consistently and successfully reproduce the above described behaviour with recent versions of Chrome, NVDA and Windows 10?
CC @jcsteh  and @feerrenrut (for Webfix relevance)

**Comment by feerrenrut** [comment]
The [Twitter Bootstrap modal demos](http://getbootstrap.com/javascript/#modals) are still available, I was not able to reproduce this with Chrome Version `59.0.3071.115` however, I'm not actually that confident that I know what I am looking for. @smashuu  Could you please add steps to reproduce the problematic behaviour that you were seeing with the bootstrap examples?

**Comment by Adriani90** [comment]
I can reproduce this issue with chrome 71 and with Firefox 64.0.2.
STR:
1. Open the Twitter Bootstrap modal demos above
2. Press o to land on the modal dialog
3. Press enter on it
4. Navigate with arrow keys to "close" and press enter or space
5. Go to focus mode with NVDA+space bar and tab to close button and press enter or space

Actual: when pressing enter or space on "close button, the modal dialog still remains focused. You can only get out of it by tabbing multiple times.

Expected: the modal should be closed when pressing enter or space bar on the close button.
cc: @feerrenrut, @jcsteh

**Comment by jcsteh** [comment]
I can't get that Bootstrap dialog to close at all. Pressing enter on it in focus mode, clicking the buttons, nothing works. My feeling is that this is a bug in the example. It's also confusing because there are two close buttons, one at the top and one near the bottom.

**Comment by Adriani90** [comment]
In this case, should we close this issue as invalid? We do not have any updates from the initial author since years.

**Comment by Adriani90** [comment]
I am closing this issue as abandoned due to missing updates from the initial author.
