### ISSUE TITLE
NVDA skips lines while reading with a Braille Display

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5347]
**Reported by HungarianLaller on 2015-09-10 09:12**
I like to read in Notped, or in Akelpad.
In these applications, when I read a plain text, my nvda is keelping lines, and I should go back with the left route key on my braille display.
It is annoiing, if I am learning, or teaching.

**Comment by ehollig** [comment]
I recall there was an issue about this before but can not remember where I saw it. Any ideas @leonardder and other Braille experts?

**Comment by leonardder** [comment]
I do not know such an issue. @DKager, you must know if this is still the case. Any how, since we can't contact the original author and we are missing relevant details (what display does he use, what keys), I'd personally close this as invalid.

**Comment by ehollig** [comment]
Agreed
