### ISSUE TITLE
Many unicode characters are missing from the standard braille table

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#537]
**Reported by bramd on 2010-01-24 21:59**
Many characters such as bullets in lists on webpages and other Unicode characters such as letters with accents are not correctly displayed in braille.

It seems to display \x followed by a character code.

**Comment by jcsteh** [comment]
If there are specific characters missing in specific tables that you believe can/should be mapped, please [report issues to liblouis](https://github.com/liblouis/liblouis). Friendlier presentation of unknown characters will be addressed in #2949.
