### ISSUE TITLE
When generating developer documentation using scons devDocs, an error is generated

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5373]
**Reported by csamaha on 2015-09-18 21:40**
The developer documentation does not get created, but an error is generated and scons terminates.
## Steps to Duplicate
1. Clone the NVDA repository using git
2. switch to the nvda directory and type scons source user_docs to generate the source tree along with user documentation
3. Assuming this command completes successfully, type scons devDocs to generate the developer documentation
## Expected Results

The developer documentation should be created and placed in the output directory
## Current Results

a epydoc-log.html file is created in the output\nvda folder, and the following error appears in the terminal window:
UNEXPECTED ERROR:
'Text' object has no attribute 'data'

Use --debug to see trace information.
scons: **\* [output\devDocs\nvda] Error 3
scons: building terminated because of errors.
## Additional Info

I am able to duplicate this with NVDA version source-master-669bdf9.

**Comment by leonardder** [comment]
I'm able to reproduce this.
[Here](https://github.com/nvaccess/nvda/files/1733649/devDocs.txt) is the output I get.

**Comment by Adriani90** [comment]
cc: @michaelDCurran, @feerrenrut maybe this is related to a missing component when installing VS 2017? I had such an error but it was hapenning with the userguide and the keycommands.html. In my case Visual C++ ATL for x86 and x64 was missing.

**Comment by leonardder** [comment]
Visual C++ ATL is properly installed here.

I guess we can revisit this when updating to Python 3, in which case Doxygen may also need an update.

**Comment by Adriani90** [comment]
@leonardder is this issue still occuring with NVDA 2020.1 RC?

**Comment by leonardder** [comment]
We're no longer using epydoc.
