### ISSUE TITLE
NVDA core stack freeze in Windows 10 when pressing Enter on The mycomputer desktop item

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5376]
**Reported by janusz on 2015-09-20 12:24**
Dear core developers,
I have found out, that When pressing Enter key, NVDA core stack freeze. There are issues, that NVDA do not have correct event feetback so Core want to pump module which detect data from UI automation, but UI automation isbusy and can not provide this kind of event. I think, that NVDA want The info too fast, which is causing error. In other words, Windows core components are slower than NVDA except. I attach crucial nvda.log part related to this problem. The question is, why thisproblem did not exist in earlyer version of windows. May be, that some event feet back algorithm work incorrectly in Windows 10.
I can deeply debug this issue, give me instructions please how to deeply debug more detail. C++ NVDA dlls are very probably enabled and compiled to provide debug info from their C++ code if error would becausedby those dlls.
Or should I had to debug by using other technique?
IAm ready to constructively help You by intensively debugging including using special external debugger, if it would help and if You know about some kind of debugger, which would help us.

**Comment by Adriani90** [comment]
@fernando-jose-silva how is this now in Windows 10 1909 Update with NVDA 2020.1 RC1?

**Comment by fernando-jose-silva** [comment]
I no longer have this problem.
Thank you.
