### ISSUE TITLE
Say all issue

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5377]
**Reported by JamaicanUser on 2015-09-20 16:59**
When using different synths with NVDA while in say all, the following occurs when initials like Mr., Mrs., Dr., St. and others are encountered:
1. Espeak: There is a very little pause after the initials, like the screen reader is trying to end the sentence. So when Hello, Mr. James is encountered, the synth says Hello, Mister. James.
2. Nuance Vocalizer (Automotive and Expressive): The synth says Hello M R. James in the above case, and in the case of I'm in St. Thomas, the synth reports Hello Street (long pause) Thomas.
This does not happen at all when reading line by line or paragraph by paragraph.

**Comment by bhavyashah** [comment]
@jcsteh Does https://github.com/nvaccess/nvda/issues/5377#issuecomment-155343430 imply a wontfix/cantfix?

**Comment by jcsteh** [comment]
I think can't fix, though we can reopen if someone has a technical solution which is feasible and takes other languages into account.
