### ISSUE TITLE
list item number announced wrongly in Google's search edit box

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5378]
**Reported by bhavyashah on 2015-09-21 09:52**
STR
* Enter www.google.com in your address bar.
* Type something, say 'nvda' in the search edit field.
Now, press up and down arrow within the edit field itself to read the search suggestions.
Expected Result: NVDA reads the items or search suggestions on each arrow press, followed by the item number.
Actual Result: NVDA reads the list items or suggestions correctly, but, the number it assigns all the search suggestions is 1 of 1.
Test Environment
Mozilla Firefox 40.0.3
NVDA version 2015.3

**Comment by jcsteh** [comment]
Fixed by Google.
