### ISSUE TITLE
change different auditory indications or sounds of NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5382]
**Reported by bhavyashah on 2015-09-21 10:30**
As mentioned earlier, I am having to rely full time on headphones to use my computer, and I believe many NVDA users may be using headphones or earphones pretty often.
Personally, I don't find the various souns of NVDA too pleasant, if not sometimes unpleasant...
The Start and Exit tones are pretty simple, meaningful with their ascent and descent, and still decent, however, I truly dislike the focus mode and browse mode sounds, particularly the former. I don't extensively use snapshots so don't mind the Error sound's presence.
Could all the above four, at least the two extremes, be replaced with more pleasant and natural auditory indications? There are several complaints about the robotic nature of ESpeak itself, not me though, but that is beyond NVDA's help and control, but, could this audio area have some scope for enhancement?
I don't have any suggestion samples, however, if anyone does, please do share. 
I try to listen to computer audio in my headphones at the bare minimum for long term safety, but, the few yet very frequent NVDA sounds just aren't my liking.
P.S. I have heard JAWS' forms mode and the other browse mode equivalent mode sounds, they are pretty good, much better than NVDA's, just saying, I don't necessarily want them to be copied or such.

**Comment by jcsteh** [comment]
See also #1007. However, that issue is more about allowing users to customise the sounds, as opposed to changing the bundled sounds.

**Comment by jcsteh** [comment]
Feedback on #7218 , #7393, these two [nvda-devel](http://nabble.nvda-project.org/New-sounds-in-next-snapshots-td42138.html) [threads](http://nabble.nvda-project.org/Feedback-from-me-on-new-sounds-td42079.html), social media and elsewhere suggests that while some users are happy with the new sounds, a significant number of users have concerns (e.g. difficulty in discerning the sounds) or are vehemently opposed to them. As a result, we're going to revert this change, and given the amount of difficulty in satisfying various groups, we are not going to consider any alternatives in the near term. Eventually, our aim would be to allow add-ons to more easily provide sound packs; see #1007. I'm going to lock comments on this issue; further discussion at this point is not useful. Thanks to those who provided feedback.
