### ISSUE TITLE
focus existing NVDA Settings dialog if the same dialog is attempted to be opened again instead of presenting Error dialog

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5383]
**Reported by bhavyashah on 2015-09-21 16:57**
STR
- Press NVDA + Ctrl + V to open the NVDA Voice Settings dialog.
- Now, retain your position or go elsewhere, and press NVDA + Ctrl + V once again.
  Expected Result: Focus should move to the Voice Settings dialog itself, because, apparently, the user wishes to access the same dialog.
  Actual Result: The Error dialog is presented informing the user that an NVDA settings dialog is already open and only upon it closure can another dialog be opened.
  My conclusive request here is that the focus move to the dialog itself when one tries to open it, unaware that it is already open. The user's ultimate intention is to access that dialog and he might still prefer the keystroke over Alt Tabbing to it if too many windows are open.
  In my case, I prefer to always keep the Voice Settings dialog open alongside any work I do, because background noise around me tends to fluctuate. Accordingly, I continuously and conveniently change the volume of NVDA's speech. While closing multiple windows, or due to other reasons, I sometimes close the dialog, but, when it is already open, the Error dialog quite a bit annoys me, because it simply informs me that it is already open, and I still need to navigate to it manually.
  I hope my request has been clearly expressed and substantially justified.

**Comment by leonardder** [comment]
@feerrenrut, any thoughts about this?

**Comment by feerrenrut** [comment]
I haven't thought this through at all, but my first thought on how to approach this would be replacing the boolean `_hasInstance` with a composite type, including the class type of the instance (and `None` when there is none) and a function to give it focus, perhaps even a function to close it. Then the check can tell if the dialog attempting to be opened is the same as already opened and give it focus. This approach could also help when exiting of NVDA is blocked due to an open dialog. Care will need to be taken in the exit case, to avoid losing unsaved changes.

**Comment by Qchristensen** [comment]
Now that we have a combined settings dialog, does that make implementing this easier?  I can see a situation where even with the dialog still focussed, you might be in the keyboard settings section and want to go to the voice settings, so you press NVDA+control+v.  Ideally this should simply change to that settings page.

**Comment by leonardder** [comment]
I think it shouldn't be very difficult to do indeed.

**Comment by JulienCochuyt** [comment]
UX proposal:
When attempting to open an NVDA dialog while one is already open:
- If this is the same dialog (including a different category in settings), just bring it forward and focus it (eventually switching categories)
- if this is a different dialog, show the current error message, but offer the possibility to focus the previously opened dialog with OK or to cancel the request - as is currently done by pressing OK.

What do you think?

**Comment by cary-rowen** [comment]
Is there any new progress on this issue? I think this kind of error prompt will make people feel unacceptable and confused. If this is improved, it will undoubtedly improve the user experience to a large extent.
