### ISSUE TITLE
NVDA announces empty table cells in layout tables as "blank"

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5391]
**Reported by jmuheim on 2015-09-24 15:15**
NVDA announces empty table cells in layout tables as "blank". I have created an example demo here:

http://developer-guide.access4all.ch/en/examples/hide_empty_table_cells_in_layout_tables.html

I think it would be nice if NVDA didn't announce empty table cells in layout tables (the same way JAWS does).

**Comment by leonardder** [comment]
This is related to #4904

**Comment by Adriani90** [comment]
@jmuheim could you please provide a new example to test? The link in the description does not work anymore.

**Comment by Adriani90** [comment]
We didn't get any updates upon request from the initial author since more than 5 years, closing as abandoned. This is also probably related to #13110.
If you are still having this particular issue, please comment with an updated minimal test case and we can reopen.
