### ISSUE TITLE
Support Cryptload or JDownloader

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#540]
**Reported by Agent Golder on 2010-01-26 15:59**
They are both programs to download .ccf container files. This system is used on most of the warez forums especially in Greece. And nobody screen reader works with them at the time.
The adress for downloading cryptload is www.cryptload.info. I don't remember the site of the second right now...
Can you do something please???

**Comment by leonardder** [comment]
Looks quite abandoned, and, if no screen reader works with this software, it is probably better to fix issues in the software itself.
