### ISSUE TITLE
Firefox: Performance Degradation since merging #2039 Fix

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5411]
**Reported by elliott94 on 2015-10-11 20:07**
Since the merge of e04e8e7 which was done to decrease the jumping of the cursor whilst navigating in Browse Mode, possibly somewhat ironically I have been experiencing much worse performance than previously. :) This mainly occurs whilst reading through links, and whilst this is somewhat annoying it also has an effect on which link is actually activated when a press of enter is performed. I've experienced a situation around 10 times within the last 24 hours whereby I'll focus on a link that I'm interested in, open Firefox's right-click menu and choose to open the link in a new tab or copy its URL to the clipboard, only to find out that I've either activated or copied the previous link that had previously received focus on the page. Somewhat strangely, however, when closing the menu and re-opening it to in theory copy or activate the exact same link as before, the correct URL is focused without any further user intervention.
**Blocking #2039**

**Comment by jcsteh** [comment]
Closing, since this was fixed by the revert of our first attempt at #2039.
