### ISSUE TITLE
Firefox: Deleted Characters Not Always Announced

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5412]
**Reported by elliott94 on 2015-10-11 21:12**
Similar to that of #5115, I am experiencing some strange behaviour whilst using Firefox that appears to happen randomly - annoyingly, it can't be produced by carrying out a list of pre-defined steps.

Whilst in Focus Mode and editing text, NVDA will sometimes not announce the characters that have been deleted when using the backspace key. This may only occur on a single character, or in certain situations may happen with several - just as an example, it's happened on 4 individual characters that have been deleted whilst composing the description of this ticket. I'm sorry that I'm not able to provide any more useful information - has anybody else ever experienced something similar?

**Comment by ehollig** [comment]
@elliott94, is this still the case for you? If so, could you provide a test case where this happens?

**Comment by elliott94** [comment]
I believe I have, but I can't think of any recent cases. Happy for this to be closed; I'll re-open if/when I see this again.

**Comment by ehollig** [comment]
Alright. Closing per request in https://github.com/nvaccess/nvda/issues/5412#issuecomment-323122413. If you can reproduce it, please open a new issue with exact steps to reproduce.
