### ISSUE TITLE
strange behavior in NVDA with Hims braille in office word when I type Korean letters

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5416]
**Reported by khsruru on 2015-10-14 03:41**
Hello, I’m using NVDA with Hims braille display.
In office word, if I type Korean letters, braille display scroll key action become strange.
If I type English letters, it is okay.
But if I type Korean, even if I press braille scroll key, it is not move to the next line.
It only moves panning in same line, but is not move to the next or prior line.
Please check this issue and fix it.

Thank you.

**Comment by ehollig** [comment]
@josephsl: do you think this is a Korean issue or a Hims braille issue? I wonder if this still exists

**Comment by leonardder** [comment]
@khsbory: Could you provide an update for this issue? Does it still occur?

**Comment by leonardder** [comment]
I'm closing this because it seems like we are unable to contact the original author of this issue. Furthermore, there is a completely new hims driver.
