### ISSUE TITLE
Presentation role and form fields problem in Firefox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5424]
**Reported by oaron on 2015-10-16 20:57**
In Firefox, if there is a definition list with  presentation role, NVDA announces everything in one line.
For example:

<dl role ="presentation">
<dt><label for ="username">User name</label></dl>
<dd><input id ="username" name ="username" type ="text"></dd>
</dl>

In Internet explorer, it works properly, so I can move with the up and down arrow keys between label and its editbox.

**Comment by ehollig** [comment]
Original author states that he can not reproduce the issue. I am unable to either. Suggest a close.

**Comment by leonardder** [comment]
Seems like a one time occurrence indeed. Closing.
