### ISSUE TITLE
Chrome application "line": cursor tracking in the editable text field

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5425]
**Reported by surfer0627 on 2015-10-17 23:40**
Hi, 
Here is a cursor tracking problem in Chrome application "line".
STR
1. Open Google Chrome.
2. Download and install line at:
https://chrome.google.com/webstore/detail/line/menkifleemblimdogmoihpfopnplikde?hl=en
3. Login account. (Users need to register E-mail address on mobile.)
4. Choose a friend to chat.
5. Press NVDA+space to switch to focus mode and type text string.
6. Press alt+tab to move away and move back again, 
or switch to browse mode, press up arrow one time, press down arrow one time, and switch to focus mode again.
NVDA will lost the correct cursor tracking position.
It seems that this field does not recognize as an editable field. NVDA recognize it as an editable section. And single letter navigation "e" could not move to it.

If this is not a NVDA issue and needs external fix. What kind of technical information should be included while contacting the app developers to fix it?
Thanks.

**Comment by bhavyashah** [comment]
Does this bug still stand? @surfer0627 If yes, should this be investigated and tackled as part of Project Webfix? @jcsteh @feerrenrut

**Comment by jcsteh** [comment]
Definitely not a candidate for webfix because it's specific to an app which isn't widely used.

**Comment by Adriani90** [comment]
@surfer0627 can you still reproduce this issue?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author for more than four years now. I am closing this issue as abandoned.
Please comment on it and we can reopen it if needed. Thanks.
