### ISSUE TITLE
Errors when composing a message in Outlook 2016

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5429]
**Reported by dkager on 2015-10-19 14:08**
In Outlook 2016, I get speech but no braille feedback when composing a message. Using NVDA master-11459,f859d5e, also confirmed with next-6fd9ad3. With braille disabled I get fewer errors, but there are still some left. See the attached logs. Apologies if this is a dupe (or if I'm a dupe).

STR:
- Launch Outlook 2016 (64-bit in my case).
- Open a new message (Ctrl+N). This is where the first error appears.
- Tab to the Subject field and enter some text.
- Tab to the message body. NVDA speaks 'Waiting for Outlook'. With braille disables this is where the second error appears.
- With braille enabled, you get more errors as you tab from field to field.

**Comment by dkager** [comment]
Since attachments don't appear to have been migrated to GitHub, this is the remaining error when starting Outlok 2016, in this case on Windows 10.

```
ERROR - RPC process 7916 (nvda_slave.exe) (12:47:56):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 90, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1165, in GetActiveObject
  File "_ctypes/callproc.c", line 945, in GetResult
WindowsError: [Error -2147221021] Operation unavailable
```

**Comment by Adriani90** [comment]
@dkager are you still seeing this error in Outlook 2016 with NVDA 2018.4.1? @ehollig could you please upload the attachments from Tracker? Thank you.

**Comment by dkager** [comment]
Heh, this is surely very outdated. I haven't seen this problem in years. Closing.
