### ISSUE TITLE
Pluralisation in Excel Elements List

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5430]
**Reported by JamaicanUser on 2015-10-19 19:33**
This is as trivial as they come.
In Browse Mode for Word/PDF/Internet, etc, the types of elements that are listed are pluralised, for example, lists, headings and annotations. In Excel, however, this is not the case. Chart instead of charts, formula instead of formulae, etc. Why is this the case? Is it an unintentional error?

**Comment by jcsteh** [comment]
Incubated in 40f4151e (done as part of #5527).
