### ISSUE TITLE
no Turkish language when adding prefered language in language detection dialog

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5438]
**Reported by fatih on 2015-10-24 08:54**
hi,
I don't see the Turkish language in the add language diolog of the language detection dialog son I can't use e-speak Turkish voice.
**Blocking #2990**

**Comment by Adriani90** [comment]
cc: @dineshkaushal

**Comment by Adriani90** [comment]
This seems fixed in NVDA 2023.1, no idea when it was fixed but now both languages appear in the language list of eSpeak. Closing as works for me.
