### ISSUE TITLE
Windows 10: Problems With the Logon Screen

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5440]
**Reported by JamaicanUser on 2015-10-25 16:54**
Hi.
When using NVDA on the Windows 10 logon screen, I experience the following issues:
1. Sometimes, when the computer has just booted up, or come out of sleep, NVDA only reports "Windows Sign In", but the focus is in the password edit field.
2. The correctness of the password is not announced. Neither is the state of the dialog, as in Welcome, or cannot connect right now.
3. NVDA reads out the password sometimes. In some cases, it reads out one letter before saying "star star star"
4. Even when enter is pressed, NVDA still says "star star star" as if a password is still being typed.
Overall, the Windows 10 logon screen needs major improvement. I'm using Windows 10 (64-bit) build 10240

**Comment by bhavyashah** [comment]
I would be surprised if this is still existent, given NVDA's strides in improving Windows 10 and Edge support in the last two years, plus the popular Windows 10 App Essentials add-on. Does the described behaviour still take place? @josephsl

**Comment by josephsl** [comment]
Hi,

Loging status announcement: to be taken care of by live region change event.

Please reopen if any of the issues discussed above happens on builds 10586 and later. Thanks.
