### ISSUE TITLE
Windows 10 Notifications and Actions Settings: Toggle buttons do not announce state change

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5441]
**Reported by jteh on 2015-10-25 22:25**
STR:
1. Open Notifications and Actions Settings.
2.    Press "Select which icons appear on the taskbar".
3. Press one of the "pressed" (enabled) buttons.
 * Expected: NVDA should say "not pressed".
 * Actual: Nothing.
4. Press the same button again.
 * Expected: NVDA should say "pressed".
 * Actual: Nothing.

This change does get reported by Narrator. Beyond this, we might also want to consider reporting these as toggle buttons and perhaps rethink the way we report toggle buttons altogether.

**Comment by nvaccessAuto** [comment]
Incubated in 445da157eaebf4cc863ad3b0507cccbb42799bb7.

**Comment by josephsl** [comment]
Hi,
A number of regressions were observed:
1. "Not pressed" is spoken on checkboxes, certain buttons and so on.
2. the toggle button for toggling certain settings such as Tablet Mode no longer announces pressed state (this could be just mine).
Thanks.

**Comment by josephsl** [comment]
Hi,
Upon further investigation, it appears toggling Tablet Mode and other items from Settings app does produce the intended result, with the first regression still remaining. Thanks.

**Comment by nvaccessAuto** [comment]
Incubated in 85403ad94f3ba18cacff24cc6e13c0439a12cc57.
