### ISSUE TITLE
Prevent NVDA audio from being ducked by other audio

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5443]
**Reported by jteh on 2015-10-28 00:34**
Windows 8 and later can duck the volume of other audio when high priority audio is playing. This includes [alarms in Windows 10](http://nabble.nvda-project.org/NVDA-and-alarms-notifications-in-Windows-10-td38755.html). We should ensure NVDA is not ducked in these cases. This can be done using the AccSetRunningUtilityState function with ANRUS_PRIORITY_AUDIO_ACTIVE_NODUCK.

**Comment by jcsteh** [comment]
We were originally going to do this separately, but it seems it does depend on #3830, so it's been done as part of that now.
