### ISSUE TITLE
Failing to call super in plug-in constructor breaks script handling

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5446]
**Reported by jteh on 2015-10-30 06:43**
@tspivy noted that failing to call super in a plug-in constructor completely breaks all script handling where the plug-in is queried. For global plug-ins, this means the entirety of NVDA.

I haven't tested this myself, but it makes sense. The ScriptableObject constructor is what sets _gestureMap and getScript assumes this is present. We should probably catch and log exceptions when calling gesture.script in InputManager.executeGesture, since we _really_ don't want that method throwing exceptions.

**Comment by leonardder** [comment]
I'd say a p3 is ok for this, as this is causing problems for external contributions only? cc @jcsteh @michaeldcurran

**Comment by michaelDCurran** [comment]
Gave it a p3. Although serious when it happens,  the developer of the plugin would have surely noticed it when developing.
