### ISSUE TITLE
ia2TextMozilla: exception: AttributeError: 'NoneType' object has no attribute 'obj'

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5454]
**Reported by parham on 2015-11-02 17:13**
When using the Telegram web application at http://web.telegram.org, I get the error sound. I'm using NVDA version master-11546,170b139. Below are the steps to reproduce:
1. Login to Telegram.
2. Use the search or recent conversations to find someone to chat with.
3. Focus on the edit box, just above the "Send" button, and type something, then press enter.
4. You will hear the error sound.

The log is pasted below:

```
ERROR - scriptHandler.executeScript (20:38:17):
error executing script: <bound method Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible.script_caret_newLine of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible object at 0x02ABF190>> with gesture u'enter'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 186, in executeScript
  File "editableText.pyc", line 128, in script_caret_newLine
  File "speech.pyc", line 673, in speakTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 291, in getTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 240, in _getText
AttributeError: 'NoneType' object has no attribute 'obj'
DEBUGWARNING - NVDAObjects.IAccessible.Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible._get_IA2Attributes (20:38:17):
IAccessibleObject.attributes COMError (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getCaretOffset (20:38:17):
IAccessibleText::caretOffset failed
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 151, in _getCaretOffset
COMError: (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))
```

**Comment by ehollig** [comment]
It sounds from the comments that NVDA doesn't lose focus and there is no noticeable effect aside from the error sound. This problem probably does not exist anymore. I would suggest a close, unless the author continues to have issues with this.

**Comment by leonardder** [comment]
It is quite likely that Telegram has changed since the initial report, but I've seen those "AttributeError: 'NoneType' object has no attribute 'obj'" messages myself as well. I wonder whether exception handling should be removed at some point.

**Comment by jcsteh** [comment]
I think this occurs when an editable text control dies just before (or during) NVDA's attempt to query information from it. P3 to investigate and hopefully find a way to handle these exceptions gracefully. Not p2 because we haven't found a case where it actually breaks functionality.

**Comment by Adriani90** [comment]
This gradually improved after #8479 has been merged. Has anybody seen this error recently still?

**Comment by jcsteh** [comment]
I see it very frequently when typing in Google Docs.
