### ISSUE TITLE
outdated copyright on NVDA community portal

### ISSUE THREAD

**Issue by nvdaTrac** [nvaccess/nvda#5459]
**Reported by bhavyashah on 2015-11-03 13:45**
The last line on the NVDA community portal reads: Copyright © 2014 NV Access, www.nvaccess.org
I do not understand much about copyrights, however, should this 2014 not be changed to 2015?

**Comment by jcsteh** [comment]
Thanks for reporting. As of yesterday, this is no longer relevant, as the Trac-based NVDA community site has been replaced by GitHub.
