### ISSUE TITLE
Sentence Navigation in Browse Mode

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5463]
**Reported by eatbird on 2015-11-04 22:19**
Hi,
I am wondering if it might be possible to add sentence navigation commands to NVDA's Browse Mode. I tend to read articles aloud to people, and find that sentence navigation is the easiest way for me to do this. Also, with complex information, sometimes the arbitrary line lengths make things more difficult to understand.

**Comment by jcsteh** [comment]
Browse mode is used for many different controls/applications and the ways we access content in those different cases are also quite different. The way in which we access content determines whether it's possible to do sentence navigation.

There are two pieces to supporting sentence navigation:

1. The really hard part: A way to retrieve the start and end of a sentence.
    - Some applications have their own idea of sentences and we can ask these applications to tell us where a sentence starts and ends. Microsoft Word is a good example, and support for this was implemented in #3288.
    - Some applications do not have such a concept, so we can't ask them. In this case, we need to use our own heuristics to figure this out, which means coming up with some way to detect sentences across multiple languages. Unfortunately, even if we can find the start and end of a sentence, moving the cursor there might not be possible because a "character" is not necessarily one single character as we normally think of it; e.g. in a word processor, a date/time field might be considered one character. This is covered by #1873.
2. The simple part: Once we have a way to retrieve the start/end of a sentence, we need commands to move there. #3288 implemented such commands for editable text, but these have not yet been implemented for browse mode.

Leaving this open to deal with point 2 above.

**Comment by bhavyashah** [comment]
Does Word have public documentation on how it defines a sentence? If so, can NVDA co-opt that definition and universalize it?

**Comment by Adriani90** [comment]
I am closing this in favor of #8518 which covers a more broader scope and a much more detailed discussion on technical part.
