### ISSUE TITLE
Outlook 2010: Cursor is stuck when encountering an image within an HTML email

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5478]
I should start by saying that at this time, I have unfortunately not been able to pinpoint when this particular issue occurs; that said, for the average user it may understandably cause a problem when it does.

When reading HTML messages in Outlook 2010, I've noticed that in emails that contain an image that the cursor will sometimes become stuck when attempting to navigate up/down, and that instead a right arrow is necessary to continue reading further text. I've tested sending myself similar messages; however, inserting an image and adding alt text does not seem to reproduce the issue successfully. Has anybody else seen anything similar, and if so could the cause be something that's relatively easy to fix?

**Comment by nvdaTrac** [comment]
Are you able to reproduce this 100% of the time in certain emails or is 
it sporadic even with the same message? If the former, are you able to 
provide us with a message where this occurs?

**Comment by Adriani90** [comment]
@elliott94 I cannot reproduce this issue. Are you still having it with NVDA 2018.4.1?

**Comment by elliott94** [comment]
Happy to close for now; I haven't seen this since.
