### ISSUE TITLE
Firefox: Tooltips announced when navigating message lists in Gmail whilst using Basic HTML view

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5480]
Whilst navigating the Inbox of Gmail's Basic HTML view by links using the Elements List dialog, the words "tool tip" are consistently announced when the user has navigated several links down the list. Since these are announced before the actual link that currently has focus, I often end of activating these wrong links. Whilst a workaround is to simply read the current line each time I navigate further down the list, this ultimately takes more time than would be necesary if these were not announced.

**Comment by jcsteh** [comment]
Do you have reporting of tool tips enabled in NVDA's Object Presentation 
dialog? If you do, this will read tool tips (which appear after a short 
delay). You probably want to disable this if you don't want this to 
occur. Note that this is disabled by default.

**Comment by elliott94** [comment]
I do have this enabled; that said, this behaviour only occurs with the Basic HTML view of Gmail, and on no other web page when I invoke the Elements List.

**Comment by jcsteh** [comment]
At a guess, I'd say the links are very long (as they tend to be in email 
message lists). This means they can't fit on the screen, so the Windows 
tree view control displays a tooltip containing the full text if you 
hover or are focused on one of the items for a short period.

**Comment by elliott94** [comment]
Ah, that would make sense. :) Assuming this is in fact the case, I'll close this for now and reopen if it turns out to be something else.
