### ISSUE TITLE
add keystroke to jump to the end of landmarks

### ISSUE THREAD

**Issue by sukiletxe** [nvaccess/nvda#5482]
Rationale: Sometimes, mostly in news sites, an aside landamark is found inside a main landmark. That makes the reading experience rather unpleasant. Adding a keyboard command to jump to the end of a landmark would improve the reading experience. Maybe it will make the announcement of the ending would make nVDA too chatty thoguh.

**Comment by jcsteh** [comment]
Rather than consuming an extra keystroke, it'd be good if we could have landmarks included in the move past end of container command (comma). This could be a bit tricky, though.

**Comment by derekriemer** [comment]
If I want to give this a try, are there any things I should know?
