### ISSUE TITLE
Outlook 2010: "Message" appended to output in message list after restart

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5485]
Upon a first run of Outlook 2010, whilst reading through items in the message list NVDA simply reads them depending on their status; for example, it may read something like "unread from Username". After a restart of the software, however, the text "message" is appended to the start of output; instead of the above example, the user is presented with "message unread from Username", which although it may seem minor adds time when quickly skimreading through messages. Using Object Navigation hasn't helped in determining whether it's simply a case of the extra text being added; that said, I don't see how that would make sense and why Outlook would only appear to do this after a restart. Has anybody else seen something similar?

**Comment by leonardder** [comment]
@Elliott94: Can you still reproduce?

**Comment by elliott94** [comment]
I can no longer reproduce this - happy for it to be closed.

**Comment by ehollig** [comment]
Per https://github.com/nvaccess/nvda/issues/5485#issuecomment-316145926, closing
