### ISSUE TITLE
Lock keys double announce when Speak command keys is on

### ISSUE THREAD

**Issue by ObjectInSpace** [nvaccess/nvda#5490]
Use Insert 2 and insert 4 to activate "speak typed characters" and "speak command keys." Then hit a "locking" key (caps, num, or scroll.) NVDA will say the name of the key, then the name of the key again, and then its state. Pressing caps lock, for example, will cause NVDA to say "caps lock, caps lock on."

**Comment by jcsteh** [comment]
If someone wants to take a stab at this, it should just be a matter of making KeyboardInputGesture.shouldReportAsCommand return False for caps lock.

**Comment by josephsl** [comment]
Hi,

 

Are there other toggle commands that should be taken care of in addition to caps lock? Thanks.

**Comment by jcsteh** [comment]
Actually, all toggle keys. I think there's a TOGGLE_KEYS constant 
somewhere in keyboardHandler for this.

**Comment by jcsteh** [comment]
Incubated in f0e78d7b.
