### ISSUE TITLE
outlook message list problem

### ISSUE THREAD

**Issue by abdullah5490** [nvaccess/nvda#5495]
while navigating in outlook 2013 or 2016 message list, NVDA mostly stop speaking the messages by aerrow keys. than restarting NVDA and outlook, both at the same time, fix the issue temporarily, but it happen again after few minutes or seconds of navigation. it starts happening in the latest master release of NVDA which is 11581, 6a318b2.

**Comment by ehollig** [comment]
@abdullah5490 is this still the case with Outlook 2016 using NVDA 2017.2?

**Comment by abdullah5490** [comment]
@ehollig Hi there. Actually i'm not using outlook as my default e-mail client anymore. But i'll confirm you in my next comment after configguring outlook in few hours.

**Comment by abdullah5490** [comment]
no @ehollig this issue is resolved i think, because i;m using outlook from 1hour but it doesn't act in a problematic way.

**Comment by leonardder** [comment]
Closing as works for me, as the author says so. Please request a reopen if this is still occurs at some point.
