### ISSUE TITLE
When in win8.1 pressing windows key with command keys on incorrectly doesn't announce that the user pressed windows key

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5497]
Using windows 8.1 do the following.

1. Press nvda+4 to enable reporting of command keys.
2. Press windows key.

## Windows does:

not announce the command keys.

## Windows should:

Announce all command keys.

**Comment by jcsteh** [comment]
There are two problems here:

1. The Windows key is often a modifier. We don't want to speak a modifier as a command key. For example, if the user pressed Windows+r, the user would first hear "Windows", followed by "Windows+r" when they pressed r. We don't speak alt for the same reason, even though alt by itself often opens a menu. The only solution to this problem would be to speak the key when it is released (not when it is pressed), but this would require a fair amount of refactor.
2. Even if we fixed this, pressing the Windows key causes the Start Screen to appear, which is a foreground change. We silence all speech on foreground changes, which is usually what the user wants; you don't want to have to wait for the alt+tab list to finish speaking when you release alt+tab, for example. The announcement of "Windows" would therefore be silenced.

For the above reasons, IMO, this isn't worth addressing unless you can give me solid reasons to the contrary.

**Comment by derekriemer** [comment]
### d

No. I agree. I personally don't use speak command keys, because it is 
way to verbose for me, but thanks for explaining.
On 11/16/2015 6:27 PM, James Teh wrote:
>
> There are two problems here:
>
>  1. The Windows key is often a modifier. We don't want to speak a
>     modifier as a command key. For example, if the user pressed
>     Windows+r, the user would first hear "Windows", followed by
>     "Windows+r" when they pressed r. We don't speak alt for the same
>     reason, even though alt by itself often opens a menu. The only
>     solution to this problem would be to speak the key when it is
>     released (not when it is pressed), but this would require a fair
>     amount of refactor.
>  2. Even if we fixed this, pressing the Windows key causes the Start
>     Screen to appear, which is a foreground change. We silence all
>     speech on foreground changes, which is usually what the user
>     wants; you don't want to have to wait for the alt+tab list to
>     finish speaking when you release alt+tab, for example. The
>     announcement of "Windows" would therefore be silenced.
>
> For the above reasons, IMO, this isn't worth addressing unless you can 
> give me solid reasons to the contrary.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5497#issuecomment-157230603>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.drupalgardens.com>
Non-proffessional website. <http://derekriemer.pythonanywhere.com/personal>
Awesome little hand built weather app that rocks! 
<http://derekriemer.pythonanywhere.com/weather>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194
