### ISSUE TITLE
enhance report formating

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#550]
**Reported by filokas on 2010-02-08 14:47**
Insert+f should anounce the margins of the document, the margins of the actual paragraph, the space between lines, level of the paragraph, etc. Each item would togle on and off.
**Blocking #671**

**Comment by leonardder** [comment]
I think all have been added, except for margins, but I'm not entirely sure.

**Comment by feerrenrut** [comment]
I'm struggling to work out what the status of these github issues is. It seems like someone is going to need to go through them and test what is implemented and what isn't and summarise it on each issue.

**Comment by feerrenrut** [comment]
Since most of this seems to be implemented (excluding margins) I'm going to close this issue. If there is some use case for margins, please open a new issue, and provide an example document and the expected output. Thanks!
