### ISSUE TITLE
Focus management with JavaScript seems to be very quirky

### ISSUE THREAD

**Issue by jmuheim** [nvaccess/nvda#5503]
I'm trying to figure out how to set focus to elements upon user interaction using JavaScript.

What I expect is that after a user presses a button or a link the focus is moved to another element (focusable or non-focusable) and properly announced. This should work both in browse and focus mode.

I have created a very simple CodePen for demo purposes: http://codepen.io/jmuheim/pen/YyBdNv

I'm working with JAWS 16 and NVDA 2015.3 on Firefox 42 and Internet Explorer 11.

**Results in NVDA+IE**
- Focusing "Jump to paragraph" link (using tab) and activating it (using enter) moves the focus to the paragraph as expected, and it is announced as "Hello, paragraph  edit".
  - While "Hello, paragraph" is correct, it definitely isn't an edit field.
  - Also, NVDA enters focus mode (the beep sound occurs); I guess this has something to do with NVDA perceiving the paragraph as edit field?
- Focusing "Jump to input" button (using tab) and activating it (using enter) moves the focus to the input as expected, and it is announced as "edit\n\nHello, input"
  - This looks correct to me

**Results in NVDA+FF**
- Focusing "Jump to paragraph" link (using tab) and activating it (using enter) moves the focus to the paragraph as expected, and it is announced as "Hello, paragraph".
  - This looks correct to me
- Focusing "Jump to input" button (using tab) and activating it (using enter) moves the focus to the input as expected, and it is announced as "edit has auto complete. Hello, input".
  - This looks correct to me

**Results in JAWS+IE**
- Focusing "Jump to paragraph" link (using tab) and activating it (using enter) moves the focus to the paragraph as expected, and it is announced as "Hello, paragraph".
  - This looks correct to me
- Focusing "Jump to input" button (using tab) and activating it (using enter) moves the focus to the input as expected, and it is announced as "Hello, paragraph edit. Hello, input type in text".
  - This looks very strange to me: not only the input is announced, but also the preceding paragraph, AND IT IS ANNOUNCED AS "edit"

**Results in JAWS+FF**
- Focusing "Jump to paragraph" link (using tab) and activating it (using enter) moves the focus to the whole document
  - This is not what's expected
- Focusing "Jump to input" button (using tab) and activating it (using enter) moves the focus to the whole document
  - This is not what's expected

Very interesting: when clicking with a mouse on the link, the focus is set to the paragraph correctly, but still the document is announced, not the paragraph.
Also, when clicking with a mouse on the button, the focus is set to the input correctly, and then the document is announced and then the input.
And (very controversial): when no screenreader is running, the example is working perfectly in IE (using the keyboard)! So JAWS seems to break the "core" functionality of the example in IE.

**Conclusion**

Using NVDA, Internet Explorer feels very quirky to me.

Using JAWS, both Internet Explorer and Firefox feel very quirky.

This is devastating, as it seems that not even very basic functionality behaves the same in the most used screenreaders and browsers.

Or am I missing something importan? Are there ways to optimise the behaviour? Maybe my JavaScript code is not clean, or I'm using the wrong events or something like that (I'm no big JS expert)?

**Comment by jcsteh** [comment]
To clarify, the only case you're encountering trouble with using NVDA is focusing the paragraph in IE?

In short, what we get from IE's accessibility implementation does make this look like an editable text field, so we'll need yet another IE hack to work around this.

Implementation note: Perhaps add "P" to the list of tags for which we ignore MSAA in MSHTML.role (currently line 710 of NVDAObjects/IAccessible/MSHTML.py).

**Comment by jmuheim** [comment]
> To clarify, the only case you're encountering trouble with using NVDA is focusing the paragraph in IE?

Yes, as far as I can see, this is the only problem.

**Comment by jmuheim** [comment]
Just as a sidenote: another accessibility consultant told me to set a label for the input, and after doing this, JAWS handles the situation as expected.

It seems that JAWS tries to collect data heuristically when there is information missing. So in the current example, the label for the input was missing, and JAWS used the adjacent paragraph as label..

Why JAWS set the focus to the whole document und FF though is a mystery. After adding the label, it's working though.

The problem in NVDA persists, though.

**Comment by michaelDCurran** [comment]
I was going to look into this, but it seems the testcase has changed. Could you please provide a link to the original testcase, or at least provide updated instructions on how to reproduce the issue with the new testcase. Thanks.

**Comment by leonardder** [comment]
@jmuheim: Could you please provide a status update and/or address the question in https://github.com/nvaccess/nvda/issues/5503#issuecomment-160480296?

**Comment by jmuheim** [comment]
This is very long time ago. I close it. If it occurs again, I'll reopen.
