### ISSUE TITLE
On focus to the empty text field NVDA says blank

### ISSUE THREAD

**Issue by babupca** [nvaccess/nvda#5505]
Hi All,
When we focus to the text field which is empty, the NVDA say's the field is blank. Please clarify whether this is the default behavior of this tool.

**Comment by babupca** [comment]
Is there any answer for this question, 

JAWS Tool : 
In this tool, when we focus to the input field, which is empty it does not say as "blank", instead it reads  as "edit text" and the id of the input field

NVDA Tool
In NVDA, when we focus on to input field, which is empty it is saying as "blank" 

Please clarify us, whether this is the issue with the tool or this is the default behaviour of the NVDA tool.

Thanks for understanding.

**Comment by jcsteh** [comment]
Please be more specific. If you mean does NVDA say "blank" when the 
field contains no text, then yes, this is the intended behaviour so that 
the user knows the field contains no text. However, I'm guessing you 
mean something other than the text of the field.

**Comment by babupca** [comment]
@jcsteh ,

Thanks James for clarifying the query. Yes i asked only about the form fields, when it is empty it says (NVDA) as 'blank'. 

When tested with the JAWS tool, we did not encountered this 'blank' keyword on focusing to the empty keyword, that's why we came into the doubt whether this is the correct behavior or not. 

Once again thanks conforming that, this is the intended behavior.
