### ISSUE TITLE
problem with donation website

### ISSUE THREAD

**Issue by mohdshara** [nvaccess/nvda#5513]
steps to reproduce:
1. open www.nvaccess.org/donate
2. select monthly donation of 20 dollar.
3. press the donate button.
expected: the page should load and ask for an email address or whatever to proceed with donation. actual: nothing happens as far as things go here with Firefox 42 or IE windows 10. same is true with Safari and Firefox on IOS.

**Comment by michaelDCurran** [comment]
Thanks for reporting. An error in the javascript on my part introduced yesterday.
Fixed now.
