### ISSUE TITLE
IE 10+ aria-hidden attributes lost

### ISSUE THREAD

**Issue by pkra** [nvaccess/nvda#5514]
Separating this from #5283.

For background, MathJax's new AssistiveMML extension which makes MathJax's visual output aria-hidden and embeds raw MathML visually hidden. 

Here is a simple demo: http://s.codepen.io/pkra/debug/NGojag

Using NVDA 2015.3 on IE10 (Win 7 VM from modern.ie) and IE11 (Win8.1 VM from modern.ie), this is voiced as "a fraction, x 2" and with MathPlayer "a fraction. x 2 x over 2". 

Looking at the DOM explorer, it seems the `aria-hidden` attribute is lost. That is, when opening the page without NVDA running, the aria-hidden attribute is listed, with NVDA running it is stripped (with IE11 I still see remnants: `="true"`). The aria-hidden attribute is lost with or without MathPlayer installed.

In case it's relevant, this problem does not occur with Firefox or Chrome; it also does not occur on IE9.

**Comment by pkra** [comment]
The related issue was #5283; sorry.

**Comment by jcsteh** [comment]
I can't reproduce this. In your test case, the outerHTML for the node says:

```
<span class="mjx-math" id="MJXc-Node-1" role="math" aria-hidden="true"><span class="mjx-mrow"...
```

Also, we never write to the DOM, only read from it.

**Comment by pkra** [comment]
D'oh! I should've known not to trust an IE developer console... I'm just creating noise it seems -- sorry!
