### ISSUE TITLE
Case sensitivity of searches in virtual buffers are not preserved with find next

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#5522]
STR:

1. Find a webpage that contains some text both with and without capitals, e.g. The and the.
2. Press NVDA+Ctrl+F, type the text with capitals.
3. NVDA finds the text. Now rpess NVDA+F3.
4. Eventually NVDA will find an occurrence without capitals.

**Comment by dkager** [comment]
And a patch in dkager/nvda@d64fb8b. Feel free to not use it and do something far more sophisticated!

**Comment by dkager** [comment]
My ‘strong reason’ is that if I perform a case sensitive search, then ask for the next result, I expect that next search to also be case sensitive. This is especially true in the log viewer (#4929, which I also worked on today). But also when searching through developer documentation in browse mode, if you are looking for SOMETHING you probably don’t want to find SomeThing with the next search (note the caps). Similarly, it struck me as odd that the last search text is preserved but the state of the case sensitive checkbox isn’t.

**Comment by dkager** [comment]
Having given this some more thought I still think this suggestion makes sense: consecutive searches for a phrase should use the same parameters that were used in the initial search for that phrase. Whether a new search should also remember the parameters is a topic of discussion. I think this is useful but I can imagine others may find it confusing. And of course these parameters should not be persistent, i.e. they revert to their defaults when you restart NVDA.

Any renewed thoughts on this Joseph? :) I'm not trolling (well, not intentionally). I just ran into real-world cases where I'd like my search parameters to be preserved as described above. For example, when searching in JavaDoc files.

**Comment by jcsteh** [comment]
I don't recall the previous discussion on this, but IMO, if someone is willing to code it, we should preserve this setting (but not across restarts of course). Aside from anything else, this is consistent with other programs that have find functionality. I can't think of any find dialog which doesn't keep the settings across executions.

**Comment by derekriemer** [comment]
In reguards of implantation:
I have refactored def onOk(self, evt):
         text = self.findTextField.GetValue()
         caseSensitive = self.caseSensitiveCheckBox.GetValue()

         wx.CallLater(100, self.activeCursorManager.doFindText, text, 
caseSensitive=caseSensitive)

to
def onOk(self, evt):
         text = self.findTextField.GetValue()
         caseSensitive = self.caseSensitiveCheckBox.GetValue()
         self.caseSensitive = caseSensitive
         wx.CallLater(100, self.activeCursorManager.doFindText, text)


and might be able to remove the whole arguement for caseSensitive from 
doFindText and then have doFindText lookup the option from 
self.caseSensitive. Is this a rework you guys are okay with?

On 1/6/2016 4:04 PM, James Teh wrote:
>
> I don't recall the previous discussion on this, but IMO, if someone is 
> willing to code it, we should preserve this setting (but not across 
> restarts of course). Aside from anything else, this is consistent with 
> other programs that have find functionality. I can't think of any find 
> dialog which doesn't keep the settings across executions.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5522#issuecomment-169490363>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.drupalgardens.com>
Non-proffessional website. <http://derekriemer.pythonanywhere.com/personal>
Awesome little hand built weather app that rocks! 
<http://derekriemer.pythonanywhere.com/weather>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment]
If you do self.caseSensitive, you're storing it on the instance of the dialog. That instance gets thrown away as soon as it's done, so it won't get preserved across finds. Instead, you need to store it as a class attribute (not an instance attribute) on CursorManager. That also allows you to get rid of the caseSensitive argument to doFindText.

**Comment by derekriemer** [comment]
Done. I will commit tomorrow. Btw, unless anyone objects (doubt it) I am 
gonna update the copyright date of source/cursorManager.py to 2016 with 
the pr.

On 1/6/2016 10:43 PM, James Teh wrote:
>
> If you do self.caseSensitive, you're storing it on the instance of the 
> dialog. That instance gets thrown away as soon as it's done, so it 
> won't get preserved across finds. Instead, you need to store it as a 
> class attribute (not an instance attribute) on CursorManager. That 
> also allows you to get rid of the caseSensitive argument to doFindText.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5522#issuecomment-169560260>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.drupalgardens.com>
Non-proffessional website. <http://derekriemer.pythonanywhere.com/personal>
Awesome little hand built weather app that rocks! 
<http://derekriemer.pythonanywhere.com/weather>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by derekriemer** [comment]
See pull request https://github.com/nvaccess/nvda/pull/5662/files

On 1/6/2016 10:43 PM, James Teh wrote:
>
> If you do self.caseSensitive, you're storing it on the instance of the 
> dialog. That instance gets thrown away as soon as it's done, so it 
> won't get preserved across finds. Instead, you need to store it as a 
> class attribute (not an instance attribute) on CursorManager. That 
> also allows you to get rid of the caseSensitive argument to doFindText.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5522#issuecomment-169560260>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.drupalgardens.com>
Non-proffessional website. <http://derekriemer.pythonanywhere.com/personal>
Awesome little hand built weather app that rocks! 
<http://derekriemer.pythonanywhere.com/weather>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by dkager** [comment]
Also, the checkbox should get the right selection state based on this attribute of course. See my commit linked to in a comment above, which was rather dirty but shows what I had in mind.

**Comment by derekriemer** [comment]
Oh. We do indeed preserve the text's state as part of the find dialog. I 
probably should preserve the case sensitivity as well.
On 1/7/2016 8:16 AM, Davy Kager wrote:
> Also, the checkbox should get the right selection state based on this 
> attribute of course. See my commit linked to in a comment above, which 
> was rather dirty but shows what I had in mind.
>
>
>
> From: James Teh [mailto:notifications@github.com]
> Sent: Thursday, January 07, 2016 06:43
> To: nvaccess/nvda <nvda@noreply.github.com>
> Cc: Davy Kager <mail@davykager.nl>
> Subject: Re: [nvda] Case sensitivity of searches in virtual buffers 
> are not preserved with find next (#5522)
>
>
>
> If you do self.caseSensitive, you're storing it on the instance of the 
> dialog. That instance gets thrown away as soon as it's done, so it 
> won't get preserved across finds. Instead, you need to store it as a 
> class attribute (not an instance attribute) on CursorManager. That 
> also allows you to get rid of the caseSensitive argument to doFindText.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5522#issuecomment-169560260> 
> . 
> <https://github.com/notifications/beacon/AC9y8Wh17WPfHudkjH3n3qfFfwHrFLl1ks5pXfKBgaJpZM4Gmcxe.gif> 
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5522#issuecomment-169690915>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.drupalgardens.com>
Non-proffessional website. <http://derekriemer.pythonanywhere.com/personal>
Awesome little hand built weather app that rocks! 
<http://derekriemer.pythonanywhere.com/weather>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by derekriemer** [comment]
Just updated the pr.

On 1/7/2016 8:16 AM, Davy Kager wrote:
> Also, the checkbox should get the right selection state based on this 
> attribute of course. See my commit linked to in a comment above, which 
> was rather dirty but shows what I had in mind.
>
>
>
> From: James Teh [mailto:notifications@github.com]
> Sent: Thursday, January 07, 2016 06:43
> To: nvaccess/nvda <nvda@noreply.github.com>
> Cc: Davy Kager <mail@davykager.nl>
> Subject: Re: [nvda] Case sensitivity of searches in virtual buffers 
> are not preserved with find next (#5522)
>
>
>
> If you do self.caseSensitive, you're storing it on the instance of the 
> dialog. That instance gets thrown away as soon as it's done, so it 
> won't get preserved across finds. Instead, you need to store it as a 
> class attribute (not an instance attribute) on CursorManager. That 
> also allows you to get rid of the caseSensitive argument to doFindText.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5522#issuecomment-169560260> 
> . 
> <https://github.com/notifications/beacon/AC9y8Wh17WPfHudkjH3n3qfFfwHrFLl1ks5pXfKBgaJpZM4Gmcxe.gif> 
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5522#issuecomment-169690915>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.drupalgardens.com>
Non-proffessional website. <http://derekriemer.pythonanywhere.com/personal>
Awesome little hand built weather app that rocks! 
<http://derekriemer.pythonanywhere.com/weather>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by dkager** [comment]
Awesome!

**Comment by derekriemer** [comment]
Note that I have a pull request open for this, and in terms of code review, this should be an easy one because there's not that much code.

**Comment by josephsl** [comment]
Hi,

On my way to do code review.

**Comment by derekriemer** [comment]
I think you reviewed the PR for this a while ago and it stalled. We had 
to update a copyright date and after that it was not re reviewed.


On 5/6/2016 5:42 PM, josephsl wrote:
> Hi,
>
> On my way to do code review.
>
>
>
> From: derekriemer [mailto:notifications@github.com]
> Sent: Friday, May 6, 2016 4:41 PM
> To: nvaccess/nvda
> Cc: josephsl; Comment
> Subject: Re: [nvaccess/nvda] Case sensitivity of searches in virtual 
> buffers are not preserved with find next (#5522)
>
>
>
> Note that I have a pull request open for this, and in terms of code 
> review, this should be an easy one because there's not that much code.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5522#issuecomment-217588214> 
> Image removed by sender.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5522#issuecomment-217588374>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by josephsl** [comment]
Hi,

Uh oh, we need to nudge devs a bit then… If there’s virtually no change between the code I reviewed and the new commit, then I’d say we should wait for a little while until @jcsteh can take a look at this further. Thanks.

**Comment by tmthywynn8** [comment]
jcsteh commented on Jan 7:
> this is consistent with other programs that have find functionality.

1. Speaking of consistency, should we change the check-box's label to "Match case", like in almost all Find dialogs?
2. Also, should the accelerator key be Alt+C rather than Alt+S (e.g. Notepad, Wordpad, and Firefox)?
3. Oh, and for future reference, should I be opening a new ticket even though the issue somewhat relates, i.e., expected or standard behavior?
