### ISSUE TITLE
Excel 2010: Spaces not announced when deleting data

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5524]
STR:
1. Open a new Excel workbook, and type "Test 1" into A1
2. Without removing focus from the active cell, hit the Backspace key twice. The removal of the "1" character should be announced, but nothing should be output when the space is removed

Whilst it's possible to edit cell content by hitting F2, it'd be great if this could somehow be resolved - it can sometimes be confusing when this isn't announced!

**Comment by jcsteh** [comment]
This is a display model issue. The problem is that we can't be sure when there is a space at the end; it's possible the "space" isn't even "written" to the screen. @michaelDCurran, any thoughts?
