### ISSUE TITLE
Microsoft Lync 2010: IM window not initially focused when invoked

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5525]
When opening a new IM session from within Lync 2010, NVDA doesn't seem to be able to interact with the window immediately; it's not possible to see what content has been composed without first shift-tabbing to the message history, and then regaining focus on the edit field where a new message is composed. I realise that Lync in particular may be an application that not many people have had experience of using; would more information about the structure of the window be helpful here?

**Comment by leonardder** [comment]
CC @Elliott94, is this still an issue for you?

**Comment by elliott94** [comment]
I unfortunately no longer have access to a working Lync installation. Happy for this to be closed.

**Comment by ehollig** [comment]
Thank you for the update. Closing for now. If you find that this problem still exists, we can reopen this issue.
