### ISSUE TITLE
Excel: Same shortcut key used for Filter and Formulas controls in Elements list dialog

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#5527]
alt+f is used for Filter and Formulas control in the Elements list dialog. This makes difficult to select one of them.

**Comment by nvdaes** [comment]
A pull request is created for this at
https://github.com/nvaccess/nvda/pull/5528

**Comment by nvaccessAuto** [comment]
Incubated in 40f4151ea55a73ff83231753c0b7ebeee14f5eb8.

**Comment by nvaccessAuto** [comment]
Incubated in 40f4151ea55a73ff83231753c0b7ebeee14f5eb8.

**Comment by nvdaes** [comment]
Thanks, I will announce this on spanish mailing list, where the bug was
reported.
