### ISSUE TITLE
Firefox or thunderbird, problems in options dialog

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#5530]
In Firefox or Thundrbird, when scrolling the options list, elements of the list are not always spoken.
I guess this is because when passing from one option to other, many other objects change in the dialog.
This occurs in many programs having this kind of interface instead of tabs.

**Comment by leonardder** [comment]
@MichelSuch: is this still an issue? If so, could you provide steps to reproduce for either thunderbird or firefox?

**Comment by ehollig** [comment]
Just a friendly reminder for @MichelSuch to respond to @leonardder's comment in https://github.com/nvaccess/nvda/issues/5530#issuecomment-315717352

**Comment by bdorer** [comment]
I can't see any problems at the moment, so I wote for closing as 
worksforme. If he's able to show us his problems we can reopen.

Am 13.10.2017 um 17:18 schrieb Ethan Holliger:

**Comment by ehollig** [comment]
Agreed. If this is still an issue, please provide exact steps to reproduce the issue and we can reopen this issue. Closing as worksforme
