### ISSUE TITLE
represent the flags in NVDAObjects window winword as hexadecimal numbers

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#5531]
Spun off #5500, suggestion by @dkager. The flags in NVDAObjects window winword are nou represented as decimal numbers 1, 2, 4, 8, 16, etc. Converting them to hexadecimal numbers (0x04, 0x08, 0x010, etc.) is prefered, since it is shorter, improves readibility and allows one to insert other flags without multiplying huge numbers.

**Comment by jcsteh** [comment]
Closing in favour of the PR, as this is a trivial code change which doesn't require discussion beyond coding style.
