### ISSUE TITLE
winamp equalizer

### ISSUE THREAD

**Issue by chrisbelle2015** [nvaccess/nvda#5533]
Many folks still use this good old stand by media player even though it's not made anymore.  The other main screen-readers, jaws and wineyes both support the equalizer, knowing which band and where it is set.  Would love to see NVDA functionality in this regard.  I am using the winamp module for NVDA right now, and it is indeed a useful addon.  Perhaps this could be updated to support the equalizer?  Thanks for all the fine work of the NVDA team.

**Comment by jcsteh** [comment]
Please provide further, thorough details, including exact steps to 
reproduce, an example of what currently gets reported and what you 
expect instead.

**Comment by chrisbelle2015** [comment]
Ok, will try and explain.

When going in to winamp, you can press alt-g and get the equalizer window.
You can control-tab through various open child windows like the playlist 
and equalizer and such.
In the eq window, when you press n, that enables and by-passes the eq.
It should speak that but doesn't in NVDA.
When you have the eq enabled, you can use the top row numbers plus a 
corresponding letter underneath to raise and lower the eq band.
the far left is grave accent
which raises the pre-amp, and the tab key lowers it.
Then you keep taking pairs like 1 and q, 2 and w,
3 and e,
all the way up to 0
and p which raise and lower each consequtive band.
I forget at the moment the different in how wineyes and jaws both report 
the actual value of the setting,
let me bring them up and see,
ok, I've just rebuilt this machine and don't have the wineyes scripts in 
here but jaws actually seems to report a db value, with 0 in the middle,
it would be nice to get that spoken if available, I think wineyes just 
does a percentage, on a slider, anyway, I bet NVDA does the best job out 
of all of them getting the actual value.
Someplace I have the actual values of the bands frequency being cut or 
boosted,
I don't know if this is still the case, but a long time ago someone sent 
me this
frequency curves settings.
chart.

60
170
310
600
1k
3k
6k
12k
14k
16k

If this is still accurate, would be nice to hear the band being cut or 
boosted by it's frequency and then the db value.
Instead of band one or band 2 I can think and go oh,
band 6 is
3k, but is nice to hear the frequency values so you don't have to think 
about it.
but how ever it is easiest to do as long as we have some indication of 
where the slider is set, even if it's a relative value, as long as it is 
a set value that doesn't change arbitrarily, then it will be helpful.
Like if 10 is in the middle or flat, then I always know that's where the 
unity or flat position is.
And of course we want the pre-amp value spoken in some way,
I don't know if this helps, but winamp stores it's values for the eq in 
the winamp.ini file.
I don't know if this is updated in real time but I have actually changed 
those values and re-set winamp eq doing this.
so I know some programming can use .ini files to set values under the 
hood, so this might help instead of having to dely on some screen 
scraping method, I don't know how wineyes or jaws does it,
if they're grabbing something from the winamp ui or doing it on the 
visible interface itself, but I'll leave that to the
hotshot skilled programmer 'grin'.
I hope this gives some idea of what should be done, and thank you for 
your attention to this.


On 11/23/2015 3:03 PM, James Teh wrote:
> Please provide further, thorough details, including exact steps to
> reproduce, an example of what currently gets reported and what you
> expect instead.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5533#issuecomment-159063513>.
>


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by jcsteh** [comment]
So does NVDA read absolutely nothing right now when you press those keys 
to adjust the bands?

**Comment by chrisbelle2015** [comment]
It does not.

I am using winamp 5.666
As far as I can tell, there is nothing on the screen.
with object nav or cursoring around.
with other screen readers either.
I suspect this is being done somehow through the api.


On 11/23/2015 7:34 PM, James Teh wrote:
> So does NVDA read absolutely nothing right now when you press those keys
> to adjust the bands?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5533#issuecomment-159123658>.
>


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by ehollig** [comment]
Marking this as feature. Maybe something like this could be added to the already created [ExtendedWinamp addon](https://addons.nvda-project.org/addons/extendedWinamp.en.html)

**Comment by bhavyashah** [comment]
Winamp is sort of abandonware now. Time to close? @ehollig

**Comment by chrisbelle2015** [comment]
It is indeed, but still seems to be very popular in the comunity.
Look how long people stuck with reaper even after that Russian guy's 
abandon ware reaccess was getting long in the tooth and buggy,
it kind of was to begin with, but as long as tools work, they are worth 
having around, everyone get's this false sense of if it wasn't made 
yesterday, it's not worth anything, but that just simply is not so,
one has to balance old and new technology, and since our choices are 
more limited,
hanging on to and using older productivity tools sometimes is the best 
way for us.
I use other players as well,
foobar, and vlc, and the like, but winamp has some capabilities and 
scripting from jaws, and even window-eyes which make it a nice addition 
for various casual playback senarios,
and even rendering stems out with certain plug-in chains, I have found 
useful with the disk writer, and so this is something I'd pay someone a 
reasonable
fee to script the equalizer for me in winamp for NVDA but if that 
doesn't happen, I can use the other screen-readers which support it.
Cheers.

**Comment by Brian1Gaff** [comment]
Its still used a lot though.
 I wonder if somebody might wish to do this in an add on, assuming the way 
to do it is actually feasible in the software, though Jaws manages it.


Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment]
Winamp has been discontinued many years ago, and although the community tried to bring up a new version, it is still one that is not really maintained in a structured way.
I don't expect any further accessibility improvements to the old Winamp GUI. Closing as abandoned.
