### ISSUE TITLE
Reading entire documents

### ISSUE THREAD

**Issue by tech55541** [nvaccess/nvda#5535]
Hello,
When reading a large document with the mouse, such as a php file or css file, where ever you put the mouse NVDA reads from the beginning. In the last update 2015.3, NVDA read from wherever you put your mouse. 
The setting under Mouse Options Text Unit Resolution no matter what set to, the same behavior still happens.
The same behavior also occurs in the GitHub comment text field. If I put my mouse at the center of my comment, it starts from Hello, and reads on.
Thanks.

**Comment by jcsteh** [comment]
What browser are you using? Also, in the GitHub comment example, what 
unit did you have your mouse resolution set to (line, word, etc.)?

**Comment by tech55541** [comment]
I am using the latest version of Mozilla Firefox. It is set to Paragraph. However, no matter what I change it to, it still has the same effect.

**Comment by tech55541** [comment]
OK, so the mouse setting Text unit resolution does change something. It changes the effect of moving your cursor along published text, such as my comment above, what it doesn't change is text that is being typed in a text box. It does not change this for edited text in browse mode either.

**Comment by jcsteh** [comment]
Reading the entire comment is expected behaviour if set to paragraph. It's certainly not expected behaviour if set to line or word.

Regression introduced by #1668.

**Comment by tech55541** [comment]
Yes, agreed.

**Comment by nvaccessAuto** [comment]
Incubated in d8d5dcfa10c995a213a2c1d07edabb4b91e24e77.

**Comment by tech55541** [comment]
This is now fixed.
