### ISSUE TITLE
NVDA crash renders NVDA controller clients useless until system reboot

### ISSUE THREAD

**Issue by coltonhill01** [nvaccess/nvda#5540]
I have only noticed this in 2015.4, installed copy.
It appears that NVDA, if not exited properly, will drop support for NVDA Controller Client32.dll, used in applications such as skype talking, most invisible twitter clients such as chicken nugget and tw blue, and audiogames.
I have tried restarting said applications to restore the NVDA Control, no luck. I have also tried restarting NVDA properly along with the applications, still no luck.
It appears that only a system reboot will fix this issue.
I don't know if NVDA needs to crash itself or if you can just kill it with the task manager. I would test it, but I really don't like waiting for this computer to boot.
My NVDA occasionally crashes on this windows 8.1 quad core 8 gig RAM AMD family processor computer.
I don't know exactly what the crash is caused by, sometimes it will just stop speaking, and I'll restart it, and I'll hear the startup sound but no shutdown sound. This is using CTRL+ALT+N
You can try launching an application that uses the NVDA-Controller-Client32.dll file, and then killing NVDA with the task manager if it's an installed copy. This bug was not introduced on portables when I tested them, but they were snapshots of 2015.4.
If the application is still communicating with NVDA ppropperly, meaning sending it text to speak via the dll, such as screen reader friendly audiogames and TWBlue, then you may have to temporarily introduce a feature into NVDA's code that will actually make it crash and kill itself. I cannot trace the crashes as I am not familiar with python, at all, much less NVDA's usage of it.
This issue was reported on a windows8.1 machine, OEM moddle, CPU running usually at 100% in the event of a crash.
It also appears to still lock up speech interrupt when a program stops responding and loads a bit on the processor, but I don't know if you can fix that.

**Comment by jcsteh** [comment]
I assume you aren't able to reproduce this any more or similar given that you closed the issue?
