### ISSUE TITLE
Save Dialog: No feedback given when SharePoint location Selected

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5542]
When invoking the standard Save As dialog within an application, it appears that if a SharePoint location within the network has automatically been selected as the default save location no feedback is given on the current position of the cursor within the folder. This has only been tested on Windows 7; more information about the dialog can be provided if that would help. I realise that this description is somewhat vague!

**Comment by leonardder** [comment]
@Elliott94: What office version is this, and can you still reproduce?

**Comment by elliott94** [comment]
This was with Office 2010; unfortunately, I no longer have access to the SharePoint install. Happy for this to be closed unless anybody else can help.

**Comment by ehollig** [comment]
Closing as requested in https://github.com/nvaccess/nvda/issues/5542#issuecomment-315850438. If this is still an issue for someone, we can reopen.
