### ISSUE TITLE
Word 2016: Wrong colors are reported in NVDA

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#5544]
When I select green or blue as a text color in Word, it is reported by NVDA as Dark Turkoise. See [this](https://dl.dropboxusercontent.com/u/59700862/color%20issues.docx) file to reproduce (haven't been able to upload it, eventhough it's docx). I've been able to reproduce the issue with this particular file in both Word 2016 and Wordpad (Win 10)

**Comment by nvaccessAuto** [comment]
Incubated in 82448028340ffd6bbd3645521e2352c2b6df8469.

**Comment by michaelDCurran** [comment]
The above change at least now calls the green line in the example light sea green, but the bottom blue line is still dark turquoise... which as far as I can tell is pretty accurate anyway... it is certainly closer to aqua than blue on the spectrum.

**Comment by leonardder** [comment]
Thanks for fixing at least the Green one. I'll try and test some more of the default Word colors as soon as I've got more time.

**Comment by leonardder** [comment]
Updated the preview file slightly and added more of the default office colors:

* Green is now light sea green, light green is now yellow green. This strikes me as an usability issue, since it is not particularly easy to guess from the color names which is the lightest one.
* Purple is reported as dark slate blue
* Orange is reported as gold

**Comment by michaelDCurran** [comment]
Have these changed or were these other colors the same before the commit?

I have a feeling it is actually MS Word incorrectly labeling the colors 
too broadly. For instance, when I try and choose a font color in MS 
Word, I see things like blue accent 1, blue accent 2 etc.

Can you give exact steps of how you selected those colors?

On 2/12/2015 7:54 PM, Leonard de Ruijter wrote:
>
> Updated the preview file slightly and added more of the default office 
> colors:
>
>   * Green is now light sea green, light green is now yellow green.
>     This strikes me as an usability issue, since it is not
>     particularly easy to guess from the color names which is the
>     lightest one.
>   * Purple is reported as dark slate blue
>   * Orange is reported as gold
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5544#issuecomment-161242721>.
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by leonardder** [comment]
Before the commit, Purple was interpreted as Dark Orchid and green as dark turkoise, the others are the same.

STR:

1. Write text in Word and select it
2. Press ctrl+d to open the font dialog
3. Tab to "font color, and pres space
4. Press up arrow twice to go to the standard colors grouping
5. Select one of the colors in this grouping with the left and right arrow keys, and press enter
6. Close the window with OK

**Comment by michaelDCurran** [comment]
There seems to be a major discrepancy between the on-screen label, the 
MS Word color index constant, and the RGB value, for each of those 
standard colors.

For example: The MS Word standard color labeled as blue: its rgb value 
is 0,112,192. On the color spectrum this is half way between blue and 
aqua. True blue would be 0,0,255. Also, MS Word's color index constant 
for this "standard" color is teal (constant wdTeal). Even this is wrong 
as teal, according to wikipedia and the standard web colors, is half way 
between blue and green.

Another example is the MS Word standard color labeled as purple: its rgb 
value is 112,48,160. On the color spectrum this is really half way 
between blue and purple (probably best called violet). Yet the MS Word 
color index constant for this entry is pink (constant wdPink). Pink on 
the color spectrum in fact is really somewhere between purple and red.

In short those standard colors are just wrong. In fact, the user can 
actually change these standard colors... they could choose  to give the 
color labeled as "blue" an rgb value of say... yellow... if they really 
wanted.

I will admit I have no vision myself, though I did years ago. But after 
I get some sighted verification on actual perception of these colors on 
screen, I will think about whether or not to keep the change. Most 
likely it will be backed out and the issue closed as can't fix.


On 2/12/2015 10:07 PM, Leonard de Ruijter wrote:
>
> Before the commit, Purple was interpreted as Dark Orchid and green as 
> dark turkoise, the others are the same.
>
> STR:
>
>  1. Write text in Word and select it
>  2. Press ctrl+d to open the font dialog
>  3. Tab to "font color, and pres space
>  4. Press up arrow twice to go to the standard colors grouping
>  5. Select one of the colors in this grouping with the left and right
>     arrow keys, and press enter
>  6. Close the window with OK
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5544#issuecomment-161272999>.
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by leonardder** [comment]
Interesting, thanks for the comprehensive rationale. I think that fits 
for me.

**Comment by jcsteh** [comment]
It seems whatever we do here is going to cause problems for some case or another.

* It could be argued that we should report the colour names exactly as they appear in Word.
* Word can use the same name for several different colours, causing ambiguity.
* Regardless, it doesn't look like we can fetch the colour names used in Word.
* Even if we could, that would then make the colours reported in Word entirely different to the colours NVDA reports everywhere else.
* While the colour names NVDA reports might not match the application, the idea is that they should be consistent across apps. Despite the names, if a sighted user sees one colour in Word and the same colour in Wordpad, they know they're the same colour. We strive to make the same true for NVDA users.
* Colour naming is very controversial. We might revisit this if we can find solid data about a "better" scheme.
