### ISSUE TITLE
Add function to get selected text in api.py

### ISSUE THREAD

**Issue by kvark128** [nvaccess/nvda#5552]
Suggest to add in the module api.py the function returns the selected text.
Many plugins required to obtain the selected text and have to write fairly large function for this.
If no text is selected, function must return None.

**Comment by jcsteh** [comment]
The api module is poorly named and we aren't adding new functions to it. Also, while convenience functions can certainly be useful, I don't think we should in this case:

* I don't think this is something that requires it; I'd say this is 5 lines of code maximum if you want to catch exceptions. It's basically: `text = api.getCaretObject().makeTextInfo(textInfos.POSITION_SELECTION).text`
* It's not particularly versatile. What if you want to get the formatting for that selection?
* Having too many APIs to do one thing leads to confusion.
* It sets a slippery precedent. If we have a convenience function to get the selected text, why not the selected text with fields? Why not the line at the caret? Why not the word at the caret? Why not the next line after the caret? You get the idea.
