### ISSUE TITLE
Keyboard layout change is not reported in console windows

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#556]
**Reported by aleksey_s on 2010-02-13 08:34**
## steps to reproduce
- ensure you have more than one keyboard layout installed
- start->run->cmd
- type something and try to change layout
- ensure you are entering letters in newly set language
  ## current results

NVDA doesn't report the change to keyboard layout
## expected results

NVDA must gracefully report the change

**Comment by leonardder** [comment]
This works for me in Windows 10. It seems both @MichaelDCurran and @JosephSL reported a works for me as well, so I assume it's safe to close this.

**Comment by jcsteh** [comment]
This is probably only relevant to XP and Vista, both of which are now end-of-life. Closing.
