### ISSUE TITLE
Microsoft Lync 2010: No Feedback given in Search Field

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5561]
When searching for the name of a contact within the main Lync window, no information is provided when text has been typed. Whilst it's possible to find any matching results by tabbing to the Results list, it would be beneficial if text entered into the Search field could be reviewed.

**Comment by leonardder** [comment]
@Elliott94: Is this still an issue? Also, do you have a particular reason why you aren't using Skype for Business?

**Comment by elliott94** [comment]
Happy for this to be closed; at the time, we wern't using Skype for Business.

**Comment by ehollig** [comment]
Closing, as requested in https://github.com/nvaccess/nvda/issues/5561#issuecomment-315850715. If this issue still exists for someone, we can reopen this issue.
