### ISSUE TITLE
MS Word trac changes should not be reported if hidden

### ISSUE THREAD

**Issue by michaelDCurran** [nvaccess/nvda#5566]
Currently NVDA will report trac changes in MS Word documents even if "Hide markup" is chosen  under Trac changes in the Review tab of the ribbon. NVDA should instead ignore trac changes in this situation. Use  `WinwordWindowObject.view.showRevisionsAndcomments`

**Comment by nvaccessAuto** [comment]
Incubated in 4b4ff6fdc41bf659728393c5755536fdd9a10a86.

**Comment by michaelDCurran** [comment]
Blocked by #5486
