### ISSUE TITLE
NVDA freezing on system startup

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#5568]
I've noticed from some time now that NVDA may freeze at system startup after I login into my account. This seams to occur mostly if I don't start interacting with my PC after I login and leave it alone. In such a case I lose speech and I have to restart NVDA. I've managed to procure a log in witch I see some warning messages about the core being frozen in stack. I'll attach the log here. It seams to have started occurring maybe around the time the audio ducking was introduced, but I don't know if it has something to do with the freezes of NVDA or not.

Test environment:
- Operating system: Windows 10 Pro (build 10586.11), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version next-12862,0367e74.
- Processor: Intel Core i5-2320 at 3.00GHz.
- RAM Memory: 4.00 GB.
- Graphics: Palit GeForce GT 630, 1024MB dedicated memory + 2047MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC662 at Intel Cougar Point PCH - High Definition Audio Controller.

Unfortunately, the log is only at level "Information" and I don't know how useful it will be. Maybe I should set it to something else for the time being and grab the log after such a freeze occurs at startup (?).
[nvda-old-log.txt](https://github.com/nvaccess/nvda/files/49623/nvda-old-log.txt)

**Comment by jcsteh** [comment]
There was an [earlier report of this issue on nvda-devel today](http://nabble.nvda-project.org/nvda-is-increasingly-freeqing-up-on-me-td39363.html).

It seems NVDA did gracefully exit. How did you trigger this? Did you just press control+alt+n to restart it?

Brief technical summary: Core just seems to freeze in wx's main loop, which is really strange.

@michaelDCurran, can you think of any way this could possibly be related to audio ducking? I can't see how it could do this, but I can't think of anything else in next either.

**Comment by k-kolev1985** [comment]
Yes, in such cases I press Control+Alt+N or activate the desktop shortcut of NVDA to restart it (I have some vision left and I can see the icons well enough for that purpose).

**Comment by jcsteh** [comment]
If at all possible, would you mind running with NVDA 2015.4 for a few days (how ever long you think it would normally take for you to see the problem)? I'd like to try to figure out whether this and #5588 are related; the latter occurs with NVDA 2015.4. Btw, it is currently safe to downgrade from a current next snapshot to NVDA 2015.4 despite the downgrade warning.

**Comment by fernando-jose-silva** [comment]
good expensive day for two of my machines'm having this problem, both with windows 10586.

[nvda.log.txt](https://github.com/nvaccess/nvda/files/53776/nvda.log.txt)
[nvda.log.txt](https://github.com/nvaccess/nvda/files/53781/nvda.log.txt)
NVDA freezes some veses to start your computer, and always at precionar ctrl + alt + n, or restart NVDA the option of turning off NVDA.
Thanks,

**Comment by fernando-jose-silva** [comment]
[nvda-old.log.txt](https://github.com/nvaccess/nvda/files/53783/nvda-old.log.txt)

**Comment by fernando-jose-silva** [comment]
Sorry two files nvda.log.txt they are equal, I did not notice that the file had been attached to the first time. NVDA-old.log.txt file is different.

**Comment by jcsteh** [comment]
@k-kolev1985: Important question i forgot to ask: do you have audio ducking enabled?

**Comment by jcsteh** [comment]
@fernando-jose-silva: As above, do you have audio ducking enabled? Also, while the first log looks like the same issue, the second log shows a lot of errors from broken add-ons, but not the freeze discussed here. For the second machine, please try restarting with add-ons disabled.

**Comment by k-kolev1985** [comment]
@jcsteh - yes, I do have audio ducking enabled.

**Comment by fernando-jose-silva** [comment]
Good afternoon dear, to me, was something different.
A machine to restart NVDA with add-ons disabled NVDA froze.
On another machine it did not freeze, but after restarting the machine NVDA did not begin with more add-ons, ice, and even closing the NVDA process aplication.exe
the player does not start, now works only deleting the folder with the accessories and settings user and starting NVDA without supplements.
I will now make tests by installing an add-on at a time and see if I find out what happens.
Follow the logs of the two machines.

**Comment by fernando-jose-silva** [comment]
[pc1_nvda.log.txt](https://github.com/nvaccess/nvda/files/55570/pc1_nvda.log.txt)
[pc1_nvda-old.log.txt](https://github.com/nvaccess/nvda/files/55572/pc1_nvda-old.log.txt)
[pc2_nvda.log.txt](https://github.com/nvaccess/nvda/files/55569/pc2_nvda.log.txt)
[pc2_nvda-old.log.txt](https://github.com/nvaccess/nvda/files/55571/pc2_nvda-old.log.txt)

**Comment by fernando-jose-silva** [comment]
Unfortunately after several trials on the machine no longer starts with NVDA, not come to a conclusion, after installing add-ons 1 1 NVDA paresse freeze with different accessories, and randomly, for example, performed NVDA only with the complement nvSpeechPlayer; installed and it has not caught for a few reboots, after a three restarts in NVDA he returned to freeze, returning to work only after uninstalling the add-ons again.

**Comment by jcsteh** [comment]
@fernando-jose-silva: Again, do you have audio ducking enabled?

**Comment by fernando-jose-silva** [comment]
Yes 

Enviado do meu iPhone

**Comment by fernando-jose-silva** [comment]
Expensive to use the next version 12941 my problems starting NVDA ended on both machines.
Thank you for the attention of all, congratulations for the work done, and excuse the failures that I've had.

**Comment by jcsteh** [comment]
@k-kolev1985, is this fixed for you now too? We're hoping it should have been fixed by 974e1577 (which is in the latest next builds).

**Comment by k-kolev1985** [comment]
@jcsteh,  I'm running NVDA version next-12965,add0a23 and it seams that it is fixed - I haven't experienced freezes of NVDA on startup.
