### ISSUE TITLE
Problem Reading ShopRite's Website with Internet Explorer--It's Blank

### ISSUE THREAD

**Issue by n2fgc** [nvaccess/nvda#5569]
Good evening,

I tried to access the http://Shoprite.com website with Internet Explorer 11 and NVDA and came up blank.  It started out in a search box, but when I tabbed out, all I heard all the way down the page was that lovely word, "Blank."  In desperation, I quit NVDA and brought up another screen reader which read the site links and shoed me the page wasn't blank.  I quit the other screen reader and started up NVDA; the links were no longer readable.

I've been given to understand that Firefox with NVDA works well on the site which is an okay work around, but for those who wouldn't know to try that solution, could you take a look at the site and help figure out how to make it and others like it work?

Thanks very much!

Lee

**Comment by jcsteh** [comment]
Thanks for the report.

Technical: Wow. This site is broken. It looks like the author accidentally used the wrong quote symbol in the code, so the lang attribute on the html tag is the following:

```
en”>
<head>
	<meta http-equiv=
```

instead of just the intended `en`. Still, we need to be able to cope with such brokenness.

What I don't quite understand yet is why our XML escaping for attribute values isn't handling this.

**Comment by nvaccessAuto** [comment]
Incubated in 046306fa87b296ad059836506d1694eaeaa62868.

**Comment by jcsteh** [comment]
> What I don't quite understand yet is why our XML escaping for attribute values isn't handling this.

That'd be because the language attribute is handled separately for MSHTML (and wasn't previously being escaped).

**Comment by n2fgc** [comment]
Hi there,
 
Well, since I don't know squat about coding, I'll just put my head back
under the pillow. :)  Seriously, I wish you guys luck in sorting this as I
have seen other sites with similar broken traits.
 
I forgot to specify all my lovely details like the fact I'm running Win-7
64-byt with all the latest updates except those that want to force one to go
to Win-10, and my Internet Explorer version is Version 11.0.9600.18097.  My
machine is a DAW-type machine, Standard Computers, ACPI with 16 Gigs ram and
Intel video, I believe.  I don't know if any of that is important, but
figured I'd give you as much as I could just in case.
 
Again, thanks for the help!
 
Peace,
Lee
 

Do not walk behind me,    | Lee Storm 
I may not care to lead;   | N2FGC 
Do not walk before me,    | n2fgc@arrl.net (or) 
I may not care to follow; | mlee.n2fgc@gmail.com 
Walk beside me,           | Twitter: @N2FGC 
And be my friend.         | Skype: Lady_Chocolee 

 

  _____

**Comment by n2fgc** [comment]
What I don't understand is why Firefox reads this page and Explorer doesn't.
Please, can you explain to the inept? :)
 
 

Do not walk behind me,    | Lee Storm 
I may not care to lead;   | N2FGC 
Do not walk before me,    | n2fgc@arrl.net (or) 
I may not care to follow; | mlee.n2fgc@gmail.com 
Walk beside me,           | Twitter: @N2FGC 
And be my friend.         | Skype: Lady_Chocolee 

 

  _____

**Comment by jcsteh** [comment]
Suffice to say that this is fixed in "next" snapshots and the fix will 
be included in NVDA 2016.1.

**Comment by n2fgc** [comment]
Thanks! I hope I didn't create too much of a kerfuffle. :) I appreciate you
addressing this so promptly!
 
Appreciatively,
Lee
 

Do not walk behind me,    | Lee Storm 
I may not care to lead;   | N2FGC 
Do not walk before me,    | n2fgc@arrl.net (or) 
I may not care to follow; | mlee.n2fgc@gmail.com 
Walk beside me,           | Twitter: @N2FGC 
And be my friend.         | Skype: Lady_Chocolee 

 

  _____
