### ISSUE TITLE
remove report comments setting from Input gestures dialog

### ISSUE THREAD

**Issue by JamaicanUser** [nvaccess/nvda#5572]
The Input gestures dialog, under Document formatting, has a setting to toggle the reporting of comments. I think this should be removed, as this is not a Document formatting setting.

**Comment by jcsteh** [comment]
@michaelDCurran: Apparently, you added the reportComments config option in 48100a09. That commit notes you didn't add a GUI option yet. Was this an oversight or did you see no point in adding this for users; i.e. it was only for advanced config tweakers? If the latter, we should definitely remove the gesture (which was added as part of #4898).

**Comment by JamaicanUser** [comment]
Already taken care of via a new setting a few months back.
