### ISSUE TITLE
extend the limit of the report clipboard command

### ISSUE THREAD

**Issue by JamaicanUser** [nvaccess/nvda#5573]
The current limit of the NVDA+C command is a bit too small to me. It needs to be extended (lengthened) or something. This, or NVDA could announce the last characters of the selection. The first? I don't know, but the current limit is too restrictive to me.

**Comment by Laughingthunder** [comment]
I agree. It would be much appreciated if this setting were configurable.

**Comment by derekriemer** [comment]
Can you give a non-personal (objective) reason why this is too short? I 
agree that reading the end may be nice, but I would love to see an 
objective reason for the length.

**Comment by jcsteh** [comment]
That command is only really meant for quick inspection. If you need to 
do serious work with the clipboard, you really should paste it into an 
application.

The problem with extending this or making it configurable is that 
sending large strings to synthesisers can cause performance problems or 
even instability. That's why we limited it in the first place. Even 
making something configurable is not acceptable if users can set the 
option in such a way that it causes performance problems or instability.

**Comment by bhavyashah** [comment]
While I agree that this isn't the most screen reader relevant feature request, I do agree. The limit could be extended from 500 to 1000 characters, which sounds quite reasonable and non-regressive to me, because 500 characters does prove too short sometimes. This may be a little too much to ask, but if NVDA could report the number of characters for larger portions of text (longer than 1000 characters) followed by 'from {first couple sentences of the clipboard contents} to {last couple sentences}', so that the NVDA user is aware of the start and end of the copied text. Even if only the former, i.e. extension of character limits is accepted and implemented, it would still be an appreciable improvement. @JamaicanUser @Laughingthunder @leonardder

**Comment by derekriemer** [comment]
How would you feel if we just simply made this a config value berried in advanced config?

**Comment by bhavyashah** [comment]
I reckon I'd be fine with it, givven that the messy hack to work with
advanced config was relatively risk-free and at least somewhat
user-friendly.

On 7/31/17, Derek Riemer <notifications@github.com> wrote:
> How would you feel if we just simply made this a config value berried in
> advanced config?
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/5573#issuecomment-319029471


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by Laughingthunder** [comment]
I agree. I've had issues with that ridiculous limit for years. My thought is that if I ask NVDA to read the contents of the clipboard, it should do so without imposing needless limits on the amount of text. For instance, if NVDA starts reading something, and I no longer wanted to do so, I can just press the control key. No big deal! I just don't see the reason for the limit in the first place, Except for computers with low-end processors. And, even in that case, I feel that the limit is just way too low.

**Comment by derekriemer** [comment]
On the contrary, what if "a" was on the clipboard 3,000,000 times. This is well known to lock many many synths and make NVDA useless.

**Comment by bhavyashah** [comment]
While I disagree that limits are needless, I do think a 500 to 1000
character extension or the ability to customize the same would be
welcomed by all.

On 8/1/17, Derek Riemer <notifications@github.com> wrote:
> On the contrary, what if "a" was on the clipboard 3,000,000 times. This is
> well known to lock many many synths and make NVDA useless.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/5573#issuecomment-319239839


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by Laughingthunder** [comment]
You have a good point about the repeated letters on the clipboard. That could definitely messed things up. So, I agree. There should be some sort of limit, but it should definitely be configurable. And, if possible it should just be expose in one of the preferences dialogs.

**Comment by derekriemer** [comment]
his has been marked good for new dev, and help wanted. I'd love to see a pr for it. 

Hint: you'll need to modify the global command.

**Comment by DrSooom** [comment]
Well, I would prefer a combobox in the General NVDA settings window with the following firm values: 100, 200, 300 to 900 and 1000 followed by 1500 and 2000 to 9500 and 10000 characters. Pressing NVDA+C twice should open a window with a text field inside it similar to bug #4908.

The current limit in NVDA 2018.1 is set to 1023 characters.

**Comment by jage9** [comment]
Has there been any update on this? I would support NVDA+C twice to put the clipboard in a virtual buffer. I think a combobox of choices is overkill but could see a case for an advanced setting.
Also, the current text for a large amount of text is very verbose.

**Comment by Adriani90** [comment]
In my view there are no real use cases for a really long string in the clipboard to be reported to the end.
1. Someone who has a lot of content in the clipboard does actually not want to listen to the whole content before pasting, but maybe wants just to explore the content very fast. This could be acomplished via a new browseable window (i.e. press nvda+c twice)
2. If you listen to the content in the clipboard to the end and then you paste it, sometimes the pasted text is not the same (i.e. when the edit field does not allow more than x characters)
3. In my view it does not make sense to listen to a very long content when sellecting it and copying to clipboard, then listening to it when it is in the clipboard, then paste it and then listen to it again to see what has really been pasted in the edit field. This is just totally inefficient. So actually while I sellect text, I already know what will be in the clipboard.

So imo the only thing that could be implemented to improve this, would be a browseable window for the content in the clipboard.

**Comment by cary-rowen** [comment]
Hi,

I even wonder if we can add a mode for accessing the Windows clipboard when NVDA +7/1 switches the review mode, named Clipboard Review.
The use of commands for detailed access to the contents of the clipboard is very popular among Chinese users.

Thanks.

**Comment by DrSooom** [comment]
@sasgrw: To read a paragraph in a web browser in Browse Mode completely, please press and hold CTRL when pressing ArrowUp or ArrowDown.

**Comment by sasgrw** [comment]
Thanks, @DrSooom.  I had checked the user guide (https://www.nvaccess.org/files/nvda/documentation/userGuide.html) and the quick reference (https://www.nvaccess.org/files/nvdaTracAttachments/455/keycommands%20with%20laptop%20keyboard%20layout.html) and neither listed ctrl+downarrow as a "read paragraph" key.

**Comment by cary-rowen** [comment]
@sasgrw 
Hello, this shortcut key is provided by Windows, and it is not different from Alt + Tab, Alt + F4 and more.
Perhaps we can suggest that NVAccess add an appendix to the NVDA User Guide to include these commonly used shortcut keys in Windows.
@michaelDCurran 
@seanbudd

**Comment by Adriani90** [comment]
It seems as per https://github.com/nvaccess/nvda/issues/5573#issuecomment-907375411 this issue is perceived as solved. If you have further requeusts towards improving things in nvda+c command, please open a new feature request.
