### ISSUE TITLE
Update to liblouis 2.6.5

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#5574]
Table improvements and minor bug fixes, plus two new tables: Norwegian 8 dot, Mongolian.

**Comment by nvaccessAuto** [comment]
Incubated in 9908ea94e1bc5d3f52c68ec3df200e7afd26b7ba.

**Comment by jcsteh** [comment]
I haven't added Norwegian 8 dot because we already have a Norwegian 8 dot computer braille table and I've no idea whether we're supposed to remove the old table, etc. Certainly, having "Norweigna 8 dot computer braille" and "Norwegian 8 dot" is confusing. Anyway, I've [asked for clarification](https://www.freelists.org/post/liblouis-liblouisxml/Norwegian-8-dot-tables).
