### ISSUE TITLE
Support audio ducking for SAPI5 synthersizers

### ISSUE THREAD

**Issue by michaelDCurran** [nvaccess/nvda#5575]
The audio ducking functionality implemented in #3830 does not work with SAPI5 synthesizers as they do not use nvwave. Eventually we will want to rewrite the SAPI5 driver to use nvwave, but for now we should at least use the audio ducking API specifically in the SAPI5 driver. Related issue #5536

**Comment by nvaccessAuto** [comment]
Incubated in 004ece42e0ed780713943f72c49f87d395e8be7c.

**Comment by michaelDCurran** [comment]
Blocked by #3830

**Comment by nvaccessAuto** [comment]
Incubated in 5505837b4171cc6606122d26c9ae27f7d23c0530.

**Comment by nvaccessAuto** [comment]
Incubated in 9fa91c2f07da195bc08992fd94d5b8bf6695be9a.

**Comment by nvaccessAuto** [comment]
Incubated in 4b7eeb73f26e9723da02450633ef97774f38ab29.

**Comment by nvaccessAuto** [comment]
Incubated in dfa326192beb408bda59732f5e08599a8b098a5d.

**Comment by jcsteh** [comment]
Fixed by 796f3f17.
