### ISSUE TITLE
Firefox/YouTube HTML5 Player: Time Remaining not automatically Updated

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5582]
When playing a video from within YouTube's new (ish) HTML5 player, the duration remaining for the current video is not automatically updated. To get a proper idea of the remaining time, it's either necessary to activate Focus Mode and Tab to the slider at which point the correct value is output by NVDA; alternatively, if Object Navigation is used, it's necessary to open a new tab and switch back to the tab containing the video before the information is updated.

**Comment by Laughingthunder** [comment]
Try pressing NVDA+F5 to refresh the buffer. Also, make sure that the option to "report dynamic content changes" is turned on in the "object presentation" dialogue.

**Comment by elliott94** [comment]
Thank you for the suggestions; however, in this situation I'm reading the information from within Focus rather than Browse Mode. Even if I did refresh NVDA's buffer, it'd take time once again finding the relevant slider - a lot more time than simply reading the time remaining.

**Comment by bhavyashah** [comment]
Hi,
Eliot,
I did notice the same issue too. Previously, at some point of time,
maybe when the YouTube HTML Player was different, or maybe in NVDA
version 2015.3, this used to work correctly, time was automatically
and continuously announced when focus was on the slider (even in
browse mode)...
Thanks.

On 12/5/15, elliott94 <notifications@github.com> wrote:
> Thank you for the suggestions; however, in this situation I'm reading the
> information from within Focus rather than Browse Mode. Even if I did refresh
> NVDA's buffer, it'd take time once again finding the relevant slider - a lot
> more time than simply reading the time remaining.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/5582#issuecomment-162192623


-- 
Warm Regards
Bhavya Shah
Using NVDA (Non Visual Desktop Access) free and open source screen
reader for Microsoft Windows
To download a copy of the free screen reader NVDA, please visit
http://www.nvaccess.org/
Using Google Talkback on Motorolla G second generation Lollipop 5.0.2
Reach me through the following means:
Mobile: +91 7506221750
E-mail id: bhavya.shah125@gmail.com
Skype id : bhavya.09

**Comment by elliott94** [comment]
Hi Bhavyashah,

This functionality still works correctly if you enter Focus Mode and manually Tab to the slider; however, the constant notification is somewhat annoying if you're trying to watch a video which is when Object Navigation is used.

**Comment by jcsteh** [comment]
You note that the value is not updated. How are you reading the value in the first place? That is, are you using object navigation or focus?

It seems Youtube doesn't actually update the value of this slider when it's not focused. This is a bug Google will need to fix. I'll report it to our contacts at Google. It'd still be useful if you could answer the above questions, though. Perhaps provide the steps of the usual scenario you use when you're watching a Youtube video and you want to check the progress.

Thanks.

**Comment by elliott94** [comment]
Thank you for reporting this. Generally, whenever I'm watching a YouTube video I'll be in Focus Mode (so that I can change the volume of playback, etc). In that case, I'll use Object Navigation to move focus to the slider in the window; whilst it's possible to Tab to this element, since the value is being updated in realtime NVDA constantly outputs the new value.

**Comment by Adriani90** [comment]
@elliott94 are you still having this issue?
Is it actually possible to implement a key stroke which is directly linked to time sliders in a html5 media object? This might solve the problem. You just press a key stroke and you hear the current value of the slider. The only thing is probably, if the webpage is updated and the design changes the link to the slider might be broken. So it must be implemented by the web developer him or herself in the best case.

**Comment by jcsteh** [comment]
As noted in https://github.com/nvaccess/nvda/issues/5582#issuecomment-162395235, I reported this to Google, but it seems there hasn't been any action. Given the lack of action on this and the time it's been open, I don't think it's worth tracking here, but you could try contacting Google Accessibility yourself to see if that has any impact. Closing.
