### ISSUE TITLE
What's New: Notify about move to GitHub

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5586]
I noticed that as it currently stands, there's no section in the What's New document that notifies developers about the move to GitHub. I realise that in theory devs should be aware through updates that have been posted to various mailing lists, but would it be beneficial to add it to the documentation also?

**Comment by jcsteh** [comment]
I don't think so, for several reasons:

1. The What's New primarily relates to changes to NVDA itself as a product, not to changes in development process, project resources, etc.
2. New developers should be reading the readme, which includes the relevant links. Existing developers that somehow missed this news will probably try community.nvda-project.org, which redirects to GitHub, where they will see the readme.
3. This change occurred for NVDA 2015.4, not NVDA 2016.1. We can retrospectively add the change, but most people aren't going to read old version notes to see if anything changed.
