### ISSUE TITLE
Windows 10: NVDA 2015.4 freezing randomly

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#5588]
This has been reported on spanish mailing list, specifically for NVDA 2015.4. Maybe a regression?
When NVDA freezes, the computer needs to be restarted to use NVDA again, and once NVDA didn't work after restarting the PC.
We don't have log files or crash dumps for now.
Thanks.

Thanks.

**Comment by jcsteh** [comment]
Thanks for reporting this, though there's unfortunately nothing we can 
do without logs/crash dumps. Certainly, we've never seen this ourselves 
on Windows 10.

**Comment by nvdaes** [comment]
OK, we try to attach these files.
I don't know if this can be related to the inclussion of NVDA in the
EaseOfAccess Center, as someone has reported on the dev list a similar
bug usin Windows 8.1.
Thanks.

**Comment by jcsteh** [comment]
I can't think of any reason Ease of Access should cause this, but it's 
impossible to rule it out completely.

**Comment by ehollig** [comment]
Is this still the case with NVDA 2017.2?

**Comment by bhavyashah** [comment]
This is just a friendly reminder for @nvdaes to kindly respond to @ehollig's https://github.com/nvaccess/nvda/issues/5588#issuecomment-314907615. In case you are away or busy, please feel free to respond only at your convenience.

**Comment by nvdaes** [comment]
@bhavyashah, @ehollig: I don't see this with NVDA 2017.2 or 3. I suggest to close the issue for now.

**Comment by ehollig** [comment]
Closing, as requested in https://github.com/nvaccess/nvda/issues/5588#issuecomment-325315954. If the problem still persists, we can reopen this issue or please create a new issue with clear steps to reproduce the problem.
