### ISSUE TITLE
NULL COM pointer access error in Libera System 7 web application

### ISSUE THREAD

**Issue by csamaha1** [nvaccess/nvda#5590]
Note that it will probably help to have access to the Libera System 7 application (www.libera.com) in order to reproduce this issue.  However, I have included the following error which I can reproduce 100% of the time in Internet Explorer 11.  This error is generated in the NVDA log viewer.
1. Log into the System 7 application.
2. There is an edit field at the top of the data tree which can be used to filter user data such as name, address, date of birth etc.  However, if you press the down arrow, you are taken out of the filter edit field and into the actual data tree which contains your filtered results.  Press the down arrow to move out of the filter edit field and into the data tree.

Current Results: When pressing the down arrow, NVDA seems to think that I still want cursor movement functionality when in reality the focus has moved to the data tree.  In Internet Explorer 11, this simply generates an error in the NVDA log and I am able to happily go about my business.  However in Internet Explorer 9 (which is what we are required to use at work) this completely crashes the browser.  I can try to provide and / or attach the web page which is causing this, but we do deal with highly confidential personal data for clients, so I need to think about how I can do this without compromising anyone's personal data.  I am running the latest master snapshot.  The output of the log is as follows:

ERROR - scriptHandler.executeScript (16:17:16):
error executing script: <bound method Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible.script_caret_moveByLine of <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible object at 0x050CA570>> with gesture u'down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 186, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 673, in speakTextInfo
  File "NVDAObjects\UIA__init__.pyc", line 242, in getTextWithFields
ValueError: NULL COM pointer access

**Comment by leonardder** [comment]
@csamaha1: Can you still reproduce this?

**Comment by derekriemer** [comment]
This needs the crash label. If the reporter is still around, this is likely to cause issues with the reporters ability to do their job effectively, so we should probably think about putting a high priority on it.

**Comment by derekriemer** [comment]
did this intentionally get 2017webxia, or did I accidentally do that?

**Comment by feerrenrut** [comment]
Giving this a priority 2, this area of the code should at least be investigated to see if there is an obvious error that we can fix.

**Comment by Adriani90** [comment]
@csamaha1 are you still having this issue?

**Comment by Adriani90** [comment]
No updates on this since years, the author seems not available anymore. I am closing as abandoned. Please comment on it if you have updates and we can reopen. Thanks.
