### ISSUE TITLE
Allow NVDA compilation using MSVC 2015

### ISSUE THREAD

**Issue by michaelDCurran** [nvaccess/nvda#5592]
Currently NVDA can only be compiled with Microsoft Visual c++ 2012 update 3 or higher, or Microsoft Visual C++ 2013. We should support compiling with Microsoft Visual C++ 2015. This requires Scons 2.4.1 and multiple fixes to our source code as VC 2015 is much more pickier about casting truncation on 64 bit (specifically in regards to HWND and HANDLE).

**Comment by nvaccessAuto** [comment]
Incubated in 5d76183459817ac335eef34af7af766ceb087ef4.

**Comment by jcsteh** [comment]
The current deployment plan for this is:

- [ ] In early January, install VS 2015 on our build server.
- [ ] Once VS 2015 is installed, force the VS version to 2015 so NVDA will refuse to build at all with earlier versions. This should be merged into next.
- NVDA 2016.1 (and thus master until rc) will still be VS 2012.
- [ ] Merge to master at the start of the 2016.2 release cycle (after 2016.1rc1).

**Comment by nvaccessAuto** [comment]
Incubated in a74f6c233ca01f003cc70994dc94a608da2893c9.

**Comment by nvaccessAuto** [comment]
Incubated in d287eef5e8a2d706d09dac94a225f1200c26654d.
