### ISSUE TITLE
Microsoft Office: Consistency of Use Screen Layout setting whilst in Browse Mode

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5596]
If the Use Screen Layout Setting is disabled from within the Browse Mode dialog, NVDA will place each link onto a separate line within that particular buffer; this can be useful for users who may not be used to NVDA's way of presenting information.

Currently, however, this particular setting does not change how content is presented within Office applications. Is there any particular reason for this? I assumed that since links act in a similar way between browsers and Office-based software the behaviour of this setting could be mirrored across both.

**Comment by jcsteh** [comment]
There are a few dimensions to this.

From a practical perspective, the question is whether it makes sense to present word processor documents in non-screen layout. While I certainly follow this on the web, word processor documents are usually simpler and navigation is focused more on editing. Also, when a user cursors around a Word document normally, links don't appear on separate lines, so this would be the more familiar experience and it might seem odd for this to change in browse mode. On the flip side, browse mode is focused on reading and it could be argued that non-screen layout is easier for some to work with when reading.

Technically speaking, the browse mode implementation for Word is completely different to that of the web; we don't use virtual buffers for Word at all. It may be extremely difficult (if not impossible) to do non-screen layout in Word for this reason.

Finally, at the very least, we have a documentation problem here. Even if we decide that we don't want to or can't do non-screen layout for Word, we need to document that this isn't supported for Word.

@MichaelDCurran, any thoughts on the practical/technical questions?

**Comment by michaelDCurran** [comment]
It is not technically impossible. We could just change our inprocess 
moveByLine code to move, look at the range covered, if there are any 
links or controls or shapes in that range and the first one of them was 
not right on the edge of the range, then move to the offset of the first 
one.

The tricky bit will be choosing what breaks lines and what doesn't.
Also it is worth noting that a change like this is still pretty 
dangerous just for breaking this... MS Word already has many problems 
with looping back on itself when moving.

Failing this, we could just document it doesn't work, and also perhaps 
add a suportsScreenLayout property to BrowseModeDocuments and if false 
the toggleScreenLayout script should provide some kind of error message.


On 8/12/2015 9:00 AM, James Teh wrote:
>
> There are a few dimensions to this.
>
> From a practical perspective, the question is whether it makes sense 
> to present word processor documents in non-screen layout. While I 
> certainly follow this on the web, word processor documents are usually 
> simpler and navigation is focused more on editing. Also, when a user 
> cursors around a Word document normally, links don't appear on 
> separate lines, so this would be the more familiar experience and it 
> might seem odd for this to change in browse mode. On the flip side, 
> browse mode is focused on reading and it could be argued that 
> non-screen layout is easier for some to work with when reading.
>
> Technically speaking, the browse mode implementation for Word is 
> completely different to that of the web; we don't use virtual buffers 
> for Word at all. It may be extremely difficult (if not impossible) to 
> do non-screen layout in Word for this reason.
>
> Finally, at the very least, we have a documentation problem here. Even 
> if we decide that we don't want to or can't do non-screen layout for 
> Word, we need to document that this isn't supported for Word.
>
> @MichaelDCurran <https://github.com/MichaelDCurran>, any thoughts on 
> the practical/technical questions?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5596#issuecomment-162699023>.
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by fernando-jose-silva** [comment]
Good night dear.
For me as a mere user, what else bothers is when reading e-mails in Outlook, mostly emails from facebook and linkdyn, is over-reading empty lines, occasionally there are 10 empty  lines between content.

**Comment by feerrenrut** [comment]
Closing this issue as a duplicate. Please see #7297 for an explanation of the intended approach regarding this.
