### ISSUE TITLE
Microsoft Lync 2010: Unable to view full list of attendees in a Meeting

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5597]
When in a meeting with multiple recipients, each individual user can be seen in a list. However, it's not currently possible to view all users that have joined; the list view appears to use a non-standard format, whereby using the down cursor does not allow additional users to be shown, and wraps the user back to the top after several entries.

**Comment by jcsteh** [comment]
How about left/right arrows or object navigation? Trying to override 
up/down arrows to fix this would be horribly error prone I think.

**Comment by elliott94** [comment]
Apologies; I should have mentioned this in my initial description. Using either of those methods doesn't allow you to view the information - even Object Navigation only presents the user with the same number of users that can be seen if using the cursors.

**Comment by jcsteh** [comment]
That's rather worrying. It suggests we possibly have no chance of fixing 
this.

**Comment by elliott94** [comment]
Pressing Home/End to move in the list does work; I'm wondering whether it's just a case of the cursor not following arrow presses as it should.

I realise that I've opened several individual issues concerning Lync; whilst in theory they should hopefully not be that difficult to fix, I realise that since the software is primarily only used in corporate environments that you may not have had a chance to have a look at its structure. What would be the best way for me to get this information into the individual issues?

**Comment by jcsteh** [comment]
If it were just related to the cursor, object navigation should work, 
since it's not bound by the cursor.

**Comment by Adriani90** [comment]
@elliott94 are you still able to reproduce this issue in last Version of Lync?

**Comment by elliott94** [comment]
Closing for now; I no longer have access to a copy of Lync 2010 that I can test with. Furthermore, Lync has now been replaced with Skype for Business; I will identify accessibility issues with SFB as I notice them.
