### ISSUE TITLE
Mouse tracking - Multiple issues when reading links within text paragraphs

### ISSUE THREAD

**Issue by Laughingthunder** [nvaccess/nvda#5602]
Please see the attached HTML document for examples and instructions for reproducing.
The HTML document should be accessible to you at the following link. I'm new to Github, so I'm not sure if this will work.
https://gist.github.com/Laughingthunder/a2a9707c8635b030661a

**Comment by jcsteh** [comment]
I think several of these issues have already been reported, but I need to comb through it more closely to track these down. At least one of them is due to a Firefox bug that I need to report.

**Comment by ehollig** [comment]
### Issues Described ###
#### Links Imbeded In a Paragraph ####
This is covered by #2160
#### Links Within List Items ####
Seems to be a similar issue to the first. NVDA reads the link text and the text in the list item separate.
#### Links Spanning Multiple Lines ####
This is covered by #374, at least with speech.

**Comment by Adriani90** [comment]
#7083

**Comment by Adriani90** [comment]
#8076 is related.

**Comment by Adriani90** [comment]
Closing this issue in favor of the already referenced issues covering the problems here.
