### ISSUE TITLE
Suggestion:  to list the spelling error and grammatical errors in MS Word.

### ISSUE THREAD

**Issue by sumandogra** [nvaccess/nvda#5606]
MSWord 2013
Suggestion:  a dialog that lists the spelling errors and grammatical errors separately will be very helpful.  this feature will be helpful for those who work with long documents.  
the spell check dialog of MSWord is a time consuming process with screen reader.  if a dialog that lists the spelling error and grammatical errors, one can reach out to the errors quickly and make the corrections as required in context to the rest of the text in the document.  
even in a document with 5 pae such feature will help increae the speed of making corrections in the documents specially with the latest versions that have new kind of spell check dilogs.

**Comment by aviraljn9** [comment]
As word itself does not detect many grammatical errors, it would be better to not include grammatical errors in the fix

**Comment by leonardder** [comment]
This is fixed for spelling errors. For grammatical errors, #7319 will fix this.

**Comment by jcsteh** [comment]
Closing in favour of #7319.

**Comment by jcsteh** [comment]
For reference, quick nav to/listing of spelling errors is issue #6942, PR #7258.
