### ISSUE TITLE
Smart Beetle Ultra 14 and auto detecting issues

### ISSUE THREAD

**Issue by WCARDude** [nvaccess/nvda#5607]
When you connect the Smart Beetle Ultra 14 via bluetooth serial to a computer, and attempt to use it with NVDA, it will not be able to detect the COM port that it is using. Thus, leaving you with your only option to use USB.

**Comment by jcsteh** [comment]
Are you able to tell me the exact Bluetooth name of your display? Spelling, capitals, spaces, etc. are very important.

**Comment by WCARDude** [comment]
Certainly. It is the Smart Beetle 14 cell by HIMS. To get it working
with NVDA, I need to select HIMS Braille Sense/Braille EDGE series in
the Braille dialogue.

**Comment by jcsteh** [comment]
That's not quite what I meant. I need the Bluetooth device name of your 
display. I believe you can get this from one of the menus on the device. 
It should also be the name that appears when you pair your device with 
your computer. See the display's user manual for more information.

**Comment by WCARDude** [comment]
Ahh, apologies. It is SmartBeetle(b)00173

**Comment by jcsteh** [comment]
It'd be great if you can test [this try build](http://www.nvaccess.org/files/nvda/try/i5607/nvda_snapshot_try-i5607-11691,88efa62.exe) and let me know whether this works. You don't need to install it; you can just run it temporarily to test this. Thanks.

**Comment by WCARDude** [comment]
This is working just fine. In fact, I am using it to type this message.

**Comment by nvaccessAuto** [comment]
Incubated in c4e16338e11986cdffdfb8c03d2da4dfe9e8748d.
