### ISSUE TITLE
Support for Baum displays using USB HID

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#5609]
Newer models of the APH Refreshabraille have optional HID support. The Baum VarioUltra and Pronto! have USB HID and no USB serial.

**Comment by nvaccessAuto** [comment]
Incubated in add0a23691089b59e5552da79a6d5c9eeec85e90.

**Comment by nvaccessAuto** [comment]
Incubated in e07263757ebb2ece344dd1585989d023942a2e75.

**Comment by nvaccessAuto** [comment]
Incubated in d55cba5d1f13a977843d7f5ba2d7723771fb17d1.

**Comment by nvaccessAuto** [comment]
Incubated in bed132c8c4d81a9b290462e807962cf2c49493c6.

**Comment by nvaccessAuto** [comment]
Incubated in b39904ea61753e46f4a492b7d2e1941fb10cd5e8.
