### ISSUE TITLE
Inconsistency with announcement of Capitalisation when letters separated by Characters

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5615]
I realise that this title is somewhat long!

STR:

1. Open Firefox, and navigate to the Address Bar. I should point out that this issue can also be observed within other applications; I'm simply using the browser for this example.

2. In the text field, type "A/B" and hit Home to jump to the start of the line.

3. Using Ctrl + right, navigate through the just-entered text. You should notice that NVDA references the fact that the "B" character is capitalised, whereas this is not reported at all for "A".

It may also be relevant to note that this particular behaviour differs by application; for example, when reviewing a message within Outlook 2010 both letters are reported as having capitalised text (if this has been applied).

**Comment by jcsteh** [comment]
When moving by word, NVDA reads by character if the word only contains one character, which is why you get indication of capitals. In this case, the word is actually "A/" (note the slash), not just "A". You're probably not hearing the slash because of your symbol level.

**Comment by elliott94** [comment]
This makes sense; that said, why would that cause a difference in behaviour by application as mentioned above? In theory, surely the announcement should be the same?

**Comment by jcsteh** [comment]
I don't have Outlook set up here right now, but I assume it's the same as Word. In Word, moving by word treats the slash as a separate word, so the slash isn't included as part of the first word. So, the key point is that the idea of "word" differs between applications.
