### ISSUE TITLE
ref bug #2471 Visual Studio 2010 Open Code Editor File Name Not Reported  with CTRL+TAB

### ISSUE THREAD

**Issue by sumandogra** [nvaccess/nvda#5619]
Changing between open code editor files with Ctrl + TAB (for example), NVDA doesn't speak the currently active file's name or title of the editor window. NVDA does speak the line the cursor is

**Comment by mohammad-suliman** [comment]
hello @sumandogra 
I am currently working on an app module for VS, if it still relevant, cant you please help us and test whether the enhancements made for VS are working also for VS 2010, especially the ctrl + tab issue reported here? the link to the source code of the module is:
https://github.com/mohammad-suliman/visualStudioAddon
list of enhancements is also in the link.
the file for the app module is attached for your convenience:
[devenv.txt](https://github.com/nvaccess/nvda/files/307212/devenv.txt)
you need to change the extension to .py.

if you are willing to test only the issue reported here, that is fine also.
thanks in advance.

**Comment by Adriani90** [comment]
We didn't hear anything from the initial Author since more than three years. I am closing this one. We can reopen it if someone reports it again.
