### ISSUE TITLE
NVDA stops speaking of typed characters from time to time

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#562]
**Reported by aleksey_s on 2010-02-16 05:40**
I noticed, that NVDA sometimes stops speaking of typed characters. It happens every time after resuming from standby mode and sometimes without any reason. Restarting of NVDA helps resolve this one. I think this was introduced in Sunday commits.

**Comment by leonardder** [comment]
This issue hasn't gotten comments during the last seven years, and honestly I've never seen it. May be it should be closed with the note that it can be re-opened at any time?

**Comment by jcsteh** [comment]
Closing as won't fix. Please reopen if the problem persists.
