### ISSUE TITLE
Excel 2010: Inconsistent Behaviour in Browse Mode

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5621]
As of NVDA 2015.4, it's now possible to view the contents of certain cell types using Browse Mode; this comes in handy where, for example, a sheet contains several merged cells and the user wishes to view the data contained within them.

That said, it appears that at this time it is only possible to activate Browse Mode when on such a cell. This currently means that if a user is reading a sheet within a workbook and they know for a fact that a merged cell is present, they first need to find a cell reference otherwise the focus in Focus Mode will skip past this range of cells. Therefore, would it be possible for Focus Mode to be activated no matter which cell currently has focus, so that there is less chance of these types of cells being missed?

**Comment by jcsteh** [comment]
Sorry, but I really don't follow this at all.

When you merge cells, the entire block of merged cells only has one 
value. Sighted users can't move to individual cells within the merged 
block either. Excel enforces this; if you merge cells, you are warned 
that only the upper-left value will be kept.

That said, I also can't see any inconsistency with browse mode here. If 
I'm in focus mode, there's only one stop for a merged block. The same is 
true in browse mode. I can enter browse mode regardless of whether I'm 
on a merged cell or a normal cell.

Please provide exact steps to reproduce and perhaps a sample spreadsheet 
illustrating the issue. Thanks.

**Comment by elliott94** [comment]
Apologies. :)

From testing, I've found that if in a worksheet that contains a group of protected cells, as you mentioned navigating past this group with a single press of a cursor key will jump past them - this is to be expected. However, in Browse Mode this doesn't appear to be the case; for example, if cells A2-A6 are merged, entering Browse Mode on A2 allows you to navigate to each cell individually. What I've found, however, is that it's only possible to activate Browse Mode on one of these cells; in this example, attempting to activate it on A1 results in nothing happening.

**Comment by jcsteh** [comment]
> in Browse Mode this doesn't appear to be the case; for example, if cells A2-A6 are merged, entering Browse Mode on A2 allows you to navigate to each cell individually.

I can't reproduce this. In browse mode, I see one stop on a2 through a6, just as I do in focus mode. I think you're going to need to provide exact steps to create a problematic sheet or perhaps attach one.

> What I've found, however, is that it's only possible to activate Browse Mode on one of these cells; in this example, attempting to activate it on A1 results in nothing happening.

Again, I can't reproduce this. If you're correct, that would mean that if you open a completely blank sheet with no merged cells, you can't enter browse mode at all. Is this correct?

Do you have any locked cells in your sheet? This may well change things, but you didn't mention this in your original report.

**Comment by elliott94** [comment]
Ok, my apologies. I think it's going to make more sense to split these issues into two; see #5637 and #5638 for proper details. Sorry for the confusion.
