### ISSUE TITLE
Excel 2010: Incorrect Number of Items announced when viewing previously entered Data

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5622]
STR:
1. Create a new workbook, and in cells A1-A9 enter any data.
2. When data has been entered into the above range, whilst focused on the same column press Alt + the down cursor. This will present a drop-down menu containing data that has previously been entered into the focused column.

At this point, you should notice that NVDA only reports the existence of a total of 8 items; the remaining entry is ignored. NVDA announces these if the user explicitly focuses them by navigating past the 8 items on screen, but it is currently possible for a user to assume that only 8 possible options are shown unless they navigate to further data entries. It may be useful to note that visually, only a total of 8 items are displayed on-screen at one time.

**Comment by jcsteh** [comment]
We can't get an accurate count here; it's entirely based on what's on screen (and there's no other way for us to access this information). The only thing we can and should do is make this position info only reported if "Guess object position information when unavailable" is enabled. This way, only users who have made this choice will receive this potentially inaccurate information.

**Comment by ehollig** [comment]
@jcsteh, from https://github.com/nvaccess/nvda/issues/5622#issuecomment-166165191, it sounds like this is a cantfix?

**Comment by jcsteh** [comment]
We can't fix the count, but see above regarding only reporting it if guessing is enabled.

**Comment by Adriani90** [comment]
Actually, if you focus the column and press ctrl+down arrow, the focus will jump to the last cell with content in that column if there are no empty cells in between. You can press ctrl+down arrow multiple times to get to the end of the data column even if there are empty cells in it. So you get the cell coordinates and you will know how many items there are. If you don't want to move the focus, press shift+end followed by shift+down arrow or ctrl+shift+down arrow and you will hear the selection range. This will also indirectly tell you how many items there are. The second and third possibility must be pressed multiple times as well if there are empty cells in the column.
The downside with this is that you must calculate a bit to get the exact number of items. Let's say the first cell with an item is b5 and the last one is b511. Then you have 506 items in the column (assuming there are no empty cells).

**Comment by Adriani90** [comment]
Another solution which is very exact and does not require any programatical changes, is the excel function count. Let's say you have items in the column from b5 to b511 and cell b400 until b500 are empty. Then you can type:
=count(b5:b511)
Excel will count all cells with content from b5 to b511 and will give you the number of items.

**Comment by Adriani90** [comment]
So there are several work arounds for this. I am closing it as can't fix.
