### ISSUE TITLE
issue with auto detecting the refreshabraille 18 second generation

### ISSUE THREAD

**Issue by z-benton** [nvaccess/nvda#5624]
I set the braille display to baum/humanware/aph displays and the auto detect doesn't work.  I have installed the USB drivers as instructed, and tried to assign the port manually with the ini file but that doesn't work and NVDA just throws error sounds at me.

**Comment by z-benton** [comment]
I also forgot to mention that the port it's trying to use is COM5,  if that helps any

**Comment by jcsteh** [comment]
What version of NVDA? Is your display's USB mode set to serial or HID?

**Comment by z-benton** [comment]
I'm running the latest snapshot and I have the display set to serial mode

**Comment by z-benton** [comment]
I also tried it with 2015.3 and 2015.4

**Comment by jcsteh** [comment]
The latest snapshot in which branch? Next or master? And i assume you mean it didn't work with any of these (2015.3, 2015.4 or the snapshot)?

How do you know it's trying to use COM5? You should generally have the port set to "automatic".

Please do the following with the latest next snapshot. Note that the extra logging I need is only present in next snapshots for now, so this won't work with other versions.

1. Start NVDA.
2. Open NVDA's General Settings dialog.
3. Set the Logging level to debug and press OK.
4. Press NVDA+control+z to open the NVDA Python Console.
5. Paste the following line and then press enter:

 ```
 import config; config.conf["debugLog"]["hwIo"] = True
 ```

6. Press NVDA+control+c to save configuration.
7. Restart NVDA.
8. Try to connect to your Refreshabraille.
9. When it fails, open the NVDA menu, select Tools and then Log Viewer.
10. In the Log menu, select Save as and save the log file with a .txt extension.
11. Attach the log file here.

**Comment by z-benton** [comment]
I got it working!  yay!
I would probably state this as a warning or a pointer for other users 
who intend on using the refreshabraille
do not install com0com also known as null modem emulator,  It's supposed 
to emulate serial ports when using dosbox  because it some how causes 
problems with NVDA's auto detect feeture as well as being able to select 
the port with this particular devices.

**Comment by jcsteh** [comment]
At a guess, I'd say it overrides the actual COM ports with something else which doesn't match the original information exposed. It'd possibly still be interesting if you could provide the debug log requested above, but it's highly likely there's nothing we can do.
