### ISSUE TITLE
browse mode navigation: previous and next spelling error

### ISSUE THREAD

**Issue by JamaicanUser** [nvaccess/nvda#5630]
I don't know if this would be intuitive, but I think a single letter key should be mapped to report the next and previous occurance of a spelling error. Maybe 'w' could be used. I understand that most persons would want to jump to spelling errors in focus mode for easy review, but I don't think this can be done.

**Comment by leonardder** [comment]
@JamaicanUser: Did you mean this for word? If so, this has been implemented in #6942, so this issue can be fixed. If you didn't mean this specifically for Word, I leave this open for the plans to allow browse mode in editable documents on the web.

**Comment by fisher729** [comment]
I opened this ticket with a different account. I initially thought about it in Word, but I'm trying to see how it could be implimented to recognise spelling errors in a Firefox edit field or something, without browse mode. That is just an example. Perhaps this cannot be done.

**Comment by Adriani90** [comment]
It might make sense to implement the speling errors at least in the elements list in browsers. @leonardder what do you think?

**Comment by Adriani90** [comment]
Actually I would close this in favor of #7320 which provides on a more general discussion on the quick navigation key for spelling errors in browse mode.
