### ISSUE TITLE
clarify 'beeps' in speech mode toggle setting: can it be removed?

### ISSUE THREAD

**Issue by JamaicanUser** [nvaccess/nvda#5631]
The command NVDA+s is very popular. It toggles between off, beeps and talk, Long and short of all this is that 'beeps' doesn't seem like a popular setting. It certainly gets in the way of trying to turn on back speech after turning it off. I'd like to know why it is included, and if it's possible to remove it.
On that note, I think the command description for this setting is quite long and needs revision. My thing is that I think it should be between speech on or speech off, since talk is rather not a good word to use.

**Comment by derekriemer** [comment]
I use this while audio editing. If you want to remove it there is a no 
speech beeps mode addon. I would vote for keeping it,

On 12/22/2015 4:02 PM, JamaicanUser wrote:
>
> The command NVDA+s is very popular It toggles between off, beeps and 
> talk, Long and short of all this is that 'beeps' doesn't seem like a 
> popular setting It certainly gets in the way of trying to turn on back 
> speech after turning it off I'd like to know why it is included, and 
> if it's possible to remove it
> On that note, I think the command description for this setting is 
> quite long and needs revision My thing is that I think it should be 
> between speech on or speech off, since talk is rather not a good word 
> to use
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5631>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.drupalgardens.com>
Non-proffessional website. <http://derekriemer.pythonanywhere.com/personal>
Awesome little hand built weather app that rocks! 
<http://derekriemer.pythonanywhere.com/weather>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by leonardder** [comment]
I actually would vote for removing it and to add the beep option to an add-on. I've actually never understood why we have this option.

**Comment by Laughingthunder** [comment]
I'm not sure what the link is, but there is already an add-on, which removes the beeps option from the speech mode toggle. I use it on all my copies of NVDA, and it works well.

**Comment by leonardder** [comment]
I know that there is an add-on. The strange thing here is that there 
must be an add-on to remove functionality. So that's why I vote for 
doing it the other way around.

**Comment by ehollig** [comment]
As beeps does not sound like a popular setting, @michaelDCurran, @jcsteh are there use cases for the beeps option toggle? Also, thoughts on the proposed idea of Speech On Vs. Speech Talk?

**Comment by bhavyashah** [comment]
@leonardder That was exactly what I was just thinking. It would be best if pressing NVDA+S just goggled between speech and silence by default. It is indeed ironic for an add-on to bre removing core functionality rather than adding it, and the add-on still being quite popular, clearly indicating that the functionality in question is pretty unpopular. Beeps should be packaged in an add-on and the core should simply offer the off and talk speech modes.

**Comment by jcsteh** [comment]
There are certainly use cases, some of them reasonably common for some users. Basically, if you ever want to know when something has happened (or when it has stopped happening) but you don't want to listen to every detail, beeps mode is useful. Examples include:

1. You're performing some activity which continually uses messages to provide progress. In that case, you can use beeps to know when there has been a progress update. If you stop hearing beeps, the task is probably complete (or has stalled).
2. You're doing some sort of continuous network ping. In that case, you might want to know when the ping starts working or when it stops working without having to hear information about every response.
3. You're using some sort of messaging system (whether chatting with real people or receiving messages from something automated). You might want to know when there is activity, but you don't want to be interrupted/distracted by the full message.

**Comment by mjanusauskas** [comment]
I use this feature, find it useful, and would prefer that it not be removed.

**Comment by derekriemer** [comment]
I use this feature a fair bit.

**Comment by Brian1Gaff** [comment]
Are you really suggesting that beep on progress bars  toggle in background 
be removed indeed all beep modes are what makes it easier to use nvda for 
me, as if I'm waiting for something to complete I can then get on with 
things and still keep an ear on it.
 I find all beep modes extremely useful all the time, it may annoy the heck 
out of my sighted friends but that is tough!
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Mohamed00** [comment]
I use beeps speech mode quite a lot in cases like compiling programs, and I believe it shouldn't be removed, however an option to hide it from speech mode in the core would be useful for people who don't need it.

**Comment by leonardder** [comment]
I take back my https://github.com/nvaccess/nvda/issues/5631#issuecomment-231162604 . Especially for audio editing, this option is really useful.

Having said that, I Concur  with the proposal to make the beeps setting optional by means of an option in the configuration.

**Comment by Brian1Gaff** [comment]
I don't get where this query came from. The ability to hear beeps in many 
different circumstances  is a very well used option. If you make it too 
complicated its going to be a pain.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Mary5958** [comment]
Bryan, I guess you're mixing it up with beeps for progress bars etc but that's not what they mean. It's the function of speech modes when you press NVDA+S: you get "speech mode off" that silences the speech, "speech mode beeps" that makes beeps but different ones than in the progress bars, and "speech mode talk" that's normally default with speech. There is actually an addon, NoBeepsSpeechMode, that excludes the beeps option, already available on the NVDA addons page.

**Comment by mdyer1** [comment]
Hi,

Is beep mode used by default when NVDA gets updated or during the install process?  Usually hear a beeping sound while it is doing the install/upgrade.  Is this what we are talking about here.

Thanks.

Matthew

**Comment by Mary5958** [comment]
Not really. I think the first comments of this issue do explain it.

**Comment by Brian1Gaff** [comment]
This issue seems to be very confused. Now I've read it it seems everyone 
thinks its something different. When something is not broken don't fix it I 
say.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment]
I've not seen that, but actually If I recall, a friend of mine with some 
sight uses the beeps mode just as a check that something has in fact 
happened.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment]
Maybe this beep tones will be transfered in a separate buffer after speech refactoring is implemented. cc: @jcsteh

**Comment by jcsteh** [comment]
> 
> 
> Maybe this beep tones will be transfered in a separate buffer after speech refactoring is implemented. cc: @jcsteh

I don't really know what you mean. There's nothing relevant to speech refactor here. The request here is for the beeps setting of speech mode (NVDA+s) to be made optional via configuration for users who don't need it. It is a user interface change; the core functionality doesn't need to be changed.

**Comment by Adriani90** [comment]
Ok. I just thought speech refactoring might also bring new dialogs which allow to choose for which events to use beep tones and speech and so on. But maybe I totally missunderstood it. Sorry for that.

**Comment by Adriani90** [comment]
Ok it seems the majority of users find this feature useful and pressing one time or two times nvda+s is not really and efficiency killer. Given the comments above and the use cases where this feature is helpful, I am closing this as won't fix. if you don't agree, please comment on it and we can reopen it if you have any arguments for removing this feature from nvda+s.
