### ISSUE TITLE
Format Information

### ISSUE THREAD

**Issue by Omrikos** [nvaccess/nvda#5642]
I wish there was an option to copy the format information to the clipboard, when pressing NVDA key+F, like, for example, NVDA+T .
I deal with HTML, and sometimes, I need to know the color code from an existing page...

**Comment by jcsteh** [comment]
With #4908 (which is now in the NVDA "next" branch for testing), you can press NVDA+f twice to read the formatting information in browse mode. You can then navigate and copy part or all of the text as you wish.

Note that we don't generally include raw information here; e.g. HTML colour codes. This information is meant to be understood by users. If you want raw information, you should use a specific web inspection tool.
