### ISSUE TITLE
Adobe Digital Edition: whole paragraphs shown on one line

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#5643]
Steps to reproduce
•	Open a document with multiple paragraphs, each paragraph should be long enough.
•	* Press down arrow, to navigate by line.
•	Expected Result: The long paragraphs will be split into multiple lines, and down arrow will take you to each individual next line.
•	Actual Result: All paragraphs, however long or short, will be displayed on one individual line only.
•	Test Environment: Adobe Digital Edition latest stable
•	NVDA version 2015.4
•	Windows 7 Ultimate 32 bit

**Comment by jcsteh** [comment]
Digital Editions doesn't have a concept of lines, at least not that a screen reader can access. A line and a paragraph are the same.

**Comment by bhavyashah** [comment]
Thanks for the clarification.
Just curious, would a browse mode implementation in Adobe Digital
Editions tackle this issue as well like the End key one?
Thanks.
P.S. Would it be possible for you to pass on these accessibility
issues to Adobe, since I see that Adobe is one of NV Access's major
sponsors and you may have contacts there. I shall too research whether
I as a common user can report this problem to the concerned...

-- 
Warm Regards
Bhavya Shah
Using NVDA (Non Visual Desktop Access) free and open source screen
reader for Microsoft Windows
To download a copy of the free screen reader NVDA, please visit
http://www.nvaccess.org/
Using Google Talkback on Motorolla G second generation Lollipop 5.0.2
Reach me through the following means:
Mobile: +91 7506221750
E-mail id: bhavya.shah125@gmail.com
Skype id : bhavya.09

**Comment by jcsteh** [comment]
> Just curious, would a browse mode implementation in Adobe Digital
> Editions tackle this issue as well like the End key one?

We could potentially "fake" lines like we do on the web. That is, they aren't the lines that sighted users see; we just break near a certain number of characters. Whether this is useful is controversial, but I (and quite a few others I think) find it easier to digest these smaller chunks even if they aren't strictly "lines".

> P.S. Would it be possible for you to pass on these accessibility
> issues to Adobe

I shall.
