### ISSUE TITLE
Adobe Digital Edition: End key does not go to the end of line

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#5644]
Steps to reproduce
• \* Open a document with at least one long paragraph (optional).
• \* Press End key.
• Expected Result: The focus will go to the end of the current line.
• Actual Result: The focus will not move. Character navigation and word navigation with left/right and Ctrl + left/right arrows works perfectly, but End just doesn’t work, by default, the focus always remains at the start of any line. 
Note: So, as a workaround, instead of End key, I go to the next line, and press Ctrl + left arrow, which goes to the end of the previous, actual line.

**Comment by jcsteh** [comment]
The cursor keys are actually implemented by Digital Editions, not NVDA. 
NVDA doesn't do anything special for cursor navigation in Digital 
Editions. That said, problems like this make me think we're going to 
need to do browse mode for Digital Editions so we have more control.

**Comment by bhavyashah** [comment]
Oh, sad to see inaccessibility in Adobe Digital Editions when it
states prominently on its website that it is screen reader accessible.
Anyways, this is a minor issue, Adobe Digital Editions is still great.
Looking forward to a browse mode implementation in Adobe Digital
Editions whenever possible, and hopefully in the future, in other word
processors and document viewers and ebook readers too...
Thanks.

-- 
Warm Regards
Bhavya Shah
Using NVDA (Non Visual Desktop Access) free and open source screen
reader for Microsoft Windows
To download a copy of the free screen reader NVDA, please visit
http://www.nvaccess.org/
Using Google Talkback on Motorolla G second generation Lollipop 5.0.2
Reach me through the following means:
Mobile: +91 7506221750
E-mail id: bhavya.shah125@gmail.com
Skype id : bhavya.09

**Comment by bhavyashah** [comment]
@jcsteh Do you consider the AdobeWork label sufficient or should NeedsExternalFix also be added to this (and maybe a couple others) ticket?

**Comment by jcsteh** [comment]
From what I understand, Adobe aren't really actively working on this any more, so changes are unlikely to happen there. It'd be possible to do browse mode in NVDA, but it's very low priority. Marking as p4.

**Comment by Adriani90** [comment]
@ruifontes

**Comment by nvdaes** [comment]
I'm not sure about the version which I have installed, seems 4.5.8 and now 4.5.10 is available. But the download link is 4.5.exed installer and I visited it. The bug can be reproduced here. Sincerely, I use this program just to purchase ebooks, but the reading experience is uncomfortable, so I can't provide too much feedback for this program.
As aside, Home key isn't working, and status bar can't be found.

**Comment by Adriani90** [comment]
Adobe actually discontinued further development of ADE years ago, and there were only two minor security updates during last 5 years. Adobe does not offer any assistance on ADE anymore. The only support is through online forums and the online help articles.
See these links for more information:
https://help.overdrive.com/en-us/0118.html
https://helpx.adobe.com/support/programs/adobe-support-policies-supported-product-versions.html
https://community.adobe.com/t5/digital-editions-discussions/is-digital-editions-discontinued/td-p/14494485

That being said, I am closing this issue as abandoned. I don't expect any further updates to the adobe digital editions regarding accessibility.
