### ISSUE TITLE
Improve accuracy and detail of touch gestures

### ISSUE THREAD

**Issue by michaelDCurran** [nvaccess/nvda#5652]
All though the over all UX for NVDA touch input could be improved, first it is necessary to make improvements to the underlying touch gesture detection code itself.
Currently there are several limitations and bugs with touch trackers and gestures such as:
* two fingers performing the same action are only merged into a multi finger action if the second finger contact starts after the first's start but before its end. This does not allow merging of fingers that overlap in other ways.
* It is possible for the user to get things like a tap and a tripple tap when trying to do a quadruple tap if multiple fingers are used.
* multi-finger and plural tap and holds are not supported very well.
 * Hovers flood speech in input help mode.
* It is impossible for scripts to find out information such as the coordinates of single fingers in a multiTouch gesture as it is lost in processing.
* Gestures with a hold (E.g. 1 finger hold + tap) are either non-existant or impossible to bind due to Python set ordering not being used.

**Comment by nvaccessAuto** [comment]
Incubated in fe46f4fe62077efdafc62e27a49b12f1518c1daf.

**Comment by nvaccessAuto** [comment]
Incubated in 1c5884df4b332fb9460a9cafdc90939c8ce85367.
