### ISSUE TITLE
NVDA crashes in word opening

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5656]
How this happened.
1. I had to do a web test with jaws and I shut it down. 
2. I booted nvda and went to open word to make notes about an issue on the webpage.
3. As word was opening, NVDA beeped and crashed.
There is some stuff in the log that has to do with the audioducking, right before the crash, and then at least 3 core cycles of core trying to recover from freeze.
The pdf extention should be removed to reveal .zip when you download because github hates zips and won't let me upload them. There is a log and a dmp here.
[wed-jan-6 word-crash-audio-ducking.zip.pdf](https://github.com/nvaccess/nvda/files/80138/wed-jan-6.word-crash-audio-ducking.zip.pdf)

**Comment by derekriemer** [comment]
I extracted the dump information from the crash dump file. Here it is. I couldn't get any quality information from it like a stack trace of addresses and instructions.

Dump Summary
------------
Dump File:	nvda_crash.dmp : C:\Users\derek_2\Google Drive\nvda\crashes\wed-jan-6 word-crash-audio-ducking\nvda_crash.dmp
Last Write Time:	1/6/2016 10:30:29 AM
Process Name:	nvda.exe : C:\Program Files (x86)\NVDA\nvda.exe
Process Architecture:	x86
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Not Present

System Information
------------------
OS Version:	6.3.9600
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
nvda.exe	C:\Program Files (x86)\NVDA\nvda.exe	0.0.0.0
ntdll.dll	C:\Windows\System32\ntdll.dll	6.3.9600.18146
kernel32.dll	C:\Windows\System32\kernel32.dll	6.3.9600.17415
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	6.3.9600.18007
user32.dll	C:\Windows\System32\user32.dll	6.3.9600.18123
msvcr90.dll	C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.8387_none_5094ca96bcb6b2bb\msvcr90.dll	9.0.30729.8387
gdi32.dll	C:\Windows\System32\gdi32.dll	6.3.9600.18034
imm32.dll	C:\Windows\System32\imm32.dll	6.3.9600.17415
msctf.dll	C:\Windows\System32\msctf.dll	6.3.9600.18081
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.9600.17415
python27.dll	C:\Program Files (x86)\NVDA\python27.dll	2.7.10150.1013
advapi32.dll	C:\Windows\System32\advapi32.dll	6.3.9600.18007
shell32.dll	C:\Windows\System32\shell32.dll	6.3.9600.18038
sechost.dll	C:\Windows\System32\sechost.dll	6.3.9600.17734
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	6.3.9600.17919
combase.dll	C:\Windows\System32\combase.dll	6.3.9600.17415
shlwapi.dll	C:\Windows\System32\shlwapi.dll	6.3.9600.17415
sspicli.dll	C:\Windows\System32\sspicli.dll	6.3.9600.17415
CRYPTBASE.dll	C:\Windows\System32\CRYPTBASE.dll	6.3.9600.17415
bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	6.3.9600.18088
_ctypes.pyd	C:\Program Files (x86)\NVDA\_ctypes.pyd	0.0.0.0
ole32.dll	C:\Windows\System32\ole32.dll	6.3.9600.17905
oleaut32.dll	C:\Windows\System32\oleaut32.dll	6.3.9600.17560
_hashlib.pyd	C:\Program Files (x86)\NVDA\_hashlib.pyd	0.0.0.0
cryptsp.dll	C:\Windows\System32\cryptsp.dll	6.3.9600.17415
rsaenh.dll	C:\Windows\System32\rsaenh.dll	6.3.9600.17415
bcrypt.dll	C:\Windows\System32\bcrypt.dll	6.3.9600.17415
winsound.pyd	C:\Program Files (x86)\NVDA\winsound.pyd	0.0.0.0
winmm.dll	C:\Windows\System32\winmm.dll	6.3.9600.17415
WINMMBASE.dll	C:\Windows\System32\WINMMBASE.dll	6.3.9600.17415
cfgmgr32.dll	C:\Windows\System32\cfgmgr32.dll	6.3.9600.17415
devobj.dll	C:\Windows\System32\devobj.dll	6.3.9600.17415
uxtheme.dll	C:\Windows\System32\uxtheme.dll	6.3.9600.17415
kernel.appcore.dll	C:\Windows\System32\kernel.appcore.dll	6.3.9600.17415
version.dll	C:\Windows\System32\version.dll	6.3.9600.17415
oleacc.dll	C:\Windows\System32\oleacc.dll	7.2.9600.17415
wx._core_.pyd	C:\Program Files (x86)\NVDA\wx._core_.pyd	0.0.0.0
wxbase30u_vc90.dll	C:\Program Files (x86)\NVDA\wxbase30u_vc90.dll	3.0.2.0
wxbase30u_net_vc90.dll	C:\Program Files (x86)\NVDA\wxbase30u_net_vc90.dll	3.0.2.0
wxmsw30u_core_vc90.dll	C:\Program Files (x86)\NVDA\wxmsw30u_core_vc90.dll	3.0.2.0
wxmsw30u_adv_vc90.dll	C:\Program Files (x86)\NVDA\wxmsw30u_adv_vc90.dll	3.0.2.0
msvcp90.dll	C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.8387_none_5094ca96bcb6b2bb\msvcp90.dll	9.0.30729.8387
wsock32.dll	C:\Windows\System32\wsock32.dll	6.3.9600.17415
comdlg32.dll	C:\Windows\System32\comdlg32.dll	6.3.9600.17415
winspool.drv	C:\Windows\System32\winspool.drv	6.3.9600.17415
comctl32.dll	C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9600.18006_none_a9ec6aab013aafee\comctl32.dll	6.10.9600.18006
ws2_32.dll	C:\Windows\System32\ws2_32.dll	6.3.9600.17415
nsi.dll	C:\Windows\System32\nsi.dll	6.3.9600.17415
SHCore.dll	C:\Windows\System32\SHCore.dll	6.3.9600.17666
wx._gdi_.pyd	C:\Program Files (x86)\NVDA\wx._gdi_.pyd	0.0.0.0
wx._windows_.pyd	C:\Program Files (x86)\NVDA\wx._windows_.pyd	0.0.0.0
wxmsw30u_html_vc90.dll	C:\Program Files (x86)\NVDA\wxmsw30u_html_vc90.dll	3.0.2.0
wx._controls_.pyd	C:\Program Files (x86)\NVDA\wx._controls_.pyd	0.0.0.0
wx._misc_.pyd	C:\Program Files (x86)\NVDA\wx._misc_.pyd	0.0.0.0
MMDevAPI.dll	C:\Windows\System32\MMDevAPI.dll	6.3.9600.17415
wdmaud.drv	C:\Windows\System32\wdmaud.drv	6.3.9600.17415
ksuser.dll	C:\Windows\System32\ksuser.dll	6.3.9600.17415
avrt.dll	C:\Windows\System32\avrt.dll	6.3.9600.17415
AudioSes.dll	C:\Windows\System32\AudioSes.dll	6.3.9600.17415
powrprof.dll	C:\Windows\System32\powrprof.dll	6.3.9600.17415
msacm32.drv	C:\Windows\System32\msacm32.drv	6.3.9600.17415
msacm32.dll	C:\Windows\System32\msacm32.dll	6.3.9600.17415
midimap.dll	C:\Windows\System32\midimap.dll	6.3.9600.17415
_socket.pyd	C:\Program Files (x86)\NVDA\_socket.pyd	0.0.0.0
_ssl.pyd	C:\Program Files (x86)\NVDA\_ssl.pyd	0.0.0.0
crypt32.dll	C:\Windows\System32\crypt32.dll	6.3.9600.17475
msasn1.dll	C:\Windows\System32\msasn1.dll	6.3.9600.17415
unicodedata.pyd	C:\Program Files (x86)\NVDA\unicodedata.pyd	0.0.0.0
pyexpat.pyd	C:\Program Files (x86)\NVDA\pyexpat.pyd	0.0.0.0
liblouis.dll	C:\Program Files (x86)\NVDA\liblouis.dll	0.0.0.0
windowsAccessBridge-32.DLL	C:\Windows\System32\windowsAccessBridge-32.DLL	2.0.7.0
win32clipboard.pyd	C:\Program Files (x86)\NVDA\win32clipboard.pyd	2.7.218.0
pywintypes27.dll	C:\Program Files (x86)\NVDA\pywintypes27.dll	2.7.218.0
nvdaHelperLocal.dll	C:\Program Files (x86)\NVDA\lib\nvdaHelperLocal.dll	0.0.0.0
usp10.dll	C:\Windows\System32\usp10.dll	6.3.9600.17415
UIAutomationCore.dll	C:\Windows\System32\UIAutomationCore.dll	7.2.9600.17795
nvdaHelperRemote.dll	C:\Program Files (x86)\NVDA\lib\nvdaHelperRemote.dll	0.0.0.0
dbghelp.dll	C:\Windows\System32\dbghelp.dll	6.3.9600.17787
IAccessible2Proxy.dll	C:\Program Files (x86)\NVDA\lib\IAccessible2Proxy.dll	0.0.0.0
clbcatq.dll	C:\Windows\System32\clbcatq.dll	2001.12.10530.17415
minHook.dll	C:\Program Files (x86)\NVDA\lib\minHook.dll	1.2.2.0
espeak.dll	C:\Program Files (x86)\NVDA\synthDrivers\espeak.dll	0.0.0.0
dwmapi.dll	C:\Windows\System32\dwmapi.dll	6.3.9600.17415
sxs.dll	C:\Windows\System32\sxs.dll	6.3.9600.17415
actxprxy.dll	C:\Windows\System32\actxprxy.dll	6.3.9600.18124
msftedit.dll	C:\Windows\System32\msftedit.dll	6.3.9600.17809
msimg32.dll	C:\Windows\System32\msimg32.dll	6.3.9600.17415
_psutil_mswindows.pyd	C:\Users\derek_2\AppData\Roaming\nvda\addons\resourceMonitor\globalPlugins\resourceMonitor\psutil\_psutil_mswindows.pyd	0.0.0.0
psapi.dll	C:\Windows\System32\psapi.dll	6.3.9600.17415
IPHLPAPI.DLL	C:\Windows\System32\IPHLPAPI.DLL	6.3.9600.17415
wtsapi32.dll	C:\Windows\System32\wtsapi32.dll	6.3.9600.17415
winnsi.dll	C:\Windows\System32\winnsi.dll	6.3.9600.17415
select.pyd	C:\Program Files (x86)\NVDA\select.pyd	0.0.0.0
profapi.dll	C:\Windows\System32\profapi.dll	6.3.9600.17415
_imaging.pyd	C:\Users\derek_2\AppData\Roaming\nvda\addons\ocr\globalPlugins\ocr\PIL\_imaging.pyd	0.0.0.0
libsndfile-1.dll	C:\Users\derek_2\AppData\Roaming\nvda\addons\audioScreen\globalPlugins\audioScreen\deps\libaudioverse\libsndfile-1.dll	1.0.25.0
libaudioverse.dll	C:\Users\derek_2\AppData\Roaming\nvda\addons\audioScreen\globalPlugins\audioScreen\deps\libaudioverse\libaudioverse.dll	0.0.0.0
MathPlayer.dll	C:\Program Files (x86)\Design Science\MathPlayer\MathPlayer.dll	2015.3.4.0
wininet.dll	C:\Windows\System32\wininet.dll	11.0.9600.18124
GdiPlus.dll	C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.9600.18123_none_dad9a2585bcb0fd8\GdiPlus.dll	6.3.9600.18123
iertutil.dll	C:\Windows\System32\iertutil.dll	11.0.9600.18124
userenv.dll	C:\Windows\System32\userenv.dll	6.3.9600.17415
AccessibleMarshal.dll	C:\Program Files (x86)\Instantbird\AccessibleMarshal.dll	25.0.0.5099
msvcr100.dll	C:\Program Files (x86)\Instantbird\msvcr100.dll	10.0.40219.1
mozglue.dll	C:\Program Files (x86)\Instantbird\mozglue.dll	25.0.0.5099
msvcp100.dll	C:\Program Files (x86)\Instantbird\msvcp100.dll	10.0.40219.1
msxml3.dll	C:\Windows\System32\msxml3.dll	8.110.9600.18046
twinapi.dll	C:\Windows\System32\twinapi.dll	6.3.9600.17415
twinapi.appcore.dll	C:\Windows\System32\twinapi.appcore.dll	6.3.9600.17415
setupapi.dll	C:\Windows\System32\setupapi.dll	6.3.9600.17415
fsbrldspapi.DLL	C:\Windows\System32\fsbrldspapi.DLL	13.0.718.400
wintrust.dll	C:\Windows\System32\wintrust.dll	6.3.9600.17415
bthprops.cpl	C:\Windows\System32\bthprops.cpl	6.3.9600.17415
BluetoothApis.dll	C:\Windows\System32\BluetoothApis.dll	6.3.9600.17415
LibLouisBrailleCom.dll	C:\Program Files (x86)\Design Science\MathPlayer\LibLouisBrailleCom.dll	1.0.0.1

**Comment by bhavyashah** [comment]
An NVDA crash, that too with a program as frequently used as Word, is usually quite concerning. Could someone please diagnose this report?

**Comment by derekriemer** [comment]
I'll look at this in the next month? I have the dump file, and I can look at it once I get my new drive. In case I forget, here's the dump.

**Comment by derekriemer** [comment]
never mind, I deleted that dump. Oops.

**Comment by derekriemer** [comment]
What we really would need is a stack trace, which I now can't get,, recommend a close.

**Comment by bhavyashah** [comment]
As noted by @derekriemer in https://github.com/nvaccess/nvda/issues/5656#issuecomment-320151668, as the original author of this ticket, he recommends a close. Please do so. @ehollig and other
