### ISSUE TITLE
Download page: Provide a way to validate the e-mail address

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#5658]
Currently, in the e-mail address field whatever string can be entered.
If a direct link was sent to the entered address, perhaps with a translated message if language preferences can be set, as in the add-ons website:
1. This would be a mechanism for validating e-mail.
2. It will be possible provide help to friends who ask how to download NVDA, by typing their e-mail addresses.
Thanks.

**Comment by leonardder** [comment]
Comfirmed. CC @MichaelDCurran @JCSTeh

**Comment by jcsteh** [comment]
Thanks for the suggestion.

We don't want to require users to open an email to access the download, as we already get enough flack for requiring an email address at all.

Using this to help friends download NVDA is interesting, but would probably open us up to spam complaints and service providers are getting very aggressive about such things now.

Closing as won't fix.
