### ISSUE TITLE
iTunes: Browse mode not updated when performing an Apple Music search

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#5659]
STR (requires an Apple Music subscription):

1. Open iTunes.
2. Select Music.
3. Select the "For you" radio button.
4. Press control+f.
5. Type "Dream Theater" and press enter.
6. Press shift+f6 to move to the results document.
7. Press control+f.
8. Type "Sleepthief" and press enter.
9. Press shift+f6 to move to the results document.
10. Press control+home and read the first line.
 * Expected: 'Showing Results for “Sleepthief” in Apple Music'
 * Actual: Either blank or 'Showing Results for “dream theater” in Apple Music'

**Comment by nvaccessAuto** [comment]
Incubated in 36422be5d2efb0e5121dc2f06a15ff2e80d0c42a.
