### ISSUE TITLE
NVDA sometimes causing an error in classic Windows Dialogs

### ISSUE THREAD

**Issue by btman16** [nvaccess/nvda#5663]
In Windows 10, I was trying to go to the run box, and when I typed in something that didn't exist, I heard the error sound, but NVDA just said ok button, instead of reading the dialog saying it couldn't find what I typed.

Steps to reproduce:
1. Press windows+R for the run dialog.
2. Type something that doesn't exist, like the word test, and press enter.
3. You will get the windows error sound and normally, NVDA reads this dialog, saying windows cannot find test, make sure you typed the name correctly, and then try again. Ok button.
But for me in Windows 10, it just said, ok button.
Note that this problem does not happen often at all but I just wanted to report it.

My system has 2 gb of Ram, but I've also seen this on some high end machines running Windows 8.1.

Thanks,

Brandon

**Comment by jcsteh** [comment]
What exact version of NVDA?

**Comment by jcsteh** [comment]
Also, a log file is necessary for us to diagnose this. Thanks.

**Comment by btman16** [comment]
Hello,

It is NVDA 2015.4.
Next time I see this, I will attach the log file. I haven't seen it since.

Thanks,

Brandon

On 1/10/16, James Teh <notifications@github.com> wrote:
> Also, a log file is necessary for us to diagnose this. Thanks.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/5663#issuecomment-170403676


-- 
It is simply sitting silently, witnessing the thoughts, passing before
you. Just witnessing, not interfering not even judging, because the
moment you judge you have lost the pure witness. The moment you say
"this is good, this is bad," you have already jumped onto the thought
process.
-- Osho

**Comment by btman16** [comment]
I was in notepad and tried to press alt+f4 to get the save dialog and
got the following output:
ERROR - eventHandler.executeEvent (20:29:21):
error executing event: focusEntered on
<NVDAObjects.Dynamic_DialogIAccessibleWindowNVDAObject object at
0x04D48470> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 853, in event_focusEntered
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\behaviors.pyc", line 141, in _get_isPresentableFocusAncestor
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1305, in
_get_isPresentableFocusAncestor
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 788, in _get_isPresentableFocusAncestor
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 617, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\behaviors.pyc", line 134, in _get_description
  File "NVDAObjects\behaviors.pyc", line 89, in getDialogText
  File "NVDAObjects\behaviors.pyc", line 75, in getDialogText
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 650, in _get_children
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUG - audioDucking.AudioDucker.disable (20:29:31):
disabling
DEBUG - audioDucking._unensureDucked (20:29:31):
Queuing _unensureDucked
DEBUG - audioDucking.AudioDucker.disable (20:29:31):
Ignoring duplicate disable
IO - speech.speak (20:29:31):
Speaking [LangChangeCommand ('en'), u'Untitled - Notepad']
IO - speech.speak (20:29:31):
Speaking [LangChangeCommand ('en'), u'edit  multi line']
IO - speech.speak (20:29:31):
Speaking [LangChangeCommand ('en'), u'blank']
DEBUG - audioDucking.AudioDucker.enable (20:29:31):
enabling
DEBUG - audioDucking._ensureDucked (20:29:31):
Increased ref count, _duckingRefCount=3
DEBUG - audioDucking.AudioDucker.enable (20:29:31):
whenWasDucked 1452475771.88, deltaMS -1452475771725
DEBUG - audioDucking.AudioDucker.enable (20:29:31):
ignoring duplicate enable
DEBUG - audioDucking.AudioDucker.enable (20:29:32):
ignoring duplicate enable
DEBUG - audioDucking.AudioDucker.enable (20:29:32):
ignoring duplicate enable
DEBUG - audioDucking._unensureDucked (20:29:32):
Decreased  ref count, _duckingRefCount=2
DEBUG - audioDucking.AudioDucker.enable (20:29:32):
ignoring duplicate enable
DEBUG - audioDucking._unensureDucked (20:29:32):
Decreased  ref count, _duckingRefCount=1
DEBUG - audioDucking.AudioDucker.disable (20:29:34):
disabling
DEBUG - audioDucking._unensureDucked (20:29:34):
Queuing _unensureDucked
DEBUG - audioDucking.AudioDucker.disable (20:29:34):
Ignoring duplicate disable
IO - inputCore.InputManager.executeGesture (20:29:34):
Input: kb(desktop):alt+f4
ERROR - eventHandler.executeEvent (20:29:35):
error executing event: focusEntered on
<NVDAObjects.Dynamic_DialogIAccessibleWindowNVDAObject object at
0x04E94590> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 853, in event_focusEntered
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\behaviors.pyc", line 141, in _get_isPresentableFocusAncestor
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1305, in
_get_isPresentableFocusAncestor
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 788, in _get_isPresentableFocusAncestor
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 617, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\behaviors.pyc", line 134, in _get_description
  File "NVDAObjects\behaviors.pyc", line 89, in getDialogText
  File "NVDAObjects\behaviors.pyc", line 75, in getDialogText
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 650, in _get_children
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
IO - speech.speak (20:29:35):
Speaking [LangChangeCommand ('en'), u'Save  button  Alt+S']
DEBUG - audioDucking.AudioDucker.enable (20:29:35):
enabling
DEBUG - audioDucking._ensureDucked (20:29:35):
Increased ref count, _duckingRefCount=2
DEBUG - audioDucking.AudioDucker.enable (20:29:35):
whenWasDucked 1452475775.09, deltaMS -1452475774939
DEBUG - audioDucking.AudioDucker.enable (20:29:35):
ignoring duplicate enable
DEBUG - audioDucking._unensureDucked (20:29:35):
Decreased  ref count, _duckingRefCount=1
IO - inputCore.InputManager.executeGesture (20:29:36):
Input: kb(desktop):tab
DEBUG - audioDucking.AudioDucker.disable (20:29:36):
disabling
DEBUG - audioDucking._unensureDucked (20:29:36):
Queuing _unensureDucked
DEBUG - audioDucking.AudioDucker.disable (20:29:36):
Ignoring duplicate disable
IO - speech.speak (20:29:36):
Speaking [LangChangeCommand ('en'), u"Don't Save  button  Alt+n"]
DEBUG - audioDucking.AudioDucker.enable (20:29:36):
enabling
DEBUG - audioDucking._ensureDucked (20:29:36):
Increased ref count, _duckingRefCount=2
DEBUG - audioDucking.AudioDucker.enable (20:29:36):
whenWasDucked 1452475776.42, deltaMS -1452475776274
DEBUG - audioDucking.AudioDucker.enable (20:29:36):
ignoring duplicate enable
IO - inputCore.InputManager.executeGesture (20:29:36):
Input: kb(desktop):tab
DEBUG - audioDucking.AudioDucker.disable (20:29:36):
disabling
DEBUG - audioDucking._unensureDucked (20:29:36):
Queuing _unensureDucked
DEBUG - audioDucking.AudioDucker.disable (20:29:36):
Ignoring duplicate disable
IO - speech.speak (20:29:36):
Speaking [LangChangeCommand ('en'), u'Cancel  button']
DEBUG - audioDucking.AudioDucker.enable (20:29:36):
enabling
DEBUG - audioDucking._ensureDucked (20:29:36):
Increased ref count, _duckingRefCount=3
DEBUG - audioDucking.AudioDucker.enable (20:29:36):
whenWasDucked 1452475776.71, deltaMS -1452475776560
IO - inputCore.InputManager.executeGesture (20:29:37):
Input: kb(desktop):space
DEBUG - audioDucking.AudioDucker.disable (20:29:37):
disabling
DEBUG - audioDucking._unensureDucked (20:29:37):
Queuing _unensureDucked
IO - speech.speak (20:29:37):
Speaking [LangChangeCommand ('en'), u'pressed']
DEBUG - audioDucking.AudioDucker.disable (20:29:37):
Ignoring duplicate disable
DEBUG - audioDucking.AudioDucker.enable (20:29:37):
enabling
DEBUG - audioDucking._ensureDucked (20:29:37):
Increased ref count, _duckingRefCount=4
DEBUG - audioDucking.AudioDucker.enable (20:29:37):
whenWasDucked 1452475777.13, deltaMS -1452475776981
DEBUG - audioDucking.AudioDucker.disable (20:29:37):
disabling
DEBUG - audioDucking._unensureDucked (20:29:37):
Queuing _unensureDucked
DEBUG - audioDucking.AudioDucker.disable (20:29:37):
Ignoring duplicate disable
IO - speech.speak (20:29:37):
Speaking [LangChangeCommand ('en'), u'Untitled - Notepad']
DEBUG - audioDucking.AudioDucker.enable (20:29:37):
enabling
DEBUG - audioDucking._ensureDucked (20:29:37):
Increased ref count, _duckingRefCount=5
DEBUG - audioDucking.AudioDucker.enable (20:29:37):
whenWasDucked 1452475777.23, deltaMS -1452475777083
IO - speech.speak (20:29:37):
Speaking [LangChangeCommand ('en'), u'edit  multi line']
IO - speech.speak (20:29:37):
Speaking [LangChangeCommand ('en'), u'blank']
DEBUG - audioDucking.AudioDucker.enable (20:29:37):
ignoring duplicate enable
DEBUG - audioDucking._unensureDucked (20:29:37):
Decreased  ref count, _duckingRefCount=4
DEBUG - audioDucking.AudioDucker.disable (20:29:37):
disabling
DEBUG - audioDucking._unensureDucked (20:29:37):
Queuing _unensureDucked
DEBUG - audioDucking.AudioDucker.disable (20:29:37):
Ignoring duplicate disable
DEBUG - audioDucking._unensureDucked (20:29:37):
Decreased  ref count, _duckingRefCount=3
DEBUG - audioDucking._unensureDucked (20:29:38):
Decreased  ref count, _duckingRefCount=2
DEBUG - audioDucking._unensureDucked (20:29:38):
Decreased  ref count, _duckingRefCount=1
DEBUG - audioDucking._unensureDucked (20:29:38):
Decreased  ref count, _duckingRefCount=0
IO - inputCore.InputManager.executeGesture (20:29:39):
Input: kb(desktop):NVDA+n
IO - speech.speak (20:29:39):
Speaking [LangChangeCommand ('en'), u'NVDA  menu']
DEBUG - audioDucking.AudioDucker.enable (20:29:39):
enabling
DEBUG - audioDucking._ensureDucked (20:29:39):
Increased ref count, _duckingRefCount=1
DEBUG - audioDucking.AudioDucker.enable (20:29:39):
whenWasDucked 1452475779.66, deltaMS -1452475779514
DEBUG - audioDucking.AudioDucker.enable (20:29:39):
ignoring duplicate enable
IO - inputCore.InputManager.executeGesture (20:29:40):
Input: kb(desktop):t
DEBUG - audioDucking.AudioDucker.disable (20:29:40):
disabling
DEBUG - audioDucking._unensureDucked (20:29:40):
Queuing _unensureDucked
DEBUG - audioDucking.AudioDucker.disable (20:29:40):
Ignoring duplicate disable
IO - speech.speak (20:29:40):
Speaking [LangChangeCommand ('en'), u'View log  v']
DEBUG - audioDucking.AudioDucker.enable (20:29:40):
enabling
DEBUG - audioDucking._ensureDucked (20:29:40):
Increased ref count, _duckingRefCount=2
DEBUG - audioDucking.AudioDucker.enable (20:29:40):
whenWasDucked 1452475780.71, deltaMS -1452475780556
IO - inputCore.InputManager.executeGesture (20:29:41):
Input: kb(desktop):enter



On 1/10/16, brandon T <brandongold98@gmail.com> wrote:
> Hello,
>
> It is NVDA 2015.4.
> Next time I see this, I will attach the log file. I haven't seen it since.
>
> Thanks,
>
> Brandon
>
> On 1/10/16, James Teh <notifications@github.com> wrote:
>> Also, a log file is necessary for us to diagnose this. Thanks.
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/nvaccess/nvda/issues/5663#issuecomment-170403676
>
>
> --
> It is simply sitting silently, witnessing the thoughts, passing before
> you. Just witnessing, not interfering not even judging, because the
> moment you judge you have lost the pure witness. The moment you say
> "this is good, this is bad," you have already jumped onto the thought
> process.
> -- Osho
>


-- 
It is simply sitting silently, witnessing the thoughts, passing before
you. Just witnessing, not interfering not even judging, because the
moment you judge you have lost the pure witness. The moment you say
"this is good, this is bad," you have already jumped onto the thought
process.
-- Osho

**Comment by jcsteh** [comment]
Follow up commit 13d8e246.
