### ISSUE TITLE
Whats new guide incorrectly says to look for audio ducking support in general settings.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5668]
In the whats new guide, it incorrectly says to look for audioducking changes in the general settings dialog. It should say synthesiser settings. PR next.

**Comment by derekriemer** [comment]
Fixed in https://github.com/nvaccess/nvda/pull/5669

**Comment by derekriemer** [comment]
Jamie and Mik, is this the best way to do changes now that we are on github?

**Comment by jcsteh** [comment]
Thanks! A few things:

* For a trivial fix like this, you can just submit a pull request and not bother with an issue. Basically, if the design, UX or whatever might require discussion, you should file an issue first before you code, but if it's a fix which pretty much anyone would do the same way, there's no point. I tried to suggest this in the [Contributing](https://github.com/nvaccess/nvda/wiki/Contributing) document, but reading it again, I didn't do a particularly good job of this, so I'll need to tweak it.
* Pull requests are certainly the correct way to submit code changes, regardless of whether you discuss them first in an issue.
* The dialog is just called Synthesizer, not Synthesizer Settings, so I changed this.

**Comment by Brian1Gaff** [comment]
I'd say only if you understand what you are doing.....:-)
 Brian

--------------------------------------------------
