### ISSUE TITLE
NVDA in MS word, not anouncing bullets and numbering

### ISSUE THREAD

**Issue by abdullah5490** [nvaccess/nvda#5672]
this is word 2016 and NVDA 2015.4. i have also tried enabling different settings within the document formatting dialog of NVDA, but it still not detecting the lists in words marked by bullets, numbering, or an alphabetical order. i am not talking about reporting the "list start" and "out of list" phrase, actually it is about the numbers that are used to present multiple itums in a list such as 1. some text then next line. 2. some more text and then a line, and so on. NVDA will read the given text, but not the numbers before it. thanks for reading.

**Comment by jcsteh** [comment]
You need to enable "Report lists" in NVDA's Document Formatting dialog.

**Comment by abdullah5490** [comment]
it is enabled, but it needs to report, "list start", "out of list"

**Comment by jcsteh** [comment]
You just said in the description that you weren't talking about those messages, but rather, the bullets and numbering:

> i am not talking about reporting the "list start" and "out of list" phrase, actually it is about the numbers that are used to present multiple itums in a list such as 1. some text...
