### ISSUE TITLE
Elements List: Cursor reset to Type grouping upon Refocus

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5683]
Currently, when the Elements List is invoked the list of elements that matches the default criteria is displayed (in this case, links). However, if the user switches focus to another window and then gives focus back to the Elements List, the list of radio buttons that changes the type of elements displayed automatically gains focus.

Would it be possible to retain focus on whichever control was being used last when this step is performed?

**Comment by jcsteh** [comment]
Same underlying issue as #4918.
