### ISSUE TITLE
Elements List: List of elements reported as Tree View

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5684]
When initially opening the Elements List, NVDA reports that the list of displayed elements is a tree view.

Unless I'm missing something very obvious (and let's be honest, that could most definitely be the case), this control shouldn't be treated as a tree view because it can only be cursored up/down. Was there any reason that a tree view was chosen for this particular section of the dialog?

**Comment by jcsteh** [comment]
While some elements (links) are only a flat list, other elements (headings, landmarks) can be hierarchical. The tree view represents the hierarchy in the latter case.
