### ISSUE TITLE
Windows 10/Start Menu: submenus in context menus for tiles are not recognized as such

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#5686]
Hi,
I've seen this in Version 1511 so far (don't have a machine running the RTM build to test this)...
When you open a context menu for a tile, submenus are not recognized as such.

STR:
1. On Windows 10, open Start Menu.
2. Select a tile (say, Microsoft Edge).
3. Open the context menu and navigate around.
4. Press right arrow when you arrive at entries such as "resize" and "more".
- Expected: NVDA announces these items as submenus.
- Actual: No submenu indication is given.

Technical: UIA class name for these items is "MenuFlyoutSubItem" as opposed to "MenuFlyoutItem" for regular menu entries. For now, Windows 10 App Essentials 16.01 deals with tile context menus in Start Menu, but I'm wondering if there are other places where UIA and NVDA have disagreements over which items are submenus or not (if it does, then it changes the implementation strategy).

Implementation:
1. At least in Windows 10 App Essentials add-on, I've modified appModules/shellexperiencehost.py by adding a UIA overlay class for submenus. This takes care of the issue outlined here.
2. If other UIA submenus are affected, the developer who'll be implementing a fix should add a UIA overlay class (in NVDAObjects.UIA namespace)  an appropriate entry in chooseNVDAObjectOverlayClasses function to let NVDA recognize this control.

Thanks.

**Comment by jcsteh** [comment]
It seems UIA doesn't have an equivalent of the HASPOPUP state.

Do these report that they're collapsed? If so, I'd prefer to use this 
fact to add the HASPOPUP state for all UIA menu items which expose this.

**Comment by josephsl** [comment]
Hi,

 

When viewed from NVDA’s perspective, it doesn’t report as collapsed (although the current UI, based on behavior I’ve seen, a new window pops up when “submenus” are clicked). Also, when I “close” the submenu and return to it, it does not focus me to the first item (quite weird).

 

Based on the fact that Narrator reports it as “collapsed”, I’d go with your suggestion (I’ve seen collapsed state defined in control types). Thanks.

**Comment by josephsl** [comment]
Hi,

As a follow-up: reassigning role to treeview item sort of solved it (collapsed is now reported). If there are controls that are really menu items that'll report collapsed state...
Thanks.

**Comment by jcsteh** [comment]
In that case, NVDA+tab should report collapsed when it's left as a menu 
item. (We filter out reporting of collapsed for menu items normally, but 
NVDA+tab overrides this.)

**Comment by josephsl** [comment]
Hi,

 

I see. Then I guess the question is how to let NVDA announce (in speech and braille) that the menu item is collapsed for that class of items – perhaps we may need to ask Microsoft about exposing collapsed state for these kinds of controls in the future.

Thanks.

**Comment by ehollig** [comment]
@josephsl, is this now fixed in NVDA without addons?

**Comment by Adriani90** [comment]
Hello, testing with Windows 10 1809 update, sub menus are announced as "colapsed" similar to tree views. In my view this is acceptable. At this moment the windows 10 app essentials addon from @josephsl changes this behavior and NVDA announces "submenu". So, the addon is actually not required now in order to be notified if an menu item can be expanded or not. it works without the addon as well.
@josephsl can you confirm?

**Comment by josephsl** [comment]
Hi, I need to do more thorough testing with 1903, along with making sure it is still working for Edge. Thanks,

**Comment by Adriani90** [comment]
It seems it's working in 1909 as well. @josephsl do you still see this issue? I think it can be closed.

**Comment by josephsl** [comment]
Hi, let’s close this for now – I have removed the workaround from my add-on a few days ago, seeing improved state detection. Thanks.

**Comment by Adriani90** [comment]
Thanks for reporting back. Closing for now. we can reopen if the issue appears again.
