### ISSUE TITLE
Microsoft Excel: Shift+f11 to create new sheet should report new position

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#5689]
Shift+f11 is the shortcut key to create a new sheet. However, NVDA doesn't report anything when you press it. We should report it the same way we report control+pageUp/pageDown.

**Comment by nvaccessAuto** [comment]
Incubated in 5ceda18fbaf1b1795338ac668436e5fddeafdde7.

**Comment by surfer0627** [comment]
Technically, is it possible to braille your position  while pressing commands: 
• shift+f11
• control+pageUp/pageDown

**Comment by michaelDCurran** [comment]
What kind of position do you mean? cell address, sheet name, or sheet 
index (e.g. 3 of 6)?
* Cell address should already be brailled.
* Sheet name can be seen on the braille display if you scroll back.
* Sheet index is not available in either speech or braille.

**Comment by surfer0627** [comment]
I mean sheet name.
at the beginning, I just expected a ui.message shows sheet name, while user press shift+f11.

Before reading previous comment, I do not know that sheet name could be brailled while tethered to focus.
In this case, user could read sheet name and cell text. But, user may not need to know sheet name while arrowing through sheet cells.


It would be great, if cell text could be presented from the first cell on the display. User could experience this design  when braille tethered to review.
Related issue 
[217](https://github.com/nvaccess/nvda/issues/217)

**Comment by surfer0627** [comment]
I mean sheet name.
at the beginning, I just expected a braille message shows sheet name, while user press shift+f11.

Before reading previous comment, I do not know that sheet name could be brailled while tethered to focus.
In this case, user could read sheet name and cell text. But, user may not need to know sheet name while arrowing through sheet cells.


It would be great, if cell text could be presented from the first cell on the display. User could experience this design  when braille tethered to review.
Related issue 
[217](https://github.com/nvaccess/nvda/issues/217)
