### ISSUE TITLE
Microsoft Excel: Report groups

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#5690]
We need to report when entering and/or exiting groups of cells. Either rows or columns can be grouped. Groups can also be nested, so we should report levels.

**Comment by nvaccessAuto** [comment]
Incubated in cd543f6efa5e5f57b10377c82a26f93dcd8859dd.

**Comment by nvaccessAuto** [comment]
Incubated in 89e48fa3916a50d5a5c9ba1c71e57e6882481a34.

**Comment by nvaccessAuto** [comment]
Incubated in f5085334822ecd44498a6d661d3de093530db449.
