### ISSUE TITLE
Annotations in browse mode on the web

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#5691]
Pressing "a" or shift+a to navigate by annotation says "No next/previous annotation".

1. In Internet Explorer, this should search for ins/del tags.
2. In other browsers, it should report "Not supported in this document".

 I think this can be generalised to all quick navigation types that aren't supported by specific VirtualBuffers. I think this can be done by having `VirtualBuffer._iterNodesByType` raise NotImplementedError instead of returning an empty iterator when a type is not supported.

 On a related note, `BrowseModeTreeInterceptor._iterNodesByType` needs to document that it can raise NotImplementedError. It should probably also do this itself instead of returning an empty iterator.

Thoughts, @MichaelDCurran?

**Comment by leonardder** [comment]
This reminds me of the fact that browse mode in Word says 'not supported' when using e for edit boxes, while there are in fact documents with edit boxes in word.

**Comment by nvaccessAuto** [comment]
Incubated in 777280adfc3c8e86d66bea7e5955650884e655d8.
