### ISSUE TITLE
tabindex="0" on "tr" or "td" element turns off browse mode

### ISSUE THREAD

**Issue by RichCaloggero** [nvaccess/nvda#5696]
Placing tabindex="0" on a "tr" element or "td" element turns off browse mode when that row or cell gains focus.
Browse mode is not turned off if the cell contains a natively focusable element (i.e. link or button).

See: http://www.mit.edu/~rjc/aria/test/tabindex-table.html

**Comment by jcsteh** [comment]
If you make a table row or cell focusable, that suggests it is interactive; i.e. that it implements its own keyboard navigation. This is the basis for something like a spreadsheet grid where the arrow keys move between cells. Thus, we switch to focus mode for it.

**Comment by RichCaloggero** [comment]
If you expect to implement keyboard navigation, then use the role="grid" and other supporting attributes throughout the table.  I don't believe browse mode should be disabled without the grid role present.

**Comment by jcsteh** [comment]
In that case, why make them focusable at all?

**Comment by RichCaloggero** [comment]
If you want a grid which is operable via both keyboard and mouse, and 
correctly propagates and handles focus events, then use role="grid" on the 
table and all correct subroles.  The role turns off browse mode.  Otherwise, 
browse mode should stay enabled no matter what other attributes are placed 
on subnodes.  I fail to see why placing tabindex="0" on a table subnode 
effects browse mode in any way.  I think turning off browse mode 
automatically should be a very rare operation. Only a very few roles, 
including role="application" should do this.

Just my two cents...
-- Rich



-----Original Message-----

**Comment by jcsteh** [comment]
On the contrary, it is intended that focus mode be enabled whenever focus hits most interactive elements. If you don't want this, turn off Automatic focus mode for focus changes in Browse Mode settings.

You still haven't given a use case as to why a table row/cell should be focusable when it isn't intended to be interactive.
