### ISSUE TITLE
Excel Elements list: include chart-only sheets in sheets list

### ISSUE THREAD

**Issue by michaelDCurran** [nvaccess/nvda#5698]
Currently only worksheets are listed in NVDA's elements list for Excel when sheets is selected as the type. This means that chart-only sheets are not included.
SheetsExcelCollectionQuicknavIterator's collectionFromWorksheet method should return the sheets collection from the active workbook, rather than the worksheets collection.

**Comment by nvaccessAuto** [comment]
Incubated in 910651350afbffbce0f49ade35eb5b15a0d1b05a.
