### ISSUE TITLE
adding a menu to include all the addons

### ISSUE THREAD

**Issue by fatmamehanna** [nvaccess/nvda#5707]
hi all,
i'd like to ask for a menu, or even a menu item, to be devoted to include all the addons and its preferences. for instance, we find some addons in the tools menu, others in the preferences menu, etc. so i think it would be easier to devote a menu or a menu item to go to when we want to control/modify an addon settings.
thanks.

**Comment by leonardder** [comment]
CC @DerekRiemer @JosephSL

**Comment by ehollig** [comment]
Duplicate of #4689
