### ISSUE TITLE
error when editing text in chrome

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#5710]
This error occurs when trying to read a text word for word in the google translator.
 Hall for reproduce translatethe error.
1. open the google translator in chrome.
2. In field to enter the text to be translate enter a large text with more than 2 lines.
3. walk with down arrow to the translate text.
4. put the focus early in the first line of text translate with home and walk word for word with Ctrl + arrow right.
   It is expected that NVDA read through the text word for word without problems.
   What happens is that the first line of text is read correctly, but the second line by walking word to word with Ctrl + arrow right, NVDA will read the end of a word and the beginning of another word as if they were a word.

**Comment by jcsteh** [comment]
When you say "the Google Translator", do you mean some function in 
Chrome or translate.google.com? Please provide exact steps to get there.

Also, please provide an example of some text you entered, the exact 
incorrect words that were spoken on the second line and the words you 
expected instead.

**Comment by fernando-jose-silva** [comment]
Thank you for listening, and sorry for the English poorly.

When I talk google translator I mean translate.google.com.

To reproduce the problem, do the following:

Open chrome.

In the address bar enter https://translate.google.com.br/?hl=pt-BR&tab=wT

Pressing ctrl + home to go to the first line of the page.

Press and to go to the text input field to be translated.

Enter the text:

Estou fazendo um teste na página do google tradutor fazendo uso do leitor de telas nvda e o navegador web google chrome.

Return with the arrows above and choose to output text translation of the English language.

Walk with the arrow below to the translated text to be:

I'm doing a test in the google translator page making use of the NVDA screen reader and web google chrome browser.

Pressing home and read the text with Ctrl + arrow right NVDA will read the text above as follows:

I'm doing a test in thegoogletranslatorpagemaking use of theNVDAscreen readerandwebgoogle chromebrowser. 

 

 

De: James Teh [mailto:notifications@github.com] 
Enviada em: domingo, 24 de janeiro de 2016 20:52
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>
Assunto: Re: [nvda] error when editing text in chrome (#5710)

 

When you say "the Google Translator", do you mean some function in 
Chrome or translate.google.com? Please provide exact steps to get there.

Also, please provide an example of some text you entered, the exact 
incorrect words that were spoken on the second line and the words you 
expected instead.

**Comment by ehollig** [comment]
@fernando-jose-silva, is this still happening for you? I am not able to replicate using Chrome 60.

**Comment by bhavyashah** [comment]
Neither can I reproduce the reported issue on a recent Chrome stable version. The translation is rendered with proper spacing, whether navigated by word or by line. Only 'screensaver' appeared as one word, which is probably expected translation itself, rather than incorrect rendering. All in all, I am unable to replicate this issue as well.

**Comment by ehollig** [comment]
Closing, unless @fernando-jose-silva is still experiencing this issue and can provide more information on exact steps to reproduce the issue

**Comment by fernando-jose-silva** [comment]
Thank you very much, I do not have this problem any more.

 

De: Ethan Holliger [mailto:notifications@github.com] 
Enviada em: quarta-feira, 16 de agosto de 2017 12:57
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [nvaccess/nvda] error when editing text in chrome (#5710)

 

@fernando-jose-silva <https://github.com/fernando-jose-silva> , is this still happening for you? I am not able to replicate using Chrome 60.
