### ISSUE TITLE
Audioducking adds a lot of debugging text to the log

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5711]
When trying to find a traceback in a log and one immediately goes to the log after the error occurs, debugging info for audioducking really takes up a lot of space. Now that the feature is almost stable, can some of the logging comments be merged, or disabled?
Here is a snippet from a random mouse movement error and a freeze in NVDA core. Note that when NVDA+f1 was pressed, I was put just above the freeze text and had to go up to find the end of the attribute error.

  File "NVDAObjects\__init__.pyc", line 829, in event_mouseMove
  File "NVDAObjects\IAccessible\__init__.pyc", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
DEBUG - audioDucking.AudioDucker.enable (10:44:29):
ignoring duplicate enable
DEBUG - audioDucking.AudioDucker.disable (10:44:29):
disabling
DEBUG - audioDucking._unensureDucked (10:44:29):
Queuing _unensureDucked
DEBUG - audioDucking.AudioDucker.disable (10:44:29):
Ignoring duplicate disable
IO - speech.speak (10:44:29):
Speaking [u'section']
DEBUG - audioDucking.AudioDucker.enable (10:44:29):
enabling
DEBUG - audioDucking._ensureDucked (10:44:29):
Increased ref count, _duckingRefCount=10
DEBUG - audioDucking.AudioDucker.enable (10:44:29):
whenWasDucked 743.659999847, deltaMS -743509
DEBUG - audioDucking.AudioDucker.enable (10:44:29):
ignoring duplicate enable
DEBUG - audioDucking._unensureDucked (10:44:29):
Decreased  ref count, _duckingRefCount=9
DEBUG - audioDucking.AudioDucker.disable (10:44:29):
disabling
DEBUG - audioDucking._unensureDucked (10:44:29):
Queuing _unensureDucked
DEBUG - audioDucking.AudioDucker.disable (10:44:29):
Ignoring duplicate disable
IO - speech.speak (10:44:29):
Speaking [u'button']
IO - speech.speak (10:44:29):
Speaking [u'Back']
DEBUG - audioDucking.AudioDucker.enable (10:44:29):
enabling
DEBUG - audioDucking._ensureDucked (10:44:29):
Increased ref count, _duckingRefCount=10
DEBUG - audioDucking.AudioDucker.enable (10:44:29):
whenWasDucked 743.789999962, deltaMS -743639
DEBUG - audioDucking.AudioDucker.enable (10:44:29):
ignoring duplicate enable
DEBUG - audioDucking.AudioDucker.disable (10:44:29):
disabling
DEBUG - audioDucking._unensureDucked (10:44:29):
Queuing _unensureDucked
DEBUG - audioDucking.AudioDucker.enable (10:44:29):
enabling
DEBUG - audioDucking._ensureDucked (10:44:29):
Increased ref count, _duckingRefCount=11
DEBUG - audioDucking.AudioDucker.enable (10:44:29):
whenWasDucked 743.958999872, deltaMS -743808
DEBUG - audioDucking.AudioDucker.enable (10:44:29):
ignoring duplicate enable
DEBUG - audioDucking.AudioDucker.disable (10:44:29):
disabling
DEBUG - audioDucking._unensureDucked (10:44:29):
Queuing _unensureDucked
DEBUG - audioDucking._unensureDucked (10:44:29):
Decreased  ref count, _duckingRefCount=10
DEBUG - audioDucking._unensureDucked (10:44:30):
Decreased  ref count, _duckingRefCount=9
DEBUG - audioDucking._unensureDucked (10:44:30):
Decreased  ref count, _duckingRefCount=8
DEBUG - audioDucking._unensureDucked (10:44:30):
Decreased  ref count, _duckingRefCount=7
DEBUG - audioDucking._unensureDucked (10:44:30):
Decreased  ref count, _duckingRefCount=6
DEBUG - audioDucking._unensureDucked (10:44:30):
Decreased  ref count, _duckingRefCount=5
DEBUG - audioDucking._unensureDucked (10:44:30):
Decreased  ref count, _duckingRefCount=4
DEBUG - audioDucking._unensureDucked (10:44:30):
Decreased  ref count, _duckingRefCount=3
DEBUG - audioDucking.AudioDucker.disable (10:44:30):
Ignoring duplicate disable
DEBUG - audioDucking._unensureDucked (10:44:30):
Decreased  ref count, _duckingRefCount=2
IO - inputCore.InputManager.executeGesture (10:44:30):
Input: kb(laptop):NVDA+f1
DEBUGWARNING - watchdog._watcher (10:44:32):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 191, in <module>
  File "core.pyc", line 382, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 353, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "scriptHandler.pyc", line 144, in _queueScriptCallback
  File "scriptHandler.pyc", line 186, in executeScript
  File "globalCommands.pyc", line 1356, in script_navigatorObject_devInfo
  File "logging\__init__.pyc", line 1165, in info
  File "logHandler.pyc", line 105, in _log
  File "wx\_core.pyc", line 13263, in SetInsertionPointEnd

INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (10:44:33):
Developer info for navigator object:

**Comment by jcsteh** [comment]
There is a lot of potential for race conditions, timing errors, etc. with something like audio ducking. One needs quite a lot of data to figure such things out.

Debug always has the potential to be quite verbose; NVDA is not unique in this respect. If you don't want that kind of detail, you could use input/output. That will still give you i/o and debug warnings like freezes.

That said, @MichaelDCurran, do you feel we need to keep all of this? I'm guessing all of this would still be needed in order to debug obscure issues. If so, I wonder if we should consider putting it behind a debugLog config flag like I did for hwIo.

**Comment by michaelDCurran** [comment]
I'm happy if this was behind a flag I guess.
It certainly all should exist in some capacity for one or two stable 
versions at least.

On 25/01/2016 8:49 AM, James Teh wrote:
>
> There is a lot of potential for race conditions, timing errors, etc. 
> with something like audio ducking. One needs quite a lot of data to 
> figure such things out.
>
> Debug always has the potential to be quite verbose; NVDA is not unique 
> in this respect. If you don't want that kind of detail, you could use 
> input/output. That will still give you i/o and debug warnings like 
> freezes.
>
> That said, @MichaelDCurran <https://github.com/MichaelDCurran>, do you 
> feel we need to keep all of this? I'm guessing all of this would still 
> be needed in order to debug obscure issues. If so, I wonder if we 
> should consider putting it behind a debugLog config flag like I did 
> for hwIo.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5711#issuecomment-174349745>.
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by derekriemer** [comment]
Closing as fixed.

**Comment by derekriemer** [comment]
Closed as fixed. Can't add a keyword (I don't have that permission).

**Comment by jcsteh** [comment]
Done in a8381049.
