### ISSUE TITLE
NVDA does not count accessible columns correctly

### ISSUE THREAD

**Issue by mpreyskurantov** [nvaccess/nvda#5718]
Use the following HTML Table markup to reproduce the issue:

```
<table>
    <thead>
        <tr>
            <th><a href="#">First header</a></th>
            <th role="presentation"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>First cell</td>
            <td role="presentation"></td>
        </tr>
        <tr>
            <td>Second cell</td>
            <td role="presentation"></td>
        </tr>
    </tbody>
</table>
```

NVDA reads this markup in the following manner:

_table with 3 rows and 2 columns
row 1 column 1
First header
link_

The entire column whose cells have the role="presentation" attribute in each row should not be counted.

The expected pronounced state is the following:

_table with 3 rows and 1 column
row 1 column 1
First header
link_

**Comment by jcsteh** [comment]
See my comment on #5717. The same applies.

**Comment by leonardder** [comment]
Closing this in favour of #5717, which has the same underlying cause. I updated the title of that issue to reflect both cases.
