### ISSUE TITLE
NVDA can not read  incoming messages automatically while working with Skype protocol for Miranda IM

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#572]
**Reported by janusz on 2010-02-25 11:43**
Dear core developers of NVDA, 
I would like to valuably please You, if YOu would try to implement new function, which would read incoming messages automatically in Miranda IM while getting chat messages from Skype
protocol for Miranda IM. Here is The direct download link to The latest compiled plugin and also direct link for downloading it's source code. Here is a compressed binarz package with The plugin 

http://dose.0wnz.at/Skype/Skype_protocol.zip

And here is The link for downloading The SkYpe Plugin source code 

http://dose.0wnz.at/Skype/Skype_protocol_src.zip

Please try to think about adding this feature to NVDA.

**Comment by leonardder** [comment]
This is still an issue, and as I think I do have the skills to fix this at some point, feel free to assign this to me.

**Comment by Adriani90** [comment]
@leonardder, @janusz is this still an issue? Skype classic is not further developed and as far as I know Miranda has implemented a skype protocoll in the last version which came out shortly. If this is still an issue, is anyone working on it?

**Comment by Adriani90** [comment]
@leonardder do you think this is something which is likely to be solved in the near future? Or is it not reproducible at all?

**Comment by Adriani90** [comment]
We do not have any updates on this issue since two years and the Miranda client has been updated. I am closing this issue as abandoned but feel free to comment on it if it is still reproducible and we can reopen the discussion. Thanks.
