### ISSUE TITLE
NVDA inaccurately says a folder is collapsed in File Explorer when there are no folders inside it

### ISSUE THREAD

**Issue by btman16** [nvaccess/nvda#5722]
In File Explorer, at least in Windows 10, I use the tree view to navigate to the folder I want, and then press tab to get to the list of files.
Today, I was navigating the tree view, and came to the downloads folder, which it said as being collapsed, leading me to think that there were other folders inside it.
However, when I checked it, and tried to expand it with right arrow it of course did not expand, as there were no other folders in it.
Since the documents folder contained other folders in it, perhaps this could have been confusing NVDA.

Steps to reproduce:
1. Open the "this pc" icon.
2. Use the tree view to navigate through the folders and try to find a folder by using the tree view that doesn't have any other folders inside it, just files.
For me, it said documents collapsed, because there were folders in it. Then when I came to downloads, it also said downloads collapsed, but there were no folders in it. If I press right arrow, then down arrow and up arrow to it, NVDA correctly identifies that this is not either collapsed or expanded, and just says downloads.

Do You know if this can be corrected please? So in other words, it should have said documents collapsed, like it did, but when I down arrow to downloads I was thinking it would say just downloads, unless there are other folders in it, in which case it would then say "Downloads collapsed", respectively.

**Comment by jcsteh** [comment]
This seems to be a weird bug in Windows when navigating to the Downloads folder inside "This PC". Interestingly, if you move to an empty folder elsewhere, it doesn't seem to occur. It also occurs with Narrator, which means this is what Windows is exposing. I don't think there's any way we could work around this; it would need to be fixed by Microsoft.

**Comment by Brian1Gaff** [comment]
This sort of problem also afflicts windows live mail as well, going up and 
down seems to wake it up to say the correct thing.
 I think it can take some parameters from a  previous selection.

Brian

--------------------------------------------------
