### ISSUE TITLE
Chrome app "line": speech reports next / previous character incorrectly

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#5725]
Hi, 
Here is a system caret tracking issue in Chrome application "line".
STR:
1. Open Google Chrome.
2. Download and install line at:
https://chrome.google.com/webstore/detail/line/menkifleemblimdogmoihpfopnplikde?hl=en
3. Login account. (Users need to register E-mail address on mobile.)
4. Choose a friend to chat.
5. Press NVDA+space to switch to focus mode and type text string "NonVisual".
6. Press home and then press Right-Arrow three times:
  expected: speech reports character "V"
  actual: speech reports previous character "n"

notes: 
• In this case, braille display correctly.
• LINE version 1.2.7

**Comment by jcsteh** [comment]
Possibly related to #6424.

**Comment by jcsteh** [comment]
I think this is probably fixed by #7201, which is now in master. @surfer0627, would you be able to test this with the latest master snapshot? Thanks.

**Comment by surfer0627** [comment]
@jcsteh
Yes, it is fixed by 7201.
I'm going to close this.
