### ISSUE TITLE
Unicode character U+200E in the text of the clock

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#5729]
On my Windows 7 system with en-US locale there are Unicode LTR marks in the text of the clock. I made some adjustments to the date and time format, but my guess is that this occurs for the clock in general. Probably also for RTL languages.

Steps to reproduce:
- Press Windows+b to go to the notification area.
- Press left arrow until you reach the clock.
  - Expected: see the date and time in braille.
  - Actual: see the date and time plus Unicode character U+200E (LEFT-TO-RIGHT MARK) prefixed to the date fields.

This character shows up because it is not in the liblouis table en-us-comp8.ctb. It's not likely to be in any other tables either.
Here is the text as copied from NVDA's review mode. Note that these characters are invisible:
`Clock 19:21, ‎Sunday, ‎31-‎01-‎2016`

I haven't encountered these characters anywhere else in Windows' GUI but apparently a similar situation exists in the file properties dialog, albeit with a different character:
https://blogs.msdn.microsoft.com/oldnewthing/20150506-00/?p=44924

Can anyone reproduce this? Is it something that could be addressed in NVDA, at least for the clock, e.g. by means of a simple filter? Or is this more of a liblouis thing?

**Comment by jcsteh** [comment]
Yeah, I've seen these. I guess we could try to filter them out, but the 
question is where. The simplest place is probably to do it specifically 
for these controls in the explorer app module, since that will kill them 
for the review cursor as well.

**Comment by dkager** [comment]
Sounds good. Fixing this in liblouis would require either updates in all tables, which is unrealistic, or to pre-compile some rules, which IMO is ugly.

By the way, I experience #4364 too on Windows 7. But from what I read this is different in later versions. I'm not sure if this Unicode thing is specific to Windows 7, but I guess filtering it out on all versions doesn't hurt.

**Comment by dkager** [comment]
Also confirmed on Windows 10. I still need to look at fixing it, though.

**Comment by dkager** [comment]
So the fix is pretty easy: replace the value by the value with U+2003E stripped. But then upon value changes (i.e. when the clock changes) nothing is announced. Am I right in assuming I should add an overlay class?

Also, the name on Windows 7 is just "Clock", which is redundant since NVDA already announces that. On Windows 10 the name equals the value, which again causes repeated announcements. I'm not sure about XP/Vista/8.1, but maybe the name could be cleared for all of these.

**Comment by jcsteh** [comment]
Yeah, you'll need an overlay class which extends the property. Assigning 
to the value overrides it forever.

Makes sense to clear the name.

**Comment by dkager** [comment]
Fixed it on Windows 7, now I just need to verify it on Windows 10 and maybe XP. PR to follow after that.

Also as a general note, the text that is actually shown on-screen appears to be in `windowText`. This isn't very useful because it doesn't include the date.

**Comment by dkager** [comment]
Ah, Windows XP is not affected by these tweaks because its accRole is ROLE_SYSTEM_CLIENT, whereas on Windows 7 it is ROLE_SYSTEM_CLOCK. The window classname is the same but on XP NVDA manually assigns ROLE_CLOCK. This is done in NVDAObjects.IAccessible.TrayClockWClass, which I could extend, but since we need different behavior on Windows 7 and up I would rather use the Explorer app module as previously suggested.

The difference in behavior is that on XP the object has no value and its name contains the time. So discarding the name would be a bad idea. Again, windowText is consistent across all platforms but does not contain the date, which I guess we want to show if possible even if it's not immediately shown visually.
