### ISSUE TITLE
NVDA Enter key and Numpad enter key fire different event

### ISSUE THREAD

**Issue by hvinh** [nvaccess/nvda#5730]
Hello,

I noticed that pressing the main enter key and the numpad enter key does not have the same behaviour on a button.
The main enter key will fire a click event, while the numpad enter key is firing a key pressed event.
Why is the behaviour not consistent?

Note: JAWS screen reader is firing a click event in both cases.

Thanks & regards

**Comment by jcsteh** [comment]
Same underlying issue as #5385.
