### ISSUE TITLE
Adobe Reader crash while document is open in few seconds

### ISSUE THREAD

**Issue by pnikesh** [nvaccess/nvda#5731]
as soon as I open my PDF file in adobe reader, it get crash in few seconds.

**Comment by jcsteh** [comment]
More details please.
Does this happen with all PDF files or only specific files?
Does it happen if you exit NVDA before opening the PDF? You may need 
sighted assistance to test this.
What version of Adobe Reader?
What version of NVDA?
What version of Windows?
Has this always happened or only recently? If recently, when did it 
start happening and what did you update prior to this occurring?

**Comment by pnikesh** [comment]
Yeah this happens with all PDFs,
I am using Adobe Reader X(10.0.1) in windows 10.


*Nikesh Patel*

**Comment by jcsteh** [comment]
That version of Adobe Reader is years out of date. Please update to 
Adobe Acrobat Reader 15 and test with that.

**Comment by pnikesh** [comment]
Ohk Thanks...


*Nikesh Patel*

**Comment by ehollig** [comment]
@pnikesh are you still having this problem with the latest version of Adobe Reader? It sounds like from https://github.com/nvaccess/nvda/issues/5731#issuecomment-181419661 that this issue has been resolved and can be closed.

**Comment by ehollig** [comment]
Closing, as it sounds like from https://github.com/nvaccess/nvda/issues/5731#issuecomment-181419661 that this issue has been resolved. This issue can be reopened if it has not.
