### ISSUE TITLE
nvda sometime speaks too much when switching windows in a multi-window java app

### ISSUE THREAD

**Issue by rpaquay** [nvaccess/nvda#5732]
This is somewhat difficult to reproduce, but nvda sometimes speaks too much, i.e. speaks the window title + all the context leading to the focused element inside the window, even though it should not speak the window title at all.

This happens in particular with IntelliJ/Android Studio when bringing up the Code Completion list in an editor text window, then closing the Code Completion list after moving the arrow up/down.

A PR is coming with a fix.

**Comment by nvaccessAuto** [comment]
Incubated in 9432f7fadd1c3b69e266a5efd1028d3948da4fc3.
