### ISSUE TITLE
A suggestion about control my pc with NVDA and braille display, no real keyboard.

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#5737]
Hello, regarding using NVDA with braille display, it is very good for me that assigned many nvda keys are mapped to my braille display, I can control my pc without real computer keyboard.
However in my braille display, there is no way to press application key.
Application key is used many times, please add this key to braille display.

Thank you.

**Comment by josephsl** [comment]
Hi, which braille display are you using?

**Comment by khsbory** [comment]
Hello, I'm using hims braille display.
In input gesture settings &gt; braille section, I can't mapping application key to braille display, braille sense u2.
 
Thank you.
 
 
  
김 형 섭	 / Hyongsop Kim
(주)엔비전스 / 대리	

서울시 종로구 가회동 1-29 
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 70 4900 0895   F. +82 2 313 3645   M. +82 10 5359 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark

  
-----Original Message-----

**Comment by Adriani90** [comment]
@leonardder is this not implemented in NVDA now? Actually we can emulate modifier keys to braille displays. Is this also possible for application key?

**Comment by Adriani90** [comment]
I think there was a pull request for including braille specific settings for key assignment.

**Comment by leonardder** [comment]
The request is to add the applications key to the Hims braille display driver, and this mapping is there in the new native driver. The applications key can be invoked by pressing dot1+dot2+dot3+dot4+space, or the f8 key on a braille edge. The ability to add custom emulated system keyboard keys is a different issue. Closing this one.
