### ISSUE TITLE
NVDA not reading aria-label on arroy down key pressed

### ISSUE THREAD

**Issue by syntaxbliss** [nvaccess/nvda#5742]
I have the next markup:

`<button aria-label="LEFT BUTTON">left button</button><input type="text" aria-label="INPUT CONTROL" value="5"><button aria-label="RIGHT BUTTON">right button</button>`

When I'm standing on the left button and then press TAB, NVDA correctly reads the input aria-label, which is:

> INPUT CONTROL edit has autocomplete
> selected 5

But if I'm standing on the left button and then press the arrow down key it reads:

> edit has autocomplete
> 5

Is this correct? Shouldn't it read the same in both cases?

**Comment by jcsteh** [comment]
When you press tab, you're dealing with the focus. When you use the arrow keys, you're reading content in browse mode. Browse mode doesn't render aria-label(ledby) as content for various reasons. See [this blog post](http://blog.jantrid.net/2015/12/woe-aria-surprisingly-but-ridiculously.html) for some info as to why this is all a lot more complicated than it seems.

**Comment by cannona** [comment]
If it helps, this behavior also matches the behavior of other screen readers.

**Comment by ehollig** [comment]
@jcsteh, from https://github.com/nvaccess/nvda/issues/5742#issuecomment-183089793, it sounds like this is intentional. Is there anything else that needs to be done for this issue?

**Comment by jcsteh** [comment]
This will be addressed by #4773.
