### ISSUE TITLE
NVDA speaks "blank" after every press of arrow keys in Google Docs

### ISSUE THREAD

**Issue by mjanusauskas** [nvaccess/nvda#5743]
To reproduce using NVDA and Firefox:
Open a Google Doc and type a line of text.
Use Shift + Arrow Keys to select some characters or words.
Either press Delete or type some new text to remove/replace the selection.
Now following every press of the Arrow Keys to move through the text NVDA speaks "blank" before reading the line or character.
Restoring correct behavior requires either the full browser tab to be refreshed or toggleing braille support on then off in the Accessibility application menu in Google Docs.

**Comment by jcsteh** [comment]
To clarify, you have braille support disabled when this occurs?

**Comment by mjanusauskas** [comment]
Yes that is correct.

**Comment by jcsteh** [comment]
This is a regression in Firefox: [Mozilla bug 1249253](https://bugzilla.mozilla.org/show_bug.cgi?id=1249253).

**Comment by mjanusauskas** [comment]
Thank you for investigating. The Google Docs team agrees that it is a 
bug in the current Mozilla Firefox version.

**Comment by jcsteh** [comment]
Fixed for Firefox 47 and 48. This will hopefully get backported to 46 as well.
