### ISSUE TITLE
unselecting text in browse mode

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#5746]
STR:
1. Open a webpage. Google will work.
2. Move to the line of buttons; google search, etc.
3. Press home.
4. Press shift+end. I hear: Google Search I'm Feeling Lucky selected
5. Press shift+home. That text should be unselected, instead I hear nothing.

**Comment by JamaicanUser** [comment]
I followed all the steps, and while it doesn't announce unselected, when I press Control+C, the text that was selected is copied. Is it truly unselected? Is NVDA at fault?

**Comment by jcsteh** [comment]
In browse mode, we handle selection. So yes, it's NVDA's fault. I don't 
currently know why.
