### ISSUE TITLE
Some notifications are not displayed to braille display.

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#5747]
Hello, I'm Hyongsop Kim in Korea.
In firefox, for example, if I sign in any web page such as gitgub, nvda reads the alert that remember my password or not.
But this alert are not displayed in my braille display.
So if I use nvda with no speech and only braille display, i can't know such alert is apeared.
I think that these kind of alerts should displayed in braille, too.
Please check this issue.

Thank you.

**Comment by dkager** [comment]
Same in IE11, though I think the notification bar is displayed and then suppressed by other content appearing.

**Comment by Adriani90** [comment]
@dkager is this issue still happening?

**Comment by dkager** [comment]
I'm not sure if/how the notification is spoken and whether it is actually sent to the braille display. It never shows up in braille, but I wouldn't know if it is spoken at all and if that is consistent.

**Comment by Adriani90** [comment]
Updates from people who could reproduce this have not been provided since more than 4 years. I am closing as abandoned. If you are still having this issue, please comment considering my previous comment above and we can reopen.
