### ISSUE TITLE
nvda doesn't tell me the cell is blank in excel.

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#5748]
Hello, I'm Hyongsop Kim in Korea.
In notepad, for example, once I move up or down arrow keys, if the line is blank, nvda says 'blank'.
But in excel, even if I move to blank cell section, nvda doesn't tell me 'blank'.
It reads only cell name such as a1 or b1.
I think that nvda should differentiate blank cell and text cell.
Please check this issue.

Thank you.

**Comment by JamaicanUser** [comment]
But if it only says the cell reference, and nothing else, why would it need to say blank? By just hearing the reference, the user should know that it is blank, right?

**Comment by jcsteh** [comment]
Blank and text cells are already differentiated by the fact that cells with text will report the text, whereas cells without text obviously won't. We say blank in Notepad because otherwise, we'd say nothing. In contrast, in Excel, there is something to say; i.e. the cell address.

**Comment by derekriemer** [comment]
Not if they turned off reporting of Cell coordinates.

Sent from my iPhone
Please disregard errors as this is a smaller device.

**Comment by jcsteh** [comment]
Sure, but then it reports "cell".

**Comment by khsbory** [comment]
Thank you for your reply.

But if a user typed ^ or just punctuation in specific cell because of their purposes or by mistakes, they doesn't know which cells has just punctuation as they explore the cells, unless they remember correct cell with has just punctuation.
Because if nvda preferences is set to no punctuation or voice engine that they are using is not tell the punctuation, it will be confusing whether the cell is blank or has punctuation. 
  
김 형 섭	 / Hyongsop Kim
(주)엔비전스 / 대리	

서울시 종로구 가회동 1-29 
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 70 4900 0895   F. +82 2 313 3645   M. +82 10 5359 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark

  
-----Original Message-----

**Comment by JamaicanUser** [comment]
There are several ways to confirm if the cell is truly blank. The Read current line command and the report current navigator object command come to mind at the moment.
