### ISSUE TITLE
Bug report about using braille display within Ckeditor, firefox

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#5754]
Hello, I'm Hyongsop Kim in Korea.
I have a bug report that using nvda with my braille display in ck editor, Firefox.
Let's suppose that I typed for lines, line 2 and 4 is blank.
1 and 3 has text.
From the top I tried to read with my Hims display, I can't go to next line, 2 with braille scroll panning panning key, no work.
So I pressed down arrow key and reached line number 2, and once I press braille scroll key, NVDA eror sound is appeared.
In other words, if next line has text, no problem, but next line is blank, there is a error.
below is some log message regarding this issue.
  File "NVDAObjects\IAccessible__init__.pyc", line 160, in _setCaretOffset
COMError: (-2147024809, '\xb8\xc5\xb0\xb3 \xba\xaf\xbc\xf6\xb0\xa1 \xc6\xb2\xb8\xb3\xb4\xcf\xb4\xd9.', (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (17:12:46):
error executing script: <bound method GlobalCommands.script_braille_scrollForward of <globalCommands.GlobalCommands object at 0x04EF8D30>> with gesture 'rightSideScrollDown'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 186, in executeScript
  File "globalCommands.pyc", line 1731, in script_braille_scrollForward
  File "braille.pyc", line 1532, in scrollForward
  File "braille.pyc", line 1174, in scrollForward
  File "braille.pyc", line 1005, in nextLine
  File "braille.pyc", line 805, in _setCursor
  File "compoundDocuments.pyc", line 106, in updateCaret
  File "textInfos\offsets.pyc", line 491, in updateCaret
  File "NVDAObjects\IAccessible__init__.pyc", line 160, in _setCaretOffset
COMError: (-2147024809, '\xb8\xc5\xb0\xb3 \xba\xaf\xbc\xf6\xb0\xa1 \xc6\xb2\xb8\xb3\xb4\xcf\xb4\xd9.', (None, None, None, 0, None))

**Comment by leonardder** [comment]
Com error -2147024809 translates to 'The parameter is incorrect.'

@khsbory: is this still an issue for you?

**Comment by khsbory** [comment]
Hello, thank you for your email.
Unfortunately, even if I updated NVDA next newest version, the problem is exist.
In CK editor's rich text editor, if there is no blank lines, braille panning button scrolls line smoothely.
However if there is one or more blank lines, even if I press panning button, it is not scrolled to next blank line in Firefox.


If you need more information, please let me know.
hThank you.





김 형 섭	 / Hyongsop Kim
(주)엔비전스 / 웹접근성사업팀 팀장	

서울시 종로구 가회동 1-29 
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 70 4900 0895   F. +82 2 313 3645   M. +82 10 5359 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark





-----Original Message-----

**Comment by derekriemer** [comment]
@leonardder do you have a drupal install to test this on?

**Comment by bhavyashah** [comment]
Thiss is just a friendly reminder for @leonardder to kindly respond to @derekriemer's https://github.com/nvaccess/nvda/issues/5754#issuecomment-319031754.

**Comment by Adriani90** [comment]
@khsbory I guess you still have this issue also with automatic review enabled? cc: @leonardder

**Comment by khsbory** [comment]
Yes, as you said, in focus mode with braile, it doesn’t work yet in CK editor with firefox.
I tested in CK editor version 5 with latest NVDA alpha version.
If you need more information, please let me know.
 
Thank you.
 
김형섭 / Hyongsop Kim
(주)엔비전스 / 웹접근성사업팀 팀장

서울시 종로구 가회동 1-29
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 2 313 9977 F. +82 2 313 3645 M. +82 10 3316 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark

 
-----Original Message-----

**Comment by Adriani90** [comment]
It seems this is the same error like in #12885. Probably the same underlying cause.
cc: @jcsteh since it affects only Firefox.

**Comment by SaschaCowley** [comment]
@khsbory are you still able to reproduce this? Using [this CKEditor 5 demo](https://ckeditor.com/ckeditor-5/demo/feature-rich/) with Firefox 129 and NVDA alpha-32997,3f82ab67 , I am unable to reproduce it.

**Comment by khsbory** [comment]
Thank you for your confirmation. I have also verified that the issue is no longer occurring on the latest browsers and the most recent version of NVDA. As there are currently no problems observed, I will proceed to close this issue. We appreciate your attention to this matter and your help in improving accessibility.
