### ISSUE TITLE
Regarding Seika mini braille support 

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#5755]
Hello, I'm Hyongsop Kim in Korea.
Nvda's braille support list doesn't include seika mini 16cell braille display.
Even if both seiak 40 and 80cell displays are supported, mini is not supported yet.
I hope this device will be included in the future.
Please check this issue.

**Comment by josephsl** [comment]
Hi, are there commands specific to this display? We’d be happy to mention Seika Mini (16) in the user guide if tests show it is working as advertised.

**Comment by khsbory** [comment]
Hi, first of all, Nvda doesn't recognize this braille display.
In other words, even if I try to choose seika, the error message is appeared.
In case of seika mini, there are for scroll keys and two joysticks.
Thank you.
 
 
  
김 형 섭	 / Hyongsop Kim
(주)엔비전스 / 대리	

서울시 종로구 가회동 1-29 
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 70 4900 0895   F. +82 2 313 3645   M. +82 10 5359 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark

  
-----Original Message-----

**Comment by jcsteh** [comment]
In order to support a display, either us or an external developer would need to loan a display for at least a month (at no cost), as well as technical documentation from the manufacturer.

Someone representing Seika did [email the nvda-devel list a few years ago](http://nabble.nvda-project.org/NVDA-dev-regarding-Miniseika-braille-display-td21387.html) saying they were goig to write a driver, but that never seems to have happened.

**Comment by khsbory** [comment]
I found seika mini nvda driver in their
manufacturer site, but the zip archive is damaged.


So I reported this issue and they sent me
correct driver.


If I attach this zip file, how about adding
this to nvda itself so that seika mini users don’t have to download additional
files?


  
  
김 형 섭	 / Hyongsop Kim
(주)엔비전스 / 대리	

서울시 종로구 가회동 1-29 
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 70 4900 0895   F. +82 2 313 3645   M. +82 10 5359 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark

  
-----Original Message-----

**Comment by josephsl** [comment]
Hi, yes, please do attach the zip file so at least I and @jcsteh can look at it (note that we need a note from Seika saying the driver license is GPL, otherwise it cannot be included). Thanks.

**Comment by khsbory** [comment]
Okay, please refer to attached file.  
  
김 형 섭	 / Hyongsop Kim
(주)엔비전스 / 대리	

서울시 종로구 가회동 1-29 
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 70 4900 0895   F. +82 2 313 3645   M. +82 10 5359 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark

  
-----Original Message-----

**Comment by josephsl** [comment]
Hi, the attachment didn't come through.
Switching to Korean:
선배님, GitHub 사용시 이메일로 답장할 경우 파일이 첨부되지 않을 수 있습니다. 혹시 제 개인 이메일(joseph.lee22590@gmail.com)로 첨부해 주실래요?
English: It appears file attachment might be lost if you leave comments via email. Could you send the file to me via my email address?
Thanks (@jcsteh, once I get the attachment, I'll forward it to you).

**Comment by jcsteh** [comment]
You'll need to attach it on the web; you can't attach via an email 
unfortunately.

Note also that we can't just accept the driver. It needs to pass review. 
If it doesn't, someone will need to fix it, and since we don't have one 
of these displays, that may be a problem. Still, we'll take a look.

**Comment by ehollig** [comment]
@josephsl, @jcsteh, were you able to get this driver from @khsbory?

**Comment by Adriani90** [comment]
It seems @khsbory is not available anymore. Is this issue still valid?

**Comment by jcsteh** [comment]
As far as I know, we never received this driver.

**Comment by khsbory** [comment]
Hi, the seika mini driver can be downloaded below.
But the problem is that in latest NVDA alpha version, the driver dooes not work.
Seika mini driver version is 3.0 and updated last year, but it is not compatible with latest NVDA alpha.
So I think that seika mini manufaturer should update the driver to compatible with latest alpha version.
I will report this issue and let you know if I get some clue.
Seika mini nvda driver
Thank you.
 
김형섭 / Hyongsop Kim
(주)엔비전스 / 웹접근성사업팀 팀장

서울시 종로구 가회동 1-29
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 2 313 9977 F. +82 2 313 3645 M. +82 10 3316 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark

 
-----Original Message-----

**Comment by JulienCochuyt** [comment]
(Cross-posting to issue #9478, I guess we could close one of the duplicates)

Accessolutions repackaged the Seika notetakers driver patch for NVDA version 3.2 as an add-on compatible with 2019.1.1
Repository: https://github.com/accessolutions/seikamini-nvda
Packaged release: https://github.com/accessolutions/seikamini-nvda/releases/download/3.2.2019.1.1/seikamini-3.2.2019.1.1.nvda-addon

We are working with Nippon Telesoft and Tsinghua Univ. on the license agreements and code clean-up to help prepare it for candidate integration in NVDA.

**Comment by ruifontes** [comment]
Julien, I have tried to go to bothe links and both report page not found!

Have you make them public?

Best regards,

Rui Fontes
Tiflotecnia, Lda.


Às 10:17 de 23/05/2019, Julien Cochuyt escreveu:

**Comment by JulienCochuyt** [comment]
Sorry @ruifontes, my bad.

> Have you make them public?

It is public now. Please try again, and thank you for your interest.

**Comment by ruifontes** [comment]
Thanks!

Rui Fontes


Às 15:15 de 23/05/2019, Julien Cochuyt escreveu:

**Comment by Qchristensen** [comment]
Minor update - I had contact from a user via email who has the Seika mini display.  The driver they had (which I'm guessing might be the older driver mentioned earlier in this issue) used the User Configuration directory which was removed in NVDA 2019.1.  I've directed them to download the updated driver that @JulienCochuyt posted in https://github.com/nvaccess/nvda/issues/5755#issuecomment-495137028 and I'll comment again if I hear back.

**Comment by moyanming** [comment]
Hi @Qchristensen,
We are the manufacturer of the Seika mini Notetaker Braille display. We have released the Seika Patch for NVDA v3.2, and @Accessolutions(https://github.com/accessolutions/seikamini-nvda) release the "seikamini-3.2.2019.1.1.nvda-addon" base on the v3.2 patch. We have tested the "seikamini-3.2.2019.1.1.nvda-addon" with Seika mini16, mini24, Seika v6, and Seika v7 and all work fine.
We want to add a new item "Seika Notetaker" within the NVDA for good user experience. Please note that the "Seika" which already within the NVDA is only working for the Seika v3/v5 Braille display. Seika v3/v5 is not compatible with the Seika Notetaker because the keys are not compatible.
Please contact me feel free.
Best Regards

**Comment by seanbudd** [comment]
I believe this issue can be closed now by #13191, #13142 and earlier PRs
