### ISSUE TITLE
NVDA key echo slows down at random intervals when typing in outlook 2016

### ISSUE THREAD

**Issue by pranavlal** [nvaccess/nvda#5757]
When I am typing a reply to a message in outlook 2016 or am typing in the message body of a new message, NVDA's character by character key echo tends to slow down. I can keep typing but I get no speech. I must stop typing and can then hear the various characters that I have typed as NVDA echos them. Once I let the string run to completion, I can resume typing at regular speeds and with character by character echo working. I do not have a way to duplicate this. I am using NVDA 2016 rc1. This problem was there in earlier versions of NVDA as well.
OS=windows 10 professional

**Comment by leonardder** [comment]
@pranavlal: Can you still reproduce this?

**Comment by pranavlal** [comment]
No/

**Comment by ehollig** [comment]
The original poster can no longer reproduce this issue. Closing
