### ISSUE TITLE
Punctuation dialog needs a way to search symbols

### ISSUE THREAD

**Issue by ghost** [nvaccess/nvda#5761]
Can the list of symbols in the punctuation/symbol pronunciation settings have a search feature?
Earlier I was trying to find the Ø symbol so I could change it's setting, but I have a very long list of characters and I'm not sure how to type it on the keyboard. If I could copy and paste it and search the list for matches I could probably find it faster?

**Comment by leonardder** [comment]
I agree a filter function for this list could be helpful. May be we should come up with a filterHelper in NVDAHelper that adds filtering functionality to either a list or a tree view. Elements list, input gestures etc. could benefit from this as well. CC @FeerRenrut

**Comment by nvdaes** [comment]
I think this is needed if we want the edition of symbols can be useful in NVDA 2018.4 and later. If the emoji speaking feature is added, the symbols dialog contains more than 2000 symbols, as I see now. In the Insert emoticon dialog used for the Emoticons add-on, whose main author is @Christianlm, a search box is added for 176 symbols.
I think that filtering based on the descriptions could be useful even to copy emojis if the Emojis panel is not available for some languages or Windows versions supported by NVDA.

**Comment by nvdaes** [comment]
Thanks. Let me know in case you want any help. Congrats for your great work.
