### ISSUE TITLE
Additions to list not read in live region

### ISSUE THREAD

**Issue by robfentress** [nvaccess/nvda#5762]
If you have created an unordered list in your page using standard HTML markup, and have made that list a live region, then JAWS with Firefox will not voice any items added to that list, if aria-atomic is false.  It doesn't matter what you set aria-relevant to.  Here is a simplified example:

`<ul aria-live="polite" aria-atomic="false" aria-relevant="additions">`
`<li>item 1</li>`
`<li>item 2</li>`
`</ul>`

Then, if you try to add the following to the list, nothing is voiced:
`<li>item 3</li>`

This is not an issue with anything else I've tested it on, only JAWS/Firefox. 

The best solution I've come up with so far, if you want to preserve the list semantics, is to change the `<ul>` and `<li>` tags to `<div>`s, and set their respective roles with aria to list and listitem.  So that would be:

`<div aria-live="polite" aria-atomic="false" aria-relevant="additions" role="list">`
`<div role="listitem">item 1</div>`
`<div role="listitem">item 2</div>`
`</div>`

This seems to work, but is not ideal.

Here are a couple of codepens for the non-example and example

Non-example using `<ul>` and `<li>` broken in JAWS/FF
[http://codepen.io/robfentress/pen/ZQNpjJ](url)

Example using aria
[http://codepen.io/robfentress/pen/YwbGjg](url)

**Comment by leonardder** [comment]
@robfentress: Are you aware of the fact that NVDA is not JAWS? Is your issue specific to JAWS or NVDA?

**Comment by robfentress** [comment]
Yes, I'm aware of that.  I posted this so long ago, I'm not sure what was in my head at the time.  Looks like I maybe accidentally posted to NVDA, instead of sending something to JAWS folks.  Sorry.

**Comment by leonardder** [comment]
@robfentress: Thanks for the clarification. Closing as invalid.
