### ISSUE TITLE
wrong tooltips are being read in the input gestures dialog

### ISSUE THREAD

**Issue by fatmamehanna** [nvaccess/nvda#5769]
hi all,
there is a problem occurs when i want to change/remove/add a shortcut key for a script. NVDA reports wrong tool tips when i select a shortcut key to be modified.
steps to reproduce:
1 check the tooltip checkBox.
2 open nvda menu/preferences/nvda input gestures dialog.
3 select configurations category.
4 go down till "shows the nvda configuration profiles item for instance.
results:
NVDA says "shows the nvda braille settings dialog" as a tool tip then says the actual phrase which "shows the nvda configuration profiles".
when i move up then move down again, nvda reports the right phrase. or you can know the right phrase for the item by pressing nvda+tab.
note that this problem doesn't occure when i uncheck the tool tip checkBox.
here is an input/output log attached.

[wrongToolTips.txt](https://github.com/nvaccess/nvda/files/140620/wrongToolTips.txt)

**Comment by jcsteh** [comment]
This depends on where your mouse was located. Tool tips are often activated by hovering the mouse. Of course, as the screen scrolls, even though your mouse position doesn't change, the item over which it is hovering does. This is is just the way tool tips for these controls work.

**Comment by Brian1Gaff** [comment]
Wrong tooltips occur in many places in Windows and always have. Its not nvda 
its windows most of the time!
 Brian

--------------------------------------------------
