### ISSUE TITLE
Menus in Visual Studio are read as checkboxes and no indication of submenus

### ISSUE THREAD

**Issue by AArnott** [nvaccess/nvda#5773]
When using the NVDA screen reader, Visual Studio 2015 menus are read as if they were checkboxes, and submenus are not called out. 
We see the desired behavior when using JAWS and Narrator, so it appears to be an NVDA issue.

**Comment by josephsl** [comment]
Hi, can you send us developer info for the menu item? To do this, focus to a menu item, press NVDA+F1, then copy and paste the developer info. Thanks.

**Comment by Neurrone** [comment]
This is the log for a menu item that is misidentified as a checkbox.

INFO - core.main (22:42:31):
NVDA initialized
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (22:42:56):
Developer info for navigator object:
name: u'Close'
role: ROLE_MENUITEM
states: STATE_FOCUSABLE, STATE_READONLY, STATE_FOCUSED, STATE_CHECKABLE
isFocusable: True
hasFocus: 1
Python object: <NVDAObjects.UIA.UIA object at 0x0481DF30>
Python class mro: (<class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (3, 99, 313, 22)
value: None
appModule: <'devenv' (appName u'devenv', process ID 3792) at address 47c24d0>
appModule.productName: u'Microsoft\xae Visual Studio\xae 2015'
appModule.productVersion: u'14.0.24720.0'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 592352
windowClassName: u'HwndWrapper[DefaultDomain;;4313f831-feda-4076-b3aa-61cfe5a8403f]'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 3744
windowText: u'Start Page - Microsoft Visual Studio'
displayText: u''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x5e6c858 at 47b0e90>
UIA automationID: 
UIA frameworkID: WPF
UIA runtimeID: (7, 3792, 49541661)
UIA providerDescription: [pid:3792,hwnd:0x0 Main(parent link):Unidentified Provider (managed:MS.Internal.Automation.ElementProxy, PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)]
UIA className: MenuItem

**Comment by AArnott** [comment]
Thanks for that, @Neurrone. Sorry I lost track of this.

**Comment by derekriemer** [comment]
Wo. I've never seen a MRO with no classes in it.


On 5/1/2016 8:45 AM, Neurrone wrote:
>
> This is the log for a menu item that is misidentified as a checkbox.
>
> INFO - core.main (22:42:31):
> NVDA initialized
> INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo 
> (22:42:56):
> Developer info for navigator object:
> name: u'Close'
> role: ROLE_MENUITEM
> states: STATE_FOCUSABLE, STATE_READONLY, STATE_FOCUSED, STATE_CHECKABLE
> isFocusable: True
> hasFocus: 1
> Python object:
> Python class mro: (, , , , , )
> description: u''
> location: (3, 99, 313, 22)
> value: None
> appModule: <'devenv' (appName u'devenv', process ID 3792) at address 
> 47c24d0>
> appModule.productName: u'Microsoft\xae Visual Studio\xae 2015'
> appModule.productVersion: u'14.0.24720.0'
> TextInfo:
> windowHandle: 592352
> windowClassName: 
> u'HwndWrapper[DefaultDomain;;4313f831-feda-4076-b3aa-61cfe5a8403f]'
> windowControlID: 0
> windowStyle: 399441920
> windowThreadID: 3744
> windowText: u'Start Page - Microsoft Visual Studio'
> displayText: u''
> UIAElement:
> UIA automationID:
> UIA frameworkID: WPF
> UIA runtimeID: (7, 3792, 49541661)
> UIA providerDescription: [pid:3792,hwnd:0x0 Main(parent 
> link):Unidentified Provider 
> (managed:MS.Internal.Automation.ElementProxy, PresentationCore, 
> Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)]
> UIA className: MenuItem
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5773#issuecomment-216046020>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by Adriani90** [comment]
@AArnott, @Neurrone is this issue still reproducible?

**Comment by AArnott** [comment]
No. We made a fix in VS 2017 for this on our side. Thanks for checking.
