### ISSUE TITLE
Handy Tech Basic 40: Wrong label for braille display keys

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#5774]
Hi,
A user of Handy Tech Basic 40 reports the following:
NVDA appears to give wrong key information for braille keys. Instead of saying 1 through 6, it says 2 through 7. Window-Eyes reports correct key labels.

To me, this sounds like a driver issue (may need to confirm with Handy Tech). Can others using this display confirm this in 2015.4 and 2016.1? Thanks.

**Comment by josephsl** [comment]
Hi,
A Handy Tech representative sent the following message to the users list:

Hello list,
this is not strictly a bug, although it may not be intuitive.
Background: Long ago we decided to internally number our Braille function keys from left to right, starting with 1. So for an eight dots Braille input pattern, key 1 would correspond to dot 7, key 2 to dot 3, key 3 to dot 2 and so on.
Basic Braille has exactly six keys, and we wanted them to correspond to Braille dots 1 to 6 in case someone would decide to perform Braille input with them. Since key 1 corresponds to dot 7, as listed above, we decided to minimize changes to existing code by starting at key 2, which corresponds to dot 3.
So, rest assured your units are doing what they're designed to do. But in case this causes too much confusion we can refactor it so those keys are actually counted 1 to 6
Felix Grützmacher

JL: I think it should be refactored (@jcsteh and Davy, any thoughts, as you are the resident braille support experts?).

**Comment by bramd** [comment]
From the driver perspective, I think it's good to not renumber the keys. If we ever get to supporting braille input through the Handy Tech driver, we can handle dots 1-6 the same for all devices without having to write exceptions for the BasicBraille. That being said, we need to make sure all basic braille commands can be accessed using this 6 keys, as also indicated in #5806 this is not the case now.

**Comment by leonardder** [comment]
CC @FelixGruetzmacher

**Comment by leonardder** [comment]
@bramd: What do you think of this in the perspective of #7458?

**Comment by bramd** [comment]
@leonardder I kept these key names, so most gestures for all other models also make sense on the BasicBraille without specifying them explicitly. We could change that, but we would need to redefine all gestures for BasicBraille specifically and it could break custom gestures defined by users of the BasicBraille.

**Comment by leonardder** [comment]
Your last point makes perfect sense. I think we hsould close this as per that reason, as well as because @FelixGruetzmacher pointed out Handy Tech doesn't concider this to be a bug.
