### ISSUE TITLE
In MS word, allow for beeping or other functionality for announcement of autocorrect.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5778]
If I type the word messsaging (3 s in that), and then press space, word autocorrects that to messaging. Does MS word expose the event that caused the word to change? If so, I propose either saying something fast (it would have to be one syllable or something, or beep to inform the user that a change in the document occurred in the word they just pressed space on.

**Comment by PratikP1** [comment]
Microsoft provides an add-in that will enable various sounds for events such as the one you described. It works with all versions of Office. Use the following link to download and install the add-in. Sounds will need to be enabled from Word options after the add-in is installed.

https://www.microsoft.com/en-us/download/details.aspx?id=7015

**Comment by ehollig** [comment]
@derekriemer, given the solution provided by @PratikP1 in https://github.com/nvaccess/nvda/issues/5778#issuecomment-206325150, is this something that you would still like to see added to NVDA or should this issue be closed. CC @feerrenrut

**Comment by fernando-jose-silva** [comment]
I have a suggestion, I do not know if it is feasible.
Could nvda provide a beep to inform you that you hear a change like this called a text correction, and nvda could also provide a shortcut key or window where you would hear a list of changes made by word corrections.
So we would receive a warning that there was a word correction through the beep, and if I did not want to interrupt my typing, I wanted to know what changes the word did in the text would be possible.

**Comment by derekriemer** [comment]
yeah, I think this solution works. Having something like this in other scenarios would be nice, but impractical.
