### ISSUE TITLE
Suggestion to add some options within menus.

### ISSUE THREAD

**Issue by levilibegas** [nvaccess/nvda#5787]
Hi! I would like to make a suggestion concerning menus in vda.
There are some options within nvda whose are shown in dialogues when they are needed. However, these options are not shown within the menus, where they could be accessed and stored properly at ini file.
I can think rightaway of two examples: the first, when try to search for text nvda+ctrl+f it will tell me wether I would like to search caseSensitivity or not. The second one, when trying to exit nvda with nvda+q, it will let me choose wether I would like to exit nvda, start nvda with add-ons disabled or restart nvda with add-ons enabled. These are only two examples that I can recall, of options that could be integrated within the nvda proper menu. ther could be more that I am not aware of...
I wonder aswell if it would be possible to add a search menu option, so that one would not need to remember where within the menu, could find an option, speech, mouse, keyboard, and so no, as it is in other platforms as Windows 7 and later or on mac menus. Thanks for all, regards.

**Comment by jcsteh** [comment]
When you say menus, I assume you don't mean the menus directly, but rather, the preferences dialogs? It doesn't make sense to just have most settings as menu items.

Regarding the Find dialog, an option like this doesn't really fit well into preferences. Also, it's something you generally need to change only when you're actually doing a search. I don't follow why having this as a setting would be useful.

Similarly, having an option to specify whether you restart with add-ons disabled would mean you always restart with add-ons disabled when you press NVDA+q. Or if you mean it should be a separate menu item, that's more or less the same as just opening the Exit dialog and selecting from the combo box, except that it clutters up the menus.

Please explain exactly how you think this would work and provide an example of why someone might use it. Thanks.

**Comment by levilibegas** [comment]
Thanks for your answer.
I have some questions and I am not sure how to post them, within separates tipics or if these would be fine, as they are related in somehow.
Yes, you're right, when I say menus, I ment just preferences. I think that if there is an option within a dialog, it would be preferable to have the chance to choose within the program on a regular bases, rather having to invoque a dialog specific. If this option is within preferences, it is easier to look for and eventually to change. When there is a preference setting in General, to choose wether NVDA should start at log of windows, similarly it would be there to have the option to determine wether addons should be allowed or not, just to check if they could interfer with nvda itself. I am aware this same result could be accomplished while exiting from nvda, however, if there was someone that did not knosw that, it would be easier to look for with in general settings.

Similarly, while trying to search for text, this option could be eassily found for someone that simply press control+plus+f and does not know that has the chance to look for the button sensitivity to capitals. If someone just hit enter in that event, he would not be aware of that option. However, if that option was within preferences, everyone would know that there is no need to look for a specific dialog to have it changed, rather could just look for it in the preferences menu...

Similarly, I wonder if there would be of interest to have a possibility to implement within preferences a search button within a combowbox, so that one could search for an option without having to look for it under, say, general, keyboard, mouse, and so on. Something similar is stablished in MAC Voice Over Screen Software and in Windows from seven upwards.
I am not familiar with github new approach of making tickets. I wanted to know, of some could pleasse help me, how it is possible to state when creating a new one, in which milestone, version, program, or other label should be assigned. Is there a way to do it?
Thanks for all and thanks for this great program...
Regards.

**Comment by jcsteh** [comment]
Restarting with add-ons disabled is intended to be a temporary change only, not something that should be saved. It is akin to Windows safe mode; note that Windows doesn't provide a permanent option for this, as it wouldn't make sense to do so. It is noted in the User Guide, but mostly, users will be isntructed to do this by developers or those providing support. Note that #3090 covers explicit disabling of specific add-ons.

Regarding the Find dialog, we would hope that users don't simply dismiss a dialog the first time without looking at any of the controls. It is very common for find dialogs in all kinds of applications to contain options like this and for them not to be present as configuration options.

Searching for settings is covered by #872.

You can't set milestones or labels. Only developers should and can do this.
