### ISSUE TITLE
replace 'report balloons' option' with 'report balloons and toast/other notifications'

### ISSUE THREAD

**Issue by JamaicanUser** [nvaccess/nvda#5789]
To my knowledge, help balloons are not used in Windows 8 and later. So, it would be confusing, especially to a new user of Windows, to have this option on in that instance on Windows 8 and later. However, this results in the toasts not being read.  For that, I recommend a change of the option name to reflect this variation.

**Comment by josephsl** [comment]
H, I agree (quite trivial to implement, I’d say a new dev should do it).

**Comment by jcsteh** [comment]
I think we should possibly just name it "Report notifications" or similar, which covers both. The config option should not be renamed internally, though, so as to avoid breaking backwards compat.

**Comment by fisher729** [comment]
Hi.

Any updates on this ticket. It might be easy to fix, but it hasn't been looked at as yet...
