### ISSUE TITLE
NVDA ducks audio on all audio devices

### ISSUE THREAD

**Issue by ondrosik** [nvaccess/nvda#5790]
When audio ducking is enabled, NVDA ducks audio in all connected soundcards. I think, that it would be better to duck audio only for soundcard which is set as default in NVDA. However, it seems, that it is windows general problem because narrator does it too. Would it be possible to avoid this in NVDA?

**Comment by jcsteh** [comment]
I'm afraid not. That's how Windows ducking works and there's no way for us to specify.
