### ISSUE TITLE
Developer guide: initOverlayClass not mentioned.

### ISSUE THREAD

**Issue by grzezlo** [nvaccess/nvda#5792]
It'd be great if the initOverlayClass method be mentioned in the section about subclassing NVDAObject.
Currently it isn't, and i spend a long time trying to figure out why the **init** method of my IAccessible subclass doesn't get called.

**Comment by derekriemer** [comment]
I totally agree here. If you guys want I could do this in a pr. 

Sent from my heavily encrypted iPhone.
Please disregard errors as this is a smaller device.

**Comment by josephsl** [comment]
Hi, I hope I covered this in the add-on development guide (if I haven’t, I’ll add your bits to the add-on guide). Thanks.

**Comment by derekriemer** [comment]
OK. Also I play promotion campaign for the NBA at Aune died because finding it is really hard.

Sent from my heavily encrypted iPhone.
Please disregard errors as this is a smaller device.

**Comment by ehollig** [comment]
@josephsl, is this taken care of in the add-on development guide and can this issue be closed?

**Comment by josephsl** [comment]
Hi, yes, an example was briefly given for this in the latest add-on guide. Thanks.

**Comment by ehollig** [comment]
Thank you @josephsl, closing because of https://github.com/nvaccess/nvda/issues/5792#issuecomment-323494341

**Comment by derekriemer** [comment]
I hope you consider merging that into the official dev guide. It's an important one.
