### ISSUE TITLE
Windows 10 Build 14279: "Invalid entry" announced when encountering various controls

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#5794]
Hi,

For those using Windows 10 Insider Preview build 14279: When you encounter objects such as toasts, Action Center items, Windows Feedback list and others, 'invalid entry" is announced.

STR (one scenario):

1. Once you receive a toast notification in Build 14279 (fast ring), press Windows+A to open Action Center.
2. Navigate through Action Center items.

Expected: NVDA announces items only.
Actual: NVDA announces "invalid entry" state.
Reproducible: Yes.
Feedback sent: yes.

Setup:

* OS: Windows 10 Insider Preview 14279
* NVDA version: next.13251

Solution: Because there are apps where 'invalid entry" must be kept, it is crucial that we take care of others in order to prevent suppressing of "invalid entry" for controls where this is desired (hopefully a fix from Microsoft would be better).

Thanks.

**Comment by jcsteh** [comment]
@MichaelDCurran, I vaguely recall nonsense like this when we were 
working on Edge last year. Is this potentially our issue or is it 
definitely Microsoft? If the latter, I think we should just get this 
reported ASAP rather than hacking around it.

**Comment by PratikP1** [comment]
Currently Microsoft has this filed as a bug but on NVDA end and not MS. They ask whether the same build of NVDA encountered this problem pre 14279. It appears that they will look at it closely if it is the case.

**Comment by josephsl** [comment]
Hi, this wasn’t the case in 14271. Thanks.

**Comment by PratikP1** [comment]
Was it the same build of NVDA?

**Comment by josephsl** [comment]
Hi, yes, same build of NVDA. Thanks.

**Comment by PratikP1** [comment]
Just reported that. Thank you for confirming. I’m on the slow ring.

**Comment by jcsteh** [comment]
Just filed a bug with Microsoft providing technical detail about why this is occurring. It's definitely a Windows (specifically, XAML) bug.

**Comment by josephsl** [comment]
Hi,

Update: Fast ring build 14361 fixes this (we'll see if it holds true for next build/slow ring version, and if so, I'll close the ticket until it happens again).

Thanks.

**Comment by jcsteh** [comment]
Microsoft confirmed this was fixed, so closing.

For reference, this was Windows bug 6889554.
