### ISSUE TITLE
th with colspan is read mutiple times on Chrome

### ISSUE THREAD

**Issue by benatkinson** [nvaccess/nvda#5798]
The th contents are read n times where n is the value of the colspan attribute.

e.g.
`<th scope="rowgroup" colspan="8">cell text</th>`
cell text is read 8 times.

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

This is only happening in Chrome, not Firefox nor IE11.

**Comment by jcsteh** [comment]
This is a bug in Chrome. I'll investigate and file a bug report soon.

**Comment by benatkinson** [comment]
Thanks James, I thought it might be. Could you please paste a link to the bug report here? Thanks again.

**Comment by jcsteh** [comment]
Looking at this further, this only occurs if you have scope="rowgroup". Can you perhaps give a more complete example that has a rowgroup with which this header is associated? I don't quite follow why you'd have a scope="rowgroup" that also has a colspan.

**Comment by jcsteh** [comment]
Looking at this further, this only seems to occur if you have scope="rowgroup". Can you perhaps give a more complete example that has a rowgroup with which this header is associated? I'm trying to understand the use case for a scope="rowgroup" that also has a colspan.

**Comment by benatkinson** [comment]
The table has multiple TBODY elements. The first row of TH elements applies to the whole table but each subsequent row of TH elements only applies to it's particular TBODY, hence the colspan and scope="rowgroup". I have attached a sample html document.

[repeating-TH-with-colspan.html.txt](https://github.com/nvaccess/nvda/files/173782/repeating-TH-with-colspan.html.txt)

**Comment by jcsteh** [comment]
Filed [Chromium issue 595233](https://bugs.chromium.org/p/chromium/issues/detail?id=595233).

**Comment by ehollig** [comment]
It appears this issue was fixed with Chrome on November 7. Closing
