### ISSUE TITLE
MSWord, problem navigating by sentence

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#5805]
Open a Word document and move by sentence using alt+downArrow or alt+upArrow. All works fine.
Then switch to browse mode using NVDA+space and switch back to normal mode.
You'll notice that now, alt+downArrow or alt+upArrow don't work anymore.
Tested with NVDA 2016.1 with all addons disabled.

**Comment by leonardder** [comment]
I can reproduce this with Word 2016.

CC @MichaelDCurran

**Comment by jcsteh** [comment]
Probably something to do with the collapseOrExpandControl script used to support alt+up/down for combo boxes in browse mode. We'd need to somehow make binding of these optional for browse mode document subclasses.

**Comment by jcsteh** [comment]
P3 because there's a workaround (switch to focus mode), but it's certainly tedious.

**Comment by Adriani90** [comment]
cc: @mltony

**Comment by Adriani90** [comment]
In case this issue is meant to occur in browse mode, this is a duplicate of #5463. Closing as duplicate. Please correct me if I missunderstood this issue and we can reopen. Thanks.
