### ISSUE TITLE
Microsoft Edge: notification bar items are not announced

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#5807]
Hi,

A variation on #2343:

Notification bar items, such as status of a download are not announced in Edge.

STR:
1. Go to a site where you can download files (such as NVDA community add-ons website).
2. Click a link to download a file.

Expected: NVDA announces notification bar items.
Actual: No announcement.
Reproducible: yes.

Setup:
- OS: Windows 10.
- NVDA version: Next.13265

Technical: A variation on #2343: the algorithm is quite simple but I'm wondering where to place this code.

Algorithm:
1. Adopt #2343 fix (UIA version will be required).
2. Allow UIA handler to let NVDA handle show events from specific controls (if this code exists, simply adding the relevant automation ID's would work).
3. Just like IE notification classes, add Edge versions of these classes and tell NvDA to fake an alert event (reading the child items in the process).

Things to discuss:
- Where should this new code live? I'm leaning towards UIA objects collection.
- Is this specific to Edge? If so, perhaps an app module would be better.

Thanks.

**Comment by jcsteh** [comment]
Does this work with Narrator?

There's no "show" event in UIA. I'm actually not sure what event they 
could be firing. It might be worth testing this with AccEvent or similar.

**Comment by josephsl** [comment]
Hi, yes, Narrator does read notification bar items when I press ENTER to download a file. Thanks.

**Comment by jcsteh** [comment]
Does it say "alert" by any chance? I wonder if they're using the system 
alert event.

**Comment by josephsl** [comment]
Hi, when Narrator announces this, it just says the item names (NotificationBar toolbar children) and doesn’t say “alert” or doesn’t give a similar indication.

**Comment by josephsl** [comment]
Hi,

Three years later:

I'm going to close this, as this is resolved.

Technical: live regions and UIA notification event is used for notification bar text announcement.

Thanks.
