### ISSUE TITLE
Move mouse to current navigator object: the position is incorrect

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#5809]
This case is happen in a internal system.
There is a edit read-only clickable field.
When user press NVDA+numpadDivide to move mouse to current navigator object, the position is incorrect(pixel value=243,580).
By pressing numpadDivide, It won't open a calender.

In NVDA2012.2, the position is right (value=245,628).
By pressing numpadDivide, it will open a calender.

browser: Internet Explorer 8
NVDA: 2016.1
system: Windows7

**Comment by jcsteh** [comment]
Do you have a high DPI screen? If you're not sure, you can check in 
Display settings in Control Panel.

**Comment by surfer0627** [comment]
Yes, I have a high DPI screen.

display resolution: 1920,1080

**Comment by derekriemer** [comment]
Also, do you have focus highlight installed?

On 3/14/2016 2:44 PM, surfer0627 wrote:
>
> Yes, I have a high DPI screen.
>
> display resolution: 1920,1080
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5809#issuecomment-196514244>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by surfer0627** [comment]
@derekriemer:
I do not install add-on focus highlight.

**Comment by surfer0627** [comment]
I do not install add-on focus highlight.

**Comment by Adriani90** [comment]
@surfer0627 are you still having this issue in last NVDA?

**Comment by Adriani90** [comment]
We do not have any further updates on this issue since more than three years. I am closing this as abandoned, given also the fact that solving this in internet explorer would be very unlikely.
