### ISSUE TITLE
Support sub-documents in Chrome

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#5818]
In Chrome, NVDA doesn't handle, for example, a document inside a dialog inside another document. This requires a change to NVDA, but I also think it's going to need a change to accChild in Chrome.

**Comment by derekriemer** [comment]
For an example of this, see the login dialog on twitter where pressing 
nvda+space doesn't put you out of focus mode in the dialog I think.

On 3/16/2016 7:56 PM, James Teh wrote:
>
> In Chrome, NVDA doesn't handle, for example, a document inside a 
> dialog inside another document. This requires a change to NVDA, but I 
> also think it's going to need a change to accChild in Chrome.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5818>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by derekriemer** [comment]
Ignore that last comment. I forgot to look at who filed the issue and assumed that example would be needed (when it probably didn't need to be given).

Sent from my heavily encrypted iPhone.
Please disregard errors as this is a smaller device.

**Comment by jcsteh** [comment]
That might actually be a different issue anyway. I'll look into it and 
file a separate issue if needed.

**Comment by jcsteh** [comment]
This does require a fix in Chrome. Filed [Chromium issue 595959](https://bugs.chromium.org/p/chromium/issues/detail?id=595959).

**Comment by nvaccessAuto** [comment]
Incubated in 314591c013c43be96fd6bd6668af0e033994cbe4.

**Comment by jcsteh** [comment]
> This does require a fix in Chrome. Filed [Chromium issue 595959](https://bugs.chromium.org/p/chromium/issues/detail?id=595959).

Now fixed.
