### ISSUE TITLE
Wrong list items count for list which consist of divs

### ISSUE THREAD

**Issue by ikuznalex** [nvaccess/nvda#5819]
NVDA announces wrong number of list items when the list consist of divs with role=listitem and other divs without this role.

The issue reproducible in case when the div container has role list item and multiple divs inside it with and without listitem role. NVDA counts them all, not only those which marked with role listitem.

Please, take a look to the following example of lists, where the issue fully reproducible.
http://codepen.io/ikuznalex/pen/qZRjNL?editors=1000

**Comment by dkager** [comment]
All of them are reproducible in IE11.

**Comment by cannona** [comment]
Here is yet another example of how this fails:

http://jsbin.com/lubamomoyu/edit?html,output

**Comment by leonardder** [comment]
Is this also reproducible in other browsers?

**Comment by Adriani90** [comment]
Yes I can also reproduce it in Firefox 65.0.1 and chrome 71. cc: @jcsteh

**Comment by seanbudd** [comment]
Closing in favour of the newer #16905
