### ISSUE TITLE
browseMode.py has no translator comment on line 50

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5822]
Pardon me if I am overstepping what types of issues I raise here, feel free to tell me to shut up if I shouldn't raise issues like this in the future.
In browseMode.py line 50, there is the string ui.message(_("focus mode"))
is there a reason this doesn't have a translator's comment?

**Comment by jcsteh** [comment]
Totally valid issue, though for trivial stuff like this, feel free to just submit a pull request with a fix if you can.

It should have a translators comment, yes. It doesn't because that string (moved from another file) pre-dates our requirement for everything to have translators comments.

**Comment by josephsl** [comment]
Hi, and when you do submit the pull request, please reference ticket 1410 also. Thanks.

**Comment by ehollig** [comment]
@derekriemer were you going to submit a PR for this?

**Comment by derekriemer** [comment]
some day
