### ISSUE TITLE
Snapshots Page: Show Size of File

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5824]
I realise that in reality this may just be a personal preference, but since the move to AppVeyor I've noticed that the size of a downloadable snapshot is no longer displayed. Is this something that could easily be re-introduced?

**Comment by Brian1Gaff** [comment]
Eh?

 In  most cases this is a function of the browser. I hear it from firefox 
ok.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by elliott94** [comment]
It is, yes - I'm able to see the size of the file if I initiate a download of the file. However, the size in KB used to be displayed directly within the page itself.

**Comment by Brian1Gaff** [comment]
I'm not sure I recall that in fact. Was this a tool tip perhaps when on the 
link?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by jcsteh** [comment]
This thread is getting overly verbose. :)

Yes, the size used to be provided in parentheses next to the download 
link. It might be possible to do this again, but it's not trivial and 
IMO doesn't justify the work required at this stage. Note that the size 
rarely changes much. You also wouldn't get it for automatic updates or 
official releases, which I think lowers the priority even further.

**Comment by Adriani90** [comment]
Actually you can see the size in the download window of your browser. Closing as won't fix. If you don't agree, please comment with arguments and we can reopen it.
