### ISSUE TITLE
Internal focus handling seems quirky

### ISSUE THREAD

**Issue by jmuheim** [nvaccess/nvda#5831]
I'm experimenting with hiding parts of a page using `aria-hidden="true"` and `tabindex="-1"` upon a user action (clicking a button).

I have set up the following codepen to show a behaviour of NVDA that seems quirky. When you click the button and press down arrow, I would expect the cursor to be on "This is readable after the button is pressed" (the first accessible item), but it's on the link below this item.
- To test with screenreader: http://s.codepen.io/jmuheim/debug/MymBXm
- To inspect code: http://s.codepen.io/jmuheim/pen/MymBXm

So here's my question: how does NVDA handle focus internally? Is it confused when elements are set to `aria-hidden="true"`? How can I prevent this problem?

**Comment by leonardder** [comment]
@jmuheim: Could you still reproduce this? If so, please provide the web page as an attachment to this ticket.

**Comment by Adriani90** [comment]
I saw this issue on multiple web pages where in browse mode the cursor was jumping aroung skipping one or more elements. @jmuheim could you please provide us with a page to test this issue? You can get more info on how the focus is handled in virtual documents by reading pull request #9114.

**Comment by Adriani90** [comment]
Ok I could test this issue by activating the second link in the description. I can still reproduce it. cc: @leonardder

**Comment by Adriani90** [comment]
Closing as fixed by #11190.
