### ISSUE TITLE
NVDA crashing while replying to messages in outlook 2016

### ISSUE THREAD

**Issue by pranavlal** [nvaccess/nvda#5835]
NVDA crashes at random intervals when I reply to an outlook message. I lose speech and have to hit ctrl+alt+delete to reach the lock screen from where I restart my computer. I am attaching a crash log with this message. 
nvda version =2016.1
windows version = Microsoft Windows [Version 10.0.10586]
64 bit 
outlook version:
 Microsoft® Outlook® 2016 MSO (16.0.6528.1017) 32-bit 

[nvda-old_log.txt](https://github.com/nvaccess/nvda/files/190704/nvda-old_log.txt)

**Comment by jcsteh** [comment]
Please provide a log at level input/output, as I can't actually see any freeze or crash here, so will need more info. See [this article for details](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps).

Also, when exactly does the freeze occur: when hitting control+r, while typing your reply or something else?

**Comment by pranavlal** [comment]
The crash occurs a few seconds after I hit ctrl+r. I am unable to duplicate this so it is a tad difficult to provide logs. I will try.

**Comment by PratikP1** [comment]
I'm wondering if this is related to the excessive freezing and high processor usage I have observed when replying to messages in Outlook 2016. I have verified that the problem occurs with JAWS and Window-Eyes as well. Microsoft has forwarded the issue to the Office team. I'm happy to pass along any other details if anyone has them.

**Comment by pranavlal** [comment]
I am attaching some logs.
[Uploading nvda_outlook_log.txt…]()

**Comment by pranavlal** [comment]
I have upgraded to nvda 2016.3 and the problem persists. The problem can occur either while replying to a message and sometimes while composing a message. I am repltying and composing messages in plain text format. I am attaching a fresh log.
[nvda_outlook01.txt](https://github.com/nvaccess/nvda/files/459641/nvda_outlook01.txt)

**Comment by ehollig** [comment]
As there has been many updates to Outlook since 2016, can anyone who uses Outlook pretty consistently confirm that this still exists?

**Comment by Brian1Gaff** [comment]
Might be worth running it past those on the user list as well. I do not use 
this version of Outlook, but I was under the impression that recent updates 
to Office and nvda had finally fixed it.
Like I say, not a user myself.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by PratikP1** [comment]
I have not seen this issue in quite a long time. Outlook does not crash when replying to messages.

**Comment by ehollig** [comment]
I am going to close this issue as https://github.com/nvaccess/nvda/issues/5835#issuecomment-429312662 states it is not happening anymore. If this comes back up as an issue, we can reopen this issue.

**Comment by pranavlal** [comment]
Hi,

I no longer have this problem. NVDA is not crashing when replying to messages in Microsoft Outlook 2016.

Thanks for following up.

-----Original Message-----
