### ISSUE TITLE
NSIS: Upgrade to address DLL Hijacking

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5839]
I'm aware that the Launcher currently uses NSIS as the backend, and from taking a look at the changelog it appears that several important changes were made recently to address the issue of DLL hijacking upon loading a new installer. Would this also apply to NVDA, and if so I imagine it's just a case of updating the build of NSIS that is used to generate the package?

**Comment by jcsteh** [comment]
Some of this doesn't apply, as our NSIS launcher isn't launched with elevated privileges. However, I think some of the issues could apply, so I think it's worth upgrading.

**Comment by nvaccessAuto** [comment]
Incubated in 937505f37bf03c8a931a899dd2aff91dd26fdc3d.
