### ISSUE TITLE
Request to alphabetize imports

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5843]
I was curious if you would except a pull request to alphabetize imports. It would make findng out which modules are used easier. I realize that in some places in NVDA the imports probably need to occur in a certain order.

**Comment by josephsl** [comment]
Hi, I’d put a yellow light on this, seeing that Python conventions ask that built-in libs be loaded first, followed by third-party libs and then ones used by devs. Alphabetizing it based on convention and after checking import dependency would be better (in my opinion). Thanks.

**Comment by jcsteh** [comment]
IMO, this would be a lot of work and churn, as well as risking difficult-to-find breakage, for very little gain. Aside from anything else, some imports just make sense before others, even if they're not in alphabetical order; e.g. importing re before sys seems silly, even though they're both builtin. That said, we should definitely be following the Python convention for ordering Joseph noted for future modules; any modules I've written recently already do this.
