### ISSUE TITLE
Section is not read when focusing input

### ISSUE THREAD

**Issue by ivandiazwm** [nvaccess/nvda#5845]
Hello,
I happen to have an `<input>` inside a `<section>` that as an `aria-labelledby`.
When I focus the first focus-able item of a section (link or button for example). The content of what the `aria-labelledby` of the section points to is read.
But this doesn't happen with the input. It is not being read when the first item is an input.
Please, take a look to this fiddle: https://jsfiddle.net/xvund83w/5/
The first section title is read when you focus the link. The the second one isn't when you focus the input.

Is this a expected behavior?

Thanks.

**Comment by jcsteh** [comment]
A section with a label is treated as a landmark. Landmarks are only read in browse mode. When you tab to the link, you're in browse mode, but when you tab to the input, NVDA switches to focus mode. If the section is semantically a grouping for form fields/controls (like fieldset), use role="group", which will also cause it to be read in focus mode.
