### ISSUE TITLE
NVDA 2016.1 hangs while opening or attaching files on LYNC 2013

### ISSUE THREAD

**Issue by limaoscar** [nvaccess/nvda#5846]
On windows 7 enterprise and office 2010
with nvda running with mouse tracking ON
open lync 2013 and try to attach a file (everything, zip doc xls)
of click on a file received from other person
NVDA stop speaks and LYNC will not be available anymore
It is necessary to restart both NVDA and LYNC

**Comment by josephsl** [comment]
Hi, could you attach a log demonstrating this problem (with log level set to input/output)? Thanks.

**Comment by Brian1Gaff** [comment]
Actually, in Windows 7 at least there are times when say opening an open 
file dialogue in many pieces of software and then tabbing around makes nvda 
go silent. It does not actually crash, but it seems to get its focus muddled 
thereafter even if the desktop does appear to still work, the best plan is 
to restart nvda.
 My take on this has always been that the routine somehow drops out at an 
inapproprite place producing some variables  left set oddly in nvda.
 Unfortunately there is normally nothing in the log that shows the effect as 
nvda still thinks its speaking.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by limaoscar** [comment]
I have updated to skype for businesses and NVDA 2016.4, now the issue does not appear enymore
