### ISSUE TITLE
Switching to eSpeak-BNG seems to have messed up localized punctuation

### ISSUE THREAD

**Issue by parhamdoustdar** [nvaccess/nvda#5847]
Steps to reproduce:

1. Press insert+ctrl+v to go to voice settings, and make the following changes:
    * Uncheck use spelling functionality if supported
    * Uncheck Trust voice's language when processing characters and symbols
    * Uncheck Automatic dialect switching (when supported)
    * Uncheck Automatic language switching (when supported)
    * Set the voice to "Persian"
    * Click OK.
2. Read this line with the punctuation level set to most: (a).

What you are hearing is the following:

- Left parenthesis
- A
- Right parenthesis
- Right parenthesis in Persian

**Comment by Christianlm** [comment]
I think is an issue since eSpeak1.48.15 or preview versions.
In fa_list file below character names category the parentesis should be 
preceded by an underline:

'_(	paRAntezbAz
_)	paRAntezbaste:'

I suppose that you reproduce the same behavior  with 
SpeechPlayerInEspeak0.3 add-on.





Chris.

Parham Doustdar, 01/04/2016 19:56:

**Comment by parhamdoustdar** [comment]
I just tested this with other languages and this seems to be a language-dependent issue that doesn't exist in other languages. Sorry for this. Closing.

**Comment by derekriemer** [comment]
You might raise it with the Espeak-NG.

On 4/2/2016 7:40 AM, Parham Doustdar wrote:
>
> I just tested this with other languages and this seems to be a 
> language-dependent issue that doesn't exist in other languages. Sorry 
> for this. Closing.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5847#issuecomment-204718762>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194
