### ISSUE TITLE
spelling error sound played for escape in firefox

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5854]
* go to github.com/contact
* go to the edit field.
* type in a misspelled word such as graf.
* Do not type any other words, but do press space. If you don't press space at least navigate away from the word and back.
* make sure the spelling error is the last word in the document, and focus the cursor just after the word. Now, press escape to exit focus mode, and press escape again. Notice how the spelling error sound is played.

**Comment by derekriemer** [comment]
Make sure you do this in the multi line field.

**Comment by jcsteh** [comment]
Yeah. Also happens for other control characters like control+a.

Blocks #2024.

**Comment by derekriemer** [comment]
Okay. And btw, sorry to raise two bugs there in rapid fire, I just 
happened to discover the second one while investigating the first one.

On 4/3/2016 11:33 PM, James Teh wrote:
>
> Yeah. Also happens for other control characters like control+a.
>
> Blocks #2024 <https://github.com/nvaccess/nvda/issues/2024>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5854#issuecomment-205143993>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment]
Fixed in 8fa97d43. And I referenced the wrong issue in that commit. Grr.
