### ISSUE TITLE
aria-hidden="true" content in <TH> is read when <input> inside <TD> gains focus.

### ISSUE THREAD

**Issue by Martinator** [nvaccess/nvda#5860]
Similar to issues:
- [#4162 - aria-hidden="true" within labels is not honored upon focus of associated input](https://github.com/nvaccess/nvda/issues/4162)
- [#5006 - aria-hidden="true" element in an input's label is read aloud by NVDA](https://github.com/nvaccess/nvda/issues/5006)

I have a screen with a large calendar. The table headers contain days as such:

```
<tr class="caption1 bold text-center">
     <th scope="col">
          <span aria-hidden="true">Sun</span>
          <span class="sr-only">Sunday</span>
     </th> 
     <th scope="col">
          <span aria-hidden="true">Mon</span>
          <span class="sr-only">Monday</span>
     </th>
     etc...
</tr>
```

When a radio button gains focus inside a TD tag, NVDA announces the entire contents of the TH tag : 
- "Sun Sunday..."
- "Mon Monday..."
- etc...

in addition to the associated LABEL tag

It is desired that only the "sr-only" days from the TH tag get announced (in addition to the content of the LABEL tag). This is true when the table cells are navigated to using keyboard table navigation. However, once a radio button is selected and you switch to radio button navigation, the input with focus reads the aria-hidden content in the TH tag.
- Windows 7 Enterprise (Service Pack 1)
- FireFox 45.0.1
- NVDA 2016.1

**Comment by jcsteh** [comment]
The same controversy as in #4162 applies: ARIA specifies that aria-hidden should be ignored when performing name computation. In focus mode, we use the name exposed by the browser, so the browser does the name computation. If you believe there is something in the spec which contradicts this, please provide details. You'd then have to convince the browser vendors accordingly.

**Comment by Adriani90** [comment]
@Martinator are you still able to reproduce this issue with last NVDA alpha and last browser versions? @jcsteh this seems like there is an external fix needed for this issue in case it is still reproducible. Right?

**Comment by jcsteh** [comment]
This is no longer reproduceable after the changes to aria-hidden in Firefox last year.
