### ISSUE TITLE
Under/Over Bar in MathML not Read

### ISSUE THREAD

**Issue by tlhamrick** [nvaccess/nvda#5863]
I am not sure if this is the intended behavior or not, but there are a few contexts in which for creating mathematical expressions, we have used a "bar" operator in an over or under script.

Underbar: _ (from the keyboard)
Overbar: &#x203e; (`&#x203e;`)

Both of these characters appear to be read as empty strings in the context of math.

To see a few of the contexts, please visit the following jsfiddle link: https://jsfiddle.net/bpp1o20j/

The first is used to create "stacked expressions" (since there isn't a lot of great support for `mstacked` or `mline` elements), where we create the underline on the final term in the operation to take the place of the "=" (more or less). So in general, we would prefer something like "with under bar" to be said in this context (where currently it just says something like "with under").

The second is to create the "bar" on top of variables, that is often used to indicate the mean or average of a set of numbers. In this case we kind of expect something like "x with over bar", or to shorten it a bit (as is often done) to "x bar", or even "x double bar" if there are nested `mover` (although we don't mind if these special sorts of interpretations don't exist).

The last would be to create the appearance of an over bar for repeating decimals (again since there isn't the elementary math support for `mline`). Some of the following things may be more of feature requests, but in this there are a few special things, first the alignment of the overscript is important as we need to know that the bar is over the right characters rather than the left or center characters (this may not be important in all contexts), and then the length of the overscript (from the `maxsize`) attribute is important as well, to indicate how many of the values the bar appears above. I would image that something along the lines of "0.83 with right aligned bar of length 1 above" would be adequate for our purposes.

I realize this may contain a few different issues, but I think that getting something to be indicated for the bar (at least in the context of a `mo`) is the first thing, and then perhaps working on some kind of indication of the alignment and length of the script when the `align` and `maxsize` attributes are present.

**Comment by jcsteh** [comment]
NVDA uses MathPlayer for math output. Thus, any of these issues need to be addressed in MathPlayer; we can't fix them in NVDA. I would suggest contacting Design Science with your requests. Thanks.
