### ISSUE TITLE
Invisible Operators and Guessing Operation in MathML

### ISSUE THREAD

**Issue by tlhamrick** [nvaccess/nvda#5864]
I recently noticed some inconsistent behavior regarding the interpretation of operations in certain expressions. Namely expressions with either common function names or expressions where there was an `mi` next to an expression fenced in parentheses.

To see a long list of potential expressions where issues may occur, go to the following jsfiddle: https://jsfiddle.net/vwsLx5vx/1/

To point out some of the things that I am having an issue with:

1. In many cases where there is no invisible operator the operation is being interpreted as "function application" so we are hearing "of" instead of what I would expect (nothing). This applies to the first two examples of "No Operator" expression. Many of the other expressions with no operator there is no interpretation of the operation.
2. In many of the cases where the function application was being used (namely with the "sine" equations, and the "log" expressions that did not have a base) no operation was being read at all.
3. In almost every case where the invisible times operator was used (`&#x2062;`), the operation was not announced (and in some cases, the "function application" operator was read instead).
4. In the case of the "limit" function, it appears to actually be reading the operator twice when the invisible function application is being applied. So it will say something like "limit as x goes to 2 of of x"

I find this somewhat troubling, namely because if we are trying to teach students math and we interpret the operations for them when they are not (or even when they are) given then if we interpret it incorrectly we have now made it nearly impossible to answer the question because the information they receive is incorrect (e.g. thinking that x(3) is "x of 3" as opposed to "x times 3" or being just given "x left paren 3 right paren" and the user interpreting which is correct makes a huge difference).

My thought about what is appropriate is this

- If there are any two adjacent (non-operator) MathML elements (e.g. `mn`, `mi`, `mrow`, `mfenced`, `msup`, etc.) with no operator between them, then we say nothing about the operation.
- If any two MathML elements are separated by an invisible operator, you read the value of the operator in its normal flow position. `&#x2061;` is "of", `&#x2062;` is "times", `&#x2063;` is equivalent to "," basically, `&#x2064;` is "plus".

**Comment by jcsteh** [comment]
NVDA uses MathPlayer for math output. Thus, any of these issues need to be addressed in MathPlayer; we can't fix them in NVDA. I would suggest contacting Design Science with your requests. Thanks.
