### ISSUE TITLE
Prime/Double-Prime as Unit

### ISSUE THREAD

**Issue by tlhamrick** [nvaccess/nvda#5865]
We have been using the prime (&#x2032;) and double prime (&#x2033;) characters to write both their respective operators and the units "minutes" and "seconds" in MathML, and similar to the recommendations here: https://www.w3.org/TR/MathML3/chapter7.html#chars.pseudo-scripts, we have been writing them as pseudo script characters inside of an `msup`.

I noticed that when using these characters as an operator, I get the expected text output as, for example, "f prime", "f double prime", "f triple prime", etc. However, when the exponent is marked as a unit (e.g. `mi class='MathML-Unit'`) it is interpreted as an exponent, so something like "55 raised to the minutes power" instead of just "55 minutes".

See the following jsfiddle for examples: https://jsfiddle.net/6ss3y4ne/

I guess we were wondering if this is intentional that one is treated as a pseudoscript and one as an exponent.

**Comment by jcsteh** [comment]
NVDA uses MathPlayer for math output. Thus, any of these issues need to be addressed in MathPlayer; we can't fix them in NVDA. I would suggest contacting Design Science with your requests. Thanks.
