### ISSUE TITLE
Change Menu Items for Consistency

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5867]
For consistency, the following items within the NVDA submenu could be changed (original/proposed new text):

Tools:

Manage add-ons/Manage add-ons...

Help:

Welcome dialog/Welcome dialog...

**Comment by josephsl** [comment]
Hi, thanks for catching them. I’ll commit the needed changes (by the way, please let us know if there are other items that lack either the pneumonic or are inconsistent). Thanks.

**Comment by elliott94** [comment]
No problem - glad to help. :) Also, thank you for making the change so quickly!

**Comment by elliott94** [comment]
Just a couple more. :)

Tools:

View log/View log...

Create Portable copy.../Create portable copy...

**Comment by josephsl** [comment]
Hi, for these, I think they don’t need to be changed (log viewer isn’t a dialog, and there’s no need to capitalize portable copy).

**Comment by elliott94** [comment]
Not a problem - however, the "P" of "Portable copy" currently has a capital at the start - should this be changed?

**Comment by josephsl** [comment]
Hi, Hmmm, you brought up a valid point (@jcsteh and others, is it something we need to look into for consistency?). Thanks.

**Comment by jcsteh** [comment]
I disagree regarding "View log". The ellipsis is used to indicate a 
dialog, but View log doesn't bring up a dialog; it brings up a window. 
It's more like Donate, User Guide, etc.

**Comment by jcsteh** [comment]
Yeah, portable really shouldn't be capitalised.
