### ISSUE TITLE
Read Current Formatting: Silence if Command Pressed Three Times

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5870]
When testing the new feature that places current formatting info into its own buffer, I noticed that when pressing this command three times within an Explorer window where no formatting is present that no output was given. is this intentional, or should this in theory still report to the user that no formatting exists?

**Comment by PratikP1** [comment]
I can understand the logic for not announcing anything. Someone has to be incredibly fast fingered to not hear the “no formatting” announcement when the keystroke is pressed the first two times.

**Comment by jcsteh** [comment]
The command was changed so that pressing three times does nothing, as it's only documented to do something for one or two presses. Otherwise, presses after the second end up opening additional formatting info windows, which is very undesirable.

**Comment by elliott94** [comment]
This makes sense - however, when activating the command three times within a window that has formatting information, I'm able to make several windows with formatting information appear. Should this in theory not be possible to do?

**Comment by jcsteh** [comment]
It's not the third press that causes the new window to appear. It's the 
second press, which is documented to do just that.
