### ISSUE TITLE
Windows 7: Ease of Access Center Presented after New Install

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5873]
After performing a new install of NVDA on several Windows 7-based machines, I've noticed that the Ease of Access Center appears to be presented to the user each time the process completes. This doesn't re-appear after restarting NVDA, but immediately after the final install window has been dismissed. Whilst not a longterm problem because it's just a one-off after a new install, this has the potential to cause confusion to new users who may wonder why two separate screen readers are speaking at the same time. I unfortunatley haven't had a chance to test this on any other operating systems than Win 7, so not sure if this behaviour can be duplicated with later versions.

**Comment by derekriemer** [comment]
This happens if booting NVDA as a higher privlage than you as well.

On 4/9/2016 6:40 AM, elliott94 wrote:
>
> After performing a new install of NVDA on several Windows 7-based 
> machines, I've noticed that the Ease of Access Center appears to be 
> presented to the user each time the process completes. This doesn't 
> re-appear after restarting NVDA, but immediately after the final 
> install window has been dismissed. Whilst not a longterm problem 
> because it's just a one-off after a new install, this has the 
> potential to cause confusion to new users who may wonder why two 
> separate screen readers are speaking at the same time. I unfortunatley 
> haven't had a chance to test this on any other operating systems than 
> Win 7, so not sure if this behaviour can be duplicated with later 
> versions.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5873>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by Brian1Gaff** [comment]
I just encountered this as well. i thought this was Windows being mega 
efficient. I'm sure it never used to occur, but there was a windows update 
last week.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by leonardder** [comment]
I'm afraid we can't do anything about this. @michaeldcurran: thoughts?

**Comment by derekriemer** [comment]
I've only seen this on win7 however.

**Comment by Adriani90** [comment]
@elliott94 do you still have this issue on Windows 7?

**Comment by elliott94** [comment]
This appears to be related to the access level that NVDA runs at - as an example, I still see this exact same thing if choosing to run NVDA as a different user (which I think is related).
