### ISSUE TITLE
NVDA issue after closing modal with role dialog

### ISSUE THREAD

**Issue by maximilianotulian** [nvaccess/nvda#5876]
Hi, i have the next issue, please see the example in jsfiddle to reproduce it http://jsfiddle.net/maxtulian93/ysss1bxu/5/

1- Click in myBtn(Open Modal) to open the modal and focus is set to the btnClose.
2- Click in btnClose on the Modal and focus is set to myBtn.
When the modal has the role="dialog" in the second step the NVDA reads "button and other button" which means that both buttons are read. Is that the common behavior? If i remove the role="dialog" of the modal the NVDA reads "button, Open Modal".

**Comment by jcsteh** [comment]
When NVDA returns to a browse mode document (which happens when you leave the dialog), it reads the line at the cursor. This is intended behaviour.

**Comment by maximilianotulian** [comment]
I really appreciate your response, Regards.
