### ISSUE TITLE
Microsoft Word: NVDA freezes when searching for header rows

### ISSUE THREAD

**Issue by michaelDCurran** [nvaccess/nvda#5878]
A part from supporting automatic column header reading via bookmarks, NVDA also searches for rows that are marked as being a header row, and includes them as well.
However, for large tables, for instance 300 rows or more, NVDA will freeze for an extremely long time, and may stop reading table information all together.
The reason for this is that NVDA walks down the rows until it finds a row marked as a header row. It does this out-of-process which is very slow.
Documentation for Microsoft Word states that when setting a header row, the top row must be included. Therefore, we should change NVDA so that it only walks down rows while it is on a header row. I.e. Either the top row, plus 1 or more further rows are the header rows, or there are none at all.

**Comment by nvaccessAuto** [comment]
Incubated in ce9a7e6957a1d1498e90b7e665d254415e6df9a5.
