### ISSUE TITLE
Attachment information in Outlook 2016 is missing spaces

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#5885]
Using Outlook 2016. Braille shows: 'Some file.doc29 KB1 of 2 attachmentsUse alt + down arrow to open the options menu' (minus the quotes).

STR:
- Open a message with attachment in Outlook 2016.
- Shift+tab out of the message body to the attachments area.

**Comment by jcsteh** [comment]
Can you provide the devInfo (NVDA+f1) please? I actually suspect this is 
Outlook being goofy, in which case the fix will need to come from Microsoft.

**Comment by dkager** [comment]
Sorry. The text is the name of the object:

```
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (07:17:05):
Developer info for navigator object:
name: u'Some file.doc29 KB1 of 2 attachmentsUse alt + down arrow to open the options menu'
role: ROLE_BUTTON
states: STATE_FOCUSABLE, STATE_SELECTABLE, STATE_FOCUSED, STATE_READONLY, STATE_SELECTED
isFocusable: True
hasFocus: 1
Python object: <NVDAObjects.UIA.UIA object at 0x04E92410>
Python class mro: (<class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u'File name:  Some file.doc\r\nFile type:  .doc File\r\nFile size:  29 KB'
location: (10, 421, 300, 62)
value: None
appModule: <'outlook' (appName u'outlook', process ID 1096) at address 4d2c870>
appModule.productName: u'Microsoft Outlook'
appModule.productVersion: u'16.0.6769.2015'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 66834
windowClassName: u'NetUIHWND'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 5356
windowText: u''
displayText: u''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x6907838 at 4e6f8a0>
UIA automationID: 
UIA frameworkID: 
UIA runtimeID: (42, 66834, 2, 422710256, 0)
UIA providerDescription: [pid:1096,hwnd:0x0 Main(parent link):Unidentified Provider (unmanaged:OUTLOOK.EXE)]
UIA className: NetUIAttachmentItemButto
```

**Comment by jcsteh** [comment]
Yeah, I suspected as much. We're not overriding that - that's what 
Outlook is exposing - and the problem is that I don't think there's any 
way for us to know where to insert spaces.

**Comment by dkager** [comment]
Interesting, the name they expose is quite verbose. Is there a place where someone could report these annoyances?

**Comment by bramd** [comment]
@dkager You can ask MSFTEnable on Twitter how to report this

**Comment by dkager** [comment]
I think this should get needsExternalFix.

**Comment by jcsteh** [comment]
CC @MichaelDCurran. Can we get this reported to Microsoft?

**Comment by michaelDCurran** [comment]
Outlook bugs from users should be reported at: https://outlook.uservoice.com/
A bug from a user always has greater impact.
You can also include the link to your report here and I can also  ensure that our accessibility contacts in Office don't miss it.

**Comment by dkager** [comment]
Has been reported and is awaiting moderation.

**Comment by Adriani90** [comment]
@dkager, did you hear something from Microsoft regarding to this? Is the issue solved meanwhile?

**Comment by dkager** [comment]
Closing since the issue is no longer present in Outlook as part of Office 365. Older versions of Outlook may still have the problem but are very unlikely to get a fix from Microsoft, nor can we easily fix the problem in NVDA.

**Comment by Brian1Gaff** [comment]
As far as I know a lot of people still use 2016 and it still gets updates 
from Microsoft.

Brian
bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----
