### ISSUE TITLE
Extend pressing reading command twice quickly to spell, to reading selected and clipboard text

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#5889]
With many reading commands (**NVDA+up arrow** to read line, **NVDA+t** to read title etc), pressing them twice quickly spells the text the command otherwise reads.

Extending this functionality to **NVDA+shift+up arrow** to read selected text and **NVDA+c** to read the clipboard would make the behaviour of these commands consistent with other reading commands.

**Comment by Adriani90** [comment]
Closing in favor of #15449 which contains more details in the issue description.
