### ISSUE TITLE
One suggestion: NVDA reading order about landmark or grouping in web page.

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#5891]
Hello, I'm Hyongsop Kim in Korea.
Now, in web browser, if I press tab key, NVDA read landmark name, or grouping name or inside list item first (suppose these items are marked up), and then read the focused text.
Also if I press up down or pageup arrow keys, it reads landmark name or inside the list first and then reads actual focused text.
By the way, how about adding option that reads these items first or last?
Last mean is that let nvda read actual focused text first and then reads the landmark name or grouping name or etc.
If that option is available, screen reader users can choose reading way based on their needs.
Now these items are read always first, some users are annoying, because they want to listen focused text first.
Please check this issue.

Thank you.

**Comment by leonardder** [comment]
Related to #7232.

**Comment by khsbory** [comment]
Okay, I checked that it is same issue that you created. Thank you.
