### ISSUE TITLE
When toggling between Full shaped mode and Half shaped mode, braille message is needed

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#5893]
This case happen in east-Asian input methods.

Steps to reproduce:
1. Open text editor.
2. Press ctrl+space switch to native input.
3. Press shift+space
  speech: Full shaped mode
  braille: nothing
  expected: Full shaped mode

4. Press shift+space again
  speech: Half shaped mode
  braille: nothing
  expected: Half shaped mode

**Comment by jcsteh** [comment]
This will be addressed by the fix for #5892.
