### ISSUE TITLE
freeze: if I restart NVDA in word editor interface of office 365 64 bit.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#5898]
Hi:
If I restart NVDA When I wrote some text at microsoft office 365 word editor interface, NVDA and MS word will be freezed together. Thanks!

**Comment by leonardder** [comment]
@vgjh2005: Is this still the case? If so, please provide additional steps to reproduce.

**Comment by ehollig** [comment]
As we have not heard from @vgjh2005 since the creation of this issue in 2016, I am going to close this issue as invalid. Unless @vgjh2005 can provide exact steps to reproduce as requested in https://github.com/nvaccess/nvda/issues/5898#issuecomment-315843937 if this is still happening.
