### ISSUE TITLE
LANDESK Web Desk: Allow for Reading of Trees

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5899]
LANDESK Web Desk is a web-based ticket and logging system that is primarily used for analysts to create new incidents and requests from customers. Since it's web-based, the majority of the product is fully usable with NVDA without issue but there's one particular aspect that would make it a whole lot easier to use if this information was spoken. I should point out that I realise that I'm making this example pretty exclusive to a particular product here, but I was hoping that a similar control may also be used throughout separate web pages and as a result the addition of this fix to NVDA would benefit other users also.

When logging a new incident from within LANDESK, the analyst is given several options that use drop-down edit fields - that is, they're simply reported as standard fields by NVDA but when in Focus Mode, hitting the down cursor presents the user with the required options that can then be activated with a press of the enter key. Whilst the majority of these fields are fine, NVDA is currently unable to read selections that are presented as a tree - that is, they have options under them. As an example, a user may be able to select "Network" as a category, but then also be required to select something else (for example, "LAN" as a subcategory). Whenever one of these subcategories are encountered, if using the keyboard an NVDA user would first have to activate Focus Mode, and then press the down cursor at least twice to activate the first category. They would then hit the right cursor to expand the list of subcategories, and then select the subcategory required by hitting the down cursor. Whenever these controls are encountered, NVDA reads neither the category or subcategory option beneath - the only way of selecting these is to either memorise the positioning of items within the list, or to select options until the required value is found.

Since the Web Desk isn't readily available, in an attempt to provide some useful information on how these controls are presented I've pasted two separate pieces of information below. The first is a section of the web source of a control that reads without issue - in this case it's for the fields that asks for the name of the user. I've then pasted the developer info that's given by NVDA to describe the object.

Edit: Since for some reason I'm unable to get the raw HTML to appear, I've uploaded it to Pastebin at the following URL:

http://pastebin.com/SgavSBRw

```
Developer info for navigator object:
name: None
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_EDITABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible object at 0x05DF0610>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.ia2Web.Editor'>, <class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (347, 228, 680, 22)
value: None
appModule: <'firefox' (appName u'firefox', process ID 7492) at address 57edeb0>
appModule.productName: u'Firefox'
appModule.productVersion: u'45.0.2'
TextInfo: <class 'NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo'>
windowHandle: 131886L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 7500
windowText: u'LANDESK Web Desk - Incident - Mozilla Firefox'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0xa5efde4 at 61386c0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=131886, objectID=-4, childID=-663321088
IAccessible accName: None
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: u''
IAccessible accValue: None
IAccessible2 windowHandle: 131886
IAccessible2 uniqueID: -663321088
IAccessible2 role: ROLE_SYSTEM_TEXT
IAccessible2 states: IA2_STATE_OPAQUE, IA2_STATE_EDITABLE, IA2_STATE_SINGLE_LINE (9224)
IAccessible2 attributes: u'margin-left:0px;text-align:start;text-indent:0px;text-input-type:text;id:mainForm-RaiseUserTitleDisplay;tag:input;class:dropdownHost isHighlighted;margin-right:0px;margin-top:0px;margin-bottom:0px;display:inline;line-number:1;'
```

Finally, the following two pieces of information show the source from the page of a subcategory field (i.e. a field that isn't read by NVDA), and the accompanying developer info.

http://pastebin.com/Q3T6bbcY

```
Developer info for navigator object:
name: None
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_EDITABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible object at 0x05DFDC70>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.ia2Web.Editor'>, <class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (347, 932, 1514, 22)
value: None
appModule: <'firefox' (appName u'firefox', process ID 7492) at address 57edeb0>
appModule.productName: u'Firefox'
appModule.productVersion: u'45.0.2'
TextInfo: <class 'NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo'>
windowHandle: 131886L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 7500
windowText: u'LANDESK Web Desk - Incident - Mozilla Firefox'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x88fb764 at 5f7a8a0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=131886, objectID=-4, childID=-663652672
IAccessible accName: None
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: u''
IAccessible accValue: None
IAccessible2 windowHandle: 131886
IAccessible2 uniqueID: -663652672
IAccessible2 role: ROLE_SYSTEM_TEXT
IAccessible2 states: IA2_STATE_OPAQUE, IA2_STATE_EDITABLE, IA2_STATE_SINGLE_LINE (9224)
IAccessible2 attributes: u'margin-left:0px;text-align:start;text-indent:0px;text-input-type:text;id:mainForm-Category3Display;tag:input;class:dropdownHost isHighlighted;margin-right:0px;margin-top:0px;margin-bottom:0px;display:inline;line-number:1;'
```

To me, at least, the above pieces of information look very similar so I'm not sure it'll be that easy to get an idea of why NVDA may not be able to read the information. Let me know if there's any other information that I could obtain to debug, but it'd be incredibly useful if this functionality was added.

**Comment by elliott94** [comment]
Apologies - I wasn't able to get GitHub to display the HTML directly, so I chose to upload the source via Pastebin. See above for links - sorry for the confusion!

**Comment by jcsteh** [comment]
The web is huge and complex enough that supporting specific controls or frameworks within NVDA isn't really feasible. This really needs to be fixed by the developers of the app or the framework they're using. Alternatively, someone might be able to make it accessible using Greasemonkey; I've had success doing this for several sites.
