### ISSUE TITLE
Upgrade to UIAutomation 8

### ISSUE THREAD

**Issue by michaelDCurran** [nvaccess/nvda#5900]
The coclass for UI Automation in Windows 7 was CUIAutomation. However, in Windows 8, Microsoft added CUIAutomation8. Using this coclass caused some extra UIA proxies to be used, and also enabled QueryInterface to IUIAutomation2. Up until now NVDA has been able to make deal with the original UI Automation from Windows 7. And where properties from newer interfaces were needed, getCurrentPropertyValue and friends was used to access the property by its ID.
However now in Windows 10, there is need for NVDA to use such features as the TextEdit event handler, which can only be registered using the IUIAutomation3 interface. To QueryInterface to this, CUIAutomation8 must be used.
CUIAutomation8 also may provide better freeze handling as connection and transaction timeouts of UI Automation calls Only got this ability in the IUIAutomation2 interface.
Therefore, NVDA should make use of CUIAutomation8 where available, QueryInterfacing to IUIAutomation3, or IUIAutomation2, also, which ever is available.
This change should be done as a first step before implementing specific support for TextEdit events etc as the change to CUIAutomation8 should be tested widely for side-effects.

**Comment by nvaccessAuto** [comment]
Incubated in c6e883833a244529116732b17374b6fcf5db0055.

**Comment by nvaccessAuto** [comment]
Incubated in 691515983419ded88829d550463831a6f1dcebd1.
