### ISSUE TITLE
Som translated strings can't be converted into the local language.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#5913]
Hi:
I find that some string is become English along with NVDA langpack updating. I have checked my po file, and all strings have been done.
Follow are those unconvert strings examples:
Beep for progress bar updates
Beep and speak progress bar updates
No progress bar updates
Speak progress bar updates
top
 left
right
move focus
symbol level most
symbol level some
symbol level all
etc.
Thanks!

**Comment by jcsteh** [comment]
The capitalisation of quite a few strings was changed recently. "Beep 
for progress bar updates" (and I assume the others) are now marked as 
fuzzy in your language file. You'll need to verify these fuzzy entries 
and remove the fuzzy flag if they're fine. The po status page shows 
zh_CN as 97.20% complete.

**Comment by jcsteh** [comment]
zh_CN appears to be 100% complete, so closing.
