### ISSUE TITLE
[EDGE][BROWSE MODE] Radio Button do not read checked component after being read once

### ISSUE THREAD

**Issue by MarxAblir** [nvaccess/nvda#5915]
Steps:
1.)Click radio button previously unselected. NVDA reads the element "radiobutton checked"
2.)Reclick the selected radio button. NVDA no longer reads the element.

in  Chrome, Firefox the element is re read onced clicked

**Comment by PratikP1** [comment]
Is the Chrome behavior correct or Edge? Why would a user click on an already selected radio button? What is the use case for this?

**Comment by MarxAblir** [comment]
It is to reconfirm the action done by the user.

**Comment by PratikP1** [comment]
The user would use the read current line command to confirm action and not reclick on the radio button.

**Comment by MarxAblir** [comment]
this will only read the label of the radio button but not the state "checked"

**Comment by MarxAblir** [comment]
ahh okay I can use NVDA + Tab thanks for the info
