### ISSUE TITLE
Google chrome sometimes double fires on aria live regions.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5919]
I'm commenting on this one, mainly because firefox doesn't do this, but chrome does.
https://django.derekriemer.com/weather/hourly
When you load this page, with firefox, once you have weather data, go to the table. Click on one of the column headers, for example, the precipitation column header. Because I have a live region update, NVDA says "table sorted by descending precipitation" When I click it again, it would say "table sorted by ascending precipitation" 
This is the expected behavior. When I click the same column header with chrome canary, this information repeats twice. "Table sorted by ascending precipitation, table sorted by ascending precipitation" then it reads the new value, "table sorted by ascending precipitation." *2

**Comment by derekriemer** [comment]
Also, the row headers are h2's (for a friend who uses android and didn't have move by row on her mobile screen reader). In chrome, the table contents aren't marked as heading 2's while in FF, they are.

**Comment by derekriemer** [comment]
Another small bug here, when I read down the table header's, in firefox, NVDA says something like "2 P.M." "3 P.M." 
When I read down the row headers in chrome, all the information is doubled. However, if I read down the second or third (non-header) column, NVDA reads this properly.

**Comment by derekriemer** [comment]
Never mind on bug about the headings. That's my stupidity on coding this.

**Comment by jcsteh** [comment]
Not sure why the live region multi speaking is happening yet, but:

> When I read down the row headers in chrome, all the information is doubled.

That's due to [Chromium issue 595233](https://bugs.chromium.org/p/chromium/issues/detail?id=595233).

**Comment by jasonday** [comment]
This occurs for me as well, Chrome double reads the initial message and then reads the entire live region on update. This occurs specifically with `role="status"` and will ignore `aria-atomic` settings.

**Comment by derekriemer** [comment]
@jcsteh  Is this a dead bug?

**Comment by jcsteh** [comment]
I just tested and this appears to be fixed in Chrome Version 60.0.3112.113 (Official Build) (64-bit). Closing.
