### ISSUE TITLE
LibreOffice Writer: Reviewing Text commands does not work

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#5923]
STR:
1. Open test file.
2. Press numpad9 (5 times)
  speech: bottom
  expected: NVDA reads table content.

notes: 
• LibreOffice 5.1.0.3
• Test file is in Chinese.

**Comment by surfer0627** [comment]
file: test reviewing text commands

**Comment by surfer0627** [comment]
file: test reviewing text commands

**Comment by surfer0627** [comment]
[Test file](http://163.13.224.25/~crali/sample  test reviewing text commands.odt)

**Comment by zahra21** [comment]
hi.
you dont need to use numpad keys for reading documents.
fortunately, you can read documents using standard and normal keys which you use to read documents in any programs!
the only problem is unsupporting sayAll for screen readers!

**Comment by ehollig** [comment]
@surfer0627, as stated in https://github.com/nvaccess/nvda/issues/5923#issuecomment-376625061 you do not need to use the numpad keys to read the document. You can use the arrow key navigation to read the document and interact with tables. Does this fix your issue?

**Comment by Adriani90** [comment]
@surfer0627 we cannot reproduce your issue, the link is not working anymore. are you still having this issue?

**Comment by Qchristensen** [comment]
No response from @surfer0627, closing issue.
