### ISSUE TITLE
NVDA announces the presence of empty Alert live regions when Firefox does a repaint

### ISSUE THREAD

**Issue by afercia** [nvaccess/nvda#5924]
Partly related to #5657.

FWIW, noticed this behaviour in the WordPress admin, where since version 4.2 we've implemented a [core JavaScript function](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/js/wp-a11y.js?rev=33201) to dispatch audible messages to ARIA live regions. We'd greatly appreciate any insights and suggestions, since making live regions work nicely across all the various browsers / screen readers combinations is not so simple :)

Could reproduce this issue only with Firefox so I guess is a mix of Firefox and NVDA behaviours. In short: when setting a CSS overflow property other than "visible" on the body (and I guess on any element that contains the alert region), NVDA announces "Alert" even if there's no change in the content of the live region. 

Please notice this happens also when the role alert region is not dynamically added to the DOM. My guess is that Firefox does a repaint and thus NVDA "thinks" a role alert region just appeared on the page.

As pointed out in #5657, according to the specification role=alert should fire a system alert event but the specification also says:
> Alerts are assertive live regions and will be processed as such by assistive technologies.

see: https://www.w3.org/TR/wai-aria/roles#alert

To me, this means that if there's no content change in the alert live region, nothing should be announced.

I've prepared three tests on Codepen to illustrate this issue:

http://s.codepen.io/afercia/debug/mPRKLa
This first test reproduces what happens in WordPress. When opening a modal dialog or in some other limited cases, WordPress sets an overflow: hidden CSS property on the body. At this point NVDA announces "alert" even if the live region is empty and no changes happened. The live region was already there appended to the body.

http://s.codepen.io/afercia/debug/zqZyKe
a simplified test, setting overflow: hidden or overflow: auto on various elements.

http://s.codepen.io/afercia/debug/XbGKZY
a very simplified test case, no JavaScript dynamic changes here, everything is already in the markup at page load.

I perfectly understand it's not a NVDA responsibility if Firefox does a repaint :) not arguing on this. By the way the resulting behaviour looks not so ideal to me and it makes users experience worse. Announcing "alert" for an empty live region looks like a not so useful behaviour. Also, NVDA will actually stop reading out the following content and probably users will be a bit confused.

Worth noting none of the other screen readers I've tested with announces "alert" when there's no content change. This is not to say who's right and who's not, just to say that making things work nicely across all browsers / screen readers combination becomes a bit difficult this way :) 

Any thoughts and feedback would be greatly appreciated. And thanks for all your awesome work on NVDA!

Side note: about the WordPress implementation, I know that using both role=alert and aria-live and all the other aria properties is redundant, bt that as intentional to maximise compatibility with all the various browsers / screen readers combinations

**Comment by jcsteh** [comment]
There are two issues here. As you guessed, the repaint is part of the issue here, since Firefox generates completely new accessible objects (and fires corresponding events) when major CSS changes like this happen ([Mozilla bug 659886](https://bugzilla.mozilla.org/show_bug.cgi?id=659886), [Mozilla bug 1256706](https://bugzilla.mozilla.org/show_bug.cgi?id=1256706). However, any fix for #5657 will also fix this, so I'm closing this as a duplicate.

**Comment by afercia** [comment]
Sure :) Thanks James, I just wanted to report this case too.
