### ISSUE TITLE
Header row issue in complex tables designed in word.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5926]
Download [this document](http://files.derekriemer.com/broken%20browse%20mode%20and%20headers%20with%20non-uniform%20table.docx) and open it. Disable protected mode for good measure and consistency. Now go to row 1 col one.
Press NVDA+shift+r to enable row headers.
Go to row 3. 
Come back up to row 2, but on column 2 or 3.
Error sound plays.
Now repeat the same procedure. Disable row headers first.
There is also a browse mode issue with NVDA, I'm going to explain that in a separate ticket.
## Table overview:

This table has a complex layout. column one has a merged vertical cell, as if a1-a2 were merged. a2-a3 are merged. a4-a5 are merged. a6-7 is like a1-2.
Row two has two sub-headers for what b-e have.
If you need a more real world example, I can send privately a lab from ebio that I don't want to post publicly so I don't share answers with students of future classes who are too resourceful for their own good.

**Comment by jcsteh** [comment]
@MichaelDCurran

**Comment by nvaccessAuto** [comment]
Incubated in 74785a379b979b46eb27bd7153f6ea06f28447b6.

**Comment by derekriemer** [comment]
Closing 5563 since this fixed rows as well.
