### ISSUE TITLE
In excel charts are not read when there is no grid present.   

### ISSUE THREAD

**Issue by sumandogra** [nvaccess/nvda#5929]

**Comment by sumandogra** [comment]
In excel, no info is given about charts and one cannot collect chart elements in elements list dialog when grid lines are not present on the sheet on which chart is present.
Steps to reproduce:
1.	Open the attached sheet that has chart present on without grid. 
2.	Press NVDA+SPACEBAR.
3.	Press NVDA+F7 to get elements list dialog.
4.	Go to type group and select charts.
5.	Tab to the list view and there are no charts present.


please note, this issue was reported by a user who could not read charts in his org with NVDA.

**Comment by sumandogra** [comment]
[Sample.xlsx](https://github.com/nvaccess/nvda/files/251966/Sample.xlsx)

**Comment by michaelDCurran** [comment]
I can see that the chart in this file is on its own sheet. I.e. rather than an object within another sheet. In this case you can get to the chart in the Elements List by going to sheets. At the moment, "charts" only lists charts on the current sheet.
