### ISSUE TITLE
Dual Language English / German

### ISSUE THREAD

**Issue by Paveway2k** [nvaccess/nvda#5931]
I am using NVDA to aid with a blind pupil who is learning German.  Is there a way to get the English read out in an English voice and the German in a German voice?

Currently I have it set as a German voice, but it pronounces the English text with a German accent also.

Thanks in advance, and sorry for such a newbie question.

I forgot to say it is whilst using Word.

Mark

**Comment by ruifontes** [comment]
Hello!

For that to happen you need three things:

1 - The synth you are using is capable to speake english and german;
2 -Check in voice configurations the option to automatic switch language;
3 - You are using a document supporting lang tags, like MS Word, PDF, HTML 
and so on, and you have to set the various texts as english or german.

Rui



-----Mensagem Original----- 
De: Paveway2k
Data: sexta-feira, 6 de maio de 2016 14:26
Para: nvaccess/nvda
Assunto: [nvaccess/nvda] Dual Language English / German (#5931)



I am using NVDA to aid with a blind pupil who is learning German. Is there a 
way to get the English read out in an English voice and the German in a 
German voice?

Currently I have it set as a German voice, but it pronounces the English 
text with a German accent also.

Thanks in advance, and sorry for such a newbie question.

Mark

-

**Comment by gurix** [comment]
Using NVDA 2017.1 on Windows 7 installed in English is not capable to recognize German websites marked with `lang='de'`.

**Comment by ruifontes** [comment]
Sorry by the question, but have you checked the option to Switch language? 
It is in Voice settings.

Rui Fontes


-----Mensagem Original----- 
De: Markus Graf
Data: 22 de fevereiro de 2017 21:00
Para: nvaccess/nvda
Cc: ruifontes ; Comment
Assunto: Re: [nvaccess/nvda] Dual Language English / German (#5931)



Using NVDA 2017.1 on Windows 7 installed in English is not capable to 
recognize German websites marked with lang='de'.

**Comment by gurix** [comment]
Ok according https://www.nvaccess.org/files/nvda/documentation/userGuide.html I have to use eSpeak NG as synthesizer. So it was my fault, having installed the false synthesizer.

**Comment by feerrenrut** [comment]
@Paveway2k It seems like this issue is resolved, I'm going to close it now. Please re-open or comment on the issue if you are unable to get this working.
