### ISSUE TITLE
[Suggestion] suggest NVDA adding a sound alert if it reaches the end

### ISSUE THREAD

**Issue by lstar4ever** [nvaccess/nvda#5936]
I found that for Voiceover on IOS device, the Voiceover will have sound alert if the focus is at the end.
And I find this very helpful and hope it can be implemented into NVDA as well.

**Comment by bhavyashah** [comment]
Duplicate of #4285

**Comment by ehollig** [comment]
Thank you @bhavyashah, I knew there was a duplicate for this, but could not find it. Closing as duplicate
