### ISSUE TITLE
NVDA and Flash Content issue

### ISSUE THREAD

**Issue by eLearninDave** [nvaccess/nvda#5938]
Hello,
After a hard drive crash my computer was rebuilt (Windows 7 Enterprise, Service Pack 1). NVDA will now only read portions of some Flash content eLearning whereas before it had no issues. I also have another computer with the same exact build as the newly rebuilt machine and NVDA has zero issues with the Flash content. Both are running the latest Flash Player version. Any ideas on how to restore NDVA's operation with Flash? (both computers are running the same build number of IE11) Anything to do with Microsoft UAC?

Thanks,

dave

**Comment by ehollig** [comment]
@eLearninDave is this still an issue for you?
Regardless, Adobe has announced that Flash is deprecated, thus will no longer be developed actively. Closing
