### ISSUE TITLE
NVDA + IE11: Problem with Tree Views implemented using active-descendant

### ISSUE THREAD

**Issue by segedyjr** [nvaccess/nvda#5940]
Tree controls implemented using aria-activedescendant do not work in IE11 unless the tabindex property is set on the tree nodes. Here's an example tree control that works: http://accessibleculture.org/research-files/aria-tree-views/treeviewD.html.

If I make a simple modification to the tree and remove the tabindex property, the keyboard controls no longer work. See this modification: http://jsbin.com/conelahaxo/1/edit?html,output

My guess is that the treeitem needs to be focusable to work, and so spans and divs without tabindex set to -1 wouldn't get caught (MSHTML.py > _get_isFocusable).

**Comment by Adriani90** [comment]
@leonnarder, @jcsteh is this actually an NVDA issue? Or does it need an external fix?

**Comment by Adriani90** [comment]
Support for IE has completely ended in 2022 and the browser is being automatically removed from machines that still have it after an Edge update in February 2023. I am closing this issue as abandoned since I don't expect further accessibility updates to IE or to IE mode in Edge.
