### ISSUE TITLE
Word announces section breaks as page breaks

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#5946]
When you insert a section break (new page), NVDA identifies it as simply a "page break".  When you insert a section break (continuous), no identification is given by NVDA.  Column breaks are also not identified.

With formatting symbols displayed, column, page and section breaks are all displayed as a dotted line (different types of dots between the three types) across the page with the type of break in (what appears visually as) text identifying "Page break (continuous)", "Column break" etc.

**Comment by derekriemer** [comment]
I think a similar issue can be seen with column breaks, and using the 
arrow keys, no method is given to move to the next column. I might e 
wrong, I only saw this once on a test.


On 5/13/2016 5:04 AM, Quentin Christensen wrote:
>
> When you insert a section break (new page), NVDA identifies it as 
> simply a "page break". When you insert a section break (continuous), 
> no identification is given by NVDA. Column breaks are also not identified.
>
> With formatting symbols displayed, column, page and section breaks are 
> all displayed as a dotted line (different types of dots between the 
> three types) across the page with the type of break in (what appears 
> visually as) text identifying "Page break (continuous)", "Column 
> break" etc.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5946>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by Qchristensen** [comment]
You're right, there are other issues with columns which I've been pondering as well.  I just mentioned the issue with column breaks as I wasn't sure if this specific aspect was related to the section break identification.

**Comment by michaelDCurran** [comment]
Microsoft Word exposes all breaks as page break characters (0x12)
However We could announce section changes like we do for page changes. I.e. when arrowing anywhere if the section changes we could say "section x" before the text, where x is the new section number. We can get this with selection.sections(1).index
