### ISSUE TITLE
CRITICAL CRASH WITH NVDA AND WORD 2016

### ISSUE THREAD

**Issue by ThomasCowley** [nvaccess/nvda#5954]
NVDA Version: master-13321,7b0fd6f5 causes Word 2016 to crash after typing for a short while. Turning off reporting of grammar errors does not fix this, so I don't think it is that feature causing the crash.
Word 2016, Office 365

**Comment by jcsteh** [comment]
Are you absolutely certain this is caused by NVDA? For example, can you 
reproduce it if you use Narrator? Also, are you running Windows 10 
Insider builds?

We have reason to believe there might be a bug in a recent update to 
Word 2016 and/or Windows 10 that might be causing this.

**Comment by ThomasCowley** [comment]
Testing both with fresh instances of word exclusively with Narrator, 
NVDA or no screen-reader, and in a single instance of word while 
switching screen-readers, I was only able to crash it with NVDA on. I 
was not able to crash it consistently, but crashes seemed to occur 
within about 2 minutes of opening word and/or enabling NVDA.

For reference, I am running Windows 10 Home 64 bit version 1511 build 
10586.318 (stable builds), Microsoft Office 365 Version 16.0.6868.2060 
and NVDA version master-13321,7b0fd6f5.

**Comment by jcsteh** [comment]
Are you seeing some sort of crash dialog or is it more like a freeze where it stops responding?

CC @MichaelDCurran.

**Comment by ThomasCowley** [comment]
I am getting an ANR dialog. "Microsoft Word has stopped working".

**Comment by Brian1Gaff** [comment]
I occasionally get this on windows 7 with older versions of word. It is very 
rare though and apparently seems to follow some fiddling about with the font 
dialogue, is this what is being done in the newer version. I cannot say when 
it will happen but put it down to old word, andwindows 7 with nvda.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by ThomasCowley** [comment]
No. It is the latest stable Windows 10 with the latest stable Word 2016 
(Office 365). This happens if I just open word and start typing; after a 
random (but usually short) period of time it crashes.

I tried using a (portable) copy of NVDA 2016.1, and word ran fine, and 
as I already said, the issue also doesn't occur while running Narrator. 
Therefore, I think it is a problem with the new version of NVDA 
(master-13324,b0e35d32), but I don't know; I'm not an expert.

In case it's useful, I've copied the error log below.

     Faulting application name: WINWORD.EXE, version: 16.0.6868.2062, time stamp: 0x5727f2ed

     Faulting module name: MSGR8EN.DLL, version: 16.0.6828.1016, time stamp: 0x5725aea7

     Exception code: 0xc0000005

     Fault offset: 0x0002181c

     Faulting process ID: 0xcb0

     Faulting application start time: 0x01d1b476b6730841

     Faulting application path: C:\Program Files (x86)\Microsoft Office\root\Office16\WINWORD.EXE

     Faulting module path: C:\Program Files (x86)\Microsoft Office\Root\OFFICE16\PROOF\1033\MSGR8EN.DLL

     Report ID: 009d9be9-206a-11e6-9c31-001060e6a72d

     Faulting package full name:

     Faulting package-relative application ID:

     Log Name: Application

     Source: Application Error

     Event ID: 1000

     Level: Error

     User: N/A

     OpCode:

**Comment by michaelDCurran** [comment]
Was your master-13324,b0e35d32) a portable or installed copy? if 
installed, could you please confirm if it crashes with a portable copy?


Thanks



On 23/05/2016 8:39 AM, Thomas Cowley wrote:
> No. It is the latest stable Windows 10 with the latest stable Word 2016
> (Office 365). This happens if I just open word and start typing; after a
> random (but usually short) period of time it crashes.
>
> I tried using a (portable) copy of NVDA 2016.1, and word ran fine, and
> as I already said, the issue also doesn't occur while running Narrator.
> Therefore, I think it is a problem with the new version of NVDA
> (master-13324,b0e35d32), but I don't know; I'm not an expert.
>
> In case it's useful, I've copied the error log below.
>
> Faulting application name: WINWORD.EXE, version: 16.0.6868.2062, time 
> stamp: 0x5727f2ed
>
> Faulting module name: MSGR8EN.DLL, version: 16.0.6828.1016, time 
> stamp: 0x5725aea7
>
> Exception code: 0xc0000005
>
> Fault offset: 0x0002181c
>
> Faulting process ID: 0xcb0
>
> Faulting application start time: 0x01d1b476b6730841
>
> Faulting application path: C:\Program Files (x86)\Microsoft 
> Office\root\Office16\WINWORD.EXE
>
> Faulting module path: C:\Program Files (x86)\Microsoft 
> Office\Root\OFFICE16\PROOF\1033\MSGR8EN.DLL
>
> Report ID: 009d9be9-206a-11e6-9c31-001060e6a72d
>
> Faulting package full name:
>
> Faulting package-relative application ID:
>
> Log Name: Application
>
> Source: Application Error
>
> Event ID: 1000
>
> Level: Error
>
> User: N/A
>
> OpCode:
>
>
> On 16/05/2016 17:51, Brian1Gaff wrote:
> > I occasionally get this on windows 7 with older versions of word. It
> > is very
> > rare though and apparently seems to follow some fiddling about with
> > the font
> > dialogue, is this what is being done in the newer version. I cannot
> > say when
> > it will happen but put it down to old word, andwindows 7 with nvda.
> >
> > Brian
> >
> > bglists@blueyonder.co.uk
> > Sent via blueyonder.
> > Please address personal email to:-
> > briang1@blueyonder.co.uk, putting 'Brian Gaff'
> > in the display name field.
> > ----- Original Message -----
> > From: "Thomas Cowley" <notifications@github.com>
> > To: "nvaccess/nvda" <nvda@noreply.github.com>
> > Sent: Monday, May 16, 2016 7:51 AM
> > Subject: Re: [nvaccess/nvda] CRITICAL CRASH WITH NVDA AND WORD 2016
> > (#5954)
> >
> >
> > I am getting an ANR dialog. "Microsoft Word has stopped working".
> >
> >
> > On 16/05/2016 15:52, James Teh wrote:
> > >
> > > Are you seeing some sort of crash dialog or is it more like a freeze
> > > where it stops responding?
> > >
> > > CC @MichaelDCurran <https://github.com/MichaelDCurran>.
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/nvaccess/nvda/issues/5954#issuecomment-219354162>
> > >
> >
> >
> >
> > ---
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/nvaccess/nvda/issues/5954#issuecomment-219360996
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nvaccess/nvda/issues/5954#issuecomment-219368864>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5954#issuecomment-220860984>
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by ThomasCowley** [comment]
It was an installed copy.

I tested with a portable copy with my preferences saved, and a portable 
copy with no preferences and both copies caused the same issue.

**Comment by michaelDCurran** [comment]
This is probably not the case, but do you have a messaging app called 
Mumble installed at all? We are noticing that it can make Microsoft Word 
unstable on certain systems.


On 23/05/2016 2:46 PM, Thomas Cowley wrote:
> It was an installed copy.
>
> I tested with a portable copy with my preferences saved, and a portable
> copy with no preferences and both copies caused the same issue.
>
>
> On 23/05/2016 08:44, Michael Curran wrote:
> > Was your master-13324,b0e35d32) a portable or installed copy? if
> > installed, could you please confirm if it crashes with a portable copy?
> >
> >
> > Thanks
> >
> >
> >
> > On 23/05/2016 8:39 AM, Thomas Cowley wrote:
> > > No. It is the latest stable Windows 10 with the latest stable Word 
> 2016
> > > (Office 365). This happens if I just open word and start typing; 
> after a
> > > random (but usually short) period of time it crashes.
> > >
> > > I tried using a (portable) copy of NVDA 2016.1, and word ran fine, and
> > > as I already said, the issue also doesn't occur while running 
> Narrator.
> > > Therefore, I think it is a problem with the new version of NVDA
> > > (master-13324,b0e35d32), but I don't know; I'm not an expert.
> > >
> > > In case it's useful, I've copied the error log below.
> > >
> > > Faulting application name: WINWORD.EXE, version: 16.0.6868.2062, time
> > > stamp: 0x5727f2ed
> > >
> > > Faulting module name: MSGR8EN.DLL, version: 16.0.6828.1016, time
> > > stamp: 0x5725aea7
> > >
> > > Exception code: 0xc0000005
> > >
> > > Fault offset: 0x0002181c
> > >
> > > Faulting process ID: 0xcb0
> > >
> > > Faulting application start time: 0x01d1b476b6730841
> > >
> > > Faulting application path: C:\Program Files (x86)\Microsoft
> > > Office\root\Office16\WINWORD.EXE
> > >
> > > Faulting module path: C:\Program Files (x86)\Microsoft
> > > Office\Root\OFFICE16\PROOF\1033\MSGR8EN.DLL
> > >
> > > Report ID: 009d9be9-206a-11e6-9c31-001060e6a72d
> > >
> > > Faulting package full name:
> > >
> > > Faulting package-relative application ID:
> > >
> > > Log Name: Application
> > >
> > > Source: Application Error
> > >
> > > Event ID: 1000
> > >
> > > Level: Error
> > >
> > > User: N/A
> > >
> > > OpCode:
> > >
> > >
> > > On 16/05/2016 17:51, Brian1Gaff wrote:
> > > > I occasionally get this on windows 7 with older versions of word. It
> > > > is very
> > > > rare though and apparently seems to follow some fiddling about with
> > > > the font
> > > > dialogue, is this what is being done in the newer version. I cannot
> > > > say when
> > > > it will happen but put it down to old word, andwindows 7 with nvda.
> > > >
> > > > Brian
> > > >
> > > > bglists@blueyonder.co.uk
> > > > Sent via blueyonder.
> > > > Please address personal email to:-
> > > > briang1@blueyonder.co.uk, putting 'Brian Gaff'
> > > > in the display name field.
> > > > ----- Original Message -----
> > > > From: "Thomas Cowley" <notifications@github.com>
> > > > To: "nvaccess/nvda" <nvda@noreply.github.com>
> > > > Sent: Monday, May 16, 2016 7:51 AM
> > > > Subject: Re: [nvaccess/nvda] CRITICAL CRASH WITH NVDA AND WORD 2016
> > > > (#5954)
> > > >
> > > >
> > > > I am getting an ANR dialog. "Microsoft Word has stopped working".
> > > >
> > > >
> > > > On 16/05/2016 15:52, James Teh wrote:
> > > > >
> > > > > Are you seeing some sort of crash dialog or is it more like a 
> freeze
> > > > > where it stops responding?
> > > > >
> > > > > CC @MichaelDCurran <https://github.com/MichaelDCurran>.
> > > > >
> > > > > —
> > > > > You are receiving this because you authored the thread.
> > > > > Reply to this email directly or view it on GitHub
> > > > >
> > <https://github.com/nvaccess/nvda/issues/5954#issuecomment-219354162>
> > > > >
> > > >
> > > >
> > > >
> > > > ---
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/nvaccess/nvda/issues/5954#issuecomment-219360996
> > > >
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub
> > > > 
> <https://github.com/nvaccess/nvda/issues/5954#issuecomment-219368864>
> > > >
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/nvaccess/nvda/issues/5954#issuecomment-220860984>
> > >
> >
> > --
> > Michael Curran
> > Executive Director, NV Access Limited
> > Phone: +61 7 3149 3306
> > Website: http://www.nvaccess.org/
> > Twitter: @NVAccess
> > Facebook: http://www.facebook.com/NVAccess
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nvaccess/nvda/issues/5954#issuecomment-220861226>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5954#issuecomment-220886587>
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by ThomasCowley** [comment]
No.

**Comment by ThomasCowley** [comment]
Just a note that this problem still persists with NVDA 2016.2. It was 
even happening on my work machine running Windows 7 (Enterprise) and 
Office 2010.

I am going to try and see if it is one of my addons or programs doing 
it, but it seems that this release has broken compatibility with 
something or other.

**Comment by bramd** [comment]
I'm having the same, or at least a very similar issue here. Word 2010 64 bits on Windows 10 (normal release, no insider build), NVDA next-13326,62282e0b.

I was editing a document and after a while NVDA freezes completely. When I restart NVDA, Word has gone in the "is not responding" state. A friend called earlier today, she has exactly the same issue with NVDA 2016.2.

The not so helpful log output during the crash:

DEBUGWARNING - watchdog._watcher (23:55:15):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 191, in <module>
  File "core.pyc", line 382, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 355, in Notify
  File "braille.pyc", line 1760, in pumpAll
  File "braille.pyc", line 1632, in handlePendingCaretUpdate
  File "braille.pyc", line 1638, in _doCursorMove
  File "braille.pyc", line 948, in update
  File "braille.pyc", line 835, in _addTextWithFields
  File "NVDAObjects\window\winword.pyc", line 496, in getTextWithFields

**Comment by bramd** [comment]
Just tried to reproduce the crash running from source commit 8b4b002adb294960014ba6b70cde659b8830c4eb. I typed for a while in the same document, but I couldn't get NVDA/Word to crash.

**Comment by derekriemer** [comment]
It's very intermittent

Sent from a mobile device.
Please disregard errors as this is a smaller device.

**Comment by derekriemer** [comment]
It should be noted that several times this is happened to me while I've told Nvidia to create a dump for word and have never gotten it to produce one

Sent from a mobile device.
Please disregard errors as this is a smaller device.

**Comment by michaelDCurran** [comment]
We do now believe that this is caused by #5877 (support for grammar errors). I know that someone has said that turning off grammar errors didn't stop this, however, the code path for spelling errors was also changed in this implementation.

Could we ask that people try using NVDA 2016.2 with report grammar errors disabled and note here if the crashes stop occurring.
 
If the crashes do not go away, please also turn off Play sound for spelling errors and continue testing Word to see if it crashes.

**Comment by michaelDCurran** [comment]
For people experiencing crashes in MS Word with NVDA, please run the following NVDA try build:
https://ci.appveyor.com/api/buildjobs/lnl8rca4vswp8mu6/artifacts/output/nvda_snapshot_try-fixWord-13355,5e83bfa3.exe

This try build is equivalent to NVDA 2016.2, with out support for grammar errors in Microsoft Word, and also contains the fix for the Microsoft Word 2007 start-up crash on XP.

Before running this build, it is very important that you reboot your computer to ensure that Microsoft word is not running, and to ensure it has not left anything around in memory. Once rebooted, start this build as a portable or installed copy, and only then open Microsoft Word.

Please let us know if the crash goes away, or if it remains.

Thanks

**Comment by derekriemer** [comment]
> Before running this build, it is very important that you reboot your computer to ensure that Microsoft word is not running, and to ensure it has not left anything around in memory. Once rebooted, start this build as a portable or installed copy, and only then open Microsoft Word.
Just to clarify, do you want us to remove NVDA completely from our computer, or MS Word? I think the program name got left out above.
Thanks.

**Comment by derekriemer** [comment]
Never mind. You said reboot, and I heard remove.

**Comment by michaelDCurran** [comment]
Sorry, I mean to ensure that Microsoft word is still not running. 
Sometimes when MS Word crashes, it seems to leave bits around. Therefore 
the next time you start Word, even with a different copy of NVDA, it 
could still be in an unstable state.


The reboot ensures that Microsoft Word is started fresh when testing.


Mick




On 10/06/2016 1:53 PM, derekriemer wrote:
>
>     Before running this build, it is very important that you reboot
>     your computer to ensure that Microsoft word is not running, and to
>     ensure it has not left anything around in memory. Once rebooted,
>     start this build as a portable or installed copy, and only then
>     open Microsoft Word.
>     Just to clarify, do you want us to remove NVDA completely from our
>     computer, or MS Word? I think the program name got left out above.
>     Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5954#issuecomment-225087456>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ANf5nbw9YFnCT_Y5v7uS3YbsBLp5gR_Rks5qKN_BgaJpZM4Ie8TA>.
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by derekriemer** [comment]
I didn't read this carefully, and heard remove rather than reboot. My bad.


On 6/9/2016 9:57 PM, Michael Curran wrote:
> Sorry, I mean to ensure that Microsoft word is still not running.
> Sometimes when MS Word crashes, it seems to leave bits around. Therefore
> the next time you start Word, even with a different copy of NVDA, it
> could still be in an unstable state.
>
>
> The reboot ensures that Microsoft Word is started fresh when testing.
>
>
> Mick
>
>
>
>
> On 10/06/2016 1:53 PM, derekriemer wrote:
> >
> > Before running this build, it is very important that you reboot
> > your computer to ensure that Microsoft word is not running, and to
> > ensure it has not left anything around in memory. Once rebooted,
> > start this build as a portable or installed copy, and only then
> > open Microsoft Word.
> > Just to clarify, do you want us to remove NVDA completely from our
> > computer, or MS Word? I think the program name got left out above.
> > Thanks.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/nvaccess/nvda/issues/5954#issuecomment-225087456>,
> > or mute the thread
> > 
> <https://github.com/notifications/unsubscribe/ANf5nbw9YFnCT_Y5v7uS3YbsBLp5gR_Rks5qKN_BgaJpZM4Ie8TA>.
> >
>
> -- 
> Michael Curran
> Executive Director, NV Access Limited
> Phone: +61 7 3149 3306
> Website: http://www.nvaccess.org/
> Twitter: @NVAccess
> Facebook: http://www.facebook.com/NVAccess
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5954#issuecomment-225087751>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AFGivUXhW6z5da0vS9nOYQ4A_UkBV9fyks5qKOCOgaJpZM4Ie8TA>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by nimerjaber** [comment]
I have done as directed, and have not experienced any further crashing.

Thanks.

On Thu, Jun 9, 2016 at 10:58 PM, derekriemer <notifications@github.com>
wrote:

> I didn't read this carefully, and heard remove rather than reboot. My bad.
>
>
>
> On 6/9/2016 9:57 PM, Michael Curran wrote:
> > Sorry, I mean to ensure that Microsoft word is still not running.
> > Sometimes when MS Word crashes, it seems to leave bits around. Therefore
> > the next time you start Word, even with a different copy of NVDA, it
> > could still be in an unstable state.
> >
> >
> > The reboot ensures that Microsoft Word is started fresh when testing.
> >
> >
> > Mick
> >
> >
> >
> >
> > On 10/06/2016 1:53 PM, derekriemer wrote:
> > >
> > > Before running this build, it is very important that you reboot
> > > your computer to ensure that Microsoft word is not running, and to
> > > ensure it has not left anything around in memory. Once rebooted,
> > > start this build as a portable or installed copy, and only then
> > > open Microsoft Word.
> > > Just to clarify, do you want us to remove NVDA completely from our
> > > computer, or MS Word? I think the program name got left out above.
> > > Thanks.
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/nvaccess/nvda/issues/5954#issuecomment-225087456>,
> > > or mute the thread
> > >
> > <
> https://github.com/notifications/unsubscribe/ANf5nbw9YFnCT_Y5v7uS3YbsBLp5gR_Rks5qKN_BgaJpZM4Ie8TA
> >.
> > >
> >
> > --
> > Michael Curran
> > Executive Director, NV Access Limited
> > Phone: +61 7 3149 3306
> > Website: http://www.nvaccess.org/
> > Twitter: @NVAccess
> > Facebook: http://www.facebook.com/NVAccess
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/nvaccess/nvda/issues/5954#issuecomment-225087751>,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AFGivUXhW6z5da0vS9nOYQ4A_UkBV9fyks5qKOCOgaJpZM4Ie8TA
> >.
> >
>
> --
> ------------------------------------------------------------------------
>
>
> Derek Riemer
>
> * Department of computer science, third year undergraduate student.
> * Proud user of the NVDA screen reader.
> * Open source enthusiast.
> * Member of Bridge Cu
> * Avid skiier.
>
> Websites:
> Honors portfolio <http://derekriemer.com>
> Awesome little hand built weather app!
> <http://django.derekriemer.com/weather/>
>
> email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
> Phone: (303) 906-2194
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nvaccess/nvda/issues/5954#issuecomment-225087841>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/APE2Obmd5HXEzKIMgsb9jHfPDkDlkv8vks5qKODQgaJpZM4Ie8TA>
> .
>



-- 
Cordially,

Nimer Jaber

Please take the time to read this signature completely as it contains
some information about the email you have just read and all
attachments contained within as well as some valuable resources and
methods for contacting me if you have any questions or wish to talk.

The message above is intended for the recipient to whom it was
addressed. If you believe that you are not the intended recipient,
please notify me via reply email and destroy all copies of this
correspondence. Action taken as a result of this email or its contents
by anyone other than the intended recipient(s) may result in civil or
criminal charges. I have checked this email and all corresponding
attachments for security threats. However, security of your machine is
up to you. Thanks.

Registered Linux User 529141.
http://counter.li.org/

To find out about a free and versatile screen reader for windows XP
and above, please click here:
http://www.nvda-project.org

You can follow @nimerjaber on Twitter for the latest technology news.

To contact me, you can reply to this email or you may call me at (218)
(409-9229) and I will do my best to respond to you promptly. Thank
you, and have a great day!

**Comment by jcsteh** [comment]
Fix included in NVDA 2016.2.1, which was released a few hours ago.

**Comment by gregjozk** [comment]
Hi,

i'm sorry, that it happened for some users. anyway reporting of grammer errors  and "playing sounds on spelling errors" was a great feature and on win7 32-bit and word 2010 it worked without problems. now i'm trying to reproduce on latest stable win10 and it seems that i cannot find no problem, so i hope, that this feature will be included again.

**Comment by jcsteh** [comment]
Note that only reporting of grammar errors was removed. Alerts for spelling errors while typing still works and is still included.

Unfortunately, we have no idea how to work around this problem with grammar errors in Word, so it's unlikely we'll be able to bring this back any time soon..

**Comment by leonardder** [comment]
Do we have any information about office vs. windows combinations where this issue does not occur? I've worked with Windows 10 and office 2016 multiple times and as far as I remember, haven't experienced crashes so far. May be we can enable the feature in working cases and disable it in others?

**Comment by jcsteh** [comment]
Even where it does occur, it's intermittent. Also, it seems to happen faster/more often on some systems than others. I was eventually able to reproduce on Windows 10 with Office 2016, but it takes a lot of rapid typing for quite a while to trigger it.

**Comment by ThomasCowley** [comment]
It does. But sometimes my word was crashing when I opened a document and 
made a couple of minor alterations. So it seems very unpredictable.
