### ISSUE TITLE
Microsoft Word browse mode copy to clipboard should copy formatting

### ISSUE THREAD

**Issue by michaelDCurran** [nvaccess/nvda#5956]
Currently browse mode for Microsoft Word's copy to clipboard command copies only the plain text via cursorManager. Instead it should use Microsoft Word's own copy command on a Microsoft Word range object.
Spin-off of #5895.

**Comment by jcsteh** [comment]
I was originally wondering whether we should somehow just not intercept 
control+c at all for browse mode in Word, since that would also have the 
desired effect. However, that might actually be harder to implement.

**Comment by nvaccessAuto** [comment]
Incubated in aa14d6ed180e52addb4b6f17e6cbe49a55df2c6a.
