### ISSUE TITLE
Some Flash players Remain Inaccessible

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#5973]
If a flash player or object as seen through nVDA exists, one of two things happens.
1. The window is reported as clickable if the document can be access through the enter key.
2. The document cannot be clicked on if the enter key command does not work.
I find this interesting behavior because the mouse will work just fine once you are able to navigate to where the object is by left clicking on it.

**Comment by jcsteh** [comment]
Please be more specific. Please provide information about what browser 
you're using, as well as an example website where this occurs and the 
exact steps you took.

**Comment by Elshara** [comment]
Example website 1.
http://www.soundclick.com/bands/default.cfm?bandID=1071100
The music player is the object within flash. As you can see, you
cannot click on it. Issue appears in Firefox, chrome, Internet
Explorer, Edge.
Example website 2.
http://www.spruz.com/
Unknown description of flash object. But the object is clickable.
Appears in, Fire Fox, Chrome, Internet Explorer, Edge.
The object is navigated to by pressing o when the website loads.
I have the latest version of flash player installed.

**Comment by bhavyashah** [comment]
Keeping in mind the on going Project Webfix as well as the fact that Flash shall be abandonware soon enough, any updated thoughts? @jcsteh @feerrenrut

**Comment by Brian1Gaff** [comment]
The sooner Flash is got rid of the better, then maybe some of the clueless 
sites that insist on using it will have to come into line and make them work 
properly in html5.
 Most of the media player crashes and weirdnesses seem to be due to Flsh 
plug ins or the code that invokes it.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by feerrenrut** [comment]
While this is an annoying issue, there is no plan to try address this issue as part of the webfix project.

**Comment by bhavyashah** [comment]
Alright. More dynamic things like Edge and evolving ARIA need the
attention anyways, as opposed to the soon-to-be-obsolete Flash.

On 7/31/17, Reef Turner <notifications@github.com> wrote:
> While this is an annoying issue, there is no plan to try address this issue
> as part of the webfix project.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/5973#issuecomment-318992592


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by bhavyashah** [comment]
@feerrenrut I was under the impression that Flash would be way lower in priority due to its coming death and the fact that most websites are transitioning to HTML 5 anyways. In fact, we have closed several Flash specific tickets as wontfix too. Thus, P3 seems unjustified to me. Thoughts?

**Comment by feerrenrut** [comment]
Yes, I think its best to be consistent with our approach to this. Closing as won't fix, it's very unlikely we would get to issues like this before Flash is well and truly obsolete.
