### ISSUE TITLE
Get NVDA Add Ons Remotely From Official Add Ons Repository

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#5977]
NVDA updates itself remotely. It would be ideal if add ons could be installed and removed remotely as well.

**Comment by jcsteh** [comment]
I assume you're talking about automatic add-on updates. That's covered by #3208. Any other kind of remote add-on maintenance would be a security hazard.

**Comment by Elshara** [comment]
Yes I'm talking bout automatic add on updates.
