### ISSUE TITLE
Abillity to read Skype profiles

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#598]
**Reported by Bernd on 2010-03-16 07:38**
None

**Comment by leonardder** [comment]
I can still reproduce https://github.com/nvaccess/nvda/issues/598#issuecomment-155282037 . I assume this is a bug in Skype's IAccessible implementation.

However, you can perfectly review the dialog with screen review. If we still consider this a bug, I think this isn't much more worth than a P4.

cc @BDorer

**Comment by Adriani90** [comment]
This is still reproducible in Skype 8. In Skype UWP not all information is reported when navigating with tab and shift+tab. But you can easily access everything with object navigation.
@bdorer, @ruifontes do you have other thoughts on this?

**Comment by Adriani90** [comment]
Testing now on Skype 8 UWP 44.0.40 and Skype Electron 8.45.0.41 with NVDA 2019.1.1, everything can be accessed now with tab and shift+tab in a profile dialog.
@k-kolev1985 can you confirm?

**Comment by k-kolev1985** [comment]
Yes, now every information in the profile dialog for a Skype user is accessible and readable either via keyboard navigation or with object navigation.

**Comment by Adriani90** [comment]
Closing as works for me.
