### ISSUE TITLE
Broken Previous heading quicknav in Edge

### ISSUE THREAD

**Issue by michaelDCurran** [nvaccess/nvda#5987]
Currently moving to previous heading in Edge browse mode (shift+h)  incorrectly moves one character forward, rather than moving to the previous heading. The current algorithm for UIATextAttributeQuickNavIterator needs total rewriting. I doubt moving previous ever worked.

**Comment by nvaccessAuto** [comment]
Incubated in 9c1c4f06cf75a64bccbb07994ff44fe5d34a7620.

**Comment by nvaccessAuto** [comment]
Incubated in 62282e0b414bbaed9d1c8c647dbff80c70ba3d65.

**Comment by nvaccessAuto** [comment]
Incubated in 5410db6a2fe8bfa5b6b660f88f07ab3c52316460.
