### ISSUE TITLE
BrailleNote: Support scroll wheel on Apex BT

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#5992]
Hi,

Referencing #2012:

On the Apex BT, there exists a scroll wheel between dots 1 and 4. This consists of four directional dots, a center button and a scroll wheel.

The below commit assigns following commands:
- Center button: ENTER.
- Directional dots are assigned to arrow keys.
- Scroll clockwise: TAB.
- Scroll counterclockwise: Shift+TAB.

Also took the time to update the BN driver by modifying copyrights. Another branch will be used for providing basic support for BrailleNote QT. Thanks.

**Comment by josephsl** [comment]
Hi,

#5993 portion: Working great according to two testers. I'm waiting for feedback from other Apex BT users (I use an Apex BT).

Thanks.

**Comment by ehollig** [comment]
Closing this, as #6316 has been merged.
