### ISSUE TITLE
Add support for BrailleNote QT basic mode

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#5993]
Hi,

Continuing from #5992:

The below commit (part of i5992 branch) adds support for BrailleNote QT models. There are two modes of operation: basic mode (basic QWERTY commands are available), and PC mode (emulates PC keyboard).

The following commands are available:
- NVDA menu: Alt+N
- Control+Home: Alt+T
- Control+End: Alt+B
- Windows key: Alt+W
- Alt key: Alt+M
- Input help mode toggle: Alt+1

On the QT, the names of keys are:
- Read: Alt
- Control: Control
- Function: right Alt.

QT commands are based on KeySoft native commands except as noted. Thanks.

**Comment by SamuelEnglard** [comment]
I've been playing around with the BrailleNote QT and thought it might help to let you know that the codes it sends for keys are the Windows Virtual Key Codes

**Comment by josephsl** [comment]
Hi,

Fixed a critical regression: possibly due to use of HwIO, QT commands were treated as raw strings, so no need to ord this anymore. Thanks.

**Comment by Adriani90** [comment]
@josephsl is this issue still valid?

**Comment by josephsl** [comment]
Hi, let’s close this one. Thanks.

**Comment by Adriani90** [comment]
ok does this mean the issue is solved? Or you will not work on this in the future. If it's not solved then maybe we can find someone who can continue working on this. Thanks.

**Comment by josephsl** [comment]
Hi, resolved as of 2018.3 (see what’s new for details). Thanks.
