### ISSUE TITLE
In Chrome, some variants of iframes don't announce anything but a title.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5994]
I am working on readium-js-viewer (a javascript epub book reader). I opened a book in chrome canary (this bug should occur in chrome as well). I noticed that chrome completely ignores all contents inside iframes. In iframe test, chrome seems perfectly happy, but chrome doesn't tell NVDA the text of the epub reader view of readium. When you go to the test, the iframe (the index of my files directory) works fine. However try to read the epub with the readium link. Note that both work as expected in firefox.

* iframe test: https://files.derekriemer.com/iframe_test.htm
* Readium viewer: https://readium.firebaseapp.com/?epub=epub_content%2Fmoby_dick&goto=%7B%22idref%22%3A%22xpreface_001%22%2C%22elementCfi%22%3A%22%2F4%2F2%2F2%2F2%2C%2F1%3A0%2C%2F1%3A1%22%7D&

cc @clapierre @benetech

**Comment by derekriemer** [comment]
That url is nasty. 
Use this if you wish.
http://bit.ly/22obbRS

**Comment by jcsteh** [comment]
That's a Chrome bug. I just filed [Chromium issue 614570](https://bugs.chromium.org/p/chromium/issues/detail?id=614570) for this.

**Comment by derekriemer** [comment]
@jcsteh It looks like this bug is fixed.

**Comment by derekriemer** [comment]
Fixed. I just confirmed this with the latest chrome canary.
