### ISSUE TITLE
Log Python stacks when handling a crash

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#5998]
We've seen quite a few crashes lately (#5706, #5764, #5844, #5859) where the crash dump just doesn't provide sufficient information to be useful. There are two things we can do to improve this:

1. Use wx dlls for which we have symbols. We're seeing quite a few crashes in wx code, but we can't get any info from them without symbols. wxPython doesn't provide symbols, but I think we might be able to drop in the pre-built dlls from wxWidgets instead, and they do provide symbols.
2. Log the Python stack for each thread. It'd be really helpful to know what was going on in Python when a crash occurred. Even if the crash isn't within Python itself, it might show us how to reproduce it.

**Comment by jcsteh** [comment]
Unfortunately, you can't just drop in the wxWidgets dlls as I'd hoped; wxPython refuses to load them. That means we'll have to build wxPython ourselves if we want symbls, which is a huge undertaking. Narrowing the scope of this issue to just the Python stack, which will still be very useful. We can deal with building wxPython elsewhere if we must.

**Comment by nvaccessAuto** [comment]
Incubated in 3ed9c12f60b981fa21ae3907b25b094b60bd9289.
