### ISSUE TITLE
Excel 2010: cannot report table row/column headers in protected sheets.

### ISSUE THREAD

**Issue by Christianlm** [nvaccess/nvda#6000]
Probably this issue could be related to #4952 and #5404.
I reproduce this on windows 7  Pro. When the sheet is protected NVDA don't reads automatically headers of rows and columns.

**Comment by jcsteh** [comment]
Unfortunately, for some unknown reason, Excel won't allow us to retrieve cell region information in protected sheets. We need cell region information to be able to accurately retrieve row/column headers.

See also #4409. CC @MichaelDCurran.

**Comment by Mister-Kayne** [comment]
I am just revisiting this thread on the issue, which I am also experiencing with Excel 2019 but on reading the detailed comments I now am aware that this cannot be fixed; see comment below. I am wondering if it is possible to re-open this issue and still work on a fix? Sorry, I ain't a techie, just someone who needs this to work really bad.

Unfortunately, for some unknown reason, Excel won't allow us to retrieve cell region information in protected sheets. We need cell region information to be able to accurately retrieve row/column headers.

**Comment by seanbudd** [comment]
This issue has been closed for over 9 years. Can you please open a new bug report with all the relevant updated information including the version of office you are using

**Comment by Mister-Kayne** [comment]
Thank you for your comment. I am a new Git Hub user and trying to get oriented to it. I will without doubt file a new issue, once I have it all figured out. Thank you once again.
