### ISSUE TITLE
Microsoft Edge: SVG inside a link announces link text multiple times

### ISSUE THREAD

**Issue by cshold** [nvaccess/nvda#6001]
When a link has a SVG element inside of it, NVDA will read out the text three times. It will also read out "graphic" for the SVG element itself, even though it has `aria-hidden="true"`, `focusable="false"`, and `role="presentation"`.

![image](https://cloud.githubusercontent.com/assets/1730309/15586539/e47130bc-2352-11e6-90d0-e2b3a9239eb7.png)

Demo http://codepen.io/cshold/pen/PzYXYX

NVDA 2016.1, running on Edge in Windows 10.
Chrome and Firefox work as expected.

**Comment by cshold** [comment]
As noted in an [April 5th 2016 NVDA post](http://www.nvaccess.org/win10/), Microsoft Edge isn't the suggested browser to use with NVDA.

**Comment by michaelDCurran** [comment]
I can not reproduce this with NVDA 2017.1 and Microsoft Edge in Windows build 15055. Many improvements were made to Edge since this bug was opened.
