### ISSUE TITLE
Error beep is frequently heard while trying to read a new message in outlook 2016

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#6002]
(This problem does not occur all the time.) Here are the steps.
1. Arrow through a list of messages. 2. Press enter on a message to read it. 3. use arrow keys to read the message. 4. use up or down arrow keys in the message. 5. switch to any other window. 6. Return focus to opened message.

most times, the message does not read when using arrow keys or NVDA+a. Up arrow results in the error tone. Down arrow a few times results in no speech. Focusing away then returning to the window resolves the problem. This does not happen all the time but happens frequently enough that I have developed the habit of moving away then returning to the window. I have not been able to determine a pattern. 

I'm attaching the log

[nvda.log.txt](https://github.com/nvaccess/nvda/files/285185/nvda.log.txt)

**Comment by PratikP1** [comment]
This problem occurs on Win 10 and Windows 7. I have not tested Office 2013 or 2010.

**Comment by mjanusauskas** [comment]
I have seen this happen in Outlook 2013.

**Comment by jcsteh** [comment]
In the log, I do see the arrows not doing anything, but I don't see any 
error when you press up arrow. Did that just not happen in this 
particular instance of the issue? I'm thinking it might be enlightening 
to see that error when it does occur.

**Comment by PratikP1** [comment]
Odd but I’m hearing the error tones. It’s not being recorded in the logs. I’m wondering if it’s a Windows error tone. Hmmm, more testing on Windows 10 shows that tone at top and bottom boundary. The tone might be a red herring. But, blank emails is still a problem. Unfortunately, I can’t seem to record here or I’d record a demo.

**Comment by ehollig** [comment]
This does not happen for me using Outlook 2016 and latest NVDA. @PratikP1, is this still an issue?

**Comment by PratikP1** [comment]
It is still an issue. It’s related to messages with layout tables.

**Comment by Adriani90** [comment]
It seems we do not have any updates for this issue in the last two years. If it is a focus tracking problem, then please comment on #8389. 
I am closing this one as abandoned. @PratikP1 please comment on it if you think we should reopen it though.
