### ISSUE TITLE
Title and description on images

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6003]
Word also has the ability to titlize and descriptionize images.
1. insert > image. select one.
2. select the image. Note4, NVDA says "/" for some reason.
3. applications key.
4. Format image > layout.
5. Alt text expanded.
6. Put a title.
6. f6 to the doc. 
The title reads once you unselect it.
7. Add description in the same way.
8. NVDA ignores the title.

**Comment by PratikP1** [comment]
Previous experience suggests that this is a matter of how Microsoft has implemented description exposure. Same thing occurs with JAWS and Window-Eyes.

**Comment by derekriemer** [comment]
@MichaelDCurran

**Comment by michaelDCurran** [comment]
I originally implemented it like this as the property we receive the "description" from is called "alternativeText". This then uses roughly the same rule as on the web. I.e. use alt text over title. However, if you can provide good evidence that authors are using title and description in a different way for Word documents, then I'd be happy to revisit that decision. I.e. perhaps expose both all the time. Or only expose title, and then provide description via optional long description like I have now done for tables.

**Comment by derekriemer** [comment]
I don't have any evidence one way or the other. I just wanted to see if 
it was similar to the table thing.


On 5/26/2016 3:43 PM, Michael Curran wrote:
>
> I originally implemented it like this as the property we receive the 
> "description" from is called "alternativeText". This then uses roughly 
> the same rule as on the web. I.e. use alt text over title. However, if 
> you can provide good evidence that authors are using title and 
> description in a different way for Word documents, then I'd be happy 
> to revisit that decision. I.e. perhaps expose both all the time. Or 
> only expose title, and then provide description via optional long 
> description like I have now done for tables.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/6003#issuecomment-222003598>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by PratikP1** [comment]
I think this interpretation is correct. PDF conversion takes the info from the description field and not title.

**Comment by jcsteh** [comment]
Closing based on the above. If someone has a solid argument to the contrary, feel free to comment.
