### ISSUE TITLE
Word Page numbering style "- 1 -" reads "dash" for page 2 onwards

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6004]
In Word 2016 at least, from a blank document, press control+enter to add a second page.  Then add page numbers (alt+n, n, u then any style - top of page, plain text 1 is fine).  Press the applications key and choose "format page numbers", press down arrow to change number format to - 1 -, - 2 -, - 3 - and press enter to accept.

Page 1's number reads as "- 1 -" but page 2 onwards only read as "dash".

**Comment by PratikP1** [comment]
It appears that NVDA is not moving through other headers at all with this page numbering style in effect. I tried adding additional pages to a document but not much luck.

**Comment by Qchristensen** [comment]
It does move between pages for me, although without it reading the page
numbers it can be hard to tell.

To test, you can insert a page number elsewhere although you can't do it
with the regular page number feature as it will use the same style of
numbering (and if you go to format page number, it will change both.
Instead if you press alt+j (then h if you press alt and j separately), then
press i to insert document information, then f for field - this lets you
insert pretty much any piece of information into your header / footer -
press p and choose "page" but then press tab and choose a different number
format and press enter - doing it that way doesn't change the numbering of
the original page number but makes it easy to see whether you are in fact
changing pages as you arrow through the header / footer fields.


-- 
22 Point

Web: http://www.22point.com.au
Facebook: https://www.facebook.com/22Point
Twitter: https://twitter.com/22PointApps

Check out our first app, RapiTap! - Tap targets fast & avoid decoys:
Adrenaline pumping, Challenging, Accessible!
https://play.google.com/store/apps/details?id=au.com.twentytwopoint.rapitap
Free trial:
https://play.google.com/store/apps/details?id=au.com.twentytwopoint.rapitapfree

**Comment by michaelDCurran** [comment]
This is definitely a bug in MS Word in the way that it allows moving by word and characters. Sometimes it skips over part of the field as we collect text. If this is specific to page fields I can probably work around this with out too much fuss. However, it would be nice to get an idea  if there are other fields that are also broken. E.g. date/time fields seem to work fine.

**Comment by feerrenrut** [comment]
Using Word 2013.
I get the described functionality (while editing the headers) when the cursor is before the page number, when after the page numbers I just get "blank".
With the nvda document formatting set to read page numbers (and no longer editing the headers) I can hear the page numbers as I move through the document.
When nvda is running (and editing the header) the cursor can not be moved back passed the page number text. When nvda is not running, I can move the cursor character by character in both directions through the page number.
When nvda is running and I click on a character in the page number field the cursor is moved to the end of the field. This is not the case when nvda is not running.
