### ISSUE TITLE
Say current line is not working in GMail conversations list in Chrome

### ISSUE THREAD

**Issue by mjanusauskas** [nvaccess/nvda#6012]
Using Chrome Canary:
Go to the standard GMail site and use the arrow keys or J and K to select a conversation from the list.
Press numpad 8 to read the current line.
Notice nothing is spoken.

**Comment by jcsteh** [comment]
While you can use read current line like this in some lists, the 
recommended way to query the currently focused object is to press 
NVDA+tab. Read current line retrieves the "text" of the object, not the 
label, but in the case of Gmail, you want the label.

**Comment by mjanusauskas** [comment]
Thanks for that information. I noticed that in Firefox that the command did
work as expected which is why I raised the question.

**Comment by ehollig** [comment]
I am not able to have anything read in the conversations list of Gmail after selecting a conversation by pressing J or K and then pressing numpad 8 in either Chrome or Firefox. Could this because NVDA is in focus mode? @mjanusauskas, is this still an issue? If so, @jcsteh do you believe this should be an issue that should be fixed as you can retrieve this information using NVDA+tab as stated in https://github.com/nvaccess/nvda/issues/6012#issuecomment-222419383?

**Comment by mjanusauskas** [comment]
Using NVDA+Tab seems to be a reasonable solution to me.

**Comment by jcsteh** [comment]
The fact that you get this information with NVDA+tab doesn't necessarily mean you should get the same info when you read the current line. The former reports information about the object (label, etc.); the latter reports information about text. Gmail has set the label very specifically to best summarise the information.

It's a bug that read line reports nothing, but even if we fixed that (which will probably require a refactor of browse mode in Chrome), it would report a lot more information, more like what you get when you move to a message, switch to browse mode and repeatedly press down arrow to read the entire row.

**Comment by Adriani90** [comment]
@jcsteh  since there is a work around for this and the initial author is ok with nvda+tab, should this be closed as "won't fix"?

**Comment by jcsteh** [comment]
I'll close this, as even though the current behaviour is not ideal, the "fix" won't provide the behaviour the reporter was originally hoping for. Note that the behaviour is now consistent between Chrome and Firefox.
