### ISSUE TITLE
hwPortUtils.listComPorts: Querying PortName can fail

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#6015]
Originally reported by @mohdshara in [this nvda-devel thread](http://nabble.nvda-project.org/focus-Braille-Display-port-selection-td40371.html).

It seems that some com ports don't have a PortName registry value:

```
ERROR - unhandled exception (15:22:32):
Traceback (most recent call last):
  File "gui\settingsDialogs.pyo", line 1537, in onDisplayNameChanged
  File "gui\settingsDialogs.pyo", line 1544, in updatePossiblePorts
  File "brailleDisplayDrivers\baum.pyo", line 117, in getPossiblePorts
  File "hwPortUtils.pyo", line 192, in listComPorts
WindowsError: [Error 2] The system cannot find the file specified
```

Unless I'm missing something, this is broken, but clearly, it can happen. I guess we should just catch the error and skip the port.

**Comment by nvaccessAuto** [comment]
Incubated in 73ee6b2af4e464b91e803a8e53695cdb0b0f56ad.

**Comment by mohdshara** [comment]
Hi Jamie. Thank you very much. that indeed fixed the error for usp connection and the display works correctly. However, can you take a look at the attached log file when I attempt to connect via bluetooth?
[Nvda-log-bluetooth.txt](https://github.com/nvaccess/nvda/files/289519/Nvda-log-bluetooth.txt)

**Comment by mohdshara** [comment]
Wonderful! thank you very much for looking into it and for fixing the issue. confirmed, I can now connect through USP and bluetooth.

**Comment by mohdshara** [comment]
Hi. It may be worth noting here, that this happened to me on 3 different laptops. They are all made by Linovo and all have windows 10 64 bit. of course, this commit fixes the issues on all of them. what I am trying to say is that there maybe a pattern here.

**Comment by jcsteh** [comment]
That would suggest Lenovo are installing something that creates this issue. It'd be interesting to see a log file at level debugWarning covering selecting a Baum display with this new build on one of those computers. The build logs some info when it encounters this issue. There's nothing we can do about it, but seeing the log might give me some idea of what this actually is.

**Comment by mohdshara** [comment]
attached are the log files with a usp connection and another with a bluetooth connection. 

[nvda-log-bluetooth-lenovo.txt](https://github.com/nvaccess/nvda/files/291639/nvda-log-bluetooth-lenovo.txt)
[nvda-log-usb.txt](https://github.com/nvaccess/nvda/files/291642/nvda-log-usb.txt)
|

**Comment by jcsteh** [comment]
Looks like the problematic port is a modem, so it's not important. That's good.

However, I did notice you're connecting via Bluetooth by choosing a specific com port, rather than using selecting automatic 'as the port and letting NVDA detect. Is automatic not working for you with Bluetooth?

**Comment by mohdshara** [comment]
Hi Jamie.

I was manually selecting a port because that was what Baum suggested. however, I have just tried, and I found out that automatic will now work too.

Thanks for your help and for fixing the issue.
