### ISSUE TITLE
Newer Papenmeier displays slow reactions or no reaction at all to commands

### ISSUE THREAD

**Issue by ChrisDel35** [nvaccess/nvda#6018]
NVDA does not always respond to actions when the monocommand of the braille display is moved. For instance, in order to pan right, sometimes moving the monocommand one step right only once is sufficient. This is what is expected. However, I sometimes need to repeat the action three or more times in order to have the display panned.

**Comment by hss16** [comment]
Do you have another screenreader installed?
This is a known bug if you run nvda after an other screenreader was used before.
Try the following:
If the display responds slowly, unplug the usb cable for two seconds.
This should fix it!

**Comment by feerrenrut** [comment]
@ChrisDel35 Could you let us know if the workaround proposed by @hss16 worked for you?

**Comment by feerrenrut** [comment]
@hss16 You mention this is a known issue, do you know why this occurs? We are looking for any clues about how we might work around it.

**Comment by ChrisDel35** [comment]
Hello @hss16,

Many thanks for this workaround.

Yes, I am using another screen reader. Now it is Jaws 17 but when I noticed the problem on an older computer, it was Jaws 13.

With the old computer and Jaws 13, I don't remember this worked. Now, I don't have this old computer anymore. However, the good news is that on the new computer with Jaws 17, it seems to work like you described.

In other words, I switch Jaws off --> I switch NVDA on --> the braille display does not respond nicely --> I unplug the display for 2 seconds --> I plug it again --> it works fine.

Many thanks. ChD

**Comment by hss16** [comment]
Hi,
On Di, Nov 29, 2016 at 10:07:22 -0800, Reef Turner wrote:
> @hss16 You mention this is a known issue, do you know why this occurs? We are looking for any clues about how we might work around it.

Unfortunately I don't have an idea what causes this problem at this point.
The error was only there after using EG.: Jaws.
Maybe it does something bad with the usbserial converter which isn't documented.
Regards
