### ISSUE TITLE
nvda skipping text during read to end in firefox

### ISSUE THREAD

**Issue by westbrookc16** [nvaccess/nvda#6020]
I have noticed occasionally that nvda will skip text during a read to end in mozilla firefox.  Inlooking at the logs it appears that text is skipped when passed to the speak function.  I particularly noticed it on the following URL: https://warhornmedia.com/2016/05/25/eternity-etched/ Simply starting reading the article with nvda+a (I am using the laptop keyboard layout) and you will notice that partway through the article, text is skipped and sometimes text is repeated.  I have noticed this on other links as well, but it seems random and I can't reproduce at will.

**Comment by ehollig** [comment]
I am not able to replicate this. Could this possibly be related to #5339?

**Comment by jcsteh** [comment]
Sounds like the same issue. Closing as duplicate.
