### ISSUE TITLE
Windows 10/LogonUI: Cannot invoke password field via touch or object navigation

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#6024]
Hi,

A user reports that he cannot move to password field using touch (I was able to confirm this).

STR:

1. Create an account where you need to enter a password (a Microsoft Account will do).
2. At the logon prompt, try using TAB key to move to "submit" button (if using a touchscreen, move your finger to submit button).
3. Use object navigation to move to password field and try invoking it (NVDA+Numpad ENTER).

Expected: NVDA moves focus to password box.
Actual: Nothing happens.
Reproducible: Yes.

Setup:
* NVDA version: latest next build (13343).
* OS: Windows 10 Version 1511 (also reproducible in Insider build 14352).

Solution: Windows 10 has changed the name of the password box class name. The below commit adds this class name, as well as updating the copyright header for appModules/logonUI.py. Thanks.

**Comment by Brian1Gaff** [comment]
I was under the opinion that at this time on a boot up there is only basic 
support for speech running.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by josephsl** [comment]
Hi, I’m working on changing this impression via a private lab/branch. Thanks.

**Comment by jcsteh** [comment]
Merged in e3e83b22.
