### ISSUE TITLE
NVDA web page access

### ISSUE THREAD

**Issue by maruthikumars** [nvaccess/nvda#6026]
Hello All,

I'm working for Accessibility Project as developer, here I'm always caught by QA Engineers saying that not able to access web page using up&down arrows. 

I would like to know how and when we should use up&down arrows?

![log in screen issue](https://cloud.githubusercontent.com/assets/19667503/15676305/5b124e2c-2763-11e6-9515-96d688982e31.png)

It would be great if you guys help me out here. Thanks in advance!

**Comment by PratikP1** [comment]
Take a look at the following link to learn about how to test web pages for accessibility with NVDA. Additional material is also available if you do a search on “NVDA demo”
https://www.marcozehe.de/articles/how-to-use-nvda-and-firefox-to-test-your-web-pages-for-accessibility/

**Comment by jcsteh** [comment]
This is more of a support/usage question, rather than an issue report. This tracker is for the latter. See http://www.nvaccess.org/help/ for support resources. Thanks.
