### ISSUE TITLE
NVDA with x64 windows 10 PE environment

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#6031]
When using NVDA with a 64-bit version of the windows 10 PE  from [this page,](http://opopanax.net/download/) I've noticed the following:
- typed characters are not announced even when the appropriate option is enabled
- screen review does not work
- browse mode in firefox does not work

Is this a problem with NVDA, or is this being caused by certain components not being present in windows PE?

**Comment by ehollig** [comment]
CC @josephsl

**Comment by Adriani90** [comment]
@Neurrone are you still having this issue?

**Comment by Neurrone** [comment]
I'll test this again and report back.

**Comment by Adriani90** [comment]
@Neurrone any updates?

**Comment by ehollig** [comment]
Closing as stale
