### ISSUE TITLE
Object navigation around many dialog boxes in Office (2016 at least)

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6036]
When using Object navigation in various dialog boxes in Office, for instance the font dialog (control+d) or modify style dialog in Word (control+shift+s to open "apply styles" then tab to "Modify" and press enter), only some objects are accessible.

Initially I was trying to navigate around the modify keystroke dialog from the modify style dialog because when you enter a keystroke to assign to a style, there is a text label which notes whether the keys you have pressed are "Currently assigned to" anything else.  (press control+shift+s to open apply styles, then tab to modify and enter, then press alt+o for format and k for shortcut key).

**Comment by nvaccessAuto** [comment]
Incubated in 11382a94ef590232dbbc059657b8027daeb15942.
