### ISSUE TITLE
eSpeak NG in NVDA 2016.2 does not honor punctuation levels for som punctuation characters

### ISSUE THREAD

**Issue by mohammadrezarashad** [nvaccess/nvda#6037]
when I press NVDA+F12 for "say time", NVDA announced "colon" between numbers; even if I set the punctuation speeking to "none" for example, 13 colon 29. This problem also exists for closed parenthesis ")". Worst of all, when I set punctuation to all, NVDA reads one ) twice.
This problem occurs when I use eSpeak NG in Persian.
Finally, when I open the LogViewer of NVDA 2016.2, I see in line 14 the following:
Using eSpeak version 1.48.15  16.Apr.15
I have same abovementioned problems with eSpeak 1.48.15 on android, too.

**Comment by jcsteh** [comment]
We're definitely using eSpeak NG now, but the version it reports is incorrect. However, I'm guessing it is an earlier commit than the one which fixes the punctuation problem for Persian.

CC @MichaelDCurran. Note that @mohammadrezarashad explained elsewhere that the Persian contributor for eSpeak NG has apparently fixed this. So, hopefully we can update safely.

**Comment by michaelDCurran** [comment]
Latest eSpeak-NG master is now in NVDA next. Is the issue fixed when running a Next snapshot?

**Comment by mohammadrezarashad** [comment]
Hello dear friends,
The issue fixed successfully.
     thanks
     Mohammadreza

۱۳۹۵-۰۴-۱۷ ۳:۳۷ +۰۴:۳۰ گرینویچ, Michael Curran <notifications@github.com>:

**Comment by mohammadrezarashad** [comment]
Warning!:
Unfortunately, faulty eSpeak is now in NVDA snapshots again. Although the problem for eSpeak in Persian was fixed in next13392; but again falls back in master13414 and master13420.

**Comment by michaelDCurran** [comment]
The upgrade to latest eSpeakNG master has not made its way from NVDA 
Next to NVDA master yet.


This should happen in a week or so.


Thanks

Mick



On 14/07/2016 4:04 AM, mohammadrezarashad wrote:
>
> Warning!:
> Unfortunately, faulty eSpeak is now in NVDA snapshots again. Although 
> the problem for eSpeak in Persian was fixed in next13392; but again 
> falls back in master13414 and master13420.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/6037#issuecomment-232438056>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ANf5nfamBdAJNZHHBAEbsAQTvIEh8S4Wks5qVSiqgaJpZM4ItWSa>.
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by mohammadrezarashad** [comment]
Thanks so much!
     Good Luck!
     Mohammadreza

۱۳۹۵-۰۵-۰۴ ۲:۳۳ +۰۴:۳۰ گرینویچ, Michael Curran <notifications@github.com>:
