### ISSUE TITLE
IFrame vs Frame

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#6047]
NVDA announces frame in Internet Explorer, but IFrame in Mozilla Firefox. Is this an error on NVDAs part? Can the two be aligned to say the same thing when frames are encountered?

**Comment by PratikP1** [comment]
Can you please provide example page/pages?

**Comment by fisher729** [comment]
A good example is on
http://www.freedomscientific.com/Training/Surfs-Up/Frame-Example.htm
Try it in multiple browsers and see the difference.

**Comment by jcsteh** [comment]
Here's what needs to be done here:

1. Change the role for frames in IE to ROLE_INTERNALFRAME.
2. Change the label for ROLE_INTERNALFRAME to "frame", since "IFrame" probably doesn't make a huge amount of sense to users.

**Comment by JamaicanUser** [comment]
Oops. There is a spelling error in the English documentation. Across only has one 'c'.
