### ISSUE TITLE
Image map is ignored in browse mode

### ISSUE THREAD

**Issue by cyberseraphic** [nvaccess/nvda#6051]
Example page:
http://www.qantas.com/travel/airlines/walkabout/us/en

Below the tab navigation bar (Nature & Wildlife, ... , Videos) there is an image map with 4 links. Using Tab key on the keyboard to navigate the page results in each of the links being read and achieving focus.

Using the arrow key to navigate the page however, results in the image map links being ignored completely. One expects that it would also read the links.

The behaviour was observed on NVDA 2016.1 and Firefox 46 / Internet Explorer 11.

**Comment by feerrenrut** [comment]
Can reproduce with FireFox 47.0.1. In Chrome I get the following output from NVDA when moving with the down arrow:

```
heading  level 2
Nature & Wildlife
link
d787
link
d4863-ttd
link
d5598-ttd
link
en
heading  level 3
Use our multi-city booking engine to search and book your flights from the US to over 
```
