### ISSUE TITLE
add backspace key binding to refreshabraille18

### ISSUE THREAD

**Issue by coltonhill01** [nvaccess/nvda#6054]
I have noticed that the refreshabraille18 does not have any binding for the backspace key, however it does have enter and the arrows. I'm wondering if you could make it possible for say b7+b9, or dot7 chord to be used as a backspace such as on IOS.

**Comment by josephsl** [comment]
Hi,

See issue #5090. Thanks.

**Comment by jcsteh** [comment]
See also #2439, #2945, #5959.
