### ISSUE TITLE
In Microsoft Excel 2007 ExcelDropDownItem reading issue

### ISSUE THREAD

**Issue by dnz3d4c** [nvaccess/nvda#6056]
STR:
1. Open attach File
2. Move to A4 Cell then press Alt+Down

Expected Results:
1. NVDA speaks: JAWS (For 

Actual Results:
1. NVDA speaks: JAWS (For Windows)

Please check Issue. Thanks!
[sample_ExcelDropDownItem.xlsx](https://github.com/nvaccess/nvda/files/305771/sample_ExcelDropDownItem.xlsx)

**Comment by Adriani90** [comment]
@dnz3d4c are you still able to reproduce this issue? I think I can reproduce it in Excel 2016 but not in Excel 2010.

**Comment by Adriani90** [comment]
@dnz3d4c are you still available?

**Comment by Adriani90** [comment]
This is not reproducible now with NVDA 2023.1 or NVDA last alpha and Microsoft Excel 2016 or 365. I am closing as works for me.

Please comment on this with updated steps to reproduce in case you still have this issue and we can reopen.
