### ISSUE TITLE
IE11+NVDA reads text hidden with display:none inside form labels

### ISSUE THREAD

**Issue by smashuu** [nvaccess/nvda#6058]
See the attached HTML file for a demonstration. The markup is simple; when navigating to the checkbox, IE will read "Hidden Text Visible label" whether the input is inside the label or associated with `for=""`.

`<label>`
`<input value="1" type="checkbox">`
`<span style="display: none;">Hidden text</span>`
`<span>Visible label</span>`
`</label>`

Possibly similar to #3281 or #3776?

[IE11_NVDA_labels.zip](https://github.com/nvaccess/nvda/files/307381/IE11_NVDA_labels.zip)

**Comment by HerinHentry** [comment]
I am able to reproduce the same issue in Chrome when the shortcut keys F is used to traverse through form elements.

**Comment by Adriani90** [comment]
Might also be Related to #5833

**Comment by Adriani90** [comment]
I am closing this issue as abandoned, given the missing updates from the initial author for so long time, and given that support for Internet Explorer has actually ended in 2022. The IE mode in Edge for backwards compatibility will be available until at least 2029, but I don't think that accessibility improvements will occur in that regard.
In Firefox, Edge and Chrome everything works as expected.
