### ISSUE TITLE
Inaccessible features treeview in Microsoft Office 2010 custom setup

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#606]
**Reported by Agent Golder on 2010-03-25 10:14**
I just noticed that in some situations such as the Microsoft Office 2010 custom setup, features treeview can't be read normally but only using object navigation which sometimes is difficult to perform actions.
While of course, with Jaws anything gose normally.
Why is this? Can a fix be made?

**Comment by leonardder** [comment]
Office 2010 is obsolete, so if this still occurs and it is Office 2010 specific, I doubt it will ever be fixed

**Comment by Adriani90** [comment]
@Agent Golder can you still reproduce this issue in Office 2010? I have installed Office 2010 on my machine but I am not able to reproduce it. However I am not sure.

**Comment by Adriani90** [comment]
We do not have an update from the author since 9 years or so. I am closing this one but feel free to comment on it if you are still having this problem. We can reopen the discussion afterwards. Thanks.
