### ISSUE TITLE
Mapping more braille display keys by default on Hims braille displays

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6063]
As an employee at Babbage (the Netherlands), I've talked to BrailleEdge customers who are interested in more default key mappings for the Hims Braille driver. For example, several keys lack mappings by default, while they are mapped to emulated system keyboard keys in other screen readers.

I might be able to work on this either in work or spare time, so feel free to assign this issue to me. I wil also investigate the SmartBeetle. Though if the main devs aren't interested in those additions, let me know.

**Comment by jcsteh** [comment]
Very happy for you to work on this. If you do, please update the User 
Guide as you go.

Some users seem to be experiencing an issue where Braille EDGE keys 
don't seem to be recognised by NVDA at all. Have you heard 
of/experienced this?

**Comment by leonardder** [comment]
## Findings so far

### SmartBeetle
* advance2=4 
* Advance 3=3 
* Advance 4=2
* right scroll up = scroll up
* right scroll down = scrolls, but no label in NVDA

**Comment by leonardder** [comment]
## Findings so far

### SmartBeetle
* advance2=4 
* Advance 3=3 
* Advance 4=2
* right scroll up = scroll up
* right scroll down = scrolls, but no label in NVDA

**Comment by leonardder** [comment]
Following my last message, it seems that hims scroll buttons are sometimes not being detected properly. Buttons which are not assigned in the driver should be distinguished by their hex code instead of an empty string.

**Comment by leonardder** [comment]
I've been able to add the smart beetle scroll buttons, which weren't recognised by the current driver. Added a warning message for intercepting unrecognised keys in the except keyError clause, which also contains a pass. Not sure whether we want to pass unrecognised keys though, as they have no name.

**Comment by leonardder** [comment]
While working on this issue, I've got points I'd like to discuss with others like @jcsteh, @dkager, @bramd and @roelvdwal .

Several Hims displays have function keys, named advance keys. The Smart Beetle has Advance1--4, the Braille Edge even has 8.
As @roelvdwal noted, the advance keys are meant to be control, windows, alt and home on the Smart Beetle, according to its manual. However, the Braille Edge advance keys are meant to be Esc, Tab, Ctrl, Alt, Shift, Insert, Windows and applications according to its manual. In other words, assignments suggested by Hims are inconcistent.
Thereby, function keys aren't additive, so when advance1 is ctrl and advance2 is shift, pressing advance1+advance2 doesn't automatically mean ctrl+shift.

1. What do you think about using the assignments in the Edge manual? This means that displays with only four advance keys (smart beetle) have Esc, Tab, Ctrl and Alt.
2. What should we do with combinations like advance1+advance2+advance3. This combination is assigned to shift+alt+tab at the moment of writing. Should we keep it that way, or change the stacked key combinations following the assignments above? For the advance1+2+3 combination, this would result in escape+tab+ctrl, which makes no sense at all.

**Comment by dkager** [comment]
Consistency sounds, well, consistent. From my point of view layered keys should accumulate their individual components, e.g. Alt+Tab should be achieved by pressing Alt and Tab. But I have never used a Hims display so maybe this makes no sense if you use the device, for example because it is hard to press certain keys together. What are you going to do with the braille keyboard, if any?

It may also be worth communicating your changes with Hims so they can update their manuals. I'm doing that with the Alva displays (PRs pending).

**Comment by roelvdwal** [comment]
The smart beatle has a keyboard mode, wherein you can directly use the braille display as a bluetooth keyboard. I don't know if other displays from hims have a similar feature, but for the smart beetle, a sollution would be to just copy that layout. Also on a related note, How do you obtain hex values for keys on the braille display? When pressing them in input help they say nothing, and when setting them in input gestures I also get a blank string. I also tried reading the serial port directly, but when converting those values from ASCII to hex I don't get the right values either.

**Comment by leonardder** [comment]
> The smart beatle has a keyboard mode, wherein you can directly use 
the braille display as a bluetooth keyboard. I don't know if other 
displays from hims have a similar feature, but for the smart beetle, a 
sollution would be to just copy that layout.

That is interesting, I should test that feature next week.

 > Also on a related note, How do you obtain hex values for keys on the 
braille display? When pressing them in input help they say nothing, and 
when setting them in input gestures I also get a blank string. I also 
tried reading the serial port directly, but when converting those values 
from ASCII to hex I don't get the right values either.

Check brailleDisplayDrivers.hims.InputGesture.__init__. The hexcode to 
key name assignments are in HIMS_KEYS, some of those are missing.

**Comment by bramd** [comment]
@leonardder I'm not very familiar with the Hims displays. That being said, if a display has a set of buttons on approximately the same place in the same layout, I would expect the same functions. You might ask Hims for the difference, there might be a good reason. However, giving my experience with them I found communicating always somewhat difficult.

**Comment by leonardder** [comment]
We (@babbagecom) have received a new [HanSoneConnect](https://github.com/nvaccess/nvda/files/329992/HanSoneConnect-NVDA.zip) from Hims.
Would be great if someone can update this dll in miscdeps. It seems stable and fixes a major SmartBeetle issue, namely that both scroll keys could obtain 2 different key values rather than just one.

**Comment by josephsl** [comment]
Hi, we may need to run it through a try build phase then. Thanks.

**Comment by josephsl** [comment]
Follow-up: besides this fix, have you noticed any other changes? Thanks.

**Comment by leonardder** [comment]
Not as of yet, and as far as I know, there aren't other changes
      documented.

**Comment by leonardder** [comment]
Another relevant point:
Several hims displays have four scroll keys, two on the left and two on the right side of the display. Currently, nvda assigns both left keys to either scroll backwards or move to the previous line. NVDA assigns both right keys to either scroll forward or move to the next line. However, the Hims displays themselves as well as other screen readers use left and right scroll up to scroll back, and left and right scroll down to scroll forward. Should we keep it as it is now, or should we bring things in line with the internal Hims functionality and other screen readers?

**Comment by cskchao** [comment]
I can only speak of the Braille Sense U2 (perkins model), but much appears to be broken/otherwise unaddressed in terms of problems with keys on HIMS devices being unrecognized/randomly disabled. In case this proves relevant/helpful, much of this is documented in issues #5063 and #3157

**Comment by leonardder** [comment]
Another customer of us reported the problem with the Smart Beetle. While work on this is still in progress (it is to be decided while investment will be made to create a native driver), it would be very helpful if [the new dll](https://github.com/nvaccess/nvda/files/329992/HanSoneConnect-NVDA.zip) could be included in miscdeps, eventually in NVDA 2016.4.

**Comment by jcsteh** [comment]
@feerrenrut: Can you please look into updating HanSoneConnect.dll in miscDeps? The new file is provided above. Note that this update doesn't *fix* this issue, but it does address part of it. Thanks.

**Comment by feerrenrut** [comment]
Due to the issues in #6436, #6334 has been backed out. These means that the updated HanSoneConnect.dll is not included in NVDA.

**Comment by Piciok** [comment]
As a part of the issues with Hims displays, I would like to add that on my Braille Edge none of the chords involving space and dot 4 seem to be working. So far I have tested down arrow (space+4) as well as tab (space+45);
Also agree more keys and the ability to perform key combinations should be added. Will it include modifiers +Letters E.G> ctrl+n, Alt f, ctrl+win+t etc?

**Comment by jage9** [comment]
I've been playing a bit with a Smart Beetle and NVDA and it seems like it may make sense to separate the Beetle and perhaps others from the catch-all Hims driver for a couple of reasons.
* As mentioned above, the scroll keys are currently not accurate and do not perform matching functions. They should probably pan forward and backward and another command added to move by line. The Beetle only has 2 while other displays have 4.
* The Beetle should take the keys from the Hims BT keyboard layout and assign them to F1 through F4. These are control, windows, alt and home. Escape, for instance, does not need a dedicated key as the current space with E works fine for this and you would not normally press escape as a modifier.

Has there been any contact with Hims directly about them writing their own driver to better support the Beetle? In reality, it just needs a better set of key bindings. For the moment, fixing the scroll issue would be a good start.

**Comment by leonardder** [comment]
> it seems like it may make sense to separate the Beetle and perhaps others from the 
> catch-all Hims driver for a couple of reasons.

Hmm, all the hims products are using the same dll to communicate. We 
already have separate key assignments for braille edge and braille 
sense, so this shouldn't be a problem.

>   * As mentioned above, the scroll keys are currently not accurate and
>     do not perform matching functions. They should probably pan forward
>     and backward and another command added to move by line. The Beetle
>     only has 2 while other displays have 4.

This is also a point where the hims dynamic link library has a bug. We 
have received a new library from them, but that one contains 
undocumented device identifiers and its incumation in next has been 
reverted.

>   * The Beetle should take the keys from the Hims BT keyboard layout and
>     assign them to F1 through F4. These are control, windows, alt and
>     home. Escape, for instance, does not need a dedicated key as the
>     current space with E works fine for this and you would not normally
>     press escape as a modifier.

I agree there.

> Has there been any contact with Hims directly about them writing their 
> own driver to better support the Beetle? In reality, it just needs a 
> better set of key bindings. For the moment, fixing the scroll issue 
> would be a good start.

It seems that Hims isn't interested in contributing to NVDA directly.

**Comment by leonardder** [comment]
[**@jage9**](https://github.com/jage9) commented on [24 mei 2017 02:57 CEST](https://github.com/nvaccess/nvda/issues/6063#issuecomment-303583719 "2017-05-24T00:57:20Z - Replied by Github Reply Comments"):
> * The Beetle should take the keys from the Hims BT keyboard layout and assign them to F1 through F4. These are control, windows, alt and home. Escape, for instance, does not need a dedicated key as the current space with E works fine for this and you would not normally press escape as a modifier.

Actually, I think this can be done in one driver, without having separate ones. I opened #7458 and I can do this as a part of it.
