### ISSUE TITLE
Braille scrolling not intersepted by input help

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6064]
Steps to reproduce:
1. Attach a braille display to the pc and connect it to NVDA
2. Enable input help
3. Press a key on the display which is associated to braille_scrollBack. You can also assign this command to a keyboard key

Expected result: NVDA should report the key input as well as the "scrolls the braille display back" message
Actual result: NVDA scrolls the braille display and doesn't report anything

This also applies to scrolling the display forward.

**Comment by jcsteh** [comment]
We don't do this (and don't want to do it) because that would make it impossible for a user to scroll to read the rest of a long input help message, particularly on a small display (e.g. 18 cells).
