### ISSUE TITLE
possible invalid role when tabbing into a labeled region.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6085]
1. Run this minimal test case. https://files.derekriemer.com/6084.htm 
2. Press "A"
    It reads the paragraph in B.
3. Press "b"
    It goes to the A paragraph inside the region and voices it as expected.
4. Press "a" again, but make sure you are in focus mode. Notice it says grouping as it should.
5. Now shift tab to B and press it. You should still be in focus mode. Notice how it reports "the region" which has a role of region as a grouping instead.

**Comment by jcsteh** [comment]
Grouping is the correct role for region according to ARIA specs. Note that we don't treat landmarks/regions specially when in focus mode. Roles and landmarks are different beasts.
