### ISSUE TITLE
no previous object in windows start menu

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#609]
**Reported by aleksey_s on 2010-03-30 13:42**
## steps to reproduce
- open start menu
- press nvda+numpad2
- navigate to the "programs" submenu with nvda+numpad6
- press nvda+numpad4
  ## current results

NVDA says "no previous object"
## expected results

NVDA must gracefully navigate to the previous item in the menu (a delimiter)
## additional info

I have classical start menu.

**Comment by leonardder** [comment]
This bug is related to Windows XP. Won't fix?
