### ISSUE TITLE
ConfigObj: use option flag for certain items

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#6090]
Hi,

First of a series of suggestions on modernizing configuration infrastructure and sort of goes alogn with removing deprecated config functions:

In ConfigObj, there is a way to restrict options to specific values using the option flag. The syntax is:

key = option("x", "y", default="x")

There are certain items in NVDA's confspec that could utilize this. The one that comes to my mind is progress bar output (currently using string check). I think this is something a potential new dev could work on this after we know for sure which options could be modified to take advantage of this.

Thanks.

**Comment by leonardder** [comment]
I think enhancements could be made to the following options:

     [general]
         loggingLevel
     [speech]
         symbolLevel
     [audio]
         audioDuckingMode: needs restrictions
     [braille]
         tetherTo
     [[progressBarUpdates]]
         progressBarOutputMode
         speechPercentageInterval: needs restrictions
         beepPercentageInterval: needs restrictions
         beepMinHZ: needs restrictions
     [mouse]
         mouseTextUnit
         audioCoordinates_blurFactor: needs restrictions
         audioCoordinates_min/maxVolume/Pitch: needs restrictions
     [keyboard]
         keyboardLayout
     [virtualBuffers]
         maxLineLength: needs restrictions?
         linesPerPage: needs restrictions?

**Comment by derekriemer** [comment]
Hi:

With intervals: These are intervals, I.E. any number between x and y.


On 6/18/2016 4:57 AM, Leonard de Ruijter wrote:
> I think enhancements could be made to the following options:
>
>       [general]
>           loggingLevel
>       [speech]
>           symbolLevel
>       [audio]
>           audioDuckingMode: needs restrictions
>       [braille]
>           tetherTo
>       [[progressBarUpdates]]
>           progressBarOutputMode
>           speechPercentageInterval: needs restrictions
>           beepPercentageInterval: needs restrictions
>           beepMinHZ: needs restrictions
>       [mouse]
>           mouseTextUnit
>           audioCoordinates_blurFactor: needs restrictions
>           audioCoordinates_min/maxVolume/Pitch: needs restrictions
>       [keyboard]
>           keyboardLayout
>       [virtualBuffers]
>           maxLineLength: needs restrictions?
>           linesPerPage: needs restrictions?
>
>
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6090#issuecomment-226935647

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by josephsl** [comment]
Hi,

There are options that are pulled in from module-level constants (such as keyboard layout), changed from somewhere else (logging level) and others. I think the safest one for now would be progress bar output option (and if possible, braille tether unless we get a word that this is also pulled from constants in braille module).

Thanks.

**Comment by jcsteh** [comment]
I'd ask you to consider several questions here:

1. Why make this change? What advantage does it provide? Remember, users are not supposed to manipulate config.conf or the config file directly; that is not officially supported.
2. Is each change backwards compatible? If the setting is an existing setting, it must accept the same values that will already be present in user configurations.

Any change like this needs a lot of testing and any mistake could break a user's configuration. So, if there isn't a very good reason to do it, it just shouldn't be done.

**Comment by josephsl** [comment]
Hi,

1. When saving to a file, ConfigObj will convert it to a string, thus preserving backward compatibility.
2. Using option check/flag allows developers to carefully consider options available and is useful to picture options that users would choose from a list.
3. By limiting options for a key, it allows NVDA to detect faulty config value early (at load time) as opposed to at runtime when settings are looked up (or settings dialogs are opened).

Points to consider:

* There are combo box items where we do need to leave corresponding checks as strings.
* Compatibility with previous checks: because ConfigObj will convert option items to strings (internally), existing routines will continue to function.
* Change of type: what if options (as in settings) are combined/split, potentially creating Booleans and other types? Highly unlikely, but this should be taken into consideration later.
* @jcsteh is right: a lot of testing should be done (maybe several months) to make sure it is working as advertised.

Note that this suggestion applies to confspec, not nvda.ini (as noted above). Thanks.

**Comment by leonardder** [comment]
I'm adding a new option to the config spec in #217, which now utilizes an integer value. However, I"m leaning towards a string based value following https://github.com/nvaccess/nvda/pull/7236#discussion_r123340945 . That's why I'm coming back to this ticket, since Ie belief option will be better than string. Since @jcsteh had a good rationale in https://github.com/nvaccess/nvda/issues/6090#issuecomment-227610984 for not changing current values to option, choosing option for #217 would break concistency somehow.

**Comment by jcsteh** [comment]
My rationale for not doing this only related to the fact that this is
existing code that's been in use in the wild for many years now. It
certainly makes sense to use this for newer options. Yes, it's
inconsistent, but that's the nature of such things in a code base with a
reasonably long history. :) To put this another way, option should probably
become the new (consistent) convention for stuff like this in future.

**Comment by Adriani90** [comment]
@josephsl, @Andre9642 are you still working on this? I guess this should be considered while moving to Python 3 as well.

**Comment by feerrenrut** [comment]
Following on from https://github.com/nvaccess/nvda/issues/6090#issuecomment-310289381 I'm going to close this issue. As far as I can tell the changes mentioned on this issue only introduce risk. This is certainly more complicated than it initially appears. For instance, when a new range of valid values is introduced one must handle the case where the config is outside of those values. This will require config upgrade code.

For new options, or if the change is required to fix an existing bug certainly use the features of ConfigObj. 
If anyone wants to pursue this idea further, it would be helpful to add documentation on the "best practice" with config spec in NVDA to the wiki / developer guide.
