### ISSUE TITLE
Unable to read styles in Table of contents options in Word 2016

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6091]
Using Word 2016 and either NVDA 2016.2.1 or NVDA Next 13363,24458af3

From a blank document:
1. Open References ribbon (alt+s)
2. Choose table of contents (t)
3. Choose custom table of contents (c)
4. Press options button (alt+o)

From this screen you can select which styles correspond to which heading levels when building a table of contents.  After the "styles" checkbox, visually there is a column of text labels with heading 1 - 9, then any other styles in use in the document.  to the right is a column of edit boxes.  By default the first three are filled in 1 - 3 (heading 1 = TOC level 1 etc).

As you tab from the initial style checkbox, you move through the first six edit boxes, with each announced as "Style 1", "Style 2" etc, not actually what style they correspond to.

After the sixth edit box (the last one visible on screen), the next tab moves to the scroll bar, which can be manipulated with the navigation keys.  Pressing shift+tab then moves back to the last edit box which is currently visible on screen and NVDA announces "style 6 edit", regardless of what style it is and even though it may not be the same edit box previously announces as "style 6".

The text labels to the left of the edit boxes have a "tick" check mark next to them if the corresponding edit box has a numerical value.

**Comment by jcsteh** [comment]
@MichaelDCurran

**Comment by michaelDCurran** [comment]
Reported to Microsoft. Tracked as MS Office bug 806706.
