### ISSUE TITLE
Treat cross-references in Word as links.

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6102]
Word can have cross-references - links to other parts of a document (headings, list items, bookmarks, footnotes, etc).  In Word 2016 you create these by pressing alt+s then r then f which opens a dialog box you can setup the exact link from.

The result is a field, code something like:

{ REF _Ref454364297 \h }

which also creates that _Ref454.... bookmark in the appropriate place (a heading in this example)

As this is really a "link", it would be good if NVDA Browse mode could recognise it as a link for navigating.

Note that part of this (and perhaps partly why it isn't already) is that there is currently no keystroke to activate the link - sighted users can hold control and click on the field - as with other links - however enter does not work in this case, it actually doesn't do anything at all and there is currently no other keystroke to activate it.

**Comment by jcsteh** [comment]
@MichaelDCurran

**Comment by feerrenrut** [comment]
@Qchristensen A fix for this is now incubated. When you get a chance could you please test out cross references and hyperlinks on your versions of word (2007 / 2016)?

Next build:
https://ci.appveyor.com/project/nvaccess/nvda/build/next-13500,595afe6e/artifacts
