### ISSUE TITLE
Windows 10 Build 14352 or later: tabbing through Start menu causes NVDA to announce navigation pane item before realizing that you are back at search field

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#6107]
Hi,

Quite an annoying problem in recent fast ring builds: tabbing through Start menu elements and returning to search field causes NVDA to announce navigation pane item again.

STR:

1. Using whatever fast ring you have (14371 will do), open Start menu.
2. Press TAB to navigate through start menu elements until you arrive back at search field.

Expected: NVDA announces, "Cortana window".
Actual: NVDA says, "navigation menu list" before announcing the fact that you are in search field.

Setup:

* OS: Windows 10 build 14371 (fast ring)
* NVDA version: next.13366.
*Reproducible: almost all the time.
* Happens with Narrator: no.

Additional notes:

* Narrator does not announce "navigation menu list" when you tab back to search field.
* Accessibility Event Checker (accevent.exe) says a UIA focus event is fired for navigation pane item (automation ID of NavigationPaneHamburgerButton) before noticing that search field told UIA that it has fired its own focus event.
* This does not happen when you press Shift+TAB to move backwards.
* Might be an odd UIA server implementation provided by SearchUI.exe or something odd is going on in our client routines.
* Feedback sent to Microsoft via Feedback Hub.

Thanks.

**Comment by jcsteh** [comment]
I couldn't reproduce this in 14361 and can't reproduce it in 14372. I'm guessing there is some timing issue at work here. I haven't checked with AccEvent yet.

**Comment by josephsl** [comment]
Hi,

Improved in 14379: when Start menu is opened the first time, navigation pane is shown. Subsequent invocation only displays search box and shortcuts bar. Will keep an eye on this until 1438x build comes out. Thanks.

**Comment by josephsl** [comment]
Hi,

Found a way to consistently reproduce this from my end:

1. Open Start, type something.
2. Reopen Start and press TAB to move through it.
3. Close Start, then open search window (Windows+S), then close it.
4. Press Start menu. The full menu appears. Then press TAB to move through components.

Thanks.

**Comment by josephsl** [comment]
Hi,

Cannot reproduce this in build 14393, so closing (will reopen if RS2 exhibits this behavior again). Thanks.
