### ISSUE TITLE
Microsoft Edge and browse mode

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#6108]
I have redefined some navigation keys for browse mode.
For example, I have set "get next heading" to "t" instead of "h".
my changes work for Firefox, Internet Explorer or Chrome, but are not taken in count under Edge.
Does NVDA use a different browse mode mechanism under Edge?

**Comment by derekriemer** [comment]
What's the purpose of changing the keys used?

**Comment by jcsteh** [comment]
Please provide the content of your gestures.ini file.

CC @MichaelDCurran.

**Comment by ehollig** [comment]
@MichelSuch, just a friendly reminder to respond to @jcsteh in https://github.com/nvaccess/nvda/issues/6108#issuecomment-229545021

**Comment by Adriani90** [comment]
@MichelSuch are you still available?

**Comment by josephsl** [comment]
Hi,

Er, any update from the original poster? If not, I'm really tempted to close this.

Thanks.

**Comment by feerrenrut** [comment]
Given that #9142 was also opened by @MichelSuch and seemed to be reporting the same issue (11 Jan 2019) I would guess it is still affecting them.

I am unable to reproduce the issue with:

**Microsoft Edge 44.18362.1.0**
**Version: beta-18022,dc5c0b8c**

Steps I took:
1. In the input gestures dialog, browse category, find "moves to next heading"
1. Focus "h" item
1. Press `alt+R` to remove
1. Press `alt+A` to add
1. Press "t" to set t as the gesture.
1. Open edge and try to use t to move to the next heading.

If someone has some other version of Edge, could you please try this out.

**Comment by Adriani90** [comment]
I performed the steps described by Reef above and I cannot reproduce this issue in NVDA 2019.3 Beta 1 on Windows 10 1909 Update. Closing as works for me.
