### ISSUE TITLE
Upgrade to LibLouis 3.0.0

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#6109]
Hi,

LibLouis 3.0.0 includes promising features, namely vastluy improved emphasis handling, next generation UEB table set and others. at the moment version 3.0.0 has entered alpha testing phase:
https://github.com/liblouis/liblouis/releases/tag/v3.0.0.alpha1

Important things to note:

* A new file named "pattern.c" is introduced that handles various patterns. Without including this file, MS Linker says unresolved symbols.
* We need to test UEB table set to make sure it is more compliant to the standard.
* A lot of testing will be required to make sure braille tables aren't broken and that NVDA can handle them well.

Thanks.

**Comment by dkager** [comment]
I'm not sure how much of the UEB stuff works with the pass1Only flag. Same for other languages. Ideally testing should be done before the final release, e.g. on the alphas. These shouldn't be less stable than regular releases. It's mostly the tables that need verification. Maybe a bold step, but we could incubate an alpha into next.

**Comment by jcsteh** [comment]
Yup, incubating alpha into next is the plan. However, we won't put an 
alpha into 2016.3; we're just incubating so it gets longer exposure.

**Comment by dkager** [comment]
The alpha should become final release in a few weeks.
