### ISSUE TITLE
LibreOffice Online - CollaboraCloud suite support

### ISSUE THREAD

**Issue by vsfoote** [nvaccess/nvda#6111]
Navigation within the Web based Collabora Online offering of CollaboraCloud Suite (aka LibreOffice Online) is a mess.  https://www.collaboraoffice.com/

Found no means of moving by keyboard between the Menu, the Toolbar and the Document canvas.  The F6, F10 keys of the desktop version are held by the browser (Firefox). Have to hunt with mouse.

When in the document-- most content is announced as editable multiline "blank".  OK to Not our Bug this I guess--but wonder if when this cloud serving Web hosted Office suite gets going NVDA is going to need a Python module dedicated to it?

**Comment by vsfoote** [comment]
This is open on the LibreOffice BZ as tdf#100530 -- https://bugs.documentfoundation.org/show_bug.cgi?id=100530

**Comment by jcsteh** [comment]
It's not currently possible to implement website specific plug-ins. Even if this were possible, it's unlikely that we'd be able to "hack" decent support for something as complex as this. If content isn't exposed, we can't get at it, and if the project is going to expose it, it may as well do it in an accessible way. The TDF bug suggests there is a lot of use of canvas, which does not bode well unless they provide alternative content.
