### ISSUE TITLE
Setting focus to empty element reads blank

### ISSUE THREAD

**Issue by jamessetaro** [nvaccess/nvda#6114]
I've got a couple elements like this at the top of my page:

<div id="loading-status" class="visuallyhidden" aria-live="assertive" aria-atomic="true">Question page load complete</div>

<div id="firstTabbable" tabindex="-1">   </div>

...lots more stuff below.

That I use to set focus to when I clear the page in a single page app in FF.  If I don't set focus then eventually FF and NVDA lose sync about where they are.

Steps
Update the loading-status
Set focus to firstTabbable.
NVDA reads Question page load complete BLANK

I don't understand why setting the focus to div firstTabbable is read as blank. Its empty and only used as a placeholder(since focus really can't be anywhere else).  Using aria-hidden and role=presentation don't seem to do anything.  It as if its still read because focus is set there.

**Comment by oliverfoster** [comment]
make it more verbose. put "Loading content" in it, or something to let the use know what's going on,

**Comment by jcsteh** [comment]
I understand what you're trying to do here. However, I don't think it makes sense to focus something empty and definitely not something hidden. Focus is pretty fundamental for a screen reader user, so NVDA will always report focus in some way. Even if we made a decision that "blank" wasn't useful, we'd still want to report the role or similar, which is also not what you want.

I'd suggest focusing something at the top of the page that has useful content; e.g. a heading or similar.
