### ISSUE TITLE
adding USB Hid support to BAUM braille displays Vario 340 and SuperVario2 

### ISSUE THREAD

**Issue by pavel46** [nvaccess/nvda#6116]
on a SightCity exebision in Frankfurt Germany BAUM introduced a new 40 cells braille display Vario 340.  this new braille display is supporting only USB HID connection. additionally, Baum has also another braille display model SuperVario 2. this braille display is supporting USB cirial port connection, bluetooth and USB HID connection. currently existing driver for the BAUM braille displays is not supporting Vario 340. it is supporting SuperVario 2  Vi USB cirial port and via bluetooth, but it doesn't support this display via USB HID. so i'm asking to add support for the USB HID connection for Vario 340 and  for SuperVario 2. 
for SuperVario 2 and humanware brilliant models produced by BAUM  i found following USB HID  idis:
  6001 hex  
 SuperVario2 40  
 
  6002 hex  
 SuperVario2 24  
 
  6003 hex  
 SuperVario2 32  
 
  6004 hex  
 SuperVario2 64  
 
  6005 hex  
 SuperVario2 80  
 
  6006 hex  
 Brailliant2 40  
 
  6007 hex  
 Brailliant2 24  
 
  6008 hex  
 Brailliant2 32  
 
  6009 hex  
 Brailliant2 64  
 
  600A hex  
 Brailliant2 80  
 for Vario 340 i found following USB HID idies:
Vario340 ="0x6201" 

    
  6010 hex

**Comment by jcsteh** [comment]
Thanks for the info. A few questions:

1. Looking at BRLTTY, it seems the vendor id is 0x0904 as with most other Baum displays. However, I'm unclear about the vendor id for the Vario 340. You wrote two numbers: 0x6201 and 0x6010. 0x6010 looks like it's probably the product id (and I'm guessing the vendor id is 0x0904, but what's 0x6201?
2. HumanWare now produce their own Brailliant B displays. My understanding was that Baum were no longer producing Brailliant displays. So what's the story with the Brailliant2?
3. Is Bluetooth auto detection working correctly for the SuperVario2? Do we need to add additional Bluetooth names for it?
4. Is Bluetooth auto detection working for the Brailliant2? Do we need to add additional Bluetooth names for it?

**Comment by jcsteh** [comment]
Another question: you mentioned that the SuperVario2 supports USB serial. Do you mean you can switch it to USB serial mode instead of HID? If so, does auto detection work or do you need to select the serial port manually in NVDA? if auto detection doesn't work, is the USB product id the same when using USB serial mode? (Often, the product id is different between these two modes.)

**Comment by pavel46** [comment]
Hi Jamie. 

Regarding the questions in your first mail my colleague provides following    infrhmation:

1.       The vendor ID of the Vario 340 is 0x0904, like all current BAUM USB products. 0x6201 is the product ID of Vario 340. 

2.       The Brailliant2 is a customized SuperVario2, like the “Brailliant” is based on “SuperVario”. I do not know if or how many of them are sold to HumanWare. Of course, they have now the Brailliant B. I was not able to get the information how many of them are delivered to HumanWare, but surely it is just a handful. 

3.       The BlueTooth-Name of “SuperVario2” is the same than the current response of “SuperVario”. So a BT AutoDetection that works with a “SuperVario” with actual firmware should work also with a “SuperVario2”.

4.       The same like above, autodetect should just work.

 

Regarding the question in your second email , yes I have to go into the advanced menu of the braille display  and select USB instead  USB HID chennal. The autoditaction  usually works well.

With kind regards.

Pavel.

**Comment by jcsteh** [comment]
Thanks! So what is 0x6010 with regard to the Vario 340?

**Comment by pavel46** [comment]
Hi Jamie. May be it was written by mistake there. The id of Vario 340 should be 6201.

Best regards.

Pavel.

**Comment by jcsteh** [comment]
Here is a [try build with support for these displays](https://ci.appveyor.com/api/buildjobs/yxpnj7xx9ut3l4yk/artifacts/output%2Fnvda_snapshot_try-moreBaum-13573%2Ce7441063.exe). Please test it with as many of these displays as you can.

**Comment by pavel46** [comment]
Hi Jamie.

Thank you very much for this new build.

My colleague tested this trial build with  Vario 340 and SuperVario2 40 cells braille displays. He reports that both displays are recognized and working properly. Both routing keys and the D keys of the braille displays are supported. 

Thank you very much again.

With kind regards.

Pavel.
