### ISSUE TITLE
the search suggestion in google site is automatically assumed

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#6121]
when performing a search using google site
www.google.com
so a search suggestion appears NVDA form mode is turned off and the search suggestion is made.
this is bad, because many veses the suggestion is not what you want to search.
This occurs when the chrome use 51, and NVDA master 13374.
I will describe the stately homes, the survey was conducted in Portuguese.
1 = open chrome, position in the search field and enter edit mode.
2 = Enter the search
"qual o desenvolvedor do"
At this point NVDA forms mode is turned off and the research suggested by google "qual o desenvolvedor do carro gol" is performed automatically.
My original intention was to complete the text of my research is "qual o desenvolvedor do window eyes"
Thank you very much.
In firefox I not notice this unwanted behavior.

**Comment by jcsteh** [comment]
I can't reproduce this. When I type a search query, the page does update 
as I type; this is intentional. However, the search box stays focused 
and NVDA stays in focus mode.

Have you changed any NVDA browse mode settings from their defaults?

Do you have any add-ons installed? If so, please try with them disabled.

**Comment by fernando-jose-silva** [comment]
Thank you for feedback.

I conducted tests from their questions, and the problem is to disable the "Auto Focus mode when the focus changes" in NVDA.

 

De: James Teh [mailto:notifications@github.com] 
Enviada em: quarta-feira, 29 de junho de 2016 19:40
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>; Author <author@noreply.github.com>
Assunto: Re: [nvaccess/nvda] the search suggestion in google site is automatically assumed (#6121)

 

I can't reproduce this. When I type a search query, the page does update 
as I type; this is intentional. However, the search box stays focused 
and NVDA stays in focus mode.

Have you changed any NVDA browse mode settings from their defaults?

Do you have any add-ons installed? If so, please try with them disabled.

**Comment by ehollig** [comment]
Sounds like this issue has been resolved.

**Comment by fernando-jose-silva** [comment]
I no longer have this problem, thank you.
