### ISSUE TITLE
Enable wx assertions and fix any reported assertions

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#6127]
Years ago, we suppressed wx assertions (ac21399c) because of a [bug in wxWidgets](http://trac.wxwidgets.org/ticket/10052). However, that bug has apparently since been fixed. We've been seeing some crashes ending in wx lately. Suppressing assertions might be hiding something bad (which might lead to a crash?), so we should try re-enabling them.

I know of one case where we're definitely triggering a wx assertion: `keyboardHandler.KeyboardInputGesture.reportExtra` sets a timer (using `wx.CallLater`) from a background thread, which is apparently bad. We should make it use `core.callLater` instead, which knows how to handle background threads correctly.

We'll need to watch for other assertions as well and fix them as they arise.

CC @feerrenrut, @MichaelDCurran.

**Comment by feerrenrut** [comment]
I have enabled assertions and confirmed that replacing `wx.CallLater` with `core.callLater` in `keyboardHandler.KeyboardInputGesture.reportExtra` runs cleanly. I exercised this code path by toggling caps-lock. 

Also successfully smoke tested in a few applications looking for other assertions triggered by wx. This was done while running from source. 

There are about 16 other places that use `wx.CallLater` directly, do you think we are likely to run into a problem with these?

See branch i6127_enableWxAssertions

**Comment by feerrenrut** [comment]
For reference the error that occurs when assertions enabled and the toggle keys (turning on caps-lock) case is not handled is the following.

```
IO - inputCore.InputManager.executeGesture (09:10:15):
Input: kb(laptop):capsLock
ERROR - keyboardHandler.internal_keyDownEvent (09:10:15):
internal_keyDownEvent
Traceback (most recent call last):
  File "keyboardHandler.py", line 147, in internal_keyDownEvent
    inputCore.manager.executeGesture(gesture)
  File "inputCore.py", line 439, in executeGesture
    gesture.reportExtra()
  File "keyboardHandler.py", line 422, in reportExtra
    wx.CallLater(30, self._reportToggleKey)
  File "C:\work\nvda\miscDeps\python\wx\_core.py", line 16802, in __init__
    self.Start()
  File "C:\work\nvda\miscDeps\python\wx\_core.py", line 16816, in Start
    self.timer.Start(self.millis, wx.TIMER_ONE_SHOT)
  File "C:\work\nvda\miscDeps\python\wx\_misc.py", line 1324, in Start
    return _misc_.Timer_Start(*args, **kwargs)
PyAssertionError: C++ assertion "wxThread::IsMain()" failed at ..\..\src\common\timerimpl.cpp(60) in wxTimerImpl::Start(): timer can only be started from the main thread
```

**Comment by feerrenrut** [comment]
#6137 has been reverted. See https://github.com/nvaccess/nvda/pull/6184

**Comment by michaelDCurran** [comment]
WX assertions enabled in 8f252398f4bf121009fd4b205c729629eab22352
However, known assertions are not yet fixed.
