### ISSUE TITLE
Update to Python 2.7.12

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6144]
> Python 2.7.12 is a bugfix release in the Python 2.7.x series.
[Changelog](https://hg.python.org/cpython/raw-file/v2.7.12/Misc/NEWS)

**Comment by jcsteh** [comment]
We currently rely on the version of Python installed on AppVeyor. It would be simplest for us to wait for AppVeyor to update. They seem to update fairly regularly, so this should be okay.

CC @MichaelDCurran.

**Comment by jcsteh** [comment]
AppVeyor has now updated to Python 2.7.12, so NVDA builds are already using this.
