### ISSUE TITLE
Notify users of expanded/collapsed states in virtual buffers

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#615]
**Reported by MarcoZ on 2010-04-06 07:28**
Followup to MozBug551684: When a widget, button, heading or the like, that can be expanded or collapsed, changes state upon a key press, NVDA should notify the user automatically. The state change is reflected int he virtual buffer when arrowing away and back, but not when changing it directly. Should work similarly to checking/unchecking checkboxes.

**Comment by leonardder** [comment]
I've seen this working, for example on www.babbage.com, menu link "Producten slechtzienden"

Closing as works for me, but please reopen if you belief I'm wrong.
