### ISSUE TITLE
In LibreOffice Writer, with latest next versions, line numbers are always displayed in braille

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#6150]
Hi,

In don't know with which next version it happened, since I don't use Writer every day,
But to-day, In noticed that line numbers are systematically shown in braille.
Since this could be usefull (in fact in any text editor), this sould be switchable.

**Comment by josephsl** [comment]
Cc @nvdaes

**Comment by nvdaes** [comment]
Hi, it's switchable. It deppends on the format document settings.
See:
https://github.com/nvaccess/nvda/pull/5980#issuecomment-230209373
for issue #5941

**Comment by MichelSuch** [comment]
Yes, it is switchable, except that, in Writer, the line number is always 
displayed, wether or not you turn it off in the document formatting dialog.

When off, the line number is nomore spoken, but still displayed.


                     Michel SUCH

michel.such@free.fr
Skype : michel.such
Twitter : @SuchMichel

**Comment by nvdaes** [comment]
Thanks, hope it can be fixed.
I will test in other editors.

**Comment by nvdaes** [comment]
Hi, I guess this issue have to be fixed changing code on Libre Office 
support.
Anyway, the pull request referenced in #i5941 issue provides a solution 
for this.
I have test this snapshot created by myself:
https://github.com/nvdaes/nvda/releases/download/i5941/nvda_snapshot_source-i5941-522c29a.exe
Thanks.

**Comment by MichelSuch** [comment]
Hi,


Just tested, and it works fine for me.


                     Michel SUCH

michel.such@free.fr
Skype : michel.such
Twitter : @SuchMichel

**Comment by jcsteh** [comment]
This was fixed in #5941.
