### ISSUE TITLE
Error durring update check

### ISSUE THREAD

**Issue by pzajda** [nvaccess/nvda#6152]
Hi,

When I try to check for update, I have the following error in the log:
ERROR - stderr (11:18:59):
Exception in thread Thread-103:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "threading.pyc", line 754, in run
  File "updateCheck.pyc", line 126, in _bg
  File "updateCheck.pyc", line 173, in setNextCheck
  File "wx_misc.pyc", line 1324, in Start
PyAssertionError: C++ assertion "wxThread::IsMain()" failed at ....\src\common\timerimpl.cpp(60) in wxTimerImpl::Start(): timer can only be started from the main thread

I use NVDA version next-13392,621e5393
I might be caused by the recent changes on WX.

Thanks.

**Comment by leonardder** [comment]
I can confirm this.
    Op 7-7-2016 om 11:44 schreef Patrick
      ZAJDA:
    
    
      Hi,
      When I try to check for update, I have the following error in
        the log:
        ERROR - stderr (11:18:59):
        Exception in thread Thread-103:
        Traceback (most recent call last):
        File "threading.pyc", line 801, in __bootstrap_inner
        File "threading.pyc", line 754, in run
        File "updateCheck.pyc", line 126, in _bg
        File "updateCheck.pyc", line 173, in setNextCheck
        File "wx_misc.pyc", line 1324, in Start
        PyAssertionError: C++ assertion "wxThread::IsMain()" failed at
        ....\src\common\timerimpl.cpp(60) in wxTimerImpl::Start(): timer
        can only be started from the main thread
      I use NVDA version next-13392,621e5393
        I might be caused by the recent changes on WX.
      Thanks.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on
          GitHub, or mute
          the thread.

**Comment by Elshara** [comment]
I can also confirm this.

**Comment by michaelDCurran** [comment]
Due to no longer suppressing wx assertions.


In the long-term we need to fix the code actually causing the 
assertions, but for now we'll try and come up with a better way of 
logging them that does not stop any code from running.




On 7/07/2016 10:25 PM, Elshara Silverheart wrote:
>
> I can also confirm this.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/6152#issuecomment-231062782>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ANf5nRF9w1ya5ZXg2i8ZKJBIgBl-ZaLYks5qTPA2gaJpZM4JG6Sb>.
>

-- 
Michael Curran
Executive Director, NV Access Limited
Phone: +61 7 3149 3306
Website: http://www.nvaccess.org/
Twitter: @NVAccess
Facebook: http://www.facebook.com/NVAccess

**Comment by feerrenrut** [comment]
P1 to assess if this is still likely to happen, and if so, what the cost to improve the situation is.

**Comment by jcsteh** [comment]
Related to #6127.

I don't think this should produce exceptions any more, as we now log wx assertions as debugWarning. That said, this assertion will definitely happen whenever updateCheck sets up the next automatic check.

I actually wrote a patch to fix this while I was away in July, but I haven't gotten around to testing it yet.

**Comment by Brian1Gaff** [comment]
As an aside to this. Not so many update check sounds now, but do notice that 
sometimes the windows system hides the prompt about a new update available 
or one of the screens during an update so you are not aware its there unless 
you look through the  alt tab list to find it.
 It seems to be windows version independent, much like the firefox one where 
it never reads the page till you force the focus to re set itself so to 
speak. To me this is odd as it always used to be very reliable in this 
active window thing.
 Not sure if this is related to the other issue, but worth a mention just in 
case.
 I've tried making logging level low in case its a timing thing, with no 
observable difference.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
