### ISSUE TITLE
Some untranslatable strings

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#6162]
In the "Document Formatting dialog", there are some strings that are there for some times and that remain untranslatable:
"report comments"
"Report line indentation with:" and the choices that go with
"report line spacing"

**Comment by leonardder** [comment]
These are strings in the next branch which haven't yet been merged into the master branch of NVDA. As soon as this functionality is merged into the master branch and the new strings are merged into to the translation repository, you will be able to translate them. After that, new translation strings have to be merged back into the nVDA master branch before they will be visible in the GUI.
Please read [the information about translating NVDA on the wiki](https://github.com/nvaccess/nvda/wiki/Translating). There are several subtopics about the specific parts of NVDA that can be translated.
I assume this can be closed.

**Comment by MichelSuch** [comment]
yes, it can.


                     Michel SUCH

michel.such@free.fr
Skype : michel.such
Twitter : @SuchMichel
