### ISSUE TITLE
Input gesture to toggle simple review mode

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6173]
In some situations, it can be desirable to quickly switch simple review mode on and off. However, it seems no input gesture script exists for this. I propose adding one left unbound by default.

**Comment by derekriemer** [comment]
This would be nice.


On 7/13/2016 8:32 AM, Leonard de Ruijter wrote:
>
> In some situations, it can be desirable to quickly switch simple 
> review mode on and off. However, it seems no input gesture script 
> exists for this. I propose adding one left unbound by default.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/6173>, or mute the thread 
> <https://github.com/notifications/unsubscribe/AFGivSndVwAfFBlAhNZaSV78mbGEEhBPks5qVPb9gaJpZM4JLe1c>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by josephsl** [comment]
Hi, I second this (object nav category). Thanks.
