### ISSUE TITLE
You can not read the columns of messages on gmail in html basic display

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#6179]
By using the display basic HTML view mode on gmail inbox, when you read the first message table column where the messages check boxes, you can not switch to the columns to the right of the table where there is subject and date by pressing ctrl + alt + arrow to the right.
Hall:
open the gmail inbox.
Choose the basic HTML view.
Press T to go to the messages table.
Press down arrow to the first column where the check boxes.
Now press Ctrl + Alt + arrow right to read the second column with the subject of messages.
Press Ctrl + Alt + arrow right to read the third column where there is the receiving of messages dates.
expected, it is that NVDA read the columns.
What ever happens is that NVDA does not read the second and third column, when reading the content of the first column.
If you read only the columns 2 and column 3 NVDA reads normally.
The problem occurs only when reading the first column and then try to read the other columns by pressing ctrl + alt + arrow to the right.
I could not reprodusir the problem in other tables.

**Comment by ehollig** [comment]
I am not sure if I am performing the steps correctly, but when I press T to go to the table, I am presented with a checkbox. When I press alt+CTRL+right, I get the sender, alt+CTRL+right then returns the subject/first few lines of the message. performing that command again gives the time/date the message was sent. Everything works as expected using Firefox 54.
Possibly related: #4272

**Comment by bhavyashah** [comment]
@fernando-jose-silva  Could you please inform us if about whether bug still persists or not? If it does, please mention the web browser(s) and their respective version(s) with which the same can be replicated.
My testing is akin to that of @ehollig. As a regular GMail Basic HTML web interface user with Firefox, I have never experienced such an issue.

**Comment by fernando-jose-silva** [comment]
Perfect, the problem has been solved, there have been several updates since the problem was opened.
Thank you very much for your attention.

Enviado do meu iPhone

**Comment by ehollig** [comment]
Closing from https://github.com/nvaccess/nvda/issues/6179#issuecomment-319345508
