### ISSUE TITLE
Document formatting items are visually hidden on small display

### ISSUE THREAD

**Issue by nishimotz** [nvaccess/nvda#6186]
Document formatting dialog now contains 27 checkbox items, and they are vertically arranged in single column.
The window height is now 748 pixels on Windows 10.

For small visual display users, the OK and Cancel buttons are accessible, however, latter part of checkbox items are simply hidden and unaccessible.

Possible solutions are:
* add vertical scroll bar (and possibly subpanel) to allow visual access of latter part of checkbox items
* horizontally multi-column arrangement of checkbox items
* divided into several groups and display separately (use tabs, radio buttons, tree views, and so on)

**Comment by feerrenrut** [comment]
This should now be addressed, see PR #6402. I'll close this issue now, please re-open it if there is still some concern.
