### ISSUE TITLE
href being read out for <a role=button> on IE11

### ISSUE THREAD

**Issue by hkdennis2k** [nvaccess/nvda#6187]
I have a simple a tag with aria-label , role= button, href="#!".

NVDA read out only the aria-label on focus by tab or in browser mode.

However, it read in a different way when I press NVDA+tab (read current item).

In chrome it read only  the (aria-label) + "button" as expected.
However, in IE11, it read the (aria-label) + "button" + (the resolved hyperlink) + "visited".

**Comment by Adriani90** [comment]
@hkdennis2k could you please post an example so we can reproduce this issue? Thanks.

**Comment by hkdennis2k** [comment]
I am no longer have access to the code that could replica the bug.

I have little memory that it could behaves very different if the a tag was
- statically from HTML
- in a jQuery dialog
- generated via javascript after onload

**Comment by Adriani90** [comment]
I think this is strongly related to #10733. I close this one in favor of that issue. Please feel free to comment if I musunderstood this issue and we can reopen if this is not related to #10733.
