### ISSUE TITLE
Add slovenian 8-computer braille to nvda

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#6188]
Hi,

in a folder of tables there is version of slovenian 8-computer braille called sl-si-comp8.ctb. is it possible to enable it? It is not final version due to on going changes of slovenian official standard but it is place where we are going to work.

thanks.

Jožef

**Comment by gregjozk** [comment]
Hi,

we've tested this table and found no seriece bugs, so can this table be included in a next official version of NVDA?

If it needed corrections, we would provide it via liblouis.

Thanks.

**Comment by josephsl** [comment]
Hi, is this for liblouis 3? If so, can we try this for 2017.1? Thanks.

**Comment by leonardder** [comment]
I'd be happy to make a pr for this, but I'd say we do this when
    #2439 is merged into master.

**Comment by gregjozk** [comment]
Hi,

We've tested only an output. @josephsl, this table was included in liblouis system since 2.6 release, I think and then there were only myner corrections. So when You asked if it can be included in 2017.1 release, I think that it is good because I know that there are more important things, which should be done. But if it is possible can it be included in a next official release?

Thanks, Jožef

**Comment by josephsl** [comment]
Hi, I said 2017.1 as we’re in the midst of testing #2439 (as noted by Leonard). Thanks.
