### ISSUE TITLE
Update to Nullsoft Scriptable Install System version 3 for launcher

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6210]
[Here](http://nsis.sourceforge.net/Docs/AppendixF.html#v3.0) is the changelog.

**Comment by leonardder** [comment]
We are now at version 3.0.1.

Is it possible to assign a priority to this?

**Comment by jcsteh** [comment]
You don't state any reasons for upgrading. Especially since this is a major version and upgrading is likely to be non-trivial, we shouldn't just upgrade for the sake of it. Are there security fixes that won't be backported to 2.x? Priority can't be assigned without further info.

**Comment by feerrenrut** [comment]
I'm going to close this issue for now. Please re-open it with further justification.
