### ISSUE TITLE
Outlook 2016: NVDA reads "Associated draft, no associated drafts" for every message

### ISSUE THREAD

**Issue by bramd** [nvaccess/nvda#6219]
Tested on latest Outlook 2016 from Office 365. @dkager reported that he has the same problem since yesterday with Office 365 as well.

# Steps to reproduce:
1. Open a mail folder (e.g. inbox)
2. Arrow through the message list

# Technical details

For every item in the message list, NVDA does the following:
1. Use Outlooks' native COM interface to query some message attributes (read/unread, attachment, meeting request etc)
2. Do a direct UIA query to loop over the children of the table row, filtered by controlType text

The "Associated draft" column has either been added very recently, or changed it's type to text and so is included in the loop in step 2.

# Solution

I'm not that familiar with Outlook, but I guess this column sometimes contains real information about an associated draft, so just dropping it might not be the solution. We might drop it if it contains the "no associated drafts" value, but this is something that should be translated exactly in all languages and is to error prone. May be Microsoft can revert this change or we can come up with a better way to determine which columns to read.

**Comment by bramd** [comment]
I've reverted to version 16.0.6965.2063. The problem is nonexistent in that version. I had a brief look at the changelogs, but didn't see any clue what changed to make this strange behavior happen.

**Comment by bramd** [comment]
I've reverted to version 16.0.6965.2063. The problem is nonexistent in that version. I had a brief look at the changelogs, but didn't see any clue what changed to make this strange behavior happen.

**Comment by dkager** [comment]
For completeness' sake, I had the same issue with Outlook 2016 from Office 365 and the solution posted above worked to resolve it.

**Comment by leonardder** [comment]
I'm now on 16.0.9001.2102, and "No associated draft" is no longer exposed. Instead, the text node is empty.
