### ISSUE TITLE
Text selection in some edit controls in Skype is not reported

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#6222]
### Description:

In some edit controls in the latest Skype for desktop, text selection is not reported. Such text controls are the ones for renaming a contact, renaming a conversation, etc. Not all text controls are affected (the chat entry edit field for example is not). The problem is when text selection is done (for example with SHIFT and the arrow keys. But if I execute the command to report the currently selected text, it correctly reports it.
### Steps to reproduce it:
1. Launch NVDA.
2. Launch Skype.
3. Focus Skype.
4. Press Alt+1 to focus the contacts list or Alt+2 to focus the last conversations list.
5. Focus a contact or a conversation entry.
6. Press F2 to rename it.
7. Use SHIFT and the arrow keys to select some text.
### Actual results:

NVDA stays silent.
### Expected results:

NVDA should report what has been selected.
### Test environment:
- Operating system: Windows 10 Pro (build 10586.494), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: next-13473,521ea127.
- Skype version: 7.26.0.101.
- Processor: Intel Core i5-2320 at 3.00GHz.
- RAM Memory: 8.00GB.
- Graphics: Palit GeForce GT 630, 1024MB dedicated memory + 3071MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC662 at Intel Cougar Point PCH - High Definition Audio Controller.

**Comment by Adriani90** [comment]
@k-kolev1985 are you still able to reproduce this issue in last skype version?

**Comment by Adriani90** [comment]
@k-kolev1985 couls you please post stept to reproduce for Skype UWP? Thanks.

**Comment by k-kolev1985** [comment]
OK, here they are:

### Steps to reproduce
1. Open Skype UWP and sign into it.
2. Press Alt+2 to go to the "Contacts" list. You may need to press TAB a few times after that, to move the keyboard focus there as well - it seams not to be done automatically by Skype, even though it should - I'll have to report that to the Skype team.
3. Select a contact from the list.
4. Invoke its context menu and from it choose "Edit contact". A dialog appears.
5. In that dialog, press TAB a few times, until you get to a grouping labeled with the name of the contact. Here, the keyboard focus should have been moved to the text field for editing the contact's name, but again there is a bug and it does not (another one to report to the Skype team).
6. Move the mouse cursor to the navigator object with NVDA+NumPad Slash and simulate a left mouse click. That should move the keyboard focus/system caret inside the edit field. NVDA+Up Arrow should read the contact's name.
7. Use Shift+Left/Right Arrow Keys to select text.
8. Invoke the NVDA command to report the currently selected text (NVDA+Shift+Up Arrow).
9. Use only Left/Right Arrow Keys to review the text.

### Expected results
NVDA should read the text while reading with Left/Right Arrow Keys. NVDA should report the selected text when doing the selection and on demand.

### Actual results
NVDA does not read the text while reading with Left/Right Arrow Keys. NVDA stays silent when selecting text. NVDA reports that there is nothing selected when invoking the NVDA command for reporting the currently selected text.

Test environment:
- Operating system: Windows 10 Pro version 1809 (build 17763.253), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- Skype UWP version: Skype version 8.37.76.92; Application version 14.37.92.0 (that is what is displayed in Skype UWP's "About" window and it is a "Preview" release).
- NVDA version: alpha-16530,d5120846.
- Processor: Intel Core i5-4670 at 3.40GHz.
- RAM Memory: 8.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC887 at Intel Lynx Point PCH - High Definition Audio Controller.

Hmm, seams this has turned into a complete bug report, maybe deserving its own separate issue. Should I report it into a new issue?

**Comment by k-kolev1985** [comment]
> 
> 
> OK, here they are:
> ### Steps to reproduce
> 
>     1. Open Skype UWP and sign into it.
> 
>     2. Press Alt+2 to go to the "Contacts" list. You may need to press TAB a few times after that, to move the keyboard focus there as well - it seams not to be done automatically by Skype, even though it should - I'll have to report that to the Skype team.
> 
>     3. Select a contact from the list.
> 
>     4. Invoke its context menu and from it choose "Edit contact". A dialog appears.
> 
>     5. In that dialog, press TAB a few times, until you get to a grouping labeled with the name of the contact. Here, the keyboard focus should have been moved to the text field for editing the contact's name, but again there is a bug and it does not (another one to report to the Skype team).
> 
>     6. Move the mouse cursor to the navigator object with NVDA+NumPad Slash and simulate a left mouse click. That should move the keyboard focus/system caret inside the edit field. NVDA+Up Arrow should read the contact's name.
> 
>     7. Use Shift+Left/Right Arrow Keys to select text.
> 
>     8. Invoke the NVDA command to report the currently selected text (NVDA+Shift+Up Arrow).
> 
>     9. Use only Left/Right Arrow Keys to review the text.
> 
> 
> ### Expected results
> 
> NVDA should read the text while reading with Left/Right Arrow Keys. NVDA should report the selected text when doing the selection and on demand.
> ### Actual results
> 
> NVDA does not read the text while reading with Left/Right Arrow Keys. NVDA stays silent when selecting text. NVDA reports that there is nothing selected when invoking the NVDA command for reporting the currently selected text.
> ### Test environment:
> 
>     * Operating system: Windows 10 Pro version 1809 (build 17763.253), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
> 
>     * Skype UWP version: Skype version 8.37.76.92; Application version 14.37.92.0 (that is what is displayed in Skype UWP's "About" window and it is a "Preview" release).
> 
>     * NVDA version: alpha-16530,d5120846.
> 
>     * Processor: Intel Core i5-4670 at 3.40GHz.
> 
>     * RAM Memory: 8.00GB.
> 
>     * Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
> 
>     * Sound Card: Realtek ALC887 at Intel Lynx Point PCH - High Definition Audio Controller.
> 
> 
> Hmm, seams this has turned into a complete bug report, maybe deserving its own separate issue. Should I report it into a new issue?

About the issue with Skype UWP (from Microsoft Store). Now I'm running the latest version of the app and the problem seams to be gone. Skype UWP version is 8.43.76.38 and the version of the app is 14.43.38.0 (all taken from Skype's about dialog). I think that is a test (insider) version of Skype UWP, but it should become stable and released to the public in the near future, I guess. So, I think this issue can be closed.
