### ISSUE TITLE
NVDA reads irrelevant titles when moving through jquery-ui autocomplete drop down list on huge pages

### ISSUE THREAD

**Issue by praedicta** [nvaccess/nvda#6225]
Hi!

We use jquery-ui autocomplete plugin. While moving through the list of items by pressing up and down arrows NVDA successively reads items, On rather simple/small pages everything works just fine. But when the amount of html  growth NVDA starts skipping items. For testing purposes I add a huge table to the page, and it causes the issue.
Here are two example pages (type 'a' in the input to see drop-down list of results):

http://praedictadev.themarker.com:9494/test1.html
http://praedictadev.themarker.com:9494/test2.html

First works as expected, but second doesn't.

**Comment by feerrenrut** [comment]
Thanks for raising this issue, and for providing test cases. However, I cant reproduce this issue in `Chrome Version 58.0.3029.110 (64-bit)` with NVDA version: `next-14098,66f26bb2`

Could you please update the description of this issue with the browser (and version) as well as the version of NVDA you are using? It would also be helpful if you could please attach an NVDA log (at debug level logging) when reproducing this problem with the provided test cases.

**Comment by Adriani90** [comment]
@praedicta are you still available? Your links in the description are not working anymore. could you please upload two working examples so we can reproduce this issue? Thanks!

**Comment by Adriani90** [comment]
It seems we lost contact to the initial author. I am closing this issue as abandoned. The links in the description are still not working.
