### ISSUE TITLE
NVDA reads tab name twice

### ISSUE THREAD

**Issue by praedicta** [nvaccess/nvda#6226]
Hi!

When I add a pseudo element ::after with position: absolute via css to a `<li>` element which has the role="tab", NVDA starts reading the tab name twice when moving through tabs by clicking left and right arrows.

Example: 
http://praedictadev.themarker.com:9494/test3.html

**Comment by ravishtiwari** [comment]
@praedicta - the link you have provided is broken, can you please correct that? OR if the issue has been fixed for you, can you share how you were able to resolve the issue so that others can benefit from it.

**Comment by ehollig** [comment]
Closing as invalid, as the above link appears to be broken. If @praedicta is able to provide a working link and describe the issue that is occurring, along with steps to reproduce, what happens, and what is expected to happen instead, we can reopen this issue.
