### ISSUE TITLE
Crash while exiting word

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6250]
Hi,
I pressed alt+f4 to exit a resume template I was editing, and boom.

**Comment by derekriemer** [comment]
[Mon 08 August 2016 02-53-28 exiting wm.zip](https://github.com/nvaccess/nvda/files/408441/Mon.08.August.2016.02-53-28.exiting.wm.zip)

**Comment by derekriemer** [comment]
Also, earlier today, I had a crash while pressing the menu item to add alt-text to an image in PowerPoint
[Mon 08 August 2016 20-58-23 Editing a powerpoint I pressed the menu item to add alt-text to an image.zip](https://github.com/nvaccess/nvda/files/408444/Mon.08.August.2016.20-58-23.Editing.a.powerpoint.I.pressed.the.menu.item.to.add.alt-text.to.an.image.zip)
.

**Comment by josephsl** [comment]
Hi, crash dump/log please. Thanks.

**Comment by derekriemer** [comment]
It's there.

**Comment by josephsl** [comment]
CC @MichaelDCurran

**Comment by josephsl** [comment]
Hi, yep, never mind, saw the zip file. Thanks.

**Comment by josephsl** [comment]
Hi,

Looking at the dump file...

If this issue is reproducible, hyave you tried it while all add-ons are disabled? If so, this is a serious thing. According to the dump output, looks like the helper thread was trying to access a memory location that it could not access due to security issue (perhaps a kernel mode address or blocked due to privilege; somewhere we can start in locating the real problem).

@MichaelDCurran: Am I reading the dump right? I don't have debug symbols handy at the moment. Thanks.

**Comment by michaelDCurran** [comment]
The first one looks as though something in NVDA tried to create a thread with an invalid start address. Nothing more can be really understood from that dump. Though it is worth noting that the main thread was in the middle of playing wave data, and another thread was stuck sending a Windows message.
The crash dump can't show us what function requested to create the thread as createThread returns before the thread is started.

**Comment by jcsteh** [comment]
The log file should include Python stacks now, so it's worth looking at that too.

**Comment by feerrenrut** [comment]
We should investigate this further and see if we can work out how to reproduce this. P1 to investigate then re-triage.

**Comment by michaelDCurran** [comment]
Closing as the dump refers to an NVDA Next build who's symbols have now expired. If this can be reproduced on demand using  either a stable build of NVDA or a much more recent Next build, then reopen the issue and attach a newer crash dump.
However, The creation of the thread into invalid memory is odd, and the dump contains some 3rd party dlls.
