### ISSUE TITLE
How I can get to read modal popup again

### ISSUE THREAD

**Issue by alex-dolbik** [nvaccess/nvda#6251]
How I can get to read modal popup content again?
I have site where modal popup appears after some time. Modal popup contains some text with time (seconds). Screen reader have to read the seconds when they are changed.

**Comment by ehollig** [comment]
@alex-dolbik, could you provide an example site where this occurs? Also, which browser and version of NVDA are you using? Having more information like this will help me, and others, replicate the issue.

**Comment by ehollig** [comment]
@alex-dolbik, is this still an issue with the latest NVDA? Now that #4493 has been implemented in the latest Master, this may have been resolved. If not, could you provide an example site along with the steps that you took to reproduce the issue, what happened, and what you expected to happen instead?

**Comment by ehollig** [comment]
Closing as invalid, as we have not heard from the original author of this issue in over 2 years.
