### ISSUE TITLE
Announce paragraph indent / hanging indent when creating with shortcut keys in Word

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6269]
In Word:

control+m increases the indent of the current paragraph
control+shift+m decreases the indent

control+t increases the hanging indent (the indent of every line except the first in a paragraph)
control+shift+t decreases the hanging indent

Currently nothing is announced when these keys are pressed.  The paragraph indent is announced when NVDA+f is pressed.

**Comment by fernando-jose-silva** [comment]
I just want to emphasize that in Portuguese, the ctrl + t command selects all text and does not change alignment.

**Comment by Qchristensen** [comment]
Thanks Fernando, something to consider.  Is there a Microsoft reference for the Portuguese specific keystrokes do you happen to know?

**Comment by fernando-jose-silva** [comment]
Good Morning.
I found an article where the shortcut keys for the Brazilian Portuguese is correct.
I found other articles more were some shortcuts with errors.
The major drawback is that the page is in Portuguese.
As a suggestion could translate the page into English using google chrome.
In the article talks about Windows 95, but tested the commands in successfully windows 10.

https://support.office.com/pt-br/article/Atalhos-de-teclado-do-Microsoft-Word-2016-para-Windows-95ef89dd-7142-4b50-afb2-f762f663ceb2

Anyway, I put down a few shortcuts:

new document ctrl+o
open a new file ctrl + a
save ctrl + b
close ctrl + w
copy ctrl + c
paste ctrl + v
cut ctrl + x
select all text ctrl + t
Bold ctrl + n
italic ctrl + i
Underline ctrl + s
center text ctrl + e
align the left ctrl + q
undo ctrl + z
redo ctrl + r
Print ctrl + p
Enable or disable change tracking Ctrl + Shift + E
Find ctrl + l
replace ctrl + u
Switch the letters between uppercase and lowercase Shift + F3
Format all letters as uppercase Ctrl + Shift + A
Underline the words but not the spaces Ctrl + Shift + W 
Apply double underline the text Ctrl + Shift + D
Copy text formatting Ctrl + Shift + C
Apply copied formatting to text Ctrl + Shift + V
Apply 1.5 line spacing Ctrl + 5
Apply the style Title 1Ctrl + Shift + 1
Apply the Heading 2 style Ctrl + Shift + 2
Apply the style Heading 3 Ctrl + Shift + 3
Insert a field DATE Alt + Shift + D
save as f12
Horto fix spelling alt + f7

**Comment by ruifontes** [comment]
Hi!

Atention! Not all shortcuts and keystrokes are equal in the european and 
brazilian portuguese versions of Windows, Office and so on...

Sorry, but I didn't notice the first message...

Fernando, can you contact me about this, please?

Rui Fontes

-----Mensagem Original----- 
De: fernando-jose-silva
Data: 5 de setembro de 2016 16:23
Para: nvaccess/nvda
Assunto: Re: [nvaccess/nvda] Announce paragraph indent / hanging indent when 
creating with control+m / control+t in Word (#6269)



Good Morning.
I found an article where the shortcut keys for the Brazilian Portuguese is 
correct.
I found other articles more were some shortcuts with errors.
The major drawback is that the page is in Portuguese.
As a suggestion could translate the page into English using google chrome.
In the article talks about Windows 95, but tested the commands in 
successfully windows 10.

https://support.office.com/pt-br/article/Atalhos-de-teclado-do-Microsoft-Word-2016-para-Windows-95ef89dd-7142-4b50-afb2-f762f663ceb2

Anyway, I put down a few shortcuts:

new document ctrl+o
open a new file ctrl + a
save ctrl + b
close ctrl + w
copy ctrl + c
paste ctrl + v
cut ctrl + x
select all text ctrl + t
Bold ctrl + n
italic ctrl + i
Underline ctrl + s
center text ctrl + e
align the left ctrl + q
undo ctrl + z
redo ctrl + r
Print ctrl + p
Enable or disable change tracking Ctrl + Shift + E
Find ctrl + l
replace ctrl + u
Switch the letters between uppercase and lowercase Shift + F3
Format all letters as uppercase Ctrl + Shift + A
Underline the words but not the spaces Ctrl + Shift + W
Apply double underline the text Ctrl + Shift + D
Copy text formatting Ctrl + Shift + C
Apply copied formatting to text Ctrl + Shift + V
Apply 1.5 line spacing Ctrl + 5
Apply the style Title 1Ctrl + Shift + 1
Apply the Heading 2 style Ctrl + Shift + 2
Apply the style Heading 3 Ctrl + Shift + 3
Insert a field DATE Alt + Shift + D
save as f12
Horto fix spelling alt + f7

-

**Comment by jcsteh** [comment]
You can use NVDA's locale specific gesture maps to work around this. 
This has already been done for several other shortcuts in Word for 
various languages.

**Comment by Qchristensen** [comment]
Changed the title to remove the specific keys and mention when the indent is created with keystrokes.  As discussed these are control+m / control+t in English but vary in other languages.

**Comment by CyrilleB79** [comment]
@Qchristensen could you please describe precisely what you expect as a reported information? Only the distance or distance+type of indent (indent/hanging indent)? Distance from the left of the page or distance from the margin.
Please also consider the discussion in #8994.

**Comment by Qchristensen** [comment]
When you press NVDA+numpad delete / NVDA+delete, it reports the distance from the left edge (and top) of the page, as set in Word (eg 140 points, 5.3cm, 1.8 inches, etc), so I would keep it consistent with that.

If we can readily determine that a specific indentation was just created may be difficult - if it can that would be great, but I think at least if it announced the distance that would be good.

**Comment by Adriani90** [comment]
One shortcut should also be announced, ctrl+q which removes the paragraph formatting.
