### ISSUE TITLE
Support unpacked addons in development mode

### ISSUE THREAD

**Issue by ctoth** [nvaccess/nvda#6277]
Similar to the unpacked extension support in Chrome, I propose a way of adding unpacked addon support to the addon manager to better support addons which are being developed.

We should be able to specify a directory with a manifest and have NVDA load the addon from the custom path where it is being developed from.
The easiest way I can see to support this is by adding a .manifest extension with a label of Unpacked Addon (for developers) or similar to the current Install... dialog in the addon manager.

**Comment by ragb** [comment]
I agree this would be very useful. In principle I agree with the proposed solution, however I'm not sure how to integrate it in the add-ons dialog. Would the open add-on file dialog support also directories with the mentioned unpacked add-on  extension?

**Comment by bhavyashah** [comment]
Any thoughts from our resident NVDA add-on experts? @josephsl @derekriemer

**Comment by josephsl** [comment]
Hi,

I think it might be preferable to look into this in Python 3 version, as support for this may introduce issues during transition period.

Thanks.

**Comment by Adriani90** [comment]
actually this should be kind of possible with the new scratch pad directory in NVDA 2019.1 Beta 1 if I am not wrong. @josephsl what do you think?

**Comment by josephsl** [comment]
Hi, I’d defer that question to @LeonardDer and @feerrenrut at this time as I’m out of office at the moment. Thanks.

**Comment by feerrenrut** [comment]
The scratchpad directory (available through advanced settings) basically accomplishes this. I would be interested in the introduction of a command to package the contents of the scratchpad dir as an addon (after filling in the basic manifest data via the GUI).

**Comment by seanbudd** [comment]
Closing as fixed by scratchpad. Please open a new issue if any further features are expected

**Comment by hwf1324** [comment]
There is a problem with scratchpad. For example, I usually develop plugins on the fly in `source/userConfig/scratchpad`, which gets me IntelliSense, and I can also test it in the source run again.
But when I need to test it in the install run I need to repeat the file copying step many times.
For example, if I need to interact with a programme that has administrator rights.

**Comment by seanbudd** [comment]
@hwf1324 - would Reef's idea of being able to package an add-on from scratchpad be an adequate solution to this? if so, can you open an issue for this if it doesn't exist

**Comment by seanbudd** [comment]
See also #10482

**Comment by hwf1324** [comment]
No, I don't think the packaging plugin addresses this issue, but this could be a new feature request.

It is possible to specify that the directory of the unpackaged plugin solves the problem I described.

**Comment by hwf1324** [comment]
> See also #10482

It seems this already exists.

**Comment by XLTechie** [comment]
@hwf1324 I'm sorry, but I have difficulty understanding why #10482 wouldn't solve the problem you described.
Let us say that it was implemented, and you had been working on an add-on in the source scratchpad.
1. Run the exporter.
2. Choose the files of your add-on.
3. Add the entries for the manifest.
4. It creates an nvda-addon package.
5. In your installed copy of NVDA, you install the newly generated nvda-addon package.
Why is that not a good solution?

**Comment by hwf1324** [comment]
@XLTechie This is of course great for Add-on's that have been developed down.

However, if Add-on still has some problems and needs to be modified and tested repeatedly, this step is too cumbersome and not as convenient as just copying and pasting the file.

So if you can specify the unpacked Add-on directory, you can skip the process of copying and pasting files over and over again.

**Comment by seanbudd** [comment]
@hwf1324 - could you open a new issue to allow customizing "addDirsToPythonPackagePath" to add additional scratchpad directories? I think that captures the step missing from #10482.
