### ISSUE TITLE
Better summarize announcement of entering and leaving nested controls

### ISSUE THREAD

**Issue by ctoth** [nvaccess/nvda#6288]

**Comment by ctoth** [comment]
Consider the case of multiple nested iframes. When we exit currently we read this n times to the user. Could we combine this to say something like out of three iframes as a start?
Given that role names are singular, this may present translation trouble/some new strings for translators.
Alternatively we could say something like the role name followed by a number indicating how many were left if greater than 1. This would have the benefit of not requiring much translation work at the cost of being a little uglier.

**Comment by ehollig** [comment]
Can this issue be closed now that we have #2591?

**Comment by ehollig** [comment]
I am going to close this in favor of #2591
