### ISSUE TITLE
Spurious focus on Bing document when leaving Windows 10 Start Menu search

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#6292]
STR:
1. Open the Start Menu.
2. Type a few characters until suggestions appear; e.g. type n then o.
3. Press escape.
- Expected: Focus should return to where it was before step 1.
- Actual: NVDA reports that focus is on a Bing document. However, keyboard focus is actually where it was before step 1.

The `hasFocus` property on the document returns False by the time I can look. I'm guessing it has focus when it fires the event (because we should otherwise be blocking it), but I'm not sure.

**Comment by josephsl** [comment]
Hi, Feedback sent to MS. Thanks.

**Comment by jcsteh** [comment]
HasKeyboardFocus is False when the event arrives. However, the current Edge code bypasses this check, probably due to brokenness in a previous build of Windows. This is no longer needed in RS1, so we stop doing it as part of #6271, thus fixing this problem.
