### ISSUE TITLE
Skype for Desktop: Support for reporting spelling errors

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#6293]
In Windows 10, Skype for Desktop now reports spelling errors with Narrator. It seems the TChatRichEdit control Skype uses has a UIA implementation which does expose this correctly. However, we don't use UIA for it because we map it to RichEdit and we disable UIA for all RichEdit controls.

We should consider using UIA for TChatRichEdit in Windows 10. I'm not sure whether this works in Windows 8/8.1 as well; this needs to be checked.

TChatRichEdit is mapped to RichEdit20 in NVDAObjects.window.windowClassMap. One option is to only insert this mapping if we're not on Windows 10 or UIA is disabled. However, because this mapping happens at import time, this might be tricky.

**Comment by bhavyashah** [comment]
@jcsteh Feel free to triage this ticket. I wouldn't vote for too high a priority on this one - probably a P4, or a P3 only if implementation cost is minimal.

**Comment by Adriani90** [comment]
@nishimotz are you working on a pull request to include your previous work on this? Or is it not intended to solve it?

**Comment by nishimotz** [comment]
@Adriani90 I am not working on this.
Anyway, most issues regarding Skype 7 are not applicable to Skype 8, in my opinion.

**Comment by jcsteh** [comment]
No longer relevant now that Skype 7 is dead. Skype 8 uses Electron and this should already work there.
