### ISSUE TITLE
Windows 10 build 14901 and later: Freezes when opening NVDA windows

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#6301]
This is intermittent, but happens often enough that it's extremely annoying. When you open an NVDA window (e.g. the Add-ons Manager, a settings dialog or the browse mode find dialog), NVDA often freezes for a few seconds. This started happening in Windows 10 build 14905.

@josephsl, I believe you mentioned this on IRC. I seem to see it a lot more when running from source than with an installed copy. Do you see this too? Also, I think you mentioned it doesn't happen in the Log Viewer, but I think I've seen it even there.

I've tracked this down to UiaHasServerSideProvider blocking when called on the desktop window in these cases. It's being called on that window in response to a nameChange event for the cursor. I don't know why it blocks then; if I call it from the Python console, it behaves just fine.

Working around this in NVDA would be trivial: we can just always return False for the desktop window. I've tested this and it seems to work. I'd obviously prefer to know why this is happening, but I suspect debugging this is going to be hideous and I'm not sure whether it's worth the effort. I also suspect Microsoft won't see this as important, as they're probably not a huge fan of us using that function anyway.

Thoughts, @MichaelDCurran?

**Comment by jcsteh** [comment]
We should probably also wait for the next build to see if this is fixed there before committing a fix.

**Comment by josephsl** [comment]
Hi,

This actually began in build 14901 (Redstone 2). At least for now, the workaround is to open log viewer first before opening other NVDA windows.

Thanks.

**Comment by jcsteh** [comment]
This appears to be fixed in Windows 10 build 14926. A fix on our side is no longer required.
