### ISSUE TITLE
Secure CRT versions greater than 6.1.x do not speak screen output automatically

### ISSUE THREAD

**Issue by nromey** [nvaccess/nvda#6302]
Every major version of Secure CRT changes the window class of its main window.  In JAWS, scripts have to be updated, and this is still the cae with NVDA, I just didn't notice it until now.  I haven't compiled this in, but I believe that one can update securecrt.py with the new window variables, right now there is support up to 7.1.x.  I will try to fork and fix this thing for the project, but I've never done this before.  Alternatively, I can upload the changed file.  I'm currently running version 8.0.2 which uses the window class of AfxFrameOrView140u.  Basically, for every version, you increment 10, so to include all versions, we need to add AfxFrameOrView110u AfxFrameOrView120u, AfxFrameOrView130u, and AfxFrameOrView140u.  The screen writes are the same in all versions.

**Comment by jcsteh** [comment]
Thanks for the info. It might be better to use a regexp like 
AfxFrameOrView\d{2,}u so we don't have to worry about adding numbers 
every version.

**Comment by nromey** [comment]
True. Would I just put it in the statement in that regular expression form and see if it works. If it compiles and works I'll re commit it.

**Comment by jcsteh** [comment]
No; you'll need to use the re module to do a regular expression match. 
If the code you've submitted works, it's probably easier just to use that.

**Comment by nromey** [comment]
Figured it out.  First python program ever.  I know, not too exciting
but still.  Thanks for the help with the expression, that one was
tricky.  Implementing with re was the easy part.  Do you want me to
comment at the top of the file that it works for all versions or just
leave the module information and commenting as is.  I ran it from
source in python and it indeed works.  Think Ill try it with JAWS
regular expressions next as I think they support them now.

**Comment by nromey** [comment]
Jamie,

I went ahead and committed the regexp version.  See what you think and
let me know if it was ok.  Again, thanks for the help.

**Comment by nromey** [comment]
File is in the right place now.
