### ISSUE TITLE
System Locks up When Navigating in Visual Studio 2015 Server Explorer

### ISSUE THREAD

**Issue by trodick** [nvaccess/nvda#6304]
When using the Visual Studio 2015 server explorer with the latest version of NVDA (2016.2.1), if I press End to go to the end of the server explorer tree view, the entire system locks up and the only way I can fix it is by shutting it down forcefully and restarting. I'm running Windows 10 Insider Build 14905, and the server explorer is set to dock as a tabbed document. I do not encounter any similar issue when using JAWS 17 with the same environment. Given that the system locks up, I don't have any way to insert a log file capturing the state at the time of the issue.

**Comment by josephsl** [comment]
Hi, is this reproducible in build 14393? If not, then it’s likely some issues in Redstone 2. Thanks.

**Comment by TylerK93** [comment]
I don't have any way to test this in 14393 at this time. Sort of 
off-topic, but what is Redstone 2?

**Comment by josephsl** [comment]
Hi, Redstone 2 is the next feature upgrade (due sometime next year). Do you have access to a system running build 14393 so you can testing this? Thanks.

**Comment by ehollig** [comment]
@TylerK93, do you have an update on this issue?

**Comment by Adriani90** [comment]
@TylerK93 are you still having this issue? @mohammad-suliman could you please test if this is still reproducible? We are not sure if the initial author is still available. Thank you!

**Comment by Adriani90** [comment]
@mohammad-suliman are you available to test this? I think VS 2015 is not really used anymore. But this issue might occur on newer VS versions as well.

**Comment by leonardder** [comment]
I'm closing this issue because of lack of response from the initial author. Visual Studio 2015 is thereby replaced by newer versions with accessibility as a higher priority
