### ISSUE TITLE
enter key doesn't work on links before input element

### ISSUE THREAD

**Issue by juliancho1025** [nvaccess/nvda#6308]
When we try to 'enter' a link at the start of a form, it doesn't redirect and the focus gets lost.
'Intro' and 'space' keys work fine.

If we move the link after an input element the 'enter' key works fine.

**Comment by josephsl** [comment]
Hi, do you have a working example that demonstrate this? Thanks.

**Comment by juliancho1025** [comment]
Sadly no, the site I'm working on is not live yet. As soon as it is I will post the link here.
I think in a month it will be accessible to the public in general.

**Comment by ehollig** [comment]
@juliancho1025, do you have a working example that demonstrates the described behavior?

**Comment by ehollig** [comment]
Closing as invalid, as we have not heard from the original poster in over a year. @juliancho1025, if you have a working example that demonstrates the issue you are experiencing, please share, along with exact detailed steps to reproduce, including what you did, what you expected to happen and what happened instead.
