### ISSUE TITLE
Default voice and language not consistent under Hong Kong Cantonese

### ISSUE THREAD

**Issue by lstar4ever** [nvaccess/nvda#6313]
Hi,
When everytime I first open NVDA installer, the language is set to Hong Kong Traditional Chinese, however, the voice for espeak was always manderine, but not Cantonese.
In Hong Kong the native language is Cantonese, not Manderine.

**Comment by bhavyashah** [comment]
@lstar4ever  Could you please clarify as to whether or not this issue applies with ESpeak-NG, the project that has superceded ESpeak?

**Comment by ehollig** [comment]
@lstar4ever, just a friendly reminder to respond to @bhavyashah in https://github.com/nvaccess/nvda/issues/6313#issuecomment-319878173. Also, can you provide thorough steps to produce the issue you are experiencing? Is this the case with NVDA 2017.3?

**Comment by ehollig** [comment]
Closing as invalid, as we have not heard from the original poster in over a year if this issue still exists for them.
