### ISSUE TITLE
NVDA not able to read webpage contents

### ISSUE THREAD

**Issue by ehollig** [nvaccess/nvda#6324]
Some time ago NVDA started to simply report "blank" or not say anything when I try to read any webpage with it. I installed the 2015.3 and it works fine, but when I updated to the final version of 2015.4, this is what I am experiencing. This is an issue in Chrome, FF and IE 11. (Chrome and FF do not say anything and IE11 says "blank").

I suspect it may be some problem with my computer (Win 7, 64bit, 8GB RAM, 500GB HD) since the same thing happens with portable versions that I run on this computer. I have tried to register the DLL's refered to in issue #2807  and have uninstalled and reinstalled FF and Chrome.

With the latest Firefox V48.02 and Internet Explorer V11.0.9600, when either program is opened, NVDA acts as if it is in focus mode. The only working key is the Tab key to go to buttons, edit fields, or links. No navigation quick keys, no arrow keys work.
in focus mode, I get the following error:
[NVDA_LOG3.txt](https://github.com/nvaccess/nvda/files/448040/NVDA_LOG3.txt)

DEBUG - treeInterceptorHandler.update (14:40:31):
Adding new treeInterceptor to runningTable: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x05A0D4F0>
ERROR - virtualBuffers.VirtualBuffer._loadBuffer (14:40:31):
Traceback (most recent call last):
  File "virtualBuffers\__init__.pyo", line 369, in _loadBuffer
WindowsError: [Error 1702] The binding handle is invalid

Note: this is on a fresh install of a portable copy of NVDA 2016.3RC1.

Related issues: #2807, #3618, #5758

**Comment by ehollig** [comment]
Thank you for the comment. Unfortunately, it did not. This happens with a portable version of NVDA as well after 2015.3. I have completely uninstalled NVDA 2016.3 as you suggested, making sure there is no NVDA folder in Program Files (X86) and no NVDA folder in Appdata. When the computer is restarted and NVDA 2016.3 is installed the problem persists. I do notice, however, that when NVDA 2016.3 is installed it takes less than a second, but when I install NVDA 2015.3 which does not experience this problem, the installation takes about 3 seconds or so. Could it possibly have something to do with an antivirus I have installed? I believe I have Webroot SecureAnywhere. Which files may it be blocking?

**Comment by jcsteh** [comment]
Ah. It could indeed be due to your virus scanner. Unfortunately, while 
we can confirm that NVDA is free of viruses, some virus scanners tend to 
think NVDA is a virus (false positive).

I'd suggest temporarily disabling your virus scanner during the 
installation. Most likely, it is blocking nvdaHelperRemoteLoader.exe, 
nvdaHelperRemote.dll or one of the vbufBackend*.dll files.

**Comment by ehollig** [comment]
Thank you @jcsteh

I was able to disable the antivirus, and although it was not quarantining any of the files that you listed above, installation of NVDA with the antivirus disabled worked! Thank you again.

**Comment by zahra21** [comment]
hi.
i completely confirm this bug and its the dupplicate of my bug
https://github.com/nvaccess/nvda/issues/6505

**Comment by zahra21** [comment]
yesterday i downloaded 2017.1 version of nvda and it seems to work Good for me with windows xp and firefox 51 and 52
