### ISSUE TITLE
Wording of options

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#6344]
Feedback on GUI, received via email. With respect to the general settings dialog, though the concept should apply to all dialogs.

> Wording can be improved for some options to make the purpose clearer and to shorten the text and apply some consistency.  Some suggestions follow:
> 
> Language (requires restart to fully take effect):  combo box  User default  collapsed 
> Do we mean restart of nvda or restart of windows? so wording could be changed to: 
> Language (changes take effect after restarting NVDA):  combo box  User default  collapsed
> 
> Save configuration on exit  check box  checked 
> could be re-worded to 
> Save configuration on exiting NVDA  check box  checked
> 
> Show exit options when exiting NVDA  check box  not checked 
> could be re-worded to 
> Confirm before exiting NVDA  check box  not checked
> 
> Automatically start NVDA after I log on to Windows  check box  not checked 
> could be re-worded to 
> Automatically start NVDA after logging on to Windows  check box  not checked
> 
> Use currently saved settings on the logon and other secure screens (requires administrator privileges)  button 
> could be shorter and re-worded to: 
> Use saved settings on logon and secure screens (requires administrator privileges)  button

**Comment by leonardder** [comment]
@feerrenrut: I'd say a p4 is sufficient for this? Setting this as good for new dev

**Comment by feerrenrut** [comment]
This issue really was just a dump of some feedback NV access received on the UI. Essentially these are discussion points, I don't think NV Access necessarily agrees with all of this feedback. @ThomasStivers thanks for the PR, however please follow this issue, since I think it's worth some discussion first.

Here are my opinions: 
Proposed: `Language (requires restart to fully take effect)` becoming `Language (changes take effect after restarting NVDA)`. 
I would prefer that this became shorter. Perhaps: `NVDA Language (requires restart)`
When this is changed there is a prompt that explains that it is a restart of NVDA that is required. Adding NVDA to the label I think helps to make this clearer, and also hopefully makes it clearer that this is the NVDA Language rather than Synth language.

>Save configuration on exit check box checked
could be re-worded to
Save configuration on exiting NVDA check box checked

I would question the use of "on" here, perhaps "when" would be better: `Save configuration when exiting NVDA`

>Automatically start NVDA after I log on to Windows check box not checked
could be re-worded to
Automatically start NVDA after logging on to Windows check box not checked

My preference: `Automatically start NVDA after log on` while it is slightly ambiguous, I think most would understand it to mean Windows log on.

**Comment by josephsl** [comment]
Hi, for the last item, I think it could be reworded as, “start NVDA after signing onto Windows”. This acknowledges the fact that users can now use MS Account to sign in as opposed to local account, as well as using remote systems. Thanks.

**Comment by derekriemer** [comment]
We want to make sure it's short and sweet however.

**Comment by josephsl** [comment]
Hi, short, sweet, and translatable. For most translators, they don’t need to worry about most messages. Thanks.

**Comment by ThomasStivers** [comment]
For these dialog labels shorter is better in my opinion. If we want to provide longer explanatory text we might consider implementing context help across the preferences boxes. This help could open the appropriate section of the user guide in the user's default browser when F1 is pressed or when a Help button, added with OK and Cancel, is pressed.

I like the idea of using tool tips, but they will only be read if the speak tool tips option is checked in object presentation settings which is not the default.
