### ISSUE TITLE
NVDA 2016.2.1 reads href attribute for links when role=“option” on Internet Explorer

### ISSUE THREAD

**Issue by denny89k** [nvaccess/nvda#6353]
I have a simple listbox

```
<ul role="listbox">
        <li >
            <a role="option" href="javascript:void(0);" aria-selected="false">text1</a>
        </li>
        <li>
            <a role="option" href="javascript:void(0);" aria-selected="true">text2</a>
        </li>
</ul>
```

https://jsfiddle.net/2Lb48y1v/

when I use NVDA 2016.2.1 on Internet Explorer, screen reader reads href attribute (for example "text1 javascript:void(0); not selected text1" or "text1 javascript:void(0); selected text2") and also, as you can see from example, reads anchor text 2 times

**Comment by PratikP1** [comment]
What, if I may ask, is the purpose of using role=”presentation”

**Comment by DzianisUkrainets** [comment]
just semantic. without rope="presentation" i have the same issue

**Comment by PratikP1** [comment]
Is there a demo site by any chance?

**Comment by DzianisUkrainets** [comment]
only here https://jsfiddle.net/2Lb48y1v/

**Comment by PratikP1** [comment]
For some reason, I’m not able to test this code even when I try to run the script

**Comment by DzianisUkrainets** [comment]
you can test it locally in your simple html page. it reproduces without additional code only by adding role="option" for links on IE11

**Comment by DzianisUkrainets** [comment]
@PratikP1 , do you have any updates ?

**Comment by Adriani90** [comment]
@denny89k when I load your code in IE, NVDA reports:
"bullet text 1
bullet text 2".

In Firefox and Chrome the listbox is displayed properly. In IE there is no listbox at all.

**Comment by Adriani90** [comment]
This seems to contain javascript code which is reported by NVDA, see also issue #10733. It seems a general issue when using javascript in IE and NVDA. I am closing this issue in favor of #10733 but please feel free to comment on this if I misunderstood this issue and if this is not related to #10733.
