### ISSUE TITLE
Microsoft Excell 2016: NVDA will not read in a formula box

### ISSUE THREAD

**Issue by sharkboyto** [nvaccess/nvda#6354]
Hi,
in Microsoft Excell 2016, NVDA will not read in the formula text field when press f2 to edit or write a new formula.
My Operating System is Windows 10 64 bit Anniversary Update.

**Comment by josephsl** [comment]
CC @MichaelDCurran

**Comment by jcsteh** [comment]
It does work as expected for most users, so this is a system specific issue.

Does NVDA say anything at all when you press f2? If so, what?
Is Narrator able to read the field?

Thanks!

**Comment by sharkboyto** [comment]
Hi,

after reboot my system and install any system update all work fine.
Thanks for the support.

Alessandro

Il 07/09/2016 00:51, James Teh ha scritto:
