### ISSUE TITLE
Fix untracked content in include/sonic after scons source

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6357]
This can be fixed since [my pull request](https://github.com/waywardgeek/sonic/pull/9) is merged into master.

**Comment by leonardder** [comment]
Would one of you be able to assign a priority to this? Thanks.

**Comment by jcsteh** [comment]
Triage note: there's no functional difference between sonic current master and the commit we're currently using, so this should be pretty safe. The only difference is the .gitignore and some white space changes.
