### ISSUE TITLE
Update SpeechPlayer in Espeak Add-On to Use eSpeak NG

### ISSUE THREAD

**Issue by Laughingthunder** [nvaccess/nvda#6365]
Please consider updating the SpeechPlayer in Espeak add-on to use the newer eSpeak NG synthesizer. I still use the latest version of this add-on during times when Vocalizer refuses to read any text containing custom Unicode characters, such as emoji characters. Therefore, I feel it is still worth maintaining.

**Comment by Laughingthunder** [comment]
I understand that this is in no way top priority, but any feedback on this would be appreciated.

**Comment by feerrenrut** [comment]
We understand there is demand for this and the value it would bring, unfortunately we are working on higher priority issues at the moment. Thanks for your enthusiasm for this project.

@michaelDCurran Could you comment on the development cost for this?

**Comment by bhavyashah** [comment]
@michaelDCurran Could you kindly respond to https://github.com/nvaccess/nvda/issues/6365#issuecomment-256828456 and update us about the current development status of NV Speech Player?

**Comment by Adriani90** [comment]
I think the best is to create an issue directly to the addon at
https://github.com/nvaccess/NVSpeechPlayer
So I am closing this one since NVDA uses eSpeak NG already.
