### ISSUE TITLE
nvda speech to sapi5

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#6366]
Could you please add a voice2sapi button in the synthesizer dialog which when pressed opens another dialog box letting you choose any available NVDA voice and variant for the current synthesizer and lets you use it as a sapi5 voice as long as NVDA is running even if NVDA is in sleep mode? Then we could use voices like festival or free sapi4 voices with sapi5 applications such as audio games. Then when you are done with the voice you would just ;hit the remove voice as sapi button in the Synthesizer dialog box. thanks.

**Comment by jcsteh** [comment]
This is out of scope for NVDA, since this is about providing voices for other applications, not voices for NVDA itself. It's also technically impossible (or at least difficult enough that it's not worthwhile). Thanks.
