### ISSUE TITLE
NVDA throws an error when Firefox paes are not fully loaded and an arrow navigation is performed

### ISSUE THREAD

**Issue by nromey** [nvaccess/nvda#6370]
Since running the master, I have encountered errors with null handles being passed during remote procedure calls.  I'm attaching my log file.  I'm not familiar with the code in question, but tracebacks are icluded so maybe this could help track down the problem.  I think maybe it happens when I arrow up and down and while NVDA speaks, I hit escape.  I haven't seen this in 2016.3  Not sure.

**Comment by nromey** [comment]
[nvda.txt](https://github.com/nvaccess/nvda/files/468673/nvda.txt)

**Comment by nromey** [comment]
After updating modules I think I've fixed the issue.

**Comment by nromey** [comment]
I figured out a reproducable path for firing this error, the code is byzantine so I'm not sure how to fix it here but here's what I've found.  Please advise on how to fix and I will try to fix it.  Here is the deal.
When using Firefox, no errors fire unless you 
(1) perform a search on google or any page with an edit box.
(2) perform the search.
(3) I'm an impatient person I guess so I hit the arrow keyy before teh search was completed so the text in the object wasn't there to arrow to.

What we need to do is makk NVDA note that the application is busy and not allow arrowing while it is busy.  I could edit the script but I'm not sure how to not perform the action if MOzila is usy/loading a page.  I think that the issue can happen when you click a link by pressing enter and then arrow around too quickly.

Any ideas on what code I can look at fixing or what code someone can fix?  I'll paste in my latest log from the latest master.

INFO - __main__ (23:29:47):
Starting NVDA
INFO - core.main (23:29:49):
Config dir: C:\nvdasource\nvda\source\userConfig
INFO - core.main (23:29:49):
NVDA version source-master-4d792f0
INFO - core.main (23:29:49):
Using Windows version 6.2.9200 workstation
INFO - core.main (23:29:49):
Using Python version 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
INFO - core.main (23:29:49):
Using comtypes version 0.6.2
INFO - synthDrivers.espeak.SynthDriver.__init__ (23:29:50):
Using eSpeak version 1.48.15  16.Apr.15
INFO - synthDriverHandler.setSynth (23:29:51):
Loaded synthDriver espeak
INFO - core.main (23:29:51):
Using wx version 3.0.2.0 msw (classic)
INFO - braille.initialize (23:29:51):
Using liblouis version 2.6.5
INFO - braille.BrailleHandler.setDisplayByName (23:29:51):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - brailleInput.initialize (23:29:51):
Braille input initialized
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (23:29:51):
UIAutomation: IUIAutomation3
INFO - core.main (23:29:51):
NVDA initialized
INFO - config.ConfigManager.save (23:29:52):
Base configuration saved
ERROR - scriptHandler.executeScript (23:30:09):
error executing script: <bound method Dynamic_EditableTextWithAutoSelectDetectionBrokenFocusedStateEditorMozillaIAccessible.script_caret_moveByLine of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionBrokenFocusedStateEditorMozillaIAccessible object at 0x059721D0>> with gesture u'down arrow'
Traceback (most recent call last):
  File "scriptHandler.py", line 186, in executeScript
    script(gesture)
  File "editableText.py", line 143, in script_caret_moveByLine
    self._caretMovementScriptHelper(gesture, textInfos.UNIT_LINE)
  File "editableText.py", line 103, in _caretMovementScriptHelper
    self._caretScriptPostMovedHelper(unit,gesture,newInfo)
  File "editableText.py", line 89, in _caretScriptPostMovedHelper
    speech.speakTextInfo(info, unit=speakUnit, reason=controlTypes.REASON_CARET)
  File "speech.py", line 691, in speakTextInfo
    textWithFields=info.getTextWithFields(formatConfig)
  File "NVDAObjects\IAccessible\ia2TextMozilla.py", line 303, in getTextWithFields
    return self._getText(True, formatConfig)
  File "NVDAObjects\IAccessible\ia2TextMozilla.py", line 252, in _getText
    obj = ti.obj
AttributeError: 'NoneType' object has no attribute 'obj'
INFO - core.main (23:30:24):
Exiting
INFO - config.ConfigManager.save (23:30:24):
Base configuration saved
INFO - __main__ (23:30:26):
NVDA exit


I reopened the issue due to finding it's reproducibility.  I tried going back through the traceback and I don't know the source well enough to throw something to not act on th arrow until the page is loaded completely.

NER

**Comment by jcsteh** [comment]
I think these are two different issues. You originally opened the issue due to null handles in RPC calls, but this AttributeError case is very different.

Regardless, are you seeing a noticeable problem here or just an exception? I'm guessing it happens because the search box disappears as NVDA is trying to read text from it. Even if we can clean up the exception (and note that final releases have the error sound disabled, so most users never notice it),We're never going to be able to report anything in this case.

**Comment by bhavyashah** [comment]
Hi,
Recently, I have been experiencing extremely conspicuous latency and
unresponsiveness in web browsing with the latest version of Firefox
and NVDA. I am not sure whether it were the recent versions of Firefox
triggering these slowdowns, or deficiences in NVDA 2016.3.
Using Wordpress significantly over the past few days, here's just one
of the 'interesting' oddities I was able to capture.
Basically, I was on my own blog, pressed the Settings link, and then
tried to move around on the loading/loaded page by arrowing, and
before the several seconds it took to adjust itself to a new page,
here's what NVDA+F1 generated:
ERROR - scriptHandler.executeScript (02:37:05):
error executing script: <bound method Gecko_ia2.script_moveByLine_back
of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x047F2AB0>> with
gesture u'up arrow'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 186, in executeScript
  File "cursorManager.pyo", line 191, in script_moveByLine_back
  File "cursorManager.pyo", line 111, in _caretMovementScriptHelper
  File "treeInterceptorHandler.pyo", line 143, in makeTextInfo
  File "virtualBuffers\__init__.pyo", line 196, in __init__
  File "textInfos\offsets.pyo", line 298, in __init__
  File "virtualBuffers\__init__.pyo", line 201, in _getSelectionOffsets
WindowsError: [Error 1775] A null context handle was passed from the
client to the host during a remote procedure call
DEBUG - NVDAObjects.IAccessible.IAccessible._get_role (02:37:05):
IARole: li
DEBUG - NVDAObjects.IAccessible.IAccessible._get_role (02:37:05):
IARole: li

Thanks.
P.S. Although I have been experiencing and have marked occurrence of
other sorts of warnings, errors and tracebacks during Internet
browsing in recent times as well, I began documenting them for tickets
just now, and out of the few catches I made, I have posted this
because it just seems not-the-common-error&traceback. :)

On 9/21/16, nromey <notifications@github.com> wrote:
> I figured out a reproducable path for firing this error, the code is
> byzantine so I'm not sure how to fix it here but here's what I've found.
> Please advise on how to fix and I will try to fix it.  Here is the deal.
> When using Firefox, no errors fire unless you
> (1) perform a search on google or any page with an edit box.
> (2) perform the search.
> (3) I'm an impatient person I guess so I hit the arrow keyy before teh
> search was completed so the text in the object wasn't there to arrow to.
>
> What we need to do is makk NVDA note that the application is busy and not
> allow arrowing while it is busy.  I could edit the script but I'm not sure
> how to not perform the action if MOzila is usy/loading a page.  I think that
> the issue can happen when you click a link by pressing enter and then arrow
> around too quickly.
>
> Any ideas on what code I can look at fixing or what code someone can fix?
> I'll paste in my latest log from the latest master.
>
> INFO - __main__ (23:29:47):
> Starting NVDA
> INFO - core.main (23:29:49):
> Config dir: C:\nvdasource\nvda\source\userConfig
> INFO - core.main (23:29:49):
> NVDA version source-master-4d792f0
> INFO - core.main (23:29:49):
> Using Windows version 6.2.9200 workstation
> INFO - core.main (23:29:49):
> Using Python version 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22)
> [MSC v.1500 32 bit (Intel)]
> INFO - core.main (23:29:49):
> Using comtypes version 0.6.2
> INFO - synthDrivers.espeak.SynthDriver.__init__ (23:29:50):
> Using eSpeak version 1.48.15  16.Apr.15
> INFO - synthDriverHandler.setSynth (23:29:51):
> Loaded synthDriver espeak
> INFO - core.main (23:29:51):
> Using wx version 3.0.2.0 msw (classic)
> INFO - braille.initialize (23:29:51):
> Using liblouis version 2.6.5
> INFO - braille.BrailleHandler.setDisplayByName (23:29:51):
> Loaded braille display driver noBraille, current display has 0 cells.
> INFO - brailleInput.initialize (23:29:51):
> Braille input initialized
> INFO - _UIAHandler.UIAHandler.MTAThreadFunc (23:29:51):
> UIAutomation: IUIAutomation3
> INFO - core.main (23:29:51):
> NVDA initialized
> INFO - config.ConfigManager.save (23:29:52):
> Base configuration saved
> ERROR - scriptHandler.executeScript (23:30:09):
> error executing script: <bound method
> Dynamic_EditableTextWithAutoSelectDetectionBrokenFocusedStateEditorMozillaIAccessible.script_caret_moveByLine
> of
> <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionBrokenFocusedStateEditorMozillaIAccessible
> object at 0x059721D0>> with gesture u'down arrow'
> Traceback (most recent call last):
>   File "scriptHandler.py", line 186, in executeScript
>     script(gesture)
>   File "editableText.py", line 143, in script_caret_moveByLine
>     self._caretMovementScriptHelper(gesture, textInfos.UNIT_LINE)
>   File "editableText.py", line 103, in _caretMovementScriptHelper
>     self._caretScriptPostMovedHelper(unit,gesture,newInfo)
>   File "editableText.py", line 89, in _caretScriptPostMovedHelper
>     speech.speakTextInfo(info, unit=speakUnit,
> reason=controlTypes.REASON_CARET)
>   File "speech.py", line 691, in speakTextInfo
>     textWithFields=info.getTextWithFields(formatConfig)
>   File "NVDAObjects\IAccessible\ia2TextMozilla.py", line 303, in
> getTextWithFields
>     return self._getText(True, formatConfig)
>   File "NVDAObjects\IAccessible\ia2TextMozilla.py", line 252, in _getText
>     obj = ti.obj
> AttributeError: 'NoneType' object has no attribute 'obj'
> INFO - core.main (23:30:24):
> Exiting
> INFO - config.ConfigManager.save (23:30:24):
> Base configuration saved
> INFO - __main__ (23:30:26):
> NVDA exit
>
>
> I reopened the issue due to finding it's reproducibility.  I tried going
> back through the traceback and I don't know the source well enough to throw
> something to not act on th arrow until the page is loaded completely.
>
> NER
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6370#issuecomment-248503831


-- 
Best Regards
Bhavya Shah

Avid Enthusiast and User of the Free NVDA Screen Reader (www.nvaccess.org)

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by bhavyashah** [comment]
Hi,
Apologies for making another comment, but this catch too seems
interesting. I pressed the Change Footer Credit link on Wordpress's
Settings page, and waited patiently until NVDA mumbled something and
then attempted to arrow around.

DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (02:44:20):
COM pointer <POINTER(IAccessibleText) ptr=0x6943474 at 4a5cb20> already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (02:44:20):
COM pointer <POINTER(IAccessibleAction) ptr=0x69436fc at 4a5c8a0>
already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (02:44:20):
COM pointer <POINTER(IAccessible2) ptr=0x69438ac at 4a5c260> already deleted
IO - inputCore.InputManager.executeGesture (02:44:20):
Input: kb(laptop):NVDA+f1
IO - speech.speak (02:44:20):
Speaking [LangChangeCommand ('en_GB'), u'clickable', u'list with 6
items', u' Back', u'button']
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (02:44:21):
COM pointer <POINTER(IAccessibleText) ptr=0x5c65c2c at 4a696c0> already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (02:44:21):
COM pointer <POINTER(IAccessibleAction) ptr=0x5c659ec at 4a697b0>
already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (02:44:21):
COM pointer <POINTER(IAccessible2) ptr=0x5c65c74 at 4a693a0> already deleted

Thanks.

On 9/23/16, Bhavya shah <bhavya.shah125@gmail.com> wrote:
> Hi,
> Recently, I have been experiencing extremely conspicuous latency and
> unresponsiveness in web browsing with the latest version of Firefox
> and NVDA. I am not sure whether it were the recent versions of Firefox
> triggering these slowdowns, or deficiences in NVDA 2016.3.
> Using Wordpress significantly over the past few days, here's just one
> of the 'interesting' oddities I was able to capture.
> Basically, I was on my own blog, pressed the Settings link, and then
> tried to move around on the loading/loaded page by arrowing, and
> before the several seconds it took to adjust itself to a new page,
> here's what NVDA+F1 generated:
> ERROR - scriptHandler.executeScript (02:37:05):
> error executing script: <bound method Gecko_ia2.script_moveByLine_back
> of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x047F2AB0>> with
> gesture u'up arrow'
> Traceback (most recent call last):
>   File "scriptHandler.pyo", line 186, in executeScript
>   File "cursorManager.pyo", line 191, in script_moveByLine_back
>   File "cursorManager.pyo", line 111, in _caretMovementScriptHelper
>   File "treeInterceptorHandler.pyo", line 143, in makeTextInfo
>   File "virtualBuffers\__init__.pyo", line 196, in __init__
>   File "textInfos\offsets.pyo", line 298, in __init__
>   File "virtualBuffers\__init__.pyo", line 201, in _getSelectionOffsets
> WindowsError: [Error 1775] A null context handle was passed from the
> client to the host during a remote procedure call
> DEBUG - NVDAObjects.IAccessible.IAccessible._get_role (02:37:05):
> IARole: li
> DEBUG - NVDAObjects.IAccessible.IAccessible._get_role (02:37:05):
> IARole: li
>
> Thanks.
> P.S. Although I have been experiencing and have marked occurrence of
> other sorts of warnings, errors and tracebacks during Internet
> browsing in recent times as well, I began documenting them for tickets
> just now, and out of the few catches I made, I have posted this
> because it just seems not-the-common-error&traceback. :)
>
> On 9/21/16, nromey <notifications@github.com> wrote:
>> I figured out a reproducable path for firing this error, the code is
>> byzantine so I'm not sure how to fix it here but here's what I've found.
>> Please advise on how to fix and I will try to fix it.  Here is the deal.
>> When using Firefox, no errors fire unless you
>> (1) perform a search on google or any page with an edit box.
>> (2) perform the search.
>> (3) I'm an impatient person I guess so I hit the arrow keyy before teh
>> search was completed so the text in the object wasn't there to arrow to.
>>
>> What we need to do is makk NVDA note that the application is busy and not
>> allow arrowing while it is busy.  I could edit the script but I'm not
>> sure
>> how to not perform the action if MOzila is usy/loading a page.  I think
>> that
>> the issue can happen when you click a link by pressing enter and then
>> arrow
>> around too quickly.
>>
>> Any ideas on what code I can look at fixing or what code someone can fix?
>> I'll paste in my latest log from the latest master.
>>
>> INFO - __main__ (23:29:47):
>> Starting NVDA
>> INFO - core.main (23:29:49):
>> Config dir: C:\nvdasource\nvda\source\userConfig
>> INFO - core.main (23:29:49):
>> NVDA version source-master-4d792f0
>> INFO - core.main (23:29:49):
>> Using Windows version 6.2.9200 workstation
>> INFO - core.main (23:29:49):
>> Using Python version 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22)
>> [MSC v.1500 32 bit (Intel)]
>> INFO - core.main (23:29:49):
>> Using comtypes version 0.6.2
>> INFO - synthDrivers.espeak.SynthDriver.__init__ (23:29:50):
>> Using eSpeak version 1.48.15  16.Apr.15
>> INFO - synthDriverHandler.setSynth (23:29:51):
>> Loaded synthDriver espeak
>> INFO - core.main (23:29:51):
>> Using wx version 3.0.2.0 msw (classic)
>> INFO - braille.initialize (23:29:51):
>> Using liblouis version 2.6.5
>> INFO - braille.BrailleHandler.setDisplayByName (23:29:51):
>> Loaded braille display driver noBraille, current display has 0 cells.
>> INFO - brailleInput.initialize (23:29:51):
>> Braille input initialized
>> INFO - _UIAHandler.UIAHandler.MTAThreadFunc (23:29:51):
>> UIAutomation: IUIAutomation3
>> INFO - core.main (23:29:51):
>> NVDA initialized
>> INFO - config.ConfigManager.save (23:29:52):
>> Base configuration saved
>> ERROR - scriptHandler.executeScript (23:30:09):
>> error executing script: <bound method
>> Dynamic_EditableTextWithAutoSelectDetectionBrokenFocusedStateEditorMozillaIAccessible.script_caret_moveByLine
>> of
>> <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionBrokenFocusedStateEditorMozillaIAccessible
>> object at 0x059721D0>> with gesture u'down arrow'
>> Traceback (most recent call last):
>>   File "scriptHandler.py", line 186, in executeScript
>>     script(gesture)
>>   File "editableText.py", line 143, in script_caret_moveByLine
>>     self._caretMovementScriptHelper(gesture, textInfos.UNIT_LINE)
>>   File "editableText.py", line 103, in _caretMovementScriptHelper
>>     self._caretScriptPostMovedHelper(unit,gesture,newInfo)
>>   File "editableText.py", line 89, in _caretScriptPostMovedHelper
>>     speech.speakTextInfo(info, unit=speakUnit,
>> reason=controlTypes.REASON_CARET)
>>   File "speech.py", line 691, in speakTextInfo
>>     textWithFields=info.getTextWithFields(formatConfig)
>>   File "NVDAObjects\IAccessible\ia2TextMozilla.py", line 303, in
>> getTextWithFields
>>     return self._getText(True, formatConfig)
>>   File "NVDAObjects\IAccessible\ia2TextMozilla.py", line 252, in _getText
>>     obj = ti.obj
>> AttributeError: 'NoneType' object has no attribute 'obj'
>> INFO - core.main (23:30:24):
>> Exiting
>> INFO - config.ConfigManager.save (23:30:24):
>> Base configuration saved
>> INFO - __main__ (23:30:26):
>> NVDA exit
>>
>>
>> I reopened the issue due to finding it's reproducibility.  I tried going
>> back through the traceback and I don't know the source well enough to
>> throw
>> something to not act on th arrow until the page is loaded completely.
>>
>> NER
>>
>> --
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/nvaccess/nvda/issues/6370#issuecomment-248503831
>
>
> --
> Best Regards
> Bhavya Shah
>
> Avid Enthusiast and User of the Free NVDA Screen Reader (www.nvaccess.org)
>
> Contacting Me
> E-mail Address: bhavya.shah125@gmail.com
> Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
> Mobile Number: +91 7506221750
>


-- 
Best Regards
Bhavya Shah

Avid Enthusiast and User of the Free NVDA Screen Reader (www.nvaccess.org)

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by bhavyashah** [comment]
Worth tackling as part of Project Webfix? @jcsteh @feerrenrut Happy to perform further testing to figure whether the Firefox slowdowns I reported earlier are even related to the scope of this ticket.

**Comment by jcsteh** [comment]
Closing because it seems the originally reported issue is no longer occurring as specified. The subsequent AttributeError finding is covered by #5454.

@bhavyashah, please open new issue(s) covering problems you're still experiencing, including all necessary info. This issue is getting far too confusing to be useful. Thanks. :)

Note that none of the issues discussed here are candidates for webfix, as they aren't issues that commonly hit many users in the wild.

**Comment by bhavyashah** [comment]
Alright.
