### ISSUE TITLE
Outlook 2016 flagged items are not read in the message list

### ISSUE THREAD

**Issue by wallaceid** [nvaccess/nvda#6374]
In the Message List, flagged mails are not read as flagged. This is a property/column just as from, subject and date

**Comment by sucharugupta** [comment]
Yes, I confirm that I am experiencing the same.

**Comment by AlexandreMooc** [comment]
Can confirm with Outlook 2016 and JAWS 2016.2.1. Flag/Completed status not announced in the message list. Only way to inquire such information is to open the message and read the "info bar" in the message header.
