### ISSUE TITLE
Outlook 2016 Calendar date picker does not read out the dates

### ISSUE THREAD

**Issue by wallaceid** [nvaccess/nvda#6375]
The calendar invite date picker does not read out dates. To get there, start a new meeting in Outlook 2016 Calendar and tab to after the date, then press Space to activate. This issue only applies to Office 365.

**Comment by AlexandreMooc** [comment]
Can confirm in Outlook 2016 and NVDA 2016.2.1. Dates and the "Today" button are not being read.

**Comment by sucharugupta** [comment]
I also experience the same with NVDA. While with JAWS, can navigate to dates but only sequentially and there no mechanism to navigate to different month or year.

**Comment by Adriani90** [comment]
@wallaceid, @AlexandreMooc, @sucharugupta are you still having this issue? I cannot reproduce it with NVDA 2019.1 Beta 1 and Outlook 2016 / 365.

**Comment by Adriani90** [comment]
It seems the author is not responding. I cannot reproduce this issue. I close it as works for me. Please comment on it if you still have the issue and we can reopen it. Thanks!
