### ISSUE TITLE
NVDA reads last line in the textarea element

### ISSUE THREAD

**Issue by maximusDreddoff** [nvaccess/nvda#6376]
My problem: 
NVDA reads last line in the textarea element. 

Here is a demo: 
http://codepen.io/Maximusdreddoff/pen/pEjrYN

To reproduce this issue you will need: 
a)	NVDA (version 2016.1) 
b)	Mozilla Firefox 48.0.2/IE 11
c)	Windows 7 

Steps to reproduce: 
1)	Start windows 7
2)	Turn ON NVDA 
3)	Start Mozilla Firefox 48.0.2/ IE11
4)	Go to my DEMO example (http://codepen.io/Maximusdreddoff/pen/pEjrYN)
5)	Set focus to the first input field.
6)	Use tab to navigate to the textarea element.
7)	Listen to the result.

Actual Results:
NVDA announces aria-label(**"Notes. Notes is not valid**") **edit invalid entry multiline** _then last line of the textarea_ (**"at purus at purus at purus"**) 

Expected Results(in JAWS(version 17.0.1377 and 17.0.2211):
NVDA announces aria-label(**"Notes. Notes is not valid**") **edit invalid entry and _doesn't_** read the last line of the textarea

Can you confirm that it is a bug or it is works as designed? Or maybe this behaviour added for some reason (what for)?

**Comment by jcsteh** [comment]
When an editable text field or document gets focus, NVDA reads the line at the cursor so the user knows where they are in the text. This is expected behaviour.
