### ISSUE TITLE
MSHTMl: Checked ARIA radio button reported incorrectly

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#6381]
[Test case](https://github.com/nvaccess/nvda/files/475978/ariaRadio.html.txt) (remove the .txt extension)

STR:
1. Open the test case in IE.
2. Move to the radio button.
3. Check it.
   - Expected: "checked"
   - Actual: "selected"
4. Press NVDA+tab to report the focus.
   - Expected: "R1  radio button  focused  checked"
   - Actual: "R1  radio button  focused  selected  not checked"

It seems MSHTML exposes the selected state via MSAA instead of the checked state for ARIA radio buttons. Interestingly, it exposes it correctly for HTML input type="radio".

**Comment by Adriani90** [comment]
This is still reproducible in NVDA 2019.1 Beta 1.

**Comment by Adriani90** [comment]
Support for IE has ended completely in 2022 and is automatically removed from machines that still have it after an Edge update in February 2023. I don't expect any furtehr updates with regards to accessibility for Internet Explorer or for IE mode in Edge. Closing as abandoned.
