### ISSUE TITLE
Explorer crashes when trying to create a new file or folder

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6384]
When I try to create a new document or folder from Win10x64 Explorer using the ribbon (alt+w,w and choose for example Microsoft Word Document, Explorer crashes most of the attempts. I have been able to reproduce this on two systems with NVDA Next (without add-ons), but it seems to occur in older versions (such as 2016.1) as well. Also tried to reproduce this with another screen reader such as JAWS, but there,  everything works as expected.

When the crash occurs, it seems that explorer reloads and I'm returned to the desktop. When I open a random folder, the contents aren't read by NVDA until I restart the program.

[Here](https://github.com/nvaccess/nvda/files/478111/nvda_new_document_failure.txt) is a log file containing the crash information.

It might be that there is some shell extension I have installed on both PC's, so I'm quite curious whether there are others able to reproduce this. Anyhow, it's slightly annoying.

**Comment by jcsteh** [comment]
If Explorer is crashing, we really need a crash dump from Explorer to debug it. Are you able to provide one? See the Minidumps for Other Applications section of the [Log Files and Crash Dumps](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) article for details. Hopefully, Explorer will oblige; sometimes, we can't generate a minidump this way.

**Comment by leonardder** [comment]
Thanks for the quick rclly.
Unfortunately, as soon as I enable crash dumping, whenever the crash occurs, both NVDA and Explorer freeze. I tried manully shutting down Explorer after the freeze, but that generates no dump. I think I will try to let it run for a while, but I honestly have no hope it will generate something.

**Comment by Brian1Gaff** [comment]
Its very intermittent as well. It can also crash if you use cut and paste a 
lot with two or more folders open in different windows.
 Windows 7 64.
 I'm almost certain this is Windows, not nvda though.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment]
Often looking at the nvda log at this time shows multiple  core frozen in 
stack loops and this I think stops one from actually doing very much about 
it untill things occasionally spring back to life, all is silent.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment]
In my case it also does it from time to time with shift/control n for new 
folder after you press enter wherther you give it a name or its defualt one. 
It also happens in windows 7.
 As I have said before, I'm not totally convinced this is nvda.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by leonardder** [comment]
[Here](https://github.com/nvaccess/nvda/files/479812/nvda_crash_explorer_3900.zip) is a crash dump I have been able to generate.

**Comment by jcsteh** [comment]
Stack from this dump:

> ```
0:061> kp 200
 # Child-SP          RetAddr           Call Site
00 00000000`13dad860 00007fff`c56bc408 UIRibbon!NetUI::Node::GetValue+0x118
01 00000000`13dad8b0 00007fff`ef1c127c UIRibbon!NetUI::DuiAccessible::GetPatternProvider+0x38
02 00000000`13dad8e0 00007fff`ef1acf80 UIAutomationCore!ProviderCallouts::GetPatternProvider+0x4c
03 00000000`13dad940 00007fff`ef1a22c2 UIAutomationCore!MsaaProxy::GetPatternProvider+0xf0
04 00000000`13dad9b0 00007fff`ef1a41ac UIAutomationCore!UiaNode::ProviderGetPatternProvider+0x2d2
05 00000000`13dada60 00007fff`ef1a1b46 UIAutomationCore!UiaNode::ProviderGetPropertyValue+0x5dc
06 00000000`13dadb70 00007fff`ef1a03fd UIAutomationCore!InProcClientAPIStub::UiaNode_GetPropertyValues+0xf6
07 00000000`13dadc20 00007fff`ef1a47ca UIAutomationCore!InProcClientAPIStub::InvokeInProcAPI+0xcd
08 00000000`13dadc60 00007fff`ef1c5a98 UIAutomationCore!UiaNode::CrossProcess_GetPropertyValues+0x2ea
09 00000000`13dadd50 00007fff`ef1c6145 UIAutomationCore!RemoteUiaNodeStub::Incoming_GetPropertyValues+0x1d8
0a 00000000`13dade10 00007fff`ef1aff6b UIAutomationCore!RemoteUiaNodeStub::OnMessage+0x55
0b 00000000`13dade50 00007fff`ef1bb59f UIAutomationCore!InvokeOnCorrectContext_Callback+0xab
0c 00000000`13dadee0 00007fff`ef1bb244 UIAutomationCore!ProcessIncomingRequest+0x18f
0d 00000000`13dadfe0 00007fff`ef1c6517 UIAutomationCore!HookBasedServerConnectionManager::HookCallback+0x204
0e 00000000`13daf0c0 00007fff`ef1be3a5 UIAutomationCore!HookUtil<&HookBasedClientConnection::HookCallback,0>::CallOut+0x17
0f 00000000`13daf100 00007fff`ef1be097 UIAutomationCore!HandleHookMessage+0x295
10 00000000`13daf280 00007fff`f3faeb02 UIAutomationCore!HookUtil<&HookBasedClientConnection::HookCallback,0>::CallWndProc+0x37
11 00000000`13daf2c0 00007fff`f3fb2563 user32!fnHkINLPCWPSTRUCTW+0x82
12 00000000`13daf310 00007fff`f68f89d4 user32!_fnDWORD+0x33
13 00000000`13daf370 00007fff`f2dc1184 ntdll!KiUserCallbackDispatcherContinue
14 00000000`13daf3f8 00007fff`f3fa87c2 win32u!NtUserMessageCall+0x14
15 00000000`13daf400 00007fff`f3faeb02 user32!CallNextHookEx+0x1b2
16 00000000`13daf450 00007fff`f3fb2563 user32!fnHkINLPCWPSTRUCTW+0x82
17 00000000`13daf4a0 00007fff`f68f89d4 user32!_fnDWORD+0x33
18 00000000`13daf500 00007fff`f2dc2da4 ntdll!KiUserCallbackDispatcherContinue
19 00000000`13daf588 00007fff`edd6bebd win32u!NtUserRealInternalGetMessage+0x14
1a 00000000`13daf590 00007fff`edd6bb02 duser!CoreSC::xwProcessNL+0x1ad
1b 00000000`13daf630 00007fff`f3fb6434 duser!MphProcessMessage+0xb2
1c 00000000`13daf690 00007fff`f68f89d4 user32!_ClientGetMessageMPH+0x44
1d 00000000`13daf730 00007fff`f2dc10c4 ntdll!KiUserCallbackDispatcherContinue
1e 00000000`13daf7a8 00007fff`f3fae52e win32u!NtUserPeekMessage+0x14
1f 00000000`13daf7b0 00007fff`d2d2a61b user32!PeekMessageW+0xfe
20 00000000`13daf7f0 00007fff`d2d54916 explorerframe!CExplorerFrame::FrameMessagePump+0x5b
21 00000000`13daf880 00007fff`d2d541c2 explorerframe!BrowserThreadProc+0x76
22 00000000`13daf8d0 00007fff`d2d54172 explorerframe!BrowserNewThreadProc+0x3a
23 00000000`13daf900 00007fff`d2cffa46 explorerframe!CExplorerTask::InternalResumeRT+0x12
24 00000000`13daf930 00007fff`f323ccff explorerframe!CRunnableTask::Run+0x536
25 00000000`13dafa00 00007fff`f323baa8 windows_storage!CShellTask::TT_Run+0x4f
26 00000000`13dafa30 00007fff`f323e90f windows_storage!CShellTaskThread::ThreadProc+0xd0
27 00000000`13dafae0 00007fff`f3865aad windows_storage!CShellTaskThread::s_ThreadProc+0x2f
28 00000000`13dafb10 00007fff`f3dc8364 SHCore!Microsoft::WRL::Details::RuntimeClass<Microsoft::WRL::Details::InterfaceList<CRandomAccessStreamBase,Microsoft::WRL::Details::InterfaceList<Windows::Storage::Streams::IRandomAccessStreamWithContentType,Microsoft::WRL::Details::InterfaceList<Windows::Storage::Streams::IContentTypeProvider,Microsoft::WRL::Details::InterfaceList<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<3>,Microsoft::WRL::CloakedIid<IRandomAccessStreamMode>,Microsoft::WRL::CloakedIid<IRandomAccessStreamFileAccessMode>,Microsoft::WRL::CloakedIid<IObjectWithDeferredInvoke>,Microsoft::WRL::CloakedIid<IObjectWithFileHandle>,Microsoft::WRL::CloakedIid<IUnbufferedFileHandleProvider>,Microsoft::WRL::CloakedIid<IRandomAccessStreamPrivate>,Microsoft::WRL::CloakedIid<ITransactedModeOverride>,Microsoft::WRL::CloakedIid<CFTMCrossProcServer>,Microsoft::WRL::Details::Nil>,Microsoft::WRL::Details::Nil> > > >,Microsoft::WRL::RuntimeClassFlags<3>,1,1,0>::~RuntimeClass<Microsoft::WRL::Details::InterfaceList<CRandomAccessStreamBase,Microsoft::WRL::Details::InterfaceList<Windows::Storage::Streams::IRandomAccessStreamWithContentType,Microsoft::WRL::Details::InterfaceList<Windows::Storage::Streams::IContentTypeProvider,Microsoft::WRL::Details::InterfaceList<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<3>,Microsoft::WRL::CloakedIid<IRandomAccessStreamMode>,Microsoft::WRL::CloakedIid<IRandomAccessStreamFileAccessMode>,Microsoft::WRL::CloakedIid<IObjectWithDeferredInvoke>,Microsoft::WRL::CloakedIid<IObjectWithFileHandle>,Microsoft::WRL::CloakedIid<IUnbufferedFileHandleProvider>,Microsoft::WRL::CloakedIid<IRandomAccessStreamPrivate>,Microsoft::WRL::CloakedIid<ITransactedModeOverride>,Microsoft::WRL::CloakedIid<CFTMCrossProcServer>,Microsoft::WRL::Details::Nil>,Microsoft::WRL::Details::Nil> > > >,Microsoft::WRL::RuntimeClassFlags<3>,1,1,0>+0x135
29 00000000`13dafc00 00007fff`f68b5e91 kernel32!BaseThreadInitThunk+0x14
2a 00000000`13dafc30 00000000`00000000 ntdll!RtlUserThreadStart+0x21
```

So, it looks like it's crashing when UIA tries to get some info from the ribbon. There is no NVDA injected code here, so we're not responsible for the crash.

As to why it doesn't occur with JAWS, I'm guessing maybe it doesn't respond to the particular event from the object that is misbehaving. It's hard to work out what event/object is causing this without being able to reproduce it, though. I can't reproduce it at all here with Win 10 x64.

What I do find curious is that in the NVDA log you provided, we froze trying to get an MSAA role, yet the crash seems to be related to a UIA object. I guess perhaps we got a UIA event for that object in a background thread and that already crashed Explorer by that point.

**Comment by jcsteh** [comment]
Actually, it's possible JAWS doesn't listen for UIA events here at all.

Can you reproduce this with Narrator?

**Comment by leonardder** [comment]
I retested Narrator and indeed, the system sometimes seems to freeze for 
like 10 seconds, but instead of an explorer crash, the system resumes 
where it freezes. But there's certainly something wrong somewhere.

Sent on behalf of @BabbageCom

**Comment by Brian1Gaff** [comment]
Actually Explorer crashes in 7 and 10 on my machine quite often when 
creating a new folder using the keyboard shortcut, and has crashed also 
while indexing files in a remote folder as well. I think its just a Windows 
bug, since a sighted friend gets it sometimes as well.
 One might have supposed Microsoft might have sorted it by now unless its 
dependent on something else like a display driver or other code. Its 
irritating especially if you open several explorer windows at the same time 
as when Explorer reboots it closes all the instances and goes back to 
desktop!

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by jcsteh** [comment]
Full dump analysis:

```
0:061> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

*** WARNING: Unable to verify timestamp for sppc.dll
*** ERROR: Module load completed but symbols could not be loaded for sppc.dll
*** WARNING: Unable to verify timestamp for DropboxExt64.65536.dll
*** ERROR: Module load completed but symbols could not be loaded for DropboxExt64.65536.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for winmm.dll - 
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for msiltcfg.dll - 
*** WARNING: Unable to verify timestamp for nvdaHelperRemote.dll

DUMP_CLASS: 2

DUMP_QUALIFIER: 400

CONTEXT:  (.ecxr)
rax=0000000000000400 rbx=00007fffc57b2220 rcx=0000000000000000
rdx=00007fffc58ac7a8 rsi=0000000000000000 rdi=0000000000000000
rip=00007fffc563c3fc rsp=0000000013dad860 rbp=00007fffc58ac7a8
 r8=0000000000000000  r9=0000000000000000 r10=00000ffff8ad787a
r11=0401000050000000 r12=0000000000000000 r13=00007fffef2df730
r14=0000000013dad9b0 r15=0000000013dada60
iopl=0         nv up ei pl zr na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246
UIRibbon!NetUI::Node::GetValue+0x118:
00007fff`c563c3fc 488b06          mov     rax,qword ptr [rsi] ds:00000000`00000000=????????????????
Resetting default scope

FAULTING_IP: 
UIRibbon!NetUI::Node::GetValue+118
00007fff`c563c3fc 488b06          mov     rax,qword ptr [rsi]

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007fffc563c3fc (UIRibbon!NetUI::Node::GetValue+0x0000000000000118)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000000
Attempt to read from address 0000000000000000

DEFAULT_BUCKET_ID:  NULL_POINTER_READ

PROCESS_NAME:  explorer.exe

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  0000000000000000

FOLLOWUP_IP: 
UIRibbon!NetUI::Node::GetValue+118
00007fff`c563c3fc 488b06          mov     rax,qword ptr [rsi]

READ_ADDRESS:  0000000000000000 

BUGCHECK_STR:  NULL_POINTER_READ

WATSON_BKT_PROCSTAMP:  57899981

WATSON_BKT_PROCVER:  10.0.14393.0

PROCESS_VER_PRODUCT:  Microsoft® Windows® Operating System

WATSON_BKT_MODULE:  UIRibbon.dll

WATSON_BKT_MODSTAMP:  578998a5

WATSON_BKT_MODOFFSET:  ec3fc

WATSON_BKT_MODVER:  10.0.14393.0

MODULE_VER_PRODUCT:  Microsoft® Windows® Operating System

BUILD_VERSION_STRING:  10.0.14393.0 (rs1_release.160715-1616)

MODLIST_WITH_TSCHKSUM_HASH:  116af3682df43b01898ba7078cdb08be3aa18976

MODLIST_SHA1_HASH:  95e26000c16f46aba3c6473ea9ff203341671a79

DUMP_FLAGS:  0

DUMP_TYPE:  2

ANALYSIS_SESSION_HOST:  ELECTRUM

ANALYSIS_SESSION_TIME:  10-28-2016 12:17:00.0764

ANALYSIS_VERSION: 10.0.14321.1024 amd64fre

THREAD_ATTRIBUTES: 
PROBLEM_CLASSES: 



NULL_POINTER_READ
    Tid    [0xb504]
    Frame  [0x00]: UIRibbon!NetUI::Node::GetValue


LAST_CONTROL_TRANSFER:  from 00007fffc56bc408 to 00007fffc563c3fc

STACK_TEXT:  
00000000`13dad860 00007fff`c56bc408 : 00000000`13dad9b0 00000000`13dad980 00000000`176dc298 00007fff`c56bad00 : UIRibbon!NetUI::Node::GetValue+0x118
00000000`13dad8b0 00007fff`ef1c127c : 00000000`13dad9b0 00000000`176dc298 00000000`0000271e 00007fff`ef1afe11 : UIRibbon!NetUI::DuiAccessible::GetPatternProvider+0x38
00000000`13dad8e0 00007fff`ef1acf80 : 00000000`00000000 00000000`14b71940 00000000`13dad9f9 00000000`00000002 : UIAutomationCore!ProviderCallouts::GetPatternProvider+0x4c
00000000`13dad940 00007fff`ef1a22c2 : 00000000`00000000 00000000`00000000 00000000`00007532 00000000`176dc298 : UIAutomationCore!MsaaProxy::GetPatternProvider+0xf0
00000000`13dad9b0 00007fff`ef1a41ac : 00000000`00000000 00007fff`ef2df730 00000000`0f99ff28 00000000`00000000 : UIAutomationCore!UiaNode::ProviderGetPatternProvider+0x2d2
00000000`13dada60 00007fff`ef1a1b46 : 00000000`000000c0 00000000`00000000 00000000`00000008 00000000`00000008 : UIAutomationCore!UiaNode::ProviderGetPropertyValue+0x5dc
00000000`13dadb70 00007fff`ef1a03fd : 00000000`00000000 00007fff`f61b9dac 00000000`00000010 00000000`0f99fe80 : UIAutomationCore!InProcClientAPIStub::UiaNode_GetPropertyValues+0xf6
00000000`13dadc20 00007fff`ef1a47ca : 00000000`14a91570 00000000`00000003 00000000`0328f540 00000000`00000000 : UIAutomationCore!InProcClientAPIStub::InvokeInProcAPI+0xcd
00000000`13dadc60 00007fff`ef1c5a98 : 00000000`0328f540 00000000`00000000 00000000`00000008 00000000`14a914b0 : UIAutomationCore!UiaNode::CrossProcess_GetPropertyValues+0x2ea
00000000`13dadd50 00007fff`ef1c6145 : 00000000`0328f540 00000000`148a9810 00000000`148a9810 00000000`0328f540 : UIAutomationCore!RemoteUiaNodeStub::Incoming_GetPropertyValues+0x1d8
00000000`13dade10 00007fff`ef1aff6b : 00000000`00000000 00000000`00000000 00000000`00000000 00007fff`f14c91c0 : UIAutomationCore!RemoteUiaNodeStub::OnMessage+0x55
00000000`13dade50 00007fff`ef1bb59f : 00000000`00002b40 00000000`00000000 00000000`13dadf79 00000000`13dae018 : UIAutomationCore!InvokeOnCorrectContext_Callback+0xab
00000000`13dadee0 00007fff`ef1bb244 : 00000000`0320e1b0 00000000`ffffffff 00000000`148a9810 00000000`000005fd : UIAutomationCore!ProcessIncomingRequest+0x18f
00000000`13dadfe0 00007fff`ef1c6517 : 00000000`0c9a0000 00000000`00000092 00000000`0326f7b0 00000000`0c9a0000 : UIAutomationCore!HookBasedServerConnectionManager::HookCallback+0x204
00000000`13daf0c0 00007fff`ef1be3a5 : 00000000`000002c2 00007fff`ed5142ea 00000000`13daf0b8 00000000`00002d18 : UIAutomationCore!HookUtil<&HookBasedClientConnection::HookCallback,0>::CallOut+0x17
00000000`13daf100 00007fff`ef1be097 : 00000000`00000000 00000000`104bd668 0000aa33`17804280 00007fff`f60a8fc5 : UIAutomationCore!HandleHookMessage+0x295
00000000`13daf280 00007fff`f3faeb02 : 00000000`00000400 00000000`00040000 00000000`0000c185 00000000`17804280 : UIAutomationCore!HookUtil<&HookBasedClientConnection::HookCallback,0>::CallWndProc+0x37
00000000`13daf2c0 00007fff`f3fb2563 : 00000000`00000000 00000000`00000010 00000000`00000000 00000000`00000000 : user32!fnHkINLPCWPSTRUCTW+0x82
00000000`13daf310 00007fff`f68f89d4 : 00000000`00000000 00000000`00000000 00000000`0a55e138 00007fff`f608f303 : user32!_fnDWORD+0x33
00000000`13daf370 00007fff`f2dc1184 : 00007fff`f3fa87c2 00000000`00000000 00007fff`c555d890 00000000`00000000 : ntdll!KiUserCallbackDispatcherContinue
00000000`13daf3f8 00007fff`f3fa87c2 : 00000000`00000000 00007fff`c555d890 00000000`00000000 00000000`00000000 : win32u!NtUserMessageCall+0x14
00000000`13daf400 00007fff`f3faeb02 : 00000000`00000000 00000000`0000138e 00000000`13daf6e8 00000000`0000c185 : user32!CallNextHookEx+0x1b2
00000000`13daf450 00007fff`f3fb2563 : 00000000`00000000 00000000`13daf6e8 00000000`00000000 00000000`00000000 : user32!fnHkINLPCWPSTRUCTW+0x82
00000000`13daf4a0 00007fff`f68f89d4 : b5040f3c`000e800f 057c2fcc`089634b2 00000000`00000400 00000000`0a4d8b90 : user32!_fnDWORD+0x33
00000000`13daf500 00007fff`f2dc2da4 : 00007fff`edd6bebd 00000000`00000000 00007fff`f323013a 00000000`00000b04 : ntdll!KiUserCallbackDispatcherContinue
00000000`13daf588 00007fff`edd6bebd : 00000000`00000000 00007fff`f323013a 00000000`00000b04 00000000`10559bc0 : win32u!NtUserRealInternalGetMessage+0x14
00000000`13daf590 00007fff`edd6bb02 : 00000000`00000000 00000000`13daf6e8 00000000`00000000 00000000`00000000 : duser!CoreSC::xwProcessNL+0x1ad
00000000`13daf630 00007fff`f3fb6434 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : duser!MphProcessMessage+0xb2
00000000`13daf690 00007fff`f68f89d4 : 00000000`00000000 00000000`018ade20 00000000`00000000 00000000`0000babe : user32!_ClientGetMessageMPH+0x44
00000000`13daf730 00007fff`f2dc10c4 : 00007fff`f3fae52e 00000000`00000001 00007fff`d2dcb8f8 00000000`00000001 : ntdll!KiUserCallbackDispatcherContinue
00000000`13daf7a8 00007fff`f3fae52e : 00000000`00000001 00007fff`d2dcb8f8 00000000`00000001 00000000`13dafa60 : win32u!NtUserPeekMessage+0x14
00000000`13daf7b0 00007fff`d2d2a61b : 00000000`ffffffff 00000000`00000001 00000000`10332eb0 00000000`10332eb0 : user32!PeekMessageW+0xfe
00000000`13daf7f0 00007fff`d2d54916 : 00000000`10332eb0 00000000`13daf999 00000000`00000006 00000000`17213370 : explorerframe!CExplorerFrame::FrameMessagePump+0x5b
00000000`13daf880 00007fff`d2d541c2 : 00000000`10332eb0 00000000`1046d210 00000000`17213370 00000000`00000000 : explorerframe!BrowserThreadProc+0x76
00000000`13daf8d0 00007fff`d2d54172 : 14c1b6e6`000012fe 00000000`1049c910 00000000`00000000 00000000`13daf9c9 : explorerframe!BrowserNewThreadProc+0x3a
00000000`13daf900 00007fff`d2cffa46 : 0000cf5f`c56fe330 00000000`100dd250 00000000`13dafa60 00000000`00000001 : explorerframe!CExplorerTask::InternalResumeRT+0x12
00000000`13daf930 00007fff`f323ccff : 00000000`00000f3c 00000000`0000b504 00000000`0000000f 00000000`0000000b : explorerframe!CRunnableTask::Run+0x536
00000000`13dafa00 00007fff`f323baa8 : 00000000`100dd250 00000000`13dafab0 00000000`1049c250 00000000`100dd250 : windows_storage!CShellTask::TT_Run+0x4f
00000000`13dafa30 00007fff`f323e90f : 00000000`100dd250 00000000`100dd250 00000000`00000000 00000000`00000000 : windows_storage!CShellTaskThread::ThreadProc+0xd0
00000000`13dafae0 00007fff`f3865aad : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : windows_storage!CShellTaskThread::s_ThreadProc+0x2f
00000000`13dafb10 00007fff`f3dc8364 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : SHCore!Microsoft::WRL::Details::RuntimeClass<Microsoft::WRL::Details::InterfaceList<CRandomAccessStreamBase,Microsoft::WRL::Details::InterfaceList<Windows::Storage::Streams::IRandomAccessStreamWithContentType,Microsoft::WRL::Details::InterfaceList<Windows::Storage::Streams::IContentTypeProvider,Microsoft::WRL::Details::InterfaceList<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<3>,Microsoft::WRL::CloakedIid<IRandomAccessStreamMode>,Microsoft::WRL::CloakedIid<IRandomAccessStreamFileAccessMode>,Microsoft::WRL::CloakedIid<IObjectWithDeferredInvoke>,Microsoft::WRL::CloakedIid<IObjectWithFileHandle>,Microsoft::WRL::CloakedIid<IUnbufferedFileHandleProvider>,Microsoft::WRL::CloakedIid<IRandomAccessStreamPrivate>,Microsoft::WRL::CloakedIid<ITransactedModeOverride>,Microsoft::WRL::CloakedIid<CFTMCrossProcServer>,Microsoft::WRL::Details::Nil>,Microsoft::WRL::Details::Nil> > > >,Microsoft::WRL::RuntimeClassFlags<3>,1,1,0>::~RuntimeClass<Microsoft::WRL::Details::InterfaceList<CRandomAccessStreamBase,Microsoft::WRL::Details::InterfaceList<Windows::Storage::Streams::IRandomAccessStreamWithContentType,Microsoft::WRL::Details::InterfaceList<Windows::Storage::Streams::IContentTypeProvider,Microsoft::WRL::Details::InterfaceList<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<3>,Microsoft::WRL::CloakedIid<IRandomAccessStreamMode>,Microsoft::WRL::CloakedIid<IRandomAccessStreamFileAccessMode>,Microsoft::WRL::CloakedIid<IObjectWithDeferredInvoke>,Microsoft::WRL::CloakedIid<IObjectWithFileHandle>,Microsoft::WRL::CloakedIid<IUnbufferedFileHandleProvider>,Microsoft::WRL::CloakedIid<IRandomAccessStreamPrivate>,Microsoft::WRL::CloakedIid<ITransactedModeOverride>,Microsoft::WRL::CloakedIid<CFTMCrossProcServer>,Microsoft::WRL::Details::Nil>,Microsoft::WRL::Details::Nil> > > >,Microsoft::WRL::RuntimeClassFlags<3>,1,1,0>+0x135
00000000`13dafc00 00007fff`f68b5e91 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
00000000`13dafc30 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21


THREAD_SHA1_HASH_MOD_FUNC:  dd02f0d9e3b5c9634e3a0c4ce30c4a6233797bb2

THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  c956556dcbdd03c6bd22d80b2ac07b09e8012c7e

THREAD_SHA1_HASH_MOD:  0777ba676e16d9f194b386ecf0b748beac060f32

FAULT_INSTR_CODE:  41068b48

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  UIRibbon!NetUI::Node::GetValue+118

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: UIRibbon

IMAGE_NAME:  UIRibbon.dll

DEBUG_FLR_IMAGE_TIMESTAMP:  578998a5

STACK_COMMAND:  .ecxr ; kb

BUCKET_ID:  NULL_POINTER_READ_UIRibbon!NetUI::Node::GetValue+118

PRIMARY_PROBLEM_CLASS:  NULL_POINTER_READ_UIRibbon!NetUI::Node::GetValue+118

FAILURE_EXCEPTION_CODE:  c0000005

FAILURE_IMAGE_NAME:  UIRibbon.dll

BUCKET_ID_IMAGE_STR:  UIRibbon.dll

FAILURE_MODULE_NAME:  UIRibbon

BUCKET_ID_MODULE_STR:  UIRibbon

FAILURE_FUNCTION_NAME:  NetUI::Node::GetValue

BUCKET_ID_FUNCTION_STR:  NetUI::Node::GetValue

BUCKET_ID_OFFSET:  118

BUCKET_ID_MODTIMEDATESTAMP:  578998a5

BUCKET_ID_MODCHECKSUM:  3e2894

BUCKET_ID_MODVER_STR:  10.0.14393.0

BUCKET_ID_PREFIX_STR:  NULL_POINTER_READ_

FAILURE_PROBLEM_CLASS:  NULL_POINTER_READ

FAILURE_SYMBOL_NAME:  UIRibbon.dll!NetUI::Node::GetValue

FAILURE_BUCKET_ID:  NULL_POINTER_READ_c0000005_UIRibbon.dll!NetUI::Node::GetValue

WATSON_STAGEONE_URL:  http://watson.microsoft.com/StageOne/explorer.exe/10.0.14393.0/57899981/UIRibbon.dll/10.0.14393.0/578998a5/c0000005/000ec3fc.htm?Retriage=1

TARGET_TIME:  2016-09-19T11:09:10.000Z

OSBUILD:  14393

OSSERVICEPACK:  0

SERVICEPACK_NUMBER: 0

OS_REVISION: 0

SUITE_MASK:  256

PRODUCT_TYPE:  1

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

OSEDITION:  Windows 10 WinNt SingleUserTS

OS_LOCALE:  

USER_LCID:  0

OSBUILD_TIMESTAMP:  2016-07-16 12:21:29

BUILDDATESTAMP_STR:  160715-1616

BUILDLAB_STR:  rs1_release

BUILDOSVER_STR:  10.0.14393.0

ANALYSIS_SESSION_ELAPSED_TIME: 10321a

ANALYSIS_SOURCE:  UM

FAILURE_ID_HASH_STRING:  um:null_pointer_read_c0000005_uiribbon.dll!netui::node::getvalue

FAILURE_ID_HASH:  {b45f3eb4-03ec-e316-9a42-cb5ee8d6d8ff}

Followup:     MachineOwner
---------
```

**Comment by Brian1Gaff** [comment]
Was this with a machine which has no nvda or other screenreader remnents?
 However I suspect that it will still hang and sometimes fall over as my 
sighted friends say this has been happening intermittently since Windows 7, 
but of course as we all know the sighted can do things different ways to us, 
so it could be we just fall foul of it more often due to the way we use 
windows. I have also noticed that if you set up explorer so it opens new 
instances of explorer windows for all folders so you effectively have lots 
of them open at a time that its far more likely to crash.
 Anecdotal, but seems real to me.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by michaelDCurran** [comment]
We have had no luck in reproducing this issue on demand. It also looks as if the bug is in Explorer itself. If this can be reproduced on demand in the future, please report the bug to Microsoft via the Feedback tool, or provide instructions on this issue that can reproduce the bug on demand and I can pass this along to Microsoft.
