### ISSUE TITLE
NVDA is reading clickable bullet for <ul><li> in Google Chrome

### ISSUE THREAD

**Issue by santospro** [nvaccess/nvda#6399]
Using NVDA with Google Chrome in Windows 10 (also in Windows 7).

http://codepen.io/santospro/pen/bwgLLm

Navigating using Down/Up arrow key, I'm hearing 'clickable bullet first item' and 'clickable bullet second item'.

```
<button>Empty action</button>
<p>
  You should accept these items:
  <ul>
    <li>First item</li>
    <li>Second item</li>
  </ul>
</p>
```

**Comment by bhavyashah** [comment]
Related to Project Webfix? @jcsteh @feerrenrut

**Comment by feerrenrut** [comment]
Closing as duplicate, please see #7430.
