### ISSUE TITLE
Unable to access context menu items in TeamSpeak 3 client more than once

### ISSUE THREAD

**Issue by mjanusauskas** [nvaccess/nvda#6403]
Install the TeamSpeak 3 client available here:
https://www.teamspeak.com/downloads
In the main channel window access the context menu on a channel or user name either via the context key or Shift+F10.
Observe that after doing this once subsequent attempts seem to open the menu but NVDA is unable to read any of the menu items.

**Comment by jcsteh** [comment]
Does this also occur with Narrator? I suspect it does. If so, this is a bug that needs to be fixed in TeamSpeak.

**Comment by mjanusauskas** [comment]
You are correct, the issue also happens with Narrator. I will attempt to
report the issue to the TeamSpeak developers.

**Comment by jcsteh** [comment]
Okay. Closing, since this is a bug in TeamSpeak.
