### ISSUE TITLE
NVDA crashing if I use the escape key to close an event in the windows event viewer

### ISSUE THREAD

**Issue by pranavlal** [nvaccess/nvda#6406]
NVDA 2016.3 freezes if I use the escape key to exit an event in the windows event viewer. To duplicate this do the following.
1. Launch the windows event viewer.
2. Brows to the application logs.
3. Arrow to an event of interest and hit enter to open it.
4. Tab to the edit box containing the details of the event and read it using the up and down arrow keys.
5. Hit escape to close this event and return to the list of events.
6. If NVDA does not stop speaking, look at a few more events.
7. If you want to avoid NVDA hanging, tab to the "close" button when an event is open and press enter to activate it and return to the event viewer.
OS=Windows 10 professional 64bit
Version 1607 (OS Build 14393.187)
I am attaching the log that was generated during the above steps. I have set the logging level to debug.
[nvda-old-logEventViewer.txt](https://github.com/nvaccess/nvda/files/491433/nvda-old-logEventViewer.txt)

**Comment by jcsteh** [comment]
@MichaelDCurran was able to reproduce this in Windows 10 build 14393. Narrator also exhibits this problem in build 14393. However, I can't reproduce it in insider build 14936. As discussed on IRC, @tspivey was also experiencing this issue, but can no longer reproduce in recent insider builds.
