### ISSUE TITLE
Excel 2016: NVDA May Be Getting Stuck In Forms Mode When Using DropDowns

### ISSUE THREAD

**Issue by jhomme** [nvaccess/nvda#6409]
Steps to reproduce: 

I have a web page open 

I also have Excel open. 

In the Excel workbook, I have dropdown's. 

I move into a dropdown and press ALT+DownArrow, select a choice, and press ENTER. 

NVDA stops speaking and the symptoms with navigation keys make it seem as though I can no longer navigate. 

When I go back to the web page, I hear the tone that NVDA uses when I hit ESCAPE to take it out of Application or Forms mode. This happens even though I have not been working with controls on the web.

**Comment by jhomme** [comment]
NVDA version is 2016.3.

**Comment by jcsteh** [comment]
Please provide a log at level input/output illustrating this issue. Also, if possible, please provide a sample spreadsheet exhibiting this issue. Thanks.

**Comment by ehollig** [comment]
Just a friendly reminder for @jhomme to respond to @jcsteh with the requested information in https://github.com/nvaccess/nvda/issues/6409#issuecomment-250028939

**Comment by ehollig** [comment]
Closing as invalid. If @jhomme is still experiencing this issue, please provide exact steps to reproduce the issue, along with the requested information in https://github.com/nvaccess/nvda/issues/6409#issuecomment-250028939
