### ISSUE TITLE
Object nav in flow: ability to let next/previous object in flow to detect objects it should not navigate to

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#6413]
Hi,

While investigating how to emulate scan mode in ObjPad add-on, I noticed the following (this may have been brought up before):

When you move to next or previous object in flow, there are objects NVDA should (ideally) not have access to. These include:
- A child item whose name matches that of its parent.
- Child of links, buttons and others.
- Graphical objects with no label whatsoever.
- Windows 8.x Start screen tile labels.

Thus I propose teaching next/prev objects in flow commands (currently implemented as one finger left/right flick) to recognize these controls and avoid them. These can be specified via a set of roles to avoid, or the navigator object can specify that object in flow should not be used to enter its children, or a better heuristic could be used.

Thanks.

**Comment by PratikP1** [comment]
There are occasions that require one to explore links and buttons to discover what they are. This is especially true when NVDA reports blank for links. I recommend keeping this functionality.

**Comment by Adriani90** [comment]
@PratikP1 could you please give an example where an user would need to access the child of such a parent?

**Comment by josephsl** [comment]
Hi,

2024 update: I think letting object navigation algorithm move to deepest child (in flow) makes more sense as there are places such as Windows Settings app with crucial information shown but is not keyboard focusable. Besides, I haven't visited this in a while. Closing as abandoned (for now).

Thanks.
