### ISSUE TITLE
NVDA announce word count wrongly with Chinese or mixed Chinese and English   

### ISSUE THREAD

**Issue by lstar4ever** [nvaccess/nvda#6418]
I am a Chinese user.
For example if I type a piece of pessage in word, then I press ctrl+a to select all, NVDA will say how many words have been selected.
However, the word count announce here is totally different from the word count made by microsoft word. 
This problem occurs when the content contains Chinese words, and the NVDA word count is usually highly bigger than that of the Microsoft word.

And the word count problem doesn't limited to word, for example if I do select all in Firefox, the word count is also incorrect.

**Comment by lstar4ever** [comment]
Well, thanks for your reply.
In Chinese, word are made up of more than one characters.
'Is it actually suggesting that the count is of words, not characters?' 
How can I check out that?


James Teh 於 5/10/2016 12:10 寫道:

**Comment by jcsteh** [comment]
What I mean is that in English, NVDA says, for example, "1000 characters
selected". Are you saying that in Chinese, it says "1000 words selected"?
If so, this is a problem in the Chinese translation. Which Chinese
translation are you using: China, Hong Kong or Taiwan?

**Comment by lstar4ever** [comment]
Oh, sorry. NVDA made it right. when selecting lots of word, it said how 
many characters selected. There is no problem with the translation.

James Teh 於 5/10/2016 12:53 寫道:

**Comment by jcsteh** [comment]
Okay. In that case, there is no issue: NVDA is reporting characters, not words, which is why you're seeing a higher number than you expected.

**Comment by bhavyashah** [comment]
Hi,
In the case of the Hindi language, when I type a certain paragraph of
text in Hindi characters, press Ctrl+A to select them all, following
are the results:
NVDA - 1046 characters selected
Microsoft Word Count - 1,041 characters (with spaces)
Although this may be a trivial issue, reporting it for reference all the same.
Thanks.

On 10/5/16, James Teh <notifications@github.com> wrote:
> Okay. In that case, there is no issue: NVDA is reporting characters, not
> words, which is why you're seeing a higher number than you expected.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6418#issuecomment-251582970


-- 
Best Regards
Bhavya Shah

Avid Enthusiast and User of the Free NVDA Screen Reader (www.nvaccess.org)

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750
