### ISSUE TITLE
NVDA does not behave correctly when selecting messages in GMail using Chrome

### ISSUE THREAD

**Issue by ssawczyn** [nvaccess/nvda#6425]
When selecting messages in GMail for move/deletion using Chrome, NVDA reads the incorrectly focused message.  To replicate:

1. Open GMail in standard view using Chrome.
2. Arrow down to a message that you wish to select.
3. Press the 'x' key which is the GMail shortcut to select the message.
4. Press the down arrow to go to the next message.

What should happen:
NVDA should read the newly focused message.

What does happen:
NVDA reads the line containing the just-selected message and indicates its state even though focus has moved away from this.  After reading this line, NVDA then proceeds to read the newly-focused line.  It's almost as if a delay is needed to give NVDA a chance to recognize that the focus has shifted.

**Comment by jcsteh** [comment]
Same underlying issue as #6421.
