### ISSUE TITLE
Flash Based Controls Aren't Accessible

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#6431]
Flash based controls aren't accessible if they fall below a certain width or height. I'm not exactly sure what the width or height is, but making both larger makes flash controls accessible and clickable without issue.
This needs to be fixed so that all widths and sizes are clickable through NVDA.

**Comment by bhavyashah** [comment]
@jcsteh Umm, why is this ticket blocked but not closed?
@Elshara  Regardless, could you please provide a test case for this issue where there are both Flash based controls of a width/height you consider accessible as well as their inaccessible counterparts with a lesser width/height? You may need to provide more detailed information for your issue to be diagnosed thoroughly.
As a side note though, Flash shall be discontinued in 2020 by Adobe, if I am not wrong, making Flash accessibility a drastically lower priority for not only NVDA developers but also users, and thus, this ticket might not witness active investigation.

**Comment by jcsteh** [comment]
This is blocked because the reporter needs to provide additional info before this issue can be considered valid. However, it seems I either forgot to comment or my comment didn't submit for some reason. :(

@@Elshara, please provide the info requested by bhavyashah above. Thanks.

Triage note: we should close this within a few weeks if the required information is not provided.

**Comment by derekriemer** [comment]
Closing, because the reporter has not provided us with the requested information.

**Comment by Elshara** [comment]
A perfect example of this use case scenario is:
https://tinychat.com/gaydays
Click allow to use flash and then try to navigate.
Another use case is:
http://thedrip.net/
Look for embedded objects. You may have to click allow.

**Comment by Adriani90** [comment]
@Elshara in your first example the controls are actually accessible. In the second example there is a html5 object and not a flash object. This is also fully accessible.
Are you still having this issue though?

**Comment by Elshara** [comment]
You could say that yes. Especially with newer releases of NVDA, I'm
finding no flash objects are accessible anymore. The browser just
crashes when NVDA tries to interact with it.

**Comment by DrSooom** [comment]
See also: Issue https://github.com/nvaccess/nvda/issues/11131#issuecomment-753320290

**Comment by CyrilleB79** [comment]
Hello
Due to Flash support removal (#12207), this PR should probably closed with WONT FIX label.
Cc @leonardder, @feerrenrut
