### ISSUE TITLE
Problem Activating Fields In Browse Mode

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#6432]
1. Some labels aren't read on the browse form using arrow keys, but are using tab keys. Such as the create new issue form on git hub for instance.
2. Recent versions of NVDA do not respect the ability to review combo boxes before activating them if no save, go or next button exists as a stand alone button. The chapter selection drop down box on fan fiction, fiction press and other such websites is an excellent example of this.
   The text issue happens in all browsers as does the combo box issue.

**Comment by Brian1Gaff** [comment]
There are multiple issues with firefox on current next, but some are there 
even in the stable release. See dev and normal lists for some weirdnesses 
though if this is all nvda or firefox is hard to say.
 I find for example launching firefox from the run bar address can result in 
no usable drop down menus unless you bring up the alt/space menu and click 
the restore even if it says unavailable and then go back. Some sites just 
get stuck and you cannot close firefox.

If you then switch away and back you can.

My brain hurts so until I can give more definite info, I'm going to shut up.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by jcsteh** [comment]
> 1. Some labels aren't read on the browse form using arrow keys, but are using tab keys. Such as the create new issue form on git hub for instance.

This is covered by #4773.

> 2. Recent versions of NVDA do not respect the ability to review combo boxes before activating them if no save, go or next button exists as a stand alone button. The chapter selection drop down box on fan fiction, fiction press and other such websites is an excellent example of this.

Please explain exactly what you're pressing and what happens. Normally, to make a selection in a combo box without each change taking effect, you press alt+downArrow to "open" the combo box, make your selection and then press alt+upArrow to close it. As far as I'm aware, there haven't been any changes in NVDA recently that would change this. This is more likely a change on the site in question. If you still believe this is a recent change in NVDA, in what version of NVDA did this last work as you expected?

Thanks.

**Comment by Elshara** [comment]
Since version 2016.3 it has been going on.
It's a bug that used to only happen in internet explorer. Now it's
happening in Firefox 49 and all other browsers. Chrome, edge.
Basically, the field gets activated before you get a chance to review
it despite the alt arrow command. So by the time you wish to look at
the next time, the page is already in the middle of loading the item
you just selected but didn't move focus away from the drop down area
itself.
Issue happens in Windows 10 64 bit for further analysis.

**Comment by Elshara** [comment]
There's also a bug where if NVDA has to restart for whatever reason,
the active browser window since version 2016.3 disables browse view
via arrow key navigation altogether.
So say you are browsing a document in firefox. NVDA wants to do an
update for instance or for whatever reason you want to restart the
program. Once done, you have to also restart firefox or whatever
browser you use just to regain control of the document via arrow keys.

**Comment by bhavyashah** [comment]
Hi,
I can confirm NVDA's bug of being unable to function in Firefox when
restarted with focus originally on a Firefox window, however, I
vaguely recall this having been covered, or having been informed about
this bug having been covered by an existing ticket.
Thanks.

On 10/7/16, Elshara Silverheart <notifications@github.com> wrote:
> There's also a bug where if NVDA has to restart for whatever reason,
> the active browser window since version 2016.3 disables browse view
> via arrow key navigation altogether.
> So say you are browsing a document in firefox. NVDA wants to do an
> update for instance or for whatever reason you want to restart the
> program. Once done, you have to also restart firefox or whatever
> browser you use just to regain control of the document via arrow keys.
>
> On 06/10/2016, Elshara <sourceminded@gmail.com> wrote:
>> Since version 2016.3 it has been going on.
>> It's a bug that used to only happen in internet explorer. Now it's
>> happening in Firefox 49 and all other browsers. Chrome, edge.
>> Basically, the field gets activated before you get a chance to review
>> it despite the alt arrow command. So by the time you wish to look at
>> the next time, the page is already in the middle of loading the item
>> you just selected but didn't move focus away from the drop down area
>> itself.
>> Issue happens in Windows 10 64 bit for further analysis.
>>
>> On 06/10/2016, James Teh <notifications@github.com> wrote:
>>>> 1. Some labels aren't read on the browse form using arrow keys, but are
>>>> using tab keys. Such as the create new issue form on git hub for
>>>> instance.
>>>
>>> This is covered by #4773.
>>>
>>>> 2. Recent versions of NVDA do not respect the ability to review combo
>>>> boxes before activating them if no save, go or next button exists as a
>>>> stand alone button. The chapter selection drop down box on fan fiction,
>>>> fiction press and other such websites is an excellent example of this.
>>>
>>> Please explain exactly what you're pressing and what happens. Normally,
>>> to
>>> make a selection in a combo box without each change taking effect, you
>>> press
>>> alt+downArrow to "open" the combo box, make your selection and then
>>> press
>>> alt+upArrow to close it. As far as I'm aware, there haven't been any
>>> changes
>>> in NVDA recently that would change this. This is more likely a change on
>>> the
>>> site in question. If you still believe this is a recent change in NVDA,
>>> in
>>> what version of NVDA did this last work as you expected?
>>>
>>> Thanks.
>>>
>>> --
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly or view it on GitHub:
>>> https://github.com/nvaccess/nvda/issues/6432#issuecomment-252136776
>>
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6432#issuecomment-252145925


-- 
Best Regards
Bhavya Shah

Avid Enthusiast and User of the Free NVDA Screen Reader (www.nvaccess.org)

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by Elshara** [comment]
It only started happening recently.

**Comment by ehollig** [comment]
The issue about "unable to function in Firefox when restarted with focus originally on a Firefox window", has been resolved with #5758. 
> 2. Recent versions of NVDA do not respect the ability to review combo boxes before activating them if no save, go or next button exists as a stand alone button. The chapter selection drop down box on fan fiction, fiction press and other such websites is an excellent example of this.

@Elshara, is this still an issue with the latest version of NVDA? Could you provide a working example demonstrating the issue?

**Comment by ehollig** [comment]
Just a friendly reminder for @Elshara, to provide a working example of the issue as requested in https://github.com/nvaccess/nvda/issues/6432#issuecomment-337017714. Is it possible that the specific drop down box has javascript that automatically refreshes the page when the selection changes?

**Comment by ehollig** [comment]
Closing as invalid, unless this is still happening for @Elshara, or a working example can be provided.

**Comment by zahra21** [comment]
hi.
about combo buxes, i want to explain my observations.
not sure, whether its the issue which Elshara reproduced or not.
in complex web pages, when javascript is enabled, (most of times i disable javascript and cant interact with combo boxes),
i observed that nvda goes to the focus mode and some combo boxes are activate by default,
and whenever i want to use brows mode again, and pressing arrow keys, nvda stays on focus mode and activate combo boxes undesiarably.
i should emphasize that i use windows xp 32 bit version, with nvda 2017.2 and 2017.3.
not sure that adding support for combobox in aria 1.1 resolved the issue or not!
i just found this issue now,
and decided to comment if it can helps someone.
i hope that my english was understandable for you and could convey my meaning.
thanks so much for your excellent screen reader and God bless you all!
