### ISSUE TITLE
In Mozilla firefox, table navigation commands cannot be used to move through rich text tables.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6440]
In Firefox, create a 2 by 2 table in docs with braille support enabled.
as a student editing documents, it would be speedy and beneficial for NVDA to support moving around between table columns/rows with NVDA table navigation commands, such as those I use in word for editing tables.
1. try pressing ctrl+alt+right arrow.
2. notice NVDA doesn't support going to the next column.

**Comment by jcsteh** [comment]
P3 because this is necessary to facilitate efficient word processing on the web. The work done here might also benefit Libreoffice, though I'm not certain of that, as LibreOffice's IA2 implementation is somewhat different.

**Comment by Adriani90** [comment]
Closing as works for me, it works properly in Firefox 65.0.2 and Chrome. For what ever reason, table navigation works only when braille support is enabled.
