### ISSUE TITLE
nvda and java 8 memory problem

### ISSUE THREAD

**Issue by limaoscar** [nvaccess/nvda#6442]
I am using NVDA with mouse tracking enabled and espeak as tts
I have to open some java GUI that take alot of memory , so, after opened the java gui,
nvda stops to talk and the gui was unresponsive for several seconds.
But the bad things is that when I try to open a subwingow in the java gui (an editor containig thousand lines of code, the LAPTON hands until I have to press the power button to restart.
There are some relationship with mouse tracking too.

**Comment by jcsteh** [comment]
Can you please provide an application which we can use to reproduce this problem?

**Comment by limaoscar** [comment]
sorry for delay, but the java application is a JNLP so you need to connect to local network to download the java classes and the Java Gui is a client server that should connect to a server to login and open the code editor that crashes.
Anyway is there a way to enable logging in NVDA to trace what happen until the computer hangs?
Kind regards.

**Comment by limaoscar** [comment]
Hello, the problem still persit in NVDA 2017.2 and java 8
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) Client VM (build 25.45-b02, mixed mode)
I tried to enable the  mini dump for jnlp application, but it does not write any dump.
I only have retreived the log debug and a nvda_crash.dmp file.
Hope could be useful.
If you need more details please tell me how to debug better the issue.
[NVDA_CRASH.zip](https://github.com/nvaccess/nvda/files/1179275/NVDA_CRASH.zip)

**Comment by leonardder** [comment]
Looks like an unintentional close.

**Comment by leonardder** [comment]
@limaoscar: Could you test this with [the most recent master build from this page](https://www.nvaccess.org/files/nvda/snapshots/)?

**Comment by limaoscar** [comment]
Hello, thanks for reopen it!
I tried your suggestion but unfortunately it still crashes, also it did not produce any crash dump 
so I am attaching only the new log.
I followed the procedure to open python console over the java gui, it showed me the correct file path but after the PC has crashed and I have resytarted it , I could not find nay new crash under that path.
[NVDA_CRASH_nvda_snapshot_next-14244,8eb8d744_.zip](https://github.com/nvaccess/nvda/files/1186839/NVDA_CRASH_nvda_snapshot_next-14244.8eb8d744_.zip)

Kind regards.

**Comment by limaoscar** [comment]
hello the problem is still  present on last build of NVDA , here in attach the crash dump and logs
[crash2.zip](https://github.com/nvaccess/nvda/files/1659586/crash2.zip)

**Comment by feerrenrut** [comment]
I'm not sure what is causing the crash, but there are many errors in the log file triggered by mouse movement:
```
ERROR - eventHandler.executeEvent (11:45:21.684):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x05C97550> with extra args of {'y': 416, 'x': 907}
Traceback (most recent call last):
  File "eventHandler.pyc", line 152, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 920, in event_mouseMove
  File "NVDAObjects\IAccessible\__init__.pyc", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
```

**Comment by limaoscar** [comment]
hello, with last version of nvda 2018.4 I am still having  same problem on java 8 applications, but in this case a dump of nvda is generated, and some other memory error is showned on log , in attach you can find them.
Kind regards.
[NVDA_java_CRASH.zip](https://github.com/nvaccess/nvda/files/2698109/NVDA_java_CRASH.zip)
[NVDA_java_CRASH.zip](https://github.com/nvaccess/nvda/files/2698112/NVDA_java_CRASH.zip)
[NVDA_java_CRASH.zip](https://github.com/nvaccess/nvda/files/2698115/NVDA_java_CRASH.zip)

**Comment by Adriani90** [comment]
This should be improved meanwhile but I guess this is still reproducible in nvda 2019.3 Beta 2. @limaoscar could you please upload crash dumps and log file of NVDA 2019.3 Beta 2? You can download the beta or alpha versions of NVDA here:
https://www.nvaccess.org/files/nvda/snapshots/
Thanks very much for your patience.

**Comment by Adriani90** [comment]
Updates and Infos are missing upon request since many years, I am closing as abandoned. If you are still having this issue, please provide the info requested and we can reopen.
