### ISSUE TITLE
User Guide: Provide anchors for sections referenced in the Basic Training for NVDA module

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6447]
@jcsteh 
Please create static anchors for the following sections mentioned in the Basic Training for NVDA module

Section 3 "Getting and setting up NVDA" TOC 9 
Section 5.7 "Mouse navigation" TOC 39
Section 6.1 "Single Letter Navigation" TOC41
Section 7 "Reading mathematical content" TOC 44
Section 8 "Application specific features" TOC 46
Section 9.1.5 "braille Settings" TOC 68
Section 9.1.6 "Keyboard Settings" TOC 69
Section 9.1.11 "Browse Mode Settings" TOC 74
Section 9.1.13 "Speech dictionaries" TOC 76
Section 9.3 "Configuration profiles" TOC 80
Section 10 "Tools" TOC 88
Section 10.3 "Add-ons manager" TOC 91

Thanks!

**Comment by jcsteh** [comment]
P2 because this will make things much better for the training material with respect to future changes to the User Guide.

**Comment by bhavyashah** [comment]
Since this ticket has a P2 priority and documentation usually seems to me a relatively less tricky aspect, could this please be looked into?

**Comment by bdorer** [comment]
as the userguide has now anchors I think @qchristensen should be able to update the training material.

**Comment by feerrenrut** [comment]
Thanks for the prompt @bdorer! @Qchristensen will be looking into this.
