### ISSUE TITLE
NVDA stops reading when entered in full screen mode in browser

### ISSUE THREAD

**Issue by harshaSamayamanthri** [nvaccess/nvda#6451]
**Issue Description:**
NVDA stops reading the webpage content when browser is changed to the full screen mode(using F11).

**Steps to reproduce:**
1)Start NVDA 
2)open any of the websites, for instance www.google.com/ and search for anything
3)while screen reader is reading the content press F11 to enter the full screen mode and observe that NVDA stops reading abruptly.
4) Issue is reproduced in all the browsers. i tried in below browsers and can see the issue
    
- Chrome version 53.0.27
- Firefox ESR version 45.4.0
- Internet Explorer version 9.0.8

**NOTE**: After entering into the full screen mode, NVDA can only read the content by using arrow keys or by moving the cursor.

**Comment by jcsteh** [comment]
Silencing speech immediately when you press a key is intended behaviour. If you wish to resume reading the entire page, use NVDA's say all command. Please reopen the issue if you believe we've misunderstood the problem. Thanks!

**Comment by Brian1Gaff** [comment]
Yes I've seen this as well, indeed there seem to be some sites that send 
browsers into full screen mode which confused the heck out of me when I 
first had it happen. It sometimes does not occur, though and my thinking is 
its something timing related.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment]
I think the point was that the direct navigation by letter no longer worked 
either, or at least this was how I found it.

 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
