### ISSUE TITLE
Display model reports the wrong background color for text drawn in transparent mode

### ISSUE THREAD

**Issue by mwcampbell** [nvaccess/nvda#6467]
When text is written with the GDI background mode set to transparent, the display model doesn't necessary report the correct background color for that text. In this case, the GDI hook should look at the actual background color before the text is drawn, rather than using the result of `GetBkColor`.

**Comment by michaelDCurran** [comment]
Our displayModel currently only records chunks of text. If a fill or other non-text drawing action occurs, any existing text in its path is simply removed from the model. Thus the only background color info we have currently is from written text.  I'm assuming you mean we should actually track other non-text drawing actions, including its background and foreground color, so that if a drawing action such as text has a transparent color we can inherit the background color from the existing chunk? 

This would be a large project. What is the impact of this (taking into account GDI becoming less used anyway)?

**Comment by mwcampbell** [comment]
I don't think you need anything that complex. Before you call the original GDI `TextOut` or `ExtTextOut` function, you can just use GetPixel to get the color at the specified X/Y coordinates. That would be good enough for my purpose, at least.

This impacts my ability to make Dragon NaturallySpeaking fully accessible as part of the [DictationBridge](http://dictationbridge.com/) project. Specifically, Dragon has some custom list views where I can't yet track the highlighted item because NVDA thinks the background color of all the text in the list view is white.

**Comment by michaelDCurran** [comment]
If the background contained some kind of pattern or image then it may 
not be accurate. However, I agree that is better than just transparent.


I will look into it at some point, though if you need it quicker I'll 
certainly review  a submitted pull request.

**Comment by jcsteh** [comment]
This was reverted in 47337ef due to severe performance regressions; see #7251.

**Comment by josephsl** [comment]
Hi,

@MichaelDCurran, attached is the path that Matt should have sent as an official PR, but looks like it didn't make it through. I'm attaching in in case you'd like to review it and let Jamie or someone commit this. Thanks.
[displayModel-attempted-fix.txt](https://github.com/nvaccess/nvda/files/1168656/displayModel-attempted-fix.txt)

**Comment by Adriani90** [comment]
There is a work around introduced in #12658. @mwcampbell, @LeonarddeR is there anything else expected here? Or is the workaround good enough to close this issue?

**Comment by lukaszgo1** [comment]
The work around from #12658 is not really useful, as it only allows to know that the background is transparent which does not allow to track which option is highlighted. Determining what is highlighted in such cases will allow to solve some issues in Becky! Internet Mail and make menus in MCS Electronics IDE's accessible. This should remain open - while a complete fix is non trivial both JAWS and Window-eyes work better here, which means that this can be solved with additional GDI hooks.
