### ISSUE TITLE
Excel: Text which isn't too wide, announced as overflowing / cropped when using high DPI

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6472]
When the DPI is changed in Windows (usually via the "Make text and other items larger or smaller" setting), it makes everything bigger or smaller - text, icons, the size of cells in Excel.  The text "abcdefghi" fits neatly in a default sized cell at the default Calibri 11pt font.  This is the same regardless of the DPI as while a higher DPI makes the text bigger, it also makes the cells in Excel bigger, so the same text still fits.  There is a small discrepancy - I've found that you can fit a "j" on the end in some conditions.

When the DPI is set above 100%, NVDA seems to behave as if the text has got bigger but the size of the cell hasn't (just a guess).  At 200%, I can about half fill a cell before NVDA announces it as overflowing (or cropped if there is text in the next cell).  I tested this on Windows 10 with Excel 2016, and Windows 7 with Excel 2007.

To reproduce:
- Set "Make text and other items larger or smaller" to anything above 100% - the higher the value, the more obvious the effect.
- Sign out / back in.
- Open Excel
- Type text in a cell.  The text "abcdefghi" fits in a cell at the default Calibri 11 under every condition I tried.
- Navigate away from the cell and back (tab then shift+tab).  NVDA reads the text and reports "overflowing".

**Comment by feerrenrut** [comment]
P3 because its information related to presentation and there could be a reasonable cost to fix.
@Qchristensen Do you think there is cause for this to be higher than P3?

**Comment by Qchristensen** [comment]
P3 is fine, announcing cropped or overflowing when the text doesn't exceed
the cell width is less of a risk than NOT announcing when text is wider
than the cell.


-- 
22 Point

Web: http://www.22point.com.au
Facebook: https://www.facebook.com/22Point
Twitter: https://twitter.com/22PointApps

Check out our first app, RapiTap! - Tap targets fast & avoid decoys:
Adrenaline pumping, Challenging, Accessible!
https://play.google.com/store/apps/details?id=au.com.twentytwopoint.rapitap
Free trial:
https://play.google.com/store/apps/details?id=au.com.twentytwopoint.rapitapfree

**Comment by michaelDCurran** [comment]
Please test the following try build from pr #6526:
https://ci.appveyor.com/api/buildjobs/2fkfm6jyfgttcpwt/artifacts/output%2Fnvda_snapshot_try-i6216-13690%2C4286b570.exe

Does this now take dpi into account?

**Comment by Qchristensen** [comment]
It doesn't seem to for me - in fact at the default Excel cell size and font size, and at DPI at 225%, it announces "overflowing" if I type only "abc" into a cell.  Using NVDA 2016.3 it announces overflowing if I type abcd, although as noted in the original post, "abcdefghij" actually fits visually in the cell.

**Comment by michaelDCurran** [comment]
Another try build:
https://ci.appveyor.com/api/buildjobs/xkei402crq7042oh/artifacts/output%2Fnvda_snapshot_try-i6216-13692%2Cbf6b2e73.exe

I've confirmed with OCR that at least on my system (Surface Pro, Excel 2016, Windows 10) overflow/crop seems to behave now at various dpi settings.

Is this true visually?

**Comment by Qchristensen** [comment]
Ha, I tried, "abc" then "abcd", "abcdefghij", and none of them said
overflowing (which is correct), then I tried "abcdefghijk", which does
overflow.... and I hit that UI Automation crash...

Actually, I am hitting that crash constantly now trying to test this...  I
can try one set of letters in a cell, but the second time it is crashing
 (eg, I just typed, "the quick br" which overflowed, and announced that, as
it should.  I then tried removing the r which should put it just inside the
line, but as soon as I hit enter, NVDA stops working again.

Ok, finally got a few more tests and it's overflow detection seems to work
perfectly.  I'm still not sure whether it exacerbates the UI Automation bug
or it's just particularly playing up for me tonight.


-- 
22 Point

Web: http://www.22point.com.au
Facebook: https://www.facebook.com/22Point
Twitter: https://twitter.com/22PointApps

Check out our first app, RapiTap! - Tap targets fast & avoid decoys:
Adrenaline pumping, Challenging, Accessible!
https://play.google.com/store/apps/details?id=au.com.twentytwopoint.rapitap
Free trial:
https://play.google.com/store/apps/details?id=au.com.twentytwopoint.rapitapfree
