### ISSUE TITLE
Focusable issue when NVDA is open

### ISSUE THREAD

**Issue by maximilianotulian** [nvaccess/nvda#6476]
Hello, I have the next issue, please see the example in jsfiddle to reproduce it
https://jsfiddle.net/maxtulian93/1foenaoc/14/

1- Open NVDA
2- Click in myBtn(Open Modal) to open the modal and focus is set to 'modal-content' 
3- Wait until the whole content gets read
4- Press tab

Result: The focus goes to the last focusable element read, in this case the 'secondButton'. Is this an expected behavior? 
If NVDA is not open, when I press tab KEY the next element focused is the `btnClose`.

Regards,
Maximiliano Tulian

**Comment by jcsteh** [comment]
This is expected. The reason is that as NVDA reads the content in a document, it moves the cursor as it reads each line. Once it's finished reading the content, the cursor is on the last line, so pressing tab focuses the first control on that line.
