### ISSUE TITLE
wxPython pyds missing debug info

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#6482]
Even now that we have debug symbols for wxPython (#6143), debugging seems to fail to load symbols for wxPython pyd files. While some sources seem to suggest that the dll files must be included on the symbol server as well, my investigation suggests otherwise (see below). However, loading symbols without the dlls requires debug information in the dll. While Python's own pyd files have this and wx dlls do as well, our wxPython pyds do not.

The `dumpbin.exe` tool included with Visual Studio allows you to check this:

> ```
> dumpbin /headers c:\progra~2\nvda\wxmsw30u_core_vc90.dll
> ...
>            10380 [      1C] RVA [size] of Debug Directory
> ...
>   Debug Directories
>         Time Type        Size      RVA  Pointer
>     -------- ------- -------- -------- --------
>     57714423 cv            3F 000129B0    117B0    Format: RSDS, {420C29AD-79AD-4998-9D6B-591E37165816}, 1, C:\build27\cpython\PCBuild\_ctypes.pdb
> ```
> 
> ```
> dumpbin /headers c:\progra~2\nvda\wx._core_.pyd
> ...
> 0 [       0] RVA [size] of Debug Directory
> ```
> 
> ```
> dumpbin /headers c:\progra~2\nvda\wxmsw30u_core_vc90.dll
> ...
>           268570 [      1C] RVA [size] of Debug Directory
> ...
>   Debug Directories
>         Time Type        Size      RVA  Pointer
>     -------- ------- -------- -------- --------
>     5477A095 cv            5A 0031CD18   31B918    Format: RSDS, {50368653-DA7A-49F9-B817-1435BCEA19C8}, 287, C:\BUILD\wxPython-src-3.0.2.0\lib\vc90_dll\wxmsw30u_core_vc90.pdb
> ```

What I don't understand is why our wxPython pyd files are missing this info. We're using `cl /Zi` and `link /DEBUG`, which should produce and embed all of the required stuff. The only difference to NVDA is that NVDA uses `/Z7` instead of `/Zi`, but I think it's the link stage that's more important here anyway.

We need to try to solve this so we can avoid the need for dlls on the symbol server.

**Comment by jcsteh** [comment]
Some notes on why I think we don't need the dlls:

1. I caused a crash on a portable copy of NVDA next.
2. I renamed the portable copy directory so that the debugger couldn't find it.
3. I loaded the dump into WinDBG.
4. I executed the commands `!sym noisy`, `.ecxr` and `kp 200`.

Here's an excerpt of information regarding _ctypes.pyd:

> ```
SYMSRV:  C:\ProgramData\dbg\sym\_ctypes.pyd\577144231a000\_ctypes.pyd not found
DBGENG:  C:\Users\jamie\junk\portnvda\_ctypes.pyd - Couldn't map image from disk.
DBGENG:  _ctypes.pyd - Partial symbol image load missing image info
DBGHELP: Module is not fully loaded into memory.
DBGHELP: Searching for symbols using debugger-provided data.
SYMSRV:  BYINDEX: 0x14
         C:\ProgramData\dbg\sym
         _ctypes.pdb
         420C29AD79AD49989D6B591E371658161
...
DBGHELP: C:\ProgramData\dbg\sym\_ctypes.pdb\420C29AD79AD49989D6B591E371658161\_ctypes.pdb already cached
*** WARNING: Unable to verify timestamp for _ctypes.pyd
DBGHELP: _ctypes - private symbols & lines 
        C:\ProgramData\dbg\sym\_ctypes.pdb\420C29AD79AD49989D6B591E371658161\_ctypes.pdb
...
01 0019e37c 70fcd676 _ctypes!ffi_call_x86(<function> * prepfunc = 0x0019e3ac, struct extended_cif * ecif = 0x70fcd676, unsigned int bytes = 0x70fcd4c0, unsigned int flags = 0x19e39c, unsigned int * rvalue = 0x00000000, <function> * fn = 0x00000001)+0x1a [c:\build27\cpython\modules\_ctypes\libffi_msvc\win32.c @ 74]
```

So, it found the info it needed to fetch symbols; note the "Searching for symbols using debugger-provided data" message. Also, note that it was able to get source file and line number info.

Now, here's a similar excerpt for wx._core_.pyd:

> ```
SYMSRV:  C:\ProgramData\dbg\sym\wx._core_.pyd\5477A111124000\wx._core_.pyd not found
DBGENG:  C:\Users\jamie\junk\portnvda\wx._core_.pyd - Couldn't map image from disk.
DBGENG:  wx._core_.pyd - Partial symbol image load missing image info
DBGHELP: No header for wx._core_.pyd.  Searching for dbg file
DBGHELP: .\wx._core_.dbg - file not found
DBGHELP: .\pyd\wx._core_.dbg - path not found
DBGHELP: .\symbols\pyd\wx._core_.dbg - path not found
DBGHELP: wx._core_.pyd missing debug info.  Searching for pdb anyway
DBGHELP: Can't use symbol server for wx._core_.pdb - no header information available
DBGHELP: wx._core_.pdb - file not found
...
*** ERROR: Module load completed but symbols could not be loaded for wx._core_.pyd
DBGHELP: wx__core_ - no symbols loaded
...
WARNING: Stack unwind information not available. Following frames may be wrong.
29 0019f1f8 056e9a80 wx__core_+0x75bb
```

In particular, note the "No header for" and "missing debug info" messages. And note the stack unwind warning and lack of source file/line.

References:

* [Symbols the Microsoft Way](https://randomascii.wordpress.com/2013/03/09/symbols-the-microsoft-way/) proved to be very useful, although it suggests that "Minidump files and most profile files do not actually record enough information to retrieve PDB files", which the above investigation seems to refute.
* [MINIDUMPS AND MATCHING MODULES](http://www.debuginfo.com/articles/matchmodules.html) shows that minidump module entries include the debug record (`CvRecord`).
* [ModuleRescue](http://www.debuginfo.com/tools/modulerescue.html) is a tool which uses the debug info in minidumps to generate dummy modules which match and thus allow symbol download. It notes that debuggers don't allow fetching of symbols without matching modules, hence the tool. However, it's quite old, and based on the investigation above, I'm guessing WinDBG now supports fetching symbols using the debug info in the minidump.

Question:

* Is there any other reason to have the dlls on the symbol server? It doesn't seem so, but we won't know for sure until we try with wxPython pyds that have debug info.

**Comment by jcsteh** [comment]
Since building wxPython again is time consuming, tedious and doesn't fix the problem for existing builds (2016.3 and later), there's another (perhaps interim) option. We now know that the wx dlls are fine; the only problem is the wxPython pyds. We could just upload the pyds to the symbol server for this build of wxPython. I still think we should fix this problem when we next have to update our wxPython build for some other reason, though.

**Comment by jcsteh** [comment]
Actually, uploading the pyds doesn't give us access to the symbols because the pyds themselves have no debug info. This makes the pyd symbols practically useless. However, it does seem that when both the pyds and dlls are present, even though we can't resolve symbols, we can at least get past them in the stack (and down to the real wx calls).

Without pyds, the stack ends like this:

> ```
28 0019f1f4 100075bb python27!PyEval_CallObjectWithKeywords(struct _object * func = 0x056e9a80, struct _object * arg = 0x05838d70, struct _object * kw = 0x00000000)+0xf3 [c:\build27\cpython\python\ceval.c @ 4219]
WARNING: Stack unwind information not available. Following frames may be wrong.
29 0019f1f8 056e9a80 wx__core_+0x75bb
2a 0019f1fc 05838d70 0x56e9a80
2b 0019f200 00000000 0x5838d70
```

For the same dump with both pyds and dlls present, the stack gets past this and gets all the way to the first call:

> ```
WARNING: Stack unwind information not available. Following frames may be wrong.
29 0019f250 03b6bed3 wx__core_+0x75bb
2a 0019f258 03b6bf0d wxbase30u_vc90!wxAppConsoleBase::HandleEvent(class wxEvtHandler * handler = 0x05562c70, <function> * func = 0x10007430, class wxEvent * 
2b 0019f274 03c3bba6 wxbase30u_vc90!wxAppConsoleBase::CallEventHandler(class wxEvtHandler * handler = 0x05562c70, class wxEventFunctor * functor = 0x0345c2a8, class wxEvent * event = 0x0019f318)+0x2d [c:\build\wxpython-src-3.0.2.0\src\common\appbase.cpp @ 623]
...
59 0019ffec 00000000 ntdll!_RtlUserThreadStart+0x1b
```

Notice that we still get the stack unwind warning and it can't resolve the symbol for `wx._core_`, but it can still move past it to wxbase30u_vc90.

Unfortunately, with just the pyds present and not the dlls, this doesn't work, even though we have debug info and symbols for the dlls. It seems WinDBG doesn't even try to find symbols for the dlls if it can't find the pyd. I'm not sure why.

So, the interim solution is to put both the wx pyds and dlls on the server; the pyds are not enough. Even then, debug info in the pyds would be ideal so we get symbols. Whether this avoids the need for the dlls on the server is an open question.

**Comment by jcsteh** [comment]
For reference, here are the full logs from the debug sessions with the same dump:

* [Both pyds and dlls available](https://github.com/nvaccess/nvda/files/540700/6482_pydsAndDlls.txt)
* [Neither pyds or dlls available](https://github.com/nvaccess/nvda/files/540703/6482_noPydsOrDlls.txt)
* [Only pyds available](https://github.com/nvaccess/nvda/files/540704/6482_onlyPyds.txt)

**Comment by feerrenrut** [comment]
As discussed with @jcsteh:
- [ ] Comment on the latest findings 
- [ ] Upload `dll`s to the symbol server (p2)
- [ ] Find out why `pyd`s dont have debug information (p3)
- [ ] Rebuild `wxPython` so that the `pyd`s have debug information. (p3)

**Comment by jcsteh** [comment]
> Whether this avoids the need for the dlls on the server is an open question.

I was debugging an unrelated crash in Firefox recently and was examining a crash dump from someone else. Even with all of the symbols present (but not the dlls), WinDBG refused to move past a particular frame in the stack. However, giving it access to the dll allowed it to move past. I still don't really understand the reason, but I can't find any further information. Furthermore, the Microsoft symbol store and the Mozilla symbol store both include binaries, and a lot of resources seem to suggest they're needed. I think we're just going to have to deal with this and upload all dlls to the symbol server.

**Comment by jcsteh** [comment]
I've uploaded dll/exe/pyd files for Python 2.7.12, wxPython 3.0.2.0 and NVDA 2016.3. #6507 will make future NVDA builds upload these automatically.

**Comment by feerrenrut** [comment]
Seems like all the p2 parts of this have been done. I'll remove the p2 label now.

**Comment by michaelDCurran** [comment]
@jcsteh: would #6641 / #6642 affect some of your findings at all? I.e. 
you may have been unknowingly testing with the wrong wxPython pyds.

**Comment by jcsteh** [comment]
Oh bleh. Yeah, that's entirely possible. I'll probably need to re-test all of this.

**Comment by jcsteh** [comment]
Yup. It seems I was indeed using the wrong pyds. Here's info from the correct wx._core_.pyd:

> ```
> dumpbin /headers wx._core_.pyd
> ...
>            8FE00 [      1C] RVA [size] of Debug Directory
> ...
>   Debug Directories
>         Time Type        Size      RVA  Pointer
>     -------- ------- -------- -------- --------
>     578B0522 cv            59 000E42E8    E28E8    Format: RSDS, {67B1B24A-0282-4DB3-8D48-> BF9398652D9A}, 1, C:\Users\Michael\programming\git\wxPython\wxPython\wx\_core_.pdb
> ```

**Comment by jcsteh** [comment]
* So we now know that the pyds actually *do* have debug info; we were just using the wrong ones. That means we don't need to re-build wxPython.
* We're also [reasonably certain that we do need the pyd/dll files on the symbol server anyway](https://github.com/nvaccess/nvda/issues/6482#issuecomment-256006826).
* The pyds on the server are the old pyds without debug info. We need these for 2016.4 and releases before 2016.3 anyway.
* We do need to upload the pyds for future releases.

So, the only change left here is:

* [ ] Upload the new wxPython pyds with debug info to the symbol server.

**Comment by jcsteh** [comment]
Ug. Looks like I somehow uploaded the dlls for Python 2.7.12, but not the pyds.

* [ ] Upload pyds for Python 2.7.12 to the symbol server.

**Comment by jcsteh** [comment]
I've uploaded the new wxPython pyds and the pyds for Python 2.7.12. I've also uploaded everything for Python 2.7.13 now that we've updated to that. So, we're all done here!
