### ISSUE TITLE
The list view is not read completely by NVDA in library window of kindle for PC with accessibility plug in.

### ISSUE THREAD

**Issue by sumandogra** [nvaccess/nvda#6487]
Steps to reproduce
Open kindle for PC with accessibility plug in.
Open the library window with the the command ALT+CTRL+L.
TAB to the list of the books and read the list with UP/DOWN ARROW.

all the items present in a row relevant to the book are read for example, the percentage of the book read.  though the title of the book is read along with date.

**Comment by jcsteh** [comment]
Thanks for reporting. A major accessibility overhaul is in development for Kindle on Windows, though we haven't been given any dates on when it will be released to the public. Closing as invalid, since all issues related to Kindle will need to be completely re-evaluated.
