### ISSUE TITLE
error when closing command console terminals

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#6506]
When I was in talking dosBox with NVDA in sleep mode using some dos applications with NVDA as the dos screen reader output then I closed dosbox and started closing the speech server terminals that must stay open while using talking DosBox I got an error. Not sure if it is concerning but I thought I'd let you know and attach the log.
[nvdalogconsole.txt](https://github.com/nvaccess/nvda/files/550967/nvdalogconsole.txt)

**Comment by jcsteh** [comment]
This is a harmless exception. It occurs because the console disappears as NVDA is trying to query it.

P3 because it'd be nice to clean this up, but fixing it is low impact and users won't hear the error sound in release builds.

**Comment by Brian1Gaff** [comment]
I have noticed in recent snaps a lot of this seems to have gone away now in 
any case. You hear something similar in xp when a series of windows updates 
are installed and it is indeed a momentary  foreground change in the 
application as nvda sees it, running and then it goes back to where it was 
so to speak.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment]
@joshknnd1982 are you still getting this error with last NVDA Alpha?

**Comment by joshknnd1982** [comment]
No not anymore



Sent from Mail for Windows 10

**Comment by Adriani90** [comment]
Thank you very much. Closing as works for me.
