### ISSUE TITLE
Document use of control+alt+space

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6510]
In forms and surveys where questions are tabular, pressing alt+ctrl+right/levt/up/down moves you through the table. If there is a radio button or checkbox in the cell, pressing alt+control+space seems to cause the box to check. Is this an undocumented feature that should be in the users guide?

**Comment by jcsteh** [comment]
We don't bind control+alt+space to anything. That's being passed straight through to the app.

**Comment by michaelDCurran** [comment]
NVDA has no support for this. The application in question is simply lazy 
about how its detecting space (I.e. it does not care that control+alt 
are being held down).
