### ISSUE TITLE
Unordered List elements text in Chinese or Russian not read correctly on focus

### ISSUE THREAD

**Issue by vinaymalagi** [nvaccess/nvda#6512]
We are implementing a custom listbox for language selection as an unordered list for our webpage. Each list item (with role "option") will have a different lang attribute. On pressing the arrow keys focus moves to next/previous list item. This issue has been found with NVDA on both chrome and firefox.
The problem we are facing is that on focus on a non-english list item like Russian or chinese NVDA either reads all the letters separately or in case of chinese identifies the language as chinese and continues to say the word "letter" multiple times.

There seems to be an issue when an "li" element, with a different lang attribute, receives focus and also with role listbox. I have created a fiddle to demonstrate the same at [https://jsfiddle.net/xqfyuz1n/13/](https://jsfiddle.net/xqfyuz1n/13/)

The fiddle has the following parts:

1. Simple Unordered List
  - All items read properly when using read all mode (pressing ins + down )
  - All non english letters read separately when focus moves to a "li" (click on any list item)

2. Simple Div List:
  - No problems in reading mode and on focus.

3. Unordered Listbox ("ul" has role listbox and "li" has role "option"):
  - The list is not read at all in reading mode (Not sure if this is a NVDA issue)
  - All non english letters read separately when focus moves to a "li" (click on any list item)

4. Div Listbox (Outer Div has role "listbox" and all list items are divs with role "option"):
  - The list is not read at all in reading mode (Not sure if this is a NVDA issue)
  - All non english letters read separately when focus moves to a "li" (click on any list item)

**Comment by jcsteh** [comment]
List boxes not being rendered in browse mode is intentional. The idea is that list boxes are an interactive control, so the user presses enter to interact with them; i.e. to select an item.

The reason you're seeing this behaviour in list boxes is that while NVDA supports language switching in browse mode, it unfortunately doesn't support it yet in focus mode. That's covered by #3188.
