### ISSUE TITLE
nvda does not reach the microsoft account sign in window in win 10

### ISSUE THREAD

**Issue by kaveinthran** [nvaccess/nvda#6516]
I am using nvda 2016.3 with win10 v1607. I have tried to link my win10 pc with Microsoft account.

steps of reproducing 
1. using win10 start menu, type sign in
2. use up/down arrows to select sign in option and press enter
3. nvda will focuses itself on the accounts list box and sign in option list item on the system settings.
4. use up arrow to go to your info list item and press enter on it
5. then, hit the tab key and press the spacebar on sign in to Microsoft account
6. nvda will say just a moment, anad freeze for a wile

expected behaviour: nvda should go into e-mail editbox

actual behaviour in my system, the focus is back to the previous window, which is the system setting area, I can't locate any editbox.

When I hit tab and activate the signin to Microsoft account again, the same things happened.

thanks

**Comment by josephsl** [comment]
Hi,

Yes, this is a known issue: https://feedbackhub.link/feedback/112/8a48da50-4bce-4851-a250-e250467ab8db/1/

A bit better in Redstone 2 builds: although slow, you can sign in.

Thanks.

**Comment by kaveinthran** [comment]
just to men it here, I have this step helped me to login in latest build of jaws18 where I applied the same steps and jaws positioned me on the e-mail edit,
thanks

**Comment by derekriemer** [comment]
Duplicate.
