### ISSUE TITLE
What's new: reword document formatting dialog changes to be based on GUI Helper work

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#6520]
Hi,

A bit vague, but here's what's going on:

Thanks to work from @feerrenrut, document formatting dialog has seen major changes to how options are labeled. This includes indentation announcement (#5906) and others. Thus it would be helpful to reword these entries in what's new to take this into account.

Thanks.

**Comment by feerrenrut** [comment]
P1 since its important that this is looked at before the next release.
