### ISSUE TITLE
Skype message edit is working incorrectly with Japanese IME

### ISSUE THREAD

**Issue by nishimotz** [nvaccess/nvda#6528]
setup:

* Windows 10 Insider 14931 (32bit)
* English user interface with Japanese IME
* Skype 7.29.64.102
* NVDA 2016.3 (and master 13684 as well)

procedure:

* start NVDA
* start Skype, sign in, select a contact, then move to "Type a message here" edit
* enable Japanese IME (Roman transliteration mode)
* type "k a w a" (river)
* expected result is Japanese phonetic hiragana characters "かわ"
* actual result is "kあwあ", i.e. the for characters are not correctly transliterated

I have filed this issue to Microsoft Insider Hub as well.

**Comment by feerrenrut** [comment]
Thanks @nishimotz, could you confirm for us:
- [ ] Does this behaviour occur without NVDA running?
- [ ] Does this behaviour occur when Narrator is running (instead of NVDA)?

**Comment by nishimotz** [comment]
Without NVDA running, or, with application sleep is turned on, this issue does not occur.

When Windows Narrator is running instead of NVDA, this issue does not occur as well.

**Comment by surfer0627** [comment]
This case also occur when typing with Chinese input method.

**Comment by nishimotz** [comment]
I have reported this issue through Skype feedback.
However, this still happens with Skype 7.32.0.104 + NVDA 2017.1rc1 + Windows 10 build 15031 + Microsoft IME.
Skype chat is almost unusable with NVDA for Japanese users.

**Comment by nishimotz** [comment]
It still happens with Skype 7.34.0.102.
No issues with Windows Narrator.
Does anyone working on this?

**Comment by nishimotz** [comment]
Still happens with Skype 7.39.0.102.
As suggested in #6293, TChatRichEdit is mapped to RichEdit20.
Does that cause this issue as well?

**Comment by nishimotz** [comment]
Confirmed that the removal of mapping solves this IME issue on Windows 10.
I am still testing on Windows 8.1 and 7.

**Comment by nishimotz** [comment]
Tested the removal of TChatRichEdit mapping with Skype 7.39.0.102:

IME issue:

* Windows 10 : resolved
* Windows 8.1 : resolved
* Windows 7 : NOT resolved

Spelling error reporting:

* Windows 10 : spelling error is detected and NVDA can report
* Windows 8.1 : spelling error detection of Skype is not working
* Windows 7 : spelling error detection of Skype is not working

With current NVDA master and Skype 7.39.0.102, IME issue occurs on Windows 10, 8.1 and 7.

**Comment by ehollig** [comment]
@nishimotz, is this still the case with Skype 8.2?

**Comment by nishimotz** [comment]
The IME issue does not occur with the setup as follows:

* Windows 10 version 1803 (64bit) + Microsoft IME Japanese
* Skype Desktop 8.29.0.50
* NVDA 2018.2.1

**Comment by Adriani90** [comment]
@nishimotz, @surfer0627 do you have the chance to test in on Windows 8.1 and 7 and see if it still occurs in Skype 8?

**Comment by nishimotz** [comment]
The issue does not occur with the following setup:
* Windows 10 version 1803 64bit Japanese
* Microsoft Japanese IME
* Skype Desktop version 8.34.0.78
* NVDA 2018.4

I will close this because Microsoft does not support Skype 7 anymore.
