### ISSUE TITLE
request for adding audio conversion of documents in to nvda in the next version!

### ISSUE THREAD

**Issue by zahra21** [nvaccess/nvda#6534]
hello every one.
nvda is realy one excellent project and i only need only one more thing  to say its complete and i dont need anything beside it!
i realy love studying books.
i have hundreds of books and sincerely wish that you include the capability of converting of different types of documents in to audio formats.
i wish that convert my books in to audio formats and have them with myself whereever i go.
i know many people that realy need this feature in nvda.
so, please add this feature in to nvda 2016.4 to use on windows xp and for all windows users in the world.
i wish that convert my documents without any extra programs.
only i want it with nvda!
i sincerely request this, pray for you and request divine mercy and blessings for you.

**Comment by josephsl** [comment]
Hello,

Hmmm, this is way beyond the scope of a screen reader. A screen reader is just that - a program that interprets what's on screen and announces what it has found to you, not a media conversion tool. There are free programs out there that could accomplish what you may need. Thanks.
