### ISSUE TITLE
Announcing Microsoft-word Keyboard Shortcuts

### ISSUE THREAD

**Issue by jacobchawala** [nvaccess/nvda#6535]
It is nice that now, when pressing line spacing keyboard shortcuts, NVDA announces. For instance, when you press control+1, NVDA says: single line spacing. Now; Let us make the following Microsoft-word keyboard shortcuts to be announced:
CTRL+c coppid
CTRL+M 
CTRL+s saved
CTRL+t hanging indent
CTRL+v pasted
CTRL+w closed
CTRL+x cut
CTRL+y redone
CTRL+z undone
CTRL+Shift+l bulleted

You can suggest more shortcuts and the way they should be pronounced when pressed. The announcements of keyboard shortcuts are very crucial especially for beginner.

**Comment by fernando-jose-silva** [comment]
I have informed this in an earlier call that I can not remember the number anymore, but I think we should be careful when setting up the reading of these shortcuts because many of these shortcuts are different due to the language of the word.
Even though many of these shortcuts are different, as an example the save is not ctrl + s and yes ctrl + b.

**Comment by feerrenrut** [comment]
@fernando-jose-silva I think the issue was #6269?

**Comment by feerrenrut** [comment]
Closing this issue as a duplicate.

**Comment by jacobchawala** [comment]
all shortcuts set, for instance, CTRL+e, CTRL+l, CTRL+r, and so on,
can be pronounced when Microsoft-word is set in either American or
British English. I have not tested in other languages. so even those
shortcuts I am talking about will be first set in English, and then
developers will slowly go on setting them in other languages of the
word. I have suggested them to be announced because it helpes very
much learners who begin to learn word. normally those NVDA students
wants every thing to be announced.

On 11/7/16, Reef Turner <notifications@github.com> wrote:
> Closing this issue as a duplicate.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6535#issuecomment-258813055


-- 
+++
Yours Sincerely,
Jacob Florian Chawala
 JFC

Phone No. 0787016381

Emails: jacobchawala@gmail.com
jacobchawala@yahoo.com

Webmail: www.caict.netai.net

Skype ID: Jacob.Florian.Chawala
+++

**Comment by jacobchawala** [comment]
the issue is closed while the shortcuts i suggested to be announced have not been dealt with in all versions of NVDA
