### ISSUE TITLE
In word, there is no announcement of multicolumn pages.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6536]
One thing word can do is support multicolumn pages. As this trivial test case shows, in browse mode seems to move between columns, however in focus mode, it doesn't. with the numbers meant to simulate a test (D is a placeholder for a question), the student only knows they missed information by hearing the wrong number. It is conceivable as shown in example 2 that the student wouldn't know at all that this is multicolumn. NVDA should have a way to.
1. announce when multiple columns exist on a page.
2. have multicolumn movement commands.

This is pretty important since businesses use this for brochures and schools use this format for exams often.
example one is just numbers with d, so the example can be seen, example two is something that would confuse a blind reader.
[D.docx](https://github.com/nvaccess/nvda/files/572834/D.docx)
[The quick brown fox jumps over the lazy dog.docx](https://github.com/nvaccess/nvda/files/572845/The.quick.brown.fox.jumps.over.the.lazy.dog.docx)

**Comment by feerrenrut** [comment]
Related to #5946

I'm currently looking at this issue, and hope to extend PR #6498 with a fix shortly.

**Comment by michaelDCurran** [comment]
Fixed in d9d6607 as a part of #5946.
