### ISSUE TITLE
Internet Explorer 11: Unable to Read content of Edit Field when Reading Current Line with Latest Snapshots

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#6539]
Since updating to the last couple of snapshots, I've noticed that when attempting to read the current line of a particular edit field in Internet Explorer 11 (by using the default gesture) that an error occurs. This worked without issue in previous snapshots, all tested under Windows 7. Here's the error that gets output to the Log Viewer:

ERROR - scriptHandler.executeScript:
error executing script: <bound method GlobalCommands.script_reportCurrentLine of <globalCommands.GlobalCommands object at 0x059FEF50>> with gesture u'NVDA+up arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "globalCommands.pyc", line 142, in script_reportCurrentLine
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 460, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 345, in _getTextWithFieldsForUIARange
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))

Here's the dev info for that particular object:

Developer info for navigator object:
name: None
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_EDITABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible object at 0x05AC5C70>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithoutAutoSelectDetection'>, <class 'editableText.EditableTextWithoutAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.MSHTML.MSHTML'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (328, 136, 121, 21)
value: ''
appModule: <'appModuleHandler' (appName u'iexplore', process ID 61008) at address 5877110>
appModule.productName: u'Internet Explorer'
appModule.productVersion: u'11.00.9600.16428'
TextInfo: <class 'NVDAObjects.IAccessible.MSHTML.MSHTMLTextInfo'>
windowHandle: 590198
windowClassName: u'Internet Explorer_Server'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 63660
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x924530 at 5b7bdf0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=590198, objectID=375, childID=0
IAccessible accName: None
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: None
IAccessible accValue: u'TestText'
MSHTML node has ancestor IAccessible: False
MSHTML nodeName: u'INPUT'

**Comment by jcsteh** [comment]
Are you running the absolute latest master or next snapshot? This should
have been fixed last week (2316b08d, merged in 8bf3dfc).

**Comment by elliott94** [comment]
Apologies - I updated to the latest Next snapshot today, and the issue has been resolved.
