### ISSUE TITLE
Chrome canary has an unlabeled button.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6540]
1. open chrome canary.
2. press win+b
3. arrow down until you hear button.
4. press enter.
5. press nvda+control+f1
6. try arrowing around the new menu.
This is a chrome menu which allows access to its task manager and other things like exit.

**Comment by feerrenrut** [comment]
P2 to investigate and file a bug with chrome.

**Comment by derekriemer** [comment]
The unlabeled button was fixed in chrome canary as of now.
However the popup menu is still inaccessible.

**Comment by derekriemer** [comment]
And now I can't even find this pop out menu in my system tray.

**Comment by ehollig** [comment]
@derekriemer, could you provide an update with this issue?

**Comment by Adriani90** [comment]
@derekriemer is this issue still reproducible with last NVDA Alpha?

**Comment by leonardder** [comment]
This issue is getting old and we don't know what version of Canary this is. I"m closing this. IF there is a similar issue still, it is probably best to file a new issue using the issue template.
