### ISSUE TITLE
make chrome legacy windows accessible.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6541]
1. go to [this site](https://revoked.grc.com) in chrome.
2. The window that appears warns you that this site is unsafe.
3. try working with this window. It appears to expose almost no accessibility information.

**Comment by feerrenrut** [comment]
I can reproduce with Chrome Version 54.0.2840.71

This seems pretty bad, @jcsteh could you comment on the cost to implement a fix for this?
Assuming there is little we can do, P2 to file a bug with chrome on this.

**Comment by jcsteh** [comment]
It's definitely a bug in Chrome.

Technical note: It does fire events. The child ids are negative numbers, which suggests that they're unique ids and that there is actually an accessibility implementation there somewhere. However, WM_GETOBJECT returns 0 for OBJID_CLIENT. At a guess, I'd say they just need to fix the window proc to handle WM_GETOBJECT for that window.

**Comment by jcsteh** [comment]
Oh, and there's absolutely no way we can work around this.

**Comment by jcsteh** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=730910

**Comment by ehollig** [comment]
It appears that [Issue 730910](https://bugs.chromium.org/p/chromium/issues/detail?id=730910) has been closed and fixed. Closing
