### ISSUE TITLE
stop the spurious alerts on chrome.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6542]
1. In chrome canary, open any website of size. nvaccess.com, derekriemer.com, darksky.net seem to work.
2. as the page loads and at random times, you hear "alert" with no further information.

**Comment by feerrenrut** [comment]
P2 to investigate the cause of this and if it is a chrome bug file it with them.

**Comment by derekriemer** [comment]
seems to be much much better now.
