### ISSUE TITLE
NVDA reads data incorrectly in ie browser when transition is used.

### ISSUE THREAD

**Issue by DeepikaJeeth** [nvaccess/nvda#6547]
Input field data is read incorrectly using IE browser if transition attribute is specified.

transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s

**Comment by feerrenrut** [comment]
@DeepikaJeeth Could you provide a minimal test case for this?

**Comment by ehollig** [comment]
@DeepikaJeeth, could you respond to @feerrenrut in https://github.com/nvaccess/nvda/issues/6547#issuecomment-259327511 and provide a minimal test case? Closing this in a week or so if we do not get a response.

**Comment by ehollig** [comment]
Closing, as we have not heard from the original poster in over a year.
