### ISSUE TITLE
Synthesizer is not saved with configuration profile

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#6554]
The synthesizer setting can not be saved / restored with configuration profiles.

To reproduce:
- Create two profiles
- In the first one set the synthesizer to "Microsoft Speech API".
- In the second set the synthesizer to eSpeak.
- Swap back to the first. The synthesizer will still be eSpeak.

In particular this will cause problems if you want to make use of features that only exist in one of the synthesizers eg: the speech boost option.

**Comment by Brian1Gaff** [comment]
Is this something to do with the synth being switchable and savable in the 
special case profile of using a read all special  profile so it uses a 
different synth just for that?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by feerrenrut** [comment]
@jcsteh I would like your opinion on this one. Is this behaviour intentional?

**Comment by jcsteh** [comment]
It's not intentional... and I've definitely seen this work. I have a demo
profile on my system which uses a different synthesiser (and that works as
expected). So, either there's a specific set of circumstances that triggers
this or it's a regression.

**Comment by feerrenrut** [comment]
In that case I'll assign it p2. I noticed this when trying to reproduce #5853.

**Comment by Adriani90** [comment]
I cannot really reproduce this in NVDA 2019.1 RC1. @feerrenrut is this still an issue?

**Comment by feerrenrut** [comment]
@Adriani90 No I can't reproduce this anymore. Tested with `alpha-16933,bae84ed6`

I'll close this issue.
