### ISSUE TITLE
Listbox doesn't announce whether item is selected as expected

### ISSUE THREAD

**Issue by smilelari** [nvaccess/nvda#6562]
Looking at this very simple listbox as an example (I am using Chrome as my browser):

https://cookiecrook.com/test/aria/multiselect/listbox.html

For the most part, the behavior is acceptable.  However, if an item in the list has been selected and then deselected, it no longer announces "not selected", even though aria-selected="false"

**Comment by jcsteh** [comment]
This works in Firefox. This appears to be a bug in Chrome. The selected state is still exposed when the item is unselected.

**Comment by jcsteh** [comment]
P2 to file a bug against Chrome.

**Comment by jcsteh** [comment]
I just tested and this appears to be fixed in Chrome Version 60.0.3112.113 (Official Build) (64-bit). Closing as worksforme.
