### ISSUE TITLE
Virtual buffers not being created in IE7 and IE8  and XP on web pages

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#657]
**Reported by briang1 on 2010-05-15 22:46**
It appears that  some time after snap 3410, but before 3419, the ability to create virtual buffers in mshtml in IE7 has become dependent on the focus being in the  main display window at the start of the page download. either that or something very like it. The effect is no auto read when the page is all downloaded, and nvda/f5 does not help. You need to manually move the focus in some way, by tab shift tab or switching applications. This never used to be the case. For details see attached doc file (assuming it attaches and is not too big
See next ticket for windows update issue allied to this one..

**Comment by leonardder** [comment]
@brian1gaff: Could you elaborate on the status of this?

**Comment by jcsteh** [comment]
While we're not dropping support for Windows XP, it just isn't feasible for us to put resources into fixing XP specific issues any more. Closing as won't fix.
