### ISSUE TITLE
When tab role has ":after" in stylesheet, it seems to read incorrectly.

### ISSUE THREAD

**Issue by mulder21c** [nvaccess/nvda#6584]
I am creating a tab UI using tablist/tab/tabpanel role, but I found something strange.

this is code fragments in question.
https://jsfiddle.net/mulder21c/pusbjvL4/

**tested steps & expected result (tested with chrome, NVDA 2016.3**

1. While the first item("category 1") is focused,
2. if press right arrow key
3. then NVDA say "category 2 tab selected 2/3"
4. if press left arrow key
5. then NVDA say "category 1 tab selected 1/3"

**actual result**
1. While the first item("category 1") is focused,
2. if press right arrow key
3. then NVDA say "category 1 category 2 tab selected 2/3"
4. if press left arrow key
5. then NVDA say "category 2 category 1 tab selected 1/3"

if element with tab role has ":after" in css, Is it correct to read the previous item?
I think it's incorrect.

**Comment by Adriani90** [comment]
@mulder21c are you still able to reproduce this issue? I am testing with NVDA 2019.1 RC1 and Chrome 72 and it seems everything is reported just fine.

**Comment by mulder21c** [comment]
@Adriani90  Oh! I've just seen your comment.
I just ran a test with the latest version of NVDA, and now it appears that the problem is not occurring and is reading correctly. Thx.

**Comment by ehollig** [comment]
Closing as worksforme
