### ISSUE TITLE
Anyone know how to combine OpenCV to NVDA？

### ISSUE THREAD

**Issue by aoki1994** [nvaccess/nvda#6588]
I want to use Opencv-Python (cv2 module) to write some addons for NVDA. But I find the opencv library is too large to get included in the addon directory. How can I correctly use it in NVDA?

**Comment by leonardder** [comment]
I guess this might be something which is more suitable to discuss on the 
NVDA development mailing list. As far as I know, all other add-ons which 
include external libraries do this by adding the add-on's directory to 
sys.path, which makes it possible to import the particular external library.

This said, I think it might be an interesting approach if add-on 
packages would support shipping an additional libraries directory which, 
if exists, is automatically added to the sys.path variable by the add-on 
initialisation system or something similar to 
addonHandler.initTranslation(). This would also nicely fit into an 
add-on dependency system where you have separate add-ons for libraries. 
For example, foth Instant translate and NVDA Remote ship JSON, and would 
benefit from a separate json library add-on.

**Comment by aoki1994** [comment]
@leonardder Thank you for answering. And I will ask the question on the NVDA development mailing list. But I still have a problem: If I want others to use my add-on, I need to pack the related library files within the add-on, right? But in order to implement the ideas about some AI applications such as video description. I need to use some frameworks like tensorflow or opencv3. And I find tensorflow takes 163.5MB. Are there any feasible way to enable users to use such add-ons conveniently. My thought now is to put the deep learning code or something like that in server. And use the add-on to send and receive data.

**Comment by derekriemer** [comment]
Please ask this on the NVDA-Devel list.
