### ISSUE TITLE
Add-on list too small in Add-ons manager screen

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6593]
In the add-ons manager screen, the list of add-ons takes up half the width of the dialog itself, leaving a large blank space to the right of the list.

Issue and solution likely similar to #6101 

CC @feerrenrut

**Comment by feerrenrut** [comment]
There seems to be different behaviour between standard windows builds and the insider program build. In the standard Windows build the list takes up most of the width of the dialog. The insider build is as described in this issue. On the windows insider build the list in the symbols list dialog is fine, so if this behaviour makes its way into the standard windows build we have a quick way to address it.

Screenshots for reference:
![image](https://cloud.githubusercontent.com/assets/3491346/21252389/5f39d2f2-c391-11e6-9bfb-f45d6c7f281d.png)
![image](https://cloud.githubusercontent.com/assets/3491346/21252409/794a3fb0-c391-11e6-9ef4-e2746d34dbf7.png)

**Comment by feerrenrut** [comment]
For now I propose we leave this issue on hold.

**Comment by Qchristensen** [comment]
On insider builds of Windows at least it still looks exactly as it does in that screen shot above for me.  Interesting that it is different between insider Windows and standard builds?

**Comment by Adriani90** [comment]
@Qchristensen I guess there is no significant change to the look of the dialog in last NVDA RC. Right?

**Comment by Qchristensen** [comment]
Since I last looked at this issue, I've reverted to a stable build of Windows.  My add-ons window seems correctly proportioned now, however this may be due to leaving the insiders program as per @feerrenrut's earlier note.  Could someone using an insider build of Windows confirm that the issue still exists, please?

**Comment by leonardder** [comment]
I'm pretty sure this has been fixed as part of the add-on versioning pr. If not, we can always reopen.
