### ISSUE TITLE
Extend Foobar2000 app module with scripts to announce elapsed and total time

### ISSUE THREAD

**Issue by tuukkao** [nvaccess/nvda#6596]
I am proposing the following changes to be implemented in the app module for Foobar2000:

* Add a script for reporting the elapsed time of the currently playing track. I suggest using the shortcut ctrl+shift+e.
* Add a script for reporting the length of the currently playing track. I suggest using the shortcut ctrl+shift+t.

All of this information can be already accessed via the status bar. However, it can be inefficient to obtain since the lengths are at the very end. Reordering the status bar so that the lengths would be presented first won't work either since it will break the report remaining time script in the app module, which relies on the status bar using its default format. These scripts would present the needed information immediately without having to listen through the entire status bar first. The proposed shortcuts are directly related to the shortcut for reporting the remaining time (ctrl+shift+r) and would therefore be easy to memorise.

I'm willing to start working on this issue immediately.

**Comment by leonardder** [comment]
I'd certainly like this functionality.

**Comment by feerrenrut** [comment]
Thanks @tuukkao. I'll set this as priority 4 since we are unlikely to work on this internally, however we are happy to accept a pull request for this issue.
