### ISSUE TITLE
When a link has focus the URL can not be read from the status bar.

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#6597]
This affects chrome and firefox.

To reproduce:
- In browse mode move focus a link using the `Tab` key.
- Use Report Status Bar using `NVDA+end` (or for laptop layout `NVDA+shift+end`)
- Note that the URL is not read.

**Comment by traviswimer** [comment]
I noticed that this is not labelled as a "security" vulnerability. I just want to point out that this bug leaves users susceptible to phishing scams and similar attacks where the link text says one thing, but the `href` points to a malicious URL.

**Comment by mohdshara** [comment]
related to #1825. looking for the status bar to read this info has severe performance penalties as @Jteh commented there.

**Comment by jcsteh** [comment]
I don't believe we need to classify this as a security issue because you can get to the URL in other ways (e.g. in Firefox, context menu -> Copy Link Location then NVDA+c to read the clipboard). Obviously not ideal, but it's sufficient enough to avoid the potential security problem.

**Comment by Adriani90** [comment]
You can get now the URL via nvda+k NVDA 2023.1. Closing as works for me.
