### ISSUE TITLE
A bulgarian string is partially hidden in the welcome dialog of NVDA

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#6599]
After we've completed the bulgarian translation for NVDA 2016.4 last night, I've decided to compile the .po file to .mo and test it. And good thing I did, though a little bit late. It turned out that the string "Welcome to NVDA!" in the dialog itself (the one with larger letters), the bulgarian translation of that string is partially truncated. The whole string in bulgarian is "Добре дошли в NVDA!", but visible in the dialog is only "Добре дошли в". Visually, the string seams not to be so much longer than the english one, or at least it seams so to me, but it still gets truncated. Also, visually there seams to be more than enough space on the right to fit the string. Probably however, the text container for that string is horizontally not expanded to the right end of the dialog, but only to a certain part of the width of it and that is why the string does not fit and gets truncated. I'll try to attach a screenshot of the dialog with the truncated string for someone with at least some vision to look at it if necessary.

P.S.: That truncated string in bulgarian seams to be using a different font in comparison with the english one. Maybe the font used for the english one does not support cyrillic and the dialog reverts to a font that does (?).

P.S.2: The Problem is only visual and not critical. NVDA reads the whole string, even if truncated.
![screenshot_2016-11-28_22-22-40](https://cloud.githubusercontent.com/assets/4395934/20717823/7e49f90e-b65f-11e6-8f15-e822e4f581a1.png)

**Comment by feerrenrut** [comment]
This is probably a quick fix, and impacts the polish of NVDA quite a lot. Setting priority 2.

**Comment by feerrenrut** [comment]
I haven't been able to reproduce this issue while using nvda with Windows 10 Version 1607 build 14393.447. I have tried setting my scaling to 175%, lowering my screen resolution to 800x600, enabling high contrast themes in various combinations.

@k-kolev1985 What version of Windows are you using? Could you please describe the display settings you have (screen resolution, size of text / scaling percentage, theme / high contrast settings)

**Comment by k-kolev1985** [comment]
Hi Reef,

Test environment:
- Operating system: Windows 10 Pro (build 14393.479), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: next-13751,e720db12, but I can reproduce it with a temporary copy of 2016.4RC1 as well.
- Desktop resolution: 1920x1080.
- Theme used: "High-Contrast Black", though I can reproduce it with the "Windows" one as well (and probably with all others, though I haven't tested it).
- Display scaling: In Settings -> Display, the slider labeled "Change the size of text, applications and other elements" is set to 0, witch probably means that the scaling is at 100%. I haven't played with that setting.
- The font size in Settings -> Display -> Advanced Display Settings -> Advanced sizing of text and other elements for all items in there is set to 9. I haven't played with that setting either.

My guessing is that it is the font name/type that causes this issue, though I don't know what font is used for that text (though it looks bold formated).

**Comment by feerrenrut** [comment]
Thanks @k-kolev1985 I needed to install and set the system language to reproduce this.

When Bulgarian system language is installed there must be a wider selection of fonts available, and this line of text is in a slightly different font.

Technical:
This newer font seems to be chosen when `wx.DECORATIVE` is used.
