### ISSUE TITLE
Google Chrome Notifications from Extensions are not read

### ISSUE THREAD

**Issue by ctoth** [nvaccess/nvda#6602]
While attempting to create a chrome extension I noticed that notifications were not being read by NVDA.

[Find attached](https://github.com/nvaccess/nvda/files/621373/testnotify.zip)
a simple unpacked Chrome extension which pops up a notification.
Install it by going to chrome://extensions and selecting load unpacked extension, then navigating to and selecting the unzipped folder.
Once the extension is loaded, pressing ctrl+shift+a should make a notification pop up.
To make this notification stay on the screen for investigation, (by default it seems to go away after a bit), in background.js, add a line after line 8 which says:
```javascript
      requireInteraction: true
```
making sure to put a comma on the previous line.

Investigation with OCR reports that there is the text on the screen, it appears to be on the bottom of the window, but I cannot seem to access it with object nav.

I would appreciate help with this :)

**Comment by Adriani90** [comment]
@ctoth is this still reproducible with NVDA 2019.1 RC1 and Chrome 72?

**Comment by Adriani90** [comment]
No updates from the initial author since more than 3 years. Closing as abandoned.
@ctoth if you need any further advice, please feel free to contact the NVDA developers mail list at
https://groups.io/g/nvda-devel
