### ISSUE TITLE
NVDA latest snapshot do not support INSERT+F while inside Google docs editable area.

### ISSUE THREAD

**Issue by JanuszChmiel** [nvaccess/nvda#6603]
Dear developers, if report formatting is not supported while using Google docs, if it will be very good if this error would be suppressed and NVDA will tell user not supported or other words. Short part of NVDA.log here:
ERROR - scriptHandler.executeScript (11:53:17):
error executing script: <bound method GlobalCommands.script_reportFormatting of <globalCommands.GlobalCommands object at 0x05046C90>> with gesture u'NVDA+f'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "globalCommands.pyc", line 1281, in script_reportFormatting
  File "speech.pyc", line 407, in splitTextIndentation
TypeError: expected string or buffer

**Comment by jcsteh** [comment]
Thanks for reporting. What browser were you testing this in? Was this while
editing a document? Did you have Google Docs braille support enabled or
disabled? (Note that having Google Docs braille support enabled improves
some other things as well even if you're not using braille, which is why I
ask this question.)

**Comment by JanuszChmiel** [comment]
Dear MR Tech, I have Screen reader support enabled inside Google account settings. I Am using latest stable version of Seamonkey WEB browser. Error have occured, when cursor have been placed on The at The opened document. There is no other error related to arrow keys support, ETC. Only Insert+F  do not work inside Google docs editable area.

**Comment by Adriani90** [comment]
@JanuszChmiel are you still having this issue with last NVDA version?

**Comment by ehollig** [comment]
In Firefox with NVDA latest Alpha and Google Docs, pressing NVDA+F reports "No formatting information".

**Comment by Adriani90** [comment]
This works correctly with NVDA alpha-20220,1c4519a6, Chrome 81 and Firefox 76.
Closing as works for me.
