### ISSUE TITLE
Non english version of Adobe reader crashes as soon as reading document window dissapears

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#661]
**Reported by pvagner on 2010-05-19 18:16**
### STR

```
* Install non english version of Adobe reader 9.3. I'm using slovak version which can be downloaded from: http://ardownload.adobe.com/pub/adobe/reader/win/9.x/9.3/sk_SK/AdbeRdr930_sk_SK.exe and also I have looked up direct download link for the french version. Hope this crashes as well and may be easier for you to deal with. Here's the direct link to download french version: http://ardownload.adobe.com/pub/adobe/reader/win/9.x/9.3/fra/AdbeRdr930_fr_FR.exe
* open any accessible pdf document in the installed copy.
```
### actual results

Ass soon as the document reading window dissapears Adobe reader crashes with the classic error windows dialog.
### expected result

Acrobat reader should not crash and NVDA should render the content into the adobe virtual buffer.

**Comment by leonardder** [comment]
Adobe Reader 9 is quite obsolete now. I've never experienced such issues with newer versions.
