### ISSUE TITLE
Snappy Driver Installer: flat review doesn't see text

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#6610]
While using the open-source program [Snappy Driver Installer](https://sdi-tool.org/), NVDA can't see any of the text on the screen, while JAWS 18 can.

**Comment by leonardder** [comment]
@tspivey: Any ideas about what this could be? How does object navigation work?

**Comment by Adriani90** [comment]
@tspivey is this still an issue in NVDA 2019.1 RC1 and last version of the driver installer?

**Comment by ehollig** [comment]
Closing as stale
