### ISSUE TITLE
Error moving to Chrome window when previously connected Braille display not present.

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6612]
Note: This happens in NVDA Master builds (I'd noticed it for awhile but only just pinned it down), up to the current build 13738,67e435a0

Steps to reproduce:
1. Use NVDA with a Braille display (I'm using an Alva).
2. Disconnect or turn off Braille display.
3. Restart NVDA.
4. ALT+TAB to a Chrome window
5. NVDA beeps an error.  Following lines written to NVDA log:

ERROR - braille.BrailleHandler.setDisplayByName (09:28:23):
Error initializing display driver
Traceback (most recent call last):
  File "braille.pyc", line 1502, in setDisplayByName
  File "brailleDisplayDrivers\alvaBC6.pyc", line 58, in __init__
RuntimeError: No ALVA display found
INFO - braille.BrailleHandler.setDisplayByName (09:28:23):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - braille.BrailleHandler.setDisplayByName (09:28:47):
Loaded braille display driver noBraille, current display has 0 cells.

Error repeats every time focus moves to or from a Chrome window.  Switching to a Microsoft Office window, file explorer, notepad, Firefox etc don't cause the error
Connecting the Braille display or setting Braille to "no Braille" stops error.

**Comment by jcsteh** [comment]
Do you have any configuration profiles, especially one for Chrome? I'm
guessing the braille display is only configured for Chrome, so it only
tries to initialise when you switch to Chrome. That error is normal when
the display is not connected and we try to initialise it.

**Comment by Qchristensen** [comment]
Ah, that was it, I wondered why it was happening in Chrome.  I forgot I setup a Chrome profile ages ago to test something else.  I must have been in Chrome when testing the Braille display error!  Ok, if this would happen in everything then is there a way to more gracefully ignore the fact the usual Braille display isn't connected?

**Comment by Qchristensen** [comment]
Ah I see, that error only occurs once when NVDA loads, which is fair enough, and then would only reoccur if going to another configuration profile set to no Braille and back again.  Ok. we can probably close this now then and I'll go back in my little box :)
