### ISSUE TITLE
Inconsistant behavior in document formatting.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6634]
1. Press alt+t. 
Expected: you land on the table reporting command.
Actual: You land on the checkbox, and it toggles. To make things worse, NVDA doesn't pretend that this box used to be checked/unchecked and has changed.

now:
Press alt+m, and repeat multiple times.
The confusion comes from the fact that if there's only one possible accelerator key, we are toggling this item, not ignoring it. This is inconsistent if the user doesn't know how many things with that key there are.

**Comment by leonardder** [comment]
Is this really inconsistent? It is quite normal behaviour that an 
accelerator key toggles a check box or activates a button, and that it 
doesn't do that when there are more items with the same accelerator. The 
opposite would be inconsistent IMO.

**Comment by jcsteh** [comment]
This is standard behaviour for accelerators. This is not just check boxes: consider menu items, for example. You can argue that we shouldn't ever double up on accelerators to be consistent, but that's an unfortunate reality with a relatively small alphabet. We try not to double up for the options we believe users most commonly use, but that's the best we can do.

I'm closing this as won't fix. If you have suggestions and use cases for accelerators which avoid doubling up, consider filing another issue, but also consider the limited space we have and whether using another accelerator is justified.
