### ISSUE TITLE
Crazy random cursor/caret jumping when using MS Speech API/Platform Synthesizer without output device

### ISSUE THREAD

**Issue by ghost** [nvaccess/nvda#6636]
1. On Windows, go to Control Panel, open "Sound" setting dialog -> Disable all playback devices
1.1. In Windows 10,  "Speakers" will be disabled as "Not plugged in" when earphone unplugged
2. Open NVDA's "Preferences > Synthesizer"
2.1. "Synthesizer" is "Microsoft Speech API" or "Microsoft Speech Platform"
2.2.  "Output device" - The drop down list is empty

Using focus highlight addon or speech viewer
http://addons.nvda-project.org/addons/focusHighlight.en.html

On many sites (e.g. this github page),  you will find
- cannot switch between focus/browse mode
- by pressing tab to any link, press enter(click),  it open/submit wrong URL/form
- by pressing up/down to same link, press enter(click),  it open a correct URL
- system cart jump to unexpected initial/next location navigate around

Workaround 1 - keep headphone plugged
Workaround 2 - don't use MS Synthesizer

**Comment by feerrenrut** [comment]
This seems like something that should be fixed.

However @hkdennis2k, first it would be good to know what your use case is?

For your (or anyone else looking at this issue) benefit there are some other workarounds if the main requirement is just to use NVDA with no sound output:
- Choosing "no speech" as the synthesizer should achieve this.
- Alternatively when starting nvda you can press `NVDA + s` to turn speech mode off.

**Comment by hkdennis2k** [comment]
No. I don't have a real end user use case.
I am a developer who test and develop web application. We aimed to make it accessible to total blind users and to compatible with NVDA.

I believe most of the real end-user will not having trouble with this issue (any idea of braille display user?)

As far as I could remember, it happens after I've switch to MS Synthesizer (which has better audio quality), and in another random day later it spent me half a day to realize _lucky_ the missing cable matters.

The real bug here, _I believe_, is not the caret, but the silence when it hit into exceptions or mis-configuration.
A simple tray visual message or audio or log in speech view will help a lot.

**Comment by feerrenrut** [comment]
@hkdennis2k While it may not be the primary use case for NVDA, it's certainly a valid use case to use NVDA for accessibility testing. I think it would be handy if speechviewer gave some indication of warning/error sounds or other audiocons. Perhaps an indication of the mode that NVDA is in as well.

**Comment by jcsteh** [comment]
I'm guessing we have an unhandled exception here which is breaking things. Can you please provide a log file capturing this issue with log level set to debug? See [Log Files and Crash Dumps](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) for details on how to do this.

**Comment by hkdennis2k** [comment]
@jcsteh 
https://gist.github.com/hkdennis2k/5dee77e3a7491c8613b9009291fa4f46

**Comment by feerrenrut** [comment]
Thanks @hkdennis2k. Extracted error from the log:

> ERROR - eventHandler.executeEvent (16:52:48):
> error executing event: gainFocus on <NVDAObjects.IAccessible.ContentGenericClient object at 0x04A2ECF0> with extra args of {}
> Traceback (most recent call last):
>   File "eventHandler.pyo", line 143, in executeEvent
>   File "eventHandler.pyo", line 91, in __init__
>   File "eventHandler.pyo", line 98, in next
>   File "C:\Users\dennis.cheung\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 419, in event_gainFocus
>   File "eventHandler.pyo", line 98, in next
>   File "appModules\explorer.pyo", line 263, in event_gainFocus
>   File "eventHandler.pyo", line 98, in next
>   File "NVDAObjects\__init__.pyo", line 892, in event_gainFocus
>   File "NVDAObjects\__init__.pyo", line 804, in reportFocus
>   File "speech.pyo", line 355, in speakObject
>   File "speech.pyo", line 313, in speakObjectProperties
>   File "speech.pyo", line 396, in speakText
>   File "speech.pyo", line 504, in speak
>   File "synthDrivers\sapi5.pyo", line 298, in speak
> COMError: (-2147200966, None, (None, None, None, 0, None))

Log from NVDA version 2016.3.

We should try to improve the stability of this. I will split off the speech viewer improvements into a new issue see #6647

**Comment by Adriani90** [comment]
@hkdennis2k are you still able to reproduce this issue with NVDA 2019.1 RC1? Since this seems related to the addon focus highlight, @nishimotz your thoughts would be very appreciated on this issue. Thanks in advance.

**Comment by nishimotz** [comment]
FocusHighlight hooks the events, but in this case, I think nothing is affected.

**Comment by Adriani90** [comment]
we didn't get any updates from the initial author since many years, and the add-on focus highlight is deprecated since visual highlight is now part of NVDA core.

I am closing this issue as abandoned.
If you are still having this issue, please comment with updated steps to reproduce and we can reopen.

**Comment by CyrilleB79** [comment]
> and the add-on focus highlight is deprecated since visual highlight is now part of NVDA core.

For the sake of correctness: No,, Focus Highlight is not deprecated since it offers more specific options to customize the highlight rectangles; there is a 2023.1 compatible version.

Anyway, unless someone can give an update to this issue, it will remain closed as abandoned.
