### ISSUE TITLE
space key label in NVDA language package don't cause any effect.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#6655]
Hi:
One day, I want to mute spacebar reading. Follow is my action:
1. Delete symbol files' space symbol,result:spacebar name is announced by English.
2.Change translation of the spacebar in langpack, and the Newest mo file is used to replace with old one,result:Don't cause anything.
Thanks!

**Comment by feerrenrut** [comment]
Its not possible to remove the space symbol using the symbol pronunciation dialog. However, you can change what it is replaced with. If you change the space symbol replacement from "space" to an actual space character I.E. " " then "space" is no longer reported.

**Comment by jcsteh** [comment]
See the workaround above if you really want to do this. However, silencing specific characters is not something we want to support officially because the user is then completely unaware of what the character is. As such, I'm closing this as won't fix.

**Comment by vgjh2005** [comment]
Hi:
The reason of this issue is that some users don't want to hear the keypress of spacebar. It is the same of the such as tab and shift or ctrl key. When we press spacebar to active a button or a checkbox, Spacebar will be announced at first then the selection state. It is inefficiency. It is also a bug. Another KeyPressAnnouncement is normal and definitional.

**Comment by josephsl** [comment]
Hi, same argument could be made for ENTER key and others, which is one of the reasons why NVDA developers won’t implement selective suppression of keys for the time being. Thanks.
