### ISSUE TITLE
Change Windows logon settings while logged in

### ISSUE THREAD

**Issue by hatserdevlats** [nvaccess/nvda#6668]
Is it possible to add an option to change settings for Windows logon and other secure screens while you are logged in? This will be a lot faster than copy the entire configuration directory.

**Comment by derekriemer** [comment]
Hi:
There are several discussions under way currently, via @leonardder and others. While we don't and can't let anyone access the system configuration, as it runs at a higher integrity (security) level, a change to NVDA is being proposed which would simply allow NVDA to present a list of addons, and let the user select all the addons which are wanted, with a warning presented that this could be dangerous if an addon is selected.

**Comment by jcsteh** [comment]
The add-on selection issue is #6305. We can't allow anything beyond this for security reasons.
