### ISSUE TITLE
Inconsistent IAccessible behaviour in treeview

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#6694]
Hello,
using NVDA 2016.4 on Windows 7 32-bit there is no problem, each treeview item is read regularly.
In the same situation, same NVDA, same application, but on Windows 10 64-bit, the item is unknown.
Relative logs attached.
Can you say where is the issue?
[logs.zip](https://github.com/nvaccess/nvda/files/685197/logs.zip)

**Comment by feerrenrut** [comment]
Priority 2 to look into the cause of this.

**Comment by Adriani90** [comment]
@ABuffEr is this still the case in NVDA 2019.1? Do you have the addon Windows 10 app essentials installed?
cc: @josephsl, @derekriemer, @Robert-J-H

**Comment by ABuffEr** [comment]
Hi,
sorry for delay. I noticed now that problem seems resolved, maybe thanks to work on IAccessible 64-bit syslistview. I close this issue.
