### ISSUE TITLE
nvda, problems when reading chm files.

### ISSUE THREAD

**Issue by mikolysz** [nvaccess/nvda#6708]
nvda has some problems when reading chm files (with the default viewer build into windows)
1. when "use screen layout when supported" is disabled, source code is shown improperly.
A good example of this behaviour is python's documentation file located in your_python_installation_directory\doc\pythonxxxx.chm. All text except source code is rendered as expected, but source is broken into many lines wherever possible. 
it looks like this:
x
=
int
(
raw_input
(
"please enter an integer: "
))
and it should look like this:
x = int(raw_input("Please enter an integer: "))
This is similar to what sometimes happens when you view a document in notepad, you have word wrap enabled and the window is not maximized.
2. when you alt+tab away from a chm document and go back, the focus sometimes jumps to the top, but sometimes it stays where it was before.
3. when you have multiple items in the tree view that point at one document but to different places, NVDA doesn't jump to the appropriate place.
python's documentation, is, again, a good example.
we can, for example, expand the python tutorial, then expand the chapter on data structures and click on "the  del statement"
first problem, when we press f6, nvda jumps to the next subsection "tuples and sequences", not to the one about del statements.
second, when we go back to the treeview, press enter on something different that is still in the same document, in this case, "sets" and press f6 again, NVDA doesn't jump anywhere at all. It should move the focus to the relevant subsection, ut it doesn't
We can press f5 before pressing enter to refresh and it works then, but it's inefficient, especially with large documents, because it takes some time.

**Comment by jcsteh** [comment]
I'd need to look into the latter points, but as for screen layout, this is
rather the point of screen layout: to make sure that content is rendered
into lines as displayed on screen. If you turn off screen layout, you're
choosing to render different elements on different lines, regardless of
their intended rendering. In these code snippets, each chunk of text is a
different element.

**Comment by miki123211** [comment]
So why it doesn't happen anywhere on the web and it happens in each chm 
file?
I prefer to have screen-layout turned off to make links easier to find, 
however, it greatly complicates reading code and is rather unintuitive, 
surprising and definitely not what most users expect, maybe except from 
those deeply familiar with the inner workings of chm.
W dniu 2017-01-08 o 22:57, James Teh pisze:
> I'd need to look into the latter points, but as for screen layout, this is
> rather the point of screen layout: to make sure that content is rendered
> into lines as displayed on screen. If you turn off screen layout, you're
> choosing to render different elements on different lines, regardless of
> their intended rendering. In these code snippets, each chunk of text is a
> different element.
>
>

**Comment by PratikP1** [comment]
Is this the only file with which you are having trouble? DO you have comparison data with other CHM files?

**Comment by Adriani90** [comment]
@dave090679, @devil418, are you still having this issue?

**Comment by Adriani90** [comment]
We didn't get any updates upon request since many years from people who reproduced this issue in the past. Closing as abandoned. If you are still having this issue, please comment and we can reopen.
