### ISSUE TITLE
Windows 10 build 15002: cannot activate browse/focus mode in Edge, cannot navigate to the document by tabbing around

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#6713]
Hi,

Related to #6712: In Windows 10 build 15002, when using Edge, one cannot move to the document when tabbing around nor toggle focus/browse mode.

STR:

1. Install build 15002.
2. Open Edge, then try tabbing around to see if you can locate the document.

Expected: one can tab to the document and toggle focus/browse mode.
Actual: Where there should have been a document, NVDA says, "unknown".
Observation: in build 15002, there is a new "frame" that is sort of a parent of the actual document, whereas this isn't there in prior builds.
Impact: Major, as this prevents people from testing various enhancements to Edge support that are now part of master branch snapshots.

Setup:

* NVDA version: next.13795
* OS: Windows 10 build 15002

Thanks.

**Comment by feerrenrut** [comment]
I think this should be priority 1 to look into. We need to get some feel for the cause of this and cost to fix it.

**Comment by michaelDCurran** [comment]
Edge documents are no longer contained within the expected Edge root container UIAElement. Thus NVDA does not give them browseMode.
The document either seems to be contained with in a grouping with a name of "WebRuntime Component View" or sometimes this parent is skipped altogether. 
The reason NVDA no longer tracks focus is eventHandler.shouldAcceptEvent is now returning false. I'm guessing some kind of foreground window check is failing?
I'm going to have a bit of a chat to the Edge teem in the next two days to see if we can shed any light on this brokenness.

**Comment by michaelDCurran** [comment]
NVDA is itself changing the role of the document to frame, as  we have code that does this if it finds a pain in edge with the textPattern yet is not a direct child of  the EdgeRoot container.

**Comment by michaelDCurran** [comment]
Filed MS Bug 10566743: NVDA can no longer access the content of documents in Microsoft Edge
