### ISSUE TITLE
Report legends

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6725]
```
data:text/html,<h2>Pizza toppings</h2><legend><dl><dt>*</dt><dd>Complementary</dd><dt>**</dt><dd>$1 extra</dd><dt><img src="spicy.jpg" alt="spicy"></dt><dd>Spicy topping</dd></dl></legend><dif id="pizza-toppings"><label><input type="checkbox"> Jalapeno <img src="spicy.jpg" alt="spicy"></label><br><label> <input type="checkbox" disabled checked tabindex="0">* Love. All Pizza's are made with lots of home made love, sprinkled on by our chefs who love their job</label></div><button>Submit</button>
```

We should announce the legend in a region or similar so the user knows this is a legend.

**Comment by jcsteh** [comment]
I'd argue this is a misuse of the [legend tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend):

> `The HTML <legend> element represents a caption for the content of its parent <fieldset>.`

Fieldset and legend are intended for grouping of form fields, where the legend becomes the name of the grouping. If you tab through a form with a fieldset/legend, NVDA will announce the legend as the name of the grouping. The "legend" is not usually that long and is near its associated form fields, so reporting it as a special kind of region is superfluous.
