### ISSUE TITLE
visual studio 2015 installer: state of checkboxes in component selection treeview are not accessible

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#6732]

**Comment by ehollig** [comment]
@beqabeqa473 it appears that your issue is blank. Could you please provide exact steps to reproduce as well as a description of the issue you are having?

**Comment by beqabeqa473** [comment]
hi.

in visual studio 2015 installer states of checkboxes aren't accessible.

the problem is that checkable object is inside of list item and is not navigable with arrow keys

**Comment by Adriani90** [comment]
it is fully accessible when object navigation is used.

**Comment by Adriani90** [comment]
@beqabeqa473 are you still having this issue in NVDA 2019.1?

**Comment by leonardder** [comment]
Visual Studio 2015 has been superseded by 2017 and 2019, which both offer a fully accessible installer. Given that installation of Visual Studio isn't an every day task and there are alternatives, I'm closing this for now.
