### ISSUE TITLE
Entering File tab in Outlook 2016 with alt+f results in no speech

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#6739]
STR
1. Open Outlook.
2. Press alt+f to enter the file tab.

Log below:

IO - speech.speak (17:13:34):
Speaking [LangChangeCommand ('en'), u'Inbox - ppatel@ezfire.net - Outlook']
IO - speech.speak (17:13:34):
Speaking [LangChangeCommand ('en'), u'Table View  table']
IO - speech.speak (17:13:34):
Speaking [LangChangeCommand ('en'), u'From Corey Malone, Subject ADA (we talked on twitter, Received Fri 1/6/2017 4:27 PM, Size 147 KB, Conversation ADA (we talked on twitter,  row 1  column 1  level 1']
IO - inputCore.InputManager.executeGesture (17:13:37):
Input: kb(laptop):alt+f
IO - inputCore.InputManager.executeGesture (17:13:40):
Input: kb(laptop):downArrow
IO - speech.speak (17:13:40):
Speaking [LangChangeCommand ('en'), u'Info  tab  selected  Info  Alt, F, I  ']
IO - inputCore.InputManager.executeGesture (17:13:42):
Input: kb(laptop):downArrow
IO - speech.speak (17:13:42):
Speaking [LangChangeCommand ('en'), u'Open & Export  tab  selected  Open & Export  Alt, F, O  ']
IO - inputCore.InputManager.executeGesture (17:13:44):
Input: kb(laptop):downArrow
IO - speech.speak (17:13:44):
Speaking [LangChangeCommand ('en'), u'Save As  Alt, F, A  ']
IO - inputCore.InputManager.executeGesture (17:13:45):
Input: kb(laptop):downArrow
IO - speech.speak (17:13:45):
Speaking [LangChangeCommand ('en'), u'Save\xa0Attachments  unavailable  Alt, F, M  ']
IO - inputCore.InputManager.executeGesture (17:13:48):
Input: kb(laptop):downArrow
IO - speech.speak (17:13:48):
Speaking [LangChangeCommand ('en'), u'Print  tab  selected  Print  Alt, F, P  ']

**Comment by ehollig** [comment]
@PratikP1, could you provide more information? this works correctly for me in Outlook 2016. The log does not provide anything either. I see that you pressed the down arrow key after pressing alt+F, but it provided the expected results.

**Comment by PratikP1** [comment]
I am no longer encountering this issue. The issue was a mismatch between what the speech said V what NVDA reported internally. This is resolved in the public release of Outlook 2016 and latest NVDA next. The issue can be closed.

**Comment by ehollig** [comment]
Closing as worksforme as reported in https://github.com/nvaccess/nvda/issues/6739#issuecomment-322810611
