### ISSUE TITLE
Scons devDocs Does Not Generate Documentation

### ISSUE THREAD

**Issue by munawarb** [nvaccess/nvda#6751]
When I type scons devDocs after executing scons source, I get an empty output directory. I've attached the scons output here.

[scons_output.txt](https://github.com/nvaccess/nvda/files/713175/scons_output.txt)

**Comment by bhavyashah** [comment]
Possibly related to #5373

**Comment by leonardder** [comment]
@munawarb: can you still reproduce this?

**Comment by munawarb** [comment]
@leonardder Sorry, since then I've switched systems and don't have the tools to build NVDA on here. I can fetch them again if you'd like me to test it, just to close out this issue, but that'll have to be in a month or two from now since I'm traveling for business at the moment and am short on free time. So, I'll follow up with you as soon as I can.

**Comment by leonardder** [comment]
I will test this on my corporate system later this week.

**Comment by ehollig** [comment]
@leonardder can you provide any updates?

**Comment by Adriani90** [comment]
@leonardder is this still an issue?

**Comment by feerrenrut** [comment]
devDocs builds for me. I can't see any error in the log file. I assume that it was being skipped, perhaps scons decided it was already built. Since there hasn't been updates in a long time I'll close this issue.
