### ISSUE TITLE
Reduce Volume Synth Settings Ring increment/decrement to 5

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#6754]
Currently, upon navigating to Volume in the Synth Settings Ring and increasing/decreasing the volume, the change value is 10. However, while using headphones and often even on speakers, amounts of 10 bring about significant differences. Particularly when using NVDA at low volumes, one may wish to change volume by an amount of much lesser than 10, which cannot be achieved seamlessly using the Synth Settings Ring and necessitates usage of the Voice Settings dialog.
As a solution to the above problem I periodically encounter, I propose changing the increment/decrement amount of the Volume option in the Synth Settings Ring to 5 instead of 10, alike the Rate option. This will enable greater flexibility on the fly.

**Comment by PratikP1** [comment]
This is a valid suggestion. If nothing else, it should be set to an increment of 5 to bring it to parity with rate, pitch, etc.

**Comment by josephsl** [comment]
Hi,

Are there synthesizers that cannot set volume to increments of five percent? If so, we cannot proceed, otherwise a developer working on this should change volume setting in synth driver handler to not use normal step of 10.

CC @TSpivey, @RAGB

Thanks.

**Comment by derekriemer** [comment]
This should be fine to perform

**Comment by josephsl** [comment]
Hi,

Because this change may break some synthesizers that cannot handle this change, we should publish a note about this once a PR for this one is merged.

Thanks.

**Comment by feerrenrut** [comment]
> Because this change may break some synthesizers that cannot handle this change, we should publish a note about this once a PR for this one is merged

@josephsl Do you know of any examples?

**Comment by josephsl** [comment]
Hi, we can ask the add-ons community. Thanks.

**Comment by Adriani90** [comment]
I cannot think of a synthesizer which would not support this feature. But the best way is to maybe release a try build with this feature implemented and ask for user reports.

**Comment by feerrenrut** [comment]
> But the best way is to maybe release a try build with this feature implemented and ask for user reports.

I'm happy with this plan, I have merged it. Please contact me if there are issues with synths.
