### ISSUE TITLE
Modify NVDA’s speech feedback for copying actions on triple-pressing of certain commands in English to place ‘copied’ at the beginning

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#6757]
Using NVDA’s title reporting or currently focused object reporting key command’s triple press actions for example, I sometimes press them multiple times in order to get them reported enough times for me to completely grasp or memorize. Often, my key presses are so successive that NVDA mistakes me for a triple-press and copies the window title or focused object to the clipboard. Usually, the problem isn’t so much about things getting unintentionally copied, but more so about being unaware of the same. This is because in both the cases of the triple press of the title and object reporting commands among others that I am not currently listing, the entire title or object is reported following which NVDA says ‘copied to clipboard’.
Thus, I propose changing this speech feedback of NVDA from ‘{title}/{object} copied to clipboard’ to ‘copied {title}/{object} to clipboard’, so that a user is aware earlier about the accidental clipboard contents change or the copying action that has inadvertently taken place. Often, I do not listen to the end of particularly long window titles in haste and issue another command interrupting speech at the end. This may be very low priority, but equally trivial to resolve. I must admit though that I am unclear about the impliciations of this string change for other languages, if any.

### Summary:
Make it clearer that text has been copied.

While trying to use commands such as title reporting, sometimes the command is mistakenly pressed 3 times resulting in the title being copied to the clipboard unintentionally. This may happen because the title is long or hard to understand, and the user wishes to hear it repeatedly.

### Expected behaviour:
```
Copied {title} to clipboard
```
### Actual behaviour
```
{title} copied to clipboard
```

The proposed change makes it clearer from the start of the utterance that the clipboard has been updated.

### Risks
This may not translate well into other languages.

**Comment by ehollig** [comment]
Hmmm, thoughts @Qchristensen?

**Comment by feerrenrut** [comment]
Rather than try to increase the clarity that a mistake has been made, another approach to this might be to make it easier to avoid the 3 press mistake in the first place. It seems to me, the user wants a way to re-trigger the last command, and only the last command.

**Comment by JulienCochuyt** [comment]
I up-vote this change request.
The current message buries the two crucial pieces of information at the end of a possibly lengthy message:
 - The triple press succeeded in a way different than single press
 - The content of the clipboard has been altered

There are three scripts emitting the incriminated message:
 - `GlobalCommands.script_navigatorObject_current`
 - `GlobalCommands.script_reportStatusLine`
 - `GlobalCommands.script_title`

Two additional scripts deal with the clipboard with a different message:
 - GlobalCommandsscript_review_copy: "Review selection copied to clipboard"
 - CursorManager.script_copyToClipboard: "Copied to clipboard"

I guess we should try to adopt a uniform phrasing for the five of them.

Possibilities:
 - "Copied {text} to clipboard" as originally requested, not my favorite
 - "Copied to clipboard: {text}"
 - "{what} copied to clipboard" with what being "Navigator Object" / "Title" / "Status bar" / "Review selection" / "Selection"
 - "Copied to clipboard", period, which at least requires no translation effort at all as it is already used

I do not have a personal preference among the last three.

**Comment by XLTechie** [comment]
My preference is for:

"{what} copied to clipboard" with what being "Navigator Object" / "Title" / "Status bar" / "Review selection" / "Selection"

**Comment by feerrenrut** [comment]
@JulienCochuyt what you are proposing is quite similar to #9028 where the consistency of "{what} selected" was improved. I agree that makes sense to be consistent for all of these types of messages.

I think there are some contradictory requirements to consider:
- After pressing a command, I don't want to wait for a long title or other text to know if I got the right command.
  - Example problem: "Long application title here copied"
  - The user only knows it was copied (and not selected or some other action) at the end, frustrating for a user uncertain if they have the pressed the right key.
   - Preference for this user: "Copied: Long application title here"
- After pressing a command, I want to know as soon as possible that I operated on the right text.
  - Example problem: "Copied: Long application title here"
  - The user is unsure they are copying the right text, and have to wait for copied to be said.
  - Preference for this user: "Long application title copied here"

For now I agree, make the messages consistent. Longer term, this falls into a speech messaging UX configuration project.

**Comment by JulienCochuyt** [comment]
@feerrenrut, thanks for pointing this out.

So, I guess the phrasing "{what} copied to clipboard: {text}" would fit most expectations:
 - Instant confirmation of the nature of the operation
 - Quite quick confirmation of the text operated upon, as long as translations for {what} do not get too verbose
 - Lengthy outputs can be cut without loss of information
 - Uniform among the five copy operations

"Review selection" is the one that can get a bit verbose in French by example.
Probably would "Selection" be sufficient as {what} for both NVDA+F10*2 and control+C.
