### ISSUE TITLE
Open Office: Spelling suggestions not read in F7 spellcheck

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6760]
In Open Office 4.1.3, F7 performs a spell check similar to Word.  The suggested correct spellings field (tab to it or press alt+s) does not read.  Move to next or previous object will read each suggested word, although without moving the focus (NVDA+shift+numpad minus doesn't move the focus within this box either).

**Comment by jcsteh** [comment]
This does appear to work in LibreOffice, so I'd say this is almost certainly a bug in OpenOffice. Given that they don't seem to be fixing accessibility issues, I'm not sure it's worth us investing time in following this up.

What exactly gets reported when you press alt+s?

**Comment by Qchristensen** [comment]
I should have said, I tried this in Libre and found that it works fine there too.

When you press alt+s, it tells you that you are in the suggestions list and gives about a paragraph explanation of what that is before telling you how many suggestions there are and reading the currently selected one, but after that, it doesn't seem to notice when the focus changes within that section.

**Comment by jcsteh** [comment]
Okay. If it works for you in Libre too, that does suggest an OpenOffice bug.

I'm closing this as above. Someone else is of course welcome to file a bug with OpenOffice if they wish.
