### ISSUE TITLE
Chrome: Sometimes, text of dialogs isn't shown in browse mode.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6766]
Go to the more tools > extentions
add one.
search for tampermonkey.
Press "Add to chrome"
Now, switch to browse mode. Read this dialog.
Note that text you can find with objject nav is invisible to browse mode.

**Comment by jcsteh** [comment]
What's happening here is that a dialog appears, but the text is actually contained within a dialog inside that dialog. (That appears in browse mode after the Close button..) Unfortunately, there's nothing focusable in that dialog, so pressing enter to interact with it can't focus anything and thus fails. This is a bug in Chrome; they should not be displaying text within a dialog within a dialog.

**Comment by jcsteh** [comment]
Filed: https://bugs.chromium.org/p/chromium/issues/detail?id=730953

**Comment by ehollig** [comment]
It appears that [Issue 730953](https://bugs.chromium.org/p/chromium/issues/detail?id=730953) has been closed and fixed in Chrome 67. Closing
