### ISSUE TITLE
UIA can return None for currentAccessKey

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#6779]
Log:

```
ERROR - eventHandler.executeEvent (17:01:45):
error executing event: gainFocus on <NVDAObjects.Dynamic_UIADesktopWindowNVDAObject object at 0x04D832D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 892, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 804, in reportFocus
  File "speech.pyc", line 355, in speakObject
  File "speech.pyc", line 272, in speakObjectProperties
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 772, in _get_keyboardShortcut
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

Re: #6025

**Comment by jcsteh** [comment]
I think I've seen this, but I don't recall where. Can you give reliable steps to reproduce this? It'd help in prioritising this issue. Thanks.

**Comment by dkager** [comment]
I think it occurs when a new window is opened, such as after you use Alt+Tab. I also think I saw it when working with the context menu in Windows Explorer. But it is hard to pinpoint because in both scenarios the individual steps you take are usually close together.

I'd say low priority, but also trivial to catch this error. It feels like it's too small to do a PR, unless it needs deep, contemplative, philosophically sound analysis. But IMO it's just a corner case. :)

**Comment by josephsl** [comment]
Hi,

A reliable way to reproduce this:

1. Open Outlook 2016.
2. Turn off simple review mode.
3. Move navigator object to the foreground window.
4. Move through the top-level children until you hear an error sound.

CC @mohammad-suliman

Thanks.

**Comment by josephsl** [comment]
Hi,

Technical: no check for NULL string (None). A naive fix is to just catch type error exception. There is a related issue where two spaces are added if accelerator key is not there (#6790). The PR will catch both.

Thanks.

**Comment by dkager** [comment]
Did the fix not go into master already?

**Comment by jcsteh** [comment]
Yes; #6792 got merged. Closing.
