### ISSUE TITLE
NVDA becomes slightly sluggish.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#678]
**Reported by Dhoundiyal on 2010-05-29 12:37**
When using NVDA 2010 in Window-7, I often experience a slight sluggishness with it. That is, NVDA seems to slow down a bit in its response when navigating with it in Window-7; specially in IE web browser and MS Word 2007.

**Comment by leonardder** [comment]
I assume we can safely close this, I've not seen this kind of concerns lately.
