### ISSUE TITLE
Virtual buffer skips check box in Chrome

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#6781]
STR:
1. In Chrome, go to http://www.newegg.ca/Product/ProductList.aspx?Description=10tb%20hard%20drive&Submit=ENE
2. Search for Manufacturer
3. When pressing the down arrow, I just hear numbers. In Firefox, I hear check boxes with manufacturer names, and numbers.
4. With the cursor on one of the numbers, press NVDA+numpad4 to move to the previous object. The check box is read.

I expect the check box to be read along with the text.

**Comment by jcsteh** [comment]
In Chrome, the check boxes are exposed with an accessible width and height of 0 (invisible). In Firefox, they're exposed as 16 x 16.

@feerrenrut, can you confirm whether there is any visual difference in Firefox and Chrome here? Are the check boxes visible in Chrome?

**Comment by feerrenrut** [comment]
To be clear, I assume we are talking about where you can filter by manufacturer. In the given example there are options like "Seagate (115)", "Western Digital (1)", etc.
The check boxes are visible in both Firefox and Chrome, and there is no visual difference.

Chrome Version 55.0.2883.87 m (64-bit)
Firefox Version 50.1.0

**Comment by jcsteh** [comment]
Okay. We'll need to file a bug against Chrome.

**Comment by jcsteh** [comment]
I just tested and this is fixed in Chrome Canary, Version 63.0.3205.0 (Official Build) canary (64-bit).

Note that it is still broken in Chrome stable, Version 60.0.3112.113 (Official Build) (64-bit).

So, the fix is in Chrome 61, 62 or 63. I'm not sure which.

Closing as worksforme.

**Comment by jcsteh** [comment]
CC @PratikP1. The radio button brokenness you reported in #7373 is also fixed in Chrome Canary 63 (but is still broken in Chrome 60).

**Comment by PratikP1** [comment]
@jcsteh, I think #7337 is not the correct issue number. The one I reported was #6980 and dealt with Edge.

**Comment by jcsteh** [comment]
Sorry, I meant #7363.
