### ISSUE TITLE
Regular expression hotkey conflict in add dictionary entry dialog

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6782]
When adding a dictionary entry (NVDA+N, P, D, then enter, then alt+a or select an entry and alt+e)

The replacement field can be accessed directly by pressing alt+r.

The regular expression field has "r" underlined, however, alt+r only goes to replacement.

Also in the add dictionary entry dialog, the underlines only appear visually when alt is pressed.  In the edit dictionary entry field, the appropriate letters are underlined all the time.

Both very minor issues.

**Comment by josephsl** [comment]
Hi, Which pneumonic would you suggest? Thanks.

**Comment by jcsteh** [comment]
E would probably be the obvious choice, though I keep wanting to say x. :)

**Comment by Qchristensen** [comment]
I'm the same.  Both options start with R and E.  To be honest, I've always
thought, once you can't use the first letter of something, it's going to be
hard to remember.  E would probably work here though as it's the second
letter and the first letter of the second word (expression).  I can see the
argument for X as well though.


--
22 Point

Check out our first app, RapiTap! - Tap targets fast & avoid decoys:
Adrenaline pumping, Challenging, Accessible!
https://play.google.com/store/apps/details?id=au.com.twentytwopoint.rapitap
Free trial:
https://play.google.com/store/apps/details?id=au.com.twentytwopoint.rapitapfree

Web: http://www.22point.com.au
Facebook: https://www.facebook.com/22Point
Twitter: https://twitter.com/22PointApps

**Comment by ehollig** [comment]
@Qchristensen, can you confirm whether the second issue still exists for you? Seems okay with the latest Master.
[**@Qchristensen**](https://github.com/Qchristensen) commented:
> Also in the add dictionary entry dialog, the underlines only appear visually when alt is pressed.  In the edit dictionary entry field, the appropriate letters are underlined all the time.

Do we agree on the pneumonic for Regular expression to be "E"? (For the "E" in expression)

**Comment by Qchristensen** [comment]
With 2017.3 at least, the underline issue seems resolved.  Re the pneumonic, I'm happy with "E".
