### ISSUE TITLE
NVDA Browse Mode Cursor gets bottom of the Page -BUG

### ISSUE THREAD

**Issue by xxxAng** [nvaccess/nvda#6803]
I am having this strange issue, I have a Single Page Application where content of the page is getting changed though a button within it.
In Focus Mode, while using Tabs, the elements rotates well with no issues.
But In Browse mode, it starts well and move sequentially element to element but when new page is invited. The cursor remain bottom of the page not at the start of the page :( :(.
If I go previous by using up arrow it goes fine.
Is this is known bug with NVDA?

**Comment by ehollig** [comment]
@xxxAng, do you have an example test case you could provide that demonstrates this issue? Also, could you please provide exact detailed steps to reproduce, including what you did, what you expected to happen and what happened instead?

**Comment by ehollig** [comment]
Unfortunately, we still require more information to understand the scope of this issue. As we have not heard from the original author in over a year, I am going to close this as invalid.
