### ISSUE TITLE
Launcher: Remove Message.html File from Distribution

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#6804]
I generated a new portable copy of NVDA today, and noticed the above file appears to be included. Is there any particular reason that this file exists, and if not could it be removed?

**Comment by josephsl** [comment]
Hi, that’s utilized by ui.browsableMessage when reporting formatting info. Thanks.

**Comment by jcsteh** [comment]
As above, this file is intended to be there and removing it will break things.
