### ISSUE TITLE
Browse mode goes the way of the doedoe sometimes on e10s enabled firefox

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6806]
Sometimes randomly, firefox nightly with NVDA, e10s enabled, browse mode disappears in the middle of a webpage existing. For example, I did a google search for something, and the document was letting me move by heading level 2. Suddenly, I couldn't move by 2 anymore, tab started acting as if it were in focus mode, and bam, no more browse mode avbailable. Even nvda+space just sits there. There's no tree interceptor at all on objects, and here's some developer info.

Developer info for navigator object:
name: u'firefox addon compatibility checker - Google Search'
role: ROLE_DOCUMENT
states: STATE_READONLY, STATE_FOCUSABLE
isFocusable: True
hasFocus: False
Python object: <NVDAObjects.Dynamic_BrokenFocusedStateDocumentMozillaIAccessible object at 0x0544E430>
Python class mro: (<class 'NVDAObjects.Dynamic_BrokenFocusedStateDocumentMozillaIAccessible'>, <class 'NVDAObjects.IAccessible.mozilla.BrokenFocusedState'>, <class 'NVDAObjects.IAccessible.mozilla.Document'>, <class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Document'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (0, 101, 1349, 627)
value: None
appModule: <'firefox' (appName u'firefox', process ID 11144) at address 5107bb0>
appModule.productName: u'Nightly'
appModule.productVersion: u'54.0a1'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 2361720L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 10116
windowText: u'firefox addon compatibility checker - Google Search - Nightly'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x7adc1ec at 544a440>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=2361720L, objectID=-4, childID=-16777218
IAccessible accName: u'firefox addon compatibility checker - Google Search'
IAccessible accRole: ROLE_SYSTEM_DOCUMENT
IAccessible accState: STATE_SYSTEM_READONLY, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048640)
IAccessible accDescription: u''
IAccessible accValue: u'https://www.google.com/search?q=firefox+addon+compatibility+checker&ie=utf-8&oe=utf-8'
IAccessible2 windowHandle: 2361720
IAccessible2 uniqueID: -16777218
IAccessible2 role: ROLE_SYSTEM_DOCUMENT
IAccessible2 states: IA2_STATE_ACTIVE, IA2_STATE_OPAQUE (1025)
IAccessible2 attributes: u'margin-left:0px;text-align:start;text-indent:0px;id:gsr;tag:body;class:srp tbo vasq;margin-right:0px;margin-top:0px;margin-bottom:0px;display:block;explicit-name:true;'

Random heading for a result:

Developer info for navigator object:
name: u'Add-on Compatibility Reporter :: Add-ons for Firefox'
role: ROLE_LINK
states: STATE_FOCUSABLE, STATE_LINKED, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x05438E10>
Python class mro: (<class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (166, 225, 414, 21)
value: u'https://addons.mozilla.org/en-us/firefox/addon/add-on-compatibility-reporter/'
appModule: <'firefox' (appName u'firefox', process ID 11144) at address 5107bb0>
appModule.productName: u'Nightly'
appModule.productVersion: u'54.0a1'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 2361720L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 10116
windowText: u'firefox addon compatibility checker - Google Search - Nightly'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x7ad5afc at 5504ee0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=2361720, objectID=-4, childID=-16778859
IAccessible accName: u'Add-on Compatibility Reporter :: Add-ons for Firefox'
IAccessible accRole: ROLE_SYSTEM_LINK
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_LINKED, STATE_SYSTEM_VALID (5242884)
IAccessible accDescription: u''
IAccessible accValue: u'https://addons.mozilla.org/en-us/firefox/addon/add-on-compatibility-reporter/'
IAccessible2 windowHandle: 2361720
IAccessible2 uniqueID: -16778859
IAccessible2 role: ROLE_SYSTEM_LINK
IAccessible2 states: IA2_STATE_SELECTABLE_TEXT, IA2_STATE_OPAQUE (5120)
IAccessible2 attributes: u'margin-left:0px;text-align:left;draggable:true;text-indent:0px;margin-right:0px;tag:a;margin-top:0px;margin-bottom:0px;display:inline;'

The tree interceptor for this is None.

>>> focus.treeInterceptor

I'm happy to let you browse on my machine a bit with nvdaremote if you want to see what happens, although we'll want to try when I'm not using my computer, say at night.

**Comment by PratikP1** [comment]
I see the same problem when NVDA is updated while FF is running. Browse mode is switched off and can’t be switched on again until FF is relaunched. It occurs with Nightly and FF standard.

**Comment by derekriemer** [comment]
Are you experencing this all the time? That may be https://github.com/nvaccess/nvda/issues/6505

**Comment by PratikP1** [comment]
Looks like what I’m experiencing is more akin to #5758

**Comment by leonardder** [comment]
@derekriemer: Is this issue still relevant?

**Comment by derekriemer** [comment]
no
