### ISSUE TITLE
Provide NVDA command line switches in an ini file

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6812]
It is possible to provide command line switches to NVDA, but it would be a handy addition if we could provide them in an ini file in the root of the NVDA installation folder.

I have the following use case. In a corporate environment where I would like to implement NVDA on behalf of @babbagecom, the roaming appdata profiles used can't exeed the size of 50mb. Thus, what I'd like to do is set the local appdata profile as the default for storing the NVDA configuration. This can be done by changing the NVDA shortcut, but that is a slightly ugly fix since people would be able to change their shortcuts, an update can break the particular shortcut, etc. Define such options in an ini file would be helpful in this case.

**Comment by derekriemer** [comment]
Useful to change the default location of the configuration, which is not possible because I can't pass command line parameters to ease of access.

**Comment by feerrenrut** [comment]
Can I ask which command line switches you are using? Rather than introduce a new ini file, we could read these particular options from the current nvda configuration.

**Comment by leonardder** [comment]
I'm afraid it is not possible to read the current configuration, as the primary reason I want to do this, is that I'd like to change the default config path for every user on the system.

**Comment by leonardder** [comment]
I noticed that the optparse module is deprecated in favour of argparse. So, I thought it would be a good idea to move the argument parser to argparse in the first place, which at least has functionality on board to parse command line variables from files (one argument per line). One of the questions we need answered is, do we want a file with just a raw command line argument on every line, or do we want a nicer, ini-style kind of file?

**Comment by jcsteh** [comment]
In this case, I'd suggest we narrow the scope to the use case. I don't think there's much use for making most of those command line arguments ini settings, at least not the ones that already aren't. Your use change is changing the default config folder system wide. Rather than using an ini file, I'd suggest we just have a setting in the hklm registry for this.

**Comment by leonardder** [comment]
Hmm, haven't thought about that one. Should this be a hidden trick, or 
should it be visible in the GUI somewhere?

**Comment by jcsteh** [comment]
I don't think it's unreasonable for this to not have a GUI, but it does
need to be documented, perhaps in the Advanced section of the User Guide.
