### ISSUE TITLE
support visual studio 2017

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#6821]
hello all.

currently nvda build script doesn't support vs2017

can you please support it?

**Comment by jcsteh** [comment]
We previously tried to support multiple versions of Visual Studio, but doing so requires a fair amount of work and is difficult to maintain. Thus, we will only support one version of Visual Studio at a time. At this stage, we have no need to upgrade to 2017. Once we do, though, we will drop support for 2015 and 2017 will become the version we support.

I'm closing this. We'll open a new issue if we need to update to 2017 at some later point.
