### ISSUE TITLE
audioducking not supported on self-built nvda

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#6823]
hello all.

we are maintaining a separate nvda for our own needs.
i tried to build an updated version on windows 10 vs2015 but for some reason i am not able to use audioducking feature.
it says not available.

could i miss some necessary tools for building?

thanks.

**Comment by jcsteh** [comment]
Audio ducking is only available for applications which have the uiAccess privilege, which requires the app to be signed with an Authenticode certificate (which you must purchase). The app must also be installed. This is a security restriction enforced by Windows.

**Comment by beqabeqa473** [comment]
possible problemis that in the log the followingis written

Using Windows version 6.2.9200 workstation

but build was performed on windows 10 machine.
