### ISSUE TITLE
NVDA gets stuck in Message multi line edit field when opening an MS Word document in Windows Explorer

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#6832]
At the outset, I apologize for the potential ambiguity of this issue and in the manner in which I describe it. In actuality, whenever I open an MS Word document in any folder or path in Windows Explorer, focus shifts to a Message edit multi line field, I am unable to Tab or arrow around or move in Windows Explorer, I need to Alt Tab to the document as opposed to it gaining direct focus, and all subsequently opened new blank Word documents are number with two and three digits (such as Document 49, Document 132, etc.). The only inconsistency in this entire process is that sometimes I am able to Tab out of the Message edit multi line and work further with files and folders through Windows Explorer, whereas sometimes arrowing and Tabbing proves futile. Please find attached a relevant snippet of log containing several repetitive errors that were getting generated followed by hopefully the Message edit multi line field's control information. As a side note, I am unable to enter any text in or edit 
[Message Edit Multi Line Errors.txt](https://github.com/nvaccess/nvda/files/746940/Message.Edit.Multi.Line.Errors.txt)
the Message box.

**Comment by ehollig** [comment]
This appears to be an issue with the preview pane in windows explorer with a Microsoft Word document. CC @michaelDCurran

**Comment by Adriani90** [comment]
@bhavyashah, @ehollig are you still able to reproduce this issue?

**Comment by Adriani90** [comment]
We do not have any updates since years on this issue. Closing as abandoned. I cannot reproduce it in NVDA 2019.3 RC3.
Please comment on it if you still see this issue and we can reopen it. Thanks.
