### ISSUE TITLE
Help panel of new Google Voice is silent

### ISSUE THREAD

**Issue by 4RJames** [nvaccess/nvda#6840]
Using NVDA with Firefox
When trying to provide feedback on accessibility with the new Google Voice web interface
Most things arte accessible
However, when using the help/feedback a help panel is presented
The help panel is silent when using mouse over to access / read the panel
Unable to provide feedback

**Comment by ehollig** [comment]
@4RJames, is this still the case?

**Comment by ehollig** [comment]
Google Voice has changed quite a bit since this issue was opened. I am closing as invalid, but if this is still the case, we can reopen it.
