### ISSUE TITLE
Nvda makes an error sound and does not make the input sound in focus mode in the text editing field in the google translator.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#6843]
When opening the google translate window and pressing enter on the site text editing field, nvda makes an error sound and does not make the input sound in focus mode
To do the tests:
Open google chrome and enter the site:
Https://translate.google.com/
Now notice that the edit field is already announced, press enter to be able to type the characters to be translated.
What happens is that a nvda sound is heard, and the incoming sound in focus mode is not done.
The expected would be that the incoming sound in focus mode would be heard.
Attention so that if soon after hearing the ad of the text field in google translator press an arrow and then enter to be able to enter the text the error sound is not heard.
Tests on nvda master 13865 and chrome 56 on a windows 10 build 14393 64bits.
Other software updates presented the same problem.
The error does not only occur in the google translator, in other sites where shortly after entering the edit field is in focus makes the same error, google search, new error in GitHub.
Last question that may be of interest is that the option of automatic entry in focus mode in nvda is disabled.
Follow the log:

IO - speech.speak (10:55:50):
Speaking [u'Tradutor', u'visitado  linque']
IO - inputCore.InputManager.executeGesture (10:55:51):
Input: kb(laptop):enter
IO - speech.speak (10:55:52):
Speaking [u'Google Tradutor  documento']
IO - speech.speak (10:55:52):
Speaking [u'edi\xe7\xe3o  multilinha']
IO - speech.speak (10:55:52):
Speaking [u'Google Tradutor  documento']
IO - tones.beep (10:55:52):
Beep at pitch 226.446492062, for 80 ms, left volume 50, right volume 50
IO - speech.speak (10:55:52):
Speaking [u'em branco']
IO - inputCore.InputManager.executeGesture (10:55:57):
Input: kb(laptop):enter
ERROR - scriptHandler.executeScript (10:55:57):
error executing script: <bound method ChromeVBuf.script_activatePosition of <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x0AF453B0>> with gesture u'\xeanter'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "browseMode.pyc", line 388, in script_activatePosition
  File "browseMode.pyc", line 1094, in _activatePosition
  File "browseMode.pyc", line 379, in _activatePosition
  File "treeInterceptorHandler.pyc", line 118, in _set_passThrough
  File "review.pyc", line 117, in setCurrentMode
  File "review.pyc", line 25, in getObjectPosition
  File "NVDAObjects\__init__.pyc", line 958, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 93, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 201, in _findContentDescendant
COMError: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (10:56:06):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (10:56:06):
Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x0AF45A90>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.ia2Web.Editor'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (29, 239, 634, 105)
value: None
appModule: <'appModuleHandler' (appName u'chrome', process ID 46536) at address af45530>
appModule.productName: u'Google Chrome'
appModule.productVersion: u'56.0.2924.87'
TextInfo: <class 'NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo'>
windowHandle: 328900L
windowClassName: u'Chrome_RenderWidgetHostHWND'
windowControlID: 176452952
windowStyle: 1445986304
windowThreadID: 34844
windowText: u'Chrome Legacy Window'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0xe0b18b4 at ada03f0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=328900, objectID=-4, childID=-232
IAccessible accName: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accRole: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accState: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accDescription: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accValue: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 windowHandle: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 uniqueID: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 role: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 states: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 attributes: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))

**Comment by Brian1Gaff** [comment]
I have encountered this on many different edit fields in many browsers and 
on some versions of windows edits, ie when you go in it gives an error but 
does in fact work. There do seem to be lots of cases in nvda where error 
sounds can occur, like  fleetingly visible batch file displays where they 
are gone by time it decides to try to do  something with them. I did wonder 
if there might be something pre written in some fields that goes when the 
cursor is detected there in focus mode.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by fernando-jose-silva** [comment]
Thanks, I'll do more tests, I'll type a text in the text field, and see if the problem happens.
I'll do this later, I'm away from the computer.

Enviado do meu iPhone

> Em 5 de fev de 2017, às 07:40, Brian1Gaff <notifications@github.com> escreveu:
> 
> I have encountered this on many different edit fields in many browsers and 
> on some versions of windows edits, ie when you go in it gives an error but 
> does in fact work. There do seem to be lots of cases in nvda where error 
> sounds can occur, like fleetingly visible batch file displays where they 
> are gone by time it decides to try to do something with them. I did wonder 
> if there might be something pre written in some fields that goes when the 
> cursor is detected there in focus mode.
> Brian

**Comment by fernando-jose-silva** [comment]
I tested it on a machine with windows 7 and nvda master 13865 and the bug also happened

**Comment by bhavyashah** [comment]
@fernando-jose-silva I believe you had reported another issue particularly related to translate.google.com on Chrome which seemed to have been resolved according to recent tests you and others performed. Could you please provide us a status update for this ticket too and let us know the current standing of the reported error?

**Comment by fernando-jose-silva** [comment]
Perfect, works correctly, sounds of errors are no longer heard in this case.

**Comment by ehollig** [comment]
Closing, as reported fixed in https://github.com/nvaccess/nvda/issues/6843#issuecomment-324635978
