### ISSUE TITLE
Cannot "escape" out of the "Confirm Deletion" prompt when the Deleting Configuration button is pressed

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6851]
In NVDA's Configuration profiles dialog, select a profile, and press alt+d or activate the "delete" button.

The "Confirm deletion" prompt appears.  Options are Yes or No.

Pressing escape should select no and close the dialog without deleting, however it does nothing.  There is no need for a "cancel" button as "No" performs the same function.

Not high priority, however potentially opens up possibility of inadvertently deleting a configuration profile if someone accidentally opens the delete prompt and thinks they have dismissed it with escape.

**Comment by josephsl** [comment]
Hi,

Confirmed.

Technical: gui.messageBox flags might be the culprit here.

Thanks.

**Comment by feerrenrut** [comment]
Looks like this is because we are using `wx.YES | wx.NO` flags with the message box.
The [wx docs for messageBox](http://docs.wxwidgets.org/3.1.0/classwx_message_dialog.html) specifies:

>  It is recommended to always use wxCANCEL with this style as otherwise the message box won't have a close button under wxMSW and the user will be forced to answer it.

Adding wx.CANCEL allows the dialog to be dismissed with the `esc` key

**Comment by Qchristensen** [comment]
I can understand why we have the buttons we do - it IS a yes / no question
- and there is no difference between saying "no" and pressing a "cancel"
button.  I don't think adding a cancel button would add confusion if there
isn't an easy way to simply catch someone pressing the escape key and
activate the no button if they do?


--
22 Point

Check out our first app, RapiTap! - Tap targets fast & avoid decoys:
Adrenaline pumping, Challenging, Accessible!
https://play.google.com/store/apps/details?id=au.com.twentytwopoint.rapitap
Free trial:
https://play.google.com/store/apps/details?id=au.com.twentytwopoint.rapitapfree

Web: http://www.22point.com.au
Facebook: https://www.facebook.com/22Point
Twitter: https://twitter.com/22PointApps

**Comment by feerrenrut** [comment]
Adding `wx.CANCEL` results in three buttons (yes, no, and cancel). Rather than do that I have re-worded the sentence, swapped to use the ok/cancel buttons. The message box will now say: 
>This profile will be permanently deleted, this action cannot be undone.

**Comment by Qchristensen** [comment]
That's probably a better solution, good job.


--
22 Point

Check out our first app, RapiTap! - Tap targets fast & avoid decoys:
Adrenaline pumping, Challenging, Accessible!
https://play.google.com/store/apps/details?id=au.com.twentytwopoint.rapitap
Free trial:
https://play.google.com/store/apps/details?id=au.com.twentytwopoint.rapitapfree

Web: http://www.22point.com.au
Facebook: https://www.facebook.com/22Point
Twitter: https://twitter.com/22PointApps
