### ISSUE TITLE
we want the FN key to be a sticky key

### ISSUE THREAD

**Issue by fatmamehanna** [nvaccess/nvda#6857]
hi devs,
as mentioned in the summary, we want the fn key to be a sticky key. most of the wireless keyboards have the fn key, which is used to do many essential functions. is it possible to do this?
thanks.

**Comment by jcsteh** [comment]
Unfortunately not. The fn key is handled by the keyboard itself, not by Windows, so NVDA has no opportunity to make it "stick".
