### ISSUE TITLE
In Richedit20 documents, spaces before some non English characters aren't considered as marking the end of words

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#6861]
I have seen this in a program (I will attach the log with dev info), and a friend reports the same with HJPad. I don't have JAWS, but this doesn't happen in Wordpad, so I think this maybe related to RichEdit20 objects.
[nvda.log.txt](https://github.com/nvaccess/nvda/files/763494/nvda.log.txt)

**Comment by Adriani90** [comment]
@nvdaes is this still the case in the last versions of the editors?

**Comment by Adriani90** [comment]
We didn't get any updates upon request from the initial author since many years, I am closing as abandoned. @nvdaes if you are still having this issue with NvDA 2024.4 Beta, please comment and we can reopen.
