### ISSUE TITLE
Nvda never finish reading the page in firefox

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#6870]
I was reading an article on a web page using firefox, and I faced a problem.
Nvda never finishes reading the page.
When navigating with the arrows below the page is read to a certain point, and then the reading resumes from a previous bookcase, staying in eternal lupe without being able to read the entire page.
The page is read up to about 3% checked with the nvda + delete command, and then jumps to the previous 1% point. The article starts at about 5%.
This is a bug reported for chrome at a time.
For the tests, open the page:

http://wp.clicrbs.com.br/conecte/2016/06/24/seu-iphone-desliga-quando-ainda-ha-10-de-bateria-se-sim-leia-este-post/?topo=52,1,1,,171,e171
Now read the page with arrows below.
Note that you'll never get to the bottom of the page.

Tested on nvda next 13881 and firefox 51.0.1 windows 10 64bits 14393.

Follows the log:

IO - inputCore.InputManager.executeGesture (10:34:43):
Input: kb(laptop):downArrow
IO - speech.speak (10:34:43):
Speaking [u'linque', u'seu-iphone-desliga-quando-aind\u2026']
IO - speech.speak (10:34:43):
Speaking [u'Imprimir', u'linque']
IO - inputCore.InputManager.executeGesture (10:34:47):
Input: kb(laptop):downArrow
DEBUGWARNING - RPC process 40604 (firefox.exe) (10:34:47):
Thread 40644, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::getLineOffsets, 985:
Offset of 10250 too big for buffer, returning false

IO - speech.speak (10:34:47):
Speaking [u'linque', u'clicRBS']
IO - inputCore.InputManager.executeGesture (10:34:52):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (10:34:52):
Developer info for navigator object:
name: u'clicRBS'
role: ROLE_LINK
states: STATE_FOCUSABLE, STATE_LINKED, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x0ACC7710>
Python class mro: (<class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (175, 69, 101, 32)
value: u'http://www.clicrbs.com.br/'
appModule: <'firefox' (appName u'firefox', process ID 40604) at address 53062b0>
appModule.productName: u'Firefox'
appModule.productVersion: u'51.0.1'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 1181318L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 40612
windowText: u'Conecte \xbb Arquivo \xbb Seu iPhone desliga quando ainda h\xe1 10% de bateria? Se sim, leia este post - Mozilla Firefox'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0xa9d8cd4 at acd2bc0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=1181318, objectID=-4, childID=-3379
IAccessible accName: u'clicRBS'
IAccessible accRole: ROLE_SYSTEM_LINK
IAccessible accState: STATE_SYSTEM_FLOATING, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_LINKED, STATE_SYSTEM_VALID (5246980)
IAccessible accDescription: u''
IAccessible accValue: u'http://www.clicrbs.com.br/'
IAccessible2 windowHandle: 1181318
IAccessible2 uniqueID: -3379
IAccessible2 role: ROLE_SYSTEM_LINK
IAccessible2 states: IA2_STATE_SELECTABLE_TEXT, IA2_STATE_OPAQUE (5120)
IAccessible2 attributes: u'margin-left:0px;text-align:center;draggable:true;text-indent:-9999px;formatting:block;margin-right:0px;tag:a;class:clicBarra-logo-clic;margin-top:0px;margin-bottom:0px;display:block;'

**Comment by jcsteh** [comment]
This is the same problem as #4797. When you reach (and thus focus) the link for more sharing options (the link below Pinterest), the page throws focus to another link, but that link then disappears. The page absolutely shouldn't be bouncing focus around like this; it is a serious authoring error.

Again, a fix for #2039 might work around this, but the social sharing widget they're using really needs to be fixed anyway.
