### ISSUE TITLE
Problem reading the password field in outlook 2016

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#6871]
Accompanying some errors in reading the account settings window in outlook 2016 already reported in some calls, I would add one more that I noticed.
When attempting to change the password of an email account, nvda upon reaching the password field makes a sequence of errors, and repeats these errors when trying to navigate with the arrows or when deleting characters in this password field
To reproduce.
Open the window for changing an email account in Outlook 2016 and navigate with tab to the password field.
Expected is that the nvda read the name of the field, what aconesse is that sounds of errors are reproduced.
When trying to navigate with the arrows by the field note that asteríscos are not read, the expected one was that they were.
And finally try to delete the characters of the password with backspace, the expected would be that the asterisk was read, what would happen is that the sound of error is heard and by what I stopped the characters are not deleted.
Outlook 2016 32 bit, Office 365 updated nvda next 13881 and windows 10 64bit 14393.
Follow the log:

IO - inputCore.InputManager.executeGesture (10:51:45):
Input: kb(laptop):rightArrow
IO - speech.speak (10:51:45):
Speaking [u'em branco']
ERROR - eventHandler.executeEvent (10:51:45):
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x0AF4AAB0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1280, in event_caret
  File "NVDAObjects\window\edit.pyc", line 825, in event_caret
  File "NVDAObjects\behaviors.pyc", line 173, in event_caret
  File "editableText.pyc", line 255, in detectPossibleSelectionChange
  File "speech.pyc", line 552, in speakSelectionChange
  File "baseObject.pyc", line 21, in __get__
  File "NVDAObjects\window\edit.pyc", line 747, in _get_text
  File "NVDAObjects\window\edit.pyc", line 623, in _getTextAtRange
  File "comtypes\__init__.pyc", line 266, in __getattr__
COMError: (-2147467259, 'Erro n\xe3o especificado', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (10:51:46):
Input: kb(laptop):rightArrow
IO - speech.speak (10:51:47):
Speaking [u'em branco']
IO - inputCore.InputManager.executeGesture (10:51:48):
Input: kb(laptop):backspace
ERROR - scriptHandler.executeScript (10:51:48):
error executing script: <bound method Dynamic_IAccessibleRichEdit20WindowNVDAObject.script_caret_backspaceCharacter of <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x0AF4AAB0>> with gesture u'b\xe9c speice'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 189, in script_caret_backspaceCharacter
  File "editableText.pyc", line 175, in _backspaceScriptHelper
  File "baseObject.pyc", line 21, in __get__
  File "NVDAObjects\window\edit.pyc", line 747, in _get_text
  File "NVDAObjects\window\edit.pyc", line 623, in _getTextAtRange
  File "comtypes\__init__.pyc", line 266, in __getattr__
COMError: (-2147467259, 'Erro n\xe3o especificado', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (10:51:52):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (10:51:52):
Developer info for navigator object:
name: u'Senha:'
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_PROTECTED, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x0AF4AAB0>
Python class mro: (<class 'NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.edit.RichEdit20'>, <class 'NVDAObjects.window.edit.RichEdit'>, <class 'NVDAObjects.window.edit.Edit'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (443, 507, 145, 16)
value: None
appModule: <'outlook' (appName u'outlook', process ID 41072) at address 521f390>
appModule.productName: u'Microsoft Outlook'
appModule.productVersion: u'16.0.6965.2117'
TextInfo: <class 'NVDAObjects.window.edit.ITextDocumentTextInfo'>
windowHandle: 460984
windowClassName: u'RichEdit20WPT'
windowControlID: 350
windowStyle: 1342259360
windowThreadID: 42736
windowText: u'fesi05'
displayText: u'******'
IAccessibleObject: <POINTER(IAccessible) ptr=0xa3b9138 at 5bb9170>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=460984, objectID=-4, childID=0
IAccessible accName: u'Senha:'
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_PROTECTED, STATE_SYSTEM_VALID (537919492)
IAccessible accDescription: None
IAccessible accValue: exception: (-2147024891, 'Acesso negado.', (None, None, None, 0, None))

**Comment by PratikP1** [comment]
All password fields in Outlook seem to suffer this problem. If any password field shows up, this can be replicated.

**Comment by fernando-jose-silva** [comment]
I recently did not see another password field to test.

Enviado do meu iPhone

**Comment by jcsteh** [comment]
CC @Neurrone.

To those who've seen this, does the name of the field still get read as expected when you tab to it? That is, are you aware you should enter a password here? Even if we do fix this, because it's a password field, the most you'll get is asterisks. Just trying to work out the priority here for a fix. Aside from the error sounds (which don't occur in releases), how much does this really affect the user?

CC @MichaelDCurran. Looks like we use ITextDocument here and it throws E_FAIL as soon as we try to call rangeObj.text. For a password field, we only need the length anyway. For this field, we should be able to get the length from windowText, but this would be Outlook specific; this won't work for windowless RichEdit. Thoughts?

**Comment by michaelDCurran** [comment]
@jcsteh: I would say we should fall back to window message richEdit support if the object has the protected state. It seems that multiple ITextDocument methods/properties do not work in these situations.

**Comment by PratikP1** [comment]
@jcsteh wrote:

  *   To those who've seen this, does the name of the field still get read as expected when you tab to it? That is, are you aware you should enter a password here? Even if we do fix this, because it's a password field, the most you'll get is asterisks. Just trying to work out the priority here for a fix. Aside from the error sounds (which don't occur in releases), how much does this really affect the user?



This doesn’t happen too often. When The password field is presented, it’s apparent from the context that the password is expected in the field. The problem is not knowing that 1( anything is entered; and 2) when something is entered, not knowing the length of such entry.



  *

**Comment by Adriani90** [comment]
@fernando-jose-silva is this issue still reproducible? The interface of changing account and so on has been changed in Outlook since then. Please test again and confirm wether this is still an issue.

**Comment by Adriani90** [comment]
@josephsl, @leonardder I think the behavior of Outlook is in Office 2019 almost similar like in Office 2016. Or should this be tested by users of Outlook 2016 still?

**Comment by Adriani90** [comment]
I am testing in Outlook 2016 and Outlook 365, the issue is still reproducible with NVDA 2019.1 as follows:
1. Open Outlook
2. Go to file ribbon
3. Go to information with arrow keys and press tab until you hear (account settings)
4. Press spacebar to expand it
5. Press tab to land on "change password"
6. Type something in the edit field
7. Press tab and shift+tab
8. Press left and right arrows to navigate through the content of the edit field.
Actual: NVDA shows errors in the log and does not report the content of the field (normally star star star)
Expected: No errors should show up and star star star should be reoprted when navigating with arrow keys.

The relevant part of the log follows.

**Comment by Adriani90** [comment]
```
IO - inputCore.InputManager.executeGesture (19:34:21.403):
Input: kb(laptop):shift+tab
IO - inputCore.logTimeSinceInput (19:34:21.493):
0.090 sec since input
IO - speech.speak (19:34:21.493):
Speaking [u'T  Eingabefeld']
ERROR - eventHandler.executeEvent (19:34:21.523):
error executing event: gainFocus on <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x032CEEB0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 179, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 966, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 854, in reportFocus
  File "speech.pyc", line 420, in speakObject
  File "speech.pyc", line 781, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 657, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 603, in _getTextAtRange
  File "comtypes\__init__.pyc", line 279, in __getattr__
COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (19:34:21.877):
Input: kb(laptop):leftArrow
DEBUGWARNING - Python warning (19:34:21.933):
C:\Program Files (x86)\NVDA\library.zip\keyboardHandler.py:524: DeprecationWarning: Yield() is deprecated
DEBUG - editableText.EditableText._hasCaretMoved (19:34:22.142):
Caret didn't move before timeout. Elapsed: 100 ms
ERROR - scriptHandler.executeScript (19:34:22.173):
error executing script: <bound method Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_moveByCharacter of <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x032CEEB0>> with gesture u'Pfeiltaste nach links'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 189, in script_caret_moveByCharacter
  File "editableText.pyc", line 144, in _caretMovementScriptHelper
  File "editableText.pyc", line 130, in _caretScriptPostMovedHelper
  File "speech.pyc", line 781, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 657, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 603, in _getTextAtRange
  File "comtypes\__init__.pyc", line 279, in __getattr__
COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (19:34:22.312):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (19:34:22.371):
Caret move detected using bookmarks. Elapsed: 0 ms
IO - inputCore.logTimeSinceInput (19:34:22.401):
0.089 sec since input
IO - speech.speak (19:34:22.401):
Speaking [u'Leer']
```
