### ISSUE TITLE
Include braille tables in the quick settings ring

### ISSUE THREAD

**Issue by Piciok** [nvaccess/nvda#6882]
At times I find myself in a situation where I need to read or write text in two different languages. For that purpose I need to go through braille settings to change the output or input tables. It would be handy to have these two in the quick settings ring alongside the TTS parameters.

**Comment by josephsl** [comment]
Hi, can you do it by using a manual config profile? Thanks.

**Comment by Piciok** [comment]
I can imagine two scenarios that often apply to my personal workflow and profiles won't be of much help:

1. following a language course where the language of instruction is different than the language taught and requires quickly jumping between two languages with different character sets.

2. Working with PoEdit, Fluency or other CAT tool and a pair of languages with different character sets.

Profiles are a great, powerful tool provided you are going to stick to one language in that particular piece of software.
Same could be said for braille input: composing documents, emails or posting to social networks in multiple languages could do with such a productivity booster.

**Comment by jcsteh** [comment]
To clarify, why are profiles not an option for multiple languages? You'd
just define one profile for one language and another profile for another
language, with appropriate settings in each.

**Comment by Piciok** [comment]
This suggestion works in the described scenarios, however it could do with extending it to support triggering profiles by individually assigned hotkeys.
Ideally, I would like to have the ability to switch the parameters in an instant which would be especially useful in translation enviromments such as Poedit where the operation of entering the profiles dialogue would have to be performed every couple of seconds to switch between the braille tables of the source and target languages (actually twice per string)/.
I believe this is the closest that we can get to the experience of a sighted translator acquiring both languages at the same time by simply looking at the screen.

**Comment by jcsteh** [comment]
Switching config profiles with keyboard shortcuts is covered by #4209. Would that satisfactorily solve your use case? If so, I'll close this but note it as a use case for #4209. Thanks.

**Comment by dkager** [comment]
@Piciok Any thoughts?
I would also say triggering config profiles by a hotkey is the preferable solution. You probably don't want all braille tables in the settings ring, so there has to be a UI to select the ones you want. Putting manual config profiles in the settings ring or giving them hotkeys sounds more flexible.

**Comment by ehollig** [comment]
Closing in favor of #4209. @Piciok, feel free to comment if you have any additional comments or thoughts.
