### ISSUE TITLE
footnotes frame is latent in word.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6902]
As seen below in this log, there are some timing issues when moving around in the footnotes frame of a word document which is my database systems book. Unfortunately, I can't share this document publicly, but could email it to NV Access. I am seeing a pause of at least 500 MS in many cases, when pressing down arrow into the frame, or while navigating the frame. Additionally, I have noticed that this doesn't occur outside the frame.
Get the millisecond precise timings like this.
log.handlers[0].formatter.datefmt = None

Input: kb(laptop):downArrow
IO - speech.speak (2017-02-21 09:50:10,703):
Speaking [u'Figure 2.8: Declaring the relation schema for the ', u'spelling error', u'MovieStar relation']
IO - inputCore.InputManager.executeGesture (2017-02-21 09:50:11,463):
Input: kb(laptop):downArrow
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (2017-02-21 09:50:11,517):
oleacc.AccessibleObjectFromEvent with window 198808, objectID 23802 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (2017-02-21 09:50:11,519):
oleacc.AccessibleObjectFromEvent with window 133160, objectID 23804 and childID 0: [Error -2147467259] Unspecified error
IO - tones.beep (2017-02-21 09:50:13,450):
Beep at pitch 233.081880759, for 80 ms, left volume 50, right volume 50
IO - speech.speak (2017-02-21 09:50:13,476):
Speaking [u'Footnotes  frame', u'foot note  3', u'The number 255 is not the result of some weird notion of what typical addresses look like. A single ']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (2017-02-21 09:50:14,280):
oleacc.AccessibleObjectFromEvent with window 198808, objectID 23837 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (2017-02-21 09:50:14,282):
oleacc.AccessibleObjectFromEvent with window 133160, objectID 23839 and childID 0: [Error -2147467259] Unspecified error
IO - inputCore.InputManager.executeGesture (2017-02-21 09:50:16,586):
Input: kb(laptop):downArrow
IO - tones.beep (2017-02-21 09:50:18,377):
Beep at pitch 220, for 80 ms, left volume 50, right volume 50
IO - speech.speak (2017-02-21 09:50:18,398):
Speaking [u'byte can store integers between 0 and 255, so it is possible to represent a varying-length character string ']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (2017-02-21 09:50:18,457):
oleacc.AccessibleObjectFromEvent with window 198808, objectID 23867 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (2017-02-21 09:50:18,457):
oleacc.AccessibleObjectFromEvent with window 133160, objectID 23869 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (2017-02-21 09:50:19,247):
oleacc.AccessibleObjectFromEvent with window 198808, objectID 23871 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (2017-02-21 09:50:19,249):
oleacc.AccessibleObjectFromEvent with window 133160, objectID 23873 and childID 0: [Error -2147467259] Unspecified error
IO - inputCore.InputManager.executeGesture (2017-02-21 09:50:20,088):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (2017-02-21 09:50:20,286):

**Comment by Qchristensen** [comment]
I started looking at this in response to a report from a user of sluggishness navigating footnotes.  I'm not getting all the errors, but there is definitely a delay of between 500 - 700ms.  I tested both using down arrow and using control+down arrow and also using SAPI 5, OneCore and eSpeak voices.  Log taken from Master 14241, but same behaviour observed in stable 2017.2 (my notes in parenthesis):

(Pressed control+down arrow)
IO - inputCore.InputManager.executeGesture (10:57:13.091):
Input: kb(desktop):control+downArrow
IO - speech.speak (10:57:13.813):
Speaking [u'foot note  18',.... (then reads footnote)


(Pressed down arrow while still reading previous footnote)
IO - inputCore.InputManager.executeGesture (11:01:58.098):
Input: kb(desktop):downArrow
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (11:01:58.114):
Cancelling
DEBUG - editableText.EditableText._hasCaretMoved (11:01:58.135):
Caret move detected using bookmarks. Elapsed: 0 ms
IO - speech.speak (11:01:58.671):
Speaking [u'foot note  19', (then reads footnote)



(Changed to eSpeak and pressed control+down arrow)
IO - inputCore.InputManager.executeGesture (11:03:46.131):
Input: kb(desktop):control+downArrow
IO - speech.speak (11:03:46.878):
Speaking [u'foot note  18', (then reads footnote)

**Comment by Qchristensen** [comment]
I just did a bit more testing, I tried a few different footnotes of various lengths and it seems that, setting aside a delay of around 170ms to move from one footnote to the next, there is a delay of about 2.5 ms per character (of the new footnote) before it is read out.
If moving to a footnote with 10 characters, the delay is around 170ms + (2.5 x 10) = 195ms (1/5th of a second)
If moving to a footnote with 100 characters, the delay would be 170ms + (2.5 x 100) = 430ms (just under half a second)
If moving to a footnote with 1000 characters, the delay would be 170ms + (2.5 x 1000) = 2670ms (2.67 seconds).

Here's my working out from my testing and my log:

Footnote 2
Lengh: 150 chars
Delay: 604 ms

Footnote 3
Lengh: 51 chars
Delay: 286 ms

Footnote 4
Lengh:  5 chars
Delay: 178 ms

Footnote 5
Lengh: 5 chars
Delay: 171

Footnote 6
Lengh: 702 chars
Delay: 1825 ms

Footnote 7
Lengh: 1 character
Delay: 177 ms

Original log entries:
IO - inputCore.InputManager.executeGesture (11:57:54.178):
Input: kb(desktop):control+downArrow
IO - speech.speak (11:57:54.782):
Speaking [u'foot note  2', u' ', u' This is the story, of a man named Brady, who was bringing up three very lovely girls.  Something ', u'spelling error', u'something, like their mother, the oldest one in curls\n']
IO - inputCore.InputManager.executeGesture (11:58:00.562):
Input: kb(desktop):control+downArrow
IO - speech.speak (11:58:00.848):
Speaking [u'foot note  3', u' ', u' Blah2 The quick brown fox jumps over the lazy dog.\n']
IO - inputCore.InputManager.executeGesture (11:58:03.355):
Input: kb(desktop):control+downArrow
IO - speech.speak (11:58:03.533):
Speaking [u'foot note  4', u' ', u' Blah3\n']
IO - inputCore.InputManager.executeGesture (11:58:04.530):
Input: kb(desktop):control+downArrow
IO - speech.speak (11:58:04.701):
Speaking [u'foot note  5', u' ', u' Blah5\n']
IO - inputCore.InputManager.executeGesture (11:58:05.770):
Input: kb(desktop):control+downArrow
IO - speech.speak (11:58:07.595):
Speaking [u'foot note  6', u' ', u' This is a really long footnote.  It\u2019s super long, it\u2019s so long you would not believe someone could ramble on so long in just one footnote, it\u2019s that long.  Ok, it\u2019s not really that long and I\u2019m starting to get bored typing it, but let\u2019s go for a bit longer and see how long we go before I get too bored to write any more.  Did you know that as well as testing your smoke alarms monthly and changing your smoke alarm batteries at least once a year, you need to replace the whole unit every ten years?  That\u2019s right, smoke alarms only have a life of ten years.  This has been a public service announcement wrapped in a footnote.  Ok, that should be just about long enough to test what I\u2019m trying to test.\n']
IO - inputCore.InputManager.executeGesture (11:58:29.411):
Input: kb(desktop):control+downArrow
IO - speech.speak (11:58:29.588):
Speaking [u'foot note  7', u' ', u' A\n']

**Comment by Adriani90** [comment]
@Qchristensen, @derekriemer I can notice a significant performance improvement with NVDA 2019.1. Could you please test and report back if the performance is still bad for you? Thanks!

**Comment by Adriani90** [comment]
After asking for confirmation, We didn't get any updates from the initial author or any people that could reproduce this issue since more than 5 years. I am closing this issue as abandoned. Performance has evolved a lot in MS Word since then. If you are still having this issue with NVDA 2024.1, please comment and we can reopen.
