### ISSUE TITLE
The command to report the name of the worksheet in excel is not translated to Portuguese Brazil

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#6907]
I installed nvda 2017.1, and I identified that the command to report the name of the worksheet in excel is not translated into Portuguese Brazil.
To test:
Change the language of nvda to Portuguese Brazil.
Enter an excel sheet and press nvda + delete.
What is expected is that nvda read

planilha "Name of worksheet "

What happens is that the nvda reads:
sheet "worksheet name"

**Comment by josephsl** [comment]
CC @feerrenrut

**Comment by jcsteh** [comment]
Already fixed in #6866. Sorry this didn't make it into 2017.1; by the time we discovered it, we had already entered translation freeze.

**Comment by fernando-jose-silva** [comment]
Thank you.

Enviado do meu iPhone

> Em 22 de fev de 2017, às 22:41, James Teh <notifications@github.com> escreveu:
> 
> . Sorry this didn't make it into 2017.1; by the time we discovered it, we had already entered translation freeze.
> 
> —
