### ISSUE TITLE
Select-all Hotkey does not always select entire web document

### ISSUE THREAD

**Issue by sjtaylor82** [nvaccess/nvda#6909]
When using any application utilising Browse Mode, including Thunderbird, Internet Explorer V11.576, or Firefox 51.0.1 (32-bit) on Windows 10 64 Bit and NVDA 2017.1 (installed), the behaviour of the select-all keystroke is intermittent depending on the location of the caret. Issuing a Control-A keystroke at the top or bottom of a web-page will issue the correct behaviour and select the entire page. If the caret moves one or more lines, but less than approximately 550 characters, control-A will select only from the start of page to the cursor location. If the caret is at the end of the page and control-A is issued, then the entire page is selected which is expected behaviour.

**Comment by jcsteh** [comment]
Confirmed.

Probably a regression introduced by 62f42c61.
