### ISSUE TITLE
Support for K-Meleon web browser

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#691]
**Reported by janusz on 2010-06-06 09:40**
Gecko based virtual buffers are not able to work with K-Meleon1.5.4en-US. Not only gecko based virtual buffers, but also focus browsing is not awailable while triing to press TAB, SHIFT+TAB. NVDA errors are being produced and virtual buffers are not being processed. My motivation of triing to work with K-Meleon is to save memory and that this WEB browser is much more faster than Mozilla Firefox. Aspecially while typing WEB address or other information to The form fields, The NVDA responsiveness is much more faster. Would You be so kind and could You analyse, if many changes inside C language code would be necessarya to get information from K-meleon? The only one possible version for testing is according to my opinion latest stable release, because newest development release is not able to give necessary information to NVDA. K-Meleon latest stable release can be used with NVDA 2010.1, but only in focus mode, while pressing arrow keys, TAB, SHIFT+TAB, and while working with NVDA object navigation keys. Virtual buffers are also not ebing processed. But NVDA 2010.1 is not working with latest development release of K-Meleon too. Please, try to analyse my report.

**Comment by leonardder** [comment]
Last K-Meleon dates from end 2015. Due to browsers requiring active maintenance to be safe and stable, I think we can safely assume this project is obsolete and this issue can be closed as a won't fix
