### ISSUE TITLE
Tabbing does not work in frame in Firefox. 

### ISSUE THREAD

**Issue by maggie-mu** [nvaccess/nvda#6912]
We had a simple page application inside an iframe. On the page, we have a navigation menu and the content page. When tabbing from menu to content form, the tab will jump to outside iframe and nothing on the content form can be read out. The menu and content are both inside an iframe. 

We tried to force focus on the iframe and also the content everything when the content is changed inside SPA, but it did not solve this problem 

This does not happen in IE but only Firefox. 

Found a test on reader compatibility conducted by PowerMapper. https://www.powermapper.com/tests/screen-readers/labelling/iframe-blank-title/
Looks like the latest two release of NVDA does not support tabbing inside iframe. 

Any suggestions?

**Comment by jcsteh** [comment]
Please provide a test case, the exact steps you took, what you expected and
what happened instead.

The page you linked to is a valid issue, but it only refers to tabbing such
that the iframe itself has focus. Any focusable elements inside the iframe
should behave as expected.

**Comment by zahra21** [comment]
hi.
i confirm this and i cant use all web pages with frames with nvda.
in some of them nvda cant read the content for me specially after frames!
even i cant navigate to copy the content and peist it anywhere to read!
please resolve it.
thanks so much, i pray for you and request divine infinite mercy and blessings for you.

**Comment by ehollig** [comment]
@maggie-mu, could you please respond to https://github.com/nvaccess/nvda/issues/6912#issuecomment-282166634

**Comment by Adriani90** [comment]
I do not entirely understand this issue I think. But according to my tests in Firefox 66.0.2 and NVDA 2019.1, when tabbing in focus mode, NVDA says only "speak" and it does not read the description of the button in the frame and it ignores the frame title. When tabbing in browse mode, NVDA reports "speak grafic" also ignoring the description and the frame title.

In Chrome 73, when tabbing in focus mode through the frame, NVDA reports for example "Speak frame, Silence. Iframe, example hyperlink, link., Speak button".
In crhome NVDA also reports other frame titles like "speak example target frame, Speak (tab) frame, and so on. On this website there are different implementations of frame titles. Some are reported when tabbing in focus mode, some are not.
But in any case, frame titles are not reported when tabbing or when pressing quicknavigation keys in browse mode. It works only in focus mode.

@jcsteh your thoughts are very apreciated here regarding firefox ignoring the frame titles. Is this bad implementation? Or is there already a specific Firefox bug in place?

**Comment by Adriani90** [comment]
The page in the issue description is not a minimal test case, it's just a results overview of tests with iFrames. We don't have any minimal test case from the initial author. We didn't get any updates after request since many years, I am closing as abandoned. In case you have a minimal test case with clear actual and expected reporting, please comment on this issue and we can reopen.
