### ISSUE TITLE
NVDA can not get text from The object with The class name ATL:0052E590 in The BlockNote.Net application.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#692]
**Reported by janusz on 2010-06-06 15:18**
 NVDA latest development release can not get text while triing to access information from The BlockNote.Net edit window. This program, BlockNote.Net is unique, because user would even edit .eml files. NVDA can read whole text if user press ESC, but arrow keys are not working. Would somebody try to analyse The display hooking code incorporated to NVDA if also this program would be accessible? Here are information from The navgiator developers infos. Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states: STATE_FOCUSABLE, STATE_FOCUSED
Python object: <NVDAObjects.IAccessible.ContentGenericClient object at 0x02382510>
Python class mro: (<class 'NVDAObjects.IAccessible.ContentGenericClient'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.AutoSelectDetectionNVDAObject'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (231, 217, 538, 316)
value: u' V\u013een\xfd pane Kypr, Dovolte mi pros\xedm, aby jsem V\xe1s ve jm\xe9nu lidskosti, jemnosti a \n gavita\u010dn\xed vny po\u013e' (truncated)
appModule: <_default (appName blocknote, process ID 160) at address 233aef0>
TextInfo: <class 'displayModel.DisplayModelTextInfo'>
windowHandle: 6685494
windowClassName: u'ATL:0052E590'
windowControlID: 52300912
windowStyle: 1444937728
windowThreadID: 3612
windowText: u'\x00'
IAccessibleObject: <POINTER(IAccessible) ptr=0x193208 at 2487b70>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=6685494, objectID=-4, childID=0
IAccessible accRole: ROLE_SYSTEM_CLIENT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)

**Comment by leonardder** [comment]
Blocknote.net doesn't seem to have been updated in years. Furthermore, the website is talking about a new release being in development, not sure how old that text is though. I suggest a won't fix.
