### ISSUE TITLE
NVDA ignores aria-labelledby on a link, FF reads link, Chrome reads nothing. 

### ISSUE THREAD

**Issue by SpacePotatoBear** [nvaccess/nvda#6923]
I have an icon thats an href to another part of my website, I'm trying to provide a meaningful name to it for screen readers, code is below.

`<a class="ui item tooltip" aria-labelledby="Email" href="https://www.mywebsite.com/app/?q=email/index" data-content="Email"><i class="appIcon email"></i></a>`

On firefox, it will read href="thisstuffhere", on chrome is reads nothing. 

This works fine on other screen readers, so its an issue with NVDA not reading aria tags correctly.

**Comment by Adriani90** [comment]
Testing in NVDA alpha-17024,97a70f1b, I get following results:
1. In firefox 66.0.2 NVDA totally ignores the link
2. In Chrome it reports 
"link app q=email/index"
3. In IE it reports "link"
@jcsteh any idea why in Firefox the link is not recognized at all?

**Comment by DataTriny** [comment]
Hi there!

Considering the following code:

```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<style>
			.email {
				background-image: url("http://www.download82.com/images/produse/iconuri/email-forwarding-server.png");
				display: inline-block;
				height: 32px;
				width: 32px;
			}
		</style>
	</head>
	<body>
		<div id="Email">Email</div>
		<a class="ui item tooltip" aria-labelledby="Email" href="https://www.mywebsite.com/app/?q=email/index" data-content="Email"><i class="appIcon email"></i></a>
	</body>
</html>
```

It works both in Firefox 66.0.2 and Chrome 73. On Edge the link is not reported, but since it will soon use Chromium, it doesn't matter.

However, we are missing a bit of information here, so I had to improvize. It would be useful to have the code of the `Email` element as well as the CSS for the `<a>` and the `<i>`.

**Comment by Adriani90** [comment]
@DataTriny see #12024 for more details on that.
I am closing this as invalid.
