### ISSUE TITLE
Shortcut to report object under the mouse

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6928]
It is now possible to move the navigator object to the object under the mouse using shift+nvda+n. I'd like to suggest additional functionality to only report the object under the mouse, without moving the navigator object to it. Sometimes, it is desirable to just check the object under the mouse before left- or right clicking it, without moving the navigator object. I'd like to suggest ctrl+nvda+n for this.

**Comment by leonardder** [comment]
Hmm, coming back to this, I dont see a reason why checking the object under the mouse can't be done by moving the navigator object. Closing this, as I'm the author of the issue and don't see a reason to keep it open :)

**Comment by bhavyashah** [comment]
But wouldn't that mean that the user would compulsorily need to change
the position of the navigator object simply for checking what is under
the mouse, whereas it would be more desirable to have the navigator
object left unaffected while inspecting the content under the mouse
pointer?

On 12/16/17, Leonard de Ruijter <notifications@github.com> wrote:
> Closed #6928.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6928#event-1390765795


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750
