### ISSUE TITLE
Automatically start after log on Winddows

### ISSUE THREAD

**Issue by The-Dark-Man** [nvaccess/nvda#6929]
When I want to install NVDA out of the portable version, there is the window witch checkboxes. One of them is for starting NVDA after log in automatically. This check box is checked, but after installing NVDA, in general settings this check box is not checked. I must check it and it works. I think, this is an issue. I use the german version of NVDA 2017.1.

**Comment by josephsl** [comment]
Hi,
The checkbox title is "automatically start NVDA on the logon screen", thus this could confuse people.

@JCSTeh, anything we can do about this - rename the checkbox, add another checkbox just for after logon scenario, or something else?

Thanks.

**Comment by The-Dark-Man** [comment]
The problem is that NVDA doesn't start automatically at windows log on allthough I tick the check box for starting automatically after logon. The check box to activate it in general settings is called "Automatically start NVDA after I log on windows."

**Comment by josephsl** [comment]
Hi, it is called differently in the dialog where you install NVDA from a portable copy. I have asked Jamie for comments. Thanks.

**Comment by The-Dark-Man** [comment]
Just to clarify, I mean the start AFTER the log on screen.

**Comment by ehollig** [comment]
CC @Qchristensen @jcsteh for any input

**Comment by Adriani90** [comment]
@The-Dark-Man are you sure you are installing NVDA with administrator rights? You can only activate that in the installation process if you have admin rights I think.

**Comment by Adriani90** [comment]
I think this is related to administrator rights, since you cannot enable this option without Administrator rights. However, I didn't hear similar reports from users in several mailing lists during last years and we don't have an update from the initial author since years. Closing as abandoned. But please feel free to comment on this issue in case it still occurs and we can reopen. Thanks.
