### ISSUE TITLE
Build 15048: if audio ducking is set to "duck when outputting speech", audio always ducks

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#6933]
Hi,

A possible solution to #6684:

In build 15048, when audio ducking is set to "duck when outputting speech", audio always ducks.

STR:

1. If you haven't, install 15048 fast ring build.
2. Run a program such as Winamp, Movies and TV and what not and play something.
3. Perform step 2 with different audio ducking settings applied.

Expected: if audio ducking is set to "speech", other audio will duck as long as NVDA is speaking:
Actual: audio always ducks.
Reproducible: yes.

Setup:

* NVDA version: 2017.1, latest next build.
* OS: Windows 10 build 15048.

Thanks.

**Comment by josephsl** [comment]
Hi,

Never mind, misread the specs. Thanks.

**Comment by k-kolev1985** [comment]
Hello,

I can also reproduce this. If I set NVDA to lower the volume of other apps when NVDA outputs speech and audio, the volume level remains lowered constantly and not only when NVDA is speaking.

Test environment:
- Operating system: Windows 10 Pro Insider Preview (build 15048.0), 32-bit, in English with all locale settings set to "Bulgarian", running in a virtual machine in VMWare Player.
- NVDA version: next-13899,af44c1d4.
- Processor: Intel Core i5-2320 at 3.00GHz.
- RAM Memory: 3.00GB.
- Graphics: Palit GeForce GT 630, 1024MB dedicated memory + 3071MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC662 at Intel Cougar Point PCH - High Definition Audio Controller.
- VMware Player version: 12.5.2 build-4638234.

**Comment by jcsteh** [comment]
No, you're correct: Microsoft reverted the ducking change in build 15048. So, we now need to revert the mitigating change in NVDA.

CC @MichaelDCurran.

**Comment by derekriemer** [comment]
Do we really need anything in the whats new here? Was this in 17.1?
