### ISSUE TITLE
Nasty lag in IE 6 when screen is updated

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#695]
**Reported by jteh on 2010-06-11 08:30**
Str:
1. Open Internet Explorer 6 and visit http://www.nvda-project.org/
2. Move around the page with up and down arrows.
3. Result: Whenever the virtual cursor moves to a new object (which causes IE to scroll), there is severe lag.
4. Expected: There should be no lag.
- This is a regression introduced by display model (c90061b3e7e8c44aaefae4d29b5839e715ba8ddd).
- Specifically, we've tracked it down to ExtTextOutHelper.
- If NVDA is restarted, performance goes back to normal. This is because it is using a separate DC and then bit blitting back to the window DC, but we don't track this other DC unless we're running when it is created.
- This doesn't seem to affect IE 8.

**Comment by leonardder** [comment]
Five years after the last post in this issue, I think it is time for a won't fix anyway. Although IE6 might still be required for some users to use some time, it is very unlikely that this will ever be considered worthwhile to fix.

**Comment by derekriemer** [comment]
or a p4, I doubt it would get a PR though
