### ISSUE TITLE
Contracted braille input: do something to  alert the user they are editing a word, and mus use contractions properly

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6956]
As a user, I type hllo, go back, and add e to the middle with out ; letter sign.  heveryllo will appear if I do a translate command. unfortunately, we can't easily deal with this. I currently see hello on the braille display, which is confusing, because that is what I expect to see.  We should separate out the e from everything else, because otherwise it looks correct!

**Comment by jcsteh** [comment]
This should be done as part of PR #6449 (issue #2439).

**Comment by jcsteh** [comment]
Fixed in 1d6035bd; merged to next in 9b0534f.
