### ISSUE TITLE
Possible work around for the heveryllo annoyance

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6957]
I'm hoping this algorithm will work to get rid of the braille bug where a user types hllo, goes back and adds an e, and gets heveryllo, or types tg, goes back and adds r, and gets tgrather rather than together. Please comment critically.

1. If user cursors into the middle of a word w and types something on their display, grab all chars in w into buffer b.
2. place the cursor at the end of w, and either control+backspace, or backspace n times, where n = the length of w
3. send b through lib louis. Place the output in bTranslated.
4. Place the contents of bTranslated on the display, with r denoting the cursor location.
5. Place the braille symbol they typed after r.
6. When the user is done editing bTranslated, send bTranslated into the back translator. Place the data in b.
7. Type the characters of b into the document, with a space, NULL, or enter afterword, depending on if they pressed enter, space, or nothing.

**Comment by derekriemer** [comment]
By a null afterword, I mean put nothing after if they pressed 78

**Comment by jcsteh** [comment]
I've considered ideas like this, but this kind of thing is extremely fragile.

1. You suggest things like moving the cursor to the end of a word, but such things are actually extremely difficult to do well.
 - Whose definition of word are we using: ours or the application's? What if those two definitions differ?
 - What if the word contains "characters" which are actually more than one physical character in length; e.g. fields in Word?
 - What if the user is on a graphic or some other piece of metadata? That would mean braille input has to figure this out and avoid doing this in that case.
 - When we move to the end of the word, we have to wait for the cursor to move there. How do we do that without blocking the core more than we already do?
 - This stuff isn't synchronous. What if the cursor moves somehow in the middle of this juggling? What about collaborative editing?
 - What if backspace n times actually removes more or less characters than expected? For example, what if some text was selected or what if there was a field (as above) which covered multiple characters? We don't necessarily know these things.
2. There will be a significant impact concerning visual effects and state if we do something like this. Again, think collaborative editing to understand the full extent of this.
3. What if the user alt+tabs out in the middle of editing? We have no chance to submit the word, so the word is just lost. Catching alt+tab is not sufficient; the user could switch via some other means we don't catch.
4. This is going to be very, very slow.
5. The risk with all of the above is that you end up removing or altering more than you should. That is not acceptable. Of course, bugs happen, but the risk is too high if those bugs potentially destroy the user's work.
6. Honestly, this code is complicated enough as it is. I'm worried something like this would just make it impossible to work with.

I'm going to close this, as it's not something we can consider triaging at this point, but I'm happy to discuss this here if you have further thoughts. We can always reopen later if we come up with something interesting.
