### ISSUE TITLE
All settings in an individual profile deleted upon NVDA crash

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#6968]
I had a recent NVDA crash caused upon pressing NVDA+f1. Windows 10 needed to be restarted. NVDA configuration was reset. All settings had to be reset. In that crash, my Outlook profile appears to have been erased. The file exists but it's blank. No other profile has been affected. Unfortunately, I don't have the old logs to show crash cause. Several restarts have managed to override logs. I noticed the error too late for me to provide more details. However, I started noticing the profile issue when reading long emails.  I'm pasting a section of the current log that shows the current error.

INFO - config.ConfigManager._loadConfig (11:07:51):
Loading config: C:\Users\Pratik Patel\AppData\Roaming\nvda\profiles\Outlook.ini
ERROR - config.ProfileTrigger.enter (11:07:51):
Error entering trigger app:outlook, profile Outlook
Traceback (most recent call last):
  File "config\__init__.pyc", line 1019, in enter
  File "config\__init__.pyc", line 637, in _triggerProfileEnter
  File "config\__init__.pyc", line 454, in _getProfile
  File "config\__init__.pyc", line 400, in _loadConfig
  File "configobj.pyc", line 1219, in __init__
  File "configobj.pyc", line 1302, in _load
ParseError: Invalid line at line "1".

**Comment by jcsteh** [comment]
Same underlying issue as #3165.
