### ISSUE TITLE
performance issues in edge

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#6973]
hello all.

using latest insider build and anniversary update with latest updates.

on both machines edge performance is not as fast as for example in firefox and chrome. when navigating with arrows or quicknav keys, nvda speaks information with some delay.

**Comment by jcsteh** [comment]
We cannot access Edge in the same way we access Firefox and Chrome (virtual buffers). Some performance improvements are already coming. However, we are continuing to work with Microsoft to improve performance further. This will require changes in both Windows and NVDA.

CC @MichaelDCurran.

**Comment by michaelDCurran** [comment]
Edge performance has been partially addressed in PR #6994.

**Comment by Adriani90** [comment]
Closing as works for me, the performance is much better in old Edge and also in Edge Chromium 81. Closing as works for me.
