### ISSUE TITLE
Edge: NVDA reds each item of a radio group twice in browse mode

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#6980]
This occurs when going through items with f" and shift+f keys as well as r and shift+r keys. It does not happen with arrow keys. Tested with Windows 10 Insider 15058 and latest NVDA snapshot.

STR:
1. Open edge.
2. Press alt+d to go to addressbar.
3. visit the following page: https://ibma.github.io/Va11yS/ARIA/ARIA2_example3.html
4. Once the page loads, press f twice to go to the radio group and the first item.
5. Press f again to go to the next item.
6. Press R and shift R to repeat these steps.

**Comment by jcsteh** [comment]
CC @MichaelDCurran

**Comment by PratikP1** [comment]
Update: the URL I referenced in my steps has been updated to https://ibma.github.io/Va11yS/WCAG_ARIA/ARIA2_example3.html

**Comment by Adriani90** [comment]
This works as expected in Edge Chromium 81. Closing as works for me.
