### ISSUE TITLE
Arrow and other command keys from QWERTY keyboard on a Braille display driver do not work

### ISSUE THREAD

**Issue by tibabit** [nvaccess/nvda#6985]
Hi,
I am working a new braille display device and I am trying to use QWERTY keyboard with my braille display to access PC running NVDA. for this I use **injectRawKeyboardInput** from **keyboardHandler** class, however I am facing some issues getting it to work-

**What works:** alphabets, numbers, symbols, space, backspace delete, enter, tab, ctrl, shift, alt, function  

**What doesn't work:** **Arrow keys, PgUp, PgDown, Home, End**, etc.

I am running Linux on my braille display device. To send keys to NVDA I read scan codes from keyboard using Linux input_event structure and send the scan code to NVDA and on the NVDA side I call injectRawKeyboardInput in my braille display driver, to pass these scan codes to OS.

Please help me get these keys to work.
Please let me know if this issues needs more explanation/clarification.

Reference: #4576
@josephsl @jcsteh

**Comment by josephsl** [comment]
Hi, what’s the model of your display and manufacturer? CC @JCSTeh

**Comment by tibabit** [comment]
I am working on the display being developed by the company I work in, so it is not available in the market yet.

**Comment by josephsl** [comment]
Hi, I see. If so, please send documentation such as protocol API documentation and others to @JCSTeh so he can assist you. Thanks.

**Comment by jcsteh** [comment]
This works as expected for me. Tested as follows:

1. Open the NVDA Python console with NVDA+control+z.
2. Enter the following: `wx.CallLater(1000, lambda: keyboardHandler.injectRawKeyboardInput(True, 0x48, True))`
    * Note: 0x48 is the PC set 1 scan code for up arrow. 

After 1 second, the cursor moves to the previous line and NVDA reads the line, just as if up arrow had been pressed.

At a guess, I'd say the scan codes you're getting in Linux are from a different set. Windows expects scan codes from PC set 1.

**Comment by tibabit** [comment]
Thanks @jcsteh, I will check the scan codes.
