### ISSUE TITLE
Edge: role="document" breaks browse mode

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#6998]
STR:

1. Open [this test case](https://github.com/nvaccess/nvda/files/860236/roleDocument.html.txt) in Edge. (Rename to .html.)
2. Try to switch between focus and browse modes with NVDA+space.
    * Expected: NVDA should indicate that it is switching.
    * Actual: Nothing happens.

role="document" breaks detection of the EdgeHTMLRootContainer, I guess because it changes the UIA control type.

Practical impact: Can't read the [ARIA 1.1 spec](https://www.w3.org/TR/wai-aria-1.1/) in Edge.

CC @MichaelDCurran.

**Comment by josephsl** [comment]
Hi, got a COM error in 14393, cannot switch to focus mode in 15063. Thanks.
