### ISSUE TITLE
Edge: Blockquote not reported

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#6999]
STR:

1. Open 
[this test case](https://github.com/nvaccess/nvda/files/860241/blockquote.html.txt) in Edge. (Rename to .html.)
2.Read the two lines with the down arrow key.
    * Expected: NVDA should report that "Text inside quote" is a block quote.
    * Actual: The fact that there is a block quote is not reported.

CC @MichaelDCurran.

**Comment by michaelDCurran** [comment]
Technical notes:
IUIAutomationTextRange::getAttributeValue(UIA_StyleIdAttributeID) can return StyleId_Quote. However, Edge does not yet implement this.
Edge does expose a UIA element for the blockquote, but as UIA does not have a suitable controlType they have exposed  a controlType of text.
The string "blockquote" is however exposed via UIA's localizedControlType property. Obviosuly we do not want to depend on something that could change with locale, but I have asked the Edge team if that is in deed localized at all. If it is not, and it is just the tag name, then we could use that for now.

Interestingly they are also doing this with all headings now as well. So, as textRange-based style quotes are not yet supported, I'd think it would be better to push for getting tagName exposed on UIA elements in Edge either through a custom property of UIA's classname property, then we can support blockquotes through an element, and do the same for headings which will also massively improve performance when searching.

**Comment by Adriani90** [comment]
This works as expected in Edge Chromium 81, even in IE11. I close this issue since Edge Chromium 81 will be distributed to most users via Windows 10 20 H1 update.
