### ISSUE TITLE
Thank you NVDA developers for changing lives of thousands around the world

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#7000]
Hi,

On behalf of NVDA users around the world, I'd like to dedicate this issue as a thank you note to NV Access and other NVDA developers for improving lives of many. I and other users are grateful for all the hard work put into this free, open-source, and community-driven screen reader that is changing lives of thousands around the world.

Thanks.

**Comment by derekriemer** [comment]
Thanks for continued dedication to NVDA, and for ensuring people have access to technology made by blind people, for blind people. One of the strongest attributes of NVDA is the fact that it is written by blind people who use it, and thus is very efficient due to necessity. Keep up the great work!

**Comment by gdata1** [comment]
Hello. I can't log ' to gratitude. I'm from Russia and in my country a lot of people enjoy the nvda. Thanks to the developers for such a great and most importantly affordable project for us blind.

**Comment by Cleversn** [comment]
As one of the first NVDA translators, I'm really glad I have chosen such a successfull project to contribute. I was eager to start contributing to some project back in 2006, never thinking that it would go on for so long and become everything it is today. Back then, I just decided to remain as a translator, though I couldn't even use NVDA as my first screen reader, which only happened  around 2011. Today I know it was by far worth the effort.

Thank you all!

**Comment by Adriani90** [comment]
It is time to bring this issue to life again. I also thank you all developers and contributors to this project. When I started to contribute about three years ago, I had in mind just to report some issues which at that time drove me crazy. If I am looking back to that time I see a lot of things which happened until today and I hope this big and meaninful project will continue in the future. Thanks again for all your efforts and energy put in NVDA and its development.

**Comment by lukaszgo1** [comment]
Don't you think that GitHub issue tracker isn't a proper place for this?

**Comment by Adriani90** [comment]
In fact yes, however, I would let @josephsl to decide what he wants to do with it. Thanks.
