### ISSUE TITLE
Acrobat DC and new version 2017.1 commands not working.

### ISSUE THREAD

**Issue by SuzieDollar** [nvaccess/nvda#7002]
I'm using Acrobat DC and can no longer get NVDA commands to work. I thought upgrading to the new version of NVDA would help but they still are not working. Is anyone else having this problem and is it a compatibility issue or is there something I am not doing correctly?

**Comment by ruifontes** [comment]
Wich commands don't work?

Rui


-----Mensagem Original----- 
De: SuzieDollar
Data: 22 de março de 2017 14:45
Para: nvaccess/nvda
Cc: Subscribed
Assunto: [nvaccess/nvda] Acrobat DC and new version 2017.1 commands not 
working. (#7002)



I'm using Acrobat DC and can no longer get NVDA commands to work. I thought 
upgrading to the new version of NVDA would help but they still are not 
working. Is anyone else having this problem and is it a compatibility issue 
or is there something I am not doing correctly?

**Comment by SuzieDollar** [comment]
I can’t really get any of the commands to work. NVDA will read wherever my mouse is hovering or I have clicked my curser but it doesn’t seem to know anything about the structure. This pdf has fully passed the accessibility check.

**Comment by ruifontes** [comment]
Strange! Here I don't have any problem... I don't use the mouse...

Rui


-----Mensagem Original----- 
De: SuzieDollar
Data: 22 de março de 2017 15:01
Para: nvaccess/nvda
Cc: ruifontes ; Comment
Assunto: Re: [nvaccess/nvda] Acrobat DC and new version 2017.1 commands not 
working. (#7002)

I can’t really get any of the commands to work. NVDA will read wherever my 
mouse is hovering or I have clicked my curser but it doesn’t seem to know 
anything about the structure. This pdf has fully passed the accessibility 
check.

**Comment by feerrenrut** [comment]
@SuzieDollar Are you able to share the PDF (by attaching it to this issue)? This will give us an example document to try to reproduce the issue you are experiencing.

**Comment by ehollig** [comment]
@SuzieDollar, just a friendly reminder to respond to @feerrenrut's comment in https://github.com/nvaccess/nvda/issues/7002#issuecomment-289415335. This issue may be closed if we do not receive any additional information to troubleshoot the issue.

**Comment by ehollig** [comment]
Closing as invalid as we have not heard from the original poster in quite a bit of time. If this is still an issue, and @SuzieDollar can provide the information requested in https://github.com/nvaccess/nvda/issues/7002#issuecomment-289415335, we can reopen this issue.
