### ISSUE TITLE
PACmate 40 (PM-40) not detected

### ISSUE THREAD

**Issue by xjobex** [nvaccess/nvda#7007]
I installed the last version of NVDA on a PC with Windows 8 where there is connected a Braille display PACmate 40 (PM-40) via USB. Following the user guide, I installed the driver from http://www2.freedomscientific.com/downloads/focus-40-blue/focus-40-14-blue-downloads.asp , but I still can not see the display in the list of NVDA . I tried to reboot / re-install the driver, without success.
I can correctly see the Braille display in "Device Manager" of Windows.
Has anyone got a similar experience?

**Comment by ruifontes** [comment]
Hello!

In Braille devices list you can't find a entry named "Freedom Scientific 
Focus/PAC Mate series"?

If not, try the following:
1 - With the PAC Mate connected, remove it from Device Manager;
2 - Desconnect it from PC;
3 - Restart Windows;
4 - Re-install the drivers;
4 - Re-connect the PAC Mate;
5 - Windows should install the drivers;
6 - Restart Windows and go to NVDA and see if you can find in the Braille 
device list the entry "Freedom Scientific Focus/PAC Mate series". If yes, 
select it.

Rui


-----Mensagem Original----- 
De: Ego Brc
Data: 23 de março de 2017 14:13
Para: nvaccess/nvda
Cc: Subscribed
Assunto: [nvaccess/nvda] PACmate 40 (PM-40) not detected (#7007)



I installed the last version of NVDA on a PC with Windows 8 where there is 
connected a Braille display PACmate 40 (PM-40) via USB. Following the user 
guide, I installed the driver from 
http://www2.freedomscientific.com/downloads/focus-40-blue/focus-40-14-blue-downloads.asp 
, but I still can not see the display in the list of NVDA . I tried to 
reboot / re-install the driver, without success.
I can correctly see the Braille display in "Device Manager" of Windows.
Has anyone got a similar experience?

**Comment by feerrenrut** [comment]
@xjobex Please let us know if this didn't work. For now I'm going to close this issue.
