### ISSUE TITLE
Add-ons: update URL to https

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#7016]
Hi,

Part of #3208:

Despite updates to add-ons website, add-ons manager and user guide still points to http website. Thus update the URL to point to https instead.

The commit will be part of #3208 client branch. Thanks.

**Comment by jcsteh** [comment]
Please do this in a separate PR if possible. It's entirely possible we might have to delay add-on updates due to infrastructure, whereas we should land this https change ASAP. Also, if you're willing, would you mind checking for other http references related to NVDA or NV Access? The NV Access website, for example, is now https.

**Comment by Brian1Gaff** [comment]
On many of my bookmarks  when its specified as http, often it is re routed 
somehow to the https version, so is this not a convention now, somehow coded 
by the system of look ups?
 also a lot of padcacher software seems to run into this problem as well.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by jcsteh** [comment]
We do redirect http to https, but relying on this is unsafe, since a
man-in-the-middle attacker could intercept the traffic and serve something
else or redirect it somewhere else. For proper security, the URL provided
should be https.

**Comment by josephsl** [comment]
Hi, I’m working on it at the moment and will provide a PR soon. Thanks.

**Comment by derekriemer** [comment]
yo @josephsl Have you gotten around to finishing this yet?

**Comment by josephsl** [comment]
Ah yes, distracted by a few things. Thanks for reminding me to finish this ASAP.

**Comment by derekriemer** [comment]
ping

**Comment by josephsl** [comment]
Hi, looks like docs round 2 is in order. Thanks.

**Comment by Adriani90** [comment]
This is also actually covered in the PR #10130. @josephsl could you please respond to my question in the last comment of the PR so that I can finish the work on it? Thanks.

**Comment by Adriani90** [comment]
Oops it seems the buttons are now in inverse order. I closed it accidentally. 👎 sorry.

**Comment by Adriani90** [comment]
Fixed in the referenced PR. Closing as fixed.
