### ISSUE TITLE
FormatFactory: NVDA report different messages while "Move to next object" / "Move mouse to current navigator object"

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#7018]
FormatFactory: NVDA report different messages while "Move to next object" / "Move mouse to current navigator object"

Steps to reproduce:
1. Open FormatFactory.
2. Press NVDA+numpad4 to move to previous object, until you hear "close"
3. Press NVDA+numpad6 to move to next object, until "ShortcutsContainer".
4. Press NVDA+numpad2 to move to first contained object, and you would hear "video tab".
5. Press NVDA+numpad6 to move to next object, until "Utilities tab".
6. Press NVDA+numpadDivide to move mouse to current navigator object.
7. Press numpadDivide to click Left mouse button, then "Utilities tab" is selected and submenu is opened.
8. Press NVDA+numpadDivide to move mouse to current navigator object, and hear "Audio Joiner"
9. Press NVDA+numpad6 to move to next object.
speech: ShortcutsContainer
expected: Video Joiner
10. Press NVDA+numpadDivide to move mouse to current navigator object.
speech: Vvideo Joiner
11. Press numpadDivide to click Left mouse button, then Video Joiner dialog is opened.

**Comment by jcsteh** [comment]
Most likely, when you click the Utilities tab (step 7), it moves focus to the main window. You can confirm this by pressing NVDA+tab after clicking. This will also move the review object. When you then route the mouse in step 8, you're actually routing it to the centre of the main window, hence the result you get in step 8. The result you get in step 9 makes perfect sense if focus got moved after you first clicked.

Note that routing the mouse does not affect the review object.

**Comment by surfer0627** [comment]
Thank you for the reply`. Actually, the point is that if I just do step9 and don't do step10. I would skip the message "Video Joiner". In step9, is it possible that NVDA just report "Video joiner"? Or, you recommend I use "screen review" for this case.

**Comment by jcsteh** [comment]
Reporting "Video Joiner" for step 9 is incorrect because that is not the next object, since (assuming I'm correct) clicking in step 7 caused the focus to be moved. If you don't want the review object to move when the focus moves, turn off "Focus moves navigator object" (NVDA+7). However, you'll want to keep this on most of the time because otherwise, your review cursor will often be somewhere unexpected.

**Comment by surfer0627** [comment]
> Reporting "Video Joiner" for step 9 is incorrect because that is not the next object.


@jcsteh Thank you for the clarification.
Also, another question please help. In step10, press NVDA+numpadDivide to move mouse to current navigator object, what does the term ""current navigator object, mean?
Thanks.




Also,

**Comment by jcsteh** [comment]
Please see the NVDA User Guide for information about NVDA concepts. Alternatively, see our [Get Help](https://www.nvaccess.org/help/) page to learn about our training material and other technical support resources. Thanks.
