### ISSUE TITLE
Launching a link from an external source while focused on the Firefox window results in "unknown"

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#7025]
Test environment: NVDA version next-13950,c31e74f7; Firefox 52; Firefox nightly;
This issue has been around for several years though.

When staying focused on Firefox main window, launching a link from another source such as the NVDA menu or program such as Chicken Nugget, NVDA announces "unknown" as Window title with no content. This requires the user to alt-tab to another window and return. See log for instance.

* Expected results: Launching such a link should immediately bring up the site/page in question.
* Actual results: NVDA announces "unknown," forcing users to switch window and return.

STR:
1. Launch Firefox.
2. Press NVDA+n to bring up the NVDA menu.
3. Press "h" to go to the help menu.
4. Press u or n to bring up either the user guide or new changes document.

IO - speech.speak (12:53:45):
Speaking [LangChangeCommand ('en'), u'Techmeme - Mozilla Firefox']
IO - speech.speak (12:53:45):
Speaking [LangChangeCommand ('en'), u'Techmeme  document']
IO - speech.speak (12:53:45):
Speaking [LangChangeCommand ('en'), u'link', u'AWS launches Amazon Connect, a tool for data centers that uses its Lex speech recognition and AI; ']
IO - inputCore.InputManager.executeGesture (12:53:48):
Input: kb(laptop):NVDA+n
IO - speech.speak (12:53:48):
Speaking [LangChangeCommand ('en'), u'NVDA  menu']
IO - inputCore.InputManager.executeGesture (12:53:49):
Input: kb(laptop):h
IO - speech.speak (12:53:49):
Speaking [LangChangeCommand ('en'), u'User Guide  u']
IO - inputCore.InputManager.executeGesture (12:53:50):
Input: kb(laptop):n
IO - speech.speak (12:53:51):
Speaking [LangChangeCommand ('en'), u'Mozilla Firefox']
IO - speech.speak (12:53:51):
Speaking [LangChangeCommand ('en'), u'unknown']
IO - inputCore.InputManager.executeGesture (12:53:55):
Input: kb(laptop):alt+tab
IO - speech.speak (12:53:55):
Speaking [LangChangeCommand ('en'), u'Word  row 1  column 2']
IO - speech.speak (12:53:55):
Speaking [LangChangeCommand ('en'), u'Word']
IO - speech.speak (12:53:55):
Speaking [LangChangeCommand ('en'), u'unknown']
IO - inputCore.InputManager.executeGesture (12:53:55):
Input: kb(laptop):alt+tab
IO - speech.speak (12:53:56):
Speaking [LangChangeCommand ('en'), u"What's New in NVDA - Mozilla Firefox  row 1  column 2"]
IO - speech.speak (12:53:56):
Speaking [LangChangeCommand ('en'), u"What's New in NVDA - Mozilla Firefox"]
IO - speech.speak (12:53:57):
Speaking [LangChangeCommand ('en'), u"What's New in NVDA"]

**Comment by jcsteh** [comment]
This is a Firefox bug. Moreover, focus is actually broken, not just wrong according to NVDA. I confirmed this by pressing control+o after hearing "unknown". If Firefox were focused, this would bring up the Open dialog. In this case, it does nothing. Control+w also doesn't close the tab just opened.

For reference, a window with the class "firefoxMessageWindow" steals the focus.

This would affect sighted users as well, so this is not an accessibility specific issue. I suggest you file a bug with Mozilla.

**Comment by PratikP1** [comment]
I’ll file that bug. Thank you for clarifying.
