### ISSUE TITLE
Problems navigating characters with left and right arrows in a conversation window in Skype for Business

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7028]
When using Skype for Business 2015 (office 2013) 32bits on windows 7 64 bit, and nvda next 13949, when opening a new conversation you can not navigate the characters typed with the right and left arrows.

To reproduce:
Using the informed software verbs, open a new conversation, enter some phrase, and before sending the message try to review the characters typed with the left and right arrows, only one sound is heard.
This problem does not occur when using nvda next 13949 together with Skype for Business 2016 32 bit on windows 10 14393 64bits.
Follow the log.

IO - inputCore.InputManager.executeGesture (10:49:21):
Input: kb(laptop):leftArrow
ERROR - scriptHandler.executeScript (10:49:21):
error executing script: <bound method Dynamic_EditableTextWithoutAutoSelectDetectionUIA.script_caret_moveByCharacter of <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x0AD62C70>> with gesture u'esquerda'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 147, in script_caret_moveByCharacter
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 719, in speakTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 584, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 574, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 409, in _getTextWithFields_text
  File "NVDAObjects\UIA\__init__.pyc", line 213, in _getFormatFieldAtRange
  File "UIAUtils.pyc", line 173, in getValue
COMError: (-2147220988, 'Um nome de campo inv\xe1lido foi usado em uma cadeia de caracteres de consulta', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (10:49:23):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (10:49:23):
Developer info for navigator object:
name: u'Entrada de Chat. Conversa com Rodrigo Martins De Lima'
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x0AD62C70>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA'>, <class 'NVDAObjects.behaviors.EditableTextWithoutAutoSelectDetection'>, <class 'editableText.EditableTextWithoutAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: ''
location: (121, 415, 388, 41)
value: u'teste\r'
appModule: <'appModuleHandler' (appName u'lync', process ID 4620) at address 5a28c30>
appModule.productName: u'Microsoft Office 2013'
appModule.productVersion: u'15.0.4893.1000'
TextInfo: <class 'NVDAObjects.UIA.UIATextInfo'>
windowHandle: 525310
windowClassName: u'NetUIHWND'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 4624
windowText: u''
displayText: u''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x43d3838 at adce940>
UIA automationID: idAutomationChatInput
UIA frameworkID: 
UIA runtimeID: (42, 525310, 2, 388704536, 0)

UIA providerDescription: [pid:4620,hwnd:0x0 Main(parent link):Unidentified Provider (unmanaged:lync.exe)]
UIA className: NetUIRicherTextbox

**Comment by ehollig** [comment]
@fernando-jose-silva, is this still the case with the latest version of NVDA?

**Comment by fernando-jose-silva** [comment]
No, thanks, I do not have this problem any more.

 

De: Ethan Holliger [mailto:notifications@github.com] 
Enviada em: sábado, 2 de setembro de 2017 01:01
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [nvaccess/nvda] Problems navigating characters with left and right arrows in a conversation window in Skype for Business (#7028)

 

@fernando-jose-silva <https://github.com/fernando-jose-silva> , is this still the case with the latest version of NVDA?

**Comment by ehollig** [comment]
Thank you for the update @fernando-jose-silva. Closing because of https://github.com/nvaccess/nvda/issues/7028#issuecomment-326838173
