### ISSUE TITLE
Creators Update/Action Center: quick actions should still be treated as a list, not layout

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#7030]
Hi,

Possibly due to pull requests for WebRuntime announcement issue in Edge: in Creators Update/Action Center, quick actions list is not announced as a list.

STR:

1. With build 15063 running, press Windows+A.
2. Navigate to quick actions.

Expected: NvDA says "list".
Actual: no announcement, just items are spoken.
Cause: presentation type is set to layout when it might be best to leave it as content.

I bring this up due to inconsistent behavior across Windows 10 builds. Thanks.

**Comment by jcsteh** [comment]
It's true that there's a list in the hierarchy, but it's an unlabelled list, and the objects that get focus within it are buttons, which is non-standard at best. The list thus serves little semantic value. Microsoft have chosen to mark this as not being content, and in this case, I'm inclined to agree with them.
