### ISSUE TITLE
Excel border reporting is too verbose by default

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#7031]
From the [comment](https://github.com/nvaccess/nvda/issues/3044#issuecomment-289722547) by @leonardder:

Referring to the issue: "no information about the cell border is given in an Excel sheet, if the cell border is different from the adjacent cells. #3044"

> I believe the defaults for this are too verbose. I think both reporting of styles and colors should be initially off. Style and color information should only be reported whenever requested specifically, either by pressing nvda+f or enabling the particular options in the document formatting dialog.

**Comment by feerrenrut** [comment]
It might be worth considering why the reporting styles and colors is on by default. Is there a historical reason, can anyone comment on this?

**Comment by bramd** [comment]
I don't know why it's on by default, but I also think it's too verbose. Besides, it's now read before the cell contents, which is a suboptimal order in my oppinion.
