### ISSUE TITLE
[BUG REPORT] NVDA error log appeared once I type Korean characters and press space with Excel

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#7032]
Hello, I'm Hyongsop Kim in Korea.
I have a bug report about typing Korean characters and error log in Excel.
In excel, if I type English or numbers, there is no problem.
But if I type Korean and press space, NVDA error log sound is appeared every time.
I brought one example log and will paste below.
this log is generated starting from NVDA and until Excel error log is appeared.
Since as soon as starting NVDA, I ran excel and type Korean characters, the log is not long.
Please refer to this log and fix this issue.
If you want to test, open Excel 2016 and using Korean input, you can type dks and hit space.
You can hear error log sound.
Thank you.

```
INFO - __main__ (23:56:03):
Starting NVDA
INFO - core.main (23:56:04):
Config dir: C:\Users\Hyongsop Kim\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (23:56:04):
Loading config: C:\Users\Hyongsop Kim\AppData\Roaming\nvda\nvda.ini
INFO - core.main (23:56:04):
NVDA version next-13946,38d8ee77
INFO - core.main (23:56:04):
Using Windows version 10.0.14393 workstation
INFO - core.main (23:56:04):
Using Python version 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
INFO - core.main (23:56:04):
Using comtypes version 0.6.2
WARNING - stdout (23:56:04):
hooked waveOutOpen
WARNING - stdout (23:56:04):
hooked waveOutClose
INFO - synthDriverHandler.setSynth (23:56:04):
Loaded synthDriver sapi5
INFO - core.main (23:56:04):
Using wx version 3.0.2.0 msw (classic)
INFO - brailleInput.initialize (23:56:04):
Braille input initialized
INFO - braille.initialize (23:56:04):
Using liblouis version 3.0.0
INFO - brailleDisplayDrivers.hims.BrailleDisplayDriver.__init__ (23:56:07):
Braille Sense (4 scrolls mode) device found
INFO - braille.BrailleHandler.setDisplayByName (23:56:07):
Loaded braille display driver hims, current display has 32 cells.
WARNING - core.main (23:56:07):
Java Access Bridge not available
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (23:56:07):
UIAutomation: IUIAutomation3
INFO - core.main (23:56:07):
NVDA initialized
INFO - updateCheck.AutoUpdateChecker._started (23:56:07):
Performing automatic update check
ERROR - eventHandler.executeEvent (23:56:29):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x0852E110> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 900, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 812, in reportFocus
  File "speech.pyc", line 367, in speakObject
  File "NVDAObjects\__init__.pyc", line 967, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 255, in __init__
  File "comtypes\__init__.pyc", line 266, in __getattr__
COMError: (-2147220992, None, (None, None, None, 0, None))
```

**Comment by ehollig** [comment]
@khsbory, is this still an issue? The log you provided does not demonstrate inputting information into MS Excel.

**Comment by khsbory** [comment]
Hello, sorry about my too late reply.
The issue is still same in excel program with type Korean characters.
To demonstrate, refer to below suggestion.
1. Open excel.
Make sure your keyboard is set to Korean language keyboard.
2. Press the right key of the space to set native input.
3. Type dks and press tab key to go to next cell.
You will hear error sound.
If you need more information, pleae let me know.

thank you. 
 
김 형 섭	 / Hyongsop Kim
(주)엔비전스 / 웹접근성사업팀 팀장	

서울시 종로구 가회동 1-29 
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 70 4900 0895   F. +82 2 313 3645   M. +82 10 5359 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark

 
-----Original Message-----

**Comment by feerrenrut** [comment]
I can reproduce this with a recent next build and Excel 2013.

Debug level log:  [Excel2013-KoreanInput.txt](https://github.com/nvaccess/nvda/files/1430215/Excel2013-KoreanInput.txt)

**Comment by Adriani90** [comment]
I am testing with NVDA alpha-17047,56e208d2 and MS Excel 2016 / 365 as well as Excel 2010. I cannot reproduce this issue.

@khsbory, @feerrenrut are you still able to reproduce it?

**Comment by bhavyashah** [comment]
The latest comment, in 2019, suggests that this issue no longer exists, while this original ticket and a confirmatory comment came in 2017. Could you please provide a status update on this issue and check if it persists? @khsbory  @feerrenrut  @josephsl

**Comment by Adriani90** [comment]
We didn't get any further updates since many years upon request. I am closing this issue as abandoned. If you are still having this problem, please comment and we can reopen.
