### ISSUE TITLE
Windows 10 build 15063: Opening a new tab in Internet Explorer results in a freeze if the new tab is your news feed

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#7039]
Hi,

Observed with latest next snapshot and Windows 10 Creators Update (build 15063): if Internet Explorer is set to open your news feed when a new tab opens, it results in a freeze.

STR:

1. With Creators Update installed, open IE and browse for a while.
2. Open a new tab 9Control+T).

Expected: New tab opens.
Actual: in some cases, this results in a freeze.
Workaround: Tools/Internet Options, then Tabs page, then select 'blank page" when asked what to open for new tabs.

Thanks.

**Comment by PratikP1** [comment]
I’m not able to verify this, Joseph. I’m running the same configuration.

**Comment by feerrenrut** [comment]
There may be some particular content in the news feed that is causing this, @josephsl if you can still reproduce this, can you please save the page (Web page complete) and attach it to this issue?  This might help us to track down the cause of this.

**Comment by josephsl** [comment]
Hi, looks like one of the cumulative updates for build 15063 may have resolved it. I’ll reopen this if I encounter more issues. Thanks.

**Comment by fernando-jose-silva** [comment]
I am having a similar problem, my internet explorer has an error when opening it, preventing it from using it.
If I use internet explorer without nvda I can navigate normally.

I am using nvda master 13976 and windows 10 15063.13

My homepage is google.
Www.google.com.br

**Comment by josephsl** [comment]
Hi, the thing is we need to be able to attach the offending page but to no avail. Thanks.

**Comment by fernando-jose-silva** [comment]
Sorry if I do not understand, I'm having problems on Google's homepage,

Enviado do meu iPhone

> Em 8 de abr de 2017, às 16:07, Joseph Lee <notifications@github.com> escreveu:
> 
> Hi, the thing is we need to be able to attach the offending page but to no avail. Thanks.
>
