### ISSUE TITLE
browse mode: Some element info are not provided in this page

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#7040]
This case occurs in browsers Edge, Chrome, and Internet Explorer. Here is steps to reproduce:
1. Link to [this page](http://npac-ntch.org/zh/programs/calendar-201704#01).
2. Press h to move to next heading.
3. Press downArrow.
speech: 2017 年 4 月 
4. Press downArrow two times.
speech: > (no element info)
5. Press enter to turn to next month.
6. Press upArrow two times.
speech: 2017 年 5 月

note:
In FireFox, speech reports "clickable >".

**Comment by feerrenrut** [comment]
Could you elaborate on the expected result? Or perhaps I am misunderstanding and the problem is the inconsistency between Firefox and other browsers?

**Comment by surfer0627** [comment]
@feerrenrut
Sorry, I did not explain this case clearly.
In step4, speech report ">". I expected (e.g. > clickable). In this case, user press enter to move to next month. If there is no element info, user perhaps read text and skip it.

**Comment by feerrenrut** [comment]
Are you still able to reproduce this? In Chrome Version `57.0.2987.133` this element is reported as "clickable >".
I do get the described behaviour in IE and Edge however.

Looking at the HTML for this page, there are no specific attributes on the element to specify that they are clickable. There is however an event handler, which I expect we should be able to pick up. The event handler is added via JQuery to the `div`. 

The following file [testClickDiv.zip](https://github.com/nvaccess/nvda/files/915952/testClickDiv.zip) curiously reproduces the problem in IE but not Edge. Possibly it should not be considered a proper minimal case. 

Using the accessibility tree tool in Edge I don't notice any difference between the "clickable" `>` and the other `div` text.

**Comment by Adriani90** [comment]
In Crhome 73 and NVDA 2019.1 this issue is not reproducible. The element is reported as clickable. In Firefox 66.0.2 it is also reported accordingly.
In IE11 is still reproducible though.

**Comment by Adriani90** [comment]
IE support has completely ended in 2022 and the browser is automatically removed from machines that still have it after an Edge update in 2023. I don't expect further updates regarding accessibility to IE or to IE mode in Edge, so I am closing this issue as abandoned.
