### ISSUE TITLE
editing url is too verbose with firefox

### ISSUE THREAD

**Issue by mohdshara** [nvaccess/nvda#7042]
str:
1. in firefox address bar, alt plus d: type a URL like www.nvaccess.org/donate and press enter to open the page.
2. go to the address once again and press end to go to the end of the URL.
3. start backspacing. 
result: nvda echos back the first 2 characters deleted correctly but then starts to echo back the whole URL each time you backspace.
expected: NVDA should echo back only the deleted character.
setup: Firefox version 52.0.2
NVDA 2017.1
windows 10 build 15063, although I don't think the build matters.

**Comment by jcsteh** [comment]
When you press NVDA+tab after this starts occurring, do you hear "list item" or "edit" among the other information? I'm guessing you hear "list item".

This occurs because the auto complete suggestion gets focused, and every time you backspace, the suggestion changes, so the new suggestion is read. The fact that the auto complete item gets focus in this case is a bug in Firefox and will need to be fixed by Mozilla.

**Comment by zahra21** [comment]
hi.
i recommend that turn off autocomplete in mozilla firefox.
this problem started happening in firefox 50 and later versions.
for the solution:
in the address bar, type
about:config
press enter on it to activate and also check i accept the risk.
then, in the search bar type
browser.urlbar.autocomplete.enabled
then press enter on it to change it value to false.
hope thats help. God bless you.

**Comment by mohdshara** [comment]
Hi.


I actually prefer to live with it as this feature is very useful. I 
would only like to know if there's a filed bug already against firefox.


thanks,
Mohammed.

**Comment by Brian1Gaff** [comment]
Yes this I find a bit annoying as well. Rather than being in Firefox' 
advanced config it needs to be a toolbar or menu option in my view.
 Brian

**Comment by mohdshara** [comment]
@jcsteh I am still not that good searching the huge Bugzilla. Since you're now with the Mozilla team, do you know if there are issues that might address this? if not, would you open one or maybe I should? thanks.

**Comment by jcsteh** [comment]
It's been filed as [Mozilla bug 1331755](https://bugzilla.mozilla.org/show_bug.cgi?id=1331755).

**Comment by jcsteh** [comment]
I've fixed this for Firefox 64. The fix is available already in Firefox Nightly.
