### ISSUE TITLE
Automatically announce relevant structural information about a web page when loaded

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7050]
This is a request from one of our customers at @BabbageCom. It is already possible to read the page contents as soon as it has been fully loaded. Alternatively, it would be a handy feature if NVDA would be able to announce a message containing information about the amount of relevant elements on a page. For example, "Page has x headings, x landmarks, x links and x form fields"

This shouldn't be that difficult to implement and gives the user direct information about how to orient within a page.

**Comment by ruifontes** [comment]
I agree with that!

Rui


-----Mensagem Original----- 
De: Leonard de Ruijter
Data: 4 de abril de 2017 12:44
Para: nvaccess/nvda
Cc: Subscribed
Assunto: [nvaccess/nvda] Automatically announce relevant structural 
information about a web page when loaded (#7050)



This is a request from one of our customers at @BabbageCom. It is already 
possible to read the page contents as soon as it has been fully loaded. 
Alternatively, it would be a handy feature if NVDA would be able to announce 
a message containing information about the amount of relevant elements on a 
page. For example, "Page has x headings, x landmarks, x links and x form 
fields"

This shouldn't be that difficult to implement and gives the user direct 
information about how to orient within a page.

**Comment by jcsteh** [comment]
Duplicate of #737.

**Comment by josephsl** [comment]
Hi, possibly a duplicate? Thanks.
