### ISSUE TITLE
zmud support needed

### ISSUE THREAD

**Issue by tommyTsaiTou** [nvaccess/nvda#7051]
I use zmud software to play mud games, but nvda can not get the correct lines that show on the screen.
zmud version is 4.62

**Comment by jcsteh** [comment]
P4 because this affects relatively few users. Pull request welcome, though!

**Comment by Adriani90** [comment]
@tommyTsaiTou how is NVDA 2019.1 behaving with the last version of zmud?

**Comment by Adriani90** [comment]
We do not have any updates on this issues since years. I am closing this as abandoned. But don't hesitate to comment on this if you still have this issue and we can reopen. Thanks.
