### ISSUE TITLE
Won't read text on website in Chrome on Windows

### ISSUE THREAD

**Issue by wccrawford** [nvaccess/nvda#7053]
http://web0.bluetoad.com/html5_viewer/testing/screenreader.html

This is a sample that we can't get NVDA to read in Chrome on Windows.  This sample works in everything else we've thrown it at.  We have changed it around to try to figure out what's preventing it from reading the text of the page, but we were unable to determine the cause.

**Comment by jcsteh** [comment]
Can you please provide the exact steps you're taking, what you expected and
what happened instead? I just tested in both Chrome stable and Chrome
Canary and I can read the page just fine.

**Comment by wccrawford** [comment]
Thank you for the prompt response.

These are the steps we followed.

1. Turn on NVDA
2. Open that page in Chrome
3. Press Tab to go to the page.  

The first press goes to the page and reads nothing.  The second press goes to the first link and reads it.

The original device we used was a newer touch-enabled Window laptop.  We tried it on an older non-touch Windows laptop and did not have the problem.  We are installing NVDA on another touch device to see if it happens there.

**Comment by wccrawford** [comment]
It seems that this only happens on some devices after all.  

Dell XPS 13 9365, running a Pre-release version of Windows 10 Home.  Version: 1703.  OS Build: 15063.13

Sorry for making this sound bigger than it was.

**Comment by josephsl** [comment]
Hi, for devices that doesn’t exhibit the problem described, can you tell us which Windows version (or in case of Windows 10, build number) is installed? That way we can narrow the issue a bit further. Thanks.

**Comment by wccrawford** [comment]
Here are the 2 devices that were fine:

Laptop: HP/Compaq 6910 Windows 10 Pro version: 1607 (OS Build 14393.969)

Touch Tablet Device: Samsung Model: HLVJ93GBA01086W i5 64bit Windows 10 Pro  version 1607 (OS Build 14393.953)

**Comment by ehollig** [comment]
@wccrawford, is this still an issue? When I open the URL that was given, I get a 404 error. This issue may be closed if we do not receive additional information on the issue or if the issue no longer exists.

**Comment by wccrawford** [comment]
Sorry about that!  I think we accidentally removed the sample there.

Thank you!

The sample was a simplified version of our actual problem, and it appears the complex version now works correctly, after updating NVDA.

I would close this ticket as fixed.  If the problem (or a similar one) reappears, I will open a new ticket.

Thanks again!
