### ISSUE TITLE
nvda plays error sound before starts or stops reading in "say all" mode (observed in w10 built 15063.13

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#7054]
Hi,

when i installed a creators update to my pc, I've found some bugs. because I'm not technical expert I cannot identify what caused it, thus I will try to describe them.

first error sound has been played when nvda loaded itself to a system.

many sounds are played during reading session (see attached logs)

sounds are played when reading session begins and ends.

tested with firefox 52.0.2 and notepad.

system specs:
- w10 64-bit (15063.13)
- latest next snapshot where addons have been disabled.

hope, this helps.

[nvda logs.zip](https://github.com/nvaccess/nvda/files/901123/nvda.logs.zip)

Thanks for your good work.

regards, Jožef

**Comment by josephsl** [comment]
CC @JCSTeh

**Comment by jcsteh** [comment]
It looks like you have a say all configuration profile, but that profile (and perhaps other profiles) is set to a synthesiser which no longer exists and/or is broken. Similarly, it seems you have configured NVDA to use BRLTTY, but it isn't running. If you fix these issues in affected profiles and save your configuration, these errors will go away.
