### ISSUE TITLE
Add custom input gestures to configuration profiles

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7058]
I'm not sure whether this has been suggested before, but I was unable to find a similar ticket so far.
I'd like to suggest the possibility to add an input gesture to enable or toggle a configuration profiles. I see two possibilities for implementation:

1. Add an extra option to each profile which adds the profile to a list of profiles which can be cycled through using an input gesture (NVDA+shift+p) by default
2. Programmatically add an unbound script to a profile which toggles between enable and disable. Enabling profile a should automatically disable profile b

**Comment by jcsteh** [comment]
Duplicate of #4209.
