### ISSUE TITLE
NVDA is reading javascript

### ISSUE THREAD

**Issue by robertregnier** [nvaccess/nvda#7059]
In IE10 with browser mode IE10 and Document Mode Standards, nvda reads out javascript.  If the document mode is changed to IE5 quirks mode then the problem goes away.  It should not be reading javascript in standards mode.  

In TestA html (attached), nvda will display the 'kkkkkk... in the speech viewer and read it out when moving over with the pointer.  Tabbing through it will not show the javascript.  

In TestB html (attached) the html is more complex and tabbing through the page will show hidden javascript even though it is not visible.

[TestA.zip](https://github.com/nvaccess/nvda/files/906269/TestA.zip)
[TestB.zip](https://github.com/nvaccess/nvda/files/906270/TestB.zip)

**Comment by feerrenrut** [comment]
Thanks for raising this, unfortunately I haven't been able to reproduce this with Internet Explorer Version `11.953`  regardless of the compatibility mode I select. 

I am using NVDA Version: `next-13972,c956204f` on Windows 10 `1607, build 14393.969`

Can you let me know what version of NVDA and of Windows you are using?

**Comment by robertregnier** [comment]
Thanks for having a look.  I upgraded to IE11 and was still able to reproduce.  I've attached a small video to demonstrate.  This is with IE 11.0.9600.16428 and Windows 7 SP1 and NVDA version 2017.1
[NVDA_with_IE11_and_javascript.zip](https://github.com/nvaccess/nvda/files/913741/NVDA_with_IE11_and_javascript.zip)

**Comment by feerrenrut** [comment]
I can't really tell how you are controlling NVDA in the SWF. Could you give a set of steps to reproduce? Please include details of any settings you modify for internet explorer, and how you control NVDA.

Also unable to reproduce with Windows 7 SP1 Build 7601
With IE Version: `8.0.7601.17514` in several of the document modes (accessed via the F12 developer tools)

**Comment by feerrenrut** [comment]
I was now able to reproduce this with NVDA Version: `next-13972,c956204f` on Windows 10 1607, build `14393.969` and Internet Explorer Version `11.953`

To reproduce with the TestA.html:
1. Ensure that NVDA has mouse tracking enabled.
2. Open the TestA.html in IE.
3. Move the mouse to just above the edit field.

I have not been able to reproduce this using the keyboard.

**Comment by feerrenrut** [comment]
Given this requires mouse tracking (which is less frequently used) and IE ( which is more or less considered legacy by Microsoft) I'll give this issue a priority 3.

**Comment by robertregnier** [comment]
Thanks for looking into this.  If you try with TestB you'll find that the problem is reproducible with the keyboard as well which should change the priority of the issue.  With regards to NVDA, the only out of the box changes made is to unselect 'clickable', that's it.

**Comment by Adriani90** [comment]
I am closing this in favor of #10733 which contains the template filed and some comments on when exactly this started to occur.

**Comment by feerrenrut** [comment]
Since issue #10733 is either resolved (on the external site), or a misunderstanding, and this issue includes sample code I'll re-open it.

**Comment by Adriani90** [comment]
Support for IE has ended completely in 2022 and it is automatically removed from machines that still have it after an Edge update in February 2023. I don't expect any further accessibility updates to IE or to IE mode in Edge. Closing as abandoned.
