### ISSUE TITLE
Split panes are regarded to as content

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7063]
As @feerrenrut requested, here is some more technical background for #7049.

IBM SPSS Statistics is software for statistical analysis, written in JAVA. In its data view, it is very verbose on every press of an arrow key, reporting the following before the actual data: "Split pane, table, table, split pane, table, table" 

As this is quite obnoxious, I went investigating how to make this application less verbose. In that process, I noticed that split panes do have presentation type content instead of layout. I reported this on [the development list](http://nabble.nvda-project.org/Split-panes-have-presentation-type-content-tt41789.html), as I wasn't sure yet whether this is intentional. It doesn't seem so according to @jcsteh, so that's why I created #7049.

Please note that this improves verbosity in SPSS' data view, but NVDA will still announce table four times before it will tell the contents of the actual cell selected. So, this is not a complete fix for the SPSS verbosity complaint.

**Comment by feerrenrut** [comment]
Thanks for the extra info @leonardder. I have set this as a P2 since there is a PR already created, I'll complete the review on this shortly.
