### ISSUE TITLE
problem in Windows live mail's address book

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#707]
**Reported by oaron on 2010-06-15 08:28**
In WinLiveMail's address book, NVDA speaks the contact's information before the contact's name.f

**Comment by leonardder** [comment]
I suggest closing this, similar to https://github.com/nvaccess/nvda/issues/508#issuecomment-306947785

> There's no point in us working on additional support for something which is now obsolete.

**Comment by derekriemer** [comment]
closing as wontfix
