### ISSUE TITLE
Improve implementation of NVDAObject.labeledBy

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/nvda#7080]
NVDAObjects have a property called labeledBy, which should do the following according to its getter docstring:

> Retreaves the object that this object is labeled by (example: the static text label beside an edit field).

It is currently only implemented for IAccessible objects,but that implementation suffers from a bug

```
>>> nav.labeledBy
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 902, in _get_labeledBy
TypeError: 'NoneType' object is not iterable
```

This is quite easy to fix and I'd be happy to create a pr for this. However, I noticed that labeledBy is just implemented nowhere, so when you set the labeledBy property for an unlabeled object, it won't get the proper label automagically. Was labeledBy ever planned to be implemented further and what would such an implementation look like?

**Comment by dkager** [comment]
Also, 'Retreaves' --> 'Retrieves'

**Comment by leonardder** [comment]
May be labeledBy should be renamed to labelledBy while at it

**Comment by feerrenrut** [comment]
@michaelDCurran or @jcsteh Care to comment on the plans around `labeledBy`?

**Comment by Adriani90** [comment]
Closing as abandoned since we didn't get any updates or further information on the implementation in the wild from @LeonarddeR or other developers in cc.

If things changed and this should still be improved, please comment and we can reopen.
