### ISSUE TITLE
Touch screen inaccurate in some programs (eg Chrome) when using DPI greater than 100%

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#7083]
Using Chrome, when the DPI (Change the size of text, apps and other items) is set to greater than 100%, touching items on the screen is inaccurate.  NVDA may read other items or the main window information.

Swiping between items works.  Selecting items on the touch screen works normally without NVDA running.

**Comment by feerrenrut** [comment]
My guess is that the number of users impacted by this is enough to set the priority to 3. There is also a work around.

**Comment by leonardder** [comment]
cc @dkager

**Comment by Adriani90** [comment]
#8076 could be related
