### ISSUE TITLE
Snapshots: Remove TMP Files before Building

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#7085]
After upgrading to the latest Next snapshot (13994,744a2d39), I've noticed that there are three separate files with a prefix of "TMP" in my installation directory. Whilst the largest of these is only 2.51 MB, is there any way that these could be removed before the snapshot is built? I assume that it's safe to remove them from my own install and that these are not needed?

**Comment by jcsteh** [comment]
These files aren't part of the snapshot. They are files that NVDA renamed during install because some app hadn't released them yet and thus Windows wouldn't allow them to be deleted. They are flagged for deletion on next reboot, so they will be deleted when you next reboot.
