### ISSUE TITLE
SAP and Netviewer

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7091]
I don't really know how many of you are working in SAP-based applications, but since many visually impaired people don't get their jobs or cannot use their full potential because of SAP issues (at least in Germany), I would like to point out some of them:

•	In SAP Applications which run through Netviewer in Internet Explorer or Mozilla Firefox, NVDA often doesn’t report selected items in combo boxes etc. Jaws reports the selected item even though the combo box is collapsed. For example HR Services
•	The process database ADONIS is not accessible at all. Buttons are not labeled and processes are not recognized as text by the screen reader. Are there any discussions with the developer of ADONIS Database?
•	Some JAWS distributors have developped scripts for SAP GUI (the main SAP operation application) and sell such scripts for huge amounts although they should actually be implemented into the screen reader itself. Is there any cooperation between NV Access or NVDA developers and SAP regarding SAP GUI? I wonder if there is sort of an ad on for NVDA with respect to this topic?

Best regards and many thanks for this huge work
Adriani

**Comment by bhavyashah** [comment]
@Adriani90 Since it has been 3 years since filing this ticket, I think it might be useful to provide a status update as to whether there has been any changes in the accessibility of the latest versions of these software using recent NVDA releases.

**Comment by Adriani90** [comment]
The only issue that remains now is the SAP Gui. Since it is not a browser based application, it is hard to convince them to adapt it. I do not have the negociation power to do this unfortunately.

I managed to convince SAP however to update their netviewer so that combo boxes are working well now.
And to my surprise, my feedback to the Adonis tool has been taken into account. Given its huge complexity, the developers really managed to bring out an update which makes it very accessible now. Really nice work from Adonis on that.

@Qchristensen were there any further updates with regard to communications between NV Access and SAP about SAP Gui accessibility?

**Comment by Qchristensen** [comment]
No there hasn't - have you had any updates on where SAP is at currently @Adriani90 ?

**Comment by Adriani90** [comment]
Not really, I know that they want to change their environment completely to SAP Hannah which is a cloud based environment. This should be acomplished by 2025 as far as I know.

**Comment by Qchristensen** [comment]
Do you know if SAP Hannah is more accessible?

**Comment by Adriani90** [comment]
Sorry, there was a typo from my side, the environment is called SAP HANA. :-)

The underlying plattform for HANA is SAP netviewer AS ABAP version for HANA, currently version 7.4. SAP Netviewer is actually kind of comparable to Sharepoint. It is a plattform which is the basis for all the SAP apps. HANA is the cloud environment where the apps are stored and where they comunicate with each other. SAP Netviewer is browser based, just like Sharepoint, and it is very accessible. The accessibility can be enabled in the settings of SAP Netviewer, basically you just have to open a SAP app in the browser and youcan access the settings from there. The settings are global and are then applied for every SAP app on the Netviewer plattform.

In the end the accessibility of apps is however determined by the app developer. SAP apps can be very customized. However, the biggest apps like SAP CRM or SAP HR services are already very accessible.

**Comment by Adriani90** [comment]
I am closing this issue as works for me, in general the apps in SAP have evolved a lot since I reported this issue. Most things work well now also given the recent improvements in NVDA.
