### ISSUE TITLE
return a 1 element array from gesture.normalizedIdentifiers rather than a string, for consistancy.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#7098]
hi.
In an addon to bring a tdsr speech server to NVDA, I want to disable scripts for the caret in terminals sometimes.
I noticed that gesture.normalizedIdentifiers returns a list of identifiers, except for if there are only 1 identifiers. Is this necessary? For consistency, an item should always return only one type when possible, because a string is also an iterable, and returning a string might cause code expecting a list to just puke and crash.

example working code.
```
	def getScript(self, gesture):
		identifyer = ""
		for i in list(gesture.normalizedIdentifiers):
			if i in self._gestureMap:
				identifyer = i
				print i
				break
		if self.TDSROn and "script_caret_" in identifyer:
			return self.script_caret_on.__get__(self, self.__class__)
		return super(TDSRConsoleNuker, self).getScript(gesture)
```

example code that pukes currently, but should work in a system that guarantees type sanity.

```
	def getScript(self, gesture):
		identifyer = ""
		for i in gesture.normalizedIdentifiers:
			if i in self._gestureMap:
				identifyer = i
				print i
				break
		if self.TDSROn and "script_caret_" in identifyer:
			return self.script_caret_on.__get__(self, self.__class__)
		return super(TDSRConsoleNuker, self).getScript(gesture)
```

**Comment by derekriemer** [comment]
use `

**Comment by jcsteh** [comment]
Far as I know, normalizedIdentifiers already always returns a list. Please provide steps to repro a situation where it returns a string instead.

**Comment by derekriemer** [comment]
Okay. I updated the code. The point being the same, but the old code didn't work, end of story. this is still an ugly hack though.

	def getScript(self, gesture):
		identifyer = ""
		for i in list(gesture.normalizedIdentifiers):
			if i in self._gestureMap:
				identifyer = i
				break
		#someone   is going to kill me after this hack ...
		if self.TDSROn and "script_caret_" in self._gestureMap.get(identifyer,lambda:1).__name__:
			return self.script_caret_on.__get__(self, self.__class__)
		return super(TDSRConsoleNuker, self).getScript(gesture)

**Comment by jcsteh** [comment]
That doesn't answer my question. How are you producing a gesture which returns a string from InputGesture.normalizedIdentifiers instead of a list?

**Comment by jcsteh** [comment]
The code for normalizedIdentifiers is exactly this:

```
return [normalizeGestureIdentifier(identifier) for identifier in self.identifiers]
```

So there's no way this can return a string. We don't override this anywhere either.

**Comment by derekriemer** [comment]
sorry, thhis might have been related to another bug in my code. I should have looked at that first (I saw x in output from my code, when I was printing all identifiers, and it looked like it was iterating over a string).
