### ISSUE TITLE
Enhance NVDAObjects.Window.Window.redraw to allow redrawing child objects

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7101]
I've seen several cases where NVDA"s display model lost its way entirely. One of the possibilities to fix this is redrawing certain object windows as well as their children. However, currently it is quite difficult to do this, as the redraw function only redraws the object window itself. Using a for loop to redraw all the descendants isn't ideal and doesn't always work.

I propose adding an optional argument to the redraw function which, if True, redraws the particular object's window as well as its child windows.

Technical background, this is as simple as putting an additional flag in the winUser.RedrawWindow function, namely RDW_ALLCHILDREN=0x0080

**Comment by jcsteh** [comment]
If it's really that simple and you are reasonably confident that it indeed
helps some use case, happy to take a PR. It makes sense to me. CC
@MichaelDCurran.

**Comment by leonardder** [comment]
It turns out that redrawing the children causes duplicate information in the display model. I have observed this before, but redrawing the window including children makes this more prevalent, so it will acttually cause more issues than it solves. Closing as invalid for now.
