### ISSUE TITLE
When the -c option is used when starting NVDA user configuration can not be saved

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#7113]
Steps to reproduce:

- Open a command prompt and cd to the nvda.exe directory.
- start nvda with `nvda.exe -c "C:\myTemp"
- open the nvda menu and select "save configuration"

An error is shown "Could not save configuration - probably read only file system".

Regression caused by atomic rename/write fix. Config path is unicode without `-c`, but when `-c` is passed, the config path is ANSI. fileUtils assumes path is always Unicode.

**Comment by leonardder** [comment]
I guess this can be fixed by changing -c from str to unicode in the argument parser. That should be done anyway. This wasn't possible in the days of optparse I belief.

**Comment by jcsteh** [comment]
Oh. Does argparse know how to retrieve command line options in Unicode? I
thought that was a limitation of Python 2 (because sys.argv is ANSI).

**Comment by leonardder** [comment]
Hmmmm, that's something I should test. But probably not, then.

N.B. Sent on behalf of @BabbageCom
