### ISSUE TITLE
Allow different cursor shapes for braille tethered to focus or review.

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#7122]
To avoid confusion between the two, notably in editable text.
The cursor shape can already be set, see #5198.

**Comment by derekriemer** [comment]
I think this is a useful PR. I have fallen into this trap several times and as seen in #7117 I actually mistook it for a bug in next. This shows how easy it is for the user to be deceived.

**Comment by derekriemer** [comment]
fixes #7117

**Comment by dkager** [comment]
Note that there is no patch (PR) yet, though that shouldn't be too hard.

**Comment by feerrenrut** [comment]
Can you please suggest a UX for this? For instance:
- do you have cursor shapes in mind for each of these modes? 
- would you suggest that the cursor shapes be configurable by the user for each of these modes?

**Comment by dkager** [comment]
> - do you have cursor shapes in mind for each of these modes?

Yes.

> - would you suggest that the cursor shapes be configurable by the user for each of these modes?

Yes.

NVDA already has the ability to configure the cursor shape. I suggest changing this from one combobox "Cursor shape" into two comboboxes:
1. Cursor shape for focus
2. Cursor shape for review

These can both take all values of `braille.CURSOR_SHAPES`. I suggest dots 7&8 as default for focus and dot 8 as default for review (very loosely based on JAWS). If a user wants the current behavior, i.e. the same shape for both modes, then she can configure the two comboboxes to be the same.

One thing I have not yet thought about is if browse mode should have its own cursor shape option. I'm tempted to say no.

**Comment by dkager** [comment]
In conclusion, do we think this is worth a patch so we can see how it goes?

**Comment by feerrenrut** [comment]
Thanks for clarifying that for us. We are happy to take a pull request to implement this feature.

**Comment by dkager** [comment]
Almost done. I have one question though. Do we call it "Cursor shape for focus/review" or "Focus/Review cursor shape"? I went for the first because the latter makes it sound like NVDA has a "focus cursor", which it doesn't explicitly have. But it is a bit shorter.

**Comment by leonardder** [comment]
I'd go for "Cursor shape for focus and "Cursor shape for review cursor".

**Comment by jcsteh** [comment]
I think you can shorten the review one to just "Cursor shape for review";
i.e. "review" instead of "review cursor".
