### ISSUE TITLE
Add support for universal app version of Skype

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#7126]
Hi,

For a while now, Microsoft has been working on a universal app version of Skype (previously Skype Preview). Since Windows 10 Version 1607 (build 14393), Skype is a preinstalled app. Although there are numerous user interface changes and the way one would use Skype is different, the new Skype universal app is stable, especially after various updates were put in place such as keyboard shortcuts.

As of now, NVDA users who'd like to use Skype have to use Windows 10 App Essentials add-on for enhanced experience. I propose that support for universal app version of Skype be a part of NVDA itself.

Things to consider:

* The typing indicator isn't announced automatically.
* In Redstone 3, My People, a feature to centralize top contacts for communication purposes, is introduced. There could be changes to Skype as a result of this feature.
* As Skype is a universal app, changes may happen from time to time, and developers should be made aware of possible regressions so workarounds can be published.

Thanks.

**Comment by josephsl** [comment]
Hi,

A chat with @JCSTeh revealed the following:

* Regular expressions for messages: as messages can change, it might be best to guard this from future problems until a much better solution (see below) is found.
* Message handling: Oddly enough, one can parse message history items by selectively cherry-picking labels from their children. Unfortunately, in some cases, message sender name isn't shown as a child label.
* Focus announcement and braille displays: As noted on WinTenApps issue 25, when gainFocus event is invoked on message history items, the shortened form of the item label disappears from the display after a short while.
* Name change handling: because message history items fire name change events (and other objects may fire this), it would be helpful to suppress this while a user is going through contacts and conversations.

Thanks.

**Comment by josephsl** [comment]
Hi,

Looks like Skype 14 is here to stay - looks sort of like Skype 8 for desktop but packaged as a UWP (or powered by UWP).

Thanks.

**Comment by josephsl** [comment]
Hi,

As of now, I'm seriously thinking about closing the pull request for this one, as the new Skype interface is being deployed around the world. I hope someone can continue this work in the future.

Thanks.

**Comment by Adriani90** [comment]
@josephsl are there still any cases in Skype UWP where your Windows 10 App Essentials is needed? Or is the support provided by NVDA natively now?

**Comment by ehollig** [comment]
Just a friendly reminder for @josephsl to reply to @Adriani90 comment in https://github.com/nvaccess/nvda/issues/7126#issuecomment-485556004
Can this issue be closed?

**Comment by josephsl** [comment]
Hi, I advise closing this one, as Skype was improved by Microsoft in recent releases. Thanks for reminding me about this.
