### ISSUE TITLE
NVDA and Windows 10 Open With dialog

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#7127]
Hello.

I have noticed lately where NVDA crashes sometimes on the launch of the Open With dialog in Windows 10. The dialog sometimes doesn't get focused, and when that happens, NVDA crashes. I will send a log if so desired.

**Comment by feerrenrut** [comment]
@fisher729 Thanks for raising the issue. Can you please attach a log, please ensure you have "debug" level logging set. If you are unsure how to do this please read ["Log files and crash dumps" on the wiki](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps).

Please could you also let us know the version and build of windows you are using _(E.G. Windows 10 Version 1607 Build 14393.1066)_

**Comment by fisher729** [comment]
Hi.

I am using
Windows 10 1703 (15063.413) with NVDA Version: master-14172,0fb961db.
I have noticed this with NVDA 2017.2.

This behaviour changes based on the situation. Sometimes, NVDA
crashes. Other times, it says 'pane' and I have to press Tab to
interact with it. It's interesting, because if I remove an openwith
module that comes with NVDA, this issue goes away. Here is the log.

INFO - __main__ (10:53:33.655):
Starting NVDA
DEBUG - __main__ (10:53:33.655):
Debug level logging enabled
DEBUG - core.main (10:53:34.000):
Core starting
INFO - core.main (10:53:34.003):
Config dir: C:\Users\Andre Fisher\AppData\Roaming\nvda
DEBUG - core.main (10:53:34.003):
loading config
INFO - config.ConfigManager._loadConfig (10:53:34.005):
Loading config: C:\Users\Andre Fisher\AppData\Roaming\nvda\nvda.ini
DEBUG - config.profileUpgrader.upgrade (10:53:34.013):
Current config schema version: 2, latest: 1
INFO - config.ConfigManager._loadConfig (10:53:34.046):
Config loaded (after upgrade, and in the state it will be used by NVDA):
{u'schemaVersion': u'2', u'upgrade': {}, u'update': {u'autoCheck':
u'True'}, u'general': {u'language': u'en', u'saveConfigurationOnExit':
u'False', u'askToExit': u'True', u'playStartAndExitSounds': u'True',
u'loggingLevel': u'INFO', u'showWelcomeDialogAtStartup': u'False'},
u'speech': {u'synth': u'espeak', u'autoLanguageSwitching': u'False',
u'outputDevice': u'Microsoft Sound Mapper', u'symbolLevel': u'100',
u'espeak': {u'voice': u'en-us', u'variant': u'none', u'rate': u'85',
u'pitch': u'40', u'inflection': u'90', u'volume': u'100',
u'capPitchChange': u'60'}, u'sapi5': {u'voice':
u'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech\\Voices\\Tokens\\VW
Bridget', u'volume': u'100', u'rate': u'60', u'capPitchChange':
u'50'}, u'eloquence': {u'voice': u'65536', u'variant': u'1', u'rate':
u'64', u'pitch': u'65', u'inflection': u'30', u'volume': u'92',
u'capPitchChange': u'20'}, u'vocalizer_expressive2': {u'voice':
u'Samantha', u'variant': u'embedded-compact', u'volume': u'80',
u'rate': u'80'}}, u'braille': {u'noBraille': {u'port': u''}},
u'keyboard': {u'useCapsLockAsNVDAModifierKey': u'True',
u'keyboardLayout': u'laptop', u'speakTypedWords': u'True',
u'allowSkimReadingInSayAll': u'True', u'speakTypedCharacters':
u'True'}, u'mouse': {u'enableMouseTracking': u'False',
u'reportObjectRoleOnMouseEnter': u'True'}, u'presentation':
{u'reportHelpBalloons': u'False'}, u'virtualBuffers':
{u'autoSayAllOnPageLoad': u'False'}, u'documentFormatting':
{u'reportComments': u'False', u'reportRevisions': u'False',
u'reportSpellingErrors': u'False', u'reportPage': u'False',
u'reportTables': u'False', u'reportTableHeaders': u'False',
u'reportTableCellCoords': u'False', u'reportLists': u'False',
u'reportBlockQuotes': u'False', u'reportLandmarks': u'False',
u'reportFrames': u'False', u'reportClickable': u'False',
u'autoLanguageSwitching': u'False'}, u'wintenApps':
{u'updateCheckTime': u'1500306572', u'updateCheckTimeInterval': u'7'}}
DEBUG - core.main (10:53:34.138):
setting language to en
INFO - core.main (10:53:34.141):
NVDA version master-14172,0fb961db
INFO - core.main (10:53:34.141):
Using Windows version 10.0.15063 workstation
INFO - core.main (10:53:34.142):
Using Python version 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016,
20:42:59) [MSC v.1500 32 bit (Intel)]
INFO - core.main (10:53:34.142):
Using comtypes version 0.6.2
DEBUG - core.main (10:53:34.157):
Initializing add-ons system
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.171):
Listing add-ons from C:\Users\Andre Fisher\AppData\Roaming\nvda\addons
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.173):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\clipContentsDesigner
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.176):
Found add-on clipContentsDesigner
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.176):
Loading add-on from C:\Users\Andre Fisher\AppData\Roaming\nvda\addons\cloudOCR
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.178):
Found add-on cloudOCR
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.178):
Loading add-on from C:\Users\Andre Fisher\AppData\Roaming\nvda\addons\eloquence
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.181):
Found add-on eloquence
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.183):
Loading add-on from C:\Users\Andre Fisher\AppData\Roaming\nvda\addons\emoticons
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.184):
Found add-on emoticons
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.186):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\noBeepsSpeechMode
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.187):
Found add-on noBeepsSpeechMode
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.188):
Loading add-on from C:\Users\Andre Fisher\AppData\Roaming\nvda\addons\objPad
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.190):
Found add-on objPad
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.191):
Loading add-on from C:\Users\Andre Fisher\AppData\Roaming\nvda\addons\ocr
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.194):
Found add-on ocr
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.194):
Loading add-on from C:\Users\Andre Fisher\AppData\Roaming\nvda\addons\pcKbBrl
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.197):
Found add-on pcKbBrl
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.197):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\placeMarkers
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.200):
Found add-on placeMarkers
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.200):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\reportSymbols
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.203):
Found add-on reportSymbols
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.203):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\resourceMonitor
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.206):
Found add-on resourceMonitor
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.207):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\reviewCursorCopier
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.210):
Found add-on reviewCursorCopier
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.210):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\speechCopierAndHistory
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.213):
Found add-on speechCopierAndHistory
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.213):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\speechPlayerInEspeak
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.214):
Found add-on speechPlayerInEspeak
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.216):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\virtualRevision
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.219):
Found add-on virtualRevision
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.219):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\vocalizer-expressive2-voice-eng-Malcolm-PremiumHigh
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.221):
Found add-on vocalizer-expressive2-voice-eng-Malcolm-PremiumHigh
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.223):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\vocalizer-expressive2-voice-English
Compact Compilation
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.224):
Found add-on vocalizer-expressive2-voice-English Compact Compilation
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.224):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\vocalizer-expressive2-voice-enu-Ava-PremiumHigh
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.227):
Found add-on vocalizer-expressive2-voice-enu-Ava-PremiumHigh
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.229):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\vocalizer-expressive2-voice-enu-Samantha-PremiumHigh
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.230):
Found add-on vocalizer-expressive2-voice-enu-Samantha-PremiumHigh
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.232):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\vocalizer-expressive2-voice-enu-Susan-PremiumHigh
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.233):
Found add-on vocalizer-expressive2-voice-enu-Susan-PremiumHigh
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.234):
Loading add-on from C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\vocalizer_expressive2_driver
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.236):
Found add-on vocalizer_expressive2_driver
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.237):
Loading add-on from C:\Users\Andre Fisher\AppData\Roaming\nvda\addons\wintenApps
DEBUG - addonHandler._getAvailableAddonsFromPath (10:53:34.243):
Found add-on wintenApps
DEBUG - core.main (10:53:34.628):
Initializing appModule Handler
DEBUG - addonHandler.Addon.addToPackagePath (10:53:34.631):
Addon wintenApps added to appModules package path
DEBUG - core.main (10:53:34.631):
Initializing NVDAHelper
DEBUG - core.main (10:53:34.714):
Speech Dictionary processing
DEBUG - speechDictHandler.SpeechDict.load (10:53:34.714):
Loading speech dictionary 'C:\Users\Andre
Fisher\AppData\Roaming\nvda\speechDicts\default.dic'...
DEBUG - speechDictHandler.SpeechDict.load (10:53:34.717):
1 loaded records.
DEBUG - speechDictHandler.SpeechDict.load (10:53:34.717):
Loading speech dictionary 'builtin.dic'...
DEBUG - speechDictHandler.SpeechDict.load (10:53:34.720):
3 loaded records.
DEBUG - core.main (10:53:34.720):
Initializing speech
DEBUG - addonHandler.Addon.addToPackagePath (10:53:34.721):
Addon eloquence added to synthDrivers package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:34.723):
Addon speechPlayerInEspeak added to synthDrivers package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:34.724):
Addon vocalizer_expressive2_driver added to synthDrivers package path
INFO - synthDrivers.espeak.SynthDriver.__init__ (10:53:34.855):
Using eSpeak NG version 1.49.1 dev
DEBUG - speechDictHandler.SpeechDict.load (10:53:35.020):
Loading speech dictionary 'C:\Users\Andre
Fisher\AppData\Roaming\nvda\speechDicts\espeak-english-us.dic'...
DEBUG - speechDictHandler.SpeechDict.load (10:53:35.020):
file 'C:\Users\Andre
Fisher\AppData\Roaming\nvda\speechDicts\espeak-english-us.dic' not
found.
INFO - synthDriverHandler.setSynth (10:53:35.023):
Loaded synthDriver espeak
INFO - core.main (10:53:35.023):
Using wx version 3.0.2.0 msw (classic)
DEBUG - core.main (10:53:35.028):
Initializing braille input
INFO - brailleInput.initialize (10:53:35.028):
Braille input initialized
DEBUG - core.main (10:53:35.029):
Initializing braille
INFO - braille.initialize (10:53:35.032):
Using liblouis version 3.2.0
INFO - braille.BrailleHandler.setDisplayByName (10:53:35.033):
Loaded braille display driver noBraille, current display has 0 cells.
DEBUG - core.main (10:53:35.035):
Initializing displayModel
DEBUG - core.main (10:53:35.035):
Initializing GUI
DEBUG - core.main (10:53:35.098):
initializing Java Access Bridge support
WARNING - core.main (10:53:35.098):
Java Access Bridge not available
DEBUG - core.main (10:53:35.101):
Initializing winConsole support
DEBUG - core.main (10:53:35.101):
Initializing UIA support
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (10:53:35.108):
UIAutomation: IUIAutomation3
DEBUG - core.main (10:53:35.421):
Initializing IAccessible support
DEBUG - core.main (10:53:35.421):
Initializing input core
DEBUGWARNING - inputCore.InputManager.loadLocaleGestureMap (10:53:35.423):
No locale gesture map for language en
DEBUG - core.main (10:53:35.424):
Initializing keyboard handler
DEBUG - core.main (10:53:35.424):
initializing mouse handler
DEBUG - core.main (10:53:35.464):
Initializing touchHandler
DEBUGWARNING - touchHandler.initialize (10:53:35.466):
No touch devices found
DEBUG - core.main (10:53:35.467):
Initializing global plugin handler
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.467):
Addon clipContentsDesigner added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.467):
Addon cloudOCR added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.469):
Addon emoticons added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.469):
Addon noBeepsSpeechMode added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.470):
Addon objPad added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.470):
Addon ocr added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.470):
Addon pcKbBrl added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.470):
Addon placeMarkers added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.471):
Addon reportSymbols added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.471):
Addon resourceMonitor added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.473):
Addon reviewCursorCopier added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.473):
Addon speechCopierAndHistory added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.473):
Addon virtualRevision added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.474):
Addon vocalizer_expressive2_driver added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (10:53:35.474):
Addon wintenApps added to globalPlugins package path
DEBUG - external:synthDrivers.vocalizer_expressive2._vocalizer.preInitialize
(10:53:35.627):
installed voice add-ons:
[u'vocalizer-expressive2-voice-eng-Malcolm-PremiumHigh',
u'vocalizer-expressive2-voice-English Compact Compilation',
u'vocalizer-expressive2-voice-enu-Ava-PremiumHigh',
u'vocalizer-expressive2-voice-enu-Samantha-PremiumHigh',
u'vocalizer-expressive2-voice-enu-Susan-PremiumHigh']
DEBUG - speechDictHandler.SpeechDict.load (10:53:35.890):
Loading speech dictionary 'C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\emoticons\globalPlugins\emoticons\emoticons.dic'...
DEBUG - speechDictHandler.SpeechDict.load (10:53:35.891):
file 'C:\Users\Andre
Fisher\AppData\Roaming\nvda\addons\emoticons\globalPlugins\emoticons\emoticons.dic'
not found.
DEBUG - core.main (10:53:36.101):
Initializing core pump
DEBUG - core.main (10:53:36.102):
Initializing watchdog
DEBUG - core.main (10:53:36.104):
initializing updateCheck
INFO - core.main (10:53:36.105):
NVDA initialized
DEBUG - core.main (10:53:36.105):
entering wx application main loop
IO - speech.speak (10:53:36.145):
Speaking [u'FolderView  list']
IO - speech.speak (10:53:36.359):
Speaking [u'Working Folder  not selected  24 of 30']
IO - inputCore.InputManager.executeGesture (10:53:40.757):
Input: kb(laptop):windows+r
IO - speech.speak (10:53:41.236):
Speaking [u'Run  dialog  Type the name of a program, folder, document,
or Internet resource, and Windows will open it for you.']
IO - speech.speak (10:53:41.323):
Speaking [u'Open:  combo box  collapsed']
IO - speech.speak (10:53:41.326):
Speaking [u'edit  Alt+o']
IO - speech.speak (10:53:41.328):
Speaking [u'selected winver']
IO - inputCore.InputManager.executeGesture (10:53:42.336):
Input: kb(laptop):shift+d
IO - speech._speakSpellingGen (10:53:42.359):
Speaking character u'D'
DEBUG - queueHandler.registerGeneratorObject (10:53:42.361):
Adding generator 1
IO - speech.speak (10:53:42.375):
Speaking [u'selection removed']
DEBUG - queueHandler.pumpAll (10:53:42.392):
generator 1 finished
IO - inputCore.InputManager.executeGesture (10:53:42.648):
Input: kb(laptop):o
IO - speech._speakSpellingGen (10:53:42.664):
Speaking character u'o'
DEBUG - queueHandler.registerGeneratorObject (10:53:42.665):
Adding generator 2
DEBUG - queueHandler.pumpAll (10:53:42.690):
generator 2 finished
IO - inputCore.InputManager.executeGesture (10:53:43.528):
Input: kb(laptop):c
IO - speech._speakSpellingGen (10:53:43.566):
Speaking character u'c'
DEBUG - queueHandler.registerGeneratorObject (10:53:43.568):
Adding generator 3
DEBUG - queueHandler.pumpAll (10:53:43.591):
generator 3 finished
IO - inputCore.InputManager.executeGesture (10:53:44.726):
Input: kb(laptop):u
IO - speech._speakSpellingGen (10:53:44.750):
Speaking character u'u'
DEBUG - queueHandler.registerGeneratorObject (10:53:44.752):
Adding generator 4
DEBUG - queueHandler.pumpAll (10:53:44.756):
generator 4 finished
IO - inputCore.InputManager.executeGesture (10:53:45.321):
Input: kb(laptop):downArrow
DEBUG - editableText.EditableText._hasCaretMoved (10:53:45.368):
Caret move detected using bookmarks. Elapsed: 0 ms
IO - speech.speak (10:53:45.377):
Speaking [u'docue:']
IO - inputCore.InputManager.executeGesture (10:53:46.943):
Input: kb(laptop):enter
DEBUG - editableText.EditableText._hasCaretMoved (10:53:47.030):
Focus event. Elapsed: 0 ms
IO - speech.speak (10:53:47.063):
Speaking [u'text  unavailable']
IO - speech.speak (10:53:47.538):
Speaking [u'English (Jamaica) - US']
IO - speech.speak (10:53:47.596):
Speaking [u'Desktop  list']
IO - speech.speak (10:53:47.608):
Speaking [u'Working Folder  not selected  24 of 30']
IO - speech.speak (10:53:48.013):
Speaking [u'pane']
IO - inputCore.InputManager.executeGesture (10:53:49.936):
Input: kb(laptop):tab
IO - speech.speak (10:53:50.217):
Speaking [u'You\u2019ll need a new app to open this docue  window
You\u2019ll need a new app to open this docue']
IO - speech.speak (10:53:50.286):
Speaking [u'list']
IO - speech.speak (10:53:50.292):
Speaking [u'list']
IO - speech.speak (10:53:50.302):
Speaking [u'Look for an app in the Store']
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.uiaDebugLogging
(10:53:50.305):
W10: UIA object name: Look for an app in the Store, event:
elementSelected, app module: <'openwith' (appName u'openwith', process
ID 4504) at address 51886b0>, automation Id: StoreTile, class name:
AppListTileElement
IO - inputCore.InputManager.executeGesture (10:53:53.536):
Input: kb(laptop):tab
IO - speech.speak (10:53:53.605):
Speaking [u'OK  button']
IO - inputCore.InputManager.executeGesture (10:53:55.536):
Input: kb(laptop):escape
IO - speech.speak (10:53:55.684):
Speaking [u'Desktop  list']
IO - speech.speak (10:53:55.693):
Speaking [u'Working Folder  not selected  24 of 30']
IO - inputCore.InputManager.executeGesture (10:53:58.525):
Input: kb(laptop):NVDA+n
DEBUG - appModuleHandler.cleanup (10:53:58.647):
application openwith closed
IO - speech.speak (10:53:58.667):
Speaking [u'NVDA  menu']
IO - inputCore.InputManager.executeGesture (10:53:58.970):
Input: kb(laptop):downArrow
IO - speech.speak (10:53:58.997):
Speaking [u'Preferences  subMenu  p']
IO - inputCore.InputManager.executeGesture (10:53:59.147):
Input: kb(laptop):downArrow
IO - speech.speak (10:53:59.171):
Speaking [u'Tools  subMenu  t']
IO - inputCore.InputManager.executeGesture (10:53:59.450):
Input: kb(laptop):rightArrow
IO - speech.speak (10:53:59.493):
Speaking [u'View log  v']
IO - inputCore.InputManager.executeGesture (10:54:00.052):
Input: kb(laptop):enter

**Comment by jcsteh** [comment]
I'm most concerned about cases where you say NVDA crashes. It'd be good if you can provide a log file and a crash dump for this situation.

Also, I notice you have Win 10 App Essentials installed. It'd be good if you can try with this disabled, only because it has some UIA event debugging code and I want to eliminate that as a possible trigger.

**Comment by fisher729** [comment]
Well, it appears that I can't reproduce this at the moment. It appears
that this behaviour was fixed somehow. Still, what is reported when
you open the dialog changes sometimes. I think the issue can be closed
though.
