### ISSUE TITLE
Occasional delay in speech response in NVDA snapshots when navigating through links.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#713]
**Reported by H.D. on 2010-06-18 02:51**
Using latest version of NVDA snapshot (as of June 17, 2010), when navigating through links (i.e. moving up and down with arrow), I occasionally experienced a slight delay before NVDA provided the speech feedback (i.e. announcing the link. I mostly noted it when doing search in both IE8 and Firefox 3.6. and navigating through search results. Attached is a log file for the said snapshot.

**Comment by leonardder** [comment]
It has been 7 years ago valuable information has been provided in this ticket. I can't reproduce this myself and we haven't gotten any other reports about this, it seems. I'd suggest a close as works for me.

**Comment by derekriemer** [comment]
the original user never responded to @jcsteh question, the log is no longer available, and if this were serious, others would have reported. Closing as for being aged.

**Comment by derekriemer** [comment]
@jcsteh @michaelDCurran how about an antique label? Would you guys have an issue with creating one?

**Comment by jcsteh** [comment]
I don't think we need such a label; it doesn't really serve any purpose, as it's not something we need to search for or gather stats about. Labelling as worksforme.
