### ISSUE TITLE
NVDA should support checkbox, radio button and combobox on some  Google Chrome extensions windows

### ISSUE THREAD

**Issue by dreinn** [nvaccess/nvda#7134]
Most extensions of Google Chrome have their configuration page.
In these pages there are combobox, radio buttons or check boxes that NVDA is not able to recognize, showing them as clickable text, with the review cursor.
Users is not able to understand if an element is active or not.

I can show it with an example, if you want to use the Adguard AdBlocker - extension, the settings window is not accessible because you don't know the state of the element.
A little part of the source code of the config page
```
<div class="settings-page-table">
54
<div class="s-page-table-row cf">
55
<div class="sp-table-row-label" i18n="options_allow_acceptable_ads"></div>
56
<input type="checkbox" class="sp-table-row-input" id="allowAcceptableAds"/>
57
</div>
58
<div class="s-page-table-row cf page-stats-switch-block">
59
<div class="sp-table-row-label" i18n="options_show_blocked_ads_count"></div>
60
<input type="checkbox" class="sp-table-row-input" id="showPageStatisticCheckbox"/>
61
```

**Comment by Adriani90** [comment]
@dreinn I think this is not entirely related to NVDA. How is the behavior now in NVDA 2019.1? Are there improvements visible? This issue depends also on how the developer of the chrome extension implemented the controls. You will never get an 100% accessibility just from NVDA's side.
If you have a specific issue and you think that it is related to NVDA, please don't hesitate to create new issues for specific extensions so we can reproduce the issues reliably.

**Comment by Adriani90** [comment]
We do not have any updates from the initial author since more than 2 years. Closing as abandoned.
