### ISSUE TITLE
On this page, arrowing up gets stuck on pause in edge.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#7145]
In edge, if on a youtube video, pressing the up arrow after navigating to the pause button gets you stuck. Other backward strokes like shict+b, control+home work.
1. visit https://www.youtube.com/watch?v=vbttZVTSJRU or another video. This one is quiet at the beginning so it's a good test.
2. down arrow to the video. You'll notice NVDA seems to think it's an embedded object. This is weird and I'm not sure why it happens.
3. press down to go past play (pause).
4. Now, press up arrow and notice how NVDA stops on "pause" and won't go up arrow again.
5. Press shift+b. Notice how skip navigation is focused.
6. now, repeat the go to the video step.
7. press control+home and note that focus lands at the top.

Expected: up arrow goes before pause.

**Comment by gdata1** [comment]
Hello. I have observed this problem and the site www.google.com if you press the up arrow on the nvda alerts remain in place. but the above there is button google apps

**Comment by ehollig** [comment]
@derekriemer, is this still an issue? I am not able to replicate using Edge 41 and the latest NVDA Next

**Comment by derekriemer** [comment]
nope.
