### ISSUE TITLE
Crash dumps wiki page, mention caching symbol paths

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#7149]
Hi:
Is it necessary to add symbol path like c:\symbols in the wiki page for crash dump analysis? If that's not there, from what I understand everything will be very slow.

**Comment by jcsteh** [comment]
Contrary to [Microsoft's documentation](https://msdn.microsoft.com/en-us/library/windows/hardware/ff558829(v=vs.85).aspx), it seems that if you include `srv*` alone to fetch symbols from the default symbol server, it also caches symbols locally. I don't think it does this if you do `srv*server`, which is what that page recommends. Particularly in the absence of certainty, I think explicit is better than implicit, so I've updated the article to add `cache*` at the start of the path, which chooses the default local cache (usually `C:\programdata\dbg\sym`).
