### ISSUE TITLE
More cursor manager selection bugs #1.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#7157]
1. paste this into the python console.
api.copyToClip(u"d\n"*30)
2. Paste the result into instantbird (Do it to yourself, not someone else).
3. press enter.
4. Press control+end, and then shift up arrow about 5 times (Any number should work).
5. press shift+home and shift+end. Nothing happens.
Expected: if shift+end is pressed, line n-k is unselected.
Actual: nothing.

**Comment by jcsteh** [comment]
Simplified STR:

1. Open this URL in Firefox: `data:text/html,ab`
2. In browse mode, press control+home.
3. Press right arrow to move to "b".
4. Press shift+end.
    * Expected: "b selected"
    * Actual: Nothing.

In short, shift+end does not work if the caret is at the last character of the line.

Not a regression: also fails in 2016.3.

**Comment by leonardder** [comment]
@jcsteh: Will this pr also fix selection on lines with only one character?
I belief the issue I reported in #7162 is related to this.

**Comment by jcsteh** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [9 May 2017, 8:29 pm AEST](https://github.com/nvaccess/nvda/issues/7157#issuecomment-300124650 "2017-05-09T10:29:01Z - Replied by Github Reply Comments"):
> @jcsteh: Will this pr also fix selection on lines with only one character?

Steps to reproduce please? I don't quite understand what you're asking.

**Comment by leonardder** [comment]
> Steps to reproduce please? 

1. go to google.com
2. Type "a" in the edit field
3. In browse mode, do home and try to select "a", which is the only character on the line

This didn't work before, but it seems that #7159 fixes this as well, as I can't reproduce this in latest next.

**Comment by jcsteh** [comment]
Were you trying to select with shift+end? If so, yes, I expected #7159
would fix this. It's just a specific case of shift+end on the last
character; when there's only one character, it's also the last character.

**Comment by bhavyashah** [comment]
Does this ticket encompass editing and selection bugs specifically for
a certain web browser, i.e. Firefox, Chrome, or Edge, or is broader in
scope as in general text editing, cursoring and selection related
issues fall under its ambit? I have been encountering various related
problems in Google Chrome while working in edit fields which I would
like to report.

On 5/10/17, James Teh <notifications@github.com> wrote:
> Were you trying to select with shift+end? If so, yes, I expected #7159
> would fix this. It's just a specific case of shift+end on the last
> character; when there's only one character, it's also the last character.
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/7157#issuecomment-300383834


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by jcsteh** [comment]
This is related to browse mode only.

**Comment by leonardder** [comment]
> Were you trying to select with shift+end? 

Yes, that is what I did. Glad this has been taken care of.
