### ISSUE TITLE
NVDA reads buttons and links even if a parent has aria-hidden="true"

### ISSUE THREAD

**Issue by julmot** [nvaccess/nvda#7164]
Inside an application I'm embedding google maps with custom buttons on top of it. The root container has `aria-hidden="true"` as it's not optimized for screen readers:

![2017-05-10 16_17_24-postauto schweiz ag - firefox developer edition](https://cloud.githubusercontent.com/assets/8310677/25903314/5a9b2e44-359c-11e7-8d66-17ce30679ef2.png)

There are many nested levels, so containing buttons/links aren't located directly inside the container.

When navigating from top to bottom using arrow keys the map and their childrens are ignored correctly. However, when I navigate using TAB, links and buttons inside this container are still read out.

Is this a bug or is there something to workaround the situation?

**Comment by jcsteh** [comment]
aria-hidden only hides elements in terms of accessibility exposure. It does not affect focus in any way. So, they will still appear in the tab order. If you want them removed from the tab order, you need to do this yourself using tabindex="-1".
