### ISSUE TITLE
focus things in the firtual buffer in browse mode, even it the thing can't gain real focus

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#7172]
### Steps to reproduce:

1. open https://docs.python.org/2/library/itertools.html
2. move to the first list.
3. down arrow into the list.
4. object nav out of that list, and dive into various lists, to read the first thild. Once you've read a first child a few times, focus one, and press nvda+shift+bksp in latptop mode, which is nvda+shift+numpad-.
5. Observe that you have to press that key multiple times. I would argue that the virtual buffer focus should be set there after one press for ease of use.

**Comment by jcsteh** [comment]
There's no such thing as "focus" as far as browse mode is concerned. There's just a cursor. The command notes that pressing it once sets the system focus and setting it twice sets the caret. In this case, the first press focuses the document (which is already focused). The second press moves the browse mode caret. You'll see exactly the same behaviour if you move the review cursor in a simple text field.
