### ISSUE TITLE
NVDA2017.1 not focusing on text area in Word2010 on file opening

### ISSUE THREAD

**Issue by NedAT** [nvaccess/nvda#7175]
Hi good people,

a friend of mine is trying to move to NVDA and is having this trouble with MS Office2010 apps.
I searched thoroughly and couldn't find solution because the similar issues relate to protected Word documents.
The checkbox on spelling errors is unchecked in Document formatting settings.
 
1. Open any Word document in Word2010 by clicking it.
2. Focus goes to Collect and Paste 2.0 instead of to the text area.
3. Alt + Tab or Alt twice moves focus to text area.
4. The same happens in Excel/PP/Outlook.

NVDA version:
2017.1

NVDA Installed or portable:
Installed

Windows version:
Windows7 Pro SP1 64-bit

Name and version of other software in use when reproducing the issue:
Office2010

Havent tried it in any other version of NVDA; this was not an issue before 2017.1.

Here is the related output from the NVDA log viewer:
Developer info for navigator object:
 name: u'\x04\x02Clipboard is empty.\nCopy or Paste items to collect them.\x02'
 role: ROLE_LISTITEM
 states: 
 isFocusable: False
 hasFocus: False
 Python object: <NVDAObjects.IAccessible.IAccessible object at 0x050701B0>
 Python class mro: (<class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
 description: None
 location: (216, 239, 285, 54)
 value: None
 appModule: <'appModuleHandler' (appName u'winword', process ID 4292) at address 509c6f0>
 appModule.productName: u'Microsoft Office 2010'
 appModule.productVersion: u'14.0.7181.5000'
 TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
 windowHandle: 1377440
 windowClassName: u'bosa_sdm_msword'
 windowControlID: 0
 windowStyle: 1409286144
 windowThreadID: 732
 windowText: u'Collect and Paste  2.0'
 displayText: u''
 IAccessibleObject: <POINTER(IAccessible) ptr=0x143409d8 at 50bf490>
 IAccessibleChildID: 1
 IAccessible event parameters: windowHandle=1377440, objectID=21, childID=1
 IAccessible accName: u'\x04\x02Clipboard is emtpy.\nCopy or paste items to collect them.\x02'
 IAccessible accRole: ROLE_SYSTEM_LISTITEM
 IAccessible accState:  (0)
 IAccessible accDescription: None
 IAccessible accValue: exception: (-2147352573, 'Member not found.', (None, None, None, 0, None))

Many thanks in advance!

**Comment by Adriani90** [comment]
related to #8389

**Comment by Adriani90** [comment]
I am closing this in favor of #8389 because this issue is very general and occurs in several situations regardless of the application. The discussion in that issue goes further and will continue there.
