### ISSUE TITLE
Brailliant BI Dot 7 Backspace not working

### ISSUE THREAD

**Issue by DrDento** [nvaccess/nvda#7186]
### Steps to reproduce:
1: Open a text editor such as notepad.exe
2: Type in text using Brailliant BI Keyboard.  
3: Try and delete an error using backspace dot 7.

### Expected behavior:
Backspace should work and delete preceding character

### Actual behavior:
No backspacing but instead \7/ is outputted

**Comment by jcsteh** [comment]
Thanks heaps for the contribution. This is actually being solved in a more unified way by #2439 (contracted braille input), wherein dot 7 is bound to backspace for all displays. Work on #2439 is already well underway, so I'm going to close this in favour of that.
