### ISSUE TITLE
Fix spelling error in the whats new

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#7192]
• The list of completions in the autocomplete context menu of the PythonConsole no longer shows any objec path leading up to the final symbol being completed. (#7023)

**Comment by jcsteh** [comment]
When reporting spelling errors or typos, please indicate the exact word or phrase that is relevant, as it can sometimes be difficult to spot even when carefully proofreading. I assume you are referring to "objec" instead of "object"?

**Comment by jcsteh** [comment]
Fixed in 7459857e.
