### ISSUE TITLE
unable to arrow on valiant8086.com website with ms edge

### ISSUE THREAD

**Issue by valiant8086** [nvaccess/nvda#7200]
### Steps to reproduce:
1. Open Microsoft Edge - this is windows 10 build 10586, (not the creators update yet).
2. type http://valiant8086.com into the address bar and press enter to load this website.
3. Notice that the arrow keys don't work, can only tab through the focusable elements.

The web page consists  of a small html file that uses two frames to load the page's navigation bar and body. Perhaps being entirely loaded in frames causes this?

### Expected behavior:
We should be able to use up and down arrow keys to navigate this site. For me, I'm able to use my arrow keys to navigate on google.com and tractordata.com etc, just not my own website.

### System configuration:
NVDA version: 2017.2 rc1

NVDA Installed or portable: portable

Other information: Running on a Lenovo Yoga 2 pro with Windows 10586 (not the creators update).

Windows version: 10586
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue: Microsoft Edge

### Other questions:

Does the issue still occur after restarting your PC? I didn't try that

Have you tried any other versions of NVDA? No, I assumed  older versions wouldn't work as well if at all.
> Please list them and the result

**Comment by jcsteh** [comment]
Thanks for reporting. I just tested and this works for me in the Creators Update. Because accessibility in Edge is very much under development at the moment, it isn't feasible for us to continue to support earlier versions.

**Comment by valiant8086** [comment]
Thanks. I'm happy with this explanation.
