### ISSUE TITLE
Brazilian portuguese translation Speak button not pressed

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7209]
Good morning everyone.
When executing the nvda next 14060 when finding a button not pressed, nvda is not reading this speech in Brazilian Portuguese, he pronounces not pressed, the correct one would be to pronounce não pressionado.
I opened this call because I found it strange, when running the nvda rc 14056 the pronunciation is correct não pressionado.
Thank you.

**Comment by feerrenrut** [comment]
My guess is that the translations have not been merged back to next recently. I have merged master into next, this will bring the latest translations. I tried testing this for you but was not sure where to find an example that would match the case you saw. In any case please try next-14063 which should be available shortly. I'll close this issue, please comment or re-open if this issue persists. 

Thanks.

**Comment by jcsteh** [comment]
For reference, this test case will do it in Firefox:

`data:text/html,<button aria-pressed="false">Boom</button>`
