### ISSUE TITLE
NVDA PIME support

### ISSUE THREAD

**Issue by tommyTsaiTou** [nvaccess/nvda#7211]
Can you guys add support to PIME? 
An open source input method.
NVDA can not read it's status, like full-shape, half-shape, and braille can not get focus to it's candidates UI.
I can only see the first one, but tts can read the rest of it.

**Comment by feerrenrut** [comment]
Perhaps others know, but I personally am not aware of PIME. Is it this https://github.com/EasyIME/PIME

It would be really helpful if you could tell us a little about what PIME is used for, and who might use it. This helps us to asses the impact this would have, and makes it easier to give a priority to the issue.

**Comment by ehollig** [comment]
@tommyTsaiTou could you provide more information about PIME and answer the other questions addressed in https://github.com/nvaccess/nvda/issues/7211#issuecomment-304581536? This will help in assigning a priority to this issue.

**Comment by ehollig** [comment]
Closing, as we have not heard from the original poster, @tommyTsaiTou, for additional information as requested in https://github.com/nvaccess/nvda/issues/7211#issuecomment-320482877
