### ISSUE TITLE
Filter BELL character (0x07) from Braille output when using Word column/row headers

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#7212]
### Steps to reproduce:
1. Open Word 2016.
2. Insert a new 2x2 table.
3. Add 'Foo' as header for column 1 and 'Bar' for column 2.
4. Press NVDA+shift+c to mark the first row as containing column headers.
5. Go to column 1 row 1 and press downArrow.

### Expected behavior:
Column 1 row 2 should be spoken and brailled with the column header 'Foo'.

### Actual behavior:
This works, but the output contains the BELL charcter and a carriage return:

```
IO - inputCore.InputManager.executeGesture (16:28:38):
Input: kb(laptop):downArrow
IO - braille.BrailleBuffer.update (16:28:39):
Braille regions text: [u'r2 Foo\r\x07 c1  ']
```

### System configuration:
NVDA version:
master-14061,3e204582

NVDA Installed or portable:
Installed

Other information:
Only really tested with braille. Speech doesn't speak these characters but I haven't chcecked if this is due to e.g. a dictionary.

Windows version:
Windows 10.0.15063

Name and version of other software in use when reproducing the issue:
Microsoft Office 2016 (16.0.8067.2115) 32-bit

### Other questions:

Does the issue still occur after restarting your PC?
Yes.

Have you tried any other versions of NVDA?
No, but this is not a new issue.

**Comment by feerrenrut** [comment]
I can reproduce this with nvda `next-14060,345aa29a` and Office 2013. Important to note that this affects braille output, but not speech.

**Comment by Adriani90** [comment]
@dkager I guess this issue is still reproducible even with UIA for MS Word enabled. Right?

**Comment by dkager** [comment]
I don't know. But because UIA only works for Office 2016 and later, the issue is still relevant anyway.

**Comment by dkager** [comment]
This is still reproducible in the latest Office 365 non-UIA. I will do a patch later this month.

**Comment by Brian1Gaff** [comment]
Good grief, this takes me back a loooong way!

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----
