### ISSUE TITLE
Screen on/off indication

### ISSUE THREAD

**Issue by artiden** [nvaccess/nvda#7214]
### Steps to reproduce:
On my notebook (asus UX305UAB)

- Press FN+f7 to on/off display;
- Press FN+f9 to on/off touchpad;
- Etc...

### Expected behavior:
Speak current state of screen, touchpad, etc...:
For example:

- Screen is enabled;
- Screen is disabled.

### Actual behavior:
Fully silence.

### System configuration:
NVDA version: 2017.2

NVDA Installed or portable: Installed

Windows version: 
windows 10 pro 10.0.15063 build 15063

**Comment by jcsteh** [comment]
These are manufacturer specific commands and I don't know of any way for us to detect these states (especially not a way that works independent of manufacturer). It probably needs some investigation, though, as it'd certainly be nice to have this feedback.

**Comment by jcsteh** [comment]
Just tried to detect the state of my Synaptics touchpad when disabled using my laptop's keyboard. Unfortunately, I had no luck. It doesn't seem to be reported to the system at all and even the Synaptics API doesn't know about it:

```
>>> sdc = comtypes.client.CreateObject("SynCtrl.SynDeviceCtrl.2")
>>> from comtypes.gen import SYNCTRLLib as syn
>>> sdc = comtypes.client.CreateObject("SynCtrl.SynDeviceCtrl.2")
>>> sdc.GetLongProperty(syn.SP_DisableState)
0
```

(I used [this thread](https://autohotkey.com/board/topic/65849-controlling-synaptics-touchpad-using-com-api/) for my quick and dirty dive into the Synaptics API.)

Haven't tried this, but it [looks like detecting screen state](https://stackoverflow.com/questions/203355/is-there-any-way-to-detect-the-monitor-state-in-windows-on-or-off) is unreliable at best.

**Comment by jcsteh** [comment]
I'm going to close this, as based on the above research (brief as it was), I don't think this is possible in any reasonably reliable way. If anyone discovers a way to do these things reliably, we can reopen this.
