### ISSUE TITLE
Checkbox grouping label not read when previous focus is on a checkbox input or button

### ISSUE THREAD

**Issue by devangelito** [nvaccess/nvda#7215]
### Steps to reproduce:
1. Copy and test the sample html below
```
    <input type="button" value="Test Button" /><br /><br />

    <!-- ADDING BELOW WILL ENABLE GROUPING TO BE READ -->
    <!-- <input type="text" /><br /><br /> -->

    <label id="lblPizzaShape">Pizza shape:</label><br />
    <fieldset role="group" aria-label="lblPizzaShape">
      <input id="circle" type="checkbox" value="circle">
      <label for="circle">Circle</label>
      <br />
      <input id="square" type="checkbox" value="square">
      <label for="square">Square</label>
    </fieldset>
    <br />

    <!-- ADDING BELOW WILL ENABLE GROUPING TO BE READ -->
    <!-- <input type="text" /><br /><br /> -->

    <label id="lblPizzaToppings">Pizza toppings:</label><br />
    <fieldset role="group" aria-labelledby="lblPizzaToppings">
      <input id="cheese" type="checkbox" value="cheese">
      <label for="cheese">Cheese</label>
      <br />
      <input id="ham" type="checkbox" value="ham">
      <label for="ham">Ham</label>
    </fieldset><br />

    <!-- ADDING BELOW WILL ENABLE GROUPING TO BE READ -->
    <!-- <input type="text" /><br /><br /> -->

    <input type="submit" value="Submit" />
```
2. Tab through the checkbox inputs within the fieldset

### Expected behavior:
Group label for each checkbox group (e.g., Pizza shape or Pizza toppings) is read

### Actual behavior:
Group labels are not read

### System configuration:
NVDA version: 2017.2
NVDA Installed or portable: Portable

Other information:
Windows 10 Pro
Chrome Version 58.0.3029.110 (64-bit)

I've also seen these similar cases which I'm not sure if it makes this a duplicate, but the behavior is very much alike:
- https://github.com/nvaccess/nvda/issues/7205
- https://github.com/nvaccess/nvda/issues/6979
- https://github.com/nvaccess/nvda/issues/3321

If the previous focus is on a text input, group labels are read properly.

### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA?
> 2017.1 (same result)

**Comment by jcsteh** [comment]
You're correct; this is the same underlying issue as #3321. Thanks for searching! I understand why it's difficult to be certain.

Closing as duplicate.

**Comment by devangelito** [comment]
Thanks for the confirmation, James! We'll just keep on tracking the duplicate issue.
