### ISSUE TITLE
NVDA freezing in latest firefox browser

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#7222]
If you open the latest firefox version53 and go to any website and try reading an article or filling out a form, NVDA will freeze and become sluggish for awhile then speed back up again. A debug log is attached.
[debuglog.txt](https://github.com/nvaccess/nvda/files/1038159/debuglog.txt)

**Comment by leonardder** [comment]
I can confirm this with both NVDA Next and 2017.2, two pc's with Windows 10 creators update

**Comment by joshknnd1982** [comment]
The firefox freezing still occurs with the  NVDA latest next snapshot. A log file is attached with the info log, debug warning, input/output, and debug logs in one text file. 
[nvdalog.txt](https://github.com/nvaccess/nvda/files/1064218/nvdalog.txt)

**Comment by leonardder** [comment]
@joshknnd1982: Are you still experiencing this issue? I've experienced freezes lately with Firefox 59 and 60 beta, but I don't know whether they are related to NVDA.

**Comment by ehollig** [comment]
@joshknnd1982 and @leonardder are you still experiencing this with the latest version of Firefox?

**Comment by joshknnd1982** [comment]
No, you can close the issue if you want to.

**Comment by ehollig** [comment]
Closing as requested.
