### ISSUE TITLE
Inconsistent content field detection in Firefox and Chrome

### ISSUE THREAD

**Issue by alexandretoco** [nvaccess/nvda#7226]
### Steps to reproduce:
GO TO: https://passagens.pontosmultiplus.com.br/

1. look for the link "PASSAGENS AÉREAS' and press enter on it.
2. it will open a form with some fields...
3. press f to find a field called "para". type "sao".
4. press capslock + spacebar to switch to browse mode and press some arrowdown. The page will show some airports. They are clickable itens and when you click it it will fill the "para" field.
5. press spacebar to click one airport. 
6. use up and down arrow to check if the the choosen airport was filled in the "para".

			
### Expected behavior:
nvda should recognize the field's content because, if you enter the edit mode and use left and right arrow, you will notice that this edit field has content.
### Actual behavior:
If you press some arrowdown and arrowup, sometimes nvda recognizes the content of this field and sometimes, not.
So the navigation is not accurate.

### System configuration:
NVDA version: 2017.2
NVDA Installed or portable: installed
Windows version: Windows 10 Home Versão 1607 Build 
SO 14393.1198 
Name and version of other software in use when reproducing the issue:
Google Chrome Versão 58.0.3029.110 (64-bit)

firefox 53.0.3(32 - bit)

I tryed with both with the same result. I made the same test with Jaws and it recognized the field's content.

### Other questions:

Does the issue still occur after restarting your PC? yes

Have 
2017.1 - same result

**Comment by Adriani90** [comment]
cc: @jcsteh, @mltony, @leonardder I can reproduce this issue just by navigating with arrow keys around. Edit fields are skipped very often if you navigate fast with down and up arrow key.

There is following in the log:

```
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (01:59:02.503):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (01:59:02.585):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible.scrollIntoView (01:59:02.806):
IAccessible2::scrollTo failed
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1326, in scrollIntoView
COMError: (-2147417848, 'Das aufgerufene Objekt wurde von den Clients getrennt.', (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (01:59:02.809):
error executing script: <bound method Gecko_ia2.script_previousFormField of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x05569710>> with gesture u'Umschalt+f'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "browseMode.pyc", line 439, in <lambda>
  File "browseMode.pyc", line 413, in _quickNavScript
  File "browseMode.pyc", line 189, in report
AttributeError: 'NoneType' object has no attribute 'role'
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (01:59:02.845):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (01:59:02.868):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - eventHandler.executeEvent (01:59:02.872):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible object at 0x05569E50> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 150, in executeEvent
  File "eventHandler.pyc", line 163, in doPreGainFocus
  File "api.pyc", line 145, in setFocusObject
  File "api.pyc", line 233, in setNavigatorObject
  File "review.pyc", line 124, in setCurrentMode
  File "review.pyc", line 26, in getObjectPosition
  File "documentBase.pyc", line 24, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 94, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 202, in _findContentDescendant
COMError: (-2147417848, 'Das aufgerufene Objekt wurde von den Clients getrennt.', (None, None, None, 0, None))
```

Moreover, this is also shown while navigating around:

```
DEBUGWARNING - RPC process 5608 (firefox.exe) (02:01:25.190):
Thread 12536, build\x86_64\vbufBackends\gecko_ia2\gecko_ia2.cpp, GeckoVBufBackend_t::render, 1196:
No content rendered in update

DEBUGWARNING - RPC process 5608 (firefox.exe) (02:01:25.197):
Thread 12536, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::replaceSubtrees, 680:
Empty temp buffer
```

**Comment by Adriani90** [comment]
@alexandretoco the design of the webpage in your description seems to have changed. There is not a link called "PASSAGENS AÉREAS'. Could you please update your description accordingly so that we can reproduce this issue?

**Comment by Adriani90** [comment]
We do not have any updates on this issue and the website design has changed so that we cannot reproduce this issue anymore. Closing as abandoned since it also seems that we lost contact to the initial author.
