### ISSUE TITLE
Fatal error blocks main thread

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7228]
Not sure whether this is intentional. I thought I already reported this, but can't find a ticket for it, so sorry if this duplicates.

### Steps to reproduce:
Do the following in a python console:

```
from logHandler import log
log.fatal("This breaks!")
```

### Expected behavior:
Fatal error sound plays, but NVDA continues as normal

### Actual behavior:
Fatal error sound plays and NVDA freezes until playing the sound is finished

**Comment by jcsteh** [comment]
We use critical to report startup or crash failures, so it needs to block.
NVDA generally exits or restarts in these cases, so if we didn't block, you
wouldn't get to hear the sound. Fatal (which is an alias for critical)
rather suggests that this is the kind of thing that has seriously
destabilised NVDA or prevented it from functioning at all, so I don't see a
good use case for most people using this anyway. Do you have a use case?

**Comment by leonardder** [comment]
I do not have a use case here, I just wasn't sure the blocking is intentional. Seems it is, closing this.
