### ISSUE TITLE
Problem reading mail for Windows 10

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#7238]
Hello. After today's update of NVDA, there is a problem reading the mail message in your app.
Steps to reproduce. 1. Open the Mail app.
2 start reading incoming mail.
Expected. NVDA should read the letter using the arrows.
Actual. Nvda says one and the same reading string can only be pressed with the NVDA key.

Was the reboot Nvda? Yes.windows 10 1703
 16199
NVDA next-14084,18708861.

**Comment by josephsl** [comment]
Hi,

Replaced by #7289, as that issue contains more info and workarounds. Turns out this is due to renamed executable (yet again). Thanks.

Thanks.
