### ISSUE TITLE
Include applications, dialogs and audio/video tags in embedded object quick navigation

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7239]
Embedded objects based on the html object tag are getting more rare these days. There are two things I see happening more regularly:

1. Applications embedded inside a document, e.g. [MediaElement.js audio and video players](http://www.mediaelementjs.com/). You can find at least two players on this page using the application role. I'm not sure whether this meets the accessibility standard, it's just that they seem to have implemented it this way. Other examples include rich text editors, which are in fact edit fields but they aren't accessible using quick nav. Since treating them as edit boxes will be quite difficult probably (you can't see whether an application is a richt text editor or not), I think object would be a nice alternative
2. Websites that have dialogs embedded on them. Usually, those dialogs should receive focus automatically, but they often don't, which requires you to find the dialog using browse mode. Quick nav for this is something I'd certainly use.

**Comment by leonardder** [comment]
@derekriemer: Given your comment in https://github.com/nvaccess/nvda/issues/124#issuecomment-217989072 , what do you think about this?

**Comment by derekriemer** [comment]
I think it would make sense.

**Comment by jcsteh** [comment]
I think this makes sense, but please note that the command descriptions and User Guide needs to explicitly mention this in the appropriate places. Regarding the User Guide, from memory, you should check the section that lists first letter navigation keys, as well as the specific section on embedded objects.

**Comment by leonardder** [comment]
I opened a pr for this. When I saw the code for this, I noticed that it was very easy to also add audio and video tags in the process, at least for Gecko and MSHTML. Although I haven't discussed this in this issue, it seemed reasonable to add these in the process. Feel free to object this, it's not a problem at all to remove this.
