### ISSUE TITLE
Automatic Say All on page load unreliable

### ISSUE THREAD

**Issue by FelixGruetzmacher** [nvaccess/nvda#7246]
### Steps to reproduce:
1. In NVDA's browse mode preferences, set the option automatic Say All on page load.
2. In Firefox 53.0.3 32 bit, surf to www.heise.de
### Expected behavior:
Page should automatically read when fully loaded.

### Actual behavior:
Page content is not read automatically.
### System configuration:
NVDA version: 2017.2
NVDA Installed or portable: Installed

Windows version: Windows 7 64 bit, fully patched

Name and version of other software in use when reproducing the issue:
Firefox 53.0.3 32 bit

### Other questions:

Does the issue still occur after restarting your PC?
Yes.
Have you tried any other versions of NVDA?
Not explicitly tried for this issue.

**Comment by leonardder** [comment]
Could you reproduce this with older versions of Firefox? If not, it 
might be related to the regression reported in #7222

**Comment by FelixGruetzmacher** [comment]
It's not a freezing issue. Say All just doesn't start, but everything remains responsive.

**Comment by jcsteh** [comment]
On the modern, highly dynamic web, there's not really a reliable way to determine when a page has finished loading. We used to wait until all resources finished loading before enabling browse mode, but on really large or slow loading pages or pages with a lot of images, stylesheets, JavaScript, etc., this can mean the user has to wait an unreasonable amount of time before they can interact with the document. In some cases, it means they can never interact at all; some pages in modern web apps always report as "busy". In contrast, a sighted user sees content as it arrives. Thus, we made the decision several years ago to just enable browse mode and say all as soon as the document got focus (which is usually when the browser thinks it has enough content to do something useful). In this case, that doesn't work so well.

Interestingly, this does behave better in Chrome, which suggests Chrome either loads it faster or behaves in a way which works better for this case. I can't fathom specific details, though.

**Comment by Adriani90** [comment]
@jcsteh I noticed that it works reliably when pressing f5 or when moving backwards to a previous page (alt+left arrow or backslash) if the page is not part of the same website (i.e. mooving backwards from link in the description to Github). But it does not work when mooving forward (alt+ right arrow from Github to link in the description).
If I am moving back and forth between two github pages, NVDA does not read at all. Neither the title of the page.

**Comment by jcsteh** [comment]
> If I am moving back and forth between two github pages, NVDA does not read at all. Neither the title of the page.

That's an entirely different issue related to so-called "single page apps" (SPAs). When you move between pages on GitHub, the page doesn't actually reload; the current document is updated dynamically. That makes things faster and smoother. Unfortunately, there's no good way to make this accessible. There's some discussion going on between various stakeholders at the moment as to how to improve this, but it will require work and cooperation right across the industry (standards, web frameworks/sites, browsers, screen readers).

**Comment by feerrenrut** [comment]
From quick testing, I believe this is fixed. Probably by https://github.com/nvaccess/nvda/pull/13589
I'm going to close the issue, @FelixGruetzmacher please confirm and let us know, I'll re-open if you disagree.
