### ISSUE TITLE
Performance regression caused by display model/transparent text color handling

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#7251]
Hi,

Several users of reported performance and display model regressions in NVDA 2017.2:

* When using OTS Studio (a broadcasting software), when scanning thousands of files, it used to take only 90 seconds with 2017.1, but it takes up to five minutes in 2017.2.
* In mIRC, when new messages arrive, NVDA repeats some messages or there is a noticeable delay when message window is updated.

After doing git bisect, it appears either one of the following might be responsible:

* execInThread
* Transparent text color handling in display model.

Thanks.

**Comment by jcsteh** [comment]
Were you able to confirm the performance regression in OTS Studio yourself? That is, are you certain that this takes 90 seconds in 2017.1, but immediately goes up to 5 minutes with 2017.2? I want to be certain this is not a regression in, for example, an OTS Studio update.

@MichaelDCurran, could the display model changes in 2017.2 cause performance hits like this?

**Comment by josephsl** [comment]
Hi, yes, I was able to confirm this. In 2017.2, NVDA’s progress bar output routine (when converting files) is slower than 2017.1. As for the cause, I’m looking at a range of commits from March 14, 2017, as master.13914 was the last good build for this case. Also, Matt informs me that display model might not be the culprit, and I’m guessing that the most direct one could be exec* function change or core.CallLater. Because of this, I’ll morph the title to reflect what’s up. Thanks.

**Comment by jcsteh** [comment]
[**@josephsl**](https://github.com/josephsl) commented on [Jun 5, 2017, 11:33 AM GMT+10](https://github.com/nvaccess/nvda/issues/7251#issuecomment-306083112 "2017-06-05T01:33:54Z - Replied by Github Reply Comments"):
> In 2017.2, NVDA’s progress bar output routine (when converting files) is slower than 2017.1.

I don't quite follow. The speed of the progress bar routine is irrelevant. Regardless of how fast NVDA responds, the question is whether the app itself is slower when performing the task.

> As for the cause, I’m looking at a range of commits from March 14, 2017, as master.13914 was the last good build for this case.

You mentioned that you did a git bisect, but you point out three possible culprits. A git bisect should allow you to narrow this down to one commit. Is there something I'm missing here? Can you outline your results in more detail?

> Also, Matt informs me that display model might not be the culprit

I'm not sure I agree here. We now possibly call GetPixel quite a lot and we discovered performance problems with GetPixel in the past with Windows Vista (see 18b39334). It's worth noting that we were calling GetPixel a lot and the change was primarily to reduce the number of calls, but I'm still suspicious of this. If you want to be certain, you can try the following. Around line 549 of nvdaHelper/remote/gdiHooks.cpp, you'll see this:

> `COLORREF prevColor = GetPixel(hdc, x, y);`

Change it to this:

> `COLORREF prevColor = CLR_INVALID;`

> and I’m guessing that the most direct one could be exec* function change

We don't use execInThread except in browse mode, Microsoft Word and IA2 editable text. I don't think any of these apply here.

> or core.CallLater.

We don't use this in many places, certainly not anywhere related to progress bar handling.

**Comment by michaelDCurran** [comment]
Also line 733 in hook_exTextOut

**Comment by josephsl** [comment]
Hi,

Bisect results: ultimately, the last commit it showed me was the display model commit from Matt. I came to my last conclusion due to the fact that master.13921 included various commits, hence looked at surrounding commits.

Regarding the program versus NVDA: to elaborate, the program responds slower when NVDA 2017.2 is run, not with 2017.1.

Thanks.

**Comment by jcsteh** [comment]
Here's a [try build which disables the GetPixel calls](https://ci.appveyor.com/api/buildjobs/lg45t0kanyug3i20/artifacts/output%2Fnvda_snapshot_try-noGetPixel-14093%2Cad84027c.exe) which I suspect to be the source of the regression. It'd be great if anyone who can reproduce this problem could test this and confirm. Thanks.

**Comment by josephsl** [comment]
Hi,

Yep, the try build resolved it. Thanks.

**Comment by jcsteh** [comment]
Would you be able to contact the original reporter and ask them to test
with this try build if they are willing, just for extra confirmation?
Thanks.

**Comment by zahra21** [comment]
hi joseph and all nvda developers.
i downloaded nvda 2017.2
even sometimes when i started my computer and pressed start button to bring the menus, nvda became unresponsive and silent.
sometimes, using TaskManager and ending processing of nvda and its shortcut to start nvda or sometimes, nvda's shortcut for starting it, was helpful for me.
but sometimes i needded to use power button to turn of my system!
i use windows xp, with twoGb of ram and cpu two cores.
in most cases, also i could not use firefox easily and i should press alt+tab many tabs many tabs or close firefox or end process of nvda and restart it to work.
so i completely uninstalled 2017.2 and returned to 2017.1
its extremely fast and completely responsive without any hang or crash.
i am completely satisfied with nvda 2017.1 and i dont have any problem which i mentioned in nvda users mailing list or in the github with firefox using this version of nvda.
nvda 2017.1 is the best version for me.
thanks so much for your great program,
i decided to keep nvda 2017.1 forever and never update it for some reasons.
but i try to test newer version to help developers until its end support for xp.
or if i cant test, i ask others and participate in github and try my best to help others in the users mailing list.
thanks so much for your great program, i pray for you in my five times obligatory prayers, pray divine infinite mercy and blessings for you all.
i wish that nvda be alive forever in the world of technology and i see its progress and can help for it.

**Comment by josephsl** [comment]
Hi,

I received numerous positive feedback from other users, including no performance degradations after using it for ten minutes, elimination of performance issues when programs are run with NVDA and so forth. Thanks.

**Comment by zahra21** [comment]
hi.
what should i do to use firefox with nvda 2017.2?
i have the issue, when i installed nvda 2017.2, sometimes nvda caused locking my keyboard and i could not do anything except turn off my system with power key and turn it on again.
sometimes restarting nvda could help me, but in heavy scrypted websites which use hundreds megabyte of ram, nvda 2017.2 is very unstable and causes the problems which i mentioned in above lines.
i really wished to use this version, (because of some important bug fixes and its the best version which supports xp).
but this performance regression and also phonetic spelling (added in this version of nvda, when using insert up three times, prevented me and i downgraded to previous versions of nvda for these reasons!
what should i do to use nvda 2017.2 without freezing my keyboard, nvda itself or possible performance regression caused by supporting transparent color background? and benefit from my desired bug fixes in 2017.2?
i really appreciate any help from you, i sincerely pray for you in my five times daily obligatory prayers
and sincerely request divine infinite and special mercy, graces, bounties and favors for you because of your extremely great screen reader which i requested God to grant me this grace to use forever and see its progress.
while nvda does not support my favorite windows xp anymore, but i try my best to help its users and developers and follow github and progress of nvda (the best screen reader in the world), which i am always grateful to Allah because of it!
