### ISSUE TITLE
Add an option to control the cursor from the Braille display in review mode

### ISSUE THREAD

**Issue by vincent-lg** [nvaccess/nvda#7256]
### Feature request

When in console mode with a Braille display, one possibility is to toggle cursor tethering.  This way, the Braille display can be move using the usual review shortcuts (numpad7, numpad9...).  It can be useful to have one profile just to activate the "Braille tethered to focus/review" when switching applications.  Quite useful for someone who spends lots of time in the Python console or Windows console, but always wishes to use the notepad or MS suite.

However, when in "Braille tethered to review" mode, if using the Braille display routing keys (to move the cursor), the real cursor (the focus cursor) is not moved, since Braille is tethered to review for navigation and keys.  I suggest to separate both modes: in most cases, the console doesn't allow clicking anyway.  But in some cases (like with Git bash for instance, which is completely accessible), one can use the mouse to click (bringing the cursor somewhere on the window) or select text.  It would be great if, even with the Braille tethered to review mode, which is kind of necessary in this case, one could still use routing keys to quickly move the cursor.

### Suggested option

One possibility would be to add an option in the Braille settings.  A simple checkbox, to have the cursor always in focus mode, or following the Braille (whether it is).  Adding it in the options would allow to expand on profiles.  Of course, in this mode, it wouldn't be possible to use the routing keys to move the review cursor around, it would be either.  There are other ways to do it but I believe this one to be the least confusing and most flexible alternative.

Thanks again for all your good work!

**Comment by jcsteh** [comment]
This is similar to #3166, except that it suggests clicking the mouse for consoles as the method used to move the caret. This is something we should investigate after #3166 is resolved.

**Comment by Adriani90** [comment]
cc: @bramd, @leonardder

**Comment by Adriani90** [comment]
Î think clicking with the mouse cannot be performed with braille still, this part of the issue might have to be investigated further. However, now after #15064 NVDA can route the system focus to the review cursor using the routing keys of the braille display. I am removing the blicked label here.

**Comment by michaelDCurran** [comment]
Closing as fixed due to the "Move system caret when routing review cursor" option. I think specificly clicking with the mouse is a secondary issue and not necessarily required to move the caret in git bash?
