### ISSUE TITLE
System focus and navigator object is not followed while Firefox is not maximized

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#7260]
STR
1 Open http://www.excellup.com/classten/mathten/trigonometryexfour.aspx in Firefox 53.0.3.
2 Navigate to the first graphic labelled ‘10 trigonometry exercise solution’.
3 Ensure that review cursor follows system focus and system caret via the Review Cursor settings dialog and ensure that NVDA+6 and NVDA+7 corresponding options are both enabled.
4 A Press Enter on the graphic.
Expected: The graphic is pressed.
Actual: Focus jumps away and NVDA reports it. It can be the Desktop, another window such as NVDA Log Viewer, or Skype buttons getting pressed depending on what programs I have loaded at the time of testing.
4 B Ensure via all means that your focus and current navigator object is the referred graphic and try pressing NVDA+Enter on the same and/or move the mouse pointer to current navigator object and emulate a left mouse click.
Expected: At least after being completely assured that the current navigator object is the required graphic by pressing NVDA+Shift+O, the graphic should be where the mouse pointer moves which NVDA should speak and the graphic is what should get clicked.
Actual: The ‘other window’ (such as Skype) receives focus and the ‘other option’ (such as the Skype Profile option) gets clicked although NVDA+Shift+O did indicate the graphic as the current navigator object.

During consistent replication of this issue to conduct various experiments, two discoveries were made:
Work-around: Pressing F11 in Mozilla Firefox maximizes the content portion after which everything works perfectly. Pressing F11 back resumes this buggy behaviour exactly as described above.
Log Snippet: Below is something I picked up while replicating this issue which is odd in the sense that it mentions a mouse click when I have actually pressed nothing but Enter. It is an excerpt from NVDA’s log which I extracted in hope of elucidating my issue.
Input: kb(laptop):enter
DEBUGWARNING - virtualBuffers.gecko_ia2.Gecko_ia2._activateNVDAObject (22:54:00):
doAction failed
DEBUGWARNING - virtualBuffers.gecko_ia2.Gecko_ia2._activateNVDAObject (22:54:00):
Clicking with mouse
IO - speech.speak (22:54:00):
Speaking [LangChangeCommand ('en_GB'), u'Skype\u2122\u200e [5] - bhavya.09']

Lastly, while this issue did occur infrequently in the past, I have noticed a conspicuous increase in the frequency of this bug happening at my end lately, which leads me to believe that NVDA version 2017.2 or a recent Firefox update may be bolstering such. I have not tested this with previous NVDA version, nor with alternate web browsers, although I have ensured that this lies with NVDA core and not with any add-on.

**Comment by ehollig** [comment]
@bhavyashah is this still something that happens for you? If so,this sounds similar to #5098

**Comment by bhavyashah** [comment]
I am very sure I believed this to be a long-standing issue with a non-maximized Firefox and NVDA and I also recall successfully reproducing this issue with the given sample URL multiple times. However, I seem to be unable to reproduce this at the moment. While #5098 and this ticket are duplicates, I would like to kindly suggest closing #5098 as a duplicate since this one seems slightly more detailed, though my assessment of the report quality might be biassed. :) Anyways, I would like to request others to retest this as well as the GMail Standard View test case of #5098 so as to ascertain whether this somehow got fixed or is still persistent. CC @jcsteh (Firefox expert and soon-to-be Mozilla representative)

**Comment by ehollig** [comment]
When doing some searches, it appears #2913 describes similar behavior. As described in https://github.com/nvaccess/nvda/issues/2913#issuecomment-155303761, the graphic described in this issue could possibly not be visible on screen when the browser is not maximized. I am closing this as invalid, but if this still persists, we can reopen this issue.
