### ISSUE TITLE
Using High Level Hooking to provide more information

### ISSUE THREAD

**Issue by winman3000** [nvaccess/nvda#7264]
With more an dmore applications, it is not possible to navigate trough the Windows with the Screen view. You should use the object Navigation insteat. But for most users, navigation with ScreenView is easier than with object Navigation. More and more Screen Readers including JAWS and Cobra are switching to High Level Hooking to get more Information and create it's own OSM.

**Comment by josephsl** [comment]
Hi, a few days ago I had a conversation with @JCSTeh, and he said this cannot be done for various reasons. I’ll leave this open in case he wants to clarify a few things. Thanks.

**Comment by josephsl** [comment]
Hi,

Also, if you're thinking of screen review in universal apps, this cannot be done for fully universalized apps, and last time I checked, JAWS 18.0.2945's JAWS cursor does not work versal apps.

Thanks.

**Comment by winman3000** [comment]
Hi Joseph,

 

this High Level thing I was mentioned will be coming with JAWS 19 and will work with UWP Apps. Cobra, a Screen Reader from Baum is working with this solution since one year or so.

 

Regards

Ali

 

Von: Joseph Lee [mailto:notifications@github.com] 
Gesendet: Mittwoch, 7. Juni 2017 17:10
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: winman3000 <ali-savas@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Using High Level Hooking to provide more information (#7264)

 

Hi,

Also, if you're thinking of screen review in universal apps, this cannot be done for fully universalized apps, and last time I checked, JAWS 18.0.2945's JAWS cursor does not work versal apps.

Thanks.

**Comment by jcsteh** [comment]
Ultimately, I think having browse mode everywhere (similar to Narrator scan mode) is a more reliable, sustainable and feature rich solution than any kind of screen scraping. I think we should exhaust all possibilities with this first before resorting to further screen scraping methods. As such, I'm going to close this; we can reopen at some future point if necessary.
