### ISSUE TITLE
Pressing alt+f or alt+e fails to launch the Chrome menu

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#7267]
### Steps to reproduce:
1. Open Chrome
2. Press alt+f to launch Chrome menu.
3. Press alt+e to launch Chrome menu.

Log snippet:
Input: kb(laptop):alt+f
IO - inputCore.InputManager.executeGesture (05:23:31.306):
Input: kb(laptop):alt+e
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (05:24:07.517):
oleacc.AccessibleObjectFromEvent with window 4786376, objectID -4 and childID 0: [Error -2147024809] The parameter is incorrect
IO - speech.speak (05:24:14.180):
Speaking [LangChangeCommand (u'en_US'), u'Issues \xb7 nvaccess/nvda  window']
IO - speech.speak (05:24:14.187):
Speaking [LangChangeCommand (u'en_US'), u'main  tool bar']
IO - speech.speak (05:24:14.191):
Speaking [LangChangeCommand (u'en_US'), u'Chrome  menu button  subMenu  Customise and control Google Chrome']
IO - inputCore.InputManager.executeGesture (05:24:20.779):
Input: kb(laptop):escape
IO - speech.speak (05:24:20.891):
Speaking [LangChangeCommand (u'en_US'), u'Issues \xb7 nvaccess/nvda  document']
IO - speech.speak (05:24:20.894):
Speaking [LangChangeCommand (u'en_US'), u'link', u'Skip to content']
IO - inputCore.InputManager.executeGesture (05:24:25.309):
Input: kb(laptop):alt+f
IO - inputCore.InputManager.executeGesture (05:24:27.036):
Input: kb(laptop):downArrow
IO - speech.speak (05:24:27.088):
Speaking [LangChangeCommand (u'en_US'), u'banner landmark ', u'link', u'Homepage']
IO - inputCore.InputManager.executeGesture (05:24:28.634):
Input: kb(laptop):alt+e
IO - inputCore.InputManager.executeGesture (05:24:29.483):
Input: kb(laptop):downArrow
IO - speech.speak (05:24:29.502):
Speaking [LangChangeCommand (u'en_US'), u'search landmark ', u'visited  link', u'This repository']

### Expected behavior:
Chrome menu should be launched and focus should be placed on the first item.

### Actual behavior:
Focus does not change even though the keys are recognized.

### System configuration:
NVDA version next-14098,66f26bb2

NVDA Installed or portable:
installed.

Windows version:
Windows 10 Version 1703 Build 16199.100

Name and version of other software in use when reproducing the issue:
Chrome Version 61.0.3122.0 (Official Build) canary (64-bit)

**Comment by PratikP1** [comment]
Related to #7266. Note that alt key by itself is not recognized.

**Comment by jcsteh** [comment]
This is a recent regression I filed earlier today: https://bugs.chromium.org/p/chromium/issues/detail?id=730924

Note that in earlier versions of Chrome, alt+f/alt+e does not focus the first item, though the menu itself does get focus. It behaves more like a context menu.

**Comment by PratikP1** [comment]
Thank you. I’d noticed the list instead of menu but didn’t know if it was related.

**Comment by PratikP1** [comment]
As of Chrome Canary 61.0.3154.0, this problem has been resolved. I can open Chrome's menu with alt+f or alt+e. Not landing on the first item is another issue. @Jcsteh, for reference, the issue you filed is labelled "Untriaged" but the regression you reported is resolved. I followed the STR you listed in your report. Chrome now says what it should.

**Comment by derekriemer** [comment]
Should I add worksforme and remove needsExternalFix and googleWork?

**Comment by jcsteh** [comment]
1. Worksforme would suggest we don't quite know what fixed the issue, which i guess is partially true, but we do have a Chromium issue for this and we know what build it got fixed in, so it's reasonably clear it was an intentional fix. So, no worksforme.
2. For a closed issue, needsExternalFix still lets us know the fix was external, not ours. The "needs" bit isn't really correct, but switching stuff to "gotFixedExternally" for linguistic satisfaction would just be pointless tedium. :) So, we leave it.
3. GoogleWork lets us know this is (in this case, was) part of our work with Google for the purposes of tracking. So we leave that too.

Hope this helps explain.
