### ISSUE TITLE
Math not spoken in Firefox using MathPlayer 4

### ISSUE THREAD

**Issue by RichCaloggero** [nvaccess/nvda#7268]
### Steps to reproduce:

1. Open firefox
2. browse to https://www.dessci.com/en/products/mathplayer/tech/accessibility.htm
3. navigate to the heading "Some sample equations to speak" and press DownArrow

### Expected behavior:

NVDA should speak The text "It is very common for textbooks and technical papers to embed snippets of math such as ", followed by a math expression. 

### Actual behavior:

To be clear, neither the math expressions themselves, or the surrounding text is spoken.  The surrounding text can be read via the nextWord (control+rightArrow) or nextCharacter (rightArrow) NVDA commands.

It also seems that if a `br` element is placed before and after each `math` element, the surrounding text will speak, but the math is still unspoken. If I position the browse cursor on a math expression and press the interact with math NVDA command, nothing is spoken. If I press this key when not on a math expression, NVDA says "not math".

### System configuration:

- NVDA version: 2017.2
- NVDA Installed or portable: installed
- Other information: MathPlayer 4.0
- Windows version: windows 7 enterprise, 64-bit, service pack 1
- firefox version 53.0.3

### Other questions:

Does the issue still occur after restarting your PC?

Yes it does.

Have you tried any other versions of NVDA?

Yes, NVDA version 14102,e82c068e

Results exactly the same, however instead of not speaking the math, a sound is heard instead. This sound is also played when using the interact with math command while positioned on a math expression.

**Comment by RichCaloggero** [comment]
Reinstalled firefox and the problem went away!

**Comment by francipvb** [comment]
Firefox for 64bits doesn't work with Mathplayer.

Cheers,
