### ISSUE TITLE
Contents of new tabs not consistently loading in Chrome

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#7271]
### Steps to reproduce:
This problem does not occur consistently. But it happens more frequently with tabs llaunched from external links. It is not related to a Chrome update as this problem started occuring a few days after a latest Chrome Canary update was applied.
1. Open Chrome.
2. Open a new Chrome tab by opening a link from an external source such as an email.
3. Try to read the page by pressing NVDA+a or by using the arrow keys.
4. Try reloading the page with control+r.
5. Occasionally press tab and shift+tab to attempt to move to parts of the page.
6. See attached log for example of behavior.

### Expected behavior:
NVDA should read all the contents of the loaded Chrome window.

### Actual behavior:
Only the window title is spoken.

### System configuration:
NVDA version next-14106,059e7f02

NVDA Installed or portable:
installed

Windows version:
Windows 10 version 1703 build 16199.100

Name and version of other software in use when reproducing the issue:
Chrome Version 61.0.3126.0 (Official Build) canary (64-bit)
[NVDA Chrome not loading buffer.txt](https://github.com/nvaccess/nvda/files/1065924/NVDA.Chrome.not.loading.buffer.txt)

**Comment by jcsteh** [comment]
> It is not related to a Chrome update as this problem started occuring a few days after a latest Chrome Canary update was applied.

Chrome applies updates automatically. Can you be certain another update wasn't applied?

While I realise you've provided a log, figuring out problematic behaviour from a log alone is tedious and time consuming. It'd be a massive help if you can provide thorough details of the problematic behaviour you're seeing. We can then use the log to glean additional details with that in mind. Some specific questions below (but as much detaila s you can provide is best):

> Open a new Chrome tab by opening a link from an external source such as an email.

When you say external source, do you mean another Chrome tab or another application or both? (Email isn't clear these days, since one might be using web mail.)

> Try to read the page by pressing NVDA+a or by using the arrow keys.

You mention later that only the window title is spoken. Are you saying that pressing up/down arrows only reads the window title?

> Try reloading the page with control+r.

What happens when you do this? The same thing as above?

> Occasionally press tab and shift+tab to attempt to move to parts of the page.

What happens?

**Comment by jcsteh** [comment]
Possibly related to #7272/Chrome issue 732199. I think we should wait until the fix for that lands and then re-evaluate.

**Comment by PratikP1** [comment]
@jcsteh wrote:
> Chrome applies updates automatically. Can you be certain another update wasn't applied?
While I realise you've provided a log, figuring out problematic behaviour from a log alone is tedious and time consuming. It'd be a massive help if you can provide thorough details of the problematic behaviour you're seeing. We can then use the log to glean additional details with that in mind. Some specific questions below (but as much detaila s you can provide is best): <

Chrome asks for manual restarts if it needs me to. Bad assumption on my part that it does it every single time. Also re details, my apologies. It appears that my original description and steps had a paragraph missing. I had a paragraph of explanation at the beginning of the steps. I should have checked to be sure that it made it. Here it is:

When loading new tabs, windows, or refreshing pages, NVDA does not read the contents of the page. Arrow keys or NVDA+a does not read the entire page. Only the page title is read. It takes multiple refreshes to resolve this. On occasion, it requires that the tab be closed and reopened. This happens most frequently when links are launched from external sources such as external email programs--e.g., Microsoft Outlook. Occasionally, the page is rendered to NVDA if tab or shift+tab is used. NVDA starts reading the page.

Since my original posting, I've verified that this behavior also happens if a new tab is launched from within Chrome. It makes no difference if the link is launched from an external source such as outlook.

Again, sorry for creating extra work for you.

**Comment by PratikP1** [comment]
Testing in Chrome Canary version 61.0.3135.0 suggests that this problem still occurs on select web sites. I'm attempting to narrow this down to understand whether the behavior is limited to specific sites.

**Comment by jcsteh** [comment]
Do you have any idea whether the missing content is in an iframe? I've
definitely seen cases of broken iframe accessibles in Chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=730915

**Comment by PratikP1** [comment]
@jcsteh wrote:
> Do you have any idea whether the missing content is in an iframe?

The missing content is definitely not in an iframe. So far, This behavior mostly happens on [Washington Post's](https://www.washingtonpost.com) site. It's still inconsisten behavior. It happens with the entire page and not specific part of the page. It did occur on another site that I was testing. No iframe anywhere in site.

**Comment by jcsteh** [comment]
When this occurs, if you press NVDA+f5, is the document readable as expected?

**Comment by PratikP1** [comment]
@jcsteh wrote:
> When this occurs, if you press NVDA+f5, is the document readable as expected?

No. The tab does not refresh. NVDA's view doesn't refresh. It's quite strange. At times, if I don't press the control key, NVDA starts reading the contents of the tab. But if I press any other key like 1 or h to skip to the main content, NVDA loses all content. It only reds the title of the page from then on.

**Comment by jcsteh** [comment]
Does NVDA even say "refreshed" when you press NVDA+f5?

**Comment by PratikP1** [comment]
@jcsteh wrote:
> Does NVDA even say "refreshed" when you press NVDA+f5?

It does say that with no effect. I'm trying to create a short screen cast so that you can look at the behavior.

**Comment by PratikP1** [comment]
As of Chrome Canary 61.0.3154.0, this problem has disappeared. I discovered that, if I let NVDA start talking and wait for about 8 to 10 seconds, the page would reload and start speaking from the top of the page. At that point, I was free to interact with it. Now, I am no longer experiencing this issue.

**Comment by richardbartley** [comment]
This issue is still occurring in Version 61.0.3163.100 (Official Build) (64-bit).  Seems to happen after a few hours of use.  Swapping tabs does not reload their content.  F12 developer tools does not load anything.

**Comment by feerrenrut** [comment]
@richardbartley Could you please update your comment to include the version of NVDA you were using?
