### ISSUE TITLE
Each new Chrome window (and manual refreshes) result in focus mode being turned on automatically 

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#7272]
### Steps to reproduce:
1. restart Windows.
2. Start NVDA if it's not already started.
3. Open Chrome.
4. try to navigate page with arrow keys or other navigation commands.
5. Use tab or shift+tab to navigate.
6. Switch to other open tabs or open new tabs or windows.
7. In an open tab with content, manually refresh the page with ctrl+r.
8. On each page, switch to browse mode with ctrl+space.

Review log of behavior.

### Expected behavior:
With each open window or tab, Browse mode should automatically switch on 

### Actual behavior:
Each page results in focus mode whether or not a form field has focus. Browse mode switches to focus if a page is refreshed.

### System configuration:
NVDA version: next-14106,059e7f02

NVDA Installed or portable: installed

Windows version: Windows 10 1703 build 16199.100

Name and version of other software in use when reproducing the issue:
Chrome Version 61.0.3126.0 (Official Build) canary (64-bit)
[NVDA Chrome auto-browse mode..txt](https://github.com/nvaccess/nvda/files/1066075/NVDA.Chrome.auto-browse.mode.txt)

**Comment by jcsteh** [comment]
This is a very recent Chrome Canary regression. I wasn't seeing this last week, but I just updated and am seeing it now. Chrome seems to have dropped the read-only state on documents, which confuses NVDA. I'll file a Chrome bug.

**Comment by jcsteh** [comment]
Filed: https://bugs.chromium.org/p/chromium/issues/detail?id=732199

**Comment by PratikP1** [comment]
Based on testing in Chrome Canary version 61.0.3135.0, this problem is resolved.

**Comment by jcsteh** [comment]
Confirmed. For reference, the issue I filed got merged into this one: https://bugs.chromium.org/p/chromium/issues/detail?id=733313
