### ISSUE TITLE
Introduce a special Math speech rate

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#7274]
As an NVDA-ESpeak user, I tend to keep speech rates between 20-45% with Rate Boost enabled (20 during meticulous reading and 45 for general navigation), and the Synth Settings Ring enables me to change them seamlessly on the fly. However, while interacting with mathematical content, particularly when needing to analyse, understand and memorize a particularly complex set of trigonometric fractions involving roots, just for instance, consuming Math content at even 20% with Rate Boost enabled leads to lack of complete understanding of the mathematics as well as an unnatural experience due to the seemingly robotic pauses in Math reading.
To address this problem, I would like to suggest introducing a distinct option to select speech rate for all Math content. This would make it possible to maintain a constant speech rate at which a user is comfortable in consuming Math, and a separate speech rate for everything else, enabling more customizable and comprehensive consumption of Math.

**Comment by jcsteh** [comment]
Similar to #4738. Requires core changes we will introduce for switching synths for specific languages (#279), which in turn depends on speech refactor (#4877).

**Comment by NSoiffer** [comment]
FYI: MathCAT has a dialog item that controls the relative rate of speech in math. Maybe this is a non-issue now?

**Comment by bhavyashah** [comment]
Thanks to @NSoiffer (and his wonderful work on MathCAT!), yes, this is no longer an issue for me. Closing this for now (but others who feel that this should be in core are welcome to reopen).
