### ISSUE TITLE
Support toast notifications in Skype for Business

### ISSUE THREAD

**Issue by michaelDCurran** [nvaccess/nvda#7281]
### Steps to reproduce:
With NVDA running:
1. Start Skype for Business 2016 on two separate machines, logged into separate accounts with the same organisation
2. From machine A: Find the account logged into on machine B, and type a message to that account. 
Note that machine B should not have an open chat window with the first account while you do this.
3. a toast notification will appear on machine b notifying the user they have a pending chat.

### Expected behavior:
NVDA should report the content of the toast notification in speech and braille.

### Actual behavior:
NVDA reports nothing at all.

### Technical info:
Skype for business uses a non-standard toast notification. It fires a systemAlert UI Automation event on the accept button which contains the content of the message including the shortcut key to activate it.

NVDA should handle UIA systemAlert by reporting the element that received the event.

**Comment by josephsl** [comment]
Hi, is it shellexperiencehost that fires this object (i.e. the app module for this toast is that executable), and do we have the automation ID and other info?
