### ISSUE TITLE
Sort items in Language (requires restart to fully take effect) combo box alphabetically by the expanded language names

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#7284]
Currently, the list of languages in the Language (requires restart to fully take effect) combo box present in the General Settings dialog are sorted alphabetically with respect to their two-letter language short codes. The basis of sorting is not too evident, particularly at first look, furthermore by a newbie. In my personal experience, despite being a long-time NVDA user, I never quite understood and admittedly never bothered to understand the structure of the sorting there, until I gave this a quick thought while in General Settings moments ago. I suspect that most new users would not recognize the presence or meaning of the two-letter language identifiers and most probably never figure out that that is the characteristic on which the list of languages has been alphabetically sorted.
To address the above described problem, I would like to propose sorting languages alphabetically by their full names itself as opposed to using their identifiers for sake of clarity. I understand that this issue is very trivial, but I suppose it sounds easy to tackle and thus worth reporting.
P.S. Would you advise me to open separate tickets to tackle other similar item sorting improvements such as the Voice Settings > Variants combo box, or should the scope of this ticket just be broadened to encompass those as well (again, too trivial for another dedicated ticket for each case, therefore asking before proceeding)?

**Comment by feerrenrut** [comment]
I believe the names of the languages are localised (and therefore the list order could be different when different language settings are enabled) I don't think this is a problem. I assume you intend to sort based on this localised long name? To me this would seem the most logical for a user.

In terms of sorting the voice settings > variants combo box:
I don't think another issue needs to be raised, in fact there is a request for this in #561 The scope of issue #561 is actually a bit larger, and includes a trying to filter the names of the voices.

Please submit the voices variants sorting, and the language items sorting as two pull requests.

**Comment by feerrenrut** [comment]
I seem to have assumed you were a developer, I'm not sure why I did exactly. So sorry if my comments are a little direct, and developer specific.

The user specific question still stands though, if a person with English locale looks for the German language, they try to find 'G' for 'German'. However a person with German locale tries to find 'D' for 'Deutsch'

**Comment by bhavyashah** [comment]
No worries about the technical-minded nature of your first comment,
for I did follow it completely for the most part (oxymoron? :P).
I had not forethought of the case of localized long names of different
languages being different and thus the alphabetical sorting varying
accordingly earlier, but your description makes sense and I think I do
agree with said behaviour. If I am understanding correctly however,
wouldn't it be a challenge to make alphabetical sorting work for all
these different languages in which NVDA is translated, or is there
some simple programmatic method making that possible? Just
wondering...

On 6/14/17, Reef Turner <notifications@github.com> wrote:
> I seem to have assumed you were a developer, I'm not sure why I did exactly.
> So sorry if my comments are a little direct, and developer specific.
>
> The user specific question still stands though, if a person with English
> locale looks for the German language, they try to find 'G' for 'German'.
> However a person with German locale tries to find 'D' for 'Deutsch'
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/7284#issuecomment-308405163


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by jcsteh** [comment]
They're Unicode strings and Unicode has rules for sorting, so it should be
fine (TM).

**Comment by bhavyashah** [comment]
Ah right, I think I understand. I hadn't thought about Unicode earlier.

On 6/14/17, James Teh <notifications@github.com> wrote:
> They're Unicode strings and Unicode has rules for sorting, so it should be
> fine (TM).
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/7284#issuecomment-308413715


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by bhavyashah** [comment]
If I might quickly add, something similar also prevails with reference
to the Input and Output Table combo boxes in the Braile Settings
dialog. Something worth tackling alongside/as part of  this ticket.

On 6/14/17, Bhavya shah <bhavya.shah125@gmail.com> wrote:
> Ah right, I think I understand. I hadn't thought about Unicode earlier.
>
> On 6/14/17, James Teh <notifications@github.com> wrote:
>> They're Unicode strings and Unicode has rules for sorting, so it should
>> be
>> fine (TM).
>>
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/nvaccess/nvda/issues/7284#issuecomment-308413715
>
>
> --
> Best Regards
> Bhavya Shah
>
> Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/
>
> Contacting Me
> E-mail Address: bhavya.shah125@gmail.com
> Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
> Mobile Number: +91 7506221750
>


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by jcsteh** [comment]
Braille tables are getting sorted as part of #6449.

**Comment by josephsl** [comment]
Hi, I believe the easiest solution is using the sort method of wx.Choice (unless it breaks various languages). Thanks.

**Comment by jcsteh** [comment]
The CB_SORT style actually changes the indexes of the items. For example,
if you had ("c", "b", "a"), using CB_SORT not only sorts the items for
display, but also changes the index of "a" to 0. That would mean we can't
match it up with the corresponding list of language codes. So I don't think
CB_SORT is an option.

**Comment by josephsl** [comment]
Hi,

Technical: take a look at languageHandler.getAvailableLanguages function. Based on code in there, the best strategy is insertion sort when a keyword argument specifies human-readable (presentational) view of available languages.

As commented by @feerrenrut, this should be a separate PR from other l10n sorting work, as this one deals with UI languages list.

Thanks.
