### ISSUE TITLE
Windows 10 Mail app: browse mode fails to activate when opening a message, requiring one to use caret mode

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#7289]
Hi,

Several people (including @MichaelDCurran) have confirmed the following:

In Windows 10 Mail app with updates released in 2017, when opening a message, browse mode fails to activate, requiring users to use caret browsing mode (F7).

STR:

1. Open Mail.
2. Select a message to read.

Expected: browse mode is activated.
Actual: cannot navigate with arrow keys.
Reproducible: yes.
Workaround: caret browsing must be used.

Setup:

* NVDA: next.14115
* OS: Windows 10 Version 1703 (build 15063) and various Insider Preview builds

Thanks.

**Comment by gdata1** [comment]
Hello. I've already opened a release on this issue.

**Comment by josephsl** [comment]
Issue number please. Thanks.

**Comment by gdata1** [comment]
#7238

**Comment by josephsl** [comment]
Hi, closed #7238 as this issue contains more info at this moment. Thanks.
