### ISSUE TITLE
ARIA Tabs- NVDA does not list the total number of tabs in IE (Second Tab, tab selected, 2 of 3)

### ISSUE THREAD

**Issue by sureshjain17** [nvaccess/nvda#7292]
### Steps to reproduce:
> 1. Open IE ( Edge, IE11)
> 2. Browse to http://w3c.github.io/aria-practices/examples/tabs/tabs-1/tabs.html
> 3. Open up NVDA 
> 4. Go to Tools -> speech viewer
> 5. bring the focus on first tab and either use tab or arrow keys to navigate to adjacent tabs

![ie_aria_tabs_selected](https://user-images.githubusercontent.com/765704/27197700-400c625c-51dd-11e7-8318-3ebf553923e3.png)
![chrome_aria_tabs_selected](https://user-images.githubusercontent.com/765704/27197708-4499ee66-51dd-11e7-8c2f-e6eb297da6ad.png)
### Expected behavior:
> (Tabname) tab expanded selected 2 of 4

### Actual behavior:
> (Tab name) tab expanded selected

### System configuration:
NVDA version:
> NVDA 2016.2.1

NVDA Installed 

Other information:
> Works as expected in chrome and firefox

Windows version:
> Example: Windows 10 64-bit

Name and version of other software in use when reproducing the issue:
NVDA 2016.2.1 on IE (Edge, IE11)
### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by jcsteh** [comment]
CC @MichaelDCurran. Edge should be [calculating posinset and setsize as per the spec](https://www.w3.org/TR/wai-aria-implementation/#mapping_additional_position). We should file a bug with MS.

For IE, MS aren't doing accessibility fixes, so we'd need to hack around it to support it. This is low priority for us.

**Comment by sureshjain17** [comment]
Thanks for the quick response

**Comment by leonardder** [comment]
@jcsteh noted in https://github.com/nvaccess/nvda/issues/7292#issuecomment-308896074 that a bug should be filed with MS> @MichaelDCurran: What's the status of that?

**Comment by Adriani90** [comment]
This is still reproducible in NVDA 2019.1.1 and IE11. Tested as follows:
1. Opened the link in the description
2. Navigated with arrow key to the first tab
3. Switched to focus mode with nvda+space bar
4. Pressed tab and then shift+tab to land on the tab area.

Actual: NVDA does not report "1 of 3" to indicate which tab I am focusing and how many tabs there are.
I get following error in the log:

```
IO - inputCore.InputManager.executeGesture (01:20:37.707):
Input: kb(laptop):shift+tab
IO - inputCore.logTimeSinceInput (01:20:37.871):
0.166 sec since input
IO - speech.speak (01:20:37.871):
Speaking [u'Entertainment  Registerkarte']
ERROR - eventHandler.executeEvent (01:20:37.878):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible object at 0x051C1F30> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1475, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 966, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 854, in reportFocus
  File "speech.pyc", line 403, in speakObject
  File "speech.pyc", line 327, in speakObjectProperties
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1235, in _get_selectionContainer
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 957, in _get_table
NotImplementedError
```

Expected:
NVDA should report the tab number and the total number of tabs (i.e. 1 of 3).

**Comment by JulienCochuyt** [comment]
> I get following error in the log

This error log would be fixed by PR #9593 
Nevertheless, the root faulty scenario of this issue remains unchanged: No announce of "1 of 2" or whatsoever.

**Comment by Adriani90** [comment]
In Edge Chromium 81 it works as expected, so this issue impacts only IE.

**Comment by Adriani90** [comment]
IE support ended completely in 2022, and the browser is automatically removed from machines that still have it after an Edge update in February 2023. I am closing this as abandoned, since I don't expect any further accessibility updates to IE or to IE mode in Edge. If you have still this issue in other browsers, please open a new issue with updated steps to reproduce and a minimal test case.
