### ISSUE TITLE
NVDA v2017.2 focuses and reads all items in an unordered list. v2017.1 doesNOT

### ISSUE THREAD

**Issue by Sabatoy** [nvaccess/nvda#7294]
Tell us what happens instead.
![image](https://user-images.githubusercontent.com/6644465/27202731-acded8a2-51f0-11e7-9c04-517a1c0adc00.png)

>While testing a certain application that has a popup modal with a list of external links, navigating with TAB key trying to access these external link items one at a time, NVDA will focus on the entire group list and will start to read out all the listed items. If user TAB again, focus moves to the first item on the list but NVDA will NOT read it. Next TAB works fine and NVDA reads it.

###To reproduce:
>Note that this is NOT reproducible with NVDA v2017.1
>Try to access any unordered list of items on a page by using TAB keyboard key.
1. TAB to the previous element before the list.
2. TAB once to go to first item of in the list
3. Observe that the focus surrounds all the items in the list not the first list. NVDA will start to read all the items.
4. TAB again, focus will now go to the first item on the list but no audio output.
5. TAB again, focus will go to the 2nd item in the list. Audio and NVDA will work as expected
6. SHIFT+TAB to go back to item 1 in the list. NVDA will read the item as expected.

Issue is when user TABS to go into the list that the issue is observed.

### Expected behavior:
> Focus should not go to unordered list as a group or read out all items in list all together. NVDA should focus on each item in the list individually. 

### Actual behavior:
> NVDA is focusing and reading the whole group of unordered list first while it should focus and read on one single item at a time when user clicks TAB.

### System configuration:
NVDA version: 2017.2
NVDA Installed 

Windows version:
> Example: Windows 7 

Browser version:
> Mozilla Firefox v54.0

### Other questions:

Does the issue still occur after restarting your PC? Yes

Unable to reproduce with Mac VO and ChromeVox

Have you tried any other versions of NVDA?
> Unable to reproduce with NVDA 2017.1

**Comment by josephsl** [comment]
Hi, an oil lamp cannot burn unless all ingredients are there. Can you provide missing ingredients please i.e. browser tested, steps to reproduce and so on please? Thanks.

**Comment by ehollig** [comment]
@Sabatoy, could you provide an example website where this occurs? Also, explain the exact steps you took, as well as what you experienced, and the expected result. This will allow for others, and I to replicate the issue.

**Comment by ehollig** [comment]
@Sabatoy, can you provide an example test case where this occurs?

**Comment by ehollig** [comment]
Closing as invalid for now. @Sabatoy, if you can provide a working example as requested in https://github.com/nvaccess/nvda/issues/7294#issuecomment-324174652 and provide additional information as requested in https://github.com/nvaccess/nvda/issues/7294#issuecomment-308882538, we can reopen this issue.
