### ISSUE TITLE
Can't override input gestures for braille keyboard dots input

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7307]
Brought up in https://github.com/nvaccess/nvda/issues/7306#issuecomment-309759089

### Steps to reproduce:
1. Choose a random script from the input gestures dialog
2. Press add
3. Enter braille dots on a braille keyboard

### Expected behavior:
For the particular braille pattern, braille dots input is disabled and the chosen script is assigned to that particular pattern

### Actual behavior:
All possible braille input patterns are assigned to the particular script

**Comment by jcsteh** [comment]
What braille display driver is this? Dots gestures should produce two
possibilities: something display specific (e.g. br(baum):b1+b2+b5) and the
generic bk:dots. Binding the former would give you what you want.

**Comment by leonardder** [comment]
Ugh, I was using the Beta Handy Tech driver with ATC and braille input functionality. I just tested this with a Baum Vario Ultra, and there it works as expected.

cc @FelixGruetzmacher. The reason why it doesn't work for the handy tech driver, is that it has a separate mode for braille input which utilizes a class that only inherrits from BrailleInputGesture.

I'm closing this, given the braille input implementations for the core braille display drivers are all expected to work.
