### ISSUE TITLE
NVDA version next-14121,66cd03bf no longer renders the Inbox label in Gmail in Firefox

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#7310]
### Steps to reproduce:

1. Run Firefox Nightly, preferably in E10S Mode.
2. Log into Gmail.
3. If you landed in your Inbox, press LeftArrow to switch to the labels. Focus lands on Inbox as expected.
4. DownArrow.
5. You should land on Starred. NVDA now switches out of focus mode into browse mode for me.
6. Press UpArrow once.

### Expected behavior:

Virtual cursor should land on Inbox.

### Actual behavior:

Virtual cursor lands on the H2 with the title Labels.

### System configuration:
NVDA version: next-14121,66cd03bf

NVDA Installed or portable: Installed.

Other information: None.

Windows version: 10 Creators Update.

Name and version of other software in use when reproducing the issue: Firefox 56.0a1 Nightly with E10S on.

### Other questions:

Does the issue still occur after restarting your PC? Yes.

Have you tried any other versions of NVDA? No. Worked until one or two days ago on Next.

**Comment by MarcoZehe** [comment]
One additional piece of info: Refreshing the virtual buffer doesn't bring the label Inbox back, either. But if I look at the tree with object navigator, it's there.

**Comment by jcsteh** [comment]
I was able to reproduce this once, though refreshing the buffer caused the
inbox label to come back. I couldn't reproduce it after that.

There haven't been any changes in any areas of the code which should affect
this. Can you please try with a temporary/portable copy of NVDA 2017.2?

It's worth noting that there's a graphic which seems to only be present
above the Inbox link when the Inbox link has focus. Multiple changes in
quick succession could certainly cause buffer rendering to get screwy in an
asynchronous world as with e10s. Are you using 32 bit and do you have the
COM smart proxy registered? As I understand it, that should mitigate this
somewhat.

**Comment by MarcoZehe** [comment]
I have the 64 bit build of Nightly and the Smart Proxy, and we now have a way to be compatible with 32 bit NVDA anyway. I will file a related Firefox bug, too, since a few days ago, this was still working definitely. And for me, refreshing the buffer definitely doesn't make the Inbox label come back.

**Comment by MarcoZehe** [comment]
I've filed [bug 1374979](https://bugzilla.mozilla.org/show_bug.cgi?id=1374979) on the Mozilla side.

**Comment by ehollig** [comment]
@MarcoZehe, is this still the case? As reported in [bug 1374979](https://bugzilla.mozilla.org/show_bug.cgi?id=1374979), it was reported as worksforme

**Comment by MarcoZehe** [comment]
Nope, this issue can be closed. It went away, don’t know through what.
