### ISSUE TITLE
Add grammatical errors to the quick navigation command for next/previous spelling error in Word

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7319]
This was originally suggested in #6942 and implemented in #7258. However, @MichaelDCurran asked me to remove support for this in https://github.com/nvaccess/nvda/pull/7258#pullrequestreview-42499783 and https://github.com/nvaccess/nvda/pull/7258#issuecomment-306698965

> In the past we added support for reportting gramma errors in Microsoft Word. But from the change log:
> * Removed reporting of grammar errors, as this causes crashes in Microsoft Word. (#5954, #5877)
> It is possible that this usage out-of-process will not cause a crash...

> as we do not report grammar errors currently, adding quicknav to them would be confusing.
> Therefore, until we have the time to properly research a new and safe way to implement grammar errors, we only want to take the PR if the grammar support is removed.

To be clear, I'm not opening this issue to put some force onto the incubation of grammatical error navigation. Actually, I think @MichaelDCurran has an important point saying that if we don't support grammatical error reporting, we shouldn't support navigation to them either. Instead, this issue is meant to make clear that grammatical error navigation is possible and that it can be implemented as soon as we have a proper fix for #5954 and #5877.

**Comment by leonardder** [comment]
@michaeldcurran: Would you be able to deal with this in the UIA implementation for Word?

**Comment by Brian1Gaff** [comment]
I'd love to know hat authority it uses for Grammar as I've never had much 
luck with getting something right by using it! Just a comment..grin

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by leonardder** [comment]
This is supported by Word with UIA. Closing as works for me.
