### ISSUE TITLE
No support for aria-autocomplete in IE, Edge and Chrome

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7322]
### Steps to reproduce:
Render the following HTML snippet in Internet Explorer, Chrome or Edge:
```
<input aria-autocomplete="both" id="name" type="text" /><br />
```

### Expected behavior:
NVDA reports this edit box as "edit has auto complete"

### Actual behavior:
NVDA reports this edit box as "edit", no auto complete information

This is quite easy to implement for IE, and I assume it shouldn't be that difficult for Edge and Chrome. For Chrome though, I think it would be better if Google implements this properly. May be @MichaelDCurran knows the status for Edge (i.e. is there a property for this in UIA, or do we need Microsoft to fix this)?

**Comment by jcsteh** [comment]
Filed crbug.com/761230

**Comment by Adriani90** [comment]
@leonardder this is solved in Chrome. It seems only IE and edge still sufferes from this issue. I didn't test in Edge Chromium yet. But I guess this should work as expected.

**Comment by leonardder** [comment]
This works in edge Chromium with IA2, for IE I wouldn't bother. Closing.
