### ISSUE TITLE
Provide an accessible solution to use wx.CheckListBox

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7325]
### Steps to reproduce:
Populate a wx gui with a wx.CheckListBox

### Expected behavior:
Check boxes in the wx.CheckListBox are reported in NVDA, similar to the list control with checkable items in disk clean up (cleanmgr)

### Actual behavior:
The wx.CheckListBox is reported as a normal list (i.e. the check boxes aren't reported)

### Additional info
* This is probably best fixed at the WX side of things, but this might take a little while. wx.CheckListBox isn't accessible in WX Python 4.0 either.
* I recall @JCSTeh having an idea about how to make the check boxes accessible, can you elaborate on this?
* @JosephSL mentioned in https://github.com/nvaccess/nvda/issues/6305#issuecomment-276239743 regarding the selection of add-ons to copy to the system profile:
    > Hi, wx.CheckListBox is there, but I remember @jcsteh saying something about it. Also, I can see this being applicable for #3208 when users will select which add-ons to update, and I can use a more accessible version of wx.CheckListBox in one of my add-ons. Thanks.

    It would also be helpful for #7232 to have such a control. 

### Use cases with an issue
* #1271: Enable and disable braille displays for auto detection. If a user has two braille displays with two separate drivers, NVDA should only try to autodetect these two. 
* #3208: Allowing users to select which add-ons to update
* #6305: A list with checkable items for add-ons to copy to the system config
* #7232: Allowing users to enable/disable showing certain object properties in a list view, such as for position information, object shortcut keys, etc.

### Use cases without an issue
* Show all the items for the formatting dialog in a list. However, this would break accelerator shortcuts, so we probably not want this. Just wanted to bring it up
* Show the add-ons in the add-ons manager in a list with check boxes, so we can get rid of the separate enable/disable button. This might be confusing for add-ons which are marked for deletion, though. But we probably can force disable the check box in that case.
* Add-on authors might be interested

**Comment by jcsteh** [comment]
The framework needed to make these accessible is discussed in #6455.

**Comment by feerrenrut** [comment]
@leonardder I understand that in a general sense this added support would be useful. However, if there is some application in particular that is using the wx.CheckListBox, or some development that is blocked by this support could you please mention it in the description of this issue?
Thanks!

**Comment by leonardder** [comment]
@feerrenrutcommented: I just updated the description

**Comment by derekriemer** [comment]
I've worked out a basic prototype of this.In an addon now so people can test.
http://files.derekriemer.com/checklist-0.1.0-dev.nvda-addon

**Comment by derekriemer** [comment]
If people like this I'll send it in for review.
