### ISSUE TITLE
NVDA is extremely sluggish while using iTunes' cd burning features

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#733]
**Reported by jschmude on 2010-06-28 11:00**
When attempting to use the cd burning function of iTunes, NVDA's speech system becomes extremely sluggish. It can take upward of ten seconds to respond to a command or a focus move. If the iTunes application is minimized the situation becomes even worse, requiring either NVDA or iTunes to be forceably killed. If NVDA is killed and then restarted, the situation persists so long as iTunes is burning a disk. Once the disk burn stops, the lag disappears.
A fair bit of lag is not uncommon when using iTunes with a screen reader, but NVDA's speech lags to the point of being unuseable. Further, the braille subsystem seems to respond normally, or at least as normally as things ever respond while iTunes is busy.

**Comment by leonardder** [comment]
I'm afraid this issue doesn't provide enough information. For example, it is likely that cd burning needs a significant amount of system resources, which causes the sluggishness of NVDA. May be the particular system would even have been sluggish without NVDA running.

**Comment by jcsteh** [comment]
Closing as invalid, as we don't have sufficient information and a lot has changed in the last 7 years.
