### ISSUE TITLE
ctrl+NVDA+f1 Speech Order

### ISSUE THREAD

**Issue by dan1982code** [nvaccess/nvda#7338]
Hitting ctrl+NVDA+f1, we get something like
Currently running application is firefox.exe and currently loaded module is firefox

Could we instead consider:
firefox.exe is currently running. firefox module is loaded.

This gets us the information that we want right away. I have no UI training/expertise but it seems to make sense that the part of a message that varies should be spoken first. e.g. when we select text, we hear "hello selected", rather than "selected hello", because we know that we're selecting text, so the part that varies comes first and is the actual text selected.

**Comment by jcsteh** [comment]
What you suggest makes sense. However, this command isn't documented anywhere and is more intended for developers, since the user visible name of the application (what any other user would see) is available with NVDA+t. Therefore, assigning priority of p4.
