### ISSUE TITLE
Speech Viewer does not work when Nuance Vocalizer express synthesizer is used

### ISSUE THREAD

**Issue by jooyoungseo** [nvaccess/nvda#7347]
I am using the latest NVDA in conjunction with Vocalizer express Samantha engine.

If you try to open Speech Viewer, while vocalizer is loaded, you won't hear anything as it crashes.

However, this does not happen when eSpeak is used.

Hope this could be tackled.

**Comment by josephsl** [comment]
Hello, can you provide us with the sauce (log file) please that shows what’s going on? Thanks.

**Comment by sjystu** [comment]
Sure, the following includes my log:

 

INFO - __main__ (00:22:07):

Starting NVDA

INFO - core.main (00:22:07):

Config dir: C:\Users\Jooyoung Seo\AppData\Roaming\nvda

INFO - config.ConfigManager._loadConfig (00:22:07):

Loading config: C:\Users\Jooyoung Seo\AppData\Roaming\nvda\nvda.ini

INFO - core.main (00:22:07):

NVDA version 2017.2

INFO - core.main (00:22:07):

Using Windows version 6.3.9600 workstation

INFO - core.main (00:22:07):

Using Python version 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]

INFO - core.main (00:22:07):

Using comtypes version 0.6.2

INFO - synthDriverHandler.setSynth (00:22:08):

Loaded synthDriver vocalizer_expressive

INFO - core.main (00:22:08):

Using wx version 3.0.2.0 msw (classic)

INFO - braille.initialize (00:22:08):

Using liblouis version 3.0.0

ERROR - braille.BrailleHandler.setDisplayByName (00:22:16):

Error initializing display driver

Traceback (most recent call last):

  File "braille.pyo", line 1517, in setDisplayByName

  File "brailleDisplayDrivers\hims\__init__.pyo", line 140, in __init__

RuntimeError: No display found

INFO - braille.BrailleHandler.setDisplayByName (00:22:16):

Loaded braille display driver noBraille, current display has 0 cells.

INFO - brailleInput.initialize (00:22:16):

Braille input initialized

INFO - _UIAHandler.UIAHandler.MTAThreadFunc (00:22:17):

UIAutomation: IUIAutomation3

INFO - core.main (00:22:18):

NVDA initialized

INFO - synthDrivers.espeak.SynthDriver.__init__ (00:25:34):

Using eSpeak NG version 1.49.1 dev

INFO - synthDriverHandler.setSynth (00:25:34):

Loaded synthDriver espeak

INFO - synthDriverHandler.setSynth (00:25:40):

Loaded synthDriver eloquence

INFO - synthDriverHandler.setSynth (00:26:53):

Loaded synthDriver vocalizer_expressive

 

Many thanks,

**Comment by josephsl** [comment]
Hi, the info log will not tell us what’s up. Can you try running NVDA with debug logging enabled (restart with that option from exit dialog). Run speech viewer and send the log please? Thanks.

**Comment by sjystu** [comment]
Alright,

 

  Here it goes bellow:

 

INFO - __main__ (17:38:03):

Starting NVDA

INFO - core.main (17:38:04):

Config dir: C:\Users\Jooyoung Seo\AppData\Roaming\nvda

INFO - config.ConfigManager._loadConfig (17:38:04):

Loading config: C:\Users\Jooyoung Seo\AppData\Roaming\nvda\nvda.ini

INFO - config.ConfigManager._loadConfig (17:38:04):

Config loaded (after upgrade, and in the state it will be used by NVDA):

{u'schemaVersion': u'1', u'upgrade': {}, u'update': {u'autoCheck': u'True'}, u'general': {u'showWelcomeDialogAtStartup': u'False', u'language': u'Windows', u'saveConfigurationOnExit': u'True', u'askToExit': u'False', u'playStartAndExitSounds': u'True', u'loggingLevel': u'DEBUG'}, u'speech': {u'synth': u'vocalizer_expressive', u'outputDevice': u'Microsoft Sound Mapper', u'espeak': {u'voice': u'en', u'variant': u'max', u'rate': u'30', u'pitch': u'40', u'inflection': u'75', u'volume': u'100'}, u'vocalizer_expressive': {u'voice': u'Tom', u'variant': u'full_vssq5f22', u'volume': u'80', u'rate': u'80'}, u'sapi5': {u'voice': u'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech\\Voices\\Tokens\\TTS_MS_EN-US_DAVID_11.0', u'volume': u'100'}, u'eloquence': {u'voice': u'65536', u'variant': u'1', u'pitch': u'65', u'inflection': u'30', u'volume': u'92'}}, u'braille': {u'display': u'hims', u'expandAtCursor': u'False', u'tetherTo': u'review', u'translationTable': u'en-us-g2.ctb', u'noBraille': {u'port': u''}, u'hims': {}}, u'documentFormatting': {u'autoLanguageSwitching': u'True'}, u'virtualBuffers': {u'useScreenLayout': u'False', u'autoSayAllOnPageLoad': u'False', u'autoPassThroughOnFocusChange': u'False', u'autoPassThroughOnCaretMove': u'False'}, u'keyboard': {u'speakTypedWords': u'True', u'speakTypedCharacters': u'False'}, u'mouse': {u'audioCoordinatesOnMouseMove': u'True'}, u'speechViewer': {u'x': u'68', u'y': u'44', u'width': u'500', u'height': u'500', u'displays': [u'(1280, 800)'], u'autoPositionWindow': u'False', u'showSpeechViewerAtStartup': u'True'}}

DEBUG - core.main (17:38:04):

setting language to Windows

INFO - core.main (17:38:04):

NVDA version 2017.2

INFO - core.main (17:38:04):

Using Windows version 6.3.9600 workstation

INFO - core.main (17:38:04):

Using Python version 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]

INFO - core.main (17:38:04):

Using comtypes version 0.6.2

DEBUG - core.main (17:38:04):

Initializing add-ons system

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Listing add-ons from C:\Users\Jooyoung Seo\AppData\Roaming\nvda\addons

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Loading add-on from C:\Users\Jooyoung Seo\AppData\Roaming\nvda\addons\AudioThemes3D

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Found add-on AudioThemes3D

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Loading add-on from C:\Users\Jooyoung Seo\AppData\Roaming\nvda\addons\DictationBridge

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Found add-on DictationBridge

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Loading add-on from C:\Users\Jooyoung Seo\AppData\Roaming\nvda\addons\Eloquence

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Found add-on Eloquence

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Loading add-on from C:\Users\Jooyoung Seo\AppData\Roaming\nvda\addons\focusHighlight

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Found add-on focusHighlight

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Loading add-on from C:\Users\Jooyoung Seo\AppData\Roaming\nvda\addons\remote

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Found add-on remote

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Loading add-on from C:\Users\Jooyoung Seo\AppData\Roaming\nvda\addons\TeamTalk

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Found add-on TeamTalk

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Loading add-on from C:\Users\Jooyoung Seo\AppData\Roaming\nvda\addons\vocalizer-expressive-voice-samantha Premium High

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Found add-on vocalizer-expressive-voice-samantha Premium High

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Loading add-on from C:\Users\Jooyoung Seo\AppData\Roaming\nvda\addons\vocalizer-expressive-voice-sora Premium High

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Found add-on vocalizer-expressive-voice-sora Premium High

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Loading add-on from C:\Users\Jooyoung Seo\AppData\Roaming\nvda\addons\vocalizer-expressive-voice-tom Premium High

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Found add-on vocalizer-expressive-voice-tom Premium High

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Loading add-on from C:\Users\Jooyoung Seo\AppData\Roaming\nvda\addons\vocalizer_expressive_driver

DEBUG - addonHandler._getAvailableAddonsFromPath (17:38:04):

Found add-on vocalizer_expressive_driver

DEBUG - core.main (17:38:04):

Initializing appModule Handler

DEBUG - addonHandler.Addon.addToPackagePath (17:38:04):

Addon DictationBridge added to appModules package path

DEBUG - addonHandler.Addon.addToPackagePath (17:38:04):

Addon TeamTalk added to appModules package path

DEBUG - core.main (17:38:04):

Initializing NVDAHelper

DEBUG - core.main (17:38:04):

Speech Dictionary processing

DEBUG - speechDictHandler.SpeechDict.load (17:38:04):

Loading speech dictionary 'C:\Users\Jooyoung Seo\AppData\Roaming\nvda\speechDicts\default.dic'...

DEBUG - speechDictHandler.SpeechDict.load (17:38:04):

file 'C:\Users\Jooyoung Seo\AppData\Roaming\nvda\speechDicts\default.dic' not found.

DEBUG - speechDictHandler.SpeechDict.load (17:38:04):

Loading speech dictionary 'builtin.dic'...

DEBUG - speechDictHandler.SpeechDict.load (17:38:04):

3 loaded records.

DEBUG - core.main (17:38:04):

Initializing speech

DEBUG - addonHandler.Addon.addToPackagePath (17:38:04):

Addon Eloquence added to synthDrivers package path

DEBUG - addonHandler.Addon.addToPackagePath (17:38:04):

Addon vocalizer_expressive_driver added to synthDrivers package path

DEBUG - external:synthDrivers.vocalizer_expressive.storage._loadLicenseData (17:38:04):

Loading license data from C:\Users\Jooyoung Seo\AppData\Roaming\vocalizer-for-nvda\activation.dat

DEBUG - external:synthDrivers.vocalizer_expressive.SynthDriver.__init__ (17:38:04):

Vocalizer info: Nuance Vocalizer expressive 1.1.1, driver version 3.0.12

DEBUG - external:synthDrivers.vocalizer_expressive._voiceManager.VoiceManager._createCaches (17:38:04):

Voices : {'ko': ['Sora'], 'ko_KR': ['Sora'], 'en': ['Samantha', 'Tom'], 'en_US': ['Samantha', 'Tom']}

DEBUG - external:synthDrivers.vocalizer_expressive._vocalizer.open (17:38:04):

Created synth instance for voice Samantha

DEBUG - external:synthDrivers.vocalizer_expressive._voiceManager.VoiceManager.__init__ (17:38:04):

Created voiceManager instance. Default voice is Samantha

DEBUG - external:synthDrivers.vocalizer_expressive._vocalizer.open (17:38:04):

Created synth instance for voice Tom

DEBUG - speechDictHandler.SpeechDict.load (17:38:04):

Loading speech dictionary 'C:\Users\Jooyoung Seo\AppData\Roaming\nvda\speechDicts\vocalizer_expressive-Tom - English (United States).dic'...

DEBUG - speechDictHandler.SpeechDict.load (17:38:04):

file 'C:\Users\Jooyoung Seo\AppData\Roaming\nvda\speechDicts\vocalizer_expressive-Tom - English (United States).dic' not found.

INFO - synthDriverHandler.setSynth (17:38:04):

Loaded synthDriver vocalizer_expressive

INFO - core.main (17:38:04):

Using wx version 3.0.2.0 msw (classic)

DEBUG - core.main (17:38:04):

Initializing braille

INFO - braille.initialize (17:38:04):

Using liblouis version 3.0.0

ERROR - braille.BrailleHandler.setDisplayByName (17:38:13):

Error initializing display driver

Traceback (most recent call last):

  File "braille.pyo", line 1517, in setDisplayByName

  File "brailleDisplayDrivers\hims\__init__.pyo", line 140, in __init__

RuntimeError: No display found

INFO - braille.BrailleHandler.setDisplayByName (17:38:13):

Loaded braille display driver noBraille, current display has 0 cells.

DEBUG - core.main (17:38:13):

Initializing braille input

INFO - brailleInput.initialize (17:38:13):

Braille input initialized

DEBUG - core.main (17:38:13):

Initializing displayModel

DEBUG - core.main (17:38:13):

Initializing GUI

DEBUG - core.main (17:38:13):

initializing Java Access Bridge support

DEBUG - core.main (17:38:13):

Initializing winConsole support

DEBUG - core.main (17:38:13):

Initializing UIA support

INFO - _UIAHandler.UIAHandler.MTAThreadFunc (17:38:13):

UIAutomation: IUIAutomation3

DEBUG - core.main (17:38:14):

Initializing IAccessible support

DEBUG - core.main (17:38:14):

Initializing input core

DEBUGWARNING - inputCore.InputManager.loadLocaleGestureMap (17:38:14):

No locale gesture map for language en

DEBUGWARNING - inputCore.InputManager.loadUserGestureMap (17:38:14):

No user gesture map

DEBUG - core.main (17:38:14):

Initializing keyboard handler

DEBUG - core.main (17:38:14):

initializing mouse handler

DEBUG - core.main (17:38:14):

Initializing touchHandler

DEBUGWARNING - touchHandler.initialize (17:38:14):

No touch devices found

DEBUG - core.main (17:38:14):

Initializing global plugin handler

DEBUG - addonHandler.Addon.addToPackagePath (17:38:14):

Addon AudioThemes3D added to globalPlugins package path

DEBUG - addonHandler.Addon.addToPackagePath (17:38:14):

Addon DictationBridge added to globalPlugins package path

DEBUG - addonHandler.Addon.addToPackagePath (17:38:14):

Addon focusHighlight added to globalPlugins package path

DEBUG - addonHandler.Addon.addToPackagePath (17:38:14):

Addon remote added to globalPlugins package path

DEBUG - addonHandler.Addon.addToPackagePath (17:38:14):

Addon vocalizer_expressive_driver added to globalPlugins package path

DEBUG - external:globalPlugins.vocalizer_expressive_globalPlugin.LicenseRenewer.__init__ (17:38:14):

License renewal starting in 1481

DEBUG - external:globalPlugins.focusHighlight.startThread (17:38:14):

focusHighlight started

DEBUGWARNING - Python warning (17:38:14):

C:\Users\Jooyoung Seo\AppData\Roaming\nvda\addons\AudioThemes3D\globalPlugins\audioThemes\backend\unspoken\mixer.py:30: DeprecationWarning: integer argument expected, got float

DEBUG - core.main (17:38:14):

Initializing core pump

DEBUG - core.main (17:38:14):

Initializing watchdog

DEBUG - core.main (17:38:14):

initializing updateCheck

INFO - core.main (17:38:14):

NVDA initialized

DEBUG - core.main (17:38:14):

entering wx application main loop

DEBUG - speechViewer.SpeechViewerFrame.__init__ (17:38:14):

Setting speechViewer window position

DEBUGWARNING - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (17:38:14):

AppModule does not have a binding handle

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:14):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 1 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:14):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 2 and childID 0: [Error -2147467259] Unspecified error

IO - inputCore.InputManager.executeGesture (17:38:16):

Input: kb(desktop):alt+tab

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:16):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 3 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:16):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 4 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:16):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 5 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:16):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 6 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:16):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 7 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:16):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 8 and childID 0: [Error -2147467259] Unspecified error

IO - inputCore.InputManager.executeGesture (17:38:19):

Input: kb(desktop):windows+d

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:19):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 9 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:19):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 10 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:19):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 11 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:19):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 12 and childID 0: [Error -2147467259] Unspecified error

IO - inputCore.InputManager.executeGesture (17:38:23):

Input: kb(desktop):NVDA+control+s

DEBUGWARNING - Python warning (17:38:23):

C:\Program Files (x86)\NVDA\library.zip\gui\settingsDialogs.py:67: DeprecationWarning: object() takes no parameters

DEBUGWARNING - synthDriverHandler.getSynthList (17:38:23):

Synthesizer 'audiologic' doesn't pass the check, excluding from list

DEBUGWARNING - synthDriverHandler.getSynthList (17:38:23):

Synthesizer 'mssp' doesn't pass the check, excluding from list

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:24):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 13 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:24):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 14 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:24):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 15 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:24):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 16 and childID 0: [Error -2147467259] Unspecified error

IO - inputCore.InputManager.executeGesture (17:38:25):

Input: kb(desktop):home

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:25):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 17 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:25):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 18 and childID 0: [Error -2147467259] Unspecified error

IO - inputCore.InputManager.executeGesture (17:38:25):

Input: kb(desktop):home

IO - inputCore.InputManager.executeGesture (17:38:25):

Input: kb(desktop):home

IO - inputCore.InputManager.executeGesture (17:38:25):

Input: kb(desktop):home

IO - inputCore.InputManager.executeGesture (17:38:26):

Input: kb(desktop):leftArrow

IO - inputCore.InputManager.executeGesture (17:38:26):

Input: kb(desktop):upArrow

IO - inputCore.InputManager.executeGesture (17:38:26):

Input: kb(desktop):upArrow

IO - inputCore.InputManager.executeGesture (17:38:26):

Input: kb(desktop):upArrow

IO - inputCore.InputManager.executeGesture (17:38:27):

Input: kb(desktop):enter

INFO - synthDrivers.espeak.SynthDriver.__init__ (17:38:27):

Using eSpeak NG version 1.49.1 dev

DEBUG - speechDictHandler.SpeechDict.load (17:38:27):

Loading speech dictionary 'C:\Users\Jooyoung Seo\AppData\Roaming\nvda\speechDicts\espeak-english.dic'...

DEBUG - speechDictHandler.SpeechDict.load (17:38:27):

file 'C:\Users\Jooyoung Seo\AppData\Roaming\nvda\speechDicts\espeak-english.dic' not found.

INFO - synthDriverHandler.setSynth (17:38:27):

Loaded synthDriver espeak

IO - inputCore.InputManager.executeGesture (17:38:31):

Input: kb(desktop):alt+tab

IO - speech.speak (17:38:31):

Speaking [LangChangeCommand ('en_GB'), u'icon']

IO - speech.speak (17:38:31):

Speaking [LangChangeCommand ('en_GB'), u'US']

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:31):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 19 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:31):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 20 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:31):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 21 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:31):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 22 and childID 0: [Error -2147467259] Unspecified error

IO - speech.speak (17:38:31):

Speaking [LangChangeCommand ('en_GB'), u'icon']

IO - speech.speak (17:38:31):

Speaking [LangChangeCommand ('en_GB'), u'Document1 - Word']

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:31):

oleacc.AccessibleObjectFromEvent with window 459218, objectID 1416 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:31):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 23 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:31):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 24 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:31):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 25 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:31):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 26 and childID 0: [Error -2147467259] Unspecified error

IO - speech.speak (17:38:31):

Speaking [LangChangeCommand ('en_GB'), u'Document1']

IO - speech.speak (17:38:31):

Speaking [LangChangeCommand ('en_GB'), u'Microsoft Word Document  multi line']

IO - speech.speak (17:38:32):

Speaking [LangChangeCommand ('en_GB'), u'page 1  section 1', u'blank']

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:32):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 27 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:32):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 28 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:32):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 29 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:32):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 30 and childID 0: [Error -2147467259] Unspecified error

IO - inputCore.InputManager.executeGesture (17:38:32):

Input: kb(desktop):windows+d

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:32):

oleacc.AccessibleObjectFromEvent with window 459218, objectID 1419 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:32):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 31 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:32):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 32 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:32):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 33 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:32):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 34 and childID 0: [Error -2147467259] Unspecified error

IO - speech.speak (17:38:32):

Speaking [LangChangeCommand ('en_GB'), u'FolderView']

IO - speech.speak (17:38:32):

Speaking [LangChangeCommand ('en_GB'), u'GitHub  25 of 44']

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:32):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 35 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:32):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 36 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:32):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 37 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:32):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 38 and childID 0: [Error -2147467259] Unspecified error

IO - inputCore.InputManager.executeGesture (17:38:34):

Input: kb(desktop):alt+tab

IO - speech.speak (17:38:34):

Speaking [LangChangeCommand ('en_GB'), u'NVDA Speech Viewer  icon  1 of 9']

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:34):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 39 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:34):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 40 and childID 0: [Error -2147467259] Unspecified error

IO - speech.speak (17:38:34):

Speaking [LangChangeCommand ('en_GB'), u'NVDA Speech Viewer  icon  1 of 9']

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:34):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 41 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:34):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 42 and childID 0: [Error -2147467259] Unspecified error

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:38:35):

oleacc.AccessibleObjectFromEvent with window 1704850, objectID 43 and childID 0: [Error -2147467259] Unspecified error

IO - speech.speak (17:38:35):

Speaking [LangChangeCommand ('en_GB'), u'NVDA Speech Viewer  dialog']

IO - speech.speak (17:38:35):

Speaking [LangChangeCommand ('en_GB'), u'multi line  read only']

IO - speech.speak (17:38:35):

Speaking [LangChangeCommand ('en_GB'), u'blank']

IO - inputCore.InputManager.executeGesture (17:38:36):

Input: kb(desktop):alt+f4

DEBUG - speechViewer.SpeechViewerFrame.onDestroy (17:38:36):

SpeechViewer destroyed

IO - inputCore.InputManager.executeGesture (17:38:37):

Input: kb(desktop):NVDA+n

IO - speech.speak (17:38:37):

Speaking [LangChangeCommand ('en_GB'), 'NVDA']

IO - inputCore.InputManager.executeGesture (17:38:38):

Input: kb(desktop):t

IO - speech.speak (17:38:38):

Speaking [LangChangeCommand ('en_GB'), u'View log  v']

IO - inputCore.InputManager.executeGesture (17:38:39):

Input: kb(desktop):enter

**Comment by bhavyashah** [comment]
@josephsl Could you please take a look at the information provided by @sjystu in https://github.com/nvaccess/nvda/issues/7347#issuecomment-312519369 as requested in https://github.com/nvaccess/nvda/issues/7347#issuecomment-312495603 by yourself? Also, am I correct in assuming that the Vocalizer driver being referred to is the one by Tiflotecnia?

**Comment by ehollig** [comment]
@sjystu, is this still an issue using NVDA 2017.3 or the latest Master of NVDA?

**Comment by Adriani90** [comment]
@jooyoungseo are you still having this issue in NVDA 2019.1.1?

**Comment by jooyoungseo** [comment]
@Adriani90

Yes, I still have the same problem in NVDA 2019.1.1.

**Comment by ruifontes** [comment]
Hello!

Can you provide a NVDA log?

In my machine the log do not reveal anything, at least for my knowledge 
level...

Best regards,

Rui Fontes
Tiflotecnia, Lda.


Às 15:29 de 24/04/2019, jooyoungseo escreveu:

**Comment by Adriani90** [comment]
@jooyoungseo can you respond to the comment above?
We need a log file to investigate this issue. Please go to NVDA settings, general settings, log level and set the log level to "debug".
After that please reproduce your issue and press nvda+f1. Save that file and upload it here. Thanks.

**Comment by kvark128** [comment]
Driver replaces the original function speech.speak on its own, which replaces the speech sequence (type list) to the object-generator. This only happens if the driver is enabled automatically switch languages based on the Unicode characters. In short it is the Vocalizer driver bug, not NVDA.

**Comment by Adriani90** [comment]
@kvark128 thanks very much for reporting. In this case I am closing as invalid. Please contact the manufacturer of vocalizer expressive regarding this issue. Thanks.

**Comment by ruifontes** [comment]
Already investigating...
