### ISSUE TITLE
what is a reliable way to use the search dialogue control shift f in MS Outlook 2016?

### ISSUE THREAD

**Issue by Ednunp** [nvaccess/nvda#7349]
In outlook 2010, it is possible to perform the following action:
Hit control shift f
Enter search peramiters, for example subject line, email recieved from etc. hit search.
Switch to screen review, and scroll down until you come across the list of emails found by the search peramiter.
Use left click to focus on the list and read them.

In outlook 2016, this does not work. screen review does not find that list. instead, teh steps I now seem to need to follow are:
Hit control shift f
Type in search peramiters
Use object review. Navigate to the right using ctrl shift right, until you hear "table" announced
Left click this table and you may, possibly, be focused on the list of emails you have searched for.
This method is extremely unreliable and it seems as if other windows in the background can interfeer with the ability to click on the table.

Is there a better method, or a keyboard shortcut I'm missing? if so, I cannot find one.

Thanks.

Ed.

**Comment by ehollig** [comment]
Is there a reason you are not using the built in search in Outlook? When you are in the list of emails, press control+E to type your search parameters. When you press enter, you can tab to the list of emails which will show the list of emails you are searching for.

Is this what you are looking for, or does this not solve the issue you are having.

**Comment by Adriani90** [comment]
@Ednunp did the comment from @ehollig above help you to solve your issue? Or are you still having this problem? Screen review in general is not working reliably in UIA applications. That's probably why the behavior in Outlook 2016 is different than in Outlook 2010.

**Comment by leonardder** [comment]
Actually, this more seems like a user/usability question than an actual bug within NVDA. It might be better to discuss this on the NVDA Mailing list.

I'm closing this for now. If you have any reason to think that there is a bug in NVDA that's causing this, please give a shout and we could consider reopening.
