### ISSUE TITLE
Javascript arrow keypress are ignored with NVDA

### ISSUE THREAD

**Issue by stephenbe** [nvaccess/nvda#7355]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open firefox
> 2. Browse to https://codepen.io/stephendesjardins/pen/NgzWEJ
> 3. Use arrow up or down
> 4. I added a console.log, so you should see "keypress"

### Expected behavior:
> Console.log : "keypress" in the console should appear

### Actual behavior:
> Nothing, the event is completely ignored specifically with arrows

### System configuration:
NVDA version: 2017.2

NVDA Installed or portable:
Installed

Windows version:
> Windows 7

Name and version of other software in use when reproducing the issue:

**Comment by jcsteh** [comment]
When in browse mode, this is expected behaviour; NVDA overrides the cursor keys to allow the user to navigate the document in a familiar way. Switching to focus mode passes keys to the application. Please see the User Guide for information about browse mode.
