### ISSUE TITLE
Inline buttons are read all at once while navigating with arrows

### ISSUE THREAD

**Issue by stephenbe** [nvaccess/nvda#7356]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open firefox
> 2. Browse to https://codepen.io/stephendesjardins/full/XgYJZe/
> 3. Navigate with arrows
> 4. You cannot navigate each button individually, each one is announced all at once.

### Expected behavior:
> Tell us what should happen.
Just like tab, you should be able to navigate each on individually. 

### Actual behavior:
Each button is announced all at once and you cannot navigate on a specific button

### System configuration:
NVDA version: 2017.2
NVDA Installed or portable:

Windows version:
> Example: Windows 7

**Comment by jcsteh** [comment]
This is expected behaviour. If you want inline elements to appear on their own line, disable screen layout as documented in the User Guide. Note that you can navigate to subsequent elements on the line by moving by word, using quick navigation, etc.
