### ISSUE TITLE
[NVDA + browser] nvda reads Link which is inside an alert multiple times.

### ISSUE THREAD

**Issue by Andrewtop** [nvaccess/nvda#7358]
### Steps to reproduce:

1. Open FF or Chrome https://codepen.io/anon/pen/LLrXKL
2. Click "show error" button
3. Listen to the alert.

### Expected behavior:
Reads link in alert once

### Actual behavior:
Reads link in alert twice and in the end of alert reads the Link one more time

### System configuration:
NVDA version:
2017.2

Windows version:
> Example: Windows 10 Enterprise 1607

**Comment by dan1982code** [comment]
I confirm this behaviour using Firefox 54. The text read by NVDA is

":
alert  Error 
follow link
follow link 
or do nothing
follow link  link  visited
:"

**Comment by Adriani90** [comment]
This is still reproducible in NVDA 2019.1.1.

**Comment by Adriani90** [comment]
cc: @MarcoZehe

**Comment by Adriani90** [comment]
Closing in favor of #10658 which has the current template filled properly and the discussion is more technical there.

**Comment by ScorpAL** [comment]
Still reproduced in NVDA 2023.1
