### ISSUE TITLE
Crash when saving document in Adobe Acrobat Pro 15.0

### ISSUE THREAD

**Issue by robertspangler** [nvaccess/nvda#7359]
I was attempting to split up a PDF file, which was a textbook, into separate, PDF chapters.  I would use the bookmarks list, press the applications key on each bookmark then press export to new document.  This would create the chapter in a separate file.  The NVDA crash occurs when I go to save the file.  It's been a few weeks, but I believe this crash occurred every other save attempt.  
### Actual behavior:
NVDA crashes.  The debuglog is below:

### System configuration:
NVDA version: 2017.2

NVDA Installed or portable:Installed

Other information: 

Windows version: Windows 10 1703 (although it may have been 1607 at the time)

Name and version of other software in use when reproducing the issue:Adobe Acrobat Pro 2015 Release (Classic) | Version 2015.006.30306

### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA?  No

Here is the debuglog:
IO - inputCore.InputManager.executeGesture (11:36:54):
Input: kb(desktop):control+s
IO - speech.speak (11:36:54):
Speaking [u'Save As PDF']
IO - speech.speak (11:36:54):
Speaking [u'pane']
IO - speech.speak (11:36:54):
Speaking [u'text frame']
DEBUGWARNING - RPC process 15020 (WerFault.exe) (11:36:56):
Thread 9696, build\x86\remote\ia2Support.cpp, installIA2Support, 86:
Error registering class object, code -2147221008

DEBUGWARNING - RPC process 15020 (WerFault.exe) (11:36:56):
Thread 9696, build\x86\remote\ia2Support.cpp, installIA2Support, 86:
Error registering class object, code -2147221008

DEBUGWARNING - RPC process 15020 (WerFault.exe) (11:36:56):
Thread 9696, build\x86\remote\ia2Support.cpp, installIA2Support, 86:
Error registering class object, code -2147221008

DEBUGWARNING - watchdog._watcher (11:36:56):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 199, in <module>
  File "core.pyo", line 391, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 361, in Notify
  File "IAccessibleHandler.pyo", line 888, in pumpAll
  File "IAccessibleHandler.pyo", line 669, in processFocusWinEvent
  File "IAccessibleHandler.pyo", line 685, in processFocusNVDAEvent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 633, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 913, in _get_parent
  File "NVDAObjects\__init__.pyo", line 69, in __call__
  File "NVDAObjects\IAccessible\__init__.pyo", line 566, in __init__
  File "IAccessibleHandler.pyo", line 356, in windowFromAccessibleObject
  File "oleacc.pyo", line 268, in WindowFromAccessibleObject

DEBUGWARNING - RPC process 15020 (WerFault.exe) (11:36:56):
Thread 9696, build\x86\remote\ia2Support.cpp, installIA2Support, 86:
Error registering class object, code -2147221008

DEBUGWARNING - NVDAObjects.IAccessible.IAccessible.__init__ (11:37:01):
Resorting to WindowFromPoint on accLocation
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible.__init__ (11:37:01):
accLocation failed: (-2147023174, 'The RPC server is unavailable.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.__call__ (11:37:01):
Invalid NVDAObject: Can't get a window handle from IAccessible
Stack trace:
  File "nvda.pyw", line 199, in <module>
  File "core.pyo", line 391, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 361, in Notify
  File "IAccessibleHandler.pyo", line 888, in pumpAll
  File "IAccessibleHandler.pyo", line 669, in processFocusWinEvent
  File "IAccessibleHandler.pyo", line 685, in processFocusNVDAEvent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 633, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 913, in _get_parent
  File "NVDAObjects\__init__.pyo", line 71, in __call__
IO - speech.speakTypedCharacters (11:37:01):
typed word: t
DEBUG - treeInterceptorHandler.killTreeInterceptor (11:37:01):
Killed treeInterceptor: <virtualBuffers.adobeAcrobat.AdobeAcrobat object at 0x0505BEB0>
IO - speech.speak (11:37:01):
Speaking [u'Publisher  window']
IO - speech.speak (11:37:01):
Speaking [u'Items View  list']
IO - speech.speak (11:37:01):
Speaking [u'05 Chapter 5  6 of 6']
IO - inputCore.InputManager.executeGesture (11:37:03):
Input: kb(desktop):alt+tab
DEBUG - appModuleHandler.cleanup (11:37:03):
application werfault closed
DEBUG - appModuleHandler.cleanup (11:37:03):
application acrobat closed

**Comment by jcsteh** [comment]
From what I can see from this log, Adobe Acrobat is crashing, not NVDA. What makes you feel this is an NVDA crash?

**Comment by robertspangler** [comment]
Sorry, I’m by no means an expert coder.  I looked at the log and saw something about issues installing IA2 and the watchdog freezing, so I thought that it was at least something to do with NVDA.  If this isn’t anything that has to do with NVDA, please accept my apologies for wasting your time!

**Comment by jcsteh** [comment]
No apologies needed; I just wanted to narrow down the issue. It's possible that NVDA is somehow triggering this crash, but the crash itself is occurring in Acrobat.

Do you know if this occurs with any PDF or only certain PDFs? Is there perhaps a sample you could provide that reproduces the problem? We have contacts at Adobe, so we might be able to forward the issue to them for investigation.

If you feel comfortable doing this, you could try following the instructions in the Minidumps for Other Applications section of the [Log Files and Crash Dumps](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) article to get a crash dump when Acrobat crashes. If you can provide that dump to us, we might be able to figure out whether some NVDA component is involved.

**Comment by robertspangler** [comment]
OK, I will try other PDF files and see what other dumps I can find.  I’m going on vacation next week, so it may be a week or two before I can get them to you.  Even if we find out that it’s not related to NVDA, I would love to get the info to Adobe so that they can fix the bug on their end as it’s very frustrating.  Oh, I don’t know if this makes a difference, and I really hate to say this since I can’t stand using it, but when I switched to JAWS there were no crashes.  I think that was another reason why I thought it might be NVDA related.

**Comment by jcsteh** [comment]
Okay. To be clear, I'm not at all ruling out the possibility that this is
somehow NVDA specific, but we need further info before we can make that
determination. Please do provide those details/dumps when you are able.
Thanks.

**Comment by robertspangler** [comment]
Hello, OK so I enabled dumps by entering the command into the Python window provided in the article that you referenced.  It informed me of where it would place the file; however, no dump is being created.  Is this because NVDA itself is not crashing?  NVDA locks up but it returns when I press alt+f4 on the Adobe windows which are not responding and press Close the Program.  Additionally, I confirmed that it is crashing with more than just one PDF file; I tried two.

Obviously, it is the combination of Adobe Acrobat Pro and something else on my system, as I doubt something this major would get passed the Adobe developers.  to recap, I go to the bookmarks tree view of the PDF document, press applications key on a bookmark and choose extract bookmark.  This opens a new Adobe Acrobat window (not a tab) with a new PDF file containing the text.  I can save it just fine the first time; it's when I go to do the next one, the crash occurs immediately after pressing ctrl+s.  This is 100% consistent.

Thanks,
Robert

**Comment by jcsteh** [comment]
That's unfortunate. Sometimes, NVDA is unable to generate dumps for other applications. The only way to get a dump then would be to use WinDBG, but unless you're familiar with that already, I don't think that's feasible; using WinDBG to do this is quite involved.

I'll see about contacting Adobe.

**Comment by robertspangler** [comment]
If it’s a matter of running another program, like a debugger, in the background than I might be able to do it.  If it involves getting into the code and setting breakpoints and such then I’m afraid you’re right – that’s a little beyond me.  Haha.

**Comment by robertspangler** [comment]
Additionally, though, if it would help to provide my contact details to Adobe so that they can work with me, too, please feel free.  I’m not sure if you can see my email address on here or not but pass it along to them if you feel it would be valuable.

**Comment by Adriani90** [comment]
@robertspangler are you still having this issue in NVDA 2019.1?

**Comment by Adriani90** [comment]
@robertspangler this is just a reminder, are you still having this issue? I was able to reproduce it with NvDA 2017.3 on Windows 8.1 and Adobe reader but not with NVDA 2019.1.1 Can you confirm please?

**Comment by Adriani90** [comment]
We do not have any updates and I cannot reproduce this issue. Closing as abandoned and works for me.
