### ISSUE TITLE
Browse Mode Find, Edge, Failing to Find Text

### ISSUE THREAD

**Issue by dan1982code** [nvaccess/nvda#7362]
Go to this page in Edge:
http://mlb.mlb.com/media/player/mpa/index.jsp
and, from the top, ctrl+NVDA+f and search for the word available
It will not be found.
Now, press t until you get to the table of games, and search for the word available
It will be found this time.

This doesn't happen in Firefox.

**Comment by josephsl** [comment]
Hi, confirmed. I get a feeling that we’re not traversing all nodes, including traversing inside containers such as tables. CC @MichaelDCurran

**Comment by ehollig** [comment]
This appears to work correctly for me using NVDA master-14340 and the steps provided in https://github.com/nvaccess/nvda/issues/7362#issue-241018704. Feel free to reopen if I am of error.
