### ISSUE TITLE
Accessibility issue while using NVDA with firefox and IE

### ISSUE THREAD

**Issue by aspireinnov** [nvaccess/nvda#7368]
Steps to reproduce:
 1. Open Firefox
 2. Start NVDA , speech viewer
 3. Opened our UI homepage and started navigating through the different elements using tab.

Expected behavior:
The different elements on UI page should get displayed on the speech viewer logs screen in the same order as that of the navigation order.

Actual behavior:
The different elements being navigated through are displayed in the speech viewer screen when we access the UI for the first time. After traversing through all the elements of the screen once, again when we navigate through the screen then the control gets passed to the last clickable link on the page and then starts working fine after we pass through the same by hitting tab.
 
System configuration:
NVDA version: 2017.2

NVDA Installed or portable:
Installed

Windows version:
Windows 7 Enterprise version Service Pack 1

**Comment by derekriemer** [comment]
can you send us a link to your page so we can further investigate this?

**Comment by jcsteh** [comment]
Do you have actual speech disabled? If you do this, the automatic "say all"
that occurs when you open the page will read the entire page, since there's
no concept of speech taking time when there's no actual speech. That would
explain why you're seeing all the content before you press tab, assuming
that's what you mean. The cursor also moves during this say all.

**Comment by aspireinnov** [comment]
Observed similar behavior on www.google.com as well.

**Comment by ehollig** [comment]
@aspireinnov, as asked in https://github.com/nvaccess/nvda/issues/7368#issuecomment-313974563, do you have the checkbox for "Automatic Say All on page load" check box checked? If so, this could be the issue. Try viewing the webpage when this checkbox is not checked and see if it fixes the issue.

**Comment by ehollig** [comment]
Closing as invalid, as we have not heard from @aspireinnov in over a year, and still require a link to the homepage as described in the original post. Also, we are still unsure if unchecking the "Automatic Say All on page load" check box has fixed this issue for @aspireinnov
