### ISSUE TITLE
Braille: giving choice concerning Dot7 and Dot8

### ISSUE THREAD

**Issue by Andre9642** [nvaccess/nvda#7369]
Since PR #6449, dot7 and dot8 are universally bound to braille input specific scripts for erase and enter.
It is a bad idea in some cases.
For example, in french, dot7 corresponding to [no-break space](https://en.wikipedia.org/wiki/Non-breaking_space) ( U+A0) and B8 corresponding to [middle dot](https://en.wikipedia.org/wiki/middot) (·U+B7).
These signs are as important as other.
Before, with my display braille, I could entering these chars. Now, I can't anymore; therefore, it's a regression.
I think that it's necessary to give the choice concerning the behavior for these keys. Otherwise, why not take inspiration from BRLTTY and iOS (who have an excellent support for them)?

**Comment by josephsl** [comment]
CC @JCSTeh and other French users.

**Comment by jcsteh** [comment]
What does BRLTTY do for dots 7 and 8? Most users seem to want dots 7 and 8 to behave as we have bound them, but it seems French might be an exception. Getting around that might require specific exceptions for the French translation.

**Comment by jcsteh** [comment]
Another thought: is it reasonable for French users who need this to rebind the dot 7 and 8 bindings, since it's possibly the only table noticeably affected? Note that this can easily be done from the Input Gestures dialog, so this is in fact already configurable as requested.

**Comment by Andre9642** [comment]
> Note that this can easily be done from the Input Gestures dialog, so this is in fact already configurable as requested.

My apologies. I had not thought about this possibility. O.o Therefore, everything is good! :)

**Comment by derekriemer** [comment]
Well, every french braille user having to do this is a bit much, don't you think?

**Comment by jcsteh** [comment]
[**@derekriemer**](https://github.com/derekriemer) commented on [10 Jul 2017, 09:12 GMT+10](https://github.com/nvaccess/nvda/issues/7369#issuecomment-313971812 "2017-07-09T23:12:06Z - Replied by Github Reply Comments"):
> Well, every french braille user having to do this is a bit much, don't you think?

I'll counter-argue: don't you think every non-French braille user having to bind dots 7 and 8 is a bit much? The set of French braille users is smaller than the set of non-French braille users.

We could do specific bindings in a French specific gestures.ini, but that would only apply to the French NVDA translation. So, if you were typing French braille with your NVDA language set to English, this wouldn't apply.

@Andre9642, how often do French users type these symbols? Are they common in French or only used by a specific set of French users? As a French user, do you think it makes sense to bind dots 7 and 8 differently for the French translation? Note my concerns above.

**Comment by josephsl** [comment]
Hi, one more variable to the mix: how about changing input tables? Does this resolve the problem?

**Comment by jcsteh** [comment]
CC @pzajda and @MichelSuch for their thoughts as French translators.

**Comment by jcsteh** [comment]
[**@josephsl**](https://github.com/josephsl) commented on [10 Jul 2017, 10:19 GMT+10](https://github.com/nvaccess/nvda/issues/7369#issuecomment-313975243 "2017-07-10T00:19:32Z - Replied by Github Reply Comments"):
> how about changing input tables?

Not sure I understand what you mean. If you mean changing the table itself to avoid dot 7 and 8 bindings, I'm assuming the tables follow some kind of standard (whether official or de facto). I imagine that won't be acceptable for French braille readers and writers.

**Comment by Andre9642** [comment]
I think that's fine as it is. Some braille displays haven't dedicated keys for backspace and enter (eg: Brailliant). Objectively, these signs are little used, enter and backspace keys are much more useful. In my opinion, as long as they can be easily redefined, that's the main one.
