### ISSUE TITLE
NVDA and Windows 10 Start Menu: reporting typed text after closing the menu

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#7370]
This is a long standing issue with NVDA.

1. Open the Windows 10 Start menu.
2. Type in the name of an app/program like' Notepad'. If you type 'Note' for example, that should be sufficient, and I recommend that because the issue would become easier to spot.
3. Press Enter. The menu will close and something happens before Notepad starts.

Expected: NVDA just keeps quiet and Notepad starts.
Actual: NVDA says Note, Notepad etc. (whatever you typed) then starts the program as expected.

I have noticed this with:
NVDA as far back as 2015.3 to the latest Next snapshot.
Windows 10 as far back as 15240 to 15063.413 and still going.
Speak typed characters and words both on and off. It doesn't matter.

**Comment by josephsl** [comment]
CC @MichaelDCurran, looks like something odd is going on with our suggestions list item handler.

**Comment by jcsteh** [comment]
Actually, this is due to the enter key handler used to read automatically inserted text on the next line; e.g. automatic numbering in Word. It can be fixed by setting announceNewLineText to False for the search field.

P3 because it's superfluous but otherwise harmless, but should be fairly easy to fix.

**Comment by josephsl** [comment]
Hi Andre, do you know other places where this should be handled? Let me know so a PR can be submitted tomorrow. Thanks.

**Comment by fisher729** [comment]
No. not at this time. The start menu is the only one that stands out now.
