### ISSUE TITLE
request to add one setting to desable spelling lines phoneticly.

### ISSUE THREAD

**Issue by zahra21** [nvaccess/nvda#7379]
i request to include one setting in 2017.3 for all people who cant or dont want to use it.
when i press nvda+up arrow twice to spell the line, sometimes nvda is a little slow in responding and sometimes i am in a complex task or in a hury and forget to press this command twice and i press it many times accedentally.
for this reason, i hear the phonetic spelling not only spelling the character of line as usual.
i sincerely request that add a setting to disable phonetic spelling of lines in 2017.3 and have previous nvda!
i understand that some people may need this feature and you provided for them.
but some people like me dont need and i believe that spelling lines phoneticly should be optional.
those want and need activate it and other uncheck it.
its very annoying and confusing for me specially because i read and edit many many books with hundreds of pages and cant pay attention that how many times i pressed nvda+up arrow for spelling!

**Comment by Qchristensen** [comment]
Edited issue to trim to content related to request.

**Comment by jcsteh** [comment]
Thanks for taking the time to make the suggestion. However, this is not something we will implement. Having an option like this just for phonetic spelling of a line is fairly arbitrary. Someone else might decide that they also don't want to accidentally spell the line when they only meant to read the line, or that they don't want to read the date when they press NVDA+f12 twice. If we implemented options for all of these, we would end up with a massive number of options, which clutters configuration.

Note that #7314 proposes having separate commands (unbound by default) for things like spell line. There are good reasons to implement this, and if we do, it would enable you to bind a separate key of your choice to spell line so you only have to press it once.

**Comment by zahra21** [comment]
hello.
thanks so much for your reply.
but in which version of nvda do you change spelling to we press its command only once?
also this is very important in compare to date which you mentioned.
i read and edit books with hundreds of pages and wish to have previous behaviour of nvda.
i wish how many times i press nvda+up arrow, hear only spelling the line letter by letter not with phonetics.!
for example: you can push this setting in voice setting to makes spelling phoneticly optional.
thanks for your help and God bless you.

**Comment by zahra21** [comment]
its a very easy task for you i am sure.
and i sincerely request that accept it and put one checkbox in for example voice settings or anywhere in preferences thats possible to disable this and have previous behaviour of nvda.
i wish to use nvda 17.3 when becomes available, because of problems for cursor navigation between character using firefox and previous versions of nvda.
i had this problem in these years and i am very glad and appreciate you to solved it.
but for spelling phoneticly, its very difficult to use nvda 2017.3
now, i am using nvda 2017.1
