### ISSUE TITLE
Unexpected behavior with table and container navigation for nested tables

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7382]
I've seen the case below in a corporate environment. I agree it isn't common style of coding.

### Steps to reproduce:
1. Execute the following from a Firefox location bar:
    ```
    data:text/html, <p>Prepare for a table</p><table><tr><th>Header 1</th><th>Header 2</th></tr><tr><td>Outer table cell 1</td><td>Outer table cell 2</td></tr><tr><td><table><tr><td>Inner table cell 1</td><td>Inner table cell 2</td></tr></table></td><td>Outer table cell 4</td></tr><tr><td>Outer table cell 5</td><td>Outer table cell 6</td></tr></table>
    ```

2. Use table navigation inside the table. Everything works fine, until you reach outer table cell 3, which consists of a table itself with two cells.

### Expected behavior:
A. When in the inner table, pressing comma moves you out of it to outer table cell 4
B. Table navigation doesn't get trapped into the inner table as soon as you are in it.

### Actual behavior:
A. When in the inner table, pressing comma moves you out of it to outer table cell 6, so the bottom of the outer table
B. Table navigation gets trapped into the inner table as soon as you are in it.

### Technical details
The outer table is treated as a content table, the inner table is treated as a layout table. This is why pressing comma in the inner table moves you to the edge of the outer table, since layout tables aren't treated as containers. If you enable "Include layout tables" in browse mode settings, issue A goes away.

### Points to discuss:
At least there is an inconsistency here, as table nav works for layout tables, but they aren't treated as containers.

* Should we disable table navigation altogether for layout tables inside content tables? I think we should consider this. May be we should even disable table navigation in all layout tables
* If the former is too much, how about treating layout tables as containers, so if you get trapped with table nav, you can navigate out of the container to the outer table?

**Comment by jcsteh** [comment]
I've always believed table navigation shouldn't consider layout tables when inclusion of layout tables is disabled. However, I believe @MichaelDCurran made a case against this, hence the current behaviour. Mick, is this (still?) correct, and if so, can you explain why? @QChristensen, thoughts?

**Comment by michaelDCurran** [comment]
I may have thought this at one time, but  today I would be fine with ignoring layout tables. I think from memory the issue was more around the complexity to do this, especially with Gecko as we use a hybrid of virtualBuffer and out-of-proc IA2. having said this, some of that code was slightly refactored when abstracting table support for browseMode, so it is worth looking into again. I certainly agree the difference between table navigation and container jumping is bad.

**Comment by jcsteh** [comment]
P2 because this can be quite problematic and layout tables are still (unfortunately) rather common.

**Comment by leonardder** [comment]
Ok, let me investigate the complexity of this later this week

**Comment by michaelDCurran** [comment]
I'll take this, as I am also working on some ARIA grid stuff which may directly affect this code.

**Comment by leonardder** [comment]
Ah, that works too.

**Comment by leonardder** [comment]
Confirmed that this now works as expected.

**Comment by derekriemer** [comment]
take this example.

data:text/html, <p>Prepare for a table</p><table><tr><th>Header 1</th><th>Header 2</th></tr><tr><td>Outer table cell 1</td><td>Outer table cell 2</td></tr><tr><td><table><tr><th>Inner table cell 1</th><td>Inner table cell 2</td></tr></table></td><td>Outer table cell 4</td></tr><tr><td>Outer table cell 5</td><td>Outer table cell 6</td></tr></table>

Table nav still traps the user, which is annoying. Could we do something like "Leaving  nested table" when navigating out of the inner table with table nav?

**Comment by leonardder** [comment]
[**@derekriemer**](https://github.com/derekriemer) commented on [2 aug. 2017 17:14 CEST](https://github.com/nvaccess/nvda/issues/7382#issuecomment-319703500 "2017-08-02T15:14:20Z - Replied by Github Reply Comments"):
> Table nav still traps the user, which is annoying. Could we do something like "Leaving  nested table" when navigating out of the inner table with table nav?

You can leave the inner table with comma, so I think that is at least something. But I agree that data tables inside data tables should be treated as layout tables.

**Comment by derekriemer** [comment]
There *could* be a usecase, but it would be verry weird.
