### ISSUE TITLE
Access to Javascript Debugger on Firefox, Internet Explorer and Chrome!

### ISSUE THREAD

**Issue by sharkboyto** [nvaccess/nvda#7386]
Hi,
I'm an italian blind developer.
My preferred accessible tolls are:
- Eclipse IDE
- Notepad++
- dbeaver (for DB)
- Tera Term  (for ssh terminal)
- WinSCP (for ftp connection and above)

For my work I need to debug web pages contain Javascript code.

The tools integrated into the most used web browsers are not accessible through assistive technologies, only with internet explorer have managed to get little results.

Can you make it accessible with nvda, one of the browsers? In my opinion Firefox or Internet Explorer are the worst choice.

In your opinion, which browser is the most accessible with nvda? Firefox or Internet Explorer?
My opinion is Firefox.

>1. open Firefox
>2. Go to tolls menu
>3. Open de developer Tools
>4. open the debug tools
> 5. press TAB and go to list of javascript avaiable
> 6. nvda read "unknow message" in the list of disponibile
> 7. press TAB to move to text area contains js code, completly not accessible area unfortunatly
> 8. is impossible to add a breackpoint and debug the file

All previous steps work better with internet explorer, but with limitations and a lot of slow execution.

Perhaps the job for the nvda developer to do in internet explorer is less than what to do in firefox.

Some sections of firefox developer tools are accessible. The debug area no.

Thanks a lot.

**Comment by jcsteh** [comment]
These are issues that need to be fixed in the browsers. The browsers simply do not expose enough information for a screen reader to be able to access these areas.

There was some discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1088804 about making the Firefox Scratchpad accessible.

Beyond this, please file bugs against Firefox or Chrome (if they haven't been filed already).

Thanks.

**Comment by leonardder** [comment]
Note that as for Firefox, firebug is fairly accessible if you explicitly enable its accessibility support. Also, I've had quite good results in the browser console with reviewing javascript errors. For example, I use the browser console for debugging grease monkey scripts.

**Comment by sharkboyto** [comment]
Hi, in the most recent Firefox update, Firebug is not supported. In the official Firebug site It is recommended to use the Firefox Developer Tools. I have installed a portable Firefox version on my system, add the firebug addon, the 2.0 version, the lastone, but in the option menu, there isn't the accessibility option for switch on/off the feature. Any suggestion? 
Unfortunately, I do not just debug through the error console, but I need a real debugging step by step. Thanks a lot.
