### ISSUE TITLE
NVDA throws Error in a specific Word Doc

### ISSUE THREAD

**Issue by CSGiuliano77** [nvaccess/nvda#7388]
### Steps to reproduce:

1.  Either open Word 2016 or open the attached file (Student log form 1.1.docx from File Explorer.
2.  Press either up or down arrows to read the text anywhere in the doc.
3.  NVDA plays an error tone.
4.  Relevant error text from NVDA log states:
ERROR - RPC process 3344 (WINWORD.EXE) (09:22:56.253):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

### Expected behavior:
NVDA should not play error tone??  There is also some lag when moving from line to line or character by character. Cannot reproduce this with any other document that I have opened in word.  It has been quite some time since I have run Word 2013, and I do not believe this occured then.

### Actual behavior:
NVDA should read the text of the document without playing error tone, and navigation should be smoother.

### System configuration:
NVDA version:
NVDA Next 14189,16D28E60

NVDA Installed or portable:
Installed

Other information:
Running under Bootcamp on MacBook Air mid 2012
Note:  This occured on a Lenovo Yoga laptop as well.  Just FYI, but fairly sure that is not relevant.

Windows version:
Windows 10 Version 1607 Build 16237.1001
(occured in prior versions since Anniversary Update)

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
Yes
I have been running nightlys since 2012, and I noticed this when running Office 2016 (versions from August, 2016 and onward.  Sorry I cannot be more specific then that.  As a work-around, I use JAWS when editing this particular document.
[Student Log Form 1.1.docx](https://github.com/nvaccess/nvda/files/1142199/Student.Log.Form.1.1.docx)

Full text of log at "info" level:
INFO - __main__ (09:06:48.611):
Starting NVDA
INFO - core.main (09:06:48.749):
Config dir: C:\Users\CSGiu\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (09:06:48.749):
Loading config: C:\Users\CSGiu\AppData\Roaming\nvda\nvda.ini
INFO - core.main (09:06:48.763):
NVDA version next-14189,16d28e60
INFO - core.main (09:06:48.763):
Using Windows version 10.0.16237 workstation
INFO - core.main (09:06:48.763):
Using Python version 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
INFO - core.main (09:06:48.763):
Using comtypes version 0.6.2
INFO - synthDriverHandler.setSynth (09:06:49.121):
Loaded synthDriver eloquence
INFO - core.main (09:06:49.121):
Using wx version 3.0.2.0 msw (classic)
INFO - brailleInput.initialize (09:06:49.124):
Braille input initialized
INFO - braille.initialize (09:06:49.125):
Using liblouis version 3.2.0
INFO - braille.BrailleHandler.setDisplayByName (09:06:49.125):
Loaded braille display driver noBraille, current display has 0 cells.
WARNING - core.main (09:06:49.157):
Java Access Bridge not available
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (09:06:49.161):
UIAutomation: IUIAutomation3
INFO - core.main (09:06:49.730):
NVDA initialized
INFO - config.ConfigManager._loadConfig (09:06:49.910):
Loading config: C:\Users\CSGiu\AppData\Roaming\nvda\profiles\firefox.ini
ERROR - RPC process 4812 (nvda_slave.exe) (09:07:29.704):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 90, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1165, in GetActiveObject
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221021] Operation unavailable
INFO - config.ConfigManager._loadConfig (09:09:46.884):
Loading config: C:\Users\CSGiu\AppData\Roaming\nvda\profiles\winword.ini
ERROR - RPC process 11548 (WINWORD.EXE) (09:10:05.384):
Thread 3624, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 11548 (WINWORD.EXE) (09:10:06.220):
Thread 3624, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 11548 (WINWORD.EXE) (09:10:07.081):
Thread 3624, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 11548 (WINWORD.EXE) (09:10:07.831):
Thread 3624, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 11548 (WINWORD.EXE) (09:10:09.740):
Thread 3624, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 11548 (WINWORD.EXE) (09:10:11.351):
Thread 3624, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 11548 (WINWORD.EXE) (09:10:25.539):
Thread 3624, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 11548 (WINWORD.EXE) (09:10:45.624):
Thread 3624, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 11548 (WINWORD.EXE) (09:10:49.875):
Thread 3624, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 11548 (WINWORD.EXE) (09:10:51.039):
Thread 3624, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 11548 (WINWORD.EXE) (09:10:54.081):
Thread 3624, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 11548 (WINWORD.EXE) (09:11:05.845):
Thread 3624, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 11548 (WINWORD.EXE) (09:11:07.216):
Thread 3624, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

WARNING - watchdog._watcher (09:11:29.645):
Core frozen in stack:
  File "nvda.pyw", line 199, in <module>
  File "core.pyc", line 396, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 367, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "scriptHandler.pyc", line 145, in _queueScriptCallback
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 176, in script_caret_moveByLine
  File "editableText.pyc", line 136, in _caretMovementScriptHelper
  File "editableText.pyc", line 122, in _caretScriptPostMovedHelper
  File "speech.pyc", line 748, in speakTextInfo
  File "NVDAObjects\window\winword.pyc", line 636, in getTextWithFields

WARNING - watchdog._watcher (09:11:44.664):
Core frozen in stack:
  File "nvda.pyw", line 199, in <module>
  File "core.pyc", line 396, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 367, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "scriptHandler.pyc", line 145, in _queueScriptCallback
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 176, in script_caret_moveByLine
  File "editableText.pyc", line 136, in _caretMovementScriptHelper
  File "editableText.pyc", line 122, in _caretScriptPostMovedHelper
  File "speech.pyc", line 748, in speakTextInfo
  File "NVDAObjects\window\winword.pyc", line 636, in getTextWithFields

WARNING - watchdog._watcher (09:11:59.704):
Core frozen in stack:
  File "nvda.pyw", line 199, in <module>
  File "core.pyc", line 396, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 367, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "scriptHandler.pyc", line 145, in _queueScriptCallback
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 176, in script_caret_moveByLine
  File "editableText.pyc", line 136, in _caretMovementScriptHelper
  File "editableText.pyc", line 122, in _caretScriptPostMovedHelper
  File "speech.pyc", line 748, in speakTextInfo
  File "NVDAObjects\window\winword.pyc", line 636, in getTextWithFields

ERROR - RPC process 11548 (WINWORD.EXE) (09:11:09.042):
Thread 3624, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:12:48.859):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:12:53.565):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:12:54.924):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:13:19.551):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:13:23.818):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:13:24.815):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:13:26.006):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:13:27.046):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:13:28.503):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - eventHandler.executeEvent (09:13:47.826):
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x07087F50> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1284, in event_caret
  File "NVDAObjects\window\edit.pyc", line 825, in event_caret
  File "NVDAObjects\behaviors.pyc", line 175, in event_caret
  File "editableText.pyc", line 290, in detectPossibleSelectionChange
  File "editableText.pyc", line 297, in _updateSelectionAnchor
  File "textInfos\offsets.pyc", line 355, in compareEndPoints
AttributeError: 'ITextDocumentTextInfo' object has no attribute '_startOffset'
ERROR - RPC process 3344 (WINWORD.EXE) (09:14:01.187):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:14:05.075):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:14:06.709):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:14:09.526):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:14:35.539):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:14:38.114):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:22:53.102):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:22:55.006):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:22:56.253):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

ERROR - RPC process 3344 (WINWORD.EXE) (09:24:09.305):
Thread 8900, build\x86\remote\winword.cpp, calculatePreAndPostColumnOffsets, 784:
error getting leftMargin. res: -2146823683 leftMargin: -1

**Comment by leonardder** [comment]
cc @FeerRenrut @MichaelDCurran, I recall the margin reporting code is from one of you guys, but not sure.

**Comment by feerrenrut** [comment]
@leonardder Thanks for raising this and providing the example. I can reproduce this with `next-14166,e5cc1931` and Word 2013. Looking at the document there are a few values missing in the paragraphs section. Without looking at the code, I would guess this is causing the error. Since this is a form, I'm assuming this document is exported from somewhere, and has incomplete paragraph information (total conjecture by the way). In any case, word seems to be happy to open the document. I would suggest we try to hardcode default values that match Word's behaviour when fetching the values fails.

**Comment by feerrenrut** [comment]
Set priority 2 to fix this, since its a regression caused by recent code, and should be fairly easy to fix.

**Comment by CSGiuliano77** [comment]
Hi all,

Thanks for being able to look into this.  I am still experiencing this issue using the latest nightly of NVDA and insider build of Office 2016.  One thing I found is that if you unprotect the document by using the "restrict editing" payne under the developer tab, this issue seems to disappear once the document is unprotected.

Once the developer tab in Word is on the ribbon, press enter on “restrict editing” under the “protection” group, which can be accessed by pressing "control+right arrow" a few times.  A new pane will appear where you have to press space on “stop protection”.  A dialog box will open, and you finally will have to uncheck the box that says, “Allow only certain types of editing in this document”.  If you move back to the document pane and try to navigate, NVDA will not throw any more errors.  Thoughts?  And thanks again.

**Comment by CSGiuliano77** [comment]
Forgot to add that this occurs with similar documents, and using the procedure above was tested on them producing the same result.

**Comment by Adriani90** [comment]
I have tested with NVDA Alpha 16691,10950C87 and NVDA 2018.4.1 on Word 2016 and 365. I cannot reproduce this issue. @CSGiuliano77 are you still seeing this problem?

**Comment by lukaszgo1** [comment]
This is still reproducible with Word 2010 32-bit on Windows 7 and the last NVDA alpha.

**Comment by Adriani90** [comment]
@CSGiuliano77 how is this now with NVDA last alpha version and Microsoft Word last update? Are you still having this issue?

You can download and test the last alpha at this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by CSGiuliano77** [comment]
@Adriani90 thank you for looking into this. It now seems to be resolved.
