### ISSUE TITLE
Unnecessary import in api.py

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#7389]
The `braille` module is imported in `setReviewPosition` but is also globally imported at the top of the file. The function-specific one is redundant. Or if it's not, a line of documentation would be nice to explain this.

**Comment by jcsteh** [comment]
Nope, the function specific import is redundant and can be removed.

**Comment by dkager** [comment]
Do you want a PR or can you sneak in a quick commit? :)

**Comment by leonardder** [comment]
We can do this as part of #2385 probably, since we might have to hack 
into that function.
