### ISSUE TITLE
Inconsistent browse mode behavior for html5 input="number"

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7390]
### Steps to reproduce:
Firefox/Chrome address bar: 
```
data:text/html, <label for="spin">Spin</label><input id="spin" type="number" min=3 max=10 />
```

For IE and Edge, paste this in a HTML file.

### Expected behavior:
Equal presentation in Browse mode and equal quick navigation behavior

### Actual behavior:
* Firefox 54: presented as spin button with edit control, navigable with e and f quicknav
* Chrome Canary 61: presented as spin button editable, value presentation is entirely broken. only f quicknav works
* Edge: Presented as spun button, no value presented. Focus mode allows to change the value accessibly. No quicknav possible
* IE: presented as edit box

### Things to do
* Add UIAHandler.UIA_SpinnerControlTypeId to quick nav for form fields and probably buttons

### Nuts to crack
* Should we treat spinners as edit boxes or buttons, or even both?
* Should we treat oleacc.ROLE_SYSTEM_SPINBUTTON as buttons?
* Should we force the NVDA role in IE to spin button for input="number"? Probably not, as it seems IE entirely lacks support for spin buttons.

**Comment by jcsteh** [comment]
See #5422 for the issues specific to Chrome. Note that this is blocked on a fix from Google.

**Comment by Qchristensen** [comment]
Here is another example created by a user: http://www.mindspace.site/static/test.html

Source:
<!doctype html>
<html lang="en">
<body>
<form>
<h1>Text</h1>
<input type="number" id="age" value="27">
</form>
</html>

Using Chrome, Version 62.0.3202.94 (Official Build) (64-bit)
The value can be adjusted in focus mode, but only reads as "blank".  In Browse mode, the value can be read only.

In Firefox (ESR, Version 52), the spin button value can be changed in Focus mode with the arrow keys and the current (new) value is read correctly.

**Comment by Adriani90** [comment]
The issue in Edge and IE11 still exists in NVDA 2019.1.1. Chrome and Firefox work very well now.

**Comment by leonardder** [comment]
I guess that for both IE 11 and Edge, a fix is very unlikely. This works ok in Edge Chromium as expected.

**Comment by Adriani90** [comment]
Closing as abandoned since support for IE ended completely in 2022 and it is automatically removed from machines that still have it after an Edge update in February 2023. I don't expect further accessbility updates in IE or IE mode in Edge.
