### ISSUE TITLE
Focus/browse mode sounds

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#7393]
I believe the sounds to indicate focus and browse modes introduced with v2017.3 are not sufficiently different from each other.  I accept that the difference is discernable, especially when using earphones, but I foresee people being confused or worse, missing the indication.  While the sounds used up to v2017.2 can be a bit raucous, they are eminently distinguishable.

Andrew

**Comment by leonardder** [comment]
Note that #7218 is still incubating, so it is not yet sure whether this will make it into 2017.3

**Comment by andrew-l-d** [comment]
That is why I mention it at this point.  I am hoping that 2017.3 would revert to the previous sounds or perhaps something a bit more subtle but readily distinguishable by diverse users in various environments.

**Comment by Brian1Gaff** [comment]
No I'm not a fan of the new ones myself either, but if the start and stop 
ones were lengthened a bit and the focus and browse ones used less stereo 
and a bit more in the lower registers it might be easier for those hard of 
hearing. also they seem a bit quiet as I have said before.


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by leonardder** [comment]
CC @JCSTeh

**Comment by dan1982code** [comment]
I've also been wondering about the very lengthy jingle that plays when NVDA updates. I do like it. But it's several seconds; is the install still happening then or is it slowing down the install? If other sounds are being shortened, perhaps this one could too?

**Comment by jcsteh** [comment]
I have plans to eventually remove that logo sound. That said, it does not
slow down the install in any way; it plays while the installer is loading.

**Comment by andrew-l-d** [comment]
Hey, I love that logo sound.

**Comment by Brian1Gaff** [comment]
I second this. Its comforting to hear it. I don't see much point in changing 
it or removing it at all.
 Very low priority. Could be just disabled if the person wants to do so I'd 
have thought. Now the more reliable saved .ini file is pretty stable It 
seems to me that the option disable logo sound from next start up would work 
if needed by somebody working in a library!!!
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by jcsteh** [comment]
Feedback on this issue, #7218, these two [nvda-devel](http://nabble.nvda-project.org/New-sounds-in-next-snapshots-td42138.html) [threads](http://nabble.nvda-project.org/Feedback-from-me-on-new-sounds-td42079.html), social media and elsewhere suggests that while some users are happy with the new sounds, a significant number of users have concerns (e.g. difficulty in discerning the sounds) or are vehemently opposed to them. As a result, we're going to revert this change, and given the amount of difficulty in satisfying various groups, we are not going to consider any alternatives in the near term. Eventually, our aim would be to allow add-ons to more easily provide sound packs. I'm going to lock comments on this PR; further discussion at this point is not useful. Thanks to those who provided feedback.
