### ISSUE TITLE
Sometimes unusably slow after restart

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#7395]
STR:
1. Restart NVDA

After that, NVDA is unusably slow.
If I reboot, this problem goes away for anywhere from a few minutes to a few weeks.

It doesn't happen all the time, either.

I can load Narrator or JAWS at that point and they both seem to work well enough for me to reboot.

Win10 build 1703, NVDA next-14176,be0a44e4.

I managed to get NVDA restarted with debug logging, here is the part of the log where I try to do something.

[log.txt](https://github.com/nvaccess/nvda/files/1147601/log.txt)

**Comment by leonardder** [comment]
Have you seen this without add-ons loaded?

**Comment by tspivey** [comment]
Yes. I once tried to restart with add-ons disabled, but it didn't help.

**Comment by Brian1Gaff** [comment]
Couple of things, have you seen the slow down thread in the nvda normal mail 
list, which suggests a lot of software activity used to create special audio 
mode, enhanced, which gets switched on after a windows update making a core 
max out where nvda is living.
 Another thought is the good old idling rate of the processor being set too 
low. All those watchdog core frozen in stack looks just like what a single 
core machine used to do if it, for example decided to download a big update 
and tried to run nvda as well.
  Not sayying this is the cause, but one issue I've seen with nvda is that 
several cores can be idling yet the one nvda is using is maxed out as if the 
machine has not actually noticed

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by jcsteh** [comment]
I do find it interesting that you get "Program Manager (not responding)" at one point. That suggests Explorer locked up, which is certainly concerning... and I don't see how NVDA could cause that. When you get Narrator running, do you encounter any strangeness at all or is everything perfectly normal?

**Comment by tspivey** [comment]
Everything's completely normal. I'm able to use Edge, navigate around, etc.
This time, I had UIA disabled for something. No difference, NVDA is still unusable.

**Comment by tspivey** [comment]
Narrator seems to cause this to happen faster. I restarted NVDA 10 times, and it was working fine.
As soon as I start Narrator and exit it, then start NVDA, it breaks, but only if I've started NVDA at least once.

Upgrading to the Windows Insider build (16281) and NVDA next-14420,b75ca8ad hasn't fixed this.

**Comment by Adriani90** [comment]
@tspivey are you still seeing this issue in NVDA 2019.1.1 and Windows 10 1809 Update or later builds?

**Comment by Adriani90** [comment]
We do not have an update for this from the initial author since more than two years. Closing as abandoned.
I cannot reproduce this on Windows 10 1909 Update with NVDA 2019.3.1 and I didn'thear any other user reports regarding this issue.

**Comment by tspivey** [comment]
I haven't seen this recently.
