### ISSUE TITLE
Microsoft Word Highlighted text

### ISSUE THREAD

**Issue by sharkboyto** [nvaccess/nvda#7396]
I,
form my work, I get from my colleges, different word processing documents. These documents (*.doc and *.docx), contain highlighted text and barred text . 
I have important information about this text,but i can not understand by nvda, i do not use braille.

Can you put these features in nvda?

Thank you.

**Comment by ehollig** [comment]
If you turn on Font attributes and Style in the document formatting dialog, does this do what you would like?

**Comment by Adriani90** [comment]
@ehollig No, because you do not change the color or the font of the text, you just highlight the text with a certain color. Unfortunately NVDA does not report it while navigating. cc: @Qchristensen

**Comment by Qchristensen** [comment]
I'm not sure what the original poster means by "barred" (possibly strikethrough?  If so, then enabling "Font attributes" in NVDA's document formatting dialog will report this).  It might be worth leaving this issue solely for highlight, and making a new issue if still required for "barred" text.

For highlighted text, Word does treat this differently to the font or background colour - NVDA does correctly read font and background colour.  Highlight seems to go on top of the text and makes the background appear yellow (or whichever highlight colour is used) - similar to running a highlighter over a printed page.  If you select the text and choose highlight again, it will remove the highlight.

Currently NVDA does not report highlight, although we'll need to check whether this is because Word isn't disclosing it, or whether NVDA isn't looking for it.

**Comment by Qchristensen** [comment]
Issue unchanged as at NVDA alpha-19159,cde557d5, Office 365 Version 16.0.12130.20344

I just edited the original subject to remove the ambiguity:

Changed from "Microsoft Word and text decoration: barred  text and highlighted text!" to "Microsoft Word Highlighted text".  As noted in my previous comment, if the original person can clarify what "Barred text" is in a new issue, that can be dealt with separately.

**Comment by Adriani90** [comment]
cc: @mltony we had a short discussion in connection with your browsenav addon on NVDACon this year. Here is a related issue.

**Comment by mltony** [comment]
@Adriani90
I thought about this again, and it looks like I won't be able to implement this from within BrowserNav after all, since BrowserNav operates on paragraphs, while smaller than paragraph parts of text can be highlighted.
Therefore, if we'd want to implement "jump to next highlighted text" features, it would need to analyze all the characters one by one, which would be way too slow. Unless maybe there's a separate feature in MSWord that would do such a search on its side.

**Comment by Adriani90** [comment]
Hmm, maybe implementing a key stroke which allows navigating by highlighted text only in browse mode would be a possibility?
It should not be part of text navigation (character, paragraph etc). Maybe this would not impact performance significantly. What do you think?

In my case at least, this issue makes my day to day work really inefficient. I get big documents with highlighted text which I have to review and where only the highlighted text has to be changed or adjusted. So in a document with 200 pages you don't really want to read it line by line or paragraph by paragraph.

cc: @michaelDCurran

**Comment by mltony** [comment]
If we are to implement this for browse mode in general, then the only 
way to find highlighted text would be to scan the attributes of every 
character, which I think would be prohibitively slow. I would rather 
argue that for MS Word documents it should be implemented using Word API 
- my intuition tells me there must be a function 
"FindNextHighlightedText" there.

**Comment by Qchristensen** [comment]
Looking at a document now, NVDA does report highlighting as a text change colour (Bright yellow background) for me in Office 365 Version: 16.0.12730.20236 and NVDA 2020.1rc1.  I'm not sure when this changed.

One way to find highlighted text is:
1. Open the advanced find dialog.  Press control+h.
2. Press alt+m for "More" options
3. Press alt+o for forma, then h for highlight.
4. Press ENTER to find next.
5. Press ESCAPE to close the find dialog.
6. You can now use control+page down to find additional instances of highlighted text (or control+page up for previous instances).

(I'm not saying that's the most efficient solution to this issue, just that it works).

**Comment by Qchristensen** [comment]
Another small update from a bit more testing:

In Office 365 currently (Office 365 (64-bit) Version: 16.0.13001.20338) there is an option for "Shading" in Word's Font options (it looks like it is hardcoded to grey).

There is also a "Shading" option in the paragraph options which lets you choose any colour.

Both these shading options, and highlighted text are reported by NVDA's "Color" option in document formatting options or NVDA+F.  Interestingly the character shading option reports "White background" for me, even though (with standard settings) my text, which is normally black on white, is actually black on grey when I use that character shading.

To actually search (to find the next coloured text further down a document) it looks like you can only specifically search for "highlighted" text.  You can search for text with a specific font colour, but not shading in Word.

**Comment by ABuffEr** [comment]
> Looking at a document now, NVDA does report highlighting as a text change colour (Bright yellow background) for me in Office 365 Version: 16.0.12730.20236 and NVDA 2020.1rc1. I'm not sure when this changed.

Hi @Qchristensen ,

using alpha-27459,816496f1, this is true only if you force UIA for Word document to always enabled, in Advanced settings.

But if the option is set to "Default (Where suitable)", then background color/highlighting is not reported in any way (not reading and neither checking with NVDA+f).

See also #5866 for a related issue and an example document.

P.S.: ah, I recognize the user and "barred" as a loan translation from Italian, I'd say you can consider as strikethrough :)

**Comment by Qchristensen** [comment]
> true only if you force UIA for Word document to always enabled

Ah thank you.  I must not have noticed that.

> I recognize the user and "barred" as a loan translation from Italian, I'd say you can consider as strikethrough :)

In that case, my earlier comment (and @ehollig's) should both address the "barred text" part of this request - turning on "font attributes" in NVDA's document formatting dialog will ensure NVDA reports strikethrough text.
