### ISSUE TITLE
In internet explorer, using newest OCR function will break browse mode.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#7399]
Hi:
### Steps to reproduce:
> 1. Use navigator to find an empty  graphic control in web page.
> 2. Press nvda+r to perform OCR recognizing. 
> 3. Press escape to exit OCR document.
> 4. Press arror keys to browser the web page.
### Expected behavior:
> Page content can be read normally.

### Actual behavior:
> Caret can't be moved at all.

### System configuration:
NVDA version:next-14188

NVDA Installed or portable:install

Windows version:windows 10 1703

### Other questions:

Does the issue still occur after restarting your PC?
> yes
Have you tried any other versions of NVDA?
> yes

**Comment by leonardder** [comment]
I assume you were testing this with NVDA Next, right?

CC @JCSTeh. Related to #7361

**Comment by jcsteh** [comment]
Confirmed.

Not sure why yet, but as soon as you press NVDA+r, the buffer dies. isAlive on the dead buffer seems to return True, so I ... don't understand, yet.

**Comment by jcsteh** [comment]
Fixed in 90241a0; merged in 6220c1b2.
