### ISSUE TITLE
feature suggestion - make progress bars readable manually

### ISSUE THREAD

**Issue by abdullah5490** [nvaccess/nvda#7400]
hi there. Here i'm once again, not with a bug report, but with a feature suggestion. As the subject line said, the feature to make progress bars readable manually. I mean, with a keystroke. A new key mapping should be created, through which NVDA can read the progress bar visible in current windows fourcely. As the current possibilities, the progress bars can only be spoken when it changes the position (move further or prior). But if the progress is stucked to any point, then the user might not able to determine the current percentage where the process is stucked.
this was just an example, lots of other scenarios can be benefitted with this small addition. So that's why, I am suggesting that, create a keyboard shortcut for NVDA, which used to read the currently visible progress bars instantly. 
Hope you'll get my point.
Thanks.
from A happy NVDA user!

**Comment by josephsl** [comment]
Hi, for most cases, object navigation will let you navigate to and read progress bars. Note that this requires implementation-specific modifications, as different API’s expose progress bars differently and some controls are nonstandard progress bars or does not expose proper information. Thanks.

**Comment by jcsteh** [comment]
Thanks for the suggestion. As already noted, you can access progress bars using the review cursor. I don't think this would be used enough to warrant its own command. Also, the behaviour is difficult to define; e.g. if there are multiple progress bars where nearby text is needed to determine context.

**Comment by abdullah5490** [comment]
ok. got your point
