### ISSUE TITLE
The Upper caseness of symbols are not indicated when reading math

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#7402]
### Steps to reproduce:
1. Go to http://linear.ups.edu/fcla/section-RREF.html
2. Navigate to the text below the heading level 5 "Definition m matrix". This is the relevant exerpt of what NVDA reads.

```
We will use upper-case Latin letters from the start of the alphabet (a comma b comma c comma dot dot dot ) to denote matrices
```

### Expected behavior:
There should be an indication that the symbols are upper cased, such as the usual pitch raise that happens when announcing a normal upper case character.

### Actual behavior:
There is no indication that the symbols are capitalized. It can be inferred from context in this case, but is important in other situations where upper and lower cased versions of the same character are being used to refer to different objects, which happens semi-frequently.

### System configuration:
NVDA version:
master-14195,a5b17a10

NVDA Installed or portable:
Installed

Other information:

Windows version:
Windows 10 1511

Name and version of other software in use when reproducing the issue:
Firefox 54.0.1

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No

**Comment by jcsteh** [comment]
Confirmed.

Unfortunately, there's nothing that an be done in NVDA to fix or work around this, as MathPlayer converts the letters to lower case before passing them to NVDA. MathPlayer either needs to issue a pitch change command itself or indicate that it should be pronounced as a character and preserve the upper case. The latter change would also require some changes in NVDA, but at least we'd have soemthing to work with.

I'd suggest you report these MathPlayer issues to Design Science.

CC @nsoiffer.

**Comment by NSoiffer** [comment]
MathPlayer is generating a pitch change. Here's what MathPlayer sends to NVDA for that example:

<mark name='0'/> <break time='100ms'/> <mark name='0'/> <prosody pitch='130%'> <say-as interpret-as='characters'>a</say-as> </prosody> <break time='60ms'/> <mark name='0'/> comma <break time='60ms'/> <mark name='0'/> <prosody pitch='130%'> <say-as interpret-as='characters'>b</say-as> </prosody> <break time='60ms'/> <mark name='0'/> comma <break time='60ms'/> <mark name='0'/> <prosody pitch='130%'> <say-as interpret-as='characters'>c</say-as> </prosody> <break time='60ms'/> <mark name='0'/> comma <break time='60ms'/> <mark name='0'/> dot dot dot <mark name='0'/> 

Buried in there you will see "<prosody pitch='130%'>" around the letters.

I have a vague memory that NVDA strips all the markup except the "break"s from the string sent to NVDA to speak. Obviously, checking the code can verify this or say my vague memory is wrong.

Note: the MathTalk speech style (set in the MathPlayer control panel) will say "upper" for these letters. There's also a ClearSpeak preference to make it say "cap", but it is not something that the reader can easily set at this time. It is however possible to modify one of MathPlayer's rule to force it to say the caps, but talk to Design Science to find out how/what to do. It's simple, but you need to be careful.

**Comment by jcsteh** [comment]
[**@NSoiffer**](https://github.com/NSoiffer) commented on [17 Jul 2017, 16:18 GMT+12](https://github.com/nvaccess/nvda/issues/7402#issuecomment-315665681 "2017-07-17T04:18:46Z - Replied by Github Reply Comments"):
> I have a vague memory that NVDA strips all the markup except the "break"s from the string sent to NVDA to speak.

No; we do handle prosody commands and map them to NVDA pitch commands. However, I'm not seeing that happen. Reopening to investigate. Sorry for the false alarm, @nsoiffer, and thanks for the input.

**Comment by jcsteh** [comment]
I was running an older beta of MathPlayer. I updated and I now definitely get the pitch changes.

@Neurrone, what speech synthesiser are you using? This will only work on synth drivers which support inline pitch changes. eSpeak, OneCore and SAPI 5 all do. However, third party drivers may not. Note that raising pitch when reading capitalised characters is handled by actually changing the pitch of the synthesiser, but this can't be done for math, since it occurs interspersed with other text.

**Comment by Neurrone** [comment]
@jcsteh ah yeah changing to espeak fixed it, thanks.
