### ISSUE TITLE
need support for long tail platinum

### ISSUE THREAD

**Issue by adilsweet** [nvaccess/nvda#7403]
i need an addon for working with long tail platinum which is a search engines marketing software, it's a world biggest software for keyword research but unfortunately currently it does not supported by any version of NVDA. it's licence is expensive but if you can try it for making an addon, i would recommend you to download it's cracked version. if someone can make it volunteer then fine otherwise i'm ready to pay some dollars for your hardwork.

**Comment by josephsl** [comment]
If it wasn't for the fact that it mentioned cracked license, then it could have been considered. Closing as invalid for now.

**Comment by derekriemer** [comment]
Not sure invalid was necessary.
