### ISSUE TITLE
Brackets (and possibly other punctuation) is not read in math

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#7406]
### Steps to reproduce:
1. Go to http://www.rellek.net/book/s_strings_intro.html
2. Navigate to the text below the second level 1 heading "2.1 Strings: A First Look". This is the relevant exerpt of what NVDA reads in the paragraph after the heading.

```
Let n be a positive integer. Throughout this text, we will use the shorthand notation n to denote the n-element set 
the set 1 comma 2 comma dot dot dot comma n. 
```

### Expected behavior:
The second occurance of `n` should be correctly read as `[n]`. 

### Actual behavior:
`[n]` is actually read as `n`. This also happens when `[n]` is not a standalone expression, such as in the definition of the function `s` in that same paragraph. So it is impossible to distinguish between these 2 notations, `n` and `[n]`, making it hard to understand this page. I'm not sure if this applies for other types of similar punctuation as well.

### System configuration:
NVDA version:
master-14195,a5b17a10

NVDA Installed or portable:
Installed

Other information:
Happens even when punctuation setting was set to all (I didn't think the punctuation setting was the cause, but it was worth checking).

Windows version:
Windows 10 1511

Name and version of other software in use when reproducing the issue:
Firefox 54.0.1

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No

**Comment by jcsteh** [comment]
I can confirm the first omission of brackets. However, for the function, I get this:

> Then a function, s maps open bracket n close bracket to x

Is this the piece you were referring to?

Regarding the first case, unfortunately, it seems MathPlayer ignores the brackets completely here. There's nothing we can do about this on the NVDA side; the fix needs to be in MathPlayer.

CC @NSoiffer.
