### ISSUE TITLE
Chrome app "line": chat, after saving file, NVDA return to (section editable) field

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#7408]
### Steps to reproduce:
1. Open Google Chrome.
2. Download and install [line](https://chrome.google.com/webstore/detail/line/menkifleemblimdogmoihpfopnplikde?hl=en).
3. Login account. (Users need to register E-mail address on mobile.)
4. Choose a friend to chat.
(Here, my friend sent me three files in advanced.)
5. Move to file1, and press "save" button to save it.

### Expected behavior:
after saving file, NVDA should stay at the first "save" button. Then, user will press "b" to find next "save" button to save file2 and file3.

### Actual behavior:
after saving file, NVDA return to (section editable) field.

### System configuration:
* NVDA version: 2017.2 installed
* LINE: 1.4.13
* Chrome: 59.0.3071.115

**Comment by jcsteh** [comment]
This is a choice that has been made by the developers of Line. If you think this should be changed, please file a request with the developers of Line. Thanks.
