### ISSUE TITLE
File Explorer / Windows Explorer - selection not read correctly when multiple files selected

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#7413]
Tested in both Windows 10 and Windows 7.
In File Explorer or Windows Explorer (WINDOWS+E to open), the following behaviour is observed:
- In the file list, press SHIFT+DOWN ARROW to select the current file and the one below it.
Expected: NVDA should advise the name of the newly moved to file and the number of files selected.
Actual behaviour: NVDA reads the name of the newly moved to file just as if it was the only selected file (as if DOWN ARROW had been pressed).

- Again in the file list, press CONTROL+A to select all.
Expected: NVDA to advise that all files have been selected
Actual behaviour: All files are selected, however NVDA does not report anything.

In addition, in either case:
- Press NVDA+SHIFT+UP ARROW or NVDA+SHIFT+S to read selection.  NVDA reads "No selection".

**Comment by jcsteh** [comment]
[**@Qchristensen**](https://github.com/Qchristensen) commented on [18 Jul 2017, 14:27 GMT+12](https://github.com/nvaccess/nvda/issues/7413#issue-243581653 "2017-07-18T02:27:30Z - Replied by Github Reply Comments"):
> - Again in the file list, press CONTROL+A to select all.
> Expected: NVDA to advise that all files have been selected

I don't think we'd want to hard code behaviour for select all; that would be fragile in different controls, locales, etc. I guess the best thing we could do here would be to announce the number of selected items.

> - Press NVDA+SHIFT+UP ARROW or NVDA+SHIFT+S to read selection.  NVDA reads "No selection".

This command is only documented as working for text documents. #1839 proposes extending this to cover lists.

Better reporting of multi select lists is covered by #5005, so closing as duplicate. I still have no idea how to implement this such that it won't really suck for performance, though. :)
