### ISSUE TITLE
Table navigation is broken if the table has caption. Ctrl + Alt + Arrows doens't work.

### ISSUE THREAD

**Issue by andrii-morozov** [nvaccess/nvda#7426]
### Steps to reproduce:
https://codepen.io/anon/pen/MoNBjX

### Expected behavior:
The navigation happens as expected.

### Actual behavior:
Not in a table cell.

**Comment by jcsteh** [comment]
There are two errors in this code:

1. You use roles of row and gridcell without a corresponding role of grid. At least in Chrome, this completely breaks the accessibility of the table. Adding role="grid" to the table fixes this and table navigation works as expected. Removing the row and gridcell roles would probably also fix this.
2. You have role="row" on the caption. A row must contain cells; a caption is special.
