### ISSUE TITLE
Include six in misc deps distribution

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#7429]
Hi,

As part of porting NVDA to Python 3 (#7105), at least two dependencies requires use of six compatibility layer:

* ConfigObj 5.x.y (#4470)
* wxPython 4.0.0 (#7077)

As noted in #7077, six comes with wxPython 4. Thus I propose that we include six package once wxPython 4 is ready, or add version 1.10.0 of this package into misc-deps until wxPython 4 is ready. My preference is for the former (I'll use the latter while porting NVDA source code to Python 3).

Thanks.

**Comment by josephsl** [comment]
Hi,

PyPI link: https://pypi.python.org/pypi/six/1.10.0

**Comment by leonardder** [comment]
Could you give some examples of why six helps in porting that are specific to NVDA's code base?

**Comment by josephsl** [comment]
Hi, although we won’t be using six in NVDA code directly, some dependencies requires this such as ConfigObj and wxPython 4. Thanks.
