### ISSUE TITLE
Windows 10 OCR

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#7432]
The Windows 10 OCR inclusion in 2017.3 is not mentioned in the What's New document.  Especially as it is a great resource, it deserves a mention there as well as in the User Manual.

Andrew
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by leonardder** [comment]
Thanks for pointing this out. However, al though it is planned to have Windows 10 OCR support in NVDA 2017.3, it has not yet arrived in the master branch. As soon as it will arrive, appropriate information will be added. See also [this article about NVDA's release process](https://github.com/nvaccess/nvda/wiki/ReleaseProcess). Closing.
