### ISSUE TITLE
Legend title is not readout when selecting same page link to input field using space or enter.

### ISSUE THREAD

**Issue by matter3** [nvaccess/nvda#7438]
When selecting a link that is a same page link to a form field, if you use enter or space to select that link you will not be read out the legend title for that field by NVDA.

### Steps to reproduce:
>
> 1. Open Internet Explorer 11 with NVDA enabled
> 2. Navigate to this CodePen: https://codepen.io/matter3/pen/EvxRwW
> 3. Put focus on the link and hit enter or space.
> 4. Note that focus is shifted to the input field

### Expected behavior:
> The screenreader should readout the legend title.
### Actual behavior:
> The screenreader does not readout the legend title as it normally does when clicking on the link.

### System configuration:
NVDA version:
2017.2

Running in a VM.

Windows version:
Windows 10 Enterprise Evaluation

**Comment by Adriani90** [comment]
This works as expected with Chrome canary 133, Firefox 133 and NVDA 2024.4.1. Closing as works for me.
