### ISSUE TITLE
Display model bug with negative coordinates

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7441]
CC @MichaelDCurran

### Steps to reproduce:
1. Start Wordpad
2. Retrieve the location for the foreground object. Here, it is (-8, -8, 1382, 744)
3. Create a DisplayModelTextInfo for the foreground object
    ```
    >>> dm=displayModel.DisplayModelTextInfo(fg,"all")
    ```
4. List all the rectangles with a left coordinate >2000
    ```
    >>> [rect for rect in dm._storyFieldsAndRects[1] if rect[0]>2000]
    ```

### Actual behavior:
The following rectangle is returned: (65528, 159, 1374, 708)

### Expected behavior:
This rectangle should be (-8, 159, 1374, 708)

### Technical background
The list of rectangles is provided as a wide character string by NVDAHelper. These wide characters are converted back to int using ord in displayModel.getWindowTextInRect, however this assumes that the resulting coords should be unsigned ints, which is incorrect.

### System configuration:
NVDA version: Next, but this will also occur in 2017.2 as this code is untouched for years
NVDA Installed
Windows 10 Creators update Dutch, DPI set at 100%

**Comment by michaelDCurran** [comment]
We need something like:
```
def wchartoint(c):
     i=ord(c)
     return i if i<32768 else i-65536
  ```

And use that in place of all calls to ord on line 171 of displayModel.py

We could possibly use struct.unpack or ctypes casting, but that would 
involve either converting the string or accessing its raw pointer etc.

If you can validate that this gives the correct results, feel free to 
create a pr.
