### ISSUE TITLE
Allow braille display specific settings in the GUI

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7452]
In NVDA's voice settings, a synthesizer can implement specific settings, such as inflection, etc. For this, the VoiceSettingsSlider class is available for use. I propose generalizing this custom settings system to allow custom settings for braille displays as well. Possibilities include:

* Dot firmness
* Enable/disable braille input. This is desirable for the handy tech driver, since one of the handy tech devices uses the space keys for either scrolling or braille input
* Enable/disable active tactile control, also for Handy Tech devices

CC @BramD

**Comment by bramd** [comment]
Looking at this code for speech synthesizers, I start to wonder if it would make sense to extend the SynthSettingsRing to a more generic quick settings ring and include some of the braille settings there as well. Any thoughts about this?

**Comment by leonardder** [comment]
[**@bhavyashah**](https://github.com/bhavyashah) commented on [16 sep. 2017 15:30 CEST](https://github.com/nvaccess/nvda/issues/7452#issuecomment-329968546 "2017-09-16T13:30:19Z - Replied by Github Reply Comments"):
> there is a rather small cross-section of NVDA users that use a
> combination of speech and Braille full time. 

Why do you think this is the case? From my experience as a trainer for visually impaired people, I can safely say this statement is, well, simply not true :)

Also note that the synth settings ring only shows its settings when there is an active synthesizer. The ring would also only show braille settings if the display supports them.

I think this must be delayed until #4877 is in core, that is, if we want to go for a generic approach for driver specific settings.

**Comment by leonardder** [comment]
Making display specific settings available in the gui requires an initialized display to work with, which doesn't fit in the current UX. Therefore, it might be best to wait for #7302 to arrive.

**Comment by beqabeqa473** [comment]
hi.

found a regression.

when using synthiser which is using LanguageInfo class in synthDriver class an name error is thrown.

please fix this as soon as possible.

fix should be trivial, instead of ID write id in the following line.
		super(LanguageInfo,self).__init__(ID, displayName)

should be

		super(LanguageInfo,self).__init__(id, displayName)
