### ISSUE TITLE
nvda key labeller: a different approach

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#7457]
Hi.

A feature request in NVDA is the possibility for the user to label keys. What if a dialog was created, similar to a dictionary dialog, where the user can define what NVDA speaks after a key press?

For example: I want Control+C to announce 'Copy' no matter where I am. I would open the Key Labeller dialog, press in a hot key field the Control+C combination. Then a tree view item similar to the Input gestures dialog's way would pop up the shortcut to confirm. I would then go to an edit box to type my label, which would be 'Copy'. I can tab to OK, then press Enter. This combo is now in a list where I can add or remove etc.

The only issue I would find is pressing Tab, but the user wouldn't intentionally move past the hot key field unless they'd want to edit the description. Thus, the keyboard combination would be absent, but spoken. The edit box would stay. If they wanted to edit the keyboard shortcut, perhaps remove it entirely and start over.

This may be better for an add-on, but consider it.

**Comment by fernando-jose-silva** [comment]
I really liked the suggestion.
It would solve a lot of the waiting we have for translation of nvda addons that delay and also waiting for the introduction of resources in nvda.

**Comment by leonardder** [comment]
I belief this would be suitable for an add-on, but i see no valid reason to have this in NVDA core. I mean, why should you have NVDA announce that you copied something when you pressed control+c? If you want to make sure your key presses did come through, you can enable speak command keys.

**Comment by fernando-jose-silva** [comment]
Turning on the command keys to speak is annoying, you will hear the keys being pressed anywhere.
At how much I just want to hear copied with ctrl + c and pasted with ctrl + v.
I can customize my application as I can customize my speech, for example, many shortcuts in my Brazilian language are not being spoken, as an example ctrl + b in the word Brazil is save, having this functionality I would already be able to adapt it today, and You would not have to wait for an implementation of nv acces.
Other screen readers already have these two features, how to customize what to speak at each keystroke, and natively speak basic controls like copy and paste.

**Comment by fisher729** [comment]
I agree, this would be good if it were in an addon.

**Comment by bhavyashah** [comment]
As per https://github.com/nvaccess/nvda/issues/7457#issuecomment-319790002, should we close this ticket since the reporter agrees that this feature request is add-on territory and unsuitable for core? @ehollig

**Comment by leonardder** [comment]
@bhavyashah: Agreed. See also https://github.com/nvaccess/nvda/issues/75#issuecomment-155277515 for @MichaelDCurran's rationale about why speaking cut, copy and paste won't be implemented for all cases.

**Comment by leonardder** [comment]
I labelled this invalid, since @fisher729 initially requested this but now agrees that it would best fit in an add-on. It felt a bit harsh to do a won't fix here.
