### ISSUE TITLE
NV Access Website: Suppress Browser HTTPS Warnings

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#7460]
Since all pages on the main NV Access site are now served using HTTPS, browsers now throw a warning whenever a link is clicked that redirects to a standard HTTP link on the old NVDA-Project.org site. Could all cases of these links be changed to reference GitHub pages directly? This would fix these warnings from being displayed.

**Comment by Adriani90** [comment]
Is this issue still valid? cc: @Qchristensen, @feerrenrut, @michaelDCurran

**Comment by Andre9642** [comment]
I found several issues about this.

Consider the following page: https://www.nvaccess.org/download/

First, in the header of pages (in the source code), there is the following lines:

```
		<!--[if IE]>
		  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
```

The link http://html5shiv.googlecode.com/svn/trunk/html5.js returns a 404.
It seems that the good link is https://raw.githubusercontent.com/aFarkas/html5shiv/master/dist/html5shiv.min.js

Then, the following link redirect to HTTP URLs whereas HTTPS versions are available and preferable:

- Get extra voices -> http://community.nvda-project.org/wiki/ExtraVoices -> https://github.com/nvaccess/nvda/wiki/ExtraVoices
- Get add-ons to enhance NVDA -> http://addons.nvda-project.org/ -> https://addons.nvda-project.org/
- Find Out More -> http://community.nvda-project.org/wiki/Connect -> https://github.com/nvaccess/nvda-community/wiki/Connect

**Comment by Qchristensen** [comment]
If pages are redirecting, EG Get extra voices redirecting from http://community.nvda-project.org/wiki/ExtraVoices to https://github.com/nvaccess/nvda/wiki/ExtraVoices it makes sense to update the links if for no other reason, than to save the time taken to redirect (usually minimal, but still).  

In terms of this issue though, all of those examples are auto-redirecting to the appropriate HTTPS page for me, and I'm never seeing a warning in Chrome, Edge, Firefox or IE?

**Comment by bhavyashah** [comment]
@elliott94  According to https://github.com/nvaccess/nvda/issues/7460#issuecomment-455427208, "In terms of this issue though, all of those examples are auto-redirecting to the appropriate HTTPS page for me, and I'm never seeing a warning in Chrome, Edge, Firefox or IE?" I concur with this assessment. Please share if you still experience this issue though.

**Comment by elliott94** [comment]
At the time of the opening of this issue, I believe there was a button present on a page which redirected from HTTPS to HTTP, resulting in this error. Happy to close for now... unless I can find the page again! :)
