### ISSUE TITLE
NVDA and Windows 10 Mail: Error when backspace is pressed

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#7466]
Steps to Reproduce:
1. Open Windows 10 Mail
2. Go to a message in the message list.
3. Select it. It opens in browse mode.
4. Press Backspace to go back to the message list.
An error sound plays in the snapshots. I have attached a brief portion of my log. Running the latest Master snapshot of NVDA. This also occurs with add-ons disabled, so that's not the issue.
IO - inputCore.InputManager.executeGesture (22:10:27.618):
Input: kb(laptop):backspace
ERROR - scriptHandler.executeScript (22:10:27.770):
error executing script: <bound method Dynamic_UIAEditableTextWithSuggestionsMailWordDocumentEditableTextWithoutAutoSelectDetectionWordDocumentUIA.script_caret_backspaceCharacter of <NVDAObjects.Dynamic_UIAEditableTextWithSuggestionsMailWordDocumentEditableTextWithoutAutoSelectDetectionWordDocumentUIA object at 0x04DDF6D0>> with gesture u'backspace'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 222, in script_caret_backspaceCharacter
  File "editableText.pyc", line 212, in _backspaceScriptHelper
  File "editableText.pyc", line 93, in _hasCaretMoved
  File "NVDAObjects\UIA\wordDocument.pyc", line 23, in __ne__
  File "NVDAObjects\UIA\__init__.pyc", line 283, in __eq__
COMError: (-2146233079, None, (None, None, None, 0, None))
DEBUG - treeInterceptorHandler.killTreeInterceptor (22:10:27.878):
Killed treeInterceptor: <nvdaBuiltin.appModules.hxmail.MailWordDocumentTreeInterceptor object at 0x04E0DA70>
IO - speech.speak (22:10:27.884):
Speaking [u'Navigation  grouping']
IO - speech.speak (22:10:27.905):
Speaking [u'Navigation  button  expanded']
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.uiaDebugLogging (22:10:27.923):
W10: UIA object name: Message, event: nameChange, app module: <'hxmail' (appName u'hxoutlook', process ID 9164) at address 4cfb6d0>, automation Id: RootFocusControl, class name: _WwG
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.uiaDebugLogging (22:10:27.934):
W10: UIA object name:  ( message text) , event: nameChange, app module: <'hxmail' (appName u'hxoutlook', process ID 9164) at address 4cfb6d0>, automation Id: MailItem, class name: MailItem

**Comment by Adriani90** [comment]
@fisher729 are you still seeing this issue?
I am not getting any error when using NVDA alpha-17099,0d2a1525.

**Comment by fisher729** [comment]
Hi.

The issue has been sorted out, somehow.

**Comment by Adriani90** [comment]
Thanks for reporting back, I am closing as works for me.
