### ISSUE TITLE
Add accelerator for "Windows 10 OCR..." option

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#7477]
### Steps to reproduce:

1. Open the NVDA preferences submenu (`NVDA+n` then `p`)
2. Notice that all options have an accelerator set except for "Windows 10 OCR..."
3. Press 'w'
4. Notice that the "Windows 10 OCR... " options dialog is opened.

### Expected behavior:
Expected this item to have an accelerator explicitly set (an underlined w for instance)

### Actual behavior:
There is no explicit accelerator, and but there is an implicit accelerator: `w`

### System configuration:
NVDA version: 14290,07052e9d

NVDA Installed or portable:
installed.

Windows version:
Windows 10

**Comment by feerrenrut** [comment]
Setting as priority 2 since its a recent feature, and this will be very quick to fix.

**Comment by feerrenrut** [comment]
We don't want this to go into the next release (2017.3), since it will affect the translations and is a minor issue.

**Comment by josephsl** [comment]
Hi, one way to get around this is telling translators to add pneumonics for this item in their po files (Korean uses this approach). Thanks.

**Comment by leonardder** [comment]
Note that this would be a waste of time if the mile stone for #577 is 2017.3

**Comment by ehollig** [comment]
Taking into note #577, I was taking a look at this. Is there a reason that activateBrailleSettingsDialog does not have an accelerator either? As the Braille settings dialog contains a lot of options, I think this would be a good dialog to add an accelerator as well.

**Comment by bhavyashah** [comment]
@ehollig By accelerator, I believe @feerrenrut meant the alphabet that is underlined in the text of that menu/submenu item which can be pressed in that menu/submenu to activate the same item directly. Braille Settings already has 'r' as its accelerator too. You can verify this by pressing NVDA+N, P, R.
It seems to me that you might have misinterpreted the original request as adding an NVDA+Ctrl+logical alphabet styled keyboard shortcut to open the Windows 10 OCR dialog, and are proposing something similar for the Braille Settings too, which currently lacks an NVDA+Ctrl+logical alphabet form of command. Having said that, this does make sense to me, but should probably be addressed by a separate ticket.
