### ISSUE TITLE
Where can i find this complete emoji list

### ISSUE THREAD

**Issue by ingf** [nvaccess/nvda#7481]
hi, Where can i find this complete emoji list, or what is the solution, thak you!

https://github.com/nvaccess/nvda/blob/8234a65269ac9fc627be64d7276e00db265fd2a4/source/locale/zh_CN/symbols.dic#L299

**Comment by fernando-jose-silva** [comment]
Good afternoon.
Taking advantage of this call, I would like to ask a question:
I understand that it is possible to read the emugis using the windowsonecore synthesizer.
My doubt is:
It is possible to read the emugis using other speech synthesizers, like nuance vocalizer exprecive, SpeechPlayer in Espeak, speak?
Thank you very much, if it is not possible, and it is necessary to use the windowsonecore synthesizer, is it possible to have speech synthesizers and SpeechPlayer in Espeak read the emugis?
If this capacity could be of the nvda and independently of the synthesizer would be an even greater gain.

**Comment by dkager** [comment]
The "complete emoji list" is available [from Unicode.org](http://unicode.org/emoji/charts/full-emoji-list.html).

Reading emoji is already covered in #6523. Marking this as duplicate.
