### ISSUE TITLE
Notepad++ and Braille: scrolling problem

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#7482]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by dreinn** [comment]
Confirmed but this is a duplicated of this thread:
https://github.com/nvaccess/nvda/issues/7419

At the moment, a display braille with notepad++ is unusable. Hope will be fixed for the 2017.3!

**Comment by leonardder** [comment]
@MichelSuch: In the future when making a mistake, please use the edit button above your comment to edit your initial message instead of creating a new ticket. Thanks a lot.
