### ISSUE TITLE
Problems reading email in Outlook inbox

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7486]
I gave the nvda to a friend.
This friend used the jaws and decided to give a chanse to the nvda.
However on this machine I have an error that I could not solve.
When navigating with the arrows through the inbox nvda does not report the most resentful emails, while giving focus these emails nvda informs only edit.
By moving through this inbox to the older emails the emails are reported normally.
It has other input boxes configured in this outlook that do not suffer from this problem.
I use Outlook 2016 and I do not have this problem.
I believe it is a setting that nvda is not able to handle correctly.
He reported that when he used the jaws he did not have this problem.
As I do not know which outlook configuration I could do this I decided to open a call and send the log to see if anyone can help me.
Unfortunately this machine is far from me and I can not have physical access to it.
Information:
Nvda master 14294.
Windows 10 64bits 15063.540.
Follow the log:

IO - inputCore.InputManager.executeGesture (20:15:49.381):
Input: kb(laptop):downArrow
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (20:15:49.979):
oleacc.AccessibleObjectFromEvent with window 1639720, objectID 62 and childID 0: [Error -2147467259] Erro não especificado
IO - speech.speak (20:15:50.078):
Speaking [u'cursor Editar']
IO - inputCore.InputManager.executeGesture (20:16:00.168):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (20:16:00.321):
Developer info for navigator object:
name: u'com anexo'
role: ROLE_LISTITEM
states: STATE_FOCUSABLE, STATE_SELECTABLE, STATE_READONLY, STATE_SELECTED
isFocusable: True
hasFocus: False
Python object: <appModules.outlook.UIAGridRow object at 0x0A129090>
Python class mro: (<class 'appModules.outlook.UIAGridRow'>, <class 'NVDAObjects.behaviors.RowWithFakeNavigation'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: ''
location: (0, 0, 0, 0)
value: None
appModule: <'outlook' (appName u'outlook', process ID 16516) at address a0bdfb0>
appModule.productName: u'Microsoft Outlook'
appModule.productVersion: u'16.0.8326.2070'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 3475622
windowClassName: u'OutlookGrid'
windowControlID: 4704
windowStyle: 1442840576
windowThreadID: 17416
windowText: u'modo de exibi\xe7\xe3o de tabela'
displayText: u''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x73e52b8 at a07cc60>
UIA automationID: 
UIA frameworkID: 
UIA runtimeID: (42, 3475622, 3, -470, -1721483136, 30609665)
UIA providerDescription: [pid:16516,providerId:0x0 Main(parent link):Unidentified Provider (unmanaged:OUTLOOK.EXE)]
UIA className: LeafRow

**Comment by dkager** [comment]
Have you tried disabling the reading pane?

**Comment by fernando-jose-silva** [comment]
Actually the reading panel is disabled, I have never tried to do the opposite, reactivate it.

I will try to play with this setting as soon as possible and return.

Thank you very much.

 

De: Davy Kager [mailto:notifications@github.com] 
Enviada em: sábado, 12 de agosto de 2017 07:48
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>; Author <author@noreply.github.com>
Assunto: Re: [nvaccess/nvda] Problems reading email in Outlook inbox (#7486)

 

Have you tried disabling the reading pane?

**Comment by PratikP1** [comment]
@fernando-jose-silva, Try the following.
Outlook groups conversations by date, pacing today at the very top of the conversation list. That group is collapsible. Check if the top most item in the grouping is collapsed. Use the right arrow key to expand the group. The announcements are a little too verbose for my taste. It may be that the collapsed state is not being picked up.

The log, as you've provided, is not likely to give us much. A little more log with keyboard input and speech output could help.

**Comment by fernando-jose-silva** [comment]
Unfortunately the group is already expanded, when the nvda pronounces edit, if press enter the message is opened and read.
I'll take the complete log and attach

Enviado do meu iPhone

**Comment by fernando-jose-silva** [comment]
[Arquivo 12-08-17 13 51 20.txt](https://github.com/nvaccess/nvda/files/1219928/Arquivo.12-08-17.13.51.20.txt)

**Comment by fernando-jose-silva** [comment]
Ataxe

**Comment by ehollig** [comment]
@fernando-jose-silva, does this still occur with the latest version of Outlook? Does it happen with a different synthesizer besides vocalizer expressive? It appears there a lot of errors with outdated or inaccessible addons. Does the issue occur with all addons disabled?

**Comment by fernando-jose-silva** [comment]
I was able to solve the problem by reinstalling the nvda of this person, now what it took for the error to be generated will be an unknown.
Thank you very much.

**Comment by ehollig** [comment]
Closing as invalid from https://github.com/nvaccess/nvda/issues/7486#issuecomment-342017769
