### ISSUE TITLE
can't get landmark from a pdf in edge

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#7490]
### Steps to reproduce:

1. Open this pdf in edge.
2. Read down by line, and move forward by character after my objective and proficiency.
3. Note this error.
error executing script: <bound method EdgeHTMLTreeInterceptor.script_moveByCharacter_forward of <NVDAObjects.UIA.edge.EdgeHTMLTreeInterceptor object at 0x051FCF90>> with gesture u'right arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "cursorManager.pyc", line 196, in script_moveByCharacter_forward
  File "cursorManager.pyc", line 141, in _caretMovementScriptHelper
  File "speech.pyc", line 749, in speakTextInfo
  File "treeInterceptorHandler.pyc", line 217, in getTextWithFields
  File "NVDAObjects\UIA\edge.pyc", line 179, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 588, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 502, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\edge.pyc", line 137, in _getControlFieldForObject
AttributeError: 'UIA' object has no attribute 'landmark'

### Expected behavior:
The info on those lines should read.

### Actual behavior:
An error.

### System configuration:
Version: next-14293,8d368f7e

NVDA Installed or portable: Installed

Other information:
@leonardder might this be a regression from your localized landmarks fix? Thought'd check.

**Comment by derekriemer** [comment]
PDF: 
[resume.pdf](https://github.com/nvaccess/nvda/files/1219998/resume.pdf)

**Comment by leonardder** [comment]
Ough, this is very like caused by the landmarks localisation fix indeed. Could you please double check this with 2017.2? If this works properly there, I will try to fix this in time for 2017.3, probably not that difficult.

@MichaelDCurran: I'm thinking about adding a landmark property to the base UIA class, but we could even consider adding it to the base NVDAObject, defaulting to None.

**Comment by leonardder** [comment]
This is either a p1 or a p2 to me, since it breaks PDF reading in Edge in a major way and is probably a regression.

**Comment by derekriemer** [comment]
hold on, I will have to get a 2017.2 installer.

**Comment by derekriemer** [comment]
yes, this is a regression from 17.2

**Comment by derekriemer** [comment]
yes, this is a regression from 17.2

**Comment by michaelDCurran** [comment]
A base NVDAObject landmark property is fine with me.

**Comment by derekriemer** [comment]
yes, this is a regression from 17.2
