### ISSUE TITLE
OneCore Voices: Support faster speech rates, greater pitch range, etc.

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#7498]
Compared with NVDA, Narrator is able to speak at faster rates with the OneCore Voices. It can also access a much wider pitch range. In addition, the rate set in Narrator is not affected by the rate set in Windows Settings, whereas NVDA is affected by this. This is because Narrator used an API which was previously private. That API has now been made public, so NVDA will be able to use it.

See the [Options property on the SpeechSynthesizer class](https://docs.microsoft.com/en-us/uwp/api/windows.media.speechsynthesis.speechsynthesizer#Windows_Media_SpeechSynthesis_SpeechSynthesizer_Options_) and the [SpeechSynthesizerOptions class](https://docs.microsoft.com/en-us/uwp/api/windows.media.speechsynthesis.speechsynthesizeroptions). Note that AudioPitch, AudioVolume and SpeakingRate (the properties we want) were only introduced in Windows 10 Insider 10.0.16257.0.

Unfortunately, we can't use these just yet for a few reasons:

1. We need a newer version of the Windows 10 SDK, but versions after 10.0.15063 only work with Visual Studio 2017. We can't yet build with Visual Studio 2017. So, this is blocked by our move to VS 2017, which is in turn blocked by support in SCons.
2. This is still a preview version of the SDK. Even once it's out of preview, it might be a while before it gets installed on AppVeyor.

Implementation notes:

1. Because this will only be available in later builds of Windows 10, we'll need to test for support of this new API at runtime. I know UWP provides a way to do this, but I've never done it myself.
2. Aside from testing for the API, we'll probably still need to keep the code around which adjusts rate, etc. with SSML to work with earlier Windows 10 builds. We might just be able to pass the default rate, volume, etc. to `_OcSsmlConverter` if the new API is supported instead of passing the cached user settings, but I'm not certain. Either way, this part of the code is going to get a bit ugly because we have to support these two cases.

**Comment by josephsl** [comment]
Hi, the API itself became public since build 16225 and later (according to UWP docs). Thanks.

**Comment by jcsteh** [comment]
There's a bit of confusion as to when this became public. The documentation I linked to (which is supposedly the official UWP documentation) says 16257. However, I've also seen references which suggest earlier. It's safe to say that it's now available in Insider builds and the preview SDK.

**Comment by zersiax** [comment]
Seeing a possible glitch here, in latest next build on latest windows 10 stable, changing the tts settings in either control panel or Narrator Settings does not appear to influence NVDA when speaking through oneCore, where I have observed this happening a few months ago. Has something changed in regards to this?

**Comment by jcsteh** [comment]
Narrator Settings would never affect it, only Windows Speech Settings.

Nothing has changed in the driver. Something might have changed in Windows
I guess. Even if that is so, there's nothing we can do to work around it
until this issue is implemented (which is currently blocked by quite a few
things as noted above).

**Comment by zersiax** [comment]
Found it already. There's quite a few places where speech rates can be set and only one of them works, e.g. the ones in narrator settings and control panel's tts settings don't work, only the settings in another part of the windows+i settings dialog seem to take :)

**Comment by leonardder** [comment]
@jcsteh: I belief all blocking cases for this issue are resolved, right? If so, we can safely remove the blocking label and set a priority for this.

**Comment by jcsteh** [comment]
As far as I know, yes, this issue is no longer blocked. It's not as simple to fix as it seems, though, since you have to be mindful of the driver's internal speech queue; you can't just set the param..

**Comment by jcsteh** [comment]
I just spent over an hour implementing this, only to discover that it doesn't actually let us access the faster rates. It's still restricted to the maximum rate we can get in Speech Settings, only it's not impacted by that setting like our previous SSML code was. It does allow us to access the greater pitch range, just not the greater rate range. So, Narrator must still be using the old private API (which does work but we can't legally use it). The string "MSTTS.SpeakRate" can still be found in Narrator's srh.dll, which would seem to confirm this.

Anyway, the code, useless as it currently is, is in the i7498OcSpeechOptions branch of my fork: https://github.com/jcsteh/nvda.git

@MichaelDCurran, would you be able to follow this up with Microsoft? Alas, this means we'll probably have to wait for yet another Windows version before we can access these rates.

**Comment by leonardder** [comment]
@michaelDCurran, @jcsteh: How is this in the October update?

**Comment by manish10** [comment]
I reached out to the narrator team to ask about this. They are no longer using a private API for this. This was the response from the developer:
<snip>Please ask the NVDA devs if they’ve looked at the SpeechSynthesizerOptions class. That’s the public API that we’ve been using to set the rate since RS4. </snip>

Are we also using the options class mentioned above?

**Comment by jcsteh** [comment]
I have a branch which uses this class, yes. Unfortunately, while it does change the rate, it doesn't allow access to the faster rates, only the normal maximum. Perhaps something got fixed recently? Last time I looked into this, I ran the strings utility to extract strings from the Narrator executables and saw the MSTTS.SpeakRate string, which is only used in the private API. That's a pretty strong suggestion that they were still using it at this point.

**Comment by manish10** [comment]
You are correct. Here is the response from the developer:

<snip>I’m sorry, I was mistaken. We didn’t start using the public SpeechSynthesizerOptions API until RS5 (the current insider version, which will be released soon).</snip>

**Comment by jcsteh** [comment]
I rebased the i7498OcSpeechOptions branch in my fork to current master. Unfortunately, with the Windows 10 1809 update (Version 1809 (OS Build 17763.55)), the maximum rate available via this API is still only the normal max rate, not the boosted rates available to Narrator. Furthermore, Narrator's SRH.dll still contains the string "MSTTS.SpeakRate", which is used in the private API to access the boosted rates. That suggests they're still not using the public API. I'm following up with Microsoft.

For reference, I saw the MSTTS.SpeakRate string using this command. (The strings utility is from GNU binutils.)
`strings --encoding=l SRH.dll`

**Comment by jcsteh** [comment]
I've updated my branch to gracefully handle older versions of Windows 10 where these features aren't available.

**Comment by jcsteh** [comment]
I'm not sure whether there was something weird on my system or I tested something incorrectly. Previously, the rates available to Narrator were vastly different to those available in the normal system speech settings; 100% in Narrator was completely unintelligible due to how fast it was. Now (perhaps due to me recently resetting Narrator's voice), they're equivalent. Furthermore, 100% in current NVDA builds is equivalent to 100% in Narrator (and 100% in system speech settings). So, I guess what I was experiencing previously was a bug. Since things are now equivalent in 1809 (and there's no advantage to the old way of doing things), I think we're good to ship this.

Unfortunately, AppVeyor doesn't yet have the required version of the Windows 10 SDK (10.0.17763.0). See appveyor/ci#2673.

**Comment by PratikP1** [comment]
@jcsteh wrote:
> The i7498OcSpeechOptions branch in my fork now also sets the appended silence and punctuation silence to the minimum. This greatly reduces the delays between utterances and after punctuation, thus resulting in a much better screen reading experience.

Practically speaking, does this mean that the pauses will be shortened between certain punctuation marks and the beginning of the next content?

**Comment by michaelDCurran** [comment]
This branch now compiles on appveyor. Not sure why that Windows SDK issue is still open.

**Comment by jcsteh** [comment]
> Practically speaking, does this mean that the pauses will be shortened between certain punctuation marks and the beginning of the next content?

Yes.

**Comment by jcsteh** [comment]
https://www.appveyor.com/updates/ confirms this. The new image containing this SDK went live on 9 November.
