### ISSUE TITLE
In UserGuide change links which point to community.nvda-project.org/ to appropriate sites

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#7500]
In a UserGuide are links, which point to community NVDA page, which is defunct. So change them so they will point to new locations.

### Steps to reproduce:
For example:
1. Open an UserGuide (suggest that it should be opened in Notepad++)
2. Go to line number 1738

### Expected behavior:
The links should direct us to pages, where topics are placed. E.G.

> For more information, please see the Developer Guide available [on the NV Access web site https://www.nvaccess.org/files/nvda/documentation/developerGuide.html].

### Actual behavior:
There is text with link which directs us to community page and because this page does not exist, then we are redirected to main NVDA page on github.

> For more information, please see the Developer Guide available from [the Development section of the NVDA web site http://community.nvda-project.org/wiki/Development].

### System configuration:
NVDA version:
last stable and UG version is: 13716
Name and version of other software in use when reproducing the issue:
Notepad ++ to easily locate community pages

**Comment by josephsl** [comment]
Hi, some were changed in 2017.3 version, but I do know there are places that still point to the community subdomain. CC @JCSTeh

**Comment by ehollig** [comment]
@josephsl, has this been resolved in #7662 a part of docs17.4?

**Comment by josephsl** [comment]
Hi, yes, resolved. Thanks.

**Comment by ehollig** [comment]
Thanks @josephsl. Closing from https://github.com/nvaccess/nvda/issues/7500#issuecomment-341816098
