### ISSUE TITLE
Windows Onecore Voices and sapi5 respond not automatic

### ISSUE THREAD

**Issue by lallerke1** [nvaccess/nvda#7502]
If we use nvda with windows onecore voices, there is a lag with the speech by several pc-es using windows 10.

**Comment by PratikP1** [comment]
This is most likely due to Windows API being used. @jcsteh I don’t think NVAccess can do anything about this behavior for now. Microsoft will have to speed up the responsiveness of OneCore through the API. Correct?

**Comment by fisher729** [comment]
Further information may be needed about this ticket, such as if Master or Next is used. There is no doubt a lag when using SAPI5, but that is the fault of speech synth vendors and Microsoft's API limitations. For example, the voices built into Windoes may be less laggy than a SAPI5 synth purchased. OneCore support is quite good, and provides better responsiveness. No doubt it is slower than say eSpeak, but it is is as good as it can be for now.

**Comment by jcsteh** [comment]
[**@lallerke1**](https://github.com/lallerke1) commented on [16 Aug 2017, 19:23 GMT+10](https://github.com/nvaccess/nvda/issues/7502#issue-250563260 "2017-08-16T09:23:38Z - Replied by Github Reply Comments"):
> If we use nvda with windows onecore voices, there is a lag with the speech by several pc-es using windows 10.

Please be more specific.
How long is the lag?
Where does it occur: between the time you press a key and the speech starting, between phrases, etc.?
What exact version of NVDA did you test with?
What exact build of Windows 10?
Which exact voice were you using?
What rate did you have it set to?
You mentioned "several PCs". Have you seen different results on other PCs?

[**@PratikP1**](https://github.com/PratikP1) commented on [17 Aug 2017, 01:25 GMT+10](https://github.com/nvaccess/nvda/issues/7502#issuecomment-322808297 "2017-08-16T15:25:38Z - Replied by Github Reply Comments"):
> Microsoft will have to speed up the responsiveness of OneCore through the API.

Are you noticing specific responsiveness problems? OneCore seems very responsive here now, especially after #7495. It's slightly less responsive than eSpeak, but certainly more responsive than most SAPI 5 synthesizers and probably similar to Vocalizer.

**Comment by PratikP1** [comment]
@jcsteh wrote:
> Are you noticing specific responsiveness problems? OneCore seems very responsive here now, especially after #7495. It's slightly less responsive than eSpeak, but certainly more responsive than most SAPI 5 synthesizers and probably similar to Vocalizer.

My original statement should have been "If more responsiveness is needed, Microsoft will have to do it through the API." I was also noticing the difference between how Narrator performs with OneCore voices and NVDA. I suspect Microsoft is accessing the voices differently. You're right that OneCore voices definitely perform better than SAPI. There are instances when it seems like the voices are lagging. I haven't had the time to do any sort of comparison in through the logs.

**Comment by jcsteh** [comment]
I'm reasonably certain Narrator uses the same API, based on some discussion with Microsoft and a few other things. Those voices will lag if you give them extremely big chunks of text, since the API processes it all at once rather than giving you back smaller chunks of audio as it goes. However, I can also reproduce this with Narrator. Since the character reading fix, I'm honestly not seeing much difference between NVDA and Narrator. If you come up with specific examples where you're seeing differences, please do tell.

**Comment by PratikP1** [comment]
@jcsteh wrote:
> I'm reasonably certain Narrator uses the same API, based on some discussion with Microsoft and a few other things. Those voices will lag if you give them extremely big chunks of text, since the API processes it all at once rather than giving you back smaller chunks of audio as it goes.

This could help explain the lags I've seen. I'll continue to do comparison testing. The difference I noticed was in traversing through long lists like Outlook inbox. I realize that it's not fair to compare the performance of an engine like ESpeak NG.

**Comment by Adriani90** [comment]
I am closing this issue as abandoned. we do not have the requested information from the initial author and there have been several improvements regarding lags for One Core voices during last years. If you still have this issue, please open a new one and fill the template completely. Thanks.
