### ISSUE TITLE
Nvda closing Sql Developer

### ISSUE THREAD

**Issue by jeanbrazcosta** [nvaccess/nvda#7512]
1> Open Sql Developer.
2> connect ### Steps to reproduce in database.
3> make a select.
4> press control + page up or alt + page up for to go to grid.

5> press Press the directional arrows.

This point Nvda Nvda will close the application
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by ehollig** [comment]
Could you please provide a [Log File](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) with debugging enabled in the general settings of NVDA demonstrating the issue?

**Comment by jeanbrazcosta** [comment]
after the last update of NVDA the problem has been fixed.
