### ISSUE TITLE
Notepad++: command "move to next line" NVDA a little bit lag

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#7516]
### Steps to reproduce:
1. Open Notepad++.
2. Press downArrow several times.

### Expected behavior:

NVDA moves smoothly.

### Actual behavior:

NVDA reports next line message a little bit lag

### System configuration:

NVDA version: 2017.3rc1 Installed 
Windows version: windows7 64bit
Name and version of other software in use when reproducing the issue:
Notepad++ 6.7.9.2

### Other questions:

The issue does not occur after restarting PC.
The issue does not occur in NVDA2017.2.

### LOG Message

Input: kb(desktop):downArrow
DEBUG - editableText.EditableText._hasCaretMoved (15:51:00.371):
Caret move detected using bookmarks. Elapsed: 0 ms
IO - braille.BrailleBuffer.update (15:51:01.013):
Braille regions text: [u'NVDA version 2017.3rc1 ']
IO - braille.BrailleHandler.update (15:51:01.013):
Braille window dots: 13457 12367 1457 17 - 1236 15 1235 234 24 135 1345 - 23 356 2 2356 46 25 1235
IO - braille.BrailleHandler.update (15:51:01.015):
Braille window dots: 13457 12367 1457 17 - 1236 15 1235 234 24 135 1345 - 23 356 2 2356 46 25 1235
IO - speech.speak (15:51:01.246):
Speaking [LangChangeCommand (u'zh_TW'), u'NVDA version 2017.3rc1\r\n']
IO - braille.BrailleBuffer.update (15:51:01.723):
Braille regions text: [u'NVDA version 2017.3rc1 ']
IO - braille.BrailleHandler.update (15:51:01.723):
Braille window dots: 13457 12367 1457 17 - 1236 15 1235 234 24 135 1345 - 23 356 2 2356 46 25 1235
IO - braille.BrailleHandler.update (15:51:01.723):
Braille window dots: 13457 12367 1457 17 - 1236 15 1235 234 24 135 1345 - 23 356 2 2356 46 25 1235
IO - inputCore.InputManager.executeGesture (15:51:01.947):

**Comment by dkager** [comment]
> The issue does not occur after restarting PC.

Do you mean the issue does not occur after you first turn on the PC, but starts happening after some time passes? If so, do you know what will make the issue appear?

Could you test with the braille display set to "No braille" (NVDA+N, P, R, select "No braille")?

**Comment by surfer0627** [comment]
@dkager
> Could you test with the braille display set to "No braille"

Yes, this issue does not occur with the braille display set to "No braille".

> do you know what will make the issue appear?

This case offen occur while restarting NVDA. after some time passes, it works well.

**Comment by Adriani90** [comment]
@surfer0627 are you still having this problem while using the braille display? cc: @DataTriny

**Comment by Adriani90** [comment]
We don't have updates on this since years and there were many changes to Notepad++ since then. I am closing this as abandoned but feel free to comment on it if it is still an issue and we can reopen. Thanks.
