### ISSUE TITLE
Upgrade SCons to 3.0.0

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#7520]
Hi,

On August 22, 2017, SCons project announced the release of an alpha build of SCons 3 that supports Python 2.7, 3.5 and 3.6. As noted in #7105, an upgrade to SCons is all we need at this point before working on Python 3 upgrade feasibility research. Now that SCons 3 alpha is here, I think the stage is almost set to start working on Python 3 upgrade research. But before the research can commence, I suggest upgrading to SCons 3.0.0 before commencing this work, which also gives us some time to play with this version by building current NVDA source code files.

Thanks.

**Comment by leonardder** [comment]
Note that SCons 3 will also support Visual Studio 2017, necessary for #7498.

I've done first tests with Scons 3, and it seems that the gettext tools module can't be found or at least isn't compiled by SCons 3. Also, there are some changes required to make the sconstruct files compatible (e.g. print needs to be a function call).

**Comment by josephsl** [comment]
Hi,

SCons 3 is officially out, so I'm working on porting our scripts as much as I can. It'll be found in a new branch named "scons300" under my fork. Thanks.

**Comment by josephsl** [comment]
Hi,

I can confirm @LeonardDer's observation: print is now a function, which should also help us move over to Python 3 by checking for instances where print statement is used (there are several in the source code). I've disabled compiling Gettext po files because scons.Environment doesn't have gettextMoFile attribute (unless it was replaced somehow).

Thanks.

**Comment by josephsl** [comment]
Hi,

This will be part of #7568 (Windows 10 SDK+SCons 3.0.0+Visual Studio 2017 support), thus closing and no need for a separate PR. Thanks.

**Comment by leonardder** [comment]
@josephsl: Seems you intended to close this, but turns out you didn't. Closing for real this time.
