### ISSUE TITLE
Navigator object in virtual buffers doesn't seem to follow correctly

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7521]
### Steps to reproduce:
Paste the following in a chrome or firefox address bar:

```
data:text/html, just text <br /><p>A paragraph<br /><br />with text<br /><a href='/'>and a link</a></p><br /><br /><p>Another paragraph</p>
```

### Expected behavior:
When arrowing through the virtual buffer, I expect the navigator object to land as follows for every line number:

1. just text (TextLeaf object inside document object)
2. A paragraph (TextLeaf object inside paragraph object inside document object)
3. blank line (white space object inside paragraph object inside document object)
4. with text (white space object inside paragraph object inside document object)
5. and a link (link object inside paragraph object inside document object)
6. blank line (white space object inside document object)
7. blank line (white space object inside document object)
8. Another paragraph (TextLeaf object inside paragraph object inside document object)

### Actual behavior:
1. just text (document object)
2. A paragraph (paragraph object inside document object)
3. blank line (same paragraph object inside document object)
4. with text (same paragraph object inside document object)
5. and a link (link object inside same paragraph object inside document object). This seems to be the only case which works as expected
6. blank line (document object)
7. blank line (document object)
8. Another paragraph (paragraph object inside document object)

### Possible cause
It seems like if an offset is part of multiple objects, VBuf_locateControlFieldNodeAtOffset doesn't return the child id for the inner object that contains the text in the buffer. Instead, it seems to return the parent of the inner object.

**Comment by Neurrone** [comment]
That would also explain the issues I've been seeing with nvda++r not recognizing the thing I expect it to.

**Comment by leonardder** [comment]
True indeed. Thanks for bringing up this use case.
cc @MichaelDCurran

**Comment by leonardder** [comment]
@MichaelDCurran, I've investigated nvdaHelper/vbufBase/storage.cpp, and it seems that VBufStorage_buffer_t::locateControlFieldNodeAtOffset purposely returns the parent of the found node. This suggest that there might be a good reason why the actual behavior should be expected.

**Comment by leonardder** [comment]
I found out that these TextLeaf objects as wel as separators don't have a controlField, so the objects aren't part of the buffer even though their content is rendered in it. This is probably quite hard to fix in a nice way and won't have much priority due to virtual buffers becoming abandoned sooner or later.

**Comment by leonardder** [comment]
Now I understand this code a little bit better, I no longer consider this request to be of relevance any more.

**Comment by leonardder** [comment]
[**@Neurrone**](https://github.com/Neurrone) commented on [4 jul. 2018 15:23 CEST](https://github.com/nvaccess/nvda/issues/7521#issuecomment-402478229 "2018-07-04T13:23:59Z - Replied by Github Reply Comments"):
> @leonardder hm, why not? It would be very useful for the OCR feature.

Are you saying that this is currently broken?

When the browse mode caret is at a particular piece of text, the navigator object is at the paragraph that holds the text, which is perfectly valid. My assumption that the navigator object ought to be at a text leaf child object was wrong.

**Comment by Adriani90** [comment]
I suggest to reopen this issue until we find the cause why getOffsetFromPoint is not working for certain elements. See for example different elements on Github page.

**Comment by leonardder** [comment]
This issue is totally unrelated to getPointFromOffset and getOffsetFromPoint. Actually, the logic that finds the correct navigator object for a virtual buffer node is _getNVDAObjectFromOffset, and in Firefox and Chrome, is doing its work perfectly in contrast to what I thought earlier.

Note the following clarification from @jcsteh, which he gave on gitter:
