### ISSUE TITLE
Lone Wolf: Issues when Used with NVDA

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#7527]
Lone Wolf is an older title developed by GMA Games that I started to play again recently. During gameplay, since text is written to the screen there are several issues when playing with NVDA; primarily that text is output twice, and the word "Selected" prepended to anything spoken. If I could clearly outline the problems here, is there anybody that would consider making changes to make this game playable, which could then be included with NVDA's main instalation package?

**Comment by leonardder** [comment]
Since Lone Wolf is a quite old title, it is very unlikely that this will be handled by NV Access. Assigning priority 4.

**Comment by Adriani90** [comment]
In Lone wolf 3.5 everything works correctly with NVDA last alpha. Closing as works for me.
Please comment on it if you are still having this issue and we can reopen. Thanks.
