### ISSUE TITLE
NVDA_17.3: NVDAObjects. Potential unimplemented child class in Windows7

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#7532]
### Steps to reproduce:
1. Press win+m to minimize all windows.
2. Press downArrow several times.

### Expected behavior:

NVDA moves smoothly.

### Actual behavior:

NVDA reports list items a little bit lag

### System configuration:

NVDA version: 2017.3 Installed 
Windows version: windows7 64bit (6.1.7601 service pack 1)

### Other questions:

In the same case, NVDA 17.3 portable will crash while pressing Win+m to minimize all windows.
The issue does not occur in NVDA2017.2.

### LOG Message:

Input: kb(desktop):downArrow
DEBUG - NVDAObjects.NVDAObject._get_placeholder (09:58:09.059):
Potential unimplemented child class: <NVDAObjects.IAccessible.sysListView32.ListItem object at 0x0646A6D0>
IO - braille.BrailleBuffer.update (09:58:09.170):
Braille regions text: [u'c\u96fb\u8166 32 of 32']
IO - braille.BrailleHandler.update (09:58:09.170):
Braille window dots: 14 145 2345 5 1345 146 4 - 25 23 - 135 124 - 25 23

**Comment by josephsl** [comment]
Hi, uh oh, @feerrenrut, any ideas, or is this even serious enough? Re #7004

**Comment by leonardder** [comment]
@surfer0627: Can you reproduce this issue with braille disabled?

**Comment by surfer0627** [comment]
When braille disabled, NVDA still reports list items a little bit lag. The difference is that log message "Potential unimplemented child class" is disappeared.

@leonardder

**Comment by ruifontes** [comment]
Hi!

It only happens with a Braille display in use...

Rui


-----Mensagem Original----- 
De: Leonard de Ruijter
Data: 28 de agosto de 2017 05:08
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] NVDA_17.3: NVDAObjects. Potential unimplemented 
child class in Windows7 (#7532)



@surfer0627: Can you reproduce this issue with braille disabled?

**Comment by leonardder** [comment]
[**@ruifontes**](https://github.com/ruifontes) commented on [28 aug. 2017 12:30 CEST](https://github.com/nvaccess/nvda/issues/7532#issuecomment-325318888 "2017-08-28T10:30:44Z - Replied by Github Reply Comments"):
> It only happens with a Braille display in use...

Could you elaborate?

**Comment by ruifontes** [comment]
Hi!

If you are using a Braille display, in my case a Handytech BB20 or a Orbit 
Reader 20, the error occurs.
If you choose "No display", the error does not occurs.


-----Mensagem Original----- 
De: Leonard de Ruijter
Data: 28 de agosto de 2017 11:35
Para: nvaccess/nvda
Cc: ruifontes ; Comment
Assunto: Re: [nvaccess/nvda] NVDA_17.3: NVDAObjects. Potential unimplemented 
child class in Windows7 (#7532)



@ruifontes commented on 28 aug. 2017 12:30 CEST:



It only happens with a Braille display in use...



Could you elaborate?

**Comment by feerrenrut** [comment]
The "Potential unimplemented child class" message can safely be ignored.  In terms of the lag, @surfer0627 could you please attach the full log. I would like to compare the timestamps on the log messages to try to understand what user action triggers it.

**Comment by surfer0627** [comment]
@feerrenrut: Please check the attached log file. Thanks.

[nvda_17.3_installed.log.txt](https://github.com/nvaccess/nvda/files/1262245/nvda_17.3_installed.log.txt)

**Comment by feerrenrut** [comment]
According to the log, it seems like there is a delay of around 400ms. I don't seem to be able to reproduce this myself using he brailleViewer driver on Windows 10 and NVDA `master-14328,c6379eb3`. @surfer0627 Could you attach a log file after doing the same thing, with braille disabled?

**Comment by surfer0627** [comment]
@feerrenrut:

I don't know why? but, the truth is that I could not reproduce this case in braille display enabled / disabled.

**Comment by feerrenrut** [comment]
@surfer0627 Are you able to reproduce the issue? If not I will close it.
