### ISSUE TITLE
Next Snapshots won't install on Windows XP any more

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#7544]
Simply run a Next snapshot on an XP machine. an error will occur when the  agree screen comes up. The error is a call to an entry point to a routine by the helper in a dll, which does apparently not exist on Windows XP.
Just in case nobody has noticed. I thought I'd best mention it. It does not 
fail in a particularly friendly way either. IE
nvda_slave.exe - Entry Point Not Found

The procedure entry point CoGetApartmentType could not be located in the 
dynamic link library ole32.dll.

 There at least three snaps with this rather terminal issue. If you  just 
bypass you end up with a non working installed copy.

The last working version is:
NonVisual Desktop Access (NVDA)
Version: next-14363,0092e3d0
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by leonardder** [comment]
Most likely caused by #7535. cc @michaeldcurran

**Comment by michaelDCurran** [comment]
CoGetApartmentType is not available until Windows 7. For now I have 
worked around this.

However, after testing on XP some more, although NVDA is again able to 
"run", IAccessible2 is not available (I.e. no access to Firefox), due to 
manifest issues.

We will very carefully way up possible options here...

**Comment by Brian1Gaff** [comment]
I cannot say I've actually noticed the issue in Firefox.
 Well not on XP anyway. The best plan maybe is to mask it out for xp as one does with uia maybe. I think somebody needs to start asking about a final version of  nvda for xp, say two versions from now so publicity can be seen by those affected.
 I don't mind that much, it just means my old clunkers that are mostly used for back ups will stay as they will be at that point. the thing is that some nice friendly way to  let the uninitiated know that a version will not run should be  thought about before then.
 With the migration to a later version of Python then I'd imagine you will get to this point at some future date.
 
In the meantime I'll go on testing on xp.
Incidentally the error seems to be after the ini file is read, so maybe it is possible to detect it then and still allow you to use the extended function calls.

Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
This message sent from a Windows XP machine!

**Comment by Adriani90** [comment]
@michaelDCurran any update on this? I guess it has an impact on NVDA 2017.3 but I don't think you will digg into this again since the support for XP and Vista is dropped since almost one year. Should this be closed?

**Comment by leonardder** [comment]
[**@Adriani90**](https://github.com/Adriani90) commented on [28 Jul 2018, 09:40 CEST](https://github.com/nvaccess/nvda/issues/7544#issuecomment-408589775 "2018-07-28T07:40:36Z - Replied by Github Reply Comments"):
> Should this be closed?

I guess so yes, thanks for catching this one.
