### ISSUE TITLE
Say all doesn't work on newly opened file in LibreOffice / Libre Office (5.3.4.2 at least) and Open Office (4.1.4)

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#7545]
When opening a document in LibreOffice, the focus starts on the first line.  If Say all (NVDA+down arrow) is pressed, only that first line is read.  Text can be typed and navigated as normal.  In testing, I found that sometimes typing a character, or moving the caret made it possible to then do a say all and have it read correctly, but not always.  I also tried pressing alt twice to move focus away and then back, which had no effect on a subsequent say all command.

The most reliable way I found to work around the problem was to press control+end to move to the very end of the file, then control+home to the start and then say all seems to work each time I've tried it.

There are a number of errors generated internally (only visible on the NVDA log) by NVDA when the file is opening.  I have pasted the log here from the time I pressed ENTER on a file (in LibreOffice's File Open dialog) to open it, through when I pressed NVDA+down arrow, to when that command finished (the next line after this was retrieving the log.

[libreOfficeSayAll.txt](https://github.com/nvaccess/nvda/files/1265573/libreOfficeSayAll.txt)

**Comment by Qchristensen** [comment]
I suspect the OS version doesn't have too much impact on this, but FWIW, I tested on Windows 10 (fast insider build 16278) and the user who reported it to me is using Windows 7 SP1, both running NVDA 2017.3.

**Comment by zahra21** [comment]
hi quentin.

thanks extremely for your guide.

does it realy work to press control end and control home to come to beginning of text with say all?

i realy need sayAll, but did not find a solution in both openoffice and libreoffice except preview in web browser in libreoffice and openoffice file menu!

could you please test with windows xp and different versions of nvda?

thanks extremely for your help, i sincerely pray for you every day and request divine infinite mercy for you.

**Comment by Qchristensen** [comment]
Hi Zahra,

Since you are running XP, perhaps you could better tell me if using say all works for you after pressing control+end then control+home after opening a document in LibreOffice.

Actually, I had only tested this and explored this bug in LibreOffice, but I just had a quick look in Apache Open Office 4.1.4 and you are right, Say all didn't seem to work immediately upon opening a document, but pressing control+end then control+home did seem to fix it.  I'll update the issue title to include Open Office.

**Comment by zahra21** [comment]
hi quentin.
thanks so much for your support as always.

i tested with my favorite version of nvda (2017.1) using libreoffice 5.3.6, 5.3.4, 5.3.5 and previous ones!
nvda reads five lines or little more, (i think one paragraph) because the numbers of lines which nvda reads are different in files and content.
i think that it depends on how many lines are in one paragraph, causes different lines reading for me.

unfortunately libreoffice has not complete support for sayAll at least for me until now.

but reading one paragraph or many lines, is very better than reading only one line!

also, someone told me that i should delete empty lines in my documents for this reason that nvda can reads documents entirely.
thanks so much for your solution.

which program should support sayAll?

is it depend on nvda to support sayAll in libreoffice?

or do libreoffice developers should find solution for supporting sayAll for screen readers?

**Comment by Qchristensen** [comment]
Reading through [LibreOffice bug 91739](https://bugs.documentfoundation.org/show_bug.cgi?id=91739), I realised this issue is a duplicate of #4119.  I'll close this as a duplicate of that issue.

**Comment by zahra21** [comment]
hi.
91739 and 4119 are the same issue.
but 91739 is the bug which i reported in bugs.libreoffice.org
and this one you reported in github.
i realy need sayAll, cant update the version of my libreoffice, nvda for my promise and wish that you provide me one efficient solution for reading my entire documents just by using sayAll.

i think that you forgot to answer my question.
who should support sayAll and provide the solution for us to use it?
nvda or libreoffice engineer?

**Comment by Brian1Gaff** [comment]
I doubt that anyone is going to do a work around that might work in xp with 
older version of nvda.
 However i understood the problem with reading a whole document was an issue 
with the libra and open code not presenting the screenreader with the 
correct data to know it can jump over gaps.
 Brian

**Comment by zahra21** [comment]
quentin,
i dont think that the bug91739 and 4119 cant be duplicate, because there places are different!
91739 is the bug that i reported in bugzilla for libreoffice developers and 4119 you reported hear.
i dont think that they are duplicate and should not be closed.
