### ISSUE TITLE
Speech Viewer deviates from normal Alt+Tab order

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#7548]
# STR #
1. Ensure you have multiple random windows open.
2. Open NVDA menu>Tools submenu>Speech Viewer.
3. Press and release Alt+Tab and note the window you have moved to.
4. Press Alt+Tab again.
Expected Result: Focus should land back on to the Speech Viewer window according to normal Alt+Tab order.
Actual Result: Speech Viewer seems to move to the end of the Alt+Tab order and focus lands on it only before the subsequent Alt+Tab would land focus on the noted window from where we started Alt+Tabbing.
# Log Snippet 
The below pasted log snippet appears more or less similarly throughout the Alt+Tab key press from the noted window till Speech Viewer:
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (12:28:41.141):
oleacc.AccessibleObjectFromEvent with window 6817558, objectID 7095 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (12:28:41.141):
oleacc.AccessibleObjectFromEvent with window 6817558, objectID 7096 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (12:28:41.141):
oleacc.AccessibleObjectFromEvent with window 6817558, objectID 7097 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (12:28:41.141):
oleacc.AccessibleObjectFromEvent with window 6817558, objectID 7098 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (12:28:41.141):
oleacc.AccessibleObjectFromEvent with window 6817558, objectID 7099 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (12:28:41.141):
oleacc.AccessibleObjectFromEvent with window 6817558, objectID 7100 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (12:28:41.141):
oleacc.AccessibleObjectFromEvent with window 6817558, objectID 7101 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (12:28:41.157):
oleacc.AccessibleObjectFromEvent with window 6817558, objectID 7102 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (12:28:41.157):
oleacc.AccessibleObjectFromEvent with window 6817558, objectID 7103 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (12:28:41.157):
oleacc.AccessibleObjectFromEvent with window 6817558, objectID 7104 and childID 0: [Error -2147467259] Unspecified error
# Implications & Use Case #
At first glance, this issue may seem particularly trivial. However, this bug affects me significantly in some ways. To work-around #6273, I desired to Alt+Tab from the Speech Viewer window to the Microsoft Word document (e.g. academic material and school textbooks), navigate to the graphic with alternative text, and then immediately Alt+Tab back to Speech Viewer so as to structurally review the same text, i.e. read the large paragraph of alternative text using standard navigation commands in order to digest the information in smaller pieces. This work-around becomes quite inefficient since by the time I am back in the Speech Viewer, there are many extraneous lines of speech I must navigate through before I can comprehensively review the Word document’s graphic’s alternative text. This may sound like an edge case at first, but any intermediate NVDA user may want to employ such a work-around to cohesively review any text (whether associated to a graphic in Word or elsewhere) which cannot itself be accessed via review any means – neither review modes nor object navigation or anything else. Apart from this line of use cases, using the Speech Viewer becomes quite inconvenient for a screen reader user, regardless of whatever purpose he/she is using this tool for, because before the Speech Viewer window is arrived at, there are many intermediary windows that NVDA will provide speech feedback for in the Alt+Tab order, leading to generation of unnecessarily many lines of speech in the Speech Viewer.
# Test Environment #
NVDA 2017.3
Windows 8.1 64 bit

**Comment by leonardder** [comment]
Honestly, in my opinion the speech viewer is not meant to be used as such. It is perfectly suitable for sighted people to review speech output on screen, and I belief it is an always on top window, meaning that the speech viewer will still be visible when you are inside your word document. For reviewing text in place, there is the review cursor.

cc @feerrenrut

**Comment by leonardder** [comment]
Ugh, I should have read your description more thoroughly. Still, I guess #6273 would be much more important to fix.

**Comment by bhavyashah** [comment]
I cannot reproduce this issue with NVDA 2023.2 on Windows 11. Closing this ticket.
