### ISSUE TITLE
OCR add-on: scan fails and an error is generated instead for certain controls

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#7551]
# STR #
Please note that all keyboard shortcuts stated hereinafter will be based on the laptop keyboard layout and shall need to be converted for the desktop equivalent manually.
1. Ensure that simple review mode is disabled. (just in case that matters)
2. Open NVDA’s Voice Settings dialog (NVDA+Ctrl+V).
3. Press NVDA+Shift+up arrow (object navigation) once to move to ‘Voice: window Alt+V’.
4. Press NVDA+Shift+right arrow until you land on what NVDA reports ‘window’ (third to last in this object hierarchy level).
5. Press NVDA+Shift+down arrow to move to ‘graphic’.
6. Press NVDA+R to issue a scan.
Expected Result: NVDA says ‘Running OCR’ and performs it.
Actual Result: There is no effect.
# Log Snippet #
The above STR not only reproduces the described issue consistently but also produces the following log:
ERROR - scriptHandler.executeScript (23:46:21.937):
error executing script: <bound method GlobalPlugin.script_ocrNavigatorObject of <globalPlugins.ocr.GlobalPlugin object at 0x046B7370>> with gesture u'NVDA+r'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "C:\Users\DELL-PC\AppData\Roaming\nvda\addons\ocr\globalPlugins\ocr\__init__.py", line 180, in script_ocrNavigatorObject
  File "C:\Users\DELL-PC\AppData\Roaming\nvda\addons\ocr\globalPlugins\ocr\PIL\Image.py", line 1439, in save
  File "C:\Users\DELL-PC\AppData\Roaming\nvda\addons\ocr\globalPlugins\ocr\PIL\BmpImagePlugin.py", line 242, in _save
  File "C:\Users\DELL-PC\AppData\Roaming\nvda\addons\ocr\globalPlugins\ocr\PIL\ImageFile.py", line 498, in _save
SystemError: tile cannot extend outside image
# Test Environment #
* NVDA version 2017.3
* Windows 8.1 64 bit
# Notes #
* Contrary to my initial belief, testing reveals that this issue exists not only for an edge case like the graphic in question but also in a Microsoft Word document, and probably a host of other controls as well.
* Pressing NVDA+R has absolutely no effect in such cases from a usage/performance standpoint – NVDA stays silent, there is no freeze, etc.

**Comment by Adriani90** [comment]
@bhavyashah please create an issue agains the ocr addon itself which has also a repository on Github. I am closing this one for now.
