### ISSUE TITLE
In Microsoft Edge some items in a list are read in a single line

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7555]
I rarely use hedge as a browser, I do not know if what I'm going to talk about is a characteristic or problem
### Steps to reproduce:
the hedge and open the nv acces website
www.nvda-project.org
press l to go to the first list of 9 items
### Expected behavior:
When pressing l, the nvda should read the first item in the list
Home
When walking with the arrows below you should read the other items each one in a row:
About
Download 
So on

### Actual behavior:
Note that nvda will read the items:
Home About Download Get Help Services Support Us Shop
All on the same line.
Pressing the down arrow will read the last item in the list
Donate

### System configuration:
NVDA version:
next 14373
NVDA Installed or portable:
instaled
Windows version:
windows 10 15063.540 64bits
Name and version of other software in use when reproducing the issue:
microsoft hedge
### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
no

**Comment by josephsl** [comment]
Hi,

Before we continue: it is Microsoft Edge.

Is this the case with other browsers such as Firefox and IE? If not, then it might be unique to how Edge renders the list.

Thanks.

**Comment by ehollig** [comment]
I initially thought that this could be an issue with Simple review mode checkbox was checked in Edge.
If the checkbox is not checked, the links appear on their own lines using Firefox. If the checkbox is checked, all links specified in the original post are rendered on the same line.
It does not appear to make a difference whether this checkbox is checked or not in Edge and browsing the NVAccess website. The list of links appear on the same line either way. Furthermore, the shortcut to change review modes, NVDA+V, appears not to work.
I am not sure whether this is related, or a new issue altogether.

**Comment by fernando-jose-silva** [comment]
No, the problem is only in microsoft hedge.

 

De: Joseph Lee [mailto:notifications@github.com] 
Enviada em: sexta-feira, 1 de setembro de 2017 14:27
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>; Author <author@noreply.github.com>
Assunto: Re: [nvaccess/nvda] In Microsoft Edge some items in a list are read in a single line (#7555)

 

Hi,

Before we continue: it is Microsoft Edge.

Is this the case with other browsers such as Firefox and IE? If not, then it might be unique to how Edge renders the list.

Thanks.

**Comment by leonardder** [comment]
[**@ehollig**](https://github.com/ehollig) commented on [2 sep. 2017 00:00 CEST](https://github.com/nvaccess/nvda/issues/7555#issuecomment-326692847 "2017-09-01T22:00:50Z - Replied by Github Reply Comments"):
> I initially thought that this could be an issue with Simple review mode checkbox was checked in Edge.

Do you by any chance mean "use screen layout" instead of "simple review mode"?

**Comment by ehollig** [comment]
@leonardder, yes that is what I meant

**Comment by Adriani90** [comment]
This works as expected in Edge Chromium 81. Closing as works for me since Edge Chromium will be distributed to most users via Windows 10 20 H1 update.
