### ISSUE TITLE
problme to read a combobox in webpages

### ISSUE THREAD

**Issue by alexandretoco** [nvaccess/nvda#7564]
### Steps to reproduce:
1. open schrome (but this also happens to edge).
2. go to www.ambutech.com and go to shop online
3. simulate to buy a cane for example. a form with various comboboxes will be shown.
4. when I press the arrows to navigate between the combobox's itens, nvda reads the page title, some links , the combobox's title and the new focused item.
It is very anoying!
### Expected behavior:
read only the new focused item

### Actual behavior:
nvda is reading unecessary elements and it makes the iteraction slow and confusing.

### System configuration:
NVDA version: 2017.3

Windows version:
windows 10 creator 64 bits

### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
no

**Comment by ehollig** [comment]
I think this may be because the page is refreshing to show new data and NVDA may think the entire page is refreshing, causing it to announce the page title. CC @leonardder @feerrenrut

**Comment by Adriani90** [comment]
@alexandretoco are you still having this problem? I cannot reproduce it with NVDA 2019.1.1 and Chrome 74.

**Comment by alexandretoco** [comment]
Hi, I think the problem is gone!
I tried it again and now, the combobox's contents are being read ok.
