### ISSUE TITLE
Problems with WAI-ARIA attributes

### ISSUE THREAD

**Issue by jmortizsilva** [nvaccess/nvda#7570]
Hi,

I'm trying to insert a header into a web page that is only visible to screen readers and I don't want to use CSS techniques to hide the content. I'm trying to use role="heading", aria-level and aria-label, but NVDA doesn't recognize the code I want to use in Firefox.

The code I'm using is:

```<div role="heading" aria-level="1"><span aria-label="headline text"></span></div>```

Jaws verifies this code in both Internet Explorer and Mozilla Firefox and NVDA only verifies it in Internet Explorer.

**Comment by Brian1Gaff** [comment]
Of course you really need to also consider what happens particularly in Edge 
and Chrome. I've seen some strange things appear in different browsers on 
some web sites for no obvious reason.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by jmortizsilva** [comment]
Hi, in Chrome works well. I can't try in Edge.

**Comment by ehollig** [comment]
This appears to work correctly in Internet Explorer, Chrome, and Edge. Expected results are not observed in Firefox.

**Comment by jcsteh** [comment]
This is due to [Mozilla bug 1418102](https://bugzilla.mozilla.org/show_bug.cgi?id=1418102), fixed for Firefox 59. I've tested the above test case and I can confirm it works in 59.
