### ISSUE TITLE
Curious Announcement When Showing History Panel in Firefox

### ISSUE THREAD

**Issue by Mohamed00** [nvaccess/nvda#7572]
I've noticed a curious announcement when viewing history using control+h in Firefox.
### Steps to reproduce.
1. Show history using control+h in Firefox.
### Expected.
NVDA should say "search history edit has autocomplete".
### Actual.
NVDA says that, along with the phrase "chrome://browser/content/history/history-panel.xul  grouping".
### System configuration.
NVDA version: next-14387,0531065f.
Windows version: Windows 10 Insider build 16281.1000.
Name of other software in use when producing the issue.
Firefox 55.0.3 (64 bit).

**Comment by bhavyashah** [comment]
Confirmed.

On 9/6/17, Mohamed Al-Hajamy <notifications@github.com> wrote:
> I've noticed a curious announcement when viewing history using control+h in
> Firefox.
> ### Steps to reproduce.
> 1. Show history using control+h.
> ### Expected.
> NVDA should say "search history edit has autocomplete".
> ### Actual.
> NVDA says that, along with the phrase
> "chrome://browser/content/history/history-panel.xul  grouping".
> ### System configuration.
> NVDA version: next-14387,0531065f.
> Windows version: Windows 10 Insider build 16281.1000.
> Name of other software in use when producing the issue.
> Firefox 55.0.3 (64 bit).
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/7572


-- 
Best Regards
Bhavya Shah

Blogger at Hiking Across Horizons: https://bhavyashah125.wordpress.com/

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by lukaszgo1** [comment]
This problem is still present in Nightly 62.0a1 (2018-06-24). It is also reproducible with JAWS, so i suppose that it is a firefox bug. cc @jcsteh

**Comment by Mohamed00** [comment]
Yeah, likely an oddly named grouping, I think this is a Firefox bug. Would probably do to file a bug on Bugzilla.

**Comment by jcsteh** [comment]
Filed [Mozilla bug 1470779](https://bugzilla.mozilla.org/show_bug.cgi?id=1470779).

**Comment by Mohamed00** [comment]
This issue is fixed in the latest Firefox Nightly builds. Since it is, I'll close this now.
