### ISSUE TITLE
Outlook 2010 crash on today page

### ISSUE THREAD

**Issue by daniel-1964** [nvaccess/nvda#7576]
### Steps to reproduce:
Open outlook and go to today page.
This occur with an exchange enterprise email account or with an hotmail email account.

### Expected behavior:
Normally the today page should present the number of unread mail and the number of draft emails, the next appointments, the tasks, ...

### Actual behavior:
Outlok crash, blocking nvda. When I restart nvda with alt-n, I have the dialogbox: "close outlook" or "restart outlook"

The debug-mode nvda log content the following:
DEBUGWARNING - RPC process 2096 (DWWIN.EXE) (18:37:41.178):
Thread 3756, build\x86_64\remote\ia2Support.cpp, installIA2Support, 86:
Error registering class object, code -2147221008

I think that it is the cause

I provide tow logs: 
* win7_nvda.log for windows 7 enterprise and an enterprise email acount
* win10_nvda.log for win10 home and an hotmail email account

### System configuration:
NVDA version:
Nvda-2017.3 or nvda-2017.2

NVDA Installed or portable:

Any version

Other information:
Was ok for nvda-2017.1 and before

Windows version:
Windows 10 Version 1703 Home edition
Windows 7 Enterprise edition 

Name and version of other software in use when reproducing the issue:
Outlook 2010 professional

### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA? Ok for nvda-2017.1 and before

[nvda-log.zip](https://github.com/nvaccess/nvda/files/1282125/nvda-log.zip)

**Comment by ehollig** [comment]
Is this possibly related to #7556

**Comment by daniel-1964** [comment]
I have just tested with the lastest nvda-2017.4 and it seems that outlook 2010 today page rework correctly on windows 7.
