### ISSUE TITLE
EVENT_SYSTEM_ALERT can not be read

### ISSUE THREAD

**Issue by israel-Liu** [nvaccess/nvda#7582]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.zoom.us 
> 3. Download zoom application, Open up the Zoom application
> 4.  When NVDA/Narrator is on
> 5. Create a meeting with 1+ participants so that you are the host
> 6. Have another user raise their hand. There is a visual alert that reads "[name] raised hand". NVDA should read this alert but does not. Narrator can read

Other information:
> Not think window must get focus

**Comment by Adriani90** [comment]
@israel-Liu this should work now in NVDA. Could you please test with NVDA 2019.1.1? Is this issue still occuring? I was testing zoom some weeks ago and could not reproduce this issue.

**Comment by Adriani90** [comment]
We do not have any updates from the initial author since mroe than two years. Closing as abandoned and works for me.
