### ISSUE TITLE
UnicodeDecodeError when NVDA running on non-English outdated systems

### ISSUE THREAD

**Issue by kvark128** [nvaccess/nvda#7586]
When runing the latest NVDA snapshots on Russian versions of outdated Windows (XP/Vista), in the log I have the following exception:
Traceback (most recent call last):
File "nvda.pyw", line 64, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 0: ordinal not in range(128)

Probably, need to explicitly specify the system encoding, since in Russian Windows it is cp1251.
For example, like so:
import winVersion
import locale
if not winVersion.isSupportedOS():
	winUser.MessageBox(0, unicode(ctypes.FormatError(winUser.ERROR_OLD_WIN_VERSION), locale.getpreferredencoding()), None, winUser.MB_ICONERROR)
	sys.exit(1)
Now the dialogue will be shown correctly.

**Comment by josephsl** [comment]
CC @MichaelDCurran

**Comment by Adriani90** [comment]
This issue seems to occur on Windows XP or Vista with snapshots of NVDA. NVDA 2017.3 was released before September 2017 I guess. So support after that has been dropped. I vote for closing this issue.

**Comment by leonardder** [comment]
Fixed in #8771
