### ISSUE TITLE
Braille error when using Cortana

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#7588]
### Steps to reproduce:
1. Press Windows+c.
2. Say "How many kilos is 10 pounds?"

### Expected behavior:
The results, with no errors, and also shown in braille.

### Actual behavior:
The followiong error:

```
ERROR - eventHandler.executeEvent (19:30:55.927):
error executing event: gainFocus on <NVDAObjects.UIA.edge.EdgeNode object at 0x04F91970> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 138, in executeEvent
  File "eventHandler.pyc", line 171, in doPreGainFocus
  File "browseMode.pyc", line 1163, in event_treeInterceptor_gainFocus
  File "braille.pyc", line 1646, in handleGainFocus
  File "braille.pyc", line 1651, in _doNewObject
  File "braille.pyc", line 1411, in getFocusRegions
  File "braille.pyc", line 911, in update
  File "braille.pyc", line 829, in _addTextWithFields
IndexError: pop from empty list
```

### System configuration:
NVDA version: master-14412,43350e89

NVDA Installed or portable: Installed

Windows version: Windows 10.0.15063

### Other questions:
Not yet sure what information is missing in braille, if any.
CC @leonardder

**Comment by dkager** [comment]
> 2. Say something smart.

Turns out this is even more restricted: some kind of data form has to show up. Tested and confirmed with "How many kilos is 10 pounds?"

**Comment by josephsl** [comment]
Hi, also CC @DerekRiemer in case he has additional comments on this, and I’ll do some testing to see what’s up. Thanks,

**Comment by derekriemer** [comment]
I'll try to get to this one

**Comment by Adriani90** [comment]
@dkager unfortunately I don't have a braille display at hand to test this. Is it still an issue in NVDA 2019.1.1?

**Comment by Adriani90** [comment]
@ruifontes couls you please test if this issue is still reproducible? Thanks!

**Comment by ruifontes** [comment]
And I can't use Cortana in portuguese, so I can't test...

**Comment by dkager** [comment]
Works for me!
