### ISSUE TITLE
Dropdown role=alert aria-live= assertive reading it several times

### ISSUE THREAD

**Issue by valentinaAl** [nvaccess/nvda#7596]
### Steps to reproduce:
> I set a dropdown with a role=alert, and Aria-live=assertive

> 1. Open Firefox
> 2. nvda reads ok the app overview
> 3. Change the dropdown
> 4. reads like a loop the text it's given to it

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> In other browser the behaviour is as expected, even in firefox the behavior with JAWS works ok

### Actual behavior:
> When it comes to nvda it loops when it should read the alert just once, it doesn't even read it in equal amounts it just varies with no pattern, it only happends with NVDA+Firefox

### System configuration:
NVDA version:
> 2017.2

NVDA Installed or portable:

Other information:
> I run this in a lolac app, but is the first time I have this issue

Windows version:
> Example: Windows 10 Home Version 1607 Build 14393.1593
 
Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
 Yes
Have you tried any other versions of NVDA?
> NO

**Comment by feerrenrut** [comment]
Sorry @valentinaAl, I'm really not sure I understand this issue. Could you please provide a sample that demonstrates the problem. And expand the steps to reproduce to outline the commands that you give to NVDA to demonstrate the behaviour. Thanks.

**Comment by Adriani90** [comment]
@valentinaAl I could not reproduce such an issue yet. Could you please upload an example so we can repoduce this issue? Thanks!

**Comment by Adriani90** [comment]
A minimal test case is missing and we didn't get any updates from the initial author. I am closing this as abandoned since it is hard to investigate without a minimal test case.

Please comment on this with a minimal test case and we can reopen.
