### ISSUE TITLE
[Bug Report] Reading word by word in Korean language issue

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#7597]
Hello, I'm Hyongsop Kim in Korea and NVDA user.
I want to report a critical bug about reading word by word in Korean language.
In web browser or word processor, we can use system caret to move by line, word or character.
By the way, if first line's first character is punctuation, such as quotation, and Korean sentence is there, even if I press CTRL plus right arrow key to move word by word, NVDA read just one character of each word.
Below is reproduce method.
1. Open notepad.
2. Change keyboard language set to Korean.
3. Press the next right key of the space in order to change to Korean character. NVDA will say Native input.
4. You can type "dkssudgktpdy, akssktj qksrkqtmqslek."
5. Press home key to read word by word from top to bottom.
6. Press CTRL plus right arrow key to move word by word.
You can hear that NVDA read just first character of each word.

Please fix this issue.
thank you.

**Comment by dnz3d4c** [comment]
I think it is the same as # 7448 issue.

**Comment by ehollig** [comment]
CC @khsbory @josephsl, is this the same issue as #7448?

**Comment by khsbory** [comment]
Hello, sorry about my too late reply about this issue.
Yes, as you said, this issue is the same issue that you provided link.
I couldn't check this is the same issue.
 
Thank you. 
 
김 형 섭	 / Hyongsop Kim
(주)엔비전스 / 웹접근성사업팀 팀장	

서울시 종로구 가회동 1-29 
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 70 4900 0895   F. +82 2 313 3645   M. +82 10 5359 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark

 
-----Original Message-----

**Comment by dnz3d4c** [comment]
@khsbory We ask you to close this issue because it is a duplicate issue.
Thanks!
