### ISSUE TITLE
Script to rapidly determine path in terminal

### ISSUE THREAD

**Issue by ctoth** [nvaccess/nvda#7602]
### Steps to reproduce:

- Open the command prompt
- Navigate into a path multiple directories deep
- Quickly determine exactly where you are

### Expected behavior:

I should be able to tell at a glance, or by using a keystroke, or ... exactly where I am without having the entire path read out to me every time.
When working with sighted developer colleagues, they can glance directly at the last segment of the path and see oh, I'm in the whatever folder whereas I have to read out the entire path to see where I am.

For instance I am currently working on an Angular app on a work laptop. My command prompt looks like:
```
C:\Users\p2730476\src\consolidation\spectrum\src\app\equipment\equipment-overview\equipment-footer-banner>
```

It would be awesome if I could review segments of the path with keystrokes, for instance in reverse numerical order, with NVDA+shift+{1, 2, 3, ...} reading progressively previous path segments, with NVDA+shift+1 reading the last one.
Or really, I don't care how we solve this, I'm just trying to bring the issue up for discussion and see if we can figure out a fix.

**Comment by daiverd** [comment]
Also, ensure that this works for Unix style paths separated by '/' characters.

**Comment by bramd** [comment]
I see why you would want such a feature. However, with the default settings of the review cursor following the caret and the object nav following the focus, you can use current word (numpad 5) and previous word (numpad 4) to review the last parts of your prompt. That's not path segments, but comes close.

**Comment by Adriani90** [comment]
@ctoth did the suggestion made by Bramd in his comment above help you in working more efficient now? or do you still need a separate script for this?

**Comment by Adriani90** [comment]
Since we didn't hear any contrary statement from the initial author, we can assume the solution proposed above works as expected. Also with laptop keyboard layout you can use nvda+down arrow key to hear the path, and nvda+right and left arrow to review it.
I am closing as works for me.
