### ISSUE TITLE
Document formatting preferences don't always apply to braille in browse mode

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#7615]
### Steps to reproduce:
1. Select a braille table that can report italic text.
2. From Preferences --> Document formatting, uncheck Font attributes.
3. Read the following line (tested with Firefox 55).

This is _italic_ text.

### Expected behavior:
The italic text is not marked as italic.

### Actual behavior:
Speech does indeed not mention the italic attribute, but braille still shows it.

### Other information
Can't reproduce in Word, so it seems specific to browse mode.

First reported by @rimas-kudelis in https://github.com/nvaccess/nvda/issues/1885#issuecomment-328823096. The key take-away point is that this problem is quite annoying for users on the web, and if unresolved may lead to people "fixing" braille tables to exclude bold/italic/etc altogether.

**Comment by bramd** [comment]
@dkager For completeness and to be able to reproduce, which table would support such attributes?

**Comment by dkager** [comment]
The Dutch tables, and proabbly UEB.

**Comment by dkager** [comment]
This can be fixed with a simple patch of braille.py to consider formatConfig before sending text formatting flags to liblouis.

A further optimization is to not fetch IA2 [text attributes](https://wiki.linuxfoundation.org/accessibility/iaccessible2/textattributes) and [object attributes](https://wiki.linuxfoundation.org/accessibility/iaccessible2/objectattributes) if all the formatConfig options that rely on them are disabled. This saves a few COM calls but the gains are probably minimal.
