### ISSUE TITLE
Updating portable  next snaps not working today

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#7616]
When I try to update a next snap today 20th sept 2017, the following happens.

IO - speech.speak (12:54:18.430):
Speaking [LangChangeCommand ('en_GB'), u'Select Folder  button']
IO - inputCore.InputManager.executeGesture (12:54:19.163):
Input: kb(desktop):space
IO - speech._speakSpellingGen (12:54:19.184):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (12:54:19.186):
Adding generator 6
IO - speech.speak (12:54:19.186):
Speaking [LangChangeCommand ('en_GB'), u'pressed']
DEBUG - queueHandler.pumpAll (12:54:19.191):
generator 6 finished
IO - speech.speak (12:54:19.381):
Speaking [LangChangeCommand ('en_GB'), u'Create Portable NVDA  dialog  To create a portable copy of NVDA, please select the path and other options and then press Continue']
IO - speech.speak (12:54:19.394):
Speaking [LangChangeCommand ('en_GB'), u'Portable directory:  grouping']
IO - speech.speak (12:54:19.405):
Speaking [LangChangeCommand ('en_GB'), u'Browse...  button']
IO - inputCore.InputManager.executeGesture (12:54:20.819):
Input: kb(desktop):tab
IO - speech.speak (12:54:20.864):
Speaking [LangChangeCommand ('en_GB'), u'Start the new portable copy after creation  check box  not checked  Alt+s']
IO - inputCore.InputManager.executeGesture (12:54:23.627):
Input: kb(desktop):tab
IO - speech.speak (12:54:23.673):
Speaking [LangChangeCommand ('en_GB'), u'Continue  button  Alt+c']
IO - inputCore.InputManager.executeGesture (12:54:25.019):
Input: kb(desktop):space
IO - speech._speakSpellingGen (12:54:25.028):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (12:54:25.028):
Adding generator 7
IO - speech.speak (12:54:25.028):
Speaking [LangChangeCommand ('en_GB'), u'pressed']
DEBUG - queueHandler.pumpAll (12:54:25.045):
generator 7 finished
IO - speech.speak (12:54:25.352):
Speaking [LangChangeCommand ('en_GB'), u'Creating Portable Copy  dialog  Please wait while a portable copy of NVDA is created.']
DEBUGWARNING - installer.tryRemoveFile (12:54:25.648):
Failed to delete file C:\nvda extra\lib\next-14456,d8cc508f\tmphtto7q, marking for delete on reboot
IO - tones.beep (12:54:26.148):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
DEBUGWARNING - installer.tryRemoveFile (12:54:26.150):
Failed to delete file C:\nvda extra\lib\next-14456,d8cc508f\tmpv8nvta, marking for delete on reboot
IO - speech.speak (12:54:26.153):
Speaking [LangChangeCommand ('en_GB'), u'Please wait']
IO - tones.beep (12:54:26.190):
Beep at pitch 110.0, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:54:26.197):
Speaking [LangChangeCommand ('en_GB'), u'0 percent']
DEBUGWARNING - installer.tryRemoveFile (12:54:26.667):
Failed to delete file C:\nvda extra\lib\tmpzbhtcz, marking for delete on reboot
DEBUGWARNING - gui.ExecAndPump.run (12:54:26.698):
task had errors
Traceback (most recent call last):
  File "gui\__init__.pyc", line 824, in run
  File "installer.pyc", line 430, in createPortableCopy
  File "installer.pyc", line 161, in removeOldProgramFiles
  File "installer.pyc", line 332, in tryRemoveFile
RetriableFailure: Failed to rename file C:\nvda extra\lib64\next-14456,d8cc508f before  remove
ERROR - gui.installerGui.doCreatePortable (12:54:26.698):
Failed to create portable copy
Traceback (most recent call last):
  File "gui\installerGui.pyc", line 263, in doCreatePortable
  File "gui\__init__.pyc", line 820, in __init__
RetriableFailure: Failed to rename file C:\nvda extra\lib64\next-14456,d8cc508f before  remove
IO - tones.beep (12:54:26.703):
Beep at pitch 1760, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:54:26.730):
Speaking [LangChangeCommand ('en_GB'), u'File in Use  dialog  NVDA is unable to remove or overwrite a file.']
IO - speech.speak (12:54:26.743):
Speaking [LangChangeCommand ('en_GB'), u'Retry  button  Alt+r']
IO - inputCore.InputManager.executeGesture (12:54:38.467):
Input: kb(desktop):space
IO - speech._speakSpellingGen (12:54:38.479):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (12:54:38.480):
Adding generator 8
IO - speech.speak (12:54:38.480):
Speaking [LangChangeCommand ('en_GB'), u'pressed']
DEBUG - queueHandler.pumpAll (12:54:38.489):
generator 8 finished
IO - speech.speak (12:54:38.773):
Speaking [LangChangeCommand ('en_GB'), u'Creating Portable Copy  dialog  Please wait while a portable copy of NVDA is created.']
DEBUGWARNING - installer.tryRemoveFile (12:54:39.076):
Failed to delete file C:\nvda extra\lib\tmpzbhtcz\tmpbp6uru, marking for delete on reboot
DEBUGWARNING - installer.tryRemoveFile (12:54:39.578):
Failed to delete file C:\nvda extra\lib\tmpzbhtcz\tmpppazwg, marking for delete on reboot
IO - tones.beep (12:54:39.579):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:54:39.585):
Speaking [LangChangeCommand ('en_GB'), u'Please wait']
DEBUGWARNING - installer.tryRemoveFile (12:54:40.082):
Failed to delete file C:\nvda extra\lib\tmpbdfmix, marking for delete on reboot
DEBUGWARNING - gui.ExecAndPump.run (12:54:40.082):
task had errors
Traceback (most recent call last):
  File "gui\__init__.pyc", line 824, in run
  File "installer.pyc", line 430, in createPortableCopy
  File "installer.pyc", line 163, in removeOldProgramFiles
  File "installer.pyc", line 332, in tryRemoveFile
RetriableFailure: Failed to rename file C:\nvda extra\lib64\next-14456,d8cc508f\tmp0kgsqs before  remove
ERROR - gui.installerGui.doCreatePortable (12:54:40.082):
Failed to create portable copy
Traceback (most recent call last):
  File "gui\installerGui.pyc", line 263, in doCreatePortable
  File "gui\__init__.pyc", line 820, in __init__
RetriableFailure: Failed to rename file C:\nvda extra\lib64\next-14456,d8cc508f\tmp0kgsqs before  remove
IO - tones.beep (12:54:40.089):
Beep at pitch 1760, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:54:40.138):
Speaking [LangChangeCommand ('en_GB'), u'File in Use  dialog  NVDA is unable to remove or overwrite a file.']
IO - speech.speak (12:54:40.154):
Speaking [LangChangeCommand ('en_GB'), u'Retry  button  Alt+r']
IO - inputCore.InputManager.executeGesture (12:54:45.443):
Input: kb(desktop):space
IO - speech._speakSpellingGen (12:54:45.450):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (12:54:45.450):
Adding generator 9
IO - speech.speak (12:54:45.450):
Speaking [LangChangeCommand ('en_GB'), u'pressed']
DEBUG - queueHandler.pumpAll (12:54:45.466):
generator 9 finished
IO - speech.speak (12:54:45.783):
Speaking [LangChangeCommand ('en_GB'), u'Creating Portable Copy  dialog  Please wait while a portable copy of NVDA is created.']
DEBUGWARNING - installer.tryRemoveFile (12:54:46.069):
Failed to delete file C:\nvda extra\lib\tmpbdfmix\tmp6oms_n, marking for delete on reboot
IO - tones.beep (12:54:46.569):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
DEBUGWARNING - installer.tryRemoveFile (12:54:46.569):
Failed to delete file C:\nvda extra\lib\tmpbdfmix\tmpdjlrh7, marking for delete on reboot
IO - speech.speak (12:54:46.573):
Speaking [LangChangeCommand ('en_GB'), u'Please wait']
DEBUGWARNING - installer.tryRemoveFile (12:54:47.075):
Failed to delete file C:\nvda extra\lib\tmpu4xs_a, marking for delete on reboot
DEBUGWARNING - gui.ExecAndPump.run (12:54:47.075):
task had errors
Traceback (most recent call last):
  File "gui\__init__.pyc", line 824, in run
  File "installer.pyc", line 430, in createPortableCopy
  File "installer.pyc", line 163, in removeOldProgramFiles
  File "installer.pyc", line 332, in tryRemoveFile
RetriableFailure: Failed to rename file C:\nvda extra\lib64\next-14456,d8cc508f\tmp0kgsqs before  remove
ERROR - gui.installerGui.doCreatePortable (12:54:47.075):
Failed to create portable copy
Traceback (most recent call last):
  File "gui\installerGui.pyc", line 263, in doCreatePortable
  File "gui\__init__.pyc", line 820, in __init__
RetriableFailure: Failed to rename file C:\nvda extra\lib64\next-14456,d8cc508f\tmp0kgsqs before  remove
IO - tones.beep (12:54:47.082):
Beep at pitch 1760, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:54:47.125):
Speaking [LangChangeCommand ('en_GB'), u'File in Use  dialog  NVDA is unable to remove or overwrite a file.']
IO - speech.speak (12:54:47.140):
Speaking [LangChangeCommand ('en_GB'), u'Retry  button  Alt+r']
IO - inputCore.InputManager.executeGesture (12:54:52.306):
Input: kb(desktop):space
IO - speech._speakSpellingGen (12:54:52.319):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (12:54:52.319):
Adding generator 10
IO - speech.speak (12:54:52.321):
Speaking [LangChangeCommand ('en_GB'), u'pressed']
DEBUG - queueHandler.pumpAll (12:54:52.326):
generator 10 finished
IO - speech.speak (12:54:52.684):
Speaking [LangChangeCommand ('en_GB'), u'Creating Portable Copy  dialog  Please wait while a portable copy of NVDA is created.']
DEBUGWARNING - installer.tryRemoveFile (12:54:52.987):
Failed to delete file C:\nvda extra\lib\tmpu4xs_a\tmpm_zqux, marking for delete on reboot
DEBUGWARNING - installer.tryRemoveFile (12:54:53.489):
Failed to delete file C:\nvda extra\lib\tmpu4xs_a\tmp85iapj, marking for delete on reboot
IO - tones.beep (12:54:53.493):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:54:53.500):
Speaking [LangChangeCommand ('en_GB'), u'Please wait']
DEBUGWARNING - installer.tryRemoveFile (12:54:53.993):
Failed to delete file C:\nvda extra\lib\tmptwwm9k, marking for delete on reboot
DEBUGWARNING - gui.ExecAndPump.run (12:54:53.993):
task had errors
Traceback (most recent call last):
  File "gui\__init__.pyc", line 824, in run
  File "installer.pyc", line 430, in createPortableCopy
  File "installer.pyc", line 163, in removeOldProgramFiles
  File "installer.pyc", line 332, in tryRemoveFile
RetriableFailure: Failed to rename file C:\nvda extra\lib64\next-14456,d8cc508f\tmp0kgsqs before  remove
ERROR - gui.installerGui.doCreatePortable (12:54:53.993):
Failed to create portable copy
Traceback (most recent call last):
  File "gui\installerGui.pyc", line 263, in doCreatePortable
  File "gui\__init__.pyc", line 820, in __init__
RetriableFailure: Failed to rename file C:\nvda extra\lib64\next-14456,d8cc508f\tmp0kgsqs before  remove
IO - tones.beep (12:54:54.000):
Beep at pitch 1760, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:54:54.030):
Speaking [LangChangeCommand ('en_GB'), u'File in Use  dialog  NVDA is unable to remove or overwrite a file.']
IO - speech.speak (12:54:54.048):
Speaking [LangChangeCommand ('en_GB'), u'Retry  button  Alt+r']
IO - inputCore.InputManager.executeGesture (12:54:58.171):
Input: kb(desktop):space
IO - speech._speakSpellingGen (12:54:58.184):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (12:54:58.184):
Adding generator 11
IO - speech.speak (12:54:58.184):
Speaking [LangChangeCommand ('en_GB'), u'pressed']
DEBUG - queueHandler.pumpAll (12:54:58.194):
generator 11 finished
IO - speech.speak (12:54:58.539):
Speaking [LangChangeCommand ('en_GB'), u'Creating Portable Copy  dialog  Please wait while a portable copy of NVDA is created.']
DEBUGWARNING - installer.tryRemoveFile (12:54:58.854):
Failed to delete file C:\nvda extra\lib\tmptwwm9k\tmpd5xazf, marking for delete on reboot
DEBUGWARNING - installer.tryRemoveFile (12:54:59.355):
Failed to delete file C:\nvda extra\lib\tmptwwm9k\tmpbxbjah, marking for delete on reboot
IO - tones.beep (12:54:59.361):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:54:59.368):
Speaking [LangChangeCommand ('en_GB'), u'Please wait']
DEBUGWARNING - installer.tryRemoveFile (12:54:59.858):
Failed to delete file C:\nvda extra\lib\tmpnovurh, marking for delete on reboot
DEBUGWARNING - gui.ExecAndPump.run (12:54:59.859):
task had errors
Traceback (most recent call last):
  File "gui\__init__.pyc", line 824, in run
  File "installer.pyc", line 430, in createPortableCopy
  File "installer.pyc", line 163, in removeOldProgramFiles
  File "installer.pyc", line 332, in tryRemoveFile
RetriableFailure: Failed to rename file C:\nvda extra\lib64\next-14456,d8cc508f\tmp0kgsqs before  remove
ERROR - gui.installerGui.doCreatePortable (12:54:59.859):
Failed to create portable copy
Traceback (most recent call last):
  File "gui\installerGui.pyc", line 263, in doCreatePortable
  File "gui\__init__.pyc", line 820, in __init__
RetriableFailure: Failed to rename file C:\nvda extra\lib64\next-14456,d8cc508f\tmp0kgsqs before  remove
IO - tones.beep (12:54:59.865):
Beep at pitch 1760, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:54:59.901):
Speaking [LangChangeCommand ('en_GB'), u'File in Use  dialog  NVDA is unable to remove or overwrite a file.']
IO - speech.speak (12:54:59.920):
Speaking [LangChangeCommand ('en_GB'), u'Retry  button  Alt+r']
IO - inputCore.InputManager.executeGesture (12:55:04.091):
Input: kb(desktop):space
IO - speech._speakSpellingGen (12:55:04.114):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (12:55:04.114):
Adding generator 12
IO - speech.speak (12:55:04.115):
Speaking [LangChangeCommand ('en_GB'), u'pressed']
DEBUG - queueHandler.pumpAll (12:55:04.121):
generator 12 finished
IO - speech.speak (12:55:04.476):
Speaking [LangChangeCommand ('en_GB'), u'Creating Portable Copy  dialog  Please wait while a portable copy of NVDA is created.']
DEBUGWARNING - installer.tryRemoveFile (12:55:04.773):
Failed to delete file C:\nvda extra\lib\tmpnovurh\tmp0re4co, marking for delete on reboot
IO - tones.beep (12:55:05.273):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
DEBUGWARNING - installer.tryRemoveFile (12:55:05.275):
Failed to delete file C:\nvda extra\lib\tmpnovurh\tmpegzwik, marking for delete on reboot
IO - speech.speak (12:55:05.278):
Speaking [LangChangeCommand ('en_GB'), u'Please wait']
DEBUGWARNING - installer.tryRemoveFile (12:55:05.779):
Failed to delete file C:\nvda extra\lib\tmppxqevx, marking for delete on reboot
DEBUGWARNING - gui.ExecAndPump.run (12:55:05.779):
task had errors
Traceback (most recent call last):
  File "gui\__init__.pyc", line 824, in run
  File "installer.pyc", line 430, in createPortableCopy
  File "installer.pyc", line 163, in removeOldProgramFiles
  File "installer.pyc", line 332, in tryRemoveFile
RetriableFailure: Failed to rename file C:\nvda extra\lib64\next-14456,d8cc508f\tmp0kgsqs before  remove
ERROR - gui.installerGui.doCreatePortable (12:55:05.779):
Failed to create portable copy
Traceback (most recent call last):
  File "gui\installerGui.pyc", line 263, in doCreatePortable
  File "gui\__init__.pyc", line 820, in __init__
RetriableFailure: Failed to rename file C:\nvda extra\lib64\next-14456,d8cc508f\tmp0kgsqs before  remove
IO - tones.beep (12:55:05.786):
Beep at pitch 1760, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:55:05.832):
Speaking [LangChangeCommand ('en_GB'), u'File in Use  dialog  NVDA is unable to remove or overwrite a file.']
IO - speech.speak (12:55:05.855):
Speaking [LangChangeCommand ('en_GB'), u'Retry  button  Alt+r']
IO - inputCore.InputManager.executeGesture (12:55:08.546):
Input: kb(desktop):space
IO - speech._speakSpellingGen (12:55:08.562):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (12:55:08.563):
Adding generator 13
IO - speech.speak (12:55:08.563):
Speaking [LangChangeCommand ('en_GB'), u'pressed']
DEBUG - queueHandler.pumpAll (12:55:08.565):
generator 13 finished
IO - speech.speak (12:55:08.946):
Speaking [LangChangeCommand ('en_GB'), u'Creating Portable Copy  dialog  Please wait while a portable copy of NVDA is created.']
DEBUGWARNING - installer.tryRemoveFile (12:55:09.253):
Failed to delete file C:\nvda extra\lib\tmppxqevx\tmp1u2zl1, marking for delete on reboot
DEBUGWARNING - installer.tryRemoveFile (12:55:09.755):
Failed to delete file C:\nvda extra\lib\tmppxqevx\tmppdi5jw, marking for delete on reboot
IO - tones.beep (12:55:09.765):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:55:09.770):
Speaking [LangChangeCommand ('en_GB'), u'Please wait']
DEBUGWARNING - installer.tryRemoveFile (12:55:10.259):
Failed to delete file C:\nvda extra\lib\tmp753rrz, marking for delete on reboot
IO - tones.beep (12:55:10.779):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
IO - tones.beep (12:55:11.627):
Beep at pitch 1760, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:55:11.678):
Speaking [LangChangeCommand ('en_GB'), u'Success  dialog  Successfully created a portable copy of NVDA at C:\\nvda extra']
IO - speech.speak (12:55:11.690):
Speaking [LangChangeCommand ('en_GB'), u'OK  button']
IO - inputCore.InputManager.executeGesture (12:55:16.891):
Input: kb(desktop):space
IO - speech._speakSpellingGen (12:55:16.904):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (12:55:16.904):
Adding generator 14
IO - speech.speak (12:55:16.904):
Speaking [LangChangeCommand ('en_GB'), u'pressed']
DEBUG - queueHandler.pumpAll (12:55:16.911):
generator 14 finished
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (12:55:17.134):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - speech.speak (12:55:17.206):
Speaking [LangChangeCommand ('en_GB'), u'Creating Portable Copy  dialog  Please wait while a portable copy of NVDA is created.']
IO - speech.speak (12:55:17.209):
Speaking [LangChangeCommand ('en_GB'), u'Creating Portable Copy']
IO - speech.speak (12:55:17.770):
Speaking [LangChangeCommand ('en_GB'), u'Downloads - Mozilla Firefox']
IO - speech.speak (12:55:17.812):
Speaking [LangChangeCommand ('en_GB'), u'Downloads']
IO - speech.speak (12:55:17.812):
Speaking [LangChangeCommand ('en_GB'), u'list']
IO - speech.speak (12:55:17.828):
Speaking [LangChangeCommand ('en_GB'), u'nvda_snapshot_next-14463,7dca66c4.exe 21.4 MB \u2014 windows.net \u2014 12:53 Open Containing Folder  1 of 1']
IO - inputCore.InputManager.executeGesture (12:55:27.010):
Input: kb(desktop):control+alt+r
IO - speech.speak (12:55:27.101):
Speaking [LangChangeCommand ('en_GB'), u'Taskbar']
IO - speech.speak (12:55:27.134):
Speaking [LangChangeCommand ('en_GB'), u'reboot nvda with log  terminal']
IO - speech.speak (12:55:27.134):
Speaking [LangChangeCommand ('en_GB'), u'80 space', u'blank']
INFO - core.main (12:55:27.177):
Exiting
DEBUG - core._terminate (12:55:27.177):
Terminating updateCheck
DEBUG - core._terminate (12:55:27.177):
Terminating watchdog
DEBUG - core._terminate (12:55:27.177):
Terminating global plugin handler
DEBUG - external:globalPlugins.focusHighlight.GlobalPlugin.terminate (12:55:27.677):
focusHighlight terminated
DEBUG - core._terminate (12:55:27.677):
Terminating gui
DEBUG - fileUtils.FaultTolerantFile (12:55:27.684):
C:\Users\Brian\AppData\Roaming\nvda\nvda.ini4smgws.tmp
INFO - config.ConfigManager.save (12:55:27.700):
Base configuration saved
DEBUG - core.main (12:55:27.700):
calling lose focus on object with focus
DEBUG - core._terminate (12:55:27.703):
Terminating treeInterceptorHandler
DEBUG - core._terminate (12:55:27.703):
Terminating IAccessible support
DEBUG - core._terminate (12:55:27.703):
Terminating UIA support
DEBUGWARNING - _UIAHandler.UIAHandler.terminate (12:55:27.904):
Timeout or error while waiting for UIAHandler MTA thread
DEBUG - core._terminate (12:55:27.904):
Terminating winConsole support
DEBUG - core._terminate (12:55:27.904):
Terminating Java Access Bridge support
DEBUG - core._terminate (12:55:27.904):
Terminating app module handler
DEBUG - core._terminate (12:55:27.904):
Terminating NVDAHelper
DEBUG - core._terminate (12:55:27.921):
Terminating touchHandler
DEBUG - core._terminate (12:55:27.921):
Terminating keyboard handler
DEBUG - core._terminate (12:55:27.921):
Terminating mouseHandler
DEBUG - core._terminate (12:55:27.921):
Terminating inputCore
DEBUG - core._terminate (12:55:27.923):
Terminating brailleInput
DEBUG - core._terminate (12:55:27.923):
Terminating braille
DEBUG - core._terminate (12:55:27.923):
Terminating speech
DEBUG - core._terminate (12:55:27.923):
Terminating addonHandler
DEBUG - core.main (12:55:28.974):
core done
INFO - __main__ (12:55:28.992):
NVDA exit
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
What can I say, I click the  update and firefox downloads it, I then action the downloaded file, it closes the running copy and  launches the temp copy in the archive, you then follow all the prompts ( I elected not to self start), and the above is the result. The errors are windows errors of course. If you perform this with start ticked it seems to fall over when it tries to start.
 
Brian

**Comment by leonardder** [comment]
Could you please update your post and file your report according to the issue template? Please also add the log snippet in a separate file, as it is very huge. This will have a major positive impact on triage of the issue you describe. Thanks a lot for your cooperation!

**Comment by Brian1Gaff** [comment]
I would if I could, but have no idea how the template works. They do not 
seem to be separate fields, and the attach seems never to work for me. I'm 
sure this has been mentioned before by others. It was not suggested that the 
template was anything but advisory. The effect I goe is rather obvious.
 Email me off list and explain how to use the template and I'll give it a 
try. Its only recently been there and normally I tend to compose these 
things offline and just upload them into the text box.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by leonardder** [comment]
Attachments need to have a certain extension, but iv you use a txt file created by notepad, that should be fine. Regarding the issue template, please ask for assistance on the NVDA mailing list.

**Comment by Brian1Gaff** [comment]
OK re the update, so txt and log are presumably OK, provided I can coax the actual dialogue to open for me.
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
This message sent from a Windows XP machine!
  ----- Original Message -----

**Comment by leonardder** [comment]
Looking at your log, I think one of the problems is that you have your NVDA distribution directly on your C partition. This is really something that you shouldn't do, as the root of the c partition is normally write protected unless you have administrative privileges. This at least applies to Windows >=8, and I belief also for more recent versions of Windows 7.

**Comment by Brian1Gaff** [comment]
Its a carry over from XP. However is this perhaps not going to be fixed by 
the ticket that asks you to select a folder as at present as we know many 
people can splurge the copy on the desktop in the route or indeed any old 
place. maybe a list of often  wrong places could be prepared to stop this. 
I'm happy to move the portable code elsewhere, but up until very recently 
this has not been an issue even on windows 10 if you have admin rights on 
the machine.
 Opinions are split on whether this practice is desirable and  I do not want 
a war of words over it, suffice to say that it suits me to not have lots of 
messages popping up when I'm trying to move things around my machine.


However if it were a problem here surely me manually copying would also 
throw errors and it does not, so I'm a little reticent of  blaming the 
security levels for this and for many new users this kind of multiple 
windows error failure would completely confuse them.
So I don't off the top of my head know the issue number of the set the path 
and don't accept dodgy ones  thing, but if you think it a good idea, then 
feed this back. My feeling on it is this is a red herring and I'll have a 
test over the weekend with some other paths, I guess the safest thing to do 
would be to use a ram drive instead and see if the updating of  a  very old 
snap with a current one will work without errors. does this seem fair?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by valiant8086** [comment]
Hi.


Do we know how to figure out what this affects? My friends and I always 
run our portable copies from an NVDA folder directly on the c drive. 
Presumably, since the NVDA folder is created by me, NVDA should be able 
to write to it. It saves configurations as expected but seems to crash 
more often than an installed copy. What are the chances the location 
could have an impact on the amount of crashes? If it is because of the 
folder location, it would be handy if it were able to identify a write 
permission issue and alert the user of the problem. I just always 
thought it was ok because once you create a folder even on the top 
level, and you get past the do you really wanna, you can move things in 
and out of it and change things inside it as you please, because you own it.


Cheers:
Aaron Spears, A.K.A. valiant8086. General Partner - Valiant Galaxy Associates "We make Very Good Audiogames for the blind community - http://valiantGalaxy.com"

<Sent with Thunderbird 52.1.0 portable>

**Comment by Brian1Gaff** [comment]
Many apps do install to the root even now. We have a talking newspaper app 
that does this and seems to have no isssues in copying stuff about every 
week. As long as its admin it just seems to work for me, which was why I was 
surprised that an update generated errors from windows. its I think perhaps 
it is opening the file twice in the latest updates. It could be tied in with 
the fix to the problem with firefox where you cannot navigate after 
restarting nvda. As I recall, Mick  made the dll files go into another 
folder but when you update its running, one supposes a portable temp copy, 
and I really do not know which dlls its using then.
 it seems to work fine most of the time on installed versions which 
perplexes me. I will over the next few days carry out some mor controlled 
test perhaps with no add ons and only basic configurations to the portable 
version and add complexity until it falls over.
 As a matter of interest, at the moment if somebody creates a portable 
version of, say the latest next on windows 7, then plugs that into an old XP 
machine, what is likely to occur?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
