### ISSUE TITLE
Outlook 2003 on windows 10 with nvda 2017.3 random crashes

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#7617]
Firstly this on somebody elses machine, which I do not have direct access too, but since Outlook problems do seem to be quite common at the moment the lady has asked me to submit this on her behalf. 
Her direct email is.
sakina.gable@gmail.com

It seems to me that randomly whe an email is opened the  email is not being displayed and things appear to have crashed.
 I did explain to her how to get a log out and to do an nvda/f1 when it happened, so here is the fragment of that log that applies.

IO - speech.speak (11:23:47.177):
Speaking [LangChangeCommand ('en_GB'), u'Inbox - Microsoft Outlook']
DEBUG - NVDAObjects.IAccessible.IAccessible._get_role (11:23:47.194):
IARole: table view
DEBUG - NVDAObjects.IAccessible.IAccessible._get_role (11:23:47.196):
IARole: table view
DEBUG - NVDAObjects.IAccessible.IAccessible._get_role (11:23:47.197):
IARole: table view
IO - speech.speak (11:23:47.221):
Speaking [LangChangeCommand ('en_GB'), u'Message Unread  From Sakina, Subject fingers cross, Received Wed 

9/20/2017, Size 4 KB, Flag Status Unflagged, ']
IO - inputCore.InputManager.executeGesture (11:23:53.221):
Input: kb(desktop):enter
IO - speech.speak (11:23:53.509):
Speaking [LangChangeCommand ('en_GB'), u'fingers cross - Message (HTML) ']
DEBUG - treeInterceptorHandler.update (11:23:53.605):
Adding new treeInterceptor to runningTable: <virtualBuffers.MSHTML.MSHTML object at 0x04E67E90>
IO - speech.speak (11:23:53.611):
Speaking [LangChangeCommand ('en_GB'), u'dialog']
DEBUG - queueHandler.registerGeneratorObject (11:23:53.617):
Adding generator 1611
IO - speech.speak (11:23:53.618):
Speaking [IndexCommand(1)]
DEBUG - queueHandler.pumpAll (11:23:56.191):
generator 1611 finished
IO - inputCore.InputManager.executeGesture (11:24:11.009):
Input: kb(desktop):NVDA+f1
DEBUGWARNING - NVDAObjects.IAccessible.MSHTML.getZoomFactorsFromHTMLDocument (11:24:11.163):
no screen object for MSHTML document
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (11:24:11.749):
Developer info for navigator object:
name: u''
role: ROLE_DOCUMENT
states: STATE_READONLY, STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: 

<NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionBodyMSHTMLIAccessibleWindowNVDAObject object 

at 0x04E67310>
Python class mro: (<class 

'NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionBodyMSHTMLIAccessibleWindowNVDAObject'>, 

<class 'NVDAObjects.behaviors.EditableTextWithoutAutoSelectDetection'>, <class 

'editableText.EditableTextWithoutAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, 

<class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.MSHTML.Body'>, <class 

'NVDAObjects.IAccessible.MSHTML.MSHTML'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 

'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, 

<class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (62, 219, 868, 538)
value: ''
appModule: <'outlook' (appName u'outlook', process ID 5468) at address 4f27590>
appModule.productName: u'Microsoft Office Outlook'
appModule.productVersion: u'11.0.8326'
TextInfo: <class 'NVDAObjects.IAccessible.MSHTML.MSHTMLTextInfo'>
windowHandle: 1574168
windowClassName: u'Internet Explorer_Server'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 324
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x619b558 at 4d353a0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=1574168, objectID=-4, childID=0
IAccessible accName: u''
IAccessible accRole: ROLE_SYSTEM_PANE
IAccessible accState: STATE_SYSTEM_READONLY, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, 

STATE_SYSTEM_VALID (1048644)
IAccessible accDescription: exception: (-2147467263, 'Not implemented', (None, None, None, 0, None))
IAccessible accValue: u'outbind://6-00000000D6D799854872444DAAFB8C98E8A27D22E4CA2E00/'
MSHTML node has ancestor IAccessible: False

It is an old version of Outlook it is true but its been working fine. Unfortunately she did the creators update and nvda update at more or less the same time so it could be either or both!
 Hope this is of help. I've suggested she use Thunderbird instead for now, but its not easy for her to do this. She has though removed Avast as it also joined in the party and made the log almost impossible to follow. She had sighted help for this, and i did wonder if its left any nasty taste behind, but I'm no expert.

### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by leonardder** [comment]
Is this Outlook 2003 or Outlook 2013?

Furthermore, may I ask you to respect the issue template for your future reports? There is now an unfilled issue template below your message. Please also consider adding log snippets of this size in an attachment rather than pasting it directly into your report. Thanks in advance!

**Comment by Brian1Gaff** [comment]
It is 2003.
 As I said in my last email,  I could not figure the template out and did 
the  report offline.

 The upload  system has always given me issues.
 You folk use these things all the time, I do not.
 It would help if the fields were real fields as it looks to my machine like 
one big field with embedded text in it and no gaps.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- O

**Comment by leonardder** [comment]
Outlook 2003 is now over 14 years old and thus abandoned and obsolete software. We've closed issues for outlook 2003 in the past due to this.

**Comment by Brian1Gaff** [comment]
I did tell the lady that this was the case but she is not very rich and she 
has been using it for some time. I suspect this actually has more to do with 
Windows updates than the actual nvda changes she had around the same time.
 If the way IE code is implemented upsets Outlook 2003, they are unlikely to 
fix it.
 I am using Outlook express here on other later windows but this works 
because a third party has created a patch file to allow the newer code to 
run reliably.
 I don't think anyone has done this for Outlook.

Anyway, if you do spot anything let me know, I'm just trying to help her.
 I don't use Outlook in any form and although I have word 2002 here I fully 
expect it to give up soon, and have a version of Libra Office on here as 
back up. I'm not interested in Microsoft office other than a runtime of 
Access to keep an old database going myself.
 I have the microsoft file format converters so no real issues.
 I have  suggested either the native email client in 10 or Tbird, but its 
that old one of the devil you know again.
I'm as guilty as anyone. If  its not broken etc.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by leonardder** [comment]
For reference, see [this MSDN page](https://support.microsoft.com/en-us/help/831607/how-to-view-all-e-mail-messages-in-plain-text-format) has been reported to be a functional workaround.
