### ISSUE TITLE
Handy Tech driver files for updating

### ISSUE THREAD

**Issue by FelixGruetzmacher** [nvaccess/nvda#7621]
This ticket contains the Handy Tech driver auxiliary files for NVDA as of September 23th 2017, validated and ready for inclusion in official NVDA releases.
To include in an existing installation of NVDA, please copy the contents of the zip file to the handyTech folder of NVDA's installation, not user profile. For example, on many systems this place is likely to be:
"C:\Program Files (x86)\NVDA\brailleDisplayDrivers\handyTech"
Anything else should be removed from that folder, that is, make sure it contains only those two files that are contained in the zip.

[HtBrailleDriverServer.zip](https://github.com/nvaccess/nvda/files/1326472/HtBrailleDriverServer.zip)

**Comment by zstanecic** [comment]
@leonardder
@bramd
@dkager
What do you think, as there will be the native support soon?


Wysłane z aplikacji Poczta dla Windows 10

Od: FelixGruetzmacher
Wysłano: sobota, 23 września 2017 12:39
Do: nvaccess/nvda
DW: Subscribed
Temat: [nvaccess/nvda] Handy Tech driver files for updating (#7621)

This ticket contains the Handy Tech driver auxiliary files for NVDA as of September 23th 2017, validated and ready for inclusion in official NVDA releases.
To include in an existing installation of NVDA, please copy the contents of the zip file to the handyTech folder of NVDA's installation, not user profile. For example, on many systems this place is likely to be:
"C:\Program Files (x86)\NVDA\brailleDisplayDrivers\handyTech"
Anything else should be removed from that folder, that is, make sure it contains only those two files that are contained in the zip.
HtBrailleDriverServer.zip

**Comment by leonardder** [comment]
I think it is up to NV Access.

If NV Access, and probably this will be @michaeldcurran, won't be able to review #7590 before 2017.4, it might be a good idea to file a pr against miscdeps for these files. Still, it would be helpful to have sort of a changelog for these files.

**Comment by dkager** [comment]
I agree with @leonardder regarding the changelog. While this does not have to be super detailed, there should probably be some motivation of why these new drivers need to be included. As the PR template suggests, it's important to know why there is need for a change in the first place, what was actually changed and if there are any known issues.

**Comment by leonardder** [comment]
Closing this, because it has been superseeded by #7458.
