### ISSUE TITLE
Add a way to send touch events to the OS

### ISSUE THREAD

**Issue by francipvb** [nvaccess/nvda#7624]
Hello,

I've reading some code sections and after researching I didn't found any way to send touch events to the operating system. May be a manual way, but I don't know the Windows API to do this myself.

I think that the best way may be to implement the `InputHandler.InputGesture.send` method in `touchHandler.TouchInputGesture` class.

Additionally, basic implementation of ~double tap~ action will play a little sound effect and redirect the gesture to windows, because doing an accessible action doesn't work in so much situations, like edit fields or HTML documents. Same for ~double-tap and hold~, like under android.

Purpose of this is to add scripts for android emulator, for example.

Another thing is documentation to do this under a non-script situation, like events, testing or other scripts that receive a different touch gesture.

Cheers,

**Comment by josephsl** [comment]
Hi, when a screen reader starts, it takes over the touchscreen, thus there’s really a no reliable way to pass on the touch gesture(s) to the OS/app. There is sort of a way, but that involves timers (see latest commits in Enhanced Touch Gestures add-on). CC @MichaelDCurran

**Comment by francipvb** [comment]
Hello,

I didn't know about this. Scripting for an android emulator can be so difficult according to this problem.

I'll definitely search for the code you've mentioned.

Cheers,

**Comment by derekriemer** [comment]
I'm not sure you need to close this, It's valid, and we'd love a way to be able to do this.
