### ISSUE TITLE
Group label not read (fieldset / legend, div with role of group)

### ISSUE THREAD

**Issue by RichCaloggero** [nvaccess/nvda#7627]
[group-label-tests.zip](https://github.com/nvaccess/nvda/files/1330322/group-label-tests.zip)
### Steps to reproduce:
1. open attached .zip and load enclosed .html into Firefox
2. Goto top of page and press tab twice.

### Expected behavior:
> Tell us what should happen.

should hear "my group label, choice 1, checkbox, unchecked"

### Actual behavior:
> Tell us what happens instead.

what you hear instead: "choice 1, checkbox, unchecked"

NVDA should read the group label (contents of `legend` element), followed by the label for currently focused item (choice 1 in this case), followed by control type, and current state.

Using `div role="group"` with a label attached via either `aria-labelledby` or `aria-label` also fails to announce the label when entering the group.

Using `div role="region"` with a proper label *does correctly announce the group label* when entering the group.

All tests can be found in the attached .zip.

### System configuration:
NVDA version: 2017.3

NVDA Installed or portable:
installed

Other information:
Firefox 55.0.3 (64 bit)

Windows version:
Windows 7

### Other questions:

Does the issue still occur after restarting your PC?

Yes it does.

**Comment by plinehan** [comment]
Thanks for the workaround of using a region.

**Comment by ehollig** [comment]
I believe this is still an issue using the latest NVDA Alpha.

**Comment by Adriani90** [comment]
I am testing with NVDA 2019.1.1 in Firefox and chrome. Fieldset, group with Aria label and group with Aria labeledby trigger a reporting of the group before control label, type and state. When using region with label and region with labeledby, the group name is not reported but this is expected I guess.

In IE11 the behavior is confusing and inconsistent between browse mode and focus mode. In browse mode, group with Aria label and group with aria labeledby reports group name. But in focus mode NVDA fails to report the group name when using only group with Aria label. But it reports group name on fieldset instead.

**Comment by Adriani90** [comment]
@MarcoZehe, @leonardder is this not related to your recent work on Aria control support?

**Comment by Adriani90** [comment]
This works as expected in Firefox 71 and NVDA 2019.3 Beta 1. Closing as works for me.
