### ISSUE TITLE
I want to change the voice in secure mode...

### ISSUE THREAD

**Issue by KevGP** [nvaccess/nvda#7630]
But I have so many addons and voices in my main NVDA configuration it took over 5 minutes to copy them to my system configuration when using the "Use current settings on secure screens" button. Also I don't want to copy them as this evidently is a security risk. All I want to do is change the voice setting to make it faster, and change the keyboard layout from desktop to laptop. So this isn't possible unless you copy all your addons, taking up extra space on your hard drive? There needs to be a way to change settings on the secure screens without copying all your addons please!!!

**Comment by leonardder** [comment]
Closing as duplicate of #2226, but certainly a valid point I concur with.

**Comment by Brian1Gaff** [comment]
Unless you have a very slow machine, it in no way takes five minutes. If it 
does maybe there is some other issue here.
 In real terms, security is not really an issue. I don't see it as one 
unless you have somebody around who is a bit of a hacker, most folk would 
not be troubled with all the config being copied. If you do not copy it all 
and in the future some parameter of a synth set up as an add on was only 
copied without access to the synth it would fall apart at boot up.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
