### ISSUE TITLE
Moving the mouse into the toolbar freezes libreoffice

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#7631]
### Steps to reproduce:

Beware this may make your machine unusable

 1. Open libreoffice writer
 2. Move the mouse into the toolbar

### Expected behavior:
Moving the mouse should not cause a crash/freeze

### Actual behavior:
LibreOffice and NVDA seem to freeze. The machine has very high CPU usage. 
The machine must be restarted to recover.

### System configuration:
NVDA version:
Next-14432

NVDA Installed or portable: Installed

Windows version:
Windows 10 Version 1709 Build 16291

Name and version of other software in use when reproducing the issue:
LibreOffice 5.4.1.2

### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA? No

**Comment by Qchristensen** [comment]
This seems to be working again (he said tentatively) in LibreOffice 5.4.2.2 (x64).

I tried NVDA 2017.3 (installed) and Next 14509 (temporary) and I seem to be able to move and hover the mouse around the toolbar as much as I like.

Can anyone else still reproduce this issue or can anyone else also confirm it is working

**Comment by feerrenrut** [comment]
Given that Quentin can not reproduce this anymore (now using  LibreOffice 5.4.2.2) I will close this issue.
