### ISSUE TITLE
MSHTML: checked disabled check boxes reported as unchecked

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7637]
### Steps to reproduce:
Paste the following in a html file, or for Firefox/Chrome, prefix with data:text/html,

```
<input type="checkbox"/>Box 1<br />
<input type="checkbox" disabled checked/>Box 2, checked<br />
<input type="checkbox" disabled unchecked/>Box 3, unchecked<br />
```

### Expected behavior:
1. Box 1 reports as checkbox not checked, it can be changed as desired
2. Box 2 reports as unavailable and checked
3. Box 3 reports as unavailable, not checkedchecked

### Actual behavior:
In Internet Explorer 11, box 2 is reported as unavailable, not checked. Also, quick navigation does not work for the unavailable check boxes.

### System configuration:
Reproduced with NVDA 2017.3 on both Windows 7 and 10 x64 systems with Internet Explorer

**Comment by leonardder** [comment]
@MichaelDCurran: Happy to fix this, if I knew where to start. Also, I suggest giving this p2 or p3.

**Comment by michaelDCurran** [comment]
My guess is that it is a bug in MSHTML's own MSAA implementation in Windows. You could possibly get around it by specifically looking for the "checked" attribute in both the vbufBackend and the MSHTML NVDAObject. I'd certainly say this is a p3.

**Comment by leonardder** [comment]
@MichaelDCurran: Thanks for the rapid reply :)
Is there a particular reason why for MSHTML quick nav, focusable is required for check boxes and radio buttons? This isn't a requirement for gecko. Unless there's a good reason, Tempted to drop this requirement for check boxes and radio buttons.

**Comment by michaelDCurran** [comment]
I don't think there is any good reason why focusable was there.

**Comment by leonardder** [comment]
I can't get this to work on the vbuf side. @MichaelDCurran: Would be very grateful if you could take a look at https://github.com/BabbageCom/nvda/tree/i7637

What I did so far:

1. Added checked to the attribute map in the vbuf backend. In the python part, add the checked state in cases where the checked attribute is there.
2. Current implementation (last commit), do everything in the vbuf backend, add the SYSTEM_CHECKED state to input nodes with the checked attribute.

It seems that, even though i explicitly added the checked attribute to the attribute map, the vbuf backend doesn't pick it up, as it doesn't end up in the attribute dictionary for the vbuf control field. It all works great at the object level.

**Comment by Adriani90** [comment]
This is still reproducible in IE11 and NVDA 2019.1.1

**Comment by Adriani90** [comment]
It would be really cool if someone could come up with a solution here. There are lots of corporate environment cases (i.e. SAP netviewer) where people fill online forms. The problem is that once submited, you cannot check with NVDA if the checkboxes in a submited form are checked or unchecked. For example if you have to fill the forms every year and you want to compare the data from previous years, you cannot do it because states of checkboxes from earlier forms are not reported correctly.

**Comment by Cleversn** [comment]
Maybe related: Every time I go to answer a survey, in Google Docs for example, I've stumbled lots of times on check boxes and radio buttons whose status NVDA doesn't correctly report as I check/uncheck, leaving me quite confused. Using Firefox 71 and NVDA 2019.2.1 on Windows 10 1909.

**Comment by Adriani90** [comment]
Support for IE has completely ended in 2022 and the browser is being automatically removed from machines that still have it after an Edge update in February 2023. I don't expect further accessibility updates to IE or to IE mode in Edge. Closing as abandoned.
