### ISSUE TITLE
Report dynamic content changes: speech reports some content in this page

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#7638]
### Steps to reproduce:
1. Press NVDA+5 to toggle "report dynamic content changes" off.
2. Open [this page](http://www.ba.org.tw/PublicInformation/AccessibilityAtm).

### Actual behavior:
Speech reports messages (in Chinese). E.G.:
創意產業融資…
行政院洗錢防制辦公室…
消費者債務清理條例…
新南巷政策…
存款帳戶查詢…
代辦貸款陷阱多…
公務機關查調資料…
不良債權售後申請…
全國繳費往…

### Expected behavior:

These messages are not reported.

### Other questions:

This case also occurs when switching to other window (E.G. notepad++).
This case is not occurred in browser FireFox.

### System configuration:

NVDA version: 2017.3 (installed)
browser: Internet Explorer 11, Google Chrome 61.0.3163.100

**Comment by surfer0627** [comment]
Testing case 2:
You could also reproduce it in this page.
http://www.ntpc.gov.tw/ch/index.jsp

**Comment by leonardder** [comment]
I've seen similar behavior on www.kruidvat.nl, though only in Chrome, and only when focus is inside the pages windows.

**Comment by Adriani90** [comment]
#7743

**Comment by Adriani90** [comment]
Closing this in favor of #7743 and referenced issues because there the discussion is more detailed.
