### ISSUE TITLE
When input field type = 'number' the 'delete' keyboard button doesn't function

### ISSUE THREAD

**Issue by raynesio** [nvaccess/nvda#7645]
### Steps to reproduce:
Create an input field with a _type="number"_ as per the below example:
`<input name="total" value="10" id="total" aria-label="Total" min="0" max="99" type="number">`

Using NVDA and Firefox navigate to the input field and enter some numeric values into the text field. Using the tab key navigate away from the input field element. Now navigate back to the input field and click the 'delete' key. You will see the numeric values cannot be deleted. If the input field has a type of 'tel' or 'text' the delete key does work.

### Expected behavior:
> When the input field type="number" the delete button should delete the numeric values within the field.

### Actual behavior:
> The delete button doesn't delete the numeric values from the input field, when the type="number".

### System configuration:
NVDA version: 2016.2.1
Browser: FireFox 33.1.1
Windows: 7

**Comment by leonardder** [comment]
May I ask why you think this is specific to NVDA? Also, please test this with NVDA 2017.3.

**Comment by raynescc** [comment]
I've tested without a screenreader and with other screenreaders (e.g. Jaws) and it worked fine with this input field type. I've also just tested with NVDA 2017.3 but the result is the same.

**Comment by Adriani90** [comment]
This is not reproducible in NVDA 2019.1.1 and firefox 66.0.3. @raynesio if you can reproduce this issue though, please comment on it and we can reopen the discussion. Thank!
