### ISSUE TITLE
tabbed browsing checkbox in IE8/7 status erratic

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#765]
**Reported by briang1 on 2010-07-16 21:30**
If you launch IE7 or8, and go to tools/internet options, then tab down to the third of the settings buttons (which  don't say what they do), the first checkbox in that property sheet is to toggle tabbed browsing off and on. 
 Pressing  it seems to result in no change announced,, after a while of playing with it, you get it to be checked when its not and not when it is!

The only way to know is to come away and come back again.

**Comment by leonardder** [comment]
This is unlikely to get fixed in the future, if it hasn't been already. 

CC @brian1gaff

**Comment by derekriemer** [comment]
Closing as won't fix, because it's a microsoft bug, and in deprecated software, and hasn't been looked at in years. Reopen if NV Access wants to P4 it.
