### ISSUE TITLE
The official community Nvda in Russia.

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#7650]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the resultHello. In Russia, a lot of people use NVDA. I propose to create a formal community in VK this is the most popular social network in Russia.

I can help with that.

**Comment by leonardder** [comment]
This issue tracker is only related to bugs or enhancements for NVDA itself, not for community matters. Closing this issue because of this. Nevertheless, your ideas are of course much appreciated, please address them to the [NVDA groups.io mailing list](http://nvda.groups.io)

**Comment by ehollig** [comment]
There is a Russian mailing list: To subscribe, send blank e-mail to nvda-rus-subscribe@tiflo.info. You can also send suggestions to the International users' mailing List (English). To subscribe, send a blank email to: nvda+subscribe@groups.io.
Source: https://github.com/nvaccess/nvda-community/wiki/Connect
