### ISSUE TITLE
Inconcistencies in the French documentation

### ISSUE THREAD

**Issue by vlegoff** [nvaccess/nvda#7651]
There are some inconsistencies in the French documentation.  The document in question can be found at https://www.nvda-fr.org/doc/userGuide.html , although I imagine the official NVDA in French has the same issue.  In section 6, "mode navigateur" (browse mode), sub-section 6.1, "Les touches de navigation rapide" (quick keys), some keys do not properly map.

h = titre (should be "t")
t = tableau (should be "y")
n = texte (should be "b" , if I'm not mistaken)
u = lien non visité (I couldn't find this one)
b = boutton (should be u)
c = liste déroulante (should be z)
q = balise de citation (should be c)

> Please note: the previous list has been compiled through observations using the French version of NVDA.  Quick keys do not match in English and French to offer more logical navigation keys.  The French documentation offers keys that don't behave as expected.  The list presented above might not be exhaustive at all, please check accuracy.

Thank you for your good work,

**Comment by leonardder** [comment]
Hmm, if I set my NVDA language to french, H moves to headings and t moves to tables, which is exactly what the documentation says.

**Comment by Andre9642** [comment]
Hello,
No problem here (I am a french user).
You have probably an add-on that modify these gestures. Maybe the Accessolution add-on?

**Comment by ehollig** [comment]
@vlegoff, as suggested in https://github.com/nvaccess/nvda/issues/7651#issuecomment-335843321 can you try this with all NVDA addons disabled? It is possible that one of them has modified your input gestures

**Comment by ehollig** [comment]
Closing as worksforme. If this is still an issue after trying the solution in https://github.com/nvaccess/nvda/issues/7651#issuecomment-335843321, we can reopen this.
