### ISSUE TITLE
Headers jumping is broken in windows 10 version 1703 when Open a PDF file with Microsoft edge.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#7653]
### Steps to reproduce:
> 
Find and open a PDF file that include headers info with Microsoft Edge.
> Press arror keys to sure there are headers in the document: Succeed.
> Press h/1/2/3/4/5/6 to try to jump to the header.

### Expected behavior:
> Jump to the specific headers's level.

### Actual behavior:
> No headers can be found.

### System configuration:
NVDA version:next-14515

NVDA Installed or portable:Installed

Windows version:1703--build:15063.608

Name and version of other software in use when reproducing the issue: Microsoft Edge

### Other questions:

Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
> Please list them and the result
No.
[紫光学大2017H1.zip](https://github.com/nvaccess/nvda/files/1375084/2017H1.zip)

**Comment by feerrenrut** [comment]
Are you sure that the PDF example you provided includes header information? I am not able to jump to headers with this PDF when using Acrobat reader, can you? With other PDFs, I can however reproduce this behaviour.

**Comment by vgjh2005** [comment]
Hi:
I think you should use edge to test this issue. Because this issue is occured at microsoft edge. My way to sure document  include headers info is pressing arror keys. NVDA will tell me headers level info. But can't jump to it by pressing H key.

**Comment by feerrenrut** [comment]
Sorry, I wasn't very clear.

With the PDF supplied on this issue (2017H1.zip) I could:
* Not jump to headers in Acrobat reader
* Not jump to headers in Edge

With another PDF on my system I could:
* jump to headers in Acrobat reader
* Not jump to headers in Edge

**Comment by vgjh2005** [comment]
So, headers jumping in edge has been broken.

2017-10-25 14:24 GMT+08:00, Reef Turner <notifications@github.com>:

**Comment by feerrenrut** [comment]
Has this worked in the past? If so, do you know what versions of NVDA or Edge you were using? or when approximately it did work?

**Comment by leonardder** [comment]
@vgjh2005: What is the state of this in Windows 10 version 1803?

**Comment by Adriani90** [comment]
This works as expected in Edge Chromium 81. Closing as works for me and as abandoned because we didn't get any updates from the initial author since year.

**Comment by Adriani90** [comment]
Adding appropriate label since this is probably still reproducible in Edge Spartan and UIA related environments.
