### ISSUE TITLE
Text double speaks in Google Docs with speak typed characters on

### ISSUE THREAD

**Issue by ehollig** [nvaccess/nvda#7660]
### Steps to reproduce:
1. Open Chrome
2. Browse to docs.google.com
3. Open a new document
4. Type some text with speak typed characters on and again with speak typed characters off.
5. Notice the letters are announced twice with speak typed characters on and announced once with speak typed characters off.
### Expected behavior:
With speak typed characters on, letters should be announced once. With speak typed characters off, no text should be spoken when typing.
### Actual behavior:
See above.
### System configuration:
NVDA version: Master-14512,2fc602c8
NVDA Installed or portable: Installed
Other information:
Windows version:
Windows 10, 1703 (OS Build 15063.674)
Name and version of other software in use when reproducing the issue:
Google Docs

### Other questions:
Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
No

I assume this has to do with live region change as partially discussed in #5760 as the results are similar.

**Comment by derekriemer** [comment]
Google deliberately puts a live region here, speaking everything you type. We can't detect the difference between this and valid behavior.

**Comment by fernando-jose-silva** [comment]
If it is intended not to solve this problem due to deliberate google behavior, I suggest documenting in the nvda documentation that typed character reading is disabled when using google docs.
I believe that only google inserting this information is not enough, the first thing I thought is that it would be a nvda problem.
