### ISSUE TITLE
Possibly Remove the UI Automation only supported in Windows 7 and later Statement from the User Guide

### ISSUE THREAD

**Issue by Mohamed00** [nvaccess/nvda#7664]
Since Windows XP and Windows Vista are no longer supported, I believe the "(UI Automation only supported in Windows 7 and later)" statement should probably be removed from section 1.1, unless of course it still applies to Windows Server 2008 R2, in that case it should be clarified.

**Comment by josephsl** [comment]
Hi, agreed, and will be part of the docs17.4 fix. CC @MichaelDCurran

**Comment by derekriemer** [comment]
was there a reason to cc @michaelDCurran if you plan to do the work?

**Comment by josephsl** [comment]
Hi, to hear expert opinions. Thanks.

**Comment by ehollig** [comment]
@josephsl, as docs17.4 or #7662 is now merged, can this be safely closed?

**Comment by josephsl** [comment]
Hi, yes, go ahead. Thanks.

**Comment by ehollig** [comment]
Closing as fixed by #7662
