### ISSUE TITLE
enable description of images in nvda

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7671]
Using the narrator in windows 10 16299 there is a function of reading image descriptions by pressing capslook + shift + d.
Would it be possible to make this function available to nvda?
Thank you very much.

**Comment by josephsl** [comment]
Hi, it’ll require that we find a way to work with Azure (perhaps through subscriptions or as part of an API). Also, I think this is a duplicate of another issue. Thanks.

**Comment by fernando-jose-silva** [comment]
Thank you very much.

**Comment by Adriani90** [comment]
cc: @larry801, @OliverEdholm in my opinion this feature should remain as an addon. What do you think? I don't think NV Access have the time and the ressources to maintain data bases and what not.

**Comment by Adriani90** [comment]
Closing this in favor of #16281 which contains more valuable discussion.
