### ISSUE TITLE
NVDA position information Reports one more item in some lists than actually present

### ISSUE THREAD

**Issue by masonasons** [nvaccess/nvda#7676]
### Steps to reproduce:
This happens in more than Foobar2000, but we'll use it as an example.
0. Turn on Report object position information
1. Open Foobar2000
2. Add something to your playlist, either by playing a file or adding one.
3. Focus the playlist list.
4. NVDA will say "1 of 2" when there is only 1 item.

Another option
Let's use Xplorer2
1. Open xplorer2
2. Check any of the panes.
3. It will say one more list item than there actually is, consistently.

### Expected behavior:
I should see how many list items there actually are.

### Actual behavior:
I see one extra list item.

### System configuration:
NVDA version: 2017.3

NVDA Installed or portable: Installed

Other information:

Windows version: 8.1, happens in 7 and 10 as well.

Name and version of other software in use when reproducing the issue:
Foobar2000
Zabkit Xplorer2

### Other questions:

Does the issue still occur after restarting your PC? Oh yes

Have you tried any other versions of NVDA? Yes, the snapshot does this as well.

**Comment by leonardder** [comment]
Do you have the option "Guess object position information when unavailable" enabled?

**Comment by ehollig** [comment]
This sounds like another instance of #8683. Please reopen if this is not the case @masonasons
