### ISSUE TITLE
IE11 bringserror in NVDA in snapshots greater then 2017.3

### ISSUE THREAD

**Issue by Novalis7747** [nvaccess/nvda#7683]
1) start NVDA (any development snapshot after 2017.3
2) start IE11
3) you hear a NVDA error beep
4) console shows
NVDA initialized
ERROR - RPC process 14948 (iexplore.exe) (13:28:19.160):
Thread 14884, build\x86\remote\COMProxyRegistration.cpp, registerCOMProxy, 111:
Error fetching class object for IAccessible2Proxy.dll, code -2147221231
5) this is all the time and also for other applications using IE embedded
6) it also happens when going through several websites. I hear a beep when using TAB, most possibly on social network connectors.

### Expected behavior:
no error beeps and social connectors are read properly

### Actual behavior:
getting above error messages in NVDA log and those  beeps

### System configuration:
NVDA version:
Nonvisual Desktop Access (NVDA)
Version: next-14541,267b5407
NVDA Installed or portable:
installed, not portable, but same effects with a portable copy

Other information:

Windows version:
Version 1709 (OS Build 16299.19)

Name and version of other software in use when reproducing the issue:
IE11 only
### Other questions:

Does the issue still occur after restarting your PC?
Yes, all the time
Have you tried any other versions of NVDA?
> Please list them and the result
2017.3 doesnt give this error

**Comment by feerrenrut** [comment]
I haven't been able to reproduce this issue with a recent build of NVDA, @Novalis7747 can you still reproduce this issue?

**Comment by Adriani90** [comment]
@Novalis7747     could you please Elaborate shortly why you Close this issue? Does it work for you now properly?

**Comment by Novalis7747** [comment]
It got fixed somewhen in the last 4 months by one of the several IE security updates .
