### ISSUE TITLE
Pseudo elements (::before, ::after) are treated as list items (Chrome)

### ISSUE THREAD

**Issue by error404as** [nvaccess/nvda#7684]
### Steps to reproduce:
> Conditions when problem could be reproduced: 
> 1. Google Chrome browser only (can't reproduce in FireFox or IE)
> 2. UL/OL element should have `::before` or `::after` pseudo elements.
> 3. Pseudo elements should have *size* (width/height + not default `display: inline;` behavior).
> 4. List should have a wrapper with js **event listener**.

NVDA says that pseudo elements (commonly used as decorative elements) are list items.

[Live example](http://asdx.pw/bug/nvda-list.html).

### Expected behavior:
> NVDA should ignore empty pseudo elements and not count them as list items.

### Actual behavior:
> NVDA takes pseudo elements as list items.

### System configuration:
NVDA portable 2017.3.
Windows 8
Google Chrome 62.0.3202.62

**Comment by ehollig** [comment]
Is this related to #6584

**Comment by feerrenrut** [comment]
I can't reproduce this with Google Chrome 63.0.3239.84
@error404as are you happy for this issue to be closed?

**Comment by error404as** [comment]
@feerrenrut Great, it's really not reproducible any more. Thanks
