### ISSUE TITLE
Support edit fields in MS Access

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#769]
**Reported by briang1 on 2010-07-19 13:56**
In a few MS Access applications and databases I have, although its possible to use them in the main, even in Access 2002, the edit fields do not act correctly when cursored or deleted, acting as if they are in fact blank. 
Also, sometimes when something is typed it remains and when you come back it is spoken but its in  fact not there at all.

In order to help at least with the main problem, I'm hopefully attaching a very small application with one edit field that changes system date. It does show the editable problem. The nvda f1 reports as follows.
INFO - appModules._default.AppModule.script_navigatorObject_devInfo (14:46:03):
Developer info for navigator object:
name: u'Change System Date to'
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_FOCUSED
Python object: <NVDAObjects.IAccessible.IAccessible object at 0x022F0E50>
Python class mro: (<class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (230, 216, 100, 15)
value: u''
appModule: <_default (appName msaccess, process ID 1072) at address 2372510>
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 394006
windowClassName: u'OForm'
windowControlID: 1041
windowStyle: 1456406528
windowThreadID: 600
windowText: u'System Date Form : Form\x00'
IAccessibleObject: <POINTER(IAccessible) ptr=0x1c18f0 at 2313490>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=394006, objectID=3, childID=0
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)

**Comment by leonardder** [comment]
@brian1gaff: Could you provide a status update for this issue?

**Comment by Adriani90** [comment]
@Brian1Gaff could you please give us an update regarding this issue? Could someone upload the attachment? I want to try it with newest NVDA and MS Access version. Thanks.

**Comment by ehollig** [comment]
@Adriani90, I have edited the original comment with the attachment.

**Comment by Adriani90** [comment]
In any case, when i type something in the "change system date to", it is spoken by NVDA. When I press tab twice I land on the change date field and the content is being reported as it should be.

**Comment by Adriani90** [comment]
This issue cannot be reproduced peroperly, I suggest closing it. @Brian1Gaff, please open a new issue with current MS Access file (preferably MS Access 2007 or higher).

**Comment by josephsl** [comment]
Hi,

Actually, with Office 2010 and higher. Closing. Thanks.
