### ISSUE TITLE
LoadLibrary failed for ISimpleDOM.dll

### ISSUE THREAD

**Issue by Gucalle** [nvaccess/nvda#7691]
I'm not sure what happened exactly.  Webroot Secure Anywhere detected something in NVDA as adware, and before i had time to try to get it to ignore the problem, it did an autoscan and removal of something.  

Now, whenever I open NVDA, or it interacts with a newly open program, I get a system error sound, as well as sometimes requiring me to alt+tab in and back out of the program to get it to interact with it.  

Checking the log viewer, I get the title posted above on almost every error entry:  

```
ERROR - RPC process 9348 (nvda.exe) (19:23:18.907):
Thread 4364, build\x86\remote\COMProxyRegistration.cpp, registerCOMProxy, 63:
LoadLibrary failed for ISimpleDOM.dll

ERROR - RPC process 9348 (nvda.exe) (19:23:18.937):
Thread 4364, build\x86\remote\ia2Support.cpp, installIA2Support, 63:
Error registering ISimpleDOM proxy
```

I tried to uninstall and reinstal the latest stable and snap releases, but the problem persissts.  Any ideas on how to make it stop doing this?  The problem is more annoying than crippling at the moment, but that might be due to me not discovering the issue.

**Comment by Brian1Gaff** [comment]
When I saw this last night, I assumed it was due to the too many tests of 
installing to prove the new update worked. I ended up completely rebooting 
the system then installing from a known working portable version.

Brian
Note it was a little awkward if you left it running as some bits of nvda 
then had no typing in feedback.



bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Gucalle** [comment]
Ah, so I should try to use someone else's computer for a bit and make a portable copy there, completely wipe NVDA from this one, and see if the portable copy works on here, and install from there?  Well thanks for that bit of info, I'll go try it out tomorrow.

     The other thing I could also look into is trying to restore whatever WSA took out and see if that works.  Granted, given how annoyingly inaccessible this is, I'm going to need some help finding the quarantined panel and the file that was taken out of NVDA.   Probably best since if I try to get the portable copy installed as the main one, WSA is going to panic and clean it again unless I try that.

    Also I noted that NVDA freezes up if one tries to highlight text in an edit box with the error active.  Other than that, it's just system error beeps whenever it interacts with a new program, or a web page is refreshed and not much else.

**Comment by Gucalle** [comment]
Ah, so I should try to use someone else's computer for a bit and make a portable copy there, completely wipe NVDA from this one, and see if the portable copy works on here, and install from there?  Well thanks for that bit of info, I'll go try it out tomorrow.

     The other thing I could also look into is trying to restore whatever WSA took out and see if that works.  Granted, given how annoyingly inaccessible this is, I'm going to need some help finding the quarantined panel and the file that was taken out of NVDA.   Probably best since if I try to get the portable copy installed as the main one, WSA is going to panic and clean it again unless I try that.

    Also I noted that NVDA freezes up if one tries to highlight text in an edit box with the error active.  Other than that, it's just system error beeps whenever it interacts with a new program, or a web page is refreshed and not much else.

**Comment by Gucalle** [comment]
Ah, so I should try to use someone else's computer for a bit and make a portable copy there, completely wipe NVDA from this one, and see if the portable copy works on here, and install from there?  Well thanks for that bit of info, I'll go try it out tomorrow.

     The other thing I could also look into is trying to restore whatever WSA took out and see if that works.  Granted, given how annoyingly inaccessible this is, I'm going to need some help finding the quarantined panel and the file that was taken out of NVDA.   Probably best since if I try to get the portable copy installed as the main one, WSA is going to panic and clean it again unless I try that.

    Also I noted that NVDA freezes up if one tries to highlight text in an edit box with the error active.  Other than that, it's just system error beeps whenever it interacts with a new program, or a web page is refreshed and not much else.

**Comment by josephsl** [comment]
Hi, one important thing you need to do: if WSA panics again, do let WSA developers know as soon as possible. We had similar hiccups like this with several AV vendors a while back. Thanks.

**Comment by Adriani90** [comment]
@Gucalle in NVDA menu under Tools you can find a tool called "com registration fixing tool". Did you try to run that tool and see if it solves your problem?

**Comment by Adriani90** [comment]
@michaelDCurran I guess this dll is considered already in the registration fixing tool. Right?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years. I am closing this issue as abandoned. Please comment if you are still having this issue and we can reopen.
