### ISSUE TITLE
NVDA can not read the information in "Turn Windows features on/off" if they is installed on an USB-key

### ISSUE THREAD

**Issue by andersbp** [nvaccess/nvda#7694]
### Steps to reproduce:
1. Install the latest version of NVDA on an USB-key, where you install NVDA as a portable version
2. After that, run NVDA from the USB-key
3. Press on the Windows-key, so the start menu open in Windows
4. Write programs and features, and find the option "Programs and features" via the arrow keys
5. Pres enter to open "Programs and features"
6. Now, use the tabulator-key to find "Turns Windows features on/off" and press enter
7. If you try to navigate in the list there come up over features in Windows, NVDA not read the information, but only say "Window".

If I install NVDA localy on my computer, and start NVDA (without Automatic start up on the logon-screen), NVDA fine will read the informations in the "Turns Windows features on/off".

Testet on Windows 7 Service Pack 1 and Windows 8.1.

Is it possible that NVDA also can read the information in"Turn Windows features on/off" if I only run NVDA from a portable version on an USB-key?

Thanks in advance for your help!

Regards,
Anders

**Comment by leonardder** [comment]
From the readme:

> Apart from the  inability to automatically start during and/or after log-on, the portable and temporary copies of NVDA also have the following restrictions:
> - The inability to interact with applications running with administrative privileges, unless of course NVDA itself has been run also with these privileges (not recommended).
> - The inability to read User Account Control (UAC) screens when trying to start an application with administrative privileges.
> - Windows 8 and later: the inability to support input from a touch screen.
> - Windows 8 and later: the inability to provide features such as browse mode and speaking of typed characters in Windows Store apps.
> - Windows 8 and later: audio ducking is not supported.

Closing as can't fix.
