### ISSUE TITLE
Menu and menu item quick navigation keys

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/nvda#7695]
I'm forwarding a suggestion from a @babbagecom customer, who would like to have quick navigation possibilities for either menus, menu items or both. I'd like to suggest the following possibilities:

* Treat menu's as lists and menu items as list items.
* Add separate menu and menu item quick navigation commands, and leave them unbound by default, similar to what I suggested in #7538

**Comment by leonardder** [comment]
In https://github.com/nvaccess/nvda/pull/10424: I added support for quick navigation scripts that are unbound by default.

**Comment by bhavyashah** [comment]
Menus/menu buttons and menu items are becoming increasingly common on the Internet. Just wondering:
* Is this an accepted feature request or still under debate?
* @leonardder Is there any chance you might take up work on this issue?

**Comment by cary-rowen** [comment]
I very much hope to be able to do this.

**Comment by Adriani90** [comment]
Menu buttons can be navigated with "b", for menu items, I wonder if it could be possible to integrate menu item also in list item navigation, quicknav "i"?
and the menu itself could be treated as a list, quicknav "l"?

**Comment by leonardder** [comment]
I'm happy to take this as soon as there is consensus and agreement from NV Access about the strategy to follow regarding key assignments and/or combining these with other quicknav keys.

**Comment by Adriani90** [comment]
Unassigned quick nav scripts for menu items and toggle buttons have been added in #16247. Closing as fixed. If something is still needed, please open a new request.
