### ISSUE TITLE
LibreOffice Writer: Border style not reported

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#7701]
In LibreOffice 5.4.2.2 (x64) using NVDA 2017.3:

Press alt+o then P to open page options
or
Press alt+o then A to open paragraph options

then press control+tab to move to the borders page of the dialog.
Next, press tab to move to "Line, Style".  This drop down list has options for the type of line used for the border (solid, dotted, dashed, double lines, etc).  These styles are not reported, simply the number in the list.

LibreOffice bug 95247: https://bugs.documentfoundation.org/show_bug.cgi?id=95247 Not clear on that ticket whether this just affects NVDA or other screen readers such as Orca on Linux as well.

**Comment by michaelweghorn** [comment]
> LibreOffice bug 95247: https://bugs.documentfoundation.org/show_bug.cgi?id=95247 Not clear on that ticket whether this just affects NVDA or other screen readers such as Orca on Linux as well.

This is now fixed in Libreoffice (will be in LO 24.2), so I think this issue can be closed. See this LO bug for more details:
https://bugs.documentfoundation.org/show_bug.cgi?id=101886

**Comment by Adriani90** [comment]
Thanks very much for updating this and for the great work on this. I am closing as completed.
