### ISSUE TITLE
locale / ko/LC_MESSAGES: wxstd.mo not included

### ISSUE THREAD

**Issue by dnz3d4c** [nvaccess/nvda#7707]
There is no wxstd.mo file in locale / ko/LC_MESSAGES directory. This causes an untranslated string to be present in the voice setting dialog (OK, Cancel button)

Thanks

**Comment by josephsl** [comment]
Hi, that’s because there were no changes made to the po file in a very long time. Will see if wxPy4 includes a fix, and if so, this issue will be closed once #7077 is closed. Thanks.

**Comment by dnz3d4c** [comment]
Thanks

**Comment by ehollig** [comment]
@josephsl in https://github.com/nvaccess/nvda/issues/7707#issuecomment-340137858 you indicate that this issue may be closed once #7077 is merged. Is that still the case?

**Comment by josephsl** [comment]
Hi, I’d say let’s close this for now until we hear comments from Korean users. Thanks.

**Comment by dnz3d4c** [comment]
Currently, the file is not included in NVDA, but for this issue NVDA's settings dialog is improved and can not be reproduced. I think the wxstd.mo file is not needed. However, it can be used in other dialogs or widgets, so it looks like you need to review it.
> 
> 
> @josephsl in [#7707 (comment)](https://github.com/nvaccess/nvda/issues/7707#issuecomment-340137858) you indicate that this issue may be closed once #7077 is merged. Is that still the case?

**Comment by ehollig** [comment]
Closing for now, as requested in https://github.com/nvaccess/nvda/issues/7707#issuecomment-429505712
