### ISSUE TITLE
Layout Tables are not being ignored in Microsoft Edge

### ISSUE THREAD

**Issue by dineshkaushal** [nvaccess/nvda#7708]
### Steps to reproduce:

1. Open Microsoft Edge
2. Browse to http://developer-guide.access4all.ch/en/examples/hide_empty_table_cells_in_layout_tables.html
3. Navigate till you observe that there are tables, but they not data tables.

This page was created by @jmuheim for issue #5391, but we could use for our purpose as well.

### Expected behavior:
These tables should be ignored as they are being ignored in Internet Explorer and Firefox.

### Actual behavior:
Tables are being reported which leads to a lot of extra information.

### System configuration:
NVDA version: 2017.3

NVDA Installed or portable: Installed

Windows version: Windows 10

**Comment by Adriani90** [comment]
The link is not working anymore, but I have tested on other websites with layout tables in Edge Chromium 81. Everything works correctly now. Tested with NVDA Version: alpha-20026,16ec967e.

Closing.
