### ISSUE TITLE
Drop down announcing issue

### ISSUE THREAD

**Issue by harsha9963** [nvaccess/nvda#7714]
While navigating to the drop down box using "Tab" key. The reader is not able to announce the label or description of the box every time I navigate to it. The screen reader announces it sometimes and doesn't most of the times. But, The label or the description is getting printed on the screen viewer every time I navigate to the box.

**Comment by ehollig** [comment]
Could you provide an example where this is happening? Also, could you please provide exact detailed steps to reproduce, including what you did, what you expected to happen and what happened instead.

**Comment by ehollig** [comment]
Closing as invalid, as we have not heard from @harsha9963 and has not provided the requested information in https://github.com/nvaccess/nvda/issues/7714#issuecomment-340928720.
Possibly related: #7550
