### ISSUE TITLE
Input of Grade 1 Braille in Portuguese is not working on Focus Blue braille displays

### ISSUE THREAD

**Issue by xtstoll** [nvaccess/nvda#7717]
### Steps to reproduce:
> 1. Install [driver](https://www.freedomscientific.com/Downloads/Focus/FocusBlueBrailleDisplayDriver) for Focus Blue braille displays
> 2. Start NVDA
> 3. Open NVDA Preferences > Braille options
> 4. Specify the input as Portuguese Grade 1 and output as Portuguese Grade 1
> 5. Select OK
> 6. Open Notepad
> 7. Type on your QWERTY keyboard: A B C 1 2 3
> 8. Read that line on the Braille display
> 9. Press ENTER on QWERTY keyboard to skip a line
> 10. Type the same text (A B C 1 2 3) on the Braille display using Portuguese Grade 1 rules. For example, for the capital A, press dots 4 and 6 (capital letter symbol), then dot 1. For the number 1, press dots 3, 4, 5, and 6 (number symbol), then dot 1.

### Expected behavior:
> On the Braille display and on the screen, the output should be: **A B C 1 2 3**

### Actual behavior:
> On the Braille display and on screen, the output is: **1 2 3 ª 2 3**

### System configuration:
NVDA version: 2017.3
NVDA Installed or portable: installed

Other information:
Windows version: Windows 10.15063
Name and version of other software in use when reproducing the issue: Focus Blue 40 with Firmware 5.71

### Other questions:
Does the issue still occur after restarting your PC? Yes
Have you tried any other versions of NVDA? Yes, 2017.4 and 2018.1rc1 (same result for both)

### Other notes:
This Spanish Grade 1 works just fine, which uses the same scheme as Portuguese for capital letters and numbers. English Grade 1 works perfectly as well, but it's not comparable because the scheme for capital letters is different. I suspect that there is something wrong with the Portuguese Grade 1 Braille table.

This is troubling because we have kids trying to use Braille displays in public schools with NVDA. Kids use Grade 1 here in Brazil, so this is a big problem for them. Help, please!

![nvda_2017-11-01_12-15-04](https://user-images.githubusercontent.com/24814666/32279373-b7452bc6-beff-11e7-9242-6169c5da3ef6.png)

**Comment by zstanecic** [comment]
@josephsl,

does it need an external fix from the portuguese braille table maintainer?



W dniu 01.11.2017 o 15:26, xtstoll pisze:

**Comment by josephsl** [comment]
Hi, based on data given, yes. In this case, the proper authority would be Liblouis people. Thanks.

**Comment by josephsl** [comment]
BTW, please test with latest master snapshot (as a portable copy) and see if the issue isn’t present in 2017.4, otherwise let’s make a trip to Liblouis. Thanks.

**Comment by ruifontes** [comment]
We are lloking to this error and others.
The corrected tables will be submited to LibLouis.

Rui


-----Mensagem Original----- 
De: zstanecic
Data: 1 de novembro de 2017 14:38
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Input of Grade 1 Braille in Portuguese is not 
working (#7717)

@josephsl,

does it need an external fix from the portuguese braille table maintainer?



W dniu 01.11.2017 o 15:26, xtstoll pisze:

**Comment by leonardder** [comment]
Is there a liblouis issue to track for this?

**Comment by leonardder** [comment]
@xtstoll: Could you please check whether this problem is fixed in the most recent next snapshot?

**Comment by xtstoll** [comment]
Unfortauntely, it does not seem to be fixed...

The output on screen (1 2 3 ª 2 3):
![notepad_2018-03-07_17-15-51](https://user-images.githubusercontent.com/24814666/37115932-6dac73e0-222b-11e8-8cbb-67e82d3e8f38.png)

The output in braille (1 2 3 ª 2 3):
![img_20180307_171540501_hdr](https://user-images.githubusercontent.com/24814666/37115990-97ca79ce-222b-11e8-8400-eb68d246ed78.jpg)

Snapshot version used to test (version 14934,4d2100c1):
![nvda_2018-03-07_17-16-12](https://user-images.githubusercontent.com/24814666/37115933-6dd44ee2-222b-11e8-8ba5-9b01cd34400e.png)

Braille configs in NVDA:
![nvda_2018-03-07_17-16-53](https://user-images.githubusercontent.com/24814666/37115982-932ec0aa-222b-11e8-882e-7f814eeb5e07.png)

**Comment by Adriani90** [comment]
@ruifontes,  @xtstoll any update on this? Is the issue still reproducible?

**Comment by ruifontes** [comment]
I don't know...

I haven'tany Braille display with a keyboard to test...

But, close it anyway, since the error, if any, it is to be solved in 
LibLouis...

Rui Fontes


Às 09:45 de 01/05/2019, Adriani90 escreveu:

**Comment by xtstoll** [comment]
I was able to test here with Focus 40 Blue and NVDA 2019.1.1 on Windows 10. This seems to be resolved! Numbers and capital letters are working properly now. 

There is another issue with Portuguese characters on the Focus 40 Blue with NVDA, which I have also reported here for the Braille Me:
https://github.com/nvaccess/nvda/issues/9665#issuecomment-498445296
