### ISSUE TITLE
NVDA with IE & FF not reading the product name.

### ISSUE THREAD

**Issue by Techieegirl** [nvaccess/nvda#7720]
We are using NVDA + IE 11 on the website and the Product name (clickable link) is not recognizing correctly. Instead of saying "Product name" NVDA is announcing "grouping". We feel its a known issue. Reference to the known issue :- https://dequeuniversity.com/testsuite/aria/aria-label-aria-labelledby/results/

NVDA + FF have same kind of issues but instead of saying the Product name, NVDA announces Section.

This Issue is not reproducible with JAWS and NVDA (chrome).

### Expected behavior:
> Expected is to read out the Product name which is visible on the screen.

### System configuration:
NVDA version:
> Example: 2017.2

NVDA Installed On Windows

Windows version:
> Example: Windows 7 Enterprise Version 64 bit

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
> Please list them and the result
Exists on IE11, IE10, NVDA 2017.2 2016

**Comment by ehollig** [comment]
Can you please provide exact detailed steps to reproduce, including what you did, what you expected to happen and what happened instead. I am not able to locate the text "Product name" on the website you reference.

**Comment by Brian1Gaff** [comment]
No me neither.


bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by feerrenrut** [comment]
It's not very clear, but I think the link is not supposed to be an example, but instead it's the proof.  

@Techieegirl The page you linked to has quite a few tests on it, could you please provide an example of the case you are interested in. Or point out which of the tests on that page you are specifically interested in?

**Comment by Adriani90** [comment]
@Techieegirl I think I have seen a similar issue on some websites. Unfortunately the link you provided in the description does not work anymore. Could you please upload a new one? Thanks!

**Comment by Adriani90** [comment]
We do not have an update from the initial author since more than two years. Closing as abandoned. Please comment on it if you still have this issue and we can reopen it.
