### ISSUE TITLE
foobar 2000 crashes when skipping tracks in playlists

### ISSUE THREAD

**Issue by dave090679** [nvaccess/nvda#7722]
Hi guys,

When I skip between the tracks in a playlist, foobar2000 crashes and it's asking me to send a crash dump.

### Steps to reproduce:
1. load a m3u playlist or add a folder to an empty playlist.
2. play the first track of the list.
3A. skip between the tracks using the multimedia keys of your keyboard.
3B. select a random track of the playlist.

### Expected behavior:
every track should be played by foobar2000 as soon as you select them in the playlist.

### Actual behavior:
Foobar2000 doesn't start to play the track(s) I selected. 
foobar2000 displays the crash dialog box "foobar2000 has crashed". 

### System configuration:
NVDA version: master-14590,5efe71c8

NVDA Installed or portable: installed

Windows version: Windows 10 17-09 build 10.0.16299.19

Name and version of other software in use when reproducing the issue: foobar 2000 Version 1.3.16

### Other questions:

Does the issue still occur after restarting your PC? yes.

Have you tried any other versions of NVDA? 
the issue doesn't occur with master-14446 and below.
### notes:
1. The crash happens even with nvda add-ons diabled.
2. It doesn't occur when I play the "crash-causing" tracks solo (e.g. by pressing enter in the windows explorer to open the single mp3 files). 
3. it doesn't depend on the windows 10 design; I tried different designs and the issue still occurs.
4. It doesn't depend on different driver versions (I tried the windows staqndard high definition audio driver as well as the realtek high definition audio driver; the issue still occurs
5. it doesn't depend on the output mode in foobar; i tried directsound as well as windows audio session (event mode and push mode); the issue still occurs.
6A. the issue doesn't occur when nvda is not running.
6B. The issue doesn't occur when another Screen reader like Jaws is running

### Notes about the attachment
the attachment contains a foobar2000 crash dump as well as an nvda debug log. The log contains the following actions I did until the crash happened:
1. I started foobar2000
2. I skipped some tracks in the playlist.
The crash happens when foobar tries to play track 9 in the playlist. in other words: The crash occurs when I select track 9 from the list or when I'm using the multimedia keys to skip through the tracks and the playback reaches track 9. It doesn't occur when foobar plays track 8 and it switches to track 9 at the end of track 8. 
The attachment can be found at
[FOOBAR_CRAsh_2017-11-02.zip](https://github.com/nvaccess/nvda/files/1438591/FOOBAR_CRAsh_2017-11-02.zip)

happy testing/fixing

Dave

**Comment by Brian1Gaff** [comment]
Is this perhaps the same issue as in another ticket of it crashing on a 
playlist track 79 if played or randomly sometimes?
 I've yet to get it to happen here but my playlists are much shorter than 
the apparent critical length in the other ticket.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Mohamed00** [comment]
I can confirm this. Foobar crashes often when NVDA is running, and not when any other screen reader is running. Could this be related to the Foobar2000 app module?

**Comment by Mohamed00** [comment]
Until this issue gets resolved, here is a quick workaround. When you press enter on a track in a playlist, quickly minimize the Foobar2000 window before the track plays. This crash only seems to happen when the Foobar2000 window has focus. Moreover, it happens more often with streams than locally stored files.

**Comment by Brian1Gaff** [comment]
It did not used to do this, so unless its something that was changed or 
removed when the nvda service was removed,I'm at a bit of a loss. Its only 
happened to me once so far and unable to get it to happen again, but it does 
seem that it might be delay related in some cases.
 Weird, sorry I cannot be of much more help as I do not have large 
playlists.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by kayatli** [comment]
This issue occurs for me as well with the latest NVDA Master build and the latest version of Foobar2000. this happens on on a playlist of local files.

**Comment by leonardder** [comment]
[**@Mohamed00**](https://github.com/Mohamed00) commented on [11 Nov 2017, 10:32 CET](https://github.com/nvaccess/nvda/issues/7722#issuecomment-343652372 "2017-11-11T09:32:17Z - Replied by Github Reply Comments"):
> This issue has been fixed by #7737  and can be safely closed.

I edited #7737 in such a way that it will also close this issue as well as soon as the pr is merged into master.
