### ISSUE TITLE
Native driver for Optelec braille displays

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#7733]
Is it possible to start work on native driver for Optelec displays such as BC6 series?

Here are some benefits:
- many users use these displays (BC640/680, BC640 Comfort (USB and also emulate them with protocol converter attached to Alva Satellite or Tieman Voyager displays.
- It would be possible to use advanced braille features which are coming to NVDA.

Unfortunately I don't have enough skills to develop it but if I can help you on the other way, please tell me.

Thanks,

**Comment by leonardder** [comment]
CC @dkager, who also has such a display and has some decent programming skills. I will see whether I could get an old device myself.

I have to note though, that it would be very helpful to have the data protocol for these displays, especially to implement the converter and Comfort part.

**Comment by gregjozk** [comment]
Hi,

shell it help you if I sent you a protocol converter via postal service or DHL? my display is currently on a maintenance and repairment so I do not need it now.
If you guide or tech me I will also be glad to send you other materials to successfully develop a native driver for BC6 series.

regards, Jožef

**Comment by leonardder** [comment]
The most important thing is the protocol, so if you could assist in getting hold of that, that would be awesome.

**Comment by leonardder** [comment]
I might have time to work on this around christmas, but I don't have a protocol to work with, only a BC640, without the comfort part. Unless I have a protocol document, I probably have to work with what BRLTTY and some device monitoring tools will tell me.

**Comment by gregjozk** [comment]
Hello,

I contacted our distributer a month ago, but unfortunately I have not
got a document yet.

anyway thanks for your good work.

regards, Jožef

2017-12-18 19:21 GMT+01.00, Leonard de Ruijter <notifications@github.com>:

**Comment by leonardder** [comment]
I've had contact with @jcsteh and might be able to start with a native driver very shortly. @gregjozk, your testing would of course be greatly appreciated. I will start posting try builds here whenever they are available, probably within the first or second week of January.
