### ISSUE TITLE
Vbuf table navigation commands should exclude layout tables if "Report layout tables" is disabled

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#774]
**Reported by jteh on 2010-07-22 06:49**
In virtual buffers, even if "Report layout tables" is disabled, the table navigation commands do not exclude layout tables. This is extremely annoying in data tables containing layout tables in their cells, as the table navigation commands get "stuck" in the layout table, preventing you from navigating the data table.

Two things need to be done:
- Extend !VirtualBuffer._getTableCellCoords() so that it skips layout tables if includeLayoutTables is disabled.
  - This is quite tricky because table cells do not know whether they belong to a layout table, so you have to continue to search through the fields to find the table and check its layout-table attribute. In addition, you have to keep going back in case there is a data table above.
- Remove the forced temporary enabling of includeLayoutTables in !VirtualBuffer._tableMovementScriptHelper().

**Comment by leonardder** [comment]
This was fixed in NVDA 2017.3
