### ISSUE TITLE
NVDA does not recognise Java Swing UI elements

### ISSUE THREAD

**Issue by yassinmmoussa** [nvaccess/nvda#7753]
Steps to reproduce:

1. Create a new Java Project on Eclipse Neon
2. Initialize JFrame, add one Jbutton, one JLabel, one list and one text field
3. Set Accessibility Name and Description for all the above elements
4. Compile and run with NVDA running in the background
5. Notice that NVDA does not recognise the UI elements at all

Expected behavior:
NVDA should read out the name of the Button when you hover over it, at the very least, it should read out the name if you TAB into the button. It should also read out the text on the JLabel when you hover over it.

Actual behavior:
NVDA absolutely does not react to the Java application, except to read out its title when hovered over, and reacting to the minimise, maximise and close buttons. When tabbing into elements nothing at all happens, when hovering over elements nothing at all happens and ALT + arrow keys only says "blank".

System configuration:
NVDA version:
2017.3

NVDA Installed or portable:
Installed

Other information:
Software is running straight from eclipse.

Windows version:
Microsoft Windows 10 Home - Version	10.0.15063 Build 15063

Name and version of other software in use when reproducing the issue:
Eclipse version:
Neon.2 Release (4.6.2)

Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No, but tried re downloading and reinstalling

**Comment by dkager** [comment]
Did you enable the Java Access Bridge through Control Panel --> Ease of Access --> Use the computer without a display?

**Comment by yassinmmoussa** [comment]
Apparently not ^^
Thank you for the quick response and sorry for the inconvenience.
