### ISSUE TITLE
Why does Insert+F7 not work when focusing a text input?

### ISSUE THREAD

**Issue by jmuheim** [nvaccess/nvda#7763]
In both Firefox and IE, when focusing a text input, `Insert + F7` wants to turn on caret browsing - instead of displaying the elements list.

Is this a bug? Interestingly, for other keyboard shortcuts using `Insert`, this doesn't seem to be a problem, e.g. `Insert + N` always shows the NVDA menu, even when focusing a text input.

**Comment by leonardder** [comment]
Insert+f7 is a key which is specifically bound to browse mode. When you have focused an input field, focus mode is active, so browse mode specific keys, including insert+f7, aren't in use by NVDA.

**Comment by jmuheim** [comment]
That's exactly what I guessed.

But why is it different for e.g. `Insert + N`?
