### ISSUE TITLE
microsoft edge windows 10 17040

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#7766]
Hello. Starting with Build 17035
 NVDA does not move to the Favorites list in Microsoft Edge.
1. Open Edge
2. Open Favorites Ctrl + I
3. Click the down arrow to start navigating through the items.
Expected. The NVDA moves through the items. In fact, nothing happens. I tried to use narrator. There's no problem with that..
Version of Windows 1703 17040
nvda next-14617,ef52ddc4

**Comment by Adriani90** [comment]
I can navigate through the items with NVDA 2017.3 and Windows 10 Build 16299.64.

**Comment by gdata1** [comment]
As I wrote earlier. The problem came from building 17035

**Comment by josephsl** [comment]
Hi, looks like a focusing issue, as I can locate favorites via object navigation. Thanks.

**Comment by gdata1** [comment]
Hello. I'm also moving through object navigation.

**Comment by derekriemer** [comment]
gdata1 commented 15 days ago

> Hello. I'm also moving through object navigation.

Do you mean you cannot even access this while using object navigation?

**Comment by gdata1** [comment]
Hello. I can access the object navigation.

**Comment by josephsl** [comment]
Hi,

Resolved in build 17063. Please reopen if the problem surfaces again in a future build. Thanks.
