### ISSUE TITLE
NVDA not reading row state like selected or not selected when apply ENTER key

### ISSUE THREAD

**Issue by subbuj9** [nvaccess/nvda#7767]
Browser : Chrome
OS : Windows 10
Application Type : Web Application(Html5 AngularJS Jquery Bootstarp)

Using Enter key to highlighting the row and changing row background but nvda is not reading the row [index] selected/not selected.
We tried aria-selected attribute but this is not working.

below is the expectation
using tab to navigate to row/cell and apply enter key >> row 1 selected.

any help

Regards
Subbu

**Comment by PratikP1** [comment]
Can you provide an example that we could look at and test? Are you looking for NVDA and Chrome to behave in a similar manner to what it does in Gmail?

**Comment by subbuj9** [comment]
![accessibility_tbale_row_selected_issue](https://user-images.githubusercontent.com/19259779/33553537-2effaafe-d91f-11e7-8c44-bc36ce602150.png)

Please find the attached image.
Green color indicates >> row already selected
Yellow color indicates >> row need to be selected using Enter key.
   Expectation : on click on Enter key > NVDA should read like 'row 4 selected'

**Comment by ehollig** [comment]
@subbuj9, do you have a working example that we could look at and test? As most of the developers for NVDA are blind, attaching an image is not useful to replicate the issue.

**Comment by Adriani90** [comment]
@subbuj9 just a reminder, could you please provide a website example where we can test this issue? Thanks!

**Comment by Adriani90** [comment]
No update on this since years and we don't have a minimal test case. Closing as abandoned, but feel free to comment on it and we can reopen.
