### ISSUE TITLE
MS Access error when cancel is pressed in data sources wizard

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#777]
**Reported by briang1 on 2010-07-22 15:32**
See the log attached for details, but basically, when you launch Msaccess, you have choices, one of these is  blank data access page. If you go in here you are prompted for a file or other input  stream. Press  return and the wizard appears. If you hit the cancel button, the error is generated as attached.

**Comment by leonardder** [comment]
@brian1gaff: Could you provide a status update for this issue?

**Comment by Adriani90** [comment]
Is this still reproducible in MS Access?

**Comment by ehollig** [comment]
I am not that familiar with MS Access. @Brian1Gaff:, could you provide an update with MS Access 2016?

**Comment by Adriani90** [comment]
@Brian1Gaff this is the last reminder before closing this issue. Is this still reproducible for you? I cannot reproduce it in MS Access 2016, maybe you can reproduce it in older versions? Your answer is appreciated. Thanks.

**Comment by Adriani90** [comment]
I am closing this for now. Please comment on it if you are still having this problem and we can reopen the discussion. Thanks.
