### ISSUE TITLE
GUI: About dialog is rendered in English

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#7770]
Hi,

A critical showstopper found: when opening About dialog in languages other than English, content is displayed in English.

STR:

1. Switch to a language other than English (NVDA menu/Preferences/General).
2. Restart NVDA.
3. Open About dialog.

Expected: content is displayed in the new language.
Actual: English is displayed.
Severity: critical.
Affects: NVDA 2017.4 RC, master, next snapshots.

Thanks.

**Comment by k-kolev1985** [comment]
Yes, I can definitely reproduce this. But why it happened is a mystery to me...

**Comment by josephsl** [comment]
Hi,

After testing various binary snapshot builds, it appears Python 2.7.14 upgrade from the build server is the likely culprit.

Thanks.

**Comment by zstanecic** [comment]
well, how we know that,

do you have an evidence?


W dniu 17.11.2017 o 15:20, Joseph Lee pisze:

**Comment by florianionascu7** [comment]
Hello, I also confirm this bug. I hope it'll be fixed in 2017.4

**Comment by josephsl** [comment]
Hi, the last master that did work was 14539, and that was with Python 2.7.13. Starting from 14549, it started using Python 2.7.14. At the same time, next snapshots began showing this problem, with the last next snapshot with no problems being 14536. This leads me to believe that something that was committed around October 18th might be to blame, and we cannot leave out Python 2.7.14. Thanks.

**Comment by leonardder** [comment]
[**@josephsl**](https://github.com/josephsl) commented on [17 nov. 2017 15:20 CET](https://github.com/nvaccess/nvda/issues/7770#issuecomment-345255871 "2017-11-17T14:20:11Z - Replied by Github Reply Comments"):
> After testing various binary snapshot builds, it appears Python 2.7.14 upgrade from the build server is the likely culprit.

I tend to disagree with this finding. I"m running Python 2.7.13 on my local system, and when running from source, the about dialog is also showing up in English. Note that the title of the dialog is properly translated.

**Comment by josephsl** [comment]
Hi,

In that case, Python is not to blame.

Further testing shows that the new likely culprit might be #7649, as prior to that, there was no problem with this dialog.

CC @MichaelDCurran

**Comment by leonardder** [comment]
Comfirmed.

I did a git checkout 1fcc7fe, and the issue did occur. After that, i did a git checkout head~, and the translation showed up correctly. Assuming this is the right way to test this, of course.

**Comment by leonardder** [comment]
@michaeldcurran: It could have to do with the move of the localisation initialisation. Note that all translatable strings in versionInfo show up as untranslated. This suggest versionInfo is imported without localisation being initialized properly. See logHandler around line 221:

versionInfo must be imported after the language is set. Otherwise, strings won't be in the correct language.
Therefore, don't import versionInfo if it hasn't already been imported.

May be use a similar trick for the RemoteHandler?

**Comment by zahra21** [comment]
hello.
i should say that i dont have this problem using nvda 2017.3 (which is built with python 2.7.13!
hope that help, God bless you all.

**Comment by nvdaes** [comment]
Hi, I can't reproduce this exactly: For me, the info is also displayed in Spanish, even if I switch to catalon, French or Italian. Spanish is the language I use for Windows.
Cheers

**Comment by florianionascu7** [comment]
Well, what NVDA version are you using?

**Comment by nvdaes** [comment]
Hi, I'm using NVDA 2017.4rc1. I see that, in the General dialog of preferences submenu, languages of the combo box are shown in Spanish too testing with NVDA set to English.
I've tested with the Python console copying to the clipboard the aboutMessage of versionInfo and is copied in Spanish too.

**Comment by Brian1Gaff** [comment]
The .ini file says windows for language, I notice.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment]
No its definitely around the time noted, and I'm thinking Unicode for some 
reason.
Might be barking up the wrong lamp post dunno.
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Elshara** [comment]
I also can confirm this behavior.

**Comment by nvdaes** [comment]
Hi, perhaps the title of the issue should be changed to: About dialog and language names in General settings are displayed in the default language for Windows.
I've changed my language to en_us and now these are shown in English.

Cheers

**Comment by florianionascu7** [comment]
We're talking about the About dialog, not about the language names of General Settings Dialog. If you're switching to another language than English and open the About dialog from Help submenu, you'll see that it is shown in English, not in the language you've set.

**Comment by nvdaes** [comment]
florianionascu7 commented 
> We're talking about the About dialog, not about the language names of General Settings Dialog. 

Maybe the two ones are caused by a common issue.

Cheers

**Comment by michaelDCurran** [comment]
Please test the following try build:
https://ci.appveyor.com/api/buildjobs/xhlj455yfuiv2jjr/artifacts/output%2Fnvda_snapshot_try-i7770-14631%2C0bfa4738.exe

**Comment by josephsl** [comment]
Hi, resolved, keeping an eye out for further confirmations. Thanks.

**Comment by nvdaes** [comment]
Hi, fixed also the issue reported by me related to About dialog, not exactly described as Joseph did.
Resolved using the exe file, not from source.
The language names are displayed in the default language for Windows, but I think it's not critical.
Thanks

**Comment by florianionascu7** [comment]
Hello, I can also confirm that this bug has been succesfully fixed.

**Comment by k-kolev1985** [comment]
Yes, I can confirm that it is fixed in the test build.

**Comment by Brian1Gaff** [comment]
Yes the about  rendered in French after changing nvda to French and 
restarting and looking at about again.
 Still having non- restart issues  though on updates.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Elshara** [comment]
Yes also resolved for me. thanks!

**Comment by florianionascu7** [comment]
I think this issue can be closed now.

**Comment by josephsl** [comment]
Done, thanks.
