### ISSUE TITLE
Windows 10: NVDA does not output anything if Laptop lid closed on the Logon Screen

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#7774]
When booting a Windows 10 laptop with the lid closed, I've noticed that NVDA does not output anything when either tabbing around the window or when using Object Navigation. This works without issue if the lid is raised before the Logon screen appears. This can make it difficult to navigate around if you lose focus on which element has focus.

**Comment by PratikP1** [comment]
Is the laptop lid set to put the machine into either sleep mode or hibernation when shut? How is the machine booted with the lid closed?

**Comment by elliott94** [comment]
The laptop is set to do nothing when the lid is closed. The laptop is docked with a docking station, which has its own power button which boots the machine.

**Comment by PratikP1** [comment]
I have a similar set up on a Lenovo laptop. I Just tested it by disabling sleep mode when lid is shut. I wasn’t able to replicate the behavior you described. Would it be possible to get a log of this behavior?

**Comment by Brian1Gaff** [comment]
Is this not a duplicate of another similar issue. I'm sure I noticed one when  looking for something else earlier.


bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
This message sent from a Windows XP machine!
  ----- 
  Sorry for that swear  word.

**Comment by Brian1Gaff** [comment]
When this machine is in its docking station could it perhaps switch to an 
external sound card perhaps when lid is shut?

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by josephsl** [comment]
Hi, no, not at all. It is likely that an overlay app is being used, which causes issues like this (I had to deal with it a few months ago when I first got my ThinkPad). Thanks.

**Comment by ehollig** [comment]
This is probably related to #7746

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years. If this issue is still occuring, please comment on it and we can reopen.
Closing as abandoned.
