### ISSUE TITLE
with the native implementation on the braille wave display, the 9th cursor routing key doesn’t work

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#7781]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. press insert +f1
> 2. press nineth routing key of the braille wave 2.10 firmware display 
> 3. notice tat it doesn’t work, bit it’s pressed, but not recognized with it.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> routing should work.

### Actual behavior:
> happens nothing.

### System configuration:
NVDA version:
> 2017.4 RC1

NVDA Installed or portable:
installed
Other information:
> tested the older com implementation. routing worked there. 

Windows version:
> 16299.60 1709

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> 2017.3 with the older com implementation cursor routing key worked

**Comment by josephsl** [comment]
CC @LeonardDer

**Comment by bdorer** [comment]
hmm, V2.10 is the last Firmware Version with 2 firmware memory banks. 
May this versions aren't working as Braillino?

The last Braille Wave firmware is 3.4.2 and needs 4 firmware banks. I 
don't know wheather this affects the driver somehow.

Am 19.11.2017 um 21:27 schrieb zstanecic:

**Comment by zstanecic** [comment]
well, i don’t think so, because all other functions work properly with 
the new protocol.

older com driver doesn’t have this problem

try to test it yourself with v2 bank.

Basically, i cannot upgrade to the 4th bank as i don’t have bluetooth


W dniu 19.11.2017 o 23:15, Bernd Dorer pisze:

**Comment by zstanecic** [comment]
OOps,

my fault... i neeeded to clean the area between the buttons. it was not 
the fault of the nvda itself


W dniu 19.11.2017 o 23:15, Bernd Dorer pisze:

**Comment by zstanecic** [comment]
you can close it, as i saw the problem.

the problem was not the software.


W dniu 19.11.2017 o 23:15, Bernd Dorer pisze:
