### ISSUE TITLE
emulate some tactile screen gestures on mouse pad

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7786]
For some time ago this request was made, however I did not locate it.
When this request was made one of the technical problems pointed out is that there are several models of mouse pads and there is a standardization of the drivers.
Now I learned that in windows 10 it is possible to enable a mouse driver called precision mouse, which would be a driver from Microsoft itself that replaces the manufacturer's mouse driver.
Would it now be possible to support this feature for this precision mouse?
Thank you very much.

**Comment by josephsl** [comment]
Hi, no, as these ads will use standardized gestures for various Windows 10 commands. Thanks.

**Comment by fernando-jose-silva** [comment]
OK thank you.

**Comment by ehollig** [comment]
Sounds like, from https://github.com/nvaccess/nvda/issues/7786#issuecomment-345760251, closing as cantfix
