### ISSUE TITLE
When using PIN at Windows 10 logon, the last digit is read aloud.

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#7792]
In Windows 10 (Fall creators update), using a pin to log in, while typing, NVDA reads "dot" for each digit if speak typed characters is enabled.  When the last digit is entered, however, NVDA reads it aloud.

I suspect this is related to Windows automatically starting to log in as soon as the last digit is entered.

If using a password (which doesn't have a set length), all characters are read as "dot", and with a pin, it is always only the last digit.

Note: This is different to an earlier issue (which I believe has been resolved) where depending on how quickly things loaded, NVDA could sometimes read the password as you typed it.  In that case, it read all characters typed.  This is a different issue as it only affects the last digit typed.

**Comment by michaelDCurran** [comment]
Now duplicate of #7908 which has a PR referencing it.
