### ISSUE TITLE
Fix invalid lines in file locale\vi\symbols.dic for 2017.4 release

### ISSUE THREAD

**Issue by tmthywynn8** [nvaccess/nvda#7793]
### Steps to reproduce:
1. Switch to a Vietnamese voice (e.g. eSpeak NG's Vietnamese (Northern) voice), and make sure that "Trust voice's language when processing characters and symbols" is checked.
2. Open NVDA's log -- NVDA menu>Tools>View log.
3. You will find entries that start out:
`WARNING - characterProcessing.SpeechSymbols.load ([timestamp):
Invalid line in file locale\vi\symbols.dic: ...`

### Expected behavior:
There should not be any errors in the default symbols file for this locale.

### Actual behavior:
There are errors that can be easily fixed (using values inherited from English's locale).

### System configuration:
NVDA version: master-14638,e2e76d08
NVDA Installed or portable: Installed

Other information:
I've attached a fixed version of the symbols file, using inherited values from the English locale where necessary.

### Steps to reproduce:
1. Switch to a Vietnamese voice (e.g. eSpeak NG's Vietnamese (Northern) voice), and make sure that "Trust voice's language when processing characters and symbols" is checked.
2. Open NVDA's log -- NVDA menu>Tools>View log.
3. You will find entries that start out:
`WARNING - characterProcessing.SpeechSymbols.load ([timestamp):
Invalid line in file locale\vi\symbols.dic: ...`

### Expected behavior:
There should not be any errors in the default symbols file for this locale.

### Actual behavior:
There are errors that can be easily fixed (using values inherited from English's locale).

### System configuration:
NVDA version: master-14638,e2e76d08
NVDA Installed or portable: Installed

Other information:
I've attached [a fixed version of the symbols file](https://github.com/nvaccess/nvda/files/1497764/symbols-vi.dic.txt), using inherited values from the English locale where necessary.

**Comment by ehollig** [comment]
CC @michaelDCurran

**Comment by josephsl** [comment]
Hi, I’d call this off until 2018.1. Thanks.,

**Comment by tmthywynn8** [comment]
I, of course, defer to your judgment. I figure it could be an easy fix because there are no translation changes, just errors like too many tabs, missing values, etc.

Timothy

**Comment by josephsl** [comment]
Understood. Go ahead and commit the changes via our translations system please. If @MichaelDCurran agrees, I suggest putting 2018.1 tag or close it as external fix. Thanks.

**Comment by tmthywynn8** [comment]
I assume that the official way of committing such changes is still by following [this guide](https://github.com/nvaccess/nvda/wiki/TranslatingUsingAutomaticProcess)? Or should we be contacting the maintainer of a given translation, in this case Vietnamese, when bugs such as these are found?

In other words, should I be [creating new issues](https://github.com/nvaccess/nvda/issues/new) when localization issues are found? Or are localization concerns handled only by going through the process of becoming a translator? Either way, will be going through the process linked above to commit this fix to the Vietnamese translation for the next release.

**Comment by josephsl** [comment]
Hi, ideally, current translators should be informed. Thanks.

**Comment by tmthywynn8** [comment]
In that case, this ticket should be closed, as I have started the process of contacting the current maintainer.

**Comment by ehollig** [comment]
Closing as requested in https://github.com/nvaccess/nvda/issues/7793#issuecomment-347283868
