### ISSUE TITLE
NVDA follows default audio device changes even when Microsoft Sound Mapper isn't selected

### ISSUE THREAD

**Issue by jscholes** [nvaccess/nvda#7797]
### Steps to reproduce:

1. Open the Synthesizer settings dialog.
2. Set the output device to a specific output e.g. headphones or an external soundcard.
3. Open sound settings from Control Panel and change the default playback device to one which is different from that selected for NVDA, e.g. speakers instead of headphones.

### Expected behavior:

NVDA's speech and tones continue to play through the audio device selected in the Synthesizer settings dialog.

### Actual behavior:

NVDA's speech and sounds begin playing back through the newly selected default playback device.

### System configuration:

NVDA next-14660,06727657 (installed on Windows 6.1.7601 service pack 1 workstation)

**Comment by josephsl** [comment]
Hi,

For reference, the discussion that prompted this and #7798 is:
https://nvda-addons.groups.io/g/nvda-addons/topic/beeps_and_profil_switching/6518910?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,6518910

In this case, contrary to suggestions from the linked discussion, extension points won't work, so we need to listen to a message or something to respond to changes in devices. Thanks.

**Comment by feerrenrut** [comment]
Giving this a priority 3 to get fixed, while its annoying, it seems there is a workaround. It also seems unlikely this is going to stop someone from being able to use NVDA effectively.

**Comment by Adriani90** [comment]
Actually I cannot reproduce this issue with speeck on Windows 10 with NVDA 2019.2. Only tones seem to play on default device but speech follows the correct output device.

@jscholes can you confirm?

**Comment by lbk2907** [comment]
I also have facing the same issue. Actually this already happend for a
long time ago.

**Comment by Adriani90** [comment]
Do you mean only tones? Or is it happening with both speech and tones?

 

 

Von: lbk2907 <notifications@github.com> 
Gesendet: Freitag, 23. August 2019 00:25
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] NVDA follows default audio device changes even when Microsoft Sound Mapper isn't selected (#7797)

 

I also have facing the same issue. Actually this already happend for a
long time ago.

**Comment by idzik1972** [comment]
Hi,
I experience a similar problem with two latest releases (2020.1 and 2020.2) on Windows 10 Pro (German version), while behaviour on Windows 7 Pro (German as well) is correct.

On another Windows 10 Pro PC, I'm experiencing crashes while trying to apply changes to sound card. Log and dump attached.
[nvda-old.log](https://github.com/nvaccess/nvda/files/5168337/nvda-old.log)
[nvda_crash.zip](https://github.com/nvaccess/nvda/files/5168339/nvda_crash.zip)

**Comment by Adriani90** [comment]
@jscholes, @lbk2907, @idzik1972 could you please test with the last NVDA alpha version if this issue still occurs? Please make sure WASAPI is enabled in NVDA advanced settings.

As far as I understand there is a solution already provided for this during the last weeks so it should work as expected now.

**Comment by jcsteh** [comment]
No response in over a year and this should be resolved by WASAPI. Closing. Please reopen if the problem persists.
