### ISSUE TITLE
None of the keyboard hotkeys work on latest Firefox version

### ISSUE THREAD

**Issue by chavab1** [nvaccess/nvda#7806]
This is my first time using NVDA and I can't get it work like expected. First off, I've read the documentation and viewed videos with introduction and tutorials on how to use the screen reader. I've downloaded the product and and I'm running it. I didn't install it yet because I want to makes sure it works as expected. I followed the instructions on this video [https://www.youtube.com/watch?v=Vx1vSd5uYS8]. I changed my NVDA key to be CapsLock and turned on the Speech Viewer option. The reader is working as I can hear and see the content in the Speech Viewer tab. However, when I try to go over the items in the Quick Reference guide I can't get any of them to work. I have it on Browse mode. If I type 'h' the screen reader just says 'h' as oppose to going to the next heading. If I type 'l' to go to next list item the screen reader just says 'l'.

I'm using Firefox 57.0 on Windows 10 with the latest version of NVDA.

Thanx

**Comment by ehollig** [comment]
Hello @chavab1 
Sounds like you are in focus mode when you open Firefox. If you could, go into the Browse mode settings in Preferences, or by pressing NVDA+CtRL+B and disable the option for "Audio indication of focus and browse modes".
Now, when you open Firefox, NVDA will announce through speech which state it is in, focus/browse mode. To toggle between the two, you can press NVDA+Space. When NVDA is in browse mode, the navigational quick keys should work.
If this is your first time using NVDA, you may be interested in joining the [NVDA Users email list](https://nvda.groups.io/g/nvda). There are a lot of users on that list that would be happy to assist with any questions. To subscribe, send a blank email to [nvda+subscribe@nvda.groups.io](nvda+subscribe@nvda.groups.io).

**Comment by chavab1** [comment]
Hi Ethan, thank you for your quick reply.
I read through a bunch of documentation and also the quick reference guide. I figured out the Focus and Browse mode. And when I enabled the Speech Viewer option I am able to tell when I'm either in Focus or Browse mode. I'm also able to toggle between them using NVDA+Space. However, even though I'm in Browse mode I still can't use the Keyboard shortcuts I listed. I think it's a compatibility issue because I just now tried on Microsoft Edge and it works as intended. All the settings are the same and it works on one but not the other.
Any suggestions??
Thanx

**Comment by ehollig** [comment]
Another thing you can try:
1. Go to [https:/www.google.com](https:/www.google.com) in Firefox.
2. You will be placed in the search box in focus mode. Press NVDA+space to go to browse mode.
3. Try pressing B or shift+B for next or prior button.

If you are still experiencing issues with Firefox 57, NvAccess has recommended to use Firefox ESR in the [NvAccess In-Process](https://www.nvaccess.org/post/in-process-halloween-2017-edition/). You can [download Firefox ESR here](https://www.mozilla.org/en-US/firefox/organizations/all/).

**Comment by chavab1** [comment]
Yeah, I just tried what you suggested and I'm still getting the same results. I'm thinking it is a browser issue since it does work on Edge.
It's OK, as long as it's working on Edge. I just wanted to make it wasn't a setting I was missing.

Thank you for your help

**Comment by chavab1** [comment]
Must be a browser issue, using the latest version of Firefox, 57.0. Works correctly on Microsoft Edge.

Thank you for your help

**Comment by Brian1Gaff** [comment]
I would heartily suggest this right now, as I never did manage to get 57 to 
work on my windows 7 machine at all.
 Brian
