### ISSUE TITLE
Excel: Tab name not read in dialog boxes when navigating using TAB key

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#7808]
In Excel (2016 at least):
1. Press control+1 to open the cell format dialog.
2. The focus starts on the current tab (Number by default).  Press TAB once to move to the first control;
 NVDA reads this.
3. Press SHIFT+TAB to move back to the tab name.  Nothing is reported.

The one exception I've found is in this dialog, if you move to the font tab, press TAB once to move to the font name (an edit box), then SHIFT+TAB to move from the edit box to the tab name, it reads.  I also found this occurs if you are in the find dialog (control+f) and press shift+tab to move from the "find what" edit box to the tab name.  So it seems moving from an edit box works but moving from other controls doesn't?

If the left or right arrows are pressed while the focus is on the tab name, the tab will change and NVDA will report the new tab.  Additionally, to change tabs, you can instead press control+tab or control+shift+tab and NVDA reports this.

Using Office 2016 and NVDA 2017.3 / 2017.4rc3.

**Comment by Adriani90** [comment]
This is not occuring anymore in NVDA 2019.1.1. Closing as works for me.
