### ISSUE TITLE
nvda is not reading the auto completion of addresses option in outlook 2016

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7811]
## Steps to reproduce:

Open Outlook.
opens a new message.
in the field to start typing an existing e-mail address in your address book.

### Expected behavior:
nvda should read the e-mail address suggested by Outlook.

### Actual behavior:
nvda reads blank when the address suggestion is displayed.

### System configuration:
NVDA version:
> Example: next-14675NVDA Installed or portable:
instaled
Other information:

Windows version:
> Example: Windows 10 Version 1709 Build 16299.64

Name and version of other software in use when reproducing the issue:
outlook 16.0.8625.2032
### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result

I believe this is a regret, because these suggestions were read earlier, but I do not know how to start from which version stopped reading, did not send e-mail from this machine for some time.

**Comment by josephsl** [comment]
Hi, confirmed. CC @MichaelDCurran

**Comment by Brian1Gaff** [comment]
We just had someone get so fed up with Office 2016 on the user list, he 
uninstalled it and then ended up with  very little that worked any more even 
though he reinstalled office 2010, I suspect that old Microsoft bug on the 
dlls. That is a real pain for many.

Brian

**Comment by feerrenrut** [comment]
Unfortunately there is something quite wrong with my Outlook installation, so I am unable to verify this at the moment, and some of the following information may be a little uncertain.

Before giving this a priority, it would help to know.
Is there a valid workaround? Let me know if the following works for you:
- Activate the "To" button
- Use the address book pop up to find and select a contact.

Is this indeed a regression. Does this occur in 2017.1? or 2016.1?

**Comment by josephsl** [comment]
Hi, for me, I don’t know what happened, but auto-complete is working again. Thanks.

**Comment by Brian1Gaff** [comment]
Just to chip in, when this issue occurs do context menus speak? I've had 
issues in many programs with these two functions going away and coming back 
in windows 7, though I do not use Outlook myself.
 Brian

**Comment by PratikP1** [comment]
I can’t say how long it takes for Outlook to provide suggestions, but as of this morning, suggestions seem to be reading correctly after three letters typed for the name or email address in question. This is in Outlook 2016.

**Comment by fernando-jose-silva** [comment]
Thank you very much.
For I activating the popup button to it is possible to read the contacts.
I have now tested in outlook 2013 and the auto complete has been read, I will do tests in 2016 and return.

**Comment by fernando-jose-silva** [comment]
Very strange, with me too now it worked again.
The only thing that changed was the nvda that when the call was opened it was the next 14675 and now it's the next 14693,

**Comment by ehollig** [comment]
Thank you for reporting back @fernando-jose-silva. I will close this as worksforme
