### ISSUE TITLE
Browse mode does not work properly in Internet Explorer on an example website

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7816]
### Steps to reproduce:
1. Open Internet Explorer
2. Go to www.ixquick.de
3. Type something in the search field
4. Navigate in browse mode by pressing h to a search result and try to activate it
5. Navigate by pressing e back to the search field and press enter to activate focus mode

### Expected behavior:
NVDA should alow me to activate those things like on most websites

### Actual behavior:
NVDA does not perform an action. Neither in browse mode, nor in the list of elements. The only way to activate the links is to go into focus mode and navigate by pressing tab to the link and then enter.

### System configuration:
NVDA version:
NVDA 2017.3

NVDA Installed or portable:
Both

Other information:

Windows version:
Win10 Fall Creators update

Name and version of other software in use when reproducing the issue:
Internet explorer 11

### Other questions:

Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
NVDA 2017.4 RC3

**Comment by Brian1Gaff** [comment]
I wonder have you tried this in Edge and Firefox 52 ESR?
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
This message sent from a Windows XP machine!
  ----- Original Message ----- 
  From: Adriani90 
  To: nvaccess/nvda 
  Cc: Subscribed 
  Sent: Saturday, December 02, 2017 1:30 PM
  Subject: [nvaccess/nvda] Browse mode does not work properly in Internet Explorer on an example website (#7816)


  Steps to reproduce:
    1.. Open Internet Explorer 
    2.. Go to www.ixquick.de 
    3.. Type something in the search field 
    4.. Navigate in browse mode by pressing h to a search result and try to activate it 
    5.. Navigate by pressing e back to the search field and press enter to activate focus mode 
  Expected behavior:
  NVDA should alow me to activate those things like on most websites

  Actual behavior:
  NVDA does not perform an action. Neither in browse mode, nor in the list of elements. The only way to activate the links is to go into focus mode and navigate by pressing tab to the link and then enter.

  System configuration:
  NVDA version:
  NVDA 2017.3

  NVDA Installed or portable:
  Both

  Other information:

  Windows version:
  Win10 Fall Creators update

  Name and version of other software in use when reproducing the issue:
  Internet explorer 11

  Other questions:
  Does the issue still occur after restarting your PC?
  Yes
  Have you tried any other versions of NVDA?
  NVDA 2017.4 RC3

**Comment by Adriani90** [comment]
In Firefox and crome works well.


Von meinem iPhone gesendet

**Comment by Brian1Gaff** [comment]
Right, been looking at this one. Indeed my 64 bit version of IE11 on that 
page and indeed on the startpage search engine also fails to activate the 
links in IE at all. It has a very complex source, including a lot of stuff 
about apple touch stuff and bits written in jason??

My guess is that IE is just not being supported by the site. I tested it on 
google and found no issues. It would be interesting to see if any other 
sites are showing this, as you say, Firefox is fine, so something is 
upsetting IE11. They are a little naughty, as if they are not going to 
support IE surely they should say it on the pages and allow you to go 
somewhere else or use a page that does work. Interestingly some of the links 
on the main page do work, but the links to the results do not.

If it is IE its hard to see what nvda could do.  I wonder if touch works? As 
I'm using windows 7 I cannot tell.
 Brian

**Comment by ehollig** [comment]
I tested the above STR in Firefox 57 and Edge and was able to activate the links of a search result. I was not able to activate the search result links in Internet Explorer 11. Marking this as IE specific.

**Comment by Brian1Gaff** [comment]
Hi, could you pelease also try this on the  startpage search engine in IE11 
and on Google.
 If as I suspect it fails in startpage, as it is a sister site to the one 
you aare using, then you can report this to them. I did this yesterday and 
got the following email
Sorry if this is formatted badly.
From
support@startpage.com

Thank you for your email and interest in StartPage.
Also, thanks for informing us about this problem. =

Could you give me some additional information to help me troubleshoot the=
 issue?

-URL you are using to access StartPage =

-Operating system being used =

-Do you have any add-ons/extensions installed that could interfere with S=
tartPage's behavior?  If so, could you disable these to see if this solve=
s the issue? =

-Explanation of specific steps taken and results (including any error mes=
sages)
-Screenshot(s) of issue

Thanks! =


Best regards,
Damayanthi J.
StartPage.com

http://www.facebook.com/startpagesearch
http://twitter.com/startpagesearch
_________________________________________________________________________=
_______

**Comment by Brian1Gaff** [comment]
I see by looking at some logs that there are loads of warnings of problems 
in nvda during any page accessed, but if you can try some logs in debug your 
end and attach them with some nvda/f1 bits here and there it would probably 
be easier for the devs to figure out why google seems to work and start page 
does not in ie 11 64 bit. I did have a look but became so confused I decided 
to let somebody  ask what they wanted if they could not get the effect 
instead. In the mean time I'll continue using firefox to save my sanity.

**Comment by Adriani90** [comment]
On startpage I have the same issue. On google everything is fine. Here are three log files. The one for startpage shows lots of comerrors when NVDA tries to build the relation to focus in browse mode. That means every time when I press any key in browse mode, a comerror is being generated. The other log file for startpage shows how NVDA handles elements when navigating in focus mode. Almost everthing is ok, those errors do not impact user experience in focus mode.

The third log file shows how NVDA should work in browse mode, I have used google for this.

Hope it helps
[nvda.log](https://github.com/nvaccess/nvda/files/1527214/nvda.log)
[nvda_Focus mode on Startpage.log](https://github.com/nvaccess/nvda/files/1527215/nvda_Focus.mode.on.Startpage.log)
[NVDA on a well working webpage.log](https://github.com/nvaccess/nvda/files/1527217/NVDA.on.a.well.working.webpage.log)

**Comment by Brian1Gaff** [comment]
I have had another email from startpage, so they do know about it, so might 
be worth talking to them to see if between you somebody can fix it. They 
seem quite open to sufggestion.
 Brian

**Comment by Adriani90** [comment]
Here is the coresponding developer info for the search edit field after conducting a search and wanting to activate the edit field again:


```
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (11:12:21):
Developer info for navigator object:
name: u'StartPage by Ixquick Web Suchen'
role: ROLE_DOCUMENT
states: STATE_READONLY, STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionBodyMSHTMLIAccessible object at 0x053521D0>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionBodyMSHTMLIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithoutAutoSelectDetection'>, <class 'editableText.EditableTextWithoutAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.MSHTML.Body'>, <class 'NVDAObjects.IAccessible.MSHTML.MSHTML'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (0, 85, 1666, 926)
value: ''
appModule: <'appModuleHandler' (appName u'iexplore', process ID 4880) at address 5250090>
appModule.productName: u'Internet Explorer'
appModule.productVersion: u'11.00.9600.16384'
TextInfo: <class 'NVDAObjects.IAccessible.MSHTML.MSHTMLTextInfo'>
windowHandle: 198112
windowClassName: u'Internet Explorer_Server'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 6940
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0xac7b5d0 at 559d440>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=198112, objectID=36, childID=0
IAccessible accName: u'StartPage by Ixquick Web Suchen'
IAccessible accRole: ROLE_SYSTEM_PANE
IAccessible accState: STATE_SYSTEM_READONLY, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048644)
IAccessible accDescription: exception: (-2147467263, 'Nicht implementiert', (None, None, None, 0, None))
IAccessible accValue: u'https://www.ixquick.de/do/search'
MSHTML node has ancestor IAccessible: False
MSHTML nodeName: u'BODY'
```

**Comment by Adriani90** [comment]
I wonder why NVDA interprets this object as being read only.

**Comment by Adriani90** [comment]
Closing because support for ixquick ended in April 2018. it compeletely merged to starpage which is fully accessible and it works well in every browser.
