### ISSUE TITLE
Firefox version 57.0 Issue: nothing is read by NVDA when we change value of select(drop-down)  inside iframe using arrow keys.

### ISSUE THREAD

**Issue by SandeepVerma10** [nvaccess/nvda#7819]
this issue replicates for any select (drop-down) control.
> Example:
 1. Open Firefox
 2. Browse to https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select
 3. change value of dropdown using arrow keys.
 4. NVDA reads nothing.

NVDA supports this in previous version of Firefox. this issue replicates only for **Firefox version 57.0**

**Comment by jcsteh** [comment]
Confirmed, though this only applies to selects in an iframe. Selects outside of an iframe work as expected. Filed [Mozilla bug 1473234](https://bugzilla.mozilla.org/show_bug.cgi?id=1473234), as this needs to be fixed in Firefox.

**Comment by jcsteh** [comment]
Fix now available in Nightly and will be in Firefox 68. I may request uplift to 67 after this has baked on Nightly for a bit, but I'm not sure yet; the patch is not trivial.
