### ISSUE TITLE
NVDA reads irrelevant text when we set focus from one i-frame to another for the first time.

### ISSUE THREAD

**Issue by SandeepVerma10** [nvaccess/nvda#7820]
NVDA remembers the last focus set in the page. When the focus is set again inside the page, it tries to set focus on the last remembered focused element.

please provide any solution for this.
 it is confusing for disable people, because it is not easy for them to diffrentiate where the actual focus is.

**Comment by Brian1Gaff** [comment]
I think for now as mentioned in In Process blog and elsewhere the advice to 
use Firefox 52 ESR, particularly for those using nvda in a production 
environment has to be the way to go here, until the new Firefox engine has 
been sorted out and NVDA learns of ways on how to interact with it to the 
standard it did in the old version.
 Brian

**Comment by fernando-jose-silva** [comment]
I would respectfully disagree with this proposed functionality.
In my day to day work it is very good that nvda remembers the focus of where it was.
In my work I have a page with a large sequence of links, I have to open each link of these, and then I press backspace or alt + left arrow and it is very good that nvda is on the last link I opened, so I do not have to scroll through the entire page again for the link.
Regarding firefox 57 what I have to complain about is that the focus is not always on the last link I visited when I press alt + left arrow.
If there is an option for nvda not to remember the focus of the visited page, it would vote for this behavior to be configured.

**Comment by feerrenrut** [comment]
@SandeepVerma10 Please can you amend the description of this issue to include an example (minimal) test case, and steps to reproduce the behaviour (including keys used to navigate etc). Please also include the output you actually got from NVDA (speech viewer is handy to allow you to copy this) and the output you expected to get. Please also specify the web browser you are using, and the version of NVDA.
