### ISSUE TITLE
NVDA is reading full table data when mouse over on header cells

### ISSUE THREAD

**Issue by subbuj9** [nvaccess/nvda#7821]
OS : windows 10
Browser : chrome

![image](https://user-images.githubusercontent.com/19259779/33553765-fc8f8d90-d91f-11e7-8a91-f48692816ac7.png)

when mouse hover on the header cell like 'Name' NVDA is reading full table data.

Regards
Subba Rao

**Comment by Qchristensen** [comment]
Hi Subba,

Please be aware that many of the developers reading this will not be able to see your image.  In any case, do you have a public URL we can replicate this at, please?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years. I am closing as abandoned.
