### ISSUE TITLE
Trouble Building from Source

### ISSUE THREAD

**Issue by philiptkd** [nvaccess/nvda#7826]
Hey guys,

I cloned this repository with the "--recursive" tag, but I still am missing some dependencies, and I don't know where to get them.

Right now, I'm trying to track down the "comInterfaces.tom" module.

Attached is my nvda.log file that's created after I run nvda.pyw.
Any insight?

[nvda.log](https://github.com/nvaccess/nvda/files/1528509/nvda.log)

**Comment by leonardder** [comment]
Did you execute scons source and did that complete correctly?

**Comment by philiptkd** [comment]
Apparently I hadn't!
It works now.
Thanks!
