### ISSUE TITLE
Moving forward then back does not result in the same text in Edge on github website.

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7838]
### Steps to reproduce:
1. Be sure that "use screen layout where supported" is deactivated in NVDA's browse settings
2. Open edge
3. Go to https://github.com/nvaccess/nvda
4. If you are logged in, please log out
5. Press e to go to search this repository
6. Press down arrow multiple times
7. Press shift + e to return to the edit field
8. Press h to go to the next heading
9. Press up arrow multiple times

### Expected behavior:
When doing steps 1 to 6, following should be reported:
Sign in or 
Sign up
You must be signed in to watch a repository
104 users are watching this repository
You must be signed in to star a repository
390 users starred this repository
You must be signed in to fork a repository
169 users forked this repository

If you do steps 7 to 9, the same should be reported but in inverse order.

### Actual behavior:
NVDA reports "ign in" and "sign out" as they are showed on the screen, so even though screen layout is deactivated, NVDA does not split the links in two lines. When pressing down arrow and up arrow to read the line again, sign in and sign out are being ignored.

When doing steps 7 to 9, NVDA skips following:
104 users are watching this repository
390 users starred this repository
169 users forked this repository

Instead, NVDA reads just following:
You must be signed in to watch a repository
You must be signed in to star a repository
You must be signed in to fork a repository
and skips sign in and sign out. 

I tried to select the lines and copy them in MS word. Following came to my clipboard:

Sign in or Sign up 

 Watch 
104 
 Star 
390 
 Fork 
169

The blank lines come from clipboard, although there should have been the links and so on.
So it is not at all the same as what has been reported.

In this case, I cannot rely on what NVDA reports and what is on the screen. It seems there are being different information provided.

### System configuration:
NVDA version:
2017.4

NVDA Installed or portable:
both

Other information:

# Windows version:
Windows 10 build 16299.64

Name and version of other software in use when reproducing the issue:
Edge browser

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
Yes, NVDA 2017.3

**Comment by Adriani90** [comment]
When pressing left and right to read the single letters of a link, NVDA jumps from link to link instead of reading the letters.

**Comment by Adriani90** [comment]
It could contribute to solve issue #7794

**Comment by Adriani90** [comment]
Unlike in outlook, holding ctrl and navigating with arrow keys by paragraphs does not describe a work around in this case.

**Comment by derekriemer** [comment]
It's not possible to support screen layout in edge.

**Comment by Adriani90** [comment]
Please read again steps to reproduce and reopen the issue. Screen layout is deactivated when reproducing this. I think you did not completely undrstand the issue. Please tell me what is confusing.


Von meinem iPhone gesendet

**Comment by Adriani90** [comment]
It is not required to support screen layout.

 meinem iPhone gesendet

**Comment by derekriemer** [comment]
Oh, so it wasn't saying screen layout needs to be supported? I'm sorry I closed this.

**Comment by derekriemer** [comment]
Okay, so what you say is happening I think I understand now. If you move down from the sign in or sign up, then back up, you end on the edit field, not "sign in or sign up" right?

**Comment by Adriani90** [comment]
That‘s right.


Von meinem iPhone gesendet

**Comment by Adriani90** [comment]
No probem :-) I think I formulated the issue in a confusing way. I intended to make it as clear as possible.
l

Von meinem iPhone gesendet

**Comment by derekriemer** [comment]
@feerrenrut this is a bug. Move seems to be moving it two lines back, not 1, but I don't know why, and don't have time right now to investigate.

**Comment by feerrenrut** [comment]
@derekriemer I can reproduce this too. Testing the same page with chrome does not show this behaviour, the number of stars etc is also reported in chrome.

**Comment by Adriani90** [comment]
This does not occur in Edge Chromium 81. Closing as works for me.

**Comment by Adriani90** [comment]
Adding appropriate label since this is deefinitely still reproducible in Edge Spartan and UIA related environments.
