### ISSUE TITLE
NVDA crashing often when quitting it with Speech Viewer open

### ISSUE THREAD

**Issue by jmuheim** [nvaccess/nvda#7854]
I always have Speech Viewer open when running NVDA.

When I quit NVDA using Insert+N, then X, often the Speech Viewer doesn't respond anymore, and I have to restart Windows to recover from the problem.

My feeling is that this happens especially often when I press the keyboard shortcuts very fast after each other.

I'm running the newest version of NVDA, on Windows 7. And I see this happen since more than a year already.

I'm not 100% sure but I think that also the "Elements list" window used to crash like this also.

Anyone else experiencing this behaviour?

**Comment by ehollig** [comment]
I was able to reproduce this issue on Windows 10 using the following steps:

1. NVDA+N, T, S
2. Check the box for Show Speech Viewer on Startup
3. Exit NVDA with NVDA+N, X
4. NVDA crashes during exit and restarts

When doing the same steps with addons disabled, NVDA exited properly.
@jmuheim, what addons do you have running? Does this happen with all addons disabled?
I also noticed that if you have the elements list (NVDA+F7), open in a web browser then try to exit NVDA by pressing NVDA+N, X, NVDA does not exit and focus is placed on the elements list dialog.

**Comment by dkager** [comment]
To be sure, are there any errors being logged?

**Comment by Qchristensen** [comment]
I had a report from a user who can replicate this issue using Eloquence as well as Vocalizer.  They sent me a log at info level which only contained the following warning:

WARNING - watchdog._watcher (16:26:46.746):
Core frozen in stack:
  File "nvda.pyw", line 217, in <module>
  File "core.pyo", line 517, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 488, in run
  File "queueHandler.pyo", line 86, in pumpAll
  File "queueHandler.pyo", line 53, in flushQueue
  File "scriptHandler.pyo", line 145, in _queueScriptCallback
  File "scriptHandler.pyo", line 187, in executeScript
  File "globalCommands.pyo", line 1452, in script_navigatorObject_devInfo
  File "logging\__init__.pyo", line 1174, in info
  File "logHandler.pyo", line 136, in _log
  File "gui\logViewer.pyo", line 107, in activate

**Comment by Adriani90** [comment]
@jmuheim are you still having this issue in NVDA 2019.3 Beta 2?

**Comment by Adriani90** [comment]
@ehollig could you create a new issue regarding the elements list problem? I could also reproduce it here with NVDA 2019.3 Beta 2.

**Comment by bhavyashah** [comment]
@jmuheim  Please respond to https://github.com/nvaccess/nvda/issues/7854#issuecomment-352064773 and https://github.com/nvaccess/nvda/issues/7854#issuecomment-576041847.

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years. I am closing this issue as abandoned. Please feel free to comment with updated steps to reproduce and coreesponding log file and we can reopen.
