### ISSUE TITLE
Strange issue in some forms in different browsers

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7860]
### Steps to reproduce:
1. Open a browser
2. Go on Github and klick on sign up
3. Press e to go to a form field
4. Activate focus mode by pressing nvda + space
5. Navigate by tab through the registration form

### Expected behavior:
NVDA should report only the form field label, the element type and the status - if given -  (i.e. user name: edit blank)

### Actual behavior:
NVDA reports "list" (before reading the label, element type and status) every time when pressing tab to change to another form field. Lists is disabled in document formating settings.

### System configuration:
NVDA version:
2017.4

NVDA Installed or portable:
Both

Other information:

Windows version:
Windows 10 1709 build 16299.64

Name and version of other software in use when reproducing the issue:
Firefox Quantum, Google Crome, IE 11

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
2017.3

**Comment by Brian1Gaff** [comment]
Does this only occur on the github site, or is it a general issue on forms?

**Comment by Adriani90** [comment]
No, it seems to occur almost on every website but not only in forms. It is a general behavior when navigating the website in focus mode. I wonder that NVDA reports this even when lists are disabled in document formating. Got on groups.io or on bitbicket or so, you will notice this issue, even though it is not very significant. But it is sometimes annoying when dealing with long forms where list is reported continuously.

**Comment by feerrenrut** [comment]
@Adriani90 Could you post the developer info for this form on this issue? You can do this by giving focus to the form element that demonstrates the problem and pressing `NVDA +F1`, the log viewer will open, with the caret on the line where the devInfo starts. You can then select from this line to the end of the last line. Please post that in a comment on this issue (best if you add three "\` " characters on the line before and after, see [Github markdown support examples](https://guides.github.com/features/mastering-markdown/#examples), from that page, click the code examples link and look for "code fencing")

**Comment by Adriani90** [comment]
Here it is:


```
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (10:27:02):
Developer info for navigator object:
name: u'Email'
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_EDITABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible object at 0x0810F270>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithoutAutoSelectDetection'>, <class 'editableText.EditableTextWithoutAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.MSHTML.MSHTML'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (973, 177, 349, 48)
value: ''
appModule: <'appModuleHandler' (appName u'iexplore', process ID 7512) at address 811cef0>
appModule.productName: u'Internet Explorer'
appModule.productVersion: u'11.00.9600.16384'
TextInfo: <class 'NVDAObjects.IAccessible.MSHTML.MSHTMLTextInfo'>
windowHandle: 132560
windowClassName: u'Internet Explorer_Server'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 2896
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x7ac4a60 at 52f3350>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=132560, objectID=339, childID=0
IAccessible accName: u'Email'
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: None
IAccessible accValue: None
MSHTML node has ancestor IAccessible: False
MSHTML nodeName: u'INPUT'
```

**Comment by feerrenrut** [comment]
I'm a little confused. In your steps to reproduce you mentioned using firefox or chrome, but this devInfo looks like it came from Internet Explorer?

**Comment by Adriani90** [comment]
It occurs in all browsers.. It is not browser specific.
 

Von meinem iPhone gesendet

**Comment by Adriani90** [comment]
I have slightly Edited the issue.

**Comment by Adriani90** [comment]
Still reproducible in NVDA 2019.3 Beta 2.

**Comment by zahra21** [comment]
hi.
i confirm this behaviour in old versions of firefox.
i tested especially with nvda 2017.3
but if i remember correctly, in 2017.2 too maybe.
when i open most websites in firefox 45, nvda says list instead of the title of the web page or  website!
in this case, nvda is in brows mode by unfortunately!
i press alt tab to go to another program and return to firefox again to read the title of that page!
