### ISSUE TITLE
Word echo misses first character when overriding a selection

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7862]
### Steps to reproduce:
1. Open Windows Explorer while speaking of typed words is enabled
2. Select a file or folder that can be renamed
3. Press f2 to rename
4. Enter the word "NVDA" and press space

### Expected result
Speech output: NVDA

### Actual result
Speech output: VDA
Log output: "typed word: vda"

### Alternative, generalised steps to reproduce:
1. Open Notepad
2. Enter "NVDA" and press space
3. Speech output: NVDA. Select this content, and type NVDA again followed by space.

### System configuration:
NVDA version: 2017.4 or next-14728,d60e4746
NVDA Installed or portable: Installed
Windows Version: Windows 10 Fall creators update

**Comment by leonardder** [comment]
The reason why this is occurring is actually very obvious when looking at the code, speech.speak cleans the curWordChars buffer. Is it me or is this a bit rigorous?

**Comment by feerrenrut** [comment]
I think this is a duplicate or quite similar to #7812

**Comment by leonardder** [comment]
Closing this as duplicate of #7812, as @feerrenrut is correct.
