### ISSUE TITLE
Major issue in SAP Netviewer when navigating in BI Portal

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7863]
### Steps to reproduce:
1. Open BI Portal and go to MIS
2. Select cumulative and periodic value
3. Select periodic values and activate Navigation
4. At this stage you can customize the data sheet you want to be displayed, that means you should move the relevant columns with the mouse into the data sheet
5. Use table navigation commands to move through the data sheet.

### Expected behavior:
SAP Netviewer is a browse based SAP platform which, amongst others, comunicates with Java plugin. In this case, NVDA should be able to simulate a mouse click when I press enter on a column and should add it to the data sheet on the right side of the Screen. The available columns are mouse over objects but are not links, Buttons or other Kind of objects.
The second part of this issue is the table navigation. NVDA should recognize properly the tables on Websites like BI Portal. I think this issue could be related to Internet Explorer, but since SAP Portals work well only in Internet Explorer, a fix would be very important.

### Actual behavior:
NVDA does not react when I press enter on the column which should be draged and droped in the data sheet. I have seen this issue in many other Websites where objects are mouse over objects but nothing else.
Additionally, NVDA seems to split the rows of the data sheet and put every row in a separate table, sometimes even single cells are treated like an individual table, especially in Header rows. In this case, table navigation with table navigation commands is not possible. This issue occurs for example on NPI Process Portal and lots of other Websites as well. Navigating through the Portal with Jaws, the table Navigation issue does not occur. On these and other affected websites, jaws works fine when table Navigation commands are being used.

### System configuration:
NVDA version:
2017.1, 2017.4

NVDA Installed or portable:
Installed

Other information:

Windows version:
Windows 8.1, Windows 10

Name and version of other software in use when reproducing the issue:
IE 11

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?

**Comment by leonardder** [comment]
Have you specific reasons to think that this problem is NVDA specific?

**Comment by Adriani90** [comment]
As far as the drag and drop thing is concerned, I am not sure. But with respect to table navigation, yes I am sure. I am using jaws as well and the table navigation works fine.

 

 

Von: Leonard de Ruijter [mailto:notifications@github.com] 
Gesendet: Montag, 18. Dezember 2017 19:19
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Author <author@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Major issue in SAP Netviewer when navigating in BI Portal (#7863)

 

Have you specific reasons to think that this problem is NVDA specific?

**Comment by Adriani90** [comment]
This is the debug warning with respect to BI portal:

```
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (10:42:47):
COM pointer <POINTER(IAccessible) ptr=0x7a7a8dc at 80c75d0> already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (10:42:47):
COM pointer <POINTER(IDispatch) ptr=0x7a7a414 at 80c78a0> already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (10:42:47):
COM pointer <POINTER(ITypeComp) ptr=0x7aee314 at 80c7e40> already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (10:42:47):
COM pointer <POINTER(ITypeInfo) ptr=0x7aee3ec at 80c7d00> already deleted
IO - inputCore.InputManager.executeGesture (10:42:50):
Input: kb(laptop):t
IO - speech.speak (10:42:50):
Speaking [LangChangeCommand (u'de'), u'Leer']
IO - inputCore.InputManager.executeGesture (10:42:50):
Input: kb(laptop):downArrow
IO - speech.speak (10:42:51):
Speaking [LangChangeCommand (u'de'), u'Leer']
IO - inputCore.InputManager.executeGesture (10:42:51):
Input: kb(laptop):control+alt+downArrow
IO - speech.speak (10:42:51):
Speaking [LangChangeCommand (u'de'), u'Tabellenrand']
IO - speech.speak (10:42:51):
Speaking [LangChangeCommand (u'de'), u'Leer']
IO - inputCore.InputManager.executeGesture (10:42:52):
Input: kb(laptop):control+alt+upArrow
IO - speech.speak (10:42:52):
Speaking [LangChangeCommand (u'de'), u'Tabellenrand']
```



And here is the developer info for table navigation:

```
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (10:42:59):
Developer info for navigator object:
name: u'Dr\xfccken Sie + zum Expandieren, Ebene "0"'
role: ROLE_SECTION
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.MSHTML.MSHTML object at 0x0558EDD0>
Python class mro: (<class 'NVDAObjects.IAccessible.MSHTML.MSHTML'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: ''
location: (307, 85, 15, 14)
value: ''
appModule: <'appModuleHandler' (appName u'iexplore', process ID 5216) at address 558ec30>
appModule.productName: u'Internet Explorer'
appModule.productVersion: u'11.00.9600.16384'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 132578
windowClassName: u'Internet Explorer_Server'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 5608
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0xacd92a4 at 53f1cb0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=132578, objectID=None, childID=0
IAccessible accName: u'CIP'
IAccessible accRole: ROLE_SYSTEM_CELL
IAccessible accState: STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048576)
IAccessible accDescription: exception: (-2147467263, 'Nicht implementiert', (None, None, None, 0, None))
IAccessible accValue: exception: (-2147467263, 'Nicht implementiert', (None, None, None, 0, None))
MSHTML node has ancestor IAccessible: True
MSHTML nodeName: u'SPAN'
```

**Comment by feerrenrut** [comment]
At the moment, the biggest obstacle to fixing / investigating this is a simple example that can access / use to reproduce the problem. Ideally this is a minimal html file or snippet.

**Comment by Adriani90** [comment]
Regarding table navigation, it could be related to #7852

**Comment by Adriani90** [comment]
Regarding drag 'n drop elements (like in this example) may be more related to improved support of java script behaviors.

**Comment by Adriani90** [comment]
Still reproducible in NVDA 2019.3 Beta 2. I will try to see if it is possible to extract the html code and paste it here.

**Comment by Adriani90** [comment]
BI portal has evolved alot since I reported this issue, IE doesn't exist anymore and in Edge it works well.
Closing as works for me.
