### ISSUE TITLE
After closing outlook on some messages outlook displays a message to save the body of the message

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7866]
When reading with the arrows some messages in outlook and soon after pressing esc to close the message the outlook displays a message to save the changes in the message.
Not a change was made in the message intentionally.
This problem does not occur when reading the message with the jaws.
This problem also occurs when running nvda with disabled addons.

### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
open the attached e-mail message.
Press the arrows below to read line by line, for a 4 lines.
Press esc to close the message.

### Expected behavior:
> Tell us what should happen.
The message should be closed without even an outlook warning.

### Actual behavior:
> Tell us what happens instead.
pressing esc escapes a message asking if you want to save changes to the message.
As we just read the message with the arrows do not expect the outlook to ask me if the message should be saved.
Stop that nvda is making some change in the message that the outlook believes the reader wants to save.
### System configuration:
NVDA version:
> Example: next-14728

NVDA Installed or portable:
instaled
Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1709 Build 16299.64 and windows 7

Name and version of other software in use when reproducing the issue:
outlook 2016 e outlook 2013
### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result

no
[Deyse Veloso Da Silva comentou em uma lembrança em que você foi marcado..msg.zip](https://github.com/nvaccess/nvda/files/1571663/Deyse.Veloso.Da.Silva.comentou.em.uma.lembranca.em.que.voce.foi.marcado.msg.zip)

**Comment by PratikP1** [comment]
I can confirm this. It started occurring recently in Outlook 2016 with NVDA. Essentially, when a message is opened, arrow keys are used, then the message is closed, Outlook prompts with a message similar to this: 
> The body of the message "Re: [nvaccess/nvda] Long delays while arrowing through text with SAPI5 voice and read command keys on (#7856)" has been changed.
> Want to save your changes to this message?
> Yes No Cancel

Debug log shows nothing that could point to the problem.

**Comment by Brian1Gaff** [comment]
Did this not used to happen in the old 2003 version from time to time as 
well back  a long time ago?
 Brian

**Comment by fernando-jose-silva** [comment]
I can no longer reproduce the problem, thank you very much

**Comment by Adriani90** [comment]
Closing. Thank you very much Fernando for reporting.
