### ISSUE TITLE
The font color retreived in word is different if pressed once than twice

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#7869]
### Steps to reproduce:

1. open word, and type derek.
2. Select the first letter e, and go into font settings (ctrl+d) and select red (bright red, 255,0,0).
3. Now, move left a character. Press NVDA+f:
    - Expected and actual: default.
4. Now, nvda+f twice.
    - Expected 
        ```
        style Normal
        Calibri
        11pt
        Default color
        align left
        line spacing 1.1 lines
        ```
    - Actual:
        ```
        style Normal
        Calibri
        11pt
        aqua grey
        align left
        line spacing 1.1 lines
        ```
5. Move right a char:
    - Actual and expected: 'style Normal  Calibri  11pt  bright red  align left  line spacing 1.1 lines'
6. Now, press NVDA+f twice.
    - Expected:
        ```
        style Normal
        Calibri
        11pt
        bright red  
        align left
        line spacing 1.1 lines
        ```
    - Actual:
        ```
        style Normal
        Calibri
        11pt
        aqua grey
        align left
        line spacing 1.1 lines
        ```

### Impact:
Users are given false information on color.

**Comment by Brian1Gaff** [comment]
What is the background colour in this case?
 Brian

**Comment by feerrenrut** [comment]
Yes I can reproduce this in Word 2013.
