### ISSUE TITLE
Include Edward voice from NV Speechplayer with NVDA for Windows 10s

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7870]
I read in the nvacces itself that at least in the first few years the addons will not be available in nvda that will run on windows 10s.
What made me sad is the possibility that I can not use the edward voice available on the speechplayer in espeak synthesizer.
My suggestion would be to be able to choose this voice natively in the nvda.
My request would be so that this voice is one of you that can be chosen, it is not so that this voice is the standard, this because I remember that this was reason of very great neglections to times last. As such, espeak would still be the standard for nvda, however the Edward voice could be natively chosen in nvda without the need to install the speechplayer add in espeak since it can not be installed on nvda using windows 10s at least in the first tions.

**Comment by feerrenrut** [comment]
@fernando-jose-silva Hopefully I understand correctly. This is something that might be considered for a future release of NVDA generally. At this point we do not have a timeline. It would require that [NV Speech Player](https://bitbucket.org/nvaccess/speechplayer) be built against new versions of espeak and integrated with NVDA.

**Comment by Brian1Gaff** [comment]
If you want it now you can still have it using the download with the added 
advantage at the moment for UK English speakers that all the other voices 
are in the add on and hence none of the really serious regressions of Espeak 
NG recently are there and for is fore and newsletteer  is said correctly and 
most of the other problems are gone.

Brian

**Comment by fernando-jose-silva** [comment]
Thank you very much. feel free to prioritize this task according to your needs.
Currently we can download the add-on, more in windows 10s so I understand you will not be able to use the addons of nvda at least in the first instant.

**Comment by ehollig** [comment]
Related issues: #4578, #5272

**Comment by michaelDCurran** [comment]
NV Access has chosen to no longer work on this particular project. Although I did update nvaccess/nvSpeechPlayer to be Python3 compatible and the add-on to be NVDA 2019.3 compatible, there are some breaking changes in eSpeak that specifically cause speechPlayerInEspeak (Edward) to no longer correctly speak voiced consonants (z, v, j, g etc). This broke somewhere in late eSpeak 1.48 or 1.49. I don't personally have the time to look into this anymore. Though of course other members of the community would be most welcome to pick this up and try and further debug and solve the issues.

**Comment by datajake1999** [comment]
SpeechPlayer is now a part of espeak-ng.
