### ISSUE TITLE
User Guide: Excel's shift+f2 to enter comment editing mode.

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#7888]
Could you please consider to add this command(shift+f2) to User Guide 10.2. Microsoft Excel.

What's New 2014.3:
> Microsoft Excel: Provide an NVDA-specific dialog to edit the comments on the currently selected cell when pressing Excel's shift+f2 command to enter comment editing mode.

**Comment by feerrenrut** [comment]
I think that would be a good idea, link to the [relevant line in changes.t2t](https://github.com/nvaccess/nvda/blob/2bc0511af6e7c6b09fa40ff4b07abb543de343ce/user_docs/en/changes.t2t#L803)
I confirmed this is not listed in the [user guide](https://github.com/nvaccess/nvda/blob/2bc0511af6e7c6b09fa40ff4b07abb543de343ce/user_docs/en/userGuide.t2t)

**Comment by josephsl** [comment]
Hi, usually we don’t list commands that are provided by applications unless NVDA overrides it for various reasons. I think a paragraph about this dialog would suffice. In case folks find other user guide problems, please do file them as separate issues so I can work on them next week. Thanks.
