### ISSUE TITLE
App modules: add additional properties for benefit of testing, add-ons and alike

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#7894]
Hi,

Sprang from a discussion on Gitter:

A new add-on developer asks if a property to return the full path for an app be created. @JCSTeh gave a solution. And since I've been meaning to add a few more properties (namely detecting if we're dealing with a universal app or not), I though it would be best to raise a meta-issue here.

Thus please let us know if you need properties about an app that should be shown as part of an app module.

Thanks.

**Comment by feerrenrut** [comment]
The solution given by jcsteh on gitter:

>Because we no longer support XP, you can use QueryFullProcessImageName. If you have an NVDAObject or AppModule for this process you want to query, you can use its processHandle property. Here's a Python console example:
> ```
> >>> size = ctypes.wintypes.DWORD(ctypes.wintypes.MAX_PATH)
> >>> path = ctypes.create_unicode_buffer(size.value)
> >>> ctypes.windll.kernel32.QueryFullProcessImageNameW(nav.processHandle, 0, path, ctypes.byref(size))
> 1
> >>> path.value
> u'C:\\Windows\\System32\\bash.exe'
> ```

**Comment by leonardder** [comment]
I think this particular property really makes sense!

**Comment by leonardder** [comment]
>Because we no longer support XP, you can use QueryFullProcessImageName. If you have an NVDAObject or AppModule for this process you want to query, you can use its processHandle property.

It seems  AppModule._setProductInfo already uses this approach, it only does not make the path visible to the end user.

**Comment by josephsl** [comment]
Hi, sure. Any other properties we need? I’m seriously considering working on this pull request and add much needed properties. Thanks.

**Comment by Adriani90** [comment]
@josephsl are you still working on this?

**Comment by josephsl** [comment]
Hi,

I need to see what properties people need for apps before I work on it for 2018.4.

Thanks.

**Comment by josephsl** [comment]
Hi,

Other properties suggested by people include:

* Immersive app: likely to be called "isHostedApp" that should be able to handle scenarios such as universal apps and Javaw. Another option is to clal this "isImnmersiveApp" with docstring explaining what "immersive" is.
* Address bar content: not exactly on scope, but useful for browser app modules to retrieve address bar content.

In addition, I propose:

* appArchitecture: returns the machine architecture for which the app was written for, suitable for Windows 10 ARM64 where it supports ARM64 and X86. With this property, NvDA should be future-proof to support a scenario where X64 apps would run on ARM64 in the future.
* Hosted inside another app: way different than Javaw or universal apps, suitable for handling a case where content process is embedded inside another app (Microsoft Edge, for example).

For now, I'll start with appPath (executable path) and will add more properties based on feedback. Thanks.

**Comment by josephsl** [comment]
Hi,

Another update: now that #4259 is here, hosted app property will first look for package info for hosted apps before saying "no". This is because some apps are not true Store apps (File Explorer) or should be treated as a hosted app when user32::IsImmersiveProcess says no (Store version of Office 365 apps, for instance). Because this change also modifies just modified product info setter, I'm willing to let the accompanying pull request wait until early next year so people can play with the newly revised product name and version getter introduced in 2019.3.

Thanks.

**Comment by josephsl** [comment]
Hi,

And now, ready for another round of review on the accompanying PR.

Thanks.

**Comment by feerrenrut** [comment]
Thanks @josephsl we'll take a look soon.
