### ISSUE TITLE
Document browse - allow to exit a <pre> block.

### ISSUE THREAD

**Issue by chinwobble** [nvaccess/nvda#7895]
### Steps to reproduce:
1. Open a page with a pre tag like https://developer.android.com/guide/components/activities/activity-lifecycle.html 
2. Navigate to the pre code blocks and try to navigate out of them (trying to quickly get to the paragraph immediately after the code blocks)

### Actual behavior:
In order to get out of the block, you need to read each line using the control+down arrow keys one at a time and it doesn't report when you have exited. 

### Expected behavior:
Treat the pre tag as a container object and allow using the exit container command (comma key) to get to the next document element 

### System configuration:
NVDA version: 2017.4 
NVDA Installed
Windows version:: Windows 10 64-bit Build 16299
Firefox Quantum 53
Google Chrome 63

**Comment by bramd** [comment]
This might be a good idea, however we need to add some kind of announcement as well when the user enters/leaves a pre element, otherwise the fact that it is a pre and a container will not be obvious.

**Comment by chinwobble** [comment]
@bramd  thanks for your feedback. 

I'd imagine the user announcements should be similar to entering a list. 
Announcing Saying: "Container with x items" 

Could you suggest where I should look to try to implement this?

**Comment by leonardder** [comment]
I think on the long term, this is quite difficult to implement. The only means to see whether code is inside pre tags is the pre tag itself. Virtual buffers know about these tags, but virtual buffers probably won't exist for another five years. In edge, I belief there is no way to find the html tag of an object.

**Comment by Adriani90** [comment]
This is now possible in NVDA last alpha with the vertical navigation command. You can assign gestures to it in NVDA input gestures dialog while being in browse mode. I assigned for example alt+nvda+up and down arrow.
The code blocks are indented further to the right compared to the text paragraphs above or below them, so you can focus e.g. the paragraph before the code block, and press the vertical navigation command down, then you skip the code block and land directly on the text paragraph after the block.
Closing as works for me.

**Comment by CyrilleB79** [comment]
Tagging here the vertical navigation PR #16236, so that we have a trace of this issue in the feature's PR in case it should be reverted in the future; let's hope not though.

But IMO, there could be situations where the code snippet is aligned vertically with the surrounding text. The users may also not be easily aware of the difference of vertical alignment of the code.

So I'd say that this issue is rather closed by the style navigation commands feature (PR #16050).
