### ISSUE TITLE
Focus bug during heading navigation

### ISSUE THREAD

**Issue by rahimabdi** [nvaccess/nvda#7897]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> In a programmatically focusable DIV with more than 1 heading:
>
> 1. Press "H" to navigate to any heading after the first one
> 2. Press "Tab" to focus the next focusable element
> 3. Focus moves to the first focusable element within the DIV, rather than the first focusable element below the heading.
>
>Codepen example: https://codepen.io/rahimabdi/pen/rpYBPb

### Expected behavior:
> Focus should move to the first focusable element below the heading.

### Actual behavior:
> Focus moves to the first focusable element in the programmatically focusable DIV.
>
>### System configuration:
>NVDA version: 2017.4
>NVDA Installed or portable: Installed
>
>Browser version: Mozilla Firefox ESR 52.5.3
>
>Windows version: Windows 10 Enterprise 64-bit (10.0.14393)
>
### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA? No

**Comment by josephsl** [comment]
Hi, can you try testing this with IE and Edge please? CC @DerekRiemer, @JCSTeh

**Comment by rahimabdi** [comment]
Hello,

The issue also appears for IE 11.1944.1393.0 and Edge 38.14393.1066.0.

-Rahim

**Comment by josephsl** [comment]
Hi, I see. Does this happen on other similarly coded websites? @DerekRiemer and @JCSTeh, any thing else we should try?

**Comment by rahimabdi** [comment]
In addition to my sample page, it occurs on our institution's CIO page (ocio.osu.edu) and the home page for Level Access' AMP tool (our institution's production instance). I discovered the bug while doing accessibility testing of these sites.

**Comment by josephsl** [comment]
Hi, I see. The thing is that we cannot have access to these sites unless permission is given (from webmasters, the university, or via a consulting contract or other legal means) for technical investigations. What we were looking for is a set of publicly accessible websites (as in people can visit a site via web browsers) with similar coding to what you’ve provided. Thanks, and sorry for the inconvenience.

**Comment by pbossley** [comment]
The ocio.osu.edu website is publically accessible in addition to the test page above; is that sufficient for testing?

**Comment by josephsl** [comment]
Hi, yes, that should work. Some of us might be interested in other domains (not just this site) where this occurs to find out if it is just the website, browser support code, the browser or what not. Thanks.

**Comment by jcsteh** [comment]
Please provide a test case in future. Simple test case:

`data:text/html,<div tabindex="-1"><h1>a</h1><button>b</button><h2>c</h2><button>d</button></div>`

This occurs because if the virtual caret is within the focused node, the tab/shift+tab keys are passed through to allow normal tab order navigation. Otherwise, the tab order set by the author is not respected if the tab order is different to the DOM order. This is definitely not something we want to change, but I also don't know how we can fix this issue without changing it.

**Comment by jcsteh** [comment]
For anyone looking into this, the relevant code is in browseMode.BrowseModeTreeInterceptor._tabOverride (source/browseMode.py around line 1282).

**Comment by pbossley** [comment]
I see the problem. I assume the reason we are seeing this is that folks are using that to perform a skip navigation. We can just avoid that technique but that doesn't solve the underlying issue that we've seen some examples of 3rd party software that does this as well. Knowing the reasoning is helpful, though.

**Comment by PratikP1** [comment]
@jcsteh commented:
> This occurs because if the virtual caret is within the focused node, the tab/shift+tab keys are passed through to allow normal tab order navigation. Otherwise, the tab order set by the author is not respected if the tab order is different to the DOM order. This is definitely not something we want to change, but I also don't know how we can fix this issue without changing it.

Would it be possible to search for author-defined tabindex attribute or would that create a significant performance degradation?

**Comment by jcsteh** [comment]
We don't use the DOM at all in Firefox or Chrome. Even if we did, I don't
think this would be feasible for performance reasons. Also, this doesn't
handle author overriding of the tab key, which is something that might be
done in more complex web apps, though I can't cite any evidence for that.

**Comment by RichCaloggero** [comment]
If this helps, the problem occurs when virtual focus is on any node inside a focusable container, even if the container is not in the tab order (i.e. `tabindex="-1"` on the container).
Another simptom seems to be that you can, in fact, tab to the container node (as if it had `tabindex="0"` on it).

See this example:
http://RichCaloggero.github.io/bug/tabindex.html

- focus on the second paragraph (the one just following the first button)
- press tab
	+ focus moves back to the button (which is the first focusable item within the focusable container)
	+ it should move forward to the next focusable element which is a button
- move to top of document and press tab
   + focus moves to the container node and everything inside it is read
   + focus should move to the first button inside the container


Hope this helps.

**Comment by jcsteh** [comment]
Also occurs in Firefox for scrollable regions, since scrollable regions are focusable in Firefox so that non-screen reader keyboard users can scroll them. (Chrome doesn't do this.) For example, this happens on the NV Access website. Distilled test case:
`data:text/html,<div style="overflow: auto; height: 20px;"><h1>a</h1><button>b</button><h2>c</h2><button>d</button></div>`

**Comment by rahimabdi** [comment]
Expected behavior, closing.
