### ISSUE TITLE
SUPPORT FOR FORMULA IN MICROSOFT EXCEL

### ISSUE THREAD

**Issue by slnconline** [nvaccess/nvda#7899]
I observed that there's no keystroke or hot key to read the formula bar in the Microsoft Excel. Whenever one moves to the cell having the value and the formula, NVDA will announce the value in the cell e.g. 362 has a formula. but there's no how to read or check the formula used in getting that particular value in the cell.

It's best to have a hot key or keystroke to press and have the NVDA automatically read out the formula bar to enable the blind user know the formula used to get the result in a particular cell.

I used installed copy of NVDA2017.4 on my PC running Windows10.

I've used the NVDA with Microsoft Office Excel 2007, 2010, 2013 and 2016.

I've tried NVDA2017.2 and NVDA2017.3 but still experience the same thing.
[sales for the week.xlsx](https://github.com/nvaccess/nvda/files/1608482/sales.for.the.week.xlsx)

**Comment by josephsl** [comment]
Hi, if you know the coordinate for the cell with formulas, switch to browse mode then press NVDA+F7 to open elements list. From there, switch element type to formulas, scroll through the resulting list and you’ll see the formula. Alternatively, if the workbook isn’t protected, you can press F2 to edit the cell contents. I think a command to announce cell details would be nice for this situation, similar to cell comments. Thanks.

**Comment by Adriani90** [comment]
You can read the formula very easy by using object navigation.

**Comment by slnconline** [comment]
Thanks for the tips. I feel it's best to have just a keystroke to perform that rather than going through the processes you've outlined. This will make reading and navigation easier and faster.

**Comment by leonardder** [comment]
You can easily switch between viewing results and formulae by pressing control + ` (accent grave)

**Comment by Adriani90** [comment]
I agree this would improve Efficiency if we had a key stroke for Formula bar like for comments. I.e. alt+nvda+f.

**Comment by netblue44** [comment]
I also concur a key stroke wood be extremely helpful

**Comment by Adriani90** [comment]
Closing in favor of #3576 which even contains some code contributions for this feature.
