### ISSUE TITLE
Reading mathematical articles and creating formulas

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7905]
### Steps to reproduce:
1. Open a mathematical / scientific article in MS Word, browser or PDF which contains signs like Sigma (standard deviation, Per Mille, double integral etc.).
Example: 
http://sites.psu.edu/symbolcodes/accents/math/mathchart/
2. Go to the signs "Asterisk Operator" or "Sigma / Standard deviation"
3. Read the signs with NVDA

### Expected behavior:
NVDA should contain a punctuation level called "mathematical" in voice settings which would contain all the descriptions of the mathematical signs unter the link above.

### Actual behavior:
Some sighns are not described in a mathematical way (i.E. * is pronounced "star" but it also could be "Asterisk Operator" in a mathematical article. Other signs are not being recognized at all (i.e. the sign for Excess).

### System configuration:
NVDA version:
2017.4

NVDA Installed or portable:
Both

Other information:

Windows version:
Windows 10

Name and version of other software in use when reproducing the issue:
Firefox 57, MS Word 2016, Adobe Acrobat Reader

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
NVDA 2017.3

**Comment by ehollig** [comment]
I believe this has been briefly discussed in #6904. #3805 also discusses including common Unicode characters.
With regards to how NVDA reads a particular symbol in a formula, I do not believe this can be changed based on the context. The symbol ∗ and * are two different characters, while they can possibly mean the same thing. CC @derekriemer, @jcsteh

**Comment by Adriani90** [comment]
I still believe a new interpunctuation level only for mathematical signs should be added to NVDA, could be defined in the symbols.dic for the coresponding symbol or in the symbols dialog.
There are unicodes especially for mathematical symbols, most of them however would be of no use for the average user. But for someone who is working often with mathematical content, this might make sense.
cc: @leonardder

**Comment by Adriani90** [comment]
In case #11467 gets merged, I think we can think about creating customized interpunctuations level. For most use cases I would take the category "some" and add the customized symbols to it (i.e. some + mathematics, some + musical symbols, some + braille symbols) or what ever is customized. This should make it easier to fetch the symbols at once without having to adjust the symbol level for each of them. For mathematical symbols there are more than 100.

**Comment by Adriani90** [comment]
cc: @feerrenrut, @michaelDCurran would you accept something like that? I.e. a new category in the punctuation / symbol level  combo box in speech settings called "some + mathematical symbols?

Actually I am not sure wether the functionality of that combo box inherits NVDA's symbols dictionary or the synthesizer specific dictionary provided by the synth itself.

**Comment by Adriani90** [comment]
I think it got much better now with the unicode normalization added by Leonard and the additional math symbols I've added to the symbols.dic file years ago. After all, I don't think we need this complexity. I am closing, but if there is any argument to still investigate this, please comment and we can reopen.
