### ISSUE TITLE
switching from a chrome video playing window to other app's window, NVDA will become cridical slow until I swith to desktop at first.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#7907]
### step to reproduce
> 1. Open chrome browser.
> 2. Open a web page with video playing by adobe flash player. Example page: http://www.ktkkt.com/y/2932/player-0-4.html
> 3. Swith to other app's window, for example skype. Now browse control will become criticle slow.
> 4. Ignore step three, let's go to the next step.
> 5. Switch to desktop at first.
> 6. Switch to skype. Now all are normal.
NVDA version: next-14781,6c5a4b12
system: windows 10 version 16299.192
 portable installation: no.
Thanks!

**Comment by feerrenrut** [comment]
I haven't been able to reproduce this issue when using Skype Version `7.40.0.103` and Chrome `63.0.3239.132`
What versions do you have?

**Comment by vgjh2005** [comment]
Hi:
chrome version:63.0.3239.108 x64.
I think you should use the low cost computer to reproduce it.
My notebook:
cpu:Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz
ram:4g ddr3
harddisk:HGST HTS541010A9E680 1tb
Thanks!

**Comment by vgjh2005** [comment]
In my computer,when video is playing, controlling speed will become more slower in this window. If I don't switch to the desktop,controlling speed will not be restored. If I switch to the desktop at first, controlling will be normal.

**Comment by Adriani90** [comment]
@vgjh2005 are you still having this issue with NVDA 2018.4? It will be quite hard for us to investigate your problem. Does this occur with other screen readers as well? Are you on very last update of Windows 10? What drivers do you have? Your notebook is not bad actually. I had one with Intel core i5 3. generation and I never had this issue. If it is a Dell laptop, be sure to remove the killer suite and reinstall the wireless driver. This causes performance issues on Dell in general. You can find lots of forums treating that topic in internet.

**Comment by Adriani90** [comment]
And please try to disable energy saving setting in the energy settings in Windows. NVDA's performance is not good if you have enabled many energy savers. But this is not only NVDA related. Every application reacts slower then.

**Comment by vgjh2005** [comment]
Thanks!
