### ISSUE TITLE
NVDA could properly read the option to install the Ask Toolbar when installing UTorrent

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#791]
**Reported by elliott94 on 2010-07-29 17:57**
In the latest versions of UTorrent, the installer offers the user to install the Ask Toolbar, along with setting their homepage and default search provider to ask.com (both of these checkboxes are read). However, the option that allows you to select whether the toolbar itself is installed isn't read by NVDA when hitting tab, and as far as I know can't be accessed when using object navigation. As far as I can tell it's not a standard checkbox, which may make it more difficult to provide access to this particular control, but it can get very annoying for the end-user to have to manually uninstall the software after it's been installed, without any accessible way to disable it.

**Comment by leonardder** [comment]
@elliott94: Could you provide a status update for this issue?

**Comment by elliott94** [comment]
I no longer use this software - I'm happy for this to be closed if nobody else has experienced this recently.

**Comment by derekriemer** [comment]
closing because the reporter requested it.
