### ISSUE TITLE
word catching when trying to navigate with the arrows quickly

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7914]
this is one of the errors that are very difficult to demonstrate.
I noticed that more often the word is crashing when pressing the arrows on a document as soon as it is opened.
I will describe the situation when word locked to see if it facilitates understanding.
I was in a bit of a hurry, so I pressed enter on a word document so that it was opened, and as soon as nvda started to advertise the name of the document already pressed down arrow.
I did not wait for the nvda to enter the name of the entire document, as soon as he started reading the first syllable, I pressed the arrow below.
When I did this nvda was mute and after a while I finally heard the word had stopped.
This has already happened twice.
I emphasize that if I have a pass and wait for the nvda to read some words as soon as the document is opened I did not receive the error.
Also, it is not every time I can reproduce this error.
nvda is the next 14781
the word is 16.0.8730.2175 32bits
windows 10 16,299,192 64bit
thank you, opening this error due to the changes in nvda with the use of uia, and to see if there is anyone else with these symptoms, or if it is me who have to have more patience, laughs.

**Comment by michaelDCurran** [comment]
Was this with UIA support for MS Word turned on in NVDA via the config 
option?

**Comment by Adriani90** [comment]
Do you Encounter this issue even when pages is disabled in document formating Settings?

**Comment by fernando-jose-silva** [comment]
Thank you very much for the returns.
Michael if the option to use the uia is not enabled by default, I'm not using it, I did not change a configuration regarding uia, nor would I know how to do this.
Adriani, was with the enabled pages advertising settings, I will disable and see if the problem occurs again within a week.

**Comment by fernando-jose-silva** [comment]
Many thanks for the feedback, and sorry for not updating more.
I believe the problem can be terminated, disabling the page report did not have the problem anymore.

**Comment by ehollig** [comment]
Thank you for the comment @fernando-jose-silva. Closing
