### ISSUE TITLE
NVDA does not route the mouse correctly when using object navigation in MS Edge

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7916]
### Steps to reproduce:
1. Using Edge, Go to
https://www.nvaccess.org/post/in-process-17th-march-2017/
2. Navigate in browse mode to an image from the article
3. Use object navigation to focus the image with the NVDA cursor
4. In laptop layout, press NVDA+Shift+m to route the mouse to the NVDA cursor

### Expected behavior:
NVDA should move the mouse onto the image like in firefox or Internet Explorer.

### Actual behavior:
Sometimes NVDA moves the mouse elsewhere but not on the image, sometimes the mouse is not being moved at all.

### System configuration:
NVDA version:
2017.4

NVDA Installed or portable:
Both

Other information:

Windows version:
Windows 10 Build 16.299.64

Name and version of other software in use when reproducing the issue:
Microsoft Edge.

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No

**Comment by feerrenrut** [comment]
Possibly related to #7915.
As with #7915, check if the position reported by Edge matches the actual position of the element, if not then we need to raise a bug against Edge.

**Comment by Adriani90** [comment]
#5602

**Comment by Adriani90** [comment]
#7083

**Comment by Adriani90** [comment]
#8076 is related, however the discussion could be continued there.
