### ISSUE TITLE
Expand the menu bar in google spreadsheets

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7922]
### Steps to reproduce:
Using firefox 57 open a new spreadsheet in google documents.
When you open the new worksheet, focus mode is enabled.
Press nvda + space to go to scan mode.
You can now press ctrl + home to go to the top of the page.
press ctrl + nvda + f to search for text, type file.
When pressing enter you should be on a menu item called file.
Now press enter to open the submenu of this item.

### Expected behavior:
The submenu should open.

### Actual behavior:
If you press enter on the File menu item, or on any other menu item such as Edit, Preview, the submenus are not opened and nothing happens.
You can not navigate the submenus.

### System configuration:
NVDA version:
> Example: next-14799

NVDA Installed or portable:
instaled
Other information:

Windows version:
> Example: Windows 7

Name and version of other software in use when reproducing the issue:
firefox 57 64bits
### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
> Please list them and the result

no
follows a log of the moment the enter is pressed and nothing occurs.

IO - speech.speak (18:36:34.217):
Speaking [u'item de menu  submenu', u'Arquivo']
IO - inputCore.InputManager.executeGesture (18:36:36.125):
Input: kb(laptop):enter
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (18:36:36.161):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (18:36:36.164):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (18:36:37.990):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (18:36:38.059):
Developer info for navigator object:
name: u'Arquivo'
role: ROLE_MENUITEM
states: STATE_COLLAPSED, STATE_FOCUSABLE, STATE_FOCUSED, STATE_HASPOPUP
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_MenuItemMozillaIAccessible object at 0x05E22A30>
Python class mro: (<class 'NVDAObjects.Dynamic_MenuItemMozillaIAccessible'>, <class 'NVDAObjects.IAccessible.MenuItem'>, <class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (151, 110, 58, 26)
value: None
appModule: <'firefox' (appName u'firefox', process ID 7948) at address 5c7cb30>
appModule.productName: u'Firefox'
appModule.productVersion: u'57.0.4'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 1049626L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 382664704
windowThreadID: 3400
windowText: u'Planilha sem t\xedtulo - Planilhas Google - Mozilla Firefox'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x6faec94 at 5e44080>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=1049626, objectID=-4, childID=-33555639
IAccessible accName: u'Arquivo'
IAccessible accRole: ROLE_SYSTEM_MENUITEM
IAccessible accState: STATE_SYSTEM_HASPOPUP, STATE_SYSTEM_COLLAPSED, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1074791428)
IAccessible accDescription: u''
IAccessible accValue: None
IAccessible2 windowHandle: 1049626
IAccessible2 uniqueID: -33555639
IAccessible2 role: ROLE_SYSTEM_MENUITEM
IAccessible2 states: IA2_STATE_SELECTABLE_TEXT, IA2_STATE_OPAQUE, IA2_STATE_ACTIVE (5121)
IAccessible2 attributes: u'margin-left:0px;text-align:start;haspopup:true;text-indent:0px;setsize:10;id:docs-file-menu;tag:div;class:menu-button goog-control goog-inline-block goog-control-hover;xml-roles:menuitem;margin-top:2px;posinset:1;margin-bottom:0px;margin-right:0px;display:inline-block;formatting:block;'

**Comment by feerrenrut** [comment]
When using Firefox 57.0.4, I did the following to access the file menu:
1. swap to browse mode with `NVDA+space`
1. press `ctrl+home` to get back to "sheets home"
1. press `NVDA+Ctrl+f` to use the nvda find dialog to find "file"
1. press `NVDA+space` once or twice, to ensure you are in focus mode
1. press the right arrow.

**Comment by fernando-jose-silva** [comment]
Yes, this way I was able to open the menus.
You can change this behavior of nvda and allow the menus to open only by pressing enter while in browse mode.
This would make the task of navigating the menus much easier.

**Comment by PratikP1** [comment]
In general, Google Docs suite (including Sheets) is better in focus mode. Use the following link to learn about how to activate menus and use other keyboard commands when the browse mode is switched off.
https://support.google.com/docs/answer/1632199?hl=en&ref_topic=6239407

**Comment by feerrenrut** [comment]
Thanks @PratikP1 this looks like the most efficient way to interact with the Google Docs suite. @fernando-jose-silva hopefully this works for you?

This issue does seem to be something that should be addressed by NVDA, as such I will close this issue.
