### ISSUE TITLE
Thunderbird: un/subscribe for imap folders isn't possible using NVDA

### ISSUE THREAD

**Issue by bdorer** [nvaccess/nvda#7925]
### Steps to reproduce:
1. Open Thunderbird
2. arrow to your email account
3. open context menu and choose subscribe
4. press tab two times to land in the list of folders
5. Arrow arround

### Expected behavior:
NVDA should read list entries and wheather they are checked or not.

### Actual behavior:
NVDA is silent. Using object navigation isn't possible in this list.

### System configuration: 
NVDA version: next-14795,19b5f5b6

NVDA Installed or portable: installed

Windows version: 10.0.16299

Name and version of other software in use when reproducing the issue:
Thunderbird 52.5.2

### Other questions:

Does the issue still occur after restarting your PC? yes

Have you tried any other versions of NVDA? no

**Comment by feerrenrut** [comment]
Could you please provide a debug level NVDA log after attempting this?

**Comment by bdorer** [comment]
Here's a commented log file. You should be able to follow my log easily because I translated the German strings but I may used the wrong english words.

[log.txt](https://github.com/nvaccess/nvda/files/1817404/log.txt)

**Comment by bdorer** [comment]
seems to be fixed doing thunderbird development
