### ISSUE TITLE
nvda lately slow on page using firefox

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7927]
Previously I opened a call reporting that this page when being opened with firefox 57 was very slow.
What makes me report this again is that the performance on this page was much worse.
### Steps to reproduce:
Open the page
https://www.cisco.com/c/pt_br/about/events-schedule/quintas-quinze.html

press ctrl + nvda + f
type 2018
press enter to do the search.

### Expected behavior:
The nvda should take around 6 seconds to allow navigation with the arrows on the page.

### Actual behavior:
nvda is taking about 50 seconds to allow navigation with the arrows

### System configuration:
NVDA version:
> Example: next-14799 
NVDA Installed or portable:

Other information:
core i 3 6200u 2,2ghz
4gb ran
ssd 128gb

Windows version:
> Example: Windows 10 Version 1709 16299.192

Name and version of other software in use when reproducing the issue:
firefox 57 64bits
### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by feerrenrut** [comment]
The previous issue was #7813, please report this on that issue. I'll close this issue since it is a duplicate. Please also report on #7813 if anything else on your system has changed, and if it is faster with an older version of NVDA.
