### ISSUE TITLE
Using chrome it is not possible to browse a page of the mosila

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7928]
### Steps to reproduce:
open the page
https://www.mozilla.org/pt-BR/firefox/new/

navigate with the arrows down the page for at least 5 times.

### Expected behavior:
it should be possible to navigate the entire page with the arrows

### Actual behavior:
nvda gets stuck in the sentence
Baixe o Firefox — Navegador web gratuito

you can not navigate to another point on the page with the arrows or tab.

### System configuration:
NVDA version:
> Example: next-14799
NVDA Installed or portable:
instaled
Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1709 16299.192

Name and version of other software in use when reproducing the issue:
chrome 63.0.3239.132 64bits 
### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result

no

**Comment by fernando-jose-silva** [comment]
When I said that the nvda is stuck, I meant that the same sentence is always read.

Baixe o Firefox - Navegador web gratuito

Stop the whole page from leaving the virtual buffer, because nvda does not even show a link on the page.
When the page is opened by clicking on the list of links to several links on the page, when walking with the arrows when nvda gets stuck in the sentence when opening the list of links all links are gone.
This is with any synthesizer.
Switching with alt + tab does not solve.

**Comment by feerrenrut** [comment]
I can't reproduce this with Chrome 63.0.3239.132, the only place I can find the text "Baixe o Firefox - Navegador web gratuito" is in the title bar for Chrome.

When you press alt+tab does nvda speak as expected for other applications? If you can reproduce this still, can you please attach a debug level NVDA log to this issue?

**Comment by Adriani90** [comment]
I cannot reproduce this issue with NVDA 2019.1.1 and Chrome 74. Fernando if you still have this issue, please comment on it and we can reopen the discussion. Thanks!
