### ISSUE TITLE
Read lines and spaces in google docs

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7939]
### Steps to reproduce:
Open a new document in google docs, an empty text document.
now type in the first line
it is test
Now navigate character by character by the inserted line and see that the spaces are not announced by nvda, when there is a space the nvda is muted.
Now create a empty  line by pressing twice after the end of the first line.
Write a text on the 3rd line you created.
My name is Fernando.
Now navigate with the arrows up and down and see that between line 1 and line 3 there is a empty  line where the nvda is mute, the expected would be that the nvda announced line empty  equally in word.

### Expected behavior:
When the nvda focus spaces should advertise space.
When nvda focuses on an empty line it should advertise empty line.

### Actual behavior:
When focusing on empty spaces or lines, it is muted.

### System configuration:
NVDA version:
> Example: next-14799

NVDA Installed or portable:
instaled
Other information:
> Example: Running in a VM

Windows version:
> Example: windows 7

Name and version of other software in use when reproducing the issue:
firefox 57
### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by ehollig** [comment]
Have you tried enabling [Braille accessibility support in Google Documents](https://support.google.com/docs/answer/6057417?hl=en)

**Comment by PratikP1** [comment]
Enabling Braille support through the accessibility menu mitigates this bug. Once enabled, it hinders proper table reading in Docs. I believe #7935 is intended to help with this.

**Comment by fernando-jose-silva** [comment]
Thank you very much for your support.
I am new to using google docs, I am using this software package due to needs in my work where they are replacing the microsoft package with google.

Braille-enabled support addresses the issue.

I think it would be interesting for someone to position us if so-called # 7935 would solve this problem.
If not, my suggestions would be to solve these problems without braille support being enabled.
Or document in nvda's help that for better performance braille support is enabled (logically if this does not lead to major issues as you reported in the difficulty of navigating tables if this braille support is enabled.

**Comment by ehollig** [comment]
Closing as worksforme
