### ISSUE TITLE
brakage in Thunderbird 60

### ISSUE THREAD

**Issue by tapper82** [nvaccess/nvda#7951]
### Steps to reproduce:
Open Thunderbird 60 and the tree view will not read back.
### Expected behavior:
You should be able to read the email folders.
### System configuration:
NVDA version:
14828,517b1ebc
Fri Feb 2 01:07:39 2018
NVDA Installed or portable:
Installed
Windows version:
windows 1064 bit

**Comment by leonardder** [comment]
Is there something that makes you think this is NVDA specific? Note that Thunderbird 60 is still in Beta or even Nightly, so it is most likely a temporary breakage. The best place to report this issue might be the Thunderbird issue tracker.

I'm tempted to close this, but will leave it open for people to report additional findings.

**Comment by Adriani90** [comment]
@tapper82 are you still having this problem? @bdorder, @novalis7747 as far as I know it works well in Thunderbird. Right?

**Comment by tapper82** [comment]
No all is fixt now. both FF and TB work as they should. You can close. Thanks.

**Comment by Adriani90** [comment]
Closing as works for me.
