### ISSUE TITLE
focus will be backed to the start of the content in chrome.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#7955]
Hi:
Browse in this webPage is impossible with focus controled by arror keys. Because the focus will be restore in the start point of the content. Please open the address: https://www.zhihu.com/question/58178068
Press 4 to navigate to the first header level four
Sorry, it's a Chinese page. 
chrome version:63.0.3239.108
windows 10 version:16299.192

**Comment by Adriani90** [comment]
This is resolved in Google Crome 71.0. I suggest closing it.

**Comment by ehollig** [comment]
This works correctly for me using Chrome 71 as well.

1. Open the following in Chrome: https://www.zhihu.com/question/58178068
2. Press 4 to move to the heading level 4 on the page.
3. Press down arrow a couple of times and focus will remain in the middle of the page.

Closing as worksforme
