### ISSUE TITLE
Context Menus Not Reading

### ISSUE THREAD

**Issue by ThomasStivers** [nvaccess/nvda#7958]
### Steps to reproduce:
1. Move to a desktop icon and either select it or leave it unselected.
2. Open the context menu with the Applications key or Shift+F10.

### Expected behavior:
NVDA should speak items on the context menu.

### Actual behavior:
NVDA remains silent and the following log entries are generated when moving up and down the context menu.

IO - inputCore.InputManager.executeGesture (07:57:21.270):
Input: kb(desktop):applications
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (07:57:21.630):
oleacc.AccessibleObjectFromEvent with window 1376602, objectID -4 and childID 0: [Error -2147312566] Error loading type library/DLL
IO - inputCore.InputManager.executeGesture (07:57:22.191):
Input: kb(desktop):downArrow
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (07:57:22.214):
oleacc.AccessibleObjectFromEvent with window 1376602, objectID -4 and childID 1: [Error -2147312566] Error loading type library/DLL
IO - inputCore.InputManager.executeGesture (07:57:23.176):
Input: kb(desktop):downArrow
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (07:57:23.207):
oleacc.AccessibleObjectFromEvent with window 1376602, objectID -4 and childID 2: [Error -2147312566] Error loading type library/DLL
IO - inputCore.InputManager.executeGesture (07:57:24.960):

### System configuration:
NVDA version:
next-14828,517b1ebc

NVDA Installed

Windows version:
Windows 10 1709 (OS Build 17074.1002)

### Other questions:

Does the issue still occur after restarting your PC?
Yes.

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by dkager** [comment]
Probably a duplicate of #2807.

To try and confirm this: did you uninstall any software before this problem started to occur?

**Comment by ThomasStivers** [comment]
I haven’t uninstalled anything, I did update Office, but did not uninstall.

**Comment by josephsl** [comment]
Hi, I think this is rather a duplicate of an issue raised not long ago regarding introduction of Sets. Thanks.

**Comment by ThomasStivers** [comment]
I finally updated to insider build 17101 and that fixed the problem.
