### ISSUE TITLE
Not receiving files or messages in wlm by pressing enter, also with url adresses

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#796]
**Reported by ManuelRamos on 2010-07-31 20:12**
When we are using NVDA with Windows Live Messenger and we want to receive a vocal message or file transfer, by pressing enter file or message are not being accessed. Also, when pressing enter to open an url adress, sent via windows live messenger

**Comment by leonardder** [comment]
WLM is abandoned, closing as won't fix.
