### ISSUE TITLE
properly marked up wai-aria checkbox double speaks labels in 2017.4 but not in 2017.3 

### ISSUE THREAD

**Issue by DavidMacDonald** [nvaccess/nvda#7960]
### Steps to reproduce:

 1. Open Chrome
 2. Browse to  https://www.w3.org/TR/wai-aria-practices-1.1/examples/checkbox/checkbox-1/checkbox-1.html
 3. press tab until you come to the example
4. Notice that the label is spoken twice. 

### Expected behavior:
It should speak once each label on tab focus

### Actual behavior:
It spoke the label twice

### System configuration:
NVDA version:
2017.4

NVDA Installed on WIN 10

Windows version:
Windows 10 

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
Version 2017.3 was OK on the same example. PS JAWS 2018 and VoiceOver speak the label properly once

**Comment by feerrenrut** [comment]
I can reproduce this with a recent next build, the same symptom as #7948 although the markup used is different.

Confirmed that the checkbox label is not spoken twice when using NVDA 2017.3

**Comment by michaelDCurran** [comment]
Regression caused by PR #7513.

**Comment by fANZYo** [comment]
This was not fixed. It seems like having a checkbox inside a label tag with `position: relative;` makes NVDA read the the label twice. Removing `position: relative;` solves the problem but prevents way too many styling to be an acceptable solution.
