### ISSUE TITLE
Allow appModules to prefer UIA for certain windows

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7961]
It is currently possible to implement isBadUIAWindow on the appModule level to use IAccessible for windows that are reported as native UIA. I also propose the opposite of this feature, i.e. an isGoodUIAWindow function that takes a window handle as a parameter and returns True if UIA should be used in all cases. I think this feature can be justified as follows:

1. It seems there are windows that do not report as native UIA even though they are, for example the window class of the Windows Defender Application Guard.
2. It makes it much easier to inspect within NVDA how an application behaves is UIA is used for a particular control.

Other arguments welcome of course. CC @dkager @michaeldcurran @josephsl

**Comment by bramd** [comment]
Sounds reasonable to me, but it might be better to combine these two methods to a useUIAForWindow method that returns True/False?

**Comment by leonardder** [comment]
[**@bramd**](https://github.com/bramd) commented on [7 Feb 2018, 19:49 CET](https://github.com/nvaccess/nvda/issues/7961#issuecomment-363870349 "2018-02-07T18:49:07Z - Replied by Github Reply Comments"):
> Sounds reasonable to me, but it might be better to combine these two methods to a useUIAForWindow method that returns True/False?

That would be problematic if the appModule wants to leave the decision to core instead. We also want to keep isBadUIAWindow for backwards compatibility.
