### ISSUE TITLE
UIA in Word: bullet not shown for empty list item

### ISSUE THREAD

**Issue by bramd** [nvaccess/nvda#7970]
### Steps to reproduce:

1. Make sure the experimental UIA support for Word is enabled
2. Open Word
3. Press ctrl+shift+l to start a list
4. Read the current line (numpad 8/nvda+l)

### Expected behavior:

* The bullet is read
* The bullet is displayed in braille

### Actual behavior:

* An empty line is read
* Nothing is displayed in braille

### System configuration:
NVDA version: next-14836,ba6e22c8
NVDA Installed

Other information:

* As soon as text is typed, the bullet is displayed/read correctly
* Also reproduceable with numbered lists
* Also occurs when adding a new item to an existing list (e.g. pres enter at the end of a list item)

Windows version: Windows 10 Version 1709 (OS Build 16299.214)

Name and version of other software in use when reproducing the issue:

* Microsoft Word Version 1801 (Build 9001.2138 Click-to-Run) (Office 365)

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No

**Comment by dkager** [comment]
Confirmed. Also when you type a dash or asterisk to start a list, that character disappears as soon as you press space and the bullet appears when you start typing further text.

**Comment by dkager** [comment]
CC @michaelDCurran

**Comment by michaelDCurran** [comment]
Technical:
When on the last line of a document and it is blank, expanding to line fails, even if there is a bullet there.
A way to work around this might be to check if the range is still collapsed, and if so, then move the end of the range to the end of the document.
But, we'd only want to do this in MS Word as it does add an extra call.
We'd really prefer that Microsoft fix this at some point of course.
