### ISSUE TITLE
UIA in Word: incorrect cursor position on bullets in lists and broken braille routing

### ISSUE THREAD

**Issue by bramd** [nvaccess/nvda#7971]
### Steps to reproduce:

1. Make sure the experimental UIA support for Word is enabled
2. Open Word
3. Press ctrl+shift+l to start a list
4. Type some text
5. Press home

### Expected behavior:

* The cursor is displayed on the first character after the bullet in braille
* Report current character (numpad 2 on desktop) speaks the character after the bullet

### Actual behavior:

* The cursor is displayed on the bullet in braille
* The bullet and the following character is read

### System configuration:
NVDA version: next-14836,ba6e22c8
NVDA Installed

Other information:

* Also reproduceable with numbered lists
* When placing the caret on the bullet, the same bullet and character is reported, instead of just the bullet
* Due to these strange navigation issues, cursor routing doesn't work correctly in a list item

Windows version: Windows 10 Version 1709 (OS Build 16299.214)

Name and version of other software in use when reproducing the issue:

* Microsoft Word Version 1801 (Build 9001.2138 Click-to-Run) (Office 365)

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No

**Comment by leonardder** [comment]
[**@bramd**](https://github.com/bramd) commented on [7 feb. 2018 21:14 CET](https://github.com/nvaccess/nvda/issues/7971#issue-295276929 "2018-02-07T20:14:01Z - Replied by Github Reply Comments"):
> Expected behavior:

Is this based on the old situation (i.e. without UIA enabled), or on something else? I just want to make sure that the UIA implementation is doing things wrong and not the object model implementation that has done things wrong all the time.

> * Due to these strange navigation issues, cursor routing doesn't work correctly in a list item

Could you elaborate on this a bit more? I assume when you press the cursor routing at the cell containing the first character after the bullet, the cursor is placed on the bullet itself?

@qchristensen/@feerrenrut: I think it would help to have some sighted person report where the cursor ends up on screen when executing the steps to reproduce.

**Comment by leonardder** [comment]
@bramd commented on 7 feb. 2018 21:14 CET:

> Expected behavior:

Is this based on the old situation (i.e. without UIA enabled), or on something else? I just want to make sure that the UIA implementation is doing things wrong and not the object model implementation that has done things wrong all the time.

> * Due to these strange navigation issues, cursor routing doesn't work correctly in a list item

Could you elaborate on this a bit more? I assume when you press the cursor routing at the cell containing the first character after the bullet, the cursor is placed on the bullet itself?

@qchristensen / @feerrenrut: I think it would help to have some sighted person report where the cursor ends up on screen when executing the steps to reproduce.

**Comment by dkager** [comment]
Yes, in the pre-UIA implementation the cursor would not go onto the bullet or the single space after it. So in "<bullet> Hello", the cursor would go to the H when pressing Home.

**Comment by dkager** [comment]
CC @michaelDCurran
