### ISSUE TITLE
<form> element with accessible labels (aria-labelledby, aria-label, title) are not detected as form landmarks

### ISSUE THREAD

**Issue by iamrafan** [nvaccess/nvda#7972]
### Steps to reproduce:

1. Open the attached file [html5-form-with-label-not-detected-as-landmark.zip](https://github.com/nvaccess/nvda/files/1705135/html5-form-with-label-not-detected-as-landmark.zip) in Chrome
2. Open NVDA
3. Open the elements list dialog (NVDA key + F7) on the page opened in chrome
4. Navigate to the landmarks radio button on the elements list dialog
5. Notice that only from landmark created only using [role=form] is present in the list.

### Expected behavior:
 Cases 5, 6, 7 should be considered as form landmarks
>Do not consider case 2, 3 ,4 as form landmarks

### Actual behavior:
Case 5,6,7 are not  detected as a form landmarks

### System configuration:
NVDA version: 2017.4
NVDA Installed

Windows version: Windows 10 Version 1709 Build 16299.192

**Comment by scottaohara** [comment]
FYI.  I opened this issue over on the [JAWS bug tracker](https://github.com/FreedomScientific/VFO-standards-support/issues/52) and we found it to be that the browsers themselves were not relaying this information in the accessibility tree.

Bugs were filed with Firefox and Chrome respectively to address this.

**Comment by iamrafan** [comment]
thanks for the update

**Comment by Adriani90** [comment]
This works as expected in Firefox. But it is still reproducible in Chrome 74 with NVDA 2019.1.1.

**Comment by Adriani90** [comment]
@scottaohara could you please post here the links to the bugs you have filled with Firefox and Chrome, so that we can track the current progress on that?

**Comment by scottaohara** [comment]
steve faulkner opened the firefox bug - https://bugzilla.mozilla.org/show_bug.cgi?id=1442196

chrome bug - https://bugs.chromium.org/p/chromium/issues/detail?id=818428

**Comment by Adriani90** [comment]
@feerrenrut, @michaelDCurran it seems from the chrome bug that this is actually properly exposed. Is this something should be considered in the landmark navigation when pressing d in browse mode at least?

**Comment by Adriani90** [comment]
cc: @SaschaCowley

**Comment by SaschaCowley** [comment]
Cases 5, 6 and 7 are recognised as forms for me with Chrome 127.0.6533.72 or Firefox 129.0B8 and NVDA alpha-32997,3f82ab67.
