### ISSUE TITLE
Errors while trying to download the latest nvda next

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7979]
During the last weeks I noticed a problem when trying to download the nvda next using a browser.
The download starts more is interrupted, being necessary to restart the file download for 4 or more times until you can download the file successfully.
I tested it on two different computers, with windows 10 16299.192 and windows 7, using firefox 58 or chrome 64.
And I also tested two different internet connections, one in my work and the other in my home.
Sorry if I'm not posting this in a correct location.
Is there not a problem with nv acces servers that might be causing this.
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
Open the page
https://www.nvaccess.org/files/nvda/snapshots/
Start downloading any version next to nvda.

### Expected behavior:
The file must be downloaded without interruption

### Actual behavior:
The download starts more and is interrupted several times before you can download the file completely.

### System configuration:
NVDA version:
When trying to download any next in the last weeks

Other information:
Tried on two different connections and geographically distant.
Tried on two different machines and browsers.
Other downloads from other locations occur without problems.

Windows version:
> Example: Windows 10 Version 1709 Build 16299.192, windows 7.

Name and version of other software in use when reproducing the issue:
chrome 64, firefox 58
### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result
next.

**Comment by Brian1Gaff** [comment]
Hmm, so this is a manual download. I have to say I just tested it here in 
ff52esr with no issues. maybe its a problem between where you are and the 
server which has the file.
 I have seen this on other downloads in the past, after an hour or so you 
suddenly find its working.
 If not then maybe somebody else can shed some light on it for you. One 
assumes other files download ok?
 Brian

**Comment by fernando-jose-silva** [comment]
Thank you very much.
Other downloads from other sources are ok.
Let's see if anyone else has this problem, or if it's something with the connection in this region.
It is not just a connection problem because I have tested on two separate connections separated by a few kilometers.

**Comment by feerrenrut** [comment]
There was an issue with the NV Access server which should now be resolved. I will close this issue for now. Please reopen it or comment if the issue continues.

**Comment by fernando-jose-silva** [comment]
Hello everyone.
You can check if there is anything else that can be done, unfortunately I still have problems downloading nvda next directly through the page, it continues with the download interrupting several times before I can successfully complete it.
Again tested on multiple connections.
Thank you very much for your attention.
