### ISSUE TITLE
NVDA does not report tabs when pressing tab in grafic settings in MS Outlook 2016

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7987]
### Steps to reproduce:
1. Open an e-mail which contains a screenshot in Outlook 2016 
2. Select the screenshot image
3. Press the application key or right click
4. Got to grafic settings
5. Navigate the dialog by tab and shift+tab

### Expected behavior:
NVDA should report the current selected tab when navigating with tab through the dialog (i.e. position tab)

### Actual behavior:
NVDA reports the currently selected tab only when pressing shift+tab, but not when pressing tab.

### System configuration:
NVDA version:
2017.4

NVDA Installed or portable:
Both

Other information:

Windows version:
Windows 10 Build 16.299.64

Name and version of other software in use when reproducing the issue:
MS Outlook 2016

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No.

**Comment by PratikP1** [comment]
Can you clarify whether or not the image is attached or embedded into the email body?

**Comment by Adriani90** [comment]
It is enbeded.  

Von meinem iPhone gesendet

**Comment by Adriani90** [comment]
This works as expected with NVDA 2019.1.1. closing as works for me.
