### ISSUE TITLE
Lotus Notes Freezes NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#80]
**Reported by msuch on 2008-04-30 08:38**
As you are about to release 0.6p3, you may want to know that this is not solved up to revision 2574.

Whenever I alt-tab to Lotus Notes, it simply stops speaking, yet continues recording informations in NVDA.log, that I have attached yesterday for info.

**Comment by leonardder** [comment]
Lotus Notes is now IBM Notes I belief. I've done some basic things with it and I don't recall crashes in the messages list, only in a third party application within notes which had a broken a11y implementation anyway.

**Comment by jcsteh** [comment]
Closing as worksforme then, but we can reopen if this still persists for some users.

**Comment by elpagano** [comment]
I tested it with the version of nvda 2010 from https://sourceforge.net/projects/nvda/files/releases/ and had no problems. the problem is with the newer ones, with the 2014 version if it crashed, something changed between versions that makes lotus crash.
