### ISSUE TITLE
NVDA is not able to read system menu in Windows10 pressing Windows+x

### ISSUE THREAD

**Issue by dreinn** [nvaccess/nvda#8008]
Using Microsoft Windows [Versione 10.0.17074.1002], and NVDA next-14860,d6c75234

If I press Windows+x to open the contest menu where you have many system options, NVDA said simply "unknown".

Narrator instead is able to read everything.

Whats is happening?

Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states: STATE_INVISIBLE, STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.IAccessible.ContentGenericClient object at 0x05E8D350>
Python class mro: (<class 'NVDAObjects.IAccessible.ContentGenericClient'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (0, 0, 0, 0)
value: u''
appModule: <'explorer' (appName u'explorer', process ID 7068) at address 5aa79b0>
appModule.productName: u'Sistema operativo Microsoft\xae Windows\xae'
appModule.productVersion: u'10.0.17074.1002'
TextInfo: <class 'displayModel.DisplayModelTextInfo'>
windowHandle: 2032808
windowClassName: u'LauncherTipWnd'
windowControlID: 0
windowStyle: -2080374784
windowThreadID: 7968
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x8252e8 at 5eb6080>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=2032808, objectID=-4, childID=0
IAccessible accName: None
IAccessible accRole: ROLE_SYSTEM_CLIENT
IAccessible accState: STATE_SYSTEM_INVISIBLE, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1081348)
IAccessible accDescription: None
IAccessible accValue: None

**Comment by josephsl** [comment]
Hi,

Yet another duplicate (trying to find the actual ticket). In short, Sets feature may have contributed to this. This is resolved in build 17083 and later.

Thanks.

**Comment by josephsl** [comment]
Hi,

Thje closest issue found is #7958. Thanks.

**Comment by dreinn** [comment]
ok sorry for the duplicate, I should search before post a bug! Still sorry

2018-02-17 1:31 GMT+01:00, Joseph Lee <notifications@github.com>:
> Hi,
>
> Thje closest issue found is #7958. Thanks.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/8008#issuecomment-366397484


-- 
Simone Dal Maso
www.nvapple.it
www.nvda.it
