### ISSUE TITLE
UIA support: choose the highest IUIAutomation interface version based on Windows release in use

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8009]
Hi,

This is a more general case based on #7984:

Due to the fact that Microsoft comes out with new Windows 10 releases twice a year, and given that these releases may include UIA changes from time to time, and since some methods (such as notification event handler) requires newer Windows 10 releases, I propose that we use highest supported IUIAutomation interface based on Windows release one is using. As of 2018, the interface versions are:

* Windows 7: IUIAutomation 1
* Windows 8: IUIAutomation 2
* Windows 8.1: IUIAutomation 3
* Windows 10 Version 1607: IUIAutomation 4
* Windows 10 Version 1709: IUIAutomation 5

Benefits:

* Allows NVDA and its add-ons to take full advantage of latest UIA methods and properties.
* Allows NVDA to stand out, especially if run as Windows Store app so it can work with more UIA events, methods, properties and what not.
* Allows NV Access and Microsoft to work together to patch UIA miscommunications.

Drawbacks:

* One must keep an eye on UIA changes between Windows releases, especially due to more frequent releases for Windows 10.
* Extensive testing must be required in order to make sure regressions are not found.
* More collaboration will be required to work through misunderstandings between NV Access and Microsoft regarding uIA specs, expectations, bugs, feature suggestions and what not.

If this suggestion is adopted:

1. UIA handler will try with IUIAutomation 5, and if not, fall back to version 4 or earlier.
2. If we're using Windows 8.x, use IUIAutomation 3. I recommend against using version 2 unless required given end of support for Windows 8.0.
3. If using Windows 10, based on build range, use IUIAutomation 3, 4, or 5. To do this, check build number. If it is less than 14393, use 3; between 14393 and 15063 is 4; 16299 and later (unless it changes) is version 5.
4. In order to test this, one might wish to compile NVDA from source and use a binary version so NVDA can detect Windows 8.1 and later.
5. Have one or two developers keep an eye on UIA changes. It doens't have to be Mick keeping an eye on this all the time; it could be someone else and alert NV Access if UIA changes must be included.
6. Ideally, UIA changes should be committed in the next NVDA release following the Windows 10 release that includes a newer IUIAutomation version. For example, if Windows 10 Version 1809 (October 2018) includes IUIAutomation version 6, NVDA 2019.1 should include support for the new interface. In case of version 5, I propose 2018.2 as the target release.

Comments are appreciated. Thanks.

**Comment by josephsl** [comment]
CC @MichaelDCurran, @LeonardDer, @DerekRiemer, @PratikP1, and any MS staff and Windows Insiders

**Comment by leonardder** [comment]
[**@josephsl**](https://github.com/josephsl) commented on [17 Feb 2018, 07:08 CET](https://github.com/nvaccess/nvda/issues/8009#issue-297982865 "2018-02-17T06:08:55Z - Replied by Github Reply Comments"):
> 3. If using Windows 10, based on build range, use IUIAutomation 3, 4, or 5. To do this, check build number. If it is less than 14393, use 3; between 14393 and 15063 is 4; 16299 and later (unless it changes) is version 5.

The current implementation just tries to query interfaces until a working interface has been found. I guess that on Windows 8.1, `uiaHandler.handler.clientObject.QueryInterface(IUIAutomation5)` will just fail, right? So, why should we use an alternative approach based on build numbers here?

**Comment by josephsl** [comment]
Hi, theoretically, on Windows 8.1, attempting to use version 5 will fail. This is fine, because UI Automation version won’t change over there. But on Windows 10 series, if it fails, then we need to keep trying until a valid interface version is found, which is a tedious task. Therefore I propose a possible shortcut by querying build ranges. Thanks.

**Comment by leonardder** [comment]
I think doing some timing tests regarding querying interfaces would be good here. Ib we ale going to use UIA5 for some core functionalities, we don't want to rely on binary voices to test things, as that would be a major decline in development experience.

**Comment by josephsl** [comment]
Hi,

Update: success - NVDA can track notification events, although it is unlike anything we've seen so far, as this event lets screen readers respond differently based on notification kind, processing constant, activity ID and what not. I'll come up with a prototype implementation via a PR soon.

Thanks.

**Comment by josephsl** [comment]
Hi,

As part of this work, a new function named getIUIAutomationInterface will be added to UIA handler module. The job of this function is to return the highest supported IUIAutomation interface. By default, it'll return version 3, as NVDA will fall back to version 2 if this function does not return appropriate interface.

The data to be returned:

* Windows 8.1: IUIAutomation3
* Windows 10 build 14393 and later: IUIAutomation4
* Windows 10 build 16299 and later: IUIAutomation5

For sake of completeness, IUIAutomation (version 1 on Windows 7) and IUIAutomation2 (Windows 8.0) will be returned so add-ons can query which uIA interface is available. This should also help other future Core work such as detecting more patterns.

Thanks.

**Comment by josephsl** [comment]
Hi,

Change of spec: build range won't be used anymore, otherwise IUIA5 isn't usable in source code version. See #8045 for a more thorough discussion of a proven alternative.

Thanks.

**Comment by josephsl** [comment]
Hi,

Now that we are using Python 3, it becomes possible to debug UIA issues from source code. Therefore I'm closing this.

Thanks.
