### ISSUE TITLE
Update copyright year in about

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#8012]
in the about dialog, NVDA says:
Copyright (C) 2006-2017 NVDA Contributors

it should say 
Copyright (C) 2006-2018 NVDA Contributors

Also, should that be NV Access Limited? CC @michaelDCurran @feerrenrut @Qchristensen

**Comment by jcsteh** [comment]
It can't be NV Access Limited alone, since others own some of the copyright. We've debated on and off whether to explicitly mention NV Access Limited here. If we're going to, I'd suggest:

`Copyright (C) 2006-2018 NV Access Limited & other contributors`

**Comment by Brian1Gaff** [comment]
From looking at other software that is mostly what they do and sometimes 
refer to more detailed doccs in the distribution if clarification is 
required.
 Brian

**Comment by michaelDCurran** [comment]
Just fixing copyright year for now as that does not break translations.
