### ISSUE TITLE
Improve support for Chromium, useful for people working on bloomberg terminals

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8027]
Dear all,

is it possible to improve support for this project?
https://github.com/bloomberg/chromium.bb

This is the browser used hwen working in bloomberg. It would help many users who want to apply for jobs in finance.

I will test it on my work and provide you with more feedback on what exactly is not working. But it would be good if some people here can test it too.

Thanks.

**Comment by leonardder** [comment]
Honestly, I consider this issue to be too broad in scope. If you find some problems with this software and if you believe that things should be fixed on the NVDA side, it might be better to post them all in separate issues, so it will be easier to keep track of them.

**Comment by dkager** [comment]
I agree. The motivation is clear, but the scope is too broad. A request for users to test the application may be more suitable for the users mailing list.
As this appears to target potential future users, not current users, the priority would probably not be as high as, say, Microsoft Office issues.

**Comment by leonardder** [comment]
Closing this as invalid. @Adriani90, please open a new issue if you think that a particular issue with this software may have to do with how NVDA deals with it.
