### ISSUE TITLE
IE11+nvda problem with SVG filter

### ISSUE THREAD

**Issue by kentxu** [nvaccess/nvda#8034]
### Steps to reproduce:
1. open IE 11
2. run the attached simple html file
3. press down key to switch focus to the text
4. the visual of the svg area is shifted

### Expected behavior:
should not shift the svg,  similar to how chrome+nvda behaves

### Actual behavior:
svg visually shifted

### System configuration:
NVDA version:2017.4

NVDA Installed or portable: 
installed

Other information:
kinda works if I remove "overflow:hidden" from the top level div, or if I do not use the svg filter.

Windows version:
windows 10 latest (as of today)

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
N/A

Have you tried any other versions of NVDA?
no
[test508_svgfilter_NVDA.html.zip](https://github.com/nvaccess/nvda/files/1754188/test508_svgfilter_NVDA.html.zip)

**Comment by Adriani90** [comment]
cc: @Qchristensen could you please test from a sighted perspective? I guess it will be quite unlikely that NV Access will invest time in solving this but I do not exactly understand this issue though.
cc: @leonardder

**Comment by Qchristensen** [comment]
Without looking at the code, I'm not sure exactly what is going on, but visually here's what's happening:

- When the page loads, it presents a large white rectangle, with a grey rectangle inside it, and the text ddd inside that, with a bit of space between the text and the top-left edge of the rectangle.

- When down arrow is pressed, The grey rectangle suddenly moves to the top left of the white rectangle, and the text moves to the very top left of the grey rectangle.

This doesn't happen in other browsers, or without NVDA running (or with Narrator running).

**Comment by Adriani90** [comment]
IE11 support has ended and with an Edge update in February 2023, the Internet explorer has automatically been removed from any Windows computer that still had it. Since this issue is only related to IE I am closing it.
