### ISSUE TITLE
NVDA with opera

### ISSUE THREAD

**Issue by ghost** [nvaccess/nvda#8040]
When I downloaded opera, I've tested it with both jaws and NVDA! here's the problem! when you launch the browser, press your alt key on the right of your spacebar, NVDA nor jaws says nothing, now when you hit your alt key, on the left side of your spacebar, jaws and NVDA says menu, because the menu actualy pops up. This needs to be addressed, I can reproduce this problem, everytime.

**Comment by leonardder** [comment]
Hey,

Do I understand it right that the right alt key never works and the left alt key works always?

What happens if you enable NVDA keyboard help (nvda+1) and press the right alt key? HOw is it announced?

**Comment by Qchristensen** [comment]
This seems to be the behaviour of Opera itself and nothing to do with NVDA.  Running Opera without any screen reader running, the left ALT key opens Opera's menu, and the right ALT key does nothing.

If you would like to change that functionality, you'll need to talk to the Opera developers.

Closing as NeedsExternalFix.
