### ISSUE TITLE
Updating an aria-atomic live region in Chrome makes NVDA speak old text

### ISSUE THREAD

**Issue by ladipro** [nvaccess/nvda#8044]
### Steps to reproduce:
Load the following markup in Chrome and update the div's innerText with JavaScript to "New text":
```
  <div
    aria-live="polite"
    aria-atomic="true"
    aria-relevant="text"
    style="white-space: pre">Old text</div>
```

### Expected behavior:
NVDA speaks "New text".

### Actual behavior:
NVDA speaks "Old text", "Old text", "New text"

### System configuration:
NVDA version: c83231ec6e31bb19e5a25d9b0442f019a7a13e73 

NVDA Installed or portable:
portable/built out of sources

Other information:
Chrome Version 64.0.3282.140 (Official Build) (64-bit)

Windows version:
Windows 10 Version 1709 Build 16299.248

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
Yes, 2017.4 official release.

**Comment by derekriemer** [comment]
@ladipro Thanks for your work. if this is your first PR, (I think it is), welcome.

**Comment by feerrenrut** [comment]
I can't reproduce this issue with `Google Chrome 80.0.3987.162` or `Firefox 74.0 (64-bit)` and the following sample:

```
<h2>Atomic=True live region</h2
<div>
	<div id="e1" aria-live="polite" aria-atomic="true">Old text</div>
</div>
<button onclick="document.getElementById('e1').innerText = 'New Text'" >Replace Text</button>
```

@ladipro Perhaps this is fixed, or my approach is different from what you intended?

**Comment by ladipro** [comment]
Apologies for the delay, I am not involved with the project where this issue was discovered anymore.

The issue indeed appears to be fixed, confirming no repro in this environment:

Chrome version 80.0.3987.149 (Official Build) (64-bit)
NVDA version 2019.3.1

**Comment by feerrenrut** [comment]
Great, thanks for confirming @ladipro
