### ISSUE TITLE
Navigational keys SHIFT and SELECT are not working on Focus Blue braille displays

### ISSUE THREAD

**Issue by xtstoll** [nvaccess/nvda#8053]
### Steps to reproduce:
> 1. Install [driver](https://www.freedomscientific.com/Downloads/Focus/FocusBlueBrailleDisplayDriver) for Focus Blue braille displays
> 2. Start NVDA and configure the braille settings for the Freedom Scientific Focus (see my configs attached in screenshot)
> 3. Open a simple text editor like Notepad
> 4. Write a sentence
> 5. On the Focus Blue, press the LEFT SHIFT key on the front panel and one of the CURSOR
ROUTER buttons to select some text, then press LEFT SHIFT + DOTS 1-4 (c in braille) to copy
> 6. On the Focus Blue, press the SELECT BUTTON and the LEFT PANNING BUTTON to go to the beginning of the file
> 7. On the Focus Blue, press the LEFT SHIFT + DOTS 1-2-3-6 (v in braille) to paste

### Expected behavior:
> Step 5: LEFT SHIFT + CURSOR ROUTER should select your text from the blinking cursor to point of the router button and LEFT SHIFT + DOTS 1-4 (c in braille) should copy your selected text
> Step 6: SELECT BUTTON + LEFT PANNING BUTTON should send your cursor to the beginning of the file
> Step 7: LEFT SHIFT + DOTS 1-2-3-6 (v in braille) should paste your copied text

### Actual behavior:
> Step 5: LEFT SHIFT + CURSOR ROUTER - text is selected (OK); LEFT SHIFT + DOTS 1-4 - it's not clear until Step 7 that it didn't actually copy
> Step 6: SELECT BUTTON + LEFT PANNING BUTTON - nothing happens
> Step 7: LEFT SHIFT + DOTS 1-2-3-6 (v in braille) - nothing happens

### System configuration:
NVDA version: 2018.1rc1 (Brazilian Portuguese)
NVDA Installed or portable: installed
Windows version: 10
Braille display: Focus 80 Blue and Focus 40 Blue
Focus Blue driver: version 1.0.2030

Does the issue still occur after restarting your PC? Yes
Have you tried any other versions of NVDA? Yes, 2017.4 (Brazilian Portuguese), same results

![nvda_2018-03-02_10-14-18](https://user-images.githubusercontent.com/24814666/36900965-146c82aa-1e04-11e8-8d12-02ecce5bf230.png)

**Comment by dkager** [comment]
> LEFT SHIFT + CURSOR ROUTER should select your text from the blinking cursor to point of the router button

This doesn't even work with the Shift key on the keyboard, so I'm a bit surprised it works with this driver.

The other commands could be added. Do you have a document that describes the expected key assignments from Freedom Scientific?

CC @bramd

**Comment by xtstoll** [comment]
It would be really great if this would work! 😸 

The full list by Freedom Scientific is here:
https://www.freedomscientific.com/Content/Documents/Manuals/Focus/Focus80Blue/Focus-80-Blue-Online-Users-Guide.htm#commandsoverview

If I had to list the order of importance of these tables, I would say:

1. Modifier Keys
2. Special Keys
3. Navigation Commands
4. Text Selection Commands
5. Windows Commands
6. Selection Commands
7. Braille Commands
8. Microsoft Word Navigation Quick Keys

If you have any questions, I'm here to help! 💪

In Brazil, we have lots of people using Focus Blue displays with NVDA (the most popular screen reader in Brazil), so I would love to see better compatibility between NVDA and these Focus Blue braille displays.

**Comment by leonardder** [comment]
cc @bramd

**Comment by bramd** [comment]
Thanks for the list. I'll see what I can implement when I am able to 
work on the new driver some more.

**Comment by bramd** [comment]
Many of these keys require layered key combinations, where a certain key can be simulated by pressing a series of braille commands. We don't have good support for this right now.

Also, we don't have support for functions combining routing buttons with other keys. This should be implemented in a more generic way for all braille displays. I would be glad to revisit this issue and implement the key bindings in the Freedom Scientific driver if this support is available in NVDA's input handling.

**Comment by Adriani90** [comment]
@xtstoll, @dkager, @bramd, @burmancomp is this issue still reproducible with NVDA 2024.1?

**Comment by Adriani90** [comment]
We didn't get any updates upon request since many years, whether this issue is still reproducible or not. I am closing as abandoned. If you are still having this issue, please comment and we can reopen.
