### ISSUE TITLE
Auto-completing e-mail addresses in Microsoft Outlook can cause an error

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#8055]
### Steps to reproduce:
1. Enable braille output in NVDA.
2. In Outlook 2016, start a new e-mail.
3. In the To, Cc or Bcc fields, start typing an e-mail address that is in an auto-complete list, e.g. the address book.

### Expected behavior:
The auto-completed address is announced through a `ui.message`.

### Actual behavior:
```
ERROR - eventHandler.executeEvent (17:40:41.236):
error executing event: stateChange on <appModules.outlook.AutoCompleteListItem object at 0x06E8AE90> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 152, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 107, in next
  File "extensionPoints.pyc", line 135, in callWithSupportedKwargs
  File "appModules\outlook.pyc", line 343, in event_stateChange
  File "ui.pyc", line 67, in message
  File "braille.pyc", line 1676, in message
  File "braille.pyc", line 1296, in update
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

### System configuration:
NVDA version: master-14897,4faf0d05

Windows version: 10.0.16299

Outlook version: 16.0.9029.2106

**Comment by leonardder** [comment]
I'm afraid I can't reproduce this. Is this reproducible when you change the tethering setting to something else?

**Comment by dkager** [comment]
I can't always reproduce either, but I mostly can by typing quickly and entering a name from the list of suggested contacts Outlook knows I e-mailed before.

**Comment by dkager** [comment]
Also reproduced in Outlook 2013. I suppose a quick fix is to ignore empty messages in `ui.message`.

**Comment by dkager** [comment]
I can't seem to reproduce this in Outlook 2016 with NVDA 2018.2.1 anymore, but since the fix is so small it probably won't hurt to add it.
