### ISSUE TITLE
No formatting information in Word with nvda_snapshot_rc-14903,a98e77cc.exe

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#8061]
When asking for formatting information for the current review cursor position in Word files with both release candidates I am frequently being told, "No formatting information".  This seems not to be an issue in Outlook emails.  This has happened occasionally in earlier versions, but a restart of NVDA usually fixes.

**Comment by ehollig** [comment]
I am not able to reproduce this using 18.1RC2 or the latest Master. Does this still occur for you @andrew-l-d? Could you provide a log with debugging set to debug demonstrating this issue?

**Comment by andrew-l-d** [comment]
Apologies!  Recently Clutz turned off review cursor follows caret for a specific purpose and forgot to turn it back on.  This issue can be closed (slaps wrist).

**Comment by leonardder** [comment]
Thanks for investigating. Closing this issue.
