### ISSUE TITLE
NVDA does not report page in kindle

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8062]
Dear all,

I am trying to find out on which page I am when reading books in kindle. NVDA does not report it.

**Comment by PratikP1** [comment]
Current page information is announced when the book is opened. In addition, this information is also announced when arrowing through the content to move across the boundary from page to page. Page number is also announced if the page up/down keys are used to move by extra content. There is no way to interrogate the application to see the current page number however. This feature, if feasible, can add efficiency to the reading process—especially in academic settings.

**Comment by Adriani90** [comment]
With NVDA 2018.1 RC2, Windows 10.16299.64 and Kindle for PC 1.21.0, pages are not reported by NVDA when navigating with arrow keys or page upt and down. I have tested with 5 books. Could it depend on which book I am using? Might this information be stored in the metadata of the book?

 

However, your proposed function would be very helpful though, actually I would prefer it.

 

 

Von: PratikP1 <notifications@github.com> 
Gesendet: Mittwoch, 7. März 2018 14:45
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Author <author@noreply.github.com>
Betreff: Re: [nvaccess/nvda] NVDA does not reporth page in kindle (#8062)

 

Current page information is announced when the book is opened. In addition, this information is also announced when arrowing through the content to move across the boundary from page to page. Page number is also announced if the page up/down keys are used to move by extra content. There is no way to interrogate the application to see the current page number however. This feature, if feasible, can add efficiency to the reading process—especially in academic settings.

**Comment by Adriani90** [comment]
Hello, I have downloaded a very new book. In the product information on Amazon it was specified that it comes with screen reader support. In this book the pages are being reported properly.
However, in my old books I can jumpt between pages by page up and down and I can read the text like in a new kindle book with screen reader support. But in the old books pages are not being reported. I assume this information has to be provided by amazon when scanning the books since on one screen page there can more than one printed pages be sumarized after scanning. So I guess it is not possible for NVDA to report the real book page if the information has not been properly implemented.

**Comment by Adriani90** [comment]
I thought it could be a possibility to report kindle pages instead of printed pages, like in pdf documents. This should only apply if the real page information is not provided by Amazon.

**Comment by Adriani90** [comment]
Closing this issue since NVDA cannot do anything about this if pages are not provided in the meta information of the book.
