### ISSUE TITLE
NVDA 2018.1 acting weird with chromium open source version of chrome.

### ISSUE THREAD

**Issue by sethmhur** [nvaccess/nvda#8066]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result

1 open duckduckgo.com
2 can't view headings or edit boxes on pages. have to press NVDA + f5 to refresh nvda review.
3. when going to youtube.com can't view headings on page have to refresh nvda 
4 not able to interact with youtube buttons with the new nvda.

**Comment by Adriani90** [comment]
@sethmhur are you still having this issue in NVDA 2019.1.1 and Chrome last version?
If yes, please try to run the com registration fixing tool in NVDA menu / tools. Does this solve the issue?

**Comment by Adriani90** [comment]
We do not have any updates from the initial author since more than 18 months. Closing as abandoned and I cannot reproduce it with NVDA 2019.3 Beta 1 in any browser.
