### ISSUE TITLE
Braille issue: the letter in a text is not being reported by speech when moving the cursor to it with the cursor routing of the braille display

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8072]
### Steps to reproduce:
1. Open a text editor
2. Write a sentence
3. Press the cursor routing of a braille display to move the cursor to a letter.

### Expected behavior:
NVDA should report that letter by speech, if speech is enabled.

### Actual behavior:
NVDA does not report the letter.

### System configuration:
NVDA version:
NVDA 2018.1

NVDA Installed or portable:
Both

Other information:

Windows version:
Windows 10.16299.248

Name and version of other software in use when reproducing the issue:
Text editor, MS Word, MS Outlook.

### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
2017.4

**Comment by Adriani90** [comment]
To clarify the usage of this feature, braille beginners would benefit a lot.

**Comment by leonardder** [comment]
I'm pretty sure this behavior is intentional. However, I agree that it might be beneficial for beginners to have the speech optionally output the character. Note that also moving by line or scrolling doesn't output speech. I believe that the option as proposed here should also cover these cases.

**Comment by Adriani90** [comment]
@Andre9642 just implemented these features in his try build of the addon braille extender. This is great.
