### ISSUE TITLE
UG at section 14.2 (Optelec BC6...) there are 2 separate entries for alt key and one space is missing in row where command for enter key was written

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#8073]
### Steps to reproduce:

- open an userguide of nvda
- go to section 14.2
- look at the provided table
- see rows 16 and 34
- for enter see row 23

### Expected behavior:

there should be only one row for alt key with sp2 and alt written in the right column and "|" should not be shown in the table when a UG was opened in browser

### Actual behavior:

there are two rows for alt key at section for Optelec bc6 instead of one in nvda's userguide and "|" is shown after listing commands for emulation of enter key

### System configuration:
NVDA version:

next: 14941,891a9c9e
NVDA Installed or portable:
installed

**Comment by ehollig** [comment]
Looks like this should have been closed when #8465 was merged. Maybe it did not automatically close because the base branch was changed? Either way, closing.
