### ISSUE TITLE
Alva satellite used via protocol converter and Optelec BC6 driver does not detect some keys and some keys were assigned twice

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#8074]
First of all I would like to thank all of you to bring support for protocol converter into NVDA.

Here is one problem: Alva Satellite has 2 Satellite keypads, one on the leftside of display and one on the rightside with 6 keys on the each keypads, but NVDA treats them as one keypad. I do not know if it is bug of NVDA or bug of protocol converter, so I have opened this ticket as @leonardder suggested in private conversation.

### Steps to reproduce:

1. connect Alva Satellite to computer via protocol converter
2. wait system to install it on the system if it was not installed already
3. from the braille settings choose Optelec bc6...
4. turn input help on
5. play with keys on Satellite display

### Expected behavior:

NVDA should differentiate between Satellite keypads, so NVDA could emulates most of keys which are on bc6 displays.

### Actual behavior:

Now NVDA emulates: sp1, sp4, and sp left, right, up and down on both satellite keypads. So there are not: sp2, sp3, spEnter, etouch1, etouch3 and etouch4.

### System configuration:
NVDA version:

next: 14941,891a9c9e

NVDA Installed or portable:
installed

Other information:

Windows version:

Windows 10Ver1709 (64-bit) build 16299.248

### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
no

**Comment by leonardder** [comment]
I believe this can be fixed by differentiating between two smart pads. An ALVA BC680 is basically a device with two BC640 devices in one.

@dkager: would be good to have your opinion about this.

**Comment by dkager** [comment]
I don't think the BC680 differentiates between the two keypads in its own driver nor in the user guide. So that would explain this issue. We should find out if the protocol converter indicates which keypad was used, e.g. in a way similar to how the secondary routing keys are sent. If the converter does not distinguish two keypads, I'm afraid there is not much we can do.

**Comment by dkager** [comment]
OK, so it turns out the driver distinguishes the thumb keys and the smartpad keys on the BC680 and probably also the protocol converter. But they get the same name, so you have two sp1 and two spEnter, etc. Now the question is what name do we give the second group instead. As I said, Optelec appears to see them as duplicates. For the protocol converter it would make more sense to give them other names. Then we might as well give them different names for the BC680 too.

@leonardder Suggestions? I think 2ndSp1 is a bit awkward and sp5-sp8 are confusing because Optelec's user guide doesn't mention them.

**Comment by gregjozk** [comment]
Hello,

> Now the question is what name do we give the second group instead.

I suggest that the second group of satellite keys could emulate sp2, sp3, spEnter, etouch1, 2 and 3, because these buttons could not be emulated now.
In the NVDA UG it could be documented with one or two rows; e.g.: At Alva Satellite series, when these displays have been used with protocol converter, one group is linked to arrow keys and tab and shift+tab command, the other keypad is linked to sp2, sp3, spEnter and etouch 1, 2 and 3 due to specifics of protocol converter.
for bc680 I did not see a problem. Would a correction break existing support?

thx.

**Comment by dkager** [comment]
I think it makes sense if you can also assign different commands to either smartpad on the BC680. That means we have to come up with different names for the second smartpad.

Note that the converter should not emulate sp3 and sp4, but should execute the associated scripts. We could have a model-specific gesture map for the converter.

**Comment by gregjozk** [comment]
Hello,

would be helpfull if I send you a users manual for protocol converter?
I reread it and found, that jaws and Dolphine can differentiate
between satellite keypads. there is also written, that they can enable
status cells, but I have not been able to enable them, so I could use
routings and second routings above them.
May be it would also helpful, if zip packages from #447 would be
recovered, so you could investigate it and may you could bring some
ideas to this ticket.

regards, Jožef

2018-03-11 11:55 GMT+01.00, Davy Kager <notifications@github.com>:

**Comment by dkager** [comment]
Could you post a link to the manual? If not, maybe upload it to GitHub.

To clarify, are you saying the status cells are not working, but the secondary routing keys *are* working?

**Comment by gregjozk** [comment]
Hello,

yes, secondary routing is working as expected.

a manual and other material I plan to send via contact form on your website if it is ok for you.

**Comment by gregjozk** [comment]
Hello,

thanks for your work.
I've just tested it with try build, which was linked to #8230, but I don't see any changes. NVDA steal treas both satellite keypads as one.

regards, Jožef

**Comment by leonardder** [comment]
Could you please verify this by trying to assign a gesture to the same 
key on both keypads, for example the key that translates to sp1?
If my theory is correct, you can assign a key to alva:sp1 and 
alva.protocolconverter:lsp1 for the left keypad, and alva:sp1 and 
alva.protocolconverter:rsp1 for the right keypad.

**Comment by gregjozk** [comment]
Hello,

Very good. Obviously I missed something when I've read content of
#8230. When I tested it yesterday, I tested without trying to assign
gestures. now it works as expected. I can confirm, that NVDA
differentiates between left and right keypads, when gestures are
assigned to one of keys. If not, E.G. NVDA will emulate up arrow with
spup on both keypads.. and when I used InputHelp, NVDA has reported
key presses in a different succession. for example on left keypad
(NVDA) key press was reported as spdown + spup and on the right keypad
(NVDA) it was reported as spup + spdown when gestures have not been
explicitly assigned. these are mine findings. I think, it would be
very helpful, if it was documented.

One small observation, which is not showstopper: NVDA detect right
physical keypad as left keypad even in the local settings of Alva
Satellite it was set to no (switch satellite function).

regards, Jožef

2018-05-04 6:07 GMT+02.00, Leonard de Ruijter <notifications@github.com>:
