### ISSUE TITLE
Critical crash in NVDA

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8077]
Dear all,

NVDA is crashing several times, especially when typing text. I gues it could be related to SAPI5 but it seems to be a critical NVDA error. See log file and dmp file.

### System configuration:
NVDA version:
2018.1

NVDA Installed or portable:
Installed

Other information:
running In VM

Windows version:
Windows version 10.0.14393 workstation

Name and version of other software in use when reproducing the issue:
IE and others

### Other questions:

Does the issue still occur after restarting your PC?
Yes.

Have you tried any other versions of NVDA?
No.
[nvda-old.txt](https://github.com/nvaccess/nvda/files/1804631/nvda-old.txt)
[nvda_crash.dmp.zip](https://github.com/nvaccess/nvda/files/1804633/nvda_crash.dmp.zip)

**Comment by derekriemer** [comment]
```
0:010> .ecxr; kp
eax=00000013 ebx=0366403f ecx=0366404b edx=006d0084 esi=000c2000 edi=026301c4
eip=77e22137 esp=0597fc48 ebp=0597fcb0 iopl=0         nv up ei pl nz na po nc
cs=001b  ss=0023  ds=0023  es=0023  fs=003b  gs=0000             efl=00010202
ntdll!RtlpLowFragHeapAllocFromContext+0x1f7:
77e22137 8931            mov     dword ptr [ecx],esi  ds:0023:0366404b=????????
  *** Stack trace for last set context - .thread/.cxr resets it
 # ChildEBP RetAddr  
00 0597fcb0 77e21a7d ntdll!RtlpLowFragHeapAllocFromContext+0x1f7
01 0597fd00 77e2197a ntdll!RtlpAllocateHeapInternal+0xcd
02 0597fd10 75ad79b0 ntdll!RtlAllocateHeap+0x2a
03 0597fd30 6048f718 msvcrt!malloc+0x90
04 0597fd3c 604906ed UIAutomationCore!operator new+0x1d
05 0597fd6c 604f1cfe UIAutomationCore!operator new+0x18
06 0597fd84 604ca0e4 UIAutomationCore!WorkItemQueue::AddItem+0x8d
07 0597fd9c 604c6377 UIAutomationCore!ProxyEventManager::OnWinEvent+0x64
08 0597fdf0 604c6506 UIAutomationCore!WinEventManager::PreWinEventProc+0x1d8
09 0597fe28 604c645d UIAutomationCore!WinEventManager::WinEventReentrancyFilter+0xa0
0a 0597fe44 75bc872f UIAutomationCore!WinEventManager::StaticWinEventProc+0x1d
0b 0597fe7c 77e74c46 user32!__ClientCallWinEventProc+0x3f
0c 0597feb4 74fa60da ntdll!KiUserCallbackDispatcher+0x36
0d 0597feb8 75ba9fa9 win32u!NtUserPeekMessage+0xa
0e 0597fee8 75ba9f44 user32!_PeekMessage+0x29
0f 0597ff24 6045f1e9 user32!PeekMessageW+0x104
10 0597ff80 77d48f04 UIAutomationCore!WinEventManager::ThreadProc+0xa9
11 0597ff94 77e49b83 kernel32!BaseThreadInitThunk+0x24
12 0597ffdc 77e49b52 ntdll!__RtlUserThreadStart+0x2b
13 0597ffec 00000000 ntdll!_RtlUserThreadStart+0x1b

```

**Comment by derekriemer** [comment]
I'm not sure if my symbols are correct here, someone who knows more should check.

**Comment by khoath** [comment]
How often do these crashes occur?
Is this problem reliably reproducible?
If the problem is reproducible what steps must be taken to cause the problem?

**Comment by Adriani90** [comment]
Very often when using Sapi5 synthesizer. It is reproducible only with SAPI5 synthesizer while typing text and navigating in general.

 

Best

Adriani

 

 

Von: Kerry Hoath <notifications@github.com> 
Gesendet: Dienstag, 13. März 2018 03:07
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Author <author@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Critical crash in NVDA (#8077)

 

How often do these crashes occur?
Is this problem reliably reproducible?
If the problem is reproducible what steps must be taken to cause the problem?

**Comment by michaelDCurran** [comment]
Which specific SAPI5 synth is this?

**Comment by Adriani90** [comment]
This is german Steffi 22 KHZ

**Comment by ehollig** [comment]
@Adriani90, do you have an update on this issue?

**Comment by Adriani90** [comment]
Well, the issue still exists with the synthesizer described above. But since this is a very old synthesizer which will not be improved anymore, I am not sure about this high priority. The user who reported this changed the synthesizer and there are many alternatives. So I will close this for now until more complains from users will raise.
