### ISSUE TITLE
Dynamic finance site is laggy and difficult to use in Chrome.

### ISSUE THREAD

**Issue by aefren** [nvaccess/nvda#8078]
### Steps to reproduce:
open chrome and go to https://www.binance.com/trade.html?symbol=ADA_BTC

### Expected behavior:
NVDA should read the info using the arrows key or letter keys.

### Actual behavior:
NVDA is laggy, stops for some seconds each time info is required.

### System configuration:
NVDA version: 2018-1

NVDA Installed or portable: Installed.

Other information:
Running in windows 10 - 64 bits with 8gb ram.

Name and version of other software in use when reproducing the issue:
Eclipse, spotify, TWBlue, vlc etc.

### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
> Please list them and the result

With NVDA 2017 and same result.

**Comment by khoath** [comment]
This site appears more responsive in Firefox, so it appears that the issue you are seeing may have more to do with the browser in use and site design.
Perhaps contacting the site designer.
For more on this see issue #8079

**Comment by feerrenrut** [comment]
I'm going to close this issue since we believe the main cause is the dynamic nature of the site design, as such I will apply the `needs external fix` label. We hope to be able to mitigate this performance issue in the future.
