### ISSUE TITLE
Startup: "language is not supported by OS" error

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8080]
Hi,

Reported by a translator and subsequently confirmed: some languages are not supported by Windows, thus an error is shown when NVDA starts.

STR:

1. Switch to Mongolian (if running latest snapshots).
2. Restart NVDA if prmopted.

Expected: no errors.
Actual: "MOngolian is not supported by OS" error is shown.

Thanks.

**Comment by leonardder** [comment]
This has been reported for Kyrgyz in #8064. Are you ok with closing this issue in favor of that one?

**Comment by josephsl** [comment]
Hi, no, as this issue will cover other languages such as Mongolian. However, if the former one is better, then I think we should edit the title on that one instead and close this one. Thanks.
