### ISSUE TITLE
Losing focus in Gmail on Chrome when navigatin

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#8087]
Using NVDA 2018.1 on Google Chrome Version 65.0.3325.162 (Official Build) (64-bit) on Windows 10 fast insider build 17120.  Issue noticed in last few versions of everything though.

When editing a GMail message in Chrome, if navigation keys - eg right arrow - are pressed several times very quickly, NVDA jumps out of focus mode and into browse mode then moves to other elements.

In the following debug log snippet, I was quickly right arrowing through my name (Quentin Christensen) and when it got to the space between my names NVDA went to browse mode and the next right arrow started moving through the letters on the "Send" button.  I haven't encountered this in Firefox.  Without NVDA running, I can press the arrow keys as much as I like, as fast as I can without problems.  I also haven't encountered this on other websites (eg GitHub), so it may be a quirk in GMail?  The only real clue from the log are the lines where it reads: "Input: kb(desktop):rightArrow
IO - speech.speak (11:35:05.766):
Speaking [LangChangeCommand (u'en_GB'), u'out of edit', u'button']"

Log follows:

DEBUG - editableText.EditableText._hasCaretMoved (11:35:05.648):
Caret move detected using bookmarks. Elapsed: 50 ms
IO - inputCore.InputManager.executeGesture (11:35:05.651):
Input: kb(desktop):rightArrow
IO - speech._speakSpellingGen (11:35:05.655):
Speaking character u'n'
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (11:35:05.667):
Begin processing speech
DEBUG - queueHandler.registerGeneratorObject (11:35:05.667):
Adding generator 18
DEBUG - queueHandler.pumpAll (11:35:05.673):
generator 18 finished
DEBUG - synthDrivers.oneCore.SynthDriver._callback (11:35:05.703):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (11:35:05.703):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (11:35:05.730):
Cancelling
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (11:35:05.734):
Queue empty, done processing
IO - inputCore.InputManager.executeGesture (11:35:05.756):
Input: kb(desktop):rightArrow
IO - speech.speak (11:35:05.766):
Speaking [LangChangeCommand (u'en_GB'), u'out of edit', u'button']
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (11:35:05.779):
Begin processing speech
IO - speech._speakSpellingGen (11:35:05.779):
Speaking character u'S'
DEBUG - queueHandler.registerGeneratorObject (11:35:05.780):

**Comment by michaelDCurran** [comment]
Do you by chance have "automatic focus mode for caret movement" set in 
Browse Mode Settings?
I could see perhaps how this feature could cause the issue if 
Gmail/Chrome was a bit slow.

**Comment by Qchristensen** [comment]
Ah yes, that's it.  I forgot I'd turned that on to test something else awhile ago.  I didn't look in Browse mode settings because I "knew" what settings I was using.  I shouldn't listen to myself, clearly I don't know anything :)

Turning that off does stop the problem, although ideally you should be able to have it on without that happening.

**Comment by ehollig** [comment]
@michaelDCurran, would it be possible to improve this when the feature is turned on, or should this issue be closed?

**Comment by ehollig** [comment]
I am still unclear on what the solution should be to this issue. Should it be "improve this when the feature is turned on", or should this issue be closed?

**Comment by Qchristensen** [comment]
While turning "automatic focus mode for caret movement" off does stop this from happening, ideally it should be able to have this setting on without losing focus.  The issue is that when a site (particularly GMail) is being slow in Chrome, if you arrow through an edit field "too fast", NVDA goes to Browse mode and jumps to the next element, even though it hadn't reached the last character in the edit field.  So, from the point of view of correct behaviour, ideally, we should "improve this when the feature is turned on".

**Comment by Adriani90** [comment]
This could also be fixed by fast browse mode. cc: @mltony

**Comment by Adriani90** [comment]
@Qchristensen is this not similar to #8211? I think this is the same underlying problem.

**Comment by Qchristensen** [comment]
This is the same as 8211, not sure why I made two issues for it.  I must have been particularly irked by it and didn't look properly.  I'll close this one as a duplicate.
