### ISSUE TITLE
The latest "next" snapshots of NVDA use the old NVDA icon and not the newer one introduced in NVDA 2017.3

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#8091]
### Steps to reproduce:
1. Install one of the latest "next" snapshots of NVDA.
2. Look at the NVDA icon used in the system tray, on the desktop, in the "Start" menu.

### Expected behavior:
NVDA should use the new style icon, introduced in NVDA 2017.3.

### Actual behavior:
NVDA uses the old style icon, used before NVDA 2017.3.

### System configuration:
- Operating system: Windows 10 Pro version 1709 (build 16299.309), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: next-14952,dd1cbe50.
- Processor: Intel Core i5-4670 at 3.40GHz.
- RAM Memory: 8.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC887 at Intel Lynx Point PCH - High Definition Audio Controller.

**Comment by k-kolev1985** [comment]
After backing out wxPython 4, NVDA reverted to using the new icon again.

**Comment by leonardder** [comment]
Closing this. A fix for this in future try builds for WX Python Phoenix should be covered by #7104.
