### ISSUE TITLE
focus jumping when typing on the Braille Edge keyboard

### ISSUE THREAD

**Issue by Piciok** [nvaccess/nvda#8094]
Steps to reproduce:

1. Connect a Hims Braille Edge display via USB and choose it in the NVDA settings. make sure the connection is successful.
2. Open any text editor: tested with Microsoft Word 2016, notepad and the WYSIWYG editor of Github, so any will do.

3. Start typing a longer chung of text (something around 15 lines.)

Expected behaviour: the cursor should follow the text.

WHat happens instead: at a certain moment the cursor moves back, sometimes by one or a couple lines, sometimes to the beginning of the document.

NVDA version: 2018.1, used to happen with older releases as well; installed copy;
Windows: tested on 7 and 10;
This could be affecting other Hims displays or displays of other manufacturers as well, haven't got any units to test it with.

Attached please find the debug log.
[Braille Edge keyboard bug log.txt](https://github.com/nvaccess/nvda/files/1815507/Braille.Edge.keyboard.bug.log.txt)

**Comment by leonardder** [comment]
This log is really huge and therefore difficult to investigate. I assume you can't reproduce this on NVDA 2017.4? Also, how about typing a huge chunk of text in notepad?

**Comment by leonardder** [comment]
Were you by any chance intending to type the letter k (dot1+3) followed by a space?

Could it be that you type that rapidly that you accidentally pressed a space+dots combination that triggered a move of the cursor?

**Comment by Piciok** [comment]
Hi there!

As described, this used to happen with 2017.4 as well but I decided to wait off until the native Hims drivers are implemented as this might have been a known issue.

This happens in notepad as well. Shall I make a next log?

I thought it could be that but I believe I was typing slowly enough for it not to happen when debugging it this time.



Wysłane z aplikacji Poczta dla Windows 10

Od: Leonard de Ruijter
Wysłano: czwartek, 15 marca 2018 15:22
Do: nvaccess/nvda
DW: Piciok; Author
Temat: Re: [nvaccess/nvda] focus jumping when typing on the Braille Edgekeyboard (#8094)

Were you by any chance intending to type the letter k (dot1+3) followed by a space?
Could it be that you type that rapidly that you accidentally pressed a space+dots combination that triggered a move of the cursor?

**Comment by leonardder** [comment]
@Piciok: Still experiencing this?

**Comment by Piciok** [comment]
I have done some preliminary testing upon remapping the default ctrl+home and other key bindings involving left side of the braille input keyboard and spacebar held together and the issue seems to be gone, thus the suggestion that I might be typing too fast seems to be a right guess. I think the issue can be closed as solved now.
