### ISSUE TITLE
Update Espeak NG to solve mangling of words

### ISSUE THREAD

**Issue by sukiletxe** [nvaccess/nvda#8095]
### Steps to reproduce:
1. Switch the Espeak NG voice to English and read the following word by word multiple times: boogey début lasagne protegé Bogotá
2. Read the following the same way with the Spanish voice: 
voice DPTO. SR. DRA. English Excmo. Izq. kg. Pte. UD.
### Expected behavior:
Espeak NG should read the words properly.

### Actual behavior:

From the ending of one word which gets glued to another, to the entire replacement of a word, to complete silence (all three aply to just one word).
### System configuration:

NVDA version: 2018.1

NVDA Installed or portable: Installed

Other information:

Windows version: Windows 7 SP1

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC? It doesn't until one or more of these words is encountered.

Have you tried any other versions of NVDA? Yes, two weeks ago it worked the same way in Next, and I haven't seen any relevant commits here since then.

See espeak-ng/espeak-ng#421

**Comment by feerrenrut** [comment]
I'm going to close this issue, please see #7846 instead. We try to keep NVDA up to date with espeak releases, and also try to update the espeak version used by NVDA next regularly.
