### ISSUE TITLE
NVDA crash with Office (Word, Excel, Outlook)

### ISSUE THREAD

**Issue by bowave** [nvaccess/nvda#8097]
NVDA crashes a lot when using Office applications. My wife is blind and we thought to give it a try to NVDA on her new computer. We used 2017.4 at first and now 2018.1. The problem is in both.

Crashes happen as following:
- NVDA stops speaking and braille. If you wait 30 sec to 1 min it might revive but interval of these stops keeps shortening and soon the machine needs reboot. While NVDA is silent I can use the applications with keyboard and mouse. NVDA does not respond to NVDA (CAPS) + N key.
- Word, Excel or Outlook stops responding. I need to kill the offending program, losing all work and NVDA comes back to life. 

I can take log files but usually there is no log as I've to restart NVDA or alternatively there is nothing in the log as Office crashes. Below are some of the errors I've seen. It is quite common to see errors in log even if everything is still working.

There are no exact way to reproduce. Sometimes she gets a full day's usage without any problem and sometimes it is every five minutes.

When using Firefox, Edge, Windows Explorer there are no problems.

I've noticed also the following,

- In Excel when the width of the column is narrower than content (cell overflow) the frequency of crashes goes up
- In Excel when using the spreadsheets in older XLS format the crashes are way more frequent than with newer XLSX files. 
- In Word when changing between print layout and draft layout crashes are frequent
- In Word when typing very fast combined with a lot of cursor movement crashes are more frequent
- In Outlook it mostly crashes when composing new emails and typing very fast

All help is appreciated, I can try out snapshot or development or older versions easily and help as much as I can. Please tell me how and what kind of logs would be beneficial and I post what I can.

Thank you for your help!

### System configuration:

NVDA version: 2017.4 and 2018.1 installed version 
Lenovo X1, 16 MB RAM
Windows 10 Pro
Office 365
All things are fully updated.

---------------------------------------------------------------------------------

ERROR - RPC process 11060 (nvda_slave.exe) (11:37:57.101):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 91, in main
  File "comHelper.pyo", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyo", line 180, in GetActiveObject
  File "comtypes\__init__.pyo", line 1245, in GetActiveObject
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221021] Toimintoa ei löydy
ERROR - eventHandler.executeEvent (15:10:15.776):
error executing event: focusEntered on <NVDAObjects.UIA.UIA object at 0x07367C70> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 152, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\__init__.pyo", line 935, in event_focusEntered
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 115, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyo", line 800, in _get_isPresentableFocusAncestor
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 115, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyo", line 1087, in _get_presentationType
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 115, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyo", line 625, in _get_presentationType
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 115, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyo", line 1027, in _get_states
  File "NVDAObjects\UIA\__init__.pyo", line 716, in _prefetchUIACacheForPropertyIDs
COMError: (-2147024809, 'Parametri ei kelpaa.', (None, None, None, 0, None)) 

- Translation of Finnish comment: 'Parameter not valid'

---------------------------------------------------------------------------------

WARNING - watchdog._watcher (16:37:04.267):
Core frozen in stack:
  File "nvda.pyw", line 212, in <module>
  File "core.pyo", line 473, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 443, in Notify
  File "IAccessibleHandler.pyo", line 880, in pumpAll
  File "IAccessibleHandler.pyo", line 654, in processFocusWinEvent
  File "IAccessibleHandler.pyo", line 521, in winEventToNVDAEvent
  File "_UIAHandler.pyo", line 327, in isUIAWindow
  File "_UIAHandler.pyo", line 315, in _isUIAWindowHelper

---------------------------------------------------------------------------------

Traceback (most recent call last):
  File "nvda_slave.pyw", line 91, in main
  File "comHelper.pyo", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyo", line 180, in GetActiveObject
  File "comtypes\__init__.pyo", line 1245, in GetActiveObject
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221021] Toimintoa ei löydy 

- Translation of Finnish comment:  'Function/Action not found'

---------------------------------------------------------------------------------

**Comment by Adriani90** [comment]
I guess it is related to @7982 and referenced issues.

**Comment by mcsedmak** [comment]
FWIW I am seeing slowdowns which sometimes get severe enough to count as app freezes using windows 7, nvda 2018.1 and excel 2016.  This problem did not exist on nvda 2017.4

**Comment by fernando-jose-silva** [comment]
I'm also having issues with excel 2016, 64bits windows 10 16299.309, there is a very large slowness comes up to 20 seconds for nvda to announce something when trying to edit a cell.
This worksheet in question is very large, and with many formulas.
When editing this same file on another machine with office 2013 32bits and windows 7 this problem does not exist.
I'm using nvda next time.
The spreadsheet has no comments.
Unfortunately the spreadsheet in question has data from my work, and I can not share it.

**Comment by Adriani90** [comment]
Which addins are activated in your MS Office programms? Please go to the ribbon files, open the options from MS Word, MS Excel etc and look at addins. In the combobox you can choose a cathegory of addins and with the button after that you can see which addins are enabled for that specific cathegory.

**Comment by Adriani90** [comment]
by the way, is this issue still reproducible in NVDA 2018.2?

**Comment by bowave** [comment]
Updated to 2018.2 and 2018.2.1 and the crashing is still there. So far I've made following changes:

- disable excel in-cell editing --> the amount of excel crashing goes down a lot
- make all columns wider than content (no overflow to the right). This is not always feasible as the sheets formatted for printing or sighted persons will be rather ugly. Having a cell that is wider than content will get excel crashed much quicker.
- diable excel cursor movement with enter. Normally cursor is going down with enter but sometimes it is crashing.

In Word and Outlook when writing really fast with 10 fingers for long sentences and chapters,  both applications tend to crash. 

Only default add-ins of Office 365 are installed. I remove all and let you know if there are any changes.

Attached is the log after 15 minutes of usage after reboot today.
[nvda.log](https://github.com/nvaccess/nvda/files/2114567/nvda.log)

**Comment by Adriani90** [comment]
@bowave, could you please translate this into english?

Toimintoa ei löydy

This is an Windows error which appears in your log file.

**Comment by Adriani90** [comment]
@michaelDCurran, @feerrenrut

**Comment by bowave** [comment]
Translation: Function/Action/Operation not found.

**Comment by bowave** [comment]
Another log file, errors are same: 

- Toimintoa ei löydy == Function/Action/Operation not found.
- M\xe4\xe4ritt\xe4m\xe4t\xf6n virhe = Unknown error

[nvda2.log](https://github.com/nvaccess/nvda/files/2122761/nvda2.log)

**Comment by derekriemer** [comment]
Possibly, can you try the following?
In word, disable all options in document formatting, and turn them back on individually for about a day to see if the crash occurs?

**Comment by Adriani90** [comment]
Also, could you please clean your registry using something like CCleaner and clean also your cache Memory?

**Comment by Adriani90** [comment]
@bowave did you try to clean up registry and so on? Did this improve Performance in Office? Or are you still having issues?

**Comment by bowave** [comment]
Tried everything, cleaned registry, created new user account, tried both administrator and non-administrator accounts, tried Windows both in Finnish and English and finally reformatted hard disk and reinstalled Windows completely. For some reason the combination of Lenovo X1 Carbon + Windows 10 Pro + Office 365 + NVDA keeps crashing.

I've come to believe the problem is more inside Office than NVDA. Crashes happen more frequently when fast typing. Maybe some interprocess communication timing inside Office/Windows is broken because the X1 is having rather slow processor and the amount of crashes is reduced when there are less screen refreshing.

Not much anybody can help here. Maybe close this bug now as there is nothing to be done and I open a new bug if I have more information.

**Comment by Adriani90** [comment]
@bowave thank you very much for your response. If you open a new issue, please also upload a log file and a crash dump to see if it is related to NVDA. I am closing this for now but we can reopen it if we find out that it is related to NVDA. So far I did not get any similar reports from other users.
