### ISSUE TITLE
Translation missing in portugues Brasil

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8099]
### Steps to reproduce:

Change the nvda language to Portuguese Brazil.
Open the Add-In Manager.
When an add-on is enabled, nvda informs.
> A list of the steps you take to demonstrate the problem. 
>
### Expected behavior:
For an enabled add-on, nvda must inform
habilitado
which is the Portuguese word for enabled.

### Actual behavior:
nvda announces the status of the English add-on
enabled

### System configuration:
NVDA version:
next 14952

NVDA Installed or portable:
instaled

Other information:
All add-on statuses are in English as an example:
Desabled after restart.
should be
desabilitado após reinício
Windows version:
windows 10 1709 build 16299.251 64 bits
Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
> Please list them and the result
no

**Comment by fernando-jose-silva** [comment]
Another option that is not translated into Portuguese Brazil:
In the general options window of the nvda option
Notify for pending update on startup
It is also in English and is not translated into portugues Brasil.

**Comment by josephsl** [comment]
Hi,

Ah yes, the new translations may not been ready then. Regarding the second one, this is expected, as the feature is not ready for translators.

Side note: I'm half-tempted to close this now, but I won't until the original poster understands the implication of what I just said above. Only then I'll close it.

Thanks.

**Comment by josephsl** [comment]
Hi,

Clarification: when I said "half-tempted", I wasn't really joking. But in consideration of the community, I did say afterwards that it'll stay open until misunderstandings are put aside. I'll write a message to the community regarding translations and alpha builds.

Thanks.

**Comment by fernando-jose-silva** [comment]
I believe I discovered why it is not translated, these changes are not in the nvda 2018.1, had not tested this option, only tested the next.
Sorry for calling you for no reason.

**Comment by josephsl** [comment]
hi,

To be specific, not in master branch yet. So whenever you come across a feature that is in next branch but not in other branches, expect new messages in English or another language. ONly when features are merged into master then messages for them will be made available for translations.

Thanks, and don't apologize for calling us with this.
