### ISSUE TITLE
Allow user to choose what is copied to system configuration

### ISSUE THREAD

**Issue by kara-louise** [nvaccess/nvda#8104]
Currently, when you press the "Use currently saved settings on the logon and other secure screens" button in "General Settings",  NVDA checks to see if you have adons in your user settings directory, then warns you about the security risks. You are then presented with a dialogue asking you if you still want to proceed.

Rather than just giving the user the choice of yes or no, I think you should be presented with 3 options.
 * Copy entire directory (including addons)
* copy only settings file
* cancel. 

Pressing copy only settings file would just copy the NVDA.ini file located in the root of the user settings folder, ignoring any profiles the user might have created.

Optionally, an advanced button could be provided for more granular settings, such as instructing NVDA to copy only the addons you need and trust to be active on secure screens.

**Comment by leonardder** [comment]
Closing as duplicate of #6305. See also #2226, #5578 and #814.
