### ISSUE TITLE
Input Gestures window doesn't list emulated keys after deleting their braille hotkey

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#8107]
On Sunday, 18th March 2018, I sent an e-mail to info@optelec.de and as CC to 'info@nvaccess.org (See bug #8106 for details)' Here is the 10th mentioned bug from this e-mail - also translated from German into English by Google Translate.

===== Translation of the German e-mail into English by Google Translate =====
10. And for the grand finale, a small bug that already exists in NVDA 2015.3. As soon as the key assignment for emulated keys (eg Tab or ALT) in the "Inputs" dialog box is removed so that they can no longer be actuated using the control keys on the Braille display, those entries in this dialog box disappear completely. Consequently, these emulated keys can not be assigned to new buttons on the Braille display via this dialog box. I see a workaround here in the "gestures.ini", where you delete the original buttons for the emulated keys at the "none" entries. But I have not looked at it yet, because I do not need the most emulated keys anyway. But for inexperienced users, this may be annoying, since you can not assume that they are handing over to INI files by hand using Notepad++.

===== Original e-mail in German =====
10.	Und zum krönenden Abschluss noch ein kleiner Bug, der allerdings auch schon in NVDA 2015.3 existiert. Sobald man die Tastenzuweisung für emulierte Tasten (z.B. Tab oder ALT) im Dialogfenster „Eingaben“ entfern, sodass jene nicht mehr mittels den Bedientasten auf der Braillezeile betätigt werden können, so verschwinden jene Einträge in diesem Dialogfenster vollständig. folglich kann man diese emulierten Tasten zumindest nicht gleich wieder über dieses Dialogfenster neuen Bedientasten auf der Braillezeile zuordnen. Einen Workaround sehe ich hier nämlich noch in der „gestures.ini“, indem man dort bei den „none“-Einträgen die ursprünglichen Bedientasten für die emulierten Tasten löscht. Aber das habe ich mir noch nicht genauer angeschaut, da ich die meisten emulierten Tasten eh nicht benötige. Aber für unerfahrene Benutzer mag dies ärgerlich sein, da man nicht davon ausgehen kann, dass sie von Hand mittels Notepad++ an INI-Dateien herumdoktern.

**Comment by CyrilleB79** [comment]
Today (NVDA 2023.1), emulated key still disappear from the tree when closing the dialog if there is no associated gesture anymore.

But since NVDA 2020.3, you can recreate it and associate a gesture if needed. Moreover, this is documented in the User Guide as well as the fact that emulated keys with no associated gesture will disappear.

I think that this behavior is acceptable. Do you agree with me? If yes, let's close this issue. If no, could you indicate what you are still expecting?

**Comment by DrSooom** [comment]
Sadly, I have to inform you that I currently do not have the necessary time to check this issue in the depth that I think is required due to several health problems. Thank you for your understanding.

**Comment by seanbudd** [comment]
Closing as abandoned
