### ISSUE TITLE
When navigating the gmail page gsuite corporate inbox using the default view, nvda gets stuck in the navigation of the chat tabs

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8111]
### Steps to reproduce:
Open the corporate gsuite email, inbox using the default view.

Now press m to go to the chat frame.
Press, to go to the end of the frame.
Now walk with arrows below and see that the nvda will be stuck in the guides
Hangouts contacts Hangouts conversations. Phone calls
To continue navigating the page you will need to press tab.

## Expected behavior:
The nvda should allow you to continue navigating with the arrows below after reaching the chat tabs.

### Actual behavior:
The nvda when navigating with the arrows below only navigates between the 3 tabs of the chat and it is not possible to read with the arrows below the rest of the page.

### System configuration:
NVDA version:
next 14952

NVDA Installed or portable:
instaled
Other information:
This only occurs in the corporate email of gsuite, it does not occur in gmail person.
Chat guides are slightly different between personal and corporate accounts.

Windows version:
windows 7 64bits

Name and version of other software in use when reproducing the issue:
chrome 65 64bits
### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result
no

**Comment by Adriani90** [comment]
related to #2039 and referenced issues.

**Comment by Adriani90** [comment]
This issue is also potentially fixed by fast browse mode. cc: @mltony

**Comment by fernando-jose-silva** [comment]
Thank you very much.
I am no longer a corporate gmail user.
I tested using gmail's non-commercial user account and could no longer replicate the problem.

**Comment by ehollig** [comment]
Closing as worksforme
