### ISSUE TITLE
Laptop keyboard configuration and numeric keypad

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#8115]
When NVDA is configured in laptop keyboard mode, the numpad keys remain affected to the function they have in desktop mode.
I mean you can't use them for pageup, pagedown etc.
We could say that laptop mode is for machines having no numeric keypad but, un oftunately, I have an Asus laptop which has a numpad, but no end key (they have placed the power button where the end key should be, and so there is no end key).
So I would like to be able to use the numpad end to replace it.
It is incredibly perturbing to have no end key on a keyboard!
So, it would be nice that, when in laptop mode, the numpad could integrally getbak to its original functions.

**Comment by leonardder** [comment]
Personally, I like the current situation where the numeric keypad keys are still assigned in laptop mode. I guess it's a matter of preference.

Having said that, I'm pretty sure your asus laptop yet has the possibility to access the End key by combining one of the arrow keys with the FN keys. Could you check whether that works for you?

**Comment by ruifontes** [comment]
No, I already tried FN key with all the keys...
FN + arrows is for Next track, previous track, Play/Pause and Stop...

Rui Fontes


Às 10:07 de 23/03/2018, Leonard de Ruijter escreveu:

**Comment by Adriani90** [comment]
Closing in favor of #16479.
