### ISSUE TITLE
Refreshabraille display won't scroll when computer awakes

### ISSUE THREAD

**Issue by mehgcap** [nvaccess/nvda#8116]
I'm finding that when I connect a first-generation Refreshabraille to NVDA via USB, I can't scroll when I wake my computer up.

* Connect a Refreshabraille (first generation) via USB.
* Open NVDA menu > preferences > braille. Choose your display and the correct connection. Make sure the display is working as expected.
* Put your computer to sleep and wait for your display to sleep as well.
* Wake up your computer, making sure NVDA resumes normally. It does for me, so far as I can tell.
* Press and hold the power button on your display to wake it up. It wakes, connects, and shows braille from NVDA as expected.
* Hit a panning button. For me, though braille changes when NVDA speech does, nothing happens when I try to pan.
* Go to the NVDA menu > preferences > braille and simply press enter, accepting the current display choice. This causes panning to work correctly again.

**Comment by leonardder** [comment]
@mehgcap: Can you still reproduce this when using NVDA 2018.3 beta with automatic braille display detection enabled?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since 5 years, closing as abandoned. Please comment in case you are still having this issue and we can reopen.
