### ISSUE TITLE
Tool Tips are not read in UWP apps when "report tooltips" is enabled

### ISSUE THREAD

**Issue by btman16** [nvaccess/nvda#8118]
If "Report Tooltips" is turned on, tooltip messages are reported in Desktop programs but not for UWP apps.

Steps to Reproduce:
1. Turn on report tooltips in object presentation.
2. Open a modern program such as Microsoft Edge.
3. Tab through the UI elements, not a web page. This is the area that includes the address bar, hub, etc.
Expected result: Tool tips should be read for most controls.
Actual Results: No tool tips are read.
But if you open Narrator, tool tips are read, and this is important because the tool tips contain the access keys needed to get to menus and other controls quickly. Without this, NVDA users will have no easy way to learn the access keys in this and other situations.
This is on Windows 10 build 17127.1 on a recent Master snapshot.

Thank you very much for your time and I look forward to any fixes you may be able to provide.

Sincerely,

Brandon Tyson

**Comment by josephsl** [comment]
Hi,

Technical: we do have UIA_tooltipOpened event ready to go. The question is where do we put the handler for UWP tooltips (perhaps a new overlay class).

CC @CToth, @MichaelDCurran, @LeonardDer
