### ISSUE TITLE
Firefox 59 becomes almost unusable on Windows 10 with NVDA

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#8119]
### Steps to reproduce:
Open webpages in Firefox, especially complex websites as Youtube videos or containing frames or adds 

### Expected behavior:
Documents shoud be loaded faster, like when they are opened for instance in Chrome.

### Actual behavior:
Most documents are loaded very slowly, and until they're completely loaded NVDA doesn't respond normally to arrow keys. Also, documents are reported as containing rows like tables, until browse mode is enabled.

### System configuration:
NVDA version:
2018.1

Installed

Windows version:
Windows 10, version 1709 (compilación de SO 16299.309), in Spanish

### Other questions:
[nvda.txt](https://github.com/nvaccess/nvda/files/1844379/nvda.txt)

The problem persists after trying Firefox in secure mode and reinstalling it, as shown in the attached log file.

**Comment by tapper82** [comment]
As far as i can tell this bug is fixed in firefox 60.

**Comment by nvdaes** [comment]
Replying to @tapper82
> As far as i can tell this bug is fixed in firefox 60.

I'm testing now with Firefox 60 in iVoox and Youtube, and sometimes arrows don't work. It seems the system freezes.
This doesn't happen with Chrome, though perhaps now pages load faster than using Firefox 59
Also, I noticed this works better when uninstalling the Mozilla Maintenance Service, also in Firefox 59.

**Comment by derekriemer** [comment]
cc @jcsteh

**Comment by nvdaes** [comment]
Today the dev version of Firefox seems to be updated and now it's faster and usable with NVDA in pages like Ivoox for me.
Though the Google main page doesn't show links like Gmail. I saw this before occasionally in previous versions of Firefox.
Thanks

**Comment by jcsteh** [comment]
[**@nvdaes**](https://github.com/nvdaes) commented on [Apr 5, 2018, 2:52 AM GMT+10](https://github.com/nvaccess/nvda/issues/8119#issuecomment-378669592 "2018-04-04T16:52:25Z - Replied by Github Reply Comments"):
> Though the Google main page doesn't show links like Gmail.

If I go to google.com, the first link at the top of the page is "Mail". What do you see?

**Comment by nvdaes** [comment]
jcsteh commented an hour ago 

> If I go to google.com, the first link at the top of the page is "Mail". What do you see?

Now I see Gmail, but sometimes, time ago, Google links previous to the edit box weren't shown in Firefox on Windows 10. This maybe fixed disabling Javascripts.
Anyway, latest versions of Firefox seem to work better than 59, though Chrome seems to be faster in Youtube or Ivoox.

**Comment by michaelDCurran** [comment]
The google page will start with the search field if your Firefox window 
is extra small. I have accidentally gotten into this state before. 
You'll also notice that the Firefox address bar and search box become 
merged as one control like in Chrome. Maximizing the window can fix this.

**Comment by nvdaes** [comment]
michaelDCurran commented 

> The google page will start with the search field if your Firefox window
is extra small. I have accidentally gotten into this state before.
You'll also notice that the Firefox address bar and search box become
merged as one control like in Chrome. Maximizing the window can fix this.

Thanks for this useful info.

**Comment by ehollig** [comment]
It sounds as if this issue is now fixed. Unfortunately, there is nothing NVDA can do with regards to the performance of Firefox 59 and 60. Closing
