### ISSUE TITLE
gvim support

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#812]
**Reported by peter on 2010-08-05 10:55**
Is there any possibility to make gvim accessible using display hook in actual versions of nvda? The text is accessible in review mode but caret movement is not detected. I tryed to change the look and blink rate to be similar to standard windows caret (this is enough to make gvim accessible with jaws) but without success. Here are the parameters which are enough to make it accessible with jaws:
set guicursor=a:hor10-Cursor-blinkwait1-blinkon52-blinkoff53
Can i some how help with this? I am a programmer but without experiences with this kind of programming. Vim is an excellent editor and it could be nice to have it accessible with nvda.

**Comment by dkager** [comment]
Anyone know if gvim has made steps to improve accessibility? https://github.com/nvaccess/nvda/issues/2156#issuecomment-155296102 mentions an addon, but that was lost when going to GitHub.
I would go as far as to say p4, because there are other editors that work well, such as Notepad++. This also depends on external work.

**Comment by Kerneels** [comment]
Hi. In case this might be of any help, please see the atached JFW script that makes GVim work reasonably well.

As soon as I can get to it, I'll revitalize the phonim project, which is a collection of approaches on how to make GVim speak. For now I thought that the use of the Vim commands sent through the OLE connection, as well as the key interpretation might be helpful for a NVDA situation.

I'm trying an NVDA AppModule for GVim, but although the NVDA log shows no errors, nothing is spoken. I suspect the OLE linkup fails, but I'm too inexperienced with NVDA to debug this properly.

The JFW script also relies on a few Vim settings in _vimrc config file, to make GVim more palatable to JFW; not sure how much of that would be relevant for NVDA, but I will have all of that once revitalizing the phonim project happened. 
[gvim.jss.txt](https://github.com/nvaccess/nvda/files/1354100/gvim.jss.txt)

**Comment by Adriani90** [comment]
Closing this in favvor of #2156 because the discussion is more detailed on that issue.
