### ISSUE TITLE
Windows 10 17110: when fetching source code via Windows Subsystem for Linux, case sensitivity flag is enabled, causing source code compilation to fail

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8122]
Hi,

A setback for Windows Subsystem for Linux users: on Windows 10 build 17110 and later, when WSL is used to fetch files or work with directories, case sensitivity flag is turned on. Among other things, it causes compilation errors when NVDA source code obtained via WSL/Git is compiled. Among other things, when trying to compile the source code, SCons complains that source files are missing. One workaround is to manually mark NVDA source code directories as case insensitive, either via fsutil.exe (Windows side) or via WSL.

Reference:
* Per-directory case sensitivity and WSL, Windows command Line Blog. URL: https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/

Thanks.

**Comment by dkager** [comment]
How is this related to the checkout process? Is WSL as a whole case-sensitive or does Git set some flag?

Which specific errors occur? Shouldn't be too hard to fix, unless it happens in submodules.

**Comment by josephsl** [comment]
Hi, it is WSL that does this. Thanks.

**Comment by leonardder** [comment]
Could you please provide a log of scons source after a full checkout from within wsl? It shouldn't be too much of a deal to make the source distribution case sensitivity compliant.

**Comment by josephsl** [comment]
Hi, when it runs, I get a output that says source file not found, needed by target file. Thanks.

**Comment by leonardder** [comment]
it might help to know what files actually are the culprit here.

**Comment by josephsl** [comment]
Hi, the first one is AcrobatAccess.idl. There are other files affected by this. Thanks.

**Comment by dkager** [comment]
> There are other files affected by this.

So it would probably make sense to fix them all in one patch.

**Comment by roelvdwal** [comment]
Unfortunately, one or more of nvda's dependencies also have this problem. Minhook is one of them. When renaming some of the other files causing problems, this error came up:
build\x86\minHook\dllmain.cpp(16): fatal error C1083: Cannot open include file: 'minhook.h': No such file or directory
We could solve this problem by checking for case sensitivity in nvda's build directory by invoking
fsutil.exe file queryCaseSensitiveInfo <path>
If this indicates that the directory is indeed marked as case sensitive, we could inform the user instead of trying to build anyway and failing.

**Comment by Adriani90** [comment]
cc: @codeofdusk

**Comment by Adriani90** [comment]
@roelvdwal, @josephsl do you still see this issue with NVDA last master source?

**Comment by zstanecic** [comment]
Windows 10 17110 is too old, and wsl progressed. It is good to close this issue.

I can clone latest master source from wsl.

**Comment by LeonarddeR** [comment]
I'm very sad to say that @roelvdwal has passed away around two years ago.

I will close this issue.
