### ISSUE TITLE
Windows 10: NVDA announces "unknown" when opening and closing quick link menu (Windows+X)

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8137]
Hi,

Reported by several people: in Windows 10, when one opens quick link menu (Windows+X), NVDA announces "unknown".

STR:

1. Press Windows+X to open quick link menu.
2. Select an item.

Expected: no "unknown".
Actual: "unknown" is announced.
Cause: an app launcher or an unknown window gains focus.

Related to: #5116, #6671.

Thanks.

**Comment by feerrenrut** [comment]
I'm not able to reproduce this issue on Windows 10 version 1709  build 16299.371.

**Comment by PratikP1** [comment]
I have not been able to replicate this in any of the insider builds of Windows. However, if we try to use object nav to look at the first level children of desktop, there are several unknown children. Perhaps what people are hearing is NVDA potentially focusing on one of these unknown objects.
