### ISSUE TITLE
Windows explorer is unuseable if under load e.g large file transfers

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#8145]
### Steps to reproduce:

1. Copy many files to the clipboard (enough so that copying them takes more than a few seconds. Navigate to the destination folder.
2. Open another windows explorer window, it doesn't matter what folder it is at.
3. Paste the files into the destination.

### Expected behavior:
NVDA should be able to read items in windows explorer and the start menu normally.

### Actual behavior:
Attempting to move through a list of files in a folder when it there's a big copy operation in the background results in nothing being spoken.
Pressing the start menu and typing to bring up the list of suggestions does not read immediately when it appears as it would normally.

These problems disappear once the file transfer completes.

### System configuration:
NVDA version:
master-14992,4ccb2ab1

NVDA Installed or portable:
Installed

Other information:
This is even happening on a laptop with a core I7 8550U, and an SSD, so hardware shouldn't be the problem here.

Windows version:
Observed on multiple versions of Windows 10, including 1709 and 1803 RTM.

Name and version of other software in use when reproducing the issue:
Windows explorer/shell

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No.

**Comment by josephsl** [comment]
Hi, this is another variation of an issue raised some months ago, ultimately caused by UIA miscommunication. Thanks.

**Comment by Neurrone** [comment]
@josephsl curious what the issue is, and whether there'll be fixes on Microsoft's and/or NVDA's end.

**Comment by josephsl** [comment]
Hi, I heard reports that UIA issue has been improved somewhat in newer Windows 10 releases. CC @TSpivey, @MichaelDCurran

**Comment by Brian1Gaff** [comment]
Are we sure this is not at least in part due to the throttling of the speed 
Windows seems to love to do when it thinks its not very busy? IE pushing up 
the idle speed can pay dividends on my I5 quite considerably.
 It also speeds up the scrolling up and down of the  file list as well.
 I've also come across a glitching in sound when this problem occurs too, 
much like in the bad old days of single core processors.

Not quite so bad on windows 7, but that is because it does not have as much 
uia going on as 10, I'd imagine.
Brian

**Comment by Neurrone** [comment]
I think it may be caused by 1803. I've never experienced such severe lag with windows explorer before.

**Comment by Neurrone** [comment]
@Brian1Gaff you were onto something when you mentioned throttling. 

I started experiencing much higher than usual latency with NVDA and didn't realized it was caused by switching to the power saver plan. There are [many hidden settings that causes the plans to have very different performance characteristics](https://superuser.com/questions/1118604/hidden-differences-between-system-power-plans-in-windows).

**Comment by Neurrone** [comment]
Related issue: #6214

**Comment by Novalis7747** [comment]
this happens for me only when source and destination is on the same hard disk. I can't reproduce it when source and destination are on different hard disks.

**Comment by leonardder** [comment]
@Neurrone: This should have been majorly improved now.
@Novalis7747: What version of Windows 10 are you using? The Windows 10 October 2018 update (version 1809) should have introduced additional fixes for this issue.

**Comment by Novalis7747** [comment]
I’m running Win10 1809 with latest updates. It is easy for me to reproduce:

  1.  Identify any big file on your hard disk, I use the Win10 1809 iso file with 3,5gb
  2.  Copy this file to a different location on the same hard disk
  3.  Try to alt tab to other running tasks or to interact with the copy dialog
  4.  Result: NVDA is lagging very bad, means it is not usable while the copy process is going on
  5.  Pasting the file to a different hard disk doesn’t impact NVDA
  6.  Problem can’t be reproduced using Narrator

**Comment by Neurrone** [comment]
This was fixed a long time ago, closing.
