### ISSUE TITLE
In windows 10 mail reply cursor not always get focus on text field

### ISSUE THREAD

**Issue by lallerke1** [nvaccess/nvda#8154]
If you open windows 10 mail app,
and answer someone with ctrl and r
the focus is not always on the message body.
The more focus is so bad, if you go from a textfile back to the mail app

**Comment by lallerke1** [comment]
Here are my logs for th
[mail.txt](https://github.com/nvaccess/nvda/files/1889971/mail.txt)
is issue in log, and txt
[mail.log](https://github.com/nvaccess/nvda/files/1889970/mail.log)

**Comment by Adriani90** [comment]
This works as expected with NVDA 2020.1 and Windows 10 1909 Update. using the last version of the mail app. Closing as works for me. But please don't hesitate to comment on this if you are still having this issue and we can reopen. Thanks.
