### ISSUE TITLE
suggestion, allow quick selection of a set of elements in web pages.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8156]
### Steps to reproduce:
in my work I have come across large tables or large lists that I would like to copy from web pages.

### Expected behavior:
I would like to suggest a shortcut key that allows you to select an entire table, or a list on a web page in a more agile way, it is currently necessary to select row by line in navigation mode.

### Actual behavior:
You must select row by row until you select the large tables or lists.

### System configuration:
NVDA version:
all

NVDA Installed or portable:
instaled and portable

Other information:
> Example: Running in a VM

Windows version:
all

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by JulienCochuyt** [comment]
> You must select row by row until you select the large tables or lists

Very sorry for the lengthy answering delay, but you actually do not need to do that to select an entire table or list.
In browse mode, NVDA offers single letter quick navigation such as "`t`" to go to the next table or "`l`" to go to the next list. Pressing `shift` + the same letter goes to the previous same element type.
There is a lesser known of these: comma ("`,`") goes to the first character past the end of a container, such as a table or a list, and `shift+,` goes to the start of the current container.

To select the whole container, be it a table or a list, you can thus follow the steps:
- Navigate to the very beginning of container, by any means you like.
- Press `NVDA+F9` to mark the start of the selection.
- Press comma ("`,`"] for quick navigation to first character after the container.
- Press left arrow to be at the very last character of the container.
- Press `NVDA+F10` twice quickly to copy the whole container into the clipboard.

Please close this issue if you feel this answer is satisfying, or feel free to propose an enhancement to the described behavior.

**Comment by bhavyashah** [comment]
@fernando-jose-silva Could you please confirm if the work-around described in https://github.com/nvaccess/nvda/issues/8156#issuecomment-533975417 by @JulienCochuyt suffices?

**Comment by fernando-jose-silva** [comment]
yes, solve my problem.
 As a suggestion, we could think of documenting this somewhere, either in the nvda training material or somewhere more interesting if there is.
 These are commands that are familiar to me, but I confess I never thought of using light together.
 thanks.

**Comment by Adriani90** [comment]
Ok, thanks for the answer and also @JulienCochuyt big thanks for the good suggestion here.
@Qchristensen do you think we can improve documentation in the user guide regarding to this? Actually there is already some documentation on this part, but without clear practical examples I guess.

I will close this issue for now, but feel free to provide documentation suggestions in a new issue.

**Comment by Qchristensen** [comment]
Thanks Adriani for tagging me.  I will certainly have a look at what we can do for the user guide.  For now at least, I've included Julien's tips in our In-Process blog this week: https://www.nvaccess.org/post/in-process-2-2-22/  (Thanks to my co-writer this week, Julien!
