### ISSUE TITLE
Problem when I want to write a document using the software Devpascal Displaymodel

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#816]
**Reported by jeronimo on 2010-08-07 22:42**
Hello, I'm studying to become a developer of applications. To edit my programs in Turbo Pascal language, I use a software called Devpascal. When I write text in Devpascal, NVDA does not announce the text that I wrote when I'm up arrow, down arrow, right arrow and left arrow. However, when I sailed with the review position, NVDA announces the text that I wrote.
I notice when you open a document in this software, NVDA listing the entire contents of the document. When I press Ctrl + subtract, NVDA announced that no cursor and even if we subtract, NVDA is a sound error.
Please, can you solve this problem for version 2010.2 because I will like to use this software correctly for my studies.
To help, I attach to this ticket Devpascal the file to install.
Tips
1. Start Devpascal.
2. Then, Ctrl + U, you will see the above comments.
Note
Jai struggled to send the file to install Devpascal because the file size was over 256 Kb. For developers who will see this message, you can 't contact email address window so I can send you the file.
Thank you

**Comment by dkager** [comment]
wontfix because very specific?

**Comment by Adriani90** [comment]
@jeronimo it is a very long time you have created this issue. Are you still having this problem with the last version of devpascal? Could you please archive the installer file into a zip file and upload it to this issue so we can install and reproduce the isue ourselves? Thank you!

**Comment by jeronimo** [comment]
@Adriani90, I do not recall anything doing with screen reader on Win OS. I would guess there was another person outside Github with the same username. Cheers!

**Comment by Adriani90** [comment]
Ok sorry for that, I saw there are lots of users with this name on github. I am closing this issue for now. If the initial author comments on it we can reopen the discussion.
