### ISSUE TITLE
NVDA does not render certain buttons in its virtual buffer in Firefox.

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#8168]
### Steps to reproduce:

1. The following code is taken directly from Step 2.C. of the [accessible name calculation algorithm](https://www.w3.org/TR/accname-1.1/) specification:
2. Unzip and load the attached [testMissingButtonsInNVDAVirtualBuffer.zip](https://github.com/nvaccess/nvda/files/1901769/testMissingButtonsInNVDAVirtualBuffer.zip) HTML document into Firefox.
3. Inspect the virtual buffer, and the accessible tree with object navigator, especially the two list items.

### Expected behavior:

The two buttons "Delete Documentation.pdf" and "Delete HolidayLetter.pdf" should be present in the virtual buffer. They can be found using object navigator.

### Actual behavior:

The buttons aren't rendered and cannot be found with the B quick navigation key.

### System configuration:
NVDA version: version next-15023,fcbd1731

NVDA Installed or portable: installed.

Other information:

Windows version: Windows 10 Version 1709 (Build 16299.371)

Name and version of other software in use when reproducing the issue: Firefox 59.0.2, 60.0beta, or 61.0a1 nightly.

### Other questions:

Does the issue still occur after restarting your PC? Yes.

Have you tried any other versions of NVDA? Yes, 2018.1.1, same issue.

**Comment by Brian1Gaff** [comment]
What about pre quantum version of FF?
Brian

**Comment by jcsteh** [comment]
The buttons have a width of 0, which means they're invisible. Thus, NVDA is correctly choosing not to render them.
