### ISSUE TITLE
random crashes in nvda windows 10 1803

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8172]
### Steps to reproduce:
Today I updated to windows 10 1803 build 17133.73.
After this upgrade, nvda showed some random crashes.
I know this type of error is very difficult to solve.
More if there is someone with the same problem.
I was able to get a nvda log file.
I did not find an error files to pick up in the temp folder.
Before this windows upgrade, there were no errors.

### Expected behavior:
no mistakes

### Actual behavior:
use windows 17133.73 and wait for some locking in nvda.

### System configuration:
NVDA version:
next 15007
NVDA Installed or portable:
instaled
Other information:
> Example: Running in a VM

Windows version:
windows 10 17133.73 64bits
Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result
no

**Comment by fernando-jose-silva** [comment]
I stopped by the log that nvda caught and did not say anything else, however continued to record the keystrokes on the keyboard.
log:
IO - inputCore.InputManager.executeGesture (14:47:12.842):
Input: kb(laptop):n
DEBUGWARNING - watchdog._watcher (14:47:13.362):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 212, in <module>
  File "core.pyc", line 473, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 443, in Notify
  File "IAccessibleHandler.pyc", line 880, in pumpAll
  File "IAccessibleHandler.pyc", line 654, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 37, in getNVDAObjectFromEvent
  File "IAccessibleHandler.pyc", line 343, in accessibleObjectFromEvent
  File "IAccessibleHandler.pyc", line 327, in normalizeIAccessible
  File "comtypes\__init__.pyc", line 1191, in QueryService

DEBUGWARNING - core.CorePump.Notify (14:47:13.426):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 443, in Notify
  File "IAccessibleHandler.pyc", line 880, in pumpAll
  File "IAccessibleHandler.pyc", line 654, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 72, in __call__
  File "watchdog.pyc", line 202, in _COMError_init
CallCancelled
IO - inputCore.InputManager.executeGesture (14:47:15.401):
Input: kb(laptop):NVDA+n
IO - inputCore.InputManager.executeGesture (14:47:24.091):
Input: kb(laptop):NVDA+t
IO - inputCore.InputManager.executeGesture (14:47:41.915):
Input: kb(laptop):escape
IO - inputCore.InputManager.executeGesture (14:47:48.127):
Input: kb(laptop):windows+m
IO - inputCore.InputManager.executeGesture (14:48:02.838):
Input: kb(laptop):alt+shift+tab
IO - inputCore.InputManager.executeGesture (14:48:05.872):
Input: kb(laptop):alt+f4
IO - inputCore.InputManager.executeGesture (14:48:07.119):
Input: kb(laptop):escape
IO - inputCore.InputManager.executeGesture (14:48:08.901):
Input: kb(laptop):alt+shift+tab
IO - inputCore.InputManager.executeGesture (14:48:11.569):
Input: kb(laptop):alt+f4
IO - inputCore.InputManager.executeGesture (14:48:12.782):
Input: kb(laptop):escape
IO - inputCore.InputManager.executeGesture (14:48:14.354):
Input: kb(laptop):alt+shift+tab
IO - inputCore.InputManager.executeGesture (14:48:14.539):
Input: kb(laptop):alt+shift+tab
IO - inputCore.InputManager.executeGesture (14:48:16.420):
Input: kb(laptop):numpadEnter
IO - inputCore.InputManager.executeGesture (14:48:16.759):
Input: kb(laptop):alt+f4
IO - inputCore.InputManager.executeGesture (14:48:17.982):
Input: kb(laptop):escape
IO - inputCore.InputManager.executeGesture (14:48:23.898):
Input: kb(laptop):alt+control+a
IO - speech.speak (14:48:26.328):
Speaking [u'Paisagem']
IO - inputCore.InputManager.executeGesture (14:48:30.171):
Input: kb(laptop):windows+u
IO - inputCore.InputManager.executeGesture (14:48:32.385):
Input: kb(laptop):alt+tab
IO - inputCore.InputManager.executeGesture (14:48:34.042):
Input: kb(laptop):alt+tab
IO - inputCore.InputManager.executeGesture (14:48:36.539):
Input: kb(laptop):windows+m
IO - inputCore.InputManager.executeGesture (14:48:37.957):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (14:48:38.641):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (14:48:39.691):
Input: kb(laptop):windows+m
IO - inputCore.InputManager.executeGesture (14:48:41.048):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (14:48:41.688):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (14:48:42.187):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (14:48:43.418):
Input: kb(laptop):alt+tab
IO - inputCore.InputManager.executeGesture (14:48:45.506):
Input: kb(laptop):alt+tab
IO - inputCore.InputManager.executeGesture (14:48:52.813):
Input: kb(laptop):control+shift+escape
IO - inputCore.InputManager.executeGesture (14:49:09.496):
Input: kb(laptop):n
IO - inputCore.InputManager.executeGesture (14:49:12.203):
Input: kb(laptop):tab
IO - inputCore.InputManager.executeGesture (14:49:14.150):
Input: kb(laptop):tab
IO - inputCore.InputManager.executeGesture (14:49:16.082):
Input: kb(laptop):tab
IO - inputCore.InputManager.executeGesture (14:49:18.706):
Input: kb(laptop):space

**Comment by Brian1Gaff** [comment]
I wonder what audiodg.exe. was doing during all this?
 Brian

**Comment by Adriani90** [comment]
@fernando-jose-silva are you still having this problem?
In the future if you see such issues which are not occuring everytime, you could firstly ask on the user list if someone else has this problem. You get much more feedback on that list and after you have an idea where it could come from, you can create an issue on Github with more details. This helps in turn to solve issues in a more efficient way. Thanks!.

**Comment by fernando-jose-silva** [comment]
All software has changed, using:
nvda alfa 17134
windows 10 1903 18362.86
I no longer received a lock.
Thank you.

**Comment by Adriani90** [comment]
Closing as works for me.
