### ISSUE TITLE
Audacity AppModule out-of-date

### ISSUE THREAD

**Issue by Robert-J-H** [nvaccess/nvda#8178]
### Steps to reproduce:
This relates to any buttons in Audacity.
The name of the button is taken from the window text rather than the accessible name.
This leads to e.g. the result that the help button is rendered as "?" (question mark) instead of "Help" in 2.3.0 Alpha.
What's more, radio buttons use the terser labels visible, rather than the more meaningful accessible ones

### Expected behavior:
NVDA should take the IAccessible name as the button label

### Actual behavior:
NVDA replaces the name with the windowText instead.

This was once (many years back) a valid workaround.

However, this is no longer needed for Audacity versions 2.0 plus and the developers requested that this should be changed since the old versions are no longer supported. 
The replacement of the ampersand sign can be kept for now although it isn't needed for recent versions.

### System configuration:
NVDA version next-15028,2754a2c8
Installed/Source/portable
Windows 10 (x64), Version 1803 (OS Build 17133.73)
Name and version of other software in use when reproducing the issue:
Audacity 2.0.0 --> 2.3.0 Alpha

### proposed change in "Audacity.py":
- Old line 15:
> obj.name=winUser.getWindowText(obj.windowHandle).replace('&','')
- New line 15:
> obj.name=obj.name.replace('&','')

Let me know if you need a pull request for this insubstantial change.

**Comment by derekriemer** [comment]
Go ahead

**Comment by Robert-J-H** [comment]
Thanks Derek

I was about to do that.
However, I had some problems with the 2.3.0 Alpha build due to an
ongoing migration to WxWidgets 3.1.1.
I hope we're able to sort these issues out before releasing officially (in May).
Nonetheless, the statements in this issue still hold for the released versions.

**Comment by Robert-J-H** [comment]
Turned out that the fault was in a missing module within Audacity Alpha.
Works smooth now.
Therefore, pull request #8181 created.

**Comment by seanbudd** [comment]
Closing as fixed by #8181
