### ISSUE TITLE
Language switching not working properly for Chinese

### ISSUE THREAD

**Issue by Porges** [nvaccess/nvda#8185]
### Steps to reproduce:

1. I have an HTML document that contains `<span lang="zh">六子棋</span>` (the outer text is marked `lang="en"`.
2. When I use an English voice as my main voice the Chinese comes out garbled in Chrome. In Edge it just says "Chinese letter" 3 times.
3. When I use a Chinese voice then it is pronounced properly (aside from the numbers in the output, as reported in #8033).
4. I tried a similar thing with French embedded in English, using an English voice as main, and it appears to be pronounced correctly in Chrome.

### Expected behavior:
The text is pronounced properly.

### Actual behavior:
The text is not pronounced properly.

### System configuration:
NVDA version: 2018.1.1

NVDA Installed or portable: Installed.

Windows version: Windows 10 Version 10.0.17133 Build 17133

Name and version of other software in use when reproducing the issue: Tested in both Chrome ( 65.0.3325.181) & Edge.

### Other questions:

Does the issue still occur after restarting your PC? Unknown

Have you tried any other versions of NVDA? No

**Comment by josephsl** [comment]
Hi, we’re missing an important puzzle piece: what synthesizer is this? Thanks.

**Comment by Porges** [comment]
Sorry, the default one – I think espeak-ng?

**Comment by Porges** [comment]
Here is an example file (I put 3 Cantonese examples as I don't know what language tags NVDA/espeak is meant to recognize here):

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>NVDA test</title>
    </head>
    <body>
        <p>Default Chinese example: <span lang="zh">六卒棋</span></p>
        <p>Cantonese example 1: <span lang="zh-HK">六卒棋</span></p>
        <p>Cantonese example 2: <span lang="zh-yue">六卒棋</span></p>
        <p>Cantonese example 3: <span lang="yue">六卒棋</span></p>
        <p>French example: <span lang="fr">Qu'est-ce que vous aimez faire pendant votre temps libre?</span></p>
    </body>
</html>
```

**Comment by Porges** [comment]
Here is a recording: [Recording.zip](https://github.com/nvaccess/nvda/files/1918240/Recording.zip)

You can hear that the Chinese/Cantonese examples just make a strange noise. The French example works.

It should sound something like this (links to eSpeak testing page):

* [Mandarin](https://odo.lv/Espeak?espeakurl=&eslang=-vcmn&speed=160&output=-w&debug=-x&text=%E5%85%AD%E5%8D%92%E6%A3%8B&formmethod=get)
* [Cantonese](https://odo.lv/Espeak?espeakurl=&eslang=-vyue&speed=160&output=-w&debug=-x&text=%E5%85%AD%E5%8D%92%E6%A3%8B&formmethod=get)

**Comment by zstanecic** [comment]
Hi,
If it is the espeak NG, the cantonese voice in it is broken.

Wysłane z aplikacji Poczta dla Windows 10

Od: George Pollard
Wysłano: вто́рникъ, 17 а҆прі́ллїа л. 2018. 06:32
Do: nvaccess/nvda
DW: Subscribed
Temat: Re: [nvaccess/nvda] Language switching not working properly forChinese (#8185)

Sorry, the default one – I think espeak-ng?

**Comment by josephsl** [comment]
Hi, just to make sure: can you reproduce this with other synthesizers (such as Vocalizer, Windows OneCore voices, etc.)? If this is specific to Espeak NG, then I suggest asking Espeak folks to comment on this. Thanks.

**Comment by Porges** [comment]
I haven't tried it with any others. The documentation says that eSpeak is the only synthesizer that supports language switching..

**Comment by jiangtiandao** [comment]
vocalizer supports language switching too
some addon also support switching between two languages
https://addons.nvda-project.org/addons/dualvoice.en.html
@Porges

**Comment by jiangtiandao** [comment]
Default Chinese example and Cantonese example 1 works on  next-15056
https://www.nvaccess.org/files/nvda/snapshots/
@Porges 
It seems that this issue has been fixed in dev version of espeak.

**Comment by Porges** [comment]
@jiangtiandao thanks, I confirmed it is working with 15056. 👍

**Comment by jiangtiandao** [comment]
Maybe auto language switching cannot detect Cantonese.
You might need to set major voice to Cantonese to get that prouncation
