### ISSUE TITLE
The specified program requires a newer version of windows

### ISSUE THREAD

**Issue by 7dITS** [nvaccess/nvda#8191]
I try to run NVDA and get the error: The Specified program requires a newer version of windows. My computer meets system requirements so I'm not sure what the issue is.

Windows version: Windows 7 Enterprise Service Pack 1 
Running on my local machine.
NVDA version : 2018.1.1
I've uninstalled and rebooted a few times. Every time I run I get the same error.

* If this issue has a resolution please direct me to it. Thanks in advance! 

![image](https://user-images.githubusercontent.com/24323027/38938666-16fce3e2-42f4-11e8-9c8e-7a4754ef5110.png)

**Comment by leonardder** [comment]
Interesting report @7dITS, I could imagine that this is annoying.

Is NVDA 2018.1.1 the first version of NVDA you tried to use, or did older versions (e.g. 2017.4, 2017.3) work for you?

**Comment by Brian1Gaff** [comment]
It is indeed odd as this would tend to indicate that either sp1 is not 
really there or something thinks its not. Would having a dual boot machine 
wwoth xp on another partition affect it? My guess would be no as its not 
runningBrian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by 7dITS** [comment]
@leonardder  I've used older versions and update to 2018.1.1 and it worked fine for a few weeks.  This started happening this week. Do you think I should revert back to the older version?

@Brian1Gaff  I don't  have a dual boot machine. I'm running the screen reader on a work machine. We use VDIs but I did not install the screen reader on the vdi.

**Comment by 7dITS** [comment]
@Brian1Gaff not that I know of.

I tried the portable version and that seems to be working for me. I'll use that going forward. Thanks for the help!

**Comment by leonardder** [comment]
@7dITS It could be that you or your administrator accidentally enabled compatibility mode for NVDA. You can check this by doing the following:

1. Go to NVDA's installation directory, usually `C:\Program Files (x86)\NVDA`
2. For the relevant executables, nvda.exe and nvda_slave.exe, go to the file proprities with alt+enter
3. On the compatibility tab, make sure that the option "Run this program in compatibility mode for:" is disabled
