### ISSUE TITLE
Skype for Business 2016: Incoming Message causes Hang with Latest Version Running

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#8192]
When updating to the latest build of Skype for Business (16.0.4678.1000) with NVDA running, whenever I receive an incoming message the client crashes. Testing with NVDA closed does not cause this to happen; this behaviour can only be observed when the message window is focused. Sending messages to other users works without issue, but it appears that Microsoft have made a change that breaks accessibility here. This was tested with Windows 10 (10.0.15063 Build 15063).

**Comment by leonardder** [comment]
What version(s) of NVDA did you use to test this?

**Comment by elliott94** [comment]
This was tested with the latest Next snapshot (15060,4709bfa7).

**Comment by Adriani90** [comment]
@elliott94 can you still see this issue in last build of Windows 10 1809 with NVDA 2018.4 and last version of Skype for business?

**Comment by elliott94** [comment]
Yes - unfortunately this issue is still present. After some testing, it appears that leaving the Toast notification open in the background will eventually cause the conversation window to automatically open - however, navigating to this when NVDA is running will cause the hang as outlined above.

**Comment by leonardder** [comment]
You're saying that the application crashes. Are you able to provide a crash dump by following [this wiki article](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps#user-content-minidumps-for-other-applications)?

**Comment by elliott94** [comment]
Closing; after testing with multiple different machines with the same Windows 10/Skype for Business builds and NVDA, it appears that the fact that NVDA is running isn't in fact the issue here (despite my initial testing where the application did not crash when NVDA wasn't open). This appears to be an issue with the client itself. Thank you for your help everyone.
