### ISSUE TITLE
Screen Review mode COM error -2147467259 for _get_IA2Attributes with LibreOffice

### ISSUE THREAD

**Issue by vsfoote** [nvaccess/nvda#8197]
### Steps to reproduce:
1. Install any recent version of LibreOffice
2. launch LibreOffice, be sure OpenGL mode is not enabled (checkbox in Tools -> Options -> View)
3. use Object Review mode and open LibreOffice Help -> About dialog
4. use numpad9, numpad6 to advance through lines or word breaks of dialog

5. toggle NVDA to Screen Review mode (NVDA + numpad7) 
6. reopen LibreOffice Help -> About dialog
7. numpad 9 to advance through lines of the dialog

### Expected behavior:
The Screen Review mode navigation through the dialog would sound strings with word breaks matching the Object Review mode, or even of scraping the display. 

### Actual behavior:
Strings sounded in Screen Review drop  characters, and are physically run together, visible in speech viewer and logs, and as sounded.

### System configuration:
NVDA version: 2018.1.1 installed

Windows version:
OS Name	Microsoft Windows 10 Home
Version	10.0.16299 Build 16299

### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
2017.2, 2017.3, 2018.1 originally reported by Zahra on Windows XP

**Comment by vsfoote** [comment]
see LibreOffice tdf#108582 -- https://bugs.documentfoundation.org/show_bug.cgi?id=108582

Here is a clip from NVDA debug level log of the corrupted Screen Review sounding:
Calling idle on audio player
IO - inputCore.InputManager.executeGesture (14:23:30.295):
Input: kb(desktop):numpad9
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (14:23:30.321):
Cancelling
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:23:30.323):
Queue empty, done processing
IO - speech.speak (14:23:30.345):
Speaking [LangChangeCommand (u'en_US'), u'Locale:en-US(en_US); alc: L']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (14:23:30.450):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:23:31.361):
Begin processing speech
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:23:31.361):
oleacc.AccessibleObjectFromEvent with window 6817536, objectID 159 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:23:31.361):
oleacc.AccessibleObjectFromEvent with window 6817536, objectID 160 and childID 0: [Error -2147467259] Unspecified error
DEBUG - synthDrivers.oneCore.SynthDriver._callback (14:23:31.377):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:23:31.377):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:23:34.709):
Queue empty, done processing
IO - inputCore.InputManager.executeGesture (14:23:37.994):
Input: kb(desktop):numpad9
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (14:23:38.010):
Cancelling
IO - speech.speak (14:23:38.032):
Speaking [LangChangeCommand (u'en_US'), u'SeeLog:ef7f8c263fcb2bac596aa0247f1e54ff375c3146']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (14:23:38.247):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:23:39.052):
Begin processing speech
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:23:39.052):
oleacc.AccessibleObjectFromEvent with window 6817536, objectID 161 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:23:39.052):
oleacc.AccessibleObjectFromEvent with window 6817536, objectID 162 and childID 0: [Error -2147467259] Unspecified error
DEBUG - synthDrivers.oneCore.SynthDriver._callback (14:23:39.099):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:23:39.099):
Calling idle on audio player
IO - inputCore.InputManager.executeGesture (14:23:43.503):
Input: kb(desktop):numpad9
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (14:23:43.519):
Cancelling
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:23:43.520):
Queue empty, done processing
IO - speech.speak (14:23:43.542):
Speaking [LangChangeCommand (u'en_US'), u'LibreOfficeDevisamodern,easy-to-use,opensourceproductivity']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (14:23:43.569):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:23:44.552):
Begin processing speech
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:23:44.555):
oleacc.AccessibleObjectFromEvent with window 6817536, objectID 163 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:23:44.555):
oleacc.AccessibleObjectFromEvent with window 6817536, objectID 164 and childID 0: [Error -2147467259] Unspecified error
DEBUG - synthDrivers.oneCore.SynthDriver._callback (14:23:44.571):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:23:44.571):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:23:47.792):
Queue empty, done processing
IO - inputCore.InputManager.executeGesture (14:23:51.559):
Input: kb(desktop):numpad9
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (14:23:51.575):
Cancelling
IO - speech.speak (14:23:51.596):
Speaking [LangChangeCommand (u'en_US'), u'suiteforwordprocessing,spreadsheets,presentationsandmore.']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (14:23:51.729):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:23:52.618):
Begin processing speech
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:23:52.618):
oleacc.AccessibleObjectFromEvent with window 6817536, objectID 165 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:23:52.618):
oleacc.AccessibleObjectFromEvent with window 6817536, objectID 166 and childID 0: [Error -2147467259] Unspecified error
DEBUG - synthDrivers.oneCore.SynthDriver._callback (14:23:52.634):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:23:52.634):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:23:55.627):
Queue empty, done processing
IO - inputCore.InputManager.executeGesture (14:23:59.450):
Input: kb(desktop):numpad9
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (14:23:59.467):
Cancelling
IO - speech.speak (14:23:59.482):
Speaking [LangChangeCommand (u'en_US'), u'hisreleasewassuppliedbytinderbox.']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (14:23:59.549):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:24:00.496):
Begin processing speech
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:24:00.496):
oleacc.AccessibleObjectFromEvent with window 6817536, objectID 167 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:24:00.496):
oleacc.AccessibleObjectFromEvent with window 6817536, objectID 168 and childID 0: [Error -2147467259] Unspecified error
DEBUG - synthDrivers.oneCore.SynthDriver._callback (14:24:00.510):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:24:00.510):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:24:02.595):
Queue empty, done processing
IO - inputCore.InputManager.executeGesture (14:24:03.059):
Input: kb(desktop):numpad9
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (14:24:03.075):
Cancelling
IO - speech.speak (14:24:03.084):
Speaking [LangChangeCommand (u'en_US'), u'opyright\xa92000\u20132018LibreOfficecontributors.']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (14:24:03.335):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:24:04.112):
Begin processing speech
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:24:04.112):
oleacc.AccessibleObjectFromEvent with window 6817536, objectID 169 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:24:04.112):
oleacc.AccessibleObjectFromEvent with window 6817536, objectID 170 and childID 0: [Error -2147467259] Unspecified error
DEBUG - synthDrivers.oneCore.SynthDriver._callback (14:24:04.144):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:24:04.144):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:24:07.993):
Queue empty, done processing

**Comment by zahra21** [comment]
hi stuart.
thanks extremely for your great efforts for improving accessibility for screen reader users!
i tested with many versions of nvda since 2014.4 until 2017.3, so i believe that nvda version number does not matter.
nvda does not recognize dialogs and messages in libreoffice using harfbuzz in screen review.
aabout libreoffice is just one example: it affects all the messages, dialogs or any information that we want to recieve by using screen review.

**Comment by vsfoote** [comment]
This would not be a HarfBuzz issue--wrong way to think.  In implementing HarfBuzz the font handling (that exposes strings to the UI) had to be reworked.

It is that font handling, not HarfBuzz shapping, that the NVDA  IAcceessible module in "Screen review" is no longer parsing correctly for the GDI based "default" rendering mode of LibreOffice.  While "Object review" and graphics API "scrapping"  (with mouse movements) continues to sound the GUI with reasonable fidelity.

The issue is with the NVDA modules feeding Screen review mode--for modern Direct3D DirectWrite string handling (as used for OpenGL) and for hybrid GDI implementations that mix calls.

**Comment by Adriani90** [comment]
might be related to #7892

**Comment by Adriani90** [comment]
@vsfoote, @zahra21 are you still seeing this issue in NVDA 2019.1.1? I am testing with Libre Office 6.2.2 and I can navigate the dialog in screen review without any errors or sounds or word breakages.
If you still have this issue, I wonder if it happen also when you use a higher DPI for your display?

**Comment by Adriani90** [comment]
cc: @leonardder

**Comment by Adriani90** [comment]
We do not have any updates from the initial author since more than one year. And I cannot reproduce it with NvDA 2019.3 RC2 on Libre Office 6.4. Closing as abandoned and works for me.
