### ISSUE TITLE
impossible to browse the entire table on the site.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8199]
### Steps to reproduce:
open the site:

https://software.cisco.com/download/home/284324806/type/284006014/release/12.0%25280%2529

Press t to go to the first table on the page.
Now press ctrl + alt + arrows below to navigate through the various columns of the table.

### Expected behavior:
you can navigate the table lines with ctrl + alt + arrows below.
### Actual behavior:
It will be stuck in 2 lines.
If you use only the arrows below you will see that there are other lines with other items to download.

### System configuration:
NVDA version:
next 15056

NVDA Installed or portable:
instaled
Other information:
> Example: Running in a VM

Windows version:
windows 7

Name and version of other software in use when reproducing the issue:
chrome  65.0.3325.181 
### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
> Please list them and the result
no

**Comment by Adriani90** [comment]
This is working in Chrome 74 with NVDA 2019.1.1. Closing as works for me.
Fernando if you are still having this problem though, please comment on it and we can reopen the discussion. Please make sure that you test with addons disabled.
