### ISSUE TITLE
NVDA should support Apple's Safari Browser

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#820]
**Reported by ManuelRamos on 2010-08-08 20:38**
It would be very usefull that NVDA could support Apple's safari browser. Now NVDA is making big progress supporting it. It is now possible to access menubars by pressing alt; and read all information displayed. However, Safari is not yet accessible when clicking on lnks to access new pages. So, it would be fantastic that support can be mmprouved.

**Comment by jcsteh** [comment]
Safari for Windows is a dead product, so closing.
