### ISSUE TITLE
Support aria-roledescription for web content

### ISSUE THREAD

**Issue by wnayes** [nvaccess/nvda#8200]
With #7112, it seems much of the plumbing is in place to support the `aria-roledescription` attribute in web content.

https://www.w3.org/TR/wai-aria-1.1/#aria-roledescription

---

Personally, I'm interested in this feature to be able to rename an `application` role region, since NVDA seems to announce "application" when transferring focus into a region with that role. I'd like to at least make it more descriptive if I can't stop that announcement.

**Comment by Malvoz** [comment]
Looks like this was fixed in https://github.com/nvaccess/nvda/pull/8346.

**Comment by Adriani90** [comment]
Closing as fixed.
