### ISSUE TITLE
The eclipse module does not to be loading

### ISSUE THREAD

**Issue by ak104** [nvaccess/nvda#8203]
Seems, The eclipse.py module does not to be loading. Had to copy javaw.py in java.py to make the module work.

**Comment by Adriani90** [comment]
cc: @michaelDCurran not sure but i think this might be a quick fix for the app module right?

**Comment by lukaszgo1** [comment]
The description of this issue is not really actionable IMHO. @ak104 Would  you be able to fill the issue template with the clear steps to reproduce? Otherwise I vote to close this.

**Comment by Adriani90** [comment]
No updates from the initial author since many years and also the description is too vague. I am closing as abandoned since information is missing upon request since years. Please open a new issue with more details about the problem.
