### ISSUE TITLE
live region announced only after next label is focused and announced; when using down arrow to browse

### ISSUE THREAD

**Issue by detoxfarm3** [nvaccess/nvda#8205]
### Steps to reproduce:
A list of the steps you take to demonstrate the problem. 

Use following aria tags for live region; aria-atomic="true" aria-live="assertive". This region is present after each textbox and generates error dynamically if textbox left empty. 

Browse this registration page using down arrow key.

### Expected behaviour:
>When browsing this registration page with down arrow, if multiple controls are present; when ever a input is left blank and focus moved to next element the error is announced only after the next label is announced. but, same works fine when using tab.

### Actual behaviour:
>First the error should be announced then the next label. same behaviour as tab.

### System configuration:
>NVDA version: 2018.1

>NVDA Installed or portable: portable

Other information:
>Running in VM, React website
>nvda screenshot of the problem- https://i.stack.imgur.com/dI6k2.png 
[code.txt](https://github.com/nvaccess/nvda/files/1946253/code.txt)

>asked the same question - https://stackoverflow.com/questions/49996152/nvda-screen-reader-aria-live-issue 

Windows version:
>Windows 2012 R2 Standard
>Firefox 59.0.2

Does the issue still occur after restarting your PC?
>Yes
Have you tried any other versions of NVDA?
>Same result when using 2017.4

**Comment by detoxfarm3** [comment]
Can any one please help me with this, thanks in advance

**Comment by RichCaloggero** [comment]
THis is not a use case for live regions. If a validation error is generated, then use browser validation facilities. Generally, it's better to validate on submit; tends to be less confusing for users. The browser validation API can automatically focus the first field which is invalid when you attempt to submit, and if an error message is properly associated via aria-describedby, then the error message will be read along with the field label when the field gains focus.

Hope this helps.

**Comment by Adriani90** [comment]
I am closing this as completed since a proposal for a solution has been provided in the last comment above.
