### ISSUE TITLE
NVDA plays its error sound while executing the time progress commands in Foobar2000 when playback is stopped

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#8209]
### Steps to reproduce:
1. Open Foobar2000.
2. Press Control+Shift+E, Control+Shift+R or Control+Shift+T, while playback is stopped.

### Expected behavior:
NVDA should report that there is no track playing.

### Actual behavior:
NVDA plays its error sound and then reports that there is no track playing.

### System configuration:
- Operating system: Windows 10 Pro version 1709 (build 16299.402), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: next-15060,4709bfa7.
- Foobar2000 version: 1.3.17.
- Processor: Intel Core i5-4670 at 3.40GHz.
- RAM Memory: 8.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC887 at Intel Lynx Point PCH - High Definition Audio Controller.

### Other questions:
- The issue occurs even with add-ons disabled.
- I'm attaching NVDA's log file with the errors about Foobar2000, with logging level set to "Debug".
[nvda-old.log](https://github.com/nvaccess/nvda/files/1950536/nvda-old.log)

**Comment by leonardder** [comment]
I can reproduce this.

**Comment by tuukkao** [comment]
Fixed. Want me to open a separate pr or would pushing to #6607 work?

**Comment by leonardder** [comment]
Pushing to #6607 makes sense, as it is still incubating.

**Comment by Adriani90** [comment]
@k-kolev1985 the PR above has been merged some versions ago. Are you still having this issue?

**Comment by k-kolev1985** [comment]
@Adriani90 No, the problem has been fixed, so I'm closing the issue.
