### ISSUE TITLE
Navigating quickly in edit fields on GMail causes NVDA to change from focus to browse mode unexpectedly

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#8211]
When typing a message in Gmail, if navigating quickly - eg rapidly pressing or holding down an arrow key to move through text, or backspace or a character, NVDA jumps from focus mode to browse mode.

In Chrome, the log looks like:

IO - inputCore.InputManager.executeGesture (13:07:32.154):
Input: kb(desktop):control+rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (13:07:32.232):
Caret move detected using bookmarks. Elapsed: 40 ms
IO - speech.speak (13:07:32.247):
Speaking [LangChangeCommand ('en_GB'), u'org/']
IO - inputCore.InputManager.executeGesture (13:07:32.250):
Input: kb(desktop):control+rightArrow
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (13:07:32.355):
COM pointer <POINTER(IAccessibleText) ptr=0x813244c at 5102670> already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (13:07:32.355):
COM pointer <POINTER(IAccessibleTable2) ptr=0x813232c at 51023f0> already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (13:07:32.357):
COM pointer <POINTER(IAccessibleAction) ptr=0x8132134 at 5102120> already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (13:07:32.357):
COM pointer <POINTER(IAccessible2) ptr=0x81320a4 at 51028f0> already deleted
IO - inputCore.InputManager.executeGesture (13:07:32.371):
Input: kb(desktop):control+rightArrow
IO - speech.speak (13:07:32.390):
Speaking [LangChangeCommand ('en_GB'), u'out of edit', u'button', u'Send ']
IO - speech._speakSpellingGen (13:07:32.407):
Speaking character u'\u202a'
DEBUG - queueHandler.registerGeneratorObject (13:07:32.407):
Adding generator 114
DEBUG - queueHandler.pumpAll (13:07:32.407):
generator 114 finished
IO - inputCore.InputManager.executeGesture (13:07:32.490):
Input: kb(desktop):control+rightArrow
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (13:07:32.555):
COM pointer <POINTER(IAccessibleText) ptr=0x813244c at 51022b0> already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (13:07:32.555):
COM pointer <POINTER(IAccessibleTable2) ptr=0x813232c at 5102080> already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (13:07:32.556):
COM pointer <POINTER(IAccessibleAction) ptr=0x8132134 at 5102ad0> already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (13:07:32.556):
COM pointer <POINTER(IAccessible2) ptr=0x81320a4 at 5102260> already deleted
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (13:07:32.563):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - speech.speak (13:07:32.585):
Speaking [LangChangeCommand ('en_GB'), u'(Ctrl-']

In Firefox, it does the same thing, though it seems a little more robust and harder to reproduce. 
 Occasionally the log records one of those get_IAccessibleRole incorrect parameter warnings:

IO - inputCore.InputManager.executeGesture (13:20:10.740):
Input: kb(desktop):rightArrow
IO - speech._speakSpellingGen (13:20:10.752):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (13:20:10.752):
Adding generator 199
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (13:20:10.760):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUG - queueHandler.pumpAll (13:20:10.763):
generator 199 finished
IO - speech._speakSpellingGen (13:20:10.767):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (13:20:10.767):
Adding generator 200
IO - speech._speakSpellingGen (13:20:10.773):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (13:20:10.773):
Adding generator 201
IO - inputCore.InputManager.executeGesture (13:20:10.773):
Input: kb(desktop):rightArrow
IO - speech._speakSpellingGen (13:20:10.779):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (13:20:10.779):
Adding generator 202
IO - speech._speakSpellingGen (13:20:10.783):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (13:20:10.785):
Adding generator 203
IO - speech._speakSpellingGen (13:20:10.789):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (13:20:10.789):
Adding generator 204
IO - inputCore.InputManager.executeGesture (13:20:10.806):
Input: kb(desktop):rightArrow
IO - inputCore.InputManager.executeGesture (13:20:10.839):
Input: kb(desktop):rightArrow
IO - inputCore.InputManager.executeGesture (13:20:10.872):
Input: kb(desktop):rightArrow
IO - inputCore.InputManager.executeGesture (13:20:10.905):
Input: kb(desktop):rightArrow
IO - inputCore.InputManager.executeGesture (13:20:10.938):
Input: kb(desktop):rightArrow
IO - inputCore.InputManager.executeGesture (13:20:10.971):
Input: kb(desktop):rightArrow
DEBUG - queueHandler.pumpAll (13:20:10.980):
generator 200 finished
DEBUG - queueHandler.pumpAll (13:20:10.980):
generator 201 finished
DEBUG - queueHandler.pumpAll (13:20:10.980):
generator 202 finished
DEBUG - queueHandler.pumpAll (13:20:10.980):
generator 203 finished
DEBUG - queueHandler.pumpAll (13:20:10.980):
generator 204 finished
IO - speech._speakSpellingGen (13:20:10.986):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (13:20:10.986):
Adding generator 205
IO - speech._speakSpellingGen (13:20:10.990):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (13:20:10.992):
Adding generator 206
IO - speech._speakSpellingGen (13:20:10.996):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (13:20:10.996):
Adding generator 207
IO - speech._speakSpellingGen (13:20:11.002):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (13:20:11.002):
Adding generator 208
IO - inputCore.InputManager.executeGesture (13:20:11.006):
Input: kb(desktop):rightArrow
IO - speech._speakSpellingGen (13:20:11.007):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (13:20:11.007):
Adding generator 209
IO - speech._speakSpellingGen (13:20:11.013):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (13:20:11.013):
Adding generator 210
IO - speech._speakSpellingGen (13:20:11.019):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (13:20:11.019):
Adding generator 211
IO - inputCore.InputManager.executeGesture (13:20:11.038):
Input: kb(desktop):rightArrow
IO - speech.speak (13:20:11.071):
Speaking [LangChangeCommand ('en_GB'), u'Add Cc Recipients \u202a(Ctrl-Shift-C)\u202c', u'link']

It might well be that this is an issue with GMail, but I thought it was worth recording since GMail is such a popular site and there may be something we can do.  Using latest versions of Chrome and Firefox, and latest Next snapshot of NVDA, although I have noticed these issues for a few months.

**Comment by Brian1Gaff** [comment]
Hmm, I've seen something similar in the Alexa App in firefox together with a very long lag before a pressed key is read making every keypress sound double.
You end up typing v  e r y s l o w so you do not cursor out of edit, or get a missed or double character!

 Brian

**Comment by Adriani90** [comment]
This will also probably be fixed by fast browse mode. CC: @mltony

**Comment by Adriani90** [comment]
@Qchristensen do you see the same behavior in NVDA 2019.3 Beta 1?
Does it make a difference when you disable automatically move system focus to focusable elements with nvda+8?
I guess overall at least in Firefox the situation should be much better now.

**Comment by Qchristensen** [comment]
It seems to behave mostly find in 2019.3beta1.  I did find a couple of times when it gets to the very start or end of a message it jumps out of it, but not consistently, and not so often.  I went back to 2019.2.1 to try and it's working fairly well now too - I wonder if Google have fixed something?

**Comment by Adriani90** [comment]
Definitely Google Chrome and Firefox there have been several fixes in the last two releases with regard to accessibility. Could you test in Chrome 81 and Firefox 75?
I see some comtypes errors in Chrome while navigating with arrow keys in browse mode, but it doesn't switch to focus mode very often when pressing quick navigation keys.
Imo this is really hard to investigate but it might be related to the com pointers not clearly detected in the virtual buffer.
@leonardder has greatly contributed to this some months ago I think.

**Comment by Qchristensen** [comment]
It does seem to be better now.  I'll have to keep an eye on it and see if it happens again.  I'll close for now.  We can reopen if we get more information or a reproducible scenario.
