### ISSUE TITLE
In Google Chrome, NVDA does not initially read toolbar buttons when tabbed to.

### ISSUE THREAD

**Issue by RD-Brown** [nvaccess/nvda#8222]
### Steps to reproduce:
1.	In Chrome, open the attached file, nvdareading.html.
2.	From the top of the page, press Tab, and note that the toolbar receives focus as expected.
3.	Press Tab again, and note that NVDA says nothing.
4.	Press Tab again, and note that NVDA still says nothing.
5.	Finally, press Tab again, and note that NVDA says, “Button 2 label, toggle button not pressed,” the second button in the toolbar.

### Expected behavior:
NVDA should read each button when it is tabbed to.

### Actual behavior:
When the toolbar has focus, NVDA remains silent for the first two presses of Tab.

### System configuration:
NVDA version: 2018.1

NVDA Installed or portable: Installed

Other information:

Windows version: Windows 7 Enterprise

Name and version of other software in use when reproducing the issue: Google Chrome V66.0.3359.139

### Other questions:

Does the issue still occur after restarting your PC? Yes
[nvdareading.zip](https://github.com/nvaccess/nvda/files/1964929/nvdareading.zip)

Have you tried any other versions of NVDA? No

**Comment by Adriani90** [comment]
This seems strongly related to #6672. @derekriemer, @feerrenrut should this be closed as duplicate?

**Comment by Adriani90** [comment]
This works as expected now in NVDA Version: alpha-28130,aOf16eOb (2023.2.0.28130) and Chrome, Firefox and Edge 112. Closing as works for me.
