### ISSUE TITLE
windows 10 emoji support 

### ISSUE THREAD

**Issue by adil-s** [nvaccess/nvda#8223]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result
I'm using NVDA version 2018.1. I am not able to access the emoji panel in windows 10 version 1803. when I press win + . to open emoji panel, nothing happens. but narrator works well with this emoji panel.

**Comment by josephsl** [comment]
Hi,

This work is being tested at the moment (#7273). As an alternative, please install Windows 10 App Essentials add-on.

Thanks.
