### ISSUE TITLE
lag in explorer 1803

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#8224]
hello all.

after installing build 1803 of windows 10 i discovered a lag of second or two in explore.

when deleting something or pasting from somewhere, nvda stops reacting for about 1-2 seconds.
this doesn't happen with narrator.

**Comment by zstanecic** [comment]
I can confirm that, using latest master snapshot.
Can it be connected whth the large UIA miscommunication?

Wysłane z aplikacji Poczta dla Windows 10

Od: beqa gozalishvili
Wysłano: środa, 2 maja 2018 16:18
Do: nvaccess/nvda
DW: Subscribed
Temat: [nvaccess/nvda] lag in explorer 1803 (#8224)

hello all.
after installing build 1803 of windows 10 i discovered a lag of second or two in explore.
when deleting something or pasting from somewhere, nvda stops reacting for about 1-2 seconds.
this doesn't happen with narrator.

**Comment by beqabeqa473** [comment]
unfortunately, i don't know.

maybe more competent people in this area will tell something.

On 5/2/18, zstanecic <notifications@github.com> wrote:
> I can confirm that, using latest master snapshot.
> Can it be connected whth the large UIA miscommunication?
>
> Wysłane z aplikacji Poczta dla Windows 10
>
> Od: beqa gozalishvili
> Wysłano: środa, 2 maja 2018 16:18
> Do: nvaccess/nvda
> DW: Subscribed
> Temat: [nvaccess/nvda] lag in explorer 1803 (#8224)
>
> hello all.
> after installing build 1803 of windows 10 i discovered a lag of second or
> two in explore.
> when deleting something or pasting from somewhere, nvda stops reacting for
> about 1-2 seconds.
> this doesn't happen with narrator.
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/8224#issuecomment-385995929


-- 
with best regards beqa

**Comment by Neurrone** [comment]
Pretty sure this is the same as #8145.

**Comment by Neurrone** [comment]
Hm, any chance this could be prioritized for fixing? I'm also hearing more complaints of this from others besides experiencing this daily myself.

**Comment by Adriani90** [comment]
@beqabeqa473, @Neurrone, @rbc3585 could you please test with last NVDA alpha if this lag is still occuring in Windows Explorer on Windows 10 last update or Windows 11? I cannot reproduce at least on Windows 11.

You can download the last NVDA alpha version here:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Neurrone** [comment]
Haven't seen this happening for some time now.

**Comment by Adriani90** [comment]
Thanks for reporting. I am closing this issue as works for me, but feel free to comment if you are still having it and we can reopen.

**Comment by Adriani90** [comment]
@beqabeqa473 I can notice a significant difference between NVDA 2023.1 and the last alpha version of NVDA. Can you also confirm whether there is a difference for you between NVDA 2023.1 and NVDA last alpha version?

**Comment by Adriani90** [comment]
@beqabeqa473 could you please answer my question above and test with last alpha?
Also I found lot of information in the web describing that the Windows widgets and the windows input experience cause a significant lag in the file explorer. Could you please try to disable these in the registry and see if it makes a difference on your end?
Here is a tutorial on how to do it:

To stop Windows input Experience:
1. Press the windows key and r key (at the same time) to bring up the run application.
2. Type "regedit" and press enter. At the prompt, click the yes button to allow the registry editor to run and make changes to your computer.
3. Click on the arrows to expand tree of each key Starting at HKEY_CURRENT_USER to navigate to 
HKEY_CURRENT_USER\Software\Microsoft\Input
4. Press tab to land in the pane on the right side, and press down arrow key to reach IsInputAppPreloadEnabled item
5. Open its context menu and press enter on  "Modify". In the edit field, change the value from 1 to 0.
6. Close the registry editor, and then sign out, or shutdown, or restart your computer. When you sign in Windows input experence should no longer run in background.


To stop Windows Widgets from running in the background go to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Dsh in the registry and set IsPrelaunchEnabled value to 0

**Comment by Adriani90** [comment]
note that these performance issues are not only related to nvda. See for example this link:
https://borncity.com/win/2022/12/08/windows-11-input-experience-consumes-20-cpu-power-in-file-explorer/

**Comment by beqabeqa473** [comment]
I cannot reproduce a slowdown on win11 23h2 with latest alpha,
howevere i still can observe a behaviour, when i am going to drive
which is not spinned up yet, it is an external harddisk, and it is
spinning up 3-4 seconds, and in this case, nvda is not responding.

I cannot test with other NVDA version for now.

On 11/18/23, Adriani90 ***@***.***> wrote:
> note that these performance issues are not only related to nvda. See for
> example this link:
> https://borncity.com/win/2022/12/08/windows-11-input-experience-consumes-20-cpu-power-in-file-explorer/
>
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/8224#issuecomment-1817300640
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Adriani90** [comment]
Are other screenreaders also suffering from this performance issue with the external drive? Could you test with Narator at least?

**Comment by Adriani90** [comment]
@beqabeqa473 could you please resopnd to my comment above? are you seeing this also with Narator or any other screen reader?

**Comment by beqabeqa473** [comment]
No, it is not happening with narrator, and i am not seeing this bug very often nowadays. Speed in explorer is acceptable with latest windows 11 23h2.

**Comment by josephsl** [comment]
Hi,

Note that Windows 10 1803 is out of support from Microsoft. I'm in favor of closing this issue for now based on latest report from Beqa.

Thanks.
