### ISSUE TITLE
add the armenian table to NVDA

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#8228]
in the Liblouis, we have armenian 8-dots table named hy.ctb
latin script is excluded, wich is good for the braille imput too.
can someone add this table to NVDA

**Comment by leonardder** [comment]
Looks like I can do this as part of #8227

**Comment by leonardder** [comment]
I've tested this table and indeed, it doesn't do anything for latin letters at all. If I use the Arabic table, there is proper support for latin letters, I believe based on UEB or something similar.

How are you supposed to deal with latin letters if the table doesn't support them at all?

**Comment by zstanecic** [comment]
Well,
it can be fixed temporarily by using Braille extender’s secondary Braille table function. 
Thanks!

Wysłane z aplikacji Poczta dla Windows 10

Od: Leonard de Ruijter
Wysłano: czwartek, 3 maja 2018 14:35
Do: nvaccess/nvda
DW: zstanecic; Author
Temat: Re: [nvaccess/nvda] add the armenian table to NVDA (#8228)

I've tested this table and indeed, it doesn't do anything for latin letters at all. If I use the Arabic table, there is proper support for latin letters, I believe based on UEB or something similar.
How are you supposed to deal with latin letters if the table doesn't support them at all?

**Comment by zstanecic** [comment]
Well, if this table hasn’t assed the tests, it wouldn’t be included in liblouis
Thanks!

Wysłane z aplikacji Poczta dla Windows 10

Od: Joseph Lee
Wysłano: czwartek, 3 maja 2018 16:12
Do: nvaccess/nvda
DW: zstanecic; Author
Temat: Re: [nvaccess/nvda] add the armenian table to NVDA (#8228)

Hi, has this table seen any real life usage (such as passing tests and such)?

**Comment by josephsl** [comment]
Hi, to me, that’s not a good justification to work on this unless the table itself provides support in one form or another. Thanks.

**Comment by josephsl** [comment]
Hi, I’m more worried about real-life tests (such as being tested by another person, not just going through automated tests). Thanks.

**Comment by zstanecic** [comment]
Support for what, 
Can you be more specific?


Wysłane z aplikacji Poczta dla Windows 10

Od: Joseph Lee
Wysłano: czwartek, 3 maja 2018 16:18
Do: nvaccess/nvda
DW: zstanecic; Author
Temat: Re: [nvaccess/nvda] add the armenian table to NVDA (#8228)

Hi, to me, that’s not a good justification to work on this unless the table itself provides support in one form or another. Thanks.

**Comment by josephsl** [comment]
Hi, issues raised by @LeonardDer.

**Comment by leonardder** [comment]
As long as this table doesn't support the latin alphabet correctly, I'm afraid we can't support this table within NVDA

**Comment by Adriani90** [comment]
Given the comment above by @leonardder, I am closing this issue for now. Please feel free to raise an issue on Liblouis first and when the table is supporting latin letters, then we can consider supporting this in NVDA.
