### ISSUE TITLE
Offer.

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#8238]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result
Hello. I have a friend he knows Russian English and French. He'd like to be a NVDA translator. What does he have to do?

**Comment by ehollig** [comment]
Hello @gdata1,
Please send your friend the links for [Translating NVDA](https://github.com/nvaccess/nvda/wiki/Translating) and the link to [subscribe to the NVDA translations mailing list](https://groups.io/g/nvda-translations). Closing, as this is a request for information and not an NVDA issue.
CC @josephsl
