### ISSUE TITLE
Firefox - NVDA isn't reading aria-label on focused element but instead some of the element's contents

### ISSUE THREAD

**Issue by JllyGrnGiant** [nvaccess/nvda#8251]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
> 1. Open Firefox
> 2. Browse to https://jsfiddle.net/erxv6rkp/2/
> 3. Run example
> 4. Tab to outer focusable div (the red background box will turn green)
> 5. Notice the aria-label for the div isn't read but instead the table content inside is read

### Expected behavior:
> NVDA should say
```
Chart not available to screen readers. Sibling table element contains screen reader available representation of chart
```

### Actual behavior:
> NVDA says 
```
frame
 table  with 2 rows and 3 columns 
row 1  column 1
Column 1
column 2
Column 2
row 2  Column 1  column 1
Row 1
Column 2  column 2
1
column 3
2
```

### System configuration:
NVDA version:
> 2018.1.1

NVDA Installed or portable:
> Installed

Other information:
> Using Firefox 59.0.3 (64-bit)

Windows version:
> Example: Windows 10 Version 1803 Build 17134.1

Name and version of other software in use when reproducing the issue:
> Using Firefox 59.0.3 (64-bit)

### Other questions:

Does the issue still occur after restarting your PC?
> Yes

Have you tried any other versions of NVDA?
> No

**Comment by janwillemvancappellen** [comment]
You can't use aria-label on div elements. You can aria-label only on interactive elements, landmark role elements, widget role elements, iframe and img elements. Check this source for detailed info: https://developer.paciellogroup.com/blog/2017/07/short-note-on-aria-label-aria-labelledby-and-aria-describedby/

**Comment by Adriani90** [comment]
cc: @jcsteh in case you have another opinion on this, otherwise we can close it I guess? I don't know if there is a way NVDA can handle aria-labeledby on div elements?

**Comment by jcsteh** [comment]
Allowing aria-label to override the content of a div would cause all sorts of problems. A div is often a container or section for a lot of other content and we definitely don't want the label overriding all of the content in those cases. Closing.
