### ISSUE TITLE
NVDA key (insert button) is malfunction on Windows 10

### ISSUE THREAD

**Issue by allaGadvanced** [nvaccess/nvda#8256]
### Steps to reproduce:
> Hi,
I'm trying to use the NVDA key with arrow (down or up) but it won't work as supposed. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Click on NVDA (Insert) key and arrow down key on keyboard at the same time.
> 4. Only next line will read.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Read All starting at current position.

### Actual behavior:
> Only next line reading.

### System configuration:
NVDA version:
> 2018.1.1

Other information:
> Running on a laptop

Windows version:
> Windows 10 Enterprise Version 10.0315063 Build 15063

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
> No

**Comment by mohdshara** [comment]
hi. this is by design. NVDA + down arrow moves the cursor to the next navigator object and speaks it. this means that your keyboard layout is set to the laptop layout. in desktop layout, this command reads from navigator object to the end.

thanks.

**Comment by josephsl** [comment]
Hi, no, not the next object – next review line in laptop layout. Thanks.

**Comment by mohdshara** [comment]
while we're at it, can you close this ticket as invalid? I don't have permission to do so myself.

**Comment by josephsl** [comment]
Hi, will close once we get a response from original poster. Thanks.

**Comment by allaGadvanced** [comment]
Hi,
I wouldn't call it invalid, but anyway, thank you for your response.
