### ISSUE TITLE
In the Windows 10 Twitter app, Compose New Tweet link is not rendered into the virtual buffer, gives error when navigating to it

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#8260]
### Steps to reproduce:
1. [Download the Twitter app](https://www.microsoft.com/store/productId/9WZDNCRFJ140) from the Microsoft store.
2. Log in.
3. Once your Home timeline appears, press CTRL+End to move to the New Tweet link, which is at the very bottom of the document (or bottom right of the screen visually). The result is that you'll hear an error sound after NVDA speaks the Compose New Tweet Link.
4. Press LeftArrow once.
5. Press RightArrow again to return to the link. Result is that the link is again read, but an error sound is heard.

### Expected behavior:
The link should be in the virtual buffer, and no error sound should be heard.

### Actual behavior:
The braille display does not show the link, and an error sound is heard. See attached zipped log file for debug output.

### System configuration:
NVDA version:
version next-15120,817bab86

NVDA Installed or portable: Installed.

Other information: Have a braille display connected.

Windows version:
Version 1803 (Build 17666.1000) - 64 BIT

Name and version of other software in use when reproducing the issue:
Twitter app from Microsoft Store, see link above.

### Other questions:

Does the issue still occur after restarting your PC? Yes.

Have you tried any other versions of NVDA?
Yes, 2018.1, same result.

[NVDA error with New Tweet link in Twitter PWA.zip](https://github.com/nvaccess/nvda/files/1994534/NVDA.error.with.New.Tweet.link.in.Twitter.PWA.zip)

**Comment by Adriani90** [comment]
Under NVDA 2019.1.1 this is much worse now, you cannot access the compose twitter link at all in the buffer. The curssor jumps around to the tweets themselves. You can only access the link with the mouse.
cc: @leonardder

**Comment by Adriani90** [comment]
The design of the app changed since this issue has been submited. Now the compose tweet is a button at the top, however NVDA reads the buttons like it was in screen layout although this setting is disabled. The navigation character by character on these buttons is not working. If you press right or left arrow, NVDA will jump from button to button in browse mode.
cc: @josephsl could you please have a look at the twitter app? Thanks.

**Comment by josephsl** [comment]
Hi, which version is this? The thing is, I don’t use PWA version of Twitter app, although I’ll look at this briefly. Thanks.

**Comment by josephsl** [comment]
Hi, possibly because of text info implementation for EdgeHTML. As the app mirrors Twitter web interface design, I’m leaning towards abandoning this one (Chromium Edge, Chrome, Firefox and friends may provide improved support). Thanks.

**Comment by Adriani90** [comment]
This works as expected now. Closing as works for me. If you are still having this issue, please comment and we can reopen.
