### ISSUE TITLE
nvda crashes windows when opening advanced power options

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8261]
### Steps to reproduce:
My control panel is configured to display items by category.
Open the control panel.
Walk with tabe up system and security.
Open system
Walk through tabe to power options.
Open power options.
Walk with tab until you change plan options ****
Press enter to open the power options for the selected plane.
You will now be on the link changing advanced power settings
press enter to open the advanced power settings.

### Expected behavior:
the advanced power settings must be opened.

### Actual behavior:
the nvda is muted, and from what looks the windows hangs.

### System configuration:
NVDA version:
next 15120
NVDA Installed or portable:
instaled
Other information:
when I open these options using another screen reader the options are displayed normally.
After this problem only restarting windows to be able to open the advanced power settings again with another screen reader.
The problem did not occur in windows 10 build 16299.214

Windows version:
windows 10 build 17134.48 64bits
Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result
no
atached log
[nvdaenerg.txt](https://github.com/nvaccess/nvda/files/1997040/nvdaenerg.txt)

**Comment by Adriani90** [comment]
@fernando-jose-silva are you still having this issue in NVDA 2019.1.1 on Windows 10 1809 Update?

**Comment by fernando-jose-silva** [comment]
everything works now, nvda 17110
windows 10 17763.437
thank you very much.

**Comment by Adriani90** [comment]
Closing as works for me.
