### ISSUE TITLE
Support connection change alerts on Skype desktop version

### ISSUE THREAD

**Issue by OzancanKaratas** [nvaccess/nvda#8267]
NVDA does not speaks about Skype's connection status. If Internet connection is lost NVDA should notify it.

**Comment by Adriani90** [comment]
I am voting actually against implementing such a feature only for skype. There are many other software which require internet connection. Impelmenting such a reporting feature for each of them would be too much work. I suggest to rather implement a reporting feature which reports if the network connection status in the system tray changes (bot for LAN and WLAN). @k-kolev1985, @leonardder, @lukaszgo1, @derekriemer your thoughts on this are very apreciated. Thanks.

**Comment by lukaszgo1** [comment]
I believe that this isn't about detecting connection loss by NVDA them self but rather about reading alert from Skype. I might misunderstand orginal reporter intentions though.

**Comment by Adriani90** [comment]
My understanding was that the author wants NVDA to report if the internet connection is lost while using skype. if skype itself exposes an alert about internet conection, in my view this is not something NVDA should necessarely report. Imagine you have 5 applications which expose such alerts which deliver the same information “internet connection is lost”. Which one will be reported first? In my view, if we knew that the internet connection is lost by the information already shown in system tray, then we can deduct that skype or any other application which requires internet connection is not working anymore and we must reconnect.

 

 

Von: Łukasz Golonka <notifications@github.com> 
Gesendet: Montag, 22. April 2019 23:21
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Support connection change alerts on Skype desktop version (#8267)

 

I believe that this isn't about detecting connection loss by NVDA them self but rather about reading alert from Skype. I might misunderstand orginal reporter intentions though.

**Comment by OzancanKaratas** [comment]
It's okay! Microsoft edited the Windows user interface for connection changes. New Windows release will run well with NVDA. Update it to latest OS build.

Thanks.

This issue can be closed.
