### ISSUE TITLE
In excel, the elements list should show sheets instead of charts by default

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#8269]
Just as it says in the title. If I can find where the code that implements the elements list is, I can try submitting a PR. There doesn't seem to be an excel app module though in the usual places.

**Comment by Neurrone** [comment]
@leonardder having to switch between sheets is a far more common occurance than cycling between charts, at least for my use. Would be interested to hear if this is the case for others as well.

**Comment by leonardder** [comment]
Are you aware of the control+page up/page down shotcuts to switch sheets?

**Comment by Neurrone** [comment]
@leonardder no, actually, thanks for the tip. Still feel that being able to see a list of sheets by default would be more helpful.

**Comment by Adriani90** [comment]
Actually there is a small bar at the bottom of the window in excel where all the sheets are displayed as tabs anc you can reach that area with the mouse. Apparently there is no other way to reach that area, I was expecting to be able to go there by pressing f6 but NVDA skips that bar unfortunately. You can also press right click on a sheet from that tab and you can  add, rename or delete a sheet.
I will close this issue and I will create a new one for the sheet navigation area.

**Comment by Neurrone** [comment]
@Adriani90 yeah that's the reason that I created this issue initially, since optimizing the defaults for the most common case makes more sense.
