### ISSUE TITLE
Arrowing around this worksheet has 2 seconds of lag

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#8271]
### Steps to reproduce:
1. [Download this workbook](https://www.dropbox.com/s/jd3i2ja904dgyta/excel%20lag.xlsx?dl=0)
2. Open it in excel and arrow around.

### Expected behavior:
There should be no lag when moving around the cells.

### Actual behavior:
About 2 seconds of lag every time you move to a new cell.

### System configuration:
NVDA version: master-15118,2229d55a

NVDA Installed or portable: installed

Other information:

Windows version: windows 10 1803

Name and version of other software in use when reproducing the issue: Excel® 2016 MSO (16.0.9226.2156

### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA? No

Other notes: Narrator does not lag at all, maybe because its using UIA?

**Comment by michaelDCurran** [comment]
I have started rewriting Excel support using in-process calls. Please test the following try build and let me know if performance is improved for this particular spreadsheet: https://ci.appveyor.com/api/buildjobs/swea0gjo30lh46rk/artifacts/output%2Fnvda_snapshot_try-excelInproc-16735%2C7b9e0012.exe

**Comment by Neurrone** [comment]
@michaelDCurran this is amazing; the latency is now low enough to be unnoticeable.
