### ISSUE TITLE
What is the expected behavior for HTML text that is highlighted with the <mark> element?

### ISSUE THREAD

**Issue by arodenbeck** [nvaccess/nvda#8273]
I have a scenario where a portion of a word has been highlighted with the <mark> HTML element. When a few letters are highlighted, the word is broken up into the letter grouping, and what is left. If the whole word is highlighted, nothing seems to happen. I have turned on the speaking of attribute changes, but it does not seem to make any difference for <mark> specifically. To further test this, I have tried using <b> and <strong> which both announce "bold" and "unbold" to denote the beginning and end of the text with differing attributes. What should the expectation be for <mark>?

**Comment by derekriemer** [comment]
I'm not sure this forum is the correct place to discuss this. I'd recommend bringing it up on the w3c's lists or an accessibility list.
