### ISSUE TITLE
[Word]: Shape insertion is not proper when NVDA is ON

### ISSUE THREAD

**Issue by WiproPSAccTest** [nvaccess/nvda#8288]
###Steps to reproduce:
1. Open the sample doc 
2. Navigate to the document edit area.
3. Place curser at the document. Observe it is blinking.
4. Navigate to Insert tab--> Shape and select any shape
5. Observe that Curser starts blinking fast and no + symbol is there to insert shape
6. Now select some shape. Observe that curser is not on the text area now.
7. Again navigate to Insert menu--> Shape tab and select any shape
8. Now come to edit area and observe that + symbol is there so you can insert the shape.

### Expected behavior:
Shape insertion should be possible even if curser is at the document edit area, as it is working with narrator

### Actual behavior:
Shape insertion is not possible if curser is on the document edit area, if it is on some illustration then shape can be inserted

### System configuration:
NVDA version: 2018.1.1
App Name: Word
NVDA Installed or portable: Installed
**Other information:**
Windows version:
> Example: Windows 10 Version 1803 Build 17134.48
Name and version of other software in use when reproducing the issue:

### Other questions:
Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
No
> Please list them and the result

**Comment by Adriani90** [comment]
@Qchristensen this issue seems very visual to me. Could you please try to reproduce? Thanks.

**Comment by Qchristensen** [comment]
As per my comment last year on https://github.com/nvaccess/nvda/issues/6141#issuecomment-492517650 and my testing just now, I believe this issue has been resolved (at least in Office 365).

You can insert a shape now in Microsoft Word.

Issue #5738 still exists - it is hard to get information about shapes, so there are still issues with shapes - but you can insert them now.  I'm going to close this as WorksForMe.
