### ISSUE TITLE
Winword/Nvda no interaction with fields in protected doc files

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#829]
**Reported by briang1 on 2010-08-17 09:33**
Problem editing unprotected fields in doc with protected text.

In Hal/Snova 6.5and above, one  can hear, but not alter the text for the fields in a protected areas doc file, and change things like checkbox state and edit in edit areas.
 In nvda, all you get is error sounds when you cursor around the document, and no text is spoken.

Attached is a sample file, a log file with nvda/f1 info included, and a log from Jarte loading the same file.
 The latter of course ignores the  protected and other  flags on the file.

This log is from Word XP but from comments I've had it at least applies to Word 2003 as well.
 I do not know how Dolphin interact with the file unless they use display chaining.
Maybe its OK to read protected text but not edit it?

**Comment by feerrenrut** [comment]
@michaelDCurran There are a handful of attachments missing here. At some stage could you please attach them to this issue? Thanks.

**Comment by feerrenrut** [comment]
Here are the attachments.
[protected doc in jarte.txt](https://github.com/nvaccess/nvda/files/683744/protected.doc.in.jarte.txt)
[winword protected error.txt](https://github.com/nvaccess/nvda/files/683745/winword.protected.error.txt)
[carers_direct_email_form blank.zip](https://github.com/nvaccess/nvda/files/683749/carers_direct_email_form.blank.zip)

**Comment by Adriani90** [comment]
@feerrenrut, @michaelDCurran I have tested this with MS Word 2016, NVDA 2018.3.2 on Windows 10 17134: I can navigate the form in focus mode without any issues in both protected and unprotected document. The labels are announced properly when navigating with up or down arrow key. However, I see following problems:

1. When navigating with tab, labels are ignored by NVDA
2. When navigating in browse mode with down and up arrow keys, NVDA jumps randomly through the form and I land on different positions loosing orientation
3. when trying to navigate with ctrl + arrow keys, NVDA also reacts inconsistent and the cursor is not mooving as expected in a word document.

**Comment by Brian1Gaff** [comment]
Hmm I notice this as well, in that page  boundaries can miss some text 
either side that you know is there. Is it a kind of slugging delay thing 
going on in word. Word closes a lot slower than it used to.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Adriani90** [comment]
@Brian1Gaff can you still reproduce the errors described by you above? The problem in my comment above are not related to protected or unprotected documents. With NVDA 2019.1.1 and MS Word 2010, I cannot reproduce the errors.
@DrSooom could you please try to reproduce this one as well? Thanks.

**Comment by DrSooom** [comment]
@Adriani90: Due to security reasons I'm no longer open doc files with Microsoft Word 2010. And for converting docx files into pdf I'm using LibreOffice Writer 6.2.x. Therefore I'm not going to test this. Furthermore I'm not really familiar with form elements in Word documents.

**Comment by Adriani90** [comment]
@lukaszgo1, @buevest, @hozosch, @gregjozk, @Sylvie42 could anyone of you please try to reproduce this issue? I cannot reproduce the errors described by @Brian1Gaff above. Note that the discussion is a bit longer on this issue.

**Comment by hozosch** [comment]
Can't reproduce this with word 2010 and the attached e mail form. Using windows 7 pro 64 bit and NVDA 2019.1.1
