### ISSUE TITLE
[Word] : Column and Row headers not announced when navigating into a table cell

### ISSUE THREAD

**Issue by WiproPSAccTest** [nvaccess/nvda#8290]
###Steps to reproduce:
1.	Create a 3x3 table in Word
2.	Move from cell (2,2) to cell (2,3)

### Expected behavior:
Should determine the column and/or row headers for each cell

### Actual behavior:
Only announces the position in set for column and row

### System configuration:
NVDA version: 2018.1.1
App Name: Word
NVDA Installed or portable: Installed
**Other information:**
Windows version:
> Example: Windows 10 Version 1803 Build 17134.48
Name and version of other software in use when reproducing the issue:

### Other questions:
Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
No
> Please list them and the result

**Comment by Adriani90** [comment]
@WiproPSAccTest could you please upload a test document where we can test this issue? How did you set the column and row headers in MS Word?
