### ISSUE TITLE
google chrome crashes after being opened and closed several times through the day.

### ISSUE THREAD

**Issue by stickbear2015** [nvaccess/nvda#8297]
### Steps to reproduce:
open and close chrome several times through the day.
### Expected behavior:
chrome should open and close without a problem!
### Actual behavior:
NVDA crashes
### System configuration:
NVDA version:
next-15129,743b57c3

### NVDA Installed or portable:
installed
### Windows version:
windows 10 Version 1803 (OS Build 17134.48)
### Name and version of other software in use when reproducing the issue:
google Chrome Version 66.0.3359.181 (Official Build) (64-bit)
### Does the issue still occur after restarting your PC?
no, rebooting fixes it for awhile
Have you tried any other versions of NVDA?
2018.1.1. Result: no issue.
[errors when opening, and closing google chrome.txt](https://github.com/nvaccess/nvda/files/2015711/errors.when.opening.and.closing.google.chrome.txt)

**Comment by derekriemer** [comment]
can you trigger NVDA to create crash dumps for chrome?
https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps

**Comment by stickbear2015** [comment]
I can't seem to get it to dump a dump file, but here's the log file.
I can attempt to get windows itself to dump minidumps, if that would help, but let's start with this.
[nvda.log.txt](https://github.com/nvaccess/nvda/files/2037672/nvda.log.txt)

**Comment by derekriemer** [comment]
I don't see the infamous "nvda crashed!" message. This is odd. Does NVDA restart itself?

**Comment by stickbear2015** [comment]
I forgot this issue was still open. I fail, lol.
I can't reproduce it on my end either. I'll close it for now unless it comes up again.
