### ISSUE TITLE
NVDA seems to loose information about system caret position in OneNote

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8301]
### Steps to reproduce:
1. Press Windows+n to open a new note in OneNote
2. Write down some text lines
3. Press down arrow multiple times
4. Press up arrow to read previous lines

### Expected behavior:
NVDA shoud, at any time, report the current text line when pressing up and down arrow key.

### Actual behavior:
NVDA is silent after pressing multiple time down arrow. After a while, NVDA gets the system caret position again and continues to work properly until pressing multiple times down arrow key again. Some times you have to press f6 to move to another window area and you have to move back to the text area to make it work again.

### System configuration:
NVDA version:
NVDA 2018.1.1

NVDA Installed or portable:
Installed

Windows version:
Windows 10.0.17134

Name and version of other software in use when reproducing the issue:
OneNote 2016

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No

**Comment by Adriani90** [comment]
This is still reproducible in NVDA 2020.1. In the onenote app for Windows 10 I get following error:

```
IO - inputCore.InputManager.executeGesture (20:19:38.336) - winInputHook (1752):
Input: kb(laptop):downArrow
ERROR - scriptHandler.executeScript (20:19:38.382) - MainThread (8572):
error executing script: <bound method EditableText.script_caret_moveByLine of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x01342FB0>> with gesture 'Pfeiltaste nach unten'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "editableText.pyc", line 219, in script_caret_moveByLine
  File "editableText.pyc", line 161, in _caretMovementScriptHelper
  File "editableText.pyc", line 94, in _hasCaretMoved
  File "documentBase.pyc", line 24, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 307, in __init__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2146233079, None, (None, None, None, 0, None))
```

@Qchristensen could you please describe what happens with the carret visually in Onenote classic? So I mean not in the Windows store app but in the preinstalled version? It seems to me when pressing down arrow multiple times NVDA changes to other content blocks but this is not reported.

**Comment by Qchristensen** [comment]
When you type your new note, it displays a box on screen near the top left of the OneNote window with your text in it.  When you press down arrow, it extends this box down as if you had pressed ENTER.  NVDA reads "Blank".

Once you press down arrow about 8 times, it goes out of the box.  The caret appears to move down about one "line" from where it was previously but the box disappears.  At this point NVDA does not read anything as you arrow around.

The first time you pop out of this box, I get the following in the log:

Input: kb(desktop):downArrow
DEBUG - editableText.EditableText._hasCaretMoved (19:19:49.848) - MainThread (32032):
Caret didn't move before timeout. Elapsed: 100 ms

After that I just get:
IO - inputCore.InputManager.executeGesture (19:19:50.024) - winInputHook (12420):
Input: kb(desktop):downArrow

(for each subsequent down arrow press).

When I press up arrow, after about the third time, it jumps back up into the box and announces that text.

I'm using NVDA 2020.1 and Office 365 (64-bit) Version: 16.0.12827.20258
