### ISSUE TITLE
NVDA does not respect its settings on google groups

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8303]
### Steps to reproduce:
1. Open this website
https://groups.google.com/forum/#!forum/braillists
2. Choose a topic and press "Reply"
3. In NVDA's settings, go to keyboard and disable report characters when typing
4. Go to the edit field with e in browse mode of NVDA and press enter to access the edit field
5. Type something

### Expected behavior:
NVDA should not repeat the characters while typing.

### Actual behavior:
NVDA repeats the characters. In some browsers, NVDA repeats everytime all the characters from the first character typed to the last character being typed. Moreover, when pressing enter or backspace, NVDA repeats the whole topic I am replying to.

### System configuration:
NVDA version:
NVDA 2018.1.1

NVDA Installed or portable:
Installed

Windows version:
Windows 10.0.17134

Name and version of other software in use when reproducing the issue:
Google Crome 66.0, Firefox 60.0.1, IE11.

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No.

**Comment by Adriani90** [comment]
Could it be related to W3C accessibility standards which are not properly implemented? Or did they implement too much accessibility?

**Comment by leonardder** [comment]
Closing in favour of newer duplicate #8442, which has received more attention.
