### ISSUE TITLE
MS Edge: Groups of buttons or edit fields are recognized as table by NVDA and are displayed by NVDA in screen layout

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8305]
### Steps to reproduce:
1. Open this website in MS Edge
https://groups.google.com/forum/#!forum/braillists
2. Go to NVDA's settings and choose browse mode
3. Disable "use screen layout, if available"
4. On google groups, press b to go to "new"

### Expected behavior:
NVDA should read "new" without table coordinates. It should allow to navigate to the next butto by pressing down arrow.

### Actual behavior:
NVDA reports table coordinates. When I want to navigate to the next button in that group, I must press ctrl+right arrow. It is not possible to navigate with a simple press ofdown arrow key although "use screen layout" is disabled. NVDA leaves the group of buttons when presing down arrow.

### System configuration:
NVDA version:
NVDA 2018.1.1

NVDA Installed or portable:
Installed

Windows version:
Windows 10.0.17134

Name and version of other software in use when reproducing the issue:
MS Edge

### Other questions:

Does the issue still occur after restarting your PC?
Yes.

Have you tried any other versions of NVDA?
no

**Comment by leonardder** [comment]
This looks like a duplicate of #7708.

**Comment by Adriani90** [comment]
Tis was indeed a duplicate, I saw this too late. Now everything works fine in Edge Chromium 81. Closing as works for me.

**Comment by Adriani90** [comment]
Adding appropriate label since this is definitely still reproducible in Edge Spartan and UIA related environments.
