### ISSUE TITLE
MS Edge: too many blank lines when navigating in Browse mode with up and down arrow keys.

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8307]
### Steps to reproduce:
1. Open this website
https://groups.google.com/forum/#!forum/braillists
2. Navigate in browse mode by pressing up and down arrow.

### Expected behavior:
NVDA should read aproximately as many blank lines as in other browsers.

### Actual behavior:
In edge in general, NVDA reads much more blank lines compared to other browsers.

### System configuration:
NVDA version:
NVDA 2018.1.1

NVDA Installed or portable:
Installed

Windows version:
Windows 10.0.17134

Name and version of other software in use when reproducing the issue:
MS Edge

### Other questions:

Does the issue still occur after restarting your PC?
Yes.

Have you tried any other versions of NVDA?
No.

**Comment by josephsl** [comment]
CC @MichaelDCurran and perhaps Windows Insiders

**Comment by Adriani90** [comment]
@derekriemer, for example take the google homepage, www.google.com. You will find 5 blank lines in edge and not blank lines at all in other browsers.

Second one is google groups, there are about 7 blank lines in edge, while in other browsers there are just the blank lines in the group description text.

In Wikipedia there are 4 blank line in edge, but no blank lines in other browsers.

**Comment by Adriani90** [comment]
it seems to be ageneral behavior in MS Edge. It is not reproducible on every website but on many.

**Comment by Adriani90** [comment]
This is not the case with Edge Chromium 81. Closing as works for me.

**Comment by Adriani90** [comment]
Adding appropriate label since this is definitely still reproducible in Edge Spartan and UIA related environments.
