### ISSUE TITLE
MS Edge: Change order of reporting information by NVDA

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8308]
### Steps to reproduce:
1. Open google
www.google.com
2. Search for something
3. Navigate by headings in browse mode

### Expected behavior:
NVDA should read the search result first and then the element type (i.e. heading level 2), like in any other browser.

### Actual behavior:
NVDA reads the element type first and then the label itself.

### System configuration:
NVDA version:
NVDA 2018.1

NVDA Installed or portable:
Installed

Windows version:
Windows 10.0.17134

Name and version of other software in use when reproducing the issue:
MS Edge

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No

**Comment by derekriemer** [comment]
yes, this is a bug I believe. Marking such @michaelDCurran

**Comment by surfer0627** [comment]
It seems that this issue is fixed in the newer [microsoft edge stable](https://www.microsoft.com/edge/?form=MO12GK&OCID=MO12GK) (browser based on the Chromium engine).
NVDA reads the search result first and then the element type (i.e. heading level 2), like in any other browser.

**Comment by Adriani90** [comment]
Yes, thanks for asking. I am closing this as works for me.
