### ISSUE TITLE
Multi-category settings: after changing a language and if no NVDA modifier is specified, keyboard settings warning is not shown

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8310]
Hi,

Found a possible refactoring flaw:

### Steps to reproduce:
1. Open NVDA Settings screen.
2. From General category, change UI language to something else.
3. Immediately switch to Keyboard category and uncheck all NVDA modifier checkboxes.
4. Select OK.

### Expected behavior:
Keyboard modifier warning is shown.

### Actual behavior:
Only langue change dialog is shown, and after clicking OK, modifier warning is then shown very briefly.

### System configuration:
NVDA version: next.15133
Tested with other versions: yes.
Tested with add-ons disabled: yes.

Thanks.

**Comment by leonardder** [comment]
Additional to this

1. Open multi category settings
2. IN keyboard settings, disable all modifiers
3. Press ok

### Result
Though you're getting an error that it is unsupported to have no modifier key enabled, the settings dialog is closed after pressing ok. Note that the keyboard settings aren't saved, though.

**Comment by josephsl** [comment]
Hi,

Technical: when OK or Apply buttons are pressed, settings screen will call onSave on all panels and will not check for exceptions, nor perform certain steps prior to calling onSave methods. Depending on which button is pressed and which dialog is shown:
1. General/Language/language is changed/OK button is pressed: core.restart function is called after language change warning is shown.
2. General/Language/language is changed/Apply button is pressed: core.restart is called and discards any changes made in other panels.
3. Keyboard/modifiers/all are not checked/OK button is pressed: modifier warning is shown and keyboard settings are not saved.
4. Keyboard/modifiers/all are not checked/Apply button is pressed: modifier warning is shown and then user is returned to Keyboard panel.
5. Language has changed and all keyboard modifier checkboxes are not checked/OK or Apply button is pressed: language change warning is shown and modifier warning is briefly shown and NVDA restarts.

One possible workaround might be to define a preSave and postSave methods in panels and call them prior to and after onSave. For example:

1. All keyboard modifiers are not checked.
2. OK or Apply button is pressed.
3. A call to presave method is called on all panels first or to a select few.
4. OnSave method is called.
5. In case a user has changed languages, a postSave method is called by the screen and displays warnings if any, provided that this is OK button only.

Thanks.

**Comment by leonardder** [comment]
I second the idea of preSave and postSave handlers. It might make sense 
to make the preSave handlers decider style, i.e. make them return True 
if saving should occur, make them return False otherwise.

An alternative approach could be making the onSave methods raise a 
StopSaveAttempt exception and than catch these exceptions in onOk and 
onApply. It is a bit less elegant, though.

Are you saying you are willing to take this, or should I do it as part 
of #8253.

**Comment by josephsl** [comment]
Hi, I think you should take this on, since you are the expert on multi-category settings. Thanks.
