### ISSUE TITLE
incorect behavior in edit fields in MS Edge

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8312]
### Steps to reproduce:
1. Open any website in MS Edge which contains editfields with alttext and / or alt description (i.e. Wikipedia, Microsoft website etc.)
2. Navigate in browse mode with e to an editfield and press enter to activate focus mode
3. Press left and right arrow key and hear what NVDA is reporting
4. Press ctrl+left or right arrow key and hear what NVDA is reporting
5. Press delete and hear what NVDA is reporting

### Expected behavior:
NVDA should report "blank" in a blank edit field when pressing left and right arrow key, ctrl + arrow keys or delete / backspace. This is the standard case in all other browsers.

### Actual behavior:
In edit fields with alttext or alt description, NVDA reports the first letter of the alttext / alt description or the first word when using arrow keys or ctrl + arrow keys. When pressing delete, NVDA reports the first letter. If there is no alttext, it reports "cariage return" (i.e. on www.google.com). This gives the impression that I delete cariage returns or letters which are not there.

### System configuration:
NVDA version:
NVDA 2018.1.1

NVDA Installed or portable:
Installed

Windows version:
Windows 10.0.17134

Name and version of other software in use when reproducing the issue:
MS Edge

### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
no

**Comment by PratikP1** [comment]
To clarify, NVDA seems to report the first letter or the first word of the label associated with the field. The best example is on Microsoft.com.

**Comment by Adriani90** [comment]
This works as expected in Edge Chromium 81, I am closing as works for me since Edge Chromium will be distributed to most users in Windows 10 20 H1 update.

**Comment by Adriani90** [comment]
Adding appropriate label since this is probably still reproducible in Edge Spartan and UIA related environments.
