### ISSUE TITLE
Keydown Events for Enter Key Not Firing

### ISSUE THREAD

**Issue by LukePettway** [nvaccess/nvda#8317]
### Steps to reproduce:
1. Browse to this JSFIddle: https://jsfiddle.net/ubxvtgq4/8/ 
1. Focus the button in the example
1. Press the enter key, delete key, tab on and off the button - the counter should increment
1. Enable NVDA
1. Focus on the button
1. Press enter - the counter won't increment
1. Press delete - the counter increments
1. Tab on and off the button - the counter increments

### Expected behavior:

The event listener for the keydown event called with the enter keycode should work the same way when NVDA is enabled.

### Actual behavior:

The event listener only fires for events which aren't called with the enter key.

### System configuration:
NVDA version:
2017.3

NVDA Installed or portable:
Installed

Other information:
Several coworkers and I observed this issue on different OS builds. 

Windows version:
Windows 10 Version 1703 Build 15063.1029

Name and version of other software in use when reproducing the issue:
Firefox Developer Edition Build 61.0b6

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
Only the version I have installed

**Comment by josephsl** [comment]
Hi, what happens when you enter focus mode (NVDA+Space) first? CC @DerekRiemer, @JcSTeh

**Comment by LukePettway** [comment]
When I enter focus mode it works as expected

**Comment by josephsl** [comment]
Hi, I see. May we close this as a duplicate of another issue dealing with not being able to press Enter key while in browse mode? Thanks.

**Comment by LukePettway** [comment]
Sure, I'll go ahead and close. Thanks again!

**Comment by ehollig** [comment]
I think you may be referring
 to #7898
