### ISSUE TITLE
Launching a new copy of NVDA should exit running version and start launched version.

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#8320]
(Updated with command line information from Leonard).

This is a minor inconsistency, but still worth recording:

With any version of NVDA running, pressing control+alt+n restarts the installed copy of NVDA.  That works fine.

If a desktop or start menu shortcut to NVDA is instead activated, or a copy of NVDA run from File Explorer, NVDA does not restart.  NVDA does have a command line parameter -r to replace or quit the running version of NVDA and start this one (Thanks [Leonard](https://github.com/nvaccess/nvda/issues/8320#issuecomment-390983968) for reminding me of that!)

See https://www.nvaccess.org/files/nvda/documentation/userGuide.html#CommandLineOptions for more information on the command line options.

I would like to then propose that we make the -r parameter implicit and adopt that behaviour by default, and perhaps in its place add a parameter to check and return a value if there is already a copy of NVDA running to enable both functionalities going forward.

**Comment by Brian1Gaff** [comment]
Hmm, in many ways what you are describing is what I get when I've just 
updated nvda and it tries to auto restart.
 I have no idea what is going on behind the scenes for this, but generally, 
I tend to relaunch with the alt/ctrl n which does close the old copy.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by leonardder** [comment]
The reason why NVDA restarts with the control+alt+n shortcut, is because the "-r" parameter is provided to the executable. This parameter closes a running copy of NVDA and then starts a new one. Adding the -r command line parameter should solve your issue.

Having said that, I agree that it could be considered to have this restarting behaviour by default.

**Comment by Brian1Gaff** [comment]
That is why when I want to automate getting the log from the previously 
running version I use a batch file and avoid running the shortcut as this 
would confuse things.


Brian

**Comment by derekriemer** [comment]
having a restart implicit could be very nice indeed.

**Comment by JulienCochuyt** [comment]
For a non-initiated user, I think it is less common to accidentally run an executable that it is to stumble upon trying to replace the current running NVDA with a portable version already created.

I already had a few hard times trying to remote assist grand beginners in accomplishing this task.

**Comment by XLTechie** [comment]
For what it's worth, either for myself or while supporting others, I have never 
run into a situation where someone accidentally had an executable copy of NVDA 
laying around, and ran it by mistake. This seems extraordinarily unlikely to 
happen for the novice users that -r was meant to help.

Conversely, having to use -r when running NVDA, as has already been stated, makes 
the replacement of NVDA by those of us doing remote technical support, a more 
annoying and time consuming process.

So, even though nobody asked, I whole-heartedly cast my vote behind this change.

**Comment by XLTechie** [comment]
So, is this still being considered? In other words: bump.:)

**Comment by josephsl** [comment]
Hi, based on comments, I’m thinking yes, but we’re blocked by Project Threshold at the moment; I myself am rebasing Project Threshold to various pull requests in the meantime and I’m sure NV Access will advise folks to do the same if a PR is going to be written for this one. Thanks.

**Comment by XLTechie** [comment]
@JulienCochuyt has already written a PR for this--a month or so ago, and an update yesterday.

**Comment by josephsl** [comment]
Hi, just saw that he has rebased it on master. I’ll perform Python 3 compatibility test, although I think edits are not necessary. Thanks.

**Comment by XLTechie** [comment]
Thanks

**Comment by josephsl** [comment]
Hi,

I'm going to reopen this to serve as a reminder as to the tough road ahead: see #10179 for a full explanation, as the design of this issue includes an unintended side effect for installed copy of NVDA when it comes out of secure screens.

Thanks.

**Comment by Adriani90** [comment]
A fix up for #10179 is provided in #10183. Thus, closing this one in favor of the both references. I suggest to reopen the feature requests only if the whole feature is implemented and reverted due to something. If there is only a bug due to the feature but the feature is not completely reverted, then I suggest to open new issues like in this case #10179. If there are more bugs discovered based on this feature, then we should think about reverting the whole feature and then we can reopen this one again.
Thanks.
