### ISSUE TITLE
Firefox57~60: type Chinese characters in edit field, user do not have access to know the previous / next character

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#8321]
This issue was reported by bill_y. It occurs in Firefox57 and later.
## Steps to reproduce:
1. Open Firefox and link to Google.
2. Press e to move to edit field.
3. Type Chinese characters E.G. "視障資源整合查詢".
4. Press left-arrow  to move to previous character.
### Expected behavior: 
NVDA speaks: "詢"`.
### Actual behavior:
NVDA speaks: (keep silent).

### Other information:
* By pressing tab to move away, and press shift+tab to move back. The function "report previous / next character" works again.
* This issue does not occur in [Firefox56](https://ftp.mozilla.org/pub/firefox/releases/56.0/).

### System configuration:
NVDA version: 2018.1
NVDA Installed or portable: installed
input methods: Chinese New Phonetic, Chinese ChangJie, Chinese Boshiami
Windows version: Windows 7, Windows 10

CC: @jcsteh

**Comment by jcsteh** [comment]
Just to clarify, did you press enter to switch to focus mode after pressing e to move to the search box? Your steps to reproduce didn't mention this. Typing Chinese characters after pressing e (without first pressing enter) isn't going to work.

Also, if you do exactly the same but type English characters instead, do you get the expected result when cursoring?

Thanks.

**Comment by surfer0627** [comment]
> did you press enter to switch to focus mode after pressing e to move to the search box? 

yes, I did.


> if you do exactly the same but type English characters instead, do you get the expected result when cursoring?

Yes, I type English characters and get the expected result when cursoring.
This issue just occured when typing Chinese characters.

Thanks for help.

**Comment by nishimotz** [comment]
Similar issue is reported regarding Japanese input method.
After the input composition session, the fixed characters can not be reviewed with left arrow and right arrow keys.
Once the focus moved to other control and returned to the edit again, it works as normal.

**Comment by surfer0627** [comment]
@Adriani90
I still could reproduce this case at least in Windows 7 / Firefox 66.0.5 (x64 zh-TW) with NVDA 2019.1.1.

**Comment by josephsl** [comment]
Hi,

How about with Firefox 91?

Thanks.

**Comment by surfer0627** [comment]
Hi,
I can not reproduce this issue with Firefox version 91.0.2 (Windows 10 20H2 (10.0.19042).

Thanks.

**Comment by josephsl** [comment]
Hi,

And as such, closing as worksforme. Please create a new issue if this happens with future Firefox releases. Thanks.
