### ISSUE TITLE
Triggering text change of currently focused text input using up/down is announced, but not with left/right/other

### ISSUE THREAD

**Issue by jmuheim** [nvaccess/nvda#8325]
I'm working on a simple implementation of a date picker.

It is only a text input, and the user can change the current date using left/right (day-wise) and up/down (week-wise). The current date is then written into the input field.

While implementing, I noticed that triggering a value change of the currently focused input is announced by NVDA in FF properly, but only using up/down keys. Other keys like left/right are announced as "blank", although the value is assigned to the text input.

Here is the current implementation of my date picker:

https://codepen.io/accessibility-developer-guide/pen/odOydP

I created a smaller CodePen to reproduce the problem. It only reacts to the user pressing a certain key, then writes some value into the input:

- `up` works as expected, "pressed up" written into field and announced
- `down` works as expected, "pressed down" written into field and announced
- `left` does not work: "pressed left" written into field, but "blank" announced
- `right` does not work: "pressed right" written into field, but "blank" announced
- `ctrl` does not work: "pressed ctrl" written into field, but nothing announced
- `alt` does not work: "pressed alt" written into field, but nothing announced
- `shift` does not work: nothing written into field, and nothing announced

This seems really strange to me. What do up/down trigger in the browser (or screen reader) that other keys do not (especially left/right)?

I played around with triggering changes manually (`$filter.trigger('change')`) and even manually selecting the value (`$filter.select()`), but didn't help.

Any idea what could make pressing the other keys work as expected?

**Comment by jmuheim** [comment]
Also tried setting the input to `readonly`, but didn't change anything:

https://codepen.io/accessibility-developer-guide/pen/zjXmqZ?editors=1000

**Comment by Brian1Gaff** [comment]
Is this specific to Firefox, and if so only the new versions? Might want to 
try waterfox.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by jmuheim** [comment]
I tried to install Waterfox, but it tells me I need at least Windows XP SP2, although I'm on Windows 7. No idea what's the problem.

However, I tried it in Chrome, and there appears the same behaviour.

Then I tested it with JAWS in both NVDA and Chrome, and again, exactly the same behaviour.

So it maybe is rather a screen reader problem than a browser problem?

I suspect that it has something to do with the internal (virtual) cursor. JAWS automatically switches between browse and focus mode depending on the element that currently has the screen reader's focus, and when playing around with up/down, the screen reader focus leaves the input even in focus mode, although JavaScript should intercept up/down and prevent default action.

So it seems that although I'm in focus mode, screen readers still react on certain keys in a specific way? This is very nasty in my opinion.

**Comment by jmuheim** [comment]
Okay, it seems to be the AUTO mode in JAWS: when disabling it, the behaviour disappears, so the focus stays in the input (regardless whether pressing up/down/whatever).

In NVDA though, I'm not aware that I have AUTO mode (or something similar) active.

**Comment by jmuheim** [comment]
> In NVDA though, I'm not aware that I have AUTO mode (or something similar) active.

Oh, I misunderstood something regarding this. Please ignore.

**Comment by jmuheim** [comment]
Still, it is disappointing that pressing up/down makes NVDA announce the content of the input, and left/right does not. Is there any way around this?

**Comment by ehollig** [comment]
I can reproduce this using Firefox 60. CC @derekriemer @michaelDCurran

**Comment by Adriani90** [comment]
@jcsteh I see that this issue can be reproduced in FF, I can also reproduce it in Google Crome and Edge as well. In IE the edit fields are not shown at all but I guess this is due to my java plugin.

**Comment by jcsteh** [comment]
valueChange events are deliberately ignored in text boxes. If they weren't, you would hear the entire value every time you typed a character.

The reason that up/downArrow work "as expected" is that these keys normally move by line, so NVDA reads the current line after sending the key press to the application. In contrast, left/rightArrow move by character, so they would only read the current character after sending the key to the app. Since the cursor is probably at the end of the field, you'll get "blank".

So, NVDA is behaving as expected here, and this is not something that can be changed without breaking normal usage. (This is most definitely not normal usage for a text box; arrow keys normally move through the text, not change it.)

**Comment by jmuheim** [comment]
Thanks for sorting this out, guys. I learn a lot about browser internals thanks to screen readers.
