### ISSUE TITLE
Enter Keypress on Parent triggers mouse click of Inner child followed by parent click

### ISSUE THREAD

**Issue by sanjay1909** [nvaccess/nvda#8326]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>https://codepen.io/sanjay1909-the-lessful/pen/erozeP 
> Try with NVDA to see the Issue mentioned in Title
> Kill the NVDA app and try
> Experimented in Browser: Firefox and Chrome

### Expected behavior:
> Expected behavior is What you see in that example when NVDA app is killed
> Keypress should call kyepress event listeners
> focus shouldn't shift to an inner child for Enter|space key

### Actual behavior:
> Keypress calling Mouse event listeners
> focus shifting to an inner child for Enter|space key

### System configuration:
NVDA version: 2018.1

NVDA Installed or portable:

Windows version:
> Example: Windows 10 Pro Version 1803

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA?
> No

**Comment by sanjay1909** [comment]
Summary of the Issue
1. Focus Shifts to inner Child When we press Enter or Space Key. As a result, child click event happens before parent click event.
2. KeyPress Triggers Mouse click event 

Issue 2 was addressed here, https://github.com/nvaccess/nvda/issues/4903 . Thanks

**Comment by derekriemer** [comment]
Was this in browse or focus mode.

**Comment by sanjay1909** [comment]
It's in **Browse Mode** with Checkbox selected for **Automatic focus for focus changes**

https://codepen.io/anon/pen/MGdYRW 
In this example, I **removed the tabindex on the child**, But still, the click event attached for the 1. child got executed and 
2. Executed first before the parent

**Comment by Adriani90** [comment]
@sanjay1909 how is this behavior in NVDA 2019.3 Beta 1? Could you please give an update?

**Comment by SuperAL** [comment]
@sanjay1909 try listening to keyup event on child, possible event timeline:
1. listen to keydown event on parent and trigger keydown
2. the event handler on parent was triggered and move the focus to child
3. child receives keyup event and trigger click handler
FYI: I encountered this situation when using material ui component, my solution is to move focus to child on keyup instead keydown.

**Comment by Adriani90** [comment]
@sanjay1909 is this still an issue with NvDA 2024.2 or 2024.3 Beta?

**Comment by Adriani90** [comment]
We didn't hear an update from the initial author upon request since more than 4 years, I am closing as abandoned. if you are still having this issue, please comment and we can reopen.
