### ISSUE TITLE
Chrome crashes in google sheets when wieving versions and running NVDA

### ISSUE THREAD

**Issue by ondrosik** [nvaccess/nvda#8327]
This is something what I can reproduce only in one particular computer.
when I open sheet in google sheets and press ctrl+alt+shift+h, the chrome hangs  and then the standard windows dialog displays telling that program is not responding. In other computer it works fine, I see the tree wiev and can select older version. In that  particular computer is windows 10, 32 bit, version 1803.

I get the following log

Input: kb(laptop):alt+control+shift+h
IO - speech.speak (13:41:18.101):
Speaking [u'Pracuje sa... \n '] (working)
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:18.664):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:18.676):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:18.686):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:18.696):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:18.707):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:18.717):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:18.726):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:18.742):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:18.749):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
IO - speech.speak (13:41:18.799):
Speaking [u'pr\xe1zdny'] (blank)
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:19.079):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:19.092):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
IO - speech.speak (13:41:19.220):
Speaking [u'aplik\xe1cia'] (application)
IO - speech.speak (13:41:19.236):
Speaking [u'Zoznam verzi\xed  stromov\xe9 zobrazenie'] (lilst of versions tree wiev)
IO - speech.speak (13:41:19.240):
Speaking [u'\xfarove\u0148 1  23. m\xe1ja, 12:27 Aktu\xe1lna verzia Adela current version 23. 5. 2018)
\u0160von\u010din\xe1rov\xe1  1 z 1']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:23.635):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
IO - inputCore.InputManager.executeGesture (13:41:26.437):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (13:41:28.565):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (13:41:29.868):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (13:41:31.246):
Input: kb(laptop):downArrow
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:31.503):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
IO - inputCore.InputManager.executeGesture (13:41:31.967):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (13:41:32.385):
Input: kb(laptop):upArrow
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:33.219):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:33.224):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:33.236):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:33.239):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:33.246):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:33.256):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:33.256):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:33.266):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:33.266):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:33.276):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:34.242):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:34.404):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:34.420):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:34.427):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:34.436):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(13:41:34.469):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
IO - inputCore.InputManager.executeGesture (13:41:37.184):
Input: kb(laptop):NVDA+f1

**Comment by derekriemer** [comment]
Strange. There isn't much info in this log I can see which provides enlightenment.

**Comment by Adriani90** [comment]
@ondrosik in your log there are only debug warnings, no errors. Is this issue still reproducible in NVDA 2019.1.1?
If you have issues only on a particular machine, I propose to consult the NVDA users list first and after discussions there you could create a github issue with more details. The users list is here:
https://nvda.groups.io/g/nvda
For now I am closing this issue but please comment on it if you still have the problem and maybe we can help you.
