### ISSUE TITLE
Use UIA for syslistview32

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#8328]
The current syslistview32 implementation of NVDA relies on a whole bunch of custom code which seems to cause issues in some situations. See for example:

* #8268: sysListView32.ListItem._getColumnLocationRaw can return malformed rectangles (i.e. with a left coordinate that is greather than the right coordinate)
* #8175: No item names for some listview items in 64 bit applications
* It relies on virtualAllocEx to get some relevant data about contents, such as the location and column names.

it turns out that at least under Windows 10, every syslistview32 list item exposes the several columns as children of list items when using UIA, along with proper mappings to their column headers. Using UIA would at least fix #8268 and might be a more solid fix for #8175 than #8190 provides.

**Comment by dkager** [comment]
This sounds really nice to have. :)

**Comment by Adriani90** [comment]
in every MS Office application. Especially in MS Access.

**Comment by Adriani90** [comment]
or in MS Powerpoint where you can group elements on a slide.

**Comment by Adriani90** [comment]
Syslistview32 with UIA supports Datagrit and Lists. It could contribute to solve #7950

**Comment by Adriani90** [comment]
SysTabcontrol32 could solve #7758

**Comment by leonardder** [comment]
I have a working prototype in https://github.com/babbagecom/nvda/tree/slvUIA

cc @josephsl

**Comment by leonardder** [comment]
[**@Adriani90**](https://github.com/Adriani90) commented on [28 jun. 2018 22:04 CEST](https://github.com/nvaccess/nvda/issues/8328#issuecomment-401156363 "2018-06-28T20:04:24Z - Replied by Github Reply Comments"):
> in every MS Office application. Especially in MS Access.

Are you sure this is not UIA?

**Comment by leonardder** [comment]
[**@Adriani90**](https://github.com/Adriani90) commented on [28 jun. 2018 22:19 CEST](https://github.com/nvaccess/nvda/issues/8328#issuecomment-401160632 "2018-06-28T20:19:46Z - Replied by Github Reply Comments"):
> SysTabcontrol32 could solve #7758

I'm afraid not, as there's another control used there.

**Comment by Adriani90** [comment]
MS Access is definitely IAccessible, have checked in the python console.

**Comment by josephsl** [comment]
Hi,

Test performed with Leonard's branch merged with master (fixing conflict in Outlook app module). I used Task Manager and Services.msc on Windows 10 Version 1809 (build 17763).

Result: I can confirm Leonard's observation: still noticing performance issues with UIA implementation. This is most noticeable in Task Manager where there is a huge delay when navigating entries in Details tab.

Thanks.

**Comment by leonardder** [comment]
I think the overall conclusion of this issue is that UIA for SysListView32 is pretty slow. Closing for now, we can always reopen if desired.
