### ISSUE TITLE
NVDA stops speaking, logs an iAccessible2 exception while reading web content in Firefox

### ISSUE THREAD

**Issue by mehgcap** [nvaccess/nvda#8329]
Using NVDA 2018.1.1 and Firefox 60.0.1, I'm getting an apparently random error while reading webpages. I know it happens when NVDA goes silent, rather than continuing a say-all or reading the next line when I'm arrowing down. When this happens, my logs shows the following:

Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.mozilla.BrokenFocusedState object at 0x058A0BF0>
Python class mro: (<class 'NVDAObjects.IAccessible.mozilla.BrokenFocusedState'>, <class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: None
value: None
appModule: <'firefox' (appName u'firefox', process ID 48416) at address 4fee4b0>
appModule.productName: u'Firefox'
appModule.productVersion: u'60.0.1'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 1771906L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 12812
windowText: u'Introduction \u2014 Tornado 5.0.2 documentation - Mozilla Firefox'
displayText: exception: 'NoneType' object is not iterable
IAccessibleObject: <POINTER(IAccessible2) ptr=0x1487c3dc at 52ad1c0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=1771906, objectID=-4, childID=-33623532
IAccessible accName: exception: (-2147417842, 'The application called an interface that was marshalled for a different thread.', (None, None, None, 0, None))
IAccessible accRole: exception: (-2147417842, 'The application called an interface that was marshalled for a different thread.', (None, None, None, 0, None))
IAccessible accState: exception: (-2147417842, 'The application called an interface that was marshalled for a different thread.', (None, None, None, 0, None))
IAccessible accDescription: exception: (-2147417842, 'The application called an interface that was marshalled for a different thread.', (None, None, None, 0, None))
IAccessible accValue: exception: (-2147417842, 'The application called an interface that was marshalled for a different thread.', (None, None, None, 0, None))
IAccessible2 windowHandle: exception: (-2147417842, 'The application called an interface that was marshalled for a different thread.', (None, None, None, 0, None))
IAccessible2 uniqueID: exception: (-2147417842, 'The application called an interface that was marshalled for a different thread.', (None, None, None, 0, None))
IAccessible2 role: exception: (-2147417842, 'The application called an interface that was marshalled for a different thread.', (None, None, None, 0, None))
IAccessible2 states: exception: (-2147417842, 'The application called an interface that was marshalled for a different thread.', (None, None, None, 0, None))
IAccessible2 attributes: exception: (-2147417842, 'The application called an interface that was marshalled for a different thread.', (None, None, None, 0, None))

**Comment by mehgcap** [comment]
I don't know if either of these will help, or are even related, but I seem them throughout my log as well.


ERROR - scriptHandler.executeScript (14:32:16.263):
error executing script: <bound method Gecko_ia2.script_activatePosition of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x083AC310>> with gesture u'enter'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "browseMode.pyo", line 468, in script_activatePosition
  File "browseMode.pyo", line 1189, in _activatePosition
  File "browseMode.pyo", line 459, in _activatePosition
  File "treeInterceptorHandler.pyo", line 119, in _set_passThrough
  File "review.pyo", line 117, in setCurrentMode
  File "review.pyo", line 25, in getObjectPosition
  File "documentBase.pyo", line 24, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 93, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 201, in _findContentDescendant
COMError: (-2147417842, 'The application called an interface that was marshalled for a different thread.', (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (14:32:19.996):
error executing script: <bound method Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible.script_caret_delete of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible object at 0x083AC970>> with gesture u'delete'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "editableText.pyo", line 247, in script_caret_delete
TypeError: _hasCaretMoved() got an unexpected keyword argument 'origWord'

**Comment by jcsteh** [comment]
Do you have any add-ons installed? Focus Highlight perhaps? Please restart NVDA with all add-ons disabled and re-test.

**Comment by mehgcap** [comment]
I'm going to close this for now. I disabled add-ons as requested, and the problem went away. I was bracing for the tedium of enabling them one at a time, testing with each, but I had to restart my computer. NVDA returned to normal, with no add-ons disabled, but the problem hasn't returned in the days since that happened. I don't know why it started or why it has since stopped.
