### ISSUE TITLE
Add a link to the developer's guide in the help menu

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#8331]
As per title, for convenience.

**Comment by derekriemer** [comment]
I disagree. The vast majority of users don't want to be bothered by this.

**Comment by Adriani90** [comment]
However, there are lots of users who are interested in learning the development Basics. I would rather suggest to write a short sentence in the user guide referencing to the development guide. In this text area, a link to the dev guide should be added. I don't recall in this Moment if the addon development guide on github is being referenced in the development guide. But this should be the case as well.

**Comment by derekriemer** [comment]
@feerrenrut should this be closed as won't fix?

**Comment by feerrenrut** [comment]
Yes, I think so. Would be happy to accept a PR that does the following:

> write a short sentence in the user guide referencing to the development guide.
