### ISSUE TITLE
Windows 10 RS5/IUIAutomationElement9: support "is dialog" property

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8339]
Hi,

The following issue is categorized as "date-based prelim" as the product under development is scheduled to be released later in 2018 at the earliest (applicable NVDA release: 2018.4):

IUIAutomationElement9, part of IUIAutomation6 (RS5), includes a property ID that lets clients determine if a control is a dialog (30174). If this works, it could be one of the tests that could be performed to add dialog speaking behavior to various UIA-powered dialogs, particularly on Edge, various universal apps and so on. Note that this is one of the potential tests - not all UIA dialogs are dialogs, and not all controls expose correct information when probed by a client.

Technical: in order to support this, IUIAutomationElement9 support must be implemented (RS5). To whoever will be working on this, I advise waiting until August at the earliest before working on it as UIA info/implementation may change without notice.

Thanks.

**Comment by josephsl** [comment]
Hi,

Preliminary foundation laid in a discrete branch in my fork. The branch is named "win10rs5". The UIA interface file in there will be edited once new SDK's with UIA changes are released. Thanks.

**Comment by josephsl** [comment]
Hi,

This and related issues will be combined into a single PR that'll include UIA interfaces based on build 17692.

Thanks.

**Comment by josephsl** [comment]
Hi,

Combined with #8405 from July 2018 onwards as Windows 10 RS5 is being finalized. Thus, I think it is ready to take the flight so folks can test this and for NV Access folks and others to take advantage of things such as event groups, connection recovery behavior and what not.

Thanks.

**Comment by Adriani90** [comment]
@josephsl the pr #8473 has been merged. Is this issue now solved and can be closed? Thanks.

**Comment by josephsl** [comment]
Hi, ah, another oversight – not referencing this issue properly in my PR. Yes, please do close this. Thanks.

**Comment by Adriani90** [comment]
I would certainly fail on referencing the right issues if I would submit a pull request given the number of issues here. So no problem. I am closing this as works for me.
