### ISSUE TITLE
NVDA keeping the last focused Element

### ISSUE THREAD

**Issue by nikhil-compro** [nvaccess/nvda#8342]
Hi,

We have a web application where we have an application area and a navigator area.

User can use shortcut like CTRL+F6 to toggle focus between Navigator and application area
There are buttons inside the Navigator area. and in Application area we use pseudo focus(I know application works with actual focus but due to complexity of the application its the only solution)

When we move focus to Navigator (give focus to view all button)and toggle back to the application, NVDA saves the last focused element. Now when we press tab keys(without NVDA) it is successfully received by code and it works fine. however we keep actual focus to BODY.
Now when we use NVDA, with each tab in application area nvda announces the last focused control in Navigator(view all button). When we use arrow keys they are captured by nvda and shows movement in navigator area instead of application area. 

Not sure why NVDA is announcing previous element if focus is on body. Have tried everthing nothing works.
Ps. Checked the same thing with jaws and it is working correctly so seems like a bug with NVDA.

**Comment by Adriani90** [comment]
cc: @leonardder, @feerrenrut maybe you have an advice for this behavior? Aparently NVDA is not getting the input correctly. I wonder if it is working when browse mode is disabled by default? Or maybe the input is registered as injected because of pseudo focus?

**Comment by Adriani90** [comment]
cc: @jcsteh maybe you have any suggestion here, if you have time.

**Comment by jcsteh** [comment]
I think we'd need to see a test case here with exact steps to reproduce to be able to make any useful diagnosis.

**Comment by Adriani90** [comment]
We didn't get any test case from the initial author for this issue. You can reach to info@nvaccess.org asking for assistance in this regard.
I am closing this as abandoned due to missing test case which cannot be investigated by the community.
