### ISSUE TITLE
Cannot read Chinese IME candidates since Win10 updated to 1709

### ISSUE THREAD

**Issue by timothytylee** [nvaccess/nvda#8343]
### Steps to reproduce:
1. Make sure Windows 10 is at 1709 edition or newer
2. Open "Language Preferences"
3. Add a Chinese language, eg: Chinese (Traditional, HKSAR)
4. Open "Options" for the newly added language
5. Add a keyboard (Chinese IME), eg: Microsoft Quick
6. Open "Notepad" application
7. Use the Chinese IME to compose text, eg: Enter "eb" then press <Space>
8. A list of candidates will be generated by the IME

### Expected behavior:
NVDA should read back the list of candidates

### Actual behavior:
NVDA is unable to read the list of candidates

### System configuration:
NVDA version: 2018.1 portable
Windows 10 is running in a VM

Windows version:
Windows 10 Home 1803 17134.48

### Other questions:
This issue has been happening on all Windows 10 PC since upgrading to 1709 edition.  The problem cannot be fixed by rebooting the PC.

NVDA 2017.4 also exhibited the same problem.

**Comment by dingpengyu** [comment]
You can't read the Chinese input method candidate under Simplified Chinese.
Specific can see these issues
NVDA will be crashed when microsoft bing input method is installed and run in the computer in w
https://github.com/nvaccess/nvda/issues/4959
The input method candidate list can not be announce in windows 8.1 · Issue #4011 · nvaccess/nvd
https://github.com/nvaccess/nvda/issues/4011
Improve announcing of input method of pinyin input in Chinese.
https://github.com/nvaccess/nvda/issues/3983
Default rules in builtin.dic interferes with Chinese
https://github.com/nvaccess/nvda/issues/4889
