### ISSUE TITLE
Add quick keys support to objpad addon

### ISSUE THREAD

**Issue by Fatihyuksek** [nvaccess/nvda#8344]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result
Please add quick keys support to scan mode in objpad addon for NVDA. This can be useful in apps like messenger for windows 10 where we cannot use the tab key to navigate relyably

**Comment by josephsl** [comment]
Hi, a few years ago there was a talk about expanding the scope of browse mode to cover other applications. In the meantime, I need to know exactly how quick keys in ObjPad add-on (mine) would benefit many people, and test cases where it works and doesn’t work. Thanks.

**Comment by Adriani90** [comment]
This is an issue particularly atributed to the addon objpad. I suggest you to fill an issue agains the addon directly. Otherwise, if you wish this behavior in NVDA's core, than you can comment on issues which are already opened for this problem. See i.e. #7759 for use cases and detailed discussion.
I am closing this one in favor of #7759 and other similar issues.

**Comment by josephsl** [comment]
Hi, as the author of that add-on, I can say that ObjPad development has been suspended for a while so I can concentrate on more important things. As Adriani said, please try filing an issue on my add-on repo please. Thanks.
