### ISSUE TITLE
Reading this two emois with polish voice of eSpeak NG freezes NVDA

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#8350]
### Steps to reproduce:
1. run NVDA next
2. in eSpeak NG switch to polish voice
## do not read the following line with eSpeak NG, because NVDA will freeze.
3. readd the following two characters 👍😜
### Expected behavior:
NVDA should read those emois.
### Actual behavior:
NVDA freezes.

### System configuration:
NVDA version:
next-15159,465f57b2

NVDA Installed or portable:
Installed
Other information:
Reading those symbols separately works and reading them together with english voice works also.

Windows version:
Tested under Windows 8 and Windows 10

### Other questions:

Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
yes NVDA master-15153,0f69cd1d and the symbols didn't freeze NVDA.

**Comment by ehollig** [comment]
Oh no. Sounds like another issue with Emoji's, similar to #7740 and #7805. CC @feerrenrut @michaelDCurran

**Comment by feerrenrut** [comment]
This will need to be investigated and a bug raised against the espeak-ng project. Since this issue has come up several times, it might be wise to contribute a PR for the espeak-ng project with automated tests for all emoji symbols, in all languages.

**Comment by zstanecic** [comment]
yes, but native speakers who knows structure of the espeak NV should bge 
involved.

polish language has no maintainers

lukasz Golonka,

comments?


W dniu 08.06.2018 o 01:33, Reef Turner pisze:
