### ISSUE TITLE
Context Sensitive Help for NVDA

### ISSUE THREAD

**Issue by ThomasStivers** [nvaccess/nvda#8354]
### Steps to reproduce:
NVDA has an extensive user guide, but it can be daunting to new users to locate the help for a particular control or dialog box in a monolythic help file.

### Expected behavior:
NVDA dialogs should include a help button as well as provide context sensitive help in response to a press of F1.

### Actual behavior:
Users must locate the appropriate section in the user guide which deals with the control or dialog they have questions about.

### System configuration:
NVDA version:
Suggestion for future release.

NVDA Installed or portable:
Both

Other information:
I will submit a pull request referencing this issue shortly.

Windows version:
Any

**Comment by Adriani90** [comment]
This is covered in #7757.
