### ISSUE TITLE
German Win7: LTR and RTL characters still exist in Properties Window (explorer.exe) and in the Taskbar Clock

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#8361]
NVDA-Version: NVDA 2018.2 RC2, Portable, Win7x64, German UI (de-AT)

See issue #5729 and PR #5751 and PR #8316 

Date formats:
+ Taskbar clock: hh:mm, Ldddd, Ldd.Lmm.Lyyyy
+ Properties window: Ldddd, Ldd. Lmmmm Lyyyy, RLhh:mm:ss
  Hint: Open the properties window of a file/folder in the Windows Explorer.

L = U+200E (LTR), R = U+200F (RTL)

Update No. 1: Windows Explorer » Detail View » Last modified field » date format:
+ NVDA 2018.1: Ldd.Lmm.Lyyyy RLhh:mm
+ NVDA 2018.2 RC2: dd.mm.yyyy hh:mm

This works as expected. And there is no issue with an empty size field in this view in Windows Explorer.

Update No. 2: Systemsteuerung\Programme\Programme und Funktionen (Control Panel\Software\Software and features) » Detail View » Date of Installation field » date format:
+ NVDA 2018.1: Ldd.Lmm.Lyyyy
+ NVDA 2018.2 RC2: dd.mm.yyyy

This also works as expected.

**Comment by DrSooom** [comment]
Update: This issue still exists in NVDA 2018.2 RC3.
Additional date format in the Windows Explorer properties window:
+ LHeute, L07. LJuni L2018, RLVor 25 Minuten (translated to EN: LToday, Ldd. Lmmmm Lyyyy, RLmm minutes ago)
  Hint: "ago" stands for "Vor". In German it stands before the amount of the minutes, not after.

**Comment by leonardder** [comment]
cc @dkager, would you be able too look into this?

**Comment by dkager** [comment]
Off the top of my head I excluded some cases, such as the clock, from the PR to make it less complex. Liblouis braille tables can also filter these characters.

**Comment by DrSooom** [comment]
Eliminating U+200E and U+200F at this early point of process has not only effects to the braille output, it also changes the pronunciation of the TTS depending of the current used synthesizer. Well, and for me: I added `sign \x200e 12378` and `sign \x200f 45678` in the file "de-de-comp8.ctb" years ago. So, the braille output alone isn't the point.

Well, after a quick look in PR #5751 I would say that this issue here (#8361) should be part of NVDA 2018.3 (or later) because it isn't critical at all.

Sadly the changelog entry in 2018.2 RC3 still says something complete different at all. In other words: the changelog entry should be changed from
> • NVDA no longer reports (LTR and RTL marks) in Braille or per-character speech when accessing the clock in recent versions of Windows. (#5729)
to something more like "Filter LTR and RTL marks from list view items" (in the Windows Explorer) because this seems to be the current state. (I know that changing the changelog entry will have no effect in the translated changelogs to NVDA 2018.2 at this late point.)

**Comment by Adriani90** [comment]
Is it still reproducible in NVDA 2018.2? I get the right reportings by speech at least. But I don't habe a braille display to test it in braille.

**Comment by Adriani90** [comment]
Hello, oh I didn't try this. Yes I can confirm.

**Comment by lukaszgo1** [comment]
@DrSooom Can you download [this build](https://ci.appveyor.com/api/buildjobs/d9rivymqnge63uv3/artifacts/output%2Fnvda_snapshot_pr8643-15891%2Cb314642b.exe) and check, that the character are gone from all the places in which you found them?

**Comment by DrSooom** [comment]
I could test all mentioned scenarios successfully. All works now as expected with NVDA pr8643-15891,b314642b. Thanks for fixing this.
