### ISSUE TITLE
NVDA Windows Store edition: "access is denied" error when launched

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8362]
Hi,

Mostly for those curious about work on Windows Store version of NVDA: when launching a side-loadable snapshot, NVDA logs "Access is Denied" error.

STR:

1. Download a side-loadable version of NVDA snapsoht (snapsohts page, select a build, go to Artifacts, and get the side-loadable appx file).
2. Install the side-loadable snapsoht.
3. Launch the newly instlaled app.

Expected: NVDA starts.
Actual: "Access id denied" error is thrown by os.pyc when it tries to create a config directory, with the directory set to .\usrConfig.
Likely scenario: either file system access must be granted, or the Store version of NVDA is fooled into believing that it is not installed on the system (config.getInstalledUserConfigPath function might be returning None when side-loadable version is instlaled).

Setup:

* NVDA version: master.15164 side-loadable appx
* OS: Windows 10 versions 1703 and 1803

Thanks.

**Comment by Brian1Gaff** [comment]
Joseph, you got a dodgy T key on your keyboard? grin...
 Brian

bglists@blueyonder.co.uk

**Comment by josephsl** [comment]
Hi,

Upon debugging this more, I found that, somehow, when installing the side-loadable version of Windows Store edition of NVDA, NVDA reports itself as not installed.

STR:

1. Go to NVDA snapshots page and open any snapshot link (not the download link).
2. Go to artifacts and download the side-loadable appx package.
3. Install the appx package and run it after installing it.

Expected: NVDA starts.
Actual: NVDA is not detecting itself as being installed.

A trace of the output generated with a custom snapshot (config.getUserDefaultConfigPath function) is as follows (found at try-wxPy4Centennial branch):

Centennial debug: testing why Windows Store version of NVDA is not detected as installed...
installed user config path is installedconfigpath (succeeds in retrieving the AppData path NVDA uses to store user config)
checking if NVDA is truly installed... (prints config.isInstalledCopy())
... False
checking if this is Windows Store version of NVDA... (prints config.isAppX)
... False
NVDA is not installed on this system

Thus, the end result is that a bogus path is returned, and when the appx package attempts to create the user directory (because it doesn't exist yet), NVDA terminates with "access is denied" error.

Thanks.

**Comment by michaelDCurran** [comment]
The fact that config.isAppX is False is the thing to concentrate on here.

As long as config.isAppX is true, the rest of NVDA will handle the 
config paths properly.

Note that when running as an appX NVDA should not currently report as 
being installed.

I would think that the call to getCurrentPackageFullName in nvda.pyw is 
failing for some reason.

**Comment by josephsl** [comment]
Hi,

Yep, kernel32.dll::GetCurrentPackageFullName says "insufficient buffer length" (Windows error 122). Tests indicate that at least the fact that the Store edition notes that it is running inside a package, so I guess the only error to handle might be 15700 (not a package) unless we need to check for other things; when testing with source code only, I get 15700, whereas the package version says something else, so I guess it is a bit of a successful debugging session.

Thanks.
