### ISSUE TITLE
2018.2 RC1 not announcing Outlook message status

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#8367]
Earlier snapshots of 2018.2 announced when a message in Outlook was forwarded or replied to.  This does not happen in RC1.  The feature has been removed from What's New, so I assume there is a good reason for removal of the feature.  Disappointing though, especially as I suggested it a while back (smile).

**Comment by Brian1Gaff** [comment]
I saw a ticket on this being very unstable and misleading the other day due 
to different versions of Outlook. Maybe its been removed due to this report. 
Have you tried rc2?

Brian

**Comment by leonardder** [comment]
Thanks for raising this. I should actually have reopened #6911 and will do so. I will close this issue.
