### ISSUE TITLE
NVDA does not switch to Hands-Free Bluetooth profile when Windows switches to it

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#8368]
### Steps to reproduce:
1. Insure that your Windows 10 PC is up-to-date, including the April 2018 update..
2. In NVDA's synthesizer settings, insure that the output device is "Microsoft Sound Mapper".
3. Connect a Bluetooth headset to your Windows 10 PC.
4. Go to Control Panel -> Devices and Printers -> your Bluetooth Headset -> its properties window -> "Services" tab and make sure that all services are enabled/checked.
5. Go to Control Panel -> Sound -> "Recording" tab. At that moment, Windows will switch the Bluetooth headset from A2DP profile to Hands-Free profile, in order for the headset's microphone to work properly.
6. Invoke NVDA's "Select a synthesizer" dialog and from the "Output device" combo box select the Hands-Free virtual Bluetooth audio device and press ENTER to activate it. Note, that this step has to be done blindly, since NVDA is silent during that time (maybe a braille display will come in handy in such a situation).

### Expected behavior:
NVDA should also automatically switch its output device to the Hands-Free Bluetooth profile (the virtual Bluetooth output audio device) created by the Bluetooth drivers/software, in order to be able to output speech and sounds properly.

### Actual behavior:
NVDA remains routed to the A2DP Bluetooth profile (the respective virtual Bluetooth audio device), and so remains silent. And in order to make NVDA output to the currently active Hands-Free virtual Bluetooth audio device, the user has to manually select it from the list of output devices from within NVDA's "Select a synthesizer" dialog, which has to be done "blindly", since NVDA is silent during that time (maybe a braille display will come in handy in such a situation).

### System configuration:
- Operating system: Windows 10 Pro version 1803 (build 17134.81), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: next-15174,c2bd4af9.
- Processor: Intel Core i5-4670 at 3.40GHz.
- RAM Memory: 8.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC887 at Intel Lynx Point PCH - High Definition Audio Controller.

### Other questions:
This issue is a long-standing one. The Bluetooth drivers have been updated for the Windows 10 April 2018 Update. Previously, NVDA would freeze on step 5 and there was nothing that the NVDA developers could do to avoid this. With the updated Bluetooth drivers, NVDA at least does not freeze, so something has changed in the behavior of the Windows Bluetooth drivers. That is why I'm raising this issue again, because maybe now the NVDA developers can do something about it. Please, let me know if you need any NVDA logs for this and I'll try to provide them for you.

**Comment by Adriani90** [comment]
@k-kolev1985 can you reproduce this with NVDA 2020.1 RC1 and Windows 10 1909 Update?

**Comment by k-kolev1985** [comment]
@Adriani90 I can reproduce it with the latest alpha build of NVDA that I use as my daily screen reader.

**Comment by hamidrezaabroshan** [comment]
I had this problem in windows 10 and nvda 2020-4 too.

**Comment by Adriani90** [comment]
@k-kolev1985 could you please test with last nVDA alpha? Is this issue still occuring?

**Comment by k-kolev1985** [comment]
@Adriani90 Now it works as expected. It was fixed for Windows 11 by Microsoft some time ago, but I forgot to update the ticket with the new information. 
I don't know if the usage of WASAPI will fix it on NVDA's end even for Windows 10 or not. My main machine is running Windows 11, but I do have a laptop with Windows 10 on which I can try it these days and report the result.

**Comment by Adriani90** [comment]
That would be great. Thanks.

**Comment by k-kolev1985** [comment]
@Adriani90 No, the behavior under Windows 10 is the same as it always was - no change there.

**Comment by Adriani90** [comment]
@k-kolev1985 could you please test now with NVDA last alpha version if this issue still occurs? Please do so with wASAPI enabled. There were some improvements during last days that could have fixed this issue.

cc: @jcsteh

**Comment by k-kolev1985** [comment]
@Adriani90 If I don't forget until then, I'll probably test it in the weekend, since I'm at work during the week and rarely have time then.

**Comment by k-kolev1985** [comment]
@Adriani90 The problem is still the same.
Test environment:
- Windows 10 (I think it is mostly up-to-date)
- Latest NVDA alpha version (just got updated)
- WASAPI was enabled in NVDA's advanced settings
- The hands-free bluetooth profile was enabled in the device's properties
I Think this is Microsoft's fault and I think that for Windows 10 it will not be fixed.
At least Microsoft fixed it a long time ago for Windows 11, which is good.
Unfortunately, my work machine is on Windows 10 and therefore I don't dare use a Bluetooth headset there. 😀
I think we can close this issue as "won't fix". What do you think?

**Comment by Adriani90** [comment]
Yeah let's close this as won't fix for now, I don't think NVDA developers will spend time to solve this backwards.
But please feel free to report this to Microsoft, maybe they do something about it.
