### ISSUE TITLE
Is there a feature in NVDA where we can know that there was a mouse left click on text?

### ISSUE THREAD

**Issue by Gulroz** [nvaccess/nvda#8369]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by Adriani90** [comment]
Yes, just press nvda]left bracket (the key next to the letter p on your keyboard) if you have keyboard layout set to laptop in NVDA settings / keyboard.
Press numpad divide if your keyboard layout is desktop.
For more feedback on this please consult the NVDA users list at 
https://nvda.groups.io/g/nvda
I am closing this issue for now.
