### ISSUE TITLE
Is there any addon to convert a txt to mp3 or wav with nvda? 

### ISSUE THREAD

**Issue by heartdragon** [nvaccess/nvda#8376]
Is there any addon to convert a txt to mp3 with nvda? thanks

### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by Brian1Gaff** [comment]
Not an add on, There may well be something to use Espeak, but there are 
plenty of programs around that turn text into audio. I'm currently using 
dspeech, which is a freebie. It has an inbuilt notepad like editor and can 
run tests of what it sounds like without creating the file every time. It 
seems to be able to use most Sappi 5 32 bit voices, but 16bit and 64 bit 
ones do not seem to work nor throw errors so I imagine either there is a 
newer version or this is just what it is.
 I've not found a good way to use a dictionary, so much of the  mis 
pronounced words need to be altered in situe, but once you have worked it 
out there is a global replace, but use it carefully in case your search 
string happens with other similar words
 It has the ability to remove  unexpected hard carriage returns that might 
spoil the flow, but be aware the actual visual appearance after this is 
usually a mess for the sighted!
You can make wav or mp3 files I think.
As to where to get it, well if you cannot find it let us know on the main 
user list. This is for issues with nvda and therefore not really appropriate 
for external programs.
 If you are looking for a way to record nvdas output directly, I can 
heartily recommend Virtual Recorder which is around all over the place. 
Obviously any file made this way will need to be edited in an audio editor 
afterwards. However it is capable of recording all sound so is very  helpful 
for youtube recording in a quick and dirty way too.
 Maybe an add on writer can make an add on to do what you want, but to me 
its not really a screenreader function, but then neither is weather and we 
have one of those!
Brian

**Comment by heartdragon** [comment]
Hi I installed a voice as complement in NVDA but when I am usign Espeak I cant see that voice. Maybe because i just installed that voice in NVDA and it is not share with with Espeak, neither textaloud. Is there another way to pass to audio file with the voice of NVDA? thanks!
https://prnt.sc/jsfun0

**Comment by leonardder** [comment]
While this is a perfectly valid question, the Github issue tracker is only meant for issues or requests regarding the core of NVDA. Please continue your discussion on the [International users' mailing list](https://github.com/nvaccess/nvda-community/wiki/Connect#user-content-international-users-mailing-list-english) instead.
