### ISSUE TITLE
nvda locking when open optimize disk

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8381]
### Steps to reproduce:
Open the properties of a disk, on the tools tab choose the optimize option (to optimize and defragment the disk).
Press enter to open optimize.
### Expected behavior:
the optimize and defragment the disk window should open.

### Actual behavior:
The nvda is locked for a good 2 minutes until it returns to work, plus the optimization and defrag window is not opened.
This only occurs with nvda, even with the add-ons deactivated.
also tested with a copy of the new nvda and port.

### System configuration:
NVDA version:
next 15211
NVDA Installed or portable:
instaled
Other information:
> Example: Running in a VM

Windows version:
windows 10 17134.81
Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result
log:
[otimisar.txt](https://github.com/nvaccess/nvda/files/2085995/otimisar.txt)

**Comment by brianb12321** [comment]
It’s working for me. Issue should be closed.

**Comment by ehollig** [comment]
I just tried this. I did the following on Windows 10,1803:
1. Open the properties of the C drive
2. Navigate to the Tools tab by pressing ctrl+tab
3. Choose the optimize option
4. Press enter
Expected and Actual behavior: the optimize disk option opens
Closing as worksforme
