### ISSUE TITLE
Addons manager Always Asks to Restart when Exiting

### ISSUE THREAD

**Issue by Mohamed00** [nvaccess/nvda#8384]
### Steps to reproduce:
1. Open the addons manager.
2. Press escape.

### Expected behavior:
The dialog exits.

### Actual behavior:
NVDA asks to restart to make changes to addons, regardless of whether addons are installed or not.

### System configuration:
NVDA version: next-15211,8a5d09f0

NVDA Installed or portable:
Installed.

Windows version:
Windows 10 version 1803, 64 bit, 17134.81.

### Other questions:

Does the issue still occur after restarting your PC?
Yes.
Have you tried any other versions of NVDA?
No.

**Comment by leonardder** [comment]
Could you please verify that all your add-ons are either in the enabled or disabled state? Alternatively, it might be good to test this behavior with latest Master snapshot or NVDA 2018.2RC3.

**Comment by Mohamed00** [comment]
It looks like it was not an issue with NVDA after all. An addon installation went wrong and was stuck at PendingInstall and never got renamed. Closing.

**Comment by Brian1Gaff** [comment]
I'm not seeing this behaviour here on windows 7. Have you tried restarting 
the pc?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
