### ISSUE TITLE
Selection support in EmEditor edit control

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#8386]
hello all.

do you have any idea how to add selection support to the EmEditor control?

thanks.

**Comment by Adriani90** [comment]
maybe @leonardder could help in answering this question?
I advice to raise such questions on gitter instant messaging first and then after discussions if there is an issue, create a new issue agains NVDA. The link to the gitter messaging service is here:
https://gitter.im/nvaccess/NVDA

**Comment by ehollig** [comment]
I recommend bring up questions like these on the [NVDA Gitter](https://gitter.im/nvaccess/NVDA) or on  the [NVDA Screen Reader Development nvda-devel@groups.io](https://groups.io/g/nvda-devel) mailing list. As there has not been discussion here, I am going to close this issue and advise @beqabeqa473 to reach out using one of the channels above.
