### ISSUE TITLE
NVDA 2018.1.1 having problem reading dropdown lists in the Excel 2016 font dialog

### ISSUE THREAD

**Issue by ghost** [nvaccess/nvda#8387]
### Steps to reproduce:

> 1. Open a new Excel work book.
> 2. Press CTRL+Shift+F to open theFont window.
> 3. Tab to Font / Font Style / Size. and try using arrows to navigate.

### Expected behavior:
> NVDA should read Fonts / Font Styles / Size available, e.g. Arial, Times New Roman / Italics, Bold, Underlined / 10, 11, 12, 14, 16 etc.

### Actual behavior:
> NVDA only reads out "blank".

### System configuration:
NVDA version:
> NVDA 2018.1.1

NVDA Installed or portable:
> NVDA installed

Other information:

Windows version:
> Windows 10 SL Version 1803 Build 17134.81

Name and version of other software in use when reproducing the issue:
> Microsoft Office 2016, for students: Excel

### Other questions:

Does the issue still occur after restarting your PC?
> Yes

Have you tried any other versions of NVDA?
> No, I don't have previous copies of NVDA

**Comment by dkager** [comment]
I updated the title to more clearly describe the issue.

**Comment by Adriani90** [comment]
This is still reproducible in NVDA 2019.1.1.
cc: @lukaszgo1, @feerrenrut

**Comment by Adriani90** [comment]
It is also reproducible in Office 365, no need to have Excel 2016 for students on Windows 10s.

**Comment by Adriani90** [comment]
closing in favor of #11504 which ocntains more details.
