### ISSUE TITLE
In email messages list in Thunderbird cannot navigate using Control+Alt+arrows

### ISSUE THREAD

**Issue by mltony** [nvaccess/nvda#8396]
### Steps to reproduce:
1. Open Mozilla Thunderbird.
2. Open any email folder and go to list of email messages in that folder.
3. Switch to threaded view by checking in the main menu: View > Sort by > Threaded
4. Try pressing Control+Alt+Arrows to navigate this table.
5. Nothing happens - these keystrokes don't work.

### Expected behavior:
You should be able to navigate by row or by column in this table.

### Actual behavior:
Nothing happens. NVDA doesn't speak anything after pressing Control+Alt+Arrows. Sometimes Thunderbird switches view to the root of email account instead of the selected folder. 

### System configuration:
NVDA version:
Version: 2018.2

NVDA Installed or portable:
Installed

Other information:
I tried with and without "Mozilla app enhancements" add-on. This issue can be reproduced regardless whether this add-on is running or not.

Windows version:
Windows 10 Version 1803 Build 10.0.17134.112

Name and version of other software in use when reproducing the issue:
Mozilla Thunderbird  Version 52.8.0 (32-bit)
### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
It was working correctly in 2018.1.1 and 2018.1.

**Comment by DrSooom** [comment]
During running NVDA 2018.2 in the "Installer-Mode" (it isn't installed on my system yet) I couldn't figure that out on Win7x64 with Thunderbird 52.8.0. Maybe I check this out later with NVDA 2018.2 Portable. In the meantime please list all installed NVDA and thunderbird add-ons.

I guess you know that you have to move the cursor firstly once to the right - otherwise the cell navigation don't work as excepted. In the very first (left) cell only the full line is reported.

**Comment by mltony** [comment]
I just disabled all my NVDA add-ons and all Thunderbird extensions and I 
could still reproduce the problem on my computer. I also tried running 
NVDA 2018.2 from the installer file and reproduced it again. Could you 
try reproducing it on Windows 10?

I didn't quite understand what you meant by moving to the right. I tried 
pressing RIght arrow and it didn't solve the problem. But right arrow is 
supposed to expand a collapsed message thread in that window. If you 
meant Control + Alt + right arrow, it didn't work either, no matter how 
many times I press it, NVDA doesn't speak anything.

**Comment by DrSooom** [comment]
1. Go to the messages list in Thunderbird.
2. Press NVDA+1 to enable NVDA's Input Help Mode.
3. Press CTRL+ALT+ArrowKeys.
4. NVDA should tell you that the NVDA-Cursor is moving to a specific direction.
5. If so, disable the Input Help Mode with NVDA+1.
6. If nothing is spoken, please upload your "gestures.ini" here. You can find it in C:\Users\%Username%\AppData\Roaming\nvda\. If you only see the file "nva.ini" but no "gestures.ini", please say this too.
7. If not: Please check out if the four CTRL+ALT+ArrowKeys are allocated with the Intel HD Graphics Control Panel.
8. If so, disable all four hotkeys for monitor rotation here.
9. Re-check the four allocations in NVDA within the Input Help Mode while the focus is on an item in the messages list in Thunderbird.

**Comment by mltony** [comment]
1. When I turn on input help mode on messages list in Thunderbird, it 
says the keystroke (e.g. Alt+Ctrl+Right arrow), but it doesn't say the 
gesture name (e.g. "Move to the next table column").

Just for comparison, I tried doing same thing on a table in web browser, 
and it would say "Alt+Ctrl+Right Arrow, Move to the next table column". 
These gestures work fine for me in web browsers.

My interpretation of this is that somehow NVDA doesn't think that 
message list in Thunderbird is a table - at least 2018.2.

2. I don't have gestures.ini file in my local NVDA directory. I don't 
have nva.ini either - but I suspect you meant nvda.ini, I do have this 
file there.

3. Even though my laptop does come with Intel HD graphics chip, I 
couldn't find any place where I could adjust hotkeys for changing the 
display. I suspect that Intel HD software is not installed on my 
computer. Also, judging by the fact that in input help mode NVDA reacts 
on these keystrokes, and the fact that table navigation keystrokes work 
fine in all other applications, I think that these keystrokes are passed 
to NVDA and not intercepted by any other program.

**Comment by DrSooom** [comment]
The main configuration parameters are stored in the "nvda.ini". "nva.ini" was a typo, sorry. As the "gestures.ini" doesn't exist it means that you never made any changes in the Input Gestures Window.

Sadly I can't reproduce your issue with NVDA 2018.2 Portable (clean version) on Win7x64 and Thunderbird 52.8.0.

Please check out again if some Intel drivers/programs are installed on your system. As I'm not familiar with the new Win10-Control-Centers I can't tell you the exactly path to the list of installed software.

One other question: If you moving the focus in Thunderbird with the Tab key around, does NVDA speak something like "table"? The option "Tables" in the NVDA Setting/Document formatting" has to be enabled for this. And don't forget to maximize the Thunderbird window (WIN+UpArrow).

**Comment by mltony** [comment]
1. I didn't found any Intel Programs installed on my computer. I only 
found in Device Manager that my display driver is Intel HD. I didn't 
find any settings page for this driver where I could assign keystrokes.  
I believe that this driver has nothing to do with this bug, since 
Ctrl+Alt+arrows shortcut works in all the other applications except 
Thunderbird. If this driver were intercepting/redefining these 
keystrokes, then they wouldn't work in any application on my computer, 
but this is not the case.

2. Document Formatting > Tables is checked in my settings. Neither NVDA 
2018.2 nor 2018.1.1 Speak the word "table" when I tab into messages 
list. However, Control+Alt+Arrow keystrokes work in 2018.1.1, but they 
don't work in 2018.2.

**Comment by ruifontes** [comment]
In my Thunderbird 52.8.0 (32 bits) 52.8.0 (32 bits) installed in Windows 10 last version (64 bits), with NVDA 2018.2.1 RC1, the table commands work alright, with or without Mozilla enhancements addon...

**Comment by mltony** [comment]
I think I figured out why you couldn't reproduce my problem. My view 
mode was set to Threaded (View > Sort by > Threaded), while the default 
mode is Unthreaded. Could you please check if you can reproduce the 
problem in Threaded mode?


To reiterate what I've figured out so far:

1. Table navigation works well in unthreaded mode in both NVDA 2018.1.1 
and 2018.2, in both installed Thunderbird on my machine and portable 
version that you sent.

2. Table navigation in threaded mode was working in 2018.1.1, but is 
broken in 2018.2. I tested both in installed Thunderbird and portable 
Thunderbird.

3. In unthreaded mode when I tab into messages list it indeed says 
"Table". but, in threaded mode, it says "Tree View" instead. I would 
expect however table navigation keystrokes to still work in threaded 
mode, since they were working in 2018.1.1.


Sorry for confusion - I should've thought of threaded mode when creating 
this bug.

**Comment by DrSooom** [comment]
Yep, now I can confirm this bug on Win7x64 and TB 52.8.0 after changing the Threads-View from "All" to "Threads with Unread". I also created [two logfiles](https://github.com/nvaccess/nvda/files/2108682/NVDA.Bug.8396_20180617_Logs.zip)
 – one for 2018.1.1 and one for 2018.2 – for the devs.

**Comment by DrSooom** [comment]
View » Threads » changing "All" to "Threads with Unread" automatically changes View » Sort by » from "Unthreaded" to "Threaded" – but not vice versa. So if "Threads with Unread" was changed to "All" back, the tree view (Threaded-Sort) still exists. In other words: My logfiles already include exactly this behaviour.

**Comment by DrSooom** [comment]
@@michaelDCurran: Could you please take a look on this new issue? Maybe it's a regression of #2642.

**Comment by DrSooom** [comment]
mltony: Please download Thunderbird Portable 60.0 from [here](https://portableapps.com/apps/internet/thunderbird_portable) and report your results. Thanks.

PS: I deleted my prepared Thunderbird Portable version from my webserver a few minutes ago.

**Comment by mltony** [comment]
@DrSooom, do you want me to test the bug again? I thought it was confirmed on that portable version of Thunderbird that you prepared for me in the previous comments. I downloaded this new version, but I couldn't figure out how to subscribe to an RSS feed. If you still want me to test it, I'll try again on the weekend.

**Comment by DrSooom** [comment]
It could be that this behaviour have been changed between 52.0.8 and 60.0. So:
1. After creating the portable version, open Thunderbird and disable the Lightning add-on first.
2. Restart Thunderbird and close the extension tab.
3. Press Tab as often as necessary to reach a link called "FeedS" (or something like that.
4. When activating this link, a new account for feeds will be created.
5. After that press Tab again to find the link for the subscriptions. You can also reach the same window through the context menu on a folder name in the list view of the new (feed) account.

Maybe this little manual helps developers too. ;)

**Comment by mltony** [comment]
@DrSooom,
I can still reproduce the issue on this version of Thunderbird. I couldn't figure out how to add an RSS feed, but I added my email account instead to test it.

**Comment by DrSooom** [comment]
@mltony: Thank you very much for confirming this. My log files should already be enough to figure out, what's going wrong here.

If my description about subscribing feeds was to short, please visit [this Thunderbird help article](https://support.mozilla.org/en-US/kb/how-subscribe-news-feeds-and-blogs). If you start Thunderbird the very first time, just ignore the e-mail setup wizard on startup. After an account for feeds was created, this e-mail setup wizard will disappear on startup.

**Comment by lukaszgo1** [comment]
Shouldn't this one be closed when #9185 was merged?

**Comment by mltony** [comment]
Yes, this is now fixed. Closing it.
