### ISSUE TITLE
announcements of new messages in google hangouts

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8399]
### Steps to reproduce:
Currently when you receive a new Hangouts message, Hangouts makes a sound.
Or sometimes nvda starts reading all the messages inside the chat.
I would ask if possible, so that nvda announces the new messages, in the moudes of the work that was done for skype for busines.

### Expected behavior:
nvda announce only the new message received.

### Actual behavior:
nvda all messages within the conversation.

### System configuration:
NVDA version:
next 15259

NVDA Installed or portable:
instaled
Other information:
> Example: Running in a VM

Windows version:
windows 7

Name and version of other software in use when reproducing the issue:
chrome 67

### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
> Please list them and the result
no

**Comment by Adriani90** [comment]
@fernando-jose-silva did you test with last Chrome version and NVDA 2018.4 on Windows 10? Is it the same behavior?

**Comment by fernando-jose-silva** [comment]
@Adriani90  Unfortunately I no longer use this tool, used in my work where I do not work anymore.
Also among my friends I do not know who uses the angouts, for me to test.
Thank you.

**Comment by Adriani90** [comment]
@derekriemer can you maybe test if this is still reproducible in NVDA 2019.3 Beta 1?

**Comment by Adriani90** [comment]
I am closing this as abandoned since we don't really have any updates since years if this is still occuring or not. Please comment on this if you are still having this issue and we can reopen.
