### ISSUE TITLE
Attempt to guess the label for unlabelled form fields on web pages

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#84]
**Reported by chris1988 on 2008-05-03 19:18**
is it at all posible to have nvda read the titles of a form field.  when going to fill out a form such as on:
https://www.google.com/accounts/NewAccount?service=mail&continue=http%3A%2F%2Fmail.google.com%2Fmail%2Fe-11-10ca38dcb38a7e30861186cae6d0522b-d070ccae47d4bd7d2b6600c9e6c69e02aa32349b&type=2
is it at all posible to have it read "first name" last name etc? without having to turn vitural buffers off and back on.
**Blocking #3153**

**Comment by leonardder** [comment]
@jcsteh: It seems you started working on this years ago, is there still a desire to implement this?

**Comment by jcsteh** [comment]
I think we still want this, though there's some controversy over whether it should be disabled by default. While I think this feature is important for usability, I also think users really need to know when the information they are receiving is possibly inaccurate. Mislabelling fields could be super problematic in a finance system, for example.

Having said that, I'm not working on this at present.

**Comment by dineshkaushal** [comment]
Many users say that in most of the cases label detection would be useful.

**Comment by Adriani90** [comment]
@leonardder the gmail form is properly recognized by NVDA including all labels. Thus, I suggest closing this issue in favor of #8335.

**Comment by Adriani90** [comment]
The GMail example is not reproducible here, see my comment above. Thus, closing this issue in favor of the referenced one above.
