### ISSUE TITLE
Slow performance in AutoIt Graphical User Interfaces

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#840]
**Reported by parham on 2010-08-20 18:43**
Graphical user interfaces created with AutoIt have a general slow performance, e.g. when navigating from control to control using the tab key, reading the content of controls (e.g. list and tree  views). It varies from system to system depending on the system specs, but it's generally a second delay between the key press and NVDA's feedback.
This can be seen in AutoIt scripts such as NVDASD.

**Comment by dkager** [comment]
[This](https://www.autoitscript.com/trac/autoit/ticket/1199#comment:2) says it works for the developer. Going to mirror that here, but feedback welcome.
