### ISSUE TITLE
Setting speech rate to 100% using SAPI4 causes an exception

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#8400]
(Initially reported by a user via Twitter & Email).

Using a Polish SAPI4 voice, when setting speech rate and pitch to 100% an exception is raised.  This manifests in not being able to open the settings dialog again once it is closed.  Moving the rate slider back just a little prevents this.

Log follows:

INFO - __main__ (13:12:41.206):
Starting NVDA
INFO - core.main (13:12:41.345):
Config dir: C:\Users\HP\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (13:12:41.345):
Loading config: C:\Users\HP\AppData\Roaming\nvda\nvda.ini
INFO - core.main (13:12:41.424):
NVDA version 2018.2
INFO - core.main (13:12:41.424):
Using Windows version 10.0.17134 workstation
INFO - core.main (13:12:41.424):
Using Python version 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
INFO - core.main (13:12:41.424):
Using comtypes version 1.1.3
INFO - synthDriverHandler.setSynth (13:12:41.673):
Loaded synthDriver sapi4
INFO - core.main (13:12:41.673):
Using wx version 3.0.2.0 msw (classic)
INFO - brailleInput.initialize (13:12:41.674):
Braille input initialized
INFO - braille.initialize (13:12:41.676):
Using liblouis version 3.5.0
ERROR - braille.BrailleHandler.setDisplayByName (13:12:41.684):
Error initializing display driver
Traceback (most recent call last):
  File "braille.pyo", line 1595, in setDisplayByName
  File "brailleDisplayDrivers\hims.pyo", line 320, in __init__
RuntimeError: No Hims display found
INFO - braille.BrailleHandler.setDisplayByName (13:12:41.684):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (13:12:41.775):
UIAutomation: IUIAutomation5
WARNING - external:globalPlugins.brailleExtender.configBE.initGestures (13:12:43.266):
No main gestures map (C:\Users\HP\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\Profiles\noBraille\default\gestures.ini; C:\Users\HP\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\Profiles\noBraille\default\gestures.ini) found
INFO - core.main (13:12:43.270):
NVDA initialized
ERROR - unhandled exception (13:12:51.351):
Traceback (most recent call last):
  File "gui\settingsDialogs.pyo", line 930, in __call__
  File "synthDrivers\sapi4.pyo", line 234, in _set_rate
COMError: (-2147418113, 'Katastrofalny b\xb3\xb9d.', (None, None, None, 0, None))
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (13:12:55.812):
Developer info for navigator object:
name: u'Pulpit'
role: ROLE_WINDOW
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.window.Desktop object at 0x050032F0>
Python class mro: (<class 'NVDAObjects.window.Desktop'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: ''
location: (0, 0, 1920, 1080)
value: ''
appModule: <'appModuleHandler' (appName u'csrss', process ID 628) at address 50a22b0>
appModule.productName: exception: processHandle is 0
appModule.productVersion: exception: processHandle is 0
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 65552
windowClassName: u'#32769'
windowControlID: 0
windowStyle: -1778384896
windowThreadID: 800
windowText: u''
displayText: u''

**Comment by josephsl** [comment]
Hi, was this also the case with NVDA 2018.1.1 and earlier? If not, this is a regression. one possible workaround is looking at max value for speech rate and put a cap on rates. I recommend against exception handling because it may appear the settings were being saved when in fact it didn’t. Thanks. CC @MichaelDCurran

**Comment by Qchristensen** [comment]
From the user: "This has always been happening but keeping rate at 100% and pitch at 99% was the trick."

So looks like a previously existing issue rather than a regression.

**Comment by Brian1Gaff** [comment]
I wonder which version of the runtime for this synth is in use. I seem to 
remember in the deep and murky paste that the runtime for these voices are 
often bundled and have several different version numbers. I've never looked 
that closely as in the main I only tend to use them for specific situations 
where I want to make the computer sound like a voice not allowed in later 
synths.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment]
I just installed my old copy of via voice and could get no issues other than 
terrible clipping due to the silly settings in the dialogues.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by leonardder** [comment]
@Qchristensen: It would be good to see whether this problem persists in NVDA 2019.3 Alpha. Having said that, SAPI4 is outdated stuff, so I doubt whether we should invest that much time in investigating the issue, as it seems to be related to a particular SAPI4 engine.

**Comment by Qchristensen** [comment]
I'll chase up the user and see what I can find out.  Mental note to self, next time include user contact details in the issue when writing issues for others!

Are there any SAPI4 voices still readily in use?  I can't even think of any to go and download to try myself (which I think is why I reported this all as secondhand initially, since I didn't have a voice to try to repro it myself).

**Comment by lukaszgo1** [comment]
cc @piciok I believe you are initial reporter of this issue.
At least in Poland some SAPI 4 voices are still very popular, thought I cannot understand why.

**Comment by ehollig** [comment]
@Qchristensen were you able to track down the original poster and find out if this still persists in 2019.3?

**Comment by Qchristensen** [comment]
I have found my original correspondence with Paweł Masarczyk, who reported this to me - I've asked him to check and advise if it is still occurring in 2019.3.1

**Comment by Adriani90** [comment]
@Qchristensen any update on this?

**Comment by Qchristensen** [comment]
I never did get a response, no.  Given that, and the decreasing number of people using SAPI 4, I'm inclined to close this and reopen or create a new issue when we do have confirmation there is even still an issue to resolve.
