### ISSUE TITLE
Review cursor stuck in draft messages in Thunderbird.

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#8402]
In Thunderbird (Using 52.8.0 32-bit release channel), and NVDA 2018.1.1 or 2018.2 (I didn't try earlier versions), NVDA's review cursor seems to get stuck on the quoted message.  To reproduce:
1. Reply to a message in Thunderbird (a short plain text message works well, some longer HTML messages seem to get stuck for about 10 seconds at a time.
2. Press CONTROL+END to jump to the bottom of the message, past the quoted text.
3. Press the right arrow.  NVDA reads a letter.  It is the first letter of the quoted email.
4. Press numpad 5, NVDA reads the first word of the quoted message.
You can naviate around the message ok, either with the text caret or review cursor, but as soon as you try and read the text at the review cursor, it reads from the start of the quoted text, regardless of where the caret is and whether focus moves review cursor is on or off.

I have one Debugwarning, repeated a few times in my log (all the details and error number etc are the same but the objectID advances by 1 each time).

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (22:18:17.243):
oleacc.AccessibleObjectFromEvent with window 461192, objectID 40 and childID 0: [Error -2147467259] Unspecified error

It doesn't seem a critical error, and the workaround seems to be to just to ignore it, and ideally just write the reply above the quoted text.

**Comment by Adriani90** [comment]
@Qchristensen can you still reproduce this issue in Thunderbird 68.3.0 with NVDA last alpha version?
I tried to reproduce it but I am not sure if I understand correctly the issue. I cannot really reproduce it.

**Comment by Qchristensen** [comment]
I just tried this with Thunderbird 60.8.0 (Evidently it's been awhile since I used Thunderbird) and couldn't reproduce it.  I've just updated to 68.3.0 and still can't reproduce this one so I'm going to close as worksForMe.
