### ISSUE TITLE
Provide a rutine for checking if a certain keystroke is in conflict and if yes, which addons are causing the conflict

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8408]
Dear all,

In times of more and more addons which are useful, sometimes users are confronted with errors or conflicts of keystrokes. Some of them use only part of the functions provided by certain addons and might forget which keystroke is atributed to which addon.

So, when pressing a keystroke which is in conflict, it would be very confortable for the user to have a message reporting which addons are involved in causing a conflict for this certain keystroke.

Practice example:
The addons Place markers and BrailleExtender provide both the keystroke NVDA+k for different functions ofcourse. So when pressing NVDA+k, NVDA should report "this keystroke is in conflict with the addons place markers and BrailleExtender". If possible, the function of the keystroke for each addon should be displayed (maybe extracted from the addon help).

In this case, the user would exactly know where the conflict is and what it has to be changed to avoid it.

**Comment by Adriani90** [comment]
Ofcourse this message can be displayed as well, if a conflict between an addon and NVDA itself exists.

**Comment by Adriani90** [comment]
@Andre9642 
@nvdaes

**Comment by nvdaes** [comment]
I think this could be extended to gestures added by users to different commands, not just for installed add-ons, not just for keystrokes, but also other gestures like touch input.
Imo, this could be added as an NVDA feature activated on demmand, not when pressing a gesture. For instance, if someone uses brailleExtender and placeMarkers add-on, but the found gesture performs the function desired by the user, let's say, the brailleExtender function, if NVDA reports a message showing conflicts, the brailleExtender function will be broken agains user wishes. In the other hand, if placeMarkers function is found first but the user doesn't want it, s/he will notice this without the NVDA message about conflicts.
But if a feature is provided on demmand, more conflicts could be found and the user may take action with a global perspective. What do you think?
For example, a button in inputGestures dialog could be provided to filter gestures assigned to different commands.
Thanks

**Comment by Adriani90** [comment]
I agree.

**Comment by Adriani90** [comment]
Closing as duplicate of #7074
