### ISSUE TITLE
upgrade ESpeakNG to the latest version

### ISSUE THREAD

**Issue by Fatihyuksek** [nvaccess/nvda#8409]
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result
Please update espeakng to the latest version because in the current version epseak-ng doesn't read the Chinese characters properly. I am talking about NVDA 2018.2.

**Comment by ehollig** [comment]
Oh no. This does not sound good. CC @feerrenrut @michaelDCurran @josephsl

**Comment by michaelDCurran** [comment]
I don't believe This is specific to 2018.2 as 2018.1 also had this issue. We are waiting for a new stable build of espeak-ng to be released so we can upgrade.

**Comment by feerrenrut** [comment]
Can anyone in the community confirm whether this is a regression (worked in a previous NVDA version, and does not work in the current NVDA version)?

**Comment by Adriani90** [comment]
@Fatihyuksek are you still having this issue in NVDA 2019.1.1 with eSpeak?

**Comment by feerrenrut** [comment]
We haven't had any response on this issue. PR #10572 updates Espeak for reference.
