### ISSUE TITLE
UIA: remove constants that were assumed unavailable in Windows 8.x

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8416]
Hi,

Continuing from #8415:

The internal UIA handler module includes a group of constants that are assumed unavailable in Windows 8. With the advent of IUIA5 support, these constants are in fact included in the UIA interface itself. As the old constants are redundant, I propose removing them (except horizontal text alignment constants, which are still not included in the interface itself).

Thanks.

**Comment by josephsl** [comment]
Hi,

The following constants are now part of UIA interface, thus internal UIA handler does not need to carry them forward:

UIA_StyleIdAttributeId=40034
UIA_AnnotationAnnotationTypeIdPropertyId=30113
UIA_AnnotationTypesAttributeId=40031
AnnotationType_SpellingError=60001
UIA_AnnotationObjectsAttributeId=40032
StyleId_Heading1=70001
StyleId_Heading9=70009
ItemIndex_Property_GUID=GUID("{92A053DA-2969-4021-BF27-514CFC2E4A69}")
ItemCount_Property_GUID=GUID("{ABBF5C45-5CCC-47b7-BB4E-87CB87BBD162}")
UIA_FullDescriptionPropertyId=30159
UIA_LevelPropertyId=30154
UIA_PositionInSetPropertyId=30152
UIA_SizeOfSetPropertyId=30153
UIA_LocalizedLandmarkTypePropertyId=30158
UIA_LandmarkTypePropertyId=30157

Thanks.

**Comment by josephsl** [comment]
Hi,

Actually, the two GUID's are still needed in the module. Thanks.

**Comment by Adriani90** [comment]
The issue referenced above is also merged. I assume this issue is solved then. @josephsl if not, please feel free to reopen it.

**Comment by josephsl** [comment]
Hi, yes, resolved a long time ago (as in last year). Thanks.
