### ISSUE TITLE
remove specific python bugfix versions from python dependency

### ISSUE THREAD

**Issue by roelvdwal** [nvaccess/nvda#8421]
Hello,
It is stated in the readme that python version 2.7.13 is required. But when examining the log file, it appears that nvda is actually built with python 2.7.15. It might be a good idea to update the readme so that it states that python version 2.7.15 is required, or references to a specific bugfix release could be removed, so that it simply lists python 2.7 as a dependency.

**Comment by leonardder** [comment]
I think mentioning the update to Python 2.7.15 in the readme makes perfect sense, but I would mention 2.7.15 and not just 2.7

**Comment by josephsl** [comment]
Hi, putting this on a queue for #7105. Thanks.

**Comment by dkager** [comment]
Since the proposed change is a one-liner and will help developers in the short-term I would still welcome a small patch for the readme even before the transition to Python 3. That said, it could perhaps be bundled in a larger readme spell/grammar check update.

**Comment by josephsl** [comment]
Hi, in this case, I’ll set up a pull request that, among other things, goes over grammar, instructions for PowerShell users and what not. Thanks.

**Comment by josephsl** [comment]
Hi, by the way, I’d wait until wxPython 4 is introduced to master branch before doing more significant work. Thanks.

**Comment by Adriani90** [comment]
@josephsl is there a PR touching this issue? Just to make sure that we reference them together. :-)

**Comment by josephsl** [comment]
Hi, we may still need to hold onto mentioning this info, especially with the speed of Python 3 development (#9543 readme mentions Python 3.7.3). Thanks.

**Comment by leonardder** [comment]
For Python 3, we should mention Python 3.7. We have no control of when appveyor updates point releases, so mentioning a particular point release seems to be overkill and causes more work for us.

**Comment by josephsl** [comment]
Hi, I’ll incorporate this into an upcoming PR on readme. Thanks.

**Comment by leonardder** [comment]
I think it is best to refrain from updates to the readme until 
threshold_py3_staging is ready to go into threshold.

**Comment by josephsl** [comment]
Hi, yes, I’m waiting on that, and also need to make sure pywin32 is no longer mentioned. Thanks.

**Comment by leonardder** [comment]
Pywin32 is still required for py2exe and therefore we bundle it in that 
repo.
