### ISSUE TITLE
Firefox and chrome: impossible to edit page's DOM

### ISSUE THREAD

**Issue by talksina** [nvaccess/nvda#8427]
Problem: with Firefox and Chrome, it's impossible to make on-the-fly modifications inside page's DOM, in a situation where a blind web developer has to test a complex page and suggest accessibility modifications.
When entering HTML editing mode from page DOM inspector, line is empty, both with voice and Braille output, while the problem does not appear on Internet Explorer.

### Steps to reproduce:

1. Open Chrome
2. type a web address. Example: www.nvaccess.org
3. when page is loaded, tab to the element you want to inspect (for example, the "about" expandable menu)
4. press shift+f10 and select "inspect element" from context menu. The page DOM will appear.
5. after inspecting, HTML code regarding this element, is displayed.
6. if sure that right element is displayed, press f10 again, and select "edit as HTML"
7. Edit box appears, but screen reader does not detect it; Braille and voice will return an empty line, while code can be edited and tested by people seeing the screen.
8. Repeat above steps, using Firefox.

### Expected behaviour:

When inspecting an element and editing its HTML, Braille and voice output should be returned, reporting exactly the code line as it is, with Braille focus if its currently focused, and this guides the user in order to be able to edit and test pages DOM without any sighted help.

### Actual behaviour:

When editing a DOM element, Braille and voice return an empty output, while on Microsoft Internet Explorer, text can be edited correctly.

### System configuration:
Chrome 67, Firefox 60, NVDA 2018.2, Windows 10 enterprise 10.0.15063.

**Comment by derekriemer** [comment]
This is because these browsers use code mirror. Code mirror is inaccessible, because it fakes a caret (or edit cursor) from the HTML code, and does not actually update the real cursor position to match. There is a work around, you can copy the code out into a text editor, then play around with it before pasting it back in. Unfortunately there is absolutely nothing NVDA can do to get the text positions since they are faked within the editor written in javascript. In the future, hopefully code mirror and other code editors will take steps to make this possible.

**Comment by talksina** [comment]
hello, thanks for answer; the workaround you mention, seems a partial one, as when you edit code in a text editor, then, when you paste it back, you don't ever know where you're pasting.
I heard about a tool called accessibility viewer -aviewer- from the paciello group, but I do not know how to use it - where to paste URL or where to allow browsers to "talk" to this tool.
Thanks


Inviato da iPhone

**Comment by Adriani90** [comment]
@jcsteh Is this solved in Firefox nightly with the fix regarding scratchpad editor?

**Comment by jcsteh** [comment]
Yes. I believe it may also be solved in Chrome, but that would need to be verified.

**Comment by Adriani90** [comment]
This is solved in Chrome 79 and NVDA 2019.3 Beta 1. Closing as works for me.
