### ISSUE TITLE
Table cell in absolute doe not work when navigating with alt+arrow

### ISSUE THREAD

**Issue by stevenbriscoeca** [nvaccess/nvda#8428]
Hello,

When I try to put a table cell in absolute, nvda gets confused and reads them all at once.

### Steps to reproduce:
1. open link : https://codepen.io/stephendesjardins/full/vrRqdR/
2. use firefox or chrome
3. navigate table headers with alt+arrows
4. you will notice that absolute headers will be all read at once instead of one every time.

### Expected behavior:
They are read like normal tables (one cell at a time)

### Actual behavior:
They are all read at once.

### System configuration:
NVDA version: 2018.2.1

NVDA Installed or portable:
Installed

Other information:
Windows

Windows version:
Windows 7

Name and version of other software in use when reproducing the issue:

### Other questions:
Have you tried any other versions of NVDA?
no

**Comment by Adriani90** [comment]
I think the description suggests to navigate with ctrl+alt+arrows.
I can still reproduce this issue with NVDA 2019.1.1 and Firefox 66.0.4 as well as Chrome 74. In Firefox, only absolute column header 1 is reported. The other absolute column headers are ignored.
In Chrome, no absolute header is reported at all.
cc: @jcsteh, @MarcoZehe

**Comment by Adriani90** [comment]
Now it works as expected in Chrome 81, but in Firefox navigating by columns with ctrl+alt+right arrow in the first row NVDA remains stuck on the first three columns and you just move in circles no matter how many times you press ctrl+alt+right arrow. This happens only in Firefox and only in the first row of the table.

**Comment by jcsteh** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1636807

**Comment by jcsteh** [comment]
This is resolved by Cache the World, which is enabled by default in Firefox 113 release.
