### ISSUE TITLE
Nvda slowly works in Yutube music in Edge

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#8431]
Hello. Nvda works very slowly in Yutube music in Microsoft Edge.
1. Open Yutube Music in edge. 2 start moving in any way.
You will see that NVDA very long responds to keystrokes.
windows 10 1803 nvda next-15363,a87d8187

**Comment by Adriani90** [comment]
@gdata1 how is this in Edge Chromium 81?

**Comment by gdata1** [comment]
@Adriani90 No. it only happens in the old edge. not chromium

**Comment by Adriani90** [comment]
Thanks for reporting. Closing as works for me in Edge Chromium 81 which will be distributed to most users with Windows 10 20 h1 update.
