### ISSUE TITLE
Ordered list numbering always starts from number 1 without regard to type or start attribute in internet explorer

### ISSUE THREAD

**Issue by dineshkaushal** [nvaccess/nvda#8438]
### Steps to reproduce:
1. Open the attached test file in internet explorer.
 2. go to the list under second heading "Next Set".
3. the list numbering should start with number 4 which can be confirmed by opening the same file in google Chrome or Firefox.

### Actual behavior:

The list numbering does not follow start and type attribute. if type attribute suggests alphabets through "a" or "A" or if it suggests roman numeral with "i" or "I", there is no difference

### Expected behavior:

NVDA should read the numbering properly.

Fixing this issue is also important as internet control is used by some software in which case users ccan not switch to Google Chrome or Firefox. One example is vital source.

understanding these numbers is important as question and answers could be numbered with breaks in between and users need to check the corresponding entries.

### System configuration:

Windows 7 

#### NVDA Installed/portable/running from source:
Installed and portable

#### NVDA version:
2018.1.1 and 2018.2
#### Windows version:
Windows 7
#### Name and version of other software in use when reproducing the issue:

Internet explorer 11, Google Chrome, and Firefox.
#### Other information about your system:

[OLHTML.zip](https://github.com/nvaccess/nvda/files/2132668/OLHTML.zip)

**Comment by dineshkaushal** [comment]
Thanks @leonardder for cross checking it. I could not find a way to replace that file.

I agree that Edge is replacing IE11, but there would be a lot of users who would would still be using it. For example I don't use IE now, but vital source uses MSHTML control, and if I am reading a book in vital source I don't have a choice. I am also sure, many other software still use MSHTML control.

Yes, vital source would provide an option to read the book online, but that is not same as reading a book offline. I would request to make it p2.

**Comment by leonardder** [comment]
I guess either @michaeldcurran or @feerrenrut will have to decide about the priority of this one.
