### ISSUE TITLE
NVDA freezes when using Elements List

### ISSUE THREAD

**Issue by bkehl** [nvaccess/nvda#8440]
### Steps to reproduce:
1. Install TestNav from this link: https://drive.google.com/file/d/191u7YGKl7QRXGKNgxj4b6ydvkUHZ5BV6/view?usp=sharing
2. Click Reference
3. Log in with the following credentials (Two Logins Below)
Username LGN028672861 

Password U3KJA2WH
Username LGN148410577
Password URRPKECA
4. Use Insert+F7 to open elements list and choose Skip To Content
5. Open Elements list and choose Skip To Instructions
6. Repeat steps 4 and 5 a couple of times.
7. NVDA stops reading and doesn't allow Tab/Insert}+F7 until the user clicks with the mouse

### Actual behavior:
NVDA requires mouse click using Elements list in fullscreen JXBrowser

### Expected behavior:
NVDA will not require a mouse click to use Elements list

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.2.1

#### Windows version:
Windows 7 Enterprise

#### Name and version of other software in use when reproducing the issue:
TestNav 1.7.1.4

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by jamessetaro** [comment]
Is there any easy way to debug this?

**Comment by ehollig** [comment]
Hello @jamessetaro. Can you restart NVDA with debugging enabled and perform the above steps, starting from the 2nd step, and then attach a text file of your log here? For more information on how to turn on debugging in NVDA or information on log files, please see this link: https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps

**Comment by jamessetaro** [comment]
Yep, will do.

**Comment by vkadri** [comment]
NVDA log file attached. 

[issue 8440-nvda log](https://github.com/nvaccess/nvda/files/2193305/issue.8440-nvda.log)

**Comment by Adriani90** [comment]
So, it seems it is a com error and in my view this issue is related to #7982.
@dineshkaushal what do you think?

**Comment by michaelDCurran** [comment]
The COMError is thrown from calling IAccessible2::uniqueID on the focused element. No doubt it has perhaps died or has been removed from the DOM, yet focus has not been restored to somewhere else. Either that or the Browser engine has not fired a new focus event for accessibility. 
This is only going by reading the log. I shall test the app as well and report back.

**Comment by vkadri** [comment]
Hello,

any update on this?

**Comment by vkadri** [comment]
Hello, is there update on this?

**Comment by Adriani90** [comment]
cc: @josephsl

Von meinem iPhone gesendet

**Comment by josephsl** [comment]
Not me - CC @MichaelDCurran

**Comment by vkadri** [comment]
Hello,

Any update on this?

**Comment by vkadri** [comment]
Hi, any update on this? This is still an issue.

**Comment by Adriani90** [comment]
@vkadri can you still reproduce this in NVDA 2023.2?

**Comment by Adriani90** [comment]
We didn't get any updates upon request from the initial author since many years, whether this issue is still reproducible in 2024 or not.
I am closing as abandoned, given also the test was done in Windows 7 which is no longer supported by NVDA.
If you are still having this issue in Windows 10 or 11, please comment and we can reopen.
