### ISSUE TITLE
NVDA echoes the contents of the Google Groups Compose edit box as each character is typed

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#8442]
### Steps to reproduce:
Simply open a Google Groups page like https://groups.google.com/forum/?nomobile=true#!forum/eyes-free , open one of the topics from the list of available topics, select the "Sign in to reply" option if you're not already signed in to your Google account, and select the "Post reply" option.
### Actual behavior:
Once you start typing in the "Compose a new message edit multi-line edit line" edit box you'll notice the issue. With each character you type, NVDA keeps repeating what you've already typed into the edit box -- and that gets really annoying as more text gets typed into the field. Also the last typed character is repeated two or three times, followed by the message "Compose a message."
### Expected behavior:
Like what happens in other edit boxes, NVDA should just repeat the typed character and respect the "Speak typed characters" settings (NVDA+2) instead of repeating the contents of the edit box from beginning to end with each character which gets typed.
### System configuration:
Various Chrome/Firefox recent releases (currently testing on Google Chrome 67.0.3396.99).
#### NVDA Installed/portable/running from source:
installed
#### NVDA version:
2017.1, 2017.2, 2017.3, 2017.4, 2018.1, and 2018.2
#### Windows version:
Windows 10 and Windows 7, both 64-Bit and Pro.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
Yes -- as mentioned above

**Comment by ehollig** [comment]
Is this due to Aria Live?

**Comment by derekriemer** [comment]
yes, this is almost certainly Aria live. Someone should get on Google to remove this "feature" from google groups as screen readers can handle it.

**Comment by amirsol81** [comment]
For the record, this cannot be duplicated with JAWS, so it seems that
FS developers have taken care of it themselves.

**Comment by amirsol81** [comment]
This issue still persists with Google Chrome version 80.0.3987.116 and NVDA Version: alpha-19724,2c4caa62.
Any solutions, work-arounds or fixes? In case it helps, JAWS 2019 and 2020 work well there.

**Comment by jcsteh** [comment]
Etherpad exhibits this issue as well in some cases.

While this is definitely authoring error, I think it'd be worth considering tweaking NVDA to ignore live region changes in an editable element. I can't think of any situation in which this is desirable and not authoring error and it seems JAWS is already doing this, so I don't think there's any risk of false positives.

**Comment by jcsteh** [comment]
This appears to be fixed in Google Groups now, but I've definitely seen it in places other than Etherpad.
