### ISSUE TITLE
NVDA is very slow when browsing the Android class list page

### ISSUE THREAD

**Issue by dnz3d4c** [nvaccess/nvda#8450]
### Steps to reproduce:
1. Open Android class list page: <https://developer.android.com/reference/classes>
2. Wait for the page to open. The page takes a long time to open.
3. When the page opens, press the H key several times to move. Alternatively, press t to navigate through the child elements of the table.
### Actual behavior:
NVDA pauses frequently when moving to the previous or next element or moving an element using the single-letter command.
### Expected behavior:
- I think there is a delay in navigation because of the large page size, but I think that navigation should be more smoothly navigated.
- If you test without using the add-ons, NVDA will be less likely to stop when you browse than when you use add-ons.
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
next
#### Windows version:
Windows10(version:1803)/ Locale:Korean
#### Name and version of other software in use when reproducing the issue:
Firefox(Nightly/64bit), Chrome(canary/64bit)
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No

**Comment by Adriani90** [comment]
@dnz3d4c I am testing with NVDA 2019.1.1 on Firefox 66.0.4. After waiting about two minutes for the website to load, the navigation works well just like on other websites. I do not see a significant performance lack. Do you still have this problem in NVDA 2019.1.1? Which synthesizer and which addons are you using? If you use focus highlight, could you please disable it and see if it gets better?

**Comment by Adriani90** [comment]
We do not have any updates from the initial author since more than 16 months. Closing as abandoned and works for me also with NVDA 2019.3 Beta 1.
