### ISSUE TITLE
NVDA prevents typing and adding a new product key for Windows 10

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#8458]
### Steps to reproduce:
Press the Windows key, type the phrase "About Your PC' and press Enter to open the System Settings window, press Tab a couple of times to reach the control which reads as "Windows specifications  grouping: Change product key or upgrade your edition of Windows  link" and press Enter, press Tab a couple of times to reach the control which says "Change product key  link," and press Enter or Space to activate it.
### Actual behavior:
NVDA reads the following, but gets stuck and doesn't allow us to type a key or move to the Next/Cancel buttons: Enter a product key  dialog  Enter a product key
Your product key should be in an email from whoever sold or distributed Windows to you, or on the box the Windows DVD or USB came in.
Quite interestingly, sometimes NVDA doesn't even read the above dialog and remains silent as we press Enter or Space on the "Change product key" link. The point is that it apparently gets stuck regardless of whether or not it reads the dialog as we can't navigate around the dialog or type the key.
### Expected behavior:
NVDA should open the dialog, allow us to type the key in the edit box, and navigate to Next/Cancel buttons via Tab/SHIFT+Tab.
### System configuration:
Windows 10 Pro 64-Bit, over the last couple of months, currently running Version 1803 (OS Build 17134.137)
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
2018.1, 2018.2
#### Windows version:
Currently Windows 10 Version 1803 (OS Build 17134.137)
#### Other information about your system:
Tested with Narrator, and it works as expected. Also tested with NVDA's various TTS engines, but the glitch is TTS-independent.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
Yes -- as mentioned above.

**Comment by josephsl** [comment]
Hi, my own tests indicate that this is unique to 1803, as this problem is gone in Redstone 5 (for now). One workaround is restarting NVDA as soon as this screen comes up, which should then allow it to navigate this screen. Thanks.

**Comment by amirsol81** [comment]
Hi. Thanks for testing this with an Insider release of Windows.

**Comment by Adriani90** [comment]
@amirsol81 are you still having this problem in NVDA 2019.1.1 on Windows 10 1809 Update?

**Comment by amirsol81** [comment]
This is no longer duplicable with NVDA alpha-20005,14c2e2ec and Windows 10 Pro 64-Bit Version 2004 (OS Build 19041.207). So I suggest closing it.
