### ISSUE TITLE
Controling menu voice and reading voice

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#847]
**Reported by ManuelRamos on 2010-08-22 05:33**
It will be very usefull distinguishing between reading and menu voice and maybe also pontuaction voice. In fact, since there are many synths, ones more helpfull to read what appears on the screen; and others, more accurate, to read books but not much eficient to control NVDA's performance; it would be important that user could configurate each function of voice required: perheaps faster when reading menus, slower and different voice for reading, etc.
**Blocked by #650**

**Comment by leonardder** [comment]
@JCSTeh: is it correct that this at least requires #4877?

**Comment by ruifontes** [comment]
The only use case I remember is having the operating system and apps in 
english and using all documents, mails and so on in portuguese.
I know some portuguese banks have systems like that...

Rui


-----Mensagem Original----- 
De: James Teh
Data: 19 de julho de 2017 03:25
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Controling menu voice and reading voice (#847)



Yes. However, I'd want to see a use case for having different voices for 
reading text and reading menus before even considering this.

**Comment by Adriani90** [comment]
Is this not blocked by speech refactoring?

**Comment by ehollig** [comment]
Yes, this is blocked by #7599 and #4877

**Comment by CyrilleB79** [comment]
@ehollig could you please remove the blocked label now since the corresponding issue and PR are closed/merged? Thanks.

**Comment by Adriani90** [comment]
Closing as this is already splitted into more issues, especially in favor of #4086, #6615 and #10363.
