### ISSUE TITLE
NVDA not reading UAC prompts

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#8470]
### Steps to reproduce:

Do something that causes a UAC prompt to appear, such as agreeing to install an NVDA update.

### Actual behavior:

Narrator reads these instead. 

### Expected behavior:

NVDA should read the UAC dialog

#### NVDA Installed/portable/running from source:

Installed

#### NVDA version:

master-15444,c1a3b0ba

#### Windows version:

Windows 10 1803 RTM, [Version 10.0.17134.112]

#### Name and version of other software in use when reproducing the issue:

N/A

#### Other information about your system:

I've also tried toggling the "use NVDA on logon screens" option to no, choosing apply, then toggling it back on. Also tried toggling NVDA's checkbox in the ease of access centre.

This is a problem because when narrator is active, alt+y appears to not activate the yes button and pressing tab to move about the dialog gives no feedback; only realized this when I had auto updates keep on failing even though I thought I gave it permission.

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA?

No

**Comment by josephsl** [comment]
Hi, is this a side effect of setting synthesizer to auto? This is a change so that when no specific synthesizer is specified, Widnows OneCore voice will pop up. Thanks.

**Comment by Neurrone** [comment]
Narrator appears to be reading the prompts properly again after a reboot, but NVDA still isn't being used. I have an explicit synthesizer set, tried changing it back to ESpeak with no effect.

**Comment by josephsl** [comment]
Hi, you need to copy settings to secure screens (NVDA menu/Preferences/Settings/General). Thanks.

**Comment by Neurrone** [comment]
Thanks, that worked after I realized alt+y wasn't choosing yes in UAC for some reason.
