### ISSUE TITLE
browse mode find invitations in hangouts

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8476]
### Steps to reproduce:
In the company where we work, we are now using hangouts for communication.
I received an invitation from a person outside the organization to talk.
A person with vision reported that the invitation appeared on the screen, including she placed the mouse over the invitation and nvda announced as a button invitation xxx.
However when navigating with the arrows on and off through the browse mode window, how much with the tab by the page focus mode the invitation does not gain focus, only with the use of the mouse.
Also searching in the window nvda does not find the button.

### Actual behavior:
the invitation to new conversation does not gain focus with the keyboard.
I do not know if this invitation will only appear in corporate accounts and if only when outside the company.
I'm quite new to using this platform
### Expected behavior:
it should be possible to locate the invitation by navigating the page with the arrows in the browse mode.

#### NVDA Installed/portable/running from source:
instaled
#### NVDA version:
next 15445
#### Windows version:
windows 7
#### Name and version of other software in use when reproducing the issue:
chrome 67
#### Other information about your system:
due to hurry when responding to the invitation because I was at work I could not explore the issue anymore, testing in another browser.
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by Brian1Gaff** [comment]
What about other browsers?

It would be interesting to know this as it might, in fact be a page 
authoring error and nobody can 'see' it with a screenreader.
 Brian

**Comment by fernando-jose-silva** [comment]
Unfortunately I did not have time to test.

**Comment by Adriani90** [comment]
@fernando-jose-silva are you still having this issue in NVDA 2019.1.1, Chrome 74 or Firefox 66.0.4?

**Comment by fernando-jose-silva** [comment]
I can not test, if there is anyone interested in continuing this question can be closed.

**Comment by Adriani90** [comment]
@derekriemer, @novalis7747, @lukaszgo1 are you maybe able to test if this is still reproducible? I did never use hangouts before.

**Comment by Adriani90** [comment]
Since I do not use hangouts and cannot test unfortunately and many requests for updates did not result in meaningful results, I am going to close this as abandoned. Please comment on it if you have test results and we can reopen. Thanks.
