### ISSUE TITLE
Difficulties operating in a website: www.doepalavras.com.br

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#848]
**Reported by ManuelRamos on 2010-08-22 06:34**
When accessing site http://www.doepalavras.com.br/ it comes a Java object. Pressing enter to open it, I can see 3 fields: name, place - city and country - and message. Difficulty comes when navegatin between feelds. It seems that NVDA freezes. However, Jaws doesn't work at all. It is an interesting site to leave message to cancer victimes. Perheaps a word can help passingthrough that big problem.

**Comment by dkager** [comment]
This URL doesn't work for me anymore.

**Comment by jcsteh** [comment]
Nor me. Closing as invalid.
