### ISSUE TITLE
Add Kurdish language family

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8490]
Hi,

Continuing from #8488:

### Rationale
When it comes to adding a new language (or a family of languages), using two-letter ISO 639-1 was sufficient for many languages. However, this is becoming a liability as certain languages are reclassified based on updated linguistics research.

One compelling case is Kurdish, a family of languages spoken in the middle east (Iraq, Turkey and other countries), comprising three dialects: Northern, Central, and Southern. In the old days, the code "ku" was assigned for Kurdish, but it only covered Central Kurdish (Iraq).

In 2018, a Central Kurdish speaker offered to translate NVDA into Kurdish. A few months later, another person who speaks Northern Kurdish joined the translations team. Around that time, there was a debate on NVDA translations mailing list regarding which code to assign to Kurdish family, with some people proposing "ku", others proposing "ckb" for Central Kurdish, with one person suggesting ku_IQ. Upon further investigation, it was decided to assign three-letter code for Kurdish language family: "ckb" for Central, "kmr" for Northern (based on ISO 639-3), because if "ku" is assigned, only Central Kurdish would be recognized, as Northern and Southern variants are not listed in Windows LCID database at all (see #8489 for justifications).

### Steps to reproduce:
1. Run NVDA from source code and add the following folders and correct locale content to source/locale: ckb, ku, ku_IQ, ku_NO, kmr.
2. Restart NVDA from source code and see if the new Kurdish language family are displayed. This must be done from a system running Windows 10 and another running Windows 7 or 8.x.

### Actual behavior:
Only Central Kurdish is recognized.

### Expected behavior:
All Kurdish variants are recognized.

#### NVDA Installed/portable/running from source:
Installed and source

#### NVDA version:
N/A (not applicable because this is a new language)

#### Windows version:
Windows 7, 8.1, 10

#### Name and version of other software in use when reproducing the issue:
N/A (not applicable)

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
N/A

### Remarks
1. Kurdish must be added to list of languages where description retrieval fails (alongside Aragonese), as only Central Kurdish is registered on Windows 10.
2. There might be questions about assigning three-letter code to some languages while using two-letter code + possible country codes for others. The answer is that, in source/locale folder, you'll see one or two folders with the three-letter language code.

Thanks.

**Comment by zstanecic** [comment]
Hi,
which files are responsible for this fix?

**Comment by josephsl** [comment]
Hi, source/languageHandler.py. I’m working on this as part of a series of commits designed to update our attitudes about locale names and such for 2018. Thanks.
