### ISSUE TITLE
NVDA ignores reading next element after reading onblur alert message

### ISSUE THREAD

**Issue by sripalreddyadamala** [nvaccess/nvda#8492]
Hi All,
              I have error messages for username and password fields and I have put role="alert" and aria-live="polite" for error messages.  Screen reader ignores reading password label on tabbing  onblur in username field.
url to test:

### Actual behavior:
Ignores reading password text label after reading alert  validationmessage in username text message
### Expected behavior:
Need to read password label on tab from username to password textbox
#### NVDA version:
218.2.1
#### Windows version:
7

#### Other information about your system:
windows 7 or mac
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
No

![image](https://user-images.githubusercontent.com/17653691/58930150-448c5580-8728-11e9-9d25-5ea9a4776fb5.png)

**Comment by josephsl** [comment]
Hi, reproduced in IE (which doesn’t read the alert) and Firefox (after couple tries). CC @JCSTeh

**Comment by michaelDCurran** [comment]
We can only fix this once #7599 is merged. However, I don't want to do that until #8006 is merged.

**Comment by sripalreddyadamala** [comment]
hey looks like #7599 is close are you going to work on this defect

**Comment by Adriani90** [comment]
We didn't get any updates upon request since many years from people who could reproduce this in the past. I am closing as abandoned, also due to the fact that we don't have a minimal test case. If you are still having this issue, please provide the information requested and we can reopen.
