### ISSUE TITLE
Using IE 11, NVDA Can't Navigate To In-page Links On A Website

### ISSUE THREAD

**Issue by RD-Brown** [nvaccess/nvda#8496]
Using Internet Explorer Version 11, NVDA does not open in-page links on the site:  http://accessibility.pearson.com/nemethdatabase/

### Steps to reproduce:
1.  Open the following URL in IE 11:  http://accessibility.pearson.com/nemethdatabase/
2.  Press H three times to move to the heading, "List of Symbols and Math Terms."
3.  Down Arrow to any link, such as Absolute Value.
4.  Try pressing both Space and Enter, and note that nothing happens.
5.  Press Tab, note that the link receives focus, at which point both Space/Enter work as expected.

### Actual behavior:
In-page link is not navigated to when Space/Enter is pressed.

### Expected behavior:
NVDA should move to the specified location on the page when Space/Enter are pressed.

#### NVDA Installed/portable/running from source:
Installed.

#### NVDA version:
V2018.2

#### Windows version:
Windows 10 Version	10.0.15063 Build 15063

#### Name and version of other software in use when reproducing the issue:
Internet Explorer V11.1155.15063.0

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA?
Yes, V2018.1 with the same results.

**Comment by ehollig** [comment]
Hello RD-Brown,

Thank you for reporting an issue. This appears to work as expected for me using the steps you provided above in IE 11.
When navigating to the heading titled "List of Symbols and Math Terms" and using the down arrow, it appears that there is a list of same page links. A bullet symbol, •, precedes these links. When using the down arrow key when screen layout is on, focus is placed on the bullet symbol. Using CTRL+Left arrow to the next word will place screen reader focus on the link that can be activated.
Alternatively, you can turn off screen layout in Internet Explorer. To do this, press NVDA+V when browsing a web page. This will allow the link to obtain focus when the down arrow is pressed.

**Comment by RD-Brown** [comment]
Dear Ethan,

Thank you for the explanation. Initially this behavior only appeared to be occurring in IE, but I can now confirm it in FF and Chrome as well. I will advise users to turn off layout mode if they wish to Down Arrow to the links directly.

Dan
