### ISSUE TITLE
Suggestion to add a button to view changes on update prompt

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#8498]
When NVDA prompts that there is a new version to update to.  It could be useful to have an option (eg a button) to view the what's new / changes file.

This was a suggestion from a user on Twitter, but when I was thinking of a use case for this, the first one that came to mind was when updating alpha versions, it would be useful to see what has changed since the last alpha version, which could give an indication of what new or changed features to test.  I realised this would potentially require changing the way the changes.html file is written for alpha builds in order to show that information.

For general users, the same applies, however - to see what has changed from NVDA 2018.1 to 2018.2.

Potentially it could be useful in cases where a point release was needed which may not affect everyone.  A user could see what had changed and elect not to update yet until they had access to more data.

For alpha and beta releases, this would require hosting the latest what's new file somewhere (perhaps just to something static like ../nvda_alpha_changes.html ).

**Comment by Brian1Gaff** [comment]
Yes, I noticed something like this on many the bits of software. IE when you 
get the  new version, one option sends you straight onto the web site to the 
top of the whats new ever changing list. Is this what you mean?
Brian

**Comment by seanbudd** [comment]
Closing as a duplicate in favour of the newer #14274
