### ISSUE TITLE
Sometimes, object roles are missing in braille in Edge browse mode

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#8508]
### Steps to reproduce:
1. Download [this](https://github.com/nvaccess/nvda/files/2200500/roletest.html.txt) file, changing the extention to html only
2. Open the file in Microsoft Edge.
3. Move through the contents with down arrow, and observe what's on a braille display.

### Actual behavior:
NVDA does show the role for the heading (h1) and link (lnk), however the role for button seems omitted.

### Expected behavior:
All roles should be shown in braille.

#### NVDA Installed/portable/running from source:
Installed and from source

#### NVDA version:
alpha-15527,9c3f5bc8

#### Windows version:
Windows 10 april 2018 update

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes, I ran NVDA from source and was able to reproduce this. I didn't try an official release yet.

**Comment by michaelDCurran** [comment]
I can reproduce this. However, it seems to specifically happen when the 
cursor is on the first character of the field. E.g. when on the 'b' of 
button, the role is not shown. Yet when on any other character in the 
word the role is correctly shown again.

**Comment by leonardder** [comment]
I found an issue that might be related.

Code snippet: `<div role="search" aria-label="This is a search landmark">test</div>`

Control field for the landmark: `FieldCommand controlStart with {'runtimeID': (42, 329956, 4, 10), '_startOfNode': False, '_endOfNode': False, 'role': 86, 'states': set(), 'nameIsContent': False, 'name': 'This is a search landmark', 'description': '', 'level': None, 'embedded': False, 'isBlock': True, 'roleText': 'search landmark', 'landmark': 'search', 'current': None}`

Note the _startOfNode value, which is False and really should be True here, as I were positioned at the start of the landmark. This was again the first cahracter in the landmark itself.

**Comment by leonardder** [comment]
I'm closing this because we're now using IA2 for Edge Chromium. If we ever move to UIA for Edge/Chrome, that's still a different story.
