### ISSUE TITLE
confused browsing in outlook.com

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8511]
### Steps to reproduce:

While in navigation mode.
Open Outlook online:
outlook.com
Log in to a microsoft account in my case I created a new account using the email @ outlook.com
After going through all the introductions, I agreed to use the new viewlook.com outlook.com.
My goal is to locate the new email button.
I pressed ctrl + home and navigated with arrows below:

### Actual behavior:
it was not possible to navigate through some items on the page, notably the new email item is not found.
now if you navigate the end page to the beginning:
Press ctrl + end and navigate with arrows to the bottom.
See that the new email item is found, as well as other items not previously spoken.

### Expected behavior:
the expectation that the navigation sense from bottom to bottom, or from bottom to bottom, the elements found on the page should be the same.
Also note that the navigation of the nvda by the page is restricted depending on the region reached first on the page.

#### NVDA Installed/portable/running from source:
instaled
#### NVDA version:
alfa 15527
#### Windows version:
10 17134.165 e windows 7
#### Name and version of other software in use when reproducing the issue:
chrome 67
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by Adriani90** [comment]
@fernando-jose-silva are you still having this issue in NVDA 2019.1.1 and Chrome 74?

**Comment by fernando-jose-silva** [comment]
everything worked fine chrome 74, windows 10 18362.86, nvda 17134
thank you very much.

**Comment by ehollig** [comment]
Thank you @fernando-jose-silva for reporting back. Closing as worksforme
