### ISSUE TITLE
Add the ability to completely disable NVDA's logging (including NVDA's crash dumps)

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#8516]
### Paths:
1. NVDA menu » Preferences » Settings... » General
2. C:\Users\[Username\AppData\Local\Temp
### Actual behaviour:
At the moment there isn't any way to completely disable NVDA's logging via the GUI which cause security and privacy issues in some circumstances.
### Expected behaviour:
Add a new logging level called "No logging" to the combobox "Logging level". This will also disable creating the files "nvda_crash.dmp" and "nvda-old.log" in the user temp folder during a NVDA crash as well.
#### NVDA version:
2018.1 (and earlier) to 2018.2.1

**Comment by josephsl** [comment]
Hi,

2018 GDPR...

Can you tell us one or two compelling justifications other than closing security and privacy hole as to why this should be done?

Thanks.

**Comment by josephsl** [comment]
Hi,

I should have said, "one or two additional justifications other than closing security and privacy hole". Thanks.

**Comment by DrSooom** [comment]
If the bluetooth name of a braille display contains personal data like the name of the owner and this information is logged by NVDA data, then of course it effects the GDPR. Because maybe someone wants to connect his braille display to a –let's say – public PC or to an non-trustable PC, the owner of those PCs could find out the real name of the owner of the braille display, even if he didn't want that.

Well, and what does the NVDA crash dump files exactly contains? I couldn't find any information about this in the NVDA user guide as well as in [this](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) and [this wiki article](https://github.com/nvaccess/nvda/wiki/Debugging-crashes).

So the question should be: Why does a normal user needs to be logged by NVDA – even if the logging level is set to "Information"? And the crash dump is only useful for debugging. So in other words: If a developer isn't asking for that, why is it created be default?

And one more question: Does NVDA reads anything from the logfile during running?

**Comment by josephsl** [comment]
Hi,

Bluetooth device name: as far as I knw (I'm sure @LeonardDer have more accurate info), NVDA doesn't care which bluetooth device it is connected to as long as it can be located easily (using a ID format I believe). For example, when I change my BrailleNote Apex's device name to my name, NVDA will still find it.

Regarding crash dump content: it contains things such as active memory set (mostly virtual memory), values of CPU registers, stack traces and what not.

As for NVDA being able to read from log: no, it can't (users can) unless a malicious actor comes along and queries where NVDA stores logs through inspecting address space of nvda.exe (via another app, which NvDA can fall victim to if code injection routine somehow calls the tampered function somehow).

Tanks.

**Comment by DrSooom** [comment]
As NVDA isn't able the read from its own logfile, why it creates one at all? If everything works fine, nothing should be logged by NVDA – even not the minimum information with their timestamps in milliseconds. Well, and forensic isn't an argument here because Windows itself logs thousands of things. But this isn't an argument against disabling NVDA's logging too at the same time.

Yep, and regarding malware: As NVDA is open source it will be quite hard to protect the end user against debug logging. In the end the warning prompts will not help, but this is a general issue which effects every software.

Maybe the whole logging functionality could be extracted from NVDA. So, if someone wants to provide any logfiles or crash dump he has to install a debug add-on first. Without this little add-on, both feature are functionless. But this would be a quite lot of work. I would say that this maybe isn't a suitable solution at all, but the first in my mind how to protect normal user completely from logging.

**Comment by josephsl** [comment]
Hi,

Hmmm, I see.

A few questions:

* Suppose a "normal user" is using NVDA with all traces of logging off. Then he or she comes across an issue that only log content can be used to obtain more info. Do you think that's a fair justification to commit to this solution?
* Suppose a user does turn off logging facility out of security and privacy concerns, and somehow finds oneself dealing with an issue that does require developers to get whatever they need. Do you think this is right?
* Do you think many so-called "normal users" would care about data privacy right away despite being told that, under right circumstances, NVDA can log input/output info?
* What is better: willing to make NVDA better by sharing an important log fragment that demonstrates a bug, or just turning off logging altogether out of fear of this leaking out to the world without users knowing it?
* What do you think is better: have content ready to be served upon request, or provide a key that locks or unlocks what's inside without giving good reasons?

I would like to request this a third time: so far, all the reasons and scenarios given have to do with closing security and privacy hole. Can you tell us a compelling justification or two as to why the proposed solution is good? Also, who will this benefit, including how and why?

Thanks.

**Comment by DrSooom** [comment]
"-mrs" doesn't stop logging. And "-l" also not. This isn't a solution!

Well, and on the other hand you couldn't tell me why it is so difficult to explain an user how to temporary enable logging via an add-on. Do you really thing it's okay that non-sense information for the end user is logged every time? Why?

Well, one more security reason: If an malware is installed on you PC and it changes the NVDA logging level and sends the NVDA logfile to a C&C server, you entered password on a website as well as all other IO has compromised. And not all websites support 2FA yet.

Okay, one last argument from my side: Advertisement. If you extract all the logging and crash dump functionality from NVDA into an add-on, you can say that NVDA is the most secure screen reader on the globe because absolutely nothing is logged.

At this point I really strongly recommend to calm down and wait to listen what the others say to this issue.

**Comment by josephsl** [comment]
Hi,

One more thing: let me know if I sounded very harsh throughout this exchange.

Thanks.

**Comment by leonardder** [comment]
[**@DrSooom**](https://github.com/DrSooom) commented on [19 Jul 2018, 04:21 CEST](https://github.com/nvaccess/nvda/issues/8516#issuecomment-406133557 "2018-07-19T02:21:56Z - Replied by Github Reply Comments"):
> If the bluetooth name of a braille display contains personal data like the name of the owner and this information is logged by NVDA data, then of course it effects the GDPR. Because maybe someone wants to connect his braille display to a –let's say – public PC or to an non-trustable PC, the owner of those PCs could find out the real name of the owner of the braille display, even if he didn't want that.

If one connects his bluetooth device to a pc, logging is also performed at the Windows level and the bluetooth device is most likely saved as paired device at that particular system itself. NVDA's logging doesn't contribute to a privacy issue here, in my opinion. Note that one who doesn't want his name to be publicly available should just not put it in bluetooth names.

I think we should only consider investigating this issue if there is some statement in the GDPR that explicitly states that this kind of logging of personal data is not allowed. Note that the log is *never* updated to NV Access or the NVDA project unless you explicitly do this yourself. On many public places, the temp folder is automatically erased when you log off. Furthermore, there are many applications that log relevant data we don't even know about. I'm pretty sure that screen reading software like ZoomText and JAWS perform logging at a similar level as NVDA does.

**Comment by josephsl** [comment]
Hi,

Can creating an add-on resolve this: yes... and no. Yes, provided that this add-on is willing to patch various NVDA functions, including C++ code. Unfortunately, because of current routines, it cannot be done.

As for this being an advertisement pitch: telling people that NVDA is secure because logging facility is completely turned off, yet also advertising an add-on that can "restore logging features and debug NVDA", is, to me, a form of deceptive advertising. Deceptive advertising not only damages the ethos of the advertiser, but also the credibility of NVDA, NV Access, and the global NVDA community. Thus, although this may have good intentions, I think it might not be a good idea to use this solution as part of an advertisement literature.

Thanks.

**Comment by DrSooom** [comment]
@josephsl: Our discussion remembers me on discussion about using Threema and Signal instead of WhatsApp, Facebook Messenger and SMS. Metadata without the message content itself also provides sensible data. Just try to find out how many metadata are stored when submitting a tweet on Twitter. (btw: My tweets are protected since my registration, but Twitter knows all. That's what you have to know.)

Okay, but it's good to know that extracting the logging functionality isn't possible at the moment (July 2018).

And to the ad point: How many NVDA users are posting issues in compare with all NVDA users? Sadly, no one can really say this. If – let's say – 95 % of all NVDA users never provides logfiles and crash dumps, I see no reason why NVDA have to log something for them. It makes no sense. And if the run into an issue, we should give them a step by step manual in different languages how to enable logging and how to act with logfiles in combination with privacy.

Remember that I set up a clean Thunderbird Portable copy for bug #8396 because I don't wanted that anyone can see my private Thunderbird instance. But how many NVDA users will do this? I don't think that anyone here is able to say this because we all have different backgrounds and experiences. so in my opinion that's why we haven't the permission to put a bunch of unknown users into a specific group.

btw: Apple also support additional diagnostics on iOS which has manually to be activate via an link on an e-mail from Apple for a specific ticket. (I checked this out right now because I don't want to say anything wrong.)

@leonardder: As JAWS and ZoomText aren't open source you aren't able to know this exactly. And we should not forget that those two products have to be activated as well which will additional data to their companies. Okay, in the meantime it's just one – VFO.

**Comment by Brian1Gaff** [comment]
I have to say, I've noticed many other some commercial pieces of software 
creating logs with often personal info in them under certain conditions 
including Dropbox and Adobe, so is this really a greater problem than with 
these other pieces of software?
 If its security, maybe we need to find out what the min standard is 
supposed to be, its very easy to become so paranoid as to make a system 
unusable.

Brian

**Comment by PratikP1** [comment]
The GDPR intends to protect the personal data of EU residents and the data which is deemed personal is:
1. Basic identity information such as name, email, address, and ID numbers
2. Web data such as location, IP address, cookies data, and RFID tags
3. Health, genetic, and biometric data
4. Racial or ethnic data
5. Political opinions
6. Sexual orientation

In this discussion, the only potential bit of "personally identifiable information" considered is Bluetooth device name. By itself, a Bluetooth device name is not an indicator of something personal. I can choose to name my display Dragon's display or Wizard's stafff. No one but I know what such a name means. 

The regulatory regime recognizes collection, processing and control as three separate mechanisms. As collection of this data remains on the machine controlled by an individual while explicitly not collecting data fitting into the six categories defined above, GDPR would not apply.

As to some malware redefining logging level and capturing user data--it can easily do so whether or not the level is set at info, the current default, or the proposed "no logging." Completely disabling logging as a potential deterrent weighed against the significant benefit that logging provides as a support mechanism argues for keeping the logging system as it is.

**Comment by derekriemer** [comment]
[**@DrSooom**](https://github.com/DrSooom) commented on [Jul 18, 2018, 9:04 PM MDT](https://github.com/nvaccess/nvda/issues/8516#issuecomment-406139920 "2018-07-19T03:04:06Z - Replied by Github Reply Comments"):
> As NVDA isn't able to read from its own logfile, why it creates one at all? If everything works fine, nothing should be logged by NVDA – even not the minimum information with their timestamps in milliseconds. Well, and forensic isn't an argument here because Windows itself logs thousands of things. But this isn't an argument against disabling NVDA's logging too at the same time.
> 
> Yep, and regarding malware: As NVDA is open source it will be quite hard to protect the end user against debug logging. In the end the warning prompts will not help, but this is a general issue which effects every software.
> 
> Maybe the whole logging functionality could be extracted from NVDA. So, if someone wants to provide any logfiles or crash dump he has to install a debug add-on first. Without this little add-on, both feature are functionless. But this would be a quite lot of work. I would say that this maybe isn't a suitable solution at all, but the first in my mind how to protect normal user completely from logging.


[**@josephsl**](https://github.com/josephsl) commented on [Jul 18, 2018, 9:55 PM MDT](https://github.com/nvaccess/nvda/issues/8516#issuecomment-406146817 "2018-07-19T03:55:13Z - Replied by Github Reply Comments"):
> Hi,
> 
> One more thing: let me know if I sounded very harsh throughout this exchange.
> 
> Thanks.


A bit, yes.

**Comment by derekriemer** [comment]
[**@josephsl**](https://github.com/josephsl) commented on [Jul 18, 2018, 7:33 PM MDT](https://github.com/nvaccess/nvda/issues/8516#issuecomment-406126082 "2018-07-19T01:33:45Z - Replied by Github Reply Comments"):
> Hi,
> 
> 2018 GDPR...
> 
> Can you tell us one or two compelling justifications other than closing security and privacy hole as to why this should be done?

What compelling additional justiication is needed? Security/privacy is very important, and being blind is no exception to security/privacy. This request seems very reasonable for us to look into. I also don't think this would be hard at all. We have a logHandler.NullLogHandler for -s, we could simply add a config option.

**Comment by derekriemer** [comment]
The thing here is it shouldn't be hard for us to add a config option for no logging, and just initialize the null log handler, which throws away all logging requests immediately (It doesn't even write them to disk). Beyond that, it doesn't seem reasonable to do other things.

**Comment by Adriani90** [comment]
I agree with @derekriemer.

**Comment by DrSooom** [comment]
One more thing in the userGuide.html (chapter: 15.2. System Wide Parameters):
> serviceDebug | … | … | If enabled, disables secure mode on windows secure desktops, allowing the use of the Python console and Log viewer. Due to several major security implications, the use of this option is strongly discouraged

This description should be expand as well. At the moment it only says something about the Log Viewer, but not also about the logging itself. A clarification here would be appreciated.

**Comment by josephsl** [comment]
Hi, yep, an oversight. Thanks.

**Comment by derekriemer** [comment]
Please see #8579. I intend to get this documentation oversight fixed. I'm really sorry we confused you. An disable logging however would be nice to have. I'll keep this open in case anyone wants to make it an option.

**Comment by josephsl** [comment]
Hi,

For anyone wishing to work on this, I recommend setting log level to 0 (if that is even an option) and adding "off" option to logging level combo box. Also, at least log the fact that logging is turned off at startup.

Good luck. Thanks.

**Comment by josephsl** [comment]
Hi, the little known __debug__ flag is useful for detecting whether or not one is using a debug build. As for crash dumps, I’d say it should be done via Python Console when instructed to do so, so no need for a checkbox. Thanks.

**Comment by DrSooom** [comment]
@josephsl: In other words: Creating crash dumps should be disabled by default in all kinds of NVDA versions – which isn't the case yet. Correct?

**Comment by josephsl** [comment]
Hi, right now, if you wish to create a crash dump across NVDA release channels, you need to open Python Console from the app you know is prone to crashes, and call a function that captures crash dumps when NVDA actually crashes. The underlying assumption is that crash dumps are needed when users can verify that crashes occur often and with specific steps. Is this what you are after? Thanks.

**Comment by DrSooom** [comment]
As far as I recognized NVDA 2018.1 (installed version) creates a file called "nvda_crash.dmp" by default. this behaviour can't be disabled via the GUI.

As far as I understood you, your suggestion is to disable this behaviour, so the user firstly have to enable it via the Python console if he need one. This procedure would be fine to me.

**Comment by Adriani90** [comment]
I think disabling logging totally is still for improving security. Crash dumps are not created automatically when NVDA starts which is ok in my opinion.
 

Von meinem iPhone gesendet

**Comment by josephsl** [comment]
Hi, not all users may notice this file being created, as this is not created every time (something we need to look at another time). As for Python Console method, I’m glad we’re on the same page. Also, for whoever is working on this, don’t use log level of 0 (not set), as it’ll handle all sorts of log messages – I think it might be best to use log level of 100 (disabled). Thanks.

**Comment by DrSooom** [comment]
Quote from (this Wiki article)[https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps]:
> Crash Dumps
> This applies to NVDA 2014.1 and later. Earlier versions do not generate crash dumps.
> If NVDA crashes, it will generate a file called a minidump which will help developers to determine the cause of the crash. In addition, minidumps can also be generated on request for other applications which crash if NVDA is suspected as the cause of the crash.
> Minidumps for NVDA Itself
> When NVDA crashes, it will usually restart itself. In some rare circumstances, this may not work. If NVDA crashes, a minidump will be generated in a file called nvda_crash.dmp. For most users, this file can be found in the user temporary folder %temp%. For users running from source, nvda_crash.dmp will be placed in the source directory.

**Comment by josephsl** [comment]
Hi, a mini dump won’t contain all memory contents used by NVDA – it’ll contain current register values, stack traces and what not – barely minimal info useful for debugging only. To me, this is not really a security and privacy concern… unless a special command-line switch could be introduced to prevent crash dumps from being created, which will be in effet for the current session only. Thanks.

**Comment by derekriemer** [comment]
[**@DrSooom**](https://github.com/DrSooom) commented on [Jul 31, 2018, 10:31 PM MDT](https://github.com/nvaccess/nvda/issues/8516#issuecomment-409446050 "2018-08-01T04:31:59Z - Replied by Github Reply Comments"):
> @josephsl: In other words: Creating crash dumps should be disabled by default in all kinds of NVDA versions – which isn't the case yet. Correct?

We also have versionInfo.isTestVersion.

**Comment by derekriemer** [comment]
[**@DrSooom**](https://github.com/DrSooom) commented on [Jul 31, 2018, 10:47 PM MDT](https://github.com/nvaccess/nvda/issues/8516#issuecomment-409448105 "2018-08-01T04:47:28Z - Replied by Github Reply Comments"):
> As far as I recognized NVDA 2018.1 (installed version) creates a file called "nvda_crash.dmp" by default. This behaviour can't be disabled via the GUI.
> 
> As far as I understood you, your suggestion is to disable this behaviour, so the user firstly have to enable it via the Python console if he need one. This procedure would be fine to me.

Actually, that's only correct if NVDA crashes other applications. We create dumps for ourself by default. They're minidumps, so the amount of info is more minial. if you want NVDA to request other applications dump on crash, you have to ask NVDA to do this in that application.

**Comment by derekriemer** [comment]
[**@DrSooom**](https://github.com/DrSooom) commented on [Jul 31, 2018, 10:58 PM MDT](https://github.com/nvaccess/nvda/issues/8516#issuecomment-409449470 "2018-08-01T04:58:05Z - Replied by Github Reply Comments"):
> Quote from [this Wiki article](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps):
> > Crash Dumps
> > This applies to NVDA 2014.1 and later. Earlier versions do not generate crash dumps.
> > If NVDA crashes, it will generate a file called a minidump which will help developers to determine the cause of the crash. In addition, minidumps can also be generated on request for other applications which crash if NVDA is suspected as the cause of the crash.
> > Minidumps for NVDA Itself
> > When NVDA crashes, it will usually restart itself. In some rare circumstances, this may not work. If NVDA crashes, a minidump will be generated in a file called nvda_crash.dmp. For most users, this file can be found in the user temporary folder %temp%. For users running from source, nvda_crash.dmp will be placed in the source directory.

See the logHandler.py. There's a line "if globalVars.appArgs.secure" line, and you can add the no logging config stuff there.

**Comment by josephsl** [comment]
Hi, I’ll cook up something, along with researching ways to modernize the ancient log handler module (this is important, as Python 3 may introduce backwards incompatible changes to log handler). Thanks.

**Comment by josephsl** [comment]
Hi,

Turns out logging cannot be turned off all the way: when binary version of NVDA (installed or portable) starts, NVDA will log a sign-on message, along with where your settings can be found. This is because our logger will write log contents to the log file as soon as the log file is ready for writing.

One way to get around this is to have an in-memory "log" (buffer) ready to hold startup messages, and then dump it to the "actual" log file if log level other than "disabled" is chosen.

One major concern I have: should logging be enabled/disabled on the fly? That is, if logging level changes to "disabled", should previous log content be kept, and if changing from "disabled" to something else, should future log contents be prepared for writing? I'm thinking this change should require a restart to fully take effect. The major downside with this approach is loss of bug traces, especially if the bug does not happen when NVDA restarts.

Thanks.

**Comment by josephsl** [comment]
Hi,

Regarding modernizing log handler, I put in some note regarding log level name dictionary splits. For whoever's going to port this file to Python 3, be sure to read Python 3 documentation on logging module carefully, as so-called "_levelNames" map is gone in Python 3.

Thanks.
