### ISSUE TITLE
improving current access to QT applications

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#852]
**Reported by arfy on 2010-08-23 14:19**
Currently, NVDA can provide access to applications written using the Nokia (formally troltech) QT GUI toolkit. However, there are still problems that show up in it's use. Note this is based on a fairly cursary look at QT creator that comes with the QT sdk, 2010.04, GPL edition. However, even so, some fairly major blocks to full access were found.
1. when tabbing through dialogs, bits of html were presented as part of the control description. for example:

press tab. "Boarder. feedback button". press tab. Boarder, select an example... menu button submenu".

On further investigation with object nav, it appears that the "boarders" are actually unlabeled group boxes.

And, an example of html showing up.
To get this, open qt creator, and hit escape to clear the welcome/getting started screen. then shift-tab once. You'll here,
Status bar. Show Sidebar span style = color "grey" fontsize=small, alt-0."
1. The help system and any web content showing is based on webKit, so, it might be time to create yet another, virtual buffer backend, perhaps...
2. Text fields don't seem to be navigable with cursor keys.
   edit's are identified as edit, submenu, and combo boxes, while identified right, and the contents initially read, don't speak as you cursor up and down to change values.

I'm sure there's other things, but those wer the first three that came to mind for now.

**Comment by jcsteh** [comment]
Qt 5 has been out for some time now and it includes major accessibility improvements, including access to editable text fields via IAccessible2 and significant bug fixes. Also, NVDA now treats borders as layout. There are certainly still problems with Qt accessibility, but these should be filed as separate issues (and ideally against Qt itself).
