### ISSUE TITLE
Disable Welcome Dialog entry in the NVDA menu on the logon screen (secure desktop)

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#8520]
### Path (secure desktop):
NVDA menu » Help » Welcome Dialog...
Actual behaviour:
The above menu entry is shown on the Windows logon screen (secure desktop). I'm asking me why?
Expected behaviour:
This menu entry shouldn't be shown in secure desktop environmental because it makes no sense for me – as there isn't a way to save the current configuration through the NVDA menu as well.
#### NVDA version:
2015.3 to 2018.1 (higher versions aren't installed on my PCs yet.)
#### Windows version:
Windows 7, 64-Bit, SP1

**Comment by josephsl** [comment]
Hi, right, an oversight. @MichaelDCurran, can we remove this entry while NVDA is running in secure mode? Thanks.
