### ISSUE TITLE
Wrong version of comtypes specified in the readme.md

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#8522]
### Steps to reproduce:
1. Open readme.md in the main folder of this repo.
2. Find the line which says '* [comtypes](https://github.com/enthought/comtypes), version 1.1.4'
3. Open NVDA log and verify, that the actual version of comtypes is 1.1.3.
### Actual behavior:
The version numbers do not match.
### Expected behavior:
The version numbers should be the same.
#### NVDA Installed/portable/running from source:
n/a
#### NVDA version:
n/a
#### Windows version:
n/a
#### Name and version of other software in use when reproducing the issue:
n/a
#### Other information about your system:
n/a
#### Does the issue still occur after restarting your PC?
n/a
#### Have you tried any other versions of NVDA?
n/a

**Comment by leonardder** [comment]
This is a bit confusing indeed. The current version of comtypes we use is actually 1.1.4 minus a piece of code that introduced a bug while not adding any relevant functionality. So functionally, we are at version 1.1.4.

**Comment by lukaszgo1** [comment]
In such case it might be better to simply say comtypes and the specific commit. It has been done for example for IAccessible2
