### ISSUE TITLE
nvda ignores reading concatane aria-labelledby label in firefox & ie

### ISSUE THREAD

**Issue by sripalreddyadamala** [nvaccess/nvda#8525]
Hi all,
              I am try to concatanete id with aria-labelledby and nvda ignores reading concated label in both IE & firefox. In my code it ignores reading popover content id.
![image](https://user-images.githubusercontent.com/17653691/42959815-0512fa34-8b58-11e8-9ac6-456db4ebda5e.png)

**Comment by PratikP1** [comment]
Many of the developers and contributors of this project are blind. Could you please provide either a live code example or attach code that could be replicated? In addition, can you tell us which version of Firefox/IE you used. In fact, it would be quite useful for you to fill out the issue template made available expressly for that purpose.

**Comment by sripalreddyadamala** [comment]
I am using ngx bootstrap  1.8.1 with angular 4..0 in my app and I am trying to concatenate popover help text  id and label name id to input field nvda ignore reading one of the those id either in firefox or Ie browser.

[
[nvda test code.txt](https://github.com/nvaccess/nvda/files/2228266/nvda.test.code.txt)
](url)

**Comment by michaelDCurran** [comment]
This testcase is invalid.  Your input tag has an aria-labelledby containing the id "username" which is infact the id of the input tag itself.   
I'm thinking perhaps you meant to reference the "userInfo" id instead?
However, I would advise against placing a message like that in the label.  You would be better  using aria-describedby for the message instead.
Remove the aria-labelledby from the input field as it is not needed, as html itself will associate the label with the "for" attribute. and use aria-describedby to reference the userInfo ID.
