### ISSUE TITLE
Sometimes impossible to close elements list

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#8529]
### Steps to reproduce:
1. Open orange.fr
2. Open elements list with NVDA+F7.
3. close it.
4. Invoke the list second time and try to close it with cancel or escape.
### Actual behavior:
The list will not close and when opening it the following is written in the log
ERROR - unhandled exception (19:06:45.973):
Traceback (most recent call last):
  File "wx\core.pyc", line 3240, in <lambda>
  File "browseMode.pyc", line 426, in run
  File "browseMode.pyc", line 827, in __init__
  File "browseMode.pyc", line 885, in initElementType
  File "browseMode.pyc", line 905, in filter
  File "virtualBuffers\__init__.pyc", line 121, in label
  File "browseMode.pyc", line 219, in _getLabelForProperties
  File "virtualBuffers\__init__.pyc", line 118, in propertyGetter
  File "virtualBuffers\__init__.pyc", line 150, in _getControlFieldAttribs
LookupError

### Expected behavior:
The list should close.
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
alpha-16056,366fcf79

#### Windows version:
Windows 7 x64
#### Name and version of other software in use when reproducing the issue:
Nightly 64
#### Other information about your system:
This issue cannot be reproduced 100% of the time, but after several attempts it will definitely show up.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?

Yes the first version which has this issue is 2017.4

**Comment by leonardder** [comment]
This looks like a duplicate of #7853, at least it has the same underlying issue.

**Comment by leonardder** [comment]
Could you reproduce this with [this try build](https://ci.appveyor.com/api/buildjobs/pp6c5tedj2t0ytiw/artifacts/output%2Fnvda_snapshot_try-geckoPointFromOffset-15627%2Ca6fca0b6.exe)?

**Comment by lukaszgo1** [comment]
I'm unable to reproduce it with the test build provided by @leonardder but, because it cannot be reproduced reliably I cannot say, that it is definitely fixed. I'm going to close this issue for now, and will reopen if nessesary

**Comment by lukaszgo1** [comment]
Unfortunatelly it isn't fixed. I've edited my initial commend with STR which  fails for me 100
% of the time.

**Comment by josephsl** [comment]
Hi,

Does this happen with other browsers and on other websites? If this is specific to a website, chances are that it might be a bit hard to reproduce this. If this happens on other browsers, then we may need to do some more digging.

Thanks.

**Comment by lukaszgo1** [comment]
My testing shows that it happens in IE11, but not in Edge I am unable to test with Chrome sorry about that. It happens with other websites from time to time, I've used orange.fr as a example, because it fails there consistently.

**Comment by josephsl** [comment]
Hi, and this isn’t happening on 2018.1 and 2018.2? Thanks.

**Comment by ruifontes** [comment]
It seems a problem in Orange portal...

See the log writing orange.fr in the navegation bar of Firefox...

Input: kb(desktop):o
IO - speech._speakSpellingGen (18:49:54.697):
Speaking character u'o'
DEBUG - queueHandler.registerGeneratorObject (18:49:54.697):
Adding generator 2506
DEBUG - queueHandler.pumpAll (18:49:55.213):
generator 2506 finished
IO - speech.speak (18:49:55.275):
Speaking [u'lista']
IO - speech.speak (18:49:55.275):
Speaking [u'https://onlineradiobox.com https://onlineradiobox.com  1 de 10']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:49:55.290):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:49:55.312):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:49:55.377):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:49:55.381):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:49:55.391):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
IO - 
external:globalPlugins.NVDAExtensionGlobalPlugin.commandKeysSelectiveAnnouncement.MyInputManager.executeGesture 
(18:49:55.693):
Input: kb(desktop):r
IO - speech._speakSpellingGen (18:49:55.752):
Speaking character u'r'
DEBUG - queueHandler.registerGeneratorObject (18:49:55.752):
Adding generator 2507
IO - 
external:globalPlugins.NVDAExtensionGlobalPlugin.commandKeysSelectiveAnnouncement.MyInputManager.executeGesture 
(18:49:56.042):
Input: kb(desktop):a
DEBUGWARNING - watchdog._watcher (18:49:56.272):
Trying to recover from freeze, core stack:
   File "nvda.pyw", line 217, in <module>
   File "core.pyc", line 515, in main
   File "wx\core.pyc", line 2134, in MainLoop
   File "gui\__init__.pyc", line 963, in Notify
   File "core.pyc", line 485, in run
   File "IAccessibleHandler.pyc", line 900, in pumpAll
   File "IAccessibleHandler.pyc", line 657, in processFocusWinEvent
   File "IAccessibleHandler.pyc", line 532, in winEventToNVDAEvent
   File "NVDAObjects\IAccessible\__init__.pyc", line 38, in 
getNVDAObjectFromEvent
   File "IAccessibleHandler.pyc", line 342, in accessibleObjectFromEvent
   File "oleacc.pyc", line 265, in AccessibleObjectFromEvent

DEBUG - queueHandler.pumpAll (18:49:56.361):
generator 2507 finished
IO - speech._speakSpellingGen (18:49:56.371):
Speaking character u'a'
DEBUG - queueHandler.registerGeneratorObject (18:49:56.371):
Adding generator 2508
IO - 
external:globalPlugins.NVDAExtensionGlobalPlugin.commandKeysSelectiveAnnouncement.MyInputManager.executeGesture 
(18:49:56.522):
Input: kb(desktop):n
IO - 
external:globalPlugins.NVDAExtensionGlobalPlugin.commandKeysSelectiveAnnouncement.MyInputManager.executeGesture 
(18:49:56.742):
Input: kb(desktop):g
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:49:56.842):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUG - queueHandler.pumpAll (18:49:56.842):
generator 2508 finished
IO - speech._speakSpellingGen (18:49:56.842):
Speaking character u'n'
DEBUG - queueHandler.registerGeneratorObject (18:49:56.842):
Adding generator 2509
IO - speech._speakSpellingGen (18:49:56.851):
Speaking character u'g'
DEBUG - queueHandler.registerGeneratorObject (18:49:56.861):
Adding generator 2510
IO - 
external:globalPlugins.NVDAExtensionGlobalPlugin.commandKeysSelectiveAnnouncement.MyInputManager.executeGesture 
(18:49:57.052):
Input: kb(desktop):e
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:49:57.262):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:49:57.276):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUG - queueHandler.pumpAll (18:49:57.276):
generator 2509 finished
DEBUG - queueHandler.pumpAll (18:49:57.276):
generator 2510 finished
IO - speech._speakSpellingGen (18:49:57.289):
Speaking character u'e'
DEBUG - queueHandler.registerGeneratorObject (18:49:57.289):
Adding generator 2511
IO - 
external:globalPlugins.NVDAExtensionGlobalPlugin.commandKeysSelectiveAnnouncement.MyInputManager.executeGesture 
(18:49:57.384):
Input: kb(desktop):.
IO - 
external:globalPlugins.NVDAExtensionGlobalPlugin.commandKeysSelectiveAnnouncement.MyInputManager.executeGesture 
(18:49:57.661):
Input: kb(desktop):f
DEBUG - queueHandler.pumpAll (18:49:57.760):
generator 2511 finished
IO - speech.speakTypedCharacters (18:49:57.772):
typed word: range
IO - speech.speak (18:49:57.772):
Speaking [u'range']
IO - speech._speakSpellingGen (18:49:57.772):
Speaking character u'ponto'
DEBUG - queueHandler.registerGeneratorObject (18:49:57.772):
Adding generator 2512
IO - speech._speakSpellingGen (18:49:57.783):
Speaking character u'f'
DEBUG - queueHandler.registerGeneratorObject (18:49:57.783):
Adding generator 2513
IO - 
external:globalPlugins.NVDAExtensionGlobalPlugin.commandKeysSelectiveAnnouncement.MyInputManager.executeGesture 
(18:49:57.983):
Input: kb(desktop):r
DEBUG - queueHandler.pumpAll (18:49:58.232):
generator 2512 finished
DEBUG - queueHandler.pumpAll (18:49:58.232):
generator 2513 finished
IO - speech._speakSpellingGen (18:49:58.242):
Speaking character u'r'
DEBUG - queueHandler.registerGeneratorObject (18:49:58.242):
Adding generator 2514
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:49:58.401):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:49:58.411):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUG - queueHandler.pumpAll (18:49:58.651):
generator 2514 finished
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:49:58.681):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:49:58.832):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
IO - 
external:globalPlugins.NVDAExtensionGlobalPlugin.commandKeysSelectiveAnnouncement.MyInputManager.executeGesture 
(18:49:59.756):
Input: kb(desktop):NVDA+upArrow
IO - speech.speak (18:49:59.773):
Speaking [u'http://orange.fr/ orange.fr']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:49:59.867):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:00.197):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:00.596):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:00.796):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:01.375):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
IO - 
external:globalPlugins.NVDAExtensionGlobalPlugin.commandKeysSelectiveAnnouncement.MyInputManager.executeGesture 
(18:50:02.605):
Input: kb(desktop):enter
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:02.829):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2WindowHandle 
(18:50:03.147):
IAccessible2::windowHandle failed: (-2147220995, 'O objeto n\xe3o 
est\xe1 ligado ao servidor', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible.__init__ (18:50:03.177):
Resorting to WindowFromPoint on accLocation
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible.__init__ (18:50:03.177):
accLocation failed: (-2147220995, 'O objeto n\xe3o est\xe1 ligado ao 
servidor', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.__call__ (18:50:03.177):
Invalid NVDAObject: Can't get a window handle from IAccessible
Traceback (most recent call last):
   File "NVDAObjects\__init__.pyc", line 72, in __call__
   File "NVDAObjects\IAccessible\__init__.pyc", line 590, in __init__
InvalidNVDAObject: Can't get a window handle from IAccessible
DEBUG - treeInterceptorHandler.killTreeInterceptor (18:50:03.200):
Killed treeInterceptor: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 
0x05BFF8B0>
IO - speech.speak (18:50:03.246):
Speaking [u'edi\xe7\xe3o']
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getCaretOffset 
(18:50:03.299):
IAccessibleText::caretOffset failed
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\__init__.pyc", line 160, in _getCaretOffset
COMError: (-2147220995, 'O objeto n\xe3o est\xe1 ligado ao servidor', 
(None, None, None, 0, None))
ERROR - eventHandler.executeEvent (18:50:03.502):
error executing event: gainFocus on 
<baseObject.Dynamic_EditableTextExEditableTextWithAutoSelectDetectionEditorMozillaIAccessible 
object at 0x05C20570> with extra args of {}
Traceback (most recent call last):
   File "eventHandler.pyc", line 155, in executeEvent
   File "eventHandler.pyc", line 92, in __init__
   File "eventHandler.pyc", line 100, in next
   File 
"C:\Users\tiflo\AppData\Roaming\nvda\addons\wintenApps\globalPlugins\wintenObjs\__init__.py", 
line 259, in event_gainFocus
   File "eventHandler.pyc", line 100, in next
   File 
"C:\Users\tiflo\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", 
line 426, in event_gainFocus
   File "eventHandler.pyc", line 100, in next
   File 
"C:\Users\tiflo\AppData\Roaming\nvda\addons\NVDAExtensionGlobalPlugin\globalPlugins\NVDAExtensionGlobalPlugin\__init__.py", 
line 519, in event_gainFocus
   File "eventHandler.pyc", line 100, in next
   File "appModules\firefox.pyc", line 24, in event_stateChange
   File "eventHandler.pyc", line 100, in next
   File "NVDAObjects\behaviors.pyc", line 169, in event_gainFocus
   File "NVDAObjects\__init__.pyc", line 961, in event_gainFocus
   File "NVDAObjects\__init__.pyc", line 849, in reportFocus
   File "speech.pyc", line 400, in speakObject
   File "speech.pyc", line 756, in speakTextInfo
   File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 340, in 
getTextWithFields
   File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 289, in _getText
AttributeError: 'NoneType' object has no attribute 'obj'
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:03.582):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUG - treeInterceptorHandler.update (18:50:04.016):
Adding new treeInterceptor to runningTable: 
<virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x05C20850>
DEBUG - virtualBuffers.VirtualBuffer._loadBuffer (18:50:04.145):
Buffer load took 0.130 sec, 4573 chars
IO - speech.speak (18:50:04.618):
Speaking [u'Portail Orange : Actu, Sport, Assistance Internet, Web Mail 
Orange - Mozilla Firefox']
IO - speech.speak (18:50:05.250):
Speaking [u'Portail Orange : Actu, Sport, Assistance Internet, Web Mail 
Orange  ocupado']
DEBUG - queueHandler.registerGeneratorObject (18:50:05.250):
Adding generator 2515
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:05.279):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:05.279):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:05.289):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
IO - speech.speak (18:50:05.559):
Speaking [u'lista']
IO - speech.speak (18:50:05.559):
Speaking [u'edi\xe7\xe3o']
IO - speech.speak (18:50:05.730):
Speaking [u'em branco']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:05.829):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:05.859):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:05.869):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:06.140):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:06.819):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:07.289):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:07.341):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:07.733):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:07.838):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
IO - 
external:globalPlugins.NVDAExtensionGlobalPlugin.commandKeysSelectiveAnnouncement.MyInputManager.executeGesture 
(18:50:07.848):
Input: kb(desktop):escape
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (18:50:08.756):
COM pointer <POINTER(IAccessibleText) ptr=0x1ba0f54c at c478990> already 
deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (18:50:08.756):
COM pointer <POINTER(IAccessibleAction) ptr=0x1ba0f6fc at c478c10> 
already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (18:50:08.756):
COM pointer <POINTER(IAccessible2) ptr=0x1ba0f30c at c478bc0> already 
deleted
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:08.772):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:08.785):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(18:50:08.792):
accRole failed: (-2147024809, 'O par\xe2metro est\xe1 incorreto.', 
(None, None, None, 0, None))
IO - 
external:globalPlugins.NVDAExtensionGlobalPlugin.commandKeysSelectiveAnnouncement.MyInputManager.executeGesture 
(18:50:08.950):
Input: kb(desktop):NVDA+f7
ERROR - unhandled exception (18:50:09.099):
Traceback (most recent call last):
   File "wx\core.pyc", line 3240, in <lambda>
   File "browseMode.pyc", line 426, in run
   File "browseMode.pyc", line 827, in __init__
   File "browseMode.pyc", line 885, in initElementType
   File "browseMode.pyc", line 905, in filter
   File "virtualBuffers\__init__.pyc", line 121, in label
   File "browseMode.pyc", line 219, in _getLabelForProperties
   File "virtualBuffers\__init__.pyc", line 118, in propertyGetter
   File "virtualBuffers\__init__.pyc", line 150, in _getControlFieldAttribs
LookupError
IO - speech.speak (18:50:09.171):
Speaking [u'Lista de Elementos  Janela']
IO - speech.speak (18:50:09.174):
Speaking [u'vista em \xe1rvore']
IO - 
external:globalPlugins.NVDAExtensionGlobalPlugin.commandKeysSelectiveAnnouncement.MyInputManager.executeGesture 
(18:50:11.480):
Input: kb(desktop):downArrow
IO - speech.speak (18:50:11.509):
Speaking [u'modifier le param\xe9trage; visitado  1 de 6  n\xedvel 0']


Rui Fontes


Às 18:12 de 18/09/2018, Joseph Lee escreveu:

**Comment by lukaszgo1** [comment]
@josephsl The first version which has this problem is 2017.4.

**Comment by josephsl** [comment]
Hi, I see. CC @JCSTeh and @MichaelDCurran

**Comment by Adriani90** [comment]
This is consistently reproducible with this example in all browsers. I have tested with NVDA 2019.1.1, Firefox 66.0.4, Chrome 74 and IE11.
Sometimes you must press multiple times nvda+f7, escape, nvda+f7, escape, nvda+f7 etc...
cc: @feerrenrut, @michaelDCurran could this lead to a regression?

**Comment by lukaszgo1** [comment]
@Adriani90 Are you able to still reproduce this in latest Firefox? I'm not.

**Comment by lukaszgo1** [comment]
Since this is no longer reproducible for me I'm going to close this issue. If someone can still repro please comment here and I'll reopen.
