### ISSUE TITLE
Issue with latest ESpeak  and Serbian

### ISSUE THREAD

**Issue by nidza07** [nvaccess/nvda#8530]
In the latest NVDA alpha version, ESpeak incorrectly reads Serbian cyrillic characters.
### Steps to reproduce:
Make sure the selected  synthesizer is ESpeak.
Switch to Serbian from the voice settings dialog.
Read the following word, written with standard English alphabet.
test
now this same word, with Cyrillic alphabet.
тест

### Actual behavior:
The cyrillic word reads like, t e s t.

### Expected behavior:
Both entries should read the same. Note that this isn't just one word. Whatever is in cyrillic will read like each letter is spaced and not like one word.

#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
alpha-15620,6c04bfb6
#### Windows version:
Windows 10- 64 bit
#### Name and version of other software in use when reproducing the issue:
ESpeak NG version 1.49.3 dev
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
Versions before this ESpeak upbrade should work fine, but I did not personally test that as I started experiencing the issue just now.

**Comment by Mohamed00** [comment]
Hmm, I think this should actually be reported to ESpeak rather than here.

**Comment by nidza07** [comment]
I agree, but I could not find the right GitHub page and I thought that ESpeak developers follow this tracker too.

**Comment by Mohamed00** [comment]
I'm not sure if they do or not, though you should still raise an issue there.. The ESpeak NG GitHub is ([here(https://github.com/espeak-ng/espeak-ng))

**Comment by Mohamed00** [comment]
I'm not sure if they follow this tracker or not, though the ESpeak NG GitHub is at https://github.com/espeak-ng/espeak-ng.

**Comment by zstanecic** [comment]
Hi to all,
the same is with the croatian voice, which reads cyrillic script, too

**Comment by nidza07** [comment]
Will close this issue as it is filled on ESpeak NG Github.

**Comment by Brian1Gaff** [comment]
Is this the same issue as with Bulgarian etc? There is a ticket for that I 
think both on nvda and espeak.
 Looks like a backtrack on Espeak needed in the short term again to me.
 I have also noticed that even in English a few words are now not spoken 
right but it seems context sensitive, so hence hard to actually pin down.

Brian
