### ISSUE TITLE
UIA performance/WinDbg: slow response when pressing Alt+Tab after pressing Control+D from WinDbg

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8535]
Hi,

Reported by @TSpivey via Skype: UIA responds slowly when pressing Alt+Tab from WinDbg.

### Steps to reproduce:
1. Install Windows SDK.
2. Open WinDbg (any version will do).
3. With WinDbg open, press Control+D to open crash dumps.
4. Press Alt+Tab.

### Actual behavior:
Switching between apps is very slow.

### Expected behavior:
Switching between apps is snappy.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.2.1 and alpha.15634

#### Windows version:
Windows 10 versions 1803 and Insider Preview

#### Name and version of other software in use when reproducing the issue:
WinDbg

#### Other information about your system:
@TSpivey uses version 1803, while I use Insider Preview.

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

### Technical:
Possibly caused by WinDbg itself.

### Workarounds:
For Version 1803 (build 17134), remove UIA name and value properties from properties to event ID's dictionary in UIA handler. This resolves this, although it raises the question as to which window is causing performance issues when firing name change and/or value change events.

In Insider Preview, use IUIAutomation6::CoalesceEvents (RS5, the flag must be set to 1/enabled).

Thanks.

**Comment by Adriani90** [comment]
@josephsl is this issue still reproducible? There are to PRs merged related to this and I guess there were changes between Windows 10 1803 and las build in 1809.

**Comment by Adriani90** [comment]
@@tspivey are you still having this issue? Or should we close it?

**Comment by Adriani90** [comment]
No updates so far from the person who can reproduce it. I am closing this issue as abandoned. Please comment on it if you still have this issue and we can reopen it. Thanks.
