### ISSUE TITLE
Change keystroke for expanding combo boxes from alt+down arrow to alt+windows+down arrow

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8541]
Dear all,

as a result from discussions in #8518, lots of users prefer to read sentence by sentence rather than line by line or paragraph by paragraph. This is fully understandable, especially when People do not use a Braille Display but want to read aloud a Long text. So, @mltony created the addon SentenceNav which uses alt+down arrow to read sentence by sentence.
To assure that there are no longer key conflicts, I suggest moving the expand Combo box command from alt+down arrow to alt+windows+down arrow. 

Note that NVDA uses alt+down and up arrow to read sentence by sentence in MS Word, so keeping this key stroke for this add-on would be very appreciated.

Thank you.

**Comment by lukaszgo1** [comment]
alt+down arrow is a Windows Keystroke not a NVDA one. In my opinion screen reader shouldn't change a system keyboard commands and this issue should be closed and labeled as cantfix and wontfix.

**Comment by Adriani90** [comment]
@lukaszgo1, however, this key stroke is used by NVDA, also in ist core funcitonality of reading sentence by sentence in MS Word. If NV Access is labeling this as won't fix, then I could create a new issue to Change the read sentence by sentence keystroke from alt+down arrow to alt+windows+down arrow. But users are used to alt+down and up arrow. The only conflict I can Encounter is related to Combo boxes. Note that ctrl+alt+arrow keys are also Windows keys and not NVDA keys. But however, NVDA uses them for table Navigation though. So, Windows keystrokes have not highest priority here. Usability and productivity is the main Goal of this.

**Comment by leonardder** [comment]
lukaszgo1 perfectly stated my opinion here. Closing as won't fix.

**Comment by leonardder** [comment]
[**@Adriani90**](https://github.com/Adriani90) commented on [23 jul. 2018 11:23 CEST](https://github.com/nvaccess/nvda/issues/8541#issuecomment-406995353 "2018-07-23T09:23:39Z - Replied by Github Reply Comments"):
> ctrl+up and down arrow is also a Windows keystroke but is used by NVDA to read paragraph by paragraph.

I'm afraid your assumptions are incorrect. Control+up and down arrow and alt+up and down are Windows and Word keystrokes, respectively. Fundamentally, these ctrl+arrow key strokes move from paragraph to paragraph, and NVDA detects these keystrokes to read the paragraph that Windows moved to. Equivalently, Word moves sentence by sentence with alt+arrows, and NVDA only detects these keys to speak the current sentence accordingly.

**Comment by Brian1Gaff** [comment]
A  lot of this is down to the context at the time in my opinion. as long as 
you know when things need to be windows and when not you are OK.

Brian

**Comment by netblue44** [comment]
Also JAWS and Nerator it is a sistem wide keystroke

**Comment by mltony** [comment]
I believe this is not necessary; keystroke conflicts can be resolved another way. Currently SetnenceNav resolves this conflict the following way. When a user presses Alt+Down or Up, SentenceNav looks at the type of currently focused element. If it happens to be a combo box,, then it expands or collapses it. Otherwise it assumes that it is in text-like field, such as an edit-box and tries to jump to next/previous sentence. So in my opinion both of these actions (combo box expand and navigate by sentence) can be bound to the same shortcut without causing conflicts - if proper care is taken to address these situations.
