### ISSUE TITLE
Apply to delete outdated locale-zh Chinese translation directory

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#8543]
Hello, I found a useless zh Chinese translation directory in the NVDA installation directory, and the source code directory. There are several files in it: characterDescriptions.dic symbols.dic This directory has not been maintained by the translator. Can you ask? Clean up as an outdated directory
### Steps to reproduce:
tion directory, and the source code directory: Installation directory:C:\Program Files (x86)\NVDA\locale\zh
Source code directory:
C:\Users\dpy\source\repos\nvda\source\locale\zh
### Actual behavior:
Delete zh directory
#### NVDA Installed/portable/running from source:
NVDA install version
#### NVDA version:
NVDA-alpha-15641
#### Windows version:
windows10-1803
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
NO
thank

**Comment by josephsl** [comment]
Hi, I think this is something we need to ask on translations community as certain locales might actually rely on this. Thanks.

**Comment by dingpengyu** [comment]
Thanks for the tips, I understand, I will send a discussion post in the translation community.

**Comment by larry801** [comment]
The "zh" locale even is not in translation svn repo.
It is safe to delete them

**Comment by dingpengyu** [comment]
cc
@leonardder  
Can you help me? Apply to delete outdated locale-zh Chinese translation directory this PR

**Comment by Adriani90** [comment]
There are many locale folders which are outdated and are not on the translations system (see i.e. AF, AF_ZA, AS, BN, ID, KOK, MNI) and many more. In my view it is good that they are included in NVDA's installations folder. if anytime in the future someone applies for translation of these languages, we can integrate them very easily in the translation system and we don't need to raise pull requests again to be included in NVDA. I am closing this. Please comment if you don't agree and we can reopen the discussion.

**Comment by larry801** [comment]
zh is now replaced by  more accurate locale zh_CN zh_TW and zh_HK, it is different from AF, AF_ZA, AS, BN, ID, KOK, MNI, "zh"  will never come back.
@Adriani90

**Comment by Adriani90** [comment]
Reopened, sorry for my missunderstanding.

**Comment by dingpengyu** [comment]
hi Adriani
Can you help me with this issue?
thank
cc
@Adriani90

**Comment by man0528** [comment]
Yes, zh will not have any value in existence.

**Comment by leonardder** [comment]
Note that for character descriptions and symbols that are not in zh_CN, zh_HK or zh_TW, NVDA will automatically fall back to possible descriptions/replacements in zh. It looks like zh/characterDescriptions.dic looks very similar to zh_HK/characterDescriptions.dic. zh_HK/characterDescriptions.dic mentions that it is for Taiwan, while I'd expect that it is meant for hongkong.
I'm not convinced that removing the zh locale directory has any benefits that justify a high priority.

**Comment by larry801** [comment]
A quick look on why zh files exist shows that it is copied from an old zh_TW translation to make espeak Mandarin work properly. But the content of zh is outdated and has parsing errors.

WARNING - characterProcessing.SpeechSymbols.load (23:24:32.983):
Invalid line in file locale\zh\symbols.dic: ﹩    錢號all   

May be make a copy on every L10N update or at installation time is a better solution than storing them in repo directly.

But that should be in another issue. This one is safe to close for now.

**Comment by larry801** [comment]
Here is the original commit which introduces zh folder.
https://github.com/nvaccess/nvda/commit/d6fe1f5c42ac5096caf86a24725934b10dc30c2a

**Comment by Adriani90** [comment]
@larry801 could you please create an issue with your proposal above? That would be great. Maybe discussions can be continued on that issue.
I am closing this one for now.
