### ISSUE TITLE
enable whatsapp microsoft store app support

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8556]
### Steps to reproduce:
download it in microsoft whatsapp store.
Log in to your whatsapp account by scanning your phone with the qr code
Now try navigating whatsapp with arrows and enter.
### Actual behavior:
nvda announces only section, and a text box searches for new conversations.
### Expected behavior:
the nvda should read with titles or tabs the titles of the conversations, the last messages received.
It should also allow you to run the audios, read incoming text messages.
Many buttons in whatsapp are not labeled.
But using other screen readers you can play the audios, read the text messages, send text messages and with a little gymnastics you can even send audio messages as well as forward.
I also noticed that it is not possible to control browse mode in the app.
In the other screen reader, the equivalent of the browse mode is fired.
#### NVDA Installed/portable/running from source:
instaled

#### NVDA version:
alfa 15620
#### Windows version:
windows 10 17134.165
#### Name and version of other software in use when reproducing the issue:
whatsapp
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by fernando-jose-silva** [comment]
I downloaded whatsapp from microsoft store direct. I'll try to figure out how to get the app link from within the microsoft store software.

Enviado do meu iPhone

Em 25 de jul de 2018, à(s) 11:28, Joseph Lee <notifications@github.com> escreveu:

> Hi, which app would you like us to test – Whatsapp Desktop, client for Whatsapp, and what not? Also, can you share the direct link for this app on Microsoft Store please? Thanks.

**Comment by fernando-jose-silva** [comment]
It is
https://www.microsoft.com/pt-br/p/whatsapp-desktop/9nksqgp7f2nh


Enviado do meu iPhone

Em 25 de jul de 2018, à(s) 12:04, fernandoj.silva21@gmail.com escreveu:

> I downloaded whatsapp from microsoft store direct. I'll try to figure out how to get the app link from within the microsoft store software.
> 
> Enviado do meu iPhone
> 
> Em 25 de jul de 2018, à(s) 11:28, Joseph Lee <notifications@github.com> escreveu:
> 
>> Hi, which app would you like us to test – Whatsapp Desktop, client for Whatsapp, and what not? Also, can you share the direct link for this app on Microsoft Store please? Thanks.

**Comment by Brian1Gaff** [comment]
NOt that I'm affected, but it would certainly help if Microsoft would check 
accessability without messing about a lot before they allowed such apps on 
their store!

Brian

**Comment by Adriani90** [comment]
Browse mode is now supported with NVDA, chants can be accessed as well as audio messages. It is true that some buttons are not labeled, but this needs to be reported to whatsapp developers.
You can also navigate the messages in focus mode and pressing the context menu key on a message will open its context menu including all the options like archiving, forwarding etc.
For other issues, please contact the developers of the app.
Closing as invalid.
