### ISSUE TITLE
Add a command line parameter to disable start at logon screen for silent installations

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#8574]
### Steps to reproduce:
1. Install NVDA with the --install-silent flag
2. Restart the system.

### Actual behavior:
NVDA runs at the logon screen.

### Expected behavior:
NVDA shouldn't run at the logon screen when explicitly chosen to install silent.

### Additional details
This issue is relevant for system administrators who want to install NVDA silently on a multi user system. IN the current situation, it is not possible to specify the start at logon behaviour from the command line. I think it makes sense to make False the default for first time silent installations. Alternatively, we could consider introducing a new command line parameter.

cc @michaeldcurran, @feerrenrut, @derekriemer

### System configuration:
Not applicable. This issue is unrelated to the Windows version of use and I believe it has been there since the  --install-silent parameter was introduced.

**Comment by michaelDCurran** [comment]
I would prefer a separate commandline argument. I don't think it is 
logical to assume that all silent installations do not require NVDA on 
logon.

**Comment by feerrenrut** [comment]
@michaelDCurran & @leonardder I would expect that the majority or silent installs do not require NVDA on log on, but not all. However, I'm concerned that changing the behaviour here could break some install processes somewhere. So I would advise on keeping the current default, and adding a new option to `--disable-start-at-logon`. If everyone agrees, then perhaps we can change the title / description of this issue?

**Comment by leonardder** [comment]
@feerrenrut: Sound sreasonable. I will follow these implementation guidelines.

Note that the default will enable NVDA at logon, unless this is not a first installation and NVDA has been disabled at the logon screen. However, when this config parameter is provided, I tend to force disable NVDA at logon, so ignoring the current state of the setting.
