### ISSUE TITLE
Rules not read when navigating "Rules and Alerts" dialog in Outlook 2016

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#8597]
1. In Outlook, open the Rules and Alerts window: ALT+H, R, R, L
2. Tab to the list of rules (is there a hotkey for that?)
3. Arrow through the list.

Expected behaviour, the screen reader should read the name of each rule (and whether it is active, and actions etc) as the focus moves.
Actual behaviour, nothing is read.

Press NVDA+up arrow (NVDA+L in Laptop layout) to read the current line, and it reads the first rule, no matter what rule actually currently has focus.  It DOES read the correct information about the active state and actions (for the first rule).

If I alt+tab out of the window and back, and then read the current line, it reads the rule that has focus (If I use the arrow keys to select a different rule and then read the current line, NVDA still reports the rule that was focussed when I alt+tabbed.

This is using the current version of Outlook 2016 / 365: 1807 build 10325.20082 Click to run, on the latest Windows fast insider 1803, build 17730.1000 and NVDA Version: alpha-15781,d58e1cd4

The behaviour is the same when using NVDA 2018.2.1.

Narrator also can't read the individual rules in the dialog, which leads me to believe it's likely an Outlook issue?

**Comment by Brian1Gaff** [comment]
As we have seen in other situations when alt tab and coming back it seems 
windows is not telling access software if things have been changed.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Qchristensen** [comment]
Just testing this issue in the current version of Office 365 (16.0.11001.20093) - This now works (tested with NVDA 2018.4beta 2 and also with 2018.2.1 since that was what I reported the error with).

While this is presumably a change Microsoft have made in Office 365, can anyone please confirm whether this is still an issue in the latest version of Office 2016 (or any other Office version) or whether this issue can be closed?

**Comment by ehollig** [comment]
This now correctly works for me in Outlook 2016. Closing as worksforme
