### ISSUE TITLE
Word with UIA enabled: Spelling error announced at start of line.

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#8609]
Initial report by @bramd

### Steps to reproduce:
1. Open Word with UIA enabled.
2. Type the following line: `This is a spellling error.`
3. Press enter.
4. Press up arrow.

### Actual behavior:
NVDA says: `[spelling error] This is a spellling error.`

### Expected behavior:
NVDA says: `This is a [spelling error] spellling error.`

#### NVDA version:
alpha-15781

#### Windows version:
1803 (17134.191)

#### Name and version of other software in use when reproducing the issue:
MS Word 16.0.10325.20082

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by michaelDCurran** [comment]
Oopps. I broke this in the recent braille fixes.

getTextWithFields_text is overridden twice in WordDocumentTextInfo.

I'll address this in a new PR.
