### ISSUE TITLE
Developer guide: document resumeSayAllMode keyword in script decorator

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#8616]
### Steps to reproduce:
N/A
### Actual behavior:
N/A
### Expected behavior:
N/A
### System configuration:
N/A
#### NVDA Installed/portable/running from source:
N/A
#### NVDA version:
alpha-15781,d58e1cd4
#### Windows version:
N/A
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
Using the keyword in an add-on.
#### Does the issue still occur after restarting your PC?
N/A
#### Have you tried any other versions of NVDA?
N/A

**Comment by leonardder** [comment]
I'm not sure about this one. resumeSayAllMode is a keyword that is now quite specific to core, related to the allow skim reading in say all option. I don't think that it is very important to have it documented, it might cause more confusion than it solves.

**Comment by nvdaes** [comment]
Maybe. In this case, please feel free to close the issue.
It's used in placeMarkers add-on and I was confused since this isn't in the guide, but I have seen that it's available and can be used.
Thanks

**Comment by leonardder** [comment]
Actually, I think it is really possible to follow the issue template here, like this

[**@nvdaes**](https://github.com/nvdaes) commented on [10 Aug 2018, 19:24 CEST](https://github.com/nvaccess/nvda/issues/8616#issue-349596146 "2018-08-10T17:24:57Z - Replied by Github Reply Comments"):
> ### Steps to reproduce:
> 1. Open the develper guide
> 2. Read the documentation about the script decorator.
> 
> ### Actual behavior:
> The resumeSayAllMode keyword isn't listed.

> ### Expected behavior:
> resumeSayAllMode should be listed. *Why do you think it should*?

> ### System configuration:
> N/A
> #### NVDA Installed/portable/running from source:
> N/A
> #### NVDA version:
> alpha-15781,d58e1cd4
> #### Windows version:
> N/A
> #### Name and version of other software in use when reproducing the issue:
> N/A
> #### Other information about your system:
> Using the keyword in an add-on. 

What add-on, and how are you using it?

> ### Other questions:
> 
> #### Does the issue still occur after restarting your PC?
> N/A
> #### Have you tried any other versions of NVDA?
> Yes, it does not apply to NVDA 2018.2.1 as that version doesn't have the script decorator.

**Comment by leonardder** [comment]
[**@nvdaes**](https://github.com/nvdaes) commented on [10 Aug 2018, 19:38 CEST](https://github.com/nvaccess/nvda/issues/8616#issuecomment-412153901 "2018-08-10T17:38:55Z - Replied by Github Reply Comments"):
> Maybe. In this case, please feel free to close the issue.
> It's used in placeMarkers add-on and I was confused since this isn't in the guide, but I have seen that it's available and can be used.

I can see why it makes sense to add this to the place markers add-on. I will label this as an issue with priority 4 though.

**Comment by nvdaes** [comment]
OK, I didn't use the template like that thinking that in a feature request can be easier to read it with less questions answered.
About the add-on, it's used like that:

>resumeSayAllMode=sayAllHandler.CURSOR_CARET,
		gesture="kb:NVDA+k"

And the same with gesture NVDA+shift+k

This add-on is on the community website, but the current version doesn't use script decorator. It's for the next version.
The repo is at
https://github.com/nvdaes/placeMarkers

Branch: 11.0-dev (PR #11).
This is used so that NVDA doesn't report the position of the next or previous bookmark while performing say all command with skim reading. In this case, just the text between the bookmark and the end of the current line is spoken.

Thanks

**Comment by CyrilleB79** [comment]
I have found this issue by chance while searching any issue corresponding to #11563. So I am providing a PR to close it.

I also just want to insist again that resumeSayAllMode keyword is used from time to time in add-ons. I have used it once in a pull-request integrated in Tony's Sentence Nav add-on.
