### ISSUE TITLE
Sluggishness with Visual Studio 2017

### ISSUE THREAD

**Issue by SaqibS** [nvaccess/nvda#8624]
### Steps to reproduce:

NVDA is very sluggish in several scenarios in Visual Studio 2017, below are 2 examples:

#### Intellisence

* In a blank console application, I start typing "Conso", and wait. After 1 or 2 seconds, NVDA announces "Console".
* I press ".wr", and wait quite some time before NVDA says "WriteLine".
* When using Narrator, feedback was very quick.

#### New File Getting Focus

* Start with all files closed.
* Press ctrl+shift+F, to open "Find in files", and type "main", and press enter.
* A multi line text field will get focus, and you cursor up/down to read the (probably only one) line which contains this text. However, initially NVDA will still say "main", as I cursor up/down, as I believe it is still read the contents of the text box in which I typed (even though it isn't visible on the screen any more). After a few seconds, it will start reading the search results as you cursor up/down.
* Now, press enter on a search result and start pressing up/down - again, NVDA keeps reading the search results even after the code file is open. Eventually it catches up.
* Also try putting the cursor on a keyword, like WriteLine, and press F12 to go to definition. A new source file will open with the definition, but again, if you cursor up/down you'll keep hearing the original file, for some seconds, until the system catches up.

I used the example of pressing cursor up/down, but the same thing happens if you press capslock+L to read current line - it keeps reading the old line for some seconds.

Narrator is very sluggish during these operations, so it is hard to make an equal comparison, but I do not believe it suffers from the same problem.

### Actual behavior:

As above, NVDA very sluggish.

### Expected behavior:

Instantaneous feedback.

#### NVDA Installed/portable/running from source:

Installed.

#### NVDA version:

2017.4

#### Windows version:

Windows 10

#### Name and version of other software in use when reproducing the issue:

Visual Studio 2017, version 15.7

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA?

Yes

**Comment by Adriani90** [comment]
@francipvb now that your pr #9441 is merged. do you think this issue can be closed? Could you try to see if it works well for you?

**Comment by francipvb** [comment]
Hello,

>     * In a blank console application, I start typing "Conso", and wait. After 1 or 2 seconds, NVDA announces "Console".
>     * I press ".wr", and wait quite some time before NVDA says "WriteLine".
>     * When using Narrator, feedback was very quick.

Still the same.

>     * Start with all files closed.
>     * Press ctrl+shift+F, to open "Find in files", and type "main", and press enter.
>     * A multi line text field will get focus, and you cursor up/down to read the (probably only one) line which contains this text. However, initially NVDA will still say "main", as I cursor up/down, as I believe it is still read the contents of the text box in which I typed (even though it isn't visible on the screen any more). After a few seconds, it will start reading the search results as you cursor up/down.
> 
>     * Now, press enter on a search result and start pressing up/down - again, NVDA keeps reading the search results even after the code file is open. Eventually it catches up.
>     * Also try putting the cursor on a keyword, like WriteLine, and press F12 to go to definition. A new source file will open with the definition, but again, if you cursor up/down you'll keep hearing the original file, for some seconds, until the system catches up.

For me it doesn't happen.

Well, the IntelliSense problem is a bit tricky NVDA reads the selected item from a LiveTextBlock widget and I don't know how NVDA processes it.

Yep, Narrator works very well with all these things, but it is a native UIA client with all their advantages, such speed and well known API.

I'm thinking how to solve this IntelliSense problem also for Visual Studio 2019.

Cheers,

**Comment by leonardder** [comment]
This should greatly improve by enabling "Enable selective registration for UI Automation events and property changes" in NVDA"s advanced settings.

**Comment by leonardder** [comment]
@SaqibS Could you elaborate on whether enabling selective UIA event registration fixes things for you?

**Comment by ivnc** [comment]
A similar issue with the Intellisense menu was reported to us by an Spanish-speaking user using VisualStudio 2019 Community. Could it be related to this?
Selective registration doesn't seem to fix the problem.

Regards.

**Comment by Adriani90** [comment]
Is this still an issue with Visual studio 2017 or newer?

**Comment by Adriani90** [comment]
We didn't hear any updates from the initial author or anyone within this conversation upon request since many years. I am closing as abandoned. Please comment if you are having this issue and we can reopen.
