### ISSUE TITLE
Checkable list checkmarks have scaling issues.

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#8635]
This was initially raised in [comments on #7491](https://github.com/nvaccess/nvda/pull/7491#issuecomment-412765761). This issue has been [reported against wxPython project](https://github.com/wxWidgets/Phoenix/issues/963), however we should investigate the cause or other work arounds.

### Steps to reproduce:
1. Set your display scaling to 125% or more
1. Open the NVDA keyboard settings (`NVDA + Ctrl + k`)

### Actual behavior:
The check marks next to the items in the "Select NVDA Modifier Keys" list have scaling artifacts.
![image](https://user-images.githubusercontent.com/3491346/44136799-4d9ccb4e-a0ad-11e8-9e6f-9d31cf6f1eaf.png)

### Expected behavior:
The check marks should be made of smooth lines.
![image](https://user-images.githubusercontent.com/3491346/44136826-6aa5a2f6-a0ad-11e8-8ebc-377816cc0f64.png)

### System configuration:
Scaling mode set to 125%

#### Name and version of other software in use when reproducing the issue:
None

**Comment by leonardder** [comment]
[**@feerrenrut**](https://github.com/feerrenrut) commented on [15 aug. 2018 10:22 CEST](https://github.com/nvaccess/nvda/issues/8635#issuecomment-413128311 "2018-08-15T08:22:09Z - Replied by Github Reply Comments"):
> I have assigned this a P2. While it does not affect the functionality, it doesn't look very good which may affect judgements of the quality of the project.

I agree. Since it also affects the overall look of the keyboard settings in a negative way, I also assigned this regression.

**Comment by feerrenrut** [comment]
Considering `CheckListCtrlMixin` shows acceptable tick marks, we should change the implementation to use that, and see if we can get the flags right so that it has a similar appearance (no heading / columns) to `CheckListBox`.

We will need some focused testing on the accessibility of this approach.

**Comment by feerrenrut** [comment]
Replacing `CustomCheckListBox` with `AutoWidthColumnCheckListCtrl` in keyboard settings should also fix: https://github.com/nvaccess/nvda/issues/8916

A similar problem to 8916 was noticed while working on the addon versioning.

**Comment by seanbudd** [comment]
This appears to not be an issue on Windows 11, the UI for this is different.

![image](https://user-images.githubusercontent.com/7090342/185025060-ded3caf0-1a55-423a-b618-139e8b923bd8.png)

@feerrenrut or someone else with Windows 10, can you please test that [this PR build](https://ci.appveyor.com/api/buildjobs/5tjllgpyfw050riq/artifacts/output%2Fnvda_snapshot_pr13254-26184%2Cbb136664.exe) from #13254 fixes the issue?

**Comment by feerrenrut** [comment]
I'm going to close this issue. I can no longer reproduce it, tested with `alpha-26009`
