### ISSUE TITLE
NVDA randomly goes silent, braille still works, active window unknown

### ISSUE THREAD

**Issue by mehgcap** [nvaccess/nvda#8638]
First, note that this problem may well be on just my machine. I'm having other problems which affect NVDA as well as Narrator. Still, in case it helps, here it is.

Recently, I've noticed that NVDA will go silent at random times. It may be random, it may be if I leave it alone for a set time, it may be something else. Whatever it is, braille works perfectly, but I lose all speech. Restarting NVDA puts things right, for a while. When this happens, the active window is suddenly "unknown".

Below is the log taken seconds after this happened most recently. The last thing in the log above this was from almost an hour before, and had to do with caret movement in a Sentilla window. I doubt it's related. NVDA was focused on Chrome, when my braille display changed to show Chrome was now an unknown window. Anyway, the log:

Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.IAccessible object at 0x0543F050>
Python class mro: (<class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: None
value: None
appModule: <'appModuleHandler' (appName u'chrome', process ID 35080) at address 4ca1cf0>
appModule.productName: exception: No version information
appModule.productVersion: exception: No version information
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 10225446
windowClassName: u'Chrome_RenderWidgetHostHWND'
windowControlID: 163609328
windowStyle: 1445986304
windowThreadID: 35336
windowText: u'Chrome Legacy Window'
displayText: exception: 'NoneType' object is not iterable
IAccessibleObject: <POINTER(IAccessible) ptr=0x4e95adb8 at 5148b70>
IAccessibleChildID: -1554937
IAccessible event parameters: windowHandle=10225446, objectID=-4, childID=-1554937
IAccessible accName: exception: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IAccessible accRole: exception: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IAccessible accState: exception: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IAccessible accDescription: exception: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IAccessible accValue: exception: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))

I recently installed the audio themes and braille extender add-ons, if that matters. I have not yet disabled both to see if that helps, as this problem is intermittent already and thus takes a while to test. However, I do have the audio themes add-on off, and did when this most recent incident occurred.

**Comment by Brian1Gaff** [comment]
Is it in any context, ie not just Chrome?
 It almost looks like the sort of behaviour you get with some malware 
screensaver graphics programs, where a screen with graphics can pop up and 
show ads.

It certainly does not seem to communicate with anything and getting to 
minimise it is often impossible without a mouse.

Just a thought.

Brian

**Comment by mehgcap** [comment]
I just ran a scan and found no malware. Plus, where braille continues to work as expected, I doubt it's a program taking over. I've only noticed it in Chrome thus far, but that's mostly because if my computer is left alone, it will be left with Crhome in focus more often than any other program. This is a work machine, so I'm limited in the time I can leave the computer alone, but I'll try a different program during lunch today and see what happens.

**Comment by DrSooom** [comment]
1. Did you try to change the synthesizer directly after NVDA stopped the speech output?
2. Which graphic card driver is installed? (There could be an issue with its update prompt window.)
3. Is skype installed/running? If so, please tell us the installed version.
4. Does this issue occur after closing an JAVA-based application? (there is an issue in combination with Java applications and the Audio Themes add-on. Restarting NVDA helps here.)
5. Is Java JRE 8.0 Update 181 (32-Bit) installed on your system?

btw: Please tell us more information about your system. Use the issue draft for more details how to do so. Thanks.

**Comment by mehgcap** [comment]
1. No, I didn't try to change the speech. I use Espeak, which I assume to be the most stable as it's not an add-on nor does it come from Windows like 1 Core. I'll give that a shot next time.
2. Due to a (possibly related) problem, I'm unable to use any core Windows dialogs, like settings or control panel. I can't review my card details to provide the model or driver information. However, this is integrated graphics, so I doubt there would be separate drivers for it alone. I've used this computer for about 2.5 years and never once gotten a prompt to install drivers for my graphics card.
3. No, Skype is not installed at all. If it is, it's definitely not running.
4. No, I'm not suing any Java apps I'm aware of.
5. I don't believe so. Due to the same problem mentioned in #2, I can't check my installed programs list. My Java folder shows a JRE1.8, along with the JDK for the same version. I don't recall how the numbers correspond, but I don't think that's 8. Even if it is, I'm not using it. I needed Java to run some test software last year, but haven't used it since.

**Comment by mehgcap** [comment]
Here's the system information. Apologies for not completing this initially.

### Steps to reproduce:

1. Open Chrome.
2. Leave the computer alone, with NVDA active. Attach a braille display to be able to continue to use NVDA once the problem occurs.

### Actual behavior:
NVDA remains silent despite, according to braille, working properly. This will take some time to start. The current window also shows as "legacy unknown", but returns to normal if you alt-tab away from, then back to, Chrome.

### Expected behavior:
NVDA should run normally, not do what it does here.

### System configuration:

#### NVDA Installed/portable/running from source:
standard install

#### NVDA version:
2018.2.1

#### Windows version:
Windows 10, 1803

#### Name and version of other software in use when reproducing the issue:
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

#### Other information about your system:
Dell PC with spinning drive, used at work. Using Orbit Reader 20 via USB.

### Other questions:

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA?
no

**Comment by DrSooom** [comment]
Could you remember when this strange scenario occurred the very first time? What happened immediately before this?

To be honest, I have absolutely no idea what's going wrong on your system. You still can create a new user account and run NVDA as a portable version in it (just for testing).

But as NVDA 2018.3 will be released shortly, I recoomend you to wait for it because of #8405. Please follow the NVDA blog to get informed when 2018.3 RC1 was released for testing.

**Comment by mehgcap** [comment]
I can test on another account, but I can't spare the time to do so at will. I'll try to remember to do that next time my machine will be alone for a while while still logged in.

The first time was August 13 or 14, I don't know which. I was doing nothing. I logged in after my computer had been locked, and found I had no speech, but I did have braille. Then the same thing happened after a period of inactivity, no log off or locking necessary. It's been that way ever since, happening randomly during inactivity and/or when I unlock it.

I have no clue either. I'll await 2018.3, and see if clearing up the other problems on my system fixes this one. That may well be the answer, with this bug being a consequence of some larger problem and not an independent issue.

**Comment by larry801** [comment]
Integrated Graphics Card also need drivers to run.Windows 8 and above may
update them silently during Windows Update.

**Comment by Neurrone** [comment]
I'm experiencing something similar for Visual Studio Code, which uses Electron. I'm not sure sure if its related. See https://github.com/Microsoft/vscode/issues/28316

**Comment by DrSooom** [comment]
[NVDA 2018.3 Beta 3](https://ci.appveyor.com/api/buildjobs/5d3wu75v704jdnar/artifacts/output/nvda_2018.3beta3.exe) was released yesterday. I wouldn't install it, but you can create a portable version from it. Use it on your own risk. It isn't a RC.

btw: If you don't need Java JRE anymore, please uninstall it for security reasons. The latest version is [8.0 Update 181](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html).

**Comment by mehgcap** [comment]
Quick update: the same problem just happened while Notepad Plus Plus was the active window, not Chrome. I don't expect this to help at all, but wanted to document it here just in case.

**Comment by DrSooom** [comment]
Does this issue also occur when the Audio Theme add-on is disabled/uninstalled?

**Comment by Adriani90** [comment]
@mehgcap, @Neurrone are you still having this issue? I am asking because I had it too months ago but it went away after some Windows updates came. Did you try to see if the com registry fixing tool in nvda menu / tools solves the problem? In case not, maybe it is a sound card issue. Try to install the bluetooth audio add-on from the official website and see if the speech still interrupts. The add-on is called bluetooth audio but it helps in cases where the sound card goes silent, especially when you live your PC inactive for more seconds / minutes.

**Comment by Adriani90** [comment]
And update to last Windows 10 build. This is always good because it seems that some issues were solved just by updating Windows 10.

**Comment by Adriani90** [comment]
@mehgcap, @Neurrone just a reminder, are you still having this issue in NVDA 2019.1.1 and Windows 10 last update using Chrome 73?

**Comment by Neurrone** [comment]
I get this infrequently still in 1809, but I haven't made any progress narrowing down what's causing it.

**Comment by mehgcap** [comment]
I've gotten similar behavior, where the window is unknown, then I lose speech and braille after a period of sluggishness from NVDA. Restarting Firefox or Notepad Plus Plus always sorts it out. I'm not sure if this is an evolution of the initial problem or a new one.

I just noticed the comment about the COM fixing tool, and ran it. I'll see if it makes a difference. I should also say that I'm now back to using Firefox over Chrome. My Windows and NVDA versions are both fully up-to-date.

**Comment by Adriani90** [comment]
@mehgcap did the com registry fixing tool solve your problem? How is the behavior in NVDA 2019.3 Beta 1?

**Comment by Adriani90** [comment]
@Neurrone, @mehgcap are you still having this issue with NVDA 2023.1 RC1 on last Windows 10 builds or Windows 11 builds?

**Comment by Neurrone** [comment]
I'm not experiencing this anymore, the VS Code issue I referenced above has been fixed.

**Comment by Adriani90** [comment]
Thanks for the update. Closing as works for me.
