### ISSUE TITLE
The nvda read emugis only after restarting the screen reader

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8639]
### Steps to reproduce:
Open the word.
Press Start +. (dot) to open the emugis panel.
Walk with the right arrows to read the names of the faces and press enter on at least 4 faces to uncertain it in the word document.
Now press esc to return to the document.
Press arrows down and down to read the inserted emugis.
Also press right and left arrows to read the emugis one by one.
### Actual behavior:
the nvda read the numbers 12 for each uncertain face.
### Expected behavior:
The nvda should read the uncertain faces.
If you restart the nvda it will normally read the emugis.
I'm using espeak with the plugins deactivated, just as I did not change the normal behavior of nvda as uia in word.
#### NVDA Installed/portable/running from source:
instaled
#### NVDA version:
alfa 15781
#### Windows version:
10 17134.228
#### Name and version of other software in use when reproducing the issue:
word 16.0.10325.20082
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by fernando-jose-silva** [comment]
Log:
IO - inputCore.InputManager.executeGesture (22:11:34.532):
Input: kb(laptop):escape
IO - inputCore.InputManager.executeGesture (22:11:38.700):
Input: kb(laptop):upArrow
DEBUG - editableText.EditableText._hasCaretMoved (22:11:38.819):
Caret didn't move before timeout. Elapsed: 100 ms
IO - speech.speak (22:11:38.819):
Speaking [u'em branco']
IO - inputCore.InputManager.executeGesture (22:11:41.441):
Input: kb(laptop):downArrow
DEBUG - editableText.EditableText._hasCaretMoved (22:11:41.565):
Caret didn't move before timeout. Elapsed: 100 ms
IO - speech.speak (22:11:41.565):
Speaking [u'em branco']
IO - inputCore.InputManager.executeGesture (22:11:43.381):
Input: kb(laptop):control+end
IO - speech.speak (22:11:43.424):
Speaking [u'cursor Desconhecido']
DEBUG - editableText.EditableText._hasCaretMoved (22:11:43.507):
Caret didn't move before timeout. Elapsed: 100 ms
IO - speech.speak (22:11:43.507):
Speaking [u'em branco']
IO - inputCore.InputManager.executeGesture (22:11:46.831):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (22:11:46.963):
Caret didn't move before timeout. Elapsed: 100 ms
IO - speech.speak (22:11:46.963):
Speaking [u'em branco']
IO - inputCore.InputManager.executeGesture (22:11:47.858):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (22:11:47.895):
Caret move detected using bookmarks. Elapsed: 0 ms
IO - speech.speak (22:11:47.993):
Speaking [u'12']
IO - inputCore.InputManager.executeGesture (22:11:48.674):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (22:11:48.707):
Caret move detected using bookmarks. Elapsed: 0 ms
IO - speech.speak (22:11:48.812):
Speaking [u'12']
IO - inputCore.InputManager.executeGesture (22:11:49.756):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (22:11:49.785):
Caret move detected using bookmarks. Elapsed: 0 ms
IO - speech.speak (22:11:49.878):
Speaking [u'12']
IO - inputCore.InputManager.executeGesture (22:11:50.678):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (22:11:50.852):
Caret didn't move before timeout. Elapsed: 100 ms
IO - speech.speak (22:11:50.940):
Speaking [u'12']
IO - inputCore.InputManager.executeGesture (22:11:53.803):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (22:11:54.053):
Developer info for navigator object:
name: u'\U0001f468'
role: ROLE_LISTITEM
states: exception: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
isFocusable: exception: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
hasFocus: False
Python object: <NVDAObjects.UIA.ListItem object at 0x050C5750>
Python class mro: (<class 'NVDAObjects.UIA.ListItem'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: ''
location: None
value: None
appModule: <'windowsinternal_composableshell_experiences_textinput_inputapp' (appName u'windowsinternal_composableshell_experiences_textinput_inputapp', process ID 9660) at address 50b1730>
appModule.productName: u'Microsoft\xae Windows\xae Operating System'
appModule.productVersion: u'10.0.17134.191'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 6096854
windowClassName: u'Windows.UI.Core.CoreWindow'
windowControlID: 0
windowStyle: -1811939328
windowThreadID: 10096
windowText: u'Microsoft Text Input Application'
displayText: exception: 'NoneType' object is not iterable
UIAElement: <POINTER(IUIAutomationElement) ptr=0x8239d38 at 52daf80>
UIA automationID: Exception: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
UIA frameworkID: XAML
UIA runtimeID: (42, 6096854, 4, 31)
UIA providerDescription: [pid:9660,providerId:0x0 Main(parent link):Unidentified Provider (unmanaged:Windows.UI.Xaml.dll)]
UIA className: GridViewItem
UIA patterns available: LegacyIAccessiblePattern, VirtualizedItemPattern, ScrollItemPattern, SelectionItemPattern

**Comment by Adriani90** [comment]
@fernando-jose-silva are you still having this issue in NVDA 2020.1?

**Comment by fernando-jose-silva** [comment]
thanks, everything works fine now.

Enviado do meu iPhone

**Comment by Adriani90** [comment]
Thanks for reporting, closing as works for me.
