### ISSUE TITLE
nvda read only face several times when finding several emugis in the same line and inside the word

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8640]
### Steps to reproduce:
Incira several diverse emugis in a same line in the word.
Now press arrows down or down to read the various emugis in sequence.

### Actual behavior:
nvda will read face, face, face, face.
### Expected behavior:
I would expect that the nvda would read the names of the various emugis, when they are varied, for example it could read:
face rolling with laughter, face with heart eyes, happy face, computer.
Now if you navigate with arrows to the right and left by the line the nvda will read the description of the emugis.
Nvda has the add-ons disabled, using espeak, and I have not changed the settings for uia in word.
#### NVDA Installed/portable/running from source:
instaled
#### NVDA version:
alfa 15781
#### Windows version:
10 17134.228
#### Name and version of other software in use when reproducing the issue:
word 16.0.10325.2082
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

log:
IO - inputCore.InputManager.executeGesture (22:15:36.065):
Input: kb(laptop):upArrow
DEBUGWARNING - Python warning (22:15:36.094):
C:\Program Files (x86)\NVDA\library.zip\keyboardHandler.py:509: DeprecationWarning: Yield() is deprecated
DEBUGWARNING - Python warning (22:15:36.095):
C:\Program Files (x86)\NVDA\library.zip\api.py:274: DeprecationWarning: Yield() is deprecated
DEBUG - editableText.EditableText._hasCaretMoved (22:15:36.098):
Caret move detected using bookmarks. Elapsed: 0 ms
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.101):
_getTextWithFieldsForUIARange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.101):
rootElement: documento
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.102):
full text: 🤣😍😘👨

DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.102):
Fetching parents starting from enclosingElement
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.105):
parentElement: editar
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.108):
parentElement: página
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.114):
Hit root
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.115):
Done fetching parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.115):
Generating controlFields for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.115):
parentElement: editar
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.117):
parentElement: página
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.118):
Done generating controlFields for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.118):
Yielding control starts for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.118):
Done yielding control starts for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.118):
Yielding balanced fields for textRange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.118):
no children
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.118):
Yielding text
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (22:15:36.118):
_getTextWithFields_text start
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (22:15:36.118):
Walking by unit None
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (22:15:36.118):
With further units of: [1, 2, 0]
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (22:15:36.119):
Chunk has text. Fetching formatting
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (22:15:36.121):
Yielding formatting and text
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (22:15:36.121):
Done _getTextWithFields_text
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.121):
Yielding controlEnd for parentElement
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.121):
Yielding controlEnd for parentElement
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (22:15:36.121):
_getTextWithFieldsForUIARange end
IO - speech.speak (22:15:36.122):
Speaking [u'\U0001f923\U0001f60d\U0001f618\U0001f468\r']
IO - inputCore.InputManager.executeGesture (22:15:41.298):
Input: kb(laptop):NVDA+f1
DEBUGWARNING - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (22:15:41.321):
AppModule does not have a binding handle
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (22:15:41.473):
Developer info for navigator object:
name: u'\xc1rea de trabalho'
role: ROLE_WINDOW
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.window.Desktop object at 0x050F81B0>
Python class mro: (<class 'NVDAObjects.window.Desktop'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: ''
location: RectLTWH(left=0, top=0, width=1920, height=1080)
value: ''
appModule: <'appModuleHandler' (appName u'csrss', process ID 13828) at address 50f81f0>
appModule.productName: exception: processHandle is 0
appModule.productVersion: exception: processHandle is 0
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 65552
windowClassName: u'#32769'
windowControlID: 0
windowStyle: -1778384896
windowThreadID: 6936
windowText: u''
displayText: u''

**Comment by Adriani90** [comment]
@fernando-jose-silva how is this now in NVDA 2020.1? Note that this depends also on which synthesizer you are using. We could add all the emojis to the symbols dictionary but this means alot of work and imo a synth provider should make sure that its synthesizer can speak the symbols correctly.

**Comment by fernando-jose-silva** [comment]
thanks, everything works fine now.

Enviado do meu iPhone

**Comment by Adriani90** [comment]
Thanks for reporting. Closing as works for me.
