### ISSUE TITLE
With the Enhanced ARIA add-on enabled and Articles checked, article landmarks produce fatal errors in braille

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#8642]
### Steps to reproduce:

1. In NVDA Alpha builds, install the Enhanced ARIA plugin.
2. Go to Settings, Enhanced ARIA, and check the Report Articles checkbox.
3. Go to any instance of the Mastodon social network, and after logging in or creating an account, go to either the Home or Notification headings and start DownArrowing.

### Actual behavior:

The first line of each article produces an error series like this:

IO - inputCore.InputManager.executeGesture (10:39:47.411):
Input: kb(laptop):downArrow
IO - speech.speak (10:39:47.545):
Speaking [u'Sprungmarke article ', u'Link', u'Uta', u' folgt dir']
ERROR - core.CorePump.run (10:39:47.578):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 475, in run
  File "braille.pyc", line 2131, in pumpAll
  File "braille.pyc", line 1873, in handlePendingCaretUpdate
  File "braille.pyc", line 1879, in _doCursorMove
  File "braille.pyc", line 975, in update
  File "braille.pyc", line 873, in _addTextWithFields
  File "browseMode.pyc", line 1074, in getControlFieldBraille
KeyError: u'article'
ERROR - queueHandler.flushQueue (10:39:47.653):
Error in func _handleUpdate from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 50, in flushQueue
  File "virtualBuffers\__init__.pyc", line 657, in _handleUpdate
  File "braille.pyc", line 1934, in handleUpdate
  File "braille.pyc", line 975, in update
  File "braille.pyc", line 873, in _addTextWithFields
  File "browseMode.pyc", line 1074, in getControlFieldBraille
KeyError: u'article'
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (10:39:47.786):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
ERROR - queueHandler.flushQueue (10:39:47.973):
Error in func _handleUpdate from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 50, in flushQueue
  File "virtualBuffers\__init__.pyc", line 657, in _handleUpdate
  File "braille.pyc", line 1934, in handleUpdate
  File "braille.pyc", line 975, in update
  File "braille.pyc", line 873, in _addTextWithFields
  File "browseMode.pyc", line 1074, in getControlFieldBraille
KeyError: u'article'

### Expected behavior:

Errors should not occur.

#### NVDA Installed/portable/running from source:

Installed.

#### NVDA version:

version alpha-15878,fabb3cd4

#### Windows version:

Windows 10 Version 10134,17738.

#### Name and version of other software in use when reproducing the issue:

Firefox 62Beta 17.

#### Other information about your system:

Handy Tech Actilino braille display.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA?

Yes, 2018.2.1, happens there, too. Error log excerpt:

IO - inputCore.InputManager.executeGesture (10:58:39.328):
Input: kb(laptop):downArrow
IO - speech.speak (10:58:39.466):
Speaking [u'Status by switching.social Sprungmarke article ', u'Link', u'ein o\u0254\u0279\u0250W']
ERROR - core.CorePump.Notify (10:58:39.490):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyo", line 446, in Notify
  File "braille.pyo", line 2003, in pumpAll
  File "braille.pyo", line 1791, in handlePendingCaretUpdate
  File "braille.pyo", line 1797, in _doCursorMove
  File "braille.pyo", line 934, in update
  File "braille.pyo", line 832, in _addTextWithFields
  File "browseMode.pyo", line 1074, in getControlFieldBraille
KeyError: u'article'

**Comment by sukiletxe** [comment]
cc @jmdaweb, as he's the author of the addon. Maybe it's nothing on his side, but just in case.

**Comment by dkager** [comment]
The implementation in braille (`landmarkLabels`) only contains [landmarks, not HTML5 elements](https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/HTML5.html).
@MarcoZehe I'd value your expert opinion on whether we should extend this to include HTML5 elements that do not map to a landmark by default.

**Comment by jmdaweb** [comment]
The article is also a landmark. Enhanced Aria extends the dictionary located in aria module. Version 2.2-dev will extend the braille dictionary too.

**Comment by dkager** [comment]
> The article is also a landmark. Enhanced Aria extends the dictionary located in aria module. Version 2.2-dev will extend the braille dictionary too.

Then why is this not in core? Not to invalidate the usefulness of your add-on, but this seems like something every user would want.

**Comment by MarcoZehe** [comment]
I can only speak for myself, but the only reason I actually use the add-on is so that I can jump between different articles on a site. The social network Mastodon, and the alternative client Pinafore use this heavily for each status, and I wanted a quick way to skip between them without having to switch off virtual cursor. So the only thing I actually did was install the add-on and activate the only checkbox that wasn't enabled yet, which was Article. I would love to see this in Core. Because I believe the html5 article element is made for exactly such cases to denote several separate pieces of text on a single page that are sort of self-contained.

**Comment by jscholes** [comment]
See https://github.com/nvaccess/nvda/issues/7835.

**Comment by dkager** [comment]
Just tested to confirm that `<article>` is not indicated in braille in any way. My vote goes to extending the landmark role-to-name dictionaries in NVDA core to include these so-called sectioning elements as well, while leaving landmark-based navigation for its own feature request.

**Comment by jmdaweb** [comment]
Hello.

You can test the latest commits on Enhanced Aria repository. I have
added also the article abbreviation as "art" for Braille. Once I update
the spanish translation, version 2.2-dev will be released. If it works
as expected, I will declare it as stable and post to the addons mailing
list.

Regards.

**Comment by jscholes** [comment]
If article is a valid landmark type, it seems like these two fixes should be implemented at the same time.  It wouldn't be appropriate for users to be aware of navigation in and out of article landmarks via speech and braille, if the same landmarks were not included in the elements list or when navigating with quick nav.

**Comment by dkager** [comment]
That's why I was hoping an ARIA expert could clarify if `<article>` is to be treated like a landmark (the link I provided above indicates that it is not).

**Comment by jmdaweb** [comment]
Hello.
Please, let me know if this new version works: https://github.com/jmdaweb/enhancedAria/releases/download/v2.2-dev/enhancedAria-2.2-dev.nvda-addon
Regards.

**Comment by tmthywynn8** [comment]
Testing against version 2018.3beta2:

- With the stable version of the add-on (2.1): The error occurs [as described above][1], as well as the display not updating with the text of the article landmark.
- With the add-on from [this comment][2]: the text is displayed with the "lmk art" prefix, and no errors are thrown.

[1]: https://github.com/nvaccess/nvda/issues/8642#issue-351513371
[2]: https://github.com/nvaccess/nvda/issues/8642#issuecomment-413828949

**Comment by Adriani90** [comment]
ok, it seems to work. Closing as works for me.
