### ISSUE TITLE
Impossible to close NVDA when welcome dialog or dialog asking about collecting data is open

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#8651]
### Steps to reproduce:
1. from the help menu open welcome dialog or wait for usage data collection dialog to appear on startup.
2. Press NVDA+q and depending on your settings select exit from the newly opened dialog box, or wait for NVDA to quit.
### Actual behavior:
Nothing happens.
### Expected behavior:
NVDA should close.
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
alpha-15905,ec3eeee9
#### Windows version:
Windows 7
#### Name and version of other software in use when reproducing the issue:
None
#### Other information 
Restarting with this dialogs open works.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
Yes 2018.2.1 and the issue is still reproducible. Obviously i havent't tried with usage data collection dialog, because it isn't present in this version.

**Comment by Mohamed00** [comment]
Probably related to #8453.

**Comment by lukaszgo1** [comment]
Closing as a duplicate of #1740. @ehollig Can you add an apropriate label to this?
