### ISSUE TITLE
Suggestion for an audio alert if warnings occur in an add on onsnapshot builds

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#8656]
It occured to me that in the next year or so, NVDA is going to undergo major changes caused by the migration to a newer version of the language and tools used by it.
 I also noticed that debug warnings are already appearing in logs on the current release and snapshots, but these generally go unnoticed unless you are  inspecting the log for some other problem.

Though I most certainly would not suggest all debug warnings are generating the error sound, is it possible that these warnings caused by code about to be depricated or have its syntax changed could have a switchable audible warning. This might help those using add ons to tell whether to lobby for an update in case, one day a new nvda comes out and breaks an important function provided by an add on. Although I understand NV Access do not make or feel responsible for add ons, ther is a kind of moral responsibility to the community, in my opinion.
 Just a thought. It may of course be very hard to actually achieve this without flagging all warnings, I do not know but its just a suggestion.
Brian<!--

**Comment by Adriani90** [comment]
There is now a warning when an addon is not compatible. I am closing this as works for me.
