### ISSUE TITLE
Python 3: new.instancemethod is no more

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8658]
Hi,

Discovered while trying to figure out why speech synthesizers were not loading in python 3 port: new.instancemethod is gone.

### Steps to reproduce:
1. Run Python 2.7 and 3.7 interpreters.
2. Type "import new".

### Actual behavior:
Python 3 raises "ModuleNotFoundError".

#### NVDA Installed/portable/running from source:
Not applicable

#### NVDA version:
N/A

#### Windows version:
Windows 10 Version 1803

#### Name and version of other software in use when reproducing the issue:
Python 2.7, 3.7

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your PC?
Not applicable

#### Have you tried any other versions of NVDA?
N/A

### Impact:
This may impact object creation and related facilities, a fundamental blocking bug for Python 3 transition. Google searches says use types.instancemethod, or in Python 3, new.instancemethod is not needed.

Thanks.

**Comment by larry801** [comment]
Is types.MethodType proper for this?

**Comment by leonardder** [comment]
a simple grep of instancemethod in the git repository turns out that instancemethod is only imported in the NVDAObjects module (__init__.py), but it is unused.

**Comment by josephsl** [comment]
Hi, confirmed. There are also others that import certain items but never use them (bdDetect and external eSpeak python module, for instance). Thanks.
