### ISSUE TITLE
Brailleme Diplsay typing issue from 2018.2 onwards - URGENT

### ISSUE THREAD

**Issue by brailleme** [nvaccess/nvda#8659]
#### Information about your system:
BrailleMe is Electronic Braille display for visually challenge persons developed by Inceptor technology pvt. Ltd. (INNOVISION). Coompay is located inside IIT Bomaby Campus Powai (Mumbai). 
Currently BrailleMe Display driver is not included in the NVDA software. We have created an NVDA add on to support our BrailleMe display with NVDA. This add on is working properly with earlier versions of NVDA  untill 2018.1.1. But after 2018.2 we are facing issues while typing braille characters.   

### Steps to reproduce:

1. Installed NVDA 2018.2 Version by executing the executable file.
2. Installed Braille me driver in the from of NVDA add on.
3. Configured BrailleMe Display for NVDA connection.
4. Started NVDA and and configured NVDA to connect to BrailleMe Display as follows:
 preferences -> braille setting -> Braille Display -> BrailleMe
5. Connection is successful after this and we are able to use the navigation commands from our braille display.
6. But while typing in a text file we are not able to type braille characters and no output is coming on the computer. This was not the case with the earlier 2018.1.1 version. With earlier version we are able to type from the device and output is reflected on the computer system. 
 
### Actual behavior:
Braille Input keys for typing are not working from 2018.1.1 version onward

### Expected behavior:
Should be able to type characters with the help of braille input keys. 

### System configuration:
Windows-10 64bit,
NVDA 2018.2,

#### NVDA Installed/portable/running from source:
NVDA installed through executable file

#### NVDA version:
NVDA 2018.2 & NVDA 2018.2.1

#### Windows version:
Windows-10 64 bit

#### Name and version of other software in use when reproducing the issue:
Braille Me Driver ( Addon + Driver)

### Other questions:
1. How can we add our BrailleMe display driver into NVDA repository? Can NVDA team guide us for that? 

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA?
working with earlier NVDA version from 2017.3 to 2018.1.1

I have attached the NVDA BrailleMe driver and Addon source code with this.
Please Find the attachments :

[Braille Me Driver.zip](https://github.com/nvaccess/nvda/files/2309131/Braille.Me.Driver.zip)
[addon.zip](https://github.com/nvaccess/nvda/files/2309127/addon.zip)

**Comment by bramd** [comment]
I can't help with this specific issue, but I've some ideas on getting BrailleMe in NVDA core:

You already have a working add-on it seems. It would be good to open a pull request for this, so we can start code review/discussion there. However, it seems the current add-on depends on winusbpy which would be a new dependency for NVDA. Would it be possible to eliminate the dependency and use the tools provided in NVDA's built-in hwIo module? That way it is also possible to include your driver in NVDA's braille auto detection (see the bdDetect module).

**Comment by ikrami1** [comment]
is there any news regarding this issue?
can Braille me Braille display driver integrated into nvda core?

**Comment by Adriani90** [comment]
cc: @michaelDCurran

**Comment by feerrenrut** [comment]
It would be helpful if the addon author (@brailleme) could describe the error they are encountering. NVDA has moved on quite a bit since 2018.2, the addon likely needs maintenance.

**Comment by Adriani90** [comment]
I will close this as abandoned because we haven't got any answer from the author since the issue has been submited.
