### ISSUE TITLE
Python version 3.7 does not support a 'ur' prefix

### ISSUE THREAD

**Issue by larry801** [nvaccess/nvda#8660]
### Steps to reproduce:
Install python3.7 
Run py -3 nvda.pyw under source folder of NVDA repo
### Actual behavior:
  File "nvda.pyw", line 179
    k = _winreg.OpenKey(_winreg.HKEY_LOCAL_MACHINE, ur"SOFTWARE\NVDA")
                                                                    ^
SyntaxError: invalid syntax
### Expected behavior:
Find a replacement of ur
### System configuration:
N/A
#### NVDA Installed/portable/running from source:
source
#### NVDA version:
master 8e2df9f
#### Windows version:
N/A
#### Name and version of other software in use when reproducing the issue:
Python3.7(32bit)

### Other questions:
Since ur" string prefix has no counterpart in python3
We can replace it with a solution from [this](https://stackoverflow.com/questions/26063899/python-version-3-4-does-not-support-a-ur-prefix) StackOverflow link

reg_path = r"SOFTWARE\NVDA"
try:
    # Python 2
    reg_path = reg_path.decode('raw_unicode_escape')
except AttributeError:
    # Python 3
    pass

A helper method may ease the process of transition and save boiler template.
like
```
def raw_unicode_escape_helper(original_string):
	try:
		# Python 2
		original_string = original_string.decode('raw_unicode_escape')
	except AttributeError:
		# Python 3
		pass
	return original_string
```
Then we can use
```
k = _winreg.OpenKey(_winreg.HKEY_LOCAL_MACHINE, raw_unicode_escape_helper(r"SOFTWARE\NVDA"))
```
If we were to use a helper method like this.
How to name it? Where to put it? Is it necessary to add a module for these helper methods in core?

**Comment by feerrenrut** [comment]
Fixed with https://github.com/nvaccess/nvda/pull/9719
