### ISSUE TITLE
Python 3: string and character comparison (chr and unichr, byte string indexing, basestring, encoding/decoding)

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#8661]
### Steps to reproduce:
Switch from python 2 to python 3.

### Expected and Actual behavior:
1. In python 2, chr(1) produces a byte character whereas unichr produces an unicode character. In python 3, unichr is now called chr whereas unichr does no longer exist. Unichr is used in the following modules:

    * XMLFormatting
    * appModules.powerpnt
    * brailleInput
    * browseMode
    * displayModel
    * keyboardHandler
    * speechXml
    * winConsoleHandler

    Six implements six.unichr which calls unichr on py2 and chr on py3. It also implements six.int2byte that calls chr on python 2 and bytes on python 3.

2. There is a major difference in how python 2 and 3 deal with getting indexes from byte strings:

    Python 2:
```
>>> string="hello"
>>> string[0]
'h'
>>> string[0:2]
'he'
>>> string[:]
'hello'
```
    Python 3:
```
>>> string=b"hello"
>>> string[0]
104
>>> string[0:2]
b'he'
>>> string[:]
b'hello'
>>> string[0]==b"h"
False
>>> string[0:1]==b"h"
True
>>> chr(string[0])=='h'
True
```

I think the following conveys the intent best:
- To compare to a single character: `chr(string[0])=='h'`

### Additional details
I think that these python differences are quite important when dealing with porting of braille display drivers and the hwIo module. I recall that, especially with incoming data, native drivers tend to use byte string indexing quite a lot, expecting a string for single indexes. This will be quite problematic.

**Comment by larry801** [comment]
If we add from __future__ import unicode_literals.
b prefix generates bytes literal, not str literal.
If drivers need bytes only that would be OK.
If some code requires str literal.
We may use bytes_to_native_str from python future.
http://python-future.org/unicode_literals.html

**Comment by leonardder** [comment]
Hmm, note that this is future, not __future__. future is an extra module that needs to be included in NVDA's build system, which shouldn't be that difficult. The interesting idea behind future is that it claims to make python 3 code work on python 2, i.e. it allows you to use python 3 style byte objects on python 2.

cc @josephsl

**Comment by leonardder** [comment]
Python 3 also removed basestring

Python 2:

```

```
Python 3:

```
>>> isinstance(b"hello", basestring)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'basestring' is not defined
```

We can use six.string_types as an alternative.

**Comment by feerrenrut** [comment]
I have updated the description with a preference for comparing a character to a single byte (from bytes). I think we should do the same for other types of comparisons:
- unicode string with bytes
- Changes in indexing of strings
