### ISSUE TITLE
Brailliant BI stops working after disconnect when using OpenBraille protocol via Bluetooth

### ISSUE THREAD

**Issue by bramd** [nvaccess/nvda#8663]
### Steps to reproduce:
1. Make sure NVDA's braille display selection is set to "automatic", the Brailliant is set to OpenBraille protocol, paired and turned on
2. After the display is recognized and shows braille output, turn it off
3. Turn it back on

### Actual behavior:
* The display is not recognized. Only turning Bluetooth off and on in Windows makes NVDA see the display again
* The display is no longer included in `hwPortUtils.listHidDevices`

### Expected behavior:
* The display is recognized every time it is turned back on

#### NVDA Installed/portable/running from source:
* Tested with Installed and running from source

#### NVDA version:
* Various recent alpha builds, including alpha-15878,fabb3cd4
#### Windows version:
* Windows 10 Version 1803 (OS Build 17134.228)
#### Other information about your system:
* Tested with Brailliant BI 40
#### Does the issue still occur after restarting your PC?
* Yes
#### Have you tried any other versions of NVDA?
* Various alpha snapshots

**Comment by bramd** [comment]
Another, probably related, issue is that the Bluetooth HID device does not show up in the list of ports for the Humanware Brailliant display. All possible serial ports are shown though, but there are no Brailliant displays with a serial port as far as I know.

CC @jcsteh

**Comment by bramd** [comment]
[**@leonardder**](https://github.com/leonardder) commented on [Aug 23, 2018, 11:19 AM GMT+2](https://github.com/nvaccess/nvda/issues/8663#issuecomment-415350003 "2018-08-23T09:19:50Z - Replied by Github Reply Comments"):
> [**@bramd**](https://github.com/bramd) commented on [22 aug. 2018 23:15 CEST](https://github.com/nvaccess/nvda/issues/8663#issue-353128413):
> 
> > *   The display is no longer included in `hwPortUtils.listHidDevices`
> 
> hwPortUtils.listHidDevices has a default kwarg that will only search for available devices. When you provide onlyAvailable=False, I assume the device shows up correctly? This might be a Windows bug, I'd say that whenever Bluetooth HID is on, these HID devices should be considered available while bluetooth is on.

I'll look into that. Since the device is available the first time, this looks like a Windows bug, or a misuse of a Windows API on our side.

> [**@bramd**](https://github.com/bramd) commented on [22 aug. 2018 23:17 CEST](https://github.com/nvaccess/nvda/issues/8663#issuecomment-415183528):
> 
> > Another, probably related, issue is that the Bluetooth HID device does not show up in the list of ports for the Humanware Brailliant display.
> 
> The list of ports lists Automatic, bluetooth and/or usb, depending on what devices are available.
> 
> *   USB shows up when bdDetect.getConnectedUsbDevicesForDriver("brailliantB") is True
> *   Bluetooth shows up when bdDetect.getPossibleBluetoothDevicesForDriver("brailliantB") is True
> *   Automatic shows up when either one or both of the cases above are true.

None of these options show while I have a working connection to the display over Bluetooth HID. I would expect auto/bluetooth to be available.

> > All possible serial ports are shown though, but there are no Brailliant displays with a serial port as far as I know.
> 
> The Brailliant BI40 uses a virtual com port over USB when in humanware mode, and therefore I thought it would make sense to allow people to explicitly choose the appropriate com port if desired.

That's true, but with a few Bluetooth devices (two ports per device) the list gets long/confusing. We might consider adding functionality to provide all possible auto detected ports in the port list by default for every device, or be more specific which ports we want to show (only USB serial ports for BrailliantB) but that's outside the scope for this issue.

**Comment by leonardder** [comment]
[**@bramd**](https://github.com/bramd) commented on [23 aug. 2018 11:29 CEST](https://github.com/nvaccess/nvda/issues/8663#issuecomment-415352651 "2018-08-23T09:29:03Z - Replied by Github Reply Comments"):
> None of these options show while I have a working connection to the display over Bluetooth HID. I would expect auto/bluetooth to be available.

That is very weird. But than still, whether automatic/bluetooth show up is entirely dependent on what hwPortUtils.listHidDevices reveals. May be it does not list your BrailliantB even though it is connected at that particular moment? Or there's something weird with the match func in bdDetect.

**Comment by Adriani90** [comment]
We didn't hear any updates from the initial author upon request since many years, I am closing this issue as abandoned. if you are still having this issue, please comment and we can reopen.
