### ISSUE TITLE
NVDA should support chitchat for facebook

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#867]
**Reported by RamboUdin on 2010-08-29 07:11**
Hi,
i'm using chit chat for facebook, to chat. So, nvda should support that.

especially, at the chat window. (reading message automatically)

**Comment by leonardder** [comment]
I'm closing this as a Won't fix:

1. The ticket is abandoned for like 7 years
2. There are two accessible alternatives for Facebook: instant bird and Miranda NG. Even the Facebook website is doable.
3. It is very unlikely that someone will ever have the resources or interest fix this at some point, given the two former points.

If someone disagrees, please feel free to harass me. It's not that difficult to reopen an issue.
