### ISSUE TITLE
Javascript exception in IE 11 with NVDA running when form submitted with empty required input fields

### ISSUE THREAD

**Issue by BrianRisingerMoxie** [nvaccess/nvda#8671]
### Steps to reproduce:
1. Open Internet Explorer 11 (I am using version 11.228.17134.0 Update version 11.0.80, specifically)
1. Navigate to a page with a form that has at least one input field that has the 'required' attribute. (an example page is attached at the bottom)
1. Do not fill in the field with the 'required' attribute'
1. Submit the form

### Actual behavior:
The form is not submitted, and a JavaScript error dialog appears indicating an error on line 1, character 1 of the page (which does not have any JavaScript on it)

### Expected behavior:
The form should not submit, and a 'required' call-out should appear indicating that the input field with the required attribute was not filled out. I would expect this call-out would be read in association with the label of the input field. I expect no Javascript error dialogs to appear, as that is the behavior without NVDA running. 

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.2.1

#### Windows version:
Windows 10 Pro
Version	10.0.17134 Build 17134

#### Name and version of other software in use when reproducing the issue:
Internet Explorer 11 version 11.228.17134.0 Update version 11.0.80

#### Other information about your system:
Interestingly, while filling out the bug report, I have discovered that the issue does no occur if I have my speakers muted (by pressing Windows-key + F1 on my laptop), however it does occur if I drag the windows speaker control in the system tray to 0% (which also shows the volume icon as being muted). This laptop has Realtek Audio drivers.

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

[NVDA.zip](https://github.com/nvaccess/nvda/files/2319890/NVDA.zip)

**Comment by StevenMilneDev** [comment]
I have also noticed this bug and it doesn't just affect Internet Explorer 11, it also affects Edge. It seems any form with HTML5 validation causes issues when the validation fails. I've confirmed it happens with email type fields and also numeric fields with a minimum value.

The error that is shown in IE is `Invalid calling object` on line 1 character 1. Edge seems to exhibit similar behaviour but without the Script Error popup.

I have created a little snippit which causes the issue to happen, but online code editors like CodePen and JSFiddle don't seem to work in IE. Below is the snippit source code which can be copy/pasted into a .html file and opened in IE;

```
<!DOCTYPE html>
<html>
    <head>
        <title>NVDA Bug</title>
    </head>
    <body>
        <h1>NVDA HTML5 Validation Bug (IE &amp; Edge)</h1>
        <p>
            The field below is &quot;required&quot; using HTML5 validation. Leave it blank or type in
            random text without the <code>@</code> symbol and then click the &quot;Submit&quot;
            button. On IE and Edge this will work unless NVDA is running in which case
            we get a Script Error popup with the error <code>Invalid calling object</code>.
            This error only occurs when NVDA is active, the form otherwise works.
        </p>
        <form action="https://google.com" method="GET">
            <label for="field1">My Field</label>
            <input type="email" id="field1" required />
            <input type="submit" value="Submit" />
        </form>
    </body>
</html>
```

My system configuration is as follows;

### System Configuration:

**NVDA Installed/portable/running from source:**
Installed

**NVDA version:**
2018.3.2

**Windows version:**
Windows 10 Enterprise Version 1803 (Build 17134.407)

**Name and version of other software in use when reproducing the issue:**
- Internet Explorer 11 Version 11.407.17134.0 (Update Version 11.0.95)
- Edge Version 42.17134.1.0 (EdgeHTML Version 17.17134)

**Comment by seanbudd** [comment]
Considering this issue only affects internet explorer and the deprecated version of Edge, I am closing this issue.

**Comment by Adriani90** [comment]
IE support ended completely in 2022, and the browser is automatically removed from machines that still have it after an Edge update in February 2023. I am closing this as abandoned, since I don't expect any further accessibility updates to IE or to IE mode in Edge. In Edge Chromium 111 I cannot reproduce this issue, Chrome and firefox work also well.
If you have still this issue in other browsers, please open a new issue with updated steps to reproduce and a minimal test case.
