### ISSUE TITLE
Remove Python 2 imports for modules renamed in python 3

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#8677]
Certain modules have been renamed between python 2.7 and 3.7.

In https://github.com/nvaccess/nvda/pull/8606 a fall back to the python 3 name for these modules was introduced. Since our releases are using Python 2.7, we first attempt to import the Python 2.7 module.

When we reach the point of including Python 3 support in a release of NVDA we should remove the python 2 imports.

See also: #8727 (Python 3 imports: additional work on builtins, relative imports, importlib)

**Comment by Brian1Gaff** [comment]
Does this mean that both python runtimes are going to be used in the 
releases. Sorry if this is a stupid question!

Brian

**Comment by jscholes** [comment]
At some point, there may be different branches of NVDA using different Python versions, e.g. a stable release using Python 2.7 and an alpha or beta build using Python 3.x.  But NVDA will only run with one Python version at a time.

**Comment by josephsl** [comment]
Hi,

Most are taken care of now. Closing.

Thanks.

**Comment by feerrenrut** [comment]
> Most are taken care of now

Most? Have you checked? If there are others not taken care of, then this should be re-opened.

**Comment by josephsl** [comment]
Hi, I bet there are instances of importing winreg, CStringIO and others that we aren’t aware of at the moment. Thanks.

**Comment by feerrenrut** [comment]
I have searched the `source/` directory for all the [changed names referenced in the python 3 porting guide.](http://python3porting.com/stdlib.html) There

The only one I have found is: `im_self` which should become `__self__`. This is used in `scriptHandler.py`, the line is as follows:
```
		givenFunc=getattr(scriptFunc.im_self.__class__, scriptFunc.__name__)
```

This should be tested to confirm that it fails. If so, it should be changed.

**Comment by leonardder** [comment]
@josephsl: Are you willing to do this?

**Comment by michaelDCurran** [comment]
As we compile with py2exe, we can be assured that all our imports are correct, as otherwise py2exe would fail. Thus to close this issue, we only need to verify changes to special attribute names (such as im_self etc). which I am doing now.

**Comment by michaelDCurran** [comment]
I have checked all builtin and attribute renames, and have confirmed @feerrenrut 's  findings that the only one not handled is im_self in scritHandler.
I have also ran py2exe and read through all missing modules. They are all optional modues imported by modules in the standard library or other dependencies, or comtypes auto-generated files. There are no missing modules directly imported by NVDA's codebase.

**Comment by michaelDCurran** [comment]
scriptHandler.isCurrentScript tries to access im_self which will always fail. However, we never call isCurrentScript anywhere in the NVDA codebase. Do people have evidence that it is ever used in add-ons? If not we should just remove the function all together.

**Comment by josephsl** [comment]
Hi, ran grep on my own repo of add-ons, along with addons installed on a portable alpha version (the latter has 67 add-ons, all of them from community add-ons website, installed for the express purpose of testing compatibility with NVDA 2019.3). Nowhere in add-ons code is isCurrentScript mentioned. Thanks.
