### ISSUE TITLE
Attaching files in Basic HTML view in Gmail and Yahoomail with NVDA Bitta 2018.3

### ISSUE THREAD

**Issue by jacobchawala** [nvaccess/nvda#8684]
when attaching files and sending them using gmail and yahoomail in basic HTML mode, Nvda does not count percentages as progress bars; but it mentions percentages in progress bars when they are in standard view.

#### Other information about your system:
             Machine name: DESKTOP-R0NVNF4
               Machine Id: {F1EFE585-AA4A-485E-9FE9-4DC0FCCDACBF}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 17134) (17134.rs4_release.180410-1804)
                 Language: English (Regional Setting: English)
      System Manufacturer: TOSHIBA
             System Model: Satellite C850-C035
                     BIOS: InsydeH2O Version 03.72.306.50 (type: BIOS)
                Processor: Intel(R) Core(TM) i3-2348M CPU @ 2.30GHz (4 CPUs), ~2.3GHz
                   Memory: 8192MB RAM
      Available OS Memory: 8074MB RAM
                Page File: 2837MB used, 7156MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      
#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA?
yes, the issue is the same.

**Comment by Adriani90** [comment]
@jacobchawala could you please test now with NVDA 2020 RC1 and the last stable versions of the browsers? Is this still occuring?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years, I am closing this as abandoned. if you are still having this issue, please comment on it and we can reopen.
