### ISSUE TITLE
The NVDA Usage Statistics Dialog shouldn't appear in try builds on startup

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#8688]
### Steps to reproduce:
Start NVDA (portable) the very first time. (No config folder exists.)
### Actual behaviour:
After the Welcome Dialog the NVDA Usage Statistics Dialog appears also in try builds.
### Expected behaviour:
After the Welcome Dialog the NVDA Usage Statistics Dialog doesn't appear in try builds.
#### Reasons:
Based on the [comment by @jcsteh in PR #8678](https://github.com/nvaccess/nvda/pull/8678#issuecomment-416833221) the whole update check procedure is disabled in try builds. So showing this dialog on startup makes no sense. Furthermore the checkbox "Allow the NVDA project to gather NVDA usage statistics" in the General NVDA Settings doesn't exists, so it's only possible to change this value by editing "nvda.ini" with Notepad++ directly.
#### Entries in "nvda.ini":
`[update]`
`	allowUsageStats = False`
`	askedAllowUsageStats = True`
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
try-15940 (provided via PR #8678)
#### Windows version:
win7x64
#### Have you tried any other versions of NVDA?
No. I don't think that this behaviour should be changed in alpha builds and higher.

**Comment by leonardder** [comment]
This makes sense and is very easy to fix, though I don't think it has much priority.

**Comment by ehollig** [comment]
It appears this was not closed because of merging #8708 into beta. Closing
