### ISSUE TITLE
Add "4.1.2. NVDA Usage Statistics Dialog" in the User Guide

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#8689]
### Steps to reproduce:
Open the NVDA User Guide.
### Actual headlines:
4. Getting started with NVDA
4.1. Launching NVDA
4.1.1. Welcome Dialog
4.2. About NVDA keyboard commands
### Expected behaviour:
Add a new chapter called "4.1.2. NVDA Usage Statistics Dialog" with a little description and a reference to "Allow the NVDA project to gather NVDA usage statistics" in the chapter "11.1.1. General (NVDA+control+g)".
#### Update on 2018-09-04:
And please also write down based on [my comment in PR #8708](https://github.com/nvaccess/nvda/pull/8708#issuecomment-418127349) in the description that the NVDA configuration ("nvda.ini") will be saved automatically by pressing the buttons "Yes" and "No", but not when pressing "Later".
#### NVDA version:
NVDA 2018.3 Beta 3

**Comment by Adriani90** [comment]
This will be also solved by #9730.
