### ISSUE TITLE
Lag when typing web address in location bar in Mozilla Firefox

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#869]
**Reported by hurrikenny on 2010-08-30 07:25**
I have been testing out the Mozilla Firefox browser and IE browser getting them to go to the same webpage. In IE it keeps up with my typing, but in Mozilla there is a lag and it even omits letters. I know that the web address is correct because the correct page loads. It doesnt seem to lag in Internet Explorer only in Firefox for some reason. I am going to the exact same sites and both pages seem to load quickly in each browser, it is just that Mozilla lags when reading the letters out to me. I am using a 1.6Ghz netbook, 1GB ram with Windows XP home to test it with.

**Comment by dkager** [comment]
The mentioned [Mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=414491) still has status New, but I can't say I'm suffering from this problem.

**Comment by feerrenrut** [comment]
It looks like there hasn't been any activity on that issue for a long time. @jcsteh Can you comment on whether you would be happy with this being closed?

**Comment by Brian1Gaff** [comment]
I think this occurs due to the auto complete issues noted elsewhere. I tend 
to turn my hearing off when entering here now.

I find all these helpful  suggestions very irritating.
 Brian


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by jcsteh** [comment]
I certainly haven't been troubled by this. I'd guess this has improved over the last few years due to changes to the way Mozilla coalesces events. We're also not hearing reports of users being hit by this. Closing as worksforme.
