### ISSUE TITLE
Problems buying e-book on Kindle Store

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#8690]
Windows 10, NVDA alpha-15878/15933/versions from other users, In Chrome or Firefox, and probably other browsers, NVDA see no button to buy Kindle e-books on amazon (no problems with other product types). The unique way is to navigate with tab/shift+tab, or object navigation.

### Steps to reproduce:

* Go to Amazon, search an e-book, open the page with all details;
* Press "h" to jump at "Buying Options" header;
* Remaining in navigation mode, explore around with arrows.

### Actual behavior:

Under header NVDA sees the button to send a free sample, and over header the e-book categories.
If you press shift+tab from sample button, or tab from last category, then you hear "Buy now with 1-click".

### Expected behavior:

NVDA should show "Buy with 1-click" and other information around it in standard page buffer, as previously.

**Comment by csm120** [comment]
I have noticed this also. In my case I had a buy for everyone header. If I used object nav I could eventually get to the by with one click button but I wasn't able to activate it. I should be able to hit b and get to the buy with 1click in one or two presses.

**Comment by ABuffEr** [comment]
Hi,
closing. today situation seems resolved. Verified on .it and .com site.
