### ISSUE TITLE
MS Word with UIA, table navigation breaks on empty cells

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#8692]
cc @michaeldcurran

### Steps to reproduce:
1. Create a Word document with a table that contains empty cells. [table.docx](https://github.com/nvaccess/nvda/files/2333182/table.docx) is an example that implements a table with 3 columns and two rows. On the first row, the middle cell is empty, whereas in row 2, the right most cell is empty.
2. Navigate with table navigation through all the cells.

### Actual behavior:
NVDA announces out of table when coming across an empty cell, and table navigation does not work any more, unless you manually move back in the table.

### Expected behavior:
It should be possible to access every cell with table navigation.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
NVDA alpha-15933

#### Windows version:
Version 1809 (OS Build 17746.1000). Also reproducible in the April update.

#### Name and version of other software in use when reproducing the issue:
MS Word 16.0.10325.20118

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Not yet

**Comment by jage9** [comment]
Can reproduce here. In addition, if you create a completely empty table, NVDA does not recognize it at all.
Here's another example file. Running Office 2016 and NVDA 2018.4RC.
[NVDA blank cells example.docx](https://github.com/nvaccess/nvda/files/2651997/NVDA.blank.cells.example.docx)

**Comment by jage9** [comment]
This seems to be fixed in Office 2016.

**Comment by jage9** [comment]
@leonardder I think this one can now be closed as resolved in 2018.4?

**Comment by leonardder** [comment]
Fixed in #9022 
Thanks for reminding. The github magic isn't very accurate in pull requests merged to beta and then to master.
