### ISSUE TITLE
FN key announcement in input help

### ISSUE THREAD

**Issue by jacobchawala** [nvaccess/nvda#8694]
FN key is not pronounced after pressing NVDA+1 to invoke input help. the team should explore this key and other keys in modern computer keyboards to make them pronounced.

#### Other information about your system:
             Machine name: DESKTOP-R0NVNF4
               Machine Id: {F1EFE585-AA4A-485E-9FE9-4DC0FCCDACBF}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 17134) (17134.rs4_release.180410-1804)
                 Language: English (Regional Setting: English)
      System Manufacturer: TOSHIBA
             System Model: Satellite C850-C035
                     BIOS: InsydeH2O Version 03.72.306.50 (type: BIOS)
                Processor: Intel(R) Core(TM) i3-2348M CPU @ 2.30GHz (4 CPUs), ~2.3GHz
                   Memory: 8192MB RAM
      Available OS Memory: 8074MB RAM
             
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
yes but the issue remains the same

**Comment by leonardder** [comment]
The fn key modifies keys at a lower level than NVDA could access.

For example, I have fn+f9 on my laptop bound to volume up. Windows is directly receiving volume up when I press fn+f9, it is not registering the fn key itself.

Therefore, closing as can't fix.
