### ISSUE TITLE
Update to Liblouis 3.7

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#8697]
Liblouis 3.7 is due for release next week. Here is what's new/relevant for us:

- Fix input/output positions for back-translation
- New Chinese Mandarin Braille Codes (Grade 1) and (Grade 2)
- Improvements to UEB

This list is not complete yet.

**Comment by zstanecic** [comment]
Hi to all,

For the braille tables, i will do the PR for the braille tables.

**Comment by leonardder** [comment]
Windows builds are currently broken. See https://github.com/liblouis/liblouis/issues/634.

In the liblouis repository, there is already a 3.7.0 tag, so it looks like this is not going to be fixed before the release. In that case, we'll have to skip 3.7.0, since I'm not particularly interested in the inclusion of a fork in NVDA.

**Comment by leonardder** [comment]
https://github.com/liblouis/liblouis/issues/634 is now solved.
