### ISSUE TITLE
Turn document formatting into a multi-category panel with lists of checkboxes

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#8699]
We now have a checkable list, #7491. I have been toying with the idea of bringing several checkible list to NVDA's document formatting settings. This issue acts as the overall place to explore the idea more fully.

The following has already been toyed with.

1. as a user, I need to quickly toggle a setting in document formatting, so that I can read my paystubs which have important font information expressed using color.
2. As a user, being able to discover settings related to tables is important to my job, where I have to grade students using a tool that has inappropriate table headers which I need to discover the method of turning their announcement off. The current implementation takes lots of time for me to explore as a new user, and there is no quick way to jump through the groupings with a keyboard.

**Comment by DrSooom** [comment]
You can set up profiles (NVDA+CTRL+P) for different document formatting settings, which are triggered manually. I set up one just for correcting text. It only contains the following four values: reportFontAttributes, reportStyle, reportSpellingErrors  and reportLists

But you are right: The document formatting panel gets larger and larger. But on the other hand: There are also options within the document formatting panel which have more than two possible values. So we have to find a non-confusing way and (tab) order for those comboboxes.

**Comment by derekriemer** [comment]
The comboboxes is a good example. Yes, there are indeed multi-value items in there. I didn't think of that.

**Comment by leonardder** [comment]
I'm happy to take this on privately.

**Comment by dingpengyu** [comment]
> I'm happy to take this on privately.
hi leonardder
Thank you for your work
I tested nvda pr10448-19062 using the windows10-1903 Simplified Chinese language.
Function can be used normally

**Comment by Adriani90** [comment]
This is not valid anymore, because the decision is to implement combo boxes which allow setting reporting by speech, braille, or both speech and braille, see e.g. font atributes combo box. A checkbox would allow only two states.
I am closing this issue as abandoned due to different approach being implemented.
If you still think the document formating setting needs a redesign, please open a new feature request and fill the new template accordingly.
