### ISSUE TITLE
Unable to type comments in YouTube

### ISSUE THREAD

**Issue by burakyuksek** [nvaccess/nvda#8703]
### Steps to reproduce:
1. Go to youtube.com
2. Open a video
3. Press e to get to comment field
4. Type a comment.
### Actual behavior:
No kind of text gets entered, even with pass next key through
### Expected behavior:
Text gets entered
### System configuration:
windows7 64-bit
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
2018.2.1
#### Windows version:
7
#### Name and version of other software in use when reproducing the issue:
Mozilla firefox 61.0.2
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No

**Comment by Adriani90** [comment]
This works as expected now in Firefox 112 and NVDA alpha-28179,345154a6 (2023.2.0.28179). Closing as works for me.
