### ISSUE TITLE
A bug to repport: NVDA works harder in Windows Explorer for some users

### ISSUE THREAD

**Issue by florianionascu7** [nvaccess/nvda#8704]
Hello, two NVDA Romanian community members told me that NVDA works harder in Windows Explorer when opening any type of audio files in Winamp. Specifically, after a file is opened in Winamp, if they want to move back to its folder, NVDA freezes and tells nothing, and they must wait a while to hear things like my music window. Well, I don't think I am so accurate as I want to be, so I'm going to provide you some steps to reproduce this bug:
1. Open a folder with many audio files.
2. Choose a file ramdomly and open it in Winamp.
3. After that, you will be automatically focused on the Winamp's window. Press alt+tab to go back to the folder and NVDA will freeze suddenly.
4. Release the keystroke and wait a while to hear things like folder name window.
Personally, I couldn't reproduce this bug. NVDA's behaviour is normal in my case. What could be the problem?

**Comment by dangmanhcuong87** [comment]
I have the same issue in some case like copy file from my laptop to server. After pressing Ctrl+V to paste, I back to the source folder on my laptop to do other thing, and NVDA does not say anything. Although sighted people might work well on the laptop at that time.
Using Windows 10 pro 1803 64 bit with NVDA 2018.2.1.
Cuong

**Comment by florianionascu7** [comment]
I am wondering why this kind of bugs can't be reproduced by all users.

**Comment by Adriani90** [comment]
Can any one still reproduce this issue on Windows 10 or 11?

**Comment by Adriani90** [comment]
We didn't get any further updates from the initial authorn since many years, i am closing as abandoned. In case there is an update and you are still having this issue, please comment and we can reopen.
