### ISSUE TITLE
In Python3 urllib nolonger contians urlopen urlencode

### ISSUE THREAD

**Issue by larry801** [nvaccess/nvda#8717]
# Background:
In python3 urllib.urlopen has been moved into urllib.request
urlencode  has been moved into  urllib.parse
There are also more changes in detail.
These functions are used in updateCheck.py
# Possible solutions:
- from six.moves import urllib and use it like python3
- try to import python2 version first  and use urlopen urlencode alone without urllib prefix

**Comment by josephsl** [comment]
Hi, while working on #8590, I once thought about addressing this one, but decided against it, seeing that it could break update checks and such. I personally vote for the second option. Note that whatever option we choose could potentially affect #3208 as well. Thanks.

**Comment by larry801** [comment]
While developing an addon. I found that the six.moves.urllib requires urllib2.
There are also a lot of subtle differences between the urllib in two versions of python.

**Comment by leonardder** [comment]
Fixed in #9820
