### ISSUE TITLE
NVDA keeps saying unknown 

### ISSUE THREAD

**Issue by adil-s** [nvaccess/nvda#8718]
for last 2 days, my doesn't read in taskbar. when I press win+T right arrow to move around apps, it keeps saying. it doesn't read any context menu. I. E. If I press, application key to see available option, it acts like I didn't press application. 
I just don't what I should do.

things I tried before creating issue here:
tried running NVDA with all add-on disabled 
tried uninstalling and reinstalling NVDA
after uninstalling, tried cleaning registry keys for NVDA 
deleted the NVDA 
folder from 
[nvda-old.log](https://github.com/nvaccess/nvda/files/2351598/nvda-old.log)

**Comment by leonardder** [comment]
Could you please explicitly run the "Run COM Registration Fixing tool..." from the tools menu?

**Comment by Brian1Gaff** [comment]
Also if you do not actually shut down windows very often do so and restart, 
another ploy is to  log off the current user then log back in, quite often 
things then start to work again.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by adil-s** [comment]
I run com registration fixing tools from NVDA tools menu. 
I also tried restarting. but nothing works. 
no idea what to do.
even, I tried reinstalling my graphics driver in hope that you will fix the issue.  but my issue doesn't resolved. 
but JAWS works fine. it doesn't have issue. 
please help me.
