### ISSUE TITLE
NVDA does not narrate comboboxes on web pages

### ISSUE THREAD

**Issue by bvancea** [nvaccess/nvda#8719]
### Steps to reproduce:

1. Open Firefox
2. Access the [ARIA Combobox pattern examples](https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html) .
3. Use DOWN arrow to navigate between elements on the page

### Actual behavior:
NVDA goes through the elements on the page, but it jumps over the combobox widgets. Pressing C does not move to the combobox, and NVDA says "No next combobox". Navigating with TAB does move focus to the combobox though.

### Expected behavior:

At one point NVDA navigation should reach a combobox widget and say narrate the fact that a combobox exists. Additionally, pressing C should move the focus to the combobox.

### System configuration:
Windows 10

#### NVDA Installed/portable/running from source:
Installed.
#### NVDA version:
2018.2.1
#### Windows version:
Version 1803 (OS Build 17134.67)
#### Name and version of other software in use when reproducing the issue:
Firefox, 61.0.2 (32 bit)
#### Other information about your system:
N/A
### Other questions:
N/A
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No.

**Comment by leonardder** [comment]
cc @michaeldcurran @jcsteh @marcozehe

**Comment by Brian1Gaff** [comment]
I just tested this on the add ons page and c definitely goes to a combo box 
in Waterfox, so if Firefox does not then its got something to do with 
firefox.
https://addons.nvda-project.org/index.en.html


Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by MarcoZehe** [comment]
Firefox exposes them, and I can interact with them if not using browse mode.

**Comment by Brian1Gaff** [comment]
Actually those on the demo page are merely clickables and do not reveal they 
are a combo box unless you click them. I thought this was normal behaviour?

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by leonardder** [comment]
[**@MarcoZehe**](https://github.com/MarcoZehe) commented on [5 sep. 2018 12:13 CEST](https://github.com/nvaccess/nvda/issues/8719#issuecomment-418677355 "2018-09-05T10:13:34Z - Replied by Github Reply Comments"):
> Firefox exposes them, and I can interact with them if not using browse mode.

Really looks like they are exposed differently though. Note that Chrome also fails.

**Comment by jcsteh** [comment]
These combo boxes have a text box child, similar to editable combo boxes in Windows such as the File Name field in the standard browse for file dialog. They also don't have a value, nor are they directly focusable. NVDA's Gecko code assumes combo boxes will have a value and thus don't need children to be rendered.

The Gecko vbuf backend needs to be taught to render children for combo boxes in this case. The tricky question is how to determine when this should be done. The reason we don't currently render children is that we don't want the list box child of a `<select>` to override its value. The logical thing is to render children if the first child is a text box, but that's tricky to do within the current code, as we don't have the children yet when we make that determination.

**Comment by Adriani90** [comment]
@bvancea I cannot reproduce this issue in Firefox 71 with NVDA 2019.3 Beta 1. Are you still seeing this issue?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since many years. I am closing as abandoned.
