### ISSUE TITLE
Provide the ability to search for a setting to change

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#872]
**Reported by etman98 on 2010-09-01 21:52**
Hello,
     I don't always like going into the NVDA Menu every time to change a setting.  If I want to change the synthasizer then connect a braille display I have to go to the synthasizer dialog then when done, go back into the NVDA Menu go to preferences, then go to braille settings.  Could you turn the NVDA Menu into a dialog with a menu bar & search box to search for a setting to change?

Thanks!

**Comment by leonardder** [comment]
This is a nice follow up for #577.

**Comment by bdorer** [comment]
Now #577 has been included this would be a nice feature for 2019.2.

**Comment by leonardder** [comment]
I'm afraid this is much more complex than you may think. @feerrenrut once proposed a major change to the way the setting gui is created from a code perspective, and I think such a major change would be required to implement this effectively.

**Comment by feerrenrut** [comment]
Yes, there are quite a few challenges to do this. There is of course the technical challenge of how to go from what we have now to what would be required to implement this feature. There are also a lot of UX challenges. To progress this issue, I think it would be good to see a minimal prototype.  I would suggest implementing this prototype with as little of the baggage in the NVDA GUI as possible, then as a secondary consider how to go from what we have to this approach.

Some UX to consider:
- How do you present the matching settings?
  - Consider visual, speech, braille.
  - Most settings rely on their context (the settings panel name / grouping) to convey a clear description of what they are for.
  - When there are several matching settings in multiple panels how do you present them both and their context?
- Often people want to to change other "nearby settings". For instance, voice and speech rate.

I have some initial ideas, but I have not worked through them to see if they are feasible:
* Highlight matches, and use F3 / Shift + F3 to jump focus.
  - All panels / options remain available to receive focus / be changed
  - Panels with matching options are visually highlighted, options that match are visually highlighted.
  - F3 can be used to jump focus to the matching options. The name of the control, followed by any group it is in and it's panel name are also reported (speech and braille)
  - Might be challenging to be able to visually highlight options.
* Use the searchCtrl in wx, fill the dropdown menu with "Control name - group name - panel name"
  - Selecting one of the items in the drop down jumps focus direct to that control.
  - F6 or some other key can be used to return focus to the searchCtrl to select another item in the list.
  - Could be done in conjunction with highlighting matches and using F3 to jump focus.
* Show a new settings panel, with just the matching controls (these could be in groups to identify the settings panel and group)
  - Doesn't allow for changing "nearby settings"

**Comment by Gene703122** [comment]
the discussion appears to me to be a case of trying to do too much.  Not being a programmer, this might not be practical but here is my modest proposal:
Why not leave the interface the same but have a search field at the top so the user would be dealing with something very familiar, an interface like the start menu search.  the user would open preferences and be in an edit field.  He/she could type something like speech and down arrow to see a list of relevant results, which could be worked with such as speed, pitch, etc.  You would press enter and be taken to the field you want to work with.  You would be in exactly the same place as if you had moved their directly.  You would work with the slider or do whatever you would do if you got their without using search.  

You would be in exactly the same place in the dialog and you would activate the ok button in exactly the same way or you would tab or shift tab to work with other settings in the dialog.  

Perhaps the search could be made more specific.  The user might type pitch, down arrow and find pitch in the list and press enter.  The user would then be on the pitch slider.  The same with speed or whatever else is available in the dialog.  

Gene

**Comment by josephsl** [comment]
Hi,

That's what I would imagine would be the case (perhaps that might be the UI a potential prototype might present)... except we need to be more specific about implementation strategy. Reef provides some thoughts about implementation strategy (see his notes above for details), but to siplify it a bit, it reuqires working with a combination of wxPython features and the capability NVDA provides.

Thanks.

**Comment by feerrenrut** [comment]
@Gene703122 one issue here is there are different kinds of matches.

Let's imagine the results for the search term "speech"
- "speech settings panel" (which contains many controls)
- "Speech interrupt for typed characters " - Keyboard  property page

The user may be trying to find a specific configuration control like "Speech interrupt for typed characters ", or just a shortcut to the speech settings panel. If all of the config controls from the speech settings panel are included (speed, pitch, voice, etc) it will be slow to find other "primary" search results such as "Speech interrupt for typed characters".

If the contents of matching groups or panels are excluded, but a way to jump directly to that settings panel or group is included, this is basically the [second suggestion I made](https://github.com/nvaccess/nvda/issues/872#issuecomment-475325576) (quoted here for reference):

>* Use the searchCtrl in wx, fill the dropdown menu with "Control name - group name - panel name"
>   - Selecting one of the items in the drop down jumps focus direct to that control.
>   - F6 or some other key can be used to return focus to the searchCtrl to select another item in the list.
>   - Could be done in conjunction with highlighting matches and using F3 to jump focus.

I would now adjust this, last time I tested the `searchCtrl` it was not very accessible, we could use a more basic control instead.

**Comment by Kanwar5** [comment]
Just bumping this thread.
I think despite the immense technical challenges, it’s an idea worth considering.
iOS has a feature similar to this, in the settings or by using spotlight search you can type in a keyword and everything associated with it will be brought up but I appreciate it’s not quite as easy when you’ve got a desktop to work with.

**Comment by marrie** [comment]
I would also like to see this for the following reasons:

-   First, the sheer number of settings in NVDA. As a new beginner things can seem overwhelming at first.
-   Second, on most other platforms, windows included, there is a search function when you tab.
-   Third and finally, as an advanced user it would be nice to type in a keyword or 2 and have a reduced list of settings to search through, things in the tree could be filtered per your search results as well, probably in theory.

Thanks.  
That should be one of the first things in tab order, visually it could be at the top center just above the tree view to make it prominent.

**Comment by Adriani90** [comment]
It seems here are no really clear UX proposals for this appart from the initial description. The proposal of adding a search feature to the settings GUI is now being followed with current practical work in #16500 and #16502.
I am closing this issue in fvor of the new one.
