### ISSUE TITLE
Generate a bug in the developer documentation using scons devDocs

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#8723]
Hello, I found the following documentation in the process of generating developer documentation with visual studio and scons devDocs. Here is my operation log:
C:\Users\dpy>cd C:\Users\dpy\source\repos\nvda
C:\Users\dpy\source\repos\nvda>scons devDocs
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Converting developerGuide.t2t to html
txt2tags wrote developerGuide.html
Move("output\devDocs\developerGuide.html", "developerGuide.html")
cd source && C:\Python27\python.exe -c "import sourceEnv; from epydoc.cli import cli; cli()" --output C:\Users\dpy\sourc
e\repos\nvda\output\devDocs\nvda --quiet --html --include-log --no-frames --name NVDA --url https://www.nvaccess.org/ *.
py appModules brailleDisplayDrivers comInterfaces\__init__.py config contentRecog extensionPoints globalPlugins gui math
Pres NVDAObjects speechDictHandler synthDrivers textInfos virtualBuffers
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\api.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name '_' is not defined (line 10)
|
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\appModuleHandler.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name '_' is not defined (line 27) 
|
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\aria.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name '_' is not defined (line 7)
|
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\audioDucking.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name '_' is not defined (line 34)
|
Warning: Unable to extract the base list for bdDetect.DeviceMatch: Bad
dotted name
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\bdDetect.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name 'pgettext' is not defined (line 21)
|
+--------------------------------------------------------------------- 
| In C:\Users\dpy\source\repos\nvda\source\braille.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name 'pgettext' is not defined (line 17)
|
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\brailleInput.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name '_' is not defined (line 11)
|
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\brailleTables.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name '_' is not defined (line 86)
|
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\browseMode.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name 'pgettext' is not defined (line 14)
| 
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\characterProcessing.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name 'pgettext' is not defined (line 128)
|
Warning: Unable to extract the base list for colors.RGB: Bad dotted
name
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\colors.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name 'pgettext' is not defined (line 107)
|
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\compoundDocuments.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name '_' is not defined (line 8)
|
Warning: Unable to extract the base list for
comtypes._compointer_meta: Bad dotted name 
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\controlTypes.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name '_' is not defined (line 202)
|
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\cursorManager.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name 'pgettext' is not defined (line 14)
|
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\displayModel.py:
| Import failed (but source code parsing was successful).
|     Error: NameError: name 'pgettext' is not defined (line 12)
|
+---------------------------------------------------------------------
| In C:\Users\dpy\source\repos\nvda\source\documentBase.py:
| Import failed (but source code parsing was successful).
Warning: 66 markup errors were found while processing docstrings.  Use
the verbose switch (-v) to display markup errors.
scons: done building targets.
Because the error log is really too much, so the above is part of my extract, the error implementation method is in my operation log. thank

**Comment by dingpengyu** [comment]
I want to report a bug that uses the (scons devDocs) to generate the developer documentation. Here are the steps I took.

**Comment by derekriemer** [comment]
What is the bug? I understand your steps. Does the build fail? These errors are probably related to NVDA having a lot of custom metaclasses and other things the autogenerator cannot handle.

**Comment by dingpengyu** [comment]
The build was successful, but the above mistakes were uncomfortable.

**Comment by derekriemer** [comment]
I don't think these name errors cause any problems, and are basically caused by empty lines in our code or something. If anyone has any further info for the errors cause, please open another issue and we can try to resolve them.
