### ISSUE TITLE
Upgrade BrlAPI from version 0.5.3 to the most recent version

### ISSUE THREAD

**Issue by tiago-casal** [nvaccess/nvda#8725]
Would the upgrade BrlAPI from version 0.5.3 (from 2010, BrlTTY 4.2) to version 0.6.2 (from 2014, BrlTTY 5.1) bring NVDA benefits, since version 0.6.2 is still available for Python 2.7 bindings for Windows?
In addition to updating the DLLs, such as brlapi-0.5.dll to brlapi-0.6.dll, would prepare the path for when NVDA is updated to Python 3, since from BrlTTY 5.2 Python 3 bindings is used but BrlAPI remains in the same series 0.6 .. .
Link to BrlTTY 5.1 package for Windows with BrlAPI 0.6.2, Python 2.7 bindings: http://brl.thefreecat.org/brltty/brltty-win-5.1-1.zip

**Comment by leonardder** [comment]
The last time I tried, the old binding still worked with the newest version of brltty. I'd like to suggest holding this back until NVDA uses Python 3, and than update to the most recent bindings in the transition process.

**Comment by Adriani90** [comment]
Newest Version of BRLAPI is 0.6.7 and I suggest to update to that Version.
https://github.com/brltty/brltty-website/blob/master/home/doc/ChangeLog.txt

There is a Python 2 and a Python 3 package.
Python 2:
https://fedora.pkgs.org/28/fedora-x86_64/python2-brlapi-0.6.7-5.fc28.x86_64.rpm.html

Python 3:
https://fedora.pkgs.org/28/fedora-x86_64/python3-brlapi-0.6.7-5.fc28.x86_64.rpm.html

These are for BRLTTY 5.6.

**Comment by Adriani90** [comment]
cc: @bramd, @michaelDCurran

**Comment by leonardder** [comment]
@jcsteh: Do you recall how the original brlapi that is now in miscdeps has been build. Is this a custom build, or does it originate from a particular official brltty build?

**Comment by jcsteh** [comment]
It was extracted from the BRLTTY build. See the commit message for nvaccess/nvda-misc-deps@d806058f6ce1627d for details.

**Comment by leonardder** [comment]
I just wrote to the BRLTTY mailing list, see [this post](https://brltty.app/pipermail/brltty/2019-June/016715.html).
I'd really prefer an official build from the BRLTTY project.

**Comment by josephsl** [comment]
Hi,

Major showstopper for #9720 and #9721, more so for the latter because MSVC error is thrown.

Note that 0.7 ships with Python 3.6 pyd, which means we do need a Python 3.7 binding for 0.7 that will not add msvcr90.dll to path (see #9721 for details).

Thanks.

**Comment by leonardder** [comment]
Despite several posts on the brltty mailing lists, I haven't received any response on my query for assistance on building the Python bindings on Windows. I did a follow up message.

**Comment by leonardder** [comment]
Updated to version 0.7.0 in #9812. Note that threshold_py3_staging does not yet contain a brltty driver that is compatible with Python 3.
