### ISSUE TITLE
NVDA 2018.3 beta 4 hangs during braille translation

### ISSUE THREAD

**Issue by jasonjgw** [nvaccess/nvda#8729]
### Steps to reproduce:
* Visit certain Web pages (e.g., https://www.voip-info.org/stun) in Google Chrome and use the down-arrow key to read through the text.
### Actual behavior:
NVDA hangs and must be restarted. I haven't found another means of recovering. The following appears in the logs:

```
DEBUGWARNING - watchdog._watcher (16:17:58.177):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 481, in run
  File "braille.pyo", line 2131, in pumpAll
  File "braille.pyo", line 1873, in handlePendingCaretUpdate
  File "braille.pyo", line 1879, in _doCursorMove
  File "braille.pyo", line 1008, in update
  File "braille.pyo", line 427, in update
  File "louis\__init__.pyo", line 157, in translate

WARNING - watchdog._watcher (16:18:13.220):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 481, in run
  File "braille.pyo", line 2131, in pumpAll
  File "braille.pyo", line 1873, in handlePendingCaretUpdate
  File "braille.pyo", line 1879, in _doCursorMove
  File "braille.pyo", line 1008, in update
  File "braille.pyo", line 427, in update
  File "louis\__init__.pyo", line 157, in translate

DEBUGWARNING - RPC process 11964 (nvda_slave.exe) (16:18:20.325):
Python warning:
C:\Program Files (x86)\NVDA\library.zip\configobj.py:28: DeprecationWarning: The compiler package is deprecated and removed in Python 3.x.
```

### Expected behavior:
Reading of the text, and simultaneous braille translation, without a hang.
### System configuration:
NVDA installed under Windows 10 1803 build 17134.254, x64. Contracted braille enabled (US English Grade II)
#### NVDA Installed/portable/running from source:
installed.
#### NVDA version:
2018.3 beta 4, also seen under beta 3, which was the first beta of 2018.3 that I tried.
#### Windows version:
Windows 10 1803 version 17134.254
#### Name and version of other software in use when reproducing the issue:
Chrome 69 - also experienced under chrome 68.
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
I don't think I encountered this issue under 2018.2.1.

**Comment by leonardder** [comment]
Could you please verify again whether this happens under NVDA 2018.2.1? Also, what braille display are you using?

**Comment by jasonjgw** [comment]
I ran the NVDA 2018.2.1 installer, and chose the "continue running" option (i.e., continuing to run without overwriting my installation). I was then still able to reproduce the issue.

This was tested with a VFO Focus 40 Blue, 5th generation display with the Freedom Scientific/VFO driver installed.

**Comment by leonardder** [comment]
DO you by any chance have another display to test with?

**Comment by jasonjgw** [comment]
Yes, I have a Baum SuperVario 40 that would use a different driver from the VFO display. The Baum display needs a clean, due to sticking pins, but that shouldn't affect this test at all. It may be Sunday or early next week before I'll have time to work on it.

**Comment by jasonjgw** [comment]
Unfortunately, NVDA 2018.3.1 failed to detect the Baum display either when I selected "automatic" or Baum as the braille display type.

Mac/VoiceOver and Linux/BRLTTY both work fine with this display.

So, for the moment, I'm limited to testing with Freedom Scientific devices until the issue with the Baum device is resolved. I'm still seeing the hangs, as described, in 2018.3.1 - on various Web pages or occasionally while editing.

**Comment by leonardder** [comment]
[**@jasonjgw**](https://github.com/jasonjgw) commented on [26 Sep 2018, 01:59 CEST](https://github.com/nvaccess/nvda/issues/8729#issuecomment-424540271 "2018-09-25T23:59:27Z - Replied by Github Reply Comments"):
> Unfortunately, NVDA 2018.3.1 failed to detect the Baum display either when I selected "automatic" or Baum as the braille display type.

Are you able to use your display with 2018.2.1 just fine?

**Comment by bramd** [comment]
@jasonjgw Could you try this build with your Focus display: https://ci.appveyor.com/api/buildjobs/qqr2tq2m3ncljmfy/artifacts/output%2Fnvda_snapshot_pr1234-6%2C2194af16.exe

It is not signed and might give a warning on opening it and I don't recommend to install this build. This contains a rewritten Freedom Scientific braille driver that might solve your issue.

**Comment by jasonjgw** [comment]
I can confirm that the snapshot works with my display. Unfortunately, some functionality (e.g., browse mode in Google Chrome) is not working, which makes it difficult to test this build extensively in my daily work.

When there's a version incorporating the rewritten driver that is more stable, I'll do more extensive testing to try to reproduce the issue.

**Comment by bramd** [comment]
@jasonjgw Thanks for your feedback. Browse mode in Chrome should work with this build, it might be necessary to restart Chrome after starting this NVDA build. Please have a look at PR #8853 for the latest builds with this driver.

**Comment by jasonjgw** [comment]
I didn't spend much time on it. My plan at this point is to download the next snapshot or beta with the driver included and test again.

**Comment by dkager** [comment]
Please do that so we know:
* if this issue still exists at all; and
* if the Focucs driver is the cause.
