### ISSUE TITLE
table navigation: add a new reference value, so that NVDA can remember the last cell coordination before the cursor was moved into a merged cell

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#8730]
In a table with merged-cells, sometimes, NVDA do not have access to move to next column correctly.

## Steps to reproduce:
1. Open link
https://www.cht.com.tw/zh-tw/home/cht/messages/2018/msg-180830-142700
2. Press t twice to move to second table.
3. Press Ctrl + Alt + rightArrow to move to r1 c2.
4. Press Ctrl + Alt + downArrow to move to r8 c2.
5. Press Ctrl + Alt + rightArrow to move to r8 c4.
speech: (row 2 through 8, column4) 95%
6. Press Ctrl + Alt + rightArrow
### Expected behavior: 
speech: (row 8 column 5) 443
### Actual behavior:
speech: (row 2 column 5) 324

### System configuration:
Windows version: Windows 7 (6.1.7601 service pack 1)
NVDA version: 2018.2.1
NVDA Installed or portable: installed
Google Chrome: 68.0.3440.106
Mozilla Firefox: 61.0.2

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA?
2018.1, 2018.3 beta3

**Comment by Adriani90** [comment]
cc: @jcsteh, @leonardder

**Comment by surfer0627** [comment]
This issue is covered by #13345.

**Comment by Adriani90** [comment]
Closing as fixed by #13345. Thanks @seanbudd and @mltony for the great work on this.
