### ISSUE TITLE
NVDA say nothing when open start menu's context menu in Windows 10

### ISSUE THREAD

**Issue by manhcuong0312** [nvaccess/nvda#8733]
When pres Application key at a folder in file Explorer, or a shortcut on Desktop, NVDA usually says: context menu but not the same in Windows 10 Start menu. After pressing, we can press arrow key to explorer the menu, but it would be better if NVDA says: context menu. This make people who beginner of learning computer feel easier.
Found this issue when teaching basic computer on desktops using Windows 10 64 bit v 1803, NVDA 2018.2.1. This stil occurs on my laptop running the same OS with NVDA 2018.3rc1.

### Steps to reproduce:
Open start menu, search for a program such as wordpad and press Application on the shortcut.
### Actual behavior:
NVDA does not say anything.
### Expected behavior:
Should say context menu, or a message announce that.
#### NVDA Installed/portable/running from source:
Install
#### NVDA version:
2018.2.1, 2018.3rc1
#### Windows version:
Windows 10 pro 64 bit, v 1803
#### Does the issue still occur after restarting your PC?
Yes its always occurs
#### Have you tried any other versions of NVDA?
no.

**Comment by josephsl** [comment]
Hi, this is because selection event is fired immediately after context menu appears. CC @MichaelDCurran

**Comment by Brian1Gaff** [comment]
I've also noticed its saying context  and that is all in 7, has there been 
some textual changes?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by dkager** [comment]
When you start arrowing up/down through the menu, NVDA reads the selected menu item. So it is only the selection when the menu first opens that is not announced.

**Comment by josephsl** [comment]
Hi,

August 2021 update: when you do open context menu for a suggestion in Start screen (this is on Windows 10 Version 21H2, by the way), NvDA Will say "context menu", which is better than last time this issue had an update.

Thanks.
