### ISSUE TITLE
Toggling aria-hidden on parent element of an aria-hidden element causes child attribute to be ignored

### ISSUE THREAD

**Issue by julesongithub** [nvaccess/nvda#8736]
This happens in Windows 10 Internet Explorer 11 and Firefox (56.0.2) but not Chrome, with the latest version of NVDA (2018.2.1).

If we have this HTML:

```
<div id="hide-this">
    <p aria-hidden="true">Some aria-hidden text</p>
</div>
```
...and we set #hide-this to [aria-hidden="true"] and then remove the attribute, the child element is not hidden anymore.

I have some example code with a button that simply toggles the attribute of #hide-this

https://jsfiddle.net/julesonjsfiddle/vu38x5f7/embedded/result/

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"
            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
            crossorigin="anonymous"></script>
</head>
<body>
    <button id="btn-toggle" type="button">Hide</button>
    <div id="hide-this">
        <p aria-hidden="true">Some aria-hidden text</p>
    </div>
    <script>
        var hidden;
        $(function () {
            $('#btn-toggle').on('click', function () {
                if (hidden) {
                    $('#hide-this').removeAttr('aria-hidden');
                }
                else {
                    $('#hide-this').attr('aria-hidden', true);
                }
                hidden = !hidden;
                $(this).text(hidden ? 'Show' : 'Hide');
            });
        });
    </script>
</body>
</html>
```

**Comment by leonardder** [comment]
Would you be able to test this in Edge and Firefox 63 beta? See [this post](https://www.marcozehe.de/2018/07/24/firefox-63-will-cut-subtrees-marked-with-aria-hidden/) by @marcozehe

**Comment by julesongithub** [comment]
> Would you be able to test this in Edge and Firefox 63 beta? See [this post](https://www.marcozehe.de/2018/07/24/firefox-63-will-cut-subtrees-marked-with-aria-hidden/) by @MarcoZehe

You reminded, i missed out an important detail in my post (now add) - for JAWS 18 compatibility reasons, I'm using Firefox 56.0.2.

I'll try Edge and FF 63 on another computer

**Comment by leonardder** [comment]
Hmm, I wonder whether we should consider patching the MSHTML vbuf back-end to make the behaviour identical to the other browsers (i.e. cut the subtree of aria-hidden elements). Before Mozilla decided to change their behaviour, it made sense not to do this, but now it seems that IE is being the only different browser here.

**Comment by leonardder** [comment]
cc @michaeldcurran

**Comment by Brian1Gaff** [comment]
I do not understand this issue, but as a significant number of people seem 
to now be using waterfox, might be worth seeing what it does also.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment]
IE is discontinued since years and the software has been removed automatically from Windows machines via an Edge update. Firefox and chromium seem to work properly with NvDA 2024.1 Beta 6.
I don't expect any further accessibility updates to IE, so i am closing this as abandoned.
