### ISSUE TITLE
google chrome crash with nvda

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#8737]
hello all.

in some specific cases, google chrome is crashing when nvda is running.

navigate to a page
https://www.howtoforge.com/tutorial/install-apache-with-php-and-mysql-on-ubuntu-18-04-lamp/
when nvda is running, and navigating page, google chrome is crashing.

it doesn't happen when narrator is running.

**Comment by DrSooom** [comment]
Please give us more information about your system and software (including version) by completely filling out the draft. Thanks.

**Comment by beqabeqa473** [comment]
hi.

latest alpha of nvda, windows 10 1803 and latest insider build 64 bit.
google chrome 64 bit.

2018-09-13 14:48 GMT+04:00, Daniel Mayr <notifications@github.com>:
> Please give us more information about your system and software (including
> version) by completely filling out the draft. Thanks.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/8737#issuecomment-420965691


-- 
with best regards beqa

**Comment by PratikP1** [comment]
I have not been able to duplicate this on the latest NVDA alpha as well as the latest version 2018-3 release candidate. I am running Chrome Canary.

**Comment by beqabeqa473** [comment]
hi.

very strange, it was crashing on three different computers, but when i tried it today, it worked well.
