### ISSUE TITLE
Reading of blank lines in html webpages

### ISSUE THREAD

**Issue by eltonfreak** [nvaccess/nvda#8747]
Steps to reproduce:
run NVDA.
Load local file or webpage with rellivant code into firefox or internet explorer.
Actual behavior:
when encountering `<p>` or `</p>` it skips them and when using down and up arrow it reads each line without saying blank for the space.
When encountering `<br>` or `<br/>` it reads the blank line, between sections of text or links.
Expected behavior:
I would like to be able to make NVDA ignore blank lines with the `<br>` or `</br>` atribute as it already does for `<p>` and `</p>`
System configuration:
Addons:
Eloquence
clipspeek
Extended aria atributes
Goldwave
ExtendedWinamp
NVDA Installed:
Full harddisk install
NVDA version:
2018.2
Windows version:
Desktop, 7 (service pack 1)
Laptop, 10 (1803)
Name and version of other software in use when reproducing the issue:
Firefox 52.9 (ESR)
Other information about your system:
HP and Dell
Other questions:

Does the issue still occur after restarting your PC?
Allways
Have you tried any other versions of NVDA?
all of them

[Test.zip](https://github.com/nvaccess/nvda/files/2380497/Test.zip)

**Comment by ehollig** [comment]
I know @derekriemer worked on creating an initial implementation of this in #6704. Maybe he can speak about this.

**Comment by Adriani90** [comment]
This is a new feature in jaws, they seem to be able to filter blank lines in browsers since Jaws february 2020 update.
However, this issue is already covered actually in #4904. Closing.
Let's continue the discussion on #4904.
