### ISSUE TITLE
Unexpected reading of console output

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#875]
**Reported by tspivey on 2010-09-02 22:28**
There are two instances I've found so far where characters are read unexpectedly in console windows:
1. When echo characters is on and read dynamic content is off, the following at a Cygwin bash prompt will echo characters until ^c is pressed:
   while :;do seq 1 100;done
   This doesn't happen when character echo is off.
2. When read dynamic content is on and regardless of the character echo setting, the first character typed on a line will speak if there's nothing else on that line. E.g. starting to type an ed command.

**Comment by frastlin** [comment]
When echo characters is on in Windows 10, the last line is spelled out in the console. So for example, when I am  on my user dir it says:
c : \ u s e r s \ b r a n d o n >
C:\users\brandon>

one right after another. I do not remember this happening in windows 7.
It should just read the second line.

**Comment by leonardder** [comment]
cc @tspivey

**Comment by Adriani90** [comment]
@tspivey can you still reproduce this in NVDA 2019.2 RC2? @codeofdusk does your highly appreciated work on console improvements with UIA solve this issue?

**Comment by codeofdusk** [comment]
> @tspivey can you still reproduce this in NVDA 2019.2 RC2? @codeofdusk does your highly appreciated work on console improvements with UIA solve this issue?

Is this a duplicate of #513?

**Comment by Adriani90** [comment]
@codeofdusk that issue was partly a duplicate.
@tspivey how is the behavior now in NVDA 2020.1 Beta?

**Comment by Adriani90** [comment]
Does anyone have an update wether this issue still occurs in last NVDA alpha?

**Comment by codeofdusk** [comment]
This is a duplicate of #513 (fixed in 2019.3).

**Comment by Adriani90** [comment]
Closing as works for me. Thanks for the update.
