### ISSUE TITLE
new nvda crashes with firefox

### ISSUE THREAD

**Issue by vortex1024** [nvaccess/nvda#8759]
### Steps to reproduce:
1. open fireffirefox and go to any website

### Actual behavior:
firefox crashes 
### Expected behavior:
site should load
### System configuration:
core i7, 6 gb ram, ssd, windows 10
#### NVDA Installed/portable/running from source:
installed
#### NVDA version:
2018.3
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
firefox 60.0.2
#### Other information about your system:
relevant log fragment:
ERROR - virtualBuffers.VirtualBuffer._loadBuffer (16:58:22.427):
Traceback (most recent call last):
  File "virtualBuffers\__init__.pyo", line 417, in _loadBuffer
WindowsError: [Error 1726] The remote procedure call failed
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
yes, it works with 2018.2

**Comment by PratikP1** [comment]
Could you try to upgrade to Firefox 61 and see if the problem still occurs?

**Comment by Brian1Gaff** [comment]
I've seen a couple of these on the nvda list, one might be this person but 
at least on of the users is using firefox 62, but i did not recognise the 
number of the windows 10. For the record, none of the quaantum firefoxes has 
ever worked on my windows 7 machine, it fails to create a buffer at all.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by DrSooom** [comment]
I wasn't able to reproduce this issue with NVDA 2018.3 Portable on Win7x64 with Firefox 56.0.2 (installed), Firefox 61.0.2 (portable) and Firefox 62.0 (portable). so please update Firefox from 60.0.2 to 62.0 first and report your results here.

If there are still crashes, please enter "about:support" in the address bar and search for section "Accessibility". Firefox 62.0 should list NVDA here.

**Comment by leonardder** [comment]
1. Have you restarted your system since you installed NVDA 2018.3?
2. Are you using a 32 or 64 bit version of firefox? Should be mentioned in help>about firefox?

**Comment by leonardder** [comment]
My colleague also reported this with Firefox 62. I'm going to investigate this further on his system, but I'm afraid that this should be considered very crytical.

**Comment by vortex1024** [comment]
Updated to firefox 62 x64 and it works. Restarting didn’t help, nor could I find NVDA in the about:config accessibility section. I still believe NVDA should work with 32 bit firefox on 64 bit windows, or at least mention that it doesn’t in the release notes.

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by ruifontes** [comment]
Yes, it works alright...

I have Firefox 62 32-bit version in Windows 10 64-bit with NVDA 2018.3 
or last Alpha version, and all is working without any problems...

And in the portuguese language comunity no one have problems yet...

Rui Fontes


Às 12:14 de 19/09/2018, vortex1024 escreveu:
