### ISSUE TITLE
the reduce function when playing speech and sound is not working

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8769]
### Steps to reproduce:
In nvda change the priority audio option to reduce when playing speech and sounds
Now play some sound.
### Actual behavior:
When setting the nvda to reduce when playing speech and sounds, nvda decreases the audio of the song, but the volume of the song does not return to the normal volume when nvda ends the speech.
When setting up nvda to do nothing, or forever reduce everything is as expected.
### Expected behavior:
the sound of the music playing must go down when the nvda utters something.
The sound should return to normal volume when nvda ends the speech.
#### NVDA Installed/portable/running from source:
install

#### NVDA version:
alfa 16026
#### Windows version:
10 17134.285
#### Name and version of other software in use when reproducing the issue:
the sound card of this notebook is:
Independent headphones; IDT High Definition Audio CODEC; Standard Device
I am using the sapi mobile synthesizer and also did test using the nv spich and speak
and the problem was the same.
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by leonardder** [comment]
I can not teproduce this issue on the same build of Windows 10 as you are using. Can you reproduce this with NVDA 2018.3.1 as well?

**Comment by fernando-jose-silva** [comment]
sorry, I discovered the reason for the problem, had in the nvda an old addom still installed, after removing it all returned to normal:
the addom calls new sapi voice if I remember correctly.

**Comment by leonardder** [comment]
Ok, thanks for clarifying.
