### ISSUE TITLE
NVDA crashes when quitting with Tiflotecnia Vocalizer add-on enabled

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#8770]
### Steps to reproduce:
1. On Windows 7, install the Tiflotecnia Vocalizer 2.0.2 add-on along with one or more voices
2. Quit NVDA.

### Actual behavior:
A critical NVDA crash occurs, and NVDA restarts itself/

### Expected behavior:
NVDA quits normally

### Technical background
The Vocalizer add-on adds a submenu item to the NVDA menu, but never destroys the particular item. This causes a crash when gui.terminate() is called after globalPluginHandler.terminate()

This can be fixed by explicitly destroying the submenu item. However, the reason why I file this as an NVDA issue is that it really concerns me that an add-on can make NVDA crytically crash like this. Also, this never happened before we used WX Python 4.

I have a [crash dump](https://github.com/nvaccess/nvda/files/2405345/nvda_crash.zip) and a [log file](https://github.com/nvaccess/nvda/files/2405347/nvda-old.log).

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
Both 2018.3.1. and alpha-16078

#### Windows version:
Windows 7 SP1

#### Name and version of other software in use when reproducing the issue:
N/A

#### Other information about your system:
Reproduced on both a VM as well as 3 stand alone systems. Always Windows 7 until now.

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes

**Comment by leonardder** [comment]
cc @michaeldcurran and @josephsl 

I gave this a p2 to investigate further whether this issue is somehow caused by NVDA doing something wrong as well.

**Comment by josephsl** [comment]
Hi, ah, the add-on in question looks for PyDeadObjectError, which exists in wxPython 3 (Classic). In Phoenix, one must handle RuntimeError. Thanks.

**Comment by Brian1Gaff** [comment]
Does the same thing happen on a restart after any update or add on update?
I myself do not have these voices but I guess we might encounter this with 
add ons which have not been updated if modified without proper testing 
first.

 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by ruifontes** [comment]
So far, that do not cause any error or warning...

Rui Fontes
Tiflotecnia, Lda.


Às 14:12 de 21/09/2018, Joseph Lee escreveu:

**Comment by Brian1Gaff** [comment]
Maybe the effect only occurs if one thing closes before another or something 
like that?

I guess the only way to stop it is to change the code to make sure it cannot 
occur.
Brian
bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by leonardder** [comment]
Every add-on is responsible for cleaning up their own changes to the NVDA menu. In these add-ons, this is not the case, i.e. on termination of the plugin, it only removes the menu item from the menu and doesn't destroy it.

**Comment by ruifontes** [comment]
Hello!

Published a corrected driver, 2.0.3, available directly in:
http://www.tiflotecnia.net/Instal/vocalizer-driver-2.0.3.nvda-addon

Thanks to Leonard!

Best regards,

Rui Fontes
Tiflotecnia, Lda.

Às 13:42 de 21/09/2018, Leonard de Ruijter escreveu:

**Comment by leonardder** [comment]
<details>
<summary>Stack dump created by @michaeldcurran</details>
<pre>
# ChildEBP RetAddr
WARNING: Frame IP not in any known module. Following frames may be wrong.
00 0012f688 02372826 0x4d787700
01 0012f6a8 022d48fc wxmsw30u_core_vc90!wxMenuItemBase::~wxMenuItemBase(void)+0x46 [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\ext\wxwidgets\src\common\menucmn.cpp @ 280]
02 0012f6c8 022d4d80 wxmsw30u_core_vc90!wxMenuItem::~wxMenuItem(void)+0x8c [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\ext\wxwidgets\src\msw\menuitem.cpp @ 513]
03 0012f6d4 101a5146 wxmsw30u_core_vc90!wxMenuItem::`vector deleting destructor'(void)+0x40
04 0012f6e4 00388cb0 wx__core!dealloc_wxMenuItem(struct _sipSimpleWrapper * sipSelf = 0x0404aad0)+0x46 [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\sip\cpp\sip_corewxmenuitem.cpp @ 1758]
05 0012f6f4 0038aaea wx_siplib!forgetObject(struct _sipSimpleWrapper * sw = 0x02ab5f48)+0x90 [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\sip\siplib\siplib.c @ 12032]
06 0012f6fc 6c8aa954 wx_siplib!sipWrapper_dealloc(struct _sipWrapper * self = 0x0404aad0)+0xa [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\sip\siplib\siplib.c @ 11583]
07 0012f724 6c8754d0 python27!subtype_dealloc(struct _object * self = 0x04073390)+0x2b4 [c:\build27\cpython\objects\typeobject.c @ 1050]
08 0012f73c 6c8aa901 python27!dict_dealloc(struct _dictobject * mp = 0x01361440)+0xa0 [c:\build27\cpython\objects\dictobject.c @ 1086]
09 0012f764 6c86e4aa python27!subtype_dealloc(struct _object * self = 0x6ca0a8e0)+0x261 [c:\build27\cpython\objects\typeobject.c @ 1035]
0a 0012f778 100c128f python27!instancemethod_dealloc(struct PyMethodObject * im = 0x02a79e18)+0x6a [c:\build27\cpython\objects\classobject.c @ 2386]
0b 0012f7b0 020fc9db wx__core!wxPyCallback::~wxPyCallback(void)+0x8f [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\sip\cpp\sip_corewxevthandler.cpp @ 45]
0c 0012f7e4 03e0995d wxbase30u_vc90!wxEvtHandler::~wxEvtHandler(void)+0xcb [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\ext\wxwidgets\src\common\event.cpp @ 1154]
0d 0012f820 0202ca8c wxmsw30u_adv_vc90!wxTaskBarIcon::~wxTaskBarIcon(void)+0x7d [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\ext\wxwidgets\src\msw\taskbar.cpp @ 199]
0e 0012f830 0202e267 wxbase30u_vc90!wxAppConsoleBase::DeletePendingObjects(void)+0x3c [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\ext\wxwidgets\src\common\appbase.cpp @ 595]
0f 0012f87c 02300a2c wxbase30u_vc90!wxAppConsoleBase::ProcessIdle(void)+0x67 [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\ext\wxwidgets\src\common\appbase.cpp @ 399]
10 0012f8cc 020541e4 wxmsw30u_core_vc90!wxAppBase::ProcessIdle(void)+0x2c [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\ext\wxwidgets\src\common\appcmn.cpp @ 367]
11 0012f8d0 0205428c wxbase30u_vc90!wxEventLoopBase::ProcessIdle(void)+0x14 [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\ext\wxwidgets\src\common\evtloopcmn.cpp @ 101]
12 0012f8fc 02054445 wxbase30u_vc90!wxEventLoopManual::DoRun(void)+0x5c [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\ext\wxwidgets\src\common\evtloopcmn.cpp @ 197]
13 0012f92c 02030a6a wxbase30u_vc90!wxEventLoopBase::Run(void)+0x85 [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\ext\wxwidgets\src\common\evtloopcmn.cpp @ 78]
14 0012f95c 10212e21 wxbase30u_vc90!wxAppConsoleBase::MainLoop(void)+0x7a [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\ext\wxwidgets\src\common\appbase.cpp @ 334]
15 0012f968 10214dd0 wx__core!wxPyApp::MainLoop(void)+0x31 [c:\projects\buildbots\win7-py27\dist-win32-py27\phoenix\sip\cpp\sip_corewxpyapp.cpp @ 317]
</pre>
</details>

**Comment by leonardder** [comment]
I'm closing this. I've only seen this with Vocalizer, and it can be fixed in the vocalizer for NVDA code. Furthermore, on Alpha, noone is likely to use a version of the add-on that has this issue, as it has been fixed upstream for Vocalizer 2.1 and 3.1.
