### ISSUE TITLE
Remote menu missing from Tools

### ISSUE THREAD

**Issue by tech55541** [nvaccess/nvda#8774]
### Steps to reproduce:
1. Open the NVDA menu.
2. Select Tools
3. Notice the Remote menu is missing.

### Actual behavior:
The Remote menu is missing.

### Expected behavior:
The Remote menu should be accessible under Tools --> Remote.

### System configuration:
Windows 7 Pro x64

#### NVDA Installed/portable/running from source:
Installed to C drive.

#### NVDA version:
Latest.

#### Windows version:
7 Professional

#### Name and version of other software in use when reproducing the issue:
NVDA Remote Add-on: https://github.com/NVDARemote/NVDARemote

#### Other information about your system:
Did not happen in last major release.

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA?
Previous version is not effected.

Please let me know if you need more information.

Thanks, Alex

**Comment by Brian1Gaff** [comment]
Hi you obviously missed the memo!
 I believe there is a blog on this on the nvaccess site and there has been 
much chat about it on the lists.
 Basically, the remote add on needs some minor changes to work with the wx4 
version of NVDA. Joseph did a patch but is reticent about  making it 
official as the authors of the add on, who have no connection with NV access 
say they will bring out an official release.
 So far, and its only been a few days, this has not happened, so if I was in 
your position, I'd keep the latest version as a portable and use the 
previous one with the old version of the Remote add on until either a new 
version comes out, or some agreement is reached to allow official use of the 
patched version.


Note NV access did contact many add on authors when the snapshots of this 
releases started to use Python WX4 for its GUIs, and one may say, though I 
cannot comment, that maybe it should have been fixed then.
 (Hides behind sofa)
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by tech55541** [comment]
Hello,

Thanks.

I edited the python file and it works fine now.

I don't usually follow the email lists, sorry for the quick report.

Closing now.
