### ISSUE TITLE
Randomity of behavior when switching folders in Windows Explorer

### ISSUE THREAD

**Issue by FelixGruetzmacher** [nvaccess/nvda#8788]
### Steps to reproduce:

1. Launch Windows Explorer.
2. Navigate for a while by hitting enter on folders, or leaving folders with backspace.

### Actual behavior:

In most cases, the first element of the folder which was just entered is announced, which is expected and correct. Sometimes, however, NVDA remains silent. Subsequent investigation will then find the navigator object pointing to an object that no longer exists.

If the folder which was just entered happens to be empty, the navigator invariably ends up on a nonexistent object.

### Expected behavior:

If the entered folder is non-empty, the first element should always be announced. If it is empty then something to the effect of "empty list" should be voiced.

#### NVDA Installed/portable/running from source:

Installed.

#### NVDA version:

Version 2018.3.2 (current as of writing).

#### Windows version:

Windows 7, 64 bit.

#### Name and version of other software in use when reproducing the issue:

Probably does not apply.

#### Other information about your system:

Experienced on systems of different speeds.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA?

No.

**Comment by Brian1Gaff** [comment]
I do not think this is particularly new as an issue is it?
 It might be more obvious in windows 10, but I'm pretty sure its been around 
as a quirk for a while.
 I do agree though that  something  a little more verbose for an empty 
folder than silence is probably desirable here.

Brian
bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by FelixGruetzmacher** [comment]
I agree it's probably not new, but I haven't seen it reported before,
presumably because such small idiosyncrasies would slip most people's
radar. The way I am rigged, they attract me as a lightning rod would
electricity.

Am Do., 27. Sep. 2018 um 10:32 Uhr schrieb Brian Gaff <
notifications@github.com>:

**Comment by leonardder** [comment]
Can you also reproduce this with latest Alpha build?

**Comment by FelixGruetzmacher** [comment]
Yes, just reproduced, unfortunately.
I have the feeling it happens less frequently but this is highly subjective.

Am Do., 27. Sep. 2018 um 11:14 Uhr schrieb Leonard de Ruijter <
notifications@github.com>:

**Comment by Brian1Gaff** [comment]
Hi, Of course many people set up explorer as default where it uses the 
window again. I tend to change it to open each explorer folder in a new 
window. That might well be a difference.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by FelixGruetzmacher** [comment]
It just may. I prefer to reuse such windows as otherwise I tend to leave a
string of them dangling behind me as I traverse the file system.

Am Do., 27. Sep. 2018 um 11:56 Uhr schrieb Brian Gaff <
notifications@github.com>:

**Comment by Brian1Gaff** [comment]
Well I tend to like a lot open as I have one task a week where I need to get 
stuff from dropbox in one folder, copy them to a fake disc folder, do 
operations on them, then copy them back to a third dropbox folder and 
occasionally use Goldwave to process one of the files to fix something in 
between. If I had to keep on opening folders I'd already opened every time I 
switched away it would confuse me!
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Adriani90** [comment]
@FelixGruetzmacher can you reproduce this also with NVDA 2020.1?
