### ISSUE TITLE
NVDA prevents copying text when selecting it with the mouse in web browsers

### ISSUE THREAD

**Issue by DataTriny** [nvaccess/nvda#8792]
### Steps to reproduce:
1. Open a web browser (tested with Firefox and Microsoft Edge),

2. Navigate to a page containing some text such as a Wikipedia article for instance,

3. Left click somewhere on the text and start selecting some characters,

4. Release the left button,

5. Press Ctrl+C.

### Actual behavior:
NVDA announces "No selection", and if you try to paste the selected text in a word processing software or a regular text box control, nothing happenes.

### Expected behavior:
The selected text should be copied to the clipboard when pressing Ctrl+C.
Currently if you use a mouse, you are forced to go to the context menu and click "Copy".

#### NVDA Installed/portable/running from source:
NVDA is installed.

#### NVDA version:
NVDA version 2018.3.2.

#### Windows version:
Windows 10 Education, version 1803.

#### Name and version of other software in use when reproducing the issue:
Microsoft Edge, Firefox 62.0.2 x64.

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA?
No.

**Comment by Andre9642** [comment]
In this case, you should press NVDA+f2 before control+c.

**Comment by DataTriny** [comment]
Of course, you can still press NVDA+F2. But it is pretty annoying for such a common case.
Furthermore, by clicking on a paragraph, all other controls will loose focus so the Ctrl+C shortcut cannot be missunderstoud by the host application, at least I think!

**Comment by leonardder** [comment]
The control+c short cut is intercepted by the browse mode cursor manager, while selecting with the mouse totally bypasses browse mode. I don't think that there's anything to do about this other than #5354.

**Comment by DataTriny** [comment]
@leonardder that's the kind of thing I was suspecting.
Since #5354 seems to tacle more or less the same issue, shall we close this one maybe?

**Comment by leonardder** [comment]
Sounds ok to me.

**Comment by C-Loftus** [comment]
Have there been any updates on this issue? I am finding it tricky to follow the other threads linked to this. It seems copying text from NVDA without pressing the pass through before is still not possible.

**Comment by XLTechie** [comment]
Is this any better in Firefox with latest NVDA alpha?
