### ISSUE TITLE
Automated Accessibility UI testing of apps/websites with NVDA

### ISSUE THREAD

**Issue by dusek** [nvaccess/nvda#8807]
### Steps to reproduce:
1. I want to develop an automated accessibility UI test to test that a webpage/Windows app works as expected in NVDA for a certain usage scenario (like signing in, posting comments, etc.).

### Actual behavior:
There is no way of doing that (at least that I know of).

### Expected behavior:
There would be a way to do that.

### Notes
This would enable one to make automated tests of accessibility, instead of having to rely on manual testing. It might be something like [W3C webdriver](https://www.w3.org/TR/webdriver1/). Or perhaps simply having a way to invoke NVDA user commands through an API instead of keyboard shortcuts, and read the result through an API rather than listening to speech and/or reading braille.

**Comment by Brian1Gaff** [comment]
I do not think any automated process could account for all the ways a user 
might fail to do a task. People do not always follow logic. Having said that 
of course such an operation would need to take into account inbuilt browsers 
in applications, like Dropbox for example which, when installing uses its 
own window to get you to log in.
 On my windows 7 machine this seems no longer to work.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by larry801** [comment]
NVDA system tests use Robot framework. There are already some function
required in your issue. You can go to tests/system folder for more detail.

**Comment by Adriani90** [comment]
We didn't get any updates / reactions on the comments from the initial author since very long time. I am closing this as abandoned and also note that NVDA provides a browser test environment where this could already be acomplished. However, NVDA does test if actions work, in fact if Aria spec and other elements in the DOM / a11y tree are working correctly.
