### ISSUE TITLE
No pause with full stops in Georgian language

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#8812]
### Steps to reproduce:
(Not my issue, but reported by a user on Facebook)
With the language set to Georgian, open notepad or Word and type several sentences, ending the first with a full stop.

### Actual behavior:

NVDA does not pause at the full stop.  NVDA will pause if there are three full stops.

### Expected behavior:

NVDA should pause at a full stop as it does in other languages such as English.

#### NVDA Installed/portable/running from source:

Installed

#### NVDA version:

NVDA 2018.2.x and NVDA 2018.3.x

Using either speak or Sapi 5 synthesizer.

#### Windows version:

Windows 10 (non-insider?)

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA?

2018.2.x

**Comment by beqabeqa473** [comment]
hello.

i think it is important to know actually which speech synthesizer
he/she are using?

2018-10-01 16:11 GMT+04:00, Quentin Christensen <notifications@github.com>:
> 
>
> ### Steps to reproduce:
> (Not my issue, but reported by a user on Facebook)
> With the language set to Georgian, type several sentences, ending the first
> with a full stop.
>
> ### Actual behavior:
>
> NVDA does not pause at the full stop.  NVDA will pause if there are three
> full stops.
>
> ### Expected behavior:
>
> NVDA should pause at a full stop as it does in other languages such as
> English.
>
> ### System configuration:
>
> #### NVDA Installed/portable/running from source:
>
> Installed
>
> #### NVDA version:
>
> NVDA 2018.2.x and NVDA 2018.3.x
>
> #### Windows version:
>
>
> Windows 10 (non-insider?)
>
> #### Name and version of other software in use when reproducing the issue:
>
> #### Other information about your system:
>
> ### Other questions:
>
> #### Does the issue still occur after restarting your PC?
>
> Yes
>
> #### Have you tried any other versions of NVDA?
>
> 2018.2.x
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/8812


-- 
with best regards beqa

**Comment by Qchristensen** [comment]
Sorry, I've updated with more information now. It happens in notepad or Word, but not Chrome or Firefox. The user is using eSpeak NG but had also tried Sapi 5.

**Comment by Adriani90** [comment]
Is this still the case with NVDA 2024.2 Beta 2?

**Comment by beqabeqa473** [comment]
I was not able to reproduce this when this issue was created and now.
Unfortunately we cannot get reporter to explain picture clearly.
I, as Georgian native speaker, cannot observe this issue.

**Comment by Qchristensen** [comment]
I went back to Facebook and I can't find the original report either in our messages or the NVDA group.  I'd feel better if @beqabeqa473 had been able to reproduce the issue originally, but if we don't have anyone able to be reproduce the issue now, I'm going to close it and we can re-open when someone reports it again
