### ISSUE TITLE
Hint do not interrupt the continuous reading by jumping to the end of the element

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8820]
### Steps to reproduce:
open a web page that contains text and in the middle of this text there is some element like a video frame or a frame with advertisement.
Go to the beginning of the text and press nvda + a to read the article.
When nvda starts reading the frame with the video or some element you want to skip press, (comma).
### Actual behavior:
the nvda will interrupt the continuous reading, it will jump to the end of the element as the video frame and it will stop, the reading will not continue automatically after jumping the element.
### Expected behavior:
As before pressing the (comma) the nvda was making a continuous reading, the reading could continue automatically after skipping the desired element.
suggestion:
Press nvda + a to read the article.
When reading a video frame or advertisement start, press the comma (,) to skip the unwanted segment.
As the continuous reading was being performed and the user did not interrupt the reading by pressing ctrl the nvda understands that the user would only like to skip something undesired and continues to read continuously after pressing the comma (,).
If this puts someone off it can be user-disabled behavior.
#### NVDA Installed/portable/running from source:
instal and portable
#### NVDA version:
all
#### Windows version:
all
#### Name and version of other software in use when reproducing the issue:
aplication suport browze mode

#### Other information about your system:
page where there is an article and a video frame that can be skipped, text continues after the frames of videos.
The text is in Portuguese.
https://www.tecmundo.com.br/software/126352-veja-deve-funcionar-fuchsia-o-novo-sistema-operacional-google.htm
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
yes

**Comment by michaelDCurran** [comment]
Is the "Allow skim reading in say all" in NvDA's Keyboard settings dialog enabled?

**Comment by fernando-jose-silva** [comment]
Many thanks michael, This solved my question, I had never attempted this option.

**Comment by leonardder** [comment]
Closing as works for me.
