### ISSUE TITLE
Feature: Perform automatic OCR on video players when in full screen subtitles are showing up

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8823]
Dear all,

in many countries movies are not synchronized. But they are subtitled instead. So I suggest when Windows media player or VLC player is playing a movie in full screen, NVDA should perform automatic OCR when subtitles are showing up. This is usually the case when an actor is speaking.

Comments are apreciated.

Best
Adriani

**Comment by Adriani90** [comment]
@javidominguez maybe you can help out with your VLC addon? At least for VLC player?

**Comment by Adriani90** [comment]
@nvdaes it would be good to have your thoughts on this as well, since you were involved in reviewing the VLC addon.

**Comment by jscholes** [comment]
Using OCR to read subtitles would probably not give very good results - it might be okay in a pinch but almost certainly not good enough to really enjoy a film or other content you were watching as a leisure activity.  An alternative idea would be to create a VLC plug-in to communicate the original text of the subtitles to the screen reader directly as they were shown on screen.

**Comment by leonardder** [comment]
Treating and closing this as duplicate of #2797
