### ISSUE TITLE
intermittent hang when deleting emails in Mozilla thunderbird

### ISSUE THREAD

**Issue by kara-louise** [nvaccess/nvda#8832]
Sometimes, when deleting a message in Mozilla Thunderbird, NVDA will become unresponsive for a few seconds before speaking.
 
### Steps to reproduce:
1. Open thunderbird.
1. Focus on a message.
1. Press Delete

### Actual behavior:
NVDA will sometimes hang before announcing the next message in the list.
### Expected behavior:
NVDA should speak the next message in the list instantly. 
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
alpha-16149,e713f614

#### Windows version:
Widows 10 home Version	10.0.17763 Build 17763 (64 bit)

#### Name and version of other software in use when reproducing the issue:
mozilla Thunderbird 60.2.1 (32-bit)
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
Version 2018.3.2 has the same issue.
[ThunderbirdIssue.log](https://github.com/nvaccess/nvda/files/2459645/ThunderbirdIssue.log)

**Comment by Brian1Gaff** [comment]
Does this occur on a 64 bit version of Thunderbird?
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by leonardder** [comment]
As far as I know, there is no public version of thunderbird compiled for x64.

I've seen this as well, and was able to fix this by disabling the global indexer. However, I haven't been able to find that option that quick.

**Comment by kara-louise** [comment]
From Thunderbird's website:
>64 bit release builds for Thunderbird are available from some Mozilla web sites but they are not tested and are unofficial.

**Comment by Brian1Gaff** [comment]
Well there was once as I recall trying it. Maybe it was abandoned. I went 
back to my old OutlookExpress as to me Tbird in general does not offer what 
I want.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment]
Ah yes that is probably where I got it. Shame as it seemed a bit smoother to 
me.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment]
@kara-louise are you still having this issue? I cannot reproduce it in NVDA alpha-19420,a2c6f0f8
and thunderbird 68.3.0.

**Comment by kara-louise** [comment]
@Adriani90 No, I managed to fix it as it was a Thunderbird issue.
Turns out I had to repair my folders.
Feel free to close this,  and I should remember to update. :)
