### ISSUE TITLE
Address autocompletion is not read in Microsoft Edge

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#8838]
### Steps to reproduce:
1. Open Microsoft Edge.
2. Visit a few sites, so some "history" is accumulated and autocompletion starts working for the address bar. This step is probably necessary only if you haven't visited any sites with Edge.
3. Then, in the address bar of Microsoft Edge, start typing the address of one of the previously visited sites.

### Actual behavior:
Microsoft Edge starts automatically completing the address that you are typing, but NVDA does not report this, as it does in other browsers like Firefox, IE and Chrome.

### Expected behavior:
Microsoft Edge starts automatically completing the address that you are typing, and NVDA does report this, as it does in other browsers like Firefox, IE and Chrome.

Test environment:
- Operating system: Windows 10 Pro version 1809 (build 17763.55), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-16164,8a7da1d4, installed.
- Microsoft Edge version: 44.17763.1.0.
- Processor: Intel Core i5-4670 at 3.40GHz.
- RAM Memory: 8.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC887 at Intel Lynx Point PCH - High Definition Audio Controller.### System configuration:

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA?
Yes, this has been happening for a long time with older versions of NVDA as well.

**Comment by josephsl** [comment]
Hi, I may need to investigate this again, since last time I checked, it raises value change events (unless that has changed in recent months). Note that if I do find a way to support it, it’ll be 1709 and later (as I just removed 1703 VM from my computer and is stored on an external hard drive for archival purposes). Thanks.

**Comment by josephsl** [comment]
Hi,

Technical: by default, Edge's address omnibar is flagged as not supporting automatic selection detection when in fact it should. One way to partly change this is to tell NVDA to replace EditableTextWithoutAutoSelectDetection with the "can" counterpart (editableTextWithAutoSelectDetection) if possible. At the moment I'm looking into which Edge (Windows 10) version introduced selection flag from UIA for documentation purposes.

CC @MichaelDCurran

**Comment by josephsl** [comment]
Hi,

For documentation purposes: the fix should work across all Windows 10 releases (and server counterparts) from 1507 onwards.

Thanks.

**Comment by josephsl** [comment]
Hi, looks like a conflict between two editable text behaviors. I’ll look into this in a few days. Thanks.

**Comment by josephsl** [comment]
Hi,

CC @LeonardDer, as his UIA auto select work will resolve this problem.

Thanks.

**Comment by Adriani90** [comment]
This seems to work just fine on Windows 10 1909 Update.
@josephsl, @k-kolev1985 can you confirm? If yes, then I suggest to close this issue as works for me.
I am testing with NVDA 2019.3 Beta 1.

**Comment by josephsl** [comment]
Hi,

Ah yes, we overlooked to mentioned this issue in the pull request - fix included in NVDA 2019.3.

Thanks.
