### ISSUE TITLE
NVDA crashes Windows when viewing prefered wireless networks

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#884]
**Reported by elliott94 on 2010-09-05 06:31**
I saw this behaviour on another machine a couple of months ago, but now I've seen it on my netbook as well.

When using the Wireless 0 Configuration Service that's built-in to Windows XP and you view your list of prefered wireless networks, NVDA appears to crash Windows, and the only way that I've found to get control back is to do a hard restart.
I'm unable to attach a log; I've not able to obtain one before Windows crashes.
Keystrokes such as alt-tabbing don't work, however you can still use NVDA keystrokes to read the time status, etc.

Steps to repro:
1. Open your Wireless Network Connection.
2. If already conected, press the "View Wireless Networks" button.
3. Press the "Change Order of Prefered Networks" button.

At this point NVDA and Windows should crash.
It should also be noted that this behaviour can't always be seen, but nine times out of ten Windows will crash.

Using XP with SP3.
This doesn't happen under Windows 7, and I can't remember if it happened in 2010.1.

**Comment by leonardder** [comment]
This is XP only, and XP specific issues won't be fixed any more unless really critical. Closing
