### ISSUE TITLE
Windows 10 Action Center: Brightness percentage not reported for brightness quick action

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#8845]
### Steps to reproduce:

1. Ensure the Brightness quick action is enabled for the Action Center. This can be enabled in Settings -> System -> Notifications & actions -> Add or remove quick actions.
2. Open Action Center by pressing Windows+a.
3. Tab to the quick actions and press right arrow until you land on Brightness.
    - Expected: NVDA should report the brightness percentage.
    - Actual: NVDA reports only "Brightness  toggle button  not pressed".
4. Press space to change the brightness.
    - Expected: NVDA should report the new brightness percentage.
    - Actual: NVDA reports nothing.

#### NVDA Installed/portable/running from source:
Installed.

#### NVDA version:
alpha-16157,526d6fca

#### Windows version:
Version 1809 (OS Build 17763.55)

### Additional info:

Even though Windows reports this as a toggle button, it isn't. The toggle state is always off. Narrator behaves as such too.

The percentage is exposed via the ItemStatus UIA property. IMO, this is inda weird, but at least it's exposed.

Because of the weirdness of this control, I'd suggest that rather than generically supporting ItemStatus as value for toggle buttons, we should just do it for this control (or at least this app). If we do it specifically for this control, we could also map it to button instead of toggle button, which is probably less confusing.

Relevant dev info for the control:

```
appModule: <'shellexperiencehost' (appName u'shellexperiencehost', ...>
UIA automationID: Microsoft.QuickAction.Brightness
UIA frameworkID: XAML
UIA providerDescription: [pid:17568,providerId:0x0 Main(parent link):Unidentified Provider (unmanaged:Windows.UI.Xaml.dll)]
UIA className: ToggleButton
UIA patterns available: LegacyIAccessiblePattern, InvokePattern, ScrollItemPattern, TogglePattern
```

**Comment by josephsl** [comment]
Hi,

I may have been too enthusiastic about this... This work may take a while - at least managed to let NVDA announce item status via state change, but will need to investigate why it is announcing the previous state sometimes.

Thanks.

**Comment by josephsl** [comment]
Hi,

Technical: we need to tell NVDA to listen to item status property event from now on, as it can be used for brightness and other quick action toggle announcements.

Pull request to be sent in the next few days.

Thanks.
