### ISSUE TITLE
new functionality give nvda function similar to nvarrador's scan mode

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8847]
### Steps to reproduce:
I was experimenting with the narrator and was impressed with a feature, the scanning mode.
What I realized of great advantages:
Inside configurations just press capslook + space and when navigating with arrows up and below it is possible to read the names of the functions and still get a splint on each function of the configurations (I did not even know that these splinters existed).
Within the apps of windows 10 it is possible to navigate as if it were in a web page, being able to jump by head and easy reading the texts of each function of the app.
In the store for example I was able to read the explanations about the features of a new app.
It would be something like making nvda browsing mode available in windows 10 apps and also within settings.
I no longer tested that the narrator's scanning mode is available even within other standard win32 applications.
In nvda we have the browse mode which is the mode that most closely approximates the narrator but it is not available in many applications applications of windows 10 including the home screen of the store microsoft.
It is also not available in the windows settings and win32 applications.
In the settings of windows and in the standard applications win 32 the closest that we have is the exploration

### Actual behavior:
in nvda we have the browsing mode that is not available in most applications windows 10 apps in the example on the first page of the microsoft store, windows settings and the standard win32 applications.
In nvda we have object navigation that is not intuitive like pressing up or down arrows as well as right and left arrows simulating a web navigation, and still does not allow using the accelerator keys like h to navigate to headers, among others.
### Expected behavior:
summarizing the request would be enough so that the navigation mode of nvda was available in the windows 10 apps
(my most glaring example would currently be on the microsoft store homepage, plus it's applied to the vast majority of windows 10 apps). Provide nvda browsing mode also in windows settings and elsewhere that the narrator's scanning mode is available.
#### NVDA Installed/portable/running from source:
all
#### NVDA version:
all
#### Windows version:
windows 10
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
yes

**Comment by gregjozk** [comment]
Hello,

did you try to use addon objpad from @josephsl ? it implements for modes:
- normal
- object (simular as navigating with object commands
- web mode - usable on the web
- scan mode (simular to Narrator's function)

see https://addons.nvda-project.org/addons/objPad.en.html

**Comment by rkingett** [comment]
I don't think this is a duplicate because I just tried to do a search and no other ticket came up that matched this one. I know about the add on, but could NVDA add scan mode into the core at some point? This would be a really great feature to have when dealing with inaccessible applications.

**Comment by josephsl** [comment]
Hi,

Note that I'm no longer maintaining ObjPad add-on. One possible workaround would be to strengthen screen review to act like scan mode or close to it, or perhaps with a new review mode.

Thanks.

**Comment by rkingett** [comment]
I'd especially want that since the add on is no longer being maintained. I mean, scan mode has helped me actually use some inaccessible applications and get to controls I couldn't get to before. It can also make navigating windows 10 apps a billion times easier, as well.

**Comment by Adriani90** [comment]
let's continue this discussion on the issue #7759. The discussion there is more broadly and there is also some kind of prototype work done by @Robert-J-H.
