### ISSUE TITLE
Problem with Notification Center

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#8883]
Hello. In Windows 10 18262 and above, Nvda often does not function in the notification center.
1.open the Notification Center.
2. Start navigation using the ARROW keys and TAB key.
Nvda can be silent.
Repeat the problem is not constant but frequent.
Restarting Nvda helps.windows. windows 10 18267. nvda alpha-16188,ceafcdd3

**Comment by gdata1** [comment]
Yes. I have to introduce this.

**Comment by josephsl** [comment]
Hi,

Just to make sure: does this happen with build 18282 now? If not, let's close it until we get more reports from users.

Thanks.

**Comment by gdata1** [comment]
Hello. In build 17282 I can sometimes reproduce the problem

**Comment by josephsl** [comment]
Hi, I think this may have to do with missed UIA events. CC @mIchaelDCurran

**Comment by josephsl** [comment]
Hi,

Is this still the case with build 18309? Thanks.

**Comment by gdata1** [comment]
Hello. In 18309 I do not observe the problem.
