### ISSUE TITLE
MS Teams: When moving focus between conversations using up/down keys, NVDA is often reading the label of the previous conversation

### ISSUE THREAD

**Issue by HarishTerala** [nvaccess/nvda#8889]
### Steps to reproduce:
1. Open Microsoft Teams app.
2. Navigate and select "Teams" app bar button.
3. Navigate and select any Channel in any Team.
4. Navigate to most recent message using Tab key.
5. Press Insert+Space key to turn off browse mode.
6. Press up arrow key and verify the speech of NVDA.

### Actual behavior:
NVDA reads the previous message information along with the current focused conversation information when navigating in application mode using up/down arrow keys.

### Expected behavior:
NVDA should read the current focused conversation information when navigating in application mode using up/down arrow keys. 
NVDA should not read the previous message information.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.2.3

#### Windows version:
Win10 1809

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by ehollig** [comment]
@HarishTerala is this still an issue with the latest version of MS Teams? Many updates to Teams have come out since this issue was created.

**Comment by HarishTerala** [comment]
@ehollig - Issues is fixed and working as expected. 

**Test environment**
Platform: Win32
Application: MS Teams
NVDA version: 2019.1
