### ISSUE TITLE
Microsoft Teams : When using browse mode and reading a conversation heading, press down arrow 6 times. Same message will be read again.

### ISSUE THREAD

**Issue by GarimaRanaV** [nvaccess/nvda#8891]
Steps to reproduce:
Open Microsoft Teams app.
Navigate and select "Teams" app bar button.
Navigate and select any message in any channel
Navigate to most recent message using Tab key.
Press Insert + Space key to turn off browse mode.
Press down arrow 6 times in channel conversation and verify the speech of NVDA.

Actual behavior:
As a user navigates through a message, the message body repeats 4-5 times – increasing navigation between messages. User is unable to know what is written in original message and proper context

Expected behavior:
NVDA should read the current focused conversation information when navigating in application mode using up/down arrow keys.

NVDA should not repeat the same message multiple times
System configuration:
NVDA Installed/portable/running from source:
Installed
NVDA version:
2018.2.3
Windows version:
Win10 1809
Name and version of other software in use when reproducing the issue:
Other information about your system:
Other questions:
Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
No

**Comment by ehollig** [comment]
@GarimaRanaV is this still an issue? When I am reading messages in MS Teams in focus mode, using up and down arrows several times does not read the message again. I am able to get the described behaviour when reading the messages in browse mode, however, it is recommended to use focus mode to read and interact with messages in a conversation.

**Comment by Adriani90** [comment]
@HarishTerala could you please test if this issue is still reproducible?

**Comment by HarishTerala** [comment]
@Adriani90 -  It depends on user to user which mode they are comfortable in interacting with messages in a conversation. 

Yes, issue still repro's. But now NVDA reads the message 4 times. 

**For quick repro follow the steps:**
1. Teams> Press Tab key to navigate to most recent message. (Make sure you are in browse mode)
2. Press up arrow keys until you read complete message.

**Comment by seanbudd** [comment]
Is this still an issue with the latest MS Teams and NVDA?

**Comment by seanbudd** [comment]
Closing as stale
