### ISSUE TITLE
MS Teams : In controls and headers within each area (channel, chat, meetings, etc.) screen reader users experience “clickable, clickable, . . . “ at minimum 15+ times for a single message

### ISSUE THREAD

**Issue by GarimaRanaV** [nvaccess/nvda#8892]
Steps to reproduce:
Open Microsoft Teams app.
Navigate and select "Teams" app bar button.
Navigate and select any message in any channel
Navigate to most recent message using Tab key.
Press Insert + Space key to turn off browse mode.
Press up and down keys to move through channel conversation and verify the speech of NVDA.

Actual behavior:
As a user navigates through a message, the message body repeats 4-5 times – increasing navigation between messages. User is unable to know what is written in original message and proper context
Chat messages,   calling control, nearly all Teams controls repeatedly output “clickable,   clickable,…”

Expected behavior:
NVDA should not read clickable multiple times while moving through the Channel conversation.

System configuration:
NVDA Installed/portable/running from source:
Installed
NVDA version:
2018.2.3
Windows version:
Win10 1809
Name and version of other software in use when reproducing the issue:
Other information about your system:
Other questions:
Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
No

**Comment by ehollig** [comment]
This is related to #7430

**Comment by ehollig** [comment]
This is no longer an issue now that #8922 is merged. Furthermore, it is recommended to read chat messages in MS Teams in focus mode rather than browse mode. Closing
