### ISSUE TITLE
In Thunderbird the email subject is announced where it already shouldn't

### ISSUE THREAD

**Issue by Mary5958** [nvaccess/nvda#8897]
### Steps to reproduce:
1. Open a message in Thunderbird
2. Press anything that navigates through the message; it can be sayAll, arrow keys, or if there are links or other elements if it's an HTML message just their respective navigation keys are enough.

### Actual behavior:
NVDA still reads the subject before the actual message text or element.

### Expected behavior:
Only the message text or the elements navigated to should be read.

Note this happens only on the first read after opening, then as long as the message is opened and you get back to read again it's OK.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
alpha-16203,b4e9e832

#### Windows version:
10.0.17134

#### Name and version of other software in use when reproducing the issue:
Thunderbird versions 52.9.1 and 60.2.1

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
alpha-16196,5fe34c52 in which it actually started happening, so it has most likely something to do with the latest commits related to browse mode dated 29 October 2018.

**Comment by Neurrone** [comment]
Caused by #8886, which has since been reverted.
