### ISSUE TITLE
MS Teams: On activating any search suggestion from "Search or type a command", NVDA do not read the opened chat username

### ISSUE THREAD

**Issue by HarishTerala** [nvaccess/nvda#8911]
### Steps to reproduce:
1. Turn on NVDA and open MS Teams app.
2. Press Tab key to navigate to "Search or type a command".
3. Type any user name and choose the user using up/down keys and press Enter key on the select the user.​
4. Verify the speech of NVDA.​

### Actual behavior:
When pressing Enter key on any search suggestion from "Search or type a command", NVDA do not read the opened chat username.

### Expected behavior:
When pressing Enter key on any search suggestion from "Search or type a command", NVDA should read the opened chat username then compose box information.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.3.2

#### Windows version:
1809

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by Adriani90** [comment]
I assume this is an web authoring issue here, there might not be a role="allert" on the press of enter on the user when searching for some one in the feed tab. When you choose the chat tab, then new chat and search for an user, NVDA reports the user after pressing enter on it.

Please report your issue to Microsoft, this not NVDA related.

I am closing this issue for now.
