### ISSUE TITLE
Preferences: Hide "Play a sound when auto-suggestions appear" option if running Windows 7 or Less

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#8912]
From experience, I believe that this option is redundant if running on anything less than Windows 8 or above. Similarly to what's been done with the OCR preferences in this dialog, would it be possible to hide this if NVDA is running on anything other than Windows 8 and later?

**Comment by Brian1Gaff** [comment]
Hi, I use Windows 7, and have no idea what this does. How might I tell if it 
works in windows 7?


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by elliott94** [comment]
This option is used, as an example, to play a sound when typing in the search field in Windows 10 to show that search results have been found and are being displayed.

**Comment by josephsl** [comment]
Hi,

The foundation is there to support editable text with suggestions - it's just that not a lot of app modules and other modules use this yet. Given that there are apps that do raise suggestion events (or provide a way to find out appearance of suggestions), I'd like to leave it as is for now.

Thanks.

**Comment by Adriani90** [comment]
I am closing this issue as per comments from @josephsl above. I will adjust the text in the userguide for this setting accordingly. Thanks.
