### ISSUE TITLE
Problem with a strange sound

### ISSUE THREAD

**Issue by gruja85** [nvaccess/nvda#8943]

**Comment by ruifontes** [comment]
Have you tested with addons disableds?

Rui Fontes


Às 14:55 de 13/11/2018, gruja85 escreveu:

**Comment by gruja85** [comment]
Tested with no add-ons, with add-ons, with versions all over to 2013..... portable or installed..... tried to change sound and video drivers
Has anyone tried to go to first item in some folder, and after that to go very, very fast with down arrow several times. Do you hear that peak sound when changing position from one item to another. The same situation is when moving mouse cursor over desktop icons very fast.What I concluded is that NVDA read the item name and send it to sound card, but then the spoken word is interrupted with another, then another and colision of the last letter of first and first letter of second word is macking that sound.

**Comment by ehollig** [comment]
I am pretty sure this is something we can not fix. Please reopen if I am incorrect. @leonardder @michaelDCurran

**Comment by Brian1Gaff** [comment]
Yes and what synth is in use as well.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment]
Is your machine a bit sluggish? I have been going manic with trying what you 
say and apart from an odd click where a word is interrupted at a peak it is 
reasonably smooth.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by leonardder** [comment]
I can't find out what the steps to reproduce ought to be.
