### ISSUE TITLE
Add support for Foxit Reader PDF Viewer

### ISSUE THREAD

**Issue by gauldoth** [nvaccess/nvda#8944]
Foxit Reader is a widely used PDF viewer all over the world.  Foxit also engages in providing accessibile PDF reading. 
Foxit Reader can work with JAWS since version 9.3, it will be great if NVDA can support it. 

### Steps to reproduce:

1. Download and install Foxit Reader 9.3, it can be downloaded from here:
https://www.foxitsoftware.com/pdf-reader/
1. Open a PDF document.
1. Press DownArrow multiple times to read the contents in the opened document.

### Actual behavior:
Could not enter browse mode, only the first line of the opened document is read.

### Expected behavior:
Enter browse mode automatically and read the contents in the document.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
Version: 2018.3.2

#### Windows version:
N/A

#### Name and version of other software in use when reproducing the issue:
Foxit Reader 9.3.0.10826

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes

### Additional info:
Foxit Reader implemented MSAA and PDDom model just as Adobe Reader does, only a few lines of modification is needed to support it. I will try to create a pull request in a few days.

**Comment by Brian1Gaff** [comment]
Yes I know it won't work with nvda, but last time I asked somebody told me 
it did not publish its access routines or support all the normal windows 
ones. It may of course have changed or maybe Jaws has a specific script for 
it?


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by leonardder** [comment]
Foxit Reader exposes a UIA document implementation. It is pretty easy to add browse mode to this and I was even able to have quick navigation working for headings, but the performance is ridiculously slow.

See https://github.com/BabbageCom/nvda/blob/i8944/source/appModules/foxitreader.py

**Comment by gauldoth** [comment]
@leonardder The UIA implementation is not complete yet. Out of process queries are quite slow due to some unknown reasons. But their developers have implemented both MSAA and PDDom for the document, the UIA implementation may be removed in future releases.

**Comment by gauldoth** [comment]
@leonardder Thanks for helping.
I also tried a commit, but I don't know how to put that in into app module, see https://github.com/gauldoth/nvda/commit/8a56c93a042860753f7ed06c8c509b313c68534a

BTW, there is another product called Foxit PhantomPDF which implemented the same interface.
If we are going to use app module, we may also need a foxitphantompdf.py under the appModules folder.

**Comment by leonardder** [comment]
> I also tried a commit, but I don't know how to put that in into app module, see [gauldoth@8a56c93](https://github.com/gauldoth/nvda/commit/8a56c93a042860753f7ed06c8c509b313c68534a)

Wow, this is exactly the next approach I intended to follow.
Would you be able to create a separate branch for this and file a pull request?
