### ISSUE TITLE
NVDA IS not Reading any Item has been selected or not selected from select drop down list

### ISSUE THREAD

**Issue by pratik-pk** [nvaccess/nvda#8949]
### Steps to reproduce:
Open the html page in chrome and than tab till select ,open drop down and select any option.
### Actual behavior:
NVDA is not Reading any Item has been selected or not selected from select drop down list
### Expected behavior:
NVDA should Read the item is selected on selecting from drop down and not selected when it is not selected.
### System configuration:
windows 10 64bit ,16GB ram
#### NVDA Installed/portable/running from source:

[selectissue.zip](https://github.com/nvaccess/nvda/files/2587964/selectissue.zip)
[selectissue.zip](https://github.com/nvaccess/nvda/files/2587966/selectissue.zip)

#### Windows version:
 Windows 10 Enterprise, version 1803
#### Name and version of other software in use when reproducing the issue:
 Latest version of chrome and Edge.
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
NO

**Comment by Adriani90** [comment]
Actually this is self explanatory since every time when you press down or up arrow in any combo box you will select an item. Why should NVDA report additionally that something is selected?
This behavior is consistent through all browsers.

**Comment by Adriani90** [comment]
This is working as expected in Crome 81 and NVDA Version: alpha-20026,16ec967e. Closing as works for me.
