### ISSUE TITLE
NVDA's skip past links command doesn't skip every link on some sites

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#8956]
I normally visit the TV By the Numbers site and read some of the comments under the ratings. With NVDA 2018.3.2 and older, when I press the 'N' key, I can go through all the comments by first line, then all I'd do is press down arrow to read the other lines of text. Of course, it would skip some, but I was fine with that. Now, in the latest alpha as of opening this ticket and for a few versions prior, I noticed that it would jump to a linnk before the text begins, rather than the text itself. It usually happens if I'm on a link in the comments to begin with, but I'm expecting it to jump straight to text. What could be causing this?

Website: tvbythenumbers.zap2it.com (open any ratings discussion page)
Browser: Firefox 63.0.3
NVDA Version: alpha-16274,498e42f8
Windows Version: 10 (1809)

**Comment by DrSooom** [comment]
CC: @michaelDCurran, @MarcoZehe and @jcsteh

**Comment by Adriani90** [comment]
This works quite reliable now when you turn off automatically set system focus to focusable elements in browse mode settings of NVDA. Just a note, the website has been closed but there is an alternativ for that.
I am closing this issue as works for me.
