### ISSUE TITLE
current status is announced multiple times by NVDA

### ISSUE THREAD

**Issue by AnthonyYY** [nvaccess/nvda#8960]
### Steps to reproduce:
1. Open this example on a windows FireFox browser tab, https://jsfiddle.net/AnthonyYY/xpvt214o/952936/
2. Open NVDA and open its speech viewer.
2. in the JSFiddle's `result` panel, use keydown `tab` twice to navigate to the next menu-item.
3. hit `enter` key to activate to target menu item.
4. check the speech viewer
### Actual behavior:
NVDA reads aria-current menu item's current status twice.
### Expected behavior:
when hitting `enter` key to activate a menu-item. clicked menu item's current status is report once only.
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
2018.3.2
#### Windows version:
Window 10 Pro
#### Name and version of other software in use when reproducing the issue:
FireFox: version 63.0.1 (32)
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
Yes

**Comment by AnthonyYY** [comment]
Previously i thought  it's an issue of react-router, for reference https://github.com/ReactTraining/react-router/issues/5507. After reproduced it by jQuery found that it may caused by NVDA.

**Comment by jozefbriss** [comment]
We have a similar issue with role="treeview" / role="treeitem" and aria-current. "current" is repeated several times up to 5. It really gets annoying quickly.

**Comment by Adriani90** [comment]
cc: @jcsteh, @MarcoZehe

**Comment by jcsteh** [comment]
This is a bug in NVDA, not in browsers. I figured out why this is happening, so I'll submit a PR shortly.
