### ISSUE TITLE
⡘ Euro-sign in is missing in German brailletable

### ISSUE THREAD

**Issue by errotech** [nvaccess/nvda#8998]
The Eurosign ⡘ (4-5-7) is missing in the german brailletable. Could someone add it?

Thanks in advance!

Eric Roeder

**Comment by leonardder** [comment]
Please file an issue against liblouis at https://github.com/liblouis/liblouis/issues

**Comment by DrSooom** [comment]
See issue 8702 and [my comment in issue #1717](https://github.com/nvaccess/nvda/issues/1717#issuecomment-418018712) for more information about what happened here and how to solve it manually.

**Comment by bdorer** [comment]
please close this issue as €-sign has been added with the latest 
liblouis release.

Am 02.12.2018 um 16:49 schrieb Daniel Mayr:

**Comment by ehollig** [comment]
Closing as requested.
