### ISSUE TITLE
TextInfo._getCaretOffset() method is not implemented in some controls

### ISSUE THREAD

**Issue by mltony** [nvaccess/nvda#9005]
### Steps to reproduce:
1. Install SentenceNav 2.0 add-on for NVDA.
2. Open an empty document in LibreOffice and type the following text:
Hello. This is test. Good bye.
3. Try navigating between sentences using Alt+Up and Alt+Down commands.

### Actual behavior:
Sentence navigation commands don't work. The following exception is thrown:
error executing script: <bound method
GlobalPlugin.script_previousSentence of
<globalPlugins.sentenceNav.GlobalPlugin object at 0x053AF570>> with
gesture u'Alt+Pfeiltaste nach oben'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "C:\Users\Kucuk\AppData\Roaming\nvda\addons\SentenceNav\globalPlugins\sentenceNav.py",
line 545, in script_previousSentence
  File "C:\Users\Kucuk\AppData\Roaming\nvda\addons\SentenceNav\globalPlugins\sentenceNav.py",
line 630, in move
AttributeError: 'TreeCompoundTextInfo' object has no attribute '_getCaretOffset'

### Expected behavior:
Sentence navigation commands should work. _getCaretOffset() method should be implemented for that TextInfo.
#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.3.2.

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
SentenceNav 2.0.
LibreOffice 6.1.3
or
Mozilla Thunderbird 60.3.2.

#### Other information about your system:
Very similar exception is thrown when trying to navigate by sentences in "Compose new email" window in Mozilla Thunderbird. _getCaretOffset() method doesn't seem to be implemented for that control either.

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No

**Comment by mltony** [comment]
@leonardder, before blaming my SentenceNav add-on, would you mind explaining what's the right way of finding out caret offset?

**Comment by leonardder** [comment]
@mltony: The major point here is that many textInfo objects that aren't inheriting from textInfos.offsets.OffsetsTextInfo don't have offsets NVDA can work with at all. So there is no right way to find a caret offset for these.

As this is not an issue within NVDA, I'm closing this as invalid. Please consider the following for SentenseNav. Either:

1. Limit your logic that relies on a caret offset to textInfos that are an instance of OffsetsTextInfo, or
2. no longer rely on offsets.

A quick skim through the add-on indicates that you're relying on offsets a lot, so the easiest decision might be disabling sentence navigation for non offset based textInfos.

**Comment by leonardder** [comment]
@mltony: it might help to ask your question on the development list.
In my opinion, both offset based and non offset based text information implementations have their advantages and drawbacks. But again, this is not a limitation within NVDA, rather on the API level of the non offset based implementations, such as UIA, Word and ITextDocument.

For Libre and Thunderbird, It might help you to know that the compound based text infos use offsets under the hood.

**Comment by mltony** [comment]
Where can I get more information about compound based text infos ?
Like what's the name of the class in NVDA? If they use offsets under
the hood - I might be able to extract them.

**Comment by derekriemer** [comment]
compound textInfos are based on code in compoundDocuments.py.
However, textInfos are extremely abstract.


Provides information about a range of text in an object and facilitates access to all text in the widget.
	A TextInfo represents a specific range of text, providing access to the text itself, as well as information about the text such as its formatting and any associated controls.
	This range can be moved within the object's text relative to the initial position.
	
	At a minimum, subclasses must:
		* Extend the constructor so that it can set up the range at the specified position.
		* Implement the L{move}, L{expand}, L{compareEndPoints}, L{setEndPoint} and L{copy} methods.
		* Implement the L{text} and L{bookmark} attributes.
		* Support at least the L{UNIT_CHARACTER}, L{UNIT_WORD} and L{UNIT_LINE} units.
		* Support at least the L{POSITION_FIRST}, L{POSITION_LAST} and L{POSITION_ALL} positions.
	If an implementation should support tracking with the mouse,
	L{Points} must be supported as a position.
	To support routing to a screen point from a given position, L{pointAtStart} must be implemented.
	In order to support text formatting or control information, L{getTextWithFields} should be overridden.
https://github.com/nvaccess/nvda/blob/master/source/textInfos/__init__.py


Two types of textInfos exist to my knowledge.

* Offset based TextInfos, which are documented in https://github.com/nvaccess/nvda/blob/master/source/textInfos/offsets.py.
* everything else, like those used in UIA, base class at in https://github.com/nvaccess/nvda/blob/master/source/NVDAObjects/UIA/__init__.py

The reason some of these are not based on offsets is that they wrap objects implemented in COM servers, I.E. res=self._rangeObj.MoveEndpointByUnit(UIAHandler.TextPatternRangeEndpoint_Start,UIAUnit,direction)

**Comment by leonardder** [comment]
> I would much appreciate if .unitCount() and/or .unitIndex() be implemented on NVDA side instead.

This again depends on what is provided by the textInfo api being used.

I think this discussion is heading in a direction where switching the conversation to the NVDA development list might be more appropriate than github.
