### ISSUE TITLE
upgrade Liblouis to version 3.8.0

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#9013]
Ho to all,
Today, the Liblouis 3.8.0 was released to the public.
It brings a ton of bubfixes, and a lot of renamed braille tables.
The biggest change to us is that pass1 only flags are removed completelly, and the braille tables where updated, and new tables were created.
Here is the excerpt from the changelog

The liblouis developer team is proud to announce the liblouis release 3.8.0. The release is available for download at:

    https://github.com/liblouis/liblouis/releases

Introduction
============

Liblouis is an open-source braille translator and back-translator. It features support for computer, literary and math braille, supports contracted and uncontracted translation for many, many languages[1].
It plays an important role in an open source accessibility stack and is used by screenreaders such as NVDA, Orca and JAWS. A companion project liblouisutdml[2] deals with formatting of braille.

Changes in this release
=======================

The major focus of this release is on braille table updates. There are major updates to German, Arabic, Chinese, Turkish, Dutch, Czech, Latvian, Spanish and Ethiopic. Some of these new tables have only been possible because Bert Frees fixed some nasty long standing bugs behind the scene. Also there is the usual assortment of code improvements and cleanups.

For a detailed list of all the changes refer to the list of closed issues[3].

New features
~~~~~~~~~~~~

- None

Bug fixes
~~~~~~~~~

- Fix support more than 4 classes thanks to Bert Frees.
- Fix capitalization of words that match `nocont' rules thanks to Bert
  Frees.

Braille table improvements
~~~~~~~~~~~~~~~~~~~~~~~~~~

- Defined the undefined character for the Czech tables thanks to Jan
  Hegr.
- Improvements to Unified English braille thanks to Mike Gray
- Updated the Dutch table to the new 2017.1 braille standard thanks to
  Davy Kager.
- Improvements to the Polish grade 1 table, to make back-translations
  of diacritics working
- Fixes to Latvian braille table thanks to Gatis Grintals and Artis
  Raugulis.
- Improvements to traditional Mainland Chinese braille and two-cell
  Chinese Braille thanks to Sunian Loomee.
- Update Bopomofo-based Chinese Braille to version 2018-11 thanks to
  Bo-Cheng Jhan
  - Correct the default braille pattern of many Chinese characters
  - Add various Chinese phrases involving exceptions of braille
    patterns
  - Modify dot patterns of dashes for readability reasons
- Added a table for Turkish grade 2 thanks to Uğur Gürbüz and Simon
  Aittamaa
- Major upgrade to the German tables. They have been upgraded to /Das
  System der deutschen Brailleschrift/ (2018). They are much smaller
  now as they are based on `lou_maketable'. As they now work for any
  locale (be it Switzerland or Germany) they have been merged into one
  set of tables for the different grades. Thanks to Christian
  Waldvogel.
- New table for Arabic contracted braille thanks to Ikrami Ahmad.
- New table for Arabic computer braille thanks to Ikrami Ahmad.
- Improvements to Ethiopic thanks to Tamru E. Belay.
- New table for Spanish contracted braille thanks to Juan Pablo Bello.

Other changes
~~~~~~~~~~~~~

- Updated the `lou_allround' and `lou_trace' test tools to include all
  the mode flags described in the documentation of the
  `lou_translateString()' function, thanks to Bue Vester-Andersen

Deprecation notice
~~~~~~~~~~~~~~~~~~

- None

Backwards incompatible changes
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- The `pass1Only' flag has been deprecated for a while and is now
  removed from the code, thanks to Bue Vester-Andersen.

New, renamed or removed tables
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

New
---

  - tr-g2.ctb
  - ar-ar-g2.ctb
  - ar-ar-comp8.utb
  - es-g2.ctb

Renamed
-------

  - de-de-accents.cti -> de-accents.cti
  - de-de-g0.utb -> de-g0.utb
  - de-de-g1.ctb -> de-g1.ctb
  - de-de-g2.ctb -> de-g2.ctb
  - de-ch-g0.utb -> de-g0.utb
  - de-ch-g1.ctb -> de-g1.ctb
  - de-ch-g2.ctb -> de-g2.ctb

Removed
-------

  - ar-fa.utb
  - Es-Es-g1.utb

Next release
============

The next release will be published on March 4 2019 so please keep up the excellent work and keep those improvements coming.

Share and Enjoy!

-- Christian Egli, on behalf of the liblouis developers

Footnotes
=========

[1]  https://github.com/liblouis/liblouis/tree/master/tables
[2]  https://github.com/liblouis/liblouisutdml
[3]  https://github.com/liblouis/liblouis/milestone/18?closed=1

--
Christian Egli
Swiss Library for the Blind, Visually Impaired and Print Disabled Grubenstrasse 12, CH-8045 Zürich, Switzerland

For a description of the software, to download it and links to project pages go to http://liblouis.org
best,
Zvonimir

**Comment by leonardder** [comment]
I will provide a pr for this which will also switch to using UCS4 under the hood, being much more friendly to emoji. I intend to add the new Spanish and Arabic tables. I'm not sure about Turkish, though. There is a tr.ctb table that is classified by NVDA as turkish grade 1, but liblouis contains another turkish grade 1 tables.

**Comment by zstanecic** [comment]
Don’t forget to add the arabic computer Braille and arabic grade 2

And also don’t forget to rename the german tables.

**Comment by DrSooom** [comment]
The SHA-256 checksum for "de-de-comp8.ctb" is the same in Liblouis 3.1.0, 3.5.0 and 3.8.0, but not in 3.0.0 and before. SHA-256: 6a6f3682bdb20c53458ee813773288d115d094b965c9f58ef0bc3ff98ce80c24
