### ISSUE TITLE
Repeated characters in the Tera Term pro

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#9014]
### Steps to reproduce:
1. Open Tera Term pro, and connect to the ssh host.
2. start typing something.
3. Press backspace  and type some more.
### Actual behavior:
After backspace is pressed each typed character is echoed back, if character echo is enabled twice. This is happening until enter is pressed.

### Expected behavior:
The character echo setting should be respected i.e no announcement if it is disabled and single announcement if it isn't.
#### NVDA Installed/portable/running from source:
Installed.
#### NVDA version:
NVDA version alpha-16346,d8c65fb3

#### Windows version:
Windows 7 x64.
#### Name and version of other software in use when reproducing the issue:
Tera Term 4.100;
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?

I've tested with NVDA  2015.3 and it is happening with it also.

**Comment by ABuffEr** [comment]
Hi,
if I understood correctly, this is a known problem. See @derekriemer add-ons such as [consoleTimer](https://github.com/derekriemer/consoleTimer) and [tdsr-NVDA](https://github.com/derekriemer/tdsr-NVDA)
Hth

**Comment by lukaszgo1** [comment]
@ABuffEr Thanks for your commend. Unfortunatelly none of the solutions above helps because:
- in case of consoleTimer it works when moving cursor, but the problem which I've described in my str appears when simply typing.
- tdsr-NVDA might work, however I often have to access machines started from the Live cd over ssh, in which case installing anything on the linux side is not possible.

**Comment by lukaszgo1** [comment]
This is Tera Term specific ad least Secure CRT is free of this problem.

**Comment by lukaszgo1** [comment]
I have no idea which specific commit to master fixes it but with NVDA version alpha-17928,9dfbd2ee this is no longer happening. The version of Tera Term is still the same so it is definitely change in NVDA. Closing as works for me though I cannot add appropriate label.
