### ISSUE TITLE
"FOCUS HIGHLIGHT" addon in Word 2013 does not hghlight lines

### ISSUE THREAD

**Issue by carbontracking** [nvaccess/nvda#9018]
### Steps to reproduce:
Install the Focus Highlight addon
Open a Word document (only tested in Word 2013)

### Actual behavior:
I understood that the Focus Highmight would highlight the line currently being read.
However, in WOrd 2013 we see the entire page surrounded by the red line and the dotted green line never appears, as I would have expected it should.
### Expected behavior:

As I navigate from line to line, the dotted green line should surround the line that currently has focus 

#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
2018.3.2
#### Windows version:
Windows 10
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No

**Comment by josephsl** [comment]
CC @Nishomotz

**Comment by Adriani90** [comment]
cc: @nvdajp

**Comment by leonardder** [comment]
It might be that #8572 will improve this.

**Comment by nishimotz** [comment]
Good to hear that NVDA worked around this.
If something is wrong with the addon itself, please use the issue system as follows:
https://github.com/nvdajp/focusHighlight/issues

**Comment by Adriani90** [comment]
Is this issue fixed now with last versions of Focus highlight and NVDA?

**Comment by leonardder** [comment]
No, as #8572 is still open.

**Comment by Adriani90** [comment]
@carbontracking could you please test if this is still the case in NVDA
alpha-16437,7274f9ba

**Comment by Adriani90** [comment]
The PR referenced above has been merged, so I think this is fixed now. Otherwise please open a new issue against the visual highlight feature which is already implemented in NVDA. Closing.
