### ISSUE TITLE
Some Braille Display drivers gone missing

### ISSUE THREAD

**Issue by zersiax** [nvaccess/nvda#9023]
### Steps to reproduce:
1. Open NVDA's settings dialog and go to the Braille category.
2. Click the Change button.

### Actual behavior:
Only a subset of braille display drivers is listed. Logging reports the missing display drivers are excluded due to them reporting being unavailable.

### Expected behavior:
All supported display listed should be listed.

#### Other information about your system:
Snippet of the log set to debug includes the following:
```
DEBUGWARNING - braille.getDisplayList (14:44:18.611):
Braille display driver alva reports as unavailable, excluding
DEBUGWARNING - braille.getDisplayList (14:44:18.611):
Braille display driver baum reports as unavailable, excluding
DEBUGWARNING - braille.getDisplayList (14:44:18.611):
Braille display driver brailleNote reports as unavailable, excluding
DEBUGWARNING - braille.getDisplayList (14:44:18.612):
Braille display driver brailliantB reports as unavailable, excluding
DEBUGWARNING - braille.getDisplayList (14:44:18.612):
Braille display driver eurobraille reports as unavailable, excluding
DEBUGWARNING - braille.getDisplayList (14:44:18.612):
Braille display driver freedomScientific reports as unavailable, excluding
DEBUGWARNING - braille.getDisplayList (14:44:18.614):
Braille display driver handyTech reports as unavailable, excluding
DEBUGWARNING - braille.getDisplayList (14:44:18.614):
Braille display driver hims reports as unavailable, excluding
DEBUGWARNING - braille.getDisplayList (14:44:18.615):
Braille display driver superBrl reports as unavailable, excluding

```

**Comment by leonardder** [comment]
This is intentional. For the drivers that support braille display auto detection, de driver is only listed when there is a possible display to connect to.

**Comment by zersiax** [comment]
Alright, but the drivers in question are not listed to pick manually either. I cannot set my display to, for example, a HIMS display even though one is connected, idem for HandyTech. Starting to suspect this is a "only broken on my machine" issue, but don't have the slightest clue how that could have happened and how to fix.

**Comment by leonardder** [comment]
Could it be that you have installed Windows 10 braille support or brltty with libUSB? If your displays are ok, the drivers should definitely show up.

**Comment by zersiax** [comment]
Some more experimenting revealed the glitch. Closing this issue because it's not actully entirely caused by NVDA. Partly had to do with drivers getting in each other's way and me not realizing that the majority of drivers no longer show up in the list of braille display drivers when the corresponding device isn't connected.
