### ISSUE TITLE
Duplicated mergedVbufBackendLibs are causing new branch to appear with each git pull.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#9024]
First of all sorry for opening issue for such trivial problem, but there was no reaction to my  message to the NVDA devel mailing list and @JulienCochuyt [commend](https://github.com/nvaccess/nvda/pull/8866#issuecomment-442468866) In my opinion such issues are affecting image of the project in the bad way.
### Steps to reproduce:
1. Clone NVDA repository.
2. Perform git pull few times.
### Actual behavior:
Each time the new mergedVbufBackendLibs branch is fetched the only difference between them being capital and small letter b. I believe it is caused by GitHub problems when pull request with this branch was created. It is caused by the fact that NTFS is not case sensitive ad cannot handle this difference well.
### Expected behavior:
When there are no changes nothing should be fetched.
#### NVDA installed/portable/running from source:
N/A
#### NVDA version:
N/A
#### Windows version:
Windows 7 x64 but it is not system specific.
#### Name and version of other software in use when reproducing the issue:
Git for Windows
#### Other information about your system:
Deleting one of the branch probably the older one should be sufficient to fix this.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
N/A

**Comment by leonardder** [comment]
The duplicate has been removed.
