### ISSUE TITLE
NVDA suddenly becomes very slow after switching to an app that has been running for a long time

### ISSUE THREAD

**Issue by a11cf0** [nvaccess/nvda#9031]
### Steps to reproduce:
1. Open an application, e.g. Total Commander.
2. Switch out of it and leave it open for a relatively long time.
3. Switch back into its window.

### Actual behavior:
After that, NVDA sometimes becomes very sluggish and starts throwing lots of RPC  errors.
It's somewhat hard to then switch to a different app, but after doing that NVDA works just fine until I switch to the broken app again.
The only way to completely stop this is to close that broken app.

### Expected behavior:
NVDA should normally continue interacting with all apps.

#### NVDA installed/portable/running from source:
NVDA is installed.

#### NVDA version:
Latest alpha snapshot.

#### Windows version:
Windows 10 1803 and 1809 64-bit.

<<<#### Name and version of other software in use when reproducing the issue:
Total Commander, TeamTalk 5 and possibly some other apps I no longer remember.

#### Other information about your system:

[Log_fragment.txt](https://github.com/nvaccess/nvda/files/2659703/Log_fragment.txt)
#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA?
I have used several recent snapshots. All of them have this problem.

**Comment by DrSooom** [comment]
Maybe related to issue #9021. For me it sounds quite similar to it.

**Comment by Neurrone** [comment]
@DrSooom I think its different. The VS Code one is caused by the main window not registering as a child of the foreground object, so NVDA silently ignores all events, like focus events.

**Comment by a11cf0** [comment]
This problem still exists and is very annoying. I've noticed that it happens more often when NVDA is restarted before switching to a long running application.
Here's a recent more complete log fragment captured after restarting NVDA and then switching to Total Commander.
[fragment2.txt](https://github.com/nvaccess/nvda/files/2866036/fragment2.txt)

**Comment by Adriani90** [comment]
@a11cf0 how is this now with NVDA 2020.1?

**Comment by a11cf0** [comment]
> @a11cf0 how is this now with NVDA 2020.1?

It seems that this was fixed a long time ago. Nowadays I cannot reproduce this issue even on slowest PCs I have.
