### ISSUE TITLE
Python 3: file() function is no more

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9038]
Hi,

Continuing research on road blocks to Python 3 transition (see #7105 for rationale).

### Is your feature request related to a problem? Please describe.
Problem: in Python 3, file() function is no more.

Steps to reproduce:

1. Run Python 2 and 3 interpreters.
2. Try the following code path:

something = file(somefilename)

python 2: works as advertised.
Python 3: name error is thrown.

This is because in python 2, file() function is really a constructor for file objects (or a stream object treated as a file). The general recommendation from various sources is to use open() function to create a file object, and close it once finished. Another way is through a context manager (with statement).

### Describe the solution you'd like
The ideal solution is use of context manager syntax of the form:

with open(somefile, mode) as someMeaningfulName:
    dosomething …

Note: spaces are used for indentation.

### Describe alternatives you've considered
Another alternative is using the form:

something = open(somefile, mode)
code …
something.close()

Although applying this solution everywhere may sound consistent, there are cases (such as when opening and closing pickle files) where context manager syntax makes more sense.

### Additional context
The solutions proposed above are both Python 2 and 3 compliant, which should assist with #7105. So far, tests with a Python 3 version of NVDA indicate that open()/code/close() will work for the most part, but some code paths may benefit from use of context manager (I would say most would).

Thanks.

**Comment by josephsl** [comment]
Hi,

The affected files are:

* source/addonHandler/__init__.py
* source/buildVersion.py
* source/config/__init__.py
* source/gui/logViewer.py
* source/logHandler.py
* source/NVDAHelper.py
* source/updateCheck.py
* source/watchdog.py
* Any module (NVDA Core or add-ons) that deals with file I/O and uses file() function

Thanks.

**Comment by Brian1Gaff** [comment]
Blimey its getting more like Basic every day...:-)
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by feerrenrut** [comment]
Closed with https://github.com/nvaccess/nvda/pull/9663
