### ISSUE TITLE
Browse mode: Navigation with quick navigation keys on amazon webpage in e-book kindle store is broken

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#9040]
### Steps to reproduce:
1. Open this page
https://www.amazon.com/gp/product/B079R2H6M9/ref=s9_acsd_hps_bw_c_x_1_w/130-5096367-5995228?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=PFBR896NZQP9WQJJ9VJ2&pf_rd_r=PFBR896NZQP9WQJJ9VJ2&pf_rd_t=101&pf_rd_p=76be9779-6022-4a29-8358-8731ff59f084&pf_rd_p=76be9779-6022-4a29-8358-8731ff59f084&pf_rd_i=133140011
2. Press b to navigate by buttons multiple times
3. Press shift+b, h, shift+h etc.
4. Press down and up arrow
5. Press shift+h or h again

### Actual behavior:
The navigation with quick navigation key is not working after the first button or heading has been reported. NVDA says "no buttons" although there are lots of them. When pressing up or down arrow and then again quick navigation keys, it is working for the first element but then is not working again. There are also uncontrolled cursor movements which might be related to incorrect parameters for get.accrole.

### Expected behavior:
NVDA should navigate stable like on other web pages.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA 2018.4 RC1

#### Windows version:
Windows 10 1809 update

#### Name and version of other software in use when reproducing the issue:
Firefox 63.0.3, Google Crome 71.0

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No but I have many users who are using 2018.3.2 and they reported this issue as well.

**Comment by Brian1Gaff** [comment]
Is this not something we knew about a while ago. There was some discussion 
that it was page authoring. ie you could not actually buy from it.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment]
This seems solved in Firefox 65.0.2 and NVDA 2019.1 Beta 1. Closing as works for me.
