### ISSUE TITLE
Pressing escape in an aria menu brings the focus out of menu instead of keeping the focus at the element previously expanded.

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#9059]
### Steps to reproduce:
1. Open this website
https://is.wfu.edu/category/news,announcements,alerts/
2. Go to the menu elements and press nvda+space to activate focus mode
3. Press tab until you land on "WFU community
4. Press down arrow to expand it and to read the links into that element
5. Press escape to colaps it

### Actual behavior:
NVDA colapses the WFU Community menu item and it jumps out of the menu.

### Expected behavior:
Escape should colaps the menu item "WFU community" and the focus should stay on WFU Community.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2018.4 RC1

#### Windows version:
Windows 10 1809 Update

#### Name and version of other software in use when reproducing the issue:
Firefox 63.0.3, Google Chrome 71.

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA?
no

**Comment by Adriani90** [comment]
I propose to implement a second action. when pressing escape once, NVDA should colaps the menu item. When pressing it twice, NVDA should leave the menu.

**Comment by Neurrone** [comment]
This is probably a problem with the site itself.

**Comment by Adriani90** [comment]
Ok it seems solved in Firefox 71, Chrome 79 and NVDA 2019.3 Beta 1. The focus stays not on the previously expanded menu item after pressing escape but at least it remains in the menu. Closing as works for me.
