### ISSUE TITLE
Audio ducking: Volume remains lowered when pressing ctrl after turning speech off with nvda+s

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#9070]
### Steps to reproduce:
1. Open NVDA and set audio ducking in synth settings to "duck when ouputting speech and sounds"
2. Open a song or a video with sound
3. Press something so NVDA speaks and ducks the audio
4. Press NVDA+s (laptop layout) to turn off speech
5. Press e.g. ctrl key to unduck audio

### Actual behavior:
Audio volume should be readjusted to the volume before ducking.

### Expected behavior:
Audio remains ducked although speech and tones are turned off.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2018.4 RC2

#### Windows version:
Windows 10 1809 Update

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA?
no

**Comment by leonardder** [comment]
I can't reproduce this with insider build 18298

**Comment by Adriani90** [comment]
Closing as works for me. I found out that this issue was occuring due to an outdated romanian synthesizer. Testing with eSpeak and Onecore voices, the issue is not reproducible.
