### ISSUE TITLE
Python 3: use native range function instead of six.moves.range for xrange/range differences

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9078]
Hi,

Another syntax issue to resolve:

### Is your feature request related to a problem? Please describe.
Python 3 unifies range iteration by renaming xrange to range. For code that relies on xrange, it will fail in Python 3 unless edited to call range function.

### Describe the solution you'd like
There are two possibilites:

1. Native: convert xrange() to range().
2. Compatbility shim: use six.moves.range for iteration, and in case a list is needed, wrap tthe call inside a list call.

I propose going with the second solution for now.

### Describe alternatives you've considered
The native mode alternative doesn't require six module. However, because some community add-ons may not be updated to support Python 3 right away, it would be beneficial to provide guidance through use of six module.

### Additional context
This is one of the key differences between Python 2 and 3 and must be resolved before full switch to Python 3 takes place.

Thanks.

**Comment by leonardder** [comment]
> I propose going with the second solution for now.

Agreed. I think this is what python modernize does as well.

**Comment by josephsl** [comment]
Hi,

I'm closing this softly - that is, left open until #7105 becomes a reality. In the end, I believe a straight native implementation is much better and cleaner.

Thanks.

**Comment by josephsl** [comment]
Hi,

Update: I'm going with native mode (editing the title accordingly).

Thanks.

**Comment by feerrenrut** [comment]
Fixed with #9627
