### ISSUE TITLE
Python 3: use next(iter) instead of iter.next()

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9086]
Hi,

Yet another syntax issue to resolve:

### Is your feature request related to a problem? Please describe.
In Python 2.x, it was possible to go through iterators via iter.next() method. This was made simple in Python 2.6 with the built-in next() function, and this is the only method for built-in iteration control in python 3.

### Describe the solution you'd like
As NVDA uses Python 2.7, it will be able to work with next(iter), making it compatible with Python 3. This will affect the following modules:

* GUI/settings dialogs: retrieving options for one or two settings.
* Event handler: handling next chain of events.
* Say all handler: say all generator.

### Describe alternatives you've considered
None

### Additional context
None

**Comment by josephsl** [comment]
Hi,

In case of eventHandler.EventExecutor object, I think it can be ignored, as it defines its own next() method that already uses Python 3 next(iter) idiom.

Thanks.

**Comment by leonardder** [comment]
> In case of eventHandler.EventExecutor object, I think it can be ignored, as it defines its own next() method that already uses Python 3 next(iter) idiom.

Note that python 3 uses __next__ instead of next. Also, looking at the _EventExecuter init function, it executes self.next() instead of next(self). These are pretty trivial though.
