### ISSUE TITLE
sublime accessibility

### ISSUE THREAD

**Issue by esmobg** [nvaccess/nvda#9088]
hello i am a visual emapred  web developer and in the company i am working i use sublime can anyone create an add-on that allows the nvda to work with this editor thank you

**Comment by leonardder** [comment]
Could you please provide information on the things that don't work for you?

**Comment by esmobg** [comment]
Nvda not  read main  menu on text editor 
and  not  read  insert code and  tags 

thanks  for   your   help

**Comment by esmobg** [comment]
hi  and  happy new  year attache screen shot  for  sublime   

nvda  not read  is here 
![2019-01-02](https://user-images.githubusercontent.com/13334643/50598868-cb58b000-0eb4-11e9-8808-1243e07600f2.png)

**Comment by esmobg** [comment]
hi  everyone  attache   sublime accessibility  log file 
[accesability   sublime  log  file.txt](https://github.com/nvaccess/nvda/files/2737075/accesability.sublime.log.file.txt)

**Comment by Adriani90** [comment]
@esmobg how is this now with NVDA 2024.2 Beta and Sublime dev 4175?
https://www.sublimetext.com/dev
Are these issues still occuring for you? Did you already contact the Sublime developers to request accessibility improvements?

**Comment by Adriani90** [comment]
We didn't geht any updates upon request since more than 5 years, closing as abandoned. If you are still having this issue, please comment and we can reopen.
