### ISSUE TITLE
NVDA to announce smilies etc

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#909]
**Reported by dharvey on 2010-09-16 05:56**
Hi,

I've noticed a lot of my friends use these graphical smilies and other stuff used on Facebook EG smily or sad face.

Having a dictionary or setting in NVDA to announce such characters since I find it confusing when my firnedsfriends use them and I don't know what they mean.

**Comment by jcsteh** [comment]
Closing as duplicate of #1680, since it has more recent discussion.
