### ISSUE TITLE
no output when using delete key in many text fields

### ISSUE THREAD

**Issue by mehgcap** [nvaccess/nvda#9094]
### Steps to reproduce:
Write some text, left arrow a few characters, and hit the delete key (NOT the backspace key.

### Actual behavior:
NVDA says nothing, even though it does speak characters when the backspace key is used, and a connected braille display does not refresh. Pressing any arrow key will update things, as will typing a character or using backspace.

### Expected behavior:
NVDA should react the same way it does when using backspace.

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2018.4

#### Windows version:
Windows 10, 1809 update installed

#### Name and version of other software in use when reproducing the issue:
Various text fields act different ways. The latest Notepad Plus Plus causes NVDA to do nothing when deleting, while Firefox 64 text fields seem to update braille but not speak any characters as they are deleted. I also work in SSH a lot, and find no refreshing whatsoever as I delete in Nano on a remote server. Finally, you can see the behavior if you try to delete while renaming a file or folder in Windows Explorer.

#### Other information about your system:
Nothing relevant.

#### Does the issue still occur after restarting your PC?
Yes. In fact, I noticed it a year or more ago. This is a regression, not a behavior that has always been present, as far as I can tell.

#### Have you tried any other versions of NVDA?
See above; this has been present for many versions. I have not tried any betas or snapshots after the public 2018.4 release.

**Comment by DrSooom** [comment]
Maybe this issue is caused by a too small window size.

**Comment by mehgcap** [comment]
Sorry for the delay.

* "speak typed characters" and "speak typed words" are both not checked
* "speech interrupt for typed characters" and "speech interrupt for enter key" are both checked
* I can reproduce the issue with no display connected

Now, the crazy thing: I have so far been unable to reproduce the issue on my home PC. It and my work PC are both running the latest Windows 10, with identical NVDA versions, though not identical configurations. I have set each one up from its defaults, not copying any configurations between the machines. That said, I had to re-install Windows at work a few months back, and the problem was present before and after the re-install. At home, on another new Windows 10 install, the delete key and NVDA play nicely together, just at one would expect.

I wonder if there's any way the issue could be tied to the keyboard? I don't have another keyboard at work just now, or I'd try that. It's all I can think of, as weird and unlikely as it sounds.

**Comment by mehgcap** [comment]
After 2019.1.1, with the same work PC and keyboard I've been using all along, this issue seems to be fixed. I don't know whether that was intentional, accidental, or a complete coincidence, and I'll likely never know. For now, though, it's fixed!
