### ISSUE TITLE
Cursor routing from a braille display not working in PowerPoint

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#9101]
STR:
1. Ensure that a braille display is connected and braille is enabled.
2. Open PowerPoint.
3. Press Enter on the title or subtitle object.
4. Enter some text.
5. Press a cursor routing button over the text on the braille display.

- Expected: The cursor moves.
- Actual: No change.

Tested with PowerPoint 2013 and 2016.

**Comment by dkager** [comment]
Probably because (in appModules\powerpnt.py):

```
			#TextRange objects in Powerpoint do not allow moving/expanding.
			#Therefore A full TextRange object must be fetched from the original TextFrame the selection is in.
```

I wonder if UIA could be of use here.

**Comment by leonardder** [comment]
I was able to successfully move within such a text range when enforcing UIA in Office 2016.

**Comment by Adriani90** [comment]
cc: @michaelDCurran

**Comment by MarioBatusic** [comment]
This Issue still occurs also with Freedom Scientific Focus 40 and Focus 14 and Office 2016.

**Comment by amenaide** [comment]
I can confirm this issue still persists wit Office 365. I'm using a Mantis q40 and a Handy Tech Easy Braille, the issue occurs on both devices.
