### ISSUE TITLE
read of typed characters is broken in wsl with tmux

### ISSUE THREAD

**Issue by OSadovy** [nvaccess/nvda#9102]
### Steps to reproduce:
* ensure wsl bash on windows is installed, and install tmux package in it
* press <windows>,  type "bash" and press enter
* type "tmux"
* type anything, eg: "echo hello world"
### Actual behavior:
NVDA says "space" on each character input. sometimes it will read random characters not related to those typed.

### Expected behavior:
NVDA should read characters that user actually types

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2018.4
#### Windows version:
windows 10, Version 1809 (OS Build 17763.194)

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
It used to work before on NVDA 2018.3 atleast. I recently updated NVDA and installed latest windows 10 updates, so I am not sure which exactly caused the regression.

**Comment by OSadovy** [comment]
I downloaded nvda_2018.3.exe and tested by just running the installer and performing described steps with NVDA running from it. Seems the bug is windows-related, because I get actual result, not an expected one :(

**Comment by Adriani90** [comment]
cc: @codeofdusk, @josephsl

**Comment by OSadovy** [comment]
Can't reproduce it with latest NVDA and Windows.
