### ISSUE TITLE
Access to the text editor in SQL Server Management Studio

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#912]
**Reported by charless on 2010-09-17 10:48**
Is it possible to add support for the editor in SQL Server Management Studio 2008? I am very glad you have added support for the Visual Studio editor and I think the control types of these  editors do not differ very much. I would appreciate it very much.

**Comment by leonardder** [comment]
I think this can be closed due to the report in https://github.com/nvaccess/nvda/issues/912#issuecomment-155284757. Version 2008 is probably obsolete. If people want support for the most recent version of SQL Server Management Studio, they can open a new issue.
