### ISSUE TITLE
Shift key does not pause speech

### ISSUE THREAD

**Issue by dangmanhcuong87** [nvaccess/nvda#9123]
Shift key does not pause speech on Windows 10 v 1809.
### Steps to reproduce:
- Run NVDA.
- Open a dialog to make NVDA read.
- Press the Shift key.
### Actual behavior:
- NVDA continue reading the current content.
### Expected behavior:
- NVDA pauses speech, and resume if pressing shift key again.
#### NVDA installed/portable/running from source:
- NVDA installed.
#### NVDA version:
2018.4.
#### Windows version:
- Windows 10 Version 1809 (OS Build 17763.195).
#### Name and version of other software in use when reproducing the issue:
- Tested multiple time using the Run dialog.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No.

**Comment by josephsl** [comment]
Hi, can you try it again after restarting with all add-ons disabled? Thanks.

**Comment by dangmanhcuong87** [comment]
Hi
I've just tried that step, and the problem still occurs. This also occurs on my friend's laptop running Windows 10 v 1809.
Thanks
Cuong
----------------
Dang Manh Cuong
 The Assistive technology specialist
 Sao Mai Vocational and assistive center for the blind
52/22 Huynh Thien Loc St., Hoa Thanh ward, Tan Phu dist., HCM, Vietnam.
 Tel: +8428 7302-4488
 E-mail: info@saomaicenter.org; tech@saomaicenter.org
 Facebook: https://www.facebook.com/saomaicenterfortheblind
 Website: http://www.trungtamsaomai.org; http://www.saomaicenter.org  Mobile 
/ Zalo: +84 902-572-300
 E-mail: dangmanhcuong@gmail.com; cuong@saomaicenter.org
 Skype name: dangmanhcuong
 facebook: http://facebook.com/dangmanhcuong
 Twitter: @ManhCuongTech
NVDA Certified Expert: https://certification.nvaccess.org/
  ----- Original Message -----

**Comment by dangmanhcuong87** [comment]
Hello all  
I solved the problem by completely removing, and reinstalling NVDA. Additional info, I've install NVDA for the first time in about 2012 - 2013, then created the portable version from that point. When reinstall Windows, or change to another computer, I just install that portable version to the new OS. When the update came, I just install update, and make the new portable that overwrite the old one and keep in my hard drive. Is this the reason why the problem occurs?

**Comment by Brian1Gaff** [comment]
I've not seen this myself, but I guess any kind of corruption could creep in 
and so it is, I think a good plan to use a clean install if things seem to 
be doing odd things. I do tend to manually save the configuration folders of 
nvda from time to time and then if I need a new install I can restore things 
again, and then if that breaks something, then at least I know the configs 
are corrupted.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment]
I had also some spooky issues with NVDA after a long time of using portable copy and reinstalling it from the copy. But it was not so often and yes I could also solve it by using a clean install.

**Comment by Adriani90** [comment]
@ehollig I think we can close this issue since the problem seems solved.

**Comment by ehollig** [comment]
Closing as requested.

**Comment by dangmanhcuong87** [comment]
Hi all
afew day ago I asked about a braille display but I did misspell so that may cause no answer. So sorry for that. I want to use the baum vario pro80 with NVDA but don't know if NVDA support for this or not, and if it has been supported, how do I get driver for it? Searched on Google, I see an NVDA issue on github about this display, but sound I don't understand clearly the issue.
Any help would be appreciated.
Cuong
----------------
Dang Manh Cuong
 The Assistive technology specialist
 Sao Mai Vocational and assistive center for the blind
52/22 Huynh Thien Loc St., Hoa Thanh ward, Tan Phu dist., HCM, Vietnam.
 Tel: +8428 7302-4488
 E-mail: info@saomaicenter.org; tech@saomaicenter.org
 Facebook: https://www.facebook.com/saomaicenterfortheblind
 Website: http://www.trungtamsaomai.org; http://www.saomaicenter.org
Mobile / Viber / WhatsApp / Zalo: +84 902-572-300
 E-mail: dangmanhcuong@gmail.com; cuong@saomaicenter.org
 Skype name: dangmanhcuong
 facebook: http://facebook.com/dangmanhcuong
 Twitter: @ManhCuongTech
NVDA Certified Expert: https://certification.nvaccess.org/
