### ISSUE TITLE
Having problems with word and firefox.

### ISSUE THREAD

**Issue by xethea** [nvaccess/nvda#9125]
Hello

I am having problems in word and fire fox. I use eloquence and it reads symbols differently. Instead of an apostrophe it will read yuro. my language in windows and word is inglesh so I do not understand why this is happening.
In fire fox when I go to enter links and I push both enter and space a menu will come up instead of entering into the link. I have to push the NDVA key and space then push enter to enter the link.

**Comment by xethea** [comment]
I have factory reset NDVa so that is not the problem. I have even switched to an earlier version and it still happens.

**Comment by Adriani90** [comment]
I had something weared like this before. Please look into your speech dictionaries in NVDA menu. Are there any entries which you do not expect?

**Comment by xethea** [comment]
how do I access the speech dictionary entries?

**Comment by xethea** [comment]
there is nothing really odd in the dictionary entries in fact there is nothing at all. Is this normal? I've looked in all three speech dictionaries.

**Comment by xethea** [comment]
Hello everyone
Here are the things I have tried to get NDVA to work on fireFox and word.
I tried reader mode, but it wasn’t stuck there.
I have factory reset NDVA 2 or 3 times.
I’ve looked in accessability on FireFox but that was not it.
I have uninstalled and then reinstalled NDVA.
I have even reset my own pc, but that didn’t help.
My speech dictionaries have no entries so that is not the problem.
I have also installed earlier versions of NDVA, but that did not help at all.
I've removed all the check boxes in input and object presentation, but none of that helped at all.
I've removed the check boxes dealing with different languages.
I went into settings and made sure my language was english.
Other Synthes do not have inflection in their voices and I do not like E speak. If anyone has any suggestion I am open to them.
Xethea

**Comment by Adriani90** [comment]
Did you try to use another eloquence addon? Which one are you using? The one from codefactory is good I think. It costs something but hey, this whole project is free otherwise. So paying a little bit for something like this is not a mess in my opinion. It might be related to eloquence. With eSpeak it works properly. Right?

**Comment by Adriani90** [comment]
Which windows version are you using? In Windows 10 please try with the onecore voices. Does the issue occur also with Onecore voices?

**Comment by xethea** [comment]
Hello

I'm using windows 10. I don't use one core it has no inflection. Maybe I could try code factory. depending on how much code factory is I might buy it. I agree it would definitely help since this intire screen reader is free. I have not been having problems up until now.

**Comment by xethea** [comment]
I bought the code factory add on, but the problem still remains that I can not push on any links without going into the virtual cursor with NDVA and space. Is there some way I can access links without pushing enter or space? Or maybe it's a FireFox problem? What do you think?

**Comment by Adriani90** [comment]
@xethea ok that means the pronounciation is now correct with codefactory addon?

**Comment by Adriani90** [comment]
@xethea did my suggestions above help you to solve your problems? Are you still having this issue in NVDA 2019.2?

**Comment by Adriani90** [comment]
We do not have any updates from the author since more than one year. Closing. Please comment on it if you still have this problem and we can reopen it. Thanks.
