### ISSUE TITLE
NVDA cuts words and reports parts of different elements together on one key press; first occurance since nvda 2018.4

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#9129]
First of all my big apologize that I didn't report this earlier, I thought it might not be an impacting issue and was not sure it is an NVDA bug. But after hearing reports from many other users and comming myself accross this issue, here it is:

### Steps to reproduce:
1. Open Youtube for example
https://www.youtube.com/watch?v=GXiPqdN575E
It is also reproducible on github and other websites.
2. Pause the video or press mute
3. Now in browse mode, navigate with b and shift+b through the video area (press o to land directly to the embeded video object)
4. Navigate with arrow keys through the video area

### Actual behavior:
NVDA pronounces only parts of the label of buttons. Some labels are sticked together and pronounced together by NVDA. Short keys for the buttons are pronounced wrong or are sticked together with short keys of other buttons. In short, the behavior in browse mode seems quite broken. Notice also the mute button which is being ocasionally skipped by NVDA when navigating with arrow keys through the video area.

### Expected behavior:
When pressing b or shift+b, NVDA should pronounce a single button and its assigned short key. When navigating with arrow keys, the mute button should not be skipped.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2018.4

#### Windows version:
Windows 10 1809 Update

#### Name and version of other software in use when reproducing the issue:
Firefox 64.0

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA?
Yes 2018.3.2 works much better.

**Comment by Adriani90** [comment]
In Google Chrome 71, NVDA 2018.4 works fine but it still repeats other elements after reading the current element to which you navigate with b or shift+b.

**Comment by Adriani90** [comment]
so the issue is most obvious in Firefox.

**Comment by Adriani90** [comment]
cc: @mltony

**Comment by ABuffEr** [comment]
> so the issue is most obvious in Firefox.
Alberto:
Absolutely. In my experience, it's a very, very old issue, but using NoScript and other add-ons for page control in Firefox, I always thought it was quite normal. If, on other hand, it happens also with standard configuration and in other browsers, well... it should be resolved :)
If it can help, I noticed that playing with window maximizing/resizing (from system menu and occasionally using resize tool provided by AnVir Task Manager Free) generally reduces the impact of issue, but consider also that many pages run JavaScript to change window appearance, as it probably happens in YouTube for a better vision.

**Comment by mltony** [comment]
I think I could reproduce this issue in both Chrome and Firefox. It seems to me this is a manifestation of rubber band effect of browse mode - when you move to next element either via down arrow or quicknav keystroke, sometimes it bounces back and reads the previous element instead.
I tried my fast_browse_mode pull request on it and it indeed behaves much better on this website - it doesn't skip buttons and is more predictable.

**Comment by mltony** [comment]
Please try NVDA build with FastBrowseMode to see if it resolves this issue:
https://github.com/mltony/nvda/releases/download/FastNVDA_alpha_2019_01_21/nvda_snapshot_source-fast_nvda-7c9d81a.exe

**Comment by Adriani90** [comment]
This is still reproducible in NVDA 2019.3 Beta 1. Disabling "automatically move system focus to focusable elements" with nvda+8 solved it but this experimental feature still has other issues.

**Comment by Adriani90** [comment]
Now that #11190 made automatically set focus to focusable elements as default behavior, this issue is fixed. Closing.
