### ISSUE TITLE
wxPython 4.0.4/future: GUI controls show generic labels instead of what's defined in NVDA source code

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9130]
Hi,

Although this bug report won't affect current NVDA releases, it'll affect future GUI/wxPython work as we move onto Python 3 and beyond:

### Background:
On January 6, 2019, wxPython 4.0.4 was released. The most exciting change is addition of wx.Accessible wrapper for MSAA, which gives programmers a way to expose accessibility information for IAccessible clients such as NVDA. However, NVDA itself does not expose proper MSAA information for its own GUI controls, instead presenting generic control labels for various roles such as wx.Choice, wx.ListCtrl and others.

### Steps to reproduce:
Install wxPython 4.0.4 and run NVDA from source code. Then open NVDA Settings screen and look at various controls on screen visually as well through keyboard navigation.

### Actual behavior:
Generic control labels are announced by NVDA.

### Expected behavior:
Actual control labels defined in the source code are announced.

#### NVDA installed/portable/running from source:
Running from source

#### NVDA version:
Alpha.16477

#### Windows version:
Windows 10 Version 1809

#### Name and version of other software in use when reproducing the issue:
wxPython 4.0.4

#### Other information about your system:
None

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes - 2018.3, 2018.4, current alpha binary version (powered by wxPython 4.0.3)

### Impact:
This will impact future wxPython version upgrade considerations (such as moving from 4.0.x to 4.1.x), as future versions will include wx.Accessible (which is enabled on Windows by default).

Thanks.

**Comment by leonardder** [comment]
This is definitely an issue in WX Python.

The constructor of a control, i.e. a checkbox, has the name attribute. IN the case of Checkbox, it defaults to wx.CheckBoxNameStr. IN the case of slider, it defaults to wx.SliderNameStr.
The new situation seems to imply that the accessible name is set to the name property of  the control, thereby ignoring the label. While it makes sense to add the ability to set the accessible name at control creation time, it doesn't make sense at all to prefer a generic name (like slider or check) over the label of a control.

II'm afraid this will have major negative impact on every application that uses WX. I think that we'll have to express our concerns in a github issue against wxPython.

**Comment by josephsl** [comment]
Hi, I already have: wxwidgets/phoenix issue 1129. Thanks.

**Comment by leonardder** [comment]
> Although this bug report won't affect current NVDA releases, it'll affect future GUI/wxPython work as we move onto Python 3 and beyond:

Actually, we'll always use a custom build of wxPython I believe, and accessibility support can be easily disabled in which case the native accessibility implementation for the controls will be used. Therefore in practice, we won't suffer from this issue. I'm tempted to close this, unless @josephsl has strong objections.

**Comment by josephsl** [comment]
Hi,

Update: resolved in 4.1.0-dev (powered by wxPython master/3.1.x). I'm closing this for now.

Thanks.
