### ISSUE TITLE
NVDA's documentation still references help balloons

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#9131]
While NVDA's Object Presentation dialog presents the option for reporting notifications, the User guide does not reference this setting properly. Instead, it still refers to the option as 'Report help balloons'. The description also still speaks about help balloons only, rather than speaking about balloons and toasts.

I suggest this is fixed in the user guide, and the description be updated to reflect the use of these notifications in later versions of Windows.

As an aside, section 8.1, Control Type, State and Landmark abbreviations still has an abbreviation for 'help baloons' (wrong spelling), but I don't know if this should also be changed.

**Comment by josephsl** [comment]
Hi, ah this one – I’ll queue it for docs19.1 branch once beta goes live. Thanks for bringing this up.

**Comment by fisher729** [comment]
Hi.

This issue seems to have been forgotten. It can be quite confusing for new users.

**Comment by knowledgebaum** [comment]
Has this issue been resolved?

**Comment by josephsl** [comment]
Hi, someone is working on it (last time I checked). Thanks for reminding us about this inconsistency.
