### ISSUE TITLE
Does not Speak when Deleting character by pressing shift.

### ISSUE THREAD

**Issue by gauravahir28** [nvaccess/nvda#9132]
While trying to delete a character when shift is pressed, the nvda does not speak anything.
It should reade the character which is getting deleted even if shift is pressed.

**Comment by leonardder** [comment]
Please provide additional information, such as what editor you're using to reproduce this on what Windows version, with what version of NVDA?

**Comment by DataTriny** [comment]
I can reproduce the issue in any kind of editable text with latest alpha version of NVDA, on Windows 10 version 1809, but I don't see why @gauravahir28 would remove text this way. It's simply that `EditableText._hasCaretMoved` is not triggered when pressing shift+backspace. However, Windows still delete the text, so we are loosing a bit of information.
