### ISSUE TITLE
Launcher: Update to latest build of NSIS to address potential Security Issues

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#9134]
NVDA is currently built with NSIS 2.51; however, in the latest builds of the installer several security issues have been address that could result in potential DLL hijacking (see https://nsis.sourceforge.io/Docs/AppendixF.html and search for "security" for more info). To prevent this, could we update to the latest NSIS build?

**Comment by leonardder** [comment]
Note that the launcher is only used to start NVDA from it, it doesn't perform the installation itself.

Having said that, I've thought about updating NSIS as well, but it doesn't have that much priority. Giving it p3 for now.

**Comment by dingpengyu** [comment]
hello
[NSIS 3.05 release](https://nsis.sourceforge.io/Docs/AppendixF.html#v3.05)
thanks

**Comment by dingpengyu** [comment]
hello
This is the pull_request of NSIS to version 3.05, mainly to upgrade nsis from 2.51 to 3.05.
[Upgrade NSIS to version 3.05 to address potential security issues.](https://github.com/nvaccess/nvda-misc-deps/pull/16)
thanks

**Comment by seanbudd** [comment]
Closed via #13398
