### ISSUE TITLE
nvda is not reading information on the sharing links

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9143]
### Steps to reproduce:
for example open this page:

https://blogs.windows.com/windowsexperience/2019/01/09/announcing-windows-10-insider-preview-build-18312/#xWRjOUGvrzJt8Zur.97

when opening the page, walk with the arrows below until the nvda begins to read the links:
This link opens in new window

See that nvda only read this, however when reading the same link with the voice over on the iphone the voice over read what the nvda speaks, and still read the name of the site that this link will open to share this news as twiter, facebook , among others.
I only noticed this behavior in the microsoft pages but I can not say that this happens penalties in these pages.
I tried to read long descriptions in this most unsuccessful links.

### Actual behavior:
can not read only
This link opens in new window
### Expected behavior:
nvda should read
This link opens in new window
Followed by the website that will open when you open the link.
#### NVDA installed/portable/running from source:
install
#### NVDA version:
alfa 16530
#### Windows version:
10 1809 17763.253
#### Name and version of other software in use when reproducing the issue:
chrome 71
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
yes

**Comment by Adriani90** [comment]
This works as expected with NVDA alpha-20175,9967903a in Chrome 81. Closing as works for me.
