### ISSUE TITLE
Add alternative way to report name of the current Excel sheet which don't require moving review cursor into Excel window

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#9147]
### Is your feature request related to a problem? Please describe.
I am often working with Excel workbooks containing multiple sheets and at the same time reading some instructions or data in another program with review cursor to avoid moving back and forth between two windows. In this case there is no easy way for me to determine in which sheet I am, because NVDA+ numpad delete works only when review cursor is in the Excel window.
### Describe the solution you'd like
There should be a command (NVDA+Alt+s perhaps) to announce name of the current sheet. 
### Describe alternatives you've considered
NVDA+tab might eventually announce current sheet name or maybe NVDA+t.
### Additional context
For the sighted users the sheet name is visible regardless of how many windows they have open, in which window they mouse cursor is if the Excel window is visible. Furthermore we are interested in the sheet in which we have focus not in the sheet in which our review cursor is similar to NVDA+tab. I understand that in the default config they are in the same place, but if we aren't accounting for the users which are using it separately why even create options to make them separate.

**Comment by josephsl** [comment]
Hi, NVDA+Numpad Delete (NvDA+Delete in laptop layout) should read current sheet name (or at least the sheet number) along with cell coordinates. Thanks.

**Comment by lukaszgo1** [comment]
NVDA+numpad delete would read current sheet name only if the review cursor is placed in the Excel window, that why I have created this issue in the first place.

**Comment by leonardder** [comment]
I think it would make sense to have a script that reports the focus object along with its focus ancestors (i.e. the ancestors that are shown in braille as well.

**Comment by lukaszgo1** [comment]
@leonardder wrote:
> 
> 
> I think it would make sense to have a script that reports the focus object along with its focus ancestors (i.e. the ancestors that are shown in braille as well.


Are there other cases in which such script might be useful in your opinion? If so, are you going to work on this?

**Comment by leonardder** [comment]
C can't think of any other advantages, but pretty sure that it makes sense to have such a script.
We can do one of the following:
1. _implement a new script:
2. Extend the report focus script to report ancestry at the third activation.

**Comment by lukaszgo1** [comment]
@leonardder  @derekriemer While your proposals presented here and in #10501 are pretty interesting I went with much simpler approach in #13060 which merely allows  to report `locationText` for the caret position. If you still have use cases for scripts reporting focus / navigator object ancestry please create a separate issues for them.
