### ISSUE TITLE
Element list is visually broken when display resolution is not high

### ISSUE THREAD

**Issue by nishimotz** [nvaccess/nvda#9148]
### Steps to reproduce:

* Set Windows desktop resolution to 1024x768
* Launch Chrome and visit https://www.nvaccess.org/
* Press NVDA+F7 to open element list dialog

### Expected behavior:

* All buttons of element list are visually shown and operable

### Actual behavior:

* The controls below the tree view are visually hidden (screenshot is attached)

![image](https://user-images.githubusercontent.com/76300/51084072-8a3f8600-1767-11e9-9e87-adb6ddc48c59.png)

#### NVDA installed/portable/running from source:

* portable

#### NVDA version:

* NVDA 2018.4

#### Windows version:

* Windows 10 version 1803 (64bit)

#### Have you tried any other versions of NVDA?

* This occurs with NVDA 2018.1.1 as well

* With NVDA 2016.3, controls such as "Filter by," "Activate," "Move to," "Cancel" are shown as expected.

![image](https://user-images.githubusercontent.com/76300/51084960-dabde000-1775-11e9-82b8-b6769a927153.png)

**Comment by leonardder** [comment]
This can be covered by adding the gui.dpiScalingHelper.DpiScalingHelperMixin to the elements list dialog.

**Comment by nishimotz** [comment]
#10655 is duplicate of this issue, and it was fixed.
