### ISSUE TITLE
Labels reading twice on checkboxes that are styled position relative

### ISSUE THREAD

**Issue by ghost** [nvaccess/nvda#9155]
### Steps to reproduce:
https://codepen.io/webknit/pen/OrdKRe
Tab to checkboxes, label should be read once "test label check box  not checked".

### Actual behavior:
label is read twice "test label test label check box  not checked"
This only seems to happen when the labels are set to position: relative; (I have added two sets of checkboxes to tab through and demonstrate this, one without the label styled).

### testing
seems to work fine on IE and FF, I only only experiencing issues on the following.
chrome - V71
NVDA - 2018.4.1
Windows 10
(Have also tried with static web file and same issue arises so the Codepen iframe etc isn't having any impact)

**Comment by GaloisGirl** [comment]
I have the same issue on https://demos.telerik.com/kendo-ui/styling/checkboxes with Chrome 77.0.3865.120. 

It's even worse on Firefox 70.0: the labels aren't read at all!

I'm using NVDA 2019.2.1

**Comment by Adriani90** [comment]
@ghost, @GaloisGirl I cannot reproduce the double speaking issue with Chrome and Edge 112 or with Firefox 111. Do you still have this issue with NVDA 2023.1?

@jcsteh regarding the focus being stuck on the checkbox in a grouping, I can still reproduce that with the link in the initial description. When I tab to the group of checkboxes, afterwards NVDA does not move the focus anymore when pressing tab. This does not occur in Chrome or Edge. I think there is already an issue on Github which covers this but I cannot find it.

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author upon request since many years, and I cannot reproduce the issue. For the part of the tab navigation being locked, please create a new issue filling the issue template.
If labels of checkboxes are still read twice for you with NVDA 2024.2 Beta, please comment and we can reopen. I am closing as abandoned.
