### ISSUE TITLE
In Chrome, Contents of Bootstrap Modal Not Voiced by NVDA

### ISSUE THREAD

**Issue by eugeneborodkin** [nvaccess/nvda#9156]
### Steps to reproduce:
JSFiddle: https://jsfiddle.net/jnv07akx/
In the Bootstrap Modal in this JSFiddle, when hovering or selecting anything inside the modal, NVDA in Firefox voices the elements, but NVDA in Chrome does not.

### Actual behavior:
JSFiddle: https://jsfiddle.net/jnv07akx/
In the Bootstrap Modal in this JSFiddle, when hovering or selecting anything inside the modal, NVDA in Firefox voices the elements, but NVDA in Chrome does not.

### Expected behavior:
NVDA in Chrome voices the elements inside the Bootstrap Modal, both paragraph text and selectable controls, similar to Firefox. Whatever is selected should get voiced by NVDA.

#### NVDA installed/portable/running from source:
Installed, running in background, Windows desktop

#### NVDA version:
2018.4

#### Windows version:
10

#### Name and version of other software in use when reproducing the issue:
Chrome:  71.0.3578.98 (Official Build) (32-bit)

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by Adriani90** [comment]
In NVDA 2020.1 I get following error:
```
IO - inputCore.logTimeSinceInput (23:48:54.295) - MainThread (6080):
0.043 sec since input
IO - speech.speak (23:48:54.295) - MainThread (6080):
Speaking ['Leer']
IO - speech.manager.SpeechManager._pushNextSpeech (23:48:54.296) - MainThread (6080):
Sending to synth: ['Leer  ', IndexCommand(3298)]
DEBUGWARNING - RPC process 11904 (chrome.exe) (23:48:54.309) - Dummy-8109 (3964):
Thread 12548, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::findNodeByAttributes, 967:
 offset 0 is past end of buffer, returning NULL

DEBUGWARNING - RPC process 11904 (chrome.exe) (23:48:54.319) - Dummy-8109 (3964):
Thread 12548, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::locateTextFieldNodeAtOffset, 859:
Offset 0 out of range. Returnning NULL

DEBUGWARNING - RPC process 11904 (chrome.exe) (23:48:54.321) - Dummy-8109 (3964):
Thread 12548, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::locateControlFieldNodeAtOffset, 879:
Could not locate node at offset, returning NULL

DEBUGWARNING - virtualBuffers.VirtualBufferTextInfo._getNVDAObjectFromOffset (23:48:54.329) - MainThread (6080):
Couldn't get NVDAObject from offset 0
DEBUGWARNING - browseMode.BrowseModeDocumentTreeInterceptor._set_selection (23:48:54.329) - MainThread (6080):
Invalid NVDAObjectAtStart
IO - inputCore.InputManager.executeGesture (23:48:54.643) - winInputHook (9252):
Input: kb(laptop):NVDA+space
DEBUGWARNING - RPC process 11904 (chrome.exe) (23:48:54.669) - Dummy-8109 (3964):
Thread 12548, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::locateTextFieldNodeAtOffset, 859:
Offset 0 out of range. Returnning NULL

DEBUGWARNING - RPC process 11904 (chrome.exe) (23:48:54.678) - Dummy-8109 (3964):
Thread 12548, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::locateControlFieldNodeAtOffset, 879:
Could not locate node at offset, returning NULL

DEBUGWARNING - virtualBuffers.VirtualBufferTextInfo._getNVDAObjectFromOffset (23:48:54.679) - MainThread (6080):
Couldn't get NVDAObject from offset 0
ERROR - scriptHandler.executeScript (23:48:54.679) - MainThread (6080):
error executing script: <bound method GlobalCommands.script_toggleVirtualBufferPassThrough of <globalCommands.GlobalCommands object at 0x07085EF0>> with gesture 'NVDA+Leerzeichen'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "globalCommands.pyc", line 1351, in script_toggleVirtualBufferPassThrough
  File "treeInterceptorHandler.pyc", line 132, in _set_passThrough
  File "review.pyc", line 124, in setCurrentMode
  File "review.pyc", line 26, in getObjectPosition
AttributeError: 'NoneType' object has no attribute 'makeTextInfo'
```

```
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (23:49:00.827) - MainThread (6080):
No developer info for navigator object
```

cc: @leonardder do you have any suggestions on this?
I get the error with Chrome 81 as follows:
1. Open the website
2. Open the modal
3. Focusing the modal in browse mode, press up or down arrow key
3. Press nvda+space

This might be related to the underlying issue here.

**Comment by Adriani90** [comment]
Now it got worse. With NVDA 2023.1 RC1, the dialog contents are not recognized at all in Firefox. In Chrome the buttons "close" and "close ok" are focusable only in focus mode.
Not sure if this is related to bad implementation. cc: @jcsteh  for Firefox.

**Comment by Adriani90** [comment]
This is indeed web authoring issue, it seems also bad documentation by Bootstrap.
https://github.com/twbs/bootstrap/issues/29769
Closing as invalid.
