### ISSUE TITLE
System caret not placed into TABLE that has a valid aria-describedby

### ISSUE THREAD

**Issue by poorgeek** [nvaccess/nvda#9163]
### Steps to reproduce:
Create a simple data table that includes an aria-describedby attribute that references some text outside of the table.

[Contrived example (via CodePen)](https://codepen.io/poorgeek/full/BvEYNN)

### Actual behavior:

When navigating to the table via the 'T' hotkey, NVDA announces the heading, table summary and the description. Using the table navigation keys results in "Not in a table cell" UNTIL you arrow down and are placed into row 1 column 1. Then the table navigation keys work as expected.

Actual output from NVDA:

> Favorite colors table  with 4 rows and 2 columns 
> Favorite colors of your friends.
> Not in a table cell

### Expected behavior:

When navigating to the table via the 'T' hotkey, NVDA announces the heading, table summary, description, *and the cursor position*. Using the table navigation keys moves the user around the table in the intended direction.

Expected output from NVDA:

> Favorite colors table  with 4 rows and 2 columns 
> Favorite colors of your friends.
> row 1  column 1
> Name

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2018.4.1

#### Windows version:

Windows 10 Build 1803

#### Name and version of other software in use when reproducing the issue:
Tested in Firefox (64.0.2) and Chrome (71.0.3578.98)

#### Other information about your system:

Works as expected in JAWS 2018 with Firefox and VO+Safari (Mojave)

#### Have you tried any other versions of NVDA?

No

**Comment by Adriani90** [comment]
This is still reproducible in Firefox 76 and Chrome 81.
cc: @jcsteh, @aleventhal

**Comment by jcsteh** [comment]
Pressing "t" moves you to the start of a table, like all other quick navigation keys move to the start of something. When a table has a description, it gets rendered as text at the start of the table so you can read through the description with the cursor keys, etc. So, the cursor really *isn't* in a table cell at that point. The only way to fix this would be to not render the description as navigable text, but this might deny the user the ability to inspect important information provided by the table.

Personally, I'd suggest this is won't fix.

**Comment by Adriani90** [comment]
I am closing this as won't fix as per comment above. If someone has other arguments we can consider reopening this at a later point.
