### ISSUE TITLE
Browse mode fails to read listbox label and skips over child options

### ISSUE THREAD

**Issue by ydogandjiev** [nvaccess/nvda#9173]
### Steps to reproduce:
1. Open the following codepen in Chrome - https://codepen.io/ydogandjiev/pen/KbjOMG or add the following HTML to a blank page:
```
<input placeholder="Put focus here"></input>
<br/>
<br/>
<label>Options:</label>
<ul role="listbox" aria-activedescendant="option1" aria-label="Options">
  <li id="option1" role="option" aria-label="Option 1" aria-selected="true">Option 1</li>
  <li id="option2" role="option" aria-label="Option 2">Option 2</li>
  <li id="option3" role="option" aria-label="Option 3">Option 3</li>
</ul>
```
2. Put focus into the textbox
3. Switch to browse mode (Insert + Space)
4. Hit down arrow a few times until you get to the listbox

### Actual behavior:
NVDA just reads "List clickable". Continuing to arrow down skips right past the options.

### Expected behavior:
NVDA should at least read the aria-label attribute of the listbox. It should also indicate that this is a listbox with multiple options. Continuing to arrow down should read each option.

### Note:
Changing the ul role from "listbox" to "list" mostly addresses the issue but that's not compliant with the ARIA spec which indicates that a "list" must have "listitem" children and a "listbox" must have "option" children.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2018.1.1

#### Windows version:
Windows 10 build 17134.523

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by DrSooom** [comment]
@ydogandjiev: Could you please figure out if this issue still exists with NVDA 2018.4.1 and Chrome 71.0.3578.127? Thanks.

**Comment by ydogandjiev** [comment]
@DrSooom, after upgrading to NVDA 2018.4.1 I see a slight improvement. The aria-label of the listbox is now read in browse mode. In my minimal repro above I hear "Options list clickable" as opposed to just "List clickable".

However, _none of the items in the listbox are read_ and there is no way to get to them in browse mode.

**Comment by Adriani90** [comment]
I can access the options in the list with object navigation but I don't get any feedback when I try to route the mouse to any of the options. It seems like I cannot select another item in the list. I can only read them in object navigation.

**Comment by jcsteh** [comment]
This test case is invalid. List box items are intentionally not rendered in browse mode. Instead, the user presses enter to switch to focus mode and then interacts with the list box. The ARIA spec says that a listbox must manage focus for a listbox, which means the listbox must accept DOM focus, implement its own keyboard navigation and focus the active item appropriately (either via DOM focus or aria-activedescendant). This test case does none of these things and thus this will not work.
