### ISSUE TITLE
MS Word with UIA: inaccurate color reporting

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9182]
The UIA implementation of MS Word does not report default colors:

### Steps to reproduce:
1. Open a new Word document
2. Type a line of text
3. Press enter, and type another line of text
4. Select the second line
5. Press ctrl+d
6. Tab to colors, and choose a different color using the color picker.
7. Press ok
8. IN NVDA's document formatting settings, enable color reporting
9. Arrow up and down

### Actual behavior:
NVDA only reports the color when at the second line. When the first line is spoken, no color reporting occurs. This gives the user the idea that the first line is written in the color of the second line, which is not the case.

### Expected behavior:
When moving from the second to the first line, NVDA should announce default color, like in the object model implementation. Preferably, NVDA should announce the human understandable value of default color, i.e. blue when it is blue, etc.

#### NVDA installed/portable/running from source:
Installed and running from source

#### NVDA version:
alpha-16587

#### Windows version:
Windows 10 1809

#### Name and version of other software in use when reproducing the issue:
Word 2016 (non 365), build 16.0.11126.20266

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes, this does not occur with older builds of NVDA where the object model implementation was the default.

cc @michaeldcurran

**Comment by CyrilleB79** [comment]
@leonardder this issue seems to be gone. Testing with NVDA 2022.4 and Word 2016 (version '16.0.5369.1000').
Now, the color is reported.

Could you confirm this?

**Comment by leonardder** [comment]
I can no longer reproduce this indeed. Closing.
