### ISSUE TITLE
NVDA does not report (new style) comments in Excel 365

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#9195]
### Steps to reproduce:

1. Open Excel to a blank workbook.
2. On any cell, open the context menu.
3. Select "New comment".
4. Type a comment, tab to "Post" button and press ENTER.
5. The comment is still visible, press ESCAPE to close.
6. Arrow away and back to the cell with the comment.

### Actual behavior:

NVDA does not report the comment.

### Expected behavior:

NVDA should report "Has comment".

When a "Note" is entered with shift+F2 (which used to be called comments, see #9193), NVDA reports "Has comment", but not when (what is now) a comment is present.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2018.4.1
#### Windows version:
Windows 10 Version: 
18272.1000 

#### Name and version of other software in use when reproducing the issue:
Office 365 Version: 
16.0.11126.20200 

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No

**Comment by andrew-l-d** [comment]
This is not good.  A strategy I suggest for improving access to complex spreadsheets is to use comments in relevant cells.  I had a JAWS user check a test file and he reported the same issue.  Narrator does recognise both comments and notes.  It has a similar issue to NVDA when entering a note - some digital gymnastics to get it to read the spreadsheet again.

**Comment by Adriani90** [comment]
Still reproducible in NVDA 2020.1 and Excel 365.

**Comment by andrew-l-d** [comment]
This issue is nearly four years old.  Both JAWS and Narrator can identify comments and notes, albeit I cannot find a way to read comments.  with Narrator without editing the comment.

**Comment by Qchristensen** [comment]
If you turn on "Use UI Automation to access Microsoft Excel controls" in NVDA's advanced options, it reports "Has comment" when you move the focus to a cell with a comment.

You can view the comment (or reply to it) with alt+r (for the review ribbon), v (for view comment).

**Comment by andrew-l-d** [comment]
Thanks Q.  That is embarrassing.  I tried turning on UI for Excel and nothing was read.  Now it works!  Perhaps this item can now be closed.
Butterfingers

**Comment by Qchristensen** [comment]
They're still improving the experience with UIA which is why we haven't made it the default in Excel yet - but that does seem to be something which does now work, so that's a good start.  I suspect the issue with reading new comments without UIA is that it just isn't exposed except with UIA, in which case there likely won't be anything we can do for older versions of Excel (which still have the new style comments).  When I was testing, I could still read the comment with alt+r then v even with UIA disabled - although without UIA, you won't be informed there IS a comment to read.

But as using UIA will work moving forward (and particularly so once we're able to make it the default for Excel), there likely isn't much more we can do so I'll close this issue.
