### ISSUE TITLE
NVDA doe not read the region on TAB when there is a select as first element

### ISSUE THREAD

**Issue by dsoldera** [nvaccess/nvda#9196]
### Steps to reproduce:
1. Go to Code Pen and create a HTML: a div with a role and aria-label, a select with one option and a input text
2. Go to the NVDA and start on the div using TAB. Check that the NVDA reads the select content bug skiping the role using TAB 
3. Using the keys of the keyboad the region context text is been hidden.
4. Example of code: https://codepen.io/dsoldera/pen/rPVgZb
### Actual behavior: 
Doesnt read the region configured on div

### Expected behavior: 
Should read the aria-label content for region

#### NVDA installed/portable/running from source: 
installed

**Comment by DrSooom** [comment]
@dsoldera: We need a few more information from you:
1. NVDA 4.0 doesn't exist. Which one are you using?
2. And with which other versions of NVDA you tested as well?
3. And please also list all the browsers (including version) where this issue occurs.

Thanks.

**Comment by Adriani90** [comment]
Testing with NVDA 2024.2 Beta on Firefox 126 and Chrome Canary 127 as well as Edge 126, NVDA reports the label of the region "ola" properly when using tab key when entering and leaving the region. For this to work in focus mode you have to enable reporting of bookmarks and regions in NVDA document formating settings if you disabled it before. The enabled state is the default behavior.
I am closing as works for me.
