### ISSUE TITLE
Do not interrupt speech when scrolling braille

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9198]
Suggested by a @bababgecom customer.

### Is your feature request related to a problem? Please describe.
Some people would like to scroll braille while speech is talking. This can be especially handy with shorter displays and when speech is reading a line that doesn't fit on one braille display. In the current situation, speech stops as soon as you scroll.

### Describe the solution you'd like
Add a "Speech interrupt for braille movement"" option to the braille settings, which works similar to how the "Speech interrupt for typed characters" function works.

**Comment by DrSooom** [comment]
Duplicate of issue #2124 and #3167.

**Comment by leonardder** [comment]
Ah, thanks for catching that!

**Comment by Andre9642** [comment]
For information, BrailleExtender add-on provides this feature since a while.

**Comment by leonardder** [comment]
This is good to know. In my opinion, there are several braille extender features that fit within NVDA core

**Comment by josephsl** [comment]
Hi, agreed. Andre, please let me know how I can assist in integrating some of your work into NVDA based on my own work on integrating parts of Windows 10 App Essentials into NVDA Core recently. Thanks.

**Comment by Andre9642** [comment]
Thanks Joseph! No problem for me to try integrate some features from BrailleExtender to NVDA Core. ☺
I'm just not sure to be as effective as you or Leonard.

**Comment by josephsl** [comment]
Hi, at some point in the future, I’ll write up some instructions and thoughts on this process on the development mailing list. Thanks.

**Comment by Andre9642** [comment]
@leonardder Oopss. Oops. Please ignore my commit. I haven't seen that you have assigned yourself this issue. My work is not finished anyway.

**Comment by leonardder** [comment]
My current work is in https://github.com/BabbageCom/nvda/tree/speechInterruptBraille
However, I'm not yet sure about the integration strategy. I like your idea to have an additional attribute on scripts and am also considering something similar.
