### ISSUE TITLE
Excel Regression: Pressing F2, Can no longer read cells

### ISSUE THREAD

**Issue by jhomme** [nvaccess/nvda#9199]
Please thoroughly read NVDA's wiki article on how to fill in this template, including how to provide the required files.
Issues may be closed if the required information is not present.
https://github.com/nvaccess/nvda/wiki/Github-issue-template-explanation-and-examples
-->

### Steps to reproduce:

1. Open Excel 2016.
2. Press F2 in any cell.
3. NVDA says "unknown."
4. Type some data, then use arrow keys to try to read. Also press reading keys, such as NVDA+L.

### Actual behavior:

NVDA does not speak.<!--

### Expected behavior:

NVDA should speak.

#### NVDA installed/portable/running from source:

NVDA Install
#### NVDA version:

2018.4.1

#### Windows version:

Windows 10 Version 1803 (OS Build 17134.523)'

#### Name and version of other software in use when reproducing the issue:

Just Excel 2016.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA?
Yes, 2018.4

**Comment by Adriani90** [comment]
I am closing this as a duplicate as per comment above. I agree that this is quite important, especially when working together with sighted coleagues.
cc: @michaelDCurranB

**Comment by jhomme** [comment]
My apologies. I searched forExcel issues before making this one.

Jim

On 1/24/19, Adriani90 <notifications@github.com> wrote:
> I am closing this as a duplicate as per comment above. I agree that this is
> quite important, especially when working together with sighted coleagues.
> cc: @michaelDCurranB
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/9199#issuecomment-457356748


-- 
==========

Jim Homme
http://www.jimhommewebdev.com
Twitter: @jimhomme
Facebook: http://www.facebook.com/jimhomme
LinkedIn: https://www.linkedin.com/in/jimhomme
Skype: jim.homme
FreeChess: jhomme
