### ISSUE TITLE
Checked menu item is not announced in IE

### ISSUE THREAD

**Issue by pumpumpurum** [nvaccess/nvda#9201]
### Steps to reproduce:
1. Go to https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-2/menubar-2.html
2. Tab through the page to any menu
3. Open the menu
4. Navigate with arrows to the checked menu item

### Actual behavior:
The menu item is not announced

### Expected behavior:
Checked menu item should be announced same as not checked with the "selected/checked" word added

#### NVDA installed/portable/running from source:
Installed from the official site
#### NVDA version:
2018.4.1
#### Windows version:
Windows 10 Enterprise 1809
#### Name and version of other software in use when reproducing the issue:
Internet Explorer 11.253.17763.0

**Comment by Adriani90** [comment]
Support for IE ended completely in 2022, and the browser is automatically removed from machines that still have it after an Edge update in February 2023. I don't expect any further updates regarding accessibility. If you still have this issue in other browsers, please open a new updated issue with coresponding steps to reproduce and a minimal test case.
I am closing this as abandoned.
