### ISSUE TITLE
Make NVDAObject.children a generator instead of a list

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9203]
### Is your feature request related to a problem? Please describe.
Sometimes, we need to walk through the children to get the active child within a container object, a list for example. This happens in QT containers. Fetching the first child and than calling next on that child can sometimes result into an endless loop when IAccessible accNavigate is not implemented properly. However, calls of NVDAObject._get_children can be pretty expensive, since it creates a list of all the children and returns it afterwards. This is pretty slow with an enormous amount of children, and causes an entire freeze of NVDA when you fetch the children of a libre office spreat sheet, for example.

### Describe the solution you'd like
I propose changing the children property into a generator as part of the switch to Python 3.

**Comment by leonardder** [comment]
It turns out that there isn't that much in core that has to be changed for this.

Cc @josephsl: curious what you think about this proposal.

**Comment by josephsl** [comment]
CC @JcSTeh, @MichaelDCurran, as they are the actual experts on this.

**Comment by leonardder** [comment]
Ah, you're right. It turns out that, especially in the case of IAccessible, IAccessibleHandler.accessibleChildren is the real culprit here. I initially thought that the massive performance hit was caused by NVDA creating NVDAObjects for every underlying IAccessible or UIA object.

Closing this.
