### ISSUE TITLE
Windows 10 1903/emoji panel: no opening announcement

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9204]
Hi,

Partially blocks #9112: In Windows 10 Version 1903, when emoji panel opens, typical opening announcement is not made.

### Steps to reproduce:
1. Install Windows 10 Insider Preview build 18305 and later.
2. Try opening emoji panel (Windows+period) or cloud clipboard (Windows+V).

### Actual behavior:
NVDA becomes verbose when opening emoji panel instead of announcing the first selected emoji, and when cloud clipboard opens, no response from NVDA.

### Expected behavior:
NVDA announces first selected emoji and announces clipboard status when cloud clipboard is opened.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Alpha.16619

#### Windows version:
Windows 10 Version 1903 Preview (build 18323)

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
Part of Windows Insider Program

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes - 2018.4.1

### Technical information:
Until Version 1809, UIA window open event was fired by modern keyboard executable, but since 18305, File Explorer (explorer.exe) is responsible for firing window open event (a new UIA window with the class name of "ApplicationFrameWindow" is now the host of modern keyboard, and that window fires window open event).

Note that in case of emoji panel, it might actually be desirable to let NVDA become a bit verbose, since Version 1903 emoji panel will let users browse emojis, kaomoji, and symbols. Let us revisit this small change when it is shown that emoji panel will open to whatever grand category (emoji, kaomoji, symbols) one was browsing to last (currently it always defaults to emoji category).

Thanks.

**Comment by josephsl** [comment]
Blocked by #10359

**Comment by Adriani90** [comment]
@josephsl the coresponding pull request for the issue which you referenced above has been merged and the issue has been closed.

**Comment by josephsl** [comment]
Hi, that I’ll take care of. Thanks.
