### ISSUE TITLE
Python 3.8: use gettext.pgettext function for translatable strings with contexts

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9207]
Hi,

Blocked by #7105 and Python 3.8:

### Is your feature request related to a problem? Please describe.
In 2012, as part of adding message contexts for various translatable messages (see #1524 for details), NVDA added pgettext function to built-in namespace. Fast forward to 2019, and one of the additions in python 3.8 (later in 2019) will be gettext.pgettext family of functions (see python/cpython:7253) which will allow NVDA to add context messages for translatable strings without modifying built-in namespace.

### Describe the solution you'd like
once #7105 is complete and when it comes time to upgrade to Python 3.8 or later, consider using gettext.pgettext.

### Describe alternatives you've considered
None

### Additional context
See #7105 for details on Python 3 transition workflow, as well as CPython pull request noted above for further details.

Thanks.

**Comment by josephsl** [comment]
Hi,

Blocked until at least wxPython is built with Python 3.8 support.

Note that there is a proposal that seeks to speed up Python releases. If this happens, Python 3.9 will hit the air in June 2020, meaning we might skip Python 3.8 and go directly to 3.9. Again this introduces another block until C extensions (wxPython, for instance) are ready.

Thanks.

**Comment by josephsl** [comment]
Hi,

2020: blocked until NVDA is built with Python 3.8, and only then this issue will be revisited.

Thanks.

**Comment by josephsl** [comment]
Hi,

2021 update: foundations being laid. The overall strategy wil be replacing pgettext call with gettext.pgettext and testing it.

Thanks.

**Comment by feerrenrut** [comment]
Should this have been closed with #12109?

**Comment by josephsl** [comment]
Hi, yes. Thanks.

**Comment by Adriani90** [comment]
Closing as fixed in the PR referenced above.
