### ISSUE TITLE
list of incompatible add-ons reads status only

### ISSUE THREAD

**Issue by bdorer** [nvaccess/nvda#9212]
### Steps to reproduce:
open add-ons manager, activate Manage incompatible add-ons... and arrow through imcompatible addons.

### Actual behavior:
While arrowing NVDA says checkbox checked or not checked.

### Expected behavior:
NVDA should read the list entries corresponding to the checkbox in front of them.

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
NVDA next 16639 and prior snapshots
#### Windows version:
Windows 10.0.17763 
#### Name and version of other software in use when reproducing the issue:
NA
#### Other information about your system:
NA
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no, as the dialog isn't available in 2018.4

**Comment by bdorer** [comment]
Woops! You god it. Didn't think that this option has anything to do there.

**Comment by josephsl** [comment]
Closing as worksforme.
