### ISSUE TITLE
Cached keyboard focus kicks in after page reload/form submit

### ISSUE THREAD

**Issue by sephyzeonas** [nvaccess/nvda#9225]
I have experienced a caching behavior whenever I reload a page or submit a form.
I already found a closed issue ( https://github.com/nvaccess/nvda/issues/5351 ) which describes my current issue properly but does not satisfy my need.
The focus issue is found on absolutely every web page which is not helpful if you want to force the  focus to another position e.g. after a form submit via JavaScript. But this behaviour is very inconsistent. This means I can reproduce the "Steps to reproduce" in about 80%. Another problem is that the focus after submitting a form jumps sometimes absolutely random to any link on a page which does not feel like any caching behavior. If NVDA is off every focus behavior works as expected.

The real question is: how is it possible to deal with such NVDA forced focus jumps in order to use custom force jumps instead?

The suggestion with random url additions in https://github.com/nvaccess/nvda/issues/5351 is a pretty bad workaround.

### Steps to reproduce:
1. NVDA on
2. Go to a page A with links
3. Click on link Y
4. Go to page A again
5. Click on Link Z
6. Go to page A again
-> Focus is on Link Y

1. NVDA on
2. Go to a page A with search form
3. Fill in and click on submit -> JavaScript forced focus kicks in (works fine)
4. Go to page A again
5. Fill in and click on submit -> JavaScript forced focus kicks in (does not work -> will be overridden by cached NVDA focus)

### Actual behavior:
Like described on "Steps to reproduce" but only on the following Browsers
Chrome (v.70.0.3538.77 64-bit)
FireFox (v.63.0 64-bit)
IE 11

### Expected behavior:
Possibility to not be force focussed by NVDA -> Javascript focus has higher priority

#### NVDA installed/portable/running from source:
NVDA installed

#### NVDA version:
2018.3.2

#### Windows version:
Windows 10 + Windows 10 virtualized

#### Does the issue still occur after restarting your PC?
Yes.
#### Have you tried any other versions of NVDA?
Yes.

**Comment by Adriani90** [comment]
@sephyzeonas can you still reproduce this in NVDA 2019.3 RC1? You can download it here:
https://www.nvaccess.org/files/nvda/snapshots/

I think what happens is that NVDA switches to browse mode when you submit and the focus is moving according to the virtual cursor of NVDA. Could you try to reproduce this after doing following in NVDA?
1. Open NVDA menu / options / settings / browse mode settings
2. uncheck the option called "enable browse mode at page load"

**Comment by Adriani90** [comment]
We do not have updates from the initial author since more than one year.
@jcsteh do you have any experience with this in Firefox? In my view the focus tracking got much better since this issue has been reported.

**Comment by Adriani90** [comment]
I am closing this issue as abandoned due to missing updates from the initial author since many years. If you are still having this issue please comment and we can reopen.
