### ISSUE TITLE
No restart confirmation prompt when installing add-on from shell

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9226]
Regression from #9151 

### Steps to reproduce:
1. Open an add-on from Windows Explorer
2. Install it

### Actual behavior:
No restart confirmation prompt is shown

### Expected behavior:
A restart confirmation prompt is shown

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-16682

cc @feerrenrut

**Comment by josephsl** [comment]
Hi,

OT, but while we're at it, can we also fix a typo (apdated)? Thanks.
