### ISSUE TITLE
Firefox and google tables: NVDAreports blank at every cell when using arrow keys to navigate, alt tabing or restarting NVDA solves the problem

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#9232]
### Steps to reproduce:
1. Open a google drive folder containing a google sheets file
2. Open the file
3. Navigate with arrow keys

### Actual behavior:
NVDA reports "blank" on every cell before reporting its coordinates and its content. Alt tabbing or restarting NVDA solves the problem. After that, NVDA does not report blank anymore.

### Expected behavior:
NVDA should not report blank on every cell when opening a sheet directly in gogle drive and using arrow keys to navigate.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA Alpha 16691,10950C87

#### Windows version:
Windows 10 1809 update

#### Name and version of other software in use when reproducing the issue:
Firefox 65

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA?
NVDA 2018.4.1, NVDA 2018.3.2

**Comment by Adriani90** [comment]
cc: @jcsteh, @michaelDCurran

**Comment by DrSooom** [comment]
@Adriani90: Is this still reproducible with Firefox 77.0.1 and NVDA 2020.1?

**Comment by Adriani90** [comment]
Now NVDA just remains silent when pressing enter on a google tables document and then pressing arrow keys to navigate. You have to press alt+tab twice to be able to work in the table. It seems there is yet another focus tracking issue here. In my case both screen reader support and braille support are enabled.

Only screen reader support is not an option, NVDA just announces blank on every cell even if the cell has content. The content is announced after announcing "blank" in this case.
cc: @jcsteh, @MarcoZehe any idea why NVDA fails to gain focus on the table cells right after opening the google tables document?

**Comment by jcsteh** [comment]
I can't reproduce this. Have you tried with add-ons disabled? It'd be great if you could provide a log file with log level set to debug. Thanks.

**Comment by Adriani90** [comment]
@jcsteh so that means in your case NVDA directly reports the cell you are navigating to when pressing arrow keys right after opening a new google table document?

in my case, here is the relevant part of the log with all add-ons disabled:
```
IO - speech.manager.SpeechManager._pushNextSpeech (21:36:57.532) - MainThread (13296):
Sending to synth: ['Screenreader Unterstützung aktiviert.  ', IndexCommand(374)]
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (21:36:57.554) - MainThread (13296):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
IO - inputCore.logTimeSinceInput (21:36:57.554) - MainThread (13296):
5.951 sec since input
IO - speech.speak (21:36:57.554) - MainThread (13296):
Speaking ['In Arbeit…\n ']
IO - inputCore.logTimeSinceInput (21:36:57.554) - MainThread (13296):
5.951 sec since input
IO - speech.speak (21:36:57.554) - MainThread (13296):
Speaking ['Finanzbericht - Google Tabellen']
IO - inputCore.InputManager.executeGesture (21:36:58.139) - winInputHook (7496):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (21:36:58.734) - winInputHook (7496):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (21:36:59.625) - winInputHook (7496):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (21:37:00.259) - winInputHook (7496):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (21:37:00.543) - winInputHook (7496):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (21:37:00.813) - winInputHook (7496):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (21:37:01.445) - winInputHook (7496):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (21:37:01.714) - winInputHook (7496):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (21:37:02.021) - winInputHook (7496):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (21:37:02.620) - winInputHook (7496):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (21:37:02.903) - winInputHook (7496):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (21:37:03.173) - winInputHook (7496):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (21:37:03.774) - winInputHook (7496):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (21:37:04.026) - winInputHook (7496):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (21:37:04.158) - winInputHook (7496):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (21:37:04.443) - winInputHook (7496):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (21:37:04.782) - winInputHook (7496):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (21:37:04.945) - winInputHook (7496):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (21:37:05.277) - winInputHook (7496):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (21:37:05.562) - winInputHook (7496):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (21:37:05.831) - winInputHook (7496):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (21:37:06.001) - winInputHook (7496):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (21:37:06.280) - winInputHook (7496):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (21:37:06.386) - winInputHook (7496):
Input: kb(laptop):downArrow
```

**Comment by Adriani90** [comment]
I cannot reproduce this anymore with NvDA alpha-27795,9ea9af61 (2023.2.0.27795)
 and Firefox 110. Closing as works for me.
