### ISSUE TITLE
Navigating by tab always starts from the top on some pages, regardless of current position

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#9234]
### Steps to reproduce:

1. Go to [this page on React's documentation](https://reactjs.org/docs/hooks-overview.html)
2. Press h a few times to move through the page. Then press tab to move to the next link.

### Actual behavior:

Tab should move you to the next link from your current position.

### Expected behavior:

The tab key always starts from the top of the page, moving you to the first link on the page.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

alpha-16619,dac59805

#### Windows version:

1803

#### Name and version of other software in use when reproducing the issue:

IE11, Firefox 66.0 b4 and latest Chrome

#### Other information about your system:

This happens on other pages on this website. I've seen this on other pages as well outside of React's documentation, not sure if this is an authoring issue. Even so, it would be good if we could find a workaround for this.

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA?

No

**Comment by Adriani90** [comment]
Hmm this is strange. If you disable automatically move focus to focusable elements with nvda+8 then this works correctly. I would have expected this behavior the other way round.
cc: @jcsteh, @leonardder

**Comment by jcsteh** [comment]
I can't reproduce this in Firefox Nightly, regardless of auto set focus to focusable. For example, if I press h four times to move to "But what is a hook?", pressing tab takes me to "don't recommend", which is a link under that heading.

**Comment by mohdshara** [comment]
@jcsteh have you tried reproducing this on nvaccess .org as described here:
on nvaccess.org with Firefox, the tab key jumps back to the start of the page #11004

**Comment by jcsteh** [comment]
> @jcsteh have you tried reproducing this on nvaccess .org as described here:
> on nvaccess.org with Firefox, the tab key jumps back to the start of the page #11004

That's a different underlying issue, as I described in https://github.com/nvaccess/nvda/issues/7897#issuecomment-609514058. This problem doesn't apply to the URL provided in https://github.com/nvaccess/nvda/issues/9234#issue-406104783, though.

**Comment by Neurrone** [comment]
I can still reproduce this if I press h once, then press tab. But that might be the issue mentioned in #7897.

**Comment by jcsteh** [comment]
For the first heading on the React page, yes, same issue as #7897. I couldn't reproduce it on subsequent headings, though.

**Comment by Neurrone** [comment]
Will close this in favour of #7897.
