### ISSUE TITLE
Firefox: can't read text right after inline element using the mouse

### ISSUE THREAD

**Issue by DataTriny** [nvaccess/nvda#9235]
### Steps to reproduce:

1. Open the provided webpage in Firefox,
2. Hover the mouse over the different lines.

### Actual behavior:

If a paragraph contains an inline element (such as a link, an image, a button, etc...) that is not placed at the start, NVDA will not be able to report the text directly following the element. But, if the paragraph is long enough, then you will be able to read the desired text (providing that you place the cursor away from the element). As you can see from my test case, this offset seems to depend on the amount of text placed before the element.

### Expected behavior:

NVDA should be able to read the text that is adjacent to an inline element, without any margin (like in Microsoft Edge or Google Chrome for instance).

#### NVDA installed/portable/running from source:

NVDA is installed.

#### NVDA version:

NVDA 2018.4.1

#### Windows version:

Windows 10 Education, version 1809

#### Name and version of other software in use when reproducing the issue:

Mozilla Firefox 65.0 (x64)
[bug.zip](https://github.com/nvaccess/nvda/files/2825827/bug.zip)

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA?

As far back as I can remember, this problem has been there for a very long time.

**Comment by feerrenrut** [comment]
What text unit resolution are you using? I set mine to paragraph.

I tested this in chrome and firefox, both seem flaky, and chrome is worse. Interestingly, in Firefox, the point where each line was read (after the link) seemed to match the number of characters before the link. It would be interesting to investigate this a little more to see if this is reproducible, and meaningful.

**Comment by feerrenrut** [comment]
Also worth testing: The behaviour with windows at different scaling levels.

**Comment by DataTriny** [comment]
Hello @feerrenrut,
I also use paragraph as the text unit resolution, but I tried with line, on both 100% and 125% DPI factors and got the same results.

**Comment by Adriani90** [comment]
@DataTriny how is the behavior in NVDA 2020 Beta 1 and Firefox 75?

**Comment by DataTriny** [comment]
Hi @Adriani90, using the webpage I provided in the issue description, the behavior is still the same with NVDA 2020.1 beta1.

**Comment by jcsteh** [comment]
This bug goes all the way back to April 2009, ebb7dbb26b8ffb5d3e041dc40204c7b57a528981. It's also being discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1822340#c16.

I'll submit a pull request shortly.
