### ISSUE TITLE
NVDA reports -0.0353 cm from top edge of page when pressing nvda+del in MS Word 365

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#9240]
### Steps to reproduce:
1. Open NVDA and open a ms word document
2. Place the carret everywhere in the document
3. Press nvda+delete to get the cursor position from left and top edge of page.

### Actual behavior:
NVDA reports the correct position from left edge of page but it always reports "-0.0353 cm from top edge of page".

### Expected behavior:
NVDA should report the correct position from top edge.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Alpha 16691,10950C87

#### Windows version:
Windows 10 1809 update

#### Name and version of other software in use when reproducing the issue:
Word 365

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA?
no

**Comment by Adriani90** [comment]
In MS Word 2010 it works as expected.

**Comment by Qchristensen** [comment]
It is also working correctly for me in Office 365 (latest stable update) using NVDA 2018.4.1 (installed), Alpha 16691 (as in original issue) and Alpha 16709 (latest alpha currently).  I have Office set to report in centimetres if that matters.  I'm using an older insiders build of Windows 10 (1809 build 18272).

Your margin's aren't set strangely or you don't have anything in your document which might be overlapping the edge of the page?

**Comment by Adriani90** [comment]
I tested in a blank documemt and typed some lines of text. Where can you set the reporting in cm?

**Comment by Qchristensen** [comment]
It's in the advanced settings:
1. (With Word open), press ALT+F, then T to open settings.
2.  CONTROL+TAB until the Advanced tab has focus (six times for me in Office 365)
3. Press ALT+M a couple of times to get to "Show measurements in units of" which is a drop-down where you can select Inches, Centimeters, Millimeters, Points or Picas.

Going back to the original issue, I would have assumed if Word is reporting the focus is at -0.0353 cm that changing the unit of measurement should mean it then reports -0.0138 inches etc, but I guess the problem could either be in how the number is calculated in the first place, or how it is converted into the unit to report.

**Comment by Adriani90** [comment]
Hmm strange. In my setting cm are already selected. Anyway, in the last alpha it seems cursor distance from page edge is not working anymore. @qchristensen can you confirm? I am using Alpha 16743,9509C256

**Comment by Adriani90** [comment]
Sorry I had to edit the last comment because I made a mistake.

**Comment by ultrasound1372** [comment]
It does indeed report -0.0139 inches from top edge of page for me. It happens with word from office 365 which I got through my university, using NVDA 2020.3 both with and without using UIA. Furthermore, if I do use UIA there will be no indication of when I've passed a page boundary, NVDA will not announce page 2 when I arrow onto page 2. For my university needs I've been stuck to proofing in page increments for my writing, and temporarily disabling UIA to get the document's length. cc @Qchristensen

**Comment by Adriani90** [comment]
@ultrasound1372 can you still reproduce the issue? I cannot reproduce it anymore with NVDA 2022.4.

**Comment by ultrasound1372** [comment]
It does still happen to me, although the bug with not reporting page numbers does appear to have been fixed. And position from the left edge works. Just the top edge does not.

**Comment by Adriani90** [comment]
@ultrasound1372 can you test with last NVDA alpha and the last update of MS Word? Is this still reproducible on your side?
You can download the last NVDA alpha for testing purposes at this link:
https://www.nvaccess.org/files/nvda/snapshots/
