### ISSUE TITLE
rowgroup role causes NVDA to incorrectly announce the size of a grid

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#925]
**Reported by kloots on 2010-09-21 18:47**
I have noticed that when using the rowgroup ARIA role to markup a grid control, the rowgroup role interferes with NVDA's ability to correctly announce the size of the grid when in standard browse mode (virtual buffer is on).  When using rolegroup, NVDA will announce the grid as having "zero rows and zero columns".

For reference, here is the URL to a simple example that can be used to reproduce the issue:
http://public.yahoo.com/kloots/aria-grid-with-rowgroup.html

Additionally, I was testing with Firefox 3.6.8.

**Comment by leonardder** [comment]
Issue looks abandoned and the W3c issue is closed. Closing this, but happy to reopen if this issue is still there.
