### ISSUE TITLE
When UIA is used for contecst menus in Word 2010 some items are reported twice.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#9252]
### Steps to reproduce:
1. Open Word 2010 using latest NVDA Alpha.
2. Open context menu,, and start navigating with the arrow keys.
### Actual behavior:
Some items are reported properly but some in a wrong way for example:
- Copy, cut and some other items are announced twice that is 'cut unavailable cut ctrl+x'
- the synonyms and styles are announced as 'synonyms collapsed menu item synonyms'
### Expected behavior:
They should be announced only once.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-16709,e51645d0

#### Windows version:
Windows 7 x64
#### Name and version of other software in use when reproducing the issue:
Word 2010 32-bit
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
Yes 2018.3 works ok.
i believe it is caused by the fact that NVDA now uses UIA for these menus cc @michaelDCurran

**Comment by Adriani90** [comment]
Is uia not only for word 2016?

**Comment by lukaszgo1** [comment]
UIA is used only for Word 2016 when we are talking about accessing the documents content, but context menu can be accessed with UIA in older versions of MS Word also. I am not sure if this was intentional.

**Comment by leonardder** [comment]
cc @michaelDCurran 
I've been able to reproduce this with Office 2016 when right clicking on misspelled words.

**Comment by lukaszgo1** [comment]
As discussed in #9259 it isn't fixed. Can someone reopen?

**Comment by Adriani90** [comment]
I am not sure if this is related to UIA. But anyway I am able to reproduce this issue in Word 2010.

**Comment by lukaszgo1** [comment]
I've just discovered that when UIA is used for treeview in the options of MS Excel in which you can enable or disable sections of ribbon state of them isn't announced. Previously it was very easy to get to them with object nav - the appropriate checkbox was directly below an item, but now with UIA used for them it is no longer possible.
Any chance for a fix?
