### ISSUE TITLE
Reading by sentence is broken in MS Outlook and Word

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#9254]
In both the current and previous alpha snapshots, reading previous and next sentence with alt-up arrow and alt-down arrow respectively in both Outlook and Word 365 does not work.  This is regardless of whether Sentence Nav is installed.  With Input Help turned on, "Move to previous sentence" and "Move to next sentence" are reported.  However, pressing either combination out of help mode does nothing.
I am running the alphas as portable versions on Windows 10 April 2018 and tried with both eSpeak and Windows one core voices.

Andrew

**Comment by leonardder** [comment]
I can confirm this for Word 2016, but only when the experimental UIA support is enabled. Could you please check the state of this setting in NVDA's advanced settings and report back your result?
Also, it would be greatly appreciated if you could update your initial description according to the issue template.

**Comment by andrew-l-d** [comment]
### Steps to reproduce:
Open either a document in Word or an email in Outlook
Press alt-up arrow to read previous sentence or alt-down arrow to read next sentence
### Actual behavior:
Nothing is presented by the screen reader
### Expected behavior:
Previous or next sentence respectively should be presented
### System configuration
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
nvda_snapshot_alpha-16691,10590c87,  nvda_snapshot_alpha-16732,03977ad4.exe and nvda_snapshot_alpha-16733,1a45aebb.
#### Windows version:
Windows 10 April 2018
#### Name and version of other software in use when reproducing the issue:
MS Word and Outlook - MS Office 365
#### Other information about your system:
The NVDA Use UI Automation to access Microsoft Word document controls when available checked
Problem does not occur if Use UI Automation to access Microsoft Word document controls when available is unchecked
### Other questions
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
Yes, problem does not occur with 2018.4.1 and earlier
###Apologies
Slapped wrist severely for not following template.  As Leonard detected, the problem only occurs when UA Automation is used.  Log file does not seem to show anything relevant.

Andrew

**Comment by leonardder** [comment]
@andrew-l-d: Can you still reproduce this?

**Comment by andrew-l-d** [comment]
Yes, I can still reproduce the issue with NVDA 2019.2.1.  When "Use UI Automation to access Microsoft Word document controls when available" is checked, reading by Sentence in MS Word and Outlook 365 still does not work.
Andrew

**Comment by andrew-l-d** [comment]
Using nvda_snapshot_alpha-23809,5f9750de navigating by sentence is not possible in MS Word or Outlook due to UI automation being the only option.  I have contacted the author of SentenceNav, whose current workload does not allow him to investigate for some time.  As I have argued in #8518, could navigating by sentence please be a core component of NVDA.  It is the only screen reader I am aware of that lacks the facility natively and it is an extremely important one.
I tried using Word's ctrl+shift+pageup/down to move by sentence.  NVDA does not present the new information.

**Comment by michaelDCurran** [comment]
UI Automation currently has no means of moving by sentence, though I believe this is planned via UI Automation Custom Patterns in MS Word. I have no timeline from Microsoft yet on when this will be available for NVDA to consume.
Until then, the question is whether this limitation is enough to hold back switching to UIA by default in MS Word for recent Office builds... waying that against the significant performance advantages of UIA.

**Comment by josephsl** [comment]
Hi, I think an alternative would be documenting this limitation clearly so people can understand what they will experience until such time Office team inside Microsoft can implement necessary changes to UIA server-side implementation. Thanks.

**Comment by michaelDCurran** [comment]
We may be able to allow a fallback to the object model for this specific feature if it is available, at least until UIA can expose this. I'll look into this.

**Comment by leonardder** [comment]
I think we should make UIA in Word opt out when it is the default, e.g. have a similar combo box in settings as is used for UIA in Chromium.

**Comment by CyrilleB79** [comment]
If it is not known when MS will support sentence navigation in UIA documents, an alternative is to prioritize and implement #8518.

**Comment by andrew-l-d** [comment]
I strongly agree with Cyrille's comment, even without the UIA issue.  Reading by sentence should not be restricted to MS Office products.
