### ISSUE TITLE
Developer scratchpad setting is saved in current configuration profile instead of globally

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9260]
### Steps to reproduce:
1. Enable the developer scratchpad setting in NVDA's advanced settings
2. Load a configuration profile
3. Disable the setting from the advanced category while the profile is active.

### Actual behavior:
The scratchpad setting is saved in the configuration profile.

### Expected behavior:
The developer scratchpad should be treated as a global setting.

### Additional thoughts
1. The development section can be added to the ConfigManager.BASE_ONLY_SECTIONS set, which is simple enough.
2. However, in this case, the advanced category will contain both global and profile specific settings, which is not very ideal.

cc @michaeldcurran

**Comment by DrSooom** [comment]
Hmm, what's about the following options in the General NVDA Settings?
+ Language
+ Automatically start NVDA after I log on to Windows
+ Use NVDA on the Windows Logon screen (requires administrator privileges)
+ Automatically check for updates to NVDA
+ Allow the NVDA project to gather NVDA usage statistics
+ Notify for pending updates on startup

How many of them should be excluded from configurations profiles too? Maybe some of them are already excluded. I haven't tested this.
