### ISSUE TITLE
tabindex of -1 causes grid size to be incorrectly announced

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#927]
**Reported by kloots on 2010-09-21 18:54**
I have noticed that if rows in a grid have a parent element whose tabindex attribute is set to -1, NVDA will incorrectly announce the grid as having "zero rows and zero columns" when in standard browse mode (virtual buffer is on).  Seems like the presence of the tabIndex attribute shouldn't affect calculation of the grid size.

Here is a an example page:

http://public.yahoo.com/kloots/bugreports/aria-grid-tabindex.html

For reference, I was testing in Firefox 3.6.8.

**Comment by leonardder** [comment]
Unfortunately, the report contains a dead link. Might be good to track this down and, if still reproducible, fix it in #7410?

**Comment by jcsteh** [comment]
Still a bug which manifests in different ways in both Firefox and Chrome:

`data:text/html,before<div role="grid" aria-readonly="true"><div tabindex="-1" role="presentation"><div role="row"><div role="gridcell">cell content</div></div></div></div>`

Firefox incorrectly reports the row and column counts as reported here.

Chrome doesn't render the cell at all.

Bugs need to be filed with both browsers.

**Comment by jcsteh** [comment]
P4 because we don't seem to be getting reports of this particular usage in the wild. If we see a specific case of this, we can raise the priority for filing browser bugs.

**Comment by Adriani90** [comment]
In Firefox 66.0.3 and NVDA 2019.1.1 this issue is still reproducible. I see this issue at work very often in SAP net viewer applications.

Following error is written to the log when trying to navigate in the table cell with ctrl+alt+arrow keys:

```
ERROR - scriptHandler.executeScript (17:41:56.723):
error executing script: <bound method Gecko_ia2.script_previousColumn of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x054A40F0>> with gesture u'Alt+Strg+Pfeiltaste nach links'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "documentBase.pyc", line 189, in script_previousColumn
  File "documentBase.pyc", line 167, in _tableMovementScriptHelper
  File "virtualBuffers\gecko_ia2.pyc", line 337, in _getTableCellAt
LookupError
```

**Comment by Adriani90** [comment]
In Chrome 74 it works as expected. The text "cell content" is rendered into a cell and you can navigate by ctrl+alt+arrow keys.

**Comment by Adriani90** [comment]
I get this behavior also in many share point applications which contain grids.

**Comment by Adriani90** [comment]
Still reproducible in Firefox 71. @jcsteh is this something you could report on Bugzilla? Unfortunately this issue is quite severe in corporate environments, epsecially in sharepoint based interfaces and the table navigation does not work.

**Comment by jcsteh** [comment]
Covered by https://bugzilla.mozilla.org/show_bug.cgi?id=1455066

**Comment by jcsteh** [comment]
This should be addressed in Firefox 75 (currently in beta). The simple test case in https://github.com/nvaccess/nvda/issues/927#issuecomment-315902639 now works as expected.

@Adriani90, could you test whether the problematic SAP net viewer and SharePoint applications you mentioned are fixed now? I understand you may not be able to run beta software in a corporate environment, so we might have to wait until Firefox 75 final.

**Comment by jcsteh** [comment]
I'm closing this, since the test case is fixed, but please do comment with your findings. We should open a new issue if there are further problems.
