### ISSUE TITLE
Disabling Word screen updating not possible in Word protected view, generates error sound

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9271]
### Steps to reproduce:
1. Open a document in Microsoft Word
2. Read line by line.

### Actual behavior:
bText reads as expected, however the following error is in de log:

```
ERROR - RPC process 5564 (WINWORD.EXE) (14:21:20.346):
Thread 2944, build\x86_64\remote\winword.cpp, ScreenUpdatingDisabler::ScreenUpdatingDisabler, 74:
application.screenUpdating false failed with code -2146821989
```

### Expected behavior:
There's no error

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Latest alpha

#### Windows version:
Windows 10 version 1803

#### Name and version of other software in use when reproducing the issue:
Word 2010: 14.0.7229.5000 64 bit

#### Additional info
We were unable to reproduce this on another system with Word 2010.

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes, this does not occur with 2018.4.1

**Comment by lukaszgo1** [comment]
I can reproduce it in Word 2010 32-bit if and only if the opened document is in the protected view.

**Comment by leonardder** [comment]
Ah, very likely that the colleague who reported this to me was also in protected view.

**Comment by leonardder** [comment]
I can now reproduce this in Word 2016 protected view.

From what my colleague reported, he initially opened a document in protected view, but disabled protected view and yet the errors persisted. This is something I've asked him to retest.

**Comment by leonardder** [comment]
Given this a p2, as though it is not harmful, it is ridiculously annoying when reading in protected view with Alpha builds.

**Comment by surfer0627** [comment]
Hi,
in the protected view, browse mode, commands (press arrows to move to next / previous line) are unavailable. This case occurs in MS Word 2010 at least.

Should we need to add some description to remind users of this issue in user guide?

log message:
DEBUGWARNING - NVDAObjects.window.winword.WordDocumentTextInfo._expandToLineAtCaret (16:53:42.045):
winword_expandToLine failed


Sorry for this off topic post.
If necessary, I'll create a new issue.

**Comment by leonardder** [comment]
@surfer0627: If there isn't already an issue for this, feel free to create one.
