### ISSUE TITLE
nvda does not use the voice synthesizer configured in a profile on a new machine.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9276]
### Steps to reproduce:
At the school where I am working, we are using software to teach students how to type.
This software calls digitavox.
This software has its own voice.
So I configured a machine for the digitavox software, and I set the synthesizer non-speech .
Until now all right.
I need to do the same for different machines.
Then I copied the profile file created for the digitavox from the profiles folder of the name digitavox.ini I went to the other machine and pasted this configuration file from the digitavox.ini profile into the profiles folder.
I restarted nvda and focused on the digitavox software, and nvda continued to speak normally, that is, the non-speech  synthesizer configuration was not applied even though the profile file is in the nvda profiles folder.
In order to work I had to select within the tuner the digitavox profile, it was as general.
My question is, should all this work just by pasting the profile file? That's what I'd expect.
I will try to summarize the areas to reproduce:

place 1
Open a software and create an auto-start profile, setting the synthesizer to be non-speech 
.

place 2
copy the created profile file from the nvda profiles folder.

place 3
On another machine, paste the profile file into the nvda profiles folder.
### Actual behavior:
nvda does not apply the configuration non-speech .

### Expected behavior:
When copying the created profile on the new machine, nvda should automatically take the non-speech 
#### NVDA installed/portable/running from source:
install
#### NVDA version:
2018.4.1
#### Windows version:
10 1803
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by DrSooom** [comment]
@fernando-jose-silva: Could you please copy the complete content of the no-speech-ini file as a comment? And the whole "Speech settings" section of the nvda.ini too. Ah, and does the file "profileTriggers.ini" exist? Thanks.

**Comment by lukaszgo1** [comment]
This is a proper behavior. The deciding factor when checking which profile should be active is the content of the profileTriggers.ini file. It is logical I for instance have a profile called simply TeX which is assigned to my LaTeX editor which of course isn't called Tex. This should be closed as invalid. If I might suggest something you might consider asking such question on one of the NVDA mailing lists before opening an issue here.

**Comment by DrSooom** [comment]
I suppose that @fernando-jose-silva should try to copy the "profileTriggers.ini" file too. If then it works as expected, he should close this issue here.

btw: As other users could have the same issue, it is much easier to find this issue here via a quick search on the web instead of asking such things in different mailing lists, which partly aren't public and which are also available in different languages. So opening this issue here was okay, even if it's going to be closed as invalid (based on an overlook).

**Comment by fernando-jose-silva** [comment]
Thank you very much
@DrSooom 
Perfect worked by copying the profileTriggers.ini
I did not know of the existence of this file.
I opened this problem because initially for me would not be a doubt, and yes maybe a problem.
I do not speak English as you should have noticed, this is a translation by Google translator.
And speaking on a list in English by the translator is very difficult, and you have always had patience in responding to open calls.
The list in Portuguese Brazil, in my opinion, is almost intact, you never get a return there.
