### ISSUE TITLE
Set start and end point in a logfile via a hotkey and save this marked part on the Windows Desktop automatically

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#9280]
### Original suggestion by @AbhitejJohn:
Quote from [his comment on issue #9275](https://github.com/nvaccess/nvda/issues/9275#issuecomment-463547835):
> Also I wish I could clear/reset the logs from the UI :)

### Steps to reproduce:
1. Change the log level to "debug" in the General NVDA Settings.
2. Open the Log Viewer via the NVDA menu.
3. Try to remember the actual last line.
4. Open the start menu. Or just do anything else. It doesn't matter. But its logs are very, very important for you.
5. Switch back to the Log Viewer.
6. Have fun by finding the previous remembered line.
### Actual behaviour:
It isn't possible to clear the logged content until step 4. It has to deleted with Notepad++ or with any other useful source code editor manually, after the logfile was saved first.
### Expected behaviour:
Add the following hotkeys to NVDA:
+ NVDA+Shift+F2: Set start point in the logfile.
+ NVDA+CTRL+F2: Set end point in the logfile.

After NVDA+CTRL+F2 was pressed, the content between the start and the end point is selected and copied into a new logfile which is automatically saved on the Windows Desktop. The filename for this new logfile is based on the current timestamp, e.g. "NVDA_2019-02-15-012345.log".
#### NVDA installed/portable:
Both
#### NVDA version:
2018.4.1
#### Windows version:
Win7 to Win10-1903

**Comment by lukaszgo1** [comment]
NVDA+Ctrl+F2 is already used by test_navigatorDisplayModelText

**Comment by DrSooom** [comment]
@lukaszgo1: Thanks for the hint – I didn't know this. Well, then just replace F2 with F4 (or any other useful key). Or just change NVDA+CTRL+F2 to NVDA+Shift+F4. NVDA+Shift+F3 is already used to search backwards.

**Comment by leonardder** [comment]
[**@lukaszgo1**](https://github.com/lukaszgo1) commented on [15 Feb 2019, 13:14 CET](https://github.com/nvaccess/nvda/issues/9280#issuecomment-464027229 "2019-02-15T12:14:36Z - Replied by Github Reply Comments"):
> NVDA+Ctrl+F2 is already used by test_navigatorDisplayModelText

Wow, this script is actually entirely new for me.

Personally, I agree with the proposal to have a way to extract certain parts of the log for easy recording of log data. However, saving the log to the desktop by default sounds a bit too much overkill for me, it could easily lead up to a desktop full of these log snippets. I think that for such functionality, I prefer the clipboard.

**Comment by DrSooom** [comment]
> I think that for such functionality, I prefer the clipboard.

Well, sounds logical to me too. In the end the user always has to save the logfile on a different place than the Windows Desktop. So it doesn't matter if he moves the logfile itself or if he first has to paste the content of the copied section of the logfile into a new, blank text file. (Hopefully he isn't using Microsoft Word for it, like those who are saving screenshots within a Word document. Okay, that's a completely different topic. 😉)

But there is one issue with the clipboard method: The user could save the file in the wrong encoding. The encoding of the "nvda.log" is UTF-8 (without BOM) with CRLF line ending. The format of the line ending wouldn't be a problem, but not using UTF-8 could lead into one.
