### ISSUE TITLE
The nvda to automatically announce the search results in the start menu

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9283]
### Steps to reproduce:
For a few weeks I've noticed that nvda stops automatically announcing search results in the start menu.
When nvda works properly for example when typing ou nvda automatically announces outlook which is the suggestion of windows.
When this problem occurs while typing ou nvda does not advertise outlook, nvda only reads the typed letters.
When navigating with the arrow below the suggestions are read.
This returns to normal when restarting nvda or windows itself.
But after some time with the computer turned on the problem returns to occur, approximately 2 times a day assuming that the machine stays on for about 6 hours a day.
I still can not establish what happens before this happens, it seems a bit random (but it should not be, due to my incompetence I still can not understand).
### Actual behavior:
After a few hours of nvda usage the screen  reader stops automatically announcing the windows suggestions.
### Expected behavior:
even after a few hours of using nvda the screen  reader should continue advertising the windows search 
#### NVDA installed/portable/running from source:
install
#### NVDA version:
alfa 16768
#### Windows version:
10 16763.292
#### Have you tried any other versions of NVDA?
no
follows the log of when the problem occurs.
[windows.txt](https://github.com/nvaccess/nvda/files/2869519/windows.txt)

**Comment by Adriani90** [comment]
@fernando-jose-silva are you still having this issue in Windows 10 1903 update and NVDA 2019.2?

**Comment by fernando-jose-silva** [comment]
I no longer have this problem.
Thank you.
nvda alfa 18450 windows 18362.295

**Comment by Adriani90** [comment]
Closing as works for me.
