### ISSUE TITLE
Add a procedure to spell emojis

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#9286]
### Is your feature request related to a problem? Please describe.

Emojis can be announced as complete words, but spelling them is not supported.

### Describe the solution you'd like
When the review cursor is placed on an emoji, a gesture may open a dialog showing the words corresponding to the emoji description, the same announced by NVDA, so that they can be reviewed with speech or using a braille display, or copied.

### Describe alternatives you've considered

The description may be provided by pressing 2 or NVDA+. twice, but this could be a concern for people with mobility issues. 

### Additional context

Emoji descriptions is not shown in Speech Viewer, so this dialog could be especially useful. If this is marked as wontfix, we could try to include this feature in the Emoticons add-on, developed by @Christianlm and others.

**Comment by josephsl** [comment]
CC @LeonardDeR

**Comment by nvdaes** [comment]
Thanks @@josephsl . About the dialog, ui.browseableMessage could also be used. Other alternative would be if symbols could be searched in the symbol dialog, to view the description, but this is not comfortable.
Also, we need to think if the dialog will show the description chosen by the user in customized symbols, or the provided by default, or if this should be configurable.

**Comment by nvdaes** [comment]
Other thought about this: This should be generalized for other symbols, not just emojis, for instance comma and so on.
One possible approach would be:

>info=api.getReviewPosition().copy()
info.expand(textInfos.UNIT_CHARACTER)
ui.browseableMessage(characterProcessing.processSpeechSymbol(locale, info.text))

The locale could be the NVDA's interface language. I have tested this in the Python console. To avoid that a browseable message is open for normal characters, we could check that info.isalpha and info.isspace is False.
If this can't be included in NVDA, I'm thinking about making it available in Emoticons add-ons. This is useful to know how emojis should be writen when they are expanded.
