### ISSUE TITLE
Put advanced panel in the end of panel list

### ISSUE THREAD

**Issue by larry801** [nvaccess/nvda#9291]
### Is your feature request related to a problem? Please describe.
No
### Describe the solution you'd like
Put advanced panel in the end of panel list
### Describe alternatives you've considered
Other applications like MPC-HC usually puts put advanced panel in the last term in settings lists.
This reduce the chance of accidentally change advanced setttings.

**Comment by josephsl** [comment]
Hi, the thing is, it might not be possible to know beforehand which add-ons will add settings panels. Thanks.

**Comment by larry801** [comment]
With so many addons installed, I ignored the fact that these panels are from addons.
If we implement this by adding a function instead of append to categoryClasses directly
That's a lot of work for such a small thing.
Close for now.

**Comment by Brian1Gaff** [comment]
No but most other software I see has advanced at the end. Its a bit like 
windows drive letters. If you want a fixed one, set it to the highest you 
will ever need. I'd have thought something similar could be done with the 
settings panels.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
