### ISSUE TITLE
combobox under iframe is not read on firefox

### ISSUE THREAD

**Issue by aliyksel** [nvaccess/nvda#9292]
### Steps to reproduce:
there is a html select item in a page. main page uses IFrame and calls this page. 

### Actual behavior:
for firefox. I select combobox and push up or down arrow, value is changed but NDVA is silent. (not open options list)

### Expected behavior:
for firefox. I select combobox and push up or down arrow, value is changed  and NDVA should read current value.

#### NVDA installed/portable/running from source:
installed.

#### NVDA version:
2018.4.1

#### Windows version:
windows 7 professional
service pack 1

#### Name and version of other software in use when reproducing the issue:
firefox 65.0.1 (64-bit)

#### Other information about your system:
chrome is working.

#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

files:
a.html
<html>
  <iframe src="b.html" />
</html>

b.html
<html>
<select id="expiryMonth" name="expiryMonth"  size="1" ">
	<option value="">Month</option>
	<option value="01" >01</option>
	<option value="02">02</option>
	<option value="03">03</option>
	<option value="04">04</option>
	<option value="05">05</option>
	<option value="06">06</option>
	<option value="07">07</option>
	<option value="08">08</option>
	<option value="09">09</option>
	<option value="10">10</option>
	<option value="11">11</option>
	<option value="12" selected="selected">12</option>
</select>
<body>
<html>

**Comment by Adriani90** [comment]
cc: @jcsteh

**Comment by jcsteh** [comment]
This is a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1473234 . This is already being tracked for NVDA in #7819.
