### ISSUE TITLE
After updating to Windows 10 1809, NVDA's process crashes on the logon screen due to a locale error

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9300]
Reported by one of my colleagues.

### Steps to reproduce:
Start the computer while NVDA's startup at the logon screen is enabled.

### Actual behavior:
NVDA does not start, an error is printed that diverts us to a log file at c;\program files (x86)\nvda\nvda.exe.log

The following relevant snippet is in the log:

```
Traceback (most recent call last):
  File "nvda.pyw", line 29, in <module>
  File "locale.pyc", line 581, in setlocale
locale.Error: unsupported locale setting
```

Inspection reveals that this is caused by an error raised by `locale.setlocale(locale.LC_ALL,'')`

### Expected behavior:
NVDA starts normally

### Additional details
After logon, NVDA starts just fine, however the performance of the system seems to have decreased. May be it is just caused by a broken update, yet I believe we should catch this error somehow.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2018.4.1

#### Windows version:
Windows 10 version 1809

#### Other information about your system:
It forcefully updated from 1803 yesterday.

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes, latest Alpha

**Comment by stickbear2015** [comment]
I can't reproduce this on my HP or dell machines both running 1809.
NVDA starts normally with no log output similar to @leonardder's colleague's output.
note the version from winver for reference:
Windows Version 1809 (OS Build 17763.316)

**Comment by leonardder** [comment]
I can't reproduce this on my machine with 1809 either. I'm pretty sure 
this machine is just broken, but the way NVDA crashes is worrying.

**Comment by stickbear2015** [comment]
@leonardder is the user in question using a different locale than english?

**Comment by leonardder** [comment]
Yes, the locale is dutch.


In the regional settings of the system, we tried both changing the 
language and the beta UTF-8 option, but neither of them made a difference.

**Comment by leonardder** [comment]
Duplicate of #8726
