### ISSUE TITLE
When navigating with the arrows on a form, nvda is not announcing the type of control.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9304]
### Steps to reproduce:
I opened a form, and started navigation with the arrows below.
In a line the nvda announced:
Type your e-mail
By pressing arrow below the nvda read this field is required.
You would expect the nvda to announce editing, and then the message this field is required.
In this case nvda suppressed speech from the edit control type, and just said the page message this field is required.
Continuing the navigation with the arrow below by the webpage, nvda announced:
Enter phone number or extension
by pressing another arrow below the nvda repeated:
Enter phone number or extension
The expected would be that the nvda announce edition required.
Again nvda suppressed the control-type speech, and in this case repeated the line soon enough.
If I press an arrow below and return with an assault arrow, nvda announces the type of the control as expected.
Let's go to the palace to the palace:
Open the page:
https://docs.google.com/forms/d/e/1FAIpQLScdX2ksd9uLlCxJToNsNYMzN1D-Pv1hPbfgQUlqiDNZCxgjqw/viewform

This form is in português Brasil.

Walk with the arrows below until the nvda pronounce:

Digite seu email

press an arrow below and nvda will announce
This field is required.

the expected would be for the nvda to speak:
edit field required.

Walk with the arrow down until the nvda read

Digite o número do telefone ou o ramal

Press the down arrow and the nvda will repeat:
Digite o número do telefone ou o ramal

the expected one would be that the nvda read
required edition

### Actual behavior:
The nvda read the message on the page stating that the padding is mandatory plus does not read the type of control being manipulated.

### Expected behavior:
Messages on the page that say fill is required can not overwrite the speech of the control type.

### System configuration
My nvda is set to not switch between the browse mode and the focus mode automatically

#### NVDA installed/portable/running from source:
install
#### NVDA version:
2018.4.1
#### Windows version:
10 17134
#### Name and version of other software in use when reproducing the issue:
firefox 65.0.1

#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by Adriani90** [comment]
cc: @jcsteh

**Comment by Adriani90** [comment]
This works as expected in NVDA 2020.1 and Firefox 76. Closing as works for me.
