### ISSUE TITLE
Add Support to Natively View Music XML in the Browser

### ISSUE THREAD

**Issue by frastlin** [nvaccess/nvda#9306]
### Is your feature request related to a problem? Please describe.

There is currently no way to read sheet music in the web browser.

### Describe the solution you'd like

Currently the [Music XML specification](https://www.w3.org/2017/12/musicxml31/) [can be rendered in HTML5](http://cdm.link/2010/05/music-notation-with-html5-canvas-in-the-browser-standard-formats-for-scores/) and I would like something similar to MathML for Music XML.  
The interface should be very similar to [Lime Aloud](http://www.dancingdots.com/prodesc/limealoud.htm).

### Describe alternatives you've considered

There is no alternative way of reading sheet music in the browser without reading the raw music XML.

### Additional context

A publisher [contacted AER](http://lists.aerbvi.org/pipermail/aernet_lists.aerbvi.org/2019-February/049208.html) asking how to add accessible music to their textbooks. The only response that could be given is that there is nothing yet. I would like there to be something.

**Comment by leonardder** [comment]
Could you provide an example document?

In my opinion, being able to parse music XML falls beyond the scope of a screen reader, as Music XML is a pretty specific standard.

**Comment by frastlin** [comment]
OK, I think I figured out what is going on:
The [Music XML Spec](https://www.w3.org/2017/12/musicxml31/) is not official and there is no browser that renders it.
This means that there is no support in HTML without using canvas and a nonsemantic UI to render music in the browser.
So the only solution to this is to build a custom HTML widget while there is no browser spec for Music XML.

**Comment by DrSooom** [comment]
@frastlin: Maybe the abc notation is a suitable solution for that. I gave a talk about this at the SightCity-Forum 2017 in Germany. See http://abcnotation.com/wiki/abc:standard:v2.1 and https://danielmayr.at/abc/.
