### ISSUE TITLE
Object explorer not working correctly in Visual Studio 2017 (v15.3 and up)

### ISSUE THREAD

**Issue by francipvb** [nvaccess/nvda#9311]
### Steps to reproduce:

1. Open any type of project with object explorer available, such _.NET_.
1. Open object explorer with <kbd>ALT+CTRL+j</kbd>.
1. Ensure you're in the objects tree and select the first expandable item.
1. Expand it by pressing <kbd>right arrow</kbd>.
1. Enter into it with <kbd>right</kbd> or <kbd>down</kbd> arrow.
1. Contract it by pressing <kbd>left arrow</kbd> twice.
1. Press the <kbd>END</kbd> key to select the last item on the tree.
1. Repeat the last four steps with this last one.

### Actual behavior:

When entering into the expanded item, the next item gains the focus. It occurs only if the expanded item is not the last.

If the expanded item is the last, it works as expected.

### Expected behavior:

Expected behavior is like any other tree view even under visual studio, like the solution explorer.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

alpha-16813,a0b991af

#### Windows version:

Version	10.0.17763 build 17763

#### Name and version of other software in use when reproducing the issue:

Visual Studio Community 15.9.7

#### Does the issue still occur after restarting your PC?

Yes, reboot doesn't change anything.

#### Have you tried any other versions of NVDA?

I've used all stable versions of nvda between 2017.3 and this alpha I'm using now.

**Comment by francipvb** [comment]
CC @leonardder 

This is related to #7504.

**Comment by beqabeqa473** [comment]
hello.

found a regression when using vs 2019 (16.1 preview 3)

when openning menu, an exception is thrown and vs is not accessible at all.

ERROR - queueHandler.flushQueue (16:09:01.252):
Error in func _fakeFocus from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 53, in flushQueue
  File "IAccessibleHandler.pyc", line 819, in _fakeFocus
  File "NVDAObjects\__init__.pyc", line 280, in objectWithFocus
  File "NVDAObjects\__init__.pyc", line 93, in __call__
  File "appModules\devenv.pyc", line 94, in chooseNVDAObjectOverlayClasses
NameError: global name 'vs_major' is not defined

**Comment by francipvb** [comment]
Hello,

Sorry for this stupid error.

I published #9557 that fix this.

Thanks for your advise.
