### ISSUE TITLE
System focus follows browse mode off: Error while trying to access a listbox in Firefox 

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#9320]
### Steps to reproduce:
1. Open Firefox
2. In NVDA, set systemf focus follows browse mode to off by pressing nvda+8
3. Open this website
https://support.freedomscientific.com/training/Surfs-Up/WebTrack.htm
4. Press l to navigate to the list of ordered products
5. Press enter to enter the listbox
6. Change system focus follows browse mode to on by pressing again nvda+8
7. Focusing the listbox, press enter to enter it

### Actual behavior:
When pressin enter on the list, NVDA does not activate focus mode. Instead, this error is shown in the log:
```
Speaking [u'Ordered Products', u'\n']
IO - inputCore.InputManager.executeGesture (21:36:09.882):
Input: kb(laptop):downArrow
IO - inputCore.logTimeSinceInput (21:36:09.944):
0.062 sec since input
IO - speech.speak (21:36:09.944):
Speaking [u'Liste']
IO - inputCore.InputManager.executeGesture (21:36:10.364):
Input: kb(laptop):enter
ERROR - browseMode.BrowseModeTreeInterceptor.maybeSyncFocus (21:36:10.382):
postFocusFunc has not been called asynchronously
```

If system focus follows browse mode, the focus mode is activated correctly and I can select items in the list as usual.

### Expected behavior:
The focus mode should be activated also when system focus does not follow browse mode.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-16813,a0b991af

#### Windows version:
Windows 10 1809 Update

#### Name and version of other software in use when reproducing the issue:
Firefox 65.0.1

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA?
yes, 2018.4.1 works correctly

**Comment by Adriani90** [comment]
cc: @mltony, @michaelDCurran

**Comment by mltony** [comment]
Yes, I could reproduce this on my computer.
So the root cause for this is that when we call .setFocus() in certain conditions, we don't always receive the corresponding Windows gainFocus event. This problem also seems to occur in other scenarios. I'll try to see if I can rewrite the logic to avoid using async callbacks.

**Comment by Adriani90** [comment]
Since the pr was reverted, I am closing this as invalid. Will reopen it if I will see it again after the pr has been merged again. Thanks.
