### ISSUE TITLE
NVDA with Firefox reads page title after selecting a option from a select element

### ISSUE THREAD

**Issue by nathanielmendoza** [nvaccess/nvda#9328]
### Steps to reproduce:
1. Go to this pen: https://codepen.io/nathanielmendoza/pen/bZNvrg
2. Get focus on the select box with tab
3. Open the option list with spacebar.
4. Select an option with enter
5. Notice that NVDA will read the page title + "document" (so in this instance, it will read "Super simple select box screen reader test (Firefox + NVDA) document"

### Actual behavior:
It will read "Super simple select box screen reader test (Firefox + NVDA) document"

### Expected behavior:
Don't read the page title after selection

#### NVDA version:
2017.4, also updated and reproduced in 2018.4.1

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
Codepen

#### Other information about your system:
Firefox version: 65.0.1
https://www.mozilla.org/en-US/firefox/65.0.1/releasenotes/

**Comment by DrSooom** [comment]
@nathanielmendoza: Please add the Firefox version, where this issue occurs, to the issue description. Firefox 56.0.2 is currently the latest version. Thanks.

**Comment by nathanielmendoza** [comment]
Updated firefox version. This is on the newest version (65.0.1). Unsure if it exists in older versions.
https://www.mozilla.org/en-US/firefox/65.0.1/releasenotes/

**Comment by DrSooom** [comment]
@nathanielmendoza: You are right – 65.0.1 is the latest version of Firefox. I confused the Firefox version with the Thunderbird version, which is currently 60.5.2. Sorry.

**Comment by DrSooom** [comment]
Now [Firefox 65.0.2](https://www.mozilla.org/en-US/firefox/65.0.2/releasenotes/) is really the latest version. 😉

**Comment by Adriani90** [comment]
this is still reproducible in NVDA alpha 19420,a2c6f0f8 and Firefox 70.0.1.
cc: @jcsteh, @MarcoZehe.
