### ISSUE TITLE
NVDA 2018.4 sees an extra column of cells in word tables

### ISSUE THREAD

**Issue by tgeczy** [nvaccess/nvda#9335]
### Steps to reproduce:
1. Open a blank word document with Office 365 or 2016
2. Go to the ribbon and the insert tab.
3. Click "add new table.
4. Choose any desired number of columns / rows. For the purposes of this report, let there be a 4 x4 table.
5. Once created, type text in each column by moving to the next one with the right arrow.
6. you will notice that NVDA announces an extra "column 5" - but typing in this field actually places text in the subsequent row below, on column 1
### Actual behavior:
NVDA announces the presence of an extra row where there is none.

### Expected behavior:
NVDA should know that this table's index stops at 4.

**Comment by Adriani90** [comment]
Closing as duplicate of #4876.
