### ISSUE TITLE
Mail app in windows 10 causes NVDA to fall silent

### ISSUE THREAD

**Issue by ChrisMedley** [nvaccess/nvda#9341]
### Steps to reproduce:
Open the windows 10 Mail app
open a email with links within
click on any link, it doesnt seem to matter which site, and  open dfault browsr, in my case this is firefox 65
after you finished on the web page close firefox,  
go back to window mail app
then more often than not NVDA fall silent
in which case NVDA has to be restarted to regain speech once again

### Expected behavior:

after closing the browser NVDA should still have the use of its speech

### System configuration
n/a

#### NVDA installed/portable/running from source:
Installed copy of NVDA 

#### NVDA version:
version 18.4.1

#### Windows version:
windows 10 1809 17763.348

#### Name and version of other software in use when reproducing the issue:
latest version of the mail app will do

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your PC?
No, even a restart of NVDA will resolve the issue usually

##
## Have you tried any other versions of NVDA?
Yes, same issue

**Comment by Adriani90** [comment]
Do you have this issue after installing the Windows 10 app essentials addon from @josephsl?

**Comment by ChrisMedley** [comment]
yes, i have the win10 app essentials addon installed
whether that is causing the issue or not i could not tell you for sure

**Comment by josephsl** [comment]
Hi,

If you don't mind, can we get a debug log from you please?

Thanks.

**Comment by ChrisMedley** [comment]
[1-NVDA log.txt](https://github.com/nvaccess/nvda/files/2946334/1-NVDA.log.txt)

**Comment by josephsl** [comment]
Hi, looks like the app module/tree interceptor isn’t cleaned up properly, raising COM error exception. I’ll do something about it from WinTenApps side later today. CC @MichaelDCurran

**Comment by ChrisMedley** [comment]
thanks Joseph

**Comment by Adriani90** [comment]
Is this now solved?

 

 

Von: ChrisMedley <notifications@github.com> 
Gesendet: Freitag, 8. März 2019 18:55
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Mail app in windows 10 causes NVDA to fall silent (#9341)

 

thanks Joseph

**Comment by josephsl** [comment]
Hi, just because I have opened a pull request should not be a reason to assume that: you can close this issue, and it is resolved all the way. Therefore, I’m reopening it. Thanks.

**Comment by josephsl** [comment]
Hi,

Before I officially leave office (for a vacation), I'll release Windows 10 App Essentials 19.03.1 that will bring this fix for people using stable version(s) of NVDA. The official fix has been sent to NV Access for review.

Thanks.
