### ISSUE TITLE
External Synthesizer speaking "less than" character with arrowing or tabbing

### ISSUE THREAD

**Issue by LadyM7lNV** [nvaccess/nvda#9345]
estarting your PC?

**Comment by lukaszgo1** [comment]
@LadyM7lNV Can you please fill the issue template?

**Comment by LadyM7lNV** [comment]
I somehow didn't have access to the issue template..

Thank you,


-- 
Nancy Shackelford --Walk On Faith And Trust In Love - Michael Reid--

**Comment by LadyM7lNV** [comment]
Anytime when using external synth with NVDA and moving focus, either with tabbing or arrowing or going through tables, Etc, NVDA speaks "less than" before any word, character or line read. This is not affected in any way with any punctuation settings.
