### ISSUE TITLE
Add ons manager in Firefox flaky in latest 65 version

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#9350]
### Steps to reproduce:
Launch firefox 65 in windows 7, go to add on manager. Attempt to navigate the dialogue. You will find some of the options that previously scrolled round themes,  extensions etc, go away when you try to move. They do still work but are not spoken.

### Expected behavior:
It should work as it used to, so when you select the themes or extenssions you tab to that list. That will work, but yoyou have now no idea which list. its on
#### NVDA installed/portable/running from source:
Installed and portable. Latest beta and last stable ie latest being 2019.1 beta
#### Windows version:
Windows 7 64 bit
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
Not applicable
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
Yes see above
here is  nvda/f1

INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo 
(08:56:46.144):

Developer info for navigator object:

name: None

role: ROLE_UNKNOWN

states: STATE_FOCUSABLE, STATE_FOCUSED

isFocusable: True

hasFocus: True

Python object: <NVDAObjects.IAccessible.mozilla.Mozilla object at 
0x05521970>

Python class mro: (<class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 
'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 
'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, 
<class 'NVDAObjects.NVDAObject'>, <class 
'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, 
<class 'baseObject.AutoPropertyObject'>, <type 'object'>)

description: u''

location: RectLTWH(left=240, top=218, width=1680, height=834)

value: None

appModule: <'firefox' (appName u'firefox', process ID 3688) at address 
5524130>

appModule.productName: u'Firefox'

appModule.productVersion: u'65.0.2'

TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>

windowHandle: 2229086L

windowClassName: u'MozillaWindowClass'

windowControlID: 0

windowStyle: 399441920

windowThreadID: 2232

windowText: u'Add-ons Manager - Mozilla Firefox'

displayText: u''

IAccessibleObject: <POINTER(IAccessible2) ptr=0x821ddbc at 548c030>

IAccessibleChildID: 0

IAccessible event parameters: windowHandle=2229086, objectID=-4, childID=-77

IAccessible accName: None

IAccessible accRole: u'vbox'

IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, 
STATE_SYSTEM_VALID (1048580)

IAccessible accDescription: u''

IAccessible accValue: None

IAccessible2 windowHandle: 2229086

IAccessible2 uniqueID: -77

IAccessible2 role: IA2_ROLE_UNKNOWN

IAccessible2 states: IA2_STATE_VERTICAL, IA2_STATE_OPAQUE (132096)

IAccessible2 attributes: 
u'margin-left:0px;text-align:start;text-indent:0px;id:list-view;tag:vbox;class:view-pane;margin-top:0px;margin-bottom:0px;margin-right:0px;display:-moz-box;'

Suspect the problem is Firefox, as I am pretty sure it worked on an older version.

**Comment by DrSooom** [comment]
CC: @jcsteh and @MarcoZehe; Maybe already fixed in the upcoming 66.0?

**Comment by MarcoZehe** [comment]
Yes, 67 in any case, don't recall which of the fixes got uplifted to 66. But yes this will improve shortly.

**Comment by jcsteh** [comment]
This is fixed for Firefox 66, as both patches got uplifted from 67. https://bugzilla.mozilla.org/show_bug.cgi?id=1525569 https://bugzilla.mozilla.org/show_bug.cgi?id=1525937

**Comment by Brian1Gaff** [comment]
Thanks, I was not sure whether it was a chicken or an egg situation!


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
