### ISSUE TITLE
Microsoft Japanese IME is not announced as expected with Windows 10 v1809 and Edge 

### ISSUE THREAD

**Issue by nishimotz** [nvaccess/nvda#9362]
### Steps to reproduce:

* enable and select Microsoft IME Japanese
* launch Microsoft Edge
* press Ctrl+L
* press Hankaku-Zenkaku key (or Alt+Tilde with English keyboard array)
* type y a m a

### Actual behavior:

with Windows 10 version 1809 (64bit) Japanese

* press Hankaku-Zenkaku key, nothing announced. actually, IME is opened
* press y : 'y' is announced
* press a : 'a' is announced. actually reading string changed to phonetic character 'ya' i.e. u+3084
* press m : 'm' is announced
* press a : 'a' is announced. actually additional reading string changed to phonetic character 'ma' i.e. u+307e

### Expected behavior:

with Windows 10 version 1803 (64bit) Japanese

* press Hankaku-Zenkaku key, 'IME opened' is announced
* press y : 'y' is announced
* press a : 'a' is announced and 'ya' is followed by
* press m : 'm' is announced
* press a : 'a' is announced and 'ma' is followed by

### System configuration

NVDA keyboard

* speak typed characters : on 
* speak typed words : off

NVDA input composition

* automatically report all available candidates : off
* report changes to the reading string : on
* report changes to the composition string : on

#### NVDA installed/portable/running from source:

* NVDA should be installed

#### NVDA version:

* 2019.1beta1 (and possibly previous releases as well)

#### Windows version:

* as mentioned above, Windows 10 version 1809 (and possibly later)

#### Name and version of other software in use when reproducing the issue:

* Microsoft IME Japanese
* Microsoft Edge browser

#### Does the issue still occur after restarting your PC?

* Yes

#### Have you tried any other versions of NVDA?

* maybe, but still investigating

**Comment by Adriani90** [comment]
@nishimotz how is this behavior in NVDA 2020 Beta with Edge Cromium 81 or higher?
If it works there, I suggest to close this issue since the Cromium version will be distributed automatically with Windows 10 20 H1 update.

**Comment by nishimotz** [comment]
Chromium Edge is not yet widely used in Japan, but we have confirmed that this glitch is not happening with the combination of the traditional Edge and the more recent NVDA.
