### ISSUE TITLE
Adobe Acrobat DC: When copying / reading text in browse mode, separate lines are merged together

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#9370]
### Case1: copying text
1. Open test file.
2. Press control+a (select all), press control+c (copy text).
3. Press control+v (paste) to notepad.

#### Actual behavior:
All lines of copied text are merged together.

#### Expected behavior:
Each line of text should be on its own line. E.G.

* 第一條 結構保固期間
* 第二條 結構保固範圍
* 第三條 房屋結構監測
* 第四條 房屋結構檢測

(If you follow the steps above, but switch to focus mode, the issue will not occur - each line of text will be on its own line.)

### Case2: reading text
1. Open test file.
2. Press downArrow three times.
#### Actual behavior:
NVDA reports:
三條 房屋結構監測 3.1 監測項目與方式： 3.1.1 設置大地沉陷觀測點樁位，與永久不動觀測點樁位進行觀測。 3.1.2 設置建築物沉陷觀測點於全區地下1 樓，並搭配桿式沉陷計。 3.1.3 設置

#### Expected behavior:
NVDA reports:
第一條 結構保固期間

#### NVDA Installed/portable/running from source:
Installed.

#### NVDA version:
2018.4.1

#### Windows version:
6.1.7601 service pack 1

#### Name and version of other software in use when reproducing the issue:
Adobe Acrobat DC 19.010.20098

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA?
NVDA_2018.3.2.

#### Other information:

In the past, a similar issue occurred in "screen review", and fixed in 2014.2. Seeing issue 3900 for more details.

**Comment by surfer0627** [comment]
[test_copying_text.pdf](https://github.com/nvaccess/nvda/files/2960745/test_copying_text.pdf)

**Comment by DrSooom** [comment]
There is a very annoying issue in the 19.x version of the Adobe Reader when the PDF file doesn't contain tags. This issue didn't exist in the 18.x version and it also don't exist in version 9.3 of the Foxit Reader – as far as I remember correctly. The Adobe Reader 19.x always creates a single text line per page for untagged PDF files.

**Comment by surfer0627** [comment]
@DrSooom
> This issue didn't exist in the 18.x version and it also don't exist in version 9.3 of the Foxit Reader 

For testing, where could I download Acrobat DC 18.x? It seems hard to find download link and change Acrobat update settings.

**Comment by DrSooom** [comment]
This is a very good question. I have no idea. After searching I would say [here](https://www.itechtics.com/download-adobe-acrobat-reader-dc-18/), but this isn't an official site of Adobe. But the download links below in this article lead to the Adobe website. Here the link for [18.009.2004/en-US](http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/1800920044/AcroRdrDC1800920044_en_US.exe).

Regarding disabling the update functionality, I found the following:
> HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Adobe\Adobe ARM\Legacy\Reader\{Produkt Code}
◾ Hier müsst ihr den Eintrag Mode bearbeiten. Es stehen euch folgende Optionen zur Verfügung:
0: Do not download or install updates automatically.
1: Do not download or install updates automatically.
2: Automatically download updates but let the user choose when to install them.
3: Automatically download and install updates.
4: Notify the user downloads are available but do not download them.

Source: https://www.tobias-hartmann.net/2016/02/acrobat-reader-updates-deaktivieren/

**Comment by surfer0627** [comment]
Thank you for the download links and user tips.
After installing 18.009.2004, Acrobat DC got quick update.
I do not have chance to change settings.

**Comment by DrSooom** [comment]
@surfer0627: Try to add the registry key before starting the Adobe Reader. But I'm not sure, if the update process starts automatically after the installation. In that case you have to kill the process "armsvc.exe" via the task manager. Please be careful. I have no idea what will happen after you have killed this process. And maybe you have to log off and log on again after the registry changes, because the Windows Registry is also read/loaded during the user logon process.

**Comment by surfer0627** [comment]
After searching issues, it seems that this is a duplicated of [7275](https://github.com/nvaccess/nvda/issues/7275#issuecomment-308015865).

jcsteh commented on 13 Jun 2017 
> Because NVDA splits text into lines itself (according to the "Maximum number of characters on one line" Browse Mode setting), we strip line break characters, as otherwise, you end up with a lot of long lines followed by short lines (as I recall happened in JAWS when I used it years ago). Having spoken to someone involved in PDF accessibility specification writing, my understanding is that the correct way to author such content is to tag each line as a separate list item or paragraph. Unfortunately, it seems no one actually does this in the wild.

> I think the only way we could reasonably solve this is to ignore NVDA's own settings for splitting lines and instead use only the line breaks in the PDF. That would also require us to not treat line breaks as paragraphs for PDF. This would be somewhat inconsistent with browse mode everywhere else, but I think consistency is probably outweighed by usability here.

But, how to explain the reason that line breaking issue sometimes occurs in Acrobat, and not in Chrome.
