### ISSUE TITLE
The Extras menu can not be opened with the x letter

### ISSUE THREAD

**Issue by sonor3000** [nvaccess/nvda#9373]
### Steps to reproduce:

1. Open the nvda menu with NVDA+n
2. Press the x letter

In older versions of NVDA this opened the Extras menu. In current 2019.1 beta this is not working anymore.

### Actual behavior:

The Extras menu will not be opened....

### Expected behavior:

Open the Extras menu like in older NVDA versions....

#### NVDA installed/portable/running from source:

Current beta of 2019.1 installed

#### NVDA version:

2019.1 beta 1

#### Windows version:

Win10, 64 bit

#### Have you tried any other versions of NVDA?

Yes. In older versions the Extras menu can be opened with the x letter.

**Comment by DrSooom** [comment]
I guess this has to be fixed by a translator – a simple "&" is missing. Which language are you using?

**Comment by Adriani90** [comment]
This is german, I think I have fixed it in last Alpha. We can track this issue in the german community channels. Closing.

**Comment by sonor3000** [comment]
I am using NVDA with the German language.

**Comment by bdorer** [comment]
Funily enough the following entries in the nvda menu don't show the 
underlined key although it works and nvda announces it:
tools (T should be underlined)
Donate (D should be underlined)
All items in the tools menu eccept manage addons don't show an 
underlined key.
In the help menu all items eccept about have an underlined key.
May someone could look at the sourcecode or in .po files wheather there 
is a difference between those entries which don't show an underlined 
letter and wich items not?
It is very intresting. Although the German item for speech viewer 
translated as "Sprachbetrachter" you can activate it with s, but the 
letter isn't underlined.


Am 14.03.2019 um 13:13 schrieb sonor3000:
