### ISSUE TITLE
Firefox: aria-describedby doesn't update when the element changes

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#9400]
### Steps to reproduce:
1. Load the attached HTML file into firefox.
2. Press control+home.
3. Press f.
4. Press space a few times.
5. Press control+home and f again. The description hasn't changed.
6. Press NVDA+tab. NVDA reads the new description.

### Actual behavior:
The description doesn't change
### Expected behavior:
The description changes
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Version: alpha-16933,bae84ed6
#### Windows version:
Windows 10 Version 1809 (OS Build 17763.316)

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No
[test.txt](https://github.com/nvaccess/nvda/files/2997498/test.txt)

**Comment by DrSooom** [comment]
@tspivey: Which Firefox version are you using? 66.0 is the latest one.
CC: @jcsteh and @MarcoZehe

**Comment by tspivey** [comment]
66.0.1.

**Comment by jcsteh** [comment]
This is a Firefox bug. There's no specific bug for it, but it's basically the same as https://bugzilla.mozilla.org/show_bug.cgi?id=493683 except that bug is for name change, where this is about description change. The fix will be pretty much the same.

**Comment by jcsteh** [comment]
Fixed in Firefox 87 (currently Nightly).
