### ISSUE TITLE
NVDA crashes Firefox Nightly when choosing label during filter creation in Gmail.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#9402]
### Steps to reproduce:
1. Open firefox Nightly, login to Gmail.
2. Perform a search and then click advanced search options.
3. Click create filter.
4. Check Apply the label, move to button for selecting a label, press it with space, and try to navigate in the newly opened menu.
### Actual behavior:
Firefox Nightly crashes, the following is written in the NVDA log
ERROR - eventHandler.executeEvent (19:12:48.443):
error executing event: gainFocus on <NVDAObjects.IAccessible.mozilla.BrokenFocusedState object at 0x0531EBF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "C:\Users\Lukasz\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 426, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "appModules\firefox.pyc", line 24, in event_stateChange
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1448, in event_gainFocus
  File "textInfos\offsets.pyc", line 458, in expand
  File "virtualBuffers\__init__.pyc", line 376, in _getUnitOffsets
  File "textInfos\offsets.pyc", line 437, in _getUnitOffsets
  File "textInfos\offsets.pyc", line 306, in _getCharacterOffsets
  File "virtualBuffers\__init__.pyc", line 230, in _getTextRange
WindowsError: [Error 1726] remote invocation of a procedure failed.

the crash report from Nightly is here:
https://crash-stats.mozilla.org/report/index/7f8b7e21-9ef0-4e44-b758-8c0b30190323
### Expected behavior:
The list of the labels should be navigable.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA version alpha-16941,e3b2e797

#### Windows version:
Windows 7 x64
#### Name and version of other software in use when reproducing the issue:
Firefox Nightly 68.0a1 (2019-03-23) (64-bit)
#### Other information about your system:
With JAWS Nightly doesn't crash in this situation.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No
cc @jcsteh @MarcoZehe

**Comment by jcsteh** [comment]
This is not a crash in Firefox code. It seems the vbuf has a reference to an invalid child node here. The line we crash on is this (in VBufStorage_fieldNode_t::getTextInRange):

`child->getTextInRange(max(startOffset,childStart)-childStart,min(endOffset-childStart,childLength),text,useMarkup,filter);`

@MichaelDCurran, any ideas?

**Comment by jcsteh** [comment]
This seems to be similar to #8924. There are two lists: one which gets focus and one which does not. As with the menu causing trouble in that issue, all of the list items are in the tree, but not inside the focused list. However, the focused item is always moved beneath the focused button using aria-owns and focused using aria-activedescendant. That is, there is only ever one list item which is a child of the focused list. When you move the focus, the previously focused item returns to the full list and the newly focused item gets owned and made the active descendant of the focused list.
Note that the accessibles aren't re-generated in this case. The list items always have the same ids, but their parents change.

What I don't understand is why #8930 doesn't fix this.

**Comment by jcsteh** [comment]
We've also had a [report of a crash in markNodeAsNonreusableIfInAncestor](https://bugzilla.mozilla.org/show_bug.cgi?id=1532603). While a different crash and we don't have STR, it's likely that this is also due to an invalid child node and that this was caused by a node moving.
