### ISSUE TITLE
Problem reading Word files with high zoom level or large fonts

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#9403]
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:

- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

### Steps to reproduce:
With screen resolution set to 1680 x 1024 open one or, better, two Word documents.
Zoom documents to 150% or set fonts in the documents to 28pt for level 1 headings and 16pt for body text.
Use up/down arrows to read the documents.
### Actual behavior:
Presentation of text will be highly unreliable.
### Expected behavior:
Text will be presented reliably.
#### NVDA installed/portable/running from source:
Both installed and portable.
#### NVDA version:
2018.4.1 and 2019.1 RC1
#### Windows version:
Windows 10 V1803

#### Name and version of other software in use when reproducing the issue:
MS Word 365
#### Other information about your system:
Problem largely resolved when changing screen resolution to 1280 * 768 and not using large fonts.  The problem only occurred because I am producing videos of screen activities and wanted a bigger image.  The problem occurs whether or not the video recording software is running.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
2018.4.1 and 2019 RC1 as above

**Comment by Brian1Gaff** [comment]
Just a comment. Does this mainly happen if the files are more than one page 
long or at the page boundary?
 I've noticed some weirdnesses  like this, sometimes long delays before 
things start to read again or actually crash and need nvda to restart.
 Trouble is its very flaky and seems to have little bearing on what version 
of Word is in use either.
 Bah humbug..
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by andrew-l-d** [comment]
The problem I described above has become more severe with NVDA 2019.2 beta 1.  If increasing the font size from 12 to 14pt, NVDA sometimes makes that nasty double-tone sound and becomes unresponsive.  I am still running a screen res of 1280 x 768.  Having reverted to 2019.1.1, the problem has so far not recurred.  I am hoping that the issue is because of the beta status - I am doing a presentation this week and could do without NVDA misbehaving.  Apologies - did not check the log file but will do so if/when the problem occurs again.  I am concerned that this quite significant issue has apparently not received attention.  It does not occur with other screen readers in my experience.
Andrew

**Comment by ehollig** [comment]
@andrew-l-d can you provide an update now with NVDA 2023.1?

**Comment by andrew-l-d** [comment]
I tested with both 2023.1 RC! and 2022.4.  I was not able to replicate the issue.  I have not had need to use the offending font size/zoom level recently and had neglected to check.


Andrew

**Comment by Adriani90** [comment]
Thanks for the update. I am closing this issue as works for me. if it is still occuring, please comment again here and we can reopen this one, or open a new updated issue.
