### ISSUE TITLE
Add the translated changelog conclusion and a link to the full one to the Update Check Dialog/Notification

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#9408]
### Steps to reproduce:
+ Path: NVDA menu » Help » Check for updates...
+ Wait for the auto-update check notification.
### Actual behaviour:
+ [Text] A new version of NVDA (2019.x) is available. (or so)
+ [Buttons] Download and install the update, Remind me later and Close
### Expected behaviour:
+ Add a protected textfield which includes the translated changelog conclusion as well as a new link or button called "Show full changelog", which open the localized version of changelog html site in a webbrowser.
+ The focus after the appearance of the update check dialog should be changed from the button "Close" to the protected textfield, because this will reduce any unwanted interactions to the absolute minimum.
+ Of course this means that all translated changelog html files must be uploaded to the NV Access website as well. Currently only the English changelog is directly available on it.
#### NVDA installed/portable:
Both
#### NVDA version:
The issue description depends on 2018.1, but it should be the same for 2019.1 too.
#### Windows version:
Win7 to Win10-1903
### See also:
Issue #8514, #9174 and #9409

**Comment by JulienCochuyt** [comment]
I up-vote the need for the change log to be available on the update notification.

The read-only field on the dialog could indeed show the full change log for the version, as it is not that long. It could be returned by the update server, as the language setting is already sent to it.
Anyway, a link to a hosted version would do the job too.

It could be useful to consider this feature also for #3208, even if the current test implementation is quite different.

**Comment by Adriani90** [comment]
I am closing this in favor of #14274 which contains more technical information and a more concrete design proposal.
