### ISSUE TITLE
Dialogs in VirtualBox reported as "unknown"

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#9414]
### Is your feature request related to a problem? Please describe.

Quote from user:
"virtualbox still says unknown in the dialogues that come out when a virtual machine is powered on, for example, the save the machine state, send shutdown signal, and to force the power off that is removed with the combinadción Ctrl+q, and so in all the dialogues of information that come out during the execution always NVDA says unknown"

### Describe the solution you'd like

Dialogs to be correctly identified and reported.

### Describe alternatives you've considered

Jaws can read these dialog boxes correctly.

### Additional context
Using latest version of VirtualBox 6.04, and NVDA 2018.4.1 and NVDA 2019.1

Also note in attached log, language is set to Spanish, so "unknown" is reported as "desconocido".

Reporting of Unknown / Desconocido is preceded by several warnings in the log:
"IO - inputCore.InputManager.executeGesture (12:38:00.138):
Input: kb(desktop):downArrow
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (12:38:00.148):
accRole failed: (-2147024809, 'El par\xe1metro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (12:38:00.150):
accRole failed: (-2147024809, 'El par\xe1metro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (12:38:00.151):
accRole failed: (-2147024809, 'El par\xe1metro no es correcto.', (None, None, None, 0, None))
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (12:38:00.151):
Cancelling
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (12:38:00.151):
accRole failed: (-2147024809, 'El par\xe1metro no es correcto.', (None, None, None, 0, None))
IO - speech.speak (12:38:00.154):
Speaking [u'desconocido']"
[desconocido.txt](https://github.com/nvaccess/nvda/files/3015500/desconocido.txt)

**Comment by lukaszgo1** [comment]
See also  https://www.virtualbox.org/ticket/629
According to the commends there it is very hard to debug. Oracle devs don't seems to be very interested in fixing this but if something could be done on the NVDA side I would be very grateful.

**Comment by Qchristensen** [comment]
I initially reported this on behalf of a user (and neglected to record the details).  I have reached out to another user I know uses VirtualBox to see if they can reproduce it.

**Comment by Adriani90** [comment]
@mhussaincov Could you test if this issue still occurs with NVDA 2024.2 Stable or 2024.3 Beta?

**Comment by Adriani90** [comment]
We didn't get any updates upon requests, from users that can reproduce this issue, since more than 5 years. I am closing as abandoned. If this is still an issue in NVDA 2024.4, please comment and we can reopen.
