### ISSUE TITLE
Feature request: NVDA sound control shortcut

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#9416]
Hi
In the daily use of NVDA, and is a music producer, there is more than one sound card, this time there is a need to switch back and forth.
### Is your feature request related to a problem? Please describe.
The normal sound card switching steps are like this: First open the context menu, then open the mobile center, then open to change the audio settings. Finally, switch between the sound card and the microphone from the sound.
The above steps are very troublesome for me. NVDA can add a set of voice control hotkeys to solve these problems.
### Describe the solution you'd like
The following is a set of sound card shortcuts:
Ctrl plus Win plus Alt plus 7%9 before a sound application
Ctrl plus Win plus Alt plus 9% after a sound application
Ctrl plus Win plus Alt plus 4%9 before a playback device
Ctrl plus Win plus Alt plus 6%9 after a playback device
Ctrl plus Win plus Alt plus 1%9 before a recording device switch
Ctrl plus Win plus Alt plus 3%9 after a recording device switch
Ctrl plus Win plus Alt plus 2% 9 to reduce the volume 13, 46, 79 selected
Ctrl plus Win plus Alt plus 8%9 to increase the volume 13, 46, 79 selected
Ctrl plus Win plus Alt plus 5%9 mute / recovery 13, 46, 79 selected
Ctrl plus Win plus Alt plus small carriage return %9 to 1,3 microphone enhanced adjustment
Ctrl plus Win plus Alt plus minus %9 set the default device
Ctrl plus Win plus Alt plus plus sign %9 to open the recording control window
The first two sets of hotkeys Ctrl+Win+Alt+7 or 9 occur when the application refers to the volume of all programs that your current lock opens. For example, if you open two skype, a browser and NVDA, when you press Ctrl+Win+Alt+keypads 7 and 9, you will hear these programs, and you will hear his current volume value after the program. When you adjust to a program and need to increase its volume, you can adjust it with Ctrl+Win+Alt+keypads 2 and 8. All the following mentioned need to adjust the volume increase and decrease, you need to use Ctrl+Win+Alt+keypad 2 and 8, which is what the screen reader hears, Ctrl+Win+Alt+2 or 8 can The items you hear are adjusted to increase or decrease the volume. Ctrl+Win+Alt+4 or 6 is to select the device to be generated, and adjust the volume of the item you hear and increase as above. The generating device mentioned here refers to all enabled devices, such as speakers, seen in the sound control box, and may have other playback devices depending on the sound card or the computer. Ctrl+Win+Alt+1 or 3 is to select the recording device, adjust the volume of the heard item to increase or decrease the same as above. The recording device mentioned here is all the enabled devices, such as microphones, seen in the Sound Controls tab. Other devices may also be available depending on the computer. Ctrl+Win+Alt+5 Mute or unmute the item heard by the current hotkey. For example, if you adjust to the microphone, you can press this group of hotkeys to mute and unmute the selection. Ctrl+Win+Alt+Keyboard Enter, here is the adjustment level of the microphone. Unlike XP, here you can directly adjust his enhancement level. There are three levels, press continuously, you can Switch between levels. Ctrl+Win+Alt+-(minus sign) Set the currently heard item as the default device operation. Only the items heard by Ctrl+Win+Alt+1, 3, 4, and 6 can be operated here. Because it is not a device project, it is naturally not possible to set it as the default device. The hotkey group homes 7, 9 get the program volume control, not the device. Note: Please be cautious here. Ctrl+Win+Alt++ (plus sign), open the recording control window. As the name implies, this group of hotkeys can directly open the recording control setting window, and the recording control window opened with the notification area is a window. Set in the hotkey group for quick setup.
### Describe alternatives you've considered
no
### Additional context
no
thank

**Comment by Adriani90** [comment]
Is this really falling in nvda‘s purpose? Actually you can switch to another sound card by pressing nvda+ctrl+s and choosing an output device in that dialog. In my view this feature should at least reported to Microsoft to be part of Windows. At least this is my opinion.

**Comment by dingpengyu** [comment]
hi Adriani
I know that I can switch from the NVDA settings, but the sound card switching in the NVDA settings is not comprehensive.

**Comment by DrSooom** [comment]
Even if this sounds quite interesting for a NVDA add-on, I'm not sure if NVDA has the permission to handle these tasks. Personally I wouldn't want to see this feature in the NVDA core, because quite a lot of NVDA users don't need this – it's just too specific for the core.

**Comment by dingpengyu** [comment]
In fact, the purpose of my issue is to improve the production efficiency of NVDA. There are still many places where NVDA can be improved. Sound card control is only a small part of it.

**Comment by dingpengyu** [comment]
> Even if this sounds quite interesting for a NVDA add-on, I'm not sure if NVDA has the permission to handle these tasks. Personally I wouldn't want to see this feature in the NVDA core, because quite a lot of NVDA users don't need this – it's just too specific for the core.

hi DrSooom
Respect your opinion

**Comment by dingpengyu** [comment]
The main application environments for sound card control include: Radio Hosts Musicians with independent sound cards and podcasters There is also an environment for audio tutorials.
After using the sound card control, the screen reader can be separately output to the second fast sound card, so that the listener can have a better operation experience regardless of the lecture or the host, and the listener can hear a better sound.
Finally, why integrate sound card control into a screen reader rather than a plug-in because the experience of the screen reader module is better than the plug-in. This is my conclusion that I tested the Simplified Chinese input method plugin. If my comments have errors, please ask
thank

**Comment by fernando-jose-silva** [comment]
I already missed a shortcut key to toggle the output of nvda to different sound cards on a notebook that did not automatically switch between the headphone output and the speakers automatically. In this notebook in question the headphone output and the speakers were shown as different sound cards.
It should be noted that in this notebook I could not change this behavior even updating the sound drivers and could not change this in the sound settings of windows.
