### ISSUE TITLE
NVDA automatically reads all input fields on an aspx page (non-stop) when tabbing into the 1st input field on IE

### ISSUE THREAD

**Issue by varunmshetty** [nvaccess/nvda#9417]
### Steps to reproduce: 
Open the URL https://account.pho-dev.ca/signup.aspx on IE 11 browser (v11.648.17134.0)
Navigate to the "First Name" field using keyboard tabbing.

### Actual behavior: 
On IE 11, NVDA reads out the following: "Put First Name star required field, last name star required field, email star please enter email and so on..". Other browsers like Firefox and Chrome does not have this issue.

### Expected behavior: 
On IE 11, NVDA should just read "Put First Name star required field". It should only read the other fields when focus is on the other fields.

#### NVDA installed/portable/running from source:
NVDA installed on a Windows 10 Enterprise laptop and is being used on a website which is being browsed using the IE 11 browser.

#### NVDA version: 
2018.4.1

#### Windows version: 
Windows 10 (Version 1803; OS Build 17134.648 )

#### Name and version of other software in use when reproducing the issue: 
Can be reproduced after a Windows system restart with minimal applications running. Can be reproduced on multiple Windows 10 machines, not restricted to 1 machine.

#### Other information about your system: 
Issue occurs on multiple machines with NVDA installed.

#### Does the issue still occur after restarting your PC? 
Yes, restart doesn't fix the issue.

#### Have you tried any other versions of NVDA? 
No.

**Comment by varunmshetty** [comment]
Hello everyone, Just curious if anyone had a chance to look at this behavior. Please let me know.

Thanks,
Varun

**Comment by Adriani90** [comment]
Support for IE ended in 2022 completely and the browser is being removed automatically from machines that still have it after an Edge update in February 2023. I don't expect any accessibility updates to IE mode in MS Edge, so I am closing this as abandoned.
