### ISSUE TITLE
Browse mode doesn't work in MS Word

### ISSUE THREAD

**Issue by jakubl7545** [nvaccess/nvda#9422]
### Steps to reproduce:
Open any MS Word document
switch to browse mode with NVDA+space
### Actual behavior:
Focus mode remains active with no error
### Expected behavior:
Browse mode should turn on
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
alpha-16976,7fc6c71f
#### Windows version:
Windows 10 1803
#### Name and version of other software in use when reproducing the issue:
Microsoft Word 2016 16.0.11328.20220)
### Other questions
 @#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No
@leonardder

**Comment by josephsl** [comment]
Hi, confirmed. Note that this does not happen with 2019.1, so looks like a recent commit to master might be to blame. Thanks.

**Comment by leonardder** [comment]
Looks like the ability to disable browse mode by default is the cause here. I might be able to provide a fix next week. Was pretty sure I tested this properly before, but oh well.

**Comment by josephsl** [comment]
Hi,

Regression caused by PR for #8716.

Thanks for confirming our thoughts.
