### ISSUE TITLE
NVDA no longer lets me turn on browse mode inside application role

### ISSUE THREAD

**Issue by pitermach** [nvaccess/nvda#9425]
### Steps to reproduce:
In either Chrome or Firefox, go to a website making use of the aria application role (IE https://cyclepath.iamtalon.me) or the attached HTML example. Get your focus inside the content contained in the application role, and try to turn on browse mode with NVDA+Space

### Actual behavior:
This used to work, but no longer does. While the focus is inside the application,  NVDA+Space does nothing. Only after pressing CTRL+NVDA+Space I can get browse mode back. But if there is any elements that can't be focused inside the application (like the text paragraph in the attached example) the only way to read them is using object navigation
### Expected behavior:
NVDA+Space should turn on browse mode and let me navigate through the content of the application.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-16976,7fc6c71f
#### Windows version:
Windows 10Ver1809 (64-bit) build 17763.379
#### Name and version of other software in use when reproducing the issue:
Google Chrome Version 73.0.3683.86 (Official Build) (64-bit), firefox 66.0.2 (64-bit) 
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
Yes. alpha-16953,89f0702a on Windows 10 1903 build 18362.1 with the same web browsers isn't exhibiting these problems.
[apptest.zip](https://github.com/nvaccess/nvda/files/3026574/apptest.zip)

**Comment by leonardder** [comment]
See 9422 and 9423

**Comment by pitermach** [comment]
Ah, so these issues might be related. Do you think #9423 will also fix this regression? I don't have a source installation to check, but if it does I can close this issue.

**Comment by leonardder** [comment]
I'm pretty sure it will fix this. I'd say, lets keep this open for now until you can confirm that it's fixed.

**Comment by leonardder** [comment]
The fix is now in Alpha snapshots. Could you verify whether it is fixed?

**Comment by pitermach** [comment]
I just tested with alpha-16982,01118965. It looks like the issue was indeed fixed
