### ISSUE TITLE
Word 2016, NVDA Advanced Mode: Alt Text Does Not Speak In Tables

### ISSUE THREAD

**Issue by jhomme** [nvaccess/nvda#9433]
### Steps to reproduce:

- Turn on NVDA Advanced mode
- Use a document that contains a table
- Ensure that the table has alt text in the Title field
- Move out of the table, then back into it. 
### Actual behavior:
NVDA does not speak the alt text.
### Expected behavior:
NVDA should speak the alt text.
#### NVDA installed/portable/running from source:
Installed. Not portable.
#### NVDA version:
2019.1.
#### Windows version:
10.0.17134.648
#### Name and version of other software in use when reproducing the issue:
Microsoft Word 2016 Microsoft Word for Office 365 MSO (16.0.10730.20264) 32-bit 
#### Does the issue still occur after restarting your PC?
Yes.
#### Have you tried any other versions of NVDA?
No. This is the first version with the feature.

**Comment by Adriani90** [comment]
How is this in NVDA 2020.1?
Also what do you mean by advanced mode? Do you mean the browse mode which can be enabled by nvda+space bar?

**Comment by Adriani90** [comment]
We didn't hear any updates from the initial author since many years. Closing as abandoned.
