### ISSUE TITLE
Explorer.exe crashes in Windows 7 when start menu accessed with the mouse.

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#9435]
### Steps to reproduce:

On Windows 7:
1. Click on the Start button to open the start menu.
2. Move the mouse over a couple of the items in the start menu as if to select something.

### Actual behavior:

Explorer.exe stopped responding, and was restarted by Windows.
Intiailly I used SAPI 5 voice, and the log contained:
"DEBUGWARNING - eventHandler.executeEvent (11:39:07.355):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x052C8AF0> with extra args of {'y': 991, 'x': 337}
Traceback (most recent call last):
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\__init__.pyo", line 928, in event_mouseMove
  File "documentBase.pyo", line 24, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyo", line 314, in __init__
COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))"

Full log: [Win7Explorerlog.txt](https://github.com/nvaccess/nvda/files/3031994/Win7Explorerlog.txt)

I then restarted the computer, changed the synth to eSpeak and repeated with the same result.  It took about 10 or 15 seconds to crash this time and in the meantime reported each menu item as the mouse moved over it. After reading the last menu item before crashing, the log reads:

DEBUGWARNING - watchdog._watcher (12:53:44.414):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 233, in <module>
  File "core.pyo", line 519, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 1003, in Notify
  File "core.pyo", line 491, in run
  File "mouseHandler.pyo", line 257, in pumpAll
  File "mouseHandler.pyo", line 223, in executeMouseMoveEvent
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\__init__.pyo", line 928, in event_mouseMove
  File "documentBase.pyo", line 24, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyo", line 314, in __init__

DEBUGWARNING - eventHandler.executeEvent (12:53:44.584):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x050C2C30> with extra args of {'y': 988, 'x': 139}
Traceback (most recent call last):
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\__init__.pyo", line 928, in event_mouseMove
  File "documentBase.pyo", line 24, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyo", line 314, in __init__
COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

This has been reported by several users with several other scenarios (all involving explorer), but using the mouse in the start menu seems a consistent way to trigger it.

### Expected behavior:
Explorer shouldn't crash.

#### NVDA version:

NVDA 2019.1 installed 

#### Windows version:

Windows 7 Home Premium, version 6.1, build 7601, service pack 1.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA?
Previous versions of NVDA (2018.4.1) do not produce a crash, and repeating without NVDA running there is no crash.

**Comment by Qchristensen** [comment]
I also meant to add, accessing the Start menu with the keyboard works fine.

**Comment by DrSooom** [comment]
Does this issue also occur if mouse tracking (NVDA+M) is disabled?

**Comment by Brian1Gaff** [comment]
It does but there is something odd from time to time when reviewing 
characters ie actual spelling using the review modes that can end in the 
explorer has stopped working issue as well. Often I've seen strange things 
going on in older copies of Word resulting in the machine needing a reboot. 
Hard to get a log in such situations I find. Its only worse in the latest 
version of nvda.
 I do not use the mouse so I suspect that its not actually the mouse as 
such, more likely its easier to fit the criteria using it.
Its not a mega problem but it has happened  afew times since I put it on. I 
would need to do more testing to find out if the log is similar though.

These sort of effects are very hard to  get to happen to order.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Qchristensen** [comment]
With mouse tracking disabled, the crash doesn't happen.

Brian, re crashes which require a reboot - in the %temp% folder, where the nvda.log is kept, there is usually an nvda-old.log which is the log from the previous time NVDA was run.  If you look for that file when you restart the computer, it should have just about everything NVDA recorded about what it was doing.  Also re the problems with issues which can be hard to reproduce, that was why I was specific in how to repro this one.  This one definitely seems to be triggered by the mouse.

**Comment by Adriani90** [comment]
cc: @nishimotz, @leonardder

**Comment by leonardder** [comment]
Ah, looks like i"m the author of this crash, see https://github.com/nvaccess/nvda/pull/8572.

Disabling mouse tracking seems to be an acceptable work around for now, but I"ll provide a fix anyway.

**Comment by lukaszgo1** [comment]
I don't know if it has the same underlying cause, but for me even with mouse tracking disabled it is sufficient to route mouse to start menu search field in Windows 7 to cause explorer to crash. When it crashes it takes NVDA with it, so the only way to go back to the working condition is to kill explorer.exe from another account.

**Comment by leonardder** [comment]
@lukaszgo1: yes, this is expected behavior according to the cause of the crash, which is a freeze in the UIA client library according to earlier findings. We thought that these were fixed, but it seems like they aren't.
A try build is on the way.

**Comment by leonardder** [comment]
@lukaszgo1 @Qchristensen Could you test [this try build](https://ci.appveyor.com/api/buildjobs/kc0a38ugwnoiyhhq/artifacts/output%2Fnvda_snapshot_try-explorerCrash-18422%2C9d9323fb.exe)

**Comment by lukaszgo1** [comment]
I can confirm that routing mouse to the start menu search box no longer crashes explorer with this build.

**Comment by Brian1Gaff** [comment]
Hi a couple of weeks ago  we had this crash 49 times while attempting to copy some files with the mouse with nvda loaded, so I'll be glad to get a fixed snap asap to save my producers sanity!
 Brian
