### ISSUE TITLE
Appx: exclude ARM64 lib folder from included in AppX package

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9436]
### Is your feature request related to a problem? Please describe.
As of NVDA 2019.1, ARM64 libraries are included to interface with 64-bit ARM versions of several apps, notably Firefox. While these libraries are needed in regular distribution, Windows Store version might not allow this. In fact, the sconscript file for AppX excludes ARM64 lib folders from list of files/folders to be excluded from the resulting package.

### Describe the solution you'd like
In addition to updating the manifest for Windows Store app package, add ARM64/lib to list of folders and files excluded from AppX package.

### Describe alternatives you've considered
None

### Additional context
None

**Comment by leonardder** [comment]
I'm not convinced that ARM64 libs are not allowed. How is the Windows Store version of NVDA on ARM64 supposed to communicate with Firefox for ARM when we exclude these libraries?

**Comment by josephsl** [comment]
Hi,

Same can be said about 64-bit Firefox on x64 processors at this moment - I just tested a side loadable copy of NVDA I've got, ran Firefox 66 64-bit version, and got error 1775 (NULL context handle). In short, unless Store policy has changed, DLL injection isn't allowed for Store apps.

Thanks.
