### ISSUE TITLE
Update CLDR 34 to CLDR 35

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#9445]
### Actual behaviour:
NVDA 2019.1 uses CLDR 34.
### Expected behaviour:
NVDA should use CLDR 35, which was released on March 27, 2019.
See also: http://cldr.unicode.org/index/downloads/cldr-35
CC: @leonardder and @michaelDCurran

**Comment by leonardder** [comment]
Thanks for bringing this up. The github repo we use for this has to be updated for this. See https://github.com/fujiwarat/cldr-emoji-annotation/issues/2
