### ISSUE TITLE
SCons doesn't detect Visual Studio 2019 properly, which may cause build issues as soon as appveyor updates its images

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9446]
### Steps to reproduce:
1. Install Visual Studio 2019, delete 2017
2. Try to build NVDA

### Actual behavior:
SCons prints an error that it couldn't find the universal platform components.

### Expected behavior:
SCons prints an error indicating that Visual Studio 2017 is required

#### Additional details
Testing on my system reveals that SCons detects VS2019 as version 14.1, rather than 14.2. I think this is likely to break things as soon as appveyor updates their images with VS2019.

**Comment by dingpengyu** [comment]
hi leonardder
I read the AppVeyor Platform Updates page, the official version of visual studio2019 has not been updated
This is the page address:
https://www.appveyor.com/updates/

**Comment by leonardder** [comment]
As they seem to prefer bug reports on a mailing list, i created [this](https://pairlist4.pair.net/pipermail/scons-users/2019-April/007684.html) thread there.

**Comment by leonardder** [comment]
See scons/scons#3346

**Comment by leonardder** [comment]
Scons 3.1.0 supports Visual Studio 2019.

@feerrenrut: What do you think? Might the recent transition to python 3, which requires people to revisit their building tool chain, justify an update to visual studio 2019?

**Comment by feerrenrut** [comment]
I'm not sure it really adds much convenience to developers, since installing a new version of python is quite easy and unrelated to Visual Studio. I also think it introduces quite a bit of risk.

Appveyor allows you to specify past VM "image" names to use for your builds, if we have trouble we can specify. We might be doing that already.

**Comment by leonardder** [comment]
On the other hand, many people are switching to VS2019 due to its accessibility improvements.
We could also consider removing the vs2017 enforcement (i.e. accept 2017 and above), while advising vs2017 while not blocking the use of vs2019 for people at their own systems.

**Comment by feerrenrut** [comment]
I think (but I haven't tested this) it would be fine to swap to VS2019 as long as the appropriate components are also installed. Note that VS2019 apparently supports `VC++ 2017 v141 toolset (x86,x64) v14.16` .

Going further, I think it might be enough just to install the appropriate buildtools, without requiring a full visual studio install: https://visualstudio.microsoft.com/downloads/

**Comment by leonardder** [comment]
I"m currently also running vs2019 with de 141 toolset. That works with current scons. Scons 3.1 doesn't allow me to build though, because it is not able to find vs2019.
