### ISSUE TITLE
Quick switching of windows of current application

### ISSUE THREAD

**Issue by adamsamec** [nvaccess/nvda#9453]
I am missing a keyboard command which would show a list of the opened windows of the currently active application only and let me select the window which I want to switch to.

### Is your feature request related to a problem? Please describe.
I am always frustrated when I have to Alt + tab through all the opened windows of all the running applications to find the one that I want to switch to.

### Describe the solution you'd like
A keyboard command that would display a list of opened windows belonging to the currently active application only. From such a list the user would be able to easily switch to another window of the current application, also utilising navigation in the list using first letters of the window title. An example of the use case for this feature is when one is having opened two or more windows of Mozilla Firefox and wants to quickly switch only between them, or when one is having opened two or more file explorer folders and wants to switch only between them.

### Describe alternatives you've considered
Currently the only way to work around this issue, although only in Windows 10, is using a separate desktop for each application, which is quite awkward.

### Additional context
This should work in all applications.

**Comment by DrSooom** [comment]
Win+1 to Win+9 (and maybe Win+0 too). You can also combine these hotkeys with Shift (new instance) and Alt (Jumplist). But I'm not sure if they are still the same on Windows 10. They were introduced with Windows 7. And ALT+ESC (firm switching order) instead of ALT+TAB is also possible. And Win+T moves the focus to the task bar, where you can navigate between its entries (include grouped entries) via the arrow keys.

**Comment by Adriani90** [comment]
Windows+tab or ctrl+alt+tab already displays a list of opened Windows. After pressing, you can navigate with left and right arrow through all the opened windows. To switch to a window, press enter on it.

**Comment by Adriani90** [comment]
So there are several confortable solutions already in place.

**Comment by Adriani90** [comment]
Thus, I am closing this one as won't fix. Please comment on it with arguments and suggestions and we can reopen it. Thanks!

**Comment by adamsamec** [comment]
Hello,
the issue https://github.com/nvaccess/nvda/issues/9460 already includes this issue and is described in more detail. So you can even delete this issue. Thanks and sorry for confusion.

**Comment by DrSooom** [comment]
@adamsamec: This issue is already closed. It needn't to be deleted.
