### ISSUE TITLE
Make elements list resizable and scrollable

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#946]
**Reported by gids on 2010-09-26 14:48**
It would improve the usability of the elements list for sighted users if it were resizeable and displayed scroll bars

'''Steps to reproduce'''

Open NVDA

Open Firefox

Visit a webpage

Press NVDA + F7

Press Headings radio button

'''Actual Results'''

Window is not resizeable and does not display scrollbars

'''Expected Results'''

Window is resizeable and displays scroll bars

**Comment by leonardder** [comment]
@FeerRenrut, would you like to give sighted assistance to do this for #588, or does #6332 block this?

**Comment by feerrenrut** [comment]
#6332 was a general issue to make sure that dilogs in nvda can be resized (if it is appropriate). If its necessary to do that for this issue, or for #588 I'm happy to help with doing that. Also happy to visually review a PR to ensure that the changes are visually acceptable. 

#6332 doesn't have a particularly high priority, and isn't one of our projects at the moment, so is unlikely to get done any time soon. 

I think this issue (#946) could possibly be closed. On next, the elements list (within the dialog) displays scroll bars correctly. The dialog, however, is not resizeable, which might be helpful, but no information is hidden in the current implementation and making it resizable would be covered by #6332.
