### ISSUE TITLE
NVDA gets laggier over time in Word using UIA and has to be restarted periodically

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#9465]
Reporting on behalf of a friend.

### Steps to reproduce:

1. Enable usage of UIA in word
2. Use word normally.

### Actual behavior:

NVDA should remain responsive while using Word.

### Expected behavior:

NVDA slows down over time when working in Word, requiring a restart every 10 mins to retain performance.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-17012,f3b9c3ce

#### Windows version:
Windows 10 1803

#### Name and version of other software in use when reproducing the issue:
Office 365 16.0.1145.20200

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by Neurrone** [comment]
CC: @michaelDCurran @leonardder 

This is still happening, as of the latest master build.

**Comment by leonardder** [comment]
cc @bramd: Is this something you're experiencing as well? I've also seen this.

**Comment by bramd** [comment]
Yes, I've seen this multiple times. It's one of the major reasons that I disabled UIA in Word for now. Unfortunately, I've no idea how to start debugging this or provide useful feedback.

**Comment by bramd** [comment]
It seems fixed, but I also don't use Word extensively on a daily basis.

**Comment by leonardder** [comment]
@Neurrone  anything to add here?

**Comment by Neurrone** [comment]
I don't use Word on a daily basis as well but when I tried to reproduce this yesterday, I wasn't able to do so.

I'll close this issue for now since this appears to be resolved.
