### ISSUE TITLE
AddonsDialog: some add-ons are marked as Enabled when NVDA is launched with --disable-addons flag

### ISSUE THREAD

**Issue by DataTriny** [nvaccess/nvda#9473]
### Steps to reproduce:

1. Launch NVDA.
2. Make sure you have at least one add-on installed.
3. Close NVDA.
4. Launch NVDA from the command line with the `--disable-addons` flag.
5. Open the add-on manager dialog.

### Actual behavior:

Add-ons that are enabled on your profile will appear as enabled on the dialog.

### Expected behavior:

Since NVDA has been told to start with all add-ons disabled, and since they are effectively not running, they shouldn't appear as enabled.

I found this when looking at #5785.

Since a label indicates that you must restart NVDA to re-enable your add-ons, and because the `--disable-addons` will likely be used by people who know what they're doing, I am wondering if we shouldn't disable this dialog and its menu entry all together.

#### NVDA installed/portable/running from source:

NVDA Installed.

#### NVDA version:

NVDA 2019.1.

#### Windows version:

Windows 10 Education version 1809.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA?

No.

**Comment by fisher729** [comment]
Confirmed.

My recommended action/fix would be to:

1. Leave the add-on dialog enabled.
2. Each add-on should be marked as disabled.
3. No option to enable or disable them should be present.

**Comment by DataTriny** [comment]
I agree. Will try to implement this soon!

**Comment by feerrenrut** [comment]
> I am wondering if we shouldn't disable this dialog and its menu entry all together.

The dialog is still useful, allowing users to get information about their addons and uninstall them. This is particularly useful if an addon is causing a usability problem.

**Comment by fisher729** [comment]
No, do not disable the dialog, just disable the option to enable or
disable the add-ons, as well as show each add-on as disabled while in
this mode.

**Comment by josephsl** [comment]
Hi,

I'm wondering if the root problem is #6275? I'll do some tests to see if it is indeed a mistake from that one with 2018.4.

Thanks.

**Comment by josephsl** [comment]
Hi,

Yep, testing shows this is a regression.

Thanks.
