### ISSUE TITLE
Impossible to use NVDA after exiting math content

### ISSUE THREAD

**Issue by jakubl7545** [nvaccess/nvda#9481]
### Steps to reproduce:
In order to reproduce it you must have braille display connected.
Open this page
https://en.wikipedia.org/wiki/Normal_distribution
go to any math formula
press NVDA+alt+m to interract with math content
press escape to exit math
### Actual behavior:
NVDA produces this error on any key press and must be restarted 
ERROR - eventHandler.executeEvent (17:39:45.654):
error executing event: becomeNavigatorObject on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x051EA990> with extra args of {'isFocus': True}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 986, in event_becomeNavigatorObject
  File "braille.pyc", line 1957, in handleReviewMove
AttributeError: 'Region' object has no attribute 'obj'
### Expected behavior:
NVDA should work normally.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
alpha-17047,56e208d2
#### Windows version:
windows 10 1803
#### Name and version of other software in use when reproducing the issue:
Mozilla Firefox 66.0.2
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by DrSooom** [comment]
CC: @leonardder and @jcsteh

**Comment by Adriani90** [comment]
@jakubl7545 how is this now in NVDA 2020.1 and Firefox 76? Are you still seeing this issue?

**Comment by Adriani90** [comment]
Is anyone with a braille display able to test whether this is still reproducible in NVDA 2024.2?
cc: @aaclause, @LeonarddeR, @burmancomp, @Emil-18
