### ISSUE TITLE
Stops reading midway through sentence

### ISSUE THREAD

**Issue by yooc** [nvaccess/nvda#9482]
### Steps to reproduce:
1. Open a page with some amount of text to read. Tested using this example page: http://22point.com.au/random/test.html
2. Attempt to read through text using down arrow key.

### Actual behavior:
NVDA stops at random points of the text. Can't read to end of sentence. But the content is accessible by continuing to read through the text using arrow key.

### Expected behavior:
NVDA can complete reading at least a complete sentence of text. Preferably, will read the entirety of text encapsulated in a DOM node.

### System configuration
2 different configurations both encountered the same behavior. Will list configurations labeled with the user.
#### NVDA installed/portable/running from source:
Both installed

#### NVDA version:
2 different configure
- User A: Version 2019.1
- User B: Version 2018.1.1

#### Windows version:
- User A: Version 10.0.16299 Build 16299
- User B: Version 10.0.16299 Build 16299

#### Name and version of other software in use when reproducing the issue:
- User A: Chrome Version 73.0.3683.103
- User B: Firefox Version Firefox 52.9.0

**Comment by ehollig** [comment]
This is probably due to the setting in browse mode settings for "Maximum number of characters on one line" set to 100. This option can be changed to any value, with a maximum of 250. @yooc does this solve the issue for you if you change the value to 250? CC @leonardder and @michaelDCurran to see why exactly this is capped at 250.

**Comment by yooc** [comment]
@ehollig That worked! Thanks for the tip. We'll try to spread the knowledge on our part as well. 😄

**Comment by ehollig** [comment]
As the user is able to change this with an existing setting, I am going to close this.
