### ISSUE TITLE
Possible bug when navigating with table in webpage

### ISSUE THREAD

**Issue by sine-w** [nvaccess/nvda#9483]
### Steps to reproduce:
visited https://www.smartid.gov.hk/en/Who-shall-replace-identity-cards/index.html
press t, and NVDA speak table  with 1 rows and 1 columns
however, if I press down arrow , it speak column 2 ..., 
press down arrow again, it speak column 3....
again, column 4.
after column 4, if I press down arrow, it speak column 1, where it didn't speak row 2.

reporting this because I am not sure if it is a HTML code problem or NVDA problem.
  

#### NVDA installed/portable/running from source:
latest stable

#### NVDA version:
2019.1
#### Windows version:
Wind 7 pro
#### Name and version of other software in use when reproducing the issue:
Latest Firefox 66

#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by DrSooom** [comment]
The W3C NU HTML checker report more than [120 errors for this site](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.smartid.gov.hk%2Fen%2FWho-shall-replace-identity-cards%2Findex.html) including errors in the table. Could it be that the rows and columns of the table are responding to the display resolution by using JavaScript?

**Comment by Adriani90** [comment]
This works correctly with NVDA alpha-20220,1c4519a6, Chrome 81 and Firefox 76. Cjlosing as works for me.
