### ISSUE TITLE
NVDA doesn't narrate parentheses in aria-keyshortcuts attribute

### ISSUE THREAD

**Issue by kolaps33** [nvaccess/nvda#9484]
### Steps to reproduce:
Please open the example: https://jsfiddle.net/m3b6tq79/
1. navigate to the first button. 
2. Observe NVDA narration:

If example would not be available the html is:

```
<ul role="menu">
        <li role="presentation">
                <button aria-label="Big smile emoticon" role="menuitem" aria-keyshortcuts="(laugh)"> 1 </button>
        </li>
</ul>
```
### Actual behavior:
 "big smile emoticon laugh"

### Expected behavior:
 "big smile emoticon menu 'left parenthesis' laugh 'right parenthesis'"

#### NVDA installed/portable/running from source:
Portable copy

#### NVDA version:
2019.1

#### Windows version:
OS build: 17763.379
Version: 1809

#### Name and version of other software in use when reproducing the issue:
Chrome Version 73.0.3683.103 (Official Build) (64-bit)

#### Other information about your system:
Win 10 Enterprise, Lenovo laptop

#### Does the issue still occur after restarting your PC?
Yes it is reproducible always

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I haven't try.

**Comment by Adriani90** [comment]
This works correctly. For this to work you need to 
1. In NVDA menu under preferences / settings / object presentation, enable "report object shortcut keys"
2. IN in NVDA's speech settings change the interpunctuation to "most".

By default "report object shortcut keys" is enabled, but interpunctuation is set on "some". That's probably why you didn't hear the paranthesis. Changing interpunctuation to "most" solves this. 

Closing as works for me.
