### ISSUE TITLE
Excel crashes when data validation drop-down is used

### ISSUE THREAD

**Issue by nishimotz** [nvaccess/nvda#9487]
### Steps to reproduce:

* start NVDA and Excel, open new sheet
* move to cell A1
* Alt A V V to open "Data Validation" dialog
* Alt+A to focus on "Allow"
* use arrow keys and select "List", and Enter
* use Tab or Alt+S to focus on "Source" edit
* type "A,B,C"
* Enter to apply validation to the cell
* make sure focus is still on cell A1
* press Alt+downArrow to open the combo box
* select "A" and press Enter
* select "B" and press Enter
* select "C" and press Enter

### Actual behavior:

* during the repetition of combo box selections, Excel crashes very often

### Expected behavior:

* Excel should not crash

#### NVDA installed/portable/running from source:

* installed

#### NVDA version:

* NVDA 2019.1.1rc1 + OneCore voice (such as Microsoft Mark)

#### Windows version:

* Windows 10 (1809) 64bit + English default language

#### Name and version of other software in use when reproducing the issue:

* Office 365 Excel version 1903 (English UI)

#### Does the issue still occur after restarting your PC?

* yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

* not yet

debug log is as follows

```
IO - inputCore.InputManager.executeGesture (18:52:57.002):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (18:52:57.201):
Input: kb(laptop):upArrow
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (18:52:59.061):
IUIAutomationElement.buildUpdatedCache failed given IDs of set([30019, 30022, 30086, 30025, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079])
DEBUGWARNING - eventHandler.executeEvent (18:52:59.061):
error executing event: typedCharacter on <NVDAObjects.UIA.ListItem object at 0x05429C70> with extra args of {'ch': u'\r'}
Traceback (most recent call last):
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\__init__.pyo", line 913, in event_typedCharacter
  File "speech.pyo", line 683, in speakTypedCharacters
  File "api.pyo", line 248, in isTypingProtected
  File "baseObject.pyo", line 47, in __get__
  File "baseObject.pyo", line 147, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyo", line 787, in _get_isProtected
  File "baseObject.pyo", line 47, in __get__
  File "baseObject.pyo", line 147, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyo", line 1116, in _get_states
  File "NVDAObjects\UIA\__init__.pyo", line 741, in _getUIACacheablePropertyValue
COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
DEBUG - appModuleHandler.cleanup (18:52:59.122):
application excel closed
DEBUG - treeInterceptorHandler.killTreeInterceptor (18:52:59.122):
Killed treeInterceptor: <NVDAObjects.window.excel.ExcelBrowseModeTreeInterceptor object at 0x05545C10>
```

related issue in Japanese 
* https://github.com/nvdajp/nvdajp/issues/192

**Comment by michaelDCurran** [comment]
When I perform these steps, I do not see a crash. However, focus gets stuck on the dead list item each time I press enter to choose the item in the list, and I need to press alt twice, or alt tab away and back again to force focus to the active cell. Is this what you are experiencing?
If it is in deed a crash, can you supply a crash dump for Excel?

**Comment by feerrenrut** [comment]
@nishimotz Can you still reproduce this error?

**Comment by dingpengyu** [comment]
Is the current problem solved?
cc @nishimotz 
thank

**Comment by nishimotz** [comment]
This problem cannot be reproduced with the following configuration:

* Windows 10 version 1903 (64bit) Japanese
* NVDA alpha-19004 (portable)
* Office 365 Excel version 1909 (build 12026.20334) Japanese

**Comment by ehollig** [comment]
According to @nishimotz in https://github.com/nvaccess/nvda/issues/9487#issuecomment-545707551 this can no longer be reproduced. Closing this issue.
