### ISSUE TITLE
NVDA reports incorrectly the title of the download progress window of Internet Download Manager

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#9489]
### Steps to reproduce:
1. Download internet Download Manager from [its website](http://www.internetdownloadmanager.com). It has a trial period, which will be enough for our purposes.
2. Install Internet Download Manager.
3. Get the URL address of a file to download (preferably a large one, so while it's downloading, you can easily observe the behavior of NVDA in the download progress window of Internet Download Manager).
4. Open Internet Download Manager from its desktop icon.
5. Go to its menubar -> Tasks -> Add new download.
6. In the "Enter new address to download" window, paste the URL from step 3 in the "Address" field and press ENTER.
7. In the next window, check that everything is OK and activate the "Start download" button. The download will start.
8. While the download is in progress and the download progress window of Internet Download Manager is in focus, invoke the NVDA command to read the title of the window (NVDA+T).

### Actual behavior:
NVDA reports "idman" as the title of the download progress dialog of Internet Download Manager.

### Expected behavior:
NVDA should report the download progress in percentage and the name of the downloading file as the title of the download progress dialog of Internet Download Manager. That is what visually appears on the screen.

### System configuration
- Operating system: Windows 10 Pro version 1809 (build 17763.437), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-17077,7f274eca, installed, in bulgarian.
- Internet Download Manager (IDM) version: 6.32 build 9, in english.
- Processor: Intel Core i5-4670 at 3.40GHz.
- RAM Memory: 8.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC887 at Intel Lynx Point PCH - High Definition Audio Controller.

#### Does the issue still occur after restarting your PC?
Yes, it does.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, the behavior is the same with older versions (incl. stable ones) of NVDA.

**Comment by gholamim6** [comment]
hello.
i have the same issue too.
if i press NVDA+t only says "IDMAN"
i need to use screen view or press Alt+tab to read the title.
also i have another problem.
the NVDA did not read items when i move on my download list.
when i navigate between Download list by arrow keys, NVDA did not notify me the item information.
i need to press tab to until i come back again on download list and now NVDA read the current Download information
but when i move to another file, the issue will remain.

**Comment by gholamim6** [comment]
sorry.
i forgot to tell my system information.
IDM V33 build 3.
NVDA 2019.1.1
and Windows 10 pro Newest version.

**Comment by Adriani90** [comment]
This works correctly with NVDA alpha-20220,1c4519a6 and Internet Download Manager 6.37. Closing as works for me. Feel free to comment on this issue if you are still haing it and we can check again.
