### ISSUE TITLE
NVDA causes word 2007 and older versions too,  assume that document is modified while it is not

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#949]
**Reported by aleksey_s on 2010-09-29 20:59**
While opening a document in word 2007 with NVDA, even if document isn't actually touched at all, when closing word asks whether to save changes or not. However, it behaves in normal way if NVDA isn't running.

**Comment by leonardder** [comment]
@MichaelDCurran @Brian1Gaff, have you still seen this issue lately? I'm tempted to close as won't fix, given the age of Office 2007 and older.

**Comment by lukaszgo1** [comment]
I am still able to reproduce it with Office 2010. 
## str:
1. Download attached file.
2. open it and start say all.
3. stop say all with CTRL key and press alt+f4.
Word asks about saving changes, but nothing has been modified.
[plan Informatyka_licencjat v.1.1.docx](https://github.com/nvaccess/nvda/files/2499568/plan.Informatyka_licencjat.v.1.1.docx)

**Comment by Brian1Gaff** [comment]
Yes  been going on for years. I was wondering if it might be the way something is hooked into a routine that is doing it, but the problem is, it is not every file that  gets the issue.
 Brian

**Comment by Adriani90** [comment]
I am not able to reproduce this issue in NVDA 2019.1.1 and MS Word 2010 and 2016 / 365. Is anyone still able to see this issue? I think there was a PR which solved this issue but I don't recall exactly which one it was.

**Comment by lukaszgo1** [comment]
For me opening the file which I've attached in my last commend in Word 2010 and closing it immediately causes this prompt to appear. I am running Windows 7 x64 and latest NVDA Alpha.

**Comment by Adriani90** [comment]
@lukaszgo1 how is this in NVDA 2019.3.1? Maybe this has been fixed by chance while updating to Python 3.

**Comment by Adriani90** [comment]
@lukaszgo1 any updates on this? I wonder if there are still users out there using Word 2010 or older at all?
