### ISSUE TITLE
NVDA aria-live reads different things for non-standard words.

### ISSUE THREAD

**Issue by luisluix** [nvaccess/nvda#9493]
### Steps to reproduce:

https://jsfiddle.net/rcqvum5j/

have a dropdown linked to a textbox, with aria live. 
when the dropdown changes, change the text in the textbox.  nvda should read the word added.
make the words and the values differnts from each other.

### Actual behavior:

If you are navigating by keyboard up/down it reads different things going up->down than down-> up. it also cuts off in the middle of the words while reading.

in the fiddle provided, it reads ma, when going down, and matorres when going up.

### Expected behavior:

read words as they are and not cut them off. And not read different things when going up/down in the dropdown.

Although im not sure if NVDA handles non-dictionary words differently.

#### NVDA version:
2019.1.1

#### Windows version:
windows 10

This is on Firefox.
Edit: Firefox 66.0.3

**Comment by DrSooom** [comment]
@luisluix: Please add the Firefox version to the issue description. Thanks.
CC: @jcsteh

**Comment by luisluix** [comment]
I added the version, is the latest one tho.

**Comment by luisluix** [comment]
after researching more it seems to be intended behavior

https://github.com/nvaccess/nvda/issues/6963#issuecomment-291693090

nvda will only read the diff of what changed.

**Comment by jcsteh** [comment]
> after researching more it seems to be intended behavior
> 
> [#6963 (comment)](https://github.com/nvaccess/nvda/issues/6963#issuecomment-291693090)
> 
> nvda will only read the diff of what changed.

Correct. If you want the entire value to be read always, add aria-atomic.
