### ISSUE TITLE
error in google docs table nav

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#9494]
### Steps to reproduce:
1. open a new docs document with braille mode enabled.
2. create a 3x3 table.
3. fill out the table.
3. try to press `alt+ctrl+<arrow keys>`

### Actual behavior:

```
Input: kb(laptop):alt+control+downArrow
ERROR - scriptHandler.executeScript (12:43:20.176):
error executing script: <bound method Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible.script_nextRow of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x0380B150>> with gesture u'alt+ctrl+down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "documentBase.pyc", line 174, in script_nextRow
  File "documentBase.pyc", line 161, in _tableMovementScriptHelper
  File "documentBase.pyc", line 126, in _getNearestTableCell
TypeError: coercing to Unicode: need string or buffer, int found
```

### Expected behavior:

NVDA can move around the table.

#### NVDA installed/portable/running from source:
instaled

#### NVDA version:
alpha-17077,7f274eca

#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
docs, chrome, firefox
#### Have you tried any other versions of NVDA? If so, please report their behaviors.

worked before 2019.1

**Comment by DrSooom** [comment]
@derekriemer: Please add the Chrome and Firefox version to the issue description and try with NVDA 2019.1.1 as well. Thanks.

**Comment by derekriemer** [comment]
happens with 2019.1.1 and it's obvious. No need to add firefox and chrome versions, it occurs with them all after 2019.1.
