### ISSUE TITLE
User is not informed if there is a clickable element in the cells of detailslist component while using nvda.

### ISSUE THREAD

**Issue by SriNandiniG** [nvaccess/nvda#9498]
### Steps to reproduce:
https://codepen.io/vitalius1/pen/OqerJN
### Actual behavior:
In the codepen demonstation, there is a dialog box that shows up upon clicking elements in the detailslist. The narrator/nvda does not mention button/link which tells the users that there is on click. I have raised the same issue to office-ui-fabric team( https://github.com/OfficeDev/office-ui-fabric-react/issues/8493), and received a response saying "not reading out the role of each element in a row seems more like a screen reader issue than a Fabric issue", hence bringing the same into notice of NVDA team
### Expected behavior:
nvda has to inform the user if there is clickable element in the detailslist.
#### NVDA version:
2018.4.1
####Web Browser:
Google chrome
 Version 74.0.3729.131
#### Windows version:
Windows 10 enterprise

**Comment by DrSooom** [comment]
@SriNandiniG: Please add the webbrowsers (including their versions) to the issue description where this issue occurs/was tested. Thanks.

**Comment by SriNandiniG** [comment]
updated. Thanks!

**Comment by Adriani90** [comment]
NVDA works correctly with this table in Chrome 81 and Firefox 76, In the third column, all the buttons are reported. If you enable "clickable" in document formating settings in NVDA, then NVDA will also report the clickable atribute on the elements in the column headers.
I am closing as works for me. But please feel free to comment on this if you think I have misunderstood this issue and we can reopen. Thanks.
