### ISSUE TITLE
NVDA GOES TO SYSTEM MENU WHEN BROWSING FACEBOOK

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#950]
**Reported by dharvey on 2010-09-30 04:00**
Using Firefox 3.6.10 with NVDA 2002.2-beta2
1.  Log into Facebook
2.  Use up and down arrows to read the page.
3.  You'll hear NVDA say "System Menu"

Result this should not happen, was fine using NVDA 2010.1 and Firefox 3.6.9.

**Comment by ehollig** [comment]
I am not able to replicate this, and it is hard to say what the issue is, as there was no log provided.

**Comment by leonardder** [comment]
Facebook has changed multiple times over the years, so has Firefox, and I've never been able to reproduce this. Closing.
