### ISSUE TITLE
In Google Chrome, NVDA does not initially read graphics containing a large amount of alt text

### ISSUE THREAD

**Issue by RD-Brown** [nvaccess/nvda#9500]
When an image contains a large amount of alt text, NVDA does not initially recognize that a graphic is present, and mistakenly announces, “No next graphic,” when G is pressed at the top of the page.  (TestNav, Pearson’s test delivery platform, is used to demonstrate this error inside Google Chrome.)

### Steps to reproduce:
1.	In Chrome, go to link: 
https://uat-gen.testnav.com/client/index.html#login?username=LGN606287323&password=3ZFRFWH7
2.	From the Test Start screen, press “B” until you reach the Start button, and press Enter.
3.	From the Section Start screen, press “B” until you reach the Start button, and press Enter.
4.	From the Question screen, press G, and note that NVDA announces, “No next graphic,” even though a graphic with alt text is present.
5.	Note that if you go to the next item (press B until you reach the Next button, and Press Enter), and then return to the previous item (press B until you reach the Previous button, and press Enter), NVDA will successfully detect and read the graphic when G is pressed.
6.	Items 2 and 4 on this form containing images with small alt text do not exhibit this issue.  Item 3 with large alt text does exhibit the same issue as above.
7.	Please be aware that to continue receiving this error, you must clear browsing data in Google Chrome each time you test this issue.

### Actual behavior:
Graphics containing a large amount of alt text are initially not detected when the page loads.

### Expected behavior:
Graphics containing any size of alt text should always be detected.

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
V2019.1.1

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
Google Chrome V73.0.3683.103

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, V2019.1 and V2018.4.  Same as above.

**Comment by Adriani90** [comment]
Note that when navigating to the introduction, "this is a very big grafic ... etc.", you can also use object navigation to access the grafic.
1. By pressing num 6 on the numblock if the keyboard layout in NVDA's settings is "desktop"
2. Or by pressing nvda+shift+right arrow if the keyboard layout is "laptop".

However, this is anyway a strange behavior, NVDA should detect the grafic initially and not when using object navigation first.

**Comment by Adriani90** [comment]
@RD-Brown the website is not working anymore. could you please try to create a minimal test case or provide another example to reproduce?

**Comment by RD-Brown** [comment]
@Adriani90  the new page is:  https://ref.testnav.com/client/index.html#login?username=LGN331402550&password=S8RZRK3F
In our tests, none of the graphics are recognized by NVDA the first time the item is viewed, but become available on subsequent viewings.

**Comment by Adriani90** [comment]
@RD-Brown thank you for the updated example. Which Chrome version and which NVDA version do you have?
I tested now with Chrome 81 and NVDA alpha-20145,cdd37c72 and I cannot reproduce this issue. For me the graphic is recognized properly right at the beginning, I don't have to press next and previous. Could you test with these versions please?
The last NVDA alpha can be downloaded here:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by RD-Brown** [comment]
@Adriani90 We are conducting further tests on our end, and will advise once we have results.

**Comment by Adriani90** [comment]
@RD-Brown any updates on this? are you still having this issue with NVDA 2023.1 RC1?

**Comment by RD-Brown** [comment]
@Adriani90 We are no longer seeing this issue in NVDA, thank you.
