### ISSUE TITLE
NVDA not honoring the lang attribute

### ISSUE THREAD

**Issue by bourpie** [nvaccess/nvda#9502]
### Steps to reproduce:

On Windows 10 in french, in Chrome or Firefox open a web page which has the page lang attribute set to "en" (&lt;html lang=&quot;en&quot;&gt;)

### Actual behavior:

The voice reads english with a french accent

### Expected behavior:

The voice should read english with an english accent

### System configuration

French Windows 10

#### NVDA version:

2019.1.1

#### Windows version:

French Windows 10

#### Name and version of other software in use when reproducing the issue:

Jaws works fine

#### Other information about your system:

Language set to Français Canada

#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

**Comment by Brian1Gaff** [comment]
What is the synth in use when this happens?
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by DrSooom** [comment]
@bourpie: Please enable "Automatic Language switching" as well as "Automatic Dialect switching" in the Speech NVDA Settings and try again. Note that not all TTS Engines support these options.

**Comment by bourpie** [comment]
@DrSooom: I had both enabled "Automatic Language switching" as well as "Automatic Dialect switching" but it didn't work. It worked when I changed the TTS Engines. Thanks for the tip.
