### ISSUE TITLE
In edit boxes using DisplayModelEditableText space is added in front of each not empty line.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#9503]
### Steps to reproduce:
1. Open  any application using DisplayModelEditableText and write a few lines.
2. Move with up and down arrows and press NVDA+up arrow to spell each of them.
3. move with left and right arrow and compare the results.
### Actual behavior:
When spelling space is presented in front of each line. It is particularly problematic when indentation reporting is used in these editors.
### Expected behavior:
The results obtained when spelling and when using arrows should be identical.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA version alpha-17077,7f274eca

#### Windows version:
Windows 7 x64
#### Name and version of other software in use when reproducing the issue:
Tested In Excel 2010, Becky Internet Mail and Dev-C++
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The same issue is present in 2019.1 and 2018.4.

**Comment by leonardder** [comment]
I guess this can be worked around by subclassing displayModel.EditableTextDisplayModelTextInfo, setting stripOuterWhitespace to True. I'm afraid this can lead to unexpected outcomes though, such as stripping spaces that ought really be there. As we most likely don't want this, this is very unlikely to get fixed at all. I'm tempted to close this as a can't fix (i.e. we really can't make sure what spaces are added erroneously and what spaces are added on purpose). May be @michaeldcurran believes otherwise?

**Comment by DrSooom** [comment]
@leonardder: Maybe a candidate for a new checkbox in the Advanced NVDA Settings? Just a thought.

**Comment by leonardder** [comment]
I'm not a huge fan of that, but it could be debated of course.

**Comment by lukaszgo1** [comment]
If stripOuterWhitespace removes all spaces to the left of the text it would make reporting of indentation even less useful that it is now in these fields. As it always adds one space it looks like a bug in the code rather than some sort of wrong guess, so maybe instead of removing spaces we should try to fix an actual bug. I agree that it isn't top priority.

**Comment by michaelDCurran** [comment]
To my knowledge this cannot be fixed. In displayModels, A 'space' is 
simply the absence of any text. Spaces at the beginning of a line are 
placed there if the first character on the line starts at a positive x 
offset from the edge of the control/window.

Clearly all edit controls start their lines with a small bit of padding. 
But as this displayModel code is somewhat generic, there is no way to 
know  what the size of this padding actually is.

**Comment by Adriani90** [comment]
Closing as cant fix as suggested above.
