### ISSUE TITLE
English User Guide: Additions/Corrections

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#9508]
I've carried out an entire read through of the English User Guide, and noticed the following additions/corrections that I hope may be useful - original text will come first on each line, followed by a ">" symbol and my suggested addition/correction. It's worth noting that this is based on alpha-16944,00a63f0a so I totally understand that several of these may already be fixed.

NVDA is copyright 2006-2018 NVDA contributors. > NVDA is copyright 2006-2019 NVDA contributors.

If you have not yet got a copy of NVDA, you can download it from www.nvaccess.org > If you have not yet got a copy of NVDA, you can download it from https://www.nvaccess.org

If created, this shortcut will also be assigned a shortcut key of control+alt+n, allowing you to start NVDA at any time with this key stroke > If created, this shortcut will also be assigned a shortcut key of control+alt+n, allowing you to start NVDA at any time with this keystroke

Tapping twice will result in a double tap. Tapping 3 times will result in a triple tap > Tapping twice will result in a double-tap. Tapping 3 times will result in a triple-tap

it's possible to have gestures like a 2-finger triple tap, a 4-finger tap, etc > it's possible to have gestures like a 2-finger triple-tap, a 4-finger tap, etc

When you find the key you wish to press, double-tap the key or lift your finger, depending on options chosen from Touch Interaction Settings category of the NVDA Settings > When you find the key you wish to press, double-tap the key or lift your finger, depending on options chosen from the Touch Interaction Settings category of the NVDA Settings

To get to the NVDA menu from anywhere in Windows while NVDA is running, press NVDA+n on the keyboard or perform a 2-finger double tap on the touch screen > To get to the NVDA menu from anywhere in Windows while NVDA is running, press NVDA+n on the keyboard or perform a 2-finger double-tap on the touch screen

NVDA Menu
NVDA+n
NVDA+n
2-finger double tap > NVDA Menu
NVDA+n
NVDA+n
2-finger double-tap

Tells NVDA to pass the next key press straight through to the active application, even if it is normally treated as an NVDA key command > Tells NVDA to pass the next key press straight through to the active application - even if it is normally treated as an NVDA key command

sleep mode disables all NVDA commands and speech/braille output for the current application. This is most useful in applications that provide their own speech or screen reading features. Press this command again to disable sleep mode > sleep mode disables all NVDA commands and speech/braille output for the current application. This is most useful in applications that provide their own speech or screen reading features. Press this command again to disable sleep mode - note that NVDA will only retain Sleep Mode settings until it is restarted

Reports the Text in the clipboard if there is any > Reports the Text on the clipboard if there is any

Note: numpad keys require numlock key to be turned off to work properly > Note: numpad keys require the num lock to be turned off to work properly (two instances)

http://www.dessci.com/en/products/mathplayer/ > https://www.dessci.com/mathplayer

• Design Science MathType in Microsoft Word and PowerPoint. MathType needs to be installed in order for this to work. The trial version is sufficient > • Design Science MathType in Microsoft Word and PowerPoint. MathType needs to be installed in order for this to work. The trial version is sufficient and can be downloaded from https://www.dessci.com/en/products/mathtype/

These settings will be stored in the document as bookmarks compatible with other screen readers such as Jaws > These settings will be stored in the document as bookmarks compatible with other screen readers such as JAWS

These settings will be stored in the workbook as defined name ranges compatible with other screen readers such as Jaws > These settings will be stored in the workbook as defined name ranges compatible with other screen readers such as JAWS

For certain dialogs, you can press Apply button to let the settings take effect immediately without closing the dialog > For certain dialogs, you can press the Apply button to let the settings take effect immediately without closing the dialog

Just like input/output, if you are concerned about privacy, you should not set logging level to this option > Just like input/output, if you are concerned about privacy, you should not set your logging level to this option

If this is enabled, NVDA will automatically check for updated versions of NVDA and inform you when an update is available > If this is enabled, NVDA will automatically check for updated versions and inform you when an update is available

The speech category in the NVDA Settings dialog contains options that lets you change the speech synthesizer as well as voice characteristics for the chosen synthesizer > The speech category in the NVDA Settings dialog contains options that allow you to change the speech synthesizer as well as voice characteristics for the chosen synthesizer

If you are using the Espeak NG synthesizer that is packaged with NVDA, this is a combo box that lets you select the Variant the synthesizer should speak with. ESpeak NG's Variants are rather like voices, as they provide slightly different attributes to the eSpeak NG voice. Some variants will sound like a male, some like a female, and some even like a frog > If you are using the Espeak NG synthesizer that is packaged with NVDA, this is a combo box that lets you select the Variant the synthesizer should speak with. ESpeak NG's Variants are rather like voices, as they provide slightly different attributes to the eSpeak NG voice. Some variants will sound like a male, some like a female, and some even like a frog. If using a third-party synthesizer, you may also be able to change this value if your chosen voice supports it.

This option allows you to change the rate of your voice. This is a slider that goes from 0 to 100, (0 being the slowest, 100 being the fastest) > This option allows you to change the rate of your voice. This is a slider that goes from 0 to 100  - 0 being the slowest, 100 being the fastest

This option allows you to change the pitch of the current voice. It is a slider which goes from 0 to 100, (0 being the lowest pitch and 100 being the highest) > This option allows you to change the pitch of the current voice. It is a slider which goes from 0 to 100 - 0 being the lowest pitch and 100 being the highest.

This option is a slider which goes from 0 to 100, (0 being the lowest volume and 100 being the highest) > This option is a slider which goes from 0 to 100 - 0 being the lowest volume and 100 being the highest.

This option is a slider that lets you choose how much inflection (rise and fall in pitch) the synthesizer should use to speak with. (The only synthesizer that provides this option at the present time is eSpeak NG) > This option is a slider that lets you choose how much inflection (rise and fall in pitch) the synthesizer should use to speak with.

This checkbox allows you to toggle whether NVDA should switch speech synthesizer languages automatically if the text being read specifies its language. This option is enabled by default. Currently only the eSpeak NG synthesizer supports automatic language switching > This checkbox allows you to toggle whether NVDA should switch speech synthesizer languages automatically if the text being read specifies its language. This option is enabled by default.

When this checkbox is enabled, NVDA will include additional symbol pronunciation dictionaries when pronouncing characters and symbols > When this checkbox is checked, NVDA will include additional symbol pronunciation dictionaries when pronouncing characters and symbols

Usually, NVDA raises the pitch slightly for any capital letter, but some synthesizers may not support this well, so perhaps this option may be of use > Usually, NVDA raises the pitch slightly for any capital letter, but some synthesizers may not support this well, so this option may be a preferred alternative for some users.

This option allows you to choose the sound card that NVDA should instruct the selected synthesizer to speak through > This option allows you to choose the audio device that NVDA should instruct the selected synthesizer to speak through

The Keyboard category in the NVDA Settings dialog contains options that sets how NVDA behaves as you use and type on your keyboard > The Keyboard category in the NVDA Settings dialog contains options that set how NVDA behaves as you use and type on your keyboard

The first checkbox lets you control if NVDA should use the capslock as an NVDA modifier key > The first checkbox lets you control if NVDA should use the caps lock as an NVDA modifier key

NVDA can be configured so that the numpad Insert, Extended Insert and/or capslock key can be used > NVDA can be configured so that the numpad Insert, Extended Insert and/or caps lock key can be used

e.g. you wish to turn capslock on when you have set capslock to be an NVDA modifier key > e.g. you wish to turn caps lock on when you have set caps lock to be an NVDA modifier key

The Desktop layout makes heavy use of the numpad (with numlock off) > The Desktop layout makes heavy use of the numpad (with num lock off)

If your laptop cannot do this or does not allow you to turn numlock off > If your laptop cannot do this or does not allow you to turn num lock off

If this is unchecked, you need to double-tap on the touch keyboard key to press the key > If this is unchecked, you need to double-tap on the key on the touch keyboard to press the key

Report Tool Tips > Report Tooltips

A checkbox that when checked tells NVDA to report tool tips as they appear. Many Windows and controls show a small message (or tool tip > A checkbox that when checked tells NVDA to report tooltips as they appear. Many Windows and controls show a small message (or tooltip

Help Balloons are like tool tips > Help Balloons are like tooltips

Uncheck this checkbox if you don't wish to have the description reported along with objects - it may be useful to give an example of a typical description that NVDA may encounter here

For example, when you enter text into the search box in Start menu in Windows Vista and later > For example, when you enter text into the search box in the Start menu in Windows 8 and later

As an example, if enabled, if the letter j was pressed, it would be trapped from reaching the document, even though it is not a quick navigation command nor is it likely to be a command in the application itself > As an example, if enabled, if the letter j was pressed, it would be trapped from reaching the document, even though it is not a quick navigation command nor is it likely to be a command in the application itself. If enabled, NVDA will tell Windows to play a default sound whenever a key is pressed that gets trapped.

When this option is enabled, NVDA will try to use the Microsoft UI Automation accessibility api in order to fetch information from Microsoft Word document controls > When this option is enabled, NVDA will try to use the Microsoft UI Automation accessibility API in order to fetch information from Microsoft Word document controls

Section 11.3 - we may wish to remove the laptop key assignments; they match their desktop counterparts

If the add-on was previously "enabled", a status will show "disabled after restart" Just like when you install or remove add-ons, you need to restart NVDA in order for changes to take effect > If the add-on was previously "enabled", the status will show "disabled after restart" - just like when you install or remove add-ons, you need to restart NVDA in order for changes to take effect

The Incompatible Add-ons Manager, which can be accessed via the "view incompatible add-ons" buttons in the Add-on manager > The Incompatible Add-ons Manager, which can be accessed via the "view incompatible add-ons" button in the Add-on manager

The Incompatible add-ons manager also has an "About add-on..." button. This opens will let you know the full details of the add-on, which is helpful when contacting the add-on author > The Incompatible add-ons manager also has an "About add-on..." button. This screen will let you know the full details of the add-on, which is helpful when contacting the add-on author

Please see extra voices page > please see the extra voices page

http://www.microsoft.com/download/en/details.aspx?id=27225 > https://www.microsoft.com/download/en/details.aspx?id=27225

http://www.microsoft.com/download/en/details.aspx?id=27224 > https://www.microsoft.com/download/en/details.aspx?id=27224

Quit already running copy of NVDA > Quit an already running copy of NVDA

Quit already running copy of NVDA and start this one > Quit an already running copy of NVDA and start this one

http://www.nvaccess.org/ > https://www.nvaccess.org/

**Comment by DrSooom** [comment]
See also issue #8689

**Comment by Adriani90** [comment]
#9730 will solve this issue. I decided to let 11.3 as part of the user guide because otherwise new users would think they must assign laptop keys themselves and I want to avoid confusions.
