### ISSUE TITLE
Windows 8: Drop Support for anything Less than Windows 8.1

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#9510]
As of 12/01/2016, Microsoft no longer support the original RTM version of Windows 8; devices must be running Windows 8.1 to continue receiving updates. To ensure that we are only supporting OSs that are continuing to receive support and to encourage users to stay up-to-date with security fixes, it may be worth considering dropping Windows 8 support.

If people think that this may be worth it, a good starting point would be to get an idea of how many users are still using NVDA with the original build of Win 8 - is there any way that we can get stats for this, based on update checks?

**Comment by lukaszgo1** [comment]
Would this bring any actual benefit for users? In my opinion it would not. Furthermore Windows Server 2012 is still supported and it also is Windows 6.2.

**Comment by leonardder** [comment]
There is no benefit in dropping Windows 8 support while keeping support for Windows 7. Even after official support for windows 7 will be dropped, I believe it will still be possible to buy extended support from Microsoft. Furthermore, Lukas has a valid point concerning Windows Server 2012.

I'm closing this as won't fix.

**Comment by Adriani90** [comment]
Note also that institutions and companies are applying updates much later than private users. Dripping support for older applications too early would impact users in a very negative way.
