### ISSUE TITLE
Mail app for Windows 10: bug inside ordered lists

### ISSUE THREAD

**Issue by DataTriny** [nvaccess/nvda#9529]
### Steps to reproduce:

1. Open NVDA,
2. Open Mail app for Windows 10,
3. Start reading a mail that contains an ordered list, (i.e. the one you are currently reading on this page),
4. Navigate between the items using up and down arrow key for instance.

### Actual behavior:

NVDA reports the index of the item following by its content and finally the index of the next one.

### Expected behavior:

NVDA should not report the index of the next item when dealing with the current one.

#### NVDA installed/portable/running from source:

NVDA installed, portable and running from source.

#### NVDA version:

NVDA 2019.1.1.

#### Windows version:

Windows 10 Education, version 1809.

#### Name and version of other software in use when reproducing the issue:

Mail app for Windows 10, version 16005.11425.20190.0.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

I got the same result using a portable copy of NVDA version 2018.4.1. However, I am pretty sure this behavior is quite recent. Maybe a change in the app itself?

**Comment by leonardder** [comment]
I Recall seeing something like this in Word as well.

**Comment by Adriani90** [comment]
@Carlos-EstebanM, @Aleskis, @gauravahir28, @alexandretoco Windows mail should work again in NVDA last alpha. Can you also test if this issue is still occuring with NVDA last alpha version? The alpha versions can be downloaded from following link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Aleskis** [comment]
Thank you. Works great !

**Comment by Adriani90** [comment]
Thanks for the update, closing as works for me.
