### ISSUE TITLE
NVDA pronouncing currency symbol before amount

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#953]
**Reported by dharvey on 2010-10-01 10:12**
Just reporting this bug

For some reason eSpeak announces the currency $10.00 the dollar sign is announced before the amount it should be announced as 100 dollars, same as $1.00 should be 1 dollar.  For amounts under $1.00 cents should be taken into account E.G. $0.50 should be announced as 50 cents.

Other currencies should be taken into account E.G. USD, CAD, AUD, pounds, Euros.

**Comment by leonardder** [comment]
@JCSTeh: Is your opinion about this still the same?

cc @Brian1Gaff

**Comment by jcsteh** [comment]
Yes. I might be happy to consider a contributed implementation for this, but it'd need to be configurable (disabled by default) and work for multiple languages. It's certainly not something we (NV Access) will work on.

**Comment by fisher729** [comment]
As this is a synthesizer specific issue, can it therefore be closed? Using synths such as Eloquence, Vocalizer Expressive and Windows OneCore Voices, I do not experience this. It's something the eSpeak NG team needs to work on, in my view.

**Comment by Adriani90** [comment]
I agree this is synthesizer specific and must be reported there accordingly. @dharvey it works with almost every synthesizer apart from eSpeak. Feel free to report this issue to eSpeak on Github. I am closing this one for now but if there are any other arguments we can reopen it ofcourse.
