### ISSUE TITLE
update espeak

### ISSUE THREAD

**Issue by hozosch** [nvaccess/nvda#9532]
Hello,
I'm removing this template because all I would like is to have espeak updated in 2019.2. There are some Pronunciation fixes and modifications to the German voice and the m8 variant I did.
Thanks advancely.

**Comment by zstanecic** [comment]
Hi @hozosch,

This thing is a bit risky...

It should be tested ina a try build, before straightforward updating. 

Do you remember the time, when the espeak was updated to the latest version?

**Comment by DrSooom** [comment]
eSpeak NG 1.49.2 is part of NVDA since 2017.4. eSpeak NG 1.49.3 seems to be still in development based on the [changelog](https://github.com/espeak-ng/espeak-ng/blob/master/CHANGELOG.md) (master branch).
@hozosch: Please update/specify the issue title. Thanks.

**Comment by hozosch** [comment]
Sorry people, it seems that my imaginations how German espeak should sound don't agree with those of others. Thanks for doing it anyway now. I'll close this issue.
