### ISSUE TITLE
When typing, always keep the raille cursor at the end of the line to show as much as the context possible

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/nvda#9536]
Filed on behalf of a @babbagecom customer.

### Is your feature request related to a problem? Please describe.
When typing text and using braille, the braille display scrolls to a new line when the caret reaches the end of a raille display. While this makes sense, it requires you to scroll back if the caret just bounced to the start of the next Braille line.

### Describe the solution you'd like
Rather than scrolling the entire display forward to the next line, it is proposed that with every new character that is added to the end of a line, the braille display sscrolls forward only one character. This ensures that:

1. When typing at the end of a line, the cursor is always positioned at the end of the braille display and therefore easy to find.
2. Space on the braille display is used more efficiently.

**Comment by DrSooom** [comment]
Yes, but as an option. If the text on a braille displayed is scrolling/updating during typing with 400 hits/Min., the braille display will make quite a lot of unwanted noise. (I really, really hate this when I'm typing within a line too add something.)
Furthermore you also have to think about word wrapping. Should it be okay if only a part of a word is displayed on the left side on the braille display – just to keep the cursor at the last braille cell all the time?

**Comment by josephsl** [comment]
Hi,

Five years later...

Any other thoughts about this proposal?

Thanks.

**Comment by michaelDCurran** [comment]
@LeonarddeR I'm going to close this for now. However, if you still believe this worthy of consideration, please reopen and adress the thoughts from @DrSooom
