### ISSUE TITLE
Support <article> elements

### ISSUE THREAD

**Issue by Dan503** [nvaccess/nvda#9537]
I am using the latest version of NVDA (2019.1.1).

It does not announce `<article>` elements when encountered or read their associated label.

`<article>` elements should basically be treated the same way as `<section>` elements except they are announced as "article" rather than "region".

**Comment by Adriani90** [comment]
This is highly related to #9227 and is implicitly part of that issue. So let's continue the discussion in #9227. Thanks. I am closing this for now.
