### ISSUE TITLE
Preprocess ligatures before sending to the synthesizer

### ISSUE THREAD

**Issue by ctoth** [nvaccess/nvda#9538]
### Is your feature request related to a problem? Please describe.

In the Chrome PDF reader, and other applications which display PDF content or content pasted from a PDF, ligatures are passed through to the synthesizer as Unicode characters. 
This often results in artifacts such as the characters 'fi' being skipped when reading.

### Describe the solution you'd like

We should create a mapping of Ligatures and substitute them in before passing them along.
We can optionally hide this behind an option, defaulting to on, or allow synthesizers to declare their support for ligature characters, as ESpeak, for instance, supports them by default.

### Describe alternatives you've considered

Opening a bug with PDFium but this won't help with websites which copy and paste PDF content directly.

**Comment by leonardder** [comment]
Would you be able to provide an example PDF document where this happens?

**Comment by Adriani90** [comment]
@ctoth without a test document it will be really hard to develop something. Just a reminder. Please provide a test document.

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author on this issue for a very long time. I am closing as abandoned.
