### ISSUE TITLE
UIA in Word: When document ends with a heading, the heading is duplicated in quick nav

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9540]
### Steps to reproduce:
1. Open MS Word
2. Create a single line and make it a heading with ctrl+alt+1/3
3. Enable browse mode
4. Press H multiple times.

### Actual behavior:
NVDA keeps reporting the heading. When opening the elements list, NVDA shows the heading twice.

### Expected behavior:
NVDA reports "no next heading". Only one heading is shown in the elements list.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-17134

#### Windows version:
Windows 10 1903 uild 18362.86

#### Name and version of other software in use when reproducing the issue:
Word 365 16.0.11601.20144

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by Brian1Gaff** [comment]
Is this the same issue that sometimes results in the line above being read a 
couple of times when you press enter to get a new line in older versions of 
Word. Its not too annoying but it sounds like slow removal of what nvda has 
buffered.

 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----
