### ISSUE TITLE
NVDA reports nested layout tables when reading HTML message in Outlook 

### ISSUE THREAD

**Issue by TommasoNonis90** [nvaccess/nvda#9541]
### Steps to reproduce:
- Open Outlook 2016 / 365
- Open any HTML based newsletter

### Actual behavior:
NVDA speaks 'all tables, most consisting of 1 row and 1 column, exclusively used for layout / responsiveness purposes. In other email clients such as thunderbird, where it uses its virtual buffer to display HTML emails, everything works seamlessly.

### Expected behavior:
NVDA should act as similarly as possible to how it would in real HTML content. I think it would be  great if these HTML messages could be virtualized, without relying on the very problematic word display.

#### NVDA installed/portable/running from source:
Installed
#### Windows version:
Version	10.0.17763 build 17763

#### Name and version of other software in use when reproducing the issue:
Outlook Version 1905 (build 11629.20008 
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, it works the same as far as 2017.1

**Comment by Qchristensen** [comment]
A couple of additional notes from the user:

"I’ve performed a few other tests, and was able to discover that if you disengage UI automation in word document controls, you do not hear tables spoken out loud unless they really are data tables.

However, this comes at a price: the down arrow navigates all these layout tables cell by cell, therefore you hear a great number of blank lines, which are in fact blank cells.


I have found that a partial solution is to turn off the reading of all tables as a configuration profile in outlook.

However, this has two side effects:

Sacrificing table announcement for *real* tables, those that do contain data
Best

Blank lines still remain aplenty, as the arrow keys still seem to go all across layout tables even though they are not announced."

**Comment by Adriani90** [comment]
yes we have discussed this topic on NVDACon in detail. I also experience this in web based netviewer apps in internet explorer (i.e. SAP CRM). It is exactly the same behavior. Actually this is very annoying especially if you work with such documents and panes every day.
It seems NVDA recognizes data tables and layout tables and reports them together as nested tables. It can not really distinguish which is the layout table. But this is just an idea.
cc: @leonardder, @michaelDCurran, @jcsteh, @feerrenrut maybe you have more experience with this behavior?

**Comment by Adriani90** [comment]
This has been fixed in PR #12857. I close this issue now as fixed.
