### ISSUE TITLE
Screen reader is narrating all video controls together when user hit tab after close button - Lightbox

### ISSUE THREAD

**Issue by Amanullah0123** [nvaccess/nvda#9547]
User Experience:
User who rely on screen reader if any object information is not narrated by screen reader user will confuse.

Test Environment:
OS: Windows 10 version: 10.0.17763 Build 17763
Browser: chrome - Version 74.0.3729.131 (Official Build) (64-bit)
Screen reader - NVDA - version 2018.4.1
URL: https://www.microsoft.com/en-us/hololens#

Repro Steps:
Step 1: Open the above URL using any browser.
Step 2: Navigate to section “OneGDCWeb-Feature-v4img9a” and press tab to select the play button and enter on it.
Step 3: Hit tab to go on pause button after close button
Step 4: Verify focus move to play/pause and narrate about play pause only

Actual: 
1. NVDA narrate all controls in one go.
![video issue](https://user-images.githubusercontent.com/47437302/57322891-7a063a80-70b9-11e9-97ac-761182c7fd7a.png)

**Comment by DrSooom** [comment]
@Amanullah0123: Please specify the version of Windows 10, Google Chrome and NVDA in the issue description. Thanks.

**Comment by Adriani90** [comment]
This is not repoducible with NVDA 2023.2 RC on Firefox, Chrome or Edge 116. I am closing as works for me. If you are still having this issue, please comment and we can reopen.
