### ISSUE TITLE
Remove deprecated functionality

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9548]
### Is your feature request related to a problem? Please describe.
The introduction of Python 3 and SPeech Refactor will introduce backwards incompatible changes.

### Describe the solution you'd like
As one of the goals is to bundle all backwards incompatible changes as much as possible, I propose removing all functionality that is considered deprecated. This includes:

* Directly importing validate instead of configobj.validate
* textInfos.Point and textInfos.Rect should utilize locationHelper instead
* braille.BrailleHandler._get/set_tether
* config.getConfigDirs
* config.ConfigManager.getConfigValidationParameter
* inputCore.InputGesture.logIdentifier property
* synthDriverHandler.SynthDriver.speakText/speakCharacter, when they survives speech refactor

### Describe alternatives you've considered
Just leave the code as is.

**Comment by Brian1Gaff** [comment]
I assume this is what the threshold snap  branch is for?
 At the current time it seems to be still working on most of my add ons and 
legacy app modules that are important like older versions of word and 
Outlook Express/live mail which is in use by many people either by the patch 
or whatever for later windows versions.

Other than that the main add ons I see affected if I read this right will be 
the 3D sound, the and  the speech player in Espeak add ons and no doubt 
other speech synths and sound generating  add ons.


It will be interesting to see which fail if the manifest is adjusted to let 
those add ons run.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by josephsl** [comment]
Hi, we might as well remove app modules that are no longer relevant – I know there will be at least one protester, but some app modules are no longer relevant, especially after dropping support for anything earlier than Windows 7 SP1. Thanks.

**Comment by josephsl** [comment]
Hi, more importantly, any add-on not ready for Python 3 will fail, which won’t be resolved by just editing the manifest. Thanks.

**Comment by Brian1Gaff** [comment]
Yes that was my point really, at least we will know then!

I'm a little worried that otherwise come the big switch over a whole raft of 
people will find nvda worse, not because it is worse, but because add ons 
they had forgotten about will be turned off by default.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by lukaszgo1** [comment]
@josephsl  wrote: 
> 
> Hi, we might as well remove app modules that are no longer relevant – I know there will be at least one protester, but some app modules are no longer relevant, especially after dropping support for anything earlier than Windows 7 SP1. 




I've looked through all appModules and only candidate for removal seems to be sndrec32 which is present only in Windows XP.
At first I've found 2 more  possible and decided to research further
1. Module for Outlook Express-  this one is still used even in Windows 10 
2. Module for MSN Messenger - while it officially is EOL there is still a patch allowing it to work and a server to which you can connect with it.

To make myself clear I am not saying that these modules should be improved in any way but we shoudl simply keep the as is. There is no point in removing functionality. The Python 3 and speeech refactor would put off enough user as is and we should do everything possible not to make last Python 2 NVDA version the next Windows XP.

**Comment by leonardder** [comment]
How about the following appModules? 

* aim
* teamtalk3 
* teamtalk4classic
* Klango

**Comment by dingpengyu** [comment]
How about the following Modules?
txt2tags
Reason for deletion:
The current txt2tags official has not been updated for a long time.
Alternatives:
You can use the markdown, or poedit plus markdown to translate the user guide and update the log.
thank

**Comment by josephsl** [comment]
Hi, I advise against removing t2t at the moment. Although we did discuss this in another issue, it is a bit risky to remove it at this stage until we think hard on a better solution. @LeonardDer, any thoughts on this one? Thanks.

**Comment by dingpengyu** [comment]
hello leonardder
I have two ideas
The first is to use python official to first convert the user guide and log into sphinx and then generate the .po file. At this time, the translator can use the poedit editor to translate the specific syntax. You don't need to export the .html file. Use the poedit editor to export to HTML functionality
The second idea is to use poedit plus markdown to manage the translation. First, convert the user guide and update log to the markdown. Then, when converting the markdown to the .po file, the translator directly translates it directly with the poedit editor. If you want to generate a web page, you can use the poedit editor to export to HTML.
thank

**Comment by leonardder** [comment]
I started working on this on my deprecate branch.

**Comment by josephsl** [comment]
Hi,

I'll work on code consistency edits (winUser.FindWindow -> findWindow, for example), destined for a separate issue.

Thanks.

**Comment by Adriani90** [comment]
@leonardder now that the PR above has been merged. Is this issue fixed? Or is there any further work to be done?

**Comment by leonardder** [comment]
Fixed in #9603
