### ISSUE TITLE
Impossible to focus popup created by Tampermonkey in Firefox Nightly

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#9552]
### Steps to reproduce:
1. Open Firefox
2. Install extension Tampermonkey if not already installed.
3. Move to address bar with CTRL+L press tab to move to the toolbar and with arrow keys locate button for Tampermonkey.
4. Press it with enter.
### Actual behavior:
Firefox Nightly frame read-only is reported, and it is required to alt+tab from Nightly to interact with browser again. The newly opened window from Tampermonkey can only be accessed with object navigation.
### Expected behavior:
The window from Tampermonkey should get focus, and it should be possible to interact with it.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA version alpha-17197,5d56962f

#### Windows version:
Windows 7 X64
#### Name and version of other software in use when reproducing the issue:
Nightly 68.0a1 (2019-05-09) (64-bit)
Tampermonkey version 4.7.5788
#### Other information about your system:
1. I've tried with clean profile for Firefox - no difference.
2. When performing these steps with JAWS document created by Tampermonkey properly gets focus.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No I haven't

cc @jcsteh @MarcoZehe

**Comment by jcsteh** [comment]
I can't reproduce this. When I press space/enter on the Tampermonkey button, the Tampermonkey "document" gets focus and NVDA goes into browse mode. That said, I think I've seen this behaviour before, and [Mozilla bug 1523034](https://bugzilla.mozilla.org/show_bug.cgi?id=1523034) suggests you're not the only person seeing this on a regular basis.

When this occurs, are you able to focus the popup by pressing f6? You may need to press it a few times.

**Comment by lukaszgo1** [comment]
No matter how many times I press F6 Tampermonkeys popup nevver gets focus.

**Comment by jcsteh** [comment]
I've been able to reproduce this intermittently and I tracked down the cause. I filed a separate Mozilla bug for this issue on Windows, since the original bug is about Linux and the issue on Windows is in Windows specific code. See https://bugzilla.mozilla.org/show_bug.cgi?id=1570848 .

**Comment by jcsteh** [comment]
Fixed for Firefox 70 (available now in Firefox Nightly).
