### ISSUE TITLE
Does Page reloading on selection of any control is accessibility issue?

### ISSUE THREAD

**Issue by Amanullah0123** [nvaccess/nvda#9554]

**Comment by josephsl** [comment]
Hi there, sorry for a really badly formatted response, but it appears there’s no water inside this container (i.e. template info, that’s it, no content or clarifications). Sorry.

**Comment by DrSooom** [comment]
@Amanullah0123: Please open this issue on the GitHub website and choose the button "Show options" to edit the issue description, which currently only contains the bug report draft. If you just wanted to ask something, maybe the [mailing lists](https://github.com/nvaccess/nvda-community/wiki/Connect) could be the right place for it. But if you wanted to report a bug, please completely fill out the bug report draft by editing it. Thanks.

**Comment by Amanullah0123** [comment]
it was a question not an issue

**Comment by Adriani90** [comment]
@Amanullah0123 for questions like this one, the community is very keen to help you on this on Gitter. Please feel free to raise your questions in the messaging area for NVDA here:
https://gitter.im/nvaccess/NVDA
