### ISSUE TITLE
NVDA does not save One core voices settings with Rate boost on

### ISSUE THREAD

**Issue by mariopercinic** [nvaccess/nvda#9558]
With new rate boost option introduced in the newest Alpha releases NVDA is not able to save the configuration for One core voices while the rateboost is on. When changes for rate and pitch are made for One core voices, it is possible to save the settings, but after restarting NVDA or after switching to another synth and going back to One core voices, the settings go to their default values. However if rate boost for One core voices is turned off, than all the settings are saved and reloaded correctly.
It is happening on Windows 10 1809 with the last Alpha release alpha-17205,93ccd518

**Comment by leonardder** [comment]
I can't reproduce this for changing the pitch, but for rate, I certainly can. I will dive into this.
