### ISSUE TITLE
Say all does not scroll consistently in word365 with UIA enabled

### ISSUE THREAD

**Issue by burakyuksek** [nvaccess/nvda#9559]
### Steps to reproduce:
1. Open a document in word365
2. Perform say all
3. Stop speech with ctrl
4. Navigate with arrows and you will see that the currsor is not where say all stopped. It is either at the start of the document or somewhat above where it is supposed to be.
### Actual behavior:
When say all is stopped with ctrl the currsor is not at the position where speech has stopped.
### Expected behavior:
The currsor is at the position where speech has stopped
### System configuration
windows7 32-bit with office365 professional plus
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.1.1
#### Windows version:
7
#### Name and version of other software in use when reproducing the issue:
Office365 professional plus
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by Brian1Gaff** [comment]
Are you sure this is definitely only with that version of word and uia?
 I've had similar issues with word doing odd things for many years in many 
versions myself.
 One of the most annoying is that it seems not to be able to get to page 2 
sometimes unless the page is zoomed to stop side by side display.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by burakyuksek** [comment]
I am not very sure but I was previously using word 2010 starter and don't remember encountering such inconsistencies.

Brian Gaff <notifications@github.com> şunları yazdı (12 May 2019 10:26):

**Comment by enessaribas** [comment]
Hi,
I can also consistently reproduce this. The curser appears not to follow say all.
Moreover, when in browse mode and review mode,  when switching between modes, the possition of the curser is not retained.

**Comment by Adriani90** [comment]
We didn't hear any updates upo request from the people who reproduced this since more than 5 years. I am closing as abandoned. if you are still having this issue with NVDA 2024.2, please comment and we can reopen.
