### ISSUE TITLE
after starting, nvda alpha-17205,93ccd518 reports errors and does not process its commands

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#9561]
In last alpha (17205... - fryday snapshot) nvda reports errors and does not process its keyboard commands. It happened when I tried to update from tuesday's snaphot (alpha-17162,2f60bc16). If I tried to run clean setup without any changes or installed addons directly from the snapshots page, it works fine

### Steps to reproduce:

- run tuesday snapshot
- make some changes like create a profile and install some addons
- try to update

### Actual behavior:

many error sounds and NVDA does not process its commands like nvda+f12 script for say time. and it happens also when trying with addons disabled after restart.

### Expected behavior:

normal startup, so I could work smoothly.

#### NVDA installed/portable/running from source:

installed and portable

#### NVDA version:

alpha-17205,93ccd518 (not tested earlier fryday and thursday snapshot yet)

#### Windows version:

Windows version: Windows 10Ver1809 (64-bit) build 17763.475

#### Name and version of other software in use when reproducing the issue:

n/a

#### Does the issue still occur after restarting your PC?

yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

yes. last tested snapshot, which works fine, is alpha-17162,2f60bc16

### NVDA Logs:

[NVDA DNEVNIKI.zip](https://github.com/nvaccess/nvda/files/3170652/NVDA.DNEVNIKI.zip)

**Comment by josephsl** [comment]
Hi, yet another instance of Unicode to bytes conversion problem. CC @LeonardDer
