### ISSUE TITLE
Spelling error in whats new on all snapshot branches

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#9563]
### Steps to reproduce:
Launch any nvda snapshot from alpha, beta or threshhold branches  
go to help and whats new and open it. Scroll down to bug fixes for 2019.2
### Actual behavior:
There is a spelling error in the item. as follows
• In Scintilla controls such as Noteplad++, NVDA can read the correct line when wordwrap is enabled. (#9424) 
### Expected behavior:
The l in notepad should not be there.
### System configurationWindows 7 Pro. NVDA any snapshot dated immediately prior to 13th May 2019.
I am using Waterfox as default browser to open the help pages from the nvda menu item.
Rest of template not applicable.

**Comment by feerrenrut** [comment]
Fixed with https://github.com/nvaccess/nvda/commit/bbc3a586022d44213ecab328c8dadeb38eef17cb
