### ISSUE TITLE
Google Chrome: Error in focusable table cells spanning multiple rows or columns

### ISSUE THREAD

**Issue by JulienCochuyt** [nvaccess/nvda#9566]
### Steps to reproduce:

In Google Chrome, browse to a table cell spanning two rows or columns with a focusable element within.
Then hit NVDA+pavnum8 (or NVDA+shift+up in laptop configuration) to navigate to the parent object.

#### Example

````html5
<table>
  <tr>
    <th>A</th>
    <th>B</th>
  </tr>
  <tr>
    <td colspan="2"><a href="">some link</a></td>
  </tr>
</table>

````
### Actual behavior:
NVDA does not say anything.
Log shows the following error:
```
ERROR - scriptHandler.executeScript (15:38:47.420):
error executing script: <bound method GlobalCommands.script_navigatorObject_parent of <globalCommands.GlobalCommands object at 0x04D9D3B0>> with gesture u'majuscule+NVDA+fl\xe8che haut'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "globalCommands.pyo", line 871, in script_navigatorObject_parent
  File "speech.pyo", line 403, in speakObject
  File "speech.pyo", line 337, in speakObjectProperties
  File "speech.pyo", line 1106, in getSpeechTextForProperties
TypeError: coercing to Unicode: need string or buffer, int found
```

### Expected behavior:
NVDA should review the line containing the cell.

#### NVDA installed/portable/running from source:
All of the above.

#### NVDA version:
2019.1.1

#### Windows version:
Windows 10 Professional 64 bits 1804 / 17763.475

#### Name and version of other software in use when reproducing the issue:
Google Chrome 74.0.3729

#### Does the issue still occur after restarting your PC?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The faulty scenario presented here is reproducible since 2018.2rc1 as of 91a0d231f8.

### Rationale
I first discovered this issue while browsing a corporate web application I do not have access to anymore. There, the symptoms were revealing themselves using regular browse-mode navigation triggering a `gainFocus` event. I could not test-reproduce this behavior with 100% occurrence, hence the object-navigation approach reported here.

The root cause is `IA2Attributes["colindex"]` being a string, not an int as other properties related to cell coordinates.
This dates back to 2017.3rc1, probably introduced by 393b55b305.
An easy fix (PR on the way) is to parse the string to an int in `IAccessible._get_{column|row}Number`.
A more thorough one would be to return an int in the first place from the C implementation.

**Comment by leonardder** [comment]
Have you tested this with latest Alpha as well? That version contains a 
fix for errors related to tables in Chrome and Firefox.

**Comment by JulienCochuyt** [comment]
Great news, thanks, I will test it.
Can I access to an official build somewhere or should I build it myself?

**Comment by leonardder** [comment]
Sure. Just take the most recent Alpha snapshot from [here](https://www.nvaccess.org/files/nvda/snapshots/)

**Comment by JulienCochuyt** [comment]
This issue is fixed.
It cannot be reproduced anymore using latest alpha build as of c20a5032.

Thanks a lot!
