### ISSUE TITLE
Cant load OneCore voices with latest threshold snapshot 

### ISSUE THREAD

**Issue by jakubl7545** [nvaccess/nvda#9567]
### Steps to reproduce:
Run latest threshold snapshot
press NVDA+ctrl+s to open select synthesiser dialog
### Actual behavior:
An error is produced and OneCore isn't in the synths list
ERROR - synthDriverHandler.getSynthList (17:10:57.437):
Error while importing SynthDriver oneCore
Traceback (most recent call last):
  File "synthDriverHandler.pyc", line 52, in getSynthList
  File "synthDriverHandler.pyc", line 42, in _getSynthDriver
  File "importlib\__init__.pyc", line 37, in import_module
  File "synthDrivers\oneCore.pyc", line 85, in <module>
  File "baseObject.pyc", line 73, in __init__
TypeError: supportedSettings is already a class attribute, cannot create descriptor with methods <function _get_supportedSettings at 0x041858F0>
### Expected behavior:
Synths list should load with OneCore in it
#### NVDA installed/portable/running from source:
tested with both installed and portable
#### NVDA version:
threshold-17244,129f7a6c
#### Windows version:
windows 10 1809 and 1803
#### Name and version of other software in use when reproducing the issue:
none
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Latest alpha snapshot works correctly.

**Comment by leonardder** [comment]
This seems to be a merge conflict oversight from @michaeldcurran, or something else went wrong here.

Having said that, while we really encourage active testing of the threshold branch, we'd appreciate it if you could be reluctant opening issues for Threshold. This branch is in active development and it has the focus of many people, including NV Access and other members of the NVDA Council. Therefore, it is pretty likely that major issues like this one are fixed on the next business day. If not, it might be better to check the [NVDA development mailing list](https://groups.io/g/nvda-devel) before filing an issue here. This saves you the burden of checking github and filing an issue there, and it saves us the need to reply on an issue and close it afterwards. Thanks in advantage for the understanding.

**Comment by Adriani90** [comment]
Having said that by @leonardder, I am closing this one for now. Please report this issue to NV Access directly or via the development mail list. Once the threshold branche becomes stable, you can create issues on Github. Thanks.
