### ISSUE TITLE
The word "imagines" is mispronounced with lang"en"

### ISSUE THREAD

**Issue by kenya612** [nvaccess/nvda#9569]
### Steps to reproduce:
1. Load NVDA 2019.1.1 in Windows 10
2. Load the attached file that contains the words "imagines" and "imagine" in any browser - Chrome Version 74.0.3729.131 (Official Build) (64-bit) or Firefox Developer Edition 68.0b1 (64-bit)

### Actual behavior:

The word "imagines" is pronounced im-ay-gin-ees.

### Expected behavior:

The word "imagines" is pronounced im-a-gins.

#### NVDA installed/portable/running from source:
Windows 10 Pro (64-bit)

#### NVDA version:
NVDA 2019.1.1 - factory default configuration
Windows OneCore voices
Microsoft David

#### Windows version:
Windows 10 Pro (64-bit)

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Different synthesizer pronounces "imagines" correctly. 
NVDA v 2019.1.1
Synthesizer eSpeak NG
English Great Britain

[NVDA_Mispronounce_Bug_May15_2019.pdf](https://github.com/nvaccess/nvda/files/3184023/NVDA_Mispronounce_Bug_May15_2019.pdf)

**Comment by josephsl** [comment]
Hi, have you reported this problem to Microsoft yet? I recommend doing so somehow because this might be a synthesizer issue rather than NVDA. Thanks.

**Comment by kenya612** [comment]
I haven’t, but I will. Thank you for the suggestion. Much appreciated.

**Comment by Adriani90** [comment]
This is definitely a synthesizer issue and is not related to NVDA. Closing. Please report this to Microsoft.
