### ISSUE TITLE
scons/devDocs: "iteration over non-sequence" error shown since introduction of abc.abstractmethod

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9573]
Hi,

Traced with git bisect to PR #8393:

### Steps to reproduce:
1. Open Command Prompt.
2. Switch to NVDA source code directory.
3. Run scons devDocs.

### Actual behavior:
Epydoc says "iteration over non-sequence".

### Expected behavior:
API docs are generated.

#### NVDA installed/portable/running from source:
Source

#### NVDA version:
Alpha.17248

#### Windows version:
Windows 10 Version 1903

#### Name and version of other software in use when reproducing the issue:
N/A

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2018.4 source

**Comment by DrSooom** [comment]
@josephsl: Any changes between NVDA 2018.4 and Alpha 17248? Or is the behavior the same?

**Comment by josephsl** [comment]
Hi, 2018.4 can build API docs via Epydoc, whereas since that commit, it can’t. Thanks.

**Comment by Adriani90** [comment]
cc: @feerrenrut, @michaelDCurran

**Comment by leonardder** [comment]
cc @derekriemer 

It might be best to revisit this when further on in the Python 3 transition.

**Comment by leonardder** [comment]
I'm closing this as won't fix, as we abandoned epydoc.
