### ISSUE TITLE
Switching profile command message is too verbose

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#9582]
Currently, when switching profiles the following message is used: `"Configuration profile {profile} manually activated`

> the switching message is a bit verbose.

To keep the result of the action clear, we want to explain that the profile has changed, however the name of the configuration profile should come first. An experienced user can then silence their synth.

Instead change the messages to `{profile} profile activated` and `{name} profile deactivated`

_Original comment posted by @feerrenrut in https://github.com/nvaccess/nvda/issues/4209#issuecomment-493110392_

Please see https://github.com/nvaccess/nvda/pull/8844/files#diff-bfbff34784dbac78b7764a877cad793dR2455 for the location of the required change.

**Comment by DrSooom** [comment]
As these messages are only raised after pressing their responsible command's hotkey, "{profile} activated" and "{profile} deactivated" could be enough too. Any thoughts?

Furthermore in my opinion there are a few more too verbose speech/braille feedbacks (e.g. NumLock, CapsLock and ScrollLock messages).

**Comment by Brian1Gaff** [comment]
I have no issue with those, as has been said, one can just silence the thing 
in the middle if one is in such a hurry.

And I'd still like to see the copy paste etc spoken  by default. all other 
screenreaders do this, and if this were made optional it would benice  for 
thos who don't want it.
 Its silly having an add on to do this.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by leonardder** [comment]
As the author of this feature, I agree with this request.

**Comment by feerrenrut** [comment]
> "{profile} activated" and "{profile} deactivated" could be enough too. Any thoughts?

I think this might be boarding on too little information, for instance it might be spoken as "web activated" or similar, which will likely cause confusion to someone who didn't expect it (or forgot about the shortcut). Whereas "web profile activated" gives that extra context to understand what has happened.
