### ISSUE TITLE
Add an option to use up and down arrow to navigate paragraphs by default

### ISSUE THREAD

**Issue by Fatihyuksek** [nvaccess/nvda#9584]
### Is your feature request related to a problem? Please describe.
I want to navigate by paragraphs in web pages with up and down arrows instead of using ctrl+up and down arrows
### Describe the solution you'd like
Add an option that enables navigating by paragraphs instead of lines when you press the up and down arrow keys
### Describe alternatives you've considered
none
### Additional context
I don't want to use this feature in word docuemnts, I only want this feature to be available in browse mode, in web browsers.

**Comment by DrSooom** [comment]
This will lead into inconsistence behavior in navigation. Could you tell us some reasons why this counter-rotating navigation feature should be implemented? Currently I only can see one: motoric limitations.

**Comment by Fatihyuksek** [comment]
Hello,
I want to read more fluently while using the arrow keys. The lines are too short. Narrator in windows 10 works like this and it is not inconsistent

iPhone’umdan gönderildi

Daniel Mayr <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (18 May 2019 17:57):


This will lead into inconsistence behavior in navigation. Could you tell us some reasons why this counter-rotating navigation feature should be implemented? Currently I only can see one: motoric limitations.

**Comment by leonardder** [comment]
1. As @DrSooom pointed out, this will lead into inconsistent behavior in navigation
2. As a workaround, you can increase the "maximum number of characters on one line" option in the browse mode settings category of NVDA's settings dialog

I'm closing this one as per above points. I noticed however that it is not possible to reassign the several browse mode navigation keys using the input gestures dialog. For cases like these, it might make sense to make these configurable. However, that's a different issue and therefore needs to be file separately. I'd still like to see proper justification in such an issue.
