### ISSUE TITLE
Excel freeze/crash completely crashes NVDA making it  completely unresponsive to user input

### ISSUE THREAD

**Issue by enessaribas** [nvaccess/nvda#9591]
### Steps to reproduce:
1. open excel, and initiate an action that causes excel to freeze and become unresponsive.

### Actual behavior:
NVDA completely  freezes and crashes, even when focus is not in the unresponsive excel window. Moreover, ctrl alt del to bring up the login screen, or NVDA restarts do not resolve this issue.
### Expected behavior:
NVDA does not crash with excel, permiting termination of excel without a third party screen reader.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
alpha-17227,1fcc2d3d
#### Windows version:
windows 10 1809
#### Name and version of other software in use when reproducing the issue:
office 365 16.0.11601.20204 
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

**Comment by Adriani90** [comment]
@enessaribas if NVDA crashes, there will be a mini crashdump generated. Could ypu please upload it here together with the log file?
You can do this by following steps:
1. Open NVDA and reprotude the issue
2. After terminating Excel and restarting NVDA, press windows+r and type %temp%
3. There you should find two files:
a) NVDA_old.log and
b) NVDA_minicrashdump.dmp
Could you please upload those two files?

**Comment by Adriani90** [comment]
Before doing the stepps above, could you please update to Version: alpha-17252,7e26d874? The alpha is here:
https://ci.appveyor.com/api/buildjobs/k2pit1g3ugsp1bvp/artifacts/output/nvda_snapshot_alpha-17252,7e26d874.exe

**Comment by enessaribas** [comment]
Hi,
I do not know a way to relyably crash excel. This crash happened spontaniously, and I cannot cause another crash. However, any situation causing excel to freeze generates this condition.

**Comment by leonardder** [comment]
Could the crash be related to initiating an edit action, i.e. pressing f2 in a cell?

If so, could you go to Excel's options, and on the advanced tab, disable the check box that says: `Allow editing directly in cells`?

**Comment by nvdaes** [comment]
Hello: A user from spanish community reports an error that maybe related to this issue. Here's part of the log. Please request more info if needed. Thanks:

> NVDA version 2019.1.1
INFO - core.main (09:00:44.042):
Using Windows version 10.0.17763 workstation
IO - speech.speak (09:57:36.598):
Speaking [u'Alerta - Vista protegida  agrupaci\xf3n']
IO - speech.speak (09:57:36.609):
Speaking [u'Habilitar edici\xf3n  bot\xf3n conmutador  sin pulsar  Habilitar edici\xf3n  Alt, A, F, J']
IO - inputCore.InputManager.executeGesture (09:57:37.283):
Input: kb(desktop):space
IO - speech._speakSpellingGen (09:57:37.309):
Speaking character u'espacio'
DEBUG - queueHandler.registerGeneratorObject (09:57:37.309):
Adding generator 626
DEBUG - queueHandler.pumpAll (09:57:37.319):
generator 626 finished
IO - speech.speak (09:57:37.608):
Speaking [u'Base de Datos.xlsx  -  Vista protegida']
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (09:57:37.638):
Could not locate dropdown list in previous objects
DEBUG - treeInterceptorHandler.update (09:57:37.648):
Adding new treeInterceptor to runningTable: <NVDAObjects.window.excel.ExcelBrowseModeTreeInterceptor object at 0x0526B130>
IO - speech.speak (09:57:37.657):
Speaking [u'BASE DE DATOS  tabla  contrase\xf1a']
IO - speech.speak (09:57:37.677):
Speaking [u'AI356']
DEBUGWARNING - watchdog._watcher (09:57:40.098):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 233, in <module>
  File "core.pyo", line 519, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 1003, in Notify
  File "core.pyo", line 489, in run
  File "IAccessibleHandler.pyo", line 900, in pumpAll
  File "IAccessibleHandler.pyo", line 757, in processForegroundWinEvent
  File "IAccessibleHandler.pyo", line 524, in winEventToNVDAEvent
  File "_UIAHandler.pyo", line 389, in isUIAWindow
  File "_UIAHandler.pyo", line 367, in _isUIAWindowHelper

DEBUG - treeInterceptorHandler.killTreeInterceptor (09:57:40.709):
Killed treeInterceptor: <NVDAObjects.window.excel.ExcelBrowseModeTreeInterceptor object at 0x0526B130>
IO - speech.speak (09:57:40.818):
Speaking [u'Base de Datos.xlsx - Excel']
DEBUG - appModuleHandler.cleanup (09:57:41.489):
application excel closed
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (09:57:41.548):
Could not locate dropdown list in previous objects
DEBUG - treeInterceptorHandler.update (09:57:41.568):
Adding new treeInterceptor to runningTable: <NVDAObjects.window.excel.ExcelBrowseModeTreeInterceptor object at 0x0526B070>
IO - speech.speak (09:57:41.568):
Speaking [u'BASE DE DATOS  tabla']
IO - speech.speak (09:57:41.598):
Speaking [u'AI356']

**Comment by Adriani90** [comment]
@enessaribas could you please try with NVDA 2020.1? Is this issue still occuring for you?

**Comment by enessaribas** [comment]
Hello,
As I cannot relyably reproduce this, I cannot test.  The main problem here is that NVDA crash completely crashes the entire pc, and not just NVDA or Excel.

**Comment by seanbudd** [comment]
Closing this as stale. If this is still an issue with NVDA 2022.1 and the latest Excel, please confirm either by reopening this issue or creating a new one.

As mentioned in earlier comments, to progress this issue we need a [log file and crash dump](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour.
Even if the issue cannot be reliably reproduced, when it does occur, please capture the log and crash dump.

Kind Regards,
NV Access Software Developers

**Comment by KevGP** [comment]
Freezes for me too. Even editing a brand new workbook causes NVDA to crash on Windows 10 and dramatically slows down my PC.
How do I get the crash dump? I can view the log when NVDA is running, but not when it's not. I checked %appdata%\NVDA but not sure where the "crash dump" is located...

**Comment by seanbudd** [comment]
@KevGP - the instructions are found in the link the previous message.
I'm not sure where you are getting that folder path from.
