### ISSUE TITLE
say all in open office

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#96]
**Reported by chris1988 on 2008-05-28 16:14**
When the user hits nvda down to say all in Open office writer, nvda will just read the current line that has focus.  I'm not sure if this has anything to do with java and java access bridge.  If thisn this isn't a nvda issue, I'm sorry.

**Comment by leonardder** [comment]
Is it safe to assume that this is solved now that Open Office relies on IAccessible2? CC @oaron

**Comment by jcsteh** [comment]
I believe LibreOffice still misbehaves with respect to reading more than one page at a time. Closing in favour of #4119, which is clearer about the current state of things and only discusses the IA2 implementation (not the defunct JAB implementation).
