### ISSUE TITLE
NVDA on IE7 with Outlook express as default email client does not read field descriptions or contents of cc and to fields during send link or page by email action

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#960]
**Reported by briang1 on 2010-10-03 11:33**
To create the problem
You need.
 1 off each.
Windows XP
 Outlook express set as default emailer
Internet Explorer 7 set as default browser

Method.
Browse to a page or link you wish to email
Select file/send
Select either page by email or link by email
 You will notice that no field is given a name

Further, you will notice, if you browse the menu bar that you are in Outlook express and can indeed use the address book to  select the email to send to. However even if you select your recipient and hit enter twice to  put it in, you cannot read the address afterwards.
 My suspicion is that in fact, we are still in the Internet Explorer app module. Log fragment

INFO - nvda (11:26:56):
Starting NVDA
INFO - core.main (11:26:56):
Config dir: C:\nvda release candidates\userConfig
DEBUG - core.main (11:26:56):
setting language to Windows
INFO - core.main (11:26:56):
NVDA version 2010.2-3866
INFO - core.main (11:26:56):
Using Windows version sys.getwindowsversion(major=5, minor=1, build=2600, platform=2, service_pack='Service Pack 3')
INFO - core.main (11:26:56):
Using Python version 2.7 (r27:82525, Jul  4 2010, 09:01:59) [v.1500 32 bit (Intel)](MSC)
INFO - core.main (11:26:56):
Using comtypes version 0.6.2

Snip of the boring bit.
I selected menu bar with alt in IE.

Speaking u'File subMenu Alt + F'
IO - keyboardHandler.internal_keyDownEvent (11:27:12):
key press: extendeddown
IO - speech.speakText (11:27:12):
Speaking u'New Tab \tCtrl+T t'
IO - keyboardHandler.internal_keyDownEvent (11:27:13):
key press: extendeddown
IO - speech.speakText (11:27:13):
Speaking u'New Window \tCtrl+N n'
IO - keyboardHandler.internal_keyDownEvent (11:27:13):
key press: extendeddown
IO - speech.speakText (11:27:13):
Speaking u'Open...\tCtrl+O o'
IO - keyboardHandler.internal_keyDownEvent (11:27:14):
key press: extendeddown
IO - speech.speakText (11:27:14):
Speaking u'Edit with Microsoft FrontPage d'
IO - keyboardHandler.internal_keyDownEvent (11:27:14):
key press: extendeddown
IO - speech.speakText (11:27:14):
Speaking u'Save\tCtrl+S unavailable s'
IO - keyboardHandler.internal_keyDownEvent (11:27:15):
key press: extendeddown
IO - speech.speakText (11:27:15):
Speaking u'Save As... a'
IO - keyboardHandler.internal_keyDownEvent (11:27:15):
key press: extendeddown
IO - speech.speakText (11:27:15):
Speaking u'Close Tab \tCtrl+W c'
IO - keyboardHandler.internal_keyDownEvent (11:27:16):
key press: extendeddown
IO - speech.speakText (11:27:16):
Speaking u'Page Setup... u'
IO - keyboardHandler.internal_keyDownEvent (11:27:17):
key press: extendeddown
IO - speech.speakText (11:27:17):
Speaking u'Print...\tCtrl+P p'
IO - keyboardHandler.internal_keyDownEvent (11:27:17):
key press: extendeddown
IO - speech.speakText (11:27:17):
Speaking u'Print Preview... v'
IO - keyboardHandler.internal_keyDownEvent (11:27:18):
key press: extendeddown
IO - speech.speakText (11:27:18):
Speaking u'Send subMenu e'
IO - keyboardHandler.internal_keyDownEvent (11:27:19):
key press: return
IO - speech.speakText (11:27:19):
Speaking u'Page by E-mail... p'
IO - keyboardHandler.internal_keyDownEvent (11:27:20):
key press: extendeddown
IO - speech.speakText (11:27:20):
Speaking u'Link by E-mail... l'
IO - keyboardHandler.internal_keyDownEvent (11:27:21):
key press: return
DEBUG - appModuleHandler.getKeyMapFileName (11:27:22):
Found keymap file for _default at .\appModules_default_desktop.kbd
DEBUG - appModuleHandler.AppModule.loadKeyMap (11:27:22):
added 80 bindings to appModule <_default (appName wordpad, process ID 3512) at address 22f3d50> from file .\appModules_default_desktop.kbd

For some reason it momentarily displayed wordpad which I had open to record all the  info before creating the ticket!

IO - speech.speakText (11:27:22):
Speaking u'NVDA - New Ticket'
IO - speech.speakText (11:27:22):
Speaking u'edit multi line'
IO - speech.speakText (11:27:22):
Speaking u'blank'
IO - keyboardHandler.internal_keyDownEvent (11:27:29):
key press: tab
IO - speech.speakText (11:27:29):
Speaking u'edit multi line'
IO - speech.speakText (11:27:29):
Speaking u'blank'
IO - keyboardHandler.internal_keyDownEvent (11:27:31):
key press: tab
IO - speech.speakText (11:27:31):
Speaking u'edit'
IO - speech.speakText (11:27:31):
Speaking u'NVDA - New Ticket'
IO - keyboardHandler.internal_keyDownEvent (11:27:34):
key press: tab
IO - speech.speakText (11:27:34):
Speaking u'document editable'
IO - speech.speakText (11:27:34):
Speaking u'blank'
IO - keyboardHandler.internal_keyDownEvent (11:27:36):
key press: shift+tab
IO - speech.speakText (11:27:36):
Speaking u'edit'
IO - speech.speakText (11:27:36):
Speaking u'NVDA - New Ticket'
IO - keyboardHandler.internal_keyDownEvent (11:27:38):
key press: shift+tab
IO - speech.speakText (11:27:38):
Speaking u'edit multi line'
IO - speech.speakText (11:27:38):
Speaking u'blank'
IO - keyboardHandler.internal_keyDownEvent (11:27:40):
key press: shift+tab
IO - speech.speakText (11:27:40):
Speaking u'edit multi line'
IO - speech.speakText (11:27:40):
Speaking u'blank'
IO - speech.speakText (11:27:42):
Speaking u'File subMenu Alt + F'
IO - keyboardHandler.internal_keyDownEvent (11:27:43):
key press: extendedright
IO - speech.speakText (11:27:43):
Speaking u'Edit subMenu Alt + E'
IO - keyboardHandler.internal_keyDownEvent (11:27:43):
key press: extendedright
IO - speech.speakText (11:27:43):
Speaking u'View subMenu Alt + V'
IO - keyboardHandler.internal_keyDownEvent (11:27:44):
key press: extendedright
IO - speech.speakText (11:27:44):
Speaking u'Insert subMenu Alt + I'
IO - keyboardHandler.internal_keyDownEvent (11:27:44):
key press: extendedright
IO - speech.speakText (11:27:44):
Speaking u'Format subMenu Alt + o'
IO - keyboardHandler.internal_keyDownEvent (11:27:45):
key press: extendedright
IO - speech.speakText (11:27:45):
Speaking u'Tools subMenu Alt + T'
IO - keyboardHandler.internal_keyDownEvent (11:27:46):
key press: extendeddown
IO - speech.speakText (11:27:46):
Speaking u'Spelling...\tF7 s'
IO - keyboardHandler.internal_keyDownEvent (11:27:47):
key press: extendeddown
IO - speech.speakText (11:27:47):
Speaking u'Request Read Receipt checked t'
IO - keyboardHandler.internal_keyDownEvent (11:27:48):
key press: extendeddown
IO - speech.speakText (11:27:48):
Speaking u'Check Names\tCtrl+K k'
IO - keyboardHandler.internal_keyDownEvent (11:27:49):
key press: extendeddown
IO - speech.speakText (11:27:49):
Speaking u'Select Recipients... r'
IO - keyboardHandler.internal_keyDownEvent (11:27:50):
key press: return
IO - speech.speakText (11:27:50):
Speaking u'Select Recipients dialog'
IO - speech.speakText (11:27:50):
Speaking u'Type name or select from list: edit Alt+y'
IO - speech.speakText (11:27:50):
Speaking u'\x00'
IO - keyboardHandler.internal_keyDownEvent (11:27:55):
key press: tab
IO - speech.speakText (11:27:55):
Speaking u'Find... button Alt+d'
IO - keyboardHandler.internal_keyDownEvent (11:27:57):
key press: tab
IO - speech.speakText (11:27:57):
Speaking u"combo box Brian Gaff Main's Contacts"
IO - keyboardHandler.internal_keyDownEvent (11:28:00):
key press: tab
IO - speech.speakText (11:28:00):
Speaking u'Address List list'
IO - speech.speakText (11:28:00):
Speaking u'~\xae\xe5v\xd1sf\xe5n\xae~ E-Mail Address: rustylombardi@ravens.com'
IO - keyboardHandler.internal_keyDownEvent (11:28:09):
key press: b
IO - speech._speakSpellingGen (11:28:09):
Speaking character u'b'

Snip of private addresses...
IO - speech.speakText (11:28:14):
Speaking u'Brian Gaff E-Mail Address: briang1@blueyonder.co.uk'
IO - keyboardHandler.internal_keyDownEvent (11:28:18):
key press: return
IO - keyboardHandler.internal_keyDownEvent (11:28:18):
key press: return
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (11:28:18):
oleacc.AccessibleObjectFromEvent with window 459862, objectID -4 and childID 0: [-2147467259](Error) Unspecified error
IO - speech.speakText (11:28:18):
Speaking u'NVDA - New Ticket'
IO - speech.speakText (11:28:18):
Speaking u'edit multi line'
IO - speech.speakText (11:28:18):
Speaking u'\ufffc'
IO - keyboardHandler.internal_keyDownEvent (11:28:22):
key press: tab
IO - speech.speakText (11:28:22):
Speaking u'edit multi line'
IO - speech.speakText (11:28:22):
Speaking u'blank'
IO - keyboardHandler.internal_keyDownEvent (11:28:23):
key press: shift+tab
IO - speech.speakText (11:28:23):
Speaking u'edit multi line'
IO - speech.speakText (11:28:23):
Speaking u'\ufffc'
IO - keyboardHandler.internal_keyDownEvent (11:28:25):
key press: extendedleft
IO - keyUtils.sendKey (11:28:25):
extendedleft
DEBUG - queueHandler.isPendingItems (11:28:25):
pending events in eventQueue: False
IO - speech._speakSpellingGen (11:28:25):
Speaking character u'\ufffc'
IO - keyboardHandler.internal_keyDownEvent (11:28:26):
key press: extendedright
IO - keyUtils.sendKey (11:28:26):
extendedright
DEBUG - queueHandler.isPendingItems (11:28:26):
pending events in eventQueue: False
IO - speech.speakText (11:28:26):
Speaking u''
IO - keyboardHandler.internal_keyDownEvent (11:28:26):
key press: extendedleft
IO - keyUtils.sendKey (11:28:26):
extendedleft
DEBUG - queueHandler.isPendingItems (11:28:26):
pending events in eventQueue: False
IO - speech._speakSpellingGen (11:28:26):
Speaking character u'\ufffc'
IO - keyboardHandler.internal_keyDownEvent (11:28:27):
key press: extendedleft
IO - keyUtils.sendKey (11:28:27):
extendedleft
DEBUG - queueHandler.isPendingItems (11:28:27):
pending events in eventQueue: False
IO - speech._speakSpellingGen (11:28:27):
Speaking character u'\ufffc'
IO - keyboardHandler.internal_keyDownEvent (11:28:27):
key press: extendedright
IO - keyUtils.sendKey (11:28:27):
extendedright
DEBUG - queueHandler.isPendingItems (11:28:27):
pending events in eventQueue: False
IO - speech.speakText (11:28:27):
Speaking u''
IO - keyboardHandler.internal_keyDownEvent (11:28:28):
key press: tab
IO - speech.speakText (11:28:28):
Speaking u'edit multi line'
IO - speech.speakText (11:28:28):
Speaking u'blank'
IO - keyboardHandler.internal_keyDownEvent (11:28:29):
key press: tab
IO - speech.speakText (11:28:29):
Speaking u'edit'
IO - speech.speakText (11:28:29):
Speaking u'NVDA - New Ticket'
IO - keyboardHandler.internal_keyDownEvent (11:28:33):
key press: tab
IO - speech.speakText (11:28:33):
Speaking u'document editable'
IO - speech.speakText (11:28:33):
Speaking u'blank'

I'm now in the message body.

nvda/F1 dump

key press: nvda+f1
INFO - appModules._default.AppModule.script_navigatorObject_devInfo (11:30:25):
Developer info for navigator object:
name: None
role: ROLE_EDITABLETEXT
states: STATE_MULTILINE, STATE_FOCUSABLE, STATE_FOCUSED
Python object: <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x022FBF70>
Python class mro: (<class 'NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.edit.RichEdit20'>, <class 'NVDAObjects.window.edit.RichEdit'>, <class 'NVDAObjects.window.edit.Edit'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (178, 214, 315, 16)
value: None
appModule: <_default (appName iexplore, process ID 1128) at address 22e46f0>
TextInfo: <class 'NVDAObjects.window.edit.EditTextInfo'>
windowHandle: 2425546
windowClassName: u'RichEdit20W'
windowControlID: 1001
windowStyle: 1342275652
windowThreadID: 792
windowText: u'\x00'
IAccessibleObject: <POINTER(IAccessible) ptr=0x1a8478 at 22f08a0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=2425546, objectID=-4, childID=0
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)

I hope this is understandable.

**Comment by leonardder** [comment]
This is XP and Outlook Express specific. NV Access isn't putting effort into fixing XP specific issues any more. Closing as won't fix.
