### ISSUE TITLE
Again remove Handy Tech com server from NVDA distributions

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9604]
### Is your feature request related to a problem? Please describe.
Though we have a native driverfor Handy Tech braille displays, the com server used for the legacy driver is still kept for ease of use, per request of handy tech. See #8213 

### Describe the solution you'd like
Again, I'd like to consider removing the com server from NVDA as part of the Threshold/Python 3 transition. At the time #8213 was filed, there was a valid reason for it, namely that the new native driver didn't offer support for older displays. This was fixed in #8016. Automatic braille display detection also works perfectly with HT displays. I believe there are currently two reasons for which a user might prefer the old driver:

* Using the built-in braille monitor. Note that that monitor has some braille translation issues.
* Using ATC with displays that don't support activating it in hardware, such as the Modular Evolution.

With removing the COM server, I'd like to urge Handy Tech to implement basic ATC support in the native driver.

cc @FelixGruetzmacher @michaelDCurran

**Comment by leonardder** [comment]
I discussed this in a phone call with @FelixGruetzmacher. Handy Tech will advise people to run the com server installer if they really want to stick to the classic driver.

**Comment by Adriani90** [comment]
@leonardder the milestone for 2019.3 has been added to this issue due to the referenced pull request. Did that PR remove the old handytech server though?

**Comment by leonardder** [comment]
Fixed in most recent update of misc-deps
