### ISSUE TITLE
fs braille displays on alpha ignore keypresses on main 8-key and space.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#9608]
The brand new fs driver breaks on my focus (Older series). I don't know how their numbering for series goes, but the fermware fersion says focus 40 5.71
STR:
1. open input help mode.
2. try to type anything on one of the 8 keys of input.
expected: input
Actual: Not even registered by the new driver.

**Comment by derekriemer** [comment]
@jcsteh did you take up the rest of the work on the fs driver? Trying to tag the right peeps here.

**Comment by leonardder** [comment]
@bramd is the right author here

**Comment by bramd** [comment]
@derekriemer Thanks for reporting this issue. I have a display with firmware 5.71 as well and braille input works as expected in input help.

It is possible to disable the braille keyboard in hardware, could you check if this is the case? If you press the power button, you should get the status display including firmware and connection state. If the braille keyboard is disabled, you see a `⣮⣵` symbol neer the right end of the display. You can enable the keyboard by pressing the right round button (NVDA reports this as RightWizWheelPress) + one of the routing buttons.

If this doesn't solve your issue, please post a log on debug level and enable hwIo logging in the advanced preferences.

**Comment by lukaszgo1** [comment]
I cannot reproduce it with my Focus 40 Blue with firmware version 5.71 either.

**Comment by derekriemer** [comment]
Okay, yeah, kb was disabled.
