### ISSUE TITLE
Focus movement changing between focus and browse mode with UIA in Word 365

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#9611]
### Steps to reproduce:
1. Open Word 365 with a document longer than visually fits on screen.  Have the option to use UIA in Word checked in NVDA's advanced options.
2. At the top of the document, press NVDA+spacebar to put NVDA in Browse mode.
3. Press CONTROL+END to move to the end of the document.
4. Press NVDA+spacebar to put NVDA in Focus mode.
5. Press the up arrow.

### Actual behavior:

A) At Step 3, the screen does NOT scroll to show the current location of the cursor.
B) At Step 5, the focus jumps back to the start of the first line.  Note that if the left arrow is pressed in Step 5, the focus moves to the END of the first line.  If the right arrow or down arrow are pressed, the focus moves to a spot just under the visible text (eg if one full page is visible, the focus moves to the start of page 2).

C) At Step 3, instead of moving to the end of the document, if the focus is moved within the visible text on screen, the focus is where it would be expected to be after step 5.

### Expected behavior:
At Step 3, the screen should scroll to show the end of the document.
At Step 5, the focus should be at the end of the document (one character from the end if left arrow is pressed, on the second last line if the up arrow is pressed).

#### NVDA version:
2019.1.1 installed

#### Windows version:
Windows 10 Version: 
18362.1 
#### Name and version of other software in use when reproducing the issue:
Office 365 Version: 
16.0.11601.20184 

#### Does the issue still occur after restarting your PC?
Yes.  Also reported by a user.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA alpha-17311,0d29265e - same behaviour.

**Comment by michaelDCurran** [comment]
@Qchristensen  Please test this try build: https://ci.appveyor.com/api/buildjobs/bsjf2a8c6t9879wf/artifacts/output%2Fnvda_snapshot_try-i9611-23673%2C38a7b5ac.exe
Browse mode in MS word with both UIA enabled and disabled should scroll the document to the exact browse mode position, even across pages.
It may be an idea to also check that scrolling in Firefox and Chrome still works as expected.
Possibly even Edge with UIA enabled.

**Comment by Qchristensen** [comment]
That try build seems to do the trick in Word, and scrolling in FF, Chrome and Edge seems to work as expected as well.
