### ISSUE TITLE
nvda cuts off the first item that is focused on the extended inventory list.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9618]
### Steps to reproduce:
open site
www.google.com
press b to get the button
Google Apps
Press enter.
Press (comma) to go to the last item in the list
More Google apps
Press enter.
### Actual behavior:
nvda announces the expansion of the list and says nothing more.
### Expected behavior:
nvda announces expansion of the list
and announces the first item in the case the first google app in this list.
In my case the translator.
If you press nvda + tabe it announces the item name the app with focus.
#### NVDA installed/portable/running from source:
instal
#### NVDA version:
alfa 17329
#### Windows version:
10 18362.113
#### Name and version of other software in use when reproducing the issue:
chrome 74
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
log:
[butyon.txt](https://github.com/nvaccess/nvda/files/3217734/butyon.txt)

**Comment by Adriani90** [comment]
@leonardder, @mltony this is solved if you disable "automatically set system focus to focusable elements" in advanced settings of NVDA.

**Comment by Adriani90** [comment]
Automatic move system focus to focusable lements is off by default, so this issue is actually nor relevant anymore. Closing as works for me.
Please comment in case you have this issue even with automatic move system focus to focusable elements disabled, and then we can proceed with investigations.
