### ISSUE TITLE
Unable to navigate between slides and edit content in Google Slides

### ISSUE THREAD

**Issue by xtstoll** [nvaccess/nvda#9623]
### Steps to reproduce:
1. Open Google Chrome.
2. Open a presentation in Google Slides with multiple slides and text content.
3. Press DOWN ARROW to go to the next slide.
4. Press TAB to go to a text box on a slide.
5. Press ENTER to edit the text.

### Actual behavior:
- When pressing DOWN ARROW, nothing happens.
- When pressing ENTER on text box, NVDA makes the sounds for Edit Mode, but does not actually enter Edit Mode.

### Expected behavior:
- DOWN ARROW should go to the next slide.
- ENTER should allow you to edit text.

### System configuration
Google Slides with Accessibility enabled

#### NVDA installed/portable/running from source:
NVDA Installed

#### NVDA version:
NVDA 2019.1.1

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
Google Chrome 74.0.3729.169 - 64 bits

#### Other information:
Both keys, DOWN ARROW and ENTER, work when you use the NVDA "Pass next key through"	(NVDA + F2). Also, without NVDA on, the two keys work properly.

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

**Comment by Adriani90** [comment]
This works as expected in NVDA 2020.1 and Chrome 81 or Firefox 76. You might have to enable screen reader and braille support in Google presentations for this to work properly.
Closing as works for me.
