### ISSUE TITLE
The focus does not change when opening a link in a new tab, NVDA is silent

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#9625]
### Steps to reproduce:
1. Open Firefox or Chrome
2. Open NVDA
3. Go to www.google.com and in the search field type Github nvda
4. Using browse mode in NVDA, navigate with h to the first result
5. Press ctrl+enter on the link

### Actual behavior:
NVDA reports only "visited" but it does not indicate that a new tab has been opened. The focus stays on the google search page.

### Expected behavior:
The focus should change to the link in the new tab (in this case Github NVDA) and NVDA should report the page title when the focus changes.
If the link opens in a new tab in background, NVDA should report this at least.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.1.1

#### Windows version:
Windows 10 1809 Update

#### Name and version of other software in use when reproducing the issue:
Firefox 67, Chrome 74.

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

**Comment by DrSooom** [comment]
@Adriani90: Isn't this a browser feature – open links in a new tab in the foreground/background?

**Comment by Adriani90** [comment]
This might be, thanks for pointing out. I have edited the description accordingly.

**Comment by DrSooom** [comment]
> If the link opens in a new tab in background, NVDA should report this at least.

Only as an option, as everybody should already know that CTRL+LeftClick and CTRL+Enter open a link by default in a new tab. And the tabbed browser feature is 15 years old.

**Comment by Adriani90** [comment]
> Only as an option, as everybody should already know that CTRL+LeftClick and CTRL+Enter open a link by default in a new tab. And the tabbed browser feature is 15 years old.

Actually there are also young people surfing through the internet who do not know this feature. Also when pressing ctrl+tag to swich between tabs or ctrl+t to open new tabs, the tab titles are reported. Why not when pressing ctrl+enter?

**Comment by Adriani90** [comment]
cc: @MarcoZehe do you have any edea for firefox at least, why is nothing reported when pressing ctrl+enter on a link?

**Comment by Cleversn** [comment]
Just as a matter of curiosity, the reason why I have never realized this problem is because I've created a sound scheme at the Windows control pannel to play a sound when a new process is opened. So, on pressing control+Enter, I know a new tab has opened because the open program sound plays.

**Comment by lukaszgo1** [comment]
In other cases like CTRL+T or  CTRL_TAB NVDA reports title of the new tab because focus moves to it.
When opening a new one with CTRL+Enter it does not, so there is no point reporting anything. In addition if someone presses CTRL+Enter it is highly unlikely that it was done without knowing what this shortcut would do.

**Comment by Adriani90** [comment]
In my view it should at least report that a new tab has opened in background. Someone might press the key stroke also accidentally. Or at least a sound should indicate that something happened. This could be introduced by the browser itself, it does not have to be a feature in NVDA.

 

Von: Łukasz Golonka <notifications@github.com> 
Gesendet: Freitag, 13. Dezember 2019 23:08
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [nvaccess/nvda] The focus does not change when opening a link in a new tab, NVDA is silent (#9625)

 

In other cases like CTRL+T or CTRL_TAB NVDA reports title of the new tab because focus moves to it.
When opening a new one with CTRL+Enter it does not, so there is no point reporting anything. In addition if someone presses CTRL+Enter it is highly unlikely that it was done without knowing what this shortcut would do.

**Comment by Adriani90** [comment]
In NVDA 2024.1 Beta, Firefox 122 and Chromium browsers Edge and Chrome 121, NVDA reports a preview of the link opened in a new tab when pressing ctrl+enter, and the property that it is visited. So this is now fixed. Closing as works for me.
