### ISSUE TITLE
UIA in Windows Console: Space Character is not Announced when Deleting Characters

### ISSUE THREAD

**Issue by Mohamed00** [nvaccess/nvda#9632]
### Steps to reproduce:
Open the command prompt and type a command, such as help help, and press backspace to delete the characters.
### Actual behavior:
The space character is not announced when deleting characters, and the character to the left is announced instead of the space.
### Expected behavior:
The space character should be announced.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
alpha-17373,98dc8278
#### Windows version:
Windows 10, Version	10.0.18898 Build 18898
#### Name and version of other software in use when reproducing the issue:
Windows Command Prompt.
#### Other information about your system:
N/a.
#### Does the issue still occur after restarting your PC?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

**Comment by codeofdusk** [comment]
This is probably related to the caret movement issues on 1903. CC @michaelDCurran
