### ISSUE TITLE
User Accounts in Control Panel suddenly exits

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#964]
**Reported by dharvey on 2010-10-04 21:11**
When scrolling through the User Accounts area in Control Panel using NVDA 2010.2-Beta2 it suddenly exits.
1.  Go to Control Panel and select User Accounts
2.  Scroll through the accounts list.

Result:  NVDA 2010.2-Beta2 exits and returns to Control Panel.  Problem doesn't occur in NVDA 2010.1.

**Comment by ehollig** [comment]
Is this still an issue? It sounds like it only happens on XP machines. CC @Brian1Gaff

**Comment by jcsteh** [comment]
XP specific. Closing.
