### ISSUE TITLE
Python 3: dict.has_key is no more

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9640]
Hi,

Another round of Python 3 compatibility report: dict.has_key is gone.

### Steps to reproduce:
Define a dictionary and try obtainig a key by doing dict.has_key(key).

### Actual behavior:
Attribute error is raised in Python 3.

### Expected behavior:
No errors.

#### NVDA installed/portable/running from source:
Source and installed

#### NVDA version:
master.17384

#### Windows version:
Windows 10 Version 1903

#### Name and version of other software in use when reproducing the issue:
N/A

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Source code version of Python 3 NVDA.

### Technical:
dict.has_key is gone. The alternative is key in dict.

Thanks.

**Comment by leonardder** [comment]
If there will be a separate pr for this, I vote for filing it against master. This is because the change is completely compatible with Python 2 and will be merged into threshold when master is merged. When merged into master, it will also get broader testing.

**Comment by josephsl** [comment]
Hi, we may need to wait, as two of the lines affected by this are tied to xrange to range conversion. Thanks.

**Comment by leonardder** [comment]
Fixed in #9697
