### ISSUE TITLE
Python 3: division operator differences between classic and the new division

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9641]
### Steps to reproduce:
Run Python 2 and 3 interpreters and try performing division operation such as "3 / 2" and "3 // 2".

### Actual behavior:
Errors such as not being converted to integer in Python 3.

### Expected behavior:
No errors.

#### NVDA installed/portable/running from source:
Source and installed

#### NVDA version:
master.17384

#### Windows version:
Windows 10 Version 1903

#### Name and version of other software in use when reproducing the issue:
N/A

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes - source code version of Python 3 NVDA

### Context:
Division operator semantics has changed between Python 2 and 3:

* /: floor division for integers in Python 2, regular division in Python 3
* //: integer division for both Python 2 and 3.

There are places in NVDA that will expect integers via single slash operator when in fact it will return float in Python 3. These include Windows Console handler, GUI, mouse handler and others. Thus either standardize around calling int, or use two slashes. Note that this must be tested extensively to make sure regressions are not introduced.

Thanks.

**Comment by leonardder** [comment]
Fixed in #9692 , #9774, #9737 , #9748
