### ISSUE TITLE
NVDA does not see the majority of content on the vatican.va Web site

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#965]
**Reported by dgoldfield on 2010-10-05 03:08**
When going to the vatican.va Web site NVDA does not identify any of the links or text on the main page while in browse mode.  If I press NVDA plus space to disable browse mode I am able to tab through the various links.  When I pressed enter on the link to go to the English version of the site NVDA did identify a form which contained an edit box and a search button but nothing else appeared in the virtual buffer but disabling browse mode did allow me to access links using the tab key.  I think I temporarily forced NVDA to get the page in the virtual buffer by closing and restarting the screen reader while the page had focus.

**Comment by ehollig** [comment]
I am  able to read the links and text on the main page of the vatican.va website in browse mode. Maybe the website changed over the years since this ticket was created.

**Comment by leonardder** [comment]
For website specific issues, it is quite unlikely that NVDA is the cause of the problem. 

@dgoldfield: If you are the dgoldfield that opened this issue, could you please give information on the status of this issue?

**Comment by ehollig** [comment]
Closing as worksforme. If this is still an issue for @dgoldfield, if he is the original poster, we can reopen this issue.
