### ISSUE TITLE
More reliable results from system tests

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#9655]
### Is your feature request related to a problem? Please describe.
For some time now NVDA has ability to perform system tests during build on AppVeyor. These are very important and would be even more important in the future due to Python 3 migration. At the moment it is necessary to install some packages from pip to perform these. As they are installed from an online repository  for most of them latest version is in use. This causes problems especially pyAutoGui and its dependencies see #9358, #9592, and #9659.
### Describe the solution you'd like
I see three possibilities of solving this:
1. Install known good versions of all of the required packages. Not very nice, but if we aren't missing any new features in them it might be acceptable. We are already doing that for some of them.
2. Use a virtual env for system tests. I haven't tried this and don't know if it would work, but it might be worth trying.
3. As the only problematic package for now is PyAutoGui and friends perhaps simply replacing it with something more reliable would be good in the long term. Quick googling shows PyWinAuto as a common alternative. Another advantage of doing that is the fact, that PyWinAuto has only a few dependencies which could break. I'll probably investigate this.
### Describe alternatives you've considered
We can leave it as is and simply downgrade specific package each time something is broken. The recent breakages are caused by Python 2, so maybe we should simply wait for Python 3 migration and hope for the best.
### Additional context
None

**Comment by leonardder** [comment]
@lukaszgo1: do you consider this fixed? If not, could you please update the initial description?

**Comment by Adriani90** [comment]
cc: @feerrenrut

**Comment by feerrenrut** [comment]
I think in the future we should move to have a virtual env for NVDA and also for the system tests. This will require some thought on how to bootstrap the virtual env setup. Building NVDA should be as easy as possible, I can foresee people forgetting to enable the virtual env for instance. We will continue to monitor the system tests for failures, while this issue raises good points I think it is too vague. I'm going to close it.
