### ISSUE TITLE
Tree of roles not tracking properly

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#967]
**Reported by christopherh40 on 2010-10-05 06:34**
In Windows Server 2008, in the Server Manager, in the Add Role wizard, the tree of roles are not tracking properly by NVDA. Window-Eyes on the other hand does.

**Comment by leonardder** [comment]
This seemed to work fine last time I checked with Server 2012. Closing due to two reasons:

1. The author mentions server 2008, not 2008R2. 2008 mainstream support [ended on 13 January 2015](https://en.wikipedia.org/wiki/Windows_Server_2008).
2. The ticket is quite abandoned.
