### ISSUE TITLE
Gestures still saved when "Save configuration on exit" is off

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#9688]
### Steps to reproduce:

1. Press NVDA+ctrl+g, and turn off "Save configuration on exit" if it's on.
2. Open the NVDA menu, preferences, input gestures.
3. Go to any unassigned gesture (example: "Restarts NVDA" under "Miscellaneous").
4. Assign a gesture to that function (example: NVDA+alt+F3).
5. Press OK.
6. Restart NVDA by any means (example: ctrl+alt+n).
7. Repeat steps 2 and 3 above, and examine whether there is a gesture assigned to the selected function. Or, just test the gesture you created.

### Actual behavior:

Any created (or modified) gesture remains configured after a restart, and with no intervening configuration save.

### Expected behavior:

Given that "Save configuration on exit" is off, and no save operation was performed, I would expect a newly created gesture to disappear, and the function it performed to become unassigned, once NVDA restarts. Correspondingly, I would expect any modified gesture to revert to its former state when NVDA restarts. Neither happens; the changes persist after a restart.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.1.1

#### Windows version:
Windows 10 Home, Version 1803 (OS Build 17134.765)

#### Name and version of other software in use when reproducing the issue:
None/not applicable

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, 2019.2beta1

#### Other Information

I ran 2019.2beta1 as a portable with no addons, and got the same behavior.

It seems that this behavior is intentional, as if gestures are not considered part of the configuration. However, from a user prospective, I would expect gestures to be part of the configuration, since they are configurable, and therefore they should obey "save configuration on exit".

I have attached two logs: one from before the restart, which shows me assigning a gesture and the temporary .ini file which is created during that process; and a less useful log which shows what happens after the restart, which simply serves to demonstrate that the gesture is still there.

[after_restart.txt](https://github.com/nvaccess/nvda/files/3264585/after_restart.txt)
[before_restart.txt](https://github.com/nvaccess/nvda/files/3264586/before_restart.txt)

**Comment by DrSooom** [comment]
Customized gestures are stored in the file "gestures.ini". This behavior exists since NVDA 2013.3, in which this function was added to NVDA.

In addition: What's about the behavior for add-on settings? As not all add-ons are able to save their configuration into the file "nvda.ini", the behavior here is also inconsistent.

**Comment by JulienCochuyt** [comment]
@XLTechie, I agree this is unexpected behavior for new users, already had this pointed out during trainings.
Also, one would expect all gestures to be reset to factory defaults when configuration is.
Or maybe after configuration factory reset ask the user if it wishes to also reset gestures, or else add a button to reset gestures in the gestures dialog…

@feerrenrut, what do you think?

@DrSooom, add-ons that store settings of their own may/should hook onto the pre and post configReset extensionPoints as of PR #7606 since 2018.3

**Comment by CyrilleB79** [comment]
IMO the current behavior is the most expected one and is what I would expect.
Indeed I have disabled Saved on exit in order not to save temporary modifications such as table announcement, language change, voice speed, etc. These are parameters that one may want to changed on the fly for temporary need. And these parameters can often be changed by shortcut, without opening the settings dialog.

On the contrary, for the following elements of configurations, I expect them to be saved even if I do not have "Save on exit" checked:

* New dictionary entries
* New symbol description
* Newly defined gestures
* Newly installed add-ons
* Newly defined profiles or triggers

None of these changes can be made via shortcut key.

Maybe a more detailed explanation in the documentation would be more suitable: indicating that the configuration corresponds to all the parameters defined in the "Settings" window.

@JulienCochuyt I understand your point with newly trained people. On the other hand, if we do not save new gestures anymore, wouldn't there be other people that expect them to be saved?

**Comment by JulienCochuyt** [comment]
@CyrilleB79, I think your way of presenting it perfectly makes sense.
I'm currently prototyping two additions to the gestures dialog:
 - a checkbox beside the filter to show only what was modified by the user (not yet fully convinced if useful, needs testing)
 - a button to restore factory defaults

**Comment by Adriani90** [comment]
Considering the comments above and the merged PR, do you think we can close this issue? Or are there any other expectations here?

**Comment by XLTechie** [comment]
There has been no comment on this in almost a year. I had left it open in case @DrSooom or @JulienCochuyt had something else to say, but nobody has.

I am still not sure i agree with the idea that a user expects gestures to be saved even if the configuration is not.  I am pretty sure that new users wouldn't expect that behavior given usage of other programs where gestures are considered part of the configuration.  But I understand the argument in the other direction, and I don't think anything is served by leaving this issue open longer.

**Comment by feerrenrut** [comment]
Apologies all, I obviously missed the conversation here. I see benefits to both sides of the argument, and agree that neither behavior is perfectly intuitive. I like the suggestion from @JulienCochuyt to look at how other aspects of the UX can be adjusted to make this more intuitive.

While @JulienCochuyt is looking to make it more obvious that something in the gestures list has deviated from the default configuration, looking at the other side of the problem we could try the following: Prevent auto-saves (align with the save on exit  setting) but when save on exit is disabled warn the user as they exit the gesture screen that their change will be temporary (until exit) and offer to make it permanent now. A dialog like:

"Save on exit is disabled, this modification will not be permanent unless you save your configuration now or manually save your configuration via the NVDA menu later. Would you like to make your modifications to gestures permanently now?"
With options:
- "Yes"
- "No"
- "checkbox: don't ask me again."
