### ISSUE TITLE
UIA in Windows consoles: no easy way to read prompt contents with speech

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9689]
### Steps to reproduce:
1. Enable NVDA's experimental UIA support in Windows consoles in recent Alpha builds
2. Open a command console
3. Type python
4. Press down arrow

### Actual behavior:
NVDA says blank. However, braille just shows the prompt, just as expected.

### Expected behavior:
NVDA reads the complete line, including the prompt: e.g. `C:\Users\Leonard de Ruijter>python`

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-17533

#### Windows version:
Windows 10 version 1093 build 18362.116

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, this was the start from the primiliary support

cc @codeofdusk

**Comment by codeofdusk** [comment]
Expected behavior observed on Windows 10 1803. This is likely related to #9632 and the other 1903 caret/text range bugs. Cc @michaelDCurran

**Comment by lukaszgo1** [comment]
I can no longer reproduce this with latest alpha on a vm running Windows 10 1903. @leonardder Is this fixed for you?

**Comment by michaelDCurran** [comment]
This was fixed several months back, but I can't quite identify the actual commit. I can confirm this issue no longer is reproducable.
