### ISSUE TITLE
Speech slower than expected with cell navigation in excel

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9694]
### Steps to reproduce:
Open a spreadsheet in excel with simple formulas
cell a1 enter the formula
= 1 * 30
cell a2
= a1 * 12
a1 will have 30
a2 will be
360
Now keep alternating with arrows up and down between cells a1 and cell a2.
Doing this with medium to high speed.
Note that after a few tries the nvda starts to fail to read the results in these cells.
The focus is on cell a2 reading the result of a1
and vice versa as well.
the focus is on cell a2 reading the result of a1.
This is just one way I found to reproduce the problem.
More if you pick up a spreadsheet with multiple formulas in sequence
and start navigating these cells with arrows and not navigate very slowly fatally after a time of use nvda will start repeating the contents of the previous cell this already being focused on a new cell.
This occurs using the synthesizer one core voice Maria in Portuguese Brazil.
Using the speak ing this did not happen.
This occurs on an older machine but is still fast for other uses:
cori i3 6th generation.
4gb of ran
On a slightly faster machine:
cori i5 7th generation
8gb of ran
I did not notice this problem.
I also noticed this in this version of nvda
nvda_snapshot_threshold-17536,7972f457
In the version I used last week:
threshold-17431,57e4c0c2
I did not notice.
### Actual behavior:
nvda repeats the contents of the previous cell plus the focus is already in another cell.
### Expected behavior:
nvda should read the contents of the cell in focus correctly.
#### NVDA installed/portable/running from source:
install
#### NVDA version:
nvda_snapshot_threshold-17536,7972f457

#### Windows version:
10 18362.145
#### Name and version of other software in use when reproducing the issue:
excel
Office 365 MSO (16.0.11629.20164) 64 bits 

#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes
threshold-17431,57e4c0c2
seemed to work well.

follows excel with simple formulas and log.
[excel.txt](https://github.com/nvaccess/nvda/files/3266806/excel.txt)
[formula.xlsx](https://github.com/nvaccess/nvda/files/3266807/formula.xlsx)

**Comment by Qchristensen** [comment]
I can replicate this in Excel 365 (Office version 16.0.12527.20242) and NVDA 2019.3.1, as well as NVDA alpha-19780,29572fb4 (Snapshot from today, 11th March) on Windows 10 1903 build 18362.388.

Log fragment from pressing up arrow (moving focus from cell A2 to A1):

IO - inputCore.InputManager.executeGesture (14:20:37.173) - winInputHook (4244):
Input: kb(desktop):upArrow
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (14:20:37.189) - MainThread (20852):
Cancelling
DEBUG - synthDrivers.oneCore.SynthDriver._callback (14:20:37.199) - Dummy-17 (18052):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:20:37.199) - Dummy-17 (18052):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:20:37.199) - Dummy-17 (18052):
Queue empty, done processing
IO - speech.speak (14:20:37.248) - MainThread (20852):
Speaking [LangChangeCommand ('en_US'), '360', 'has formula', 'A2']
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:20:37.258) - MainThread (20852):
Begin processing speech
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (14:20:37.283) - MainThread (20852):
oleacc.AccessibleObjectFromEvent with window 461596, objectID 6762 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (14:20:37.283) - MainThread (20852):
oleacc.AccessibleObjectFromEvent with window 461596, objectID 6764 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (14:20:37.283) - MainThread (20852):
oleacc.AccessibleObjectFromEvent with window 461596, objectID 6765 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (14:20:37.283) - MainThread (20852):
oleacc.AccessibleObjectFromEvent with window 461596, objectID 6766 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (14:20:37.283) - MainThread (20852):
oleacc.AccessibleObjectFromEvent with window 461596, objectID 6768 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - synthDrivers.oneCore.SynthDriver._callback (14:20:39.069) - Dummy-17 (18052):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:20:39.069) - Dummy-17 (18052):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (14:20:39.139) - MainThread (20852):
Cancelling
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:20:39.144) - Dummy-17 (18052):
Queue empty, done processing
IO - inputCore.InputManager.executeGesture (14:20:39.181) - winInputHook (4244):
Input: kb(desktop):NVDA+f1

**Comment by Adriani90** [comment]
@Qchristensen could you please try to reproduce this in last Alpha? Thsi should be much better now I think.

**Comment by fernando-jose-silva** [comment]
I can still easily replicate the problem
In the annex that follows, in cell a1 there is a date 02/15/2006
when i press ctrl + home nvda reads this date as expected.
In cell a2 in cell a2 there is the date 17/05/2020
However when I press the down arrow I heard the contents of cell A1 again.
nvda alfa 20220
excel EXCEL.EXE, Microsoft Office 16.0.12730.20270
windows 10 19041.264 64bit
voice synthesizer windows one core portuguese Brasil Maria
auto performance power option.
core i3 
[excel.txt](https://github.com/nvaccess/nvda/files/4640094/excel.txt)
6100 notebook
ran 4gb

**Comment by Qchristensen** [comment]
I can't reproduce this, although testing it, when I look at the log I do have a few entries such as:

```
IO - inputCore.InputManager.executeGesture (16:32:46.237) - winInputHook (29108):
Input: kb(desktop):downArrow
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (16:32:46.238) - MainThread (27140):
oleacc.AccessibleObjectFromEvent with window 68532, objectID 8812 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (16:32:46.238) - MainThread (27140):
oleacc.AccessibleObjectFromEvent with window 68532, objectID 8814 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (16:32:46.239) - MainThread (27140):
oleacc.AccessibleObjectFromEvent with window 68532, objectID 8815 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (16:32:46.240) - MainThread (27140):
oleacc.AccessibleObjectFromEvent with window 68532, objectID 8816 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (16:32:46.240) - MainThread (27140):
oleacc.AccessibleObjectFromEvent with window 68532, objectID 8818 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (16:32:46.240) - MainThread (27140):
Cancelling
DEBUG - synthDrivers.oneCore.SynthDriver._callback (16:32:46.275) - Dummy-6 (27672):
Cancelled, stopped pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:32:46.276) - Dummy-6 (27672):
Calling sync on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:32:46.276) - Dummy-6 (27672):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:32:46.276) - Dummy-6 (27672):
Queue empty, done processing
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (16:32:46.280) - MainThread (27140):
oleacc.AccessibleObjectFromEvent with window 68532, objectID 8824 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (16:32:46.281) - MainThread (27140):
oleacc.AccessibleObjectFromEvent with window 68532, objectID 8826 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (16:32:46.282) - MainThread (27140):
oleacc.AccessibleObjectFromEvent with window 68532, objectID 8827 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (16:32:46.283) - MainThread (27140):
oleacc.AccessibleObjectFromEvent with window 68532, objectID 8828 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (16:32:46.283) - MainThread (27140):
oleacc.AccessibleObjectFromEvent with window 68532, objectID 8830 and childID 0: [WinError -2147467259] Unspecified error
IO - speech.speak (16:32:46.448) - MainThread (27140):
Speaking [LangChangeCommand ('en_GB'), 'a cell with text', 'overflowing', 'A4']
IO - inputCore.InputManager.executeGesture (16:32:46.453) - winInputHook (29108):
Input: kb(desktop):upArrow

```

In each case however, the correct text was read.

**Comment by Adriani90** [comment]
@fernando-jose-silva could you please test with last Alpha version of NVDA?

**Comment by fernando-jose-silva** [comment]
The
[excel19-6.txt](https://github.com/nvaccess/nvda/files/4806785/excel19-6.txt)
 problem continues.
log

**Comment by Adriani90** [comment]
@fernando-jose-silva are you still able to reproduce this issue with the last NVDA version?

**Comment by CyrilleB79** [comment]
Still reproducible here with NVDA 2022.4, disabled add-ons, not using UIA to access Excel sheets, excel 2016 ('16.0.5378.1000', Windows 10 20H2 (AMD64) build 19042.2486.

I can reproduce about 1 time out of 5 after alternating at high speed during at least 5 seconds.

The issue is not specific to ONeCore, I can reproduce with eSpeak, as well as with IBMTTS (add-ons enabled in this last case of course).

**Comment by CyrilleB79** [comment]
Unfortunately, it is still reproducible. Tested with:
* Today's NVDA snapshot (nvda_snapshot_alpha-27996,d8396f9b.exe)
* Disabled add-ons
* Excel version '16.0.16130.20306'

**Comment by Adriani90** [comment]
@fernando-jose-silva, @CyrilleB79 I notice a performance improvement when using MS Excel with NVDA 2024.2. Could you test whether this issue is still reproducible with NVDA 2024.2? I cannot reproduce.

**Comment by fernando-jose-silva** [comment]
Thank you very much, I haven't had this problem for a long time.

**Comment by CyrilleB79** [comment]
Cannot reproduce either on my side. Fixed.
