### ISSUE TITLE
Remove trailing 'I' or 'L' from number literals.

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#9701]
Python 3.7 does not support trailing 'I' or 'L' on number literals, these need to be removed.

**Comment by leonardder** [comment]
I assume 2to3 can do this for us when only applying the necessary fixers?

**Comment by feerrenrut** [comment]
I expect so. It would certainly be a good place to start.

**Comment by feerrenrut** [comment]
Fixed in https://github.com/nvaccess/nvda/pull/9719
