### ISSUE TITLE
Python 3: __hash__ must be defined for classes defining __eq__

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9708]
Hi,

Been meaning to file this for a while:

### Background:
Due to redesigned data model in Python 3, combined with hash randomization in Python 3.3 and later, any class defining __eq__ method must define __hash__ method (or set it to use facilities provided by the superclass). Without doing so Python 3 raises errors.

### Steps to reproduce:
Define a class in Python 2 and 3 that overrides equality operator (==) via __eq__ method.

### Actual behavior:
Error in Python 3.

### Expected behavior:
No errors.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Alpha, stable

#### Windows version:
Windows 10 Version 1903

#### Name and version of other software in use when reproducing the issue:
N/A

#### Other information about your system:
None

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes - Python 3 source code

### Solution:
Try using __hash__ method from superclass.

### Scope:
Many objects, including text infos, NVDA objects, etc.

**Comment by leonardder** [comment]
I recall that there is a hashable abstract in collections.abc. I think it makes sense to define that as a superclass for these classes.

**Comment by leonardder** [comment]
Fixed in #9757
