### ISSUE TITLE
COM Registration Tool: Modify to Register Additional Objects

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#9709]
When initially logging the ticket where I was having problems with Skype for Business 2016 (https://github.com/nvaccess/nvda/issues/7311), Jamie recommended a set of registry patches that could be run and several DLLs that could be re-registered. When performing the mentioned steps in the above ticket, the issues that I encounter with the installation of the Skype for Business 2016 client are immediately resolved upon a reboot.

When running the COM Registration Tool included with the latest NVDA Alpha snapshot, however, this isn't the case - NVDA remains broken until I manually import the mentioned registry files and re-register several DLLs. Would it be possible to add these files to the list of objects that are re-registered by the included NVDA tool?

**Comment by Adriani90** [comment]
cc: @michaelDCurran, @jcsteh

**Comment by Brian1Gaff** [comment]
This is also the case with the non reading of dialogues in Dropbox, but I do 
not know the actual bits fixed. All I can tell you is that avastclear caused 
the issue and  a reinstall of windows fixes it , but the registration tool 
as it stands does not.
 I have one machine fixed and one still with the problem. is there any way I 
can compare the registry files in some way to find where the differences are 
I wonder?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by DrSooom** [comment]
@Brian1Gaff: You can save/export keys from the Windows Registry Editor and compare them with WinMerge or Notepad++, as the *.reg files are nothing than simple text files. But this procedure is of course not really convenient. Furthermore: Be always careful in using the Windows Registry Editor. Before changing anything here, please always create an image-based backup of the whole system.

**Comment by lukaszgo1** [comment]
@elliott94 I'd like to take a look at this, and fix if I can? Could you please tell me on which version of Windows (and build if it is Windows 10) are your experiencing this? Is it still Win 7 like in #7311?

**Comment by elliott94** [comment]
> 
> 
> @elliott94 I'd like to take a look at this, and fix if I can? Could you please tell me on which version of Windows (and build if it is Windows 10) are your experiencing this? Is it still Win 7 like in #7311?

Thank you. :) So, to reproduce - this works on either Windows 7 X64 and tested with Windows 10 X64 (builds 1703 and 1803):

1. Install a fresh copy of Windows, and a copy of NVDA (either snapshot or release build is fine)

2. Download and install the Skype for Business 2016 Basic client X64 from the following URL - I can provide a direct link to the executable if required:

https://www.microsoft.com/en-us/download/details.aspx?id=49440

You'll notice that immediatley after being installed, NVDA begins to stop reading certain controls - as an example, the right-click menu that appears when either right-clicking or hitting the Applications key on a file/folder from within Explorer

3. Run the COM Registration Tool from within the Tools menu of NVDA and reboot - you'll notice that the problem remains

4. Finally, follow the instructions outlined in #7311 and reboot - you'll notice that the issue is fixed

Thanks.

**Comment by lukaszgo1** [comment]
@elliott94 I've tried to reproduce the problem (without a success unfortunately) as follows:
1. Installed clean Windows 7 x64 pro SP1.
2. Installed latest NVDA alpha.
3.  on a second machine downloaded Skype For Business from the link above. The exact link to the install file which i ended up with is https://download.microsoft.com/download/8/7/E/87E24B50-9C85-4B1D-A581-94AA037803F8/LyncEntry_bypass_ship_x64_en-us_exe/lyncentry.exe
4. Installed it on the first machine.
5. Tried reading taskbar, context menu in Explorer, and a page in IE - all worked.
6. Rebooted.
7. Tried all the above still NVDA reads as expected.


Could you please give the exact link to the install file that you've used. Is there any step that I've missed? Perhaps Windows image from which you're installing is special somehow.

**Comment by elliott94** [comment]
Apologies - try this link, it looks like Microsoft have updated their installation package. This is the one that causes breakage:

https://download.microsoft.com/download/8/7/E/87E24B50-9C85-4B1D-A581-94AA037803F8/lyncentry_4417-1000_x64_en-us.exe

**Comment by lukaszgo1** [comment]
I still cannot reproduce it. @elliott94 In #7311 you've mentioned reimaging. Are you using modified installation image when installing Windows? If so is there a chance of accessing it?

**Comment by elliott94** [comment]
Unfortunately this image is deployed by my organisation, so not accessible. Just to check - are you using an original ISO/DVD to install Win 7 SP1? Do you by any chance have a Windows 10 ISO that we can test with?

**Comment by lukaszgo1** [comment]
> 
> 
>  Just to check - are you using an original ISO/DVD to install Win 7 SP1?

Yes


>  Do you by any chance have a Windows 10 ISO that we can test with?

In the mean time I've tried on clean install of Windows 10 1703 x64, but cannot reproduce it there either. If it helps, and if you're willing to test I can share these iso''s with you. To ensure that I am not missing anything I always perform actual install, and then directly so no drivers, no updates, no internet connection install NVDA and then SFB.

**Comment by elliott94** [comment]
Ok - thanks for all of your efforts. With Win 7 in particular, do you have UAC enabled or disabled? If enabled, would you be able to disable to ensure that NVDA is running as administrator, and then reinstall the SFB 2016 client using admin too? Disabling UAC will force everything to install with elevated perms in either case.

Thanks.

**Comment by lukaszgo1** [comment]
Disabling UAC made no difference. This issue is really strange not only because I cannot reproduce the symptoms on my machine, but also because COM Registration Fixing Tool performs exactly the same commands as in #7311, and performing them manually fixes it for you. Would you be able to set log level to debug,, execute the COM Registration Fixing Tool again and post the log here? I am not sure it'll help, however the tool performs some logging, and perhaps log would tell us something interesting.

**Comment by elliott94** [comment]
Will give this a go when I'm next on the machine in question. Just out of interest - if you install the SFB 2016 client and then the latest release build of Firefox, does NVDA read web page content for you when you browse?

**Comment by JulienCochuyt** [comment]
Might be related: I have a client working on migrating from Windows 7 to 10.
After a fresh install of their Windows 10 master and any version of NVDA from 2016.4 up to 2019.2, IAccessible is broken in registry.
Manually merging `oleaccProxy.reg` into the registry's WOW6432Node fixes the issue.
Turns out that NVDA's COM Registration Fixing Tool is for some reason unable to merge `.reg` files,  but does not detect any error as the exit code of `regedit` is 0.
Investigation is still in process, but our culprit of choice would be the antivirus software shipped along with that particular Windows 10 master.

cc @rthxy

**Comment by Adriani90** [comment]
cc: @feerrenrut

**Comment by lukaszgo1** [comment]
@JulienCochuyt wrote:
[...]
> Manually merging `oleaccProxy.reg` into the registry's WOW6432Node fixes the issue.
> Turns out that NVDA's COM Registration Fixing Tool is for some reason unable to merge `.reg` files, but does not detect any error as the exit code of `regedit` is 0.
> Investigation is still in process, but our culprit of choice would be the antivirus software shipped along with that particular Windows 10 master.



It turns out the path to the registry files in COMRegistrationFixes is wrong (it points out to "COMRegistryFixes\*.reg" rather than to "COMRegistrationFixes\*.reg".
I'll submit a fix for this during this weekend.

**Comment by lukaszgo1** [comment]
@elliott94 Would you be able to test this with latest Alpha? I believe this should be fixed by #11494 but don't want to close it without a confirmation.

**Comment by elliott94** [comment]
Looks much better, thank you. :) Would you like me to close?

**Comment by lukaszgo1** [comment]
Yes please. I don't have such permissions whereas you, as an original reporter, do.

**Comment by elliott94** [comment]
Now fixed in #11494.
