### ISSUE TITLE
Material-UI Radio buttons are interacting with delay

### ISSUE THREAD

**Issue by erickbelfy** [nvaccess/nvda#9717]
### Steps to reproduce:
Given a list of  Material-UI Radio Input, you can try using this [link](https://codesandbox.io/s/determined-tharp-8v22f) while trying to navigate through the nodes using NVDA with firefox (both latest versions) NVDA interacts (either the voice and the speech-debugger) in a particular way.

### Actual behavior:
When we focus the editor on the radio input it says  "radio button not checked 1/3 or 2/3 or 3/3"

Let's pretend that i select the radio 1/3. The interaction says "checked". Then, i navigate to the radio 2/3 and return to the previous one, the reader is saying "radio button not checked 1/3 " and after a couple of miliseconds the reader says "checked"

### Expected behavior:
the reader should identify the when a radio input is checked and reads "radio button checked 1/3 " if the radio input carries the property checked or if it carries a value.

#### NVDA installed/portable/running from source:
NVDA installed

#### NVDA version:
2019.1.1

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
Firefox 67.0.1

**Comment by Adriani90** [comment]
This works correctly now with NVDA alpha-20220,1c4519a6 and Firefox 76. I am closing as works for me.
But please don't hesitate to comment on this if you think I misunderstood the issue and we can reopen it afterwards.
