### ISSUE TITLE
Virtual buffer does not process the entire Facebook.com page with Seamonkey

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#972]
**Reported by dgoldfield on 2010-10-08 12:50**
I am using Seamonkey 2.0.8.  If I go to www.facebook.com with this browser NVDA's virtual buffer only shows the first two or three lines of the page, when I use my arrow keys, ending with the line that says "chat 0."  However, if I use the tab key I am able to move through the various links and form controls.  I even hear NVDA play the camera sound when moving into an edit box indicating that I am temporarily out of browse mode.  I think I was once able to get NVDA to display the full page by restarting NVDA, but this is not consistent and the last time I tried doing that the virtual buffer still only let me read the first few lines using arrow keys.  This is a relatively new problem and it may have started with Seamonkey's latest version.

**Comment by ehollig** [comment]
Is this still the case? The latest version of SeaMonkey is 2.46.

**Comment by leonardder** [comment]
This issue is abandoned for more than six years, furthermore, Facebook has changed multiple times since then. Closing. If this is still the case, please provide a new issue with steps to reproduce, and at least try to reproduce with multiple browsers.
