### ISSUE TITLE
Brltty/Python 3: R6034 error when running unittests

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9721]
Hi,

Related to #9720 but more major than that:

### Steps to reproduce:
1. Fetch threshold_py3_staging branch and an eventual PR for 9720.
2. Run scons tests.

### Actual behavior:
Microsoft Visual C++ R6034 (an application attempted to load a library incorrectly) error is thrown whiel running braille display gesture integrity test.

### Expected behavior:
No errors

#### NVDA installed/portable/running from source:
Source

#### NVDA version:
Python 3 version

#### Windows version:
Windows 10 Version 1903

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
None

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Master - no errors.

### Cause:
According to numerous sources, this is caused by repeated insertion of msvcr90.dll into path used by the executable. In this case, brltty is the culprit due to really old brlapi binding in use, which will attempt to insert msvcr90.dll when in fact this is already part of NVDA source path. Raising a runtime error in Brltty braille display module mitigates to some degree.

### Solution:
* Short-term: skip braille display gesture test with unittest.skip decorator with a justification beside it.
* Long-term: upgrade to newer brlapi binding, which won't actually resolve this problem, since 0.7 (latest release) ships with Python 3.6 pyd file when we need 3.7 pyd file.
* Really long-term solution: evaluate necessity of including msvcr90.dll in the source code path.

Thanks.

**Comment by leonardder** [comment]
I don't think we need msvcr90.dll at all. The MSVC 9.0 redistributable was a dependency of Python 2.7. brlapi is still at the 2.7 version, so Python 3.7 tries to import a python 2.7 pyd file and fails expectedly.

I think I prefer closing this in favour of #8725

**Comment by josephsl** [comment]
Hi,

@MichaelDCurran, any thoughts please?

**Comment by leonardder** [comment]
@josephsl: Could you try this with https://github.com/nvaccess/nvda-misc-deps/pull/14 checked out in miscdeps? That also removes the dependency on msvc90. Make sure to clean your source distribution

**Comment by josephsl** [comment]
Hi,

No errors. Note that just modifying one of brlapi0.7 DLL or CP37 C extension will work, but for sake of completeness, it would be best to update both the C extension and the DLL. Also, MSVC9 files are still copied by sconstruct, so we may need to take care of removing that step if and only if there is nobody in source code using these runtime DLL's.

Thanks.

**Comment by leonardder** [comment]
fixed in #9812
