### ISSUE TITLE
Windows 2016/2019 NVDA is reading the text "Requiring the following for Enrollment" twice

### ISSUE THREAD

**Issue by jerryfu823** [nvaccess/nvda#9732]
### Steps to reproduce:
This issue is found in Windows Server 2016/2019 which has the role "Certificate Authority" which in an ADCS (Active Directory Certificate Service) environment. To reproduce the bug, "Certificate Authority" role should be added through "Service Manager", and configured as "Enterprise CA".

1) In Windows Search box, lookup "CertSrv.MSC" and run the command;
2)Tab till tools-->certification authority and press enter​
3)Activate Certificate Templates tab & Select Manage and press enter
4)Activate any one the item in the grid & select "Duplicate Template" and press enter
5)Start Screen Reader
6)Verify if Screen Reader is reading all the contents, controls, links, images properly.

###
"Require the following for enrollment" is read twice.
![Bug_20580686_NVDA is reading the text require the following for enrollment two times](https://user-images.githubusercontent.com/19564230/59392766-b1f24480-8d2d-11e9-8e33-782c08f907cc.jpg)
### Expected behavior:
"Require the following for enrollment" is read only once.

#### NVDA installed/portable/running from source:
NVDA installed.

#### NVDA version:
2019.1.1

#### Windows version:
Windows 2016/2019
#### Other information about your system:
Role "Certificate Authority" should be added through "Service Manager", and configured as "Enterprise CA".

### Other questions
No.

# Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### the developer info for the problematic control (NVDA+F1)
Please contact my working email zhfu@microsoft.com. 
#### a textual description of the issue graphic, 
When tab to the page "Issance Requirements", NVDA start to read the contact of the page, however it reads the text "Require the following for enrollment" twice.

#### testing results with Narrator.
Narrator works well with this dialog and read the dialog as expected, i.e., "Require the following for enrollment" is just read once.

**Comment by josephsl** [comment]
Hi, for this one and the previous issue, we need three things please: the developer info for the problematic control (NVDA+F1), a textual description of the issue graphic, and testing results with Narrator. Thanks.

**Comment by jerryfu823** [comment]
@josephsl , bug is updated with the info you requested. Please feel free to let me know anyting I could assist. Thanks.

**Comment by Adriani90** [comment]
@jerryfu823 could you please give an update on how it is now with NVDA 2020.1? Thanks.

**Comment by Adriani90** [comment]
Wid didn't get any updates from the initial author since more than two years now, and we cannot easiliy reproduce this issue since people would need access to an enterprise account. I am closing this as abandoned. If you have any updates on this, please comment on it and we can reopen.

Please test with NVDA 2023.1 if this is still an issue for you.
