### ISSUE TITLE
NVDA freezes for a few seconds

### ISSUE THREAD

**Issue by bingen13** [nvaccess/nvda#9741]
On seemingly random intervals, NVDA stops responding for a few seconds. Afterwards it comes back to life. Sometimes, though not always, processing of modifier keys will be affected, so NVDA-1 for example gets processed as 1.

### Steps to reproduce:

Launch NVDA. Wait for a few minutes doing things. Unfortunately I haven't found any pattern to the event.

### Actual behavior:

NVDA stops responding to keyboard commands. Both Braille and voice are frozen for a few seconds. Afterwards, NVDA resumes responding. At that point, NVDA commands may or may not work. F11 for NVDA Remote usually won't, though it will say controlling remote computer, but commands will not be passed through.

### Expected behavior:

NVDA responds to keyboard commands and focused changes in a timely fashion. Braille and voice continue operating. NVDA commands are correctly executed.

#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2018.3.2
#### Windows version:
Windows 7 Service Pack 1 64 bits
#### Other information about your system:
NVDA plug-ins are Resource Monitor and NVDA Remote.

````
Relevant quote from log file:

DEBUGWARNING - watchdog._watcher (10:28:58.440):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 478, in run
  File "IAccessibleHandler.pyo", line 900, in pumpAll
  File "IAccessibleHandler.pyo", line 757, in processForegroundWinEvent
  File "IAccessibleHandler.pyo", line 532, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyo", line 38, in getNVDAObjectFromEvent
  File "IAccessibleHandler.pyo", line 342, in accessibleObjectFromEvent
  File "oleacc.pyo", line 240, in AccessibleObjectFromEvent

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (10:28:58.546):
oleacc.AccessibleObjectFromEvent with window 132910, objectID -4 and childID 0: 
DEBUGWARNING - watchdog._watcher (10:28:59.046):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 478, in run
  File "IAccessibleHandler.pyo", line 883, in pumpAll
  File "IAccessibleHandler.pyo", line 757, in processForegroundWinEvent
  File "IAccessibleHandler.pyo", line 524, in winEventToNVDAEvent
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

DEBUGWARNING - core.CorePump.run (10:28:59.348):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyo", line 478, in run
  File "IAccessibleHandler.pyo", line 883, in pumpAll
  File "IAccessibleHandler.pyo", line 757, in processForegroundWinEvent
  File "IAccessibleHandler.pyo", line 524, in winEventToNVDAEvent
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 351, in _isUIAWindowHelper
  File "watchdog.pyo", line 195, in sendMessageCallCanceller
CallCancelled
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (10:28:59.598):
oleacc.AccessibleObjectFromEvent with window 132932, objectID 1 and childID 0: [Error -2147467259] Error no especificado
DEBUG - appModuleHandler.cleanup (10:29:00.848):
application acrord32 closed
DEBUG - treeInterceptorHandler.update (10:29:01.095):
Adding new treeInterceptor to runningTable: <virtualBuffers.adobeAcrobat.AdobeAcrobat object at 0x05AE08D0>
DEBUG - virtualBuffers.VirtualBuffer._loadBuffer (10:29:06.993):
Buffer load took 5.896 sec, 59583 chars
````

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Unfortunately not. Can try portable versions but cannot easily install other versions as it's a work computer where I don't have administrative privileges.

**Comment by DrSooom** [comment]
Are you using a Bluetooth keyboard? And please disable the NVDA add-on "Resource Monitor" and compare the situation. Thanks.

**Comment by bingen13** [comment]
No, I'm using a normal wired USB keyboard. I'll try without the Resource Monitor addon on Monday.

**Comment by Adriani90** [comment]
Please try the addon bluetooth audio. It is on the official website www.addons.nvda-project.org
The name of the addon is confusing. It helps when the sound card goes in standby every few seconds which I supose it happens in this case. The addon works for every audio device regardless if it is a bluetooth device or not.

**Comment by bingen13** [comment]
I'll try it, though I'm pretty sure it's not a sound card issue; but I'll report with the results of that, too.

**Comment by Brian1Gaff** [comment]
I have noticed this happen if you are working as a windows update is coming 
down in the background, or indeed other background things are going on, say 
a backup or something.
 Quit why it sometimes seems to stop bits of nvda from working is not clear, 
but generally the thing needs a reboot, ie the whole machine, not nvda which 
makes me suspect that its a windows thing, not an nvda thing.
 It happens on windows 7 so not 10 specific. This last update arrived here 
on wednesday and did this to me whhile I was trying to edit a word file.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by Brian1Gaff** [comment]
If he is right and it affects certain operations in nvda, ie those that rely 
on info from windows, then my bet is on a backgrounndo update or back up.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by bingen13** [comment]
I've tried without Resource Monitor addon and the problem persists.

I don't think it's a Windows issue, because if it were, it wouldn't go associated to the Remote F11 command behaving strangely. Or rather, if it's a Windows issue, something odd must be going on with NVDA as well.

**Comment by DrSooom** [comment]
@bingen13: Which Anti-Virus-/Malware-Solution is installed? Maybe some specific files are blocked by that software.

And is Mozilla Thunderbird running? I have plenty RSS-Feeds subscripted in Thunderbird, which causes slowdowns for up to 20 seconds every time when all feeds are updated together.

**Comment by bingen13** [comment]
Will check what AV is running. Thunderbird is not installed.

**Comment by Adriani90** [comment]
Did you try the addon bluetooth audio?

Von meinem iPhone gesendet

**Comment by Adriani90** [comment]
@bingen13 are you still having this issue in NVDA 2019.2.1?

**Comment by bingen13** [comment]
I'm still having the issue, though it seems less frequent. I am sure it's not an audio processing issue, because while NVDA is frozen I've heard other sound notifications coming through.

**Comment by Adriani90** [comment]
@bingen13 could you please test with NVDA last alpha version or with NVDA 2020.1 if this is still reproducible?
The last alpha version can be downloaded here:
https://www.nvaccess.org/files/nvda/snapshots/
