### ISSUE TITLE
Charging Status/Screen Orientation: Make Automatic Announcement Configurable

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#9742]
For several years now, NVDA has automatically announced certain status events. These are:

When the AC adaptor for portable computers is connected/disconnected, and the current charge status of the battery

The screen orientation when this changes

The screen size when this changes (in pixels)

Would it be possible to add several configuration options so that users can change whether the status of these options is automatically announced? As an example, a user may wish to automatically be told when their AC adaptor is connected/disconnected, but the screen orientation may not be of any use to them.

**Comment by Adriani90** [comment]
I vote against this because especially the screen orientation can be changed by pressing key strokes. For example if you use an intel grafic card, the screen orientation changes when you are not in a table and press ctrl+alt+arrow keys. It also changes when you change the window with alt+tab into a table but you press ctrl+alt+arrow keys too fast and there is not enough time for the focus to land on a cell in a table. This happens alot on slow pcs.
But in general, we should be careful not to overwelm users with tens of unnecessary additional settings
Is the reporting of such things so stressful for you that you want to exclude them from default? Or what is the reason behind this?

**Comment by Adriani90** [comment]
Also the reporting that the batery is loading when you plug in a charging cable is very useful because this tells you actually that the cable or the batery is still working properly.

**Comment by Adriani90** [comment]
I mean these kind of reportings occur very rarely. Usually you don‘t change the screen orientation or plug in and out a charging cable every  2 minutes or so.

**Comment by Adriani90** [comment]
I am closing this as won't fix. If you have convincing arguments to implement this, please comment on this isue and we can reopen the discussion.

**Comment by elliott94** [comment]
Apologies for not replying to this sooner.

We already give users lots of customisation options; the argument for not adding this could also be used, for example, when discussing the fact that we allow users to choose whether spelling errors are automatically announced; using the logic that all users would want to know about charging and screen status, we could also assume that all users would also want to know if they have accidentally mistyped a word. The same goes for startup sounds - I personally find it useful to know when NVDA is in the process of loading, but other users may not. I think that we should at least consider this and get further input.

**Comment by Adriani90** [comment]
I would not compare this with spelling errors. Spelling errors are encountered by users much more often than changing the screen orientation. If we start to implement a checkbox for every expression reported by nvda, then we overfill the dialogs with settings which are merely used. The strength of NVDA is that the settings are well structured and that the settings are aligned to the user impact. This feature would not really change the user experience in NVDA given the fact that this reporting occurs very rarely. But maybe @lukaszgo1 or @feerrenrut have other arguments which would justify stronger such an option?

Von meinem iPhone gesendet

**Comment by XLTechie** [comment]
While I am usually in favor of more choice, and giving users all the control 
they want, in this case I agree with @Adriani90. It just seems 
unnecessary to make such a relatively rare indicator switchable.  It could be 
done with some sort of add-on, I suppose.
