### ISSUE TITLE
Remove modules imports that are not used in a given module

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9754]
Hi,

Discovered while doing some more work on Python 3 syntax changes:

### Is your feature request related to a problem? Please describe.
There are some modules importing one or more things that it won't use. This is caused by numerous merges and splits, and in case of speech refactor, conversion of speech module into a package.

For example, in speehc main module, we have:

from six import with_metaclass

And in config main module:

from six.moves import CStringIO as String IO

Both of these modules are imported but never used in respective modules.

### Describe the solution you'd like
It would be best to remove unused imports when they are truly not needed.

### Describe alternatives you've considered
Leave the source code as is.

### Additional context
If accepted, this work can take place either during Python 3 transition stage 1 (source code edits/now) or shortly after.

Thanks.

**Comment by josephsl** [comment]
Hi,

And yes, I'll take care of this shortly after 2019.2 stable comes out. Also, please let us know if you find other instances of module imports not being used by a module.

Thanks.

**Comment by Adriani90** [comment]
@josephsl since this does not affect translators, are you still thinking to touch this for 2019.3?

**Comment by josephsl** [comment]
Hi, too late for 2019.3 – perhaps we should have a talk about this while 2020.1 is under development. Thanks.

**Comment by Adriani90** [comment]
ok, maybe also cc: @michaelDCurran

**Comment by feerrenrut** [comment]
Please note, some imports are provided for backwards compatibility, though they should have comment to state that is the case. Flake8 should pick up newly added / changed import lines that aren't used. I would prefer not to have changes across lots of files just to remove unused imports. However, if you are already delivering a change to a file, you can clean up the imports. But do think about backwards compatibility in the process.

**Comment by josephsl** [comment]
Hi,

CC @SeanBudd, I assume our Flake8 to Ruff conversion took care of this one. If yes, let's close this one and open new issues in case Ruff finds unused imports again.

Thanks.

**Comment by seanbudd** [comment]
Yes - there's either noqa comments or the imports have been removed.
