### ISSUE TITLE
UIA in Word: Comments are not read when pressing NVDA+Alt+C

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#9755]
### Steps to reproduce:

1. In Enhanced NVDA options, turn on UIA for Word.
2. Create a new document in Word, write something, then add a comment. Basically, do what is described in Chapter 12.1 and 12.2 of the NVDA with Microsoft Word training.
3. Now, focus the word or text again that has the text and press NVDA+Alt+C to read the comment.
4. Open NVDA Advanced Settings, and turn off UIA for Word.
5. Repeat step 3 with the document still open.

### Actual behavior:

1. After step 3, Nothing is spoken.
2. After step 5, the comment is spoken as expected.

### Expected behavior:

NVDA would read the attached comment in both cases.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

2019.1.1 and also 2019.2Beta and current alpha versions.

#### Windows version:

Windows 10 19h1.

#### Name and version of other software in use when reproducing the issue:

Word in Office 365.

#### Other information about your system:

None applicable.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

See above. All that support this feature.

**Comment by zstanecic** [comment]
This is a duplicate issue, covered by a pull request. 
see issues created by me. 
Thanks!

**Comment by MarcoZehe** [comment]
OK, this is a dupe of #9285 and will be fixed by #9631 and can be closed.
