### ISSUE TITLE
Unable to expand button more within a message in gmail

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9765]
### Steps to reproduce:
Open a message in gmail.
Use the default view mode.
With the message open to speed up you can press 3 to go to the level 3 header.
With the arrows until
menu button submenu more.
Press enter.
### Actual behavior:
Nothing happens.
### Expected behavior:
the button submenu opens and allows navigation with the up and down arrows through the options.
If you switch to focus mode you can expand the options.
#### NVDA installed/portable/running from source:
install
#### NVDA version:
alpha-17611 
#### Windows version:
10.0.17763.404
#### Name and version of other software in use when reproducing the issue:
chrome
75.0.3770.90
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
[gmail.txt](https://github.com/nvaccess/nvda/files/3297533/gmail.txt)

**Comment by fernando-jose-silva** [comment]
nvda is set to not automatically switch to focus mode.

**Comment by charmarkk** [comment]
I'm having this issue with a popup/dropdown (whatever way you want to say it) menu on an internal application as well. Same exact thing, enter doesn't open the menu or anything. With NVDA shut off, it works as expected.

If I have NVDA switch into focus mode, then it works and I can both expand the menu and use arrow keys to get around and select and open a listed link.

NVDA 2019.1.1, Firefox 68, Windows Version 10.0.16299 Build 16299.

**Comment by Adriani90** [comment]
This is still an issue. The button does not expand the menu in browse mode in Firefox. In Crhome you have to press multiple times enter and sometimes the menu expands but you need to be very very patient :-).
@jcsteh, @MarcoZehe maybe you have some hints at least for Firefox?
It might also be bad web authoring. cc: @aleventhal

**Comment by jcsteh** [comment]
This works as expected for me in Firefox with NVDA's default setting of switching to focus mode for focus changes. Focus mode is how menus like these are intended to be navigated, so I don't really see this as a bug. For what it's worth, this Gmail menu is kinda weird and renders only one item at a time, and it also gets rendered as a child of the button.

**Comment by fernando-jose-silva** [comment]
I believe that for advanced users switching to focus mode is a logical thing.
 But I would like to point out that to explain to novice users that they have to go to focus mode to manipulate the menu controls, it is extremely difficult.

Enviado do meu iPhone

**Comment by jcsteh** [comment]
Novice users won't have disabled auto switching to focus mode, so they
don't have to switch to focus mode. NVDA will do it for them when
appropriate.

**Comment by Adriani90** [comment]
Since auto switching to focus mode is enabled by default, I agree with Jamie here. This does not have an impact on novice users. I am closing this issue for now.
