### ISSUE TITLE
NVDA Chinese input error

### ISSUE THREAD

**Issue by man0528** [nvaccess/nvda#9772]
[nvda.log](https://github.com/nvaccess/nvda/files/3303956/nvda.log)

In NVDA version 17633, NVDA warns when typing Chinese in edit blanks of files renaming of windows Explorer. 
### Steps to reproduce:
1. Start NVDA. 
2. Install Chinese input status for windows 10. 
3. Select any file in Windows Explorer(Including desktop items). 
4. Press F2 or open application menu to activate renaming action. 
5. Switch to Chinese input status. 
6. Type with a keyboard. 

### Actual behavior:
Error warning and reporting nothing. 

### Expected behavior:
Reporting typed characters.

#### NVDA installed/portable/running from source:
Both in Installed version and portable version

#### NVDA version:
1. NVDA 2019.2 beta 1, 
2. NVDA Beta 17522, 
3. NVDA Beta 17633. 

#### Windows version:
Windows 10Ver1903 (64Bit) build 18362.175

#### Name and version of other software in use when reproducing the issue:
Windows explorer

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This error begins with nvda Alpha-16953, So, It is speculated that the occurrence of this error may be related to [PR 8643](https://github.com/nvaccess/nvda/pull/8643).

**Comment by dingpengyu** [comment]
cc @josephsl and
@leonardder

**Comment by nishimotz** [comment]
It seems Japanese IME is related as well.

**Comment by lukaszgo1** [comment]
@man0528 @nishimotz @dingpengyu Could you please download https://ci.appveyor.com/api/buildjobs/hi3gm2r5dvy7ly0d/artifacts/output%2Fnvda_snapshot_pr9779-17731%2C8c7a5621.exe and check if the issue is fixed?

**Comment by dingpengyu** [comment]
> @man0528 @nishimotz @dingpengyu Could you please download https://ci.appveyor.com/api/buildjobs/hi3gm2r5dvy7ly0d/artifacts/output%2Fnvda_snapshot_pr9779-17731%2C8c7a5621.exe and check if the issue is fixed?
hi lukaszgo
Thank you for your work, the problem has been solved

**Comment by man0528** [comment]
Thank you very much for @lukaszgo's efforts.The problem was solved.

**Comment by lukaszgo1** [comment]
Thanks for your confirmations.
