### ISSUE TITLE
Some UIA tooltips aren't reported

### ISSUE THREAD

**Issue by francipvb** [nvaccess/nvda#9777]
### Steps to reproduce:

Note that I've tested this with Visual Studio 2019

1. Ensure NVDA is configured to read tooltips by checking the first checkbox in NVDA-&gt;Preferences-&gt;Settings-&gt;Object presentation.
1. Also ensure that simple review mode checkbox is not checked under review cursor in NVDA settings dialog.
1. Open Visual Studio and either create a new project or open one.
1. In a code editor for any file with IntelliSense support, open suggestions popup.
1. Select any item with documentation.
1. With object navigation commands, select the foreground window and enter the first child of it's first child.
1. Open the log viewer with <kbd>NVDA+f1</kbd>.

See these two log chunks:

Class MRO:

```
Python class mro: (<class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
```

UIA class:

```
    UIA className: ToolTip
```

Note that the tooltip is not reported.

Another test:

1. Open Visual Studio and create a new WPF project.
1. In the main window, add a control and set his tool-tip.
1. Run without debugging with <kbd>CTRL+f5</kbd>.
1. Trigger the tool-tip by hovering the mouse.

Same results.

### Actual behavior:

Tool-tips should be reported.

### Expected behavior:

The notification behaviour class should be added to the class MRO as it has the default implementation for tooltips. This should be reported.

#### NVDA installed/portable/running from source:

64 bits standard computer.

#### NVDA version:

alpha-17678,535c9382

Also tested with alpha-17832,7dd122b7.

#### Windows version:

Windows 10 1809

Also tested with version 1903 with same results.

#### Name and version of other software in use when reproducing the issue:

Visual Studio 2017 (15.9.11), 2019 (16.1.5 and 16.2 preview 3)

In fact this doesn't applies to a specific application, but to one or more UIAutomation frameworks.

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by francipvb** [comment]
CC @josephsl @feerrenrut @leonardder 

CC @AmadeusW I think you'll interested on tracking this...

**Comment by AmadeusW** [comment]
To anyone working on this - Please use [Visual Studio 16.2 preview 3](https://visualstudio.microsoft.com/vs/preview/) (shipped today) which has an important update.

I have set the Automation Name property on the ToolTip, such that the UIA_ToolTipOpened event now contains the content of the tooltip. I verified this using AccEvent. Also, Microsoft Narrator correctly reads the tooltip content. However, NVDA does not read it.

**Comment by francipvb** [comment]
Hello @AmadeusW,

> 
> 
> To anyone working on this - Please use [Visual Studio 16.2 preview 3](https://visualstudio.microsoft.com/vs/preview/) (shipped today) which has an important update.

Checked out Visual Studio Preview some minutes ago and playing with it.

> I have set the Automation Name property on the ToolTip, such that the UIA_ToolTipOpened event now contains the content of the tooltip. I verified this using AccEvent. Also, Microsoft Narrator correctly reads the tooltip content. However, NVDA does not read it.

Note that the Tool Tip issue is not only for Visual Studio, but all Wpf tool tips I believe.

I need to play a bit more to confirm this.

Regarding the documentation tooltip:

* ToolTipOpened is fired twice when the item is highlighted.
* The name of the selected item is not set when an item has documentation such remarks or parameter information. You can verify this by selecting AccessViolationException of .Net framework or .Net Standard.

@josephsl I don't want to touch NVDA's core UIAutomation implementation yet until I know more about the codebase and UIAutomation. Can you look into this?

Cheers,

**Comment by francipvb** [comment]
Hello again,

> Hello @AmadeusW,
> 
> (...)
> > I have set the Automation Name property on the ToolTip, such that the UIA_ToolTipOpened event now contains the content of the tooltip. I verified this using AccEvent. Also, Microsoft Narrator correctly reads the tooltip content. However, NVDA does not read it.
> 
> Note that the Tool Tip issue is not only for Visual Studio, but all Wpf tool tips I believe.
> 
> I need to play a bit more to confirm this.

Confirmed. To reproduce do the following:

1. Create a new WPF application.
1. Add a tooltip to any control.
1. Run the project with <kbd>CTRL+F5</kbd>.
1. Do an action to trigger the tooltip.

> Regarding the documentation tooltip:
> 
>     * ToolTipOpened is fired twice when the item is highlighted.

This does not happen with Wpf standard tooltips.

Cheers,

**Comment by francipvb** [comment]
Related to pr#8124

**Comment by josephsl** [comment]
Hi,

Now that #8124 is part of NVDA master, please see if it resolves some of this (note that latest master branch is Python 3, so anything not ready for Python 3 will fail).

Thanks.

**Comment by christopherpross** [comment]
Hi,
great work, now the tooltips for example in the intellisens list are read out. But in visual studio, there are also many other useful information, e.g. the parameternames and so on. I think this is a issue on the site of the program, I reported this problem here:
https://developercommunity.visualstudio.com/content/problem/704122/accessibility-display-parameterinfo-and-other-rele.html

Maybe we can find a solution to gever to get all useful informations from visual studio and enhance the workflow for blind coder.

all the best,
Christopher

**Comment by Adriani90** [comment]
Thanks very much @christopherpross for reporting. Users like you are really game changers. Thanks Joseph also for your great work.
I am closing this as works for me.
