### ISSUE TITLE
Chromium-based browsers: buggy text navigation in multiline edit fields

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#9786]
### Steps to reproduce:

1. Open a Chromium-based browser, for example Chrome Version 75.0.3770.100, or MS Edge Dev version 77.
2. Find a multiline text field, for example when creating a new issue in Github, and navigate by word or line.

### Actual behavior:

Wrong lines are spoken when arrowing up and down, and wrong words are spoken when moving by word. Also, often, character positions are reported wrong, making editing a dangerous task with unpredictable results.

### Expected behavior:

None of the above, editing should be normal.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

Observed in alpha-17750,27694a31. Does not occur in alpha-17743,5883af56.

#### Windows version:

19h1.

#### Name and version of other software in use when reproducing the issue:

Chromium-based browsers.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

See above, a regression from a checkin of #9773. CC @codeofdusk and @michaelDCurran.

**Comment by Living4God1991** [comment]
I can confirm this. It's been a problem for a while now, although I can't remember how long. It happens in all versions of Chrome and Edge with alpha versions of NVDA as well as stable. I apologize if this shows up twice. I replied via email but it doesn't look like it worked.

**Comment by MarcoZehe** [comment]
This was fixed by the reverting of #9773 and can be closed.
