### ISSUE TITLE
System tests: update dependencies

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9799]
### Is your feature request related to a problem? Please describe.
Currently, due to compatibility reasons, system tests relies on older dependencies for Python 2 compatibility. Every time system tests dependencies were updated, Appveyor build fails because they were updated to a non-Python 2 version.

### Describe the solution you'd like
As part of #9797 and #9798 work, it is proposed to modify system tests dependencies to remove old releases - that is, fetch latest modules (no equals qualifiers).

### Describe alternatives you've considered
Keep using current releases.

### Additional context
Part of Python 3 work.

**Comment by leonardder** [comment]
@josephsl: Is this fixed already?

**Comment by josephsl** [comment]
Hi, not yet. For now system tests are passing with current dependencies, and I plan to wait this weekend before committing dependency changes in requirements file. Thanks.

**Comment by josephsl** [comment]
Hi,

Expect at least one try build just for testing build status with newest dependencies.

Thanks.

**Comment by josephsl** [comment]
Hi,

I'll do something about this in August.

Thanks.

**Comment by Adriani90** [comment]
@josephsl do you have any updates to this? Thanks.

**Comment by josephsl** [comment]
Hi, I’d wait until 2019.3 stable comes out before looking into this again. Thanks for the reminder.

**Comment by Adriani90** [comment]
@josephsl now that 2020.1 is out, have you had a look into this? Is this still to be done? It would be good to take care of this now that we are in maintenance loop.

**Comment by josephsl** [comment]
Hi, there are more important issue/pull request pairs to consider, so this one is taking a back seat for now (besides, I’m desperate for a vacation from NVDA world for a while). Thanks.

**Comment by seanbudd** [comment]
Can this be closed?

**Comment by seanbudd** [comment]
Stale
