### ISSUE TITLE
NVDA doesn't really work all the way with audacity

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#980]
**Reported by KevanGC on 2010-10-17 07:24**
It doesn't work all the way when you're using Audacity (Audacity is a free audio editer.)
You should get NVDA to work all the way with Audacity or another audio editer/recorder.

**Comment by ehollig** [comment]
As @jcsteh said in a previous comment, this is an unhelpful report. Not enough information has been provided.

**Comment by josephsl** [comment]
CC @DerekRiemer, any updates?

**Comment by derekriemer** [comment]
nope
