### ISSUE TITLE
Update check/Python 3: update check fails due to incomplete urllib package imports

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9818]
### Steps to reproduce:
In order to test this, a binary version of Python 3 staging snapshot is ideal:

1. Run the latest Python 3 staging snapshot.
2. Check for updates.

### Actual behavior:
Errors such as a traceback that says no function.

### Expected behavior:
Update check succeeds.

#### NVDA installed/portable/running from source:
Source and portable

#### NVDA version:
Py3 staging 17843

#### Windows version:
Windows 10 Version 1903

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
None

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes- no i8ssues with Python 2 version.

### Cause:
Caused by incomplete urllib package import (such as not importing urllib.request/parse).

Thanks.

**Comment by josephsl** [comment]
Hi,

Note that if one imports just urllib, urllib.request/parse won't be imported. The solution is to import at least urllib.request, which will then import other parts of this package.

Thanks.

**Comment by josephsl** [comment]
Hi,

Also, this affects timeout parameter (see #2352 for a history of this).

Thanks.

**Comment by leonardder** [comment]
Fixed in #9820
