### ISSUE TITLE
Update check/Python 3: "bytes-like object is required" traceback when checking for updates

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9819]
### Steps to reproduce:
For this one, Python 3 staging snapshot with update check fix must be in use with debug logging enabled:

1. Run Python 3 staging snapshot.
2. Try checking for updates.

### Actual behavior:
The following traceback is recorded:

DEBUGWARNING - updateCheck.UpdateChecker._bg (08:16:54.308):
Error checking for update
Traceback (most recent call last):
  File "updateCheck.py", line 232, in _bg
    info = checkForUpdate(self.AUTO)
  File "updateCheck.py", line 141, in checkForUpdate
    key, val = line.split(": ", 1)
TypeError: a bytes-like object is required, not 'str'

### Expected behavior:
No errors.

#### NVDA installed/portable/running from source:
Source and portable

#### NVDA version:
Python 3 staging 17843

#### Windows version:
Windows 10 Version 1903

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
None

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes - no errors in Python 2 releases.

**Comment by leonardder** [comment]
Fixed in #9837
