### ISSUE TITLE
Adobe Acrobat/Reader crashes few seconds after opening

### ISSUE THREAD

**Issue by magibrahim** [nvaccess/nvda#9822]
Hello, 

Wanted to reach out to see if someone is having similar issue; NVDA latest version is installed 2019.1.1 and both Adobe Acrobat 11.23 and Reader DC latest version, both crashes few seconds after opening. I can reproduce the issue every time.

Event viewer showing UIAutomationCore.dll is the faulting module.

Hoping for some insight on how to fix this.

**Comment by DataTriny** [comment]
Hello @magibrahim,
It would be nice if you could properly fill out the [bug report template](https://github.com/nvaccess/nvda/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Could you at least mention if NVDA is installed as well as your Windows version please? It will help developers to find out what is going on.
Thanks.

**Comment by magibrahim** [comment]
Steps to reproduce: Acrobat crashes upon opening, NVDA is running
Actual behavior: Immediate app crash
Expected behavior:
System configuration
NVDA installed/portable/running from source: Installed
NVDA version: 2019.1.1
Windows version: Windows 10 Pro x64, 10.0.17134
Name and version of other software in use when reproducing the issue: Adobe Acrobat 11.23/ Adobe Reader DC "Latest Version"
Other information about your system:
Other questions
Does the issue still occur after restarting your PC? Yes
Have you tried any other versions of NVDA? If so, please report their behaviors. No

**Comment by DrSooom** [comment]
Isn't the Adobe Acrobat 11.23 outdated?

Well, start NVDA with the flag "--no-sr-flag" and then start the Adobe Reader DC. If the Adobe Reader DC is still crashing after a few seconds, re-install it. (Even as the Adobe Reader DC isn't a critical application, creating an image-based backup of the whole system before re-installing is nevertheless recommended.)

**Comment by Adriani90** [comment]
I guess adobe acrobat and adobe dc are not working very well when you have both installed on your PC. Could you try to uninstall one of them and see if the issue is still occuring?

**Comment by magibrahim** [comment]
Thank you so much for the replies, tomorrow morning I will be removing reader and do some testing. fingers crossed.

**Comment by DrSooom** [comment]
@magibrahim: You could also install [Foxit Reader](https://www.foxitsoftware.com/pdf-reader/) as an alternative for the Adobe Reader. NVDA supports the Foxit Reader since 2018.4.

**Comment by jsk90123** [comment]
install adobe updates

**Comment by Adriani90** [comment]
@magibrahim do you still have this issue in NVDA 2019.3 Beta 2?

**Comment by Adriani90** [comment]
I cannot reproduce this with last version of Adobe reader and NVDA 2020.1. And we don't have any updates from the initial author. Closing as works for me and abandoned.
