### ISSUE TITLE
Update check/Python 3: Windows error 17 thrown when attempting to postpone a donwloaded update

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9825]
### Steps to reproduce:
In order for this to work, recent Python 3 staging branch with update capability must be used.

1. Use a recent Python 3 staging update.
2. Try updating to a newer build.
3. At the last second, postpone the update.

### Actual behavior:
Windows error 17 is thrown:

IO - speech.speak (20:07:58.786):
Speaking [LangChangeCommand ('en_US'), 'NVDA Update  dialog  NVDA version threshold_py3_staging-17851,779ca15b is ready to be installed.\n']
IO - speech.speak (20:07:58.796):
Speaking [LangChangeCommand ('en_US'), 'Install update  button  Alt+i']
IO - inputCore.InputManager.executeGesture (20:08:00.286):
Input: kb(desktop):escape
WARNING - stdout (20:08:00.286):
.\userConfig\updates\nvda_update_nrzt7u9w.exe
DEBUGWARNING - updateCheck.UpdateAskInstallDialog.onPostponeButton (20:08:00.286):
Unable to rename the file from C:\Users\User\AppData\Local\Temp\nvda_update_nrzt7u9w.exe to .\userConfig\updates\nvda_update_nrzt7u9w.exe
Traceback (most recent call last):
  File "updateCheck.py", line 521, in onPostponeButton
    os.renames(self.destPath, finalDest)
  File "C:\Python37\lib\os.py", line 268, in renames
    rename(old, new)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'C:\\Users\\User\\AppData\\Local\\Temp\\nvda_update_nrzt7u9w.exe' -> '.\\userConfig\\updates\\nvda_update_nrzt7u9w.exe'

### Expected behavior:
No errors.

#### NVDA installed/portable/running from source:
Source and portable

#### NVDA version:
Python 3 staging 17851

#### Windows version:
Windows 10 Version 1903

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
None

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes - no errors with Python 2 releases.

**Comment by josephsl** [comment]
Hi,

Note that applying the update right away (clicking Install button) works. A major issue with update results keys being treated as bytes (#9819) should be done in order for update check result to show up.

Thanks.

**Comment by leonardder** [comment]
Could you actually reproduce this with master as well if you run the portable snapshot from another disk drive? If so, this is not threshold specific.

**Comment by josephsl** [comment]
Hi, can’t reproduce this on master running on portable copy. Thanks.

**Comment by leonardder** [comment]
This is a python bug or enhancement, depending on your point of view. See [this issue](https://bugs.python.org/issue28356). From our perspective, it's a bug.

We have two options

1. Switch to shutil.move
2. Build our own wrapper around MoveFileEx.

I prefer the former.

A patch for this should ensure that both os.rename and os.renames are covered throughout the codebase.

**Comment by josephsl** [comment]
Hi, let me do some experiments and report back with a PR if it works. Thanks.

**Comment by josephsl** [comment]
Hi,

Thankfully, there is no known module that uses os.renames.

If implemented, os.rename to shutil.move will involve add-on handler (install/uninstall), config (profile renames), installer, log handler (renaming the old log), and update check (postponing updates).

Thanks.

**Comment by josephsl** [comment]
Hi,

Performance issues observed when using shutil.move, specifically when postponing updates, partly caused by the update dialog staying open until file "rename" operation is completed. Python 3.8 may speed things up a bit, but given that this scenario may involve moving data across devices (say, postponing an update when run from a portable copy stored on a USB flash drive), it'll feel like a regression.

The other issues to note would be when installing NVDA and/or add-ons, as both of these involve os.rename. Thankfully, these will deal with data on just one drive (or in case of add-ons, under one directory), so it does not pose a problem. Also, no issues seen with log file and profile renames.

Thanks.

**Comment by josephsl** [comment]
Hi,

Upon further examination, the only place that uses os.renames function is update check. I think places that use os.rename (without an 's') pose no issues for now, but we want to be safe.

For now the most ideal option is using shutil.move in places where we use os.rename(s) if it makes sense, leaving others as is. As noted previously, using shutil.move introduces appearance of performance regression when postpone button is clicked. To mitigate this, perhaps queueing shutil.move after closing the dialog might work in bringing back the speed users expect.

Thanks.

**Comment by josephsl** [comment]
Hi,

Performance: a dedicated thread will work well for this situation - I investigated async/await but it doesn't really fit our needs at the moment.

Because this work will require #9819 to be merged first, I'll file two separate PR's for this combined work.

Thanks

**Comment by josephsl** [comment]
Hi,

I'll keep this issue open, but I think it would be best to file a new issue to deal with MoveFileEx wrapper design that goes beyond update postpone button handler.

Thanks.

**Comment by feerrenrut** [comment]
Fixed with commit 2a260be633bc406220435366bdde0aba5d3a0459 in PR #9849
