### ISSUE TITLE
MoveFileEx: create a wrapper for use by update check, file utils and others

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9847]
Hi,

This issue is a more generalized version of #9825:

### Is your feature request related to a problem? Please describe.
Currently, various file operations (specifically, renames) use os.rename(s) function to accomplish file moves or renames. However, as noted in #9825, there are behavioral differences between Python 2 and 3 regarding os.renames. The most prominent problem being update check/postpone button handling where the handler fails due to internal differences in how this function is implemented.

The best solution so far is using kernel32.dll::MoveFileEx function. Not only this simulates "renames", it also allows file moves to be carried out just by using Windows API functions we've been using without knowing it. This has been successfully tested in PR #9836.

While reviewing the mentioned PR, @LeonardDer commented that there are other parts of NVDA that could be modifiedto use a wrapper for MoveFileEx function. These include file renaming operations in the installer and fault-tollerant file feature in file utils. Thus he recommends using this opportunity to design a MoveFileEx wrapper and centralize support for this wrapper.

### Describe the solution you'd like
Create winKernel.moveFileEx with associated file move flags so other modules can call this function rather than scattering the work across modules.

### Describe alternatives you've considered
Leave the source code as is.

### Additional context
In terms of how to proceed with code, it is already available as part of #9836 - it is a matter of letting other modules use it. This code is also Python 3 compliant.

### Reference:
* MoveFileEx documentation from Microsoft Docs: https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-movefileexa

Thanks.

**Comment by Brian1Gaff** [comment]
Actually this might well solve those odd errors where the log file cannot be 
written to when nvda tries to restart after an update, perhaps?

Brian
bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by josephsl** [comment]
Hi, probably not. Thanks.

**Comment by feerrenrut** [comment]
Fixed with commit 2a260be633bc406220435366bdde0aba5d3a0459 in PR #9849
