### ISSUE TITLE
Expose UIASelectionPattern and UIATablePattern

### ISSUE THREAD

**Issue by towebo** [nvaccess/nvda#9861]
>

**Comment by josephsl** [comment]
Hi, er, looks like the road is not paved yet i.e. can we get more info as to why this is needed and where this can be most useful, filled out according to the template please? Thanks.

**Comment by towebo** [comment]
UIA exposes UIAGridPattern but without the UIASelectionPattern and UIATablePattern it’s impossible to make a grid/table accessible because you can’t inform the user what’s selected and what the data in each colum represents.

**Comment by josephsl** [comment]
Hi, understandable. Can you think of an example application that can benefit from this? Also, note that there is also selection2 pattern series, too. Thanks.

**Comment by towebo** [comment]
Visma Administration is aan accounting software that has approx 50% of the market for small and medium sized businesses in Sweden and we’ve managed to get them to make the application more accessible. They have a custom made grid that was totally inaccessible and now they’ve implemented UIA but NVDA didn’t recognize it and is quiet. I’ve received C# code that can extract the data and it’s from that I began my research in NVDA source code. It looks like the IUIASelectionPattern and IUIATablePattern are defined but not present in class UIA. Now when writing this I think that there’s some kind of UIAValuePattern that is used to get the data in the cells. The grids are also used as lists by having a foll row selected.t

**Comment by towebo** [comment]
@josephsl , the following is reported when inspecting the navigator object.

Developer info for navigator object:
name: u'Grid'
role: ROLE_DATAGRID
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <appModules.spcsadm.VismaSafGrid object at 0x04BE7670>
Python class mro: (<class 'appModules.spcsadm.VismaSafGrid'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: ''
location: RectLTWH(left=1589, top=1047, width=882, height=304)
value: None
appModule: <'spcsadm' (appName u'spcsadm', process ID 12388) at address 4b56ff0>
appModule.productName: u'Visma Administration'
appModule.productVersion: u'2019.2'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 2032908
windowClassName: u'SafGrid'
windowControlID: 7407
windowStyle: 1352728576
windowThreadID: 9096
windowText: u'Custom1'
displayText: u'Djurg\xe5rdens Ridsport o St\xe4ngsel  AB FTG2H\xe4st och Hage by TR FTG1H\xe4st och Hage by TR FTG3H\xe4st och Hage by TR HastochHageH\xe4st och Hage by TR HastochHage - kopiaH\xe4st och Hage by TR HoH_180209H\xe4st och Hage by TR KaninMawingu Mawingu\xd6vningsbolaget AB Ovnb' (truncated)
UIAElement: <POINTER(IUIAutomationElement) ptr=0x59e548 at 4bb1da0>
UIA automationID: SafGrid
UIA frameworkID: Win32
UIA runtimeID: (42, 2032908)
UIA providerDescription: [pid:11572,providerId:0x1F050C Main:Nested [pid:12388,providerId:0x1F050C Main(parent link):Unidentified Provider (unmanaged:spcsadm.exe)]; Nonclient:Microsoft: Non-Client Proxy (unmanaged:UIAutomationCore.dll); Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:UIAutomationCore.dll)]
UIA className: SafGrid
UIA patterns available: LegacyIAccessiblePattern, GridPattern, ScrollPattern, SelectionPattern, TablePattern

It's interesting that it recognizes the selection pattern and the table pattern even if you can't use then in the code. I haven't found the Selection2 patterns you mentioned. Are they specified in the UIA.py?

**Comment by josephsl** [comment]
Hi, selectoin2 pattern series are available in newer UIA interfaces, and are not included in NVDA yet. Thanks.

**Comment by leonardder** [comment]
Adding new patterns as properties to the UIA object should be pretty easy to do. I"m marking this as a good for new dev.

This can be a nice way to get a list of all the patterns.

`[p for p in vars(UIAHandler.UIA) if p.endswith("Pattern")]`

Make sure that for every pattern, check the minimum required windows version, just like how it is done with the "UIATextEditPattern" property.

**Comment by leonardder** [comment]
Selection patterns are added in #12210

**Comment by Adriani90** [comment]
@seanbudd is this also fixed now that #12862 has been merged?

**Comment by seanbudd** [comment]
yes, thanks @Adriani90 . Closed by #12862, #12210
