### ISSUE TITLE
Update changes file on threshold branch

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#9862]
Look at the PR's merged to `threshold` and `threshold_py3_staging`, decide if a what's new entry is required and write one if so. Particular attention should be given to changes relevant to developers (especially authors of, add-ons, braille drivers, synth drivers). Non user visible changes do not need to be included.

Please list the PR's that you have looked at (and either written an entry, or decided one isn't necessary) in the description, all PR's to `threshold` or `threshold_py3_staging` need consideration. 

Because this will be on-going work create a draft PR, it helps us to know when the PR is finished, or more accurately, that it is not. We likely wont merge it until we are ready to merge threshold back to master. Because only then we will know we have handled all PR's

**Comment by josephsl** [comment]
Hi, speaking of which, I’ll add an entry on #7105 while we are at it, along with fixing new lines. Thanks.

**Comment by josephsl** [comment]
Hi,

If you don't mind, can you merge master into threshold first please? That way we can work from a common ground.

Thanks.
