### ISSUE TITLE
Could not attach console (windows error 6) when running cmd.exe

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#9867]
Note: the below only occurs if the advanced "Use
UI Automation to access the windows console when available" option is turned off. In
other words: the current default condition.

### Steps to reproduce:

Run a recent NVDA alpha or beta.
Perform Windows+r, "cmd", enter.

### Actual behavior:

A windows error sound occurs on launch.

The console appears to act normally after that, although when doing a "cls" NVDA is silent (does not read the prompt), until enter is pressed a second time, though this may be unrelated and happens in older versions.

Various warnings, and a "could not attach console: windows error (6, 'the handle is invalid')" are logged.

### Expected behavior:

No windows error sound, no logged warnings or errors.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

beta-17929

#### Windows version:

Windows 10 Home 1903, 64 bit

#### Name and version of other software in use when reproducing the issue:

Windows command shell (cmd.exe)

#### Other information about your system:

AMD

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

A few recent betas have done this.
Edit: also occurs on an installed version of alpha-17928,9dfbd2ee (7/3/2019).
Doesn't happen with 2019.1.1, although the (likely unrelated) cls problem does.

[nvda-cmd-errors.txt](https://github.com/nvaccess/nvda/files/3356708/nvda-cmd-errors.txt)

**Comment by XLTechie** [comment]
CC @codeofdusk

**Comment by XLTechie** [comment]
I intended to mention this in the original issue: this is with the advanced "Use 
UI Automation to access the windows console when available" turned off. In 
other words: the current default.

**Comment by Adriani90** [comment]
qXLTechie could zou test please with last alpha_ I cannot reproduce this issue in NVDA alpha-17901,ac6ea147.

**Comment by Brian1Gaff** [comment]
I don't see it with betas in Windows 7 either.
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by XLTechie** [comment]
@Adriani90  the alpha you tested with is not the most recent alpha. It is from July 1, which is older than the beta I was testing with.
But you are correct that it doesn't occur in that alpha.
However, it does occur in the most recent alpha: alpha-17928,9dfbd2ee (July 3rd).

**Comment by lukaszgo1** [comment]
I cannot reproduce it on my main machine running Windows 7 nor on my vm running Windows 10 1809. I can however reproduce it on Windows 10 1903 though it isn't happening all the time. I've tried tracking it down to a specific build of Alpha without much luck - the Alpha 17901,ac6ea147 mentioned by @Adriani90 also exhibits this issue occasionally. Logging this specific exception at a higher log level and therefore avoiding error sound is covered by #7250 and the error sound isn't present in a release version.

**Comment by Andre9642** [comment]
I confirm the issue with the current alpha version (alpha-18450,8c27752f), many recent alpha and versions mentioned by @XLTechie. With fresh portable versions and installed versions (with add-ons disabled). Running on Windows 10Ver1903.

When Windows Console support is set to UIA, the bug doesn't seem to occur. But unfortunately I prefer legacy mode for now (because many other odd behaviors).

However the bug doesn't happen systematically.

When this happens, I also have the following error is raised in the log and I'm unable to navigate in the Terminal content:

```
DEBUGWARNING - winConsoleHandler.connectConsole (09:31:49.453):
Could not attach console: OSError(9, The handle is invalid, None, 6)
ERROR - NVDAObjects.behaviors.LiveText._monitor (09:31:49.471):
Error getting initial lines
Traceback (most recent call last):
  File "NVDAObjects\behaviors.pyc", line 271, in _monitor
  File "NVDAObjects\window\winConsole.pyc", line 62, in _getTextLines
  File "winConsoleHandler.pyc", line 127, in getConsoleVisibleLines
  File "wincon.pyc", line 77, in GetConsoleScreenBufferInfo
OSError: [WinError 6] The handle is invalid
```

**Comment by lukaszgo1** [comment]
cc @codeofdusk again. Also @Andre9642 if you are experiencing problems with new UIA support for consoles could you open a bug report about them? UIA would be the default for 2019.3, and it is important to make it as good as possible before the release.
