### ISSUE TITLE
NVDA double-speaking profiles when using FB with arrow keys

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#987]
**Reported by dharvey on 2010-10-21 04:06**
using firefox 3.6.11.
1.  Log into Facebook.
2.  Use arrows to navigate profiles in news feed or go to your profile.

Result:  NVDA double-speaks the profile name as you arrow up and down.  his should not happen.

**Comment by ehollig** [comment]
I am not able to replicate this. Facebook and Firefox has changed quite a bit over the years.

**Comment by leonardder** [comment]
[**@ehollig**](https://github.com/ehollig) commented on [15 jul. 2017 17:30 CEST](https://github.com/nvaccess/nvda/issues/987#issuecomment-315541804 "2017-07-15T15:30:48Z - Replied by Github Reply Comments"):
> I am not able to replicate this. Facebook and Firefox has changed quite a bit over the years.

Very likely indeed. Closing as works for me.
