### ISSUE TITLE
Threshold_py3_staging snapshots: desktop shortcut doesn't work

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9870]
### Steps to reproduce:
Start a threshold_py3_staging snapshot while a source copy is running.

### Actual behavior:
The following error is written to the log:

```
ERROR - RPC process 8660 (nvda_slave.exe) (19:47:36.752):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 53, in main
  File "shellapi.pyc", line 38, in ShellExecute
FileNotFoundError: [WinError 2] The system cannot find the file specified.
```

### Expected behavior:
NVDA starts as normal

### Background
The slave is using sys.exec_prefix, but that's empty in frozen copies of NVDA on Python 3. Don't know why. May be another difference in py2exe we weren't aware of.
I will investigate this further in or after the weekend.

**Comment by feerrenrut** [comment]
Fixed with commit 17c7ea1b68904fb27f38b89f7955b9dae52d2616 in PR #9871
