### ISSUE TITLE
NVDA causing other pyinstaller wx python programs to crash

### ISSUE THREAD

**Issue by NathanTech7713** [nvaccess/nvda#9885]
Hello there,
I am a developer myself, of python applications using wx python as a GUI and pyinstaller to turn them into an executable.
this was working fine right up to about a week or two ago.
Since then, i have noticed that NVDA seems to be causing the programs to lag when ever it finds a list control.
It lags about 1 second per move, for reference. I tested this without NVDA running and can confirm that the issue does not occur unless NVDA is loaded. Similarly, I then tried restarting NVDA after launching the program. The result of this was the program stopped responding, and then closed.
Finally, I tried launching the program, then launching NVDA. In this instance, the program ran fine up to the point where NVDA launched, and then began to lag.
I turned therefore to the debug logs. Whenever focusing on the window, with alt tab, I got this result:

```
DEBUGWARNING - watchdog._watcher (10:10:33.178):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 233, in <module>
  File "core.pyo", line 519, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 1003, in Notify
  File "core.pyo", line 489, in run
  File "IAccessibleHandler.pyo", line 900, in pumpAll
  File "IAccessibleHandler.pyo", line 657, in processFocusWinEvent
  File "IAccessibleHandler.pyo", line 524, in winEventToNVDAEvent
  File "_UIAHandler.pyo", line 389, in isUIAWindow
  File "_UIAHandler.pyo", line 367, in _isUIAWindowHelper
```
Just today, i also got this error when I closed the program:
```
DEBUGWARNING - eventHandler.executeEvent (10:10:45.255):
error executing event: gainFocus on <NVDAObjects.Dynamic_MultitaskingViewFrameListItemListItemUIA object at 0x05AEA890> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "C:\Users\natha\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 426, in event_gainFocus
  File "eventHandler.pyo", line 100, in next
  File "appModules\explorer.pyo", line 301, in event_gainFocus
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\__init__.pyo", line 966, in event_gainFocus
  File "NVDAObjects\__init__.pyo", line 854, in reportFocus
  File "speech.pyo", line 403, in speakObject
  File "speech.pyo", line 277, in speakObjectProperties
  File "baseObject.pyo", line 47, in __get__
  File "baseObject.pyo", line 147, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyo", line 1291, in _get_columnNumber
  File "NVDAObjects\UIA\__init__.pyo", line 741, in _getUIACacheablePropertyValue
COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (
```
I hope you can help in resolving this issue soon.

**Comment by leonardder** [comment]
Did you receive a Windows update that could have caused this?

**Comment by NathanTech7713** [comment]
That is possible.
I did have an update come through, but will be honest and say I can not remember if the timing of said update coincides exactly with this problem beginning.
Has NVDa been updated here since that update, and should I therefore update it? Or.

**Comment by NathanTech7713** [comment]
Update: Having run the Run the Com registration tool, the error has now disappeared from the log. The issue however, still persists, and this error occasionally appears in the log:
Error while removing  pending update menu item
Traceback (most recent call last):
  File "gui\__init__.pyo", line 233, in evaluateUpdatePendingUpdateMenuItemCommand
wxAssertionError: C++ assertion "node" failed at ..\..\src\msw\menu.cpp(890) in wxMenu::DoRemove(): bug in wxMenu::Remove logic

**Comment by leonardder** [comment]
It might be good to know the exat version of NVDA and Windows you're on, as well as the version of WXPython you're using.
Do you have this problem when the application is frozen with PyInstaller, or also from source?

**Comment by NathanTech7713** [comment]
Windows is the latest, as its on automatic update.
NVDA version: 2019.1.1.
WX Python version: the most up-to-date of the classic build, but this also occurs with 4.0 phoenix. though I only tested it briefly with that.
No, this issue does not occur if the python program is uncompiled.
It does occur with it compiled, however

**Comment by NathanTech7713** [comment]
Hi there,
Sorry to be a bother, but this is really holding up developent on my end on both releases and test fazes. 
I've tried completely uninstalling NVDA and reinstalling it, but the same issue still occurs.
Hopig for a resolution soon.
Cheers.

**Comment by NathanTech7713** [comment]
For reference, here is one example of where it crashes the program:
IO - inputCore.InputManager.executeGesture (17:28:17.855):
Input: kb(laptop):enter
DEBUGWARNING - watchdog._watcher (17:28:23.391):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 233, in <module>
  File "core.pyo", line 519, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 1003, in Notify
  File "core.pyo", line 489, in run
  File "IAccessibleHandler.pyo", line 897, in pumpAll
  File "IAccessibleHandler.pyo", line 620, in processGenericWinEvent
  File "IAccessibleHandler.pyo", line 524, in winEventToNVDAEvent
  File "_UIAHandler.pyo", line 389, in isUIAWindow
  File "_UIAHandler.pyo", line 367, in _isUIAWindowHelper

DEBUGWARNING - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (17:28:23.905):
AppModule does not have a binding handle
IO - speech.speak (17:28:23.907):
Speaking [LangChangeCommand ('en'), u'Luna RSS. By Nathan Tech. (Not Responding)']

**Comment by josephsl** [comment]
Hi,

A few things:

1. What happens if you use NVDA 2019.2 beta 3?
2. Have you tried testing the app after freezing with something other than Pyinstlaler i.e. CX_Freeze or Py2exe and running that agaisnt NVDA 2019.1.1 and/or 2019.2 beta 3?

I recommend testing with 2019.2 beta 3 before doing some more investigations. If the answer to the second question is a "no", chances are that it might be something to do with Pyinstaller.

Thanks.

**Comment by NathanTech7713** [comment]
Hello!
So aparrently it didn't send when I sent the email.
I tried with py2exe and got the exact same result.
When running NVDA 2019.3beta, I got the following error when the crash occurred:
WARNING - watchdog._watcher (19:46:17.878):
Core frozen in stack:
  File "nvda.pyw", line 231, in <module>
  File "core.pyo", line 519, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 1003, in Notify
  File "core.pyo", line 489, in run
  File "IAccessibleHandler.pyo", line 887, in pumpAll
  File "IAccessibleHandler.pyo", line 661, in processFocusWinEvent
  File "IAccessibleHandler.pyo", line 524, in winEventToNVDAEvent
  File "_UIAHandler.pyo", line 408, in isUIAWindow
  File "_UIAHandler.pyo", line 386, in _isUIAWindowHelper

**Comment by josephsl** [comment]
Hi,

Technical: somehow, watchdog freezes when UIAutomationCore::UiaHasServerSideProvider gets stuck somewhere.

Since this does not happen when running the said program from source, I'm thinking something odd is going on during or after freezing the program. I'm wondering if NVDA might be affected by it (I know that we can't use UIA in NVDA itself due to issues seen) because we are also using wxPython frozen through Py2exe.

Thanks.

**Comment by josephsl** [comment]
Hi,

Another possibility: can you try with latest wxPython 4.1.0 development build to see if it is something to report to Robin?

Thanks.

**Comment by NathanTech7713** [comment]
Hi.
It'll take me a little while to test wx version 4, as I'll have to write a test program from scratch and what not.
What is interesting though is this issue didn't occur before. IE, I have products out right now that function perfectly fine, and yet when installed on my system, do not. I am wondering if it is because my python environment variable is pointed at c:/python2732, not c:python27? there is a c:/python27 though it is empty

**Comment by josephsl** [comment]
Hi, that may explain part of it – did you perhaps install a 64-bit Python 2.7 by chance? Thanks.

**Comment by NathanTech7713** [comment]
Well, previously, I had this configuration:
c:python27 was 64 bit
c:python3 was 64 bit pytho n3
c:python2732 was 32 bit python 2
and c:python332 was python 3 win 32.
then I'd compile by doing:
c:/python2732/scripts/pyinstaller, or
c:/python332/scripts/pyinstaller.

I recently uninstalled the 64 bit pythons.
I wonder if that screwed everything up, as it were.

**Comment by josephsl** [comment]
Hi, could be a coincidence. Note that NVDA is a 32-bit app which uses Python 2.7, although NVDA is about to be powered by Python 3.7 at any moment now. In any case, try reinstalling 64-bit Python and see if Pyinstaller can deal with this, and if it doesn’t chances are that it might be a Windows Update issue or something going on with NVDA+UIA. Thanks.

**Comment by NathanTech7713** [comment]
Hi,
I can confirm this issue still occurs, with the same traceback, with wx python 4.
I refigured my system to work with what it used to have in terms of python directories, and still no joy.
the issue persists!
I am completely lost for ideas now.

**Comment by NathanTech7713** [comment]
Just a further question, what actually is UIA?
This lag issue seems to occur only with wx.listctrl, as I can tab between the buttons very quickly and it keeps up fine. To that end, if I click the back button, rather than pressing backspace, the not responding and crash doesn't occur.
To recap, this issue cropped up out of no where, and it is affecting all compiled products, even those that used to work.

**Comment by josephsl** [comment]
Hi, given this does not occur on other systems, I’m thinking this is unique to yours – perhaps a DLL issue from your system. Thanks.

**Comment by josephsl** [comment]
Hi, UI Automation, a collection of API’s used between apps and assistive technologies to exchange accessibility information for controls and other elements. Thanks.

**Comment by NathanTech7713** [comment]
Heya,
Yeah. Figures as much.
Have you any tips for things to try?
I'm assuming dll's are missing/problematic for NVDA, so logic would suggest an uninstall and then a reinstall, though that didn't help last time...
Thanks

**Comment by josephsl** [comment]
Hi, I’m out of ideas myself – I won’t suggest resetting your computer in hopes that we can find a solution without resorting to it. Thanks.

**Comment by Adriani90** [comment]
@NathanTech7713 are you still having this issue in NVDA 2019.3 Beta 2? Sometimes it helps to re-register the com dlls or if possible all the dlls on your system. At least for some few com dlls NVDA provides a com registration fixing tool. You can find it in the NVDA menu under tools. Did you try that?

**Comment by lukaszgo1** [comment]
@NathanTech7713 Is this still reproducible for you?

**Comment by Adriani90** [comment]
We didn't get any updates from the initial author since more than 2 years. I am closing this issue as abandoned. if you are still having it, please comment and we can reopen.
