### ISSUE TITLE
Automatically set system focus to focusable lements off: pressing enter on a spin button moves the cursor to the task bar or to the address bar

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#9886]
### Steps to reproduce:
1. In Firefox, visit this website
https://www.dinnerkrimi.de/spielstaette/karlsruhe/badisch-brauhaus_005895/details.html
2. After the website is loaded, press nvda+8 to turn off automatically set system focus to focusable elements
3. In browse mode, press b to jump to the spin buttons
4. press enter on one of them to adjust the value in the spin edit

### Actual behavior:
Focus jumps to the task bar or to the address bar. The value in the spin edit does not change.

### Expected behavior:
The number in the spin edit should change and the focus should actually not change its position.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-17928,9dfbd2ee

#### Windows version:
Windows 10 1809 update

#### Name and version of other software in use when reproducing the issue:
Firefox 67.0.4.

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

**Comment by Adriani90** [comment]
Unfortunately there is not much logged when this happens. The only relevant part is this one directly after pressing enter:

```
IO - inputCore.InputManager.executeGesture (13:03:51.795):
Input: kb(laptop):enter
DEBUGWARNING - virtualBuffers.gecko_ia2.Gecko_ia2._activateNVDAObject (13:03:51.818):
doAction failed
DEBUGWARNING - virtualBuffers.gecko_ia2.Gecko_ia2._activateNVDAObject (13:03:51.819):
Clicking with mouse
```

cc: @leonardder, @mltony, @jcsteh

**Comment by DrSooom** [comment]
Perhaps NVDA isn't able to figure out the exact position of these elements. Thus it isn't also possible to move the mouse cursor onto it by using its NVDA command.  Maximize the Firefox window with WIN+ArrowUp and try again.

Well, and please throw the stupid Cookie notification out of the way, if it appears. You find it near the bottom of the html structure.

**Comment by Adriani90** [comment]
I tried it, maximizing the window does not solve this problem. However, if system focus is automatically set to focusable elements, the problem is not occuring. Thus, the problem appears wehn using the feature introduced by PR #9511.
