### ISSUE TITLE
Threshold_py3_staging: look at "Py3 rview" comments in the code, evaluate the code and remove these comments

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9888]
During the Python 3 migration, several extra comments have been added to clarify changes. Now we know more about how Python 3 behaves and we are able to test things with a working branch, we can re-evaluate these cases and remove the comments.

For example, there are several cases of `for value in list(dictionary.values())`, in which case wrapping inside a list call is not necessary. In case of `for key in list(dictionary.keys())`, it is enough to use `for key in dictionary:`

Some other comments are obsolete in that they tell the reader that we are iterating over the keys of a dictionary, but if we call .keys() on an object, it is pretty obvious that we're dealing with a dictionary anyway.

**Comment by josephsl** [comment]
Hi, ping me if you’d like me to take a look at these comments (I wrote a majority of them), although I won’t be able to respond for a few days due to events beyond my control where I live. Thanks.

**Comment by leonardder** [comment]
I will open a draft pr at some point in the near future.

**Comment by feerrenrut** [comment]
Closed with commit 0fb2342a9de82f6cbd262a6a33a70d9d8c6aeb29 in PR #9890
