### ISSUE TITLE
Revert selection message being at the end for list cases

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#9894]
### Steps to reproduce:

1. open a windows explorer window, select the files list, or open any multi-select list.
2. press control+space on a file.
3. move down or up with control+arrows.

### Actual behavior:
NVDA says "blah blah blah" before selected or unselected.

### Expected behavior:

As before, NVDA should say selected or unselected before the message, but only when selection changes.

#### NVDA version:
Version: alpha-17928,9dfbd2ee

Regression caused by #9028

**Comment by derekriemer** [comment]
@leonardder @feerrenrut

**Comment by josephsl** [comment]
Hi, the other day I was thinking we should add a Boolean (checkbox) setting that allows people to specify the old or the new behavior. What do you think? CC @LeonardDer

**Comment by DrSooom** [comment]
I love checkboxes. Well, I guess all of you already knew that. 😉

**Comment by derekriemer** [comment]
No, I think we should just remove the new behavior in this specific case. it's a special case. We don't need NVDA being littered with hundreds of one-off decision checkboxes.

**Comment by Brian1Gaff** [comment]
Yes it would be nice to have this as a choice,as long as it still works as a 
toggle on each item to alter the state when you hit space.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by Brian1Gaff** [comment]
Well I don't really agree, as its hardly a complex thing but can allow 
people to configure it and leave it. Default it to whatever you like, but 
the mere fact we have had it both ways in the past proves to me that there 
is push back against  one or the other behaviour, or nobody would have 
altered it!

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by lukaszgo1** [comment]
I am testing with 2019.1.1 and selected/nos selected is reported at the end in these cases. @derekriemer Are your certain that it is a regression?

**Comment by leonardder** [comment]
@lukaszgo1 Are you testing with the English version of NVDA? It could be that the translators of your particular language decided to swap the order.

I agree with @derekriemer. the selected state should be announced before the list item in these cases.

**Comment by lukaszgo1** [comment]
Yes, I've tested with the 2019.1.1 in  English, and not selected is announced at the end, selected however isn't announced at all when navigating with CTRL+arrows.

**Comment by DrSooom** [comment]
> Yes, I've tested with the 2019.1.1 in English, and not selected is announced at the end, selected however isn't announced at all when navigating with CTRL+arrows.

Exactly the same behavior on my machines with NVDA 2015.3/2018.1 (I'm waiting for 2019.2) on Win7x64 – both German GUI (incl. NVDA).

> It could be that the translators of your particular language decided to swap the order.

I suppose it wouldn't be bad to talk about this in a separate issue or in the translators' mailing list.

**Comment by DrSooom** [comment]
> Yes, I've tested with the 2019.1.1 in English, and not selected is announced at the end, selected however isn't announced at all when navigating with CTRL+arrows.

Exactly the same behavior on my machines with NVDA 2015.3/2018.1 (I'm waiting for 2019.2) on Win7x64 – both German GUI (incl. NVDA).

> It could be that the translators of your particular language decided to swap the order.

I suppose it wouldn't be bad to talk about this in a separate issue or in the translators' mailing list.

**Comment by XLTechie** [comment]
@josephsl, The request to make it configurable was in the comments of the PR I 
believe, though not acted upon.

I disagree with the "too much configurability" argument. People like choice. 
When it comes to saying "selected" before or after text, people have arguments 
on both sides, and enough prefer it each way that it should really be a 
checkbox. See #1707 for some of the arguments, just as one example.

  For the case of selecting files, however, it almost certainly should be 
announced before the (un)selected name, regardless of any checkbox.

**Comment by feerrenrut** [comment]
I don't believe there is a regression here so I'm going to close this issue. If you get different results on some system please add a comment.

For each preference (selected first vs last) there are good justifications. Collecting these user stories may help us to innovate in this area, see https://github.com/nvaccess/nvda/issues/6757#issuecomment-506673210 for an example of similar user stories.

Sometimes this is just a matter of preference, NV Access has goals to improve the configurability of the NVDA speech user experience and even suggested it as a project idea for Google Summer of Code. However, creating a check box for every variation will make configuration for users difficult and maintenance for developers difficult.

## Test method

1. In the keyboard settings panel (`NVDA + control + k`) enable:
   - Speak command keys
1. Open speech viewer
1. Open explorer, navigate to a folder with at least 5 items
1. Focus the second item in the the file list
1. Press `NVDA + F12` to speak the time, marking the start of speech output
1. Press `NVDA + TAB` to ensure the name of the currently focused file is spoken
1. Press `shift + down arrow` once to select two consecutive items
1. Press `control + down arrow` twice to skip an item
1. Press `control + space` to select the non consecutive item
1. Press `control + up arrow` four times to focus the first list item
1. `Alt + tab` to the speech viewer, select text from the `alt+tab` command, back to the time marker, copy this as your test output.

## Results
For 2019.1, latest beta build, and 2017.3 the output was all identical ( except for the time). See detailed output below.

### 2019.1:
```
11:30 AM
NVDA+tab
test file B.txt  list item  focused  selected  2 of 6
shift+down arrow
test file C.txt  3 of 6
ctrl+down arrow
test file D.txt  not selected  4 of 6
ctrl+down arrow
test file E.txt  not selected  5 of 6
ctrl+space
selected
ctrl+up arrow
test file D.txt  not selected  4 of 6
ctrl+up arrow
test file C.txt  3 of 6
ctrl+up arrow
test file B.txt  2 of 6
ctrl+up arrow
test file A.txt  not selected  1 of 6
alt+tab
```

### Latest Beta (beta-18022,dc5c0b8c)
```
11:33 AM
NVDA+tab
test file B.txt  list item  focused  selected  2 of 6
shift+down arrow
test file C.txt  3 of 6
ctrl+down arrow
test file D.txt  not selected  4 of 6
ctrl+down arrow
test file E.txt  not selected  5 of 6
ctrl+space
selected
ctrl+up arrow
test file D.txt  not selected  4 of 6
ctrl+up arrow
test file C.txt  3 of 6
ctrl+up arrow
test file B.txt  2 of 6
ctrl+up arrow
test file A.txt  not selected  1 of 6
alt+tab
```

### 2017.3
```
11:37 AM
NVDA+tab
test file B.txt  list item  focused  selected  2 of 6
shift+down arrow
test file C.txt  3 of 6
ctrl+down arrow
test file D.txt  not selected  4 of 6
ctrl+down arrow
test file E.txt  not selected  5 of 6
ctrl+space
selected
ctrl+up arrow
test file D.txt  not selected  4 of 6
ctrl+up arrow
test file C.txt  3 of 6
ctrl+up arrow
test file B.txt  2 of 6
ctrl+up arrow
test file A.txt  not selected  1 of 6
alt+tab
```

**Comment by DrSooom** [comment]
See also: Issue #8193
