### ISSUE TITLE
threshold_py3_staging: An error is displayed when updating portable copy

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#9898]
### Steps to reproduce:
1. Create portable copy of older NVDA threshold_py3_staging 
2. Attempt to update it.

### Actual behavior:
During update the following dialog is displayed
[Window Title]
Error

[Content]
Failed to create portable copy: catching classes that do not inherit from BaseException is not allowed

[OK]

In addition the following is in the log:
ERROR - gui.installerGui.doCreatePortable (19:30:30.383):
Failed to create portable copy
Traceback (most recent call last):
  File "installer.pyc", line 371, in tryRemoveFile
  File "winKernel.pyc", line 399, in moveFileEx
PermissionError: [WinError 5] Odmowa dostępu.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui\installerGui.pyc", line 355, in doCreatePortable
  File "gui\__init__.pyc", line 915, in __init__
  File "gui\__init__.pyc", line 919, in run
  File "installer.pyc", line 464, in createPortableCopy
  File "installer.pyc", line 179, in removeOldLibFiles
  File "installer.pyc", line 372, in tryRemoveFile
TypeError: catching classes that do not inherit from BaseException is not allowed

Surprisingly update succedes 
### Expected behavior:
No dialog box with error during update.

#### NVDA installed/portable/running from source:
Portable

#### NVDA version:
NVDA version threshold_py3_staging-17992,74431b8b
#### Windows version:
Windows 7 x64
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, Alpha builds are working.

**Comment by josephsl** [comment]
Hi, review in progress via #9876. Thanks.

**Comment by lukaszgo1** [comment]
Fixed with #9876. Closing. Thanks @josephsl
