### ISSUE TITLE
File upload and aria-live

### ISSUE THREAD

**Issue by AssassinLV** [nvaccess/nvda#9902]
We've run into a small wall - while making so that the added file information is read by the screen readers (for complying to WCAG2.1AA (for testing we use NVDA))..

The issue is that when the user opens "File Upload" - it's not the browser per-se but the File-Browse window, and if you select a file to be uploaded - then the aria-live="assertive" is ignored because the focus - goes back to the whole webpage - even if the actual focus is still the button, so the whole page is being read instead of the added part within the "aria-live" part of the page...

Does anyone knows of a work-a-round for this?

### Steps to reproduce:
1) Have a page with upload upon file selection from file dialog
2) Have an aria-live='assertive' to an element which will have text: "file {fileName} was uploaded" after upload

### Expected:
Only the text "file {fileName} was uploaded" is pronounced

### Actual:
Whole website is being read from beggining

#### NVDA version: 
2019.1.1

#### Windows version: 
Windows 10

#### Name and version of other software in use when reproducing the issue:
Google Chrome 75.0.3770.100 x64 , IE

#### Does the issue still occur after restarting your PC?: 
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.: 
No

**Comment by DrSooom** [comment]
@AssassinLV: Please completely fill out the bug report draft. Thanks.

**Comment by AssassinLV** [comment]
@DrSooom, to be fair - I'm not sure even if it is a bug, but sure - I'll fill up the rest of data.....

**Comment by AssassinLV** [comment]
Updated description with the rest of data

**Comment by Adriani90** [comment]
I think @derekriemer is actually having some work on this but I am not sure if it would exactly address this issue. That work will refactor the live region handler in the NVDA helper.

**Comment by Adriani90** [comment]
@AssassinLV are you still having this issue with NVDA 2024.2?
Did you try to turn off the setting "say all on page load" in NVDA browse mode settings? This might solve the issue.

**Comment by AssassinLV** [comment]
Sorry, I am not in a project anymore that uses this tool :)

**Comment by seanbudd** [comment]
#6335

**Comment by seanbudd** [comment]
Closing as no minimal sample could be provided
