### ISSUE TITLE
Ys 

### ISSUE THREAD

**Issue by jubervice** [nvaccess/nvda#9903]
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

**Comment by Adriani90** [comment]
I don‘t understand this issue. What exactly do you request? Currently when you are loged in on github and click the button new issue, you are already asked to choose the correct template for issue or feature.

**Comment by Adriani90** [comment]
I am closing this issue as invalid.
