### ISSUE TITLE
NVDA has an error browsing the web on Google Chrome

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#9906]
An error tone occurred during the process of browsing the web with NVDA and Google Chrome.
### Steps to reproduce:
open [github](https://github.com) and [google](https://www.google.com)
Then browse the web page and you can hear the error sound.
### Actual behavior:
Browse the web to report an error tone
### Expected behavior:
An error occurred
#### NVDA installed/portable/running from source:
install
and
portable
#### NVDA version:
NVDA version alpha-17928
#### Windows version:
windows10-1903-10.0.18362.175
#### Name and version of other software in use when reproducing the issue:
no
#### Other information about your system:
no
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The same problem occurred after testing with NVDA threshold_py3_staging-18000-portable.
google chrome version:
Google Chrome version 74.0.3729.108 (official version) (64-bit)
NVDA log:
[nvda.log](https://github.com/nvaccess/nvda/files/3375159/nvda.log)
thank

**Comment by Adriani90** [comment]
Could you please run the com registration fixing tool in nvda menu / tools? Is the problem still occuring after that?

**Comment by dingpengyu** [comment]
> Could you please run the com registration fixing tool in nvda menu / tools? Is the problem still occuring after that?

I ran the com registration fixing tool or the above problem.
thank

**Comment by Adriani90** [comment]
So is the problem solved now? Or do you still hear the errors?


Von meinem iPhone gesendet

**Comment by dingpengyu** [comment]
> So is the problem solved now? Or do you still hear the errors? Von meinem iPhone gesendet
> […](#)
> Am 10.07.2019 um 03:20 schrieb eric ***@***.***>: Could you please run the com registration fixing tool in nvda menu / tools? Is the problem still occuring after that? I ran the com registration fixing tool or the above problem. thank — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

hi Adriani
The problem has not been solved. I stopped testing all the plugins of NVDA and still reported an error.
thank

**Comment by Adriani90** [comment]
@dingpengyu it seems this error is comming from one core voices. Could you please test if this also occur with eSpeak?

The relevant part of the log is this:
```
ERROR - NVDAHelperLocal (07:21:54.244):
Thread 10888, build\x86\localWin10\oneCoreSpeech.cpp, ocSpeech_speak::<lambda_21151d5a0dfc8f546bcaed819f94e1de>::operator (), 98:
Error -2147024894: 系统找不到指定的文件。
```

It seems some registry keys related to One core cannot be loaded. This is stated quite at the beginning of the log file as follows and it causes a slow start of NVDA of about 5 seconds:
```
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.220):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enGB_GeorgeM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.220):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enUS_DavidM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.220):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enGB_HazelM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.220):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enGB_SusanM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.220):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enUS_ZiraM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.220):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_jaJP_AyumiM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.221):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_jaJP_HarukaM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.221):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enAU_CatherineM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_zhHK_TracyM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_zhTW_HanhanM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_zhTW_YatingM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_jaJP_IchiroM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_zhHK_DannyM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enUS_MarkM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enAU_JamesM, WindowsError(2, '')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_zhTW_ZhiweiM, WindowsError(2, '')
```

cc: @leonardder, @jcsteh

**Comment by dingpengyu** [comment]
> @dingpengyu it seems this error is comming from one core voices. Could you please test if this also occur with eSpeak?
> 
> The relevant part of the log is this:
> 
> ```
> ERROR - NVDAHelperLocal (07:21:54.244):
> Thread 10888, build\x86\localWin10\oneCoreSpeech.cpp, ocSpeech_speak::<lambda_21151d5a0dfc8f546bcaed819f94e1de>::operator (), 98:
> Error -2147024894: 系统找不到指定的文件。
> ```
> 
> It seems some registry keys related to One core cannot be loaded. This is stated quite at the beginning of the log file as follows and it causes a slow start of NVDA of about 5 seconds:
> 
> ```
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.220):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enGB_GeorgeM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.220):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enUS_DavidM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.220):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enGB_HazelM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.220):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enGB_SusanM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.220):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enUS_ZiraM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.220):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_jaJP_AyumiM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.221):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_jaJP_HarukaM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.221):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enAU_CatherineM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_zhHK_TracyM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_zhTW_HanhanM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_zhTW_YatingM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_jaJP_IchiroM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_zhHK_DannyM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enUS_MarkM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enAU_JamesM, WindowsError(2, '')
> DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (07:21:30.223):
> Could not open registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_zhTW_ZhiweiM, WindowsError(2, '')
> ```
> 
> cc: @leonardder, @jcsteh

Hi Adriani
I tested with eSpeak NG
eSpeak NG did not report an error while browsing the web
Below is the NVDA log
[nvda.log](https://github.com/nvaccess/nvda/files/3379802/nvda.log)
thank

**Comment by dingpengyu** [comment]
I just tested NVDA threshold_py3_staging-18054, and the problem of using google to browse the web has been resolved. Open chrome browser and use tab to browse the web without error sound.
