### ISSUE TITLE
Browseable Messages - Centered and enlarged

### ISSUE THREAD

**Issue by JulienCochuyt** [nvaccess/nvda#9910]
### Is your feature request related to a problem? Please describe.

Browseable messages, as produced with `ui.browseableMessage` are shown in a tiny window, located near the top-left corner of the display, sometimes partially off-screen.

These limitations do not encourage authors to leverage the offered functionality - currently used only for format related info.

Looking at the source, it is clear the original intention was to have the window centered on the screen:
`DIALOG_OPTIONS = "dialogWidth:350px;dialogHeight:140px;resizable:yes;center:yes;help:no"`

The "center" option, which defaults to "yes", is misinterpreted at least with newer Internet Explorer versions. To obtain the desired behavior - a centered window - it should be removed.

### Describe the solution you'd like

- Remove the "center" option to preserve its "yes" default.
- Remove the height and width options to obtain a somewhat bigger default size window.

### Additional context

Upcoming PR

**Comment by josephsl** [comment]
Hi, actually, I use this facility in my add-ons, and content recog framework uses this as well. CC @Nishimotz who has practical experience with this. Thanks.

**Comment by nishimotz** [comment]
I have changed `center:yes;` to `center:desktop;` in nvdajp.
It worked better.

**Comment by JulienCochuyt** [comment]
@nishimotz thanks for your feedback

> `center:desktop;`

I could not find a reference for this value for the "center" option.
Do you know if it has a different meaning than the default "yes", when multiple desktops are involved maybe? Is it supported in older IE versions? Eg. we are keeping around the "help" option which is meaningful only for IE versions < 7.

I found you original ticket on this subject: (https://osdn.net/projects/nvdajp/ticket/36310)
If translation is correct, you did not have an official reference at the time.
Do you remember if you tried without the "center" option back then, and if it had a different effect compared to "desktop"?

By the way, I am sorry no one considered your valuable comment: (https://github.com/nvaccess/nvda/issues/4908#issuecomment-215653279)

My reference for these options is:
(https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa741859(v%3Dvs.85)
Which in turn indirectly refers to the following for the "pchOptions" parameter:
(https://docs.microsoft.com/en-us/previous-versions//hh870397(v=vs.85))

The following web site does mention the "desktop" value for the "center" option, but state it as "undocumented" and provide no further details nor version compatibility:
(https://www.geoffchappell.com/studies/windows/ie/mshtml/api/htmldlg/options.htm?tx=34)

**Comment by nishimotz** [comment]
Sorry, I don't remember how I discovered that option.

**Comment by leonardder** [comment]
> 
> ... content recog framework uses this as well.

I don't think so, contentRecog uses a cursor manager.

**Comment by JulienCochuyt** [comment]
If there is no argument in favor of the undocumented "desktop" value, I would advocate to keep with my original proposal of removing the option "center" altogether to obtain its safe and documented "yes" behavior.

**Comment by josephsl** [comment]
Hi, at least in theory the idea is there. Thanks.
