### ISSUE TITLE
Table within figure and figcaption referenced by aria-labelledby / describedby announced twice

### ISSUE THREAD

**Issue by afercia** [nvaccess/nvda#9914]
### Steps to reproduce:

Please refer to this codepen: 
https://codepen.io/afercia/full/WqmbPQ

It's based on this W3C tutorial example:

**Using the `<figure>` element to mark up a table summary**
https://www.w3.org/WAI/tutorials/tables/caption-summary/#using-the-figure-element-to-mark-up-a-table-summary

### Actual behavior:
- press T to jump directly to the table
- the figcaption text is announced twice
- first, as content of the figure element 
- then, as label and description of the table

### Expected behavior:
- when jumping directly to the table, I'd expect the text to be announced only once, as accessible name and description of the table
- maybe related: the figure element is announced as a generic "grouping"

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.1.1
#### Windows version:
Windows 10 Pro

#### Name and version of other software in use when reproducing the issue:
Tested with Firefox 69 and Chrome 75: no difference.

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

For what is worth, testing with JAWS (Firefox and Chrome) and VoiceOver (Safari), there's only one announcement.

Also for what is worth this came up while exploring alternative to the `<caption>` element for the new WordPress editor, see https://github.com/WordPress/gutenberg/pull/15554

**Comment by Adriani90** [comment]
This is working properly now with NVDA alpha-20220,1c4519a6, Chrome 83 and Firefox 76. Closing as works for me.
