### ISSUE TITLE
Py3 Python console: tab completion no longer shows private attributes

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9918]
### Is your feature request related to a problem? Please describe.
In python 2, pressing tab in the python console gives us auto completion for an object. For example, typing `nav.` followed with tab gives us all the properties on the cached navigator object, including the ones starting with one or two underscores. In python 3 however, these attributes are hidden.

### Describe the solution you'd like
I think I like this new approach, but it should be documented as a change in the section of changes for developers.

### Describe alternatives you've considered
Restore the python 2 behavior.

**Comment by JulienCochuyt** [comment]
I do not reproduce on latest threshold snapshot (18031 - ae3747ad).
In this version, tab completion still shows all attributes, including single and double leading underscores.
Did you witness this behavior with latest threshold_py3_staging source instead?

IMHO, if we have something to fix here, an ideal behavior would be as follows:
- `nav.`<tab> : list all "public" members
- `nav._` <tab> : list all single leading underscore attributes
- `nav.__` <tab> : list all double leading underscore attributes

**Comment by leonardder** [comment]
Threshold is still python 2, this is related to py3_staging.

**Comment by JulienCochuyt** [comment]
My bad. I indeed reproduce - and quite like it - on latest threshold_py3_staging snapshot (18054 - 92458e98).
The behavior is exactly the one I naively stated as being my ideal one in my previous comment.

+1 for keeping this behavior and documenting it as an improvement.

**Comment by leonardder** [comment]
cc @feerrenrut

**Comment by XLTechie** [comment]
+1 for leaving it as-is, with added changelog entry.

**Comment by feerrenrut** [comment]
Yes, I'm happy with this also. Happy to take a suggestion for the changelog. Does the userguide/devguide need an update?

**Comment by JulienCochuyt** [comment]
> Yes, I'm happy with this also. Happy to take a suggestion for the changelog. Does the userguide/devguide need an update?

The userGuide only points to the devGuide: No impact needed IMHO.
Proposed update to the devGuide: PR #9935

Proposed changelog entry:

Section: Changes for developpers
The tab-completion in the Python console is now smarter. Refer to the Developer Guide for more details.
