### ISSUE TITLE
Installer/Python 3: type error thrown when attempting to perform a fresh NVDA instlal with no other versions present

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#9923]
Hi,

To @LeonardDer, another symptom of comparison with None:

### Steps to reproduce:
Try installing a fresh copy of NVDA Python 3 staging snapshot on a system without any NVDA version installed. This is easily accomplished through Windows Sandbox (Windows 10 Version 1903).

### Actual behavior:
The following traceback is printed when attempting to install NVDA (after choosing to do so from the launcher)

ERROR - unhandled exception (17:55:56.772):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 747, in <lambda>
  File "gui\__init__.pyc", line 777, in onAction
  File "gui\__init__.pyc", line 351, in onInstallCommand
  File "gui\installerGui.pyc", line 263, in showInstallGui
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### Expected behavior:
No errors.

#### NVDA installed/portable/running from source:
Not installed

#### NVDA version:
Python 3 staging 18054

#### Windows version:
Windows 10 Version 1903 Sandbox

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
Tested inside Windows Sandbox.

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes - no issues with lapha, current Threshold, and 2019.1.1.

### Additional context:
The install comparison function found in installer returns None when no version of NVDA is found on a system. The actual installer GUI doesn't know that the installer function returns None and proceeds to compare the return value as though it is an integer.

Thanks.

**Comment by feerrenrut** [comment]
Fixed with commit cb5405f in PR #9924
