### ISSUE TITLE
MS Word: browse mode setting ignored after pressing Alt+F7

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#9927]
STR:
1. Start writing a document, and make a spelling mistake.
2. Press NVDA+Space, to turn on browse mode in Word.
3. Press W to move to the error.
4. Press Alt+F7 and correct it by pressing Enter.
5. Press W again.

Expected: NVDA will say no next error.
Actual: NVDA has switched to edit mode in Word again.

Testing on Windows 10 1903, NVDA 2019.2beta3, NVDA 2019.1.1 didn't exhibit this behaviour, as I tested it. Word 2019 with UIA enabled on both.

**Comment by leonardder** [comment]
I can not reproduce this with NVDA alpha-18064, which featureset is equal to 2019.2Beta3. I tested with Office 2016.

**Comment by fisher729** [comment]
Have you tried with 2019.2beta3?

**Comment by fisher729** [comment]
Hi.

Closing, at is no longer reproduceable using NVDA 2019.3 with Microsoft Office version 16.0.13426.20332

**Comment by fisher729** [comment]
Hi.

Closing, at is no longer reproduceable using NVDA 2019.3 with Microsoft Office version 16.0.13426.20332
