### ISSUE TITLE
when opening a java application it is not possible to review the characters typed in a text field

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9939]
### Steps to reproduce:
Open a java application.
Put the focus in a text field.
Please enter some characters.
Read the typed text with directional arrows.
### Actual behavior:
an error sound is heard and not a character or text is read
### Expected behavior:
the typed text should be read when navigating with the arrows
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
nvda_snapshot_threshold_py3_staging-18066,131ed840.exe
#### Windows version:
10 17763
#### Name and version of other software in use when reproducing the issue:
java application
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes
I did not notice the problem in alpha verbs.
log:
[java.txt](https://github.com/nvaccess/nvda/files/3399040/java.txt)

**Comment by feerrenrut** [comment]
Fixed in commit 3dcea53 via PR #9951
