### ISSUE TITLE
PowerPoint: Report more accurate position of text with NVDA+delete

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#9941]
### Is your feature request related to a problem? Please describe.

In PowerPoint, when editing an object with text, you can press NVDA+numpad delete / NVDA+delete to have NVDA report the review cursor location.  Currently what this reports is the percentage of the way through the text in the current object the cursor is.

For instance, in the text:
"The quick brown fox jumps over the lazy dog".

If the caret is at the start of the word "jumps", NVDA+numpad delete reports "45%".

if the text is split over two lines before the word jumps, NVDA+numpad delete reports the same thing.

### Describe the solution you'd like

It would be useful to know the position within the container or slide.

If the same command is used to query the position of the object itself (press escape once from editing text), NVDA reports: "120 points from left slide edge, 88.4 points from top slide edge, 120 points from right slide edge, 264 points from bottom slide edge".

A similar format for the position within the container would enable objects to be positioned which might overlap the container but not the text.

### Additional context

Using Office 365 version 16.0.11727.20222 on Windows 10 version 18362.1  using NVDA 2019.2beta3.

**Comment by josephsl** [comment]
Hi,

Five years later...

@Qchristensen, updates please.

Thanks.

**Comment by Adriani90** [comment]
Still an issue in Powerpoint 365 with NVDA 2024.3 Beta.
Solving This request would make designing presentations really much easier.
