### ISSUE TITLE
Elevated Consoles Unusable in beta-18133,b29acb42

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#9956]
### Steps to reproduce:

Press: Windows+r
Type: cmd
Press: ctrl+shift+enter.
Proceed past the UAC dialog.

### Actual behavior:
After entering the password or whatever to pass the UAC, the introductory text to the console speaks, as well as the initial prompt.
Thereafter, only Windows error sounds are generated for any key press, including NVDA commands.

### Expected behavior:
Achieve a usable console.

### System configuration
Installed NVDA beta-18133,b29acb42
Windows 10, 1903 64bit.

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Did not happen under 2019.1.1 last time I had it installed.

### Comments

I notice that in the elevated copy of NVDA, the Advanced settings are unavailable. That makes me wonder if the UI Automation support is unavailable in this situation, and if that might be contributing?

**Comment by josephsl** [comment]
Hi, I can’t reproduce this in alpha at the moment. What happens when you start with add-ons off? CC @CodeOfDusk

**Comment by XLTechie** [comment]
Additional element: if this is done from an administrative account, the problem 
does not exist. It only seems to happen if done from a non-admin account, with 
an admin password entered at the UAC.

Add-ons enabled or disabled makes no difference.

After updating virtualization options in Turn Windows Features On and Off, the 
Windows error sounds have disappeared, and now the consoles are just entirely 
silent.

Tried to test with alpha, but it doesn't like the idea of installing over a 
newer beta.

**Comment by XLTechie** [comment]
Log attached. Windows errors 5 and 6 in the tracebacks.

Maybe related to #9867 
[nvda-windows-errors-5and6.txt](https://github.com/nvaccess/nvda/files/3415746/nvda-windows-errors-5and6.txt)

**Comment by lukaszgo1** [comment]
I've tested on my vm running Win 10 1903 with NVDA 2019.1.1 and the situation is the same so it isn't a regression. NVDA never worked particurarly well with appps running as a different user.

**Comment by Adriani90** [comment]
@XLTechie are you still having this issue in NVDA 2023.2?

**Comment by XLTechie** [comment]
No, thought this was closed long ago.
