### ISSUE TITLE
Threshold: "SyntaxError: invalid or missing encoding declaration for 'brailleDisplayDrivers\\handyTech.pyc'"

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9960]
### Steps to reproduce:
1. Connect a handy tech display using auto detection
2. Disconnect it.

### Actual behavior:
Many logging errors in the log, all leading up to `SyntaxError: invalid or missing encoding declaration for 'brailleDisplayDrivers\\handyTech.pyc'`

### Expected behavior:
NO errors

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
threshold-18146

#### Windows version:
Windows 10 1903

#### Name and version of other software in use when reproducing the issue:
Handy Tech Active Braille braille display

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, no errors on alpha.

**Comment by leonardder** [comment]
Mm, manually uninstalling and reinstalling NVDA fixed the problem for me. It turns out that C:\Program Files (x86)\NVDA\brailleDisplayDrivers contained many outdated files. I'd have expected that the installer had cleaned these up, though.

**Comment by feerrenrut** [comment]
Fixed with commit 44c3234  in PR #9961
