### ISSUE TITLE
NVDA is not considering all the Ids mentioned in the aria-labelled by for IE combobox

### ISSUE THREAD

**Issue by vaishnavimakam** [nvaccess/nvda#9965]
Steps to reproduce:

1. Rename the attched txt to html and open in IE 11+
2. [new 8.txt](https://github.com/nvaccess/nvda/files/3426258/new.8.txt)
3. Keep NVDA on and try to tab into the combo box. 
4. NVDA only reads the text in label element and ignores the text in span element
5. This does not work even after adding any text inside the span tag.

This is working fine in Chrome.

I am using NVDA 2019.1.1

**Comment by DrSooom** [comment]
@vaishnavimakam: Please add the exact IE 11 version and the Windows version to the issue description. Thanks.

**Comment by vaishnavimakam** [comment]
IE 11 version
![image](https://user-images.githubusercontent.com/5100911/62028493-febaad80-b1fd-11e9-936b-90f2a7271ce3.png)
Windows version - 
![image](https://user-images.githubusercontent.com/5100911/62028561-2dd11f00-b1fe-11e9-8375-ace15873054e.png)

**Comment by vaishnavimakam** [comment]
Windows version - 
![image](https://user-images.githubusercontent.com/5100911/62028607-4a6d5700-b1fe-11e9-9d48-fb9f85191354.png)
IE 11 version - 
![image](https://user-images.githubusercontent.com/5100911/62028635-5a853680-b1fe-11e9-90a8-1c2c4dcd6849.png)

**Comment by DataTriny** [comment]
Hi @vaishnavimakam, please remember that you are posting on a screen reading software issue tracker and therefore most of the developers are indeed blind and cannot read screenshots content.
For anyone interested:
- Windows version: 1803 (build 17134.706),
- IE version: 11.706.17134.0

**Comment by Adriani90** [comment]
Support for IE ended completely in 2022, and the browser is automatically removed from machines that still have it after an Edge update in February 2023. I don't expect any further updates regarding accessibility. If you still have this issue in other browsers, please open a new updated issue with coresponding steps to reproduce and a minimal test case.
I am closing this as abandoned.
