### ISSUE TITLE
Keep Volume and Speed Constant When Switching Profiles

### ISSUE THREAD

**Issue by jhomme** [nvaccess/nvda#9966]
### Is your feature request related to a problem? Please describe.

I have a few profiles: one for Word, one for Excel, and others. When I change the volume and speed of NVDA, it is disconcerting  to keep changing one or the other  in each profile when I switch away from the Normal profile or back again.

### Describe the solution you'd like

I'd like checkboxes that say something like "Change rate with Normal," and "Change speed with Normal." If I uncheck them, NVDA behaves as it does now. If I check them, NVDA would check the rate and volume of the Normal profile and match them.

### Describe alternatives you've considered

Writing code to get this to happen. I do not know Python well enough yet.

### Additional context
I've always considered these settings as global.

**Comment by DrSooom** [comment]
Please open all ini files in the folder "C:\Users\[Username]\AppData\Roaming\nvda\profiles" with Notepad++. The configuration profiles should only store the different settings in compare to the default profile.

**Comment by Adriani90** [comment]
Closing in favor of #10156 which contains more discussion on this.
