### ISSUE TITLE
Secure Screens: Don't Allow Users to invoke NVDA's GUI

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#9969]
When NVDA is run from within a Secure Screen, we currently disable some functionality due to security implications - limiting the Log Viewer being a good example of this. Due to the fact that users will only primarily use NVDA on Secure Screens when either locking their device or logging back into Windows, could we also consider disabling most (if not all) of NVDA's GUI? I can think of several good reasons to do this:

1. We offer users the option of copying their current config to Secure Screens, so any changes that need to be made can simply be done via the existing button from within the Preferences dialog - or for advanced users, by editing the config from within the systemConfig folder directly

2. Less experienced NVDA users may wonder why changes explicitly changed in their config on Secure Screens (edited from within the Preferences dialog) arn't synced to their main NVDA config - we could eliminate this confusion by simply disabling the GUI

3. Limiting use of GUI controls would also eliminate an attack vector if any such vulnerabilities were to be found within wx, and would prevent fixes from having to manually be integrated into NVDA

**Comment by lukaszgo1** [comment]
I can imagine many situations in which having access to the GUI on the secure screens would be useful.
1. You are sharing a pc with sighted colleagues / family and someone turns volume all the way down. Therefore to login you have to connect usb sound card and of course switch to it from the synthesizer dialog.
2. The pc is used by blind and deaf-blind users. They need to switch to the braille display not supporting auto-detection even on the login screen, so they need access to the braille dialog.

Given the fact that we cannot reasonably predict what part of the GUI might b needed for a particular use case on the secure screens i vote for closing this.

**Comment by elliott94** [comment]
With your first point, it could be argued that the Synth Settings Ring could be used for this; that said, the second point is more than valid.

Instead, then, could we consider only allowing certain sections from within Preferences to be accessed, or disable the saving of the config when NVDA is running on Secure Screens?

**Comment by lukaszgo1** [comment]
It is already not possible to save config from secure screens.

**Comment by elliott94** [comment]
Apologies; after performing more testing, I see that it's not, in fact, possible to save config changes - @lukaszgo1, thank you for assisting with this.
