### ISSUE TITLE
NVDA LinkedIn problems

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#997]
**Reported by dharvey on 2010-10-24 10:50**
Hi

I seem to be having a problem with the LinkedIn website.  It occurs in IE and Firefox.

STR:
1.  Log into LinkedIn.
2.  Go to help and type in Change Email address.
3.  Read through instructions.

Result:  According to instructions there should be a settings link.
Actual result:  No settings link is found.

**Comment by ehollig** [comment]
I was able to find the "Settings & Privacy" link and activate it. It is likely that LinkedIn has changed their website since this ticket was created. Therefore, instructions may be different.

**Comment by leonardder** [comment]
Linked in has changed in a very major way. Closing this as works for me. @ehollig, thanks for trying to reproduce!!
