### ISSUE TITLE
Preferences: Add Option to automatically Sync NVDA Config with Secure Desktop Settings

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#9970]
Currently, if a user wishes to mirror their primary NVDA config to the set of settings used on Secure Screens, they have two options - they can either do a copy/paste of their "nvda" folder into "systemConfig", or they can simply use the button found in the main Preferences dialog. However, they then wish to make updates to their config which results in the above two steps having to be performed once again.

To make this somewhat easier, could we add an option to NVDA so that on each close, the core examines the main config, and if any changes are made (whether that be changes to NVDA's config files or additions/removals from the main NVDA config directory), these changes are automatically copied to the "systemConfig" directory? This settings should only be enabled if NVDA detects the presence of the "systemConfig" directory to begin with.

**Comment by leonardder** [comment]
I think we can't do this, as copying user config to the system config requires elevated privileges. It is also a huge security risk. Imagine that you accidentally installed a malicious add-on and that add-on ends up in the system config automatically. It would have full system privileges when running on a secure screen.

I once proposed #6822 as an alternative, though this proposal seems to be pretty complex. AN alternative approach could be piping the speech and braille from the system config to the user config, or loading NVDA on secure copies with the current user configuration (without add-ons).

For now, I'm closing this as can't fix.
