### ISSUE TITLE
Error when building NVDA from source about ComTypes sub module

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#9976]
### Steps to reproduce:

1. Check out the source code for NVDA.

### Actual behavior:

While checking out the submodules, the following error is displayed:

error: Server does not allow request for unadvertised object 8c45582fe497269594f127f93d1a786d6bc868fb
Fetched in submodule path 'include/comtypes', but it did not contain 8c45582fe497269594f127f93d1a786d6bc868fb. Direct fetching of that commit failed.

### Expected behavior:

Complete checkout without errors.

#### NVDA installed/portable/running from source:

Running from source.

#### NVDA version:

2019.3/master.

#### Windows version:

10 19H1.

#### Name and version of other software in use when reproducing the issue:

Current Git and other dependencies as specified in the updated readme.

#### Other information about your system:

Nothing unusual.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

N/A.

**Comment by leonardder** [comment]
have you tried to deinit the comtypes submodule and init it again after a submodule sync?

**Comment by dnz3d4c** [comment]
Running git submodule sync from the NVDA src directory and running git submodule update seems to fix the problem.

**Comment by MarcoZehe** [comment]
> 
> 
> Running git submodule sync from the NVDA src directory and running git submodule update seems to fix the problem.

Yes, that did the trick for me, too.

Now when running scons source, I get:

ImportError: bad magic number in 'py2exe': b'\x03\xf3\r\n':
  File "C:\devel\nvda\SConstruct", line 20:
    from py2exe.dllfinder import pydll

**Comment by leonardder** [comment]
Updating a source repo from Python 2 to 3 requires some extra care. @feerrenrut, good to be aware of it.

You're probably best to run git clean -dfx from the main repo and from miscdeps.

**Comment by MarcoZehe** [comment]
After I did that, running scons source gives:

ModuleNotFoundError: No module named 'py2exe':
  File "C:\devel\nvda\SConstruct", line 20:
    from py2exe.dllfinder import pydll

git clean -dfx in the misc_deps directory gave something about removing py2exe. And git submodule update or git submodule update --init, with and without git submodule sync before, doesn't pull anything new or update anything.

**Comment by leonardder** [comment]
There are new submodules as well. I think submodule init . should fix that

**Comment by feerrenrut** [comment]
A fresh clone is probably easiest, otherwise:
- Checkout the branch (`git checkout origin/master`)
- Sync and update submodules (`git submodule sync` then `git submodule update --init --recursive`)
- Clean your working directory (`git clean -dfx`)
- Clean all submodules (`git submodule foreach git clean -dfx`)

Then try building.

**Comment by MarcoZehe** [comment]
I managed to get it working by force-updating the submodules. Now, I have a problem with the scons script not recognizing my VC 2017 Community install, even though all install options and individual components are installed and up to date. The problem seems to be that there is also a 2019 version installed on my system, which I need to build Firefox. And even though it mimics the installed components of 2017, it is not happy. But that's a different issue I think. If you're interested, I can copy&paste the error message.

**Comment by leonardder** [comment]
Ah, I think that should also have been the case on previous master.
If you have 2017 for NVDA only, you can just remove it and install the vc 15.16 buildtools. That's what I currently do.

**Comment by MarcoZehe** [comment]
Thanks, that worked, and NVDA now built successfully.
