### ISSUE TITLE
Routing cursor don't work

### ISSUE THREAD

**Issue by Oreonan2** [nvaccess/nvda#9981]
### Steps to reproduce:
* Open a text editor like Notepad.
* Write a text.
* Try to move cursor with routine cursor of Braille Display.

### Actual behavior:
Error sound is play and cursor isn't move.

### Expected behavior:
No error and cursor is move

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-18199,af9b85de

#### Windows version:
10.0.18362.239

#### Name and version of other software in use when reproducing the issue:
Notepad

#### Other information about your system:
Use old Papenmeier Braille Display

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, before switch to python 3 this action worked correctly.

**Comment by leonardder** [comment]
Could you please provide a log containing the error?

**Comment by Oreonan2** [comment]
Oh yes, the part of log containing the error:
"
ERROR - scriptHandler.executeScript (22:30:54.930):
error executing script: <bound method GlobalCommands.script_braille_routeTo of <globalCommands.GlobalCommands object at 0x08970EF0>> with gesture 'route'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 190, in executeScript
  File "globalCommands.pyc", line 2028, in script_braille_routeTo
  File "braille.pyc", line 1770, in routeTo
  File "braille.pyc", line 1387, in routeTo
  File "braille.pyc", line 1059, in routeTo
  File "braille.pyc", line 1026, in getTextInfoForBraillePos
TypeError: list indices must be integers or slices, not float
"

**Comment by leonardder** [comment]
@Oreonan2: thanks for this
Just to make sure, you're using the papenmeier older models display?

**Comment by Oreonan2** [comment]
@leonardder Yes, exactly

**Comment by leonardder** [comment]
Would you be able to test the following try version to see if the problem persists there?
https://ci.appveyor.com/api/buildjobs/6d74jt218k1oa8hr/artifacts/output%2Fnvda_snapshot_try-papenmeierSerial-18201%2C22b76ff4.exe

**Comment by Oreonan2** [comment]
I just tested this version, the problem is corrected.

**Comment by XLTechie** [comment]
The title of this thread is "Routine cursor don't work".
Is that supposed to be "Routing cursor don't work"?

If it is, can someone please change the title so that future people searching on 
github will have a hope of finding this?
