### ISSUE TITLE
Firefox, sometimes error when turning off focus mode when focused on a text field

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#9987]
### Steps to reproduce:

No exact steps, sometimes when focused on a text field, on different pages, and wanting to turn off focus mode with INS+Space or Escape, NVDA emits an error sound, and browse mode is not invoked. Alt-tabbing out and back into Firefox then resolves the problem, but it tends to occur in irregular intervals again.

### Actual behavior:

When this occurs, NVDA logs the following:

IO - inputCore.InputManager.executeGesture (09:05:41.492):
Input: kb(laptop):NVDA+space
DEBUGWARNING - RPC process 8872 (firefox.exe) (09:05:41.529):
Thread 7048, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::locateTextFieldNodeAtOffset, 854:
Offset 8144 out of range. Returnning NULL

DEBUGWARNING - RPC process 8872 (firefox.exe) (09:05:41.549):
Thread 7048, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::locateControlFieldNodeAtOffset, 874:
Could not locate node at offset, returning NULL

DEBUGWARNING - virtualBuffers.VirtualBufferTextInfo._getNVDAObjectFromOffset (09:05:41.549):
Couldn't get NVDAObject from offset 8144
ERROR - scriptHandler.executeScript (09:05:41.549):
error executing script: <bound method GlobalCommands.script_toggleVirtualBufferPassThrough of <globalCommands.GlobalCommands object at 0x048ABA10>> with gesture u'NVDA+Leertaste'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 192, in executeScript
  File "globalCommands.pyo", line 1309, in script_toggleVirtualBufferPassThrough
  File "treeInterceptorHandler.pyo", line 133, in _set_passThrough
AttributeError: 'NoneType' object has no attribute 'treeInterceptor'

### Expected behavior:

Nothing of that sort.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

2019.2Beta3.

#### Windows version:

10 19H1

#### Name and version of other software in use when reproducing the issue:

Firefox 69 Beta 8.

#### Other information about your system:

Connected is a Handy Tech Actilino.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes, [this snapshot build](https://ci.appveyor.com/project/nvaccess/nvda/build/alpha-18064,e579eb02) before the Speech Refactor/Python3 merge did not exhibit the problem, and it had been running since July 15. In 2019.2Beta3, which only ran for two days, this has already occurred 5 times or so.

**Comment by MarcoZehe** [comment]
To be clear, this is an issue specifically pertaining to 2019.2Beta3. CC @feerrenrut.

**Comment by Brian1Gaff** [comment]
Are there any specific pages you can tell us about that do this?
 I've not experienced any errors using Firefox or Waterfox on beta 3 on 
windows 7.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by MarcoZehe** [comment]
I've seen it on Twitter at least once. And once on my banking site.

**Comment by DrSooom** [comment]
@MarcoZehe: Does this issue also occur if you are using no braille display? See also: Issue #8967.

**Comment by Adriani90** [comment]
@MarcoZehe are you still seeing this issue in Firefox 76 with NVDA last alpha? Does it make a difference if you have a braille display connected or not?

**Comment by MarcoZehe** [comment]
No, this issue can be closed.

Am Do, 21. Mai 2020, um 02:31, schrieb Adriani90:

**Comment by Adriani90** [comment]
Thanks for reporting back Marco. Closing as works for me.
