### ISSUE TITLE
Error when loading some pages in MSEdge Chromium

### ISSUE THREAD

**Issue by Oreonan2** [nvaccess/nvda#9988]
### Steps to reproduce:
- Open Microsoft Edge based on Chromium (Ege dev for example);
- Go to a protected folder authentification webpage
- Connect to the protected folder

### Actual behavior:
- When authentification is successfully and webpage is loading, an error appear in the NVDA's log.
- Error is:
>ERROR - eventHandler.executeEvent (14:04:51.654):
>error executing event: gainFocus on <NVDAObjects.IAccessible.chromium.Document object at 0x00CF6230> with extra args of {}
>Traceback (most recent call last):
>  File "eventHandler.pyc", line 155, in executeEvent
>  File "eventHandler.pyc", line 92, in __init__
>  File "eventHandler.pyc", line 100, in next
>  File "C:\Users\coren\AppData\Roaming\nvda\addons\easyTableNavigator\globalPlugins\easyTableNavig>ator.py", line 82, in event_gainFocus
>    nextHandler()
>  File "eventHandler.pyc", line 100, in next
>  File "NVDAObjects\__init__.pyc", line 1033, in event_gainFocus
>  File "NVDAObjects\__init__.pyc", line 921, in reportFocus
>  File "speech\__init__.pyc", line 345, in speakObject
>  File "baseObject.pyc", line 46, in __get__
>  File "baseObject.pyc", line 149, in _getPropertyViaCache
>  File "NVDAObjects\__init__.pyc", line 1251, in _get__hasNavigableText
>  File "baseObject.pyc", line 46, in __get__
>  File "baseObject.pyc", line 149, in _getPropertyViaCache
>  File "NVDAObjects\IAccessible\ia2Web.pyc", line 58, in _get_states
>  File "baseObject.pyc", line 46, in __get__
>  File "baseObject.pyc", line 149, in _getPropertyViaCache
>  File "NVDAObjects\IAccessible\__init__.pyc", line 866, in _get_states
>  File "comtypesMonkeyPatches.pyc", line 22, in __call__
>_ctypes.COMError: (-2147467259, 'Erreur non spécifiée', (None, None, None, 0, None))

### Expected behavior:
No error when loading page

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-18199,af9b85de

#### Windows version:
10.0.18362.267

#### Name and version of other software in use when reproducing the issue:
Microsoft Edge dev 77.0.223.0

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by lukaszgo1** [comment]
@Oreonan2 I believe this should be fixed by #9984. Could you please download [this build](https://ci.appveyor.com/api/buildjobs/qa5nekj2ar0n9exq/artifacts/output%2Fnvda_snapshot_pr9984-18207%2C3d1c015b.exe) and check?

**Comment by Oreonan2** [comment]
@lukaszgo1 Yes, I confirm with this build my problem is fixed.
