### ISSUE TITLE
NVDA version alpha-18199,af9b85de problems sapi 4 and others

### ISSUE THREAD

**Issue by markusg2** [nvaccess/nvda#9989]
### Steps to reproduce:
sometimes nvda react slowly or it crash. i can navigat but it is not possible to open the nvda menu and other
i have german whois of sapi 4
there is funny behaviour
by reading english text on some line the screenreader stops for 1-3 seconds and will read again.
NVDA version alpha-18199,af9b85de
when you navigate by using coursor up and down, to my version numberthe screenreader hangs 
following you see in the logfile
turning language dedtection on or of makes no difference 

INFO - __main__ (14:39:45.835):
Starting NVDA
INFO - core.main (14:39:46.163):
Config dir: C:\Users\Markus\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (14:39:46.163):
Loading config: C:\Users\Markus\AppData\Roaming\nvda\nvda.ini
INFO - config.ConfigManager._loadConfig (14:39:46.256):
Config loaded (after upgrade, and in the state it will be used by NVDA):
{'schemaVersion': '2', 'upgrade': {}, 'update': {'autoCheck': 'True', 'allowUsageStats': 'True', 'askedAllowUsageStats': 'True', 'startupNotification': 'True'}, 'general': {'language': 'de', 'saveConfigurationOnExit': 'True', 'askToExit': 'False', 'playStartAndExitSounds': 'True', 'loggingLevel': 'DEBUG', 'showWelcomeDialogAtStartup': 'False'}, 'speech': {'synth': 'sapi4', 'outputDevice': 'Microsoft Soundmapper', 'autoLanguageSwitching': 'True', 'symbolLevel': '100', 'autoDialectSwitching': 'False', 'espeak': {'voice': 'de', 'variant': 'max', 'rate': '30', 'pitch': '40', 'inflection': '75', 'volume': '100'}, 'eloquence': {'voice': '262144', 'variant': '1', 'pitch': '65', 'inflection': '30', 'volume': '92', 'backquoteVoiceTags': 'True', 'useSpellingFunctionality': 'False', 'rate': '42'}, 'oneCore': {'voice': 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech_OneCore\\Voices\\Tokens\\MSTTS_V110_deDE_KatjaM', 'volume': '100', 'rate': '100'}, 'sapi4': {'voice': '{F58DF580-4BB3-11D5-A81B-00B0D0B68D94}', 'rate': '20', 'pitch': '21', 'volume': '40'}, 'sapi5': {'voice': 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech\\Voices\\Tokens\\TTS_MS_DE-DE_HEDDA_11.0', 'rate': '55', 'volume': '100'}}, 'braille': {'autoTether': 'False', 'tetherTo': 'focus', 'display': 'noBraille', 'noBraille': {'port': ''}}, 'keyboard': {'keyboardLayout': 'laptop', 'useCapsLockAsNVDAModifierKey': 'True', 'speakTypedCharacters': 'False', 'speakTypedWords': 'True', 'alertForSpellingErrors': 'False', 'speakCommandKeys': 'False'}, 'presentation': {'reportTooltips': 'True', 'reportDynamicContentChanges': 'False', 'reportAutoSuggestionsWithSound': 'False', 'progressBarUpdates': {'progressBarOutputMode': 'speak', 'reportBackgroundProgressBars': 'True'}}, 'documentFormatting': {'reportTables': 'False', 'reportTableHeaders': 'False', 'reportTableCellCoords': 'False', 'includeLayoutTables': 'True', 'reportClickable': 'False', 'reportStyle': 'True', 'reportLineSpacing': 'False'}, 'reviewCursor': {'simpleReviewMode': 'False', 'followCaret': 'True', 'followFocus': 'True'}, 'virtualBuffers': {'useScreenLayout': 'False', 'autoSayAllOnPageLoad': 'False', 'autoFocusFocusableElements': 'True'}, 'uwpOcr': {'language': 'de-DE'}, 'wintenApps': {'updateCheckTime': '1551900594'}, 'audio': {'audioDuckingMode': '0'}, 'mouse': {'enableMouseTracking': 'True', 'audioCoordinates_detectBrightness': 'True'}, 'development': {'enableScratchpadDir': 'False'}, 'debugLog': {'hwIo': 'True', 'audioDucking': 'False', 'gui': 'True', 'louis': 'True', 'timeSinceInput': 'True'}, 'UIA': {'useInMSWordWhenAvailable': 'True', 'winConsoleImplementation': 'UIA'}}
DEBUG - core.main (14:39:46.413):
setting language to de
INFO - core.main (14:39:46.453):
NVDA version alpha-18199,af9b85de
INFO - core.main (14:39:46.453):
Using Windows version 10.0.18356 workstation
INFO - core.main (14:39:46.453):
Using Python version 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]
INFO - core.main (14:39:46.453):
Using comtypes version 1.1.7
INFO - core.main (14:39:46.453):
Using configobj version 5.1.0 with validate version 1.0.1
DEBUG - core.main (14:39:46.453):
Initializing add-ons system
DEBUG - addonHandler._getAvailableAddonsFromPath (14:39:46.453):
Listing add-ons from C:\Users\Markus\AppData\Roaming\nvda\addons
DEBUG - addonHandler._getAvailableAddonsFromPath (14:39:46.453):
Loading add-on from C:\Users\Markus\AppData\Roaming\nvda\addons\wintenApps
DEBUG - addonHandler.Addon.__init__ (14:39:46.463):
Using manifest translation from C:\Users\Markus\AppData\Roaming\nvda\addons\wintenApps\locale\de\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (14:39:46.463):
Found add-on wintenApps - 20190726-dev. Requires API: (2019, 1, 0). Last-tested API: (2019, 3, 0)
DEBUG - core.main (14:39:46.793):
Initializing appModule Handler
DEBUG - addonHandler.Addon.addToPackagePath (14:39:46.793):
Addon wintenApps added to appModules package path
DEBUG - core.main (14:39:46.793):
Initializing NVDAHelper
DEBUG - core.main (14:39:46.904):
Speech Dictionary processing
DEBUG - speechDictHandler.SpeechDict.load (14:39:46.904):
Loading speech dictionary 'C:\Users\Markus\AppData\Roaming\nvda\speechDicts\default.dic'...
DEBUG - speechDictHandler.SpeechDict.load (14:39:46.904):
file 'C:\Users\Markus\AppData\Roaming\nvda\speechDicts\default.dic' not found.
DEBUG - speechDictHandler.SpeechDict.load (14:39:46.904):
Loading speech dictionary 'builtin.dic'...
DEBUG - speechDictHandler.SpeechDict.load (14:39:46.904):
3 loaded records.
DEBUG - core.main (14:39:46.913):
Initializing speech
DEBUG - speechDictHandler.SpeechDict.load (14:39:47.103):
Loading speech dictionary 'C:\Users\Markus\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\sapi4\sapi4-German-Standard_ Max (Adult Male), 6.1 - ETI-Eloquence.dic'...
DEBUG - speechDictHandler.SpeechDict.load (14:39:47.103):
file 'C:\Users\Markus\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\sapi4\sapi4-German-Standard_ Max (Adult Male), 6.1 - ETI-Eloquence.dic' not found.
DEBUG - synthDriverHandler.SynthDriver.loadSettings (14:39:47.103):
Loaded settings for SynthDriver sapi4
INFO - synthDriverHandler.setSynth (14:39:47.103):
Loaded synthDriver sapi4
INFO - core.main (14:39:47.103):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5 with six version 1.12.0
DEBUG - core.main (14:39:47.113):
Initializing braille input
INFO - brailleInput.initialize (14:39:47.113):
Braille input initialized
DEBUG - core.main (14:39:47.113):
Initializing braille
INFO - braille.initialize (14:39:47.113):
Using liblouis version 3.10.0
INFO - braille.initialize (14:39:47.118):
Using pySerial version 3.4
INFO - braille.BrailleHandler.setDisplayByName (14:39:47.123):
Loaded braille display driver noBraille, current display has 0 cells.
DEBUG - core.main (14:39:47.123):
Initializing displayModel
DEBUG - core.main (14:39:47.123):
Initializing GUI
DEBUG - core.main (14:39:47.163):
initializing Java Access Bridge support
DEBUG - core.main (14:39:47.323):
Initializing legacy winConsole support
DEBUG - core.main (14:39:47.323):
Initializing UIA support
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (14:39:47.335):
UIAutomation: IUIAutomation6
DEBUG - core.main (14:39:49.326):
Initializing IAccessible support
DEBUG - core.main (14:39:49.326):
Initializing input core
DEBUGWARNING - inputCore.InputManager.loadUserGestureMap (14:39:49.326):
No user gesture map
DEBUG - core.main (14:39:49.326):
Initializing keyboard handler
DEBUG - core.main (14:39:49.326):
initializing mouse handler
DEBUG - core.main (14:39:49.357):
Initializing touchHandler
DEBUG - touchHandler.initialize (14:39:49.364):
Touch support initialized. maximum touch inputs: 10
DEBUG - core.main (14:39:49.364):
Initializing global plugin handler
DEBUG - addonHandler.Addon.addToPackagePath (14:39:49.364):
Addon wintenApps added to globalPlugins package path
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.__init__ (14:39:49.364):
W10: adding additional events
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.__init__ (14:40:07.656):
W10: added event ID 20026, assigned to UIA_dragStart
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.__init__ (14:40:07.656):
W10: added event ID 20027, assigned to UIA_dragCancel
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.__init__ (14:40:07.656):
W10: added event ID 20028, assigned to UIA_dragComplete
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.__init__ (14:40:07.656):
W10: adding class name Popup to known dialog class names
DEBUG - core.main (14:40:07.671):
Initializing core pump
DEBUG - core.main (14:40:07.671):
Initializing watchdog
DEBUG - core.main (14:40:07.671):
initializing updateCheck
INFO - core.main (14:40:07.671):
NVDA initialized
DEBUG - core.main (14:40:07.671):
entering wx application main loop
IO - speech.speak (14:40:07.725):
Speaking [LangChangeCommand ('de_DE'), 'Start  Fenster']
DEBUGWARNING - characterProcessing._getSpeechSymbolsForLocale (14:40:07.740):
No CLDR data for locale de_DE
...

IO - inputCore.InputManager.executeGesture (16:18:28.673):
Input: kb(laptop):alt+tab
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (16:18:28.850):
oleacc.AccessibleObjectFromEvent with window 10159810, objectID -4 and childID 0: [WinError -2147024809] Falscher Parameter
IO - inputCore.logTimeSinceInput (16:18:29.016):
0.343 sec since input
IO - speech.speak (16:18:29.016):
Speaking ['New Issue · nvaccess/nvda - Google Chrome']
IO - inputCore.logTimeSinceInput (16:18:29.189):
0.516 sec since input
IO - speech.speak (16:18:29.189):
Speaking ['New Issue · nvaccess/nvda  Dokument']
IO - inputCore.logTimeSinceInput (16:18:29.205):
0.532 sec since input
IO - speech.speak (16:18:29.205):
Speaking ['Title  Eingabefeld  erforderlich']
IO - inputCore.logTimeSinceInput (16:18:29.220):
0.548 sec since input
IO - speech.speak (16:18:29.220):
Speaking ['NVDA version alpha-18199,af9b85de problems sapi 4 and others ausgewählt']
IO - inputCore.InputManager.executeGesture (16:18:29.575):
Input: kb(laptop):home
DEBUG - editableText.EditableText._hasCaretMoved (16:18:29.641):
Caret move detected using bookmarks. Elapsed: 10 ms
IO - inputCore.logTimeSinceInput (16:18:29.641):
0.066 sec since input
IO - speech.speak (16:18:29.641):
Speaking [PitchCommand(offset=30), CharacterModeCommand(True), 'N', PitchCommand(), EndUtteranceCommand()]
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (16:18:29.641):
Unsupported speech command: PitchCommand(offset=30)
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (16:18:29.645):
Unsupported speech command: PitchCommand()
IO - inputCore.logTimeSinceInput (16:18:29.675):
0.100 sec since input
IO - speech.speak (16:18:29.675):
Speaking ['NVDA version alpha-18199,af9b85de problems sapi 4 and others nicht ausgewählt']
IO - inputCore.InputManager.executeGesture (16:18:30.060):
Input: kb(laptop):shift+end
IO - inputCore.logTimeSinceInput (16:18:30.097):
0.038 sec since input
IO - speech.speak (16:18:30.097):
Speaking ['NVDA version alpha-18199,af9b85de problems sapi 4 and others ausgewählt']
IO - inputCore.InputManager.executeGesture (16:18:33.428):
Input: kb(laptop):alt+tab
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (16:18:33.500):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (16:18:33.578):
oleacc.AccessibleObjectFromEvent with window 10225346, objectID -4 and childID 0: [WinError -2147024809] Falscher Parameter
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (16:18:33.728):
oleacc.AccessibleObjectFromEvent with window 6358074, objectID 252 and childID 0: [WinError -2147467259] Unbekannter Fehler
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (16:18:33.728):
oleacc.AccessibleObjectFromEvent with window 6358074, objectID 253 and childID 0: [WinError -2147467259] Unbekannter Fehler
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (16:18:33.728):
oleacc.AccessibleObjectFromEvent with window 6358074, objectID 254 and childID 0: [WinError -2147467259] Unbekannter Fehler
IO - inputCore.logTimeSinceInput (16:18:33.753):
0.325 sec since input
IO - speech.speak (16:18:33.753):
Speaking ['NVDA-Protokollbetrachter']
IO - inputCore.logTimeSinceInput (16:18:33.808):
0.380 sec since input
IO - speech.speak (16:18:33.808):
Speaking ['Eingabefeld  nur lesen  mehrzeilig']
IO - inputCore.logTimeSinceInput (16:18:33.808):
0.380 sec since input
IO - speech.speak (16:18:33.808):
Speaking ['INFO - __main__ (15:51:29.112):\r']
IO - inputCore.InputManager.executeGesture (16:18:34.088):
Input: kb(laptop):f5

^
other errors
pyton error:
DEBUGWARNING - Python warning (14:40:17.692):
C:\Program Files (x86)\NVDA\library.zip\api.py:270: DeprecationWarning: Yield() is deprecated
IO - inputCore.logTimeSinceInput (14:40:17.958):
0.540 sec since input
IO - speech.speak (14:40:17.958):
Speaking [LangChangeCommand ('de_DE'), 'NVDA  Minihilfe']
IO - inputCore.InputManager.executeGesture (14:40:18.157):
Input: kb(laptop):downArrow
DEBUGWARNING - Python warning (14:40:18.187):
C:\Program Files (x86)\NVDA\library.zip\keyboardHandler.py:528: DeprecationWarning: Yield() is deprecated
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:40:18.187):
oleacc.AccessibleObjectFromEvent with window 8520248, objectID 1 and childID 0: [WinError -2147467259] Unbekannter Fehler
DEBUG - editableText.EditableText._hasCaretMoved (14:40:18.187):
Caret move detected using event. Elapsed: 0 ms
IO - inputCore.logTimeSinceInput (14:40:18.187):
0.030 sec since input
IO - speech.speak (14:40:18.187):

ERROR - unhandled exception (14:48:32.608):
wx._core.wxAssertionError: C++ assertion "m_menuDepth > 0" failed at ..\..\src\msw\toplevel.cpp(1545) in wxTopLevelWindowMSW::DoSendMenuOpenCloseEvent(): No open menus?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\__init__.pyc", line 997, in Notify
  File "core.pyc", line 493, in run
  File "watchdog.pyc", line 54, in alive
SystemError: <_FuncPtr object at 0x05418A08> returned a result with an error set
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:48:32.708):
oleacc.AccessibleObjectFromEvent with window 8520248, objectID 707 and childID 0: [WinError -2147467259] Unbekannter Fehler
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:48:32.708):
oleacc.AccessibleObjectFromEvent with window 8520248, objectID 708 and childID 0: [WinError -2147467259] Unbekannter Fehler
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:48:32.708):
oleacc.AccessibleObjectFromEvent with window 8520248, objectID 709 and childID 0: [WinError -2147467259] Unbekannter Fehler
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:48:32.708):
oleacc.AccessibleObjectFromEvent with window 8520248, objectID 710 and childID 0: [WinError -2147467259] Unbekannter Fehler
IO - inputCore.InputManager.executeGesture (14:48:33.178):
Input: kb(laptop):control+end
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:48:33.243):
oleacc.AccessibleObjectFromEvent with window 8520248, objectID 711 and childID 0: [WinError -2147467259] Unbekannter Fehler

ERROR - eventHandler.executeEvent (14:51:34.663):
error executing event: typedCharacter on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x0110EC70> with extra args of {'ch': '\x17'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 980, in event_typedCharacter
  File "speech\__init__.pyc", line 695, in speakTypedCharacters
  File "api.pyc", line 247, in isTypingProtected
  File "baseObject.pyc", line 46, in __get__
  File "baseObject.pyc", line 149, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 854, in _get_isProtected
  File "baseObject.pyc", line 46, in __get__
  File "baseObject.pyc", line 149, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\ia2Web.pyc", line 58, in _get_states
  File "baseObject.pyc", line 46, in __get__
  File "baseObject.pyc", line 149, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 866, in _get_states
  File "comtypesMonkeyPatches.pyc", line 22, in __call__
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
DEBUG - treeInterceptorHandler.killTreeInterceptor (14:51:34.844):
Killed treeInterceptor: <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x011DEAB0>
IO - inputCore.logTimeSinceInput (14:51:34.852):

DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (14:55:49.869):
Unsupported speech command: LangChangeCommand ('de_DE')
DEBUGWARNING - RPC process 21532 (chrome.exe) (14:55:49.947):
Thread 16556, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::getLineOffsets, 1050:
Offset of 0 too big for buffer, returning false

DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getCaretOffset (15:01:57.249):
IAccessibleText::caretOffset failed
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 182, in _getCaretOffset
  File "comtypesMonkeyPatches.pyc", line 22, in __call__
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))

DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getFormatFieldAndOffsets (15:09:09.596):
could not get attributes
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 233, in _getFormatFieldAndOffsets
  File "comtypes\__init__.pyc", line 857, in __call__
  File "comtypesMonkeyPatches.pyc", line 22, in __call__
_ctypes.COMError: (-2147467263, 'Nicht implementiert', (None, None, None, 0, None))

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (15:09:25.530):
oleacc.AccessibleObjectFromEvent with window 20186860, objectID 9692 and childID 0: [WinError -2147024809] Falscher Parameter
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (15:09:25.586):
IUIAutomationElement.buildUpdatedCache failed given IDs of {30019, 30086, 30022, 30025, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079}

### System configuration
win 10 info will be in logfile
#### NVDA version:
NVDA version alpha-18199,af9b85de
#### Windows version:
10
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

**Comment by Adriani90** [comment]
cc: @leonardder, @feerrenrut, @josephsl this seems quite serious.

**Comment by josephsl** [comment]
Hi, please tell us which SAPI4 voices you are using so anyone with these voices can help you better. Thanks.

**Comment by DrSooom** [comment]
@josephsl: From the logfile:
> sapi4-German-Standard Max (Adult Male), 6.1 - ETI-Eloquence.dic

@markusg2: Next time, please upload bigger logfiles instead of posting their text directly into the issue description. Thanks.

**Comment by josephsl** [comment]
Hi, if it is a certain version of Eloquence, then we can’t help you. I advise contacting add-on authors for further assistance. Thanks.

**Comment by DrSooom** [comment]
@josephsl: Only (your) [wintenApps add-on](https://addons.nvda-project.org/addons/wintenApps.en.html) is used based on his logfile. So ETI Eloquence must have been installed via another screenreader, perhaps by JAWS. An older version of ZoomText (9.x) also installed IBM ViaVoice SAPI-4, which can be used by NVDA.

**Comment by josephsl** [comment]
Hi, in this case, if it has worked in 2019.2 beta 3, then it might be something we do need to look at, although it was reported that we may face issues when contacting synth makers (especially Nuance). Thanks.

**Comment by DrSooom** [comment]
Maybe I'm totally wrong, but I guess it has something to do with the different kind of handling Unicode between Python 2 and Python 3. Furthermore I think that IBM ViaVoice SAPI-4 respectively ETI Eloquence SAPI-4 only supports ANSI, which wasn't no problem with Py2-NVDA. But please correcct me if I'm wrong.

**Comment by zstanecic** [comment]
Arrrrgh!

That’s the sapi 4 culprit. 

Some synthesizers needs the ansi encoding to work perfectly, like the polish neurosoft syntalk, which is no loonger developed.

Btw, isn’t sapi 4 abandoned by MS?

I am for setting this as wontfix, as some synths are either not unicode, but some are.

**Comment by leonardder** [comment]
If we need to ensure ANSI for SAPI4 (if we do not do that already), it 
shouldn't be that difficult to do.

It would be most helpful to have such a voice to test with.

**Comment by DrSooom** [comment]
@leonardder: Please send me an [e-mail](https://danielmayr.at/kontakt.php).

**Comment by leonardder** [comment]
I've done some quick tests with IBM ViaVoice, and f I throw an unicode character at it, the voice parses it as being CP1252.

If I do `print("\u2800")`, the voice reads the result as â euros.

This seems to be the result of "\u2800".encode("utf-8").decode("cp1252").

No differences between Py2 and Py3, so I think unicode decoding isn't really the problem here.

**Comment by DrSooom** [comment]
If you can select IBM ViaVoice as TTS in NVDA, then read ⠀ (U+2800) directly in the web browser. Is this character spoken as "question mark"?

**Comment by leonardder** [comment]
NO. The CP1252 value of the character is spoken, so `â €`
This is expected and not a bug in NVDA. It looks like NVDA just throws Unicode at SAPI4, it's just the voice being unable to handle it.

**Comment by DrSooom** [comment]
Sorry, maybe I wasn't clear enough. The NVDA logfile (2018.1) always shows `u'\u2800` in the corresponding lines. The "question mark" is generated by the TTS itself – I guess outside of NVDA. By using the German IBM ViaVoice "Fragezeichen" is spoken, but you can't see this in the NVDA logfile here too. So NVDA is sending this Unicode character directly to the TTS.

And please enable/disable the option "Use spelling functionality if supported" in the Speech NVDA Settings. This makes a different when moving by character – TTS gets muted if enabled. Otherwise "question mark" respectively "Fragezeichen" is spoken. Quick test with NVDA 2019.2 RC1 portable.

**Comment by leonardder** [comment]
@markusg2 As you are the initial author of this issue, are you still suffering from these problems? Note that some SAPI4 problems have been fixed.

**Comment by leonardder** [comment]
@markusg2: Another friendly reminder to provide details about the status of this issue.

**Comment by Adriani90** [comment]
We do not have any updates on this issue from the initial author. Closing as abandoned since we cannot really reproduce it.
If this issue still occurs, please comment on it and we can reopen it. Thanks.
