### ISSUE TITLE
Not working build from source on 32-bit Windows

### ISSUE THREAD

**Issue by kvark128** [nvaccess/nvda#9990]
Because of the following bug in scons 3.0.4, impossible to build NVDA from source on 32-bit version of Windows:
https://github.com/SCons/scons/issues/3333
Is it possible to update scons to version 3.1.0 where this bug is fixed?

**Comment by josephsl** [comment]
CC @LeonardDer, and based on his comments, a good time to also update to VS 2019. Thanks.

**Comment by leonardder** [comment]
I don't think that appveyor has a vs2019 build ready yet, but I could be wrong.
I've been able to build NVDA with vs2019 with current scons if I install de 16.1 build tools from the vs2019 setup.

**Comment by leonardder** [comment]
As every build system is different and this is most likely related to setup issues (i.e. no bug in NVDA's build environment itself), please discuss these matters on the NVDA Development mailing list.

See also #9976.

This issue ask for an update of SCons. This is covered in #9446. Therefore, I'm closing this as duplicate.
