### ISSUE TITLE
A11y_Azure VM Image Builder_Azure Image Builder Preview_Screen Reader:When focus is on 'More Information' button present beside 'Azure subscription' ,'Image type' , 'Provisioner' and 'reference name' labels NVDA is reading wrong information of list items

### ISSUE THREAD

**Issue by saiprasanna93** [nvaccess/nvda#9994]
Environment Details:
URL: https://acctesting.visualstudio.com​
Browser Details: Google Chrome Version 74.0.3729.169(Official Build) (64-bit)​
​
Repro Steps:​​
1)Hit URL: https://acctesting.visualstudio.com and log in with appropriate credentials.​​
2)Open any project from the available projects​
3)Tab till Pipelines and press enter​
4)Tab till Releases and press enter​
5)Create a new release pipeline​
6)Select Empty Job and tab till Add an Artifact and press enter​
7)Select Azure Repos Git and fill the required fields and tab till 'Add' button and press enter​
8)Tab till stages and select job​
9)select 'Agent job' and add task​
10)Search for Image Builder Task and Press enter on Add button​
11)Select Azure Image Builder Task under Agent Job​
12)Tab till  'Azure subscription' ,'Image type' , 'Provisioner' and 'reference name' more information buttons​
12)Verify how NVDA is reading when focus is on 'more subscription' ,'Image type' , 'Provisioner' and 'reference name' buttons​
​
Actual Result:​
When focus is on 'More Information' button present beside 'Azure subscription' ,'Image type' , 'Provisioner' and 'reference name' labels NVDA is reading wrong information of list items 
​
Expected result: ​
When focus is on 'More Information' button present beside 'Azure subscription' ,'Image type' ,'Provisioner' and 'reference name' labels NVDA should read correct information of list items ​
​
User Impact: ​
Screen reader users will face problem if NVDA is reading incorrect information of list items 
​
MAS Reference:
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Comment by saiprasanna93** [comment]
![Bug_9994_When focus is on 'More Information' button present beside 'Azure subscription' label NVDA is reading wrong informatio of list items](https://user-images.githubusercontent.com/50437422/62118038-98f02380-b2da-11e9-8b52-6a6b1c20cd3d.png)

**Comment by saiprasanna93** [comment]
![Bug_9994_When focus is on 'More Information' button present beside 'Image type' label NVDA is reading wrong info of list items](https://user-images.githubusercontent.com/50437422/62118070-a9a09980-b2da-11e9-8912-935f11a96300.png)

**Comment by saiprasanna93** [comment]
![Bug_9994_When focus is on 'More Information' button present beside 'provisioner' label NVDA is reading wrong info of list items](https://user-images.githubusercontent.com/50437422/62118088-b32a0180-b2da-11e9-9746-6f04a1d7ebc3.png)

**Comment by saiprasanna93** [comment]
![Bug_9994_When focus is on 'More Information' button present beside 'reference name ' label NVDA is reading wrong info of list items](https://user-images.githubusercontent.com/50437422/62118101-bcb36980-b2da-11e9-9104-37722517cd9d.png)

**Comment by michaelDCurran** [comment]
Closing on request from reporter privately by email.
