### ISSUE TITLE
A11y_Azure VM Image Builder_Azure Image Builder Preview_Screen Reader: NVDA is reading some extra content which is not displayed on the screen when we close the 'Azure subscription button'

### ISSUE THREAD

**Issue by saiprasanna93** [nvaccess/nvda#9995]
Environment Details:
URL: https://acctesting.visualstudio.com​
Browser Details: Google Chrome Version 74.0.3729.169(Official Build) (64-bit)​
​
Note:​
Same issue is observed for all the 'information buttons' available in the page​
​
Repro Steps:​​
1)Hit URL: https://acctesting.visualstudio.com and log in with appropriate credentials.​​
2)Open any project from the available projects​
3)Tab till Pipelines and press enter​
4)Tab till Releases and press enter​
5)Create a new release pipeline​
6)Select Empty Job and tab till Add an Artifact and press enter​
7)Select Azure Repos Git and fill the required fields and tab till 'Add' button and press enter​
8)Tab till stages and select job​
9)select 'Agent job' and add task​
10)Search for Image Builder Task and Press enter on Add button​
11)Select Azure Image Builder Task under Agent Job​
12)Tab till  'Azure subscription button' and open it by using enter and close it by esc​
12)Verify whether NVDA is reading  some extra content or not when we close the 'Azure subscription button'​
​
Actual Result:​
NVDA is reading some extra content which is not displayed on the screen when we close the 'Azure subscription button'​
​
Expected result: ​
NVDA shouldn't read any extra content which is not displayed on the screen when we close the 'Azure subscription button'​
​
User Impact: ​
Screen reader users will get confused if NVDA is announcing some extra content which is not displayed on the screen

MAS Reference:
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Comment by saiprasanna93** [comment]
![Bug_9995_NVDA is reading some extra content which is not displayed on the screen when we close the 'Azure subscription button'](https://user-images.githubusercontent.com/50437422/62120068-8aa40680-b2de-11e9-8381-9a5257dd0c83.png)

**Comment by michaelDCurran** [comment]
Closing on request from reporter privately by email.
