### ISSUE TITLE
A11y_Azure VM Image Builder_Azure Image Builder Preview_Screen Reader: When focus lands on the'Image type' combo box NVDA is reading all the contents of list items

### ISSUE THREAD

**Issue by saiprasanna93** [nvaccess/nvda#9996]
Environment Details:
URL: https://acctesting.visualstudio.com​
Browser Details: Google Chrome Version 74.0.3729.169(Official Build) (64-bit)​
​
​
Repro Steps:​​
1)Hit URL: https://acctesting.visualstudio.com and log in with appropriate credentials.​​
2)Open any project from the available projects​
3)Tab till Pipelines and press enter​
4)Tab till Releases and press enter​
5)Create a new release pipeline​
6)Select Empty Job and tab till Add an Artifact and press enter​
7)Select Azure Repos Git and fill the required fields and tab till 'Add' button and press enter​
8)Tab till stages and select job​
9)select 'Agent job' and add task​
10)Search for Image Builder Task and Press enter on Add button​
11)Select Azure Image Builder Task under Agent Job​
12)Tab till  'Image type' combo box​
12)Verify how NVDA is reading When focus lands on the 'Image type' combo box ​
​
Actual Result:​
When focus lands on the 'Image type' combo box NVDA is reading all the contents of list items​
​
Expected result: ​
When focus lands on the 'Image type' combo box NVDA should not  read all the contents of list items, NVDA should read the list items when the focus is on that particular list item only​
​
User Impact: ​
Screen reader users will find difficulties if NVDA is reading all the contents of list items at once
​
​
MAS Reference:
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Comment by saiprasanna93** [comment]
![Bug_9996_When focus lands on the'Image type' combo box NVDA is reading all the contents of list items](https://user-images.githubusercontent.com/50437422/62124013-d5c21780-b2e6-11e9-977c-426097b3de69.png)

**Comment by michaelDCurran** [comment]
Closing on request from reporter privately by email.
