### ISSUE TITLE
When window asking about credentials gains focus after closing Outlook 2010 NVDA freezes

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#9999]
### Steps to reproduce:
1. Ensure that you have mail account added in Outlook, and that password for it isn't  saved.
2. Open Outlook 2010.
3. Wait for the window asking about password to open.
4. Alt-tab back to Outlook, start navigating through messages with arrow keys and then close Outlook with Alt+f4.
### Actual behavior:
NVDA freezes and never goes back, - not in a reasonable time anyway, I've waited about 20 minutes and had no patience to wait longer.
### Expected behavior:
No freeze

#### NVDA installed/portable/running from source:
Tried latest Python 2 Alpha installed, and latest master of Python 3 from source.
#### NVDA version:
Installed NVDA version alpha-18064,e579eb02, and  latest master as of 2019.07.30 from source

#### Windows version:
Windows 7 x64 in Polish
#### Name and version of other software in use when reproducing the issue:
Microsoft Outlook 32-bit in Polish
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Explained above.
### Additional info
- If UIAHandler is terminated before performing these steps freeze didn't occur.
- I've also tested with add-ons disabled - same effect.
- The attached log is from current master running from source

[nvda.log](https://github.com/nvaccess/nvda/files/3448738/nvda.log)

**Comment by Adriani90** [comment]
@lukaszgo1 is this still reproducible in NVDA 2019.3 Beta 4?

**Comment by feerrenrut** [comment]
Labeling as blocked, pending information about reproducibility.

**Comment by lukaszgo1** [comment]
This is still reproducible with latest Alpha running as a portable with all add-ons disabled. The errors are exactly the same, and as mentioned above terminating UIAHandler prevents this from occurring.

**Comment by feerrenrut** [comment]
Thanks for the update @lukaszgo1 You mentioned you tried the latest python 2 alpha I assume the issue was present? Is the issue present in 2019.2.1?

**Comment by lukaszgo1** [comment]
The issue is present in 2019.2.1. I've tried to reproduce it with 2016.2 (picked it at random) and the issue is also present there, so I assume it is not a  regression.

**Comment by codeofdusk** [comment]
This issue also applies on NVDA 2020.1 when using Outlook with a corporate Office365 account with MFA. (I think it's the same issue, but can open another one if needed)

STR:
1. Open Outlook and log in.
2. When the MFA prompt (in the embedded MSHTML control) appears, open Yubico Authenticator and object nav to read the OTP code.
3. Switch back to Outlook and try to enter the OTP code.

NVDA/Outlook freeze at this point.

This is a very serious issue for employers with very short (24 hours) login expiry. As a workaround, using the Microsoft Authenticator app with push notifications makes the process less painful (if approved by the sysadmin).

Cc @michaelDCurran.

**Comment by Adriani90** [comment]
We didn't get any updates from people who were able to reproduce this since many years, I am closing as abandoned. Feel free to comment in case you are still having this issue and we can reopen.
